### ISSUE TITLE
The "" file does not exist or is not readable.

### ISSUE THREAD

**Issue by ycruzb** [laravel/framework#31249]
- Laravel Version: 6.12.0
- PHP Version: 7.2.0
- Database Driver & Version: 10.1.35-MariaDB

### Description: 
I get this error: 

Symfony\Component\Mime\FileinfoMimeTypeGuesser::guessMimeType:50
vendor/symfony/mime/FileinfoMimeTypeGuesser.php:50

The "" file does not exist or is not readable.

when trying to upload a file bigger than 2mb. 

php.init important values:

upload_max_filesize=3000M
post_max_size=3000M

### Steps To Reproduce:

Upload a file bigger than 2mb

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ycruzb** [comment]
I've fixed this changing the temporal folder permissions.

**Comment by RaulChan** [comment]
> I've fixed this changing the temporal folder permissions.

which temporary folder?

**Comment by ycruzb** [comment]
@RaulChan the temporary folder of the OS, where the OS make a temporary copy of the file before moving it to the final location. Hope this can help you.

**Comment by RaulChan** [comment]
> @RaulChan the temporary folder of the OS, where the OS make a temporary copy of the file before moving it to the final location. Hope this can help you.
I will try... 
Thank you !

**Comment by RaulChan** [comment]
> @RaulChan the temporary folder of the OS, where the OS make a temporary copy of the file before moving it to the final location. Hope this can help you.

I will try...
thank you !

**Comment by jwjcmw** [comment]
If someone else gets this error and it doesn't turn out to be a permissions issue, check your php.ini...make sure that your upload_max_filesize is as big as your post_max_size.  I had 1000M for post_max_size (we deal with some big ol' video files), but only 100M for upload_max_size (I blame my old eyes).  The upload would churn for a long time, and then throw the error above.

**Comment by leonardomaier** [comment]
@jwjcmw thank you, saved my day!

**Comment by aacassandra** [comment]
you are amazing @jwjcmw , thanks for the knowledge

**Comment by joe94113** [comment]
@jwjcmw thank you

**Comment by AlexanderVasSan** [comment]
no me funciono lo del upload_max_filesize y post_max_size. Sigue el mismo error

**Comment by damms005** [comment]
@taylorotwell do you mind a PR that replaces the less helpful message `The "" file does not exist or is not readable` with a more helpful message? (e.g. [by comparing file size with configures sizes](https://github.com/laravel/framework/issues/31249#issuecomment-627409757))

**Comment by demateu** [comment]
> * Laravel Version: 6.12.0
> * PHP Version: 7.2.0
> * Database Driver & Version: 10.1.35-MariaDB
> 
> ### Description:
> I get this error:
> 
> Symfony\Component\Mime\FileinfoMimeTypeGuesser::guessMimeType:50 vendor/symfony/mime/FileinfoMimeTypeGuesser.php:50
> 
> The "" file does not exist or is not readable.
> 
> when trying to upload a file bigger than 2mb.
> 
> php.init important values:
> 
> upload_max_filesize=3000M post_max_size=3000M
> 
> ### Steps To Reproduce:
> Upload a file bigger than 2mb

This worked for me
