### ISSUE TITLE
MailFaker missing always*() 

### ISSUE THREAD

**Issue by mspasov** [laravel/framework#31247]
- Laravel Version: 6.4.0
- PHP Version: 7.3.13
- Database Driver & Version: n/a

### Description:

MailFaker does not fake `Mail::always*()` methods. There are several ways to work around this, but I don't like them. 

Is there any reason why those methods are not faked too?

### Steps To Reproduce:

```php
Mail::fake();
Mail::alwaysFrom('test@test.com');
```
Error: Call to undefined method Illuminate\Support\Testing\Fakes\MailFake::alwaysFrom()

**Comment by driesvints** [comment]
Always methods are defined on the mailer, not on mailables (what mail faking is for). If you want also this to be supported, feel free to open an issue on the ideas repo or attempt a pr.
