### ISSUE TITLE
Str::afterLast() return the string itself if no occurance observed

### ISSUE THREAD

**Issue by cosecantt** [laravel/framework#31256]
Laravel Version: **v6.12.0**
PHP Version: **7.2.9**
Description: _Looks like Str::afterLast() has bug_

Steps To Reproduce:
`Str::afterLast('Hello', '.')` returns `'Hello' `instead of `null`  or is that expected behavior?
Documentation says:

> The Str::afterLast method returns everything after the last occurrence of the given value in a string

However there is no any occurance and should return `null` in my opinion.

**Comment by basarozcan** [comment]
I think everyone's expects are different. For example

`$slice = Str::after('Hello', '.');` returns `Hello` too.

Maybe behaviour of nonoccurrence may be writtern on documentation.

**Comment by driesvints** [comment]
Current behavior seems to be okay. Feel free to send in a PR to the docs to clarify anything.

**Comment by emargareten** [comment]
@driesvints How about adding an optional parameter that will allow `null`/`''` to be returned?
