### ISSUE TITLE
HTTP tests don't fail when they should and when they do in real life usage.

### ISSUE THREAD

**Issue by keithmifsud** [laravel/framework#31263]
- Laravel Version: 6.0
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:

I've written a Feature test for updating a User (my setup for auth and access management is very simple..I.e. using more or less Laravel's out of the box implementation). This test..

```
    /**
     * @test
     */
    public function it_can_update_the_email_address()
    {

        $user = $this->existingUser->toArray();

        $this->actAsApiUser('system');

        $user['email'] = 'not.keith@tenant.com';

        $response = $this->json(
            'POST',
            '/api/user/update',
            $user
        );

        $response->assertStatus(200);

        $response->assertJson(
            [
                'user' => $user
            ]
        );

        $this->assertDatabaseHas(
            'users',
            $user
        );

        $this->assertDatabaseMissing(
            'users',
            $this->existingUser->toArray()
        );
    }
```

Points to this controller method:

```
    /**
     * Updates the user.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function updateUser(Request $request): JsonResponse
    {

        $user = $this->userDatabaseModel->find(
            $request->get('id')
        );

        $user->name = $request->get('name');
        $user->email = $request->get('email');

        if ($request->get('revoked_access') === true) {
            $user->revoked_access = now();
            $user->tokens->each(
                function ($token) {

                    /** @noinspection PhpUndefinedMethodInspection */
                    $token->delete();
                }
            );
        }

        /** @noinspection PhpUndefinedMethodInspection */
        $user->save();

        return response()->json(
            [
                'user' => $user
            ],
            200
        );
    }
```

However, I've mistakenly, had an extra `first()` method chained to the above `find()` method. For some reason, the feature test always passed. I only realised the extra chained `first()` method call when I was testing from the UI which is a separate API client.

### Steps To Reproduce:

As detailed above.. just change the part on the controller method from:

```
        $user = $this->userDatabaseModel->find(
            $request->get('id')
        );
```

To:
```
        $user = $this->userDatabaseModel->find(
            $request->get('id')
        )->first(); // <--added
```

I believe the test should have failed since the e2e manual test did. My response from the failing e2e test was:

```
message: "SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "users_email_unique"↵DETAIL:  Key (email)=(peter@jones.com) already exists. (SQL: update "users" set "name" = Peter Jones, "email" = peter@jones.com, "updated_at" = 2020-01-28 11:28:40 where "id" = cb5417d2-1f35-4fc6-a6bd-d3f631dbf678)"
```

The error above makes sense. Am I right to say that the test should of failed?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by keithmifsud** [comment]
Hi @driesvints .. thank you for your reply and not so much for closing the issue! This is not a support __ME__ question unless my understanding of the tests' assertions is wrong. It does not seem to be since my assertion should fail and it did not in tests but it did in real life.

I have fixed the issue my end but the __real__ issue is that the assertion is not asserting so I believe we/you/someone should look into it.

I kindly ask you to look into it, I don't think that I am mistaken, albeit possible. If I am not mistaken then all folks using this feature test are not really testing. This can be a big issue for production apps.

**Comment by 36864** [comment]
You used different data in your "manual e2e" test than you did in your feature test. At a guess I would say there is no user in your database with the email `not.keith@tenancy.com`, but there is at least one user, who isn't the first user in the database, with the email `peter@jones.com`

**Comment by keithmifsud** [comment]
Thanks for your reply @36864 .. .. in my scenario. I can update the email address as the user is only distinguishable by the UUID attribute which is also the Eloquent's model primary key and/or index in DB.

I just tested this again (this minute) and e2e wise it fails but not in `phpunit`.

For more background... this is the "existingUser":

```
    /**
     * Sets up the tests.
     *
     * @throws Exception
     */
    protected function setUp(): void
    {

        parent::setUp();

        $this->existingUser = User::create(
            [
                'id' => TestableUniqueIdentifier::generate()->toString(),
                'name' => 'Keith Mifsud',
                'email' => 'keith@tenant.com',
                'password' => Hash::make('password'),
                'access_type' => 'tenant',
                'tenant_identifier' => TenantIdentifier::generate()->toString(),
                'enterprise_identifier' => null,
                'revoked_access' => null
            ]
        );
    }
```

and the `find()` method..uses the primary key which is a column named `id` with a type of of `uuid`.

**Comment by 36864** [comment]
> I can update the email address as the user is only distinguishable by the UUID attribute which is also the Eloquent's model primary key and/or index in DB.

The error message you got clearly indicates a violation of a unique key on the email column.
