### ISSUE TITLE
Error on queue:work database

### ISSUE THREAD

**Issue by Litiano** [laravel/framework#31276]
- Laravel Version: 6.13.0
- PHP Version: 7.4.1
- Database Driver & Version: PDO SqlSrv 5.7.0
- OS: Windows 7 x64

### Description:
PHP on Windows does not support PCNTL functions.

### Steps To Reproduce:
$ php artisan queue:work database

In Worker.php line 182:

  Call to undefined function Illuminate\Queue\pcntl_alarm()

**Comment by kanidjar** [comment]
Can the documentation be updated as well?

https://laravel.com/docs/6.x/installation#server-requirements

PCNTL is not mentioned at all.
