### ISSUE TITLE
Illuminate/Http/Request - No easy way to access only the input data

### ISSUE THREAD

**Issue by gthedev** [laravel/framework#31272]
### Description:
There is no simple way to access _only_ the input data for a Request.

`Illuminate/Http/Request::input()` returns request (input) data and query data.
`Illuminate/Http/Request::all()` returns input, file and query data.

The only way to get only the input data (for example, to fill a Model) is to access the parameter bag directly, such as:
`$request->request->all()`

Which will not work if the request is GET and data is within the `$request->query` Bag, or JSON request and the data is within the `$request->json` Bag.

Perhaps opening up `Illuminate/Http/Request::getInputSource()` method to public would solve this, so that we can do:
`$request->getInputSource()->all()`
And get all the correct Request data excluding files and query string.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
