### ISSUE TITLE
Laravel 6 passport migration error

### ISSUE THREAD

**Issue by pnjeru** [laravel/framework#31283]
- Laravel Version: 6
- PHP Version: 7.2

### Description:
I have done a fresh laravel passport installation `composer require laravel/passport
` in my app but when i run `php artisan migrate` I get an error.

Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `oauth_auth_codes` add constraint `oauth_auth_codes_client_id_foreign` foreign key (`client_id`) references `oauth_clients` (`id`) on delete cascade)

Kindly assist me, i don't know what am doing wrong.

**Comment by driesvints** [comment]
There's already a bunch of issues open on the passport repo. We'll get this fixed.

**Comment by ZayRTun** [comment]
I am having the same issue. Looking forward to solutions.

**Comment by driesvints** [comment]
@ZayRTun this has already been fixed in the latest passport release.
