### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by x-jim** [laravel/framework#31288]
- Laravel Version: 5.8.*
- PHP Version: 7.2.25
- Database Driver & Version: Mysql 8.0.15

### Description:
Sometimes the app enter in this function getAttribute() without $this->attributes, when you register a user with Laravel Auth module. And I solved this from 5.6 Laravel version editing the function with:
`if(!$this->attributes) {
            return;
        }`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by x-jim** [comment]
Im using Laravel Version: 5.8.*
