### ISSUE TITLE
"Impossible to create the root directory" after upgrade to latest laravel (6.13.1)

### ISSUE THREAD

**Issue by spresnac** [laravel/framework#31285]
- Laravel Version: 6.13.1
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
After upgrading from laravel 6.12 to 6.13.1, this error come up (no change to code).
https://flareapp.io/share/VP6948mJ#F41

### Steps To Reproduce:
https://flareapp.io/share/VP6948mJ#F41

**Comment by driesvints** [comment]
@spresnac I don't see anything which has changed to the filesystem which could have caused this. Maybe a different dependency?

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
