### ISSUE TITLE
Testing with unencrypted cookies doesn't work

### ISSUE THREAD

**Issue by gjm** [laravel/framework#31282]
- Laravel Version: 6.11.0
- PHP Version: 7.4
- Database Driver & Version: n/a

### Description:

I have configured a cookie not to be encrypted in `App\Http\Middleware\EncryptCookies` middleware. This cookie is used in another middleware, along with other (normally encrypted) cookies. 

When I'm testing the middleware, I can't access both types of cookies. Either I can access the unencrypted one (using `disableCookieEncryption`) or the encrypted one. 

### Steps To Reproduce:
Configure the cookie name `plain` not to be encrypted in `App\Http\Middleware\EncryptCookies`:
```php
class EncryptCookies extends BaseEncrypter
{
    protected $except = [
        'plain',
    ];
}
```

With this test I can only access `plain` cookie (`encrypted` is `null`):
```php
public function testCanAccessCookies ()
{
    $this->disableCookieEncryption()
         ->withCookie('plain', 'plain value')
         ->withCookie('encrypted', 'encrypted value')
         ->get('/');
}
```

With this test I can only access `encrypted` cookie (`plain` is the encrypted string value):
```php
public function testCanAccessCookies ()
{
    $this->withCookie('plain', 'plain value')
         ->withCookie('encrypted', 'encrypted value')
         ->get('/');
}
```

**Comment by driesvints** [comment]
You seem to be correct. The except property isn't taken into account when using this method.

**Comment by gentcys** [comment]
@driesvints i want to help to solve this problem, so i create a PR about my solution. If there are some suggestions, that would be great.
