### ISSUE TITLE
Blueprint doesn't support Grammer's macro

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#31296]
* Laravel Version: 6.0 or 5.8
* PHP Version: 7.3.6
* Database Driver & Version: MySQL 8.0.16

### Description:

I'm using `macro` to extend `Illuminate\Database\Schema\Grammars\MySqlGrammar` and `Illuminate\Database\Schema\Blueprint` classes like this:

```php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\Grammars\MySqlGrammar;
use Illuminate\Support\Fluent;

Blueprint::macro('fulltext', function ($columns, $name = null, $algorithm = null)
{
    return $this->indexCommand('fulltext', $columns, $name, $algorithm);
});

Blueprint::macro('dropFulltext', function ($index)
{
    return $this->dropIndexCommand('dropIndex', 'fulltext', $index);
});

MySqlGrammar::macro('compileFulltext', function (Blueprint $blueprint, Fluent $command)
{
    return $this->compileKey($blueprint, $command, 'fulltext');
});
```

and use it on my migrations like this:

```php
Schema::table('clients', function (Blueprint $table) {
    $table->fulltext(['first_name', 'last_name']);
});
```

But it doesn't work because the `method_exists` used on `Blueprint` class doesn't care about dynamic calls and always returns `false` for methods added by macro: https://github.com/laravel/framework/blob/5b1b3675748649da19c9b6308d1ade25f41eabd5/src/Illuminate/Database/Schema/Blueprint.php#L122

I believe we should use `is_callable([$grammar, $method])` instead. Can I make a PR to fix this?

**Comment by driesvints** [comment]
The macroable behavior for the Blueprint class wasn't meant to be used like this. It was meant to provide extra methods on the Blueprint class and not on the different grammars. What you're asking really is Macroable behavior for the Grammer classes. You're free to open up an issue on the ideas repo about this or attempt a PR. Thanks.

**Comment by hafezdivandari** [comment]
@driesvints Grammer classes already have Macroable behavior and It's not what I'm asking. What am I asking is to change `method_exists` to `is_callable` to make `Blueprint` respect Grammers's macros.

**Comment by driesvints** [comment]
@hafezdivandari feel free to send in a PR with a failing test that will highlight the bug.

**Comment by hafezdivandari** [comment]
@driesvints sure.
