### ISSUE TITLE
Macroable exception if usen on Model

### ISSUE THREAD

**Issue by 4n70w4** [laravel/framework#31291]
- Laravel Version: 6.6.1
- PHP Version: 7.3.11

### Description:

Currently, when using `Macroable` trait in eloquent models, an exception occurs:

```
    "message": "Method App\\Organization::hydrate does not exist.",
    "exception": "BadMethodCallException",
    "file": "/var/www/app/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php",
    "line": 103,
```

### Steps To Reproduce:

add to Model:

```php
    use Macroable;
```

**Comment by 4n70w4** [comment]
Do you have any better ideas than this? https://github.com/laravel/framework/pull/31286

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
