### ISSUE TITLE
Singleton-related mocking broken in Unit tests

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#31294]
- Laravel Version: 6.12.0
- PHP Version: 7.3.13
- Database Driver & Version: sqlite - memory

### Description:
While writing a unit test, I had to mock out a singleton which holds cached data:

        $this->app->singleton('locations', function () {
            return Cache::remember('locations', now()->addDay(), function () {
                return Manager::api('location')->all()->keyBy('id');
            });
        }); 

where this exists in the AppServiceProvider, and Manager is an external SDK manager where the `api` method will change the resulting class based on the param. In order to have this run sucessfully, I need to have the singleton callback not be hit and mock it out.

In trying various ways of mocking the Cache facade like the docs have `Cache::shouldReceive...` as well as just calling `Cache::put` with the mocked data, the mocked data never comes through. I also tried to mock the Container itself, which doesn't work or at least leads to other failures as a result since nothing should probably be mocked on it in the first place. Even just trying to bind the data as a callback:

    App::singleton('locations', function () { return $locations; });

or via the similar `instance` method, don't seem to work either and my tests still insist on hitting the external api. Beyond that there is an odd functionality around when the callback is resolved, which seems to be right at the start of unit testing, and not per test, so that kind of leads me to believe that this swap is impossible to begin with as the code already runs prior to the unit test.

### Steps To Reproduce:
Have a singleton defined in the app service provider, and have a unit test that tries to change the value of the singleton.... see that almost anyway to achieve this fails.

**Comment by mfn** [comment]
My gut feeling is that your service was resolved before it hits your test which does the mocking; you need to figure our why/where it does happen.

Maybe another eagerly initialized service which gets initialized when the framework boots or forgot to make service provider deferred?

Otherwise I can just say, mocking singletons work as mocking anything else. You just need to make sure it's not "accidentaly" resolved before you register (=overwrite it with) your mocked version.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ragingdave** [comment]
This _**is**_ a bug already. The whole concept of a unit test itself is to test isolated pieces of the application, so saying that something else in another test hit the singleton first...then that defeats the entire concept of a unit test because state outside of the test is affecting the test itself. Which by definition sounds incorrect. So what was suggested (deferring the service provider or somehow preventing unrelated tests from accessing the singleton) doesn't really apply because at the core, a singleton is being persisted across unit tests when IMHO it shouldn't which is the bug to begin with.
Furthermore, if you need to test multiple values of a singleton between tests (for example, testing if data exists in the singleton and then separately the case of data not existing), that is also currently unable to happen.

I'm not really sure why this was closed as it is a bug as outlined in the initial issue details as well as in this follow up.

**Comment by driesvints** [comment]
@ragingdave can you please just try on one of the channels first so others can pitch in? @mfn has already provided some feedback. I think others can help as well. Feel free to report back after you've reached the same conclusions.

**Comment by ragingdave** [comment]
I actually did try the discord chat in both the help chat and internals chat yesterday prior to putting in a ticket and got literally nothing from that avenue. As I mentioned in my reply, the feedback provided by @mfn is useful in that it pointed out the true bug around singleton mocking not specifically the mocking, but once a singleton is resolved, you can never change it in any way for different unit tests cases. This can be demonstrated through testing a singleton in 2 unit tests where one tests around conditions where the data is missing and where data might exist. Either way the bug is that singletons aren't reset per unit test, meaning that the unit test has shared state between tests which defeats the purpose of a unit test in the first place. The database already works to remigrate per unit test, so why would singletons be any different?

**Comment by taylorotwell** [comment]
App service provider is resolved before your test runs. See setUp of base test class and "refreshApplication" method.

**Comment by ragingdave** [comment]
Yes I did see that. As it turns out, I had the singleton being used in a partial mock that was being mocked prior to setting the singleton, which meant that the singleton instance on the mocked model was being set prior to mocking the singleton which gave the impression of the singleton instance not working. As it turns, out just reordering the mocking so that high level things (mocking singletons) happen at the very start of the test, then proceeding to the actual content or other mocks for the test works and addresses the issue.

**Comment by mfn** [comment]
> so saying that something else in another test hit the singleton first...then that defeats the entire concept of a unit test because state outside of the test is affecting the test itself

FTR this is not what I said or implied; that's a misinterpretation.

I said:
> My gut feeling is that your service was resolved before it hits your test

This can already happen due to service providers eagerly initializing some code.

It seems you solved it already, glad for you 👍
