### ISSUE TITLE
Pass content to test case http calls

### ISSUE THREAD

**Issue by esbenp** [laravel/framework#31303]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:

`\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests` will, e.g. when calling `$this->post`, not serialize the data as content. This means `$request->getContent` does not mimick the expected behaviour as in live environment - since it will be empty. This can be a problem if your test needs the raw content of a request - e.g. when testing a webhook endpoint that validates the request. This is because normally we rely on `getContent` to do a HMAC check.

But what about just doing something like `base64_encode(hash_hmac('sha256', json_encode($request->all()), 'secret', true))`? The issue here is that this data is passed through middleware which will potentially alter it. E.g. trim middleware or converting empty strings to null will subtly alter the data of the request which will make the test case pass but fail in live environment.

I am not sure if there is another way to get the data (sorry if so). And I am unsure if its a dumb move to alter `MakesHttpRequests` to do something like this `return $this->call('POST', $uri, $data, [], [], $server, json_encode($data));`?

### Steps To Reproduce:

Call `$this->post` inside a test case with data. `$request->getContent()` will return `""` in the handler

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by esbenp** [comment]
Hi, this is also an issue in 6.x

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by esbenp** [comment]
I am not sure I understand @driesvints ? Do you mean you do not consider this a bug or what?

**Comment by driesvints** [comment]
@esbenp heya, it's best that you first try to discuss this on one of the channels above. Maybe some others can provide some insights there. If you can then confirm it as a bug feel free to reply back.

**Comment by esbenp** [comment]
I already did investigate and identified the problem. The behaviour of `\Illuminate\Http\Request::getContent` differs from test environment and live environment. I am not sure how to confirm that this is a bug??? Is it a certain person that will make that call or what?

**Comment by esbenp** [comment]
For ref here are my posts:

https://laravel.io/forum/request-getcontent-differs-in-live-and-tests
https://laracasts.com/discuss/channels/testing/request-getcontent-differs-in-live-and-tests

**Comment by andrey-helldar** [comment]
Laravel 9.0.2

Same problem. `$request->getContent()` returns an empty string.
