### ISSUE TITLE
Wildcard listener still called after Event::forget('foo*')

### ISSUE THREAD

**Issue by JonathanGawrych** [laravel/framework#31307]
- Laravel Version: 6.13.1
- PHP Version: 7.2.23
- Database Driver & Version: N/A

### Description:
Calling `Event::forget` with a wildcard eventName does not clear the wildcard cache in Dispatcher, thus even after forgetting wildcards, the listener will still be called. The wildcard cache is only cleared when _adding_ a listener instead

### Steps To Reproduce:
You can simply reproduce this in tinker (print suppressed):
```php
20:10 $ php artisan tinker
>>> $output = new \Symfony\Component\Console\Output\ConsoleOutput();
>>> Event::listen('foo', function () use ($output) { $output->writeln('foo listener'); });
>>> Event::listen('foo*', function () use ($output) { $output->writeln('foo* listener'); });
>>> Event::dispatch('foo');
foo listener
foo* listener
>>> Event::forget('foo');
>>> Event::forget('foo*');
>>> Event::dispatch('foo');
foo* listener
>>> Event::listen('foo*', function () { /* this clears the wildcard cache */ });
>>> Event::forget('foo*');
>>> Event::dispatch('foo');
>>> exit;
Exit:  Goodbye
```

My current workaround is a little clunky by listening with a noop function to clear the cache, then immediately forgetting it.

**Comment by driesvints** [comment]
I can reproduce this. The `wildcardsCache` doesn't seems to be reset. I'll fix this. Thanks for reporting 👍
