### ISSUE TITLE
Cache::remember does not work with null

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [laravel/framework#31312]
* Laravel Version: 5.8 but the offending code is still unchanged in master
* PHP Version: 7.3
* Cache Driver: Redis

### Description

When storing `null` using `Cache::remember($key, $ttl, $callback)` the callback is executed every time, even if the value (`null`) is already stored in the cache.

### Steps to reproduce

Here is the offending code in "src/Illuminate/Cache/Repository.php"

    public function remember($key, $ttl, Closure $callback)
    {
        $value = $this->get($key);

        // If the item exists in the cache we will just return this immediately and if
        // not we will execute the given Closure and cache the result of that for a
        // given number of seconds so it's available for all subsequent requests.
        if (! is_null($value)) {
            return $value;
        }

        $this->put($key, $value = $callback(), $ttl);

        return $value;
    }

As you can see, if the value that is returned from the cache is `null`, the callback is still executed. Here is code to reproduce the problem. `$callback` should only be executed once, but is actually called twice:

    $callback = function() {
        echo "Running the callback\n";
        return null;
    };

    Cache::remember('test', 1000, $callback);
    Cache::remember('test', 1000, $callback);

Expected output:

    Running the callback

Actual output: 

    Running the callback
    Running the callback

The same problem occurs when using `rememberForever`.

### Possible Solution

I couldn't find this mentioned in the documentation, so I think as a first step it should be explained more clearly.

With the exception of `Memcached` it should also be possible to add an actual "has($key)" method to `Illuminate\Contracts\Cache\Store`. This could then be used to determine if the callback should be executed or not. A new config setting would have to be introduced to toggle between new and old behaviour (with the current behaviour being the default). `Memcached` could get an additional config setting which would default to the current behaviour (null == value doesn't exist). If the new bahaviour (callback is only executed once) is wanted, it could use some placeholder value for null at the expense of some performance and memory.

As an alternative to changing the behaviour of `Cache::remember($key, $ttl, $callback)` I suggest a fourth parameter `$recallNull = false`. Leaving it at `false` would change nothing. If set to `true`, it would not run the callback if the value was already in the cache (even if it were `null`).

**Comment by driesvints** [comment]
This is unfortunately not possible with the remember method. If we had to implement this we'd have to remove the null check and then the remember method just wouldn't work. We can't support a `null` here.

**Comment by ThisIsJustARandomGuy** [comment]
Why is it not possible? Apart from memcached, every cache driver that comes with Laravel could support a proper `has($key)` method (which would have to be added). For memcached it could be solved in a different way (store a placeholder value instead of `null` and use that to determine if a key is not set (`get($key)===null`) or if it's actually `null` (`get($key)===SomePlaceholder`).

Then the null check could be replaced with a call to `$this->store->has($key)`

**Comment by driesvints** [comment]
It would require us to implement a new call like you said. You're free to attempt a PR but I doubt it'll pass.

**Comment by ThisIsJustARandomGuy** [comment]
Thanks, maybe I'll be motivated this weekend.

I think it should at least be mentioned in the docs, though (hopefully I'll be able to make a PR for that as well)

**Comment by lovekrissh143** [comment]
Hey @ThisIsJustARandomGuy have you managed to get a solution for this, cuz I'm with the same problem dude and looking for a workaround. So we have to get it done somehow because Laravel is all about customization and that's why people love it.
So this is community driven and must suffice the community needs, isn't it??

**Comment by lovekrissh143** [comment]
@driesvints please help get this one fixed. Hope you would understand :)

**Comment by ThisIsJustARandomGuy** [comment]
@lovekrissh143 I just used -1 to represent null since it achieved the same
in my case.

>

**Comment by lovekrissh143** [comment]
@ThisIsJustARandomGuy 
@driesvints @taylorotwell 

I did something like this to achieve the results I need: 

app.php

'should_cache' => config('cache.default') === 'none',

vendor\laravel\framework\src\Illuminate\Cache\Repository.php

in remember function :

```
if(config('app.should_cache')){

    return $callback();
}
```

![shouldCache](https://user-images.githubusercontent.com/48975027/106763576-fa761880-665c-11eb-987a-e63bb3a0b8c6.png)


But we definitely need a solution for this from the Great Laravel Team. :)

**Comment by ojsoft** [comment]
I also stumbled across this problem today and yes... it needs to be fixed.
Imagine I want to cache this.
Cache::remember(‘my-model’, 300, function() {return App\Model\MyModel::find(1);});
It returns a model or zero. The cache is worthless if null is not cached, because then the query is made again and again. The behaviour is not only unintuitive, it is simply wrong.

**Comment by andrewevans** [comment]
I have resorted to the "store -1 to mean this thing doesn't exist" for the falsey keys that get hit the most. Pretty ugly but it works. Oddly, I have to check for both integer -1 _and_ string "-1" in the template.
