### ISSUE TITLE
Joins on Eloquent relations not bein applied on eager count

### ISSUE THREAD

**Issue by vaites** [laravel/framework#31311]
- Laravel Version: 6.x
- PHP Version: 7.3.1
- Database Driver & Version: MySQL 5.7

### Description:

If you define a model with a relation that includes joins with other tables, the relation works well when loading as usual (`Model::findOrFail(1)->relation`) or with eager loading (`Model::with('relation')->findOrFail(1)->relation`) but fails with eager count (`Model::withCount('relation')->findOrFail(1)->relation_count`);

The relation count uses a subquery that doesn't include the join (see example above).

As said in the [Laracasts discussion](https://laracasts.com/discuss/channels/eloquent/eloquent-relations-using-joins-not-working-with-eager-count), there are workarounds to solve this, but the relation count must work with joins or, if is not possible, throw an exception when using it.

### Steps To Reproduce:

Start with an empty Laravel project (which includes users table). Then add the comments table:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCommentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('comments', function (Blueprint $table)
        {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->text('comment');
            $table->timestamps();

            $table->foreign('user_id')->references('id')->on('users');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('comments');
    }
}
```

Then, a table for using the join:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAlertsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('alerts', function (Blueprint $table)
        {
            $table->increments('id');
            $table->unsignedInteger('comment_id');
            $table->tinyInteger('status_id');
            $table->timestamps();

            $table->foreign('comment_id')->references('id')->on('comments');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('alerts');
    }
}
```

The user model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->join('alerts', function(JoinClause $join)
        {
            $join->on('alerts.comment_id', 'comments.id');
            $join->where('alerts.status_id', 1);
        });
    }
}
```

The comment model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
```

The alert model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Alert extends Model
{
    public function comment(): BelongsTo
    {
        return $this->belongsTo(Comment::class);
    }
}
```

Then, add 1 comment associated to the first user and then 1 alert associated with the comment and set the status_id to zero.

Now you have the working example:

```php
$user = User::with('comments')->findOrFail(1);
$comment_count = $user->comments->count(); // returns 0 (good)
      
$user = User::withCount('comments')->findOrFail(1);
$comment_count = $user->comments_count; // returns 1 (bad)	
``` 

The first block makes 2 queries, one for the user and other for the comments WITH the join:
```sql
select * from `users` where `users`.`id` = ? limit 1;
select * from `comments` inner join `alerts` on `alerts`.`comment_id` = `comments`.`id` and `alerts`.`status_id` = 1 where `comments`.`user_id` in (1);
```

The block makes only 1 query using a subquery WITHOUT the join:

```sql
select `users`.*, (select count(*) from `comments` where `users`.`id` = `comments`.`user_id`) as `comments_count` from `users` where `users`.`id` = 1 limit 1
```

**Comment by driesvints** [comment]
Can you post your exact framework version please?

**Comment by vaites** [comment]
I detected it with 6.7.0, and the problem remains in 6.12 (I used it to make the example)

**Comment by staudenmeir** [comment]
It's not explicitly stated in the documentation, but Eloquent relationships aren't meant to have additional JOIN clauses. A `whereHas()` subquery would be the right approach.

In your example, do _all_ of a comment's alerts have to match the constraint or _one_ of them?

**Comment by vaites** [comment]
There are many ways to solve the problem, from using hasManyThrough to modifying the data model. But that is not the issue here. If you don't have to build relationships with joins, the framework shouldn't allow it. It makes no sense that it works with and without eager load but not with eager count. Either the framework does not allow it at all or if its allowed it you should do it well.

**Comment by driesvints** [comment]
Thanks @staudenmeir 

@vaites feel free to send in a PR to the docs

**Comment by deleugpn** [comment]
Just hit this issue and it is indeed a bit confusing.
