### ISSUE TITLE
Eloquent relationship with where, result is non object

### ISSUE THREAD

**Issue by gzai** [laravel/framework#31310]
- Laravel Version: 6.13.1
- PHP Version: 7.2.20
- Database Driver & Version: 10.3.16-MariaDB

### Description:
when use where in relationship, result is non object

### Steps To Reproduce:

Result $family is object
```
Model : 

public function getFamilyAttribute()
    {
        $arr = [];
        $family_status = MsFamilyStatus::get();
        if ( $family_status->count() ) {
            foreach ($family_status as $key => $value) {
                $family = $this->attr_family
                    // ->where('ms_family_status_id', $value->id )
                    ->first();
                $arr[] = $family->name;
            }
        }
        return collect( $arr );
    }

public function attr_family()
    {
        return $this->hasMany('App\Models\ProfileAttrFamily', 'profile_id');
    }
```

Result $family is not object but array
```
public function getFamilyAttribute()
    {
        $arr = [];
        $family_status = MsFamilyStatus::get();
        if ( $family_status->count() ) {
            foreach ($family_status as $key => $value) {
                $family = $this->attr_family
                    ->where('ms_family_status_id', $value->id )
                    ->first();
                // $arr[] = $family->name; // error non object
                $arr[] = $family['name']; // result
            }
        }
        return collect( $arr );
    }

public function attr_family()
    {
        return $this->hasMany('App\Models\ProfileAttrFamily', 'profile_id');
    }
```
```
Controller : 

print_r( $model->family );
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
