### ISSUE TITLE
Tagged Cache getMultiple broken

### ISSUE THREAD

**Issue by LasseRafn** [laravel/framework#31314]
- Laravel Version: 6.13 (but I saw it in 5.7 as well)
- PHP Version: 7.4

### Description:

Using the TaggedCache will break `getMultiple($keys)`.

I can't seem to 

### Steps To Reproduce:

1. Use normal non-tagged cache: `Cache::getMultiple(['test'])` and you will get an array with one key ('test') with a null value.

2. Use tagged cache: `Cache::tags('some-tag')->getMultiple(['test'])` and you will get an array with one key ('') with a null value.

![EPn0ECZWAAEh5I7](https://user-images.githubusercontent.com/2689341/73554884-72a37000-4444-11ea-988d-3bcfac199e56.jpeg)
I apologise for the attachment of image.

### Causes

I think the cause is that in `Illuminate\Cache\Repository->getMultiple` it calls the `many` method on itself, which handles it all fine. HOWEVER tagged caches uses the trait `RetrievesMultipleKeys` which overrides this `many` method! 

It takes an array of keys and loops them.. however since we in the `getMultiple` also set default values, it actually loops the values rather than the array keys, hence tries to get(null) (null is default value)

**Comment by LasseRafn** [comment]
Solution COULD be to change line 19 in `Illuminate\Cache\RetrievesMultipleKeys` from

```php
foreach ($keys as $key) {
```

to

```php
foreach ($keys as $key => $value) {
```

However I am unsure if this will break something else

**Comment by driesvints** [comment]
Which driver are you using? Is this for all drivers?

**Comment by LasseRafn** [comment]
Definitively for all drivers, but I tested with array and redis driver.

Driver is irrelevant as they all use the same trait it seems (These do: NullStore, FileStore, ApcStore, TaggedCache, ArrayStore, DatabaseStore, and RedisTaggedstore extends TaggedCache)

**ALL drivers affected**

**Comment by driesvints** [comment]
@LasseRafn if I change the line above I get three failing tests in the `tests/Cache` directory.

**Comment by LasseRafn** [comment]
Figured that would probably break something too 🙁

I’ll submit a pr with alternative fix

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by anik786** [comment]
This still seems to be an issue on Laravel 8
