### ISSUE TITLE
CORS not working on laravel V6 but works on laravel V5.8

### ISSUE THREAD

**Issue by GabMic** [laravel/framework#31327]
- Laravel Version: 6.13
- PHP Version: 7.4.2
- Database Driver & Version: MySQL

### Description:
Only GET request accepted when CORS are enabled. No `POST, PUT. OPTIONS`.
Using the laravel-cors package, and set up it as usual like in the docs. 

### Steps To Reproduce:
Use laravel-cors or some kind of cors middleware on laravel version 6 and send a POST\PUT request.

**Comment by driesvints** [comment]
Please open up an issue on their repo.
