### ISSUE TITLE
Temprorary file not generated for UploadFile::fake()

### ISSUE THREAD

**Issue by dannyyounes** [laravel/framework#31329]
- Laravel Version: 6.13.1
- PHP Version: 7.3.14
- MYSQL 5.7:

### Description:
There seems to be an issue with using the UploadFile::fake()->image(). When this is run, the temporary file is not created so when the upload script needs to move the file to the appropriate location, it states the the file can't be found

The error I am getting is:

Unable to find a file at path [php624B.tmp]. Failed asserting that false is true.

I have tested this on Laragon virtual server and vagrant ubuntu/Xenial and I get the same issue on both

### Steps To Reproduce:

```
 $this->WithoutExceptionHandling();

    //login as admin
    $admin = $this->signInAsAdmin();

    Storage::persistentFake('public');

    $attributes =  [
        'group_name' => $this->faker->name,
        'group_description' => $this->faker->paragraph,
        'group_privacy' => '0',
        'group_cover' => $file = UploadedFile::fake()->image('random.jpg')
    ];

    //create new group
    $response = $this->post('/admin/groups', $attributes);

    unset($attributes['group_cover']);

    Storage::disk('public')->assertExists($file);

    //check the data exists in database
    $this->assertDatabaseHas('groups', $attributes);

    //how is the uploaded file written to database

    //check the data exists in database
    $this->assertDatabaseHas('media', ['file_name' => $file]);

    //make sure the title appears on the group list
    $this->get('/admin/groups')->assertSee($attributes['group_name']);
```

**Comment by driesvints** [comment]
I see you're using multiple requests in a single test. Unfortunately this doesn't really works well and is discouraged. Please separate your requests into different tests.
