### ISSUE TITLE
Handler::$dontReport fails to work with SoapFault exceptions

### ISSUE THREAD

**Issue by bhartvigsen** [laravel/framework#31349]
- Laravel Version: 6.4.1
- PHP Version: 7.2.14
- Database Driver & Version: N/A

### Description:
If you add \SoapFault::class to $dontReport, SoapFault exceptions are still caught and handled by the Laravel exception handler, preventing try / catch logic from working.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bhartvigsen** [comment]
Hi I'm reporting a bug, I don't need support
