### ISSUE TITLE
Model association queries cross-library problems

### ISSUE THREAD

**Issue by zhongjq** [laravel/framework#31346]
- Laravel Version: #.#.#
5.8
- PHP Version: #.#.#
7.3
- Database Driver & Version:
mysql5.6
### Description:

vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
![image](https://user-images.githubusercontent.com/1228323/73747183-df46a380-4791-11ea-9df9-9151970d63fb.png)

If the correlation between models is multiple data, this row causes the associated model if it's the default database, you have to set the $connection property, otherwise the associated model is forced to change to the database connection of the current model, which makes no sense so far I'm rewriting this method in the model, comment out this row

![image](https://user-images.githubusercontent.com/1228323/73747086-98f14480-4791-11ea-8d62-7556a93255c8.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
