### ISSUE TITLE
Template of controller --api

### ISSUE THREAD

**Issue by Daniel-Mendes** [laravel/framework#31351]
- Laravel Version: 6.2
- PHP Version: 7.4

### Description:
So when I use the artisan command for creating a api controller the default response is  ``` \Illuminate\Http\Response ```but for an api like from axios by default you want a ``` \Illuminate\Http\JsonResponse ``` no 
?, like ``` response()->json() ```, is it just a choice ?, should I just change the default template ?
```php
@return \Illuminate\Http\Response instead of \Illuminate\Http\JsonResponse
```
### Steps To Reproduce:
```php
php artisan make:controller API/TestController --api
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
