### ISSUE TITLE
where(DB::raw()) in whereExists() outputs different result as compared to whereRaw()

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#31353]
- Laravel Version: 6.13.1
- PHP Version: 7.4

### Description:

Using `where(\DB::raw())` generates a different query when used in a `whereExists()` as compared to using `whereRaw()`

### Steps To Reproduce:

Following the example [as on the docs](https://laravel.com/docs/6.x/queries#where-exists-clauses)

```php
DB::table('users')
    ->whereExists(function ($query) {
        $query->select(DB::raw(1))
            ->from('orders')
            ->whereRaw('orders.user_id = users.id'); // generates correct sql
            //->where(\DB::raw('orders.user_id = users.id')); // generates incorrect sql (see below)
    })
    ->toSql();
```

**whereRaw sql:**

```sql
select * from `users` where exists (select 1 from `orders` where orders.user_id = users.id)
```

**where(\DB::raw(...)) sql**

```sql
# take note of the extra " is null" being added
select * from `users` where exists (select 1 from `orders` where orders.user_id = users.id is null)
```

Given that the intent of both queries is the same, shouldn't they generate the same sql?

**Comment by BrandonSurowiec** [comment]
That is intended behavior since you're only escaping the column of the "where". Use `whereColumn()` instead.

```
->whereColumn('orders.user_id', 'users.id')
```

**Comment by garygreen** [comment]
Hmm interesting. I guess Laravel isn't aware a second parameter isn't passed so assumes `null` and tags that onto the where. Thanks for the workaround
