### ISSUE TITLE
file_put_contents("cache_folder_path_which_is_not_present"): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0):

### ISSUE THREAD

**Issue by amitskycap** [laravel/framework#31350]
- Laravel Version: 5.8
- PHP Version: 7.2

This use case is really strange. It never occurs on all the networks but on some specific networks only. 
I have deployed my application in the production environment and for most of the users, it is working fine but I have a specific user, who reported an issue with application behavior on their home wifi. Following is the list where the app is working fine and where it is not.

At office 
On Wifi : Working fine
On Mobile data: Working Fine

At home
On Wifi : Not working
On Mobile Data: Working Fine

When at his home wifi he made a request, There is an error log generated Screenshot attached.  When in the directory I tried to look for that file, the file is not present. 

I have tried all the solutions, like 
php artisan cache:clear, 
php artisan config:clear, 
composer dump-autoload

Also
Permission 775 to folder
and
permission of folder to www:data group and user

I am unable to thin, what I can do to at least go in the right direction. Any kind of suggestions or help is appreciated so that I can go in the right direction to look for this issue. 

Mind it the issue is only on some specific wifi network. In the same region, other users are not facing this issue one or two users reported this issue but very rare.

![Screenshot 2020-02-04 at 8 10 44 PM](https://user-images.githubusercontent.com/56591295/73754479-7a3b7f80-478a-11ea-9112-0436020f24bb.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
