### ISSUE TITLE
Unexpected relationship behaviour

### ISSUE THREAD

**Issue by samloft** [laravel/framework#31364]
- Laravel Version: 6.7.0
- PHP Version: 7.3
- Database Driver & Version:

### Description:

When using a whereHas() and a with() on a query and one table has trimmed trialing white space and the other does not, whereHas will match, but the with (in this case belongsTo) does not find a match.

Would expect with() whereHas to not find anything, or with() to follow the same rules.

As a side note, hasMany() does seem to follow the same logic as whereHas().

I'm well aware I can trim all data before passing over to the application, but would still expect to see the same logic.

### Steps To Reproduce:

Two Tables

- Products
code |description
TEST   ,A description

- Prices
code|price
TEST,1.22

A belongsTo relationship

`
public function prices(): BelongsTo
    {
        return $this->belongsTo(Price::class, 'code', 'code');
    }
`

A products show query.

`
public static function show()
    {
        return self::where('code', 'TEST')->whereHas('prices')->with('prices')
    }
`

The above with return the product, but the relationship will be blank.

**Comment by staudenmeir** [comment]
What database are you using?

**Comment by samloft** [comment]
Appologies for the delay.

I have tried on both

mariadb 10.4
&
mariadb 10.3

**Comment by staudenmeir** [comment]
This is not a Laravel issue but caused by the weird behavior of MySQL/MariaDB: https://bugs.mysql.com/bug.php?id=64772

When Laravel matches the eager loading results to their parents, it uses strict comparison (as expected).

**Comment by samloft** [comment]
Not true i'm afriad.

I have just performed the same test on

MSSQL 2008
MSSQL 2017

Get the exact same results

whereHas('relationship') matches (as the belongsTo has found a match).
But with('relationship') returns null.

**Comment by staudenmeir** [comment]
Yes, SQL Server shows the same behavior. PostgreSQL and SQLite behave correctly (IMO).

For a string column that you are using as a (primary) key, I strongly advise you to trim the values before inserting them into the database.

**Comment by samloft** [comment]
Well, postgres auto white spaces depending on the char length.

So postgres does work, but only because it pads it anyway

`
customer | "SCO100    "
name | "STUFFANDTHINGS                                                                                      "
address1 | "STUFFANDTHINGS                                                                                      "
customer_test |  
    customer | "SCO100    "
    stuff | "fdsfdsfds                                                                                           "
`

And obviously in an ideal world, all data would be trimmed of white space, but in an enterprise enviroment when you are having to use existing data, we dont all have that luxury. 

The argument i'm trying to make is.

If whereHas('relationship') is true, then we should expect with('relationship') to be returning that relationship. No matter the rules or database used.

**Comment by driesvints** [comment]
I agree with @staudenmeir. Please trim your values before inserting them into the DB.

**Comment by samloft** [comment]
As stated, it's not always possible to be in control of what data is in a database.

The fact is, whereHas() and with() are not consistant, it shouldn't matter the what the data is.
