### ISSUE TITLE
Cache directory with conflicting ownership

### ISSUE THREAD

**Issue by valleema** [laravel/framework#31367]
- Laravel Version: 5.5
- PHP Version: 7.0.33
- Database Driver & Version: mysql 15.1

### Description:
Scheduled tasks in Kernel.php, ran by one user (user is set up in supervisor conf files) are automatically creating folders in `cache/data`. For instance, it creates `b0/f9` folder arborescence, with nothing in it, owned by me, `valleema`.

On ther other side, the app is launched by the user `www-data`. 
One of my controllers uses the cache. When I add something to the cache, it happens that it wants to create `b0/c4/6f0a24451a788a5dca4bd27733ee8acc9d160dae`. But it cannot: since `b0` top-level folder is owned by user `valleema`, user `www-data` cannot write in it... And fail.

### Steps To Reproduce:
Have 1 supplementary user than the one launching the app (not belonging to a common group).

Use Cache in a controller.

Change ownership to the top-level folder to the other user.

Try to put something in the cache again, it fails.

**Comment by jayked** [comment]
Execute the following commands:
```bash
sudo usermod -a -G www-data {user: valleema in your case}
sudo chown -R www-data: bootstrap/cache storage
sudo chgrp -R www-data bootstrap/cache storage
sudo chmod -R ug+rwx bootstrap/cache storage
```
This will add `valleema` to the `www-data` group and change ownership of directories `bootstrap/cache` and `storage` to the `www-data` user which both the `www-data` user and `valleema` user can access because they are both member of the `www-data` group.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
