### ISSUE TITLE
Error when schedule laravel job

### ISSUE THREAD

**Issue by mb-jignesh** [laravel/framework#31360]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version:

### Description:

I have created one job that contains only insert value in the table please check bellow.

```
protected function schedule(Schedule $schedule) {
     $schedule->call('test:mp3')->cron('* * * * *');
}
 public function handle() {
        $param =  array();
        $param['email_reference']       = "test";
        $param['email_address']         = "test@matrubharti.com";
        \DB::table('table name')->insert([ $param ]);
 }
```

### ERROR
**[2020-02-05 15:46:02] production.ERROR: Function test:mp3() does not exist {"exception":"[object] (ReflectionException(code: 0): Function test:mp3() does not exist at /var/www/html/MB-WEB/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:143)
[stacktrace]**

**Comment by CodingMonkTech** [comment]
To run artisan command you need to following syntax

`schedule->command('test:mp3)->daily();`

**Comment by mb-jignesh** [comment]
> As test:mp3 is a Artisan Command you need to use following syntax.
> 
> `$schedule->command('test:mp3)->daily();`
