### ISSUE TITLE
[ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string.

### ISSUE THREAD

**Issue by kazantip151** [laravel/framework#31366]
- Laravel Version: 5.8.36
- PHP Version: 7.3.9
- Database Driver & Version: MSQL (sqlsrv)

### Description:
Hi, i don't know if it bug or its my fault. I am using query builder (not eloquent) in my method i do `select` and in where statement i have raw query like this: 
`->where(DB::raw('convert(datetime, left(DateInserted,8), 3)'), '>=', 'begdate')`
and i get this error:
`SQLSTATE[22007]: [ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string.`
so it cant do the raw query - convert
I am on windows with xampp.
If i run my query in Microsoft SQL Server Management Studio (program to work with MSQL), it works! So maybe its a problem with sql drivers for php or something with laravel, i don't know.
### Steps To Reproduce:
- Use a SQLServer database
- Create table with a `DateInserted, char(20)` column, the date string store like this: `01/01/14 12:35:24:13`
- Create another column with a `begdate, smalldatetime` column, the date stored here like this: `2017-01-01 00:00:00`
- Try to take row with this where statement, `where DateInserted > or = to begdate`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
