### ISSUE TITLE
Model property treated via "__get" always tested true via "empty" method

### ISSUE THREAD

**Issue by Pulsahr** [laravel/framework#31362]
- Laravel Version: 6.12.0
- PHP Version: 7.2.19-0ubuntu0.18.04.2
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

### Description:
If a model has a property returned by magical  `__get` method, the `empty` test will always return true.
Note: Bug was already present in 6.7.0, didn't try any other version.

### Steps To Reproduce:
Have a model that returns a value via __get method:
```php
/**
     * @param string $key
     * @return mixed
     */
    public function __get($key)
    {
        switch ($key) {
            case 'friendlyName' :
                return $this->friendly_name;
            default :
                return parent::__get($key);
        }
    }
```

Test code, after instanciating $object with a value in the fillable property "friendly_name":
```php
$object = ModelClass::find($validId); // returns an instance, not null
$tmp = $object->friendlyName;
dump($tmp); // "value"
dump($object->friendlyName); // "value"
dump(empty($tmp)); // false
dump(empty($object->friendlyName)); // true
```

In case this has anything related, here are the fillable relevant properties of my model. The PK is also casted as a string.
```php
protected $fillable = [
        'id',
        'friendly_name',

        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'id' => 'string'
    ];
```

**Comment by mfn** [comment]
Using `empty()` does not call `__get` but `__isset`, which you didn't implement => no bug in Laravel here.

**Comment by Pulsahr** [comment]
I can't believe I did not notice that. Sorry for the wrong report.
