### ISSUE TITLE
Request parameter names with "." aren't working.

### ISSUE THREAD

**Issue by mertcelen** [laravel/framework#31379]
- Laravel Version: v6.12.0
- PHP Version: 7.3.11-1~deb10u1
- Database Driver & Version: sqlite

### Description:
request parameters with . (dot) in its names automatically converted to _ (underscore).

### Steps To Reproduce:
make a request post request with names.test
observe request()->all() to identify problem.

**Comment by willrowe** [comment]
PHP replaces periods with underscores. See the note at the end of `Example #3` here: https://www.php.net/variables.external
