### ISSUE TITLE
belongsTo Relation to Models with sofdelete trait

### ISSUE THREAD

**Issue by christopherfuturistech** [laravel/framework#31375]
- Laravel Version: 5.8
- PHP Version: 7.2.14
- Database Driver & Version: Mysql 5.7.24

### Description:
Just yesterday we were having a php error on one of our model upon retrieval of data I have joined a parent table which has a softdelete trait with another model that has no softdelete trait.

### Steps To Reproduce:
- I have this class definition:

```
class Restaurant extends Model{
      use SoftDeletes;

       public function locations(){
		return $this->hasMany('App\Location', 'restaurant_id', 'id');
	}
}

class Location extends Model{
        public function restaurant(){
		return $this->belongsTo('App\Restaurant', 'restaurant_id');
	}

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new LocationScope);
        static::retrieved(function ($obj) {
            $restaurantId = $obj->restaurant()->get()->first()->id;
});
        }
}

class LocationScope implements Scope {
	public function apply(Builder $builder, Model $model)
    {
               foreach($builder->getQuery()->joins as $join){
			if($join->table == 'restaurants'){
				$builder->where('restaurants.deleted_at', null);
				break;
			}
		}
    }
}

$locations = \App\Location::where('restaurant_id', <restaurant_id>)->get()->first();
$locations->restaurant()->get()->first()->id;
```
- where the <restaurant_id> is an id of a restaurant that was soft deleted or deleted_at != null.

This would result to an error 'Trying to get property 'id' of non-object' fortunately i manage to handle this with global scopes (but without it the error would occur) cause I knew that if a restaurant is not soft deleted it would be null by value and is included on the list so calling a location that belongs to a restaurant that was soft deleted should not have any issues even by retrieving it not sure if this is something that we should really be handling or solving it with global scope would be sufficient enough to handle it I included my solution on the current version I'm using I also tried 6.x version and its the same thing.

Best Regards

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
