### ISSUE TITLE
[6.14] After a symfony update, fresh laravel installation incorrectly return a "text/xml" content type if the request's headers say they prefer xml

### ISSUE THREAD

**Issue by paulcdejean** [laravel/framework#31370]
- Laravel Version: 6.14.0
- PHP Version: PHP 7.3.11
- Database Driver & Version: N/A

### Description:

In a sympfony minor (?) version update, the behavior of web requests was changed, to return "text/xml" if the requester seems to prefer it. This isn't correct as html which isn't valid xml ends up being returned with a text/xml content type.

### Steps To Reproduce:

`composer create-project --prefer-dist laravel/laravel blog`

Set up a webserver for this on localhost.

`curl -v -H "Accept: application/xml,application/xhtml+xml,text/html" http://localhost 2>&1 >/dev/null | grep 'Content'`

Observe that the returned content type is "text/xml"

Put the output of the front page through an xml linter and observe that it is not valid XML.

```
$ curl -s localhost | xmllint -
-:65: parser error : Opening and ending tag mismatch: link line 10 and head
    </head>
           ^
-:87: parser error : Opening and ending tag mismatch: meta line 5 and html
</html>
       ^
-:88: parser error : Premature end of data in tag meta line 4

^
-:88: parser error : Premature end of data in tag head line 3

^
-:88: parser error : Premature end of data in tag html line 2

^
```

### Expected behavior:

The content type returned is text/html, as it was during Symfony version v4.3.8.

**Comment by driesvints** [comment]
If this was a symfony update we can't do anything about this ourselves. Please open an issue on their repo or send in a PR for better support of said content types.
