### ISSUE TITLE
{test:name} show null in Version 7

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [laravel/framework#31406]
- Laravel Version: 7.x.x
- PHP Version: 7.3.0
- Database Driver & Version: MySQL 5.6

### Description:
Route:
`Route::get('test/{test:id}', 'TestController@debug');`

$pTest->name show null

I have two values in the table tests.

`class TestController extends Controller
{

    public function debug(Test $pTest)
    {
        var_dump($pTest->name);
        var_dump(Test::all());
    }

}`

**Comment by staudenmeir** [comment]
The parameter needs to have the same name as the route segment: https://laravel.com/docs/routing#implicit-binding

```php
class TestController extends Controller
{
    public function debug(Test $test)
    {
        var_dump($test->name);
    }
}
```

**Comment by SoftwareDesign-Solution** [comment]
In which PHP file the new functionality is implemented?

**Comment by staudenmeir** [comment]
How do you mean? You only need to rename the parameter of `TestController::debug()`.

**Comment by SoftwareDesign-Solution** [comment]
I would like to know where the changes in the framework for this functionality were made. Because I like that in version 6.14. want to customize for a current project

**Comment by staudenmeir** [comment]
https://github.com/laravel/framework/pull/30471/files
