### ISSUE TITLE
Session locking doesn't work

### ISSUE THREAD

**Issue by adam1010** [laravel/framework#31405]
## What I'm seeing:
When logged in to my site (with Session), I have one page where I put a `sleep(30)` in and another that loads very fast. If I open the "slow" page in one tab and then while that's loading I open the "fast" page in another tab, the "fast" page loads immediately.

## What I'd expect to see
Since the "slow" page has the session locked, the "fast" page should not load until **after** the "slow" page, because the "slow" page should have the Session locked and so the "fast" page should be busy waiting inside the `session_start()` until the "slow" page has closed the session and is able to proceed with the request.

## Details
In Laravel 6 the recommend Redis session driver switched to `phpredis` which provides the `redis.session.locking_enabled` ini setting so that long running pages block other simultaneous requests. However, setting that does not solve the problem.

**Comment by driesvints** [comment]
Let's focus the discussion in the other issue.

**Comment by adam1010** [comment]
I'm not experiencing the problem from the other discussion. I actually found that Issue after creating this one, because my problem is with race conditions causing duplicate payments on my website. The Session Locking is my concern, so if that other discussion decides to deal with the problem another way, this issue still exists as it's own problem. 

Can we re-open this?

**Comment by driesvints** [comment]
@adam1010 can you please fill out the issue template in that case?
