### ISSUE TITLE
 Slow route group

### ISSUE THREAD

**Issue by lucasantoniooficial** [laravel/framework#31404]
- Laravel Version: 5.7
- PHP Version: 7.4

### Description:
I took a client's project using only one route group and it's causing the project to slow down.

My client has about 500 route lines. At least in version 5.7 I did not test in version 6.x

### Steps To Reproduce:
Make a very large route group, I think 200 lines is enough. But in our reality it was 500 lines in a single group.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
