### ISSUE TITLE
Throttling in controller with standard settings in Kernel.php won't change HTTP headers on API routes

### ISSUE THREAD

**Issue by Cyb0rk** [laravel/framework#31412]
- Laravel Version: 6.14.0
- PHP Version: 7.3.11-1~deb10u1
- Database Driver & Version: file, same as Laravel

### Description:
When in https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L41 the standard option for throttling on API routes is set, you can overwrite it via 

```PHP
public function __construct()
{
    $this->middleware('auth:api');
    // Two requests per minute
    $this->middleware('throttle:2');
}
```

in your controller and the throttling is changed for the whole controller. But the HTTP headers still says:

```HTTP
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
```

the only change to the correct values if you comment out line 41 in https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php#L41

Then the HTTP headers are:
```HTTP
X-RateLimit-Limit: 2
X-RateLimit-Remaining: 1
```

### Steps To Reproduce:
Create a API route and controller, change throttling rates for the specific controller and check the headers via curl -v ROUTE_URL

**Comment by driesvints** [comment]
Please provide an app test that reproduces the problem, thanks!

**Comment by driesvints** [comment]
This is expected. The middleware in the kernel is the last one to be applied so it overrides the one from the controller.

**Comment by Cyb0rk** [comment]
@driesvints Thanks for your information. But if it is expected: than it is broken. Because, as I wrote above, If you change it in the controller, throttling actually is changed, but only not displayed correctly in the response headers.

So if kernel middleware is the last one applied, my changes from the controller shouldn't work But they do: so it is a bug.
