### ISSUE TITLE
Bad array key parsing for fetching JSON value from JSON DB Column

### ISSUE THREAD

**Issue by nikolap123** [laravel/framework#31414]
"quote" is JSON column in table. "quote" has propery 'companyName'.
Query:
`$test=Stock::where('symbol','LIKE',"$query%")->get(['symbol','quote->companyName']);`
Response:
![image](https://user-images.githubusercontent.com/37135652/74144128-73829180-4bfc-11ea-9bac-5847cc495269.png)

I'm not sure is this MySQL execution error or application level error.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
