### ISSUE TITLE
I can't visit the post resource with postman 

### ISSUE THREAD

**Issue by JamesKid** [laravel/framework#31419]
- Laravel Version: 6.5.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
![图片](https://user-images.githubusercontent.com/6158899/74168867-5635dd80-4c65-11ea-9f9c-a9a786e6d25c.png)
![图片](https://user-images.githubusercontent.com/6158899/74168903-664dbd00-4c65-11ea-9dc9-e54b10d55b5e.png)
![图片](https://user-images.githubusercontent.com/6158899/74169433-47035f80-4c66-11ea-84e6-903494b115be.png)

it dosesn't get in the store function . why ?

**Comment by browner12** [comment]
Unfortunately GitHub is not an appropriate platform for general application issues. This is only for issues/bugs with the framework code itself.

Please close your issue, and instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

Laravel Slack (https://larachat.co/)
Laravel.io Forum (https://laravel.io/forum)
Laracasts Forum (https://laracasts.com/discuss)
StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks!
