### ISSUE TITLE
Enhancement: Composer script input / output print order.

### ISSUE THREAD

**Issue by shahvirag** [laravel/framework#31423]
- Laravel Version: 6.x
- PHP Version: 7.2.x

### Description:
Composer scripts execution input and output order print.

"scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan vendor:publish --force --tag=telescope-assets --ansi",
            "@php artisan vendor:publish --force --tag=livewire:assets --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
   },

![laravel composer output](https://user-images.githubusercontent.com/24240840/74212994-0c78e180-4cbd-11ea-941c-85e70afbb387.png)

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
