### ISSUE TITLE
Policy and its Model

### ISSUE THREAD

**Issue by Cellard** [laravel/framework#31427]
- Laravel Version: 6.*
- PHP Version: no matter
- Database Driver & Version: no matter

### Description:

As we know, developer may declare Policy and manually register it in AuthServiceProvider. Developer may register one Policy to few Models:

```
protected $policies = [
    Post::class => SomePolicy::class,
    Article::class => SomePolicy::class,
];
```

It is useful if Models have similar security rules and behavior.

Now look at `Illuminate\Auth\Access\Gate::callPolicyMethod()`. The description says:

```
// If this first argument is a string, that means they are passing a class name
// to the policy. We will remove the first argument from this argument array
// because this policy already knows what type of models it can authorize.
```

In fact, Policy may not know exact Model it should authorize.
If action doesn't require Model (e.g. `$this->authorize('create', Post::class)`) the Policy misses very useful information.

```
class SomePolicy
{
    public function create(?User $user)
    {
        // Is it Post? Or maybe Article?
    }
}
```

So, in one hand we may register one Policy to few Models, in other hand the authorization process doesn't provide information about exact Model.

Is it bug or feature?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
