### ISSUE TITLE
Using the default API Authentication with a custom storage_key containing the string "password" will leave all API routes completely open to access

### ISSUE THREAD

**Issue by andrewalexanderbalogh** [laravel/framework#31422]
- Laravel Version: 6.12.0
- PHP Version: 7.3.13
- Database Driver & Version:
MySQL 8.0.19

### Description:
When using the default _**API Authentication**_ as documented at  
~ https://laravel.com/docs/6.x/api-authentication 

If you set a custom `storage_key` in the `config/auth.php` configuration file as noted at 
~ https://laravel.com/docs/6.x/api-authentication#configuration

which contains the string **"password"**,

then All API routes will be completely Open to access, despite incorrect credentials being provided.

### Steps To Reproduce:
1. Create a field in the `users` table for the `api_token`, but name it **_"api_password"_**  
~ see https://laravel.com/docs/6.x/api-authentication#database-preparation

2. Set the `storage_key` of  `gaurds => api` in `config/auth.php` to **_"api_password"_**

3. Create a new entry in the `users` table with a value set for **_"api_password"_** (hashing does not matter)

4. Make a GET request to an API-Route (`routes/api`) that makes use of the `auth:api` Middleware

Example Route;
```php
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

Example request
```
http://localhost/api/user?api_token=some-invalid-credential
```

5. Notice that despite the wrong credential befing provided for the `api_token` parameter, the first entry of the `users` table is still returned. 

Why does this occur? Take a look at the function `EloquentUserProvider::retrieveByCredentials` 
that gets called 
~ see line https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/EloquentUserProvider.php#L120

Here becuase the key ("api_password") contains the string "password", the query is not updated to use the where condition, so you end up with a query of 
```msyql
select * from users;
```
which then results in the first user of the `users` table always getting returned by the function.

### Notes
Its probably rare that someone would use a `storage_key` field-name containing the string "password", but I almost did, and it would have left my API routes wide open to access. 

At the very least, you need to put a Strong-Warning in your documentation that if custom field names are used for the `storage_key`, they should NOT contain the string "password"

**Comment by taylorotwell** [comment]
Fixed in next release.
