### ISSUE TITLE
Custom usage of ViewErrorBag regression

### ISSUE THREAD

**Issue by dakira** [laravel/framework#31435]
- Laravel Version: 6.14
- PHP Version: 7.4.0

### Description:
After upgrading from 5.8 to 6.14 adding custom errors to the MessageBag doesn't seem to work by adding a ViewErrorBag. The error message can be seen [here]( https://flareapp.io/share/xPQ0Kym1#F49). *Call to undefined method Illuminate\Support\MessageBag::getBag()*

The error in question was manually added to the message bag with the following code:
```php
return redirect(URL::previous())
    ->with('errors', (new ViewErrorBag())->add("street", "Custom error message."))
    ->withInput(request()->all());
```

### Steps to reproduce
I created a minimal example to produce the regression at [dakira/viewerrorbag](https://github.com/dakira/viewerrorbag).

```bash
git clone git@github.com:dakira/viewerrorbag.git
cd viewerrorbag
composer install
cp .env.example .env
php artisan key:generate
```

Now open the site and enter *crash* in the form. Everything should behave as expected. So lets upgrade Laravel.

```bash
git checkout 6.14
rm -r storage vendor
git checkout -- storage
composer install
```

Entering *crash* in the form will now produce the error.

**Comment by driesvints** [comment]
I think you shouldn't just attempt to overwrite the `errors` key like this. This doesn't, for example updates the errors in the session. It's also not documented anywhere like this in the docs that you should use `ViewErrorBag` like this.

Can you try to use the `withErrors` method instead as detailed here? https://laravel.com/docs/6.x/validation#named-error-bags

**Comment by dakira** [comment]
`withErrors` needs a validator which I don't have at this point. Maybe a bit more explanation what I'm doing and why:

I'm using a FormRequest already to validate all input data (e.g. to check if a user entered an address). If it validates I send it on to an external API. Depending on the results of the API call I want to invalidate some of the form data (e.g. "there is no street by this name" or "there is no building at the given address").

I just figured out I can just validate again with a validation rule in a closure that checks against the API response. Thanks for pushing me in this direction, this is much cleaner. 👍 

My problem is solved, but I'd still argue this is a regression that should at least be mentioned in the upgrade guide, right? OTOH maybe this usage of the ViewErrorBag is such an edge case that it's probably okay to just ignore this. You decide. :-)

**Comment by dakira** [comment]
Update: I read the source of `withErrors`. The way I use ViewErrorBag was just a complicated workaround for not being able to just use withErrors to add custom errors in previous releases. This works now:

```php
return back()
    ->withErrors(['field_name' => 'Custom error message'])
    ->withInput();
```

The respective code hasn't changed in 3 years, so I guess I messed up when I started doing it this way. :)
