### ISSUE TITLE
Method Illuminate/Database/Eloquent/Collection::withTrashed does not exist

### ISSUE THREAD

**Issue by ASBaj** [laravel/framework#31446]
According to the docs, I should be able to run withTrashed() on a relationship instance. However, when I do so, I get a  Illuminate/Database/Eloquent/Collection::withTrashed does not exist error. This makes sense, as it appears to be querying the wrong class for the withTrashed Method.

This worked pre 6.0. I'm wondering if this is a bug? I just recently updated.

Thanks!

**Comment by devcircus** [comment]
Looks like maybe you're doing something like ```$parent->children->withTrashed()```. Using the relation property give you a collection. Instead, you would need to use ```$parent->children()->withTrashed()```.

**Comment by ASBaj** [comment]
Unfortunately, that isn't it. I am indeed calling `$parent->children()->withTrashed()`.

**Comment by ASBaj** [comment]
Upon further investigation, I do not believe this is laravel issue. Another instance of the framework running 6.0 does not appear to have the same problem.

**Comment by ASBaj** [comment]
For those that wanted to know, the issue is with using a constructor on a model that implements `SoftDeletes`. As in PHP a child constructor is not automatically called when overwritten, it was necessary to use `parent::__construct()` to get it working correctly.

**Comment by papny86** [comment]
> For those that wanted to know, the issue is with using a constructor on a model that implements `SoftDeletes`. As in PHP a child constructor is not automatically called when overwritten, it was necessary to use `parent::__construct()` to get it working correctly.

You are the Best
