### ISSUE TITLE
Cookie session driver causes issues with SameSite strict or lax

### ISSUE THREAD

**Issue by Krisell** [laravel/framework#31442]
- Laravel Version: 6.15.0
- PHP Version: 7.4.0
- Session Driver: cookie
- Chrome 80

### Description: 
Using the cookie-setting `SameSite=strict` causes links from other domains to not send cookies on the first request. This causes Laravel to create a new session with a new identifier, but the old session data cookie is left, and passed on every request.

Follow a few links like that (or reload the page after following a link) and the number of cookies increases, until the server will start rejecting the requests due to the header size (exactly when depends on the server settings, but around 10 times is enough for me).

![image](https://user-images.githubusercontent.com/25909128/74323112-4c0b0080-4d85-11ea-9804-2414190310f0.png)

```
400 Bad Request (Request Header Or Cookie Too Large)
```

### Steps To Reproduce:
 * Create a brand new Laravel application
 * Set `SESSION_DRIVER=cookie` in `.env`
 * Set `'same_site' => 'strict'` in `config/session.php`
 * Create a link to your page from another domain, and follow that a few times
 * See the number of cookies increase for every request
 * There is no need to store any manual data in the session, the default is sufficient to cause a problem

### Lax
A very similar issue exists for the `'lax'`-setting, which I suppose is more common (and default in Chrome 80). Normal links are fine, but POST-requests to your page does not include cookies and will cause the same issue.

### Additional information
I do understand that the same problem has always existed if the `laravel_session` cookie, which points to the actual session data cookie, is deleted and the page is reloaded. The difference here is that this issue affects users unwittingly and that browser defaults have changed.

### Ideas
I have a very brief understanding of how the session cookies function in Laravel and how they are set, and I do understand that it is impossible to clean up data after the pointer is lost. However, one solution could be to name the data-cookie in a specific way, for instance laravel_session_data_SESSIONID, instead of just SESSIONID, such that dangling data can be deleted, or to always use the same cookie name for the data, since the data store is not shared between users.

I guess the reason that `laravel_session` is just a pointer is to be more generic and behave the same way for all session drivers, but in the case of cookies, couldn't the data be stored directly on that cookie (saving data on every request)?

**Comment by driesvints** [comment]
I'm not sure where all those cookies come from. Unfortunately I don't have time to deep dive into this so appreciating it if anyone can help out here.

**Comment by Krisell** [comment]
Thanks for responding. 

A cookie with the session data is always created when the cookie driver is used. The SameSite setting `strict` or `lax` may cause the cookie to not be sent, even though it exists and is kept in the browser for future requests. Laravel has no way of knowing this and responds with a new data-cookie (with a new random name).

**Comment by taylorotwell** [comment]
If no cookies aren't sent then Laravel will not have any way to determine anything about old sessions. There is likely no solution to this and the answer is simply to use a different session driver such as database.

**Comment by Krisell** [comment]
I agree @taylorotwell about 'lax'. It's quite disturbing though that a post-request to any site from anywhere causes the user from that site to be logged out (regardless of session driver), since Laravel can't see the session and generates a new.

I'll see if I can try out my ideas about the original problem some day. Here's three ideas to try if anyone else wants to look at it:

 * Always use same (specified) name for cookie-data, which will overwrite instead of keep the old dangling.
* Use a prefix for data cookies and clear old unused (the above is probably a better idea).
* Put the session data directly in the laravel_session cookie. This would be nice, but will probably be harder to implement and add some special cases to the session handling.

**Comment by Krisell** [comment]
@taylorotwell  I was able to reproduce both issues at nova.laravel.com, which uses the cookie driver.

Steps:
 * Force someone to make a post-redirect to nova.laravel.com, i.e. by embedding a simple script at any site the user might visit.
 * The CSRF-protection will respond with 419, but the user is then logged out, and the old cookie is kept (for reasons stated above). Do this a few times, and nova.laravel.com doesn't work until cookies are cleared.

Since nova.laravel.com doesn't specify any SameSite-value, it relies on the default. This will be lax in future Chrome, and this new setting can be forced today by visiting chrome://flags and searching for 'lax'.

Chrome allows lax-cookies to be sent i a post-request for 2 minutes after creation, but after waiting these two minutes, the "attack" is successful.

![image](https://user-images.githubusercontent.com/25909128/74343668-b6cf3280-4dab-11ea-9deb-e3e679daaf09.png)

![image](https://user-images.githubusercontent.com/25909128/74343790-ea11c180-4dab-11ea-971b-54ad80b47c44.png)

It's not a big problem, I agree, just wanted to clarify that it has nothing to do with bad setup of Laravel (except for choice of session-driver).

**Comment by taylorotwell** [comment]
I'm not sure what you want me to do. This is simply how cookies work with these settings 😄 ... if you don't like that behavior use a dfferent session driver.

**Comment by Krisell** [comment]
Just to clarify, using "Strict" causes issues regardless of session driver, since all drivers keep id in a cookie.

For "lax", i'll think some more about my proposed solutions above, but I'm sure someone else will figure something better out :)

**Comment by Krisell** [comment]
@taylorotwell Regarding your previous comment: _"It would not be very typical for other sites to be making full POSTs to your domain anyways."_ 

Today I realized that this is **very** common using OAuth (access_token is sent back in a POST request). The solution is thankfully simple – to use an endpoint which does not use the StartSession middleware.

**Comment by LiviuDodan** [comment]
I know it's too late to comment but if the issue it's not yet solved the problem it's in the .env file, the line 
"SESSION_DRIVER=cookie" change to "SESSION_DRIVER=file" 
That's because if the session driver is set to file, stores the data  in the "app/storage/sessions" folder. Otherwise, if the session driver is set to cookie, the data will be encrypted in the user cookies.
I hope this will help you and to others who had the same problem.

**Comment by valorin** [comment]
> Maybe Laravel should never create a **new** session during POST (from a different domain)? 

That wouldn't work. If you're using `SameSite=None`, then you'd probably want new sessions created on `POST`.


> I'll see if I can try out my ideas about the original problem some day. Here's three ideas to try if anyone else wants to look at it:
> 
> * Always use same cookie name for session-data, which will overwrite instead of keep the old dangling.
> * Use a prefix for data cookies and clear old unused (the above is probably a better idea).
> * Put the session data directly in the laravel_session cookie. This would be nice, but will probably be harder to implement and add some special cases to the session handling.

The prefix idea seems to be the best approach, given how the session systems work. That'd allow easy identification of old session cookies to be removed.

Doesn't solve the `SameSite=strict` issue though, but if you're using that setting, you've already got some interesting requirements to work within.

**Comment by rudiedirkx** [comment]
> That wouldn't work. If you're using `SameSite=None`, then you'd probably want new sessions created on `POST`.

That's a weird moment to **start** a session IMO, but you're right, it's possible. For now. Samesite=None will disappear soon, so anybody still counting on that will have to do some dev.

That's how I updated my middleware: no new session during POST from different-or-empty-referer. And everything works beautifully. Works for Strict too. Maybe that's per app, not global Laravel. I think it's reasonable: no new session during POST from unknown origin.

What a search it was. So many articles and questions, about Samesite and Larvel sessions, and this one was the most relevant. 👍

**Comment by karel-de-bruin** [comment]
@Krisell For OAuth, do you perhaps know how do you get around having to verify the 'state' and 'nonce' that should be passed back to you, if you do not have access to the session?

For example, for Microsoft OAuth, you need to generate a random 'state' string, as well as a random 'nonce'. Both should be stored in the session before you redirect the user to the 3rd party OAuth flow.

The 'state' and 'token' are then POSTed back to you, where you need to verify them against those stored in your session ('state' directly and 'nonce' from the token).

**Comment by Krisell** [comment]
@karel-de-bruin 
> [@Krisell](https://github.com/Krisell) For OAuth, do you perhaps know how do you get around having to verify the 'state' and 'nonce' that should be passed back to you, if you do not have access to the session?

Yeah I don't remember giving the advice to disable session handling, and as you say keeping state is important for security reasons in OAuth. I don't think using `lax` with a post-request should cause any problems today, especially not in case the user began on your domain, since I think browser keep a time-windows that allows POST requests to include cookies when bouncing back, e.g. in an OAuth flow.

I'd recommend you search for help for your specific use case in a community help form, e.g. the Laravel Discord.

**Comment by rudiedirkx** [comment]
@karel-de-bruin What I did in my app is:

- modify the session middleware to never _start_ a new session during POST, and
- make a GET redirect from the POST request with all the POST data in the query, and handle the oauth response in that GET request where the session works fine

**Comment by karel-de-bruin** [comment]
@rudiedirkx Thanks for the info, I appreciate it! As far as I know passing the token via a GET is not recommended for security reasons. 

Not sure of all the implications yet, but at the moment setting _both_ the following, makes the redirect work with POST in any case:
`SESSION_SECURE_COOKIE=true`
`SESSION_SAME_SITE=none`
