### ISSUE TITLE
WhereIn with integer returns partial match on string. (int) 1 returns (string) '1ab1fdeb-7e83-4be9-a1b4-52da267d2733'

### ISSUE THREAD

**Issue by booni3** [laravel/framework#31441]
- Laravel Version: 6.12.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0

### Description:
Passing an integer 1 into a whereIn against a string column (i.e. UUID), returns a match against 1ab1fdeb-7e83-4be9-a1b4-52da267d2733

```php
Model::whereIn('uuid', [1])
    ->each(function(Model $model) {
        dd($model->uuid); // '1ab1fdeb-7e83-4be9-a1b4-52da267d2733'
    });
```

To prevent this from happening you have to force the whereIn array to a string, which is not very intuitive, even if technically correct.

```php
Model::whereIn('uuid', array_map('strval', $this->ids)); // returns no results as expected
```

**Comment by staudenmeir** [comment]
This is the way MySQL compares values and not a Laravel issue.

It's the application's responsibility to prevent comparisons like this, e.g. by validating user input.

**Comment by booni3** [comment]
I understand its not a Laravel issue... but wonder if there is something that could be built into eloquent in a similar way that you can cast model values on the way out. What if we can cast them on the way into the query too?

**Comment by driesvints** [comment]
Please see the answer by @staudenmeir
