### ISSUE TITLE
Query Builder paginate() method count total number is wrong when using distinct() and join

### ISSUE THREAD

**Issue by shiromani2018** [laravel/framework#31458]
- Laravel Version: v6.10.1
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
When "select, distinct and join"  using in query together pagination is returning  a wrong total  number of pages as well as last_page.  It is showing Eloquent collection total items without "distinct" filter on it,  i.e.  dd($collection->count() =3210 ) and dd($collection->get()->count() = 1059) . But when I do not use join it is working fine with "distinct"

### Steps To Reproduce:
The below output of the total item is wrong :
"meta": {
        "current_page": 1,
        "from": 1,
        "last_page": 22,
        "path": "xxxxxxxx",
        "per_page": "50",
        "to": 50,
        "total": 3210
Please can you help on this.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26935 and numerous other issues and attempted prs.
