### ISSUE TITLE
artisan foreign key generation issue

### ISSUE THREAD

**Issue by zonouzi** [laravel/framework#31456]
- Laravel Version: 6.14.0
- PHP Version: 7.4.1
- Database Driver & Version: MySql MariaDB 10.4.11
- Apache: 2.4.41 (Win64)

Description: Using artisan migration to add a foreign key to an existing table fails.

Steps To Reproduce:
1- run a migration file, that adds a foreign key in up() function, with the following command:
$table->foreign('user_id')->refernces('id')->on('users')->onDelete('cascade');
2- the cli is:
>php artisan migrate
3- generate the following errors:
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') on delete cascade' at line 1 (SQL: alter table `posts` add constraint `posts_user_id_foreign` foreign key (`user_id`) references `users` () on delete cascade)

  at C:\sites\laravel1\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') on delete cascade' at line 1")
      C:\sites\laravel1\vendor\laravel\framework\src\Illuminate\Database\Connection.php:457

  2   PDO::prepare("alter table `posts` add constraint `posts_user_id_foreign` foreign key (`user_id`) references `users` () on delete cascade")
      C:\sites\laravel1\vendor\laravel\framework\src\Illuminate\Database\Connection.php:457

  Please use the argument -v to see more details.

How to mitigate:
in vendor>laravel>framework>src>Illuminate>Database>Schema>Grammars>	Grammar.php:
	
change line 81 from this:
            $this->columnize((array) $command->references)
to this:
            $this->columnize((array) $command->refernces)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by zonouzi** [comment]
I haven't found any resolution. So I suggest the following, until a real mitigation, I mean correcting the variable name all over the source code, has been provided.

How to mitigate:
in vendor>laravel>framework>src>Illuminate>Database>Schema>Grammars> Grammar.php:

change line 81 from this:
$this->columnize((array) $command->references)
to this:
$this->columnize((array) $command->refernces)

**Comment by mfn** [comment]
@zonouzi the code you pointed out looks correct, maybe you have a typo in your migration
