### ISSUE TITLE
Notification mock returning PHPUnit artefacts

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/framework#31459]
- Laravel Version: 6.15.1
- PHP Version: 7.3.13
- Database Driver & Version: SQLite

### Description:

I was scratching my head because I created a notification test for a new project and it seemed pass even though the functionality was not even ready. I noticed that just calling the Notification::fake(); creates an PHPUnit assertion that always passes, even though there is the actual assert after that which supposed to fail. I don't think this suppose to be the case?

```
<?php

namespace Tests\Feature;

use App\Notifications\OrderShipped;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;

class NotificationsTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test 1
     *
     * @return void
     */
    public function testNotification()
    {
        Notification::fake();
        Notification::assertSentTo(User::all(), OrderShipped::class);
    }

    /**
     * Test 2
     *
     * @return void
     */
    public function testNotificationFake()
    {
        Notification::fake();
    }
}

```

Results in:

`OK (2 tests, 2 assertions)`

### Steps To Reproduce:

I created a fresh install with just the empty notification and the tests.

```
git clone git@github.com:lasselehtinen/laravel-notifications-test.git
composer install
vendor/bin/phpunit
```

First test should fail and the second one should return PHPUnits "No assertions made" warning.

**Comment by driesvints** [comment]
Hmm. I actually get the following for the above:

```
$ phpunit tests/Feature/ExampleTest.php                                                                                                   ~/Sites/test-routes-caching
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

RR                                                                  2 / 2 (100%)

Time: 111 ms, Memory: 20.00 MB

There were 2 risky tests:

1) Tests\Feature\ExampleTest::testNotification
This test did not perform any assertions

/Users/driesvints/Sites/test-routes-caching/tests/Feature/ExampleTest.php:20

2) Tests\Feature\ExampleTest::testNotificationFake
This test did not perform any assertions

/Users/driesvints/Sites/test-routes-caching/tests/Feature/ExampleTest.php:31
```

So the last test works as expected but I'd expect the first one to fail actually 🤔

**Comment by driesvints** [comment]
I see, the first test doesn't performs any assertions because an empty collection is passed. Maybe we can throw an exception there. I'll try to send in a PR for that.

**Comment by driesvints** [comment]
Sent in a fix here: https://github.com/laravel/framework/pull/31471

**Comment by lasselehtinen** [comment]
Thanks! I will be waiting for the next release then.
