### ISSUE TITLE
API resources loads a model's accessor when using when(), whenLoaded(), mergeWhen(), etc.

### ISSUE THREAD

**Issue by sfox55** [laravel/framework#31462]
- Laravel Version: 6.15.0
- PHP Version: 7.2.26

### Description:
I have an issue with API resources where it will load my custom attribute/accessor, which loads a relationship causing unnecessary additional database queries, even when using conditional attribute loading in the API resource.

This may not be a "bug" per se, but is a major performance problem. I'm not sure if it just boils down to poor implementation, but I've tried many many different solutions and the only ones that did the job were workarounds that are not satisfactory (ie. checking if the relationship is loaded on the accessor itself.)

### Steps To Reproduce:
API Resource example:
```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PostResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'created_by' => UserResource::make($this->whenLoaded('activity', $this->created_by)),
        ];
    }
}
```

Post model with custom attribute:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Activity;

class Post extends Model
{
    public function activity()
    {
        return $this->morphMany(Activity::class, 'model');
    }

    public function getCreatedByAttribute()
    {
        $created = $this->activity()->with('user')->where('action', 'created')->orderBy('created_at')->first();

        if ($created && $created->user) {
            return $created->user;
        }

        return null;
    }
}
```

The resource will still query the activity relationship, even though the condition wasn't met. This causes massive amounts of queries when using a resource collection for example.

**Comment by sfox55** [comment]
Best workaround solution I could come up with:

<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PostResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'created_by' => UserResource::make($this->whenLoaded('activity',
                ($this->relationLoaded('activity') || array_key_exists('created_by', $this->getAttributes()))
                    ? $this->created_by : null)),
        ];
    }
}

**Comment by derekmd** [comment]
That code snippet is the equivalent of:

```php
public function toArray($request)
{
    $createdBy = $this->created_by; // runs database queries

    return [
        'created_by' => UserResource::make($this->whenLoaded('activity', $createdBy)),
    ];
}
```

You need to wrap the computed result in a PHP `Closure` to lazyload the result.

```php
public function toArray($request)
{
    return [
        'created_by' => UserResource::make($this->whenLoaded('activity', function () {
            return $this->created_by;
        })),
    ];
}
```

Either way, the example computed get mutator will always run extra database queries since `$this->activity()` starts a new query builder. Changing the implementation to work on the `$post->activity` Collection object will prevent N+1 queries when fetching many posts.

```php
public function getCreatedByAttribute()
{
    return $this->activity->sortBy('created_at')->firstWhere('action', 'created')
        ->user ?? null;
}
```

```php
PostResource::collection(
    Post::with('activity.user')->latest()->take(10)->get()
);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sfox55** [comment]
Thanks @derekmd - I don't know why I never thought of using a closure. D'oh!
