### ISSUE TITLE
Artisan: Add reserved options to the documentation

### ISSUE THREAD

**Issue by danrichards** [laravel/framework#31476]
- Laravel Version: 5.8.35
- PHP Version: 7.2.10-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: 5.7.22-0ubuntu18.04.1

### Description:

Reserved options like `--version` are worthy of a mention in the [docs](https://laravel.com/docs/5.8/artisan). 

### Steps To Reproduce:

Add `--version` option to any command. 

Typically, you'll just get the laravel version no matter your artisan signature. And even with `Artisan::call` w/tinker you'll get the version.

This was particularly difficult to debug in my case because I'm using a Job to dispatch my command, and no output, no `failed` fired, nothing, the application just continued. I felt silly when I figured it out, I just was calling `--version` instead of `--to_version` (the correct option)

Here is the Job I use, it's quite useful, it would be nice to see something equivalent to this in the framework, or maybe there is and I just haven't found it.

```
<?php

namespace App\Jobs;

use Artisan as Console;
use Exception;
use Log;

/**
 * Class Artisan
 *
 * Call a command that would normally take awhile to complete but < 12 hours
 * or whatever the default visibility timeout is on your queue provider.
 */
class Artisan extends AbstractJob
{
    /** @var string $command */
    protected $command;

    /** @var array $parameters */
    protected $parameters;

    /**
     * Artisan constructor.
     *
     * @param string $command
     * @param array $parameters
     */
    public function __construct($command, $parameters)
    {
        $this->command = $command;
        $this->parameters = $parameters;
    }

    /**
     * Execute the job.
     *
     * @return void
     * @throws Exception
     */
    public function handle()
    {
        ini_set('max_execution_time', config("queue.connections.{$this->connection}.visibility_timeout", 1800));

        Console::call($this->command, $this->parameters);
    }

    /**
     * The job failed to process.
     *
     * @param  Exception  $exception
     * @return void
     */
    public function failed(Exception $exception)
    {
        Log::emergency(__METHOD__, [$exception->getMessage()]);
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
