### ISSUE TITLE
Artisan::call() is broken after v6.15

### ISSUE THREAD

**Issue by Ghustavh97** [laravel/framework#31485]
- Laravel Version: 6.15.1
- PHP Version: 7.4.1
- Database Driver & Version: SQLite v3.22.0

### Description:

`\Illuminate\Support\Facades\Artisan::call()` is broken after v6.15

**throws** `PHP Error:  Call to undefined method Symfony/Component/Console/Output/BufferedOutput::section() in /var/www/html/laravel-vue-spa/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php on line 225`

### Steps To Reproduce:

1. Install v6.15 or higher
2. run `php artisan tinker`
3. inside tinker run `Artisan::call('route:list')`

### Screenshots
 **v6.15.1**

![L6151](https://user-images.githubusercontent.com/20132952/74577934-7eda1200-4f9a-11ea-9502-8419d4c8d61c.PNG)

 **v6.15**

![L6150](https://user-images.githubusercontent.com/20132952/74577960-987b5980-4f9a-11ea-924f-e5d78772f2ce.PNG)

 **v6.14**

![L6140](https://user-images.githubusercontent.com/20132952/74577972-a6c97580-4f9a-11ea-9df8-b682d74ae795.PNG)

**Comment by crynobone** [comment]
Fixes already merged, pending new tag

https://github.com/laravel/framework/pull/31469
