### ISSUE TITLE
Artisan Facade commands and behaviours not the same as CLI

### ISSUE THREAD

**Issue by pjhartin** [laravel/framework#31494]
- Laravel Version: 6.15.1
- PHP Version: 7.3

### Description:
When running various Artisan commands using the Artisan support facade, not all commands can be replicated as they would be via the CLI. 

### Steps To Reproduce:
As an example, using Laravel Nova adds a number of `nova:` based artisan commands. If checking what commands are available via `Artisan::all();` - only the core commands are returned. 

This makes executing any web based or programmatic based Artisan calls unreliable. 

In addition, running `Artisan::call('migrate:fresh');` will also miss various tables from external packages that are registered as service providers, such as the official Laravel Nova and Laravel Telescope packages.

**Comment by pjhartin** [comment]
This may be related to #31485

**Comment by crynobone** [comment]
It's not related. If you use `Artisan::call()` outside of CLI environment and the command missing was registered only for CLI using `$app->runningInConsole()` condition then yes it will be missing.

**Comment by pjhartin** [comment]
Interesting, I did not know that.

However, unless telescope's migrations are registered to run only in the console, then I think this is still a bug.

**Comment by crynobone** [comment]
> However, unless telescope's migrations are registered to run only in the console, then I think this is still a bug.

It is. 
https://github.com/laravel/telescope/blob/2.0/src/TelescopeServiceProvider.php#L71-L102

**Comment by driesvints** [comment]
Please see the remarks by @crynobone
