### ISSUE TITLE
Wrong route resource singular form

### ISSUE THREAD

**Issue by tsulatsitamim** [laravel/framework#31495]
- Laravel Version: 6.0
- PHP Version: 7.3
- Database Driver & Version: MYSQL

### Description:
In route resource, when we make route with name 'comprehensives' the singular form is 'comprehensife' but the generated resource controller is 'comprehensive'

### Steps To Reproduce:
1. create Model named Comprehensive with resource controller
2. Add route resource name comprehensives
3. Access get the route /api/comprehensives/id
4. The $comprehensive variable is null, even id is available

**Comment by driesvints** [comment]
We use the doctrine inflector library for this so please open up an issue on their repo.
