### ISSUE TITLE
Memory is not freed up after calling view()->render()

### ISSUE THREAD

**Issue by lexilya** [laravel/framework#31505]
- Laravel Version: 6.15.1
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:

It would seem that the memory is not freed up after calling view()->render() in a loop.

I tried this same thing in v5.8.37, and it's fine there with no increased memory usage after each loop.

### Steps To Reproduce:

Create a fresh project, make an artisan command with the following function:

```
for ($i = 0; $i < 500; $i++) {
  $data = random_bytes(1024 * 1024);
  view('welcome', ['data' => $data])->render();
}
```

random_bytes() just to generate some sample data and increase the size of the data passed to the view. The data does not need to be printed in the view.

After a number of iterations, you run out of memory.

Result in 6.15.1

```
Iteration: 52. Usage: 69601976
Iteration: 53. Usage: 70655560
Iteration: 54. Usage: 71709144
Iteration: 55. Usage: 72762728
Iteration: 56. Usage: 73816312
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1052672 bytes) in /test/app/Console/Commands/Test.php on line 41
```

Result in 5.8.37

```
Iteration: 495. Usage: 14428888
Iteration: 496. Usage: 14428888
Iteration: 497. Usage: 14428888
Iteration: 498. Usage: 14428888
Iteration: 499. Usage: 14428888
```

**Comment by driesvints** [comment]
I managed to confirm this. Appreciating any help with debugging this.

**Comment by 36864** [comment]
This appears to be related to the usage of Ignition. Ignition overrides the default blade engine with its own, which collects all data from every view you render, presumably to facilitate debugging.

**Comment by GrahamCampbell** [comment]
If you disable ignition, is there no memory leak?

**Comment by GrahamCampbell** [comment]
Is it maybe that there is not actually a memory leak, and it is a feature of ignition that it is storing up "view stuff" for debugging if there is an error later?

**Comment by 36864** [comment]
Yes, this is technically not a memory leak. The date is deliberately stored by Ignition for later use.

I don't see an easy way to temporarily disable Ignition other than excluding it from auto-discovery and dumping the autoload.

**Comment by driesvints** [comment]
@lexilya feel free to take this up with their repo.

**Comment by halaei** [comment]
Is this fixed in ignition? I hope it doesn't cause issues with Octane.

**Comment by lexilya** [comment]
@halaei I did not report this to the Ignition repo. Since in my case I was doing something in a CLI app and didn't care about error pages for the web, I just replaced the dependency.

**Comment by SomethingWrong** [comment]
I've got a small hack for everyone who still wonders how to overcome that `render()` memory leak without switching to `spatie/ignition`.

@GrahamCampbell correctly stated the reason why it happens and It's not a bug indeed. Ignition replaces `CompilerEngine` for Blade with its slightly enhanced compiler which collects all that data to help you debug later. 

I had a simple artisan command which compiled thousands of views and ran out of memory easily due to discussed feature. So the "cleanest" way to overcome this is to replace an Ignition compiler engine with an original one. You can do it either in `AppServiceProvider.php` to make the change app-wise or directly right before you `render()` a view:

```php
app()->make('view.engine.resolver')->register('blade', function () {
    return new \Illuminate\View\Engines\CompilerEngine(app()->get('blade.compiler'));
});
```
