### ISSUE TITLE
Facade and Container has same method bound() with different arguments

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#31500]
- Laravel Version: v6.14.0
- PHP Version: 7.3.?
- Database Driver & Version: Mysql 8.?

### Description:
Tried to call App::resolved(Request::class), because of using DeferredProviders.
PhpStorm highlight that resolved() requires \Closure on 1st Argument.
Illuminate\Support\Facade has method resolved() and it isnt Container->resolved();

**Comment by driesvints** [comment]
That's an unfortunate side effect of the method being the same.

**Comment by 6562680** [comment]
May God grant you health so answer all the problems that you have in your life
