### ISSUE TITLE
[6.x] Unable to see a real exception message with symfony/debug ^4.4

### ISSUE THREAD

**Issue by AtCliffUnderline** [laravel/framework#31502]
- Laravel Version: 6.7.0
- PHP Version: 7.2.26
- Database Driver & Version: MySQL 5.7

### Description:
After updating to symfony/debug 4.4 and getting class `FatalThrowableError` being deprecated I'm unable to get a real exception message in runtime. As an example I had such trace:
```
RuntimeException: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4. in /var/www/app/modules/api/controllers/ApiController.php:286
Stack trace:
#0 [internal function]: ApiController->apiErrorHandler(16384, 'The "Symfony\\Co...', '/var/www/vendor...', 14, Array)
#1 /var/www/vendor/symfony/debug/Exception/FatalThrowableError.php(14): trigger_error('The "Symfony\\Co...', 16384)
#2 /var/www/vendor/composer/ClassLoader.php(444): include('/var/www/vendor...')
#3 /var/www/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vendor...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(134): spl_autoload_call('Symfony\\Compone...')
#6 /var/www/LaravelApp/Http/Middleware/Localization.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
```
So 6th step is middleware, but after that I got an exception which implements Throwable, so in Pipeline.php:134 Laravel generates object of FatalThrowableError. And It is impossible to track what is real reason of application being stopped, because the only thing I see is about deprecated class. 

As i mentioned this problem in PR #31475 I understood it will be OK in Laravel 7, but what I have to do now?

### Steps To Reproduce:
I hope you understood me even with my bad English. The only way to reproduce it - update sympfony/debug to ^4.4 and got a Throwable error in runtime.

**Comment by GrahamCampbell** [comment]
What is your error reporting level? The fact that a silenced deprecation error is raised should not matter.

**Comment by AtCliffUnderline** [comment]
@GrahamCampbell `E_ALL & ~E_DEPRECATED & ~E_STRICT`

**Comment by GrahamCampbell** [comment]
And do you have any other error handlers registered? Like flare or bugsnag?

**Comment by AtCliffUnderline** [comment]
@GrahamCampbell I'm sorry, I guess Laravel bootstraps with -1 and displaces my error reporting level. But -1 is default and this issue happens with default value, is it ok? I don't have any other handlers registered.

**Comment by driesvints** [comment]
The error is trigger as `E_USER_DEPRECATED` which you usually don't want enabled in production. This is just a notice for you in development to let you know that the class will be removed in a future version. In Laravel 7 this will be remedied.
