### ISSUE TITLE
PasswordBroker reset password throttle does not work

### ISSUE THREAD

**Issue by Adam-78** [laravel/framework#31513]
- Laravel Version: 6.x
- PHP Version: 7.2
- Database Driver & Version:

### Description:
In laravel 6.x, the password broker '[sendResetLink](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Passwords/PasswordBroker.php#L58)' method includes code to throttle the password:

        if (method_exists($this->tokens, 'recentlyCreatedToken') &&
            $this->tokens->recentlyCreatedToken($user)) {
            return static::RESET_THROTTLED;
        }

However it doesn't work. I've noticed when I look at the '[TokenRepositoryInterface](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Passwords/TokenRepositoryInterface.php)' class, this method hasn't been included?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Adam-78** [comment]
Hi,

I would have thought this is a bug since the method 'recentlyCreatedToken' is missing in the TokenRepositoryInterface in version 6.x

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Passwords/TokenRepositoryInterface.php

It's only available in version 7.x

https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/Passwords/TokenRepositoryInterface.php

**Comment by driesvints** [comment]
Hey @Adam-78 it seems so: https://github.com/laravel/framework/pull/30373
