### ISSUE TITLE
Encrypt result for same data is not a fixed length.

### ISSUE THREAD

**Issue by patrickcarlohickman** [laravel/framework#31512]
- Laravel Version: 6.5.0
- PHP Version: 7.2.24

### Description:
The current encryption algorithm can produce a different size result when encrypting the same piece of information.

For example, this is a possible result:

```
strlen(encrypt('000000000')); // 216
strlen(encrypt('000000000')); // 224
```

This can make some things difficult when needing to know how much space to allocate for something that should theoretically be a fixed size (for example, determining the size of a database field).

In the above example, the result will usually be between 216 and 224 characters, but the theoretical max size (though statistically impossible) would be 308 characters. Additionally, the larger the source encrypted data, the more variable the resulting size will be.

In the last steps of encryption, the algorithm generates the following array:

```
[
    'iv' => 'base64_encoded string',
    'value' => 'base64_encoded string',
    'mac' => 'sha256 hash',
]
```

It then json_encodes the array, base64_encodes that, and returns the string.

The issue is caused by json_encoding the base64_encoded data in the array. If the base64_encoded `iv` or `value` contains a forward slash, the json_encoding adds a backslash to the string to escape it. So, the resulting json_encoded string is a variable length, depending on how many forward slashes ended up in the `iv` and `value` results.

### Steps To Reproduce:
```
$results = [];
for ($i = 0; $i < 10000; $i++) {
    $results[] = strlen(encrypt('000000000'));
}
dump(array_count_values($results));

=> [
     216 => 7425,
     220 => 2548,
     224 => 26,
     228 => 1,
   ]
```

Thanks,
Patrick

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by patrickcarlohickman** [comment]
@driesvints Thank you for taking the time to look at this. I apologize if I wasn't clear, but I was reporting a bug. The size of the encryption result is not fixed when encrypting a fixed size piece of data.

For example, a social security number is 9 digits. If I encrypt this, the result will usually be 216 characters, but can sometimes be 220, 224, 228, etc.

The algorithm can be updated to change this so that it will result in a fixed size (always 216 for a nine digit string). Is there interest in fixing this before I submit a PR?

Thanks,
Patrick

**Comment by driesvints** [comment]
This isn't a bug.
