### ISSUE TITLE
The new HTTP client still makes real requests when faked

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#31519]
- Laravel Version: 7.0
- PHP Version: not relevant
- Database Driver & Version: none

### Description:
The new HTTP client added in https://github.com/laravel/framework/pull/31449 still makes real requests when faked. After the real call is done it returns a stubbed response.

### Steps To Reproduce:
Fake the HTTP client, make a request:

```php
function testItStubsResponses()
{
    $factory = new Factory();

    $factory->fake([
        '*' => Factory::response('Hallo', 200),
    ]);

    // This website has a 5 second delay
    $response = $factory->get('http://slowwly.robertomurray.co.uk/delay/5000/url/http://laravel.com');

    $this->assertSame('Hallo', $response->body());
}
```

The test above takes 5+ seconds to complete, because it makes a real request to the given url.

---
I tried to fix this myself, but I couldn't figure out how the [`PendingRequest`](https://github.com/laravel/framework/blob/c3f3e86b8d22e57029cef7f09fc011048654a9f2/src/Illuminate/Http/Client/PendingRequest.php#L418) class works.

Just my 2 cents, but Guzzle has a [built-in solution](http://docs.guzzlephp.org/en/stable/testing.html) for mocking responses. It takes less than 5 lines of code to implement. It might be a good idea for future maintainability to use the default Guzzle way, instead of the current complicated custom solution.

**Comment by taylorotwell** [comment]
Fixed.
