### ISSUE TITLE
Inconsistent values of $this within a model

### ISSUE THREAD

**Issue by nepetadosmil** [laravel/framework#31516]
- Laravel Version: 6.14.0
- PHP Version: 7.4.2
- Database Driver & Version: MariaDB 10.4.12, InnoDB Engine.

### Description:
- In this case, ``$this`` returns the model (expected behaviour):
![object](https://user-images.githubusercontent.com/25409753/74745011-82ec8500-5263-11ea-9ad7-60bdd87a1a31.PNG)
- In this case, ``$this`` returns ``null``:
![null](https://user-images.githubusercontent.com/25409753/74745037-8e3fb080-5263-11ea-951e-8b70f6ceb886.PNG)

This happened with the ``User`` model (where the ``getToken()`` method is located). I haven't tested it in other models, so I'm not sure if it happens in other cases as well. In both screenshots, the only difference is the line in which ``dd($this)`` is located. No other changes were made to the code whatsoever. ``$token->hasExpired()`` does NOT modify/delete/access any models.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nepetadosmil** [comment]
Thought it was a bugette. Couldn't find anything about it after searching for quite some time, but I guess I didn't search enough apparently. I'll try to dig further, many thanks!
