### ISSUE TITLE
Str::singular('<anything>_data') returns unexpected result

### ISSUE THREAD

**Issue by peter-bolemant** [laravel/framework#31517]
- Laravel Version: 6.2
- PHP Version: 7.3.14
- Database Driver & Version: irrelevant

### Description:

Str::singular('foo_data') returns 'foo_**datum**' - this can make big problems eg. with route model bindings - using Route::resource('user-data', ...), the route parameter then unexpectedly becomes {user_datum}

Even if _datum_ can be considered to be the singular form of _data_,  in this case I think it can be quite confusing. Str::singular('data') returns 'data', as one would expect.

### Steps To Reproduce:

dd(Str::singular('foo_data'));

**Comment by driesvints** [comment]
We're using the doctrine inflector class for this so you'll have to open an issue on their repo.
