### ISSUE TITLE
`SoftDeletes` should call `syncOriginal()` after UPDATE query execution

### ISSUE THREAD

**Issue by mpyw** [laravel/framework#31527]
- Laravel Version: 6.16.0
- PHP Version: 7.4

### Description:

Currently models get dirty (`isDirty() == true`) after both force-deletion and soft-deletion. 

#### Force-deletion

Correct behavior. After deletion, the model doesn't exist anymore: `$exists = false`. We cannot sync the latest attributes from database.

#### Soft-deletion

Wrong behavior. After deletion, the model still exists: `$exists = true`. We should be able to retrieve the latest attributes or immediately restore the data. **Currently, immediate `restore()` call just after `delete()` has a broken behavior.** `SoftDeletes` should call `syncOriginal()` after UPDATE query execution.

### Steps To Reproduce:

```php
$softDeletable->delete();
$softDeletable->restore(); // It does't execute any queries
```

```php
$softDeletable->delete();
$softDeletable->refresh();
$softDeletable->restore(); // It works
```

**Comment by driesvints** [comment]
I can reproduce this but unsure what's causing this. Tried to dive into the internals but it's not clear why the `deleted_at` column isn't cleared in the database when `restore` is called.

**Comment by mpyw** [comment]
@driesvints 

1. `Model::delete()`
2. `SoftDeletes::runSoftDelete()`
3. Model attributes have been set (`Model::isDirty()` returns true)
4. `Builder::update()`
5. **`Model::syncOriginal()` should be called here but we are missing it**

When we restore models..

```php
    /**
     * Restore a soft-deleted model instance.
     *
     * @return bool|null
     */
    public function restore()
    {
        /* ... */

        // This revert the model attribiutes
        // `Model::isDirty()` returns false!!!!!!
        $this->{$this->getDeletedAtColumn()} = null;

        /* ... */

        $result = $this->save();

        /* ... */
    }
```

```php
    /**
     * Save the model to the database.
     *
     * @param  array  $options
     * @return bool
     */
    public function save(array $options = [])
    {
        /* ... */

        if ($this->exists) {
            $saved = $this->isDirty() ?
                        $this->performUpdate($query) : true; // Model::performUpdate() won't be fired
        }

        /* ... *./
    }
```

**Comment by danielsuguimoto** [comment]
@taylorotwell closed the PR, so I'm bringing the question here. Should we sync the timestamps fields only? See https://github.com/laravel/framework/pull/31631#issuecomment-592534632

**Comment by quetzyg** [comment]
Currently I'm running into issue #31823, due to the changes proposed here.
