### ISSUE TITLE
Working with $request and event in UserRegistration

### ISSUE THREAD

**Issue by skydev2020** [laravel/framework#31526]
I create a RegisterController and it comes with default code.
`protected function create(array $data)
    {
        return $user;
    }`
It is missing $request parameter and real code is define here.
Illuminate/Foundation/Auth/RegistersUsers.php -> register function and registered function.
`public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        event(new Registered($user = $this->create($request->all())));

        $this->guard()->login($user);

        return $this->registered($request, $user)
                        ?: redirect($this->redirectPath());
    }`

How can I show success/fail message after user created? in RegisterController without overwriting register function in my HomeController function?

It looks like I have to define listener for 
` event(new Registered($user = $this->create($request->all())));`

How to define the listener? And looks like this function 
`  protected function registered(Request $request, $user)
    {
        //
    }`
is a listener, should I overwrite this function in my HomeController file or should I define custom event handler which I don't know?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
