### ISSUE TITLE
Migrations doesn't force or even allow specifying ALGORITHM=INPLACE on schema alterations, which hands mysql users a loaded footgun

### ISSUE THREAD

**Issue by paulcdejean** [laravel/framework#31530]
For mysql, adding columns to tables and other schema operations are sometimes executed in place, which makes them fast and also means they don't require table level locks.

However sometimes they're not, which means mysql will lock the table and copy its entire contents! This can let's just say have an adverse impact if done on production.

So because of that best practice is to specify `ALGORITHM=INPLACE` when running a migration. This way if for some reason it doesn't support doing a safer in place alteration, the migration will quickly fail rather than bringing down production.

The reasons `ALGORITHM=INPLACE` might not be supported can be extremely arbitrary and hard to predict.

Migrations currently don't have a column modifier or anything to allow specifying this, and don't specify it by default. Which mean that mysql users need to hand write alter statements in order to utilize this safety feature.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by paulcdejean** [comment]
Ok thanks, submitting it there.

**Comment by paulcdejean** [comment]
https://github.com/laravel/ideas/issues/2084

**Comment by binaryfire** [comment]
@paulcdejean Hi Paul. Looks like the ideas repo has been archived and no further action was taken.

I agree, it would be good if we could pass the ALGORITHM and LOCK variables via artisan migrate. It’s essential for mission-critical apps. 

Did you ever find a good way to handle this?

**Comment by binaryfire** [comment]
@driesvints Hey Dries, here’s a bit more background on why this is important: https://planetscale.com/blog/zero-downtime-laravel-migrations

**Comment by shawndibble** [comment]
MySQL 8 uses the algorithm in the following order: INSTANT -> INPLACE -> COPY. You can specify algorithms for any indexing, just not adding columns. Is this option really still needed? 

I understand if you are on MySQL 5.6 this might be very useful. But I think for those still on older versions, using raw sql works adequately.

**Comment by iSWORD** [comment]
@binaryfire you can vote for this here https://github.com/laravel/framework/discussions/44757

**Comment by dmtar** [comment]
@driesvints @paulcdejean Is this still an open question and needs a PR or by any chance its already supported with the most recent framework versions?
