### ISSUE TITLE
[6.15.1] Queues not working with MariaDB

### ISSUE THREAD

**Issue by diverpl** [laravel/framework#31536]
- Laravel Version: 6.15.1
- PHP Version: 7.3.14
- Database Driver & Version: 10.1.44-MariaDB-cll-lve

### Description:
I've added a comment to the issue #31368, but I guess it's better to create a new issue.

A queue worker using MariaDB driver is returning the following error due to changes made with pull request #31287.

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SKIP LOCKED' at line 1 (SQL: select * from `jobs` where `queue` = default and ((`reserved_at` is null and `available_at` <= 1581714782) or (`reserved_at` <= 1581714692)) order by `id` asc limit 1 FOR UPDATE SKIP LOCKED)`

I guess there is [no implementation of FOR UPDATE SKIP LOCKED](https://jira.mariadb.org/browse/MDEV-13115) in MariaDB, so since version 6.14 of Laravel queues are broken.

### Steps To Reproduce:
Just run your queue worker using MariaDB driver.

**Comment by sisve** [comment]
I would slightly want to highjack this issue to ask for clarification if MariaDB is a supported database platform for Laravel. It's not listed at https://laravel.com/docs/6.x/database

**Comment by driesvints** [comment]
@sisve unofficially yes but there's been more and more discrepancies popping up over the years that it might be best that we separate the driver.

**Comment by themsaid** [comment]
The changes are only applied if `PDO::ATTR_DRIVER_NAME` return `mysql` or `pgsql`. I guess for MariaDB it's still returning `mysql`?

**Comment by AegirLeet** [comment]
> The changes are only applied if `PDO::ATTR_DRIVER_NAME` return `mysql` or `pgsql`. I guess for MariaDB it's still returning `mysql`?

Yes, MariaDB is returning `mysql`. However, you can check `PDO::ATTR_SERVER_VERSION`, it will contain the string `MariaDB` somewhere if it's MariaDB. Example: `5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1`

**Comment by themsaid** [comment]
@AegirLeet can you test a change on your machine and open a PR with what worked for you?

**Comment by AegirLeet** [comment]
@themsaid I've submitted a PR.

**Comment by driesvints** [comment]
Will be in the next release.
