### ISSUE TITLE
Query existence relation "Has" is ignoring distinct

### ISSUE THREAD

**Issue by enricooliva** [laravel/framework#31546]
- Laravel Version: 5.6
- PHP Version: 7.3
- Database Driver & Version:

### Description:

Declaring hasMany() a relation with distinct() function. Using "Has" for querying relationship existence but the distinct() is ignored.

### Steps To Reproduce:

photo
id id_1 description
 0     1      AAAA
 1     1      AAAA

```
public function thumb_photos() {
        return $this->hasMany('Photo',id_1','localkey')->select('id_1')->distinct();
}
```

Journey::has('thumb_photos','=',1) is false ERROR!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
