### ISSUE TITLE
makeWith not respecting type hinting

### ISSUE THREAD

**Issue by gjm** [laravel/framework#31545]
- Laravel Version: 6.11.0
- PHP Version: 7.4

### Description:
If I have a class like this:
```php
class Foo
{
    function __construct(Bar $bar, Baz $baz, int $int)
    {
        ...
    }
}
```
If I try to instantiate like this:
```
$instance = app()->makeWith(Foo::class, ['int' => 10.1]);
```

Instead of getting a `TypeError` exception I get the `$int` parameter with a value of `10`. I have `declare(strict_types=1)` in the class file.

**Comment by driesvints** [comment]
scalars aren't supported here I'm afraid.
