### ISSUE TITLE
Multiple choice error undefined index

### ISSUE THREAD

**Issue by o-Dasd-o** [laravel/framework#31557]
- Laravel Version: 6.14.0
- PHP Version: 7.2.24
- OS: Win10

### Description:
I create a test command. I put the code to handle,
```
$color = $this->choice(
  'What is your favorite color?',
  ['red', 'blue', 'green'],
  'red',
  null,
  true
);
$this->info($color);
```
I run the command and the result was a loop with an error "[ERROR] Undefined index: red"
if I set false to "allowMultipleSelections" then run great.
What happen to multiple? I miss something?

Before I submit. I run the code again but I set attempts as 1, And the result was...
```
$color = $this->choice(
  'What is your favorite color?',
  ['red', 'blue', 'green'],
  'red',
  1,
  true
);
$this->info($color);
```

```
  ErrorException  : Undefined index: red

at ...\laravel\vendor\symfony\console\Helper\SymfonyQuestionHelper.php:52

  48|                 $choices = $question->getChoices();
  49|                 $default = explode(',', $default);
  50|
  51|                 foreach ($default as $key => $value) {
  > 52|                     $default[$key] = $choices[trim($value)];
  53|                 }
  54|
  55|                 $text = sprintf(' %s [%s]:', $text, OutputFormatter::escape(implode(', ', $default)));
  56|

Exception trace:

1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: red", "C:\WinNMP\WWW\laravel6\vendor\symfony\console\Helper\SymfonyQuestionHelper.php")
    C:\WinNMP\WWW\laravel6\vendor\symfony\console\Helper\SymfonyQuestionHelper.php:52

2   Symfony\Component\Console\Helper\SymfonyQuestionHelper::writePrompt(Object(Illuminate\Console\OutputStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))
    C:\WinNMP\WWW\laravel6\vendor\symfony\console\Helper\QuestionHelper.php:116
```

Please update the doc with the way can user  select multiple choices. I find it because I check the symfony compoment.

### Steps To Reproduce:
I don't know yet

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
