### ISSUE TITLE
Artisan throws an error if there are routes defined with invokable or resourceful controllers that are yet to be created

### ISSUE THREAD

**Issue by takdw** [laravel/framework#31553]
- Laravel Version: 6.16.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 8.0.19
- OS: Ubuntu 19.10

### Description:
`php artisan` commands will not execute and will throw an error if there are routes defined with invokable or resourceful controllers that do not exist yet. For example defining the route `Route::get('/test', 'NonExistentController');` and trying to run any artisan command will throw this error.
```

   UnexpectedValueException  : Invalid route action: [App\Http\Controllers\NonExistentController].

  at /home/tamrat/Documents/personal/bug/vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:91
    87|      */
    88|     protected static function makeInvokable($action)
    89|     {
    90|         if (! method_exists($action, '__invoke')) {
  > 91|             throw new UnexpectedValueException("Invalid route action: [{$action}].");
    92|         }
    93| 
    94|         return $action.'@__invoke';
    95|     }

  Exception trace:

  1   Illuminate\Routing\RouteAction::makeInvokable("App\Http\Controllers\NonExistentController")
      /home/tamrat/Documents/personal/bug/vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:46

  2   Illuminate\Routing\RouteAction::parse("test", ["App\Http\Controllers\NonExistentController", "App\Http\Controllers\NonExistentController"])
      /home/tamrat/Documents/personal/bug/vendor/laravel/framework/src/Illuminate/Routing/Route.php:162

  Please use the argument -v to see more details.
```

This error doesn't happen if I change the route definition to `Route::get('/test', 'NonExistentController@nonExistentMethod');`

### Steps To Reproduce:
Go to `routes/web.php` and define a route with a controller action with out a method specified and then try to run any artisan command.

I'm not sure if this is by design or a bug. But I don't remember experiencing it before and it wasn't a very to solve at first.

**Comment by driesvints** [comment]
Maybe the error message can be better here. Feel free to send in a PR if you want. Thanks.

**Comment by Siluearsene** [comment]
return 'Vous avez résolue mon problème merci à vous.' ;
