### ISSUE TITLE
default retry_after queue parameter is not respected

### ISSUE THREAD

**Issue by aat2703** [laravel/framework#31562]
- Laravel Version: 6.15.1
- PHP Version: 7.3.11
- Database Driver & Version:
Redis 5.0.x

### Description:
I'm not entirely sure about the behaviour of retry_after, but here it is...

default retry_after queue parameter is not respected. Though overriding this parameter works fine in my OrderCreatedJob. The job is retried instantly when it fails and the 5 second retry_after parameter is not respected. 

OrderCreatedJob.php
```
class OrderCreatedJob implements ShouldQueue {

	use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

	public $tries = 3;
	public $retryAfter = 10;
	public function __construct() {

	}

	public function handle() {
		throw new Exception('This fails');
	}
}

```
queue.php
``` php
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => 'default',
            'retry_after' => 5, // This does not work
            'block_for' => null,
        ],
```
Polling redis
```
andreasaagaard@DESKTOP-TGP1VTJ qo-pos-api % php artisan queue:work redis
[2020-02-22 19:23:38][25] Processing: App\Jobs\OrderCreatedJob
[2020-02-22 19:23:38][25] Processing: App\Jobs\OrderCreatedJob
[2020-02-22 19:23:38][25] Processing: App\Jobs\OrderCreatedJob
[2020-02-22 19:23:38][25] Failed:     App\Jobs\OrderCreatedJob
```
### Steps To Reproduce:
Set "retry_after" parameter and dispatch a job that fails instantly and see that "retry_after" is not respected

**Comment by raulp** [comment]
@aat2703 you miss-understood `retry_after`. Read more [here](https://laravel.com/docs/5.8/queues#job-expirations-and-timeouts). It is related to how much a job will stay in "processing" mode. So in your case, add a sleep(10) in your job, and the worker will automatically retry the job after 5s.

**Comment by aat2703** [comment]
@raulp thank you - Thats what my second thought was...

I saw some other posts with the same issue as this one. I think the retry_after config vs $retryAfter in the job itself is abit confusing :)

**Comment by themsaid** [comment]
`retry_after ` => If you hear nothing from the job (no success or failure) for x seconds, retry it.

`$retryAfter` => If the job fails, retry it after x seconds.
