### ISSUE TITLE
Database migration documentation confusing

### ISSUE THREAD

**Issue by matiaslauriti** [laravel/framework#31563]
I am sorry if this is not the correct section for reporting this, but I did not found the correct place to post this as this must be updated.

### Description:
I was having a look at the [**Database: Migrations** page](https://laravel.com/docs/master/migrations#creating-columns) and I found out that there are 2 methods usable for creating columns.

Those methods seems to not exist anymore, as I was having a look at the core and at the [official documentation](https://github.com/laravel/docs/blame/6.x/migrations.md#L216) (github) and I found out that those methods are not even present on the `.md` file.

So I am assuming that page needs a new deploy.

----
**EDIT:** I see that the documentation is not showing that if you choose `6.x` or less, but on the core it exists in `master`, but [that change](https://github.com/laravel/framework/blame/master/src/Illuminate/Database/Schema/Blueprint.php#L807) was introduced by @taylorotwell 4 months ago, so what am I missing ? Why is it not released ? I see it is going only for 7.x ?

**Comment by AegirLeet** [comment]
The `master` branch is for the next major release (7.x). Development for the current major release (6.x) takes place in the `6.x` branch and the documentation can be found at https://laravel.com/docs/6.x/.

**Comment by matiaslauriti** [comment]
> The `master` branch is for the next major release (7.x). Development for the current major release (6.x) takes place in the `6.x` branch and the documentation can be found at https://laravel.com/docs/6.x/.

Yes, I saw that. It it just confusing having a look at `master` on the Docs page. I think the best thing would be to remove `master` from the Docs, because it is showing docs for a non released version and can create confusion for less experienced developers (they can assume as I did, that `master` is latest branch like `6.x` right now).

**Comment by driesvints** [comment]
master branch is always for the next release. We'll create a 7.x branch once we release 7.x

If you want something changed on the docs feel free to send in a pr 👍
