### ISSUE TITLE
Validator translation fallback locale can use attribute translations of default locale

### ISSUE THREAD

**Issue by JochemKlingeler** [laravel/framework#31575]
- Laravel Version: v6.16.0
- PHP Version: 7.2.27

### Description:
Validator will return translated error messages for validation rules. If the translation for the default locale does not exist, it will return the fallback locale's translation instead.
However, if a translation for the attribute does exist for the default locale, it will use that translation instead of the attribute translation of in the fallback locale.
This can cause certain words in the translation to be in the wrong language.

### Steps To Reproduce:
resources/lang/en/validation.php:
```
<?php
return [
    'required' => 'The :attribute field is required.',
    //'same' => 'The :attribute and :other must match.'// <-- missing
    'attributes' => [
        'email' => 'email address',
        //'first_name' => 'first name', // <-- missing
    ],
]
```
resources/lang/nl/validation.php:
```
<?php
return [
    'required' => ':Attribute veld is verplicht.',
    'same' => ':Attribute en :other moeten overeenkomen.',
    'attributes' => [
        'email' => 'e-mailadres',
        'first_name' => 'voornaam',
    ]
]
```
config/app.php:
```
<?php
return [
    'locale' => 'en',
    'fallback_locale' => 'nl',
    // ...
];
```

Execute:
```
$messages = Validator::make(
    [
        'email' => 'bob',
        // 'first_name' => null // <-- missing
    ],
    [
        'email' => 'same:bob@alice.com',
        'first_name' => 'required'
    ],
)->errors()->getMessages();
```

Expected:
```
// Even though 'nl' does have a custom translation for attribute 'first_name'
// 'en' does not. Default behaviour will replace '_' in attribute key with ' '.
$messages['first_name'][0] === 'The first name field is required.';

// 'en' does not have a translation for slug 'same' and will thus use fallback.
// Both 'en' and 'nl' have an custom attribute for 'email' but because the
// original slug was only found in the fallback, the attribute should also
// come from the fallback.
$messages['email'][0] === 'E-mailadres en bob@alice.com moeten overeenkomen';
```

Actual:
```
// As expected, we don't use the fallback for 'first_name'.
$messages['first_name'][0] === 'The first name field is required.';

// Sadly, the non-fallback attribute name is placed in the fallback translation
$messages['email'][0] === 'Email address en bob@alice.com moeten overeenkomen';
```

### Workaround
1. Set the fallback locale to be the same as the locale.
2. Make sure it doesn't fallback by having all translations available for every slug.

Both of these workarounds seem to defeat the purpose of the fallback feature.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by JochemKlingeler** [comment]
I asked the people over at [Laracasts](https://laracasts.com/discuss/channels/laravel/bug-validator-translation-fallback-locale-can-use-attribute-translations-of-default-locale) and they seem to see this as an unfortunate, but expected behavior.

In hindsight I guess it makes sense for any translation to be able to fallback, including the attributes of an already translated sentence.

Thanks for your time and keep up the good work!

**Comment by driesvints** [comment]
@JochemKlingeler no problem. Thanks for investigating 👍 

If you think it's useful, a pr to the docs is always appreciated to clarify things better.
