### ISSUE TITLE
Decryption is giving wrong value with integer values having 19 or more digits

### ISSUE THREAD

**Issue by harishdurga** [laravel/framework#31576]
- Laravel Version: 5.8.35
- PHP Version: 7.2.27
- Database Driver & Version:Mysql & 8.0

### Description:
I encrypted **99999999999999999889** . But when decrypting i am getting **9223372036854775807**

### Steps To Reproduce:
Try to encrypt 99999999999999999889 with `\Crypt::encryptString($string)` and decrypt with `\Crypt::decryptString($encrypted)`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by harishdurga** [comment]
Now the application is in production. So it is hard to upgrade. Is there anyway you can help me with this issue?
