### ISSUE TITLE
Storage::download not working with S3

### ISSUE THREAD

**Issue by dwyer14** [laravel/framework#31586]
- Laravel Version: 6.16.0
- PHP Version: 7.3.8
- Database Driver & Version: N/A

### Description:
The `Storage::download` method seems broken. Might be an issue with flysystem-aws-s3-v3, but thought I'd start here.

### Steps To Reproduce:

1. Fresh Laravel install.
2. `composer require league/flysystem-aws-s3-v3 ~1.0`
3. Enter S3 credentials into `.env`
3. Route for downloading an existing, public file. eg:
```php
return \Storage::disk('s3')->download( '/_testing/sample-image.jpg' );
```
5. Observe failed download.

![failed-download](https://user-images.githubusercontent.com/13950848/75217455-b7c57400-575c-11ea-8171-7fda7a459725.gif)

**Comment by driesvints** [comment]
Wondering if it's related to https://github.com/laravel/framework/pull/31163

Does downgrading to v6.11.0 fix the problem? And if so: does upgrading to v6.12.0 break it again?

**Comment by voyula** [comment]
Please give Laravel error logs file content.

**Comment by dwyer14** [comment]
@driesvints - Thanks for the suggestion! Can confirm. Going down to 6.11.0 resolves the issue, going back up to 6.12 breaks it again. @voyula - logs are empty/non-existent.

**Comment by voyula** [comment]
I think output buffering problem for downloading data.

**Comment by driesvints** [comment]
We've reverted the pr that caused this.
