### ISSUE TITLE
Blade X is not properly passing the attributes

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/framework#31595]
- Laravel Version: 7.x-dev
- PHP Version: 7.3.11
- Database Driver & Version: Not Mandatory

### Description:
Blade X component implemented in #31363

So based on that i have tried to pass the json which is from controller but instaed of passing a json into component its passing  a compiled string

### Steps To Reproduce:

Create a Component

`resources\views\components\avatar.blade.php`

`{{$foo}}
`
Component Call

```
@php
    $array = ['foo','bar'];
    $json = json_encode($array)
@endphp

<x-avatar
foo={{$json}}
></x-avatar>
```

Expected:  Json needs to printed out

Actual :  `&lt;?php echo e($json); ?&gt;  `

Screenshot of dumped:

![image](https://user-images.githubusercontent.com/30294553/75330421-10088d00-58a7-11ea-9635-8bb16c34ec2d.png)

**Comment by ryangjchandler** [comment]
You're using `{{ }}` which escapes the output, so the `<` and `>` are being encoded.

**Comment by driesvints** [comment]
Try:

```
<x-avatar :foo="$json"></x-avatar>
```

**Comment by driesvints** [comment]
https://laravel.com/docs/master/blade#passing-data-to-components
