### ISSUE TITLE
Redis cache is not set in laravel 6.2

### ISSUE THREAD

**Issue by anandmainali** [laravel/framework#31599]
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version: mysql & 10.4.6-MariaDB

### Description:
Redis cache data is not set in my application but it is working fine in laravel 5.5.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
