### ISSUE TITLE
Eloquent Query using Dynamic Model Laravel

### ISSUE THREAD

**Issue by starking8b** [laravel/framework#31598]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
I have this code which I am using to create a dynamic model in laravel

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class CRUD extends Eloquent
{   
    public $collection ;

    function __construct($attributes = [],$collection ="" )
    {  
        parent::__construct($attributes);

  $this->collection = $collection;

    }

}
and I call this class using this code

     $table='HW12345' ;
     $device_model = new CRUD([],$table);
     $device_model::limit(10)->get();
but this code return empty array . if I put this code inside the constractor

echo $collection
it print the correct value

HW12345

that mean model get the value of passed variable .

if I replaced the code

$this->collection = $collection;

to

$this->collection = 'HW12345';

it is working right without any problem and return data from collection HW12345 what is my wrong and why is that happening

this is the link on stackoverflow
https://stackoverflow.com/questions/60415088/eloquent-query-using-dynamic-model-laravel

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
