### ISSUE TITLE
Syncing a many-to-many with a pivot model with $touches does not touch related models

### ISSUE THREAD

**Issue by Zoefschildpad** [laravel/framework#31597]
- Laravel Version: 6.17.0
- PHP Version: 7.3.8
- Database Driver & Version: sqlite and mysql

### Description:
I have two models, say Owner and Item. There is a many to many relation between owners and items. That relation uses a pivot model `ItemOwner extends Pivot`.
I want to update the updated_at of an Owner when I attach a new item to them. So I add `$touches = ['owner'];` and an owner() relation. However when I now call `$item->owners()->sync($owner)` the owner's updated_at timestamp is not updated.

Digging into it a little more, I've been able to determine the pivot model is not dirty, and that is why it doesn't call touchOwners() in finishSave() in Model.php

I have also observed (more or less by accident) that setting $incrementing to true on the pivot model "fixes" the problem. I only mention this because $incrementing shouldn't have any impact on this case.

### Steps To Reproduce:
```
class Owner extends Model
{
    public function items() {
        return $this->belongsToMany(Item::class)->using(ItemOwner::class);
    }
}

class Item extends Model
{
    public function owners() {
        return $this->belongsToMany(Owner::class)->using(ItemOwner::class);
    }
}

class ItemOwner extends Pivot
{
    protected $touches = ['owner'];
    public function owner() {
        return $this->belongsTo(Owner::class);
    }
}


//and then in tinker I ran
$owner = Owner::create([]); 
$item = Item::create([]);
$item->owners()->sync($owner);
```

**Comment by driesvints** [comment]
Related to https://github.com/laravel/framework/issues/30573 ?

**Comment by Zoefschildpad** [comment]
> 
> 
> Related to #30573 ?

I doubt it. That issue is about the timestamps in a pivot table not updating. My pivot table doesn't have timestamps.

**Comment by driesvints** [comment]
@Zoefschildpad I think you have the `$touches` defined on the incorrect class. Try it on the Item class instead?

```php
class Item extends Model
{
    protected $touches = ['owners'];

    public function owners() {
        return $this->belongsToMany(Owner::class)->using(ItemOwner::class);
    }
}
```

Does that work with `$item->owners()->sync($owner)`?

See https://laravel.com/docs/6.x/eloquent-relationships#touching-parent-timestamps

**Comment by Zoefschildpad** [comment]
Yes, that does update the timestamp. However there are two reasons this isn't what I want to do.
Firstly, $item->owners()->attach($owner) now updates all of the item's owners, instead of just the one that was attached. 
Secondly, now it updates the timestamps whenever the item is saved, which I don't want to do. 

I need it to be on the pivot model, because I only want the timestamp to be updated when a new model is attached. At that point, the pivot model is created and that should trigger the pivot model to touch its relations.

I can also "fix" the problem by adding `public $incrementing = true;` to the ItemOwner model. This tries to set an id for the pivot, making the pivot model dirty, which makes it pass the isDirty() check in Model.php finishSave(). However, I don't think `$incrementing` should have any bearing on whether a relation is touched or not.

I think touchOwners is supposed to be called in the following cases:

- Whenever a model is created.
- Whenever a dirty model is saved.

I am creating a model, but for some reason the foreign keys aren't considered dirty. And since those are the only values I'm saving, the model isn't considered dirty and that is why it isn't touching the owner. This seems like unintended behavior to me.

**Comment by driesvints** [comment]
I'm not really sure if what you're asking is actually a but or something which simply isn't supported yet. Feel free to send in a PR if you want if you can solve this in clean way.
