### ISSUE TITLE
[6.x] Can't access session via Javascript

### ISSUE THREAD

**Issue by SketchNI** [laravel/framework#31591]
- Laravel Version: 6.16.0
- PHP Version: 7.4.0
- Database Driver & Version: not relevent to issue.

### Description:
I'm storing sessions in Redis and can see the session in [Telescope](https://laravel.com/docs/6.x/telescope) and [barryvdh/laravel-debugbar](https://packagist.org/packages/barryvdh/laravel-debugbar) but when trying to access the session via Javascripts `sessionStorage.getItem()` I get `null` returned to me.

I can echo out the contents of the session from Laravels `session()` helper (also using it to create the session in the first place) but Javascript & Browser console just can't see the session.

I have `config('session.http_only')` set to `false` and `strict_mode` on `lax`

### Steps To Reproduce:
Create route endpoint '/test'
Create session in closure.
Echo session out in return statement
See session in browser window.
Can't see session from javascript.

**Comment by SketchNI** [comment]
Minimum viable code
```php
Route::get('/test', function() {
    session()->put(['test' => 'test!']);
    return "session key is <em>test</em><br>contents are: " . session('test');
});
```

**Comment by AlexH269** [comment]
As far as I know the sessionStorage has nothing to do with the PHP session, which is completely server side and  (luckily) not directly accessible from the client. See here: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

The "session.http_only" controls, if the cookie which Laravel uses for identifying the session on the server is accessable by javascript.

What are you trying to achieve? If you just want to specific data from the session, just use an ajax.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
