### ISSUE TITLE
Command withoutOverlapping not working

### ISSUE THREAD

**Issue by tjhunkin** [laravel/framework#31609]
- Laravel Version: 6.17.0
- PHP Version: 7.2.24
- Database Driver & Version: N/A

### Description:

Command everyFiveMinutes()->withoutOverlapping() fires again after 5 minutes even though the previous command hasn't completed as yet

### Steps To Reproduce:

**Command Kernel Entry**

`$schedule->command('sms:test')->everyFiveMinutes()->withoutOverlapping();`

**Command**

```
<?php

namespace App\Console\Commands\Sms;

use Illuminate\Console\Command;

// php artisan sms:test
class TestSmsCommand extends Command
{
    protected $signature = 'sms:test';
    protected $description = '';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        while(true)
        {
            info(self::class.' started process');

            sleep(600);

            info(self::class.' ended process');

            exit();
        }
    }
}
```

**Log Output**

[2020-02-26 16:45:03] test.INFO: App\Console\Commands\Sms\TestSmsCommand started process
[2020-02-26 16:50:05] test.INFO: App\Console\Commands\Sms\TestSmsCommand started process
[2020-02-26 16:55:03] test.INFO: App\Console\Commands\Sms\TestSmsCommand ended process
[2020-02-26 16:55:04] test.INFO: App\Console\Commands\Sms\TestSmsCommand started process

As you can see, the first one kicks-off at 2020-02-26 16:45:03

Then it kicks-off again at 2020-02-26 16:50:05 (5 minutes later), but according to the documentation, the second one should not kick-off if the first one is still processing.

Or am I mistaken?

**Comment by mantas-done** [comment]
You are doing something wrong. What cache driver are you using?

If you want you can check yourself. When you run schedule:run with withoutOverlapping() Laravel write some value to cache driver. Next time when you run schedule:run it checks for that value. If it exists - job will not run.

**Comment by tjhunkin** [comment]
CACHE_DRIVER=array

**Comment by mantas-done** [comment]
Cache driver doesn't save data anywhere. It just stores data for that request and forgets it after the request is finished. So it will not work with array driver. Use file, database, redit, memcache... basically any other driver for it to work.

**Comment by tjhunkin** [comment]
busy installing redis quick

**Comment by tjhunkin** [comment]
@mantas-done yes, that seems to sort it out. I will try and add this as a note in the documentation, as it isn't mentioned nor is it obvious.
