### ISSUE TITLE
Php artisan serve does not auto increment port number on Windows 10

### ISSUE THREAD

**Issue by Nothing-Works** [laravel/framework#31605]
- Laravel Version: 6.17.1
- PHP Version: 7.4.2
- Database Driver & Version: N/A

### Description:
So, in a fresh installed Laravel(Windows 10), when I do `php artisan serve` two times on the same app, the port does not increment as expected see the pic below.

![Capture](https://user-images.githubusercontent.com/18606648/75405927-f5e8b080-5973-11ea-92d5-7941ce6a5462.PNG)

### Steps To Reproduce:
`Laravel new artisan`
`php artisan serve`
`php artisan serve`

**Comment by driesvints** [comment]
I unfortunately can't test myself on Windows so appreciating any help here.

**Comment by donnysim** [comment]
I don't think this is a laravel problem - php built-in server does not complain about port being used when running (at least on windows):

```
php.exe -S 127.0.0.1:8000 "path-to-project\server.php"
php.exe -S 127.0.0.1:8000 "path-to-project\server.php"
php.exe -S 127.0.0.1:8000 "path-to-project\server.php"
```

they'll all run successfully but only the first one will serve it, when you close the first one, the second takes over and so on.

**Comment by YeisonTapia** [comment]
Hi @Nothing-Works 

By default this command always uses port 8008, if running several times 'php artisan serve' should behave like @donnysim said.

If what you need is to run multiple servers on different ports, you can add the option --port

```
$ php artisan serve -h
Usage:
  serve [options]

Options:
      --host[=HOST]     The host address to serve the application on. [default: "127.0.0.1"]
      --port[=PORT]     The port to serve the application on. [default: 8000]
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Serve the application on the PHP development server
```

**Comment by driesvints** [comment]
@Nothing-Works please see the above answers.

**Comment by Nothing-Works** [comment]
@donnysim I also found this, it's interesting.

**Comment by Nothing-Works** [comment]
@YeisonTapia first the default port is 8000 not 8008, second I know I can specify the port number. This was a feature added 5.8. My question is this is not working on windows, not how to run multiple servers on different ports.

**Comment by Nothing-Works** [comment]
@driesvints  would take a pr to fix this on windows?

**Comment by driesvints** [comment]
@Nothing-Works if you can solve this in a clean and non-breaking way then yes.
