### ISSUE TITLE
Ajax request returns 500 internal server error on v6.16.0

### ISSUE THREAD

**Issue by Adam-78** [laravel/framework#31602]
- Laravel Version: 6.16.0
- PHP Version:7.2.24
- Database Driver & Version: MySQL 5.7

### Description:

Upgraded from 6.7 to 6.16  and noticed ajax requests are returning 500 internal server error. When I view the logs I get the following error:

    [2020-02-26 19:09:13] local.ERROR: Header may not contain more than a single header, new line
    detected {"userId":1,"exception":"[object] (ErrorException(code: 0): Header may not contain 
    more than a single header, new line detected at /home/vagrant/myapp/vendor/symfony/http- 
    foundation/Response.php:341)

When I hit the url directly or in versions below 6.7 it works fine. 

### Steps To Reproduce:

My ajax code:

    $(document).ready(function ()  {
        $('#company_id').on('change',function(){
             var companyId = $(this).val();

             if (companyId) {
                 $.ajax({
                     url : baseUrl + '/admin/companies/lookup/' + companyId,
                     type : "GET",
                     dataType : "json",
                     success:function(data)
                     {
                         $('#employee_id').empty();
                         $('#employee_id').append('<option value="">Please select</option>');
                         $.each(data, function(index,element){
                               $('#employee_id').append('<option value="'+ element.id +'">'+ element.name 
                               +'</option>');
                          });
                      },
                      error:function(xhr){
                            console.log(xhr.responseText);
                      }
                });
            }
            else {
                 $('#employee_id').empty();
             }
         });
    });

Controller method:

    public function employeeLookup($id)
    {
          $employees = $this->userRepository->getByCompany($id)->get();

          return response()->json($employees);
     }

This was working fine in v 6.6

**Comment by GrahamCampbell** [comment]
My guess is that something is messing up your request headers somewhere in between the client and php-fpm. Are you using a load balancer?

**Comment by Adam-78** [comment]
@GrahamCampbell No I'm not using any load balancers. When I revert back to v 6.6 it works fine using same environment.

**Comment by GrahamCampbell** [comment]
\And the same symfony versions?

**Comment by AegirLeet** [comment]
Something is causing one of the response headers to contain a newline. I'd try setting a breakpoint [here](https://github.com/symfony/http-foundation/blob/v4.4.4/Response.php#L338) and inspecting the headers array on the response. Or just `\dd($this->headers->allPreserveCaseWithoutCookies());` if you don't have Xdebug set up.

**Comment by Adam-78** [comment]
On v6.16 it is symfony v 4.4.4

I've managed to narrow it down. This error happens when debugbar is enabled and the following setting in debugbar.php is set to true:

    'add_ajax_timing' => true,

**Comment by driesvints** [comment]
Good that you narrowed it down. Please follow along with the issue in debugbar. Thanks
