### ISSUE TITLE
[7.x] Blade Component Self-Closing Tag parsing fails when using empty attributes

### ISSUE THREAD

**Issue by nhedger** [laravel/framework#31610]
- Laravel Version: 7.x
- PHP Version: 7.4.3
- Database Driver & Version: n/a

### Description:

When using blade component **self-closing tags** inside a blade view, passing an empty attribute results in the component not being parsed and compiled.

### Steps To Reproduce:

In any blade view, add a tag component with one or many empty attribute value:

```html
<x-alert type="" limit='' @click="" />
```

### Analysis

Since I was unable to reproduce this error when using open and closing tags instead of self-closing tags, I checked how these tags were parsed and notice that the pattern for parsing the attributes differs.

The pattern for parsing an attribute looks like this:

```diff
=
(?:
    \\\"[^\\\"]+\\\"
    |
    \'[^\']+\'
    |
    [^\'\\\"=<>]+
)
```

Here, the `+` prevents the attribute from being empty because it requiring `1 or more` characters. Instead, `*` should be used to allow for `0 or more` characters, just as it's being done when parsing opening tags:

```
=
(?:
    \\\"[^\\\"]*\\\"
    |
    \'[^\']*\'
    |
    [^\'\\\"=<>]+
)
```

**Comment by driesvints** [comment]
I'm not yet sure if it's meant to work like this. Imo if you define an attribute you'd also add something to it. We'll see if Taylor accepts the pr.

**Comment by nhedger** [comment]
Well,

Since this syntax is valid in HTML as feature is somehow trying to mimic HTML i'd expect it to work the same way. Or at least warn mean if I'm doing something wrong. Currently, the compilation fails silently.

Either way, I believe this behaviour should be consistent for self-closing tags and opening tags.

**Comment by driesvints** [comment]
PR was merged. Thanks!

**Comment by nhedger** [comment]
Awesome :) have a nice day.
