### ISSUE TITLE
Unable to login with other account after logout

### ISSUE THREAD

**Issue by AdventurePandah** [laravel/framework#31621]
- Laravel Version: 6.17.1
- PHP Version: 7.4.0
- Database Driver & Version: -

### Description:
The session 'password_hash' won't be deleted after a logout with Auth::logout();
If you logout and try to login with a other account, it won't work.

### Steps To Reproduce:
Logout and try to login with a other account.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
