### ISSUE TITLE
Warning while running failed job through command line

### ISSUE THREAD

**Issue by andreladocruz** [laravel/framework#31625]
- Laravel Version: 6.17.1
- PHP Version: 7.3
- Database Driver & Version:

### Description:
PHP Deprecated:  Return value of "Illuminate/Queue/Console/RetryCommand::execute()" should always be of the type int since Symfony 4.4, NULL returned. in /home/forge/xpto/vendor/symfony/console/Command/Command.php on line 258

### Steps To Reproduce:
A failed job in database
open tinker
run \Illuminate\Support\Facades\Artisan::call('queue:retry ' . $jobId);

**Comment by AegirLeet** [comment]
This has been discussed at https://github.com/laravel/framework/issues/30845 before. There's a PR for 7.x with a fix [here](https://github.com/laravel/framework/pull/30610/files#diff-2aaa23817a4aeafde63888bd631364e7).

@GrahamCampbell Maybe that particular change should be merged into 6.x too?

**Comment by driesvints** [comment]
@AegirLeet we can't support Symfony 5 in 6.x without breaking a lot. These are only deprecation warnings. You should turn these off in production.

**Comment by AegirLeet** [comment]
@driesvints I realize we can't backport that whole PR for Symfony 5 support, but adding **just** the `(int)` cast in `Command::execute()` and `ClosureCommand::execute()` should be perfectly fine and would make this particular warning go away at least. I'll submit a PR so you can see what I mean.

**Comment by GrahamCampbell** [comment]
You just need to ignore the silenced deprecation errors. Production error config shouldn't even show them.
