### ISSUE TITLE
nesbot/carbon restricted more in 5.6 than 5.5, making upgrade hard

### ISSUE THREAD

**Issue by troelskn** [laravel/framework#31638]
- Laravel Version: 5.6.x-dev
- PHP Version: 7.3.11
- Database Driver & Version:
Not relevant

### Description:
I am upgrading an application from 5.4. I have upgraded to `5.5.x-dev`, which bumps `nesbot/carbon` up to the highest supported version, `1.39.1`. After fixing the application, I proceeded to upgrade to laravel 5.6, but get into trouble because 5.6 want to downgrade nesbot/carbon. I believe this is likely just a mistake in the `composer.json` manifest. For 5.5.x-dev it says `^1.26.0`, whereas 5.6.x-dev says `1.26.*`.

Could we please change the requirements in 5.6.x-dev to be the same as 5.5.x-dev?

**Comment by GrahamCampbell** [comment]
You should be able to go straight from Laravel 5.5 LTS to Laravel 6 LTS?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by troelskn** [comment]
> Can you please try to upgrade to the latest version and see if your problem persists?

Are you a bot or did you just not read what I wrote?

**Comment by driesvints** [comment]
@troelskn I'm not. Please upgrade to a supported version of Laravel.

**Comment by crynobone** [comment]
https://github.com/laravel/framework/commit/27b88449805c1e9903fe4088f303c0858336b23b

it was locked due to breaking change on carbon at the time. Even if we change it based on your request it will be broken.

Beside that, the contributor not going to change a code that was no longer supported

**Comment by troelskn** [comment]
@crynobone Thanks for the explanation. I guess I will have to skip directly to 5.7 then.

**Comment by GrahamCampbell** [comment]
5.7 has known security issues. Skip to 6.0.
