### ISSUE TITLE
Laravel Request "request bag" not equal Symfony Request "request bag"

### ISSUE THREAD

**Issue by szekeresa** [laravel/framework#31639]
- Laravel Version: 4.2, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6
- PHP Version: 7.0, 7.1, 7.2, 7.3
- Database Driver & Version: -

### Description:
I would like to use this original Symfony Request, but the POST parameters include GET parameters.

`$symfonyRequest->query->all() == $laravelRequest->query->all()`
`$symfonyRequest->request->all() != $laravelRequest->request->all()`
GET parameters exists in $laravelRequest->query->all(), but exists in $laravelRequest->request->all() too!!

I know that the $_GET parameters are in the "query" bag and the $_POST parameters are in the "request" bag... But now "request" = "query"..

In : [src/Illuminate/Http/Request.php on createFromBase() function](https://github.com/laravel/framework/blob/7d9e7068c49f945385673014d4cba4de28accd5e/src/Illuminate/Http/Request.php#L586)

This line is **overwrite** "request" parameterBag with GET query params
```$request->request = $request->getInputSource();```

**Not understood why...  Please help!**

### Steps To Reproduce:
Clean install. Put routes/web.php

    Route::get(
        '/request',
        function () {
            $symfonyRequest = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
            $laravelRequest = app(\Illuminate\Http\Request::class);
            assert($symfonyRequest->query->all() == $laravelRequest->query->all());   // this is equal
            assert($symfonyRequest->request->all() == $laravelRequest->request->all());  // wWhy not equal?  
        }
    );

`# php artisan serve`

click: http://127.0.0.1:8000/request?param=get

`ErrorException (E_WARNING)
assert(): assert($symfonyRequest-&gt;request-&gt;all() == $laravelRequest-&gt;request-&gt;all()) failed`

OR 

`# php artisan tinker`

paste:

        $_GET_ = ['parameter' => 'get-value'];
        $_POST_ = [];

        $request = new \Illuminate\Http\Request($_GET_, $_POST_);
        $request->setMethod('GET');
        $queries = $request->query->all();
        $requests = $request->request->all();
        assert($queries == $_GET_); // this is equal
        assert($requests == $_POST_); // this is equal

        $symfony = new \Symfony\Component\HttpFoundation\Request($_GET_, $_POST_);
        $symfony->setMethod('GET');
        $request = \Illuminate\Http\Request::createFromBase($symfony);  // use Illuminate\Http\Request::capture() in public/index.php
        $queries = $request->query->all();
        $requests = $request->request->all();
        assert($queries == $_GET_); // this is equal
        assert($requests == $_POST_, 'failed! $requests != $_POST_ - Why not equal?');

PHP warning:  assert(): $requests != $_POST_ - Why not equal? failed on line 1

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
