### ISSUE TITLE
Stringable class reserved keyword in PHP 8

### ISSUE THREAD

**Issue by iamthefreeman** [laravel/framework#31643]
- Laravel Version: 7.x
- PHP Version: 8.0.0
- Database Driver & Version: N/A

### Description:
A new [stringable rfc](https://wiki.php.net/rfc/stringable#vote) has passed for PHP 8.0.

[Stringable](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Stringable.php) has been added in Laravel version 7. Would it be worth renaming this class now (before 7.x goes gold) to stop potential BCs? If we can come up with a new name, I'm happy to submit a PHP.

https://github.com/php/php-src/pull/5083/files - It looks like the core PHP code refactored their names to `StringCapable`

### Steps To Reproduce:
N/A

**Comment by driesvints** [comment]
Sorry, realized only now that you were talking about a reserved keyword. Will look into this.

**Comment by taylorotwell** [comment]
It is only a reserved class in the root namespace:

![image](https://user-images.githubusercontent.com/463230/75558688-cedbbe80-5a07-11ea-9b23-144aef3ea6ab.png)
