### ISSUE TITLE
Unable to get appends in JsonResource

### ISSUE THREAD

**Issue by francoism90** [laravel/framework#31645]
- Laravel Version: 6.17.1
- PHP Version: 7.4.3
- Database Driver & Version: MariaDB 10.4.12

### Description:
It should be possible to get the appends in a JsonResource (https://github.com/laravel/ideas/issues/976) as `getArrayableAppends` has been made public.

I'm dumping the resource and see the appends I want to get:

```
class VideoResource extends JsonResource
{
    /**
     * @return array
     */
    public function toArray($request)
    {
        dd($this->resource);
     }
```

![image](https://user-images.githubusercontent.com/5028905/75564323-36b3f880-5a4c-11ea-98ca-100c2f6cf41d.png)

But how can I get them? It seems both `getAppends()` and `getArrayableAppends()` aren't callable.

### Steps To Reproduce:

See Description.

**Comment by ryangjchandler** [comment]
The method `getAppends()` doesn't exist I don't think. The `getArrayableAppends()` is protected. You should add a public method to your model that returns the `protected $appends` attribute or calls the `getArrayableAppends()` method. 

The trait in concern in here is `Illuminate\Database\Eloquent\Concerns\HasAttributes`

**Comment by francoism90** [comment]
@ryangjchandler That works, thanks! :)

Has this method been removed and/or can this be added?

**Comment by ryangjchandler** [comment]
> @ryangjchandler That works, thanks! :)
> 
> Has this method been removed and/or can this be added?

I'm sure a getAppends() method could be added, but I think a PR for this has been rejected in the past.

**Comment by driesvints** [comment]
Feel free to open up an issue in ideas repo or attempt a new pr

**Comment by Muhammadinaam** [comment]
Why is this closed without a solution?
