### ISSUE TITLE
PGSQL default return 'ID' and not primarykey?

### ISSUE THREAD

**Issue by HeroSK1** [laravel/framework#31640]
- Laravel Version: 6.10.1 (PHP ARTISAN LIST)
- PHP Version: 7.2
- Database Driver: pgsql

### Description:
When i insert a new record into my table i get an error: 
**SQLSTATE[42703]: Undefined column: 7 ERROR: column "id" does not exist LINE 1**

But in my model i added: 
public $primarykey = 'id_drukwerk';

But it still want to return just 'id'

### Steps To Reproduce:
Migration:
`Schema::create('lds_drukwerk', function (Blueprint $table) {
            $table->integer('id_drukwerk')->primary();
            $table->string('loterij')->nullable();
            $table->string('drukwerk_extern')->nullable();
            $table->string('drukwerk_intern')->nullable();
            $table->boolean('actief')->default(true);
            $table->dateTime('date_created')->nullable();
            $table->string('user_created')->nullable();
            $table->dateTime('date_modified')->nullable();
            $table->string('user_modified')->nullable();
        });`

Model:
` protected $table = 'lds_drukwerk';
    public $primarykey = 'id_drukwerk';
    const CREATED_AT = 'date_created';
    const UPDATED_AT = 'date_modified';`

And in my controller i do: 
`$drukwerk->loterij = $request->LoterijCode;
        $drukwerk->drukwerk_extern = $request->drukwerk_extern;
        $drukwerk->drukwerk_intern = $request->drukwerk_intern;
        $drukwerk->actief = $request->actief;
        $drukwerk->date_created = now();
        $drukwerk->user_created = Auth::user()->name;
        $drukwerk->save();`

**Comment by mantas-done** [comment]
![image](https://user-images.githubusercontent.com/17127206/75555528-0e74cb80-5a45-11ea-8c39-046c7afaaee4.png)

![image](https://user-images.githubusercontent.com/17127206/75555588-319f7b00-5a45-11ea-890b-c0c4d9891ad1.png)

**Comment by staudenmeir** [comment]
The property is `protected` has an uppercase "K":

    protected $primaryKey = 'id_drukwerk';

**Comment by driesvints** [comment]
Please see the answer above.
