### ISSUE TITLE
Cannot get pivot model's id attribute on deleted event

### ISSUE THREAD

**Issue by musapinar** [laravel/framework#31658]
- Laravel Version: 6.17
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
Having a custom ```MorphPivot``` (with primary key ```id```) and listening to ```deleting``` or ```deleted``` events will not return all attributes.
Similar to: https://github.com/laravel/framework/issues/29678

### Steps To Reproduce:
Considering :
- A ```Role``` can have many ```Permission``` : 
```php
    public function permissions(): MorphToMany
    {
        return $this
            ->morphToMany(
                Permission::class,
                'model',
                'model_has_permissions',
                'model_id',
                'permission_id'
            )
            ->using(PermissionPivot::class)->withPivot('id')
            ->withTimestamps();
    }
```

- Intermediate/pivot table ```model_has_permissions``` has primary key ```id```.
- ```PermissionPivot``` extends ```MorphPivot```.
- Listening on ```deleted``` (or ```deleting```) model event on the pivot table will only return 2 attributes : 
![image](https://user-images.githubusercontent.com/7329873/75614382-69d3b600-5b38-11ea-950a-f83c40111d22.png)
above is a dump and die of ```$role->permissions()->sync([]);``` which detaches/deletes all entries in the pivot table.

```php
        Schema::create('model_has_permissions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('model_type');
            $table->uuid('model_id');
            $table->uuid('permission_id');
            $table->index(['model_type', 'model_id'], 'model_has_permissions_mtype_mid_index');
            $table->timestamps();
        });
```

### Expected Behavior:
Return all the attributes, that is to say: all the columns of the pivot table.
If not possible, at least return what I enforce and expect to obtain with ```->withPivot('id')```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by sweet-greg** [comment]
This makes doing work inside the observer's deleting/deleted function (next to) impossible.
Why is this considered a feature instead of a bug?
(Laravel/ideas is archived so I couldn't think of a better place to resurface it)

**Comment by uandco** [comment]
+1 here. Working on some audit log feature on a project and `deleting` events on `MorphPivot` only have the 2 related model IDs, doesn't have the pivot ID or even the type attribute, which makes it impossible to find what exact model was impacted.

**Comment by websuasive** [comment]
+1 too.  Also working on some audit code which needs to be able to keep a journal all changes throughout the system for compliance reasons which users can then review and see what has changed when.

**Comment by DougThwaites** [comment]
Hi all, not going to weigh in on feature of bug but for me adding "id" to the list of withPivot() columns was a fine solution.

**Comment by gitstashgithub** [comment]
A workaround: add `$this->refresh();` to MorphPivot model `deleting` event (or `$model->refresh();` if you use boot in some cases). This will load `MorphPivot` model all fields.
