### ISSUE TITLE
[7.x] onDelete('set null') and nullable() ordering in migration

### ISSUE THREAD

**Issue by AngryMoustache** [laravel/framework#31656]
- Laravel Version: 7.x-dev
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 5.7.20

### Description:
When adding a foreign key to my table, and setting the `onDelete` to `'set null'`, I got an `Cannot add foreign key constraint` error after running the migration:
```php
$table->foreignId('user_id')
    ->constrained()
    ->onDelete('set null')
    ->nullable();
```

This was fixed by moving the `nullable()` up to just above the `constrained()`:
```php
$table->foreignId('user_id')
    ->nullable()
    ->constrained()
    ->onDelete('set null');
```

It is functional now, but still feels like this is a bug.

**Comment by driesvints** [comment]
Does the same problem happen on 6.x?

**Comment by AngryMoustache** [comment]
`->foreignId()` and `->constrained()` don't exist in Laravel 6 as far as I know

**Comment by driesvints** [comment]
@AngryMoustache Just realized that your first example can't ever work (not even in 6.x). I doesn't makes sense to set a `set null` constraint on a none-nullable column. You have to put them in the correct sequence.

**Comment by davidbassey** [comment]
According to the documentation: "Any additional column modifiers must be called before the constrained method"
$table->foreignId('user_id')
      ->nullable()
      ->constrained();

Source: https://laravel.com/docs/9.x/migrations#foreign-key-constraints
