### ISSUE TITLE
Can't set component view attributes from component class.

### ISSUE THREAD

**Issue by PhiloNL** [laravel/framework#31653]
- Laravel Version: 7.x-dev
- PHP Version: PHP 7.3.11
- Database Driver & Version: N/A

### Description:
I'm not 100% sure if this is a bug or intended behavior, but I'm not able to set default attributes from the component class.

### Steps To Reproduce:

```php
<?php 
use Illuminate\View\Component;
use Illuminate\View\ComponentAttributeBag;

// App\View\Components\Button
class Button extends Component
{

    public function __construct()
    {
        $this->withAttributes(['class' => 'foobar', 'type' => 'button']); 
    }

}
```

```php
<?php 
// resources/views/components/button.blade.php
dd($attributes);
?>
```

```
Illuminate\View\ComponentAttributeBag {#284 ▼
  #attributes: []
}
```

**Comment by ryangjchandler** [comment]
> * Laravel Version: 7.x-dev
> * PHP Version: PHP 7.3.11
> * Database Driver & Version: N/A
> 
> ### Description:
> I'm not 100% sure if this is a bug or intended behavior, but I'm not able to set default attributes from the component class.
> 
> ### Steps To Reproduce:
> ```
> <?php 
> use Illuminate\View\Component;
> use Illuminate\View\ComponentAttributeBag;
> 
> // App\View\Components\Button
> class Button extends Component
> {
> 
>     public function __construct()
>     {
>         $this->withAttributes(['class' => 'foobar', 'type' => 'button']); 
>     }
> 
> }
> ```
> 
> ```
> <?php 
> // resources/views/components/button.blade.php
> dd($attributes);
> ?>
> ```
> 
> ```
> Illuminate\View\ComponentAttributeBag {#284 ▼
>   #attributes: []
> }
> ```

You can assign values to public properties on the component class and they should get automatically passed through to the view

**Comment by PhiloNL** [comment]
@ryangjchandler thanks for your comment 😄 I'm aware that this is possible. This still requires the following, however: 

```php
<button {{ $attributes->merge(['class' => $class]) }}>
{{ $slot }}
</button>
```
I think it looks / works a bit cleaner if this is possible from the component class, because I assume this is what the `withAttributes` method is for, but again I might be wrong and this may be the intended behavior.

**Comment by ryangjchandler** [comment]
> @ryangjchandler thanks for your comment 😄 I'm aware that this is possible. This still requires the following, however:
> 
> ```
> <button {{ $attributes->merge(['class' => $class]) }}>
> {{ $slot }}
> </button>
> 
> // Instead of just:
> <button {{ $attributes }}>
> {{ $slot }}
> </button>
> ```
> 
> I think it looks/works a bit cleaner if this is possible from the component class because I assume this is what the `withAttributes` method is for, but again I might be wrong and this may be the intended behavior. Especially when building components with a lot of attributes managed by the component class and having to place them directly into the view might be cumbersome.

Sorry, I see what you're trying to do. I thought you were just trying to pass some values down from the class. This does seem like a bug though.

**Comment by ryangjchandler** [comment]
So that actual cause of the problem is `$component->withAttributes([])` being called in the compiled view.

I can see a couple of solutions here:

1. Wrap the `$component->withAttributes([])` call in an if statement to make sure the attributes array is not empty.

2. Inside of the `Component::withAttributes()` method, instead of calling `$this->attributes->setAttributes($attributes)`, do `$this->attributes = $this->attributes->merge($attributes)`. This would merge the attributes being passed in wrong `$component->withAttributes([])` with the ones that you have added inside of the constructor.

There might be a better way to do this, but after quickly playing around with the source, these 2 options fixed the problem you were having. Would be great to get @driesvints 's thoughts on this.

**Comment by driesvints** [comment]
Let's see if the PR gets accepted.

**Comment by PhiloNL** [comment]
Thanks for the PR @ryangjchandler 🙌

**Comment by eusonlito** [comment]
Related with this issue, the pull request https://github.com/laravel/framework/pull/31676 and the Idea https://github.com/laravel/ideas/issues/2104 I have some situation similar to this working with `withAttributes`.

I need to set a tag value from `href` attribute, but after get the `href` attribute from constructor, I can not use the `href` on attibutes again.

```php
<?php declare(strict_types=1);

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class Button extends Component
{
    /**
     * @var string
     */
    public string $variant;

    /**
     * @var string
     */
    public string $tag;

    /**
     * @param string $variant = 'primary'
     * @param string $href = ''
     *
     * @return self
     */
    public function __construct(string $variant = 'primary', string $href = '')
    {
        $this->variant = $variant;
        $this->tag = $href ? 'a' : 'button';

        $this->withAttributes(array_filter([
            'href' => $href
        ]));
    }

    /**
     * @return \Illuminate\View\View
     */
    public function render(): View
    {
        return view('web.components.button');
    }
}
```
```php
<{{ $tag }} {{ $attributes->merge(['class' => 'button is-'.$variant]) }}>
    {{ $slot }}
</{{ $tag }}>
```
```php
<x-button :href="route('user.signup')" variant="secondary">
    {{ __('signup') }}
</x-button>
```
**Result:**
```html
<a class="button is-secondary">
    signup
</a>
```

**Comment by eusonlito** [comment]
An alternative can be:

```php
<?php declare(strict_types=1);

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class Button extends Component
{
    /**
     * @var string
     */
    public string $variant;

    /**
     * @param string $variant = 'primary'
     *
     * @return self
     */
    public function __construct(string $variant = 'primary')
    {
        $this->variant = $variant;
    }

    /**
     * @return string
     */
    public function tag(): string
    {
        return $this->attributes['href'] ? 'a' : 'button';
    }

    /**
     * @return \Illuminate\View\View
     */
    public function render(): View
    {
        return view('web.components.button');
    }
}
```
But `$this->attributes['href']` is always empty on `tag` method.
