### ISSUE TITLE
Database queue driver deadlock + solution

### ISSUE THREAD

**Issue by mantas-done** [laravel/framework#31660]
- Laravel Version: 6.12.0
- PHP Version: 7.2.11
- Database Driver & Version: MySQL 5.7.24

### Description:
Original issue: https://github.com/laravel/framework/issues/7046
When running more than one queue worker deadlocks happen.

### Steps To Reproduce:
1. Create an empty job
2. Start 10 queue workers (database) 
`artisan queue:work`
3. Add to queue 10,000 jobs
`$arr = [];    
    for ($i = 0; $i < 10000; $i++) {$arr[] = new \App\Jobs\TestJob();} Queue::bulk($arr);`
4. Expected: somewhere between 100 and 500 jobs will fail with a deadlock error.

### Proposed solution
Remove "queue" column index from the "jobs" table. The only index on the "jobs" table should be the primary index on "id" column.

### Expected outcome after removing the index
1. No more deadlocks and failed jobs
2. Somewhere around 20% performance increase in job processing.

### Explanation of the fix (my guess)
When a queue job tries to reserve a new job by running SELECT...FOR UPDATE, it must get 2 locks on both indexes (id and queue). Acquiring those two locks is not atomic and if another worker releases the job by executing the delete statement in between, it can acquire the lock between those 2 actions and create a deadlock.

Can somebody test this and confirm that the findings are correct?

**Comment by themsaid** [comment]
The queue index is necessary since the query uses the queue column to filter jobs. Upgrade to MySQL 8 and you won't have to worry about Deadlocks with the database queue :)

**Comment by aditya-rewari-cb** [comment]
@themsaid I am having exactly same issue with MySQL version 8 !!!

Server version: 8.0.21-0ubuntu0.20.04.4 (Ubuntu)

@mantas-done Did MySQL upgrade worked for you ??? .. or you went ahead with index removal from 'queue' column

**Comment by mantas-done** [comment]
> @themsaid I am having exactly same issue with MySQL version 8 !!!
> 
> Server version: 8.0.21-0ubuntu0.20.04.4 (Ubuntu)
> 
> @mantas-done Did MySQL upgrade worked for you ??? .. or you went ahead with index removal from 'queue' column

Removing index works perfectly. 
Unfortunately, AWS Aurora Serverless DB won't support MySQL 8.0 in near future.

**Comment by aditya-rewari-cb** [comment]
> > @themsaid I am having exactly same issue with MySQL version 8 !!!
> > Server version: 8.0.21-0ubuntu0.20.04.4 (Ubuntu)
> > @mantas-done Did MySQL upgrade worked for you ??? .. or you went ahead with index removal from 'queue' column
> 
> Removing index works perfectly.
> Unfortunately, AWS Aurora Serverless DB won't support MySQL 8.0 in near future.

Yes.. working for me too

Only issue as suspected was.. performance downgrade ! (coz we removed indexes)

**Comment by einarsozols** [comment]
Can confirm that `queue` column index removal is solution.

Also waiting for AWS Aurora MySQL 8 support
