### ISSUE TITLE
Job Chaining Issue

### ISSUE THREAD

**Issue by anasred** [laravel/framework#31662]
- Laravel Version: 5.8.37
- PHP Version: 7.2.24
- Database Driver & Version: MySQL v5.7.29

### Description:
When consuming withChain() method to chain jobs, the behavior is not stable.

### Steps To Reproduce:

create 4 jobs to dispatch, like so.
```
ProcessDocument::withChain([
  new ConvertToPdf($files),
  new MergePdfs(),
  new CleanUp()
])->dispatch();
```
Notes:
- "ProcessDocument" act as a wraper only, and doing nothings.
- all of the above jobs are ```implements ShouldQueue``` interface
- I added ```\Log::info('JobName Called')``` on each one of them I got the following:
[2020-03-01 12:18:37] development.INFO: ProcessDocument Called
[2020-03-01 12:18:37] development.INFO: ConvertToPdf Called

that's all I got the last two jobs didn't fire at all!

What I did next is I removed the "ProcessDocument" job and use the jobs as follows:
```
ConvertToPdf::withChain([
  new MergePdfs(),
  new CleanUp()
])->dispatch($files);
```
Notes:
- all of the above jobs are ```implements ShouldQueue``` interface
- only the first one is fired!

I'm using Amazon SQS for this and I have over 70 queued jobs, mailables, notifications .... all of them worked as expected, except job chaining.

**Comment by mantas-done** [comment]
5.8 not supported anymore

**Comment by themsaid** [comment]
Closing since 5.8 is not supported anymore.
