### ISSUE TITLE
<x-component as variable

### ISSUE THREAD

**Issue by support-softya** [laravel/framework#31661]
hi i start using laravel 7 
and i loved the way thats working with <x-component_name />
but what if i want the component name as variable like this .. 
`	@php $variable = 'setting_navbar'; @endphp
	<x-{{$variable}} />
`
how can i do something like this 
thanks a lot

**Comment by ryangjchandler** [comment]
> hi i start using laravel 7
> and i loved the way thats working with <x-component_name />
> but what if i want the component name as variable like this ..
> `	@php $variable = 'setting_navbar'; @endphp <x-{{$variable}} /> `
> how can i do something like this
> thanks a lot

Not sure this is possible since the `{{ }}` and component tag will be evaluated at the same time. Probably better to use a switch statement and depending on the value of `$variable`, change the component that gets included.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by plakhin** [comment]
Does anyone found the solution for dynamic components in Laravel? Vue.js has a good implementation `<component :is="componentName">`
