### ISSUE TITLE
VER 7 Throwable not needed

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#31673]
- Laravel Version: 7
- PHP Version: #.#.#
- Database Driver & Version:

### The 5.8 code works

This is correct for php including 7.4:
```
    public function report(Exception $exception)
    {
        parent::report($exception);
    }
```

This is done by php.  The following seems wrong.
```
    public function report(Throwable $exception)  ///////  not needed.
    {
        parent::report($exception);
    }
```

Why do you think you need throwable now.  PHP handles that part.

Even in a custom framework I can throw an exception, and it's handled by the exception handler.

```
throw new \Exception('Route not allowed.');
```

And that's in php 7.4

```
    public static function exceptionHandler($e)
    {
        self::newMessage($e);
        self::customErrorMsg();
    }
```
In config:
```
        set_exception_handler('Core\Logger::ExceptionHandler');
        set_error_handler('Core\Logger::ErrorHandler');
```
Where in the Symfony docs are they using throwable, and why the need when php takes care of it through an error and exception handler.

But yes you can "throw" an exception.  This seems wrong.

Right in php manual https://www.php.net/manual/en/class.exception.php
Exception takes care of implementing your throwable.

Symfony 5.1 doc's https://symfony.com/doc/current/components/error_handler.html

#### Furthermore see this reference:

https://www.php.net/manual/en/class.throwable.php

Which states:
> quote
PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.
unquote

**Comment by GrahamCampbell** [comment]
Symony 5 changed some stuff (they deleted symfony/debug). We have decided to update Laravel 7 to use the throwable type in its exception handler, as a consequence.

**Comment by GrahamCampbell** [comment]
> Exception takes care of implementing your throwable.

TypeEorror does not extend Exception.
