### ISSUE TITLE
Ver 7 do all errors have to be thrown now

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#31687]
- Laravel Version: 7
- PHP Version: #.#.#
- Database Driver & Version:

### This is in reference to closed issue https://github.com/laravel/framework/issues/31673

Please see that first.

###  The php manual clearly states:

> Throwable is the base interface for any object that can be thrown via a throw statement in PHP 7, including Error and Exception. 

But via a throw statement.  How are regular errors going to be handled with this code
```
    public function report(Throwable $exception)
    {
        parent::report($exception);
    }
```
Similar in vendor, says Throwable?  Are you saying that to have an error now you have to specifically throw an error?

Again the PHP manual clearly states that:

> PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.

If for example someone has code that will throw an error, they shouldn't have to throw it every time themselves, php has both

```ruby
https://www.php.net/manual/en/function.set-error-handler.php

https://www.php.net/manual/en/function.set-exception-handler.php
```

Which is supposed to take care of such things.

I don't see how (Throwable $exception) will do anything except handle an error if you use the "throw" keyword.

#### So if letting a framework handle errors:
```
 handler ( Exception $ex ) : void
```

#### But if having to use the "throw" word every where
```
 handler ( Throwable $ex ) : void
```

Even with the second line there, somewhere you still need handler ( Exception $ex ) to handle errors that did not come from the "throw" keyword.

But why both when the first line handles both:

> Since PHP 7, most errors are reported by throwing Error exceptions, which will be caught by the handler as well.

**Comment by GrahamCampbell** [comment]
I already explained why we need to use the throwable type here.

**Comment by GrahamCampbell** [comment]
Laravel's exception handler is also called by more code than just php's own error handler.

**Comment by GrahamCampbell** [comment]
> https://www.php.net/manual/en/function.set-error-handler.php

This does **NOT** refer to `Error`s. This handles errors raised by `trigger_error`. These errors are not the same as what happens when an instance of `Error` is thrown. Those are handled by the "exception" handler, which has that name for historic reasons.

**Comment by GrahamCampbell** [comment]
Don't believe me? https://3v4l.org/AkeHi
