### ISSUE TITLE
Replace method from Request facade not replacing data from query parameters

### ISSUE THREAD

**Issue by kalemdzievski** [laravel/framework#31683]
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: pgsql & Postgre 9.6

### Description:
The replace method from the Request facade is not replacing data from query parameters.
The documentation of the method says "Replace the input for the current request.".
I would assume that input would mean "all input", not just the input from the form.
In addition, if one call the method "input" from the Request facade, the data from both form and query will be returned, making me think that the replace method would touch both of them.

### Steps To Reproduce:
Try making two PUT requests. One where parameter "test" is sent via form and one where the "test" parameter is sent via query.
Using the following code
`Request::replace(Request::except(['test']));`
the parameter "test" will be only replaced if it is sent via form, but not if sent as query parameter.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by kalemdzievski** [comment]
@driesvints thanks for the quick response.
I've also check the code for the method replace on Laravel 6.x and 7.x.
It has not been changed.
Can we please reopen the issue or should I open a new one with updated Laravel version?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
