### ISSUE TITLE
PHP Fatal error:  Declaration of App\Exceptions\Handler::report(Exception $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Throwable $e)

### ISSUE THREAD

**Issue by aavinseth** [laravel/framework#31686]
- Laravel Version: 7.0
- PHP Version: 7.3.5
- Database Driver & Version: 10.1.40-MariaDB

### Steps To Reproduce:

1. Change "laravel/framework" to "^7.0" in composer.json
2. Change "facade/ignition" to "^2.0" in composer.json
3. Change "laravel/ui" to "~2.0" in composer.json
4. Change "nunomaduro/collision" to "^4.1" in composer.json
5. Run command composer update in cmd

Gets Error

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Declaration of App\Exceptions\Handler::report(Exception $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) in D:\xampp\htdocs\bookster\web\app\Exceptions\Handler.php on line 8
PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
Stack trace:
#0 D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php(803): ReflectionClass->__construct('App\\Exceptions\\...')
#1 D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(787): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array, false)
#3 D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php(265): Illuminate\Foundation\Application->resolve('App\\Exceptions\\...', Array, false)
#4 D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php(799): Illuminate\Container\Container->Illuminate\Contain in D:\xampp\htdocs\bookster\web\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 805
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

I am also attaching my composer.json and composer.lock file

[composer_json_and_composer_lock_file.zip](https://github.com/laravel/framework/files/4276806/composer_json_and_composer_lock_file.zip)

**Comment by GrahamCampbell** [comment]
Please follow the upgrading guide.

**Comment by GrahamCampbell** [comment]
https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades

**Comment by rezamirzapoor** [comment]
I follow the updagrade guide and got this error

**Comment by spelbreker** [comment]
if you not changed anything in the handler. copy paste this file:

https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php

**Comment by manuelddahmen** [comment]
I'm not using laravel. I still have an 5 years old application in my dead repository. Sad.

**Comment by rafaelxavierborges** [comment]
@spelbreker It was missing the Exceptions folder and also the Handler.php file.
After created these worked pretty well.
Thanks a lot!

**Comment by sodmond** [comment]
Thanks @spelbreker worked for me too.

**Comment by Mnassser** [comment]
`<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
}
`

**Comment by priscillajoshy** [comment]
> if you not changed anything in the handler. copy paste this file:
> 
> https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php

I was getting this error after upgrading to laravel 8.0. Applying this change resolved all the issues. Thanks a lot.

**Comment by jamal221** [comment]
> 
> 
> if you not changed anything in the handler. copy paste this file:
> 
> https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php

My Dear, you completely rescue me from a big trap, I focus on this issue more than two weeks and you show me the correct way.

**Comment by saedyousef** [comment]
It's quite clear. Just replace the param of the report method inside your handler to match ExceptionHandler::report
As I see, it's using Throwable now.

**Comment by ariswj29** [comment]
thank u mate, it works

**Comment by ariswj29** [comment]
> 

Thank u mate, it works.

**Comment by acgtwentyone** [comment]
This occurs to me as well after upgrading Laravel from to 8 from 7, and just like mentioned by @saedyousef, I've to change from 

```Exception ```
to
```Throwable```

in 

```App\Exceptions\Handler.php```

and now everything seems to work fine.

**Comment by douglas-fortunatus** [comment]
For Laravel >= 7

> The report and render methods of your application's `App\Exceptions\Handler` class should accept instances of the Throwable interface instead of Exception instances:

```php
use Throwable;

public function report(Throwable $exception);
public function render($request, Throwable $exception);

```

**Comment by duyquang1410** [comment]
https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php
This guide helped me when I upgraded from laravel 5.8 to 8.0

**Comment by heitordeve** [comment]
> use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
> use Throwable;

Success!
