### ISSUE TITLE
Bug in the sync method

### ISSUE THREAD

**Issue by Shieldforce** [laravel/framework#31697]
- Laravel Version: 6.X
- PHP Version: 7.3.3
- Database Driver & Version: SQLSRV

**Comment by themsaid** [comment]
I don't understand the steps of reproduction. Can you please share a code snippet?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
