### ISSUE TITLE
onOneServer() not working reliably when utilizing after()

### ISSUE THREAD

**Issue by rufhausen** [laravel/framework#31695]
- Laravel Version: 5.8.37 (I know this is technically not supported as of last week, but I'm not seeing code changes in this area since.
- PHP Version: 7.3.14
- Database Driver & Version:
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
redis 5.0.x (Elasticache on production)
### Description:
We have a scheduled job that includes an ->after() changed to it along with ->onOneServer().
The issue is that it appears that jobs that include ->after() (at least with what we've included in after(), prevent the mutex to be added in a timely manner to prevent another worker server from also trying run the job. As you can see from the code snippet, we are calling some artisan command that need to run after the job has completed. Everything works except that it runs on multiple worker servers randomly (more often than not). I'm including a screenshot of logs for 24 hours showing that most times, the job runs on both workers, including one instance where the job was already running on one worker for 3 seconds and still picked up by the 2nd worker. A few times, it only ran on one server. I added the before() in order to help troubleshoot the problem.

Removing the after(), but retaining the before(), appears to resolve the issue.

```
$schedule->command('import:vehicles')
                    ->hourlyAt($this->staggeredHourlyEnvironmentTimes(15))
                    ->timezone('America/New_York')
                    ->unlessBetween('1:00', '7:00')// Don't run from 10PM PT to 7AM ET
                    ->before(function () {
                        \Log::notice('---- STARTING VEHICLE IMPORT ON: ' . php_uname('n') . '----');
                    })
                    ->after(function () {
                        Artisan::call('pricingtool:price');
                        Artisan::call('pricingtool:export');
                        Artisan::call('pricingtool:default-price');
                        Artisan::call('marketscan:cache-rebates');
                        Artisan::call('marketscan:cache-incentive-compatibilities');
                    })->withoutOverlapping()
                    ->onOneServer();`
```

<img width="1170" alt="Screenshot_3_2_20__2_58_PM" src="https://user-images.githubusercontent.com/43862/75723569-cbf7fc80-5c99-11ea-818a-977218d5c5ef.png">

### Steps To Reproduce:
Utilize the after() method. Not sure if matters what your are loading in to after(), but I think it's assumed that the writing of the mutex/timestamp into cache, wouldn't be dependent on that.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
