### ISSUE TITLE
Auth::routes() no longer works in Laravel 7

### ISSUE THREAD

**Issue by iamthefreeman** [laravel/framework#31708]
- Laravel Version: 7.0.1
- PHP Version: 7.3.7
- Database Driver & Version: N/A

### Description:
After upgrading to Laravel 7, I'm getting the following error after calling `Auth::routes();`

```
InvalidArgumentException
Attribute [auth] does not exist.
```

![Screenshot 2020-03-03 at 15 05 27](https://user-images.githubusercontent.com/916500/75788651-75a1c100-5d60-11ea-94b9-3882b0701a37.png)

**Comment by driesvints** [comment]
Hey @iamthefreeman. Did you do this step in the upgrade guide? https://laravel.com/docs/7.x/upgrade#authentication-scaffolding

**Comment by iamthefreeman** [comment]
I didn't have `laravel/ui` as a dependency within my project (I think I did the auth step back in Laravel 5.8?) 

I've installed it and that appears to have fixed it. Would it be worth updating the docs to say `laravel/ui` is now required if you use `Auth::routes`?

**Comment by iamthefreeman** [comment]
🤦‍♂

Whoops! Thanks for that.
