### ISSUE TITLE
[7.x] $attributes are not being passed down to Blade components anymore

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/framework#31706]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:

Hello,
we were using Laravel 7 dev version in our project and it was ok. After upgrading to 7.0 release (released today), the $attributes variable are not taking effect anymore inside components.

### Steps To Reproduce:

Just create a Blade component, pass some attributes (e.g. "class") and add {{ $attributes }} inside the component, and you can see that it won't be taking any effect (not being passed down).

**Comment by driesvints** [comment]
Investigating

**Comment by lucasromanojf** [comment]
@driesvints thanks!

Just to help, I created a new L7 app, changed my welcome.blade.php to this:

```html
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            .font-red {
                color: red;
            }
        </style>
    </head>
    <body>
        <x-teste class="font-red"/>
    </body>
</html>
```

And my teste.blade.php component is simply:

```html
<div {{ $attributes }}>
    Hello World
</div>
```

**Comment by taylorotwell** [comment]
Fixed in 7.0.1.

**Comment by lucasromanojf** [comment]
Wow, you're fast men!
Thank you!

**Comment by ryangjchandler** [comment]
This one was my fault. Apologies to all for the problems caused 😢
