### ISSUE TITLE
Blade components ignore comments

### ISSUE THREAD

**Issue by booni3** [laravel/framework#31711]
- Laravel Version: 7.0.1
- PHP Version: 7.4.1

### Description:
A component within a comment will render.

### Steps To Reproduce:
```blade
{{-- <x-form-input></x-form-input> --}}
```

**Comment by driesvints** [comment]
Thanks. We'll look into this.

**Comment by driesvints** [comment]
We pushed a fix for this that we'll release next week. Use regular html comments for now please.
