### ISSUE TITLE
7.X artisan:test not functioning on upgrade?

### ISSUE THREAD

**Issue by zack6849** [laravel/framework#31718]
- Laravel Version: 7.0.1
- PHP Version: 7.3.9
- Database Driver & Version: N/A

### Description:
I've updated an existing app from 6.x to 7.x following the upgrade guide, and the artisan test command doesn't work for me, output below:
```

laravel@9e4f99b1870a:/var/www/html$ php artisan test
                                                                                                               
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Could not use "NunoMaduro\Collision\Adapters\Phpunit\Printer" as printer: class does not exist
laravel@9e4f99b1870a:/var/www/html$ 
```

The docs say the following:

Update your laravel/framework dependency to ^7.0 in your composer.json file. In addition, update your nunomaduro/collision dependency to ^4.1 and facade/ignition to ^2.0.

Here are the require lines from my composer.json:

Require:
        "laravel/framework": "^7.0",
        "facade/ignition": "^2.0",
Require Dev:
        "nunomaduro/collision": "^4.1",

Am i missing something?

Thanks!

**Comment by driesvints** [comment]
How were you able to install phpunit 7.5? 🤔 
That shouldn't be possible with the new constraints afaik.

**Comment by zack6849** [comment]
This was what was already there, what version of phpunit should i be bumping to?

**Comment by driesvints** [comment]
I can't install phpunit 7.5 on a fresh laravel 7 installation so I'm wondering why you can.

**Comment by driesvints** [comment]
Did you update you actually run `composer update` after updating your dependencies?

**Comment by zack6849** [comment]
I am able to run composer upgrade and composer update, no issues.

```
zack@hephaestus ~/E/uem (master)> composer update                                                                                                                                                                                   15:42:30
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package anahkiasen/underscore-php is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: itsgoingd/clockwork
Discovered Package: lab404/laravel-impersonate
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-activitylog
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
zack@hephaestus ~/E/uem (master)> php artisan test                                                                                                                                                                                  15:42:55
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Could not use "NunoMaduro\Collision\Adapters\Phpunit\Printer" as printer: class does not exist
zack@hephaestus ~/E/uem (master) [1]>                    
```

**Comment by driesvints** [comment]
I see. Can you try installing PHPUnit 8.4 and see if the problem is resolved then?

**Comment by zack6849** [comment]
Yep, that seemed to fix the bug, do you guys need any more info from me for further troubleshooting, or are we just going to chalk this up as some kind of weird scenario that probably won't happen?

**Comment by driesvints** [comment]
We'll add the step to updating phpunit to the upgrade guide. Thanks for helping out. Happy coding!
