### ISSUE TITLE
[7.x] Str::slug(null) will fail

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#31713]
- **Laravel Version:** 7.0.1
- **PHP Version:** 7.4.3

### Description:
`Str::slug(null)` will not works anymore. Not was documented as a breaking change. But I think that is better force `(string)`. 

In real world case, some fields from a table, for instance, could be a `VARCHAR(...) NULLABLE`, and you can't use anymore something like `Str::slug($user->name)` without a `(string)` cast in all cases.

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/framework/pull/31717
