### ISSUE TITLE
ResourceNotFoundException thrown with route caching

### ISSUE THREAD

**Issue by leigeber** [laravel/framework#31725]
- Laravel Version: 7.0.2
- PHP Version: 7.4.1
- Database Driver & Version: N/A

### Description:

When hitting an unavailable route without caching a NotFoundHttpException is thrown as it was with 6.x. Now with route caching a ResourceNotFoundException is thrown which doesn't seem to be handled by the standard 404 template setup.

### Steps To Reproduce:

Call `php artisan route:cache` to cache routes and hit an unavailable route to throw a ResourceNotFoundException resulting in a 500 error.

**Comment by olegmelnik** [comment]
I observe the same thing, but I get `Symfony\\Component\\Routing\\Exception\\NoConfigurationException` and 500 code

**Comment by driesvints** [comment]
Please provide code to reproduce the problem.

**Comment by leigeber** [comment]
@olegmelnik That's likely because Ignition is enabled in the environment you're testing against.

@driesvints This is really a non-code issue, even on a brand new create-project it happens. Just drop the closures so the routes can be cached and then hit a random endpoint. As noted above Ignition changes the error if its enabled.

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/framework/pull/31738

**Comment by driesvints** [comment]
Released 7.0.3 with a fix for this.
