### ISSUE TITLE
assertAuthenticatedAs Fails when using uuid 

### ISSUE THREAD

**Issue by pa-bouly** [laravel/framework#31728]
- Laravel Version: 6.17.1
- PHP Version: 7.2.24
- Database Driver & Version: Postgresql 

### Description:
I'm using an uuid  for my User to authenticate. (I'm using [ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine) )
All works fine, but when i'm testing the authentification with the `assertAuthenticatedAs` methods, i got this error : 
`The currently authenticated user is not who was expected
Failed asserting that 'd5ac944d-b245-4c95-8b4d-283579c1872b' is identical to an object of class "Ramsey\Uuid\Uuid".`

I'm currently overriding 'assertAuthenticatedAs' to use `assertEquals` instead of `assertSame` to be able to pass my tests. I'm curious if it would be possible to change it directly in the framework  [here](https://github.com/laravel/framework/blob/cbd46c70bc747af5f80a4a257ff58fd533e3f815/src/Illuminate/Foundation/Testing/Concerns/InteractsWithAuthentication.php#L96), or if i keep my overridden method :)

Thanks

**Comment by driesvints** [comment]
Can you share the test?

**Comment by pa-bouly** [comment]
This is the test : 

```    
    /** @test */
    public function can_register_using_facebook_and_login()
    {
        $this
            ->json('POST', route('auth.login.facebook'))
            ->assertSuccessful();

        $customer = Customer::whereEmail('foo@bar.com')->first();
        $this->assertAuthenticatedAs($customer);
    }
```
And this is the controller 
```    
public function facebook(Request $request)
    {
        $facebookUser = $this->getFacebookUser();

        /** @var Customer $customer */
        $customer = Customer::whereEmail($facebookUser->email)->first();

        if (!$customer) {
            $customer = $this->createFromFacebook($facebookUser);
            event(new Registered($customer));
        }

        Auth::login($customer);
        return $this->respondWithToken($customer);
    }
```

**Comment by driesvints** [comment]
It's probably best to also share the model. Thanks.

**Comment by pa-bouly** [comment]
This is the model : 
```php
<?php

class Customer extends Authenticatable implements JWTSubject
{
    use Notifiable, SoftDeletes;

    protected $fillable = [
        'uuid',
        'full_name',
        'email',
        'password',
        'locale',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function (Customer $customer) {
            $customer->uuid = Str::uuid();
        });
    }

    public function getJWTIdentifier()
    {
        return $this->uuid;
    }

    public function getAuthIdentifierName()
    {
        return 'uuid';
    }

    public function getJWTCustomClaims(): array
    {
        return [];
    }
}
```
And the migration to add the uuid: 
```php

class AddUuidToCustomers extends Migration
{
    public function up()
    {
        \Doctrine\DBAL\Types\Type::addType('uuid', 'Ramsey\Uuid\Doctrine\UuidType');

        Schema::table('customers', function (Blueprint $table) {
            $table->uuid('uuid')->unique()->nullable();
        });

        Customer::all()->each(function (Customer $customer) {
            $customer->uuid = Str::uuid();
            $customer->save();
        });

        Schema::table('customers', function (Blueprint $table) {
            $table->uuid('uuid')->nullable(false)->change();
        });
    }

    public function down()
    {
        Schema::table('customers', function (Blueprint $table) {
            $table->dropColumn('uuid');
        });
    }
}
```
Thanks a lot ;)

**Comment by driesvints** [comment]
I see you haven't defined your primaryKeyType:

![Screenshot 2020-03-05 at 14 14 07](https://user-images.githubusercontent.com/594614/75984936-9fd3ba00-5eeb-11ea-8d93-c82467ce8464.png)

Can you add that and try again?

**Comment by pa-bouly** [comment]
Nop i'm still getting this error : 
```The currently authenticated user is not who was expected
Failed asserting that '2f1bc2c4-0a47-406c-8844-2c935bc07c98' is identical to an object of class "Ramsey\Uuid\Uuid".`

**Comment by driesvints** [comment]
@pa-bouly replace `$customer->uuid = Str::uuid();` with `$customer->uuid = Str::uuid()->toString();`?

**Comment by pa-bouly** [comment]
Neither :/

**Comment by driesvints** [comment]
I'm gonna elevate this as a bug then because I'm out of ideas. Appreciating any help with this. Thanks for reporting.

**Comment by ryangjchandler** [comment]
Think I've found the problem here. Will send in a PR.

**Comment by pa-bouly** [comment]
Any news about it @ryangjchandler  ? :)

**Comment by driesvints** [comment]
It works for me when using the regular uuid column type. We can't unfortunately give support for third party libraries so please post this on a support channel.
