### ISSUE TITLE
[7.x] Route caching STILL doubles URI prefixes for 2+ nesting levels

### ISSUE THREAD

**Issue by AramZahedi** [laravel/framework#31727]
- Laravel Version: 7.0.2
- PHP Version: 7.4.3

### Description:
Route caching system doubles route prefixes for routes that are grouped and prefixed with more than 2 levels of nesting.
It appeared in 7.0.1 and the new release fixed the problem for only 1 level of nesting.
But the problem persists for 2+ levels of nesting.

### Steps To Reproduce:
1. Add this routes group to your web router file.
`Route::prefix('profile')->group(function () {
    Route::prefix('{user:username}')->group(function () {
        Route::prefix('block')->middleware(['auth'])->group(function () {
            Route::post('/', 'HomeController@index')->name('profile.block');
            Route::delete('/', 'HomeController@index')->name('profile.unblock');
        });
    });
});`

**Like this:**
![carbon (6)](https://user-images.githubusercontent.com/40715409/75863401-a2fc7680-5e15-11ea-805c-6c384937864c.png)

2. Cache the routes in the command line using:
`php artisan route:cache`

3. Now get the routes list from the command line using `php artisan route:list`, and you will see this route:

> profile/{user:username}/block/profile/{user}/block

**Comment by ryangjchandler** [comment]
After a quick look, it seems like this bit of code is causing the problem: 

![image](https://user-images.githubusercontent.com/41837763/75869456-7cccdb80-5e01-11ea-9ed2-a898bf689160.png)

The `prefix` contains the scoping parameters, in your case `{user:username}`, whereas the `uri` does not, so it's not getting replaced / removed from the URI.

**Comment by cambagulung** [comment]
up

**Comment by driesvints** [comment]
Looking into this

**Comment by driesvints** [comment]
Released 7.0.3 with a fix for this.
