### ISSUE TITLE
Usefullness of a code line (PackageManifest)

### ISSUE THREAD

**Issue by ncou** [laravel/framework#31729]
Hi,

Nice piece of code. Looking at the source code I got an interogation.
What is the usefullness of the following code line :

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/PackageManifest.php#L109

There is a filesystem->get() call but the return value is not used, and the getRequire seems to do the job.

What am i missing ? This code line seems useless...

Keep up the good work.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ncou** [comment]
Sorry for using the wrong channel, simply trying to point some dead code. 
Not really important, so keep up the good work and have fun !
