### ISSUE TITLE
[7.x] Model Factory Attribute Casting Bug

### ISSUE THREAD

**Issue by fragkp** [laravel/framework#31734]
- Laravel Version: 7.0.2
- PHP Version: 7.4.3
- Database Driver & Version: Sqlite

### Description:
Hey,
I encountered a breaking change from Laravel 6 to 7. When I'm using a Model Factory and my Model has an attribute casting to `int`, it will be fail to resolve this correctly.

### Steps To Reproduce:
I've created an example repository.

Model: https://github.com/fragkp/laravel-7-factory-bug/blob/master/app/User.php
Test: https://github.com/fragkp/laravel-7-factory-bug/blob/master/tests/Feature/ExampleTest.php

The last assertion will fail since the`exit_code` attribute there is `null`.

On Laravel 6 the attribute `exit_code` is `0`.

**Comment by narwy** [comment]
@fragkp set it to `integer` instead of `int`

**Comment by fragkp** [comment]
> @fragkp set it to `integer` instead of `int`

Has no effekt for me. Also: `int` and `integer` are the same here:
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L511

**Comment by themsaid** [comment]
`null` is never casted and always returned as is.

**Comment by fragkp** [comment]
> `null` is never casted and always returned as is.

Yes, but why is the second call on `exit_code` null?

**Comment by themsaid** [comment]
You'll need to debug that in your app. Find the raw attributes of the model so you understand what's going on.

**Comment by fragkp** [comment]
After digging deep into the core and history, I've found the change between version 6 -> 7.

Taylor changed the behavior of `originalIsEquivalent` here: https://github.com/laravel/framework/commit/e5375547b85f4f2024c9b6d01aef70960630cf69#diff-6a9cb621261ef4a702081454957adfb2L1355

So, in my example code happens following:
Attribute (exit_code) is 0.
Original is null.

The `==` check returns true and no SQL Update will be fired.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/commit/2b395cd1f2fe95b67edf97684f09b7c5c4a55152

thanks

**Comment by driesvints** [comment]
Released 7.0.3 with this.
