### ISSUE TITLE
Undefined variable zvalIsRef after upgrading to php 7.4

### ISSUE THREAD

**Issue by sasokovacic** [laravel/framework#31742]
- Laravel Version: 5.8
- PHP Version: 7.4

### Description:

I'm getting "Undefined variable zvalIsRef" inside of the "symfony/var-dumper/Cloner/VarCloner.php" file on line 268 after upgrading to php 7.4. Before I was using php 7.2 and it worked fine. 

### Steps To Reproduce:

Install Laravel 5.8 to a PHP7.4 web server. Dump something using dump() method inside of a controller method or route closure function and make a REST request.

See the image bellow:

![image](https://user-images.githubusercontent.com/4608330/75906874-ac063b80-5e47-11ea-9405-0a8d4abb6b2f.png)

**Comment by morloderex** [comment]
Laravel 5.8 is No longer supported i would not expect it to support PHP 7.4 at all.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
