### ISSUE TITLE
NotFoundHttpException returns empty message

### ISSUE THREAD

**Issue by olegmelnik** [laravel/framework#31757]
- Laravel Version: 7.0.4
- PHP Version: 7.2.27

### Description:
After making a request to the not existing endpoint returns next json:
```
{
  "message": ""
}
```

Expected: 
```
{
  "message": "Not found"
}
```

**Comment by driesvints** [comment]
Please share code to reproduce the issue.

**Comment by olegmelnik** [comment]
Which code would you like to receive?

**Comment by driesvints** [comment]
How do I reproduce the problem? What steps did you take?

**Comment by olegmelnik** [comment]
I am making request from HTTP client to not an existing endpoint 

<img width="1212" alt="Снимок экрана 2020-03-05 в 16 52 04" src="https://user-images.githubusercontent.com/7072397/75987836-a79e5900-5f01-11ea-9da6-54d85371e468.png">

**Comment by driesvints** [comment]
Sent in a PR for this. It's unsure if this will get accepted as the exception is pretty descriptive on its own but we'll see.

https://github.com/laravel/framework/pull/31764

**Comment by driesvints** [comment]
Pr was rejected so I guess this won't be changed sorry.
