### ISSUE TITLE
Route prefix get truncated when using ->prefix('/') fluent routing registration

### ISSUE THREAD

**Issue by crynobone** [laravel/framework#31759]
- Laravel Version: 7.0.4
- PHP Version: 7.4.3
- Database Driver & Version: N/A

### Description:

Certain fluent route registration will truncate the first URL prefix, this issue has been reported in:

* https://github.com/laravel/framework/issues/31732#issuecomment-594904074
* https://github.com/laravel/nova-issues/issues/2410#issuecomment-595142222

### Steps To Reproduce:

Create a new project

```
composer create-project laravel/laravel sandbox
```

Delete the content of `routes/api.php` since you can't cache closure based route.

Then update the default `routes/web.php` from 

```php
Route::get('/', function () {
    return view('welcome');
});
```

to

```php
Route::middleware(['web'])
    ->domain(null)
    ->name('web.')
    ->prefix('/')
    ->group(function ($router) {
        $router->view('welcome/user', 'welcome');
    });
```

<img width="802" alt="Screenshot 2020-03-05 at 8 16 12 PM" src="https://user-images.githubusercontent.com/172966/75980820-2dc89880-5f1e-11ea-9b43-19390e45e735.png">

Excepted to received `/welcome/user` but gotten `/user`

**Comment by crynobone** [comment]
Interesting enough, if you set `->prefix(null)` you'll get the expected `/welcome/user`. It seem that somewhere in the route cache decoding process there a different between how the parser translate `"/"` vs `null`

**Comment by driesvints** [comment]
Thanks, looking into this

**Comment by driesvints** [comment]
Sent in a PR for this: https://github.com/laravel/framework/pull/31760
