### ISSUE TITLE
php artisan route:catch 404 not found page

### ISSUE THREAD

**Issue by hihuangwei** [laravel/framework#31753]
- Laravel Version: 7.0.4
- PHP Version: 7.4.0
- Database Driver & Version: MySQL

### Description:

resource  routes

`php artisan route:catch`

`exception: "Symfony\Component\HttpKernel\Exception\NotFoundHttpException"
file: "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php"
line: 42
message: ""`

**Comment by driesvints** [comment]
There's not a lot of info here.. Can you please share some code to reproduce the issue?

**Comment by hihuangwei** [comment]
> There's not a lot of info here.. Can you please share some code to reproduce the issue?

`{
    "message": "",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php",
    "line": 42,
    "trace": [
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/CompiledRouteCollection.php",
            "line": 107,
            "function": "handleMatchedRoute",
            "class": "Illuminate\\Routing\\AbstractRouteCollection",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 635,
            "function": "match",
            "class": "Illuminate\\Routing\\CompiledRouteCollection",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 624,
            "function": "findRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 613,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 36,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/mpms/public/index.php",
            "line": 46,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}`

**Comment by driesvints** [comment]
@hihuangwei please share some code. Your routes file is the most important bit here.

**Comment by hihuangwei** [comment]
> @hihuangwei please share some code. Your routes file is the most important bit here.

issuse url 'http://localhost/dashboard/enterprise/user'

file name 'routes/dashboard.php'
`<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['auth:api', 'throttle:2000,1']], function () {
    Route::group(['middleware' => 'scopes:dashboard'], function () {
Route::group(['prefix' => 'enterprise', 'namespace' => 'Enterprise'], function () {
            Route::put('user/{id}/link', 'UserController@link');
            Route::resource('user', 'UserController')->only([
                'index', 'show', 'edit', 'update', 'create', 'store'
            ]);
        });
    }
}`

**Comment by driesvints** [comment]
There's no "dashboard" prefix defined. The below works:

```php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['auth:api', 'throttle:2000,1']], function () {
    Route::group(['prefix' => 'dashboard', 'middleware' => 'scopes:dashboard'], function () {
        Route::group(['prefix' => 'enterprise', 'namespace' => 'Enterprise'], function () {
            Route::put('user/{id}/link', 'UserController@link');
            Route::resource('user', 'UserController')->only([
                'index', 'show', 'edit', 'update', 'create', 'store'
            ]);
        });
    });
});
```

**Comment by hihuangwei** [comment]
@driesvints 

RouteServiceProvider.php

`<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';
    protected $apiNamespace = 'App\Http\Controllers\Api';
    protected $dashboardNamespace = 'App\Http\Controllers\Dashboard';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        // 只有在 id 为数字时才执行。
        Route::pattern('id', '[0-9]+');

        parent::boot();
    }

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();
        $this->mapWebRoutes();
        $this->mapDashboardRoutes();
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }

    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix('api')
            ->middleware('api')
            ->namespace($this->apiNamespace)
            ->group(base_path('routes/api.php'));
    }

    protected function mapDashboardRoutes()
    {
        Route::prefix('dashboard')
            ->middleware('api')
            ->namespace($this->dashboardNamespace)
            ->group(base_path('routes/dashboard.php'));
    }
}
`

**Comment by sapsal** [comment]
/**
 * Define the "web" routes for the application.
 *
 * These routes all receive session state, CSRF protection, etc.
 *
 * @return void
 */
protected function mapWebRoutes()
{
    Route::middleware('web')
        ->namespace($this->namespace)
        ->group(base_path('routes/web.php'));
}
