### ISSUE TITLE
Throwable declaration must be compatible with ExceptionHandler

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#31758]
- Laravel Version: `7.0.4`
- PHP Version: `7.2.28` and `7.3.15`

### Description:
`app/Exceptions/Handler.php`:

![2020-03-05_15-05-37](https://user-images.githubusercontent.com/10347617/75980217-14f6bd80-5ef3-11ea-8659-5e3e4f0abed9.png)

But the minimum [allowed](https://github.com/laravel/framework/blob/7.x/composer.json#L18) php version is - `7.2.5`.

[This section](https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades) of the documentation does not help, since it does not apply to the php version.

PS: There are no problems with PHP 7.4 - it supports such typing.

**Comment by GrahamCampbell** [comment]
Please read the upgrading guide. We fully support PHP 7.2, but you need to update your code as prescribed in the guide.

**Comment by GrahamCampbell** [comment]
That phpstorm recommendation looks wrong. Look at the actual code file. It does not have "Exception" in it.

**Comment by andrey-helldar** [comment]
@GrahamCampbell, thanks!

**Comment by Egzonrexhepi** [comment]
@GrahamCampbell That is true, but any idea how could i now handle Exceptions like in the previous version.
I also think i found a mistake in documentation of laravel 7.x of method render (https://laravel.com/docs/7.x/errors#render-method) it is using old version of this method and i dont think we can still check throwables for exception types. If yes can you explain how please?

**Comment by driesvints** [comment]
@Egzonrexhepi thanks for reporting that. I've sent in a PR to fix those docs: https://github.com/laravel/docs/pull/5866

**Comment by Egzonrexhepi** [comment]
@driesvints What about the workaround on handling cusotm exceptions now? Thanks for fast reply

**Comment by driesvints** [comment]
@Egzonrexhepi I'm not sure what you mean. What's not working for you?

**Comment by Egzonrexhepi** [comment]
@driesvints Before the Handler.php was changed we could do something like this to handle custom http exceptions:
`  public function render($request, Throwable $exception)
    {
        if ($exception instanceof  AuthenticationException) {
            // handle here
        }
//        return parent::render($request, $exception);
    }`

But now that it accepts throwable, how can we do this?

**Comment by driesvints** [comment]
Just like that? It should work exactly the same.

**Comment by Egzonrexhepi** [comment]
@driesvints My bad, i wass missing header params "Accept: application/json" so therefore the middleware was redirecting and not throwing exception. Thanks anyways!
