### ISSUE TITLE
Problem with HTTP facade and withCookies() function

### ISSUE THREAD

**Issue by adamdyderski** [laravel/framework#31750]
Hi,

I have a problem during passing array to withCookies() function of HTTP client facade - Laravel throw an exception:

`InvalidArgumentException {#365
  #message: "cookies must be an instance of GuzzleHttp\Cookie\CookieJarInterface"
  #code: 0
  #file: "D:\Laravel\api\vendor\guzzlehttp\guzzle\src\Middleware.php"
  #line: 31
  trace: { ... }
`

After changing parameter type from array to CookieJarInterface in PendingRequest class:

`public function withCookies(CookieJarInterface $cookies)`

and the CookieJar object is passed, the problem does not occur and everything works fine. Do you know it is Laravel problem or maybe I do something wrong?

**Comment by adamdyderski** [comment]
@driesvints ok, thanks

**Comment by driesvints** [comment]
This was fixed in a different way.
