### ISSUE TITLE
Update model props in "deleting" event observer

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#31754]
- Laravel Version: 5.8.37
- PHP Version: 7.4.3
- Database Driver & Version: sqlite

### Description:

This might be not a bug, but a limitation and an expected behavior, but I didn't find it mentioned in docs.
```
namespace App\Observers;

use App\User;

class UserObserver
{
    public function deleting(User $user)
    {
        $user->status |= User::STATUS_DELETED;
    }
}
```
The model uses `softDeletes`, so it may look redundant while there's `deleted_at` property. However, I have a use case for this and I can imagine a case where I would want to change some other props on delete.

Should the UPDATE query (the one that sets `deleted_at`) after the event is fired include the `status` column? Would be nice. Note that I would not expect `updating`/`updated` event be invoked in this case.

Edit: Corrected method name in the code above from `deleted` to `deleting`.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by ryanmortier** [comment]
@driesvints Hello Dries,

I'm running the latest laravel and having the same issue.

- PHP 8.3
- Laravel v11.34.2
- Database SQL Server 2019

To explain better, I am using the `deleting` event like so:

```php
class WorkOrderObserver
{
    public function deleting(WorkOrder $workOrder): void
    {
        $workOrder->status = WorkOrderStatus::Deleted;
    }
}
```

Unfortunately, the status is not being updated when the model is persisted. I've verified the event is being hit by dumping/logging the model inside the method.

In any of the other `ing` events, I can update a property on the model before it's persisted. For example, I'm doing this with the `restoring` event and it's working. It's only the `deleting` event that this doesn't work. I'm trying to avoid doing a second database query to update the status when the model is **soft-deleted**.
