### ISSUE TITLE
Memcached read timeouts occur silently

### ISSUE THREAD

**Issue by uphlewis** [laravel/framework#31763]
- Laravel Version: 5.8 (i know, i know, but illuminate memcached code hasnt had any real changes since 5.7 so this should still be relevant)
- PHP Version: 7.3.14
- Database Driver & Version: n/a

### Description:
Memcached read timeouts occur silently (no errors or warnings) so there is no visibility into any issues except for a consistent HTTP response slow-down (in my case of 4s universally since my session driver also uses memcached).

### Steps To Reproduce:
1. Configure a memcached server that is unreachable.

2. Run the following
```sh
php artisan tinker
# Psy Shell v0.9.12 (PHP 7.3.14 — cli) by Justin Hileman
$start = microtime(true); dump(Cache::get('foo')); $end = microtime(true); echo sprintf('%fs', $end-$start);
# ^ null
# 4.002080s⏎
Cache::driver()->getStore()->getMemcached()->getResultMessage();
# => "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY"
```

**Comment by driesvints** [comment]
Please try this on the latest version first and then report back. Thanks.
