### ISSUE TITLE
Custom route validators does not work on compiled routes.

### ISSUE THREAD

**Issue by dkulyk** [laravel/framework#31774]
- Laravel Version: 7.0.0-4
- PHP Version: 7.3.14
- Database Driver & Version: MySQL 5.7

### Description:
Multidomain application have  customer pages related to domain. I used custom route validation(ValidatorInterface) for passing route to handling.

In Laravel 7 compiled routes does not used route validators and this behavior is broken.

### Steps To Reproduce:
```php
class PageRouteValidator implements ValidatorInterface
{
    public function matches(Route $route, Request $request)
    {
        if ($route->getName() === 'pages.page') {
            $alias = $route->bind($request)->parameter('alias');

            return Page::query()
                ->where('domain',$route->getDomain())
                ->whereIn('alias', $alias)
                ->exists();
        }

        return true;
    }
}

Route::getValidators();
Route::$validators[] = new PageRouteValidator();
Router::get('{alias}',  'PageController@page')->name('pages.page');

```

Compiled route always matched route.

**Comment by driesvints** [comment]
Unfortunately this won't be possible anymore with the new dumped Symfony matcher. The validators were our own way to do the route matching and the new Symfony matcher takes this over for us so there's no possibility to define validators anymore when routes are cached. This was also all undocumented and not really meant to be used this way. Sorry about that.

**Comment by ollieread** [comment]
@driesvints the symfony router supports conditions, which would make up for things like this. Is there anything on the table to support this, or any room for it?

**Comment by driesvints** [comment]
@ollieread maybe best that you open a ticket in discussions detailing what you want to implement. Make sure to link to said Symfony feature. Feel free to ping me.
