### ISSUE TITLE
Router caching: an error is displayed when trying to optimize "var_export does not handle circular references"

### ISSUE THREAD

**Issue by Manzadey** [laravel/framework#31779]
- Laravel Version: 7.0.4
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7

### Description:

An error is displayed when trying to cache routes:

`var_export does not handle circular references`

at [\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteCacheCommand.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Console/RouteCacheCommand.php):107
```
protected function buildRouteCacheFile(RouteCollection $routes)
{
    $stub = $this->files->get(__DIR__.'/stubs/routes.stub');

    return str_replace('{{routes}}', var_export($routes->compile(), true), $stub);
}
```

1. \vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteCacheCommand.php:107
var_export([])

2. \vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteCacheCommand.php:66
Illuminate\Foundation\Console\RouteCacheCommand::buildRouteCacheFile(Object(Illuminate\Routing\RouteCollection))

`

### Steps To Reproduce:

1. start laravel site
2. php artisan route:cache

**Comment by driesvints** [comment]
Please share your routes.

**Comment by Manzadey** [comment]
> Please share your routes.

Found a problem. 

```
<?php

use App\Models\Front\Landing;
use Illuminate\Database\Eloquent\Collection;

$relationships = [
    'articles',
    'employees',
    'equipments',
    'videos',
    'prices',
];


foreach (Landing::all() as $landing) {

    $compact = [];

    foreach ($relationships as $rel) {
        if ($landing->$rel instanceof Collection && $landing->$rel->isNotEmpty()) {
            $compact[$rel] = $landing->$rel;
        }
    }

    Route::view($landing->slug, 'front.landings.' . $landing->landing_id, $compact)->name($landing->landing_id);
}

```
`$landing->$rel` returned Eloquent Collection. When converting a collection to an array `toArray()`, no errors occur.

But in this case, I need a collection of elements.

**Comment by driesvints** [comment]
I don't think this is a wise idea to do. For this use case I'd recommend using a controller instead. Please use the `toArray` for now if it fixes the problem for you.

**Comment by Manzadey** [comment]
I agree. But I have no other choice. 

Here's why:
`
Route::get('{departments_parent}', 'DepartmentController@parent')->name('parent');
`


Unfortunately this approach doesn't work:
```
Route::get('{departments_parent}', 'DepartmentController@parent')->name('department');
Route::get('{landing}', 'LandingController@index')->name('landing');
```
