### ISSUE TITLE
Memcached read timeouts occur silently

### ISSUE THREAD

**Issue by uphlewis** [laravel/framework#31773]
- Laravel Version: 7.0.4
- PHP Version: 7.3.14
- Database Driver & Version: N/A

### Description:
**Re-posting of https://github.com/laravel/framework/issues/31763 after testing with latest version of the framework**

Memcached read timeouts occur silently (no errors or warnings) so there is no visibility into any issues except for a consistent HTTP response slow-down (in my case of 4s universally since my session driver also uses memcached).

### Steps To Reproduce:
1. Configure CACHE_DRIVER to memcached, and configure a memcached server that is unreachable (e.g., as in my case - an AWS elasticache instance in a VPC unreachable by my local VM).
2. Run the following
```bash
php artisan tinker
# Psy Shell v0.9.12 (PHP 7.3.14 — cli) by Justin Hileman
>>> $start = microtime(true); dump(Cache::get('foo')); $end = microtime(true); echo sprintf('%fs', $end-$start);
# null
# 4.060695s⏎
>>> Cache::driver()->getStore()->getMemcached()->getResultMessage();
# => "A TIMEOUT OCCURRED"
>>> $start = microtime(true); dump(Cache::get('foo')); $end = microtime(true); echo sprintf('%fs', $end-$start);
# null
# 4.144948s⏎
>>> Cache::driver()->getStore()->getMemcached()->getResultMessage();
# => "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY"
```

**Comment by driesvints** [comment]
Hmm, I don't know myself unfortunately. I'll leave this open to see if someone else has any ideas.

**Comment by uphlewis** [comment]
Yeah i did have a brief dig but couldnt see an immediately obvious solution beyond checking the return value of `Memcached::getResultCode()` after each connect/read/write operation which feels a little wrong. Not spent enough time working with PHP's memcached driver to know if there's a "better" way.

**Comment by driesvints** [comment]
I couldn't reproduce the timeouts from above unfortunately, I always got the "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" message.

**Comment by uphlewis** [comment]
> I couldn't reproduce the timeouts from above unfortunately, I always got the "SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY" message.

As an exception ?? The issue is that the framework's memcached API makes it seem like a benign cache miss; no error is surfaced when memcached is unavailable.

**Comment by driesvints** [comment]
Heya, it's actually indeed not wanted that these errors bubble up as exceptions. When your cache fails you want it to fail silently and not bring down your app.

**Comment by uphlewis** [comment]
Debatable, but ok !!
