### ISSUE TITLE
Str::slug("some string", "") will issue PHP Warning

### ISSUE THREAD

**Issue by axit-joost** [laravel/framework#31776]
* Laravel Version: 7.0.4
* PHP Version: 7.4.3

### Description:

Observed that
```php
Str::slug('some text', '');
```
No longer yields
```
=> "sometext"
```
like it did in Laravel 6.x

In Laravel 7.x it yields:
```
PHP Warning:  strpos(): Empty needle in vendor/voku/portable-ascii/src/voku/helper/ASCII.php on line 882
```
Which can be traced back to commit eea5d5df51ddc2055e71436913deeed97ccaaaa2, [7.x] Update external ascii package (#29947) (#31383)

Also observed that there is no test for this case it in `SupportStrTest::testSlug()`.

And although one might never do this, an `empty string` does not equal to `null`, therefore the default argument value of '-' is not applied to `$separator`. However, this empty string *will* reach the `strpos()` call in the `ASCII` library.

According to the official `strpos()` documentation, the `needle` must be a string. If it's not a string, it is converted to an integer and applied as an ordinal value of a character. What the documentation fails to report, is that passing an `empty string` will issue a `WARNING`.

Finally, observed that this was not documented as a potential breaking change.

**Comment by axit-joost** [comment]
cc @voku perhaps something that your `portable-ascii` package should handle?

**Comment by taylorotwell** [comment]
We may just have to revert slug handling to match our 6.x logic instead of using the package.

**Comment by driesvints** [comment]
We've reverted the slug changes.
