### ISSUE TITLE
New Custom Casting For Eloquent Models Has Excessive set() calls

### ISSUE THREAD

**Issue by ralphschindler** [laravel/framework#31778]
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Database Driver & Version:
n/a

### Description:
When attempting to write a CustomCast that will convert between a complex Object and the serialization for the database, `CastAttributes::set()` is called an excessive amount of times. This could be problematic (and unnecessary) if the work to serialize is non-trivial (like converting points into a binary representation.)

This is due to excessive calls to `HasAttributes::mergeAttributesFromClassCasts()` that originate from multiple places in both `Model::getAttributes()` and `Model::save()` calls: 

- from `save()` itself: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Model.php#L670
- then from `save()` calling `performInsert()` calling `getAttributes()`:
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Model.php#L827
- then from `save()` calling `finishSave()` calling `isDirty()` calling `getDirty()` calling `getAttributes()`: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1326
- then from `save()` calling `finishSave()` calling `syncOriginal()` calling `getAttributes()`: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1205

There is probably more to unpack here, and perhaps custom attributes should only be doing lightweight transformation, but it feels like this could be a good tool if Eloquent could manage to only transform the values to a savable value once before insert/update. Should we continue this discussion?

### Steps To Reproduce:
https://github.com/laravel/framework/compare/7.x...ralphschindler:custom-cast-excessive-calls

**Comment by driesvints** [comment]
Going to leave this to Taylor to review

**Comment by taylorotwell** [comment]
Yeah, probably worth exploring if we can get rid of some of those redundant calls for sure.

**Comment by driesvints** [comment]
Even though nothing's broken, I'm gonna mark this as a bug so we can take a look at this later on. Appreciating prs in the meantime!

**Comment by gentcys** [comment]
Suppose we set the attributes of Eloquent Model through the way specified in the [test](https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php): 
```php
$model->address = $address = new Address('110 Kingsbrook St.', 'My Childhood House');
$address->lineOne = '117 Spencer St.';
```
The [`mergeAttributesFromClassCasts`](https://github.com/laravel/framework/blob/b6063e6d227ee7b9a0a823062f68a689690e44cc/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1091) method guarantees that every castable attributes set by the way above will be cast before save. 

What if we add a property like `$originalClassCastCache`(named it just an example) as a comparison to `$classCastCache`, each element in latter property is a deep copy of element in former property. 

```php
$classCastCache['address'] = unserialize(serialize($originalClassCastCache['address']));
```

And the [`mergeAttributesFromClassCasts`](https://github.com/laravel/framework/blob/b6063e6d227ee7b9a0a823062f68a689690e44cc/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1091) method make a comparison of each element referenced by the same key(like `'address' => `). If it's different then do the merge action.

```php
protected function mergeAttributesFromClassCasts()
{
    foreach ($this->classCastCache as $key => $value) {
        if ($this->classCastCache[$key] == $this->originalClassCastCache[$key] ) {
            continue;
        }
        
        $caster = $this->resolveCasterClass($key);

        $this->attributes = array_merge(
            $this->attributes,
            $caster instanceof CastsInboundAttributes
                   ? [$key => $value]
                   : $this->normalizeCastClassResponse($key, $caster->set($this, $key, $value, $this->attributes))
        );
    }
}
```

@driesvints @taylorotwell
