### ISSUE TITLE
Artisan view:cache not caching vendor views

### ISSUE THREAD

**Issue by stayallive** [laravel/framework#31789]
- Laravel Version: 7.0.2
- PHP Version: 7.4.2
- Database Driver & Version: n.v.t.

### Description:

As discovered because "Allow disabling checks for expired views" (#31206), `php artisan view:cache` does not seem to generate cached views for vendor views.

This does not look like an issue with the expired views check disabling but a "bug" (or maybe better "omission") from the `view:cache` command to consider vendor views.

### Steps To Reproduce:

Install Laravel + Horizon and run `php artisan view:cache`, add `VIEW_CHECK_EXPIRATION=false` to your `.env` and visit `/horizon`.

This should produce something like:

```
include(/var/www/staging/storage/framework/views/737e90b7e3fd02fa774d19f2efa426527c54bb06.php): failed to open stream: No such file or directory (View: /var/www/staging/releases/20200305214528/vendor/laravel/horizon/resources/views/layout.blade.php)
```

Another report on the original PR: https://github.com/laravel/framework/pull/31206#issuecomment-595569353.

**Comment by driesvints** [comment]
Ping @browner12

**Comment by stayallive** [comment]
I do hope this means it's temporary reverted until `view:cache` can also compile vendor views? 

I really like this feature in itself and as said this _is not an issue with the feature reverted_. 

Could we keep this (or another issue) open until someone wants/can improve the `view:cache` behaviour to also include vendor views so this feature can be brought back?

**Comment by driesvints** [comment]
@stayallive since the bug for this was fixed for now there's no reason to keep an issue open on this repo. You're free to open one on the ideas repo if you like or attempt a new pr.

**Comment by browner12** [comment]
sorry to resurrect an old issue, but did anyone ever confirm this issue and that `view:cache` did not handle package views?

I've been messing around with the command all day, and as far as I can tell it's compiling views from packages registered in the default `loadViewsFrom()` method **and** in the `publishes()` custom vendor directory.

there don't appear to be any relevant changes that would have fixed this behavior from 2 years ago.
