### ISSUE TITLE
Customize RouteServiceProvider File Override Constant

### ISSUE THREAD

**Issue by Ghiffari** [laravel/framework#31788]
- Laravel Version: 6.*
- PHP Version: 7.2
- Database Driver & Version:

### Description:

I added new function under RouteServiceProvider to setup new routes file, and it overrides constant, I'm not sure if it's intended like that or not

### Steps To Reproduce:

1. Customize new routes
```php
protected function mapUIRoutes()
    {
        Route::prefix('ui')
            ->namespace($this->namespace)
            ->group(base_path('routes/ui.php'));
    }
```

2. Register in map
 ```php
$this->mapApiRoutes();        
     $this->mapWebRoutes();
        if(env("APP_ENV") == "local"){

            $this->mapUIRoutes();
        }
```
once I access example.test/login it shows error

> Symfony\Component\Debug\Exception\FatalThrowableError
Undefined class constant 'App\Providers\RouteServiceProvider::HOME'

### Current solution
re-add this line on app\Providers\RouteServiceProvider.php

`public const HOME = '/home';`

**Comment by driesvints** [comment]
You need to add the constant: https://github.com/laravel/laravel/blob/6.x/app/Providers/RouteServiceProvider.php#L24
