### ISSUE TITLE
Extract view component from routing component 

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/framework#31781]
- Laravel Version: any
- PHP Version: any
- Database Driver & Version: doesn't matter

### Description:
The Routing component is tightly coupled to view component
https://github.com/laravel/framework/blob/2f9ebc2bb4ec482afdca959f19184d8c4505e99d/src/Illuminate/Routing/ResponseFactory.php#L6

this seams weird, since for example, if I want build some API I will also need the view component. I can't  

### Steps To Reproduce:
1) run laravel app on api only route
2) remove `Illuminate\View\ViewServiceProvider`
3) see it fail

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
