### ISSUE TITLE
softDelete on migration creates field label 0

### ISSUE THREAD

**Issue by lesaff** [laravel/framework#31780]
- Laravel Version: 7.x
- PHP Version: 7.3.1.5
- Database Driver & Version: mysql MariaDb 10.4.11

### Description:
When creating a migration table with `$table->softDeletes(0);` it creates a field labeled `0` instead of `deleted_at`

### Steps To Reproduce:
- Create a migration
- Add `$table->softDeletes(0);`

**Comment by driesvints** [comment]
Don't do that. The first parameter is the column name.

**Comment by lesaff** [comment]
Well, documentation needs to be updated then?

![Screen Shot 2020-03-05 at 4 55 03 PM](https://user-images.githubusercontent.com/1151181/76024826-2398a100-5f02-11ea-84d5-d3ec4790287d.png)

**Comment by driesvints** [comment]
Hmm, yeah that seems to be incorrect. Thanks for spotting!

**Comment by driesvints** [comment]
Sent in a fix for that: https://github.com/laravel/docs/pull/5864
