### ISSUE TITLE
Casts returning error after upgrade to L7

### ISSUE THREAD

**Issue by ron-florax** [laravel/framework#31790]
- Laravel Version: 7.0.3
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.19

### Description:
I've got several models casting an array to json. These were working fine before upgrading to Laravel 7, but now return the exception `ErrorException json_decode() expects parameter 1 to be string, array given in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:827` . This seems to occur after creating a model with the json-field set, then reusing the model instance and running `save()` on it. I've also tried casting to `array`, have been through the upgrade guide several times, as well as the comparison between the 6.x and master-branches on this repo. Obviously a lot has changed in casting, so I might have missed something?

### Steps To Reproduce:

**Model:**
```
class Frame extends BaseModel
{
protected $fillable = [
        'remaining_balls',
    ];

    protected $casts = [
        'remaining_balls' => 'json',
    ];
}
```

**Controller:**
```
$frame = Frame::create([
            'remaining_balls' => [
                'reds' => $match->reds,
                'yellow' => true,
                'green' => true,
                'brown' => true,
                'blue' => true,
                'pink' => true,
                'black' => true,
            ],
        ]);

        $frame->player_1_points = ($match->player_1_handicap) ? $match->player_1_handicap : 0;
        $frame->save();
```

**Comment by GrahamCampbell** [comment]
Is this still happening in 7.0.4 or the latest commit on the 7.x branch?

**Comment by ron-florax** [comment]
@GrahamCampbell Yes, it's still happening on those.

**Comment by themsaid** [comment]
I don't understand your steps of replication? 

```
$user = \App\User::find(1);

$user->save();

return $user;
```

This works, if there's a JSON field in the user model it's casted to array without issues.

**Comment by ron-florax** [comment]
@themsaid It's when you change a value of a field before calling `save()`.

**Comment by themsaid** [comment]
```
$user = \App\User::find(1);

$user->name = 'Mohamed';

$user->save();

return $user;
```

Still works, I get the response:

```
{"id":1,"name":"asd","email":"mohamed@mail.com","email_verified_at":null,"remember_token":[1,2,3],"created_at":"2020-03-06T06:08:36.000000Z","updated_at":"2020-03-06T10:59:04.000000Z"}
```

See `remember_token` casted to array and stored in DB as JSON. No problems.

**Comment by ron-florax** [comment]
It turns out this is an issue in Spatie ActivityLogger (https://github.com/spatie/laravel-activitylog/issues/680). Sorry for wasting your time, thanks for the help!
