### ISSUE TITLE
Markdown mail templates need to be unindented

### ISSUE THREAD

**Issue by AntoineAugusti** [laravel/framework#31805]
- Laravel Version: 7.02
- PHP Version: 7.4.3

### Description:
In the following commit https://github.com/laravel/framework/commit/f17e347b15e8d27b4e775a8f961bda083326ee8f, HTML mail templates were deindented. 

Previously, I [exported the default template](https://laravel.com/docs/5.7/mail#customizing-the-components). After upgrading to Laravel 7,  the panel component spits outs HTML in the email 
![image](https://user-images.githubusercontent.com/295709/76097008-f517d600-5f94-11ea-9780-54cfb62a74f3.png)

This is a bug to me because:
- in order to fix the issue, people need to unindent their files or republish and apply changes
- the upgrade guide does not say to republish assets

**Comment by driesvints** [comment]
We can't revert this. You'll need to republish your templates. We'll add this to the upgrade guide.

**Comment by AntoineAugusti** [comment]
Thanks for updating the upgrade guide.

Can you unindent templates maybe?

**Comment by driesvints** [comment]
> Can you unindent templates maybe?

That's not possible with the new parser.

**Comment by CyrilMazur** [comment]
Sorry to resuscitate an old issue, but would that be possible to disable this behaviour for those who want? (with a config variable maybe). I'm sure most Laravel devs see more value in being able to indent their mail templates, rather than being able to send mails that display raw code.

**Comment by driesvints** [comment]
@CyrilMazur it's not possible with the current parser. You'll get the same result as the screenshot above.

**Comment by CyrilMazur** [comment]
Gotta get used to templates without indentation then 💩
