### ISSUE TITLE
Declaration of Illuminate\Foundation\Application::handle incompatible on 7.0.4

### ISSUE THREAD

**Issue by vladoa** [laravel/framework#31803]
- Laravel Version: 7.0.4
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
I tried putting my fresh Laravel 7 application on a live server with Envoyer. After the deployment, there is an error message when opening any screen of the app:
`PHP Fatal error:  Declaration of Illuminate\Foundation\Application::handle(Symfony\Component\HttpFoundation\Request $request, $type = self::MASTER_REQUEST, $catch = true) must be compatible with Symfony\Component\HttpKernel\HttpKernelInterface::handle(Symfony\Component\HttpFoundation\Request $request, int $type = self::MASTER_REQUEST, bool $catch = true) in /usr/www/users/myuser/mydomain.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 29`

I also tried PHP 7.2 and PHP 7.4.
Maybe I am doing something wrong. Please don't get upset if that is the case.

### Steps To Reproduce:
Install Laravel 7.0.4 on PHP 7.3.11
Or there might be some other reason. I don't know.
There are also other people experiencing this issue:
https://laracasts.com/discuss/channels/laravel/laravel-7-error

**Comment by driesvints** [comment]
Thanks for noting this. Sent in a PR here: https://github.com/laravel/framework/pull/31806
