### ISSUE TITLE
Str::slug now returns different results

### ISSUE THREAD

**Issue by Lloople** [laravel/framework#31801]
- Laravel Version: 7.0.4
- PHP Version: 7.3.14
- Database Driver & Version: MySQL 5.7

### Description:
I have a test where I slugify a string such as `Offer with 15% discount` and check that the result is `offer-with-15-discount`. Since I updated to Laravel 7 this test fails because `Str::slug` now returns `offer-with-15-percent-discount`. 

This would not be an issue since this result is more SEO friendly, but the package used here doesn't have all the languages in place, `Spanish` an `Catalan` are missing for example. 

I suggest removing the `$replace_extra_symbols` flag so the result would be as it was before until the library has more languages or be able to call `Str::slug($string, $separator, $language, $extraSymbols)`.

### Steps To Reproduce:

Laravel 6:

```
>>> Str::slug('Offer with 15% discount')
=> "offer-with-15-discount"
``` 

Laravel 7:

```
>>> Str::slug('Offer with 15% discount')
=> "offer-with-15-percent-discount"
```

**Comment by driesvints** [comment]
We've reverted the pr that caused this in 7.0.5 so can you try that version?

**Comment by Lloople** [comment]
@driesvints Tried it and works as expected. Thank you very much! 🥳

**Comment by GrahamCampbell** [comment]
There are also tests now ensure this doesn't break later, or at least, that we actively would have to decide to break it.
