### ISSUE TITLE
refresh(): Call to undefined relationship [pivot] on model

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#31811]
- Laravel Version: 6.18.0
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7

### Description:

This is a regression introduced in #31125 - all custom pivot models that uses [`AsPivot`](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php) trait are broken now due to this line:

https://github.com/laravel/framework/blob/898f24ec56d5a2859a28f4dc0cc98ae967eec456/src/Illuminate/Database/Eloquent/Model.php#L1154

obviously it should also check if the model uses `AsPivot` trait. Something like:

```php
return $relation instanceof Pivot
    || in_array(AsPivot::class, class_uses_recursive($relation), true);
```

### Steps To Reproduce:

1. Create new laravel 6.x app
2. Create `user_users` table
    ```sql
    CREATE TABLE IF NOT EXISTS `user_users` (
        `my_user_id` BIGINT(20) UNSIGNED NOT NULL,
        `pivot_my_user_id` BIGINT(20) UNSIGNED NOT NULL
    )
    ```
3. Run this test
    ```php
    <?php
    
    namespace Tests\Unit;
    
    use App\User;
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Database\Eloquent\Relations\Concerns\AsPivot;
    use Tests\TestCase;
    
    class ExampleTest extends TestCase {
        public function testAsPivotRefresh() {
            $user  = MyUser::query()->findOrFail(factory(User::class)->create()->getKey());
            $child = MyUser::query()->findOrFail(factory(User::class)->create()->getKey());
    
            $user->users()->attach($child->getKey());
    
            $this->assertEquals(1, $user->users->count());
    
            $user->users->first()->refresh();
        }
    }
    
    class MyUser extends User {
        protected $table = 'users';
    
        public function users() {
            return $this
                ->belongsToMany(static::class, (new UserPivot())->getTable(), 'my_user_id', 'pivot_my_user_id')
                ->using(UserPivot::class);
        }
    }
    
    class UserPivot extends Model {
        use AsPivot;
    
        protected $table = 'user_users';
    }
    ```

**Comment by GrahamCampbell** [comment]
> in_array(AsPivot::class, class_uses_recursive($relation), true);

This feels kinda hacky. Shouldn't we have an interface for this?

**Comment by LastDragon-ru** [comment]
> This feels kinda hacky. Shouldn't we have an interface for this?

Agreed, but interface will not fix existing code

**Comment by ryangjchandler** [comment]
> > in_array(AsPivot::class, class_uses_recursive($relation), true);
> 
> This feels kinda hacky. Shouldn't we have an interface for this?

I'd prefer to use the interface in all honesty, and I'm sure if people run into this problem they will find the information in the docs somewhere.

I don't believe traits should be used to enforce outside functionality on the edge of your application. The interface approach has already been taken with other checks & rules for model classes.

Happy to make a PR with the new marker interface.

**Comment by driesvints** [comment]
Why aren't you extending the `Pivot` class?

**Comment by LastDragon-ru** [comment]
> Why aren't you extending the Pivot class?

@driesvints same reasons as described in initial PR #25851

**Comment by driesvints** [comment]
I see. Then an interface won't work here because people would have to implement it manually to solve the problem. We could maybe go for the solution you proposed above. Feel free to send in a PR.
