### ISSUE TITLE
Error send mail

### ISSUE THREAD

**Issue by serderovsh** [laravel/framework#31817]
- Laravel Version: 7.0.1
- PHP Version: 7.3
- Database Driver & Version: Mysql

### Description:

When trying to send a message through "smtp" an error occurs.

1. https://github.com/laravel/laravel/blob/master/config/mail.php - the configuration is such
2. Returns the text: **Undefined index: host**

**Code example 1:**
```php
 Mail::mailer('smtp')
                    ->to(config('mail.email_support'))
                    ->send(new TestMailRequest());
```

**Code example 2:**
```php
 Mail::to(config('mail.email_support'))
                    ->send(new TestMailRequest());
```

The error occurs at the stage "createSmtpTransport", the parameter "host" cannot be found.
**Link code:** https://github.com/laravel/framework/blob/7.x/src/Illuminate/Mail/MailManager.php#L186

Maybe I made a mistake somewhere, but after changing the configuration "mail", this error appears

**Comment by serderovsh** [comment]
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Mail/MailManager.php#L186 
An error occurs at this point.

**Comment by driesvints** [comment]
@serderovsh you haven't accidentally emptied your `MAIL_HOST` env variable have you? https://github.com/laravel/laravel/blob/master/.env.example#L27

**Comment by serderovsh** [comment]
**My env code**
```env
MAIL_MAILER=smtp
MAIL_HOST=
MAIL_PORT=465

**Comment by serderovsh** [comment]
Everything works when I do this:


**mail.php**
```php
return = [
'mailers' => [
  //code default
],

'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
'port' => env('MAIL_PORT', 587),
'encryption' => env('MAIL_ENCRYPTION', 'tls'),
'username' => env('MAIL_USERNAME'),
'password' => env('MAIL_PASSWORD'),
]

**Comment by themsaid** [comment]
Remove this from your mail.php config file

```
'driver' => env('MAIL_DRIVER', 'smtp'),
```

and replace it with 

```
'default' => env('MAIL_MAILER', 'smtp'),
```

**Comment by vincenzoraco** [comment]
I have this problem with queue. I have debugged it and the host index seems to be okay, but as soon as it goes to a queue, it became unavailable.

Any idea why?

**Comment by 7snovic** [comment]
As mentioned, replacing  `'driver' => env('MAIL_DRIVER', 'smtp'),` by `'default' => env('MAIL_MAILER', 'smtp'),` will do the trick.

However, I spent over 20 minutes to figure out that, keeping the `'driver' => env('MAIL_DRIVER', 'smtp'),` in the mail.php config file seems to tell Laravel to use the old-fashioned configurations. I was keeping it as a backward compatibility but figured out that it will break the mail sending, so you need to comment it out or remove it and replace it with `'default' => env('MAIL_MAILER', 'smtp'),`
