### ISSUE TITLE
[7.x] BUG - Undefined index: bindingFields

### ISSUE THREAD

**Issue by nanophp** [laravel/framework#31825]
- Laravel Version: 7.0.6
- PHP Version: 7.3.14
- Database Driver & Version:

### Description:

I have a BranchStoreRequest class
![image](https://user-images.githubusercontent.com/7104643/76143164-c4f83200-607d-11ea-9d7f-1517c148d0c3.png)

Into BranchController

![image](https://user-images.githubusercontent.com/7104643/76143170-d9d4c580-607d-11ea-90df-f35786244dd4.png)

### Steps To Reproduce:

namespace Illuminate\Routing;
method: CompiledRouteCollection

![image](https://user-images.githubusercontent.com/7104643/76143194-fe30a200-607d-11ea-847e-f5e123745e2e.png)

**Comment by driesvints** [comment]
Did you try re-caching your routes?

**Comment by nanophp** [comment]
> Did you try re-caching your routes?

@driesvints Handler class defined globally all possible exception. What kind of exception class for example?

**Comment by driesvints** [comment]
@nanophp we added key this as a bug fix for cached routing. Can you please try to re-cache your routes?

**Comment by nanophp** [comment]
> @nanophp we added key this as a bug fix for cached routing. Can you please try to re-cache your routes?

@driesvints after re-cache it works. It would be better mark as bugfix.
