### ISSUE TITLE
[7.x] deleted_at value no longer listed as dirty when soft deleting

### ISSUE THREAD

**Issue by quetzyg** [laravel/framework#31823]
- Laravel Version: 7.0.5+
- PHP Version: 7.3.11
- Database Driver & Version: SQLite 3.28.0

### Description:
Since this [change](https://github.com/laravel/framework/commit/d1859a5e7e5f32d9ccdfd9fb095cc00ed172a958#diff-b565fe8ac473cfd17864956b2f146308R96) was introduced in version 7.0.5, the `deleted_at` attribute no longer is considered _dirty_. This also affects other attributes that might be modified in the model prior to soft deleting.

### Steps To Reproduce:
Upgrade to framework version 7.0.5 or above, soft delete a model. The `deleted_at` key and corresponding value are no longer returned when calling `getDirty()`.

### Additional information
Here's the [failing test](https://gitlab.com/altek/accountant/-/jobs/462953341) of a package I maintain and here's the [part](https://gitlab.com/altek/accountant/-/blob/master/tests/Integration/RecordingTest.php#L365) where it broke.

**Comment by staudenmeir** [comment]
> the deleted_at attribute no longer is considered dirty

After the UPDATE query, the `deleted_at` attribute _is_ no longer dirty.

> This also affects other attributes that might be modified in the model prior to soft deleting.

`runSoftDelete()` only syncs the attributes that its UPDATE query updated. Other attributes are still dirty.

**Comment by driesvints** [comment]
@quetzyg please see the answer by @staudenmeir
