### ISSUE TITLE
[7.x] Unable to prepare route [api/user] for serialization. Uses Closure. (LogicException)

### ISSUE THREAD

**Issue by devmansurov** [laravel/framework#31821]
- Laravel Version: 7.0.6
- PHP Version: 7.4.2
- Database Driver & Version: MariaDB 10.4.11 (XAMPP)

### Description

I have installed laravel 7 in my local server. When I run `php artisan route:cache` command then laravel return error:

> **LogicException**
> 
> Unable to prepare route **[api/user]** for serialization. Uses Closure.

This problem was not in previous versions of the framework.

**Comment by msonowal** [comment]
@devmansurov 
When route has closures you can not cache route so you need to map with controller action

**Comment by driesvints** [comment]
> This problem was not in previous versions of the framework.

Closure routes were never supported so this definitely was.

**Comment by imamhsn195** [comment]
I am facing this problem with laravel 7 from laravel5.3. Please help me.

**Comment by JefferyHus** [comment]
This issue still exists, even using a controller method didn't help at all. Laravel still throws the same error

**Comment by NanhBunsin** [comment]
@msonowal  
you said when a route has closures you can not cache route so you need to map with controller action I am a new Laravel learner I also met this issue on how to map with controller action?

**Comment by hk7507** [comment]
route/api. Then comment this:
//Route::middleware('auth:api')->get('/user', function (Request $request) {
//    return $request->user();
//});

**Comment by driesvints** [comment]
In Laravel 8 it'll be possible to cache routes using closures.

**Comment by gzai** [comment]
I have same issue ( laravel 7.23.2 ), after run ```php artisan optimize``` then laravel return error 
```
Unable to prepare route [/] for serialization. Uses Closure.
```

My web root 
```
Route::get('/', function () {
    return view('welcome');
});
```

**Comment by driesvints** [comment]
Going to lock this to prevent more "I have this too" comments.
