### ISSUE TITLE
QueryBuilder exists() does not respect query scope

### ISSUE THREAD

**Issue by willhatchVista** [laravel/framework#31834]
- Laravel Version: 5.8.36
- PHP Version: 7.3.10
- Database Driver & Version:
mysql 5.7.28
### Description:
query builder exists() method does not respect global scope

### Steps To Reproduce:

We have a Spark integration with a global scope on all major entities that limits their access by team_id

So that querying User::all() would only return those with a role on the current team. 

However when I query User::exists($id) the result is true, but when I call User::find($id) the result is null because of scope.

**Comment by staudenmeir** [comment]
[`exists()`](https://github.com/laravel/framework/blob/d234d8ac6b06c076c5ebb1d485c821ebac1cc988/src/Illuminate/Database/Query/Builder.php#L2416) doesn't accept any parameters.

Use one of these queries:

```php
User::where('id', $id)->exists();
User::whereKey($id)->exists();
```

**Comment by willhatchVista** [comment]
Thank you!

**Comment by rudiedirkx** [comment]
I can explicitly call `applyScopes()` on the query, before `exists()`, but that's silly:

```php
Level::query()->where([
  'country_id' => 234,
])->applyScopes()->exists()
```
