### ISSUE TITLE
failed() method not getting hit after a job is failed

### ISSUE THREAD

**Issue by axtricssolutions** [laravel/framework#31839]
- Laravel Version: 6.16.0
- PHP Version: 7.3.15
- Database Driver & Version: Mysql 8

### Description:
Hi,

I am running few jobs and trying to setup a failed() public method within the job itself. Though even after throw a manual exception i can see that the job is failed and sent into failed_jobs table but the failed method is not getting hit.
Here is my code

`
public function failed(Exception $exception) { 
Log::channel('jobs')->error('Catalog Sync Failed for Merchant');
 }`

Kindly note that Failed Jobs Event is getting hit though and i am using https://github.com/spatie/laravel-failed-job-monitor to manage that.

What is wrong here? Can anybody help?

**Comment by themsaid** [comment]
I can't replicate. It's more likely an issue with your app.
