### ISSUE TITLE
MailManager exception thrown when using "mailgun" driver 

### ISSUE THREAD

**Issue by jfrabaute** [laravel/framework#31845]
- Laravel Version: v7.0.4
- PHP Version: 7.2.26

### Description:
After upgrading from 6.X to 7.X the mailer throws an exception.
It should also fail on a brand new laravel 7.X install.

### Steps To Reproduce:
Install laravel 7.x
On the env file for the current environment, set MAIL_MAILER to:

MAIL_MAILER=mailgun

Try to send an email.
An exception is thrown:
```
InvalidArgumentException
Mailer [mailgun] is not defined.

Illuminate\Mail\MailManager::resolve
vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:111
```

```php
    protected function resolve($name)

    {

        $config = $this->getConfig($name);

 

        if (is_null($config)) {

            throw new InvalidArgumentException("Mailer [{$name}] is not defined.");

        }
```

IIUC, possible reason: The doc says to put the mailgun config into config/services.php. But the code is checking if a config with the same name as the MAIL_MAILER exists so it fails as the following method of MailManager is returning null for "mailgun" driver:

```php
    /**
     * Get the mail connection configuration.
     *
     * @param  string  $name
     * @return array
     */
    protected function getConfig(string $name)
    {
        // Here we will check if the "driver" key exists and if it does we will use
        // the entire mail configuration file as the "driver" config in order to
        // provide "BC" for any Laravel <= 6.x style mail configuration files.
        return $this->app['config']['mail.driver']
            ? $this->app['config']['mail']
            : $this->app['config']["mail.mailers.{$name}"];
    }
```

Should "mailgun" be defined in the "config.mail.mailers" array?
Maybe just have:

```php
'mailers' => [
  'mailgun' => true,
...
```

could be enough, I haven't tried.

Or maybe the mailgun config should move from the config/services.php file to the config/mail.php file in the "mailers" array?

**Comment by MaximeWillinger** [comment]
It has been fixed on https://github.com/laravel/laravel/commit/efcf74f422b381a69da8f673061eb94487e6f557 
You can just update your mail.php file to the latest version.

**Comment by jfrabaute** [comment]
Great, thank you!
