### ISSUE TITLE
addSelect statement is lost outside a where clause on the Eloquent builder [ADVICE]

### ISSUE THREAD

**Issue by denitsa-cm** [laravel/framework#31850]
- Laravel Version: 6.18.0
- PHP Version: 7.4.3
- Database Driver & Version: mysq 8.0.15

### Description:

`addSelect` gets lost outside where.

### Steps To Reproduce:

The query starts as:

```
Publisher::select('providers.*')
```
Basically I'm doing a manual select on the model which uses the `providers` table. I'm doing this because this is part of a paginated filter/sort in a list view and I need to continue doing a lot of chaining on this, where I need the columns to be explicitly selected.  Then inside a `where` I do an `addSelect` with a computed column.

With this code:

```
$query = Publisher::select('providers.*');

dump('dump 1', $query->toSql());

$query->where(function ($query) {
    $query->addSelect([
        'current_subscriptions_total_original_price' =>
            SubscriptionPeriod::select(DB::raw('SUM(subscription_periods.price)'))
              ->whereColumn('subscription_periods.publisher_id', 'providers.id')
              ->whereDate('subscription_periods.start_date', '<=', today())
              ->whereDate('subscription_periods.end_date', '>=', today())
              ->whereNull('subscription_periods.deleted_by')
              ->whereNull('providers.deleted_by')
              ->groupBy('providers.id'),
         ]);
    dump('dump 2', $query->toSql());
    return $query;
});

dd('dump 3', $query->toSql());
```

This is what gets dumped:

Dump 1.
```
select `providers`.* from `providers` 
where `providers`.`deleted_at` is null 
  and `providers`.`type` = ?;"
```

Dump 2
```
select `providers`.*, 
  (select SUM(subscription_periods.price) from `subscription_periods` 
  where `subscription_periods`.`publisher_id` = `providers`.`id` 
  and date(`subscription_periods`.`start_date`) <= ? 
  and date(`subscription_periods`.`end_date`) >= ? 
  and `subscription_periods`.`deleted_by` is null and `providers`.`deleted_by` is null 
  and `subscription_periods`.`deleted_at` is null group by `providers`.`id`) as 
  `current_subscriptions_total_original_price` from `providers` 
  where `providers`.`deleted_at` is null 
  and `providers`.`type` = ?;
```
Dump 3 where the entire `addSelect` is no longer present.

```
select `providers`.* from `providers` 
where `providers`.`deleted_at` is null 
  and `providers`.`type` = ?"
```

I need the `where` because all the conditions that could be applied inside need to be isolated.

However, the `addSelect` is lost outside the `where` condition.

What is the best way to hack around this?

**Comment by rodrigopedra** [comment]
HI @denitsa-cm , I think you don't need to nest the `addSelect` inside the `where` closure, as the  `addSelect` will add the columns as a subquery, so it is already isolated from the outer query where clauses

~~~php
$query = \App\Publisher::select('providers.*');

$query->addSelect([
    'current_subscriptions_total_original_price' =>
        SubscriptionPeriod::select(DB::raw('SUM(subscription_periods.price)'))
            ->whereColumn('subscription_periods.publisher_id', 'providers.id')
            ->whereDate('subscription_periods.start_date', '<=', today())
            ->whereDate('subscription_periods.end_date', '>=', today())
            ->whereNull('subscription_periods.deleted_by')
            ->whereNull('providers.deleted_by')
            ->groupBy('providers.id'),
]);

dump($query->toSql());
~~~

Returned

~~~sql
select `providers`.*, (select SUM(subscription_periods.price) from `subscription_periods` where `subscription_periods`.`publisher_id` = `providers`.`id` and date(`subscription_periods`.`start_date`) <= ? and date(`subscription_periods`.`end_date`) >= ? and `subscription_periods`.`deleted_by` is null and `providers`.`deleted_by` is null group by `providers`.`id`) as `current_subscriptions_total_original_price` from `providers` where `providers`.`deleted_at` is null and `providers`.`type` = ?
~~~

Also, please consider posting this kind of question in one of the support forums:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co)
* [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

In general Laravel team advised to use this issue tracker for reporting bugs with the library itself.

Reference: https://github.com/laravel/framework/issues/31729#issuecomment-594578603

**Comment by denitsa-cm** [comment]
@rodrigopedra Thanks for the reply. I still find the `addSelect` being lost outside the `where` clause an odd behaviour.

**Comment by denitsa-cm** [comment]
What happens inside the `where` is dynamic in my case -> sometimes it could be this `addSelect`, sometimes it could just be applying some other conditions that should be grouped inside a `where`. Hence I want to keep everything inside a `where`.

**Comment by rodrigopedra** [comment]
Well, the `addSelect` gets lost because the nested where creates a new query to pass inside the the `where` closure and them merge only the `where` bindings to the outer query.

You can see it here:

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Query/Builder.php#L1333-L1355

So I am afraid that, unfortunately, you won't be able to add conditional select fields inside a `where` closure.

As an alternative, you can consider using `when` to switch between dynamic parts. In the case of the other conditions that should be grouped they would need their own `where` closure.

~~~php
$query = \App\Publisher::select('providers.*');

$query->when($someCondition, function ($query) {
    $query->addSelect(...);
});

$query->when($otherCondition, function ($query) {
    $query->where(function ($query) {
        $query->where(...);
        $query->orWhere(...);
        $query->orWhere(...);
    });
});

// ...
~~~

**Comment by denitsa-cm** [comment]
@rodrigopedra Yes, I guess I'll have to do that. Thanks again!
