### ISSUE TITLE
[7.x] config:cache command unexpectedly loads .env.production other than .env

### ISSUE THREAD

**Issue by KNJ** [laravel/framework#31855]
- Laravel Version: 7.0.8
- PHP Version: 7.4.0

### Description:

If `APP_ENV=production` is in `.env`,  `artisan config:cache` command will create cache from both `.env.production` and `.env`, that is not the same behavior as in 6.x. If the command is executed again, cache will be created from `.env` alone.

### Steps To Reproduce:

Prepare .env file:

```
APP_NAME=Laravel
APP_ENV=production
APP_KEY=base64:NRQuuQKj+IIqc9nH/FclXCXY0qka97A6bw5Ac51lVdU=
APP_DEBUG=true
APP_URL=http://localhost
```

And .env.production file:

```
APP_KEY=
APP_URL=http://example.com
```

Execute config:cache

```
php artisan config:cache
```

See bootstrap/cache/config.php (UNEXPECTED):

```php
<?php return array (
  'app' =>
  array (
    'name' => 'Laravel',
    'env' => 'production',
    'debug' => true,
    'url' => 'http://example.com',
    'asset_url' => NULL,
    'timezone' => 'UTC',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'faker_locale' => 'en_US',
    'key' => '',
    'cipher' => 'AES-256-CBC',
    'providers' =>
```

Command again and then (CORRECT, same as in 6.x) :

```php
<?php return array (
  'app' =>
  array (
    'name' => 'Laravel',
    'env' => 'production',
    'debug' => true,
    'url' => 'http://localhost',
    'asset_url' => NULL,
    'timezone' => 'UTC',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'faker_locale' => 'en_US',
    'key' => 'base64:NRQuuQKj+IIqc9nH/FclXCXY0qka97A6bw5Ac51lVdU=',
    'cipher' => 'AES-256-CBC',
    'providers' =>
```

**Comment by GrahamCampbell** [comment]
Looking at the code, I don't think this behaviour has changed since 6.x? It always will have loaded the env.production file?

**Comment by GrahamCampbell** [comment]
Comparing the 6.x env code to 7.x: https://www.diffchecker.com/Ov6hK3QA, there are no changes.

**Comment by KNJ** [comment]
`php artisan config:clear && php artisan config:cache` is always NG.
`php artisan config:clear && php artisan config:cache && php artisan config:cache` is always OK.

That's odd behavior. I'll try to trace the code including phpdotenv.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by ejunker** [comment]
@KNJ I also ran into this issue with having a .env and .env.production file and `APP_KEY` being empty the first time I run `php artisan config:cache` Did you find any more information on why it is happening? I wonder if it has something to do with Illuminate\Foundation\Console\ConfigCacheCommand::getFreshConfiguration() and the way that it bootstraps the framework, maybe it is not calling DotEnv correctly.
