### ISSUE TITLE
Artisan not waiting for userinput

### ISSUE THREAD

**Issue by 43r04** [laravel/framework#31859]
- Laravel Version: 7.0.8
- PHP Version: 7.4.0
- Database Driver & Version: MySQL  Ver 15.1 Distrib 10.3.14-MariaDB
- Windows 10
- Apache 2.4.41 (WAMP 64 Bit)

### Description:
Hi, i got an error for own written commands.
The commands are NOT waiting for user-input, even on most simple commands. Each user-input gets aborted instantly. This error occurs on Windows-CMD, PowerShell and Cygwin CLI (no others tested).

### Steps To Reproduce:
To replicate this error i simply wrote a new command by running the 'php artisan make:command MyTest'-command.
This is my whole command i wrote for this scenario:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class MyTest extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'mytest:check';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'MyTest checks user-inputs';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->line("Inside test command");
        if($this->confirm("Do you wish to continue?")) {
            $this->line("Confirmed");
        } else {
            $this->line("Not confirmed");
        }
        exit();
    }
}
```
Now if i´m running my command through artisan i get the "Inside test command" and the prompt for the user input. But instead of waiting for my input i just get a message, that the userinput is "aborted" (see screenshot below).
![laravel_cli_aborts](https://user-images.githubusercontent.com/20698999/76215163-6adaa680-620e-11ea-953e-30c6a968aa61.png)

**Comment by ryangjchandler** [comment]
It looks like this is a problem with PHP itself, specifically 7.4.0 running on Windows. There was a bug report for some Symfony components which suggest upgrading to PHP 7.4.1 to fix the problem. 

If you need more info, see here: https://github.com/symfony/maker-bundle/issues/531

I think it's safe to close this issue now.

**Comment by 43r04** [comment]
@ryangjchandler Thank you, that fixed the problem.

Not only upgrading, also downgrading (to 7.3.12) worked for me.

Bye and greetings.
