### ISSUE TITLE
field name with underline cannot be validated normally

### ISSUE THREAD

**Issue by Jason23347** [laravel/framework#31862]
- Laravel Version: 5.8
- PHP Version: 7.2.24

### Description:
There was a field 'short_name'.
In the From Request Class, the rule was 'string'.
If the request data is x-www-form-urlencoded, it works.
However, if the request is like this
```shell
curl -d '{"short_name": "something"}' -H "Content-Type: application/json" $URI
```
the filed just desappear!
If add 'required' to rules, then "The short name field is required." is shown.

### Steps To Reproduce:
just add this to your form request
```json
'short_name' => 'required|string',
```
then make a request with content type of json.

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
