### ISSUE TITLE
Change font does not work in  Laravel notification markdown CSS file

### ISSUE THREAD

**Issue by amrasouli79** [laravel/framework#31866]
- Laravel Version: 7.0.0
- PHP Version: 7.3.10

### Description:
I trying to change notification markdown.
everything works correctly except font family. (in Gmail and also Telescope mail)
if everything works correctly except this mean the problem is from Laravel.
I tryed to import font from local path and also public path (https://example.com) to my css file(inside @font-face)
Also i tried to import thiese URLs with (base 64 encoing)
In my mail.config file this code has been added

```
    'markdown' => [
        'theme' => 'default.css',

        'paths' => [
            resource_path('views/vendor/mail'),
        ]
```

But still does not work 
### Steps To Reproduce:
Run php artisan vendor:publish --tag=laravel-mail as described in the documentation and change the generate files in resources\view\vendor\mail and try sending mails.As you will see if you change default.css inside html\themes directory font does not work

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
