### ISSUE TITLE
assertSoftDeleted not working properly

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#31881]
- Laravel Version: 7.0.8
- PHP Version: 7.4.1
- Database Driver & Version: mysql 8

### Description:

After upgrading to Laravel 7 some of my tests related to `assertSoftDeleted` fails, The `deleted_at` column filled but i dont know what is the problem

```
Failed asserting that any soft deleted row in the table [threads] matches the attributes {"id":1,"name":"Alexis Blick","hits":"0","deleted_at":"2020-03-10T10:04:14.000000Z","created_at":"2020-03-10T10:04:14.000000Z","updated_at":"2020-03-10T10:04:14.000000Z"}.

Found: [
    {
        "id": "1",
        "name": "Alexis Blick",
        "hits": "0",
        "deleted_at": "2020-03-10 10:04:14",
        "created_at": "2020-03-10 10:04:14",
        "updated_at": "2020-03-10 10:04:14"
    }
].
```

```php
/** @test */
public function soft_delete_threads()
{
    $this->signInAdmin();

    $thread = create(Thread::class);

    $this->delete(route('thread.destroy', $thread));

    $this->assertSoftDeleted('threads', $thread->fresh()->toArray());

}
```

**Comment by sergiy-petrov** [comment]
@foremtehan I believe it's because Laravel 7 uses a new date serialization format when using the toArray or toJson method on Eloquent models as mentioned in upgrade guide
https://laravel.com/docs/7.x/upgrade#date-serialization

You could try something like
$this->assertSoftDeleted('threads', ['id => $thread->id]);

**Comment by sergiy-petrov** [comment]
Also you could ovveride serializeDate  method in your model as also mentioned in upgrade guide
