### ISSUE TITLE
Scheduler depends on globally available illuminate/foundation helpers

### ISSUE THREAD

**Issue by nmokkenstorm** [laravel/framework#31891]
- Laravel Version: 5.4.0 - 7.0.4
- PHP Version: 7.3.7, not relevant
- Database Driver & Version: n/a

### Description:
At the moment the Scheduler component within `illuminate/console` depends on globally available `dispatch` and `dispatch_now` functions, this introduces an undocumented dependency between the Laravel framework as a whole, and the `illuminate/console` component. I'm willing to look into fixing this, because there has been a push in the past to make stuff less dependent on `illuminate/foundation`, but I'm raising an issue here first because most of my efforts towards these kinds of PRs have been met with lukewarm response so far.

The dependency on these helpers was introduced in the 5.4.0 branch, which is why I included it in the version range.

### Steps To Reproduce:
- `composer require illuminate/console`
- Create a Schedule, use it to dispatch stuff on crontab
- observe undefined function errors

**Comment by GrahamCampbell** [comment]
Thanks for the report. I've prepared a PR to address this.

**Comment by GrahamCampbell** [comment]
This issue would have auto-closed when I do the 6.x -> 7.x branch merge. ;)
