### ISSUE TITLE
"symfony/translation"-bug returned when upgrading from 4.3.8 to v5 for Laravel 7

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#31893]
- Laravel Version: v7.1.0
- PHP Version: 7.2.24

### Description:
```
2020/03/10 19:52:04 [error] 13590#13590: *18393 FastCGI sent in stderr: "PHP message: PHP Warning:  include(/home/forge/my.app/vendor/composer/../symfony/translation/TranslatorInterface.php): failed to open stream: No such file or directory in /home/forge/my.app/vendor/composer/ClassLoader.php on line 444
PHP message: PHP Warning:  include(): Failed opening '/home/forge/my.app/vendor/composer/../symfony/translation/TranslatorInterface.php' for inclusion (include_path='.:/usr/share/php') in /home/forge/my.app/vendor/composer/ClassLoader.php on line 444
PHP message: PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set. in /home/forge/my.app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258
```

```
2020/03/10 20:44:24 [error] 12467#12467: *18679 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) in /home/forge/my.app/vendor/nesbot/carbon/src/Carbon/Translator.php on line 18
PHP message: PHP Fatal error:  Uncaught ErrorException: Declaration of Illuminate\Http\Response::setContent($content) should be compatible with Symfony\Component\HttpFoundation\Response::setContent(?string $content) in /home/forge/my.app/vendor/laravel/framework/src/Illuminate/Http/Response.php:14
```

### Steps To Reproduce:
Upgrade an existing project to the latest version of Laravel v7.1.0. Install this on a server with PHP Version: 7.2.24. 

I found out that it is because of the package ```"symfony/translation"```. For Laravel 6 you can fix this by setting the package to version **4.3.8**. This is not an option for Laravel 7, because that uses version 5 of that package. 

It should work with my PHP-version, because my composer.lock tells me that this is the highest required PHP-version: ```"php": "^7.2.5",```. I have **7.2.24** which is higher as **7.2.5**.

**Comment by themsaid** [comment]
Laravel doesn't require `symfony/translation` anywhere. You'll need to debug your app or ask for the forums for help.

**Comment by Jaspur** [comment]
@themsaid are you sure? because I have it also in a clean install a couple of times in the composer.lock file. it's part of the symfony stack Laravel uses, but in a incorrect way. see: https://gist.github.com/Jaspur/19b5f69fcef32ae21a023e46d52eab3b

**Comment by themsaid** [comment]
How can I replicate the issue given that I've upgraded and helped upgrading multiple laravel apps to 7 already with no issues? I think it's a package you are using.

**Comment by Jaspur** [comment]
See my updated comment. I also occurs on a clean install on my server. Installed directly via Forge from the Laravel Github repo itself.

**Comment by GrahamCampbell** [comment]
Probably due to global dependency conflicts.

**Comment by Jaspur** [comment]
@GrahamCampbell is occurs on a clean Laravel 7 install too..

**Comment by themsaid** [comment]
I still can't replicate on a Forge server with a fresh install ¯\_(ツ)_/¯

**Comment by Jaspur** [comment]
@themsaid using ```PHP 7.2.24-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:28:51) ( NTS )``` ?

**Comment by rimace** [comment]
@Jaspur Is the PHP version important? Does it work for you with 7.3?

**Comment by Jaspur** [comment]
That is where the server runs on where the bug occurs. And it is a bug, because the minimum requirement is PHP 7.2.5. Version of the server is higher as that.

**Comment by themsaid** [comment]
I'll re-open even though I can't replicate the issue. Maybe someone else can replicate?

**Comment by rodrigopedra** [comment]
`nesbot/carbon` requires `symfony/translation` which requires `symfony/translation-contracts`

I tested a clean install on a machine running php 7.2.28 and didn't have any issues, can you try updating your server to php 7.2.28

If that fixes the issue we may try updating the minimum requirement to that version.

Have in mind I just ran a clean install, navigated to home (using valet, so using php-fpm) and ran `php artisan` to check for installation. I don't know if that contract was ever touched to trigger the error, let me know if there is a more complete test I can run to test the issue.

---

Know most of you know this, but for completeness this is how I find the dependency:

~~~bash
$ php --version
PHP 7.2.28-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:25) ( NTS )
$ laravel new laravel
$ cd laravel
$ php artisan --version
Laravel Framework 7.1.0
$ composer why symfony/translation-contracts
symfony/translation  v5.0.5  requires  symfony/translation-contracts (^2) 
$ composer why symfony/translation
nesbot/carbon  2.31.0  requires  symfony/translation (^3.4 || ^4.0 || ^5.0)
$ composer why nesbot/carbon
laravel/framework  v7.1.0  requires  nesbot/carbon (^2.17)
~~~

If there is a clever way to this, please let me know

**Comment by Jaspur** [comment]
And Carbon is a dependency of L7.

A clean install on the server results in this error:
```
2020/03/11 11:57:47 [error] 29665#29665: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale) in /home/forge/laravel-7.my.app/vendor/nesbot/carbon/src/Carbon/Translator.php on line 18
PHP message: PHP Fatal error:  Uncaught ErrorException: Declaration of Illuminate\Http\Response::setContent($content) should be compatible with Symfony\Component\HttpFoundation\Response::setContent(?string $content) in /home/forge/laravel-7.my.app/vendor/laravel/framework/src/Illuminate/Http/Response.php:14
Stack trace:
#0 /home/forge/laravel-7.my.app/vendor/laravel/framework/src/Illuminate/Http/Response.php(14): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', '/home/forge/lar...', 14, Array)
#1 /home/forge/laravel-7.my.app/vendor/composer/ClassLoader.php(444): include('/home/forge/lar...')
#2 /home/forge/laravel-7.my.app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/forge/lar...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Http...')
#4 /home/forge/laravel-7.my.app/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): spl_autoload_call(" while reading response header from upstream, client: 213.124.78.202, server: laravel-7.my.app, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "laravel-7.my.app", referrer: "https://forge.laravel.com/servers/117933/sites/981381"
```
Actually there is a white screen of death visible and is the error above shown in the nginx error log.

**Comment by rodrigopedra** [comment]
Well, as 7.2.28 is the latest 7.2 version from the PPA Laravel Forge installs on every server you have two paths:

1 - Through Forge UI
- Navigate to your Forge server page (from the servers dropdown, not the sites)
- Select PHP on the left bar
- Click a button labeled "Upgrade Current Version To Latest Patch Release"

2 - Through SSH
- SSH to your server
- Run:
    ```bash
    $ sudo apt update
    $ sudo apt upgrade
    ```

Note that command might upgrade other packages too. Also you will need your `sudo` password to run them.

**Comment by Jaspur** [comment]
Ah, I didn't knew that specific version was the latest one ;-) I upgraded to that version and now it all works!

**Comment by GrahamCampbell** [comment]
This happens when your actual php-fpm version is 7.0 or 7.1.

**Comment by GrahamCampbell** [comment]
Evidence: https://3v4l.org/oKG2J.

**Comment by Jaspur** [comment]
Hmm, I did a check before upgrading php to the latest version and it had 7.2 fpm in the nginx config.

**Comment by GrahamCampbell** [comment]
It is impossible for this error to occur on PHP 7.2 or higher.

**Comment by larryx64** [comment]
> Probably due to global dependency conflicts.

That was it for me.

Laravel Version: 7.1.1
PHP Version: 7.3.15

Check your global composer file (located at ~/.composer on Mac, not sure for the other OS) and make sure there's not an old Carbon version in there.

Thanks @GrahamCampbell

**Comment by adnandogar** [comment]
At least laravel team should manage this issue permanently,
Even With fresh installation on remote server this is generation:
Declaration of Carbon\Translator::setLocale($locale) must be compatible with Symfony\Contracts\Translation\LocaleAwareInterface::setLocale(string $locale)

tried many ways:

My local machine using php 7.3.19
and remote server: php7.3.21

tried with all ways to add
transport and contractors but no luck,
really a painful action to install laravel7

locally this is working but the same thing is on live server.
Kindly get me fix out this.

**Comment by domissssssss** [comment]
> This happens when your actual php-fpm version is 7.0 or 7.1.

It's also happening on 7.3

I am upgrading laravel from 5.5 to 8 and till 7th version I had to use `"symfony/translation-contracts": "^1.1.6"` in composer, since laravel 7 symfony 5 is needed thus everything breaks.

Always used carbon 1, upgraded to carbon 2, but this doesn't seem to be an issue, when removed still I get 500 error.

When upgrading translation-contracts to 2 composer update works but I get 500 error. If downgraded to 1.1.6 composer update runs for a long time and then I get issues with Symfony 5

**Comment by domissssssss** [comment]
> > This happens when your actual php-fpm version is 7.0 or 7.1.
> 
> It's also happening on 7.3
> 
> I am upgrading laravel from 5.5 to 8 and till 7th version I had to use `"symfony/translation-contracts": "^1.1.6"` in composer, since laravel 7 symfony 5 is needed thus everything breaks.
> 
> Always used carbon 1, upgraded to carbon 2, but this doesn't seem to be an issue, when removed still I get 500 error.
> 
> When upgrading translation-contracts to 2 composer update works but I get 500 error. If downgraded to 1.1.6 composer update runs for a long time and then I get issues with Symfony 5

Turns out I had issue with php version. When I types php -v via vagrant ssh I would get 7.3. but I actually had to put php: 7.3 in vagrant -> Homestead.yaml 

`
---
ip: "192.168.10.10"

memory: 8192
cpus: 2
provider: virtualbox
mariadb: true
elasticsearch: 6

folders:
    - map: ~/Projects
      to: /home/vagrant/code
      type: "nfs"
      mount_opts: ['nolock,vers=3,udp,noatime,actimeo=1']

sites:
      to: /home/vagrant/code/jetcamps_website/public
      php: "7.2"
`
