### ISSUE TITLE
Blade Components do not like alphanumeric character hugs

### ISSUE THREAD

**Issue by Tickthokk** [laravel/framework#31892]
- Laravel Version: 7.0.8
- PHP Version: 7.4.3
- Database Driver & Version:

### Description & Steps To Reproduce:

When closing a blade component tag, and the very next character is alphanumeric, a `ViewException` is thrown. Examples 1-4 work fine, however examples 5 & 6 error. The existence of example 3 makes me think this is a bug.

```
<!-- components/component.blade.php -->
{{-- /resources/views/components/component.blade.php --}}
<component>Stuff</component>

<!-- 1.blade.php -->
<x-component></x-component> Words

<!-- 2.blade.php -->
<x-component/> Words

<!-- 3.blade.php -->
<x-component></x-component><span></span>Words

<!-- 4.blade.php -->
<x-component></x-component>{{ '' }}Words

<!-- 5.blade.php -->
<x-component/>Words

<!-- 6.blade.php -->
<x-component></x-component>Words
```

If you include words before it, it outputs a space. I even compressed the component to one line (with no EOF line) to be sure.

```
<!-- components/component.blade.php -->
{{-- /resources/views/components/component.blade.php --}}<component>COMPONENT</component>

<!-- 7.blade.php -->
Hello<x-component/> Goodbye
```

When I view source (note the unintended space after Hello).

```
Hello <component>COMPONENT</component> Goodbye
```

---

On a lesser note, other blade tags have a similar spacing issue. I've noticed it for a while, and its easy enough to work around, but figured I'd at least document it now since its acting a lot like the other issue:

```
<!-- 1.blade.php -->
@if (true)Words @endif MoreWords

<!-- 2.blade.php -->
<span>A</span>@if (true)<span>B</span>@endif<span>C</span>

<!-- 3.blade.php -->
@if (true)Words@endif MoreWords

<!-- 4.blade.php -->
@if (true)Words @endifMoreWords

<!-- 5.blade.php -->
@if (true)Words@endifMoreWords

<!-- 6.blade.php -->
BeforeWords@if (true)Words @endif MoreWords
```

Only scenario 1 & 2 work; 3-6 throw a `ViewException`. Example 6 differs from the Component issue noted above. Admittedly, inline logic like this is gross, but I've had small/easily-avoided use cases in the past.

**Comment by driesvints** [comment]
Can you try to upgrade to the newest version and see if any bug is solved? There have been some bug fixes in the last couple of days.

**Comment by Tickthokk** [comment]
I upgraded to v7.1.3, and the errors still persist.

For completeness, here's the error of example 5 above (`<x-component/>Words`).

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) (View: /srv/www/[redacted]/resources/views/test.blade.php)
```

Example 7 (`Hello<x-component/> Goodbye`) still contains the space and I also re-checked the final 6 `@if` examples and they're all still throwing exceptions the same way.

**Comment by driesvints** [comment]
Thanks. I'll elevate this to a bug. If you can PR a fix that'd be great.

**Comment by driesvints** [comment]
@Tickthokk good spot really. Sent in a fix for this: https://github.com/laravel/framework/pull/32005
