### ISSUE TITLE
Laravel forces to have customizing keys with scoping

### ISSUE THREAD

**Issue by JenabKhaan** [laravel/framework#31906]
- Laravel Version: 7.0.x
- PHP Version: 7.2.24
- Database Driver & Version: not related

### Description:
When using custom keys Laravel forces us with scoping, for example, I have a route to getting a country and a post, but I can't get that using slug key because it doesn't have a relation with country, and in this case, I want to handle scope myself and I don't need implicitly scope binding, but I get an error (`Call to undefined method App\Country::posts()
`).
I know it isn't a common problem but I think we need a way to turn the implicitly scope binding off.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
