### ISSUE TITLE
Validation unique rule with ignore, integer turns into string

### ISSUE THREAD

**Issue by hassanzohdy** [laravel/framework#31902]
- Laravel Version: >= 6
- PHP Version: >= 7.2
- Database MongoDB & Any Version:

### Description:
As MongoDB database is case sensitive to the stored types, the `unique` validation rule fails with the `ignore` method, as it casts the given `id` into strings everytime.

### Steps To Reproduce:
Try the following:

`Rule::unique('some_table')->ignore((int) $id, 'id')`

Always give the error: 'name already exists'.

After some digging, this happens because of the `stripslashes` function that is being called in `Illuminate\Validation\Concerns\ValidatesAttributes` trait, here is the code block:

```php
            if (! is_null($id)) {
                $id = stripslashes($id);
            }
``` 

# Fix

Just add a type check for the value of $id, for example:

```php

            if (! is_null($id) && is_string($id)) {
                $id = stripslashes($id);
            }
```

This would fix it as it will not convert any `integer` | `boolean` values into `strings`
.

**Comment by hassanzohdy** [comment]
I made a PR regarding the issue #31904

**Comment by driesvints** [comment]
MongoDB is unfortunately not supported sorry.
