### ISSUE TITLE
LazyCollection groupBy not working as intended

### ISSUE THREAD

**Issue by itsursujit** [laravel/framework#31912]
- Laravel Version: 6.18.0
- PHP Version: 7.3

using `groupBy` on LazyCollection is returning `Collection` instead of `LazyCollection`

I tried to use following code:

```
// ContactHelper.php
public static function getContacts($file, $listId, $defaultPrefix = null)
    {
        return LazyCollection::make(function() use ($file, $listId, $defaultPrefix) {
            $f = fopen($file, 'r');

            // read each line of the file without loading the whole file to memory
            while ($line = fgets($f))
            {
                $row = explode(",", $line);

                if (trim(urlencode(strtolower(trim($row[0]))), '%EF%BB%BF') == "phone" || empty(trim($row[0])))
                {
                    continue;
                }
                yield [
                    'phone'     => !empty($row[0]) ? handleInvalidStrings(trim($row[0])) : '',
                    'firstname' => !empty($row[1]) ? handleInvalidStrings(trim($row[1])) : '',
                    'lastname'  => !empty($row[2]) ? handleInvalidStrings(trim($row[2])) : '',
                    'email'     => !empty($row[3]) ? handleInvalidStrings(trim($row[3])) : '',
                    'custom1'   => !empty($row[4]) ? handleInvalidStrings(trim($row[4])) : '',
                    'custom2'   => !empty($row[5]) ? handleInvalidStrings(trim($row[5])) : '',
                    'list_id'   => $listId,
                ];
            }
        });
    }

$contacts = \App\Helpers\ContactHelper::getContacts(public_path('/file_250k.csv'), 113); 
// LazyCollection
    $test = $contacts->groupBy('phone')->chunk(20)->each(function ($item, $key) {
        dd($item); // LazyCollection with Collection inside
    });
```

Result:
https://www.dropbox.com/s/j17x4qh96l0q7jc/Screenshot%202020-03-10%2023.15.08.png?dl=0

**Comment by driesvints** [comment]
@JosephSilber is this correct?

**Comment by JosephSilber** [comment]
The inner values of each group are a `Collection`. Correct.

**Comment by itsursujit** [comment]
@JosephSilber If the inner values of each group is a `Collection` and it uses the entire memory to process/fetch the data, what is the use of LazyCollection?

**Comment by JosephSilber** [comment]
Some operations, such as sorting and grouping (which is just another form of bucket sort) cannot be done lazily. That's just the nature of these operations.

In these cases, there indeed is not much benefit to using a lazy collection.<sup>1</sup>

You only gain back the laziness advantage as you chain methods onto the result.

---

<sup>1</sup> Even though the actual sorting and grouping cannot be done lazily, they are still deferred to when you actually start enumerating the values. If no values are ever enumerated, nothing is ever pulled from the source. In that sense they're still somewhat lazy.
