### ISSUE TITLE
HTTP client overrides multiple occurrences of same query parameter

### ISSUE THREAD

**Issue by devfrey** [laravel/framework#31918]
- Laravel Version: 7.1.0
- PHP Version: 7.4.3
- Database Driver & Version: irrelevant

### Description:
I have a use case where I need to query an endpoint with multiple occurrences of the same query parameter. Guzzle supports this just fine if the query parameters are passed in the URL. Laravel's HTTP client, however, always extracts the query parameters from the URL and then passes them to Guzzle as an array. This results in the last occurrence overwriting all prior occurrences.

The endpoint in question is a Lucene/Solr instance that allows the [`fq` query parameter](https://lucene.apache.org/solr/guide/8_4/common-query-parameters.html#fq-filter-query-parameter) to be specified multiple times. As far as I'm aware there's no standard regarding these query parameters so this should be a valid use case.

Unfortunately there's no way around this problem. Even with the bracket syntax (to indicate a query parameter with multiple values) Guzzle then turns it into a URL that is not supported by Solr.

### Steps To Reproduce:
Make a request to an endpoint with multiple occurrences of the same query parameter and you'll see the last occurrence overwrites all previous ones:
```php
Http::get('https://example.com/?fq=hello&fq=world');
// actual request goes to https://example.com/?fq=world
```

**Comment by donnysim** [comment]
I dont really know how you will deal with array keys not overriding each other, but for this problem you could try using `fq=+hello +world`.

**Comment by devfrey** [comment]
> I dont really know how you will deal with array keys not overriding each other, but for this problem you could try using `fq=+hello +world`.

I simplified the example in my first post. My actual use case is a bit more complicated and your suggestion – unfortunately – won't work for me.

**Comment by driesvints** [comment]
This was fixed I think in the latest release: https://github.com/laravel/framework/pull/31858

Can you try with the very latest patch version?

**Comment by devfrey** [comment]
Thanks for responding @driesvints. Unfortunately, that fix is unrelated. I've been able to create a fix, but I haven't yet succeeded in adding a proper test. I'll PR my fix to get some feedback and hopefully someone can assist in writing a test.

**Comment by devfrey** [comment]
Thanks for responding @driesvints, but unfortunately that fix is unrelated. My use case is impossible with the current implementation, because `PendingRequest` calls `parseQueryParams()`. It then sets the 'query' option on the Guzzle request, which results in Guzzle ignoring any query parameters in the URL.

A fix would be to remove the call to `parseQueryParams()` entirely, but I'm not sure how breaking that would be.

**Comment by driesvints** [comment]
Would appreciate a Pr if you could send one in. Thanks!

**Comment by driesvints** [comment]
Fixed and will be in today's release.
