### ISSUE TITLE
[7.x] artisan test not respecting disabling stop on failure

### ISSUE THREAD

**Issue by tobyryuk** [laravel/framework#31914]
- Laravel Version: 7.1.0
- PHP Version: 7.4.1
- Database Driver & Version: N/A

### Description:
Running a lot of tests where one of the first tests fail, execution stops of all following test no matter what. We read that it says that the command `will automatically stop on the first test failure` which doesn't make sense since you can't seem to turn it off and if you'd want to turn it on, phpunit already has a flag for it?

### Steps To Reproduce:
Add tests to a Laravel 7 project with failing tests. Potentially add `stopOnFailure="false"` to see no further effect.

**Comment by driesvints** [comment]
Please open an issue on https://github.com/nunomaduro/collision

**Comment by baldarn** [comment]
this seems to be not supported jet

https://github.com/nunomaduro/collision/issues/37#issuecomment-621159598
