### ISSUE TITLE
Http client adds trailing slash when $url is empty string.

### ISSUE THREAD

**Issue by ttrig** [laravel/framework#31913]
- Laravel Version: 7
- PHP Version: 7

### Description:
This might be by design and not a bug, but when i replaced my guzzle client with the new http client in Laravel 7, it adds a trailing slash in `src/Illuminate/Http/Client/PendingRequest.php:457`.
The reason for this is that i define the full uri with `Http::baseUrl('http://foo/bar')` and then call e.g. `$http->post('', [...])`.

Expected URL: `http://foo/bar`
Actual URL: `http://foo/bar/`

### Steps To Reproduce:
```php
Http::baseUrl('http://foo/bar')->post('', [...]) // => http://foo/bar/
```

**Comment by ryangjchandler** [comment]
Is this causing problems with your request. I can only imagine it being a problem if the server the request is being made to doesn't match trailing slashes.

**Comment by ttrig** [comment]
Yes, because of [.htaccess:12](https://github.com/laravel/laravel/blob/166abfa35c535f4572d5971a99aec45cc8c63ff6/public/.htaccess#L12) i get a redirect and lose the post data.

**Comment by driesvints** [comment]
This doesn't seems to be related to Laravel.

**Comment by ben182** [comment]
I think it **is** related to Laravel. A trailing slash is always added between base url and the actual url. I discovered this behavior when trying to use the base url together with a paramter and it always put a trailing slash in the middle. I think it makes sense to check if a trailing slash is needed between these two parts (like "http://httpbin.org" and "ip") BUT not for ("http://httpbin.org/?param=" and "1" - or the example from above).
https://github.com/laravel/framework/blob/71844a39bd63c1319bb12d81d1d9212aed0b0077/src/Illuminate/Http/Client/PendingRequest.php#L551

**Comment by joereynolds** [comment]
This still exists in Laravel 9.x as an FYI.

**Comment by richard015ar** [comment]
Having the same issue on Laravel 9.x. Why is it closed? It seems to be a Laravel issue.

**Comment by richard015ar** [comment]
FYI, everyone, it is an issue from Guzzle: https://github.com/guzzle/guzzle/issues/770
I fixed it using a different base URL. 
Following the example of the main post, what it worked for me was:
```php
Http::baseUrl('http://foo')->post('bar', [...]) // => http://foo/bar
```
It is not ideal, but works.
