### ISSUE TITLE
Laravel mail not working with custom smtp settings

### ISSUE THREAD

**Issue by khakanali** [laravel/framework#31910]
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:
I'm trying to setup custom smtp settings. I've setup smtp server  on shared hosting. Laravel mail function return nothing. Then i've tested it by using SwiftMailer. Swiftmailer return the success message but didn't get the email in the inbox. 

This SMTP server working fine with PHPMailer.And received emails in the inbox without any problem

**Comment by ryangjchandler** [comment]
Please try upgrading to Laravel 6.x or greater and see if the problem still persists since 5.8 is no longer being supported and 6.x is the LTS release.

**Comment by khakanali** [comment]
@ryangjchandler Thank you. I tried this.but no luck :(

**Comment by driesvints** [comment]
Are you using the new `MAIL_MAILER` env variable? https://github.com/laravel/laravel/blob/develop/config/mail.php#L16

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
