### ISSUE TITLE
\Log::debug($text); - Is breaking the Log functionality when the $text is too big.

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#31921]
- Laravel Version: 6.4.#
- PHP Version: 7.2.#
- Database Driver & Version:

### Description:
I was debugging and needed to get some text printed out to my log file. Like that

    \Log::debug('abc');
    \Log::debug($longText);

but it does not print any thing. Not only this line was not working, but all the others Log calls was not adding data to the file too. In the example above, the "abc" was not getting to the log file. I have noticed, that the text that I was trying to log was too big.
In fact it was 53410 symbols. But it is not huge, right? 
I tried to run it from controller and from the unit test - same result, it was not working. I tried upgrading laravel to 6.9 - it did not help, the problem persisted.

### Steps To Reproduce:

\Log::debug('abc');
 $text = '11...'; // make it 53410 symbols
\Log::debug($text);

**Comment by driesvints** [comment]
Just trim the text before you send it to the logger.
