### ISSUE TITLE
Middleware [cache.headers] does not work on file responses

### ISSUE THREAD

**Issue by obby-xiang** [laravel/framework#31922]
- Laravel Version: 7.x
- PHP Version: 7.4.1
- Database Driver & Version:null

### Description:
There is no cache handler for file responses in middleware `\Illuminate\Http\Middleware\SetCacheHeaders`.

### Steps To Reproduce:
null

**Comment by dwightwatson** [comment]
The cache headers are removed when a session is present - like in the default `web` stack. They will work as expected when there is no session present.

**Comment by obby-xiang** [comment]
Function `handle` in `\Illuminate\Http\Middleware\SetCacheHeaders` only handles responses with not empty content. It does not handle file responses.

**Comment by driesvints** [comment]
Feel free to send in a PR if you think this should be supported 👍
