### ISSUE TITLE
WRONG Database Connection on running phpunit tests

### ISSUE THREAD

**Issue by masterwto** [laravel/framework#31924]
- Laravel Version: 7.1.0
- PHP Version: 7.3.4
- Database Driver & Version: mysql

### Description:
This is perhaps a problem with phpunit intergration of laravel framework.

I have `DB_CONNECTION=mysql` and the connection works OK because `php artisan ide-helper:models` generates the right `_ide_helper_models.php` file with right model properties.
The default config/database.php file is never changed.

### Steps To Reproduce:
1. `php artisan tinker` reacts like this:
```
>>> config('database.default')
==> "mysql"
>>> getenv('DB_CONNECTION')
==> "mysql"
```

2. Make a phpunit test: `php artisan make:test DefaultDatabaseConnectionTest`

```php
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DefaultDatabaseConnectionTest extends TestCase
{
    public function testEnvDatabaseConfigurationIsMysql()
    {
        $this->assertSame('mysql', getenv('DB_CONNECTION'));
    }

    public function testDefaultDatabaseIsSqlite()
    {
        $this->assertSame('sqlite', config('database.default'));
    }
}

```

The output looks like:
```
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

.F..                                                                4 / 4 (100%)

Time: 2.43 seconds, Memory: 18.00 MB

There was 1 failure:

1) Tests\Feature\DefaultDatabaseConnectionTest::testEnvDatabaseConfigurationIsMysql
Failed asserting that false is identical to 'mysql'.

D:\Projects\GateWayTester\tests\Feature\DefaultDatabaseConnectionTest.php:13

FAILURES!
Tests: 4, Assertions: 4, Failures: 1.

```

Seems `CreatesApplication` trait did not read the `.env` config file.

**Comment by SjorsO** [comment]
[The `phpunit.xml` in the framework skeleton](https://github.com/laravel/laravel/blob/master/phpunit.xml#L23) overrides the `DB_CONNECTION` value. 

Your tests will use the database configured in your `.env` If you remove these two lines:
```
<server name="DB_CONNECTION" value="sqlite"/>
<server name="DB_DATABASE" value=":memory:"/>
```

**Comment by masterwto** [comment]
@SjorsO It works! Thank you so much!
