### ISSUE TITLE
[7.x] BindingResolutionException was handled twice

### ISSUE THREAD

**Issue by linhntaim** [laravel/framework#31944]
- Laravel Version: 7.1.1
- PHP Version: 7.3

### Description:

When setting none-existed middleware(s) to route(s), a BindingResolutionException will occur and the error page of the exception will be rendered twice.

### Steps To Reproduce:

1. Setting a none-existed middleware to a route:

```php
Route::group(['middleware' => 'any_none_existed_middleware'], function() {
	Route::get('/', function () {
		return view('welcome');
	});
});
```

2. Accessing URL of the root path (by simply running `php artisan serve` and accessing `http://127.0.0.1:8000/` on browser); then, an error page will be shown with duplicated content.

![image](https://user-images.githubusercontent.com/6326961/76560288-6d215700-64d3-11ea-88a7-bf1b96f258ab.png)

In the picture above showing the error page in view-source mode, the `html` tag is duplicated because the content of the error page is rendered twice.

**Comment by driesvints** [comment]
Thanks for reporting. I think the message itself is still pretty straightforward. Feel free to send in a PR if you can solve this more cleanly.
