### ISSUE TITLE
Issue with Policy not being triggered properly?

### ISSUE THREAD

**Issue by arthur798** [laravel/framework#31949]
- Laravel Version: 6.18.§
- PHP Version: 7.4

### Description:

So I have a route model binding like that:
```
            Route::model('questionnaireAttachment', \App\Models\QuestionnaireAttachment::class);
```

I also have policy registered in AuthServiceProvider.php:
```
            QuestionnaireAttachment::class => QuestionnaireAttachmentPolicy::class,
```

and the route I have is like this:
```
                Route::get('questionnaire/attachments/{questionnaireAttachment}', [AttachmentController::class, 'getAttachments'])->name('questionnaireAttachmentRetrieve')->middleware('can:view,questionnaireAttachment');
```

the policy has `return false;` in it so I know it fails however when I make the request to the endpoint, despite the return false; i still get to the controller and I get a valid 200 response

**Comment by staudenmeir** [comment]
Please post all the code necessary to reproduce this on a fresh installation of Laravel.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
