### ISSUE TITLE
[6.17.1] Offset error when trying to query a collection to retrieve a column in php 7.4

### ISSUE THREAD

**Issue by Adam-78** [laravel/framework#31941]
- Laravel Version: 6.17.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:

I have a collection as follows:
  
     $products = $this->productRepository->getByCompanyId(1)->get();
   

     Illuminate\Database\Eloquent\Collection {#856 ▼
         #items: array:1 [▼
           0 => App\OrderItemProduct {#824 ▼
             #table: "product"
             ...
             #attributes: array:3 [▼
                "available" => "5"
                "product_name" => "Product X"
                "product_id" => 1
             ]
             ....
           }
         ]
      }

I want to get the `available` value for a single record. I try the following which works if a record exists in the above collection:

     $available = $products->where('product_id','=', 1)->first()['available'];

However it throws an exception `Trying to access array offset on value of type null` if I try to retrieve the `available` value of a record that doesn't exist in the above collection e.g trying to get `available` value for product_id `17`:
   
    $available = $products->where('product_id','=', 17)->first()['available'];

Same error happens if you use the `value` method as follows and as documented https://laravel.com/docs/6.x/queries#retrieving-results

    `available = $products->where('product_id','=', 17)->value('available');

This happens when using php 7.4 - on php 7.2 both methods work fine.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Adam-78** [comment]
Hi,

I've already asked on stackoverflow. As per the post this is an issue with php 7.4 https://www.php.net/manual/en/migration74.incompatible.php
