### ISSUE TITLE
Error sending mail with queue (Mailable & ShouldQueue)

### ISSUE THREAD

**Issue by hulkur** [laravel/framework#31950]
- Laravel Version: 7.1.1
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:

Upgrading from Laravel 6.18.0

If Mailable implements ShouldQueue then sending it causes 

`Illuminate\Contracts\Container\BindingResolutionException : Target [Illuminate\Contracts\Mail\Factory] is not instantiable.`

If I remove ShouldQueue then mail is sent.
Tested it in tests and tinker with drivers: sendmail, log, array.

### Code snippets:

Mailable:
`class Invitation extends Mailable implements ShouldQueue`

sending:
`Mail::to($data['email'])->send(new Invitation($inviteCode, $data['email']));`

**Comment by driesvints** [comment]
Please share more code to reproduce the problem.

**Comment by driesvints** [comment]
There's also https://github.com/laravel/framework/pull/31809 which could be related

**Comment by v-stein** [comment]
Hello @hulkur,
Have you checked the configuration of your mailers?

Even thought it is said that Laravel 6's configuration is still supported, you may want to double check and update your configuration file to match what Laravel 7 expects. This is what fixed the issue for us.

**Comment by hulkur** [comment]
I dug too deep ...

It was a combination of new mailer configuration and overriding framework classes.
