### ISSUE TITLE
paginate method with default parameters have a SQL syntax error

### ISSUE THREAD

**Issue by MohammadNajjary** [laravel/framework#31953]
My stack is :
laravel 6.2 
php:7.2
mysql:5.7.24

i have paginate method in my repo :
```
    /**
     * @param int $page
     * @param int $per_page
     * @return LengthAwarePaginator
     */
    public function paginate(int $page = 1, int $per_page =1): LengthAwarePaginator
    {
        $per_page = intval($per_page) > 1 ? intval($per_page) : config('constants.PER_PAGE.DEFAULT');

        return $this->model->paginate($per_page, null, null, $page);
    } 
```
This is paginate API document:

`LengthAwarePaginator paginate(int $perPage = 15, array $columns = ['*'], string $pageName = 'page', int|null $page = null)`

if you use null for optional parameter like this :

` return $this->model->paginate($per_page, null, null, $page);
`
You will encounter the following error.
```
Illuminate\Database\QueryException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from `users` limit 10 offset 0' at line 1 (SQL: select from `users` limit 10 offset 0)
```
but after change parameter like below it works:
`  return $this->model->paginate($per_page, ['*'], null, $page);
`

**Comment by AegirLeet** [comment]
The second parameter `array $columns = ['*']` asks for an `array` (**not** `array|null`) and the third parameter `string $pageName = 'page'` asks for a `string` (**not** `string|null`), so `null` is not a valid value for either of those parameters. By passing `null`, you are overriding the default values (`['*']` and `'page'`). If you want to keep the default values, you need to pass them explicitly.

**Comment by MohammadNajjary** [comment]
You're right, but `null` in laravel 5.5 it's Ok, but this version have error.
