### ISSUE TITLE
Queue Timing delay is completely wrong

### ISSUE THREAD

**Issue by pollyrobin** [laravel/framework#31951]
- Laravel Version: v6.18.0
- PHP Version: 7.4.2
- Database Driver & Version: 8.0.13 - MySQL Community Server - GPL

### Description:
I made a simple queue system with the queue driver / connection as a db.
I am using laradock containers (if its even relevant)
I created a controller which on pageload send a simple email to mailhog and the code that does this is:
       
```
for($i = 1; $i <= 10; $i++) {
    SendTestEmail::dispatch()->delay(now()->addSeconds($i));
 }
```

When I visit the webpage to execute the task i already have artisan queue:work running.
If i look in the database the second i open the page i can see that it created the jobs in the database with a timestamp that looks valid:

id | queue | payload | attempts | reserved_at | available_at | created_at |  
-- | -- | -- | -- | -- | -- | -- | --
131 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109404 | 1584109403
132 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109405 | 1584109403
133 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109406 | 1584109403
134 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109407 | 1584109403
135 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109409 | 1584109404
136 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109410 | 1584109404
137 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109411 | 1584109404
138 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109412 | 1584109404
139 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109413 | 1584109404
140 | default | {"displayName":"App\\Jobs\\SendTestEmail"... | 0 | NULL | 1584109414 | 1584109404

However the output and speed of the jobs being processed is completely wrong:

[2020-03-13 14:23:25][131] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:26][131] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:26][132] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:26][132] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:26][133] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:26][133] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:29][134] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:29][134] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:29][135] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:29][135] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:33][136] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:33][136] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:33][137] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:33][137] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:33][138] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:33][138] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:33][139] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:33][139] Processed:  App\Jobs\SendTestEmail
[2020-03-13 14:23:37][140] Processing: App\Jobs\SendTestEmail
[2020-03-13 14:23:37][140] Processed:  App\Jobs\SendTestEmail

### Steps To Reproduce:

Create a controller with:
```
<?php

namespace App\Http\Controllers;
use App\Jobs\SendTestEmail;

class TestController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function testTestMail() {
        
        for($i = 1; $i <= 10; $i++) {
            SendTestEmail::dispatch()->delay(now()->addSeconds($i));
        }
    }
}
```

Create a job with:

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Mail;
use App\Mail\TestEmail;

class SendTestEmail implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $email = new TestEmail();
        Mail::to('test@test.com')->send($email);
    }
}
```

And create a simple email class

```
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class TestEmail extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('emails.test')->text('emails.test-plain');
    }
}
```

And .env: 
```
APP_NAME=laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=laravel
DB_PASSWORD=laravel

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**Comment by AegirLeet** [comment]
Not sure what exactly you think is wrong here. Delaying a job for, say, 10 seconds means it will be available for processing after 10 seconds. It doesn't guarantee the job will be executed exactly 10 seconds from now, since the queue could be blocked by other jobs or the worker could be in a "sleep" phase where it waits for new jobs.

The `queue:work` command has a `--sleep` option which controls how long the worker sleeps when it can't find any jobs. The default is 3 seconds and reducing this value (for example, `--sleep=0.1`) will tend to make the timing more accurate.

**Comment by pollyrobin** [comment]
Alright, I tried it with the --sleep=0.1 and it works perfectly.
Now it also makes sense as well why several jobs are executed in the same second because of this 3-second sleep.  

Thanks for the explanation!

**Comment by AegirLeet** [comment]
Just be aware that this will potentially execute one DB query every 0.1s.
