### ISSUE TITLE
TimestampTz in SQLite breaks with Query Builder's prepareBindings

### ISSUE THREAD

**Issue by danvim** [laravel/framework#31969]
- Laravel Version: 6.9
- PHP Version: 7.4
- Database Driver & Version: sqlite (actually, depending on "design rationale", it may have affected others as well)

### Description:

This issue is related to https://github.com/laravel/framework/issues/16356, relating to `Connection::prepareBindings()`

The problem arises here:

https://github.com/laravel/framework/blob/3a4ba41752327656702de1a30fc4cd48073f05ab/src/Illuminate/Database/Connection.php#L591-L607

This is the hard coded standard SQL date format, not overridden by either Postgres or SQLite classes.

https://github.com/laravel/framework/blob/514dff27a5cbb6225f37050d0c7fa2e71b064f44/src/Illuminate/Database/Grammar.php#L189-L197

In my unit testing environment, I used in memory sqlite for unit testing. (Postgres in development server does not have this issue)

If I have this model:

```php
class Test extends Model {
    protected $dateFormat = DateTime::ISO8601; // just for illustration. This does not work with Postgres
    // ...
}
```

At one point the following is called:

```php
Test::create([
    'show_at' => Carbon::now()
]);
```

This model instance has the following original attributes immediately afterwards:

```php
[
    'id' => 1,
    'show_at' => Carbon, // an attribute used in `create()`
    'created_at' => '2012-12-12T12:12:12+00:00',
    'updated_at' => '2012-12-12T12:12:12+00:00'
]
```

When we try `Test::find(1)` at this point, its original attributes are the following due to `$grammar->getDateFormat() // returns 'Y-m-d H:i:s'` in `prepareBindings()` (L600):

```php
[
    'id' => 1,
    'show_at' => '2012-12-12 12:12:12'
    'created_at' => '2012-12-12T12:12:12+00:00',
    'updated_at' => '2012-12-12T12:12:12+00:00'
]
```

**This should not have happened, as `toArray()` would fail with `Carbon::createFromFormat()` with this date format inconsistency.**

**Comment by driesvints** [comment]
Is this also a problem in the latest 6.x version?

**Comment by danvim** [comment]
> Is this also a problem in the latest 6.x version?

I believe so, I haven't tested, but from the master branch code that I've referenced, the issue is there.

**Comment by driesvints** [comment]
Don't have time for this myself atm unfortunately. Appreciating any help with this.

**Comment by staudenmeir** [comment]
You need to add `show_at` to the list of [date attributes](https://laravel.com/docs/6.x/eloquent-mutators#date-mutators):

```php
class Test extends Model
{
    protected $dates = ['show_at'];

    protected $dateFormat = DateTime::ISO8601;
}
```

**Comment by danvim** [comment]
@staudenmeir That wouldn't work. `$dateFormat` is not involved into deserializing `Carbon` instance in `Connection::prepareBindings()`. I only mocked minimum code on my original question for simplicity.

**Comment by staudenmeir** [comment]
It _does_ work because the date serialization happens in the model, not in the connection.

Don't dismiss a solution without even trying it.

**Comment by driesvints** [comment]
Please see the answer from Staudenmeir above. Thanks for helping!
