### ISSUE TITLE
reset password redirect url error

### ISSUE THREAD

**Issue by mowangjuanzi** [laravel/framework#31960]
- Laravel Version: 7.1.1
- PHP Version: 7.4.3
- Database Driver & Version: 8.0.19

### Description:

I changed `home` url 

```php
Route::get('/', 'HomeController@index')->name('home');
```

When I reset my password and click the button, I will jump to `/home`. Normally, I should jump to `/`

**Comment by devcircus** [comment]
You should be able to set the path to your home route using the HOME const in your RouteServiceProvider.

**Comment by mowangjuanzi** [comment]
but login action is ok? why reset password is not ok?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
