### ISSUE TITLE
A commented line in a Blade file outputs a blank line

### ISSUE THREAD

**Issue by Axieum** [laravel/framework#31963]
- Laravel Version: `6.16.0`
- PHP Version: `7.4.3`

### Description:
Having a commented line in a Blade file results in an empty line in the output file.

### Steps To Reproduce:
Create a blade file (e.g. `index.md.blade.php`) - we'll use Markdown as an example:
```blade
{{-- Page Header--}}
# Title
> A page description...

{{-- Output Contents --}}
{{-- Another comment --}}
## @lang('package::contents.title')
@each('package::content', $contents, 'content')
```

Rendering via
```php
$output = view('package::index')->with(['contents' => $content])->render();
//dd($output);
```

Results in a file with unnecessary blank lines (note top, and three blank lines between title and content, etc.) - again this is just a simple example, but lots of comments stacks up overtime:
```md

# Title
> A page description...



## Contents
### Content #1
This is content 1.

### Content #2
This is content 2.
```

**Comment by GrahamCampbell** [comment]
I don't think this is a bug. You have an actual newline after the commend has ended.

**Comment by Axieum** [comment]
> You have an actual newline after the commend has ended.

Yes I am aware of this, and the code itself just replaces the comment with an empty string, leaving the new line at the end. But I believe if the comment ends at the end of the line, that line can be disregarded.

**Comment by Axieum** [comment]
Another thing I have noticed, is that the following directive does not emit a new line:
```blade
` ` `
@lang('package::lang.key', ['name' => $name])
` ` `
```

Outputs:
```blade
` ` `
package::lang.key` ` `
```

**Comment by driesvints** [comment]
This is expected. Don't do this when using Markdown.

**Comment by maxi032** [comment]
Normal comments are also leaving empty lines. By normal I mean html code that is not a markdown
