### ISSUE TITLE
[5.6.x] back() Method keep statis value, go to root direcotory

### ISSUE THREAD

**Issue by mahbubid** [laravel/framework#31968]
- Laravel Version: 5.6.39
- PHP Version: 7.4.3
- Database Driver & Version: mariadb 10.4

### Description:
value of back() keeping in root direcotory, case

```
function createMarchent(){
return **back()**->withErrors($validarotArray)->withInput();
}
```

### Steps To Reproduce:
i need back() in some previous page, ex: gua.com/marchents, but value of back() in my case keep gue.com.

Validating : i have same code, running and works fine with apache&php v 7.1.

<img width="736" alt="Screenshot 2020-03-15 at 2 05 53 AM" src="https://user-images.githubusercontent.com/2823242/76688779-b5bb4a80-6662-11ea-913e-22632549eb40.png">

thanks for time.

**Comment by GrahamCampbell** [comment]
Laravel 5.6 is not compatible with PHP 7.4. Please downgrade to PHP 7.2, or upgrade to Laravel 6 or 7.

**Comment by mahbubid** [comment]
> Laravel 5.6 is not compatible with PHP 7.4. Please downgrade to PHP 7.2, or upgrade to Laravel 6 or 7.

ok, thanks very much, i run it now!
