### ISSUE TITLE
Container failing to resolve $customStubPath on MigrationCreator

### ISSUE THREAD

**Issue by thechrisroberts** [laravel/framework#31978]
- Laravel Version: 7.1.13
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 8.0.18

### Description:

Apologies if this is my misunderstanding rather than an error, but there's a weird issue when creating custom versions of certain migration commands, causing the container to throw a dependency error due to a failure to resolve `$customStubPath` for `MigrationCreator`:

```
Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator
```

I'm able to address the issue by adding the following to my `AppServiceProvider`, though I'm not sure if I'm missing a more appropriate way to handle this:

```php
$this->app->when(MigrationCreator::class)
    ->needs('$customStubPath')
    ->give(function ($app) {
        return $app->basePath('stubs');
    });
```

Since `MigrationCreator` is being registered in the `MigrationServiceProvider`, I'm thinking the resolution failure is an error and that the above snippet should not be necessary, though I'm not sure what's actually behind the failed resolution.

### Steps To Reproduce:

* Create a custom (even if just empty) `app/Console/Commands/MigrateMakeCommand.php` extending `Illuminate\Database\Console\Migrations\MigrateMakeCommand`
* Run any Artisan command; this should be enough to trigger the error

**Comment by driesvints** [comment]
Your solution is the correct one. Since we bind the migrator as a singleton to the container you'll explicitly have to tell how to resolve the path if you overwrite the command.

**Comment by gmutinel** [comment]
This code doesn't work for me. On the other hand, I made 2 different packages that extends that Class so I don't think that this would be the correct approach, one would overwrite the other or am I missing something?

**Comment by didix16** [comment]
Me too, that code doest not work for me... The error persist...

**Comment by didix16** [comment]
@gmutinel I found a solution.
In my case the error message was:
Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class **App\Database\Migrations\MigrationCreator**

which IS NOT **Illuminate\Database\Migrations\MigrationCreator**

In my MigrationCreator, I just put $customStubPath=null on constructor since I overwrited the stubPath method and I don't need the attribute to have a "valid" value.

So checkout if you have a custom MigrationCreator class.

NOTE: I don't needed to do the solution which @thechrisroberts said. Maybe because I'm using Laravel 7.2

Hope this help to you.

Here is my MigrationCreator:

`<?php


namespace App\Database\Migrations;

use Illuminate\Database\Migrations\MigrationCreator as BaseCreator;
use Illuminate\Filesystem\Filesystem;

class MigrationCreator extends BaseCreator
{
    public function __construct(Filesystem $files, $customStubPath = null)
    {
        parent::__construct($files, $customStubPath);
    }

    /**
     * Get the path to the stubs.
     *
     * @return string
     */
    public function stubPath()
    {
        return __DIR__.'/stubs';
    }
}`

**Comment by gmutinel** [comment]
Damn, thanks, I was almost there!

The magic here is due to the fallback in the Illuminate\Container\Container.php file

```
protected function resolvePrimitive(ReflectionParameter $parameter)
    {
        if (! is_null($concrete = $this->getContextualConcrete('$'.$parameter->name))) {
            return $concrete instanceof Closure ? $concrete($this) : $concrete;
        }

        if ($parameter->isDefaultValueAvailable()) {
            return $parameter->getDefaultValue();
        }

        $this->unresolvablePrimitive($parameter);
    }
```

That NULL works because of that isDefaulValueAvailable().

@driesvints what do you think about adding a default value like this to the Core function in order to fix this at the base (or add a tip to the Docs at least)?

**Comment by driesvints** [comment]
@gmutinel feel free to send in a pr

**Comment by gmutinel** [comment]
is it ok for you @didix16 ? After all, the fix is yours

**Comment by didix16** [comment]
Yeah, no problem. If PR pasts the tests it is ok

**Comment by weogrim** [comment]
If someone gets here like me, solution is in `\Illuminate\Database\MigrationServiceProvider`, where `\\Illuminate\Database\Console\Migrations\MigrationMakeCommand` is registered:

```
    /**
     * Register the command.
     *
     * @return void
     */
    protected function registerMigrateMakeCommand()
    {
        $this->app->singleton(MigrateMakeCommand::class, function ($app) {
            // Once we have the migration creator registered, we will create the command
            // and inject the creator. The creator is responsible for the actual file
            // creation of the migrations, and may be extended by these developers.
            $creator = $app['migration.creator'];

            $composer = $app['composer'];

            return new MigrateMakeCommand($creator, $composer);
        });
    }
``` 

This code is passing `$creator` into the `\Illuminate\Database\Console\Migrations\MigrateMakeCommand`, but not to our custom command. 

On key `migration.creator` is singleton for `\Illuminate\Database\Migrations\MigrationCreator;`:

```
    protected function registerCreator()
    {
        $this->app->singleton('migration.creator', function ($app) {
            return new MigrationCreator($app['files'], $app->basePath('stubs'));
        });
    }
``` 

which passes `$app->basePath('stubs')` as `$customStubPath`.

All we need to do is on our Custom Service Provider register the same, but for CustomMakeMigrationCommand:
```
protected function registerMigrateMakeCommand()
    {
        $this->app->singleton(CustomMakeMigrationCommand::class, function ($app) {
            // Once we have the migration creator registered, we will create the command
            // and inject the creator. The creator is responsible for the actual file
            // creation of the migrations, and may be extended by these developers.
            $creator = $app['migration.creator'];
            $composer = $app['composer'];

            return new MigrateMakeCommand($creator, $composer);
        });
    }
```
