### ISSUE TITLE
Error context not available inside a component

### ISSUE THREAD

**Issue by molteber** [laravel/framework#31975]
- Laravel Version: 7.1.3
- PHP Version: 7.4.3
- Database Driver & Version: n/a

### Description:
Is there a reason why the error context is/should not be available inside components? As a temporary solution, I've feeded `$errors` to the component through a attribute

### Steps To Reproduce:
This does not work:
```blade
# input.blade.php
@props(['name'])
<input type="text" name="{{ $name }}">
@error($name)
{{ $errors->first($name) }}
@enderror
```
```html
# login.blade.php
<x-input name="login" />
```

This does work:
```blade
# input.blade.php
@props(['name', 'errors'])
<input type="text" name="{{ $name }}">
@error($name)
{{ $errors->first($name) }}
@enderror
```
```html
# login.blade.php
<x-input name="login" :errors="$errors" />
```

**Comment by taylorotwell** [comment]
It is available. Are you using Livewire? Note that Livewire had a bug that caused this behavior until the most recent 1.0.4 release.

**Comment by molteber** [comment]
Seems like it works as expected now yes.
I realize I didn't use the anonymous component at all, but rather class component, which was typed ViewErrorBag (thus adding an empty error bag to the component)

During my testing after updating the framework, I failed to remove the `errors` property, thus not working as expected.
