### ISSUE TITLE
Sessions issue

### ISSUE THREAD

**Issue by ehsanrasta** [laravel/framework#31987]
- Laravel Version: 5.7
- PHP Version: 7.1.2
- Database Driver & Version: mysql 

### Description:
Hi
I have an application on production and using session for auth, after changing SESSION_DOMAIN some bugs happened
1.Users got 419 http error and should clear their browsers cache
2.After login users immediately redirected to login page 

I solved this issue by changing SESSION_COOKIE to something else

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
