### ISSUE TITLE
[7.x] Components with default values not working?

### ISSUE THREAD

**Issue by zack6849** [laravel/framework#31980]
- Laravel Version: 7.1.3
- PHP Version: 7.4.1
- Database Driver & Version: MySQL (ver. 5.5.5-10.4.11-MariaDB-1:10.4.11+maria~bionic)

### Description:
I'm not able to make a component with class-based default options in my constructor for some reason. 

I've created a repository to demonstrate my issue, viewable here:
https://github.com/zack6849/component-bug

My select component works, however for some reason no matter what I pass to the blade template, the $name_field and $value_field are ALWAYS their default values.

Am I doing something wrong here? I'll be the first to admit I'm not super caught up on the new components, but this seems strange since other default options are NOT their default options (for example, id and name are settable) 

Reproduction steps:

- Setup app as normal
- Migrate & seed
- Visit default route

Expected Results:
- 2 Select elements, both with visible option text and correct IDs

Actual Results:
- 2 Select elements, only one showing the correct option text, both showing the default IDs because ID is the default field the value is driven by

Quick snippets, just for context:

![tXhTDjkejJxsAU2GZTcUd2cMQ](https://user-images.githubusercontent.com/1343898/76712518-2eb4b380-66f0-11ea-83bd-3c515736f857.png)

Select Component class:
```
<?php

namespace App\View\Components;

class Select extends BaseInput
{
    public $options;
    public $selected;
    public $name_field;
    public $value_field;

    /**
     * Create a new component instance.
     *
     * @param string $label
     * @param $options
     * @param string $id
     * @param string $name
     * @param $selected
     * @param bool $disabled
     * @param string $name_field
     * @param string $value_field
     */
    public function __construct($label, $options, $id = '', $name = '', $selected = null, $disabled = false, $name_field = "name", $value_field = "id")
    {
        parent::__construct($id, $name, $label, null,  $disabled);
        $this->options = $options;
        $this->selected = $selected;
        $this->name_field = $name_field;
        $this->value_field = $value_field;
        debug("End of init for select value: " . $value_field. ' name: '. $name_field . ", id: " . $id);
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.select');
    }

    public function selected($option){
        return $option == $this->selected ? 'selected="selected" ' : '';
    }

    public function option_value($option){
        debug("Returning \$option->{$this->value_field} as value");
        return $option->{$this->value_field};
    }


    public function option_name($option){
        debug("Returning \$option->{$this->name_field} as name");
        return $option->{$this->name_field};
    }
}
```

Select blade component blade.php
```
<x-form-group>
    <label for="{{$id}}">{{$label}}</label>
    <select id="{{$id}}" class="form-control" name="{{$name}}" @if($disabled == true) disabled @endif>
        @foreach($options as $option)
            <option {{ $selected($option) }} value="{{$option_value($option)}}">{{$option_name($option)}}</option>
        @endforeach
    </select>
</x-form-group>
```

**Comment by zack6849** [comment]
I've been poking around in xdebug and it seems that the container "hasParameterOverride" function is returning false for the name_field and value_field options, not sure why...

**Comment by driesvints** [comment]
Default values aren't supported. You need to explicitly pass through the values.

**Comment by zack6849** [comment]
@driesvints so to clarify, default values are unsupported in ALL component classes? documenting that may be helpful, as it just looked like none of the examples were in a case where they happened to define a default.....

**Comment by driesvints** [comment]
Yes. Feel free to send in a pr to the docs 👍

**Comment by zack6849** [comment]
Is this because of the design of the feature, or is this just something that code was never written to support? eg: could support for this be added in the future, or is there a limitation here somewhere?

**Comment by driesvints** [comment]
By design. You always want to explicitly pass your arguments.

**Comment by zack6849** [comment]
@driesvints are underscores not allowed in constructor parameter names? the more i poke around with these, the more strange issues I run into?

This works:
    
```
public function __construct($label, $options, $id, $name, $optionname, $optionvalue, $selected = null, $disabled = false)
    {
        $this->options = $options;
        $this->selected = $selected;
        $this->name_field = $optionname;
        $this->value_field = $optionvalue;
        $this->id = $id;
        $this->name = $name;
        $this->label = $label;
        $this->disabled = $disabled;
    }
```
```
<x-form.inputs.select name="community_id" optionname="foo" optionvalue="id" label="Community" id="community" :selected="$order->community" :options="$communities" :disabled="true"></x-form.inputs.select>
````

This doesn't?

   ```
 public function __construct($label, $options, $id, $name, $option_name, $option_value, $selected = null, $disabled = false)
    {
        $this->options = $options;
        $this->selected = $selected;
        $this->name_field = $option_name;
        $this->value_field = $option_value;
        $this->id = $id;
        $this->name = $name;
        $this->label = $label;
        $this->disabled = $disabled;
    }

```
```
<x-form.inputs.select name="community_id" option_name="foo" option_value="id" label="Community" id="community" :selected="$order->community" :options="$communities" :disabled="true"></x-form.inputs.select>
```



I get the following error

Facade\Ignition\Exceptions\ViewException: Unresolvable dependency resolving [Parameter #4 [ <required> $option_name ]] in class App\View\Components\Form\Inputs\Select (View: /var/www/html/resources/views/pages/work_orders/view.blade.php) in file /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 993

I'm not sure what's going on here, or where the right channels to ask questions like this are, obviously larachat exists but there aren't many people there who have started using the 7.x components.

**Comment by driesvints** [comment]
That's not supported I'm afraid.

**Comment by zack6849** [comment]
Could you elaborate? What other constraints are there that aren't supported that i'll run into later?

**Comment by taylorotwell** [comment]
Works fine for me. Unsure what @driesvints is referring to.

![image](https://user-images.githubusercontent.com/463230/76797664-071b2500-679c-11ea-9f0c-6363440480a3.png)

![image](https://user-images.githubusercontent.com/463230/76797671-0a161580-679c-11ea-94aa-3c9beb8339bc.png)

**Comment by taylorotwell** [comment]
In your first code, snippet you are using `select` instead of `x-select`.

**Comment by taylorotwell** [comment]
Your constructor params should be $nameField and $valueField (camel case) and the attributes should be name-field and value-field (kebab case).

**Comment by driesvints** [comment]
@zack6849 sorry, was under the impression that arguments for class based components were always required.

**Comment by zack6849** [comment]
So, there are constraints for the constructor parameters, but default values are allowed?

Re: using select instead of x-select, could you elaborate? that snippet you see is the content of my x-select element

**Comment by taylorotwell** [comment]
Read my last comment. You shouldn't be using underscore snake casing.

**Comment by zack6849** [comment]
@taylorotwell Thanks, I was able to get it working per your instructions with the following commit https://github.com/zack6849/component-bug/commit/b79feb9a617ef39ed9fa75bc09878ed2d20c3bcc

So, to be clear here, laravel is NOT just taking the attribute names and trying to map them to constructor parameters, it's morphing them in some way?

If so, **THAT** might be worth further documenting, because at this point I just gave up on making these work and started using vue instead, which isn't saying much, they're not very complex components, but I'd still like to be able to use the newer stuff.

**Comment by taylorotwell** [comment]
Sure, feel free to make a docs PR.

**Comment by zack6849** [comment]
I'm not sure I fully understand whatever morphs are happening here, would you mind either changing it (since you'd obviously have a pretty firm grasp of what's happening here) or linking me to the relevant code so I can further understand what's going on here?

Thanks!

**Comment by jbnv** [comment]
Are you seriously saying that default values are not allowed in the constructor arguments? Are you seriously saying that if I'm using a component class with public attributes, that *every single one* has to have a value? It's bad enough that I've wasted a  substantial amount of time figuring out things in Laravel because they aren't intuitive. Flat-out subverting basic PHP functionality and forcing developers to make workarounds that are unnecessary isn't acceptable.

**Comment by hsumudupriya** [comment]
![image](https://github.com/user-attachments/assets/a8a465e9-5155-4400-a463-0a7c5cc202be)
Even though the documentation for Laravel 11.x mentions that default values can be passed to the data attributes of anonymous components using the `@props` directive, if you call the anonymous component without the said attribute, Laravel throws an undefined variable error. This happens only for the attributes whose names contain hyphens.
![image](https://github.com/user-attachments/assets/6dd5099d-b100-4931-b1f7-7a35a11ad6b7)
![image](https://github.com/user-attachments/assets/a4a4361f-3e19-47b7-b6af-0fa381321b15)

@taylorotwell you might want to check this out :)
