### ISSUE TITLE
Bad binary version when launch process into a job

### ISSUE THREAD

**Issue by ElRochito** [laravel/framework#31989]
- Laravel Version: 7.1.3
- PHP Version: .4.3
- Database Driver & Version: Postgres 12.2

### Description:
I have a queuable job which launch a process like this:
```
final class BashTask implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle(): void
    {
        $process = new Process(
            ['curl', 'https://www.google.fr'],
            base_path()
        );
        $process->disableOutput();
        $process->start();
    }
}
```

I work on MacOS, curl apple version is not yet up to date so I've installed with brew curl-openssl.

I've exported binary path on my PATH

### Steps To Reproduce:

**First case**
- I set my QUEUE_CONNECTION env variable to `redis`
- I dispatch my job
- I run `php artisan queue:work`
- Job run successfully
- cURL version used is good

**Second case**
- I set my QUEUE_CONNECTION env variable to `sync` (by default)
- I dispatch my job
- Job failed because `curl` is an older version (using the default MacOS curl version at /usr/bin/curl)

Someone's already had the problem ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ElRochito** [comment]
Ok thanks, sorry for my mistake
