### ISSUE TITLE
[7.x] Larvel cors issue

### ISSUE THREAD

**Issue by mohanrajDev** [laravel/framework#31981]
Laravel 7.x api cors origin issue for GET request but working for POST request?. Please help me.

**Comment by msonowal** [comment]
@mohanrajDev 
what is the config?

**Comment by paulocastellano** [comment]
@msonowal 

I have the same problem (Get and Post), independent of rules in cors.php  I get blocked:

inclusive with ```'paths' => ['*'],```

* Laravel 7.16.1
* PHP 7.4

**Important:**

With Postman, I can call the URL.
