### ISSUE TITLE
Verifier, to verify that there is a bug

### ISSUE THREAD

**Issue by luolaifa000** [laravel/framework#31986]
- Laravel Version: 6.2.0
- PHP Version: 7.2.19
- Database Driver & Version:

### Description:
Verifier, to verify that there is a bug in the email format. The last one in the email format is the Chinese semicolon (；), which has also passed the verification

### Steps To Reproduce:
$tempParams['email'] = "aaaaaa@gg.com；"
$validator = Validator::make($tempParams, [
                    'email' => 'required|email',
                ]);

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
