### ISSUE TITLE
[7.x] Laravel test event listeners dump() issue

### ISSUE THREAD

**Issue by madriesen** [laravel/framework#31984]
- Laravel Version: 7.0.0
- PHP Version: 7.2.5

### Description:
While testing an event-listener, the test fails when using dump('...') in listener: Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.
When using print_r('...') in listener, the tests succeed.

### Steps To Reproduce:
Create a test with call to controller
Fire an event in controller.
In the event listener, use:  dump('...'); // the test will fail
In the event listener, use: print_r('...'); // the test will succeed

**Comment by GrahamCampbell** [comment]
Can you show the full stack trace. Does this happen with the latest version of Laravel 7.0.0 is not supported, but 7.1.3+ is.

**Comment by driesvints** [comment]
The dump function is part of the symfony framework.

**Comment by GrahamCampbell** [comment]
> The dump function is part of the symfony framework.

But the error is produced by Laravel code according to the OP.

**Comment by driesvints** [comment]
Please share some code.

**Comment by ionutantohi** [comment]
This seems to be similar with: #30700

**Comment by madriesen** [comment]
written test:
`/** @test */
    public function a_member_request_can_be_created()
    {
        $response = $this->post(route('memberRequest'), ['email' => 'test@mail.be']);
        $response->assertStatus(200);

        $response = $this->post('/api/memberrequest/create', ['email' => 'test@mail.be']);
        $response->assertStatus(200);
    }`


controller:
`    public function __invoke(memberRequestRequest $request)
    {
        // create member request
        $member_request = MemberRequest::create();

        // add email to request
        $email = $member_request->email()->create(['address' => $request->email]);

        // fire event memberrequest created
        event(new MemberRequestEvent\Created($member_request));

        // send response
        return response()->json(['data' => ['email' => $email, 'member_request' => $member_request]]);
    }`

Event:
`class Created
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $member_request;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($member_request)
    {
        $this->member_request = $member_request;
    }
}`

Listener:
`class NotifyAdminViaMail
{
    /**
     * Handle the event.
     *
     * @param  Created  $event
     * @return void
     */
    public function handle(Created $event)
    {
        // send email
        dump('sending member_request notification email to admin...');
    }
}`

Error:
`1) Tests\Feature\Http\Controllers\Auth\Registration\Invite\InviteControllerTest::an_invite_can_be_opened
Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.

/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:787
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:772
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:119
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:275
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:304
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:210
/Users/martijn/laravel/system/user_management/MS_Users/app/Exceptions/Handler.php:53
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:415
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:113
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:468
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:286
/Users/martijn/laravel/system/user_management/MS_Users/tests/Feature/Http/Controllers/Auth/Registration/Invite/InviteControllerTest.php:27

Caused by
ReflectionException: Class config does not exist

/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:787
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:772
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:119
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:275
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:304
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:210
/Users/martijn/laravel/system/user_management/MS_Users/app/Exceptions/Handler.php:53
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:415
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:113
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:468
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:286
/Users/martijn/laravel/system/user_management/MS_Users/tests/Feature/Http/Controllers/Auth/Registration/Invite/InviteControllerTest.php:27
`

**Comment by driesvints** [comment]
@madriesen you're performing two HTTP calls in your test. Please separate them in different tests and see if the problem persists.

**Comment by madriesen** [comment]
I updated the tests:
`use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class InviteControllerTest extends TestCase
{

    use RefreshDatabase;
    private $member_request;
    private $email;

    public function setUp(): void
    {
        parent::setUp();
        // $this->withoutEvents();


        $response_data = $this->post(route('memberRequest'), ['email' => 'test@mail.be'])["data"];

        $this->member_request = $response_data["member_request"];
        $this->email = $response_data["email"];
    }


    /** @test */
    public function an_invite_can_be_created()
    {
        $response = $this->post('/api/invite/create', ['member_request_id' => $this->member_request['id'], 'email_id' => $this->email['id']]);
        $response->assertStatus(200);

        $response->assertJsonStructure(['data' => ['email', 'invite']]);
    }

    /** @test */
    public function an_invite_can_be_opened()
    {
        try {
            $response = $this->post(route('invite'), ['member_request_id' => $this->member_request['id'], 'email_id' => $this->email['id']]);
        } catch (Error $e) {
            dd('test failed');
        }
        $invite = $response["data"]["invite"];

        $response = $this->post(route('openInvite'), ['invite_id' => $invite["id"]]);
        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => ['invite', 'email']]);
        $response->assertJson(['data' => ['email' => $this->email]]);
    }
}
`
errors:
`PHPUnit 8.3.5 by Sebastian Bergmann and contributors.

"sending member_request notification email to admin..."
."sending member_request notification email to admin..."
E                                                                  2 / 2 (100%)

Time: 314 ms, Memory: 30.00 MB

There was 1 error:

1) Tests\Feature\Http\Controllers\Auth\Registration\Invite\InviteControllerTest::an_invite_can_be_opened
Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist.

/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:787
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:772
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:119
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:275
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:304
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:210
/Users/martijn/laravel/system/user_management/MS_Users/app/Exceptions/Handler.php:53
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:415
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:113
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:468
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:286
/Users/martijn/laravel/system/user_management/MS_Users/tests/Feature/Http/Controllers/Auth/Registration/Invite/InviteControllerTest.php:23

Caused by
ReflectionException: Class config does not exist

/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:787
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:772
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:119
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:275
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:304
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:210
/Users/martijn/laravel/system/user_management/MS_Users/app/Exceptions/Handler.php:53
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:415
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:113
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:468
/Users/martijn/laravel/system/user_management/MS_Users/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:286
/Users/martijn/laravel/system/user_management/MS_Users/tests/Feature/Http/Controllers/Auth/Registration/Invite/InviteControllerTest.php:23

ERRORS!
Tests: 2, Assertions: 4, Errors: 1.
`

**Comment by madriesen** [comment]
> This seems to be similar with: #30700

This worked indeed.
