### ISSUE TITLE
EnsureEmailIsVerified cause a wrong verification when User model doesn't implement MustVerifyEmail

### ISSUE THREAD

**Issue by ptsilva** [laravel/framework#31993]
- Laravel Version: latest
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
When we use `Illuminate\Auth\Middleware\EnsureEmailIsVerified` without explicitly using "implements" `Illuminate\Auth\MustVerifyEmail` on the User default model, it causes a wrong verification, see below:
https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php#L22
```php
!$request->user()  // false
$request->user() instanceof MustVerifyEmail // false
!$request->user()->hasVerifiedEmail() // true
```

Laravel has a direct dependency between the middleware and `\Illuminate\Auth\MustVerifyEmail` interface. In my opinion, the solution could be as simple as throwing an exception when the User model does not alegedly "implements" `MustVerifyEmail` interface.

**Comment by driesvints** [comment]
Just implement the required interface?
