### ISSUE TITLE
Laravel 7 Weird Logout Issue

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [laravel/framework#31992]
- Laravel Version: 7.1.2
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
I have just finished a Laravel 7 app. Upon after finalising payments, I am now having weird issue. I send LOGGED IN USER to payment gateway, the user pays and gateway sends back the user to website as a POST request. But the website response action is never called. Since it is under auth middleware, the user is I don't know how LOGGED OUT and sent to the login screen instead.

In the response where the app sends to http://localhost:8000/login, the headers have `laravel_session` cookie as required.

But the action http://localhost:8000/subscription/process is never called and user is logged out. Never had such issues upto Laravel 6 with same payment gateway.

Inspecting network tab about hops is as follows:
```
POST http://localhost:8000/subscription -> 302 << gateway >>
<< gateway >> -> POST http://localhost:8000/subscription/process -> 302 http://localhost:8000/login
```

### Steps To Reproduce:
The route definition is as follows:
```php
<?php

Route::middleware('auth')->group(function () {

    // This sends the user to gateway
    Route::post('subscription', 'SubscriptionController@renew')->name('subscription.renew');

    // Gateway send the user back here
    Route::post('subscription/process', 'SubscriptionController@process')->name('subscription.process');
});
```

Moreover, I also added below URL to `VerifyCsrfToken` middleware as at first, it was throwing 419.

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    protected $except = [
        '/subscription/process',
    ];
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by vaibhavpandeyvpz** [comment]
It was due to `SameSite=Lax` set by default in Laravel 7 in https://github.com/laravel/laravel/commit/2913a55d87461fabe94907c5728d7a9451bcae80 commit.

**Comment by sebacarrasco93** [comment]
> It was due to `SameSite=Lax` set by default in Laravel 7 as in [laravel/laravel@2913a55](https://github.com/laravel/laravel/commit/2913a55d87461fabe94907c5728d7a9451bcae80) commit.

Thank you! It works again perfectly!

**Comment by Sunny-Ojo** [comment]
@sebacarrasco93  how did you solve it? i changed SameSite to 'null' but still my application wast was logging me out unnecessarily
