### ISSUE TITLE
laravelcollective/html installation problem

### ISSUE THREAD

**Issue by iamzouz** [laravel/framework#31995]
- Laravel Version: 7.1.2
- PHP Version: 7.4.0
- Database Driver & Version: phpMyAdmin 4.9.2
When i try to install laravelcollective/html with the command 'composer require "laravelcollective/html":"^5.8.0" ' in my laravel project i get the following message on the console:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.1.2
    - Conclusion: don't install laravel/framework v7.1.2
    - laravelcollective/html 5.8.x-dev requires illuminate/view 5.8.* -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - laravelcollective/html v5.8.0 requires illuminate/view 5.8.* -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, 
v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - laravelcollective/html v5.8.1 requires illuminate/view 5.8.* -> satisfiable by illuminate/view[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, 
v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/view 5.8.x-dev|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.0|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.11|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.12|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.14|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.15|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.17|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.18|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.19|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.2|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.20|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.22|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.24|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.27|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.28|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.29|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.3|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.30|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.31|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.32|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.33|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.34|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.35|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.36|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.4|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.8|don't install laravel/framework v7.1.2
    - don't install illuminate/view v5.8.9|don't install laravel/framework v7.1.2
    - Installation request for laravel/framework (locked at v7.1.2, required as ^7.0) -> satisfiable by laravel/framework[v7.1.2].        
    - Installation request for laravelcollective/html ^5.8.0 -> satisfiable by laravelcollective/html[5.8.x-dev, v5.8.0, v5.8.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by brunogaspar** [comment]
You should use version 6 of the Laravel Collective for Laravel 7.

```
composer require laravelcollective/html:^6.0
```

**Comment by iamzouz** [comment]
@brunogaspar Thank you ! It works 👍 
Any documentations for laravelCollective 6.0 ?

**Comment by brunogaspar** [comment]
It's all on their website https://laravelcollective.com/docs/6.0/html

**Comment by GrahamCampbell** [comment]
Please raise any questions with the laravel collective team, relating to their code. :)
