### ISSUE TITLE
HTTP client ok() http code 201 

### ISSUE THREAD

**Issue by jurrid** [laravel/framework#32000]
- Laravel Version: 7.0.8

### Description:

If you post to a end point and the server responded back with a http code 201 Created the `$response->ok()` gives back a false. I don't know if this is as attended but to me it feels a bit odd...

**Comment by iamthefreeman** [comment]
It sounds like your endpoint is creating a resource and is returning a status of `201`. In that case, you should be testing for `$response->assertCreated()`. 

You may also test against `$response->assertSuccessful` which will do the following: 

```php 
public function isSuccessful(): bool
{
   return $this->statusCode >= 200 && $this->statusCode < 300;
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jurrid** [comment]
Yes i'm aware the endpoint is creating a resource, hence the question. But no where in the documentation is stated that the ok() method is only for 200 status.

**Comment by iamthefreeman** [comment]
https://laravel.com/docs/7.x/http-tests#assert-ok

> assertOk
Assert that the response has a 200 status code:

**Comment by jurrid** [comment]
For clarification i'm not testing..  

One line to [this](https://laravel.com/docs/7.x/http-client#error-handling) section should be sufficient.

**Comment by rikiless** [comment]
I don't get it. Zttp::isOk() returns true based on successful (>= 200 and < 300) and Laravel Http not?
