### ISSUE TITLE
auto reload page and $errors global variable is empty when an error has length greater than 75 characters

### ISSUE THREAD

**Issue by bacodekiller** [laravel/framework#32018]
- Laravel Version: 6.10
- PHP Version: 7.2.26
- Database Driver & Version: Mysql version 5.7

### Description:
I have same problem like issue #31007. Please help me fix it.

**Comment by dwightwatson** [comment]
I've had similar issues with validation errors using the cookie session driver. I believe I was hitting the file size limit and the information was getting lost. Try using a different session driver.
