### ISSUE TITLE
User::find(1) runs two queries

### ISSUE THREAD

**Issue by mianaliasjad** [laravel/framework#32019]
- Laravel Version: ^7.0
- PHP Version: ^7.2.5
- Database Driver & Version:
MySql
### Description:
I am running a simple query `User::find(1)` and i have checked in the telescope it runs two queries in the result. 
While `User::where('id',1)` only runs one query.

**Comment by staudenmeir** [comment]
What queries does `User::find(1)` run?

**Comment by dwightwatson** [comment]
Are you sure you're not logged in as that user, so the query is being performed by the auth driver and then a second time by your query?

Note also that `User::where('id',1)` won't perform a query - you would need to call `get()` or `first()` on that in order to perform the query.

**Comment by devcircus** [comment]
Yes, auth is likely running that one query that you see. It'll likely be run on every authenticated request.

**Comment by mianaliasjad** [comment]
Thanks, everyone it was auth that was running that query.
