### ISSUE TITLE
Missing ? in CompilesComponents for BladeCompiler

### ISSUE THREAD

**Issue by christian98** [laravel/framework#32020]
- Laravel Version: 7.0.1
- PHP Version: 7.4.2
- Database Driver & Version: I think that's irrelevant ;)

### Description:
When I'm trying to Compile a Component the old way without any parameters for the constructor:
```php
@component('App\View\Components\Test::class')@endcomponentClass
```

I'll get this error:
```
Argument 2 passed to Illuminate\View\Compilers\BladeCompiler::compileClassComponentOpening() must be of the type string, null given, called in D:\xampp\htdocs\messNet\vendor\laravel\framework\src\Illuminate\View\Compilers\Concerns\CompilesComponents.php on line 33 
```

When I look at the [Sourcecode](https://github.com/laravel/framework/blob/7.x/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php#L60), I think there is a "?" missing for a parameter:
```php
public static function compileClassComponentOpening(string $component, string $data, string $hash)
```
should be:
```php
public static function compileClassComponentOpening(string $component, ?string $data, string $hash)
```

Also when I look at the code of the mentioned method, i think the developer thought about that because it says:
```php
($data ?: '[]')
```

### Steps To Reproduce:
Create a Component without parameters for the constructor.
Call the component as stated above.
then you should get the error ;)

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/framework/pull/32032
