### ISSUE TITLE
Auth files in laravel 7

### ISSUE THREAD

**Issue by sajad2176** [laravel/framework#32022]
- Laravel Version: 7x
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

After laravel upgrade to v7 I install a fresh laravel from composer and there is a problem about auth files. actullay the auth folder is empty so I install the "composer require laravel/ui" and after that I run the "php artisan ui bootstrap --auth" and the controllers and views ... were made buuuut the traits which are located in "Illuminate\Foundation\Auth*" for example the AuthenticatesUsers , RedirectsUsers , ... are not exists and I don't know what to do .

my composer.json :
```{
"name": "laravel/laravel",
"type": "project",
"description": "The Laravel Framework.",
"keywords": [
    "framework",
    "laravel"
],
"license": "MIT",
"require": {
    "php": "^7.2.5",
    "fideloper/proxy": "^4.2",
    "fruitcake/laravel-cors": "^1.0",
    "guzzlehttp/guzzle": "^6.3",
    "laravel/framework": "^7.0",
    "laravel/tinker": "^2.0",
    "laravel/ui": "^2.0",
    "spatie/laravel-activitylog": "^3.13"
},
"require-dev": {
    "facade/ignition": "^2.0",
    "fzaninotto/faker": "^1.9.1",
    "mockery/mockery": "^1.3.1",
    "nunomaduro/collision": "^4.1",
    "phpunit/phpunit": "^8.5"
},
"config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true
},
"extra": {
    "laravel": {
        "dont-discover": []
    }
},
"autoload": {
    "psr-4": {
        "App\": "app/"
    },
    "classmap": [
        "database/seeds",
        "database/factories"
    ]
},
"autoload-dev": {
    "psr-4": {
        "Tests\": "tests/"
    }
},
"minimum-stability": "dev",
"prefer-stable": true,
"scripts": {
    "post-autoload-dump": [
        "Illuminate\Foundation\ComposerScripts::postAutoloadDump",
        "@php artisan package:discover --ansi"
    ],
    "post-root-package-install": [
        "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
        "@php artisan key:generate --ansi"
    ]
  }
}```

**Comment by sajad2176** [comment]
I find the problem.
the command
 ```php artisan ui bootstrap --auth``` doesn't work in laravel 7 but  the ```php artisan ui vue --auth``` works fine and it's very werid

**Comment by devcircus** [comment]
just tested by running the following commands and everything worked as expected:

```
laravel new playground
```

```
composer require laravel/ui
```

```
php artisan ui bootstrap --auth
```

```
yarn
```

```
yarn run dev
```

**Comment by rodrigopedra** [comment]
Regarding the auth traits, those traits files are now owned by the `ui` package, but namespaced as usual, you can find those files in the `/vendor/laravel/ui/auth-backend` folder in your project vendor folder.

As they have the same namespace as before you can import them using the `Illumintate\Auth\...` namespace as before. Composer allows mapping different folders to the same namespace.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
