### ISSUE TITLE
Wrong output to the command prompts on windows

### ISSUE THREAD

**Issue by koulaw** [laravel/framework#32033]
- Laravel Version: 7.2.0
- PHP Version: 7.3.12
- Database Driver & Version: Mysql (10.4.10-MariaDB)
- OS: Windows

### Description:

Trying to create a command to make a superadmin using ask prompt inputs.

When i run the command and answer a question with a any accented character, the output is wrong. Accented character are encoded. I did run the same code on both Windows and MacOs, the problem only appear when testing Windows OS.

### Steps To Reproduce:

run php artisan make:command SuperAdmin

in the handle() function  `command/SuperAdmin.php` file add :

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;

class CreateSuperAdmin extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:superadmin';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new Super Admin';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $first_name = $this->ask('First name ?');
        dd($first_name);
    }
}
```

Run the `make:superadmin` command then answer the First name question with `Rémi`

**Expected return**: Rémi
**Actual return**: R\x00mi

Am i missing anything ?

Thanks for the reading.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
