### ISSUE TITLE
Getting error using condition directives on blade components.

### ISSUE THREAD

**Issue by mojtabaahn** [laravel/framework#32045]
- Laravel Version: 7.2.1
- PHP Version: 7.4.3
- Database Driver & Version: -

### Description:
Imagine we have blade component `component-a` and we want to pass some attribute to it on some condition ( well, if condition did not met, we want to pass nothing ).

Currently when using condition directives ( `@if`, `@isset` , ...) it will make error : **syntax error, unexpected 'endif' (T_ENDIF), expecting end of file**

### Steps To Reproduce:
```blade
<!--component-a.blade.php-->
<div {!! $attributes !!}></div>
```

```blade
<!-- main view file -->
<x-component-a @if(true) property @endif />
```

**Comment by driesvints** [comment]
I see you're using 7.0.2, can you upgrade to the very latest version? Numerous fixes have been made since.

**Comment by mojtabaahn** [comment]
Thanks for feedback. Upgraded to 7.2.1 and same results appear.

**Comment by driesvints** [comment]
Unfortunately we don't seem to support this syntax. Please try:

```blade
@if(true)
<x-component-a property />
@else
<x-component-a />
@endif
```

**Comment by stuartcusackie** [comment]
My component accepts a large chunk of data in it's main $slot. It seems I would have to write a lot of code twice with this solution.

> Unfortunately we don't seem to support this syntax. Please try:
> 
> ```
> @if(true)
> <x-component-a property />
> @else
> <x-component-a />
> @endif
> ```

My component accepts a large chunk of data in it's main $slot. It seems I would have to write a lot of code twice with this solution.

**Comment by nagi1** [comment]
I hate to say this without providing ant solutions or suggestions, but I have the same problem.
Is there any other elegant way to handle this?

**Comment by nagi1** [comment]
> I hate to say this without providing ant solutions or suggestions, but I have the same problem.
> Is there any other elegant way to handle this?

15 min later, I solved this  (in my usecase) 

input-component.blade.php
```php
        <input type="checkbox" id="{{ $name }}" name="{{ $name }}" {{ $attributes->merge(['class' => $makeItemClass($errors->first($name))]) }}
 @if($isChecked) checked @endif <--- added a flag here
/>
```

InputComponent.php

```php
class InputSwitch extends InputGroupComponent
{
    public $isChecked;

    public function __construct( $isChecked = false) {
        $this->isChecked = $isChecked;
    }
}
```


Usage in my view

```blade
                <x-admin.input-switch name="is_active" label="{{ __('Active') }}" label-class="text-dark" top-class="col-2" :is-checked="true">
                </x-admin.input-switch>
```


Cheers :wine_glass:

**Comment by driesvints** [comment]
No there isn't unfortunately. This is pretty hard to make possible with the compiler. If anyone can figure out on how to make directives in components possible we're welcoming PRs.

**Comment by akinuri** [comment]
I'm having this same issue. I need to render a single component and I need to pass two different attributes depending on a condition. The `{{ ... }}` syntax does not seem to work when used in component syntax.

I'm guessing the blade file is rendered in a single pass. To make the `{{ ... }}` syntax also work in component syntax, there can be two passes. The first is to resolve `{{ ... }}` since it seems to have higher priority, and then the second to resolve the components. Wouldn't this work?
