### ISSUE TITLE
[MSSQL] add renameForeign command

### ISSUE THREAD

**Issue by heartbeatLV** [laravel/framework#32044]
- Laravel Version: 7.2.1
- PHP Version: 7.4.3
- Database Driver & Version: SQL Server 14.0.2027.2

### Description:
Currently there is the [renameIndex](https://laravel.com/docs/7.x/migrations#renaming-indexes) function:

```php
Schema::table('table', function (Blueprint $table) {
    $table->renameIndex('from', 'to');
})
```

The generated query is:
```sql
sp_rename N'"table"."from"', "to", N'INDEX'
```

```php
SqlServerGrammar.php:309

public function compileRenameIndex(Blueprint $blueprint, Fluent $command)
{
    return sprintf("sp_rename N'%s', %s, N'INDEX'",
        $this->wrap($blueprint->getTable().'.'.$command->from),
        $this->wrap($command->to)
    );
}
```

### Error: 

If it is used to rename a **foreignKey** it fails:

`SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Either the parameter @objname is ambiguous or the claimed @objtype (INDEX) is wrong. (SQL: sp_rename N'"table"."from"', "to", N'INDEX')`

### Additional Info:
This query works:
```sql
sp_rename N'"schema"."from"', "to"
```

I noticed that in MSSQL if the table belongs to a schema also the foreign key belongs to it. Therefore if the name of the table is passed it does not work.
Example for the table **customSchema.table_name**: 
```php
Schema::table('table_name', function (Blueprint $table) {
    $table->renameIndex('from', 'to');
})
```

this works (note the first parameter of the table function):
```php
Schema::table('customSchema', function (Blueprint $table) {
    $table->renameIndex('from', 'to');
})
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
