### ISSUE TITLE
Http Client multipart request

### ISSUE THREAD

**Issue by lumore** [laravel/framework#32058]
- Laravel Version: ^7.2
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.0.12

### Description:
Http Client throws an error when passing both file and body params into POST request.

### Steps To Reproduce:

```
$photo = fopen(public_path('/storage/') . $this->photoPath, 'r');

$response = Http::withToken($this->token)
	->withHeaders([
		'X-Header' => $this->header
	])
	->attach('photo', $photo)
	->post($url, [
		'name' => 'test'
	]);
```
Request above ends up with throwing the following error:

> TypeError: Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given, called in /vendor/guzzlehttp/psr7/src/MultipartStream.php on line 70 in file /vendor/guzzlehttp/psr7/src/MultipartStream.php on line 79

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by adelinferaru** [comment]
@lumore I seems that during the process of creating Guzzle options array, if you have an ::attach in your flow, even though the body format is set to 'multipart', the post array data is not formated but it is merged into options as it is. So in your example you should do as below:
```
$photo = fopen(public_path('/storage/') . $this->photoPath, 'r');

$response = Http::withToken($this->token)
	->withHeaders([
		'X-Header' => $this->header
	])
	->attach('photo', $photo)
	->post($url, [
                [
                       'name' => 'param_1',
                       'contents' => 'param_1 contents'
                ],
                ....
	]);
```

**Comment by rossity** [comment]
@driesvints This is definitely a bug and I can confirm I have reproduced it. The above solution works but should not be necessary. We should be able to do the following:

```php
photo = fopen(public_path('/storage/') . $this->photoPath, 'r');

$response = Http::withToken($this->token)
	->withHeaders([
		'X-Header' => $this->header
	])
	->attach('photo', $photo)
	->post($url, [
                   'param_1' => 'param_1 contents',
                    ...
            ]);

```

This would bring it in line with the format of every other post request.

**Comment by driesvints** [comment]
Okay re-opening. Feel free to send in a PR.

**Comment by Temepest74** [comment]
It is still not fixed in laravel 8

**Comment by nafil-gigsboard** [comment]
Unable to fix this issue

**Comment by codoffer** [comment]
> contents

What is "contents"? Will I have to pass file content with param? I want to send some values and a multipart file with field attachments[]

How can I achieve this? I am getting an error

A 'contents' key is required

**Comment by handhikadj** [comment]
what is the alternative on this?

**Comment by codoffer** [comment]
We have used an alternate way for this issue. We have used guzzle package - https://docs.guzzlephp.org/en/stable/request-options.html#multipart

**Comment by handhikadj** [comment]
yea. I also though it too.
anyway, how can this is passed to production and still in the docs while it's still buggy? SMH...

**Comment by murilolivorato** [comment]
same problem here . 

```
  "message": "A 'contents' key is required",
    "exception": "InvalidArgumentException",
    "file": "/var/www/html/vendor/guzzlehttp/psr7/src/MultipartStream.php",
    "line": 90,
    "trace": [
        {
            "file": "/var/www/html/vendor/guzzlehttp/psr7/src/MultipartStream.php",
            "line": 77,
            "function": "addElement",
            "class": "GuzzleHttp\\Psr7\\MultipartStream",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/guzzlehttp/psr7/src/MultipartStream.php",
            "line": 38,
            "function": "createStream",
            "class": "GuzzleHttp\\Psr7\\MultipartStream",
            "type": "->"
        },
```


any solution ?

**Comment by raja-muhammad-asher** [comment]
Facing the same problem and alternatively used guzzle package as proposed by @codoffer

**Comment by alexrada** [comment]
still getting it in laravel 10.

**Comment by alejandroschmeichler** [comment]
I encountered the same issue in Laravel 11, but only when the post data array includes nested keys. For example

```php
$data = [
   'key_1' => 1,
   'key_2' => [
      'key_2_1 => 2
   ],   
];
```

So I just flattened the array and now it works.

```php
$data = [
   'key_1' => 1,
   'key_2_1' => 2
];
```

**Comment by sundayz** [comment]
I know it's not a helpful comment but we're also running into this issue, the StabilityAI api requires a multipart image upload: https://platform.stability.ai/docs/api-reference#tag/3D/paths/~1v2beta~13d~1stable-fast-3d/post

**Comment by gagaltotal** [comment]
the following : [https://github.com/laravel/framework/pull/32428]
this is work for me : 

```
$file_path = fopen(storage_path('app/public/file/'. $dok_file), 'r');

                        $upload = Http::withHeaders([
                            'Auth'          => 'Bearer '.$token1->token,
                            'Authorization' => 'Bearer '.$token2->token,
                        ])->attach(
                            'file', $file_path
                        )->post('https://api.com/upload-dok',[
                            [ 'name' => 'file',  'contents' => $file_path ],
                            'value_1'     => $value1,
                            'value_2'     => $value2,
                        ]);
```

**Comment by stansGama** [comment]
> I encountered the same issue in Laravel 11, but only when the post data array includes nested keys. For example
> 
> ```
> $data = [
>    'key_1' => 1,
>    'key_2' => [
>       'key_2_1 => 2
>    ],   
> ];
> ```
> 
> So I just flattened the array and now it works.
> 
> ```
> $data = [
>    'key_1' => 1,
>    'key_2_1' => 2
> ];
> ```

Another approach is to json encode nested arrays like

`$data = [
   'key_1' => 1,
   'key_2' => json_encode(['key_2_1 => 2]),   
];`

**Comment by virkse** [comment]
Multi-dimensional data or single index data i fixed it using below code.

```
Http::acceptJson() ->attach('attachments[]', File::get($path), File::basename($path)) ->post(
    $destination, [ 
              [ 
                  'name' => "first_name", 
                  "content" => "John Smith" 
              ], 
                  [
                    'name' =>
                    "providers", "content" => 1, 
                  ], 
                 [
                   'name' => "providers", 
                   "content" => 2, 
                  ], 
                 [ 
                     'name' => "providers", 
                     "content" => 3, 
                 ] 
      ]
);
```

Breakdown your multiple dimensions in further parts with same name like above providiers.

**Comment by danharrin** [comment]
Just wanted to share that I was also receiving `A 'contents' key is required` intermittently and was very confused as to why.

It turns out that the `attach()` method has an `array_filter()` which removes the 'contents' data from a file attachment if it is falsy: an empty string, 0, `'false'` etc.

So the fix is to ensure that the content you are attaching is never falsy. Always make sure you are attaching content that is truthy, and is not empty.
