### ISSUE TITLE
not able to authorize for privateChannels 

### ISSUE THREAD

**Issue by srhtylmz19** [laravel/framework#32057]
- Laravel Version: 7
- PHP Version: 5.8
- Database Driver & Version: mysql

### Description:

im firing event to listen from socket , when i fire event with ''Channel'' there is no problem with communication, but when i tried to make them privateChannel i cant authorize to listen events. i have roles on my users and i just want my admin-users to be able to listen my private channel
here is example:

event.php
 public function broadcastOn()
    {
        return new PrivateChannel('redeems');
    }

channels.php

Broadcast::channel('redeems', function ($user, $id) {
    return true;
});

and my echo instance

const echo = new Echo({
  host: 'http://127.0.0.1:6001/',
  broadcaster: 'socket.io',
  client: socketio,
  authEndpoint: 'broadcasting/auth',
  auth: {
    headers: {
      Authorization: 'bearer-token',
    },
  },
});

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
