### ISSUE TITLE
Memory leak when logging a lot of times

### ISSUE THREAD

**Issue by cosmeoes** [laravel/framework#32054]
- Laravel Version: 6.18.2
- PHP Version: 7.3.12
- Database Driver & Version: Not used.

### Description:
I have a command that does a lot of processing. That command runs out of memory. After a lot of trial and error, I realized that the bug is still present on a clean installation of laravel and just having a huge for loop with only `Log::info("test")` inside it. 
This a sample of the results of memory usage by calling `memory_get_usage()`:
```
Sat Mar 21, 2020 0:34: Memory 12.93 mb
Sat Mar 21, 2020 0:34: Memory 12.93 mb
Sat Mar 21, 2020 0:34: Memory 12.93 mb
...
Sat Mar 21, 2020 0:34: Memory 49.63 mb
Sat Mar 21, 2020 0:34: Memory 49.63 mb
Sat Mar 21, 2020 0:34: Memory 49.63 mb
...
Sat Mar 21, 2020 0:35: Memory 92.93 mb
Sat Mar 21, 2020 0:35: Memory 92.93 mb
Sat Mar 21, 2020 0:35: Memory 92.93 mb
```

### Steps To Reproduce:
I created a command to test this memory leak by runing `php artisan make:command TestLeak`:
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class TestLeak extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:leak';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        for ($i = 0; $i < 2000000; $i++) {
            Log::info("Causing memory leak");
            $this->logMemory();
            
        }
    }


    private function logMemory() {
        $memoryUsage = $this->convert(memory_get_usage());

        $datetime = (new \DateTime('now'))->format('D M d, Y G:i');
        file_put_contents("memory.log", "$datetime: Memory $memoryUsage\n", FILE_APPEND);
        
    }

    function convert($size)
    {
        $unit=array('b','kb','mb','gb','tb','pb');
        return @round($size/pow(1024,($i=floor(log($size,1024)))),2).' '.$unit[$i];
    }
    
}

```
Then ran it with `php artisan test:leak`. This creates a file called `memory.log` which has the results showed above.

### Other information:
The only progress I could make to figure this out is that I noticed that if I comment out the references to `$this->dispatcher` in [`src/Illuminate/Log/Logger.php`](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Log/Logger.php) class, the issue seems to go away.

More specifically here: 
https://github.com/laravel/framework/blob/de01e2926a7560c43fb763d86de134a52b46928b/src/Illuminate/Log/Logger.php#L36-L40
And here:
https://github.com/laravel/framework/blob/de01e2926a7560c43fb763d86de134a52b46928b/src/Illuminate/Log/Logger.php#L187-L194

I'm not sure about this but this could be related to this issue https://bugs.php.net/bug.php?id=76982

I don't know much about PHP or Laravel so help here would be much appreciated .

**Comment by cosmeoes** [comment]
Reproduced the issue on version 7.2.2.

**Comment by taylorotwell** [comment]
Is anything in your code calling Log::listen?

**Comment by cosmeoes** [comment]
Honestly, I don't know. But this is a default project I created by running `composer create-project --prefer-dist laravel/laravel blog`. The only thing I did was create the command to test it.

**Comment by mo3000** [comment]
I reproduce this on a fresh installation of laravel (7.3.0) by running 

> composer create-project --prefer-dist laravel/laravel blog

add a command  with simple code here

```php
/**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        while (true) {
            Log::info("Causing memory leak");
            $this->line('memory usage: '.(memory_get_usage(true) / 1024 / 1024));
        }
    }
```

The memory usage mumber keeps go up and after like  a minute got a oom error:

>    Whoops\Exception\ErrorException

>  Allowed memory size of 134217728 bytes exhausted (tried to allocate 33554440 bytes)
> at vendor/facade/ignition/src/LogRecorder/LogRecorder.php:35

I look at LogRecorder.php and see this:
```php
    public function record(MessageLogged $event): void
    {
        if ($this->shouldIgnore($event)) {
            return;
        }

        $this->logMessages[] = LogMessage::fromMessageLoggedEvent($event);  //this is line no 35
    }
```
Seems like LogRecorder keeps store logMessages in an array and never release them.
If commenting out line 35 the problem disapears.

I understand that store messages is useful but in a long living command line app we need a way to free all that stored messages.
@driesvints

**Comment by mfn** [comment]
You don't need to use ignition, it's optional (though comes installed by default) => https://github.com/facade/ignition/issues is the correct repo to report issues

**Comment by mo3000** [comment]
> You don't need to use ignition, it's optional (though comes installed by default) => https://github.com/facade/ignition/issues is the correct repo to report issues

good to know.

**Comment by driesvints** [comment]
Please open an issue on the ignition repo.
