### ISSUE TITLE
Artisan Key Generate not working with PHP 7.4.4

### ISSUE THREAD

**Issue by ExCluSiv3** [laravel/framework#32059]
- Laravel Version: 7.2.0
- PHP Version: 7.4.4

### Description:

When using the command "php artisan key:generate" with PHP 7.4.4 a RuntimeException is thrown in the EncryptionServiceProvider, when no APP_KEY is set.

"No application encryption key has been specified."

### Steps To Reproduce:

1. Update PHP to Version 7.4.4
2. Create a fresh Laravel project
3. Try to generate a new APP_KEY using the "php artisan key:generate" Command.

**Comment by staudenmeir** [comment]
What OS are you using?

**Comment by ExCluSiv3** [comment]
I'm using MacOS (10.15.3), but the same error occurs within my CI Pipeline which is based on the official PHP Docker images (latest, linux/amd64, https://hub.docker.com/_/php?tab=tags).

My local php has been installed through homebrew, but i noticed the error because the CI Pipeline kept failing.

**Comment by GrahamCampbell** [comment]
Is this a problem specifically with 7.4.4?

**Comment by ExCluSiv3** [comment]
Yes totally, i've tested it locally with php 7.4.2, my CI Pipeline used 7.4.3 (which i also tested locally afterwards) and after the update to 7.4.4 the command broke.

**Comment by driesvints** [comment]
I can run the command on PHP 7.4.4

**Comment by CaliforniaMountainSnake** [comment]
I also see the problems with `php artisan key:generate` on docker image `php:7.4-fpm`.
Sometimes the command works fine, but sometimes `APP_KEY` just has been not set and still empty, fifty-fifty.
I didn't see any problems with this command on the previous versions php (7.3) or previous versions of Laravel (5.8).
I am not sure this is the problem of php 7.4, maybe this is the problem of laravel 7 or something else.

**Comment by ExCluSiv3** [comment]
@CaliforniaMountainSnake check your ServiceProviders, in another Project where i came across this, i have tried to set some Inertia::share value from the session within the Providers boot() method. Prior to 7.4.3 this was no problem, but after the update to 7.4.4 this threw an Exception which caused the Command to stop before it could set the APP_KEY

**Comment by ujesh-t** [comment]
Facing same issue.. PHP 7.4 on CENTOS 8

**Comment by nezaboravi** [comment]
i have problem here on PHP 7.4.15 
When i run command, it does not write it into .env file, but it says key generated on terminal.
I am on macos Big Sur, M1 silicon
 ```
paper git:(vladimir/swap-is_admin) ✗ php artisan key:generate
Application key set successfully.
➜  paper git:(vladimir/swap-is_admin) ✗ php -v
PHP 7.4.15 (cli) (built: Feb  4 2021 07:01:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.3, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies```

**Comment by smecnarowski** [comment]
I had the same problem because there was no APP_KEY. After adding line APP_KEY= to the .env file key generated with success.

**Comment by nezaboravi** [comment]
> I had the same problem because there was no APP_KEY. After adding line APP_KEY= to the .env file key generated with success.

I have added APP_KEY=

**Comment by mycarrysun** [comment]
> I had the same problem because there was no APP_KEY. After adding line APP_KEY= to the .env file key generated with success.

Was bugging me for a good few minutes before I saw this comment and this was the solution that fixed it for me. Thank you.

**Comment by icetique** [comment]
This was giving me headaches for the past few days. What helped me was adding APP_KEY= to the .env file, however with one space before the line break.

**Comment by kevinbigfun** [comment]
try clear everything cache, especially config:clear and cache:clear.
key generation may be influenced by these stuff.

**Comment by thanhtruong1992** [comment]
> try clear everything cache, especially config:clear and cache:clear.
> key generation may be influenced by these stuff.

It is working
