### ISSUE TITLE
How to use Socket.IO with laravel?

### ISSUE THREAD

**Issue by iamzouz** [laravel/framework#32062]
- Laravel Version: 7.1.2
- PHP Version: 7.4.0
- Database Driver & Version: mysql 8.0.18

Hello Guys, i am building a Web Chatting Platform with Laravel,
and i am new to web sockets, i want to use Socket.IO to make it Real-Time Chat Application.
But i don't know why it's very hard to find a documentation or Tutorial or a course to buy to learn Socket.IO with Laravel.

Anyone have any idea how or where can i find the above requested?
Thank you in advance.

**Comment by ankurk91** [comment]
Have you seen this

https://docs.beyondco.de/laravel-websockets/

**Comment by ryangjchandler** [comment]
Please post this in one of the many forums available, or another community such as Discord / Slack. This issue board is for bugs related to the framework itself.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
