### ISSUE TITLE
Redis Prefix not prepending

### ISSUE THREAD

**Issue by ItsZiroy** [laravel/framework#32069]
- Laravel Version: 7.2.2
- PHP Version: 7.4.4
- Database Driver & Version: Redis 4.0.9, Predis 1.1.1
### Description:
We have encountered an issue that randomly made our redis prefix disappear. We have no Idea why this occurs. One day the prefix, which at that point was not of any use for us disappeared. So I just changed the channel name our frontend listens to back to the name without a prefix. Now, however, we wanted to add a second project on the same redis database, but with a different prefix. The prefix does not prepend properly although it is cached and accessable from `config('database.redis.options.prefix')` We have tested that. Looking at our laravel-echo-server terminal, we observed that no prefix was attached unless we added it manually to the channel name like below image shows. 
![image](https://user-images.githubusercontent.com/44354000/77265681-a3ae5d00-6c9d-11ea-98e8-559cbb1658d3.png)

The date I observed that the name was not attached was January 31, 2019. That was on v6.12.0 Please let me know if you need additional information.

**Comment by driesvints** [comment]
Please fill out the issue template with proper versions.

**Comment by ItsZiroy** [comment]
I have updated the versions accordingly I believe.

**Comment by ItsZiroy** [comment]
Updating to Redis version to 5.x will fix the error!
