### ISSUE TITLE
Multiple Blade X component instantiations in the same view

### ISSUE THREAD

**Issue by MCFreddie777** [laravel/framework#32063]
- Laravel Version: 7.2.1
- PHP Version: 7.3.13

### Description:
Can you have multiple instantiations of one Blade X component?

It says: __Cannot declare class App\View\Components\Foo, because the name is already in use__

If you use it once - or use it without constructor / class variables, it works. Maybe I'll go with the anonymous way, I was just curious what am I doing wrong.

### Steps To Reproduce:
```
// app/view/components/foo.php

class Foo extends Component {
    public $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    ...
```

```
// resources/views/components/foo.blade.php
<div>
    {{  $name }}
</div>
```
```
// resources/views/rootcomponent.blade.php
<x-foo name="John"></x-foo>
<x-foo name="Mary"></x-foo>
```

**Comment by driesvints** [comment]
Component names need to be unique.
