### ISSUE TITLE
issue with "required" validation rule behavior

### ISSUE THREAD

**Issue by anasred** [laravel/framework#32061]
- Laravel Version: 7.2.2
- PHP Version: 7.2.26
- Database Driver & Version: MySQL

### Description:
'required' validation will no longer return 422 status code. instead, it will redirect your request to '/'

### Steps To Reproduce:
on a fresh Laravel project add the following:
1. routes/api.php

```
Route::post('orders', 'OrderController@store');
```

2. add a new controller in: app/Http/Controllers/OrderController.php
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function store(Request $request)
    {
        $validated = $request->validate([
            'user_id' => 'required' //OR ['required']
        ]);

        return $validated; /// THIS LINE WONT BE REACHED WHETHER THE ABOVE VALIDATION EVALUATED TO TRUE OR FALSE
    }
}
```

** also this being tested on Laravel v6.18.2 with same behavior

**Comment by staudenmeir** [comment]
Please provide the necessary code to reproduce this on a fresh installation of Laravel, ideally as a GitHub repository.

**Comment by anasred** [comment]
My bad...
The problem was that PostMan didn't send ```Accept: "application/json"``` header with the request by default. When I added it the behavior worked properly.
