### ISSUE TITLE
composer package:discover --ansi fails the first time it runs with Class MyClass does not exists

### ISSUE THREAD

**Issue by marcohern** [laravel/framework#32064]
- Laravel Version: 7.2.2
- PHP Version: 7.3.9
- Database Driver & Version: mysql 5.7.29-log

### Description:
So i'm developing a site using Laravel and a PHP library called dracula which I am attaching as a submodule. At the moment the website is empty, but I am developing commands that I wish to execute in a schedule. Im deploying to Heroku. Laravel runs fine locally, and the first few times It deployed to Heroku fine. At some point all Heroku builds started to fail, but locally it would still work fine.

I was able to reproduce the issue when I cloned my laravel app repo from scratch into a new folder. as soon as I ran composer update on the newly cloned repo, composer fails, run it a second time and it works. But since the first time always fails, this breaks my build in Heroku.

### Steps To Reproduce:
The following are the list of commands to reproduce:
```
git clone https://github.com/marcohern/onsale.git
cd onsale
composer update
#this fails, but do it again...
composer update
#...and now it works, but build broke the last time, so Heroku rejects
```
This is the output of composer update in my local machine.
[onsale_composer_update_log.txt](https://github.com/laravel/framework/files/4364527/onsale_composer_update_log.txt)

This is the output from Heroku 
[onsale_composer_update_heroku_log.txt](https://github.com/laravel/framework/files/4364534/onsale_composer_update_heroku_log.txt)

my composer.json (app is called onsale and submodule dependency is called dracula). It may be a little dirty because i've been updating it trying to find the issue.

[onsale_composer.json.txt](https://github.com/laravel/framework/files/4364531/onsale_composer.json.txt)

**Comment by marcohern** [comment]
The error message is **Class Marcohern\Dracula\Manager does not exist**. To be clear, the class does in fact exists and in the correct path, as specified in the composer.json (dracula\src\Manager.php). Also, the error is triggered after the submodule (dracula subfolder) is cloned, suggesting that the submodule is not the immediate cause of the problem.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
