### ISSUE TITLE
[7.x] transferStats is null when using Http::fake

### ISSUE THREAD

**Issue by PhiloNL** [laravel/framework#32068]
- Laravel Version: 7.2.2
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:
When using `Http::fake` the transferStats attribute returns `null` instead of the `transferStats` object.

### Steps To Reproduce:
Add the following route and hit this route. This will return the `GuzzleHttp\transferStats` object.
```php
Route::get('foo', function() {
    $transferStats = Http::get('https://laravel.com/img/logotype.min.svg')->transferStats;
    dd($transferStats);
});
```

Create a test and fake the Http client, I tried a couple of things but it keeps returning `null`:

```php
class HttpTest extends TestCase
{
    public function testRoute()
    {
        Http::fake();
        $this->get('foo'); // returns null
    }

    public function testFoobar()
    {
        Http::fake([
            '*' => Http::response(
                base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg=='),
                200,
                [
                    'Content-type' => 'image/jpeg',
                    'Content-Length' => '172498',
                ])
        ]);
        $this->get('foo'); // returns null
    }
}
```

**Comment by driesvints** [comment]
Since nothing is transferred during faking it's not available. Feel free to send in a PR to the docs if you want. Thanks.
