### ISSUE TITLE
Factory depends on `Symfony\Component\Finder\Finder`

### ISSUE THREAD

**Issue by PandaRory** [laravel/framework#32070]
- Laravel Version: Illuminate\Database 5.6.x or newer
- PHP Version: PHP 7.2
- Database Driver & Version: N/A

### Description:

I have a project using `Illuminate\Database 5.6.39` separately to build model and migrate data in unit test and not with laravel framework. 

When using `Illuminate\Database\Eloquent\Factory` to generate all fake data at once, I notice Factory's public static function `construct` depends on `Symfony\Component\Finder\Finder`. 
https://github.com/illuminate/database/blob/v7.2.2/Eloquent/Factory.php#L7

Should Finder lib be noted `suggest` in composer.json of `Illuminate\Database`?

### Steps To Reproduce:
I use ModelFactory to generate fake data under factories directory, eg. MemberFactory. 

tests/Database/ModelFactory.php
```php
<?php

namespace Tests\Database;

use Faker\Factory as FakerFactory;
use Illuminate\Database\Eloquent\Factory;

class ModelFactory
{
    public static function construct()
    {
        $faker = FakerFactory::create();
        return Factory::construct($faker, __DIR__ . '/Factories');
    }
}
```
tests/Database/Factories/MemberFactory.php
```php
<?php

namespace Tests\Database\Factories;

use Faker\Generator as Faker;
use Model\Member;

$this->define(Member::class, function (Faker $faker) {
    return [
        'uid' => 'john',
        'email' => 'john@gmail.com',
        'created_at' => $faker->dateTime(),
        'updated_at' => $faker->dateTime(),
    ];
});
```
run phpunit and it errors
```
Error: Class 'Symfony\Component\Finder\Finder' not found

/projects/XXX/vendor/illuminate/database/Eloquent/Factory.php:274
/projects/XXX/vendor/illuminate/database/Eloquent/Factory.php:68
/projects/XXX/vendor/tests/Database/ModelFactory.php:13
/projects/XXX/vendor/tests/TestCase.php:36
```

**Comment by driesvints** [comment]
PR was sent in. Thanks for reporting.
