### ISSUE TITLE
Dynamic call to static method

### ISSUE THREAD

**Issue by jooola** [laravel/framework#32079]
- Laravel Version: 7.x.x
- PHP Version: 7.3 or 7.4

### Description:

Since we upgraded to version ^7, phpstan is throwing the following errors:
 
```
 ------ ------------------------------------------------------------- 
  Line   src/Laravel/Providers/DirectusProvider.php                   
 ------ ------------------------------------------------------------- 
  52     Dynamic call to static method                                
         Illuminate\Foundation\Application::configurationIsCached().  
  95     Dynamic call to static method                                
         Illuminate\Foundation\Application::routesAreCached().        
 ------ ------------------------------------------------------------- 
```

I opened a ticket on the larastan project https://github.com/nunomaduro/larastan/issues/483 , but I feel it is better if I report this problem here.

Please read https://github.com/nunomaduro/larastan/issues/483 to get all the details on this problem.

Specially https://github.com/nunomaduro/larastan/issues/483#issuecomment-597828522:
> I don't really know how those checks are made, but maybe it's the class definition conflicting with the Facade definition?
In Facade it's declared as static, and interface/class it's a class method.

### Steps To Reproduce:

See:
- https://github.com/directus/api-next/blob/master/src/Laravel/Providers/DirectusProvider.php#L52
- https://github.com/directus/api-next/blob/master/src/Laravel/Providers/DirectusProvider.php#L95

**Comment by driesvints** [comment]
This doesn't seems like a bug with Laravel so please continue the discussion in the linked issue. Thanks.
