### ISSUE TITLE
Validator output returns parsed data instead of original

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/framework#32076]
- Laravel Version: 6.18.2
- PHP Version: 7.4

### Description:
When using the $this->validate() function inside a controller the parsedData gets returned instead of the original data. This means that a dot is converted to "->"

```
    /**
     * Parse the data array, converting dots to ->.
     *
     * @param  array  $data
     * @return array
     */
    public function parseData(array $data)
    {
        $newData = [];

        foreach ($data as $key => $value) {
            if (is_array($value)) {
                $value = $this->parseData($value);
            }

            $key = str_replace(['.', '*'], ['->', '__asterisk__'], $key);

            $newData[$key] = $value;
        }

        return $newData;
    }
```

### Steps To Reproduce:

Post the following data to an controller:
```
{
  "id": 18,
  "config": {
    "x": {
      "a": "a",
      "b": "b"
    },
    "y.z": {
      "a": "a",
      "b": "b"
    }
  }
}
```

Run the validator:
```
        $updates = $this->validate($request, [
            'config' => 'nullable',
        ]);
```

The output has the dot converted to an arrow:

```
{
  "id": 18,
  "config": {
    "x": {
      "a": "a",
      "b": "b"
    },
    "y->z": {
      "a": "a",
      "b": "b"
    }
  }
}
```

**Comment by driesvints** [comment]
That's expected. Dot syntax in keys conflicts with the validator so they're stripped. Please use something else as a key.

**Comment by jeffreyzant** [comment]
Why does the $this->validate function return the stripped data and not the normal data? That doesn't make sense. It makes the function unpredictable and does not work as expected. Why not return the original data from the function and not the parsed data? Seems to me this could be done by using the "->only()" function on the given request object.
