### ISSUE TITLE
SQLite fails silently to rename or change columns in same time of adding new ones.

### ISSUE THREAD

**Issue by mathieutu** [laravel/framework#32073]
- Laravel Version: 7.2.2
- PHP Version: 7.4.2
- Database Driver & Version: Sqlite 3.31.1

### Description:

Hi, 
Because in SQLITE case DBAL recreate a temporary database with data present in current table, if you rename, change or drop some columns at the same time you add some, the added will be lost without any error message.

As Laravel execute all the queries inside a table callback at the same time, I can't see a proper and quicker way to fix that.

I so would recommend to throw an error if a field is changed at the same time one another is added, in the `ensureCommandsAreValid` method. (Actually there are already other checks and error thrown about changing columns in sqlite)

I would be glad to make a PR if this solution is ok for you.

Matt'

### Steps To Reproduce:

```php
 Schema::table('users', function (Blueprint $table) {
     $table->string('type');

     $table->renameColumn('name', 'full_name');
});
```

**Comment by mathieutu** [comment]
For the record, if people find this issue, the bypass to this limitation is to do: 
```php
Schema::table('users', function (Blueprint $table) {
     $table->string('type');
});

Schema::table('users', function (Blueprint $table) {
     $table->renameColumn('name', 'full_name');
});
```

(but this is not the point here. The point is to fail to inform developers that the way they tried doesn't work.)

**Comment by bert-w** [comment]
> "Dropping or modifying multiple columns within a single migration while using a SQLite database is not supported."

https://laravel.com/docs/5.8/migrations#dropping-columns

**Comment by mathieutu** [comment]
Yeah @bert-w I know, and it's not the point here. 
Actually dropping or modifying a column with **any other operation** is not supported.

**Comment by driesvints** [comment]
Please fill out the issue template with proper versions.

**Comment by mathieutu** [comment]
@driesvints Done, even if it has no relation with any version.
(As far I know the issue seems present from the beginning of Laravel, and is not linked to php or sqlite versions.)

**Comment by driesvints** [comment]
@mathieutu using different calls is twtg. I've had to do that myself always as well. If you think the docs should be more clear here feel free to send in a PR!

**Comment by mathieutu** [comment]
Ok. It was not about the doc, but throwing an exception in code. 
So I'll do a PR. 🤷‍♂
