### ISSUE TITLE
Multidimensional array in Illuminate\Support\MessageBag

### ISSUE THREAD

**Issue by Vinimaks** [laravel/framework#32075]
- Laravel Version: 5.7.x-7.x
- PHP Version: 4.0.1-7.4

### Description:
`Illuminate\Support\MessageBag` does not support multidimensional errors. I guess that because of using PHP `array_unique` in the constructor method.

### Steps To Reproduce:
        $errors = [
            'sigup' => [
                "country" => [
                    "The country must be a string."
                ],
                "zip" => [
                    "Zip code is required"
                ]
            ]
        ];

       new \Illuminate\Support\MessageBag($errors);

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by idezigns** [comment]
Not sure why they would close this, but what you are looking to achieve is simple, just use

$errors->getMessages()
