### ISSUE TITLE
Problem with Laravel and PHP

### ISSUE THREAD

**Issue by miranwarwtc** [laravel/framework#32074]
- Laravel Version: #.#.# //How do I find this?
- PHP Version: 7.1.23
- Database Driver & Version: //Not sure on this as well

### Description:
I'm trying to run Laravel, but I am getting some errors.

### Steps To Reproduce:
First, I run: "create-project laravel/laravel –-prefer-dist" and all is fine.

Second, I run: "composer create-project laravel/laravel test dev-develop" and I get the following error: "[InvalidArgumentException]Could not find package laravel/laravel with version dev-develop in a version installable using your PHP version 7.1.23."

Sorry, I am new to Laravel and have tried looking around already on various forums and have been unable to find a solution so far. Please let me know if you have any suggestions. Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
