### ISSUE TITLE
src/Illuminate/Encryption/Encrypter.php: openssl_cipher_iv_length not found

### ISSUE THREAD

**Issue by Indianos** [laravel/framework#32080]
- Laravel Version: 6.18.2
- PHP Version: 7.4.4
- Database Driver & Version: MariaDB 10.4.x?

### Description:
As soon as I moved to php7.4 the Encrypter class is producing error:
`Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length()` on line 84

### Steps To Reproduce:
I don't know which function excatly calls this (couldn't catch it in backtrace) but here's code of working with cookies:
**app/Providers/RouteServiceProvider.php:**
```php
$lang = \cookie('user_lang', session()->get('user_lang') ?? Cookie::get('user_lang') ?? config('app.locale'), 60 * 24 * 30);
Cookie::queue($lang);
$this->app->setLocale($lang->getValue());
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
