### ISSUE TITLE
Scheduler only run once

### ISSUE THREAD

**Issue by Naghal** [laravel/framework#32089]
- Laravel Version: 6.15.0
- PHP Version: 7.4.3
- Database Driver & Version: sqlsrv

### Description:
With the combination of the following scheduler config and job, the scheduler will only run once, then it will always state afterward that  `No scheduled commands are ready to run`.

### Steps To Reproduce:
1. Create a Job which implements ShouldQueue
2. Create a command with the following code
```
<?php

namespace App\Console;

use Illuminate\Console\Command;
use App\Jobs\FetchEmails as FetchEmailsJob;

class FetchEmails extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'emails:fetch';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Fetches emails and creates Ticket & TicketMessage';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        FetchEmailsJob::dispatch();
    }

}
```
3. Configure the scheduler as following
```
$schedule->command('emails:fetch')
         ->everyMinute()
         ->withoutOverlapping()
         ->emailOutputOnFailure('email@armcanada.ca');
```
4. Run the queue worker and the scheduler
`php artisan queue:work --tries=2` `php artisan schedule:run`
**Notice that the command and the job are processed once.**
5. Run the scheduler after a couple minutes
**Notice the output `No scheduled commands are ready to run`**
6. Remove the following line from the scheduler config `->withoutOverlapping()`
7. Run the scheduler
**Notice that this time it is running the command and the job is processed**

Since the job is processed and completed, `withoutOverlapping` should not block the next occurence of the command.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
