### ISSUE TITLE
Custom Casting Bug - getOriginal returns incorrect value for attribute with custom casting because of classCastCache

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#32083]
- Laravel Version: 7.2.2
- PHP Version: 7.4.2
- Database Driver & Version: Mysql 8

### Description:

I have an attribute with a custom cast. If I already retrieved that attribute, the casted value is cached in classCastCache. If I then update the attribute's value and request the original value, I still receive the old value.

This is caused by the `getClassCastableAttributeValue` only using the key and not the value to determine if the cached value can be returned

```php
protected function getClassCastableAttributeValue($key)
{
    // This should not only use the key, but also the raw value
    if (isset($this->classCastCache[$key])) {
        return $this->classCastCache[$key];
    } else {
        $caster = $this->resolveCasterClass($key);

        return $this->classCastCache[$key] = $caster instanceof CastsInboundAttributes
            ? $this->attributes[$key]
            : $caster->get($this, $key, $this->attributes[$key] ?? null, $this->attributes);
    }
}
```

### Steps To Reproduce:

- Add custom cast to User model

```php
class User extends Model
{
    protected $casts = [
        'email' => EmailCast::class
    ]
}

class EmailCast implements CastsAttributes
{
    public function get($model, string $key, $value, array $attributes)
    {
        return $value;
    }

    public function set($model, string $key, $value, array $attributes)
    {
        return [$key => $value];
    }
}
```

- Create a user

```php
$user = factory(\App\User::class)->create(['email'=>'taylor@laravel.com'])
```

- Update the user's email

```php
$user->update(['email' => 'dries@laravel.com'])
```

- Get the user's original email. That should be 'taylor@laravel.com', but 'dries@laravel.com' is returned instead.

```php
$user->getOriginal('email') // returns 'dries@laravel.com', but should return 'taylor@laravel.com'
```

**Comment by driesvints** [comment]
I think I agree with you that this is a bug but I'm gonna let Taylor verify this first.

**Comment by taylorotwell** [comment]
->update() calls ->save() which calls ->syncOriginal(). That doesn't seem like a bug to me. The model has been saved and no longer has any "dirty" values.

**Comment by gdebrauwer** [comment]
But if you run `$user->getRawOriginal(‘email’)`, it does return ‘taylor@laravel.com’. So should `getOriginal(‘email’)` not return the same?

**Comment by driesvints** [comment]
That indeed seems a bug to me. I suspect something's off with the `$classCastCache` here.

**Comment by taylorotwell** [comment]
->getRawOriginal still returning `taylor@laravel.com` does seem like a bug. It should return `dries@laravel.com`

**Comment by ljjackson** [comment]
I've attempted to debug this and I've not been able to recreate this issue.

This is the diff for my tests vs a base install of Laravel, just to see if my tests aren't meeting the criteria of this issue.

https://github.com/ljjackson/laravel-issue-32083/compare/0.1.0...master

This is the diff for the 7.2.2 install of the Laravel framework.

https://github.com/ljjackson/laravel-issue-32083/compare/master...laravel-7.2.2

Environment: 
Laravel Version: 7.2.2 & 7.6.2
PHP Version: 7.4.4
Database Driver & Version: MySQL 8

The only thing different here is the PHP version.

**Comment by taylorotwell** [comment]
I can't recreate either. `getOriginal` returns the correct value for me. If someone finds a bug PRs are welcome.

**Comment by gdebrauwer** [comment]
I used the `getOriginal()` method in an observer, when the `syncOriginal()` method is not called yet. So my 'steps to reproduce' were not correct 😣

This is the correct (and easy) way to recreate the issue:

```php
$user = factory(\App\User::class)->create(['email'=>'taylor@laravel.com'])

$user->email = 'dries@laravel.com';

dump($user->getOriginal('email')); // returns 'dries@laravel.com', which is incorrect!
dump($user->getRawOriginal('email')); // returns 'taylor@laravel.com'
```

**Comment by taylorotwell** [comment]
Fixed.
