### ISSUE TITLE
Argument 1 passed to Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer::__construct() must be a boolean or a callable, string given

### ISSUE THREAD

**Issue by crazyfd** [laravel/framework#32107]
- Laravel Version: 7.2.2
- PHP Version: 7.4.1
- Database Driver & Version:

### Description:
Program exception,
`
[2020-03-25 21:52:52] production.ERROR: Argument 1 passed to Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer::__construct() must be a boolean or a callable, string given. {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Symfony\\Component\\ErrorHandler\\ErrorRenderer\\HtmlErrorRenderer::__construct() must be a boolean or a callable, string given. at vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:49)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(389): Symfony\\Component\\ErrorHandler\\ErrorRenderer\\HtmlErrorRenderer->__construct('0')
#1 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(343): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionWithSymfony(Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException), '0')
#2 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(326): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionContent(Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#3 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(411): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse(Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#4 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(313): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#5 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(210): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#6 app/Exceptions/Handler.php(55): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException))
#9 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 vendor/fruitcake/laravel-cors/src/HandleCors.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#24 public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#25 {main}
"} 

`

**Comment by GrahamCampbell** [comment]
Please update your app.php file to cast to a boolean as per https://github.com/laravel/laravel/commit/5ddbfb845439fcd5a46c23530b8774421a931760.

**Comment by brainlet-ali** [comment]
What about Lumen where do I put it?

**Comment by paulcedo** [comment]
Lumen please. Help us to fix this issue too

**Comment by GrahamCampbell** [comment]
Fixed in https://github.com/laravel/lumen-framework/commit/6eb8ff55dde107afe138250a0dce71f0c800c492. Will be available on Tuesday 21st.

**Comment by GrahamCampbell** [comment]
In the meanwhile, Lumen users can publish the app.php config file and add a bool cast in there themselves.

**Comment by Bharat-B** [comment]
@GrahamCampbell this doesn't solve it in laravel 9
