### ISSUE TITLE
Session driver array

### ISSUE THREAD

**Issue by finndev** [laravel/framework#32108]
- Laravel Version: 7.3.0
- PHP Version: 7.4.0

### Description:

We have set the session driver to `array` to prevent the `Set-Cookie` header from being added to the response to properly cache content. This worked during Laravel 6.x but this change broke everything:

> The array session driver data is now persistent for the current request. Previously, data stored in the array session could not be retrieved even during the current request.

The documentation has also not been updated here:

https://laravel.com/docs/master/session#configuration

There, it still says that the session is NOT persistent.

>  sessions are stored in a PHP array and will not be persisted.

The question now is, how do we stop Laravel from adding the `Set-Cookie: laravel_session...` header? Setting the driver to `array` seems to not work anymore.

**Comment by finndev** [comment]
For those having the same issue, I have temporarily fixed it by changing the StartSession Middleware function `sessionIsPersistent` to:

```
return ! in_array($config['driver'], [null, 'array']);
```

**Comment by driesvints** [comment]
I can't reproduce this. The session isn't persistent for me when using the array driver.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by finndev** [comment]
@driesvints 

1) Use latest Laravel 7.4.0
2) Set the session driver to `array`
3) Disable the CSRF Middleware
4) Do a request to your Laravel site. The "laravel_session" cookie will get set making the session persistent.

**Comment by AntonKucheriavyi** [comment]
Any ideas, how fix it? Because we also have this in Laravel 7
