### ISSUE TITLE
Ambiguities in array eloquent casting

### ISSUE THREAD

**Issue by et-nik** [laravel/framework#32117]
- Laravel Version: 6.x/7.x
- PHP Version: 7.2. Actual on 7.3, 7.4
- Database Driver & Version: MySQL 5.6/MariaDB 10

### Description:

Array casting not working as I'm expecting.
I expect that invalid json string to be converted to an array or an exception to be thrown. But invalid json converts to string.

Invalid json `string(2) """"` converted to empty string.

This happens because json_decode convert some invalid json to ambiguities value. Example:
```php
$string = '""';
var_dump(json_decode($string, true)); // string(0) ""
```

Json string to array casting uses `json_decode` without any checks.
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L809

### Steps To Reproduce:

* Create some database entity

Migration:
```php
Schema::create('foo', function (Blueprint $table) {
    $table->increments('id');
    $table->string('payload');
});
```

Model:
```php
class Foo extends Model
{
    public $timestamps = false; 

    protected $casts = [
        'bar' => 'array'
    ];
}

```

* Insert new row to database with invalid json:

```sql
INSERT INTO `foo` (`bar`) VALUES ('""');
```

* Find element and read bar property

```
$foo = App\Foo::find(1);

var_dump($foo->bar); // Expects array but given empty string
```

**Comment by driesvints** [comment]
I think I agree with you that this is a bug. I've pinged @taylorotwell about this.

**Comment by driesvints** [comment]
We agree that this seems like a bug. Appreciating a PR if you could make one.

**Comment by et-nik** [comment]
Okay. I'll try to make PR.

I want to add that `string(2) """"` is valid json but converted to empty string.
I think that `fromJson` method ([HasAttributes.php#L807](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L807)) should return only array or object value.

**Comment by et-nik** [comment]
I found another example of this strange casts:
```
class Foo extends Model
{
    public $timestamps = false; 

    protected $casts = [
        'bar' => 'array'
    ];
}
```

```
$foo = new Foo;
$foo->bar = 'string';  // Something went wrong and for some reason a string got here
$foo->save();

$foo = Foo::find(1);
echo $foo->bar; // string? Why it is string?
```

**Comment by driesvints** [comment]
Please see Taylor's response on the PR.

**Comment by et-nik** [comment]
@driesvints at first we said that the bug should be fixed. I spent time on fix and tests, and Taylor closed PR and did not even write any details why it is not bug. I am dissatisfied with this.

**Comment by driesvints** [comment]
@et-nik Taylor gave an explanation why this isn't a bug.
