### ISSUE TITLE
Inbound custom cast generates PHP notices when setting values to null on new model instances

### ISSUE THREAD

**Issue by wfeller** [laravel/framework#32111]
- Laravel Version: 7.3.0
- PHP Version: 7.4.3
- Database Driver & Version: n/a

### Description:

When using inbound custom casts, and setting a value to null on an empty model, we get PHP notices of undefined index.

Setting a null initial value will try to retrieve the current value by doing `$this->attributes[$key]`, but since `$this->attributes[$key]` does not exist yet, we get a PHP notice.

In `HasAttributes->getClassCastableAttributeValue()`, it can be solved by changing the following:

```php
   return $this->classCastCache[$key] = $caster instanceof CastsInboundAttributes
                ? $this->attributes[$key]
                : $caster->get($this, $key, $this->attributes[$key] ?? null, $this->attributes);
```

Into:
```php
   return $this->classCastCache[$key] = $caster instanceof CastsInboundAttributes
                ? ($this->attributes[$key] ?? null)
                : $caster->get($this, $key, $this->attributes[$key] ?? null, $this->attributes);
```

### Steps To Reproduce:

```php
class User extends Authenticatable
{
    protected $casts = ['name' => Uppercase::class];
}
```

```php
class Uppercase implements CastsInboundAttributes
{
    public function set($model, string $key, $value, array $attributes)
    {
        return is_string($value) ? strtoupper($value) : $value;
    }
}
```

```php
$user = new User;
$user->name = null;
```
<img width="343" alt="image" src="https://user-images.githubusercontent.com/21337627/77564174-94f4bf80-6ec2-11ea-9e73-d2eb826df78b.png">

**Comment by driesvints** [comment]
Indeed seems a bug to me. Can you send in a PR?

**Comment by driesvints** [comment]
Sent in a pr: https://github.com/laravel/framework/pull/32118

**Comment by wfeller** [comment]
Thanks!
