### ISSUE TITLE
if input is integer .. then function should return type integer 

### ISSUE THREAD

**Issue by MinaZakaria** [laravel/framework#32110]
https://github.com/laravel/framework/blob/5042846eb0bdd0ade2e760015b1e5c57013225d5/src/Illuminate/Http/Concerns/InteractsWithInput.php#L129

if rules contains integer `id`
```php
public function rules()
    {
        return [
            'id' => 'required|integer',
        ];
    }
```
then `$request->input('id');` should return integer
but input method here expects `@return string|array`

**Comment by GrahamCampbell** [comment]
The integer validator doesn't check if something is an integer type necessarily, it confirms it is a string that looks like an integer.

**Comment by MinaZakaria** [comment]
phpstan static analysis tool fails as it expects the return type to be integer but input type expects `@return string|array`
