### ISSUE TITLE
Http facade keeps the reference to Response

### ISSUE THREAD

**Issue by sergiz** [laravel/framework#32124]
- Laravel Version: 7.2.2
- PHP Version:7.2.24
- Database Driver & Version: n/a

### Description:
When using the new Http facade, the reference to Guzzle's response is kept somewhere, so the tmp file that it (might) create doesn't get removed automatically before the script completely ends. This is not a problem for HTTP requests, but it is when using the Http facade in an artisan command..

When you forcefully stop the execution (for example with Ctrl+C) the PHP won't delete temp files it created. If you used Http facade anywhere in your artisan command (and it created any temp files) they will be left behind.
Now, if you use Guzzle library directly, everything will work fine because unsetting reference to the response, will also get the temp file deleted. On the other hand, with Http facade, when you unset the reference to the response it returned, nothing will happen.

### Steps To Reproduce:
```
$response = Http::get('https://api.github.com/repos/laravel/framework/releases/latest');
unset($response);
// The reference to the response still exists somewhere, temp file is not deleted.
```

**Comment by driesvints** [comment]
Seems like a bug to me as well. Appreciating prs for this.

**Comment by nuernbergerA** [comment]
I can look into this

**Comment by nuernbergerA** [comment]
Hi @sergiz
I tried to reproduce your issue but couldn't, maybe its OS related.

## Setup
* OS: Ubuntu 19.10
* PHP: 7.2.29 and 7.4.4
* Laravel: 7.2.2 and 7.5.2

## Steps to Reproduce
```bash
composer create-project --prefer-dist laravel/laravel test-http-client
cd test-http-client
php artisan make:command --command="test:http" TestHttpClient
```

Modify `app/Console/Commands/TestHttpClient.php`
```php
public function handle()
{
    // Simulate delay 3s
    $response = \Illuminate\Support\Facades\Http::get('http://slowwly.robertomurray.co.uk/delay/3000/url/https://api.github.com/repos/laravel/framework/releases/latest');
    unset($response);

    // Simulate other operations
    sleep(10);
}
```

Find PHP `tmp` path
```bash
php -r "echo sys_get_temp_dir();"
/tmp
```

Observe folder for changes (refresh every 0.1 seconds)
```bash
watch -d -n 0.1 ls -lah /tmp
```

Now we can run our `command`
```bash
php artisan http:test
# <Ctrl> + <C> within 3s or after 3s but within 13s
```

## Result
My `/tmp` had no PHP related files during the test.

Maybe someone else can try to reproduce it?

**Comment by driesvints** [comment]
@nuernbergerA thanks for helping out.

@sergiz feel free to respond with exact steps to reproduce and we'll have another look.
