### ISSUE TITLE
When I use the route cache, the prefix route binding parameters will report an error, so I trace the source code and modify it here is no problem

### ISSUE THREAD

**Issue by liujundezhanghao** [laravel/framework#32127]
- Laravel Version: 7.3.0
- PHP Version: 7.3.7
- Database Driver & Version:

### Description:

When I use the route cache, the prefix route binding parameters will report an error, so I trace the source code and modify it here is no problem

php artisan route:cache
![image](https://user-images.githubusercontent.com/20275621/77682155-6dd8e380-6fd1-11ea-9b93-805d5cd8502e.png)

![image](https://user-images.githubusercontent.com/20275621/77681739-c8257480-6fd0-11ea-9af1-aedc96b88036.png)

### Steps To Reproduce:

`Route::prefix('v1.2')->get('circle_category/{circle_category}', 'CircleController@circleCategoryMore'); //首页->圈子->更多`

php artisan route:cache

**Comment by driesvints** [comment]
Please post exact steps to reproduce.

**Comment by liujundezhanghao** [comment]
> Please post exact steps to reproduce.


1.Add a route 
`Route::prefix('v1.2')->get('circle_category/{circle_category}', 'CircleController@circleCategoryMore'); 
` 
 in api.php;
2. Command line execution  `php artisan route:cache`
3. Visit  [http://localhost/v1.2/api/circle_category/1'](url)

![image](https://user-images.githubusercontent.com/20275621/77759564-df676f00-706f-11ea-8e0a-5a5fd89eae93.png)

**Comment by driesvints** [comment]
Please post more code. Controllers, etc. There's not much to go on from here. Maybe a test app (commit custom changes separately).

**Comment by liujundezhanghao** [comment]
> Please post more code. Controllers, etc. There's not much to go on from here. Maybe a test app (commit custom changes separately).
You are right so i changed

**Comment by driesvints** [comment]
I see the problem but the solution from above breaks the tests so we'll need to look for a different one.

**Comment by liujundezhanghao** [comment]
Thank you, I hope to be resolved soon
