### ISSUE TITLE
VaporImage field gives 403 response both locally and when deployed on Vapor

### ISSUE THREAD

**Issue by devonmather** [laravel/framework#32137]
- Laravel Version: 7.3.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8
- Nova Version 3.1.0
- Laravel Sanctum 2.1.0 (Not sure how this could impact, but since it's new?)

### Description:
I have a VaporImage field that is giving a 403 response when i try to upload. I figure that maybe that's expected behaviour when running locally. So I deployed it to stage but having the same issue. I debugged it a little and it doesn't seem to be able to get past the following code block in `SignedStorageUrlController::store()`.

```
Gate::authorize('uploadFiles', [
    $request->user(),
    $bucket = $request->input('bucket') ?: $_ENV['AWS_BUCKET']
]);
```

### Steps To Reproduce:

Add Vapor Field
```
VaporImage::make('Logo')->maxWidth(200)
                ->hideFromIndex(),
```

Then deploy and try to upload and image, and get following response.

<img width="1440" alt="Screenshot 2020-03-27 at 19 39 31" src="https://user-images.githubusercontent.com/3239389/77789418-40d51100-7063-11ea-8d5a-723433d7842f.png">

And when I run it locally, I get the following response.
```
{
    "message": "This action is unauthorized.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
    "file": "/Users/devonmather/Projects/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 224,
```

**Comment by driesvints** [comment]
Please open up a ticket with vapor support.

**Comment by kennyhorna** [comment]
@devonmather Hi, did you find a solution for this? I'm experiencing the same using Nova + VaporImage. (I tried to find a similar issue in one of the Vapor repos but find nothing)

**Comment by devonmather** [comment]
@kennyhorna I haven't had any luck getting it to work. Regarding this particular issue you may need to add a UserPolicy for uploads to work, this is mentioned in the docs. However even after doing so I was still having issues. So I commented out the fields for now, as support was unable to help with the error I was having.

<img width="333" alt="Screenshot 2020-04-22 at 12 29 00" src="https://user-images.githubusercontent.com/3239389/79972663-9a7c0000-8496-11ea-9b20-350adc132029.png">

**Comment by clayzar** [comment]
I was having the same issue. I did some investigation and this is what I discovered.

I noticed that the user was empty in the method
`Laravel\Vapor\Http\Controllers\SignedStorageUrlController::store`

`
Gate::authorize('uploadFiles', [
            $request->user(), // This was empty
            $bucket = $request->input('bucket') ?: $_ENV['AWS_BUCKET']
        ]);
`

In the past I've found this means that the authentication middleware was not ran.

So I found where the route was defined: `Laravel\Vapor\DefinesRoutes`. The only middleware was `web`. I listed the routes `php artisan route:list` and found that there are several other middleware for the nova routes. (Routes beginning with `/nova` by default, in my case I had changed my nova path to `/admin`). So I added the copied that middleware for nova and added it to the middleware for the vapor route definition:

`
            \Laravel\Nova\Http\Middleware\Authenticate::class,
            \Laravel\Nova\Http\Middleware\DispatchServingNovaEvent::class,
            \Laravel\Nova\Http\Middleware\BootTools::class,
            \Laravel\Nova\Http\Middleware\Authorize::class,
`

This fixed my issue, but this is obviously not a true solution as it modifies third-party code. I'm trying to understand if there's a way to apply this middleware to the route in my own application code. Even if I could, I think I may be missing something obvious here, since other users are not having this issue. 

It's also worth noting that, in my case, I'm not using the default authentication guard.  I have an `admin` guard that is authenticated with an `Admin` model, instead of the `User` model.

I'll provide any new findings later.

**Comment by clayzar** [comment]
When I switch my authentication guard for nova to the default, it works perfectly fine. The `$request->user()` is populated and the authorization passes. Switching back to my `admin` guard causes the 403 again, because of an empty `$request->user()` 🤔

**Comment by kennyhorna** [comment]
> @devonmather Hi, did you find a solution for this? I'm experiencing the same using Nova + VaporImage. (I tried to find a similar issue in one of the Vapor repos but find nothing)

In my case the error was that I hadn't installed the aws dependency lol 🤦‍♂️. I discovered that the next morning (I know, it was the lack of sleep). It's now working properly.

**Comment by andresilvagomez** [comment]
I found this solution 

Gate::define('uploadFiles', 'App\Policies\UserPolicy@uploadFiles');

**Comment by ibrahim-mubarak** [comment]
I had to extend the default VaporServiceProvider with the middlewares required by Nova and disabled the default VaporServiceProvider

composer.json
```json
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/vapor-core"
            ]
        }
    },
```

VaporServiceProvider.php
```php

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use Laravel\Nova\Http\Middleware\Authenticate;
use Laravel\Nova\Http\Middleware\Authorize;
use Laravel\Nova\Http\Middleware\BootTools;
use Laravel\Nova\Http\Middleware\DispatchServingNovaEvent;
use Laravel\Vapor\Http\Controllers\SignedStorageUrlController;
use Laravel\Vapor\VaporServiceProvider as ServiceProvider;

class VaporServiceProvider extends ServiceProvider
{
    /**
     * Ensure that Vapor's internal routes are defined.
     *
     * @return void
     */
    public function ensureRoutesAreDefined()
    {
        if ($this->app->routesAreCached()) {
            return;
        }

        Route::post(
            '/vapor/signed-storage-url',
            SignedStorageUrlController::class . '@store'
        )->middleware([
            'web',
            Authenticate::class,
            DispatchServingNovaEvent::class,
            BootTools::class,
            Authorize::class,
            Authorize::class,
        ]);
    }
}
```

I still don't like this very much though

**Comment by kchoppin** [comment]
I was having a similar issue with a custom guard. Overwriting the packages route with my custom guards auth middleware worked for me.

`Route::post('/vapor/signed-storage-url',[\Laravel\Vapor\Http\Controllers\SignedStorageUrlController::class, 'store'])->middleware('auth:admin');`

**Comment by nenads** [comment]
How do you pick file after from tmp ? if used with nova

{message: "File not found at path: ", exception: "League\Flysystem\FileNotFoundException",…}
exception: "League\Flysystem\FileNotFoundException"
file: "/var/www/html/vendor/league/flysystem/src/Filesystem.php"
line: 389
message: "File not found at path: "
trace: [{file: "/var/www/html/vendor/league/flysystem/src/Filesystem.php", line: 223,…},…]

**Comment by michavie** [comment]
Made a PR in the core package for this - so you don't have to use your temporary workarounds:
https://github.com/laravel/vapor-core/pull/78

**Comment by Jaspur** [comment]
@michavie still occurring over here..

```
ERROR  Time : 2021-01-19 11:32:39

File not found at path: tmp/688d117c-32e3-41c0-8c14-4d60d94da6f8 {"userId":2,"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: tmp/688d117c-32e3-41c0-8c14-4d60d94da6f8 at /tmp/vendor/league/flysystem/src/Filesystem.php:389)
```

@nenads did you found a fix?

**Comment by michavie** [comment]
@Jaspur The PR to let you configure the route's middleware for has been merged into vapor-core but not yet released

**Comment by zachu90** [comment]
> I was having a similar issue with a custom guard. Overwriting the packages route with my custom guards auth middleware worked for me.
> 
> ```
> Route::post(
>     '/vapor/signed-storage-url',
>     [\Laravel\Vapor\Http\Controllers\SignedStorageUrlController::class, 'store']
> )->middleware('auth:admin');
> ```

This works perfectly, thanks !

**Comment by pmreyes** [comment]
> @michavie still occurring over here..
> 
> ```
> ERROR  Time : 2021-01-19 11:32:39
> 
> File not found at path: tmp/688d117c-32e3-41c0-8c14-4d60d94da6f8 {"userId":2,"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: tmp/688d117c-32e3-41c0-8c14-4d60d94da6f8 at /tmp/vendor/league/flysystem/src/Filesystem.php:389)
> ```
> 
> @nenads did you found a fix?

@Jaspur - was wondering if you've resolved this? I'm having the same issue
