### ISSUE TITLE
Undefinex index: driver

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#32130]
- Laravel Version: 6.18.3
- PHP Version: 7.4.4
- Database Driver & Version: irrelevant

### Description:

I believe this is a bug. Following code will throw exception if 2fa.dsn is not set (it works otherwise). It probably should throw, but I would expect a different exception.
```
  Config::set('database.connections.2fa', ['url' => \config('2fa.dsn')]);
  return DB::connection('2fa');
```
Here's the error:
```
 ErrorException  : Undefined index: driver 

 at /home/mike/Work/hkccp/kolab/src/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php : 127 
   123|   
   124|          // Next we will check to see if an extension has been registered for a driver 
   125|         // and will call the Closure if so, which allows us to have a more generic 
   126|         // resolver for the drivers themselves which applies to all connections. 
 > 127|          if (isset( $this -> extensions [ $driver = $config [ 'driver' ]])) { 
   128|             return call_user_func ( $this -> extensions [ $driver ], $config , $name ); 
   129|         } 
   130|   
   131|         return $this -> factory -> make ( $config , $name ); 

 Exception trace: 
1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: driver", "/home/mike/Work/hkccp/kolab/src/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php", ["2fa"])                                                 
     /home/mike/Work/hkccp/kolab/src/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php : 127 

 2    Illuminate\Database\DatabaseManager::makeConnection("2fa") 
     /home/mike/Work/hkccp/kolab/src/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php : 86 

 3    Illuminate\Database\DatabaseManager::connection("2fa") 
     /home/mike/Work/hkccp/kolab/src/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php : 261 
...
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by alecpl** [comment]
WTF people with you? Is "I believe this is a bug." not strong enough? Is exception trace not enough? Or this is your normal way of handling tickets. Let's close the ticket immediately and see if it's really important to the user so he comes back and asks? Are you a robot? No, it is not that important for me, I hoped it would be for you.

**Comment by lk77** [comment]
Well your code is not correct

**Comment by carlosed1995** [comment]
> Well your config is not correct, missing driver at least, see an example here : https://github.com/laravel/laravel/blob/8d3a964edc67125f336f14ccfca31b62623bca65/config/database.php

@lk77 Tanks, that congiration working for me
