### ISSUE TITLE
The command `make:test` works incorrectly with prefix `Tests` and postfix `.php`

### ISSUE THREAD

**Issue by denis-korchagin95** [laravel/framework#32136]
- Laravel Version: 7.2.2
- PHP Version: 7.2.24
- Database Driver & Version: n/a

### Description:

1) When I create a test with prefix `Tests` laravel created it in the project root directory. It is incorrect, I mean. Because I have a model called `Test` and also `TestsController.php`.
It's really confusing...

2) The second one: postfix `.php` in the name of the test also not handled correctly.
If I write `php artisan make:test TasksTest.php` it would be nice to automatically delete the last `.php` substring in the test's name.

### Steps To Reproduce:

1) `php artisan make:test TestsTest.php` and you should see a file called `testsTest.php` in the project root directory.

2) `php artisan make:test TasksTest.php` and you should see a file called `TasksTest.php.php` in the right place but with the wrong name.

**Comment by driesvints** [comment]
We don't support the `.php` suffix and generally you end your PHPUnit test classes with `Test`, not start them.

**Comment by denis-korchagin95** [comment]
> We don't support the `.php` suffix and generally you end your PHPUnit test classes with `Test`, not start them.

Ok, but my model entity called `Test` and the behaviour of `make:test` a little weird...
