### ISSUE TITLE
Issue with clearing the database after executing the tests

### ISSUE THREAD

**Issue by Saneesh** [laravel/framework#32147]
- Laravel Version: 7.2.0
- PHP Version: 7.3.16-1+ubuntu19.10.1+deb.sury.org+1
- Database Driver & Version: sqlite 2.8.17

Laravel application and PHPUnit are using sqlite as database.

For the development in my local I have configured as follows
```
// .env
DB_CONNECTION=sqlite
DB_DATABASE=/path/to/db.sqlite
```
```
// phpunit.xml
<server name="DB_CONNECTION" value="sqlite"/>
<server name="DB_DATABASE" value=":memory:"/>
```
(No changes in phpunit.xml from my side)

Step 1: Register a user and login/logout 
Step 2: Add some test cases and execute it
Step 3: Try to login, it shows an error message: `SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from "users" where "id" = 1 limit 1)`

After executing the tests the existing tables are removed from the `sqlite` database even though the test's database is in `memory`

I have tried with `./vendor/bin/phpunit` and `php artisan test`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
