### ISSUE TITLE
Route Model Scoping needs route key to work

### ISSUE THREAD

**Issue by bkintanar** [laravel/framework#32144]
- Laravel Version: 7.3.0
- PHP Version: 7.4.4
- Database Driver & Version:

Mysql 5.7.29-0ubuntu0.18.04.1 (homestead)

### Description:

The implicitly binding multiple eloquent models in a single route and scoping the second model doesn't work out of the box. You need to specify the route key name ({post:id}) for it to work.

Shouldn't it use the `id` if no custom key has been set?

So for me to auto scope the second eloquent model, I need to say `users/{user}/posts/{post:id}` even if I'm just using the default route key name.

Source: Laravel docs ⤵️ 

<img width="683" alt="Routing_-_Laravel_-_The_PHP_Framework_For_Web_Artisans" src="https://user-images.githubusercontent.com/685928/77818490-c1e8e280-710d-11ea-9352-1c8047cd4595.png">

### Steps To Reproduce:

```php

class User extends Model
{
	public function posts()
	{
		$this->hasMany(Post::class);
	}
}


Route::get('users/{user}/posts/{post}', function (User $user, Post $post) {
	dd($post);
});
```

Even if the $post doesn't belong to the $user, it will still show.

**Comment by browner12** [comment]
What if you don't want it to scope?

**Comment by bkintanar** [comment]
@browner12 fair point, but that doesn't what the docs says. Docs says "**Laravel will automatically scope the query to retrieve the nested model by its parent** ..."

**Comment by browner12** [comment]
You missed the first part of that sentence.

> When using a custom keyed implicit binding as a nested route parameter, Laravel will automatically scope

***When*** using a custom...

**Comment by bkintanar** [comment]
I still think it would auto scope out of the box.

**Comment by driesvints** [comment]
@browner12 thanks for confirming that.

@bkintanar we're open to prs.
