### ISSUE TITLE
`php artisan make:component Namespace/Subcomponent` creates wrong `render` function

### ISSUE THREAD

**Issue by PHPGuus** [laravel/framework#32155]
Laravel: 7.3.0
PHP: 7.3.16
Database Driver & Version: N/A

### Description
Even though #32009 and #32030 mention that this is fixed, it isn't.

When running `php artisan make:component Namespace/Subcomponent` the generated `render()` function returns `view('components.test')` as opposed to `view('components.namespace.test')`. The blade file is created in the correct location "resources/views/components/namespace/test.blade.php".

I am attempting a PR for this against the 7.x branch.

###Steps to reproduce
`php artisan make:component Namespace/Test`

**Comment by PHPGuus** [comment]
PR is on its way: #32156

**Comment by innoflash** [comment]
Fixed here and merged. https://github.com/laravel/framework/pull/32132

**Comment by PHPGuus** [comment]
Weird, because I pulled the latest 7.x branch, and your fix was not in it...

**Comment by innoflash** [comment]
I think its because its not yet in the latest tag but definitely in master

**Comment by PHPGuus** [comment]
Well, the main branch for PR-ing against is 7.x, so that's where I looked ;-)

**Comment by innoflash** [comment]
Last time i checked all PR are supposed to happen in the the master. The 7.x must just be a default set for packagist

**Comment by PHPGuus** [comment]
Maybe there's conflicting information out there...

From https://laravel.com/docs/7.x/contributions#which-branch:
"All bug fixes should be sent to the latest stable branch or to the current LTS branch. Bug fixes should never be sent to the master branch unless they fix features that exist only in the upcoming release."

At any rate, we both came to the same conclusion... Brilliant minds and all that ;-)

**Comment by GrahamCampbell** [comment]
That's because it was actually merged into 8.x. The contributor misslablled the PR...

**Comment by driesvints** [comment]
Looks like Graham has already ported this to the 7.x branch. Will be in tomorrow's release.
