### ISSUE TITLE
Illuminate\Foundation\Auth\ConfirmsPasswords removed without any information

### ISSUE THREAD

**Issue by CreativeBulma** [laravel/framework#32162]
- Laravel Version: 7.3
- PHP Version: 7.4.4

### Description:
Illuminate\Foundation\Auth\ConfirmsPasswords has been removes since v6.X without any information about it. Documentation mention that _All authentication scaffolding has been moved to the laravel/ui_. But it does not contains any `ConfirmsPasswords` trait. And what if we don't want to use the UI scaffolding ?

**Comment by CreativeBulma** [comment]
Same with `Illuminate\Foundation\Auth\RedirectsUsers`.
Where can we find them now ?

**Comment by devcircus** [comment]
All of those traits are in the ui package
