### ISSUE TITLE
Inconsistent queue documentation

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/framework#32168]
- Laravel Version: 5.X, 6.X, 7.X
- PHP Version: -
- Database Driver & Version: -

### Description:

In the documentation, under [Driver Notes & Prerequisites](https://laravel.com/docs/7.x/queues#driver-prerequisites) > Redis Cluster, it is mentioned that Redis queue names should use key hash tags (`'{default}'`). However, in the rest of the documentation, all config examples for Redis simply use the name `'default'`. I am currently using `'default'`, and that seems to work fine.

So currently I have no idea if I should use `'default'` or `'{default}'`, or if it doesn't matter at all. Because I don't know what's correct, I can't make a PR to fix this.

### Steps To Reproduce:

.

**Comment by driesvints** [comment]
Just send in a pr please with `default`. Taylor will update it if it needs to be switched.
