### ISSUE TITLE
Class illuminate\<random> wasn't preloaded

### ISSUE THREAD

**Issue by Thor-x86** [laravel/framework#32163]
- Laravel Version: 6.18.3
- PHP Version: 7.4.4
- Database Driver & Version: MySQL 8.0 (InnoDB engine)
- Nginx Version: 1.16.1

### Description:
Sometimes Laravel throws exceptions as title above. The class is random on every modification at app side even though there is no error at app's source code (I have checked several times). I'm sure this bug caused by unimplemented new feature on PHP 7.4 called [preload](https://wiki.php.net/rfc/preload) because the error never exist at my company's server (which is using PHP 7.3).

### Steps To Reproduce:
1. Use fresh Ubuntu 18 LTS installation
2. Install PHP 7.4, [all PHP dependencies](https://laravel.com/docs/6.x/installation#server-requirements), PHP7.4-FPM, MySQL 8.0, [Nginx 1.16](https://www.nginx.com/resources/wiki/start/topics/tutorials/install/), redis-server, and memcached.
3. Configure MySQL, php.ini, Nginx, and Redis.conf
4. Clone the git
5. Create .env based on configuration
6. Run `composer install;composer update;php artisan key:generate`
7. Run `php artisan migrate;php artisan passport:install;php artisan db:seed;php artisan storage:link`
8. Run `npm install;npm run dev`
9. Start php7.4-fpm and nginx service
10. Go explore the website until error occur, try restart php7.4-fpm and nginx service several times.

### Screenshot:
![Annotation 2020-03-30 043151](https://user-images.githubusercontent.com/30412448/77861501-8a7a5300-723f-11ea-87e8-2dfcab4293fe.jpg)

**Comment by mo3000** [comment]
It doesn't show up in my mac, PHP 7.4.4 (cli) (built: Mar 19 2020 20:12:27) ( NTS ). The preload feature requires some script in your project and I think it couldn't be enabled by default.

**Comment by driesvints** [comment]
We don't support preloading at the time. This blog post might interest you: https://stitcher.io/blog/preloading-in-php-74

**Comment by SlyDave** [comment]
I get this issue occasional too, random file failing, preloading hasn't been enabled or configured (same as OP).

Laravel 8.25.0

nginx version: nginx/1.18.0 (Ubuntu)

PHP 7.4.14 (fpm-fcgi) (built: Jan 13 2021 08:04:47)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

Restarting php-fpm resolves the issue for me until it appears again, doesn't seem to be  Laravel problem, but maybe a php-fpm problem - why is it trying load from the preloaded classes if it isn't configured to preload...
