### ISSUE TITLE
Running artisan db:seed finishes with: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given

### ISSUE THREAD

**Issue by nekromoff** [laravel/framework#32167]
- Laravel Version: 5.8
- PHP Version: 7.4
- Database Driver & Version: n/a

### Description:
Running artisan db:seed finishes with: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given

### Steps To Reproduce:
Use some config/xxx.php file with instruction calling `asset`:
`'name'  => '<img src="' . asset('images/some.png') . '" width="20"> XYZ',`

Laravel will work correctly, however `artisan` will crash with the above mentioned error.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by lovecoding-git** [comment]
`asset()` helper can't be used in `config` file.

**Comment by shahalpk** [comment]
> `asset()` helper can't be used in `config` file.

This seems to be the problem. I am able to reproduce the issue in Laravel v7. 

@driesvints can you confirm if this is a bug / expected behaviour?

**Comment by lovecoding-git** [comment]
@shahalpk 

You can override config value in AppServiceProvider.
```

    public function boot()
    {
        config([
          'xxx.value' => '<img src="' . asset('images/some.png') . '" width="20"> XYZ'
       ]);
    }
```

**Comment by driesvints** [comment]
@shahalpk expected

**Comment by shahalpk** [comment]
@driesvints okie. but shouldn't the error message be more meaningful?

**Comment by precompiled** [comment]
> `asset()` helper can't be used in `config` file.

Neither can `url()`.

**Comment by nekromoff** [comment]
Same on v8.

**Comment by wildangunawan** [comment]
> > `asset()` helper can't be used in `config` file.
> 
> Neither can `url()`.

Neither can `route()` too.

**Comment by ZaeemNexgen** [comment]
dd

**Comment by ZaeemNexgen** [comment]
> @shahalpk
> 
> You can override config value in AppServiceProvider.
> 
> ```
> 
>     public function boot()
>     {
>         config([
>           'xxx.value' => '<img src="' . asset('images/some.png') . '" width="20"> XYZ'
>        ]);
>     }
> ```
