### ISSUE TITLE
Laravel Log not writing

### ISSUE THREAD

**Issue by bsod696** [laravel/framework#32166]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
Last time log file updated was on the same day i git clone my repo to my hosting server

### Steps To Reproduce:
supposedly whenever pages load or an error produced, error will be written o log file. I already change the permission to 777 on log file even the whole storage folder, issue still rise

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
