### ISSUE TITLE
HasManyThrough with different database connections

### ISSUE THREAD

**Issue by Naghal** [laravel/framework#32171]
- Laravel Version: 5.8.36
- PHP Version: 7.3
- Database Driver & Version: mssql

### Description:
When defining a `hasManyThrough` relationship, the `protected $connection` attribute is ignored.

### Steps To Reproduce:
Create the following models (Abbreviated code)
```php
class Resource extends Model
{
    protected $connection = 'tcollect'

    public function absences()
    {
        return $this->hasManyThrough('ARM\TargetHoraire\Absence', 'ARM\Tcollect\ICO\ICOExternalReference', 'RecordID', 'ResourceID', 'ID', 'ExternalKey');
    }
}
```

```php
class Absence extends Model
{
    protected $table = 'Absences';
    protected $connection = 'punch';
}

```

```php
class ICOExternalReference extends Model
{
    protected $table = 'ICOExternalReferences';
    protected $connection = 'tcollect';
}
```
Then call the relationship on the resource model
`$resource->absences;`

Notice that `ICOExternalReference` $connection attribute is ignored. It tries to use the ICOExternalReference from the `punch` connection.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Naghal** [comment]
Hi, I just updated to Laravel 6.18.3. The same problem occurs :/

**Comment by driesvints** [comment]
Please ask this on a support channel.

**Comment by Naghal** [comment]
It has been posted on stackoverflow, gets no response. Also, since this is a bug, I think it is more appropriate to report it as a bug.
