### ISSUE TITLE
Defining LOG in Job constructor throws Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by denischiciudean** [laravel/framework#32179]
- Laravel Version: 7.3.0
- PHP Version: 7.4.3
- Database Driver & Version: unrelated

### Description:
I have a job with different methods, and wanted to declare a logger for the entire job, and set it in the constructor. Kept throwing exceptions until I moved setting the logger to the handle method.

### Steps To Reproduce:
Create new Job. Set the constructor to `$this->log = \Log::channel('daily');`. Dispatch Job;
```
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;


class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->log = \Log::channel('daily');
    }

    private $log;

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        //$this->log->info("Hello world!");
    }
}
```
Moving the constructor statement to the handle method works.
```
  public function handle()
    {
        $this->log = \Log::channel('daily');
    }
```

**Comment by mo3000** [comment]
It's not a bug.
When a laravel Job is dispatched, it's serialized first and sent to a queue if a queue is set. And php doesn't know hot to serialize "$this->log" since it's a closure. You may define ____serialize and __unserialize to fix this or simply make $this->log to string like this:
```php
    public function __construct($channel = 'file')
    {
        $this->log = $channel;
    }

    private $log;

    public function handle()
    {
        Log::channel($this->log)->info('hello');
    }
```

**Comment by mfn** [comment]
What @mo3000 said: you've to view the job constructor / it's properties as the boundary from dispatching to execution which in between may have to go over a serialization process to cross e.g. the database, redis, etc.

AFAIK certain complex things support this out of the box because it's a common use, e.g. Eloquent models.

Otherwise try to keep simply/discrete values within the job and do they "heavy" stuff in `handle()`, i.e. on-demand when it's executed.
