### ISSUE TITLE
Password::broker() with existing email cause SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by masterix21** [laravel/framework#32174]
- Laravel Version: 7.3.0
- PHP Version: 7.4.2
- Database Driver & Version: mysql (v5.7.29)

### Description:
I have upgraded an application from Laravel 6 to 7.3, but now seems that something goes wrong with the Password Reset process: when I call Password::broker()->sendResetLink(...) with an existing email address, I get the following error:
`Illuminate/Database/QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as `null` where `email` = ?' at line 1 (SQL: delete from `password_resets` as `null` where `email` = admin@laravel.test)'`

I have another application that uses a fresh Laravel 7 installation, and it works: the bug seems to be caused by the upgrade. What could be?

### Steps To Reproduce:
`\Illuminate\Support\Facades\Password::broker()->sendResetLink(['email' => 'admin@laravel.test' ]);`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
