### ISSUE TITLE
`Str::is()` wildcard does not match new lines

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel/framework#32180]
- Laravel Version: 7.3.0
- PHP Version: 7.3.16
- Database Driver & Version: MySQL 5.7.29

### Description:
According to the docs `str_is` or `Str::is` is supposed to use asterisks as wildcards, but the internal regular expression uses the `u` (PCRE_UTF8) modifier without including the `s` (PCRE_DOTALL) modifier.

### Steps To Reproduce:

```
$match = Str::is(
    'test string*',
    "test string should match \n even \n with \r new \n\r lines"
);

// should be `true`
dump($match);
```

Result should resolve to `true`, but resolves to `false`

**Comment by driesvints** [comment]
Closing this since the pr was closed.
