### ISSUE TITLE
When response() is returned in controller the framework tries and fails to convert Response Factory to string

### ISSUE THREAD

**Issue by petar-rankovic-logeecom** [laravel/framework#32198]
- Laravel Version: v6.18.3
- PHP Version: 7.4.3
- Database Driver & Version:5.7.29-0ubuntu0.18.04.1

### Description:
When empty response with status 200 is returned the following exception is thrown:
[2020-04-02 09:51:56] local.ERROR: Object of class Illuminate\Routing\ResponseFactory could not be converted to string {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Object of class Illuminate\\Routing\\ResponseFactory could not be converted to string at /home/petar/Code/shopify/vendor/symfony/http-foundation/Response.php:409) 

### Steps To Reproduce:

1. Write a simple method in controller as follows:
public function test() {
return response();
}

2. Call the method from a web request.

3. The error is thrown as described.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by devcircus** [comment]
That's not how you return an empty response. Check out the response helper definition. When used with no arguments, it returns a response factory.
