### ISSUE TITLE
Blade component attributes with verbatim directive not passing properly.

### ISSUE THREAD

**Issue by rumrhky** [laravel/framework#32190]
Attribute with verbatim directive not passing properly.

```
 <x-inputs.text name="xxx"
                @verbatim :disabled="isNotWorking" @endverbatim
 >
</x-inputs.text>
```

I want to bind vue js code to blade component attribute bag.

Works fine before laravel 7.2.0, not working anymore after upgrade.

now outputs as below:
![image](https://user-images.githubusercontent.com/18545622/78112370-daaf0c00-741d-11ea-9896-c0dc091bd095.png)

Any solutions??

**Comment by driesvints** [comment]
This syntax isn't supported.

**Comment by keithbrink** [comment]
Quick suggestion for you, you can use `v-bind-disabled` as alternative syntax here.
