### ISSUE TITLE
Automatic model timestamps casts results unwanted toArray columns format

### ISSUE THREAD

**Issue by mkhinini-motaz** [laravel/framework#32195]
- Laravel Version: 7.3.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.2.31-MariaDB,

### Description:

Hello,

I am used to working with laravel 5.7 where i add **protected $dateFormat = 'U';** to have my "created_at" and "update_at" stored and read as timestamps, when **->toArray()**  is called on a model, the timestamps in the returned array maintain their values from the database.

However, with laravel 7.4, the result of the call to **->toArray()** converts my timestamps into dates and i get something like **2020-04-01T21:13:52.000000Z** instead of a valid timestamp.

I searched in the documentation and there is no indication of this change.

I solved this problem by overriding the **Illuminate\Database\Eloquent\Concerns\HasAttributes@addDateAttributesToArray** method to prevent it from converting timestamps to dates.

```
protected function addDateAttributesToArray(array $attributes)
{
    return $attributes;
}
```

I hope the maintainers of the framework would consider returning to the old behaviour where we are free to use dates or timestamps simply by defining an attribute : **protected $dateFormat = 'U';**

Thanks

**Comment by staudenmeir** [comment]
Did you see https://laravel.com/docs/7.x/upgrade#date-serialization?

**Comment by mo3000** [comment]
It's definitely in the document. Please refer to the latest document upgrade guide [https://laravel.com/docs/7.x/upgrade#date-serialization](url). It suggests:
```php
    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
```

**Comment by mkhinini-motaz** [comment]
Ok i admit i didn't see it, but still, i still have to define a method (like i did) in every model (or put it in a class and extend it from models) so that it can convert my dates back to timestamp. This is something i didn't have to worry about before.

```
protected function serializeDate(\DateTimeInterface $date)
{
    return $date->getTimestamp();
}
```

Don't you guys think this is a little messy, which is the reason that made me post this issue in the first place, not to find a solution (already got it) but to better structure my code.

With solution proposed by @mo3000 , in DB, dates are timestamps, on **->toArray()** call, they are converted to Date objects and then back to timestamps again the method i redefined. the solution i posted skips this whole process and leaves dates as retrieved from DB. 

Why is this cast couldn't just be optional or nonexistent like with previous versions of laravel ?

> Laravel is a web application framework with expressive, elegant syntax. We’ve already laid the foundation — freeing you to create without sweating the small things.

It is not the cases for dates anymore when you use timestamps.

**Comment by mo3000** [comment]
Http client library prefer current format. But I agree with you @mkhinini-motaz  difining a method for every model in your project is a little bit inconvenience. I wish it can be set in a global config file.
