### ISSUE TITLE
route() helper doesn't generate correct URI's for routes with a custom binding key

### ISSUE THREAD

**Issue by elbojoloco** [laravel/framework#32201]
- Laravel Version: 7.4.0 (since 7.0.0)
- PHP Version: 7.3.13
- Database Driver & Version: MySQL 5.7 (MariaDB)

### Description:
The `route()` helper doesn't account for the Laravel 7 way of specifying a custom route model binding key inside the route parameter when passing a Model to use implicit binding. It will generate the URL with ID's as parameters instead of the expected column (like a slug).

### Steps To Reproduce:
1. Create a route like this:
```
Route::get('/profile/{user:slug}', function (User $user) {
    return $user;
})->name('profile');
```
2. Try to generate a URI using the `route()` helper: `route('profile, $user)`
3. Inspect/view the given URI, it should look something like: `https://app.test/profile/1` instead of expected: `https://app.test/profile/@johndoe` (assuming the `slug` is `@johndoe`)

**Comment by driesvints** [comment]
I'd also expect that to work. Appreciating a PR if you could send one in.

**Comment by elbojoloco** [comment]
@driesvints I tried.. I got it working until I found out that my fix was not compatible with explicitly passing the parameter value (so passing `$user->slug` instead of `$user` as route() argument). I will link my commit, maybe someone can use it as inspiration: https://github.com/elbojoloco/framework/commit/d26bec650aff8242acecf6463d0091f0edf59964

**Comment by if4lcon** [comment]
you can set it in the model
```php
public function getRouteKeyName()
{
    return 'slug';
} ```

or 

```php
route('profile, ['slug' => $user])
```
