### ISSUE TITLE
Unable to locate aliased anonymous component view

### ISSUE THREAD

**Issue by Tylerian** [laravel/framework#32207]
- Laravel Version: 7.3.0
- PHP Version: 7.4.3

### Description:
When using `Blade::aliasComponent` to give an alias to an anonymous component, the alias is not registered and an exception is thrown.

### Steps To Reproduce:
1. Create an anonymous component view in an unconventional path. (eg: resources/views/ui/test.blade.php)
```html
@props(['foo', 'bar' = 'baz'])
<div>
{{ $foo }}
<br/>
{{ $bar }}
</div>
```
2. In your App service provider, aliase that component as 'test':
```php
/* AppServiceProvider.php */
Blade::aliasComponent('ui.test', 'test')
```
3. Call that component from a Blade view using the new Component syntax
```html
<div>
    <x-test :foo="'foz'" />
</div>
```

4. BOOM
```
Facade\Ignition\Exceptions\ViewException
Unable to locate a class or view for component [test].
```

**Comment by driesvints** [comment]
Use `Blade::component('ui.test', 'test')` instead.

**Comment by Tylerian** [comment]
> component

It works, thanks @driesvints !

I've thought `Blade::component` was only for class-based components as stated in the method description (`Register a class-based component alias directive.`)

Perhaps it should be clear in the docs that it also works for view based components?

**Comment by driesvints** [comment]
@Tylerian feel free to send in a PR 👍

**Comment by Tylerian** [comment]
@driesvints 
Wait your method doesn't work, I was testing the wrong deployment where I made a hotfix.

> @Tylerian feel free to send in a PR 👍

Will do!

**Comment by driesvints** [comment]
The above definitely works. I'm using it as such in several apps atm. Tried clearing your views?

**Comment by Tylerian** [comment]
> Tried clearing your views?

Whoops, my bad!!
