### ISSUE TITLE
Inconsistency between case in route–model binding and resource authorisation

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#32216]
- Laravel Version: 7.4.0
- PHP Version: 7.3.13
- Database Driver & Version: N/A

### Description:
There seems to be an inconsistency between what route–model binding is expecting and what resource authorisation is expecting when it comes to multi-word route parameters in a nested route.

Consider the following scenario: a tenant has many service providers. To get a single service provider for a tenant, I had a route like this:

```php
Route::get('tenants/{tenant:slug}/service-providers/{service_provider:slug}', 'Tenant\ServiceProviderController@show')->name('tenant.service_provider.show');
```

However, this throws an error saying it can’t find a `service_providers` method on my `Tenant` model when the router is trying to do the automatic scoping.

However, I _also_ use resource authorisation a lot in my controllers:

```php
public function __construct()
{
    $this->authorizeResource(ServiceProvider::class);
}
```

By default, `authorizeResource` expects multi-word parameters to be snake_case: https://github.com/laravel/framework/blob/db36649acc738ddba3c107b2c513c9125a3380a5/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L85

So which is it? snake_case or camelCase for multi-word parameters? It would be good if the framework set a convention for one or the other, instead of having different parts of code normalise parameters to different cases.

### Steps To Reproduce:
As above.

**Comment by driesvints** [comment]
Hmm yeah that doesn't seems to be wanted. I'll investigate.
