### ISSUE TITLE
laravel 5.8 verification email email/resend post method missing in route

### ISSUE THREAD

**Issue by umefarooq** [laravel/framework#32222]
- Laravel Version: 5.8.*
- PHP Version: 7.2.29

### Description:
When you "click here to request another" button on resend verification email i am getting this message "The POST method is not supported for this route. Supported methods: GET, HEAD." we have to change resend verification method from get to post i have check verification email route is  also generating get route.

### Steps To Reproduce:
need to modify Illuminate\Routing\Router

`$this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');`

need to be changed to

`$this->post('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');`

Right now i have added following route in my web.php which work fine.

`Route::post('email/resend','Auth\VerificationController@resend');`

**Comment by devcircus** [comment]
In 5.8, that route was a get request. In newer versions it changed to a post. You must be using routes from a different version than your stubs.

**Comment by umefarooq** [comment]
My mistake i down graded it from laravel 6 to 5.8 and did not noticed before. yes it is get in laravel 5.8.

**Comment by murph133** [comment]
Laravel Docs for upgrading to 6.0: https://laravel.com/docs/6.x/upgrade#email-verification-route

Changed from GET to POST request. Code provided.
