### ISSUE TITLE
Codes inside a comment which is inside a @foreach/loop in a .blade.php file is running.

### ISSUE THREAD

**Issue by nicolanilomartinoph** [laravel/framework#32224]
- Laravel Version: 7.0.0
- PHP Version: 7.4.4
- Database Driver & Version: MySQL , v5.7.29

### Description:
Codes inside a comment which is inside a @foreach in a blade.php file is still being executed.

### Steps To Reproduce:

1. Make a blade.php file
2. Make a @foreach loop

![Screenshot from 2020-04-04 14-01-50](https://user-images.githubusercontent.com/60249499/78420032-206a0f80-767e-11ea-848c-2e61f681e643.png)

3. Pass a variable to the view via controller
4. Display the variable
5. Comment out the code that displays the variable

![Screenshot from 2020-04-04 14-02-14](https://user-images.githubusercontent.com/60249499/78420082-6fb04000-767e-11ea-8064-99a86df4cff2.png)

6. Run again and get this error.

As you can see, even if the code accessing the [skill_image] variable is commented, Laravel is still trying to access it. Even if my code is wrong or the variable is not being passed at all by the controller to the view. It shouldn't look for that variable in the first place is it is commented. 

I already tried //  /*  commenting. I had no choice but to remove the code.

**Comment by AegirLeet** [comment]
That's just a HTML comment, it doesn't affect blade. Use `{{-- ... --}}` as documented [here](https://laravel.com/docs/7.x/blade#comments).

**Comment by GrahamCampbell** [comment]
Yes, it is very much intended that HTML comments will have their blade code executed.
