### ISSUE TITLE
Discrepancy between routes and cached routes with double slashes

### ISSUE THREAD

**Issue by BafS** [laravel/framework#32228]
- Laravel Version: 7.4.0
- PHP Version: 7.4.3
- Database Driver & Version: -

### Description:

There is a discrepancy between routes and cached routes when we have double slashes in the url.

### Steps To Reproduce:

```php
app('router')->get('/foo', 'Controller@foo');
```

http://127.0.0.1//foo works (same for ...///foo or any arbitrary number of slashes)

Run `./artisan route:cache`

http://127.0.0.1//foo does not work and shows a misleading exception

```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: HEAD.
```

But HEAD is also a 405.

Not having consistency between routes and cached routes is dangerous, we had a typo with a `domain.com//foo` somewhere in the front-end code which was working fine on development but broke on production.

**Comment by mo3000** [comment]
To define a route, app('router') is not recommended, use Route Facade instead and it's  consistency. Also, rfc1738 recognizes one and only one slash as path separator in http urlpath part. That is to say, "foo//bar" means "foo / /bar" where "/bar" is a hsegment. You can't expect arbitrary number of slashes in the url work the same.

**Comment by BafS** [comment]
@mo3000 using `Router::foo` or `app('router')->foo` is the same, in both case you use the container, I simply try to never use facades for many reasons.
Right for rfc1738, I would prefer domain.com//foo not to work but I'm fine as long as it's consistent between the two options.

**Comment by mo3000** [comment]
I have tested laravel 7.4.0, 7.3.0 in "php artisan serve" on mac, works fine.  Now I'm a little confused. Any further info may help others reproduce this. @BafS

**Comment by mo3000** [comment]
I know it's not irrelevant to this issue but when I was looking into route implementation I found this code in RouteFileRegistrar.php:
```php
    /**
     * Require the given routes file.
     *
     * @param  string  $routes
     * @return void
     */
    public function register($routes)
    {
        $router = $this->router;

        require $routes;
    }
```
where "$router" is assigned but never used because it's local.  It looks suspicious to me.

**Comment by BafS** [comment]
@mo3000 
in `routes/web.php`
```php
Route::get('/foo', 'Controller@foo');
```
in `app/Http/Controllers/Controller.php`
```php
class Controller extends BaseController {
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function foo() {
        return 'foo';
    }
}
```
With http://127.0.0.1:800//foo

- `./artisan route:cache && ./artisan serve`: Does not match
- `./artisan route:clear && ./artisan serve`: Does match

You can reproduce only if it's the root path, domain.com/foo//bar is consistent

**Comment by X-Coder264** [comment]
> I know it's not irrelevant to this issue but when I was looking into route implementation I found this code in RouteFileRegistrar.php:
> 
> ```
>     /**
>      * Require the given routes file.
>      *
>      * @param  string  $routes
>      * @return void
>      */
>     public function register($routes)
>     {
>         $router = $this->router;
> 
>         require $routes;
>     }
> ```
> 
> "$router" is assigned but never used because it's local ([commit 4cf3d30](https://github.com/laravel/framework/commit/4cf3d30f0acf295197438392049771599e569834)). It looks suspicious to me.

That is there on purpose, it enables you to write (in your routes file):

`$router->get('/foo', 'Controller@bar');`

instead of:

`Route::get('/foo', 'Controller@bar');`

And if you put at the top:

```
use Illuminate\Contracts\Routing\Registrar;

/** @var Registrar $router */

```
you get nice autocompletion in your IDE.

**Comment by driesvints** [comment]
`http://127.0.0.1//foo` is an incorrect url and shouldn't work in the first place tbh.

**Comment by BafS** [comment]
@driesvints I agree but please keep the issue open then because it does work in dev mode :)

**Comment by driesvints** [comment]
@BafS there's no need to keep an issue open when it's not a bug.

**Comment by BafS** [comment]
> http://127.0.0.1//foo is an incorrect url and shouldn't work in the first place tbh.

It does work in dev mode, it does not work with cached routes; it's inconsistent.
