### ISSUE TITLE
Notification::fake() doesn't fire NotificationSending event

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#32242]
- Laravel Version: 6.2.1
- PHP Version: 7.2
- Database Driver & Version: NA

### Description:

For some notifications I have listener attached to NotificationSending event, which should prevent sending notification if false is returned from handle() function.
When I test notifications with Notification::fake() it shows that notification was sent, even though NotificationSendingListener returns false and it's not being actually sent in the application. Looks like NotificationSending event is not even fired with Notification::fake();

### Steps To Reproduce:

Create NotificationSendingListener for NotificationSending event, make it return false from handle() method

**Comment by driesvints** [comment]
Notification fakes prevents notifications from being sent so no event is emitted either.

**Comment by vedmant** [comment]
@driesvints How then it's possible to test if notification was sent or no if no notification are sent as you say.
