### ISSUE TITLE
Components: HTML attributes are only provided by $attributes array

### ISSUE THREAD

**Issue by lairg99** [laravel/framework#32246]
- Laravel Version: 7.4.0
- PHP Version: 7.4.1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.28, for osx10.15 (x86_64) using  EditLine wrapper

### Description:

Attributes defined in components will be ignored by the templating engine, but will be provided in the ```$attributes``` array. When defining attributes explicitly, I would like to access them directly.

### Steps To Reproduce:

Exemplary I've generated a select component with my intention:

```php
<?php

namespace App\View\Components\Form;

use Illuminate\View\Component;

class SelectField extends Component
{
    /**
     * Name of the select field.
     *
     * @var string
     */
    public $name;

    /**
     * Current selected value.
     *
     * @var string
     */
    public $selected;

    /**
     * All available options of the selection.
     *
     * @var array
     */
    public $options;

    /**
     * Define required attribtues through the constructor.
     * 
     * @param string $name
     */
    public function __construct(string $name) {
        $this->name = $name;
    }

    public function render() {
        return view('components.form.select-field');
    }
}
```

```HTML
<select name="{{ $name }}">
    @foreach($options as $value => $option)
        <option @if($selected === $value) selected @endif>{{ $option }}</option>
    @endforeach
</select>
```

However, the attributes ```$options``` and ```$selected``` are only available via the ```$attributes``` array, so that the following code would result:

```HTML
<select name="{{ $name }}">
    @foreach($attributes['options'] as $value => $option)
        <option @if($attributes['selected'] === $value) selected @endif>{{ $option }}</option>
    @endforeach
</select>
```

For an overview I've attached a fragment of the dump of ```$this```.

```
"data" => array:6 [▶
  "errors" => Illuminate\Support\ViewErrorBag {#334 ▶}
  "name" => "type"
  "selected" => null // <-- This should also be set
  "options" => null // <-- This should also be set
  "attributes" => Illuminate\View\ComponentAttributeBag {#348 ▶
    #attributes: array:2 [▶
      "options" => array:4 [▶
        // key => value assignment
      ]
      "selected" => "S"
    ]
  }
  "slot" => Illuminate\Support\HtmlString {#372 ▶
    #html: ""
  }
]
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!
