### ISSUE TITLE
Custom Pivot Models And Incrementing - Primary Key is missing when detaching relation

### ISSUE THREAD

**Issue by squiaios** [laravel/framework#32253]
- Laravel Version: 5.8.37
- PHP Version: 7.2.19
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.15-MariaDB,

### Description:
When using custom pivot class on model with incrementing to true, if I detach one relation, the id is nullable while deleting because method InteractsWithPivotTable->detachUsingCustomClass() create pivot object from model keys.

see https://github.com/spatie/laravel-activitylog/issues/395#issuecomment-555005760 to get more information

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
