### ISSUE TITLE
Custom Pivot Models And Incrementing - Primary Key is missing when detaching relation

### ISSUE THREAD

**Issue by squiaios** [laravel/framework#32255]
- Laravel Version: 6.18.3
- PHP Version: 7.2.19
- Database Driver & Version: mysql Ver 15.1 Distrib 10.3.15-MariaDB,

### Description:
When using custom pivot class on model with incrementing to true, if I detach one relation, the id is nullable while deleting because method InteractsWithPivotTable->[detachUsingCustomClass()](https://github.com/laravel/framework/blob/f0f977a717e65dbe3413ef48ff82c12b5efb309d/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L454) create pivot object from model keys.

see spatie/laravel-activitylog#395 (comment) to get more information

**Comment by driesvints** [comment]
Please post full steps to reproduce.

**Comment by squiaios** [comment]
### Migrations

```
Schema::create('artists', static function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('last_name');
    $table->string('first_name');
    $table->timestamps();
    $table->softDeletes();
});

Schema::create('nationalities', static function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('label');
    $table->timestamps();
});

Schema::create('artist_nationality', static function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->unsignedBigInteger('artist_id');
    $table->unsignedBigInteger('nationality_id');
});
```

### Models

```
namespace App;

class Artist extends \Illuminate\Database\Eloquent\Model
{
	use Illuminate\Database\Eloquent\SoftDeletes;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function nationalities()
    {
        return $this->belongsToMany(Nationality::class);
    }
}
```
```
namespace App;

class Nationality extends \Illuminate\Database\Eloquent\Model
{
	//
}

```

### Pivot

```
namespace App\Pivots;

class ArtistNationality extends \Illuminate\Database\Eloquent\Relations\Pivot
{
	public $incrementing = true;
}
```

### Insert data

```
$artist = \App\Artist::create(['last_name' => 'Guetta', 'first_name' => 'David']);
$nationalityFrench = \App\Nationality::create(['label' => 'french']);
$nationalityEnglish = \App\Nationality::create(['label' => 'english']);

$artist->nationalities()->sync([$nationalityFrench->id]);
```

### Problem
When I sync with detach, if I want to use laravel model events, like `deleted`, the `id` parameters is not filled in [detachUsingCustomClass](https://github.com/laravel/framework/blob/f0f977a717e65dbe3413ef48ff82c12b5efb309d/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L454)

```
$artist->nationalities()->sync([$nationalityEnglish->id]);
```

**Comment by driesvints** [comment]
I'll leave this open for now and come back at a later time. Appreciating any help in the meantime.

**Comment by petrenkorf** [comment]
@driesvints can I take a look on this?

**Comment by driesvints** [comment]
@petrenkorf yes of course, any help welcome.

**Comment by driesvints** [comment]
I can't reproduce this sorry. Everything perfectly works when I try out your example. Feel free to provide even more thorough steps to reproduce and we'll have another look.

**Comment by benounnas** [comment]
i hope the documentation must emphasis this section because i had the same issue too, i think the pivot incrementing should be true by default
