### ISSUE TITLE
default eloquent where returning wrong result, querying string fields.

### ISSUE THREAD

**Issue by vn1miguel** [laravel/framework#32263]
Hi! I'm using Laravel 7.X.  Trying to query model, i receive unexpected result value: 

`return MyModel::where('my_string_field', 'query_value')->get();`

replacing **'query_value'** for some Integer or Boolean value, the query result a wrong result e.g:

`return MyModel::where('my_string_field', 10)->get();` 
the above query return rows where field start with **'10'** e.g: '10ajdhdhsd'

`return MyModel::where('my_string_field', false)->get();` 
the above query return * rows of table

there are many setup where return not correct values of query.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
