### ISSUE TITLE
findOrFail throws ModelNotFoundException although exists in database

### ISSUE THREAD

**Issue by mingyoung** [laravel/framework#32265]
- Laravel Version: 7.4.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 8.0.19

### Description:
When I use `$user->teams()->findOrFail(Model::class)` by passing a Model instance. It will throw an ModelNotFoundException. (Team ID 14 it actually exists in database)

See the pictures below

#### Code
```php
// App\User::class:
public function teams()
{
    return $this->belongsToMany(Team::class)
            ->withPivot('role');
}
```
#### Laravel 6.x (works)
<img width="1433" alt="2020-04-07 9 34 44" src="https://user-images.githubusercontent.com/6228858/78620711-53491900-78b3-11ea-92ea-440ce0d37645.png">

#### Laravel 7.x 😭
<img width="2189" alt="2020-04-07 9 36 19" src="https://user-images.githubusercontent.com/6228858/78620707-517f5580-78b3-11ea-9446-d1753dcf7993.png">

**Comment by driesvints** [comment]
The above example doesn't even makes sense. You already have the ID. Why retrieve the model first? It also doesn't makes sense to pass a model instance there.
