### ISSUE TITLE
Target Dispatcher is not instantiable.

### ISSUE THREAD

**Issue by Tyldar** [laravel/framework#32280]
- Laravel Version: 7.0.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:

I'm using the latest version and I tried to generate a new job class by using artisan.
Once I try to dispatch, I get the following error:

> Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable.

My job definition:

```
<?php

namespace App\Jobs\v1;

use App\Models\v1\User;
use App\Utils\Firebase;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class UserDelete implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected User $user;
    public function __construct(User $user)
    {
        $this->user =$user;
    }

    public function handle()
    {
    	
    }
}
```

And after that i'm trying to call with:
```
<?php

namespace App\Observers\v1;

use App\Jobs\v1\{UserInit, UserDelete};
use App\Models\v1\User;
class UserObserver
{
    public function deleted(User $user)
    {
        UserDelete::dispatch($user);
    }
}
```

### Steps To Reproduce:
- Quickstart a new Laravel project
- Generate a new job (php artisan make:job Test)
- Try to dispatch it

**Comment by driesvints** [comment]
This works for me.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Tyldar** [comment]
Thanks @driesvints for taking a look.
I already tried all of the links you sent.

I finally went with not dispatching anything inside the deleted method of model observer. It seems to be related to that deleted method only.

**Comment by rome2o** [comment]
In my case, this was `APP_ENV` being set to `production` on my local environment caused this to happen. I switched to this env due to some debugging issues at some point in time and forgot to change it back.
