### ISSUE TITLE
The new composer breaks autoloading

### ISSUE THREAD

**Issue by KubqoA** [laravel/framework#32309]
- Laravel Version: 7.5.0
- PHP Version: 7.4.4
- Database Driver & Version: psql 12.2

### Description:
There is a new composer version available and although it's currently a snapshot and not a stable release it breaks the `artisan package:discover` command, which fails on [this line](https://github.com/laravel/framework/blob/55070d4e57abd710783d29329d6f6846b570f452/src/Illuminate/Foundation/PackageManifest.php#L125) in the `PackageManifest` class.

The current structure of the `installed.json` has changed. Previously it was:
```
[
    {package1},
    {package2}
]
```
However, now it has changed to:
```
{
    "packages": [
        {package1},
        {package2}
    ],
    "dev": true
}
```
thus the line fails as the `$packages` array isn't no longer a direct array of the available packages.

A quick fix, is to append on the previously linked line after the `json_decode` function call `['packages']`, but this would break the functionality for older versions of composer.

This change in structure is also present in the [changelog for composer](https://github.com/composer/composer/blob/master/CHANGELOG.md#200--2020-):
* Added more info to vendor/composer/installed.json, a dev key stores whether dev requirements were installed, and every package now has an install-path key with its install location

### Steps To Reproduce:
1. Update composer via: `composer selfupdate --snapshot`
2. I deleted `composer.lock` and `vendor` directory, however this doesn't seem to affect this
3. Run `composer update`, which should fail when the `postAutoloadDump` scripts run, more specifically the `@php artisan package:discover --ansi`

**Comment by driesvints** [comment]
Thanks for reporting. Marking this as a bug even though it's for an unreleased composer version.

I guess we can easily check if the `$packages` variable has a `packages` key and use that instead.

**Comment by KubqoA** [comment]
I can make a PR for that, if it would help you :)

**Comment by driesvints** [comment]
Would be cool. I think we just need to do the following adjustments:

```php
        if ($this->files->exists($path = $this->vendorPath.'/composer/installed.json')) {
            $installed = json_decode($this->files->get($path), true);

            $packages = $installed['packages'] ?? $installed;
        }
```

Please send to 6.x, thanks!

**Comment by KubqoA** [comment]
Fixed in #32310

**Comment by kumsalajans** [comment]
@driesvints I am getting the same issue in Plesk stable version on composer

**Comment by KubqoA** [comment]
@driesvints shouldn't this, however, also get fixed for 7.x? Or it will, but this PR will suffice for that?

**Comment by driesvints** [comment]
@KubqoA 6.x is merged into 7.x regularly so it gets all of the fixes from 6.x

**Comment by KubqoA** [comment]
Oh sweet :+1: ! Thanks. Have a nice day :slightly_smiling_face:

**Comment by GrahamCampbell** [comment]
New tags of Laravel 5.5, 5.6, 5.7, 5.8, 6, and 7 will go out tomorrow, so people can continue to deploy their code with Composer v2.
