### ISSUE TITLE
URL validator doesn't allow urls that have hostnames ending with digits

### ISSUE THREAD

**Issue by bsacharski** [laravel/framework#32301]
- Laravel Version: 7.5.1
- PHP Version: 7.3.1
- Database Driver & Version:

### Description:
The url validation rule doesn't consider urls that use hostnames ending with digits as valid.
For instance, http://domain1/ is not considered a valid url.

This has its roots in Symfony Validator component's regex which was used as a basis for Illuminate's validator.

### Steps To Reproduce:
Define new validator with `url` constraint.
Try to validate data with url `'http://domain1/`

**Comment by bsacharski** [comment]
Fixed in a PR #32302

**Comment by driesvints** [comment]
That's not a valid domain afaik?

**Comment by bsacharski** [comment]
@driesvints The domain gets resolved properly, Symfony validator considers it valid, `filter_var` also considers it as valid, `parse_url` parses it correctly. 

Would have to check the RFCs to verify against the specification, but from what I see, it should be a valid domain.

**Comment by bsacharski** [comment]
Fixed in #32315
