### ISSUE TITLE
Laravel doesn't support event discovery if used within a package

### ISSUE THREAD

**Issue by WoLfulus** [laravel/framework#32313]
- Laravel Version: 7.5.2
- PHP Version: 7.4.3
- Database Driver & Version: n/a

### Description:

It seems that `classFromFile` doesn't resolve the class name correctly from packages.
Also, might be related to #28187 and #28121.

### Steps To Reproduce:

- Create a package
- Create some listeners under `Listeners` folder
- Create an event service provider for the package and register it for loading

```php
<?php

declare(strict_types=1);

namespace My\Package;

use Illuminate\Foundation\Support\Providers\EventServiceProvider;

class EventsProvider extends EventServiceProvider
{
    public function shouldDiscoverEvents(): bool
    {
        return true;
    }

    public function discoverEventsWithin(): array
    {
        return [
            __DIR__.'/Listeners'
        ];
    }
}
```

- Install the package on a project
- `php artisan event:list` no events loaded

Events won't be discovered because `classFromFile` will return `Vendor\my\package\Listeners\ListenerName` instead of `My\Package\Listeners\MyListener`. 

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Events/DiscoverEvents.php#L75

The error is supressed with a `continue`

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Events/DiscoverEvents.php#L47

I'm wondering, is this going to be supported eventually?

**Comment by driesvints** [comment]
Event discovery is only available for your app atm. If you want this to be supported feel free to open an issue on the ideas repo.
