### ISSUE TITLE
Laravel mergeConfigFrom() not giving expected behavior

### ISSUE THREAD

**Issue by sadaimudiNaadhar** [laravel/framework#32320]
- Laravel Version: 7.3.0
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

Hello, I Am building a project in HMVC architecture. So am loading configurations from different modules. Sometimes I may need to override data in the main config array. For this, I used mergeConfigFrom() in my providers. This adds when a new key-value pair is given to config array, but not over-riding when am giving existing key-value pair.

#### Issue
 Value is not over-writing when giving a new value for an existing key in the main config array.

### Steps To Reproduce:

- Create a new file  **config/db.php**
```
<?php

return [
  'connections' => 'my_new_connection_settings'
];
```
- In **app/Providers/AppServiceProvider.php**
```
$this->mergeConfigFrom(config_path('db.php'), 'database');

dd(config('database'));
```
#### Current Output
![image](https://user-images.githubusercontent.com/42279368/78974782-60267080-7b30-11ea-8e73-2d7456eb4391.png)

#### Expected Output
![image](https://user-images.githubusercontent.com/42279368/78974644-163d8a80-7b30-11ea-8bc1-49b859112218.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sadaimudiNaadhar** [comment]
Hi @driesvints  Thank you for your reply. I have updated the question. Could you please take a look. the function array_merge() in mergeConfigFrom() will not override instead it adds, I think we need to swap the params in array_merge(). I know about various config helpers provided by laravel. Could you please take a look above problem considering as a general issue. 

Thanks.

**Comment by pildit** [comment]
I have exactly the same problem and if i swap the arguments, it works as it should : override the key.
