### ISSUE TITLE
Method Illuminate\Http\Response::redirectToRoute does not exist.

### ISSUE THREAD

**Issue by samuelhgf** [laravel/framework#32323]
- Laravel Version: 7.4.0
- PHP Version: 7.4.2

### Description:

When using the response() helper it returns a Response Factory. So it is allowed to use some method such as redirectToRoute()

<img width="405" alt="Captura de Tela 2020-04-10 às 14 59 28" src="https://user-images.githubusercontent.com/16768378/79012389-8e11b200-7b3c-11ea-855b-e991989ce12f.png">

But when pass any parameters to the helper it return a Response. Not allowing to use some methods as possible when returns a Response Factory

<img width="361" alt="Captura de Tela 2020-04-10 às 15 00 03" src="https://user-images.githubusercontent.com/16768378/79012461-b7324280-7b3c-11ea-9172-14d8a6bcafbf.png">
<img width="529" alt="Captura de Tela 2020-04-10 às 15 05 40" src="https://user-images.githubusercontent.com/16768378/79012477-c3b69b00-7b3c-11ea-895b-1b6460cbb089.png">

### Steps To Reproduce:

In an action make a return of a response()->redirectToRoute("routeName")
And make a return of a response("message of the response")->redirectToRoute("routeName")

**Comment by driesvints** [comment]
`redirect()->route('routeName)`
