### ISSUE TITLE
Exception when returning empty response

### ISSUE THREAD

**Issue by svscherpenseel** [laravel/framework#32321]
- Laravel Version: 7.5.2
- PHP Version: 7.3
- Database Driver & Version: MariaDB 10.4

### Description:
Laravel throws the following exception when returning an empty response from a controller.

```
Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 65
```

### Steps To Reproduce:
Return an empty response from a controller:

`return response();`

**Comment by driesvints** [comment]
Please see the docs: https://laravel.com/docs/7.x/responses

An empty response will return the response factory.
