### ISSUE TITLE
No hint path defined for [xxx]

### ISSUE THREAD

**Issue by stephen404-13** [laravel/framework#32333]
- Laravel Version: 6.x
- PHP Version: 7.2

### Description:
i have this error when i try to send a mail to confirm register .
No hint path defined for [components/errors]. (View: /home/fotsing/Bureau/eschool-gabon/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views/404.blade.php)

### Steps To Reproduce:
i use this code in my RegisterController

```
public function register(Request $request)
    {
        $this->validator($request->all())->validate();

        event(new Registered($user = $this->create($request->all())));

        //$user = User::all()->last();  
        //dd($user);
        
        $user->notify(new RegisteredUser());

        //$this->guard()->login($user);

        return $this->registered($request, $user)
                        ?: redirect('/login')->with('success','Votre compte a bien ete creer ,vous devez confirmez avec l\' mail que vous allez recevoir');
    }
```

and a code of notification is:

 ```
public function toMail($notifiable)
    {

        return (new MailMessage)

                    
                   
                    ->success()

                    ->subject('Incription sur mon site xxxxx')

                    ->line('votre compte a bien ete cree ,merci de cliquer sur le lien suivant pour confirmer')

                    ->action('Confirmez mon compte', url("/confirm/{$notifiable->id}/" . urlencode("{$notifiable->confirmation_token}"))))
            
                    ->line('Merci pour votre confiance!!!');
    }

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
