### ISSUE TITLE
serializeDate format in model not working after retrieveing from get

### ISSUE THREAD

**Issue by harrisdt15f** [laravel/framework#32335]
- Laravel Version: 7.5.2
- PHP Version: 7.3.16
- Database Driver & Version: mysql 8.0.19

### Description:
when i get created_at data from  item which is from loop and then is get the unformated date.
I don't know it is bugs or not

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/27404296/79043842-66057a00-7c34-11ea-9f72-80e783f5f118.png)
![image](https://user-images.githubusercontent.com/27404296/79044032-7702bb00-7c35-11ea-85e6-abfc8dfe8c30.png)

![image](https://user-images.githubusercontent.com/27404296/79043940-03f94480-7c35-11ea-8d65-b736c5eb9095.png)

![image](https://user-images.githubusercontent.com/27404296/79043995-4753b300-7c35-11ea-959e-fd6064cc6435.png)

created_at field with wrong format output
![image](https://user-images.githubusercontent.com/27404296/79043860-8b928380-7c34-11ea-94d5-2d1b0d433b5d.png)

**In my opinion created Data should be** 
![image](https://user-images.githubusercontent.com/27404296/79044236-99490880-7c36-11ea-973c-07d74e318a5e.png)

**Comment by staudenmeir** [comment]
You aren't getting the expected result because you are using Carbon's JSON serialization instead of Eloquent's. Use `$item->toArray()` or `$item->only('id', 'cn_name', ...)` to build `$returnData`.

**Comment by harrisdt15f** [comment]
but why it causes to Carbon's JSON serialization I just retrieved it from Eloquent and not do any other casting.

**Comment by staudenmeir** [comment]
`$item->created_at` creates a `Carbon` instance that has no connection to the model or `serializeDate()`. When you serialize it to JSON, `Carbon` uses its default behavior and returns an ISO-8601 string.

**Comment by harrisdt15f** [comment]
ok  Thank you.
