### ISSUE TITLE
Crash when call all() method on Data Model with eager loading on hasManyThrough relationship

### ISSUE THREAD

**Issue by thobn24h** [laravel/framework#32350]
- Laravel Version: 7.5.2
- PHP Version: 7.4.2
- Database Driver & Version: MySQL

### Description:
When I want to get all Category Model with Eager Loading "MainGroup" data --> Exception.
This code run normally in Laravel 5.x, 6.x

### Steps To Reproduce:

**Here is my code:**
```
$listCategories = Category::with('mainGroups')->all();
```

**Relationship:**
```
class Category extends Model {
    public function mainGroups() {
        return $this->hasManyThrough('App\MainGroup', 'App\CategoryMainGroup', "category_id", "id", "id", "main_group_id");
    }
}
```

**Exception:**
```
BadMethodCallException
Call to undefined method Illuminate\Database\Eloquent\Builder::all()
```

**Walk Through:**
Use method get() alternate for all()
```
$listCategories = Category::with('mainGroups')->get();
```

**Comment by staudenmeir** [comment]
This code doesn't work with older versions of Laravel either. `all()` is only available in the model (`Category::all()`) but not in the query builder. The query builder only works with `get()`.
