### ISSUE TITLE
Ayuda con el gestor de base de datos de postres

### ISSUE THREAD

**Issue by AlfredQ** [laravel/framework#32353]
- Laravel Version: Laravel Framework 7.5.2
- PHP Version: 7.4.3
- Database Driver & Version: 
- postgres (PostgreSQL) 12.2
- npm -v 6.14.4
- Composer version 1.10.1
### Description:
public function update(Request $request, Entry $entry)
    {
        $validatedData = $request->validate([
            'title' => 'required|min:7|max:255|unique:entries, id,'.$entry->id,
            'content' => 'required|min:25|max:3000'
        ]);
        $entry->title = $validatedData['title'];
        $entry->content = $validatedData['content'];
        $entry->save(); // UPDATE
        $status = 'Your entry has been updated successfully.';
        return back()->with(compact('status'));
    }
### Steps To Reproduce:
pero me vota el siguiente error.
Illuminate\Database\QueryException
SQLSTATE[42703]: Undefined column: 7 ERROR: no existe la columna « id» LINE 1: select count(*) as aggregate from "entries" where " id" = $1... ^ HINT: Probablemente quiera hacer referencia a la columna «entries.id». (SQL: select count(*) as aggregate from "entries" where " id" = Fugiat sed eius quo abc.s and "id" <> 1)
-------------------------------------------------
ahora si le quito id,'.$entry->id,
'title' => 'required|min:7|max:255|unique:entries',
 de la "function update" funciona pero cambiando la información el title para actualizar y yo solo quiero cambiar la información de content.
Cambie de gestor de base de datos a mysql y no me muestra el mismo problema, será el error con el gestor de base de datos de postgres.
gracias

**Comment by driesvints** [comment]
Unfortunately we cannot provide any support other than in English, sorry about that.

Please try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
