### ISSUE TITLE
Laravel 7.0 issue 419 Error when login in movilphone chrome or safari browser

### ISSUE THREAD

**Issue by oriolrg** [laravel/framework#32378]
- Laravel Version: 7.0
- PHP Version: 7.2.*
- Database Driver & Version: mysql

### Description:
I have found a bug, which causes that when trying to log in from iphone safari or android chrome, it returns error 419. In the other browsers it works correctly. I have tried the same with different projects carried out with laravel and the problem is the same, in addition there are more users of laravel who have the same problem without obtaining a solution. Does this mean that Laravel cannot work from mobile phones?

### Steps To Reproduce:
You can try to login with iphone safari or android chrome to this url:

tecnolord,cat/test/login
https://documentator.io/login

n all the apps created with Laravel that I have tested I get the same result. So all this makes me think that it is Laravel's problem.

**Comment by driesvints** [comment]
Please try on a support channel like suggested on the previous issue. Thanks.

I can use the login screen on mobile safari just fine in several apps.
