### ISSUE TITLE
Laravel 7.0 issue 419 Error when login in movilphone chrome or safari browser

### ISSUE THREAD

**Issue by oriolrg** [laravel/framework#32375]
My app works correctly and does not return this error 419, except when I login from Chrome browser or Safari from a mobile phone.

**Comment by oriolrg** [comment]
This is my composer.json part of laravel
"require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0"
    },


From any other browser there is no problem but when it is done from a mobile phone in chrome or safari yes. I have been checking the session configuration and I think it is correct, it is saved in file.

I will appreciate the help since this bug causes my system to not be usable from apple terminals.
Thank you very much in advance

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by oriolrg** [comment]
Well I understand that it is a Laravel bug, since this causes a laravel app to not be functional for apple phones or chrome android browsers. In the other cases it works correctly

**Comment by oriolrg** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Well I understand that it is a Laravel bug, since this causes a laravel app to not be functional for apple phones or chrome android browsers. In the other cases it works correctly

**Comment by oriolrg** [comment]
I don't know very well the cause of the problem, but I see that the session is always created well except from the mentioned browsers. In this case the session file is not generated inside storage / framework / session.
I can not understand the reason why it only happens in those browsers and in the rest it does not

**Comment by oriolrg** [comment]
I have found a thread that talks about a delay in some browsers and that causes the session to be destroyed already? Can this be so? I have tried to modify the lifetime of the session but it does not work either. You know this isn't a laravel library problem?

**Comment by oriolrg** [comment]
See if I think it is a Laravel problem, if I have been reviewing several projects done with laravel, and they all have the same error 419 when running from android chrome or safari. Some examples are:
https://documentator.io/login
tecnolord.cat/test

And all the projects I've done so far have the same bug. So if I think it is a Laravel problem, at least a problem that affects Laravel

**Comment by IlCallo** [comment]
@driesvints this seems to be the root of the error.
Can this be integrated in Laravel Sanctum docs?
https://github.com/Fyrd/caniuse/issues/4813

**Comment by driesvints** [comment]
Feel free to send in a pr.

**Comment by IlCallo** [comment]
@driesvints 
Where do you think would be better to add the notice?
`same_site` option is `lax` by default but is never mentioned into the docs.
It's located under `config/session.php` configuration.
Shall I add the disclaimer into session page? Sanctum page? Directly in the comment into `config/session.php` over that option?
