### ISSUE TITLE
[5.7] Testing assertViewIs() with followingRedirects() throws an error: `The response is not a view.`

### ISSUE THREAD

**Issue by RyoIkarashi** [laravel/framework#32381]
- Laravel Version: 5.7.28
- PHP Version: 7.2.27
- Database Driver & Version: Mysql (5.7.29)

### Description:

When asserting a view with `assertViewIs()` after the `call()` method with `followingRedirects()` always throws an error saying `The response is not a view`.

```php
// The controller's method of `/create` endpoint returns `return redirect()->route('routeName')`.
// But asserting the view returned by the controller after `call` method with `followingRedirects()` will always throw an error like below.

$this->followingRedirects()->call('POST', '/create')->assertViewIs('routeName'); // => The response is not a view

// also doesn't work.
$response = $this->call('POST', '/create');
$this->followRedirects($response)->assertViewIs('routeName');
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
