### ISSUE TITLE
Call to undefined method League\Flysystem\Filesystem::extends

### ISSUE THREAD

**Issue by samuelhgf** [laravel/framework#32395]
- Laravel Version: 7.6.2
- PHP Version: 7.4.2

### Description:
I was trying to use DropboxFilesystem from spatie and came with this error
I was following the laravel docs about custom filesystem, but appears that there is no such extends method in the Storage facade

https://laravel.com/docs/7.x/filesystem#custom-filesystems

`public function boot()
    {
        Storage::extends('dropbox', function ($app, $config) {
            $client = new Client(
                $config['authorization_token']
            );

            return new Filesystem(new DropboxAdapter($client));
        });
    }
}`

### Steps To Reproduce:

Just follow the [CutsomFilesystem](https://laravel.com/docs/7.x/filesystem#custom-filesystems) documentation

**Comment by Raza9798** [comment]
Replace the Boot function with
     `Storage::extend('dropbox', function ($app, $config) {
              $client = new DropboxClient(
                  $config['authorization_token']
             );

              return new Filesystem(new DropboxAdapter($client));
        });`

**THE MISTAKE YOU MADE WAS**
Storage::extend**s**('dropbox', function ($app, $config) {
