### ISSUE TITLE
Route macro don't support concatenation

### ISSUE THREAD

**Issue by darklight9811** [laravel/framework#32396]
- Laravel Version: 7.5.2
- PHP Version: 7.2.7
- Database Driver & Version: not related

### Description:
When creating a macro for routes, they are not available with concatenation

### Steps To Reproduce:

Create a macro and register it in the boot method of a service provider
``` php
\Illuminate\Support\Facades\Route::macro("effectResource", function($name, $controller, $options = []) {
    \Illuminate\Support\Facades\Route::resource($name, $controller, $options)->only(['store', 'update', 'destroy']);
});
```

Call it in the route file (either web or API):
``` php
Route::effectResource("/preset", "Project\PresetController");
Route::middleware(["anyMiddlewareHere"])->effectResource("/project", "Project\Controller");
```

The second line should give the error, while the first one should work.

**Comment by driesvints** [comment]
It's not meant to be used like that. Try:

```php
Route::middleware(["anyMiddlewareHere"])->group(function () {
    Route::effectResource("/preset", "Project\PresetController");
});
```
