### ISSUE TITLE
artisan make:policy returning empty dependence

### ISSUE THREAD

**Issue by barreirinha** [laravel/framework#32397]
- Laravel Version: 7.6.1
- PHP Version: 7.4.1
- Database Driver & Version:

### Description:

When I use the  **artisan make:policy**   command with the **-m** option, it returns a empty dependence in the Class

### Steps To Reproduce:

`php artisan make:policy RolePolicy -m Role`

Returned Class:

``` bash
<?php

namespace App\Policies;

use App\Role;
use Illuminate\Auth\Access\HandlesAuthorization;
use ;

class RolePolicy 
{
```

I get the same issue when I try **php artisan make:policy RolePolicy --model=Role**. 

But If i type **php artisan make:policy RolePolicy -m=Role** it returns:

``` bash
 <?php

namespace App\Policies;

use App\=Role;
use Illuminate\Auth\Access\HandlesAuthorization;
use ;
```

**Comment by driesvints** [comment]
I don't get this problem in the latest version. I just get the expected dependencies.

**Comment by safaomnia** [comment]
I've got same problem in laravel 5.8.*
