### ISSUE TITLE
Error for Null object happen when i change laravel version 

### ISSUE THREAD

**Issue by Adamkaram** [laravel/framework#32403]
- Laravel Version: 6.2
- PHP Version:7.2

the fresh method always return Null for the user relation i'm tried some method like load and loadmissing but it all doesn't work it works for me in old version but Now i doesn't 

this my code to save a comments 
**public function store(Request $request, News $News)
 { return auth()->user()->comments()->create([
            'body' => $request->body,
            'News_id' => $News->id,
            'comment_id' => $request->comment_id])->fresh()
; }**
and this my relations with protected $with 
    **protected $with = ['user'];
 public function user()
    {
        return $this->belongsTo('App\User');
    }
 public function comments()
    {
        return $this->hasMany('App\Comment');
    }**

in the older version like 5.8 i was able to get the user object and retrieve his name this error from vue js and it's  related with laravel 

![12](https://user-images.githubusercontent.com/52092726/79467573-181fb600-8028-11ea-9921-3a9f149478ad.png)
![13](https://user-images.githubusercontent.com/52092726/79467577-19e97980-8028-11ea-87c1-577d03a73d47.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Adamkaram** [comment]
yup i try in all of this and this is bug this work in older version
