### ISSUE TITLE
Undefined variable: subcopy

### ISSUE THREAD

**Issue by hemal2665** [laravel/framework#32406]
- Laravel Version: 6.0
- PHP Version: 7.4
- Database Driver & Version:  ODBC Driver for PHP 5.8 

### Description:

Just migrated from Laravel 5.6 and php 7.1 to Laravel 6.0 and php 7.4. Everything is running fine except password reset email. I am receiving following error.

So far i have tried clearing views, config and cache but no luck. I tried removing $subcopy variable and replacing or with ?? in layout view but email looks funky and displaying some html tags. I am beginner with this and desperately trying to make this work since last few days. Any help would be appreciated.

Thanks. 

![tempsnip](https://user-images.githubusercontent.com/50035610/79483170-e71b9300-7fdf-11ea-9298-d87aea53da69.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
