### ISSUE TITLE
Blade components not passing variables when called recursively

### ISSUE THREAD

**Issue by eduardoarandah** [laravel/framework#32429]
- Laravel Version: 7.4.0
- PHP Version: 7.3.15
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64)

### Description:

When components are called inside another component I get variables not set. 

Imagine a component that renders comments and their replies recursively. 

Every comment renders its childen components. 

This is what we want:
![image](https://user-images.githubusercontent.com/4065733/79623445-eff48d80-80e1-11ea-866c-e88ef82d1d79.png)

This is what we get:
![image](https://user-images.githubusercontent.com/4065733/79623469-161a2d80-80e2-11ea-9140-449953b1111c.png)

### Steps To Reproduce:

Comment-Item fails like this:
```
namespace App\View\Components;
use Illuminate\View\Component;

class CommentItem extends Component
{
    public $comment;
    public $depth;

    public function __construct($comment, $depth = 0)
    {
        $this->comment = $comment;
        $this->depth = $depth;
    }

    public function render()
    {
        return view('components.comment-item');
    }
}
```

But works like this:

```
 public function render()
 {
     return view('components.comment-item', [
     'comment' => $this->comment,
     'depth' => $this->depth,
     ]);
 }
```

When setting variables explicitly, component works just fine!!

This is the code for recursively calling the component. 
It's not that relevant I guess, but I'll put it here if it helps:

```
 public function renderCommentsRecursive($comment, $depth)
 {
   // exit condition
     if (!$comment->has('comments')) {
         return null;
     }
     // process
     $out = "";
     foreach ($comment->comments()->ordered()->get() as $childComment) {
         $commentComponent = new CommentItem($childComment, $depth);
         $out .= $commentComponent->render();

         // recursive
         $out .= $this->renderCommentsRecursive($childComment, ++$depth);
     }
     return $out;
 }
```

Could it be that variables are named exactly the same in parent-child so blade mixes scope??

Please let me know if this information is enough to reproduce, or need a more detailed example!!

**Comment by driesvints** [comment]
Please share the `components.comment-item` view.

**Comment by eduardoarandah** [comment]
Sure! 

Note that type doesn't matter. 

$depth is just a number
$comment is a model

comment-item.blade.php

```
<li id="comment-{{ $comment->id }}" class="comment" style="margin-left: {{ $depth*2 }}rem">
{{ $comment->text }}
</li>
```

**Comment by driesvints** [comment]
Can you maybe share all the views involved? Also the ones calling the components.

**Comment by eduardoarandah** [comment]
Sorry for not providing a simpler example:

I made a fresh laravel app to demo it:
https://bitbucket.org/eduardoarandah/laravel-blade-variables-error/src

![image](https://user-images.githubusercontent.com/4065733/79894883-b6669f80-83cb-11ea-81ed-5d7431daf598.png)


welcome.blade.php

```
<html>
    <body>
      <x-father-component/>
    </body>
</html>
```

app/View/Components/FatherComponent.php
```
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use App\View\Components\ChildComponent;

class FatherComponent extends Component
{
    public function render()
    {
        $children = $this->renderChildren(8);
        return view('components.father-component', [
          'children' => $children,
        ]);
    }

    public function renderChildren($depth)
    {
        $depth--;

       // exit condition
        if (!$depth) {
            return null;
        }

        $child = new ChildComponent($depth);
        $out = $child->render();
        $out .= $this->renderChildren($depth);
        return $out;
    }
}

```

resources/views/components/father-component.blade.php
```
<div>
  Hello world! <br>
  Here is children:
    {!! $children !!}
</div>

```

app/View/Components/ChildComponent.php
```
<?php
namespace App\View\Components;

use Illuminate\View\Component;

class ChildComponent extends Component
{
    public $depth;
    public function __construct($depth)
    {
        $this->depth = $depth;
    }
    public function render()
    {
      // doesn't work:
        // return view('components.child-component');
        // does work:
        return view('components.child-component', [
          'depth' => $this->depth,
        ]);
    }
}

```

resources/views/components/child-component.blade.php
```
<div style="margin-left: {{ $depth*2 }}rem;padding: 1rem;border:1px solid gray">
  Hello Depth: {{ $depth }}
</div>
```

**Comment by driesvints** [comment]
You can't use components outside views like that. In the Blade views `->withAttributes` is called on the components to pass in its attributes.

**Comment by eduardoarandah** [comment]
May I ask how to use `->withAttributes` if calling `->render()` outside blade? 

are components relying on some global initialization? some global state?

**Comment by driesvints** [comment]
Here: https://github.com/laravel/framework/blob/7.x/src/Illuminate/View/Compilers/ComponentTagCompiler.php#L195-L197
