### ISSUE TITLE
MorphTo model saving events are not fired

### ISSUE THREAD

**Issue by vmartins** [laravel/framework#32437]
- Laravel Version: 7.6.2
- PHP Version: 7.3.16
- Database Driver & Version: MySQL 5.7.29

### Description:
MorphTo relation don't fire ```saving``` / ```saved``` [events](https://laravel.com/docs/7.x/eloquent#events).

### Steps To Reproduce:
-> Table structure of official documentation [One To Many (Polymorphic)](https://laravel.com/docs/7.x/eloquent-relationships#one-to-many-polymorphic-relations).

-> Model Structure:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public $timestamps = false;

    /**
     * Get the owning commentable model.
     */
    public function commentable()
    {
        return $this->morphTo();
    }
}

class Post extends Model
{
    public $timestamps = false;
    protected $fillable = ['title'];

    /**
     * The "booted" method of the model.
     */
    protected static function booted()
    {
        static::saving(function ($post) {
            logger('saving post');
            dd('saving post');
        });
    }

    /**
     * Get all of the post's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

class Video extends Model
{
    public $timestamps = false;
    protected $fillable = ['title'];

    /**
     * The "booted" method of the model.
     */
    protected static function booted()
    {
        static::saving(function ($video) {
            logger('saving video');
            dd('saving video');
        });
    }

    /**
     * Get all of the video's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}
```
-> Updating Related Models
```php
$comment = App\Comment::find(1);
$comment->commentable()->update(['title' => 'new title' . rand()]);
```

Closures models events are never fired!

**Comment by staudenmeir** [comment]
Take a look at the warning from the docs that applies to your situation:

> When issuing a mass update or delete via Eloquent, the saved, updated, deleting, and deleted model events will not be fired for the affected models. This is because the models are never actually retrieved when issuing a mass update or delete.

You are doing what the warning refers to as "mass update" (although you are only updating a single record). The events are fired when you retrieve the related model before updating it:

```php
$comment->commentable->update(['title' => 'new title' . rand()]);
                    ^^
```

**Comment by vmartins** [comment]
Thanks for the explanation. Closed!
