### ISSUE TITLE
IoC Container call method has a bug

### ISSUE THREAD

**Issue by irazasyed** [laravel/framework#32438]
- Laravel Version: 7.6.2
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:

Container `call()` method without the required params of a method doesn't throw any exception and instead invokes with the default values of the next params in line. Something that isn't expected and has a bad side effect.

I'll explain what's happening and I have a solution as well.

### Steps To Reproduce:

Let's take this class as an example

```php
<?php

namespace App;

class Test
{
    public function handle($name, $title = 'CEO', $rank = 'Executive')
    {
        dd('Name: ' . $name, 'Title: '. $title, 'Rank: '. $rank);
    }
}
```

As we can see, the `$name` parameter is a required parameter while the other two have default values.

Now when you invoke this method using the container WITHOUT the parameters:

```php
$test = app()->call('App\Test@handle');
```

As per the normal PHP's behaviour, we would expect it to fail and throw an exception because we haven't provided a required parameter. However, Laravel's IoC container ignores the fact that there's a required parameter that's missing when it's building the dependencies parameter array.

So because of this minor logic flaw, it ends up building an array with the other two optional parameters default values and just invokes that method with the new parameters array resulting in `$name` parameter getting a value of the second optional param, i.e. `$title` and `$title` itself getting the third param's default value. So when you look at the output of the above. You'll see something like this:

```
Name: CEO
Title: Executive
Rank Executive
```

The expectation was it to throw an exception at least because of the missing value for the required param.

If we do the same but this time WITH the parameters passed to the call method, it still doesn't help.

Ex:
```php
$params = ['title' => 'Founder', 'rank' => 'Owner'];

$test = app()->call('App\Test@handle', $params);
```

Output:
```
Name: Founder
Title: Owner
Rank: Executive
```

As you can see, because the params array didn't have the required param key-value, instead of failing, it ignored and just used the default values of the other two params and invoked it.

We're using IoC container to process some user inputs with required and optional params in a library and we don't control that but because of this weird bug, it's causing an abnormal behaviour.

This works fine if the required param is passed on to the container's call method.

I with a friend of mine traced this issue and tracked it down to the `BoundMethod::addDependencyForCallParameter` [method](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Container/BoundMethod.php#L157-L173) which is responsible to build the params array. 

The solution is only to check if the param is not optional and the parameters passed by the user doesn't have the required param's name in it just like other conditional statement and if it doesn't, throw an exception.

Here's the proposed solution:

```diff
/**
 * Get the dependency for the given call parameter.
 *
 * @param  \Illuminate\Container\Container  $container
 * @param  \ReflectionParameter  $parameter
 * @param  array  $parameters
 * @param  array  $dependencies
 * @return void
 *
 * @throws BindingResolutionException
 */
protected static function addDependencyForCallParameter($container, $parameter,
                                                        array &$parameters, &$dependencies)
{
    if (array_key_exists($parameter->name, $parameters)) {
        $dependencies[] = $parameters[$parameter->name];

        unset($parameters[$parameter->name]);
    } elseif ($parameter->getClass() && array_key_exists($parameter->getClass()->name, $parameters)) {
        $dependencies[] = $parameters[$parameter->getClass()->name];

        unset($parameters[$parameter->getClass()->name]);
    } elseif ($parameter->getClass()) {
        $dependencies[] = $container->make($parameter->getClass()->name);
    } elseif ($parameter->isDefaultValueAvailable()) {
        $dependencies[] = $parameter->getDefaultValue();
+   } elseif(!$parameter->isOptional() && !array_key_exists($parameter->name, $parameters)) {
+        $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->getName()}";

+        throw new BindingResolutionException($message);
+    }
}
```

The exception was simply extracted from the [unresolvablePrimitive](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Container/Container.php#L991-L996) method in Container class.

I've already tested this solution and it works as expected. I can send a PR but I'm not sure if the exception and the message there makes sense. But if you have a better solution, that would be great of course.

**Comment by irazasyed** [comment]
I think the bug is present in previous versions of Laravel as well. So it would be great if this or any other solution is added to at least Laravel 6 or whatever versions are still supported.

**Comment by mfn** [comment]
Would be great to see the PR and if any (existing) tests fail.

**Comment by irazasyed** [comment]
Created a PR #32439. Let's see!
