### ISSUE TITLE
Variable not found in blade component

### ISSUE THREAD

**Issue by md13381** [laravel/framework#32435]
- Laravel Version: 7.4.0
- PHP Version: 7.4.4
- Database Driver & Version:

### Description:
Using laravel blade components, we have created a component named app/view/components/navbar.php with an associated view resources/views/components/navbar.blade.php using the  `php artisan make:component navbar`. This component gets called in index.blade.php

index.blade.php:
```
<!DOCTYPE html>
<html lang="en">
    <!-- Body -->
    <body>
        <!-- Nav Bar -->
        <x-navbar/>
        <!-- End Nav Bar -->
    </body>
    <!-- End Body -->
</html>
```
navbar.php
```
namespace App\View\Components;
use Illuminate\View\Component;
use Illuminate\Http\Request;

class navbar extends Component
{

    public $loggedIn;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function render()
    {
        $loggedIn = false;
        if (!empty($this->request->cookie('authToken'))) {
            $loggedIn = true;
        }

        return view('components.navbar', [
            'loggedIn' => $loggedIn,
        ]);
    }
}
```

navbar.blade.php
```
    @if ($loggedIn)
      Shown if logged in
    @else
      Shown if logged out
    @endif
```
The component correctly displays in some peoples enviroments however in many it returns variable $loggedIn not found. In all cases looking inside storage/framework/views and the associated file it does auto find the component as is also shown in the autoload file. We found we were able to resolve this by creating an inline component return or by renaming navbar.php to Navbar.php and the class also to Navbar. It seems like it is case dependent which the documentation does not mention as a limitation.

**Comment by driesvints** [comment]
> class navbar extends Component

Your navbar and filename class needs to be PascalCase.

**Comment by md13381** [comment]
My point was this is not in the documentation as the artisan command does not automatically do this

**Comment by driesvints** [comment]
@md13381 all examples in the documentation are in PascalCase

**Comment by md13381** [comment]
There is only one example of a single word. `class Alert extends Component` That does really not demonstrate PascalCase

**Comment by driesvints** [comment]
It literally does?

**Comment by md13381** [comment]
It doesnt in any way suggest it is strict is my point, considering the actual calling of the component inside a blade is all lower case

**Comment by Citvej** [comment]
I agree with @md13381 and the documentation is poorly written.

**Comment by driesvints** [comment]
Feel free to PR any improvement you want to make 👍
