### ISSUE TITLE
FormRequest returns "not" validated when Form data is Empty

### ISSUE THREAD

**Issue by tmacedo29** [laravel/framework#32445]
- Laravel Version: 7.6.2
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7.17-13

### Description:
It seems FormRequest validator returns _Invalid_ when no data is sent from Form data, and there are no rules

### Steps To Reproduce:
Create a FormRequest using the command: **php artisan make:request MyTestRequest** and use it (MyTestRequest) as input parameter of a method that handles an empty data POST request from a Form.

**MyTestRequest.php**
```php
public function authorize()
{
  return true;
}
public function rules()
{
  return [ ];
}
```

**routes\web.php**
```php
Route::post('mytest', 'MyTestController@myTest');
```

**MyTestController.php**
```php
public function myTest(MyTestRequest $request)
{
  if ($request->validated())
    dd("validated");
  else
    dd("not validated");
}
```

**mytest.blade.php**
```html
<form method="POST" action="{{ route('test') }}">
  @csrf
  <button>Save</button>
</form>
```

**Comment by staudenmeir** [comment]
`validated()` is the wrong method for this check, use `$request->passes()` instead.

`validated()` returns the validated data as an array and in this case, it's an empty array. In a loose comparison, PHP treats it as a _falsy_ value: https://www.php.net/manual/de/types.comparisons.php
