### ISSUE TITLE
Laravel 7 Custom helpers render my app throw exceptions (Page expired) when login 

### ISSUE THREAD

**Issue by BechirAhmed** [laravel/framework#32440]
- Laravel Version: ^7.6.0
- PHP Version: ^7.2.5
- Database Driver & Version: mysql, latest

### Description:
I'm trying to create custom helper, on local environment it's working greate.
but when push to server i can't login any more, it always return page expired.

I have tried 2 options to load my helpers:

1. require it in service provider (register function)
```php
public function register()
 {
      foreach (glob(app_path() . '/Helpers/*.php') as $file) {
	require_once $file;
      }
 }
```

2. composer.json file
```php
"autoload": {
    ...
    "files": [
          "app/Helpers/custom_helpers.php"
      ]
}
```

but always the same error.
Does Laravel 7 support custom helpers, if yes how to implement them?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
