### ISSUE TITLE
Installing version 7.x or updating from old version

### ISSUE THREAD

**Issue by hussain2y2** [laravel/framework#32443]
- Laravel Version: 7.6
- PHP Version: 7.4
- Database Driver & Version: pgsql, php7.4-pgsql

### Description:
I am trying to set up a new version of Laravel via composer but at last it give me errors:

1. Class Illuminate\Foundation\ComposerScripts is not autoloadable, can not call post-autoload-dump script.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255.

It was working fine with Laravel 6.x but when I have updated to 7.x it gives me the above errors. 

### Steps To Reproduce:

1. Install new version

**Comment by ndhan93** [comment]
update class App\Exceptions\Handler also
See: https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
