### ISSUE TITLE
Laravel 7.x doesn't allow to overwrite named routes any more

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#32446]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:

Before Laravel 7 it was possible to overwrite single named routes added by 3rd party Laravel packages e.g. in ./routes/web.php. This is not possible any more. What is the suggested way to change routes introduced by 3rd party packages now?

**Comment by activa-media** [comment]
Got the same problem here. When I use 
`Route::resource('companies.contracts.previews', 'PreviewController')->only('show');` 

the route above is working but when I use 

`Route::get('companies/{company}/contracts/{contract}/previews/{preview:id}', 'PreviewController@show');`

the route throw `Call to undefined method App\Contract::previews()`. The route didn't even reach App\Preview at all.

**Comment by activa-media** [comment]
Updates:

`Route::get('companies/{company}/contracts/{contract:id}/previews/{preview:secret}', 'PreviewController@show');`
Turns out to be working after did some dirty trick bypassing the relationship.

// Model App\Contract.php
`public function preview() { return $this->hasOne(Preview::class);` Not working but this is want I want the relationship to be and end up become like this... Got this error `Call to undefined method App\Contract::previews()`

`public function previews() { return $this->hasMany(Preview::class);` Working but this not I want.

This is so weird when the error is pointing App\Contract and not PreviewController@show

**Comment by driesvints** [comment]
@aimeos if you need to overwrite package routes you need to explicitly define them in your own routes file and prevent the route registration of the package in the same fashion we do in Cashier: 

https://github.com/laravel/cashier/blob/11.x/src/Cashier.php#L133-L143

It's up to the package to implement this.

@activa-media I don't know what you mean. You obviously haven't defined the `previews` relationship method on your Contract model and you're making use of the new Custom Keys & Scoping. See https://laravel.com/docs/7.x/routing#implicit-binding

**Comment by activa-media** [comment]
Hi @driesvints , I did define the relationship on the models before I define routes. If I din't define it, obviously it won't work on `Route::resource()` mentioned above.

`Route::get('companies/{company}/contracts/{contract:id}/previews/{preview:secret}', 'PreviewController@show');` Somehow throw an error looking for `Call to undefined method App\Contract::previews()`

Contract only have one Preview, so the relationship is `preview()` but when I rename it to `previews()` it works. This is not right.

**Comment by driesvints** [comment]
@activa-media your route segment is named `previews`, not `preview`.

**Comment by enextiarg** [comment]
I have de same problen. Before version 7 it's was able to replace a route. For eg. welcome:

`
        $router = Route::get('/');
        $router->uses('Enexti\Core\Http\Controllers\CoreController@welcome')->name('welcome')->middleware('web');

`

**Comment by enextiarg** [comment]
I found a temporary solution. Use a middleware called ChangeHomeUrl. 

```
$route = $request->route();
if($route->uri === '/') $route->uses(Hooks::apply_filters('core_controller_welcome','Enexti\Core\Http\Controllers\CoreController@welcome'));
```
