### ISSUE TITLE
Raw queries with bindings do not work with data type conversion functions.

### ISSUE THREAD

**Issue by DanVeira** [laravel/framework#32456]
- Laravel Version: 7.6.2
- PHP Version: 7.2.19
- Database Driver & Version: sqlsrv 15.0.2000.5

### Description:
Raw queries with bindings do not work with data type conversion functions CAST() and CONVERT().

### Steps To Reproduce:
```
//select count(*) from [tbl_rfaccount] where CONVERT(varchar, id) = 'test'
$count = DB::connection('sqlsrv_rf_user')->table('tbl_rfaccount')
  ->whereRaw("CONVERT(varchar, id) = ?", $request->input('id'))
  ->count();
//$count = 1

//select count(*) from [tbl_rfaccount] where id = CONVERT(binary(13), 'test')
$count = DB::connection('sqlsrv_rf_user')->table('tbl_rfaccount')
  ->whereRaw("id = CONVERT(binary(13), ?)", $request->input('id'))
  ->count();
//$count = 0
```
Both of those should return `$count = 1` but only the top query does. When pasting those two queries directly into the database manager both return a count of 1.
I've used Laravel Telescope to see the queries being executed and the code outputs the query commented above it.
The same behavior happens with INSERT.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by DanVeira** [comment]
I've posted this issue to several support channels:

- https://laracasts.com/discuss/channels/laravel/laravel-query-builder-whereraw-with-convert-to-datatype-returning-different-results
- https://laravel.io/forum/raw-queries-with-bindings-not-working-with-data-type-convers
- https://stackoverflow.com/questions/61312251
- https://discordapp.com/channels/297040613688475649/486983156411400202/701764904138309735
- https://larachat.slack.com/archives/C039F76DN/p1587384686348500

No luck so far.

**Comment by DanVeira** [comment]
I guess this is a problem with PDO and data types. If I use the sqlsrv driver without PDO everything works fine. I have no clue how to get around this while being able to use Larave's query builder so I'm just going to give up for now as this has wasted me over 20 hours.
