### ISSUE TITLE
Error on `whereHasMorph` when morph columns are null

### ISSUE THREAD

**Issue by ambengers** [laravel/framework#32458]
- Laravel Version: 7.6.2
- PHP Version: 7.2.25
- Database Driver & Version: MySQL 5.5.5-10.4.10-MariaDB

### Description: 

Using `whereHasMorph` and `orWhereHasMorph` when there are records with null values on morph columns, laravel produces this error:

```
Search Filter (Ambengers\QueryFilter\Tests\Feature\SearchFilter)
 ✘ It can search through polymorphic relation
   ┐
   ├ Error: Class name must be a valid object or a string
   │
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:718
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:179
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:245
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:90
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:247
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:217
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:228
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:266
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:227
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:228
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:229
   ╵ /Users/dignity/codes/query-filter/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:321
```

### Steps To Reproduce:

For simplicity's sake, let's use the comments example we have on docs:

https://laravel.com/docs/7.x/eloquent-relationships#querying-polymorphic-relationships

1. Setup a couple comment records in the database. Let couple of records be null on `commentable_type` and `commentable_id` columns.
2. Run the `whereHasMorph` query against comments like so:

```
$comments = App\Comment::whereHasMorph('commentable', '*', function (Builder $query) {
    $query->where('title', 'like', 'foo%');
})->get();
```

**Comment by DSpeichert** [comment]
I can reproduce this bug.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/29357

**Comment by mrwogu** [comment]
@driesvints I am also using this for morphTo and it's still not working.

**Comment by ambengers** [comment]
@driesvints I don't think the solution on #29357 is the same solution for this issue, if this is the reason this issue is being closed.

**Comment by DSpeichert** [comment]
@driesvints I can provide a more detailed explanation as this bug occurs specifically when querying morphs of any type (using `*`).

Migration:

```php
...
$table->nullableMorphs('service');
...
```

Model:

```php
public function service()
{
   return $this->morphTo();
}
```

When there is a `ModelName` record with actually null `service_id` and `service_type` columns, it works like this:

This one WORKS:
```php
ModelName::whereHasMorph('service', [RelatedOne::class, RelatedTwo::class])
```

This one does not:
```php
ModelName::whereHasMorph('service', '*')
```

When there are no null morphs in the database, both actually exist as expected.

Therefore, there appears to be a bug in the handling of "any" type.

**Comment by driesvints** [comment]
Okay re-opening.

@staudenmeir do you might know what's going on here?

**Comment by ambengers** [comment]
@DSpeichert or @driesvints - is it correct to say that when we use wildcard ("*") on `whereHasMorph`, we also expect to get rows with null morph columns?

**Comment by staudenmeir** [comment]
I'll submit a fix.

**Comment by DSpeichert** [comment]
@ambengers Right now it looks like undefined behavior, but in my opinion, when using `whereHasMorph('morph', '*')`, I have an expectation of NOT getting morphs with NULL values. If they are NULL, we don't actually "have morph".

I'd be curious to see what is the "desired" behavior for soft-deleted morphs. I guess that by following Laravel's prior pattern, those would be skipped as well, although that would make it impossible to decide through the Closure (one could do `->whereNull('deleted_at')` in the Closure).

**Comment by staudenmeir** [comment]
@DSpeichert The wildcard includes soft-deleted morph types.

A query like this works correctly even if all comments of a certain type are soft-deleted:

```php
Comment::whereHasMorph('commentable', '*', function (Builder $query) {
    $query->where('title', 'like', 'foo%');
})->withTrashed()->get();
```

**Comment by taylorotwell** [comment]
Fixed.

**Comment by shengslogar** [comment]
This doesn't consider if all morph records in a table are null and, since we're not even hitting the loop here, will return all records:

https://github.com/laravel/framework/blob/92957206252cd4e40430f6f9eb2560566fa34ba3/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L216

I would expect something like:

```
if (count($types) > 0) {
     // foreach ($types as $type)...
} else {
     $query->whereNotNull(this->query->from.'.'.$relation->getMorphType());
}
```

...for consistency. Thoughts?
