### ISSUE TITLE
Models Ide helpers

### ISSUE THREAD

**Issue by thisismhp** [laravel/framework#32459]
- Laravel Version: 7.6.2
- PHP Version: 7.3.16
- Database Driver & Version: MariaDB 10.4.11

### Description:
Static methods of models like :  Post::where not declear in your classes
### Solution:
Add below comments to Model class
 * @method static static find($id)
 * @method static static orderBy($column, $type = 'ASC')
 * @method static static where(...$conditions)
 * @method static static orWhere(...$conditions)
 * @method static static get($key = null)
 * @method static static last()
 * @method static static first()
 * @method static static all()
 * @method static static paginate()

**Comment by mfn** [comment]
Seems you want to check out https://github.com/barryvdh/laravel-ide-helper

**Comment by thisismhp** [comment]
> 
> 
> Seems you want to check out https://github.com/barryvdh/laravel-ide-helper

No , this package is for custom columns and attributes , laravel must declear own methods

**Comment by driesvints** [comment]
We have no intention of adding this to the Model class.

**Comment by thisismhp** [comment]
Thank you for your attention!

**Comment by devcircus** [comment]
The ide helper package does handle this.
