### ISSUE TITLE
Larave-echo Private Channel "Auth info required to subscribe to chat.1" authentication issue

### ISSUE THREAD

**Issue by AbdallahAhmed** [laravel/framework#32469]
- Laravel Version: 6.x
- PHP Version: 7.4

#### routes/channel.php
Broadcast::channel('chat.1', function ($user) {
    return true;
});

notice that I also tried to put middleware inside Broadcast::route in BroadcastServiceProvider boot method.

#### app.js
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '-------',
    cluster: 'eu',
    encrypted: true,
    authEndpoint: "http://***.dev/auth",
    auth: {
        headers: {
            Authorization: "Bearer " +  localStorage.getItem("token"),
        }
    }
});
window.Echo.private('chat.1')
            .listen('MessageSent', function (message) {
            console.log(message);
        });

#### It's working well with the public channels, I don't what's the problem!!! 
Pusher returns an error "Auth info required to subscribe to chat.1"

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
