### ISSUE TITLE
firstWhere merges pivot attributes with model on belongsToMany relation

### ISSUE THREAD

**Issue by Vinimaks** [laravel/framework#32464]
- Laravel Version: 6.18.1
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
On many to many relations when call `firstWhere()` on builder it returns model without `pivot` but all of `pivot` attributes are merged to the model. If you call `where()->first()` instead it works fine. On the examples below, you can see that the `options` and other fields were overwritten
![firstWhere](https://user-images.githubusercontent.com/17598095/79768479-853a9080-8333-11ea-936a-52bacf7706aa.png)
![where](https://user-images.githubusercontent.com/17598095/79768502-8c619e80-8333-11ea-9a39-8bf932fc3c30.png)

### Steps To Reproduce:

1. Create many to many relations with custom pivot model
2. Call firstWhere() on builder
3. Done.

**Comment by driesvints** [comment]
That indeed seems like a bug to me.

**Comment by staudenmeir** [comment]
We need to add [`firstWhere()`](https://github.com/laravel/framework/blob/0946c3eb93cfe70a895bcae67d47c341d990a781/src/Illuminate/Database/Eloquent/Builder.php#L247) to the `BelongsToMany` relation. The same goes for `HasManyThrough`.

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/framework/pull/32525
