### ISSUE TITLE
Mutator usage for foo->bar (JSON) syntax.

### ISSUE THREAD

**Issue by mathieutu** [laravel/framework#32463]
- Laravel Version: 7.6.2
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:

Hi, 
We can't use mutator for `foo->bar` syntax in eloquent model.

In fact the `hasSetMutator` function is looking for `setFoo>barAttribute`, because of the `Str::studly` transformation, which is not a valid method name.

On way to do that would be to strip the `>` character before looking for a method, so it would look for `setFooBarAttribute` which can be considerate ok for me.

I can do the PR if you're ok with that. 
Or if not, please feel free if you have any solution that I can implement in a PR.

### Steps To Reproduce:

`$user->update(['foo->bar' => 'baz'])`

Thanks.

**Comment by driesvints** [comment]
I wouldn't expect that to work at all tbh. You're free to attempt a PR as this seems more like a feature request. Thanks.
