### ISSUE TITLE
Mysql query silently failing

### ISSUE THREAD

**Issue by tdjac0bs** [laravel/framework#32468]
- Laravel Version: v6.18.7
- PHP Version: 7.2.30
- Database Driver & Version: mysql 8

### Description:
A query that fails when using DBeaver, doesn't trigger exception when using Laravel.

### Steps To Reproduce:
1 - Execute the following code:
```php
try{
$data = DB::select( DB::raw ("select ( select 1 as a union all select 2 as a ) b"));
var_dump($data);
} catch (\Exception $e){
die( 'error' );
}
```

It would be expected to see the 'error' message, but system returns `array(0) { } `

Please note that executing the same query throws exception in DBeaver:
![image](https://user-images.githubusercontent.com/2075267/79816699-36542180-835a-11ea-9391-5cd610fc3fae.png)

**Comment by staudenmeir** [comment]
This is not a Laravel issue but a PHP bug.

It only occurs when `PDO::ATTR_EMULATE_PREPARES` is set to `false`.

You can reproduce it with a native `PDO` connection:

```php
$pdo = new PDO('mysql:host=127.0.0.1;port=3306;dbname=homestead', 'homestead', 'secret');
$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
$pdo->query('select ( select 1 as a union all select 2 as a ) x');
dump($pdo->errorInfo());
```

You get the expected error when removing the second line or setting the attribute to `true`.

**Comment by driesvints** [comment]
Please see the answer above.

@staudenmeir thanks for helping out 👍

**Comment by tdjac0bs** [comment]
Hello. Thanks for the answer. 

However it does not explains why is laravel using the PDO::ATTR_EMULATE_PREPARES as false, and if we can make it work as expected in Laravel.

Thank you.

**Comment by staudenmeir** [comment]
Laravel has always been using `false` because it's the recommended setting nowadays.

You can override it for your application's MySQL connection in `config/database.php`:

```php
'mysql' => [
    ...
    'options' => [
        PDO::ATTR_EMULATE_PREPARES => true,
    ],
],
```

I wouldn't recommend that because it can have side effects.

What's your use case that you are running invalid queries?

**Comment by tdjac0bs** [comment]
Hello @staudenmeir , you're saying it's a PHP bug, can you share the link of this PHP bug?

The use case is a BI system ( it generates the SQL dynamically ), we can't really ensure that query will not be invalid, that's why we want an exception being trowed so we can notify user about mistake.

**Comment by staudenmeir** [comment]
https://bugs.php.net/bug.php?id=72076
