### ISSUE TITLE
Breaking change and Exception: Collection->groupBy() with callable in the form [$object, 'method']

### ISSUE THREAD

**Issue by LMCom** [laravel/framework#32470]
- Laravel Version: 7.6.2
- PHP Version: 7.3.17
- Database Driver & Version:

### Description:
A breaking change was introduced with version 5.5. It is still there.
To allow multi level grouping, it is checked, if $groupBy is an array.

See
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Collection.php#L431

Introduced:
https://github.com/laravel/framework/commit/4fb6206a1c6b6950ffdd93c65fa8d43ae7d0c6b9#diff-1f18a78060929ba4f93e96a4d21d022dR657

If $groupBy is an array, the multi level code path is used. However, $groupBy can be a callable, and a callable can be in the form `[$object, 'method']`. In this case, it should be treated like other callables that are passed to `$this->valueRetriever()` a few lines later. This was the behaviour before this change.

This is not only a breaking change, but also a bug, because it leads to an exception in data_get() in helpers.php: "explode() expects parameter 2 to be string, object given".

### Steps To Reproduce:
Call the method accordingly.

**Comment by patriziotomato** [comment]
Some of the rare reasons to hate PHP :-(
https://stackoverflow.com/questions/32459408/php-callable-method-not-as-array

**Comment by driesvints** [comment]
I sent in a PR for this: https://github.com/laravel/framework/pull/32471
