### ISSUE TITLE
Old version of docs don't including a warning that they're documentation for an unmaintained version

### ISSUE THREAD

**Issue by paulcdejean** [laravel/framework#32484]
I know docs issues are supposed to go in via pull request to the docs repo, but I wasn't sure how to do a pull request for this request because of the nature of it.

For symfony if you view documentation for a version that's no longer maintained you get a warning: "WARNING: You are browsing the documentation for Symfony 3.3 which is not maintained anymore. Consider upgrading your projects to Symfony 5.0."

You can view this page to see an example: https://symfony.com/doc/3.3/page_creation.html

Laravel docs for old versions have no such warning. For example: https://laravel.com/docs/4.2/eloquent

Why is this important? Well search engines can return old versions of docs in their results for quite some time, and it's pretty impossible to guarantee that on google the 7.x docs version shows up before the 5.5 docs version for example. Adding a warning would help prevent a degree of developer confusion when they're googling for a solution, as well as encouraging more people to upgrade to the latest and greatest version of laravel!

**Comment by driesvints** [comment]
The support policy clearly indicates which version is supported or not: https://laravel.com/docs/7.x/releases#support-policy

**Comment by mfn** [comment]
@driesvints FWIW I also support the idea of @paulcdejean 

People may not realize what they current version is when they arrive at the docs and thus might not suspect to check the specific page. Not everyone is as much as involved as we are.

I banner on older versions would also clearly help in my opinion

**Comment by driesvints** [comment]
Hmm, yeah maybe that's true. I'll run it over with Taylor.

**Comment by driesvints** [comment]
Did an attempt here: https://github.com/laravel/laravel.com-next/pull/119
