### ISSUE TITLE
viewAny method on policies not working

### ISSUE THREAD

**Issue by enbermudas** [laravel/framework#32486]
- Laravel Version: `7.0`
- PHP Version: `7.4.4`
- Database Driver & Version: `mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64)`

### Description:
The `viewAny` method on my policies is not working. The rest of the methods are working just fine in every single policiy excepting that particular one.

### Steps To Reproduce:

1. Generate a policity with the artisan command

```bash
php artisan make:policy ThreadPolicy --model=Models\\Thread
```

2. Add the next piece of code the the `viewAny` method

```php
/**
 * Determine whether the user can view any thread.
 *
 * @param  \App\User $user
 * @return mixed
 */
public function viewAny(User $user)
{
    return true;
}
```

3. Register the policy at `app\AuthServiceProvider.php`

```php
/**
 * The policy mappings for the application.
 *
 * @var array
 */
protected $policies = [
    // 'App\Model' => 'App\Policies\ModelPolicy',
    Thread::class => ThreadPolicy::class,
];
```

4. Add the constructor function to the `ThreadController`

```php
public function __construct()
{
    $this->middleware('auth:sanctum')->except(['index', 'show']);
    $this->authorizeResource('thread');
}
```

5. Create the index method on the `ThreadController`

```php
/**
 * List threads.
 *
 * @param \IndexRequest $request
 *
 * @return \Illuminate\Http\JsonResponse
 */
public function index(IndexRequest $request)
{
    $per_page = $request->query('per_page') ? $request->query('per_page') : 5;
    $threads = Thread::paginate($per_page);

    return response()->json($threads);
}
```

6. Create the route

```php
Route::middleware('auth:sanctum')->prefix('thread')->group(function () {
    Route::get('/', 'ThreadController@index');
});
```

7. Serve the application and perform a GET request to the endpoint
```json
{
    "message": "This action is unauthorized.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
    "file": "/home/kike/prs/projects/rpbb/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 224
}
```

**Comment by innoflash** [comment]
Have you tried using ```Thread::class``` instead of a string the authorizeResource method?

**Comment by enbermudas** [comment]
@innoflash I'm currently using the `Thread::class`. The problem is that now I have to remove the `except()` from my constructor in order to make them work. Like this:

```php
public function __construct()
{
    $this->middleware('auth:sanctum');
    $this->authorizeResource(Thread::class);
}
```

With that update I do have the authorization functionality that I wanted, but now all my routes are requiring the authentication, which is not my intention. I would like to have both the index and show of every model accessible to guests.

**Comment by driesvints** [comment]
Isn't the problem that you're defining `auth:sanctum` twice? It shouldn't be in your routes file as you're defining it on your controller already.

**Comment by driesvints** [comment]
I think the problem is the duplicate middleware call. Remove the middleware call from your routes and try again.
