### ISSUE TITLE
Merge of query bindings bug

### ISSUE THREAD

**Issue by warna720** [laravel/framework#32490]
- Laravel Version: 5.8
- PHP Version: 7.2.4
- Database Driver & Version: 10.3.10-MariaDB

### Description:
When the query bindings of a where clause is merged, the third parameter is merged with single quotes and not backticks when suitable.

### Steps To Reproduce:
```php
DB::table('profiles')
    ->join('messages', 'profiles.id', '=', 'messages.receiver_id')
    ->where('messages.created_at', '>', 'profiles.updated_at')
```
results in the following query:
```sql
select * from `profiles` inner join `messages` on `profiles`.`id` = `messages`.`receiver_id` where `messages`.`created_at` > 'profiles.updated_at'
```
When I manually execute the query with backticks instead of single quotes, I get the expected result:
```sql
select * from `profiles` inner join `messages` on `profiles`.`id` = `messages`.`receiver_id` where `messages`.`created_at` > `profiles`.`updated_at`
```
Maybe I missed something, I checked in discord server but did not get an accepted answer.

**So problem is, query bindings is not merged with backticks when suitable.**

**Comment by staudenmeir** [comment]
`where()` is for comparisons between a column and a value, use `whereColumn()` for comparisons between two columns:

```php
DB::table('profiles')
    ->join('messages', 'profiles.id', '=', 'messages.receiver_id')
    ->whereColumn('messages.created_at', '>', 'profiles.updated_at')
```

> when suitable.

Laravel can't know when to interpret the third argument as a column name.

**Comment by warna720** [comment]
That what I was looking for. Thank you so much!
