### ISSUE TITLE
Shallow nested resource results in 404 for create route of parent

### ISSUE THREAD

**Issue by amshehzad** [laravel/framework#32503]
- Laravel Version: 7.3.0
- PHP Version: 7.3.12
- Database Driver & Version:

### Description:
I create a route resource for Announcements, it worked fine. then I created a nested resource for group announcements and it worked too. but I noticed that if I create shallow nesting, the announcement create page results in 404
Here is my routes list:
![image](https://user-images.githubusercontent.com/15146578/80039156-97bdf100-8510-11ea-9150-c321db401771.png)

everything is fine except that if go to announcements/create it gives a 404,
if I create nested resource without shallow, everything works fine

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by amshehzad** [comment]
Hello @driesvints , thank you for your attention, yes I acknowledge this as a possible bug, I just did not posted this for the support here as I find this as a bug so I'll be glad if you can check this out :)
