### ISSUE TITLE
External Google Tools break env() function for config:cache

### ISSUE THREAD

**Issue by KeithTurkowski** [laravel/framework#32504]
- Laravel Version: 6.2
- PHP Version: 7.3.16
- Database Driver & Version: MySQL

### Description:

I recently ran `php artisan config:cache` and subsequently received a Google Search Console notification that my schema had errors, after looking into it extensively, I narrowed it down to the `config:cache` command and interactions with the `env()` function and the Google Structured Data Testing Tool: https://search.google.com/structured-data/testing-tool

I cannot reproduce the error independently from my own machine, if I load the page with `config:cache` and again after `config:clear` it produces identical HTML (verified with SFV hash check).

### Steps To Reproduce:

1. Use a basic Laravel site
2. Create or modify a blade file to include `{{ env('APP_URL', 'Google Sees This') }}`
3. From the console run `php artisan config:clear`
4. Load the URL for the blade in a web browser, and inspect the source to observe the APP_URL value as set in the .env file
5. Load the page using Google Structured Data Testing Tool: https://search.google.com/structured-data/testing-tool
6. Observe the HTML markup in the tool shows the same APP_URL value
7. From the console run `php artisan config:cache`
8. Load the URL for the blade in a web browser, and inspect the source to observe the same APP_URL value as set in the .env file
9. Load the page using Google Structured Data Testing Tool: https://search.google.com/structured-data/testing-tool
10. Observe the HTML markup in the tool shows 'Google Sees This' instead of the correct APP_URL value from the .env file

Really weird error, but it seems like an external tool shouldn't be causing the .env() function to fail to return data from the .env file like this when `config;cache` is run.

**Comment by devcircus** [comment]
Seems more likely an error with the tool and not laravel. A lot of these types of tools rely on brittle functionality to get data.

**Comment by driesvints** [comment]
This also doesn't seems like a Laravel bug to me. Feel free to try a support channel.

**Comment by GrahamCampbell** [comment]
> Create or modify a blade file to include {{ env('APP_URL', 'Google Sees This') }}

The problem is that you are not meant to use the env function outside of config files. Once you cache your config files, Laravel will stop bothering to read your .env file to save performance.

**Comment by driesvints** [comment]
@KeithTurkowski I always create a `settings` file myself if I need extra config options so yeah that's a valid approach. I try to leave the existing config files unaltered if possible.
