### ISSUE TITLE
Invalid route action using SAC if namespace is defined

### ISSUE THREAD

**Issue by gerardnll** [laravel/framework#32519]
- Laravel Version: 7.7.1
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
An Invalid route action exception is throw if namespace is defined in route service provider when using a single action controller.

### Steps To Reproduce:

```
Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
```
and then you define a route using a Single Action Controller (__invoke) like that in `web.php`:

```
use App\Http\Controllers\BusinessPanel\ShowDashboardPageController;

Route::prefix('panel')->group(
    function () {
        Route::get('/', ShowDashboardPageController::class);
    }
);
```

Throws:
```
UnexpectedValueException
Invalid route action: [App\Http\Controllers\App\Http\Controllers\BusinessPanel\ShowDashboardPageController].
```

Note how namespace is appended to the ::class result

**Comment by driesvints** [comment]
You can't combine these. Either remove the namespace in your service provider or use the string name of your class.

**Comment by trijulio** [comment]
Like @driesvints said, i remove the "use App\Http\Controllers\...Controller" and worked

Thanks 😃
