### ISSUE TITLE
Setting a new select for a query does not clear bindings

### ISSUE THREAD

**Issue by sebsel** [laravel/framework#32526]
- Laravel Version: 7.6.2 (and reproduced myself on 7.7.1)
- PHP Version: 7.4.0
- Database Driver & Version: Postgres 12.1

### Description:
Setting a new select for a query does not clear bindings.
For me, this started out as issue https://github.com/laravel/nova-issues/issues/2341 in Nova: saving a model related to another model which has a count in it's index-query.

### Steps To Reproduce:
- new Laravel install
- `php artisan make:model Book -m`
- add `$table->boolean('has_valid_isbn');` and `$table->foreignId('user_id');`
- on the User model, add the relation:
    ```php
    public function books()
    {
        return $this->hasMany(Book::class)->where('has_valid_isbn', true);
    }
    ```
- migrate and start Tinker:
    ```php
    >>> $query = App\User::withCount('books');
    => Illuminate\Database\Eloquent\Builder {#3013}
    >>> $query->toSql();
    => "select "users".*, (select count(*) from "books" where "users"."id" = "books"."user_id" and "has_valid_isbn" = ?) as "books_count" from "users""
    >>> $query->getBindings();
    => [
         true,
       ]
    >>> $query->select('*')->toSql();
    => "select * from "users""
    >>> $query->select('*')->getBindings();
    => [
         true,
       ]
    >>> $query->select('*')->get();
    Illuminate/Database/QueryException with message 'SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000003" requires 0 (SQL: select * from "users")
    ```

Note that this only happens with the Postgres driver. MySQL just ignores the extra bindings.

**Comment by driesvints** [comment]
Start a new query when you need to do a new select. Don't re-use an existing one.

**Comment by driesvints** [comment]
@sebsel I think so yes.

**Comment by sebsel** [comment]
@driesvints I understand the need to be conservative in the framework, especially in the database layer. I do think you're closing too soon, though.

In the `select()` method, there is already a line that sets the `$this->columns` property to an empty array: calling `select()` will overwrite everything in the select-portion of the query. (Else we can use `addSelect()`).

I think the solution to this problem would be to also add a line to set the bindings for the select-portion of the query to an empty array:

```php
    public function select($columns = ['*'])
    {
        $this->columns = [];
        $this->bindings['select'] = [];
```

It seems like a valid solution to me.

https://github.com/laravel/framework/blob/cd4e1d5bf3f4d9b11c8190ad5412e34489b6986f/src/Illuminate/Database/Query/Builder.php#L225-L240

**Comment by driesvints** [comment]
Hmm you might be correct here. Tests seem to still pass when I add this. Can you send in a PR with a test?
