### ISSUE TITLE
'name' attribute not working in Route Groups.

### ISSUE THREAD

**Issue by Sahaj-15** [laravel/framework#32528]
- Laravel Version: 7.6.2
- PHP Version: 7.2.28
- Database Driver & Version: MySQL, version 15.1

### Description:
Whenever you supply the 'name' attribute to a route group in a way like this:
`Route::group(['name' => 'admin. '], function() { });`
and then you add a route in that group and name it and then if you use the `route()` helper to get that route using `admin.name` as the parameter, it gives an error. Instead if you use `name` as the parameter (without the value of the name attribute of the group) it does work.
Not only that, you can also do something like this `Route::name()->group();` and it works as expected. Why is that so?

### Steps To Reproduce:
Make a route group as described above.
Make a route within that group and name it whatever you want.
Make any blade file and try to use the route helper to get URL of the route. The expected functionality is something like route('admin.name') but instead it gives an error. If you use route('name') it does actually work.

**Comment by driesvints** [comment]
Names need to be unique. Applying the same name to all routes within the group will cause duplicate route names and the duplicate ones will be stripped out.

**Comment by martinbean** [comment]
@driesvints I think this is a bug. This was brought up on the Laravel Discord server. I created a new Laravel app and added the following the **routes/web.php** file:

```php
Route::group(['name' => 'admin.'], function () {
    Route::get('/foo', function () {
        return response('Foo');
    })->name('foo');
});
```

When I ran `php artisan route:list`, the `name` for **/foo** was just `foo` (so `admin.` hadn’t been prepended as I’d expect).

**Comment by driesvints** [comment]
Hmm, that indeed seems problematic. Thanks for the easy example.

**Comment by driesvints** [comment]
Urgh, just realised of course that this doesn't exists. Use the name method:

```php
Route::name('admin.')->group(function () {
    Route::get('/foo', function () {
        return response('Foo');
    })->name('foo');
});
```

**Comment by jakubzelazny** [comment]
Wouldn't `Route::group(['as' => 'admin.']` work the same as `Route::name('admin.')`?
```
Route::group(['as' => 'admin.'], function () {
    Route::get('/foo', function () {
        return route('admin.foo');
    })->name('foo');
});
```

It would allow us to specify shared attributes in case we need it. For example, we could add a prefix to the group to access it by **/admin/foo** instead of **/foo**.
```
Route::group(['as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::get('/foo', function () {
        return route('admin.foo');
    })->name('foo');
});
```

**Comment by driesvints** [comment]
No, that's not supported atm.
