### ISSUE TITLE
Accessing not provided console command argument/option does throw an exception instead of returning null (as documented)

### ISSUE THREAD

**Issue by strongholdmedia** [laravel/framework#32527]
- Laravel Version: 5.x, 6.x, 7.x
- PHP Version: 7.3.14
- Database Driver & Version: irrelevant

### Description:

Documentation states in the `Artisan Console > Command I/O > Retrieving input` section:

> ```php
> // Retrieve a specific option...
> $queueName = $this->option('queue');
> 
> // Retrieve all options...
> $options = $this->options();
> ```
> If the argument or option does not exist, `null` will be returned.

This is _wrong_.
In reality, an error results, as per `The "%s" argument/option does not exist.`.

_I am somewhat confident that this is the behaviour of the underlying `symfony/console`_ - just have no idea if this is intended or not.
If it is - which I suspect - then the documentation should be updated (to reflect on the fact that a `hasArgument()`/`hasOption()` wrapping should instead be added).

I contemplated creating a merge request for it (later) but would like to hear your thoughts on the matter first.

FWIW, this was supposedly also problematic in 4.x (as apparent from some Laracasts post), is as such in all our L5.x versions (5.6-5.8), and per the documentation it should also be so for 7.x.

### Steps To Reproduce:

* Create a console command
* Add an option (optional or otherwise) with no default value
* Run the command without providing the option, and expect `$this->option()` to return (at least) null

**Comment by GrahamCampbell** [comment]
I think this is correct? It only returns null if the option is valid and optional, but not provided?

**Comment by driesvints** [comment]
@GrahamCampbell is correct.

**Comment by strongholdmedia** [comment]
There might be some confusion on my side then.

You mean that the `option` and the `argument` works differently?

The error is also thrown for an optional option, without a default value (that is, one with a question mark).
Is that syntax only supported for arguments?

**Comment by strongholdmedia** [comment]
Well, given that it is weekend, and I might just as well have had answered my own question instead of always waiting for someone else to test it :D I did a test, and thus _can confirm that the question mark syntax for optional options does not seem to be supported, nor this fact mentioned_.

I still suggest that the documentation is misleading though.
Seemingly in 5.1, the documentation (and I suspect the console argument handling internals as well) changed. As far as I am concerned, 5.0 seems to have used the Symfony underlying syntax that distinguishes between _optional options_ and _optional values_.
I think this may have been the source of confusion that may have led to the current situation.
But ever since then, as long as currently, it states that

> If the argument or option does not exist, null will be returned.

Which, to me, seems clearly not matching the actual behavior. :)

My question towards consensus thus would be whether you would rather alter the documentation to match the actual situation, and/or improve the option handling so that it would support _both optional options and optional values_.

I understand that this may at first seem redundant for people working exclusively on Web projects and/or Windows, but please remember that for "shell people" it is _more than daily_ to use arguments "--do" as true, without explicit values, and false when omitted (or even defaulting to true and "--dont" being the "disable" counterpart - same as "--whatever" for on and "--no-whatever" for off).

_I am absolutely willing to help, but first, I think, the matter should be decided upon, taking possible "breaking changes" into account (that would currently only be use cases where options are used with literal question marks in their names, I guess)._

**Comment by driesvints** [comment]
@strongholdmedia feel free to send in a PR to the docs if you think something can be clarified 👍

**Comment by strongholdmedia** [comment]
Shall this mean that you are _against_ changing the current behavior to be consistent instead?

**Comment by strongholdmedia** [comment]
> I think this is correct? It only returns null if the option is valid and optional, but not provided?

But it doesn't.
In fact there is no (documented) way to create an option as optional, at least in the signature.
