### ISSUE TITLE
Eloquent doesn't check deleted_at column in join clauses (inner join, outer join etc.)

### ISSUE THREAD

**Issue by Baha2rM** [laravel/framework#32520]
- Laravel Version: 7.7.1
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
When I use an inner join clause on a eloquent model It retrieves all columns include the rows that their deleted_at is NOT NULL.
Assume that we have 2 model State and City and these tow have one to many relation, when I run State::query()->join('cities', 'cities.state_id','states.id')->where('id',1)->get() query, It It retrieves state 1 with its cities included deleted_at=2020-0x-xx xx:xx:xx cities.

### Steps To Reproduce:
We try to develop a package to solve this problem by checking deleted_at rows in join clauses:
https://github.com/BlackPlatinum/laravel-softdelete-fixer

**Comment by driesvints** [comment]
You're not referencing a model here. You're using a raw join. So the query builder can't apply any soft deleting behavior because it can't know that the table is a model with the SoftDeletes trait applied.

**Comment by Baha2rM** [comment]
So if I use pure eloquent it will check for deleted_at rows in join clauses automatically?
