### ISSUE TITLE
Event broadcasting - The default Redis setup seems contradictory with Laravel Echo

### ISSUE THREAD

**Issue by Shizzen83** [laravel/framework#32535]
- Laravel Version: 7.0
- PHP Version: 7.4

### Description:
A few months ago, I faced a no-error issue while installing a Redis/Laravel Echo Server/Laravel Echo stack. I tried to listen to an event on a private channel. Everything looked fine but the default Redis config triggers an unexpected behavior about channel naming because of this

```php
'prefix' => Str::slug(env('APP_NAME', 'laravel'), '_').'_database_',
```

On a broadcasting, the channel name gets automatically prefixed by this value and it becomes impossible to match with `Echo.private(channel)` from Laravel Echo which expects a `private-*` channel (e.g. `app_database_private-test` vs `private-test`). To make it work, I had to replace this prefix with empty string.

### Steps To Reproduce:

Recently I helped someone on StackOverflow who faced it too, that's why I decided to open this issue. Every detail is available here:

https://stackoverflow.com/questions/61224586/unable-to-authenticate-laravel-private-channel-using-laravel-echo-server-redis/61224814#61224814

You can notice the unexpected formatting `[1:21:22 PM] - IQ7eT9P_RzF62lRSAAAA could not be authenticated to app_database_private-message.3`

### Documentation:
Moreover, there is nothing mentioned in the documentation about this, then if nothing is done in project template, I'd appreciate a lot at least a warning in this documentation.

Thanks in advance for the other devs!

(and personal thanks for this amazing framework!)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
FYI: there have been lots of issues with this but it always boiled down to misconfiguration. This one could be related to the prefix setting in laravel-echo-server.
