### ISSUE TITLE
SetCacheHeaders doesn't work because of the weak validator

### ISSUE THREAD

**Issue by flamisz** [laravel/framework#32539]
- Laravel Version: 7.5.2
- PHP Version: 7.4.2
- Database Driver & Version: N/A

### Description:

I use the `SetCacheHeaders` middleware on a route with this settings: 
`'cache.headers:public;max_age=60;etag'`

I don't know how to modify it, but it makes a weak etag like: 
`W/"e83027935c9ccb2374beae1b78a756c1"`

The problem is that, when the browser send the request when the cache expires, it sends a header like this:
`If-None-Match: W/"e83027935c9ccb2374beae1b78a756c1"`

But when the middleware checks the etag of the requests, it generates the etag for the response without the `W/` so the comparison will be false.

I tried to debug like this: 
`dd(request()->getETags());` -> 
`[ 0 => "W/"e83027935c9ccb2374beae1b78a756c1""]`

And if I `dd` this: `dd(md5($response->getContent()));` -> 

`"e83027935c9ccb2374beae1b78a756c1"`

### Steps To Reproduce:
Create a route and add the middleware: `->middleware('cache.headers:public;max_age=60;etag');`

Your development environment has to support cache and etags. Valet doesn't do that.

Thanks

**Comment by driesvints** [comment]
Isn't this more of a feature request for weak etags? I can see a potential `etag:weak;` value like this that could surround the hash with `W/" "` maybe. At the moment I don't see any way for weak etags to work.

**Comment by flamisz** [comment]
Yes, probably you're right, I just don't really know why it got a weak tag, maybe it's not framework related at all, but environment?
I think I can just create an other middleware where I clean etags from the the weak tag if any.
Thanks anyway.
