### ISSUE TITLE
Pagination data missing from api resource.

### ISSUE THREAD

**Issue by ChristopherCarranza** [laravel/framework#32548]
- Laravel Version: 7.8.1
- PHP Version: 7.4.2
- Database Driver & Version: MySql & 5.7

### Description:
When sending an eloquent query to an api resource with pagination the pagination data is missing from the result.

Laravel 6.x

```json
{
  "current_page": 1,
  "data": [
    {
      "id": 10000196,
      "name": "John Doe",
    }
  ],
  "first_page_url": "http://www.mysite.com/users?page=1",
  "from": 1,
  "next_page_url": "http://www.mysite.com/users?page=2",
  "path": "http://www.mysite.com/users",
  "per_page": 1,
  "prev_page_url": null,
  "to": 1
}
```
Laravel 7.x

```json
[
  {
    "id": 10000196,
    "name": "John Doe",
  }
]
```

### Steps To Reproduce:

Using a fresh laravel app with the default user table and at least one user in the database.

```php
$resource = \App\Http\Resources\User::collection(\App\User::query()->paginate(1));

dd($resource->toJson());
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by cwilby** [comment]
Briefly chatted with Chris on Larachat, I found a similar issue upgrading a codebase that paginates records using `JsonResource::collection` instead of creating a ResourceCollection.

Example action:

```php
<?php

namespace App\Domain\Post\Actions;

use App\Domain\Post\Models\Post;
use App\Domain\Post\Resources\PostResource;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class GetTodaysPosts extends Controller
{
  public function __invoke(Request $request)
  {
    return PostResource::collection(Post::today()->paginate(
      $request->pageSize ?? 10,
      ['*'],
      'page',
      $request->page ?? 1
    ));
  }
}
```

Example resource:

```php
<?php

namespace App\Domain\Post\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PostResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->getKey(),
            'title' => $this->title,
            'description' => $this->description
        ];
    }
}
```

With this setup, when the resource is serialized, I don't see a paginated response similar to @ChristopherCarranza.

**Comment by cwilby** [comment]
As a note, it may be that `ResourceCollection` is the preferred approach according to the documentation.

https://laravel.com/docs/7.x/eloquent-resources#pagination

It does still leave questions around the usage of `JsonResource::collection`.

**Comment by driesvints** [comment]
Re-opening this. Currently a bit strapped on time so appreciating anyone helping out here.

**Comment by taylorotwell** [comment]
Hey there, we document that you need to use an actual collection to do this: 

![image](https://user-images.githubusercontent.com/463230/80498674-a30a8580-8931-11ea-9a3f-f7bd0ecbe119.png)

Note the section about no extra metadata being added.

**Comment by taylorotwell** [comment]
Although even this works for me on latest Laravel 7:

```php
    return UserResource::collection(User::paginate(10));
```

**Comment by cwilby** [comment]
Returning paginated resources from routes works 👍 

```php
Route::get('/users', function() {
    return \Illuminate\Http\Resources\Json\JsonResource::collection(
        \App\User::paginate(10)
    );
});
```

Calling `toJson` directly still returns only the paginated rows without meta.  Personally, I don't use this feature but some might.

```php
    return UserResource::collection(User::paginate(10))->toJson();
```

**Comment by mahbodsh** [comment]
I have developed a helper to generate all required pagination data of ResourceCollection and it can be accessed through the below link:

https://gist.github.com/mahbodsh/1c9f181bdb96c15b98247aedea168349
