### ISSUE TITLE
assertSessionHas assertions don't work correctly when using PHPUnit 9

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#32541]
- Laravel Version: 7.8.1
- PHP Version: 7.4.4
- Database Driver & Version: Mysql 5.7
- Session driver: array

### Description:
After a updating PHPUnit from 8 to 9  some of my tests started failing, for example:
```php
$this->userLogin()
    ->postBuy('something invalid')
    ->assertStatus(302)
    ->assertSessionHasErrors(['invalidAmount' => true]);
```

After some debugging, this seems to be the culprit:

```php
public function assertSessionHasErrors($keys = [], $format = null, $errorBag = 'default')
{
    $this->assertSessionHas('errors');

    $keys = (array) $keys;

    $errors = $this->session()->get('errors')->getBag($errorBag);
    dump($errors);
    foreach ($keys as $key => $value) {
        // $value === "1"
        dump($errors->get($key, $format));
        
        // This assertion fails when using PHPUnit 9
        // PHPUnit::assertContains(true, [0 => "1"]);
        PHPUnit::assertContains($value, $errors->get($key, $format));
    }
```

The result of the first dump is:
```
// dump($errors);

Illuminate\Support\MessageBag^ {#4970
  #messages: array:2 [
    "oops" => array:1 [
      0 => true
    ]
    "invalidAmount" => array:1 [
      0 => true
    ]
  ]
  #format: ":message"
}

```

The result of the second dump is:
```
// $key === 'invalidAmount'
// dump($errors->get($key, $format));

array:1 [
  0 => "1"
]
```

---
Maybe the real issue here is that `[0 => true]` gets turned into `[0 => "1"]` when getting it from the error bag.

**Comment by driesvints** [comment]
> Maybe the real issue here is that [0 => true] gets turned into [0 => "1"] when getting it from the error bag.

This is actually correct because message placeholders are populated with the values from the error bag. Because they're strings all booleans are converted to "1"s and zeros respectively. 

This bug is apparently caused by https://github.com/sebastianbergmann/phpunit/issues/3426. I'll try to send in a PR to workaround this.

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/framework/pull/32555
