### ISSUE TITLE
Integrity constraint violation on Implicit Route Binding and Has Many Through

### ISSUE THREAD

**Issue by filkris** [laravel/framework#32546]
- Laravel Version: 7.8.1
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7.24

### Description:
It is not possible to resolve child route parameter using Implicit Route Binding Custom Key via Has Many Through relationship while we have Default Key defined.

### Steps To Reproduce:
Lets say we have following structure:
routes/web.php
```php
Route::resource('{country}/jobs', 'JobController')->parameters([
    'country' => 'country',
    'jobs' => 'job:id',
]);
```
Model App\Country.php:
```php
public function jobs()
{
    return $this->hasManyThrough(Job::class, Location::class);
}
```
Model App\Location.php:
```php
public function jobs()
{
    return $this->hasMany(Job::class);
}
```
Model App\Job.php:
```php
public function getRouteKeyName()
{
    return 'slug';
}
```
When we try to resolve Job in JobController@show for example: `public function show(Country $country,  Job $job)  {}` the following error will occur:
```SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select `jobs`.*, `locations`.`country_id` as `laravel_through_key` from `jobs` inner join `locations` on `locations`.`id` = `jobs`.`location_id` where `locations`.`country_id` = 1 and `id` = 20 limit 1)```

Its not hard to figure out we can not use `id` in this situation, but `jobs.id`. 

### Possible ~~Solution~~ Workaround:
In [ImplicitRouteBinding](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Routing/ImplicitRouteBinding.php#L40) we can find that `resolveChildRouteBinding()` method is called and the method is defined inside Eloquent [Model](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Model.php#L1523):
```php
public function resolveChildRouteBinding($childType, $value, $field)
{
    return $this->{Str::plural($childType)}()->where($field, $value)->first();
}
```
If we change it to something like this:
```php
public function resolveChildRouteBinding($childType, $value, $field)
{
    $childType = Str::plural($childType);

    return $this->{$childType}()->where("{$childType}.{$field}", $value)->first();
}
```
It will work as intended. Also, it will work if we move one step closer and try the modified method with the Has Many relationship. In this case, a prepared SQL query should be like:
```sql
select * from `jobs` where `jobs`.`location_id` = ? and `jobs`.`location_id` is not null and `jobs`.`id` = ?
```

Please note, this ~~solution~~ workaround is not tested. Its just attempt to making things work and it works with Has Many and Has Many Through relationships.

**Comment by driesvints** [comment]
I don't think your solution will work because you're explicitly setting the table name while there could be cases where people want to customise that. I'm wondering if we could leverage a subquery for `HasManyThrough`.

**Comment by filkris** [comment]
This possible solution was just my attempt to figure out what is going on inside framework. I am not that deep in Laravel and its challenging to see the big picture. I agree, We should go somehow with a subquery definitely since the same problem happens if we try to to something like this:
```php
$country->jobs()->select(['id', 'name', 'slug'])->get();
```

**Comment by taylorotwell** [comment]
Fixed by: https://github.com/laravel/framework/commit/8d69454575267840643289b8de27d615cfe4bb62
