### ISSUE TITLE
Route pattern issue

### ISSUE THREAD

**Issue by Nuranto** [laravel/framework#32542]
- Laravel Version: 7.8.1
- PHP Version: 7.4.4
- Database Driver & Version: mariadb10.3

### Description:
Note : I'm not sure if that's a bug, or if it has been made like this for a purpose..

Issue is that we cannot use the same route binding twice even when using different keys.

### Steps To Reproduce:

Try to configure a route like : `post/{post:slug}-{post}.html`

You will get : 
```
Route pattern "/post/{post:slug}-{post}.html" cannot reference variable name "post" more than once.
```

Same error with a route like : `post/{post:slug}-{post:id}.html`

**Comment by driesvints** [comment]
This isn't valid. You always need to separate these patterns. `/{post}.html` wouldn't work either I believe.

**Comment by Nuranto** [comment]
What about `post/{post:slug}/{post:id}` or `post/{post:slug}/{post}` ?

**Comment by Nuranto** [comment]
What about `/post/{post:slug}/{post}` ? Or  `/post/{post:slug}/{post:id}` ?

**Comment by driesvints** [comment]
I'm not sure if that works for the scoping behavior when using implicit binding: https://laravel.com/docs/7.x/routing#implicit-binding
