### ISSUE TITLE
Eloquent returns invalid value from the date column if it defined as a primary key

### ISSUE THREAD

**Issue by adinindu** [laravel/framework#32545]
- Laravel Version: 6.18.10
- PHP Version: 7.3.2
- Database Driver & Version: MySQL 5.7

### Description:
When a table is created without an auto-increment primary key and having a date type primary key instead, retrieving date(column) from eloquent returns only year as a string. 

Having protected $dates = ['column_name'] has no effect. If column casted as a date works. 

Looks like this only effects if a date type column defined as primary_key. 

### Steps To Reproduce:
In your migration
```
Schema::create('stats', function (Blueprint $table) {            
            $table->date('date');
            $table->Integer('visits');
            $table->Integer('jobs')
            $table->timestamps();
            $table->softDeletes();
            $table->primary('date');
});
```

In your Model

use Illuminate\Database\Eloquent\Model;

```
class Stat extends Model
{
    protected $table = 'stats';
    protected $primaryKey = 'date';
    
    // Having $dates has no effect either
    protected $dates = ['date'];

    protected $fillable = [];
}
```

When accessing date column
```
$stat = \App\Stat::first();
$d = $stat->date;
// $d returns only year
```

**Comment by dkulyk** [comment]
```php
public $incrementing = false;
```

**Comment by adinindu** [comment]
> ```
> public $incrementing = false;
> ```

Thanks. Should have read documentation thoroughly.
