### ISSUE TITLE
Model error

### ISSUE THREAD

**Issue by AllexNogue** [laravel/framework#32547]
- Laravel Version: 6.0
- PHP Version: 7.2.28
- Database Driver & Version: MySQL 5

### Description:

I have in my database a column called "original" and when I needed to call it in my view I received the following error: "Array to string conversion (View: C:****\resources\views\client\projects\view.blade.php)"

I solved it by calling $file['original']

### Steps To Reproduce:

**in Model Projects:**
```
public function files() 
{
   return $this->hasMany(Files::class, 'project_id', 'id');
}

public function getFiles()
{
  return $this->files()->get();
}
```

**in view:**

```
foreach($project->getFiles() as $file){
            echo $file->original;
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
