### ISSUE TITLE
.env.testing is ignored even config cache was cleared

### ISSUE THREAD

**Issue by poldixd** [laravel/framework#32556]
- Laravel Version: 7.8.1
- PHP Version: 7.3.17
- Database Driver & Version:

### Description:

I created `.env.testing` for testing. For testing I use a separate MySQL database. The documentation says, when a `.env.testing` exists, laravel take the setting from this file.

> In addition, you may create a .env.testing file in the root of your project. This file will override the .env file when running PHPUnit tests or executing Artisan commands with the --env=testing option. https://laravel.com/docs/7.x/testing

This is the priority list:

`.env.testing` > `phpunit.xml` > `.env`

If I run the tests with `php artisan test` or `./vendor/bin/phpunit`, laravel takes only the settings from `phpunit.xml`and not from the `.env.testing`. Of course I cleared the config cache with `php artisan config:clear`.

### Steps To Reproduce:

```
$ laravel new blog
$ cp .env .env.testing
```

Modify the `.env.testing`
```
# [...]
APP_ENV=testing
DB_CONNECTION=mysql
# [...]
```

Don't modify the `phpunit.xml`. It says DB_CONNECTION = sqlite
```xml
<server name="DB_CONNECTION" value="sqlite"/>
```

Modify the `tests/Feature/ExampleTest.php` and output the `config('database.default')`
```php
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        dd(config('database.default'));
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

Now run the test with `phpunit`. Clear the config cache before!

```bash
⇒  php artisan config:clear && ./vendor/bin/phpunit
Configuration cache cleared!
PHPUnit 8.5.4 by Sebastian Bergmann and contributors.

."sqlite"
```
Same issue with `php artisan test`:

```bash
⇒  php artisan config:clear && php artisan test
Configuration cache cleared!

   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   RUNS  Tests\Feature\ExampleTest
  • basic test

  Tests:  1 passed, 1 pending
"sqlite"
```

`php artisan test --env=testing` doesn't work either.

```bash
⇒  php artisan config:clear && php artisan test --env=testing
Configuration cache cleared!

   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   RUNS  Tests\Feature\ExampleTest
  • basic test

  Tests:  1 passed, 1 pending
"sqlite"
```
If I create a config cache before with `--env=testing`, everything works fine.

```bash
⇒  php artisan config:clear && php artisan config:cache --env=testing && php artisan test
Configuration cache cleared!
Configuration cache cleared!
Configuration cached successfully!

   PASS  Tests\Unit\ExampleTest
  ✓ basic test

   RUNS  Tests\Feature\ExampleTest
  • basic test

  Tests:  1 passed, 1 pending
"mysql"
```

**Comment by GrahamCampbell** [comment]
> .env.testing > phpunit.xml > .env

This not what will actually happen. First, if you have real environment variables they will be used, then phpunit.xml may add some new ones and replace the existing ones, then if you have a .env file that will be loaded BUT existing variables will not be replaced, only new ones. If you ask for testing .env.testing will be loaded instead of .env, at the end.

**Comment by GrahamCampbell** [comment]
This exactly explains the issue you are describing. We are not going to change the default behaviour so that .env or .env.testing overrides the phpunit or existing env variables, I'm afraid, so we are not treating this as a bug report.

We did actually already consider using the overriding behaviour rather than the current behaviour in: https://github.com/laravel/framework/pull/30926. There were more convincing arguments for keeping the existing behaviour.

**Comment by cAstraea** [comment]
Does anyone have more info on this please ? I'm trying to "convience" my tests to run under "testing" env but no matter what I do   dd(getenv("APP_ENV")) always returns "local"  and phpunit.xml and .env.testing are throughly ignored. Now I'm starting to second guess if the DB_DATABE in .env.testing is not getting ignored also ? :S

I have a command that uses an external api and I don't want to make real requests when testing it and I'm using the env to return a fake implementation of it.

**Comment by 0xdfc** [comment]
@GrahamCampbell, my apologies for raising a dead issue. But, when working with tests often enough I'll need to run cases while I am in a dev / local environment. In docker builds that were provided in Laravel <= 11.x via sail, this becomes an issue, it forces a recreation of containers along with the right environment. This ends up being quite the clunky DX.

Is there a recommended way to apply modifications to the env outside of shell command level overrides? I've been doing `APP_ENV=testing php artisan test` for a while now. But I'm now running into needing more and more env variable overrides and well.. it's problematic.
