### ISSUE TITLE
[8.x] Schema Dump (MariaDB)

### ISSUE THREAD

**Issue by mvdnbrk** [laravel/framework#32552]
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: 10.4.11-MariaDB

### Description:

A `schema:dump` command is added in Laravel 8.x (PR #32275).
The `baseDumpCommand` uses `--set-gtid-purged=OFF` in the `MySqlSchemaState` class.

https://github.com/laravel/framework/blob/c389f0a4a0dfb411bf7f50edcf543a896299f73b/src/Illuminate/Database/Schema/MySqlSchemaState.php#L78-#L81

MariaDB does not have the `--set-gtid-purged` option which results in a `ProcessFailedException`. 

Error Output:
`mysqldump: unknown variable 'set-gtid-purged=OFF'`

**Comment by taylorotwell** [comment]
This should be fixed.

**Comment by iKlsR** [comment]
Encountered this issue and just upgraded to 8.0

MySQL 5.7

```
mysqldump: unknown variable 'set-gtid-purged=OFF'
mysqldump: unknown variable 'set-gtid-purged=OFF'

   Symfony\Component\Process\Exception\ProcessFailedException

  The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 7(Unknown error)

Working directory: /app

Output:
================


Error Output:
================
mysqldump: unknown variable 'set-gtid-purged=OFF'

  at vendor/symfony/process/Process.php:252
    248▕      */
    249▕     public function mustRun(callable $callback = null, array $env = []): self
    250▕     {
    251▕         if (0 !== $this->run($callback, $env)) {
  ➜ 252▕             throw new ProcessFailedException($this);
    253▕         }
    254▕
    255▕         return $this;
    256▕     }

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by Bouhnosaure** [comment]
Same here ! 

```shell
mysqldump: unknown variable 'set-gtid-purged=OFF'
mysqldump: unknown variable 'set-gtid-purged=OFF'

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 7(Unknown error)

Working directory: /app

Output:
================


Error Output:
================
mysqldump: unknown variable 'set-gtid-purged=OFF'

  at vendor/symfony/process/Process.php:252
    248▕      */
    249▕     public function mustRun(callable $callback = null, array $env = []): self
    250▕     {
    251▕         if (0 !== $this->run($callback, $env)) {
  ➜ 252▕             throw new ProcessFailedException($this);
    253▕         }
    254▕ 
    255▕         return $this;
    256▕     }

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

Client config : 

```shell
root@592ea3c7e066:/app# mysqldump --version
mysqldump  Ver 10.17 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64)
```

**Comment by mvdnbrk** [comment]
@driesvints can this be reopened?

**Comment by mvdnbrk** [comment]
I am getting:

```
mysqldump: unknown variable 'column-statistics=0'
```

**Comment by taylorotwell** [comment]
Opne a PR to fix what you want.

**Comment by taylorotwell** [comment]
I have no idea if this works for MariaDB. I only use MySQL.

**Comment by driesvints** [comment]
@iKlsR are you using the latest Laravel version?

**Comment by iKlsR** [comment]
@driesvints Yes, latest everything. Fresh project and had just upgraded, php is 7.4, mysql 5.7.31.

**Comment by mvdnbrk** [comment]
@iKlsR can you post the output of `mysql --version` ?

**Comment by iKlsR** [comment]
```
$ lando mysql --version
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
```

**Comment by iKlsR** [comment]
Ok so poking around a bit, this seems to stem from the mariadb distrib. If I comment out the flag in `baseDumpCommand()` The schema gets dumped but then I run into #34303 so I guess that might warrant some looking at **again** as well.

Reading the entire issue listing with this as well as external fixes on this I propose stripping `--column-statistics=0 '--set-gtid-purged=OFF` if the dump version has mariadb *or* maybe entirely and allow access to the underlying dump executable to allow advanced? users to pass these. If I remove those works as expected and I don't think they are relevant either, you just want a schema dump.

**Comment by ludo237** [comment]
I don't have any issue at all with MariaDB 10.5.x and latest Laravel 8.

**Comment by iKlsR** [comment]
@taylorotwell This is still not fixed sadly, column stats was just an addition, still errs with `--set-gtid-purged=OFF`. See https://stackoverflow.com/questions/48876519/mysqldump-stopped-working-with-conversion-to-mariadb-set-gtid-purged-off-issue.

Maybe just add a note in the docs, since this is a rare command, I'm fine commenting out that for now each time.
