### ISSUE TITLE
Memory leak in fzaninotto/Faker usage

### ISSUE THREAD

**Issue by bytestream** [laravel/framework#32574]
- Laravel Version: 6.18.10
- PHP Version: 7.4.5
- Database Driver & Version: N/A

### Description:
See https://github.com/fzaninotto/Faker/pull/1730

https://github.com/fzaninotto/Faker/pull/1730#issuecomment-524603785 says it should be handled in userland - similar to https://github.com/ergebnis/test-util/blob/master/src/Helper.php#L34-L47

At the moment https://github.com/laravel/framework/blob/v6.18.10/src/Illuminate/Database/DatabaseServiceProvider.php#L77 is reset on every unit test.

### Steps To Reproduce:
https://github.com/bytestream/php74-memory-leak
```
$ php7.3 vendor/bin/phpunit --repeat 100
Time: 3.78 seconds, Memory: 396.00 MB

$ php7.4 vendor/bin/phpunit --repeat 100
Time: 11.56 seconds, Memory: 734.00 MB
```

**Comment by taylorotwell** [comment]
So what exactly are we supposed to do?

**Comment by bytestream** [comment]
Keep a static instance of the generator rather than recreate it on every test, similar to https://github.com/ergebnis/test-util/blob/master/src/Helper.php#L34-L47

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/commit/222823377c936ab4cceeb1fa42db84821c04bff6

**Comment by bytestream** [comment]
Great thanks! Please can you copy to `6.x` as well, or will you accept a PR if I make one?

**Comment by deleugpn** [comment]
The fix for this introduced a new (imo worse) bug: https://github.com/laravel/framework/issues/32700
