### ISSUE TITLE
How can i retrieve entity from main morph table?

### ISSUE THREAD

**Issue by pysoftware** [laravel/framework#32579]
AdminHistory
public function entity() {return $this->morphTo();}
Services 
public function history() {return $this->morphMany(AdminHistory::class, 'entity');}
i get this from AdminHistory
"id" => 1
 "entity_type" => "App\Models\Services"
"entity_id" => 1
but i also want to get entity with ent_type and ent_id
is it possible?

**Comment by taylorotwell** [comment]
This isn't a bug report.
