### ISSUE TITLE
Eloquent collection gets null in-place of a deleted model on $collection->fresh() 

### ISSUE THREAD

**Issue by aliadhillon** [laravel/framework#32577]
- Laravel Version: 7.8.1
- PHP Version: 7.4.4
- Database Driver & Version: MySQL v5.7.29

### Description:
When we delete an model from an Eloquent collection like so
```
$collection->find($id)->delete()
```
or just
```
Model::find($id)->delete()
```
 and then to get the latest data use 
```
$collection = $collection->fresh()
```
it return null in the place of deleted model. And then if you send this collection to your view you will obviously get error **trying to get property of null**.
So shouldn't `fresh()` method just remove that deleted model from the collection instead of placing a [null](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Collection.php#L283) in it's place or this is the intended behavior and we should instead do
```
$collection = Model::all()
```
to get the latest data after a delete.

### Steps To Reproduce:
Fetch an Eloquent collection of any model from database and then delete any model that is in that collection and then use the `$collection->fresh()` method to get the fresh data from database.

**Comment by dwightwatson** [comment]
That's the behaviour if you called `fresh()` on a single record that has since been deleted (i.e. it returns `null`, so I would sort of expect the same if you called it on a collection. I think forcing you to call `fresh()->filter()` is better as it is much more explicit about your intention.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
