### ISSUE TITLE
6.x Changelog missing latest 8 releases

### ISSUE THREAD

**Issue by leewillis77** [laravel/framework#32571]
### Description:
The 6.x changelog (https://github.com/laravel/framework/blob/6.x/CHANGELOG-6.x.md) contains 6.18.2 as the latest release, and no information about the changes in 6.18.3, 6.18.4, 6.18.5, 6.18.6, 6.18.7, 6.18.8, 6.18.9, or 6.18.10

Please can we ensure this is updated *as part of making a release*

**Comment by driesvints** [comment]
We're not updating this changelog anymore.

**Comment by leewillis77** [comment]
Sorry, but that's the most unhelpful reply to an issue ever.

Is the changelog now held somewhere else (in which case can we remove, or amend the one in the repo to link to it - happy to do the PR if you want)? Or because you're just not bothering to have one? My understanding was that Laravel 6.x is an LTS release, so I really don't understand the concept of it having no release notes...

**Comment by driesvints** [comment]
Sure, feel free to send in a pr.

**Comment by leewillis77** [comment]
I would, but I have *no idea* what it would say. Are the changes documented elsewhere?

**Comment by nunomaduro** [comment]
@leewillis77 You can use this UI to see difference between versions: https://github.com/laravel/framework/compare/v6.18.2...v6.18.3. And maybe pull request updates to the changelog.

**Comment by leewillis77** [comment]
@nunomaduro So, the release notes simply aren't produced any more? I understand I can create a diff myself, and work out what the changes are, but the replies to this issue suggest that, as a project, producing release notes isn't considered important. 

If true, I find that an insane position to be taking. Producing release notes and communicating to your software's users is the basic minimum requirement to describe yourself as "releasing software" - not to mention providing "long term support". 

Are you seriously suggesting that every Laravel developer should go through the commit diffs when working through updates, or seeing if a bug they care about might be fixed by upgrading?

**Comment by brunogaspar** [comment]
@leewillis77 https://github.com/laravel/framework/releases see if that helps?

**Comment by lcdss** [comment]
There is also release notes and upgrade guides for major versions in the Laravel website.

**Comment by leewillis77** [comment]
@brunogaspar That would be nice, but the latest that contains notes for is 6.18.2

**Comment by leewillis77** [comment]
@lcdss How does that help determine what changed between 6.18.2 and 6.18.10?

**Comment by driesvints** [comment]
Send in a pr if you want.

**Comment by driesvints** [comment]
I've just added all missing releases. I'll add these myself from now on every week.
