### ISSUE TITLE
Eloquent find() method generate weird sql query

### ISSUE THREAD

**Issue by nmfzone** [laravel/framework#32587]
- Laravel Version: 7.8.1
- PHP Version: 7.3.12
- Database Driver & Version: Mysql 8.0.19

### Description:
The Eloquent `find()` method seems not generating sql as it should be, when we pass a Model to the $id parameter. The sql query maybe working as expected, but it seems weird for me.

```php
$site->participants()->find(Auth::user())
```

It will produce a query something like this:

```sql
select
  `users`.*,
  `site_participant`.`site_id` as `pivot_site_id`,
  `site_participant`.`participant_id` as `pivot_participant_id`
from
  `users`
  inner join `site_participant` on `users`.`id` = `site_participant`.`participant_id`
where
  `site_participant`.`site_id` = 1
  and `users`.`id` in (
    1,
    'John Doe',
    'johndoe@example.com',
    '2020-04-28T22:50:03.000000Z',
    '2020-04-28T22:50:03.000000Z',
    '2020-04-28T22:50:03.000000Z'
  )
```

Instead only passing the Model's ID, Laravel pass the whole Model's data.
I saw it had a method called `parseId`:

```php
/**
 * Get the ID from the given mixed value.
 *
 * @param  mixed  $value
 * @return mixed
 */
protected function parseId($value)
{
    return $value instanceof Model ? $value->{$this->relatedKey} : $value;
}
```

I assume mixed $id in `BelongsToMany::find()` can be a Model, right? Since Laravel will check if the $id is a Model, it will gets the Model's primary key value. But it seems Laravel not handle it correctly.

It affects:
- `Illuminate\Database\Eloquent\Builder::find()`
- `Illuminate\Database\Eloquent\Relations\BelongsToMany::find()`
- `Illuminate\Database\Eloquent\Relations\HasManyThrough::find()`

**Comment by staudenmeir** [comment]
> The docblock said that it accepts Model as a value.

Where does it say that? It says that it _returns_ a model.

**Comment by nmfzone** [comment]
@staudenmeir Ah, you're right. Ok, let me re-phrase my statement.

**Comment by nmfzone** [comment]
It seems this is related to https://github.com/laravel/framework/pull/30312

**Comment by nmfzone** [comment]
I don't know this use case, but in Laravel 7.x now it's impossible to pass an `EloquentCollection` into `Illuminate\Database\Eloquent\Relations\BelongsToMany::findMany()`.

In the end, I don't know this is a bug or just a feature that getting removed.

Because in 7.x there is still `Illuminate\Database\Eloquent\Relations\Concerns\InteractsWithPivotTable::parseIds()` that prepares ids from an `EloquentCollection`.

**Comment by driesvints** [comment]
Passing a model isn't supported.

**Comment by nmfzone** [comment]
@driesvints But but..in 6.x, it's still supported. Is there any documentation about this?
So what's the purpose of this https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L591 ?

**Comment by nmfzone** [comment]
Well, at least it has been fixed by @taylorotwell at the end...

https://github.com/laravel/framework/commit/353442d80722e8862c3f140b7e34c27578e89f7d#diff-fac59ee2778e54567a539e9140a1a42c
