### ISSUE TITLE
Mail settings in config/mail.php and .env ignored

### ISSUE THREAD

**Issue by schel4ok** [laravel/framework#32580]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Database Driver & Version: 

### Description:
I have TestMail class like below on local server and it is not working.
All adjusted just like in official documentation here https://laravel.com/docs/master/mail
Maildriver is Mailgun.

### Steps To Reproduce:
in controller
```
	public function TestMailSend(TestMailRequest $request) {

        Mail::to( env('MAIL_TO_ADDRESS') )->send(new TestMail());
		return [
			'message' => 'Success!', 
			'alertclass' => 'success',
				];
	}
```

app/Mail/TestMail.php
```
use Illuminate\Http\Request;
use App\Http\Requests\FreeZamerRequest;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class TestMail extends Mailable
{
    use Queueable, SerializesModels;

    public $subject = 'Test mail subject';
    
    public function __construct()
    {

    }

    public function build(FreeZamerRequest $request)
    {
        $this->view('mail.test')->withRequest($request);
    }
}
```

config/mail.php
```
    'from' => [
        'address' => env('MAIL_FROM_ADDRESS', 'noreply@myhost.ru'),
        'name' => env('MAIL_FROM_NAME', 'FromUsername'),
    ],
    'reply_to' => [
        'address' => env('MAIL_REPLY_TO_ADDRESS', 'reply@myhost.ru'),
        'name' => env('MAIL_REPLY_TO_NAME', 'ReplyUsername')
    ],

```

.env
```
MAIL_DRIVER=mailgun
MAIL_FROM_ADDRESS=noreply@myhost.ru
MAIL_FROM_NAME="${APP_NAME}"
MAIL_TO_ADDRESS=mailto@myhost.ru
MAIL_REPLY_TO_ADDRESS=reply@myhost.ru
MAIL_REPLY_TO_NAME=ReplyUsername
```

After click on sendmail button on the page I see success message 
In chrome devtools on Network tab I see status 200 OK
In Laravel Debugbar I see new mail and **FROM field is empty**!!!
```
Message-ID: <acbe4825b8e083baa54243fd55aa7f94@myhost.test>
Date: Tue, 28 Apr 2020 22:54:33 +0300
Subject: =?utf-8?Q?=D0=97=D0=B0=D1=8F=D0=B2=D0=BA=D0=B0_=D0=BD?=
 =?utf-8?Q?=D0=B0_=D0=B1=D0=B5=D1=81=D0=BF=D0=BB=D0=B0?=
 =?utf-8?Q?=D1=82=D0=BD=D1=8B=D0=B9_=D0=B7=D0=B0=D0=BC=D0=B5=D1=80?=
From: 
Reply-To: =?utf-8?Q?=D0=98=D0=BB=D1=8C=D1=8F?= <reply@myhost.ru>
To: reply@myhost.ru
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

Then I go to mailto@myhost.ru mailbox and I don't see this mail.
Then I go to mailgun account and see this mail Bounced.
Tech support in Mailgun said that it is Bounced, because FROM field is empty.

Then if I change code like that I have mail delivered
```
    public function build(Request $request)
    {
        $this->from('noreply@myhost.ru')->view('mail.freezamer')->withRequest($request);
    }
```

Why default FROM settings in config/mail.php and .env ignored?

**Comment by taylorotwell** [comment]
You shouldn't be using the `env` function outside of configuration files. You shouldn't be using it in your controller.

**Comment by schel4ok** [comment]
In Laravel 6 this code worked

**Comment by schel4ok** [comment]
Env value MAIL_FROM_ADDRESS return null whereas MAIL_REPLY_TO_ADDRESS return its value.
Why?

**Comment by devcircus** [comment]
env variables can only be trusted in config files. Some may work some may not. It's documented in Laravel docs and the package docs.

**Comment by SjorsO** [comment]
Laravel 7 renamed `MAIL_DRIVER` to `MAIL_MAILER`. This change should be backwards compatible, but I've had some trouble with it myself too.

Could you try renaming `MAIL_DRIVER` to `MAIL_MAILER` and see if that helps?

**Comment by schel4ok** [comment]
OK. No `env `outside config files. I changed like that.

controller
```
Mail::to( config('mail.to.address') )->send(new TestMail());
```

app/Mail/TestMail.php
```
$this->view('mail.test')->withRequest($request);
```

config/mail.php
```
    'from' => [
        'address' => env('MAIL_FROM_ADDRESS'),
        'name' => env('APP_NAME'),
    ],
    'to' => [
        'address' => env('MAIL_TO_ADDRESS'),
        'name' => env('toName'),
    ],
    'reply_to' => [
        'address' => env('MAIL_REPLY_TO_ADDRESS'),
        'name' => env('APP_NAME')
    ],
```

And anyway I see empty from field in laravel debugbar after this mail sent and mail is not delivered
```
From: 
Reply-To: =?utf-8?Q?=D0=98=D0=BB=D1=8C=D1=8F?= <reply@myhost.ru>
To: reply@myhost.ru
```

**Comment by taylorotwell** [comment]
This is working fine for me. I can't recreate. If you find a bug feel free to PR a fix.

**Comment by MarceauKa** [comment]
@schel4ok I had the same problem today, run `php artisan config:cache` and it'll works!

**Comment by sebdesign** [comment]
I'm facing a similar issue with Laravel 7.x locally, using a new installation.

**config/mail.php**
```php
'from' => [
    'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
    'name' => env('MAIL_FROM_NAME', 'Example'),
],
```

**.env**

The rest of the `MAIL_*` variables are correctly set with working credentials.
```env
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"
```

When I send an email without specifying the `from` address:
```php
Mail::to($user)->send(new DummyEmail());
```

then I get the following exception:
```
Swift_TransportException Cannot send message without a sender address 
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:195 Swift_Transport_AbstractSmtpTransport::send
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:71 Swift_Mailer::send
vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:521 Illuminate\Mail\Mailer::sendSwiftMessage
vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:288 Illuminate\Mail\Mailer::send
vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:170 Illuminate\Mail\Mailable::Illuminate\Mail\{closure}
vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php:19 Illuminate\Mail\Mailable::withLocale
vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:171 Illuminate\Mail\Mailable::send
vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:304 Illuminate\Mail\Mailer::sendMailable
vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:258 Illuminate\Mail\Mailer::send
vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php:122 Illuminate\Mail\PendingMail::send
...
```

I did some investigation and I found that the `mail.from.address` config value is `null`, because the `MAIL_FROM_ADDRESS` in the `.env` is set to `null`.

If I remove the `null`, i.e. `MAIL_FROM_ADDRESS=` then the config value is an empty string, which also throws the same exception.

If I remove the `MAIL_FROM_ADDRESS` from the `.env`, then the config value is `hello@example.com`, which doesn't throw an exception.

So it seems that the `env()` helper is picking up the `$default` value only if the env variable is not set **at all**.

The solution for this would be to remove the default value from the `config/mail.php` and add it to `.env.example`.

```php
'from' => [
    'address' => env('MAIL_FROM_ADDRESS'),
    'name' => env('MAIL_FROM_NAME', 'Example'),
],
```

```env
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME="${APP_NAME}"
```

@taylorotwell Should I submit a PR for this in the `develop` branch of the `laravel/laravel` repository? I think that should be fixed in the next major version.

**Comment by martanto** [comment]
> 
> 
>     * Laravel Version: 7.8.1
> 
>     * PHP Version: 7.2.19
> 
>     * Database Driver & Version:
> 
> 
> ### Description:
> 
> I have TestMail class like below on local server and it is not working.
> All adjusted just like in official documentation here https://laravel.com/docs/master/mail
> Maildriver is Mailgun.
> ### Steps To Reproduce:
> 
> in controller
> 
> ```
> 	public function TestMailSend(TestMailRequest $request) {
> 
>         Mail::to( env('MAIL_TO_ADDRESS') )->send(new TestMail());
> 		return [
> 			'message' => 'Success!', 
> 			'alertclass' => 'success',
> 				];
> 	}
> ```
> 
> app/Mail/TestMail.php
> 
> ```
> use Illuminate\Http\Request;
> use App\Http\Requests\FreeZamerRequest;
> use Illuminate\Bus\Queueable;
> use Illuminate\Contracts\Queue\ShouldQueue;
> use Illuminate\Mail\Mailable;
> use Illuminate\Queue\SerializesModels;
> 
> class TestMail extends Mailable
> {
>     use Queueable, SerializesModels;
> 
>     public $subject = 'Test mail subject';
>     
>     public function __construct()
>     {
> 
>     }
> 
>     public function build(FreeZamerRequest $request)
>     {
>         $this->view('mail.test')->withRequest($request);
>     }
> }
> ```
> 
> config/mail.php
> 
> ```
>     'from' => [
>         'address' => env('MAIL_FROM_ADDRESS', 'noreply@myhost.ru'),
>         'name' => env('MAIL_FROM_NAME', 'FromUsername'),
>     ],
>     'reply_to' => [
>         'address' => env('MAIL_REPLY_TO_ADDRESS', 'reply@myhost.ru'),
>         'name' => env('MAIL_REPLY_TO_NAME', 'ReplyUsername')
>     ],
> ```
> 
> .env
> 
> ```
> MAIL_DRIVER=mailgun
> MAIL_FROM_ADDRESS=noreply@myhost.ru
> MAIL_FROM_NAME="${APP_NAME}"
> MAIL_TO_ADDRESS=mailto@myhost.ru
> MAIL_REPLY_TO_ADDRESS=reply@myhost.ru
> MAIL_REPLY_TO_NAME=ReplyUsername
> ```
> 
> After click on sendmail button on the page I see success message
> In chrome devtools on Network tab I see status 200 OK
> In Laravel Debugbar I see new mail and **FROM field is empty**!!!
> 
> ```
> Message-ID: <acbe4825b8e083baa54243fd55aa7f94@myhost.test>
> Date: Tue, 28 Apr 2020 22:54:33 +0300
> Subject: =?utf-8?Q?=D0=97=D0=B0=D1=8F=D0=B2=D0=BA=D0=B0_=D0=BD?=
>  =?utf-8?Q?=D0=B0_=D0=B1=D0=B5=D1=81=D0=BF=D0=BB=D0=B0?=
>  =?utf-8?Q?=D1=82=D0=BD=D1=8B=D0=B9_=D0=B7=D0=B0=D0=BC=D0=B5=D1=80?=
> From: 
> Reply-To: =?utf-8?Q?=D0=98=D0=BB=D1=8C=D1=8F?= <reply@myhost.ru>
> To: reply@myhost.ru
> MIME-Version: 1.0
> Content-Type: text/html; charset=utf-8
> Content-Transfer-Encoding: quoted-printable
> ```
> 
> Then I go to [mailto@myhost.ru](mailto:mailto@myhost.ru) mailbox and I don't see this mail.
> Then I go to mailgun account and see this mail Bounced.
> Tech support in Mailgun said that it is Bounced, because FROM field is empty.
> 
> Then if I change code like that I have mail delivered
> 
> ```
>     public function build(Request $request)
>     {
>         $this->from('noreply@myhost.ru')->view('mail.freezamer')->withRequest($request);
>     }
> ```
> 
> Why default FROM settings in config/mail.php and .env ignored?




> 
> 
> OK. No `env `outside config files. I changed like that.
> 
> controller
> 
> ```
> Mail::to( config('mail.to.address') )->send(new TestMail());
> ```
> 
> app/Mail/TestMail.php
> 
> ```
> $this->view('mail.test')->withRequest($request);
> ```
> 
> config/mail.php
> 
> ```
>     'from' => [
>         'address' => env('MAIL_FROM_ADDRESS'),
>         'name' => env('APP_NAME'),
>     ],
>     'to' => [
>         'address' => env('MAIL_TO_ADDRESS'),
>         'name' => env('toName'),
>     ],
>     'reply_to' => [
>         'address' => env('MAIL_REPLY_TO_ADDRESS'),
>         'name' => env('APP_NAME')
>     ],
> ```
> 
> And anyway I see empty from field in laravel debugbar after this mail sent and mail is not delivered
> 
> ```
> From: 
> Reply-To: =?utf-8?Q?=D0=98=D0=BB=D1=8C=D1=8F?= <reply@myhost.ru>
> To: reply@myhost.ru
> ```

Clearing cache, restart supervisor and nginx work for me.
`php artisan cache:clear`
`sudo supervisorctl restart all`
`sudo nginx -s reload`

**Comment by bloodykheeng** [comment]
I've  also encountered the same issue where Laravel's mail configuration cache doesn't update properly when using the VSCode integrated terminal, but works correctly when using Windows Command Prompt or PowerShell opened through Windows Search.

## Problem

When I modify mail configurations in my `.env` file and run the standard Laravel config cache commands in VSCode's integrated terminal:

```bash
php artisan config:clear
php artisan config:cache
```

The cache appears to clear (bootstrap/cache gets cleared), but when I run:

```bash
php artisan config:show mail
```

The old configurations are still showing  thus the new configs from my `.env` file are not being cached.

## Workaround

The issue is resolved when I use Windows Command Prompt or PowerShell opened directly through Windows Search instead of VSCode's integrated terminal:

1. Open Command Prompt or PowerShell through Windows Search
2. Navigate to project directory
3. Run the same commands:
   ```bash
   php artisan config:clear
   php artisan config:cache
   ```

After running these commands in the external terminal, both VSCode terminal and the external terminal show the updated mail configurations when running `php artisan config:show mail`.
