### ISSUE TITLE
assertSessionHasInput fails when no value is supplied

### ISSUE THREAD

**Issue by ce-brex** [laravel/framework#32586]
- Laravel Version: 7.6.2
- PHP Version: 7.2.17
- Database Driver & Version:

### Description:
Trying to assert the session has just an input key always returns the key is missing.  It is trying to assertTrue on the value of the key in the old input, rather than just checking if it exists.

Changing `$this->session->getOldInput($key)` to `$this->session->hasOldInput($key)` in the call to assertTrue() when $value is null within the assertSessionHasInput method seems to make it work as intended.

### Steps To Reproduce:
Call assertSessionHasInput() while only supplying one or more keys.

**Comment by taylorotwell** [comment]
Fixed in next release.
