### ISSUE TITLE
Memory leak in View render()

### ISSUE THREAD

**Issue by kiuka** [laravel/framework#32591]
- Laravel Version: 7.8.0
- PHP Version: 7.3.17
- Database Driver & Version:

### Description:

View class does not cleanup after render causing memory leak.

### Steps To Reproduce:

I'm sending bulk emails, using view to create mail body. When pass the body as an instance of View the process starts leaking memory and leaves a few MB every time it sends an email.

I started to debug and found that it was caused by the View::render() (I didnt go any further to see the real problem, because after I just prerendered the content instead of passing it as a View).

So the code below does NOT memory leak, but if you remove ->__toString() call in build() method it starts to.

Actually the example probably could be an infinite loop of calling View->render() but I was lazy to write one:)

```
<?php

namespace App\Newsletter;

use Builder;

class Newsletter
{
    private $mailer = null;

    public function __construct()
    {
        $this->mailer = \Mail::mailer('smtp');
    }
    public function send()
    {
        $articles = $this->getArticles();
        $news = $this->getArticles();

        // generate email body
        $body = $this->build($articles, $news);

        $emails = $this->getEmails();

        foreach ($emails as $key => $email) {
            $this->sendEmail($email->email, $body);
        }
    }

    private function build(Collection $articles, Collection $news)
    {
        $builder = new Builder();

        // builder html() and text() return an instance of the created View

        return [
            'html' => $builder->html($this->getSubject(), $articles, $news)->__toString(),
            'text' => $builder->plainText($this->getSubject(), $articles, $news)->__toString()
        ];
    }

}
```

**Comment by bytestream** [comment]
I think you'll need to produce a test repo and a command / url which demonstrates the issue.

**Comment by kiuka** [comment]
Oh damn, I just realized that it was a getter in my view that was called every time when the view was rendered.

thanks:)
