### ISSUE TITLE
Use Phpredis Class 'Redis' not found

### ISSUE THREAD

**Issue by anyforever** [laravel/framework#32590]
- Laravel Version: 7.6.0
- PHP Version: 7.2.30
- Database Driver & Version:

### Description:
I removed the Redis facade alias in my config/app.php and composer removed predis
use supervisord
php artisan queue:work --sleep=3 --tries=3
Redis Support | enabled
Redis Version | 5.2.1
Redis Sentinel Version | 0.1
Available serializers | php, json, igbinary
Available compression | zstd

### Steps To Reproduce:
Class 'Redis' not found

  at /usr/local/var/www/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:74
    70|      * @throws \LogicException
    71|      */
    72|     protected function createClient(array $config)
    73|     {
  > 74|         return tap(new Redis, function ($client) use ($config) {
    75|             if ($client instanceof RedisFacade) {
    76|                 throw new LogicException(
    77|                         extension_loaded('redis')
    78|                                 ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'

  • A class import is missing: You have a missing class import. Try importing this class: `Illuminate\Support\Facades\Redis`. 

      [2m+25 vendor frames [22m
  26  /usr/local/var/www/project/artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

   Error

**Comment by anyforever** [comment]
Redis can work normally except supervisord  run queue

**Comment by anyforever** [comment]
I found the cause of the problem，my local install php 7.2 and 7.3，but php7.3 no redis，supervisord conf file run the queue in PHP 7.3

**Comment by smartssa** [comment]
For anyone who stumbles upon this, just make sure you have the PECL Redis extension installed for each of your versions, as well as the `predis/predis` composer package.
