### ISSUE TITLE
laravel new project --auth doesn't create HomeController.php

### ISSUE THREAD

**Issue by mariandmt** [laravel/framework#32598]
I have created a new laravel project with --auth, but HomeController hasn't been created. I have also tried with composer require laravel/ui and php artisan ui vue --auth in an existing project and I encounter the same problem. Thanks

**Comment by cbaconnier** [comment]
It has been fixed few minutes ago https://github.com/laravel/ui/pull/100

**Comment by mariandmt** [comment]
Great. Thanks

**Comment by taylorotwell** [comment]
Fixed.
