### ISSUE TITLE
Wrong count() on Eloquent Builder when using groupBy statements

### ISSUE THREAD

**Issue by Skullbock** [laravel/framework#32592]
- Laravel Version: 7.7.1
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8.0

### Description:
Follow up of #4306

In Eloquent, when you try to ```count()``` on a query builder instance that has active ```groupBy``` statements, the count retrieved is wrong.

### Steps To Reproduce:

Try to run a count on a grouped query builder:

```php

$count = \App\YourModel::query()
           ->groupBy([
                'some_group_by_column',
                'some_other_group_by_column'
            ])
          ->count();
```

### Solution:

This issue is commonly resolved by counting the rows in the subquery.

```php
$count = (int) DB::query()
            ->selectRaw('COUNT(' . $columns . ') as count')
            ->fromSub(\App\YourModel::query()
                ->groupBy([
                    'some_group_by_column',
                    'some_other_group_by_column'
                ]), 'agg')
            ->value('count');
```

I'm by no means a DB expert, so i would like to receive some guidance on how to PR a fix for this.
Maybe @driesvints has some hints?

Thanks

**Comment by staudenmeir** [comment]
Please see #28931 and https://github.com/laravel/ideas/issues/1693.

**Comment by Skullbock** [comment]
Thanks

**Comment by laratuto** [comment]
[easy download code](https://laratuto.com/group-by-in-laravel-php-laravel/)
