### ISSUE TITLE
Making internal requests using app()->handle() will stop Session from persisting

### ISSUE THREAD

**Issue by jorovow** [laravel/framework#32595]
- Laravel Version: 7.4.4
- PHP Version: 7.2.5
- Database Driver & Version: 10.4.11-MariaDB

### Description:
If you make internal requests using app()->handle() no changes you make to the Session will persist anymore.

### Steps To Reproduce:
1. Make an invokable controller with the code below and refresh it a couple of times.
2. Now change true to false in the if-statement.
3. Now the session will start persisting.

```
public function __invoke(Request $request)
{
    var_dump($request->session()->get('test'));     // null; no matter how many times your refresh, unless you change if statement's true to false...
    $request->session()->put('test1', 123);
    var_dump($request->session()->get('test'));     // 123;
    
    if (true) {     // change this to false and test will now start persisting to 123
        var_dump(app()->handle(\Request::create('/', 'post'))->getContent());
    }
    
    return;
}
```

**Comment by X-Coder264** [comment]
Subrequests are a Symfony thing. Laravel does not official support them (as you can see there is nothing about them in the documentation) so it's no wonder that some things don't work as you'd expect when you use them.

**Comment by taylorotwell** [comment]
Yeah sub requests are not really an officially supported Laravel thing as I consider them essentially an anti-pattern.
