### ISSUE TITLE
Exception throw with Parameterless Component Methods

### ISSUE THREAD

**Issue by tomsix** [laravel/framework#32596]
- Laravel Version: 7.9.2
- PHP Version: 7.4.4
- Database Driver & Version: /

### Description:
 
Today I updated a project to the latest Laravel v7.9.2 and got issues with parameterless component methods. I get a 'Facade\Ignition\Exceptions\ViewException 
array_key_exists()' exception ([see flare.io](https://flareapp.io/share/v5pZODPE#F71)) when I use the method inside $errors.

$errorName => method that returns a string with the key for the error bag

`$errors->has($errorName)` => throws exception
`$errors->has($errorName())` => No exception

There is an exception because `array_key_exists()` don't accept an InvokableComponentVariable. I could use parens but my components are inside a package. Other projects that doesn't use the latest update will not work if I change this in my package. `Call to undefined function errorName()` is thrown because $errorName would be evaluated first, executing that public method. The resulting callable would then be executed due to the parenthesis at the end.

**Comment by taylorotwell** [comment]
I recommend updating to use the `()`. We really don't want to revert this as it IMO was a bug that all parameter less methods were eagerly invoked even if you never accessed them as a variable at all.
