### ISSUE TITLE
Queue:failing dose not return an exception nor job name in laravel5.7

### ISSUE THREAD

**Issue by saeid78** [laravel/framework#32607]
Hi,
I have set up queue:failing in the boot method and was expecting to catch exception , but it only return connection Name!
I have this : 
Queue::failing(function (JobFailed $event) {
            Log::error('JobFailed. ' . json_encode([
            'connectionName' => $event->connectionName,
            'job' => $event->job,
            'exception' => $event->exception
            ]));
        });
And this is my Command:
command=php /var/www/html/artisan queue:work redis --sleep=3 --tries=3 --quiet
Thanks!

**Comment by taylorotwell** [comment]
Sounds like a feature request, not a bug.

**Comment by saeid78** [comment]
Thx @taylorotwell But  I have  followed https://laravel.com/docs/5.7/queues#failed-job-events 
Shouldn't I expect to get an Exception there?
Do I need to bring this out somewhere else ?
please advice.

**Comment by mfn** [comment]
The docs don't document everything, `::failed` is the generalization.

There's another (in the docs undocumented) event `::exception` which receives it:
```php
        Queue::exceptionOccurred(function (JobExceptionOccurred $event) {
…
```
`\Illuminate\Queue\Events\JobExceptionOccurred` contains the job and the exception

**Comment by saeid78** [comment]
Thx @mfn for the info!

**Comment by boogiefromzk** [comment]
@mfn Great feature, thank you!
