### ISSUE TITLE
ENV Variables

### ISSUE THREAD

**Issue by Smokietr** [laravel/framework#32604]
- Laravel Version: 7.0
- PHP Version:7.2.5

### Description:
The "env" property of the $subject variable does not work when sending an email.
The commands used : 
`env('APP_NAME')`
`Env::get('APP_NAME')`

The subject is empty in the incoming mail. I am having this problem in the mailable class.

**Comment by devcircus** [comment]
Use config in your mailable, not env.

**Comment by GrahamCampbell** [comment]
Yes, as per the docs, please only read the env variables loaded by Laravel within your config files. When you cache your config, Laravel doesn't read any of the original config files or the .env file anymore, to maximize performance.
