### ISSUE TITLE
Task Scheduling using weekdays doesn't work

### ISSUE THREAD

**Issue by mpalencia** [laravel/framework#32603]
- Laravel Version: 5.8.32
- PHP Version: 7.3.7
- Database Driver & Version:

### Description:
Chaining of weekdays method does not work. 
Docs on schedule:
https://laravel.com/docs/5.8/scheduling

### Steps To Reproduce:

**Example:**
$schedule->call(function () {
    // code here
})->tuesdays()
->wednesdays()
->thursdays()
->at('13:00');

This doesn't work. I need to run my code from Tuesday to Thursday, but chaining the methods does not work.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
