### ISSUE TITLE
Laravel HTTP Client ignores custom Content-Type URL-Encoded

### ISSUE THREAD

**Issue by StanBarrows** [laravel/framework#32618]
- Laravel Version: 7.9.2
- PHP Version: 7.4.4

### Description:
When sending a HTTP Requests with the custom Content-Type **form-urlencoded** - the body still gets sent as a JSON. The URL-Encoded type is used bymy OAUTH 2  workflow and I'm not able to trick the server with switching the content-type to **application/json**.

### Steps To Reproduce:

Send a HTTP-POST Request with a customer header Content-Type: application/x-www-form-urlencoded - Your application will still receive a JSON-Request.
```
Http::withHeaders([
    'Content-Type' => 'application/x-www-form-urlencoded',
])
    ->withBasicAuth('$client', '$client_secret')
    ->withoutVerifying()
    ->post('$endpoint', [
        'grant_type' => 'authorization_code',
        'code' => '$code',
        'redirect_uri' => '$redirect_ur',
    ]);
```

You still receive json:

`"{"grant_type":"authorization_code","code":"asdf","redirect_uri":"asdf"}"`

**Comment by taylorotwell** [comment]
See: https://laravel.com/docs/7.x/http-client#request-data

"Sending Form URL Encoded Requests"

**Comment by StanBarrows** [comment]
Unfortunately I still receive an error. The Guzzle example I attached below is working fine.

```
  $response = Http::withHeaders([
            'Content-Type' => 'application/x-www-form-urlencoded'
        ])->withOptions([
            'debug' => true,
        ])->withBasicAuth($client,$client_secret)
            ->asForm()->post($endpoint,
                [
                    'grant_type' => 'authorization_code',
                    'code' => $request->code,
                    'redirect_uri' => $redirect_url
                ]);
```

![image](https://user-images.githubusercontent.com/10268813/80764934-1256c400-8b42-11ea-9c7d-c91fe5316a92.png)


```
 $body = 'grant_type=authorization_code&code=' . $request->code . '&redirect_uri=' . urlencode($redirect_url);

            $client = new Client();

            $response = $client->post($endpoint, [
                'headers' => [
                    'Content-Type' => 'application/x-www-form-urlencoded'
                ],
                'auth' => [$client,$client_secret,
                ],
                'body' => $body,
            ]);
```

**Comment by StanBarrows** [comment]
Removing the custom header fixes the problem, thx for the hint!

```
$response = Http::withBasicAuth(
            config('services.bexio.client_id'),
            config('services.bexio.client_secret'))
            ->asForm()->post(config('services.bexio.token_endpoint'),
                [
                    'grant_type' => 'authorization_code',
                    'code' => $request->code,
                    'redirect_uri' => config('services.bexio.redirect_url')
                ]);
```

**Comment by FB-LilianaIturribarria** [comment]
@taylorotwell I still have the same issue, so basically i have something like this:

`
function request() {
$headers = [
            'Accept'        => 'application/json',
        ];
$request = Http::baseUrl($baseUrl)->withHeaders($headers);

if ($authEndpoint) {
            $request->withBasicAuth($this->clientId, $this->clientSecret);
        }
        
        return $request;
}

// using the request fn
        $queryParams = [];
        $payload = [
'grant_type' => 'refresh_token',
            'refresh_token' => 'XXXX',
            'redirect_uri' => $this->callbackUrl,
];
        $url = $endpoint . (count($queryParams) > 0 ? '?' : '') . http_build_query($queryParams);
        $request = $this->request(true);

        if ($contentType === 'form') {
            $request = $request->asForm();
        }

        $response = $request->post($url, $contentType === 'form' ? [
            'form_params' => $payload,
        ] : $payload);
        
        
`
but response returns that i'm not sending the correct payload

`
{
    "status": "error",
    "message": "Missing Parameter: 'grant_type' must be set"
}
`

I'm using laravel v9.38.0

**Comment by davileichs** [comment]
The issue is when you use ->withHeaders() it removes the grant_type from body of array
The solution is to use asForm() instead withHeaders()
