### ISSUE TITLE
Inconsistency with unique and exists validators on other connections

### ISSUE THREAD

**Issue by klaasgeldof** [laravel/framework#32615]
- Laravel Version: 7.7.1
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 5.7.28

When you need the `unique` and `exists` validators on other connections, there are several options, but they don't work always the same.

Assuming we have a model like this:

```php
class User extends Model
{
    protected $connection = 'other';
}
```

These rules work correctly:

```php
'unique:other.users'
'unique:'.User::class
Rule::unique('other.users')
```

But the following does not, as it ignores the connection:

```php
Rule::unique(User::class)
```

Same with the `exists` rule.

**Comment by taylorotwell** [comment]
Fixed on master branch. I'm not comfortable fixing on a patch release because some applications may be depending on this "bug" using the default connection if no other connection is specified. You can use one of the alternative approaches for now.

**Comment by klaasgeldof** [comment]
Okay, thanks!
