### ISSUE TITLE
withCount()'s output in having() Doesn't work with paginate()

### ISSUE THREAD

**Issue by Hayat-Umar** [laravel/framework#32620]
- Laravel Version: 6.3.0
- PHP Version: 7.3.12
- Database Driver & Version: MySql

### Description:
So, I have noticed that withCount()'s provided alias is not available in having() method when used with paginate(). But it works perfectly fine if we use it with get().

### Steps To Reproduce:
Create 2 models, Define relationship, Fetch the results and see the problem.

Thanks

**Comment by staudenmeir** [comment]
Laravel's pagination doesn't support `HAVING` clauses: #28476 [etc.](https://github.com/laravel/framework/issues?q=is%3Aissue+pagination+having)

You can try this package: https://github.com/justbetter/laravel-pagination-with-havings
