### ISSUE TITLE
middleware: next don't take le resquest in param

### ISSUE THREAD

**Issue by kadevland** [laravel/framework#32630]
- Laravel Version: 7.9.2
- PHP Version: 7.4.5
- Database Driver & Version: sqlite 

### Description:
In middlelware i change request and pass to next but in controlle take the original request.

### Steps To Reproduce:

 https://github.com/kadevland/laravel-7-middleware-issue

**Comment by GrahamCampbell** [comment]
Can you commit the base app, and then apply your changes in a separate commit, otherwise its hard to see the code you are demonstrating.

**Comment by kadevland** [comment]
ok i repushed the code with all step

**Comment by kadevland** [comment]
simple code :
1 middleware witch duplicate request and add custom header (hard value for this test)
1 controller return from request the custom header value ( in json )
1 test call route and check if respond has je good json response

**Comment by taylorotwell** [comment]
You would need to bind your new request into the container to get it to be shared across the application.
