### ISSUE TITLE
Console Options Parsing with Scheduler

### ISSUE THREAD

**Issue by sumityadav** [laravel/framework#32637]
- Laravel Version: 6.18.10
- PHP Version: 7.3.11
- Database Driver & Version: mysql 5.7.29

### Description:
Scheduling command with array options will not parse the options correctly.

### Steps To Reproduce:
I have a console command which accepts multiple email addresses as option `--email`.

**Command Signature**
```php
protected $signature = 'status-check {--email=* : List of email addresses.}';
```
When I want to call the Artisan command from my controller, I use following (works as expected)
```php
Artisan::call(StatusCheck::class, [
    '--email' => ['user1@example.com', 'user2@example.com']
]);
```

Now I want to schedule this command using the Scheduler.
```php
$schedule->command(StatusCheck::class, [
    '--email' => ['user1@example.com', 'user2@example.com']
])->daily();
```
This will result in following exception:
**Too many arguments, expected arguments "command".**

**Comment by taylorotwell** [comment]
You can just do $schedule->command('status-check --email=foo --email=bar');

**Comment by taylorotwell** [comment]
It's not possible to support the syntax you mentioned at this time without a breaking change to array based arguments (not options), so I suggest using the syntax I pasted above.

**Comment by taylorotwell** [comment]
Fixed in next patch release though.

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/commit/cfc3ac9c8b0a593d264ae722ab90601fa4882d0e

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/32641
