### ISSUE TITLE
Queueable cannot define properties contrary to what doc says

### ISSUE THREAD

**Issue by Korko** [laravel/framework#32649]
- Laravel Version: 7.*
- PHP Version: 7.2+
- Database Driver & Version: N/A

### Description:
Queue doc implies that a ShouldQueue Job may define the "$connection" property
(https://laravel.com/docs/7.x/queues#customizing-the-queue-and-connection)

Problem is: Most Jobs use Queueable trait which already define the $connection property. PHP does not allow to redefine a property already defined in a trait: https://3v4l.org/32k30

Therefor, we should add a method getConnection that can be redefined in the Queueable Job and update the doc accordingly.

**Comment by themsaid** [comment]
Not all jobs use `Queueable`, if you use Queueable you can just set the connection from the constructor. This is by design, not a bug.
