### ISSUE TITLE
assertJsonCount doesn't seem to work correctly with key '0'

### ISSUE THREAD

**Issue by YFjMhEix** [laravel/framework#32651]
- Laravel Version: v6.18.11 (but the issue exists on 7.x too)
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:

assertJsonCount of class Illuminate\Foundation\Testing\TestResponse seems not to work correctly when I use a JSON with a key '0'. See example below.

### Steps To Reproduce:

Consider e.g. a GET endpoint returning a JSON response:

```php
return response()->json(
    ['0' => ['key1' => 'value1'],
     '1' => ['key2' => 'value2'], 
     '2' => ['key3' => 'value3']]);
```

Test:

```php
$response->assertOk()
            ->assertJsonCount(1, '0')
            ->assertJsonCount(1, '1')
            ->assertJsonCount(1, '2');
```

##### Expected result:
Green test.

##### Actual result:
Red test, fails at first assertJsonCount, the other 2 are ok.
```
Failed to assert that the response count matched the expected 1
Failed asserting that actual size 3 matches expected size 1.
```

Problem is probably the 
```php
if ($key) {
```
at the beginning of assertJsonCount which sorts out the key with value '0', hence counting the 3 elements on the root level.

**Comment by themsaid** [comment]
fixed by https://github.com/laravel/framework/pull/32655
