### ISSUE TITLE
Issue with component tags: "Unable to locate a class or view for component"

### ISSUE THREAD

**Issue by neamtua** [laravel/framework#32657]
- Laravel Version: 7.9.2
- PHP Version: 7.4.3 (local), 7.3.17 (production)
- Database Driver & Version:

### Description:
I've ran into a weird issue today while using the new components from Laravel 7. I've created a WeeklyStats component (php artisan make:component WeeklyStats) and displayed it with
`<x-weeklystats/>`
in my local environment (Laravel Valet).
Everything works, loads, etc.

Problem appeared after deploying to my production server.
I kept getting the error "Unable to locate a class or view for component [weeklystats]. at [truncated]/vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:234)"

It only worked after i've used the same name as the view the component was loading
`<x-weekly-stats/>`

I've read the documentation and it states that "Blade component tags start with the string x- followed by the kebab case name of the component class". It's at least confusing because WeeklyStats kebab-cased is not weekly-stats.

Also, the other confusing part is why it worked locally in the first place. I did check after clearing all the cache and compiled views.

**Comment by ryangjchandler** [comment]
Hi @neamtua, when you run `Str::kebab()` on "WeeklyStats", it does in fact return "weekly-stats".

![Capture](https://user-images.githubusercontent.com/41837763/80916392-430c4880-8d50-11ea-8aec-86b1af9d7273.PNG)

**Comment by taylorotwell** [comment]
Why would it not be `weekly-stats`?

**Comment by neamtua** [comment]
Before you close it, why does it work on Valet with <x-weeklystats>?

**Comment by codemonkey76** [comment]
Could it be that your production server uses case sensitive file system while your local environment does not

**Comment by virgiltu** [comment]
I am having a similar issue. 

Index.blade.php 
  `<x-sliderHome default="sliderHome"></x-sliderHome>`

component was redecorated to   view/components/home 

sliderHome.blade.php

In component controller I call 

` return view('components.home.sliderHome', compact('slider'));`

 On local windows environment everything works. 
Linux Production server - InvalidArgumentException Unable to locate a class or view for component [sliderHome]. 

The only way to fix it is so move the file back in components but that is counter productive as I have very many components for many pages.

**Comment by dissolvdgrl** [comment]
> Could it be that your production server uses case sensitive file system while your local environment does not

Sorry for commenting on a closed issue, but I just ran into this and this was indeed the case with a project I am working on. The client uses shared hosting and changing the component file name to only lower case worked on the production server.
