### ISSUE TITLE
Appending an attribute to model is not working as expected in 7.9.2

### ISSUE THREAD

**Issue by samiam9297** [laravel/framework#32650]
Hi, for more info please see
https://stackoverflow.com/questions/61554718/appending-an-attribute-to-a-laravel-model?noredirect=1#comment108884510_61554718
https://laracasts.com/discuss/channels/code-review/appending-an-attribute-to-a-laravel-model?page=0#reply=603967

- Laravel Version: 7.9.2
- PHP Version: 7.4.0
- Database Driver & Version: 10.4.10-MariaDB

### Description:
https://laravel.com/docs/7.x/eloquent-serialization
According to the docs, appending a value to an attribute should be easy. I used artisan to create a model:
```
namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit_Live extends Model
{
    protected $table = 'live_data_units';

    public function getOtherUnitNameAttribute()
    {
        return $this->unitName;
    }

    protected $appends = ['other_unit_name'];

}
```

`dd()` output:
![image](https://user-images.githubusercontent.com/61100078/80870834-f143bf80-8c76-11ea-99fc-fe218dec50f8.png)

The issue is with `getOtherUnitNameAttribute()`. If I change to `protected $appends = ['other_unit_name' => 'this is a test'];`, I can see output:
![image](https://user-images.githubusercontent.com/61100078/80870897-497ac180-8c77-11ea-992b-7c3a84d31fd0.png)

### Steps To Reproduce:
1. Create a model in artisan.
2. Append an attribute.
3. Use `dd()` in the view to dump the array.

**Comment by devcircus** [comment]
What you're looking at is simply the value of the appends property of the model. That's what it is supposed to be. 

```dump($model->toArray());``` and you'll see the appended attribute along with the other attributes.
