### ISSUE TITLE
fresh and refresh method not loading relationship correctly

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#32664]
- Laravel Version: 7.9.2
- PHP Version: 7.4.3

### Description:
fresh and refresh on model not working correctly

### Steps To Reproduce:

Example: having 3 model A, B and C

A -> hasMany B, B -> hasMany C

```php
class A extends Model
{
    public function bs()
    {
        return $this->hasMany(B::class);
    }
}

class B extends Model
{
    public function cs()
    {
        return $this->hasMany(C::class);
    }
}
```
```php
// tinker
$a = A::with('bs.cs')->first();

$a = $a->fresh(); // lose all bs.cs relationship

$a = A::with('bs.cs')->first();

$a->refresh(); // still have bs, but lost cs
```

**Comment by mfn** [comment]
> fresh and refresh

For `fresh()`, this is expected: it deliberately does not reload relationships.

**Comment by driesvints** [comment]
Why are your relations named `bs`, `bc` when you're referencing them as `b.c`?

**Comment by kocoten1992** [comment]
> Why are your relations named `bs`, `bc` when you're referencing them as `b.c`?

edited

**Comment by driesvints** [comment]
I also don't think this is possible atm. The way I see it refresh only loads back direct relations and not cascading ones. I'm not really sure if this is a bug or intended.

**Comment by taylorotwell** [comment]
All of this sounds like fairly decent behavior. Definitely with fresh().  Even with refresh() I think current behavior is pretty fine. You can lazily access any additional deeper relationships that you want.
