### ISSUE TITLE
Cannot use Illuminate\View\View as View because the name is already in use

### ISSUE THREAD

**Issue by kylekatarnls** [laravel/framework#32665]
- Laravel Version: master#8f21a39
- PHP Version: 7.4.2

### Description:
When using `InteractsWithViews` I get:
```
Cannot use Illuminate\View\View as View because the name is already in use in vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithViews.php on line 8
```

And indeed this file contains 2 imports named `View`.

### Steps To Reproduce:
```php
<?php

use Illuminate\Foundation\Testing\Concerns\InteractsWithViews;

class Foo
{
    use InteractsWithViews;
}
```

I will try to see which is the right import or if it needs an alias to use both and propose a PR.

**Comment by staudenmeir** [comment]
Caused by https://github.com/laravel/framework/commit/8f21a39dde9fbf1ea50c88f3c8cd9f5f5c6fa29a.

**Comment by kylekatarnls** [comment]
Yes I saw that and so I'm preparing an aliasing of the \Illumanite\View\View use.

**Comment by GrahamCampbell** [comment]
> Yes I saw that and so I'm preparing an aliasing of the \Illumanite\View\View use.

You can't do this. You need to use it as something, if you have already bound the name.

**Comment by kylekatarnls** [comment]
aliasing = as something

That's what I mean: #32666

**Comment by GrahamCampbell** [comment]
Ah, you mean in our code, not yours. :)

**Comment by driesvints** [comment]
Merged

**Comment by kylekatarnls** [comment]
Perfect, works fine for me too using laravel/framework: dev-master.
