### ISSUE TITLE
PDO::ATTR_SERVER_VERSION unreliable when behind a managed proxy

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#32681]
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 8.0.15, hosted by Azure

### Description:
I'm using Azure MySQL databases for a long time now and wanted to make the move from MySQL 5.7 to 8.0. Laravel has already introduced compatibility regarding session modes (`NO_AUTO_CREATE_USER`) by checking the actual server version (MySQLConnector - strictMode method), so that's great.

However there's a peculiar catch when working with cloud providers such as Azure: their database servers are behind a proxy and these don't know in advance which version you're connecting to. 

As a consequence `$connection->getAttribute(PDO::ATTR_SERVER_VERSION)` will always yield `5.6.42.0` regardless of the actual MySQL version, and the version compare in the MySQLConnector fails to return the correct modes...

I'm not sure what to suggest or how to tackle this. `select version()` does return the correct version number though, but I guess that's not a viable solution since it requires an open connection. Perhaps some config option that overrides the version fetch when present?

---

Seems at Drupal someone reported the same issue: https://www.drupal.org/project/drupal/issues/3089902

And an official reply from Microsoft:
https://social.msdn.microsoft.com/Forums/en-US/795cb2be-dce7-4805-b324-a67e83697580/azure-database-for-mysql-reports-incorrect-version?forum=AzureDatabaseforMySQL

**Comment by driesvints** [comment]
Isn't this more a PDO problem then a Laravel problem? I guess any framework that uses PDO will suffer from this?

**Comment by Propaganistas** [comment]
It's indeed true that any framework will experience this, but I think this isn't even situated on the level of PDO. As it seems a server can arbitrarily modify its exposed server version. So I don't think version compatibility conditionals should ever rely on it in a non-configurable way? Because in case of managed DB instances there's no way to circumvent this I'm afraid.

**Comment by taylorotwell** [comment]
Yeah I have of no other solution to this than allowing the developer to literally provide a hard-coded version we should use instead. If you want to research that and make a PR to the framework feel free to take a look.
