### ISSUE TITLE
http post throw error on getting 403 status

### ISSUE THREAD

**Issue by harrisdt15f** [laravel/framework#32680]
- Laravel Version: 7.9.2
- PHP Version: 7.3.17
- Database Driver & Version: 

### Description:
![image](https://user-images.githubusercontent.com/27404296/81047122-5eac5600-8eec-11ea-999f-323c9eae6def.png)

### Steps To Reproduce:
call to this url and then got directly get error.
"http://fe.vrbetdemo.com/MerchantQuery/GameBet", ["1.0", "JHHY", "zOsKgfUvfDrM0JRDL4bAWY203+OTk9Ix66YZ877F0ro2Q5PPapN9koMfcZohyrQk0xYHOKdNx69cqaJynFqk3EH3iB1Ls9wNZHTh29j7uXsHy3x/3Db3kTW8DjQFBQ85"])

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
