### ISSUE TITLE
getCode() is not working in Exception Handler class.

### ISSUE THREAD

**Issue by shihabudheenf** [laravel/framework#32695]
- Laravel Version:^7.0
- PHP Version: 7.2.5
- Database Driver & Version: MySQL 8

### Description:
Not getting response status code in Exception handler class. 

### Steps To Reproduce:
- File: App\Exceptions\Handler.PHP
- Function :  public function render($request, Throwable $exception)

When trying to get response status code `$exception->getCode()` , it returns 0. 

So, we can not produce custom error JSON response.

**Comment by deleugpn** [comment]
`getCode()` returns the Exception code, not the Http Status Code. You might want to do something in the lines of

```
if ($exception instanceof \Symfony\Component\HttpKernel\Exception\HttpExceptionInterface) {
    $exception->getStatusCode();
}
```

**Comment by CarlosGCJesus** [comment]
> `getCode()` returns the Exception code, not the Http Status Code. You might want to do something in the lines of
> 
> ```
> if ($exception instanceof \Symfony\Component\HttpKernel\Exception\HttpExceptionInterface) {
>     $exception->getStatusCode();
> }
> ```

Sorry, I might be wrong and the noob here, but this silly....

I know I'm late to this threat, and testing Laravel9 with php8.2! Testing a personal site to learn...

So, I'm at app/Exceptions/Handler.php... and the ideia is to register any error that passes here into a table, so I'm trying to get info for table:
```
public function report(Throwable $exception)
    {
           \Log::info("report " . $exception->getMessage());
           \Log::info("code : " . $exception->getCode());
           \Log::info("exception : " . get_class($exception));
           \Log::info("user : " . Auth::user()->id);
```

Which I get:
[2023-01-12 09:34:00] local.INFO: report The route bo-ho could not be found.  
[2023-01-12 09:34:00] local.INFO: code : 0 
[2023-01-12 09:34:00] local.INFO: exception : Symfony\Component\HttpKernel\Exception\NotFoundHttpException  
[2023-01-12 09:34:00] local.INFO: user : 2

So to get the 404, I have to "pre-cast"... okey, BUT.... will I have to pre-cast all possible exceptions??? my default will be easy with abort(403), butwhat about other system errors? Will I get a file with dozens of special casts?
