### ISSUE TITLE
Validate request body within FormRequest

### ISSUE THREAD

**Issue by twickstrom** [laravel/framework#32690]
- Laravel Version: 7.8.1
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.28

### Description:
`required` validation rule behaving inconsistently

According to the [docs](https://laravel.com/docs/7.x/validation#rule-required):

**required**

The field under validation must be present in the input data and not empty. A field is considered "empty" if one of the following conditions are true:

- The value is null.
- The value is an empty string.
- The value is an empty array or empty Countable object.
- The value is an uploaded file with no path.

### Steps To Reproduce:

I have a simple FormRequest that validates an array in the body:

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SyncPosts extends FormRequest
{
  public function authorize()
  {
    return true;
  }

  public function rules()
  {
    return [
      '*' => 'required|array|min:1',
      '*.id' => 'required|numeric',
      '*.title' => 'required|string'
    ];
  }
}
```

Controller Method:
```
public function sync(SyncPosts $request)
{
  // Should only get here if validation passes.
  dd($request);
}
```
Per the docs I would expect the request body (*) to be required, an array, with at least one Object (post).

The following request works perfect and passes validation:

HTTP Request: `POST /posts`
Request body:
```
[{
  "id": 1,
  "title": "Example Post"
}]
```

The following request works perfect and fails validation:

HTTP Request: `POST /posts`
Request body:
```
[{
  "id": null,
  "title": "Example Post"
}]
```

However both of these example will pass validation (this is not expected):

HTTP Request: `POST /posts`
Request body:
```
[]
```
HTTP Request: `POST /posts`
Request body:
```
(empty)
```

**Comment by koenhoeijmakers** [comment]
Makes sense, if you send an empty request then the validation wont trigger on it as `'*'` matches "any key in the request" and having `[]` or `(empty)` doesn't have any keys it should validate.

**Comment by taylorotwell** [comment]
You need to assign a key to that request input so we have something to go on. I don't think `*` at the top level makes sense in a validation context.

**Comment by mwikala** [comment]
@twickstrom I found a really nice way of achieving this.

`FormRequest.php` has a method which gets the requests input data to give to the validator.
```php
/**
 * Get data to be validated from the request.
 *
 * @return array
 */
public function validationData()
{
    return $this->all();
}
```

In your Request class you can just override this method and add your key or do anything with the data before it goes to the validator
```php
class ApiInputRequest extends FormRequest
{
    /**
     * Convert request body before sending it to validator.
     * 
     * @return array
     */
    public function validationData()
    {
        return [ 'data' => $this->all() ];
    }
// rules(), messages() etc.
}
```
