### ISSUE TITLE
Calling the 'trashed()' method on a soft deleted model where the deleted_at column wasn't part of the select query returns false

### ISSUE THREAD

**Issue by BrunMartins** [laravel/framework#32705]
- Laravel Version: 7.4.0
- PHP Version: 7.4.3
- Database Driver & Version: Mysql Windows 8.0

### Description:
When querying a model with the SoftDeletes trait with select columns that don't include the 'deleted_at' column, the ```trashed()``` method returns false even if that model has been soft deleted.

If this is default behaviour, it should be explicitly explained in the SoftDelete section of the Laravel Eloquent ORM documentation.

### Steps To Reproduce:

1. Add a model with SoftDeletes trait;
2. Seed the database with one or two items;
3. Soft delete the items
4. Have a query builder line such as ```$model1 = Model::withTrashed()->select('id', 'col_1', 'col_2')->first();```;
5. Have a query builder line such as ```$model2 = Model::withTrashed()->first();```;
6. ```$model1->trashed()``` returns ```false``` and ```$model2->trashed()``` returns ```true```

**Comment by taylorotwell** [comment]
If you don't select the `deleted_at` column I have on idea how the framework would know if the item is currently trashed or not?
