### ISSUE TITLE
Please apply [Specify lower case `column_name` (fixes #20190) #21037] to Laravel version 5.4

### ISSUE THREAD

**Issue by evmorris94** [laravel/framework#32707]
- Laravel Version: 5.4.36
- PHP Version: 7.2.24
- Database Driver & Version:
MySQL 8.0

### Description:
We are having an interaction issue between Laravel version 5.4 and MySQL 8.0.
The problem and solution are described in https://github.com/laravel/framework/pull/21037.  The pull request there was applied to Laravel version 5.5.  Please apply the same fix to Laravel version 5.4.

**Comment by taylorotwell** [comment]
Laravel 5.4 is no longer maintained.

**Comment by rimace** [comment]
@evmorris94 An idea is to fork Laravel and apply the patches to 5.4 by yourself.
Wouldn't recommend it though, as you're just falling behind and makes it harder upgrading the framework sometime.
