### ISSUE TITLE
Intervention\Image\Exception\NotReadableException Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.

### ISSUE THREAD

**Issue by mansoormilad** [laravel/framework#32701]
I am using laravel and I got this error

Intervention\Image\Exception\NotReadableException
Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.
I also edit my php.ini but still I have the same error 
someone can fix this problem?

**Comment by shadoWalker89** [comment]
This is not related to laravel. The error is in the Intervention library.

From the error message you are trying to use Intervention with a unsupported image type.
The error message is very clear, this is not a bug but a bad usage of the library.
You have to force your user to upload one of the listed extensions in the error message or try another driver.
