### ISSUE TITLE
Integrity constraint violation on Implicit Route Binding and BelongsToMany

### ISSUE THREAD

**Issue by Tantrisse** [laravel/framework#32706]
- Laravel Version: 7.10.2
- PHP Version: 7.4
- Database Driver & Version: irrelevant

### Description:
It is not possible to resolve child route parameter using Implicit Route Binding Custom Key via `belongsToMany` relationship while we have a Default Key defined.

This issue is related (not a consequence but a missed case) to this other issue : #32546 

### Steps To Reproduce:
With the following structure : 

`Event` -> ManyToMany (with or without custom table) -> `User`

Route :
```php
Route::apiResource('events.users', EventUserController::class)->parameters([
    'users' => 'user:id',
]);
```

Model `Event` :
```php
class Event extends Model
{
    public function users()
    {
        return $this->belongsToMany(User::class, 'participations')
                          // ->using(Participation::class) // to use a custom intermediate table models 
        ;
    }
}
```

Model `User` :
```php
class Event extends Model
{
    public function events()
    {
        return $this->belongsToMany(Event::class, 'participations')
                          // ->using(Participation::class) // to use a custom intermediate table models 
        ;
    }
}
```

Model `Participation` (if Pivot class used)
```php
class Participation extends Pivot
{
    protected $table = 'participations';
}
```

If we hit `/events/1/users/1`, the following SQL error is thrown : 
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL:
    SELECT `users`.*,
           `participations`.`event_id` AS `pivot_event_id`,
           `participations`.`user_id` AS `pivot_user_id`
    FROM `users`
    INNER JOIN `participations` ON `users`.`id` = `participations`.`user_id`
    WHERE `participations`.`event_id` = 1
      AND `id` = 1
    LIMIT 1
)"
```
### Possible solution:
The same way the commit https://github.com/laravel/framework/commit/8d69454575267840643289b8de27d615cfe4bb62 fixed the case for `HasManyThrough`, a check should be added to concat the table name when the relation is a `BelongsToMany` as a join is performed too.

Something like:
```php
    public function resolveChildRouteBinding($childType, $value, $field)
    {
        $relationship = $this->{Str::plural(Str::camel($childType))}();

        if ($relationship instanceof HasManyThrough || $relationship instanceof BelongsToMany) {
            return $relationship->where($relationship->getRelated()->getTable().'.'.$field, $value)->first();
        } else {
            return $relationship->where($field, $value)->first();
        }
    }
```

I made the modification locally and did not ran into any error when using it. If I'm not missing important thing, this should be a flawless fix.

Regards.

**Comment by taylorotwell** [comment]
Fixed in next patch.
