### ISSUE TITLE
Validation with integer and min

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#32714]
- Laravel Version: 5.6.39
- PHP Version: 7.3.*

### Description:
Validation miss mach.

### Steps To Reproduce:
When try validate value `true` with that validation rules `'integer|min:0'` I get positive response. Only when I use `'numeric'` rule, validation fails, but `'min:0'` still doesn't work as expected.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LocalHeroPro** [comment]
It's nota a question.
