### ISSUE TITLE
Unit testing of events not working

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/framework#32715]
- Laravel Version: 6.18.13
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
Unit testing of events are not working. They do work on <= L6.18.10, after a composer update to 6.18.13 they don't work anymore.

```
$this->expectsEvents(OrderCreatedFlowEvent::class);
$event = new OrderCreatedFlowEvent();
Event::dispatch($event);
```

```
1) Tests\Unit\ApiEventTest::testTriggerOrderCreated
These expected events were not fired: [App\Events\FlowEvents\OrderCreatedFlowEvent]
Failed asserting that an array is empty.
```

**Comment by taylorotwell** [comment]
Will be fixed in next patch. Thanks.
