### ISSUE TITLE
Request key value changes after validation failure

### ISSUE THREAD

**Issue by rthakur** [laravel/framework#32718]
- Laravel Version:^7.0
- PHP Version: ^7.2.5
- Database Driver & Version: MySql & Ver 14.14 Distrib 5.7.29

### Description:
I am adding validation on a key as numeric instead of a string. But, the validator restructures the rule. 

### Steps To Reproduce:

```
$validate = \Validator::make($request->all(), [
            1 => 'required|number'
]);

if ($validate->fails()) {
       echo "<pre>"; print_r($validate->getMessageBag()->all()); die;
       die;
}
```

### Expected
```
 [1] => Array
                (
                    [0] => required
                    [1] => number
                )
```

### Returns
```
Array
(
    [0] => Array
        (
            [0] => required
            [1] => number
        )

)
```

```
Illuminate\Validation\ValidatorRules defined From Controller
stdClass Object
(
    [rules] => Array
        (
            [1] => Array
                (
                    [0] => required
                    [1] => number
                )

        )

    [implicitAttributes] => Array
        (
        )

)

Rules after array_merge_recursive
Array
(
    [0] => Array
        (
            [0] => required
            [1] => number
        )

)
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rthakur** [comment]
Hi there, I think

**Comment by rthakur** [comment]
Hi there,

I think it's a bug as the key-value changes from 1 to 0. Still, I will ask in the support channel.
