### ISSUE TITLE
Plural media

### ISSUE THREAD

**Issue by matro-skin** [laravel/framework#32723]
How about to add "media" to \Illuminate\Support\Pluralizer::$uncountable ?
That's it.

- Laravel Version: any
- PHP Version: any
- Database Driver & Version: any

**Comment by driesvints** [comment]
https://github.com/laravel/framework/pull/31928

**Comment by patrickbrouwers** [comment]
Breaking change was introduced by Doctrine/Inflector 1.4.0, I've PR'd a fix over there https://github.com/doctrine/inflector/pull/142
