### ISSUE TITLE
Request::ip() returns Docker IP

### ISSUE THREAD

**Issue by ErnestStaug** [laravel/framework#32720]
- Laravel Version: 6.6.2
- PHP Version: 7.4.0
- Database Driver & Version: Mysql 8 

### Description:
`Request::ip()` return default docker IP which is `172.69.190.66`

### Steps To Reproduce:

Dockerize your Laravel framework with Nginx ( or use Laradock) and return `Request::ip()` or `\Request::getClientIp()` in home controller.

I was able to get real IP with this [solution](https://stackoverflow.com/questions/33268683/how-to-get-client-ip-address-in-laravel-5/37937828#answer-41769505), but my concern is if this method is used somewhere else in framework it will cause other issues and limitations where is not supposed to.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
