### ISSUE TITLE
[7.x] shouldQueue() returning false in listeners that implement ShouldQueue doesn't work

### ISSUE THREAD

**Issue by stancl** [laravel/framework#32722]
- Laravel Version: 7.10.3
- PHP Version: 7.4
- Database Driver & Version: sqlite

### Description:

Returning `false` from `shouldQueue()` on event listeners doesn't cause the listener to be executed synchronously.

### Steps To Reproduce:

The following test passes, assuming `FooListener` **does not implement** `ShouldQueue`.

```php
/** @test */
public function listeners_can_be_synchronous()
{
    Queue::fake();
    Event::listen(MyModelCreated::class, FooListener::class);

    MyModel::create();

    Queue::assertNothingPushed();

    $this->assertSame('bar', app('foo'));
}
```

However, if I **do implement** `ShouldQueue` and return false from `shouldQueue()`, the test fails, saying that class `foo` could not be instantiated, which indicates that the listener's `handle()` method was not reached.

```php
class FooListener implements ShouldQueue
{
    public function handle()
    {
        app()->instance('foo', 'bar');
    }

    public function shouldQueue()
    {
        return false;
    }
}
```

The strange thing is that the `Queue::assertNothingPushed()` assertion passes. If I `return true` from `shouldQueue()`, it fails, as it should. But if I `return false`, the Queue assertion passes, while the `app()` assertion fails, since the listener's `handle()` is not executed. This can be proven also by `dd()`ing inside `handle()`.

**Comment by taylorotwell** [comment]
It would be a breaking change to start executing them synchronously when this returns `false`. Do we ever document anywhere that this is the behavior?

**Comment by stancl** [comment]
@taylorotwell Yes, this PR makes the behavior match with docs.

https://laravel.com/docs/7.x/events#queued-event-listeners

![Screenshot from 2020-05-08 22-07-41](https://user-images.githubusercontent.com/33033094/81444998-64b66700-9178-11ea-935f-f3ed81ac715d.png)

**Comment by devcircus** [comment]
Seems like something is a little off with the wording in the docs.

**Comment by stancl** [comment]
@devcircus Hmm, possible.

The `return $event->order->subtotal >= 5000` example makes more sense as "should this be executed at all, or not".

But it could also be that the operation is expensive when the subtotal is over 5000, for whatever reason.

My use case for this is that I ship vendor listeners and let people customize them like:

```php
SomeListener::$shouldQueue = false;
```

rather than forcing them to extend the class to make this simple change. (The static property is returned from `shouldQueue()`.)

Also the naming of the method makes perfect sense for this. Should this listener be queued (i.e. override the simple `instanceof ShouldQueue` check), or should it be executed synchronously.

If the logic was "should this run at all or not", then it should be called `shouldHandle()`, not `shouldQueue()`, and it should work on non-`ShouldQueue` listeners too.

**Comment by themsaid** [comment]
if `shouldQueue` is false, the listener is not going to be executed at all.

We added `shouldQueue` to allow developers to stop sending a listener to queue and reserve a spot on the queue while the listener should not run at all.

Current behaviour is expected and we're updating the docs.

**Comment by stancl** [comment]
@themsaid If I update my PR to use a different method for the behavior I need, will you accept it?

The name could be something like `shouldRunAsynchronously()` or something of your choice if that's too verbose.

I believe having logic inside a method to decide whether some job should go onto the queue or run synchronously is a genuine use case.

Thank you.

**Comment by themsaid** [comment]
If it shouldn't be queued then why implement the ShouldQueue interface on the listener?

**Comment by stancl** [comment]
Because it *can* be queued, optionally. The use case I explained above is to change a static property on a vendor listener, and another use case would be something like

```php
public function shouldRunAsynchronously()
{
    return $this->items->count() > 5000;
}
```

to queue a job only if it's too expensive to run in the browser.

**Comment by themsaid** [comment]
@stancl I see your point. But if we add this feature I think we should add it everywhere we check for the ShouldQueue interface for consistency. So to decide if the job/mail/notification/listener should be queued or run async we check the `shouldRunAsynchronously` method if it exists, if not we just do the current check for `ShouldQueue`.

**Comment by stancl** [comment]
@themsaid That's a good point.

I searched for `ShouldQueue` in the codebase and these are the only relevant places where the interface presence is checked:

<details>
<summary>Click to expand (8 code snippets)</summary>
- https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Notifications/NotificationSender.php#L75-L77
- https://github.com/laravel/framework/blob/de4a640894f4dd5686ad41447e535cb79a138ebf/src/Illuminate/Events/Dispatcher.php#L430-L432
- https://github.com/laravel/framework/blob/8c4064712b08e1a9f61bf89e765c1a3e1edab356/src/Illuminate/Bus/Dispatcher.php#L133-L136
- https://github.com/laravel/framework/blob/476ce4585321d6b02ab23e0bcf5c2353ae392bd6/src/Illuminate/Notifications/Channels/MailChannel.php#L117-L119
- https://github.com/laravel/framework/blob/3aad099de500807a28738b30a21aa6182fd913ff/src/Illuminate/Console/Scheduling/Schedule.php#L131-L133
- https://github.com/laravel/framework/blob/f69ad90b9d508b59a017d0e412d8228e71230a51/src/Illuminate/Support/Testing/Fakes/MailFake.php#L340-L342
- https://github.com/laravel/framework/blob/3aad099de500807a28738b30a21aa6182fd913ff/src/Illuminate/Console/Scheduling/Schedule.php#L131-L133
- https://github.com/laravel/framework/blob/7d30c1b564ddcd87a0fb6b59bc7b8d3cde7432e8/src/Illuminate/Mail/Mailer.php#L302-L303
</details>

However, note one thing. All of these places **only check for the presence of the interface**. The only place that actually calls the `shouldQueue()` *method* is the place where I was adding the bugfix, so `Events/Dispatcher`:

![Screenshot from 2020-05-08 23-01-33](https://user-images.githubusercontent.com/33033094/81449132-e067e200-917f-11ea-854e-71578d71d22e.png)

Therefore, all of these places that check for the **presence of the interface** only check whether they should pass the call to the queue, which then checks the `shouldQueue()` method.

This means that I can add the behavior for `shouldRunAsynchronously()` (or however you or @taylorotwell decide to name the method) right where I added the "bugfix" and it will work for all things that `shouldQueue()` works for.

I may be missing something here though. Maybe `shouldQueue()` is specific only to listeners & jobs? That wouldn't be an issue for the use cases I described above though. Listeners/jobs are the only things for which it makes sense to implement this in my opinion.

**Comment by themsaid** [comment]
A notification is always sent, a mailable is always sent, a listener doesn't always run the logic. That's why shouldQueue was only added to listeners, to provide a way to not waste sending a job to queue while it won't run any code anyway.

`shouldRunAsynchronously` however, can be used with jobs, notifications, mailables, and listeners.

**Comment by stancl** [comment]
That's true. I realistically don't see too many use cases for this behavior in those classes, but I guess for example the

```php
MyListener::$shouldQueue = true;
```

could be used with e.g. vendor notifications too.

Hmm, can't we do this on `Queue` level somehow? We could check if the `$job` has the `shouldRunAsynchronously()` method in `push()`. Though this would have to be added to every single queue driver:

https://github.com/laravel/framework/blob/de4a640894f4dd5686ad41447e535cb79a138ebf/src/Illuminate/Queue/RedisQueue.php#L89-L92

Which means that it couldn't be a first-class feature if we want to remain BC and let people have their own queue drivers.

Do you see any way that this could be realistically implemented? I would really use this for the conditionally queued listeners.

**Comment by stancl** [comment]
Now I'm thinking that maybe I could do

```php
class ExampleListener implements ShouldQueue
{
    public static $shouldQueue = true;

    public function handle($event)
    {
        // ...
    }

    public function shouldQueue($event)
    {
        if (static::$shouldQueue) {
            return true; // listener is queued
        } else {
            $this->handle($event);
            return false;
        }
    }
}
```
since I the event is passed to `shouldQueue` too.

So this probably solves the issue for me.

Thanks.
