### ISSUE TITLE
whereRaw

### ISSUE THREAD

**Issue by FSElias** [laravel/framework#32735]
- Laravel Version: 7.9.2
- PHP Version: 7.3.17
- Database Driver & Version: 10.1.44-MariaDB-cll-lve

### Description:
I have a table with a full-text index, for some reason, the binding on whereRaw resulting in an empty while the direct query is working fine,

### Steps To Reproduce:

```php
$q = 'Fady Elias';

//returns 0 record witch is wrong
$query = User::query()
             ->whereRaw("MATCH(`Tax_Payer_Name`) AGAINST ('?')", [$q])
             ->limit(10)
             ->get();

//returns 1 record which is correct
$query = User::query()
             ->whereRaw("MATCH(`Tax_Payer_Name`) AGAINST ('$q')")
             ->limit(10)
             ->get();
```

Please, am I missing something?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
