### ISSUE TITLE
.env file did not report any type of error after changing the string

### ISSUE THREAD

**Issue by dharmendrashah** [laravel/framework#32736]
- Laravel Version: 7.0
- PHP Version: 7.4.5
- Database Driver & Version: mysql v8

### Description:
when you change something in the `.env` file without quotation mark it stop the rendering the views and did not report any error on the server or anywhere. I was stuck on this issue for my whole day after quickly changing some code and `.env` file configuration i was thinking that i miss something while writing my code but at the end i realized something that .env file needs quotation mark 

i found the solution but some new Developer might not find this issue and move to another framework 

Make a 500 error or something that indicates that this is the issue

### Steps To Reproduce:
change .env file any configuration to `SOMETHING=SOME` to `SMETHING=SOME THING`

**Comment by buismaarten** [comment]
Laravel uses [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv), I think that's a better place to create this issue.

**Comment by GrahamCampbell** [comment]
Yep, this is intended. You have a syntax error in your file. The exception message will tell you this. If you want a space in the content, you need to enclose it in quotes.

**Comment by GrahamCampbell** [comment]
There's even a specific test for this case: https://github.com/vlucas/phpdotenv/blob/v4.1.5/tests/Dotenv/ParserTest.php#L183-L190, showing this is not a bug, but exactly the intended behaviour.
