### ISSUE TITLE
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

### ISSUE THREAD

**Issue by robinflyhigh** [laravel/framework#32733]
- Laravel Version: 6.x
- PHP Version: 7.4

### Steps To Reproduce:
composer update

**Comment by GrahamCampbell** [comment]
Thanks for the report, we are aware of this. Laravel 6 is LTS, and uses deprecated code. This fine.

**Comment by GrahamCampbell** [comment]
Laravel 7 no longer uses that package, if you want to upgrade.

**Comment by neclimdul** [comment]
@GrahamCampbell I don't believe that is true of Laravel 7 https://github.com/laravel/framework/blob/7.x/composer.json#L86

**Comment by driesvints** [comment]
@neclimdul you're pointing to require-dev which doesn't ships with Laravel 7

**Comment by neclimdul** [comment]
Yeah I guess its a different issue. I'll open that I guess.
