### ISSUE TITLE
Unexpected exit code of artisan commands

### ISSUE THREAD

**Issue by thlassche** [laravel/framework#32746]
- Laravel Version: 7.10.3
- PHP Version: 7.3.6

### Description:
https://github.com/laravel/framework/commit/f81b6ed01fb60580ade8c7fb4386aff4cb4d7719#diff-2aaa23817a4aeafde63888bd631364e7R202 introduced a change in the command exit code handling. 

If you had a command returning `bool(true)` in L6.x, it would result in an exit code of `0`. Using the same command in L7 results in an exit code of `1` (because of the cast to int)

Two things here:

- It is not documented in the upgrade guide and is breaking in e.g. CI pipelines
- One might argue that the original Symfony way of dealing with this is more clear: https://github.com/symfony/console/blob/master/Command/Command.php#L261 (just failing on it, especially since a failure exit code of `1` if you return true is a bit counterintuitive)

### Steps To Reproduce:
- Make a simple command, e.g.:
`app/Console/Commands/TestCommand.php`
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class TestCommand extends Command
{
    protected $signature = 'test';

    public function handle()
    {
        $this->info("Test exit code");
        return true;
    }
}

```
Run the command and check the exit code:
```
php artisan test
echo $?
```

Returns `0` in Laravel 6, `1` in Laravel 7

**Comment by driesvints** [comment]
Bit of an unfortunate side effect indeed but you should really always return integers from console commands. I'll add a note to the upgrade guide about this.
