### ISSUE TITLE
jsonSerializable get override by toArray in Pagination

### ISSUE THREAD

**Issue by eslym** [laravel/framework#32743]
- Laravel Version: v6.18.6
- PHP Version: PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
- Database Driver & Version: MySQL 5.7.24, mysqlnd 5.0.12-dev, 

### Description:
When the implementation of toArray and jsonSerializable are different in Model, the jsonSerializable will not work in Pagination class because it use toArray to replace all jsonSerializable, but this two function should not be the same.

See [Illuminate/Pagination/LengthAwarePaginator.php#L187](https://github.com/laravel/framework/blob/148e61f20324e8f345cd26613b005676acf76f8b/src/Illuminate/Pagination/LengthAwarePaginator.php#L187)

Edit: I found out even Model itself is doing like this

**Comment by taylorotwell** [comment]
Post the simplest possible way to recreate this.

**Comment by mo3000** [comment]
LengthAwarePaginator works fine. If you need a different json string, use your own paginator or just transform the sql result to the desired array before the pagination.
Paginators can't efficiently figure out every model instance in the sql result implements JsonSerializable or not (there may be no instance at all -- just a plain php array).

**Comment by eslym** [comment]
My case scenario is:

````
Product:
- id
- name
- description

Image:
- id
- product_id -> product (id)
- url
````
````php
class Product extends Model {
    public function images(){
        return $this->hasMany(Image::class, 'product_id');
    }
}

class Image extends Model {
    public function jsonSerialize(){
        return $this->url
    }
}

response()->json(Product::with(['images'])->get());
/*
Expected Result: {
    "id": 1,
    "name": "",
    "description": "",
    "images": ["http://...", "http://..."]
}
Actual Result: {
    "id": 1, 
    "name": "", 
    "description": "", 
    "images": [
        {"id": 1, "product_id": 1, "url": "http://..."}, 
        {"id": 2, "product_id": 1, "url": "http://..."}
    ]
}
*/
````
The result is not as expected, even though I can override the `toArray()` instead to achieve what I want, but obviously it doesn't seen right

**Comment by mo3000** [comment]
@eslym. According to the example above I think you should implement JsonSerializable in class Product, not Image. Because class Product is called directly. Check out this:

```php
class Product extends Model implements \JsonSerializable
{
    public function images()
    {
        return $this->hasMany(Image::class, 'product_id');
    }

    public function jsonSerialize()
    {
        $json = parent::jsonSerialize();
        if (isset($json['images'])) {
            $arr['images'] = array_column($json['images'], 'url');
        }
        return $json;
    }

}
```

**Comment by eslym** [comment]
@mo3000 the problem is not implement it in which model, the problem is there is `jsonSerializable()` call to `toArray()` everywhere, so doesn't matter override in which model, there will always has unexpected result in somewhere when serialize to json

**Comment by mo3000** [comment]
Don't be so hard on "toArray" 😊. Think about it. You want a json array, what choice do you have? Laravel Model and Paginator give the exact default behavior perfect for most scenario. The so called "unexpected" result can always be fixed by overriding jsonSerializable() somewhere in your code. @eslym

**Comment by eslym** [comment]
@mo3000 unfortunately it won't, because the call stack will be `Paginator::jsonSerializable()` -> `Paginator::toArray()` -> `Model::toArray()`, jsonSerializable will not get involved.
If I override the `Paginator::jsonSerializable()`, then the another scenario comes,
````
Order:
- id
- product_id
- amount

Product:
- id
- name
- description

Image:
- id
- product_id -> product (id)
- url
````
Lets assume the Order having the relation to Product and serialize it to json, so the case will be
`Paginator::jsonSerializable()`(assumed overrided) -> `Order::jsonSerialize()` -> `Order::toArray()` -> `Product::toArray()`, the `Product::jsonSerializable()` still ending up not being called, so the result still not as expected because `Model::jsonSerializable()` is actually called the `Model::toArray()`.

**Comment by driesvints** [comment]
Hmm, I can understand why you'd expect that but it's simple not the way it works atm. The paginator will always call `toArray` on the collection: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Pagination/LengthAwarePaginator.php#L166

We could add a flag on the `toArray` method to use `jsonSerialize` instead if it's true and call that in the `jsonSerialize` method of the paginator. Or we could duplicate the contents of `toArray` in the paginator class and call `jsonSerialize` instead (might be a bit more clear even though more verbose).

Also, there's the question wether you actually want this to happen or not. Some people might expect the current behavior instead. I'll leave it up to Taylor to decided upon this.

**Comment by eslym** [comment]
@driesvints I guess this have to let Laravel team to decide, but I will prefer if they have separate implementation, because they looks really like serving different purpose.

**Comment by taylorotwell** [comment]
I'm not sure there is really a "bug" here. It sounds more like an opinion on a change that should be made. Have you considered using Eloquent resources to have more fine-grained control over how your models are serialized?
