### ISSUE TITLE
Calling Command::resolveCommand with Command instance throws an error

### ISSUE THREAD

**Issue by VGirol** [laravel/framework#32751]
- Laravel Version: 7.9.2
- PHP Version: 7.3.17
- Database Driver & Version:

### Description:
Calling Illuminate\Console\Command::resolveCommand with a Command instance throws an error :
ErrorException: class_exists() expects parameter 1 to be string, object given

However the resolveCommand method accepts an instance of \Symfony\Component\Console\Command\Command class as first parameter.

### Steps To Reproduce:
Create a new Command :
php artisan make:command ErrorCommand

Fill the $name attribute :
    protected $name = 'make:error';

Fill the handle method with :
public function handle()
{
    $command = $this->resolveCommand('\Illuminate\Foundation\Console\ModelMakeCommand');
    $second = $this->resolveCommand($command);
}

Execute the command :
php artisan make:error

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
