### ISSUE TITLE
The `\Illuminate\Database\Eloquent\Concerns\HasAttributes::originalIsEquivalent` method doesn't compare attributes with the `object` cast correctly. 

### ISSUE THREAD

**Issue by MrMadClown** [laravel/framework#32785]
- Laravel Version: 6.18.6
- PHP Version: 7.2.26
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.28

### Description:
The `\Illuminate\Database\Eloquent\Concerns\HasAttributes::originalIsEquivalent`  method compares attributes with the `object` cast with a `==` comparator. 
Therefore changing an attribute from `{"key":""}` to `{"key":null}` is not possible.

### Steps To Reproduce:
[Example](https://gist.github.com/MrMadClown/9dfec90263482036f9922c56de35dd36)

**Comment by driesvints** [comment]
Strict comparison of object casts isn't possible: https://3v4l.org/O5OFO

**Comment by MrMadClown** [comment]
So using the `object` cast is a bad if the attribute contains keys which values could change between `0, false, null, or ""`? 
I know strict comparison doesn't work, but what about casting to arrays for comparison instead?
Or is there recommended way to force an attribute to be considered dirty?
I could override `\Illuminate\Database\Eloquent\Concerns\HasAttributes::getDirty` and simply always add the attribute, but that feels like a hack to me..
