### ISSUE TITLE
trans() helper function with custom array element validation messages

### ISSUE THREAD

**Issue by crayolaeater12** [laravel/framework#32798]
- Laravel Version: 7.10.3
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:
When accessing custom validation messages in the default `/resources/lang/en/validation.php`, the `trans()` helper function returns only the key when the custom validation message being retrieved is
for array elements, e.g. `entries.*.increase.required` format. I have ensured that the key is existing and is being accessed via `trans('validation.custom.entries.*.increase.required')` in my custom rule object.

### Steps To Reproduce:

Create a custom array element validation message:
`'person.*.email' => ['email' => 'Invalid email.']`

Retrieve the custom array element validation message via `trans()` helper function
`trans('validation.custom.person.*.email.email');`

In my case, the `trans()` helper only returns the key `'validation.custom.person.*.email.email'`.

**Comment by taylorotwell** [comment]
I don't think we ever documented that this was intended to be possible? Therefore, this sounds more like a feature request.
