### ISSUE TITLE
In policies, auto injected model instance foreignKey property type changes to string in http-tests get()->assertOk()

### ISSUE THREAD

**Issue by vanguardkras** [laravel/framework#32804]
- Laravel Version: 7.8.1
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 8.0.18

### Description:
StackOverflow thread:
[link](https://stackoverflow.com/questions/61768924/a-laravel-policy-works-differently-on-tests/61769068#61769068)

I figured it out when get an 403 status code after running an http-test. However, it worked correctly in a browser.

If you use a policy class that automatically injects an instance of a Model, and you create a test database record, after retrieving the model instance it changes its foreign key type to string. It leads to a strict comparison failure and 403 error consequently.
 
I believe it's not an expected behaviour.
 
### Steps To Reproduce:
- Create a migration and a model with a foreign key to the user table:

```php
$table->foreignId('user_id')->constrained();
```

- Create a resource controller for the model with show() method.

```php
     public function show(TestModel $testModel)
     {
        dd($testModel);
     }
```

- Create a policy with method view():
```php
    public function view(User $user, TestModel $testModel)
    {
        return $user->id == $testModel->user_id;
    }
```

- Bind the policy to the model in your AuthServiceProvider:
```php
TestModel::class => TestModelPolicy::class,
```

- Authorize the policy in your controller:
```php
    public function __construct()
    {
        $this->authorizeResource(TestModel::class, 'test_model');
    }
```
- Add a resource route:
```php
Route::resource('test_models', 'TestModelController');
```

- Create an http-test:
```php
    public function testModelTest()
    {
        $user = User::create(['email' => 'testEmail@testEmail.test']);
        $this->actingAs($user);
        $testModel = new TestModel();
        $testModel->user_id = $user_id;
        $testModel->save();
        $this->get('/test_models/' . $testModel->id)->assertOk();
    }
```
- Open the page in a browser creating a record in advance. Everything works fine.
- Run the test and receive a 403 error.
- Dump the model instance inside the policy method and check the results in a browser. The user_id parameter has the Integer type.
- Check the same in your test. The user_id is a string now.

**Comment by taylorotwell** [comment]
To me this sounds like a difference between your browser and your test database. Perhaps you are using SQLite in tests and MySQL in the browser?

**Comment by vanguardkras** [comment]
@taylorotwell It was correct. Thanks for your reply and I'm sorry for wasting your time. I appreciate what you do!
