### ISSUE TITLE
Using database cursor consumes a lot of memory

### ISSUE THREAD

**Issue by dinamic** [laravel/framework#32817]
- Laravel Version: 6.18.3
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.0.12

### Description:

Using `Model::query()->cursor()` to iterate over big tables consumes a lot of memory.

Here's are the memory spikes, should cursor be used.
- https://pastebin.com/LnwnD2ay

A workaround is to use `Model::query()->chunk(1, function() {})`. In our case, the memory consumption dropped to 28mb from about 400mb.

### Steps To Reproduce:
1. have a model with a table that has a lot of entries in it. the bigger the content, the easier to reproduce. in our case, we have a column that usually has about 2mb text. Trying to iterate through all 3000 items is an issue for us with memory consumption spiking to 400mb.
2. watch the memory consumption as you iterate items using `Model::query()->cursor()`

**Comment by dinamic** [comment]
Profiling with Blackfire gives PDO as the main offender, but I am not sure how's that possible if we using a cursor. I only have free account, so this could be accumulated memory consumption.

![image](https://user-images.githubusercontent.com/11616/81963895-7f785800-961e-11ea-8e2e-34962210cd82.png)

**Comment by dinamic** [comment]
I can't find an explicit setting of `PDO::ATTR_CURSOR` to be set to `PDO::CURSOR_SCROLL`. 

Could it be that Laravel is not configuring PDO properly?

**Comment by rodrigopedra** [comment]
Hi @dinamic , just in case you want to test it, you can add PDO options per database connection in your project's  `./config/database.php` file.

For example, I will assume you want to add that option to the default MySQL connection config:

~~~php
// ./config/database.php

'mysql' => [
    'driver' => 'mysql',
    'url' => env('DATABASE_URL'),
    'host' => env('DB_HOST', '127.0.0.1'),
    'port' => env('DB_PORT', '3306'),
    'database' => env('DB_DATABASE', 'forge'),
    'username' => env('DB_USERNAME', 'forge'),
    'password' => env('DB_PASSWORD', ''),
    'unix_socket' => env('DB_SOCKET', ''),
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => '',
    'prefix_indexes' => true,
    'strict' => true,
    'engine' => null,
    'options' => extension_loaded('pdo_mysql') ? array_filter([
        PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
        PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL, // <<<<< ADDED
    ]) : [],
],

~~~

**Comment by dinamic** [comment]
@rodrigopedra that parameter should be set when creating [the prepared statement](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Connection.php#L361). The options available in the config file are not the place for this kind of setting.

I've done some testing and I don't seem to be able to make cursor work with MySQL at all.

**Comment by dinamic** [comment]
I would rather extend and replace the cursor method implementation with one that uses the approach that `chunk()` method does.

I have a workaround in place by extending `Illuminate\Database\Eloquent\Builder` and overriding the `cursor()` method. https://pastebin.com/EahJk2rj

I wonder, how do we fix it permanently for other users?

**Comment by taylorotwell** [comment]
Add this to your options in your `config/database.php`:

```php
            'options' => [
                PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false,
            ],
```
