### ISSUE TITLE
Call to undefined function Illuminate\Testing\Constraints\array_key_first()

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#32826]
- Laravel Version: 7.11.0
- PHP Version: 7.2.24
- Database Driver & Version: mysql 5.7.19

### Description:
I am writing a unit test and checking in pivot table if has some keys and throws error for undefined function. That function is for php 7.3 but laravel 7 requirement is 7.2.5+ right?
Why trait is using functions that are for 7.3 php version? 
I am doing anything wrong?

### Steps To Reproduce:
Create a table and add some records.
Create a test add assertion like this.
```
$this->assertDatabaseHas('user_role', [
            'user_id'     => $user->id,
            'role_id' => $role->id,
        ]);
```

**Comment by lupinitylabs** [comment]
It would be helpful if you shared the exact error message you get, preferably the whole stack trace.

**Comment by mariosvasiliou** [comment]
Hello @lupinitylabs ,
This is the strack trace 
```
Error : Call to undefined function Illuminate\Testing\Constraints\array_key_first()
 C:\laragon\www\zygos-gov\vendor\laravel\framework\src\Illuminate\Testing\Constraints\HasInDatabase.php:81
 C:\laragon\www\zygos-gov\vendor\laravel\framework\src\Illuminate\Testing\Constraints\HasInDatabase.php:66
 C:\laragon\www\zygos-gov\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase.php:46
```
under further investigation it looks that the current error occures when the values you are looking are not in the table and the data are empty or missing the looking ids

**Comment by chrysanthos** [comment]
The [array_key_first](https://www.php.net/manual/en/function.array-key-first.php) method was introduced in php 7.3, so that probably shouldn't be there in the first place.

**Comment by lupinitylabs** [comment]
Good find!

**Comment by mariosvasiliou** [comment]
@lupinitylabs  Thanks,testing is crucial indeed

**Comment by GrahamCampbell** [comment]
Actually this is tested, but the tests load the PHP 7.3 polyfill...

**Comment by GrahamCampbell** [comment]
This is now fixed on 6.x and 7.x.
