### ISSUE TITLE
BelongsToMany wrong find query when using a model as id

### ISSUE THREAD

**Issue by matteoformenti** [laravel/framework#32828]
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8.0.20

### Description:
Calling find() on a belongsToMany relationship returns wrong result when a model is used as parameter.
`if (is_array($id) || $id instanceof Arrayable) `
should become
`if ((is_array($id) || $id instanceof Arrayable) && ! $id instanceof Model)`
Since any model implements Arrayable, the check inside find() treats the given model as an array, thus calling findMany. 
This behaviour is incorrect, but there's a bigger bug, if the model you're searching has a field with a value that is present in the column `$this->getRelated()->getQualifiedKeyName()`, this record will be retrieved too.

### Steps To Reproduce:
1) Create a Description model, with `id, otherField.`
2) Create a Product Model, with `id`
4) Product belongs to many Description
5) Create a product and two descriptions, one with `id = 1, otherField = 'hello world'` and the other with `id = 2, otherField = 1`
6) Associate the description with id = 1 to the existing product
7) Get all product descriptions via `$product->descriptions())`, you should only get the description with id = 1
8) Find description with id = 2 in product `$product->descriptions()->find(Description::find(2))`, you should receive an empty collection, but since the second description has a field with value 1 and whereIn is called instead of where, you get a result.
For clarity I'm  attaching a tinker session too
[tinker_output.txt](https://github.com/laravel/framework/files/4634626/tinker_output.txt)

**Comment by taylorotwell** [comment]
Do we document passing a model to this method?

**Comment by taylorotwell** [comment]
I don't think we ever document using this method in this way but I will ship a fix in next patch.

**Comment by matteoformenti** [comment]
https://laravel.com/docs/7.x/eloquent-collections#method-find here it says that find accepts a model as parameter, the behaviour is instead working correctly when using find on a collection, where the first check is whether or not the parameter is a model
