### ISSUE TITLE
Get NoConfigurationException on production env

### ISSUE THREAD

**Issue by rniederer** [laravel/framework#32823]
- Laravel Version: 7.0.1
- PHP Version: 7.4.5
- Database Driver & Version: unknown

### Description:
Hello

I put my first laravel project on production environment and get this error when I call a api route:

`Symfony\Component\Routing\Exception\NoConfigurationException:  in file /home/public_html/mydomain.com/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php on line 182`

I have only api.php routes. I have no route or view in web.php. I generated the key on production environment and installed the packages with composer install.

**Comment by xuanquynh** [comment]
Could you show your `routes/api.php` file content? And which api did you call?

**Comment by rniederer** [comment]
`<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

Route::post('register', 'AuthController@register');
Route::post('login', 'AuthController@login');
Route::post('user/validate', 'UserController@validateUser');
Route::post('password/request', 'PasswordController@request');
Route::post('password/reset', 'PasswordController@reset');
Route::post('contact', 'ContactController@send');

// TODO remove this
Route::post('login/password', 'LoginController@password');

// User
Route::get('user', 'UserController@getUser')->middleware(['auth:api']);
Route::post('user', 'UserController@save')->middleware(['auth:api']);
Route::get('user/remove/request', 'UserController@removeRequest')->middleware(['auth:api']);
Route::post('user/remove', 'UserController@remove')->middleware(['auth:api']);

// Wishlist
Route::get('wishlist', 'WishlistController@all')->middleware(['auth:api']);
Route::get('wishlist/{hash}', 'WishlistController@getByHash');
Route::post('wishlist/{hash}/login', 'WishlistController@login');
Route::get('wishlist/user/{hash}', 'WishlistController@getOwnByHash')->middleware(['auth:api']);
Route::put('wishlist/{id}', 'WishlistController@update')->middleware(['auth:api']);
Route::post('wishlist', 'WishlistController@insert')->middleware(['auth:api']);
Route::delete('wishlist/{id}', 'WishlistController@delete')->middleware(['auth:api']);

// Wish
// Route::get('wish', 'WishlistController@all')->middleware(['auth:api']);
// Route::put('wishlist/{id}', 'WishlistController@update')->middleware(['auth:api']);
Route::post('wish', 'WishController@insert')->middleware(['auth:api']);
Route::put('wish/{id}', 'WishController@update')->middleware(['auth:api']);
Route::delete('wish/{id}', 'WishController@delete')->middleware(['auth:api']);

// Donate
Route::post('donate', 'DonateController@insert');
Route::get('donate/export/{hash}', 'DonateController@export')->middleware(['auth:api']);
`
I try to call user/validate with "email"-parameter. I tried with http and https (I have a lets encrypt ssl certificate).

**Comment by xuanquynh** [comment]
This exception comes from [Symfony](https://github.com/symfony/symfony/blob/e60a876201b5b306d0c81a24d9a3db997192079c/src/Symfony/Component/Routing/Exception/NoConfigurationException.php). No routes are configured which means this file may not be loaded, I guess. I have no idea. You have to debug your production environment by yourself.

**Comment by rniederer** [comment]
Where can I ask for this error?

**Comment by sergeByishimo** [comment]
did you by any chance touch the `App\Providers\RouteServiceProvider` file?

could you show?

**Comment by rniederer** [comment]
Not that I know.

My RouteServiceProvider:
```
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to your controller routes.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * The path to the "home" route for your application.
     *
     * @var string
     */
    public const HOME = '/home';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @return void
     */
    public function boot()
    {
        //

        parent::boot();
    }

    /**
     * Define the routes for the application.
     *
     * @return void
     */
    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();

        //
    }

    /**
     * Define the "web" routes for the application.
     *
     * These routes all receive session state, CSRF protection, etc.
     *
     * @return void
     */
    protected function mapWebRoutes()
    {
        Route::middleware('web')
             ->namespace($this->namespace)
             ->group(base_path('routes/web.php'));
    }

    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix('api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
}

```

<img width="298" alt="Bildschirmfoto 2020-05-15 um 12 28 14" src="https://user-images.githubusercontent.com/13643858/82041002-c3636f80-96a7-11ea-9276-1e00e6180ce1.png">

**Comment by sergeByishimo** [comment]
does `php artisan route:list` show any of the routes?

**Comment by vpankeev** [comment]
Hi
Try to run these commands at first:
```
php artisan route:clear
php artisan config:clear
``` 
Then try to run `php artisan route:list` and show output to us.

And can you show full api url that you called?

**Comment by rniederer** [comment]
I did `php artisan route:list`. Then I realized, that I have to create my passport keys.

Now it works partly...

I have another problem with my routes:
`message: "Too few arguments to function App\Http\Controllers\WishlistController::update(), 0 passed and exactly 1 expected"`

I get this message from routes like this:
`Route::put('wishlist/{id}', 'WishlistController@update')->middleware(['auth:api']);`

My controller-function:
```
    public function update(int $id, Request $request)
    {
        $wishlist = App\Wishlist::find($id);

        if (!$this->_validateUser($wishlist)) {
            throw new HttpResponseException(response()->json(['error' => 'Unauthenticated'], 401));
        }

        $attributes = $request->all();
        return $this->save($wishlist, $attributes);
    }
```
Locally it works fine...

**Comment by taylorotwell** [comment]
Sounds like this is not a framework issue.
