### ISSUE TITLE
[7.x] Can't access a relation in $with if also using Model::get() 

### ISSUE THREAD

**Issue by zack6849** [laravel/framework#32833]
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL

### Description:
I'd like to be able to use relations in an appends, while also being able to use get

My goal here is, to for example, send some JSON to the front end, with users keyed by ID, but only with a few fields I want, for example, the id, their name, and their label.

### Steps To Reproduce:

 This is what i'm doing, briefly.

```

 //load the label
    protected $appends = [
      'label'  
    ];
    
    //we should always have a department loaded
    protected $with = [
        'department'
    ];

    public function department(){
        return $this->belongsTo(Department::class);
    }

    public function getLabelAttribute(){
        return "({$this->department->name}) {$this->name}";
    }

```

```
Route::get('/test', function (){
    return User::get(['id', 'name'])->keyBy('id');
});
```
This fails, because it doesn't have the department relation anymore, and i can't see any users. 

https://flareapp.io/share/17xKaLPb

I have a full repo with the code here: https://github.com/zack6849/appends-bug

You might think, duh, just add label to the get, well, that doesn't work, because get works on db columns (as you probably know)

I'm not sure if this is a legitimate bug, or if there's a better way to do this?

In the meantime, i'm doing this, which feels dirty:

```
    return User::all()->keyBy('id')->map(function ($user){
        return [
            'id' => $user->id,
            'name' => $user->name,
            'label' => $user->label
        ];
    });
```

Thoughts?

**Comment by vpankeev** [comment]
Try to use 
```
Route::get('/test', function (){
    return User::with(['department'])->get(['id', 'name'])->keyBy('id');
});
```

or modify accessor
```
public function getLabelAttribute(){
   if (!$this->relationLoaded('department')) {
            $this->load('department');
        }
        return "({$this->department->name}) {$this->name}";
    }
```

P.S.: First modify will be better for performance

**Comment by zack6849** [comment]
Neither of those work.

**Comment by staudenmeir** [comment]
You need to select the foreign key column `department_id`:

```php
return User::get(['id', 'name', 'department_id'])->keyBy('id');
```

You can still hide it:

```php
return User::get(['id', 'name', 'department_id'])->makeHidden('department_id')->keyBy('id');
```

**Comment by zack6849** [comment]
Hiding it didn't seem to work, but your suggestion of selecting the foreign key did, that's a hell of a gotcha, you'd think with it being in the with it would explicitly select it anyways.

**Comment by taylorotwell** [comment]
You aren't selecting the department_id as @staudenmeir noted.

**Comment by zack6849** [comment]
Hi @taylorotwell ! 

Is it possible for this to be documented somewhere / somehow?

I'm not sure where it'd go, but it's a hell of a gotcha that should be noted somewhere.

**Comment by sergeByishimo** [comment]
Hello @zack6849 

it’s so obvious that when you’re calling a relationship, a foreign key must be included in selected fields! that’s database and not framework related!

or do you want the framework to automatically add the foreign key in the query’s select? but that would be so invasive i think.

just keep it in mind.

**Comment by zack6849** [comment]
@sergeByishimo when i explicitly say to laravel that i always want a relation to be loaded by adding it to my $with of my model, i do expect the framework to join that model, yes.

**Comment by sergeByishimo** [comment]
@zack6849 you raise a good point but it might not be a shared opinion. 

let’s see what @taylorotwell has to say about it! or a PR might be needed in this case.

**Comment by zack6849** [comment]
That's a great idea, @sergeByishimo , someone should make an issue on github and ping taylor about it so that he can weigh in on it. :roll_eyes:
