### ISSUE TITLE
Undefined variable using @php directive

### ISSUE THREAD

**Issue by SneakyGerald** [laravel/framework#32836]
- Laravel Version: 7.10.3
- PHP Version: 7.2.29
- Database Driver & Version:

### Description:

I assign some value to my variable using `@php` directive but the view throws an error saying that variable doesn't exist.

```
    @php
        $path = 'my_path';
    @endphp

    @include('my-view', ['model' => $my_model, 'path' => $path])
```

![image](https://user-images.githubusercontent.com/26321350/82091892-807db800-96f8-11ea-956f-aceabce9b964.png)

If I replace `@php` by `<?php` and `@endphp` by `?>` all works fine. Also on the top of view, I use a similar approach and all works fine:

```
@php
    $url= 'value';
@endphp
<a href="{{ route($url, ['item' => $item->value]) }}" class="button button--white">
    <i class="fas fa-exclamation-triangle"></i> Error
</a>
```

### Steps To Reproduce:
1. Add `@php` directive to your view with some variable assignation
2. Pass the variable using `@include` directive  to the different view

**Comment by GrahamCampbell** [comment]
Can you paste the compiled blade file?

**Comment by SneakyGerald** [comment]
Not sure if I took it from the right place:
```
                    <section class="inter-section">
                        @php
                            $path = explode('.', \Route::currentRouteName(), 2)[0];
                        ?>

                        <?php echo $__env->make('my-view', ['model' => $my_model, 'path' => $path], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
```

**Comment by SneakyGerald** [comment]
I think the problem is caused by:
`@php($variable = $value)`

Compiled blade turns it into:
`<?php($variable = $value)`

And doesn't close PHP tag as the result blade is getting lost and stop transform some code parts. Seems strange that when I use `<?PHP` in that case (I mean `$url` variable) it doesn't throw the error even if the PHP tag of one line directive (`$variable`) is not closed.

**Comment by taylorotwell** [comment]
I can't recreate this.

**Comment by LegitDongo** [comment]
Sorry to resurrect, but can confirm this is still happening

It appears to only happen when a blade template contains both `@php()` and `@php ... @endphp` - they work fine when there's only one or the other

I'm on laravel/framework v9.46.0 and PHP 8.0.19

To replicate:
1. Create test template
2. Add this
```html
<html>
<body>
test
@php($a = 'abc')
test2
@php
$b = 'def';
@endphp
</body>
</html>
```
3. Load the page, see that `test2` isn't on the page
4. Find the following compiled file in `storage/framework/views`
```html
<html>
<body>
test
<?php($a = 'abc')
test2
@php
$b = 'def';
?>
</body>
</html><?php /**PATH /xxx/resources/views/test.blade.php ENDPATH**/ ?>
```

This clearly isn't correct, and nobody would expect this kind of behavior.
