### ISSUE TITLE
SessionGuard does not Encrypt Remember_web cookie

### ISSUE THREAD

**Issue by Ragash** [laravel/framework#32849]
- Laravel Version: 7.11.0
- PHP Version: 7.4.4
- Database Driver & Version: Mysql 8

### Description:
when the `AuthenticateSession `middleware runs his check on `($this->auth->viaRemember()) ` will get `remember_web` cookie as `null`  via  `$request->cookies->get($this->auth->getRecallerName())` resulting in an `Undefined offset: 2 ErrorException` as soon the middleware tries to explode the null value.

I've already checked into SessionGuard.php to make sure the cookie is properly formed and queued, and it's work properly.

i'm not sure if the cookie get a new encryption, or if it dont get decrypted at all.
but i tryed to move  `\Illuminate\Session\Middleware\AuthenticateSession::class` on top of `\App\Http\Middleware\EncryptCookies::class` and this let the request get the cookie properly

### Steps To Reproduce:
install the default scafolding login. enable the AuthenticateSession middleware and login with remember checked

**Comment by Ragash** [comment]
Update: i've noticied that `EncryptCookie `middleware produce an error when trying to decrypt the remember_web cookie, so i've dumped it to debug and noticied that the information inside the cookie are not encrypted at all!

so it only normal it will fail and set it to null.
im still struggling to understand why SessionGuard wont encrypt it properly when using CookieJar

**Comment by taylorotwell** [comment]
Unable to recreate. Works fine.
