### ISSUE TITLE
How to add table comments at migrations ?

### ISSUE THREAD

**Issue by hihuangwei** [laravel/framework#32840]
- Laravel Version: 7.11.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 8.0.20

### Description:
 How to add table comments at migrations ?

**Comment by thisismhp** [comment]
```
Schema::create("foo", function (Blueprint $table) 
    {
     .
     .
     .
    });
```

`    DB::statement("ALTER TABLE `foo` comment 'comment'");`

**Comment by sergeByishimo** [comment]
Hi @thisismhp 

https://laravel.com/docs/7.x/migrations#column-modifiers

look for comment in the Column Modifiers table.

**Comment by thisismhp** [comment]
Hi @sergeByishimo  
@hihuangwei wants add comment for `tables` not columns

**Comment by sergeByishimo** [comment]
yeah sorry! @thisismhp that answer you provided is right!

i wonder if a much nicer way is PR worthy!!

**Comment by thisismhp** [comment]
@sergeByishimo :) tnx

**Comment by thisismhp** [comment]
> 
> 
> yeah sorry! @thisismhp that answer you provided is right!
> 
> i wonder if a much nicer way is PR worthy!!
> `$table->comment('example comment')`

this is a feature request.
laravel team must answer it!
