### ISSUE TITLE
Laravel mailable subject not working if I queue the mailable

### ISSUE THREAD

**Issue by rahamatj** [laravel/framework#32843]
- Laravel Version: 7.0
- PHP Version: 7.3.11
- Database Driver & Version: mysql 10.4.8-MariaDB

### Description:

# Laravel mailable subject not working if I queue the mailable

I'm working with laravel 7.0 and for some reason when I write subject in my build method of a mailable and queue it by calling the queue method of the Mail facade the subject isn't changing, it is taking the mailable classname and setting it as the subject. If I hard code the `$subject` variable in the mailable class it works and if I don't queue it then the subject gets set. Anybody knows how to solve this? I'm using database driver to handle the queue.

### Steps To Reproduce:

- Create a mailable
- In the build method set the subject
- Set up queue with the database driver
- Queue the mailable and run the queue using `php artisan queue:work`
- If I use `php artisan queue:listen` it works fine

## Mailable build method
```
public function build()
{
    return $this->subject(config('app.name') . ' OTP')
         ->markdown('emails.otp');
}
```

## Queuing up the mail to send
```
\Illuminate\Support\Facades\Mail::to($this->user->email)
            ->queue(new \App\Mail\Otp($generatedOtp));
```

**Comment by taylorotwell** [comment]
Unable to recreate this using latest Laravel 7 and `queue:work`.
