### ISSUE TITLE
Foreach in email table component breaks table

### ISSUE THREAD

**Issue by SamuelNitsche** [laravel/framework#32854]
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version: not applicable

### Description:
Using a foreach loop inside a markdown table component breaks the rendered table

This works fine (Github rendering is bit off here):
```
@component('mail::table')
| Foo           | Bar                  |
| :--------- | :---------- |
| foo.           | bar                   |
@endcomponent
```

![Bildschirmfoto 2020-05-17 um 14 48 57](https://user-images.githubusercontent.com/24483576/82147081-9224a400-984d-11ea-921b-279c0bf80552.png)

But this breaks it:
```
@component('mail::table')
| Foo       | Bar         |
| :--------- | :------------- |
@foreach ([1, 2, 3] as $foo)
| foo | bar |
@endforeach
@endcomponent
```

![Bildschirmfoto 2020-05-17 um 14 51 08](https://user-images.githubusercontent.com/24483576/82147115-dca62080-984d-11ea-817c-b66dd28a8ab6.png)

**Comment by hyperalghorithm** [comment]
You shouldn't indent items, instead of
```
@component('mail::table')
| Foo       | Bar         |
| :--------- | :------------- |
  @foreach ([1, 2, 3] as $foo)
    | foo | bar |
  @endforeach
@endcomponent
```

write
```
@component('mail::table')
| Foo       | Bar         |
| :--------- | :------------- |
@foreach ([1, 2, 3] as $foo)
| foo | bar |
@endforeach
@endcomponent
```

**Comment by SamuelNitsche** [comment]
I also tried this before opening the issue. Should have mentioned this.
I updated the original post accordingly.

**Comment by hyperalghorithm** [comment]
Your issue could be somewhere else, I've tried
```
@component('mail::table')
| Foo       | Bar         |
| :--------- | :------------- |
@foreach ([1, 2, 3] as $foo)
| foo | bar |
@endforeach
@endcomponent
```
And it does give the proper output. 

![Screenshot_20200517_175547](https://user-images.githubusercontent.com/49185208/82153439-b42b2000-9867-11ea-91d8-a3883a73c264.png)

**Comment by SamuelNitsche** [comment]
Fixed it. The issue was the indentation of the `@component` itself. Now I feel a but dumb 😅

Thank you!

**Comment by debasis-bizzmanweb** [comment]
1
