### ISSUE TITLE
Mutator Accessor field disappeared after paginate

### ISSUE THREAD

**Issue by harrisdt15f** [laravel/framework#32858]
- Laravel Version: 7.11.0
- PHP Version: 7.3.18
- Database Driver & Version: mysql 8.0.19
### Description:
I tried with makeVissible('picture') , append('picture')
however, result in paginate disappeared the mutator field.
light me if there has trick to retrive it.

### Steps To Reproduce:
In Model I have
```
 /**
     * Get Pic
     *
     * @return string
     */
    public function getPictureAttribute(): string
    {
        $this->attributes['picture'] = $this->picPath->path;
        unset($this->picPath);
        return $this->attributes['picture'];
    }

    /**
     * Banner PicPath.
     * @return HasOne
     */
    public function picPath(): HasOne
    {
        return $this->hasOne(StaticResource::class, 'id', 'pic_id');
    }
```
In Controller 
```
$data                      = $this->model
            ->append('picture')
            ->with(
                [
                 'author:id,name',
                 'lastEditor:id,name',
                ],
            )
            ->paginate($this->perPage);
```

**Comment by taylorotwell** [comment]
I think it's because you are appending to a model instance then starting a new query. You need to call append on each of the resulting paginator items. `$data->each(fn ($data) => $data->append('picture'));`

**Comment by harrisdt15f** [comment]
After I added this and then it disappeared pagination result.
![image](https://user-images.githubusercontent.com/27404296/82154320-94afe980-989f-11ea-8a29-ba873a30d7ca.png)

```
->paginate($this->perPage)->each(function ($item) {
                $item->append('pic');
            });
```

**Comment by harrisdt15f** [comment]
Thank you.

**Comment by harrisdt15f** [comment]
I think I would be better if  paginate method could get append field from the result from model instance.

**Comment by locojuhi** [comment]
I've opened this thread because I'm trying to use the paginate method with two fields that are json (media, tagged) and also has property accessors. It looks like if is not taking the accessors in consideration when printing.

Is there any way to handle this or I'm doing the whole thing wrongs?

Thank you very much for your time before hand
`JSON{
    "current_page": 1,
    "data": [
        {
            "id": 6,
            "description": "is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "achievement": null,
            "public_id": "88101a9952ab80480c6912824038951d13867d34",
            "media": "[{\"type\": \"image\", \"150_150\": {\"url\": \"https://placeimg.com/150/150/people\"}, \"240_150\": {\"url\": \"https://placeimg.com/240/150/people\"}, \"450_300\": {\"url\": \"https://placeimg.com/450/300/people\"}, \"1280_860\": {\"url\": \"https://placeimg.com/1280/860/people\"}}, {\"type\": \"image\", \"150_150\": {\"url\": \"https://placeimg.com/150/150/people\"}, \"240_150\": {\"url\": \"https://placeimg.com/240/150/people\"}, \"450_300\": {\"url\": \"https://placeimg.com/450/300/people\"}, \"1280_860\": {\"url\": \"https://placeimg.com/1280/860/people\"}}]",
            "pet": 1,
            "created_by": 1,
            "created_at": "2020-05-27 23:16:03",
            "updated_at": "2020-05-27 23:16:03",
            "deleted_at": null,
            "tagged": "[{\"id\": \"some-public-id\", \"name\": \"Pepito perez\"}]",
            "position": null
        }
    ],
    "first_page_url": "http://localhost/api/posts?page=1",
    "from": 1,
    "last_page": 6,
    "last_page_url": "http://localhost/api/posts?page=6",
    "next_page_url": "http://localhost/api/posts?page=2",
    "path": "http://localhost/api/posts",
    "per_page": 1,
    "prev_page_url": null,
    "to": 1,
    "total": 6
}`
