### ISSUE TITLE
Wrong count() when limit is used in query scope

### ISSUE THREAD

**Issue by EmanueleCoppola** [laravel/framework#32855]
- Laravel Version: v7.11.0
- PHP Version: 7.4.1
- Database Driver & Version: sqlite

### Description:
When calling the count() function on a model by passing through a query scope that uses the limit(x) function, the count is wrong.

I reproduced the issue in this repository: https://github.com/EmanueleCoppola/laravel-limit-in-scope-error

### Steps To Reproduce:
Create a query scope like
```php
<?php

class Test extends Model
{
    //

    public function scopeTest($query) {
        return $query->where('something', 'test');
    }

    public function scopeTestWithLimit($query) {
        return $query->where('something', 'test')->limit(10);
    }

}
```

```php
<?php

// By calling
Test::test()->count(); // The output will 50
Test::test()->get()->count(); // The output will be 50
Test::testWithLimit()->count(); // The output will be 50
Test::testWithLimit()->get()->count(); // The output will be 10
```
Those steps are already implemented in the repository that I linked above.

**Comment by taylorotwell** [comment]
Note that this is how databases behave:

![image](https://user-images.githubusercontent.com/463230/82153793-46630200-982f-11ea-9ef9-53ffb2a32f5a.png)

You are limiting the result set.
