### ISSUE TITLE
make:component command makes an incorrect view file reference when using a namespace for the new component

### ISSUE THREAD

**Issue by peterfox** [laravel/framework#32860]
- Laravel Version: 7.11.0
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:

When making a component file via the artisan command, namespaced Components produce view references with a backlash and hyphen instead of a period (`\-` instead of `.`). e.g. `Input\\Basic` produces `return view('components.input\-basic');`

### Steps To Reproduce:

1. run:

`php artisan make:component Input\\Basic`

2. view newly created file `app/Components/Input/Basic.php`

3. line 26 will contains:

`return view('components.input\-basic');` when expected line to say `return view('components.input.basic');`

**Comment by taylorotwell** [comment]
`php artisan make:component Input/Basic`

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by peterfox** [comment]
@taylorotwell thank you
