### ISSUE TITLE
Str plural breaking change!

### ISSUE THREAD

**Issue by chadidi** [laravel/framework#32864]
- Laravel Version: v6.18.14
- PHP Version: 7.4

### Description:
I've updated Laravel from `v6.18.11` to `v6.18.14`, and some of my eloquent queries broke the problem is with `Str::plural()`

For example:
`Experience` model broke cause `Str::plural('experience')` output is `experience` when before it was `experiences`.
### Steps To Reproduce:
- Update to `v6.18.14`
- try `Str::plural('experience')`

**Comment by GrahamCampbell** [comment]
Please report this to the inflector team.

**Comment by GrahamCampbell** [comment]
https://github.com/doctrine/inflector

**Comment by GrahamCampbell** [comment]
Actually, this is already fixed, but not release yet: https://github.com/doctrine/inflector/compare/1.4.1...1.4.x.
