### ISSUE TITLE
New laravel 7 feature Date Serialization error with not UTC timezone

### ISSUE THREAD

**Issue by daparisi** [laravel/framework#32871]
- Laravel Version: 7.11.0
- PHP Version: 7.3.7
- Database Driver & Version: MySQL 5.7.30

### Description:
Laravel configurated with a different timezone from UTC returns an object with an attribute cast as date in bad format.

### Steps To Reproduce:
Config the laravel app with a timezone different from UTC.
/config/app.php -> 'timezone' => 'Europe/Madrid',
Create a model with an attribute cast as date that is stored in database as date format (not datetime or timestamp).
Return the model attributes in json.

In my case with a date stored in database as "2020-05-18" laravel returns the object as JSON with attribute value "2020-05-17T22:00:00.000000Z".

To solve it I override the function asDate in class 'HasAttributes' in my model with this:
protected function asDate($value)
    {
        return $this->asDateTime(Carbon::createFromFormat('Y-m-d', $value, 'UTC')->startOfDay());
    }

**Comment by taylorotwell** [comment]
https://laravel.com/docs/7.x/upgrade#date-serialization
