### ISSUE TITLE
Release 7.11.0 lost file 

### ISSUE THREAD

**Issue by fengchenghao** [laravel/framework#32880]
- Laravel Version: 7.0
- PHP Version: 7.2.29
- Database Driver & Version: doesn't matter

### Description:
Lost a file:
framework/src/Illuminate/Http/Middleware/TrustHosts.php

### Steps To Reproduce:
$ laravel new project
$ vi /project/app/Http/Middleware/TrustHosts.php

Line 5: use Illuminate\Http\Middleware\TrustHosts as Middleware;
I can find it in Branch 7.x, but it is not in release 7.11.0.

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Http/Middleware/TrustHosts.php
https://github.com/laravel/framework/tree/f4563bd2e0875c59a1f7967abdbe5cef7f240117/src/Illuminate/Http/Middleware

**Comment by thisismhp** [comment]
i haven't this issue with laravel last version

**Comment by brunogaspar** [comment]
That file was added 10 hours ago
v7.11.0 was released 6 days ago

It was not released yet, nothing is missing, so you just need to wait for a new release for you to use it, or just use the unreleased (dev) version.

**Comment by GrahamCampbell** [comment]
This will be included in today's release. The middleware is commented out by default in laravel/laravel, so new app creation until the release is made will still work fine.
