### ISSUE TITLE
Subdomain cookie not being set in safari browser

### ISSUE THREAD

**Issue by anishdcruz** [laravel/framework#32896]
- Laravel Version: 7.11.0
- PHP Version: 7.4.3
- Database Driver & Version: Mysql 5.7.29

### Description:

I wanted to share the cookie of `wesbite.test` and its subdmain `cp.website.test`
So i set `SESSION_DOMAIN=.website.test` prefixed with dot, but no cookie is being set for subdomains in safari and all IOS mobile browsers.

It works fine in chrome.

Is this an expected behaviors for cookies to be not set in safari?

In Chrome
<img width="1440" alt="Screen Shot 2020-05-19 at 3 49 31 PM" src="https://user-images.githubusercontent.com/2182620/82380780-547c7280-9a29-11ea-9e93-e3b7afd193d8.png">

Safari
<img width="1440" alt="Screen Shot 2020-05-19 at 3 49 44 PM" src="https://user-images.githubusercontent.com/2182620/82380789-56decc80-9a29-11ea-8f64-0b943224e74c.png">

### Steps To Reproduce:

```
// file .env
SESSION_DOMAIN=.website.test
SESSION_COOKIE=website_session
```

```
// file RouteServiceProvider.php
Route::domain('cp.website.test')
    ->as('admin:')
    ->middleware('web')
    ->namespace($this->namespace)
    ->group(base_path('routes/admin.php'));
```

```
// file routes/admin.php
Route::group(['middleware' => 'guest'], function() {
    Route::get('/', function() {
        return 'admin';
    });
});
```

On visiting http://cp.website.test/

- chrome: cookie is set
- safari macos 10.15.1: cookie is not set
- iphone7 (13.2) safari and chrome: cookie is not set

**Comment by laurencei** [comment]
Humor me - and try changing `website_session` to `websitesession`

There was a bug back in IE8 that `_` in cooklies caused problems. *maybe* its the same here.

**Comment by anishdcruz** [comment]
@laurencei when using `SESSION_DOMAIN=null` cookie is being set for that particular subdomain.
I guess naming is not an issue here.
Thanks

**Comment by GrahamCampbell** [comment]
Is this the case in the very latest version of Safari?

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2829600/82428068-def0c080-9a81-11ea-9561-0ce23ff93203.png">

**Comment by anishdcruz** [comment]
<img width="282" alt="Screen Shot 2020-05-20 at 1 06 14 PM" src="https://user-images.githubusercontent.com/2182620/82439373-d658b400-9a9a-11ea-802c-0fb3d1b37273.png">

There is issue with IOS (13.2) mobile browse safari, chrome, edge too.
I tested login form in mobile and all of them throw 419 because no cookie was send on form submission . 

Also each page refresh new session is created in database.

**Comment by taylorotwell** [comment]
I'm not sure this is a Laravel issue.

**Comment by anishdcruz** [comment]
I tested this in vanilla php and the cookie is being set.

<img width="1440" alt="Screen Shot 2020-05-21 at 3 45 49 AM" src="https://user-images.githubusercontent.com/2182620/82514574-65ef7880-9b16-11ea-8968-4d4897318cd4.png">

<img width="1440" alt="Screen Shot 2020-05-21 at 3 46 08 AM" src="https://user-images.githubusercontent.com/2182620/82514580-6982ff80-9b16-11ea-85d3-4da1b679a38b.png">

/etc/hosts
```
127.0.0.1   cookie.localhost
127.0.0.1   cp.cookie.localhost
```

cookie.php
```
<?php
    $value = '1';
    $name = 'safari';

    setcookie($name, $value, [
        'expires' => time() + 86400,
        'path' => '/',
        'domain' => '.cookie.localhost',
        'secure' => false,
        'httponly' => true,
        'samesite' => 'Lax',
    ]);

    echo $_SERVER['HTTP_HOST'];
?>
```

```
php -S localhost:8000

```

Cookie is being set for both `cookie.localhost` and `cp.cookie.localhost`

**Comment by anishdcruz** [comment]
Finally issue resolved.
Ran `valet tld localhost` and every worked as expected. 
Thanks

**Comment by dergoldbroiler** [comment]
> $value = '1';
>     $name = 'safari';
> 
>     setcookie($name, $value, [
>         'expires' => time() + 86400,
>         'path' => '/',
>         'domain' => '.cookie.localhost',
>         'secure' => false,
>         'httponly' => true,
>         'samesite' => 'Lax',
>     ]);

thanks a lot, without the additional arguments i did not get it to work in safari. this was the solution 👍

**Comment by jeff-h** [comment]
@anishdcruz can you elaborate on why `valet tld localhost` fixed it for you? Did you also change your domains to  `website.localhost` and `cp.website.localhost`?

I have the same issue but don't use valet.

**Comment by efriandika** [comment]
Yes.. I got similar issue too.. I am not sure this is laravel or safari problem..

**Comment by valh1996** [comment]
Same problem here...

**Comment by jacknotman** [comment]
This looks to be a Safari issue, having the same problem on node, using the http module. Chrome / Firefox have no issue setting the cookie ~ interestingly I am able to set some cookies, but not others, even though these cookies are being set with the same / similar parameters
