### ISSUE TITLE
exists validation issue

### ISSUE THREAD

**Issue by thisismhp** [laravel/framework#32904]
- Laravel Version: 7.12.0
- PHP Version: 7.4.2
- Database Driver & Version: dosn't matter

### Description:
When we use exists validation like below : 

`'post_id' => ['required', Rule::exists('posts', 'id')->whereNull('deleted_at')],`

if we pass any string after correct id , like : `2foo` , input is valid and laravel dosn't throw validation exception

**Comment by taylorotwell** [comment]
That generally seems to be MySQL behavior: select * from users where id = '1foo'

Will return a user with an ID of 1. Try adding the integer validation rule.
