### ISSUE TITLE
When logout and check auth still returning true

### ISSUE THREAD

**Issue by mrhili** [laravel/framework#32903]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

php": "^7.2.5",
        "acaronlex/laravel-calendar": "^1.0",
        
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelcollective/html": "^6.1",

### Description:

I guess session is nut flushed

### Steps To Reproduce:

Logout

@auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest

result:
The user is authenticated...

**Comment by mrhili** [comment]
C:\laragon\www\ZOUHAIR\calendar\vendor\laravel\ui\auth-backend\AuthenticatesUsers.php



   public function logout(Request $request)
    {
        $this->guard()->logout();



        $request->session()->invalidate();

#**THIS LINE ADDED**

        $request->session()->flush();




FEEL REE TO CLOSE WHEN YOU SEE THAT BUG

**Comment by taylorotwell** [comment]
Usually after logout you should redirect to another page.

**Comment by mrhili** [comment]
But I will still be logged in.

and never log out

a lot of people talk about that in StackOverflow

Do you suggest that when I logout I will redirect to another page and flush the session?
