### ISSUE TITLE
Str::*() methods work inconsistently for certain special characters

### ISSUE THREAD

**Issue by musahakeem** [laravel/framework#32910]
- Laravel Version: 7.0
- PHP Version: 7.2.24

### Description:
[IJMES](https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/information/author-resources/ijmes-translation-and-transliteration-guide) is a Cambridge standard for transliteration of Middle Eastern studies. Some of those transliteration characters unfortunately don't work consistently when using `Str::title()`, `Str::slug()` and other methods such as `Str::studly()`.

### Steps To Reproduce:
```php
$ php artisan tinker

>>> Str::title('Al-Fātiḥah');
=> "Al-Fātiḥah"
>>> Str::slug('Al-Fātiḥah');
=> "al-fatiah" // <-- Wrongly eaten up 'h'

>>> Str::title('ʾĀli-ʿImrān');
=> "ʾāli-ʿimrān" // <-- Wrongly lowercased 'Ā' and 'I' due to preceding ʾ and ʿ
>>> Str::studly('ʾĀli-ʿImrān');
=> "ʾĀliʿImrān"
>>> Str::slug('ʾĀli-ʿImrān');
=> "ali-imran"

>>> Str::title('Aṣ-Ṣāffāt');
=> "Aṣ-Ṣāffāt"
>>> Str::studly('Aṣ-Ṣāffāt');
=> "AṣṢāffāt"
>>> Str::slug('Aṣ-Ṣāffāt');
=> "as-saffat"

>>> Str::title('Ṭāʾ Hāʾ');
=> "Ṭāʾ Hāʾ"
>>> Str::slug('Ṭāʾ Hāʾ');
=> "ta-ha"

>>> Str::title('Yōenoes');
=> "Yōenoes"
>>> Str::slug('Yōenoes');
=> "yoenoes"

>>> Str::title('ʾIbrāhīem');
=> "ʾibrāhīem" // <-- Wrongly lowercased 'I' due to preceding ʾ
>>> Str::studly('ʾIbrāhīem');
=> "ʾIbrāhīem"
>>> Str::slug('ʾIbrāhīem');
=> "ibrahiem"
>>> Str::title('\'Ibrāhīem'); // <-- using regular apostrophe
=> "'ibrāhīem" // <-- Wrongly lowercased 'I' due to preceding apostrophe
```

As can be seen, both `Str::title()` and `Str::slug()` yield inconsistent results. But this is also the case when compared to `Str::studly()` and probably other methods.

**Comment by musahakeem** [comment]
To hopefully make unit testing easier, I prepared these two arrays:
```php
// Capitalization
$specialCharacterMap = [
    'ñ' => 'Ñ',
    'ğ' => 'Ğ',
    'ş' => 'Ş',
    'ṣ' => 'Ṣ',
    'ḍ' => 'Ḍ',
    'ż' => 'Ż',
    'ç' => 'Ç',
    'ṭ' => 'Ṭ',
    'ḥ' => 'Ḥ',
    'ẓ' => 'Ẓ',
    'ḳ' => 'Ḳ',
    'ā' => 'Ā',
    'ū' => 'Ū',
    'ō' => 'Ō',
    'ī' => 'Ī',
    'ü' => 'Ü',
    'ö' => 'Ö',
];

// Slugification
$specialCharacterSlugMap = [
    'ʾ' => '',
    'ñ' => 'n',
    'ğ' => 'g',
    'ş' => 's',
    'ṣ' => 's',
    'ḍ' => 'd',
    'ż' => 'z',
    'ç' => 'c',
    'ṭ' => 't',
    'ḥ' => 'h',
    'ẓ' => 'z',
    'ʿ' => '',
    'ḳ' => 'k',
    'ā' => 'a',
    'ū' => 'u',
    'ō' => 'o',
    'ī' => 'i',
    'ü' => 'u',
    'ö' => 'o',
];
```
Here is the entire list: [Cambridge IJMES TransChart PDF](https://www.cambridge.org/core/services/aop-file-manager/file/57d83390f6ea5a022234b400/TransChart.pdf).

**Comment by taylorotwell** [comment]
All we do is call `mb_convert_case` on `Str::title`. Perhaps raise an issued with PHP.

**Comment by musahakeem** [comment]
I see...
https://github.com/laravel/framework/blob/7ebd21193df520d78269d7abd740537a2fae889e/src/Illuminate/Support/Str.php#L522-L531

@taylorotwell what about `Str::slug()` eating up the `ḥ`?

```php
>>> Str::slug('Al-Fātiḥah');
=> "al-fatiah" // <-- Wrongly eaten up 'ḥ' rather than converting to 'h'
```

https://github.com/laravel/framework/blob/7ebd21193df520d78269d7abd740537a2fae889e/src/Illuminate/Support/Str.php#L544-L571
