### ISSUE TITLE
exception-render-report.stub Line indented incorrectly; expected 4 spaces, found 5

### ISSUE THREAD

**Issue by Alphaws** [laravel/framework#32916]
Line indented incorrectly; expected 4 spaces, found 5
https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Foundation/Console/stubs/exception-render-report.stub#L14

**Comment by GrahamCampbell** [comment]
Thanks for reporting. This will be fixed in Tuesday's 6.x and 7.x releases.
