### ISSUE TITLE
Storage::path breaks when using cache due to missing method in CachedAdapter

### ISSUE THREAD

**Issue by rezen** [laravel/framework#32917]
- Laravel Version: v7.12.0
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
If you use caching for the filesystem, setting a config in `config/filesystems.php` like seen below and then call `Storage::path("sample/hello.html");` you will get the error 
```
Error: Call to undefined method League\Flysystem\Cached\CachedAdapter::getPathPrefix() 
in file /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php
on line 119
```

**Config**  
```php
<?php

// ...
 'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'cache' => [
                'store' => 'redis',
                'expire' => 600,
                'prefix' => 'fs_cache_local',
            ],
        ],
```

### Options
- ~~Upgrade the flysystem-cached-adapter package to 1.0.9~~
- Patch `FilesystemAdapter` with something like the suggestion below
```php
    public function path($path)
    {
-        return $this->driver->getAdapter()->getPathPrefix().$path;
+        $adapter = $this->driver->getAdapter();
+        if ($adapter instanceof CachedAdapter) {
+                $adapter = $adapter->getAdapter();
+        }
+        return $adapter->getPathPrefix().$path;

    }
```

**Comment by rezen** [comment]
I can PR it, just figured I should start with an issue.

**Comment by taylorotwell** [comment]
Sure, feel free to send over the PR. Thanks.

**Comment by ThaDaVos** [comment]
I'm running into the same issue as above but than on Laravel 6 (as it's the LTS, not 7)
Is there any fix for this except disabling the caching?
