### ISSUE TITLE
Unable to set REQUEST_URI after getting REQUEST_URI

### ISSUE THREAD

**Issue by KeithTurkowski** [laravel/framework#32929]
- Laravel Version: 6.2
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:
I believe this is a caching bug related to modifying the REQUEST_URI. If I use any of the request getter functions to query the REQUEST_URI, such as `$request->server->get()` it seems to prevent the setters from working, e.g. `$request->server->set('REQUEST_URI', "test")`.

### Steps To Reproduce:
I have the following middleware, which works as I want (which I specify in app\Http\Kernel.php):
```
<?php

namespace App\Http\Middleware;

use Closure;

class Localize
{
    public function handle($request, Closure $next)
    {
        if(substr($_SERVER['REQUEST_URI'], 0, 4 ) === "/es/" || $_SERVER['REQUEST_URI'] === "/es")
        {
            $request->server->set('REQUEST_URI', substr($_SERVER['REQUEST_URI'], 4));
            app()->setLocale('es');
        }
        return $next($request);
    }
}
```
This middleware checks to see if the REQUEST_URI begins with `/es`, if so it removes that portion of the REQUEST_URI and changes the locale before continuing on to the routing in web.php.

Notice that I am using PHP `$_SERVER['REQUEST_URI']` to query the value of the REQUEST_URI.

If I modify that code to instead use any kind of $request call to a getter method, such as `$request->server->get()` before I call `$request->server->set()`, the setter seems to no longer modify the REQUEST_URI as expected for purposes of routing in web.php.

I'm guessing that $request does some sort of caching that is triggered when you use a getter, and doesn't recache as I expect when using a subsequent setter.

**Comment by driesvints** [comment]
This is a little too much magic going on here I think. I have no idea how this would even work with routes already loaded into the router let alone route caching.

**Comment by b-karin** [comment]
Here is an alternative way of doing it. An example is using Lumen, but you can apply it with a little changes.
`<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class SetLocale
{
    public function handle($request, Closure $next, $guard = null)
    {
      $lang = substr($request->path(), 0, 2);
      if (in_array($lang, ['es'])) {
        config(['app.locale' => $lang]);
        $proxy = Request::create(
          substr($request->path(), 3),
          $request->method(),
          $request->all()
        );
        return app()->dispatch($proxy);  
      }

      return $next($request);
    }
}
`
