### ISSUE TITLE
Model $attributes gives error with Model::firstOrCreate()

### ISSUE THREAD

**Issue by tanthammar** [laravel/framework#32925]
- Laravel Version: 7.11.0
- PHP Version: 7.4.4
- Database Driver & Version: MySql 5.7

### Description:
model `$attributes` gives error when I try to use `Model::firstOrCreate()`

### Steps To Reproduce:

I have this on a model:
```js
    protected $attributes = [
        'invoicing' => [
            'calc_due_days_from' => 'invoice_date',
            'invoice_date_num_days' => 30,
            'before_start_num_days' => 48,
            'currency_code' => 'SEK',
            'currency_symbol' => 'kr',
            'invoice_note' => null,
            'inv_prefix' => null,
            'inv_suffix' => null,
            'inv_counter' => null,
            'cred_note' => null,
            'cred_prefix' => null,
            'cred_suffix' => null,
            'cred_counter' => null,
        ],
    ];
```

It works great with `new Model` but I get an error if I try to use `firstOrCreate()`

**Error in TinkerWell**
```info
Argument 1 passed to Illuminate/Database/Grammar::parameterize() must be of the type array, string given, called in /Users/tina/Sites/bookons-api/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 866
```

**Error in Horizon** (I am trying to make a batch import)
```info
ErrorException: json_decode() expects parameter 1 to be string, array given in /Users/tina/Sites/bookons-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:811
```

_If I comment out the attributes I can use firstOrCreate() without any problem._

**Comment by tanthammar** [comment]
The same applies for `Model::create()`

**Comment by taylorotwell** [comment]
Does this attribute have any type of cast on it?

**Comment by tanthammar** [comment]
Thank you for your reply :)

yes:
```js
protected $casts = [
        'invoicing' => 'array',
];
```

**Comment by tanthammar** [comment]
And here is a part of the batch import that relates to the attribute:
```js
$this->organizer = Organizer::unguarded(function () {
            return Organizer::firstOrCreate(
                ['id' => $this->post['ID']],
                [
                    //... lots of fields
                    'invoicing' => [
                        'calc_due_days_from' => $this->get_due_days_setting(),
                        'invoice_date_num_days' => $this->meta('wpcf-org-due-days') ?? null,
                        'before_start_num_days' => $this->meta('wpcf-market-due-days') ?? null,
                        'currency_code' => 'SEK',
                        'currency_symbol' => 'kr',
                    ],
                 //... more fields
            );
        });

**Comment by netpok** [comment]
You shouldn't override the attributes array on the model manually I think, also you are storing an array in it so when the json cast tries to decode the array it will fail.

**Comment by tanthammar** [comment]
@netpok I don't really follow you.
1.  An attribute is a default value that you are allowed to override anywhere.
2. I am always using the array form to store data in a json column. Never any issues. (given that it is casted to an array)

**Comment by tanthammar** [comment]
@netpok hmm do you mean that I have to new up a model ->then change the attributes ->then save() instead of Create?

**Comment by netpok** [comment]
The attributes array stores the attributes in a database compatible format, I never used it in that way, usually when I needed a similar feature I used the model::creating event to set them if needed.

If you still want to use that you need to use that in the same format as the database (a JSON string), but please note laravel will not merge those fields for you, it will just simply overwrite it with the data you provided.

To achieve what you wanted you should probably use something similar:
```php
static function boot(){
    parent::boot();

    static::creating(function($model){
        $model->invoicing = array_merge([/* defaults */], $model->invoicing);
    });
}
```

**Comment by tanthammar** [comment]
@taylorotwell Can you please confirm that the suggested solution from @netpok  is correct?
Feels awkward that I should not be able to override the models $attribute on the create method.

**Comment by driesvints** [comment]
Attributes are the values after they've already been casted. You'll need to either provide the json payload in the attributes array or use something like @netpok suggested.

**Comment by tanthammar** [comment]
@driesvints 
So, This is because it is an array??
I am sorry for being slow headed but I want to understand.

I did a test and this works as I expect. 
I can set a default value with the `$attributes` prop but still override it on the create method.
**So this works:**
```js
protected $attributes = [
        'first_name' => 'Pop',
        'last_name' => 'Eye',
]
```
```js
Organizer::firstOrCreate(
    ['id' => 100],
    [
        'first_name' => 'Super',
        'last_name' => 'Man',
    ]
);
``` 
returns
```js
App\Models\Organizer {
     first_name: "Super",
     last_name: "Man",
}
```

But this not:
```js

protected $casts = [
    'name' => 'array'
];

protected $attributes = [
  'name' => [
        'first_name' => 'Pop',
        'last_name' => 'Eye',
    ]
];

Organizer::firstOrCreate(
    ['id' => 200],
    [
        'name' => [
        	'first_name' => 'Super',
        	'last_name' => 'Man',
    	],
    ]
);
```

**Comment by driesvints** [comment]
```php
protected $attributes = [
    'invoicing' => '{"calc_due_days_from":"invoice_date","invoice_date_num_days":30,"before_start_num_days":48,"currency_code":"SEK","currency_symbol":"kr","invoice_note":null,"inv_prefix":null,"inv_suffix":null,"inv_counter":null,"cred_note":null,"cred_prefix":null,"cred_suffix":null,"cred_counter":null}',
];
````

**Comment by tanthammar** [comment]
Thank You both @driesvints  and @netpok for taking the time to explain :)
Grateful!

**Comment by netpok** [comment]
@tanthammar Please note:
Setting
```
protected $attributes = [
    'invoicing' => '{"calc_due_days_from":"invoice_date","invoice_date_num_days":30,"before_start_num_days":48,"currency_code":"SEK","currency_symbol":"kr","invoice_note":null,"inv_prefix":null,"inv_suffix":null,"inv_counter":null,"cred_note":null,"cred_prefix":null,"cred_suffix":null,"cred_counter":null}',
];
```
and than calling:
```php
$model = Model::create(['invoicing'=>['invoice_note'=>'A note']]);
```
will result in:
`$model->invoicing` being equal to `['invoice_note'=>'A note']`

**Comment by tanthammar** [comment]
@netpok Tnx!!! 
I went with your suggestion and it is working great :)

> The attributes array stores the attributes in a database compatible format, I never used it in that way, usually when I needed a similar feature I used the model::creating event to set them if needed.
> 
> If you still want to use that you need to use that in the same format as the database (a JSON string), but please note laravel will not merge those fields for you, it will just simply overwrite it with the data you provided.
> 
> To achieve what you wanted you should probably use something similar:
> 
> ```
> static function boot(){
>     parent::boot();
> 
>     static::creating(function($model){
>         $model->invoicing = array_merge([/* defaults */], $model->invoicing);
>     });
> }
> ```
