### ISSUE TITLE
Migration ignores new columns when also dropping existing columns (SQLite)

### ISSUE THREAD

**Issue by TheDoctor0** [laravel/framework#32922]
- Laravel Version: 7.12.0
- PHP Version: 7.4.5
- Database Driver & Version: SQLite

### Description:
New columns are not added to the table when the migration both creates a new column and drops the existing one. After splitting those changes to separate migrations the problem no longer exists.
This issue seems to be SQLite related as with PostgreSQL it works fine.

### Steps To Reproduce:
1. Create a migration for the table.
2. Add the second migration with schema change that adds a new column and drops an existing column.
3. The existing column has been dropped but a new column is not present in the table.

**Comment by taylorotwell** [comment]
Don't do that with SQLite. It doesn't support a variety of operations.

**Comment by nvahalik** [comment]
Workaround (for anyone who finds this):

Just wrap the deletion in a separate block:

e.g. this:

```
Schema::table('users', function (Blueprint $table) {
    $table->dropColumn('columnToRemove');
    $table->string('columnToAdd');
});
```

Would become this:

```
Schema::table('users', function (Blueprint $table) {
    $table->dropColumn('columnToRemove');
});

Schema::table('users', function (Blueprint $table) {
    $table->string('columnToAdd');
});
```
