### ISSUE TITLE
storedAs columns cannot be accessed as model attribute in tests

### ISSUE THREAD

**Issue by erayerdin** [laravel/framework#32939]
- Laravel Version: 7.0
- PHP Version: 7.4.5
- Database Driver & Version: `mariadb  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1`

### Description:
You cannot access a `storedAs` column in a model instance while in tests.

### Steps To Reproduce:

**1. Change `phpunit.xml` to MariaDB.**

By default, PHPUnit uses in-memory SQLite for faster migration and refresh yet SQLite does not have a concept of virtual or stored generated columns. We need to explicity tell PHPUnit to use a MariaDB database. This test database, in my environment, is a separate database from dev database (dev database contains seeds, I clearly wouldn't like to access my dev database while testing).

```xml
<!---->
<php>
    <!---->
    <server name="DB_CONNECTION" value="mysql"/>
    <server name="DB_DATABASE" value="another_test_database"/>
    <server name="DB_USERNAME" value="testuser"/>
    <server name="DB_PASSWORD" value="testpassword"/>
    <!---->
</php>
<!---->
```

**2. Create new model and fill migrations.**

```bash
php artisan make:model Message -mfs  # also create migration
```

Open generated migration file and fill it:

```php
// ...
$table->id();
$table->timestampsTz();
$table->text('content');
$table->boolean('sent_by_email')->default(false);
$table->boolean('sent_by_sms')->default(false);
$table->boolean('sent_by_notification')->default(false);
// ...
```

Logically, we could also add relations such as sender or receiver but those are not in the scope of this issue so will not be added.

We will create another migration because that's what I did in my environment and I'd like to keep it close to my environment.

```bash
php artisan make:migration add_sent_all_to_messages --table messages
# table is "messages"
```

Fill it:

```php
// ...
$table->boolean('sent_all')
    ->nullable()
    ->storedAs('sent_by_email AND sent_by_sms AND sent_by_notification');
// ...
```

**3. Fill factory.**

```php
$factory->define(Message::class, function (Faker $faker) {
    return ['content' => $faker->text];
});
```

**4. Test on tinker.**

I can oddly access `sent_all` in Tinker as below:

```php
$message = factory(Message::class)->create([
    'sent_by_email' => true, 'sent_by_sms' => true, 'sent_by_notification' => true
]);
// the output shows 'sent_all' and it says it's true. I can also access it directly.
$message->sent_all
// true
```

**5. Access on tests.**

This is the buggy part. Simply create a test:

```bash
php artisan make:test MessageTest --unit
```

Fill the test:

```php
// ...
use Tests\TestCase;
// ...
class MessageTest extends TestCase {
    use RefreshDatabase;

    public function testSentAll() {
        $message = factory(Message::class)->create([
             'sent_by_email' => true, 'sent_by_sms' => true, 'sent_by_notification' => true
        ]);
        $this->assertNotNull($message->sent_all);  // will fail here saying it is null
    }
}
```

**6. A workaround: Adding as accessor.**

When I add it as accessor, test succeeds. Go to Message model and add:

```php
public function getSentAllAttribute(): bool {
    return DB::table('messages')->where('id', '=', $this->id)->select('sent_all')->first()->sent_all;
}
```

Intuitively, PHPUnit should not fail in step 5 but adding this somehow solves the problem.

**Comment by jamie-brown** [comment]
Does it work if you do: 

```php
$message->fresh()->sent_all
```

**Comment by erayerdin** [comment]
@jamie-brown Yes, now it works.

I guess I know where you're coming from. Since the column computation is on database side and we do not provide `sent_all` by hand in the example above, it's natural for Laravel to not know it until it specifically query the database for `sent_all` field.

Still, though, it's odd that this works in Tinker.

**Comment by dorqa95** [comment]
I have the same issue with Laravel 9.4, PHP 8.1.12, Postgresql 14.6 when testing. As a workaround, is also made a mutator in the Model, but calculated the attribute just when the field value is not avaliable:

```
public function company() : Attribute
{
    return Attribute::get(fn($value) => $value ?? preg_replace('(.+@)', '', $this->email));
}
