### ISSUE TITLE
Newly created migration file

### ISSUE THREAD

**Issue by Hrache** [laravel/framework#32949]
- Laravel Version: 7.10.2
- PHP Version: 7.4.4
- Database Driver & Version:
mariadb-10.4.12-winx64
### Description:
After using php artisan make:migration migration_name --create='new_migration' --table='new_migration' file gets generated within content such below:
function up()
{
	Schema::create(''new_migration'', ...
means that the argument contains PHP string related syntax error

### Steps To Reproduce:
Probably at the file content writing stage user provided quote signs should be ignored and proper code generated quotes should be used to prevent additional quote appearing.

**Comment by netpok** [comment]
As far as I know Windows does not support single quotes in command line, you should use double quotes.

**Comment by Hrache** [comment]
Here is what I mean and yes I'm using Windows 10:
[https://youtu.be/hcIg2aRaYQk](url)
