### ISSUE TITLE
Route prefix not found on Laravel

### ISSUE THREAD

**Issue by adeguntoro** [laravel/framework#32940]
I use very simpel code to make sure that my route is working, so i copy prefix route example from laravel website and it show me error 404 not found.
```
Route::prefix('admin')->group(function () {
    Route::get('users', function () {
        // Matches The "/admin/users" URL
    });
});
```
I use Laravel 6.12.0, but sometime my project on laravel 7 also have same problem.
Is this my error, or this error from Laravel it self ?
I also clean cache, config, route, view, optimize, still not success.

![error web route](https://user-images.githubusercontent.com/26304962/82732094-4b471a80-9d35-11ea-8659-4d3dc68c76c9.PNG)

**Comment by taylorotwell** [comment]
Works fine for me.

**Comment by adeguntoro** [comment]
okay, update for today, i know the reason why my prefix route not found, because this code :
```
Route::get('/{kategori}/{slug}', 'ArtikelController@show'); // This make prefix Error, with or without slash
```
and this is my full route : 
```
Route::get('/kategori/{slug}', 'ArtikelController@show'); // Okay
Route::get('/{kategori}/{slug}', 'ArtikelController@show'); // This make prefix Error, with or without slash

Route::prefix('admin')->group(function () {
    Route::get('users/{id?}', function ($id = null) {
        echo 'Matches The "/admin/users/" URL '.$id.''; //Okay
    });
    Route::get('role', function(){
        return view('role'); //Okay
    });
});

// This also fine if i put after prefix.
// Route::get('/', 'ArtikelController@index'); // Okay
// Route::get('/{kategori}/{slug}', 'ArtikelController@show'); // Okay
```
I'm not sure about laravel docs about how to use route, especialy about prefix and paramater.
