### ISSUE TITLE
In the picture below

### ISSUE THREAD

**Issue by Hrache** [laravel/framework#32953]
- Laravel Version: 6.9.0
- PHP Version: 7.4.4
- Database Driver & Version: mariadb-10.4.12-winx64

### Description:
As a notification it appeared in the githubs account of mine where it says that "Potential security vulnerability found in the symphony/http-foundation dependency.

### Steps To Reproduce:
I only wanted to know what it does mean and is it safe or no, and if no then what to do against ?

https://drive.google.com/file/d/1qpUdLd0xUvWeQNUXALE3RFMp0d8TVqlK/view

**Comment by driesvints** [comment]
Please don't post about security vulnerabilities publicly. Read our readme and our security policy: https://github.com/laravel/framework/security/policy
