### ISSUE TITLE
Mail message body not encoded.

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#32954]
- Laravel Version: 6.18.15
- PHP Version: 7.4.6

### Description:
I'm sending an email in a documented way, using Mailables with view() method pointing to a blade template. It looks to me that the sent message body is not encoded despite the fact that Content-Transfer-Encoding specifies quoted-printable. For example I expect all `=` replaced with `=3D`, but it's not only these. If I put some UTF-8 characters in the HTML content they are not encoded either.

Here's a fragment of a sample message (logged using MAIL_DRIVER=log):

```
...
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
...
```

**Comment by driesvints** [comment]
How are you sending the email? Can you share some code?

**Comment by alecpl** [comment]
It's very simple, I followed the doc. In a job I do:
```
Mail::to($email)->send(new SignupVerification($code));
```
and in SignupVerification mailable I do:
```
$this->view('emails.signup_code')->subject($subject)->with([]);
```
and in `resources/views/emails/signup_code.blade.php` I have the HTML content.

**Comment by driesvints** [comment]
Hmm, I have to admit I've never seen any request for this before nor do I know what this specifically does. The only thing that I find back for this is https://swiftmailer.symfony.com/docs/messages.html#setting-the-encoding

**Comment by taylorotwell** [comment]
Unclear what is the problem here. People send emails successfully with Laravel every day. Please submit a PR if there is a bug to fix.

**Comment by alecpl** [comment]
I guess most mail clients can display the message anyway, but that does not mean the message is valid. It's clear that the quoted-printable encoding is not used, but specified in the header.

Maybe it is a swiftmailer issue, maybe it's caused by how Laravel uses it. It is a shame that you don't care and pretend there's no bug.

**Comment by alecpl** [comment]
Oh, I think I found the culprit. The message is malformed only in log. So, this is a problem of `MAIL_DRIVER=log`. And looking at `getMimeEntityString()` method I see that indeed it builds the message output by calling `getBody()`. It should be using `toString()`. I confirm that change works. 

Now, I don't know whether it is a bug or it was designed to not contain encoded body in log. Please, decide, I can provide a PR.

**Comment by alecpl** [comment]
That was the initial behavior, but it has been changed in https://github.com/laravel/framework/commit/983009cce82c05b (5.0.30). So, looks like it is intended. Still, I'm not sure this is what most people would expect. As you can see it confused me.

**Comment by bastinald** [comment]
Anybody from google looking for a fix, use the `setEncoder` method in your mail:

```php
            Mail::raw($text, function (Message $message) use ($toAddress) {
                $message->to($toAddress);
                $message->setEncoder(new Swift_Mime_ContentEncoder_PlainContentEncoder('8bit'));
            });
```

You can see here, I am replacing `quoted-printable` with `8bit` which removes all the `3D` bullshit.

**Comment by ycoya** [comment]
Hello, @alecpl , It's been a while from this issue, but I'm facing the same problem, just using the log to check emails and get the links created which are turned into quoted-printable `=3D`. I'm using laravel version 9.41.0 and php 8.0.8.
I tracked the code and I found that in 
`Illuminate\Mail\Transport\LogTransport.php`
```
public function send(RawMessage $message, Envelope $envelope = null): ?SentMessage
{
    $this->logger->debug($message->toString());
    return new SentMessage($message, $envelope ?? Envelope::create($message));
}
```
The `$message->toString() `is where the text is Encoded to quoted-printable.
In `symfony\mime\Message.php`  We can see what this function does.
```
public function toString(): string
{
    if (null === $body = $this->getBody()) {
        $body = new TextPart('');
    }

        return $this->getPreparedHeaders()->toString().$body->toString();
 }

```
If we continue digging into **$body->toString()**, we can find that this is from `symfony\mime\Part\TextPart.php` and extends from `symfony\mime\Part\AbstractPart.php`, where the `toString()` method is defined.

```
public function toString(): string
{
    return $this->getPreparedHeaders()->toString()."\r\n".$this->bodyToString();
}
```
The `$this->bodyToString()` is defined in `symfony\mime\Part\TextPart.php`
```
public function bodyToString(): string
  {
      return $this->getEncoder()->encodeString($this->getBody(), $this->charset);
  }
```
And here we can see that an Encoder is used. If we go to `__construct` function of this `symfony\mime\Part\TextPart.php` we could be able to see this piece of code
```
   if (null === $encoding) {
        $this->encoding = $this->chooseEncoding();
    } else {
        if ('quoted-printable' !== $encoding && 'base64' !== $encoding && '8bit' !== $encoding) {
            throw new InvalidArgumentException(sprintf('The encoding must be one of "quoted-printable", "base64", or "8bit" ("%s" given).', $encoding));
        }
        $this->encoding = $encoding;
    }
```
The encoding passed is null so the line `$this->encoding = $this->chooseEncoding();` is executed,` chooseEncoding()` method is

```
 private function chooseEncoding(): string
  {
      if (null === $this->charset) {
          return 'base64';
      }

      return 'quoted-printable';
  }
```
Like charset is not null, then quoted-printable is used to encode the message when we use the mailer log to send emails. So this what happens and it comes from symfony. 

Looking for a workaround to this in laravel I followed the documentation to create custom channels for logging.
So I created a class in `app\Mail\Logging\CustomLogger.php` which extends from `Illuminate\Log\Logger`. Then I override the method debug, which is the one used in `Illuminate\Mail\Transport\LogTransport.php` in `send `method as I mentioned at the begining of this reply. 

In this method i check for a character =3D, perhaps there is other way to detect quoted-printable text, but this way worked for me. Anyway the idea is to convert back the quoted-printable to 8 bit-string. Using the quoted_printable_decode function for this purpose.
```
namespace App\Mail\Logging;
use Illuminate\Log\Logger;

class CustomLogger extends Logger
{
    public function debug($message, array $context = []): void
    {
        $message = str_contains($message, "=3D") ? quoted_printable_decode($message) : $message;
        $this->writeLog(__FUNCTION__, $message, $context);
    }
}
```
After this an invokable class was created in `app\Logging\CreateCustomMailLogger.php` this one  will resolve our custom channel using the CustomLogger before. Here we get `\Illuminate\Log\Logger` from container and pass to our CustomLogger construct method, the objects required to instantiate it.
```
namespace App\Logging;
use App\Mail\Logging\CustomLogger;
class CreateCustomMailLogger
{
    public function __invoke(array $config)
    {
         /**  @var \Illuminate\Log\Logger $log **/
        $log = resolve('log');
        return new CustomLogger($log->getLogger(), $log->getEventDispatcher());
    }
}
```
In `config\logging.php` I added a new channel. I named it maillog. In via option the CreateCustomMailLogger invokable class.

 ```
 'maillog' => [
          'driver' => 'custom',
          'via' => \App\Logging\CreateCustomMailLogger::class
        ],
```
In `config\mail.php` we check that the log mailer is this way, as it should be as default

```
'log' => [
            'transport' => 'log',
            'channel' => env('MAIL_LOG_CHANNEL'),
        ],
```
so in `.env` file. We set
```
MAIL_MAILER=log
MAIL_LOG_CHANNEL=maillog
```
So every time we send an email using the mailer log, the channel mailog is used, the logger with debug override method is used and we have our emails quoted-printable free and it doesn't interfere when sending emails using other transport layer.

Hope this help!
