### ISSUE TITLE
Can't use relationship with same model in $withCount

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/framework#32964]
- Laravel Version: 6.X.X & 7.X.X
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0.18

### Description:

Users can refer each other to our product, and therefore have the appropriate relations. I want to automatically load the counts of these relationships. This is the relevant part of my model:

```php
class User extends Authenticatable
{
    protected $withCount = ['referred', 'referrer'];

    public function referrer()
    {
        return $this->belongsTo(User::class, 'referrer_id');
    }

    public function referred()
    {
        return $this->hasMany(User::class, 'referrer_id');
    }
}
```

Querying the model now results in an out of memory exception, possibly due to an infinite loop.

For some reason, `User::withCount(['referred', 'referrer'])->restOfQuery()` works just fine.

### Steps To Reproduce:

1. Implement model with self-referential relation.
2. Add `$withCount = ['self_referential_relation']` to the model.
3. Query the model.

**Comment by driesvints** [comment]
You can't do that because it indeed causes an infinite loop of the subsequent model trying to do the withCount loading again.

**Comment by WouterFlorijn** [comment]
@driesvints so that's a bug right? To get the count of a relationship, why would the related model's withCount need to be loaded?

**Comment by Illizian** [comment]
I am experiencing a similar issue, however not with self-referential models.

```php
class Model_A extends Model
{
  protected $withCount = [
    'model_b',
  ];

  public function model_b()
  {
    return $this->belongsToMany(Model_B::class);
  }
}

class Model_B extends Model
{
  protected $withCount = [
    'model_a',
  ];
  
  public function model_a()
  {
    return $this->belongsToMany(Model_A::class);
  }
}
```

Am I being stupid? 😕

**Comment by bradley-varol** [comment]
For anyone stumbling across this, I used a global scope to apply my `withCount` method for all queries, and then disabled it for the self-referencing relationships. An example with a User model:

```php
class User
{

  protected static function boot()
  {
      parent::boot();
  
      static::addGlobalScope('withCounts', function (Builder $builder) {
          $builder->withCount([
              'posts',
              'comments',
              'followers',
          ]);
      });
  }
  
  public function followers()
  {
      return $this->belongsToMany(User::class)
          ->withoutGlobalScope('withCounts');
  }

}
```

**Comment by shengslogar** [comment]
I realize this is a very old issue but odd to me that this is still the same behavior in Laravel 9.x. This would make sense to fail if there were indeed circular references, but even attempting to load `hasMany(self::class)` relationships fail, where there would be a finite amount of cascading data-points to load.

It also doesn't explain why `protected $with =  [ 'sameClassRelation' ]` works while `protected $withCount = [ 'sameClassRelation' ]` doesn't. (Granted, I haven't dug through the Eloquent Builder source.)

If this is indeed intended/accepted behavior, would a PR for an exception being thrown when detecting a same-class relation be accepted rather than a 500/OOM error with no stack trace?

**Comment by 200-0K** [comment]
A fix for this i've found is to create a global scope and do the count manually with a subquery. 

Example:

```php
<?php

class Comment extends Model
{
  // ...

  protected static function booted()
  {
      static::addGlobalScope('withRepliesCount', function ($builder) {
          $builder->selectRaw('comments.*, (
              SELECT COUNT(*) 
              FROM comments as replies 
              WHERE replies.parent_id = comments.id 
              AND replies.deleted_at IS NULL
          ) as replies_count');
      });
  }

  // ...
}
```

The point here is to not use the self-refrential relationship method since it will cause an infinite loop and throw an out of memory exception
