### ISSUE TITLE
Issue with using "sticky" option with Postgresql driver and read/write connections.

### ISSUE THREAD

**Issue by nesh-ua** [laravel/framework#32966]
- Laravel Version: 7.4.3
- PHP Version: 7.12.0
- Database Driver & Version: PostgreSQL 12

### Description:
I have 2 connection with db (read/write). Also i set "sticky" option as true. After creating new row all request to DB use "read" connection. After updating some row, there are not any problem. This problem is happened when table has auto increment.

### Steps To Reproduce:
```
//create some row.
$quest = factory(Quest::class)->create();
// update this row. if i remove comment for next lines, everything work alright. Because update was made. But when we make only create, selection works via "read" connection.
//$quest->limit_winners = random_int(1, 200);
//$quest->update();
// find this row. (use read connection), but if i understood right have to use write connection, because new row was created.
$quest = Quest::query()->where('id', $quest->id)->first();
print_r($quest);
```

**Comment by taylorotwell** [comment]
Don't see any issue in the code. Feel free to make a PR to address any bug you find.

**Comment by nesh-ua** [comment]
@taylorotwell 
I found a problem here:
/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php
When called "processInsertGetId" function we only create new row via selectFromWriteConnection. But function "recordsHaveBeenModified" is not called (this need because all next requests have to use "write connection").

This is my pr https://github.com/laravel/framework/pull/32973
