### ISSUE TITLE
[7.2.1 to 7.12.0] Config cache path breaking change in Windows environments

### ISSUE THREAD

**Issue by derekmd** [laravel/framework#32960]
- Laravel Version: 7.12.0
- PHP Version: 7.4.5
- Database Driver & Version: N/A

### Description:

`FoundationApplicationTest` is currently failing when running the framework's test suite on Windows environments, which isn't reflected in Linux CI output.

https://github.com/laravel/framework/pull/31985 introduced a Windows environment breaking change in point release 7.2.1. The pull request description says:

> In default mode it's not affecting anything else.

Which is not true, unless I'm interpreting that sentence incorrectly.

### Steps To Reproduce:

```php
$_SERVER['APP_CONFIG_CACHE'] = '/ext/cache/config.php';
echo app()->getCachedConfigPath();
// "C:\Users\Foo\projects\blog\/ext/cache/config.php"
```

Pre-7.2.1, this returned `"/ext/cache/config.php"` for `"C:\ext\cache\config.php"` (assuming `getcwd()` fell under `C:\`.)

That pull request changed how the `Application` class treats `/`-prefixed paths in Windows. With `DIRECTORY_SEPARATOR`, `\` is the default prefix on Windows and the above is now a relative path.

```php
getcwd() . '/ext/cache/config.php'
```

### Choose 1 of 2 fixes:

1. This is the edgiest of edge cases. No bug report was filed in the past two months after this was introduced. Most likely userland calls `getcwd()` or `__DIR__` when setting up a custom absolute `new Application($path)`.

   Updating these tests:

   * `testEnvPathsAreUsedForCachePathsWhenSpecified`
   * `testEnvPathsAreUsedAndMadeAbsoluteForCachePathsWhenSpecifiedAsRelative`

   with this snippet:

   ```php
   $app = new Application('/base/path');
   if (DIRECTORY_SEPARATOR === '\\') {
      $app->addAbsoluteCachePathPrefix('/');
   }
   ```

   will make the tests green on all operating systems. Windows users must give a `C:\...` string going forward.

2. Or keep pre-7.2.1 behavior on Windows, the `Application` class can be be updated from:

   ```php
   class Application extends Container implements
       ApplicationContract,
       CachesConfiguration,
       CachesRoutes,
       HttpKernelInterface
   {
       // ...

       /**
        * The prefixes of absolute cache paths for use during normalization.
        *
        * @var array
        */
       protected $absoluteCachePathPrefixes = [DIRECTORY_SEPARATOR];
   ```

   to:

   ```php
       protected $absoluteCachePathPrefixes = ['/', '\\'];
   ```

   `/`-prefixed paths would again work on Windows.

I'll submit a pull request for one of the two. I'm wondering which way the framework wants to go.

**Comment by driesvints** [comment]
Hey @derekmd, thanks once again for a thorough explanation.  I'm guessing the second option is the most viable one here. 

Ping @krzysztofrewak.

**Comment by krzysztofrewak** [comment]
Second one looks better for me too. It's changing framework behaviout, not the tests themselves. 

Btw, I was using `__DIR__`  when I was working on Windows, thus I never noticed any errors.

**Comment by taylorotwell** [comment]
Second option is fine.

**Comment by taylorotwell** [comment]
Will close since PR is incoming.
