### ISSUE TITLE
Cannot use withCookies when making test JSON requests

### ISSUE THREAD

**Issue by Zakini** [laravel/framework#32965]
- Laravel Version: 7.10.3
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7.29-0ubuntu0.18.04.1

### Description:
Using `withCookies()` in a test when making a JSON request (`getJson()`, `postJson()`, etc.) does not send the cookies to the application.

### Steps To Reproduce:
Add this route:
```php
Route::get('/', function () {
    return response()->json(request()->cookie('foo'));
});
```

Add this test:
```php
public function testCookies()
{
    $value = $this->withCookies(['foo' => 'bar'])
        ->get('/')
        ->json();
    $jsonValue = $this->withCookies(['foo' => 'bar'])
        ->getJson('/')
        ->json();

    $this->assertEquals($value, $jsonValue);
}
```

This test will fail: `$value` is `'bar'` but `$jsonValue` is `[]`

-----

Looks like this is because [`json()`](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L427) doesn't call `$this->prepareCookiesForRequest()` like the non-JSON methods (`get()`, `post()`, etc.). I'm happy to add this in a PR, unless there's a reason not to add this?

**Comment by driesvints** [comment]
That's because you usually don't use cookies to make requests to JSON endpoints.

**Comment by Zakini** [comment]
But it does happen. Case in point: Laravel Sanctum SPA auth.

If nothing else, shouldn't this be mentioned in the docs somewhere?
