### ISSUE TITLE
Mailable::mailer not used when sending

### ISSUE THREAD

**Issue by BnitoBzh** [laravel/framework#32979]
- Laravel Version: 7.12.0
- PHP Version: 7.3.18
- Database Driver & Version: pgsql

### Description:
Mailable has a mailer property that represents the mailer that should send the message.
But it is not used to send the message.

### Steps To Reproduce:
Prerequisite : Configure 2 mailers (smtp / mailgun) with smtp as default.

Create a simple basic TestMail class that extends the Mailable class.
```php
<?php
namespace App\Mail;
use Illuminate\Mail\Mailable;
class TestMail extends Mailable
{
    public function __construct()
    {
        $this->mailer = 'mailgun';
    }

    public function build()
    {
        // The test-mail.blade.php file simple contains 'hello world'
        return $this->text('mails.test-mail');
    }
}
```
Try to send the TestMail with the Mail facade
```php
Mail::to('email@eample.com')->send(new TestMail);
```

The TestMail is sent with the smtp mailer instead of the mailgun.

Trying to configure the mailer inside the build method has no effect.
```php
    // ...
    public function build()
    {
        // The test-mail.blade.php file simple contains 'hello world'
        return $this->mailer('mailgun')->text('mails.test-mail');
    }
```

If we specify the mailer from the Facade the mailgun mailer is used.
```php
Mail::mailer('mailgun')->to('email@eample.com')->send(new TestMail);
```

**Comment by koenhoeijmakers** [comment]
Seems that the given `mailer` property is only used when no `mailer` has been selected as it only uses this property when the `Factory` is passed instead of a `Mailer`.

**Comment by BnitoBzh** [comment]
Ok, so how to transform this basic usage to make sure the `TestMail` mailer will be used correctly?
```php
Mail::to('email@eample.com')->send(new TestMail);
```

**Comment by paul-thebaud** [comment]
Hi!
I think the `mailer` property should be used and override default mailer.
This way, it will work as same as the `connection` property on Eloquent Models, or the `queue` property on Jobs.

**Comment by BnitoBzh** [comment]
The `Mail` facade always returns the default mailer `Mail::to(...)->send(...)` if no mailer is specified `Mail::mailer(...)->to(...)->send(...)`.

The `Mail` facade (which returns the mail.manager) has no method for using the mailer property of the sent mail (`TestMail`).

**Comment by taylorotwell** [comment]
I'm not sure we ever document this behavior or ability.

**Comment by vesper8** [comment]
Wait I'm confused, why was this closed? What's the conclusion?

The docs mention that you can specify the mailer using the Mail facade: https://laravel.com/docs/7.x/mail#sending-mail

```
use Illuminate\Support\Facades\Mail;

...

Sending Mail Via A Specific Mailer
By default, Laravel will use the mailer configured as the default mailer in your mail configuration file. However, you may use the mailer method to send a message using a specific mailer configuration:

Mail::mailer('postmark')
        ->to($request->user())
        ->send(new OrderShipped($order));
```

I am trying to do exactly this, I want certain mailables to be sent using the `sendmail` mailer and it is ignoring what I pass to the mailer, even if I pass an invalid mailer, no matter what I do it always uses the default mailer.

How can we use different mailers for different mailables then?

**Comment by driesvints** [comment]
@vesper8 This indeed doesn't work. Re-opening.

**Comment by BnitoBzh** [comment]
@vesper8 In my tests, when i use the `mailer()` method from the `Mail` facade it works.
```php
// with smtp as default driver
Mail::mailer('mailgun')->to('email@example.com')->send(new TestMail);
// TestMail is send with mailgun
```
It is only when the `mailer` is configured directly on my `TestMail` class (in the constructor, or in the `build` method) that it does'nt work (AND without `mailer()` method usage from the `Mail` facade)

After `Illuminate\Mail\Mailer` class inspection, the `mailer` property from the `Mailable` is always overriden during the send process by the `Mailer` name itself.

```php
     /**
     * Send the given mailable.
     *
     * @param  \Illuminate\Contracts\Mail\Mailable  $mailable
     * @return mixed
     */
    protected function sendMailable(MailableContract $mailable)
    {
        return $mailable instanceof ShouldQueue
                        ? $mailable->mailer($this->name)->queue($this->queue)
                        : $mailable->mailer($this->name)->send($this);
    }
```

I think that de send method used by the MailManager must not be a simple forward to the default mailer (or specified mailer) but a method that get the correct mailer first from the Mailable class concerned, or the specified mailer or finally the default mailer ...

For now, in my projects, All `Mail` facade call specify the mailer to use. But the best way would be to defined it directly on every `Mailable` classes. To note, at this point, Notifications (by email) aren't concerned by this. Because the Notification `MailMessage` class has a `mailer` that is correctly used when sending the mail notification.

**Comment by vesper8** [comment]
can we see your TestMail class ?

In my case I do not ever specify the mailer inside the mailable class and yet it isn't working and always uses the default mailer

I don't feel that it should be required to specify the mailer in the Mailable class as this removes the flexibility of specifying different mailers for the same Mailable in different scenarios.

Most importantly, I feel that when specifying a mailer on the Mail Facade it should always override and become the mailer that's used no matter what

**Comment by BnitoBzh** [comment]
@vesper8 in the initial message to this issue

**Comment by BnitoBzh** [comment]
@vesper8 Just in case, what's your laravel/framework version ?

**Comment by taylorotwell** [comment]
It was closed because this isn't documented as a way to use the mailer.

Also, how would we know what you intend to do. If you set a mailer in the constructor or the `build` method, then do `Mail::send(new Email)`... how do we know whether you intend to override the mailer with the default mailer or whether you want to use the one in the `build` method? That's why I think it only makes send to specify the mailer when actually sending the mail via the mail facade.

**Comment by vesper8** [comment]
Hrm.. I see now that I misread the initial post and am having a different problem, in my case I am not setting the mailer in the Mailable like OP is, I am trying to specify the mailer when using the Mail Facade like shown in the documentation, and that for some reason isn't working for me.. if that is working for all of you then there must be something else I am doing wrong, my bad

@BnitoBzh I'm on v7.10.3

**Comment by taylorotwell** [comment]
@vesper8 that situation is working for me.

**Comment by vesper8** [comment]
I found the culprit.. https://github.com/beyondcode/helo-laravel is causing the issue, as soon as I uninstalled the helper I was then able to specify the mailer using the facade. I guess they override one too many things in their service provider https://github.com/beyondcode/helo-laravel/blob/master/src/HeloLaravelServiceProvider.php which causes it to lose the flexibility. Will open an issue on their repo about it

**Comment by BnitoBzh** [comment]
@taylorotwell Ok for me, it could probably be a good idea to comment the mailer property on Mailable class to specify that it can't be used as a configuration property in constructor or build method ? Just for documentation.

**Comment by taylorotwell** [comment]
OK

**Comment by johannesnagl** [comment]
Still unclear to me why the `Mailable` class has a method tha can set the `mailer` if it's not working. I today run into the same issue as discussed here. 

Defining it on the Facade, it's working; defining it inside the Mailable's constructor, it's not working. 

Reason why this behavior would be super handy for me:
We currently switch on a user level which mailer we're using. So, passing down the `user` to the `Mailable` itself makes it easy to just call `$this->mailer($user->preferred_mailer)`

**Comment by johannesnagl** [comment]
I now found a way to do it:

Inside the mailable, just set the:

```php
if (XY) {
    $this->mailer($user->preferred_mailer);
}
```

And then, in the place, where the Facade is triggering the sending, do the following:

```php
$mail = new InviteMail($this->userId);
 Mail::mailer($mail->mailer ?? null)->send($mail);
```

With this check, you can make sure, that the proper mailer is properly set.

**Comment by ReDev1L** [comment]
```php
     /**
     * Send the given mailable.
     *
     * @param  \Illuminate\Contracts\Mail\Mailable  $mailable
     * @return mixed
     */
    protected function sendMailable(MailableContract $mailable)
    {
        $mailer = $mailable->mailer ?? $this->name;
        return $mailable instanceof ShouldQueue
                        ? $mailable->mailer($mailer)->queue($this->queue)
                        : $mailable->mailer($mailer)->send($this);
    }

```

@taylorotwell May Laravel team consider this change? nothing special here, but very handy

**Comment by ReDev1L** [comment]
Because my change was rejected - our team came to following solution:
We extend all our mailables from class with overriden method:
```php
<?php

use Illuminate\Mail\Mailable;
use Illuminate\Support\Facades\Mail;

class BaseMailable extends Mailable
{
    public function send($mailer = null): void
    {
        $mailer = $mailer ?? Mail::mailer($this->mailer);
        parent::send($mailer);
    }
}

```
For example our mailable looks like this:
```php
<?php

namespace App\Mail\Order;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class StoreOrderMail extends BaseMailable
{
    use Queueable, SerializesModels;
    
    public $mailer = 'maigun_b2c';

    /**
     * Create a new message instance.
     */
    public function __construct()
    {
    }
}

```
And to send emails with mailer set up in Mailable:
```php
        $mail = new StoreOrderMail();
        $mail->send();
```
To send it with mailer, not set in Mailable:
```php
        $mail = new StoreOrderMail();
        $mail->send(Mail::mailer('any-mailer'));
```
