### ISSUE TITLE
Model casts don't behave as expected.

### ISSUE THREAD

**Issue by Jannick94** [laravel/framework#32972]
- Laravel Version: 7.11 / 7.12
- PHP Version: 7.4.5

### Description:
In 7.11 a cast with the same name as a relation (in our case a BelongsToMany) would be ignored and the relation would be returned when calling $model->relation. However, since 7.12 the cast takes priority.

The cast doesn't behave as expected, we cast to an array but if the array is empty, the cast returns `null` instead of an empty array.

### Steps To Reproduce:
You need 2 models with a relation to the other on one of them:

```
// Paycheck.php
class Paycheck extends Model
{
    protected $casts = [
        'invoices' => 'array',
    ];

    public function invoices()
    {
        return $this->belongsToMany(Invoice::class);
    }
}
```

```
// Invoice.php
class Invoice extends Model
{
    //
}
```

```
dd($paycheck->invoices); // Collection in 7.11
dd($paycheck->invoices); // null in 7.12
```

**Comment by taylorotwell** [comment]
You should never have an attribute that has the same name as a relationship. Or a cast. I think it is just generally undocumented behavior in Laravel at this point.

**Comment by Jannick94** [comment]
> You should never have an attribute that has the same name as a relationship. Or a cast. I think it is just generally undocumented behavior in Laravel at this point.

Alright, but shouldn't the cast return an empty array instead of `null` then?

**Comment by taylorotwell** [comment]
I don't know really. It's undefined behavior to put a cast on a relationship in Laravel. So, I'm not sure whose to say what it "should" return.

**Comment by driesvints** [comment]
Think this could be a feature request maybe. Feel free to open up a discussion.

**Comment by Jannick94** [comment]
> I don't know really. It's undefined behavior to put a cast on a relationship in Laravel. So, I'm not sure whose to say what it "should" return.

Understood, so if I'm correct this behavior changed between 7.11 and 7.12, but it isn't a breaking change because it shouldn't be used this way in the first place?

**Comment by driesvints** [comment]
yep
