### ISSUE TITLE
RefreshDatabase trait only dropping tables for main connection

### ISSUE THREAD

**Issue by StevePorter92** [laravel/framework#32989]
- Laravel Version: 6|7
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
`\Illuminate\Foundation\Testing\RefreshDatabase` runs the `migrate:fresh` command which will only wipe tables on the main database connection.

If running migrations on specific connections other than the main one, the tables for these connections will not be dropped so test runs after the first one will error with:

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tests' already exists (SQL: create table `tests` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

Given the `RefreshDatabase` trait can perform transactions on multiple connections with the `connectionsToTransact` property, should it also `db:wipe` those connections too?

### Steps To Reproduce:
Fresh laravel project with steps to reproduce here https://github.com/StevePorter92/refresh-database-issue.

List of changed files: https://github.com/StevePorter92/refresh-database-issue/compare/0d7e05cf753336c22352d229a053b7c07251e0bc...master
```
git clone git@github.com:StevePorter92/refresh-database-issue.git
cd refresh-database-issue
composer install
docker-compose up -d
php artisan test
php artisan test
```

Notable files:
```php
...
# app/Test.php
...
class Test extends Model
{
    protected $connection = 'mysql2';
}
```

```php
...
# database/migrations/2020_05_27_150916_create_tests_table.php
...
class CreateTestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('mysql2')->create('tests', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });
    }
...
```

```php
...
# tests/feature/ExampleTest.php
...
class ExampleTest extends TestCase
{
    use \Illuminate\Foundation\Testing\RefreshDatabase;

    /**
     * Connections to transact
     *
     * @var array
     */
    protected $connectionsToTransact = ['mysql', 'mysql2'];
...
```

Happy to raise a PR for this if we think the trait should wipe all connections, or connections that it transacts on

**Comment by driesvints** [comment]
Sounds like a feature request. Moving this to discussions.
