### ISSUE TITLE
Slug helper removes slashes

### ISSUE THREAD

**Issue by chimit** [laravel/framework#32999]
- Laravel Version: 7.4.0
- PHP Version: 7.4

### Description:
The slug helper removes slashes instead of replacing them with a dash.

Comments from `Illuminate/Support/Str.php`:
```
// Remove all characters that are not the separator, letters, numbers, or whitespace.
...
// Replace all separator characters and whitespace by a single separator
```
I guess slash is a separator symbol, therefore it shouldn't be removed but replaced by a separator.

### Steps To Reproduce:
```
php artisan tinker
>>> Str::slug('Government/Academic')
=> "governmentacademic"
```

**Comment by driesvints** [comment]
Bit opinionated I guess. Moving to discussions. I doubt this will ever make it in because of the breaking change.
