### ISSUE TITLE
updateOrCreate method returning 'id' value of 0 for insert or update

### ISSUE THREAD

**Issue by kuhlaid** [laravel/framework#32994]
- Laravel Version: 7.13.0
- PHP Version: 7.3.9
- Database Driver & Version: SQL Server v14

### Description:
I am inserting/updating records into my `SurveyData` using the `updateOrCreate` method and the database records are being updated and inserted with no problem. However I was hoping to get back the complete object from the updateOrCreate method. The only problem is the 'id' field in the updateOrCreate returned object (`$surveyData` in the code below) is simply set to 0 (no matter if the object is being updated or inserted in the db).
```
public function update(Request $request) {
    $surveyData = SurveyData::updateOrCreate(
            [
                'id' => $request->id
            ],
            [
                'obj' => $request->obj,
                'created_at' => $request->created_at,
                'updated_at' => $request->updated_at
            ]
        );
}
```

### Steps To Reproduce:
If my request object looks like:
```
{
	"obj":"testing object 5",
	"id":"asfasdfasfddg"
}
```

`$surveyData` returns:
```
{
  "id": 0,
  "obj": "testing object 5",
  "created_at": "2020-05-28T00:23:54.687000Z",
  "updated_at": "2020-05-28T00:28:06.777000Z"
}
```
... instead of having `"id":"asfasdfasfddg"` in the object. Note that the `id` field is a string in the database NOT an int.

**Comment by AlexMalikov94** [comment]
Set `$incrementing` to false on your model.

```public $incrementing = false;

It checks if this is set to true, if it is, it will try to change the key field to int.

**Comment by kuhlaid** [comment]
How can I determine all of the properties a function inherits without drilling down through layers upon layers of inherited classes? Laravel is so abstracted that my IDE (VS Code plus lots of Laravel plugins) does not seem to know how to find all of the properties of the updateOrCreate function much less point me to the declaration of it without doing a global code search on 'updateOrCreate'. I checked the API docs and it does not allow searching on properties, so searching on property 'incrementing' using the online API search at [https://laravel.com/api/7.x/search.html?search=updateOrCreate](https://laravel.com/api/7.x/search.html?search=updateOrCreate) will turn up empty.
