### ISSUE TITLE
validate($request, []) method keeps refreshing

### ISSUE THREAD

**Issue by pazcalll** [laravel/framework#32996]
- Laravel Version: 7.13.0
- PHP Version: 7.3.1
- Database Driver & Version: Phpmyadmin 4.9.1 and 10.1.8-MariaDB

### Description:
every time I do a submit form with validate, the form is just refreshes the page and no more thing happens. when I delete the validation method or delete some validate method contents, it can go to the next page but doesn't pass any value.

### Steps To Reproduce:
1. Make a default login authentication by using _php artisan ui vue --auth_
2. Try to change login and register parameter from email into username.  Add or replace the required methods like what happens in youtube tutorials (any tutorial).
3. Once you register name, username, and password, the problem will appear.
4. Here the problem appears. the page doesn't send any information or giving any error message.
5. Try to remove the validate() method or remove some contents in it. It may gives you error message or maybe register success then to homepage, or maybe it keeps refreshing.
6. If you are done with the register page, then try to logout and re-login by using login page. In here the problem is getting insane because even the replaced method doesn't have any value, it keeps refreshing for every clicked login button

**sorry to say that I am still new in Laravel, but I followed so many tutorials to change the login and register parameter to become username and password and none of them give me any solution.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
