### ISSUE TITLE
Using a sliced collection with one item causes serialization to fail

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/framework#33006]
- Laravel Version: 6.18.13
- PHP Version: 7.4.*
- Database Driver & Version:

### Description:
When a collection is given with indexes the following will fail, in my case this happens because of a sliced collection with a single element: https://github.com/laravel/framework/commit/7b32469420258e9e52b24b2ffa7f491e79a3a870#diff-3f60c3ac71917b0e1e2977c956f6bcc0R569

```
return $relations[0];
```

```
Undefined offset: 0 at /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php:569
```

I guess it should make more sense to add an array_values here since all other case do work with when the index doesn't start at zero.

**Comment by GrahamCampbell** [comment]
Just needs to get piped thru `array_values` first, right?

**Comment by jeffreyzant** [comment]
Yea! I didn’t check if it touches the code elsewhere, but I can’t see any problems with the fix

**Comment by taylorotwell** [comment]
Fixed in next patch release.
