### ISSUE TITLE
Missing password_resets migration

### ISSUE THREAD

**Issue by netpok** [laravel/framework#33002]
- Laravel Version: 7.0.0+

### Description:
The password resets migration was moved to the ui package in commit https://github.com/laravel/laravel/commit/13e43893ba2457c3e49898f0066a5ce8d7ea74f4 from the boilerplate.

This migration was not part of the UI but the Auth/Passwords/DatabaseTokenRepository which is currently not usable without creating the table manually or installing the UI package. This causes problems with Nova when used standalone. The migration should either be moved back or provided by a command just like the `cache:table` command.

**Comment by driesvints** [comment]
Yeah, I've noticed that too. Think it's indeed best that it gets moved back to the skeleton.

Ping @taylorotwell

**Comment by taylorotwell** [comment]
Agree basically.

**Comment by taylorotwell** [comment]
Done.
