### ISSUE TITLE
Verified email dead end

### ISSUE THREAD

**Issue by eduardoarandah** [laravel/framework#33008]
- Laravel Version: 7.3
- PHP Version: 7.3
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64)

### Description:

When you use email verification, there's a dead end if the user typed the wrong email. 

Where do I go from here? 

![image](https://user-images.githubusercontent.com/4065733/83197578-4d2d2700-a103-11ea-9447-cbf735d3328b.png)

One solution is of course, register again.

But, this dead end is more problematic if you have a "my info" page and user types a wrong alternative email.
After changing user email & removing `email_verified_at` then the user is locked out forever. 

![image](https://user-images.githubusercontent.com/4065733/83197825-bc0a8000-a103-11ea-8568-63d1aa31cc35.png)

The simplest solution would be to let the user change his email in `/email/verify`
so this dead-end is removed 

![image](https://user-images.githubusercontent.com/4065733/83198094-2d4a3300-a104-11ea-9225-43ce446a60fb.png)

What do you think? 

### Steps To Reproduce:

Enable email verification 

https://laravel.com/docs/7.x/verification

**Comment by eduardoarandah** [comment]
# How to let the user modify his email and ask for confirmation in laravel

_^ This to help programmers looking for an answer_

## Step 1: Create a regular controller to let the user change his email/password

Use this template as example to change name, email and password

```
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class DashboardController extends Controller
{
...
    public function save(MyInfoRequest $request)
    {

        $user = Auth::user();
        $email = $request->input("email");
        $userChangedEmail = false;

        // if users changed email, force verify
        if ($email != $user->email) {
            $user->email = $request->input("email");
            $user->email_verified_at = null;
            $userChangedEmail = true;
        }

        // if password is received
        if ($user->password) {
            $user->password = Hash::make($request->input("password"));
        }

        // save name
        $user->name = $request->input("name");
        $user->save();

        // user changed email, so send notification
        if ($userChangedEmail) {
            $user->sendEmailVerificationNotification();
        }
    }
}

```

## Step 2: in verify.blade.php add email field

```
            <form class="d-inline" method="POST" action="{{ route('verification.resend') }}">
              @csrf

              <div class="mb-4 row">
                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                <div class="col-md-6">
                  <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email"
                    value="{{ old('email') ?? Auth::user()->email }}" required autocomplete="email">
                  @error('email')
                  <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                  </span>
                  @enderror
                </div>
              </div>

              <div class="text-center">
                <button type="submit"
                  class="btn btn-primary mb-3">{{ ucfirst(__('click here to request another')) }}</button>.
              </div>
            </form>

```

### Step 3: Your verification controller needs to let the user update password


In `app/Http/Controllers/Auth/VerificationController.php` add logic to change password

```
    /**
     * Resend the email verification notification.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function resend(Request $request)
    {

        // allow changing email
        $email = $request->input("email");
        $user = \Auth::user();

        if ($email && $email != $user->email) {
            $validator = Validator::make($request->all(), [
              'email' => ['string', 'email', 'max:255', 'unique:user'],
            ]);

            if ($validator->fails()) {
                return back()->withErrors($validator)->withInput();
            }
            $user->email = $request->input("email");
            $user->save();
        }

        if ($request->user()->hasVerifiedEmail()) {
            return $request->wantsJson()
                        ? new Response('', 204)
                        : redirect($this->redirectPath());
        }

        $request->user()->sendEmailVerificationNotification();

        return $request->wantsJson()
                    ? new Response('', 202)
                    : back()->with('resent', true);
    }

```

## Add verify to your Auth routes

`Auth::routes(['verify' => true]);`

Also, change `auth` to `verified` in your route middlewares, example:


```
Route::group(
    [
    'middleware' => ['web', 'verified'],
    ],
    function () {
         ....
        Route::resource('example', 'ExampleController');
    }
);

```

Read more: [https://laravel.com/docs/7.x/verification#introduction](https://laravel.com/docs/7.x/verification#introduction)

**Comment by devcircus** [comment]
IMO if we use email verification, we shouldn't build in a way to allow users to change their email address before they are verified. If a user registers with the wrong email, and email verification is mandatory, then they should have to re-register with the correct email. 

On the developer side, you should clear unverified accounts from your db on a regular basis. 

For the situation you mentioned, dead-end, you could add a note to that screen with a link to the registration page, in case a user entered the wrong address. You could even change the message to include the email address that they used, so they know if they entered the wrong one. 

Otherwise, you could implement this yourself. I don't think it should be the default or even optional behavior out-of-the-box.
