### ISSUE TITLE
Custom polymorphic intermediate table models updates records incorrectly

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#33007]
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 8.0.20

### Description:
Laravel framework incorrectly updates records in the db when using many-to-many pivot model for the relation.

**Issue:** if the polymorphic table has two records with same `item_id` but with different `item_type`, then calling `updateExistingPivot` method for the specific relation will ignore `item_type` and will update all records with the specified `item_id`.

**Custom polymorphic many-to-many pivot model**:
```
<?php

namespace App\Models\Warehouse;

use App\Traits\Models\MoneyFieldsTrait;
use Illuminate\Database\Eloquent\Relations\MorphPivot;

class InventoryItemPivot extends MorphPivot
{
    use MoneyFieldsTrait;
}
```

**Relation in the model**:
```
public function dishes(): MorphToMany
{
    return $this->morphedByMany(Dish::class, 'item', 'sale_items')
        ->using(InventoryItemPivot::class);
}
```

And code which update existing pivot incorrectly:
```
$model->dishes()->updateExistingPivot($id, $attributes);
```

### Steps To Reproduce:
1. `updateExistingPivot` method which use custom polymorphic many-to-many pivot model call `updateExistingPivotUsingCustomClass`:
https://github.com/laravel/framework/blob/dce44297bf1c8bbbfe39d467d4ca5e04f45d78d9/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L191
2. then code calls `getCurrentlyAttachedPivots` and I think in this method we are loosing `morphType` and `morphClass` for pivot and calling only `setPivotKeys` but should call `->setMorphType($this->morphType)` and `->setMorphClass($this->morphClass)`:
https://github.com/laravel/framework/blob/dce44297bf1c8bbbfe39d467d4ca5e04f45d78d9/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L482

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by roman-veryovkin** [comment]
@taylorotwell could you please release this patch as soon as possible? I'm experiencing this problem in production...
