### ISSUE TITLE
after_or_equal returns wrong code

### ISSUE THREAD

**Issue by Fr3di** [laravel/framework#33005]
- Laravel Version: 7.13.0
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
I have a route to the controller method with specific request. Inside the request I am validating the date format like this:
`'date' => 'required|date_format:Y-m-d|after_or_equal:today'`
when I send in Postman the date which is today or later everything is fine and code 200 is returned. When I send the date before today api sends also 200 code but it never hits the method code (tried to check with dd) but returns the home page of the api. 

### Steps To Reproduce:
- Create api route,
- create controller and method with custom request
- set authorize() return value to true
- set rule() return value to ['date' => 'required|date_format:y-m-d|after_or_equal:today']
- send request to the api (i.e. using Postman) with date before today and after

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
