### ISSUE TITLE
Reset Password Email: Default template contains stray HTML close tags.

### ISSUE THREAD

**Issue by ryanrapini** [laravel/framework#33009]
![email error](https://user-images.githubusercontent.com/286087/83207138-760fe500-a120-11ea-870c-608802d18363.png)

- Laravel Version: ^6.18
- PHP Version: ^7.2

See above image. Sending the default Laravel "Reset Password" email seems to generate this output

**Comment by taylorotwell** [comment]
You may need to de-indent some of your templates if you have published them.
