### ISSUE TITLE
Missing translation key pagination.goto_page in Tailwind pagination view

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#33015]
- Laravel Version: 7.12.0
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
The new Tailwind pagination view uses a [`__('pagination.goto_page')` translation key](https://github.com/laravel/framework/blob/2279b73d5553c34c970128264a248f3bb57afad6/src/Illuminate/Pagination/resources/views/tailwind.blade.php#L74) that isn't present in the [default language file](https://github.com/laravel/laravel/blob/master/resources/lang/en/pagination.php).

None of the other pagination views use this translation key.

**Comment by driesvints** [comment]
Just send in a PR.

**Comment by SjorsO** [comment]
Because it is only used in one of the 7 views, should it be removed, or also added to the other 6?

**Comment by driesvints** [comment]
Added to the other ones as well I think.

**Comment by SjorsO** [comment]
Maybe you can re-open this issue so someone can make a PR for that?

**Comment by driesvints** [comment]
Sure.
