### ISSUE TITLE
Bad domains not being handled in registration flow when email verification is required

### ISSUE THREAD

**Issue by codaru** [laravel/framework#33018]
- Laravel Version: 6.18.16
- PHP Version: 7.3.8
- Database Driver & Version: n/a
- Mail Driver: mailgun
- Previously closed issue, with no resolution: https://github.com/laravel/framework/issues/26246

### Description:
When a user signs up with an email and enters a domain that is invalid, an error is thrown by Mailgun when the verification emails are to be sent, see below

> Client error: `POST https://api.mailgun.net/v3/...removed.../messages.mime` resulted in a `400 BAD REQUEST` response: { "message": "'to' parameter is not a valid address. please check documentation" }

This stops the app dead in its tracks.

### Steps To Reproduce:
1. Enter an email with a domain that does not exist (for example: email@domainabcujwu123123.com)
2. User record is created and the email and password can be used, but
3. Verification email flow is kicked off and throws error above

**Comment by derekmd** [comment]
Since that previous issue thread, Laravel added new email validation options: https://laravel.com/docs/7.x/validation#rule-email

Applications can update `RegisterController@validator()` to:

```php
'email' => ['required', 'string', 'email:rfc,dns', 'max:255', 'unique:users'],
```

Invalid domains will cause the form submission to fail before saving to the database and making a Mailgun request.

**Comment by codaru** [comment]
> Since that previous issue thread, Laravel added new email validation options: https://laravel.com/docs/7.x/validation#rule-email
> 
> Applications can update `RegisterController@validator()` to:
> 
> ```
> 'email' => ['required', 'string', 'email:rfc,dns', 'max:255', 'unique:users'],
> ```
> 
> Invalid domains will cause the form submission to fail before saving to the database and making a Mailgun request.

Thanks! Have been holding off on upgrading but glad to know that there are additional validation rules to cover that case.

**Comment by atisedighi** [comment]
> Since that previous issue thread, Laravel added new email validation options: https://laravel.com/docs/7.x/validation#rule-email
> 
> Applications can update `RegisterController@validator()` to:
> 
> ```
> 'email' => ['required', 'string', 'email:rfc,dns', 'max:255', 'unique:users'],
> ```
> 
> Invalid domains will cause the form submission to fail before saving to the database and making a Mailgun request


You are awesome

> Since that previous issue thread, Laravel added new email validation options: https://laravel.com/docs/7.x/validation#rule-email
> 
> Applications can update `RegisterController@validator()` to:
> 
> ```
> 'email' => ['required', 'string', 'email:rfc,dns', 'max:255', 'unique:users'],
> ```
> 
> Invalid domains will cause the form submission to fail before saving to the database and making a Mailgun request.

You are awesome, your comment fixed my problem, thanks :)
