### ISSUE TITLE
Missing hint of Http Facade methods

### ISSUE THREAD

**Issue by memochou1993** [laravel/framework#33027]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:

Missing hint of Http Facade methods: `fake()` and `response()`.

### Steps To Reproduce:

<img width="631" alt="截圖 2020-05-30 下午10 58 10" src="https://user-images.githubusercontent.com/38420282/83331452-199bf980-a2c9-11ea-887c-ec6db88fa630.png">

**Comment by taylorotwell** [comment]
Feel free to PR them.
