### ISSUE TITLE
Validation rule "unique" ignores "connection" model field and always use default database connection

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [laravel/framework#33029]
- Laravel Version: 7.13.0
- PHP Version: 7.4.5
- Database Driver & Version:
MySQL 8.0.20
### Description:
If you use validation rule like "unique:users" and your `User` model contains custom `$connection` field, you always get error like `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'migrations_database.users' doesn't exist` where `migrations_database` - default connection database.

Maybe `unique` validation rule ignores `$table` field too, but I am not sure.

### Steps To Reproduce:
Create a different from default connection name for model and use `unique` validation rule with this model.

**Comment by voyula** [comment]
Laravel Rule only using query builder. **Not uses MODEL**.
You can specify a connection;

"unique:database.users"

**Comment by voyula** [comment]
https://stackoverflow.com/questions/32728346/laravel-validation-unique-exists-with-different-database-connection

**Comment by CaliforniaMountainSnake** [comment]
@voyula, ok, thank you, you are absolutely right.
