### ISSUE TITLE
Queue name of Queued Event Listeners cannot be set/overwritten.

### ISSUE THREAD

**Issue by lupinitylabs** [laravel/framework#33026]
- Laravel Version: 7.11.0
- PHP Version: 7.4.4
- Database Driver & Version: mySQL 8.0

### Description:

In Queued Event Listeners, it is not possible to set the queue name programatically, e.g. by setting it in the constructor. If set up like described in https://laravel.com/docs/7.x/events#queued-event-listeners, overriding the `$queue` attribute within the `Listener`, it is possible to hardcode the queue name within the class, but not to change it, e.g. to set it from a config value when the `Listener` is constructed.

A pull request with a possible solution was submitted at https://github.com/laravel/framework/pull/32770 but closed by Taylor suggesting to overwrite the queue name in the constructor, which, as described, does not work.

By the way, this works fine when dispatching Jobs, because the root of the problem exists in `Illuminate\Events\Dispatcher` during creation of the listener and job objects, and not in the Bus Dispatcher. 

### Steps To Reproduce:

A freshly installed Laravel project demonstrating the behavior is available at https://github.com/lupinitylabs/queuename. Its README.md also holds additional information on the nature of the problem.

You can reproduce this on your own by following these steps:

1. Create an Event
2. Create a Queued Event Listener as described in the docs linked above, implementing ShouldQueue, and adding a constructor to set the queue name. Use the InteractsWithQueue trait to be able to access the job object that has been queued to execute the listener and dd() the job object on handle() like this:

```
<?php

namespace App\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class QueuesOnSomeQueue implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * @var string
     */
    public $queue = 'initial-queue';

    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        $this->queue = 'destination-queue';
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle($event)
    {
        dd($this->job);
    }
}
```

3. Wire the Listener to the Event using `EventServiceProvider`'s $listen attribute:
```
    protected $listen = [
        SomeEvent::class => [
            QueuesOnSomeQueue::class,
        ],
    ];
```
4. Fire the event somewhere, e.g. in the home route or on tinker like `event(new SomeEvent())`
5. The output of the dd() will show the `SyncJob` instance with the queue attribute still set to `initial-queue` instead of the expected `destination-queue`.

**Comment by taylorotwell** [comment]
I see. I have reopened the PR.
