### ISSUE TITLE
The "route:list" command displays/output all attached Middleware.

### ISSUE THREAD

**Issue by TiBianMod** [laravel/framework#33041]
- Laravel Version: 7.13.0
- Laravel Sanctum: 2.3.3
- PHP Version: 7.4.6

### Description:
This issue/behavior is introduced on `Laravel Version 7.13.0` and specific on commit (https://github.com/laravel/framework/commit/7ebd21193df520d78269d7abd740537a2fae889e).
The "route:list" command will output all the attached Middleware per route after installing `Laravel Sanctum`.

### Steps To Reproduce:

```
laravel new app
```

> List all routes

```
php artisan route:list
```
<img width="652" alt="Screenshot 2020-05-31 at 18 52 49" src="https://user-images.githubusercontent.com/6713842/83358178-0c871500-a372-11ea-91a6-bb8b14db167b.png">

> ### All Good and Nice :)

> Now lets install `Laravel Sanctum`

```
composer require laravel/sanctum
```

> List all the routes again

```
php artisan route:list
```
<img width="1916" alt="Screenshot 2020-05-31 at 18 54 17" src="https://user-images.githubusercontent.com/6713842/83358295-d4cc9d00-a372-11ea-9814-a34be303134d.png">

### Related commit (https://github.com/laravel/framework/commit/7ebd21193df520d78269d7abd740537a2fae889e)

**Comment by kiddtang** [comment]
i am not using `laravel/sanctum`, but it happen after the `composer update`

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 23 updates, 0 removals
  - Updating doctrine/cache (1.10.0 => 1.10.1): Loading from cache
  - Updating doctrine/inflector (2.0.1 => 2.0.2): Loading from cache
  - Updating doctrine/lexer (1.2.0 => 1.2.1): Loading from cache
  - Updating guzzlehttp/guzzle (6.5.3 => 6.5.4): Loading from cache
  - Updating voku/portable-ascii (1.4.10 => 1.5.1): Loading from cache
  - Updating vlucas/phpdotenv (v4.1.5 => v4.1.6): Loading from cache
  - Updating symfony/event-dispatcher-contracts (v2.0.1 => v2.1.2): Loading from cache
  - Updating symfony/service-contracts (v2.0.1 => v2.1.2): Loading from cache
  - Updating opis/closure (3.5.1 => 3.5.3): Loading from cache
  - Updating symfony/translation-contracts (v2.0.1 => v2.1.2): Loading from cache
  - Updating nesbot/carbon (2.34.0 => 2.35.0): Loading from cache
  - Updating monolog/monolog (2.0.2 => 2.1.0): Loading from cache
  - Updating league/flysystem (1.0.68 => 1.0.69): Loading from cache
  - Updating laravel/framework (v7.11.0 => v7.13.0): Loading from cache
  - Updating cakephp/chronos (2.0.4 => 2.0.5): Loading from cache
  - Updating laravel/horizon (v4.3.2 => v4.3.3): Loading from cache
  - Updating spatie/laravel-permission (3.11.0 => 3.13.0): Loading from cache
  - Updating backpack/crud (4.1.4 => 4.1.6): Loading from cache
  - Updating backpack/generators (v3.0.1 => v3.1.0): Loading from cache
  - Updating facade/ignition (2.0.2 => 2.0.5): Loading from cache
  - Updating laravel/telescope (v3.4.0 => v3.5.0): Loading from cache
  - Updating mockery/mockery (1.3.1 => 1.4.0): Loading from cache
  - Updating phpunit/phpunit (8.5.4 => 8.5.5): Loading from cache
```
i am not sure which packages contributing to this issue, just giving my output for whoever looking in this issue...
the middleware list become looooong expanded list...

**Comment by n1crack** [comment]
I have the same problem..

**Comment by driesvints** [comment]
This is fixed with https://github.com/laravel/framework/pull/32993 which will be in the next patch release.

**Comment by JoshuaDoshua** [comment]
@TiBianMod  @plai2010 
do you have `barryvdh/laravel-debugbar` installed? removing that fixed it for me. Related issue:
https://github.com/barryvdh/laravel-debugbar/issues/1046

**Comment by plai2010** [comment]
Thanks @JoshuaDoshua for sharing your experience. I didn't install barryvdh/laravel-debugbar however; I cannot find it in my composer.lock or vendor either.

You have Sanctum installed, and removing DebugBar helps? Just trying to nail down the scenario.

**Comment by TiBianMod** [comment]
Hi @JoshuaDoshua, I don't use `barryvdh/laravel-debugbar`, but like I explained before, you can reproduce this issue by installing `Laravel Sanctum `after creating a new `Laravel` app and you will see the route:list what outputs.

**Comment by quangvision** [comment]
> Hi @JoshuaDoshua, I don't use `barryvdh/laravel-debugbar`, but like I explained before, you can reproduce this issue by installing `Laravel Sanctum `after creating a new `Laravel` app and you will see the route:list what outputs.

Yes, I agree with you. By installing laravel/sanctum, route:list comes with all route middlewares expanded. That is really annoying :)

**Comment by plai2010** [comment]
I actually don't think #32993 is the same issue as this; I would like to see this issue re-opened.

**Comment by leo95batista** [comment]
any update on this issue?

**Comment by driesvints** [comment]
Outputting all the middleware is intended.

**Comment by leo95batista** [comment]
I think it would be ideal to leave the format as it was before, and if you really want to show the current format, then do it through an optional parameter in the command. Like ```php artisan route:list --expand-middleware```

**Comment by driesvints** [comment]
Kind of inclined to agree with you there @leo95batista. You could always attempt a PR to see if Taylor would approve it.

**Comment by plai2010** [comment]
> Outputting all the middleware is intended.

I noticed something to that effect in the check-in history of some code when I was looking into it. I was puzzled however that Laravel without Sanctum did not expand the middleware classes.

Either way, the behavior seems inconsistent.

**Comment by leo95batista** [comment]
I have created a [pull request](https://github.com/laravel/framework/pull/33843#issue-466878587) to solve this problem, I hope it will be accepted

**Comment by leo95batista** [comment]
I have created a [pull request](https://github.com/laravel/framework/pull/33843#issue-466878587) to solve this problem, I hope it will be accepted

**Comment by leo95batista** [comment]
I have created a [pull request](https://github.com/laravel/framework/pull/33843#issue-466878587) to solve this problem, I hope it will be accepted

**Comment by leo95batista** [comment]
I have created a [pull request](https://github.com/laravel/framework/pull/33843#issue-466878587) to solve this problem, I hope it will be accepted

**Comment by leo95batista** [comment]
My pull request was rejected, I just have to wait for someone to give a solution...

**Comment by marouane-souadi** [comment]
having the same proble, it was solved after removing  barryvdh/laravel-debugbar

**Comment by kenxu5500** [comment]
having the same problem. but you can filter the column with flag. `php artisan route:list -c`

**Comment by zmorris** [comment]
I don't know how the maintainers managed to mess this one up!

@kenxu5500 gave the [cleanest solution](https://github.com/laravel/framework/issues/33041#issuecomment-737778918), but here's a cross-platform one-liner if you need to see all of the columns:
```shell
php artisan route:list | perl -pe 's/\x1b\[[0-9;]*[mG]//g' | perl -0777 -pe 's/ +\|(\r\n?|\n)/\n/g' | perl -0777 -pe 's/(\r\n?|\n)(\| +){6}/, /g'
```

to break it down:
```shell
php artisan route:list | \
perl -pe 's/\x1b\[[0-9;]*[mG]//g' | \  # strip control characters: https://superuser.com/a/561105
perl -0pe 's/ +\|(\r\n?|\n)/\n/g' | \  # strip trailing whitespace and pipe character, substituting newline with \0 during processing via -0
perl -0pe 's/(\r\n?|\n)(\| +){6}/, /g' # strip leading pipes and whitespace before middleware column, substituting newline with \0 during processing via -0
```

Remember to change the `{6}` portion if you change the number of columns with the `--columns[=COLUMNS]` option, see `php artisan route:list -h`.

I haven't tested it on Windows yet, but my understanding is that `perl` will match any line ending with `(\r\n?|\n)` and then substitute the platform-specific line ending when the `\n` replacement is written to the output stream.

I messed around with `sed` and a few other methods, but unfortunately there is no cross-platform multiline search and replace regex command that isn't burdened with quirks. So I've decided to always use `perl` moving forward since it's available in most environments.

A better method might be to use `php artisan route:list --json | jq` but I haven't figured out the magic incantation to output a table yet.

https://stedolan.github.io/jq/

Other workarounds:
https://stackoverflow.com/questions/62244648/laravel-route-list-php-artisan-routelist-displaying-middleware-on-new-lines
