### ISSUE TITLE
New project (L7) - session.php secure option not up to date

### ISSUE THREAD

**Issue by Sartoric** [laravel/framework#33052]
- Laravel Version: 7.13.0
- PHP Version: 7.2.8
- Database Driver & Version:

### Description:
The file session.php of a new project, created via composer, is not up to date based on migration guide 

>Next, please update your session configuration file's secure option to have a fallback value of null:
>'secure' => env('SESSION_SECURE_COOKIE', null),

the secure option is still set as
`'secure' => env('SESSION_SECURE_COOKIE'),`

### Steps To Reproduce:
- Create a new project via composer
`composer create-project --prefer-dist laravel/laravel NEW`
- check the config/session.php file

**Comment by voyula** [comment]
Yes, I also noticed.

**Comment by driesvints** [comment]
This is only when you're upgrading from 6.x where it was set to false: https://github.com/laravel/laravel/blob/6.x/config/session.php#L169

`null` is the default fallback.
