### ISSUE TITLE
withoutOverlapping() not working properly

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [laravel/framework#33051]
- Laravel Version: 6.x
- PHP Version: 7.2
### Description:
So in my `Commands/Kernel.php` i have the following code which is suppoused to emulate a supervisor for `queue:work`:
```
$schedule->command('queue:restart')->everyFiveMinutes();
$schedule->command('queue:work')->name('queue_work_name')->withoutOverlapping()->everyMinute()->runInBackground();
```
I've already cleared every tipe of cache, however in my process list using `ps aux | grep "php artisan"` I see this:
```
marcober 20527  0.0  0.0 376636 30956 ?        S    15:52   0:00 /opt/alt/php72/usr/bin/php artisan queue:work
marcober 22397  0.1  0.0 376636 30952 ?        S    15:53   0:00 /opt/alt/php72/usr/bin/php artisan queue:work
marcober 24157  0.1  0.0 376636 30956 ?        S    15:54   0:00 /opt/alt/php72/usr/bin/php artisan queue:work
marcober 29198  0.7  0.0 376636 30956 ?        S    15:56   0:00 /opt/alt/php72/usr/bin/php artisan queue:work
```
Why are they running together if i have `->withoutOverlapping()`?
PS: my only cron job is the one that you can find on the documentation 

### Steps To Reproduce:
add this to the Kernel:
```
$schedule->command('queue:restart')->everyFiveMinutes();
$schedule->command('queue:work')->name('queue_work_name')->withoutOverlapping()->everyMinute()->runInBackground();
```
and this cron job:
```
*  *  *  *  *  path/to/my/project && php artisan schedule:run >> /dev/null 2>&1
```

**Comment by vladislavtkachenko** [comment]
You need to delete "everyMinute" method.

**Comment by AlbertoSinigaglia** [comment]
> You need to delete "everyMinute" method.

I've already tried, but nothing has changed, I still see a lot of instances of `queue:work` running together

**Comment by driesvints** [comment]
Moving to discussions.
