### ISSUE TITLE
Custom casts are behaving like singletons

### ISSUE THREAD

**Issue by netpok** [laravel/framework#33057]
- Laravel Version: 7.13.0
- PHP Version: 7.4

### Description:
Custom casts on a model are behaving like singletons.

If I have a custom castable field on a model and I'm accessing twice it returns same object which can lead the second time the object is actually not representing the model state. 

### Steps To Reproduce:
Attached example test implemented with Carbon:
https://github.com/netpok/laravel-singleton-cast/blob/master/tests/Unit/ExampleTest.php

**Comment by driesvints** [comment]
This is because Carbon is mutable. Try:

```php
use Carbon\CarbonImmutable;

class UnsavedModel extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'not_singleton' => DontSingleton::class,
    ];
}

class DontSingleton implements \Illuminate\Contracts\Database\Eloquent\CastsAttributes
{
    public function get($model, string $key, $value, array $attributes)
    {
        return CarbonImmutable::parse($value);
    }

    public function set($model, string $key, $value, array $attributes)
    {
        return (string) $value;
    }
}
```

**Comment by netpok** [comment]
@driesvints Yes, that's my exact problem, it behaves differently from the internal casts, I updated my test example with other instances.

If this is the expected behavior there should be a warning about it in the documentation.

**Comment by driesvints** [comment]
I don't see your update. Can you maybe just share the code here?

**Comment by netpok** [comment]
Sorry I forgot to push it, now it's up now.

Also if the current behavior is the expected one maybe the internal casts should be updated to match the new behavior.

**Comment by driesvints** [comment]
I'll reopen this for @taylorotwell to have a look at.

**Comment by netpok** [comment]
Thanks, an example where this could be a problem:
- In a controller an event is fired `CustomEvent::dispatch($model->custom_casted_attribute)` and later the model is saved.
- Everything works, but later a new listener is added, where the object is changed.
- Now the original controller will update the db record with the modified value.

**Comment by taylorotwell** [comment]
That's how custom casts are intentionally designed to work. Otherwise very basic operations would not be possible, such as:

$customer->address->lineOne = 'foo';
$customer->address->lineTwo = 'bar';

**Comment by netpok** [comment]
@taylorotwell @driesvints Then shouldn't the internal casts like `collection` or `datetime` exhibit the same behavior?

I mean
```php
$order->payment_due_date->addDay();
$order->attributes['color'] = 'green'; // attribute is a collection
```
would be great to have too.
