### ISSUE TITLE
Callbacks used for faked HTTP client responses are always called

### ISSUE THREAD

**Issue by Zakini** [laravel/framework#33068]
- Laravel Version: 7.13.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7.29-0ubuntu0.18.04.1

### Description:
When passing an associative array to `Http::fake()`, any and all callbacks for the matching URL in that array are called, instead of only the first one.

### Steps To Reproduce:
```php
public function testCanMockHttp()
{
    Http::fake([
        '/foo' => function () {
            dump('here');
            return Http::response('foo');
        },
        '/bar' => function () {
            dump('not here');
            return Http::response('bar');
        },
        '*' => function () {
            dump('also here');
            return Http::response('fallback');
        }
    ]);

    $this->assertEquals(
        'foo',
        Http::baseUrl('http://example.com')->get('/foo')->body()
    );
}
```

This test passes, but both "here" and "also here" are dumped.

In my specific case, I was using something like this:
```php
Http::fake([
    '/foo' => Http::response('foo'),
    '*' => fn($request) => dd($request)
]);
```
to diagnose why a request wasn't matching one of the fakes.

I'm happy to put in a PR to fix this.

**Comment by taylorotwell** [comment]
Sure, feel free to send in a PR.
