### ISSUE TITLE
Can not perform multiple sync() on morphToMany relationship

### ISSUE THREAD

**Issue by besanek** [laravel/framework#33072]
- Laravel Version: 6.18.17
- PHP Version: 7.2.24
- Database Driver & Version: MariaDB 10.0

### Description:

Can not perform multiple sync() on single model instrance for morphToMany relationship. On second sync is thrown `BadMethodCallException : Call to undefined method Illuminate\Database\Eloquent\Relations\Pivot::setMorphType()`

The problem has occurred in the version 6.18.17. The version 6.18.16 works fine.

### Steps To Reproduce:

1) create model with `morphToMany` relationship
```php
    public function settings()
    {
        return $this->morphToMany(Setting::class, 'has_setting');
    }
```
2) Sync multiple times in one request
```php
$model = factory(Model::class)->create();
// Works
$model->tags()->sync([1]); 
// Throws BadMethodCallException : Call to undefined method Illuminate\Database\Eloquent\Relations\Pivot::setMorphType()
$model->tags()->sync([2]); 
```

**Comment by ralphschindler** [comment]
Can confirm this is an issue. This appears to be the commit that broke:

https://github.com/laravel/framework/commit/684208b10460b49fa34354cc42f33b9b7135814f#diff-3c8f4b63b093b84a3e3d4e862743dec0

When `$record` is an instance of `Illuminate\Database\Eloquent\Relations\Pivot`, `setMorphType` is not an available method.

**Comment by mic-oliveira** [comment]
I have the same problem, however in version 7.14. In version 7.13. * Did not present this problem.

**Comment by madpilot78** [comment]
Also experiencing this with 7.14.0, 7.13.0 works fine. Same commit to blame. as reported by @ralphschindler 

For me the bug is showing when using spatie laravel-permission. In a test I ssign roles in two separate calls and I get this error.

This line in spatie laravel-permission triggers the issue:

https://github.com/spatie/laravel-permission/blob/e25986c298b921e884a0a93a6f09f81c0c9cdb5a/src/Traits/HasRoles.php#L116

**Comment by adamthehutt** [comment]
Can confirm this issue in 7.14.

**Comment by taylorotwell** [comment]
Will release a patch.
