### ISSUE TITLE
Maximum Execution time exceeded!!!

### ISSUE THREAD

**Issue by Kuraj11101** [laravel/framework#33080]
- Laravel Version: 7.11
- PHP Version: ^7.3.17
- Database Driver & Version: MySQL 

### Description:
Have had issues with user registration using Laravel passport and Jwt Token. I always get maximum execution time exceeded. At first it was 30secs I later change it to 300secs in my PHP.ini file but I still do have the same issue. And it have been over a week now!!!!

### Steps To Reproduce:
Create login and registration controller, create MySQL data with the necessary env configurations. Php artisan make:Auth and try to register a user.

**Comment by mrcat323** [comment]
But in laravel 7 `artisan make:auth` doesn't exist ? how did you do it ?
Use [laravel/ui](https://github.com/laravel/ui) package, say `artisan ui bootstrap --auth` and try again. I tried, everything works fine
