### ISSUE TITLE
When syntax error occurs the output incorrectly points to the view file

### ISSUE THREAD

**Issue by challgren** [laravel/framework#33083]
- Laravel Version: 7.14.0
- PHP Version: 7.4
- Database Driver & Version: n/a

### Description:
When a syntax error occurs and is caught the error outputs the view instead of the file the syntax error occured

### Steps To Reproduce:
Create a controller with a syntax error and the output will point to the view as being the cause of the error. See attached screenshot

![FB_IMG_1591167127428](https://user-images.githubusercontent.com/88909/83605405-7869a900-a53d-11ea-9d96-8af9f7151b88.jpg)

Side note I'm not the original reporter of this error so I can't confirm the exact laravel version but discussion is at https://www.facebook.com/groups/447837565425043/permalink/1489126884629434/

**Comment by taylorotwell** [comment]
Works for me...

<img width="714" alt="image" src="https://user-images.githubusercontent.com/463230/83650750-4af11f80-a57e-11ea-8a68-a7ac0b2ee30c.png">
