### ISSUE TITLE
Commands are not re-initialised when called via Artisan::call()

### ISSUE THREAD

**Issue by CyrilMazur** [laravel/framework#33100]
- Laravel Version: 7.7.1
- PHP Version: 7.4
- Database Driver & Version:

### Description:

Take this example:

```php
Artisan::call('check-lang-file fr');
Artisan::call('check-lang-file en');
Artisan::call('check-lang-file de');
```

The same instance of the `CheckLangFile` command is used for the three calls, which means the object is not re-initialised in before each call.

### Steps To Reproduce:

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;

class Test extends Command
{
    protected $signature = 'test';

    protected $counter = 0;

    public function handle()
    {
        $this->counter++;

        $this->line($this->counter);

        // this example is stupid but it proves the point
    }
}
```

```php
Artisan::call('test'); // expect 1, see 1
Artisan::call('test'); // expect 1, see 2
Artisan::call('test'); // expect 1, see 3
```

**Comment by driesvints** [comment]
Commands are resolved using the dependency container. Because you're trying to execute the commands at runtime after each other, the container will return the already resolved command. This is expected. This won't happen in a CLI environment because the app is bootstrapped again for every separate execution.

**Comment by CyrilMazur** [comment]
This happens in a CLI environment also, when calling commands inside a command like so:

```php
$this->call('test'); // expect 1, see 1
$this->call('test'); // expect 1, see 2
$this->call('test'); // expect 1, see 3
```

This happens as long as you call the same command more than once.

If it's intended I can accept it, it should just be documented.

**Comment by driesvints** [comment]
@CyrilMazur That's not a CLI environment. That's runtime.

I'm talking about:

```bash
php artisan test
php artisan test
php artisan test
```

**Comment by driesvints** [comment]
We're accepting prs if you want.

**Comment by CyrilMazur** [comment]
I'm talking about:

```php
public function handle()
{
    $this->call('test');
    $this->call('test');
    $this->call('test');
}
```

Yes I'll try to write a PR, fix code or update doc.
