### ISSUE TITLE
When softDelete, getDirty is empty in deleted event

### ISSUE THREAD

**Issue by hulkur** [laravel/framework#33101]
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Database Driver & Version:

### Description:

When soft-deleting a model changes are not visible to deleted event handlers as syncOriginal is called before firing the event.

In real and forced delete DB record is deleted, syncOriginal is not needed and everything is ok.

In soft-delete:
- `Model::delete()` calls `$this->performDeleteOnModel()` (goes to `SoftDeletes` trait method)
   - `SoftDeletes::performDeleteOnModel` calls `runSoftDelete`
   - `SoftDeletes::runSoftDelete` updates DB record and calls `$this->syncOriginalAttributes`
- `Model::delete()` fires `deleted` event

Result is that in deleted event handlers model `getDirty()` is empty but it should contain at least `deleted_at` attribute.

## Proposal:

Make the order similar to update which soft-delete in reality is. (as in `Model::finishSave`)

Move `$this->fireModelEvent('deleted', false);` from `Model::delete` to the end of `Model::performDeleteOnModel` and add to `softDeletes::runSoftDelete` between update and syncOriginal

```
$query->update($columns);

$this->fireModelEvent('deleted', false);

$this->syncOriginalAttributes(array_keys($columns));
```

This way all the changes done in softDelete logic is visible to deleted event handlers.

**Note**: This creates BC breaks if someone has overwritten `performDeleteOnModel` or `runSoftDelete` in their app.

PR or not to PR ?

**Comment by taylorotwell** [comment]
I'm curious what the use case would be for dirty attributes in a soft delete operation? Aren't you just calling $foo->delete()? What is being updated?

**Comment by hulkur** [comment]
Yes, I call ->delete() and in runSoftDelete() I have more changes to the model (ex: deleted_by).
Then in deleted event handler change set is stored for auditing. This requires usage of getDirty().
