### ISSUE TITLE
Request IP is 127.0.0.1 when deployed on Vapor.

### ISSUE THREAD

**Issue by Abhi0725** [laravel/framework#33104]
- Laravel Version: 7.11.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.8

### Description:

Laravel request()->ip() is 127.0.0.1 when deployed via Vapor which causes the signature to be same for all not logged in users in ThrottleRequests middleware. Shouldn't we use `x-vapor-source-ip` header from [this pull request](https://github.com/laravel/vapor-core/pull/15)?
I have changed the method `resolveRequestSignature` in ThrottleRequests middleware  from:

`return sha1($route->getDomain().'|'.$request->ip());`

to this:

```
$ip = $request->header('x-vapor-source-ip') ?: $request->ip();
return sha1($route->getDomain().'|'.$ip);
```

Should I send a pull request? Or is this not a correct way to do?

**Comment by driesvints** [comment]
Probably best that you email vapor support.

**Comment by Abhi0725** [comment]
@driesvints and where to do that? I can't find it the support email anywhere in Laravel. Raised this issue 6 days ago and got it closed. Raised again here with solution and you closed it now. Isn't Vapor a product of Laravel?

Please tell me where I can raise vapor support request?

Also, Isn't the solution provided good as Laravel should have Vapor support out of the box?

**Comment by driesvints** [comment]
There's a support widget on the bottom right in Vapor.

**Comment by maurocasas** [comment]
Why is this not common knowledge? I'm facing the same issue, have tried both request()->ip() and using the header x-vapor-source-ip, both coming back 127.0.0.1

**Comment by lululombard** [comment]
This is still broken!

**Comment by swilla** [comment]
This is returning 127.0.0.1 because of [trusted proxies.](https://laravel.com/docs/8.x/requests#trusting-all-proxies)  You can set it to a wildcard, but I also found this package that creates a dynamic list of proxies for Vapor: 
https://github.com/ge-tracker/laravel-vapor-trusted-proxies
