### ISSUE TITLE
Container contextual binding infinite recursion

### ISSUE THREAD

**Issue by X-Coder264** [laravel/framework#33114]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: irrelevant

### Description:

Trying to resolve a service from the container with a contextually bound logger results in an infinite recursion while the `\Illuminate\Log\LogManager` service gets resolved  (the `$container->make('log')` method call).

### Steps To Reproduce:

Create a fresh Laravel project install, add the following code:

```php
<?php

namespace App\Services;

use Psr\Log\LoggerInterface;

class Foo
{
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    // some methods...
}
```

In a service provider (it doesn't matter if it is in the `register` or `boot` method):

```php
use App\Services\Foo;
use Illuminate\Contracts\Container\Container;
use Illuminate\Support\ServiceProvider;
use Psr\Log\LoggerInterface;

$this->app->when(Foo::class)->needs(LoggerInterface::class)->give(function (Container $container) {
    dump('the recursion happens here');
    return $container->make('log')->driver('single');
});
```

When the `Foo` service is resolved from the container (for example when it is typehinted in the controller constructor or method) an infinite recursion happens:

`Maximum function nesting level of '256' reached, aborting!`

On the other hand doing

```php
$this->app->bind(Foo::class, function (Container $container) {
    return new Foo($container->make('log')->driver('single'));
});
```

works as expected and I'm using it at the moment as a workaround.

It isn't really pretty when the `Foo` service has the logger dependency for example as the fifth argument in its constructor as that means that I've to write four calls to `$container->make()` which I wouldn't have to write if the contextual binding example worked.

**Comment by morloderex** [comment]
Hey @X-Coder264 
The message `Maximum function nesting level of '256' reached, aborting!` to my experiance usually comes when you have Xdebug enabled. 

As a work around try increasing the `xdebug.max_nesting_level` php ini setting to some bigger number or disable it entirely and report the result. 

If that does not help you only then would i consider this a bug.

**Comment by X-Coder264** [comment]
I do have Xdebug, but even without it the issue is still present.

**Comment by driesvints** [comment]
That indeed seems like a bug to me.

**Comment by taylorotwell** [comment]
I'm not sure of a good way to solve this really. You have to think about what the code is saying a bit... internally "LoggerInterface" is just an alias of the "log" container binding. So, when you say "when the Foo class needs "log", resolve "log"... that's recursive and I'm not sure there is any way around that really - not just for log but for any binding. It just doesn't make sense.

One way around is just remove the type hint from Foo.

**Comment by EdgarSedov** [comment]
> I don't think this is solvable. You have to think about what the code is saying a bit... internally "LoggerInterface" is just an alias of the "log" container binding. So, when you say "when the Foo class needs "log", resolve "log"... that's recursive and I'm not sure there is any way around that really - not just for log but for any binding. It just doesn't make sense.
> 
> One way around this is just remove the type hint from Foo. The other option would be to make the LoggerInterface not be an alias of `log`, but that would be a larger breaking change.
> 
> Another option might be a method on the container to remove aliases so that you can unregister that alias.

Can be solved with introduction of buildTarget\resolveFor parameter, which will prevent recursion for second resolving
