### ISSUE TITLE
ChoiceQuestion breaks console formatting

### ISSUE THREAD

**Issue by ethanclevenger91** [laravel/framework#33119]
- Laravel Version: 7.14.1
- PHP Version: 7.4.4
- Database Driver & Version: MySQL, MariaDB 10.whatever is in Homestead 9.5.1

Git/Git Bash 2.27.0
Win 10

### Description:
`$this->choice` within a console command breaks subsequent formatting in Git Bash on Windows.

### Steps To Reproduce:
This command:
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ChoiceTest extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'choice-test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->choice('Select', ['one', 'two']);
        $this->info('Hey there.');
    }
}
```

produces this:

![image](https://user-images.githubusercontent.com/2623646/83907383-2b8ef980-a71a-11ea-8c1d-a171a16a17d6.png)

[Here's another instance, unresolved.](https://stackoverflow.com/questions/58118864/git-bash-console-output-breaks-down-when-using-laravel-console-choice-method)

I have a feeling this could be a bug with the Symfony Console component, but wanted to check in here first.

**Comment by driesvints** [comment]
Since the choice method is just a convenience wrapper around Symfony's `ChoiceQuestion` class it's probably indeed best to open up an issue on their repo.
