### ISSUE TITLE
Overriding and extending a package view causes a loop

### ISSUE THREAD

**Issue by MrCrayon** [laravel/framework#33122]
- Laravel Version: v7.14.1
- PHP Version: 7.3.18
- Database Driver & Version:

### Description:
(It should affect any version)
Laravel comes with an easy way to override package views but there is no way to tell Laravel to force inclusion of original package view.
This can cause a loop when `@extends` is called in an overriding view.

### Steps To Reproduce:

1. Install package called `package` that has a view called `template`
2. Create a view as `resources/views/vendor/package/template.blade.php`
3. Content of view should be `@extends('package::template')`
4. View compiling enters a loop since `package::template` is resolved as `resources/views/vendor/package/template.blade.php`

### Why do we need this to work?
Right now when you want to override a package view you need to copy/publish file and change it, this causes problems of maintainability.
Even if views provide sections to easily override some parts that functionality is lost if you need to copy the whole file.

### How to fix this?
We should check if template resolved is the same calling for inclusion.
Unfortunately I didn't find a way to check this without using another syntax, I'll be opening a PR to solve this.

**Comment by taylorotwell** [comment]
This of course isn't possible. Extending the same view is recursive.

**Comment by MrCrayon** [comment]
@taylorotwell it's not about extending the same view that of course wouldn't make sense, it's about extending package view from app and overriding it. 

It's recursive only because there is currently no way in Laravel to say that you want to force package view, my PR fixes that.

I'm not sure if I didn't explain well enough the use case and utility or if there is a problem with my PR that I don't see.

Any explanation would be greatly appreciated, thanks!

**Comment by fsmeier** [comment]
So this was never merged I guess? - running exactly in that problem that i wanna customize one section of a package-view without copying all the other stuff which would be a maintainence hell.
