### ISSUE TITLE
Change of behavior with custom date casters

### ISSUE THREAD

**Issue by brianrlewis** [laravel/framework#33134]
- Laravel Version: 7.14.1
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7

### Description:

The recent `v7.14.0` release changed some behavior in my application in regards to a custom date casting class that I use. 

Commit 2d52abc is the reason for the change in behavior on my end.

This commit is in response to #32983

In my application I am using a custom date casting class instead of the native `$casts = [ 'datetime:n/j/Y g:i:s A' ]` feature in order to have the desired format set as the `toStringFormat` of the returned carbon object and also to convert the UTC date to the local timezone.

I submitted a pull #31923 regarding this awhile back but it was closed so I ended up going this route.

Here is what my date casting class looks like:

```
<?php
class CastTimestamp implements CastsAttributes
{
    public function get($model, $key, $value, $attributes)
    {
        if ($value) {
            $format = 'n/j/Y g:i:s A';

            return carbon($value)
                        ->settings([
                            'toStringFormat' => $format,
                            'toJsonFormat' => $format,
                        ])
                        ->local();
        } else {
            return null;
        }
    }

    public function set($model, $key, $value, $attributes)
    {
        return $value ? carbon($value)->toDateTimeString() : null;
    }
}
````

Before the 2d52abc commit, when the eloquent `toArray()` method is called any datetime attributes from my custom caster would be returned as a carbon object. Afterwards these objects could be serialized without issue and when that serialization takes place my desired datetime format will be used.

However now the date is serialized when `toArray()` is called and that serialization process disregards my desired datetime format.

I guess I don't fully understand what the problem was in #32983 that needed to be solved. Is it necessary that all dates be serialized to a string when `toArray()` is called or can date objects be returned as is like they were before? If the date objects are returned as is then other serialization methods (like `json_encode`) can easily convert the date objects to a string if necessary.

I'm completely open to doing things differently on my end if there is a better way to accomplish my goals.

**Comment by taylorotwell** [comment]
IMO, the Eloquent `serializeDate` method should be used to determine date format.
