### ISSUE TITLE
Middlewares are not run while throwing http exceptions

### ISSUE THREAD

**Issue by Mdhesari** [laravel/framework#33138]
- Laravel Version: 7.12.0
- PHP Version: 7.3.5
- Database Driver & Version: Mysql & 5.7.26

### Description:
My problem is for example a user calls an endpoint that is not recognizes as a result it will throw NotFoundHttpException, then when I want to access logged-in user because bunch of related middlewares are not running so it will return null => Auth::user()

### Steps To Reproduce:
1. Trigger a wrong endpoint
2. Face a http not found exception
3. User is not accessible

**Comment by devcircus** [comment]
Search through the issues. It is designed this way. Use a fallback route if you need all middleware to run.

**Comment by GrahamCampbell** [comment]
Yes, this is by design.

**Comment by Mdhesari** [comment]
I think I should run middlewares manually with Pipeline, what do you think?

@devcircus 
@GrahamCampbell

**Comment by Mdhesari** [comment]
Using fallback can't help because I also want the samething for other errors such as 401, 403, 501 etc
