### ISSUE TITLE
Can't register a singleton with a SoapClient in the constructor

### ISSUE THREAD

**Issue by MarianNapi** [laravel/framework#33146]
- Laravel Version: 7.14.1
- PHP Version: 7.3.18

I've created a new ServiceProvider and added it to the app.php. I then registered a singleton with a test class which has a SoapClient in it's constructor:

`        $this->app->singleton(
            Test::class,
            function () {
                return new Test(new SoapClient(null));
            }
        );`

I then get this error when trying to get the class like this:

`app(Test::class)`

> Illuminate\Contracts\Container\BindingResolutionException : Unresolvable dependency resolving [Parameter #0 [ <required> $wsdl ]] in class SoapClient

It doesn't matter wether I use null or a real wsdl as SoapClient parameter, the error stays the same.

**Comment by driesvints** [comment]
Moving to discussions
