### ISSUE TITLE
Method getMimeType() returns wrong format on SVG files

### ISSUE THREAD

**Issue by filipbekic01** [laravel/framework#33147]
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Database Driver & Version: -

### Description:
When i upload `image/svg+xml` and invoke `getMimeType()` it returns `image/svg` instead. I tried to read `$_FILES['file_name']['type']` and it actually returns as expected `image/svg+xml` but `getMimeType()` is wrong. 

### Steps To Reproduce:
Upload `image/svg+xml` file and print it's mime type - it's wrong.

**Comment by driesvints** [comment]
We use symfony/mime under the hood. Please open up an issue on their repo.
