### ISSUE TITLE
Notifications id show only first digits

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#33141]
- Laravel Version: 7.14.1
- PHP Version: 7.3.18
- Database Driver & Version:

### Description:
When making @dd($notification), we get full uuid.
When trying get notification id in foreach loop, are returned only first diggits from id (if they are digits), or `0` (when two first digits are letters). Should return full id in all scenarios.
When trying get that notification by `Auth::user()->notifications()->find($id)` (first digits), get error.

### Steps To Reproduce:
Notifications ids in database:

In Controller
```php
public function index()
{
    $notifications = Notification::all();

    return view('notifications.index', ['notifications' => $notifications]);
}
```
In index.blade.php
```php
@foreach($notifications as $notification)
    {{-- @dd($notification) --}}
    {{ $notification->id }}
    @dd($notification->id)
@endforeach
```
We'll get:
```
92
92
```
When we call `@dd($notification)` in example blade we get full uuid in original node.
Expected result
```
92b97b2a-4951-47c9-bac4-4ec1228243bb
```

For fixing that, I need to add in mu own Notification class
```php
/**
 * The attributes that should be cast.
 *
 * @var array
 */
protected $casts = [
    'id' => 'string'
];
```
At least, please add that to docs!

**Comment by driesvints** [comment]
Works fine for me. The default `DatabaseNotification` class already has the proper key type: 

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Notifications/DatabaseNotification.php#L14

**Comment by EvidenceEkanem** [comment]
> * Laravel Version: 7.14.1
> * PHP Version: 7.3.18
> * Database Driver & Version:
> 
> ### Description:
> When making @dd($notification), we get full uuid. When trying get notification id in foreach loop, are returned only first diggits from id (if they are digits), or `0` (when two first digits are letters). Should return full id in all scenarios. When trying get that notification by `Auth::user()->notifications()->find($id)` (first digits), get error.
> 
> ### Steps To Reproduce:
> Notifications ids in database:
> 
> In Controller
> 
> ```
> public function index()
> {
>     $notifications = Notification::all();
> 
>     return view('notifications.index', ['notifications' => $notifications]);
> }
> ```
> 
> In index.blade.php
> 
> ```
> @foreach($notifications as $notification)
>     {{-- @dd($notification) --}}
>     {{ $notification->id }}
>     @dd($notification->id)
> @endforeach
> ```
> 
> We'll get:
> 
> ```
> 92
> 92
> ```
> 
> When we call `@dd($notification)` in example blade we get full uuid in original node. Expected result
> 
> ```
> 92b97b2a-4951-47c9-bac4-4ec1228243bb
> ```
> 
> For fixing that, I need to add in mu own Notification class
> 
> ```
> /**
>  * The attributes that should be cast.
>  *
>  * @var array
>  */
> protected $casts = [
>     'id' => 'string'
> ];
> ```
> 
> At least, please add that to docs!

same bug found in laravel 7

**Comment by Daniil-Solovyev** [comment]
I got the same problem. The only thing that helps is getting the table through the DB facade instead of getting the model through Eloquent. DB:table('my_table')->get() instead of Model::get(). Maybe it will be useful for someone.

**Comment by pakistanimoon** [comment]
i am still getting same issue in laravel 9
i solved it using 
`DB::table('notifications')->` instead of `Notification::`

**Comment by LocalHeroPro** [comment]
I have to be cast automatically. Without additional workaround.

**Comment by MarienMupenda** [comment]
You need to add a custom method and get the original value.





     public function id()
     {
       return $this->getRawOriginal('id');
     }
