### ISSUE TITLE
Mutators for columns with case not applied to array serialization

### ISSUE THREAD

**Issue by jnoordsij** [laravel/framework#33145]
- Laravel Version: 7.10.3
- PHP Version: 7.4.3
- Database Driver & Version: MariaDb 10.1.23

### Description:
When defining a mutator for a database column that starts with an uppercase letter, the attribute is correctly mutated when retrieving it from the model (e.g. `$model->Attribute`). However, the array representation of the model returns the original non-mutated value (e.g. `$model->toArray()['Attribute']`).

### Steps To Reproduce:
1. Add a mutator to a model that has an attribute retreived from a database column with an uppercase first letter. 
1. Serialize the model to an array and access the attribute.
1. The returned attribute is not mutated.

### Possible cause
The matching done [here](https://github.com/laravel/framework/blob/v7.13.0/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L185) checks for matches between keys in `$attributes` and `$mutatedAttributes`, where the first contains a key starting with an uppercase and the second contains a key starting with a lowercase.

### Example model:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class Example extends Model
{
    /**
     * The attributes that should be visible in serialization.
     *
     * @var array
     */
    protected $visible = [
        'CaseColumn',
        'otherColumn',
    ];

    /**
     * Map used to map attributes.
     *
     * @var array
     */
    public static $attributeMap = [
        'key' => 'value',
        'otherkey' => 'othervalue',
    ];
    
    /**
     * Return otherColumn value: works on arrays
     *
     * @param string $value
     *
     * @return string
     */
    public function getOtherColumnAttribute($value) {
        return Arr::get(self::$attributeMap, $value, 'Default');
    }

    /**
     * Return CaseColumn value: does NOT work on arrays
     *
     * @param string $value
     *
     * @return string
     */
    public function getCaseColumnAttribute($value) {
        return Arr::get(self::$attributeMap, $value, 'Default');
    }
}
```

**Comment by driesvints** [comment]
Mutators expect columns to be snake cased.

**Comment by jnoordsij** [comment]
Ok, so then it is actually bugged when retreiving it from the model? As now model and array behave in a different manner, which I think is quite confusing...
