### ISSUE TITLE
Artisan Tinker issue

### ISSUE THREAD

**Issue by arafathoq** [laravel/framework#33153]
- Laravel Version: 7.12.0
- PHP Version: 7.4.6
- Database Driver & Version: 10.4.12-MariaDB 

### Description: Artisan Tinker does not run updated class methods 
Requires exit from Artisan shell and re enter artisan shell to run the latest class method

### Steps To Reproduce:
Enter artisan shell
Run class method
Modify class method
Run class method -> still produces old data

**Comment by CaddyDz** [comment]
This is by design, artisan uses PHP Repl and loads the container once per session, there is nothing Laravel can do

**Comment by arafathoq** [comment]
thanks, that was really quick

appreciate the info

**Comment by CaddyDz** [comment]
Here's a [reference](https://github.com/bobthecow/psysh/issues/416#issuecomment-332725566)

**Comment by CaddyDz** [comment]
There was [this project](https://github.com/furey/tinx) to get the session reloaded  from within tinker

**Comment by arafathoq** [comment]
I will keep it simple
Exit and re enter tinker shell
