### ISSUE TITLE
HTTP Client Response json() method return type inaccurate

### ISSUE THREAD

**Issue by Alanaktion** [laravel/framework#33155]
- Laravel Version: 7.14.1
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
In the HTTP client, the Response [json() method](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Http/Client/Response.php#L51) defines its return type as `array` and mentions that it returns in array in its description.

When an HTTP request is retrieved that contains a non-object JSON response, the return type in the `json()` method may not actually be `array`, for example if the response data is a JSON-encoded string, or null/boolean value, but still parses correctly and returns the expected value.

It makes sense to me to change the return type in the PHPDoc block to `mixed`, and add a note to the method description that objects will be returned as associative arrays, rather than that the function always returns an array.

### Steps To Reproduce:

Call any JSON API that returns a json-encoded scalar value. For example:

```php
use Illuminate\Support\Facades\Http;

Http::fake([
    'example.com/string' => Http::response(json_encode('Example'), 200, ['Content-Type' => 'application/json']),
    'example.com/bool' => Http::response(json_encode(true), 200, ['Content-Type' => 'application/json']),
]);

$response = Http::get('http://example.com/string');
$response->json(); // "Example"
$response = Http::get('http://example.com/bool');
$response->json(); // true
```

**Comment by nwehrhan** [comment]
Your correct it will not always return an array.
Here is where its decoded: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Http/Client/Response.php#L50

I opened up a pull request here to change the return type: https://github.com/laravel/framework/pull/33157

This seems like expected `json_decode` behavior. https://www.php.net/json_decode

**Comment by driesvints** [comment]
Feel free to send in a PR to the docs.

**Comment by nwehrhan** [comment]
I made the update to the 7.x docs. https://github.com/laravel/docs/pull/6098
