### ISSUE TITLE
laravel collection contains not working properly 

### ISSUE THREAD

**Issue by joisarjignesh** [laravel/framework#33168]
- Laravel Version: 7.0
- PHP Version: 7.4.6
- Database Driver & Version: sqlite

### Description: laravel collection contains method not working properly

for example :
```
$collection = collect([
    ['color' => 'blue', 4, 2],
    ['x', 'y', 'color' => 'red', 'shape' => 'circle', 300],
    ['make' => 'Acura', 'type' => 'NSX'],
]);

dd($collection->contains('color', 'blue'));   //return true
dd($collection->collapse()->contains('color', 'blue')); //return false
```

without collapse() contains work properly after collapse() and then use contains() it not working properly
it will return result as false but 'color' key  with value 'blue' is there .

**Comment by driesvints** [comment]
Moving to discussions.
