### ISSUE TITLE
Response status code [403] is not an unauthorized status code (assertUnauthorized)

### ISSUE THREAD

**Issue by millman2394** [laravel/framework#33167]
- Laravel Version: ^7.0
- PHP Version: 7.3.16
- Database Driver & Version: mysql 7

### Description:
I'm trying to use `assertUnauthorized()` on a test that should return unauthorized from a FormRequest class.

The issue is that this only returns true if the status is a `401` rather than a `403`

```
public function assertUnauthorized()
    {
        $actual = $this->getStatusCode();

        PHPUnit::assertTrue(
            401 === $actual,
            'Response status code ['.$actual.'] is not an unauthorized status code.'
        );

        return $this;
    }
```

### Steps To Reproduce:
Create a FormRequest class and return false on a request via a test. Try to `assertUnauthorized` and it will tell you `Response status code [403] is not an unauthorized status code.`

**Comment by driesvints** [comment]
403 is forbidden: https://httpstatuses.com/403
