### ISSUE TITLE
Use of Illuminate\Support\Reflector in Illuminate\Routing\RouteDependencyResolverTrait breaks type hinting when using  'self'

### ISSUE THREAD

**Issue by oldusername91** [laravel/framework#33177]
- Laravel Version: 6.18.18
- PHP Version: 7.4.6
- Database Driver & Version: mysql 5.7

### Description:

Illuminate\Routing\RouteDependencyResolverTrait::transformDependency used to handle type hint ```self``` on Controller methods.

This is no longer the case after [1af06328c77b875dfb3304f3e9611c2078314acb](https://github.com/laravel/framework/commit/1af06328c77b875dfb3304f3e9611c2078314acb#diff-f49ef6656de3695a6595631fb339b4b4)

### Exception message
Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target class [self] does not exist."

### Steps To Reproduce:

Model:

```
<?php

namespace Models;

use Illuminate\Database\Eloquent\Model;

class WeatherVane extends Model
{
    public static function windDirection(self $wv)
    {
        return view('wind_direction', ['model' => $wv]);
    }
}
```
Route:
```
Route::get('windDirection/{wv}', [
    'uses' => 'Models\WeatherVane@windDirection',
]);
```

**Comment by GrahamCampbell** [comment]
Thanks for the report. I'll look into fixing this.

**Comment by driesvints** [comment]
A model can't be a controller so it's pretty unconventional what you're trying to do here.

**Comment by oldusername91** [comment]
Unconventional yes, not recommended I'm sure, but it was something that was working in a previous version of the framework.

**Comment by GrahamCampbell** [comment]
This is still a bug in the new reflection stuff. self and static need to be resolved to their actual class names. I will send a PR to do this later today.
