### ISSUE TITLE
Option parsed incorrectly in artisan command

### ISSUE THREAD

**Issue by nerg4l** [laravel/framework#33175]
- Laravel Version: 6.18.15
- PHP Version: 7.2.24
- Database Driver & Version:

### Description:

Option parsed incorrectly in artisan command. Should not detect dash when wrapped in quotes.

### Steps To Reproduce:

Run a command with dash in a string.

```
php artisan command:name "- "
```

```
The "- " option does not exist.
```

**Comment by driesvints** [comment]
Heya, I can indeed confirm this. However, the code handling this under the hood is Symfony Console so you'll need to open up a ticket on their end.

**Comment by nerg4l** [comment]
Sure, thanks
