### ISSUE TITLE
 Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by NesmaJarour** [laravel/framework#33189]
when I write in command -- 
php artisan db:seed --class=CategoriesTableSeeder
This error appears 
 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Laravel' for key 'categories_name_unique' (SQL: insert into `categories` (`created_at`, `is_published`, `name`, `slug`, `updated_at`, `user_id`) values (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1), (2020-06-11 16:35:07, 1, Laravel, laravel, 2020-06-11 16:35:07, 1))

  at C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

  1   C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
      PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Laravel' for key 'categories_name_unique'")

  2   C:\xampp\htdocs\laravelblog\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
      PDOStatement::execute()

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by NesmaJarour** [comment]
Thank you very much for your help .
