### ISSUE TITLE
Tuple routes do not work if name is before verb method

### ISSUE THREAD

**Issue by hailwood** [laravel/framework#33192]
- Laravel Version: 7.15.0
- PHP Version: 7.4.6

### Description:
When defining routes you can use the tuple syntax - 

```php
Route::get('test', [TestController::class, 'index'])->name('test');
```

And this works correctly, however if you switch the order of those methods to 

```php
Route::name('test')->get('test', [TestController::class, 'index']);
```

Then you'll hit

> ReflectionException: Function () does not exist at vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:23

Which appears to be an issue when it gets `$action['uses']`.

**Comment by driesvints** [comment]
Name always needs to be after the HTTP method call.
