### ISSUE TITLE
Illuminate\Foundation\Auth\ThrottleLogins removed in 7.x and is not reflected anywhere in the upgrade documentation

### ISSUE THREAD

**Issue by chrisidakwo** [laravel/framework#33194]
- Laravel Version: 7.15.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL

### Description:
This isn't an issue. I should have probably done a PR to the docs, but I'm not sure how to write that. 

On upgrading from Laravel 5.8 to 7, I noticed that the `ThrottleLogins` class has been removed. Or is that it has been moved somewhere else? I've tried searching, but can't find it.

If removed or moved to a different namespace, I think the upgrade docs should mention that.

**Comment by driesvints** [comment]
This has been moved to the UI package which is noted here: https://laravel.com/docs/7.x/upgrade#authentication-scaffolding

**Comment by chrisidakwo** [comment]
Oh, I now see the meaning of "authentication scaffolding". With the name of the package as "laravel/ui", I'd easily assumed that was just for the auth views and assets.

Thanks though.
