### ISSUE TITLE
Computed attributes are only serialized if they have a corresponding regular attribute with the same name.

### ISSUE THREAD

**Issue by shawn-simon** [laravel/framework#33197]
- Laravel Version: 7.x
- PHP Version: any
- Database Driver & Version:

### Description:

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L185

```
            // We want to spin through all the mutated attributes for this model and call
            // the mutator for the attribute. We cache off every mutated attributes so
            // we don't have to constantly check on attributes that actually change.
            if (! array_key_exists($key, $attributes)) {
                continue;
            }
```

The ! here in line 185 is erroneous, this means it only serializes computed attributes IF they have a corresponding attribute with the same name.  Therefore, the cache is only populated if it's already populated.

**Comment by driesvints** [comment]
Sounds like an optimization. Feel free to open up a discussion or send in a PR.

**Comment by shawn-simon** [comment]
KK. Actually I think I misread the code. Please delete / ignore this, sorry!
