### ISSUE TITLE
@elseguest directive doesn't work

### ISSUE THREAD

**Issue by JonMagon** [laravel/framework#33204]
- Laravel Version: 7.13.0
- PHP Version: 7.4.3

### Description:
When a user is logged he can't see a part between @elseguest and @endguest directives.
In the compiled blade there's just the same condition in both ifs.
```php
<?php if(auth()->guard()->guest()): ?>
    <div>first</div>
<?php elseif(auth()->guard()->guest()): ?>
    <div>second</div>
<?php endif; ?>
```

### Steps To Reproduce:

- Use the following construction:
```php
@guest
    <div>first</div>
@elseguest
    <div>second</div>
@endguest
```

**Comment by X-Coder264** [comment]
The compiled Blade PHP looks as expected. Check this PR (and the tests in it) for more info:

https://github.com/laravel/framework/pull/23569

**Comment by JonMagon** [comment]
Thanks, it makes sense. else confuses me here
