### ISSUE TITLE
Middleware priority puts StartSession before EncryptCookies

### ISSUE THREAD

**Issue by muisit** [laravel/framework#33208]
- Laravel Version: 7.x
- PHP Version: 7.2
- Database Driver & Version: MySql

### Description:
The router sorts middleware before executing. It uses a middlewarePriority mapping, of which the root version is defined in Illuminate\Foundation\Http\Kernel.php

If you add the Illuminate\Cookie\Middleware\EncryptCookies (or the default App\Http\Middleware\EncryptCookies stub), it should _always_ run before the StartSession middleware, or else the session cookie is not recognised. However, EncryptCookies is not in the priority list by default, so if the routes are sorted, it could (!) occur that StartSession is run first. This happens if another middleware is found before StartSession that is defined with a lower priority, like 'throttle'.

### Steps To Reproduce:
Define a middleware definition containing throttle, StartSession and EncryptCookies:
        'web' => [
            'throttle:60,1',
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Session\Middleware\StartSession::class]

The EncryptCookies should always run first. However, because the default priority puts StartSession before Throttle, the first is moved to the top of the list, before EncryptCookies.

This is not regularly encountered, because either EncryptCookies is in the global middleware list, or throttle is not used in the same middleware group as StartSession (which is the case if you throttle the API, but use tokens instead of session cookies).

### Fixes
The user could add his/her own priorities, but the documentation advises against this.

The user could move the throttle middleware to after the StartSession him/herself, in which case SortedMiddleware recognises that the order is fine and does not reorder. This seems the least invasive, but it is not easy to recognise why this is happening in the first place.

The default priority list could include EncryptCookies before StartSession, so we never run into encrypted session cookies. This seems like the most easy solution.

**Comment by taylorotwell** [comment]
Feel free to PR something for this. This isn't really a "bug" because Laravel ships with the middleware in the correct order. Only if you move them into an incorrect / invalid order do you receive an error.

**Comment by muisit** [comment]
I beg to differ. 
Laravel by default does not put EncryptCookies in the priority list, which means it gets a default priority of 'after-prioritized'. This is incorrect, as it always needs to run before 'StartSession', and that one does have a priority.

The fact that the problem does not occur 'by default' is only because 'by default' the throttle middleware is not in the same list as the StartSession and EncryptCookies.
