### ISSUE TITLE
Dump and cookies not working together

### ISSUE THREAD

**Issue by bertheyman** [laravel/framework#33215]
- Laravel Version: 7.14.1
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
Using `dump` sets headers, which might silent fail for setting cookies. (as they can't be set when headers are already sent)
A `var_dump` doesn't trigger this behaviour when I tested it.

Not sure what causes the difference between dump and var_dump.
Would there be a way of having dump work with cookies?
If not, would it be a good idea to mention this in the docs?
Might be a great help because of the silent failure.

### Steps To Reproduce:
1. Use a dump()
2. Set a cookie afterwards
3. No cookie is set (and no error is triggered)

**Comment by driesvints** [comment]
Dump is a Symfony function and unfortunately out of our control. If you want to clarify something in the docs we're welcoming prs 👍
