### ISSUE TITLE
Queue worker remembers singleton between jobs

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#33222]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: MySql 5.7.3

### Description:
Queue workers remember singletons between jobs.

### Steps To Reproduce:
Some class with state:
```php
class Foo
{
    private $now;

    public function get()
    {
        if (! $this->now) {
            $this->now = now()->toDateTimeString();
        }

        return $this->now;
    }
}
```

AppServiceProvider:
```php
public function register()
{
    $this->app->singleton(Foo::class);
}
```

Queued job:
```php
class SomeJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        $foo = app(Foo::class);

        info($foo->get());
    }
}
```

Dispatch the job multiple times:
```php
Route::get('/', function () {
    SomeJob::dispatch();
});
```

Running a queue worker using `artisan queue:work` will always log the same value:

![image](https://user-images.githubusercontent.com/7202674/84683986-480c0c80-af38-11ea-91f3-69765c6654db.png)

I've experienced this bug both using the `database` and `redis` queue drivers.

**Comment by taylorotwell** [comment]
That's not a bug. That's how daemon queue workers work. If you want to have a non-daemon listener that reboots the framework on each job use `queue:listen`.
