### ISSUE TITLE
Schema renameColumn() not working with case-sensitive table names

### ISSUE THREAD

**Issue by Phil795** [laravel/framework#33228]
- Laravel Version: 5.8
- PHP Version: 7.1.33
- Database Driver & Version: PostgreSQL 10.12
- Doctrine DBAL: ^2.9

### Description:
I am currently working with the schema class for modifying tables. 
If the table name is lowercase (example: prefix_foo_bar) there are no problems. 
But if the table name is case-sensitive, renaming the column will not work with the built-in `renameColumn()` function.

### Steps To Reproduce:
Create table (example: prefix_Table_Name)
Use schema class to rename a column:

```php
$oldColumn = 'PLATZHALTER_34';
$newColumn = 'FooBar';
$tableName = "prefix_Table_Name";

Schema::table($tableName, function(Blueprint $table) {
  if(Schema::hasColumn($tableName, '"'.$oldColumn.'"')) {
    $table->renameColumn('"'.$oldColumn.'"', '"'.$newColumn.'"');
  }
});
```

### Exception
```javascript
{
  "message": "SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"bi_formular_demo\" does not exist (SQL: ALTER TABLE bi_formular_Demo RENAME COLUMN \"PLATZHALTER_16\" TO \"datetime\")",
  "exception": "Illuminate\\Database\\QueryException",
  "file": "C:\\Users\\Philipp\\Documents\\Report Editor\\ReportEditor\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php",
  "line": 664,
}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
