### ISSUE TITLE
return response()->json

### ISSUE THREAD

**Issue by n3aka** [laravel/framework#33233]
- Laravel Version: 7.13.0
- PHP Version: 7.1.4
- Database Driver & Version: mysql, mariadb:10.2.14

### Description:
Let's say I have an Post table and a comment table with a one to many relationship
When I want to create a json formated response, I receive the post with the comment and a seperate object with the response only, however if I only put the post I don't receive the coment at all

### Steps To Reproduce:

Post.php
``
``<?php

namespace App;
use App\Language;
use App\Categorie;
use App\Profile;
use App\Attachement;

use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    ...
    public function attachements()
    {
        return $this->hasMany(Attachement::class);
    }
}
``
PostController.php:
``
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Comment;

use Illuminate\Support\Facades\Http;
...
class AssignmentsController extends Controller
 /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
$post= Post::findOrFail($id);
....
return response()->json([
            'post' => $assignment,
            'comment' => $post->comment
        ]);
``
It's my second week into laravel and my first bug report, so I hope I did everything right and thanks for your work, it's a nice framework!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
