### ISSUE TITLE
7.16.1 - Empty array incorrectly validates with 'required' rule

### ISSUE THREAD

**Issue by woodsandwalker** [laravel/framework#33235]
- Laravel Version: 7.16.1
- PHP Version: 7.4.1

### Description:
Empty array incorrectly validates with 'required' rule and doesn't throw error as expected.

### Steps To Reproduce:
```
$validator = \Validator::make([], [
    'foo' => ['required']
]);
$validated = $validator->validated();

// code beyond here is executed
```

**Comment by driesvints** [comment]
> The field under validation must be present in the input data

https://laravel.com/docs/7.x/validation#rule-required
