### ISSUE TITLE
Method prepareForValidation returns ParameterBag on $this->attributes instead of Form Field

### ISSUE THREAD

**Issue by i6media** [laravel/framework#33246]
- Laravel Version: 7.16.1
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.7

### Description:
When you have a form field called _attributes_ and you use the `prepareForValidation` Method in a Form Request Validation, you can't fetch that field properly. The [documentation](https://laravel.com/docs/7.x/validation#prepare-input-for-validation) states that you should use `$this->slug` to receive the specified Form Field. However when you call `$this->attributes`, you won't receive the contents of the Form Field, but a ParameterBag instead.

### Steps To Reproduce:
- Create a Form in Blade: `<input type="text" name="attributes" value="Test" />`
- Create a Request: `php artisan make:request FormRequest`
- Create Method PrepareForValidation inside FormRequest:
   ```
    protected function prepareForValidation()
    {
        // Dumps ParameterBag instead of "Test"
        dd($this->attributes)
    }
   ```

**Comment by taylorotwell** [comment]
Likely because `$attributes` is a public property of the Symfony HttpFoundation class. There is no way for us to resolve this. You would need to use $this->input('attributes') most likely.

**Comment by i6media** [comment]
That works like a charm, thanks!
