### ISSUE TITLE
Deprecated warnings after composer update (symfony/http-foundation to v5.1)

### ISSUE THREAD

**Issue by jschurse** [laravel/framework#33240]
- Laravel Version: 7.16.1
- PHP Version: 7.4.3
- Database Driver & Version: Not relevant

### Description:
Since the upgrade of Symfony Http-Foundation to v5.1 calling the set method of the InputBag Class with a null value triggers an deprecated warning.

https://github.com/symfony/http-foundation/blob/5.1/InputBag.php#L77-L81

The Laravel middleware ConvertEmptyStringsToNull which is being called on each request by default will cause these warnings. It seems to no longer be compatible with the Symfony InputBag.

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php#L16

### Steps To Reproduce:

- Install new Laravel instance as described in the docs.
- Enable deprecated warnings in php
- Make http request to laravel with an GET param without value.

### Possible Fixes:

̶f̶̶i̶̶x̶̶ ̶̶t̶̶h̶̶e̶̶ ̶"̶s̶̶y̶̶m̶̶f̶̶o̶̶n̶̶y̶/̶h̶̶t̶̶t̶̶p̶-̶f̶̶o̶̶u̶̶n̶̶d̶̶a̶̶t̶̶i̶̶o̶̶n̶"̶ ̶̶d̶̶e̶̶p̶̶e̶̶n̶̶d̶̶e̶̶n̶̶c̶̶y̶̶ ̶̶t̶̶o̶̶ ̶̶v̶̶5̶̶.̶̶0̶
̶h̶̶t̶̶t̶̶p̶̶s̶̶:̶//̶g̶̶i̶̶t̶̶h̶̶u̶̶b̶̶.̶̶c̶̶o̶̶m̶/̶l̶̶a̶̶r̶̶a̶̶v̶̶e̶̶l̶/̶f̶̶r̶̶a̶̶m̶̶e̶̶w̶̶o̶̶r̶̶k̶/̶b̶̶l̶̶o̶̶b̶/̶7̶̶.̶̶x̶/̶c̶̶o̶̶m̶̶p̶̶o̶̶s̶̶e̶̶r̶̶.̶̶j̶̶s̶̶o̶̶n̶#̶l̶̶3̶̶8̶
-> this was a bad idea because of https://github.com/symfony/symfony/security/advisories/GHSA-mcx4-f5f5-4859

Remove the ConvertEmptyStringsToNull middleware

**Comment by GrahamCampbell** [comment]
Symfony 5 will keep supporting null, so this isn't an issue. You should turn off deprecation warnings on your production server. Symfony will likely introduce more and more warnings in the 5.x series that Laravel will trigger.

**Comment by jschurse** [comment]
The problem is I have deprecation warnings enabled in my CI/CD pipeline where these are now being triggered on each run.

I removed the middleware from my Kernel.php to mitigate this problem.

**Comment by GrahamCampbell** [comment]
I'll keep this open, never the less, because this will eventually become a problem for later versions of Laravel. We need to consider if we want to change how this middleware works, maybe in Laravel 8.

**Comment by taylorotwell** [comment]
I have opened a PR on Symfony to try to get this fixed.

https://github.com/symfony/symfony/pull/37326
