### ISSUE TITLE
Laravel 7 pessimistic locking locks entire table instead of a single row!

### ISSUE THREAD

**Issue by navaneeth-raman-bhaskar** [laravel/framework#33258]
- Laravel Version: 7.15
- PHP Version: 7.4.6
- Database Driver & Version: MariaDB 10.4.11

### Description:
**Laravel 7** `pessimistic locking` **locks entire table instead of a single row:**

Below code is going to return array response for each invoices.
Once action method called for id =1 it takes 20 sec to get committed.
When the same method called for id=2 response waits until the first transaction is finished.

```

protected function actions($id)
    {
      DB::beginTransaction();
        try {
      if($id==1)
          sleep(20);

        $invoice = Invoice::lockForUpdate()->find($id);
        $name = 'Approve';
        if ($invoice->approved) {
            $name = 'Disapprove';      
        }
    } catch (Exception $e) {
            DB::rollBack(); 
        }
        DB::commit();

        return [
            'name' => $name,
            'id' => 'menu-approve',
            'data-status' => $invoice->approved
        ];
    }

```

### Steps To Reproduce:

```
class InvoiceController extends Controller
{ 
    protected function actions($id)
    {
      DB::beginTransaction();
        try {
      if($id==1)
          sleep(20);

        $invoice = Invoice::lockForUpdate()->find($id);
        $name = 'Approve';
        if ($invoice->approved) {
            $name = 'Disapprove';      
        }
    } catch (Exception $e) {
            DB::rollBack(); 
        }
        DB::commit();

        return [
            'name' => $name,
            'id' => 'menu-approve',
            'data-status' => $invoice->approved
        ];
    }
 }
```

> Why entire table is locked instead of single row ? @taylorotwell

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by navaneeth-raman-bhaskar** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

It was perfectly worked on Laravel 6.x


> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

It was previously working on Laravel **6.x**
a `lockForUpdate()` locks a specific row until it was committed successfully.
But other` select *` queries without a` lockForUpdate()` could read the entire table.
In **7.x** when you locked a single row, the entire record(table) gets locked!.

> Isn't this a serious bug??

**Comment by navaneeth-raman-bhaskar** [comment]
It was previously working on Laravel **6.x**

A `lockForUpdate()` locks a specific row until it was committed successfully `(Select * from invoices where id=1 FOR UPDATE`). 
But `select * from invoices where id=2 FOR UPDATE` should not be wait until the first query get committed. 
Also without specifying a lock (` Select * from invoices`) records are not drawn and it waits the first transaction to be committed. 
What could be the possible reason to lock entire table instead of a single row?

In **7.x** when you locked a single row, the entire record(table) gets locked!
