### ISSUE TITLE
Eloquent Value Object are not casted back when converting models to json.

### ISSUE THREAD

**Issue by rela589n** [laravel/framework#33257]
- Laravel Version: 7.15.0
- PHP Version: 7.3.7
- Database Driver & Version: 10.3.16-MariaDB

### Description:
The problem is that value objects are not casted back when call `Client::toJson()`.
So, for example we have next model:
```
App\Models\Client {#4028
     id: 7,
     name: "asdf@asdf.com",
     email_verified_at: null,
   }
```
Accessing `name` property gives us `Name` value object: 
```
App\ValueObjects\Name^ {#4027
  #name: "asdf@asdf.com"
}
```
When we call `$client->toJson()`, we get empty object instead of primitive value:
`{"id":7,"name":{},"email_verified_at":null}`
### Steps To Reproduce:
_Client Eloquent Model:_
```
class Client extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'name'     => NameCast::class,
        'password' => PasswordCast::class,
    ];
}
```
_Name Cast:_
```
class NameCast implements CastsAttributes
{
    public function get($model, string $key, $value, $attributes)
    {
        return Name::create($value);
    }

    public function set($model, string $key, $setName, $attributes)
    {
        if (!$setName instanceof Name) {
            throw new \InvalidArgumentException('Parameter $setName must be instance of ' . Name::class);
        }

        return [
            $key => $setName->value()
        ];
    }
}
```
_Name Value Object:_
```
class Name
{
    public const MIN_LENGTH = 2;

    protected $name;

    private function __construct(string $name)
    {
        if (mb_strlen($name) < self::MIN_LENGTH) {
            throw new \InvalidArgumentException('Name must has at least ' . self::MIN_LENGTH . ' characters');
        }

        $this->name = $name;
    }

    public static function create(string $name): Name
    {
        return new static($name);
    }

    public function value()
    {
        return $this->name;
    }
}
```

**Comment by driesvints** [comment]
I get the same result and was also a bit surprised at this. I'm suspecting that this is the expected behavior and that you should implement `Illuminate\Contracts\Support\Arrayable` on your value object. But it would be good to clarify this in the docs.

Gonna wait to see what @taylorotwell says about this.

**Comment by taylorotwell** [comment]
Objects are expected to implement Arrayable / JsonSerializable to solve this. I thought I documented that but maybe not. If not we can update the documentation.

**Comment by driesvints** [comment]
I sent in a PR here: https://github.com/laravel/docs/pull/6123
