### ISSUE TITLE
Str::contains() returns a "false negative" result due to mb_strpos usage

### ISSUE THREAD

**Issue by willsmanley** [laravel/framework#33264]
- Laravel Version: 7.15.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 8.0.19

### Description:

`Str::contains()` is really handy but I think its usage of `mb_strpos` causes it to rarely give a false negative. 

I am not exactly sure how mb_strpos works relative to strpos, but it has to do with byte sequencing. If the sequence of bytes doesn't match exactly, no result is returned.

I am not sure if it has to do with charset of the strings being compared, but I found one such instance where a false negative is returned. 

### Steps To Reproduce:

```
try {
   // Any DB query that will result in a QueryException due to violation of an integrity constraint.
   // Easiest way to do this is to try to store a row with a value that already exists on a UNIQUE column
   $user = new User();
   $user->unique_id = 123; // assuming that a User with unique_id 123 already exists.
   $user->save();
}catch (Exception $e){

   // $e->getMessage() will output something like this:
   // SQLSTATE[23000]: Integrity constraint violation: 1062 ...........

   $contains = Str::contains($e->getMessage(), 'Integrity constraint violation');
   // false

   $contains = strpos($e->getMessage(), 'Integrity constraint violation') > -1;
   // true
}
```

I suggest updating Str::contains to use strpos() instead as it seems to be more accurate. If that makes sense I can create a PR.

**Comment by driesvints** [comment]
Seems to be working fine: https://3v4l.org/1UAVH

**Comment by willsmanley** [comment]
You need to actually run the query. It works fine when you manually paste a
string.

Please re-open and give a standard query a try.

**Comment by willsmanley** [comment]
@driesvints Could you please re-open the issue and attempt to replicate the bug using an actual DB query? The issue is not going to be re-produceable by copying the error message text because it has to do with the specific character encoding used when a query exception is thrown.

**Comment by driesvints** [comment]
Can you post an actual DB query for me to test out?

**Comment by willsmanley** [comment]
I did but I will do it again in more detail.

**1) Run a migration for a users table**
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateUsersTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('users', function(Blueprint $table)
		{
			$table->id();
                         $table->timestamps();
                         $table->string('unique_id')->unique();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('users');
	}
}
```

** 2)Make sure you have a Users model **


**3) Execute a DB query to trigger the exception  **
```
try {
   $user = new User();
   $user->unique_id = 123; // this user is created successfully
   $user->save();

   $user = new User();
   $user->unique_id = 123; // this user will not be created successfully because of the unique constraint on ID
   $user->save();
}catch (Exception $e){

   // $e->getMessage() will output something like this:
   // SQLSTATE[23000]: Integrity constraint violation: 1062 ...........

   $contains = Str::contains($e->getMessage(), 'Integrity constraint violation');
   Log::debug($contains);
   // false

   $contains = strpos($e->getMessage(), 'Integrity constraint violation') > -1;
   Log::debug($contains);
   // true


}

```

**Comment by driesvints** [comment]
Thanks for the detailed example. I tried this but both return true for me.

**Comment by willsmanley** [comment]
Are you testing it on a Mac? I can’t figure out why that would be a
different result from me.

**Comment by driesvints** [comment]
yes

**Comment by sisve** [comment]
Did you save your code file with a weird encoding? It sounds like the database message is in one encoding, and the string you got in your code is in another encoding.
