### ISSUE TITLE
Mocking Notification Failed 

### ISSUE THREAD

**Issue by mohammedabdallah** [laravel/framework#33260]
- Laravel Version: ^6.0
- PHP Version: 7.3.17
- Database Driver & Version:Mysql &  Ver 14.14 Distrib 5.7.30

### Description:
I want to fake notification but always it asserting false and say 
The expected [App\Notifications\NewOrderReceived] notification was not sent.
Failed asserting that false is true.
### Steps To Reproduce:
After Some debugging I ended up to this function 
`* Get all of the notifications for a notifiable entity by type.
     *
     * @param  mixed  $notifiable
     * @param  string  $notification
     * @return array
     */
    protected function notificationsFor($notifiable, $notification)
    {
        return $this->notifications[get_class($notifiable)][$notifiable->getKey()][$notification] ?? [];
    }**`
It generate error Undefined index: App\Models\User

**My code **
`<?php

namespace Tests\Unit;

use App\Models\Brand;
use App\Models\SubOrder;
use App\Models\User;
use App\Notifications\NewOrderReceived;
use App\Services\OrderService;
use App\States\Order\PendingPayment;
use App\States\Order\Preparing;
use Tests\TestCase;

use Illuminate\Support\Facades\Notification;
class NotficationTest extends TestCase
{
    protected $orderService;

    protected function setUp(): void
    {
        $this->orderService = app()->make(OrderService::class);
        parent::setUp();
    }
    /** @test */
    public function it_send_notification_in_case_of_status_is_changed()
    {
        $brand = factory(Brand::class)->create();

        $subOrder = factory(SubOrder::class)->create(
            [
                'brand_id' => $brand->id,
                'state' => PendingPayment::$name,
            ]
        );

        Notification::fake();
        $subOrder->state = Preparing::$name;
        $subOrder->save();
        Notification::assertSentTo(
            User::latest()->first(),
            NewOrderReceived::class,
           1
        );

    }

}
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by seewhy17** [comment]
@mohammedabdallah I can't seem to see any line of code that actually sends the notification. I think you should do that before your assertions.
Since you are sending the notification to a user, you should have a reference to a user Model or collection depending on your flavor...


```
...
// get the user
$user = ...

$user->notify(new NewOrderReceived($subOrder));

// then you can make your assertions

```
hopefully, this helps.
