### ISSUE TITLE
Declaration of Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) must be compatible with Illuminate\Contracts\Debug\ExceptionHandler::report(Exception $e)

### ISSUE THREAD

**Issue by svoby1** [laravel/framework#33282]
- Laravel Version: 7.16.1
- PHP Version: 7.3.11
- Database Driver & Version: -

### Description:
I have got 2 errors:
`Fatal error: Declaration of Illuminate\Foundation\Exceptions\Handler::report(Throwable $e) must be compatible with Illuminate\Contracts\Debug\ExceptionHandler::report(Exception $e) in /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 38`

second:
`Fatal error: Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Container/Container.php:805 Stack trace: #0 /Users/Svoby/www/localhost/fakturacia/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): ReflectionClass->__construct('App\\Exceptions\\...') #1 /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->build('App\\Exceptions\\...') #2 /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array, false) #3 /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\Foundation\Application->resolve('App\\Exceptions\\...', Array, false) #4 /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Co in /Users/Svoby/www/localhost/projectName/api/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 807`

I upgraded laravel from 6 to 7, and of course I have read an upgrade manual. But still I do know, what can cause an issue.

### Steps To Reproduce:
Try to show a blade page which is not valid/broken.

Thank you

**Comment by driesvints** [comment]
Please see previously posted issues and make sure you update your symfony dependencies as well.
