### ISSUE TITLE
Calling a query using "with" returns some null relations when they do exist

### ISSUE THREAD

**Issue by xLesterGG** [laravel/framework#33295]
- Laravel Version: 7.16.1
- PHP Version: 7.3.5
- Database Driver & Version: MySQL 5.7

### Description:
Calling a relation by using `with` returns certain results with null even if relation exists (data exists with correct foreign key)

### Steps To Reproduce:

I have created a fresh project with the minimal required elements to reproduce this [here](https://github.com/xLesterGG/laravelapp)

There are 2 tables and two models, credit_requests (parent) and user_addresses(child). 

After you have cloned it, run the migrations and run `db:seed` ( this seeds runs the user addresses factory and create the linking credit request).

The expected output would be 500 credit requests with their user addresses.

In the seed, I will log the results of the query `CreditRequest::with('userAddress')->get()`

By viewing the laravel.log, search for `"user_address":null` , you will see that some records are missing the relation even when all the records are created via the factory. 

By doing a `migrate:refresh --seed`, the number of nulls will vary

**Comment by staudenmeir** [comment]
You need to set the correct key type: https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions

```php
class CreditRequest extends Model
{
    public $incrementing = false;

    protected $keyType = 'string';

    public function userAddress()
    {
        return $this->hasOne('App\UserAddress');
    }
}
```

**Comment by xLesterGG** [comment]
> You need to set the correct key type: https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions
> 
> ```
> class CreditRequest extends Model
> {
>     public $incrementing = false;
> 
>     protected $keyType = 'string';
> 
>     public function userAddress()
>     {
>         return $this->hasOne('App\UserAddress');
>     }
> }
> ```

I have verified this fixes the issue. Is there any reason why some records do somehow return the relation and some does not since the keyType isn't set in the first place?

**Comment by staudenmeir** [comment]
I would guess that the matching only "works" when the UUID starts with a digit.

**Comment by xLesterGG** [comment]
> I would guess that the matching only "works" when the UUID starts with a digit.

That sounds logical. Maybe having an alert or error would be good when the datatype expected and received as it's not obvious when there is is problem, and is not easy to debug
