### ISSUE TITLE
Model Object Serialization To Arrays

### ISSUE THREAD

**Issue by navaneeth-raman-bhaskar** [laravel/framework#33292]
- Laravel Version: 7.16
- PHP Version: 7.4.6
- Database Driver & Version: MariaDB 10.4.13

### Description:

**Laravel `7.x` serialization of created_at column vs `6.x` serialisation**

In 6.x serialized created_at column value shows `2020-06-21 08:26:11`.
in 7.x serialized created_at column has a value `2020-06-21T08:26:11.000000Z`
### Steps To Reproduce:
I need to save many relationship as single insert like this
```
$subArray = [];
      for ($i = 0; $i < count($request['subs']); $i++) {
           $sub = new InvoiceSub(); 
           $sub->invoice_id = $invoice->id;  //$invoice already saved
           $sub->setSub($request, $i);  //this  will set rest of the attributes
           $sub->created_at = $sub->updated_at = now()->format('Y-m-d H:i:s');
           $subArray[] = $sub->toArray();
        }  
DB::table('invoice_subs')->insert($subArray); // multiple insertion
```
when you die and dump `$subArray` you can see the difference in 6.x and 7.x
The problem is that in 7.x throws a database error because of serialization difference.

I am reporting this issue and I have another suggestion.

> I can directly use laravel **saveMany()**
like  `$invoice->saveMany($subArray) //subArray contains object instead of array.`
But i'm not using it because of it runs as many query as the number of subs.
Is there any way of saving many related data in a single query?

**Comment by CalumTowers** [comment]
This is [documented in the upgrade guide](https://laravel.com/docs/7.x/upgrade#date-serialization) for Laravel 7 and an example is provided to restore the 6.x behaviour too.

**Comment by navaneeth-raman-bhaskar** [comment]
@CalumTowers Ok thank you.
