### ISSUE TITLE
[7.0 - MAILER] How to replace swift.transport

### ISSUE THREAD

**Issue by mrWodoo** [laravel/framework#33309]
For laravel 5.7 I had
`<?php

namespace App\Providers;

use App\Services\EmailLabs\TransportEmailLabs;
use Illuminate\Support\Arr;
use Illuminate\Support\ServiceProvider;
use GuzzleHttp\Client as HttpClient;

class EmailLabsServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->publishes([
            __DIR__.'/../config/emaillabs.php' => config_path('emaillabs.php'),
        ], 'config');
        $transportManager = $this->app['swift.transport'];
        $this->registerEmailLabsTransport($transportManager);
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Get to register our custom email driver
     *
     * @return void
     * @author Sebastian
     **/
    protected function registerEmailLabsTransport($manager)
    {
        $manager->extend('emaillabs', function(){
            $config = $this->app['config']->get('emaillabs', []);
            $client = $this->getHttpClient($config);
            return new TransportEmailLabs($client, $config);
        });
    }

    /**
     * Prepare configured http client
     *
     * @return GuzzleHttp\Client
     * @author Sebastian
     **/
    protected function getHttpClient($config)
    {
        $guzzleConfig = Arr::get($config, 'guzzle', []);
        return new HttpClient(Arr::add($guzzleConfig, 'connect_timeout', 60));
    }
}
`

as my custom provider, but now I get this error

`Target class [swift.transport] does not exist. `
I'm unable to find any proper docs for replacing/extending the swift.transport for 7.0

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
