### ISSUE TITLE
CastAttributes work incorrectly when try to work with original attributes

### ISSUE THREAD

**Issue by mrakolice** [laravel/framework#33302]
- Laravel Version: 7.15.0
- PHP Version: 7.4.3

### Description:
When try to cast original value to object, `getOriginal` works unexpectedly - this function overrides original attribute getter (because of `$classCastCache`) and main getter (`$model->attribute`) start returns previous value.

If I can have options to disable this cache for some fields, this would be great.

### Steps To Reproduce:

I tried to setup in my project [php-decimal](https://php-decimal.io/) for better work with numbers.
When I casting database values to object I have this bug.

Here some simple example code with test, that fails.

```php

class CustomCastingTest extends AppTestCase
{
    public function testOriginalCasting(): void
    {
        $model = new TestModel();

        $model->amount = 15;

        $this->assertSame(15, $model->amount->getField());
        $model->save();

        $model->amount = 25;
        $this->assertSame(15, $model->getOriginal('amount')->getField());
        $this->assertSame(25, $model->amount->getField()); // return 15 here
    }
}

class TestModel extends Model
{
    public $timestamps = false;

    protected $casts = [
        'amount' => SomeObjectCaster::class,
    ];
}

class SomeObject
{
    private $field;

    public function __construct($field)
    {
        $this->field = $field;
    }

    public function getField()
    {
        return $this->field;
    }

    public function __toString()
    {
        return strval($this->field);
    }
}

class SomeObjectCaster implements CastsAttributes
{
    public function get($model, $key, $value, $attributes)
    {
        if ($value instanceof SomeObject) {
            return $value;
        }

        return new SomeObject($value);
    }

    public function set($model, $key, $value, $attributes)
    {
        return [$key => (new SomeObject($value))->getField()];
    }
}



```

**Comment by driesvints** [comment]
This is exactly how `getOriginal` works. You updated the value at `$model->amount = 25;` but the "original" value is still 15.

**Comment by driesvints** [comment]
Hmm, sorry looks like I was a tad too fast. I'll take a look why amount isn't returning 25.

**Comment by driesvints** [comment]
I agree that this seems like a bug. I'd also expect the cache to be cleared when a new value is set. I'm gonna let @taylorotwell confirm this first before I send in a fix.

**Comment by mrakolice** [comment]
Thanks for the fast response!

**Comment by rela589n** [comment]
Defining cast for `amount` you tell that it should be `SomeObject` for the client. But you set the value not of it's instance. I think you should do something like `$model->amount = new SomeObject(15)`. Or use mutators.

**Comment by driesvints** [comment]
@rela589n is correct. I forgot this myself. I'll try to make the docs more clear about this.

@mrakolice try this:

```php

    public function testBasicTest()
    {
        $model = new User();

        $model->amount = new SomeObject(15);

        $this->assertSame(15, $model->amount->getField());
        $model->save();

        $model->amount = new SomeObject(25);
        $this->assertSame(15, $model->getOriginal('amount')->getField());
        $this->assertSame(25, $model->amount->getField()); // return 15 here
    }
}
```

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/docs/pull/6128

**Comment by mrakolice** [comment]
This approach is not solved this kind of problem, I checked it. I described where to find bug. You can find this bug in Illuminate\Database\Eloquent\Concerns\HasAttributes.php#565 and #572.
