### ISSUE TITLE
Inflector\Inflector::pluralize Deprecated version 5.8.38

### ISSUE THREAD

**Issue by bluemountainteam** [laravel/framework#33319]
- Laravel Version: 5.8.38
- PHP Version: 7.2.19
- Database Driver & Version: Mysql 5.7

### Description:
Hi Support,

I have a problem with Doctrine//inflector with this problem: The "Doctrine\Common\Inflector\Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API. on line 261

I know that this problem already speaking in other issue.

I use composer update, but the problem is always here, how can i resolve it?

Thanks

**Comment by GrahamCampbell** [comment]
Yes, this is deprecated, and so is Laravel 5.8. Please upgrade to Laravel 6 LTS or Laravel 7, or turn off deprecation warnings in production.

**Comment by bluemountainteam** [comment]
Thanks @GrahamCampbell for the quickly answer :-)

**Comment by zaratedev** [comment]
Thx @GrahamCampbell
