### ISSUE TITLE
Packets out of order due to calling stored procedure

### ISSUE THREAD

**Issue by adeel-raza-azeemi** [laravel/framework#33318]
- Laravel Version: 7.2.31-1
- PHP Version: 7.6.2
- Database Driver & Version:10.3.22-MariaDB

### Description:
IF you call a stored procedure that opens a cursor; will cause the database to aborted connection; and laravel will gives you packets out of order exception.

MariaDB error

    2020-06-22 12:56:05 15 [Warning] Aborted connection 15 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
    2020-06-22 12:56:08 14 [Warning] Aborted connection 14 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
    2020-06-22 12:56:08 68 [Warning] Aborted connection 68 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)
    2020-06-22 12:56:08 67 [Warning] Aborted connection 67 to db: 'srsp_hrd' user: 'root' host: 'localhost' (Got an error reading communication packets)

Laravel exception

    Packets out of order. Expected 1 received 33. Packet size=297 (SQL: CALL get_par())

### Steps To Reproduce:
    DELIMITER @@
    DROP PROCEDURE IF EXISTS get_par @@
    CREATE PROCEDURE get_par ()
    BEGIN

        DECLARE cur CURSOR FOR SELECT pID, fname FROM pars;

        SET @cSql = CONCAT('CREATE OR REPLACE view pars as SELECT pID, fname FROM participant WHERE trgID =1');
        PREPARE stmt FROM @cSql;
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt; 

        OPEN cur;

        SELECT 'In CURSOR';

        CLOSE cur;
        DROP VIEW pars;

    END @@ 
    DELIMITER ; 

Although calling the procedure from terminal is absolutely fine.

    CALL get_par();

But calling it from laravel causes the error

    $par = DB::select('CALL get_par()');

**Comment by driesvints** [comment]
Ref https://github.com/laravel/framework/issues/24255

**Comment by taylorotwell** [comment]
Unsure this is a Laravel bug.

**Comment by adeel-raza-azeemi** [comment]
Dries Vints @driesvints  i had read that issue before issuing this; several times. And PR didn't solved this issue.

@taylorotwell Sir just execute the code and if you don't got the error than I accept all the blame.

**Comment by adeel-raza-azeemi** [comment]
Just in case to prove my point here is the vanilla PHP code that executes like a charm. But Laravel throws an exception. This is the show method of controller. Where Laraval statement throws an exception whereas vanilla PHP works like a charm. Please at least accepts that this is a bug. 
For now I will use vanilla besides Laravel to get the work done.

    public function show(training $training) {

This will throw an exception. Laravel statement        

        // DB::select('CALL get_par()');

        $con = '';
        $res = array();
        try {
          $con = new \mysqli(env("DB_HOST", "localhost"), env("DB_USERNAME", "root"), env("DB_PASSWORD", 'password'), env("DB_DATABASE", "db_name"))
                  or die('Could not connect to the database server' . mysqli_connect_error());
          if (empty($con))
            throw new \Exception("Connection is only allowed for authorized personnels.", 5001);
        } catch (\Exception $e) {
          echo 'Caught exception: ', $e->getMessage(), "\n";
        }
        $r = $con->query('CALL get_par()');
        while ($row = mysqli_fetch_array($r)) {
          $res[] = $row;
        }

        dd(json_encode($res));
        return view('training.training.show', compact('training'));
      }

**Comment by mfn** [comment]
@adeel-raza-azeemi you're comparing different things here; not saying there's no problem, but you're showing the `mysqli_*` extension, whereas Laravel only uses PDO.

Please try it with raw PDO first

**Comment by adeel-raza-azeemi** [comment]
@mfn You are right; sadly I had rarely used PDO. Anyway will try that now. Thanks for the guidance.

**Comment by adeel-raza-azeemi** [comment]
Ok I had written in PDO and it had executed perfectly

    public function show(training $training) {
      $con = '';
      $res = array();

    try {
      $con = new \PDO("mysql:host=" . env('DB_HOST', 'localhost') . ";dbname=" . env('DB_DATABASE', 'db'), env('DB_USERNAME', 'root'), env("DB_PASSWORD", 'password'));
      $con->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

      foreach ($con->query('CALL get_par()') as $row) {
        $res[] = $row;
      }
      $con = null;
    } catch (\PDOException $e) {
      echo "Connection failed: " . $e->getMessage();
    }

    dd(json_encode($res));
    return view('training.training.show', compact('training'));
  }

**Comment by mfn** [comment]
You can get the underlying PDO instance from your DB connection and just use it.

Maybe `::select()` does some magic which interferes, I haven't looked at it.
