### ISSUE TITLE
HasAttributes::originalIsEquivalent() float comparing bug

### ISSUE THREAD

**Issue by digitv** [laravel/framework#33321]
- Laravel Version: 6.18.21
- PHP Version: 7.3.16
- Database Driver & Version: PostgreSQL 

### Description:
When saving Eloquent model with only one change in attribute with `float` casting it do nothing, just returns true.
It's becouse of invalid comparison in `HasAttributes::originalIsEquivalent()` in section (line 1181)
```
        } elseif ($this->hasCast($key, ['real', 'float', 'double'])) {
            return bccomp(
                $this->castAttribute($key, $current),
                $this->castAttribute($key, $original)
            ) === 0;
        } elseif ($this->hasCast($key)) {
```
It doesn't compare decimal part because of missing thir paramer `$scale` for `bccomp`.

### Steps To Reproduce:
Get a model with `float` casting of some attribute, save it and try to update only decimal part of that attribute (eg 1.5 => 1.6).
If you'll go deeper you find that:
```
::isDirty() => false
::getDirty() => []
::originalIsEquivalent() => true
```

**Comment by digitv** [comment]
Laravel `6.18.20` has no such bug.
Commit https://github.com/laravel/framework/commit/0a49b23336671df73c3d94a4b6a1e75025c8f65b breaks functionality.

**Comment by taylorotwell** [comment]
Reverting the PR.

**Comment by digitv** [comment]
THX a lot )
