### ISSUE TITLE
Ignition error : undefined identifier

### ISSUE THREAD

**Issue by kuldep7** [laravel/framework#33327]
![Screenshot from 2020-06-24 21-30-02](https://user-images.githubusercontent.com/40533394/85591597-0b8c8f00-b663-11ea-82f7-e50cdc9bac3e.png)
Uncaught SyntaxError: Unexpected identifier
1:2 Uncaught SyntaxError: Unexpected token '!'
1:2 Uncaught TypeError: window.ignite is not a function
    at 1:2
(anonymous) @ 1:2
1:2 Uncaught ReferenceError: Ignition is not defined

These errors are displayed occasionally in console and nothing is displayed on screen.

**Comment by taylorotwell** [comment]
Please raise this on the Ignition repository.
