### ISSUE TITLE
Job retryAfter not being called on subsequent tries

### ISSUE THREAD

**Issue by filipegar** [laravel/framework#33331]
- Laravel Version: 6.18.21
- PHP Version: 7.4.6
- Database Driver & Version: PostgreSQL (libpq 12.2)

### Description:

I'm having some trouble to make retryAfter() work properly on a queued job using the database driver.
My App is calling a DownloadReport job that queries an external service - if the report is not available it would get back a 404. There is no such way to track the report generation so repeting the job looks the only way.

I added a retryAfter() method to my Job class expecting it to be called after every failed run, so I could create some kind of sliding retry window to allow this external service to process the data; but looks like retryAfter() is only called on the first run. After that the value is probably being cached and reused on every run.

Is there something that could be done to allow retryAfter() to re-run on every fail?
My job is being dispatched as `\App\Jobs\DownloadReport::dispatch($report)->onQueue('downloads')`.
The queue worker is a simple `php artisan queue:work --queue=downloads`

### Steps To Reproduce:

1. Generate a Job with `php artisan make:job`
2. Set a public `$tries` variable to something big.
3. Add a retryAfter method with the following code (from [the docs](https://laravel.com/docs/7.x/queues#dealing-with-failed-jobs))
```
public function retryAfter()
{
    return 60 * pow(2, $this->attempts());
}
```
4. Make the handle() method raise an exception on every run.
5. Dispatch the job with `App\Job\ThatJobYouCreated::dispatch()`
6. Run the queue worker
7. Let it run and watch that the job retrying every 120s and not 120, 240, 480, 960 - as retryAfter method defines.

**Comment by themsaid** [comment]
Backoff is called one time when the job is being dispatched and the value is stored in the payload. It's not called on each failure.

You'll need to catch the exception and call :

```
$this->release(
   60 * pow(2, $this->attempts())
);
``

**Comment by driesvints** [comment]
@filipegar we're updating the docs which were incorrect. Thanks for reporting this.

**Comment by filipegar** [comment]
Thanks @driesvints @themsaid for clarifying it. Mohamed's suggestion worked great. Thanks!
