### ISSUE TITLE
Database configuration as URL/DSN with timezone

### ISSUE THREAD

**Issue by Gounlaf** [laravel/framework#33336]
- Laravel Version: 6.18.22
- PHP Version: 7.4.7
- Database Driver & Version: `pdo_mysql`

### Description:

I want to configure the timezone of a database connection. It doesn't when using a DSN.

### Steps To Reproduce:

* Declare a connection using the "url" options instead of splitting all part manually; `mysql://user:pwd@host:port/database_name?timezone=%2B00%3A00` or `mysql://user:pwd@host:port/database_name?timezone=+00:00`
* Make a request via Eloquent
* You will get an error about the timezone: it's parsed/decoded as ` 00:00` instead of `+00:00`

Encoded (`%2B00%3A00`) or "raw" version (`+00:00`) doesn't work
Things happens in ConfigurationUrlParser class, when options (queryString) are parsed.

Double encoding the value `%252B00%253A00` works, but I think it's more a hack than the real way to configure the URI/DSN.

Regards.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
