### ISSUE TITLE
While chaining a Macros or Mixins in  Illuminate\Database\Schema\Blueprint class its not working properly

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/framework#33345]
- Laravel Version: 7.17.2
- PHP Version: 7.4.3
- Database Driver & Version: 10.4.11-MariaDB

### Description:
While chaining a `Macros` or `Mixins` in  **Illuminate\Database\Schema\Blueprint** class its not getting called.
Based on #33341
### Steps To Reproduce:

1. Create a Macro.

```
Blueprint::macro('log',function($log){
            logger()->info($log);
            return $this;
        });

```

2.Use the macro in migration.
```
  /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Blueprint::macro('log',function($log){
            logger()->info($log);
            return $this;
        });

        Schema::create('random_table', function (Blueprint $table) {
            $table->id();
            //this will log
            $table->log('THIS WILL BE LOGGED')->string('first_name');
            //this won't be logged
            $table->string('last_name')->log('THIS WON\'t BE LOGGED')->nullable()->default('LAST_NAME');
        });
    }

```
3. Run migrate command

`php artisan migrate:fresh` or `php artisan migrate`

4. Now see the Log File.

Here is what i have got

`[2020-06-26 02:15:08] local.INFO: THIS WILL BE LOGGED `

**Here is the SQL Generated.**

```
CREATE TABLE `random_table` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`last_name` VARCHAR(255) NULL DEFAULT 'LAST_NAME' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;

```

**Comment by sisve** [comment]
`Blueprint::string('...')` returns a ColumnDefinition, not a Blueprint, so that's why you cannot call your macro on it. The ColumnDefinition class is based on Fluent which accepts any methods and attributes, and it treats the method invocation as a `$columnDefinition->log = 'THIS WON\'t BE LOGGED'`.

**Comment by driesvints** [comment]
Please see the answer above.
