### ISSUE TITLE
PHP Fatal error:  Interface 'JsonSerializable' not found 

### ISSUE THREAD

**Issue by davidmarin77** [laravel/framework#33344]
- Laravel Version: 7.
- PHP Version: 7.2
- Database Driver & Version:

Description:
when i install the laravel project in hostgator i got this issue

/vendor/laravel/framework/src/Illuminate/Support/Enumerable.php on line 11

Steps To Reproduce:

interface Enumerable extends Arrayable, Countable, IteratorAggregate, Jsonable, **JsonSerializable**

**Comment by GrahamCampbell** [comment]
This happens if `ext-json` is not enabled. Please ask your hosting provider to enable it. Laravel requires that extension.
