### ISSUE TITLE
Validator dotPlaceholder breaks key names returned

### ISSUE THREAD

**Issue by domainregistrar** [laravel/framework#33357]
- Laravel Version: 7.14.1
- PHP Version: 7.4
- Database Driver & Version: N/a

### Description:
It appears when a request parameter key contains a period "." the Validator.php generates a random string, and replaces the . but does not revert this when returning the parameters via $request->validated() - breaking the expected key name.

If it is required for dots to be converted within the application logic, would expect this to be reverted when returning the parameters from $request->validated();

### Steps To Reproduce:
Create request with rules():

`    public function rules()
    {
        return [
            'example'  => 'bail|required'
       ]
    }
`
Send request with parameters:

$_POST['example] = [ 'a.host.name' => null ];

Output:

$request->all():

`array(
'example' => array('a.host.name' => null)
)`

$request->validated():

`array(
'example' => array('aRANDOMhostRANDOMname' => null)
)`

**Comment by klimov-paul** [comment]
This issue has been fixed only partially.
The attribute key is still messed up at the validation messages array.

**Comment by l0rb** [comment]
This hasn't been fixed in Laravel 6, which should still get bug fixes till: September 7, 2021.

**Comment by Kwaadpepper** [comment]
On laravel 8.83 (Seems it starts since 8.76)

Validator replaces dots

So I had to replace this

    [function ($attribute, $value, $fail) use ($max, $dim) {
        try {
            if (\is_object($value)) {
                Validator::validate(
                    [$attribute => $value],
                    [$attribute => [
                        'file',
                        'mimes:png,jpg,jpeg',
                        sprintf(
                            'dimensions:%s=%d,%s=%d',
                            $max ? 'max_height' : 'height',
                            $dim['hauteur'],
                            $max ? 'max_width' : 'width',
                            $dim['largeur']
                        )
                    ]]
                );
            }
        } catch (ValidationException $e) {
            $fail(collect($e->errors())->first()[0]);
        }
    }]

with this in order to work 

    [function ($attribute, $value, $fail) use ($max, $dim) {
        try {
            if (\is_object($value)) {
                Validator::validate(
                    [$attribute => $value],
                    [self::mbReplace('.', '\.', $attribute) => [
                        'file',
                        'mimes:png,jpg,jpeg',
                        sprintf(
                            'dimensions:%s=%d,%s=%d',
                            $max ? 'max_height' : 'height',
                            $dim['hauteur'],
                            $max ? 'max_width' : 'width',
                            $dim['largeur']
                        )
                    ]]
                );
            }
        } catch (ValidationException $e) {
            $fail(collect($e->errors())->first()[0]);
        }
    }]

`$attribute` can be something like `data.product.picture1`
`$value` can be Http UploadedFile object
