### ISSUE TITLE
Bug when accessing nested query parameters from the `request` objects `get()` method

### ISSUE THREAD

**Issue by bilfeldt** [laravel/framework#33376]
- Laravel Version: 7.17.2
- PHP Version: 7.4.3
- Database Driver & Version: None

### Description:
Accessing nested query parameters using the `Request` works with `except()` (can exclude nested query parameter) but not for `get()` which is not able to fetch nested query parameters.

By "nested query parameters" I refer to parameters provided as arrays like the `filter` in this url, which holds both a `search` and a `country`: `/?filter[search]=emma&filter[country]=us&sort=name`.

Not sure if this is intended behaviour, but I would expect that the behaviour of `$request->get()` and `$request->except()` would be the same. Note that a query parameter with a dot (`'filter.search`) could also be presented and those are currently being changed to an underscore (`filter.search` => `filter_search`) - but this might change soon as I can see from [this](https://github.com/symfony/symfony/issues/29664))

Let me know if anything needs clarification.

### Steps To Reproduce:

Dump the request like so in `web.php`:

```php
Route::get('/', function (\Illuminate\Http\Request $request) {
    dd(
        $request->query(), // entire query: works 👍 
        $request->get('filter'), // get a single query parameter: works 👍 
        $request->get('filter.search'), // get a nested query parameter: bug 👎 
        \Arr::get($request->query(), 'filter.search'), // a workaround to get the nested value: works 👍  
        $request->except('filter.search') // this works just fine for nested parameters: works 👍 
    );
});
```
and check the result from the following request `/?filter[search]=emma&filter[country]=us&sort=name`

#### Result from `$request->query()`: works 👍 
The query parameter `filter` has two nested values `search` and `country` as expected:
```
[
  "filter" => [
    "search" => "emma",
    "country" => "us",
  ],
  "sort" => "name",
]
```

#### Result from `$request->get('filter')`: works 👍 
The query parameter `filter` has two nested values `search` and `country` as expected:
```
[
  "search" => "emma",
  "country" => "us",
]
```

#### Result from `$request->get('filter.search')`: bug 👎 
Fetching the nested query parameter `filter->search` does not work:
```
null // should have been "emma"
```

#### Result from `\Arr::get($request->query(), 'filter.search')`: works 👍 
Fetching the nested query parameter by using the `Arr::get` helper method works as expected:
```
"emma"
```

#### Result from ` $request->except('filter.search')`: works 👍 
Excluding a nested value works just fine, note that the nested `filter.country` is not removed as epected:
```
[
  "filter" => [
    "country" => "us",
  ],
  "sort" => "name",
]
```

**Comment by koenhoeijmakers** [comment]
The `get` method is pretty much the `Symfony` implementation, you could use `$request->input('filter.search')` instead.

**Comment by taylorotwell** [comment]
See above.

**Comment by bilfeldt** [comment]
@koenhoeijmakers you are right that `$request-> input('filter.search')` works 👍  while both `$request->query('filter.search')` and `$request->get('filter.search')` does not.

A minor "problem" is that `input()` accesses the entire payload as described in the [documentation](https://laravel.com/docs/7.x/requests#retrieving-input):
> ... retrieves values from entire request payload (including the query string)

So currently there is no solution for accessing a nested query parameter while ensuring it is not from the payload, but anyone else encountering this can use:
```
\Arr::get($request->query(), 'filter.search') // if it's important to only get results from the query
$request->input('filter.search') // if it's not really an issue that the data could also be elsewere in the payload
```
