### ISSUE TITLE
RefreshDatabase is behaving in an unexpected way when running on test database

### ISSUE THREAD

**Issue by ahmedash95** [laravel/framework#33383]
- Laravel Version: 7.17.2
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7.30

### Description:
RefreshDatabase trait uses `RefreshDatabaseState` to run the `artisan migrate:fresh` per file. and it uses database transactions to wipe the data after each test. the problem is with database rollback does not truncate the tables. it's just removing the added rows. so in an example tests like below, second and third case will always fail

```php
class ExampleTest extends TestCase
{
  use RefreshDatabase;

  public function test1()
  {
      $this->assertEquals(1, factory(User::class)->create()->id);
  }

  public function test2()
  {
      $this->assertEquals(1, factory(User::class)->create()->id); // id is 2
  }

  public function test3()
  {
      $this->assertEquals(1, factory(User::class)->create()->id); // id is 3
  }
}
```

### Steps To Reproduce:

In any laravel project write a new test with 3 methods like above and make sure your test database is `MySQL` or `Postgres` and it will fail

### Suggestion to fix

drop database state check. it will affect the performance as we will run migrations before each test but that would be the expected behavior in this case 

I can create the PR  of the Fix if maintainers agreed with me it should be fixed

**Comment by dwightwatson** [comment]
The issue here is your tests making assumptions about the state of the database - you probably don't need to be testing what the ID of created records is.

**Comment by mfn** [comment]
I'm with @dwightwatson 

Also there are databases like Postgres, where sequences (= mysql autoincrement) are also inherently _not_ part of a transaction. I.e. you create a new row and sequence was increased => a rollback will remove the row but _not_ roll back the sequence number.

IMHO there isn't anything to fix here unless you're seeking a MySQL specific workaround or so…

**Comment by ahmedash95** [comment]
> The issue here is your tests making assumptions about the state of the database - you probably don't need to be testing what the ID of created records is.

to make it more clear (and probably I'm doing it wrong but it worth saying). I'm using pest to write tests like below. and I'm using beforeEach to create a new user and log him in before each test. 

```php
uses(RefreshDatabase::class);

beforeEach(fn () => actingAs($user = factory(User::class)->create()));


test('can ask question', function(){
    livewire(AskQuestion::class, ['toUserId' => 1])
        ->set('question', 'How old are you')
        ->call('saveQuestion');

    $this->assertDatabaseHas('questions', [
        'question' => 'How old are you',
        'from_user_id' => 1,
    ]);
});
```

**Comment by ahmedash95** [comment]
I've found the answer https://laravel.com/docs/7.x/dusk#migrations. using `DatabaseMigrations` will run the migration before each test and that made it work as expected for me.

**Comment by mfn** [comment]
Yeah, apologies, I could have spotted this too as I'm using `DatabaseMigration`.

I believe for MySQL it will work because the autoincremnets roll back, but other DBs might not do that.

**Comment by ahmedash95** [comment]
MySQL is enough for me. thanks for your answer :)
