### ISSUE TITLE
laravel error

### ISSUE THREAD

**Issue by zilinyo** [laravel/framework#33387]
Laravel Version: 7.16.1
PHP Version:8.0

### Description:

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/default/htdocs/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/default/htdocs/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 927

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/default/htdocs/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 853

Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/default/htdocs/blog/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 927

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest version of Laravel. We already fixed this. :)
