### ISSUE TITLE
RequestValidation using Model abstraction inconsistency

### ISSUE THREAD

**Issue by cehmke91** [laravel/framework#33398]
- Laravel Version: v7.14.1
- PHP Version: 7.4.5
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.29, for osx10.15 (x86_64) using  EditLine wrapper

### Description:
When validating a request with a unique constraint I can do the following `unique:model_table,unique_attribute`.
If I want to validate an update request and ignore the value on the current model so that the validation doesn't fail attempting to update the unique_attribute to the existing value, I can pass the id like: `unique:model_table,unique_attribute,model_id`.
In addition if I wish to be validating on a column other than id I can add that like `unique:model_table,unique_attribute,column_value,column_name`.

The final value defaults to id, I believe because this is what most commonly will be what is validated on, in essence the primary_key of most tables, and if I have a different primary key then I can set it there like so:
`unique:model_table,unique_attribute,model_id,primary_field`.

Laravel will also allow you to pass the model name instead of the table name, this allows me to keep the knowledge of the table name entirely in the model. You would do so like: `unique:App\Model,unique_attribute`.
This then reads $table attribute on the model. However if I then have a non-standard primary key field on the table the following doesn't work `unique:App\Model,unique_attribute,model_id` returning with an error stating that id doesn't exist.
It would still work with `unique:App\Model,unique_attribute,model_id,id_column_name`.
Thus it's not reading the column name in the same way that it does the table name.

Given the behaviour of passing in the model instead of the table name, and that the column_name always defaults to 'id' I believe the intention for it is to default to the $primaryKey, a value which it could read from the model as it does the $table attribute when being provided the model. This would also more completely and neatly encapsulate the values inside the Model, instead of exposing them to the request as well.

### Steps To Reproduce:

- create a request for a model with an id primary key field, which has a validator on a unique field.
- set the validation `unique:model_table,unique_attribute,model_id`
- send an update request, observe this will ignore the value already on the model.
- change the validation to `unique:App\Model,unique_attribute,model_id`
- run the same request, the behavior should be the same
- set the primary key field to something like `user_id` instead of `id`
- set the validation as `unique:model_table,unique_attribute,model_id`
- run the same request, observe that it will fail to validate trying to retrieve the id from the database.
- set the validation as `unique:model_table,unique_attribute,model_id,user_id`
- this should validate correctly again
- set the validation as `unique:App\Model,unique_attribute,model_id`
- this will again fail attempting to read the non-existent id from the database
- set the validation to `unique:App\Model,unique_attribute,model_id,user_id`
- this passes again as before.

I believe that given the model has been provided the validation should read the primaryKey from the model if no value is provided instead of defaulting to id.

**Comment by taylorotwell** [comment]
Fixed in next patch release.
