### ISSUE TITLE
Pagination unnecessary three dots when onEachSide is 2

### ISSUE THREAD

**Issue by pnunas** [laravel/framework#33397]
- Laravel Version: 7.8.1
- PHP Version: 7.4.5
- Database Driver & Version: MariaDB 10.4

### Description:
Pagination elements has unnecessary three dots when set `onEachSide(2)`
`<- 1 2 ... 6 7 [8] 9 10 ... 11 12 ->`
`<- 1 2 ... 3 4 [5] 6 7 ... 11 12 ->`

**Comment by taylorotwell** [comment]
Update your Laravel version.
