### ISSUE TITLE
URL::signedRoute ignores the custom key set in route definition.

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#33399]
- Laravel Version: 7.18.0
- PHP Version: 7.3.18
- Database Driver & Version: pgsql

### Description:

When Generating a named route that is signed, via `URL::signedRoute()` and the route sets a custom key `teams/{team:slug}` The team's id is used instead of the slug. Generating the route unsigned returns the slug as expected.

```php
URL::route('teams.show', $team); // /teams/some-team
URL::signedRoute('teams.show', $team); // teams/4?signature=eeb765d7b1ad43721beb257ad6d780f1fb651a0b8c31e2f648e2d3530155610f
```

Expected Result:
```php
URL::signedRoute('teams.show', $team); // teams/some-team?signature=eeb765d7b1ad43721beb257ad6d780f1fb651a0b8c31e2f648e2d3530155610f
```

### Steps To Reproduce:

Define a route with a model binding and a custom key, e.g. `teams/{team:slug}` then generate a signed url with the route. `URL::signedRoute('teams.show', $team)`.

**Comment by joel-butcher** [comment]
@tobz-nz signed routes use the route key for the model to generate that part of the URL. You can get around this issue by overriding the `getRouteKeyName` method in your model.

**Comment by taylorotwell** [comment]
Fixed in next patch release.
