### ISSUE TITLE
Pivot Table `WithPivot` Casting Attribute

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#33401]
- Laravel Version: v7.17.2
- PHP Version: 7.4.5
- Database Driver & Version: PostgreSQL (ver. 12.2 (Ubuntu 12.2-2.pgdg18.04+1))

### Description:
I have a Company object. This company object has many variables over a Many-To-Many relationship. The pivot table created has an additional column, value. This value is a double.

So I have in my code... ( Ignore the namespace please :) )
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model {

    /** @var string[] */
    protected $casts = [
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function variables() {
        return $this->belongsToMany(Variable::class)
            ->withPivot(['value'])
            ->withCasts(['value' => 'float']);
    }
}
```
However, no cast...
Code: `dd($company->variables->map->pivot->map->value);`
![Screen Shot 2020-07-01 at 10 36 36 AM](https://user-images.githubusercontent.com/10394554/86263367-bf6fac00-bb86-11ea-9dd5-0a354ec5a54e.png)

Ok... so let's try this piece of code
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model {

    /** @var string[] */
    protected $guarded = [];

    /** @var string[] */
    protected $casts = [
        'variables.pivot.value' => 'float'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function variables() {
        return $this->belongsToMany(Variable::class)
            ->withPivot(['value'])
            ->withCasts(['value' => 'float']);
    }
}
```
Still no luck
Code: `dd($company->variables->map->pivot->map->value);`
![Screen Shot 2020-07-01 at 10 38 11 AM](https://user-images.githubusercontent.com/10394554/86263520-f80f8580-bb86-11ea-979c-88be90201189.png)

What about if we get the other model involved, the Variable?
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Variable extends Model {

    /** @var string[] */
    protected $casts = [
        'pivot.value' => 'float',
    ];
}
```
And with that I'm out of ideas to cast this ever elusive value to a float
Code: `dd($company->variables->map->pivot->map->value);`
![Screen Shot 2020-07-01 at 10 39 31 AM](https://user-images.githubusercontent.com/10394554/86263673-28572400-bb87-11ea-962a-03643a5389a8.png)

Is this a bug? Is there something I missed in the documentation? 

Thank you for your time.

**Comment by gofish543** [comment]
In the code above, I do have other pieces of code in the Models, but I have removed them to avoid clutter and allow the Laravel team to more easily reproduce this error.

**Comment by staudenmeir** [comment]
You need to define a custom pivot model and add the cast there:
https://laravel.com/docs/7.x/eloquent-relationships#defining-custom-intermediate-table-models

**Comment by gofish543** [comment]
I am aware I can do a custom pivot model. But I do not want to and an entire pivot model is grossly over-killing what I need to do.

**Comment by taylorotwell** [comment]
I don't think we ever intended withCasts to work this way. You are placing a withCast on the relationship model, not the pivot model. We don't have a feature for doing this to the pivot table at this time. Closing since this is not an "issue" but simply a missing feature.
