### ISSUE TITLE
On-Demand Notifications route not respected, seems is overwritten by the via notification class method

### ISSUE THREAD

**Issue by illambo** [laravel/framework#33408]
- Laravel Version: 6.18.23
- PHP Version: 7.2.22
- Database Driver & Version: *

### Description:
[On-Demand Notifications](https://laravel.com/docs/6.x/notifications#on-demand-notifications) route not respected, seems is overwritten by the via notification class method

### Steps To Reproduce:

- run `php artisan make:notification Test`
- set _via_ array to  _database_ and _mail_

```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class Test extends Notification
{
    use Queueable;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail', 'database'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
                    ->line('The introduction to the notification.')
                    ->action('Notification Action', url('/'))
                    ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            //
        ];
    }
}
``` 

- test with php artisan (with mail driver log)
`php artisan tinker`
`\Illuminate\Support\Facades\Notification::route('mail', ['tom@gmail.com', 'jerry@gmail.it'])->notify(new \App\Notifications\Test);`

- check errors -> attempt to create data to db
- another try with empty via array
```
/**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return [];
    }
``` 
- check result log -> no message sent

Example of my current workaround:
```
/**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ($notifiable instanceof \Illuminate\Notifications\AnonymousNotifiable) ?
            array_keys($notifiable->routes) : ['database', 'mail'];
    }
```

Do you have any suggestions? am I wrong?

:) Thanks for the support!

**Comment by driesvints** [comment]
You can't have an empty via. And when you use an on demand notification it'll limit it to the one channel you're sending.

**Comment by illambo** [comment]
@driesvints thanks for the reply but can u check this steps:

- test with php artisan (with mail driver log)

php artisan tinker
\Illuminate\Support\Facades\Notification::route('mail', ['tom@gmail.com', 'jerry@gmail.it'])->notify(new \App\Notifications\Test);

- check errors -> attempt to create data to db

Why try to create data to _database_ channel if route asked is _mail_ ?

Thanks

**Comment by driesvints** [comment]
Hey @illambo. I tried that scenario and also get the error of the database channel. In general I think it would make sense for us to prevent using the database channel for anonymous notifiables. I'll try to whip up a pr for this. Thanks for reporting.

**Comment by driesvints** [comment]
Sent in a PR here: https://github.com/laravel/framework/pull/33409
