### ISSUE TITLE
Model > whereHas > Multiple Connection > Cross Database | Not Working

### ISSUE THREAD

**Issue by MwSpaceLLC** [laravel/framework#33402]
- Laravel Version: **7.X.X**
- PHP Version: **PHP 7.4.6 (cli) (built: May 12 2020 11:38:52)**
- Database Driver & Version: **Ver 8.0.20 for Win64 on x86_64**

### Description:
In multiple connection project all work, but we need to use whereAs method but not work.
We have checked online searching all the forums of the framework but have not found the solution to our problem.
we have multiple connections in the same project one manages in particular the user database and it all works by changing the connection in the model class.  

As in this example the method in particular does not work other methods yes.

```php
Route::get('/test', function ($event = null) {
    echo User::with('categories')->get();
    echo User::whereHas('categories')->get(); // this method break (not change connection)
});
```

Result on web:
![image](https://user-images.githubusercontent.com/29952045/86268058-ec907e80-bbc7-11ea-9c6d-d75842c3496d.png)

On the result, first method work fine. Other method not property. i think not change connection

### User Class belongsToMany:
```php

    /**
     * @var string
     */
    protected $connection = "lumen";

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->setConnection('ciao')->belongsToMany(
            Category::class,
            'user_category')
            ->withPivot('user_role');
    }
```

### Category Class belongsToMany:
```php

    /**
     * @var string
     */
    protected $connection = "helpdesk";

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(
            User::class,
            'user_category'
        )
            ->withPivot('user_role');
    }
```
We have tried to force db changes connection but not work...

### Steps To Reproduce:

Create Multiple Connection and use belongsToMany Function in Model

**Comment by staudenmeir** [comment]
Please see #23042, especially https://github.com/laravel/framework/issues/23042#issuecomment-451665259.

**Comment by MwSpaceLLC** [comment]
Thanks @taylorotwell @staudenmeir,

For now we install a package. In future this issue will be fix ?

**Comment by MwSpaceLLC** [comment]
So we tried to install package and extend by new eloquent model class. but not work.

**Comment by MwSpaceLLC** [comment]
Hi there, we want to write that for us all work fine in mysql with package [cross-database](https://github.com/hoyvoy/laravel-cross-database-subqueries).

![image](https://user-images.githubusercontent.com/29952045/86354491-70e70e00-bc69-11ea-9ef7-e801cdfb899b.png)

In this query User are in DB1 and categories are in DB2. the result work great!

![image](https://user-images.githubusercontent.com/29952045/86354653-b572a980-bc69-11ea-9b87-4858c756ac98.png)

For us, we must specify relation connection ('database.relation') in : 

![image](https://user-images.githubusercontent.com/29952045/86354747-df2bd080-bc69-11ea-8420-17976b69dc74.png)

And for User, we must replace Authenticatable with new model class:

![image](https://user-images.githubusercontent.com/29952045/86354822-01255300-bc6a-11ea-928f-60c026b7ec38.png)

![image](https://user-images.githubusercontent.com/29952045/86354850-0bdfe800-bc6a-11ea-9f53-90bbf9862258.png)

Thanks for the trick :+1:

**Comment by laratutodotcom** [comment]
-----------[SOLVED]-------------- 
How To Connect Multiple Database In Laravel?
https://laratuto.com/how-to-connect-multiple-database-in-laravel/

**Comment by f-liva** [comment]
Support for different databases is needed

**Comment by skalero01** [comment]
Hi everyone, just for commenting another solution you can use is creating a Model that extends eloquent with the next code

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model as Base;

class Model extends Base
{
    public function __construct(array $attributes = [])
    {
        $this->table = $this->getConnection()->getDatabaseName().'.'.$this->getTable();
        parent::__construct($attributes);
    }
}
```

And extends this model instead of eloquent one and it will work

**Comment by michelbarutot** [comment]
works perfect!

**Comment by ahmadrio** [comment]
> Hi everyone, just for commenting another solution you can use is creating a Model that extends eloquent with the next code
> 
> ```
> <?php
> 
> namespace App\Models;
> 
> use Illuminate\Database\Eloquent\Model as Base;
> 
> class Model extends Base
> {
>     public function __construct(array $attributes = [])
>     {
>         $this->table = $this->getConnection()->getDatabaseName().'.'.$this->getTable();
>         parent::__construct($attributes);
>     }
> }
> ```
> 
> And extends this model instead of eloquent one and it will work

thanks, it works

**Comment by Taoshan98** [comment]
> Hi everyone, just for commenting another solution you can use is creating a Model that extends eloquent with the next code
> 
> <?php
> 
> namespace App\Models;
> 
> use Illuminate\Database\Eloquent\Model as Base;
> 
> class Model extends Base
> {
>     public function __construct(array $attributes = [])
>     {
>         $this->table = $this->getConnection()->getDatabaseName().'.'.$this->getTable();
>         parent::__construct($attributes);
>     }
> }
> And extends this model instead of eloquent one and it will work

It works only if both databases are on th same server.
