### ISSUE TITLE
Customizing default key name in route doesn't override Route::model effect

### ISSUE THREAD

**Issue by aanbar** [laravel/framework#33403]
- Laravel Version: 7.14.1
- PHP Version: 7.2.30
- Database Driver & Version: MySQL 5.7.21

### Description:
Using custom key for routing doesn't override Route::model effect, it keeps hitting the id column by default

### Steps To Reproduce:
Add the following in your routes file assuming you are using a model named 'Page'
```
Route::model('page', \App\Page::class);
Route::get('page/{page:slug}', function(\App\Page $page) {
    return 'Hello World';
});

```

It will produce 404 instead of 'Hello World', I have laravel-debugbar installed & it shows the query being made is as follows:

```
select * from `pages` where `id` = 'page-slug' limit 1
```

**Comment by gofish543** [comment]
I opened an issue about this a few weeks ago. By using Route::model you are explicitly binding 'page' to \App\Page which results in that model's route key being used. 
Refer to the issue for more information #https://github.com/laravel/framework/issues/33079
