### ISSUE TITLE
After caching config: crash > There is no existing directory at /laravel_folder/storage/logs and its not buildable: Permission denied

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [laravel/framework#33417]
- Laravel Version: 7.16.1
- PHP Version: 7.3.19
- Database Driver & Version: mysql

### Description:

I just noticed a buggy behaviour when generating the config:cache via php artisan config:cache
after executing it, laravel gave this error message:
There is no existing directory at /laravel_folder/storage/logs and its not buildable: Permission denied

Funny thing is: The folder is there, has the right permissions and after deleting the config cache file it works again...
![grafik](https://user-images.githubusercontent.com/21183922/86404504-c1686680-bc7d-11ea-9035-d22a1f83b745.png)

### Steps To Reproduce:

In my case:
1) php artisan config:cache
2) navigate to laravel website...

I would not write a Issue here if there weren't other persons having the problem:
https://stackoverflow.com/questions/51041196/there-is-no-existing-directory-at-storage-logs-and-its-not-buildable-permissio
As far as I can see I can't point at the error: Is it the way the config cache is generated? why does it behave different than when the config isn't cached? Why does the error point to a folder, which apparently exists?

**Comment by driesvints** [comment]
This seems like an obvious permission error. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by PatrickCaneloDigital** [comment]
Seems but it isn't...
Why does it work then when the config is not cached (without changing permissions)?
If it was a permission error I would get the exception with or without caching...

I can reproduce the error as much as I want: 
"php artisan config:cache" > Installation throws error
delete bootstrap/cache/config.php > Installation works
"php artisan config:cache" > Installation throws error

**Comment by jonathanMelly** [comment]
In case someon googles about that and arrives here like me, I figured out that the reason for that issue in my case was that the SSH connection to the shared hosting had a **chroot** and running `php artisan config:cache` from that **chrooted** environment put a wrong path in _bootstrap/config.php_... 
The solution I’m about to implement is instead of doing `php artisan config:cache` from commandline, I will do a `curl` to a _DeployController_ that calls artisan from web environment, thus do the config:cache correctly...

**Comment by shubhammalik19** [comment]
install php-dom
sudo dnf install php-dom

**Comment by jordyloeuille** [comment]
I ran into a closely related deployment issue while working on Laravel applications hosted in environments where the SSH/chroot path can differ from the actual web runtime path.

The important detail is that `bootstrap/cache/config.php` can contain values that were resolved while `config:cache` was executed. If that cache is generated in a different filesystem context, CI workspace, chroot or release directory, the cache can technically be valid PHP while still being wrong for the runtime that eventually loads it.

Rebuilding the cache directly in the final runtime environment with:

php artisan config:clear
php artisan config:cache

is still the preferred solution.

For FTP/shared-hosting deployments where running Artisan reliably after every deployment is not always possible, I maintain a package specifically for this problem:

https://github.com/Codegenie-BE/laravel-config-cache-guard

It fingerprints the configuration sources together with a runtime-bound identity and rejects a stale or relocated config cache before Laravel fully boots. It can then safely repair the cache.

The latest version also tracks successful native `config:cache` and `route:cache` commands, so a cache that was correctly rebuilt during deployment is immediately considered current.

Disclosure: I maintain the package.
