### ISSUE TITLE
PostGreSQL accepts null values for UNIQUE constraint but Laravel returns not-null constraint violations

### ISSUE THREAD

**Issue by gilles6** [laravel/framework#33424]
- Laravel Version: 7.17.2
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:

PostGreSQL UNIQUE constraint **accepts** `null` values but still, while seeding, I got this error message:

> Not null violation: 7 ERROR:  null value in column "phone" violates not-null constraint

### Steps To Reproduce:

I'm using this in my migration file:
```
$table->string('phone')->unique();
```
Adding `->nullable()` fixes the issue but should not be necessary:
```
$table->string('phone')->unique()->nullable();
```

Reference:
> PostgreSQL treats NULL as distinct value, therefore, you can have multiple NULL values in a column with a UNIQUE index. 

https://www.postgresqltutorial.com/postgresql-indexes/postgresql-unique-index/#:~:text=PostgreSQL%20treats%20NULL%20as%20distinct,creates%20a%20corresponding%20UNIQUE%20index.

**Comment by mfn** [comment]
> fixes the issue but should not be necessary

Why? What If I want unique phone numbers but not null?

I don't quite understand…

**Comment by mfn** [comment]
Laravels Blueprint defaults to `non null`, so it's imperative to write `nullable` if you don't want that. I don't see how this is different for `->unique()` from anything else?

**Comment by gilles6** [comment]
Ok, my bad, I thought `UNIQUE` included nullable. Thanks!
