### ISSUE TITLE
$items needed for manual Paginator instance must be $perPage+1 for hasMore() to work, otherwise hasMore() would always return false

### ISSUE THREAD

**Issue by drionix** [laravel/framework#33428]
- Laravel Version: 7.12.0
- PHP Version: 7.3.12
- Database Driver & Version: Not relevant

### Description:
When creating a manual paginator instance, these are the parameters required as far as I understand:
` public function __construct($items, $perPage, $currentPage = null, array $options = [])`,
with `$items` being the `array_slice()` of the data to be paginated. 

As of Laravel 7.12.0, this is the code that can be found on `Illuminate\Pagination\Paginator`
```
protected function setItems($items)
{
    $this->items = $items instanceof Collection ? $items : Collection::make($items);

    $this->hasMore = $this->items->count() > $this->perPage;

    $this->items = $this->items->slice(0, $this->perPage);
}
```

The problem lies here
` $this->hasMore = $this->items->count() > $this->perPage;`

If we are to create a page that contains 5 items, normally people will `array_slice()` their data until it contains only 5 items, thus `$items->count()` passed to Paginator will be 5.

For example, we can look at `forPage()` method for Collections.
```
$collection = collect([1, 2, 3, 4, 5, 6, 7, 8, 9]);

$chunk = $collection->forPage(1, 5);

$chunk->all();

// [1, 2, 3, 4, 5]
```

However by doing so, `$this->items->count()` will always equals to `$this->perPage`, therefore `$this->hasMore` will always return `false`.

So if we are to create a page that contains 5 items, we have to pass 5+1 items as $items to `Illuminate\Pagination\Paginator` instance for `Paginator::hasMore()` to work.

I found this out by debuging how `DB::simplePaginate()` works and found that when we `DB::simplePaginate(5)`, there are actually 5+1 items that are being passed to `Illuminate\Pagination\Paginator`.

### Steps To Reproduce:
```
new Paginator(collect([1, 2, 3, 4, 5, 6, 7, 8, 9])->slice($page-1*$perPage,$perPage),$perPage);
```
or
```
new Paginator(collect([1, 2, 3, 4, 5, 6, 7, 8, 9])->forPage($page, $perPage);$perPage);
```

Both cases will result in `Paginator::hasMore()` to always return `false`.

I don't know whether this is the intended behaviour, but it is not documented and can be confusing.

**Comment by taylorotwell** [comment]
You can use this method to manually tell the paginator if it has more pages or not:

![Uploading image.png…]()

**Comment by drionix** [comment]
I think you get me wrong. The problem is not to manually tell the paginator whether it has more pages or not, but when you need to tell you whether it has more pages or not. In this case, the paginator will always return false.
