### ISSUE TITLE
dropForeign() with multiple columns

### ISSUE THREAD

**Issue by guoyunhe** [laravel/framework#33437]
- Laravel Version: 7.18.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7.29

`dropForeign()` function supports array as parameter. I thought it means you can drop multiple foreign keys at the same time:

```
$table->dropForeign(['avatar_id', 'portrait_id']);
```

But get this error

```
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'users_avatar_id_portrait_id_foreign'; check that column/key exists (SQL: alter table `users` drop foreign key `users_avatar_id_portrait_id_foreign`)
```

But from my understanding, one foreign key is only for one column, here will never be such a `users_avatar_id_portrait_id_foreign` key.

**Comment by driesvints** [comment]
The `dropForeign` doesn't works like that. It will build up the composite key from the two columns that you're passing. Try:

```php
$table->dropForeign('avatar_id');
$table->dropForeign('portrait_id');
```

**Comment by guoyunhe** [comment]
In the documentation, it only recommends two other ways:

![image](https://user-images.githubusercontent.com/5836790/86597079-e9203d00-bfa3-11ea-9d1b-00798ca68b31.png)

If `$table->dropForeign('avatar_id');` is available, it should be the preferred way in the documentation because its syntax is more simple.

**Comment by driesvints** [comment]
I think the docs are pretty clear? Use a string if it's the exact column name or use an array if you want to resolve the column name.

**Comment by guoyunhe** [comment]
It is:
```
$table->dropForeign('posts_user_id_foreign');
```
Not:
```
$table->dropForeign('user_id');
```

**Comment by guoyunhe** [comment]
And for the array, it doesn't explain what happen if the array contains more than two elements.
