### ISSUE TITLE
foreignId method generates wrong query for SQLite

### ISSUE THREAD

**Issue by MRezaKarimi** [laravel/framework#33448]
- Laravel Version: 7.15.0
- PHP Version: 7.4
- Database Driver & Version: SQLite3 3.27.2

### Description:
When I use "foreignId" method to create foreign key in database, database throws syntax error. But creating an unsigned id field and then using "foreign" method works properly.

**Comment by driesvints** [comment]
Share your code.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
