### ISSUE TITLE
Many-to-many detach with where behaves unexpectedly

### ISSUE THREAD

**Issue by d-luk** [laravel/framework#33444]
- Laravel Version: 7.18.0
- PHP Version: 7.4.6
- Database Driver & Version: MariaDB 10.4.8

### Description:
I have a model called `User` with a many-to-many relation to `Role`. A role has a `'type'` column which can be `'admin'`.

Now I do the following:

```php
$user->roles()->where('type', 'admin')->detach();
```

Anyone would expect this to only detach the role where the `type` is `'admin'`. Instead, all the roles are detached.

This expected behaviour seems currently unsupported but it's highly counter-intuitive and misleading.

**Suggested solution:** Do not discard the provided `where` when doing a `detach`.

### Steps To Reproduce:
See description.

**Comment by driesvints** [comment]
Hey @d-luk. That's not how `detach` behaves. Actions for `attach`/`detach` are always done on the relationship as a whole. They're never scoped (and thus also not documented as such). See https://laravel.com/docs/7.x/eloquent-relationships#updating-many-to-many-relationships for how to use them.

**Comment by d-luk** [comment]
Hi @driesvints, thanks for the quick reply.

I understand that this is not how it currently works, but as I mentioned this is highly unexpected behaviour as the API provides a `where` method which is subsequently ignored. For that reason I would consider this to be a bug.

In my opinion such behaviour should either work as expected or not be part of the API at all. The current behaviour is very prone to bugs.

Please re-open this issue.

**Comment by driesvints** [comment]
What's not meant to work like this and isn't documented to be used as such isn't a bug.

**Comment by d-luk** [comment]
Fair enough, I've submitted a [feature request](https://github.com/laravel/ideas/issues/2290) instead.
