### ISSUE TITLE
Http::withBody method does not exist

### ISSUE THREAD

**Issue by aanderse** [laravel/framework#33447]
- Laravel Version: 7.15.0
- PHP Version: 7.3.16
- Database Driver & Version: N/A

### Description:
I tried to use the `withBody` method of the new `Http` facade but `tinker` told me the method doesn't exist. See https://laravel.com/docs/7.x/http-client for details.

### Steps To Reproduce:
```
php artisan tinker
>>> use Illuminate\Support\Facades\Http;
>>> Http::withBody('blah')
BadMethodCallException with message 'Method Illuminate/Http/Client/PendingRequest::withBody does not exist.'
```
:man_shrugging:

**Comment by ahinkle** [comment]
Update your Laravel version - `Illuminate\Http\Client\PendingRequest::withBody()` was introduced in v7.17.2.

https://github.com/laravel/framework/blob/6f3aa1fa539d2f30c1862ebb960c2414665cf4aa/CHANGELOG-7.x.md#v7172-2020-06-24

**Comment by aanderse** [comment]
Thank you very much @ahinkle!
