### ISSUE TITLE
php artisan storage:link uses absolute path

### ISSUE THREAD

**Issue by guoyunhe** [laravel/framework#33441]
- Laravel Version: 7.18.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7.29

After run `php artisan storage:link`, a symlink is created in `public/storage`. But it links to absolute path `/home/guo/git/webdev/laravel-test/storage/app/public`.

This has several disadvantages:

1. When you move or rename the project folder, all links broke. You have to delete and recreate them.
2. It cannot work with both local system and homestead virtual machine.
3. You cannot add absolute symlink to version control.

You won't have all these issues with relative symlink `../storage/app/public`.

**Comment by driesvints** [comment]
Lots of people have been using this for years without a problem so I don't think we should be making any changes here.

**Comment by guoyunhe** [comment]
It is just an improvement to make the existing feature even better. Lots people don't have issue doesn't mean a few people can be ignored?

**Comment by ahinkle** [comment]
Feel free to submit a PR for review or create a community package.

**Comment by siikamiika** [comment]
Also ran into this issue. Seems like it's already possible after https://github.com/laravel/framework/pull/32457 if you install `symfony/filesystem` and run `php artisan storage:link --relative`.

At least with default storage directory it would be easier to just use `ln -s ../storage/app/public/ public/storage` instead.
