### ISSUE TITLE
factory()->create() returns all rows from database instead just created

### ISSUE THREAD

**Issue by radian31337** [laravel/framework#33452]
- Laravel Version: 6.18.23
- PHP Version: 7.2.24
- Database Driver & Version: SQL Server 15.00.4043 & Driver version 17.05.0001

### Description:
Let assume database has 1000 records. 
`$model = factory(Model::class)->create();`
Creates one record, but returns all from database, so '$model->count()' is 1001.

Now we want to create 1 record with 1 relation.
`$model = factory(Model::class)->create()->each(function($item) {
factory(Related::class)->create(['some_id' => $item->id]);
});`
Code above creates one record, but returns all from database and create 1001 related instead just one.

Adding parameter with number of records solves the problem, but above is unwanted behavior.
`$model = factory(Model::class, 1)->create()->each(function($item) {
factory(Related::class, 1)->create(['some_id' => $item->id]);
});`

### Steps To Reproduce:
Database should has some records.
`
$model = factory(Model::class)->create();
dd($model->count()) // returns all from database instead one created
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
