### ISSUE TITLE
Cannot install at laravel 5.0.35

### ISSUE THREAD

**Issue by ting5875** [laravel/framework#33468]
- Laravel Version:5.0.35
- PHP Version: 5.6.40
- Database Driver & Version:

### Description:
    - illuminate/encryption v5.8.9 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.8.8 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.8.4 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.8.36 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.35 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.34 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.33 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.32 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.31 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.30 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.3 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.8.29 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.28 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.27 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.24 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.22 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.20 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.2 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.8.19 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.18 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.17 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.15 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.14 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.12 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.11 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.8.0 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.9 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.8 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.7 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.6 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.5 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.4 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.3 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.28 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.27 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.26 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.23 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.22 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.21 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.20 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.2 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.15 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.11 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.10 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.7.1 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.7.0 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.9 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.8 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.7 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.6 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.5 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.4 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.39 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.38 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.37 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.36 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.35 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.34 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.33 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.32 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.31 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.30 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.3 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.29 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.28 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.27 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.26 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.25 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.24 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.23 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.22 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.21 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.20 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.2 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.19 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.17 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.16 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.15 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.14 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.13 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.12 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.11 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.10 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.

    - illuminate/encryption v5.6.1 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.6.0 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.44 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.43 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.41 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.40 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.39 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.37 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.36 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.35 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.34 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.33 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.28 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.2 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.17 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.16 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption v5.5.0 requires php >=7.0 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption 5.7.19 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption 5.7.18 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - illuminate/encryption 5.7.17 requires php ^7.1.3 -> your PHP version (5.6.5) does not satisfy that requirement.
    - Installation request for laravel/passport 2.0 -> satisfiable by laravel/passport[v2.0.0].
    - Conclusion: remove laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.35
    - laravel/passport v2.0.0 requires illuminate/encryption ~5.4 -> satisfiable by illuminate/encryption[5.7.17, 5.7.18, 5.7.19, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/encryption v5.4.0|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.13|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.17|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.19|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.27|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.36|don't install laravel/framework v5.0.35
    - don't install illuminate/encryption v5.4.9|don't install laravel/framework v5.0.35
    - Installation request for laravel/framework (locked at v5.0.35, required as 5.0.*) -> satisfiable by laravel/framework[v5.0.35].

Installation failed, reverting ./composer.json to its original content.

### Steps To Reproduce:
composer require laravel/passport=4.0

**Comment by koenhoeijmakers** [comment]
Laravel 5.0 isn't supported anymore, you could try updating to 5.5 (LTS) or a higher supported version. 

See: https://laravel.com/docs/7.x/releases#support-policy

**Comment by GrahamCampbell** [comment]
Passport doesn't support Laravel 5.0. Pasport version 4 should work with Laravel 5.5 LTS, however.

Note that `laravel/passport=4.0` is bad syntax. You need `laravel/passport:^4.0`.

**Comment by ting5875** [comment]
noted with thanks
