### ISSUE TITLE
Running artisan causes UrlGenerator::__construct() to throw an exception when url() helper is in a config file

### ISSUE THREAD

**Issue by mpavey0** [laravel/framework#33466]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: mysql

### Description:

If the `url()` helper is called from `config/services.php`, running artisan from the console (for example, `php artisan config:cache`) generates the following error message:

```
In UrlGenerator.php line 120:

  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given,
  called in /Users/mpavey/code/weeklyemails/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 65
```

### Steps To Reproduce:

1. Create a new Laravel project (e.g., `laravel new break-artisan`)
2. Add the following code into `config/services.php`:
```php
'google' => [
    'client_id' => env('GOOGLE_CLIENT_ID'),
    'client_secret' => env('GOOGLE_CLIENT_SECRET'),
    'redirect' => url('/login/google/callback'),
],
````
3. From the console, run `php artisan`

**Comment by koenhoeijmakers** [comment]
You can't call container services from a config file as these services are not available yet when the config files are parsed.

**Comment by mpavey0** [comment]
Thanks. I wondered if that might be the case, but was surprised to note that the application itself appears to work fine with this code — it's only Artisan that crashes. 

If this behavior is, essentially, by design, might it be possible for Artisan to fail more gracefully, and/or to update the [documentation](https://laravel.com/docs/7.x/helpers#method-url) to note the restriction?

**Comment by GrahamCampbell** [comment]
Thanks for the report, however this is not a bug. You cannot use the service container at all, from within a config file. You must write plain PHP code in there.
