### ISSUE TITLE
Loading Custom Package's routes can only be done in one Service Provider

### ISSUE THREAD

**Issue by AndrykVP** [laravel/framework#33460]
- Laravel Version: 7.16.1
- PHP Version: 7.4.7
- Database Driver & Version: 10.4.13-MariaDB Homebrew

### Description:
I opened [this discussion in Laracasts](https://laracasts.com/discuss/channels/laravel/routes-from-multiple-service-providers-in-custom-package?page=1#reply=622335). It refers to a problem when creating a custom package that uses "child" service providers that are registered by the Package's main service provider like this:

```php
<?php

namespace Vendor\Package\Providers;

use Illuminate\Support\ServiceProvider;

class MainServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        // Register all the Package's Service Providers
        $this->app->register(
            FirstServiceProvider::class,
            SecondServiceProvider::class,
            ThirdServiceProvider::class,
        );  
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        // Load routes
        $this->loadRoutesFrom(__DIR__.'/../First/Routes/web.php');
        $this->loadRoutesFrom(__DIR__.'/../Second/Routes/web.php');
        $this->loadRoutesFrom(__DIR__.'/../Third/Routes/web.php');
    }
}
```
Each of these child service providers, namely `First`, `Second` and `Third`, have Routes, Traits, Commands, Models, Facades, etc, of their own and they all load without a hitch except for routes.

### Steps To Reproduce:
In a folder structure like this:

```yaml
src/
    First/
        Routes/
            web.php
    Second/
        Routes/
            web.php
    Third/
        Routes/
            web.php
    Providers/
        FirstServiceProvider.php
        SecondServiceProvider.php
        ThirdServiceProvider.php
        MainServiceProvider.php
```
Register only the `MainServiceProvider.php` in the package's `composer.json`:

```json
"extra": {
    "laravel": {
        "providers": [
            "Vendor\\Package\\Providers\\MainServiceProvider"
        ],
    }
}
```

Load all routes from `MainServiceProvider.php` in the `boot()` method, as demonstrated in the code above, and run `php artisan route:list` to verify that the routes have been loaded correctly.

They should be.

Now comment out all three `loadRoutesFrom()` methods from `MainServiceProvider` and copy them to their respective provider's `boot()` method. When running `php artisan route:list` again, only the routes from the first registered service provider will be loaded. In this example, that would be the routes from `FirstServiceProvider.php`.

This is strange to me, since I can load and bind other things to Laravel's Service Container in each child provider, such as loading migrations and binding singletons; but not routes.

**Comment by sebdesign** [comment]
You can't call `$this->app->register()` with multiple (provider) arguments. The `register` method accepts the `$provider` and a `$force` flag. Now you are only registering the first provider, and only the first routes from the first provider are registered.

You need to register each provider explicitly:

```php
$this->app->register(FirstServiceProvider::class);
$this->app->register(SecondServiceProvider::class);
$this->app->register(ThirdServiceProvider::class);
```

**Comment by AndrykVP** [comment]
@sebdesign Thank you, that fixed it. I found the code to register multiple provider arguments in the same method in some tutorial and thought it worked fine. But registering them individually worked perfectly, thanks a lot
