### ISSUE TITLE
createOrUpdate model method doesnt work with SET type

### ISSUE THREAD

**Issue by notf0und** [laravel/framework#33465]
- Laravel Version: 6.18.22
- PHP Version: 7.3.17-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: MySQL 14.14 Distrib 5.7.29

### Description:
When try to use static method updateOrCreate on a model with a SET type attribute, there is no way to make it work

### Steps To Reproduce:
Create a migration with a SET type field
```php
$table->set('flavors', ['strawberry', 'vanilla']);
```
And try to use updateOrCreate method on a model:

```php
Model::updateOrCreate(['id' => 1], ['flavors' => 'strawberry, vanilla']);
```
Returns:

Warning: 1265 Data truncated for column 'flavors' at row 1 at /home/vagrant/code/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)

**Comment by sergiy-petrov** [comment]
@notf0und try to remove the odd space:

`'strawberry, vanilla'` ->` 'strawberry,vanilla'`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
