### ISSUE TITLE
Chrome Plugins firing extra Requests to Laravel.

### ISSUE THREAD

**Issue by designbyjr** [laravel/framework#33476]
- Laravel Version: 7.19
- PHP Version: 7.4.7
- Database Driver & Version: MYSQL v8.0

### Description:
When setting up a mailable to be sent after a request in a controller, Chrome Version 83.0.4103.116 (Official Build) (64-bit) with Grammarly plugin, fires 2 requests instead of one. Therefore causing 2 mailable emails to be sent.

### Steps To Reproduce:
This code will fire twice because of 2 requests, but one request is not from the user but the plugin.
`Route::get("/testone",function (){
    $model = EmailVoucher::find(1);
    $build = new ClientVoucherMail($model);
    Mailx::mailer('mailgun')->to("XXXXXXX@gmail.com")
        ->send($build);
});`

**Comment by GrahamCampbell** [comment]
Thanks for the report. You should not be sending emails on a GET request. GET, HEAD, OPTIONS should all be side-effect free. Thus, I don't think this is a bug in either Laravel or Grammarly.

**Comment by GrahamCampbell** [comment]
If this is happening for other kinds of requests, like POST, please report this bug to Grammarly, and/or implement request idempotence (like Stripe do) so requests can't be replayed by mistake.
