### ISSUE TITLE
Bug in EncryptCookies::decrypt error handling.

### ISSUE THREAD

**Issue by bryan-kramer** [laravel/framework#33474]
- Laravel Version: 7.19.0
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:

If there is a cookie with an invalid payload, the error handler call `$request->cookies->set($key, null);` triggers a Symfony depreciation exception that aborts cookie processing:

```
ErrorException: Since symfony/http-foundation 5.1: Passing "null" as a 2nd Argument to "Symfony\Component\HttpFoundation\InputBag::set()" is deprecated, pass a string or an array instead. in /home/dm.internal/files/_webs/silvalea/vendor/symfony/deprecation-contracts/function.php:25
```

### Steps To Reproduce:

1. Have a Laravel application create a cookie outside of Laravel's cookie mechanism so that the payload is invalid.
2. Visit a page in the app.

**Comment by GrahamCampbell** [comment]
Please turn off deprecation errors on your production server. They are not errors.
