### ISSUE TITLE
Reset Password Notification failes when using of createUrlUsing method

### ISSUE THREAD

**Issue by voyula** [laravel/framework#33477]
- Laravel Version: 7.19.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 8.0.18

### Description:

When i use createUrlUsing method with Laravel Queue, occurs Job Failed error.

I think Laravel Queue cannot serialize this callable/Closure method;
Illuminate\Auth\Notifications\ResetPassword
```php
public static $createUrlCallback;
```

My App\Models\User.php file;
```php
....
public function sendPasswordResetNotification($token)
{
    $notification = new ResetPasswordNotification($token);
    $notification->createUrlUsing(function ($notifiable, $token) {
        return url(route('user.password.reset', [
            'token' => $token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));
    });
    $this->notify($notification);
}
....

```

**Comment by taylorotwell** [comment]
Do not queue password reset notifications.

**Comment by voyula** [comment]
@taylorotwell Why?

**Comment by voyula** [comment]
I want to balance.
