### ISSUE TITLE
Job timeout isn't throwing an exception

### ISSUE THREAD

**Issue by glamorous** [laravel/framework#33473]
- Laravel Version: 7.18.0
- PHP Version: 7.4.2
- Database Driver & Version: /

### Description:
When a long job has a specific timeout, then no exception is thrown. There is only an exception if the job doesn't have a timeout but for example Horizon has a timeout. Therefore if you say a job can only have maximum 1 exception but can try 10 times but the timeout for one job run is 100s, then it will try 10 times for 100s every time. I expect an exception to be thrown because all the retries will fail because of the timeout for this long job.

Real life example: When using cache locks in job to release a job, the lock can't be released because there's no exception and the "failed" method is not called so you can't cleanup the lock. The second try for the job, the lock is still set but you can retrieve it anymore because that retried job isn't the owner. Therefore job will still retry x amount of times, then fails, and then forceReleased the lock. Not the expected behaviour.

### Steps To Reproduce:

1.  Create job with a sleep for 20s
2. Set the job timeout to 10s
3. Set amount of tries to 6
4. Set amount of maximum exceptions to 1
4. Dispatch the job
5. 60s will pass and the job will eventually fail after 6 tries with MaxAttemptsExceededException

I guess this is a bug, because the failed job will never be successful for the timeout that has been set to the job. Now the function `markJobAsFailedIfWillExceedMaxAttempts` has been called by `registerTimeoutHandler` (in src/Illuminate/Queue/Worker.php). The name of called function (`markJobAsFailedIfWillExceedMaxAttempts`) indicates it should only check if it exceeds the max attempts. Therefore instead of calling this method it should throw a new 'jobTimedOutException' (or something similar) so the user is in control to catch it or to let the job fail and look at the tries and maximum exceptions, the default behaviour of Laravel.

I would expect the same behaviour as when Horizon-process has been killed by the specified timeout of the worker. Then the default Laravel behaviour is working fine.

If wanted, I can submit a PR with a proposal.

**Comment by taylorotwell** [comment]
So... what were you expecting to happen? I'm not clear on that.

Were you expecting it to only attempt once because of "maximum exceptions"?

**Comment by themsaid** [comment]
Not clear what you expect here. You want to consider a job timeout as an exception and fail right away since you have maxExceptions=1?

**Comment by glamorous** [comment]
Sorry for the misunderstanding. The expectation was the same behaviour like hitting the timeout only in horizon/queue command. There it will fail after one long attempt that is hitting the timeout of the process. So yes, failing because of the maxExceptions=1.

The `registerTimeoutHandler` uses the function `timeoutForJob` on the Worker-class:

```
protected function timeoutForJob($job, WorkerOptions $options)
{
        return $job && ! is_null($job->timeout()) ? $job->timeout() : $options->timeout;
}
```

But the behaviour is different in the end. When horizon kills the process, you get the wanted exception right after hitting the timeout (so no additional retries because of the maxExceptions variable set to 1) and the failed method on the job is called (when it exists). The latter isn't happen when set a timeout on the job that is smaller then horizon timeout (like advised in the documentation).

**Comment by themsaid** [comment]
Sorry I still don't understand. What do you mean by the Horizon timeout?

What is the bug here? Is it that the job retries while you have maxExceptions=1?

**Comment by glamorous** [comment]
In Horizon you can set a timeout for the supervisor. If no job timeout is specified, the timeout set by the worker (Horizon) is used in the function `timeoutForJob` (see above). The difference in behaviour is, that on that moment when there's a timeout at "horizon/queue" level, an exception is thrown (the expectation), but not when the job itself is timed out when the job has a timeout for itself. (not correct behaviour). Therefore you can't release a cache lock or something else (in failed method) when you're job has been timed out because of the timeout set in the job-class.

In my opinion instead of calling the `markJobAsFailedIfWillExceedMaxAttempts` in in src/Illuminate/Queue/Worker.php:162 it should it should throw a timeout exception so as an develop you have control of the timeout of your job.

In the documentation https://laravel.com/docs/7.x/queues#cleaning-up-after-failed-jobs :

> You may define a failed method directly on your job class, allowing you to perform job specific clean-up when a failure occurs. This is the perfect location to send an alert to your users or revert any actions performed by the job. The Exception that caused the job to fail will be passed to the failed method.

Problem is the "cleanup" can only be done after the amount of retries in case of a timeout due to job timeout.

If it's "work as intended". How can you release a cache-lock if the job is running too long, so it goes in timeout. Without waiting to al its retries happened (because maxExceptions is not taken into account for a timeout)

**Comment by themsaid** [comment]
The `failed()` method is only called when the job runs out of tries, this is the expected behaviour. You can clear the lock when the job starts again to use a backoff that pushes the job back to queue to be retried after the lock expires.

**Comment by glamorous** [comment]
Why is there then a change in behaviour if no timeout is set? When the supervisor kills the process by hitting the timeout, a retry isn't happen.

Can you give an example for the cache lock. Our cache lock hasn't an expire time. We use it to fulfill the jobs in sync for specific client and release it to the queue if lock is already used by other job. But when the job with the lock hits its own timeout, then retries can't require the lock. This is also not wanted because the job hits the timout once, and will timeout all the other times too. How can this be managed? If timeout happend, it shouldn't retry again and use resources.

**Comment by themsaid** [comment]
I think you're confusing things. I suggest you try post a sample code on the forums and see if people can help explain what's going on in your job.

As for Horizon, the timeout works the same as in a regular worker. When a timeout happens the worker will exit but the job is still in queue and is going to be retried if you have tries available.

**Comment by taylorotwell** [comment]
It would be a pretty huge change of behavior for us to start calling failed() for every timeout? We have never before called `failed` multiple times for the same job (once for each timeout if it times out 3 times)...

**Comment by taylorotwell** [comment]
Converting to discussion pending inactivity.
