### ISSUE TITLE
Carbon date/time differs from return to dd()

### ISSUE THREAD

**Issue by hmrneves1** [laravel/framework#33475]
- Laravel Version: 7.16.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
After setting up the config/app.php with timezone 'Europe/Lisbon', I tried to get the date values using Carbon::now() and they are always wrong.

With this, we can't compare dates since the date isn't the real one. Example:
`
if (Carbon::parse($subscriber->token_expire_date)->gt(Carbon::now()))
{
	return $this->response(false, 410, config('http_responses.410'), []);
}
`

### Steps To Reproduce:

Getting wrong values (minus 1 hour):
rerturn Carbon::now();

Getting proper values:
dd(Carbon:now());

### Discussions

Mine: https://stackoverflow.com/questions/62798761/laravel-carbon-timezone
Another developer: https://stackoverflow.com/questions/62758417/laravel-7-carbon-return-ever-time-as-utc/62758619

**Comment by GrahamCampbell** [comment]
> and they are always wrong.

This won't be the case. You will just need to be very careful about which things are UTC vs local.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by hmrneves1** [comment]
> > and they are always wrong.
> 
> This won't be the case. You will just need to be very careful about which things are UTC vs local. Probably `dd` is showing the local time.

Hmm ye, dd() is actually the right date/hour. Since the project are local, the date/time should be equal right? Besides that, I manually defined the timezone.

**Comment by vmoos12** [comment]
am on laravel 7 and have same issue, now() function always return UTC even am configured 'timezone' => 'Africa/Cairo',..
how should we solve this issue.

thanks in advance
