### ISSUE TITLE
Passing attributes to factory builders do not prevent the execution of code in the factory definition 

### ISSUE THREAD

**Issue by IdrisN** [laravel/framework#33471]
- Laravel Version: 7.18.0
- PHP Version: 7.4.6
- Database Driver & Version: postgres 12.3

### Description:

You have following factory:
```php
$factory->define(Setting::class, function (Faker $faker) {
  return [
    'user_id' => factory(User::class)->create(),
    ...
  ];
});
```

Executing `factory(Setting::class)->create(['user_id' => 42])` causes the creating of a user model although the `user_id` attribute should override the `user_id` definition.

#### Background/Thought Process

I am trying to have factories which are independent and closed. 
E.g. in the scenario above the user model must have a settings model which belongs to the user. Therefore the user factory should create a settings model if needed and the settings factory should create the user model it belongs to if no user_id is given. 
This is crucial for testing purposes. If i want to test the user model, i should be able to just use the user factory to create an instance without knowing what other models belong to the user and potentially need to be created as well. Similarly, if i want to test the settings model, it should be enough to just create an instance with the settings factory without creating all models the settings model belongs to manually. This is the reason why the settings factory above has the creation of a user instance in the factory definition.

The achieve this, i wrote the following factories:

```php
// Settings factory

$factory->define(Setting::class, function (Faker $faker) {
  return [
    'user_id' => factory(User::class)->create(),
    ...
  ];
});


// User factory

$factory->define(User::class, function (Faker $faker) {
  return [
    ...
  ];
});

$factory->afterCreating(User::class, function ($user, $faker) {
  factory(Setting:class)
    ->create([
      'user_id' => $user->id,
      ...
    ]);
});
```

Using the user factory in this case causes an infinite loop because the creation of a user triggers the creation of a settings model. And although the `user_id` is given to the settings factory, a creation of a new user instance is triggered by the settings factory.

**Comment by sergiy-petrov** [comment]
![image](https://user-images.githubusercontent.com/8986207/86926954-6205cd00-c13b-11ea-9112-ab1bcce0a2d0.png)
https://laravel.com/docs/6.x/database-testing#writing-factories

You could either pass factory(User::class) (so without create() method) or closure as mentioned in the documentation. I've checked and in both cases the odd row in users table won't be inserted.

![image](https://user-images.githubusercontent.com/8986207/86927322-dd677e80-c13b-11ea-9473-ff8e6da5f97d.png)

**Comment by driesvints** [comment]
Please see the answer above.
