### ISSUE TITLE
Reflector needs to convert "parent" as well as "self"

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#33483]
Kinda an edge case. I'll fix this soon.

**Comment by GrahamCampbell** [comment]
FYI, this is valid PHP:

```
<?php

namespace Foo;

class Foo {}

class Bar extends Foo
{
    function f(parent $x) {}
}

(new Bar)->f(new Foo());
```

Laravel should be able to method injection on `Bar::f`, by looking up `Foo` in the container, but currently it looks for the string `parent`, by mistake.

**Comment by ryangjchandler** [comment]
Is this a problem for 6.x, since running this code in Tinkerwell on 7.x works perfectly fine.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/41837763/87045490-df8b1500-c1ef-11ea-9e17-20da1acf39a9.png">

**Comment by GrahamCampbell** [comment]
Maybe you have an old version of 7.x, because the reflector code in the latest 6.x is identical to that in 7.x.

**Comment by ryangjchandler** [comment]
Yeah that was it - Tinkerwell's default app is running an older version, just tested on 7.19 and fails.
