### ISSUE TITLE
[6.18.24] Undefined offset: 0 in SqlServerProcessor.php line 24

### ISSUE THREAD

**Issue by 2acode** [laravel/framework#33485]
- Laravel Version: 6.18.24
- PHP Version: 7.2.24
- Database Driver & Version: FreeTDS driver v1.00.82 | Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64)

### Description:
When i try to add a new record to the database i get this message: "Undefined offset: 0 in SqlServerProcessor.php line 24".
With v6.18.23 it works properly.

Commit [6.x] SQL Server fix backport #33453

### Steps To Reproduce:
Eloquent:
    $myModel = new \Erp\Models\MyTable;
    $myModel->field = 'text';
    $myModel->save();

Query builder:
    $id = DB::table('mytable')->insertGetId(['field' => 'text']);

**Comment by rodrigopedra** [comment]
Hi @2acode 

I visited http://www.freetds.org/ to download the database driver, but there they report the stable version is 1.2.3 and I couldn't find any reference to v7.3

Got to that site from their github repo: https://github.com/FreeTDS/freetds

Is you freeTDS driver from a different vendor? How can I get that version for testing?

**Comment by 2acode** [comment]
I'm sorry, my mistake:
freetds v1.00.82
ubuntu 18.04 LTS

**Comment by rodrigopedra** [comment]
Thanks, I figured out the 7.3 is the connection version, never used freeTDS before. I am trying to figure out how to solve the issue for both drivers (freeTDS and the official one) as that PR was sent to fix another issue.

**Comment by driesvints** [comment]
We've reverted the pr that caused this. Will be released on Tuesday or maybe sooner.
