### ISSUE TITLE
DB::()->delete() returns zero always

### ISSUE THREAD

**Issue by omidMolaverdi** [laravel/framework#33491]
Laravel 6.18.24 
PHP Version: 7.4
Database Driver & Version: Mysql

Thanks for developing Laravel.

I have recently updated to the Laravel 6.18.24 and realised that DB::()->delete() always returns zero. It used to be right but seems problematic with the new update.

Here is the code that I use:

```
 $dlt = DB::table('members')
            ->whereIn('id', array_XXX)
            ->where('id2', YYY)
            ->delete();
dd($dlt);
0
```
I should add that the deletion is successful however the return value in `$dlt` is zero, then any check on it fails and ends up misleading message to the client.

I am also aware of the bug in update() that returns zero if there is nothing to update. Please can you kindly take a look at this as well?

**Comment by driesvints** [comment]
I get the number of deleted records back when I try to run a delete statement.

**Comment by omidMolaverdi** [comment]
Thanks. Do you have the same version of Laravel as I have?

**Comment by driesvints** [comment]
Yes.

**Comment by omidMolaverdi** [comment]
Its weird. do you use ->where**In**('id', array_XXX) or where?

**Comment by driesvints** [comment]
Tried both.

**Comment by omidMolaverdi** [comment]
puzzled. Do you have any guess of the reason? I use redis cache, could it be a reason?

**Comment by omidMolaverdi** [comment]
out of curiosity what is the output of whereIn()->delete(). Is it an array of record indexes?

**Comment by driesvints** [comment]
@omidMolaverdi it's best that you try a support channel at this point as this issue tracker is for reporting bugs:
- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by omidMolaverdi** [comment]
Okay thanks a lot.
