### ISSUE TITLE
Wrong custom validation message is given when validating for nested arrays with the same key.

### ISSUE THREAD

**Issue by juliomotol** [laravel/framework#33494]
- Laravel Version: 7.19.0
- PHP Version: 7.3.12
- Database Driver & Version: N/A

### Description:

Wrong custom validation message is given when validating for nested arrays with the same key. I have a nested array that both have the same keys. Below is a sample of the json I'm sending.

```json
{
    "users": [
        {
            "name": "Julio Motol",
            "posts": [
                {
                    "name": ""
                }
            ]
        }
    ]
}
```

We can see that both `user` and `user.*.post` have a `name` property.

In my validator, I'm setting my custom message like this:
```php
$validator = Validator::make(
    $request->all(),
    [
        'users.*.name' => ['required'],
        'users.*.posts.*.name' => ['required'],
    ],
    [
        'users.*.name.required' => 'user name is required',
        'users.*.posts.*.name.required' => 'post name is required',
    ]
);
```

When I send an empty name for a post, it returns the message for `users.*.name.required` instead of `users.*.posts.*.name.required`.

#### My `routes/api.php`
```php
Route::middleware('api')->post('/test', function (Request $request) {
    $validator = Validator::make(
        $request->all(),
        [
            'users.*.name' => ['required'],
            'users.*.posts.*.name' => ['required'],
        ],
        [
            'users.*.name.required' => 'user name is required',
            'users.*.posts.*.name.required' => 'post name is required',
        ]
    );

    if($validator->fails()){
        return $validator->errors();
    }

    return response('passed!');
});
```

#### My Postman test
![image](https://user-images.githubusercontent.com/21353103/87122038-a9649880-c2b6-11ea-950c-e6408f3ec704.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by juliomotol** [comment]
After looking through how the Validator works, I found that the problem is with FormatMessage.php@L101

https://github.com/laravel/framework/blob/5b47c76ca3e3c43be71ebb25e02c6b79b2bb2632/src/Illuminate/Validation/Concerns/FormatsMessages.php#L101

I added a `Log::debug()` before and after that line like so:
```php
foreach ($keys as $key) {
    foreach (array_keys($source) as $sourceKey) {
        \Log::debug($key.' | '.$sourceKey);        // This will log "<the key we're looking for> | <the current key in custom messages>"
        if (Str::is($sourceKey, $key)) {           // The suspected culprit.
            \Log::debug($source[$sourceKey]);      // If it passed, this will be logged.
            return $source[$sourceKey];
        }
    }
}
```
![image](https://user-images.githubusercontent.com/21353103/87154585-134b6500-c2ec-11ea-8c83-3d32c40a4cc1.png)

And surely enough after running the request, my log file has these entries:
```
[2020-07-10 12:22:45] local.DEBUG: users.0.posts.0.name.required | users.*.name.required
[2020-07-10 12:22:45] local.DEBUG: user name is required
```
Now, knowing how it works, I tried putting the message for `users.*.name` at the _bottom_ and it works as intended.

I also looked deep in the `Str::is()` and it seemed that when doing `Str::is('users.*.name.required', 'users.0.posts.0.name.required')`. it returns `true` because the pattern its using the check is `users\..*\.name\.required`. It is indeed a match because the `.*` catches the `0.posts.0` in our string. But we don't want this behavior since we're checking deeper in to the array.
https://github.com/laravel/framework/blob/5b47c76ca3e3c43be71ebb25e02c6b79b2bb2632/src/Illuminate/Support/Str.php#L265

### Verdict

I'm pretty confident that this is a bug. But for now, as a workaround, I'll place the top level array validation messages at the bottom part of the messages array for the Validator.

**Comment by driesvints** [comment]
Hey @juliomotol. I indeed think this is a bug. I can't find anything in the docs that say you can't use this.

**Comment by taylorotwell** [comment]
Fixed on next patch release.

**Comment by juliomotol** [comment]
Thank you Laravel Team ❤️

**Comment by KryDos** [comment]
hey everybody, 
it seems like the fix broke our app a bit. 
Here is the example. Assume the data is structured like this:

```
{
  "user": {
     "level1": {
        "level2_1": {
           "level3": "value"
         },
       "level2_2": {
          "level3": "value"
       }
     }
  }
}
```
We define a validation message key for that data structure like this:

```
"user.level1.*.required" => "Custom message" 
```

It worked previously but now we have to use this to make it work:

```
"user.level1.*.*.required" => "Custom message" 
```
(additional asterisk added). 

It's totally fine to update our custom messages but sometimes we don't know how deeply nested the data is. So that previous behavior of how asterisk worked was super helpful. 

Is there any recommendations on how I can bypass the new change? It seems like whenever I use asterisk I'm getting into that new IF that was added here - https://github.com/laravel/framework/commit/6615371d7c0a7431372244d21eae54696b3c19f2

Thanks

**Comment by driesvints** [comment]
@KryDos actually the new behavior makes more sense. level2_1 is the first asteriks and level3 the second one.

**Comment by KryDos** [comment]
@driesvints you're right, the new behavior looks more explicit but it is pretty different from what it was before. As I mentioned sometimes we just don't know how deeply the data is nested. 

Do you know if there is any way for me to make custom FormatsMessages trait (or probably make custom Validator class with redefined `getFromLocalArray` method)?

**Comment by driesvints** [comment]
Not at the time sorry.
