### ISSUE TITLE
Getting unauthenticated json message on Logout & Login with different credentials

### ISSUE THREAD

**Issue by hossein-zare** [laravel/framework#33505]
- Laravel Version: 7.17.2
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 10.4.11-MariaDB

### Description:
I tried logging out and logging in with a different account, I'm getting the `unauthenticated` JSON message.
I'm not able to login at all.
I'm also using the `database` session driver.

### Steps To Reproduce:
Log out and Login with different credentials.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
