### ISSUE TITLE
Changes applied to request data does not effect!

### ISSUE THREAD

**Issue by soheilrt** [laravel/framework#33509]
- Laravel Version: 7.19.0
- PHP Version: 7.4
- Database Driver & Version: mysql 5.7.30

### Description:
I was trying to normalize my data through a request file after validation passed and suddenly I figured out that manipulated data are only accessible from `$request->{variable}` and when I'm trying to access data via `$request->get('<variable name>')` it returns original data. Is this behavior normal?

### Steps To Reproduce:

My Request file:
```php
class LoginConfirmRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'mobile' => ['required', 'numeric', 'regex:/^((\+989|09)\d{9})$/',],
            'verifyCode' => ['required', 'numeric', 'regex:/^(\d{5})$/'],
        ];
    }

    protected function passedValidation()
    {
        $this->merge(['mobile' => preg_replace('/^\+989(\d*)/', '09$1', $this->get('mobile'))]);
    }
}
```

my controller:
```php

    /**
     * @param LoginConfirmRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function confirm(LoginConfirmRequest $request)
    {
         $request->get('mobile'); // original data
         $request->mobile; //manipulated data
    }

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
