### ISSUE TITLE
Blade Extends Loop

### ISSUE THREAD

**Issue by rafaelbreno** [laravel/framework#33508]
- Laravel Version: 7.16.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.20
- Ubuntu 20.04 (Idk if it's important)

### Description:
There's a little bug with Laravel Blade when you extends the blade components in itself, It makes the computer freeze(In my case) and to back to normal needs to unplug from the energy source.

### Steps To Reproduce:
**Please Be Careful** this just **froze** my laptop(kinda old but it still works).
1. Create a Route just to render a blade view:
```php
Route::get('/', function () {
    /* This will render a file in:
    * /foo/bar/laravel-project/resources/views/test.blade.php
    */
    return response()->view('test');
});
```
2. Then create the `test.blade.php` file
`
@extends('test')
`
3. Then access you this route on your browser, FYI I'd tried to test this by accessing it on my cellphone with help of nGrok, and it still froze my computer.

**Comment by voyula** [comment]
Because you are extending current blade component and occurs infinite loop.

This is not bug, this is an unreasonable coding.

**Comment by koenhoeijmakers** [comment]
Do you _not_ have a memory limit?

**Comment by Thefakedeal** [comment]
Thank you for this issue. I spent 2 days searching what I did wrong when every thing seems ok turns out I accidentally extended the same view.
