### ISSUE TITLE
Redis scan should always return the $cursor.

### ISSUE THREAD

**Issue by owlwang** [laravel/framework#33542]
- Laravel Version: 7
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:

As the document say :

_**While SCAN does not provide guarantees about the number of elements returned at every iteration...
Basically with COUNT the user specified the amount of work that should be done at every call in order to retrieve elements from the collection.**_

In Redis, the scan command may not return the result but it will always return the cursor.
Therefore, it may encounter the situation that the result is empty but the cursor is not 0. (as the image show)

<img width="436" alt="image" src="https://user-images.githubusercontent.com/13383393/87501358-74c75700-c691-11ea-9e18-81518aca16a5.png">

The empty result isn't mean there's no result of this match pattern, it need to query more times or need bigger count.

Currently, the scan function is:
```php
    public function scan($cursor, $options = [])
    {
        $result = $this->client->scan($cursor,
            $options['match'] ?? '*',
            $options['count'] ?? 10
        );

        return empty($result) ? $result : [$cursor, $result];
    }
```

When the result is empty but the cursor is not 0, it will always return an empty array, and the cursor will **not changed**, it will cause client can not get the next cursor.

### My solution:
1. Get the references of the cursor. `public function scan(&$cursor, $options = [])`
2. Always return cursor. `return [$cursor, $result];`
3. `return empty($result) && $cursor === 0 ? $result : [$cursor, $result];`

### Ref:

[https://redis.io/commands/scan](https://redis.io/commands/scan)

**Comment by HongjiangHuang** [comment]
In order to ensure compatibility, it is not good to modify the `scan` function

**Comment by HongjiangHuang** [comment]
Seems like this can solve your problem very simply
```
[$cursor, $result] = $this->scan($cursor, $options) ?: [$cursor, []];
```

**Comment by owlwang** [comment]
**Yes, modify the scan function is not a good way.**

As I mentioned before, when you do a scan it will return two values, cursor and result. 
When the cursor = 0 it means reach the end of the query.

Let's imaging we want to query something:
you get cursor=1638400 and result = []
But the scan function will only return an empty array, no cursor. The user cannot get next query cursor.

If you set `$cursor=NULL`, after execute your code, the $cursor still NULL. It was not changed to the correct value. You cannot get the correct cursor to do next query.

**Comment by taylorotwell** [comment]
PR what you want to do to the `master` branch with a thorough explanation of why it is needed and what the breaking changes are.

**Comment by taylorotwell** [comment]
Fixed on next major release to always return [$cursor, $results];

**Comment by taylorotwell** [comment]
Fixed on next patch release.
