### ISSUE TITLE
Session lost after redirection from another domain

### ISSUE THREAD

**Issue by xswebfr** [laravel/framework#33540]
- Laravel Version: 7.19.1
- PHP Version: 7.3.6
- Database Driver & Version: Mysql 8

### Description:

It seems like sessions are lost after a redirect from another domain.

### Steps To Reproduce:

1. Redirect with javascript from another domain to an existing route inside your project.
2. Inside the controller : add something to session and make redirect to another route.
3. Your "something" doesn't exist!

### Notes

In my case : I have sent an email with signed link, when the signature is invalid it must redirects to homepage with a "notification" array :
```
if (!$request->hasValidSignature()) {
    return redirect()->route('home')->with('notification', $notificationData);
}
```

When I go to this page directly and without signature : it works. No problem!

But links are rewriten inside my sent emails by my MTA (SendInBlue).
The new link redirect to a empty page (MTA website) who instantly redirect in javascript to my initial link.
After the redirection : "notification" doesn't exist in session.

**Comment by driesvints** [comment]
Looks like a support question. Moving to discussions.
