### ISSUE TITLE
Query Builder::tap method not consistent with collection or helper

### ISSUE THREAD

**Issue by hackel** [laravel/framework#33550]
- Laravel Version: 7.20.0
- PHP Version: 7.4.8

### Description:
The `tap` method, in both Collection and Support/helpers, returns the value that it was called with, ignoring the return value of the closure.  I believe this is the expected behaviour.  However, because the `BuildsQueries::tap` method defers to `when`, it will actually only return the expected value if the closure returns falsey/void.

### Steps To Reproduce:

I modified the existing test in `\Illuminate\Tests\Database\DatabaseConcernsBuildsQueriesTraitTest` to illustrate the issue:
```php
    public function testTapCallbackInstance()
    {
        $mock = $this->getMockForTrait(BuildsQueries::class);
        $result = $mock->tap(function ($builder) use ($mock) {
            $this->assertEquals($mock, $builder);
            return 1;
        });
        $this->assertEquals($mock, $result);
    }
```
This fails because `$result === 1` here, when it should not.  This may seem a bit contrived.  The reason this issue popped up for me is I was using arrow functions, which *always* return a value.  e.g.
```php
    public function testTapCallbackInstance()
    {
        $mock = $this->getMockForTrait(BuildsQueries::class);
        $result = $mock->tap(fn ($builder) => 1);
        $this->assertEquals($mock, $result);
    }
```
The reasoning here is that I want to be able to chain tap calls regardless of what they return.
```php
User::where(...)
    ->tap(fn ($query) => collect([1,2])->each(fn ($i) => $query->orWhere('i', $i)))
    ->orWhere(...)
    ->get();
```
This fails because `orWhere` is called on the Collection instance instead of the Builder.

It's a simple fix, unfortunately this method has been around in its current form since v5.4.16 and fixing it would be a breaking change.

**Comment by driesvints** [comment]
We could fix this but probably needs to go to master.

**Comment by taylorotwell** [comment]
PR welcome on master.
