### ISSUE TITLE
Email validation not working (RFCValidation)

### ISSUE THREAD

**Issue by kenaths** [laravel/framework#33565]
- Laravel Version: 5.8.38
- PHP Version: 7.3.2
- Database Driver & Version:

### Description:
It gives an error when try to validate an email. Below are the details.

exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/var/www/sso/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php"
line: 654
message: "Class 'Egulias\EmailValidator\Validation\RFCValidation' not found"

### Steps To Reproduce:
Create fresh project 
Try to create a user with an email

**Comment by rimace** [comment]
That version is not supported anymore. 
Did you test with with an supported version, 6 or 7?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
