### ISSUE TITLE
Unable to extend 'redirector' service

### ISSUE THREAD

**Issue by yuriy-martini** [laravel/framework#33577]
- Laravel Version: v7.20.0
- PHP Version: 7.4.3
- Database Driver & Version: -

### Description:

Receiving exception when trying to extend "redirect" service of Laravel:
`Argument 2 passed to Illuminate\Routing\ResponseFactory::__construct() must be an instance of Illuminate\Routing\Redirector, instance of App\Redirector given, called in /home/yuriy/Work/laravel-demo/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 168
`

### Steps To Reproduce:
1. create `\App\Redirector.php` class:
```php
<?php

namespace App;

class Redirector
{
    /**
     * @var \Illuminate\Routing\Redirector|mixed
     */
    protected $baseRedirector;

    public function __construct($baseRedirector)
    {
        $this->baseRedirector = $baseRedirector;
    }

    /**
     * Create a new redirect response to the "home" route.
     *
     * @param  int  $status
     * @return \Illuminate\Http\RedirectResponse
     */
    public function home($status = 302)
    {
        // conditionally add custom logic or fall back to $baseRedirector

        return $this->baseRedirector->home($status);
    }

    /**
     * Pass dynamic methods call onto base Redirector.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, array $parameters)
    {
        return call_user_func_array([$this->baseRedirector, $method], $parameters);
    }
}

```
2. register in `\App\Providers\AppServiceProvider.php`:
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    //...
    public function register()
    {
        $this->app->extend('redirect', function ($baseRedirector) {
            return new \App\Redirector\Redirector($baseRedirector);
        });
    }

    //...
}

```
3. use `response` helper in `routes/web.php`:
```php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return response()->json(['message' => 'OK']);
});

```
4. navigate to http://localhost:8000

**Comment by yuriy-martini** [comment]
same as #33530

**Comment by driesvints** [comment]
> Argument 2 passed to Illuminate\Routing\ResponseFactory::__construct() must be an instance of Illuminate\Routing\Redirector, instance of App\Redirector given, called in /home/yuriy/Work/laravel-demo/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 168

It's pretty clear that you're not passing the correct type here.

**Comment by yuriy-martini** [comment]
Sorry, your explanation is not enough clear. Why I should not be able to extend  Laravel's Redirector service?

**Comment by driesvints** [comment]
You're passing in the wrong type. Your redirector probably doesn't extends the correct class. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by rodrigopedra** [comment]
Hey @yuriy-martini 

In your code sample you are decorating the base redirector, not extending it.

As in several places the Redirector is type-hinted you should extend it as a sub-class not as a decorator.

Try this:

~~~php
<?php

namespace App;

class Redirector extends \Illuminate\Routing\Redirector
{
    /**
     * Create a new redirect response to the "home" route.
     *
     * @param  int  $status
     * @return \Illuminate\Http\RedirectResponse
     */
    public function home($status = 302)
    {
        // conditionally add custom logic or fall back to $baseRedirector

        return parent::home($status); // calls base class redirector
    }
}
~~~

~~~php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    //...
    public function register()
    {
        $this->app->extend('redirect', function ($redirector) {
            return new \App\Redirector($redirector->getUrlGenerator());
        });
    }

    //...
}
~~~

This way your instance will satisfy any class or methods that type-hint the base `Redirector` class.

I guess maybe you could use the service container's `->singleton()` or `->bind()` methods instead of `->extend()`, but that should work.

**Comment by yuriy-martini** [comment]
> Hey @yuriy-martini
> 
> In your code sample you are decorating the base redirector, not extending it.
> 
> As in several places the Redirector is type-hinted you should extend it as a sub-class not as a decorator.
> 
> Try this:
> 
> ```
> <?php
> 
> namespace App;
> 
> class Redirector extends \Illuminate\Routing\Redirector
> {
>     /**
>      * Create a new redirect response to the "home" route.
>      *
>      * @param  int  $status
>      * @return \Illuminate\Http\RedirectResponse
>      */
>     public function home($status = 302)
>     {
>         // conditionally add custom logic or fall back to $baseRedirector
> 
>         return parent::home($status); // calls base class redirector
>     }
> }
> ```
> 
> ```
> <?php
> 
> namespace App\Providers;
> 
> use Illuminate\Support\ServiceProvider;
> 
> class AppServiceProvider extends ServiceProvider
> {
>     //...
>     public function register()
>     {
>         $this->app->extend('redirect', function ($redirector) {
>             return new \App\Redirector($redirector->getUrlGenerator());
>         });
>     }
> 
>     //...
> }
> ```
> 
> This way your instance will satisfy any class or methods that type-hint the base `Redirector` class.
> 
> I guess maybe you could use the service container's `->singleton()` or `->bind()` methods instead of `->extend()`, but that should work.

Hi @rodrigopedra thanks for your reply! My intention was to demonstrate that extending the base class and calling `->singleton()`, object will be reinstatiated and this OK until some other package doesn't do the same thing, in that case more than one package extending Redirector is not possible(note: that same thing is not true for many other laravel services). The fundamental question is that almost all laravel services(Session, UrlGeneratar, ViewFactory and many others...) are described and used by their respective interfaces but only some of them are not.
