### ISSUE TITLE
Component template yielding section of previous component

### ISSUE THREAD

**Issue by falko100** [laravel/framework#33585]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: mysql  Ver 8.0.19 for osx10.14 on x86_64

### Description:
My component yields the content of a previous component.

### Steps To Reproduce:
I have a component with a dynamic view

```
    public function render()
    {
        switch ($this->type) {
            case 'select':
                return view('components.dynamic-input.select');
            default:
                return view('components.dynamic-input.default');
        }
    }
```

Both of these views extend a layout and have a `field` section:
```
@extends('components.dynamic-input.layout')

@section('field')
 <!-- Input specific code -->
@endsection
```
layout.blade.php (stripped of tailwind classes)
```
<div class="wrapper-classes">
    <label for="input_{{ $name }}"
           class="label-classes">
        {{ $label }}
    </label>
    <div class="column-classes">
        <div class="field-classes">
            @yield('field')
        </div>

        @include('form.error', ['name' => $name])
    </div>
</div>

```

When putting them both into a form:
```
<x-input
    name="phone"
    label="Phone number"
    placeholder="Enter your phonenumber"
></x-input>

<x-input
    name="education"
    label="Education level"
    type="select"
    :options="\App\Enums\EducationLevel::values()"
    placeholder="Pick your level of education"
></x-input>
```

The second input has the right label, but the `@yield('field')` is filled with a text-input with the placeholder `Enter your phonenumber`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by falko100** [comment]
@driesvints Nobody is responding and I am quite sure this is a bug.
![image](https://user-images.githubusercontent.com/11974977/87880208-1af7c180-c9f0-11ea-9d2b-0375096b71ca.png)
![image](https://user-images.githubusercontent.com/11974977/87880221-35319f80-c9f0-11ea-848d-381ddb3fadd8.png)
![image](https://user-images.githubusercontent.com/11974977/87880225-411d6180-c9f0-11ea-8728-92ecf27d0a95.png)

**Comment by falko100** [comment]
The screenshots are in a clean Laravel install. This isn't the right behaviour is it?

**Comment by driesvints** [comment]
@falko100 this indeed can't work like this just like you cannot use extends twice in the same blade file. The components aren't "scoped" in their rendering. The "yield" will apply in the view where the components are rendered and because it applies twice it'll conflict.

**Comment by falko100** [comment]
I made the render return the `layout` view and added a sub-view it `@include`.
Maybe being able to use `@extends` would be a great additional feature.

**Comment by driesvints** [comment]
It definitely would yes.
