### ISSUE TITLE
Laravel 419 Page Expired Error

### ISSUE THREAD

**Issue by alihanc** [laravel/framework#33588]
- Laravel Version: 7x
- PHP Version: 7.3
- Database Driver & Version: Mysql 8.0

Hello, I am a user of mac os x. I code a simple blog and there is 1 form on my contact page. I am sending this form to the same route as post but I get 419 error. In another project, I have installed laravel ui auth. When I try to login with demo user, I get 419 error. I have been trying to solve it for 1 week. Can you help me?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
