### ISSUE TITLE
Gate::after(): returning a not null value do not alter the result of the authorization

### ISSUE THREAD

**Issue by ivanomatteo** [laravel/framework#33587]
- Laravel Version: 7.20.0
- PHP Version: 7.4.8
- Database Driver & Version: mysql 8.0.21

### Description:

According to the documentation about the after method:
https://laravel.com/docs/7.x/authorization#intercepting-gate-checks

_"Similar to the before check, if the after callback returns a non-null result that result will be considered the result of the check."_

But has no effect, like in older version of the framework.

### Steps To Reproduce:

```
Gate::define('edit-settings', function ($user = null) {
    return true;
});
Gate::after(function ($user = null, $ability = null, $result = null, $arguments = null) {
    return false; //this have no effect
});

// ------------

Gate::allows('edit-settings'); // return true!
```

**Comment by driesvints** [comment]
The behavior is OR, not AND. If any of the above returns true, the permission passes.

**Comment by ivanomatteo** [comment]
> The behavior is OR, not AND. If any of the above returns true, the permission passes.

**The actual behavior seems different:**

```
Gate::define('edit-settings', function ($user = null) {
    // no return 
});
Gate::after(function ($user = null, $ability = null, $result = null, $arguments = null) {
    return false;  // the result is determined only by Gate::after() function
});


```

```
Gate::define('edit-settings', function ($user = null) {
    return false; 
});
Gate::after(function ($user = null, $ability = null, $result = null, $arguments = null) {
    return true;  // if  Gate::define() return not null value, so Gate::after() return value is ignored
});
```

Maybe the documentation have to be updated?

**Comment by joeyrush** [comment]
> The behavior is OR, not AND. If any of the above returns true, the permission passes.

Is there a way in an `Gate::after()` hook to return the definitive result? This explanation makes the following snippet, as highlighted in the OP, completely inaccurate:

> "Similar to the before check, if the after callback returns a non-null result that result will be considered the result of the check."

Context: using laravel/bouncer for DB permissions, configured so that it runs Laravel policies before DB permission checks but then I also want an additional global rule to run after everything else where it denies based on X condition **unless** a policy returns true (hence why I can't use `Gate::before`)
