### ISSUE TITLE
warn on command get "Call to a member function getFormatter() on null"

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#33582]
- Laravel Version: Laravel Framework 7.20.0
- PHP Version: PHP 7.4.8
### Description:
CI/CD run occasionally throw out this error, rerun almost sure it will gone.
It happen when call warn (or comment) https://laravel.com/docs/7.x/artisan#writing-output

### Steps To Reproduce:
I've try couple way to reproduce, but unable to do so
```php
$this->warn(0);
$this->warn('');
$this->warn(null);
$this->warn('null');
```

No step to reproduce, it occurrence are quite random, can't pinpoint when it happen 
```php
00:08:51.263   Tests:  1 failed
00:08:51.263 
00:08:51.263    Error 
00:08:51.263 
00:08:51.263   Call to a member function getFormatter() on null
00:08:51.263 
00:08:51.263   at engine/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php:312
00:08:51.263     308|      * @return void
00:08:51.263     309|      */
00:08:51.263     310|     public function warn($string, $verbosity = null)
00:08:51.263     311|     {
00:08:51.263   > 312|         if (! $this->output->getFormatter()->hasStyle('warning')) {
00:08:51.263     313|             $style = new OutputFormatterStyle('yellow');
00:08:51.263     314| 
00:08:51.263     315|             $this->output->getFormatter()->setStyle('warning', $style);
00:08:51.263     316|         }
00:08:51.263 
00:08:51.263   1   engine/app/Console/Commands/xxxxxxxxxxx.php:1733
00:08:51.263       Illuminate\Console\Command::warn()
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
