### ISSUE TITLE
e function in laravel can throw exception when passing the array in the first parameter

### ISSUE THREAD

**Issue by abderrazzak-oxa** [laravel/framework#33583]
- Laravel Version: 7.20.0
- PHP Version: 7.4.0

### Description:
e function in laravel can throw exception when passing the array in the first parameter, like e(old('email')) so this email param can be array because this email param was sent from frontend.

#### normal code:
`<input type="email" name="email" value="{{ old('email') }}">`
#### after editing in inspect element in browser
`<input type="email" name="email[]" value="{{ old('email') }}">`
send email param as array
then when the email is not valid it will return `old('email')` as an array
so it will be like this `{{ old('email') }}` after blade compiler will be `e(old('email'))`

### Problem:
The problem is in `e` function exactly is in htmlspecialchars function it not accept array parameter
`return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode);`

### Solve:
The solve is to check if `$value` parameter is a string type else you can return empty value
`return is_string( $value )? htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode): '';`

**Comment by GrahamCampbell** [comment]
This is a bug in your code. You must check if the result is a string first, before trying to escape it.

**Comment by GrahamCampbell** [comment]
`{{ is_string($v = old('email')) ? $v : '' }}` might do what you need.

**Comment by abderrazzak-oxa** [comment]
but there's a problem in the default login.blade.php, also this bug is in a lot of sites like laravel-news.com/login ...!
you need to update it in login.blade.php and register.blade.php ... @taylorotwell !

**Comment by SjorsO** [comment]
@GrahamCampbell I don't think you should dismiss this issue so quickly. The example shows that you can cause 500 errors in pretty much any Laravel application by sending invalid data.

Many applications send errors to Slack, Sentry or Flare. Being able to easily trigger errors could be a possible way to DDoS (or simply harass) an application.
