### ISSUE TITLE
Datetime strings containing timezone data (written to a Laravel API) are stored incorrectly in database

### ISSUE THREAD

**Issue by miking7** [laravel/framework#33592]
- Laravel Version: 7.13.0
- PHP Version: 7.4.1
- Database Driver & Version: mysql 5.7.12

### Description:
Laravel incorrectly throws out timezone data passed to an API (ie: create/update call), and stores times in the database that are based on an "assumed" timezone instead of the timezone specified.

The issue is due to an Eloquent inconsistency already highlighed (unsuccessfully) under [issue #19865](https://github.com/laravel/framework/issues/19865).  @DSpeichert was correct - Laravel is unnecessarily throwing away timezone information here, and is exhibiting inconsistent behaviour between retrieving and storing information to Eloquent Models.  

### Steps to Reproduce:
1. Create an API using any model with datetime values.
2. Try to write a value to the API using any (ie: ISO 8601) text format that includes a timezone offset - ie: `2020-07-20T02:30+10:00`.
3. Laravel completely discards the timezone information and writes invalid values to the database - ie: `2020-07-20 02:30` (using the default database timezone) - which stores an invalid datetime value.
### Temporary Fix - Override the faulty function (coming from HasAttributes.php):
Notes: 
* Insert this code into your models to fix Eloquent's inconsistent handling of timezones when storing vs retrieving from a model.  
* This code is a Laravel 7 update based on a @DSpeichert's original suggested fix in [issue #19865]
* Although we're overriding it on a per-model basis here, this function could completely replace the faulty function defined in `Illuminate/Database/Eloquent/Concerns/HasAttributes.php`

```php
    /**
     * Convert a DateTime to a storable string.  (Override Laravel Default - which inconsistently throws away timezone informatio)
     *
     * @param  mixed  $value
     * @return string|null
     */
    public function fromDateTime($value)
    {
        return empty($value) ? $value : $this->asDateTime($value)->setTimezone(config('app.timezone'))->format(
            $this->getDateFormat()
        );
    }
```

### Alternative temporary fix using a mutator
Note: This code is required for every datetime field you need to protect in your models.  (We had developed this code before finding @DSpeichert 's more generic fix.
```php
    /**
     * Set the "Test" field value (without throwing away timezone data)
     *
     * @param  string  $value
     * @return void
     */
    public function setTestAttribute($value)
    {
        $this->attributes['test'] = Date::parse($value)->setTimeZone(config('app.timezone'));
    }
```

### Alternative "Fix" = don't trust Laravel with non-UTC dates
Laravel API create/update requests won't handle dates properly if they are in any string format that contains timezone offsets.    Another "fix" is to convert all dates to UTC in the front-end before writing them to your API.

**Comment by driesvints** [comment]
DateTime objects are stored as timestamps in the database which don't have any context of a timezone. We cannot convert to UTC automatically because not everyone stores their datetime objects as UTC. You are responsible for converting to the correct timezone yourself. Either store as UTC (or your preferred timezone) or save the timezone as a separate database column.

**Comment by truongan** [comment]
Stumble upon this after hours of frustrating when trying out date mutator. I think the document oughto boldly stated that Timezone information in DateTime object will be stripped of when saving to Eloquent model, since a github issues response is quite hard to search for

**Comment by dmekhov** [comment]
> DateTime objects are stored as timestamps in the database which don't have any context of a timezone. We cannot convert to UTC automatically because not everyone stores their datetime objects as UTC. You are responsible for converting to the correct timezone yourself. Either store as UTC (or your preferred timezone) or save the timezone as a separate database column.

@driesvints

but what if I use dateTimeTz/timestimeTz field?

I tried save field with timezone but laravel stored wrong value to databse - if I use not utc app.timezone
