### ISSUE TITLE
ETag cache will not be checked correctly

### ISSUE THREAD

**Issue by zKoz210** [laravel/framework#33591]
- Laravel Version: 7.20.0
- PHP Version: 7.4.0

### Description:
ETag doesn't work when using it in Laravel Middleware. Due to "**W/**", the comparison cannot be performed correctly
![image](https://user-images.githubusercontent.com/28255085/87884519-5f4a8800-ca17-11ea-89bb-7a98bcf1d5b4.png)

![image](https://user-images.githubusercontent.com/28255085/87884120-b6029280-ca14-11ea-9e8e-c25842f2b93a.png)

Code: https://github.com/symfony/http-foundation/blob/master/Response.php#L1094

### Steps To Reproduce:

```
Route::middleware('cache.headers:public;max_age=2628000;etag')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
}
```

**Comment by GrahamCampbell** [comment]
> ETag doesn't work when using it in Laravel Middleware. Due to "W/", the comparison cannot be performed correctly

Where is that code from please? Is it in `laravel/framework` or `laravel/laravel`. If not, then you just have a bug in your own/3rd party code?

**Comment by zKoz210** [comment]
This is a symfony/httpfoundation problem I understand?

Code: https://github.com/symfony/http-foundation/blob/master/Response.php#L1094

**Comment by GrahamCampbell** [comment]
It looks that way. Please let them know with a self-contained example, without mentioning laravel middleware so they can understand the bug.
