### ISSUE TITLE
Using CastsAttribute on a foreign key results in "Illegal offset type in isset or empty"

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#33601]
- Laravel Version: `7.15.0`
- PHP Version: `7.4.3`
- Database Driver & Version: `pgsql` `2:7.4+75`

### Description:

It appears as though when I define a custom cast, [this line of code](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L190) fails to correctly resolve a value that Eloquent can use.

### Steps To Reproduce:
Use the following custom cast on any foreign key of a relation in a model:

```php
<?php namespace App;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Ramsey\Uuid\Uuid;

class UuidCast implements CastsAttributes
{
    public function get($model, string $key, $value, array $attributes)
    {
        if (empty($value)) {
            return null;
        }

        return Uuid::fromString($value);
    }

    public function set($model, string $key, $value, array $attributes)
    {
        if (empty($value)) {
            return null;
        }

        if (is_string($value)) {
            $value = Uuid::fromString($value);
        }

        return $value->toString();
    }
}
```

I end up getting _"Illegal offset type in isset or empty"_ when using `SerializesModels` and a queue or email.

### Notes
I think what it's doing is attempting to use - in this case - an instance of my `Uuid` to index into the array, which is obviously bad. What would make more sense here is perhaps to try and bypass the cast and use whatever value the model is holding internally. Failing that, perhaps it can recognize the configured cast and artificially call `set` to obtain the internal value?

**Comment by taylorotwell** [comment]
You can't use an object as an offset. Best thing we could maybe do there is cast the value to a string if it's an object.

**Comment by atrauzzi** [comment]
Would it not be possible to see if the model has a configured cast for the attribute and run it through `set` to get the primitive value?

**Comment by taylorotwell** [comment]
I don't know. That's another option perhaps. Feel free to explore it in a PR.

**Comment by staudenmeir** [comment]
Please also see https://github.com/laravel/ideas/issues/2144.

**Comment by driesvints** [comment]
I'm going to close this because of previous declined attempts. However, feel free to attempt a new pr. Thanks.

**Comment by atrauzzi** [comment]
Unfortunate, seems like a deficiency that you can't cast a column simply because it's used in a relation...

**Comment by driesvints** [comment]
@atrauzzi we're open to prs if you want to help make that more clear in the docs 👍

**Comment by driesvints** [comment]
Actually, just found that this is documented already:

https://laravel.com/docs/7.x/eloquent-mutators#attribute-casting

<img width="722" alt="Screenshot 2020-07-31 at 16 45 52" src="https://user-images.githubusercontent.com/594614/89046522-575ee200-d34d-11ea-82bd-14c2968c2f91.png">
