### ISSUE TITLE
Setting a date on Eloquent model with timezone causes wrong time to be stored in UTC 

### ISSUE THREAD

**Issue by grEvenX** [laravel/framework#33604]
- Laravel Version: 7.20.0
- PHP Version: 7.4.8
- Database Driver & Version: PostgreSQL (all versions), but doesn't seem relevant for the problem

### Description:
The time stored internally in the Eloquent instance (and the DB) is wrong when trying to set a date property of an Eloquent model using a Carbon instance that has a different timezone than UTC set.

It seems the problem is related to the `HasAttribute` trait's `fromDateTime` method that gets called when the Eloquent attribute setter method is called.
The method currently has the following implementation

```!php
public function fromDateTime($value)
{
    return empty($value) ? $value : $this->asDateTime($value)->format(
        $this->getDateFormat()
    );
}
```

This should probably respect the `timezone` config property defined in `config/app.php`, or be set to UTC?
If it was supposed to be in UTC, it could be solved by changing `$this->asDateTime($value)->format(...)` to `$this->asDateTime($value)->utc()->format(...)`

### Steps To Reproduce:

The following code can be used as a test:
```!php
<?php

class MyModel extends Model
{
    protected $dates = [ 'started_at'];
}

$aModel = new MyModel();
$aModel->started_at = new Carbon\Carbon('2018-05-09T07:09:32+02:00');

// The date-time to be stored in UTC should be at 05:09:32 instead of 07:09:32
assert('2018-05-09T05:09:32.000000Z' == $aModel->started_at->toJSON()); // should be true
// $aModel->started_at->toJSON() outputs 2018-05-09T07:09:32.000000Z (lost the 2 hours from the UTC+2 offset from the input date)
```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/33592 and other closed issues. You are responsible for converting to the correct timezone before storing.

**Comment by UncertaintyP** [comment]
Hey @driesvints I just stumbled upon this.

According to the linked issue you said Laravel stores the datetime as timestamp. So is it intended behavior that Laravel changes the timestamp? As you can see in the following example Laravel shifts the timestamp by 1 hour :worried: :cry: 


```
>>> $model->start_at  = now('Europe/Berlin')
=> Illuminate\Support\Carbon @1638313200 {#5413
     date: 2021-12-08 19:30:22.622384 Europe/Berlin (+01:00),
   }
>>> $model->start_at
=> Illuminate\Support\Carbon @1638316800 {#5412
     date: 2021-12-08 19:30:22.0 UTC (+00:00),
   }
>>>  now('Europe/Berlin')->startOfMonth()
=> Illuminate\Support\Carbon @1638313200 {#5408
     date: 2021-12-08 19:30:39.301046 Europe/Berlin (+01:00),
   }
```

**Comment by driesvints** [comment]
@UncertaintyP yes that's intended. Like it's said in the other issues: you are responsible for setting the correct timezone before storing timestamps.

**Comment by UncertaintyP** [comment]
@driesvints Just to make sure this is **NOT** about timezones. Laravel changes the **TIMESTAMP** as can be seen here:

```
>>> $now = now('Europe/Berlin')
=> Illuminate\Support\Carbon @1639050236 {#5325
     date: 2021-12-09 12:43:56.948526 Europe/Berlin (+01:00),
   }
>>> $model->start_at = $now
=> Illuminate\Support\Carbon @1639050236 {#5325
     date: 2021-12-09 12:43:56.948526 Europe/Berlin (+01:00),
   }
>>> $model->start_at->timestamp
=> 1639053836
>>> $now->timestamp
=> 1639050236
```

See the timestamps differ by 3600 seconds :worried:

**Comment by driesvints** [comment]
Yes that's expected, you're second timestamp is in the Tokyo timezone so it's not the same moment in time.

**Comment by khangln-amv** [comment]
@driesvints just so you know, timestamp does not have timezone data, timestamps are the number of seconds elapsed from a single point in time (the UNIX epoch). They do not changes across timezone
