### ISSUE TITLE
Redis::keys returns key including laravel prefix

### ISSUE THREAD

**Issue by john-tuck** [laravel/framework#33615]
- Laravel Version: 7.15.0
- PHP Version: 7.3.14
- Database Driver & Version:

### Description:
I'm not sure if this should be a feature request or bug.. I'm trying to iterate over a set of keys using Redis::keys, but the keys that are returned include the laravel prefix. I have to either strip out the prefix to actually use the keys or not use a prefix at all.

### Steps To Reproduce:
```>>> use Illuminate\Support\Facades\Redis;
>>> Redis::set('test:test1', 'test');
=> true
>>> Redis::keys('test:*');
=> [
     "laravel_database_test:test1",
   ]
>>> Redis::del('laravel_database_test:test1');
=> 0
>>> Redis::del('test:test1');
=> 1
```

**Comment by taylorotwell** [comment]
Right now we will call it a feature. Would be a breaking change to modify it at this point and I'm not sure what the preferred behavior would be. You can strip the prefix in user land.
