### ISSUE TITLE
Setting DateFactory to use CarbonImmutable breaks date validation when Date::setTestNow() is used

### ISSUE THREAD

**Issue by vincemukiiri** [laravel/framework#33620]
- Laravel Version: 7.9.1
- PHP Version: 7.4.5
- Database Driver & Version: mysql 8.0.20

### Description:
Setting the DateFactory to use CarbonImmutable in AppServiceProvider by calling `DateFactory::use(CarbonImmutable::class);` in the register function and setting a test date like `Date::setTestNow(Date::parse('2018-07-19'))` causes the date validation to fail. This is because validation logic uses Carbon and so it doesn't recognise the test date in `Illuminate\Validation\Concerns\ValidatesAttributes` trait:
```
/**
     * Check if the given value should be adjusted to Carbon::getTestNow().
     *
     * @param  mixed  $value
     * @return bool
     */
    protected function isTestingRelativeDateTime($value)
    {
        return Carbon::hasTestNow() && is_string($value) && (
            $value === 'now' || Carbon::hasRelativeKeywords($value)
        );
    }
```

### Steps To Reproduce:
Set the DateFactory to use CarbonImmutable in AppServiceProvider:
```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        DateFactory::use(CarbonImmutable::class);
    }

    ...
}
```

Run the following test:
```
public function testDateValidation()
    {
        Date::setTestNow(Date::parse('2018-07-19'));

        $validator = Validator::make(['date' => '2018-07-23'], [
            'date' => 'required|date_format:Y-m-d|after_or_equal:today',
        ]);

        $this->assertTrue($validator->passes());
    }
```

**Comment by taylorotwell** [comment]
Just use Carbon directly.

**Comment by mfn** [comment]
@vincemukiiri I think you may have a valid point!

The `Carbon::` calls in `ValidatesAttributes` were introduced in Feb 2018 => https://github.com/laravel/framework/commit/7bcfa908f8bd3bfcccfb0aedbd7e5d1417241b80

Later that year we got the Carbon / Date overhaul which added the ability to switch implementations => https://github.com/laravel/framework/commit/ccb9d6c311bdfa8d22e32131f3e5474d588415ac

As can be seen, _many_ occurrences of `Carbon` have been replaced with the `Date` facade to accommodate the flexibility when the date handler is changed.

@kylekatarnls do you remember / have an idea why some occurrences like these were not adapted? https://github.com/laravel/framework/blob/a66caa51ae1a99990ce6a572ade5fd78e4ad3d3a/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L258-L269

Thanks

**Comment by kylekatarnls** [comment]
Actually, the `getDateTime()` make me feel a bit uncomfortable:

```php
    protected function getDateTime($value)
    {
        try {
            if ($this->isTestingRelativeDateTime($value)) {
                return Date::parse($value);
            }

            return date_create($value) ?: null;
        } catch (Exception $e) {
            //
        }
    }
```

When `isTestingRelativeDateTime($value)` is true, it will return a `Carbon` instance (or the configured class such as CarbonImmutable or any other compatible date class), else it will return a simple `DateTime` (mutable).

However, if it would simply `return Date::parse($value);` in every case, this should be uniform and produce predictible return type.

So I agree to use Date::hasTestNow and Date::hasRelativeKeywords but the whole sense `isTestingRelativeDateTime` may also be questioned.

@derekmd Could you please explain why handling `isTestingRelativeDateTime()` cases differently if true or false? Why not using `Carbon` to get date/timestamp in any of the 2 circumstances and let Carbon deal with the testNow which is yet properly handled?

**Comment by kylekatarnls** [comment]
As a first option, I propose #33623, it would fix this by removing the code in this file that is specific to `hasTestNow` and simply use the `Date::parse()` in every case so handling the testNow is delegated to `Carbon` or the class chosen via the `Date` which is my opinion the one which is responsible for that.

**Comment by mfn** [comment]
Thank you @kylekatarnls 🙏

**Comment by vincemukiiri** [comment]
Thanks @kylekatarnls! 😁
