### ISSUE TITLE
required_without not working correctly

### ISSUE THREAD

**Issue by SamuelNitsche** [laravel/framework#33628]
- Laravel Version: 7.21.0
- PHP Version: 7.4.3
- Database Driver & Version: n/a

### Description:
I have a form where users can book a ticket for an event. Users have to enter a postal code, either a general for every attendee or one per attendee.

My validation logic looks like this:

```php
request()->validate([
    'postal_code' => ['nullable', 'required_without:attendees.*.postal_code'],
    'attendees' => ['required', 'array'],
    'attendees.*.postal_code' => ['nullable', 'required_without:postal_code'],
]);
```

When I submit the form and only enter the "attendee postal_code" laravel returns the following validation error.

`The postal_code field is required when attendees.*.postal_code is not present.`

I tried different combinations like dropping the `nullable` rules but I can't get it to work.

**Comment by driesvints** [comment]
There have been many assumptions in the past about required_without not working properly. Please check these first: https://github.com/laravel/framework/issues?q=is%3Aissue+required_without+is%3Aclosed

**Comment by SamuelNitsche** [comment]
Yes, I already read through all of them. That's why I tested all kind of `nullable` and `sometimes` combinations before opening the issue.

Also, `required_without` works perfectly fine without using an array.

**Comment by themsaid** [comment]
```
'postal_code' => ['nullable', 'required_without:attendees.*.postal_code']
```

`required_without:attendees.*.postal_code`. Basically Laravel doesn't know how to validate that. Which attendee in the array of attendees that you want to validate against?

IMO. Don't try to twist the validation rules to cover those edge cases, will almost always give unexpected results. Create a custom validation code and throw a ValidationException instead. This will make you code much much much easier to read and modify.

**Comment by SamuelNitsche** [comment]
Hm, I would expect that laravel validates every attendee in the array to have a `postal_code`, otherwise the `postal_code` field is required. That's why I thought you use an asterisk.

Thats also how I understand [the docs](https://laravel.com/docs/7.x/validation#validating-arrays). Every user that has entered a `first_name` also has to enter a `last_name`.

**Comment by themsaid** [comment]
It doesn't work like that. Use custom validation code instead.

Also the logic seems a bit odd. If you have 99 attendees with postal codes but 1 of them without, do you want to require the `postal_code`?

**Comment by SamuelNitsche** [comment]
Okay, I will write custom validation code.

Yes, this is what I need. Due to Covid-19, we need the postal code of every attendee. In normal circumstances, people of the same household attend to the event and enter the "general `postal_code`" but I want to allow them to also book tickets for other people.
They then can overwrite the `postal_code` for the additional person.

Hope this makes sense for you.
