### ISSUE TITLE
Incorrect Parameter Type for Illuminate\Session\Store::pull

### ISSUE THREAD

**Issue by johnfrankmorgan** [laravel/framework#33626]
- Laravel Version: 7.20.0
- PHP Version: 7.4.8
- Database Driver & Version:

### Description:

The docblock for Illuminate\Session\Store::pull has an incorrect type for the optional $default argument.
This causes Psalm static analysis to fail with a PossiblyFalseArgument error when a value other than a ?string is supplied for the $default parameter.

Rather than a nullable string, the $default argument should be type hinted as mixed.

### Steps To Reproduce:
Run Psalm static analysis with a minimum error level of 3 to produce an error.

`php vendor/bin/psalm app/example.php`

Example PHP file (app/example.php):
```php
<?php

use Illuminate\Session\Store;

/** @var Store $store */
$store = app()->make(Store::class);
$store->pull('test', false);
```

Psalm configuration file (psalm.xml):
```xml
<?xml version="1.0"?>
<psalm
    errorLevel="3"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="app"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```

**Comment by driesvints** [comment]
Feel free to attempt a PR if you think anything is wrong here.
