### ISSUE TITLE
Problem with DB transaction in queue

### ISSUE THREAD

**Issue by ilirien** [laravel/framework#33635]
- Laravel Version: 6.2.0 (tested on this version but looks like all version have same problem)
- PHP Version: 7.3
- Database Driver & Version: MySQL 8

### Description:

Problem is when you listening event in queue

`\Illuminate\Database\Events\TransactionCommitted`

and exception occured in this event listener, next job in queue will have transaction level before transaction start -1 and it won't start transaction for this job.

###  Steps To Reproduce:

The easiest way to reproduce run this 2 jobs

```
dispatch(function () {
    \DB::transaction(function() {
        var_dump(\DB::transactionLevel());
    });
});

dispatch(function () {
    \DB::transaction(function() {
        var_dump(\DB::transactionLevel());
    });
});
```

As well you need to setup listener for 

`\Illuminate\Database\Events\TransactionCommitted`

I'm setting it in AppServiceProvider for example 

`app('events')->listen(\Illuminate\Database\Events\TransactionCommitted::class, function () {
        throw new \Exception();
});`

###   Possible ways to fix:

Switch line for setting transaction level and firing event

```
//from
if ($this->transactions == 1) {
     $this->getPdo()->commit();
}

$this->transactions = max(0, $this->transactions - 1);

$this->fireConnectionEvent('committed');

//to
if ($this->transactions == 1) {
     $this->getPdo()->commit();
}

$this->fireConnectionEvent('committed');

$this->transactions = max(0, $this->transactions - 1);
```

Or in handleCommitTransactionException method use 

```
$this->transactions = max(0, $this->transactions - 1);

//instead of 

$this->transactions--
```

**Comment by mfn** [comment]
Interesting find, the state of the transaction not being properly restored before a new job, expecting a "clean slate", is certainly problematic.

Stupid question: wouldn't this also be possible to reproduce _without_ jobs being involved?

**Comment by driesvints** [comment]
Which queue are you using? Please share your queue setup as well as your database configuration.

**Comment by ilirien** [comment]
@driesvints redis/beanstalkd same problem. What exactly you need about database configuration?

I've tested on MySQL 8.0.17 and PDO

But it looks like not problem with software, just only logic problem in laravel.

**Comment by ilirien** [comment]
@mfn 

Code to reproduce without queue, but it should be very rare case. 

```
app('events')->listen(\Illuminate\Database\Events\TransactionCommitted::class, function () {
    throw new \Exception();
});

try {
    \DB::transaction(function () {
        var_dump(\DB::transactionLevel()); //1
    });
} catch (\Throwable $e) {
    //
}

app('events')->forget(\Illuminate\Database\Events\TransactionCommitted::class);

\DB::transaction(function() {
    //actually this code is not in transaction
    var_dump(\DB::transactionLevel()); // 0
});
```

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by mfn** [comment]
FTR https://github.com/laravel/framework/commit/c4cdfc7c54127b772ef10f37cfc9ef8e9d6b3227
