### ISSUE TITLE
Cannot delete custom MorphPivot in Laravel 6.18.26

### ISSUE THREAD

**Issue by lukadriel7** [laravel/framework#33647]
- Laravel Version: 6.18.26
- PHP Version: 7.4.8
- Database Driver & Version: MariaDB 10.3.23

### Description:
Trying to delete a custom MorphPivot Model using uuid as primary key result in an error:
```
Illuminate/Database/QueryException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: delete from `comment` where (`` = 01418755-c68e-4ea5-8043-cef348c47445))'
```
Laravel uses an empty string instead of the id column to try and find the model.
Creating, updating and finding model by id still works.

Model Code:
```
<?php

namespace App;

use App\Traits\HasUuid;
use Illuminate\Database\Eloquent\Relations\MorphPivot;

class Comment extends MorphPivot
{
    use HasUuid;

    protected $casts = [
        'id' => 'string'
    ];

    protected $fillable = [
        'id',
        'parent_id',
        'user_id',
        'commentable_id',
        'commentable_type',
        'content',
        'created_at',
        'updated_at'
    ];

    public $incrementing = false;
    public $keyType = 'string';
    protected $primaryKey = 'id';
}
```
Migration Code:
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCommentTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('comment', function (Blueprint $table) {
            $table->uuid('id');
            $table->primary('id');
            $table->text('content')->default("");
            $table->boolean('spoiler')->default(false);
            $table->boolean('hidden')->default(false);
            $table->boolean('edited')->default(false);
            $table->uuid('parent_id')->nullable();
            $table->uuid('user_id')->default((string) Illuminate\Support\Str::uuid());
            $table->uuid('commentable_id')->default((string) Illuminate\Support\Str::uuid());
            $table->string('commentable_type')->default(App\Post::class);
            $table->json('meta')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('comment');
    }
}
```

### Steps To Reproduce:

- Create a laravel 6 project
- Create a custom pivot model and its migration similarly to code posted above
- Create a new record
- Try deleting the record

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by lukadriel7** [comment]
@driesvints Hey, I did a quick check in the source code of MorphMany and found the problem. This condition is missing in the Laravel 6.x tag source code.
```
if (isset($this->attributes[$this->getKeyName()])) {
   return (int) parent::delete();
}
```
the same instruction exist in the simple Pivot model through the AsPivot trait: 
[AsPivot trait laravel 6.x](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php#L111)

[MorphPivot Laravel 6.x](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/MorphPivot.php#L46)

[MorphPivot Laravel 7.x](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Relations/MorphPivot.php#L46)

Can you please check it ?

**Comment by lukadriel7** [comment]
> @driesvints Hey, I did a quick check in the source code of MorphMany and found the problem. This condition is missing in the delete method of MorphPivot in Laravel 6.x tag source code.
> 
> ```
> if (isset($this->attributes[$this->getKeyName()])) {
>    return (int) parent::delete();
> }
> ```
> 
> the same instruction exist in the simple Pivot model through the AsPivot trait:
> [AsPivot trait laravel 6.x](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php#L111)
> 
> [MorphPivot Laravel 6.x](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Relations/MorphPivot.php#L46)
> 
> [MorphPivot Laravel 7.x](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Relations/MorphPivot.php#L46)
> 
> Can you please check it ?

@driesvints i can confirm that it is the problem, i change the laravel source code of MorphPivot in my project (I know it is bad but I just wanted to check) And it works.

**Comment by driesvints** [comment]
@lukadriel7 feel free to attempt a pr to see if Taylor will merge it.

**Comment by lukadriel7** [comment]
@driesvints , about that I don't really know how to write tests...
