### ISSUE TITLE
When actingUs with soft deleted user with verified email address, authentication passed user calls

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#33652]
- Laravel Version: 7.21.0
- PHP Version: 7.3.20
- Database Driver & Version:

### Description:
When we have verified user email address and user is soft deleted we can create new resource in database while testing ;(
Deam.

### Steps To Reproduce:
1. Add in web.php file:
https://laravel.com/docs/7.x/verification#verification-routing
and
```php
Route::middleware('verified')->group(function () {
    Route::post('/group', 'GroupController@store')->name('groups.store');
});
```

3. Make user model soft delete:
https://laravel.com/docs/7.x/eloquent#soft-deleting

4. Write test:
```php
public function testStore()
{
    $group = factory(Group::class)->make()->toArray();
    $invalidUser = User::withTrashed()->whereNull('email_verified_at')->orWhereNotNull('deleted_at')->get()->random();
    $response = $this->actingAs($invalidUser)->postJson('/groups', $group);
    $response
        ->assertStatus(JsonResponse::HTTP_FORBIDDEN)
        ->assertJson(['message' => 'Your email address is not verified.']);
}
```

When we get user with filled up nodes `email_verified_at` and `deleted_at` with date, then we get error message:
```php
Expected status code 403 but received 201.
Failed asserting that 403 is identical to 201.
```

**Comment by devcircus** [comment]
Looks like your route middleware only prevents users that are not verified. Since you're using "orWhere", the query will either return users who are not verified OR soft-deleted, not both. 

Soft deleted models are filtered at the query-level by default, but if you explicitly allow them via the "withTrashed" method, they are treated as a valid user. 

Seems like everything is working as expected unless I'm completely overlooking something in the logic. 

You could try grabbing a specific user that is not verified and run the same test. If that one fails, the maybe something needs to be addressed.

**Comment by LocalHeroPro** [comment]
So in what way working authentication, if I can access to page with soft deleted user?

**Comment by devcircus** [comment]
Soft deleted users will not be found therefore not authenticated. When you use "withTrashed", you're telling Laravel to ignore the fact that the model has been soft deleted. 

Authentication should do something similar to:

```php
$authenticated = User::where('email', $email)->where('password', bcrypt($password)->first();
```
In that case, soft deleted users will not be found and therefore not authenticated.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LocalHeroPro** [comment]
@devcircus, so in your opinion acting as soft deleted user is a feature?
