### ISSUE TITLE
[7.22.0] withCookie test method broken

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel/framework#33664]
- Laravel Version: 7.22.0
- PHP Version: 7.4.0
- Database Driver & Version: sqlite

### Description:
With the new release (7.22.0), the withCookie() method used in tests is broken. All cookies return null instead of the expected content.

This seems to have been introduced in the 7.22.0, as 7.21.0 works as expected.

### Steps To Reproduce:
1. Create feature test using withCookie() method while making request
2. Die and dump $request->cookie()
3. Note that content for cookie is null when it should not be.

**Comment by driesvints** [comment]
Looking into this.

**Comment by driesvints** [comment]
A fix was released. Thanks for reporting 👍

**Comment by andyvenus** [comment]
If anyone else has issues with this, the latest patch also means that the APP_KEY must be base64 encoded (we had an old APP_KEY for tests that was generated a while back before the format was updated). If your APP_KEY is not prefixed with `base64:`, the tests will fail.

**Comment by bytestream** [comment]
At what point did `base64:` become a requirement? All other code checks for `base64:` and handles when it doesn't exist.

**Comment by bytestream** [comment]
Behaviour updated to handle case here - https://github.com/laravel/framework/commit/84765753ee164e7b0978021c4d42711011aed340
