### ISSUE TITLE
Laravel Passport issue when using latest L7.22 & L7.22.1

### ISSUE THREAD

**Issue by robtesch** [laravel/framework#33666]
- Laravel Version: 7.22 & 7.22.1
- PHP Version: 7.4.8
- Database Driver & Version: Mysql 8.0.20

### Description:
Latest versions cause Passport based internal API to return "Unauthenticated" responses. Reverting to 7.21 fixes the issue.

### Steps To Reproduce:
Create plain laravel app using version 7.22 or 7.22.1. Install laravel passport. Make API request from front-end to back end, using the documented method (in my case, axios with "X-CSRF-TOKEN" and "X-Requested-With" headers). Api route should use auth:api as middleware.

**Comment by driesvints** [comment]
Duplicate of https://github.com/laravel/framework/issues/33665

Users need to logout and re-login.

**Comment by rennokki** [comment]
@driesvints I already checked for this and it throws 401 Unauthenticated all the way up.

**Comment by aaronhuisinga** [comment]
@driesvints this is definitely a legitimate issue. After updating and logging out/clearing cache, we still have requests made via Axios failing that were working before the update.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/33665#issuecomment-664550743
