### ISSUE TITLE
[7.22.4] Patch Problem: Argument #2 ($concrete) must be of type Closure|string|null

### ISSUE THREAD

**Issue by joelharkes** [laravel/framework#33680]
- Laravel Version: 7.22.4
- PHP Version: 7.4.4
- Database Driver & Version: N/A

### Description:

```
TypeError: Illuminate\Container\Container::bind(): Argument #2 ($concrete) must be of type Closure|string|null
```

I would expect I can already instantiate the class and just add that one to the container instead of adding a short hand function around it?

### Steps To Reproduce:

```php
$mock = \Mockery::mock(TestClass::class, [
   'someMethod' => null,
]);
app()->singleton(TestClass::class, $mock);
```

**Comment by gocanto** [comment]
you should be able to do this like so

```php
app()->instance(TestClass::class, $mock)
```

**Comment by GrahamCampbell** [comment]
Where is this documented?

**Comment by GrahamCampbell** [comment]
The singleton method says you must pass a callback that returns the class as the 2nd param: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Container/Container.php#L356.

**Comment by GrahamCampbell** [comment]
It looks like some other methods call bind differently. I think we should make the singleton method also do this, and widen it's doced type, so the code you have there will work again:

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Container/Container.php#L1287-L1299

**Comment by GrahamCampbell** [comment]
Ah, yes, I see @gocanto had provided the solution here. Passing an object as that 2nd param to singleton never worked properly in the first place, which is why we added that extra guard to stop people doing it by mistake.
