### ISSUE TITLE
Illuminate\Cookie\Middleware\EncryptCookies.php auth:api always unauthenticated

### ISSUE THREAD

**Issue by mc0de** [laravel/framework#33681]
- Laravel Version: 7.22.2
- PHP Version: 7.3.20
- Laravel Passport: 8.5.0

### Description:
It looks like EncryptCookies.php still has bugs with encryption, this completely breaks any SPA project,
because `auth:api` middleware doesn't work anymore, but in other middlewares auth()->user() works correctly.

Project uses `laravel/passport:8.5` and `api:auth` middleware.

Route looks as follows:
```
Route::group(['prefix' => 'v1', 'as' => 'api.', 'namespace' => 'Api\V1\Admin', 'middleware' => ['auth:api']], function () {
    Route::apiResource('abilities', 'AbilitiesController', ['only' => ['index']]);
});
```

### Request headers:
```
GET /api/v1/abilities HTTP/1.1
Host: clientqa.test
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: eyJpdiI6IkRURnRldkJUc0xTd0tjTnErWWNRYUE9PSIsInZhbHVlIjoiOTdwOTBTdUh2Zk51UGNTeUpWaWtzTHdUVDFhV1RxOE1GaysrV1lwbGtFckFyZ2lqdWlLTXA2QkVCWGRBWW1QYmVPTFQ3UHVGSTVHZjE5L1hreWN4QUFMS3d0WXJNMXlJWndGUmx1R0VsTWEzbEdNZm41SkdFK2JRODZOZ3hzUGUiLCJtYWMiOiI3YmIyMDhmMzgxMzJmZTFiMDM5OGEyMzY5ZTdkMTNjM2MwMjAyYTM5MWVlMTA4NmU4MGU5ZWIzOTYzY2RjYzdiIn0=
Connection: keep-alive
Referer: http://clientqa.test/admin/dashboard
Cookie: XSRF-TOKEN=eyJpdiI6IkRURnRldkJUc0xTd0tjTnErWWNRYUE9PSIsInZhbHVlIjoiOTdwOTBTdUh2Zk51UGNTeUpWaWtzTHdUVDFhV1RxOE1GaysrV1lwbGtFckFyZ2lqdWlLTXA2QkVCWGRBWW1QYmVPTFQ3UHVGSTVHZjE5L1hreWN4QUFMS3d0WXJNMXlJWndGUmx1R0VsTWEzbEdNZm41SkdFK2JRODZOZ3hzUGUiLCJtYWMiOiI3YmIyMDhmMzgxMzJmZTFiMDM5OGEyMzY5ZTdkMTNjM2MwMjAyYTM5MWVlMTA4NmU4MGU5ZWIzOTYzY2RjYzdiIn0%3D; laravel_session=eyJpdiI6ImdGYUZpT2plN3kxN210YlYraVhTWVE9PSIsInZhbHVlIjoiNS9IblE0NitRMXB6b01XV0Vid3RsTC9PTFUyODBuYXByaFFlckc4ZDRSQW4wdzdiUkZzdDRUQUJldE5hQVg3VVVHN3E5R0tNRWJTTVhpdkZJZHZzdnR4eEtnd0NJT1laYThCdHNwZzk1ek0rcmMwUHNNaVpyTWV2MUt2anVxYXUiLCJtYWMiOiIxM2RhOTg4NzBmMmMwNTZkNGQwOTYxNjk0YmRjN2JhMGYwMWRjN2EwM2UxZWM4ODkzNTAzYzg4Y2JlMDFkYmM0In0%3D; laravel_token=eyJpdiI6IkVDVGpUVFdnajJNd1BpWVRWblVGRlE9PSIsInZhbHVlIjoiTlFOKzBoT01HZDVkU0l2K0dwODVQNHpRWDc4Z2M0Mi91azNETlVNcTd4aE9QVGRnamFjL0NqVkxSZjY0V3FPZDVyRVRDeHc5WGFLZXJETDN6V3p0UkRNeWNGemZyVmZQY3k5aDZsUkZvSjZwM1pzT3o2MnBSMjNDem9NMDIwQ051RlowZ0xuSE8wZkNuRlpvMGxCWGdVR0svTlNoOFVuVGN4Zm9pcUs5UmRKd2FzY3d4U3M5a0Q5dVM5dGtwajhXdHFiMytEcWdjekh2MElodnNRNzROb1pZZTR4MElXa0RFWHZPNUVjdTFUOEU2eURxbWRJdUJoNGhsUXZ1c28zdTBxOXpCNmtGd3ZEVllmU256WjcyNzlqbHpUeGJOY3FMblVjWERUTXhETWNFYjc5eFFPUkRvaUQrTUFpY0hXWCsiLCJtYWMiOiJmZTRjMmYyZTJjOWJlYzBjZTg0NTU0ZGQ1YzZlZDc0ZDhmYzY0NDNiY2YyOThlNmE4NTIwYjc1NDNmZTI4MTgxIn0%3D
Pragma: no-cache
Cache-Control: no-cache
```

### Response headers:
```
HTTP/1.1 401 Unauthorized
Server: nginx/1.18.0
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.3.20
Cache-Control: no-cache, private
Date: Tue, 28 Jul 2020 10:47:51 GMT
```

### Steps To Reproduce:
run `composer update` on any project that uses auth:api middleware and has `laravel/passport` with `\Laravel\Passport\Http\Middleware\CreateFreshApiToken::class,` enabled.

or just run `composer install` in fresh installation. In addition `composer.lock` file is not respected and gets newer buggy version anyway.

In the end i think this is not passport related but due to new EncryptCookies logic.

#### Important
Reverting encrypt cookies to previous version (laravel/framework "v7.14.1") solves the issue and everything works correctly again.

![Screenshot from 2020-07-27 19-54-50](https://user-images.githubusercontent.com/8727992/88657622-e1534480-d0da-11ea-9997-0edc2b3d0bdd.png)

I checked if it persists to this moment with `composer clearcache` since i found it yesterday, and I can confirm that.

**Comment by avvertix** [comment]
According to https://blog.laravel.com/laravel-cookie-security-releases seems Laravel Passport needs to be version 9.3.2 to support the bug-fix release, which I think is 7.22.4.

**Comment by driesvints** [comment]
Please upgrade to the maintained Passport 9 (latest version) which has a fix for this.

**Comment by mc0de** [comment]
solved
