### ISSUE TITLE
Model::newInstance() calls Models::setTable() unnecessarily 

### ISSUE THREAD

**Issue by ollieread** [laravel/framework#33682]
- Laravel Version: 7.22.4
- PHP Version: 7.4.7
- Database Driver & Version: Mysql 5.7

### Description:
When creating a new instance of a model using `Model::newInstance()` there is a call to `Model::setTable()` using the value returned in `Model::getTable()`.

If you've overridden `Model::getTable()` to do something like add a prefix or suffix to the table name based on a configuration value, the new instance of the model will have a double prefix or suffix.

While I somewhat understand the thought process behind this bit of code, I don't really think it serves a purpose, and I cannot for the life of me find something that breaks if I remove it. 

The same could be said for the call to `Model::setConnection` and `Model::mergeCasts()` though the connection one at least makes some sense and has a sensible fallback.

### Steps To Reproduce:
- Override `Model::getTable()` to add a prefix
- Query the model
- Call `$model->getTable()`

**Comment by driesvints** [comment]
Have you tried this with Pivot models? They override this method.

**Comment by ollieread** [comment]
@driesvints Looking at the code behind the Pivot models there shouldn't be any issues here either.

`Model::getTable()`:

```php
public function getTable()
{
    return $this->table ?? Str::snake(Str::pluralStudly(class_basename($this)));
}
```

`AsPivot::getTable()`:

```php
public function getTable()
{
    if (! isset($this->table)) {
        $this->setTable(str_replace(
            '\\', '', Str::snake(Str::singular(class_basename($this)))
        ));
    }

    return $this->table;
}
```

All that the pivot model does is generate a table name as singular, not plural.

The particular project I was having issues with was also having the same issue with pivot models. The setting of the table would still duplicate prefixes or suffixes added by the overridden `getTable()` method.

**Comment by driesvints** [comment]
In that case feel free to attempt a PR to see if Taylor would accept it. Thanks.
