### ISSUE TITLE
Logging in or registering occasionally hangs indefinitely.

### ISSUE THREAD

**Issue by jaesung2061** [laravel/framework#33689]
- Laravel Version: 7.22.2
- PHP Version: 7.3.10
- Database Driver & Version: Mysql v5.7.28

### Description:
About 10-20% of the time, on both local and production servers, logging in or registering causes the browser to start loading (the spinner on the tab starts going), but never finishes. The request never times out. Refreshing the page logs the user in as intended.

I've made no changes to the default auth scaffolding.

This Reddit thread shows others have the same problem:

https://www.reddit.com/r/laravel/comments/hzguta/laravel_sometimes_hangs_on_login_or_registration/

### Steps To Reproduce:
Attempt to log in or create a new account using standard Laravel auth scaffolding.

**Comment by driesvints** [comment]
Moving to discussions.
