### ISSUE TITLE
inserting issues

### ISSUE THREAD

**Issue by frankgreen1** [laravel/framework#33693]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
Fatal error: Uncaught Error: Class 'Illuminate\Support\Facades\Route' not found in C:\wamp64\www\frank\routes\web.php:35 Stack trace: #0 {main} thrown in C:\wamp64\www\frank\routes\web.php on line 35

this is the error i got please can anybody help me with these issues?

**Comment by ahinkle** [comment]
Please completely fill out the template. 

I would advise closing this issue as this isn't a bug with the framework directly. Please check [Laracasts](https://laracasts.com/discuss), [Laravel.io/forum](https://laravel.io/forum), or the [Laravel Discord channel](https://discordapp.com/invite/mPZNm7A) for support.
