### ISSUE TITLE
It is not possible to add plain text to a MailMessage in a Notification

### ISSUE THREAD

**Issue by Jubeki** [laravel/framework#33699]
- Laravel Version: v7.22.4
- PHP Version: v7.4.3
- Database Driver & Version: MySQL v5.7.24

### Description:
It is possible to send a html and plain email with a Mail which extends Mailable. If you want to send a Notification and want to send a html and plain email then you get an error because it is not possible to attach a plain view.

#### Not working example with notifications:
1. Create a new notification with `php artisan make:notification TestNotification`
2. Add the following Code to the notification:
```php
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->view('mail.test.html')
            ->text('mail.test.plain'); // Not existing
    }
```
3. Execute the toMail-Method

#### Working Example with Mails:
1. Create a new notification with `php artisan make:notification TestNotification`
2. Add the following aode to the notification:
```php
    public function build()
    {
        return $this->view('mail.test.html')
            ->text('mail.test.plain');
    }
```
3. Try to send Mail

**Comment by driesvints** [comment]
MailMessages from notifications work a little different so this isn't possible. If you want to adjust or improve something here feel free to send in a PR. Thanks.
