### ISSUE TITLE
[7.x] Blade fails using Component Methods. Undefined Variable.

### ISSUE THREAD

**Issue by lomotech** [laravel/framework#33690]
- Laravel Version: 7.22.4
- PHP Version: 7.4.8
- Database Driver & Version: -

### Description:
I'm trying to access a public accessed function from my component class in blade but it fails with undefined variable error triggered.

### Steps To Reproduce:

1. Create component.

2. Add a function
`public function isSelected($option)
    {
        return $option === $this->selected;
    }`

3. Try to access it via component blade view
`{{ $isSelected() }}`

4. Error triggered.
`ErrorException
Undefined variable: isSelected`

Note: I'm using Livewire. Don't know if it related or not.
Note2: Do not sure if its same issue with #31733 or not.

**Comment by voyula** [comment]
Try {{ $isSelected }}

**Comment by lomotech** [comment]
> Try {{ $isSelected }}

Same error triggered. I'm following example in the docs https://laravel.com/docs/7.x/blade#displaying-components

<img width="316" alt="Screenshot 2020-07-29 at 10 53 58" src="https://user-images.githubusercontent.com/7269466/88751299-ddcac680-d189-11ea-9cbb-e915177ffbe2.png">

**Comment by voyula** [comment]
Retry: {{ $isSelected('option-1') }}

**Comment by lomotech** [comment]
> Retry: {{ $isSelected('option-1') }}
> 
> I don't using Blade Components, but i tries to help you.

Thanks for your reply.

Unfortunetly, still same error triggered.

**Comment by voyula** [comment]
Hmm, I think I can't help for now.

**Comment by lomotech** [comment]
Nevermind, coz this is not an urgent project.

**Comment by voyula** [comment]
I was tried with clean fresh project and not have a problem for me.

**Comment by lomotech** [comment]
I will retry back with fresh project.

**Comment by voyula** [comment]
```php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public function isSelected($option) {
        return $option;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.alert');
    }
}
```
resources/views/components/alert.blade.php
```php
<div>
    {{ $isSelected('f') }}
    <!-- Simplicity is an acquired taste. - Katharine Gerould -->
</div>
```

resources/views/index.php
```html
<x-alert></x-alert>
```

**Comment by lomotech** [comment]
I've try with fresh, still same. There is any method for me to debugging this?

**Comment by voyula** [comment]
Can you create a GitHub repository with your project to find the problem.

**Comment by lomotech** [comment]
https://github.com/lomotech/laravel-component

But I think you will have no problem since it's just a clean project.
I've try to change PHP version in my machine to 7.3.20 but still not success.

Note: im using macOS catalina + valet. PHP install using brew.

**Comment by lomotech** [comment]
If I'm testing with laravel playground, its working.

https://laravelplayground.com/#/snippets/306f2e07-f905-4715-b167-2abad2d27494

Then i think it's come from my machine. But why...

**Comment by voyula** [comment]
Type to terminal;

composer clear-cache

And type in clean project folder;
rm -rf vendor
rm -rf composer.lock
rm -rf bootstrap/cache/*

And install clean project.

**Comment by lomotech** [comment]
Still same. There is one more thing that I've counter, I don't know if its related or not.
I can't edit value that come from <x-alert test="test"> in the class.
It will show same "test" value in component.
Seems it have been static / immutable. This problem only happen in component class for this time being.

**Comment by lomotech** [comment]
i close for this time being since its not laravel problem at several test.
maybe need to reinstall my php.

**Comment by aisthetes** [comment]
php artisan view:clear help me with this.

**Comment by aranes-rc** [comment]
Have you been able to fix this?
