### ISSUE TITLE
CookieValuePrefix patch broke test requests ->withCookie()

### ISSUE THREAD

**Issue by josiasmontag** [laravel/framework#33696]
- Laravel Version: 7.22.4
- PHP Version: 7.4.6

### Steps To Reproduce:

The following test fails:

```php
Route::middleware([EncryptCookies::class])->group(function () {
    Route::get('/test', function (Request $request) {
        return $request->cookie('test');
     });
});

$response = $this
    ->withCookie('test', 'value')
    ->get('/test');

$response->assertSeeText('value');
```

### Fix

The bug seems to be in [MakesHttpRequests](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L604). 
The line should be:

```php
return encrypt(CookieValuePrefix::create($key, app('encrypter')->getKey()).$value, false);
```

**Comment by driesvints** [comment]
Works fine for me in the version you're reporting.

**Comment by josiasmontag** [comment]
@driesvints Okay, it seems to work if the `APP_KEY` is base64 encoded. This bug happens if the key is just a random string:

```php
config(['app.key' => Str::random(32)]);
```

**Comment by bytestream** [comment]
@josiasmontag behaviour updated to handle your case here - https://github.com/laravel/framework/commit/84765753ee164e7b0978021c4d42711011aed340
