### ISSUE TITLE
Query clauses 'leak' from primary model's over-ridden newQuery() method into eager-loading query for morphMany relationship

### ISSUE THREAD

**Issue by jonnott** [laravel/framework#33695]
- Laravel Version: 7.22.4
- PHP Version: 7.3.9
- Database Driver & Version: MySQL 5.7.26

### Description:
If you've over-ridden a newQuery() on a model, adding extra query clauses subsequent to `parent::newQuery()`, AND the model has a polymorphic one-to-many relationship, AND you eager-load that relationship, the query clauses set in the newQuery() are somehow also being applied to the relationship eager-loading query. This will cause SQL errors if the related model doesn't also have the table columns those clauses are referencing.

Short version: the query clauses from the primary model's newQuery() method shouldn't factor in the eager-loading query for the related model, but in the case of a morphMany relationship, they seem to.

### Steps To Reproduce:
Making something similar to the polymorphic one-to-many example in the Laravel docs...

```
Table structure

foobars
    id - integer
    name - string

foobar_comments
    id - integer
    comment - text
    commentable_id - integer
    commentable_type - string
    exclusive_field - string (nullable) (this is importantly only in this table, not the other)
```

(Then add an entry with id '1' in each table and make the relationship between the two using `commentable_id` and `commentable_type` = 'App\Foobar')

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FoobarComment extends Model
{
    public function newQuery()
    {
        $query = parent::newQuery();

        $query->whereNull('exclusive_field');

        return $query;
    }

    public function commentable()
    {
        return $this->morphTo();
    }
}

```

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foobar extends Model
{
    public function comments()
    {
        return $this->morphMany('App\FoobarComment', 'commentable');
    }
}
```

Then a simple closure route like this..

```
Route::get('/polytest', function () {
    $comments = FoobarComment::with('commentable')->get();
});
```

...will result in an error when querying to eager-load the `commentable` relationship:

```
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'exclusive_field' in 'where clause' (SQL: select * from `foobars` where `exclusive_field` is null and `foobars`.`id` in (1))
```

The `exclusive_field is null` clause should NOT be included in this query on the related `foobars` table.

The first query that is run to get the primary model(s) includes the clause and works correctly:

```
select * from `foobar_comments` where `exclusive_field` is null
```

**Comment by jonnott** [comment]
For context, the example given above is obviously a simple-as-possible scenario to evidence the issue in a fresh-Laravel-app context.

Where this is actually causing us a problem is a more complex real-world scenario where there are actually multiple different models involved in the polymorphic one-to-many relationship, and the over-riding of newQuery() on models is in order to facilitate a quite bespoke multi-tenanting setup.

Additionally, the real-world app is still running Laravel 5.8 in production, so this issue has been around since 5.8 at least (and looking at laravel/framework git blame, there's nothing to suggest it didn't exist earlier in 5.x too, perhaps even as long as polymorphic relationships have existed in Eloquent)..

**Comment by jonnott** [comment]
NB Fetching the `commentable` relationship works fine with lazy-loading instead..

```
    $comment = FoobarComment::first();
    $foobar = $comment->commentable;
    dd($comment);
```

.. will dump out the `FoobarComment` with the `Foobar` instance showing under `relations`, no problem.

**Comment by jonnott** [comment]
Furthermore, if the additional clause on the primary model is added via a global scope, instead of via `newQuery()`, then the eager-loaded relationship also works fine..

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FoobarComment extends Model
{
    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(function ($query) {
            $query->whereNull('exclusive_field');
        });
    }

    public function commentable()
    {
        return $this->morphTo();
    }
}
```

*Works:*

```
Route::get('/polytest', function () {
    $comments = FoobarComment::with('commentable')->get();
});
```

So the problem appears to exhibit only with `newQuery()` over-riding.

**Comment by jonnott** [comment]
Turns out we're now re-thinking the way we do our tenanting, looking to use a combination of global scopes and the `boot()` method, rather than over-riding `newQuery()`, to get around this 'issue'..

Whether this is a 'bug', or just a strange anomaly exhibiting due to the specific combination of things going on (`newQuery()` over-ride, plus a polymorphic one-to-many) .. I don't know enough about Eloquent's internal mechanics to even guess. Also there's the question of whether `newQuery()` over-riding is even a legitimate way to add 'universal' conditions into model queries.

Would be good to get thoughts from @taylorotwell and/or @reinink on this, as the author and de-facto-world-expert on Eloquent, respectively.. ;)

**Comment by driesvints** [comment]
Hey @jonnott. I'm gonna leave this one to @taylorotwell.

Personally I wouldn't recommend overriding `newQuery` as it could potentially lead to complications (like the above).

**Comment by reinink** [comment]
Yeah so my recommendation would be to try and find a  more"first class" way to solve this. I literally never override the `newQuery()` method. For example, maybe you could simply add a global scope to your model instead:

```php
class FoobarComment extends Model
{
    protected static function booted()
    {
        static::addGlobalScope('not_exclusive', fn ($query) => $query->whereNull('exclusive_field'));
    }
    
    public function commentable()
    {
        return $this->morphTo();
    }
}
```

Now, I'm not sure this actually solves your particular problem (I honestly haven't dug deep enough), but it might, since you could optionally remove the global scope when it's causing issues.

**Comment by jonnott** [comment]
I'd be interested in why `newQuery()` has `public` visibility rather than `protected`, if we're not meant to over-ride it.

**Comment by driesvints** [comment]
@jonnott because it can still be used to get a new query builder instance for an existing model to build up queries. But it's only meant for basic queries and not meant to be overridden. I'll try to send in a PR to the docs for this.

**Comment by driesvints** [comment]
https://github.com/laravel/docs/pull/6217

**Comment by driesvints** [comment]
We'd like to find out the root cause of this issue before we do any change.

**Comment by rodrigopedra** [comment]
Hi @driesvints , from the issue description it seems to be related to these pieces of code:

https://github.com/laravel/framework/blob/75792f4c6945749046d4ec1ce560b04640d36b99/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L256-L261

Which in turn calls:

https://github.com/laravel/framework/blob/75792f4c6945749046d4ec1ce560b04640d36b99/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L275-L278

Problem seems to be that as the `morphTo` doesn't know which is the related model when eager loading it creates a new query based from the base model, not from the related model, like other relation factory methods do.

So the changes applied by overriding the `newQuery` method on the base model are "leaked" into the query built for fetching the related instances.

I couldn't come up with a solution for this, ass when eager loading it is hard to know what the related model will be without hinting it, or maybe fetching one database record (in that case it could fail if there are no related models yet).

Another option would be to add a `cloneWithoutBindings` to the query builder and use it there.

Hope it helps.

**Comment by jonnott** [comment]
> Hi @driesvints , from the issue description it seems to be related to these pieces of code:

This was approximately where I thought the problem might lie when I was originally trying to step through the code and (naively) diagnose..

**Comment by taylorotwell** [comment]
Yeah, I don't see a great way to "fix" this without just duplicating the content of `newQuery` into the `HasRelationships@morphEagerTo` method. That's an option but in general I agree you shouldn't modify `newQuery` as that really sounds like a road to even more headaches.

**Comment by jonnott** [comment]
Thanks @taylorotwell and @reinink for your input.

We've subsequently completely rewritten our tenancy code using global scopes instead, and it's working nicely.

**Comment by reinink** [comment]
@jonnott Glad to hear, and happy to help! That sounds better for sure. 💪
