### ISSUE TITLE
Auth:api always unauthenticated after update to Laravel version 6.18.29

### ISSUE THREAD

**Issue by itepifanio** [laravel/framework#33698]
- Laravel Version: 6.18.12
- PHP Version: 7.3.2
- Spark: 7.0 

### Description:
I try to update to Laravel 6.18.29, this updates requested two packages ` doctrine/inflector ` and ` symfony/polyfill-php7.3 `, after installed this two packages I could update Laravel with `composer update laravel/framework `, but after the updated all my requests from my api came with 401 error "Unauthenticated". 
I'm able to uses the web auth and stuff, but the API doesn't work. My project uses spark, so in my auth.php file exists this config:

```php
'api' => [
        'driver' => 'spark',
],
```

I have to make other change to this update work on my project?

**Comment by taylorotwell** [comment]
Please update to the latest Spark release which provides compatibility with the latest Laravel 6.x patch.
