### ISSUE TITLE
Shared sessions with the Session Driver "Database"

### ISSUE THREAD

**Issue by jack85811** [laravel/framework#33703]
- Laravel Version: 7.22.4
- PHP Version: 7.3.10
- Database Driver & Version: pgsql 12

### Description:

hello!
I have a use case where i have two Laravel applications running. Both of them connect to the same database and both of them are using the same session driver "database". Each of them are on a different subdomain. This allows my users to be logged in, when they switch the application, without questioning that it is a different application.
Since both application  are connected to the same DB, they will always check if the session is valid and pass them  to the the secured routes. This worked all well with the laravel version 7.18.0. Since the version 7.22.4 it doesn't work anymore.
When going from App A to App B laravel will perform the standard auth check with the result of throwing the unauthorized exception, so that the user has to login again. laravel/framework/Auth/Middleware/Authenticate.php
![image](https://user-images.githubusercontent.com/26297983/88907554-0c63a280-d259-11ea-8605-7cfbfbf11992.png)

This means, that it does not recoignize the shared domain somehow, which i have been setting for both applications.

### Steps To Reproduce:
    1) Share the cookies, sessions and users between the applications
    2)  Use the same encryption key
    3) Use the same domain & Database
    
The following ENV variables have to be set, so that this will work
SESSION_DRIVER=database
SESSION_CONNECTION=common_database
SESSION_DOMAIN=".example.com"
APP_KEY=base64:322138fdsfbnaffsadfasf //needs to be the same in both

i recommend checking out Zsolt Gyures guide, which i used for my implementation.
https://github.com/laravel/framework/issues/new?template=1_Bug_report.md

I'm curious to hear from you guys, since I've been reading your update on the cookie security release!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jack85811** [comment]
But this is currently working with laravel 7.18.0!
how can this then not be working in version  7.22.4?

**Comment by voyula** [comment]
Yes, Laravel no longer supports distributed sessions since version 7.22.4 release.

**Comment by canthis** [comment]
@jack85811 Any progress and luck with this? I'm having similar problems authenticating to private Broadcast channel since cookies security update. 

I'm on Laravel version 6.18.31, and on 6.18.26 everything worked just fine.

**Comment by jack85811** [comment]
@canthis i'am very sorry, i forgot to update this issue! Yes i resolved it!
So as the cookie update post said, i upgraded all instances to the new version.
what i found out, is that my repo had a composer lock file in it ...
so overall my bad, because my CI/CD pipeline always ran the composer install with the version 7.15.0 of the laravel/framework.

i found it out the hard way by stepping into each app with running the php artisan --version cmd.
Keep in mind that laravel can not process the cookie in the same way that like in the versions < 7.22.4, since it hashes the cookie first before encryption and it compares this hash after the decryption. So whatever your guard is doing, keep this in mind!

I hope you can solve your problem :)

**Comment by canthis** [comment]
Thanks for your response and findings @jack85811, those helped me out to understand and solve my problem!

Cheers :)
