### ISSUE TITLE
Job::dispatchAfterResponse() not dispatching from model observer

### ISSUE THREAD

**Issue by geodro** [laravel/framework#33702]
- Laravel Version: 7.22.4
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
Queueable jobs are not dispatching from model observers after the response is sent

### Steps To Reproduce:

`class UserObserver {`
&nbsp;&nbsp;&nbsp;&nbsp;`public function created(User $user): void`
&nbsp;&nbsp;&nbsp;&nbsp;`{`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Job::dispatchAfterResponse($user);`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
`}`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by yooouuri** [comment]
I don't know if its related.

Controller method:

```
use App\Jobs\StoreClient as StoreClientJob;

public function store(StoreClientRequest $request): Response
{
    $validated = $request->validated();

    StoreClientJob::dispatchAfterResponse($validated);

    return \response()->view('admin.client.create');
}
```

StoreClient(Job):
```
<?php

namespace App\Jobs;

use App\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class StoreClient implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable;

    protected $client;

    /**
     * Create a new job instance.
     *
     * @param array $client
     */
    public function __construct(array $client)
    {
        $this->client = $client;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        [ 'email' => $email, 'contact_person' => $contact_person ] = $this->client;

        sleep(5);

        $user = new User();
        $user->name = $contact_person;
        $user->email = $email;
        $user->password = Hash::make(Str::random());
        $user->save();
    }
}
```

When I run the following, during the POST it sleeps for 5 second. I configured redis and nothing is send to the queue, the worker command does not show anything... Use `StoreClientJob::dispatch($validated);` instead of `StoreClientJob::dispatchAfterResponse($validated);` sends it to the queue.
