### ISSUE TITLE
Task Scheduling using withoutOverlapping with APC cache driver doesn't work.

### ISSUE THREAD

**Issue by ft525** [laravel/framework#33701]
- Laravel Version: 6.18.0
- PHP Version: 7.3.12
- PHP Extensions:
	apc: 1.0.5
	apcu: 5.1.18

### Description:
When cache driver set to "apc", the tasks with "withoutOverlapping" will not be executed.
Please see the following sample.

### Steps To Reproduce:

```php
// .env
CACHE_DRIVER=apc


// ./app/Console/Kernel.php
$schedule->call(function () {
	// Can not be executed with "withoutOverlapping".
	\Illuminate\Support\Facades\Log::debug("Task 1 doesn't work.");
})->cron('* * * * *')->name('Task-1')->withoutOverlapping();

$schedule->call(function () {
	// Can be executed without "withoutOverlapping".
	\Illuminate\Support\Facades\Log::debug('Task 2 works correctly.');
})->cron('* * * * *')->name('Task-2');
```

```php
// I also tried apc cache, to make sure it works normally.
$ttl = 10;
\Illuminate\Support\Facades\Cache::put('key', 'value', $ttl);
```

----------

```php
// .env
CACHE_DRIVER=file (or non-apc)


// ./app/Console/Kernel.php
$schedule->call(function () {
	// Can be executed when cache driver is non-apc.
	\Illuminate\Support\Facades\Log::debug('Task 3 works correctly.');
})->cron('* * * * *')->name('Task-3')->withoutOverlapping();
```

**Comment by driesvints** [comment]
I can't reproduce this. The tasks execute for me. Please try a support channel:
- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by ft525** [comment]
> I can't reproduce this. The tasks execute for me. Please try a support channel:
> 
I found the problem.
Since my APC setting is "apc.enable_cli = 0", it can't work in cronjob.
Enabled CLI, then it works.
