### ISSUE TITLE
Unit tests extending wrong TestCase class

### ISSUE THREAD

**Issue by sven-ahrens** [laravel/framework#33717]
- Laravel Version: 7.19.1
- PHP Version: 7.2.5
- Database Driver & Version: MySQL & 5.7

### Description:
When creating a new unit test: ``php artisan make:test UserTest --unit`` the generated class extends **the wrong TestCase class** (``use PHPUnit\Framework\TestCase;``)

The problem with that is, that if you depend on service containers, laravel has not been able to create the application yet.

So if you try to load a language string like for instance: ``__('auth.failed')`` then you get the following error:

> Target class [translator] does not exist.

To solve this problem, laravel should actually extend this class: ``use Tests\TestCase;`` which actually creates the app by default

```
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
}
```

### Steps To Reproduce:

1. Create an unit test: ``php aritsan make:test UserTest --unit``
2. Try to load a language string with ``__('auth.failed')``
3. You should get an error: ``Target class [translator] does not exist.``

**Comment by driesvints** [comment]
Hey Sven. They don't actually. Unit tests aren't meant to initialize the framework. If you need the framework either write a feature test or feel free to change this in your own app.
