### ISSUE TITLE
Array cookies are not supported anymore

### ISSUE THREAD

**Issue by halaei** [laravel/framework#33722]
- Laravel Version: 6.18.31
- PHP Version: 7.2.31
- Database Driver & Version: none

### Description:
Reading `Illuminate\Cookie\Middleware\EncryptCookies::decryptCookie()`, I think Laravel supports some sort of array cookies, but after the recent changes, it is not handled anymore in decrypt method.

### Steps To Reproduce:
Hitting the following route once will break the app and no further requests can be handled if EncryptCookies middleware is enabled:

```php
Route::get('/test', function () {
    Cookie::queue(Cookie::make('x[0]', 'value', 60));
    Cookie::queue(Cookie::make('x[1]', 'value2', 60));
    return request()->cookie();
});
```

Error:
```
ErrorException thrown with message "strpos() expects parameter 1 to be string, array given"

Stacktrace:
#32 ErrorException in /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:86
#31 strpos in /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:86
...
```

**Comment by taylorotwell** [comment]
I don't have a good fix for this at the moment.

**Comment by lagbox** [comment]
@taylorotwell  is this still not an issue since you don't have a good fix ... or do you just think this isn't an actual issue?   because I can't see a reason to close an issue without solving it if it is valid (perhaps my lack of imagination)

**Comment by driesvints** [comment]
@lagbox afaik this was undocumented to be used as such. I do realise this is natively to how PHP handles them but I'm afraid with the recent security changes we can't support them like that anymore. Might be worth pr'ing to the docs..

**Comment by lagbox** [comment]
@driesvints thanks for your explanation ... looks really odd from the outside to just see "i dont have a good fix" therefore closed

**Comment by halaei** [comment]
@driesvints maybe it's good to just change the code so that it ignores those cookies without rasing a fatal error?

**Comment by driesvints** [comment]
@halaei we can't do that without reintroducing the security issue.

**Comment by halaei** [comment]
@driesvints  Sorry maybe I explained ot wrong. I mean setting the cookie to null if it is an array.

**Comment by driesvints** [comment]
@halaei gotcha. Might be a good alternative yeah.
