### ISSUE TITLE
artisan command names with dash are parsed improperly

### ISSUE THREAD

**Issue by plakhin** [laravel/framework#33723]
- Laravel Version: 7.13.0 (same in 6.18.31)
- PHP Version: 7.4.8
- Database Driver & Version -:

### Description:
Artisan commands with dash in name are also executed when calling with only first part of name (before dash).

### Steps To Reproduce:
`php artsian auth:clear` calls `auth:clear-resets` (`php artsian auth:clear` === `php artsian auth:clear-resets`)
`php artisan dump` calls `dump-server` `(php artisan dump` === `php artisan dump-server`)

**Comment by taylorotwell** [comment]
This wouldn't be a Laravel issue. Would be a Symfony Console thing.
