### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by DUDU54** [laravel/framework#33735]
- Laravel Version: 7.11.0
- PHP Version: 7.4.6
- Database Driver & Version: Mysql Community Server 8.0.19

### Description:
Hello, i'm developing an api for an android/iOS app and i implemented a picture upload. The developer of the app got a bug with the upload. On telescope, he got the error bellow
![image](https://user-images.githubusercontent.com/14166148/89131965-0b5c9a80-d511-11ea-9586-8c7e4f5f7244.png)
In the payload tab, it show `size: 0` but the content of the picture is not empty
![image](https://user-images.githubusercontent.com/14166148/89131970-16afc600-d511-11ea-9288-230ffea2759b.png)
after some research, i figured out that the size of the picture is more than the `upload_max_filesize`
![image](https://user-images.githubusercontent.com/14166148/89131976-1ca5a700-d511-11ea-8dd8-c8d1d2280c62.png)
after rising the limit, it's now working and show the correct size and upload the file as it should
![image](https://user-images.githubusercontent.com/14166148/89131973-19aab680-d511-11ea-95d2-739a210ecfc3.png)

I don't know if it's real bug or a correct reaction of laravel, maybe it should say a different message because it's hard to know the origin of the error: "The pictures.0 failed to upload.".
### Steps To Reproduce:
create a post endpoint with image validation and upload a file larger than the `upload_max_filesize`

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. As you pointed out, the issue is that your upload_max_filesize is too low. :)

**Comment by GrahamCampbell** [comment]
There's no way for Laravel to tell the difference between a genuine zero-byte file upload, and busting PHP's max filesize limit.

**Comment by GrahamCampbell** [comment]
Laravel does the right thing, in validating and rejecting the input.
