### ISSUE TITLE
Make ValidationException message localizable.

### ISSUE THREAD

**Issue by whoacowboy** [laravel/framework#33741]
- Laravel Version: 7.22.4

### Description:
**framework/src/Illuminate/Validation/ValidationException.php**
It would be helpful if we could localize the ValidationException message

### Steps To Fix:
Change
```
    public function __construct($validator, $response = null, $errorBag = 'default')
    {
        parent::__construct('The given data was invalid.');

        $this->response = $response;
        $this->errorBag = $errorBag;
        $this->validator = $validator;
    }
```

to

```
    public function __construct($validator, $response = null, $errorBag = 'default')
    {
        parent::__construct(__('validate.data_invalid'));

        $this->response = $response;
        $this->errorBag = $errorBag;
        $this->validator = $validator;
    }
```

Then add a line to `resources/lang/en/validate.php`

```
...
'data_invalid' => 'The given data was invalid.',
...
```

I can send over a PR if it's helpful.

**Comment by driesvints** [comment]
No, this has been tried many times in the past. This message isn't something that's meant for user land. Implement your own localized message in your app please.
