### ISSUE TITLE
Composer production command no remove symfony/var-dumper package

### ISSUE THREAD

**Issue by alejandroguille** [laravel/framework#33757]
- Laravel Version: 7.22.2
- PHP Version: 7.3
- Database Driver & Version: Mysql 5.7

### Description:
After executing this command `composer install --no-dev -o`
the package **symfony/var-dumper** is not **deleted** and is still loaded by the autoload generating extra load.

### Steps To Reproduce:
`composer install --no-dev -o`
In code  `dump('Hello')` <-- this works perfectly

I think it shouldn't work in ENV=dev ...

regards.

**Comment by driesvints** [comment]
Probably by a sub dependency. Anyway this isn't the place for this, please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by mfn** [comment]
@alejandroguille `composer depends symfony/var-dumper` can help you figuring this out

**Comment by alejandroguille** [comment]
facade/flare-client-php  1.3.4    requires  symfony/var-dumper (^3.4|^4.0|^5.0)       
facade/ignition          2.3.5    requires  symfony/var-dumper (^5.0)                 
laravel/framework        v7.23.0  requires  symfony/var-dumper (^5.0)                 
laravel/tinker           v2.4.1   requires  symfony/var-dumper (^4.3|^5.0)            
psy/psysh                v0.10.4  requires  symfony/var-dumper (~5.0|~4.0|~3.0|~2.7)  
symfony/error-handler    v5.1.3   requires  symfony/var-dumper (^4.4|^5.0)

**Comment by alejandroguille** [comment]
Is un bug in laravel 7.23 - require "symfony/var-dumper": "^5.0",

**Comment by driesvints** [comment]
@alejandroguille this isn't a bug. Like the output from above shows, numerous packages require this dependency.

**Comment by alejandroguille** [comment]
> @alejandroguille this isn't a bug. Like the output from above shows, numerous packages require this dependency.

Yes, but in **require-dev** instead **require**

**Comment by driesvints** [comment]
No, in `require`: https://github.com/facade/ignition/blob/master/composer.json#L23

**Comment by alejandroguille** [comment]
Simple the creators recommend putting in require-dev, because in production it affects performance,
![image](https://i.ibb.co/pfTB3CJ/Selecci-n-146.png)

**Comment by driesvints** [comment]
@alejandroguille you'll need to open an issue on the repos of the packages from above in that case.

**Comment by driesvints** [comment]
Actually you're right in that we also use this ourselves in our own "require": https://github.com/laravel/framework/blob/7.x/composer.json#L43

But that's because we use this [here](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Stringable.php#L7) and [here](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Traits/EnumeratesValues.php#L16). And that isn't going to change any time soon sorry.

**Comment by alejandroguille** [comment]
you're right, there is dependency there!
