### ISSUE TITLE
touches property does not fire update event in hasMany relationship

### ISSUE THREAD

**Issue by mrhn2005** [laravel/framework#33759]
- Laravel Version: 6.18.31
- PHP Version: 7.4.8
- Database Driver & Version: Mysql 5.7

### Description:
It seems because of batch update of relations updated_at in touchOwners method (`$this->$relation()->touch();`) , updated event does not fire in parent model when using hasMany relationship.
   ```
public function touchOwners()
   {
        foreach ($this->touches as $relation) {
            $this->$relation()->touch();

            if ($this->$relation instanceof self) {
                $this->$relation->fireModelEvent('saved', false);

                $this->$relation->touchOwners();
            } elseif ($this->$relation instanceof Collection) {
                $this->$relation->each->touchOwners();
            }
        }
   }
```

### Steps To Reproduce:
1- create a product and brand model which a brand has many products
2- add `protected $touches = ['products'];` in brand model
3- add observer for products.
4- product updated event will not fire when updating brand

**Comment by taylorotwell** [comment]
Because it doesn't retrieve all the models. It's a batch operation.
