### ISSUE TITLE
[7.x] config:cache fails tests by throwing 419 instead of 302 on redirects

### ISSUE THREAD

**Issue by rennokki** [laravel/framework#33758]
- Laravel Version: Latest 7.x
- PHP Version: 7.4, coming with Homestead
- Database Driver & Version: -

### Description:
The `config:cache` command ran in unit testing throw `419` errors if trying to test the Auth scaffolding.
The below example is just one out of some tests that failed to me inexplicably, throwing 419 instead of 302 redirects.

### Steps To Reproduce:
- Create a new project
- Install laravel/ui and deploy the assets with the `--auth` flag
- Add `'verify' => true` to the `Auth::routes()` in `web.php`
- Create a new feature test and add this in one of the tests:

```php
$this->post(route('verification.resend'))->assertRedirect(route('login'));
```

- Expect the test to pass.
- `php artisan config:cache`
- Rerun tests, they fail:

```
Response status code [419] is not a redirect status code.
Failed asserting that false is true.
```

**Comment by driesvints** [comment]
Don't run this locally.
