### ISSUE TITLE
Markdown mail::panel shows RAW HTML

### ISSUE THREAD

**Issue by tosettil-polimi** [laravel/framework#33769]
- Laravel Version: 7.x
- PHP Version: 7.4.7 (Win x64)
- Database Driver & Version:
jenssegers/laravel-mongodb 3.6.4
### Description:
Same of [#31076](https://github.com/laravel/framework/pull/31076/commits/a7aaf16bfcd96688d4c738e0ba6267f7094bb741) in version 6.x

### Steps To Reproduce:
0. Install fresh laravel installation and setup SMTP...

1. Create App/Mail/TestMail.php
```
...

public function build()
{
    return $this->subject('test markdown error')
                ->markdown('email');
}
```

2 .Create resources/views/email.blade.php
```
@component('mail::message')
# Hello

@component('mail::panel')
This is the panel content.
@endcomponent

@endcomponent
```
3. Send email
`Mail::to('your@email.com')->send(new TestMail);`

4. Email with markdown panel component will be broken.
![image](https://user-images.githubusercontent.com/24563313/89533072-1d7d5800-d7f3-11ea-96d7-b5557743056a.png)

Solution:
In `Illuminate\Mail\Markdown:parse`
change this
```
    /**
     * Parse the given Markdown text into HTML.
     *
     * @param  string  $text
     * @return \Illuminate\Support\HtmlString
     */
    public static function parse($text)
    {
        $environment = Environment::createCommonMarkEnvironment();

        $environment->addExtension(new TableExtension);

        $converter = new CommonMarkConverter([
            'allow_unsafe_links' => false,
        ], $environment);

        return new HtmlString($converter->convertToHtml($text));
    }
```

to this:

```
    /**
     * Parse the given Markdown text into HTML.
     *
     * @param  string  $text
     * @return \Illuminate\Support\HtmlString
     */
    public static function parse($text)
    {
        $environment = Environment::createCommonMarkEnvironment();

        $environment->addExtension(new TableExtension);

        $converter = new CommonMarkConverter([
            'allow_unsafe_links' => false,
        ], $environment);

        $text = preg_replace("/^\\h+/m", '', $text->toHtml());

        return new HtmlString($converter->convertToHtml($text));
    }
```

**Comment by driesvints** [comment]
Please provide code snippets and detailed steps to reproduce.

**Comment by tosettil-polimi** [comment]
The steps and error below:

0. Install fresh laravel installation and setup SMTP...

1. Create App/Mail/TestMail.php

`...

public function build()
{
    return $this->subject('test markdown error')
                ->markdown('email');
}`

2 .Create resources/views/email.blade.php
`@component('mail::message')
# Hello

@component('mail::panel')
This is the panel content.
@endcomponent

@endcomponent`
3. Send email
Mail::to('your@email.com')->send(new TestMail);

4. Email with markdown panel component will be broken.
![image](https://user-images.githubusercontent.com/24563313/89533072-1d7d5800-d7f3-11ea-96d7-b5557743056a.png)

**Comment by tosettil-polimi** [comment]
The steps and error below:

0. Install fresh laravel installation and setup SMTP...

1. Create App/Mail/TestMail.php
```
...

public function build()
{
    return $this->subject('test markdown error')
                ->markdown('email');
}
```

2 .Create resources/views/email.blade.php
```
@component('mail::message')
# Hello

@component('mail::panel')
This is the panel content.
@endcomponent

@endcomponent
```
3. Send email
`Mail::to('your@email.com')->send(new TestMail);`

4. Email with markdown panel component will be broken.
![image](https://user-images.githubusercontent.com/24563313/89533072-1d7d5800-d7f3-11ea-96d7-b5557743056a.png)

**Comment by tosettil-polimi** [comment]
> Please provide code snippets and detailed steps to reproduce.

Updated

**Comment by driesvints** [comment]
Renders just fine for me:

<img width="911" alt="Screenshot 2020-08-06 at 17 23 55" src="https://user-images.githubusercontent.com/594614/89550221-a3a49900-d809-11ea-9563-7a34d2dac9fa.png">

Did you publish the markdown files to your `resources/view/vendor` directory? You might need to publish them again:

```
php artisan vendor:publish --tag=laravel-mail --force
```
