### ISSUE TITLE
belongsToMany doesn't use SoftDeletes trait

### ISSUE THREAD

**Issue by matro-skin** [laravel/framework#33766]
- Laravel Version: 7.22.4
- PHP Version: 7.3.17
- Database Driver & Version: MySQL 8.0.14

### Description:
If we set deleted_at for through-model, we have all items in result anyway

### Steps To Reproduce:
We have models relation like: `ChatThread > ChatParticipant > User`
ChatThread has relations: 
```
    public function participants()
    {
        return $this->hasMany(ChatParticipant::class, 'thread_id', 'id')
                    ->with('user');
    }

    /**
     * Get Users of Thread
     *
     * @return BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(
            User::class,
            with(new ChatParticipant)->getTable(),
            'thread_id',
            'user_id'
        );
    }

```
and we have 3 records of ChatParticipant
then we delete one record from ChatParticipant
and have
```
$thread->participants->count(); // 2
$thread->users->count(); // 3
```
But we expect to see 2 records both of relations.

P.S. `ChatThread` and `ChatParticipant` models use `SoftDeletes` trait, `User` doesn't use it

**Comment by ledungsbacken** [comment]
This is expected behavior. The `participants` relation is uses the `ChatParticipant` model while the `users` relation does not.
All you are doing is grabbing the table name, nowhere do you say that it should use soft deletion.

**Comment by matro-skin** [comment]
Really expected?
We have tree with 10 branches, each branch has 10 leaves.
Total 10 branches and 100 leaves.

Let's break one branch. We have 9 branches, but still 100 leaves. Really that's we expect?)

**Comment by matro-skin** [comment]
My pivot model (ChatParticipant) is an actual Eloquent model, not Pivot.

**Comment by driesvints** [comment]
I think @ledungsbacken explained it well enough.
