### ISSUE TITLE
Type must be 'string' (as in base class '\Illuminate\Database\Eloquent\Model') 

### ISSUE THREAD

**Issue by stonkeep** [laravel/framework#33760]
- Laravel Version: v7.22.4
- PHP Version: 7.4.7
- Database Driver & Version: 7.4

### Description:
was encoded normally when suddenly it started giving the following error

Type of App\Entidade::$table must be string (as in class Illuminate\Database\Eloquent\Model)
Everywhere
someone help me 
I've already reverted the changes and nothing

### Steps To Reproduce:
Example of my code

```
class Entidade extends Model
{
    use Notifiable;
    use SoftDeletes;
    use TrataDataTrait, ModelFieldsTrait, SGPTrait;

    const DELETED_AT = 'dt_removido';

    const CREATED_AT = 'dt_criado';

    const UPDATED_AT = 'dt_atualizado';

    protected $table = 'tb_entidade';

    protected $guarded = ['id'];
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Benoit1980** [comment]
> * Laravel Version: v7.22.4
> * PHP Version: 7.4.7
> * Database Driver & Version: 7.4
> 
> ### Description:
> was encoded normally when suddenly it started giving the following error
> 
> Type of App\Entidade::$table must be string (as in class Illuminate\Database\Eloquent\Model)
> Everywhere
> someone help me
> I've already reverted the changes and nothing
> 
> ### Steps To Reproduce:
> Example of my code
> 
> ```
> class Entidade extends Model
> {
>     use Notifiable;
>     use SoftDeletes;
>     use TrataDataTrait, ModelFieldsTrait, SGPTrait;
> 
>     const DELETED_AT = 'dt_removido';
> 
>     const CREATED_AT = 'dt_criado';
> 
>     const UPDATED_AT = 'dt_atualizado';
> 
>     protected $table = 'tb_entidade';
> 
>     protected $guarded = ['id'];
> ```

I have the exact same issue, did you find a solution please? This happened out of nowhere. 

Thanks

**Comment by samjoyce777** [comment]
I had this, completely out of the blue, on all branches. Restarted computer, containers, composer update and cleared every cache in Laravel project. Still happened. Suspect something corrupted. Deleted repo and recloned and that fixed it.

**Comment by enzostefani507** [comment]
It can be fixed by deleting the vendor folder and then run composer install
