### ISSUE TITLE
Can't register non-namespaced classes as Blade components with `::class` syntax

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/framework#33779]
- Laravel Version: 7.23.0 (`illuminate/view`)
- PHP Version: 7.4.5

### Description:

`$bladeCompiler->component(Thing::class)` doesn't work if the file it's called in, and `Thing::class`, aren't namespaced.

Our use case for this is [Jigsaw](https://github.com/tightenco/jigsaw), a static site generator that uses Blade for templating. We let users customize Blade by [creating a simple `blade.php` file in the root of the project](https://jigsaw.tighten.co/docs/content-blade/#extending-blade-with-custom-directives), into which we inject an instance of the Blade compiler so they can register components, aliases, or custom directives. If that file isn't namespaced, component classes defined within that same file can't be registered: see tightenco/jigsaw#492.

### Steps To Reproduce:

```php
<?php

use Illuminate\Filesystem\Filesystem;
use Illuminate\View\Compilers\BladeCompiler;
use Illuminate\View\Component;

$bladeCompiler = new BladeCompiler(new Filesystem, '/tmp/cache/path');

class Icon extends Component
{
    public function render()
    {
        return '<div>:)</div>';
    }
}

$bladeCompiler->component(Icon::class);
```

This compiles to...

```blade
@component('Icon', 'icon', [])
<?php $component->withAttributes([]); ?>
```

...which will fail—`Icon` isn't recognized as a class, because `CompilesComponents` checks if components are classes by looking for `::class` or `\` in their name:

https://github.com/laravel/framework/blob/75792f4c6945749046d4ec1ce560b04640d36b99/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php#L31-L35

### Workaround:

`$bladeCompiler->component('\\Icon')` or `$bladeCompiler->component('\\' . Icon::class)` both appear to do the trick, but they're ugly and it would be cool if this just worked.

### Possible solution:

We could check if the component is a class:

```diff
-    if (Str::contains($component, ['::class', '\\'])) {
+    if (Str::contains($component, ['::class', '\\']) || class_exists($component)) {
```

The problem is that this of course passes for _any_ global class, including builtins like `Exception`, `stdClass`, `SplFileInfo`, `Closure`, etc. This would cause some pretty weird errors if users have non-class components with those names, since `class_exists()` isn't case-sensitive, so it would pass for something like `exception` or `closure` and then try to actually use that builtin class as a Blade component.

Thoughts?

**Comment by driesvints** [comment]
Hey @bakerkretzmar. This sounds more like a feature request. Happy to look at a PR if you could whip one up. Thanks.
