### ISSUE TITLE
cache folders permission

### ISSUE THREAD

**Issue by alexeydg** [laravel/framework#33770]
- Laravel Version: v7.21.0
- PHP Version: 7.4.8

If you set 'permission' => 0777 in the cache.php config, then laravel creates a cache file, for example "/cache/data/8e/6b/8e6b66745c4b35dbcd7765ff9123821a5ee03b71" the file 8e6b66745c4b35dbcd7765ff9123821a5ee03b71 itself has the correct permissions 0777, while the created directories 8e and 6b have permissions 0755. This creates difficulties if you clear the cache in the console under a different user, there is no access for the php artisan cache:clear command. This happens because this is the way how mkdir works with recursion; for good reason, all directories need to be set to the same permissions as specified in the config.

**Comment by driesvints** [comment]
Directory permissions is your own responsibility and not the framework's one.

**Comment by buismaarten** [comment]
Please reopen this issue, I didn't change any configuration or permissions and have this issue too on multiple Homestead installations.
