### ISSUE TITLE
Laravel new test stuck on crafting application

### ISSUE THREAD

**Issue by agarwalvaibhav0211** [laravel/framework#33787]
- Laravel Version: #.#.#(Not even creating a laravel folder so not applicable)
- Laravel Installer Version: 3.2.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8.0

### Description:
Whenever I Run `laravel new laravelSite` the installer stucks on `Crafting application...`. I have been waiting for 2 hrs, but no resolution. I tried this same command with `-vvv` but no difference.

### Steps To Reproduce:
Run `laravel new <anynamehere>`

Please help

**Comment by driesvints** [comment]
Works fine for me.

**Comment by agarwalvaibhav0211** [comment]
Can you give some tips to diagnose possible issues??

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
