### ISSUE TITLE
Http Client not sending file streamed from an s3 filesystem

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#33780]
- Laravel Version: 7.23.2
- PHP Version: 7.3.20-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: mysql  Ver 8.0.21

### Description:
Using the Http client and sending an attached file from an s3 driven filesystem - the file is not send in the request.

Using a local filesystem works as expected.

### Steps To Reproduce:

```php
$response = Illuminate\Support\Facades\Http::attach('file', $spatieMediaLibMediaModel->stream())
    ->acceptJson()
    ->post('https://some-endpoint.api');

dd($response->json());

/**
  [
     "message" => "The given data was invalid.",
     "errors" => [
       "file" => [
         "The file must be a file.",
       ],
     ],
   ]
*/
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
