### ISSUE TITLE
first Collection Higher Order Messaging Issue

### ISSUE THREAD

**Issue by archy-bold** [laravel/framework#33784]
- Laravel Version: 6.18.34
- PHP Version: 7.3.19
- Database Driver & Version: MariaDB 10.4.12

### Description:

When using the collection higher order messaging `first`, it returns an instance of `Illuminate\Support\HigherOrderCollectionProxy`, then attempting to access a property on what I would expect to be the first item, it returns that full item, rather than the specific property.

I'd expect the below to return the ID of the first user, instead it returns the first User object.

```php
$users = User::all();
dd($users->first->id); // App\User^ {...
```

Oddly this then returns the ID itself:

```php
dd($users->first->id->id); // 1
```
Am I using this incorrectly? Or is this a bug?

### Steps To Reproduce:

The simplest example would be as follows:

```php
factory(User::class)->create();
$users = User::all();
dd($users->first->id);
```

**Comment by dkulyk** [comment]
`$users->first->id` searches first item where property id is not negative and returns it.
If you need get first item you should use `$users->first()`

**Comment by driesvints** [comment]
Yeah, this isn't exactly how higher order messages work. They can't be used to access attributes like that. Use `$users->first()` if like @dkulyk if you need the first model.

**Comment by archy-bold** [comment]
Ok, thanks for the heads up on that @dkulyk and @driesvints. I'm using the higher order messaging in my case because I want to use it in a null coalescing statement and functions don't work in that case.

```php
$users = null;
dd($users->first()->id ?? null); // Throws Error: Call to a member function first() on null
dd($users->first()->id->id ?? null); // null
```

I assume it's effectively an argument to the function for those that take it eg `sortBy`, `filter`, etc where others take no arguments eg `sum`, `avg`. Why does `first` act differently to the `first()` function in this case? I can't find this information documented anywhere.

**Comment by driesvints** [comment]
Try `optional($users)->first()->id`.

**Comment by archy-bold** [comment]
Thanks for the tip but I simplified the use case above. I'm actually accessing down a few relationships in my case:

```php
$user->organisation->labels->first->id->id ?? null
````

It seems that would still work anyway because I'm always looking for an item that exists in the database anyway ie it will have a non-negative `id`. It's just not the clearest code to read!

**Comment by driesvints** [comment]
You're not using it correctly that way I'd say. That's why it doesn't reads well. Like I said before, higher order messaging isn't meant to dynamically access attributes. It's to execute certain actions in a shorter way.

**Comment by archy-bold** [comment]
That may be. But then surely `first` is an unusual inclusion in that respect; since the whole point is to access a single item.

Plus the class itself, [HigherOrderCollectionProxy.php#L46](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/HigherOrderCollectionProxy.php#L46), has the functionality to access a property.
