### ISSUE TITLE
Laravel loses added constraits to relationships when restoring models.

### ISSUE THREAD

**Issue by xyxzfj** [laravel/framework#33817]
- Laravel Version: v5.6.14
- PHP Version: 7.1.15
- Database Driver & Version:

### Description:
In laravel, constraints (clousers) can be added to a relationship being loaded. For example:

    $book->load(['owner' => function($query) {
        $query->where('enabled', '=', true);
    }]);

When `$book` is serialized, the closure is missing since it cannot be serialized by php.
So when `$book` is restored with `\Illuminate\Queue\SerializesAndRestoresModelIdentifiers::restoreModel`, the added constraint is gone, which is buggy.

Can this be fixed?

### Steps To Reproduce:

Like in Description.

**Comment by driesvints** [comment]
No, this is impossible to do afaik.

**Comment by xyxzfj** [comment]
> No, this is impossible to do afaik.

Impossible to fix? Any plan to doc this limitation and let the developer avoid using added constraints when a model is possible to be serialized and restored?

**Comment by driesvints** [comment]
@xyxzfj feel free to send in a pr to the docs 👍
