### ISSUE TITLE
Laravel paginate and inRandomOrder

### ISSUE THREAD

**Issue by omidMolaverdi** [laravel/framework#33821]
- Laravel Version: 6.2.28
- PHP Version:7.4
- Database Driver & Version: Mysql

### Description:
I realised that combining `paginate `and `inRandomOrder `ends up the reverse order in the page numbers. To explain it more, if you have a code like below:

```
       $links = DB::table('linkbox')
            ->inRandomOrder('1234')
            ->paginate(4);
```
and imagine that the table has 7 records. In the view I will see 3 records on page 1 and 4 records on page 2. If I drop `inRandomOrder `then the pagination is right [the right order here should be 4 on page 1 and 3 on page 2].

**Comment by driesvints** [comment]
Moving to discussions.
