### ISSUE TITLE
Blade components: Passing through props via $attributes breaks x-tag parsing

### ISSUE THREAD

**Issue by jordyvandomselaar** [laravel/framework#33836]
- Laravel Version: 7.25.0
- PHP Version: PHP 7.4.2

### Description:

When you nest a component like so:

`welcome.blade.php`

```html
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head></head>
    <body>
    <x-foo src="https://festileaks.com/wp-content/uploads/2017/10/Foo-Fighters-press-Brantley-Gutierrez-696x522.jpg"/>
    </body>
</html>
```

`foo.blade.php`

```html
<div>
    <x-bar {{ $attributes }}/>
</div>
```

`bar.blade.php`

```html
<div>
    <img src="{{ $src }}" alt="">
</div>
```

You end up with an actual `<x-bar />` in your `html`.

### Steps To Reproduce:

I've created a minimal reproduction example here: https://github.com/jordyvandomselaar/laravel-components-attributes-bug

**Comment by driesvints** [comment]
You can't pipe through attributes in 7.x like that. In 8.x this is fixed.

**Comment by jordyvandomselaar** [comment]
Alright but 8.x isn't released yet and according to [https://laravel.com/docs/master/releases](https://laravel.com/docs/master/releases), Laravel 7 gets bugfixes until September 3rd.

It strikes me as really odd that it won't get fixed in the currently latest version of Laravel.

**Comment by driesvints** [comment]
@jordyvandomselaar this isn't a bug. It's an unsupported feature for 7.x. We can't implement it in 7.x without breaking a whole lot, including the way people might currently be handling attributes in their apps.
