### ISSUE TITLE
Mimes validation

### ISSUE THREAD

**Issue by vladislavtkachenko** [laravel/framework#33837]
- Laravel Version: 7.25.0
- PHP Version: 7.4.4

### Description:
.pdf files files do not pass validation "mimes:pdf"
->guessExtension() method return "bin"

### Steps To Reproduce:
Upload *.pdf file by axios

**Comment by GrahamCampbell** [comment]
Do you have `ext-finfo` installed?

**Comment by vladislavtkachenko** [comment]
ext-finfo - installed

http://prntscr.com/tybnpd
http://prntscr.com/tyboea

**Comment by GrahamCampbell** [comment]
What does the whole array look like, if you dump it all out, and not just `[0]`?

**Comment by vladislavtkachenko** [comment]
http://prntscr.com/tyc48p

It seems that the problem is specifically with this pdf. Although it opens correctly in acrobat reader and chrome

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vladislavtkachenko** [comment]
https://drive.google.com/file/d/1m852olVDXtLIDw9k2jRKp5Nxf9Lh18cm/view?usp=sharing
