### ISSUE TITLE
Real-time facades make raw calls to storage_path() instead of using the Cache abstraction

### ISSUE THREAD

**Issue by yangm97** [laravel/framework#33839]
- Laravel Version: 7.24.0
- PHP Version: 7.4.9
- Database Driver & Version: none

### Description:

Unfortunately it seems like the facade cache doesn't make use of the Cache abstraction and makes raw calls to `storage_path()` instead, as seen https://github.com/laravel/framework/blob/c2f2867cb1c835fd32c91bc9a772c3ec1ce68894/src/Illuminate/Foundation/AliasLoader.php#L103 and https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Cache/Console/ClearCommand.php#L89 

This creates an issue for lambda (and any kind of hardened read-only filesystem with restricted or no write paths) as the default file storage path is not writeable (see brefphp/laravel-bridge#8). 

While changing the default storage path would fix my specific issue, it comes at the cost of allowing other stuff fail silently, as noted by @mnapoli on https://github.com/brefphp/laravel-bridge/pull/9#issuecomment-672684462

### Steps To Reproduce:

1. Use a [real-time facade](https://laravel.com/docs/7.x/facades#real-time-facades)

**Comment by GrahamCampbell** [comment]
> Use a real-time facade

Could you link us to what that is?

**Comment by yangm97** [comment]
> > Use a real-time facade
> 
> Could you link us to what that is?

You mean this https://laravel.com/docs/7.x/facades#real-time-facades ?

**Comment by taylorotwell** [comment]
Vapor takes care of this by tweaking the storage path environment variables I believe.

**Comment by yangm97** [comment]
> Vapor takes care of this by tweaking the storage path environment variables I believe.

Seeing as Real-Time Facades are the only thing not making use of the cache API I would say it's better to fix it so we can use redis and other cache backends instead of doing this workaround.

**Comment by mnapoli** [comment]
👍  using the cache API sounds like a more generic solution, is there a reason to favor not using the cache API?
