### ISSUE TITLE
countBy method fails if the field name is passed as a string

### ISSUE THREAD

**Issue by linktoahref** [laravel/framework#33847]
- Laravel Version: `7.25.0`
- PHP Version: `7.2.33`
- Database Driver & Version: mysql & `8.0.21`

### Description:

With respect to the commit #33801 
Returns error "Called to undefined function <field name>" on `countBy`  method if the field name is passed as a string.

### Steps To Reproduce:

Laravel version `7.24.0`

    $collection = collect([
        ['type' => 'O+', 'name' => 'John'],
        ['type' => 'O-', 'name' => 'Joe'],
        ['type' => 'O+', 'name' => 'Justin']
    ]);

    $collection->countBy('type');

    // returns
    Illuminate\Support\Collection {#4859
        all: [
            "O+" => 2,
            "O-" => 1,
        ],
    }

Laravel version `7.25.0`

    $collection = collect([
        ['type' => 'O+', 'name' => 'John'],
        ['type' => 'O-', 'name' => 'Joe'],
        ['type' => 'O+', 'name' => 'Justin']
    ]);

    $collection->countBy('type');

    // returns
    Call to undefined function type() in vendor/laravel/framework/src/Illuminate/Support/LazyCollection.php on line 259

**Comment by driesvints** [comment]
Ping @JosephSilber

**Comment by JosephSilber** [comment]
Sorry for breaking that :cry: 

There was no test covering this. I submitted a PR with a fix that also includes the obligatory tests.

**Comment by driesvints** [comment]
Thanks @JosephSilber.
