### ISSUE TITLE
Using the paginate method inside a builder macro

### ISSUE THREAD

**Issue by BoyeMagnus** [laravel/framework#33840]
- Laravel Version: 6.18.31
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 8

### Description:
When using the paginate method within a builder macro, some mapping goes wrong.

### Steps To Reproduce:
1. Add some data
```
CREATE TABLE `cars` (`id` int, PRIMARY KEY (id));
CREATE TABLE `people` (`id` int AUTO_INCREMENT,`first_name` varchar(255), PRIMARY KEY (id));
CREATE TABLE `car_person` (`id` int AUTO_INCREMENT,`person_id` int,`car_id` int, PRIMARY KEY (id));

INSERT INTO `cars` (`id`) VALUES ('1');
INSERT INTO `people` (`first_name`) VALUES ('a');
INSERT INTO `people` (`first_name`) VALUES ('b');

INSERT INTO `car_person` (`id`, `person_id`, `car_id`) VALUES ('25', '1', '1');
INSERT INTO `car_person` (`id`, `person_id`, `car_id`) VALUES ('26', '2', '1');
```

2. Run the following code 
```
use Illuminate\Database\Eloquent\Builder;
Builder::macro('customPaginate', function () {
	return $this->paginate(15);
});
class Person extends \Illuminate\Database\Eloquent\Model {
}
class Car extends \Illuminate\Database\Eloquent\Model {
	public function people() {
		return $this->belongsToMany(Person::class);
	}
}
$car = Car::findOrFail(1);
$car->people()->customPaginate()->getCollection();
```
The ids of the peoples in the collection is the id from the belongsToMany table, instead of the actual id of the person

**Comment by staudenmeir** [comment]
Your query doesn't work properly because `BelongsToMany` has its own implementation of [`paginate()`](https://github.com/laravel/framework/blob/d2da49c113f995bce6ed64ac765ca3ab3fa6236c/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L825) to select the right columns and your macro bypasses that.

You (also) need to register the macro on the `Relation` class.
