### ISSUE TITLE
Laravel return no results but MySQL return results

### ISSUE THREAD

**Issue by dayota** [laravel/framework#33853]
- Laravel Version: 7.10.3
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.21

### Description:
I launch paginate on query and it's return no results. But when i launch same query (dump query from builder with toSql and replace bindings) directly in mysql console i have results.

### Steps To Reproduce:
$builder = SettingsOrganizationCustomerUserProfile::from('view_settings__organization_customer_user_profiles', 'vsocup')
            ->select('vsocup.*')
            ->leftjoin('view_settings__organization_customer_persons_occupations as vsocpo', 'vsocup.id', '=', 'vsocpo.settings__organization_person_id')
            ->leftjoin('view_settings__organization_customer_occupations as vsoco', 'vsocpo.view_settings__organization_customer_occupation_id', '=', 'vsoco.id')
            ->leftjoin('view_settings__organization_customer_companies as vsocc', 'vsoco.settings__organization_company_id', '=', 'vsocc.id')
            ->where('vsocc.id', 2);

`dump($builder->paginate(15));`
return :
Illuminate\Pagination\LengthAwarePaginator^ {#475
  #total: 0
  #lastPage: 1
  #items: Illuminate\Database\Eloquent\Collection^ {#467
    #items: []
  }
  #perPage: 15
  #currentPage: 1
  #path: "https://xxx.xxxx.com/test"
  #query: []
  #fragment: null
  #pageName: "page"
  +onEachSide: 3
  #options: array:2 [
    "path" => "https://xxx.xxxx.com/test"
    "pageName" => "page"
  ]
}

`dump($builder->paginate(15, ['vsooup.*']));`
return :
Illuminate\Pagination\LengthAwarePaginator^ {#476
  #total: 0
  #lastPage: 1
  #items: Illuminate\Database\Eloquent\Collection^ {#475
    #items: []
  }
  #perPage: 15
  #currentPage: 1
  #path: "https://xxx.xxxx.com/test"
  #query: []
  #fragment: null
  #pageName: "page"
  +onEachSide: 3
  #options: array:2 [
    "path" => "https://xxx.xxxx.com/test"
    "pageName" => "page"
  ]
}

Query launch in MySQL console:
select count(`vsocup`.`id`) as aggregate
    from `view_settings__organization_customer_user_profiles` as `vsocup`
    left join `view_settings__organization_customer_persons_occupations` as `vsocpo` on `vsocup`.`id` = `vsocpo`.`settings__organization_person_id`
    left join `view_settings__organization_customer_occupations` as `vsoco` on `vsocpo`.`view_settings__organization_customer_occupation_id` = `vsoco`.`id`
    left join `view_settings__organization_customer_companies` as `vsocc` on `vsoco`.`settings__organization_company_id` = `vsocc`.`id`
where `vsocc`.`id` = 2;
return :
+-----------+
| aggregate |
+-----------+
|       292 |
+-----------+

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
