### ISSUE TITLE
mail.php config file template not complete. 

### ISSUE THREAD

**Issue by learn-by-flying** [laravel/framework#33869]
- Laravel Version: 7.25.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL v8.0.19

### Description:
The mail.php config template does not properly document the from portion of the mailable. If the from method is not specified then Laravel uses the default from address.

Does not work:
'lab_connect' => [
            'transport' => env('MAIL_LC_TRANSPORT'),
            'host' => env('MAIL_LC_HOST'),
            'port' => env('MAIL_LC_PORT'),
            'encryption' => env('MAIL_LC_ENCRYPTION'),
            'address' => env('MAIL_LC_FROM_ADDRESS'),
            'name' => env('MAIL_LC_FROM_ADDRESS'),
            'username' => env('MAIL_LC_USERNAME'),
            'password' => env('MAIL_LC_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
        ],

Works:
'lab_connect' => [
            'transport' => env('MAIL_LC_TRANSPORT'),
            'host' => env('MAIL_LC_HOST'),
            'port' => env('MAIL_LC_PORT'),
            'encryption' => env('MAIL_LC_ENCRYPTION'),
            'from' => [
                'address' => env('MAIL_LC_FROM_ADDRESS'),
                'name' => env('MAIL_LC_FROM_ADDRESS'),
            ],
            'username' => env('MAIL_LC_USERNAME'),
            'password' => env('MAIL_LC_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
        ],

### Steps To Reproduce:

Specify a different default from address than the mailer from address and the default is used unless the from sub array is specified. 

https://github.com/laravel/laravel/blob/develop/config/mail.php

**Comment by driesvints** [comment]
This isn't needed. No idea why it doesn't work for you but it's best that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by learn-by-flying** [comment]
@driesvints I filed this as I've spent the last few hours trying to chase this one down including posting on the Laracast forums.

If you do not include the from => [] in the mail.php mailable array you will not get the expected results if you need to send from multiple addresses.

I filed as a bug as Laravel is working but not in the expected way when specifying a mailable. 

Perhaps the documentation should include this detail for those who need it and the mailable trait is new in the v7 series?

**Comment by driesvints** [comment]
Please share full steps to reproduce, including any code snippets and/or env settings.
