### ISSUE TITLE
Cannot update eloquent array attribute (json column)

### ISSUE THREAD

**Issue by fredericseiler** [laravel/framework#33863]
- Laravel Version: 7.25.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 8.0.19

### Description:
Hi, I recently updated a Laravel app codebase from 7.22.4 to 7.25.0, and I can no longer update nested array values in eloquent.

```php
User::first()->update(['options->foo' => 'bar']); // does nothing
```

### Steps To Reproduce:
- Fresh install of Laravel 7.25.0
- Migration:
```php
Schema::table('users', function (Blueprint $table) {
    $table->json('options')->default(new Expression('(JSON_OBJECT())'));
});
```
- User model:
```php
class User
{
    protected $guarded = [
        'id',
    ];

    protected $casts = [
        'options' => 'array',
    ];
}
```
- Seed a user
- Try to update the nested attribute (worked with Laravel 7.22.4):
```php
User::first()->update(['options->foo' => 'bar']); // no update, no error.
```
![image](https://user-images.githubusercontent.com/954168/90149169-7c5b4800-dd84-11ea-843d-934c3b284935.png)

As a temporary workaround, it works with `forceFill`:
```php
User::first()->forceFill(['options->foo' => 'bar'])->save(); // updated.
```
![image](https://user-images.githubusercontent.com/954168/90149338-ab71b980-dd84-11ea-92a2-6d49b6bd875c.png)

**Comment by mnabialek** [comment]
It's probably related to https://blog.laravel.com/security-release-laravel-61835-7240 but seems to not work well for such case

**Comment by fredericseiler** [comment]
Thanks, didn't see that post. In fact, if I remove `'id'` from the `$guarded` property, everything's back to normal.

So, I guess this isn't a bug... or is it ? :man_shrugging:

**Comment by taylorotwell** [comment]
Yes, this was noted in the security release. You would need to make `options->foo` explicitly fillable. It's not safe to have an unguarded JSON column like that.

**Comment by mfn** [comment]
This also broke the following code, when defining `$guarded = [];`
```php
SomeModel::updateOrCreate([
  'some_model.column',
]);
```
The column will silently not be updated or created.

Reason is that `\Illuminate\Database\Eloquent\Model::removeTableFromKey` is now a no-op.

The fix is to remove the `some_model.` prefix.

I re-read the security release a few times but I wouldn't derive that change from that.

Anyway, not a bug issue, the test suite caught it. Just thought I'd mention it as another datapoint in case someone runs into this.

**Comment by driesvints** [comment]
Hey @mfn please see https://github.com/laravel/framework/issues/33895

We never officially supported or documented the usage of the `<connection>.<table-name>` syntax.

**Comment by mfn** [comment]
Actually, the reason I _had_ them was for `table.column`, not `connection.table` 🤔

See it as a counterpart to `::select('table.column')` (relevant when performing joins).

But yes, it's rather obscure and in fact I would say my code was buggy / relying on undefined behaviour. I don't even think it was done concisely.

Thank you very much for the additional information!
