### ISSUE TITLE
Queue database driver - failing to retry all failed jobs

### ISSUE THREAD

**Issue by mihaliak** [laravel/framework#33874]
- Laravel Version: 7.10.3
- PHP Version: 7.4.0alpha1
- Database Driver & Version: mysql 5.7

### Description:
Can't retry all failed jobs while using database driver. Having around 10k failed jobs and running `php artisan queue:retry all` fails with allowed memory size error.

php artisan queue:retry all
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 173
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/vendor/symfony/error-handler/Error/FatalError.php on line 1

### Steps To Reproduce:
1. Use database queue driver
2. Generate around 10k failed jobs
3. Run php artisan queue:retry all
4. See error in console

Workaround for this is create custom command and using cursor for selecting failed jobs IDs and running `php artisan queue:retry {id}` for every failed jobs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
