### ISSUE TITLE
[8.x] data_get function not available when using stand-alone illuminate/collections

### ISSUE THREAD

**Issue by kbond** [laravel/framework#33875]
- Laravel Version: 8.x
- PHP Version: 7.4.9
- Database Driver & Version: n/a

### Description:

When using `illuminate/collections` as a stand alone package, it makes calls to the `data_get` function (11 places) which is not defined. It is in `Illuminate/Support/helpers.php` (which is not available in the stand-alone package).

### Steps To Reproduce:

1. Install `illuminate/collections`
2. Try to use `Arr::pluck()`

I'm not sure how you would want to fix this but let me know if I can help! (Ref: #32478)

**Comment by driesvints** [comment]
@kbond we're checking in on this. Thanks for testing Laravel 8!

**Comment by GrahamCampbell** [comment]
Fixed now. :)
