### ISSUE TITLE
SQLSTATE[42000] [1226] User 'db_user' has exceeded the imax_user_connections' resource (current value: 30)

### ISSUE THREAD

**Issue by sanmitpawar** [laravel/framework#33880]
- Laravel Version: 5.5.*
- PHP Version: 7.0.0
- Database Driver & Version: mysql 

### Description:

we are having laravel 5.5.* framework, & we have hosted on the shared server most of the cases we encountered with this issue please provide the solution for the 
![WhatsApp Image 2020-08-07 at 11 41 31 PM](https://user-images.githubusercontent.com/19944808/90279258-7ea5cb00-de86-11ea-977d-c4e383909672.jpeg)
same

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
