### ISSUE TITLE
[7.24.0+] Dynamically assigning table- and connection name appear to be broken after 7.23.2

### ISSUE THREAD

**Issue by SDekkers** [laravel/framework#33895]
- Laravel Version: `v7.24.0` and `v7.25.0`
- PHP Version: 7.4.9
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.31,

### Description:
After updating to `v7.25.0` (from `v7.23.2`) it looks like dynamically assigning the table- and connection name isn't working anymore when using `Model::create($insert)`.

### Steps To Reproduce:
We've got this model:

`App\Models\VirtualUser` which has an ID, email, and password as columns
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class VirtualUser extends Model
{

	public    $timestamps = false;

	protected $guarded    = ['id'];

	public function __construct(array $attributes = [])
	{
		parent::__construct($attributes);

		$conn = config('xcustom.connections.'.__CLASS__); // resolves to 'conn2'
		$tbl = config('xcustom.tables.'.__CLASS__); // resolves to 'virtualusers';

		$this->setConnection($conn);
		$this->setTable($tbl);
	}
}
```

When using `Laravel v7.23.2` the below code inserts a record just fine:
```
$insert = [
	'email'     => 'test@my-domain.tld',
	'password'  => 'test', // for testing purposes.
	'domain_id' => 1,
];

$result = \App\Models\VirtualUser::create($insert);
```

But when using `v7.24.0` or `v7.25.0` it errors as below:

```
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1364 Field 'password' doesn't have a default value (SQL: insert into `virtual_users` () values ())
```

When using
```
$insert = [
	'email'     => 'test@my-domain.tld',
	'password'  => 'test', // for testing purposes.
	'domain_id' => 1,
];

$result = \App\Models\VirtualUser::insert($insert);
```

It's fine in all 3 versions. I've checked the differences between 7.23.2 and 7.24, but can't seem to find anything Eloquent related that would break this code.

**Comment by driesvints** [comment]
Laravel doesn't and has never officially supported assigning the connection to a table name from userland. You cannot use the `setTable` method for that.

**Comment by driesvints** [comment]
We're sorry that this was broken for you. But these changes were part of recent security updates and we won't (and simply can't) reverse them, sorry.

https://blog.laravel.com/security-release-laravel-61835-7240

**Comment by SDekkers** [comment]
Clear. I've found a work-around to initialize `parent::__construct()` after my table assignments rather than before. Thanks Dries!
