### ISSUE TITLE
Dimensions rule fails to correctly check ratio 1/1 when height equals to width + 1

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [laravel/framework#33899]
- Laravel Version: 5.4 onwards (#19542), 6.x, 7.x
- PHP Version: 7.4.2
- Database Driver & Version: N/A

### Description:
Dimensions rule fails to correctly check ratio 1/1 when height equals to width + 1. Following case passes validation while it should not:
```php
width: n
height: n + 1
ratio: 1/1
```

Here is the code:
https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L556-L569

What it simplifies to:
```php
  $precision = 1 / max($width, $height);
  $precision = 1 / (n + 1)
```

```php 
  $leftCalc = abs($numerator / $denominator - $width / $height)
  $leftCalc = 1 - n / (n + 1)
  $leftCalc = 1 / (n + 1) (became same as $precision)
```

```php
check for fail:
  $leftCalc > $precision (which returns false, meaning it did not fail)
```

### Steps To Reproduce:
```php
use Illuminate\Http\UploadedFile;

$n = 64;

Validator::make([
	'image' => UploadedFile::fake()->image('image.png', $n, $n + 1),
], ['image' => 'dimensions:ratio=1'])
  ->errors()
  ->all()
```

**Comment by driesvints** [comment]
This seems to be a bug specifically with the faking of images because when I write a test for this scenario in the framework with a real image it behaves as expected. I'm not sure what's going on here. Afaik the faked file's dimensions are passed correctly but the validator isn't behaving as expected.

**Comment by developerbmw** [comment]
It's a float comparison issue and it only happens with certain values of $n in the example above. For example validation passes with $n=64 but not with $n=72

I will submit a PR for this shortly.

**Comment by driesvints** [comment]
Sent in https://github.com/laravel/framework/pull/34003 for this.
