### ISSUE TITLE
Double cache prefix applied when locking with DynamoDB and Memcached

### ISSUE THREAD

**Issue by BrianHigby** [laravel/framework#33901]
- Laravel Version: 7.20.0
- PHP Version: 7.4.7
- Database Driver & Version: N/A

### Description:
When using session blocking with DynamoDB or Memcached as the session block store, Laravel applies the cache prefix twice to the key. I dug into this and found that when `lock()` in `DynamoDbStore` creates the `DynamoDbLock` instance it prefixes the name.

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/DynamoDbStore.php#L405-L408

`DynamoDbLock` gets passed the current `DynamoDbStore` instance, which already has the prefix stored in it, and when `acquire()` gets called it in turn calls `add()` which results in the prefix being applied a second time creating the double prefix.

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/DynamoDbLock.php#L35-L40

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/DynamoDbStore.php#L257-L265

The same double prefix logic exists in `MemcachedStore` and `MemcachedLock` as well.

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/MemcachedStore.php#L189-L192

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/MemcachedLock.php#L35-L40

https://github.com/laravel/framework/blob/8f22cabf3e29cabb206eec01b7c856e993e54eb7/src/Illuminate/Cache/MemcachedStore.php#L138-L143

Removing the prefix in the respective `lock()` functions fixes the issue on my end. I'll submit a PR for this unless I'm missing something and this double prefix is here for a reason. I suspect it is not intended as other Cache stores do not appear to have this issue.

### Steps To Reproduce:

1. Configure session blocking with either DynamoDB or Memcached.
2. Create a route that blocks and add a die or any other way to kill the request prematurely so the session block remains in the cache.
3. Check the cache keys to see the cache prefix is being applied twice for the session block.

**Comment by taylorotwell** [comment]
Feel free to submit PR. Thanks.
