### ISSUE TITLE
lumen redirect() Target class [redirect] does not exist.

### ISSUE THREAD

**Issue by puzzle9** [laravel/framework#33905]
- Laravel Version: ^7.0#.#.#
- PHP Version: 7.4#.#.#
- Database Driver & Version:

### Description:

```php
    // api.php
    $router->get('/', function () {
        redirect('/hello');
    });
```

### guess
vendor/laravel/lumen-framework/src/helpers.php
vendor/laravel/framework/src/Illuminate/Foundation/helpers.php

`redirect()` repeat

**Comment by GrahamCampbell** [comment]
You cannot install both laravel and lumen at the same time.
