### ISSUE TITLE
Paginator bypasses model-defined jsonSerialize() 

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#33917]
- Laravel Version: 7.25.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7

### Description:
When serializing paginated results to json, the LengthAwarePaginator class calls toArray() on the model collection but not jsonSerialize(). If a model has custom json serialization logic defined in its own jsonSerialize() method, that will be bypassed in favor of the base toArray() conversion. 

### Steps To Reproduce:
Generate paginated query results on a model that defines its own jsonSerialize() method.

Fixing this is probably as simple as changing the jsonSerialize() method on the LengthAwarePaginator class to something like:
```
public function jsonSerialize()
{
    $array = $this->toArray();
    $array['data'] = $this->items->jsonSerialize();

    return $array;
}
```
This is a little inefficient, since most of the time the model's jsonSerialize() call will call toArray() anyway, so there are duplicate calls. So to reduce redundant method calls in favor of redundant code:
```
public function jsonSerialize()
{
    return [
        'current_page' => $this->currentPage(),
        'data' => $this->items->jsonSerialize(),
        'first_page_url' => $this->url(1),
        'from' => $this->firstItem(),
        'last_page' => $this->lastPage(),
        'last_page_url' => $this->url($this->lastPage()),
        'next_page_url' => $this->nextPageUrl(),
        'path' => $this->path(),
        'per_page' => $this->perPage(),
        'prev_page_url' => $this->previousPageUrl(),
        'to' => $this->lastItem(),
        'total' => $this->total(),
    ];
}

```
Yet another option would be to pass a JsonResource class to the paginator, and have it use that instead. That would be a more significant refactoring, though.

**Comment by driesvints** [comment]
This is expected. Please use API resources for this: https://laravel.com/docs/7.x/eloquent-resources

**Comment by adamthehutt** [comment]
Thanks, and my bad. Didn't realize those could be used with pagination.
