### ISSUE TITLE
Fail to replicate with table pivote

### ISSUE THREAD

**Issue by fabdelgado** [laravel/framework#33916]
- Laravel Version: 7.22.4
- PHP Version: 7.3
- Database Driver & Version: Mysql

### Description:
I am trying to duplicate records in another table and its pivot table called files.

I have run the following code but it only replicates the records, not the relationships in the pivot table.

`Draft::find($ id)->load('files')->replicate ()->setTable('publishes')->save();`

### Steps To Reproduce:

Create a table called Drafts and have a N to M relationship with files.
Try to replicate the Draft table to a new one and keep the file relationships on a new pivot.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by fabdelgado** [comment]
thanks @driesvints
