### ISSUE TITLE
Numeric string min/max length validation fails

### ISSUE THREAD

**Issue by gaaf** [laravel/framework#33921]
- Laravel Version: v5.8.38 (but also present in later versions)
- PHP Version: 7.3.14-1~deb10u1
- Database Driver & Version:

### Description:
I want to validate a field to contain a **string** with length limits and that may only contain a numeric value. This fails as the validator evaluates the numeric value instead of the string length.

### Steps To Reproduce:
```php
$validator = \Validator::make(
  ['test' => "1234567890"],
  ['test' => 'string|numeric|min:4|max:10']
);

dd($validator->passes());
^ false

dd($validator->errors());
^ Illuminate\Support\MessageBag^ {#4330
  #messages: array:1 [
    "test" => array:1 [
      0 => "The test may not be greater than 10."
    ]
  ]
  #format: ":message"
}
```

### Suggested Fix:
Don't try to be smart with the type if a string is requested.

I'll submit a PR soon which will fix this issue.

**Comment by taylorotwell** [comment]
Numeric and string are not compatible rules at the moment. Numeric data is expected to be a numeric type.

**Comment by SjorsO** [comment]
You could solve this problem with a regex validation rule: `regex:/^\d{4,10}$/`

**Comment by gaaf** [comment]
Thanks SjorsO. I was already using that but wanted to have nicer to read code _and_ error message (without writing a custom validator.

And as a ```numeric``` in Laravel validators doesn't imply, enforce nor checks the attribute to be a numeric **type** at all (like taylorotwell seemed to claim in the previous comment), combining ```string``` and ```numeric``` seemed like the nicest solution.
