### ISSUE TITLE
[6.x/7.x] broadcast() method causes memory leak

### ISSUE THREAD

**Issue by rennokki** [laravel/framework#33952]
Like the title says, I ran into a discussion about some memory leaks for beyondcode/laravel-websockets here: https://github.com/beyondcode/laravel-websockets/issues/325

The basic truth is that after some testing, I found out that running `broadcast(...)` will severely increase the memory for a ReactPHP loop, for instance.

To replicate this:

- create a new Laravel project
- `composer require laravel/websockets:"dev-2.x-memory-leak"`
- copy the migrations: `php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="migrations"`
- run them: `php artisan migrate`
- get to the root of the project and run `php artisan websockets:serve --statistics-interval=1`
- open an artisan server with `php artisan serve`
- Go to `http://127.0.0.1:8000/laravel-websockets`
- Click on Connect
- Watch the memory increase in the console that ran `websockets:serve`

As explained in https://github.com/beyondcode/laravel-websockets/issues/325#issuecomment-676565842 and https://github.com/beyondcode/laravel-websockets/issues/325#issuecomment-677198100, the problem starts from a `broadcast()` that causes the leakage.

I have tested even the code within the event. Running `broadcast()` caused the memory leaks.

**Comment by rennokki** [comment]
I have pointed out in https://github.com/beyondcode/laravel-websockets/issues/325#issuecomment-676622837 that a controller also caused the issue, eventually moving on in https://github.com/beyondcode/laravel-websockets/issues/325#issuecomment-677198100 to find out the issue is because of the broadcasting dispatch.

The package got a `dev-2.x-memory-leak` version in composer where just the `broadcast()` method causes the memory leak.

**Comment by rennokki** [comment]
The issue seems to be caused by the `new StatisticsUpdated(...)` bit, where `StatisticsUpdated` is an event class.

**Comment by mo3000** [comment]
I followed the instructions step by step to reproduce this. After digging a while, I found out that in /facade/ignition/src/IgnitionServiceProvider.php, function boot():
```php
//        $this->app->make(QueryRecorder::class)->register();
//        $this->app->make(LogRecorder::class)->register();
        $this->app->make(DumpRecorder::class)->register();
```
comment out this two lines make the memory leak go away.
So it sounds like not a bug of "broadcast()".

**Comment by mpskovvang** [comment]
A fix without touching the original files is to set `reporting.maximum_number_of_collected_queries` to `0` in `config/flare.php`.

**Comment by rennokki** [comment]
@mpskovvang Makes sense! I have informed the package users that had the respective issue.
