### ISSUE TITLE
Scheduling bug when using everyFourHours

### ISSUE THREAD

**Issue by k-t-holland** [laravel/framework#33956]
- Laravel Version: 7.17.2
- PHP Version: 7.3.19
- Database Driver & Version: mysqlnd 5.0.12-dev

### Description:
Getting the following error while trying to use everyFourHours
`ERROR: Method Illuminate\Console\Scheduling\Event::everyFourHours does not exist.`

### Steps To Reproduce:
```
$schedule
    ->call(function () {
        //
    })
    ->between('05:00','17:00')
    ->everyFourHours()
    ->timezone('America/New_York');
```

**Comment by taylorotwell** [comment]
The method exists. Make sure you are up to date.
