### ISSUE TITLE
Bugs with returning a closure/anon function from a component

### ISSUE THREAD

**Issue by ddrght12345** [laravel/framework#33981]
- Laravel Version: 7.25.0
- PHP Version: 7.4.3

### Description:
Following the docs (https://laravel.com/docs/7.x/blade#passing-data-to-components), returning a closure from the render method presents a few different problems:

1) The full view gets passed to (View/)`Factory::exists($view)`, which causes an `ErrorException` to be thrown.
Forcing `$view` to a string, or running it through `$this->normalizeName($view)` will fix this issue

2) None of the data which should exist, exists.
By which, Im referring to the default things such as `$attributes` and `$slot`.
In addition, none of the public properties are available.

### Steps To Reproduce:
1) Create a component
2) Per docs, change the render method to return a `function` instead of a `view`

I was in the process of debugging this further, but I have run out of time that I had allotted to this problem.
*Side note: Returning a closure doesnt feel... Right. It would be nice if there was a way to modify `$slot`/`$attributes` outside of that.*

**Comment by driesvints** [comment]
Please post your component and view.

**Comment by ddrght12345** [comment]
Directly from the docs, with only a different name
```php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Testing extends Component {
    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render() {
        return function(array $data) {
            // $data['componentName'];
            // $data['attributes'];
            // $data['slot'];

            return view('components.testing');
        };
    }
}
```

```php
<div>{{ $slot }}</div>
```

**Comment by taylorotwell** [comment]
Docs are just wrong. You need to return an inline component or a view name as a string from the Closure.
