### ISSUE TITLE
[5.5.50] Cookie prefix fails when value serialized array

### ISSUE THREAD

**Issue by ConstantinFF** [laravel/framework#33997]
- Laravel Version: 5.5.50
- PHP Version: 7.3.18
- Database Driver & Version:

### Description:
From the latest release of Laravel 5.5
the security fix with cookie prefix fails when cookie value is set to an array.
```
(1/1) ErrorExceptionArray to string conversion
--
in EncryptCookies.php line 155
```
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L155

`$prefix` value is string
`$cookie->getValue()` is array

I would suspect that same issue would be on 7.x:
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L148
### Steps To Reproduce:
Set Cookie Middleware to serialize values in `App\Http\Middleware\EncryptCookies`
```
protected static $serialize = true;
```

And then set a cookie value to array:
```
Cookie::queue('test_cookie', ['test' => 'value'], time() + 3600, '/');
```

**Comment by driesvints** [comment]
We don't support setting cookies as an array.
