### ISSUE TITLE
Validator validated returns unvalidated data

### ISSUE THREAD

**Issue by tim-hanssen** [laravel/framework#34006]
- Laravel Version: 7.18.0
- PHP Version: 7.4

### Description:

Form requests depend on the validator validated function to only return data that is validated and specified in the rules. 

### Steps To Reproduce:

Rules

```
return [
            
            'items' => [
                'array'
            ],
            
            'items.id' => [
                'string'
            ]
        ];
```

Input data:

`
{
    "items" : {
        "id" : "a",
        "name" : "Twee"
    }
}
`

Returned validated data:

Result of : $request->validated();

```
Array
(
    [items] => Array
        (
            [id] => a
            [name] => Twee
        )

)

```

Expected:

```
Array
(
    [items] => Array
        (
            [id] => a
        )

)
```

Adding an extra check in the Validator file to ensure no arrays are added back as a whole fixes the issue.

https://github.com/laravel/framework/pull/34005

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tomswinkels** [comment]
@driesvints this is not a question? This is a bug?

**Comment by driesvints** [comment]
Feel free to attempt that PR again but with a proper explanation and tests (see the PR template).

**Comment by eduardoturconi** [comment]
Why is this even closed?
