### ISSUE TITLE
Rule::exists validation does not work when running units test laravel

### ISSUE THREAD

**Issue by inferiore** [laravel/framework#34013]
- Laravel Version: 7.X
- PHP Version: 7.4.9
- Database Driver & Version: I'm running units test by using the trait `Illuminate\Foundation\Testing\RefreshDatabase`. I use SQLITE 3

### Description:
I validate a input field by using `Illuminate\Support\Facades\Validator` also  I use `Illuminate\Validation\Rule:Exists` in order to customize the query that checks if the value received  exists in the table.
Everything works perfectly when sending the request through postman
The problem is shown when running the units test by using `php artisan test`. I try with valid values and I receive error in the unit test

Clue: it seems like that  `Illuminate\Validation\Rule:Exists` function does not work properly when running units tests

### Steps To Reproduce:

1. Develop a endpoint which uses the next rule (Use `POST` http verb):

```  $validator = Validator::make($request->all(), [      
      'speciality_id'=>'exists:specialities,id',  
      'sub_speciality_id'=>
                [
                'required_if:health_care_worker_type_id,1',
                    Rule::exists('sub_specialities')->where(function ($query) use ($request) {
                        return $query->where('speciality_id',"=", $request->get("speciality_id")); // this rule fails even when valid valuesl
                    }),

                ],
```
2. Create a unit test, code a method named `populate`, in order to populate the database by using seeds. Populate with a valid values which you know the unit test passes  with
```
public function populate(){
        $this->seed( \SpecialitySeeder::class);
        $this->seed( \SubSpecialitySeeder::class);
    }
```  
3. Make sure you call the `populate` method  before to run the unit test. 
```
$this->populate();
     $data = [
            "speciality_id"=> 1,
            "sub_speciality_id"=> 1,
        ];
$response = $this->post('your-endpoint',$data);
$response->assertStatus(200);
```
4. It suppose that the rule should not fail but the unit test shows it fails.  
Use `$response->getContent()` to know what the response was. It should be: "{"sub_speciality_id":["The selected sub speciality id is invalid."]}"`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
