### ISSUE TITLE
Laravel Queue Worker --timeout argument is not working

### ISSUE THREAD

**Issue by voyula** [laravel/framework#34012]
- Laravel Version: 7.22.4
- PHP Version: 7.4.9
- Database Driver & Version: -

### Description:

![Image](https://i.ibb.co/0CfxXs3/Screenshot-123.png)

Current time: 2020-08-25 21:58:59

Worker did not timeout.

**Comment by voyula** [comment]
Is pcntl module absolutely necessary for timeout?

**Comment by mfn** [comment]
[Yes,](https://github.com/laravel/framework/blob/f64299a11dedaaadf1cfff07b2b3220a9b791837/src/Illuminate/Queue/Worker.php#L124-L126) [I believe so](https://github.com/laravel/framework/blob/f64299a11dedaaadf1cfff07b2b3220a9b791837/src/Illuminate/Queue/Worker.php#L155-L173)

**Comment by voyula** [comment]
@mfn Yes, tested now and true.

**Comment by voyula** [comment]
In Laravel Document;

The timeout feature is optimized for PHP 7.1+ and the pcntl PHP extension.

Why not say; Must be installed. ?

**Comment by driesvints** [comment]
@voyula feel free to PR something to the docs.
