### ISSUE TITLE
Redis::connect(): SSL: Handshake timed out 

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#34018]
- Laravel Version: 6.18.36
- PHP Version: 7.2.33 and 7.3.21
- Database Driver & Version: MYSQL 5.7.31

### Description:
 When updated laravel version redis stopped working.
I have changed configurations and try various options, nothing worked.
Also i removed and reinstall phpredis extension but still nothing.
I believe the problem has something to do with [this ](https://github.com/laravel/framework/pull/33892) pull request 
Also problem seems to be on unix machines only, windows are working.
If i revert to version 6.18.35 is working perfectly

### Steps To Reproduce:
Update laravel 6.x to latest version
Set your REDIS_CLIENT  in env to phpredis
Set your CACHE_DRIVER in env to redis

**Comment by mfn** [comment]
Maybe also related to https://github.com/laravel/framework/pull/34017#issuecomment-680724904  🤔

**Comment by driesvints** [comment]
Should be fixed now in 6.18.37
