### ISSUE TITLE
SendEmailVerificationNotification not called for existing users on login

### ISSUE THREAD

**Issue by bellwood** [laravel/framework#34014]
- Laravel Framework 7.25.0
- PHP 7.4.9
- Postgresql 12.4

### Description:
Given this seeder:

```
        $admin = User::create([
            'name' => 'Admin User',
            'email' => 'admin@admin.com',
            'password' => Hash::make('password'),
            'email_verified_at' => now()
        ]);

        $author = User::create([
            'name' => 'Author User',
            'email' => 'author@author.com',
            'password' => Hash::make('password'),
            'email_verified_at' => now()
        ]);

        $user = User::create([
            'name' => 'Generic User',
            'email' => 'user@user.com',
            'password' => Hash::make('password')
        ]);
```

When `user@user.com` logins in, they are prompted:

```Before proceeding, please check your email for a verification link. If you did not receive the email, click here to request another.```

However, because this user wasn't created as part of the registration process, an email hasn't yet been sent to them to check and since SendEmailVerificationNotification() is not called during this login the user will have to "click here to request another"

Wouldn't it be prudent to call SendEmailVerificationNotification() on login if they haven't been verified?

**Comment by bellwood** [comment]
This works perfectly:

**./vendor/laravel/ui/auth-backend/VerifiesEmails.php**
```php
    /**
     * Show the email verification notice.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(Request $request)
    {
        if ($request->user()->hasVerifiedEmail()) {
            return redirect($this->redirectPath());
        }

        $request->user()->sendEmailVerificationNotification();
        return view('auth.verify');

        // return $request->user()->hasVerifiedEmail()
        //                 ? redirect($this->redirectPath())
        //                 : view('auth.verify');
    }
```

**Comment by developerbmw** [comment]
Why can't you just set `email_verified_at` in the seeder? I don't understand what the use case is for requiring seeded users to verify their email address.

**Comment by bellwood** [comment]
@developerbmw if you are requiring email verification on an existing application, you'll have users in the db that don't have a `email_verified_at` value and the above scenario occurs.

**Comment by bellwood** [comment]
I'm not sure there is a good way to resolve this.

Being that we don't track if/when an email was sent and we have no way of knowing if a signed URL was generated for an email, unless we modified the users table schema to track that via `email_verification_sent` there is really no good way, logically, to make that determination, at least from my purview.

That said, perhaps expanding the auth group of artisan to include say:

`php artisan auth:reverify --unverified` - re-send verifications to all un-verified users
`php artisan auth:reverify --all` - re-send verifications to all users, invalidating `email_verified_at`

Bit of an edge case I guess but for those bolting email verification on to existing projects, it would be nice to simply call `php artisan auth:reverify --unverified` and know all your existing users will get an email.

**Comment by developerbmw** [comment]
Yes I agree it is a bit of an edge case. Maybe the best solution is to add a message in your app UI about the added requirement for email verification so users aren't confused when they try to log in, and they can click resend email.

**Comment by driesvints** [comment]
You need to set `email_verified_at` in your seeder.

**Comment by bellwood** [comment]
@driesvints yes, that would certainly resolve the issue based on my example seeder however I wanted to raise the issue to see if this was considered a bug or not, rather than just modify my schema.

Would pull requests for additional artisan auth commands be welcome?

**Comment by driesvints** [comment]
@bellwood no sorry. Just set this in your seeder.
