### ISSUE TITLE
Auth::viaRemember() always returns false

### ISSUE THREAD

**Issue by arce701** [laravel/framework#34028]
- Laravel Version: 7.26.0
- PHP Version: 7.3.3
- Database Driver & Version: 10.1.38-MariaDB

### Description:
I'm trying to check if my Keep session active box works.
It does not matter if you check it or not, the `Auth::viaRemember()` function returns **false**.

### Steps To Reproduce:

`use Illuminate\Support\Facades\Auth;`
`....`
```
 public function home()
    {
        dd(Auth::viaRemember());
          ....
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by arce701** [comment]
I already did, I did not find a solution anywhere, if there is one without modifying the framework. sorry for escaping my attention.

**Comment by arce701** [comment]
Something I do **NOT** like about laravel **Issues** is that they don't even leave it open for discussion, they give a **short answer** and **close it**.

**Comment by driesvints** [comment]
@arce701 please understand that we can't provide support for each individual issue that can be asked on a support channel. We have dozens of open source repos to maintain and also need to work on new releases. We have a large and active community out there that can help out.
