### ISSUE TITLE
data_get does not work when there is a dot in the key

### ISSUE THREAD

**Issue by dejury** [laravel/framework#34021]
- Laravel Version: 7.26.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7

### Description:
I am implementing a webhook in Laravel where i receive certain parameters with a dot notation. For example, the city will be send as parameter: "`Location.City`".

When using the `$request->input('Location.City')` it will return null.
The issue seems to be in the `data_get` method, it does not support dotted keys.

There is already a pull request (#33786) for this one, I think with some small improvements (like checking first for multidimensional and if there is no match use the dotted key if available), this could really help people.

**Comment by lk77** [comment]
Hello,

`$request->input('Location_City')` should work

**Comment by dejury** [comment]
Well it doesn't work:

`dd($request->input("Location.City"), $request->input("Location_City"));`

results in
<img width="1190" alt="Schermafbeelding 2020-08-26 om 17 17 24" src="https://user-images.githubusercontent.com/16034333/91322511-21801280-e7c0-11ea-9c1e-a85e5e9dcdc3.png">

**Comment by lk77** [comment]
For me it's working fine :



![Capture du 2020-08-26 17-19-41](https://user-images.githubusercontent.com/9606882/91322855-80458c00-e7c0-11ea-8082-5d6a9fa9fd7b.png)

![Capture du 2020-08-26 17-21-40](https://user-images.githubusercontent.com/9606882/91322990-a3703b80-e7c0-11ea-844a-e009e2aa7323.png)


![Capture du 2020-08-26 17-19-50](https://user-images.githubusercontent.com/9606882/91322851-7facf580-e7c0-11ea-9e99-642f013026b0.png)

**Comment by dejury** [comment]
Well thats strange. I'm not sure, but I don't see where this should happen in the code when using data_get().
Are you using 
`\Illuminate\Http\Request $request->input()`?

**Comment by dejury** [comment]
<img width="1193" alt="Schermafbeelding 2020-08-26 om 17 26 53" src="https://user-images.githubusercontent.com/16034333/91323593-59d42080-e7c1-11ea-928c-c20a09f674cb.png">

First dump is the $request->all()

**Comment by dejury** [comment]
<img width="1197" alt="Schermafbeelding 2020-08-26 om 17 27 37" src="https://user-images.githubusercontent.com/16034333/91323684-740dfe80-e7c1-11ea-8e3d-1f21268d2cea.png">

The first dump is the $request->all()

**Comment by lk77** [comment]
Yes, i'm using the input method from the request.

it's seems that the behaviour with json is not the same

![Capture du 2020-08-26 17-32-33](https://user-images.githubusercontent.com/9606882/91324281-2f369780-e7c2-11ea-8b4c-c1e15a6b3b46.png)
![Capture du 2020-08-26 17-32-16](https://user-images.githubusercontent.com/9606882/91324287-2fcf2e00-e7c2-11ea-9912-046e039eed7e.png)

**Comment by driesvints** [comment]
Dots in keys aren't supported here.

**Comment by sambindoff** [comment]
@driesvints is there a specific reason for this as I was about to submit a PR to enable dot notation for the `request()->query` method, but won't bother if it's already been discussed and unlikely to be accepted? Cheers

**Comment by driesvints** [comment]
Yes, the input method uses dot notation to access keys in array based input.

https://laravel.com/docs/8.x/requests#retrieving-input

<img width="755" alt="Screenshot 2020-12-22 at 12 29 21" src="https://user-images.githubusercontent.com/594614/102884132-5f7d0280-4451-11eb-840b-3582187fa446.png">


<img width="757" alt="Screenshot 2020-12-22 at 12 29 24" src="https://user-images.githubusercontent.com/594614/102884129-5e4bd580-4451-11eb-90a5-e48b1c1ddb5c.png">

**Comment by sambindoff** [comment]
@driesvints that's understood, it was more for accessing query string parameters using dot notation as I like to be explicit with where my data is coming from.

Due to the `query` method not supporting dot notation I'm currently using the `input` method but this doesn't accurately represent where the data is coming from and I'd like to use the query method in this instance.

I was just curious as to why the query method doesn't support this and if there was a specific reason, otherwise I'd submit the PR for discussion. If there's a legitimate reason that's no problem, I'll just keep using the input method.

**Comment by lk77** [comment]
does not seems consistent to me, result change depending on the request, if it's application/json or x-www-form-url-encoded
