### ISSUE TITLE
`\Illuminate\Support\Str` is not multi-byte safe

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#34027]
- Laravel Version: 7.*

### Description:
Some of the methods are still not multi-byte safe like `\Illuminate\Support\Str::afterLast`.

**Comment by driesvints** [comment]
Please re-open a more thorough issue with proper steps to reproduce.

**Comment by nunomaduro** [comment]
Or even a test that fails.

**Comment by GrahamCampbell** [comment]
NB Just because some code doesn't use mb_ functions, it doesn't mean it doesn't work with mb strings. It could be the case that treating them as single byte strings works just fine for the use case.
