### ISSUE TITLE
[7.x] Polymorphic relations not working with fully qualified class names in mysql

### ISSUE THREAD

**Issue by mvalim** [laravel/framework#34026]
- Laravel Version: 7.24.0
- PHP Version: 7.2.26-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper
- Database collation: utf8mb4_unicode_ci

### Description:
While trying to make some of my models translatable utilizing polymorphic relationships, I found that while the framework can save the related data to the databse correctly, I can't query for specific translations because of the way backslashes work in mysql.

```
trait HasTranslatableAttributes {
  ...
  public function translatables() {
      return $this->morphMany(Translatable::class, 'translatable');
  }
}
```

```
class OperationalArea {
  use HasTranslatableAttributes;
}
```

After saving some translations with:
```
$this->translatables()->firstOrNew([
    'language_id' => $languageId,
])->fill(['translation' => $translation])->save();
```

I have in my database:
```
INSERT INTO `translatables` (`id`, `language_id`, `translatable_type`, `translatable_id`, `translation`) 
VALUES (1, 3, 'Domain\\Admin\\Models\\OperationalArea', 1, 'Translation');

INSERT INTO `translatables` (`id`, `language_id`, `translatable_type`, `translatable_id`, `translation`) 
VALUES (2, 3, 'Domain\\Admin\\Models\\OperationalArea', 1, 'Translation 2');
```

Note that `'Domain\\Admin\\Models\\OperationalArea'` is the class name saved by the framework and is stored as `'Domain\Admin\Models\OperationalArea'`

If I query for the first OperationalArea with the translatable relationship here's how the queries are generated:

```
OperationalArea::with(['translatables' => function($translatablesQuery) {
    $translatablesQuery->where('language_id', 1);
}])->find(1)

select * from `operational_area` where `operational_area`.`id` = 1 limit 1

select * from `translatables` where `translatables`.`translatable_id` in (1) 
and `translatables`.`translatable_type` = 'Domain\Admin\Models\OperationalArea' and `language_id` = 1
```

The second query does not return any records, even if they exist in the database.

If I copy the exact query generated by the framework run it changing only `'Domain\Admin\Models\OperationalArea'` to `'Domain\\Admin\\Models\\OperationalArea'` it works as expected.

```
select * from `translatables` where `translatables`.`translatable_id` in (1) 
and `translatables`.`translatable_type` = 'Domain\\Admin\\Models\\OperationalArea' and `language_id` = 1   
<--- Works
```

Searching the web and reading the docs about polymorphic relationships I did not found any workaround that does not involve morphMap, and since there's no mention of morph maps being required, polymorphic relations should work with fully qualified class names. I think maybe this is a bug.

Maybe the framework should automatically add the extra backslashes, or at least offer a way so we can add it ourselves?

We can customize the way the morph class is resolved with `getMorphClass` but as far as I know we can't change the way it's added to a sql select query.

### Steps To Reproduce:

In addition to the steps described above you can run the following query:
`SELECT 'Domain\Admin\Models\OperationalArea'`
and it returns `DomainAdminModelsOperationalArea`

If you run `SELECT 'Domain\\Admin\\Models\\OperationalArea'` it returns what would be the correct value `Domain\Admin\Models\OperationalArea`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
