### ISSUE TITLE
[7.x] RouteCollection::addLookups ignores domain routing

### ISSUE THREAD

**Issue by tminich** [laravel/framework#34034]
- Laravel Version: 7.26.0
- PHP Version: 7.4.9
- Database Driver & Version: not relevant

### Description:
RouteCollection::addLookups generates a name lookup for routes. If you use domain specific routing routes that are invalid for the current domain are added to this lookup. Even worse, if you have distinct routes for separate domains with the same name, the lookup can contain the wrong route for the given name and the current domain.

The function should check if the route is actually valid for the current domain or at least prefer the route for the current domain when adding it to the name lookup if possible.

**Comment by driesvints** [comment]
Please re-submit with a fully filled out issue template and steps to reproduce.
