### ISSUE TITLE
Validation rules containing customRules and String rules causing a error in php 7.4.9

### ISSUE THREAD

**Issue by s1k3** [laravel/framework#34030]
- Laravel Version: ^.7.24
- PHP Version: 7.4.9
- Database Driver & Version: Maria DB 10.0

### Description:
It looks like using custom rules with string rules is causing a error for php version 7.4.9. I have tested that for php version 7.2 & 7.3 it works great. I think isssue is with php 7.4.9
My code is 
```php
<?php

namespace App\Http\Requests;

use App\Helper\Code;
use App\Models\Exhibition;
use App\Rules\TicketAvailabilityValidator;
use Carbon\Carbon;
use Illuminate\Foundation\Http\FormRequest;


class TicketsFormRequest extends FormRequest
{

    public function rules()
    {
        $rules= [
            'name' => 'required|string',
            'phone' => 'required|digits:11',
            'exhibition_id' => ['required',new TicketAvailabilityValidator],
            'shift' => 'required|string',
            'application_date' => 'required',
        ];
        return $rules;
    }
}
```
***screenshot of the error***
![Screenshot_2020-08-27 🧨 trim() expects parameter 1 to be string, object given](https://user-images.githubusercontent.com/19550001/91420466-90b83e00-e876-11ea-8554-6f64b5b8fd0a.png)

### Steps To Reproduce:
1. Use string rules and Custom rules in a array altogether. Example:
```php
        $rules= [
            'exhibition_id' => ['required',new TicketAvailabilityValidator],
        ];
```
2. Use php 7.4.9 version i have checked for 7.3.7 & 7.2 but did not found any issue

**Comment by driesvints** [comment]
Paste your `TicketAvailabilityValidator` class.

**Comment by s1k3** [comment]
```php
<?php

namespace App\Rules;

use App\Models\Exhibition;
use App\Models\Ticket;
use Carbon\Carbon;
use Illuminate\Contracts\Validation\Rule;

class TicketAvailabilityValidator implements Rule
{

    private $message;

    public function __construct()
    {
        $this->message = "Not available";
    }

    public function passes($attribute, $value)
    {
        //count total number of capacity for this date
        $count = Ticket::where("exhibition_id", $value)->count();
        $exhibition = Exhibition::findOrfail($value);
        //check if is there any capacity left of not
        return $exhibition->total_capacity > $count;
    }

    public function message()
    {
        return $this->message;
    }
}

```

**Comment by s1k3** [comment]
I think the issue is using both the **string** and the custom rule object  together.
* This one works fine. when i only use the custom valiation rule
```php
 $rules= [
     'exhibition_id' => [new TicketAvailabilityValidator],
];

```
* But when i combine this with  a string then the error happens
```php
$rules= [
     'exhibition_id' => ["required",new TicketAvailabilityValidator],
];
```
Again this issue is for only ***php 7.4.9*** it works good for php 7.2 & 7.3

**Comment by driesvints** [comment]
I've just tested this and I can't reproduce it. I'm thinking something else is at off here but it's best that you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
