### ISSUE TITLE
Nested `$attributes->merge` in blade component cause error.

### ISSUE THREAD

**Issue by yaquawa** [laravel/framework#34035]
- Laravel Version: 7.*
- PHP Version: 7.4

### Steps To Reproduce:

`section.blade.php`:
```blade
<section {{ $attributes->merge(['class' => 'mt:20']) }}>
    <div class="container">
          {{ $slot }}
    </div>
</section>
```

`outer-section.blade.php`:
```blade
<x-section {{ $attributes->merge(['class' => 'bg:blue.50']) }}>
    <div>foobar</div>
</x-section>
```

This cause an error `<x-outer-section class="foo" />` 

```
syntax error, unexpected 'endif' (T_ENDIF)
```

**Comment by driesvints** [comment]
You can't use `{{ $attributes}}` on blade components in 7.x. That's only available in Laravel 8.

Please see the docs: https://laravel.com/docs/7.x/blade#managing-attributes

<img width="722" alt="Screenshot 2020-08-27 at 15 45 33" src="https://user-images.githubusercontent.com/594614/91450221-5ea9da80-e87c-11ea-8301-09082b206818.png">
