### ISSUE TITLE
helpers.php

### ISSUE THREAD

**Issue by amr2142018** [laravel/framework#34047]
PHP Parse error:  syntax error, unexpected '?' in /home/smellandsmile/public_html/smellandsmile_core/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 242
i tried many times to change php version but there is no change 
and this is the message of my website 
File not found (404 error)

**Comment by lk77** [comment]
Hello,

which version of laravel framework and php do you have ?

**Comment by amr2142018** [comment]
PHP version 7.4
laravel 5

**Comment by mfn** [comment]
Laravel 5 is not supported anymore, please upgrade to at least Laravel 6

**Comment by lk77** [comment]
you need to downgrade to php 7.3 if you want to keep laravel 5
