### ISSUE TITLE
No index length check

### ISSUE THREAD

**Issue by vokamut** [laravel/framework#34051]
- Laravel Version: 6.18.15
- PHP Version: 7.3.18
- Database Driver & Version: 5.7

### Description:
No index length check

### Steps To Reproduce:

Migration:
```
Schema::create('test', static function (Blueprint $table) {
    $table->increments('id');
    $table->integer('long_column_name_1');
    $table->integer('long_column_name_2');
    $table->integer('long_column_name_3');

    $table->index([
        'long_column_name_1',
        'long_column_name_2',
        'long_column_name_3'
    ]);
});
```

Error:
```
Illuminate\Database\QueryException:
SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'test_long_column_name_1_long_column_name_2_long_column_name_3_index' is too long
(SQL: alter table `test` add index `test_long_column_name_1_long_column_name_2_long_column_name_3_index`(`long_column_name_1`, `long_column_name_2`, `long_column_name_3`))
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
