### ISSUE TITLE
Laravel doesn't return bearerToken when it's expired

### ISSUE THREAD

**Issue by vahidvdn** [laravel/framework#34066]
- Laravel Version: 7.x
- PHP Version: 7.3
- Database Driver & Version:

### Description:

I get bearer token in laravel by following:

```PHP
$bearerToken = $request->bearerToken();
```

When The token is not expired, it returns the token, but as soon as the token becomes expired, it returns null. (The token still exists in apache_request_headers())

Any idea?

**Comment by driesvints** [comment]
Please don't open support issues on this repo (see the issue templates). Ask on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by vahidvdn** [comment]
@driesvints Don't you think there is a tiny possibility that this can be a bug report?
