### ISSUE TITLE
[8.x] Faker doesn't work within model factory states

### ISSUE THREAD

**Issue by axlon** [laravel/framework#34069]
- Laravel Version: 8.x-dev
- PHP Version: 7.4.8
- Database Driver & Version: N/A

### Description:
Right now it appears that using Closure factory states alongside Faker does not work, this is because the Closure is created in another instance of the factory then where it is eventually invoked, so when it is invoked `$this->faker` still references the old instance's faker (which, depending on the situation, may or may not be null). So instead attributes created via faker this way will be null.

### Steps To Reproduce:
- Create a fresh Laravel 8.x-dev application `composer create-project laravel/laravel:dev-develop`
- Paste the following snippet in the UserFactory:
```
    public function foo()
    {
        return $this->state(fn () => [
            'name' => $this->faker->name,
        ]);
    }
```
- Open Tinker
- Paste the following line `User::factory()->foo()->make()`

### Potential fix:
I was able to get it working by adding `$state = $state->bindTo($this);` within the reduce callback in `Factory::getRawAttributes()`, this works because `$this->faker = $this->withFaker()` is called right before the states are resolved, but I don't know what further implications this has.

**Comment by driesvints** [comment]
Thanks! We've fixed this.

**Comment by drbyte** [comment]
Is it just me or is this still broken?

- `laravel new testProject`  (Laravel 8.0.0)
- Paste the following snippet in the `UserFactory.php`
```php
public function foo()
    {
        return $this->state([
            'name' => $this->faker->name,
        ]);
    }
```
- Open Tinker
- Paste the following line: `User::factory()->foo()->make()`
- returns `PHP Notice:  Trying to get property 'name' of non-object`
- `dd($this->faker);` returns `null`

@axlon @driesvints

**Comment by driesvints** [comment]
@drbyte could it be that you're using a unit test where the framework isn't booted?

**Comment by drbyte** [comment]
@driesvints no, it's a proper FeatureTest which properly extends TestCase

Here's a blank repo with a commit showing how to reproduce it:
https://github.com/drbyte/withFaker-bug/commit/45442006ed35c394a23f2372cc5b8012f5463f6d

**Comment by axlon** [comment]
@drbyte its because your state is not within a closure, when you use it like this the state will be resolved as soon as you call the method is called before faker is initialised

Changing it to the snippet below should fix it:

```
    public function male()
    {
        return $this->state(fn () => [
            'name' => $this->faker->firstNameMale,
        ]);
    }
```

**Comment by drbyte** [comment]
Thanks. My brain was treating it as a regular class, but of course it's not. 😄 

The docs don't mention it, but I've submitted a PR. https://github.com/laravel/docs/pull/6329/files
