### ISSUE TITLE
$request->user() is fetching user data from db instead of token

### ISSUE THREAD

**Issue by vahidvdn** [laravel/framework#34061]
- Laravel Version: 7.x
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I have a token (generated with Laravel passport) in my header while sending a request. When I want to extract data from the token, I have the following:
```
$request->user();
```
But this retrieves the data from the db (because when I change the name value, it gives me the new name), which is not a good idea. (since the goal of jwt is extract the data form the token itself and be stateless).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vahidvdn** [comment]
@driesvints I couldn't be able to find any solution. (asked on those community websites). I think the issue should be opened since it's a critical issue.

**Comment by driesvints** [comment]
@vahidvdn the `user` method is meant to extract the user from the DB. This isn't an issue.

**Comment by vahidvdn** [comment]
@driesvints So, how can I get user id from the token itself? (by decoding the token not fetching from the DB)
