### ISSUE TITLE
laravel 7 blade component public methods not working 

### ISSUE THREAD

**Issue by virgiltu** [laravel/framework#34068]
- Laravel Version:7.0
- PHP Version:7.3
- Database Driver & Version:

### Description:

 I have looked everywhere before coming to this submit this. Maybe it is something I am doing wrong but I cant seem to resolve it. 
   Components work in local windows but not on production Linux

### Steps To Reproduce:

Created a component   <x-home.homeMenu default="home_menu"></x-home.homeMenu>   in  index.blade.php

Created homeMenu Component in Views/Component/home
`  <nav class="nav-home-aside">
        <ul class="menu-category">
            @foreach ($categories as $item)
              <li><a href="/category/{{ $item->link }}">{{ $item->title }}</a></li>
            @endforeach
        </ul>
    </nav>`

Generated Component Controller using php artisan make:componenet homeMenu

homeMenu.php located in App/View/Components

```
   public function render()
    {
        $categories = WebCategories::where('show' , 1)->orWhere('show' , 3)->orderBy('sort', 'asc')->get();
        return view('components.homeMenu', compact('categories'));
    }
```

Local Windows Environment Result :   Works Perfectly 
Linux Production Environment:  Error

`Facade\Ignition\Exceptions\ViewException
Undefined variable: categories (View: /www/wwwroot/new.istylefurniture.com/resources/views/components/homeMenu.blade.php)`

### Steps To Fix:
   I also moved the components back outside the component/home folder but same issue.

**Comment by virgiltu** [comment]
If anybody has issues the solution is to Capitalize everything 

as above rename to HomeMenu
also the blade file should be HomeMenu 
and call it the same  <x-HomeMenu default="HomeMenu"></x-HomeMenu>

**Comment by driesvints** [comment]
You @virgiltu you class name is invalid. You always have to use PascalCase class names when working with a PSR-4 autoloader.
