### ISSUE TITLE
Belongs-To-Many Pivot Model no way to set keys?

### ISSUE THREAD

**Issue by zyxxyzyxz** [laravel/framework#34072]
- Laravel Version: 7.26.1
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.19

### Description:
I'm using 2 databases on the same server in a single Laravel app.
- My Default Connection.
- A Connection to another database that I source users from (Also set my User class connection and primary key to match this).

I'm also using a custom pivot model so I can use UUID's in my pivot table.
```php
class AccountUserPivot extends Pivot
{
    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * The "type" of the primary key ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'account_id',
        'user_id',
    ];

    /**
     * Bootstrap the model and its traits.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        // Generate UUID for model instead of integer.
        self::creating(function ($model) {
            $model->id = (string) Str::uuid();
        });
    }
}
```

If we ignore the UUID and Custom Pivot for a second, and I leave my pivot migration as just auto-incrementing and use the code below, I get the desired functionality.
```php
return $this->belongsToMany(Account::class, 'account_user', 'user_id', 'account_id')
            ->withTimestamps();
```

However, if I do;
```php
return $this->belongsToMany(Account::class, 'account_user', 'user_id', 'account_id')
            ->using(AccountUserPivot::class)
            ->withTimestamps();
```

Then the parameters passed in `belongsToMany` get completely ignored, and after trying various ways of setting the keys inside the pivot model, e.g;
```php
public function __construct()
    {
        $this->setPivotKeys('user_id', 'account_id');

        parent::__construct();
    }
```

It treats them like they don't even exist and continues to try and "guess" the keys which results in things like `user_user_id` due to my custom connection setup.

I've also tried setting them explicitly in the member variables of the pivot model like so with no luck.
```php
/**
     * The name of the foreign key column.
     *
     * @var string
     */
    protected $foreignKey = 'user_id';

    /**
     * The name of the "other key" column.
     *
     * @var string
     */
    protected $relatedKey = 'account_id';
```

Not sure if I'm just missing something or if this is a bug, but I've attempted to search pretty much everywhere and haven't been able to come up with a solution over the last couple of days.

I sort of need to use a custom pivot model and I can't just get rid of it, because due to my custom connection setup, when doing something like;
```php
return $this->belongsToMany(Account::class, 'account_user', 'user_id', 'account_id')
            ->withTimestamps();
```
It works because `Account` is the parent model, and it has a connection of my default connection (where the pivot table will be located.)

As soon as I try and do the inverse side of the relationship;
```php
return $this->belongsToMany(User::class, 'account_user', 'user_id', 'account_id')
            ->withTimestamps();
```
It will break because `User` is now the parent model, and it has a connection of my other connection so it tries to search for the pivot table in the wrong database.

I believe I can fix this via a Pivot Model as I could just set the table/connection based on `instanceof` or something similar, but from my current testing it appears a lot of stuff I try and do inside of the custom pivot model is just being flat out ignored. (Definitely is being triggered though if I put a `dd()` it gets hit no problem.)

### Steps To Reproduce:
Same as described above. Can provide more information if necessary but felt I was pretty thorough above. 👍

**Comment by driesvints** [comment]
I can't reproduce this. Combining `using` and custom columns works for me. 

Please create a repo with a minimum amount of code that reproduces the problem. Please commit your changes separately from the base skeleton.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
