### ISSUE TITLE
php artisan schema:dump error (mysqldump8 and mysqld 5.7)

### ISSUE THREAD

**Issue by roberto-butti** [laravel/framework#34078]
- Laravel Version: 8.0.0
- PHP Version: 7.4.*
- Database Driver & Version: mysqldump 8 and mysqld 5.7

### Description:
executing :
```
php artisan schema:dump
```
I receive an error

```
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'db_laravel_8' AND TABLE_NAME = 'failed_jobs';': Unknown table 'column_statistics' in information_schema (1109)
```
due to the different version mysqldump 8 against an older mysql daemon 5.7.
schema:dump execute mysqldump local command. The version 8 has the flag column-statistics set as 1 (true) by default. mysql5.7 could not have "information_schema.COLUMN_STATISTICS".

### Steps To Reproduce:
In a envirnoment where you have mysqldump 8 and mysql5.7 execute php artisan schema:dump

### Fix
- In baseDumpCommand() (MySqlSchemaState.php) add option column-statistic=0
```
    protected function baseDumpCommand()
    {
        $gtidPurged = $this->connection->isMaria() ? '' : '--set-gtid-purged=OFF';
        $statisticOff = " --column-statistics=0 ";
        return 'mysqldump ' . $statisticOff . ''.$gtidPurged.' --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host=$LARAVEL_LOAD_HOST --port=$LARAVEL_LOAD_PORT --user=$LARAVEL_LOAD_USER --password=$LARAVEL_LOAD_PASSWORD $LARAVEL_LOAD_DATABASE';
    }
```

**Comment by taylorotwell** [comment]
Do you want to PR your fix?

**Comment by roberto-butti** [comment]
Sure!

**Comment by roberto-butti** [comment]
I submitted the PR : #34079

**Comment by vanthao03596** [comment]
mysqldump: [ERROR] unknown variable 'column-statistics=0'
I got this error when try to run php artisan schema:dump

**Comment by driesvints** [comment]
@vanthao03596 which database driver and version are you running?

**Comment by roberto-butti** [comment]
> mysqldump: [ERROR] unknown variable 'column-statistics=0'
> I got this error when try to run php artisan schema:dump

@vanthao03596  Which version of mysqldump ? mysqldump --version

**Comment by driesvints** [comment]
your database driver. Mysql? maria db? what version?

**Comment by roberto-butti** [comment]
I replicated the error.
With mysql-client (mysqldump) 8 , column-statistics is supported;
with mysql-client (mysqldump) 5.7, column statistic is NOT supported.

Using column-statistics=0, it allows to use mysqdump8 with a mysql5.7(server)
Using column-statistcis=0 fails with mysqldump5.7

Possible solutions that I have in mind:
- avoid to use column-statistics by default, and add a option in schema:dump (for example disable-statistic)
- try to do some "magic": executing mysqldump without column-statistci, if it fails, try with column-statisctics.

I like more the first one.

**Comment by vanthao03596** [comment]
@roberto-butti  @driesvints I'm using mysqldump, mysql 8.0.2
![1](https://user-images.githubusercontent.com/34786441/92105702-700b5d80-ee0d-11ea-955a-0a86eb54a5cd.png)

**Comment by driesvints** [comment]
@roberto-butti so it seems it's not just mysql 5.7

**Comment by roberto-butti** [comment]
> @roberto-butti @driesvints I'm using mysqldump5.7, mysql 8.0.2
> ![1](https://user-images.githubusercontent.com/34786441/92105788-8dd8c280-ee0d-11ea-9ad3-e38f12fdd9fe.png)

@vanthao03596  just to clarify, 
mysqldump is version 5.7.30 and the mysql database service is 8.0.2. Is it correct ?

@driesvints  do you want i add a option in DumpCommand to allow the user to "disable" statistics and force (--column-statistics=0) only.
The parameter could be column-statistics-off, or something similar. 
I could create a PR in my break lunch or this evening.

**Comment by driesvints** [comment]
I think you'd want statistics off by default? The migrations are only meant for your DB structure, nothing else really.

**Comment by roberto-butti** [comment]
ok, I agree to keep --column-statistics=0 in the code as default (now we have this, in the latest codebase).
And allow to the user to declare in command line to  skip column-statistics (with an option) if the user has a old version of mysqldump.
--skip-column-statistics (the name of the option in the signature of the command).
Is it ok for you, @driesvints ?

**Comment by driesvints** [comment]
I think we need to find a solution where it never faults, on any MySQL version. In which specific situations does it fail now?

**Comment by roberto-butti** [comment]
As far as i know on mysqldump 5.7 it fails bacause it doesn't support column-statistics=0 .
It is quite a common problem on backup software that rely on mysqldump. I see that lot of them has the option in the configuration to set or not the column-statistics.
I'm courious to see if also DbDumper of Spatie has the same problem...

**Comment by driesvints** [comment]
Is there any way we can check for the MySQL version in that command to not use the flag when it's 5.7?

**Comment by driesvints** [comment]
I mean mysqldump 5.7

**Comment by roberto-butti** [comment]
As far as i know we have mysqldump --version.
But the output is differente based on the version , the build and the architecture.
For mysqldump 8 :
```
mysqldump  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)
```
or,  for mysqldump 5.7:
```
mysqldump  Ver 10.13 Distrib 5.7.29, for osx10.15 (x86_64)
```
See _Ver_ and the _Distrib_.
So I think that we can't rely on the version output.

**Comment by taylorotwell** [comment]
We could just state that the feature requires a certain version of mysqldump?

**Comment by roberto-butti** [comment]
Sure @taylorotwell . 
At this point my suggestion is : 
the requirements is to have mysqldump version 8.

My additional suggestion is , for the user with an older version of mysqldump, allow them to use and additional option in command line, and allow them to use the feature schema:dump (is a kind of "legacy" option). What do you think ?

**Comment by roberto-butti** [comment]
I'm going to release a PR, if you agree.

I think that i'm covering all scenarios.
Let me know what do you think ab out this proposal.

The only thing requested by the user for not having errors,  is to force the user to use the option --column-statistics-off in the condition with mysqldump 8 and mysqld 5.7.
Considering that is an edge case, the great library of spatie DbDumper it doesn't support this scenario (i think that i will drop a PR also for that package).


mysqldump version | mysql service version | artisan command to use
-|-|-
5.7 | 5.7 |  php artisan schema:dump
8 | 8 |  php artisan schema:dump
5.7 | 8 |   php artisan schema:dump
8 | 5.7 |   php artisan schema:dump --column-statistics-off

**Comment by driesvints** [comment]
Is there really no way to determine the MySQL version in the command? Then we can work around this entirely.

**Comment by roberto-butti** [comment]
> Is there really no way to determine the MySQL version in the command? Then we can work around this entirely.

Currently I'm not able to determine a reliable way to identify exactly the version :(

**Comment by roberto-butti** [comment]
PR #34125 
Tested with:

mysqldump version | mysql service version | artisan command to use
-|-|-
5.7 | 5.7 |  php artisan schema:dump
8 | 8 |  php artisan schema:dump
5.7 | 8 |   php artisan schema:dump
8 | 5.7 |   php artisan schema:dump --column-statistics-off

Tested also with Posgtres connection (pg_dump) with php artisan schema:dump

**Comment by anburocky3** [comment]
![image](https://user-images.githubusercontent.com/15264938/98961490-9e9f6600-252b-11eb-8a05-752812995747.png)

**Comment by anburocky3** [comment]
![image](https://user-images.githubusercontent.com/15264938/98961543-aeb74580-252b-11eb-8a1c-ae75cd6c2f08.png)
and the file is .dump not .sql ?
