### ISSUE TITLE
static::setEventDispatcher(new NullDispatcher($dispatcher)) still dispatch event

### ISSUE THREAD

**Issue by flyw** [laravel/framework#34071]
- Laravel Version: 6.18.37
- PHP Version: 7.2.19
- Database Driver & Version:

### Description:
Illuminate\Database\Eloquent\Concerns\HasEvents 
when call: withoutEvents 
```php
static::setEventDispatcher(new NullDispatcher($dispatcher)) // not disable event
```
event still fired.

### Steps To Reproduce:
```php
class MyModel extends Model {
    protected $dispatchesEvents = [
        'saved' => MyModelSavedEvent::class,
    ];
}

MyModel::withoutEvent(function () {
  $model = MyModel::find(1);
  $model->Save();
});
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
