### ISSUE TITLE
[7.x] Eloquent `paginate()` method does not support `distinct()` property

### ISSUE THREAD

**Issue by hameesakhan** [laravel/framework#34070]
- Laravel Version: 7.14.1
- PHP Version: 7.3.1
- Database Driver & Version:
10.1.37-MariaDB
 libmysql - mysqlnd 5.0.12-dev

### Description:
I have about 121 records in `products` table. After few joins the total records become 220. Using `DISTINCT` clause reduces the results to 97 records. But the collection `->total()` method still yields 220 records.

I have also tried removing `->distinct()` and the test went successfully. The resulting collection did has 220 records.

I think the problem is in this method `runPaginationCountQuery` which doesn't honor $this->distinct property:
laravel\framework\src\Illuminate\Database\Query\Builder.php.

### Steps To Reproduce:
Have a table with multiple same records and use `->distinct` and `->paginate()` together on Eloquent object.

Elouent Query Builder (yields 97 records):
```
$productsQB = Product::select('products.id', 'products.category_id', 'products.slug', 'products.name', 'products.currency_id', 'products.price')
            ->join('categories AS subSubCategories', 'subSubCategories.id', 'products.category_id')
            ->join('categories AS subCategories', 'subCategories.id', 'subSubCategories.category_id')
            ->join('categories', 'categories.id', 'subCategories.category_id')
            ->join('product_specifications', 'products.id', 'product_specifications.product_id')
            ->where('categories.id', $category->id)
            ->distinct();
```

Collection (which shows 220 total records):
`Show {{$products->firstItem()}} - {{$products->lastItem()}} Of {{ $products->total()}} Product`

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26935 and numerous other issues.
