### ISSUE TITLE
Laravel docs site [https://laravel.com/docs/8.x] showing old version warning on version 8.

### ISSUE THREAD

**Issue by aliadhillon** [laravel/framework#34087]
- Laravel Version: 8.0.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Laravel docs website [laravel.com/docs/8.x](https://laravel.com/docs/8.x) is showing 
"WARNING You're browsing the documentation for an old version of Laravel. Consider upgrading your project to Laravel 7.x." on selecting version 8 of laravel documentation.
![Annotation 2020-09-01 213230](https://user-images.githubusercontent.com/13802089/91881812-872a3e00-ec9b-11ea-87d9-ce348d4eca79.jpg)

**Comment by driesvints** [comment]
@aliadhillon this will go away when the docs are live next week. Just ignore it for now.
