### ISSUE TITLE
laravel session conflict

### ISSUE THREAD

**Issue by hannanstd** [laravel/framework#34081]
hi
consider you have multiple browser tabs. and you have one form on each tab. then you click submit button of all form in all tabs very fastly (submit all forms in each browser tab together).
and we redirect user in contorller with ` back()->withInput()`.
then when we redirect to back, we see inputs of some forms conflict and there is the data of some forms in other forms.
how can i fix this bug?

Laravel Framework 6.18.35

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
