### ISSUE TITLE
Duplicate column name while aggregating

### ISSUE THREAD

**Issue by mbm-rafal** [laravel/framework#34096]
- Laravel Version: 7.27.0
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.5.5 MySQL

### Description:
For aggregate selects it's forbidden to have a duplicated column names. 

`[2020-09-01 18:59:47] local.ERROR: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'description' (SQL: ... at /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)`

### Steps To Reproduce:
Execute this query.

```
$count = DB::query()->fromSub(function ($query) {
   $query
       ->from('users')
       ->addSelect('email')
       ->addSelect('email')
       ->groupBy('email');
}, 'a')->count();
```

### Motivation
When using a repositories design patter, we are having criteria that build a query based on the data in the specific criteria,
we don't check on this level agains existing columns. I believe array_unique could be executed on the columns just before sending a query.  It does not affect any column select aliases.

https://github.com/laravel/framework/discussions/34097

**Comment by taylorotwell** [comment]
If you would like to submit a PR to run `array_unique` feel free.

**Comment by saltamay** [comment]
Can anyone please confirm that this was indeed resolved? I can't seem to find the changes in the production code.
