### ISSUE TITLE
Email dns validation passes if domain has no mx record

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#34092]
- Laravel Version: 7.27.0
- PHP Version: 7.4.9

### Description:
The email dns validation passes emails as correct even if they have no mx record and you really can't send a mail to the domain.

### Steps To Reproduce:
```php
$v = \Illuminate\Support\Facades\Validator::make([
    'email' => 'xxx@icluod.com', // transposed characters 'o' and 'u'
], [
    'email' => 'email:dns',
]);
dd($v->passes());
```

### Reason for the Result:
Laravel is using `DNSCheckValidation` of `egulias/email-validator`. But their implementation is a little bit tricky:

The provided domain passes the dns validation because the domain has an `A record` but [a warning is saved that no mx-record was found](https://github.com/egulias/EmailValidator/blob/master/src/Validation/DNSCheckValidation.php#L139). So laravel would have to correctly fail the `email:dns` validation if this warning is present as the email recipient is not reachable. At the moment it's just looking at the boolean return value.

**Comment by driesvints** [comment]
I don't think a warning is a valid reason to fail this rule. We depend on the boolean return.

**Comment by tpetry** [comment]
@driesvints @taylorotwell What is the intended use case for the dns validation? The laravel documentation does not state what the dns validation should do. But with the actual implementation the dns check **does not** verify that the host has mx dns records so the recipient is reachable. Unreachable hosts pass the validation.

**Comment by driesvints** [comment]
@tpetry it's best to reference the docs for the underlying email validator library for that.

**Comment by iosty** [comment]
indique le répertoire à suivre je ne sais pas ou est ce que je doit effectuer la modification
