### ISSUE TITLE
Http client get method response has 200 status, when it recieve 422

### ISSUE THREAD

**Issue by sidigi** [laravel/framework#34094]
- Laravel Version: v7.26.1
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Http client returns 200 ok if response send 422 http status code

Insomnia / Postman / curl
GET http://test.com/users/1 // Response with 422 in other http clients

Laravel Http client:
$response = Http::get('http://test.com/users/1') 
$response->status()  // 200 in laravel http client

### Steps To Reproduce:
Make http request with method get to any http url, which returns http status 422. It need for example to validate query parameters for get, for example ?id=916cb58e-ad95-45b8-9b21-116573560149 - we need check uuid and throw 422 exception if it is not uuid

I think it need throw error

**Comment by taylorotwell** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/463230/91992335-a35cc800-ecf9-11ea-888e-d5917f85e4b9.png">

<img width="143" alt="image" src="https://user-images.githubusercontent.com/463230/91992345-a5bf2200-ecf9-11ea-8bb6-e52ec205da2c.png">

**Comment by sidigi** [comment]
nope

### If it from laravel it is 422 status (trace)
```
> GET /foo HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: insomnia/7.0.3
> Cookie: laravel_session=eyJpdiI6Ik5yTjA2SW9zM1pLQnFWSjluZ1lDekE9PSIsInZhbHVlIjoibzJkTXJmR3REcnR4MFZDMWZUM2dPL3FhWndKZFErelh5dDgzaStqelFWekNhNXh0TFV3WjNuYkZQWG8reWNGaWxSNWpDQzFxa1dtQlI2cDNkRVJqMWxGSzN2LzU3ZmVLU1N3aWp2SVJRSThaaHozaVdCQWswL1llaDlSd0VsRUciLCJtYWMiOiIyMGVmNmNiMjc5OTQyMWEzMDQ3MmE3MmM5ODIyODgzYzEzMDBjMWJhOWU4MjFlZDkzM2M2ZWI5NzM1MjUxMjAwIn0%3D; XSRF-TOKEN=eyJpdiI6InFTWHNiN2NlSkkreGxROVZBVjlZb2c9PSIsInZhbHVlIjoiUEJKOGZEWXZqN0VkaEx6VGtMS3ZBd1YyNDNSWS9kYXVFRW1GWTBQMzF1QmV1S0NWRDBPdko5Q3NmQUpJNDVQNFFDMUNUTmN0OGFRbkRhL1p6RW44eFR2TlFOdEZIMXB4d2ZqaGp0N0N1VDB6cnVUMStubStBc1RBOWZnVEZUWTYiLCJtYWMiOiI2ZTFlZjdlYmM4OGQ5NDhhZDdmMGM1NWYzOTlmZmIyZjU5YWU2M2FmNDlmZmE3NWE5OWRiZjc1Y2U0ZWMxZTBiIn0%3D
> Accept: application/json

< HTTP/1.1 422 Unprocessable Entity
< Host: 127.0.0.1:8000
< Date: Wed, 02 Sep 2020 15:49:53 GMT
< Connection: close
< X-Powered-By: PHP/7.4.3
< Cache-Control: no-cache, private
< Date: Wed, 02 Sep 2020 15:49:53 GMT
< Content-Type: application/json
```

### But this response (trace) is 200
```
> GET /contacts?filter%5Bauthor_id%5D=1&filter%5Buser_id%5D=1 HTTP/1.1
> Host: api.bgs-events.com
> User-Agent: insomnia/7.0.3
> Cookie: auth.strategy=cognito; auth.redirect=%2Fevents
> Accept: application/json
> Content-Type: application/json
> Content-Length: 140

| {
| 	"value": "93423423425",
| 	"type": "phone",
| 	"resource_id": "5c4dd772-389b-4639-be90-61969ba52bfc",
| 	"resource_type": "user-service.user"
| }

* upload completely sent off: 140 out of 140 bytes

< HTTP/1.1 422 
< Date: Wed, 02 Sep 2020 12:26:37 GMT
< Content-Type: application/json
< Content-Length: 114
< Connection: close
< x-amzn-RequestId: ******
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: *
< x-amzn-Remapped-Content-Length: 114
< x-amzn-Remapped-Connection: keep-alive
< X-RateLimit-Remaining: 56
< x-amz-apigw-id: SPNbdHNcFiAFT0Q=
< Cache-Control: no-cache, private
< x-amzn-Remapped-Server: Apache/2.4.38 (Debian)
< X-RateLimit-Limit: 60
< X-Powered-By: PHP/7.4.9
< Access-Control-Allow-Methods: *
< x-amzn-Remapped-Date: Wed, 02 Sep 2020 12:26:37 GMT
```

**Comment by sidigi** [comment]
My fall it is proxy

**Comment by RikkiMasters** [comment]
I just had the same issue.

For me it was because the api is sending back HTML as I didn't specify json as the return type, so it will always be 200 ok.

Use
`Http::accept('application/json')->get('http://example.com/users');`
or
`Http::acceptJson()->get('http://example.com/users');`
