### ISSUE TITLE
My php artisan queue:work and also php artisan queue:listen nothing works. Still I have jobs in my table. My jobs are never excecuted.

### ISSUE THREAD

**Issue by Piccotalent101** [laravel/framework#34104]
- Laravel Version: 5.3
- PHP Version: 7.0
- Database Driver & Version: mysql

My queue was working firn with supervisor. Then I have stopped queue and supervisor for some purpose. Again I have restarted, But queue is not working...Supervisor showing running sttaus.. But queue is not working. Still jobs are in table.

I don't what is the exact issue

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by Piccotalent101** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

You are not supporting 5.3 bugs ...Or laravel 5.3 not support queue?
