### ISSUE TITLE
model not found public decrement method

### ISSUE THREAD

**Issue by zoulux** [laravel/framework#34107]
- Laravel Version: 7.x
- PHP Version: 7.4
- Database Driver & Version: mysql8.0

### Description:
```php
            $course = Course::query()->first();
            $course->increment('total_star_score', $star);
```

the phpStorm tip `Member has protected access, but class has magic method __call`

![image](https://user-images.githubusercontent.com/9365514/92104929-a6001000-ee14-11ea-81c6-87d32365fffa.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by zoulux** [comment]
@driesvints Thank you,But i think is a bug. I'm prepare make a merge request.
