### ISSUE TITLE
Email Validation is validating an invalid Email Address

### ISSUE THREAD

**Issue by ismailansari** [laravel/framework#34119]
- Laravel Version: 6.18.35
- PHP Version: 7.2.24
- Database Driver & Version:

Description:
I'm using simple laravel validation and have the following rules:

`'pemail' => 'required|email',`

but this email is showing as invalid email i.e. `34@34.34`

**Comment by ManojKiranA** [comment]
Try this out

`'pemail' => ['required','email:filter'],`

For more email validation check take a look at this

https://laravel.com/docs/7.x/validation#rule-email

**Comment by driesvints** [comment]
This is a valid email address.

**Comment by ismailansari** [comment]
Thanks @driesvints,  Please accept my apology, I didn't checked the documentation before creating the issue this time. I was stupid :-(
