### ISSUE TITLE
Creating a new laravel project using --dev does not get me the latest 8.x code for Bus

### ISSUE THREAD

**Issue by alexbowers** [laravel/framework#34129]
- Laravel Framework 8.x-dev

### Description:

I ran `laravel new <project> --dev` and expected to be able to try out batch jobs, however looking at the code, in illuminate/Bus, Batch does not exist.

### Steps To Reproduce:
- Run `laravel new <project> --dev`

**Comment by AegirLeet** [comment]
Are you using version `^4.0` of `laravel/installer`?

**Comment by driesvints** [comment]
Please use v4 of the installer.

**Comment by alexbowers** [comment]
I can confirm this works on v4. Thanks.
