### ISSUE TITLE
ENV file not recognizing Sometimes!

### ISSUE THREAD

**Issue by lovecoding-git** [laravel/framework#34137]
- Laravel Version: 7.14.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Apache 2.4,

### Description:

I sometimes get this error.

`production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at ~\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:80)`

And this too.
![image](https://user-images.githubusercontent.com/61916777/92226873-fdb37f80-eed7-11ea-8be3-7c993b7bf202.png)

I have worked 2 years on Laravel project and I think I have idea about most errors.
But I have no idea why this error sometimes comes.
It's not coming every time. About 1 time per about quick 100 or more requests. (Especially when I switch links very quickly.)
There is the same error log for Ajax request too. (I saw it when I switch Session values quickly.)

It happens both on my local & server too.
(I regenerated key, config:clear, cache:clear ...)

Is this kind of Laravel bug? or is it web server issue?
Have anyone ever seen this kind of issue before?
I posted this issue on slack channel and stackoverflow too but the answers were "generated key? cleared cache? ...)
And again, the project is working well without any issue but sometimes it went wrong like above.

Thank you!

**Comment by sisve** [comment]
We've been talking about this on Slack, and the problem is how Apache on Windows defaults to executing php requests within the same process, so the environment variables gets really wonky. I've written more about this at https://github.com/laravel/framework/issues/24510#issuecomment-395865724

This is a server configuration issue, and not something that can be solved with code.

**Comment by jackbaron** [comment]
@lovecoding-git you got a solution for this? i have a same problem
