### ISSUE TITLE
Http client library is not maintaining the numeric keys of the array I am sending

### ISSUE THREAD

**Issue by rafatga** [laravel/framework#34130]
- Laravel Version: 7.0.0
- PHP Version: 7.4.1
- Database Driver & Version: MYSQL 5.7.26

### Description:
I have an array with numeric keys that I am trying to send to an API. Unfortunately using the http client library it overwrites the numeric keys of my array that I am trying to send.

`
$arr = [
        11 => [
            'vanguard_core_id' => 1
        ]
    ];
`
OR
`
$arr = [
        '11' => [
            'vanguard_core_id' => 1
        ]
    ];
`

AFTER IT CONVERTS TO

`
$arr = [
        0 => [
            'vanguard_core_id' => 1
        ]
];
`

### Steps To Reproduce:

`
    $arr = [
        11 => [
            'vanguard_core_id' => 1
        ]
    ];

    $re = Http::asJson()->withHeaders(['Accept' => 'application/json']);

    $response = $re->post($url, $arr);
`

### The Problem
The issue is in the method send() of the class PendingRequest.php. There is a piece of code that merges the $option array and mess up the array keys.

Illuminate/Http/Client/PendingRequest.php

<img width="259" alt="Screen Shot 2020-09-04 at 9 04 54 AM" src="https://user-images.githubusercontent.com/3813277/92211224-68d96380-ee90-11ea-80e4-728938419751.png">

<img width="266" alt="Screen Shot 2020-09-04 at 9 05 12 AM" src="https://user-images.githubusercontent.com/3813277/92211237-6f67db00-ee90-11ea-8ae7-7f16459b5fcf.png">

<img width="407" alt="Screen Shot 2020-09-04 at 8 49 45 AM" src="https://user-images.githubusercontent.com/3813277/92211252-7858ac80-ee90-11ea-9e2d-86ab77a7609d.png">

<img width="631" alt="Screen Shot 2020-09-04 at 9 05 20 AM" src="https://user-images.githubusercontent.com/3813277/92211296-89a1b900-ee90-11ea-9920-039e199048bd.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
