### ISSUE TITLE
Laravel Queue Worker --timeout argument is not working 

### ISSUE THREAD

**Issue by voyula** [laravel/framework#34148]
- Laravel Version: 7.22.4
- PHP Version: 7.4.9
- Database Driver & Version: -

### Description:

![Image](https://i.imgur.com/Ny3CUJT.png)

**Comment by taylorotwell** [comment]
Works fine for me:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/463230/92283519-aa383600-eec5-11ea-8577-a29c2c3476e4.png">

**Comment by voyula** [comment]
@taylorotwell This problem can be for Curl requests?

**Comment by voyula** [comment]
I will try with curl request.
