### ISSUE TITLE
Custom Intermediate Table Models does not fire event on pivot model update

### ISSUE THREAD

**Issue by MostafaNobaghi** [laravel/framework#34157]
- Laravel Version: 7.27.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql

Description: Custom Intermediate Table Models does not fire event on pivot model update (using ```updateExistingPivot``` method). the other methods like attache, detache and sync works fine.

**Comment by driesvints** [comment]
Please provide a way to reproduce.

**Comment by taylorotwell** [comment]
Closing pending reproducable example.
