### ISSUE TITLE
8.x Frontend scaffolding throws error

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#34158]
After running:
```
composer require laravel/ui   // that works fine
```

Next according to docs you can run:
```
php artisan ui bootstrap
//or
php artisan ui bootstrap --auth
```
This is prior to npm and node js.  In other words auth should be scaffolded without npm or node js, yet it throws this error:
```
   ErrorException

  copy(C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\resources\sass/_variables.scss): failed to open stream: No such file or directory

  at C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\vendor\laravel\ui\src\Presets\Bootstrap.php:42
     38▕      * @return void
     39▕      */
     40▕     protected static function updateSass()
     41▕     {
  ➜  42▕         copy(__DIR__.'/bootstrap-stubs/_variables.scss', resource_path('sass/_variables.scss'));
     43▕         copy(__DIR__.'/bootstrap-stubs/app.scss', resource_path('sass/app.scss'));
     44▕     }
     45▕
     46▕     /**

  1   C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\vendor\laravel\ui\src\Presets\Bootstrap.php:42
      copy()

  2   C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\vendor\laravel\ui\src\Presets\Bootstrap.php:15
      Laravel\Ui\Presets\Bootstrap::updateSass()
```
Note bootstrap.php does exist.

Even in the Authentication chapter, quick start it has:
```
php artisan ui vue --auth
```
Also errors.

The docs clearly state, a quote from docs:

> Once the laravel/ui package has been installed, you may install the frontend scaffolding using the ui Artisan command:

It does not say npm or node js is required to scaffold auth.

I don't use mix, and scaffolding auth has always worked without npm or node js.  Will this be fixed by final release?

### EDIT:

Under resources folder I manually created a sass folder, then the scaffolding worked.  So an empty sass folder should be created during install or while running ui.

**Comment by taylorotwell** [comment]
Fixed.

**Comment by vicsystems55** [comment]
worked for me too

**Comment by A-hamada-nexa** [comment]
I have the same issue and I saas created  folder maualy but still it shows same error
