### ISSUE TITLE
Cannot extend model factories

### ISSUE THREAD

**Issue by kayandra** [laravel/framework#34166]
- Laravel Version: 8.x
- PHP Version: 7.4.3
- Database Driver & Version: sqlite 3.31.1

### Description:

In the previous versions of Laravel, we used to be able to extend model factories by calling `factory(Model::class)->raw()`. I checked the abstract factory at `Illuminate\Database\Eloquent\Factories\Factory` and noticed we don't have a raw method defined. 

### Steps To Reproduce:

Therefore, doing something like `Model::factory()->raw()` won't work. Then I tried getting raw data using `Model::factory()->definition()` which will also fail if we try to access `$this->faker` in the definition as faker isn't setup yet.

A temporary fix from my end is to boot faker from within the factory definition

```
    public function definition()
    {
        $this->faker = $this->withFaker();

        return [
            'title' => $this->faker->company,
        ];
    }
```

**Comment by aidan-casey** [comment]
What is your use case? Are you trying to add to or change data that was previously generated? It seems like the below example might be what you are after?

```php

<?php

namespace Database\Factories;

use App\Models\Test;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class TestFactory extends OtherFactory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Test::class;    // Leave this, or not.

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return array_merge(parent::definition(), [
            'foo' => 'bar'
        ]);
    }
}


```

**Comment by kayandra** [comment]
Yeah, this would work, but if you used faker in the parent definition it would fail due to the fact that faker has not been instantiated at that point.

**Comment by aidan-casey** [comment]
I actually did test this before posting and the above works with faker as well. It’s literally just merging the raw definition array on the other factory with whatever new key / value pairs you put in. Have you tested the above and run into issues?

**Comment by kayandra** [comment]
It doesn't work for me. Let me provide more context here.

I have a `ProjectFactory` extended by a `TestFactory`

**ProjectFactory**
```
    public function definition()
    {
        return [
            'title' => $this->faker->company,
            'user_id' => User::factory(),
        ];
    }
```

**TestFactory**
```
    public function definition()
    {
        return array_merge(parent::definition(), [
            'foo' => 'bar'
        ]);
    }
```

In a test file i.e `ProjectTest` 

```
    /** @test */
    public function add_dashboard_to_project()
    {
        dd(Test::factory()->definition()); 
    }
```

Here's the error I get

```
• Tests\Feature\DashboardTest > add dashboard to project
   ErrorException 

  Trying to get property 'company' of non-object

  at database/factories/ProjectFactory.php:28
     24▕     {
     25▕         // $this->faker = $this->withFaker();
     26▕ 
     27▕         return [
  ➜  28▕             'title' => $this->faker->company,
     29▕             'user_id' => User::factory(),
     30▕         ];
     31▕     }
     32▕ }

  1   database/factories/ProjectFactory.php:28
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()

  2   database/factories/TestFactory.php:24
      Database\Factories\ProjectFactory::definition()


  Tests:  1 failed
  Time:   0.10s
```

I just want a raw representation of the factory similar to what we had in v7. Adding a `raw()` method to the factory would resolve this.

**Comment by aidan-casey** [comment]
I guess I'm not sure why you would need to get the raw definition outside of a factory? The above _would_ work if you run something like: `dd(Test::factory()->make()->toArray())`, but what's your goal in trying to get the raw definition before having fake data generated outside of a factory class?

**Comment by taylorotwell** [comment]
This is a feature request. Make a PR with the feature you want if you wish.

**Comment by taylorotwell** [comment]
Also note that if you wanted the raw array you could just define a method on the parent factory that returns the raw array and call it from both the child and the parent.
