### ISSUE TITLE
8.x return view throwing error

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#34160]
A view and layout that works perfect in 7.* latest is throwing this error in 8.0:
```
Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct(), 0 passed in C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\vendor\facade\ignition\src\IgnitionServiceProvider.php on line 128 and exactly 1 expected (View: C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\resources\views\layouts\dog\indextp.blade.php) 
```

I know I am getting to controller because I can dd the data just fine.

This is happening on any view, I have tried quite a few views.

Note I am not using tailwind but I did do:

> you should add the following method call to the boot method of your application's AppServiceProvider:

use Illuminate\Pagination\Paginator;
```
    public function boot()
    {
        Paginator::useBootstrap();
    }
```

**Comment by jimgwhit** [comment]
This is now resolved, but still weird.  I changed the very top of layout file  from:
```
<html>
```
To
```
<!DOCTYPE html>
<html>
```
It works. Yet in the 8.0 documentation the examples still show only:
```
<html>
```
And nothing in the upgrade guide stating this will cause an error.
I'll leave open just temporary in case someone else encounters  this.

**Comment by Windygo** [comment]
While upgrading from 7.x to 8.x came across above issue:
I added the missing argument on line 128 

//return new PhpEngine();  // raised issue
return new PhpEngine(**$this->app['files']**);  // resolved issue

See line ~128
https://github.com/illuminate/view/blob/master/ViewServiceProvider.php
