### ISSUE TITLE
Calling "Route::getRoutes()->match()" in a middleware will retrieve an empty model out of "Route Model Binding"

### ISSUE THREAD

**Issue by mkwsra** [laravel/framework#34165]
- Laravel Version:  7.25.0
- PHP Version:  7.4.8
- Database Driver & Version: mysql  Ver 8.0.21 for osx10.15 on x86_64 (Homebrew)

### Description:
In any middleware calling  `Route::getRoutes()->match` will prevent healthy route model binding, resulting not 404 but a new default instance of the model

### Steps To Reproduce:
add this line to any of your middlewares : 
```
Route::getRoutes()->match($request)
```

Then add any route/model binding
```
Route::get('users/{user}', function (\App\User $user) {
    dd($user);
});
```

**Comment by driesvints** [comment]
We don't support using `getRoutes` like this.

**Comment by mkwsra** [comment]
Okay, can you tell me what is supported? any alternative way?

**Comment by driesvints** [comment]
Please try a support channel.
