### ISSUE TITLE
laravel new basic not working

### ISSUE THREAD

**Issue by shahakshay938** [laravel/framework#34171]
- PHP Version: 7.4.9
-  Composer Version: 1.10.10
- Windows 10 (Version 1903)

**Description:**

I have installed composer setup in machine and after that i have installed laravel framework globally using this command `composer global require laravel/installer`. After next i have run the `laravel new blog` command so it show me this error
`'rm' is not recognized as an internal or external command, operable program or batch file.`

**Comment by owenvoke** [comment]
The installer currently isn't working on Windows. Waiting on a new tag. :+1: https://github.com/laravel/installer/issues/141

**Comment by Bradez** [comment]
This should be fixed now as `v4.0.1` has been tagged.

Run `composer global require laravel/installer` again and it'll work. 👍

**Comment by shahakshay938** [comment]
I think there still some issue as its download the packages it prints the **downdowndowndownloading** and it's color is in red instead of white or green.
![image](https://user-images.githubusercontent.com/36084104/92411233-99f1b680-f164-11ea-8844-77879ab13607.png)
