### ISSUE TITLE
Queued job which's job class doesn't exists, doesn't faill gracefully when being handled by queue worker

### ISSUE THREAD

**Issue by georgeboot** [laravel/framework#34179]
- Laravel Version: 8.x-dev
- PHP Version: 7.4
- Database Driver & Version: MySQL 8
- Runtime: Vapor 7.4

### Description:
When a queue job is dispatched to the queue, and then the job class is removed, the queue handler won't fail the job but keeps trying it indefinitely.

Error:
`
/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php at line 82
method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Jobs\TestJob" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition
`

### Steps To Reproduce:
1. Create a job (eg `App\Jobs\TestJob`) with something like `$this->job->release()` in the `handle` method so it never completes
2. Make sure the job has at least one middleware
3. Dispatch the job
4. Remove the job class from the code base
5. Run the queue worker

### Expected outcome
The job fails and is added to the `failed_jobs` table (or alternatively, the job is just removed)

### Actual outcome
The job errors and will be retried indefinitely

**Comment by themsaid** [comment]
Can't replicate. The job fails correctly with:

```
failed to open stream: No such file or directory at .../vendor/composer/ClassLoader.php:444
```

**Comment by georgeboot** [comment]
@themsaid have you tested on Vapor?

I first thought this only happened with job middleware but it produces the same error without job middleware.

I just deployed a fresh Laravel 7 product to Vapor. (so I can confirm this is already an issue on L7 and not only on L8-dev).

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue
{
    public $tries = 20; // 5 minutes

    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        info('Releasing job again on try '.$this->attempts());
        
        $this->release(15);
    }
}
```

After dispatching this job, I renamed the job to `TestJobRenamed` and deployed again.
As soon as the deployment finished, I see this error being produced every second:
<img width="829" alt="Schermafbeelding 2020-09-08 om 14 21 09" src="https://user-images.githubusercontent.com/884482/92476005-94d14d80-f1de-11ea-939a-358497a10e06.png">
