### ISSUE TITLE
8.0 Non blade view doesn't load (worked in 7.*)

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#34173]
A view (non blade) that's a php file gives error, but worked perfect in 7.* laravel, the error:
```
Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct(), 0 passed in C:\BitNami\wampstack-7.4.7-0\apache2\laravel80up\vendor\facade\ignition\src\IgnitionServiceProvider.php on line 128 and exactly 1 expected 
```
It's called in controller like:
```
        return view('dog/indexadmin')
                ->with('dogs', $dogs)
                ->with('pagelinks', $pagelinks);

// also tried

        return view('/dog/indexadmin')
                ->with('dogs', $dogs)
                ->with('pagelinks', $pagelinks);
```

In view I even tried this:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>hello</title>

    </head>

    <body>
        <?php echo 'hello';
        die;
        ?>
        <div>
        //  more code
```
Got same error.  And ignition seems to show it's error where you can't see actual error.

### Note original name was:

```
indexadmin.php

// changing it to

indexadmin.blade.php it worked
```
All prior versions, the view worked without blade if using php as template language.

**Comment by mfn** [comment]
> vendor\facade\ignition\src\IgnitionServiceProvider.php

It's a problem with ignition, please check their issues

**Comment by jimgwhit** [comment]
@mfn  I am not worried about ignition, my concern is:

* someview.php does not work any more.
* Renaming to someview.blade.php works.

Never had to do this prior to version 8.

**Comment by GrahamCampbell** [comment]
Yep, that seems to be caused by the issue in ignition?

**Comment by mfn** [comment]
> Never had to do this prior to version 8.

It's because the `PhpEngine` template engine was changed in Laravel 8 in a breaking way, requiring all implementors adapting their code.

And this means also Ignition, that's why you get this in your error:
> `Too few arguments to function Illuminate\View\Engines\PhpEngine::__construct(),`

and that's how I know it's a "problem" with Ignition:
> `vendor\facade\ignition\src\IgnitionServiceProvider.php`

**Comment by freekmurze** [comment]
I've just tagged a release on Ignition that solves this. Run composer update to pull it in. Let me know if this fixes the issue for you.
