### ISSUE TITLE
Inline blade component with @if = unexpected endif

### ISSUE THREAD

**Issue by tanthammar** [laravel/framework#34186]
- Laravel Version: 7.27.0
- PHP Version: v7.4.4
- Database Driver & Version: n/a

### Description:
I have an inline blade component where I try to add an `@if @endif `statement in the declaration.

Error:
```
syntax error, unexpected 'endif' (T_ENDIF), expecting end of file
```
### Steps To Reproduce:

Blade inline component:
```blade
@props([
    'tag' => 'div',
    'attr' => []
])
<{{$tag}} @foreach($attr as $key => $value) {{$key}}="{{$value}}" @endforeach {{ $attributes }}>
    {{ $slot }}
</{{$tag}}>
```

This gives the error:
```blade
<x-build-tag :attr="$this->getAttr('root')" @if('foo' == 'foo') data-foo="bar" @endif>Hello</x-build-tag>
```

The the `getAttr('root')` returns this array
```php
'root' => [
    'class' => 'w-full',
],
```

**Comment by RVxLab** [comment]
Can you post what that looks like in the compiled view?

**Comment by driesvints** [comment]
Unfortunately, using directives on components isn't possible at this time. See https://laravel.com/docs/7.x/blade#managing-attributes

![Screenshot 2020-09-08 at 13 15 03](https://user-images.githubusercontent.com/594614/92469604-60a55f00-f1d5-11ea-801a-4c1167034991.png)
