### ISSUE TITLE
Method getColumnListing doesn't work on postgresql using multiple schemas

### ISSUE THREAD

**Issue by slayerbleast** [laravel/framework#34185]
- Laravel Version: 7.27.0
- PHP Version: 7.3.8
- Database Driver & Version: Postgresql 12.3

### Description:

The way of getting all columns of a table:

    $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable())

Doesn't work when the project works with multiple schemas.
Only works when you want to retrieve a table of primary schema defined.

### Steps To Reproduce:

1. By default postgresql should have the primary schema `public`.
2. Create another schema `warehouse`.
3. The .env must define to use `public` schema as default:

		DB_DATABASE=postgres
		DB_SCHEMA=public

4. Create a new migration that creates a new table on `warehouse` schema:

		public function up()
		{
			Schema::create('warehouse.products', function (Blueprint $table) {
				$table->id();
				$table->string('name');
				$table->timestamps();
			});
		}

5. Run the migration.
6. Create this example test:

		public function testBasicTest()
		{
			$columns = [
				'id',
				'name',
				'created_at',
				'updated_at',
			];
			$this->assertEquals($columns, $this->getConnection()->getSchemaBuilder()->getColumnListing('warehouse.products'));
		}

### Expected result
The test should pass.

### Actual result
The test fails.
This line:

    $this->getConnection()->getSchemaBuilder()->getColumnListing('warehouse.products');

returns `[]`

**Comment by FreekVR** [comment]
I believe this is the same issue I'm running into, with MySQL:

The new updates where Laravel is (I believe) using this function to determine what columns can be filled (Post 7.24) breaks when using Hyn Multi-tenancy, in this case, my model has a custom `getTable()` which returns `system.roles` instead of `roles` as the table name, and as long as this is the case, it won't fill any columns like "name" even though we have set  `$guarded = ['id'];` set on the model

**Comment by slayerbleast** [comment]
@FreekVR I am not using any model. The problem is precisely that I'm passing this value you said as a parameter directly and it's not working.

    $this->getConnection()->getSchemaBuilder()->getColumnListing('warehouse.products'); // not working
    $this->getConnection()->getSchemaBuilder()->getColumnListing('products'); // not working
    $this->getConnection()->getSchemaBuilder()->getColumnListing('public.users'); // not working
    $this->getConnection()->getSchemaBuilder()->getColumnListing('users'); // working

**Comment by driesvints** [comment]
We don't support setting the connection name on the table. Use the connection property for that.
