### ISSUE TITLE
8.x routing thows error without Scope Resolution Operator (::)

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#34188]
From 8.* docs:
```
use App\Http\Controllers\UserController;

Route::get('/user', [UserController::class, 'index']);
```

From 7.* docs
```
Route::get('/user', 'UserController@index');
```

Without changing to ::class you get a namespace error.

But this is not mentioned in the upgrade guide. Yes it's in the routing chapter, but being a breaking change shouldn't it be included in upgrade guide.

And has anyone addressed this https://github.com/laravel/ui/issues/138

Why doesn't docs have an issue section.

I did PR, but positive I did it correctly.

**Comment by driesvints** [comment]
There's a pr to the docs open now: https://github.com/laravel/docs/pull/6309
