### ISSUE TITLE
Model replication throws error when using $withCount = ['relation'] in the model

### ISSUE THREAD

**Issue by mehrancodes** [laravel/framework#34192]
- Laravel Version: 5.8.1
- PHP Version: 7.3.19
- Database Driver & Version: Mysql 5.7

### Description:
Just been trying to replicate a model that has the property `$withCount = ['downloads']`, but when I `push()` the new model it tries to insert the `downloads_count` as a column in my new model. I can exclude the `downloads_count` when I do the replication but isn't this something wrong?

### Steps To Reproduce:
// Lesson Model
```php
<?php

class Lesson extends Model
{
    protected $withCount = ['downloads'];
}
```

// When I replicate it, it throws this error.
```php
$lesson->replicate()->push();

//Mysql Error:
SQLSTATE[HY000]: General error: 1 table resources has no column named downloads_count (SQL: insert into "resources" ("lesson_id", "type", "title", "url", "deleted_at", "downloads_count") values (3, external_resource, 'Adipisci et natus cupiditate minima.', https://www.youtube.com/watch?v=bTqVqk7FSmY, ?, 0))
```

But when excluding the `downloads_count` it works fine:
```php
$lesson->replicate(['downloads_count'])->push();

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
