### ISSUE TITLE
[8.x] Non-existent class used in newly deprecated method

### ISSUE THREAD

**Issue by fletch3555** [laravel/framework#34190]
- Laravel Version: 8.x (master branch)
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
`ServiceProvider::loadFactoriesFrom()` is newly marked as deprecated for 8.x (in the [master branch](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/ServiceProvider.php#L237), but not in the [7.x branch](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/ServiceProvider.php#L174)).  This method references `ModelFactory` which is an alias for `Illuminate\Database\Eloquent\Factory`, which has since been moved to the laravel/legacy-factories package.  This class should not be used unless that package is installed as well.  I'm happy to PR a fix, but I would appreciate some guidance from the laravel team.

I also noticed that any references to factories has been removed from the [package development page in the docs](https://laravel.com/docs/8.x/packages).  I assume this is because factories are now full-fledged namespaced classes and can therefore be referenced directly.  I understand the docs are likely not yet complete, so keeping that in mind... Is there any direction for package maintainers to best support both 7.x and 8.x versions?

**Comment by taylorotwell** [comment]
What is your question specifically?

**Comment by fletch3555** [comment]
Hi @taylorotwell, thank you for taking the time to respond.

Apologies if my previous comment wasn't clear.

I guess I'm asking if this was a mistake, a needed improvement to the docs, or "working as-intended".

I don't see anything in the upgrade guide mentioning `ServiceProvider::loadFactoriesFrom()` can no longer be used without the new legacy-factories package.  Because right now, if you do, you'll get an error stating class doesn't exist.  When I see a deprecation warning, I assume it will still work but that I need to work toward something else, but in this case, it would be broken.

Second point was more seeking guidance.  From comments in laravel/legacy-factories#1, I tried a few different approaches, but was unable to maintain support for both laravel 7 and 8.  If my package provides old style factories, I run into the above issue.  If I provide new factory classes, then (assuming they make use of our factories) our users need to use new factory classes as well (defeating the purpose of legacy-factories).  Admittedly, I've gotten a little twisted trying to wrap my head around the many cases here, so apologies if I'm mistaken on any part of this.  But, my question is, how would you recommend best supporting both Laravel 7 and 8 in parallel from the perspective of a package providing factories?

Thank you.

**Comment by taylorotwell** [comment]
Correct, you need to use that package.

If you want to support both 7 and 8. I would make a new major version that supports 8.x while your previous version / branch supports 7.x until people upgrade. Or, have users of your package be required to install laravel/legacy-factories.

**Comment by MajidMohammadian** [comment]
I tested this and it worked

You can add the following code inside the ServiceProvider in the register:

    namespace JobMetric\Setting;
    
    use Illuminate\Database\Eloquent\Factories\Factory;

    public function register(): void
    {
        ...

        Factory::guessFactoryNamesUsing(function (string $modelName) {
            return "\\JobMetric\\Setting\\Factories\\" . class_basename($modelName) . 'Factory';
        });
    }

I put this code in the jobmetric/laravel-setting package
