### ISSUE TITLE
FilesystemAdapter->getLocalUrl() does not urlencode the provided $path

### ISSUE THREAD

**Issue by LukeTowers** [laravel/framework#34199]
- Laravel Version: 6.18.38 (also present in latest 8.x)
- PHP Version: 7.4.9
- Database Driver & Version: N/A

### Description:
The `Illuminate\Filesystem\FilesystemAdapter` `getLocalUrl($path)` method does not urlencode the `$path` argument when returning it meaning that it can provide invalid URLs.

### Steps To Reproduce:
Create a file with a space in its filename `test file.txt` and put it in `/storage/app`. Attempt to get the URL to the file via `Storage::disk('local')->url('test file.txt');`. You will receive `/storage/app/test file.txt`, when you should instead receive `/storage/app/test%20file.txt`.

**Comment by taylorotwell** [comment]
I think it may be best that you simply store them with names that are URL encoded? I'm not sure we can fix this on our end without breaking changes.

**Comment by LukeTowers** [comment]
@taylorotwell what sort of breaking changes can you think of? If people are already bypassing this issue in their own applications by encoding the name before passing it to this method, then you could always just `rawurlencode(rawurldecode($path))` to make sure you don't double encode it. I'm interested in hearing what other cases could cause breaking changes though.

If you do decide to do nothing about it though I would recommend adding a note to the docs about it not guaranteeing a valid URL.

**Comment by taylorotwell** [comment]
Can you make a PR that isn't breaking to show me what you mean?
