### ISSUE TITLE
Parse error when using BusServiceProvider

### ISSUE THREAD

**Issue by huuptag** [laravel/framework#34193]
- Laravel Version: 8.x
- PHP Version: 7.2.19

### Description:
I found an error when using Bus/Queueable trait.
ParseError: syntax error, unexpected ')' in Illuminate\Bus\BusServiceProvider.php at line 51.

### Steps To Reproduce:
Remove the last comma when create new DatabaseBatchRepository.

**Comment by driesvints** [comment]
Laravel 8 doesn't supports PHP 7.2. Please upgrade to PHP 7.3 where this is possible.

**Comment by huuptag** [comment]
thanks @driesvints !
