### ISSUE TITLE
[8.x] Routes can't find controller

### ISSUE THREAD

**Issue by dacoto97** [laravel/framework#34204]
- Laravel Version: 8.0.0
- PHP Version: 7.9.10
- Database Driver & Version: NONE

### Description:

Routes can't find controller:

![image](https://user-images.githubusercontent.com/16915053/92526139-42ffe600-f225-11ea-900b-da74db11aef4.png)

### Steps To Reproduce:

1. Install clean laravel 8.
![image](https://user-images.githubusercontent.com/16915053/92526244-6f1b6700-f225-11ea-890c-eecec15c2ed4.png)
2. Create a controller.
![image](https://user-images.githubusercontent.com/16915053/92526318-8f4b2600-f225-11ea-9ca4-b7b44abb084f.png)
3. Modify the router to load the view from the controller.
![image](https://user-images.githubusercontent.com/16915053/92526340-97a36100-f225-11ea-9ccf-ec5fd2455caf.png)

**Comment by taylorotwell** [comment]
Please consult documentation on how to define routes to controllers: https://laravel.com/docs/8.x/controllers#basic-controllers

**Comment by dacoto97** [comment]
Hi @taylorotwell.
This works with Laravel 7.x, and I have not seen in the documentation anything about this change.
It would be ideal to inform about this in the update guide.
I take this opportunity to thank the work done with laravel.

**Comment by snapey** [comment]
@dacoto97 

Previously controller classes were prefixed in the RouteServiceProvider.  `protected $namespace = 'App\Http\Controllers';` 

This has been removed now.

This, copied from L7 project

    Route::get('/project/create','Project\ProjectController@create');

has to become

    Route::get('/project/create','App\Http\Controllers\Project\ProjectController@create');

or use the new syntax

**Comment by ezkeromar** [comment]
The full answer in this article:
https://www.phppkgs.com/2020/12/solved-laravel-8-cant-find-controller.html

Hope it helps
Cheers
Omar
