### ISSUE TITLE
Version 8 doesn't completely scaffold Auth

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#34207]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 8

### Description: No Login Controller is created and no trait.

From docs:

> Now that you have routes and views setup for the included authentication controllers, you are ready to register and authenticate new users for your application! You may access your application in a browser since the authentication controllers already contain the logic (via their traits) to authenticate existing users and store new users in the database.

### Steps To Reproduce:

Run php artisan jetstream:install livewire

And is laravel/ui deprecated, or will it work with v8 and future versions, nothing in the v8 docs about that? 

Where are the traits the documentation refers to I like to be able to override some methods if possible.

I like to redirect depending on the role, like you could in UI.

**Comment by fylzero** [comment]
@jimgwhit Just as a workaround.  You 100% can use laravel/ui with Laravel 8.  I just upgraded an app using that combo.  The only thing you'll need to do is use the work around for Auth::routes described here:  https://github.com/laravel/ui/issues/138

**Comment by driesvints** [comment]
> And is laravel/ui deprecated, or will it work with v8 and future versions, nothing in the v8 docs about that?

laravel/ui is indeed deprecated. But like @fylzero says you can use a workaround.

Please open this issue on the jetstream repo.

**Comment by mjbanvard** [comment]
> @jimgwhit Just as a workaround. You 100% can use laravel/ui with Laravel 8. I just 
> upgraded an app using that combo. The only thing you'll need to do is use the work
> around for Auth::routes described here: https://github.com/laravel/ui/issues/138

This link leads to a 404. I am having the same issue in a container with Laravel 8.6.* running, and I cannot initiate VUE, because 'ui' is not recognized, not does it show up in 'php artisan list'

**Comment by fylzero** [comment]
@mjbanvard I believe this is no longer an issue.  All of this was happening during a brief period after Jetstream was launched.  Laravel UI has continued support and is no longer officially deprecated.  So if you create a fresh Laravel 8 project and install Laravel UI, everything should be good to go.

**Comment by mjbanvard** [comment]
@fylzero I'm working with a Laravel container, running in Docker on my local machine. When I type 'php artisan ui vue' I receive a message 'Command "ui" is not defined'

**Comment by devcircus** [comment]
Did you composer require laravel/ui?

**Comment by mjbanvard** [comment]
@devcircus Yes, I did. I'm running the Laravel framework 8.61.0
