### ISSUE TITLE
Laravel v8.x tests require PHPUnit ^9.0 - not mentioned in Upgrade Guide

### ISSUE THREAD

**Issue by ry167** [laravel/framework#34208]
- Laravel Version: v8.0.0
- PHP Version: 7.4.9
- Database Driver & Version:not relevant

### Description:

`nunomaduro/collision ^5.0` tells us that `artisan test` depends on PHPUnit ^9.0 which isn't mentioned in the [Upgrade Guide](https://laravel.com/docs/8.x/upgrade). 

This causes tests to fail with error:
```
RuntimeException 

  Running Collision ^5.0 artisan test command requires PHPUnit ^9.0.

  at vendor/nunomaduro/collision/src/Adapters/Laravel/Commands/TestCommand.php:66
     62▕      */
     63▕     public function handle()
     64▕     {
     65▕         if ((int) \PHPUnit\Runner\Version::id()[0] < 9) {
  ➜  66▕             throw new RuntimeException('Running Collision ^5.0 artisan test command requires PHPUnit ^9.0.');
     67▕         }
     68▕ 
     69▕         // @phpstan-ignore-next-line
     70▕         if ((int) \Illuminate\Foundation\Application::VERSION[0] < 8) {

      +14 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

This is very similar to #31718 so an update to the Upgrade Guide is probably all that is needed, with a link to some details on the PHPUnit upgrade: https://phpunit.de/announcements/phpunit-9.html

I did not add PHPUnit to my `composer.json` so I imagine this is an issue that lots of developers upgrading will run into. 

### Steps To Reproduce:

- Start project using Laravel v7.x
- Upgrade to v8.x follow the Upgrade Guide
- Run any tests

**Comment by nunomaduro** [comment]
Collision doesn't require `phpunit:^9.0`. The `test` Artisan command requires `phpunit:^9.0`.

**Comment by ry167** [comment]
@nunomaduro Updated original issue slightly to reflect that

**Comment by driesvints** [comment]
You own this code. Just change it to PHPUnit 8.
