### ISSUE TITLE
Http Client SendAsync

### ISSUE THREAD

**Issue by shmuelgutman** [laravel/framework#34216]
I'm using the `Illuminate\Support\Facades\Http` wrapper and I love it.
I wonder if there is an option to utilize the Guzzle Async feature so I can do `Http::sendAsync(...)` and get the Promise as in http://docs.guzzlephp.org/en/stable/quickstart.html#async-requests

I know I can use the Guzzle library directly, but I like the Laravel's pattern with this `PendingRequest` and `this` chaining.

I can also work on a PR for this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
