### ISSUE TITLE
error when i execute an artisan migrate command: syntax error, unexpected ')'

### ISSUE THREAD

**Issue by dfloresc** [laravel/framework#34213]
https://github.com/laravel/framework/blob/5bf30a553a1478ae8d8b3f6791286c7936a19ed5/src/Illuminate/Bus/BusServiceProvider.php#L50

There is an extra comma at final of this line, i only remove it and i tried again and this work for me.

**Comment by Krisell** [comment]
Support for trailing commas in function calls was added in php 7.3, which is required by Laravel 8.
