### ISSUE TITLE
Running php artisan down with message option results in : The "--message" option does not exist.

### ISSUE THREAD

**Issue by fylzero** [laravel/framework#34211]
- Laravel Version: 8.0.0
- PHP Version: 7.4.9
- Database Driver & Version: MySql 5.7.29

### Description:
Trying to run `php artisan down --message="Deploying new code"` and it says `The "--message" option does not exist.`. I know some things have changed with this command that I am still figuring out but at this time the option is still mentioned as being available in the Laravel 8 docs here:  https://laravel.com/docs/8.x/configuration#maintenance-mode

### Steps To Reproduce:
- Run `php artisan down --message="Some message"`
- Results in error: `The "--message" option does not exist.`

**Comment by samloft** [comment]
Just to confirm same issue here, didn't belive I would have any issues with this as the 8* docs show the --message command.

I'm currently setting maintenance mode via a SQL table with the message passed by the admin from one site, so this now fails.

Can we have confirmation if this is ment to be removed and we need to find workarounds, or was left in the docs by mistake (And not mentioned in the upgrade guide)

**Comment by taylorotwell** [comment]
Will update the docs.

**Comment by FoksVHox** [comment]
> Will update the docs.

Was there a reason to that it was removed @taylorotwell ?

**Comment by fylzero** [comment]
I just re-watched his Laracon talk for the answer.  You can now use
`--render="bladeviewhere"`

Some things changed with this because I think there were issues with the
original down command not working in certain situations.

**Comment by fylzero** [comment]
> > Will update the docs.
> 
> Was there a reason to that it was removed @taylorotwell ?

I just re-watched his Laracon talk for the answer.  You can now use `--render="bladeviewhere"`


Some things changed with this because I think there were issues with the original down command not working in certain situations.

**Comment by fylzero** [comment]
@taylorotwell It might be worth adding that the --message option is removed in the Upgrade Guide as well.  Just a thought.
