### ISSUE TITLE
barry en dries

### ISSUE THREAD

**Issue by 3robi-vollebregt** [laravel/framework#34215]
In ProviderRepository.php line 208:
                                                     
  Class 'Barryvdh\DomPDF\ServiceProvider' not found

**Comment by driesvints** [comment]
@3robi-vollebregt this isn't the dompdf issue tracker. Open up an issue here: https://github.com/barryvdh/laravel-dompdf

**Comment by 3robi-vollebregt** [comment]
we fixed already sorry thanks maatew
