### ISSUE TITLE
Upgrading to Laravel 8 from 7: Invokable controllers error out

### ISSUE THREAD

**Issue by fylzero** [laravel/framework#34210]
- Laravel Version: 8.0.0
- PHP Version: 7.4.9
- Database Driver & Version: MySql 5.7.29

### Description:
Upgrading Laravel app from 7.26.1 to 8.0.0.  I watched the Laracon talk where Taylor said routes wouldn't need to be updated so long as the $namespace param in RouteServiceProvider was left alone.  This seems not to include invokable controller references.  Not sure if that was intended.  I'm converting my routes to the new syntax but figured I'd mention it.  I've already had this verified by another dev on a fresh project as well.

### Steps To Reproduce:
- Install Laravel 8
- Add `protected $namespace = 'App\Http\Controllers';` to the `app/Providers/RouteServiceProvider.php` file.
- Create a controller with am __invoke() method.
- Add an invokable reference route using the old syntax `Route::get('testing', 'ControllerNameHere');`
- php artisan list breaks, can't run composer update, route will not work.

**Comment by ry167** [comment]
I cannot reproduce this - I have an invokable controller, matching `$namespace` and can run `php artisan list` and view the Controller without issue. 

What error are you seeing?

**Comment by fylzero** [comment]
@ry167 Silly question, are you trying this on Laravel 8?

```
UnexpectedValueException
Invalid route action: [HomeController].

  at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:91
     88▕     protected static function makeInvokable($action)
     89▕     {
     90▕         if (! method_exists($action, 'invoke')) {
  ➜  91▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     92▕         }
     93▕
     94▕         return $action.'@invoke';
     95▕     }

  • HomeController is not invokable: The controller class HomeController is not invokable. Did you forget to add the __invoke method or is the controller's method missing in your routes file?

My route Route::get('/', 'HomeController');

The top of my home controller...

class HomeController extends Controller
{
    public function __invoke(Request $request)
    {

**Comment by ry167** [comment]
Yep: 
```
$ php artisan --version
Laravel Framework 8.0.0
```

Does your `HomeController` actually exist within `namespace App\Http\Controllers;`? If that is the top of your file it would seem not? 

Here is a working controller as an example:
```
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndexController extends Controller{
    public function __invoke(Request $request){
        return view('welcome');
    }
}
```

**Comment by fylzero** [comment]
@ry167 This was an upgrade so nothing is broken in the original code and I can verify that switching the syntax "soved" the problem.  Also I've had this verified by another developer on a fresh project.

**Comment by ry167** [comment]
Yep: `Route::get('/', 'IndexController');`. I have a mix of invokable, resource and normal controllers.

Not much else I can help with here then sorry - will have to wait for someone else to come in

**Comment by fylzero** [comment]
@ry167 100% sure, just verified this again with these steps...

laravel new laravel8
composer install
npm install
php artisan make:controller TestController
Added code to controller:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function __invoke()
    {
        return true;
    }
}
```

Added route:  `Route::get('test', 'TestController');`

**Comment by ry167** [comment]
Ah, Laravel 7.x has this (note line 2) in `RouteServiceProvider`:
```
Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
```
The namespace is added to the Route group for 7.x and is not in Laravel 8.x. See here for 7.x: https://github.com/laravel/laravel/blob/7.x/app/Providers/RouteServiceProvider.php

Migrated applications should not encounter this issue.

`protected $namespace` on `ServiceProvider` probably doesn't do anything within the `RouteServiceProvider` so you will need to use it. If you add `->namespace($this->namespace)` it should resolve your issues.

Commit that broke it is here: https://github.com/laravel/laravel/commit/58a98efb86c0c0a819e333a52eccf2a7de652f15#diff-b467cc786635bd6945b17726282f1c64

Bug is valid, thankfully an easy fix - nice work

**Comment by fylzero** [comment]
@ry167 Excellent work!  Yeah, I migrate applications in a unique way.  I spin up a fresh app, git init then overlay so I can diff out everything that has changed.  This tends to get rid of old garbage left behind.  So yep, this one is on me.  I missed that line, you're spot on.  Thanks!

**Comment by ry167** [comment]
Might still be worth making a change in `laravel/laravel` for this? By default invokable controllers won't work it seems and the docs don't mention anything on it

**Comment by fylzero** [comment]
@ry167 By default the Controller@method syntax doesn't work either.  It was a conscious choice they made to move it over.  Taylor Otwell explained it at Laracon Online but said upgraded apps shouldn't have a problem and in most cases they won't.  This was just me missing the thing.  The upgrade guide stays silent on it because it isn't really a problem and the new documentation only references the new syntax.  https://laravel.com/docs/8.x/routing

Sounds like they've got all the bases covered on it.

**Comment by snapey** [comment]
Apart from users with the new framework following older tutorials unfortunately.  Its a breaking change for anyone moving a project to Laravel 8 (as opposed to upgrade) and is not mentioned in the docs.

This, copied from L7 project

    Route::get('/project/create','Project\ProjectController@create');

has to become

    Route::get('/project/create','App\Http\Controllers\Project\ProjectController@create');

or use the new syntax

(and not just for invokable controllers)

**Comment by lagbox** [comment]
It would seem that setting the `$namespace` property is only for generating URLs to actions. The documentation does not really make that obvious though.

**Comment by henryavila** [comment]
I had the same problem and it's not clear in upgrade docs.

In resume, to change Routes to sintaxe `Route::get('/profile', ShowProfileController::class)` 
you need to **remove** the line `    protected $namespace = 'App\Http\Controllers';` in `RouteServiceProvider.php` file
