### ISSUE TITLE
[8.x] Can't wire:model.lazy on dynamic components

### ISSUE THREAD

**Issue by stancl** [laravel/framework#34222]
- Laravel Version: 8.0.0
- PHP Version: 7.4
- Database Driver & Version: none

### Description:

Using `wire:model` (or presumably attributes with `:` in general) on `<x-dynamic-component>` doesn't work. It interprets the `:` incorrectly.

### Steps To Reproduce:

```html
<html>
<head>
<body>
    <x-dynamic-component :component="$foo" wire:model="bar" />
</body>
</head>
```

Shows: https://flareapp.io/share/17WGpn7X#F51

It tries to compile it as:
```php
<?php $component = $__env->getContainer()->make(Illuminate\View\AnonymousComponent::class, ['view' => 'components.foo','data' => ['wire:model' => $wire:model]]); ?>
```

**Comment by stancl** [comment]
The issue seems to be here: https://github.com/laravel/framework/blob/43bea00fd27c76c01fd009e46725a54885f4d2a5/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php#L154

It tries to set a value for `wire:model` - by making a variable called `$wire:model`.

In my case:
```php
<?php foreach (array_filter((['action','value','wire:model']), 'is_string', ARRAY_FILTER_USE_KEY) as $__key => $__value) {
    $$__key = $$__key ?? $__value;
} ?>
```

`:` is not a valid character for PHP variables.

I have no clue how to solve this.

**Comment by stancl** [comment]
`:` can be used for attributes in case of non-dynamic components though. I would expect the `CompilesComponents` logic to be executed on all components (to compile them) but seems like normal components just work?

For example, Caleb's Surge uses:
```html
<x-input.file-upload wire:model="newAvatar" id="photo">
```

**Comment by ryangjchandler** [comment]
@stancl in your situation, a temporary fix might be to use `:wire:model="'bar'"` instead, where you're just binding it to a plain old string.

**Comment by stancl** [comment]
```html
<x-dynamic-component :component="$foo" :wire:model="'foo'" />
```

doesn't work

and neither does
```html
<x-dynamic-component :component="$foo" wire:model="'foo'" />
```

**Comment by ryangjchandler** [comment]
It's also worth noting here that `wire:model` and other attributes with colons in their name work fine when using class-based components, but if the component you're trying to load is anonymous, that's where the problems occur.

**Comment by taylorotwell** [comment]
@ryangjchandler it works fine for class based dynamic components?

**Comment by ryangjchandler** [comment]
@taylorotwell - if the component that you are trying to load is a class-based component, then yeah it works fine. It only seems to be a problem when `:component="$component"` is pointing to an anonymous component.

**Comment by taylorotwell** [comment]
Fixed in upcoming patch release.

**Comment by stancl** [comment]
Awesome, thanks!

**Comment by stancl** [comment]
@taylorotwell Seems like `wire:model.lazy` is broken. This is the compiled code:

```php
'data' => ['action' => $action,'wire:model.lazy' => $wireModel.lazy,'type' => $type]
```

**Comment by stancl** [comment]
I see that you basically turned `:` into spaces for the `camelCase()` call in https://github.com/laravel/framework/commit/4b1e317c7aec22c2767766bb8b84e059fe4e0802#diff-cbf844e5c539f80da76550a99eacf4ba

I guess the fix for `.` will be the same? Or maybe replace `.lazy` with `_lazy` to have different replace characters for `:` and `.`?

**Comment by stancl** [comment]
FWIW if you agree with me on the `.lazy` -> `_lazy` variant, I'd gladly submit a PR with tests and everything - just like the commit I linked.

**Comment by stancl** [comment]
And again, this works with class-based components. Just like #34346 

@taylorotwell If this stuff only happens when using anonymous component, I'm thinking if it wouldn't be better to change the logic of DynamicComponent.

If it generated & registered a **component class**, I think all of these problems would go away?

If the constructor would be empty (i.e. doesn't accept any props), everything would be passed via the attribute bag, and then the `@props()` call in the component would pop those values out and assign variables — so AFAIK it would work flawlessly.

**Comment by taylorotwell** [comment]
@stancl yeah I think it will be a similar change to the `:` change.

**Comment by taylorotwell** [comment]
Pushing a patch.

**Comment by stancl** [comment]
Thank you.
