### ISSUE TITLE
php artisan serve can't bind to any port

### ISSUE THREAD

**Issue by vitorsemeano** [laravel/framework#34229]
- Laravel Version: 8.0.1
- PHP Version: 7.4.10
- OS: Windows 10
- Database Driver & Version: no database needed

### Description:

After upgrading to laravel 8, and running the command php artisan serve, it responds with an error recursively, like so:

![image](https://user-images.githubusercontent.com/4042283/92616028-a89bb300-f2b5-11ea-9c90-5afd2e500da7.png)

This behavior does not happen if i change php version to 7.4.5 or switch to laravel 7.x.

### Steps To Reproduce:

1. have a laravel project started up with version 8.x
2. make sure you have the most recent stable php version installed (at time of writing 7.4.10)
3. run php artisan serve
4. see that the command can't bind itself to any port

As additional note, i debugged the generated command (running php artisan serve), and copy paste it directly in the command line and it worked, without returning any error.

If you need any more info, just ask.

Thanks

**Comment by driesvints** [comment]
We don't use windows ourselves so feel free to send in a PR which fixes this on Windows.

**Comment by AegirLeet** [comment]
Can't reproduce this. Might be something on your machine interfering.

**Comment by vitorsemeano** [comment]
Hi, thanks for your feedback.

I managed to resolve this issue. Not quite sure what as the cause, but it was related with something not right in php.ini.

So what i did was use the standard php.ini-development (that comes with a pre built php), and add whats missing in the file and should work. In any doubt try only renaming php.ini-development to php.ini without modifying its contents.

**Comment by jonboc** [comment]
The one line I needed to change in my php.ini to fix this problem was
`variables_order = "EGPCS"`
to
`variables_order = "GPCS"`

**Comment by gustaveco** [comment]
> Something to do with the Env variable. No ideia how this affects the core functionality of php built in server to this degree.

It's in the 8^ laravel upgrade. Becaouse the server if one runn it directly works fine:

```
php -S 127.0.0.1:8000  -t public/ server.php
```
and in Laravel 7 `artisan serve` works without problems (windows 10, php 7.4.6).

**Comment by Devang142** [comment]
For me, it was silly mistake. I have installed php in new machine but php.ini was missing. So, I have created php.ini file from php.ini-production file and then php artisan serve command worked fine as expected.

**Comment by isharainduranga** [comment]
php.ini was missing .Check whether your composer has installed.

**Comment by amirazad1** [comment]
After upgrading php7 to php8 for XAMPP,I receive this error.re-creating php.ini from php.ini-production works for me.

**Comment by Galaxy0419** [comment]
Hi guys, I created a merge request https://github.com/laravel/framework/pull/40819 to fix the issue.  Could you try it out to see if it's working?

**Comment by omniaSayed** [comment]
> The one line I needed to change in my php.ini to fix this problem was `variables_order = "EGPCS"` to `variables_order = "GPCS"`

i have been with this problem for days and your solution worked thank

**Comment by Afer13** [comment]
injimjin ihkhh uhihkiuhhhu

**Comment by niu-grandpa** [comment]
> The one line I needed to change in my php.ini to fix this problem was `variables_order = "EGPCS"` to `variables_order = "GPCS"`

Thanks！This is a very good

**Comment by dhurbamis** [comment]
Yes, it was php.ini

change below
variables_order = "EGPCS"
to
variables_order = "GPCS"

**Comment by MiN6JI** [comment]
```
variables_order = "EGPCS"
to
variables_order = "GPCS" 
```

If you are using laravel herd and facing same issue and can't find the php.ini just right click the herd icon from the taskbar and open the  configuration files you will see all your php version folders, click onto the one of the folder as per your configuration of php and search for php.ini and make the above changes.

**Comment by kamasuPaul** [comment]
In case anyone using PVM on windows comes here looking: I installed a new version of PHP using PVM, but it didn't come with a php.ini file. That was causing the issue. To fix it, I just had to add a php.ini file.

**Comment by scrucher** [comment]
if you're using windows open your powershell and type 
`php --ini`
that comand will provide the path to your php.ini file, then go to your laravel app  click on  vendor => laravel => sail => runtime then choose which php version instaed on your machine  copy the php.ini file and post it to the initial php.ini file that will be able to solve the issue on windows OS 
![image](https://github.com/user-attachments/assets/e2b5063b-ede5-43f6-a826-aeaa5165151e)
![image](https://github.com/user-attachments/assets/f4dc58a4-21f5-4435-b28c-73a7586eb5ef)
![image](https://github.com/user-attachments/assets/644e9878-e001-4908-b9ed-7461a2208f03)

**Comment by imantarmizi** [comment]
For windows PowerShell,

PS D:\xampp\htdocs\testing-project-1> php artisan serve
  Failed to listen on 127.0.0.1:8000 (reason: ?)
  Failed to listen on 127.0.0.1:8001 (reason: ?)
  Failed to listen on 127.0.0.1:8002 (reason: ?)
  Failed to listen on 127.0.0.1:8003 (reason: ?)
  Failed to listen on 127.0.0.1:8004 (reason: ?)
  Failed to listen on 127.0.0.1:8005 (reason: ?)
  Failed to listen on 127.0.0.1:8006 (reason: ?)
  Failed to listen on 127.0.0.1:8007 (reason: ?)
  Failed to listen on 127.0.0.1:8008 (reason: ?)
  Failed to listen on 127.0.0.1:8009 (reason: ?)
  Failed to listen on 127.0.0.1:8010 (reason: ?)
PS D:\xampp\htdocs\testing-project-1> php --ini
Configuration File (php.ini) Path:
Loaded Configuration File:         C:\Users\User\.config\herd\bin\php83\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

Step 1:   Copy this = C:\Users\User\.config\herd\bin\php83\php.ini 
Step 2: Go to File Explorer on your local hardware
Step 3: Paste the copied path
Step 4: Search "variables_order"
Step 5: Change "EGPCS" to "GPCS"
Step 6: php artisan serve 

This worked for me in 2024 with php version 8.3.11

**Comment by hackvival** [comment]
> si señor, esta es la solucion, muy descriptivo, casi que no encuentro algo funcional, hay varios archivos php.ini en el proyecto Thank you so much.
![image](https://private-user-images.githubusercontent.com/57249962/384177244-e2b5063b-ede5-43f6-a826-aeaa5165151e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc5NTgsIm5iZiI6MTczMTY0NzY1OCwicGF0aCI6Ii81NzI0OTk2Mi8zODQxNzcyNDQtZTJiNTA2M2ItZWRlNS00M2Y2LWE4MjYtYWVhYTUxNjUxNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA1MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTE2NTk1NTZjYWYzYzI1OTdiZmYzNzFhN2M4Y2M1NTliOWEwYTc2NjJmZTk0MjdiZmFmNTcyZDU5YmExMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZOs8z7TE-AsDI4vRls2r0UGqfK2cRJQbcfB8vfOfZ9M) ![image](https://private-user-images.githubusercontent.com/57249962/384177334-f4dc58a4-21f5-4435-b28c-73a7586eb5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc5NTgsIm5iZiI6MTczMTY0NzY1OCwicGF0aCI6Ii81NzI0OTk2Mi8zODQxNzczMzQtZjRkYzU4YTQtMjFmNS00NDM1LWIyOGMtNzNhNzU4NmViNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA1MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmEzNTE3MzlmYzljZjhiZjU1ZWViMjQ3OTgzZDM3NWNhMzgzZTRmODNlM2RlNzM4NzVhOGI3YzljOGZhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yc9mCm0hTEQC5hLr_0oCvTQG0hfR0B7OYd-O-hIspMM) ![image](https://private-user-images.githubusercontent.com/57249962/384177384-644e9878-e001-4908-b9ed-7461a2208f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc5NTgsIm5iZiI6MTczMTY0NzY1OCwicGF0aCI6Ii81NzI0OTk2Mi8zODQxNzczODQtNjQ0ZTk4NzgtZTAwMS00OTA4LWI5ZWQtNzQ2MWEyMjA4ZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA1MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNGQwZjgwODNiMDRlYWI0MTQxNWI2YjhjOGJlMTVhNDQ4MDVjZTQ0NmM2NGI2ZDQzMmRkNDZmN2VhOTBkZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bFrcsLKR9jAifTABtANtl17kfMZSiBZ8VoL9TMMc9Jw)

**Comment by NelsonTH56** [comment]
Currently encountering this same issue. variable_order='GPCS' did not work for me. Is anyone else still having this problem?

**Comment by Anaphylaxis** [comment]
> Currently encountering this same issue. variable_order='GPCS' did not work for me. Is anyone else still having this problem?

This did work for me, make sure you're using variable**s**_order (note the plurality of variable)

**Comment by Abdirahman5863** [comment]
> if you're using windows open your powershell and type `php --ini` that comand will provide the path to your php.ini file, then go to your laravel app click on vendor => laravel => sail => runtime then choose which php version instaed on your machine copy the php.ini file and post it to the initial php.ini file that will be able to solve the issue on windows OS ![image](https://github.com/user-attachments/assets/e2b5063b-ede5-43f6-a826-aeaa5165151e) ![image](https://github.com/user-attachments/assets/f4dc58a4-21f5-4435-b28c-73a7586eb5ef) ![image](https://github.com/user-attachments/assets/644e9878-e001-4908-b9ed-7461a2208f03)

thanks it worked for me
