### ISSUE TITLE
[8.x] Wrong factory namespace for models with "custom" namespace

### ISSUE THREAD

**Issue by SamuelNitsche** [laravel/framework#34221]
- Laravel Version: 8.0.0
- PHP Version: 7.4.3
- Database Driver & Version: Mysql 5.7

### Description:
I have a user model in the `App\Domain\Auth\Models` namespace. When I create a factory using the command `php artisan make:factory UserFactory --model="App\Domain\Auth\Models\User"` the factory is created in the `Database\Factories` namespace. When I call the `User::factory()` method, I get the following error

```
 Error

  Class 'Database\Factories\Domain\Auth\Models\UserFactory' not found

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:623
    619▕     public static function factoryForModel(string $modelName)
    620▕     {
    621▕         $factory = static::resolveFactoryName($modelName);
    622▕
  ➜ 623▕         return $factory::new();
    624▕     }
    625▕
    626▕     /**
    627▕      * Specify the callback that should be invoked to guess factory names based on dynamic relationship names.

      +1 vendor frames
  2   tests/Unit/TeamTest.php:17
      App\Domain\Auth\Models\User::factory()
```

### Steps To Reproduce:
1. Move the `User` Model to a namespace other than `App` or `App\Models`
2. Create a factory for the model
3. Call `User::factory()`

**Comment by taylorotwell** [comment]
If your models don't follow the convention you can use "UserFactory::new" as noted in the documentation.

**Comment by SamuelNitsche** [comment]
Sorry for wasting your time. I must have missed that. 😞
