### ISSUE TITLE
Factory not found when model inside subdirectory from models directory

### ISSUE THREAD

**Issue by hsmfawaz** [laravel/framework#34238]
- Laravel Version: 8.0
- PHP Version: 7.3.21
- Database Driver & Version:Mysql

### Description:
When generating a model inside sub-directory from the model directory Example 
`App\Models\Administration\Admin`  with factory
it will throw 
`Class 'Database\Factories\Administration\AdminFactory' not found`
when i tried to create a new model using the new factory system

### solution
the artisan argument `-f` for the command `php artisan make:model` should match the same namespace as the model

### Steps To Reproduce:
1- `php artisan make:model Administration/Admin -mf`
2- Fill the definition method for the generated factory
3- `Admin::factory(1)->create();`

**Comment by taylorotwell** [comment]
Works for me. Make sure your factories namespace is correct.

**Comment by hsmfawaz** [comment]
> 
> 
> Works for me. Make sure your factories namespace is correct.

Yes the problem is with the generated factories namespace 
it should be generated as
`Database\Factories\Administration\AdminFactory`
but it will be generated as
`Database\Factories\AdminFactory` and it will throw exception because the model namespace is `App\Models\Administration\Admin`
