### ISSUE TITLE
`php artisan schema:dump` throws an error on Windows

### ISSUE THREAD

**Issue by ahaseeb04** [laravel/framework#34232]
- Laravel Version: 8.0.0
- PHP Version: 7.4.9
- Database Driver & Version: mysql Ver 15.1 Distrib 10.4.14-MariaDB

![image](https://user-images.githubusercontent.com/64300504/92622501-14205900-f293-11ea-9a41-87af48f2a7e9.png)

**Comment by driesvints** [comment]
There's a PR open that'll fix this shortly: https://github.com/laravel/framework/pull/34233
