### ISSUE TITLE
Comma at the end on the method is invalid

### ISSUE THREAD

**Issue by keepanitreel** [laravel/framework#34242]
https://github.com/laravel/framework/blob/a4c365f9a964f1d9346a662b426476dc1bffc660/src/Illuminate/Bus/BusServiceProvider.php#L50

**Comment by keepanitreel** [comment]
Error is thrown when booting app

require '/vendor/autoload.php';
$app = require('/bootstrap/app.php');
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

---
  
ParseError 

  syntax error, unexpected ')'

  at /vendor/laravel/framework/src/Illuminate/Bus/BusServiceProvider.php:51
     47▕             return new DatabaseBatchRepository(
     48▕                 $app->make(BatchFactory::class),
     49▕                 $app->make('db')->connection(config('queue.batching.database')),
     50▕                 config('queue.batching.table', 'job_batches'),
  ➜  51▕             );
     52▕         });
     53▕     }
     54▕ 
     55▕     /**

**Comment by X-Coder264** [comment]
This is valid syntax in PHP 7.3 which is the minimum supported version for Laravel 8.

https://wiki.php.net/rfc/trailing-comma-function-calls

Make sure that your PHP-FPM is running PHP 7.3+.

**Comment by keepanitreel** [comment]
Thanks @X-Coder264 i'm dumb...was running my test in 7.2
