### ISSUE TITLE
seeder  does't work correctly if I specify --class=... option

### ISSUE THREAD

**Issue by hikarine3** [laravel/framework#34243]
- Laravel Version: 8.0.0
- PHP Version: 7.4.9
- Database Driver & Version: pgsql&12

### Description:
After upgrading to Laravel 8 from latest Laravel 7,
Seeder doesn't work if I specify --class=.. option.
Without specifying --class, 
php artisan db:seed
can run.

### Steps To Reproduce:
```
php artisan make:seeder AdditionalJobAttrSeeder;
php artisan db:seed --class=AdditionalJobAttrSeeder;
```

```
In Container.php line 811:                                                                           
  Target class [Database\Seeders\AdditionalJobAttrSeeder] does not exist.  
In Container.php line 809:                                                                 
  Class Database\Seeders\AdditionalJobAttrSeeder does not exist  
```
                                                                 
I could resolve this problem by editing
vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php 

by commenting out
```
        if (strpos($class, '\\') === false) {
        //    $class = 'Database\\Seeders\\'.$class;
        }
```
which means I can resolve the issue by typing
```
php artisan db:seed --class=\\AdditionalJobAttrSeeder;
```
even if I don't edit the file but this is different behavior from official document and previous behavior.

**Comment by hikarine3** [comment]
So actually
https://github.com/laravel/framework/commit/cadad245ff1d5e294ef6d3f312d66dc63f728619
brought this bug.

**Comment by driesvints** [comment]
Did you add the new namespaces? https://github.com/laravel/laravel/blob/master/database/seeders/DatabaseSeeder.php#L3
And register them in your composer.json? https://github.com/laravel/laravel/blob/master/composer.json#L39
And ran `composer dump`?

**Comment by hikarine3** [comment]
Thanks for you comment.

compser.json and composer dump were done.
but 
> Did you add the new namespaces?
Seed Class was created in Laravel 7.25 by "php artisan make:seeder ..." and at the time it doesn't have the namespace but it worked.
But I noticed that if I create seed class in 8.0.0 from zero using "php artisan make:seeder TestSeeder", it now adds namespace.

So the problem is SeederClass created by lalavel 7 lost compatibility with Laravel 8 without changing the code if we specify --class=... option.

If it is described in https://laravel.com/docs/8.x/upgrade as compatibility problem, it would be better.

**Comment by xseguib** [comment]
Same problem here and that's how I fixed:

- Update composer.json and add namespaces to seeders as mentioned in https://github.com/laravel/framework/issues/34243#issuecomment-690094980

- Rename database/seed directory to database/seeders.
- composer dump

As hikarine3 said would be nice to have this compatibility issue mentioned in the upgrade guide.


Thanks!

**Comment by driesvints** [comment]
Thanks. I've sent in a PR here: https://github.com/laravel/docs/pull/6339

**Comment by vladislavtkachenko** [comment]
I have derictories into "seeders". If i write psr-4 namespase for folder, - error target class [Database\Seeders\SafeSeeder] does not exist

**Comment by xseguib** [comment]
Your namespace should be Database\Seeders;

**Comment by hikarine3** [comment]
If I am correct, 
php artisan make:seeder TestSeeder
will create the file under
 database/seeds
yet, so writing
            "Database\\Seeders\\": "database/seeders/"
is not so good idea, I am afraid.

**Comment by xseguib** [comment]
Hello,

I executed(With Laravel 8.0.3) php artisan make:seeder TestSeeder and it created the file under database/seeders with the namespace Database\Seeders

so it's working fine for me :)

**Comment by hikarine3** [comment]
Hmm, then
```
vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeederMakeCommand.php:        if (is_dir($this->laravel->databasePath().'/seeds')) {
```
affected the difference of behavior.
So if we remove seeds directory, I think the behavior of creation of class will change like you said.

**Comment by xseguib** [comment]
Yeah, I have assumed you followed my steps form here https://github.com/laravel/framework/issues/34243#issuecomment-690112896 😅 

I haven't tried, but maybe you can change the default seeder stub and put the old seeds path in the composer.json, so then you don't need to change the directory name ( I didn't tested this!)

**Comment by hikarine3** [comment]
Either can be O.K but changing like you would be better considering it is default location in Laravel 8 though we don't see change if we haven't renamed database/seeds directory.

**Comment by ekosynth** [comment]
I'm using Laravel 8.6.0, created a seeder, it includes the namespaces by default, and the files are put in the database/seeders directory, but still cant find my seeder:

```
   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [CoursesTableSeeder] does not exist.

```

**Comment by razlupercio** [comment]
sorry to zombify this thread, but I have followed the steps indicated on #34243

**Comment by Briareos17** [comment]
It still not working, Laravel 8.10.0, checked everything discibed in this thread

**Comment by mikebranderhorst** [comment]
1. composer.json
```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
```
2. rename directory database/seeds/ to database/seeders/
3. add namespace to every file in directory database/seeders/
```
<?php

namespace Database\Seeders;

```
For sub directories
```
<?php

namespace Database\Seeders\SubDirectoryName;

```
4. change string to class in DatabaseSeeder.php
(I needed this step to get is working for Lumen 8.2)
```
$this->call(CustomSeeder::class);
```
For multiple
```
$this->call([
    Custom1Seeder::class,
    Custom2Seeder::class,
    Custom3Seeder::class,
]);
```
5. composer dump

**Comment by Briareos17** [comment]
It's working, thx.
