### ISSUE TITLE
Attempt method in class TokenGuard

### ISSUE THREAD

**Issue by izshreyansh** [laravel/framework#34246]
- Laravel Version: 7.27.0
- PHP Version: 7.3.13
- Database Driver & Version: Mysql 5.7.28

### Description:
There's isn't an `attempt` method on `Illuminate\Auth\TokenGuard`, Therefore we have to have a parallel auth guard in `\config\auth.php` for each driver `session`, `token`. In-order to authenticate a user with `session` & then creating a `token` for the user.

I'll explain with some code.

In `config\auth.php`

```
'web' => [
    'driver' => 'session',
    'provider' => 'users',
],

'api' => [
    'driver' => 'token',
    'provider' => 'users',
    'hash' => false,
],
```

```
if (! $token = auth()->guard('web')->attempt($credentials)) {
    return response()->json(['error' => 'Unauthorized'], 401);
}

$token = auth()
    ->guard('web')
    ->user()
    ->createToken( 'token-name');
```

If only there was an `attempt` method on `Illuminate\Auth\TokenGuard` so we could do something like following:

```
if (! $token = auth()->guard('api')->attempt($credentials)) {
    return response()->json(['error' => 'Unauthorized'], 401);
}

$token = auth()
    ->guard('api')
    ->user()
    ->createToken( 'token-name');
```

#### Why?

This i'm thinking for the scenario where there's isn't any web app, There's just Laravel backend running so we can skip declaring guard for a session driver & we don't have to 

```
    'guards' => [

         'api' => [
             'driver' => 'token',
             'provider' => 'users',
             'hash' => false,
        ],
    ],
```

PS: If this is dumb, I'm honestly sorry for taking up your time.

**Comment by driesvints** [comment]
Sounds like a feature request. Feel free to pr something.
