### ISSUE TITLE
Redis cache driver unserialize notice

### ISSUE THREAD

**Issue by dododedodonl** [laravel/framework#34250]
- Laravel Version: 7.28.1
- PHP Version: 7.4.9
- Redis Version: `redis-server 5:5.0.3-4+deb10u2`
- Redis Driver: `php-redis 5.3.1+4.3.0-1+0~20200708.25+debian10~1.gbp800f71`

`REDIS_CLIENT=phpredis`

### Description:
When using redis as cache driver, locks don't behave the same as with for example the database driver, and throws an unserialize notice. Without locks, is works as expected.

### Steps To Reproduce:
Using `CACHE_DRIVER=database`:
```php
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Cache;
$key = 'test_'.Str::uuid(); // eg. "test_401b4b8c-e9ab-49b9-9a59-de6a408ad49e"
$lock = Cache::lock($key, 20); // instance of Illuminate\Cache\DatabaseLock

$lock->get(); // returns true
$value = Cache::pull($key, -1); // key does not exist yet, -1 returned as expected
$lock->release(); // returns true
```

Using `CACHE_DRIVER=redis`:
```php
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Cache;
$key = 'test_'.Str::uuid(); // eg. "test_86486733-0a55-4ef5-af54-ae0c753305fb"
$lock = Cache::lock($key, 20); // instance of Illuminate\Cache\RedisLock

$lock->get(); // returns true
$value = Cache::pull($key, -1); // returns false and throws a notice
// PHP Notice:  unserialize(): Error at offset 0 of 16 bytes in vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php on line 306
$lock->release(); // returns false,
```

However, this does work, but returns false when releasing the lock, which is not the case for the database driver
Using `CACHE_DRIVER=redis`:
```php
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Cache;
$key = 'test_'.Str::uuid(); // eg. "test_86486733-0a55-4ef5-af54-ae0c753305fb"
$lock = Cache::lock($key, 20); // instance of Illuminate\Cache\RedisLock

$lock->get(); // returns true
Cache::put($key, -1); // returns true
$value = Cache::pull($key, -1); // returns "-1"
$lock->release(); // still returns false ?
```

**Comment by driesvints** [comment]
Don't have time at to dive into this but appreciating any help here.

**Comment by taylorotwell** [comment]
I guess I'm confused. Why are you overwriting the value of the cache lock key manually? That is causing problems.

**Comment by dododedodonl** [comment]
Should different drivers not be feature compatible? The database and array driver use a separate store for locks, which makes that they behave differently then for example the redis driver, without an explicit mention of the difference in behaviour. I think either the database and array driver should be changed to use the same store, or drivers like redis driver should be changed to use a different store for locks, or the difference in behaviour should be mentioned somewhere in the docs.
