### ISSUE TITLE
Laravel development server failed to listen on 127.0.0.1:8000

### ISSUE THREAD

**Issue by jonboc** [laravel/framework#34255]
- Laravel Version: 8.0.3
- PHP Version: 7.3.9 with all necessary extensions enabled
- Database Driver & Version: MySQL 8.0.17
- OS: Windows 10

### Description:
After running composer create-project --prefer-dist laravel/laravel blog to create a new project the `php artisan serve` command fails to start the server. The terminal output is:
```
Starting Laravel development server: http://127.0.0.1:8000
[Thu Sep 10 14:02:24 2020] Failed to listen on 127.0.0.1:8000 (reason: ?)
```
It tries ten times before exiting. I have tried to start it on a different port but this also fails.

Other projects on the same machine running Laravel Framework 7.22.4 can all start the server.

### Steps To Reproduce:
```
composer create-project --prefer-dist laravel/laravel blog
php artisan serve
```

**Comment by driesvints** [comment]
We don't use Windows ourselves and we've had other reports that this works for people on Windows.

See https://github.com/laravel/framework/issues/34229

**Comment by ynaderi1959** [comment]
Why did you close this issue.
I have the same problem.

**Comment by ynaderi1959** [comment]
> * Laravel Version: 8.0.3
> * PHP Version: 7.3.9 with all necessary extensions enabled
> * Database Driver & Version: MySQL 8.0.17
> * OS: Windows 10
> 
> ### Description:
> After running composer create-project --prefer-dist laravel/laravel blog to create a new project the `php artisan serve` command fails to start the server. The terminal output is:
> 
> ```
> Starting Laravel development server: http://127.0.0.1:8000
> [Thu Sep 10 14:02:24 2020] Failed to listen on 127.0.0.1:8000 (reason: ?)
> ```
> 
> It tries ten times before exiting. I have tried to start it on a different port but this also fails.
> 
> Other projects on the same machine running Laravel Framework 7.22.4 can all start the server.
> 
> ### Steps To Reproduce:
> ```
> composer create-project --prefer-dist laravel/laravel blog
> php artisan serve
> ```

I solved the problem by this [link](https://stackoverflow.com/questions/52594477/composer-not-working-on-windows-gives-composer-exception-nosslexception-error/61361052/#answer-61361052)

**Comment by indrysfa** [comment]
change `php.ini-development` to be `php.ini`

**Comment by geomorillo** [comment]
i already have a php.ini it doesnt work for me im on windows 10

**Comment by ozerozay** [comment]
php -S 192.168.1.107:80 -t public/ worked for me.

**Comment by eniog** [comment]
php -S 127.0.0.1:80 -t public/ Works for me too

**Comment by arslan433** [comment]
php -d variables_order=GPCS artisan serve


run this command it works for me
