### ISSUE TITLE
Eloquent: $withCount + global scope w/ where + custom select() breaks bindings

### ISSUE THREAD

**Issue by rbresjer** [laravel/framework#34256]
- Laravel Version: 6.18.38
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.21 (not tested with other versions)

### Description:
Not sure how to explain best (I think the steps below make the issue clear), but when you have a specific combination of a global scope, a local scope, some where clauses and a custom `select()`, the query and the bindings do not line up anymore.

I encountered this issue whilst setting up a Nova metric for a model using a local scope. The Nova metric changes the `select()`.

### Steps To Reproduce:
Either clone [this repository](https://github.com/rbresjer/laravel-bindings-issue/) (which is a fresh Laravel 6 installation + [the steps below](https://github.com/rbresjer/laravel-bindings-issue/commit/92614d21953c36a841dd3bab53d579d29efc071f)), or:
1. Setup a fresh Laravel 6.* installation with a MySQL database (set up .env as well)
2. Create 2 models: e.g. TestParent and TestChild. TestParent should have a HasMany relation with TestChild. TestChild should have a column of type string
3. Add a `protected $withCount = ['testChildren'];` to the TestParent model
4. Create a global scope for TestChild with a where on the string column
5. Create a local scope for TestParent with a whereHas on TestChildren (e.g. a where on the updated_at)

Then:
1. `php artisan migrate:fresh`
2. `php artisan db:seed`
3. `php artisan tinker`, select TestParents by using the local scope, but add a custom select, e.g.: `App\TestParent::test()->select('id')->first();`

This results in:
```
Illuminate/Database/QueryException with message 'SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: 'lorem' (SQL: select `id` from `test_parents` where exists (select * from `test_children` where `test_parents`.`id` = `test_children`.`test_parent_id` and `updated_at` >= lorem and `string` = 1900-01-01 00:00:00) limit 1)'
```

The generated query:
```
>>> App\TestParent::test()->select('id')->toSql();
=> "select `id` from `test_parents` where exists (select * from `test_children` where `test_parents`.`id` = `test_children`.`test_parent_id` and `updated_at` >= ? and `string` = ?)"
```

The generated bindings:
```
>>> App\TestParent::test()->select('id')->getBindings();
=> [
     "lorem",
     "1900-01-01 00:00:00",
     "lorem",
   ]
```

So it looks like the custom `select()` does change the query but doesn't remove the corresponding bindings.

### Workaround
1. Make TestParent->withCount public.
2.
```
$builder = new TestParent;
$builder->withCount = [];
$builder = $builder->public();
...
```

**Comment by driesvints** [comment]
> Add a protected $withCount = ['testChildren']; to the TestParent model

You can't use this property directly like this. The `withCount` method as shown in the documentation does way more behind the hood.
