### ISSUE TITLE
User Namespace in RegisterController is still use App\User instead of use App\Models\User

### ISSUE THREAD

**Issue by absmugz** [laravel/framework#34269]
- Laravel Version: 7
- PHP Version: 7.2.5
- Database Driver & Version:

### Description:

RegisterController User Namespace is still use App\User instead of use App\Models\User

### Steps To Reproduce:

create new laravel app then run --auth

**Comment by spspasov** [comment]
Why would you expect it to use the `App\Models` feature? That's a Laravel 8 thing.
