### ISSUE TITLE
trailing comma results in syntax error

### ISSUE THREAD

**Issue by flaute** [laravel/framework#34275]
Error in BusServiceProvider.php line 51: syntax error, unexpected ')'

Removing the trailing comma resolves the bug.

https://github.com/laravel/framework/blob/8723739746a53442a5ec5bdebe649f8a4d9dd3c2/src/Illuminate/Bus/BusServiceProvider.php#L50

**Comment by taylorotwell** [comment]
That is valid syntax in PHP 7.3, which Laravel 8 requires.

**Comment by flaute** [comment]
Sorry!
My provider‘s CLI was still on PHP 7.2 while the main version has been switched to PHP 7.3 already.
