### ISSUE TITLE
Can't change the configuration of redis

### ISSUE THREAD

**Issue by abderrazzak-oxa** [laravel/framework#34276]
- Laravel Version: 7.28.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 8

### Description:
When i want to change the redis (url, password ...) it can't be changed because laravel can't update the config when i call `app('cache')->forgetDriver('redis')`

### Steps To Reproduce:
```
app('cache')->set('test', 'test_value');
config()->set('database.redis.cache.host', null);
app('cache')->forgetDriver('redis');
app('cache')->set('test', 'test_value');// there's no error for nulled url
```

### Problem
The problem is in Redis Service Provider `\src\Illuminate\Redis\RedisServiceProvider.php`
```
$this->app->singleton('redis', function ($app) {
    $config = $app->make('config')->get('database.redis', []);

    return new RedisManager($app, Arr::pull($config, 'client', 'phpredis'), $config);
});
```
### Solve
I think this problem will be solved when you update the config when calling forgetDriver method

**Comment by taylorotwell** [comment]
You could probably unset the redis singleton from the container:

```php
$container = app();
unset($container['redis']);
```

**Comment by abderrazzak-oxa** [comment]
@taylorotwell Thank You

**Comment by abderrazzak-oxa** [comment]
@taylorotwell 
it give me this error!
```
Illuminate\Contracts\Container\BindingResolutionException
Target class [redis] does not exist.
```

**Comment by abderrazzak-oxa** [comment]
if you use:
```
$container = app();
unset($container['redis']);
``` 

you will delete bindings and instances and resolved
```
unset($this->bindings[$key], $this->instances[$key], $this->resolved[$key]);
``
just we need to delete only instances<br>

so the right way is:
```
app('cache')->forgetDriver('redis');
App::forgetInstance('redis');
```

@taylorotwell  Thank for help!
