### ISSUE TITLE
allOnQueue call on chained jobs crash

### ISSUE THREAD

**Issue by Krunch** [laravel/framework#34272]
- Laravel Version: 8.0.3
- PHP Version: 7.3.20
- Database Driver & Version: mysql 8.0.20

### Description:
I just upgraded to Laravel 8 and the same code that worked in Laravel 7 stopped working. Calling `allOnQueue` on a chained job returns this error:
`Call to a member function allOnQueue() on int`

### Steps To Reproduce:

`Job1::withChain([
    new Job2()
])->dispatch()->allOnQueue('other');`

I tried to use the new recommended way in the documentation with `Bus::chain(...)->dispatch()->allOnQueue('other')` but the same error was being thrown.

**Comment by taylorotwell** [comment]
I'll have to let Mohamed weigh in but maybe looks like an undocumented breaking change we will need to document.

I think you are maybe supposed to do:

```php
Job1::withChain([new Job2])->onQueue('other')->dispatch();
```

Or...

```php
Bus::chain([new Job1, new Job2])->onQueue('other')->dispatch();
```

**Comment by themsaid** [comment]
It's an undocumented breaking change indeed. Here's a PR to add it to the docs https://github.com/laravel/docs/pull/6348
