### ISSUE TITLE
Query Builder Closure adding `select *` if extra values are passed to it

### ISSUE THREAD

**Issue by byteasc** [laravel/framework#34273]
- Laravel Version: v8.0.3
- PHP Version: 7.4.2

### Description:

Query Builder `where` closure is adding a `select *` to the Sql, when in previous versions this wasn't the case. 

### Steps To Reproduce:

```
DB::table('users')
            ->where('name', '=', 'John')
            ->where(function ($query) {
                $query->where('votes', '>', 100)
                    ->orWhere('title', '=', 'Admin');
            }, '=', true);
```

Previously the `where` would be:  ```("votes" > '100' or "title" = 'Admin')```
It is now producing: ```(select * where "votes" > '100' or "title" = 'Admin') = 1```

This example will cause the where to have a `select *` created with it. Although, it appears to be related to passing the = and true thru to the where, but in previous versions this was either removed programmatically or the functionality has changed. This obviously is causing some things to fail that weren't previously, even if the extra values are necessary for the Where, which they don't appear to be.. but we're updating from an older version of laravel so somebody wrote our code that way for some reason

**Comment by taylorotwell** [comment]
Interesting. I'm curious why you are passing the = true at all? Isn't your goal accomplished even when you don't pass it?

**Comment by byteasc** [comment]
> Interesting. I'm curious why you are passing the = true at all? Isn't your goal accomplished even when you don't pass it?

I asked the same thing actually to the developer here that wrote that code (in quite a few places thru-out the application, but I only found it due to a unit test failure)... and he said he wrote it that way because without it, there were cases where what was being produced by the query builder was causing weird side effects, so by adding the = true, it seemed to cause those issues to be corrected.

**Comment by taylorotwell** [comment]
Hmm, I don't think that should be the case. It should not be necessary.

**Comment by byteasc** [comment]
> Hmm, I don't think that should be the case. It should not be necessary.

I can go thru and change all of our codebase that has that set that way and see if there are any side effects from it, that I can tell.. just found it odd that it was now throwing in the `select *` as part of the query now.

Although to be fair, we are coming from 5.8 and making the jump to 8, so it is possible that something has been corrected in the last few versions that was responsible for what we were seeing prior.

**Comment by ninjaparade** [comment]
Wonder if this is related to something Matt did?

**Comment by taylorotwell** [comment]
I think the select is added because we added a new feature making sub query wheres easier to construct. We didn't anticipate needing to support the use case you describe because it should never be necessary to execute the boolean logic you want.

**Comment by byteasc** [comment]
> I think the select is added because we added a new feature making sub query wheres easier to construct. We didn't anticipate needing to support the use case you describe because it should never be necessary to execute the boolean logic you want.

Works for me @taylorotwell  I will go thru and fix our codebase to not use that logic and keep an eye on it! Thank you for following up
