### ISSUE TITLE
can't call route api

### ISSUE THREAD

**Issue by letieu** [laravel/framework#34279]
- Laravel Version: 8.x
- PHP Version: 7.4

### Description:
I create a SPA , define a route catch all
 `Route::any('{catchall}', function () {
    return view('app');
})->where('catchall', '.*');`

and create all api route in api.php, but when call api , all request go to route web, and return view app

**Comment by rimace** [comment]
Can you post your `routes.php` and `api.php` please. So I can try to replicate the problem.

**Comment by letieu** [comment]
> Can you post your `routes.php` and `api.php` please. So I can try to replicate the problem.
## My api.php
> <?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;



Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

Route::apiResource('tasks', \App\Http\Controllers\TaskController::class);

## My web.php
.
> <?php

use Illuminate\Support\Facades\Route;



Route::any('{catchall}', function () {
    return view('app');
})->where('catchall', '.*');

**Comment by gmutinel** [comment]
Laravel 8 changes the RouteServiceProvider behaviour, but it's not yet documented in the upgrade guide, take a look at the "Routing Namespace Updates" section here: https://laravel.com/docs/8.x/releases

took me a bit too to fix this during the upgrade

**Comment by serhatculhalikp** [comment]
@JeffreyWay had mentioned this https://twitter.com/jeffrey_way/status/1303728676434063361

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
