### ISSUE TITLE
Cannot implode collection of Stringables

### ISSUE THREAD

**Issue by leepownall** [laravel/framework#34270]
- Laravel Version: 8.0.3
- PHP Version: 7.4.9
- Database Driver & Version: N/A

### Description:

Cannot implode a collection of Stringables.

### Steps To Reproduce:

```php
collect([Str::of('taylor'), Str::of('dayle')])->implode(',');

// Expected
'talyor,dayle'

// Actual
''

```

**Comment by taylorotwell** [comment]
This is more of a feature request.
