### ISSUE TITLE
schema:dump error

### ISSUE THREAD

**Issue by vladislavtkachenko** [laravel/framework#34280]
- Laravel Version: 8.0.4
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.31

### Description:
mysqldump: unknown variable 'set-gtid-purged=OFF'

### Steps To Reproduce:
php artisan schema:dump

**Comment by vladislavtkachenko** [comment]
`$this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION)` - returns '5.7.31'

**Comment by driesvints** [comment]
I can't reproduce that on this version.

**Comment by vladislavtkachenko** [comment]
if you can't reproduce it, then there is no problem. ok :)

**Comment by from20020516** [comment]
@vladislavtkachenko Are you using `mysql-default-client` a.k.a `maria-db-client`? 
This error occurs because the `--set-gtid-purged` option does not exist in mariadb.

Try this:
```sh
wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb -P /tmp \
  && dpkg -i /tmp/mysql-apt-config_0.8.15-1_all.deb \
  && apt-get update -y \
  && apt-get install mysql-client -y
```

**Comment by iraklisg** [comment]
@from20020516  `mysql-client` package seems to be unavailable in mysql APT repository

`Package 'mysql-client' has no installation candidate`
