### ISSUE TITLE
Route resource not working in laravel 8.x

### ISSUE THREAD

**Issue by AlisherN** [laravel/framework#34286]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Route::resource() method is giving ```Target class [Admin\App\Http\Controllers\Admin\ProfileController] does not exist.``` error
Here is the code:
```
Route::prefix('admin')->namespace('Admin')->group(static function() {

    Route::middleware('auth')->group(static function () {
        //...
        Route::resource('profile', ProfileController::class);
    });
});
```

**Comment by driesvints** [comment]
Please read the upgrade guide, specifically the part about controller namespaces: https://laravel.com/docs/8.x/upgrade

**Comment by steve111MV** [comment]
The easiest way to fix this is to import your CustomController class in the route.

`
use App\Http\Controllers\VideoController;

use App\Http\Controllers\BlogController;
`

**Comment by kuvar0158** [comment]
you should try this ..this is working for me.....
php artisan cache:clear
php artisan route:clear
php artisan view:clear

**Comment by AhmedOmar414** [comment]
remove the namespace('admin')
