### ISSUE TITLE
Illuminate Support Arr class not found.

### ISSUE THREAD

**Issue by loduis** [laravel/framework#34292]
I can't find this class in the framework in version 8
![image](https://user-images.githubusercontent.com/451862/92948991-ec123080-f41f-11ea-8710-703ec260a1a6.png)
previus version exists
![image](https://user-images.githubusercontent.com/451862/92949058-0cda8600-f420-11ea-9444-68269d739e28.png)

**Comment by driesvints** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Arr.php

**Comment by jessarcher** [comment]
I realise this is probably my issue, but I'm getting an error on `composer install` since this file was moved.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception
In ClassLoader.php line 444:
                                                                               
  include(/builds/<redacted>/<redacted>/vendor/composer/../laravel/framework/sr  
  c/Illuminate/Support/Arr.php): failed to open stream: No such file or direc  
  tory     
```

```
$ php --version
PHP 7.4.10 (cli) (built: Sep  3 2020 19:59:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
$ composer --version
Composer 1.10.13 2020-09-09 11:46:34
```

It's only failing in CI (i.e. a fresh build with no cache or anything). On my local machine it's fine. I'll post back if I figure it out.

**Comment by jessarcher** [comment]
As is often the way, and as I suspected, the issue was mine, and I solved it moments after posting the above :joy: 

There was another cache at play - the CI runner cache on GitLab. After clearing that, it built fine.

Hopefully this helps someone else!

**Comment by LukeTowers** [comment]
@driesvints is this class aliased anywhere? The SupportArr test still references the old path but I can't seem to find any aliasing that would support that.

**Comment by driesvints** [comment]
Hey @LukeTowers, what do you mean with 

> The SupportArr test still references the old path

Can you point out where?

**Comment by LukeTowers** [comment]
@driesvints sure, see https://github.com/laravel/framework/blob/8.x/tests/Support/SupportArrTest.php#L6

**Comment by driesvints** [comment]
That seems okay to me?

**Comment by LukeTowers** [comment]
@driesvints it's referencing `lluminate\Support\Arr` when the actual class is `lluminate\Collections\Arr`. If `lluminate\Support\Arr` is expected to work; my question is where is that connection between the non-existent `lluminate\Support\Arr` class and the actual `lluminate\Collections\Arr` class set up?

**Comment by driesvints** [comment]
The `Illuminate\Collections` namespace doesn't exists? 

I do see there's two usages of it [that was introduced in this PR](https://github.com/laravel/framework/pull/37034) but the OP accidentally used it while it should have been `Support`. I'll send in a PR to fix that.

**Comment by LukeTowers** [comment]
@driesvints ahh, I see! The collections stuff was split off into its own package but the namespace remained the same; that's the critical piece of information that I was missing. Specifically to answer my own question [this line](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/composer.json#L23) is what makes `/src/Illuminate/Collections/Arr.php` available as `Illuminate\Support\Arr`.
