### ISSUE TITLE
Laravel Sanctum does not work anymore with Laravel 8

### ISSUE THREAD

**Issue by alihassan1133** [laravel/framework#34301]
- Laravel Version: 8.1.0
- PHP Version: 7.4.9
- Database Driver & Version: mysql Ver 15.1 Distrib 10.4.14-MariaDB

### Description:
![image](https://user-images.githubusercontent.com/62854082/92985061-2e1d8f80-f47d-11ea-9f65-c9966cdaa351.png)

I was trying to migrate an application from Laravel 7 to 8. My authentication does not work anymore. I can still log in using the form and I'm redirected, but after that I'm getting a general "unauthenticated" message. It seems like the Sanctum middleware is not picking up the fact that I have logged in.

**Comment by driesvints** [comment]
Please open this on the sanctum repo
