### ISSUE TITLE
Duplicate Server Error View

### ISSUE THREAD

**Issue by malohtie** [laravel/framework#34305]
- Laravel Version: 8.1
- PHP Version: 7.4

### Description:
 The Server Error view render 2 times

![image](https://user-images.githubusercontent.com/20033279/92992689-aa978900-f4e4-11ea-8b78-b4e3b05dbe09.png)

![image](https://user-images.githubusercontent.com/20033279/92992704-c569fd80-f4e4-11ea-8029-d50ff668e40d.png)

### Steps To Reproduce:

Remove App key

**Comment by driesvints** [comment]
Managed to reproduce this on the Livewire stack. App needs to be out of debug mode to reproduce.

**Comment by taylorotwell** [comment]
I'm having trouble reproducing it on my end. Can you give me step by step instructions starting with "laravel new"...

**Comment by malohtie** [comment]
@taylorotwell yes sure,

make new project 
``` laravel new test ```

remove  app Key
![image](https://user-images.githubusercontent.com/20033279/93000546-1d265a00-f521-11ea-8b38-6a5045c13aec.png)

serve application,  
``` laravel artisan serve ```

![image](https://user-images.githubusercontent.com/20033279/93000582-4515bd80-f521-11ea-9f19-15909166a729.png)

also i just notice that if APP_DEBUG is true will render this page two times

![image](https://user-images.githubusercontent.com/20033279/93000635-a178dd00-f521-11ea-8060-fcf202544a9b.png)

**Comment by vkosciuszko** [comment]
From what i've seen it happen when resolving the EncryptCookies middleware in the terminate method of the application.

**Comment by taylorotwell** [comment]
It only happens for me on the PHP dev server (artisan serve)... does not happen when running under Nginx.

**Comment by taylorotwell** [comment]
Yeah, if the framework can't resolve a middleware due to something like a missing APP_KEY the handle and terminate both throw an exception and it gets rendered twice. I personally have no plans to spend anytime fixing this as it does not affect applications in reality / production or cause any significant problem. If someone else wants to devote some time to fix it feel free but I'm not sure how simple it would be.

**Comment by malohtie** [comment]
i managed to reproduce it also on laragon homestand using apache

**Comment by vkosciuszko** [comment]
Just catch the exception then die.

**Comment by taylorotwell** [comment]
This also happens on 7.x Probably has happened for a while if you delete your app key. I suggest just not doing that.
