### ISSUE TITLE
Bugg in BusServiceProvider.php

### ISSUE THREAD

**Issue by TheDevJulian** [laravel/framework#34308]
- Laravel Version: 8
- PHP Version: 7.3
- Database Driver & Version: I don't know.

### Description:
Bug found in: `/vendor/laravel/framework/src/Illuminate/Bus/BusServiceProvider.php`

The code below has an bug:
```php
    protected function registerBatchServices()
    {
        $this->app->singleton(BatchRepository::class, DatabaseBatchRepository::class);

        $this->app->singleton(DatabaseBatchRepository::class, function ($app) {
            return new DatabaseBatchRepository(
                $app->make(BatchFactory::class),
                $app->make('db')->connection(config('queue.batching.database')),
                config('queue.batching.table', 'job_batches'),
            );
        });
    }
```
### Steps To Reproduce:
Remove the `,` that is on the line: `config('queue.batching.table', 'job_batches')` or else `/password/email` will not work.

**Comment by taylorotwell** [comment]
That is valid PHP syntax as of PHP 7.3. It is likely your CLI PHP is not PHP 7.3 or higher.

**Comment by TheDevJulian** [comment]
See the screen for PHP version I'm using
![VxyTh18yPl](https://user-images.githubusercontent.com/48862721/92998085-23fc9f00-f518-11ea-97e2-5c4914896e07.png)
