### ISSUE TITLE
Namespace name doesn't match the PSR-0/PSR-4 project structure 

### ISSUE THREAD

**Issue by sinkcup** [laravel/framework#34307]
- Laravel Version: 8.1.0
- PHP Version: 7.4
- Database Driver & Version: sqlite

### Description:

Laravel 8 does not need to be compatible with the old version, so could follow PSR-4, now it has error:

![image](https://user-images.githubusercontent.com/4971414/92994416-9bd4c480-f52c-11ea-90fd-15f72f1f9469.png)

suggest:

rename `database/factories/` to `database/Factories/`, such as `app/Http` not `app/http`.

### Steps To Reproduce:

change

```json
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
```

to

```json
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\": "database/"
        }
    },
```

**Comment by driesvints** [comment]
It definitely does.

**Comment by GrahamCampbell** [comment]
This is a bug in phpstorm.

**Comment by afilina** [comment]
Here's a workaround. Open your PHPStorm settings and go to `Inspections > Class path doesn't match project structure > Directories`. Configure the folder/namespace associations that are causing problems. Example:

![image](https://user-images.githubusercontent.com/199835/104762221-fb88e980-5731-11eb-9968-b0a8ab40682c.png)

**Comment by sinkcup** [comment]
Maybe I didn't make it clear, I mean: Laravel 8 is working fine in PHPStorm, and the 'database/' changed to PSR-4, but dirs in 'database/' is still lowercase, so we can find the hack for PSR-4 in `composer.json`, other uppercase dirs in 'app/' or 'tests/' are very good. @driesvints @GrahamCampbell 
When the major version changes, it may be an opportunity to make such incompatible changes.

![image](https://user-images.githubusercontent.com/4971414/110887018-80ecdc80-8324-11eb-9865-bc6c2f66c246.png)

```
├── app
│   ├── Console ✓ uppercase
│   ├── Exceptions ✓ uppercase
│   ├── Http ✓ uppercase
│   ├── Models ✓ uppercase
│   └── Providers ✓ uppercase
├── database
│   ├── factories ✕ lowercase, need hack for PSR-4
│   ├── migrations
│   └── seeders ✕ lowercase, need hack for PSR-4
├── tests
│   ├── Feature ✓ uppercase
│   └── Unit ✓ uppercase
```

**Comment by trin4ik** [comment]
> It definitely does.

https://laravel.com/docs/10.x/contributions#coding-style

![image](https://user-images.githubusercontent.com/839633/235166662-5a8de16f-b8ae-464d-a3dd-f7193866eb31.png)

**Comment by isaacdarcilla** [comment]
> Here's a workaround. Open your PHPStorm settings and go to `Inspections > Class path doesn't match project structure > Directories`. Configure the folder/namespace associations that are causing problems. Example:
> 
> ![image](https://user-images.githubusercontent.com/199835/104762221-fb88e980-5731-11eb-9968-b0a8ab40682c.png)

This works.
