### ISSUE TITLE
Jetstream / Teams: Column not found: 1054 Unknown column 'current_team_id' in 'field list'

### ISSUE THREAD

**Issue by McPan** [laravel/framework#34304]
- Laravel Version: 8.1.0
- PHP Version: 7.4.10
- Database Driver & Version: mysql / mariadb 10.4.14
- Package Jetstream / Livewire w. Teams

### Description: Exeception Error after registering a new user and redirect to dashboard

ErrorException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'current_team_id' in 'field list' (SQL: update `users` set `current_team_id` = 1, `users`.`updated_at` = 2020-09-12 09:07:10 where `id` = 1) (View: <PATH_TO_PROJECT>\resources\views\layouts\app.blade.php) (View: <PATH_TO_PROJECT>\resources\views\layouts\app.blade.php) 

Described column 'current_team_id' is missing in the 'users' table.

### Steps To Reproduce:

Create a new Laravel 8 project

```
composer create-project --prefer-dist laravel/laravel .\
```

Include 'jetstream' package

```
composer require laravel/jetstream
```

Create and run migrations

```
php artisan jetstream:install livewire --teams
npm install && npm run dev
php artisan migrate
```

Open the website of the new project and register a new user. Redirecting to the 'dashboard' will throw the exception specified above.

### (Temporary) solution

Create and run another migration

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddCurrentTeamIdToUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->foreignId('current_team_id')
                    ->after('remember_token')
                    ->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('current_team_id');
        });
    }
} 
```

Try to register a new user and everything works fine.

**Comment by driesvints** [comment]
Please open this on the jetstream repo.
