### ISSUE TITLE
Package illuminate/collections needs symfony/var-dumper

### ISSUE THREAD

**Issue by ronvanderheijden** [laravel/framework#34306]
- Illuminate/Collections Version: v8.1.0
- PHP Version: PHP 7.4.10 (cli)
- Database Driver & Version: n/a

### Description:

When using the `illuminate/collections` package, I encounter a dependency problem.  
It seems that, to use `dump()` or `dd()`, I need `symfony/var-dumper`.

1. https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Collection.php#L13
2. https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Traits/EnumeratesValues.php#L16
3. https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/composer.json

### Steps To Reproduce:
```json
{
    "require": {
        "illuminate/collections": "^8.1"
    }
}
```

```php
collect([])->dump();
```

Gives `PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\VarDumper\VarDumper' not found in ...`.

### Possible solution
```json
{
    "require-dev": {
        "symfony/var-dumper": "^5.1"
    }
}
```

**Comment by taylorotwell** [comment]
You can install it in your own application if you need it. I don't think we should require it for one method.
