### ISSUE TITLE
ComponentAttributeBag's $attributes should be an array, is another CAB instead

### ISSUE THREAD

**Issue by stancl** [laravel/framework#34313]
- Laravel Version: 8.1.0
- PHP Version: PHP 7.4
- Database Driver & Version: irrelevant

### Description:

Attributes passed to components as `$attributes` are an instance of `ComponentAttributeBag`.

This class has a property, `$attributes`, that should be an array according to the source code.

However, `@dd($attributes)` inside a component shows:

```
Illuminate\View\ComponentAttributeBag {#1284 ▼
  #attributes: Illuminate\View\ComponentAttributeBag {#340 ▼
    #attributes: array:1 [▼
      "class" => "text-sm leading-5 font-medium text-gray-900"
    ]
  }
}
```

As you can see, the *outer* CAB's `$attributes` is another instance of CAB. The *inner* one is correct and has an array `$attributes` property.

I've been looking into the source code trying to figure out how this can even happen — because most CAB's methods for setting `$attributes` only accept arrays — but didn't succeed.

So, in short: **I think `$attributes` in components should be stored in a `ComponentAttributeBag`'s `$attributes` property *as an array*. Not as another object which contains that array.**

### Steps To Reproduce:

Create a component and `@dd($attributes)` inside.

### Other implications

I discovered this by trying to create a `ComponentAttributeBag` myself. My use case is that I have a dynamic component and I wanted to **pass data from an array such that it would become part of $attributes`**.

To do this, I tried to do:
```html
<x-dynamic-component :component="$someVariable" {{ $field->attributes() }} class="abc">
```

Where `$field->attributes()` returns `new ComponentAttributeBag(['foo' => 'bar'])`.

However, this resulted in some errors in the compiled Blade code.

Since `$attributes` can be used like
```html
<input type="text" {{ $attributes }}>
```
I was hoping that creating a `ComponentAttributeBag` — an object of the same type as `$attributes` — would let me pass an array as attributes on an `x-dynamic-component` call.

But, like I said, this resulted in those strange Blade errors. **This might be due to the fact that a version of `ComponentAttributeBag` which works — components' `$attributes` — has a structure of `ComponentAttributeBag->ComponentAttributeBag->array`, rather than `ComponentAttributeBag->array` (which it should have), that I tried to construct myself.**

So, to recapitulate, I'd like to know:
1. If `$attributes` in components should be `ComponentAttributeBag->attributes = array`, rather than two nested objects
2. If the fact that `$attributes` uses two nested objects is why my own `ComponentAttributeBag` is not working in `<x-dynamic-component :component="$someVariable" {{ $field->attributes() }}>`

Point 1 is a mismatch of docblocks and the real object, and point 2 is what I'm really trying to achieve.

**Comment by stancl** [comment]
Okay, so it seems like the *other implications* section is not related to this, because even this code:

```html
<x-dynamic-component :component="$foo" {{ '' }}>
    foo
</x-dynamic-component>
```

breaks with the same exception. Calling anything using `{{ }}` in the dynamic component call breaks. But that's a separate problem. If you recognize that as a valid bug, I'll open a separate issue for this.

So the weird thing that remains is the structure of the `$attributes` ComponentAttributeBag in components.

**Comment by taylorotwell** [comment]
I'm lost reading this. Give me an example of something that is broken that you want to work in your application.

**Comment by taylorotwell** [comment]
Issue 1: OK, but what does that mean practically? Just that the docblock is wrong?

Issue 2: Yeah, it appears there is some problem with proxying down attributes on a dynamic-component. If you want to look into fixing this please go ahead.

**Comment by stancl** [comment]
1. I think it's not just a docblock issue. The entire class seems to assume that it's an array. And the double nesting of classes makes no sense to me. So **I think the docblock is correct, but for some strange reason the double nesting happens - and could cause some unexpected issues.**
2. I initially thought that 1) was the cause of this, but as I found out with the empty string Blade call `{{ '' }}`, these two issues aren't related.

So since 2) is an independent thing, I don't have a practical issue that 1) causes, but it's still weird behavior worth looking at.

And for 2) I'll open a separate issue. Not sure if I can solve this myself but I can try.

**Comment by taylorotwell** [comment]
Why open a separate issue?

**Comment by stancl** [comment]
The two issues are unrelated. I thought the issue with passing Blade to dynamic components was caused by the first issue (the component bag thing), but it's independent. Two completely separate issues.

**Comment by taylorotwell** [comment]
Issue 2 is fixed and will be released in next patch.

**Comment by taylorotwell** [comment]
I think they are related and both issues are fixed by my latest commit.

**Comment by taylorotwell** [comment]
Sorry I meant to say issue 1 is fixed. I don't know about issue 2. I am able to {{ }} on a dynamic component... maybe it is only if it's at the end of the tag?

**Comment by taylorotwell** [comment]
Issue 2 is basically expected. Echos in component aren't "actually" processed at all. Echoing inside attributes is supported and echoing {{ $attributes }} is supported but nothing else is supported. That is because components are compiled before the render cycle even happens.

**Comment by stancl** [comment]
Thanks a lot @taylorotwell !

Okay, so I did some more digging with the help of @imliam and we found a few things.

## Passing dynamic attributes to components

Like you said, echoing `{{ $attributes }}` works, but nothing else is supported. This is due to the regex that compiles opening Blade-x tags:

https://github.com/laravel/framework/blob/1b83b3c03c9513f2e0d0a80ee8a895b07534237b/src/Illuminate/View/Compilers/ComponentTagCompiler.php#L113

This quite literally means that `{{ $field->attributes() }}` won't work, but `{{ $attributes }}` will.

There are two workarounds here.

### Creating a temporary attributes variable

Right above the component call, you can use:
```html
@php($attributes = $field->attributes)
```
To be able to echo `{{ $attributes }}`.

### Binding to the attributes property

I'm not sure if this works with other components too, but with the dynamic component, you can use `:attributes="$foo" class="bar"` and the resulting `$attributes` inside the component will contain `$foo` merged with `'class' => 'bar'`, which is neat.

Note that `$foo` needs to be an instance of `ComponentAttributeBag`, rather than an array.

---

I'm writing this down so that anyone trying to figure out how to pass dynamic attributes to components has an easier time. I'll rename the issue as well.

Another solution me and Liam investigated was using `@component()` directly, because ultimately what I'm trying to do here is pass a dynamic array of attributes to a dynamic component - like `@component($component, $data)`. But it requires a lot of extra magic to work with class-based components.

So the solution above with `:attributes="..."` is probably ideal.

**Comment by lucas-quinn-guru** [comment]
I was only able to get the custom attributes to pass to the dynamic component if they were of type ComponentAttributeBag.  But, I still had a problem passing a alpineJS attribute.

From a controller, I'm building a view to display a dynamic component that I want to have a clickable event.

`view("partials.component")->with(
     [
         "componentName"=>"icon.trash",
          "attributes"=> new ComponentAttributeBag(
              [
                  "@click"=>"$dispatch('flash', { account_uuid: '" . $account[ 'uuid' ] . "' })",
                          
              ]
          )
     ]
)`

This will throw an exception because I think, the array passed to ComponentAttrributeBag cannot have a key starting with a @.  Is there a way to escape this so that it works?

**Comment by stancl** [comment]
> I don't know why yet

Blade assumes it's a directive. You should be encoding that string probably.

Also, displaying a component like that is not a good idea, it's a pretty hacky approach. Just return a view that does `<x-dynamic-component>`
