### ISSUE TITLE
Profile Image not Showing Laravel 8 jetstream

### ISSUE THREAD

**Issue by DikshantNiraula** [laravel/framework#34319]
- Laravel Version: 8.0.0
- PHP Version: 7.3
- Database Driver & Version: sql

### Description:

Hi, I created a laravel project after 1 day of Laravel 8 release, I was checking features of jetstream
and everything works fine except when I change Image ot doesnot show up due to some reasons, found out that the url of image shows localhost instead of localhost:8000 { which showed image},
so my query is is there any where in file I can change so that I will see the image with url :8000( Already tried .env url)
Thank you...

**Comment by taylorotwell** [comment]
Make your your .env APP_URL is correct and make sure to run php artisan storage:link.

**Comment by DikshantNiraula** [comment]
Tried it but no good.. linked storage file shows uploaded image but inspecting in browser shows localhost.
will try with fresh laravel 8 files again..

**Comment by janreycablinda** [comment]
I have the same problem. is there any solution?

**Comment by Sunny-Ojo** [comment]
same problem here, and it makes the profile page ugly when it doesn't display. The image is currently in the storage folder though

**Comment by BloodTwist** [comment]
Hello, I delete the storage symbolic link in the public/ directory, and run `php artisan storage:link`, It works for me. Cache error?

I use `php artisan view:clear` , and doesn't works.

**Comment by skino2019** [comment]
This issue is resolved my changing the **APP_URL=http://sitename.test** in your .ENV to what you have your domain parked as (Using Valet).

i use the .vm url so i changed mine to sitename.vm and my mugshot shows correctly.

**Comment by DevRKYSona** [comment]
> Make your your .env APP_URL is correct and make sure to run php artisan storage:link.

Thanks! It helped me.

**Comment by DikshantNiraula** [comment]
I made a fresh Laravel 8 folder and it worked smooth.
Thank you everyone.

**Comment by tomicato** [comment]
skino2019 прав! Всё заработало прекрасно - лично для меня:
- .env APP_URL 
- php artisan view:clear

**Comment by hamuelpalallos** [comment]
Just delete or comment the APP_URL in .env, it should work just fine!

**Comment by MonDc** [comment]
After correction of APP_URL, 
run this :  
php artisan optimize:clear

**Comment by dariusdauskurdis** [comment]
I had the same problem, my profile photo had wrong url 
http://**myproject.test/myproject.test**/storage/profile-photos/nf4U3SAgD8jAec1Q41lARqNxpSUSFUcPoBS5RQxG.jpeg
Duplicated **myproject.test**
`APP_URL=myproject.test `
I changed to 
`APP_URL=http://myproject.test` 
and everything is ok now. Don't forget to add http://

**Comment by suaveone** [comment]
I solved this!  If you use a virtual dev environment like **Vagrant** which I do. Your storage link might be linked to your local path and not your environment dev path.  When I checked mines was linked to the local path.  I was being careless and was not using my **vagrant ssh**.  Once was in **vagrant ssh** I removed the storage link in **public: rm -r public/storage** and re added it with **php artisan storage:link** that fixed it.  Im sure this issue can occur in other environments as well.

**Comment by rscodelab** [comment]
Set your APP_URL in .env , mine is APP_URL=http://localhost:8000
and run the command in CLI as **php artisan storage:link** to create the symbolic link for storage/app/public, if you haven't run the command you will not get the profile image in you dashboard.

**Comment by alexanderwerk** [comment]
First of all, check whether the slashes under:

 **config / jetstream.php**

in line 44 (features) are still there. If so, then these must be deleted in order to activate this feature.

**Comment by ausafmughal** [comment]
@alexanderwerk your solution worked for me thank you.

**Comment by Sunny-Ojo** [comment]
Thank you all

**Comment by tecbeez** [comment]
@alexanderwerk it works for me. Thanks mate

**Comment by arafkarim** [comment]
I used 'php artisan view:clear' first and then 'php artisan storage:link' 
These work for me.

**Comment by Said20hr** [comment]
This would help in case you are using jetstream and you run all : 

- in .env =>` APP_URL=http://127.0.0.1:8000`
- `php artisan storage:link`
- `php artisan view:clear` or `php artisan optimize:clear`


And all what you get is an empty box for profile_photo_url, you need to verify that the attribute `name` is still exist on model `User`, otherwise you can custom the function **defaultProfilePhotoUrl()**  from  **HasProfilePhoto trait**, because it's returning the field `name`

**Comment by solos10x** [comment]
my profile photo was working fine but when i uploaded my website from the localhost to my webhost it stop working
