### ISSUE TITLE
Abort method with message parameter does not render the message itself as told in the docs unless debug mode is set to true, or the request expects json

### ISSUE THREAD

**Issue by ProteanCode** [laravel/framework#34317]
- Laravel Version: 8.0.4
- PHP Version: 7.4.7
- Database Driver & Version: postgis/postgis:12-3.0-alpine

### Description:

Running abort method with message parameter does not render the message itself as told in the docs unless debug mode is set to true, or the request expects json

> HTTP Exceptions
> Some exceptions describe HTTP error codes from the server. For example, this may be a "page not found" error (404), an "unauthorized error" (401) or even a developer generated 500 error. In order to generate such a response from anywhere in your application, you may use the abort helper:
> 
> abort(404);
> The abort helper will immediately raise an exception which will be rendered by the exception handler. Optionally, you may provide the response text:

> abort(403, 'Unauthorized action.');

### Steps To Reproduce:

Use the following code in Authenticate middleware

```
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        abort(404, 'The page is missing');                                      // The page is missing will not render, we will get classic blade 404 Not found view
        abort(422, 'The data you passed are invalid');                          // This will render a 'The server returned a "422 Unprocessable Entity".'
        abort(500, 'Devs are running out of coffee to fix it, please wait');    // This will render a view with "500 Server error"
    }
}
```

### Steps To Fix:

While this is not directly a bug, its a misleading documentation. Documentation should mention that the message parameters work only for json requests and customized messages are described in next paragraph. Either update the docs or include the message parameter in your default error templates.

Edit: while looking at 403 error message there is that line:
`@section('message', __($exception->getMessage() ?: 'Forbidden'))`
that works as I would personally thing any or these error blade files should work

**Comment by taylorotwell** [comment]
We can fix the documentation. Can you submit a PR.
