### ISSUE TITLE
Sessions does not support multiple guards

### ISSUE THREAD

**Issue by aminetiyal** [laravel/framework#34310]
- Laravel Version: 8.1.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.24

### Description:
The sessions table does not support multiple guards, you can see below the first row is with a normal **web** guard the second one is with a costumed guard that I created, which make it impossible to work with the new jetstream package while managing browser sessions
![image](https://user-images.githubusercontent.com/13120169/92999095-2bbb4400-f516-11ea-8e9c-bbf3f1785125.png)

### Steps To Reproduce:

Add the `user_type` column to the sessions table, and provide authenticated user class name while setting user information to the payload

**Comment by taylorotwell** [comment]
This is a feature request.
