### ISSUE TITLE
Returning response from authenticate middleware returns "Header may not contain more than a single header, new line detected" error

### ISSUE THREAD

**Issue by ProteanCode** [laravel/framework#34316]
- Laravel Version: 8.0.4
- PHP Version: 7.4.7
- Database Driver & Version: postgis/postgis:12-3.0-alpine

### Description:

I want to return a 422 response from middleware if the headers sent by client does not match expected one

### Steps To Reproduce:

Use the following code in Authenticate middleware

```
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return response("Expected header Accept application/json", 422);
        }
    }
}
```

And you will get the 500 response "Header may not contain more than a single header, new line detected"

In fact returning even an empty response from middleware (at least this one) results in this error.

I am also using jwt-auth if that matters but I highly doubt

Currently I am aborting the action with abort method but this does not allow me to show the message to end user when debug is set to false so its a no-go

This links to my another bug report: https://github.com/laravel/framework/issues/34317

**Comment by taylorotwell** [comment]
Note the return type of the method you are modifying. It expects a string. You are returning an entire response which Laravel is then trying to stuff into the Location header of a redirect.
