### ISSUE TITLE
Failed Jobs seem to be inserting value of null for column id, produces not null violation in PostgreSQL 

### ISSUE THREAD

**Issue by gordongrech** [laravel/framework#34322]
- Laravel Version: 7.17.2
- PHP Version: 7.4.6
- Database Driver & Version: PostgreSQL 12.3

### Description:
The Application's database infrastructure consists of multiple connections and schema. UUIDs are used across the board as primary keys, however auto-incrementing integers are used for the failed_jobs table to maintain consistency with the framework. 

When failed jobs are inserted into the failed_jobs table, the value of id seems to be inserted as null;
_INSERT INTO a_xxx.failed_jobs(id, connection, queue, payload, exception, failed_at) VALUES ($1, $2, $3, $4, $5, $6)_
Throwing an;
_Illuminate\Database\QueryException SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint_

Migration is as follows;

        Schema::create('a_xxx.failed_jobs', function (Blueprint $table) {
            $table->id('id');
            $table->text('connection');
            $table->text('queue');
            $table->longText('payload');
            $table->longText('exception');
            $table->timestamp('failed_at')->useCurrent();
        });

A temporary solution has been implemented by using another column as primary key and defining id as nullable and adding another column to act as primary key.

      Schema::create('a_xxx.failed_jobs', function (Blueprint $table) {
            $table->id('_id');
            $table->integer('id')->nullable();
            $table->text('connection');
            $table->text('queue');
            $table->longText('payload');
            $table->longText('exception');
            $table->timestamp('failed_at')->useCurrent();
        });

I have looked into the framework specifically at Illuminate\Queue\Failed\DatabaseFailedJobProvider.php:62 which seems consistent with the expected behavior so this could be a problem with our setup. However, since the second migration schema works fine, the issue seems to point to a bug. 

I would greatly appreciate opinions or assistance in debugging further.  

### Steps To Reproduce:

- PostgreSQL 12.3 as Database
- Failed Jobs table with standard migrations schema on one PostgreSQL database and schema called a_xxx.
- a_xxx is defined as a foreign schema to the default database connection (Handled by PostgreSQL, should be transparent for Laravel).
- Run a failing job.

        public function handle()
        {
            throw new \Exception('Job failure testing.');
        }

Thank you in advance for your assistance.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by driesvints** [comment]
@gordongrech we've thus extended our bug fix period til beginning of October but looking at this issue is that this can be asked on a support channel.
