### ISSUE TITLE
Pass parameters to Seeders always null

### ISSUE THREAD

**Issue by AugmentBLU** [laravel/framework#34335]
- Laravel Version: 8.2.0
- PHP Version: 7.3.9
- Database Driver & Version: MySQL 14.14

### Description:
Parameters return null when using `call` or `callSilent` within Seeders. 

Using this example https://github.com/laravel/framework/pull/33737

### Steps To Reproduce:
Create a simple Seed with the following and run `php artisan db:seed`. Dump returns `null`.

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{

    public function run()
    {
        $this->callSilent(UserTableSeeder::class, "Param1", "Param2");

    }
}

class UserTableSeeder extends Seeder {
    public function run($param1 = null, $param2 = null) {
        dd($param1);
    }
}
```

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by taylorotwell** [comment]
This feature felt pretty broken IMO. On next patch you can call `callWith(SeederClass::class, ['param1', 'param2']);`

**Comment by AugmentBLU** [comment]
@taylorotwell Thanks for fixing so soon, look forward to the next release.

**Comment by bobate** [comment]
@taylorotwell 
I'm a noob, running L 8.10.0, and callWith still giving me null. My code:

            $numRounds = 5;
            $this->callWith(RoundSeeder::class, [$numRounds]);

In RoundSeeder:   

    public function run($numRounds = NULL)
    {
        dd($numRounds);     // null ?

If you can point out anything I'm missing, greatly appreciated.
Thanks

**Comment by freestyledork** [comment]
@bobate 
This is probably way late, but using the splat operator you need to pass array keys that will end up becoming the resolved named parameters.  

Using your example, this should work.
```
$this->callWith(RoundSeeder::class, ['numRounds' => 5]);
```
```
public function run($numRounds = NULL)
{
    dd($numRounds);     // 5
    ...
```
