### ISSUE TITLE
Artisan Schema::Dump and Read/Write Connections

### ISSUE THREAD

**Issue by billriess** [laravel/framework#34340]
- Laravel Version: 8.2.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 8.0.19

### Description:
The command `php artisan schema:dump` fails if you have read and write database connections configured in your `config/database.php` file because it's expecting a string for the values and instead gets an array.

### Steps To Reproduce:
Setup read and write connections (https://laravel.com/docs/8.x/database#read-and-write-connections) and then run `php artisan schema:dump`.

**Comment by taylorotwell** [comment]
Fixed in upcoming patch release.
