### ISSUE TITLE
orderByDesc doesn't work properly with PostgreSQL

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#34354]
- Laravel Version: 7.25
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL 12.4

### Description:

When i use `orderByDesc` the results are not sorted in pgsql connection:

```php

MyModel::query()
    ->where('title', 'ilike', "%$input%")
    ->orWhere('original_title', 'ilike', "%$input%")
    ->orderByDesc('votes')
    ->get()
    ->take(20)
    ->values();
```

results:

```
0 => array:14 [
    "id" => 8
    "title" => "some title"
    "original_title" => null
    "year" => null
    "votes" => null
  ]
  1 => array:14 [
    "id" => 106
    "title" => "some title 2"
    "original_title" => null
    "year" => null
    "votes" => null
  ]
```
As you can see it doesnt sort the results by `votes` column and gave me null records, But when i use collection's `sortByDesc` method it world work:

```php

MyModel::query()
    ->where('title', 'ilike', "%$input%")
    ->orWhere('original_title', 'ilike', "%$input%")
    ->get()
    ->sortByDesc('votes')
    ->take(20)
    ->values();
```

results :

```
0 => array:14 [
    "id" => 22853
    "title" => "example title"
    "original_title" => "example title 1"
    "year" => 2011
    "votes" => 462058

  ]
  1 => array:14 [
    "id" => 59981
    "title" => "example title 2"
    "original_title" => "example title 2"
    "year" => 1964
    "votes" => 440306

  ]
```

**Comment by mfn** [comment]
That's the behaviour of Postgres, see https://www.postgresql.org/docs/12/queries-order.html
> The NULLS FIRST and NULLS LAST options can be used to determine whether nulls appear before or after non-null values in the sort ordering. **By default, null values sort as if larger than any non-null value**; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

Best to use raw sorting and add `NULL LAST` for `DESC` if you rather want that.

**Comment by foremtehan** [comment]
@mfn that works, But i have a question, Shouldn't laravel take care of it? I mean we say to laravel "order by desc" but it doesnt.
