### ISSUE TITLE
Make Seeder using old path

### ISSUE THREAD

**Issue by bldcaveman** [laravel/framework#34351]
- Laravel Version: 8.0
- PHP Version: 7.4.8
- Database Driver & Version:

### Description:
When generating a seeder the seeder is put into the old folder "seeds" as opposed to "seeders".
This is contrary to what is stated here: https://laravel.com/docs/8.x/upgrade#seeder-factory-namespaces

**Comment by driesvints** [comment]
Think you haven't done the step listed there to rename the directory. The command first checks if you have the old seeds directory still defined: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Console/Seeds/SeederMakeCommand.php#L71

**Comment by bldcaveman** [comment]
Hiya no I definitely do have that directory

**Comment by bldcaveman** [comment]
Oh I can't have both- okay fair enough

**Comment by bldcaveman** [comment]
Ah no here's the issue:

When I do composer install it says: 

  Could not scan for classes inside "database/seeds" which does not appear to be a file nor a folder

**Comment by driesvints** [comment]
Did you do the steps from this section?

![Screenshot 2020-09-15 at 16 28 15](https://user-images.githubusercontent.com/594614/93223535-76d09380-f770-11ea-9f9b-d2020d517d48.png)

**Comment by bldcaveman** [comment]
That sorted it! Thank you :)
I was under the impression that section was if you didn't use the legacy factories package.
