### ISSUE TITLE
[8.x] Missing required parameters for Route

### ISSUE THREAD

**Issue by barokurniawan** [laravel/framework#34363]
- Laravel Version: 8.1.0
- PHP Version: 7.4.10
- Database Driver & Version: PostgreSQL

### Description:
Cannot generate link or url with function `route()` always return `Missing required parameters`.
Note that the route is not cached.

### Steps To Reproduce:
1. Here is the route code :
```
<?php 
use Illuminate\Support\Facades\Route;
Route::name("blog.")->domain("{blog}.blog.com")->group(function () {
    Route::get("/", [YourController::class, "listPosts"])->name("home");
    Route::get("/{year}/{month}/{slug}.html", [YourController::class, "singlePost"])
        ->name("post");
    Route::get("/about", [YourController::class, "aboutUser"])->name("about");
    Route::get("/assets/{file}", [YourController::class, "assetsHandler"])->name("assets");
});
```
2. You can access it via `php artisan tinker`
```
route('blog.assets', 'test.js');
```
Or 
```
route('blog.assets', ['file' => 'test.js']);
```
Both return the same result.
The error is not only for `blog.assets` route, but also `blog.post` too.

**Comment by rodrigopedra** [comment]
The `{blog}` parameter defined in the `->domain()` call is required for each route in this group.

Try adding it:

~~~php
route('blog.assets', ['file' => 'test.js', 'blog' => 'foo']);
~~~

You will get: `http://foo.blog.com/assets/test.js`

Fro the docs: https://laravel.com/docs/8.x/routing#route-group-subdomain-routing

> Subdomains may be assigned **route parameters** just like route URIs

**Comment by barokurniawan** [comment]
@rodrigopedra you're right. 
Thank you very much.

**Comment by rodrigopedra** [comment]
You're welcome =)
