### ISSUE TITLE
app('router')->getRoutes()->match() - Dosen't work correctly when running on subdirectory

### ISSUE THREAD

**Issue by eckelarsson** [laravel/framework#34362]
- Laravel Version: 8.0.0
- PHP Version: 7.3.22
- Database Driver & Version: MySQL 5.6

### Description:

I'm running Laravel in a subdirectory, so the base of the url is HTTP://www.domain.com/laravel
Was running on a small issue with Livewire returning 404 on ajax request, so did some digging and found where the bottleneck was, and it was this function to get the current route from the url.

`
// $referer = CURRENT_URL
$route = app('router')->getRoutes()->match(
                Request::create($referer, 'GET')
            );
`

And it returned the 404 response. So I did a small hack to confirm, str_replace the /laravel (subdirectory) segment from $referer, and it worked.

### Steps To Reproduce:
Set up an Laravel application in a subdirectory and try the function 
`
// $referer = CURRENT_URL
$route = app('router')->getRoutes()->match(
                Request::create($referer, 'GET')
            );
`

**Comment by rodrigopedra** [comment]
I don't think running a Laravel app from a subdirectory is supported

Docs: https://laravel.com/docs/8.x/installation#directory-configuration

Also some comments from core developers on previous issues:

**Comment by GrahamCampbell** [comment]
> I don't think running a Laravel app from a subdirectory is supported

That's correct. It's not.
