### ISSUE TITLE
[8.x] Route::view() return wrong paramaters bag

### ISSUE THREAD

**Issue by unspokenn** [laravel/framework#34375]
- Laravel Version: 8.3.0
- PHP Version: 7.3.22
- Database Driver & Version: irrelevant

### Description:
After upgrading laravel 7.x to 8.x, im unable to use Route::view () in my project because Route:view() view,data,status,headers keys return inside parameters array. my project check parameters->status using it for another job.Controller inside return view() working as it should.

### Steps To Reproduce:
Routing\Route.php
![image (11)](https://user-images.githubusercontent.com/3756497/93334106-0a679a00-f82d-11ea-91aa-4805ecc2b72b.png)

Route::view()
![image (12)](https://user-images.githubusercontent.com/3756497/93334152-1a7f7980-f82d-11ea-83d8-2913cfab70bb.png)

Controller inside method return view()
![image (13)](https://user-images.githubusercontent.com/3756497/93334189-2e2ae000-f82d-11ea-96fe-852347954bf6.png)

**Comment by rojtjo** [comment]
Could you show the actual route registration?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
