### ISSUE TITLE
Factories with models located in a sub directory of the models directory not discoverable 

### ISSUE THREAD

**Issue by ultrasamad** [laravel/framework#34374]
- Laravel Version: 8.3.0
- PHP Version: 7.4.5
- Database Driver & Version: psql 12 (not relevant though)

### Description:
A new issue reporter here.
I realized when a model is placed in a sub directory of the default models directory eg `App\Models\Discussion\Post.php`, its corresponding factory namespaced under `Database\Factories` is not discoverable.

Factories whose models live in the default models directory however works. 

### Steps To Reproduce:

- Create a fresh laravel 8 project
- Create a model in a sub directory of the default models directory with a corresponding factory 
  `artisan make:model Discussion\\Post -f`
- Try instantiating a post with `Post::factory()->make()`

It throws an error like this:
```
Class 'Database/Factories/Discussion/PostFactory' not found in .../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php on line 623
```

**Comment by taylorotwell** [comment]
Unable to recreate.
