### ISSUE TITLE
Model Factory Not Found When namespace changes

### ISSUE THREAD

**Issue by shoaibayaz** [laravel/framework#34372]
- Laravel Version: 8.3.0
- PHP Version: 7.4.7
- Database Driver & Version: mysql 8.0.0

### Description:
I have install fresh project of laravel 8 and changed my namespace and vendor i am creating user from UserFactory in tinker it says UserFactory Not Found And it searching like:

`
Database\Factories\Namespace\Models\UserFactory::class
`

### Steps To Reproduce:
Install fresh project of laravel
Change namespace App To SomethingElse
Then try to create user from factory

**Comment by taylorotwell** [comment]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/463230/93359621-6c61d880-f808-11ea-928f-af745b2274bd.png">

**Comment by lloricode** [comment]
@shoaibayaz you can you this

```php
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

abstract class BaseFactory extends Factory
{
    public function modelName()
    {
        $resolver = fn(self $factory) => app()->getNamespace().
            'Models\\'.
            str_replace(class_basename($factory), '', str_replace(self::$namespace, '', static::class)).
            Str::replaceLast('Factory', '', class_basename($factory));

        return $this->model ?: $resolver($this);
    }
}

```

then extend all you factory class to this
