### ISSUE TITLE
<x-dynamic-component :component="$comp" :attr="$value"/> passes $value as an escaped string even for objects and collections

### ISSUE THREAD

**Issue by gabrielrf96** [laravel/framework#34380]
- Laravel Version: 8.3.0
- PHP Version: 7.3.22

### Description:

This problem happens when using the new <x-dynamic-component/> Blade component, and passing attributes to it as shown below:

<x-dynamic-component :component:"$component" **:requiredAttr="$value"**/>

As long as $value is a basic type, or an array, this works correctly and passes the attribute to the component constructor.
However, if $value is a Collection, or an instance of a model, this fails. The component, instead of receiving the object, will receive a string representation of said object.

### Steps To Reproduce:

1. Create a component that receives a collection of model instances as a parameter:

```
<?php

namespace App\View\Components\Listings;

use Illuminate\View\Component;

class ItemListing extends Component
{

    public $items;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($items) {
        $this->items = $items;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.listings.item_listing');
    }
}
```

2. Create the component view. The view uses the $items parameter to render a list:

```
<div class="item-listing">
        @foreach ($items as $item)
            <x-resource.items.entry :resource="$resource" :item="$item"/>
        @endforeach
</div>
```

3. In another view, include the component dynamically

```
<x-dynamic-component :component="$listingType" :resource="$resource" :items="$items"/>
{{-- $listingType is set by the controller to 'listings.item-listing', the component que created earlier --}}
```

4. By having followed these steps, an **'Invalid argument supplied for foreach()'** error will be thrown.

5. By dumping the $items variable in the component view, we can see the DynamicComponent has passed the collection as escaped string, and not an object:

```
<div class="item-listing">
        @php dd($items) @enphp {{-- This dumps the value of $items and shows that it has been passed as a string --}}
        @foreach ($items as $item)
            <x-resource.items.entry :resource="$resource" :item="$item"/>
        @endforeach
</div>
```

**Comment by taylorotwell** [comment]
Use 8.4.0.
