### ISSUE TITLE
Unable to define mail theme location other than within vendor/themes

### ISSUE THREAD

**Issue by snapey** [laravel/framework#34391]
- Laravel Version: 8.0.4
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
Sending a notification, we are able to specify a `->theme('name')` but this theme must be in the vendor/mail/html/themes folder for it to be picked up.  We cannot specify that it is in our own views/mail folder. It is therefore also necessary to have published the mail views.

The Markdown.php class includes the following lines;
```
        $theme = Str::contains($this->theme, '::')
            ? $this->theme
            : 'mail::themes.'.$this->theme;
```
which seems to say that if the theme specified contains a hint then use it as-is otherwise apply the `mail::` hint to the name

### Workaround

Register a hint in the app service provider, eg;

```
        $this->loadViewsFrom(resource_path('views/mail'), 'appMail');
```
then specify the theme in the Notification as;
```
        return (new MailMessage)
                    ->theme('appMail::mycorp')
                    ->subject('Your login code for ' . config('app.name'))
                    ->line('Here is your login PassPhrase which is valid for the next 15 minutes')
                    ->line($this->passphrase)
// etc
```
so, specifying a hint causes this path to be used and not the mail:: view path

Should it be possible to specify the theme without the hint?, eg `->theme('mail.mycorp')` ?

**Comment by taylorotwell** [comment]
I think we could change that check to just check if the given view exists first. I will make a patch.
