### ISSUE TITLE
[8.x] Get wrong route parameter when using model binding together with route parameter

### ISSUE THREAD

**Issue by wilzokch** [laravel/framework#34398]
- Laravel Version: 8.2.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
Laravel will return wrong route parameter when using model binding together with route parameter

### Steps To Reproduce:
1. add following code into routes/web.php
`  Route::any('users/{user}/{token}', function(\App\Models\User $user, $token) {
        dd([$user, $token]);
    });
`
  
2. open browser & go to http://localhost:8000/users/1/123
3. expect output with user object id: 1 and token 123
4. actual output will show user object id: 1 and token 1

**Comment by driesvints** [comment]
Works fine for me.
