### ISSUE TITLE
"Nothing to migrate" bug when folder name has [] on it

### ISSUE THREAD

**Issue by seiferxiii** [laravel/framework#34407]
- Laravel Version: 7.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL / MSSQL

### Description:
A bug on laravel migration occurs when your path has "[]" on it causing migration files unable to migrate

### Steps To Reproduce:
- Create a laravel project with [] on path of the project ( example: C:\\[PROJECTS]\new-laravel-project )
- Generate a migration file
- Run php artisan migrate
- Done

**Comment by taylorotwell** [comment]
Hmm, not sure. Feel free to submit a PR or rename your folder.
