### ISSUE TITLE
[8.x] Problem with EmailVerificationRequest

### ISSUE THREAD

**Issue by HelDoRe** [laravel/framework#34408]
Laravel : 8.x
PHP : 7.6.4

I make all from documentation (https://laravel.com/docs/8.x/verification), almost all works fine, but when i click link from email, i have :

**Illuminate\Contracts\Container\BindingResolutionException
Target class [Illuminate\Foundation\Auth\EmailVerificationRequest] does not exist.**

in route/web.php (as documentation says

**use Illuminate\Foundation\Auth\EmailVerificationRequest;
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');**

I dont know what happens.

**Comment by taylorotwell** [comment]
Hasn't been tagged yet. I'm going to this afternoon.
