### ISSUE TITLE
Call to a member function is() on string Collection.php:542

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#34416]
- Laravel Version: 7.28
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL 12.4

### Description:
doc: 
>If the collection contains arrays or objects, you can pass the key of the attributes that you wish to check for duplicate values:

I did this on my model, But when i want to get duplicated titles it throw a error:

```php
Thread::all()->duplicates('title')
```
```
Error : Call to a member function is() on string
\vendor\illuminate\database\Eloquent\Collection.php:542
\vendor\illuminate\support\Collection.php:286
\tests\ExampleTest.php:10
```

**Comment by lagbox** [comment]
It would seem this method on Eloquent Collection is intended for finding duplicate models in a Collection with how the `duplicateComparator` method is defined (to use the `is` method of the Model).

You would have to get a Support Collection from your Eloquent Collection to run `duplicates` how you want.

```php
Thread::all()->toBase()->duplicates('title');
```

**Comment by foremtehan** [comment]
I tried that, But the results are wrong and not duplicated.

**Comment by taylorotwell** [comment]
Appears to be more of a documentation issue.
