### ISSUE TITLE
Type hinting $table, $casts in Model throws error 

### ISSUE THREAD

**Issue by infinite4evr** [laravel/framework#34414]
- Laravel Version: 8.0.3
- PHP Version: 7.4.10
- Database Driver & Version:

### Description:

Php  7.4 added the [support ](https://wiki.php.net/rfc/typed_properties_v2) for type hinting properties in the classes, traits

```
// This should be valid
class Store extends Model
{
    protected array $guarded = ['created_at', 'updated_at'];

    protected array $casts = [
        'description' => 'array',
    ];

    protected array $attributes = [
        'site_id' => '1'
    ];
}
```
I did the same in my model and it throws an error since types are not declared in traits being used by Illuminate\Database\Eloquent\Model namely HasAttributes, GuardsAttributes

### Steps To Reproduce:

Type hint any extended property like $table, $guarded, $casts in the model and it'll throw an error  "Type cannot be defined for $table etc" 

Example : 
```
class Store extends Model
{
    protected array $casts = [
        'description' => 'array',
    ];
}
```

Can something be done for this? I would want to use them since writing phpdoc comments after type hinting is available seems redundant to me ( until and unless I want to be verbose about what the variable actually does ) 

I can code and test for this if required

**Comment by driesvints** [comment]
You can't do that as the parent properties aren't type hinted themselves. Since we still need to support PHP 7.3 we can't modify the Model class. And it is unlikely that we ever will.
