### ISSUE TITLE
syntax error, unexpected in registerBatchServices method

### ISSUE THREAD

**Issue by iiviiahdisa** [laravel/framework#34422]
- Laravel Version: 8.3.0
- PHP Version: 7.4.4
- Database Driver & Version: MySql 5.7.24

### Description:
Hello.
When I call "php artisan" I see the following error due to the extra comma on line 51

### Steps To Reproduce:
`

        $this->app->singleton(DatabaseBatchRepository::class, function ($app) {
            return new DatabaseBatchRepository(
                $app->make(BatchFactory::class),
                $app->make('db')->connection(config('queue.batching.database')),
                config('queue.batching.table', 'job_batches'),
            );
        });
    
`

**Comment by GrahamCampbell** [comment]
This happens whenever your PHP version is less than 7.3.
