### ISSUE TITLE
Validated request parameters return null values.

### ISSUE THREAD

**Issue by gregorip02** [laravel/framework#34428]
- Laravel Version: ^7x || ^8.x
- PHP Version: ^7.2
- Database Driver & Version: MySQL

### Description:

When we have an attribute declared in a database structure similar to the following.

```yaml
articles:
  - id: int
  - title: not null string
  - content: not null string
  - published: not null date default now()
```

We assume that when trying to register a data set which does not have the `published` attribute, the date of the system where our database is running will be assumed.

### Steps To Reproduce:

1. Define our `StoreArticleRequest`
```php
<?php

// ...
class StoreArticleRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required',
            'content' => 'required',
            'published' => 'sometimes|nullable|date'
        ];
    }
}
```

2. Now in our `ArticleController` we try to do the following.

```php
<?php

// ...

class ArticleController extends Controller
{
    public function store(StoreArticleRequest $request)
    {
        $attributes = $request->validated();

        return Article::create($attributes);
    }
}
```
This would work for a request that includes all the attributes evaluated in `StoreArticleRequest`. But if you send a request like the following.

```json
{
  "title": "My title",
  "content": "Hello world",
  "published": null
}
```
The `validated()` method will also include the `published` property, which will try to register as `NULL` raising an SQL exception because it is not a valid value for `DATE`.

**Comment by gregorip02** [comment]
I propose a new method to obtain attributes of the HTTP request validated and containing non-null values.

```php
<?php

// ...
class FormRequest extends Request implements ValidatesWhenResolved
{
    /**
     * Get the filled validated data from the request.
     *
     * @return array
     */
    public function validatedFilled()
    {
        $validated = $this->validated();

        // Exclude nullable attributes
        return array_filter($validated, fn ($value) => !empty($value));
    }
}
```

**Comment by driesvints** [comment]
Just attempt the PR, thanks.
