### ISSUE TITLE
Legacy model factories does not work along new factories

### ISSUE THREAD

**Issue by Lukasz93P** [laravel/framework#34437]
- Laravel Version: 8.3.0
- PHP Version: 7.4
- Database Driver & Version: It's not related to DB.

### Description:
You published package [legacy factories](https://github.com/laravel/legacy-factories), it works as expected but only if we do not use legacy factories along with some new factories. When we use mixed style factories, Factory class tries to redeclare class defined inside new model factories.
### Steps To Reproduce:
Install [legacy factories](https://github.com/laravel/legacy-factories), create one legacy and one new factory, run the test which uses both factories.

I know exactly how to fix this problem, it requires only a few lines of code inside one class in legacy factories package, so I can help with that but I need Your permission for that.

**Comment by driesvints** [comment]
You indeed can't use both at the same time. It's one or the other.

**Comment by driesvints** [comment]
I've sent in a PR to clarify that: https://github.com/laravel/docs/pull/6399

**Comment by Lukasz93P** [comment]
But as I wrote I know how to fix it so why You just closed the issue isntead of allowing to fix that problem @driesvints ?

**Comment by driesvints** [comment]
@Lukasz93P feel free to send in a PR if you like 👍

**Comment by Lukasz93P** [comment]
But I cant push new brach to repo of Legacy factories, permissions do not allow me to do that @driesvints

**Comment by driesvints** [comment]
You need to fork the repo.

**Comment by driesvints** [comment]
@Lukasz93P turns out you should be able to use them at the same time. Can you please post very specific steps to reproduce or a test repo which reproduces the problem on a fresh laravel install? Preferable commit your custom changes separately from the base laravel skeleton.

**Comment by Lukasz93P** [comment]
@driesvints as I wrote the problem, occurs because classes declared in new factories are redeclared by the legacy factory, which raises an error.

Will it be a good solution if I would give You a link to merge the request with solution inside my forked repo?

**Comment by driesvints** [comment]
We've looked into this further and are gonna try to update upgrade docs to be more clear about this particularly use case. Thanks.

https://github.com/laravel/docs/pull/6401

**Comment by Lukasz93P** [comment]
@driesvints thanks, now it works ;)

**Comment by driesvints** [comment]
@Lukasz93P awesome. Thanks for your issue 👍

**Comment by hackel** [comment]
@Lukasz93P Unfortunately your solution fails when extending a base class that isn't named "Factory". e.g.
`class MyChildFactory extends BaseFactory`
The above php file will get loaded twice and generate an error.

Wouldn't it be enough to simply check that it's a class and remove "extends Factory" from the regex?  It's already making a lot of assumptions.  Otherwise something like this is working for me, but feels super brittle:
```php
    protected function isLegacyFactory(string $path)
    {
        $file = file_get_contents($path);

        if (!(preg_match("/class\s([A-Z+a-z]+)[ \n]/", $file, $matches))) {
            return true;
        }

        $class = $matches[1];

        if (preg_match('/namespace\s([A-Z+a-z\\\\]+);/', $file, $matches)) {
            $class = "{$matches[1]}\\$class";
        }

        return ! is_a($class, \Illuminate\Database\Eloquent\Factories\Factory::class, true);
    }
```
