### ISSUE TITLE
Defining a route using a callable with the 'uses' key in the action

### ISSUE THREAD

**Issue by lagbox** [laravel/framework#34451]
- Laravel Version: 8.5.0
- PHP Version: 7.3.11
- Database Driver & Version: N/A

### Description:

It would seem we can not use a callable when using the 'uses' key of the action array for a route. The route will get defined (though `artisan route:list` will list it as a `Closure`) but when dispatched it will cause an error:

`ReflectionFunction::__construct() expects parameter 1 to be string, array given `

This is coming from the `fromAction` method of `Illuminate\Routing\RouteSignatureParameters`:

```php
public static function fromAction(array $action, $subClass = null)
{
    $parameters = is_string($action['uses'])
                    ? static::fromClassMethodString($action['uses'])
                    : (new ReflectionFunction($action['uses']))->getParameters(); // <--------
     ...
```
Using a string or closure for `uses` works fine.

### Steps To Reproduce:

Define a route using the array syntax for the 'action':

```php
Route::get('test', ['uses' => [App\Http\Controllers\TestController::class, 'test']]);
```
Hit that route.

### Question

Are we not supposed to be able to use the callable syntax with the array syntax for the action?

**Comment by driesvints** [comment]
No. That syntax isn't supported. `uses` refers to an action which always needs to be a callable or `Controller@method` string.

**Comment by lagbox** [comment]
@driesvints `[Controller, method]` is a callable

**Comment by driesvints** [comment]
Sorry, I meant a closure.

**Comment by lagbox** [comment]
I don't see why we shouldn't be able to use that, but okay.

**Comment by driesvints** [comment]
@lagbox I'm just saying it's not possible now but I agree with you that we could maybe make this happen. If you're up for it, try a PR?

**Comment by lagbox** [comment]
I can give it a go, thank you.

**Comment by lagbox** [comment]
Alright seems like a change only needs to be made in one place in `Illuminate\Routing\RouteAction@parse`:

```php
    ...
    
    if (is_callable($action, true)) {
        ...
    }

    if (isset($action['uses']) && is_callable($action['uses'])) {
        return [
            'uses' => ($parts = $action['uses'])[0] .'@'. $parts[1],
            'controller' => $parts[0] .'@'. $parts[1],
        ];
    }
```

I will check out the tests to see what to add.
