### ISSUE TITLE
Can't dynamically call the same anonymous component twice, with different attributes each time

### ISSUE THREAD

**Issue by stancl** [laravel/framework#34469]
- Laravel Version: v8.6.0
- PHP Version: 7.4.0
- Database Driver & Version: irrelevant

### Description:

```html
{{-- Works: --}}
<x-foo value="abc" a="b" />
<x-foo value="abc" />

{{-- Doesn't work: --}}
<x-dynamic-component component="foo" value="abc" a="b" />
<x-dynamic-component component="foo" value="xyz" />
```

### Steps To Reproduce:

Create a basic **anonymous** component named `foo`. It doesn't have to do anything, just make it an empty div.

Create another component that uses the code above.

The issue is that the **dynamic component call for `foo` gets compiled and cached**. Even though the call is different each time.

So the first call assumes an `$a` variable existing, but this variable is not present in the second call.

Hence, an exception like this is thrown:

```
Undefined variable: a (View: /Users/samuel/Projects/dynamic-component-wire/storage/framework/views/a553ad954f8954104deb899637465b63312af2fd.blade.php) (View: /Users/samuel/Projects/dynamic-component-wire/storage/framework/views/a553ad954f8954104deb899637465b63312af2fd.blade.php)
```

### Debugging

When you open `a553ad954f8954104deb899637465b63312af2fd.blade.php`, you see:

```php
<?php extract(collect($attributes->getAttributes())->mapWithKeys(function ($value, $key) { return [Illuminate\Support\Str::camel(str_replace([':', '.'], ' ', $key)) => $value]; })->all(), EXTR_SKIP); ?>
@props(['value','a'])
<x-foo :value="$value" :a="$a" >

{{ $slot ?? "" }}
</x-foo>
```

This is the **compiled & cached version of the dynamic `x-foo` call**. The issue is that the same file is used for both calls, even though they're different.

This can be proved by adding a `dump()` statement above the `@props` line:
```php
<?php dump(isset($a)); ?>
```

This results in:

![Screen Shot 2020-09-22 at 20 42 41](https://user-images.githubusercontent.com/33033094/93923813-2c24bd80-fd14-11ea-8f1a-a5908b90c6c9.png)

### Expected behavior

Each dynamic call can be different, therefore we shouldn't reuse compiled views for them.

Each of those `<x-dynamic-component component="foo" ... />` calls should have a separate compiled file.

**Comment by taylorotwell** [comment]
Probably will need a PR. Not sure how much time I have to keep looking into dynamic components.

**Comment by stancl** [comment]
Sure, appreciate the bug fixes so far.

I've spent a lot of time in Blade internals at this point do I think I should be able to do this.

**Comment by stancl** [comment]
This fixes it:

```diff
protected function bindings(string $class)
{
-    if (! isset(static::$bindings[$class])) {
        [$data, $attributes] = $this->compiler()->partitionDataAndAttributes($class, $this->attributes->getAttributes());

-      static::$bindings[$class] = array_keys($data->all());
+       return array_keys($data->all());
-    }

-    return static::$bindings[$class];
}
```

The `$bindings` static property on `DynamicComponent` caches the parsed bindings by component name.

So the `DynamicComponent::$bindings` array looks like:

```php
'components.foo' => [
  0 => "value"
  1 => "a"
],
```

And the next time `DynamicComponent` is calling `components.foo`, it uses this cached version instead of parsing the bindings again.

I will submit a PR, but before I do, could you please tell me if you know whether there's a reason for this caching? Or is that just a performance thing?

Thank you.

**Comment by taylorotwell** [comment]
Probably just performance. I guess we will have to ditch that.
