### ISSUE TITLE
ServeCommand doesn't respect environment variables

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#34472]
- Laravel Version: 8.5.0
- PHP Version: 7.4.10
- Database Driver & Version:

### Description:
I've upgraded two separate Laravel projects that use Dusk to 8.x, they use different CIs - one on CircleCI and the other on HerokuCI. After the upgrade the Dusk tests no longer function (while the rest of the suite remains green).
I was able to uncover the error from one of the logs on CircleCI:

```
[2020-09-23 09:35:29] testing.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /home/circleci/laravel/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
```

I think previously ServeCommand would respect `$_ENV` variables provided by the CI tool but after 8.x it's now expecting to use environment variables from a `.env*` file now instead.

So this problem is resolvable on CircleCI because I can tell it what the database credentials are, and put them in the `.env.testing` file to use. However, on a platform like HerokuCI the database credentials (and Redis credentials) are always dynamic and made available as actual environment variables.

Basically - this is a breaking change to 8.x that the ServeCommand won't load environment variables from the environment, where it did on 7.x. This is generally recoverable except in cases that you need something from the environment (like Heroku add-on configurations).

Curious to hear your thoughts here, and whether this is something that is fixable or will remain as-is. I'm sure there are other situations where this will cause problems, but it appears to make Laravel Dusk incompatible with HerokuCI.

Relevant issue: #34217, but the patch is around loading the correct `.env` file rather than loading actual environment variables.

### Steps To Reproduce:

A minimal test reproduction is to create a fresh Laravel app without an `.env` and attempt to set environment variables locally.

```
export APP_ENV=local
export APP_KEY=base64:5Laaaa9GN7PfNv4uRf4iAyJ/Nn/X+KNGsjbAGytLoEw=
php artisan serve
```

The app won't run because it won't have access to the `APP_KEY`.

**Comment by taylorotwell** [comment]
Are you able to make a PR?
