### ISSUE TITLE
Not able to load routes from custom routes file

### ISSUE THREAD

**Issue by harishdurga** [laravel/framework#34478]
- Laravel Version: 8.5.0
- PHP Version: 7.4.10
- Database Driver & Version: Mysql & 8

### Description:
Not able to load routes from custom routes file. In RouterServiceProvider.php within the `$this->routes` i am trying to load routes from a different route file. But i am getting 404 not found page. Also i changed the prefix `api` to `apii` to check if the changes are reflecting but still the api/* routes are working. I cleared the route cache,config and application cache. But still it is not working.
```php
$this->routes(function () {
            Route::middleware('web')
                ->group(base_path('routes/web.php'));
            
            Route::prefix('api/v1')
                ->middleware('api')
                ->middleware('api_version:v1')
                ->namespace("{$this->apiNamespace}\V1")
                ->group(base_path('routes/api_v1.php'));
            
            Route::prefix('api')
                ->middleware('api')
                ->group(base_path('routes/api.php'));
            
                
        });
```
the `routes/api_v1.php` file contains
```php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::get('test', function () {
    return response()->json(['message'=>'Hello']);
});
```
I tried to visit the url `https://my-app.test/api/v1/test` the i got
![Screenshot from 2020-09-23 10-06-00](https://user-images.githubusercontent.com/10380630/93967452-d3d9d400-fd84-11ea-9e78-78525190f71e.png)

### Steps To Reproduce:

- Create a new routes file
- Add the new file to `$this->routes` in the `RouteServiceProvider.php` file.

**Comment by lk77** [comment]
Hello,

you have an issue somewhere, we have api.php / apiv2.php and it works fine.

**Comment by harishdurga** [comment]
Sorry, it is my mistake. I have an issue with one of my middlewares and the routes not loading from the group.
