### ISSUE TITLE
  Call to undefined method App\Models\Dir::factory()

### ISSUE THREAD

**Issue by Parsa237** [laravel/framework#34484]
- Laravel Version: 8.2.0

### Description:

I am currently making a test. However, everytime I run it I get the following error:   `Call to undefined method App\Models\Dir:factory()` I do not know why I get this. I also am doing `use App/Models/Dir` but I still get this error. How can I solve this?

Error:

`BadMethodCallException Call to undefined method App\Models\Dir::factory()`

**Comment by lagbox** [comment]
This seems like a question for the forums since this is support. Does your `App\Models\Dir` Model use the `HasFactory` trait?

**Comment by Parsa237** [comment]
Hi, yes it does.

`use Illuminate\Database\Eloquent\Factories\HasFactory;`

**Comment by lagbox** [comment]
Just having that at the top of the file does not mean that your model is using that trait. Is there a `use HasFactory;` statement inside the class definition?

**Comment by Parsa237** [comment]
No, there is now a `use HasFactory` at the top of of `class dir`. I know have the following error: `  Class 'Database\Factories\AssortmentFactory' not found`

**Comment by lagbox** [comment]
This is support, not a bug. You can take this to one of the forums like laracasts or laravel.io and ask.

**Comment by Parsa237** [comment]
I solved it. Thanks for the help
