### ISSUE TITLE
Factory state only run once with count after upgrading to laravel 8

### ISSUE THREAD

**Issue by EmielSchmeink** [laravel/framework#34493]
- Laravel Version: 8.6.0
- PHP Version: 7.4.3
- Database Driver & Version: PostgreSQL 12.4

### Description:
When trying to make multiple model instances using `Class::factory()->stateFunction()->count(50)->make();`, it seems that the state function is only run once, even though this was not the case in laravel 7. The state function uses the faker to create a random value for each instance, so now all instances have the same value.

### Steps To Reproduce:
1. create a model
2. create a factory for the model
3. add a state function to the factory
4. make sure that the state function sets a random value
5. call the factory using a count of more than one
6. observe all instances have the same value for the random state

**Comment by taylorotwell** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/463230/94032626-bf4a0b80-fd85-11ea-825e-d5e59cf48b13.png">

Works fine for me... 

User::factory()->count(10)->withRandomVotes()->create();

**Comment by EmielSchmeink** [comment]
I forgot the closure :upside_down_face:
