### ISSUE TITLE
Http client not applying middleware when using Http::fake()

### ISSUE THREAD

**Issue by badams** [laravel/framework#34505]
- Laravel Version: 8.2.0
- PHP Version: 7.4.6
- Guzzle Version:  7.0.1

### Description: 

If you provide middleware on your Http client it will never be invoked when using `Http::fake()`

### Steps To Reproduce:

```php
class HttpClientMiddlewareTest extends TestCase
{
    public function test_it_applies_middleware_when_no_fake()
    {
        $middleware = Middleware::mapResponse(function (ResponseInterface $response) {
            return $response->withHeader('X-Foo', 'bar');
        });

        $response = Http::asForm()->withMiddleware($middleware)->get('http://google.com');
        $this->assertEquals('bar', $response->header('X-Foo'));
    }

    public function test_it_doesn_not_apply_middleware_when_fake()
    {
        $middleware = Middleware::mapResponse(function (ResponseInterface $response) {
            return $response->withHeader('X-Foo', 'bar');
        });

        Http::fake();

        $response = Http::asForm()->withMiddleware($middleware)->get('http://google.com');
        $this->assertEmpty($response->header('X-Foo'));
    }
}
```

![Screen Shot 2020-09-24 at 2 45 56 PM](https://user-images.githubusercontent.com/340715/94094874-b3894280-fe74-11ea-9987-af7c58b4cde5.png)

As you can see the middleware is not applied in the second test

* Add middleware to client `$client->withMiddleware(...)`
* Call `Http::fake()`
* Assert Middleware applied

**Comment by driesvints** [comment]
I'm actually not sure about this one myself. Will need input from @taylorotwell here.

**Comment by taylorotwell** [comment]
I'm not sure I would expect any middleware to run at all, so to me personally this is expected behavior. If you're faking the HTTP client you are going to specify exactly what responses should returned.

**Comment by badams** [comment]
@taylorotwell @driesvints I'd really appreciate if you can reconsider this, without this working its completely impossible to test that middleware is configured and working correctly.

Perhaps my example of mutating the response was not great - this was for simplicity sake and was lifted directly from the [guzzle docs](http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware).

I have a number of middleware that perform a range of actions such as:

* Validating JSON response structure against a OAS/Swagger spec (If its invalid an exception should be thrown)
* Caching responses based on provided options
* Transforming responses to appropriate exceptions (eg `ValidationException::withMessages(...)`, `AuthorizationException` etc)

Without the ability to test my middleware, the `withMiddleware(...)` method is not useful to me and I've had to opt for a more procedural approach or use Guzzle directly, but honestly I much prefer the interface for `Http` and `Http:fake()`

I'm happy to work on a PR for this if needed.

**Comment by driesvints** [comment]
We're probably not going to reconsider this, sorry.

**Comment by eduarguz** [comment]
So, I also spent some time in this... Then found this issue. 

I think there is another good use case for this. We, very often, need to log what is sent to an api and what is received.

When testing, using `Mail::fake()`,  Testing this logger will not be possible

```php 
$response = Http::withMiddleware(Middleware::log(
            app(LogManager::class)->channel(),
            new MessageFormatter()
        ))->{$method}($url, $payload);
```

just in case +1 on this 

Thanks
