### ISSUE TITLE
Database seeders in wrong directory

### ISSUE THREAD

**Issue by farhanianz** [laravel/framework#34500]
- Laravel Version: 8.6.x
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 14.14
- Composer version: 1.8.6

### Description:
**php artisan make:seeder & vendor:publish** (only tested by publishing from a 3rd party package currently) places the seeders in the **"database/seeds"** directory while the docs say make:seeder will generate the seeder in the **"database/seeders"** directory. (Ref: https://laravel.com/docs/8.x/seeding#writing-seeders )

While calling the seeders from seeds directory, it fails (ran composer autoload-dump with no luck).
**Output:**
_Target class [Database\Seeders\TestSeeder] does not exist._
_at D:\Codes\www\project-x\vendor\laravel\framework\src\Illuminate\Container\Container.php:811_ 

![screenshot](https://user-images.githubusercontent.com/3446817/94048421-4f736980-fdf5-11ea-8104-a40a91e3dbee.png)

Moving the seeders from **"database/seeds"** directory to **"database/seeders"** directory solves the issue.

### Steps To Reproduce:

```
    laravel new SeederTest --jet --stack=livewire
    php artisan make:seeder TestSeeder
    php artisan migrate:fresh --seed
```
Call the seeder from DatabaseSeeder.php

```php
$this->call([
            TestSeeder::class,
        ]);

```

**Comment by taylorotwell** [comment]
If you're using vendor:publish, the package decides where to publish the seeders.

**Comment by farhanianz** [comment]
I understand the package decides vendor:publish, but I'm facing the issue with make:seeder as well.

**Comment by farhanianz** [comment]
Well, IDK what went wrong, but I couldn't reproduce the issue with a fresh laravel installation which I thought I would 😕 (I should have tried first, sorry..). A fresh Laravel 8.6.0 is working perfectly. Perhaps I'm having the issue because of something else.

**Comment by yarkm13** [comment]
It seems that if you have both `database/seeders` and `database/seeds` directories `php artisan make:seeder UserSeeder` will place `UserSeeder.php` file to `seeds` but with incorrect `namespace Database\Seeders;`. 

And it's totally an issue because you can't use it in default `database/DatabaseSeeder` as docs say `
