### ISSUE TITLE
MethodNotAllowedHttpException The GET method is not supported for this route. Supported methods: HEAD.

### ISSUE THREAD

**Issue by aavinseth** [laravel/framework#34512]
- Laravel Version: 8.6.0
- PHP Version: 7.3.5
- Database Driver & Version:

### Description:  MethodNotAllowedHttpException The GET method is not supported for this route. Supported methods: HEAD. error comes after running command php artisan route:cache on default page for first time

PFA below link for the error screencast

https://streamable.com/dfq7lw

### Steps To Reproduce:
1.  composer create-project --prefer-dist laravel/laravel blog
2. Run project localhost/blog/public
3. Run command php artisan route:cache
4. Run project localhost/blog/public error will come (The GET method is not supported for this route. Supported methods: HEAD.)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. 

You can post support questions on our discussions tab instead so I'm moving it over there. I won't be able to help you out personally but others who are watching this repository can help you out.

Alternatively, you can post this question on one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
