### ISSUE TITLE
laravel route was not detected after enabling php artisan optimize

### ISSUE THREAD

**Issue by Naravyb** [laravel/framework#34524]
hello, I want to report anomalies when using laravel, actually this happened in version 5 too.

So, when I finish installing laravel. i am trying to use artisan optimize php to try cleaning. Then I tried to write a route, it worked fine at first .. then when I edited this route, a problem occurred. At first I created this route with the GET method, then when I changed POST it didn't change automatically. but when I clear route cache its okay. What happened exactly?

this code and php artisan route:list --name="change-lang" before i change to POST method
![Screenshot from 2020-09-24 23-52-01](https://user-images.githubusercontent.com/30528814/94176568-7d72af80-fec2-11ea-8928-3eb92d5cbad9.png)
![Screenshot from 2020-09-24 23-59-43](https://user-images.githubusercontent.com/30528814/94176596-86638100-fec2-11ea-9e0d-d95101409d79.png)

this code and php artisan route:list --name="change-lang" after i change to POST method
![Screenshot from 2020-09-25 00-01-36](https://user-images.githubusercontent.com/30528814/94176680-a2ffb900-fec2-11ea-9a7a-a4542509bfe7.png)
nothing changes.
I know with just a php artisan route: this cache can return to normal, but if it's not automatic it will make this even more difficult. 
so how to fix this? thank u

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Naravyb** [comment]
oke thank u very much.
