### ISSUE TITLE
actingAs testing method overrides the default guard

### ISSUE THREAD

**Issue by netpok** [laravel/framework#34549]
- Laravel Version: 6.x+

### Description:
The `actingAs` testing method overrides the default guard, this results in tests that pass when they should not.

### Steps To Reproduce:
We had an endpoint which displays different content when the user is logged in or not so we could not use the auth middleware which sets the guard upon user checking.

example controller:
```php
public function example(Request $request)
{
    $user = request()->user() // it should be request()->user('other-guard');
    if ($user) {
        return view('authenticated-content', ['user' => $user]);
    }

    return view('guest-content');
}
```

corresponding test:
```php
public function example_test()
{
    $user = factory...; // the usual
    $this->actingAs($user. 'other-guard');

    $response = $this->get('endpoint');

    $response->assertViewHas('user', $user);
}
```

This test will pass because of [this line](https://github.com/laravel/framework/blob/2ec773802f75c20926a27b8b308b3ea2f13b8d7c/src/Illuminate/Foundation/Testing/Concerns/InteractsWithAuthentication.php#L36) while in the real world it will just show the guest content to the authenticated user.

**Comment by driesvints** [comment]
Are you wrapping your api routes in the correct guard?

```
     Route::middleware('auth:api')->get('/' function () {
         return 'Ok';
     })
```

**Comment by netpok** [comment]
As I wrote it needs to display different content based on the login state, if it's behind the auth middleware it will set the correct guard however it will also redirect the user to the login page instead of displaying the guest content.

**Comment by taylorotwell** [comment]
We can't remove this line as that would be pretty breaking. If you want your code to always pull from a specific guard you can pass the guard to the $request->user() method.

**Comment by netpok** [comment]
Yeah, that's what I was talking about the test should have failed just like in the real environment.

**Comment by kwarnkham** [comment]
I have a get route protected by middleware 'auth:merchant.
I do have merchant guard configured in auth.php.

But when I test with $this->actingAs method, both 'user' and 'merchant' are passing the test.
I'm expecting the normal user to fail the test.
