### ISSUE TITLE
eloquent model paginate throw sql error

### ISSUE THREAD

**Issue by vasymus** [laravel/framework#34559]
- Laravel Version: 8.6.0
- PHP Version: 7.4.10
- Database Driver & Version: InnoDB 5.7.30

### Description:
when call `SomeEloquentModel::query()->paginate(null, null);` mysql exception is thrown
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from `ac_symbols` limit 15 offset 0' at line 1 (SQL: select from `ac_symbols` limit 15 offset 0)`
or similar
The point is `select from` without asterisk.

### Steps To Reproduce:
1. Create any eloquent model, for example, User
2. Call in any controller `User::query()->paginate(null, null)`

**Comment by dkulyk** [comment]
```php
public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
```
You are selecting `null` columns?

**Comment by vasymus** [comment]
> ```
> public function paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
> ```
> 
> You are selecting `null` columns?

I understand, but the point is to add some is_null($columns) check.
