### ISSUE TITLE
Sintax error on BusServiceProvider

### ISSUE THREAD

**Issue by oricis** [laravel/framework#34552]
- Laravel Version: 8.6.0
- PHP Version: 7.4.10
- Database Driver & Version: MySql
- Running on Ubuntu 18.04

### Description:
 Sintax error on class: Illuminate\Bus\BusServiceProvider, line: 50

`config('queue.batching.table', 'job_batches'),`

to fix replace by:

`config('queue.batching.table', 'job_batches')`

### Steps To Reproduce:
- Install Laravel + Jetstream (livewire) with composer
- Open the app

**Comment by fragkp** [comment]
Similar problem like this: https://github.com/laravel/framework/pull/34435

Your PHP Version is not correct.
