### ISSUE TITLE
Mailable::mailer() ignored

### ISSUE THREAD

**Issue by MartinW2012** [laravel/framework#34561]
- Laravel Version: 7.20.0
- PHP Version: 7.3.10
- Database Driver & Version: n/a

### Description:

Mailable has a mailer() method that is supposed to set the mailer that will be used to send the message.

However the default mailer is always used.

### Steps To Reproduce:

Create the following Mailable class:
```php
use Illuminate\Mail\Mailable;
use Illuminate\Bus\Queueable;

class TestEmail extends Mailable
{
	use Queueable;

	public function __construct()
	{
	}

	public function build()
	{
		$this->from('sender@gmail.com', 'Test Sender');
		$this->subject('This is a test');
		$this->html('<p>This is a test - ignore at your peril</p><p>Let me know if you have any questions ...</p>');
		return $this;
	}
}
```

Now try to send an email using the default mailer:
```php
Mail::to('test@gmail.com')->queue(new TestEmail);
```
This works fine, the email is sent via the default emailer.

However if you try sending with a specific mailer:
```php
Mail::mailer('postmark')->to('test@gmail.com')->send(new TestEmail);
```
it does not send via the "postmark" mailer, it still sends via the default mailer.

**Comment by driesvints** [comment]
Works just fine for me.

**Comment by MartinW2012** [comment]
> Works just fine for me.

Not for me, do you have the same version of Laravel as me? What do you have in your "vendor" directory, do you have SwiftMailer which is the only non-Laravel entity I have that works with any sort of "mailer"?

**Comment by MartinW2012** [comment]
In case anyone has the same problem and comes here when they do a google search ...

The problem I had was that I originally had Laravel v6 and when I updated to version 7 it left my "config/mail.php" file unchanged.

Unfortunately however, it appears that the "mailer()" function only works if you have the new style "config/mail.php" file - ie your file MUST have 'default' instead of 'driver' and it must also have 'mailers' configuring all the different mailers.

**Comment by netbbe** [comment]
> In case anyone has the same problem and comes here when they do a google search ...
> 
> The problem I had was that I originally had Laravel v6 and when I updated to version 7 it left my "config/mail.php" file unchanged.
> 
> Unfortunately however, it appears that the "mailer()" function only works if you have the new style "config/mail.php" file - ie your file MUST have 'default' instead of 'driver' and it must also have 'mailers' configuring all the different mailers.

Thanks for posting this. It helped me solve this problem in 2025 after many hours of searching.
