### ISSUE TITLE
Container implementation not compliant to PSR-11

### ISSUE THREAD

**Issue by fetzi** [laravel/framework#34589]
- Laravel Version: 8.7.1
- PHP Version: 7.4
- Database Driver & Version: -

### Description:
According to the [PSR-11 specification](https://www.php-fig.org/psr/psr-11/#112-reading-from-a-container) the `get` method of the Container MUST throw an exception based on `NotFoundExceptionInterface`, when `has` returns false. This is not the case when autowiring is used.

### Steps To Reproduce:
Create a class called `TestClass` without any content and add the following code inside of a Controller:

```php
$container = new Container();

$has = $container->has(TestClass::class);
$instance = $container->get(TestClass::class);

dd($has, $instance);
```

this code will output `false` and the created instance of the class. This behavior is not compliant to PSR-11.

**Comment by sergiy-petrov** [comment]
TestClass::class is actually known to the container. If you try $contaier->get('some_name'); you will get "EntryNotFoundException" exception

**Comment by fetzi** [comment]
If TestClass is known to the container shouldn't `has` return `true` then? And btw. I'm instantiating a new instance of the container before without any bindings.

**Comment by taylorotwell** [comment]
I'm more concerned about general DX vs. satisfying PSR-11. The Laravel container can resolve arbitrary concrete classes even if they are not registered in the container.

**Comment by fetzi** [comment]
I totally understand that but I think `has` should also reflect this possibility and it would also ensure the compatibility with the PSR.
It would be an improvement for DX and it wouldn't downgrade it.
