### ISSUE TITLE
artisan schema:dump error

### ISSUE THREAD

**Issue by pendolf** [laravel/framework#34592]
- Laravel Version: 8.6.0
- PHP Version: 7.3.22
- Database Driver & Version: 
mysqldump  Ver 10.16 Distrib 10.1.45-MariaDB, for debian-linux-gnu (x86_64)
mysql 8.0.20

### Description:

When i run `php artisan schema:dump` it returns followed error:

```bash
mysqldump: unknown variable 'set-gtid-purged=OFF'
[2020-09-30 05:29:36] local.ERROR: The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.
```

### Steps To Reproduce:

I am using `php:7.3-apache-stretch` docker image and install default `mysql-client` with apt.

**Comment by vladislavtkachenko** [comment]
https://github.com/laravel/framework/issues/34280

**Comment by yarbala** [comment]
I have the same error, in Alpine linux. It comes from mariadb client, because it is default on alpine. 

`mysqldump  Ver 10.17 Distrib 10.4.13-MariaDB, for Linux (x86_64)`

In my opinion it is no problem to remove this option. In documentation of original mysqlclient it is:

**Comment by GrahamCampbell** [comment]
I think this might have been fixed in the very latest release. Can you upgrade?

**Comment by taylorotwell** [comment]
If you have a fix please submit a PR. I do not plan to spend anymore time on various mysql client issues with schema:dump.

**Comment by yarbala** [comment]
It is not laravel bug. In my case - client is maria db, but DB is MySQL. When you install mysql client on Alpine linux, it uses mariadb client instead. So code:

\Illuminate\Database\Schema\MySqlSchemaState::baseDumpCommand
`$gtidPurged = $this->connection->isMaria() ? '' : '--set-gtid-purged=OFF';`

not works

**Comment by pendolf** [comment]
@yarbala Yea, I understand it. And I don't say what is a bug. But the given command don't give me a choice to choose any options. Moreover the GTID option is for servers that use GTID-based replication, it's not enabled by default in mysql 5.6, 5.7, 8.0, so I don't understand why this `--set-gtid-purged=OFF` should be included in mysqldump command.
