### ISSUE TITLE
required_with rule is ignored, field not validated

### ISSUE THREAD

**Issue by xorock** [laravel/framework#34594]
- Laravel Version: 8.7.1
- PHP Version: 7.3

### Description:
I have simple invocable controller `public function __invoke(ListInvoicesRequest $request)` with ListInvoicesRequest which extends FormRequest. Rules are as follows:

```php
public function rules()
    {
        return [
            'sellerId' => 'sometimes|required|integer',
            'productId' => 'sometimes|required|integer',
            'barcode' => 'sometimes|required',
            'productName' => 'sometimes|required',
            'serialNumber' => 'required_with:productId,barcode,productName',
            'expirationDate' => 'required_with:productId,barcode,productName',
        ];
    }
```

Query string: /api/invoices/listInvoices?sellerId=1234&serialNumber=test, /api/invoices/listInvoices?sellerId=1234&productId=123

No matter what data I send and whether I keep `sometimes` rule in `productId`, `productName`, `barcode` or not, rules for `serialNumber` and `expirationDate` are ignored and form passes validation.

**Comment by lk77** [comment]
Hello,

get parameters are not subject to validation by default,
you should override all() method and include them if you want.

**Comment by xorock** [comment]
How's that? If I remove sometimes from sellerId it's validated:

```json
{
    "message": "The given data was invalid.",
    "errors": {
        "sellerId": [
            "Pole seller id jest wymagane."
        ]
    }
}
```

I've changed method to POST and still fields are skipped.

**Comment by xorock** [comment]
Ok, thank You for explanation.

**Comment by rodrigopedra** [comment]
Another option is overriding your `FormRequest`'s `prepareForValidation` and add any additional data you want to validate. 

There is an example in the docs about it:

https://laravel.com/docs/8.x/validation#prepare-input-for-validation

**Comment by xorock** [comment]
One more question. According to https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Http/FormRequest.php#L117 -> https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Concerns/InteractsWithInput.php#L267 all data should be validated. Other GET parameters like sellerId are validated.

**Comment by rodrigopedra** [comment]
@xorock 

I just tested and it works as expected.

I created a fresh Laravel 8 project and on its `./routes/web.php` I added the following:

~~~php
<?php

use Illuminate\Support\Facades\Route;

class MyRequest extends \Illuminate\Foundation\Http\FormRequest
{
    public function rules()
    {
        return [
            'sellerId' => 'sometimes|required|integer',
            'productId' => 'sometimes|required|integer',
            'barcode' => 'sometimes|required',
            'productName' => 'sometimes|required',
            'serialNumber' => 'required_with:productId,barcode,productName',
            'expirationDate' => 'required_with:productId,barcode,productName',
        ];
    }

    protected function failedValidation(\Illuminate\Contracts\Validation\Validator $validator)
    {
        \dd($validator->getMessageBag()->getMessages());
    }
}

Route::get('test', function (MyRequest $request) {
    return $request->all();
});
~~~

Then I ran `php artisan serve` and navigated to `http://127.0.0.1:8000/test?sellerId=1234&productId=123`

And got the following output (from the `dd` call inside the `failedValidation` method):

~~~
array:2 [▼
  "serialNumber" => array:1 [▼
    0 => "The serial number field is required when product id / barcode / product name is present."
  ]
  "expirationDate" => array:1 [▼
    0 => "The expiration date field is required when product id / barcode / product name is present."
  ]
]
~~~

So it might be something else that is causing the unexpected behavior.

Note that, by default when failing a validation the `FormRequest` will navigate back to the previous page with the errors messages on the session.
