### ISSUE TITLE
Http::get('URL')->throw() will now throw "Argument 0 not passed to function"

### ISSUE THREAD

**Issue by yateric** [laravel/framework#34591]
- Laravel Version: 8.7.1
- PHP Version: 7.4.10
- Database Driver & Version: Not related

### Description:
```
// framework/src/Illuminate/Http/Client/Response.php

public function throw()
{
    $callback = func_get_arg(0);

    if ($this->serverError() || $this->clientError()) {
        if ($callback && is_callable($callback)) {
            $callback($this, $exception = new RequestException($this));
        }

        throw $exception;
    }

    return $this;
}
```
It will throw `Argument 0 not passed to function` if no argument is passed.

### Steps To Reproduce:
```
Http::get('https://www.laravel.com')->throw()->body();
```
This code will throw the `Argument 0 not passed to function` in Laravel 8.7.1

**Comment by MiniCodeMonkey** [comment]
Thanks for reporting this. I also posted some details about it here: https://github.com/laravel/framework/commit/d034e2c55c6502fa0c2bebb6cbf99c5e685beaa5#r42849328

**Comment by MiniCodeMonkey** [comment]
Any reason not to do `public function throw($callback = null)` instead of using `func_get_arg(0)`?

**Comment by rodrigopedra** [comment]
@MiniCodeMonkey , changing the method signature would be a breaking change for users that are extending this class, and as breaking change it would only be released on Laravel 9.

So the approach allows us to add this new feature without introducing a BC.

**Comment by MiniCodeMonkey** [comment]
Ah. That totally makes sense. Thanks for clarifying!

On September 30, 2020, GitHub <notifications@github.com> wrote:
> @MiniCodeMonkey <https://github.com/MiniCodeMonkey> , changing the
> method signature would be a breaking change for users that are
> extending this class, and as breaking change it would only be released

> on Laravel 9.
>
> So the approach allows us to add this new feature without introducing

> a BC.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/framework/issues/34591#issuecomment-
701435463>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AABV254UJIE5TOTYXDNCL3TSIM7QNANCNFSM4R6RCOSQ>.

**Comment by andrey-helldar** [comment]
@taylorotwell, https://github.com/laravel/framework/pull/34597 fix accepted. Tell me, when is the patch release planned?

**Comment by driesvints** [comment]
@andrey-helldar releases are done on Tuesdays.

**Comment by andrey-helldar** [comment]
![image](https://user-images.githubusercontent.com/10347617/95182770-b6b5f400-07cd-11eb-984b-0c2fbe467f94.png)
