### ISSUE TITLE
Key with arrow notation is not guardable

### ISSUE THREAD

**Issue by angauber** [laravel/framework#34604]
- Laravel Version: 8.6.0
- PHP Version: 7.4.2
- Database Driver & Version: Mysql 5.7.29

### Description:

It is not possible to fill a model using the `->` notation because the key will be marked as not guardable.

 Relevent code:
```php
    protected function isGuardableColumn($key)
    {
        if (! isset(static::$guardableColumns[get_class($this)])) {
            static::$guardableColumns[get_class($this)] = $this->getConnection()
                        ->getSchemaBuilder()
                        ->getColumnListing($this->getTable());
        }

        return in_array($key, static::$guardableColumns[get_class($this)]);
    }
```
The return value will be false when passing the key `extras->test` because only `extras` will be present in that array.

### Steps To Reproduce:

1. Create a model and a migration with a json field `extras`
```
class StructuredActor extends Model
{
    protected $guarded = [
        'id',
    ];
}
```
2. test if the attribute is guarded with the arrow notation `extras->test`
```php
$m->isGuarded('extras') // false
$m->isGuarded('extras->test') // true
```

### Possible fix

Replace the return value of `isGuardableColumn`:
```php
        return in_array(Str::before($key, '->'), static::$guardableColumns[get_class($this)]);
```

I am not sure if this is a expected behaviour or a bug.  
If it's a bug I will be happy to submit a PR

**Comment by taylorotwell** [comment]
This is expected behavior after a security fix. I recommend using `fillable`. It is not possible to safely use guarded and JSON mass assignments at the same time.

**Comment by marwankhanfar** [comment]
@taylorotwell also the new logic does not handle the emulator attributes I suggest to check, and this will still secure too,
in our base model, we had overridden the function as below 

`    protected function isGuardableColumn($key)
    {
        return parent::isGuardableColumn($key) || $this->hasSetMutator($key);
    }`

@angauber what you can do is to add another OR condition with regex for the arrow notation
