### ISSUE TITLE
Field File missing or converted into string when using "FormRequest validation"

### ISSUE THREAD

**Issue by clablancherie** [laravel/framework#34603]
- Laravel Version: ^7.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.24

### Description:
Hi, i'm trying to validate a field file in my form. i've added "enctype multipart/form-data", my field is typed "file" but when i submit the form, my field is missing from my request. Also, when i remove "enctype" my field appears but it's not a field file, it's only the file name, so it's a string.

On the other hand, when I use the Request object, and not FormRequest to retrieve my request, I can see very well my file field, and I see that it is an "UploadedFile".

I don't understand what's going on, I've never had upload problems before.

### Steps To Reproduce:

- Create a form with a field "file". Then get the Request (Illuminate\Http\Client),you will see your file field into it.
- Create a form request and add a "dd()" on top of the rules, with debug $this->request->all(), you will see your file as string, only by his name.
- Add "enctype multipart/form-data" on your form, then you will see that your field disappear from your request.

You will see some capture in attachments.

Regards,
Christophe

![with-http-request](https://user-images.githubusercontent.com/68842985/94685899-5ab12280-032a-11eb-87c7-d354accc29a5.JPG)
![without-enctype](https://user-images.githubusercontent.com/68842985/94685900-5be24f80-032a-11eb-826f-51383712d50e.JPG)
![enctype+form-request](https://user-images.githubusercontent.com/68842985/94685902-5be24f80-032a-11eb-94ba-70d3469560b3.JPG)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
