### ISSUE TITLE
queue:retry {jobId} command not removing failed job from failed_jobs table

### ISSUE THREAD

**Issue by andreladocruz** [laravel/framework#34617]
- Laravel Version:  v8.7.1
- Horizon Version: v5.2.0
- PHP Version: 7.3.22
- Database Driver & Version: MySQL 5.7.22

### Description:
calling the PHP artisan queue:retry command do not remove jobs from failed_jobs table.

### Steps To Reproduce:
force a queued job to fail, then run PHP artisan queue:retry {jobId}.

**Comment by taylorotwell** [comment]
I don't think it is supposed to or ever has.

**Comment by andreladocruz** [comment]
@taylorotwell , this was how things works before upgrading to laravel 8 and horizon 5.

The queue:retry command used to remove the item from failed_jobs table.

**Comment by sisve** [comment]
It seems it should still remove the job from failed_jobs. What failed job provider are you using?

https://github.com/laravel/framework/blob/0bdd5c6f12cb7cb6644e484169656245af417735/src/Illuminate/Queue/Console/RetryCommand.php#L43
https://github.com/laravel/framework/blob/0bdd5c6f12cb7cb6644e484169656245af417735/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php#L93-L96

**Comment by andreladocruz** [comment]
@sisve , we use a MYSQL table. 

I have a cron to retry failed jobs every 30 minutes. 

![image](https://user-images.githubusercontent.com/3315596/94964310-829eb280-04f1-11eb-8ffd-5dba69fac89a.png)

I had to add the `$item->delete();` line to remove failed item from the table.
