### ISSUE TITLE
After pruning migrations and running migrate:fresh next migrations fail

### ISSUE THREAD

**Issue by rihardssceredins** [laravel/framework#34628]
- Laravel Version: v8.7.1
- PHP Version: 7.4.10
- Database Driver & Version: PostgreSQL, 12.4

### Description:
Currently tested only on PostgreSQL, but basically once migrations have been pruned and afterwards a new migration is added tests will fail because the new migration will be logged with ID 1 (auto increment is lost when creating database from dumped schema).

### Steps To Reproduce:
```
laravel new postgres-migrations
cd postgres-migrations
```
Create a new PostgreSQL database, update `.env` to point to it.
```
php artisan migrate
php artisan schema:dump --prune
php artisan migrate:fresh
php artisan make:migration NewMigration
php artisan migrate
```

Will result in:

```
Illuminate\Database\QueryException

SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "migrations_pkey"
DETAIL:  Key (id)=(1) already exists. (SQL: insert into "migrations" ("migration", "batch") values (2020_10_02_080813_new_migration, 2))
```

**Comment by taylorotwell** [comment]
PRs welcome.

**Comment by taylorotwell** [comment]
Fixed in next patch release.
