### ISSUE TITLE
Laravel 8 function setKeysForSaveQuery conflict

### ISSUE THREAD

**Issue by ruigomesa** [laravel/framework#34643]
Laravel Version: 8.8.0
PHP Version: 7.4.6
Database Driver & Version: -
Description:
The problem is the function setKeysForSaveQuery($query).
In the file Iluminate\Database\Eloquent\Model.php is declared function setKeysForSaveQuery($query)
And in the file Iluminate\Database\Eloquent\Relations\Concerns\AsPivot.php is declared function setKeysForSaveQuery(Builder $query)

**Comment by selcukcukur** [comment]
How does the conflict occur?

**Comment by timmoh** [comment]
For me also
Laravel Version: 8.8.0
PHP Version: 7.4.6

```
trait HasCompositePrimaryKey {
    /**
     * Set the keys for a save update query.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function setKeysForSaveQuery(Builder $query)
    {
        $keys = $this->getKeyName();
        if(!is_array($keys)){
            return parent::setKeysForSaveQuery($query);
        }

        foreach($keys as $keyName){
            $query->where($keyName, '=', $this->getKeyForSaveQuery($keyName));
        }

        return $query;
    }
}
```

**Comment by rodrigopedra** [comment]
@ruigomesa it seems to be fixed in Laravel 8.8.0, can you try running `composer update` again? 

If it still errors after update, try deleting the vendor folder and running `composer install`.

@timmoh , the type hint was removed from the base method in Laravel 8.8.0, as your trait is custom userland code, you need to remove the typehint from it.

**Comment by driesvints** [comment]
This is already fixed.

**Comment by demidovich** [comment]
Laravel Version: 8.9
PHP Version: 7.4.11

This is not fixed

**Comment by l3eto** [comment]
im having this error with latest version laravel 8.17.2, how did u solved it? is a new empty project, but giving error.

**Comment by o15a3d4l11s2** [comment]
In the latest version of Laravel (8.19.0) I get an exception `array_key_exists(): The first argument should be either a string or an integer` because it is trying to get the name of the primary key, which in case of composite key is an array. Therefore later array_key_exists will always fail. Are there any suggestion how this can be resolved?

**Comment by driesvints** [comment]
We don't support composite keys.

**Comment by o15a3d4l11s2** [comment]
@driesvints, sorry for bothering you. I am aware this is something that has come up from time to time and I know composite keys are not supported in Eloquent. I was trying to find a quick workaround to continue working without the need to change some of my models immediately (as I saw `trait HasCompositePrimaryKey` in the comments above). It seems now is the time to move away from composite keys and just use a surrogate key.

**Comment by timmoh** [comment]
if you need it. here is the code worked for me
```php
namespace App\Models\Traits;
use \Illuminate\Database\Eloquent\Builder;

trait HasCompositePrimaryKey {
    /**
     * Set the keys for a save update query.
     *
     * @param  mixed  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function setKeysForSaveQuery($query)
    {
        $keys = $this->getKeyName();
        if(!is_array($keys)){
            return parent::setKeysForSaveQuery($query);
        }

        foreach($keys as $keyName){
            $query->where($keyName, '=', $this->getKeyForSaveQuery($keyName));
        }

        return $query;
    }

    /**
     * Get the primary key value for a save query.
     *
     * @param mixed $keyName
     * @return mixed
     */
    protected function getKeyForSaveQuery($keyName = null)
    {
        if(is_null($keyName)){
            $keyName = $this->getKeyName();
        }

        if (isset($this->original[$keyName])) {
            return $this->original[$keyName];
        }

        return $this->getAttribute($keyName);
    }
}
```

**Comment by o15a3d4l11s2** [comment]
@timmoh, I had a similar implementation (slightly different but same final functionality behaviour), but with the latest version it did not work for me. Maybe I have hit a special case. At the end I decided to just continue working by modifying my table.

**Comment by ewgenkmz** [comment]
$ php artisan -V
Laravel Framework 8.36.2

The same problem:
ErrorException: Declaration of App\Core\EloquentModels\ModerTraits\HasCompositePrimaryKey::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query)

**Comment by iKlsR** [comment]
If you had this working prior and updated just change `Builder $query` to `$query`

**Comment by themrflibble** [comment]
> $ php artisan -V Laravel Framework 8.36.2
> 
> The same problem: ErrorException: Declaration of App\Core\EloquentModels\ModerTraits\HasCompositePrimaryKey::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query)

I had `Builder $query` as the parameter, when I removed `Builder` it solved this issue.

**Comment by justinrclarke** [comment]
> > $ php artisan -V Laravel Framework 8.36.2
> > The same problem: ErrorException: Declaration of App\Core\EloquentModels\ModerTraits\HasCompositePrimaryKey::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query)
> 
> I had `Builder $query` as the parameter, when I removed `Builder` it solved this issue.

This solved my issue as well.

**Comment by ODelibalta** [comment]
@timmoh Thank you for sharing. I tried to implement it but now I get ```array_key_exists(): Argument #1 ($key) must be a valid array offset type``` error 

```php
class Fifty extends Model
{
    use HasCompositePrimaryKey;
 
    public $incrementing = false;
    public $timestamps = false;
    protected $primaryKey = ['col1', 'col2', 'col3'];

```
