### ISSUE TITLE
When I change the Primary id through getters then foreign keys stop working

### ISSUE THREAD

**Issue by sajidfrommerqata** [laravel/framework#34655]
I need to add 0s to the right side of the id. When I do so through getter in the model then all my relations stop working. Can you fix this issue? Thank you

```
/**
     * Pad 0s to the right side of the id,
     *
     * @param  string  $value
     * @return string
     */
    public function getIdAttribute($value)
    {
        return str_pad($value, 4, '0', STR_PAD_LEFT);
    }
```

**Comment by rodrigopedra** [comment]
Primary Keys are cast to integer by default. 

From the docs: https://laravel.com/docs/8.x/eloquent#eloquent-model-conventions  \
*scroll to the **Primary Keys** section*

> In addition, Eloquent assumes that the primary key is an incrementing integer value, which means that by default the primary key will automatically be cast to an `int`.

> If your primary key is not an integer, you should set the protected `$keyType` property on your model to string:

~~~php
<?php

class Flight extends Model
{
    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';
}
~~~

As in your use-case you need zero-padded numerical strings as the primary key, you should change the `$keyType` to string.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sajidfrommerqata** [comment]
@rodrigopedra same issue

**Comment by rodrigopedra** [comment]
@sajidfrommerqata I guess I misunderstood your issue description:

>  all my relations **stop working**

So I am assuming that without the accessor (`getIdAttribute`) all your relations work as expected, but you need the padded `id` property for presentation purposes.

I'd suggest you add another property for presentation, something like this:

~~~php
// on your model:
public function paddedId() {
    return str_pad($this->id, 4, '0', STR_PAD_LEFT);
}

// usage
$model->paddedId();
~~~

Or, if you want to use it as an attribute:

~~~php
// on your model
public function getPaddedIdAttribute() {
    return str_pad($this->id, 4, '0', STR_PAD_LEFT);
}

// usage
$model->padded_id;
~~~

If using the latter approach you can also tweak `$appends` and `$hidden` properties to have the property added to JSON output:

~~~php
// on your model
protected $appends = ['padded_id'];

protected $hidden = ['id'];
~~~

One last option, if you really want to have the padded id named `id` but want to keep relations working, is overriding the `getKey()` method on your model, if doing so you would end with something like this on your model:

~~~php
public function getIdAttribute($value) {
    return str_pad($value, 4, '0', STR_PAD_LEFT);
}

public function getKey() {
    if (is_null($this->attributes['id'] ?? null)) {
        return null;
    }

    return intval($this->attributes['id']);
}
~~~

`getKey()` is used when matching relation results.
