### ISSUE TITLE
Database queue timeout when waking up computer from suspend

### ISSUE THREAD

**Issue by siikamiika** [laravel/framework#34652]
- Laravel Version: 8.6.0
- PHP Version: 7.4.10
- Database Driver & Version: pgsql, PostgreSQL 12.4

### Description:

`php artisan queue:listen` throws `ProcessTimedOutException` when waking up the computer from suspend.

```

   Symfony\Component\Process\Exception\ProcessTimedOutException

  The process "'/usr/bin/php' 'artisan' 'queue:work' '--once' '--name=default' '--queue=default' '--backoff=0' '--memory=128' '--sleep=3' '--tries=1'" exceeded the timeout of 60 seconds.

  at vendor/symfony/process/Process.php:1201
    1197▕
    1198▕         if (null !== $this->timeout && $this->timeout < microtime(true) - $this->starttime) {
    1199▕             $this->stop(0);
    1200▕
  ➜ 1201▕             throw new ProcessTimedOutException($this, ProcessTimedOutException::TYPE_GENERAL);
    1202▕         }
    1203▕
    1204▕         if (null !== $this->idleTimeout && $this->idleTimeout < microtime(true) - $this->lastOutputTime) {
    1205▕             $this->stop(0);

      +19 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Steps To Reproduce:

- Set `QUEUE_CONNECTION=database` in `.env`
- Run `php artisan make:job JobName`
- Run `php artisan queue:table`
- Run `php artisan migrate`
- Run `php artisan queue:listen`
- Suspend computer (Linux if relevant)
- Wake up computer and you get this error

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by siikamiika** [comment]
According to people on IRC what I'm looking for is too low level for a framework like Laravel.

Some suggestions and comments:
- Keep PC always on
- Get a server
- Run the queue on supervisord
- Use `--timeout 0` but add a timeout in the job itself
