### ISSUE TITLE
Resolve url loader Admin LTE is not working

### ISSUE THREAD

**Issue by eternalBlast** [laravel/framework#34676]
the resolve url loader not working on admin lte css from laravel sass. The other dependencies like bootstrap datepicker works well.
I'm using `resolve-url-loader` 3.1.0 in package.json
Here is my app.scss file
`@import '~admin-lte/dist/css/adminlte.min';`
If i was using .min.css, it worked well.
`@import '~admin-lte/dist/css/adminlte.min.css';`
Please check if it could be done without .css extension. Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
