### ISSUE TITLE
Overwriting attribute from one table with the value of an attribute with same name from another table in SQL join

### ISSUE THREAD

**Issue by zmilan** [laravel/framework#34671]
- Laravel Version: 7.22.4
- PHP Version: 7.4.7
- Database Driver & Version: pdo_mysql mysqlnd 7.4.7

### Description:
I'm relatively new to Laravel and the ecosystem and I have faced this issue which took me a lot of time to debug and understand:

```php
$user = User::rightJoin('tenant_users', 'tenant_users.user_id', '=', 'users.id')
    ->where('tenant_id', '=', $tenantFinder->getId())
    ->where(function ($query) use ($request) {
          $query->where('email', '=', $request->email)
            ->orWhere('username', '=', $request->email);
    })
    ->first();
```

This query return user which email or username exists in **users** table and has relation to **tenants** table through **tenant_users** table. So far so good. It was working correctly until I have discovered that it actually **doesn't work correctly**. It actually ends up setting ``` $user.id ``` field with **id** from **tenant_users** table instead of with **id** value from **users** table. The final result is that it grabs correct user information from **users** table except for **id** attribute which is later used for other related tables and load wrong information.

After some time trying to debug and to understand from where it found that `$user.id`, checking database values, clearing cache, taking raw SQL, and executing it, I have found what is the issue. After that, I was able to "solve" it by limiting select fields to only fields from the **users** table columns, like this:

```php
$user = User::rightJoin('tenant_users', 'tenant_users.user_id', '=', 'users.id')
    ->where('tenant_id', '=', $tenantFinder->getId())
    ->where(function ($query) use ($request) {
          $query->where('email', '=', $request->email)
            ->orWhere('username', '=', $request->email);
    })
    ->select('users.*')
    ->first();
```

Anyway, I don't think that this is how it should work. It should never "overwrite" attribute from one table with the value of an attribute with the same name from another table that is used in SQL join. Since I'm new to Laravel, I still keep the option that I'm doing something wrong here, so any suggestion is welcome too :)

**NOTE:** 
I didn't go with the default way of using relation, through pivot table, because in that case, I would end up with a much more complex SQL query than this way.

### Steps To Reproduce:
I believe that this is easy to replicate. The only thing that could help to spot this easy is to ensure that **id** in **tenant_users** and **id** in **users** table are different (which is usually not like if you don't delete some records from **users** table).

**Comment by staudenmeir** [comment]
Related: https://github.com/laravel/ideas/issues/347

**Comment by zmilan** [comment]
@staudenmeir thanks for pointing me to this issue... I didn't know about it, I'm relatively new to the Laravel community.

Anyway, I see that it is an old one and that is closed. But it has a very good point and it is actually a possible security issue. If you check my code above you will see that it uses 2 tables **users** and **tenant_users**. And if not limited to **users.*** it actually replaces **users.id** with **tenant_users.id** inside **$user** model. So in some scenario user that is authenticated with a valid username/password could get **id** from some other record that could, by chance, be some record with the highest privileges, and when I use later in code, for example, **$user->rights** to load relation with privileges for that user, it would actually return privileges for the user which has **id** that doesn't belong to the authenticated user.

**Comment by fernandobandeira** [comment]
It's been a while but if I remember this was a problem with the PDO implementation of the fetchObject.

Basically, your query will return two values for the same key (id) fetchObject doesn't know what to do with two values for the same property so it just picks the latest one and uses that, the result is that when you have any join, you might have fields overwritten if they have the same column names.

The easiest solution would be to put a note on the docs and advise users that are using joins to name their columns on the joins so this doesn't occur.

To fix this internally, the pdo could use something like FETCH_NAMED instead, fetch named returns an array if a key has two possible values, Laravel could check if any property returned is an array and throw an error to warn the user of an issue with his query.

**Comment by driesvints** [comment]
I don't think there's any workable solution for this. Feel free to attempt to PR something if you find a solution. Or send in a note to the docs. Thanks.

**Comment by zmilan** [comment]
@fernandobandeira like I have explained on other thread in laravel/ideas, I think that it is not a problem in how it works, but in that it doesn't warn you about that... For example, it is just throwing an exception like "duplicate/ambiguous column was found" everything would be clear and easy to fix by the developer (which responsibility it is to be more narrow about what he/she wish)... the way how it works at the moment, it silently overwrite attribute with another value, which then raises an issue with all other relations that comes from that model...
I'm not sure is this kind of check is possible, I didn't get time to check the code, but if it is not possible then the next best option would be to just make a big warning in the documentation. I also don't think that this is an issue when you use DB facade, since that way you expect plain data, but when you use model you expect that it would not mess at least not the primary key :)
