### ISSUE TITLE
/email/verify route 

### ISSUE THREAD

**Issue by maksimuslyandia** [laravel/framework#34673]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
when you are already verified, you don't need verify again.
After registration, we go through verification.
After verification, the / email / verify route is still active and I can verify myself again by mistake by manually navigating to / email / verify and the email_verified_at entry in the database will be overwritten.
There is a solution to how to prevent accidental navigation along the / email / verify route after verification. Or rather, if the user has already been verified, then just go to the main page.
### Steps To Reproduce:

need add check route to EnsureEmailsVerified.php
 elseif ($request->route()->uri === '/email/verify') {
            return route('login');
        }

#here example
public function handle($request, Closure $next, $redirectToRoute = null)
    {
        if (!$request->user() ||
            ($request->user() instanceof MustVerifyEmail &&
                !$request->user()->hasVerifiedEmail())) {
            return $request->expectsJson()
                ? abort(403, 'Your email address is not verified.')
                : Redirect::route($redirectToRoute ?: 'verification.notice');
        } elseif ($request->route()->uri === '/email/verify') {
            return route('login');
        }
//        dd( $request->user()->hasVerifiedEmail());
        return $next($request);
    }

**Comment by maksimuslyandia** [comment]
Or add one else middleware when we are already verified

**Comment by bbashy** [comment]
If you navigated to `/email/verify` when already verified, it wouldn't update the DB, regardless of if they have the signed URL query params.

Check the code that verifies;

```
public function verify(Request $request)
    {
        if (! hash_equals((string) $request->route('id'), (string) $request->user()->getKey())) {
            throw new AuthorizationException;
        }

        if (! hash_equals((string) $request->route('hash'), sha1($request->user()->getEmailForVerification()))) {
            throw new AuthorizationException;
        }

        if ($request->user()->hasVerifiedEmail()) {
            return $request->wantsJson()
                        ? new JsonResponse([], 204)
                        : redirect($this->redirectPath());
        }

        if ($request->user()->markEmailAsVerified()) {
            event(new Verified($request->user()));
        }

        if ($response = $this->verified($request)) {
            return $response;
        }

        return $request->wantsJson()
                    ? new JsonResponse([], 204)
                    : redirect($this->redirectPath())->with('verified', true);
    }
```

**Comment by maksimuslyandia** [comment]
thank you

ср, 18 нояб. 2020 г. в 13:57, Ben Sampson <notifications@github.com>:
