### ISSUE TITLE
PHPunit with inmemory database does no run migrations when using the new schema dump feature of laravel 8

### ISSUE THREAD

**Issue by kylescousin** [laravel/framework#34680]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: SQLITE

### Description:
PHPunit with inmemory database does no run migrations when using the new schema dump feature of laravel 8

### Steps To Reproduce:

Dump all your migrations to mysql-schema.sql with 
`php artisan schema:dump --prune`

Set phpunit.xml connection and database as follows:
```
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>
```

Extend tests from this base class:
```
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp() : void
    {
        parent::setUp();
        Artisan::call('migrate:fresh --seed');
    }

    protected function login($user = null)
    {
        $user = $user ?: factory('App\User')->create();

        $this->actingAs($user);

        return $this;
    }
}
```

Run your testsuite. (Base table not found on all tests)

When changing the database in phpunit to a mysql database, the migrations do run.

**Comment by driesvints** [comment]
https://laravel.com/docs/8.x/migrations#squashing-migrations

<img width="688" alt="Screenshot 2020-10-05 at 14 22 25" src="https://user-images.githubusercontent.com/594614/95078956-3b453b80-0716-11eb-984d-837c3f0e4277.png">
