### ISSUE TITLE
DatabaseTokenRepository can generate a token with a forward slash, which breaks the password.reset route

### ISSUE THREAD

**Issue by mstralka** [laravel/framework#34687]
- UI Version: 2.1.0
- Laravel Version: 7.18.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.31

### Description:

The `password.reset` route from laravel-ui is generated like this:
~~~
password/reset/{token}

# and it maps to App\Http\Controllers\Auth\ResetPasswordController@showResetForm
~~~

`ResetPasswordController->showResetForm` expects $token as a route parameter, like this:
~~~php
public function showResetForm(Request $request, $token = null)
~~~

If `token` is generated with a forward slash in it, then the route will not be matched to `password.reset`, Because the slash is a URL path delimiter.

We've seen this occur because the `DatabaseTokenRespository->createNewToken()` function does this:
~~~php
return hash_hmac('sha256', Str::random(40), $this->hashKey);
~~~

Sometimes, that function returns a string containing a forward slash.

### Steps To Reproduce:

Insert a record in your `password_resets` table with your email address and this token (which was generated in our production system with the forward slash):

~~~
$2y$10$M.PUHvBRZbv5N2RYx3Pnhu/neWmaajw1V02azOAbMge7BYiwpdeZG
~~~

Use Tinker to load your User model and then send the ResetPasswordNotification:

~~~bash
php artisan tinker
~~~

~~~php
$user = App\Models\User::find(3); // Replace with your model's ID
$user->sendPasswordResetNotification('$2y$10$M.PUHvBRZbv5N2RYx3Pnhu/neWmaajw1V02azOAbMge7BYiwpdeZG');
~~~

Check your email and click the **Reset Password** link.

Because that `$token` has a backslash in it, your Laravel site will return a 404 Page not found error.

### Expected behavior

The `$token` should never have a forward slash in it, or the route matching logic should account for the possibility that the token could have a slash in it.

Thank you

**Comment by driesvints** [comment]
Great issue, thanks. If you can whip up a PR for this that'd be great. Otherwise I'll try to tackle this tomorrow so it's in time for tomorrow's release.

**Comment by mstralka** [comment]
Thanks - I tried changing the route definition like this:
~~~php
Route::get('password/reset/{token?}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
        ->where('token', '(.*)');
~~~

But when I reset my password, I'm getting `PasswordBroker::INVALID_TOKEN`  returned from `PasswordBroker->validateReset()`, so I must be missing something somewhere.

I'll keep working on it.

**Comment by mstralka** [comment]
This isn't a bug with the framework but with our customization. 

We have a subclass of `DatabaseTokenRepository->create()` function that was returning the hashed token, which is why the token in the URL sometimes had the slash in it. We are going to remove the customization and revert to the original route definition.

Sorry for the false bug!

**Comment by taylorotwell** [comment]
We should probably just stripe forward slashes out of the token when we generate it.
