### ISSUE TITLE
fresh migration in specific path

### ISSUE THREAD

**Issue by HamidMp** [laravel/framework#34699]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description: 

In multiple database configuration and multiple migration paths (sub folders in migration folder) when executing `artisan migrate:fresh --path=/database/migrations/newpath` it will reset both specific path and migration path (main migration) but it only migrate (create) specific path (without creating main migration files) therefore in database (mysql) the main database has only migration-table.

BUG: fresh command works on root path when we mention some specific paths in artisan command
the solution is that 'fresh' command should works only for specified paths.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
