### ISSUE TITLE
Exception restoring psql dump in 8.8

### ISSUE THREAD

**Issue by matejvelikonja** [laravel/framework#34694]
- Laravel Version: 8.8.0
- PHP Version: 7.4.11
- Database Driver & Version: postgres 12.4

### Description:
After upgrading to Laravel 8.8., migration failed to restore migration squash created in previous version of Laravel.

```
Error Output:
================
pg_restore: error: input file appears to be a text format dump. Please use psql.
```

### Steps To Reproduce:
- Run `php artisan schema:dump --prune` in 8.7
- Upgrade to 8.8
- Clear database and run migrations.

I think the issue happens in this commit fcf175b246a646e81c13fb0e6c212f0b21cdfe51.

The other question is, why changing from text dump to binary dump, as binary dump is not visible in VCS?

**Comment by taylorotwell** [comment]
I think you will have to re-dump, because we had some problems with previous version of schema dump.

**Comment by matejvelikonja** [comment]
But what's the reasoning to move from `plain` text dump to `custom-format archive suitable for input into pg_restore`?
Is it not better to have plain text dumps in VCS instead of a binary one?

**Comment by taylorotwell** [comment]
I don't really know except that it was part of this PR that fixed an issue: 

https://github.com/laravel/framework/issues/34281

https://github.com/laravel/framework/pull/34293

**Comment by d-stephane** [comment]
Install laravel with a version lower than 8.8 and start the migration.
Then do "php artisan schema: dump --prune" and look in the generated file. You will find at the end this:
```
INSERT INTO public.migrations VALUES (1, '2014_10_12_000000_create_users_table', 1);
INSERT INTO public.migrations VALUES (2, '2014_10_12_100000_create_password_resets_table', 1);
INSERT INTO public.migrations VALUES (3, '2019_08_19_000000_create_failed_jobs_table', 1);
```
If you have to install this project on another server you will have to start the migration.
It is the file obtained with the dump that will be loaded and not the migration files because "--prune" option used.
Until then everything works. If you run migration -> error !
Look in the database of your new project:
```
test3=# SELECT * FROM migrations_id_seq;
 last_value | log_cnt | is_called 
------------+---------+-----------
          1 |      32 | t
```
The value of last_value is incorrect.
With a pg_dump -Fc I don't have this problem.
I do not know if it's clear


PS : sorry for my bad English.....

**Comment by matejvelikonja** [comment]
@d-stephane ah, I see. I've also encountered this issue, but I have fixed it manually.

However, I don't like having a binary file in the VCS. Since you don't see changed in the schema. But if there is no other option....

Ok, at least this change has to be somehow marked in the changelog. And it's a breaking change, since schema dump from <8.8 does not work in 8.8.

**Comment by taylorotwell** [comment]
If someone has a fix without switching to the binary dump let me know.

**Comment by matejvelikonja** [comment]
🤔 maybe at least support for both `pg_restore` and `psql` command could be added in [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Schema/PostgresSchemaState.php#L54) based on the `$path`.

They you could at least use `php artisan migrate --seed --schema-path=database/schema/pgsql-schema.sql`...
