### ISSUE TITLE
[Breaking] Correct output of Str::snake

### ISSUE THREAD

**Issue by danilopolani** [laravel/framework#34719]
- Laravel Version: 8.9.0
- PHP Version: 7.4.10
- Database Driver & Version: N/A

### Description:
I was playing around with `Str::snake` when I found out that it does not return what I expected, for example `Str::snake('Not-Modified')` should return `not_modified` but currently it returns `not-_modified`; same for `not-modified` (lowercase) that should return `not_modified` but, instead, the output is STILL `not-modified`.

Taking a look at the Unit tests for this I found out [there are some regression tests](https://github.com/laravel/framework/blob/8.x/tests/Support/SupportStrTest.php#L380-L384) to prevent breaking changes exactly for these cases and I was wondering if it's time to introduce a breaking change for it (with Laravel 9?). For instance, both `Not-Modified` and `not-modified` should return `not_modified`.

Currently I can't use `Str::snake` for my use case and I'm using a simple regex (`/[^\d\w_]/u`), but would nice that Laravel itself fixes it and not forcing the users to use an handmade regex because the helper is wrong.

### Steps To Reproduce:
N/A

**Comment by AegirLeet** [comment]
Can't you just do `Str::snake(str_replace('-', ' ', 'Not-Modified'));`?

I don't feel like saving a single `str_replace()` is a strong enough justification for breaking BC.

**Comment by danilopolani** [comment]
I know about the `str_replace`, but still the issue is on the helper IMHO. `Not-Modified` was an example of what value I can have, since I'm parsing HTTP Status Codes it could be also `I'm a Teapot` and that would render in `i'm_a_teapot` which is not a valid snake_case string.

**Comment by AegirLeet** [comment]
What's your definition of valid snake_case? Stripping out certain characters might be desirable for your specific use case, but it isn't necessarily desirable for everyone.

**Comment by danilopolani** [comment]
A valid snake_case string should contain only letters, numbers and underscores. You couldn't write a variable or method named `$i'm_a_teapot` for example. Take a look also to `lodash`, it transforms `I'm a Teapot` into `im_a_teapot`, it just strips all the non-alphanumeric characters.

**Comment by AegirLeet** [comment]
OK - that's not a universal standard though, as far as I know. Both implementations are completely arbitrary.

**Comment by danilopolani** [comment]
IMHO this is just a wrong implementation (probably because of breaking changes indeed), let's wait for an official answer tho.

**Comment by taylorotwell** [comment]
If you need any different "snake" behavior I would suggest writing it yourself.

**Comment by danilopolani** [comment]
I was just reporting this, how `foo-bar` is considered a valid snake case (according to the tests) if it's instead a kebab case? It could not be both.
