### ISSUE TITLE
remember cookie dosen't work after laravel upgrade 7 to 8 

### ISSUE THREAD

**Issue by strawoo** [laravel/framework#34717]
- Laravel Version: 8.8.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql 8.0.17, 

### Description:
remember_web_~~~~ cookie was deleted when i tried login by using remember_ cookie only

### Steps To Reproduce:
1. login with remember paramger like this.
`Auth::login($user, $remember);`
2. delete session cookie. 
3. retry request to some page. ( ex) my page)
4. redirected to login page and remember_web cookie was deleted.

**Comment by iamthefreeman** [comment]
What version of 7.x did you migrate from?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by strawoo** [comment]
> What version of 7.x did you migrate from?
> 
> Edit: https://blog.laravel.com/laravel-cookie-security-releases (It may have to do with this, as one of the releases of Laravel had a security fix within it, but it invalidated all existing cookies).

Thank's for your comment. Unfortunately, i'm using redis session driver.

**Comment by strawoo** [comment]
I found this cause. the cause of the issue is **7.26.1 changes**(if remember cookie have not password part, session be log out. now i use socialite). 
**not 8.X issue.**
