### ISSUE TITLE
can not install in windows with laravel new command

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [laravel/framework#34729]
- Laravel Version: 8.x
- PHP Version: 7.4.3

### Description:

with laravel new command this problem happened, with composer, it's fine no error

when I installing in windows if my windows defenders real-time protection is on I can't install the project, it's showing me this error below

![bug](https://user-images.githubusercontent.com/48278861/95351125-af343f00-08e2-11eb-8a8b-51c355f52901.PNG)

In windows the defender message shows me that this file contains virus

**Comment by GrahamCampbell** [comment]
Please report this false positive to Microsoft.
