### ISSUE TITLE
User Session 'user_agent' and 'ip_address' fields are corrupt when using Laravel Echo Server.

### ISSUE THREAD

**Issue by huguesjoyal** [laravel/framework#34737]
- Laravel Version: 8.9.0
- PHP Version: 7.3.21
- Database Driver & Version: MySQL 5.7.31

### Description:
Seems to be an old issue :
https://laracasts.com/discuss/channels/laravel/user-session-user-agent-and-ip-address-fields-are-corrupt-when-using-laravel-echo-server

The problem is that the laravel-echo-server itself is creating a request to the /broadcasting/auth URL without passing the HTTP_USER_AGENT and the REMOTE_ADDR would always be the one used by the server itself.

My suggestion is to modify the file src/Illuminate/Session/DatabaseSessionHandler.php to add an exception to the addRequestInformation() method that would just not set the IP address and user_agent to payload.

Something like :
```php
    protected function addRequestInformation(&$payload)
    {
        if ($this->container->bound('request') && $this->userAgent()) {
            $payload = array_merge($payload, [
                'ip_address' => $this->ipAddress(),
                'user_agent' => $this->userAgent(),
            ]);
        }

        return $this;
    }
```

**Comment by driesvints** [comment]
Since this is specific to echo server I don't really see how this is a bug within Laravel. Feel free to attempt a PR if you wat to change something 👍

**Comment by huguesjoyal** [comment]
Thanks, but since you think this is related to laravel-echo-server, I'm gonna try to make these package to forward the user-agent and to set a X-Forwarded-For so that the sessions has all the same "info" as the laravel request.
