### ISSUE TITLE
Events registered via subscribers ignored when using auto event discovery

### ISSUE THREAD

**Issue by mewejo** [laravel/framework#34745]
- Laravel Version: 8.9.0
- PHP Version: 7.4.8
- Database Driver & Version: MySQL 8.0.20-0ubuntu0.20.04.1 (via Homestead)

### Description:
Subscribers listed in `\App\Providers\EventServiceProvider::$subscribe` and registering events via `\Illuminate\Events\Dispatcher::listen()` in the `subscribe()` method are not having their listeners called upon fired events. Removing `shouldDiscoverEvents()` (returning true) from `\App\Providers\EventServiceProvider` allows the events registered via the subscribers to fire again.

### Steps To Reproduce:

1. Create an event subscriber as per https://laravel.com/docs/8.x/events#registering-event-subscribers
2. Test your events fire (they should)
3. Enable automatic event discovery as per https://laravel.com/docs/8.x/events#event-discovery
4. The event that fired in step 2 no longer fires

I am using the `\Illuminate\Auth\Events\Login` event in this instance, though it looks like it would affect other events too.

**Comment by driesvints** [comment]
Event discovery is only available for event listeners. That's why it's listed under that particularly section in the docs.

**Comment by mewejo** [comment]
@driesvints  I know, I'm not trying to use event discovery for subscribers. I'm trying to use (and have been using, until enabling auto event discovery) subscribers too. Is it intentional that it's one or the other? And if so, is that listed in the docs somewhere?

**Comment by driesvints** [comment]
@mewejo you're free to work on a PR for this but I don't think it's possible given the nature of how subscribers behave.

**Comment by mewejo** [comment]
I'll take your word for it not being possible, as you know far more about the inner workings of Laravel than I do.. Could the docs be updated to reflect the fact that event subscribers and event discovery are not able to be used together please?

**Comment by driesvints** [comment]
The feature is documented under event listeners so I don't know how much clear it can be? Feel free to attempt a PR however if you feel like anything can be clarified.

**Comment by mewejo** [comment]
Ok, my tests were failing and I just assumed it was because the event was not firing, but in fact it was due to the event firing twice. If I get a chance I'll try and add something to the docs about not using them together as events will be registered multiple times.
