### ISSUE TITLE
Sending a notification through the mail channel does not write to log when MAIL_MAILER=log

### ISSUE THREAD

**Issue by panda-madness** [laravel/framework#34742]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Database Driver & Version: SQLite

### Description:

When trying to send a notification via the `mail` channel with MAIL_MAILER=log Laravel does not write anything to the log if the notification returns a `MailMessage` in it's `toMail()` method. Creating a proper `Mailable` class and returning that works as expected.

### Steps To Reproduce:
1. Set the mail driver to `log`.
2. Create a notification:
```
class SomeNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function via(User $notifiable)
    {
        return ['mail'];
    }

    public function toMail(User $notifiable)
    {
        return (new MailMessage)
                    ->line("Code: $notifiable->code");
    }
}
```
3. Attempt to send the notification: `$user->notify(new SomeNotification())`.
4. Check the log.

**Comment by driesvints** [comment]
Works fine for me with the exact code from above.
