### ISSUE TITLE
I get Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable when broadcasting Pusher events.

### ISSUE THREAD

**Issue by mevanso01** [laravel/framework#34766]
- Laravel Version: 8.9.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL

### Description:
I have an issue with broadcasting pusher events. This is what I get from Laravel.

> Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable while building [Illuminate\Queue\CallQueuedHandler, Illuminate\Queue\CallQueuedHandler]. in file /var/www/html/development/devhubhandler/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1017

For sending pusher events, I'm using **pusher/pusher-php-server** library.
I'm sure that I've set **env** variables correctly. **BROADCAST_DRIVER** is set to **pusher**, _config/broadcasting.php_ is defined correctly. Also, I've defined an event class that implements **ShouldBroadcast**. All this worked perfectly on previous Laravel versions.

### Steps To Reproduce:

This is the dependencies.
```
    "require": {
        "php": "^7.3",
        "laravel/framework": "^8.0",
        "laravel/helpers": "^1.3",
        "laravel/tinker": "^2.0",
        "pusher/pusher-php-server": "^4.1",
        ...
    },
```

This is **env** variables.
```
BROADCAST_DRIVER=pusher
PUSHER_APP_ID=******
PUSHER_APP_KEY=********************
PUSHER_APP_SECRET=********************
PUSHER_APP_CLUSTER=us3
```

This is content of **config/broadcasting.php**.
```
    'connections' => [
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
            ],
        ],
        ...
    ],
```

This is the code snippet for sending pusher events.

`broadcast(new EventTxnUpdate($sessionKey, $id, $fullName))->toOthers();`
```
class EventTxnUpdate implements ShouldBroadcast
{
  use Dispatchable, InteractsWithSockets, SerializesModels;

  public $sessionKey;
  public $tid;
  public $userFullName;

  public function __construct($sessionKey, $tid, $userFullName)
  {
      $this->sessionKey   = $sessionKey;
      $this->tid          = $tid;
      $this->userFullName = $userFullName;
  }

  public function broadcastOn()
  {
      return [env('PUSHER_APP_CHANNEL_TXN')];
  }

  public function broadcastAs()
  {
      return 'txnUpdate_'.$this->tid;
  }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
