### ISSUE TITLE
Problem with missed methods after upgrading Laravel 7.x to 8

### ISSUE THREAD

**Issue by cupcodei** [laravel/framework#34763]
Hi, after upgrading Laravel framework using Composer, I tried to use one of it's new methods, "upsert", which is defined in "Illuminate\Database\Query\Builder.php" but I found that I don't have this method in my project files. How is it possible? Did I missed something when I was upgrading my project? temporally I copied that method and its requirement("compileUpsert") from github and it works fine. But is it a good solution?!

**Comment by lagbox** [comment]
This method was just added in the last few days and there has not been a tagged release of Laravel 8.x since then. So you won't have it until the next tagged version `8.10.0`

Also:
#34761

**Comment by driesvints** [comment]
Will be released on Tuesday at the latest.
