### ISSUE TITLE
Delay withChain Errors

### ISSUE THREAD

**Issue by mikebrandl** [laravel/framework#34762]
- Laravel Version: 8.9.0
- PHP Version: 7.3.23
- Database Driver & Version: Mysql 

### Description:

I have a delayed Queue Job, withChain, which I need to run two jobs shortly after each other. 

   QuoteJob::withChain([
                new NestedQuoteJob($quote),
            ])->dispatch($quote)->delay(now()->addMinutes(1));

When using this I get the following error: message: "Call to a member function delay() on string"

This worked fine on Laravel 7 which is what I am attempting to upgrade from, so appears a new bug, non chained jobs work fine.

E.G  QuoteJob::dispatch($quote)->delay(now()->addMinutes(1));

### Steps To Reproduce:

Delay a dispatched, chained job.

**Comment by rodrigopedra** [comment]
This feature was removed in this commit:

https://github.com/laravel/framework/pull/33364/commits/de662daf75207a8dd69565ed3630def74bc538d3

Included in this PR:

https://github.com/laravel/framework/pull/33364

Unfortunately I couldn't find the reasoning on why this change was made. Maybe this could be reverted somehow.

**Comment by driesvints** [comment]
Although the docs don't specifically show an example of using `delay` in combination with `withChain` I understand that this technically worked in a previous version. I'll check with @themsaid to see if we'll either add this to the upgrade guide or restore this functionality. Thanks for reporting.

**Comment by driesvints** [comment]
@mikebrandl does it work if you put delay before dispatch?

**Comment by mikebrandl** [comment]
Hi @driesvints Sadly not, just tried it.

**Comment by taylorotwell** [comment]
Need more feedback from @themsaid on this but looks like the `delay` method needs to be added to `PendingChain`.

**Comment by taylorotwell** [comment]
Fixed in next patch release.
