### ISSUE TITLE
upsert function documented but not yet working 

### ISSUE THREAD

**Issue by hamzamogni** [laravel/framework#34761]
- Laravel Version: 8.0
- PHP Version: 7.2.5
- Database Driver & Version: mysql

### Description:

On the official documentation, an upsert function is documented [here](https://laravel.com/docs/8.x/queries) but is not yet working. I think it should be removed from documentation or explicitly mention that it is not yet implemented.

### Steps To Reproduce:

run `DB::table("table name")->upsert([], [], []);`

**Comment by paras-malhotra** [comment]
@hamzamogni the new version isn't yet tagged. It will be available as soon as its tagged.

**Comment by driesvints** [comment]
Will be released on Tuesday.
