### ISSUE TITLE
SQLite non-incrementing Primary key type handling

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#34773]
- Laravel Version: 8.9.0
- PHP Version: 7.4.3
- Database Driver & Version: Sqlite/Mysql

### Description:
When dealing with a non-incrementing primary key that is still an integer. Laravel isn't converting that primary key to an int. This causes a testing discrepancy between mysql testing/usage (CI/CD) and sqlite testing (local) for unit/integration tests.

### Steps To Reproduce:

MIgration columns
```
$table->unsignedBigInteger('id');
```

Model configuration:
```
public $incrementing = false;
```

Using a model that is going to be tested in both environments mysql and sqlite environments, note that when using a factory or just in general creating a model during testing will result in the primary key not staying the same data type. This causes a specific issue like:

```
$model = Temp::create(['id' => 123']);
$model->is(Temp::find(123)); // false when it should be true
```
This returns false, because in the create, the id is left as an int, but when retrieving from the database, it stays a string when testing using sqlite. This creates a layer of friction that really shouldn't be required. While I understand this is a database level
datatype issue, just turning on/off incrementing shouldn't potentially break a test based on a datatype.

Temp workaround:
Ensure that the id is cast to int in the $casts property on the model.

**Comment by taylorotwell** [comment]
PR's welcome, but I really suggest not running tests against different databases like this. It's not reliable really. I would always run against the same type of database in local, staging, and production. Can you share your model definition?
