### ISSUE TITLE
/laravel/framework/src/Illuminate/Routing::callAction() call_user_func_array() using php8 "error"

### ISSUE THREAD

**Issue by jungbaksacom** [laravel/framework#34782]
- Laravel Version: 6.0.0 and grater
- PHP Version: 8.0.0 rc1
- Database Driver & Version:

### Steps To Reproduce:

return call_user_func_array([$this, $method], $parameters);

change

return call_user_func_array([$this, $method], **array_values($parameters)**);

**Comment by GrahamCampbell** [comment]
Laravel does not support PHP 8/0, and in fact composer won't let you install it unless you ask it to ignore platform dependencies.

**Comment by GrahamCampbell** [comment]
Dries, Taylor and I have been working hard on PHP 8 support, including a of work on Laravel's dependencies to get them ready. Things are almost complete now, with Guzzle 7.2.0 being released a few hours ago, with PHP 8.0 compatibility. Our final blockers are Whoops and Doctrine DBAL. See https://github.com/laravel/framework/pull/33388.
