### ISSUE TITLE
ReflectionProperty's isInitialised is available after PHP 7.4

### ISSUE THREAD

**Issue by chaoszcat** [laravel/framework#34783]
https://github.com/laravel/framework/blob/2e47b9c7db158c9dd776c734f8cdb927cf84a4c8/src/Illuminate/Queue/SerializesModels.php#L70

Isn't `isInitialised` is only available after PHP 7.4? Ref: https://www.php.net/manual/en/reflectionproperty.isinitialized.php

**Comment by GrahamCampbell** [comment]
That code is only executed on PHP 7.4.
