### ISSUE TITLE
Missing chain() method in BusFake

### ISSUE THREAD

**Issue by ajcastro** [laravel/framework#34797]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Database Driver & Version: Mysql 5.7

### Description:
I have a code in controller with `Bus::chain($jobs)->dispatch()` and my unit tests is calling `Bus::fake();`. 
When I run my unit test, it errors `Call to undefined method Illuminate\Support\Testing\Fakes\BusFake::chain()`. 
Maybe `chain` method should be added also in `BusFake`

UploadsController.php
```php
    public function store()
    {  
       $upload = Upload::create(request()->all());
        Bus::chain([
            new UploadProcessingJob($upload),
            new FinalizeUpload($upload),
        ])->dispatch();
        return $upload;
    }
```

UploadsControllerTest.php
```php
   public function test_uploads_store()
    {
        Bus::fake();

        $response = $this->postJson(route('uploads.store'), [
            //... omitted for brevity
        ]);

        $response
        ->assertCreated();

        Bus::assertDispatched(UploadProcessingJob::class);
    }
```

**Comment by taylorotwell** [comment]
Fixed in next patch release.
