### ISSUE TITLE
Str::isUuid validation helper, or Str::uuid broken

### ISSUE THREAD

**Issue by simonsdigital** [laravel/framework#34799]
- Laravel Version: 8.6.0
- PHP Version: 7.4.9
- Database Driver & Version: Mysql 5.7.31-0ubuntu0.18.04.1

### Description:
UUID validation helper Str::isUuid doesn't validate self-generated Uuids correctly. There is a suspected fault with either the generation, or validation logic.

### Steps To Reproduce:

`
\Illuminate\Support\Str::isUuid(\Illuminate\Support\Str::uuid())
`

The above returns false.

**Comment by JurianArie** [comment]
This is because you forgot to call `toString()`.
`\Illuminate\Support\Str::isUuid(\Illuminate\Support\Str::uuid()->toString())`
The above returns true.

**Comment by fragkp** [comment]
Maybe we could check if the given parameter is an instance of `\Ramsey\Uuid\UuidInterface` and cast it to string.
