### ISSUE TITLE
Unwanted recursion in custom casts

### ISSUE THREAD

**Issue by daniser** [laravel/framework#34798]
- Laravel Version: 8.9.0, 7.28.4
- PHP Version: 7.4.5

### Description:
Custom cast can't properly access virtual attributes (defined by accessors or maybe another casts too (not tested)) from its $model argument in set() method.

### Steps To Reproduce:
1. Create custom cast which accesses another virtual (computed by accessor) attribute from $model in its set() method.
2. Create table with primary key and one another column.
3. Create eloquent model for this table and apply custom cast from step 1 to column from step 2.
4. Add accessor for non-existent attribute. This will be virtual attribute for step 1.
5. Instantiate model, set its castable attribute to some object (for some reason it's important), and save it.

Expected result:
- Succesful cast application using input object and virtual model attribute.

Result accessing virtual attribute via magic property:
- Undefined property: App\Models\CastTest::$prefix (can't find virtual attribute; WHY???)

Result accessing virtual attribute via getAttribute() method:
- Maximum function nesting level of '256' reached, aborting! (recursion)

### Example code:

Custom cast:
```
<?php

namespace App\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

class TestCast implements CastsAttributes
{
    public function get($model, string $key, $value, array $attributes)
    {
        // Not important
    }

    public function set($model, string $key, $value, array $attributes)
    {
        // Access via magic property
        $prefix = $model->prefix;

        // Access via getAttribute() method (comment previous line to get here)
        $prefix = $model->getAttribute('prefix');

        return $prefix.$value[0];
    }
}
```

Database table:
```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

Schema::create('cast_test', function (Blueprint $table) {
    $table->id();
    $table->string('test');
});
```

Eloquent model:
```
<?php

namespace App\Models;

use App\Casts\TestCast;
use Illuminate\Database\Eloquent\Model;

/**
 * @property string $test
 * @property-read string $prefix
 */
class CastTest extends Model
{
    protected $table = 'cast_test';

    public $timestamps = false;

    protected $casts = [
        'test' => TestCast::class,
    ];

    public function getPrefixAttribute()
    {
        return 'HELLO_';
    }
}
```

Test code:
```
<?php

use App\Models\CastTest;

$test = new CastTest;
$test->test = new \ArrayObject(['WORLD']);
$test->save();

// EXPECTED RESULT: "HELLO_WORLD" in `test` field in the `cast_test` table.
```

**Comment by taylorotwell** [comment]
Not a great way to solve this atm - possibly not ever. When accessing something via a mutator we are going to sync back all mutated data from custom casts, but since this is being done via a custom cast it will never resolve.

You will likely just need to access the attribute via the `$attributes` property that is passed to your method or figure out some other work around.

**Comment by taylorotwell** [comment]
For your specific example, I would just make prefix() a method, not an accessor.
