### ISSUE TITLE
Http Request uri discrepancies in unit tests with trailing slash

### ISSUE THREAD

**Issue by ahinkle** [laravel/framework#34801]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Database Driver & Version: n/a

### Description:
There are some discrepancies with when using `->getRequestUri()` in the browser vs unit tests with a trailing slash.

In production, certain nginx configurations automatically add the trailing slash. Simple fix in our application but we aren't able to create a replicable test. 

Usage note: We are using `getRequestUri()` to dynamically fetch content via a slug column value (such as 'test') from the database.

1. Create a route:
```php
Route::get('test', fn() => request()->getRequestUri());
```

Visit `/test/` (with trailing slash) in Browser:
![Screen Shot 2020-10-12 at 10 57 54 AM](https://user-images.githubusercontent.com/17038330/95767091-d0e24d00-0c79-11eb-9927-ce294b8ec90c.png)

Create a test:
```php
public function test_trailing_slash_is_resolvable()
{
    $this->get('/test/')
        ->assertSee('/test/');
    // $this->assertEquals('/test/', request()->getRequestUri());
}
```

Response:
```
Failed asserting that '/test' contains "/test/".

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/test/'
+'/test'
```

**Comment by taylorotwell** [comment]
Don't use a trailing slash.

**Comment by DCzajkowski** [comment]
Respectfully, this doesn't seem like a reasonable response @taylorotwell. There are cases, where trailing slashes must be handled appropriately. In my opinion, it's understandable the framework makes it easier to handle requests by assuming trailing slashes are irrelevant and stripping them for developer's convenience. But in tests, when I do
```php
<?php

$this->get('/contact/');
``` 
I expect the test to simulate a request to `/contact/`, not strip it on the request level. Could you please reconsider this?

cc: @driesvints

**Comment by driesvints** [comment]
@DCzajkowski I don't agree here. An URL with or without a trailing slash should be treated as the same URL therefor it's perfectly valid to only use urls in these tests without a trailing slash. If you want to force urls without trailing slash then that's a responsibility of your web server, not the framework.

**Comment by DCzajkowski** [comment]
@driesvints thank you for your input.

I think what I am struggling to understand, is why we can simulate a request to `/contact/` in manual tests (e.g. in a browser, postman, curl) and see how the application behaves and cannot do that in automated tests (except for browser tests, but those are not relevant to the discussion).

> If you want to force urls without trailing slash then that's a responsibility of your web server, not the framework.

Does this mean, that in your opinion it's up to nginx's/apache's configuration how trailing slashes are treated and testing that behavior in the application has no point?

If so, I understand the logic behind this, but on the other hand, server misconfigurations do happen, and testing at least the app does not crash when those occur would be beneficial.

Let me know what you think. :)

**Comment by driesvints** [comment]
Your web server can be set up to strip trailing slashes. But if it isn't then your app wouldn't behave any differently as if a url did had trailing slashes or not.

**Comment by DCzajkowski** [comment]
Hm, let me give you an example.

Let's say I have an app, that is served on both `/contact` and `/contact/`. I want to test, that in both cases, the canonical meta tag is set to the same URL (let's say, `/contact`).

I make a test:

```php
public function test_a_canonical_url_points_to_the_same_url_ignoring_a_slash()
{
    $responseA = $this->get('/en');
    $responseB = $this->get('/en/');

    $canonicalURL = '<link rel="canonical" href="' . url('/en') . '" />';

    $this->assertStringContainsString($canonicalURL, $responseA->baseResponse->content());
    $this->assertStringContainsString($canonicalURL, $responseB->baseResponse->content());
}
```

Now for the implementation I do:
```html
<link rel="canonical" href="{{ app('app.url') . Request::getRequestUri() }}" />

<!-- ^ the above will be the exact URI we are on -->
```

The test passes, even though a correct implementation in this case is:

```html
<link rel="canonical" href="{{ Request::fullUrl() }}" />

<!-- ^ the above will have a trailing slash stripped irrespective of what we currently are on -->
```

When I learned this behavior exists, it became obvious it's not possible to test this in Laravel without overriding a TestCase's parent function. 

I don't care if Laravel assumes correct server implementation and strips trailing slashes on the application level. What I do care about, is that when I write a test, that makes a request to URL _x_, I expect the testing framework to do exactly that. Without any tampering with the input — especially like this.

**Comment by b166er** [comment]
i have same issue, i need to test a api-url with and without trailing slash, is it possible to re-open this issue?

**Comment by riabiy-denis** [comment]
> @DCzajkowski I don't agree here. An URL with or without a trailing slash should be treated as the same URL therefor it's perfectly valid to only use urls in these tests without a trailing slash. If you want to force urls without trailing slash then that's a responsibility of your web server, not the framework.

Imagine having a Laravel Vapor setup. 
The only way to have trailing slashes redirect there is using middleware. And I'd prefer to test that logic in a TDD-manner :)

**Comment by b166er** [comment]
my example implementation, maybe this helps someone who searching for strict handling of trailing slashes.

app\Http\Middleware\TrailingSlash.php
```php
<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Exceptions\TrailingSlashException;

class TrailingSlash
{

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $requestUrl = $request->getRequestUri();
        // if trailing slash exists at end AND is NOT root path
        if (Str::endsWith($requestUrl, '/') && '/' !== $requestUrl) {
            throw new TrailingSlashException(); // throw a nice formatted error message
        }
        return $next($request); // continue with next
    }
}
```

app\Http\Kernel.php
```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;
class Kernel extends HttpKernel
{
    protected $middleware = [
        //...
        \App\Http\Middleware\TrailingSlash::class, // add TrailingSlash-Middleware to Kernel
    ];
//...
```

**Comment by riabiy-denis** [comment]
@b166er 
I wish you've posted it yesterday : D 

Here is the regex, that does the same. 
```
if (preg_match('/.+\/$/', $request->getRequestUri()))
==
if (Str::endsWith($requestUrl, '/') && '/' !== $requestUrl) {
 ```

Pick what fits you the most. 

p.s. @b166er just curious. Did you spend 1hr debugging requests, until you've added `'/' !== $requestUrl` or you wrote it right away?

**Comment by danon** [comment]
There are many legitimate ways why a developer might want to distinguish a request based on whether a trailing slash was used or not.

For example: to improve SEO, you should handle canonical links, such that `page.com/contacts` returns 200, but `page.com/contacts/` redirects 301. In order to be able to do that, you need to check if a trailing slash is used in a request.

Further more, in order to write an automatic test for that feature, you need to be able to create a test request with a trailing slash, that will actually be passed to the logic.

Let's not make tools that try to be smarter than their users.
