### ISSUE TITLE
[Validation rules] - why I can't extend a new validator make by artisan make:rule?

### ISSUE THREAD

**Issue by gritzkoo** [laravel/framework#34807]
- Laravel Version: 8.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 8.0

### Description:
In the documentation, there are two ways of how to register a new validation. 
Register a new one in AppServiceProvider by adding a *__Validator::extend__* who uses closures, and using PHP artisan *__make:rule__* command and in validator use the keyword *__'my-field' => [`new MyRule`],__*  ... there is a way to just use the PHP artisan command in Validation::extend?
Like use the command *__php artisan make:rule MyRule --name my-rule__* and then generate the Rule class and register in *__AppServiceProvider__*  validation extend with name provided like *__Validation::extend('my-rule', MyRule::class)__*?

**Comment by taylorotwell** [comment]
This appears to be a question, not a bug.
