### ISSUE TITLE
Custom renderable for ModelNotFoundException

### ISSUE THREAD

**Issue by Eldair** [laravel/framework#34804]
- Laravel Version: 8.9.0

### Description:

Line `313` (`$e = $this->prepareException($this->mapException($e));`) in `Illuminate\Foundation\Exceptions\Handler` class makes it impossible to write custom renderable for `ModelNotFoundException` (or other exceptions changed with that method without some complicated checks). Perhaps it should be moved below foreach loop, or there is some other way to do it?

### Steps To Reproduce:

Writing this `$this->renderable(fn(ModelNotFoundException $e) => response()->json(__('errors.not_found'), 404))` in `register` method of `App\Exceptions\Handler` will have no effect.

**Comment by taylorotwell** [comment]
The exception is converted into a NotFoundHttpException; however, the original ModelNotFoundException is available via $exception->getPrevious(). So, register a renderable listener on NotFoundHttpException and check $e->getPrevious() for instanceof ModelNotFoundException.

**Comment by Eldair** [comment]
Hello,
In that case I would have to duplicate the default behavior for when previous exception is not `ModelNotFound` and it is inconsistent with `reportable` where there is no transformation.

I guess I can still overwrite the render method like in L7.

**Comment by joaquinwojcik** [comment]
@taylorotwell 

Can you improve docs for [Reportable & Renderable Exceptions](https://laravel.com/docs/8.x/errors#renderable-exceptions)?
It's not very clear if Laravel Service Container will automatically load them or if we should register them into `Handler.php`
In this last case, how should we register renderable exceptions?

If I want to create renderable exception for 404 errors, should I extend `NotFoundHttpException` or `Exception`?

E.g

```
<?php

namespace App\Exceptions;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class NotFoundException extends NotFoundHttpException
{
    /**
     * Report the exception.
     *
     * @return void
     */
    public function report()
    {
        //
    }

    /**
     * Render the exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function render($request)
    {
        return response(...);
    }
}
```

thx in advance
