### ISSUE TITLE
Cache::has(key) - is deleting the key from the DB no matter what the expiration date is set to 

### ISSUE THREAD

**Issue by heyaj19** [laravel/framework#34811]
- Laravel Version:  7.28.3
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 14.4

### Description:
 
I am creating signed URLS and using DB to store them if the response is a success. When I check the DB to see it exists by using Cache::has it deletes it. Due to which it does not exist 

### Steps To Reproduce:

The code is here 
https://medium.com/@DarkGhostHunter/laravel-combining-signed-routes-with-temporal-tokens-c5177769b432

**Comment by iksaku** [comment]
Could you upload an example code on https://laravelplayground.com/ please? That way people can trace the issue easier :wink:

**Comment by taylorotwell** [comment]
Unable to recreate. Make your system clock is in sync.

**Comment by heyaj19** [comment]
@taylorotwell  the expiration date is set to multiple dates in advance. As the above example shows using FILE. I am using the database. Not sure if this makes a difference and this is happening on my local machine - where the clock is in sync
