### ISSUE TITLE
Use brackets in directives

### ISSUE THREAD

**Issue by SpokeUniverse** [laravel/framework#34824]
![image](https://user-images.githubusercontent.com/44891639/95926438-a6ba9780-0dff-11eb-9778-75b0734f379e.png)
When I am trying to add a bracket, Laravel throws an error: 'ParseError, syntax error, unexpected '?' (View: <view path>)'

**Comment by taylorotwell** [comment]
Generally this kind of thing isn't possible because of the limitations of Blade parsing using regular expressions. I suggest just using a normal section input:

```php
@section('error-title')
Not found :(
@endsection
```
