### ISSUE TITLE
problem with @php and @while in blade 

### ISSUE THREAD

**Issue by nerdpanda-ir** [laravel/framework#34821]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11

### Description:
i'm using `@php()` for define counter variable but , when `blade` compiled code to php , can not close php tag . 
 i think this is bug 
please help me for Understand this subject 
Shot Group 1  : 
![Screenshot_2020-10-13_16-16-19](https://user-images.githubusercontent.com/39291525/95871952-20f50880-0d7b-11eb-9eb6-f3ce1533c501.png)
![Screenshot_2020-10-13_16-16-37](https://user-images.githubusercontent.com/39291525/95871972-26525300-0d7b-11eb-9633-672022984caa.png)
![Screenshot_2020-10-13_17-09-34](https://user-images.githubusercontent.com/39291525/95871993-2b170700-0d7b-11eb-8097-8b2107858619.png)

Shot Group 2 : 
this syntaxt dont have Error 

![Screenshot_2020-10-13_17-10-39](https://user-images.githubusercontent.com/39291525/95872274-7cbf9180-0d7b-11eb-9f1b-c26ecc5d0bed.png)
![Screenshot_2020-10-13_17-10-43](https://user-images.githubusercontent.com/39291525/95872291-80ebaf00-0d7b-11eb-95a3-bb01349f0bc8.png)

**Comment by taylorotwell** [comment]
Passing PHP expressions to the @php directive is not documented as being possible nor is it supported.

**Comment by fridzema** [comment]
@nerdpanda-ir in your first example you have forgotten the `@endphp` at the end. As @taylorotwell said it is not possible to pass something as a function; https://laravel.com/docs/8.x/blade#php

```php
@php
$counter++;
@endphp
```
