### ISSUE TITLE
[8.10.0] The same error appears twice.

### ISSUE THREAD

**Issue by selcukcukur** [laravel/framework#34842]
- Laravel Version: 8.10.0
- PHP Version: 7.4
- Database Driver & Version: 

### Description:
The error is displayed twice on the error pages. I thought there was a problem with the Ignition Package, but Symfony Exception, Whoops Exception are all the same. I think there is a problem with Laravel.

### Steps To Reproduce:
1. "composer create-project --prefer-dist laravel/laravel" install laravel.
2. We can try any error screen. It's the same with all of them. 
3. **Example :** In the ".env" file, leave the APP_KEY variable blank.

### The Screen You Will See :

The same error appears twice : https://prntscr.com/uzn0os

**Comment by paras-malhotra** [comment]
It's not a bug. See https://github.com/laravel/framework/issues/34305

> if the framework can't resolve a middleware due to something like a missing APP_KEY the handle and terminate both throw an exception and it gets rendered twice

**Comment by selcukcukur** [comment]
@paras-malhotra I understand thanks.
