### ISSUE TITLE
[8.9] RefreshDatabase incompatible with Schema::create

### ISSUE THREAD

**Issue by RDelorier** [laravel/framework#34849]
- Laravel Version: 8.9.0
- PHP Version: 7.4.11
- Database Driver & Version: mysql => mariadb 10.4

### Description:
`RefreshDatabase` trait doesn't work correctly if `Schema::create` is used during test.

I have a job that dynamically creates a table but when testing with the mysql driver it interferes with the transactions started with `RefresDatabase`.

Found this additional information https://stackoverflow.com/questions/50819257/creating-and-dropping-a-table-during-laravel-test

The solution I found is to use `DatabaseMigrations` instead of `RefreshDatabase`.

### Steps To Reproduce:
```php
<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_creates_a_user()
    {
        User::factory()->create(['id' => 1]);

        Schema::create('foo', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });

        $this->assertTrue(true);
    }

    public function test_it_creates_another_user()
    {
        User::factory()->create(['id' => 1]);
        $this->assertTrue(true);
    }
}

```

Running this test will result in an error for duplucate primary key 1 on user

![image](https://user-images.githubusercontent.com/2295675/96153490-c4f5c580-0edb-11eb-84c6-656972209e1d.png)

**Comment by RDelorier** [comment]
Found this additional information https://stackoverflow.com/questions/50819257/creating-and-dropping-a-table-during-laravel-test

**Comment by X-Coder264** [comment]
This is just how MySQL works. All DDL  statements (including CREATE TABLE) do an implicit commit of the transaction and the `RefreshDatabase` trait uses transactions to do its job so this is expected behavior. To be honest I don't see what can Laravel do here (maybe better document this behavior?).

**Comment by RDelorier** [comment]
> This is just how MySQL works. All DDL statements (including CREATE TABLE) do an implicit commit of the transaction and the `RefreshDatabase` trait uses transactions to do its job so this is expected behavior. To be honest I don't see what can Laravel do here (maybe better document this behavior?).

Better documentation of this behavior seems like the best option here.

**Comment by mfn** [comment]
Indeed. In Postgres it works as a user would expect, as DDL statements respect existing transactions.
