### ISSUE TITLE
Event Discovery for package development

### ISSUE THREAD

**Issue by zeravcic** [laravel/framework#34844]
- Laravel Version: [8.10.0](https://github.com/laravel/framework/tree/v8.10.0)
- PHP Version: 7.4.10 ([Homestead v9.5.1, VirtualBox](https://app.vagrantup.com/laravel/boxes/homestead/versions/9.5.1))
- Database Driver & Version: MySQL v5.7.29

### Description:
It seems that '[Event Discovery](https://laravel.com/docs/8.x/events#event-discovery)' for package development ([1](https://laravelpackage.com/10-events-and-listeners.html#creating-an-event-service-provider)) ([~~2~~](https://laravel.com/docs/8.x/packages)) does't work as expected.

It's OK when the `listen` property contains an array of all events (keys) and their listeners (values), but overriding the `shouldDiscoverEvents` and the `discoverEventsWithin` methods doesn't discover events (throw exception).

### Steps To Reproduce:

1. Package's composer file:
```json
// /packages/vendor-name/package-1/composer.json
{
    "name": "vendor-name/package-1",
    "autoload": {
        "psr-4": {
            "VendorName\\Package1\\": "src/"
        }
    },

    // ...
}
```

2. Package's custom event provider:
```php
// /packages/vendor-name/package-1/src/app/Providers/EventServiceProvider.php

namespace VendorName\Package1\app\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
// ...

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [];

    public function boot() {}

    public function shouldDiscoverEvents()
    {
        return true;
    }

    protected function discoverEventsWithin()
    {
        return [
            realpath(__DIR__ . '/../Listeners'),
        ];
    }
}
```

3. EXECUTE: `ReflectionException` is throw on [line 47](https://github.com/laravel/framework/blob/v8.10.0/src/Illuminate/Foundation/Events/DiscoverEvents.php#L47) with message "_Class Packages\vendor-name\package-1\src\app\Listeners\SendWelcomeEmail does not exist_".

This is maybe a request to improve the [`classFromFile` method](https://github.com/laravel/framework/blob/v8.10.0/src/Illuminate/Foundation/Events/DiscoverEvents.php#L76), yes? :grin:

**Comment by taylorotwell** [comment]
I'm not sure we ever document event discovery from packages as being possible or a package being able to register events in this way? "laravelpackage.com" is not an official Laravel website and I'm not sure who maintains that.

You are right that I see `classFromFile` as only working on `app` directory classes.

Anyone is open to try to add this functionality but personally I'm not sure I am going to consider it a bug at this moment because I don't think we ever intended to support this at the package level.
