### ISSUE TITLE
[8.x] Route prefix mixed up in Route::group and Route::prefix

### ISSUE THREAD

**Issue by bzrncev** [laravel/framework#34845]
If I install a brand new Laravel 8.x app and add the following code in app.php:
```php
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->get('/foo', function() {
    //
});

Route::group(['prefix' => 'v1'], function() {
    Route::get('/bar', function() {
        //
    });
});
```

when I run ```php artisan route:list``` I get the following results:
```
+--------+----------+------------+------+---------+------------+
| Domain | Method   | URI        | Name | Action  | Middleware |
+--------+----------+------------+------+---------+------------+
|        | GET|HEAD | /          |      | Closure | web        |
|        | GET|HEAD | api/v1/bar |      | Closure | api        |
|        | GET|HEAD | v1/api/foo |      | Closure | api        |
+--------+----------+------------+------+---------+------------+
```

I want the prefix ```/api/v1/``` in both of my routes, but they are mixed up.

**Comment by taylorotwell** [comment]
I remember this coming up when @driesvints and I rebuilt some routing stuff and we agreed it is a little odd, but we couldn't change it right now without breaking other use cases.

That is why in the documentation we only show usage of `prefix` in a group context. I suggest always using it in that way.
