### ISSUE TITLE
Inconsistent implementation with upsert() functionality

### ISSUE THREAD

**Issue by nxuls** [laravel/framework#34850]
- Laravel Version: 8.10.0
- PHP Version: 7.3.8
- Database Driver & Version: mysql (MySQL 8)

### Description:
The recently added `upsert()` functionality (for Eloquent Models) is inconsistent, leading to vastly different outcomes depending on the database adapter that is currently in use for the application.

- If you are using MySQL, the `$uniqueBy` function argument is completely thrown away and not used in any capacity. The end result will be that the record will either be created or updated based on duplicate key entries (standard `ON DUPLICATE KEY` functionality in MySQL)

- In all other drivers, the `$uniqueBy` function argument is utilized, the columns are considered for duplicate checks, and overall it works as it should.

### Steps To Reproduce:

1. Create a table in MySQL that has a few test columns, add no indexes to this table not even a primary key

1. Run `upsert()` with relevant test data, pick a random pre-existing column for `$uniqueBy`, the function call will create a new record

1. Run `upsert()` with the same exact data as the previous step, you will have multiple records with duplicate data, even though you have specified a unique column via `$uniqueBy`.

**Comment by taylorotwell** [comment]
Ping @paras-malhotra

**Comment by mfn** [comment]
https://github.com/staudenmeir/laravel-upsert has a pretty nice implementation; wonder if the original author checked it and what they think about this in comparison?

**Comment by paras-malhotra** [comment]
@nxuls, all database drivers except SQL Server require the `uniqueBy` columns to be have either a PRIMARY index or a UNIQUE index. If you have these indices setup, the queries will be consistent with all drivers except SQL Server because all drivers would anyway not allow any inserts that violate the primary/unique constraints. 

The behaviour you're seeing is because you're trying to use a `uniqueBy` clause on columns that are not indexed as PRIMARY or UNIQUE. I'll send a PR for updating the docs to clarify this.

**Comment by paras-malhotra** [comment]
@mfn it's pretty much the same implementation

**Comment by nxuls** [comment]
> 
> 
> @nxuls, all database drivers except SQL Server require the `uniqueBy` columns to be have either a PRIMARY index or a UNIQUE index. If you have these indices setup, the queries will be consistent with all drivers except SQL Server because all drivers would anyway not allow any inserts that violate the primary/unique constraints.
> 
> The behaviour you're seeing is because you're trying to use a `uniqueBy` clause on columns that are not indexed as PRIMARY or UNIQUE. I'll send a PR for updating the docs to clarify this.

I know, that's what I said. In my opinion this functionality is too "db engine specific" to have an actual function for it seeing as how it can't be replicated the same all across the board with a single query. Also, yes the documentation is misleading.

**Comment by paras-malhotra** [comment]
If the constraints are setup properly, you will see consistent behaviour across the board.

**Comment by nxuls** [comment]
> 
> 
> @nxuls, all database drivers except SQL Server require the `uniqueBy` columns to be have either a PRIMARY index or a UNIQUE index. If you have these indices setup, the queries will be consistent with all drivers except SQL Server because all drivers would anyway not allow any inserts that violate the primary/unique constraints.
> 
> The behaviour you're seeing is because you're trying to use a `uniqueBy` clause on columns that are not indexed as PRIMARY or UNIQUE. I'll send a PR for updating the docs to clarify this.

If that's the intended functionality, then it is not clear in the documentation so it would definitely be good to update it. Regardless, the functionality of creating or updating automagically without requiring the use of indexes is something I'm sure some people would appreciate having (bulk updates come to mind).

**Comment by paras-malhotra** [comment]
Upserts without indexes aren't supported in most databases as bulk queries unfortunately.

I've sent a PR to the docs to clarify this: https://github.com/laravel/docs/pull/6496

**Comment by taylorotwell** [comment]
Closing this since a doc update has been opened as a PR.
