### ISSUE TITLE
[8.X] Can not run artisan optimize without views

### ISSUE THREAD

**Issue by eusonlito** [laravel/framework#34854]
- Laravel Version: v8.10.0
- PHP Version: 7.4.11

### Description:

I'm using an api without any view (nor `resources` directorory) and I can not execute `php artisan optimize` without views installed.

Trying to execute `php artisan optimize` without `Illuminate\View\ViewServiceProvider::class` provider:

```
$> php artisan optimize

Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Compiled views cleared!

In Container.php line 811:
                                       
  Target class [view] does not exist.  
                                       

In Container.php line 809:
                             
  Class view does not exist  
```

Trying to execute `php artisan optimize` with `Illuminate\View\ViewServiceProvider::class` provider but without `resources/views` folder:

```
$> php artisan optimize

Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!

In ViewClearCommand.php line 57:
                        
  View path not found.  
```

### Steps To Reproduce:

1. Remove `Illuminate\View\ViewServiceProvider::class` provider or delete `resources/views` folder.
2. Execute php artisan optimize

### Expected Results:

Do no try to optimize not loaded service providers.

Can I send a PR with a fix for this issue?

**Comment by GrahamCampbell** [comment]
This is the expected case. Laravel does not support unloading core service providers.

**Comment by eusonlito** [comment]
> This is the expected case. Laravel does not support unloading core service providers (unless you are doing some custom trickery which needs you to extend a core service provider and register that instead).

Then `ViewServiceProvider` is a core service? I can avoid to execute `optimize` and execute the one by one the others cache, config and route cache commands, but, will Laravel fails on other point if I do not use the `ViewServiceProvider`?

Thanks :)
