### ISSUE TITLE
Handling deadlock caused by locking reads

### ISSUE THREAD

**Issue by yos1p** [laravel/framework#34855]
- Laravel Version: 5.8.38
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.26

### Description:
Deadlock exception caused by locking reads (sharedLock or lockForUpdate) should be thrown and not just ignored and return empty results.

### Steps To Reproduce:
- Open two terminals for php artisan tinker
- Start transaction in the terminals (`DB::transaction()`)
- In T1, update a specific User
- In T2, update a specific User
- In T1, try to select number of Users with sharedLock()
- In T2, try to select number of Users with sharedLock()

Expected:
- Error / Exception thrown

Actual:
- Empty results returned

**Comment by taylorotwell** [comment]
I don't think we have control over that? We just return what the database returns. If the database doesn't error we don't throw an exception.

**Comment by mohamedazher** [comment]
I have an issue similar to the one mentioned here lockForUpdate() returns an empty result after the timeout occurs once it crosses innodb_lock_wait_timeout. 

Trying the same mysql via terminal gives ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction. However in Laravel it just waits and returns an empty result with no exception/error. Shared lock however works, it throws and error while running the update query (after the timeout occurs). 

A simple way to reproduce is to open 2 tinker sessions and do the following

Session 1
```
 DB::transaction(function()
            {
                $user = User::where('id',1)
                    ->lockForUpdate()
                    ->first();

                sleep(55);

                $user->name = 'test1';
                $user->save();

            });
```
Session 2
```
 DB::transaction(function()
            {
                $user = User::where('id',1)
                    ->lockForUpdate()
                    ->first();

                //$user is null with no error after the timeout
                $user->name = 'test2';
                $user->save();
            });
```

Any reason why no exception occurs when the same occurs in mysql command line? or is there a better way to handle this?

**Comment by mohamedazher** [comment]
Seems to be a bug in PHP https://bugs.php.net/bug.php?id=76742 deadlock errors are ignored with PDO::ATTR_EMULATE_PREPARES is set to FALSE
