### ISSUE TITLE
Broadcast Auth 403 Error When Routes Cached

### ISSUE THREAD

**Issue by myckhel** [laravel/framework#34859]
- Laravel Version: ^8.0
- PHP Version: 7.4

### Description:
When routes are being cached,
broadcast channels returns 403 response upon using channel class for the authorisation
But when route are not cached
then the broadcast auth works perfectly

### Steps To Reproduce:
```php
<?php
// channels.php
Broadcast::channel('App.User.{id}', 'App\Broadcasting\User\Channel');

// Channel.php
public function join(User $user, $id)
{
    return (int) $user->id === (int) $id;
}

// BroadcastServiceProvider
public function boot()
{
      Broadcast::routes(['middleware' => ['auth:api'], 'prefix' => 'api']);
}
```

```bash
php artisan route:cache
```

```curl
GET {{host}}/api/broadcasting/auth?channel_name=private-App.User.1
```

returns 403 error.

Please help Thanks.

**Comment by taylorotwell** [comment]
I was unable to recreate this on a fresh Jetstream Laravel application. I cached my my routes.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/463230/96293253-153e5780-0fb0-11eb-8916-d57241b7b2da.png">

Maybe double check your configuration. What does the output of `artisan route:list` give you? Does the broadcast route look correct in that list?

**Comment by myckhel** [comment]
Well i expected your response to be a broadcast auth token: 
```json
{"auth": "hdisijehehsusygt_€#^^#gss"}
```
Instead of: 
```json
{"name": "Taylor"}
```

🙂🙂🙂

I hope you can reproduce the bug.

**Comment by myckhel** [comment]
please  @taylorotwell this bug still persists and no solution found so far.

`api/broadcasting/auth` exists in `route:list` command


from https://github.com/laravel/framework/blob/5ba3d0b8c660ce36ac6325a6edba20b9e4ffb333/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php#L66

when route cached and `Log::debug($this->channels);` logs
```
[2021-03-11 16:31:31] local.DEBUG: array ();
```

but when route not cached logs

```
[2021-03-11 16:36:20] local.DEBUG: array (
  'App.User.{id}' => 'App\\Broadcasting\\User\\Channel',
  'story-created.{countryId}.{stateId}.{gender}' => 'App\\Broadcasting\\CountryStateGenderChannel',
  'story-deleted.{countryId}.{stateId}.{gender}' => 'App\\Broadcasting\\CountryStateGenderChannel',
  'spotlight-created.{countryId}' => 
  Closure::__set_state(array(
  )),
  'message-event-created.{conversation}' => 'App\\Broadcasting\\Chat\\ConversationChannel',
  'message-created.{conversation}' => 'App\\Broadcasting\\Chat\\ConversationChannel',
  'message-new.user.{user}' => 'App\\Broadcasting\\Chat\\UserMessageChannel',
  'message-event.user.{user}' => 'App\\Broadcasting\\Chat\\UserMessageChannel',
  'User.Online.{user}' => 
  Closure::__set_state(array(
  )),
)  
```

What could be the possible reason for empty `$channels`?

**Comment by myckhel** [comment]
i have finally fixed this issue by creating a fresh laravel app and comparing it to my app.
along the way i discovered a difference which caused the issue.

it was due to this missing line from BroadcastServiceProvider
`require base_path('routes/channels.php');`
