### ISSUE TITLE
Timezone implementation error, case:  'America/La_Paz' and now() function

### ISSUE THREAD

**Issue by flvportafolio** [laravel/framework#34863]
- Laravel Version: 8.10.0
- PHP Version: 7.4.10

### Description:
i got an error when i set up config/app.php with 'timezone' => 'America/La_Paz'
- if i code --> echo now()." - "; return(now());  
i got output --> 2020-10-16 19:59:08 - "2020-10-16T23:59:08.868845Z"

so I got 2 different dates, but if I don't modify the timezone which has by default 'timezone' => 'UTC' in config/app.php i got 2020-10-17 00:28:08 - "2020-10-17T00:28:08.099556Z" this is a equivalent date.
### Steps To Reproduce:
1) change 'timezone' => 'UTC' in config/app.php to 'timezone' => 'America/La_Paz'
2) code in any controller with index method --> echo now()." - "; return(now());

**Comment by rodrigopedra** [comment]
The `echo` usage converts to a common string representation and uses a timezone.

The `return` usage tried to convert to a JSON representation, which is UTC based, hence the `Z` in the end.

If you try to do this:

~~~php
Route::get('test', function () {
    echo now()->format('Y-m-d h:i:s') . ' - ';
    return(now()->format('Y-m-d h:i:s'));
});
~~~

You will get both dates within the same timezone.

**Comment by flvportafolio** [comment]
the problem is that im getting a list of users with timestamps created_at, updated_at powered by api and im getting the problem with dates distinct, i think that laravel config timezone does not act globally on the application.
