### ISSUE TITLE
Laravel 8 none existing route after deleting work

### ISSUE THREAD

**Issue by MahdiPishguy** [laravel/framework#34861]
- Laravel Version: "^8.0",
- PHP Version: 7.4.10 

### Description:
i had `checkAuth` route in `routes` early and now it doesn't defined in routes because i deleted that

you can see this output:

    php artisan route:list

output:

> Your application doesn't have any routes matching the given criteria.

now when i try to test this route, it worked :|

    192.168.1.103:8000/checkAuth
    
    True, you are logged!!

### Steps To Reproduce:
    php artisan optimize:clear
    php artisan config:cache
    php artisan config:clear
    php artisan clear-compiled
    composer dump-autoload

**Comment by MahdiPishguy** [comment]
> 
> 
> `php artisan route:clear` ?

i tested all of them, i steel have this problem, i'm wondering what happend

**Comment by ExpDev07** [comment]
Having trouble understanding what you initially claim is your issue?

**Comment by MahdiPishguy** [comment]
> 
> 
> Having trouble understanding what you initially claim is your issue?

after more than 12 hours work on this issue, i can't resolve and i had to downgrade laravel version and finally problem resolved

**Comment by taylorotwell** [comment]
You have some sort of cache.
