### ISSUE TITLE
extra comma in BusServiceProvider

### ISSUE THREAD

**Issue by kebook-programacao-1** [laravel/framework#34871]
- Laravel Version: 8.10.0
- PHP Version: 7.3.23
- Database Driver & Version:MySQL 5.7.31 

### Description:
In BusServiceProvider.php line 51:
  syntax error, unexpected ')'
when running the composer update i got the error message above, checking the vendor / laravel / framework / src / Illuminate / Bus / BusServiceProvider.php file, there is a comma after the last parameter of the function, removing, I was able to install the dependencies

### Steps To Reproduce:
I just went to the root of the project and ran a composer update

**Comment by ExpDev07** [comment]
PHP should support leading commas in parameters (at least tested on newer PHP version 7.4.7).

**Comment by kebook-programacao-1** [comment]
@ExpDev07, I just tested the function below in PHP 7.4.3 and 7.3.23, in both the error occurred

<?php
function sum ($x, $y,){
        return $x + $y;
}
echo sum(1,1);

error: PHP Parse error:  syntax error, unexpected 'return' (T_RETURN) in /tmp/teste.php on line 3

**Comment by kebook-programacao-1** [comment]
@ExpDev07 , I just tested the function below in PHP 7.4.3 and 7.3.23, in both the error occurred
`<?php
function sum ($x, $y,){
	return $x + $y;
}
echo sum(1,1);`

**Comment by GrahamCampbell** [comment]
https://3v4l.org/WJtvC

**Comment by GrahamCampbell** [comment]
Function calls are not the same as function definitions.

**Comment by ExpDev07** [comment]
@GrahamCampbell that is if the method has no parameters, see the following: https://3v4l.org/RcPJs. Works for 7.3+, fails below.
