### ISSUE TITLE
Collections intersect Doesn't Work

### ISSUE THREAD

**Issue by bhushan** [laravel/framework#34889]
Let's Suppose,

We have Collection Of Post Models where we are eager loading relations like auther etc 

so `$collectionA` consists of All Post Models with eager loaded relations.

Now we have another Collection `$collectionB` where we didn't fetched relations

and then

if I use `$collectionB->intersect($collectionA)` or vise versa It returns empty collection even if i have similar models.

**Comment by bhushan** [comment]
Laravel Version: 7.26.0
PHP Version: 7.4
Database Driver & Version: MySQL 5.7
OS: MacOs

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
