### ISSUE TITLE
artisan serve Error "Failed to listen on" "reason: ?" 

### ISSUE THREAD

**Issue by gustaveco** [laravel/framework#34886]
- Laravel Version: 8.10.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7.31
- OS: Windows 10 v1903

### Description:
Installing a fresh project of Laravel (8.10.0) and running `php artisan serve`gives error indicating that cannot listen to a determined port: `Failed to listen on 127.0.0.1:8000 (reason: ?)` with multiples ports:

```
Starting Laravel development server: http://127.0.0.1:8000
[Mon Oct 19 09:36:12 2020] Failed to listen on 127.0.0.1:8000 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8001                      [Mon Oct 19 09:36:12 2020] Failed to listen on 127.0.0.1:8001 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8002
[Mon Oct 19 09:36:13 2020] Failed to listen on 127.0.0.1:8002 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8003
[Mon Oct 19 09:36:13 2020] Failed to listen on 127.0.0.1:8003 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8004
[Mon Oct 19 09:36:14 2020] Failed to listen on 127.0.0.1:8004 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8005
[Mon Oct 19 09:36:14 2020] Failed to listen on 127.0.0.1:8005 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8006
[Mon Oct 19 09:36:15 2020] Failed to listen on 127.0.0.1:8006 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8007
[Mon Oct 19 09:36:15 2020] Failed to listen on 127.0.0.1:8007 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8008
[Mon Oct 19 09:36:16 2020] Failed to listen on 127.0.0.1:8008 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8009
[Mon Oct 19 09:36:16 2020] Failed to listen on 127.0.0.1:8009 (reason: ?)
Starting Laravel development server: http://127.0.0.1:8010
[Mon Oct 19 09:36:17 2020] Failed to listen on 127.0.0.1:8010 (reason: ?)
```

But if i try just: 

```
 php -S 127.0.0.1:8000  -t public/ server.php
[Mon Oct 19 13:38:39 2020] PHP 7.4.6 Development Server (http://127.0.0.1:8000)
started
```
works fine.

Also, i tried with a Laravel ^7 versión and always works fine.

### Steps To Reproduce:

```
composer create-project --prefer-dist laravel/laravel laratest-8
php artisan serve
```

**Comment by devcircus** [comment]
There have been other reports of this happening on windows. See [this issue](https://github.com/laravel/framework/issues/34229) for discussion. Looks like a php.ini tweak has fixed this issue for others.

**Comment by driesvints** [comment]
See the comment above.

**Comment by NeamotNaim** [comment]
i also faced this problem. In my term, it was the old version of php 7 and Laravel requires update version of PHP in my environment (xampp) so I update xampp for PHP current version. then it works. mainly php.ini file is the main reason for this. If you have trouble to update xampp PHP version then you can download latest version of xampp then install it in other folder except "C" then copy php.ini file and paste it to your "C- xampp-php" folder. I think it would work now.

**Comment by yurenzhen** [comment]
i got this problem too, and i succeed solved it in this way:

set: php.ini

variables_order = "GPCS"

**Comment by Shemandia** [comment]
i got the same error too

**Comment by carlosdaniel26** [comment]
me too

**Comment by raheescwc2020** [comment]
type php -S localhost:8000 -t public/

**Comment by Kremilly** [comment]
> type php -S localhost:8000 -t public/

This solved for me, thx

**Comment by eu-pedro** [comment]
> type php -S localhost:8000 -t public/

solved it for me, thanks bro

**Comment by Mahmoudadel17** [comment]
> type php -S localhost:8000 -t public/

solved it for me also, thanks ^_^

**Comment by zackyfachrur** [comment]
> php artisan serve Failed to listen on 127.0.0.1:8000 (reason: ?) Failed to listen on 127.0.0.1:8001 (reason: ?) Failed to listen on 127.0.0.1:8002 (reason: ?) Failed to listen on 127.0.0.1:8003 (reason: ?) Failed to listen on 127.0.0.1:8004 (reason: ?) Failed to listen on 127.0.0.1:8005 (reason: ?) Failed to listen on 127.0.0.1:8006 (reason: ?) Failed to listen on 127.0.0.1:8007 (reason: ?) Failed to listen on 127.0.0.1:8008 (reason: ?) Failed to listen on 127.0.0.1:8009 (reason: ?) Failed to listen on 127.0.0.1:8010 (reason: ?) all the suggestions are not working for me

try from this guy : 
https://github.com/laravel/framework/issues/34229#issuecomment-2463451622

**Comment by fathulmaulana** [comment]
C:\Users\       \.config\herd-lite\bin php.ini 

variables_order = "EGPCS"  >>>> variables_order = "GPCS"
