### ISSUE TITLE
Route with Custom Key and Scoping ignoring Eloquent Model's resolveRouteBinding()

### ISSUE THREAD

**Issue by icaroscherma** [laravel/framework#34894]
- Laravel Version: 8.10.0
- PHP Version: 7.4.0
- Database Driver & Version: MariaDB 10.4.7

### Description:

I have a custom route binding resolver through a Trait I made and it works fine until I need to use Route Scoping, then it completely ignores it. I haven't seen any guidance regarding doing another function specifically for scoping on the docs ( https://laravel.com/docs/8.x/routing#implicit-model-binding-scoping ) .

### Steps To Reproduce:

`app/User.php`
```PHP
public function posts()
{
    return $this->hasMany(Post::class);
}
```

`app/Post.php`
```PHP
use App\Traits\HasHashidRoute;

public function user()
{
    return $this->belongsTo(User::class);
}
```

`app/Traits/HasHashidRoute.php`
```PHP
trait HasHashidRoute
{
    /**
     * @see parent
     */
    public function resolveRouteBinding($value, $field = null)
    {
        if ($field === 'hashid') {
            $field = null;
            $value = $this->decodeHashid($value);
        }
        return parent::resolveRouteBinding($value, $field);
    }
}
```

`routes/web.php`
```PHP
Route::get('users/{user}/posts/{post:hashid}', [PostController::class, 'show']);
```

`app/Http/Controllers/PostController.php`
```PHP
use App\{Post, User};
public function show(User $user, Post $post)
{
    return $post->load(['user']);
}
```

---

### Error:

Browse to `https://local/users/11/VAw9eEpl54JQRvld` then you will get:

`Illuminate\Database\QueryException`
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hashid' in 'where clause'`

```SQL
SELECT *
FROM `posts` where `posts`.`id` = 11
  AND `posts`.`id` IS NOT NULL
  AND `hashid` = 'VAw9eEpl54JQRvld'
  AND `posts`.`deleted_at` IS NULL
LIMIT 1
```

### Workaround:

If I change the controller function to the way below, it works fine.
```PHP
public function show($user, Post $post)
{
    if ($post->user_id != $user) {
        return abort(404);
    }
    return $post->load(['user']);
}
```

**Comment by icaroscherma** [comment]
It seems that this issue ( #31946 ) was ignored months ago on Laravel 7.
The bug remains unfixed or the right way of doing it remains undocumented.

**Comment by taylorotwell** [comment]
So what is the problem exactly? Does your posts table not have a `hashid` column?

**Comment by taylorotwell** [comment]
When using implicit scoped binding, we don't call `resolveRouteBinding`, we call `resolveChildRouteBinding`.

**Comment by icaroscherma** [comment]
> So what is the problem exactly? Does your posts table not have a `hashid` column?

Nope, it's a hashid that's decoded and then the query looks for the primary key (usually `id`) with the decoded input. (translate an youtube-like ID to regular integer PK)

> When using implicit scoped binding, we don't call resolveRouteBinding, we call resolveChildRouteBinding.

I tried to add the function below into `app/Posts.php` and into the `app/Traits/HasHashidRoute.php` but it didn't seem to work.

```PHP
public function resolveChildRouteBinding($childType, $value, $field) {
    dd('a');
}
```

Screenshot below:

![Screen Shot 2020-10-20 at 8 29 14 AM](https://user-images.githubusercontent.com/42467/96608545-5a170680-12ae-11eb-89ca-bf70860485d0.png)

**Comment by icaroscherma** [comment]
Nevermind, it worked, the function needs to be on the parent, which in this case it's`App\Model\User`.
It kinda breaks the trait design the way I did because for this I would need to add the Trait on both `App\Model\Post` and `App\Model\User`, but it makes sense.

I would appreciate having a note with this function on Laravel Docs thou. 😞

**Comment by driesvints** [comment]
@icaroscherma feel free to send in a PR to the docs if you think anything should be clarified further 👍

**Comment by icaroscherma** [comment]
@driesvints I'm not sure if I used the right wording but I just sent a PR with that. ;) Thanks for encouraging that.
