### ISSUE TITLE
Jobs queue:retry-batch not works

### ISSUE THREAD

**Issue by pnunas** [laravel/framework#34899]
- Laravel Version: 8.10.0
- PHP Version: 7.4.10
- Database Driver & Version: 10.4.12-MariaDB

### Description:
When I want retrying failed jobs from a batch, got an error:
`Unable to find failed job with ID`

### Steps To Reproduce:

My job_batches table row:

| id | total_jobs | pending_jobs | failed_jobs | failed_jobs_id |
|--|--|--|--|--|
| 91cf2e05-4026-46f7-aa61-9eda1a8435cc | 5 | 3 | 3 | ["25f4c4fa-5369-4719-a692-781d72a2f413","485dfd33-2005-4842-a81b-8558d9c87ece","88ffd14c-cd1f-4802-8b86-d971612cf465"] |

failed_jobs rows:

| payload |
|--|
| {"uuid":"25f4c4fa-5369-4719-a692-781d72a2f413","displayName":.... |
| {"uuid":"485dfd33-2005-4842-a81b-8558d9c87ece","displayName":.... |
| {"uuid":"88ffd14c-cd1f-4802-8b86-d971612cf465","displayName":.... |

artisan command:
`php artisan queue:retry-batch 91cf2e05-4026-46f7-aa61-9eda1a8435cc`

returns:
```
Unable to find failed job with ID [25f4c4fa-5369-4719-a692-781d72a2f413].
Unable to find failed job with ID [485dfd33-2005-4842-a81b-8558d9c87ece].
Unable to find failed job with ID [88ffd14c-cd1f-4802-8b86-d971612cf465].
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by anton-chernets** [comment]
You should change _database_ to _database-uuids_ driver in the **queue** config
` 'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
`
