### ISSUE TITLE
loadRoutesFrom doesn't accept string paths anymore

### ISSUE THREAD

**Issue by nabihnadhif** [laravel/framework#34908]
- Laravel Version: 8.11.1
- PHP Version: 7.4.11

### Description:

The merge of the PR [34866](https://github.com/laravel/framework/pull/34866/commits/81b374b9e768344a0b6ceba6e6ea03ce14877ba6) introduce a bug.
I got the following error when I upgrade to the new version.
```php
TypeError: Argument 2 passed to Laravel\Lumen\Routing\Router::group() must be an instance of Closure, string given, called in /home/vsts/work/1/s/vendor/illuminate/support/Facades/Facade.php on line 261
```
In the documentation of the group method, it's indicated that the method accept `closure` and `string` types for the second parameter. There is a mess somewhere 😬 

### Steps To Reproduce:

1. Create a package with a routes file `routes/web.php`
1. Use `$this->loadRouteFrom(__DIR__.'/../routes/web.php')` to load the routes.
1. Run a test

**Comment by taylorotwell** [comment]
Reverting.
