### ISSUE TITLE
Stringable not sharing base Str macros

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#34901]
- Laravel Version: 8.10.0
- PHP Version: 7.4.3

### Description:
When using Str macros one might expect that then using Str::of and using Str fluently, that macros would be available for use on that as well. This is not the case and attempting to use a Str macro on a Stringable instance results in an error. This while makes sense that it doesn't work is very unexpected as (correct me if I'm wrong) all other Str methods work as expected on the Stringable object, so it wouldn't be a huge leap for macros defined on the Str class would also apply to the Stringable without further work from the developer side.

### Steps To Reproduce:
1. Add a macro to Str.
2. Attempt to use the macro on a Stringable instance.

**Comment by driesvints** [comment]
Stringeable and Str are two different things so yeah this won't automatically be applied to both if you add a macro to one of them. I also don't know if it makes sense to do so.

**Comment by ragingdave** [comment]
@driesvints I understand they are separate classes, but having to add 2 identical macros when everything else just automatically works and how closely they are related seems like bad DX.

Specifically in pseudo-code, wouldn't it be nice to have the macro lookup on the Stringable class incorporate checks on the Str class like:

Stringable:
```
if (Str::hasMacro('supercool'))
return new static(Str::supercool($value));
```

In this way any macros defined on the Str helper, would be readily available on Stringable without anything like:
```
Str::macro('supercool', function () {
    // Does something super cool and returns a string
});
```
AND
```
Stringable::macro('supercool', function () {
   new static(Str::supercool($value));
});
```

**Comment by taylorotwell** [comment]
I'm not super opposed to it but it would be a breaking change I believe.
