### ISSUE TITLE
"_gid" cookie  warning

### ISSUE THREAD

**Issue by mh4620** [laravel/framework#34900]
- Laravel Version: 8.10.0
- PHP Version: 7.3.8

### Description:
Iam get this warnings from laravel:
Cookie “_ga” will be soon treated as cross-site cookie against {{address}} because the scheme does not match.
Cookie “_gid” will be soon treated as cross-site cookie against {{address}} because the scheme does not match.
Cookie “_gat” will be soon treated as cross-site cookie against {{address}} because the scheme does not match.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
