### ISSUE TITLE
Unique validation exception column with Eloquent model

### ISSUE THREAD

**Issue by Rizlantamima** [laravel/framework#34913]
- Laravel Version: 6.18.35
- PHP Version: 7.2.14
- Database Driver & Version: Oracle 12c

### Description:
I had a case when I'm using the `validate `method on `Illuminate\Http\Request`, according to the documentation the unique rules has parameter `table, column, except, idColumn`, It's very useful when the `table` parameter can be replaced with `Eloquent model`, but when I provide the `except` param with the Pk value and I leave the `idColumn` is thrown an error.
here is my code : 
```
$except_unique_id = $userRole->user_role_id;
$request->validate([
   'user_role_name' => 'string|required|unique:\App\Models\UserRole,user_role_name,'.$except_unique_id
]);
```
is thrown an error because the default value of `idColumn` is `id`.
```
"Error Code    : 904\r\nError Message : ORA-00904: \"ID\": invalid identifier\r\nPosition      : 82\r\nStatement     : select count(*) as aggregate from \"TC_USER_ROLE\" where \"USER_ROLE_NAME\" = :p0 and \"ID\" <> :p1\r\nBindings      : [Superadmin,12]\r\n (SQL: select count(*) as aggregate from \"TC_USER_ROLE\" where \"USER_ROLE_NAME\" = Superadmin and \"ID\" <> 12)
```
I know it can be resolve when I provide the `idColumn` param with `user_role_id` (the Pk Column).

but I expect since we can provide the `table` param with `Eloquent model`, maybe the default value of `idColumn` param, should belong to the `$primaryKey` object on the Model.

**Comment by taylorotwell** [comment]
So the code you posted above gets an error? But you included the user_role_name?

**Comment by Rizlantamima** [comment]
@taylorotwell no Sir, I got an error because the default value for `idColumn`  is `ID`, but the PK on my Model isn't `ID` but `user_role_id`, however it could be solved if I provide the `idColumn` parameters with my own PK. 

this one is error :
```
$request->validate([
   'user_role_name' => 'string|required|unique:\App\Models\UserRole,user_role_name,1'
]);
```

this one is success : 
```
$request->validate([
   'user_role_name' => 'string|required|unique:\App\Models\UserRole,user_role_name,1,user_role_id'
]);
``` 

`unique:table,column,except,idColumn`
I just expect since we can use `Model` on the `table` param, the default value for `idColumn` should be get from the PK on the `Model` itself

**Comment by Organizm238** [comment]
@Rizlantamima 
Looking at the source code, it should work exactly as you want. Have you specified `$primaryKey` in your eloquent Model?

**Comment by taylorotwell** [comment]
Yeah, we already call `$model->getKeyName()` make sure you are setting your key properly in the model.

**Comment by taylorotwell** [comment]
Looks like the behavior may have been different on 6.x but it is how you describe on 8.x.
