### ISSUE TITLE
\Route::currentRouteName() always return null on laravel 7.28.4

### ISSUE THREAD

**Issue by dominservice** [laravel/framework#34914]
- Laravel Version: 7.28.4
- PHP Version: 7.3.22 
- Database Driver & Version: 10.4.14-MariaDB

### Description: 
When I try to check what the name of the current route is, I get null every time.
On Laravel 5.x it works fine, but with this version of Laravel I keep getting null

### Steps To Reproduce:
in any controller, view, middleware set: dd(\Route::currentRouteName());

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by dominservice** [comment]
Hey @driesvints 
on middleware steel not work after upgrade to laravel 8.11.2

**Comment by dominservice** [comment]
I found a solution, so if someone has a similar problem, use the following code in middleware.

        $route = \Route::getRoutes()->match($request);
        $routeName = $route->action['as'];

best regards
