### ISSUE TITLE
app()->call() gives an error when calling a static function using (array) parameters

### ISSUE THREAD

**Issue by lethalcreed** [laravel/framework#34920]
- Laravel Version: 6.19.1
- PHP Version: 7.4.8

### Description:
The release of 6.19.1 introduced a bug.

I got the following error message on all my app->call methods after upgrading from version 6.19.0:

` Illuminate\Contracts\Container\BindingResolutionException  : Unable to resolve dependency [Parameter #0 [ <required> $files ]] in class studioprojectie\prowriterxcore\Http\Services\SymlinkService`

### Steps To Reproduce:

1. Create a static class with a public static function using an array parameter.
2. Call the function from a file that is always loaded like `AppServiceProvider`
3. Run a test.

**Comment by taylorotwell** [comment]
@lethalcreed Provide exact classes and code I can paste into a blank Laravel project to recreate this please.

**Comment by lethalcreed** [comment]
Sorry ofcourse: 

1. Create a php file called `TestService.php` on location /app/Http/Services.

2. Put the following in de TestService.php file:
```
<?php

namespace App\Http\Services;

class TestService
{
    /**
     * @param array $array
     */
    public static function test(array $array)
    {
        dd($array);
    }
}
```

3. Paste this in the `AppServiceProvider` boot method:
`app()->call('App\Http\Services\TestService@test', ['test']);`

4. Visit laravel project in browser

This triggers the `Illuminate\Contracts\Container\BindingResolutionException
Unable to resolve dependency [Parameter #0 [ <required> array $array ]] in class App\Http\Services\TestService` error.

**Comment by dkulyk** [comment]
But works well:
```php
app()->call('App\Http\Services\TestService@test', ['array' => ['test']]);
```

**Comment by lethalcreed** [comment]
Aha so the key of the parameter array must be the name of the variable in the called function. 

It seems like I mis understood the way the app()->call() function works and because of the bug (that's fixed in v6.19.1) it worked for me in the older versions withouth explicitly naming the parameters. 

My understanding was that the order of the parameters in the array parsed to the call function would just translate to the order of parameters on the called function and it behaved that way in older versions but this makes sense too.

Thanks for the help!

**Comment by GrahamCampbell** [comment]
But you're saying this other code used to work before, say on **6.18.0**?

**Comment by GrahamCampbell** [comment]
We probably don't want to break code like that.

**Comment by lethalcreed** [comment]
It did, it even worked in 6.19.0. My test code posted above also runs fine in these older versions. 

I already fixed this in all my code but i can imagine there might be some other people scratching there head over this.

**Comment by driesvints** [comment]
Your example doesn't even work for me on v8.5.0 so I don't think this could have ever worked tbh.

**Comment by lethalcreed** [comment]
That is because this is a laravel v6 issue. I am aware that it doesn't work in v8.

**Comment by driesvints** [comment]
If I test your example in v6.19.0 or any version below I get:

```
Argument 1 passed to App\TestService::test() must be of the type array, string given, called in /Users/driesvints/Sites/test-laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 31
```

But when I test: `app()->call('App\Http\Services\TestService@test', [['test']]);` it works without the named key. So that part indeed seem to have been changed. We don't document this usage anywhere in the docs however so I'm not sure if we ever supported that. 

I'll leave it up to @taylorotwell to decide on it. Thanks.

**Comment by taylorotwell** [comment]
I would imagine this is probably easy for us to fix so we should probably just correct the call_user_func_array call that was removed? @GrahamCampbell @driesvints

**Comment by driesvints** [comment]
Found the culprit: https://github.com/laravel/framework/pull/34970

**Comment by taylorotwell** [comment]
Fixed in next patch.

**Comment by taylorotwell** [comment]
Hey @lethalcreed ... unfortunately we are going to have to revert this behavior. Supporting this causes other (bigger) problems. For now we suggest passing the keys of the argument names in your parameters array.
