### ISSUE TITLE
Route::view() and Route::redirect() methods have reserved parameter names

### ISSUE THREAD

**Issue by jhoff** [laravel/framework#34939]
- Laravel Version: 5.5 -> 8.x
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

Using `Route::view()` or `Route::redirect()` with specifically named route parameters causes unexpected behavior.

Method | Reserved parameter
------------ | -------------
Route::redirect() | `destination`
&nbsp; | `status`
Route::view() | `view`
&nbsp; | `data`
&nbsp; | `status` ( 8.0+ )
&nbsp; | `headers` ( 8.0+ )

### Steps To Reproduce:

Add any of the following routes to invoke error

`Route::redirect('foo/{destination}', 'bar');` -> `ERR_TOO_MANY_REDIRECTS`
`Route::redirect('foo/{status}', 'bar');` -> `Argument 2 passed to Symfony\Component\HttpFoundation\RedirectResponse::__construct() must be of the type int, string given`

`Route::view('foo/{view}', 'bar');` -> `View [XXX] not found.`
`Route::view('foo/{data}', 'bar');` -> `View [XXX] not found.`
`Route::view('foo/{status}', 'bar');` -> `View [XXX] not found.`
`Route::view('foo/{headers}', 'bar');` -> `Argument 4 passed to Illuminate\Routing\ResponseFactory::view() must be of the type array, int given`

### Cause

Both of these route methods are setting defaults on the route when invoked, which are then overridden by route parameters:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/Router.php#L246-L247

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/Router.php#L275-L280

### Solution

Without digging further into the router internals, I'm not sure this is something that can or should be solved.

Maybe the best remediation is to simply add a note to the [documentation](https://laravel.com/docs/8.x/routing#route-parameters)?

**Comment by driesvints** [comment]
Good catch. I've sent in a PR to the docs about this: https://github.com/laravel/docs/pull/6518
