### ISSUE TITLE
database config option not taken into account

### ISSUE THREAD

**Issue by lolo3129** [laravel/framework#34933]
- Laravel Framework Version: 8.10.0
- PHP Version: 7.3.23
- Database Driver & Version: mysql

### Description:
I use certificate to access a mysql database.
I added option in config database file. 
the certificate I use is not validated (slight CN diff)
as it is not production environment, I don't really care
I added a parameter to ignore certificate validation, but the parameter is ignored and I can't connect
I had to

### Steps To Reproduce:

I changed database.php config file adding options : 
           'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA', "ca-cert.pem"),
                PDO::MYSQL_ATTR_SSL_CERT => env('MYSQL_ATTR_SSL_CERT', "client-cert.pem"),
                PDO::MYSQL_ATTR_SSL_KEY => env('MYSQL_ATTR_SSL_KEY', "client-key.pem"),
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('MYSQL_ATTR_SSL_VERIFY_SERVER_CERT', 0),
            ]) : [],

the 3 firsts params are taken into account from the .env file but not the 4th
I had to change the framework file ( Illuminate\Database\Connectors\Connector.php) and default protected $options value to make it work

If I set 1 as default value 1, or set 1 as .env value, it is correctly propagated to the config value, but not 0

**Comment by hyperalghorithm** [comment]
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => env('MYSQL_ATTR_SSL_VERIFY_SERVER_CERT', 0),

The env file loads values as string. You need true or false.
https://laravel.com/docs/8.x/configuration#environment-variable-types

PHP will load false if the number zero is a string "0" and true if it's a number (this includes 1 and 0) or a non-empty string. https://www.php.net/manual/en/language.types.boolean.php

PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => "0", // false
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => "1", // true
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 1, // true
PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => "1", // true

Just set MYSQL_ATTR_SSL_VERIFY_SERVER_CERT in your env to true or false as well as the defaults in the config

**Comment by lolo3129** [comment]
thank you ! i will better RTFM next time !
