### ISSUE TITLE
assertJson() and json_decode ASSOC behaviour

### ISSUE THREAD

**Issue by danilopolani** [laravel/framework#34946]
- Laravel Version: 8.11.2
- PHP Version: 7.4.10
- Database Driver & Version: N/A

### Description:
`assertJson()` by default sets the `$assoc` argument of `json_decode` to true and due to this behaviour objects are casted to array and testing the returned by an API is not always possible because `[]` is different from '{}` and our API must return an empty object, not an empty array.

### Steps To Reproduce:

1. Create this route

```php
Route::get('/test', fn () => response()->json([
  'foo' => 'bar',
  'obj' => (object) ['foo' => 'bar'],
  'emptyObj' => new \stdClass(),
]));
```

2. Create a test asking for the exact json (I'm using PestPHP but works too with PHPUnit)

```php
getJson('/test')
    ->assertExactJson([
      'foo' => 'bar',
      'obj' => (object) ['foo' => 'bar'],
      'emptyObj' => new \stdClass(),
    ]);
```

Running the test the output will be:

```
--- Expected
+++ Actual
@@ @@

  -'{"emptyObj":{},"foo":"bar","obj":{"foo":"bar"}}'
  +'{"emptyObj":[],"foo":"bar","obj":{"foo":"bar"}}'
```

Currently I solved this by checking the `->getContent()` value of the JSON request, but an argument or method to change this behaviour would be nice IMHO

**Comment by driesvints** [comment]
We can't really solve this since if we provided an argument for it there could still be situations where mixed content (both arrays and objects) would debunk this.
