### ISSUE TITLE
 ParseError

### ISSUE THREAD

**Issue by alexander-lawaetz** [laravel/framework#34942]
- Laravel Version: 8.11.2
- PHP Version: 7.4.11
- Database Driver & Version:  mysql 5.7.24

### Description:
ERROR:
![Laravel-v 8 4 11-terminal-error-log](https://user-images.githubusercontent.com/73331861/96980559-b46ace00-151f-11eb-83e4-eeb2a7c42fb4.JPG)

FIX

Original

![Laravel-v 8 4 11-vs-code-original](https://user-images.githubusercontent.com/73331861/96981920-09a6df80-1520-11eb-88d2-9eee401ebce7.JPG)

Solution

Remove end of line , on line 50

![Laravel-v 8 4 11-vs-code-solution](https://user-images.githubusercontent.com/73331861/96980602-b6cd2800-151f-11eb-86de-a816a8ca799c.JPG)

### Steps To Reproduce:
php artisan
php artisan migrate

**Comment by alexander-lawaetz** [comment]
Sorry for the inconvience, my Laragon cli wasn't updated to my newly added php version.
Everything works as attenteded with php 7.4.11

**Comment by spacedog4** [comment]
but Laravel shouldn't work with php 7.3?
