### ISSUE TITLE
throttle api

### ISSUE THREAD

**Issue by rst630** [laravel/framework#34956]
- Laravel Version: Laravel Framework 8.11.2
- PHP Version: 7.4
- Database Driver & Version:

Jetstream / Inertia

### Description:
```
    protected $middlewareGroups = [
        'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

by default throttle:api enabled in api section. When I doing axios.get(/api/user) or any other api route, I got answer delay 3-4 sec and huge load on server (CPU) even if I request this route 1 time per 3 sec. Even if in route just closure which return immediatly.

```
Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return 1;
});
```

Why this happens? If I disabling 'throttle:api' - all works fine and I got answer from endpoint in 80-100ms

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
