### ISSUE TITLE
Recent change to refresh() and fresh() methods caused BC breakages

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#34954]
- Laravel Version: 8.11.2
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7

### Description:
I'm hoping it might be possible to revisit the changes in PR #34836. With those changes, Laravel now invokes the `setKeysForSaveQuery()` method every time an Eloquent model calls `fresh()` or `refresh()`. In my case, this broke a ton of code, since I'm currently overriding that method for my implementation of optimistic locking on certain records. 

I can change my implementation of the locking logic easily enough, but before I do that, I wanted to just raise a flag, since this seems like an abuse of the `setKeysForSaveQuery()` method. Should Laravel really be calling that method outside of a save query? Calling it during fresh() or refresh() is unexpected based on the method's name.

### Steps To Reproduce:
N/A

**Comment by taylorotwell** [comment]
It's possible we could create a new method like `setKeysForSelectQuery` or something.

**Comment by adamthehutt** [comment]
@taylorotwell Thanks for the reply. That would be a lot clearer and semantically consistent, IMO.

**Comment by driesvints** [comment]
@adamthehutt yeah, feel free to send in a PR. Thanks 👍
