### ISSUE TITLE
Specifying connection in migration is ignored

### ISSUE THREAD

**Issue by jaketoolson** [laravel/framework#34962]
- Laravel Version: 8.11.2
- PHP Version: 7.4.6
- Database Driver & Version: SQLite

### Description:
Trying to run migrations against a specific connection always uses the default db connection found at `config.database.default`. 

If I change my default connection to reflect the connection I'm trying to run in the migration, the migration runs successfully (which confirms it can find/read the sqlite file)

I'm using a fresh install of Laravel with little changes.

### Steps To Reproduce:
`config/database.php` excerpt:
```
[
    'connections' => [
        'testdb' => [
            'driver' => 'sqlite',
            'database' => database_path('temp.sqlite')
        ],
     ]
]
```

Sample Migration wrapped in `Schema::connection` ignores the connection specified:
```
class CreateInventoryTable extends Migration
{
    public function up()
    {
        Schema::connection('testdb')->create('tbl', function (Blueprint $table) {
            $table->id();
        });
    }
}
```

Setting `$connection` ignores the connection specified:
```
class CreateInventoryTable extends Migration
{
    public $connection = 'testdb';
}
```

**Comment by ahinkle** [comment]
Hmm, works for me.

> Schema::connection('connection')

Is this just an example,  or should you try `Schema::connection('sqlite')`?

**Comment by jaketoolson** [comment]
> Hmm, works for me.
> 
> > Schema::connection('connection')
> 
> Is this just an example, or should you try `Schema::connection('sqlite')`?

Sorry, my example was incorrectly.  I updated it.

**Comment by jaketoolson** [comment]
I think I figured out part of it -- I have _never_ run migrations.  So the only migration I have, I'm trying to migrate to a DB connection that is different than the default set in the config.  

So it looks like it's trying to first check if the migration has been run (against default DB) - and my default DB isn't yet configured, this is why it continues to fail -- it can't connect to the default DB and check the migrations table.

**Comment by driesvints** [comment]
@jaketoolson does the solution from Passport work for you? 

https://github.com/laravel/passport/blob/master/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php

**Comment by jaketoolson** [comment]
@driesvints - The problem is, if I try to run a migration against a different connection than the default, if the system is unable to connect to the default db (to find the migrations table), everything fails.

So what I originally thought was my migrations failing to respect the specific connection I specified, I've since realized it's having to deal with the system looking for a migrations table somewhere before it actually runs a migration (does this make sense? haha)

**Comment by driesvints** [comment]
Ah right. Yeah you always need a migrations table present on any connection. That's expected. When working with multiple connections you'll run into this. We could maybe clarify this in the docs. Thanks for raising.
