### ISSUE TITLE
morphedByMany "manipulates" column on morphed table if it starts with "pivot"

### ISSUE THREAD

**Issue by syron0** [laravel/framework#34966]
- Laravel Version: 8.11.2
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 5.7.29

### Description:
I'm connecting two models with a polymorphic many to many relationship.
Model `System` defines a `morphedByMany` relationship towards `PivotPointsSystem`.

The problem arise because `PivotPointsSystem` has a column called `pivot_points_id`, which will end inside `MorphPivot` object as `points_id`, thus making impossible to navigate further relationships.

This is the result if I query `PivotPointsSystem` directly:
![image](https://user-images.githubusercontent.com/46669600/97122401-dcc41980-1725-11eb-8a4c-9e77e7748400.png)

While this is the result if I navigate `morphedByMany` relationship:
![image](https://user-images.githubusercontent.com/46669600/97122200-6541ba80-1724-11eb-9f32-740bb6bad1ce.png)

Thank you in advance.

### Steps To Reproduce:
I created a public [minimal repo](https://github.com/syron0/laravel-morphed-by-many-issue) to reproduce the issue, which uses Docker for convenience.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by syron0** [comment]
Hi @driesvints, thanks for your reply.
I surely don't want to sound rude in any way and I could ask on support channels, but there's no way this is not a bug.

The column I indicated, since it starts with `pivot`, is literally taken out of the model and included in the `MorphPivot` model.
Being it a foreign key it makes impossible to navigate further relationships if not by reloading/refreshing the same model.

I even tried using a custom MorphPivot model and aliasing it using `->as`, with no luck.

**Comment by driesvints** [comment]
@syron0 can you first try some support channels? Maybe some people have other insights. As soon as you've confirmed this with others feel free to re-open a new issue 👍
