### ISSUE TITLE
The GET method is not supported for this route. Supported methods: HEAD.

### ISSUE THREAD

**Issue by technicalheist** [laravel/framework#34977]
- Laravel Version: 8.x
- PHP Version: 7.4.10
- Database Driver & Version: 10.4.14-MariaDB (No Use)

#### here is the steps to regenerate the issue 

Here is the problem :

- Step : 1 Create a new laravel project using:
```
 composer create project laravel/laravel testapp
```
- Step : 2 Go to Browser navigate to url : http://localhost/testapp/public (I am using apache or xampp server) everything works fine

- now Step 3 : Go to Console and type ``` php artisan optimize ```  you will see some cache is cleared and optimized.

after then again go to browser and refresh the page : http://localhost/testapp/public

you will see this error : https://prnt.sc/v7lfzt

I am using windows 10 and xampp server.

**Comment by rodrigopedra** [comment]
Per its docs, Laravel does not support serving an app from a subfolder.

> You should not attempt to serve a Laravel application out of a subdirectory of the "web directory"

Reference: https://laravel.com/docs/8.x#directory-configuration

For example when you cache your routes (which the `optimize` command does under the hood), Laravel does some optimizations that breaks serving an app from a subfolder. This is why your app ceases to work after running that command.

To revert route caching, you can run: 

~~~bash
$ php artisan optimize:clear
~~~

Or remove all `.php` files from your project's `./bootstrap/cache/` folder.

There are many closed issues relating similar problems when serving a Laravel app from a subfolder and the official instance is that this kind of setup is not supported.

Some references from a search on Laravel's GitHub issues tracker:

https://github.com/laravel/framework/issues/32236#issuecomment-692546842

https://github.com/laravel/framework/issues/32082#issuecomment-604986571

**Comment by rodrigopedra** [comment]
Also you should configure your server to not need to type `/public` to access a Laravel application. This is a security measure to prevent access to your app's source code and sensitive assets.

**Comment by driesvints** [comment]
Please see the above.

**Comment by technicalheist** [comment]
Above solution worked for me...Thank you so much
