### ISSUE TITLE
renameColumn removes the unsigned on a tinyint

### ISSUE THREAD

**Issue by d3v1** [laravel/framework#35008]
- Laravel Version: 8.11.2
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 8.0.21

### Description:

When renaming an unsigned tinyint column using migrations I noticed the column became signed. I could not recreate this behaviour on other integer types.

### Steps To Reproduce:

1. Create a table with an unsigned tinyint
2. Rename the column
3. See the column is now signed

**Comment by taylorotwell** [comment]
This is a `doctrine/dbal` issue: https://github.com/doctrine/dbal

You can see that the TableDiff we hand them has unsigned = `true` - but the table alter SQL they create loses the unsigned:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/463230/97591528-b45e4880-19cd-11eb-9783-3d764d48527f.png">

<img width="707" alt="image" src="https://user-images.githubusercontent.com/463230/97591549-b9bb9300-19cd-11eb-9c2f-170328a4bf6a.png">

**Comment by taylorotwell** [comment]
I suggest reporting it to them. There is nothing we can do about it here.

**Comment by d3v1** [comment]
Thanks for looking. I'll do that

**Comment by halloei** [comment]
I just ran into this bug. You didn't report it to `doctrine/dbal`, did you @d3v1?

**Comment by d3v1** [comment]
Sorry @halloei, I could not make the time after being shifted to another project. I've not been back on the project for a while.

Please accept my apologies, I know it will have been a painful issue to trace

**Comment by d3v1** [comment]
I'm back on the Laravel side of things and I started off by investigating this a little further and `doctrine/dbal` doesn't actually support tinyint as a column type. When renaming this column type we probably get unexpected results for that reason. I thought this might be useful for you to know @halloei 

Supported types for dbal: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html
Old discussion about the tinyint type: https://github.com/doctrine/dbal/issues/2830
