### ISSUE TITLE
How to stop swift mailer exception if host is not valid?

### ISSUE THREAD

**Issue by CloudVisionBulgaria** [laravel/framework#35009]
{
  "message": "Connection could not be established with host emailpwd.com1 :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: No such host is known. ",
  "exception": "Swift_TransportException",
  "file": "\\vendor\\swiftmailer\\swiftmailer\\lib\\classes\\Swift\\Transport\\StreamBuffer.php",
  "line": 261,
  "trace": [
    {
      "function": "{closure}",
      "class": "Swift_Transport_StreamBuffer",
      "type": "->"
    },

**Comment by taylorotwell** [comment]
This is not an issue with the Laravel framework.
