### ISSUE TITLE
Route::resources unable to map to Fully Qualified Class Names

### ISSUE THREAD

**Issue by 4050350194** [laravel/framework#35014]
- Laravel Version: 8.10.0
- PHP Version: 7.4.2
- Database Driver & Version: N/A

### Description:

I'm unable to specify a *Fully Qualified Class Name* when specifying resource controllers map with `Route::resources`.

Documentation for resource controllers [is located here](https://laravel.com/docs/8.x/controllers#resource-controllers).

### Steps To Reproduce:

Define a resource controller routes like this (I'm using this for Inertia + JetStream):

```php

use App\Http\Controllers\SomeController;

...

Route::resources([
    'some' => SomeController::class,
]);
```

Nor will this help:

```php

Route::resources([
    'some' => \App\Http\Controllers\SomeController::class,
]);
```

### Result when using the above

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Http\Controllers\App\Http\Controllers\SomeController] does not exist.
http://environment.test/some
```

Note the recurring namespace:

```
App\Http\Controllers
```

And then followed again by:

```
App\Http\Controllers\SomeController
```

Thus constructing an incorrect *FQCN*.

### Current solution for me (at least)

*Old-style* mapping to a controller:

```php
Route::resources([
    'some' => 'SomeController',
]);
```

**Comment by rodrigopedra** [comment]
Do you have a `$namespace` property in your project's `RouteServiceProvider`?

If so, you should remove that, otherwise it will get prepended to your Controllers FQCN

**Comment by 4050350194** [comment]
> Do you have a `$namespace` property in your project's `RouteServiceProvider`?
> 
> If so, you should remove that, otherwise it will get prepended to your Controllers FQCN

Thank you, sire!

Now it works like a charm.

I totally didn't knew about `RouteServiceProvider::$namespace` property and it's behavior.

I'll close this issue right now.

**Comment by rodrigopedra** [comment]
You're welcome!

On a fresh Laravel 8 install, this parameter should be missing from the `RouteServiceProvider` and by consequence be null. 

If you migrated from an older version, don't miss reading the Upgrade Guide. This change is highlighted here:

https://laravel.com/docs/8.x/upgrade#automatic-controller-namespace-prefixing

Also, if this is an existing app that you migrated to Laravel 8, and is trying to install Jetstream on it, bear in mind, per Jetstream docs, that Jetstream is only meant to be installed on new applications. Its docs recommends not to install it on existing applications:

> Jetstream is only meant to be installed on new Laravel projects. You should not attempt to migrate an existing project to Jetstream.

Reference: https://jetstream.laravel.com/1.x/installation.html

If it is a fresh Laravel 8 installation, please ignore my remarks.

Have a nice day =)
