### ISSUE TITLE
Route::resource and apiResource interfering with get routes

### ISSUE THREAD

**Issue by Chico3001** [laravel/framework#35011]
- Laravel Version: 8.11.2
- PHP Version: 7.4.5

### Description:
Adding new get routes below a previous resource route will result in a 404 not found error 

### Steps To Reproduce:

In web.php i had:

```
	Route::apiResource('encuestas', SurveyController::class);
	Route::get('encuestas/covid', [SurveyController::class, 'covid'])->name('encuestas.covid');
	Route::get('encuestas/tos', [SurveyController::class, 'cough'])->name('encuestas.cough');
	Route::get('encuestas/temperatura', [SurveyController::class, 'temperature'])->name('encuestas.temperature');
```
 
With this configuration any attempt to enter to any new encuestas named routes will result in a 404 not found error, to fix it i had to setup in this configuration (moving apiResource to the end) :

```
	Route::get('encuestas/covid', [SurveyController::class, 'covid'])->name('encuestas.covid');
	Route::get('encuestas/tos', [SurveyController::class, 'cough'])->name('encuestas.cough');
	Route::get('encuestas/temperatura', [SurveyController::class, 'temperature'])->name('encuestas.temperature');
	Route::apiResource('encuestas', SurveyController::class);
```

This bug will also appear using resource instead of apiResource

**Comment by rodrigopedra** [comment]
It is not a bug. I'd say it is a limitation. The

~~~php
Route::apiResource('encuestas', SurveyController::class);`
~~~

Will register several routes under the hood. One of them, to retrieve a single resource, will be:

~~~
GET /encuestas/{encuesta}
~~~

Which accepts a second parameter that can be anything.

So when the router tries to match this path: `/encuestas/covid`, if API Resource is defined before the route you expected, the router will match this path against `/encuestas/{encuesta}` and will try to run the associated controller action  (`SurveyController@show`).

There are a couple of ways you could avoid it, one is using route parameter constraints:

https://laravel.com/docs/8.x/routing#parameters-global-constraints

So the pattern is more unlikely to be match, if for example your model identifier is an integer or an UUID.

But I think the easiest solution is to define routes with dynamic paths before routes with static paths.

**Comment by taylorotwell** [comment]
See above.
