### ISSUE TITLE
Laravel Eloquent `value()` failed with join & table aliases.

### ISSUE THREAD

**Issue by gusdecool** [laravel/framework#35019]
- Laravel Version: 6.18.36
- PHP Version: 7.3.*
- Database Driver & Version: MySQL 5.6

### Description:

Laravel Eloquent builder failed to get scalar value if we have join table and table aliases.

### Steps To Reproduce:

Consider we have 2 tables: `company` & `company_site` and both table have column called `alias`

```php
$foo = Company::from('company as c')
    ->join('company_site as cs', 'c.companyID', '=', 'cs.companyID')
    ->where('cs.alias', '=', 'foo')
    ->value('c.alias');
```

In here, we're trying to get scalar of `company.alias` where `company_site.alias` is `foo`. In `value(...)` method we should select by table alias `c.alias` otherwise the SQL will error due to ambigous which `alias` column we refer here, as it could be either from `company_site` or `company`.

This is the source code of the method https://github.com/laravel/framework/blob/500798623d100a9746b2931ae6191cb756521f05/src/Illuminate/Database/Eloquent/Builder.php#L510-L515

**At line 512**, the query successfully retrieved the single result with `$column = c.alias` but **at line 513** it will failed due the attributes are listed as `alias` not `c.alias`.

**Comment by taylorotwell** [comment]
Fixed on next patch release.

**Comment by rodrigopedra** [comment]
Well, when having conflicting column names, the SQL resultset from PDO will not include the table alias as you can see in this plain PHP script:

~~~php
<?php

$sql =<<<SQL
WITH `company` AS (
    SELECT 1 AS `companyID`, 'foo' AS `alias`
    UNION
    SELECT 2, 'bar'
    UNION
    SELECT 3, 'baz'
),
`company_site` AS (
    SELECT 1 AS `companyID`, 'foo' AS `alias`
    UNION
    SELECT 2, 'bar'
    UNION
    SELECT 3, 'baz'
)
SELECT *
FROM
    company as c
    JOIN company_site as cs
        ON c.companyID = cs.companyID
WHERE cs.alias = 'foo'
SQL;

$pdo = new \PDO('mysql:host=127.0.0.1;dbname=dummy', 'root', '123456');

$statment = $pdo->query($sql, \PDO::FETCH_ASSOC);
~~~

output:

~~~bash
$ php scratch.php 
Array
(
    [0] => Array
        (
            [companyID] => 1
            [alias] => foo
        )

)
~~~

So there is not much Laravel can do to differentiate between conflicting columns.

What you can do is use `->selectRaw` or other select methods to alias the column names:

~~~php
$foo = Company::from('company as c')
    ->selectRaw('c.alias AS return_value')
    ->join('company_site as cs', 'c.companyID', '=', 'cs.companyID')
    ->where('cs.alias', '=', 'foo')
    ->value('return_value');
~~~

**Comment by rodrigopedra** [comment]
I was typing my response before I see @taylorotwell 's response.

Maybe they found a clever way to overcome this limitation. Or there might be a PDO configuration I am not aware of which return conflicting column names.
