### ISSUE TITLE
Eager Loading Specific Columns cause MySQL Error when using custom pivot model with autoincrementing id

### ISSUE THREAD

**Issue by KenLewis** [laravel/framework#35016]
- Laravel Version: 8.11.2
- PHP Version: 7.3.23
- Database Driver & Version: MySQL 5.6.x

### Description:
When eager loading specific columns for a belongsToMany relationship which has a custom pivot table that has an auto-incrementing id as the pivot tables primary key, MySQL spits out `SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous`. 

This is due to the Eloquent Builder class' `createSelectWithConstraint` method not prefixing the columns with the related table's name.

### Steps To Reproduce:
- Create 2 models that have `belongsToMany` relation to each other

```
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Element extends Model
{
    public function software()
    {
        return $this->belongsToMany(Software::class)
                    ->using(ElementSoftware::class);
    }
}
```

```
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Software extends Model
{
    public function elements()
    {
        return $this->belongsToMany(Element::class)
                    ->using(ElementSoftware::class);
    }
}
```

Then create a custom pivot table model.

```
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;

class ElementSoftware extends Pivot
{
    public $incrementing = true;
}
```

Then in a controller, try to query for data using eager loading with specific columns.

```
<?php
namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Software;

class SoftwareController extends Controller
{
    public function index()
    {
        return Software::with(['elements:id,name,description'])->get();
    }
}
```

Since the elements columns are not prefixed with the table name (like they are in most other places), MySQL gets confused with the 2 'id' columns (elements.id and element_software.id).

The resulting eager loading query looks like this:

```
SELECT 
    `id`,
    `name`,
    `description`,
    `element_software`.`software_id` AS `pivot_software_id`,
    `element_software`.`element_id` AS `pivot_element_id`
FROM
    `elements`
        INNER JOIN
    `element_software` ON `elements`.`id` = `element_software`.`element_id`
WHERE
    `element_software`.`software_id` IN (1, 2, 3, 4)
        AND `elements`.`deleted_at` IS NULL
```

And it returns this error:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous
```

The query should look like this:
```
SELECT 
    `elements`.`id`,
    `elements`.`name`,
    `elements`.`description`,
    `element_software`.`software_id` AS `pivot_software_id`,
    `element_software`.`element_id` AS `pivot_element_id`
FROM
    `elements`
        INNER JOIN
    `element_software` ON `elements`.`id` = `element_software`.`element_id`
WHERE
    `element_software`.`software_id` IN (1, 2, 3, 4)
        AND `elements`.`deleted_at` IS NULL
```

**Comment by taylorotwell** [comment]
You need to add the `select` call on your Eloquent query if you're going to be manually selecting ambigious columns.

**Comment by KenLewis** [comment]
@taylorotwell my query that I am actually using is:

```
Software::select("software.*")
                       ->with([
                               'elements:id,name,description',
                           ]);
```

**Comment by taylorotwell** [comment]
Got it. Just curious, why are you wanting to select specific columns on the relationship? 😄  Just so I can get a good sense of the use case here.

**Comment by KenLewis** [comment]
It's definitely an edge case.

You can blame Spatie and their ActivityLogger package. Haha. It needs the autoincrementing id column if I want to use their LogsActivity trait on a pivot table.

I've already worked around the issue by removing the constraints from the `with()` and added them to the model's `$hidden`. This accomplishes the same thing, but I only did that after digging into this issue today. I figured it'd be an easy enough thing to fix, but I'd have to rewrite that function and I guessed you'd end up rewriting it the way you wanted it.

**Comment by taylorotwell** [comment]
Fixed in next patch release. Thanks.

**Comment by KenLewis** [comment]
Thank you @taylorotwell !
