### ISSUE TITLE
[8.x] Factories do not resolve nested relationships

### ISSUE THREAD

**Issue by axlon** [laravel/framework#35024]
- Laravel Version: 8.11.2
- PHP Version: 7.4.8
- Database Driver & Version: N/A

### Description:
When creating relations through the `Factory::has()` method nested relations are not created.

Example (I skipped the factories, because nothing except for the relations is really relevant here)

```php
class A extends Model
{
    public function b()
    {
        return $this->hasOne(B::class);
    }
}

class B extends Model
{
    public function c()
    {
        return $this->hasOne(C::class);
    }
}

class C extends Model
{
    //
}
```

And then:

```php
A::factory()->has(B::factory()->hasC())->create(); // Will create an A with a B, but no C
A::factory()->has(B::factory()->has(C::factory())->create(); // Same thing
```

~The problem appears to lie in the `Relationship` and `BelongsToManyRelationship` classes, which never call `Factory::createChildren()` (which is a protected method)~

### Steps To Reproduce:
- Create the models as detailed above, with model factories
- Create a test containing part 2 of my example

**Comment by driesvints** [comment]
Gonna forward this one to Taylor to see if that's intended or not.

**Comment by taylorotwell** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/463230/97588487-89bec080-19ca-11eb-9af2-fc942c81b570.png">

**Comment by axlon** [comment]
I just tried it on a fresh Laravel application and was able to reproduce it, I'll try to debug further

**Comment by taylorotwell** [comment]
How did you reproduce it?

**Comment by axlon** [comment]
I created a new Laravel app and added the models A, B and C including migrations and tests however this time even B is not being created, so I think I must be doing something wrong otherwise a lot more people would be running into this issue.

Example code is [here](https://github.com/axlon/tmp/blob/master/tests/Feature/ExampleTest.php#L27) (this line is where the test fails)

**Comment by taylorotwell** [comment]
You're using `belongsTo` to link A and B but you're creating B from A as if it was a child.

**Comment by axlon** [comment]
Ah it seems this was the issue (it was actually a copy-paste error in the example I created, but I think it will probably be something similar in my actual project) thanks for checking 👍
