### ISSUE TITLE
Undefined table exception due to createSelectWithConstraint change

### ISSUE THREAD

**Issue by leigeber** [laravel/framework#35028]
- Laravel Version: 8.12.1
- PHP Version: 7.5.6
- Database Driver & Version: PostgreSQL 12.2

### Description:

The change in https://github.com/laravel/framework/commit/500798623d100a9746b2931ae6191cb756521f05 doesn't account for pre-existing prefixed columns in subset eager loading to prevent ambiguous queries. The result is errors like "Undefined table: 7 ERROR:  invalid reference to FROM-clause entry for table ...".

Something like ->with('profiles:profiles.id,image') for instance throws a query exception now. Not sure if the map should check for an existing period before concatenation? I'm assuming others may run into this when updating.

**Comment by taylorotwell** [comment]
Fixed in upcoming patch release today.
