### ISSUE TITLE
clear-compiled fail

### ISSUE THREAD

**Issue by seth-shi** [laravel/framework#35021]
- Laravel Version: 7.x
- PHP Version: 7.4
- Database Driver & Version: 5.7

### Description:
I in the `config/app.php` added a service provider,` XXXServerProvider: : class`, and then submit the code.The production environment generates cache files in `bootstrap/ cache`

When I next updated the code to remove the `XXXServerProvider:class` from `config/app.php`, this was normal at the time of my local development.As I deploy the code to production, because it is automated, running Composer install will fail because there are already `php atisan clear-compiled`. Clear-compiled will load the `bootstrap/cache` cache class again, but I have removed the code
![image](https://user-images.githubusercontent.com/28035971/97551385-e2fc1380-1a0d-11eb-8df6-10ea4e6c3af3.png)

**Comment by seth-shi** [comment]
Now I'm adding an automatic deployment script
```
rm bootstrap/cache/packages.php
rm bootstrap/cache/services.php
```
But I don't think it's an elegant solution

**Comment by driesvints** [comment]
You reported this under 7.x which isn't supported anymore but I can also reproduce this in 8.x. I can't even run the `php artisan config:clear` command in this situation which is troublesome.

I'm a bit torn on how to fix this as seen from a language perspective it makes sense that the app fails. A solution out the top of my brain would be to not load config caching as `php artisan config:clear` is run but not sure what the consequences of that would be or how it would be done. 

I'm gonna mark this as a bug for now but will try to dive deeper into this later on. In the worst circumstance we'll need to add a note to the docs about this edge case.

**Comment by seth-shi** [comment]
@driesvints Because My production environment executed `php artisan config:cache`, Put old code in `XXXServerProvider: : class` cache to `bootstrap/cache/config.php`,  When My new code is removed`XXXServerProvider`,  `bootstrap/cache/config.php` It also contains this class. 
When I started `php artisan`, the frame loaded the class from config, and there was no error in the class.I have to delete the config file manually

**Comment by GrahamCampbell** [comment]
I don't think this is a bug. It's to be expected, and it's why the laravel/laravel composer.json clears that directly without loading the framework.

**Comment by driesvints** [comment]
@GrahamCampbell is correct. The `postAutoloadDump` method on the `ComposerScripts` class will clear this after a composer dump is run: https://github.com/laravel/laravel/blob/master/composer.json#L51

It seems this is more of a case of an incorrect sequence of running commands during deployment.

**Comment by seth-shi** [comment]
`PostAutoloadDump `is really clear about the file. but `PostAutoloadDump ` run is need laravel bootstrap. If the `bootstrap/cache/config`. Contains a PHP class does not exist, then the` laravel` startup fails, then the` PostAutoloadDump` also perform less than
