### ISSUE TITLE
Invalid route action: [count]

### ISSUE THREAD

**Issue by Ozerich** [laravel/framework#35026]
- Laravel Version: 8.12.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:

After upgrade to 8.12 it is impossible to use "count" as function name for route

In routes.php:
`Route::get('workers/count', [WorkersController::class, 'count']);`

throw the error "_**Invalid route action: [count]**_."

If I change it to `Route::get('workers/count', WorkersController::class . '@count');`

it works correctly

On 8.11.2 the error is not reproduced

**Comment by driesvints** [comment]
We're looking into this

**Comment by taylorotwell** [comment]
Hmm, I can't recreate this. I do however hit that error if I don't import the controller properly in my routes file.

Have you "use App\Http\Controllers\WorkersController;` at the top of your file?

**Comment by taylorotwell** [comment]
Fixed in upcoming patch.

**Comment by taylorotwell** [comment]
Patch released.

**Comment by Ozerich** [comment]
It is working well now, thank you!
