### ISSUE TITLE
[Laravel 8.x] Arr::set() vs. data_set() different results on same array

### ISSUE THREAD

**Issue by therobfonz** [laravel/framework#35035]
- Laravel Version: 8.3.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.7.31

### Description:

`Arr::set()` and `data_set()` seem to be returning different array structures setting the same nested property. `Arr::set()` is returning an array at the level of the property you are setting where as `data_set()` is returning the entire array with the nested property set as expected.

### Steps To Reproduce:

Given the following array
```php
[
    'editor' => [
        'page' => [
            'body' => [],
            'rows' => [],
            'title' => 'Fragment Base',
            'template' => [],
            'description' => '',
        ],
    ],
];
```

When I try to set any nested value inside `editor`, it returns me an array at that level

Example: I try to set `rows` using `Arr::set($array, 'editor.page.rows', ['my test array'])` and it returns me an array of
```php
[
    'body' => [],
    'rows' => ['my test array'],
    'title' => 'Fragment Base',
    'template' => [],
    'description' => '',
]
```

However, using `data_set($array, 'editor.page.rows', ['my test array'])`, the returned array is expected.
```php
[
    'editor' => [
        'page' => [
            'body' => [],
            'rows' => ['my test array'],
            'title' => 'Fragment Base',
            'template' => [],
            'description' => '',
        ],
    ],
];
```

![Screen Shot 2020-10-30 at 6 48 10 AM](https://user-images.githubusercontent.com/35386780/97696661-4ae94300-1a7c-11eb-975d-1fa9685ea21c.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by therobfonz** [comment]
Hi Dries. Thanks for the quick response! I just tested on Laravel 8.3 and the problem persists. Updating the above issue with the correct version number.

**Comment by driesvints** [comment]
@therobfonz these are two different functions which don't mimic each other's behavior.

**Comment by therobfonz** [comment]
Correct, however, the documentation for each method has the example like I have outlined above and shows the same results

https://laravel.com/docs/8.x/helpers#method-data-set
https://laravel.com/docs/8.x/helpers#method-array-set

When I use the example in Laravel 8.3 for `Arr::set()` as noted in the documentation
```php
$array = ['products' => ['desk' => ['price' => 100]]];

Arr::set($array, 'products.desk.price', 200);

// ['products' => ['desk' => ['price' => 200]]]
```

it only returns
```php
['price' => 200']
```
not the array noted as the example output

**Comment by rodrigopedra** [comment]
@therobfonz 

I tested in a fresh Laravel 8 app and I can somehow replicate the unexpected behavior:

~~~php
<?php
// ./routes/console.php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Arr;

Artisan::command('app:test', function () {
    $array = [
        'editor' => [
            'page' => [
                'body' => [],
                'rows' => [],
                'title' => 'Fragment Base',
                'template' => [],
                'description' => '',
            ],
        ],
    ];

    $return = Arr::set($array, 'editor.page.rows', ['my test array']);

    \dd($array, $return);
});
~~~

Which outputs different results for the `$array` and `$return` variables:

~~~bash
$ php artisan app:test
array:1 [
  "editor" => array:1 [
    "page" => array:5 [
      "body" => []
      "rows" => array:1 [
        0 => "my test array"
      ]
      "title" => "Fragment Base"
      "template" => []
      "description" => ""
    ]
  ]
]
array:5 [
  "body" => []
  "rows" => array:1 [
    0 => "my test array"
  ]
  "title" => "Fragment Base"
  "template" => []
  "description" => ""
]
~~~

I also would expect both values to be the same. I tried tweaking the code to try getting the  same value but with no luck.

I must confess that I never relied on the return value and always used it like this:

~~~php
$array = [/*some data*/];

Arr::set($data, 'my.key', 'value');

return $data;
~~~

As I expected it to change the parameter by reference. So maybe not relying on its return value is the way to go.

**Comment by taylorotwell** [comment]
So, this is an interesting curiosity; however, I'm not sure we will really take any action on it. Making any change to it would be a breaking change for seemingly little benefit. Like the comment above, I've never relied on the returned value and the method doc blocks don't even describe what the return value is "supposed" to be. I actually wasn't even aware these methods had a return value until this issue was raised. 😆 

So, for now, I think we will probably take no action. The safest course IMO is to use Arr::set and then use Arr::get afterwards to get exactly what you want from the array.

**Comment by therobfonz** [comment]
Thanks for the explanation Taylor. I'll proceed as you have outlined above.
