### ISSUE TITLE
Laravel Testing: Storage fake "Maximum function nesting level of '256' reached, aborting"

### ISSUE THREAD

**Issue by FrazeColder** [laravel/framework#35034]
- Laravel Version: 8.x
- PHP Version: 7.4.11
- Database Driver & Version: MariaDB 10.5.6

### Description:
I have written a few tests for my own project but I am facing a strange error... My test should test if a image passes the validation rules, gets uploaded and really exists under the given path. For that I am mocking my storing as described in the [docs][1] with `Storage::fake`.

Also, I am using [this][2] technique to mock the `Storage::fake` path for the spatie media library which I am using.

This is my test:

    /** @test */
    public function a_logged_in_user_deletes_his_avatar_passes_fake_storage()
    {
        $fake_storage_disk = 'users';
        Storage::fake($fake_storage_disk);
    
        config()->set('filesystems.disks.userFiles', [
            'driver' => 'local',
            'root' => Storage::disk($fake_storage_disk)->getAdapter()->getPathPrefix(),
        ]);
    
        $user = User::factory()->create();
        $this->actingAs($user);
    
        $filename = Str::random(20) . '.jpg';
        $file = UploadedFile::fake()->image($filename, 200, 200);
    
        $response = $this->json('POST', route('user.avatar.update', $user->name), [
            'avatar' => $file
        ]);
    
        $response->assertStatus(302);
        $this->assertTrue(Storage::disk($fake_storage_disk)->exists($user->id . '/' . $filename));
    
        $response = $this->json('POST', route('user.avatar.delete', $user->name), [
            'value' => 1
        ]);
    
        $response->assertStatus(302);
    }

Here now comes the problems:
1. When running this tests (or even all tests where I test if I can upload an image and it exist) in row, it works like a charm. No problem at all!

2. When running ALL my tests, I get the problem that `$this->assertTrue(Storage::disk($fake_storage_disk)->exists($user->id . '/' . $filename));` fails because it is saying `Unable to assert that false is true`. This actually means, the file doens't exists.

3. However, when I am trying to `dd(Storage::disk($fake_storage_disk)->exists($user->id . '/' . $filename))` to check where the problem is I get this error:

>     Tests\Feature\User\LoggedIn\DeleteAvatar\UserTest::a_logged_in_user_deletes_his_avatar_fails_required_fake_storage
>     Error: Maximum function nesting level of '256' reached, aborting!
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/facade/ignition/src/DumpRecorder/MultiDumpHandler.php:13
>            
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/facade/ignition/src/DumpRecorder/DumpRecorder.php:34
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/facade/ignition/src/DumpRecorder/MultiDumpHandler.php:13
>
>     [Repeats 256 times]
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/facade/ignition/src/DumpRecorder/DumpRecorder.php:34
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/symfony/var-dumper/VarDumper.php:50
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/vendor/symfony/var-dumper/Resources/functions/dump.php:38
>     
>     /Users/jantrier/Desktop/Programmieren/MyWebsiteProject/tests/Feature/User/LoggedIn/DeleteAvatar/UserTest.php:52

What also confuses me is why he is throwing this error in this line `$this->assertTrue(Storage::disk($fake_storage_disk)->exists($user->id . '/' . $filename));` and not at the beginning when initializing `Storage::fake`. However, I get the same error when trying to `dd(..)` the `Storage::fake`...

Any ideas on how to solve this or where the problem is? Also, why the heck does it work when running it as a single test and also with other uploading tests but when running it with ALL other tests I have it fails?

Kind regards and thank you!

  [1]: https://laravel.com/docs/8.x/mocking#storage-fake
  [2]: https://github.com/spatie/laravel-medialibrary/issues/623#issuecomment-381559675

### Steps To Reproduce:
Take my test code

**Comment by taylorotwell** [comment]
I'm not sure if infinite recursion or happening or you just have a really big call stack. 

But, another question that comes to mind is why is $fake_storage_disk `users` while your call to `config` is updating a `userFiles` disk?

**Comment by taylorotwell** [comment]
Closing pending inactivity. Feel free to reopen.
