### ISSUE TITLE
Maintenance mode doesn't work on wildcard subdomains

### ISSUE THREAD

**Issue by hicham-saddek** [laravel/framework#35036]
Hello i've encountered this problem with many of my projects before, Laravel maintenance mode doesn't allow you to change the maintenance session domain name. I would like to purpose to you an easy fix from this line
https://github.com/laravel/framework/blob/3a0f1fd90636c5083b562823432f4b1a563d4927/src/Illuminate/Foundation/Http/MaintenanceModeBypassCookie.php#L20
and change it to something similar to this 👍 
![image](https://user-images.githubusercontent.com/36214361/97738655-f0350300-1ade-11eb-9235-b8aa91b90541.png)
instead of this
![image](https://user-images.githubusercontent.com/36214361/97738705-0773f080-1adf-11eb-9b4c-65aa2dcd71e6.png)
Hope this helps the devs :)

Kind regards

**Comment by taylorotwell** [comment]
If you have a feature you would like to contribute please make a PR.

**Comment by hicham-saddek** [comment]
Well it wasn't a feature of sorts, when we set in the .env file the SESSION_DOMAIN to something like .site.test normally the session should be accessible inside the subdomains. but in this case it does but not the Laravel maintenance cookie which generates an error after if a dev is accessing the sub.site.test domain name and can't access the mix('css/app.css') file because they are under site.test not sub.site.test it returns a 500 :(
