### ISSUE TITLE
I am not getting about this issue it's show undefined..

### ISSUE THREAD

**Issue by Developer-Nasim** [laravel/framework#35030]
I am using Laravel 7 as well
I have routed and would like to pass data by using the compact function,,,, but compact is not working

Kindly check these Screenshots then you can get it,, but I am not getting about this
1. https://prnt.sc/v9lxhp 
2. https://prnt.sc/v9lyzm 
3.https://prnt.sc/v9lzb1

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
