### ISSUE TITLE
[8.x] Enexpected `withChain(...)` behaviour

### ISSUE THREAD

**Issue by hivokas** [laravel/framework#35041]
- Laravel Version: `8.12.3`
- PHP Version: `7.4.11`
- Database Driver & Version: `mysql  Ver 8.0.19 for macos10.15 on x86_64 (MySQL Community Server - GPL)`

### Description:

There are 3 classes:

#### Base job

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;

abstract class BaseJob
{
    use Queueable;
}
```

#### `JobHigh` that should be processed in the `high` queue

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class JobHigh extends BaseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, SerializesModels;

    public $queue = 'high';

    public function handle()
    {
        //
    }
}
```

#### `JobMedium` that should be processed in the `medium` queue

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class JobMedium extends BaseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, SerializesModels;

    public $queue = 'medium';

    public function handle()
    {
        //
    }
}
```

While in Laravel 7 (`7.28.4`) both `dispatch(new JobHigh); dispatch(new JobMedium);` and `JobHigh::withChain(new JobMedium)->dispatch()` throw jobs to the appropriate queues, in Laravel 8 (`8.12.3`) that's not a case for `withChain(...)`.

Is that a bug? Or that's a change that was accidentally not included `Upgrade Guide`.

### Steps To Reproduce:

```php
dispatch(new JobHigh);

dispatch(new JobMedium);
```

#### Laravel 7:

![image](https://user-images.githubusercontent.com/22997803/97778836-a30a6d00-1b82-11eb-8ef7-71b4ab1e50a7.png)

#### Laravel 8:

![image](https://user-images.githubusercontent.com/22997803/97778761-09db5680-1b82-11eb-95b7-55ea6b0f4f0d.png)

```php
JobHigh::withChain([
    new JobMedium,
])->dispatch();
```

#### Laravel 7:

![image](https://user-images.githubusercontent.com/22997803/97778850-caf9d080-1b82-11eb-8d74-ed3a8ba81f0a.png)

#### Laravel 8:

![image](https://user-images.githubusercontent.com/22997803/97778775-2081ad80-1b82-11eb-9b0e-4ea85b9904b7.png)

**Comment by hivokas** [comment]
Looks like the problem lays here:

https://github.com/laravel/framework/blob/363dc94885590331ef0bf9106bf90be2dbe8fff6/src/Illuminate/Foundation/Bus/PendingChain.php#L136-L153

**Comment by taylorotwell** [comment]
@themsaid

**Comment by themsaid** [comment]
Opened https://github.com/laravel/framework/pull/35047 with a fix
