### ISSUE TITLE
Nested Blade Components misses parts of $attributes from parent Component

### ISSUE THREAD

**Issue by mvsvolkov** [laravel/framework#35046]
- Laravel Version: 8.11.2
- PHP Version: 7.4.11 

### Description:
The nested blade component has its own unique properties. I have a need to wrap such component with another component. And when i try to forward these unique properties using the `$attributes` variable, they are lost. In this case, standard properties, for example, a `class`, works fine.

### Steps To Reproduce:

1. Install fresh laravel
2. Create one Component with a custom property. This `x-button`, for example:
```php
@props(['buttonText' => 'default Button'])

<div>
	<div>x-button Attributes here: {{ $attributes }}</div>
	<button {{ $attributes }}>
		{{ $buttonText }}
	</button>
</div>
```
3. Create parent Component and send `{{ $attributes }}` to the child component. This `x-button-hover`, for example:
```php
<div style="padding: 20px; border: 1px solid black;">
	Just dummy simple example.
	<div>x-button-hover Attributes here: {{ $attributes }}</div>
	<x-button {{ $attributes }}></x-button>
</div>
```

4. Use this components on welcome (or other) page.
```php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <style type="text/css">
        .red {
            color: red;
        }
        .green {
            color: green;
        }
    </style>
</head>
<body>

    <x-button class="red" buttonText="It is working"></x-button>
    
    <x-button-hover class="green" buttonText="It is not working"></x-button-hover>

</body>
</html>
```
5. run build-in web-server `php artisan serve` 

6. And you will see `buttonText` attributes works fine when i use `x-button` component, but not when i use `x-button-hover` component
![image](https://user-images.githubusercontent.com/8544605/97790252-168a9980-1bd8-11eb-95ec-10ebf43dcd06.png)

**Comment by taylorotwell** [comment]
I can't recreate this. The attributes pass down to the nested component.

**Comment by taylorotwell** [comment]
I think it's just being used a little wrong. If it is a prop you need to pass it like a prop to the root button:

hover-button.blade.php:

```html
@props(['buttonText'])

<div class="hover-button">
    <x-button :button-text="$buttonText" {{ $attributes }}></x-button>
</div>
```

button.blade.php:

```html
@props(['buttonText'])

<div {{ $attributes }}>
    Button {{ $buttonText }}
</div>
```

**Comment by mvsvolkov** [comment]
Thanks for the answer. This is definitely enough in my case.

But, I think that defining the properties of nested components in the properties of the parent component seems a little annoying.
It turns out that I need to create properties in the parent component and not use them in it, but only pass them to the child component.

And if I have to create many levels of components, it gets even more painful.

Anyway, these are just wishes)
