### ISSUE TITLE
No logging after adding Log::debug in AppServiceProvider

### ISSUE THREAD

**Issue by timohund** [laravel/framework#35060]
- Laravel Version: 8.12.3
- PHP Version: 7.4.11
- Database Driver & Version:

### Description:

After i've added a DB::listen closuer in AppServiceProvider::boot that should write logs to the errorlog:

```
        if (App::environment('local')) {
            DB::listen(function ($query) {
                Log::debug($query->sql, $query->bindings);
            });
        }
```

logging in the Controller does not produce any log message anymore:

```
        Log::debug('test');
```

### Steps To Reproduce:

- Configure "errorlog" as log channel
- Add DB::listen closure for logging:
- Add logging in the controller

Am i doing something wrong or is this a bug?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
