### ISSUE TITLE
Blade templates simply dont work

### ISSUE THREAD

**Issue by JosephJose** [laravel/framework#35068]
Blade x-templates ignore template controller OR dont work at all. Everything created via terminal php artisan make:component

In home.blade.php I have 
`<x-ssdfsdfsdfsdf />`
Then in components folder I have a controller "ssdfsdfsdfsdf.php" with the same class name (tried also capitalized first letter) that returns a view. 
I am getting this error
 `Unable to locate a class or view for component [ssdfsdfsdfsdf]`
If I name the component view the same as x-tag, then the framework ignores the controller altogether. This simply doesnt work.

**Comment by taylorotwell** [comment]
They work. They are used extensively in Jetstream. You likely have a typo or user error.
