### ISSUE TITLE
Cannot set different schema on database config

### ISSUE THREAD

**Issue by Giacomo92** [laravel/framework#35070]
- Laravel Version: 7.27.0
- PHP Version: 7.3
- Database Driver & Version: sqlsrv 5.8

### Description:
Cannot set different schema on database config

### Steps To Reproduce:
set 'schema' => env('DB_SCHEMA', 'dbo') on config
and test the connection with a model query

**Comment by rodrigopedra** [comment]
`schema` option is  not available for SQL Server, only for Postgres

Also I don't think PDO's DSN for SQL Server supports specifying a schema:

https://docs.microsoft.com/en-us/sql/connect/php/connection-options?view=sql-server-ver15

But, you can specify the schema during a query:

~~~php
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

Route::get('/test', function () {
    return DB::table('INFORMATION_SCHEMA.COLUMNS')->get();
});
~~~

Or in a eloquent model's `$table` attribute:

~~~php
<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Route;

class Column extends Model
{
    protected $table = 'INFORMATION_SCHEMA.COLUMNS';
}

Route::get('/test', function () {
    return Column::all();
});
~~~

**Comment by driesvints** [comment]
See above.

**Comment by Giacomo92** [comment]
Thank you @rodrigopedra. I have added the schema on $table attribute

**Comment by rodrigopedra** [comment]
You're welcome! Great you got it working. Have a nice day .
