### ISSUE TITLE
Laravel Schedule running twice using supervisor

### ISSUE THREAD

**Issue by sdjrppl** [laravel/framework#35075]
- Laravel Framework 8.11.2
- PHP Version: PHP 7.4.11
- Database Driver & Version: MySql 5.7

### Description:
Hi, I'm using laradock with php-worker with scheduler configured on supervisor. 
It's the default configs basically. First I thought it was a bug on my code, then I take drastic measures and removed all, leaving just Log::info calls trying to understand what was causing 2 calls on my commands.
So as you can see in the pictures, the schedule method is been called twice. Can someone give me some guidance to prevent this from happening? 
Thanks

### Supervisor 
[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=/bin/sh -c "while [ true ]; do (php /var/www/artisan schedule:run --verbose --no-interaction &); sleep 60; done"
autostart=true
autorestart=true
numprocs=1
user=laradock
redirect_stderr=true

### Images:

![image](https://user-images.githubusercontent.com/17573664/97990288-9df22b80-1dd7-11eb-9050-83136c935dde.png)
![image](https://user-images.githubusercontent.com/17573664/97990494-ec9fc580-1dd7-11eb-95cf-890f43bdd422.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sdjrppl** [comment]
Ok thanks, sorry about that
