### ISSUE TITLE
Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() must be of the type string, null given

### ISSUE THREAD

**Issue by Abouhassane** [laravel/framework#35071]
- Laravel Version: 8.12.3
- PHP Version: 7.4.3
- Database Driver & Version: Mysql

### Description:
I keep finding this error in my log files repeatedly, and also when i try to run my tests. 

I found out that in this file `Illuminate\Foundation\Bootstrap\SetRequestForConsole`, the `$uri`variable passed to the Request::create function comes null. 

For some reason the `$app->make('config')->get('app.url', 'http://localhost');` returns null

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lybuneiv** [comment]
Please set value for APP_URL in .env file
Example: APP_URL=http://localhost
