### ISSUE TITLE
I get error message while creating new project in laravel (windows)

### ISSUE THREAD

**Issue by Shekhardas580** [laravel/framework#35079]
- Laravel Version: (v8.4.0)
- PHP Version: 7.4.12
- Database Driver & Version: 

Problem 1
    - laravel/framework[v8.12.0, ..., 8.x-dev] require league/flysystem ^1.1 -> satisfiable by league/flysystem[1.1.0, ..., 1.x-dev].
    - league/flysystem[1.1.0, ..., 1.x-dev] require ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].

**Comment by driesvints** [comment]
Your error is in the message above. Your PHP build is missing the fileinfo extension.

**Comment by lynxus** [comment]
FYI. Found this useful. Annoyingly fileinfo is disabled by default and im struggling to learn laraval. These annoyances are making frontend even harder.. Can we go back to plain old php and html pleeeeaaaseee? i dont like learning.

**Comment by nosferatu-id** [comment]
> FYI. Found this useful. Annoyingly fileinfo is disabled by default and im struggling to learn laraval. These annoyances are making frontend even harder.. Can we go back to plain old php and html pleeeeaaaseee? i dont like learning.
nope...

**Comment by Bosh1707** [comment]
I also get this message. I'm a bit of a noob so can anyone help me fix this? I'm kind of desperate and I've been trying to solve this thing for days

**Comment by javaidnaik** [comment]
Found a solution to this in MAMP.

In addition to editing the **php.ini** in **mamp\bin\php7.1.5\php.ini**, You need to add **extension=php_fileinfo.dll** in **mamp\conf\php7.1.5\php.ini**. Notice the conf folder.

In configurations, the file doesn't seem to be related to the running server, but it does in fact make a difference.

**Comment by paraLasnap** [comment]
Problem 1
    - laravel/framework[v8.12.0, ..., 8.x-dev] require league/flysystem ^1.1 -> satisfiable by league/flysystem[1.1.0, ..., 1.x-dev].
    - league/flysystem[1.1.0, ..., 1.x-dev] require ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\Program Files\PHP\php-7-4-5-non-thread-safe\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.


SVP jai rencontré ce meme probleme.

Cela fait Maintenant plus d'une Semaine que je n'arrive pas a insttaler LARAVEL.
Besion d'aide SVP .

j'utilise WAMP

**Comment by ElectronSz** [comment]
Problem 1
    - laravel/framework[v8.12.0, ..., 8.x-dev] require ext-mbstring * -> it is missing from your system. Install or enable PHP's mbstring extension.
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].

**Comment by ahmetbrl38** [comment]
I also have the same problem,but I couldn't find a solution

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
