### ISSUE TITLE
Previewing markdown notifications does not honour custom theme

### ISSUE THREAD

**Issue by nathanpurcell** [laravel/framework#35081]
- Laravel Version: 8.13.0
- PHP Version: 7.4.0
- Database Driver & Version: n/a

### Description:
When trying to preview a markdown notification in browser ([as per the docs](https://laravel.com/docs/8.x/notifications#previewing-mail-notifications)), it appears that the inline custom theme as set using the `theme()`method is not being honoured - the default theme is used instead. 

### Steps To Reproduce:
New installation of Laravel 8. 
Create a markdown notification using Artisan: 
```bash
php artisan make:notification Testing --markdown testing
```

Publish mailable views and assets: 
```bash
php artisan vendor:publish --tag=laravel-mail
```

Create custom theme in `/resources/views/vendor/mail/html/themes` (named `testing.css`). 
Make a trivial but obvious changes to the theme - for example make all color references on .button-primary a bright pink: #ff00ff. 

Update `App\Notifications\Testing` to use this custom theme: 
```php
public function toMail($notifiable)
{
    return (new MailMessage)->theme('testing')->markdown('testing');
}
```

Update `routes/web.php` to run example: 

```php
Route::get('/', function () {
    // Send the notification.
    // $send = Notification::route('mail', 'nathan@nathanpurcell.com')->notify(new \App\Notifications\Testing);

    // Preview the notification.
    $user = new \App\Models\User;
    $user->email = 'nathan@nathanpurcell.com';

    return (new App\Notifications\Testing)->toMail($user);
});
```

What's interesting is that if you uncomment the first line where the notification is sent and run the code, the subsequent render works as expected. 
Otherwise the notification renders, but using the default theme.

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by nathanpurcell** [comment]
Great stuff, thank you!
