### ISSUE TITLE
\Artisan::output() retrun empty string?

### ISSUE THREAD

**Issue by hcweb** [laravel/framework#35086]
I execute \Artisan::call('route:cache') or \Artisan::call('config:cache');dd(\Artisan::output()); returns an empty string, but execute \Artisan:: call('route:clear') or \Artisan::call('config::clear');dd(\Artisan::output()); return value and manually execute php artisan config:clear or php artisan route: The same as clear, what's the matter? Is it \Artisan::call('route:cache');dd(\Artisan::output()); the default return is an empty string?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
