### ISSUE TITLE
PR to make changing auth notifications (VerifyEmail,  ResetPassword) easier 

### ISSUE THREAD

**Issue by SebastianSchoeps** [laravel/framework#35087]
When extending the Auth notification templates (`Illuminate\Auth\Notifications\ResetPassword`, `Illuminate\Auth\Notifications\VerifyEmails`) to write your own messages but keep the original logic, you have to override the `toMail` methods.

Would a PR like the following have a chance to get accepted?

Old:
```
public function toMail($notifiable)
{
    if (static::$toMailCallback) {
        return call_user_func(static::$toMailCallback, $notifiable, $this->token);
    }

    if (static::$createUrlCallback) {
        $url = call_user_func(static::$createUrlCallback, $notifiable, $this->token);
    } else {
        $url = url(route('password.reset', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));
    }

    return (new MailMessage)
        ->subject(Lang::get('Reset Password Notificationss'))
        ->line(Lang::get('You are receiving this email because we received a password reset request for your account.'))
        ->action(Lang::get('Reset Password'), $url)
        ->line(Lang::get('This password reset link will expire in :count minutes.', ['count' => config('auth.passwords.'.config('auth.defaults.passwords').'.expire')]))
        ->line(Lang::get('If you did not request a password reset, no further action is required.'));
}
```

New:
``` 
public function toMail($notifiable)
{
    if (static::$toMailCallback) {
        return call_user_func(static::$toMailCallback, $notifiable, $this->token);
    }

    if (static::$createUrlCallback) {
        $url = call_user_func(static::$createUrlCallback, $notifiable, $this->token);
    } else {
        $url = url(route('password.reset', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));
    }

    return $this->getMailMessage($url);
}

protected function getMailMessage($url)
{
    return (new MailMessage)
        ->subject(Lang::get('Reset Password Notificationss'))
        ->line(Lang::get('You are receiving this email because we received a password reset request for your account.'))
        ->action(Lang::get('Reset Password'), $url)
        ->line(Lang::get('This password reset link will expire in :count minutes.', ['count' => config('auth.passwords.'.config('auth.defaults.passwords').'.expire')]))
        ->line(Lang::get('If you did not request a password reset, no further action is required.'));
}
```

This way I could just override the `getMailMessage` method in an own notification that extends the original one.

Just quickly checking here before submitting my first PR to Laravel - just want to make sure.

Thanks,
Sebastian

**Comment by selcukcukur** [comment]
@SebastianSchoeps yes it can be expanded that way. But why should we need this?

**Comment by SebastianSchoeps** [comment]
The question is not if it could be done (technically), but if a PR would be accepted.

Possible use cases:
- add a link to the privacy policy into the mail
- use different texts in the body
- use a different subject
- remove the "this link will expire line" (for whatever reson)
- use a saluation

**Comment by selcukcukur** [comment]
@SebastianSchoeps The situations you mentioned for this can also be overridden directly "toMail".

Example : A new "toMail" can be written to the notification file created for a hello message, overriding "toMail" completely.

PR will not be accepted in my guess, but send it. So we can see what Taylor Otwell has to say about it.

**Comment by SebastianSchoeps** [comment]
That's what I do right now, overridding `toMail`. Which means I have to keep the logic e.g. for creating the URLs. That's exactly the reasoning for the PR.

**Comment by selcukcukur** [comment]
> That's what I do right now, overridding `toMail`. Which means I have to keep the logic e.g. for creating the URLs. That's exactly the reasoning for the PR.

I understand what you say. But Taylor Otwell is very sensitive about adding new things. He argues that the amount of code is important for the sustainability of the project. The PR you've applied doesn't exactly fix a problem. As I said, it is already working properly, so you may not accept it, try your luck. @taylorotwell

**Comment by taylorotwell** [comment]
Best bet is probably just to make the PR and let us evaluate. You have already essentially written the code here.

**Comment by driesvints** [comment]
@SebastianSchoeps also please see our issue templates before opening a feature request and use the ideas repo for these.

**Comment by SebastianSchoeps** [comment]
Yes, sorry, I only found the idea repo afterwards and thought „That‘s where I should have gone“...
Am 5. Nov. 2020, 13:21 +0100 schrieb Dries Vints <notifications@github.com>:

@SebastianSchoeps<https://github.com/SebastianSchoeps> also please see our issue templates before opening a feature request and use the ideas repo for these.
