### ISSUE TITLE
Wrong type in function

### ISSUE THREAD

**Issue by ben221199** [laravel/framework#35082]
In order to make custom connection drivers, `Connection` should changed to `ConnectionInterface`.

https://github.com/laravel/framework/blob/41915424bbd0939048e9b2d3701568dc2bc98790/src/Illuminate/Database/DatabaseManager.php#L166

**Comment by driesvints** [comment]
If you want to change anything feel free to PR. Although I doubt we'll be making this breaking change, sorry.

**Comment by ben221199** [comment]
I will make a PR.

`Connection` is already an class that implements `ConnectionInterface`. How could that break the code?

**Comment by driesvints** [comment]
yes since you're changing the method signature

**Comment by ben221199** [comment]
I see. I got this one:
```
Declaration of App\Http\Controllers\TestController::configure(Illuminate\Database\Connection $connection, $type) should be compatible with Illuminate\Database\DatabaseManager::configure(Illuminate\Database\ConnectionInterface $connection, $type)
```

Maybe it could be changed in Laravel 9, because that is a major version change and people are then prepared for breaking changes.
