### ISSUE TITLE
`Illuminate\Database\ConnectionResolverInterface` used as `\Illuminate\Database\Connection`

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#35090]
- Laravel Version: 8.13.0
- PHP Version: 7.4.x
- Database Driver & Version:

### Description:

https://github.com/laravel/framework/blob/71dbf2206880bd79198eb859e642662a4ac85f0a/src/Illuminate/Database/Console/DumpCommand.php#L36-L42

https://github.com/laravel/framework/blob/71dbf2206880bd79198eb859e642662a4ac85f0a/src/Illuminate/Database/Console/DumpCommand.php#L57-L69

`$connection` is a `\Illuminate\Database\ConnectionInterface` but it is used as `\Illuminate\Database\Connection` in `schemaState` , the problem is  `\Illuminate\Database\ConnectionInterface` doesn't have `getSchemaState()`. Thus this is code will fail when `ConnectionResolverInterface::connection()` return trully `ConnectionInterface` instance (as it should).

Maybe `ConnectionInterface` should be updated, or `ConnectionResolverInterface` shouldn't be used here.

**Comment by taylorotwell** [comment]
This doesn't affect actual code.
