### ISSUE TITLE
Change enum doesn't work

### ISSUE THREAD

**Issue by rela589n** [laravel/framework#35096]
- Laravel Version: 8.12.3
- PHP Version: 7.4
- Database Driver & Version: Postgres 13

### Description:

I've defined column of enum type.
After some time I've got need to extend enum type.
But this doesn't allow me to do that.

Here's error what i encounter:
```
Unknown column type "enum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

### Steps To Reproduce:

First migration:
```php
Schema::create('seasons', function (Blueprint $table) {
    $table->id();
    $table->enum('type', ['predefined'])
        ->default('predefined');

    $table->integer('start_month');
    $table->integer('end_month');

    $table->timestamps();
});
```

Second one:

```php
Schema::table(
     'seasons',
     function (Blueprint $table) {
         $table->enum('type', ['predefined', 'another'])->change();
     }
);
```

**Comment by Vusys** [comment]
This is a documented limitation: https://laravel.com/docs/8.x/migrations#renaming-columns

And it has a long outstanding issue with some workarounds: https://github.com/laravel/framework/issues/1186

**Comment by rela589n** [comment]
I'm sorry, documented is that enum column could not be renamed. There is no
information about changing

**Comment by taylorotwell** [comment]
The documentation may need to be updated.

**Comment by t1m0t** [comment]
I had to change it to `string` and keep checking values at code level with
```php
$validatedData = Request::validate([
...
 'myValue' => ['required', Rule::in('valueA', 'valueB', 'valueC', 'valueD', 'valueE')],
...
]);
```

**Comment by nnnnnnnngu** [comment]
You can drop the column  and add the updated:

``` php
        Schema::table(
            'seasons',
            function (Blueprint $table) {
                $table->dropColumn('type');
            }
        );

        Schema::table(
            'seasons',
            function (Blueprint $table) {
                $table->enum('type', ['predefined', 'another']);
            }
        );
```

**Comment by didix16** [comment]
Hi, I'm having the same issue. Any clue when this will be fixed? Thanks

**Comment by edrisranjbar** [comment]
> Hi, I'm having the same issue. Any clue when this will be fixed? Thanks

I have a table called `form8` which already have some data in it. I want to make some of the fields `nullable`, I'm using the following syntax:
```php
        Schema::table('form8', function (Blueprint $table) {
            $table->string('adjustment_question1_type')->nullable()->change();
            $table->integer('adjustment_question1_cost')->nullable()->change();
            $table->enum('adjustment_question1_radio', ['option1', 'option2', 'option3'])->nullable()->change();
            $table->string('adjustment_question2_type')->nullable()->change();
            $table->integer('adjustment_question2_cost')->nullable()->change();
            $table->enum('adjustment_question2_radio', ['option1', 'option2', 'option3'])->nullable()->change();
            $table->string('adjustment_question3_type')->nullable()->change();
            $table->integer('adjustment_question3_cost')->nullable()->change();
            $table->enum('adjustment_question3_radio', ['option1', 'option2', 'option3'])->nullable()->change();
        });
```

And i'm facing This Error:
```
 Doctrine\DBAL\Exception 

  Unknown column type "enum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

  at vendor/doctrine/dbal/src/Exception.php:115
    111▕     }
    112▕ 
    113▕     public static function unknownColumnType(string $name): self
    114▕     {
  ➜ 115▕         return new self('Unknown column type "' . $name . '" requested. Any Doctrine type that you use has ' .
    116▕             'to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the ' .
    117▕             'known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database ' .
    118▕             'introspection then you might have forgotten to register all database types for a Doctrine Type. Use ' .
    119▕             'AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement ' .

      +14 vendor frames 

  15  database/migrations/2023_07_15_233658_make_adjustment_fields_nullable_in_clients_table.php:24
      Illuminate\Support\Facades\Facade::__callStatic()
      +24 vendor frames 

  40  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

**Comment by aurelioth** [comment]
I know this is closed but...

Is not posible to go back directly from string to enum because it could result in data loss, so we need to create a new column and copy the data from the string column to the new enum column.

$table->enum('new_enum_column', ['val1', 'val2', 'other'])->nullable();

//Update values
$table->update(['new_enum_column' => DB::raw('type')]);

//Drop the old column
$table->dropColumn('old_column_string');

//Rename the new column to keep the old name
$table->renameColumn('new_enum_column', 'old_column_name');

Hope it helps.

**Comment by Musuyaba** [comment]
Here's the code snippet for future reference. The code that @aurelioth give not work for me.

> **BadMethodCallException**
> Method Illuminate\Database\Schema\Blueprint::update does not exist.

It accomplishes the following tasks: renaming 'current_column' to 'old_column', creating 'current_column' with new elements, ensuring that unique elements from 'old_column' become elements in the new 'current_column', copying each row's value from 'old_column' to 'current_column', and finally dropping 'old_column'.


```php
Schema::table('your_tables', function (Blueprint $table) {
    // Rename the column
    $table->renameColumn('current_column', 'old_column');

    // If it's an enum column, update its values
    $table->enum('current_column', ['element1', 'element2', 'element3'])->nullable();

    // Update each row with the value from the old column
    DB::table('your_tables')->get()->each(function ($row) {
        DB::table('your_tables')
            ->where('id', $row->id)
            ->update(['current_column' => $row->old_column]);
    });

    // Drop the old column
    $table->dropColumn('old_column');
});
```

**Comment by syahid-dev** [comment]
This works for me, by adding the following configuration to the `config/database.php` file.

```php
use Doctrine\DBAL\Types\StringType;
 
'dbal' => [
    'types' => [
        'enum' => StringType::class,
    ],
],
```

**Comment by ahaneef29** [comment]
@syahid-dev can you please share which section to add about code ? In config/database.php

**Comment by syahid-dev** [comment]
> @syahid-dev can you please share which section to add about code ? In config/database.php

Here you go
```php
<?php

use ...
use Doctrine\DBAL\Types\StringType;

return [

    ...

    'dbal' => [
        'types' => [
            'enum' => StringType::class,
        ],
    ],

];
```

**Comment by meeprakash25** [comment]
using raw query
Schema::table('users', function (Blueprint $table) {
            DB::statement("ALTER TABLE posts MODIFY type ENUM('IF','DF','P','N','E', 'BP')
                        NOT NULL");
        });

**Comment by ratulSharker** [comment]
> This works for me, by adding the following configuration to the `config/database.php` file.
> 
> ```
> use Doctrine\DBAL\Types\StringType;
>  
> 'dbal' => [
>     'types' => [
>         'enum' => StringType::class,
>     ],
> ],
> ```

At the first glance, it seems working properly. The migration run without any error. But just a flag, doing so the column type will become `varchar` instead of expected `enum(...)` type.

**Comment by TheZoraiz** [comment]
**!!NOTE!!** Changing `config/database.php` to interpret enum as `Doctrine\DBAL\Types\StringType` like so:
```php
use Doctrine\DBAL\Types\StringType;
 
'dbal' => [
    'types' => [
        'enum' => StringType::class,
    ],
],
```
... will change your column to `varchar(255)` instead of `enum`. You're literally altering the data type. Be careful

**Comment by Mohamed-G2021** [comment]
> DB::statement("ALTER TABLE seasons MODIFY COLUMN type enum('predefined', 'another') DEFAULT 'predefined'");

perfect answer
worked for me
