### ISSUE TITLE
PHP 7.4.12 Preloader Confilict with Laravel's Observer

### ISSUE THREAD

**Issue by sametsahindogan** [laravel/framework#35104]
- Laravel Version: 8.13.0
- PHP Version: 7.4.12
- Database Driver & Version: -

### Description:

I was using a php 7.4 version lower than php 7.4.12 on my server. When I updated to PHP version to 7.4.12, I noticed that Laravel and the preloader were not working. ( If you use Laravel's Observer )

I preloaded whole Laravel vendor files like this script -> https://github.com/brendt/laravel-preload/blob/master/preload.php

I tested on 2 different projects with different servers. If any model has Observer, then errors occurs.

Problem is here; https://github.com/laravel/framework/blob/249fad34517fd652754c003c8a4eee379ebea697/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L40

### Steps To Reproduce:

* Make sure your php version is 7.4.12 and install clean Laravel project
* Create a empty observer, then Observe specific Models on your AppServiceProvider
* Use this script for preloading whole Laravel vendor files https://github.com/brendt/laravel-preload/blob/master/preload.php
* Make necessary php.ini settings for preloading
* If everything is ok, then restart php74-fpm service and try it

**Comment by driesvints** [comment]
I don't know anything about preloading. If you have a fix for this feel free to send in a PR 👍

**Comment by phroggyy** [comment]
@driesvints can we re-open this. This causes an issue in PHP 7.4.12. Even if you don't have a solution, it should be kept open so it can be found and not duplicated.

**Comment by sametsahindogan** [comment]
@phroggyy @driesvints I created a [bug report on PHP ](https://bugs.php.net/bug.php?id=80322) about this issue 

Also, this error is not triggered only when using observer. If I create a new object from the Model,(e.g Models/User.php) I get the same error. 

I think Laravel has no problem about this bug.

You can examine the details from the [bug report](https://bugs.php.net/bug.php?id=80322) on I have created.

**Comment by phroggyy** [comment]
Alright great, I was going to try and repro this myself with a plain laravel project, glad you did that 👍

**Comment by sametsahindogan** [comment]
> Alright great, I was going to try and repro this myself with a plain laravel project, glad you did that 👍

You can be sure that I tried all the possibilities. I think all that remains is to wait.  👍

**Comment by sametsahindogan** [comment]
@phroggyy It looks like a PHP bug as we guessed. It will be fixed at PHP 7.4.13 release. Thanks to @nikic :clap:
