### ISSUE TITLE
Upsert results in an QueryException on MS SQL

### ISSUE THREAD

**Issue by jasperjorna** [laravel/framework#35109]
- Laravel Version: 8.13.0
- PHP Version: 7.4.12
- Database Driver & Version: sqlsrv, Microsoft SQL Server 2017

### Description:
The newly introduced `upsert()` function results in the following QueryException:

```SQLSTATE[HY000]: General error: 20018 A MERGE statement must be terminated by a semi-colon (;). [20018] (severity 15) [merge [foo] using (values (1, 'Foo'), (2, 'Bar')) [laravel_source] ([id], [name]) on [laravel_source].[id] = [foo].[id] when matched then update set [name] = [laravel_source].[name] when not matched then insert ([id], [name]) values ([id], [name])] (SQL: merge [foo] using (values (1, Foo), (2, Bar)) [laravel_source] ([id], [name]) on [laravel_source].[id] = [foo].[id] when matched then update set [name] = [laravel_source].[name] when not matched then insert ([id], [name]) values ([id], [name]))```

### Steps To Reproduce:

1. Use the sqlsrv driver with an MS SQL database

2. Create a simple database table, for example:
```
CREATE TABLE [dbo].[foo] (
    [id] bigint,     
    [name] nvarchar
);
```

3. Execute a simple `upsert` statement, for example: 
```
DB::table('foo')->upsert(
    [
        ['id' => 1,'name' => 'Foo'],
        ['id' => 2,'name' => 'Bar'],
    ],
    'id',
    ['name']
);
```

**Comment by taylorotwell** [comment]
@paras-malhotra do you have any ideas on this?

**Comment by paras-malhotra** [comment]
Sent a PR to fix this: https://github.com/laravel/framework/pull/35112

@jasperjorna can you confirm that this fixes the issue?

**Comment by jasperjorna** [comment]
@paras-malhotra Confirmed this fixes the issue, a typical case of a missing `;`.

Thank you for the quick update. 👍
