### ISSUE TITLE
Upsert method create new record every time when update form.

### ISSUE THREAD

**Issue by shankhadevpadam** [laravel/framework#35103]
- Laravel Version: 8.12.3
- PHP Version: 7.4.12
- Database Driver & Version: 8.0.22

I have post meta table with fields [id, post_id, meta_key, meta_value]. i want to bulk update a meta values. But It repeatedly create a new row when using upsert method while updating the form everytime.

```
foreach ($metas as $key => $value) {
    $arr[] = [
        'post_id' => $post->id,
        'meta_key' => $key,
        'meta_value' => $value ?? '',
    ];
}

Postmeta::upsert($arr, ['id', 'post_id', 'meta_key'], ['meta_value']);
```
but while using updateOrCreate method it work fine.
```
foreach ($metas as $key => $value) {
    Postmeta::updateOrCreate(['post_id' => $post->id, 'meta_key' => $key], ['meta_value' => $value ?? '']);
}
```

**Comment by paras-malhotra** [comment]
@shankhadevpadam do you have a `unique` or `primary` index on the `meta_value` field? It's probably not working because you don't have the index setup. If you did, there was no way the mySQL engine would insert a new row because of the index.

**Comment by shankhadevpadam** [comment]
id is primary key.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
