### ISSUE TITLE
firstOrCreate search for null value converts to string

### ISSUE THREAD

**Issue by matiazar** [laravel/framework#35113]
- Laravel Version: 8.13.0
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.4.12

### Description:

$notification = Notification::firstOrCreate([
            'resource' => $notif['resource'],
            'topic' => $notif['topic'],
            'response' => null
            ], [some other values]);

returns

#attributes: array:12 [
    "resource" => "/item/55359"
    "topic" => "item"
    "response" => "null"   --> like string and not null value
    "status_id" => "Pending"
    "attempts" => 0
]

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
