### ISSUE TITLE
API resource resets non-sequential numeric keys inside nested data

### ISSUE THREAD

**Issue by gbradley** [laravel/framework#35118]
- Laravel Version: 8.13.0
- PHP Version: 7.4.10
- Database Driver & Version: n/a

### Description:

If returning a nested array inside an API resource, the array keys will be reset if they are numeric but non-sequential. This behaviour is the same regardless of wrapping; `$preserveKeys = true` does resolve the problem, but as per the docs ("Laravel resets the collection's keys") this should presumably be applied to the top-level collection keys only, not all nested arrays inside the returned data structure.

### Steps To Reproduce:

Defining this resource:

```
class KeysReset extends JsonResource
{

    public function toArray($request)
    {
        return [
            'foo' => [
                'bar' => [
                    100 => 'baz'
                ]
            ]
        ];
    }
}
```

results in this JSON:

```
{
    "data": {
        "foo": {
            "bar": [
                "baz"
            ]
        }
    }
}
```

instead of the expected:

```
{
    "data": {
        "foo": {
            "bar": {
                100 : "baz"
            }
        }
    }
}
```

**Comment by driesvints** [comment]
`$preserveKeys` is meant for nested keys as well. See the `testKeysArePreservedIfTheResourceIsFlaggedToPreserveKeys` test that validates this behavior.

**Comment by gbradley** [comment]
If that's the intended behaviour, may I suggest changing the docs? The only mention of `$preserveKeys` is inside the "Preserving Collection Keys" section, but the above scenario has nothing to do with collections. Thanks!

**Comment by driesvints** [comment]
I don't think I understand the issue sorry. What's not clear?

**Comment by gbradley** [comment]
The docs describe `$preserveKeys` as a feature under the heading "Preserving Collection Keys" (emphasis mine):

> #### Preserving Collection Keys
> *When returning a resource collection from a route*, Laravel resets the collection's keys so that they are in simple numerical order. However, you may add a preserveKeys property to your resource class indicating if *collection keys* should be preserved.

In my code example I'm not using collections at all, so when I read the above paragraph:

- it doesn't seem relevant, as I'm not returning a collection;
- it seems like *only* the collection's keys would be reset, rather than all keys.

Something like the following would describe the actual behaviour:

> #### Preserving Keys
> When returning a resource or resource collection from a route, Laravel resets all numeric keys (including nested keys) so that they are in simple numerical order. However, you may add a preserveKeys property to your resource class indicating if numeric keys should be preserved.

**Comment by gbradley** [comment]
Sorry for the 2nd reply, but perhaps my example wasn't good at describing the issue. 

The `testKeysArePreservedIfTheResourceIsFlaggedToPreserveKeys` test seems to assume that the lowest-nested array is the 'byId' collection, and so it makes sense to reset those keys. But there other scenarios where the lowest-nested array is not a collection.

Taking this model and resource:

    class MyModel
    {

        protected $casts = [
            'foo'   => 'array'
        ];

    }

    class MyModelResource
    {

        public function toArray()
        {
            return [
                'foo'   => $this->foo
            ];
        }

    }

and creating the model with a `foo` array with non-sequential numeric keys:

    $model = new MyModel([
        'foo'   => [
            100 => 'bar'
        ]
    ]);

    return new MyModelResource($model);

returns this json:

    [
        'foo' => [
            'bar'
        ]
    ]

**Comment by driesvints** [comment]
Hey @gbradley. I agree that the wording isn't entirely clear on that. Can you perhaps PR your changes to the docs?
