### ISSUE TITLE
MySQL data type default values are not supported in migrations.

### ISSUE THREAD

**Issue by gregorip02** [laravel/framework#35119]
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.x

### Description:

Commonly in relational databases we have data types whose default values could be assigned using functions of the database manager. The default method does not seem to work as I expect when executing the migrations.

### Steps To Reproduce:

```php
// create_posts_table
public function up()
{
  Schema::create('posts', function (Blueprint $table) {
    $table->id();
    $table->text('content')->nullable();
    $table->json('media')->default('JSON_ARRAY()');
    $table->timestamps();
});
```

I tried to fix it as follows but I keep getting the same error.

```php
// create_posts_table
public function up()
{
  Schema::create('posts', function (Blueprint $table) {
    $table->id();
    $table->text('content')->nullable();
    $table->json('media')->default('[]');
    $table->timestamps();
});
```

The error is because the migration tries to run the following.

```sql
create table `posts` (
  `id` bigint unsigned not null auto_increment primary key, 
  `content` text null, 
  `media` json not null default 'JSON_ARRAY()',
  `created_at` timestamp null, 
  `updated_at` timestamp null
) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

When it should be.

```sql
create table `posts` (
  `id` bigint unsigned not null auto_increment primary key, 
  `content` text null, 
  `media` json not null default (JSON_ARRAY()),
  `created_at` timestamp null, 
  `updated_at` timestamp null
) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

I think this would be solved by adding a new method called `defaultRaw()` or something like that, to add default values as expressions. 

see https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

**Comment by rodrigopedra** [comment]
Try this workarounf

~~~php
// create_posts_table
public function up()
{
  Schema::create('posts', function (Blueprint $table) {
    $table->id();
    $table->text('content')->nullable();
    $table->json('media')->default(DB::raw('(JSON_ARRAY())'));
    $table->timestamps();
});
~~~

I agree `->defaultRaw(...)` is more expressive, on the other hand it seems like an edge-case.

**Comment by driesvints** [comment]
Seems like a feature request.
