### ISSUE TITLE
Class files does not exist

### ISSUE THREAD

**Issue by rezaamini-ir** [laravel/framework#35120]
Hello everyone.
I'm working on a Laravel package and now I have a strange error.

When I'm trying to load migrations in my test case I get an error.
It's my code and I think it's not wrong.
`$this->loadMigrationsFrom(__DIR__.'/../database/migrations');`

I've added the class map in `composer.json` and my migration file is: `2020_09_05_99999_create_users_table.php`

Error : 
`Illuminate\Contracts\Container\BindingResolutionException: Target class [files] does not exist.`

**Comment by GrahamCampbell** [comment]
This happens when you have not registered the filesystem service provider.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Filesystem/FilesystemServiceProvider.php

**Comment by rezaamini-ir** [comment]
I use all of `laravel/framework` as a dependency in composer.josn.
and the file system depends on the framework, does not?
I've registered `FilesystemServiceProvider::class` in my test case as a provider and now I get.
`Symfony\Component\Console\Exception\CommandNotFoundException: The command "migrate" does not exist.`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
