### ISSUE TITLE
i cannot run npm start

### ISSUE THREAD

**Issue by TrendTrickster** [laravel/framework#35122]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
confusion@1.0.0 start C:\Users\Acer\Desktop\Pranava Web Development\bootstrap 4\Bootstrap4\conFusion
> npm run watch:all

> confusion@1.0.0 watch:all C:\Users\Acer\Desktop\Pranava Web Development\bootstrap
4\Bootstrap4\conFusion
> parallelshell "npm run watch:scss" "npm run lite"

child_process.js:422
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:422:11)
    at spawn (child_process.js:532:38)
    at C:\Users\Acer\Desktop\Pranava Web Development\bootstrap 4\Bootstrap4\conFusion\node_modules\parallelshell\index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Acer\Desktop\Pranava Web Development\bootstrap 4\Bootstrap4\conFusion\node_modules\parallelshell\index.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! confusion@1.0.0 watch:all: `parallelshell "npm run watch:scss" "npm run lite"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the confusion@1.0.0 watch:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-11-06T01_33_07_538Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! confusion@1.0.0 start: `npm run watch:all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the confusion@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-11-06T01_33_07_644Z-debug.log

**Comment by jason822** [comment]
Are you running Laravel / Vue.js?
In laravel 8.x, it provides Jetstream / Inertia as default.
In case npm doesn't run properly, you can remove package.json lock file, and then update npm modules again.

Another solution is to move source project to primary disk (i.e D or E, not C)

**Comment by iamthefreeman** [comment]
You might be running an old version of node/npm. If you are running an old version, I would recommend upgrading it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by TrendTrickster** [comment]
Hey.

Thanks for your response to this question , But I am not using laravel I am
Using Git, Node Js, Visual Studio.

I cannot run NPM START in the cmd as i change the package.json file
start: npm run watch:all

**Comment by TrendTrickster** [comment]
Kindly Help Me in This as I am Just a Beginner. I am Creating a Website.

I am Learning In coursera About This.

Please 🙏🙏🙏🙏

**Comment by tejirimakel** [comment]
try downgrading from npm install --save-dev parallelshell@3.0.2 to npm install --save-dev parallelshell@3.0.1
