### ISSUE TITLE
Command package:discover crashes when using Composer 2

### ISSUE THREAD

**Issue by freecod** [laravel/framework#35127]
- Laravel Version: 5.8.35
- PHP Version: 7.2.30
- Database Driver & Version:

### Description:

After updating composer to version 2, the command 
"@php artisan package: discover --ansi" 
from the "post-autoload-dump" scripts crashes with an error

In PackageManifest.php line 122:
   Undefined index: name

The crash occurs because the command reads the vendor/composer/installed.json and expects to receive an array of packages, but in the new composer 2 format, the packages are nested under the "packages" node:

{
     "packages": [
         {
             "name": "asm89 / stack-cors",
             "version": "1.2.0",
             "version_normalized": "1.2.0.0",
        ...
    ]
}

### Steps To Reproduce:

1) Install stable composer ver 2
2) Run "composer require some/package"

**Comment by driesvints** [comment]
Upgrade to the latest Laravel 5.8 version which has support for Composer 2
