### ISSUE TITLE
Add DateTime milliseconds to database Grammar bindings

### ISSUE THREAD

**Issue by TeroBlaZe** [laravel/framework#35135]
Laravel Version: 8.13.0
PHP Version: 7.4.11
Database Driver & Version: default Laravel installation PDO, MySQL 5.7

https://github.com/laravel/framework/blob/8550bac5cf4d9e8d52296c1f6d93bbf7f4596002/src/Illuminate/Database/Grammar.php#L189-L197
As a DateTime column precision could be stored in a database it is convenient to change query format binding to `Y-m-d H:i:s.u`

**Comment by driesvints** [comment]
This isn't necessary.

**Comment by TeroBlaZe** [comment]
> This isn't necessary.

I can't agree. It is necessary to query rows that contain milliseconds. And without this change, you are unable to implement precise time-based cursor pagination.

**Comment by driesvints** [comment]
@TeroBlaZe most of the datetime columns are timestamps which are in seconds, not miliseconds.

**Comment by TeroBlaZe** [comment]
@driesvints Maybe so but you also could use the TIMESTAMP precision option to add milliseconds and microseconds but you unable to filter on it because of this query format. There should be an option to support this format as you need it. What do you think?

**Comment by driesvints** [comment]
You can already modify this format on your models by setting the `$dateFormat` property:

```php
protected $dateFormat = 'Y-m-d H:i:s.u';
```

**Comment by TeroBlaZe** [comment]
> You can already modify this format on your models by setting the `$dateFormat` property:
> 
> ```
> protected $dateFormat = 'Y-m-d H:i:s.u';
> ```

Why do think am I talking about eloquent and models? This variable can do nothing with DB's queries. There's a place that does a thing.
https://github.com/laravel/framework/blob/a9af73f4bac48ea29d49d918c52a41628089358c/src/Illuminate/Database/Connection.php#L587-L609

I think the issue was closed without a reason so please reopen it so anyone else can see it. Maybe someone can provide a better solution than mine.

**Comment by driesvints** [comment]
We're not changing this, sorry.

**Comment by rwinzhang** [comment]
I happen to face this issue too. The `$dateFormat` on Model only affects when we save the model but not when we need to query. My use case is not on the microseconds, but when I want to query with a specific timezone and `Y-m-d H:i:s` format makes the timezone information truncated and returns wrong results. I think we need a way to configure this like doing `Grammar::setDateFormat('Y-m-d H:i:s.uP')` on `AppServiceProvider`, so I can override it when needed. Please consider this suggestion @driesvints, Thanks.
