### ISSUE TITLE
SQL error on replicated model

### ISSUE THREAD

**Issue by AleeeKoi** [laravel/framework#35132]
- Laravel Version: 8.13.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7

### Description:

Hello,
executing a `loadCount` on a model, then replicating it and then try to save it produce a Mysql error.
It's like the replication produce and invalid model. Without replication works fine.

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users_count' in 'field list'`

### Steps To Reproduce:

```
if ($thisModel->exists && $thisModel->loadCount('users')->users_count > 0) {
    $thisModel= $thisModel->replicate();
}
$thisModel->save();
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by AleeeKoi** [comment]
@driesvints ok, asked (but I really think it's a but).
If I unset manually the model property before save it works fine `unset($policy->users_count);`
I think there is a problem during the replication.
Thank you
