### ISSUE TITLE
Creating policies with Models returns strange ffect.

### ISSUE THREAD

**Issue by MyNameIsAres** [laravel/framework#35133]
- Laravel Version: 8.10.0
- PHP Version: 7.4.3
- Database Driver & Version: Not relevant I believe?

### Description:
When I create a policy using the Artisan command:
`php artisan make:policy -m=Test`

The Policy's skeleton (or scaffolding) is messed up. The `use` statement at the top that imports the model becomes:
`use App\Models\=Test` 

The method parameters for anything **other **than**** the `User $user` parameter is messed up too. 
For example: 

```
    /**
     * Determine whether the user can view the model.
     *
     * @param  \App\Models\User  $user
     * @param  \App\Models\=Test  $=Test
     * @return mixed
     */
    public function view(User $user, =Test $=Test)
    {
        //
    }
```

Notice the unusual '=' symbols. To my knowledge, those aren't supposed to be there.

### Steps To Reproduce:
Create a policy with a given model:
`php artisan make:policy -m=Test` (for example)

Open the policy, and simply observe.

**Comment by driesvints** [comment]
Just use `php artisan make:policy FooPolicy -m Test`
