### ISSUE TITLE
Embedded image does not display on browser preview

### ISSUE THREAD

**Issue by yuyenkan** [laravel/framework#35134]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Database Driver & Version: mysql

### Description:
the embedded image on browser preview showing nothing but ok in mailing

### Steps To Reproduce:
<head>
</head>
<body>
<img src="{{ $message->embed(asset('image.png')) }}" />
</body>

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
