### ISSUE TITLE
Decimal not input

### ISSUE THREAD

**Issue by Monte4952** [laravel/framework#35144]
- Laravel Version: 6.5.0
- PHP Version: 7.2.3
- Database Driver & Version:

### Description:
Hi
I tried decimal value with DB query builder and Eloquent and updated it without errors.
But I don't get the decimal value.
I want any solutions to this issue.

- MySQL field:

           price : decimal(10,2) or float(10,2)

- DB builder:

            $dataArray= array(
                'price'=>45.34,
            );
            DB::table('track_asin')->where('id','=',2627119)->update($dataArray);

- Eloquent:

            $dataArray= array(
                'price'=>45.34,
            );
            TrackAsin::where('id','=',2627119)->update($dataArray);

- Database Result:
          
          price = 45.00
Thank you for advance

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
