### ISSUE TITLE
storage driver sftp, Exception "This driver does not support retrieving URLs."

### ISSUE THREAD

**Issue by kolyayurev** [laravel/framework#35159]
- Laravel Version: v8.12.3
- PHP Version: v7.4.3
- Database Driver & Version: MySQL 5.7

### Description:

I get Exception  

> "This driver does not support retrieving URLs."

when try get image url from storage:
` Storage::disk('sftp')->url('users/default.png');`

I am use `league/flysystem-sftp` driver as in the official documentation

### Steps To Reproduce:
1. add to config "filesystems"
'sftp' => [
 'driver' => 'sftp',
 'host' => '192.168.11.111', // my sftp serverip
 'username' => 'username',
 'password' => 'password',
]
2. set in .env file FILESYSTEM_DRIVER=sftp
3. clear config cache
4.  do this code:
` Storage::disk('sftp')->url('users/default.png');`
5. get Exception  "This driver does not support retrieving URLs."

### Screeshots
![image](https://user-images.githubusercontent.com/56155627/98577513-1f145b80-22cd-11eb-822e-98e9da0d1189.png)

**Comment by kolyayurev** [comment]
Perhaps there is a better adapter than this ` league/flysystem-sftp` ?

**Comment by driesvints** [comment]
The exception message is obvious here I think. I think if you need an url based alternative you might be better off with something like an S3 bucket.
