### ISSUE TITLE
Migrating a SQLite database from a schema doesn't work on Windows

### ISSUE THREAD

**Issue by duncan-c** [laravel/framework#35162]
- Laravel Version: 8.13.0
- PHP Version: 7.4.11
- Database Driver & Version: sqlite v3.32.2

### Description:
When trying to migrate a blank instance of a sqlite database, from the database/schema directory, on Windows the command fails with the error:
`The command "sqlite3 $LARAVEL_LOAD_DATABASE < $LARAVEL_LOAD_PATH" failed.`
`The system cannot find the file specified.`

I believe this is because the environment variables used in the *SqliteSchemaState.php* file are the Linux type, and aren't actually resolved in Windows. In the *MysqlSchemaState.php* file the commands use the variable format: `${:LARAVEL_LOAD_PATH}`, and changing to this format in *SqliteSchemaState.php* resolves this issue (I will make a PR for this).

After this is resolved the migration works fine when using an sqlite file as the database instance, but when using a memory database, the migration fails with the following output:

```
Migration table created successfully.
Loading stored database schema: .....\schema/sqlite-schema.dump
Loaded stored database schema. (205.50ms)

In Connection.php line 671:                                                      
  SQLSTATE[HY000]: General error: 1 no such table: migrations (SQL: select "migration" from "migrations" order by "batch" asc, "migration" asc) 

In Exception.php line 18:
  SQLSTATE[HY000]: General error: 1 no such table: migrations  

In PDOConnection.php line 78:
  SQLSTATE[HY000]: General error: 1 no such table: migrations  
```

### Steps To Reproduce:
1. Place an sqlite schema at: `database/schema/sqlite-schema.dump`
    - The file can just contain this line for simplicity:
```
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
```
2. Run a migration `php artisan migrate --database=sqlite` (make sure the sqlite database is blank before this)
    - You should get an error as described above

3. Fix the *SqliteSchemaState.php* file by changing `$LARAVEL_LOAD_PATH` on line 63 to `"${:LARAVEL_LOAD_PATH}"`, and `$LARAVEL_LOAD_DATABASE` on line 77 to `"${:LARAVEL_LOAD_DATABASE}"` (including the double quotes)

4. Run the migration again (make sure the sqlite database is a file, not memory)
    - This should work fine

5. Change your `.env` file to set `DB_DATABASE=:memory:`, and refresh the config cache

6. Run the migration again
    - This should fail with the error described above

**Comment by driesvints** [comment]
Will be in today's release. Thanks.

**Comment by duncan-c** [comment]
Thanks! Although the PR only fixes the first error, and doesn't fix the problem seen when trying to use the sqlite schema with an in-memory database.

**Comment by driesvints** [comment]
I managed to reproduce that. I dived deep into this but cannot figure out. It seems to me that for some reason the schema dump isn't loaded into the in-memory database. I *think* it's related somewhere to these lines:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L143-L145

Maybe it has something to do with the combination of output buffering and in memory DB.

**Comment by taylorotwell** [comment]
In memory database loading is not supported I don't believe. The restore is currently done using the `sqlite3` binary and that would execute in an entirely difference process from your local Laravel process's in memory database.

I'm not sure if restoring to in memory databases is easily possible. But, it is not supported at all right now and thus is a feature request. Anyone is welcome to take a stab at a PR to support it.

**Comment by taylorotwell** [comment]
Personally I recommend just using a file-based SQLite database during testing if you want to use schema dumps. You can create a separate database file for your tests.

**Comment by duncan-c** [comment]
Yep, that's what I've done (test database file). Makes sense about the separate processes preventing it from working. If I get a chance I'll see if I can add support in, but the file works fine so it's not an urgently needed feature for sure!

**Comment by driesvints** [comment]
I was thinking that might be happening but couldn't figure out the exact reason. Thanks for clarifying @taylorotwell. 

We've also updated the docs to indicate that database dumps cannot be combined with in-memory databases.
