### ISSUE TITLE
Sometimes validation rule does not work

### ISSUE THREAD

**Issue by Williamug** [laravel/framework#35167]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

I have been trying to apply a sometimes validation of an image field but does not work out.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
