### ISSUE TITLE
Preview email with embed image : wrong url 

### ISSUE THREAD

**Issue by neoteknic** [laravel/framework#35169]
- Laravel Version: 8.13.0
- PHP Version: 7.4.12
- Database Driver & Version: Mariadb 10.5.6

### Description:
In browser preview (return a mailable) from a blade tempalte (not markdown).
Links with $message->embed(public_path('url'))
Should output /url instead of cid:hash
Images aren't visible in preview.

### Steps To Reproduce:

Create a Mail (extends Mailable) with a blade template and an embed image.
Try to preview it from browser
Same as this (but wrong Laravel version) #35134

**Comment by driesvints** [comment]
This is unfortunately impossible at this time. As there's no way for the mailer to know if the mail is sent to a browser or being rendered in preparation for being sent we also cannot know when to swap out the SwiftMailer calls for the CID embedded attachments. 

I've sent a note to the docs about this: https://github.com/laravel/docs/pull/6561

**Comment by taylorotwell** [comment]
Easiest way to preview these emails would be to just send them to a real testing client like Mailhog or HELO.
