### ISSUE TITLE
fulfill method in EmailVerificationRequest class does'nt check for verified user

### ISSUE THREAD

**Issue by ScriptingBeating** [laravel/framework#35168]
- Laravel Version: 8.12.3
- PHP Version: 7.4
- Database Driver & Version: Mysql 8.0

### Description:
`fulfill` method in `EmailVerificationRequest` class does not check if the user's email is already verified and updates email_verified_at timestamp again 

currently, it is doing this

```
public function markEmailAsVerified()
{
    return $this->forceFill([
        'email_verified_at' => $this->freshTimestamp(),
    ])->save();
 }
```

Expected :

```
public function markEmailAsVerified()
{
   if (!$this->hasVerifiedEmail()) {
        return $this->forceFill([
           'email_verified_at' => $this->freshTimestamp(),
        ])->save();
   }
 }
```

**Comment by driesvints** [comment]
You usually don't call this method again when the email has already been verified.

**Comment by ScriptingBeating** [comment]
https://laravel.com/docs/8.x/verification#the-email-verification-handler
In the documentation, it was mentioned that you can call the `fulfill` method directly after declaring the route and using the `EmailVerificationRequest` Request class, so I thought that it should be this class's responsibility to check if the user is already verified or not

**Comment by driesvints** [comment]
Hmm actually, this might be better off as a check at the beginning of the `fulfill` method in the `EmailVerificationRequest` itself. So the event doesn't gets fired again either. Can you maybe send in a PR for that?

**Comment by ScriptingBeating** [comment]
@driesvints  Yes, sure I would love to.
