### ISSUE TITLE
Laravel has a serieus caching issue

### ISSUE THREAD

**Issue by martijnhiemstra** [laravel/framework#35176]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Database Driver & Version: Not needed

### Description:

I changed my email password on my mail server. I then changed the MAIL_PASSWORD value in my .env file. I cleared my cache, my configuration and route and view cache. I connected to my mail account from thunderbird and I could connect immediately with the new password so the new password works. 

I then visited my website, I sent an email and I kept getting errors that the password was wrong. The password was printed in the logs and it was the old password!!! I then used the following command to find the password:

```
grep -Ril "THEMAILPASSWORD" ./
```  

It could not find the old password, anywhere. The only conclusion is that there is a serious flaw in Laravel that is caching environment values somewhere. I have no idea where. The old value could not be found on the harddisk. I ran all the clear commands. And still the mail was using the old password.

**Comment by ash-jc-allen** [comment]
I might be barking up the wrong tree here and it might not be much help for you. But are your emails that you're sending queued? If so, have you tried restarting the queues?

I think the config is cached in the queue system, so whenever anything in the config changes you need to restart the queues to get the new values.

Hopefully this helps. Sorry if you already knew this though 😄

**Comment by themsaid** [comment]
Did you deploy your app after the environment changes? Did you restart your workers?

**Comment by GrahamCampbell** [comment]
You need to regenerate your config cache, not just clear it, and also reload php-fpm and restart your queue workers.

**Comment by taylorotwell** [comment]
Closing because this is user error. Laravel doesn't cache environment variables in secret locations.
