### ISSUE TITLE
Error on Composer Install new project at Generating optimized autoload files stage 

### ISSUE THREAD

**Issue by ashvinih** [laravel/framework#35170]
Installed Homestead on Nov 10, 2020 to version 11.x 
ssh in to homestead box run following commands

Run create project command 
> laravel new apomsrep --jet

at the end of project creation following messages are shown

=======
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Parse error:  syntax error, unexpected end of file in /home/vagrant/projects/apomsrep/vendor/laravel/framework/src/I
lluminate/Foundation/Application.php on line 649
=======

If I try to run 
> php artisan serve

I get following error

=======
PHP Parse error:  syntax error, unexpected end of file in /home/vagrant/projects/apomsrep/vendor/laravel/framework/src/I
lluminate/Foundation/Application.php on line 649

Parse error: syntax error, unexpected end of file in /home/vagrant/projects/apomsrep/vendor/laravel/framework/src/Illumi
nate/Foundation/Application.php on line 649
=======

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
