### ISSUE TITLE
GuardsAttributes::isGuarded() function not working

### ISSUE THREAD

**Issue by cbaobviux** [laravel/framework#35172]
- Laravel Version: 7.29.3
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
To my understanding the function GuardsAttributes::isGuarded($key) is not working properly. The problem is located line 206 in src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php. I believe the should be:

               ! $this->isGuardableColumn($key);

and not 

               $this->isGuardableColumn($key);
 

### Steps To Reproduce:

Create app\Models\TestModel.php as this:
`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TestModel extends Model
{
    public function myFunc(): bool
    {
        return $this->isGuarded('key');
    }
}
`

Execute the following:
---cut---cut---cut---cut---cut---cut---cut---cut---cut---cut---
$  ./artisan tinker
Psy Shell v0.10.3 (PHP 7.3.11 — cli) by Justin Hileman
>>> $testModel = new App\Models\TestModel();
=> App\Models\TestModel {#6138}
>>> $testModel->myFunc();
=> true
>>> 
---cut---cut---cut---cut---cut---cut---cut---cut---cut---cut---

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by cbaobviux** [comment]
Well, from just browsing the source code of version 8 it seems the bug also exists there.

**Comment by driesvints** [comment]
I doubt this is a bug. Best thing you can do is send in a PR with a failing test to prove that a bug is happening.
