### ISSUE TITLE
Rendering a Blade View Component in PHP code does not work

### ISSUE THREAD

**Issue by WC-Jordy** [laravel/framework#35187]
- Laravel Version: 8.14.0
- PHP Version: 7.4.9
- Database Driver & Version: PDO mysqlnd 7.4.9

### Description:
I want to render a Blade View Component in PHP but when calling the 'render' method, I get 'Undefined variable: attributes':
![image](https://user-images.githubusercontent.com/69194376/98814523-14210e80-2426-11eb-8143-a5b453257abb.png)

I made sure to pass the attributes by calling 'withAttributes' which adds a 'ComponentAttributeBag'. This is how the object looks like:
![image](https://user-images.githubusercontent.com/69194376/98814732-62361200-2426-11eb-94fb-ad8f526230ae.png)

### Steps To Reproduce:
1. Instantiate a new view component.
2. Call the 'withAttributes' method on the component and pass any array.
3. Call the 'render' method.

**Comment by taylorotwell** [comment]
No idea because there is no code here.
