### ISSUE TITLE
Can't access nested resoures id from constructor

### ISSUE THREAD

**Issue by hsul4n** [laravel/framework#35192]
- Laravel Version: 8.0
- PHP Version: 7.4.12

When trying to access nested resource id I got `BindingResolutionException`:
```php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TestController extends Controller
{
    // throws BindingResolutionException: "Unresolvable dependency resolving"
    public function __construct(Request $request, $wallet_id)
    {
    }
}
```

```php
// routes/api.php

Route::apiResource('api/v1/wallets.test', 'WalletTestController');
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
