### ISSUE TITLE
Constructor request return null user

### ISSUE THREAD

**Issue by hsul4n** [laravel/framework#35191]
- Laravel Version: 8.0
- PHP Version: 7.4.12

When trying to access user from construct request it returns null:
```php
<?php

namespace App\Http\Controllers\API\Customer\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    public function __construct(Request $request)
    {
        dd($request->user()); // return null
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rodrigopedra** [comment]
That is by design, since Laravel 5.3

> [Since] Laravel 5.3, you can't access the session or authenticated user in your controller's constructor because the middleware has not run yet.

https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors

That upgrade guide provides an alternative.
