### ISSUE TITLE
Queue worker ignores job's maxTries setting if using retryUntil()

### ISSUE THREAD

**Issue by trevorgehman** [laravel/framework#35199]
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: Mysql 8.0.21 / Redis 5.0.7

### Description:
There is a discrepancy between how the worker treats `$job->retryUntil()` and `$job->maxTries()` depending on whether an exception is thrown. This only affects jobs where `retryUntil()` is used.

Essentially, if a job throws an exception, if _either_ `$job->retryUntil()` is exceeded _or_ `$job->maxTries()` is exceeded, the job fails. This seems to be the expected behavior.

However, if the job _doesn't_ throw an exception, but is just released (such as when using a rate limit middleware), then only `$job->retryUntil()` is considered and `$job->maxTries()` doesn't matter.

#### Job that throws an exception:
1. Create a job with `$tries=5` and `retryUntil() { return now()->addHour(); }`.
2. Throw an exception in the job.
3. The job will be attempted 5 times, then fail.

#### Job that is just released:
1. Create a job with `$tries=5` and `retryUntil() { return now()->addHour(); }`.
2. Use a middleware that just releases the job.
3. The job will be attempted repeatedly for 1 hour.

Note that in either case (whether throwing an exception or releasing the job), the number of attempts is incremented.

### Details:
When picking up a job, the worker first checks the number of attempts:

https://github.com/laravel/framework/blob/72ea7baf3eeb1efa0b6c36423bc98382725f38a9/src/Illuminate/Queue/Worker.php#L395-L397

This method prioritizes `retryUntil()`. That is, if you use `$job->retryUntil()`, it doesn't matter what the `$tries` property is on the job or the `--tries` parameter is on the worker. The `$job->retryUntil()` method essentially overrides them:

https://github.com/laravel/framework/blob/72ea7baf3eeb1efa0b6c36423bc98382725f38a9/src/Illuminate/Queue/Worker.php#L474-L480

If the job throws an exception, the worker again checks the number of attempts:

https://github.com/laravel/framework/blob/72ea7baf3eeb1efa0b6c36423bc98382725f38a9/src/Illuminate/Queue/Worker.php#L432-L434

But this time, `retryUntil()` is _not_ prioritized. Meaning, if _either_ the time set in `retryUntil()` is passed _or_ the max attempts (as specified on the job or worker) is exceeded, the job will be marked as failed:

https://github.com/laravel/framework/blob/72ea7baf3eeb1efa0b6c36423bc98382725f38a9/src/Illuminate/Queue/Worker.php#L500-L506

**Comment by taylorotwell** [comment]
IMO `retryUntil` and `maxTries` are sort of mutually exclusive. Either you want the job to retried until a given time is reached or you want it to be retried a specific number of times. When using `retryUntil` I would use `maxExceptions` if you want to determine how many uncaught exceptions are allowed:

https://laravel.com/docs/8.x/queues#max-exceptions

**Comment by trevorgehman** [comment]
> IMO `retryUntil` and `maxTries` are sort of mutually exclusive. Either you want the job to retried until a given time is reached or you want it to be retried a specific number of times. When using `retryUntil` I would use `maxExceptions` if you want to determine how many uncaught exceptions are allowed:
> 
> https://laravel.com/docs/8.x/queues#max-exceptions

That's how I thought it worked originally and I think that makes more sense. The documentation seems to indicate that all you need to do is use `retryUntil()`, but unless I'm missing something, you also need to set `--tries=0` on the worker or `$tries = 0` on the job, because by default it is set to 1:

https://github.com/laravel/framework/blob/e9483c441d5f0c8598d438d6024db8b1a7aa55fe/src/Illuminate/Queue/Console/WorkCommand.php#L37

And when an exception is thrown, it will check the `$maxTries` after checking `$job->retryUntil()`:

https://github.com/laravel/framework/blob/72ea7baf3eeb1efa0b6c36423bc98382725f38a9/src/Illuminate/Queue/Worker.php#L504-L506

**Comment by trevorgehman** [comment]
Either way, it seems like these two methods shouldn't contain different logic:

https://github.com/laravel/framework/blob/e9483c441d5f0c8598d438d6024db8b1a7aa55fe/src/Illuminate/Queue/Worker.php#L468-L485

https://github.com/laravel/framework/blob/e9483c441d5f0c8598d438d6024db8b1a7aa55fe/src/Illuminate/Queue/Worker.php#L496-L507

**Comment by themsaid** [comment]
We need to decide which logic we want to keep and change the other one.

Should `retryUntil` and `maxAttempts` work together or `maxAttempts` should be ignored if `retryUntil` was set?

**Comment by trevorgehman** [comment]
I think what you did in the PR is the best approach: `retryUntil()` essentially overrides `maxAttempts`.

**Comment by kam2yar** [comment]
I have the same issue. 
In my situation, I need to run my queue 5 times before 5 minutes.
and if takes much longer than 5 minutes get fail. 
also if it process too fast and I tried 5 times no more new jobs are needed.

I think maybe you can affect tries to queue run.
thanks.

**Comment by miken32** [comment]
> IMO `retryUntil` and `maxTries` are sort of mutually exclusive. Either you want the job to retried until a given time is reached or you want it to be retried a specific number of times.

I found this issue during a search, thinking something was broken. The quoted logic makes sense but it should be more explicitly explained in the documentation that `retryUntil()` negates `$tries` and `tries()` completely.

>When using `retryUntil` I would use `maxExceptions` if you want to determine how many uncaught exceptions are allowed:

Note that having a `retryUntil()` method also causes the value of `$maxExceptions` to be ignored.
