### ISSUE TITLE
The form validator mimes and Store method in Illuminate\Http\UploadedFile.php problem with m4a audio files

### ISSUE THREAD

**Issue by reza-kharestani** [laravel/framework#35203]
- Laravel Version: 7.29.2
- PHP Version: 7.2.10
- Database Driver & Version: MySQL: 5.7.23 MariaDB: 10.3.9

### Description:

the bug is: I upload a **m4a** format file and it stores it as a **mp4** file in the server! and more:

The form validator checking mimes and also the Store method in Illuminate\Http\UploadedFile.PHP has a problem with m4a audio formats. I made a form in which I upload a file to the server using the mimes as a validation step before processing the form, even though my uploaded files are **m4a** the validation function does not accept them and returns an error. when I use the dd function to check the uploaded file mime type it appears it recognized the mime type as **audio/x-ma4** and even when I add this to the validation it does not accept the file, then I added mp4 to the mime type and suddenly the m4a file was got validated as an mp4 file and when the store function from UploadedFile.php try to store my uploaded file to the server it saves the file in a new mp4 format!!! basically, I upload a m4a format file and it stores it as a mp4 file on the server!!!

I poked around the multiple functions and I think actually the **guessMimeType** method in "Symfony\Component\Mime\MimeTypes" makes the ultimate mistake of guessing the mime. and it goes south from there!

### Steps To Reproduce:
I made a simple form with this blade view:
```blade
<form action="{{ route('upload-audio') }}"  method="post" enctype="multipart/form-data">
	@csrf
		<div class="form-group">
			<input type="file" class="form-control" id="audio" name="audio">
			@if ($errors->has('audio'))
				{{ $errors->first('audio') }}
			@endif
		</div>
	</div>
	<div class="form-inline form-group">
		<button type="submit" class="btn btn-default">upload</button>
	</div>
</form>
```
and my controller method to handle the uploaded data:
```php
    /**
     * Show the upload document page
     *
     * @return \Illuminate\Http\Response
     */
    public function uploadContent(Request $request)
    {
        $request->validate([
            'audio' => 'required|mimes:m4a,mp4,mp3'
        ]);
        $path = $request->file('audio')->store('audio');
        return $path;
    }
```
if I use the below code the validator does not accept the m4a upload file at all:
```php
            'audio' => 'required|mimes:m4a,mp3'
```
I also checked other possibilities like these but none of them are working:
```php
            'audio' => 'required|mimetypes:audio/x-m4a
            'audio' => 'required|mimetypes:audio/x-m4a|mimes:m4a,mp3
```
the only thing that working around the validation is 
```php
            'audio' => 'required|mimes:m4a,mp4,mp3'
```
but it stores the **m4a** file as a **mp4** file in the server

**Comment by taylorotwell** [comment]
You need to report this to Symfony, who manages the MIME guessing.

**Comment by reza-kharestani** [comment]
OK!
just for people who may has this problem! Actually, I found out my problem was local due to the PHP **finfo** function using a local file which is explained here:
[https://stackoverflow.com/questions/12272098/php-finfo-detecting-m4a-audio-as-video/12272150](url)
