### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#35200]
- Laravel Version: 8.14.0
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
Base Unit test looks like [this](https://github.com/laravel/laravel/blob/8.x/tests/Unit/ExampleTest.php):
```php
public function testBasicTest()
{
    $this->assertTrue(true);
}
```
when I add that line `$users = User::all();` - and of course on top of file `use App\Models\User;` - I get:
```shell script
Error: Call to a member function connection() on null

/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1492
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1458
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1265
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1182
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1218
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1171
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1161
/var/www/cpt.local/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:475
/var/www/cpt.local/html/tests/Unit/ExampleTest.php:18
```
The same line works in all `Feature` tests.

### Steps To Reproduce:
Try to run that test:
```php
public function testBasicTest()
{
    $this->assertTrue(true);
    $users = User::all();
}
```

**Comment by driesvints** [comment]
You're extending the PHPUnit test case instead of the Laravel TestCase. If you need a database connection write a feature test.

Also: it's always a good idea to try to search for your issue before posting as this has been posted many times before.

**Comment by LocalHeroPro** [comment]
Did you have describe it in https://laravel.com/docs/8.x/database-testing?
I only see:
>  Unit tests are tests that focus on a very small, isolated portion of your code. In fact, most unit tests probably focus on a single method.

**Comment by driesvints** [comment]
A small isolated portion of your code doesn't involves a database connection.

**Comment by LocalHeroPro** [comment]
I don't see that in docs. :confused:
