### ISSUE TITLE
If APP_URL doesn't have a protocol, "http://localhost/" is prepended to all URLs when running in the console

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/framework#35206]
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: n/a

### Description:

If the `APP_URL` environment variable does not include a protocol (e.g. `my-app.test`), URLs generated inside console commands, using the `url()` helper, the `URL` Facade, or `UrlGenerator` directly, will all have `http://localhost/` prepended.

Related to #2554 but this has nothing to do with subdirectories.

### Steps To Reproduce:

1. `laravel new my-app`
2. In `routes/console.php`:

```php
<?php

use Illuminate\Support\Facades\Artisan;

Artisan::command('url', function () {
    $this->info(url('/'));
});
```

3. Update `.env` to remove `http://` from `APP_URL` (e.g. `my-app.test`)
4. `php artisan url`

**Output**:

`http://localhost/my-app.test`

**Expected**:

Not sure honestly, but definitely not that. Probably just `my-app.test`, the value of `APP_URL`?

I know `my-app.test` on its own like that is not technically a valid URL, but it's more valid than `http://localhost/my-app.test` and would work normally in lots of situations (whereas `http://localhost/my-app.test` won't).

Happy to PR this but not sure yet where exactly to put the console check, I'd be interested to hear your thoughts.

**Comment by GrahamCampbell** [comment]
> If the APP_URL environment variable does not include a protocol

This case is not supported. You must provide a protocol. Behaviour of the framework is undefined in the case where you produce an invalid app url.

**Comment by rodrigopedra** [comment]
`APP_URL` should be a URL, and a scheme (or protocol) is a required part of a URL.

You should use `APP_URL=http://my-app.test` or `APP_URL=https://my-app.test` in case your local server have SSL configured.

References:

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax

https://tools.ietf.org/html/rfc2396#section-1.3

https://tools.ietf.org/html/rfc3986#section-1.1.1

From the last reference:

> Each URI begins with a scheme name...

Note: All URLs (Uniform Resource Locators) are URIs (Uniform Resource Identifiers).

**Comment by bakerkretzmar** [comment]
Thanks! To clarify, I know there always _should_ be a protocol, this behaviour just seemed pretty wacky in the case where there isn't for whatever reason. Context: tighten/ziggy#359.

If `APP_URL` without a protocol is wrong enough that this behaviour doesn't matter, cool. Not being sarcastic—I genuinely don't know how common this is and if it's worth even thinking about. I guess I was just wondering if there's a more graceful way to fail, maybe even throwing an exception if it's not a valid URL, to tip the user off, instead of silently creating something even weirder.

Feel free to close if you don't think this is worth addressing further 👍🏻

**Comment by rodrigopedra** [comment]
No problem, was only trying to clarify a protocol is needed. 

People often forget about that, mostly because these days the protocol gets hidden by most browsers and platforms (twitter hides them when sharing links, for example).

Please apologize if I sounded rude in any way, wasn't my intention.
