### ISSUE TITLE
Incrementing a json column value throws error but does change the value in DB

### ISSUE THREAD

**Issue by imanghafoori1** [laravel/framework#35205]
- Laravel Version: 8.14.0
- PHP Version: 7.3.23
- Database Driver & Version: mysql 5.7.24-winx64

### Description:
If we try this query, the age value in DB does increment up, but it also throws an error in php.

```php
Person::first()->increment('my_json_col->age');
```
Error:
```
ErrorException
Undefined index: my_json_col->age
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:1431
```

### Steps To Reproduce:
Create a sample model:
```php
protected $casts = [
   'my_json_col' => 'json',
];
```

In migration:
```php
$table->json('my_json_col')->nullable();
```
save a value in the table:
```php
...
$person->my_json_col = ['age' => 0];
$person->save();
```
then you can try to increment the age.
```php
Person::first()->increment('my_json_col->age');
```

Thanks in advance.

**Comment by taylorotwell** [comment]
These methods do not attempt to support JSON columns, thus this is a feature request and not a bug.
