### ISSUE TITLE
Detection of MariaDB doesn't work (MySqlConnection.php->isMaria)

### ISSUE THREAD

**Issue by TimStollberg** [laravel/framework#35223]
- Laravel Version: 8.8.0

- PHP Version: 7.4.12
=> Dockerfile => FROM php:7.4-apache

- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
=> https://github.com/docker-library/mysql/blob/1a25a09159a3d7b6b5b8ad0e6c7eb53504b3aab5/8.0/Dockerfile

### Description:

Hey Laravel team,
i tried to use the `php artisan schema:dump --prune` in my current setup. And received the following 

```
mysqldump: unknown variable 'set-gtid-purged=OFF'
mysqldump: unknown variable 'set-gtid-purged=OFF'

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 7(Unknown error)

Working directory: /var/www/html

Output:
================


Error Output:
================
mysqldump: unknown variable 'set-gtid-purged=OFF'

  at vendor/symfony/process/Process.php:252
    248▕      */
    249▕     public function mustRun(callable $callback = null, array $env = []): self
    250▕     {
    251▕         if (0 !== $this->run($callback, $env)) {
  ➜ 252▕             throw new ProcessFailedException($this);
    253▕         }
    254▕ 
    255▕         return $this;
    256▕     }

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

The issue starts when building the mysqldump command here: /laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php 

```
    protected function baseDumpCommand()
    {
        $columnStatistics = $this->connection->isMaria() ? '' : '--column-statistics=0';

        $gtidPurged = $this->connection->isMaria() ? '' : '--set-gtid-purged=OFF';

        return 'mysqldump '.$gtidPurged.' '.$columnStatistics.' --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}"';
    }

```

` $this->connection->isMaria()`

in /laravel/framework/src/Illuminate/Database/MySqlConnection.php doesn't work well, because the 

```
    public function isMaria()
    {
        return strpos($this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION), 'MariaDB') !== false;
    }
```

`$this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION)` 

returns "8.0.22".

(I tried it also with MySQL Docker image mysql-5.7 same issue - MySQL/MariaDB returns 5.7.x but now MariaDB in it.)

When i do a `mysql --version` on the console i get:

`mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

I googled a lot and i didn't find any easy solution to fix the code, because MySQL is returning that value. Relying on the return value of the MySQL/MariaDB server seems not to be safe enough.

Maybe there should be a mariaDB flag in the database.php config file(?)

_As a workaround I just used a 'return true;' in the isMaria() method, but that can't be the solution ;-)_

Thanks for you help and good work so far.

**Comment by driesvints** [comment]
Please upgrade to the latest version of the framework to see if that fixes your problem. If not, feel free to report back.

**Comment by TimStollberg** [comment]
Hello Dries Vints,

the newest Version I found is tagged as 8.14.0, correct?

The code that causes the issue hasn't change. Please see this commit (isMaria method):

https://github.com/laravel/framework/commit/fe45851e9ae2df4dab9aefd64254ac58f9c14593#diff-2457dcec4893341ec321a74bf80c296c8d8cb52f433ef25f262380aacf9afc08

So the issue is still existing. 

Cheers
Tim

**Comment by driesvints** [comment]
@TimStollberg I think you're facing a different problem here. The version "8.0.22" which if causing the issue is a MySQL version, not a MariaDB one. It seems you're connecting to a MySQL database, not a MariaDB one.

**Comment by TimStollberg** [comment]
@driesvints 
You're right. My bad. It was a MySQL container that was running.
I tried it with MariaDB and it works 👍 

Found the cause of it now.

Our DB container is MySQL:latest.
Our PHP container [php:7.4-apache] (including Laravel) installs the default-mysql-client

```
RUN apt-get update \
    && apt-get install -y default-mysql-client 
```

```
mysqldump --version
mysqldump  Ver 10.17 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64)
```


So Laravel checks the DB server for a version string to detect whether it is connecting to a MariaDB.
IMHO, this way is not reliable, because the mysqldump version (usable command parameters) on the local container (PHP/Laravel container) can vary.




In our case it we got the following errors.

```
root@local-be-app:/var/www/html# php artisan schema:dump --prune
mysqldump: unknown variable 'set-gtid-purged=OFF'
mysqldump: unknown variable 'set-gtid-purged=OFF'

   Symfony\Component\Process\Exception\ProcessFailedException

  The command "mysqldump --set-gtid-purged=OFF --skip-add-drop-table --skip-add-locks --skip-comments --skip-set-charset --tz-utc --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 7(Unknown error)

Working directory: /var/www/html

Output:
================


Error Output:
================
mysqldump: unknown variable 'set-gtid-purged=OFF'

  at vendor/symfony/process/Process.php:252
    248▕      */
    249▕     public function mustRun(callable $callback = null, array $env = []): self
    250▕     {
    251▕         if (0 !== $this->run($callback, $env)) {
  ➜ 252▕             throw new ProcessFailedException($this);
    253▕         }
    254▕
    255▕         return $this;
    256▕     }

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```
