### ISSUE TITLE
issue with queuing emails

### ISSUE THREAD

**Issue by lsmith77** [laravel/framework#35235]
- Laravel Version:  v8.9.0
- PHP Version:  7.3.24
- ramsey/uuid: 4.1.1 (latest version)
- Database Driver & Version:

### Description:
I am using Laravel Spark, sending invitation emails (ie. using `SendInvitation` which in turn uses `InviteUserEmail`). This causes an exception as the `$id` is an instance of `LazyUuidFromString` and not a string/integer, which breaks inside `\Illuminate\Queue\SerializesAndRestoresModelIdentifiers::restoreCollection()`.

I am opening the issue here because I suspect the issue isn't Spark specific.

### Steps To Reproduce:
Invite a user to a team inside Laravel Spark

### Hacky Fix

````
    protected function restoreCollection($value)
    {
        if (! $value->class || count($value->id) === 0) {
            return new EloquentCollection;
        }
        $collection = $this->getQueryForModelRestoration(
            (new $value->class)->setConnection($value->connection), $value->id
        )->useWritePdo()->get();
        if (is_a($value->class, Pivot::class, true) ||
            in_array(AsPivot::class, class_uses($value->class))) {
            return $collection;
        }
        $collection = $collection->keyBy->getKey();
        $collectionClass = get_class($collection);
        return new $collectionClass(
            collect($value->id)->map(function ($id) use ($collection) {
if ($id instanceof LazyUuidFromString) {
    $id = $id->serialize();
}
                return $collection[$id] ?? null;
            })->filter()
        );
    }`
```

**Comment by lsmith77** [comment]
I am not sure if this is related to https://github.com/ramsey/uuid/issues/327

**Comment by driesvints** [comment]
Please post your jobs.

**Comment by lsmith77** [comment]
It is a bit tricky .. as stated above, this is inside a Laravel Spark application, which is proprietary code, so I am not sure if I am allowed to share the code in a public ticket. so maybe even though I am fairly sure that the issue is inside the framework, I should rather discuss this with Laravel Spark maintainre?

**Comment by lsmith77** [comment]
Maybe what I can say is that the Spark code assigns `Uuid::uuid4()` as the ID of the model being serialized here. This returns an instance of `LazyUuidFromString`. Is this not allowed? ie. would it be the responsibility of the Spark code to ensure that the ID is a string?

**Comment by driesvints** [comment]
Hmm yeah it should be a scalar or at least have the option to be converted to a scalar. I'm talking this over with the team.

**Comment by lsmith77** [comment]
ok thank you .. there are 4 places where a UUID is assigned during model creation, if you have access to the code you can find them with the following search:
https://github.com/laravel/spark-aurelius/search?q=Uuid%3A%3Auuid4%28%29

**Comment by lsmith77** [comment]
Oh one more thing .. those places have not changed in a long time. So it was possible before to assign `Uuid::uuid4()` and indeed maybe the issue is a BC break inside the Ramsey UUID library.

**Comment by lsmith77** [comment]
hmm yeah .. LazyUuidFromString seems to be new in 4.0 and it does not have `__toString()` method, which is probably why things worked before, ie. it was just converted to a string when needed automatically.

**Comment by lsmith77** [comment]
ah no .. it does have a `__toString()`

**Comment by lsmith77** [comment]
so indeed forcing the string cast fixes the issue as well `return $collection[(string)$id] ?? null;`

**Comment by themsaid** [comment]
> Invite a user to a team inside Laravel Spark

I can invite a user to a team inside Laravel Spark without problems. We haven't received a similar issue from other customers. You'll need to share more details on your issue.

**Comment by lsmith77** [comment]
ok thx. do you also have ramsey/uuid 4.1+ ?

**Comment by themsaid** [comment]
What's the full stack trace of the exception you get?

**Comment by themsaid** [comment]
also what is `InviteUserEmail `?

**Comment by lsmith77** [comment]
ah damn indeed. this part is custom code.

anyway I have a work around, by simply forcing the id to be a string.

I will try to create a reproducable test case on plain Laravel to show the issue with using a model with UuidInterface instances as the ID while using the Queue. If I manage to do this then we can have a more productive discussion. Sorry for not doing this immediately. I clearly got confused about what is custom code and what is spark code.

closing the ticket for now until I have this reproducable test case.

**Comment by driesvints** [comment]
@lsmith77 no worries. Thanks for raising this. Glad you got it sorted 👍
