### ISSUE TITLE
Http retry function does not work with withHeaders function 

### ISSUE THREAD

**Issue by Tariq-rahman** [laravel/framework#35232]
- Laravel Version: 8.4
- PHP Version: 7.4.11
- Database Driver & Version: mariadb v10.4

### Description:
The HTTP client `retry` function causes an internal server error when using the function `withHeaders`

```
HTTP request returned status code 500: {"HttpStatusCode":500,"HttpStatusDescription":"Internal Server Error","Errors":[{"Message":"Internal exception occurred. (truncated...)
```

### Steps To Reproduce:

Create a API request (I am making a request to royal mail shipping api)

```
$response = Http::withHeaders([
                'x-ibm-client-id' => Config::get('royal-mail.clientId'),
                'x-ibm-client-secret' => Config::get('royal-mail.clientSecret'),
                'x-rmg-security-username' => Config::get('royal-mail.username'),
                'x-rmg-security-password' => Config::get('royal-mail.password'),

            ]);

            $response = $response->retry(3, 200);
            $response = $response->post('https://api.royalmail.net/shipping/v3/token');

```
 and send request. When the `withHeaders` function is used, the `retry` function fails and causes an error. without the `withHeaders` function the `retry` function function does not fail and instead I get a response from the API that my credentials are incorrect.

**Comment by driesvints** [comment]
What happens if you put retry first?

```
Http::retry(3, 200)
    ->withHeaders([
                'x-ibm-client-id' => Config::get('royal-mail.clientId'),
                'x-ibm-client-secret' => Config::get('royal-mail.clientSecret'),
                'x-rmg-security-username' => Config::get('royal-mail.username'),
                'x-rmg-security-password' => Config::get('royal-mail.password'),
            ])
    ->post('https://api.royalmail.net/shipping/v3/token');
```

**Comment by Tariq-rahman** [comment]
I still get the same result, when putting retry first

**Comment by taylorotwell** [comment]
Unable to recreate. 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/463230/99311485-4796db00-2822-11eb-9829-1960c11148ae.png">
