### ISSUE TITLE
artisan migrate not working on laravel 8.12, doctrine/dbal 3.0

### ISSUE THREAD

**Issue by batjeciftci** [laravel/framework#35237]
Running the command php artisan migrate results in Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found. I looked in the dbal's directory and it seems like the structure changed.

**Comment by driesvints** [comment]
There's a PR open for this which will be merged soon: https://github.com/laravel/framework/pull/35236

**Comment by enniosousa** [comment]
@driesvints the PR #35236 was mergerd and this issue isn't solved.

https://github.com/laravel/framework/blob/a94c16d9408e1f0d37f9d3fd4d4439e903072435/src/Illuminate/Database/MySqlConnection.php#L5

**Comment by GrahamCampbell** [comment]
@batjeciftci Please do look at the suggested packages output from composer. It tells you what versions of dbal are supported.
