### ISSUE TITLE
Email validation is incorrect

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [laravel/framework#35234]
- Laravel Version: 7.x, 8.x
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:
Email validation is incorrect. It passes when there is space(s) around `@` sign. e.g: `test@ gmail.com` or `test @gmail.com`

### Steps To Reproduce:
```php
class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testEmailValidationFailsForInvalidEmails() {
        $testInvalidEmailFails = function($email) {
            $validator = \Validator::make([
                'email' => $email,
            ], ['email' => 'email']);

            $this->assertTrue($validator->fails(), "Validation did not fail for: $email");
        };

        $testInvalidEmailFails('test@ gmail.com');
        $testInvalidEmailFails('test @gmail.com');
    }
}
```

**Comment by devcircus** [comment]
Check the docs for the different types of email validates. Also, Laravel uses egulias/email-validate under the hood. Probably best to raise any issues there. 

Actual email RFC guidelines are much more loose than what is used by much of the tech industry. Especially for the local part of the address.

**Comment by OrkhanAlikhanov** [comment]
@devcircus thanks for your reply. Interestingly enough valid emails but with warnings.

https://github.com/egulias/EmailValidator/blob/ca90a3291eee1538cd48ff25163240695bd95448/tests/EmailValidator/Validation/RFCValidationTest.php#L238-L242


From laravel docs:

> #### email
> 
> The field under validation must be formatted as an e-mail address. Under the hood, this validation rule makes use of the [`egulias/email-validator`](https://github.com/egulias/EmailValidator) package for validating the email address. By default the `RFCValidation` validator is applied, but you can apply other validation styles as well:
> 
>     'email' => 'email:rfc,dns'
> 
> The example above will apply the `RFCValidation` and `DNSCheckValidation` validations. Here's a full list of validation styles you can apply:
> 
> - `rfc`: `RFCValidation`
> - `strict`: `NoRFCWarningsValidation`
> - `dns`: `DNSCheckValidation`
> - `spoof`: `SpoofCheckValidation`
> - `filter`: `FilterEmailValidation`
> 
> The `filter` validator, which uses PHP's `filter_var` function under the hood, ships with Laravel and is Laravel's pre-5.8 behavior. The `dns` and `spoof` validators require the PHP `intl` extension.

It seems `'email' => 'email:strict'` would make it work. I'm going to close this. Thanks!

**Comment by OrkhanAlikhanov** [comment]
>Actual email RFC guidelines are much more loose than what is used by much of the tech industry. Especially for the local part of the address.

What do you think, wouldn't it make sense to at least default the email validation to `strict` mode? One of the users actually accidentally put space before `@` sign during registration that's how I noticed this.
