### ISSUE TITLE
How to disable laravel 8 paginator links

### ISSUE THREAD

**Issue by myckhel** [laravel/framework#35239]
- Laravel Version: ^8.0
- PHP Version: ^7

### Steps To Reproduce:
```php
<?php 
Model::paginate();

```
returns 
```json
"links": [
        {
            "url": null,
            "label": "&laquo; Previous",
            "active": false
        },
        {
            "url": "http://127.0.0.1:8000/api/messages?page=1",
            "label": 1,
            "active": true
        },
        {
            "url": "http://127.0.0.1:8000/api/messages?page=2",
            "label": 2,
            "active": false
        },
        ...
    ]
```
these links are useless for me and making my response size bigger.

i have been looking for ways to disable the links by default but i couldnt.

i tried 
```php
Model::simplePaginate()
``` 
but `total` property always returns same value as pageSize

SOS.
Someone rescue me.
thanks.

**Comment by bonzai** [comment]
> This repository is only for reporting bugs.

https://laravel.com/docs/8.x/contributions#support-questions

```php
use Illuminate\Support\Arr;

Arr::except(Model::paginate()->toArray(), 'links')
```

**Comment by taylorotwell** [comment]
Not possible to disable them at this time.

**Comment by rodrigopedra** [comment]
To return just a paginator's items from a JSON endpoint:

~~~php
$records = Model::paginate();

return $records->items();
~~~

Or if you want to keep into the `data` key:

~~~php
$records = Model::paginate();

return ['data' => $records->items()];
~~~

Instead of returning you can also assign it to a variable in both cases.

**Comment by myckhel** [comment]
Thanks you all

I hope very soon laravel will implement the option to disable it.
