### ISSUE TITLE
Duplicate slash (`/`)  when storing files using `putFile` or `putFileAs` given a path with trailing slash (`/`)

### ISSUE THREAD

**Issue by CristianGiordano** [laravel/framework#35245]
- Laravel Version: 6.x / 7.x / 8.x
- PHP Version: All
- Database Driver & Version: N/A

### Description:
When saving files using the storage system (either through an `UploadedFile` or `Storage` facade etc) if the given path to store the file has a trailing slash the returned path has a duplicate slash.

This is more of a developer experience issue as this only happens given a path with a trailing slash. This issue was [raised a while back](https://github.com/laravel/framework/issues/22263), thus my assumption is it doesn't affect many people.

### Steps To Reproduce:

```
class MediaUploadController
{
    public function __invoke(Request $request)
    {
        $file = $request->file('media');

        $path = $file->storeAs('uploads/', 'uploaded-file.mp4');

        dump($path); // --> "uploads//uploaded-file.mp4"
    }
}
```

**Comment by driesvints** [comment]
You are responsible for this, not the filesystem.
