### ISSUE TITLE
IDE and static analysis warn type mismatch when non-array arguments are passed to Collection's zip() method

### ISSUE THREAD

**Issue by wand2016** [laravel/framework#35249]
- Laravel Version: v6.18.10
- PHP Version: 7.4.4
- Database Driver & Version: -

### Description:

<img width="696" alt="スクリーンショット 2020-11-17 23 07 05" src="https://user-images.githubusercontent.com/22491120/99400773-bd866980-292a-11eb-929d-c3081b8b9016.png">

Collection's zip() method should receive 
`array`, `Enumerable`, `Arrayable`, `Jsonable`, `JsonSerializable`, and `Traversable` items.
(see https://github.com/laravel/framework/blob/82ffe3c/src/Illuminate/Support/Traits/EnumeratesValues.php#L827-L844)
When given non-array items, however, IDE and static analysis warn type mismatch.

### Steps To Reproduce:

```php
$xs = collect([1, 2, 3]);
$ys = collect(['a', 'b', 'c']);
$xys = $xs->zip($ys);
```

PhpStorm and Larastan(v12.19) warn type mismatch.

### Note

Laravel 7.x and 8.x have same problem.
(I know bug fixes for 7.x is no longer supported.)

**Comment by taylorotwell** [comment]
The docblock needs to be fixed, not the code.
