### ISSUE TITLE
Wrong $request->url() while running on a sub-path using a Reverse Proxy

### ISSUE THREAD

**Issue by coolsam726** [laravel/framework#35241]
- Laravel Version: 8.14.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql 5.7

### Description:
When running my app in a subpath as `http://mydomain.com/my-app`, `$request->url()` is WRONG since it does not include the base uri (`my-app`). Using `URL::forceRootUrl()` only fixes `\URL::current()` but NOT `$request->url()`. This is only the case when using a Reverse Proxy, and after much investigation I realized the issue lies squarely on the $_SERVER['REQUEST_URI'] parameter.

This behavior in turn affects  the UrlGenerator->hasCorrectSignature() method which is used by several verification features including email verification.

I hope the steps below are clear to reproduce the issue. I have wrestled with it and tried all the dirty tricks I could, but it is still stuck on my team's way. I will really appreciate any help I could get on this.

### Steps To Reproduce:
1. Create a new laravel 8 app and run `php artisan serve` (Port 8000)
2. Create a Reverse Proxy in apache2 virtualhost (My vhost is `https://csm.strathmore.edu/`):
```apacheconfig
<Location "/my-app">
        ProxyPass http://localhost:8000
        ProxyPassReverse http://localhost:8000
</Location>
```
3. In env config, set APP_URL
```dotenv
APP_URL=https://csm.strathmore.edu/my-app
```
4. In AppServiceProvider's boot method, force the root Url as follows:
```php
    public function boot()
    {
        \URL::forceRootUrl(config('app.url'));
    }
```
5. in your WelcomeController->welcome() controller, dd the following and see the results:
```php
    public function welcome(Request  $request) {
        dd(\URL::current());
        return view('welcome');
    }
```
Output:
![image](https://user-images.githubusercontent.com/5610289/99369869-05c36e80-28ce-11eb-9d4c-3350593f6627.png)

```php
    public function welcome(Request  $request) {
        dd($request->url());
        return view('welcome');
    }
```
Output:
![image](https://user-images.githubusercontent.com/5610289/99369997-32778600-28ce-11eb-94eb-cfb90146deec.png)

```php
    public function welcome(Request  $request) {
        dd($request->server->get('REQUEST_URI'));
        return view('welcome');
    }
```
Output:
![image](https://user-images.githubusercontent.com/5610289/99370911-538ca680-28cf-11eb-9be3-d3c622f034bd.png)

**Comment by rodrigopedra** [comment]
Per its docs, Laravel does not support serving an app from a subfolder.

> You should not attempt to serve a Laravel application out of a subdirectory of the "web directory"

Reference: https://laravel.com/docs/8.x#directory-configuration

For example when you cache your routes (which the `optimize` command does under the hood), Laravel does some optimizations that breaks serving an app from a subfolder. This could be one reason why your app ceases to work after running that command.

To revert route caching, you can run: 

~~~bash
$ php artisan optimize:clear
~~~

Or remove all `.php` files from your project's `./bootstrap/cache/` folder.

There are many closed issues relating similar problems when serving a Laravel app from a subfolder and the official instance is that this kind of setup is not supported.

Some related issues from a search on Laravel's GitHub issues tracker:

https://github.com/laravel/framework/issues/32236

https://github.com/laravel/framework/issues/32082

https://github.com/laravel/framework/issues/32832

https://github.com/laravel/framework/issues/34362

https://github.com/laravel/framework/issues/34977

**Comment by coolsam726** [comment]
> Per its docs, Laravel does not support serving an app from a subfolder.
> 
> > You should not attempt to serve a Laravel application out of a subdirectory of the "web directory"
> 
> Reference: https://laravel.com/docs/8.x#directory-configuration
> 
> For example when you cache your routes (which the `optimize` command does under the hood), Laravel does some optimizations that breaks serving an app from a subfolder. This could be one reason why your app ceases to work after running that command.
> 
> To revert route caching, you can run:
> 
> ```shell
> $ php artisan optimize:clear
> ```
> 
> Or remove all `.php` files from your project's `./bootstrap/cache/` folder.
> 
> There are many closed issues relating similar problems when serving a Laravel app from a subfolder and the official instance is that this kind of setup is not supported.
> 
> Some related issues from a search on Laravel's GitHub issues tracker:
> 
> #32236
> 
> #32082
> 
> #32832
> 
> #34362
> 
> #34977

Dear @rodrigopedra ,
Thank you for those insights, but I thought the documentation is talking about serving the laravel app inside a sub-directory of the web-root, for example placing it under `/var/www/html`? If that is the case, I don't have an issue with it at all. In fact, I don't have an issue with the file system at all. By `subdirectory` what I meant configuring the server so that the app is served under a path of the root domain, i.e `https://mydomain.ext/my-app` instead of `https://mydomain.ext` which is the base domain. 

Let me check the issues you have referenced above to see if they are related.

**Comment by rodrigopedra** [comment]
Hi @coolsam726 

My comment about route caching was meant to illustrate one aspect of the framework that could break when serving from a subdirectory. As the official instance is to not support this setup, I expect other parts in the framework to not behave as expected due to this approach. Specially URL related ones.

If you read the related issues you will see people have varying degrees of problems/success when serving from a subdirectory reporting different issues.

I understand having a subdirectory in the URL and having a proper configuration on your webserver are different things, many of those issues' respondents pointed that out. Also I know it is possible to have a proper configuration to use a setup like that properly secured.

But unfortunately the official instance from the framework's maintainers it that issues related to serving an app using a base subdirectory is not supported, which means that issues related to such setup won't be considered as a bug.

I apologize if my first answer wasn't clear enough (not a native English speaker here), hope this one makes it more clear.

**Comment by coolsam726** [comment]
@rodrigopedra ,
This is clear and understood. Thanks for taking the time to help out. I guess I will have to find a workaround since I develop for an institution whose policy is to run most of the apps under a sub-directory.

Thanks again.

**Comment by rodrigopedra** [comment]
You're welcome, have a nice day =)

**Comment by madalinignisca** [comment]
@coolsam726 serving from a subdirectory can be helped out using [Alias](https://httpd.apache.org/docs/2.4/mod/mod_alias.html) and full path, also setting APP_URL to full url including base path.

Works not only for Laravel, but other frameworks with same explanation can't work from subdirectory.

I serve like this multiple development branches for the team on a lock by subdomain dev and test project, as I can add as many aliases I want to Apache's config.

**Comment by divoto** [comment]
Does anyone found a workaround for this????

**Comment by Roronoa97** [comment]
![custom checking signature](https://user-images.githubusercontent.com/63334875/160365727-ecddc5b4-b4c7-4f4f-a787-c77d179c77fc.PNG)

Hope this help, I'm just copying the syntax from  hasCorrectSignature() in UrlGenerator.php and implements it in my controller. I use route('name') to get full url. Already tested it on project serve in subdomain.

If there is better option, please teach me..Thanks

**Comment by divoto** [comment]
For everyone having the same issue, $request->url() is not correct when server from sub-directory and behind the reverse proxy there is a very easy solution, this also correct error on signing Urls with laravel.
On your apache configuration or (nginx), also on .httaccess is required to set **X-Forwarded-Prefix "/subdirectory"** and with correct settings to TrustedProxy everything will work.
