### ISSUE TITLE
Laravel route locale middleware not working with model binding

### ISSUE THREAD

**Issue by Dronax** [laravel/framework#35247]
- Laravel Version: 8.12.3
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7

### Description:

I use this guide: https://mydnic.be/post/how-to-build-an-efficient-and-seo-friendly-multilingual-architecture-in-laravel-v2

I have these routes and middleware:

    $locale = request()->segment(1);

    Route::middleware('localized')->prefix($locale)->group(function() {
         Route::get('/contacts', 'ContactController@index');
         Route::get('/page/{page}', 'PageController@index');
    });

And middleware localized from Kernel.php -> routeMiddleware:

    public function handle(Request $request, Closure $next)
    {
        if (!array_key_exists($request->segment(1), config('translatable.locales'))) {
            $segments = $request->segments();

            $segments = Arr::prepend($segments, config('app.fallback_locale'));

            if($request->session()->has('language')) {
                $segments[0] = session('language');
            }

            return redirect()->to(implode('/', $segments));
        }
        
        return $next($request);
    }
 
When I access to: site.test/contacts he redirect me on locale: site.com/en/contacts
When I access to  site.test/page/test I got 404 not found, If I access to: site.com/en/page/test then page working. Problem with redirect on locale with route model binding.

In Controller Page I have:

    public function index(Page $page) 
    {
        return view('page', compact('page'));
    }

In translatable.php:

    'locales' => [
        'de' => 'Deutsch',
        'en' => 'English',
    ],

In AppServiceProvider:

    public function boot()
    {
        if(array_key_exists(request()->segment(1), config('translatable.locales'))) {
            app()->setLocale(request()->segment(1));
        }
    }

**Comment by driesvints** [comment]
You can't use the request global in a routes file.
