### ISSUE TITLE
Error compile blade with component defined in other package

### ISSUE THREAD

**Issue by WimDeMeester** [laravel/framework#35252]
- Laravel Version: 8.14.0
- PHP Version: 7.4.12
- Database Driver & Version: Not applicable

### Description:

I have a blade file where I use a component that is defined in another package.  The blade file looks like this:

```
<x-media-library-attachment />
```

The component is shown correctly in my application, but when I try to manually compile my blade file in the following way:

```
$fs    =    new \Illuminate\Filesystem\Filesystem();
$compiler = new \Illuminate\View\Compilers\BladeCompiler($fs, 'test');
$contents = $compiler->compileString($fs->get('./resources/views/layout/test/test.blade.php'));
```

, I get the following error

```
InvalidArgumentException with message 'Unable to locate a class or view for component [media-library-attachment].'
```

Do I use the compileString method in a wrong way?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
