### ISSUE TITLE
artisan down --secret

### ISSUE THREAD

**Issue by lindsay-twoblacksheep** [laravel/framework#35253]
- Laravel Version: 8.14.0
- PHP Version: 7.3.16
- Database Driver & Version: n/a

### Description:
I run the command php artisan down--secret="cbb13ad7-6656-4334-a793-9259f762beb1" when navigating to the site using the token, I get a 404 Not Found error

### Steps To Reproduce:

- Create a project using the composer create-project --prefer-dist laravel/laravel <project name> cmd 
- cd into project
- php artisan serve
- php artisan down --secret="cbb13ad7-6656-4334-a793-9259f762beb1"
- navigate to http://localhost:8000/cbb13ad7-6656-4334-a793-9259f762beb1

**Comment by taylorotwell** [comment]
Followed steps. Worked fine for me.
