### ISSUE TITLE
Wrong table name is returned by qualifyColumn in query

### ISSUE THREAD

**Issue by Brenneisen** [laravel/framework#35265]
- Laravel Version: 8.15.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8

### Description:

Since this this commit: 5d57908 it is no longer possible to correctly qualify the model field in a query like this:

```
$user->load(['posts' => function ($query) use ($values) {
    $query->whereIn($query->qualifyColumn('hash'), $values); // qualifyColumn should return "post" instead of "user_has_post"
}]);
```

**Comment by ddzobov** [comment]
Which table name you expecting in result of this method?

**Comment by Brenneisen** [comment]
Hi @ddzobov,

If I add more scopes they will also be executed on the model `post`:

```
$user->load(['posts' => function ($query) use ($values) {
    $query->visible()->premium()->whereIn($query->qualifyColumn('hash'), $values); // qualifyColumn should return "post" instead of "user_has_post"
}]);
```

If I want to use the pivot model I can use `wherePivot` or `wherePivotIn`.

**Comment by ddzobov** [comment]
Why not to use it like this?

```
$user->load(['posts' => function ($query) use ($values) {
    $query->visible()->premium()->whereIn('hash', $values); // qualifyColumn should return "post" instead of "user_has_post"
}]);
```

My opinion is - currently you have wrong usage of this method in your project.

But if community will approve this, method in BelongsToMany can me renamed to `qualifyPivotColumn()`

**Comment by Brenneisen** [comment]
Because this field is ambiguous.

**Comment by ddzobov** [comment]
> Because this field is ambiguous.

$user->load(['posts' => function ($query) use ($values) {
    // $query is not instance of Eloquent like Post::query(), this is BelongsToMany relationship here
    $query->visible()->premium()->whereIn('posts.hash', $values)
        ->where($this->qualifyColumn('something'), 123); // user_has_posts.something
}]);

**Comment by Brenneisen** [comment]
You're right! `$query->getRelated()->qualifyColumn(...)` should solve this for me. But I suspect it is a breaking change, as `BelongsToMany` is the first relation with a `qualifyColumn` method. Other relations instead forward this call to the model / builder.

**Comment by ddzobov** [comment]
Other relationships don't have table and pivot model (default or custom) between two models, so you will not have troubles like this.

**Comment by taylorotwell** [comment]
@ddzobov can we get rid of the breaking change by renaming the method to qualifyPivotColumn?

**Comment by ddzobov** [comment]
> @ddzobov can we get rid of the breaking change by renaming the method to qualifyPivotColumn?

Yes, i can do that now but i think that need to rename it back later. What do you think about that?

**Comment by taylorotwell** [comment]
Why do we need to rename it back later?

**Comment by ddzobov** [comment]
> Why do we need to rename it back later?

Personally, i'm expecting to qualify column of current relationship's model. For example, for BelongsTo it will be remote model, but for BelongsToMany it should be Pivot model.

And what about MorphToMany? Which table name will be used in that case?
