### ISSUE TITLE
Invalid signature if the url parameters has ']' or '[' symbols.

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#35269]
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8.0.22

### Description:
Hi all.
I'm facing that the calling `URL::temporarySignedRoute('download', 60, $parameters)` generate invalid signature if the parameters has `[` or `]` symbols. 

### Steps To Reproduce:

```
$parameters = ['operator[menu_category_name]' => 'like'];

$url = URL::temporarySignedRoute('download', now()->addMinutes(5), $parameters);
```

**Comment by taylorotwell** [comment]
This works for me? I copy and paste the URL returned into my browser.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/463230/99551504-8a22f980-2981-11eb-90ac-6bd7949a32b7.png">

**Comment by siarheipashkevich** [comment]
@taylorotwell please add `signed` middleware to your `something` route.

**Comment by siarheipashkevich** [comment]
You should generate signed url and after try make a request to this signed url.

**Comment by taylorotwell** [comment]
Oh whoops lol

**Comment by taylorotwell** [comment]
Hmm it still works for me to hit it in the browser.

**Comment by taylorotwell** [comment]
I suspect your issue has something to do with URL encoding.

**Comment by siarheipashkevich** [comment]
I'm using postman for getting signed url and after getting response I copy this url and paste to browser and get invalid signature at the moment.

**Comment by taylorotwell** [comment]
Share your exact response in Postman.

**Comment by siarheipashkevich** [comment]
![Screenshot from 2020-11-18 19-04-19](https://user-images.githubusercontent.com/7753600/99555030-e95c2a80-29d0-11eb-9ec1-a91e709b5832.png)

**Comment by siarheipashkevich** [comment]
![Screenshot from 2020-11-18 19-05-32](https://user-images.githubusercontent.com/7753600/99555190-16104200-29d1-11eb-8397-57c09a8299c3.png)

**Comment by bbashy** [comment]
Looks like you're trying to encode JSON in the URL?

If you dig into the signed route code, see what query string values your code can see. Probably all messed up from the equals `%5D=`

**Comment by siarheipashkevich** [comment]
As I understand that `temporarySignedRoute` can't convert any json data from post request, am I right?

**Comment by taylorotwell** [comment]
I have no idea. I'm not sure I even understand the question.

**Comment by taylorotwell** [comment]
Maybe try base64 encoding your parameter array JSON string and then base64 decoding it later.

**Comment by siarheipashkevich** [comment]
Hi @taylorotwell the main question of the issue is it ok that the `temporarySignedRoute` method can't correctly convert any data for getting **valid** signed url?

**Comment by TK0423** [comment]
I set up this routes to try to replicate the issue
![image](https://user-images.githubusercontent.com/22331963/100022233-6bb96580-2da8-11eb-87bc-1e6a651cf9ea.png)

returning the url in an array to have it converted to a json
![image](https://user-images.githubusercontent.com/22331963/100023088-f51d6780-2da9-11eb-8e16-d2b860babafd.png)

the url returned is valid and the operator parameter on the request contains the correct data

![image](https://user-images.githubusercontent.com/22331963/100023180-226a1580-2daa-11eb-84de-a4ab4c7dafeb.png)


I created a post route to test it with your payload from a rest client

![image](https://user-images.githubusercontent.com/22331963/100024248-06677380-2dac-11eb-8d53-c8cfa6f5d856.png)

![image](https://user-images.githubusercontent.com/22331963/100024533-9ad1d600-2dac-11eb-8f00-88e9bb6e4bb8.png)

this returns an invalid signature error when accessing the page 
I suspect the error you are having is you are encapsulating your params inside a "params" attribute

I send the payload as this
![image](https://user-images.githubusercontent.com/22331963/100024366-39aa0280-2dac-11eb-93d0-a6b8f13ccf11.png)


if $url is dd, the url can be copy and pasted correctly on the browser, if returned as json, it needs to be decoded first, but it's been generated properly

![image](https://user-images.githubusercontent.com/22331963/100025000-8a6e2b00-2dad-11eb-9638-6d02e83d5ad4.png)



your getDownloadUrl method should look like this, to make it work
![image](https://user-images.githubusercontent.com/22331963/100024919-5d217d00-2dad-11eb-9d4a-0f0d27de4ead.png)

temporarySignedRoute is working properly, unless it should accept objects in get parameters, like the object 
`{
	"params": {
		"team_id": 454,
		"menu_category-name": "%ce%",
		"operator[menu_categoryname]": "like"
	}
}`

**Comment by taylorotwell** [comment]
Closing this for now.

**Comment by kristalis** [comment]
Any guided solution on this, getting invalid signature
