### ISSUE TITLE
Custom theme not used for markdown notifications

### ISSUE THREAD

**Issue by viirre** [laravel/framework#35278]
- Laravel Version: 8.14.0
- PHP Version: 7.4.9
- Database Driver & Version: N/a

### Description:
A "markdown notification" will not apply css from a custom theme (if set in the `mail.php` config). 

This is because of [this commit](https://github.com/laravel/framework/commit/ed4411d310f259f75e95e882b748ba9d76d7cfad) that was merged into 8.14.0. The problem is that during the markdown rendering, the Markdown renderer's `$theme` property has been changed from the custom theme to either the theme explicitly set on the notification's MailMessage class (via `$mailMessage->theme()`)  or `default`. 

The commit above is a fix for #35081 

### Steps To Reproduce:
1. Create a new Laravel installation
2. Publish mailable views: `php artisan vendor:publish --tag=laravel-mail`
3. Create a new markdown notification: `php artisan make:notification InvoicePaid --markdown=mail.invoice.paid`
4. Create a new theme css file: `views/vendor/mail/html/themes/test.css` with some css that clearly deviates from the default theme
5. Change the `markdown.theme` from `default` to `test` inside `config/mail.php`
6. Render the notification and see that the `test` css is NOT applied

If I change the version in composer.json to 8.13.0, this will work as intended.

**Comment by taylorotwell** [comment]
Fixed in upcoming patch release. Thanks.
