### ISSUE TITLE
Array validation, all items are considered invalid when any of them fails.

### ISSUE THREAD

**Issue by koenhoeijmakers** [laravel/framework#35272]
- Laravel Version: 8.14.0
- PHP Version: PHP 7.4.12

### Description:
When trying to get the `valid` rows from a validator that has array validation (`items.*.`) and one of the rows is `invalid` then every element of the given `items` is considered `invalid`.

### Steps To Reproduce:
This only seems to be the case when validating arrays:
```
$validator = $this->validationFactory->make([
    'items' => [
        ['name' => false],
        ['name' => 'correct'],
    ],
], [
    'items.*.name' => ['string'],
]);

try {
    $validator->validate();
} catch (ValidationException $exception) {
    dd($exception->validator->valid()); // returns []
}
```

This does not seem to be the case when not validating arrays:
```
$validator = $this->validationFactory->make(['name' => true, 'working' => 'yep'], [
    'name' => ['required', 'string'],
    'working' => ['required', 'string'],
]);

try {
    $validator->validate();
} catch (ValidationException $exception) {
    dd($exception->validator->valid()); // returns ['working' => 'yep']
}
```

**Comment by taylorotwell** [comment]
I'm not sure this is really a bug. Just behavior you maybe did not expect?
