### ISSUE TITLE
Laravel Collection keyBy

### ISSUE THREAD

**Issue by upeksha1996** [laravel/framework#35280]
Hi, I was testing the below code in laravel tinker.
```
$c=collect([(object)['id'=>0,'name'=>'asd'],(object)['id'=>1,'name'=>'qwe']]);
$c->keyBy("id")
```
results for the above code is 
```
Illuminate\Support\Collection {#4317
     all: [
       {#4340
         +"id": 0,
         +"name": "asd",
       },
       {#4338
         +"id": 1,
         +"name": "qwe",
       },
     ],
   }
```
When I changed the id of the first element to a non zero value like the below code

```
$c=collect([(object)['id'=>3,'name'=>'asd'],(object)['id'=>1,'name'=>'qwe']]);
$c->keyBy("id")
```

It gives the intended results as below
```
Illuminate\Support\Collection {#4340
     all: [
       3 => {#4341
         +"id": 3,
         +"name": "asd",
       },
       1 => {#4339
         +"id": 1,
         +"name": "qwe",
       },
     ],
   }
```

Is there is a way to get a result like below when there is an element with value zero in laravel collection?
```
Illuminate\Support\Collection {#4340
     all: [
       0 => {#4341
         +"id": 0,
         +"name": "asd",
       },
       1 => {#4339
         +"id": 1,
         +"name": "qwe",
       },
     ],
   }
```

_Originally posted by @upeksha1996 in https://github.com/laravel/framework/discussions/35279_

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by upeksha1996** [comment]
@driesvints I asked it in the discussion but I anyway posted it as a bug since it was not mentioned in the documentation that keyBy cannot be used with zero as a key.

**Comment by monteduro** [comment]
found any solution?
