### ISSUE TITLE
Unable to run queue:clear in production

### ISSUE THREAD

**Issue by alexbowers** [laravel/framework#35286]
- Laravel Version: 8.9.0
- PHP Version: 7.4
- Database Driver & Version: -
- Using: Laravel Vapor

### Description:
When running a `vapor command production` to `queue:clear --queue=<name> --force` I get the error: `The "--force" option does not exist.`

**Comment by driesvints** [comment]
It this is vapor specific please send an support ticket to Vapor support.

**Comment by alexbowers** [comment]
@driesvints Its a general issue, if you run `php artisan queue:clear --force --queue=a` in any project (including locally, it will say `--force option does not exist`

However, to run it in a production environment, ConfirmableTrait requires a `--force` option.

**Comment by driesvints** [comment]
Hmm you're right, that's bizar. Gonna try to look into this later.

**Comment by driesvints** [comment]
This seems to be fixed in the latest version.

**Comment by alexbowers** [comment]
Confirmed, sorry I thought I had updated before testing it again, but all I
did was a redeploy to vapor which used my lock file. My bad.

**Comment by driesvints** [comment]
No worries 👍
