### ISSUE TITLE
isGuarded method is working unexpectedly(?)

### ISSUE THREAD

**Issue by kevinp1005** [laravel/framework#35297]
I am extending a User model from a package with` $guarded` property, and it returns null on all columns, but if i use `$fillable` property it works.

``` php 

class User extend ERPUser {
 ...
}


// with  protected $guarded = ['id']; on ERPUser Model
 $u = User::create([
            'name'=>'testing99',
            'email'=>'testing99@gmail.com',
            'password'=>Hash::make('demo213')
]);
// this will return null on all columns


// with protected $fillable = ['name','email'];  on ERPUser Model
 $u = User::create([
            'name'=>'testing99',
            'email'=>'testing99@gmail.com',
            'password'=>Hash::make('demo213')
]);

// this works!

```

I was trying to find what causes it, and i found this, but i'm not sure if this is the expected behaviour.

![Screen Shot 2020-11-20 at 12 42 44](https://user-images.githubusercontent.com/25806608/99759682-e591ea80-2b2d-11eb-9af0-e84fc818628a.png)

![Screen Shot 2020-11-20 at 12 47 44](https://user-images.githubusercontent.com/25806608/99760393-98624880-2b2e-11eb-9269-f6e797060ed0.png)
 
When i try to remove `isGuardableColumn` in the `isGuarded` condition, it works, or if I set it to 
`$this->isGuardableColumn($key)` instead of `!$this->isGuardableColumn($key)`

I am not sure why `!$this->isGuardableColumn($key)` means "isGuarded" , is this expected ?

**Comment by ttlmm** [comment]
i have the same question! 

trait GuardsAttributes

/**
     * Determine if the given key is guarded.
     *
     * @param  string  $key
     * @return bool
     */
    public function isGuarded($key)
    {
        if (empty($this->getGuarded())) {
            return false;
        }

        return $this->getGuarded() == ['*'] ||
               ! empty(preg_grep('/^'.preg_quote($key).'$/i', $this->getGuarded())) ||
               ! $this->isGuardableColumn($key);
    }

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
