### ISSUE TITLE
Cannot make resource from --resource

### ISSUE THREAD

**Issue by wisnugufad** [laravel/framework#35298]
- Laravel Version: 4.0.4
- PHP Version: 7.4.10
- Database Driver & Version:

### Description:
I'm new in laravel, in order to make controller and resource I use command PHP artisan make:controller UserController --resource

but, it just generate controller not with the resource.
![image](https://user-images.githubusercontent.com/37105643/99773777-82a94f00-2b3f-11eb-94a8-23d691ae07bb.png)

**Comment by idsulik** [comment]
The make:controller {name} --resource makes Resource Controller, not json resource(app/Http/Resources) and controller  

https://laravel.com/docs/8.x/controllers#resource-controllers

**Comment by wisnugufad** [comment]
> The make:controller {name} --resource makes Resource Controller, not json resource(app/Http/Resources) and controller
> 
> https://laravel.com/docs/8.x/controllers#resource-controllers

is the folder app/Http/Resources is still empty. but if I run the command separately like make:resource it work to make resource
