### ISSUE TITLE
Model Deleting Event Closure is not triggering when ->save() is called.

### ISSUE THREAD

**Issue by skeeith** [laravel/framework#35292]
- Laravel Version: 8.13.0
- PHP Version: 7.4.11
- Database Driver & Version: PHP PDO & MySQL 5.7.32

### Description:
When doing an update on a model you'll use ->save() method to update it.

so I have this code on my UserController@update method

```
$user = $this->user->findOrFail($id);
$user->fill($request->all());
$user->save();
```

I have this on my User Model
```
/**
 * The "booted" method of the model.
 *
 * @return void
 */
protected static function booted()
{
    static::updating(function ($user) {
        # Some code here setting default values when updating
        $user->name = 'Test Name';
    });
}
```

### Steps To Reproduce:
1. Create new fresh laravel app using `laravel new project-name` command
2. Create a UserController by running `php artisan make:controller UserController --resource` and then register it on your router
3. Then add the booted code to your `User` Model.
4. Try setting your default name value on the `static::updating` method.
4. Then try updating a single model and checked on the value if it reflected.

### Other Details
`static::creating` is being triggered fine, but `static::updating` is not

**Comment by khalilst** [comment]
@skeeith I've tried your code and it is working fine without any problem.
After calling the `save()` method for update, the `user->name` is `Test Name`. 
Also the issue's title and description aren't same! (title says `deleting` not working and in the description you're talking about `updating`).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by skeeith** [comment]
@khalilst thanks for verifying this man, it looks just specific to my project, also the model is not actually `User` but a different one. I created a new v8 project and it does work fine, maybe there's just something wrong with my project. good to know you verified it.

Thanks!

**Comment by skeeith** [comment]
@driesvints I found the issue when updating a certain Model and it didn't have any changes (which is expected behavior for me) on the fields, the Model::updating event isn't being triggered. it's being triggered ONLY WHEN there's really a change on a single field.

The problem here is when you're dealing with <input type="checkbox"> or probably radio types (I haven't tried it on radio) when you tick off/turn off/unchecked an input checkbox it doesn't send a key: value pair on the request BUT this should be considered as off behavior.

```
This is ON
checkbox_field_name: 'on',
...other fields
```

```
This is OFF
...other fields
```

Now, whether there aren't any changes, the Model::updating event SHOULD TRIGGER but the problem is it doesn't.
