### ISSUE TITLE
Illuminate\Database\PDO\MySqlDriver depends on package doctrine/dbal listed in require-dev

### ISSUE THREAD

**Issue by undefinedor** [laravel/framework#35302]
- Laravel Version: 8.15.0

### Description:
`Illuminate\Database\PDO\MySqlDriver` depends on package doctrine/dbal listed in require-dev.

After `composer install --no-dev` ,  class `Doctrine\DBAL\Driver\AbstractMySQLDriver` is not found .

```
<?php

namespace Illuminate\Database\PDO;

use Doctrine\DBAL\Driver\AbstractMySQLDriver; // this class
use Illuminate\Database\PDO\Concerns\ConnectsToDatabase;

class MySqlDriver extends AbstractMySQLDriver
{
    use ConnectsToDatabase;
}
```

**Comment by driesvints** [comment]
That's because the dependency is in `suggest` and not needed for every component. You need to explicitely require it: https://github.com/laravel/framework/blob/8.x/composer.json#L132
