### ISSUE TITLE
Route caching issues

### ISSUE THREAD

**Issue by deviouspk** [laravel/framework#35325]
- Laravel Version: 8.15
- PHP Version: 7.4
- Database Driver & Version: mysql - mariadb 11

### Description:

Route caching only caches application routes and not the ones from external packages for example telescope or horizon routes are not cached. 
This happened to me when updating to L8.

### Steps To Reproduce:
I didnt try it with an empty default laravel app but should be the same.
- Clone a default laravel application 
-install a package that has routes (e.g. telescope)
- Check telescope works myapp.com/telescope
- run php artisan route:cache
- myapp.com/telescope will throw a 404

**Comment by taylorotwell** [comment]
Telescope works fine for me with routes cached.

**Comment by therecluse26** [comment]
The same issue happens for me on Laravel 8, running route:cache twice resolves the issue, for some reason. This caused a customer outage when we discovered it. We ran php artisan route:cache during a production deploy, and all of our users started getting 404s on all routes. Running it twice (or clearing the route cache) resolved the issue.
