### ISSUE TITLE
Cache::many with MemcachedStore throws exception because of array_combine

### ISSUE THREAD

**Issue by WarcraftLogs** [laravel/framework#35324]
- Laravel Version: 8.15.0
- PHP Version: 7.4.11

### Description:

When invoking Cache::many() with an array of keys where only a subset of the keys are hits, an exception is occurring because of an element count mismatch using array_combine.

ErrorException: array_combine(): Both parameters should have an equal number of elements
#75 /vendor/laravel/framework/src/Illuminate/Cache/MemcachedStore.php(92): Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
#74 [internal](0): array_combine
#73 /vendor/laravel/framework/src/Illuminate/Cache/MemcachedStore.php(92): Illuminate\Cache\MemcachedStore::many
#72 /vendor/laravel/framework/src/Illuminate/Cache/Repository.php(125): Illuminate\Cache\Repository::many
#71 /vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(396): Illuminate\Cache\CacheManager::__call
#70 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Support\Facades\Facade::__callStatic

### Steps To Reproduce:
Use the Memcached store and invoke Cache::many with a set of keys where some are in the cache and some are not.

**Comment by taylorotwell** [comment]
Unable to recreate this:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/463230/99995066-83c8bf00-2d7f-11eb-847b-b311085e2f29.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/463230/99995073-85928280-2d7f-11eb-8780-91da542a5514.png">

**Comment by WarcraftLogs** [comment]
I'll dig into it and try to get a better example, since it must be more specific than I thought. It's a real-world exception that I'm hitting though so I know it's there. 👍
