### ISSUE TITLE
Cannot logout with OAuth2 and session driver Redis.

### ISSUE THREAD

**Issue by jordiepasman** [laravel/framework#35328]
- Laravel Version: 8.15
- PHP Version: 7.4
- Database Driver & Version:

### Description:
We use passport with OAuth2 to get the access token. We use Redis as our session driver. Only when I log out I cannot delete the session. Which keeps me logged in. 

Get the same result with session driver file.
Only if I set session driver to database I can logout with:

```        
        auth()->user()->sessions()->delete();

        if (auth()->user()->token()->revoke()) {
            return response()->json();
        }
```

### Steps To Reproduce:

1. `SESSION_DRIVER=redis`

2. I tried this but none of these deleted the session.

`auth()->user()->token()->revoke()`
`session()->flush();`
`session()->regenerate();`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
