### ISSUE TITLE
Laravel 8.15 composer update problems

### ISSUE THREAD

**Issue by avenCN** [laravel/framework#35327]
- Laravel Version: 8.15.0
- PHP Version: 7.4.11

### Description:
If use composer update (1.10.17)
show message as some plugin abandoned:

Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested. Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.

If use composer update (2.0.7)
show message as some plugins version back to old:

  - Downgrading brick/math (0.9.1 => 0.8.17)
  - Downgrading filp/whoops (2.9.1 => 2.9.0)
  - Downgrading ramsey/uuid (4.1.1 => 4.1.0)
  - Upgrading sebastian/resource-operations (3.0.3 => dev-master 0f4443c)

**Comment by durianpeople** [comment]
I am currently on composer version 2.0.7, with PHP version 7.4.11 and laravel/framework version 8.15.0. I cannot recreate the results you got, instead I got _fzaninotto/faker is abandoned_ message.

However the package fzaninotto/faker is _actually_ abandoned now, just for information

**Comment by driesvints** [comment]
use `fakerphp/faker` instead
