### ISSUE TITLE
queue:work stopping on failure

### ISSUE THREAD

**Issue by Adizbek** [laravel/framework#35321]
- Laravel Version: 7.28.4
- PHP Version: 7.4.11
- Database Driver & Version: mysql

### Description:
`php artisan queue:work` stopping after  Http client throws exception, as I investigated, `causedByLostConnection` is getting true, but actually queue driver connection has not lost connection, http client couldn't connect. So, I caught error in job and rethrow it with different signature and now `queue:work` is continuing working

### Steps To Reproduce:
Just create a simple job, connect to port which is not serving anything with http client, try with this code, it should fail and exit, and then uncomment commented codes, worker should work as expected without exiting.
```php
    public function handle()
    {
//        try {
            $response = Http::post($this->callback_url, [
                'id' => $this->id,
                'result' => $this->result
            ]);

            if ($response->successful()) {
                $this->entity->update(['delivered' => 1]);
            }
//        } catch (\Exception $e) {
//            throw new \Exception("Server has not returned successful response code");
//        }
    }
```

#### Additional information:
Exception message is
```text
 cURL error 7: Failed to connect to localhost port 5000: Connection refused 
```
I think [this](https://github.com/laravel/framework/blob/740a0faea40920cc1880737fc49580aeb0165150/src/Illuminate/Database/DetectsLostConnections.php#L43) is causing problem.

**Comment by paras-malhotra** [comment]
Hmm looks like a genuine bug. This line is causing the worker to stop: https://github.com/laravel/framework/blob/56f79e2b6e4ee99b26be0c5c73d57cd3a3974fd1/src/Illuminate/Queue/Worker.php#L339

**Comment by paras-malhotra** [comment]
Submitted a PR (https://github.com/laravel/framework/pull/35323) to fix this

**Comment by taylorotwell** [comment]
PR merged.
