### ISSUE TITLE
Artisan make:component with dot notation creates a faulty folder and class structure.

### ISSUE THREAD

**Issue by GustavoFenilli** [laravel/framework#35337]
- Laravel Version: 8.12
- PHP Version: 7.4

### Description:
When creating a new component using dot notation and the artisan command using the example layout.skeleton, it creates the views correctly inside: views/components/layout/skeleton.blade.php, but it does not create correctly the php class and its folder structure, making it as: View/Components/layout.skeleton.php, having inside a class like: 

```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class layout.skeleton extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.layout.skeleton');
    }
}
```

### Steps To Reproduce:

Run php artisan make:component layout.skeleton

**Comment by driesvints** [comment]
Dot notation isn't supported and I saw that we don't document yet how to create components in sub directories. I've just sent in a PR to the docs for that: https://github.com/laravel/docs/pull/6586

You probably need:

```bash
php artisan make:component Layout/Skeleton
```
