### ISSUE TITLE
Auth::logoutOtherDevices() requires a double login submission...

### ISSUE THREAD

**Issue by alturic** [laravel/framework#35334]
- Laravel Version: 8.15.0 (no jestream, fortify, etc)
- PHP Version: 7.3.3
- Database Driver & Version: MySQL 5.8

### Description:
On my login action, I call `auth()->attempt(...);`, then `auth()->logoutOtherDevices(...);` and finally `return redirect()->route('dashboard');` and everything works great. However, if I logout, I have to submit my login twice before it actually logs me in.

### Steps To Reproduce:
I have 3 routes

```
Route::get('/', DashboardIndexAction::class)->name('dashboard');

Route::post('/logout', LogoutAction::class)->name('logout');

Route::get('/login', LoginAction::class)->name('login');
Route::post('/login', LoginSubmitAction::class);
```

As I mentioned above, in my login controller I call the auth attempt, on a successfully login I call the logoutOtherDevices, and then I redirect to the dashboard route. On my logout controller I simply call `auth()->logout();` and then `return redirect()->route('login');`. However, if I do logout, as I said it redirects me to my login route, but if I try to login again, upon the first form submission it simply redirects me back to the login page. On the second submission it actually logs in. That first form submission after a logout POSTs to /login, which redirects me via GET to /, and that 302's to /login again making me think the login was successful (of course it was, my credentials were correct), but the GET to / seems to run AuthenticateSession (or some other core middleware) which then redirects back to /login...

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by alturic** [comment]
I've been talking to some fellow users on larachat's Slack for the past 2 hours trying to figure out what could be causing this. :)

**Comment by driesvints** [comment]
@alturic can you create a fresh laravel repo with the minimum amount of code needed to reproduce this? Please commit custom code separate from the base laravel installation.

**Comment by alturic** [comment]
I mean, I could but I would spend more time doing all of that than you would simply making two controllers with these 7 lines of code:

Logout action/route via POST
```
auth()->logout();

return redirect()->route('login');
```

and a login action/route via POST

```
if (!auth()->attempt($request->only('email', 'password'), $request->remember)) {
      return back();
}

auth()->logoutOtherDevices($request->post('password'));

return redirect()->route('home');
```

And of course uncommenting AuthenticateSession::class in Kernel.php.

If you wouldn't help without me making a repo, you can keep the ticket closed. Those two snippets of code (outside of the form view) is literally all the code needed to reproduce. :)

**Comment by alturic** [comment]
For anyone else that may run into this, I appear to have fixed it on my logout controller by doing the following.

Current, making me submit a login form twice after logout:
```
        auth()->logout();

        return redirect()->route('login');
```

Updated logout action, which doesn't require a double form submit now:
```
        auth()->logout();
        $request->session()->invalidate();

        $request->session()->regenerateToken();
        return redirect()->route('login');
```
