### ISSUE TITLE
Blade syntax escaping htmlspecialchars

### ISSUE THREAD

**Issue by alddesign** [laravel/framework#35347]
- Laravel Version: 5.5.50
- PHP Version: 7.3.23
- Database Driver & Version: SQLite3

### Description:
Hey guys i am using code view, cause otherwise this will be displayed the wrong way... and thats the spirit...
```
When creating view templates with blade syntax the escaping doesnt seem to work the right way:
{{ "&lt;" }} should be converted to "&amp;lt;" (the "&" ist the special char and should be converted to "&amp;".
Instead it stays "&lt;". ( Although PHPs htmlspecialchars("&lt;") would return "&amp;lt;")

{{ "<" }} alone results in "&lt;" whicht is fin IMHO. Same with {{ "&" }} resulting in "&amp;"
```

### Steps To Reproduce:
-Create a view that calls a blade layout
-Content of the blade layout;
```
{{ "&lt;" }}
{{ "<" }}
{{ "&amp;" }}
{{ "&" }}
```
-Open the view in your browser to check the results. Imho the correct results for each line should be:
```
1: "&amp;lt;"
2: "&lt;"
3: "&amp;amp;"
4: "&amp;"
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by alddesign** [comment]
Ah nut. My bad. 
I will try with laravel 7/8 versions.

**Comment by alddesign** [comment]
Works correctly in current 7.x and 8.x releases.
