### ISSUE TITLE
Try to get data from morph table

### ISSUE THREAD

**Issue by abuamr-gafurov** [laravel/framework#35341]
- Laravel Version: 7.18.0
- PHP Version: 7.3.22
- Database Driver & Version: MySQL 5.7

### Description:
I try to get favorite data from favorites morph table and get error:
**Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous** 

### Steps To Reproduce:
```
$client = Client::findOrFail($request->client_id);
$client->getFavoriteItems('App\Models\Vendor')->get();
```

```
public function getFavoriteItems(string $model)
{
	return app($model)->whereHas('favoriters', function ($query) {
		return $query->where('client_id', $this->getKey());
	});
}
```
### SQL:
and **getFavoriteItems** function return:
```
SELECT
	*
FROM
	`vendors`
WHERE
	EXISTS (
		SELECT
			*
		FROM
			`clients`
			INNER JOIN `favorites` ON `clients`.`id` = `favorites`.`client_id`
		WHERE
			`vendors`.`id` = `favorites`.`favoriteable_id`
			AND `client_id` = 1
			AND `favoriteable_type` = 'App\\Models\\Vendor'
			AND `clients`.`deleted_at` IS NULL
		ORDER BY
			`id` DESC)
		AND `vendors`.`deleted_at` IS NULL
	ORDER BY
		`id` DESC;
```

correct sql looks like this (this is hard code)
```
SELECT
	*
FROM
	`vendors`
WHERE
	EXISTS (
		SELECT
			*
		FROM
			`clients`
			INNER JOIN `favorites` ON `clients`.`id` = `favorites`.`client_id`
		WHERE
			`vendors`.`id` = `favorites`.`favoriteable_id`
			AND `client_id` = 1
			AND `favoriteable_type` = 'App\\Models\\Vendor'
			AND `clients`.`deleted_at` IS NULL
		ORDER BY
			`clients`.`id` DESC)
		AND `vendors`.`deleted_at` IS NULL
	ORDER BY
		`id` DESC;
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
