### ISSUE TITLE
Class from controllers not working in x-dynamic-component

### ISSUE THREAD

**Issue by anantgrafix** [laravel/framework#35351]
- Laravel Version: ^8.12

### Description:
`<x-dynamic-component :component="$component->path" class="{{ $component->class }}" />`
component is rendering view but class is not working

even `:class="$component->class"` as dynamic property gives error

in both cases Error is
Undefined property: Illuminate\View\DynamicComponent::$class (View: C:\xampp\htdocs\laravel\resources\views\test.blade.php)

**Comment by anantgrafix** [comment]
<x-{{ $dynamic-component-name }} :type="$type class="p-4" />

This will be convenient if possible.

**Comment by taylorotwell** [comment]
$component is a reserved variable there. Use something else.
