### ISSUE TITLE
getDirty not casting attribute value

### ISSUE THREAD

**Issue by Braunson** [laravel/framework#35350]
- Laravel Version: 8.16.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 5.7.32

### Description:
Looks like the `getDirty` method in `HasAttributes.php` is returning the proper dirty variable however it's not casting it at all.

### Steps To Reproduce:

Recreated in the Laravel Playground
https://laravelplayground.com/#/snippets/19351b59-0a95-49d7-b531-bc2a242b77d2

**Comment by taylorotwell** [comment]
🤷  ... we wouldn't change it now as it would be a breaking change. Isn't getDirty() the same as just saying $model->created_at after you have changed it?

**Comment by taylorotwell** [comment]
For what it's worth, you can add your own method to a base model class that works around this and does something like the following:

```php
return (new static)->setRawAttributes($this->getDirty(), true)->getOriginal();
```

**Comment by Braunson** [comment]
@taylorotwell Thanks, I didn't mean to write the original description up as a "bug" but more an idea. I can see it both ways where `getOriginal()` should be the opposite of `getDirty()`, but also can see why it's currently setup as it is (dirtying being the untouched changed data).

Thanks for the workaround!
