### ISSUE TITLE
Accept header is not properly parsed

### ISSUE THREAD

**Issue by puckipedia** [laravel/framework#35353]
https://github.com/laravel/framework/blob/43bea00fd27c76c01fd009e46725a54885f4d2a5/src/Illuminate/Http/Concerns/InteractsWithContentTypes.php#L56

The code currently seems to assume that an Accept header starting with a mime type that contains `/json` or `+json` means that the request should be responded to with JSON. This is incorrect and dangerous; as it doesn't check the exact subtype of the MIME type. As an example, requesting `application/{foobarbaz}+json` will return any arbitrary JSON response if the server implements JSON responses at all, even if that could cause confused deputy attacks. Simultaneously, it doesn't look at the `q=` parameter, meaning that a request cannot set a priority for any output format relative to any other output format.

My suggestion would be to swap this out with a proper parser, like `Symfony\Component\HttpFoundation\AcceptHeader`, as suggested by https://symfony.com/doc/current/components/http_foundation.html#accessing-accept-headers-data

**Comment by taylorotwell** [comment]
Unclear what action we are supposed to take from this that isn't a major breaking change.

**Comment by taylorotwell** [comment]
Also need a clearer example of why this is "dangerous".
