### ISSUE TITLE
ThrottleRequests:api does not exist

### ISSUE THREAD

**Issue by dejury** [laravel/framework#35359]
- Laravel Version: 8.16.0
- PHP Version: 7.4.12

### Description:
When upgrading to Laravel 8.16.0 from 8.15.0, I'm getting this error when running tests:
`ReflectionException 

  Class Illuminate\Routing\Middleware\ThrottleRequests:api does not exist

  at vendor/laravel/framework/src/Illuminate/Routing/Router.php:718
`

I see there is something changed in that part of code in the new version, but I can't seem to see what causes the issue, so I did not (yet) generate a pull request.

**Comment by dejury** [comment]
Well, #35358 was created at the same time, but I am sure this is related.

**Comment by muhajirinlpu** [comment]
yeah, it is really related :smile:

**Comment by mstaack** [comment]
same issue here on my side!

**Comment by robtesch** [comment]
Same here. For what it's worth, it seems to only be affecting routes where I have:

```->withoutMiddleware(['someMiddleware'])```

and when I remove that the routes seem to work.

Downgrading to v8.15.0 also solves the issue. Good thing I caught this one before deploying!

**Comment by taylorotwell** [comment]
Sorry all. Pushing out a fix now.

**Comment by taylorotwell** [comment]
Released 8.16.1.

**Comment by robtesch** [comment]
Thanks so much as always @taylorotwell

**Comment by dejury** [comment]
Thanks a lot for the quick fix!
