### ISSUE TITLE
ForeignId with constrained and onDelete, onDelete is ignored

### ISSUE THREAD

**Issue by yuyenkan** [laravel/framework#35366]
- Laravel Version: ^8.0
- PHP Version: 7.3
- Database Driver & Version: mysql, 10.3.16-MariaDB

### Description:
foreignId with constrained and onDelete, onDelete is ignored, cascade or set null both cannot

### Steps To Reproduce:
        Schema::create('table', function (Blueprint $table) {
            $table->id();
        });

        Schema::create('table2', function (Blueprint $table) {
            $table->foreignId('table_id')->nullable()->onDelete('set null')->constrained('table');
        });

**Comment by rodrigopedra** [comment]
Try this:

~~~php
Schema::create('table2', function (Blueprint $table) {
    $table->foreignId('table_id')->nullable()->constrained('table')->onDelete('set null');
});
~~~

or even:

~~~php
Schema::create('table2', function (Blueprint $table) {
    $table->foreignId('table_id')->nullable()->constrained('table')->nullOnDelete();
});
~~~

Key here is calling `->onDelete(...)` or `->nullOnDelete()` after calling `->constrained(...)`.

`->foreignId(...) ` returns a `ForeignIdColumnDefinition` which is a convenience class for setting default data type for a foreign id that references a field created with `->id()`  (`BIGINT UNSIGNED`), but id doesn't forward calls or effectively create a foreign id index before either `->constrained(...)` or `->references(...)` is called.

After calling `->constrained(...)` it returns a `ForeignKeyDefinition` instance which then actually knows how to handle the `->onDelete(...)` call.

Hope it helps.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
