### ISSUE TITLE
Queue hangs indefinitely when using a Carbon object for the "backoff"

### ISSUE THREAD

**Issue by browner12** [laravel/framework#35367]
- Laravel Version: 8.16.1
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 8.0.21

### Description:

TBH, not sure if this is a bug, or operating as intended.

The documented way to set a custom "backoff" directly on a Job is either via a property or method:

https://laravel.com/docs/8.x/queues#dealing-with-failed-jobs

```php
/**
 * The number of seconds to wait before retrying the job.
 *
 * @var int
 */
public $backoff = 3;

/**
 * Calculate the number of seconds to wait before retrying the job.
 *
 * @return int
 */
public function backoff()
{
    return 3;
}
```

However, if you dive into the source, you'll see that it also tries to account for instances of `\DateTimeInterface` that are passed to it.

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Queue.php#L178

```php
/**
 * Get the backoff for an object-based queue handler.
 *
 * @param  mixed  $job
 * @return mixed
 */
public function getJobBackoff($job)
{
    if (! method_exists($job, 'backoff') && ! isset($job->backoff)) {
        return;
    }

    return collect($job->backoff ?? $job->backoff())
        ->map(function ($backoff) {
            return $backoff instanceof DateTimeInterface
                ? $this->secondsUntil($backoff) : $backoff;
        })->implode(',');
}
```

Which means, if we are using the `backoff()` method, we should be able to do this:

```php
/**
 * Calculate the number of seconds to wait before retrying the job.
 *
 * @return \Illuminate\Support\Carbon
 */
public function backoff()
{
    return now()->addMinutes(5);
}
```

Some people like to do this so the code is a little more readable. However, this will break the queue, and cause it to sit in "processing" indefinitely.

It looks like this was caused by this commit, which added the ability to do "exponential backoffs".

https://github.com/laravel/framework/commit/e9b892fc4958269279926147ea8979e6547dcd25

Specifically, it is being caused by instantiating a Collection by passing a `Carbon` instance. Because the `Carbon` object is an instance of `\JsonSerializable`, it is hitting this line in the Collection instantiation:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Collections/Traits/EnumeratesValues.php#L887

```php
/**
 * Results array of items from Collection or Arrayable.
 *
 * @param  mixed  $items
 * @return array
 */
protected function getArrayableItems($items)
{
    if (is_array($items)) {
        return $items;
    } elseif ($items instanceof Enumerable) {
        return $items->all();
    } elseif ($items instanceof Arrayable) {
        return $items->toArray();
    } elseif ($items instanceof Jsonable) {
        return json_decode($items->toJson(), true);
    } elseif ($items instanceof JsonSerializable) {
        return (array) $items->jsonSerialize();
    } elseif ($items instanceof Traversable) {
        return iterator_to_array($items);
    }

    return (array) $items;
}
```

I can "solve" this in my application by returning an array from the `backoff()` method:

```php
/**
 * @return array
 */
public function backoff()
{
    return [
        now()->addSeconds(10),
    ];
}
```

But I'd like to solve it in core as well. I think there are 3 options we could take. First, we could account for it at a low level when instantiating a Collection, so essentially:

```php
collect(now());
```

behaved the same as:

```php
collect([now()]);
```

but this would be a **breaking change**, and I'm not sure what the effects of this would be.

Second, we could solve it higher up the chain, and specifically account for it in the `Queue`:

```php
/**
 * Get the backoff for an object-based queue handler.
 *
 * @param  mixed  $job
 * @return mixed
 */
public function getJobBackoff($job)
{
    if (! method_exists($job, 'backoff') && ! isset($job->backoff)) {
        return;
    }

    $methodBackoff = $job->backoff() instanceof DateTimeInterface ? [$job->backoff()] : $job->backoff();

    return collect($job->backoff ?? $methodBackoff)
        ->map(function ($backoff) {
            return $backoff instanceof DateTimeInterface
                ? $this->secondsUntil($backoff) : $backoff;
        })->implode(',');
}
```

Or option 3, we could require people to return an array in their `backoff()` method if they want to use Carbon objects:

```php
/**
 * @return array
 */
public function backoff()
{
    return [
        now()->addSeconds(10),
    ];
}
```

### Steps To Reproduce:

Return a Carbon object from a Job `backoff()` method:

```php
/**
 * @return \Illuminate\Support\Carbon
 */
public function backoff()
{
    return now()->addSeconds(10);
}
```

**Comment by themsaid** [comment]
fixed with https://github.com/laravel/framework/commit/c6f14c6da9c36219455ae66bb853cfbc27d3b24d

**Comment by browner12** [comment]
Great, thanks.
