### ISSUE TITLE
Installing livewire package issue

### ISSUE THREAD

**Issue by YassineChe** [laravel/framework#35360]
- Laravel Version: ^8.12
- PHP Version: ^7.3|^8.0

### Description:

- I'm trying to install livewire but i'm getting this exception
<img width="1109" alt="Screen Shot 2020-11-25 at 11 20 08" src="https://user-images.githubusercontent.com/46085172/100215111-ed2c0780-2f10-11eb-98bf-f62f4ecd46bd.png">

- Log file :

> [2020-11-25 10:19:27] local.ERROR: file_put_contents(): Exclusive locks are not supported for this stream {"exception":"[object] (ErrorException(code: 0): file_put_contents(): Exclusive locks are not supported for this stream at /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/league/flysystem/src/Adapter/Local.php:199)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/Users/youssefa...', 199, Array)
#1 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/league/flysystem/src/Adapter/Local.php(199): file_put_contents('/Users/youssefa...', '<?php\
\
use Illu...', 2)
#2 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/league/flysystem/src/Filesystem.php(99): League\\Flysystem\\Adapter\\Local->update('2014_10_12_2000...', '<?php\
\
use Illu...', Object(League\\Flysystem\\Config))
#3 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/league/flysystem/src/MountManager.php(597): League\\Flysystem\\Filesystem->put('2014_10_12_2000...', '<?php\
\
use Illu...', Object(League\\Flysystem\\Config))
#4 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(249): League\\Flysystem\\MountManager->put('2014_10_12_2000...', '<?php\
\
use Illu...')
#5 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(233): Illuminate\\Foundation\\Console\\VendorPublishCommand->moveManagedFiles(Object(League\\Flysystem\\MountManager))
#6 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(198): Illuminate\\Foundation\\Console\\VendorPublishCommand->publishDirectory('/Users/youssefa...', '/Users/youssefa...')
#7 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(163): Illuminate\\Foundation\\Console\\VendorPublishCommand->publishItem('/Users/youssefa...', '/Users/youssefa...')
#8 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php(76): Illuminate\\Foundation\\Console\\VendorPublishCommand->publishTag('fortify-migrati...')
#9 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\VendorPublishCommand->handle()
#10 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#15 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#16 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#17 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(56): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\NullOutput))
#18 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(40): Illuminate\\Console\\Command->runCommand('vendor:publish', Array, Object(Symfony\\Component\\Console\\Output\\NullOutput))
#19 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/jetstream/src/Console/InstallCommand.php(41): Illuminate\\Console\\Command->callSilent('vendor:publish', Array)
#20 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Jetstream\\Console\\InstallCommand->handle()
#21 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#23 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#26 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Jetstream\\Console\\InstallCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /Users/youssefakchar/.bitnami/stackman/machines/xampp/volumes/root/htdocs/project/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"} 

Im ussig Macos Catalina.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ilkerkocatepe** [comment]
I have same error. I'm using XAMPP on MacOS Big Sur.
Are there any solutions to this?

Best regards

**Comment by YassineChe** [comment]
@ilkerkocatepe 

This because permissions stuff, i'm newbie using MacOS, I haven't reached to solution...
But i solved it by installing MAMP instead XAMP, and i put folders (projects) in Desktop (No permissions required) and everything works fine...

Still looking for a practical solution, i will notify you when i arrive, you either, please!

Best regards.

**Comment by ilkerkocatepe** [comment]
I am also using the same solution for now. Don't worry, if I find a solution, I'll write it here. 
@YassineChe 

Thanks

**Comment by joelbutcher** [comment]
@ilkerkocatepe  @YassineChe Checkout Laravel Valet - make for a beautifully simple and easy-to-use dev PHP, MySQL, Redis environment for macOS on Nginx.

You can also run WordPress... If you REALLY want to

**Comment by YassineChe** [comment]
@joelbutcher, I'm using Laravel Valet as you recommended to me, thank you so much,

@ilkerkocatepe, i recommending you to use Laravel Valet too.

Thanks.
