### ISSUE TITLE
PhpRedis bug stopping TLS encrypted cluster connection

### ISSUE THREAD

**Issue by devsi** [laravel/framework#35368]
- Laravel Version: **6.20.3**
- PHP Version: **7.2.33**
- Database Driver & Version: **Redis 6.x / phpredis 5.3.2**

### Description:
Cannot connect to Clustered Redis instance over TLS in PhpRedis 5.3.2.

This is fixed in Laravel 7+. [See here](https://github.com/laravel/framework/issues/35020), but Laravel 6 still has this problem, needs a work around for Laravel 6.x as `context` doesn't exist as a configuration option. As Laravel 6 supports Redis over TLS and is still supported LTS I suspect it should be fixed in 6.x too.

Redis responds with: `RedisClusterException  : Error processing response from Redis node!`

See the [phpredis issue](https://github.com/phpredis/phpredis/issues/1607) for more context. Fix is described in the last comment.

### Steps To Reproduce:
Set up a TLS connection to a clustered redis. It seems every version of phpredis has the issue, but 5.3.2 introduces a fix. Needs to be reflected in Laravel

**Comment by driesvints** [comment]
I've sent in a PR for this: https://github.com/laravel/framework/pull/35370

While technically Laravel 6 is closed for new features and the new context option in Redis wasn't supported there I believe it would be good if we did. I'm closing this already. Let's see how the PR goes.

Thanks

**Comment by devsi** [comment]
Ah this is amazing thanks. :) I should've made the PR myself, that was rude of me! Thanks for getting that made so quick.
