### ISSUE TITLE
 Method Illuminate\Routing\RouteRegistrar::withoutMiddleware does not exist.

### ISSUE THREAD

**Issue by innoflash** [laravel/framework#35362]
- Laravel Version: 8.x.x
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
Pretty sure this is not the right place to present this but I think the `Route::withoutMiddleware([])->group();` is missing

How else can we go to call `->withoutMiddleware()` on all endpoints in a group.

### Steps To Reproduce:
Create a route group and call `withoutMiddleware` on the group
```php

Route::middleware(['web', 'auth'])
     ->withoutMiddleware(['api', 'auth:api', 'user-active'])
     ->group(function () {
		//todo add routes that needs to remove the middlewares
	});

```

**Comment by taylorotwell** [comment]
This just doesn't exist. Closing as the method doesn't exist and this isn't really a "bug".
