### ISSUE TITLE
Array to string conversion in assertJsonValidationErrors

### ISSUE THREAD

**Issue by djankolija** [laravel/framework#35378]
- Laravel Version: 8.14.0
- PHP Version: 7.14.0
- Database Driver & Version: MySql 5.7

### Description:
When calling `assertJsonValidationErrors` and expecting more than one error for the same key, an array to string conversion is hit. Culprit is `TestResponse: 653` which should probably have `key: '{$key}'` instead of `key:'{$value}'`

### Steps To Reproduce:
1. Run a test and assert json validation errors e.g.:
```
        $response->assertJsonValidationErrors([
            'units' => [
                'The units must be a number.',
                'The units must be greater than 0.'
                ]
        ]);
```

**Comment by driesvints** [comment]
Think you're mis using this a bit. This method doesn't uses validation messages. Try:

```php
$response->assertJsonValidationErrors('units');
```
