### ISSUE TITLE
Faker Lib Deprecated

### ISSUE THREAD

**Issue by myckhel** [laravel/framework#35379]
- Laravel Version: 8
- PHP Version: 8

### Description:
Faker library is deprecated and only faker library preventing laravel installation on php 8
how do we handle this case?

I temporarily removed faker from my `composer.json` in order to get laravel installed but faker is a lib i cant do without.

**Comment by crynobone** [comment]
You can change to `fakerphp/faker`

**Comment by myckhel** [comment]
oh great thank you
