### ISSUE TITLE
Inconsistent related model values inside Events when using Eager loading by default

### ISSUE THREAD

**Issue by filev-svt** [laravel/framework#35372]
- Laravel Version: 8.0.0
- PHP Version: ^7.2.5
- Database Driver & Version: psql, version unknown

### Description:
When using Eloquent events and automatic (default) eager loading the relationships in the events are not reflecting the changes. I am aware this is maybe a vague description, so let's use an example: I have a one-to-many relationship: each Invoice has 1..n Line Items. When a Line Item is deleted/created/edited (note the past tense, the events used are the ones after the event completion, eg. deleted, saved...) the Invoice should have its values recalculated. 

If default eager loading is not used, the recalculation works absolutely fine. If default eager loading via `protected $when` is used, however (eager load the Invoice Line Items automatically), the recalculation is suddenly using the old Line Items values, therefore the Invoice values are always incorrectly recalculated.

My guess is that this is somewhat justified by the logic of eager loading under the hood, so maybe just a **mention in the eager loading documentation** with an exclamation mark would be enough for the developers, unfortunately, for me, it caused quite the significant bug (as you would imagine with invoices) because I expected **consistent behaviour from the events with or without eager loading**. 

### Steps To Reproduce:

1. Have a one-to-many relationship
2. Set default eager loading via `protected $when` trait in the Model
3. Create some event logic for the edited item, which manipulates the related item in the booted function after delete or after save
4. Log the model and related record values from the event

Thanks for the cooperation, will gladly add a real code example if needed :)

**Comment by driesvints** [comment]
Laravel 8 doesn't run on PHP 7.2 so I don't think this is a valid bug report.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks

**Comment by filev-svt** [comment]
The composer.json has a requirement for ^7.2.5 (notice the arrow), the issue was on PHP 7.3.19, but I'll try the other channels I guess... 
Thanks anyway.
