### ISSUE TITLE
Returns 404 on /dashboard 

### ISSUE THREAD

**Issue by connelevalsam** [laravel/framework#35388]
- Laravel Version: Laravel Framework 8.14.0
- PHP Version: PHP 7.4.10 (cli) (built: Sep  1 2020 16:52:39) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
- Database Driver & Version: Xampp v3.2.4 running MariaDB

### Description:
new to Laravel, following a tutorial that uses version 7, saw that a lot of changes where made. Got to the auth part and that's where all hell was loose.
First i did this: `php artisan ui vue`
Then I did: `php artisan ui vue --auth`
ran: `npm install`
and then ran: `npm run dev`
Found out that it didn't display the Login/register on the page and when I tried visiting the route i had `404` error.
Did some reading and discovered `jetstream`.

I now deleted everything that had to do with vue and even the `node_modules`.
I ran: `composer require laravel/jetstream`
did: `php artisan jetstream:install livewire`
ran: `npm install`
did: `php artisan migrate`
and started the server. It didn't display the login/register route but i could access the links. I tried registering a new user but when it redirected me to `/dashboard` it shows `404` error.

**Comment by taylorotwell** [comment]
I would install Jetstream in a fresh project.

**Comment by connelevalsam** [comment]
So what happens to this project?
I should start all over again?

**Comment by driesvints** [comment]
@connelevalsam If you want to install Jetstream in an existing project and you run into issues it's best that you try a support channel. Jetstream is a scaffold tool for new apps.

**Comment by connelevalsam** [comment]
okay can you point me to a support channel?
cos started afresh is tiring!

**Comment by driesvints** [comment]
Here you go:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
