### ISSUE TITLE
Laravel 5.4.36 with php 7.3

### ISSUE THREAD

**Issue by usamaxyz** [laravel/framework#35408]
- Laravel Version: 5.4.36
- PHP Version: 7.3
- Database Driver & Version:

### Description:

compact(): Undefined variable: operator

in Builder.php line 1229

at HandleExceptions->handleError(8, 'compact(): Undefined variable: operator', '[omitted]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php', 1229, array('query' => object(Builder), 'boolean' => 'and', 'not' => false, 'type' => 'Exists'))

at compact('type', 'operator', 'query', 'boolean')in Builder.php line 1229

I checked github comments. This bug is already fixed. But these is no new release 5.4.37.

### Steps To Reproduce:
when executing:
composer update
It's still using laravel 5.4.36 where the bug exist.

Thanks

**Comment by mnabialek** [comment]
This version of Laravel is not supported. You should upgrade to some later version. See https://laravel.com/docs/5.8/releases#support-policy

**Comment by usamaxyz** [comment]
Hi mnabialek, 
updgrading is not that easy. and we are not always ready for. I downgrade php version to 7.1 and every things works fine.
thanks.
