### ISSUE TITLE
image validator doesn't work with jpg

### ISSUE THREAD

**Issue by makroxyz** [laravel/framework#35413]
- Laravel Version: 8.16.1
- PHP Version: 7.4.14
- Database Driver & Version:

### Description:
after composer update, symfony/mime updated to 5.2.0.. then uploading a jpg file the validation rule 'image' doesn't work anymore

### Steps To Reproduce:
```php
 /** @test */
public function upload_logo()
{
        Storage::fake('public');

        $file = UploadedFile::fake()->image('logo.jpg', 150, 30);

        $this->post('/upload'), [
            'logo' => $file,
        ])->assertSessionDoesntHaveErrors();
}
```

controller
```php
public function store(Request $request) 
{
     $request->validate([
         'logo' => 'required|image'
     ]);
}
```

**Comment by driesvints** [comment]
Please open an issue on the Symfony issue tracker.

**Comment by makroxyz** [comment]
same as #35417
