### ISSUE TITLE
Rule 'image' validation error after upgrading to symfony/mime v5.2.0

### ISSUE THREAD

**Issue by mnaas** [laravel/framework#35417]
- Laravel Version: 8.16.1
- PHP Version: 7.4

### Description:
After composer update that updated symfony/mime from 5.1.9 to v5.2.0, the 'image' validation rule keep giving me 400 response. After investigating the problem

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1037

here it shows that the array of mimes to compare against uses `jpeg`, while in here 

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1181

the 
```
$value->guessExtension()
```
Is returning `jpg` which is not accepted according to the array mentioned above.
Is this considered a symfony/mime v5.2.0 issue or Laravel related one?

**Comment by claudiodekker** [comment]
Can comfirm, seeing this issue in my test suite as well.

Test: 
```php
$response = $this
    ->actingAs(User::factory()->administrator()->create())
    ->json('POST', route('template.create'), [
        'icon' => UploadedFile::fake()->image('icon.jpg'),
    ]);
```

Implementation:
```php
$request->validate([
    'icon' => 'image',
]);
```

Output:
```
array:2 [
  "message" => "The given data was invalid."
  "errors" => array:1 [
    "icon" => array:1 [
      0 => "The icon must be an image."
    ]
  ]
]
```

**Comment by erikgaal** [comment]
Laravel picks the first element of the array of probably extensions here. https://github.com/laravel/framework/blob/2b4b18c8e0368906424d13594de3634a9bc6095b/src/Illuminate/Filesystem/Filesystem.php#L401

`symfony/mime:v5.2.0` somehow changed the order of the guessed extensions and now returns `jpg`, which is not in the array of allowed extensions here.

https://github.com/laravel/framework/blob/2b4b18c8e0368906424d13594de3634a9bc6095b/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1039

**Comment by fragkp** [comment]
@erikgaal Symfony does it too: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/File/File.php#L61

**Comment by halaei** [comment]
Can this be backported to Laravel 6 as well?

**Comment by driesvints** [comment]
Thanks all. As this is a change in Symfony we're unfortunately caught by this as well. Symfony doesn't consider a BC break so we'll have to patch this ourselves but it seems like we can do this easily. There's already a PR open which we'll merge soon and release tomorrow at the latest.

**Comment by driesvints** [comment]
Also see https://github.com/symfony/symfony/issues/39225

**Comment by driesvints** [comment]
The PR was merged and will be tagged soon.

**Comment by nguyenyou** [comment]
@driesvints Looks like the Laravel 5.x version also suffered from this issue. Should we apply the patch to Laravel 5.x too?

**Comment by driesvints** [comment]
Laravel 5.8 isn't maintained anymore sorry.

**Comment by olieady** [comment]
If you're on Laravel 5.8 still and you can't upgrade very easily like me do this instead

`composer require symfony/mime 5.1 `

**Comment by alex-zukitek** [comment]
I am using laravel v5.6 and same error. I fixed by replace "image" to "file|mimes:jpeg,png,jpg,gif,svg"
