### ISSUE TITLE
Illuminate/Support/Str TypeError

### ISSUE THREAD

**Issue by mickedplay** [laravel/framework#35425]
I've updated recently to PHP 8.0.0 and Laravel 8.16.1 and this happened:
```
TypeError

mb_strpos(): Argument #1 ($haystack) must be of type string, Closure given
```
[https://img.mickedplay.de/laravel-str-type_error.png](url)

71: `@if(request()->route()->getController()->getName() === 'something')`

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.
