### ISSUE TITLE
Console schedule twiceMonthly at a given time

### ISSUE THREAD

**Issue by brightjune** [laravel/framework#35429]
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
twiceMonthly at a given time is not working ok

![image](https://user-images.githubusercontent.com/5484071/100683554-8c3e7c80-33b3-11eb-991a-3770738385a2.png)

dailyAt($time) is set the minute and hour, then in function return set minute and hour to 0 again.

### Steps To Reproduce:
```
$schedule->command('test:test')
                ->twiceMonthly(1, 16, '1:30');
```

### Fixed:
```
public function twiceMonthly($first = 1, $second = 16, $time = '0:0')
    {
        $daysOfMonth = $first.','.$second;

        $this->dailyAt($time);

        return $this->spliceIntoPosition(3, $daysOfMonth);
    }
```

**Comment by driesvints** [comment]
We'll need a little more info at why it's not working okay.

**Comment by JayBizzle** [comment]
Created a PR that displays this issue #35436
