### ISSUE TITLE
@yield and @section is not working

### ISSUE THREAD

**Issue by abdinur99** [laravel/framework#35424]
- Laravel Version: #.#.# 
8.1
- PHP Version: #.#.#
7.4.12
- Database Driver & Version:

### Description:

<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

view/welcome.blade.php

<body class="p-6 bg-gray-200">
    <nav class="p-6 bg-white flex justify-between mb-6">
        <ul class="flex items-center">
            <li>
                <a href="/" class="p-3">Home</a>
            </li>
            <li>
                <a href="/" class="p-3">Dashboars</a>
            </li>
            <li>
                <a href="/" class="p-3">Post</a>
            </li>
        </ul>
    </nav>

    @yield('content')
</body>

view/show.blade.php

@extends('welcome')

@section('content')
<div class = "flex justify-center">
    <div class="w-8/12 bg-white p-6 rounded-lg">
        Content
    </div>
</div>

@endsection

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
