### ISSUE TITLE
Illuminate/Support/Str TypeError

### ISSUE THREAD

**Issue by mickedplay** [laravel/framework#35428]
- Laravel Version: 8.16.1
- PHP Version: 8.0.0
- Database Driver & Version: MariaDB 10.4

### Description:
TypeError thrown in template. Some templates are working but if I try it inside of app.blade.php, the error will appear.
Is there anything I missed?
[https://img.mickedplay.de/laravel-str-type_error.png](https://img.mickedplay.de/laravel-str-type_error.png)

### Steps To Reproduce:
Call `@php dd(request()->route()->getController()->getName()) @endphp` in your app.blade.php template.

**Comment by rodrigopedra** [comment]
Is your current route a closure based route? If so, `->getController()` will fail as it will try to instantiate the controller class from the controller action associated to it, which won't exist for a closure based route.

Also, when there is a controller class action associated to the route, does the controller have a `->getName()` method?

One more thing: there is a `@dd(...)` blade directive:

https://github.com/laravel/framework/blob/43bea00fd27c76c01fd009e46725a54885f4d2a5/src/Illuminate/View/Compilers/Concerns/CompilesHelpers.php#L17-L26

**Comment by mickedplay** [comment]
@rodrigopedra

`Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');`

The error didn't appear before updating to Laravel 8.16.1/PHP 8

**Comment by rodrigopedra** [comment]
I tried to reproduce it in a fresh Laravel app and it worked.

`./app/Http/Controllers/DashboardController.php`

~~~php
<?php

namespace App\Http\Controllers;

class DashboardController extends Controller
{
    public function index()
    {
        return view('test');
    }

    public function getName()
    {
        return 'name';
    }
}
~~~

`./resources/views/test.blade.php`

~~~blade
@extends('layouts.app')

@section('content')
    Dashboard
@endsection
~~~

`./resources/views/layouts/app.blade.php`

~~~blade
<!DOCTYPE html>
<html lang="en">
<head>
    <title>test</title>
</head>

<body>
@yield('content')
@php dd(request()->route()->getController()->getName()) @endphp
</body>
</html>
~~~

`./routes/web.php`

~~~php
<?php

use Illuminate\Support\Facades\Route;

// works fine for this route
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

// fails with same error message for this one
Route::get('/fails', function () {
    return view('test');
})->name('fails');
~~~

Can you post the results of running:

~~~blade
@php dd(request()->path(), request()->route()) @endphp
~~~

From your blade template? Thanks.

Also did you clean your view templates after upgrading your Laravel version?

~~~bash
$ php artisan view:clear
~~~

That might also help.

**Comment by driesvints** [comment]
Feel free to reply with additional info
