### ISSUE TITLE
firstOrNew return null value

### ISSUE THREAD

**Issue by alabjaoui** [laravel/framework#35438]
$user = Utilisateur::firstOrNew(
                ['id_user' => $agent->age_id],
                   ['id_user' => $agent->age_id, 'id_profil' => '9']
            );

 SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id_profil" violates not-null constraint

Version Laravel: 5.1

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
