### ISSUE TITLE
Customized validation messages not working for some validation rules

### ISSUE THREAD

**Issue by agi--** [laravel/framework#35432]
- Laravel Version: 8.x, 6.x (LTS)
- PHP Version: 7.4+
- Database Driver & Version: Mysql 5.7 (not relevant)

### Description:
Customized error messages for Form Requests as described in
https://laravel.com/docs/8.x/validation#customizing-the-error-messages (similar link for 6.x)
are not working for rules that check for numeric array in an array, e.g. `foo.* => 'required|array'`. 

The reason is the escape sequence `\z` in `\Illuminate\Validation\Concerns\FormatsMessages::getFromLocalArray():104`:
```
                    if (preg_match('#^'.$pattern.'\z#u', $key) === 1) {
```
The rule is processed correctly, only the customized error message is not used.
There must be a reason for this escape sequence that I fail to see.

I think it's a general problem if validation rules end with `.*`.

### Steps To Reproduce:

Just add following test to `\Illuminate\Tests\Validation\ValidationValidatorTest`.
```
    public function testNestedErrorMessageRetrievedFromLocalArray2()
    {
        $trans = $this->getIlluminateArrayTranslator();
        $v = new Validator(
            $trans,
            ['foo' => [['bar'], ['bar']]],
            ['foo.*' => ['required', 'array']],
            ['foo.*' => 'foo expects a list of arrays']
        );
        $this->assertTrue($v->passes());

        $v = new Validator(
            $trans,
            ['foo' => ['bar', 'bar']],
            ['foo.*' => ['required', 'array']],
            ['foo.*' => 'foo expects a list of arrays']
        );

        $this->assertFalse($v->passes());
        $this->assertSame('foo expects a list of arrays', $v->errors()->all()[0]);
    }
```
It's going to fail in on the last assert statement:
```
Failed asserting that two strings are identical.
Expected :'foo expects a list of arrays'
Actual   :'validation.array'
```
If you remove the escape sequence all tests are running successfully.

**Comment by driesvints** [comment]
You need to define this message on the rule itself:

```php


        $v = new Validator(
            $trans,
            ['foo' => ['bar', 'bar']],
            ['foo.*' => ['required', 'array']],
            ['foo.*.array' => 'foo expects a list of arrays']
        );
```

**Comment by agi--** [comment]
Oh, I see. Thanks.
