### ISSUE TITLE
Validation image fail after upgrade to v7.29.3

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#35431]
- Laravel Version: 7.29.3
- PHP Version: 7.3.22
- Database Driver & Version: PostgreSQL (ver. 12.4)

### Description:
After upgrade version to V7.29.3 validation image fail.

```
'avatar_file' => ['nullable', 'image', 'max:2000']
```
#### Before upgrade laravel version: 7.29.2
![Screen Shot 2563-12-01 at 14 55 30](https://user-images.githubusercontent.com/6513358/100713867-89f61580-33e7-11eb-90e5-9d5491dad80b.png)

#### After upgrade laravel version: 7.29.3
![Screen Shot 2563-12-01 at 14 57 56](https://user-images.githubusercontent.com/6513358/100713881-92e6e700-33e7-11eb-95df-c341ee0ef596.png)
![Screen Shot 2563-12-01 at 15 02 04](https://user-images.githubusercontent.com/6513358/100713906-9bd7b880-33e7-11eb-8f5c-1b84a5983dd0.png)

**Comment by driesvints** [comment]
This is because of a change in Symfony's mime component and will be fixed with today's release.

**Comment by sky93** [comment]
I still have this problem:
symfony/mime v5.2.3
laravel/framework: 5.8.*
php 7.4.14

**Comment by driesvints** [comment]
@sky93 Laravel 5.8 isn't supported anymore. Please upgrade to Laravel 8

**Comment by sky93** [comment]
> @sky93 Laravel 5.8 isn't supported anymore. Please upgrade to Laravel 8

In every Laravel version if we execute `composer install`, we should get the last **compatible** version correct?
