### ISSUE TITLE
Batchable jobs run sequentially rather than in parallel

### ISSUE THREAD

**Issue by ctwillie** [laravel/framework#35447]
- Laravel Version: 8.11.2
- PHP Version: 7.4.0
- Database Driver & Version: Mysql 8

### Description: 
Batchable jobs are running sequentially, rather than in parallel.

### Steps To Reproduce:
1. Define a ```Batchable``` job

```php
use Illuminate\Bus\Batchable;
use Illuminate\Bus\Queueable;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Bus;

class ChildJob
{
    use Batchable, Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    private $num;

    public function __construct($num)
    {
        $this->num = $num;
    }

    public function handle()
    {
        switch ($this->num) {
            case 1:
                sleep(10);
                dump($this->num);
                break;
            case 2:
                sleep(1);
                dump($this->num);
                break;
            case 3:
                sleep(0);
                dump($this->num);
                break;
            case 4:
                sleep(4);
                dump($this->num);
        }
    }

```

2. Define a job that batches ```ChildJob```
```php
use App\Jobs\ChildJob;
use Illuminate\Bus\Batch;
use Illuminate\Bus\Queueable;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Bus;

class ParentJob
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        $batch = Bus::batch([
            new ChildJob(1),
            new ChildJob(2),
            new ChildJob(3),
            new ChildJob(4),
        ])->dispatch();
    }

}
```

3. Dispatch ```ParentJob```

When ```ParentJob``` is dispatched, the output from each ```ChildJob``` seems to prove they running sequentially and not in parallel. I was under the impression that ```Batchable``` jobs will run in parallel.

Any help is much appreciated. Thanks!

**Comment by rodrigopedra** [comment]
What queue driver are you using?

Also how many queue workers are you starting?

If there is only one queue worker running it will consume one job at a time from the queue.

If using Horizon to manage your queue, please share its supervisor configuration.

**Comment by WadeShuler** [comment]
I am new to Laravel, and I see the batching is new in v8. However, I am currently working on batching and queues as well.

In the docs [https://laravel.com/docs/8.x/queues#chains-within-batches](https://laravel.com/docs/8.x/queues#chains-within-batches) it says:

> You may add a set of chained jobs within a batch by placing the chained jobs within an array. For example, we may execute two job chains in parallel.

So it seems like it should be an array of arrays.

Try this:

```
$batch = Bus::batch([
    [new ChildJob(1)],
    [new ChildJob(2)],
    [new ChildJob(3)],
    [new ChildJob(4)],
])->dispatch();
```

Though, what @rodrigopedra said may be true here as well. I am not sure if a single worker would rotate through the chain or step sequentially in this case?

**Comment by themsaid** [comment]
You need to run multiple workers in order for the jobs to be processed in parallel.

**Comment by ctwillie** [comment]
Thank you all for the help!

**Comment by tejas-webmavens** [comment]
In Bus::batch we are calling new ChildJob({dynamic}) child job in chain/batch

can we do something like first job response send to the next job call?
