### ISSUE TITLE
Pivot table fields in macros not properly aliased

### ISSUE THREAD

**Issue by Zoefschildpad** [laravel/framework#35458]
- Laravel Version: 8.12.13
- PHP Version: 7.3.23
- Database Driver & Version: MySQL  8.0.22

### Description:
When fetching a model using a query builder macro through a many-to-many with fields on the pivot table matching the other model, such as timestamps, the fields from the pivot table are fetched instead of the fields from the model.

A query without a macro starts with:
```
select `items`.*,
       `category_item`.`item_id` as `pivot_item_id`,
       `category_item`.`category_id`     as `pivot_category_id`,
       `category_item`.`created_at`    as `pivot_created_at`,
       `category_item`.`updated_at`    as `pivot_updated_at`
from `items`
         inner join `category_item` on `items`.`id` = `category_item`.`item_id`
where `category_item`.`category_id` = ?
```

but through a macro, the query starts with:

```
select *
from `items`
         inner join `category_item` on `items`.`id` = `category_item`.`item_id`
where `category_item`.`category_id` = ?
```

### Steps To Reproduce:
Create two models, 'item' and 'category' with a belongsToMany()->withTimestamps() relation.
Create a macro
```
Builder::macro('test') {
    dd($this->get());
}
```
and run
```
$category->items()->test();
```
and observe that the timestamps from the pivot table are returned instead of the ones from the model.

**Comment by taylorotwell** [comment]
Sounds like you're calling `get` on the Elouqent builder and maybe not on the relationship.
