### ISSUE TITLE
The photo must be an image

### ISSUE THREAD

**Issue by pietsteph** [laravel/framework#35450]
I have an API to upload an image and it has following rules:
`'photo' => 'image|mimes:jpeg,jpg'`

I uploaded an image with jpg format, but it's always gave me error that "The photo must be an image."
*Everything was fine before, until I did composer update, every image uploading API got this kind of error.

**Comment by veneliniliev** [comment]
duplicate #35431 #35417 
and already fixed from symfony/mime
