### ISSUE TITLE
Unknown named parameter $fallbackPlaceholder in PHP 8

### ISSUE THREAD

**Issue by devhammed** [laravel/framework#35459]
- Laravel Version: 7.24
- PHP Version: 8.0.0
- Database Driver & Version: Sqlite3

### Description:

I am using Route::fallback() to render the React.js frontend view but I started getting `Unknown named parameter $fallbackPlaceholder` after upgrading to PHP 8.

Below is the full log:

```
[2020-12-02 15:43:02] local.ERROR: Unknown named parameter $fallbackPlaceholder {"exception":"[object] (Error(code: 0): Unknown named parameter $fallbackPlaceholder at /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54)
[stacktrace]
#0 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#1 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#2 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#3 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#4 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#5 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#6 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#8 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#10 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#12 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#14 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#15 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#17 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#19 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#21 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#23 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#25 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#32 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#34 /home/devhammed/Projects/Epower/grant-master/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#36 /home/devhammed/Projects/Epower/grant-master/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#38 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#40 /home/devhammed/Projects/Epower/grant-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#41 /home/devhammed/Projects/Epower/grant-master/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#42 /home/devhammed/.composer/vendor/genesisweb/valet-linux-plus/server.php(276): require('...')
#43 {main}
"} 
```

NOTE: It works normally if using a closure as the handler but doesn't work with controller classes.

### Steps To Reproduce:

Running on PHP 8, create a controller/invokable controller and add a fallback route using this for example `Route::fallback('FrontendController');` and try to visit in the site.

**Comment by AegirLeet** [comment]
Upgrade to the latest 7.x version.

**Comment by devhammed** [comment]
> Upgrade to the latest 7.x version.

This is what I am getting...

<pre><font color="#42E66C">Loading composer repositories with package information</font>
<font color="#42E66C">Updating dependencies (including require-dev)</font>
<span style="background-color:#E356A7"><font color="#EFA554">Your requirements could not be resolved to an installable set of packages.</font></span>

  Problem 1
    - This package requires php ^7.2.5 but your PHP version (8.0.0) does not satisfy that requirement.
  Problem 2
    - tymon/jwt-auth 1.0.x-dev requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.2 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.1 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.5.1 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.5 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.4.1 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.4 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.3 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.2 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-rc.1 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-beta.3 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-beta.2 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-beta.1 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-alpha.3 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0-alpha.2 requires php ^5.5.9 || ^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - tymon/jwt-auth 1.0.0 requires php ^5.5.9|^7.0 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.25.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.28.4 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.28.3 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.28.2 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.28.1 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.28.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.27.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.26.1 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.26.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.25.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - laravel/framework v7.24.0 requires php ^7.2.5 -&gt; your PHP version (8.0.0) does not satisfy that requirement.
    - Conclusion: don&apos;t install laravel/framework v7.30.0
    - Conclusion: don&apos;t install laravel/framework v7.29.3
    - Conclusion: don&apos;t install laravel/framework v7.29.2
    - Installation request for tymon/jwt-auth ^1.0 -&gt; satisfiable by tymon/jwt-auth[1.0.0, 1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.4.1, 1.0.0-rc.5, 1.0.0-rc.5.1, 1.0.1, 1.0.2, 1.0.x-dev].
    - Conclusion: don&apos;t install laravel/framework v7.29.1
    - Conclusion: don&apos;t install laravel/framework v7.29.0
    - tymon/jwt-auth 1.0.0-alpha1 requires illuminate/support 5.1.* || 5.2.* -&gt; satisfiable by illuminate/support[5.1.x-dev, 5.2.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don&apos;t install illuminate/support 5.2.x-dev|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.0|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.19|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.21|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.24|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.25|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.26|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.27|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.28|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.31|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.32|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.37|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.43|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.45|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.6|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.2.7|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support 5.1.x-dev|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.1|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.13|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.16|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.2|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.20|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.22|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.25|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.28|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.30|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.31|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.41|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.6|don&apos;t install laravel/framework 7.x-dev
    - don&apos;t install illuminate/support v5.1.8|don&apos;t install laravel/framework 7.x-dev
    - Installation request for laravel/framework ^7.24 -&gt; satisfiable by laravel/framework[7.x-dev, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.28.4, v7.29.0, v7.29.1, v7.29.2, v7.29.3, v7.30.0].

</pre>

**Comment by AegirLeet** [comment]
You'll have to wait until `tymon/jwt-auth` supports ^8.0 then.

**Comment by devhammed** [comment]
> You'll have to wait until `tymon/jwt-auth` supports ^8.0 then.
> 
> Alternatively, try running composer with `--ignore-platform-reqs` (not a good solution though).

Well, it is working now by ignoring platform requirements.
