### ISSUE TITLE
DatabaseSeeder Behaving Differently Depending on How it's Called

### ISSUE THREAD

**Issue by jayceedaily** [laravel/framework#35452]
**Actual Project**
- Laravel Version: 8.0
- PHP Version: 7.4.11
- Database Driver & Version: PostgresSQL 12.4 

**Tested in  New Version**
[Test Link](https://github.com/jayceedaily/laravel_seeder_bug)

- Laravel Version: 8.12
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8.0.22

### Description:
Running `db:seed` populates fields regardless if it's in the Model fillable, and when running it programmatically, it only populates the field included in the fillable.

| id | name   | description |
|----|--------|-------------|
| 1  | burger | a sandwhich |
| 2  | burger |             | 

_ref. The first record was created with `db:seed`  while the second record was created by running DatabaseSeeder via a controller_

### Steps To Reproduce:
**Model**
```
class Item
{
     protected $fillable = ['name'];
}
```
**Seeder**
```
public function run() 
{
     Item::create([
          'name' => 'burger',
          'description' => 'a sandwich'
     ]);
}
```
**DatabaseSeeder**
```
public function run()
{
     $this->call(Item::class);
}
```
**TriggerSeederController**
Insert the item but with no description values.
```
public function index()
{
     $seeder= new DatabaseSeeder;

     $seeder->run();
}
```

**Console Scenario**
Ignores the fillable and includes the description on the record.
```
> php artisan db:seed
```

**Comment by jayceedaily** [comment]
After a little digging I found that the db:seed was doing forcing mass assignments.  Shouldn't it be consistent everywhere and honor the fillables. If it's gonna do the mass assignments, why not have it as a prop on the DatabaseSeeder so that it is clear to the developer what is happening.

**Comment by taylorotwell** [comment]
Use `Artisan::call('db:seed', ['class' => ItemSeeder::class])`

**Comment by jwilson-bm** [comment]
@taylorotwell Why did you close this? I can confirm that this is still an issue. And your suggestion does not help - the same error still happens. I see in the documentation that there is a note saying _"Mass assignment protection is automatically disabled during database seeding."_  But there is no explanation as to why. So what is the logic in not honoring mass assignment protection when running a seeder? And to @jayceedaily 's point, why not offer a flag to enable/disable it?
