### ISSUE TITLE
Nested anonymous components default props overwrites given attributes

### ISSUE THREAD

**Issue by jhhazelaar** [laravel/framework#35457]
- Laravel Version: 8.17.0
- PHP Version: 7.4.12

### Description:
Nested anonymous components can pass down attributes with de Attribute bag. A anonymous component can have a `@props` directive with defaults. If you pasdown the attributes bag with nested component, the default is used and not the passed attribute.

### Steps To Reproduce:

Anonymous component button(`components/button.blade.php`):
```blade
@props(['tag' => 'button'])

<{{ $tag }} {{ $attributes->merge(['class' => 'inline-flex items-center px-4 py-2 border text-sm font-medium rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2']) }}>
    {{ $slot }}
</{{ $tag }}>
```

Anonymous component button blue(`components/button-blue.blade.php`):
```blade
<x-button {{ $attributes->merge(['class' => 'border-transparent text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500']) }}>
    {{ $slot }}
</x-button>
```

Use somewhere in blade template:
```blade
<x-button-blue tag="a">Button text</x-button>
```

Expect:
```html
<a class="inline-flex items-center px-4 py-2 border text-sm font-medium rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 border-transparent text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500">
    Button text
</a>
```

Given:
```html
<button class="inline-flex items-center px-4 py-2 border text-sm font-medium rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 border-transparent text-white bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500">
    Button text
</button>
```

Workaround to get expected, change the button component to:
```blade
<{{ $attributes->get('tag', 'button') }} {{ $attributes->merge(['class' => 'inline-flex items-center px-4 py-2 border text-sm font-medium rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2']) }}>
    {{ $slot }}
</{{ $attributes->get('tag', 'button') }}>
```

**Comment by taylorotwell** [comment]
Yeah, you have to be explicit about the tag prop you pass down.

**Comment by jhhazelaar** [comment]
Oke, why not pass it down? I'm just curious. With passing it down the component explicitly, we get some extra line of code that doesn't do anything besides passing it down.

By the way, thank you for creating laravel and doing all this work for the community!
