### ISSUE TITLE
Form field not found in Illuminate\Http\Request object

### ISSUE THREAD

**Issue by michele-grifa** [laravel/framework#35460]
- Laravel Version: 8.17.1
- PHP Version: 7.4
- Database Driver & Version:

### Description:
I have a form with two field and i want to upload two different type of files, the first field load all image in a folder, the second load an Excel file.
When i upload all the fields, the second (**field2**) is not present in the request. If i choose only the Excel file, the field is populated in the controller.

I created a Laravel Playground at this [link](https://laravelplayground.com/#/snippets/ad39ce1f-fc72-40ba-bf19-8b62e7f9927f), to demostrate the problem.

### Steps To Reproduce:

- Choose a folder with some images with the first input field
- Choose a file with the second input field
- Press the Test button

**Comment by rodrigopedra** [comment]
Just tested and it is working as expected.

Note that form inputs are sent to the server using their `name` attributes as each field name, not the `id` attribute. This is a HTML standard not specific to Laravel.

Images from the directory are sent in the `images[]` array corresponding to its input `name` attribute.

And excel file is sent as `file1` corresponding to its input `name` attribute.

![image](https://user-images.githubusercontent.com/5470108/100901232-6217b800-34a2-11eb-9441-1460d325a269.png)

**Comment by michele-grifa** [comment]
> Just tested and it is working as expected.
> 
> Note that form inputs are sent to the server using their `name` attributes as each field name, not the `id` attribute. This is a HTML standard not specific to Laravel.
> 
> Images from the directory are sent in the `images[]` array corresponding to its input `name` attribute.
> 
> And excel file is sent as `file1` corresponding to its input `name` attribute.
> 
> ![image](https://user-images.githubusercontent.com/5470108/100901232-6217b800-34a2-11eb-9441-1460d325a269.png)
Yes i know that are sent using `name` attribute

I tested out and with a few images work, but if i load more than 20 images, only the first 20 are send, and the second file is not sent at all

**Comment by rodrigopedra** [comment]
It seems your `php.ini` is not configured to handle this amount of file uploads.

You can check which directives regarding file uploads are available here:

https://www.php.net/manual/en/ini.core.php#ini.sect.file-uploads

Those values affect how PHP handle file uploads before delegating to Laravel. If those configurations are not set to accommodate your use-case PHP could fail to populate the request variables with the expected values, so Laravel could misssome files.

If you don't know where your `php.ini` is located, you can create a route that returns `phpinfo();`. This function will render all values configured for your PHP executable, including the `php.ini` file location.

Note that a common PHP installation has two `php.ini`, one for CLI and one for the web process. So you should check the web one. There are many ways to do so, including inspecting the file itself in a text editor, in case you know where it is located. But the easiest way, in my opinion, is to return the results of calling `phpinfo()`.

Hope this helps.

**Comment by michele-grifa** [comment]
> It seems your `php.ini` is not configured to handle this amount of file uploads.
> 
> You can check which directives regarding file uploads are available here:
> 
> https://www.php.net/manual/en/ini.core.php#ini.sect.file-uploads
> 
> Also read about this one:
> 
> https://www.php.net/manual/en/ini.core.php#ini.post-max-size
> 
> Those values affect how PHP handle file uploads before delegating to Laravel. If those configurations are not set to accommodate your use-case PHP could fail to populate the request variables with the expected values, so Laravel could misssome files.
> 
> If you don't know where your `php.ini` is located, you can create a route that returns `phpinfo();`. This function will render all values configured for your PHP executable, including the `php.ini` file location.
> 
> Note that a common PHP installation ships with two `php.ini` files, one for CLI and one for the web process. You should check the web related one. But also check the CLI one if you are developing your application using PHP's built-in server (used by `php artisan serve` under the hood), as this built-in server uses the CLI `php.ini` file.
> 
> There are many ways to do so, including inspecting the file itself in a text editor, in case you know where it is located. But the easiest way, in my opinion, is to return the results of calling `phpinfo()`.
> 
> Hope this helps.

Thanks, the `max_file_uploads` resolved my problem.
