### ISSUE TITLE
Trying to access array offset on value of type bool [L7]

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/framework#35461]
- Laravel Version: 7.29.3
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7

### Description:
I get the following error: ```Trying to access array offset on value of type bool``` when using `$this->throttle`.
The error is here:
```
public function acquire()
    {
        $results = $this->redis->eval(
            $this->luaScript(), 1, $this->name, microtime(true), time(), $this->decay, $this->maxLocks
        );

        $this->decaysAt = $results[1];

        $this->remaining = max(0, $results[2]);

        return (bool) $results[0];
    }
```
If `$results` is false, it throws an error that is hard to debug.
 
### Steps To Reproduce:
1. When `$this->throttle` fails, it doesn't fail gracefully.

**Comment by taylorotwell** [comment]
Please re-submit with a small reproducable example that we can paste into a fresh Laravel application.

**Comment by renkx** [comment]
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/26194193/163745415-ec0f1289-6e15-43c8-9720-554c24ed77f6.png">

Laravel Version: 9.8.1
PHP Version: 8.1.4
Redis Version：4.0

redis occasionally returns false
