### ISSUE TITLE
Throttle Middleware returns wrong response type HTML, when JSON expected for API routes.

### ISSUE THREAD

**Issue by ronnie-depp** [laravel/framework#35483]
- Laravel Version: 8.15.0
- PHP Version: 7.3.x
- Database Driver & Version:

### Description:

Throttle Middleware should automatically return response in JSON or HTML based on WEB or API route. Or should provide option to get response in a particular format even in XML, JSON, CSV, HTML etc.

Not just throttle but in every class or package which returns a response built by Laravel.

### Steps To Reproduce:

Whenever any exception occurs on Laravel's end it must return exception in a specified response type.

**Comment by taylorotwell** [comment]
Your request needs to `Accept` the `application/json` content type.

**Comment by ronnie-depp** [comment]
thanks
