### ISSUE TITLE
Broadcasting - ReflectionException: Class App\Http\Middleware\Authenticate:api does not exist

### ISSUE THREAD

**Issue by adrianpaiva1** [laravel/framework#35481]
- Laravel Version: 8.16
- PHP Version: 7.4
- Database Driver & Version: MySql 8
- Laravel Passport 10.0.1

### Description:

After upgrading to laravel 8.16 from 8.x, currently getting this error when including the "auth:api" middleware to broadcast routes

In BroadcastServiceProvider

`Broadcast::routes(['middleware' => ['auth:api'], "prefix" => "api"]);`

`ReflectionException: Class App\Http\Middleware\Authenticate:api does not exist in file /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php on line 718`

This happens when attempting to auth using the "api/broadcasting/auth" route

### Steps To Reproduce:

Add the auth:api middleware to the broadcast routes to the BroadcastServiceProvider as seen above.

Assuming this is the commit causing this for me

https://github.com/laravel/framework/commit/acb4b77adc6e257e132e3b036abe1ec88885cfb7#diff-f26a04b14bec5e0c2d41744423329f18e0bcbbeae8a3deb16d02ff8799494490

Not an issue on Laravel 8.15 and below

**Comment by taylorotwell** [comment]
Fixed on 8.17.2.
