### ISSUE TITLE
Method sync not remove row from deleted_at with SoftDeletes

### ISSUE THREAD

**Issue by yvescleuder** [laravel/framework#35485]
- Laravel Version: 8.12
- PHP Version: 7.4.3
- Database Driver & Version: MariaDB 10.4.14 

### Description:
I have 3 tables, 1 being a Many To Many relationship table

1) vehicles
2) accessories_vehicle (N-N)
3) accessories

When I am going to update a particular vehicle, I receive the IDs of the accessories that I want to link or undo the link as a parameter of my request.
Imagine that when I registered this vehicle, I had the accessory [1,2,3], after a while the user can go and remove accessory 3 or any other one he had, or can he add it correctly? He can send the 3,4,5, so the accessory 1,2 must be removed.
When I make $vehicle->accessories()->sync([3,4,5]); works perfectly, it removes the 1,2 accessories and adds the 4,5. Accessory 3 remains on the base as it has not yet been removed.
Soon after, the user wants to return accessory 2, when he sends the request he executes in this way.
$vehicle->accessories()->sync([2,3,4,5]);
However accessory 2 is not set to NULL in the deleted_at field, it remains "deleted", I cannot do this with sync.
Also, a new record is not created with accessory 2, I don't know why you don't make any of the options.

### Steps To Reproduce:

`class Vehicle extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'placa',
        'renavam',
        'cor_id',
        'revenda_id',
        'endereco_id'
    ];

    public function accessories()
    {
        return $this->belongsToMany(Accessory::class)
            ->using(AccessoriesVehicle::class)
            ->withTimestamps();
    }
}`

`class Accessory extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'nome'
    ];
}`

`class AccessoriesVehicle extends Pivot
{
    use SoftDeletes;
}`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by rodrigopedra** [comment]
See docs about:

> Note: Pivot models may not use the `SoftDeletes` trait. If you need to soft delete pivot records consider converting your pivot model to an actual Eloquent model.

https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models
