### ISSUE TITLE
Scheduling: emailWrittenOutputTo in combination with appendOutputTo incompatible

### ISSUE THREAD

**Issue by Phillip85** [laravel/framework#35492]
- Laravel Version: 6.0.4
- PHP Version: 7.4
- Database Driver & Version: mysql 5.7

### Description:

When you want to write output of an scheduled job to a log file and get an email for this output, 
it will send all previous outputs via email, which are written to the same log file.

According to my understanding, it should only send the output of the current execution.

### Steps To Reproduce:

```
            $schedule->command(App\Console\Commands\TestCommand::class)
                ->hourly()
                ->withoutOverlapping()
                ->runInBackground()
                ->appendOutputTo(storage_path('logs') . "/output" . date("Y-m-d") . ".log")
                ->emailWrittenOutputTo("phillip@example.org");
```

**Comment by driesvints** [comment]
Please upgrade to the latest Laravel 6 version and see if the issue has been solved since then.

**Comment by Phillip85** [comment]
same behaviour in latest version:

> php artisan --version
Laravel Framework 6.20.6

**Comment by Phillip85** [comment]
looks like there has nothing changed in version 8 too
at least the method looks like the same

https://github.com/laravel/framework/blob/a8f7118bd7451302a8563c05494ed6adf9f0d777/src/Illuminate/Console/Scheduling/Event.php#L477

**Comment by taylorotwell** [comment]
Really I think to change this now would be a breaking change. Some people may for example depend on seeing the whole output every time. Could possibly be considered for a `master` branch change but I'm not sure if it's worth the breaking change?

**Comment by Phillip85** [comment]
the current behavior is inconsistent, right now it depends on the name of the logfile.

```
->appendOutputTo("test.log");
```
and
```
->appendOutputTo("test".date("Ymd").".log");
```
and
```
->appendOutputTo("test".uniqid().".log");
```

would lead to different behavior of the method emailWrittenOutputTo


how about some split into 

```
emailLoggedWrittenOutputTo
emailCurrentWrittenOutputTo
```

**Comment by driesvints** [comment]
@Phillip85 you're always free to attempt a PR but like Taylor said it might not be worth the breaking change.
