### ISSUE TITLE
matchAll only returns group 1 or 0

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#35509]
- Laravel Version: 8*
- PHP Version: 7.4

`Str::of($str)->matchAll()` only return group 1 or 0

```php
public function matchAll($pattern)
{
    preg_match_all($pattern, $this->value, $matches);

    if (empty($matches[0])) {
        return collect();
    }

    return collect($matches[1] ?? $matches[0]);
}
```

So how can i use this if i want to use more than 1 group ? is it possible to convert these to laravel matchAll?:

```php
preg_match_all('/td>(.*?)<.*\R.*\R.*?d>(.*?)<.*\R.*?d>(.*?)</', $html, $m);

$result = array_map(function ($c, $p, $s) {
    return [
        'c' => $c,
        's' => $p,
        'r' => $s
    ];
}, $m[1], $m[2], $m[3]);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by foremtehan** [comment]
@driesvints sees "So how can i..." then immediately close the issue.
