### ISSUE TITLE
Laravel project not working after migrating to a new server

### ISSUE THREAD

**Issue by degeta10** [laravel/framework#35513]
- Laravel Version: 5.8.38
- PHP Version: 7.2.34
- Database Driver & Version: mysql v5.7

### Description:
I just migrated to an ec2 instance in AWS. I installed everything fresh and whole setup is over.
But now when I login it shows the below error:

> Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated.

How can I solve this issue? I have tried the fixes mentioned in [this ](https://github.com/lcobucci/jwt/issues/550)thread but still doesn't work.

### Steps To Reproduce:

I'm using passport version v^7.4. And also for reference below is my composer.json.

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "aloha/twilio": "^4.0",
        "astrotomic/laravel-translatable": "^11.9",
        "benwilkins/laravel-fcm-notification": "^4.0",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.0",
        "fzaninotto/faker": "^1.9",
        "guzzlehttp/guzzle": "^6.5",
        "intervention/image": "^2.5",
        "justbetter/laravel-pagination-with-havings": "^1.4",
        "kreait/laravel-firebase": "^2.4",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.4",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^1.0",
        "maatwebsite/excel": "^3.1",
        "predis/predis": "^1.1",
        "spatie/laravel-permission": "^3.7",
        "vinkla/hashids": "^6.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
