### ISSUE TITLE
Relation::tableNameAsMorphType breaks morphTo relations

### ISSUE THREAD

**Issue by dmason30** [laravel/framework#35519]
- Laravel Version: 8.17.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
The https://github.com/laravel/framework/pull/35257 PR doesn't seem to work with `morphTo` relations. You end up with an `Class 'posts' not found`  when using in conjunction with `Relation::tableNameAsMorphType();`

```php
Error : Class 'posts' not found
/src/Illuminate/Database/Eloquent/Relations/MorphTo.php:180
/src/Illuminate/Database/Eloquent/Relations/MorphTo.php:129
/src/Illuminate/Database/Eloquent/Relations/MorphTo.php:115
/src/Illuminate/Database/Eloquent/Builder.php:597
/src/Illuminate/Database/Eloquent/Builder.php:566
/src/Illuminate/Database/Eloquent/Builder.php:534
```
### Steps To Reproduce:
Taking the example from the docs where `imageable` could be a `Post` or a `User`.
https://laravel.com/docs/8.x/eloquent-relationships#one-to-one-polymorphic-relations:

```php
class Image extends Model
{
    public function imageable()
    {
        return $this->morphTo();
    }
}
```

Add the below to `AppServiceProvider` in the `boot` method:
```php
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {     
        Relation::tableNameAsMorphType();
    }
}
```

The below code will throw the exception described above:

```php
$post = Post::factory()->create();

$image = Image::factory()->create([
    'imageable_type' => $post->getTable(), // 'posts'
    'imageable_id' => $post->id,
]);

// This will throw the exception
$postTitle = $image->imageable->title
```

**Comment by driesvints** [comment]
Can you create a quick repo that reproduces the problem? Please commit custom code separately from the base skeleton.

**Comment by dmason30** [comment]
@driesvints No problem. 

Repo: https://github.com/dmason30/laravel-framework-morph-to-example
Commit: https://github.com/dmason30/laravel-framework-morph-to-example/commit/2ffc8ca19464a4c116b5dc4105cc26e1d9a4b0b5
Erroring Code: https://github.com/dmason30/laravel-framework-morph-to-example/blob/master/tests/Feature/ExampleTest.php

Github Action Run showing failing test:
https://github.com/dmason30/laravel-framework-morph-to-example/runs/1511184347?check_suite_focus=true

**Comment by taylorotwell** [comment]
@imanghafoori1

**Comment by driesvints** [comment]
I've come to the conclusion that it's impossible to solve this one. Since with the inverse here you only have the context of the alias there's no way to derive the class name from it as you simply don't know the namespace of the model. 

At the moment I'm more leaning to reverting this completely as we can't ever ship this properly. Mapping custom morph types will always need to be done manually through the morph map.

**Comment by imanghafoori1** [comment]
Checking the problem

**Comment by imanghafoori1** [comment]
It seems that the `morphTo` relation exceptionally does not accept a `$related` model, in the case `Post::class`.
So there are a few approaches to this for laravel 9.x :

- To change the `morphTo` to accept a $related parameter, like other morph relations.

- Hold on this behaviour as the default to this and document `Relation::morphMap(...);` as mandatory only for `morphOne` relations. (Not for all relations)

- Try to derive \App\Post, \App\Models\Post from `posts` before bail out with an error.

- or Revert it :skull: 🙌

**Comment by driesvints** [comment]
1. Kind of defeats the purpose of morphMap to begin with, 2. would still contain the broken code, 3. isn't feasible (as explained above)

I think it's best to revert this.

**Comment by imanghafoori1** [comment]
@driesvints Yeah, the first option not possible with one model. it should accept a list of "Imagable models" which is not very good either.

**Comment by dmason30** [comment]
One consideration for option 2 is that you can still use 'Relation::morphMap' in conjunction with `Relation::tableNameAsMorphType`

So say they code was changed to attempt to morph table names into models via `str->singular->camelCase` and checking `class_exists` to throw a more meaningful error. 

If you had a table 'posts' but for the benefit of this example for some reason your model was called `BlogPost` then you could setup in the `AppServiceProvider`.

```php
class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {     
        Relation::tableNameAsMorphType();

        Relation::morphMap(['posts' => BlogPost::class]);
    }
}
```

The benefit here keeps it using the table name as the default so you don't end up adding all your models to `morphMap` and if it can't find the model when doing `morphTo` the error should suggest to add the `table => model` to the map.

If your models were outside of the default `App/` or `App/Models/` locations then you probably shouldn't use this method anyway.

**Comment by taylorotwell** [comment]
Let's just revert it.

**Comment by taylorotwell** [comment]
@driesvints can you send in the revert PR?

**Comment by driesvints** [comment]
@taylorotwell will do
