### ISSUE TITLE
cache:clear does not work when php 8 does not use exception variable

### ISSUE THREAD

**Issue by yusufonur** [laravel/framework#35512]
- Laravel Version: 8.17.2
- PHP Version: 8.0.0
- Database Driver & Version: Mysql 5.7.24 || PDO

### Steps To Reproduce:
If I use it like this, the cache:clear command gives an error:

    try {
        //...
    } catch (Exception) {
        return "Foo bar";
    }

The error i got:
Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in ...Path

The file containing the relevant code is in Helpers.php and I am adding it in composer.json.

**Comment by driesvints** [comment]
You're missing a variable next to your exception type.

**Comment by yusufonur** [comment]
> You're missing a variable next to your exception type.

https://wiki.php.net/rfc/non-capturing_catches 

This type of usage is allowed with PHP-8 "non-capturing catches".

**Comment by driesvints** [comment]
@yusufonur your CLI PHP version is probably set to an older version than PHP 8

**Comment by yusufonur** [comment]
Yes, it worked correctly when I updated the CLI version. Thank you.
