### ISSUE TITLE
Guzzlehttp\Guzzle seems to be missing in dependencies

### ISSUE THREAD

**Issue by madman-81** [laravel/framework#35517]
- Laravel Version: 7.28.4
- PHP Version: 7.4.6
- Database Driver & Version: n/a

### Description: 
Updating Laravel Passport from 9.3 to 9.4 highlighted that Guzzlehttp\Guzzle was also removed from the packages. However, Laravel's HTTP client is depending on Guzzle as well. Should it therefore not be listed in "require" instead of "require-dev"?

### Steps To Reproduce:
I haven't tested it with a clean project, but downgrading Passport to 9.3.2 installed Guzzle again and made my project work again too. Of course I could also require Guzzle in my project, but shouldn't that be required by the Laravel project?

**Comment by rodrigopedra** [comment]
Guzzle is a suggested dependency:

https://github.com/laravel/framework/blob/c007d7cc726c5bf839d3547a5f021f927635ee73/composer.json#L135

The docs on the HTTP Client tells one should install Guzzle before using it:

> Before getting started, you should ensure that you have installed the Guzzle package as a dependency of your application.

https://laravel.com/docs/8.x/http-client#introduction

I guess the idea is as not everyone will use the HTTP Client, to not make Guzzle a hard dependency as someone might be using a different version of Guzzle when migrating a project, or not using it at all.

**Comment by driesvints** [comment]
Guzzle is indeed not a requirement to run most of the framework's features.
