### ISSUE TITLE
Illuminate\Auth\Events\Lockout returns empty $event

### ISSUE THREAD

**Issue by MatthewK177** [laravel/framework#35529]
- Laravel Version: 8.17.2
- PHP Version: 7.4.13
- Database Driver & Version: N/A

### Description:
The `Illuminate\Auth\Events\Lockout` event does not return the expected data to the listener.

### Steps To Reproduce:
```
<?php

namespace App\Listeners;

use Illuminate\Auth\Events\Lockout;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

use App\Models\System\SystemLog;

use Log;

class LogLockout
{
  /**
   * Create the event listener.
   *
   * @return void
   */
  public function __construct()
  {
    //
  }

  /**
   * Handle the event.
   *
   * @param  Lockout  $event
   * @return void
   */
  public function handle(Lockout $event)
  {
    Log::info(json_encode($event));
  }
}
```
The returned result is `{"request":{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}}`

The expected result is the throttled request as per https://laravel.com/api/8.x/Illuminate/Auth/Events/Lockout.html

**Comment by driesvints** [comment]
This class isn't used anymore. It seems to be forgotten during the refactor of the way throttling works. I'll send in a PR to remove it.

**Comment by rodrigopedra** [comment]
@driesvints just for the record, the Lockout event is dispatched from

1 - Fortify:

https://github.com/laravel/fortify/blob/f29ed3f63d6da006fb540e2894e4aa387ccabde2/src/Actions/EnsureLoginIsNotThrottled.php#L42

2 - Breeze:

https://github.com/laravel/breeze/blob/e2b6643978739f2e4a51deda8bcd03228fcddc0a/stubs/App/Http/Requests/Auth/LoginRequest.php#L72

3 - Laravel UI

https://github.com/laravel/ui/blob/ff6af4f0bc5a5bfe73352cdc03dbfffc4ace92d8/auth-backend/ThrottlesLogins.php#L82

**Comment by driesvints** [comment]
@rodrigopedra ah gotcha

@MatthewK177 if you could post more thorough steps to reproduce (with any of the libraries from above) I'll take a look at this.

**Comment by alperyazgan** [comment]
Related issue : [Lockout Event is not fired](https://github.com/laravel/fortify/issues/336)

[This class isn't used anymore](https://github.com/laravel/framework/issues/35529#issuecomment-740540007)
