### ISSUE TITLE
Routing: APP_URL blocks kernel DNS resolving

### ISSUE THREAD

**Issue by rennokki** [laravel/framework#35522]
- Laravel Version: Latest 8.x
- PHP Version: 7.4.x
- Database Driver & Version: -

### Description:
After many attempts and different configurations, I found out that the APP_URL enforces the entry point for the routes. I am pretty sure it's not an NGINX error because an old-fashioned `var_dump($_SERVER)` was tested in `public/index.php` file and it successfully worked, alongside the 404 NOT FOUND page.

This is failing my internal healthchecks within the app, meaning that it works from the outside, but Laravel throws 404 from the inside when obviously using another domain than `APP_URL`. I tried diff-ing between the latest 7.x and latest 8.x to maybe find something relevant, but I can't seem to find anything suspect. I'm still going to try to find something while this issue gets replies in hope that the route issue is not actually an issue and it can easily be fixed from my side.

### Steps To Reproduce:
- Deploy a Laravel basic application into any NGINX environment with a single root { } block that has a `listen 80 default_server`
- Set the `APP_URL` to `http://test.local.app`
- Add that domain to `/etc/hosts` that points to `127.0.0.1`
- `curl http://test.local.app` - it works
- `curl http://127.0.0.1` - throws 404
- Changing the `APP_URL` to `http://test.local2.app`, for example, would make `http://test.local.app` fail to 404, even if it points to `127.0.0.1`

**Comment by kohlerdominik** [comment]
Hi

is it a fresh Laravel installation? Then it might be related to TrustHosts-Middleware. You can disable it by commenting out the line in Kernel.php

**Comment by driesvints** [comment]
See the above.
