### ISSUE TITLE
Cannot create a new Laravel application on Linux (Fedora)

### ISSUE THREAD

**Issue by yaayes** [laravel/framework#35537]
- Laravel Version: Latest
- PHP Version: ~
- Docker version: 19.03.13
- docker-compose version: 1.27.4

### Description:
I want to try Laravel Sail but I can't install a new Laravel application on Fedora 33, using the new approach from the docs
https://laravel.com/docs/8.x#getting-started-on-linux

And here is the output when I'm executing the command `curl https://laravel.build/my-new-app | bash`

```bash
Warning: TTY mode requires /dev/tty to be read/writable.
    Creating a "laravel/laravel" project at "./my-new-app"
    Installing laravel/laravel (v8.5.2)
    
                                  
      [ErrorException]            
  mkdir(): Permission denied  
                              

    create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

cd: no such file or directory: my-new-app

Please provide your password so we can make some final adjustments to your application's permissions.

[sudo] password for ysedrani: 

Thank you! We hope you build something incredible. Dive in with: cd my-new-app && ./vendor/bin/sail up

```
After that, the directory named `my-new-app` was not created, even if the bash script says `Dive in with: cd my-new-app && ./vendor/bin/sail up`

I've searched a lot, but since this install approach is new, I really can't find anything!

### Steps To Reproduce:
Install a new Laravel application following the instructions from the official docs:
https://laravel.com/docs/8.x/installation#getting-started-on-linux

**Comment by taylorotwell** [comment]
Where are you running the command? Note that the problem is here:

```
mkdir(): Permission denied  
```

Some directory permission issue on your machine.

**Comment by yaayes** [comment]
Thank you for responding.. I'm running this command within a directory in my home directory! I don't think it's related to some permission issue, but i will recheck that again.
And IMHO the bash script should exit with an error code instead of actual output: `Dive in with: cd my-new-app && ./vendor/bin/sail up`. whereas nothing was created!

**Comment by yaayes** [comment]
Hi @taylorotwell, I have rechecked the directory permissions and it seems correct:
```bash
drwxrwxr-x ysedrani ysedrani    4 KB Mon Nov 16 15:12:58 2020 code
```
change it to `777` doesn't work too.

And since the command `laravel new my-new-app` running from the docker container, the thing is SELinux is preventing the container from changing the host, I've tried to disable SELinux `setenforce 0` and it works, but disabling SELinux is not a solution, I'll try to generate a policy from the audit.
A note in the official docs will saves time for anyone running Linux with SELinux enabled (Fedora, CentOS, RHEL..)
