### ISSUE TITLE
Doesn't the hidden property work after binding

### ISSUE THREAD

**Issue by doox911Finex** [laravel/framework#35532]
- Laravel Version: 8.17.2
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
If I just execute User::all() in the controller everything works. But if I do it via binding, then the hidden field doesn't work. I can see hidden fields in the server response. How to solve this problem?

My provider:
```php
  class RepositoryServiceProvider extends ServiceProvider
  {
    public function register()
    {
      $this->app->when(UserController::class)
        ->needs(ModelRepositoryInterface::class)
        ->give(function() {
          return new UserRepository(new User);
        });
    }
  }

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by doox911Finex** [comment]
This is a bug.

**Comment by driesvints** [comment]
@doox911Finex I doubt it. Please try a support channel.
