### ISSUE TITLE
Inconsistent behavior in evaluation of factory definitions

### ISSUE THREAD

**Issue by MajedDH** [laravel/framework#35547]
- Laravel Version: 8.17.2
- PHP Version: 7.4.9
- Database Driver & Version: not related.

### Description:
According to the documentation of the factories:

> If the relationship's columns depend on the factory that defines it you may provide a callback which accepts the evaluated attribute array:
> ```
> public function definition()
> {
>     return [
>         'user_id' => User::factory(),
>         'user_type' => function (array $attributes) {
>             return User::find($attributes['user_id'])->type;
>         },
>         'title' => $this->faker->title,
>         'content' => $this->faker->paragraph,
>     ];
> }
> ```
That's true only key of the relationship is before the dependent attribute. for example:
```
   return [
         'user_id' => User::factory(),
         'content' => function(array $attrs) {
               return "A POST FOR USER" . $attrs['user_id'] ;
         },
     ];
```
in this example it'll work and `$attrs['user_id']` will be some kind of a key (some integer for example).
but if we reverse the order of the keys:
```
   return [
          'content' => function(array $attrs) {
               return "A POST FOR USER" . $attrs['user_id'];
         },
         'user_id' => User::factory(),
     ];
```
here while running the 'content' closure, `$attrs['user_id']` will have the value of `User::factory()`. this is not consistent and probably will cause trouble to developers just like it caused to me. 

If the behaviour is intended I think this should go in the documentation. OR it can be repaired by expanding the attributes [Factory.php#L407](https://github.com/laravel/framework/blob/50303eedf86ec896f7ab2bec2e9d1a7845fd6cd4/src/Illuminate/Database/Eloquent/Factories/Factory.php#L407) on two passes, the first pass evaluates the relationships like in [Factory.php#L413](https://github.com/laravel/framework/blob/50303eedf86ec896f7ab2bec2e9d1a7845fd6cd4/src/Illuminate/Database/Eloquent/Factories/Factory.php#L413) then other types of attributes will be evaluated in the second pass.

**Comment by driesvints** [comment]
If you want to improve this behavior feel free to send in a PR.
