### ISSUE TITLE
Fatal Error in MysqlDriver due to incompatible method signature from interface Doctrine\DBAL\Driver

### ISSUE THREAD

**Issue by duxthefux** [laravel/framework#35553]
- Laravel Version: 8.18.1
- PHP Version: 7.4.12
- Database Driver & Version: MySQL 5.7.28

### Description:
We just upgraded to the latest laravel version and noticed the following fatal error in `src/Illuminate/Database/PDO/MySqlDriver.php` which gets reported from phpstan. 

```
PHP Fatal error:  Declaration of Illuminate\Database\PDO\Concerns\ConnectsToDatabase::connect(array $params) must be compatible with Doctrine\DBAL\Driver::connect(array $params, $username = NULL, $password = NULL, array $driverOptions = Array) in application/vendor/laravel/framework/src/Illuminate/Database/PDO/MySqlDriver.php on line 16
Fatal error: Declaration of Illuminate\Database\PDO\Concerns\ConnectsToDatabase::connect(array $params) must be compatible with Doctrine\DBAL\Driver::connect(array $params, $username = NULL, $password = NULL, array $driverOptions = Array) in application/vendor/laravel/framework/src/Illuminate/Database/PDO/MySqlDriver.php on line 16
```

This currently only happens in phpstan due to
```
protected function getDoctrineDriver()
    {
        return class_exists(Version::class) ? new DoctrineDriver : new MySqlDriver;
    }
```
as it loads the `MysqlDriver`-class.

**Comment by TomHAnderson** [comment]
What version of the DBAL library are you using?

**Comment by driesvints** [comment]
We don't optimize for tools like PHPStan. If you are experiencing a genuine app bug please send in a PR (which you did it seems).

**Comment by duxthefux** [comment]
@driesvints this is not a phpstan error, but a native fatal error from php.

**Comment by driesvints** [comment]
You said: 

> This currently only happens in phpstan
