### ISSUE TITLE
Extra whitespace in the x-syntax

### ISSUE THREAD

**Issue by osbre** [laravel/framework#35551]
- Laravel Version: 8.18.1
- PHP Version: 7.4.13
- Database Driver & Version:

### Description:

Expected output of `welcome.blade.php`:
 `OK`
Current output:
 `O K`

As you can see from files below, the compiler adds extra-whitespace.

Extra whitespace defined there:
https://github.com/laravel/framework/blob/f185be865a/src/Illuminate/View/Compilers/ComponentTagCompiler.php#L233

Is there some way to get rid of that?

### Steps To Reproduce:

`welcome.blade.php`:

```php
O<x-text />
```

`components/text.blade.php`

```php
K
```

**Comment by osbre** [comment]
If I try to manually remove it by using `@component` directive:

`O@component('components.text')@endcomponent` 

The result will be an error.

So, it seems like I must add whitespace:

`O @component('components.text')@endcomponent` 

Result:

`O K`

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/34931
