### ISSUE TITLE
pdo_sqlsrv doctrine2 migration dateTime('field')->change() converts from datetime to datetime2

### ISSUE THREAD

**Issue by senyahnoj** [laravel/framework#35566]
- Laravel Version: 6.0.4
- PHP Version: 7.4.12
- Database Driver & Version: pdo_sqlsrv 5.8.1

### Description:

Wrote an initial migration script to create a not-nullable column:

$table->dateTime('field_name');

This creates a **datetime** data type in the SQL Server database.

Wrote a subsequent migration to change the column to be nullable.

$table->dateTime('field_name')->nullable()->change();

As well as making it nullable it has also changed the data type to be **datetime2**!

I cannot work out how to get the data type back to **datetime** which is what I want.

### Steps To Reproduce:

On an existing table run the following migration

```
/**
 * Migration one create the column
 *
 * @return void
 */
public function up(): void
{
    Schema::table('my_table', function (Blueprint $table) {
        $table->dateTime('my_field');
        // Result is a newly created datetime column
    });
}
```

Then do a second migration to make the column nullable as below

```
/**
 * Migration two modify the column
 *
 * @return void
 */
public function up(): void
{
    Schema::table('my_table', function (Blueprint $table) {
        $table->dateTime('my_field')->nullable()->change();
        // Result is a nullable column but it's changed to a datetime2!
    });
}
```

**Comment by driesvints** [comment]
We use DBAL under the hood so please report this to the doctrine/dbal repo.

**Comment by senyahnoj** [comment]
Surely if the laravel framework uses DBAL "under the hood" this is a laravel framework issue? I am using the database migration methods from laravel after all.

**Comment by driesvints** [comment]
It's not. We don't control this code.

**Comment by senyahnoj** [comment]
My biggest problem is reporting this to doctrine/dbal is that I do not know how to reproduce it without specifically using the laravel framework. I'll give it a go, but I expect they'll tell me it's a problem with laravel.
