### ISSUE TITLE
Validate "image" not working with JPG extension

### ISSUE THREAD

**Issue by wallacemaxters** [laravel/framework#35568]
- Laravel Version: 5.8.38
- PHP Version: 7.2.34-8+ubuntu20.04.1+deb.sury.or

### Description:

I attempt to validate with `'required|image'`, but when image is JPG, always return error in `image` validation.

When i go to the code of `ValidatesAttributes::validateImage`, I see this:

```    /**
     * Validate the MIME type of a file is an image MIME type.
     *
     * @param  string  $attribute
     * @param  mixed   $value
     * @return bool
     */
    public function validateImage($attribute, $value)
    {
        return $this->validateMimes($attribute, $value, ['jpeg', 'png', 'gif', 'bmp', 'svg', 'webp']);
    }

```

[Code in 5.8 tag](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1014)

The error is probably caused because `'jpg'` is not present in `array`, but in [version 6.x](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1057) contains this field.  In addition `$value->guessExtension()` return is `jpg`. 

#### Adicional info

The installed version of `Symfony\Component\Mime` is `symfony/mime@v5.2.0`

**Comment by driesvints** [comment]
5.8 isn't maintained anymore. Please upgrade.

**Comment by wallacemaxters** [comment]
Im solved it installing the the version symfony/mime@5.1.9
