### ISSUE TITLE
Laravel 7 dd() cannot show array collect() result

### ISSUE THREAD

**Issue by dikiwidia** [laravel/framework#35565]
- Laravel Version: 7.30.1
- PHP Version: 7.3.15
- Database Driver & Version: MySQL 5.0.12

### Description:
Hello, i try to check my data array using dd after upgrade from Laravel 6 to 7. 
In Laravel 6.* dd can show on console chrome at Network tabs like a picture 
![image](https://user-images.githubusercontent.com/8361706/101790292-e0282e80-3b34-11eb-8c27-c47ad48d0f92.png)

But on Laravel 7.* console network tab blank like this picture
![image](https://user-images.githubusercontent.com/8361706/101790174-bc64e880-3b34-11eb-8d0d-21c8236d02d3.png)

Any solutions for show value of array in console chrome in Laravel 7 like using Laravel 6 ?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
