### ISSUE TITLE
ResetPasswordController reset method, how can i add some DB validation like check for previuos passwords

### ISSUE THREAD

**Issue by kazantip151** [laravel/framework#35560]
- Laravel Version: 8.15.0
- PHP Version: 7.4.11
- Database Driver & Version: 10.4.14-MariaDB

### Description:
`App\Http\Controllers\ResetPasswordController.php`
Hi, i don't really understand where i can add my validation in front of DB in `ResetPasswordController` in `reset()` method or how can i override this method, i need when user make reset password i need to check for previous passwords in my table that i created for old passwords.

### Steps To Reproduce:
Here in `$request->validate` i want to add validation for previous passwords from my table and i dont know how to implement it here
```
public function reset(Request $request)
    {
        $request->validate($this->rules(), $this->validationErrorMessages());

        // Here we will attempt to reset the user's password. If it is successful we
        // will update the password on an actual user model and persist it to the
        // database. Otherwise we will parse the error and return the response.
        $response = $this->broker()->reset(
            $this->credentials($request), function ($user, $password) {
                $this->resetPassword($user, $password);
            }
        );

        // If the password was successfully reset, we will redirect the user back to
        // the application's home authenticated view. If there is an error we can
        // redirect them back to where they came from with their error message.
        return $response == Password::PASSWORD_RESET
                    ? $this->sendResetResponse($request, $response)
                    : $this->sendResetFailedResponse($request, $response);
    }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
