### ISSUE TITLE
Schema dump fails with prefixed tables (specifically migrations)

### ISSUE THREAD

**Issue by Braunson** [laravel/framework#35586]
- Laravel Version: 8.17.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.32

### Description:
`php artisan schema:dump` does not seem to support databases with prefixes set. It throws this error:

```
vagrant@code-homestead:~/code$ php artisan schema:dump --database=mysql
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: [ERROR] unknown variable 'column-statistics=0'
mysqldump: [Warning] Using a password on the command line interface can be insecure.

   Symfony\Component\Process\Exception\ProcessFailedException

  The command "mysqldump  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --skip-add-locks --skip-comments --skip-set-charset -
-tz-utc --set-gtid-purged=OFF "${:LARAVEL_LOAD_DATABASE}" migrations --no-create-info --skip-extended-insert --skip-routines --compact" failed.

Exit Code: 6(Unknown error)

Working directory: /home/vagrant/code

Output:
================


Error Output:
================
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't find table: "migrations"

  at vendor/symfony/process/Process.php:257
    253▕      */
    254▕     public function mustRun(callable $callback = null, array $env = []): self
    255▕     {
    256▕         if (0 !== $this->run($callback, $env)) {
  ➜ 257▕             throw new ProcessFailedException($this);
    258▕         }
    259▕
    260▕         return $this;
    261▕     }

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Updating the `config/database.php` migrations value with the prefix fixes the issue but wouldn't that affect other areas i.e other areas calling that config variable and prefixing it (again)? I would think I'd only have to prefix the database connection details not the general `migrations` config variable.

### Steps To Reproduce:
- Create a new database
- Update `config/database.php` and your MySQL connection being used with a prefix.
- Run migrations to create the tables
- Run `php artisan schema:dump`

**Comment by Braunson** [comment]
I also noticed that if I was success to run `schema:dump`, the dump file isn't used while testing, it's not run, likely due to it exporting from a `mysql` driver and testing using the `sqlite` driver, but I don't see anywhere to specify the dump file to migrate or how to force it to use the mysql one.

**Comment by taylorotwell** [comment]
Regarding your last comment - you need to use MySQL when running tests. You can't import a MySQL dump into SQLite.

**Comment by Braunson** [comment]
@taylorotwell Thanks, good point. I can put in a PR to fix the the migration table/prefix issue?

**Comment by taylorotwell** [comment]
Sure.

**Comment by Braunson** [comment]
I see `withMigrations` method was added in commit 110eb15a77f84da0d83ebc2bb123eec08ecc19ca by @taylorotwell. I wonder if adding the prefix within that method is preferred or to just update `schemaState` in `DumpCommand.php`?

**Comment by taylorotwell** [comment]
I think DumpCommand could just be updated at this point.

**Comment by taylorotwell** [comment]
I've pushed a fix for this.
