### ISSUE TITLE
Why are jobs not executed on a Redis queue if save is enabled for the Redis service? Is this expected behaviour?

### ISSUE THREAD

**Issue by iamniels** [laravel/framework#35585]
- Laravel Version: 8.18.0
- PHP Version: 7.4.12
- Database Driver & Version: phpredis

### Description:
As soon as I enable save on the Redis service, the jobs are not being executed anymore. The queue worker is still hitting the database. The jobs are still stored in the database. No exceptions, no logs, no console output. 

### Steps To Reproduce:
In Ubuntu:
1. set `save 1 900` in `/etc/redis/redis.conf`
2. Jobs are not being executed anymore

What is the best approach to retain jobs between Redis restarts?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
