### ISSUE TITLE
Chains with failed jobs in batches can make `pending_jobs` and `failed_jobs` seem inconsistent

### ISSUE THREAD

**Issue by Orrison** [laravel/framework#35583]
- Laravel Version: 8.17.2
- PHP Version: 7.4
- Database Driver & Version: MySQL Aurora Serverless 5.7

### Description:

When job chains are added to batches and a job fails that still has other jobs within it's chain, `pending_jobs` and `failed_jobs` can seem inconsistent. This is because `failed_jobs` is only incremented by 1.
Though this may be expected behavior since it is technically only 1 job that failed, some may be confused with the inconsistency between `pending_jobs` and `failed_jobs` and think that some jobs are somehow missing in the batch.

Example:

```php
$batch = Bus::batch([
                new JobThatWillFail(),
                new AnotherJob(),
                new AnotherJob(),
            ])->allowFailures()->dispatch();
```

In the above scenario after processing the batch will have 3 `total_jobs`, 3 `pending_jobs`, but 1 `failed_job`

A couple of fixed I thought of could be:

- Incrementing `failed_jobs` by 1 + "any jobs left in the jobs current chain"
or
- Adding a column something like `jobs_in_failed_job_chain`

Or perhaps this is expected behavior, as truly only one job has failed, the other jobs in the chain have just not been processed due to the failure. If so then perhaps adding a note about this in the [Chains within Batches](https://laravel.com/docs/8.x/queues#chains-within-batches) section of the docs may be helpful.

Curious what the community/Laravel team thinks.

### Steps To Reproduce:

- Create and dispatch a batch containing a job chain in which any but the last job will fail
- Wait for all available jobs to process
- Check `job_batches` table to see `pending_jobs` at a higher value then `failed_jobs`

**Comment by taylorotwell** [comment]
I'm not sure we would want to increment failed jobs any higher than the number of actual failed jobs.

**Comment by Orrison** [comment]
> I'm not sure we would want to increment failed jobs any higher than the number of actual failed jobs.

Yeah that makes sense, it could be helpful to possibly add some info in the docs about this situation. Would that be alright?
