### ISSUE TITLE
When displaying validation error on form fields all filled fields are becoming empty, 

### ISSUE THREAD

**Issue by srimani282** [laravel/framework#35598]
- Laravel Version:^0.8.7
- PHP Version:^7.3|^8.0
- Database Driver & Version:

When displaying validation error on form fields all filled fields are becoming empty,  one form with 4 fields and other form with around 100 fields and It will be very difficult for the user to re enter, and when I click back button i am getting back filled fileds with error messages,

I have tried validatiing both on Request Object as well as validate function in controller,

![Screenshot from 2020-12-14 17-07-42](https://user-images.githubusercontent.com/53419199/102077298-10bae180-3e2f-11eb-9bd5-f02c0a77940d.png)
![Screenshot from 2020-12-14 17-08-15](https://user-images.githubusercontent.com/53419199/102077313-16b0c280-3e2f-11eb-83fe-24b9cecfc733.png)

**Comment by srimani282** [comment]
if u see the screenshot I have filled Name and phone left other 2 fields, even those two have become empty after validation

**Comment by emargareten** [comment]
https://laravel.com/docs/8.x/requests#retrieving-old-input

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by srimani282** [comment]
Hi there, 
thanks that helped me a lot.

Best Regards,
Sri Mani.

**Comment by srimani282** [comment]
Hi there,
Its working but for file field and select fields it is still becoming blank, Can you please tell me how do I handle that,
