### ISSUE TITLE
RedisException MOVED when config to use  Redis Cluster 

### ISSUE THREAD

**Issue by tititorn** [laravel/framework#35600]
- Laravel Version: 8.18.1
- PHP Version: 7.4.13
- Database Driver & Version:
- phpRedis Driver & Version: 5.3.2
- Redis Server Version: 5.0.3 

### Description:
When config laravel to connect to Redis Cluster with the following config/database.php

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'clusters' => [
                'default' => [
                        'host' => env('REDIS_HOST', '127.0.0.1'),
                        'password' => env('REDIS_PASSWORD', null),
                        'port' => env('REDIS_PORT', '6379'),
                        'database' => env('REDIS_DB', '0'),
                ],
                'options' => [
                        'cluster' => env('REDIS_CLUSTER', 'redis'),
                ],
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],

### Steps To Reproduce:
When config to connect to standalone Redis, it work fine. But when config to connect to Redis Cluster, there is RedisExecption MOVED.

**Comment by driesvints** [comment]
There's not a lot of info here I'm afraid. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
