### ISSUE TITLE
Has break on custom DB connection

### ISSUE THREAD

**Issue by usmanjdn93** [laravel/framework#35618]
- Laravel Version: #.#.# 8.18.1
- PHP Version: #.#.# 7.4
- Database Driver & Version: MySQL 5.7.32

### Description:

Had two models (menu, service) with two different databases, connection set in model. when I get menu with (service), I get the result. But when used `has(service)` to get the menu which have service will shown 
`Base table or view not found: 1146 Table 'common.services' doesn't exist` 

it will look in my first database 

common is my first database name and services are store in second database.

### Steps to Reproduce:

create two model in different database
fetch `menu` with relation `has(service)` to get only menu which have service

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
