### ISSUE TITLE
Please guys put a button to go back to the top of the page on your documentation....

### ISSUE THREAD

**Issue by HamzaInPerth** [laravel/framework#35612]
Everything is on the title, delete this bug report after reading.

**Comment by browner12** [comment]
These has been requested and discussed many times. Not gonna happen. Use CMD + UP arrow, or your OS's equivalent.

**Comment by HamzaInPerth** [comment]
Thank you, didnt know this.

**Comment by browner12** [comment]
No problem.

Adding links for reference.

https://twitter.com/taylorotwell/status/1037443554614882309
https://twitter.com/taylorotwell/status/954082318662107136
