### ISSUE TITLE
Job delay ignored when using batches

### ISSUE THREAD

**Issue by pr4xx** [laravel/framework#35619]
- Laravel Version: 8.18.1
- PHP Version: 7.4.13
- Database Driver & Version: MariaDB / Redis
- Horizon

### Description:

When dispatching a queueable job directly via `dispatch($job)` after adding a delay with `$job->delay(now()->addMinute()` everything works as intended. I can see that the job will be handled by horizon after one full minute.
But when using `Bus::batch([$job])->dispatch();` with the same job and added delay, the job will be processed immediately by horizon.

### Steps To Reproduce:
- create job class with `Batchable` trait and `ShouldQueue` interface
- create new instance of said job and add delay on that object
- use the `Batch` facade to batch that job
- monitor queue progress and see that the job will be processed instantly

**Comment by themsaid** [comment]
This is the expected behaviour. You may dispatch a delayed job that dispatches the batch if you want to delay processing all jobs of the batch.

**Comment by pr4xx** [comment]
Thanks for clarification!
For anyone finding this and implementing the suggested extra job which creates and dispatches the batch with delay:
I was now getting out of memory messages: `Allowed memory size of 536870912 bytes exhausted`.
I pinned it down to a call to `serialize($batch->options)` within the DatabaseRepository when calling `dispatch()` on the batch.
I think the resulting memory issue is somewhat related to this issue: #23505
I am using an eloquent model as a protected property on the new job, handed over in the constuctor.
My workaround was to not accept the model itself, but the primary key instead. Then using find in the jobs handle method.

**Comment by generalov-viktar** [comment]
> Thanks for clarification!
> For anyone finding this and implementing the suggested extra job which creates and dispatches the batch with delay:
> I was now getting out of memory messages: `Allowed memory size of 536870912 bytes exhausted`.
> I pinned it down to a call to `serialize($batch->options)` within the DatabaseRepository when calling `dispatch()` on the batch.
> I think the resulting memory issue is somewhat related to this issue: #23505
> I am using an eloquent model as a protected property on the new job, handed over in the constuctor.
> My workaround was to not accept the model itself, but the primary key instead. Then using find in the jobs handle method.

I create pull request to fix this bug
https://github.com/laravel/framework/issues/35619#issuecomment-745494705

**Comment by shreyanshp-cactus** [comment]
@pr4xx  Can you not use `RateLimiter` [https://laravel.com/docs/9.x/queues#job-middleware](https://laravel.com/docs/9.x/queues#job-middleware)
Instead of trying to delay the job?

Assuming if your only motive is some sort of throttling.
