### ISSUE TITLE
Laravel 8 cannot  show dd() the array result

### ISSUE THREAD

**Issue by dirszas14** [laravel/framework#35628]
- Laravel Version: 8.19.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL & v 5.7

### Description:

Hello i just try to return the dd() function but i didnt show the value like the previous laravel version
![image](https://user-images.githubusercontent.com/31124351/102329042-75567780-3fba-11eb-8144-6ef83bc59875.png)

it shoud be return like this

![image](https://user-images.githubusercontent.com/31124351/102328222-5c999200-3fb9-11eb-8dab-f75805d65443.png)

i hope you can fix this ASAP. thank you!

**Comment by gmutinel** [comment]
The problem is in symfony/var-dumper, and isse is alread opened there: https://github.com/symfony/symfony/issues/39394
