### ISSUE TITLE
Fluent Strings doesn't work with each() function.

### ISSUE THREAD

**Issue by pixieaka** [laravel/framework#35638]
- Laravel Version: 8.18.1
- PHP Version: 8.0.0
- Database Driver & Version: 10.4.17-MariaDB

### Description:
Fluent Strings doesn't work with each() function.

### Steps To Reproduce:
```
return User::take(2)->get()->each(function(User $user) {
    $user->emailOnly = Str::of($user->email)->before('@');

    return $user;
});
```
### Result
![image](https://user-images.githubusercontent.com/17777237/102421894-36eaa800-400e-11eb-8849-26d89a743098.png)

### Work Fine
```
return User::take(2)->get()->each(function(User $user) {
    $user->emailOnly = Str::before($user->email, '@');

    return $user;
});
```
### Result
![image](https://user-images.githubusercontent.com/17777237/102422019-803af780-400e-11eb-9ada-826514d64bbb.png)

**Comment by filkris** [comment]
It works fine but you can not use Fluent strings in that fashion.

Take a look in [Str](https://github.com/illuminate/support/blob/master/Str.php) class on [L50](https://github.com/illuminate/support/blob/master/Str.php#L50). The `of` method returns a new [Stringable](https://github.com/illuminate/support/blob/master/Stringable.php) class. On [L741](https://github.com/illuminate/support/blob/master/Stringable.php#L741) there is a `__toString()` method. 

You should call `toString()` at the end.

```php
return User::take(2)->get()->each(function(User $user) {
    $user->emailOnly = Str::of($user->email)->before('@')->toString();

    return $user;
});
```

**Comment by pixieaka** [comment]
@filkris [L108](https://github.com/illuminate/support/blob/master/Str.php#L108) Before function return string.

Example:
```
public function index()
{
    return Str::of('Test@github.com')->before('@');
}
```
It's work fine without `__toString()`.
![image](https://user-images.githubusercontent.com/17777237/102441972-04e83e80-402c-11eb-9a4d-a3d0cf820911.png)

**Comment by crynobone** [comment]
You can't compare the 2 exactly the same.

`Fluent` implements `JsonSerializable` and `Jsonable` so the response is converted to json. And since `Stringable` is an object it return `{}`.

`Stringable` by itself just an object. So it got converted to string from the `Response` object. 

https://github.com/laravel/framework/blob/7365e4459c2ef048ea9cfe23f515b73695549f92/src/Illuminate/Routing/Router.php#L764-L787

**Comment by driesvints** [comment]
See the above.

**Comment by pixieaka** [comment]
Thanks guys for explanation. @crynobone @driesvints @filkris
