### ISSUE TITLE
[8.x] MaintenanceModeException is not thrown on maintenance mode

### ISSUE THREAD

**Issue by vigneshgurusamy** [laravel/framework#35635]
- Laravel Version: 8.18.1
- PHP Version: 7.4.13

### Description:

After executing `php artisan down` command on laravel 8.x, it does not throw `MaintenanceModeException` on the user request instead it throws `HttpException`.

Still middleware phpdoc, [laravel documentation](https://laravel.com/docs/8.x/configuration#maintenance-mode) mentions that laravel will throw `MaintenanceModeException` on maintenance mode.

https://github.com/laravel/framework/blob/7365e4459c2ef048ea9cfe23f515b73695549f92/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php#L36-L47

**Note**: This change was not captured in [laravel 8.x upgrade guide](https://laravel.com/docs/8.x/upgrade#maintenance-mode-updates).

**Comment by taylorotwell** [comment]
I'll update doc block and docs.

**Comment by jamespavett** [comment]
Hello, just wanted to mention that this issue is actually still live. Want to make sure it doesn't get missed as it caused me some issues today.

**Comment by XGhozt** [comment]
Was this ever fixed? I ran into this today.

**Comment by kristijorgji** [comment]
I get HttpClientException with status code 503 but no other information like remaining time for maintenance like I could get with  `MaintenanceModeException` that exposed `willBeAvailableAt` and `wentDownAt`

How can I get those fields where are not present in HttpClientException!

**Comment by csimpi** [comment]
Now how can I catch it if it throws a `HttpClientException`? Seems Taylor didn't use it so it's considered redundant feature :D
