### ISSUE TITLE
joinSub -> Property [from] does not exist on the Eloquent builder instance.

### ISSUE THREAD

**Issue by OliverZiegler** [laravel/framework#35631]
- Laravel Version: 8.19.0
- PHP Version: 7.14.10
- Database Driver & Version: mysql 5.7.31

### Description:

when calling `joinSub` with a Model query (instance of `Eloquent\Builder`) we run in an error:
`Property [from] does not exist on the Eloquent builder instance.`

Seems like I ran into the same issue like described in #34249 and could trace it down to the following.

`Query\Builder->joinSub` calls `Query\Builder->createSub` where  `Query\Builder->parseSub` gets called.

```php
protected function parseSub($query)
    {
        if ($query instanceof self || $query instanceof EloquentBuilder || $query instanceof Relation) {
            $query = $this->prependDatabaseNameIfCrossDatabaseQuery($query);

            return [$query->toSql(), $query->getBindings()];
        } elseif (is_string($query)) {
            return [$query, []];
        } else {
            throw new InvalidArgumentException(
                'A subquery must be a query builder instance, a Closure, or a string.'
            );
        }
    }
```

Here it also checks for an `EloquentBuilder` and passes it down to `prependDatabaseNameIfCrossDatabaseQuery`.

```php
protected function prependDatabaseNameIfCrossDatabaseQuery($query)
    {
        if ($query->getConnection()->getDatabaseName() !==
            $this->getConnection()->getDatabaseName()) {
            $databaseName = $query->getConnection()->getDatabaseName();

            if (strpos($query->from, $databaseName) !== 0 && strpos($query->from, '.') === false) {
                $query->from($databaseName.'.'.$query->from);
            }
        }

        return $query;
    }
```

But if `$query` here is not an `Query\Builder` but an `Eloquent\Builder` we cannot access `$query->from`.
My IDE tells me it is available (as `Query\Builder` is `@mixin \Illuminate\Database\Query\Builder` in the PHP Doc comments of `Eloquent\Builder`, but I cannot get how PHP should get access to the mixed in properties.
The `ForwardCalls` Trait makes only functions available, but not properties and in the `__get` only `orWhere` is a magic property.

As for now I could workaround by calling `$query->toBase()` when using it in `joinSub` but the main issue is still present in the laravel core I think.

**Comment by taylorotwell** [comment]
Can you call the `from` method? Please share the entire query you are trying to create?

**Comment by sauladam** [comment]
I actually ran into the same issue with a subselect today after upgrading from Laravel 5.8 to Laravel 8.

We have a Partner, a partner hasMany Sales, and I want to add a column with the total sales while fetching a Partner:

`Partner::withRecentSales()`

```php
// Partner.php

public function scopeWithRecentSales($query)
{
  $query->select('*')
        ->selectSub(Sales::lastDays(30)->forCurrentPartner(), 'sales');
}
```

This was working fine before with Laravel 5.8, after upgrading to Laravel 8 it failed with `Property [from] does not exist on the Eloquent builder instance.`

The sub-select has another subquery and there are multiple databases involved.

```php
// Sales.php

public function scopeForCurrentPartner($query)
{
  $query->addSelect(DB::raw('...'))
    ->whereIn('product_number', function ($qry) {
        $qry->from(...)
            ->select('sku')
            ->whereRaw(...);
    });
}
```

But I'm not sure this is even relevant. The interesting part that it works fine in Laravel 8 as soon as I `toBase()` the subselect as OP mentioned:

```php
 $query->select('*')
        ->selectSub(Sales::lastDays(30)->forCurrentPartner()->toBase(), 'sales');
```
I'm not sure how much of an issue that is, just wanted to share it in case somebody gets sent here by Google.

**Comment by thisiskj** [comment]
@sauladam Thanks for posting that. I just ran into the same problem and `->toBase()` fixed it for me.

**Comment by Sparkinzy** [comment]
I found something is wrong in Builder ,I have solved this errror and push a PR 


[Fix bug on Cross database Query](https://github.com/laravel/framework/pull/38629)
