### ISSUE TITLE
Factory hasAttached method and custom pivot table model

### ISSUE THREAD

**Issue by illambo** [laravel/framework#35642]
- Laravel Version: ^8.0
- PHP Version: 7.4
- Database Driver & Version: -

### Description:
Using factory [hasAttached](https://laravel.com/docs/8.x/database-testing#pivot-table-attributes) method with [custom pivot table model](https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models) seems doesn't take the right defined table.

### Steps To Reproduce:

```php
class Match extends Model
{
    use HasFactory;

    // [...]

    /**
     * @return BelongsToMany
     */
    public function missions(): BelongsToMany
    {
        return $this->belongsToMany(Mission::class)
            ->as('planned_mission')
            ->using(PlannedMission::class)
            ->withPivot(['data'])
            ->withTimestamps();
    }

   // [...]
}

class Mission extends Model
{
   use HasFactory;

   //[...]
}         

class PlannedMission extends Pivot
{
   // [...]

   /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'planned_missions';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    // [...]
}

Match::factory()
   ->hasAttached(
       Mission::factory()->count(3),
       ['data' => null],
       'missions' // try with or without throw the same error
   )
   ->create();
```

Throw error: _Illuminate\Database\QueryException_ 

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge.match_mission' doesn't exist (SQL: insert into `match_mission` (`mission_id`, `match_id`, `created_at`, `updated_at`, `data`) values (2, 7, 2020-12-17 09:34:31, 2020-12-17 09:34:31, ?))

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by illambo** [comment]
Hi, thanks for the reply, I know there are other ways to achieve my goal (in fact I have already solved it in another way) but what I noted is a bug or not?

Thanks

**Comment by illambo** [comment]
Ok, I address the [issue](https://laracasts.com/discuss/channels/laravel/factory-hasattached-method-and-custom-pivot-table-model-seems-dont-take-the-right-table) on Laracasts.

**Comment by illambo** [comment]
Ehi @driesvints in order to work you need "force" the table name in the relationship like this:
```php
/**
 * @return BelongsToMany
 */
public function missions(): BelongsToMany
{
    return $this->belongsToMany(Mission::class, (new PlannedMission)->getTable())
        ->as('planned_mission')
        ->using(PlannedMission::class)
        ->withPivot(['data'])
        ->withTimestamps();
}
```
But in my opinion it is a forcing, it creates confusion and doesn't use the appropriate method `->using(...)`.

Consider whether to reopen the issue,
thanks!
