### ISSUE TITLE
Can't to get SCHEDULE_CACHE_DRIVER parameters from env

### ISSUE THREAD

**Issue by SOLAGURT** [laravel/framework#35640]
Laravel Version: 6.20.3
PHP Version: 7.4.7

https://github.com/laravel/framework/blob/7365e4459c2ef048ea9cfe23f515b73695549f92/src/Illuminate/Foundation/Console/Kernel.php#L114

Always return null when caching config.

I want you to get it from config without using the env.
```
return $this->app['config']['cache.schedule_driver']
```

**Comment by taylorotwell** [comment]
Please docs about environment variables and caching.

**Comment by taylorotwell** [comment]
Will retrieve from `cache.schedule_store` and fall back to environment variable if that doesn't exist.
