### ISSUE TITLE
Getting DirectoryNotFoundException with migrate:refresh --path=specified

### ISSUE THREAD

**Issue by yazeed** [laravel/framework#35652]
- Laravel Version: ^8.0
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL 12.4

### Description:

Getting DirectoryNotFoundException with migrate:refresh --path=database/migrations/migration_filename_specified.php

### Steps To Reproduce:

1. Request to migrate a specific file.
2. Error says directory not found even though the path is correct and points to a specific file, not a directory.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
