### ISSUE TITLE
Laravel 8.x Factories - make() doesn't insert an entry into DB

### ISSUE THREAD

**Issue by leo-vannini-granicus** [laravel/framework#35666]
I'm in the process of upgrading to Laravel 8.x, and i've run into an issue where my model/factories don't generate an id field or entries in the test database after the call to make().

Take the following code for example...

Model:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Camera extends Model
{
    use HasFactory;

    protected $connection = 'mysql.client';
    protected $table = 'camera';

    public $timestamps = false;
}
```

Factory:
```
<?php

namespace Database\Factories;

use App\Models\Camera;
use Illuminate\Database\Eloquent\Factories\Factory;

class CameraFactory extends Factory
{
    protected $model = Camera::class;

    public function definition()
    {
        return [
            'name' => $this->faker->word,
        ];
    }
}
```

Test file:
```
<?php declare(strict_types=1);

namespace Tests\Services;

use App\Models\Camera;
use Tests\TestCase;

final class ExampleTest extends TestCase
{
    public function test_getAll()
    {
        $camera = Camera::factory()->make();
        $this->assertSame(1, $camera->id);
    }
}
```

This assertion fails. If I debug and break after the make() function, I see no object inserted into the DB. I've added a save() call after the make, which does in fact insert the entry into the DB, but then my return value is true (because the save() succeeded).

In previous iteration of Laravel, the factories performed an insert and returned the model with a valid id back. Am I missing something with upgrading? Is there anyway to make() a factory model, insert it, and get the object back in one line anymore?

Thanks in advance for all the help.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rodrigopedra** [comment]
I guess you are after `->create()` not `->make()`.

Even on Laravel 7 `->make()` does not save to the database. Docs from Laravel 7:

> the `make` method to create models but not save them to the database:

Reference: https://laravel.com/docs/7.x/database-testing#creating-models

**Comment by leo-vannini-granicus** [comment]
> I guess you are after `->create()` not `->make()`.
> 
> Even on Laravel 7 `->make()` does not save to the database. Docs from Laravel 7:
> 
> > the `make` method to create models but not save them to the database:
> 
> Reference: https://laravel.com/docs/7.x/database-testing#creating-models

This is totally the answer. Much thanks again!
