### ISSUE TITLE
Mail::to does not respect name parameter, but Mailable::to respects

### ISSUE THREAD

**Issue by mabasic** [laravel/framework#35687]
- Laravel Version: 7.30.0
- PHP Version: 7.4.13
- Database Driver & Version: sqlite

### Description:

This does not set the recipient name:

```
Mail::to('test@test.com', 'name')->send(new MessageCreated($message));
```

but this does:

```
...

class MessageCreated extends Mailable
{
    ...

    public function build()
    {
        $this->to('test@test.com', 'name');

        return $this->markdown('emails.messages.created');
    }
}

```

### Steps To Reproduce:

See above.

I'm trying to install xDebug find the reason why this happens. For some reason `name` is not even passed to the Mail::to method even when I hard code it, but it is passed on `$this->to(` method inside the Mailable class.

If I pass an object like so:

```
Mail::to((object) [
    'name' => 'test',
    'email' => 'test@test.com'
])
```

then it works.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by mabasic** [comment]
Same behavior on version `8.5.5` except that on `8.5.5` the method signature for `Mail::to` only accepts $users mixed. Mailable::to() still accepts email and name.

**For people who stumble upon this issue:**

Use:

```
Mail::to((object) [
    'name' => 'test test',
    'email' => 'test@test.com'
])
```

**Comment by driesvints** [comment]
@mabasic that's correct. `Mail::to('test@test.com', 'name')` has never been valid syntax.
