### ISSUE TITLE
redirect is not working inside Exceptions/Handler.php

### ISSUE THREAD

**Issue by VeRJiL** [laravel/framework#35681]
- Laravel Version: 7.24
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:
I am trying to redirect user to a specific route (return Redirect()->route('routeName');) but this is not working.

### Steps To Reproduce:
1. create a new custom exception class with custom properties and methods.
2. throw the new created exception
3. inside handler write these code
```
    public function render($request, Throwable $exception)
    {
        if ($request->wantsJson()) {
            return $this->handleCustomExceptionJsonFormat($exception);
        }

        $this->handleCustomWebException($request, $exception);
    }

    public function handleCustomWebException(Request $request, Throwable $exception)
    {
        switch (get_class($exception)) {
            case EntityNotFoundException::class:
                flash()->warning($exception->getMessage());
                return redirect()->route($exception->getRedirectRoute());
            break;

            default:
                return parent::render($request, $exception);
        }
    }
```

4. make a request to the endpoint which wont contain the entity and white screen appears instead of redirecting user to the route.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
