### ISSUE TITLE
Calling $this->fail() from within a Job doesn't stop execution

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [laravel/framework#35684]
- Laravel Version: 8.19.0
- PHP Version: 7.4.11
- Database Driver & Version:

### Description:
The documentation is not quite clear on this, but I would assume calling $this->fail() on a Job would stop execution immediately

### Steps To Reproduce:
Create a new Job:

```
public function handle(){
  echo 'start';
  $this->fail();
  echo 'stop';
}
```

Running this in a queue worker will still echo out 'stop' after failing

```
[2020-12-21 11:50:06][53] Processing: App\Jobs\TestJob
start
[2020-12-21 11:50:07][53] Failed:     App\Jobs\TestJob
stop
[2020-12-21 11:50:07][53] Processed:  App\Jobs\TestJob
```

**Comment by driesvints** [comment]
Feel free to send in a PR to the docs if you feel this isn't clear 👍

**Comment by AntonioDiPassio-AppSys** [comment]
So you're saying this is the intended functionality? What is the purpose of this function then? Would it not be better to throw an exception instead?

**Comment by driesvints** [comment]
You're suppose to stop code execution yourself.
