### ISSUE TITLE
foreignIdFor throw exception with pivot model

### ISSUE THREAD

**Issue by hsmfawaz** [laravel/framework#35688]
- Laravel Version: 8.19.0
- PHP Version: 7.4.13
- Database Driver & Version:sqlite & mysql 5.6

### Description:
using foreignIdFor will throw 
`TypeError: Argument 1 passed to Doctrine\Inflector\Inflector::pluralize() must be of the type string, null given`
**if the given model was a pivot model created by**
`php artisan make:model UserRole -m --pivot`
example
```PHP
//2020_12_21_203640_create_user_role_table.php
public function up()
 {
        Schema::create('user_role', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
        });

 }

//2020_12_21_203845_create_activities_table.php

public function up()
 {
        Schema::create('activities', function (Blueprint $table) {
            $table->id();
            $table->string('body');
            $table->foreignIdFor(\App\Models\UserRole::class)
                ->nullable()
                ->constrained()
                ->nullOnDelete();
            $table->timestamps();
    });
 }

```
### Steps To Reproduce:
Test generated here : 
https://github.com/hsmfawaz/laravel_contributions/commit/341b9b057e1b07181ccd7fd09e8ec189599bd8a0

**Comment by taylorotwell** [comment]
Guess it doesn't support pivot models.
