### ISSUE TITLE
Contextual and primitive binding in service provider does not work with handle-like classes

### ISSUE THREAD

**Issue by stemis** [laravel/framework#35695]
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:
When registering dependencies in the service provider, it is not picked up when the `handle` method is used in for example jobs.
### Steps To Reproduce:

ServiceProvider.php
```php
$this->app->when(MyJob::class)
          ->needs('$financeFilesystem')
          ->give(function () {
              return Storage::disk('finance');
          });
$this->app->when(MyJob::class)
          ->needs('$configVar1')
          ->give(function (ConfigRepository $configRepository) {
              return $configRepository->getVar1();
          });
```

Handle-like class
```php
class MyJob() {
  __construct($var2) {}

  public function handle(Filesystem $financeFilesystem, int $configVar1) {
  
  }
}

MyJob::dispatchSync(2);
```

```
Illuminate/Contracts/Container/BindingResolutionException with message 'Unable to resolve dependency [Parameter #1 [ <required> int $configVar1]] in class MyJob'
```

It does seem logical that the service provider should know how to resolve this. It is able to resolve the Filesystem, however, this is just the regular Filesystem, the service provider closure is never called.

Is this simply not supported (yet) or is there a way to do this?

**Comment by driesvints** [comment]
Method binding isn't supported here.
