### ISSUE TITLE
Bus::fake single job class will cause Bus::batch not work.

### ISSUE THREAD

**Issue by bolechen** [laravel/framework#35693]
- Laravel Version: v8.19.0
- PHP Version: 7.4.13

### Description:

Bus::fake single job class will  cause Bus::batch not work.

### Steps To Reproduce:

```php
<?php
// TestCase
    protected function setUp(): void
    {
        Bus::fake([SomeJobNeedFake::class]);
    }
?>
```

```php
<?php
$batch = Bus::batch([])->dispatch();
$batch->add([new AnotherJob()]);

// AnotherJob not execute!
?>


Sorry English is not my native language, if more information is needed I will be happy to provide it.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by bolechen** [comment]
@driesvints i make a fresh install laravel to reproduce this, could u have time to look? very thx. https://github.com/bolechen/busfake-bug

more info at https://github.com/bolechen/busfake-bug/issues/1

**Comment by driesvints** [comment]
Please try a support channel from above.

**Comment by bolechen** [comment]
My test is like this, I ask this to stack-overflow & Discord, but no one have know why this. :(

```php
class ExampleTest extends TestCase
{
    public function testBusFake()
    {
        Bus::fake([NeedFakeJob::class]);

        Bus::batch([
            new NeedFakeJob(),
            new NormalJob(),
        ])->dispatch();

        Bus::assertDispatched(NeedFakeJob::class);
    }
}
```
