### ISSUE TITLE
Passport actingAs test method broken in 8.20.0

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel/framework#35696]
- Laravel Version: 8.20.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL

### Description:
#35692 introduced a breaking change. The Passport::actingAs() method is no longer working in 8.20.0. Reverting that commit fixes the issue for us.

### Steps To Reproduce:
1. Install Laravel 8.20.0
2. Install Passport 4.x
3. Write test using Passport::actingAs($user);
4. Test will fail with a 401 Unauthenticated error.

**Comment by lo00l** [comment]
Also it breaks `actingAs()` method in `Illuminate\Foundation\Testing\Concerns\InteractsWithAuthentication` trait.
Also test fails with 401 error.

**Comment by psprokofiev** [comment]
+1
Looks like cause of it
https://github.com/laravel/framework/commit/0d601f598a2434b8b126c06af75a0f089b10a102

**Comment by driesvints** [comment]
We reverted this. Thanks
