### ISSUE TITLE
'HEADER_X_FORWARDED_ALL' is deprecated | TrustProxies

### ISSUE THREAD

**Issue by pixieaka** [laravel/framework#35700]
- Laravel Version: 8.20.0
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
![image](https://user-images.githubusercontent.com/17777237/102950615-a57aaa80-44d3-11eb-90a0-5c829ef06efa.png)

### Steps To Reproduce:
'HEADER_X_FORWARDED_ALL' is deprecated | TrustProxies

**Comment by driesvints** [comment]
This is a depreciation notice. Nothing is broken.

**Comment by browner12** [comment]
https://laravel.com/docs/9.x/upgrade#updating-dependencies

composer remove fideloper/proxy
