### ISSUE TITLE
Symfony\Component\Console\Exception\RuntimeException: Not enough arguments after updateing to 8.19 

### ISSUE THREAD

**Issue by error-400-byte** [laravel/framework#35709]
- Laravel Version: 8.19.0
- PHP Version: 7.4.13

### Description:
Getting this random issue after update to 8.19.0

### Steps To Reproduce:
1. Create command with any name 'user_signup'
2. Add this code Artisan::queue('user_signup', ['id' => 1 ]);

**Comment by taylorotwell** [comment]
Unable to reproduce using your steps.
