### ISSUE TITLE
Http client returns null on invalid json using the json-method with no way to check if the decoding of the json is valid

### ISSUE THREAD

**Issue by crissi** [laravel/framework#35716]
- Laravel Version: 7.22.3
- PHP Version: 7.4

### Description:
If **Http::get('http://someurl')->json()** is used and invalid json is sent it will always return null and with no way to check if the decoding of the json is valid.

I ran into this issue after an external API suddently started sending invalid JSON. In my case it was a BOM-character in front of the json, but is relevant for any responses expected to be json and turning out to sending invalid json.

The reason why this happens is because the json() method does not check if the json is decoded correctly and just return the result of json_decode.

The Http client does not throw errors as a starting point, only when the **throw**-method is used(). 

So do we want it to throw on invalid json when using the json() and no throw()-method?

or should the throwing on json error be handed else where?

### Steps To Reproduce:
       Run Http::get('http://someurl/that/returns/invalid/json')->throw()->json() 
      // and you will receive null for any invalid json response.

**Comment by taylorotwell** [comment]
I don't think we will change this behavior atm. If you want to work around this you can check for `null` in your own code and throw whatever error you want.

**Comment by crissi** [comment]
Okay,

In my case that endpoint would actually return null or json object for different cases, now it was just returning null all the time.

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Taylor Otwell <notifications@github.com>
Sendt: Friday, December 25, 2020 6:38:29 PM
Til: laravel/framework <framework@noreply.github.com>
Cc: Christian <c2n@live.dk>; Author <author@noreply.github.com>
Emne: Re: [laravel/framework] Http client returns null on invalid json using the json-method with no way to check if the decoding of the json is valid (#35716)


I don't think we will change this behavior atm. If you want to work around this you can check for null in your own code and throw whatever error you want.

**Comment by rodrigopedra** [comment]
Hi @crissi , I just had a similar problem, but as `\Illuminate\Http\Client\Response` is macroable I added this macro to my `AppServiceProvider@boot` method:

~~~php
\Illuminate\Http\Client\Response::macro('validJson', function ($key = null, $default = null) {
    if (! $this->decoded) {
        $this->decoded = json_decode($this->body(), true, 512, JSON_THROW_ON_ERROR);
    }

    return $this->json($key, $default);
});
~~~

And then I call it like this:

~~~php
$data = Http::get('http://someurl/that/returns/invalid/json')->throw()->validJson();
~~~

Thought it could help.

**Comment by crissi** [comment]
Thanks man👍

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Rodrigo Pedra Brum <notifications@github.com>
Sendt: Tuesday, December 29, 2020 3:01:07 AM
Til: laravel/framework <framework@noreply.github.com>
Cc: Christian <c2n@live.dk>; Mention <mention@noreply.github.com>
Emne: Re: [laravel/framework] Http client returns null on invalid json using the json-method with no way to check if the decoding of the json is valid (#35716)


Hi @crissi<https://github.com/crissi> , I just had a similar problem, but as \Illuminate\Http\Client\Response is macroable I added this macro to my AppServiceProvider@boot method:

\Illuminate\Http\Client\Response::macro('validJson', function ($key = null, $default = null) {
    if (! $this->decoded) {
        $this->decoded = json_decode($this->body(), true, 512, JSON_THROW_ON_ERROR);
    }

    return $this->json($key, $default);
});

And then I call it like this:

$data = Http::get('http://someurl/that/returns/invalid/json')->throw()->validJson();

Thought it could help.
