### ISSUE TITLE
`EnsureEmailIsVerified` has changed behavior

### ISSUE THREAD

**Issue by skollro** [laravel/framework#35718]
- Laravel Version: 8.20.1
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
[This commit](https://github.com/laravel/framework/commit/422b8487b18ab000bf1124ab42490499d90b7151#diff-a596e43462232399e8c072a5d859c7faa904b92066ba3ced0d321273bbaf4269) has changed the behavior of the `EnsureEmailIsVerified` middleware.

If `url.intended` is already present, its value is overridden and we are redirected to the default route instead. This was not the case prior to 8.10.0.

**Comment by taylorotwell** [comment]
Probably no plans to revert this.
