### ISSUE TITLE
@auth @elseauth and @endauth not working for guest user

### ISSUE THREAD

**Issue by rajjanorkar** [laravel/framework#35726]
- Laravel Version: 8.20.1
- PHP Version: 7.3.19
- Database Driver & Version: MySQL 8

### Description:

```
@auth 
dd('Authenticated');
@elseauth 
dd('Guest');
@endauth 
```

This does not work. It never goes in @elseauth section for not logged in user.

### Steps To Reproduce:
Please see above.

**Comment by rodrigopedra** [comment]
Use `@elseguest`

~~~
@auth 
    @dd('Authenticated')
@elseguest
    @dd('Guest')
@endauth 
~~~

**Comment by rajjanorkar** [comment]
Thank you, 

isn't that `@elseguest `should go in 
```

@guest 
.. 
@elseguest 
.. 
@endguest
```

**Comment by rodrigopedra** [comment]
No,

`@elseauth` compiles to `<?php elseif(auth()->guard{$guard}->check()): ?>`

https://github.com/laravel/framework/blob/aae5c4acf3492ffac107ac2e466914e455623da8/src/Illuminate/View/Compilers/Concerns/CompilesConditionals.php#L35-L40

And `@elseguest` compiles to  `<?php elseif(auth()->guard{$guard}->guest()): ?>`

https://github.com/laravel/framework/blob/aae5c4acf3492ffac107ac2e466914e455623da8/src/Illuminate/View/Compilers/Concerns/CompilesConditionals.php#L112-L117

I personally think it reads better the way it is:

~~~blade
@auth {{-- If user is authenticated --}}
    ...
@elseguest {{-- else, If user is a guest --}}
    ...
@endauth 
~~~

**Comment by rajjanorkar** [comment]
Thank you @rodrigopedra 
I had been using it wrongly then.

Naturally i thought this is how it should be  used. (@auth @elseauth @endauth same for @guest...), but i was wrong.
Thank you once again for clarifying.
