### ISSUE TITLE
Batch with Job Chaining on specified queue does not seem to be working

### ISSUE THREAD

**Issue by streamingsystems** [laravel/framework#35739]
- Laravel Version: 8.20.1
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Description:

Hello,

I am implementing some code using the new batch queue processing (using chains). I am seeing something odd and wanted to see if I was doing anything wrong.

I am running a simple test using the code below I would expect all my Jobs to all run on 'my-queue'.

What I am seeing is the TestJob1's both run on the correct queue (my-queue), however TestJob2 is running on the default queue.

```
$batch = Bus::batch([
            [
                new TestJob1(),
                new TestJob2(),
            ],
            [
                new TestJob1(),
                new TestJob2(),
            ]
        ])->then(function (Batch $batch) {
           
        })->catch(function (Batch $batch, Throwable $e) {
            
        })->finally(function (Batch $batch) {
            
        })->allowFailures()->onQueue('my-queue')->dispatch();
```

However, when I pull them out of the chain and run them as a series of batches it seems to work fine:

```

$batch = Bus::batch([
            new TestJob1(),
            new TestJob2(),
            new TestJob1(),
            new TestJob2(),
        ])->then(function (Batch $batch) {
            
        })->catch(function (Batch $batch, Throwable $e) {
            
        })->finally(function (Batch $batch) {
           
        })->allowFailures()->onQueue('my-queue')->dispatch();

```

Thanks!

**Comment by themsaid** [comment]
Thanks for reporting this. I've opened a PR that will fix it: https://github.com/laravel/framework/pull/35746
