### ISSUE TITLE
Double ports for domain specification with different port in url generator

### ISSUE THREAD

**Issue by sebwas** [laravel/framework#35731]
- Laravel Version: 8.19.0
- PHP Version: 7.4.13
- Database Driver & Version: Irrelevant

### Description:
If the Laravel instance runs under a non-standard port (for example 9080) and a route is added with a different domain that contains a port, too (which, I know is not standard procedure; a domain should not contain a port, but this is the only way to add another host to Laravel's routing), generating urls with this route generates bad URLs with double ports (For example `http://localhost:3000:9080`).

### Steps To Reproduce:
1. Run laravel with a non-standard port (i.e. 443 for HTTPS or 80 for HTTP).
2. Add a route with a domain that contains a port number, e.g.
    ```php
    $frontendDomain = 'localhost:3000';

    Route::domain($frontendDomain)->get('login')->name('auth.login');
    ```
3. Generate the URL for the given route: `app('url')->route('auth.login')`
4. See the malformed URL: `http://localhost:3000:9080/login`

This is simple to patch and I will soon provide a pull request taking care of this.

**Comment by driesvints** [comment]
Heya, thanks for your report.

>  which, I know is not standard procedure; a domain should not contain a port, but this is the only way to add another host to Laravel's routing

Yeah, it shouldn't. As it isn't meant to contain a port number then we can't consider this to be a bug. I feel like this is more a case of functionality being missing. It seems you've already been working on a PR so we should focus on making this happen through something like that instead.

PS.: small side note: you *are* always adding the port number to your `APP_URL` env variable, correct?

**Comment by sebwas** [comment]
> you are always adding the port number to your APP_URL env variable, correct?

I am not quite sure that I understand what you mean.

In my example, yes, I am adding the port number. In other instances, I would probably omit it (specifically 80 for http and 443 for https, as these are being omitted by Laravel itself as well).

**Comment by driesvints** [comment]
@sebwas you need to add the port number to your url for production here: https://github.com/laravel/laravel/blob/8.x/.env.example#L5

**Comment by sebwas** [comment]
Sure, but that's the problem. Only when I change it to a non-standard port (in which case I would completely omit it) does this "bug" occur. (In my example Laravel would have been running under 9080)

I understand that this is not a bug. It's not a bug, because for my example I am abusing the system. However, there is no other way to make laravel generate correct URLs with two different ports, so this ultimately is a missing feature.

**Comment by driesvints** [comment]
@sebwas understood. Maybe we can look into adding this for a future release. We're open to PRs but the decision lies with Taylor on merging them.

**Comment by sebwas** [comment]
I understand.

I tried, anyway, but I don't have the time right now to make this a new feature in the proper facilities. (i.e. `RouteRegistrar` and `UrlGenerator` probably)

**Comment by Manu-sh** [comment]
i have the same issue with laravel 9
