### ISSUE TITLE
Markdown not allow html in mails but html_input is allowed

### ISSUE THREAD

**Issue by isaeken** [laravel/framework#35745]
- Laravel Version: 8.19.0
- PHP Version: 8.0.0
- Database Driver & Version: MariaDB 10.5

### Description:
Markdown not allow html in mails but html_input is allowed in CommonMark Converter

### Steps To Reproduce:

i am changed line 41 in ``mail/html/layout.blade.php`` to my own function
````php
public static function parse($text, $config = ['allow_unsafe_links' => false])
{
    $environment = Environment::createCommonMarkEnvironment();
    $environment->addExtension(new TableExtension);
    $converter = new CommonMarkConverter($config , $environment);
    return new HtmlString($converter->convertToHtml($text));
}
````
````blade
{{-- Body --}}
{{ MYCLASS::parse($slot, ['allow_unsafe_links' => false, 'html_input' => 'allow']) }}
````

but html tags are striping

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
