### ISSUE TITLE
Factory class instances are not consistent throughout factory process

### ISSUE THREAD

**Issue by benswinburne** [laravel/framework#35749]
- Laravel Version: 8.20.1
- PHP Version: 7.4.10
- Database Driver & Version: PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

### Description:

When using factory classes I get different instances of the factory back which prevents me using the object to store things on the factory instance.

For example. Let's say a `Creative` hasOne `Script`, and thus a `Script` belongsTo a `Creative`. A Script must always have a Creative so my factories set one up. 90% of the time, I want all the default corresponding models set up but occasionally, I don't want to set up the related models.

Trying to set up a Fluent like API to facilitate this doesn't seem to work because I don't get the same factory instance back.

For example if I write

```
Creative::factory()->withoutScript()->create();
```

And expect to be able to configure my factory object inside `withoutScript()` I can't as when the after hooks are run the object they receive is a new factory with a different object ID and thus has the default `$createScript = true` as opposed to the false I set.

### Steps To Reproduce:

```
<?php

namespace Database\Factories;

use App\Creative;
use App\Script;
use Illuminate\Database\Eloquent\Factories\Factory;

class CreativeFactory extends Factory
{
    protected $createScript = true;

    protected $model = Creative::class;

    public function definition()
    {
        return ['name' => $this->faker->bs];
    }

    public function configure()
    {
        // createScript always true, id always different to that in withoutScript
        dump($this->createScript, spl_object_id($this)); 

        return $this->afterCreating(function (Creative $creative) {
            if ($this->createScript) {
                $creative->script()->save(
                    Script::factory()->create([
                        'creative_id' => $creative->id,
                    ])
                );
            }
        });
    }

    public function withoutScript()
    {
        dump(spl_object_id($this));

        $this->createScript = false;
        return $this;
    }
}

```

```
<?php

namespace App;

use App\Script;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Creative extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    /**
     * The script for this creative.
     */
    public function script()
    {
        return $this->hasOne(Script::class);
    }
}
```

```
<?php

namespace App;

use App\Creative;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Script extends Model
{
    use HasFactory;

    /**
     * The creative this script belongs to.
     */
    public function creative()
    {
        return $this->belongsTo(Creative::class);
    }
}
```

### Extra

For extra context, obviously if i have a script factory create a creative and a creative factory create a script when used, one sets up the other and i get surplus rows in my database which means things like `->assertDatabaseCount()` has off by one weirdness in tests because my factories aren't behaving as I want them.  For example, the below test fails because there are two scripts.

```
test('a script factory creates a creative', function () {
    Script::factory()->create();

    $this->assertDatabaseCount('creatives', 1);
    $this->assertDatabaseCount('scripts', 1); // fails, there are two
});
```

When the script factory looks like this.

```
<?php

namespace Database\Factories;

use App\Creative;
use App\Script;
use Illuminate\Database\Eloquent\Factories\Factory;

class ScriptFactory extends Factory
{
    protected $model = Script::class;

    public function definition()
    {
        return [
            'creative_id' => Creative::factory()->lazy(),
        ];
    }
}
```

What's obviously happening here is the

- script factory runs, makes a script, the definition makes a creative using the creative factory
- the creative factory runs and makes a creative, which makes the script

Then the original Creative hasOne Script relationship doesn't find the script we expect either.

```
test('a script factory creates a creative', function () {
    $script = Script::factory()->create();

    $this->assertDatabaseCount('creatives', 1);

    $creative = Creative::first(); // we know there is only one so grab it like this for sake of argument.

    $this->assertEquals($creative->script->id, $script->id); // the script the hasOne finds is not the one we just created. This fails
}));
```

Allowing me to use things like ->withoutScript i can change my Factory to the below, for example.

```
<?php

namespace Database\Factories;

use App\Creative;
use App\Script;
use Illuminate\Database\Eloquent\Factories\Factory;

class ScriptFactory extends Factory
{
    protected $model = Script::class;

    public function definition()
    {
        return [
            'creative_id' => Creative::factory()->withoutScript()->lazy(),
        ];
    }
}
```

As there are no before hooks for factories I can't easily prevent things happening, and cleaning them up in afterCreating seems wasteful i.e. 

```
    public function withoutScript()
    {
        return $this->afterCreating(function ($creative) {
            $creative->script()->delete();
        });
    }

```

--

* I think this is a bug but not entirely sure. If it's not a bug then I suppose it's a feature request so apologies if there's a different issue template for that. I can repost/rephrase if necessary.

**Comment by taylorotwell** [comment]
I agree this is more of a feature request than a "bug". Since we just use the issue tracker on GH for legitimate bugs I am going to close this for now.

**Comment by benswinburne** [comment]
Thanks @taylorotwell. Is this something worth me fleshing out in laravel/ideas for consideration?

The only way I've managed to get this to work so far is by extending the factory class and effectively removing the immutability (by removing the `newInstance` calls from the various methods).

This works, but obviously it would be great if at some point there is a sensible alternative to keep data within a factory object. If a new copy of the factory is needed, perhaps deep copying the object rather than just passing a discrete set of data into the constructor or passing some sort of meta property into the constructor would be useful so that information for that instance of a factory can be maintained throughout the process.

Just putting this here in the event that it is useful for anyone else.

```
<?php

namespace Database\Factories;

use Closure;
use Illuminate\Database\Eloquent\Factories\Factory as LaravelFactory;

abstract class Factory extends LaravelFactory
{
    /**
     * Create a new instance of the factory builder with the given mutated properties.
     *
     * @param  array  $arguments
     * @return static
     */
    protected function newInstance(array $arguments = [])
    {
        return $this;
    }

    /**
     * Specify how many models should be generated.
     *
     * @param  int|null  $count
     * @return static
     */
    public function count(?int $count)
    {
        $this->count = $count;

        return $this;
    }

    /**
     * Add a new "after creating" callback to the model definition.
     *
     * @param  \Closure  $callback
     * @return static
     */
    public function afterCreating(Closure $callback)
    {
        $this->afterCreating->push($callback);

        return $this;
    }

    /**
     * Add a new "after making" callback to the model definition.
     *
     * @param  \Closure  $callback
     * @return static
     */
    public function afterMaking(Closure $callback)
    {
        $this->afterMaking->push($callback);

        return $this;
    }

    /**
     * Add a new state transformation to the model definition.
     *
     * @param  callable|array  $state
     * @return static
     */
    public function state($state)
    {
        $this->states->push(
            is_callable($state)
                ? $state
                : function () use ($state) {
                    return $state;
                }
        );

        return $this;
    }
}
```

NB: The various relationship methods aren't in the example above as I've not needed to use those yet.
NB2: I have not yet run this against the test suite to see if the expected behaviour changes (other than the immutability), but I am running this against a largish existing test suite with no problems so far.

**Comment by amcsi** [comment]
I ran into this same issue. Though my case was a lot simpler:

I wanted to use `configure()` to set some dependencies into private properties as an alternative to the constructor that accepted many arguments. And unfortunately it turned out that those properties just get lost in the immutable copy.

I'm in a luckier situation though, because I could get around this by just using `app()` within `definition()` to access dependencies.

**Comment by 1giba** [comment]
thx @benswinburne 

I had the same issue.
