### ISSUE TITLE
The requested resource /login was not found on this server.

### ISSUE THREAD

**Issue by Hassen307** [laravel/framework#35751]
![Screenshot_2020-12-29 404 Not Found](https://user-images.githubusercontent.com/27709364/103289198-e3516480-49e6-11eb-86e1-6edd7b06b985.png)

- Laravel Version: 6.18.35
- PHP Version: 7.4.13
- Database Driver & Version: 10.4.13-MariaDB

### Description:
when we use a folder in public folder have the same name as the URL, we get an error

### Steps To Reproduce:
create an empty folder named 'login' inside the public folder, and the try to access the url (localhost:8000/login), problem persists in all the similar scenario (localhost:8000/register...)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
