### ISSUE TITLE
routes with 'group' as binding does not work

### ISSUE THREAD

**Issue by danikp** [laravel/framework#35767]
- Laravel Version: 8.20.1
- PHP Version: 7.4
- Database Driver & Version:

### Description:
After upgrade from version 6 to latest, all routes having 'group' binding failing to work. Changing it to anything else works perfectly. Behavior reproducible with and without using explicit binding. All other 100+ bindings are totally fine

### Steps To Reproduce:
1. create route in following format
Route::get('groups/{group}',  'GroupsController@show');

1.1 update RouteServiceProvider to use default namespace for above to work

2. create controller and model
php artisan make:controller --api --model=Group GroupsController

3. create new table and fill with few rows or set any existing table to be used with model

4. make a call to route above with id existing in table above

exception "Target class [Group] does not exist." thrown even with explicit binging being set like that
Route::model('group', \App\Models\Group::class);

**Comment by taylorotwell** [comment]
Unable to recreate. Works for me.
