### ISSUE TITLE
php artisan migrate:rollback command trigger error when migrations table doesn't exist

### ISSUE THREAD

**Issue by netojose** [laravel/framework#35763]
- Laravel Version: 8.12.3
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.22

### Description:
Artisan command `php artisan migrate:rollback` throw exception if `migrations` table doesn't exist
Illuminate\Database\QueryException

### Steps To Reproduce:
* run `php artisan migrate:rollback` in some Laravel instalation without migrations table
* See the error below:

<img width="1075" alt="Screenshot 2021-01-01 at 19 31 21" src="https://user-images.githubusercontent.com/134008/103445152-86a4b280-4c4f-11eb-9ca0-74b25b6a16b7.png">

**Comment by taylorotwell** [comment]
Don't run it without a migrations table.
