### ISSUE TITLE
Group by is not accept float values in Collection class

### ISSUE THREAD

**Issue by abdrzakoxa** [laravel/framework#35765]
- Laravel Version: 8.*
- PHP Version: 7.4

### Description:
The problem is when I want to use `groupBy` method in `Illuminate\Support\Collection` for float value it give me this error:
`array_key_exists(): The first argument should be either a string or an integer`
- currently the groupBy method is just accept int, boolean and string values

### Steps To Reproduce:
```php
$products = [
    [
        'unit_cost' => 10.50,
        'name' => 'Bag',
    ],
    [
        'unit_cost' => 10.50,
        'name' => 'Bag',
    ],
    [
        'unit_cost' => 20.50,
        'name' => 'E-Book',
    ],
];
collect($products)->groupBy('unit_cost');
```

- error: `array_key_exists(): The first argument should be either a string or an integer`

### Solve problem

in `Illuminate\Support\Collection:441`
```php
$groupKey = is_bool($groupKey) ? (int) $groupKey : (string) $groupKey;
```

**Comment by crynobone** [comment]
You should be able to use

```php
$products = [
    [
        'unit_cost' => 10.50,
        'name' => 'Bag',
    ],
    [
        'unit_cost' => 10.50,
        'name' => 'Bag',
    ],
    [
        'unit_cost' => 20.50,
        'name' => 'E-Book',
    ],
];

collect($products)->groupBy(function ($item) {
    return (string) $item['unit_cost'];
});
```

**Comment by abdrzakoxa** [comment]
@crynobone Yes I know, but groupBy should accept int, boolean, float and string values, because now it accept only int, boolean and string values

**Comment by abdrzakoxa** [comment]
@crynobone
The data type of php is:
```
String
Integer
Float (floating point numbers - also called double)
Boolean
Array
Object
NULL
Resource
```

So it should accept: `String, Integer, Float, Boolean, NULL`

**Comment by taylorotwell** [comment]
You will need to use the solution provided by @crynobone

**Comment by abdrzakoxa** [comment]
@taylorotwell I already use it, but I don't know why groupBy accept only bool, string and int but not accept float ...
