### ISSUE TITLE
Patch request for 7.x from 8.x PhpRedisConnector

### ISSUE THREAD

**Issue by normkatz** [laravel/framework#35772]
- Laravel Version: #.#.# 7.22.4
- PHP Version: 7.3.19
- Database Driver & Version: Redis 6.0.9
- phpredis Version 5.3.1

### Description:
We are using Laravel with phpredis and a redis server that needs TLS1.2 and a verified CA and cert.

In vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php function establishConnection() in Laravel 8.x, you have:
        if (version_compare(phpversion('redis'), '5.3.0', '>=')) {
            if (! is_null($context = Arr::get($config, 'context'))) {
                $parameters[] = $context;
            }
        }

But it was not patched into Laravel 7.x (at least not 7.22.4).  We are running 7.22.4 in production and phpredis is not passing the context ssl parameters from config/database.php to the redis extension (or openssl).  Would it be possible for you to patch Laravel 7.x?  Upgrading our environment to 8.x will take a significant effort in our FDA compliant environment.

### Steps To Reproduce:
On a system running Laravel 7.x:
Create a self-signed certificate and extract the CA, key and cert files.
Update your redis settings in config/database to include these in the 'context' array.
For example:
'context' => [
    'stream' => [
        'allow_self_signed' => true,
        'ciphers' => 'DEFAULT:!TLSv1.0:!TLSv1.1:!SSLv3',
        'local_cert' => '/usr/local/certs/tls.crt',
        'local_pk' => '/usr/local/certs/tls.key',
        'cafile' => '/usr/local/certs/ca.pem'
    ],
]

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by normkatz** [comment]
It was fixed in 7.28.   Anyone running previous version should just update with composer.
