### ISSUE TITLE
Routing customizing the default key not work

### ISSUE THREAD

**Issue by vicobohdan** [laravel/framework#35770]
- Laravel Version: 8.18
- PHP Version: 7.3.11
- Database Driver & Version: mysql

### Description:
https://laravel.com/docs/8.x/routing#customizing-the-default-key-name not working:

`Route::get('/{product:slug}', [ProductController::class, 'show']);`

path parameter not pass to model select:
`select * from `products` where `slug` is null limit 1`

### Steps To Reproduce:

**Comment by vicobohdan** [comment]
why? not work also in Laravel v8.20.1

vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:
```
public function resolveRouteBinding($value, $field = null)
    {
        return $this->where($field ?? $this->getRouteKeyName(), $value)->first();
    }
```
field parameter is ok, but $value is always null, expected is that $value = route path parameter `{product:slug}`, or I'm wrong?

**Comment by driesvints** [comment]
@vicobohdan please try a support channel. There's most likely something wrong in your app.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
