### ISSUE TITLE
change()ing a column via a migration ignores storedAs()

### ISSUE THREAD

**Issue by iansltx** [laravel/framework#35789]
- Laravel Version: 8.18.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7 and 8.0

### Description:

Specifying storedAs() (guessing virtualAs has the same problem) on a column change in a migration doesn't apply the generated column expression, silently leaving you with plain column rather than a generated one. This may be a Doctrine DBAL issue since it involves change(), but figured I'd file the issue where I experienced it.

### Steps To Reproduce:

In one migration:

```php
Schema::create('urls', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->json('response');
    $table->string('click_url')->storedAs("response->>'$.click_url'");
});
```

At this point you'll see the correct generated column in `SHOW CREATE TABLE urls`.

But once you run this:

```php
Schema::table('urls', function (Blueprint $table) {
    $table->string('click_url', 4096)->storedAs("response->>'$.click_url'")->change();
});
```

You get the longer field length but lose the generated-ness.

**Comment by taylorotwell** [comment]
Changing columns is handled basically entirely by Doctrine DBAL so probably needs to be discussed there.
