### ISSUE TITLE
Notification via email, error at delivery

### ISSUE THREAD

**Issue by halivert** [laravel/framework#35788]
- Laravel Version: 8.21.0
- PHP Version: 7.4.13
- Database Driver & Version: MariaDB 10.3.25

### Description:
I need to send notifications through email, I queued those notifications, and then the job is dispatched without exceptions, but the email never arrives to another domain (gmail.com, outlook.com), not even in junk folder.

I think is due a lack of HELO field in queued emails, because it arrives if the recipient is in the same domain, and this is the difference between queued, and sync emails.

![queue sync email](https://user-images.githubusercontent.com/16197249/103680390-bbfd1900-4f4b-11eb-86a7-13d69eb6a482.png)
Email sent with `queue=sync`

![queued email](https://user-images.githubusercontent.com/16197249/103680463-d33c0680-4f4b-11eb-98d1-5d62bd5b47fc.png)
Email sent with `queue=database`

### Steps To Reproduce:
Send email notification with and without queue, compare 

Template to reproduce
https://github.com/halivert/email-test

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by halivert** [comment]
Hi Dries,

Maybe I didn't use the correct description
I think the issue is in the queue worker, it didn't cache correctly (or something like that) the HELO field to use in the queued notifications.

I don't know the reason of the difference between sync notifications having correct HELO and queued not.

Greetings and thank you so much for your time

**Comment by halivert** [comment]
Update

It was, indeed, caused by HELO field. 
Searching in swiftmailer docs and laravel source code I found that you need to specify `config.mail.local_domain` key if you want to preserve HELO in queued mails in a daemon queue.
