### ISSUE TITLE
BelongsToMany#updateOrCreate is not merging arguments before create

### ISSUE THREAD

**Issue by marcoboers** [laravel/framework#35798]
- Laravel Version: 8.20.1
- PHP Version: 7.4.8
- Database Driver & Version: MariaDB 10.5.8

### Description:
For `Illuminate\Database\Eloquent\Relations\BelongsToMany` relationships, the `updateOrCreate` method is not merging the $attributes and $values arrays. 

This is different from the behaviour of the `updateOrCreate` methods on `Builder`,   `HasOneOrMany` and `HasManyThrough` classes and from the documented behaviour "If no such flight exists, a new flight will be created which has the attributes resulting from merging the first argument array with the second argument array" [eloquent#upserts](https://laravel.com/docs/8.x/eloquent#upserts). 

**Illuminate\Database\Eloquent\Relations\BelongsToMany**
```
    public function updateOrCreate(array $attributes, array $values = [], array $joining = [], $touch = true)
    {
        if (is_null($instance = $this->where($attributes)->first())) {
            return $this->create($values, $joining, $touch);
        }

        $instance->fill($values);

        $instance->save(['touch' => false]);

        return $instance;
    }
```
**Proposed solution**
This solution is based on master (9.x) branch where the fix for [#34083](https://github.com/laravel/framework/issues/34083) is taken into account.
```
    public function updateOrCreate(array $attributes, array $values = [], array $joining = [], $touch = true)
    {
        if (is_null($instance = $this->related->where($attributes)->first())) {
            $instance = $this->create($attributes, $joining, $touch);
        }

        $instance->fill($values);

        $instance->save(['touch' => false]);

        return $instance;
    }
```
### Steps To Reproduce:
```
Schema::create('roles', function (Blueprint $table) {
    $table->increments('id');
    $table->unsignedBigInteger('created_by_id');
    $table->string('name'); // <-- required
    $table->timestamps();
});
```
```
$user = User::factory()->create();
Role::create(['name' => 'existing.role', 'description' => 'foo']);
$user->roles()->updateOrCreate(['name' => 'existing.role'], ['description' => 'bar']);

parent::assertEquals(1, Role::count()); // assertion fails (or is never reached); count equals 2
```
```
$user = User::factory()->create();

// throws: Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
$user->roles()->updateOrCreate(['name' => 'existing.role'], ['description' => 'bar']); 

parent::assertEquals(1, Role::count()); // assertion fails (or is never reached); count equals 2
```

When confirmed I'll submit the pull request.

**Comment by driesvints** [comment]
Heya, this is already fixed for the upcoming Laravel 9 release. See https://github.com/laravel/framework/issues/34083#issuecomment-698559977

**Comment by marcoboers** [comment]
@driesvints I did see that comment. 
However, this is about a slightly different issue.
Which is that if the model does not exist, and therefor should create the model, the first argument is not used for creating the model (only the second argument is used). Which is different behavior from when calling the method directly on the model or on another type of relation.

And that is why this is mainly about the change of this line
https://github.com/laravel/framework/blob/ce57929931f877f03a8428498654591e890f55f8/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L631

into
```
$instance = $this->create($attributes, $joining, $touch);
```

Which is not fixed in the current master branch as far as I can tell.

**Comment by driesvints** [comment]
@marcoboers can you attempt a PR to master?

**Comment by matiaslauriti** [comment]
It is a shame you opened a PR for `9.x` but not `8.x` as you found the issue there. I have now done so and I hope I did not do anything wrong.
