### ISSUE TITLE
"Undefined index: command" when retrying queue job

### ISSUE THREAD

**Issue by manavo** [laravel/framework#35813]
- Laravel Version: 8.21.0
- PHP Version: 7.4.11
- Database Driver & Version:

### Description:

When calling `php artisan queue:retry ID`, if the job is a raw job that has been pushed into the queue, there isn't a `command` key to be used in the `RetryCommand@refreshRetryUntil`. That then causes an issue since the key is missing in the `RetryCommand@refreshRetryUntil` method, and the queue job doesn't get retried.

### Steps To Reproduce:

Create a class which can be queued, which fails:

```php
class FailJob
{

    public function fire($job, $data) {
        throw new \Exception('Fail on purpose');
    }

}
```

Queue that job:

```php
Queue::push('FailJob', [])
```

Once it fails, get the ID of that job:

```
php artisan queue:failed
```

Call the artisan command to retry it:

```
php artisan queue:retry {ID_HERE}
```

And you get this error:

```
   ErrorException 

  Undefined index: command

  at vendor/laravel/framework/src/Illuminate/Queue/Console/RetryCommand.php:129
    125▕     protected function refreshRetryUntil($payload)
    126▕     {
    127▕         $payload = json_decode($payload, true);
    128▕ 
  ➜ 129▕         $instance = unserialize($payload['data']['command']);
    130▕ 
    131▕         if (is_object($instance) && method_exists($instance, 'retryUntil')) {
    132▕             $payload['retryUntil'] = $instance->retryUntil()->timestamp;
    133▕         }

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Sorry I'm not supplying a failing test to reproduce as I'm short on time right this minute, but just wanted to report ASAP!

**Comment by taylorotwell** [comment]
Will send in a fix.

**Comment by manavo** [comment]
Thanks!
