### ISSUE TITLE
Second parameter of Illuminate\Http\Client\PendingRequest::post(string $url, array $data = []) defaults to an array

### ISSUE THREAD

**Issue by nticaric** [laravel/framework#35817]
- Laravel Version: 8.x
- PHP Version: 8.0

### Description:
The class `Illuminate\Http\Client\PendingRequest` contains 4 methods ( `post()`, `patch()`, `put()`, `delete()` )
that have a default second parameter set as an empty array. This will set the raw request body to `[]`
which for most cases is fine, but for some external API's the request will break because they don't
know what to do with an empty array. Because of type hinting, it's not possible to set the data to `null`

The solution for this would be either to remove type hinting or to set the default value to null.

If necessary, I can create a PR

**Comment by driesvints** [comment]
No plans to change this sorry.

**Comment by nticaric** [comment]
Is there any reason why it must be be a blank array?

In my particular case I am sending a post requests to a fintech application and they return a 500 response if the body is not blank? Why force it to be an empty array?

The solution is simple as  `public function post(string $url, $data = [])`

**Comment by nticaric** [comment]
Here's an example that shows whats going on:
By calling:

```php
Http::post("https://httpdump.app/dumps/fc80daac-9f6a-4c74-b747-d488e387f1a9");
```

By inspecting the request on `https://httpdump.app/inspect/fc80daac-9f6a-4c74-b747-d488e387f1a9`
you'll see that the response body is set to a blank array, which should not be the case

**Comment by MrJuliuss** [comment]
Hi, got the same problem with paypal Api, i can't send a post request without body...

**Comment by nticaric** [comment]
My workaround for this was to use it like this:

```php
    Http::withToken($token)
        ->send('POST', $url, [
            'json' => null
        ]);
```

But I still think that the method should look like `public function post(string $url, $data = [])`, without forcing the user to use an array so that `null` can be specified as a second parameter

**Comment by MrJuliuss** [comment]
> My workaround for this was to use it like this:
> 
> ```
>     Http::withToken($token)
>         ->send('POST', $url, [
>             'json' => null
>         ]);
> ```
> 
> But I still think that the method should look like `public function post(string $url, $data = [])`, without forcing the user to use an array so that `null` can be specified as a second parameter

It works indeed. Thanks !
I'm agree with you.
