### ISSUE TITLE
php artisan serve not following the --env parameter passed

### ISSUE THREAD

**Issue by rvigneshw** [laravel/framework#35815]
- Laravel Version: 8.0
- PHP Version: 8.0.0
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for Linux (x86_64)

### Description:

When running test with laravel dusk, the php artisan  serve --env=dusk.local does not pick the database given in .env.dusk.local file instead it chooses .env file database

### Steps To Reproduce:

type the command and register and you will fine user stored in different database

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
