### ISSUE TITLE
Can't share database session between laravel 5.8 and laravel 6/7

### ISSUE THREAD

**Issue by jm-vergara** [laravel/framework#35811]
I have laravel 5.8 in production and many projects with SSO using the shared database session in laravel. But when I add laravel 7 o 6 into laravel 5.8 database session it keeps creating a new session and logout users in both applications.

How can share database session in laravel 5.8 and Laravel 6 or 7?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
