### ISSUE TITLE
Unable to disable a specific model event instead of all.

### ISSUE THREAD

**Issue by gregorip02** [laravel/framework#35818]
- Laravel Version: 8.19.0
- PHP Version: 7.4

### Description:

When I run the tests, I need to disable a specific model event, say "created", but `MyModel::flushEventListeners()` would not work because I need my "creating" event to be fired. An "inelegant" solution is to run the following.

```php
<?php

\Illuminate\Support\Facades\Event::fake([
    'eloquent.created: ' . MyModel::class
]);
```

This would work, but what if we have something like the following:

```php
<?php

MyModel::flushEventListeners(['created']);

// Or something more especific
MyModel::flushEventListener('created');
```

There would be no compatibility problems and we continue to use the same API.

I can send you a PR if you like it.

**Comment by driesvints** [comment]
Sounds like a feature request. Feel free to attempt a PR if you like.
