### ISSUE TITLE
queue:retry is broken after recent commit

### ISSUE THREAD

**Issue by chaoszcat** [laravel/framework#35825]
- Laravel Version: 8.21.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL

### Description:
A [recent pull on the framework](https://github.com/laravel/framework/pull/35780) has broken the `php artisan queue:retry`. I submitted a [comment on the commit](https://github.com/illuminate/queue/commit/34183c7575e5f3b785f5f31a3718f49b91350d04#commitcomment-45716391) but decided to create this issue since this is reproducible.

### Steps To Reproduce:

1. Create a fresh project

```shell
composer create-project laravel/laravel test
```

2. Create database migrations

```shell
php artisan queue:table
php artisan migrate
```

3. Insert a new user into the users table with an email address.

```sql
INSERT INTO users SET name="test", email="test@example.com", password="";
```

4. Make sure `.env` is using database as the queue driver:

```
QUEUE_CONNECTION=database
```

5. Create a new notification that will fail (`app/Notifications/TestNotification.php`)

```php
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

class TestNotification extends Notification implements ShouldQueue
{
    use Queueable;
    
    public function via($notifiable)
    {
        return ['mail'];
    }

    public function toMail($notifiable)
    {
        throw new \RuntimeException('Purposely fail this notification to test queue:retry');
    }
}
```

6. Insert the notification into queue by calling this anywhere from the code:

```php
(\App\Models\User::find(1))->notify(new \App\Notifications\TestNotification());
```

7. Run the queue worker. The worker should fail.

```shell
php artisan queue:work
```

8. Retry the queue, and the problem arise:
```shell
php artisan queue:retry all
```
```
ErrorException 

Attempt to read property "timestamp" on null

  at vendor/laravel/framework/src/Illuminate/Queue/Console/RetryCommand.php:132
    128▕ 
    129▕         $instance = unserialize($payload['data']['command']);
    130▕ 
    131▕         if (is_object($instance) && method_exists($instance, 'retryUntil')) {
  ➜ 132▕             $payload['retryUntil'] = $instance->retryUntil()->timestamp;
    133▕         }
    134▕ 
    135▕         return json_encode($payload);
    136▕     }

      +16 vendor frames 
```

### Reasoning:

As per [my comment on the commit](https://github.com/illuminate/queue/commit/34183c7575e5f3b785f5f31a3718f49b91350d04#commitcomment-45716391), the [`retryUntil()` method in the class `SendQueuedNotifications`](https://github.com/illuminate/notifications/blob/8.x/SendQueuedNotifications.php#L140-L147) does not always return a Carbon object as expected in the RetryCommand. Suggest a fix is to check also if the `retryUntil()` is returning a Carbon object before accessing the `timestamp` field.

**Comment by rodrigopedra** [comment]
I guess this is fixed by this commit: 4415b94623358bfd1dc2e8f20e4deab0025d2d03

But it still needs to be tagged.

**Comment by chaoszcat** [comment]
@rodrigopedra no it's not. The `if` case in `RetryCommand` is checking if `SendQueuedNotifications` is indeed an object, and if the method `retryUntil()` is exist or not, and he simply call `retryUntil()->timestamp` without checking if the method is returning a Carbon object or not. The method defined in `SendQueuedNotifications` is returning `null` when the notification does not define a `retryUntil()`.

**Comment by rodrigopedra** [comment]
I see now, thanks for the heads up.

**Comment by driesvints** [comment]
Thanks for the report. I've sent in a fix here: https://github.com/laravel/framework/pull/35828
