### ISSUE TITLE
Router - Percent encoded "/" not working

### ISSUE THREAD

**Issue by aaron-ecce** [laravel/framework#35829]
- Laravel Version: 8.21.0
- PHP Version: 7.4.4
- Database Driver & Version: mysql 5.7

### Description:

Attempting to use an encoded "/" (%2F) in a route param does not resolve. It is suggested in the [documentation](https://laravel.com/docs/master/routing#parameters-encoded-forward-slashes) that this only works in the last segment, but this does not seem to be the case.

### Steps To Reproduce:

As per documentation, add the following to your web route:

```php
Route::get('/search/{search}', function ($search) {
    return $search;
})->where('search', '.*');
```

the visit: /search/some%2Furl

### Expected Result

Expected it to display the text "some/url"

### Actual Result

404 Http response

**Comment by driesvints** [comment]
Works for me. Do you have your routes cached? Run `php artisan route:clear`.
