### ISSUE TITLE
Errors returned from request class with numeric rules index is reset.

### ISSUE THREAD

**Issue by paulohpsrock** [laravel/framework#35831]
- Laravel Version: 7.30.1
- PHP Version: 7.3.25
- Database Driver & Version: mysql | mariadb:10.2

### Description:
Errors returned from request class with numeric rules index is reset.

### Steps To Reproduce:
1 - create request with rules:

    <?php  
      
    namespace App\Http\Requests\Rest;  
      
    use Illuminate\Foundation\Http\FormRequest;  
      
    class RegisterRequest extends FormRequest  
    {  
        public function authorize()  
        {  
            return true;  
        }  
      
        public function rules()  
        {  
            return [  
                1 => 'required',  
                2 => 'required',  
                3 => 'required',  
                '14' => 'required',  
                '20' => 'required',  
            ];  
        }  
    }

2 - When using the class in a controler it returns the following error message structure.

    errors: [
        0: ["O campo 0 é obrigatório."]
        1: ["O campo 1 é obrigatório."]
        2: ["O campo 2 é obrigatório."]
        3: ["O campo 3 é obrigatório."]
        4: ["O campo 4 é obrigatório."]
    ]

The correct thing would be:

    errors: [
        1: ["O campo 0 é obrigatório."]
        2: ["O campo 1 é obrigatório."]
        3: ["O campo 2 é obrigatório."]
        14: ["O campo 3 é obrigatório."]
        20: ["O campo 4 é obrigatório."]
    ]

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
