### ISSUE TITLE
Cannot render component with quotes inside blade template

### ISSUE THREAD

**Issue by durianpeople** [laravel/framework#35843]
- Laravel Version: 8.21.0
- PHP Version: 7.4.11
- Database Driver & Version: -

### Description:

When creating a component with an attribute that is dynamically generated by Blade using brackets `{{ }}` with quotes that matches the attribute quotes, the component is not rendered.

### Steps To Reproduce:

Create a component with an attribute, e.g.:

```php
<x-some-component attribute="{{ "dynamically-set-value" }}" />
```

### Expected behavior

I'm actually not sure whether this is an intended or unintended behavior, but because it is enclosed within a Blade templating context using `{{ }}`, I expect that that should be renderable.

### Note

I notice that it has to do with the regex matching in `\Illuminate\View\Compilers\ComponentTagCompiler::compileSelfClosingTags`.

**Comment by driesvints** [comment]
Yes, using `{{ }}` can lead to side effects like this. We recommend using the `:attribute=""` syntax as explained in the docs: https://laravel.com/docs/8.x/blade#passing-data-to-components
