### ISSUE TITLE
Accessors for database columns consisting of integers in their name not getting serialized when sending JSON response 

### ISSUE THREAD

**Issue by ScriptingBeating** [laravel/framework#35847]
- Laravel Version: 8.20.1
- PHP Version: 7.3
- Database Driver & Version: Mysql 8

### Description:
Accessors for database columns consisting of integers in their name not getting modified/serialized with new values when passing them in JSON response 

### Steps To Reproduce:

I have created an accessor to modify a database value

```
public function getImage1Attribute($value)
{
   return $value ? asset('storage/hosts/images/' . $value) : null;
}
```

but I am still getting original value in JSON API like this

```
{
    "message": "success",
    "data": {
        "id": 1,
        "image_1": "n0rVxA1L-1610381013.jpg",
        "created_at": "2021-01-07 18:02:56",
        "updated_at": "2021-01-11 16:03:33"
    }
}
```

I am passing response like this

```
return response([
      'message' => Lang::get('api.success'),
      'data' => HostDetail::find($id)
]);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ScriptingBeating** [comment]
I already asked everywhere but didn't find any solution that's why I asked here

**Comment by driesvints** [comment]
Can you post the links of the places where you asked?

**Comment by ScriptingBeating** [comment]
https://laracasts.com/discuss/channels/laravel/accessors-not-working-in-api

**Comment by ScriptingBeating** [comment]
And I found out that this might be a bug, that's why I posted

**Comment by ScriptingBeating** [comment]
But no problem I will wait for some days.

**Comment by driesvints** [comment]
Ah, I see. That's no bug but the expected behavior. It expects it to be without the `_` in your column name as we cannot know if that's present or not.

**Comment by ScriptingBeating** [comment]
Okay, but it doesn't even work with the column name `image1`.

**Comment by driesvints** [comment]
Ah I see what's going on. You need to do this: https://laravel.com/docs/8.x/eloquent-serialization#appending-values-to-json

See: 

<img width="733" alt="Screenshot 2021-01-11 at 18 51 18" src="https://user-images.githubusercontent.com/594614/104219159-0ac01c80-543e-11eb-81e1-6438d34130cc.png">

**Comment by ScriptingBeating** [comment]
No, append only works for custom attributes, this is not a custom attribute it already exists in the database. I am just modifying it using accessor. And I am getting the data in JSON response It's just that I am getting the original value not the computed one. I get the computed one only when I access it explicitly like `$model->image_1`.
