### ISSUE TITLE
Probably a bug in "Multiple Rate Limits"

### ISSUE THREAD

**Issue by mantas-done** [laravel/framework#35844]
- Laravel Version: 8.21.0
- PHP Version: 8.0.0
- Database Driver & Version: tested cache driver set to Database and Redis (on Homestead)

### Description:

When using multiple rate limits, the remaining limit is decreasing by 2. Should decrease by 1 with every page refresh.

### Steps To Reproduce:

Try using an example from the documentation: https://laravel.com/docs/8.x/routing#multiple-rate-limits
![image](https://user-images.githubusercontent.com/17127206/104167209-a6cd3200-5404-11eb-9657-b8f71c568814.png)

**Comment by taylorotwell** [comment]
No code is included in this issue.

**Comment by mantas-done** [comment]
Added code.

**How to reproduce?** 
Open the main page. 

**What is expected?**
At least 3 requests per minute are expected to be allowed.

**Actual result**
After 2 page loads, 429 error is shown.

https://github.com/mantas-done/laravel-bug/commit/63c31e4f85c28bf0f14fb9654dda9566c30cdf78

**Comment by driesvints** [comment]
@mantas-done I think it's best that you provide a PR with a failing test to prove that this is broken.

**Comment by mantas-done** [comment]
@driesvints Not quite sure how to do it. Asked on discord, but no answers yet.

**Comment by mantas-done** [comment]
https://github.com/laravel/framework/pull/35848 added one test. If you have any questions I will be glad to help.
