### ISSUE TITLE
Nullsafe operator call ErrorException undefined operator

### ISSUE THREAD

**Issue by roman-rachkov** [laravel/framework#35855]
- Laravel Version: 8.21
- PHP Version: 8.0

### Description:
Hello. When im try to use undefined variable with nullsafe operator laravel throw me EerrorException, but i wait null result. I think its wrong when i cant use native language feature

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
