### ISSUE TITLE
HEADER_X_FORWARDED_ALL in TrustProxies Middleware depreciated

### ISSUE THREAD

**Issue by wjonkerhulst** [laravel/framework#35860]
- Laravel Version: 8.5.7
- PHP Version: 7.4.13
- Database Driver & Version: -

### Description:
HEADER_X_FORWARDED_ALL used in /app/Http/Middleware/TrustProxies.php is deprecated since Symfony 5.2.

### Steps To Reproduce:
Read Symfony documentation https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies

**Comment by driesvints** [comment]
Heya, thanks. Deprecated doesn't mean it doesn't works anymore. We'll remove it in a future version once 5.2 has become the minimum version.

**Comment by glisandro** [comment]
Hi!

Does not work for me.

![image](https://user-images.githubusercontent.com/470037/104346501-427ea100-54de-11eb-8fb8-9580b7c9196a.png)

tks

**Comment by driesvints** [comment]
@glisandro that's a deprecation notice of PHP that only happens in development. You should turn off those in your PHP ini file. This won't happen in production. 

In any case we're checking in on replacing the deprecated header: https://github.com/laravel/laravel/pull/5514
