### ISSUE TITLE
Extra space when using annonymous component

### ISSUE THREAD

**Issue by Babiute** [laravel/framework#35866]
- Laravel Version: 8.22.0
- PHP Version: 7.4.9
- Database Driver & Version: none

### Description:
Laravel Blade add extra space when using anonymous component.

### Steps To Reproduce:
1) create a annonymous component at laravel component default directory;

```
//link.blade.php
@props(['href'])

<a class="underline text-green-500 hover:text-green-700 focus:text-green-700" href="{{ $href }}">{{ $slot }}</a>
```

2) Use the component in a paragraph in any view.
`<p class="py-1">I'm in love with <x-link href="https://laravel.com/docs/8.x">LARAVEL</x-link>.</p>`

3) A extra space will appear (from where? That's why I think its a bug) between the word LARAVEL and the dot at the end of the sentence.

**Comment by taylorotwell** [comment]
Well, there is a line break within your component that you pasted?

**Comment by Babiute** [comment]
Hi Taylor.
There is not a line breaker.
Let's say, its the full component.

**Comment by taylorotwell** [comment]
Opened a PR to address the issue. Can you please take a look?

**Comment by Babiute** [comment]
Yes I can.
But as I'm not good enough on read the code yet, there is not much that I can do besides post the bug I have found.
