### ISSUE TITLE
Failed jobs table UUID field

### ISSUE THREAD

**Issue by 021-code** [laravel/framework#35861]
- Laravel Version: 8.22.0
- PHP Version: 7.4.13
- Database Driver & Version: MySql 8.0.22 

### Description:
Command ```php artisan queue:failed-table``` creates a schema with a field ```uuid```, but class ```\Illuminate\Queue\Failed\DatabaseFailedJobProvider``` does not write this field.

**Comment by driesvints** [comment]
Make sure your driver is set properly: https://github.com/laravel/laravel/blob/8.x/config/queue.php#L84

Also see the upgrade guide: https://laravel.com/docs/8.x/upgrade#failed-jobs-table-batch-support

> Next, the failed.driver configuration option within your queue configuration file should be updated to database-uuids.
