### ISSUE TITLE
Bug in Illuminate\Support\Str::camel()

### ISSUE THREAD

**Issue by lapaliv** [laravel/framework#35886]
- Laravel Version: v7.30.1
- PHP Version: 8.0.0

### Description:
Words after numbers are not capitalized. This goes against the main idea of camelCase

### Steps To Reproduce:
```
php artisan tinker
Psy Shell v0.10.5 (PHP 8.0.0 — cli) by Justin Hileman
>>> Illuminate\Support\Str::camel('one1two2three')
=> "one1two2three"
```

Correct result: `one1Two2Three`

**Comment by driesvints** [comment]
We use `ucwords` behind the scenes: https://3v4l.org/niV4n

I also believe this is the correct behavior since we cannot know if the numbers are meant to be the first character of a camelcased string or not. Probably not worth the breaking change anyway.
