### ISSUE TITLE
[Bug] Legacy Factory in Lumen 8

### ISSUE THREAD

**Issue by quevlu** [laravel/framework#35896]
- Laravel/Lumen Version: 8.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
There is a bug when you try to implement legacy factories in Lumen 8. The factory is inside database/factories. I haven't moved the location of it.

Error log
![image](https://user-images.githubusercontent.com/2734741/104653400-515d8300-5699-11eb-9cb4-238e85255c4b.png)

UserFactory class
![image](https://user-images.githubusercontent.com/2734741/104653529-823db800-5699-11eb-9907-bc2d8fa9a377.png)

User model

![image](https://user-images.githubusercontent.com/2734741/104653598-9d102c80-5699-11eb-8f55-cd1955da93df.png)

UserSeeder

![image](https://user-images.githubusercontent.com/2734741/104653656-b2855680-5699-11eb-937d-46ca6137cbe5.png)

### Steps To Reproduce:
1- Install legacy factory | composer require laravel/legacy-factories
2- Define UserFactory logic
3- Add in model HasFactory Trait
4- Create a seeder with factory logic
5- Execute php artisan migrate:fresh --seed

**Comment by driesvints** [comment]
Heya. You're talking about legacy factories but you're clearly using the new class based factories in your code? Also: please post this on the Lumen framework repo next time if you're experiencing an issue with Lumen. Thanks
