### ISSUE TITLE
Query builder ignores third argument when using `is` operator

### ISSUE THREAD

**Issue by rela589n** [laravel/framework#35899]
- Laravel Version: 7
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL 10

### Description:

What I am trying to do is just add `where` check of not null.
Something like this:

```php
$eloquentQuery->where($this-subQuery(), 'is', 'not null');
```

But this just ignores my third argument and produces something like:

```sql
where (select my_subquery) = 'is'
```

The expected behaviour is:

```sql
where (select my_subquery) is not null
```

BTW, `whereNotNull` doesn't work with subqueries, but columns.
Also I tried to pass `DB::raw()` as second parameter and it also isn't working.

When I pass three arguments, I am sure of what I am doing. Why do the framework just silently ignore value I passed? The logic is very strange.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rela589n** [comment]
Don't you think that if this

```php
$eloquentQuery->where($this-subQuery(), 'is', 'not null');
```

produces this

```sql
where (select my_subquery) = 'is'
```

but not that:

```sql
where (select my_subquery) is not null
```

is not an issue?
Currently it is a stupid behaviour, which creates a bugs. Are you surely going to close this issue like this?
