### ISSUE TITLE
Incorrect MIME boundary generation for Mailable with empty html body

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [laravel/framework#35905]
- Laravel Version: 8.22.1
- PHP Version: 7.4.11
- Database Driver & Version:

### Description:
When sending a Mailable with an empty string as html body, the MIME boundary for the attachment is incorrectly generated.

### Steps To Reproduce:
- Create a test.txt file in storage, with some data 
- Create a mailable with the following code as build():
```
        return $this->html('')
            ->subject('test')
            ->attachFromStorage('test.txt');
```

**Comment by driesvints** [comment]
@AntonioDiPassio-AppSys can you try to apply the same fix from https://github.com/laravel/framework/commit/055762286132d545cbc064dce645562c0d51532f but then for the HTML part a bit above it? Does that fixes your issue?

**Comment by AntonioDiPassio-AppSys** [comment]
@driesvints Yes, this fixes the issue.
