### ISSUE TITLE
HttpClient throw exception

### ISSUE THREAD

**Issue by gittadm** [laravel/framework#35907]
- Laravel Version: #.#.# 8.12
- PHP Version: #.#.# 7.4
- Database Driver & Version:

### Description:

According to documentation https://laravel.com/docs/8.x/http-client#error-handling :

Unlike Guzzle's default behavior, Laravel's HTTP client wrapper does not throw exceptions on client or server errors (400 and 500 level responses from servers). 

But code like this 

 $response = Http::withToken(config('api.auth_token'))
                ->retry(API::RETRY_TIMES, API::RETRY_SLEEP_MILLISECONDS)
                ->timeout(API::TIMEOUT_SECONDS)
                ->post(API::getFullURL($url), $data);

throw RequestException for 422 answer code

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by baceto90** [comment]
I don't know why this issue was closed, but i got the same RequestException even I don't chain ->throw method on Http client.
Obviously the documentation is not accurate at the moment.

**Comment by chris-lee-lb** [comment]
@driesvints we've also faced this issue today, and just as @baceto90 says. In the laravel documentation, HTTP client facade shows it will not explicit throw exception before you use throw method. But retry method was broke this awareness. 

I think it will make a lot of cufuse when people use it. (and this behavior will be aware easily, because retry failed is not common scenario)

Please consider it is a bug. Thanks.

**Comment by bernardwiesner** [comment]
I thought the point of not throwing an exception was to avoid the need of a try catch and handling it with $response->failed(). But we still need a try catch because not all exceptions are caught...

**Comment by jordanade** [comment]
I just got bit by this bug in Laravel 10. Retry() causes undocumented/inconsistent behavior. Why is this bug closed??

**Comment by matt-ostrom-hall-rss** [comment]
For anyone landing here looking for a resolution, the retry method has a throw parameter that you can set to stop the retry throwing an exception

**Comment by tobias-kuendig** [comment]
Full example:

```php
$response = Http::withToken($token)
        ->retry(5, 1000, $callback, throw: false)
        ->post();
```

Docs: https://laravel.com/api/11.x/Illuminate/Http/Client/PendingRequest.html#method_retry
