### ISSUE TITLE
Problem with load blade components

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [laravel/framework#35903]
- Laravel Version: 8.20.1
- PHP Version: 8
- Database Driver & Version:

I have an issue about load blade component in laravel 8 when i try use props i always got and error about undifiend variable $variablename
i got this error just on mac os i tried to change component class name and also i tried to register component manually in appServiceprovider boot method but i had no luck
`

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
/**
* Create a new component instance.
*
* @return void
*/
public function __construct()
{
//
}

/**
 * Get the view / contents that represent the component.
 *
 * @return \Illuminate\Contracts\View\View|string
 */
public function render()
{
    return view('components.alert');
}
}`

blade:
@props(['frontContent'])
div
{{$frontContent}}
/div

### Steps To Reproduce:
php artisan make:component Alert

**Comment by driesvints** [comment]
Hey @ehsantalkhouncheh. Maybe you misunderstood me but with a support channel I meant one of these:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
