### ISSUE TITLE
Segmentation fault by running tests

### ISSUE THREAD

**Issue by N3XT0R** [laravel/framework#35932]
- Laravel Version: 8.x branch
- PHP Version: 7.3
- Database Driver & Version: same as in the docker-compose file, because i am using this one to create containers. 

### Description:
Segmentation fault

I was trying to execute the actual existing tests inside the project. Actually i have a Segmentation fault error on running them.
Was trying to look how much coverage is there, i've already tried to increase the memory limit up to 16 GB, but same effect. 
Can anyone help out or give some useful information ? 

### Steps To Reproduce:

vendor/bin/phpunit

**Comment by GrahamCampbell** [comment]
Any segfaults are a bug in PHP. Please isolate the cause and report at bugs.php.net.

**Comment by GrahamCampbell** [comment]
If you are having trouble running the tests, you can run them using `./bin/tests.sh`, which runs the tests entirely using Docker.

**Comment by GrahamCampbell** [comment]
NB Laravel actually deleted it's phpunit code coverage config recently, so you won't get proper metrics unless you setup the include uncovered files stuff.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
