### ISSUE TITLE
While using SQL Server database, changing a "datetime" column will change its type to "datetime2(6)"

### ISSUE THREAD

**Issue by gopalkildoliya** [laravel/framework#35940]
- Laravel Version: 6.18.24
- PHP Version: 7.3.23
- Database Driver & Version: sqlsrv

### Description:
When using SQL Server as database, if we change a *DateTime* column with migrations, it will change column type from `datetime` to `datetime2(6)`

### Steps To Reproduce:

STEP 1 - Create a table with a column of DateTime type.

```
Schema::table('ThroughputHistory', function (Blueprint $table) {
            $table->dateTime('Date');
        });
```
This executes following statement and creates a column with type `datetime`.
```
alter table "ThroughputHistory" add "Date" datetime not null
```

STEP 2- Now if we change this column and make it nullable as following

```
Schema::table('ThroughputHistory', function (Blueprint $table) {
            $table->dateTime('Date')->nullable()->change();
        });
```
In this case it will change the column type also to `DATETIME2(6)`
```
ALTER TABLE ThroughputHistory ALTER COLUMN Date DATETIME2(6)
```

**Comment by driesvints** [comment]
Please see many other opened issues about this here: https://github.com/laravel/framework/issues?q=is%3Aissue+datetime2+is%3Aclosed

We don't control the code for this as this is done by DBAL.
