### ISSUE TITLE
Collection sortBy does not work if collection elements are stdClass

### ISSUE THREAD

**Issue by tm1000** [laravel/framework#35947]
- Laravel Version: 8.23.1
- PHP Version: 7.4.13
- Database Driver & Version: 10.5.8-MariaDB-1:10.5.8+maria~focal

### Description:

When running raw database queries through illuminate the returned response is a collection of stdClass objects (This is because the default fetch mode for PDO is set to PDO::FETCH_OBJ). I'm not sure if this is the intended result but these objects can't be sorted because stdClass does not implement the ArrayAccess interface. Thus when Laravel Collections tries to sort the collection all results end up returning null and it's unsortable.

I would say this is a non issue at first but because any queries return a collection one would think it should work. I assume other methods from collections will have issues from any raw results as well.

### Steps To Reproduce:

```
$a = new stdClass();
$a->name = 'a';
$b = new stdClass();
$b->name = 'b';
$c = new stdClass();
$c->name = 'c';

$collect = collect([$b, $a, $c]);

$collect = $collect->sortBy([['name', 'asc']]);
```

**Output:**
```
array (
  0 => 
  (object) array(
     'name' => 'b',
  ),
  1 => 
  (object) array(
     'name' => 'a',
  ),
  2 => 
  (object) array(
     'name' => 'c',
  ),
)
```

A "quick" fix online is to just cast all stdClass to array through map then sort:

```
$collect = $collect->map(function ($x) {
    return (array) $x;
});

$collect = $collect->sortBy([['name', 'asc']]);
```

**Output:**
```
array (
  0 => 
  array(
     'name' => 'a',
  ),
  1 => 
  array(
     'name' => 'b',
  ),
  2 => 
  array(
     'name' => 'c',
  ),
)
```

This does indeed correct the issue but it seems to over complicate something that I think collections could detect. That being the usage of stdClass which can be temporarily converted to perform the desired functions.

**Comment by derekmd** [comment]
Your example `Collection@sortBy()` call will need to follow the documentation's example: https://laravel.com/docs/8.x/collections#method-sortby The query `Builder@orderBy()` method allows defining the sort direction parameter for values `'asc'` or `'desc'` but Laravel's collection sort methods don't support such a parameter.

Instead call `$collect->sortBy('name')` (ascending) or `$collect->sortByDesc('name')`:

```php
$a = new stdClass;
$a->name = 'a';
$b = new stdClass;
$b->name = 'b';
$c = new stdClass;
$c->name = 'c';

collect([$b, $a, $c])->sortBy('name');
// => Illuminate\Support\Collection {
//   all: [
//     1 => {
//       "name": "a",
//     },
//     0 => {
//       "name": "b",
//     },
//     2 => {
//       "name": "c",
//     },
//   ],
// }

collect([$b, $a, $c])->sortByDesc('name');
// => Illuminate\Support\Collection {
//   all: [
//     2 => {#3419
//       "name": "c",
//     },
//     0 => {
//       "name": "b",
//     },
//     1 => {
//       "name": "a",
//     },
//   ],
// }
```

If you have a look at the framework's call stack for `Collection@sortBy()`, you can see it does support `stdClass` properties through the `data_get()` global helper function:

* `Illuminate\Support\Collection@sortBy()`
* calls `Illuminate\Support\Traits\EnumeratesValues@valueRetriever()`
* which calls `data_get()` in file `Illuminate/Support/helpers.php`

```php
$c = new stdClass;
$c->name = 'c';
data_get($c, 'name');
// => "c"
```

**Comment by tm1000** [comment]
@derekmd scroll down a bit further in the documentation you linked and you will see that what I said works.

**Comment by tm1000** [comment]
I added a fix in the linked PR against the function `sortByMany` which exists in Collection to support using data_get over Arr::get

**Comment by derekmd** [comment]
> This was added in 8.x it appears as this section does not appear in 7.x or lower

Ah sorry, I was mistakenly looking at a stale 7.x branch on my local machine and I didn't realize multi-sort was added by 8.x.

The original `sortByMany()` change was submitted on the `Arr` class so it looks like it was never fully adjusted when the method was moved to `Collection`. Your `data_get()` pull request will fix it but some tests should probably be added to ensure the feature doesn't get broken in the future.

This (less pretty) arrow function syntax also works to handle `stdClass` multi-sorts:

```php
collect([$b, $a, $c])->sortBy([
    fn($a, $b) => strcmp($a->name, $b->name), // name asc
    fn($a, $b) => $b->id - $a->id, // id desc
]);
```

**Comment by tm1000** [comment]
Thanks @derekmd. I thought about doing that as well. However I'm being told by @GrahamCampbell that Collections `Collections are intended to wrap arrays, not objects.` so at this point I really don't know what the answer is. If anything the documentation should state something to the effect that Objects are not supports in Collections (even though Illuminate returns a Collection of stdClass for results that aren't eloquent)

🤷‍♂️
