### ISSUE TITLE
BUG: `without` does not work on morphTo relations

### ISSUE THREAD

**Issue by bdteo** [laravel/framework#35954]
- Laravel Version: 7.28.3
- PHP Version: 7.3.18
- Database Driver & Version: mysql/MySQL 8.0.17

### Description:
Let's say we have the following:
```
$results = $someModel->with(
    [
            'someMorphToRelation' => function (MorphTo $query) {
                return $query->without(
                    [
                        'images',
                    ]
                );
            }
    ]
)->get();
```
A model returned by the `someMorphToRelation` defines `protected $with = ['images'];`

### Steps To Reproduce:

- Define a model that has a `MorphTo` relation
- Define `protected $with = ['anyRelation'];` on a model returned by the MorphTo relation
- Fetch the model defining the `MorphTo` relation while also eager loading that `MorphTo` relation, setting `->without(['anyRelation'])` on the eager load
- Dump the results and see that `->without(['anyRelation'])` had no effect at all and `anyRelation` is still eager loaded.

**Comment by taylorotwell** [comment]
Pull requests welcome.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by cweiske** [comment]
Still happens with laravel 11.34.2.
