### ISSUE TITLE
Cannot use table alias when using soft deletes

### ISSUE THREAD

**Issue by semiherdogan** [laravel/framework#35953]
- Laravel Version: 8.22.1
- PHP Version: 8.0.0
- Database Driver & Version: Mysql & 8.0.22

### Description:
If i have soft deletes in a model, when i use "from" method to add table alias soft delete query not updating.

### Steps To Reproduce:
Create table with soft deletes and query with table alias 

For example this is ok.

```php
\App\Models\Product::toSql()
```

```sql
select * from products where products.deleted_at is null
```

---

But in this scenario `products.deleted_at`should be `p.deleted_at`

```php
\App\Models\Product::from('products', 'p')->toSql()
```

```sql
select * from products as p where products.deleted_at is null
```

---

As for the workaround i am using `withTrashed` method like below:

```php
\App\Models\Product::from('products', 'p')->withTrashed()->whereNull('p.deleted_at')->toSql()
```

```sql
select * from products as p where p.deleted_at is null
```

Am i missing something?

Let me know if you need further information.

**Comment by taylorotwell** [comment]
Pull requests welcome.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
