### ISSUE TITLE
MorphMany withTrashed is not working

### ISSUE THREAD

**Issue by yankewei** [laravel/framework#35969]
- Laravel Version: 8.21.0
- PHP Version: 7.4.9
- Database Driver & Version: Mysql & 8.0.21

### Description:
I have three tables on db.
```
-  comments
    - id
    - body
    - commentable_id
    - commentable_type
    - deleted_at

- posts
    - id
    - title
    - deleted_at

- video
    - id
    - title
    - url
```
These three tables correspond to three models.
```php
class Comment extends Model
{
    use SoftDeletes;

    public function commentable()
    {
        return $this->morphTo();
    }
}

class Post extends Model
{
    use SoftDeletes;
    
    public function comments()
    {
        return $this->morphMany('App\Models\Comment', 'commentable');
    }

}

class Video extends Model
{

    public function comments()
    {
        return $this->morphMany('App\Models\Comment', 'commentable');
    }
}
```
Now I want to get the comment, and the entity corresponding to the comment. Notice, **comment model is using soft delete**
```php
Comment::with(['commentable' => function (MorphTo $query) {
    return $query->withTrashed();
}])->get();

// This working fine.
```

Then, comment does not use soft delete. 
```php
class Comment extends Model
{
    // use SoftDeletes;

    public function commentable()
    {
        return $this->morphTo();
    }
}
```
I got an exception:
`BadMethodCallException : Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()`, it look like get video entity is failed.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
