### ISSUE TITLE
Constrained foreignIdFor doesn't work for Models with a customized table name

### ISSUE THREAD

**Issue by elbojoloco** [laravel/framework#35963]
- Laravel Version: 8.23.1
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.29

### Description:
When dealing with models that have a different table name than the expected snake cased and pluralized version of the model's name it's not possible to use `$table->foreignIdFor(UnconventionalModel::class)->constrained()` to automatically set the constraint. If the model contains a customized table name, that should be used instead for this to work.

### Steps To Reproduce:
1. Create a fresh Laravel app with a database
2. Create a new model 
3. Create a table for that model that doesn't match the snake cased and pluralized model name, for this example I'll use a model `UserRole` with a table `roles`. The expected table name here would be `user_roles`.
3. Give that table at least an ID using `$table->id()`
4. Create a new migration to add foreign ID column to the `users` table and use the foreignIdFor method: `$table->foreignIdFor(UserRole::class)->constrained()`
5. Run your migrations

If you were to change `foreignIdFor` to just `foreignId` where you explicitly pass the column name it will work as expected: `$table->foreignId('role_id')->constrained()`

**Comment by taylorotwell** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/463230/105224126-66fffc00-5b22-11eb-856f-e8ffd5710258.png">

Here is what the code does. If it doesn't do what you want use a more manual method of specifying your foreign key.

**Comment by bramceulemans** [comment]
You can pass a table name to `->constrained($table);`
