### ISSUE TITLE
ShouldBeEncrypted job contract not working as expected

### ISSUE THREAD

**Issue by JackWH** [laravel/framework#35964]
- Laravel Version: 8.23.1
- PHP Version: 7.4.1
- Database Driver & Version: MariaDB 10.5.8

### Description:
* PR #35527 introduced Job Encryption, and its code was tidied up later in f80f647852106942e4a0ef3e9963f8f7a99122cf.
* I tried adding `ShouldBeEncrypted` to two separate database job classes — an event listener and a `Notification` — both of which implement `ShouldQueue`.
* The jobs are added to the database, but the `command` property is not encrypted.

### Steps To Reproduce:

1. Open `src/Illuminate/Queue/Queue.php` in your IDE
2. Set a breakpoint at [line 154](https://github.com/laravel/framework/blob/d7f27d534807a731bbb487712d7fb35c4a2d6817/src/Illuminate/Queue/Queue.php#L154)
3. You will see that `$job instanceof ShouldBeEncrypted` evaluates to `false`, and the job is not encrypted.

The `$job` property appears to be an instance of `Illuminate\Queue\CallQueuedHandler@call` when entered in to the database. I'm not sure why this would be, as the queue handler internals are a little out of my depth... any clues would be appreciated. Thanks in advance.

**Comment by themsaid** [comment]
This currently works only with jobs dispatched from the bus `Job::dispatch()` or `dispatch(new Job)`. It doesn't work with events or notifications because I thought these records won't hold any sensitive data.

**Comment by driesvints** [comment]
@JackWH we'll make this work with other queueables soon.

**Comment by amberlampsio** [comment]
issue was resolved here, https://github.com/laravel/framework/pull/36036
