### ISSUE TITLE
FormRequest url rule fail if contain ・

### ISSUE THREAD

**Issue by paul38467** [laravel/framework#35968]
- Laravel Version: 7.28.3
- PHP Version: 7.4.8
- Database Driver & Version: MySQL

### Description:
a valid URL but validation fail: https://ja.wikipedia.org/wiki/レスリー・チャン

### Steps To Reproduce:
```
<input type="text" name="url" value="https://ja.wikipedia.org/wiki/レスリー・チャン"> `fail`

<input type="text" name="url" value="https://ja.wikipedia.org/wiki/レスリーチャン"> `if remove ・ pass`

FormRequest rule:
'url' => 'string|url,
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
