### ISSUE TITLE
Inconsistent behaviour of env helper

### ISSUE THREAD

**Issue by xorock** [laravel/framework#35977]
- Laravel Version: 8.0
- PHP Version: 7.4.11
- Database Driver & Version:

### Description:
I'm testing additional environmental variables passed to docker container. I have secrets file with simple content `export APP_NAME="Laravel test app"` and standard APP_NAME=Laravel variable read from .env file. Docs says:

```
If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null.
```

The second part of the sentence is not entirely correct because env('APP_NAME') will always return "Laravel test app" read from exported var. Now, the problem is that after executing `php artisan config:cache`, `env('APP_NAME')` and `config('app.name')` return 2 different values. Maybe if variable exists in .env and is accessible via $_ENV they should be merged? 

### Steps To Reproduce:
export APP_NAME="Laravel test app"
.env -> APP_NAME=Laravel
php artisan config:cache
echo config('app.name') // after cache: Laravel
echo config('app.name') // before cache: Laravel test app

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by xorock** [comment]
OK, but I have two different values before and after config cache was created and documentation says something different to real life. It's a bug for me.
