### ISSUE TITLE
'tests/Feature/EmailVerificationTest.php' failed after enable email verification

### ISSUE THREAD

**Issue by fen9li** [laravel/framework#35970]
- Laravel Version: Laravel Framework 8.23.1
- PHP Version: PHP 8.0.1
- Database Driver & Version: mysql:8.0

### Description:
'tests/Feature/EmailVerificationTest.php' failed after enable email verification

### Steps To Reproduce:

1. Install Laravel 8 with JetStream, Inertia stack with teams. Migrate.
2. Run all 'tests/Feature/*' successfully.
3. Make below changes to enable email verification.
 
```
$ git diff
diff --git a/app/Models/User.php b/app/Models/User.php
index 3481e75..ea2f8c4 100644
--- a/app/Models/User.php
+++ b/app/Models/User.php
@@ -11,7 +11,7 @@ use Laravel\Jetstream\HasProfilePhoto;
 use Laravel\Jetstream\HasTeams;
 use Laravel\Sanctum\HasApiTokens;
 
-class User extends Authenticatable
+class User extends Authenticatable implements MustVerifyEmail
 {
     use HasApiTokens;
     use HasFactory;
diff --git a/config/fortify.php b/config/fortify.php
index 0226449..b64a87a 100644
--- a/config/fortify.php
+++ b/config/fortify.php
@@ -134,7 +134,7 @@ return [
     'features' => [
         Features::registration(),
         Features::resetPasswords(),
-        // Features::emailVerification(),
+        Features::emailVerification(),
         Features::updateProfileInformation(),
         Features::updatePasswords(),
         Features::twoFactorAuthentication([
$
```

4. Run below test failed

```
$ sail test tests/Feature/EmailVerificationTest.php 

   FAIL  Tests\Feature\EmailVerificationTest
  ⨯ email verification screen can be rendered
  ✓ email can be verified
  ✓ email can not verified with invalid hash

  ---

  • Tests\Feature\EmailVerificationTest > email verification screen can be rendered
  Expected status code 200 but received 500.
  Failed asserting that 200 is identical to 500.

  at tests/Feature/EmailVerificationTest.php:30
     26▕         ]);
     27▕ 
     28▕         $response = $this->actingAs($user)->get('/email/verify');
     29▕ 
  ➜  30▕         $response->assertStatus(200);
     31▕     }
     32▕ 
     33▕     public function test_email_can_be_verified()
     34▕     {


  Tests:  1 failed, 2 passed
  Time:   17.19s

$ 
```

However, when I tried to register user manually, it works well. Please help on this. Thank you!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by SimplyCorey** [comment]
Anyone who comes across this can modify the test to this if they have teams enabled to get this to pass:

```
    public function test_email_verification_screen_can_be_rendered()
    {
        if (! Features::enabled(Features::emailVerification())) {
            return $this->markTestSkipped('Email verification not enabled.');
        }

        $user = User::factory()
            ->withPersonalTeam()
            ->create([
                'email_verified_at' => null,
            ]);

        $response = $this->actingAs($user)->get('/email/verify');

        $response->assertStatus(200);
    }
```
