### ISSUE TITLE
app()->runningInConsole() returns true when invoked inside of a queued job ?

### ISSUE THREAD

**Issue by vesper8** [laravel/framework#35980]
- Laravel Version: 7.30.3
- PHP Version: 7.4.14

### Description:

I noticed that `app()->runningInConsole()` returns true when being checked inside of a queued job. I did not expect this behaviour. I extend the ConsoleOutput class so that it gives me colourful feedback when running manually via the CLI and otherwise logs the feedback to the log file when not run in the CLI. I was surprised to see that queued jobs (redis queue driver) are considered as being run on the CLI. Not sure if this is a bug or intended. If intended, is there a way to detect whether code is being run manually on the CLI vs being run inside of a queued job 

### Steps To Reproduce:

Inside a controller function

```
    public function jobTest()
    {
        logger()->debug(sprintf('JobController - Running in console? %s', app()->runningInConsole())); // returns false

        dispatch(new \App\Jobs\JobTest());
    }
```

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class JobTest implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function handle()
    {
        logger()->debug(sprintf('JobTest - Running in console? %s', app()->runningInConsole())); // returns true ?!
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
