### ISSUE TITLE
blade components do not accept spaces in a parameter assignment

### ISSUE THREAD

**Issue by sdbruder** [laravel/framework#35994]
- Laravel Version: 8.23.1
- PHP Version: 8.0.0
- Database Driver & Version: mysql (not relevant here)
### Description:

Blade components do not allow spaces in parameter assignment, so something like this does not work:
```
    <x-a
        class     = "bg-red-300"
        parameter = "bg-yellow-300"
    >
        A SLOT.
    </x-a>
```
but the exact same component used like this works:
```
    <x-a
        class="bg-red-300"
        parameter="bg-yellow-300"
    >
        A SLOT.
    </x-a>

```
### Steps To Reproduce:

Just add spaces  around equal in blade component parameter assignment.

### Steps To Solution:

If that behaviour is ok at least it needs to be documented. If it's not ok then it needs to be fixed.

**Comment by driesvints** [comment]
This isn't supported sorry.

> If that behaviour is ok at least it needs to be documented.

I don't agree with this sorry. We can't document every single exception. I even think the syntax you've shown isn't valid to begin with.

**Comment by sdbruder** [comment]
> ... I even think the syntax you've shown isn't valid to begin with.
To the extent of my knowledge that is ok for HTML in any known browser, and if the intention of a blade component is to mimick HTML, IMHO this a limitation.

just tested, it's ok for HTML be formatted like that (multiple lines and with spaces in assignments).

**Comment by driesvints** [comment]
Maybe for HTML so but in Blade this isn't supported sorry.
