### ISSUE TITLE
[6.x] - api requests getting 401 unauthorized

### ISSUE THREAD

**Issue by vmitchell85** [laravel/framework#36006]
- Laravel Version: 6.18.27+
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
We've got an app that has been using Passport for a while for local api calls. There has been many developments on this front, most notably Sanctum, but we can't move to that yet. With the release of 6.18.27 all our api calls fail. Another user @danielsefton mentioned this in #33662 but I was unable to locate and issue where this was mentioned.

Thanks in advance for your time.

### Steps To Reproduce:
- Install example repo: https://github.com/vmitchell85/laravel-bug-demo - this includes
    - laravel 6.18.26
    - laravel ui
    - following these instructions: https://vincemitchell.me/blog/consuming-your-own-api/
    - modifying default  `ExampleComponent.Vue` to hit the default `/api/user` route and output to console
- Configure with a database
- Register and login
- Visit `\home` and check console to see user information printed
- update `laravel\framework` in composer.json to `6.18.27`
- run `composer update`
- log back in
- Visit `\home` and check console to see user information call gets 401

**Comment by taylorotwell** [comment]
Is your Passport installation up to date? What version is it?

**Comment by vmitchell85** [comment]
Looks like upgrading 6 to latest and Passport to 9 latest is working. I mistakenly thought I was stuck on passport 7.

Closing as my demo project is working now, will test with real app.

Sorry for wasting your time. Thanks for all the hard work on Laravel!

**Comment by vmitchell85** [comment]
Confirmed, all is well... sorry again.
