### ISSUE TITLE
Exceptions that are thrown in Request::capture() is not handled by the error handler

### ISSUE THREAD

**Issue by KMLX28** [laravel/framework#36024]
- Laravel Version:  8 (last version)
- PHP Version: 7.4.10
- Database Driver & Version: MySql 5.6

### Description:
Exceptions that are thrown in `index.php`  in `Request::capture()` is not handled by the error handler `\App\Exceptions\Handler.php`.

In my case: there is an antivirus in the server which deletes any infected uploaded file. When the user uploads an infected file. what happens is: 

1. the user uploads file.
2. PHP puts the file path in the global request.
3. the antivirus deletes the file.
4. Symfony tries to construct the file here `SymfonyRequest::createFromGlobals()`
5. Symfony checks the file here `vendor/symfony/http-foundation/File/File.php`: 

```
    public function __construct(string $path, bool $checkPath = true)
    {
        if ($checkPath && !is_file($path)) {
            throw new FileNotFoundException($path);
        }

        parent::__construct($path);
    }

```

6. exception is thrown and it's going to show it in the browser (security issue)
`Fatal error: Uncaught Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: The file "/tmp/php6CKu5H" does not exist in /home/vagrant/code/eskan/vendor/symfony/http-foundation/File/File.php on line 35`

### Steps To Reproduce:
1. Set up fresh Laravel installment.
2. throw the error in `vendor/symfony/http-foundation/File/File.php` like this: 
```
    public function __construct(string $path, bool $checkPath = true)
    {
            throw new FileNotFoundException($path);
        if ($checkPath && !is_file($path)) {
        }

        parent::__construct($path);
    }

```

Note: any thrown error in `Request::capture()` can have the same case.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by KMLX28** [comment]
Thank you for the quick response, but I **don't** think this is a question, this an issue regarding error handling.

**Comment by driesvints** [comment]
Please create a repo that reproduces this problem. Please commit your custom changes separately from the base Laravel skeleton.

**Comment by KMLX28** [comment]
> Please create a repo that reproduces this problem. Please commit your custom changes separately from the base Laravel skeleton.

I can't since the only change is in the `vendor`.

simply, with a fresh installment, throw an exception in `Illuminate\Http\Request::capture()` in index.php.

I think there is a lot of things that can go wrong while building the request instance, so there should be a reason for not handling the error during `Request::capture()` by the handler, or it's an issue. 

* I find a way to hide the error by setting disabling 'display_errors'.
