### ISSUE TITLE
[6.x] TrimStrings middleware $except nested array attributes

### ISSUE THREAD

**Issue by 2acode** [laravel/framework#36040]
- Laravel Version: 6.20.14
- PHP Version: 7.2.25

### Description:
In middleware TrimStrings nested array attributes declared in $except are ignored: the array values are trimmed anyway.
Similar to https://github.com/laravel/framework/pull/26350

### Steps To Reproduce:
protected $except = ['lines.description']; // OK
protected $except = ['lines.*.description']; // Ignored

**Comment by driesvints** [comment]
This sounds more of a feature request than a bug. We don't support that atm.
