### ISSUE TITLE
Error occurs during the loading of middleware defined in the controller

### ISSUE THREAD

**Issue by usameavci** [laravel/framework#36045]
I get an error when I define middleware in the controller. May be linked to: c6e8357e19b10a800df8a67446f23310f4e83d1f

- Laravel Version: 8.24.0
- PHP Version: 7.4.7
- Database Driver & Version: Mysql v8.0.19

### Description:
![image](https://user-images.githubusercontent.com/6714468/105769164-76da6e80-5f6e-11eb-960b-119be5d22348.png)

### Steps To Reproduce:
Add this code block below to controller's __construct method:
```php
$this->middleware(function($request,$next) {
    return $next($request);
});
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by usameavci** [comment]
I just updated it to the new version 8. In the previous version this code was working. It started to error after the update. The documentation says that Closure can be used, but the code block in this commit (c6e8357) has not checked the Closure. The code is already giving an error due to this ERROR. "class_exists () expects parameter 1 to be string, object given" Don't you think this is an error?


Ref:  `* @param  \Closure|array|string  $middleware` https://github.com/laravel/framework/blob/e93c478adc5f1524d3dc77fea53a3c4cd34fd79b/src/Illuminate/Routing/Controller.php#L16-L30

**Comment by usameavci** [comment]
> I just updated it to the new version 8.24.0. In the previous version (8.5.0) this code was working. It started to error after the update. The documentation says that Closure can be used, but the code block in this commit ([c6e8357](https://github.com/laravel/framework/commit/c6e8357e19b10a800df8a67446f23310f4e83d1f)) has not checked the Closure. The code is already giving an error due to this ERROR. "class_exists () expects parameter 1 to be string, object given" Don't you think this is an error?
> 
> Ref: `* @param \Closure|array|string $middleware`
> 
> https://github.com/laravel/framework/blob/e93c478adc5f1524d3dc77fea53a3c4cd34fd79b/src/Illuminate/Routing/Controller.php#L16-L30

What do you think? @driesvints

**Comment by driesvints** [comment]
@usameavci this all just works for me on 8.x

**Comment by usameavci** [comment]
I had the opportunity to examine the situation a little more. When I set up and tested the project from scratch, I didn't see a problem either. After examining it, I saw that this situation occurred after such a procedure.

- First of all, we define a route and exclude middleware from the route.
https://github.com/usameavci/laravel-test/blob/c172958c046a8b7c44826de841998e622972e597/routes/web.php#L1-L18

- Later, we define another dynamic middleware in the controller's __construct() method that we point the route.
https://github.com/usameavci/laravel-test/blob/c172958c046a8b7c44826de841998e622972e597/app/Http/Controllers/Controller.php#L14-L24

It gives this error after these operations. I attach the sample project below.

https://github.com/usameavci/laravel-test

I will be glad if you can examine it. Thanks @driesvints

**Comment by driesvints** [comment]
@usameavci it's best that you send in a PR with a failing test that proves this is broken.
