### ISSUE TITLE
Http test header not available from service provider

### ISSUE THREAD

**Issue by chris-rs** [laravel/framework#36052]
- Laravel Version: 8.23.1
- PHP Version: 7.4.12
- Database Driver & Version: Postgres 10

### Description:
When using HTTP tests in feature test I like to send custom headers along with the request.
`$this->withHeaders([
            'Accept'    => 'application/vnd.laravel+json;version=2.0'
 ]);`
This header is used for versioning: In the route service provider the Accept header is inspected and used to load appropriate routes. But from a feature test I am not able to process the custom accept header.
The custom accept header is available in the controller itself, but not in the route service provider.

### Steps To Reproduce:

- Create a feature test
- Perform an Http call and inspect the request headers from a service provider
```php
<?php

namespace Tests\Feature\FeatureTest;

use Tests\TestCase;

class FeatureTest extends TestCase
{
    public function setUp(): void
    {
    	parent::setUp();
    }

    public function tearDown(): void
    {
    	parent::tearDown();
    }

    public function test_http_custom_header()
    {
    	$this
            ->withHeaders([
               'Accept'    => 'application/vnd.laravel+json;version=2.0'
            ])
            ->get('/api/test')
            ->dump()
            ->assertStatus(200);
    }
}
```
```php
<?php

namespace App\Providers;

class RouteServiceProvider extends ServiceProvider
{
    public function boot()
    {
        dump(request()->headers);
    }
}
```

**Comment by taylorotwell** [comment]
Service providers are run before routes and middleware.
