### ISSUE TITLE
Parallel testing doesn't use squashed database dump file

### ISSUE THREAD

**Issue by BertvanHoekelen** [laravel/framework#36057]
- Laravel Version: 8.25.0
- PHP Version: 8.0.1
- Database Driver & Version: Mysql 8.0

### Description:
When running tests in parallel the php migrations fail because the squashed database is not migrated.

### Steps To Reproduce:
- Use the `DatabaseTransactions` trait in your TestCase.php.
- Have a squashed database file e.g. `database/schema/test-schema.dump`
- Do an assertion on a table created in the dump file.
- Run `php artisan test --parallel --recreate-databases --stop-on-failure`

### Possible solutions:
1. Add `schemaPath` method to `ParallelTesting ` to define the schema path used when migrating the created databases.
2. Use the original schema path of the database defined in phpunit.xml. So if `DB_CONNECTION=testing` it should use `database/schema/testing-schema.dump`

**Comment by driesvints** [comment]
@BertvanHoekelen why did you close this again? Did you find a solution?

**Comment by BertvanHoekelen** [comment]
I tried it in a new laravel project and there it just works. Somehow in my application the package migrations are already migrated before `TestDatabase::ensureSchemaIsUpToDate()` calls `Artisan::call('migrate')`. I need to investigate more and come up with good steps to reproduce.

**Comment by BertvanHoekelen** [comment]
Found the actual issue `loadSchemaState` won't get called because it thinks there are already (package) migrations executed.

You can checkout: https://github.com/BertvanHoekelen/laravel-parallel-testing-example and then run ` php artisan test --parallel --stop-on-failure --recreate-databases --processes=4`

**Comment by BertvanHoekelen** [comment]
Sometimes revisiting something later fixes the problem. When I deleted the databases and tried it again it worked.
I think that the problems lies with the test databases getting out of sync when you squash the database.
