### ISSUE TITLE
ParallelRunner expects the CreatesApplication trait to be at the root of the tests folder

### ISSUE THREAD

**Issue by osteel** [laravel/framework#36053]
- Laravel Version: 8.25.0
- PHP Version: 8.0
- Database Driver & Version: N/A

### Description:

On [line 132](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Testing/ParallelRunner.php#L132) of the `ParallelRunner` class, the `createApplication` method expects the `CreatesApplication` trait to be at the root of the application's `tests` folder.

It probably shouldn't make that assumption, since that folder may have been reorganised by the user.

### Steps To Reproduce:

1. move the `CreatesApplication` trait in a `Traits` subfolder of the `tests` folder;
2. run `php artisan test --parallel`.

**Comment by osteel** [comment]
There seems to be [a way](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Testing/ParallelRunner.php#L67) to change the `$applicationResolver` static property of the `ParallelRunner` class, but so far my attempts have failed.

I created the following service provider:

```php
<?php

namespace App\Providers;

use Illuminate\Testing\ParallelRunner;
use Illuminate\Testing\ParallelTestingServiceProvider as BaseProvider;

class ParallelTestingServiceProvider extends BaseProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        ParallelRunner::resolveApplicationUsing(function () {
            $applicationCreator = new class {
                use \Tests\Traits\CreatesApplication;
            };

            return $applicationCreator->createApplication();
        });
    }
}
```

And I added it to the list of application providers in `config/app.php`.

It seems to be ignored so far – am I missing something?

Thanks,

Yannick

**Comment by taylorotwell** [comment]
Why would this folder or file be moved by the user?

**Comment by osteel** [comment]
Why is this file in this folder and not in the `vendor` folder in the first place? So it can be extended or modified, right?

In my case I've got a number of traits in my tests, so I move them under a `Traits` subfolder for clarity. I don't know what other people may or may not do, my point is that from the moment a file is not in the `vendor` folder, the framework should not assume what happened to it.

Otherwise that'd mean you are willing to dictate how your users organise their files in the pre-existing structure, which sends a worrying message in my opinion.

**Comment by kozlikov** [comment]
After updating, I started getting this error on Windows server:
```
During class fetch: Uncaught ErrorException: include(C:\www\test\laravel\vendor\composer/../laravel/framework/src/Illuminate/Testing/Concerns/TestDatabases.php): Failed to open stream: No such file or directory in C:\www\test\laravel\vendor\composer\ClassLoader.php:444
```

**Comment by taylorotwell** [comment]
Don't move the file.

**Comment by osteel** [comment]
This is just wrong, but I know there's no point arguing with you.

**Comment by michielkempen** [comment]
I completely agree with @osteel here.

At our company, we follow the convention from languages such as Go and put our tests in the same directory as our application code.

Having a separate nearly empty tests directory is pointless in this case, so we remove it and move the CreatesApplication trait to a different location. A strategy that has worked perfectly for us, up to this point.

Laravel is extremely flexible, and we love it for this. But "Don't move the file" doesn't fit its philosophy.

**Comment by driesvints** [comment]
I've sent in a PR to the docs to hopefully make it clear in the future that the trait should stay in place: https://github.com/laravel/docs/pull/6789

**Comment by osteel** [comment]
@driesvints that's something, but if that file is not supposed to be changed, then I think it should be in the `vendor` folder.

With this new feature the framework introduces a hard link to a file that Laravel users were free to update thus far. Effectively, it introduces a breaking change for some users. As part of a minor version release.

One could argue that one doesn't have to use that feature, and that it relates to tests, so it's not a big deal. But if that's a practice the Laravel team is OK with, what will it be next time? What new hard dependency will be introduced? It reduces the confidence users have regarding a part of the codebase they are supposed to have full control over.

Like I said, it sends a worrying message.

**Comment by driesvints** [comment]
> but if that file is not supposed to be changed, then I think it should be in the vendor folder.

While the file shouldn't switch location, the contents of the trait can still be modified which could be useful in certain situations. 

> With this new feature the framework introduces a hard link to a file that Laravel users were free to update thus far. Effectively, it introduces a breaking change for some users. As part of a minor version release.

You are not required to use parallel testing if you don't want to like you said. To be honest I definitely understand your remarks but I personally think it's no big deal for such a small piece of code.

**Comment by osteel** [comment]
@driesvints it seems that @nunomaduro kind of planned for this with the `$applicationResolver` static property of the `ParallelRunner` class. Can we hook into it somehow, like I attempted to in my second comment in this issue?

When such hard links are introduced, I think it's fair to expect a way to go around it to be provided as well.

In any case, thank you for being respectful and actually taking the time (not just in this instance). I think others would be inspired to do the same.

**Comment by crynobone** [comment]
@osteel I been looking at using the method as well for Orchestra Testbench but it's just not possible. Basically the test command pass `Illuminate\Testing\ParallelRunner` class string as an argument to paratest to run everything under a separate child process. 

There a PR to remove said method to avoid any further confusion.

**Comment by driesvints** [comment]
> Can we hook into it somehow, like I attempted to in my second comment in this issue?

Seems like that's unfortunately not possible as Mior describes above.

> In any case, thank you for being respectful and actually taking the time (not just in this instance). I think others would be inspired to do the same.

Welcome :)

**Comment by crynobone** [comment]
The alternative right now is to use a custom Runner class and add `--runner` options when using parallel testing.

Based on your structure.

```php
<?php

namespace Tests;

class ParallelRunner extends \Illuminate\Testing\ParallelRunner
{
    /**
     * Creates the application.
     *
     * @return \Illuminate\Contracts\Foundation\Application
     */
    protected function createApplication()
    {
        $applicationCreator = new class {
            use Traits\CreatesApplication;
        };

        return $applicationCreator->createApplication();
    }
}
```

and then use:

```
php artisan test --parallel --runner="\Tests\ParallelRunner"
```

**Comment by osteel** [comment]
@crynobone will give this a try when I get a minute, thank you

**Comment by osteel** [comment]
@crynobone that worked 👍

**Comment by taylorotwell** [comment]
I'll just implement Nuno's PR before there is more drama around it.

**Comment by taylorotwell** [comment]
Done.
