### ISSUE TITLE
/_ignition/execute-solution security bug

### ISSUE THREAD

**Issue by almakano** [laravel/framework#36067]
- Laravel Version: 7.30.1
- PHP Version: 7.2.24
- Facade/ignition: ^2.0

### Description:
Today I found suspicious php file at the public directory, like ScLkgMAo.php
Nginx access logs have records of accessed ip: 185.17.40.152, 71.251.26.120
These ips successfully hitted URL /_ignition/execute-solution with POST method

Can I remove facade/ignition from require-dev section of composer.json and re-update all gracefully ?

**Comment by taylorotwell** [comment]
We don't maintain Ignition. You shouldn't have Ignition or debug mode enabled in production.
