### ISSUE TITLE
Error: Class 'Dotenv\Repository\RepositoryBuilder' not found 

### ISSUE THREAD

**Issue by ZUBAT** [laravel/framework#36062]
- Laravel Version: 8.25.0
- PHP Version: 7.3.6
- Database Driver & Version:

### Description:
after clear install (laravel new) catch error
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
PHP Fatal error:  Uncaught Error: Class 'Dotenv\Repository\RepositoryBuilder' not found in \vendor\laravel\framework\src\Illuminate\Support\Env.php:55
Stack trace:
#0 \vendor\laravel\framework\src\Illuminate\Support\Env.php(76): Illuminate\Support\Env::getRepository()
#1 \vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1052): Illuminate\Support\Env::get('APP_SERVICES_CA...')
#2 vendor\laravel\framework\src\Illuminate\Foundation\Application.php(970): Illuminate\Foundation\Application->normalizeCachePath('APP_SERVICES_CA...', 'cache/services....')
#3 vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(57): Illuminate\Foundation\Application->getCachedServicesPath()
#4 vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(45): Illuminate\Foundation\ComposerScripts::clearCompiled()
#5 phar://C:/ProgramData/ComposerSetup/bin/com in vendor\laravel\framework\src\Illuminate\Support\Env.php on line 55

Fatal error: Uncaught Error: Class 'Dotenv\Repository\RepositoryBuilder' not found in vendor\laravel\framework\src\Illuminate\Support\Env.php:55
Stack trace:
#0 vendor\laravel\framework\src\Illuminate\Support\Env.php(76): Illuminate\Support\Env::getRepository()
#1 vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1052): Illuminate\Support\Env::get('APP_SERVICES_CA...')
#2 vendor\laravel\framework\src\Illuminate\Foundation\Application.php(970): Illuminate\Foundation\Application->normalizeCachePath('APP_SERVICES_CA...', 'cache/services....')
#3 vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(57): Illuminate\Foundation\Application->getCachedServicesPath()
#4 vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(45): Illuminate\Foundation\ComposerScripts::clearCompiled()
#5 phar://C:/ProgramData/ComposerSetup/bin/com in 
\vendor\laravel\framework\src\Illuminate\Support\Env.php on line 55

### Steps To Reproduce:

 laravel new app

**Comment by taylorotwell** [comment]
Working fine for me.

**Comment by jpjadeja777** [comment]
> Working fine for me.

not working for us? what is solution of this error??

**Comment by jpjadeja777** [comment]
what's the step of resolved this
