### ISSUE TITLE
Job batch doesn't work properly with PostgreSQL

### ISSUE THREAD

**Issue by raftx24** [laravel/framework#36061]
- Laravel Version: 8.24.0
- PHP Version: 7.4.13
- Database Driver & Version: PostgreSQL 13.0

### Description:
A serialized object in PHP that has null values before and after private fields like will fail to serialize because Postgres PDO serialization will stop on null values.
Example:  
`"O:1:"A":1:{s:8:"\0A\0field";N;}"`

This is because of [PQescapeStringConn](https://www.postgresql.org/docs/current/libpq-exec.html)  
> A terminating zero byte is not required, and should not be counted in length. (**If a terminating zero byte is found before length bytes are processed, PQescapeStringConn stops at the zero;** the behavior is thus rather like strncpy.) 

Therefore, if we need to store a serialized object into a text Postgres column, it will fail.

Laravel uses serialization for `job_batches.options` and when used with PostgresSQL causes this error:   
```php
 ErrorException 

  Insufficient data for unserializing - 273 required, 90 present

  at vendor/laravel/framework/src/Illuminate/Bus/DatabaseBatchRepository.php:286
    282▕             (int) $batch->total_jobs,
    283▕             (int) $batch->pending_jobs,
    284▕             (int) $batch->failed_jobs,
    285▕             json_decode($batch->failed_job_ids, true),
  ➜ 286▕             unserialize($batch->options),
    287▕             CarbonImmutable::createFromTimestamp($batch->created_at),
    288▕             $batch->cancelled_at ? CarbonImmutable::createFromTimestamp($batch->cancelled_at) : $batch->cancelled_at,
    289▕             $batch->finished_at ? CarbonImmutable::createFromTimestamp($batch->finished_at) : $batch->finished_at
    290▕         );

      +4 vendor frames 
 ```

### Steps To Reproduce:
```php
class A {
    private $field;
}

$a = new A();

Bus::batch([])
    ->then(fn ($batch) => $a)
    ->dispatch();
```

### Possible Fix
We can use base64_encode before inserting & base64_decode after fetching the serialized objects.

If you find this solution ok let me know and I'll create a PR for it.

Thank you. 

References:   
[PostgreSQL: Chapter 33. libpq — C Library](https://www.postgresql.org/docs/current/libpq-exec.html)   
[Text column type doesn't reliably hold serialized variables](https://www.drupal.org/project/drupal/issues/690746)

**Comment by staudenmeir** [comment]
This is the approach we are using to fix the issue in the cache component: #25530

**Comment by taylorotwell** [comment]
I would be fine with that solution as long as we can do it in a backwards compatible way for other database drivers. Or, ideally, not base64_encode at all when using other drivers.

**Comment by raftx24** [comment]
I'll create a PR that will do base64_encode only for PostgreSQL
