### ISSUE TITLE
Fatal error shown when loading the homepage

### ISSUE THREAD

**Issue by brendanmurty** [laravel/framework#36074]
- Laravel Version: 8.25.0
- PHP Version: 7.4.14
- Database Driver & Version: N/A

### Description:

After updating to Laravel 8.25.0, I'm getting a fatal error when loading my homepage.

Reviewing the content in `storage/logs/laravel.log`, I see this:

```
production.ERROR: syntax error, unexpected ')' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected ')' at /.../vendor/laravel/framework/src/Illuminate/Testing/Concerns/TestDatabases.php:148)
```

Removing the comma at the end of line 147 fixes the issue in my testing.

Seems to have been introduced here:
https://github.com/laravel/framework/commit/5edb9fe45a75d226ff7e0b91d2c27d625f022de0#diff-e14de3b8b89927a4173ce411b40520d70feb289b071aa0b7d6cdfb043f3fc696R147

The source code of the website where I encountered this error:
https://github.com/brendanmurty/murty.io

### Steps To Reproduce:

Update to Laravel version 8.25, then load the home page.

**Comment by driesvints** [comment]
You're using a PHP version lower than 7.3

**Comment by le-yo** [comment]
I am on 7.3 and facing the same issue

**Comment by driesvints** [comment]
@le-yo you're definitely using a PHP version lower than 7.3 as PHP 7.3 supports this syntax.

**Comment by thomasbird1984** [comment]
I have the same issue and my server has `v7.4.9`

```
PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

**Comment by driesvints** [comment]
@thomasbird1984 again: you're using a PHP version lower than 7.3. The version which you show above is probably from a different environment and not the one used to run your code (either CLI or web).

**Comment by driesvints** [comment]
See https://3v4l.org/Em5RY

**Comment by thomasbird1984** [comment]
> @thomasbird1984 again: you're using a PHP version lower than 7.3. The version which you show above is probably from a different environment and not the one used to run your code (either CLI or web).

This was directly from ssh on the Ubuntu server just running `php --version` Either way I just went for a workaround and updated the same way as this commit and everything works now:
https://github.com/laravel/framework/pull/36075/commits/65b9da48dd05ab6fa617813cc75bcdd39e054d62

**Comment by driesvints** [comment]
@thomasbird1984 most likely your web server is running a different php version than your CLI version.

**Comment by le-yo** [comment]
@driesvints I am on PHP 7.3.19-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jun 12 2020 07:48:30) ( NTS ) and that issue is still on that version. 

Is there any other reason to upgrade higher than this apart from the Syntax/comma?

**Comment by driesvints** [comment]
@le-yo PHP 7.2 is EoL: https://www.php.net/supported-versions.php

Again: you're not running PHP 7.3. See the working syntax here: https://3v4l.org/Em5RY

**Comment by mohsen2986** [comment]
im change it to php version 7.4 and its  work fine

**Comment by zahidgani** [comment]
"syntax error, unexpected ')'" in vendor/laravel/framework/src/Illuminate/Testing/Concerns/TestDatabases.phpTestDatabases.php


remove the trailing "," in your set function call:

config()->set(
        "database.connections.{$default}.database",
        $database
    );

**Comment by daronjay** [comment]
i can confirm, running Valet with php@8.0, had the same issue, removing these two trailing commas fixed it
