### ISSUE TITLE
Dynamic relationships in laravel using subqueries for belongstomany relationship

### ISSUE THREAD

**Issue by toxifiedmatrix** [laravel/framework#36073]
- Laravel Version: 8.25.0
- PHP Version: 7.4.12
- Database Driver & Version: MySQL

### Description:
As I have been following [Eloquent Performance Patterns by Jonathan Reinink][1], he has explained how to add dynamic relationship using subquery for models with hasmany relationship. But as per my application I need to do the same for belongstomany relationship. Please help me achieve it.

  [1]: https://eloquent-course.reinink.ca/

### Steps To Reproduce:
Here is the example source code of the following, which achieves the said above dynamic relationship using subquery for models with hasmany relationship.
```
$query = User::query()
    ->addSelect(['role' => Role::select('name')
        ->whereColumn('user_id', 'users.id')
        ->latest()
        ->take(1)
    ]);
        
return $this->applySorting($query);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dkulyk** [comment]
Try this
```php
$user = new User();
/** @var BelongsToMany $relation */
$relation = \Illuminate\Database\Eloquent\Relations\Relation::noConstraints(fn () => $user->roles());
$user->newQuery()
    ->addSelect([
        'role' => $relation
            ->select('name')
            ->whereColumn($relation->getQualifiedParentKeyName(), $relation->getQualifiedForeignPivotKeyName())
            ->latest()
            ->take(1),
    ])
```

**Comment by dkulyk** [comment]
Or this:
```php
$user = new User();
($query = $user->newQuery())
    ->addSelect([
        'role' => $user->roles()->getRelationExistenceQuery(Role::query(), $query, ['name'])
            ->latest()
            ->take(1),
    ])
```

**Comment by toxifiedmatrix** [comment]
@dkulyk Thanks alot mate, I'll surely give it a try. 😃
