### ISSUE TITLE
Notifications soft delete testing

### ISSUE THREAD

**Issue by kami16ru** [laravel/framework#36078]
- Laravel Version: 8.18.1
- PHP Version: 7.3.24
- Database Driver & Version: MySQL 8.0.22

### Description:

When testing Notification soft delete controller, after deleteJson method $response->assertStatus shows ok, but checking read_at column shows null instead of right value.

### Steps To Reproduce:

Instead of using auth()->user() I've sent User id threw PHPUnit to show you what clearly controller returns and same method executed from PHPUnit don't.

    public function softDelete(string $id, Request $request)
    {
        $user = User::query()->where('id', '=', $request->user)->first();

        $notification = $user->unreadNotifications->where('id', 'LIKE', $id)->first();

        if ($notification) $notification->markAsRead();
        else return response([
            'message' => 'Notification with given id not found',
            'errors' => 'Notification id ' . $notification . 'not found'
        ], Response::HTTP_NOT_FOUND);

        return $user->unreadNotifications->where('id', 'LIKE', $id)->first();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function test_chat_notifications_api_soft_delete()
    {
        $notification = $this->user->unreadNotifications->random();

        $this->assertNotEmpty($this->user->unreadNotifications
            ->where('id', '=', $notification->id)->first());

        $response = $this->deleteJson(route(
            'api.ticketsystem.chat.notifications.softdelete',
            $notification->id), ['user' => $this->user->id]
        );

      //        dd($response->getContent());

      //        $response->assertStatus(204);

        dd([
            'getcontent' => $response->getContent(),
            'after' => $this->user->unreadNotifications->where('id', 'LIKE', $notification->id)->first()]);

        $this->assertEmpty($this->user->unreadNotifications->where('id', '=', $notification->id)->first());
    }

Output from terminal:
`...........................array:2 [
  "getcontent" => "{"id":"0d51d5f0-64a4-49b2-9825-3ed7cb799b9f","type":"App\\Notifications\\ChatRequestCreatedNotification","notifiable_type":"App\\Modules\\User\\Models\\User","notifiable_id":38,"data":{"chat_request":{"id":25,"message":"test_chat_api_store message","channel_name":"7e7b7f1a-cb18-43a0-bfe7-749d6f8f4c2f1","operators_online":1,"user":{"id":1,"name":"Rosemarie Leannon","email":"lea.wisozk@example.net"},"created_at":"2021-01-28T09:42:46.000000Z","updated_at":"2021-01-28T09:42:46.000000Z"}},"read_at":"2021-01-28T09:42:47.000000Z","created_at":"2021-01-28T09:42:46.000000Z","updated_at":"2021-01-28T09:42:47.000000Z"}"
  "after" => Illuminate\Notifications\DatabaseNotification^ {#242
    #keyType: "string"
    +incrementing: false
    #table: "notifications"
    #guarded: []
    #casts: array:2 [
      "data" => "array"
      "read_at" => "datetime"
    ]
    #connection: "mysql"
    #primaryKey: "id"
    #with: []
    #withCount: []
    #perPage: 15
    +exists: true
    +wasRecentlyCreated: false
    #attributes: array:8 [
      "id" => "0d51d5f0-64a4-49b2-9825-3ed7cb799b9f"
      "type" => "App\Notifications\ChatRequestCreatedNotification"
      "notifiable_type" => "App\Modules\User\Models\User"
      "notifiable_id" => 38
      "data" => "{"chat_request":{"id":25,"message":"test_chat_api_store message","channel_name":"7e7b7f1a-cb18-43a0-bfe7-749d6f8f4c2f1","operators_online":1,"user":{"id":1,"name":"Rosemarie Leannon","email":"lea.wisozk@example.net"},"created_at":"2021-01-28T09:42:46.000000Z","updated_at":"2021-01-28T09:42:46.000000Z"}}"
      "read_at" => null
      "created_at" => "2021-01-28 09:42:46"
      "updated_at" => "2021-01-28 09:42:46"
    ]
    #original: array:8 [
      "id" => "0d51d5f0-64a4-49b2-9825-3ed7cb799b9f"
      "type" => "App\Notifications\ChatRequestCreatedNotification"
      "notifiable_type" => "App\Modules\User\Models\User"
      "notifiable_id" => 38
      "data" => "{"chat_request":{"id":25,"message":"test_chat_api_store message","channel_name":"7e7b7f1a-cb18-43a0-bfe7-749d6f8f4c2f1","operators_online":1,"user":{"id":1,"name":"Rosemarie Leannon","email":"lea.wisozk@example.net"},"created_at":"2021-01-28T09:42:46.000000Z","updated_at":"2021-01-28T09:42:46.000000Z"}}"
      "read_at" => null
      "created_at" => "2021-01-28 09:42:46"
      "updated_at" => "2021-01-28 09:42:46"
    ]
    #changes: []
    #classCastCache: []
    #dates: []
    #dateFormat: null
    #appends: []
    #dispatchesEvents: []
    #observables: []
    #relations: []
    #touches: []
    +timestamps: true
    #hidden: []
    #visible: []
    #fillable: []
  }
]
`

So controller works well setting read_at column, but executing same method in tests leaving read_at column as null.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
