### ISSUE TITLE
(Insecure) Default Papertrail channel settings: plain text over udp 

### ISSUE THREAD

**Issue by jonneroelofs** [laravel/framework#36070]
- Laravel Version: 8.22.1
- PHP Version: 8.0.1
- Database Driver & Version: Mysql

### Description:
Just got started with using papertrail and Laravel together. 
I noticed that the default config in logging.php for the papertrail channel uses the SyslogUdpHandler. However this manner of sending logs to papertrail uses udp with plain text. That seems unwise?

I was wondering if we should protect new / inexperienced laravel users from using this by either changing the defaults or documenting how they might go about using tcp + ssl (tls). Although it took me quite some time to figure out how to do this, it was in the end only a minor tweak to the configuration file (switching to the monolog SocketHandler with a tls connectionString).

Love to hear what you guys think and if I can do anything to help.

Cheers!

### Steps To Reproduce:

**Comment by driesvints** [comment]
Heya. If you want to change this feel free to attempt a PR with a thorough explanation on why that's needed. Thanks

**Comment by prattcmp** [comment]
> Heya. If you want to change this feel free to attempt a PR with a thorough explanation on why that's needed. Thanks

Isn't Papertrail UDP sent as plaintext and therefore insecure without TLS? Surprised this has been closed for so long... unless I'm missing something.
