### ISSUE TITLE
[8.x] Callback in routes does not support object method callable type

### ISSUE THREAD

**Issue by maduranma** [laravel/framework#36079]
- Laravel Version: 8.25.0
- PHP Version: 8.0.1

### Description:
In the routing, you cannot pass a callable array formed by an object and a string (function name), even this is a supported callable.

PHP manual: [https://www.php.net/manual/en/language.types.callable.php](https://www.php.net/manual/en/language.types.callable.php) (type 3)

You can try it like this:
```php
class foo
{
    public function bar()
    {
        echo 'This is a test';
    }
}

$callback = [new foo, 'bar'];
$callback(); // It echoes "This is a test"
```

### Steps To Reproduce:
In the routes file:
```php
class foo {
    public function bar() {
        echo 'This is a test';
    }
}
Route::get(
    '/test',
    [new foo, 'bar']
);
```

This throws an error in ```Illuminate\Routing\RouteAction``` as in line ```34``` it tries to convert the object to a string when concatenating for ```uses``` and ```controller``` in return array.

**Comment by driesvints** [comment]
This isn't supported sorry.
