### ISSUE TITLE
Unexpected Error: Illuminate/Testing/Concerns/TestDatabases.php

### ISSUE THREAD

**Issue by whoami213** [laravel/framework#36083]
Laravel Version: 8.25.0
Laravel Framework: 8.25.0

After `composer update`  from laravel v8.24 to v8.25 it breaks and throws off things.

![image](https://user-images.githubusercontent.com/18107626/106239775-2305a900-623e-11eb-8918-f97937afda56.png)

Error: `syntax error, unexpected ')`

Cause of the Issue:
```php
 protected function switchToDatabase($database)
    {
        DB::purge();
 
        $default = config('database.default');
 
        config()->set(
            "database.connections.{$default}.database",
            $database,
        );
    }
```

Temp solution to Fix:
Commented the switchToDatabase function.

```php
 protected function switchToDatabase($database)
    {
       /* DB::purge();

        $default = config('database.default');

        config()->set(
            "database.connections.{$default}.database",
            $database,
        );*/
    }
```

**Comment by crynobone** [comment]
Hello there, it seems you're using running the page on PHP lower than 7.3. Otherwise, you shouldn't be able to see this error.

**Comment by LastDragon-ru** [comment]
![image](https://user-images.githubusercontent.com/1329824/106256659-ff8a3080-6234-11eb-83a3-d74fa5eb42f0.png)

**Comment by whoami213** [comment]
> Hello there, it seems you're using running the page on PHP lower than 7.3. Otherwise, you shouldn't be able to see this error.

Nope, I'm using PHP 7.4.13
![image](https://user-images.githubusercontent.com/18107626/106405675-0356c680-6472-11eb-9f81-981dbff034e9.png)
![image](https://user-images.githubusercontent.com/18107626/106405648-ee7a3300-6471-11eb-8922-0c37ac6abaaa.png)

I'm not sure what is the main cause of the issue but after updating to ` v8.25.0` of laravel it breaks my code and it's pointing to the Parallel testing.

**Comment by whoami213** [comment]
> > Hello there, it seems you're using running the page on PHP lower than 7.3. Otherwise, you shouldn't be able to see this error.
> 
> Nope, I'm using PHP 7.4.14
> ![image](https://user-images.githubusercontent.com/18107626/106405675-0356c680-6472-11eb-9f81-981dbff034e9.png)
> ![image](https://user-images.githubusercontent.com/18107626/106405648-ee7a3300-6471-11eb-8922-0c37ac6abaaa.png)
> 
> I'm not sure what is the main cause of the issue but after updating to ` v8.25.0` of laravel it breaks my code and it's pointing to the Parallel testing.

In addition, I'm debugging the issue but upon changing the `.env` file to `APP_ENV=local` and `APP_DEBUG=true` the error didn't show up anymore, I'm thinking that the Parallel testing has an issue on the Production environment.

**Comment by driesvints** [comment]
@whoami213 I'm 100% sure you're not using PHP 7.4. This syntax is valid on PHP 7.3 or higher: https://3v4l.org/Em5RY

**Comment by bally86** [comment]
I'm having the same error. Running PHP 7.4.5 x64.
Any solution?

**Comment by driesvints** [comment]
@bally86 you're not running PHP 7.4. Make sure to check your CLI version vs web server binary.

**Comment by bally86** [comment]
I just upgraded to 8.02. Still teh same error:

https://i.imgur.com/IgU7r8k.png

**Comment by driesvints** [comment]
You're definitely not running PHP 8. Most likely you still need to restart your web server.

**Comment by bally86** [comment]
Server is restarted and no other versions exists on the server anymore. 100% PHP 8. Still the same error.

**Comment by bally86** [comment]
Okay, found the issue. The request was a DELETE request and there was a reference to PHP7.2 for DELETE requests in the web.config file. Sorry! Thanks!

**Comment by adirkandel** [comment]
> Okay, found the issue. The request was a DELETE request and there was a reference to PHP7.2 for DELETE requests in the web.config file. Sorry! Thanks!

Could you please elaborate more about your solution?, what do you mean `reference to PHP7.2 for DELETE requests in the web.config file.`

**Comment by dover7** [comment]
just remove the commas before ) 

`        if ($url) {
            config()->set(
                "database.connections.{$default}.url",
                preg_replace('/^(.*)(\/[\w-]*)(\??.*)$/', "$1/{$database}$3", $url)
            );
        } else {
            config()->set(
                "database.connections.{$default}.database",
                $database
            );`

**Comment by aliparsa** [comment]
> You're definitely not running PHP 8. Most likely you still need to restart your web server.

I 100% sure I'm using php 7.3.27  in both cli and web server and I have same error

phpinfo inside laravel
![php](https://user-images.githubusercontent.com/7766677/115345975-cd012b80-a1c4-11eb-96c3-278991b7f6b8.jpg)

cli
![phpv](https://user-images.githubusercontent.com/7766677/115346149-0a65b900-a1c5-11eb-8cb9-5b765ae1f258.jpg)

**Comment by ZnarKhalil** [comment]
> Okay, found the issue. The request was a DELETE request and there was a reference to PHP7.2 for DELETE requests in the web.config file. Sorry! Thanks!

this was the issue on windows server 2016

**Comment by Theodory** [comment]
My server using Nginx and `php version 8` but am still getting this error @adirkandel , any idea on nginx?

**Comment by Theodory** [comment]
> just remove the commas before " ) "
> 
> ```
> if ($url) {
>             config()->set(
>                 "database.connections.{$default}.url",
>                 preg_replace('/^(.*)(\/[\w-]*)(\??.*)$/', "$1/{$database}$3", $url)
>             );
>         } else {
>             config()->set(
>                 "database.connections.{$default}.database",
>                 $database
>             );
>         }
> ```

You can't remove that manually since error originate from vendor that's the temporary fix but it's not good practice.

**Comment by Theodory** [comment]
> just remove the commas before " ) "
> 
> ```
> if ($url) {
>             config()->set(
>                 "database.connections.{$default}.url",
>                 preg_replace('/^(.*)(\/[\w-]*)(\??.*)$/', "$1/{$database}$3", $url)
>             );
>         } else {
>             config()->set(
>                 "database.connections.{$default}.database",
>                 $database
>             );
>         }
> ```

You can't remove that manually since error originate from vendor that's the temporary fix but it's not good practice.

**Comment by raychandtw** [comment]
in my case, the nginx conf still using php 7.2 after i upgrade to 7.4. Simply update config and restart nginx.
