### ISSUE TITLE
Illuminate\Validation\Rules\DatabaseRule::$using seems to never be called

### ISSUE THREAD

**Issue by Max13** [laravel/framework#36096]
- Laravel Version: 
- PHP Version: 8.22.0
- Database Driver & Version: Not relevant

### Description:

The documentation for [`exists`](https://laravel.com/docs/8.x/validation#specifying-a-custom-column-name) validation rule using the `Rule::exists()` facade shows an example with a where using a callback, which according to [`Illuminate\Validation\Rules\DatabaseRule:L90`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Rules/DatabaseRule.php#L90) is stored in `DatabaseRule::$using` property.

It doesn't seem the callbacks stored there are ever called.

### Steps To Reproduce:

Try the example `exists` validation, using `Rule::exists()` and a callback in where.

**Comment by taylorotwell** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/463230/106366791-eef4bb80-6303-11eb-86f3-04c578b6e151.png">

My closure was invoked and the condition was added to the query.
