### ISSUE TITLE
Mailable not working with On-Demand Notifications

### ISSUE THREAD

**Issue by gaetan-hexadog** [laravel/framework#36115]
- Laravel Version: 8.24.0
- PHP Version: 7.4.14
- Database Driver & Version: 10.5.8-MariaDB

### Description:
When using a Mailable within `toMail` function of notification, email is not sent when sending an On-Demand notification

### Steps To Reproduce:
1. Create a notification using code in documentation
```php
use App\Mail\InvoicePaid as InvoicePaidMailable;

/**
 * Get the mail representation of the notification.
 *
 * @param  mixed  $notifiable
 * @return Mailable
 */
public function toMail($notifiable)
{
    return (new InvoicePaidMailable($this->invoice))
                ->to($notifiable->email);
}
```

2. Try to send On-Demand notification using code from documentation
```php
Notification::route('mail', 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

Following error is raised:
```php
Undefined property: Illuminate\Notifications\AnonymousNotifiable::$email 
```

Same when changing `$notifiable->email` to `$notifiable->mail`

```php
Undefined property: Illuminate\Notifications\AnonymousNotifiable::$mail 
```

And when removing `->to($notifiable->email)` (because On-Demand notification should handle mail from route property) there is no error but email is not sent.

```php
public function toMail($notifiable)
{
    return (new InvoicePaidMailable($this->invoice));
}
```
Email is not send.

**Comment by mo7zayed** [comment]
@gaetan-hexadog

Did you check the value of `$notifiable` I think it means that it has to be a class using the `Notifiable` trait
check: https://laravel.com/docs/8.x/notifications#specifying-delivery-channels

If you wanna send on demand notification like this: https://laravel.com/docs/8.x/notifications#on-demand-notifications, In case you are using on-demand notification the `$notifiable` variable will be passed as a string in your case.

You will need to check `toMail` function
```php
    public function toMail($notifiable)
    {
        $to = null;

        if (is_object($notifiable)) {
            $to = optional($notifiable)->email; // this is object and it may have email property
        }

        if (is_string($notifiable)) {
            $to = $notifiable; // this is a string
        }

        if (!$to) {
            return (new InvoicePaidMailable($this->invoice))->to($to);
        }

        throw new InvalidEmailException("Some custom message here");
    }
```

**Comment by taylorotwell** [comment]
Yeah, looks like you if you plan to use it on demand you will need to check what type of value $notifiable is.

**Comment by gaetan-hexadog** [comment]
Thanks but what about the use of the `routeNotificationForMail` funtion ? I have to call it manually inside the toMail function when the notifiable is an object ? Shouldn't it be automatic ?

I mean On-Demand notification should use the email address passed via the `route` method. Right ?
So why do I have to check my notifiable object and retreive the mail address manually ?


```php
Notification::route('mail', 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

If I use the non On-Demand notification I understand I have to work with the `notifiable` object and do the checks explained. But shouldn't the recipient address automaticaaly handled by the route method ? It's the way it works with `MailMessage`.

**Comment by driesvints** [comment]
@gaetan-hexadog using your example works for me:

```php
Notification::route('mail', 'taylor@example.com')
            ->notify(new InvoicePaid());
```

**Comment by gaetan-hexadog** [comment]
> @gaetan-hexadog using your example works for me:
> 
> ```php
> Notification::route('mail', 'taylor@example.com')
>             ->notify(new InvoicePaid());
> ```

with InvoicePad `toMail` function returning a Mailable ?Did you use the `->to()` function of the Mailable ? What did you put as parameter for `->to()` emthod of your mailable ? if so why do we have ro use the to method if recipient is set by route ?

**Comment by driesvints** [comment]
> Did you use the ->to() function of the Mailable ?

You can't do that with on demand notifications.

**Comment by gaetan-hexadog** [comment]
> > Did you use the ->to() function of the Mailable ?
> 
> You can't do that with on demand notifications.

I can't do what ? use Mailable object or use the `to` method ? if it's using the `to` function so that's my point, my email is not sent without it even if the récipient email is set by `Notificaytion::route`

**Comment by driesvints** [comment]
Use the `to` method.

**Comment by driesvints** [comment]
@gaetan-hexadog mine is so there's something else that's going wrong for you. Please try a support channel.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by gaetan-hexadog** [comment]
> Use the `to` method.

thanks but you just told wa can't use `to` method with on-demand notification and on the othdr side you tell we have to use it.


the issue still there: Mailable Object is not working with On-Demand notification because recipient set by `route` is not taken into account.

**Comment by driesvints** [comment]
That was as a reply to your question " use Mailable object or use the to method ?". I'm going to leave it at this because I think this is an endless discussion.

**Comment by gaetan-hexadog** [comment]
sorry to ask for details about one line answer of one question on 4 asked.


mMaybe I did not understood the given answers but I don't see in replies an answer which show that Mailable objects are working with On-Demand Notification.

Once again maybe I did not understood provided answers and I need more info to prove that the fact that my mail is not sent when using mailable object (without to function) with on-demand notification (with route function) is not an issue.

**Comment by driesvints** [comment]
@gaetan-hexadog maybe if you can put up a repo which reproduces this problem in the most simplest way I can have another look. Please commit your changes separately from the base skeleton.

**Comment by gaetan-hexadog** [comment]
> @gaetan-hexadog maybe if you can put up a repo which reproduces this problem in the most simplest way I can have another look. Please commit your changes separately from the base skeleton.

Thanks I'll do that.

**Comment by gaetan-hexadog** [comment]
@driesvints my sample code is available here: https://github.com/hexadog/laravel-notification-mailable

You can test it like that:
1. Configure your Mail provider in .env
2. Go to url `http://127.0.0.1:8000/mailable` to test On-Demand notification with Mailable --> This does not sent work (no mail sent)
3. Go to url `http://127.0.0.1:8000/mailmessage`to test On-Demand notification with MailMessage --> This work (mail correctly sent)

**Comment by driesvints** [comment]
Ah I think you mistook me when I said commit separately. Can you please first commit the base Laravel skeleton and then another commit with your custom changes? That allows me to just pull the app in and test things out.

**Comment by gaetan-hexadog** [comment]
My Bad. It's done (2 commits: one with Laravel Skeleton and one with changes for notification tests).

**Comment by driesvints** [comment]
@gaetan-hexadog aaah I now indeed see what you mean.

I took a very very deep dive into all of this and came to the conclusion that this isn't possible at all. When using a `Mailable` instead of `MailMessage` you should always explicitly define the recipients using the `->to` method on the mailable even if you're using on demand notifications. 

I've sent a PR to the docs with an example for your specific use case that also explains the limitations of using Mailables vs MailMessages. I hope that helps: https://github.com/laravel/docs/pull/6816

In any case, the solution to your problem is the following one:

```php

     use App\Mail\InvoicePaid as InvoicePaidMailable;
     use Illuminate\Notifications\AnonymousNotifiable;

     /**
      * Get the mail representation of the notification.
      *
      * @param  mixed  $notifiable
      * @return Mailable
      */
     public function toMail($notifiable)
     {
         $recipient = $notifiable instanceof AnonymousNotifiable
             ? $notifiable->routeNotificationFor('mail')
             : $notifiable->email;

         return (new InvoicePaidMailable($this->invoice))
                     ->to($recipient);
     }
``

**Comment by gaetan-hexadog** [comment]
Thanks a lot @driesvints for your time, the investigation you performed and the given solution (working like a charm).

**Comment by GavG** [comment]
If using the associateive array [email => name] format for on-demand notification mail routes as described here: https://laravel.com/docs/8.x/notifications#on-demand-notifications

e.g.
`
Notification::route('mail', [

    'barrett@example.com' => 'Barrett Blair',

])->notify(new InvoicePaid($invoice));
`
$notifiable->routeNotificationFor('mail') won't return a valid input format for ->to()

So some mapping is needed, similarly as phpspider describes when the routeNotificationFor('mail') contains multiple addresses extra work is needed to make this work.

**Comment by pOmelchenko** [comment]
laravel 11, same problem

```
[2024-10-10 15:10:19] local.ERROR: Email "Barrett Blair" does not comply with addr-spec of RFC 2822. {"exception":"[object] (Symfony\\Component\\Mime\\Exception\\RfcComplianceException(code: 0): Email \"Barrett Blair\" does not comply with addr-spec of RFC 2822. at /var/www/pub/vendor/symfony/mime/Address.php:54)
```
