### ISSUE TITLE
whereKey used 'id' instead of 'key' in select statement 

### ISSUE THREAD

**Issue by rabol** [laravel/framework#36119]
- Laravel Version: 8.25.0
- PHP Version: 7.4.14
- Database Driver & Version: mysqlnd 7.4.13

### Description:
Using the whereKey method on a model uses 'id' instead of 'key' in select

### Steps To Reproduce:
Create a model with 

```
php artisan make:model KeyValue -m
```

modify the migration

```
Schema::create('key_values', function (Blueprint $table) {
            $table->id();
            $table->string('key');
            $table->string('value')->nullable();
            $table->timestamps();
        });
```

Migrate

```
php artisan migrate
```

Try to get a record

```
$record = KeyValue::whereKey('test')->first();
```
will produce this
```
select * from `key_values` where `key_values`.`id` = 'test' limit 1
```

**Comment by driesvints** [comment]
`whereKey` is a dedicated method on the Eloquent builder to select by a primary key.

**Comment by dkulyk** [comment]
`whereKey` is reserved method. You can use `where('key', '=', 'test')` instead.
