### ISSUE TITLE
storeAs result in fopen ErrorException

### ISSUE THREAD

**Issue by TheMutabor** [laravel/framework#36114]
- Laravel Version: 8.16.1
- PHP Version: 7.4.1

### Description:
I have trouble to run storeAs in my productive System. If i runing this code:
```
public function update_avatar(Request $request)
    {
        if ($request->hasFile('avatar')) {
            $request->validate([
                'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            $avatarName = $request->user()->id . '_avatar' . time() . '.' . request()->avatar->getClientOriginalExtension();

            $request->avatar->storeAs('avatars', $avatarName, 'public');

            $request->user()->avatar = $avatarName;
            $request->user()->save();
        }
        return true;
    }
```
I get the error "fopen(): Filename cannot be empty" on FilesystemAdapter.php:271
![2021-02-01 18_14_36-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/69642873/106494011-2ad18180-64ba-11eb-9e3a-afc6300aa2e5.png)

if i dd($request->avatar) i get this output:
```
Illuminate\Http\UploadedFile {#422 ▼
  -test: false
  -originalName: "IMG_0133.JPG"
  -mimeType: "image/jpeg"
  -error: 0
  #hashName: null
  path: "C:\Windows\Temp"
  filename: "php53A6.tmp"
  basename: "php53A6.tmp"
  pathname: "C:\Windows\Temp\php53A6.tmp"
  extension: "tmp"
  realPath: false
  aTime: 2021-02-01 16:59:21
  mTime: 2021-02-01 16:59:21
  cTime: 2021-02-01 16:59:21
  inode: 7881299348284884
  size: 373209
  perms: 0100666
  owner: 0
  group: 0
  type: "file"
  writable: true
  readable: true
  executable: false
  file: true
  dir: false
  link: false
  linkTarget: "C:\Windows\Temp\php53A6.tmp"
}
```
As you see realPath is false and if i dd($file) from the putFileAs function i get also returned false so the putFileAs tryes to call
`$stream = fopen(false, 'r');`
And this can`t work. So i think this is possible a bug. If i run this in dev mode as artisan serve mode it works pretty well but not on my IIS Productive system.

**Comment by driesvints** [comment]
> but not on my IIS Productive system.

This seems to me that it's environment specific and thus not related to Laravel. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
