### ISSUE TITLE
Auth facade return false when change routes

### ISSUE THREAD

**Issue by moku23** [laravel/framework#36121]
- Laravel Version: 8.25
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 8.0.19

### Description:
When I set logged user in one route (Auth::LoginUsingId(1)) and changing route for check if User is logged, it return null.

### Steps To Reproduce:
```
//My Routes (web.php)
    Route::get('/login', [\App\Http\Controllers\UserController::class,'login']);

    Route::get('/test_login', [\App\Http\Controllers\UserController::class, 'getUser']);
```

```
// UserController.php
namespace App\Http\Controllers;

use App\Http\Middleware\Authenticate;
use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Authenticate
{
    //
    protected $user;

    public function login()
    {
        $auth = Auth::loginUsingId(3);
        return var_dump($auth); // <--- here return 3
    }


    public function getUser()
    {
        return response(['user'=>Auth::id()]); // <--- here is null
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by moku23** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

I've already wrote in IRC and StackOverflow, and it seems to be a bug

**Comment by driesvints** [comment]
Can you link to those threads?

**Comment by moku23** [comment]
> Can you link to those threads?

https://stackoverflow.com/questions/66006453/laravel-auth-return-null/

**Comment by driesvints** [comment]
You posted this 2 hours ago. Give it some more time and try other channels like discord and laracasts forums as well.

**Comment by moku23** [comment]
I hope, thanks!
