### ISSUE TITLE
Job not persisting in the mysql database - Intermittent

### ISSUE THREAD

**Issue by Babiute** [laravel/framework#36136]
- Laravel Version: "^8.12",
- "laravel/tinker": "^2.5"
- PHP Version: 7.4.9
- Database Driver & Version: MySql 8

### Description:
I am using the database queue. The problem is that when trying to create a job, on the first attempt it never persists. In the second attempt the job is persisted. I don't change anything. I just try again and the job is persisted.

### Steps To Reproduce:
1) Create any fresh laravel application.
2) Configure your connection to the database.
3) Make sure it is working.
4) Create the proper migration for the jobs.
5) Run the migrations.
6) Create any job, but to be faithful to the problem, it must implement ShouldBeUnique and have a unique key (any key).
7) At the prompt, use `php artisan tinker` and then `\ App \ Jobs \ YourJob :: dispatch ();`

At that point you will see that your job has not been persisted. However, if you run `\ App \ Jobs \ YourJob :: dispatch (); `it again, it will be persisted.

Note 01: 
Sometimes the job just stops being persisted forever. There is no change in the code, it just stops being persisted. However, everything else in the application continues to work, including requests to the database, which excludes the possibility that the database is unavailable.
Note 02: You can simulate it by using some view to call the dispatch event. The behavior will be the same.

Att,
Babiute

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
