### ISSUE TITLE
Laravel 8 components @props directive is not working!

### ISSUE THREAD

**Issue by alirezaashrafi** [laravel/framework#36158]
ErrorException
Undefined variable: label (View: resources/views/components/forms/select.blade.php) 

How can I fix this issue?
I upgraded Laravel 7 to 8
Currently Laravel: v8.26.1

```php
<x-forms.select name="subject" label="Subjects" value="test">
    @foreach($user->subjects as $subject)
        <option value="{{$subject->id}}">{{$subject->name}}</option>
    @endforeach
</x-forms.select>
```

```php
// app/View/Components/Forms/Select.php

<?php

namespace App\View\Components\Forms;

use Illuminate\View\Component;

class Select extends Component
{
  
    public function render()
    {
        return view('components.forms.select');
    }
}
```

```php
// resources/views/components/forms/select.blade.php

@props(['label'])
{{$label}}

<label class="form-label">{{ $attributes->get('label') }}</label>

<select class="form-select" aria-label="Default select" {{$attributes}}>
    {{ $slot }}
</select>

```
![Laravel components @props directive is not working](https://user-images.githubusercontent.com/25801966/107084383-3b605f80-680c-11eb-8947-548d1618d22e.png)

**Comment by taylorotwell** [comment]
`@props` is only for anonymous components that do not have a class. If you are using a class, consult this documentation: https://laravel.com/docs/8.x/blade#passing-data-to-components
