### ISSUE TITLE
Artisan test command ignoring testsuite argument

### ISSUE THREAD

**Issue by JoshPJackson** [laravel/framework#36162]
- Laravel Version: 8.26.1
- PHP Version: 7.4.12
- Database Driver & Version:
N/A

### Description:
I created an artisan command to run the artisan test command with the testsuite option set. This was so I could do a couple of other things before the test suite was run. When I pass in the `--testsuite` argument it is ignored, and all testsuites are run.

Command File: app/Console/Commands/RunFeatureTests.php

```
/**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->call('test', [
            '--testsuite' => 'Feature'
        ]);
    }
```

### Steps To Reproduce:
1. Clone https://github.com/JoshPJackson/laravelexample
2. run `php artisan test:feature` on the command line
3. Notice that all test suites run

**Comment by taylorotwell** [comment]
Ping @nunomaduro

**Comment by crynobone** [comment]
Both `test` and `dusk` command unpack the arguments and options from `argv` instead of Symfony Input. This would allow both commands to forward any PHPUnit configuration without having to register all options on both classes. 

I'm not sure if there an easy fix to this, @nunomaduro may have other input on this. 

However, you could directly extend `TestCommand` (but do aware it is marked as `@internal`).|

```php
<?php

namespace App\Console\Commands;

use NunoMaduro\Collision\Adapters\Laravel\Commands\TestCommand;

class RunFeatureTests extends TestCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:feature
        {--without-tty : Disable output to TTY}
        {--parallel : Indicates if the tests should run in parallel}
        {--recreate-databases : Indicates if the test databases should be re-created}
    ';

    /**
     * Get the array of arguments for running PHPUnit.
     *
     * @param array $options
     *
     * @return array
     */
    protected function phpunitArguments($options)
    {
        return array_merge(parent::phpunitArguments($options), [
            '--testsuite=Feature',
        ]);
    }
}
```

Also you can utilise composer `scripts`:

```json

    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "feature:test": [
            "@php artisan test --testsuite=Feature"
        ]
    },

**Comment by nunomaduro** [comment]
As @crynobone said, this seems a current limitation of the `TestCommand` - but also a limitation of similar commands such as the `DuskCommand`.

You can use the solution proposed by @crynobone as a workaround, but you can also submit a pull request to improve this here: https://github.com/nunomaduro/collision/blob/stable/src/Adapters/Laravel/Commands/TestCommand.php.
