### ISSUE TITLE
Daily logger doesn't clean compressed logs

### ISSUE THREAD

**Issue by halaei** [laravel/framework#36160]
- Laravel Version: 6.20.16
- PHP Version: 7.4.14
- Database Driver & Version: None

### Description:
daily logger has a `days` option. I assume after the given days the log files will be cleared. Although I have set days to 7, I see a lot of old .gz files in logs directory.
I don't find which part of the code is responsible for compressing logs to .gz files.
Reading monolog `RotatingFileHandler` class I think its algorithm to clean old files is incomplete. Only processes that started in days before they try to log can clean log files. But I think that is not how I ended up with lots of .gz files.

Maybe framework should have a log cleaner artisan command and schedule it daily? It is more efficient and simpler than adding code to log rotator, IMO.

### Steps To Reproduce:
- Use daily logger and set days to 1 and log for a few days.
- ls logs directory.
Or you can ls logs directory of your current Laravel projects in production.

### Update:
I thinkg .gz files are generated by logrotate in forge servers. If that is true, my issue has nothing to do with framework. But it may be a forge issue. This is a doc I have found: https://laravel-news.com/httpsserversforhackers-comlogrotate-forge.

[This stackoverflow](https://stackoverflow.com/a/59455671/1561026) was also helpful:
```
postrotate
       find /path/to/log/ -name "*.log.*.gz" -mtime +7 -delete
endscript
```

**Comment by taylorotwell** [comment]
That is logrotate on Forge.
