### ISSUE TITLE
Fill json field using column->key syntax fails when column contains non-object

### ISSUE THREAD

**Issue by mankowitz** [laravel/framework#36167]
- Laravel Version: 7.28.4
- PHP Version: 7.4.14
- Database Driver & Version: Mysql 5.7.26

### Description:
fill of json field results in exception if the json field is not an object

### Steps To Reproduce:
Create a json column in a table. For example, I have a `user_info` column in my `users` table.

If I set the json column to null before I start, it works as expected:
```
>>> User::find(3)->forceFill(['user_info' => null])->save()
=> true
>>> User::find(3)->forceFill(['user_info->name' => 'scott'])->save()
=> true
>>> User::find(3)->user_info
=> "{"name": "scott"}"
```

However, if I set the column to another valid json string which doesn't parse as an object, it throws an exception
```
>>> User::find(3)->forceFill(['user_info' => '"json string which is not an object"'])->save()
=> true
>>> User::find(3)->forceFill(['user_info->name' => 'scott'])->save()
<warning>PHP Warning:  Illegal string offset 'name' in /var/www/html/station/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 567</warning>
=> true
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by mankowitz** [comment]
Sure. I upgraded to 

Laravel Version 8.27.0
PHP Version: 7.4.15
Database Driver & Version: Mysql 8.0.21

Same problem.

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
