### ISSUE TITLE
$_ENV variables missing when running tests in parallel

### ISSUE THREAD

**Issue by BoyeMagnus** [laravel/framework#36164]
- Laravel Version: 8.26.1
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8.x

### Description:
When running tests in parallel $_ENV variables are not set. It should include the environment variables set in phpunit.xml / .env.testing.
When running tests, not in parallel the $_ENV variables are correctly set.

### Steps To Reproduce:
1. Setup .env.testing / phpunit.xml with some environment variables.
2. Add `dd(var_dump($_ENV));` in a test
3. Run `php artisan test`. This outputs:
```
array(32) {
  ["SHELL_VERBOSITY"]=>
  int(0)
  ["APP_NAME"]=>
  string(22) "xxxx"
  ["APP_KEY"]=>
  ....
}
```
4. Run `php artisan test --parallel`. This outputs:
```
array(0) {
}
```

**Comment by taylorotwell** [comment]
Ping @nunomaduro

**Comment by nunomaduro** [comment]
This seem to be an issue with the dependency "Paratest" and the way it handles processes. You can use `getenv()` or `$_SERVER` to access those variables.

**Comment by bbprojectnet** [comment]
Hi,

I have similar issue. I'm using https://github.com/jakzal/phpunit-globals to change ENV variables per test. When test are run in sequence everything works as expected, in parallel, changed ENV seems no effect.
