### ISSUE TITLE
validator date 24:00:00

### ISSUE THREAD

**Issue by puzzle9** [laravel/framework#36178]
- Laravel Version: v8.21.0
- PHP Version: 7.4.12
- Database Driver & Version:  10.5.6-MariaDB

### Steps To Reproduce:

```php
        $validator = Validator::make([
            'time' => '2021-02-08 24:00:00',
            'time' => '2021-02-08 24:01:01',
            'time' => '2021-02-08 24:59:59',
        ], [
            'time' => 'required|date',
        ]);

        // false
        dd($validator->fails());
```

`$validator->fails()` is `false`

but `SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value`

So is this the standard time

Or how should I judge

**Comment by driesvints** [comment]
24:00:00 doesn't exists.

**Comment by puzzle9** [comment]
> 24:00:00 doesn't exists.

but `$validator->fails()` is `false`

no error

**Comment by driesvints** [comment]
That's because `2021-02-08 24:00:00` is accepted by `strtotime` which is used under the hood. See the docs here: https://laravel.com/docs/8.x/validation#rule-date

What you're looking for is `date_format`:

```php
$validator = Validator::make([
    'time' => '2021-02-08 24:00:00',
    'time' => '2021-02-08 24:01:01',
    'time' => '2021-02-08 24:59:59',
], [
    'time' => 'required|date_format:Y-m-d H:i:s',
]);
```

**Comment by puzzle9** [comment]
<https://www.php.net/manual/en/class.datetime.php>

`is error no format Y-m-d H:i:s`
```php
        $validator = Validator::make([
            'time' => '2021-02-08 24:00:00',
            'time' => '2021-02-08 24:01:01',
            'time' => '2021-02-08 24:59:59',
        ], [
            'time' => 'required|date_format:Y-m-d H:i:s',
        ]);
```

`is ok`
```php
        $validator = Validator::make([
            'time' => '2021-02-08T18:30:24+0800',
        ], [
            'time' => 'required|date_format:Y-m-d\TH:i:sO',
        ]);
```
