### ISSUE TITLE
Str::class_basename does not exist

### ISSUE THREAD

**Issue by LKnulp** [laravel/framework#36174]
- Laravel Version: 8.12
- PHP Version: 7.4.14
- Database Driver & Version:

### Description:
The helper ```Str::class_basename``` seems to be removed (I didn't found it in the ```Illuminate\Support\Str```) although it's still listed in the documentation for version 8.x.
The problem is that the basic PHP function ```basename``` does not support "\\" which is necessary when processing namespaces.

### Steps To Reproduce:
Call ```Str::class_basename('Foo\Bar\Baz');``` as described in the documentation.

**Comment by pascalbaljet** [comment]
The method is included in the `helpers.php` file (it's not a PSR-4 namespaced class file):
https://github.com/laravel/framework/blob/v8.26.1/src/Illuminate/Support/helpers.php#L69
