### ISSUE TITLE
Notification with ShouldBroadcastNow not fired immediately

### ISSUE THREAD

**Issue by andrewlim7** [laravel/framework#36183]
- Laravel Version: 6.20.16
- PHP Version: 7.3.12
- Database Driver & Version:

### Description:
I have a real-time notification class which is using the default notification class and implements ```ShouldBroadcastNow```. I am using ```QUEUE_CONNECTION=database``` because I need to put all the emails into a queue. However, when I am trying to send a basic notification to a user, the broadcast notification will put into a queue instead of fire immediately. I have tried to ```php artisan config:clear``` and ```php artisan optimize:clear```, it is not working too.

### Steps To Reproduce:
1. Create a notification by using ```php artisan make:notification RealTimeTesting``` and ```php artisan queue:table``` to store the event / mail into database.
2. Add some code inside RealTimeTesting.php as shown below 
```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Broadcasting\ShouldBroadcastNow;
use Illuminate\Notifications\Messages\BroadcastMessage;
use Illuminate\Notifications\Notification;

class RealTimeTesting extends Notification implements ShouldBroadcastNow
{
    use Queueable;

    public function __construct()
    {

    }

    public function via($notifiable)
    {
        return ['database','broadcast'];
    }

    public function toArray($notifiable)
    {
        return [
            "user" => "user_name"
        ];
    }

    public function toBroadcast($notifiable)
    {
        $data = [];
        $data['content'] = "testing";
        $broadcast = new BroadcastMessage($data);

        return $broadcast;
    }
}
```
3. Assume you have a user model and trigger this notification by using ```php artisan tinker``` as shown below
```
$user = User::where('login_id',1)->first();
$user->notify(new App\Notifications\RealTimeTesting());
```

**Comment by BrandonSurowiec** [comment]
If you're using artisan tinker, I believe it makes a `PendingDispatch` class which is not handled until it is destroyed, via the `__destruct` method. Meaning you would need to `exit` right after you call the above code for it to be handled. You may want to stick this code in a web route and refresh your browser every time you want to send a test message.

**Comment by driesvints** [comment]
See the answer above. Thanks @BrandonSurowiec

**Comment by andrewlim7** [comment]
@BrandonSurowiec I have inserted the code in one of my controllers and it is still not working. I have tried to ```php artisan optimize:clear```. 

myController.php
```
public function testNotifications()
    {
        $user = User::where('login_id',1)->first(); 
        $user->notify(new App\Notifications\RealTimeTesting());

        return "Done";
    }
``` 

web.php
```
Route::get('test-notifications', 'myController@testNotifications');
```

**Comment by andrewlim7** [comment]
Sorry for interrupt, after 2 days of attempts, still not working as expected. Do you all have any idea to solve it? @driesvints

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
