### ISSUE TITLE
Parallel testing not working when database connection set by DATABASE_URL

### ISSUE THREAD

**Issue by ekateiva** [laravel/framework#36189]
- Laravel Version: 8.26.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 5.7.26

### Description:

If [database is configured using URLs](https://laravel.com/docs/8.x/database#configuration-using-urls) (by using `DATABASE_URL`), [parallel testing](https://laravel.com/docs/8.x/testing#running-tests-in-parallel) is not working. 

The reason is that when switching the database in parallel testing, only the _database_ property is changed for default database connection ([a reference to the code](https://github.com/ekateiva/framework/blob/1884c4df4cc0d15b0721897153854c55c5e8ccbf/src/Illuminate/Testing/Concerns/TestDatabases.php#L145-L147)). The suggestion would be to take care of cases, when `database.url` is used as well.

### Steps To Reproduce:

- In `config/database.php` configure your MySQL connection using URLs (https://laravel.com/docs/8.x/database#configuration-using-urls)
- Have a few tests that use traits like `DatabaseTransactions` or `DatabaseMigrations`
- Run `php artisan test --parallel --processes=4`
- You can expect to see some `Illuminate\Database\QueryException` with error message like "Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_test.users' doesn't exist (SQL: alter table `users` add unique `users_email_unique`(`email`))"

**Comment by ekateiva** [comment]
@nunomaduro, I've also tested this on your repo https://github.com/nunomaduro/demo-p and you can replicate it there as well by setting `DATABASE_URL` instead of regular DB credentials (username, password, database, etc).

**Comment by driesvints** [comment]
Nuno's PR was merged. Thanks for the issue.

**Comment by nunomaduro** [comment]
@ekateiva Thank you for your help on the pull request. The regular expression was really helpful!
