### ISSUE TITLE
flock() expects parameter 1 to be resource, bool given in Laravel - 8

### ISSUE THREAD

**Issue by Nilanth** [laravel/framework#36205]
- Laravel Version: 8.5.9
- PHP Version: 7.3
- Database Driver & Version:

### Description:
While accessing route this error is raised

`flock() expects parameter 1 to be resource, bool given
`
### Steps To Reproduce:

1. fresh Install Laravel 8 
2. Add laravel/ui package
3. Generate basic scaffolding... 
`php artisan ui react`
4. Generate login / registration scaffolding...
`php artisan ui bootstrap --auth`
5. Register a user or try to log in

**Comment by driesvints** [comment]
If you want to fix anything for the UI package feel free to send in a PR.
