### ISSUE TITLE
Cannot catch QueryException for Jobs

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#36215]
- Laravel Version: 8.5
- PHP Version: 8
- Database Driver & Version: Mysql

### Description:
Cannot catch QueryException when the job failed to push payloads to the database

### Steps To Reproduce:
```
laravel new catchFailed
QUEUE_CONNECTION=database
php artisan queue:table
php artisan migrate
php artisan make:job MyJob

```
Temporary revoke all privileges for the user to get QueryException

```
REVOKE ALL PRIVILEGES ON *.* FROM '<user_name>'@'localhost';
REVOKE ALL PRIVILEGES ON *.* FROM '<user_name>'@'%';
```

```php
MyJob::disptach();
```

The `fail()` and `Queue::failing()` methods does not work with this exception.

**Comment by taylorotwell** [comment]
This is the behavior I would expect. The job is never pushed. The try / catch would probably need to wrapped around your `MyJob::dispatch`.
