### ISSUE TITLE
Method whenLoaded() return an empty array

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [laravel/framework#36214]
Laravel 8.12,
PHP 8.0.0,
MySQL 5.7

### Description:
{
"id": 1,
"title": "Web Dev",
"level": "senior",
"category": {
"id": 1,
"name": "IT"
},
"locations": []
},

### Steps To Reproduce:
```
//Job Model:
public function locations()
    {
        return $this->belongsToMany(Location::class);
    }
 //Job Resource
 public function toArray($request)
    {
        return [
            'id' => $this->id,
            'title' => $this->title,  
            'level' => $this->level,  
            'category' => new CategoryResource($this->category), 
            'locations' => LocationResource::collection($this->whenLoaded('locations')), 
          ];
    }
    
    //Response
    $jobs = Job::with('locations')->get();
    return JobResource::collection($jobs);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ivanradojevic-web-dev** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

It's all nice, but no one has an answer why the method doesn't work :)
