### ISSUE TITLE
asset() helper doesn't return the right url in a job when url have port number

### ISSUE THREAD

**Issue by elbaylot** [laravel/framework#36226]
- Laravel Version: 8.23.1
- PHP Version: 7.4.10
- Database Driver & Version: 10.4.14-MariaDB

### Description:
Generating a path to an image or file locally does not work when the url has a port number and the helper `asset()` is used in a job (database connection for queue).

### Steps To Reproduce:
**For example** : 

My URL in `.env` :
`APP_URL=http://127.0.0.1:8000`

Imagine a logo path in `public/img/logo.png`

In a controller,  `asset('img/logo.png')` will return `http://127.0.0.1:8000/img/logo.png`.
In my delayed job, `asset('img/logo.png')` call in a view will return `http://127.0.0.1/img/logo.png` without the port number.

It's not very annoying but it's complicated to properly debug emails locally. An email debugger like Helo can't access the images.

**Comment by driesvints** [comment]
I can't reproduce this. Works fine for me in queued jobs:

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ImageJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        logger(asset('logo.jpg'));
    }
}
```

```php
dispatch(new \App\Jobs\ImageJob());
```

![Screenshot 2021-02-11 at 14 49 23](https://user-images.githubusercontent.com/594614/107644987-70d7d380-6c78-11eb-80a0-1010bd8a105d.jpg)

**Comment by ExamediaSoftware** [comment]
Got this same issue today
