### ISSUE TITLE
[8.x] Syntax Error Factory file

### ISSUE THREAD

**Issue by sherazahmad1989** [laravel/framework#36224]
During creating test cases i find out a syntax error in factory file 

file location : vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php

      /**
      * Get a new factory instance for the given model name.
      *
      * @param  string  $modelName
      * @return static
      */
     public static function factoryForModel(string $modelName)
     {
        $factory = static::resolveFactoryName($modelName);

         return $factory::new(); here is error
     }

- Laravel Version: 8.7.1

- PHP Version: 7.4.14
- Database Driver & Version: MySql

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
