### ISSUE TITLE
Laravel 8 pass attributes down to nested components

### ISSUE THREAD

**Issue by Swanty** [laravel/framework#36225]
- Laravel Version: 8.20.1
- PHP Version: 8.0.1
- Database Driver & Version: N/A

### Description:
I have 2 components and I am trying to pass down attributes from one component to the other.

### Steps To Reproduce:

File: `resources/views/home.blade.php`  
```
<x-form-input name="username" />
```

File: `resources/views/components/form-input.blade.php`  
```
<x-input type="text" {{ $attributes }} />
```

File: `resources/views/components/input.blade.php`
```
@php
dd($attributes);
@endphp

<input {{ $attributes }} />
```

Output:
```
Illuminate\View\ComponentAttributeBag {#1451 ▼
  #attributes: array:1 [▼
    "name" => "username"
  ]
}
```

As you can see only 1 attribute is outputted even though `form-input` component added extra atribute `type="text"`  
Expected result should of been 2 attributes `type` and `name`  

I also tried putting `:attributes="$attributes"` instead of `{{ $attributes }}`, but same problem occurs.  

Am I doing something wrong or not understanding how the attributes work?

**Comment by driesvints** [comment]
This isn't supported atm but will be supported in Laravel 9.

**Comment by rodrigopedra** [comment]
@Swanty as a workaround until Laravel 9 is released try this:

~~~blade
<x-input {{ $attributes->merge(['type' => 'text']) }} />
~~~

https://laravel.com/docs/8.x/blade#non-class-attribute-merging
