### ISSUE TITLE
Markdown formatting is behaving strangely in blades used to send emails

### ISSUE THREAD

**Issue by LucileDT** [laravel/framework#36229]
- Laravel Version: 7.13.0
- PHP Version: 7.4.12
- Database Driver & Version: ? (I did not setup my environment and I don't know how to get this information)

### Description:

The Mardown is not always formatted as HTML when using it in a blade rendered through `->markdown()`. Sometimes, it is (expected behavior), while other times it is interpreted as full text. It may depend on its position in HTML tags.

### Steps To Reproduce:
- create a new Notification `MyNotification`
- create a new blade `my-notification.blade.php`
- in `MyNotification->toMail()`, set up the blade render in `->markdown()`
- in `my-notification.blade.php`, add this code:

```html
@php
$stringWithMarkdown = '**This text is bold**';
$stringWithLink = 'This should be a [link](https//randomwebsite.com)';
@endphp

# First table:

{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" style="font-style:italic;">
{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
</td>
</tr>
</table>

# Second table:

{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" style="font-style:italic;">
{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
</td>
</tr>
</table>

# Third table:

{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" style="font-style:italic;">
{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
</td>
</tr>
</table>

# Fourth table:

{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td align="center" style="font-style:italic;">
{{ Illuminate\Mail\Markdown::parse($stringWithMarkdown) }}
{{ Illuminate\Mail\Markdown::parse($stringWithLink) }}
{!! $stringWithMarkdown !!}
{!! $stringWithLink !!}
</td>
</tr>
</table>
```

- send the email

#### Expected behavior:
- all markdown in interpreted and rendered as HTML

#### Current behavior:
- depending on the method to render the strings (`{!! !!}` tag vs `Illuminate\Mail\Markdown::parse()`) and on the tag position, the markdown is interpreted as full string (see attached picture)

![image](https://user-images.githubusercontent.com/23707217/107665033-552af800-6c8d-11eb-8d04-b4224d37f6cf.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
