### ISSUE TITLE
Laravel 8 component @props not setting prop value

### ISSUE THREAD

**Issue by Swanty** [laravel/framework#36236]
- Laravel Version: 8.20.1
- PHP Version: 8.0.1
- Database Driver & Version: N/A

### Description:
`@props` removes `disabled` from `$attributes`, but does not set `$disabled` value to true.

### Steps To Reproduce:

File: `resources/views/home.blade.php`  
```
<x-form-input type="text" :disabled="true" />
```

File: `resources/views/components/form-input.blade.php`  
```
<x-input :attributes="$attributes" />
```

File: `resources/views/components/input.blade.php`
```
@props(['disabled' => false])

@php
dd([
    'disabled' => $disabled,
    'attributes' => $attributes,
]);

$class = 'border-gray-300';
$classDisabled = 'border-gray-300 bg-gray-50 text-gray-500';

if ($disabled) {
    $class = $classDisabled;
}
@endphp

<input {{ $attributes->merge(['class' => $class]) }} {{ $disabled ? 'disabled' : '' }}/>
```

Output:
```
array:2 [▼
  "disabled" => false
  "attributes" => Illuminate\View\ComponentAttributeBag {#1501 ▼
    #attributes: array:1 [▼
      "type" => "text"
    ]
  }
]
```

**Comment by driesvints** [comment]
I've been breaking my head over this one for a few but cannot figure it out. Gonna see if @taylorotwell knows what's going on here.

**Comment by taylorotwell** [comment]
Fix here: https://github.com/laravel/framework/issues/36236
