### ISSUE TITLE
Error Unknown named parameter $token

### ISSUE THREAD

**Issue by tguimmaraess** [laravel/framework#36238]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

I'm using the API route and a middleware to check the token.

I usually pass two parameters to the api routes:

`Route::get('/show-profile/{token}/{userId}/', 'Api\User\UserCtrl@showUser')->middleware('checkToken');`

it works, but now, I also need to pass a third parameter to get the user post, which is postId:

`Route::get('/profile/{token}/{userId}/{postId}', 'Api\User\PostCtrl@getPost')->middleware('checkToken');
`
And it gives me an error: 

> Error Unknown named parameter $token

### Steps To Reproduce:

I just added three parameters in the API route, located in the folder `routes`

It works with 2 parameters but it doesn't seem to work with 3. 

 It's not the method as it has only` $request `as parameter.

I tried: 

1. removing the middleware
2. Removing everything inside the function `getPosts`
3. Clearing the cache

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tguimmaraess** [comment]
Thank you for your reply. 

I'm sorry if I'm wrong but it seems like an issue to me, as I don't see any reason for Laravel to not find the `$token` parameter.

**Comment by tguimmaraess** [comment]
Thank you. After trying a lot, I found out that it wasn't letting me add more parameters to the route because my Controller was extending the default Controller. Now everything works fine.
