### ISSUE TITLE
Job::withChain & Mailables

### ISSUE THREAD

**Issue by pecuchet** [laravel/framework#36252]
- Laravel Version: 7.30.4
- PHP Version: 7.4.14
- Database Driver & Version: MySQL 8.0.23

### Description:

Because mails can be queued (and the doc speaks of a "[unified queue API](https://laravel.com/docs/8.x/mail#queueing-a-mail-message)"), I was expecting to be able to chain a `Mailable` instance with the `withChain` method. But that seems to throw an error:
```
Argument 1 passed to Illuminate\Mail\Mailable::queue() must implement interface Illuminate\Contracts\Queue\Factory, instance of Illuminate\Queue\RedisQueue given, 
called in /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php on line 155
```
The above is with a default Redis connection. I do not expect it to be different with other connections, since looking a the source code `Mailable::queue()` seems to expects an instance of `Illuminate\Queue\QueueManager` (which implements `Illuminate\Contracts\Queue\Factory`).

Am I missing something or is this by design? Or should we not allow this usage? 

### Steps To Reproduce:

```
MyJob::withChain([
   new MyMailable($model),
])->dispatch($model)->allOnQueue('my-queue');
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
