### ISSUE TITLE
Artisan route:list command output (middleware column) changed when using Router::pushMiddlewareToGroup method.

### ISSUE THREAD

**Issue by reppair** [laravel/framework#36258]
- Laravel Version: `8.25.0`
- PHP Version: `7.4.15`
- Database Driver & Version: MYSQL | `5..7.30` - not relevant but.. 

### Description:
Middleware column of the `php artisan route:list` output contains middleware class names instead of a group name after pushing a new middleware to a group via `Illuminate\Routing\Router::pushMiddlewareToGroup` public method.

### Steps To Reproduce:
- Register a test route
  

```php
Route::get('test', 'App\Http\Controllers\Controller@test')->middleware('web');

// and a function in Controller.php
public function test()
{
    return 'test';
}
```

- List the routes with `php artisan route:list` and check the output
  
```bash
+--------+----------+----------+------+--------------------------------------+------------+
| Domain | Method   | URI      | Name | Action                               | Middleware |
|        | GET|HEAD | test     |      | App\Http\Controllers\Controller@test | web        |
+--------+----------+----------+------+--------------------------------------+------------+
```
So far, so good..

- Create a new test middleware `php artisan make:middleware Test`
  
- Push the new middleware to the `web` group via `pushMiddlewareToGroup` method of the `Illuminate\Routing\Router` class from within `AppServiceProvider`.

```php
namespace App\Providers;

use App\Http\Middleware\Test;
use Illuminate\Routing\Router;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot(Router $router)
    {
        $router->pushMiddlewareToGroup('web', Test::class);
    }
}
```

- List the routes with `php artisan route:list` and check the output

```bash
+--------+----------+----------+------+--------------------------------------+--------------------------+
| Domain | Method   | URI      | Name | Action                               | Middleware               |
|        | GET|HEAD | test     |      | App\Http\Controllers\Controller@test | App\Http\Middleware\Test |
+--------+----------+----------+------+--------------------------------------+--------------------------+
```

### Expected behavior
See regular output under Middleware column - `web`.

Last time I used it it worked as expected (quite some time ago) maybe something changed and I missed it?

**Comment by reppair** [comment]
Also I tried it in `App\Providers\RouteServiceProvider` with `app('router')->pushMiddlewareToGroup('web', Test::class);` - same output.

Maybe I'm doing it wrong but I use this function in some package service providers and that breaks the route listing of the apps where I require these packages.

**Comment by driesvints** [comment]
This is the correct new behavior.

**Comment by reppair** [comment]
Any way to list the groups after pushing a middleware to one of them?

**Comment by taylorotwell** [comment]
@driesvints hmm, I'm confused why this would be desirable behavior? You seem to lose the group in route:list just because you push a new middleware to the group?

**Comment by taylorotwell** [comment]
@reppair fixed on next patch release.
