### ISSUE TITLE
Clone method via macro doesn't work properly

### ISSUE THREAD

**Issue by rela589n** [laravel/framework#36255]
- Laravel Version: 8.22.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.6

### Description:

The root cause of problem lies in `\Illuminate\Database\Eloquent\Builder:1511`:
![image](https://user-images.githubusercontent.com/41589422/107857043-a1646c80-6e34-11eb-886a-2d924fe4d9ca.png)

### Steps To Reproduce:

Probably this reproduce the problem:

```php
$query1= $user->posts()->someScope();
$query2 = $query1->clone(); // returns the same object
$query2->someOtherScope(); // modifies query1, because it is the same object
```

Just another example:

```php
$builder=AnswerOption::find(233)->answers();

$builder->clone(); // is the same object
```

![image](https://user-images.githubusercontent.com/41589422/107857374-bd690d80-6e36-11eb-86d9-ad74431a13d3.png)

Migrations:

```
class CreateAnswerOptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('answer_options', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->string('text', 128);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('answer_options');
    }
}


class CreateAnswersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('answers', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->unsignedBigInteger('answer_option_id');
            $table->foreign('answer_option_id')
                ->references('id')
                ->on('answer_options')
                ->onDelete('cascade')
                ->onUpdate('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('answers');
    }
}
```

Models:

```php
class AnswerOption extends Model
{
    public function answers(): HasMany
    {
        return $this->hasMany(Answer::class);
    }
}

class Answer extends Model
{
    public function answerOption(): BelongsTo
    {
        return $this->belongsTo(AnswerOption::class);
    }
}
```

**Comment by taylorotwell** [comment]
Can you just do $foo = clone $foo;?

**Comment by rela589n** [comment]
For sure can I. But it is completely strange to ignore value returned and silently return `$this`. I think there could be other methods returning something different from `$this`. Thus it's bug spreads over all such methods.

Probably value of `forwardCallTo` should be saved. Therefore return `$this` only if value is empty. But from other hand we don't know whether it will break something (probably yes).

**Comment by taylorotwell** [comment]
We never seem to document the ->clone() method. I suggest just using the PHP built-in `clone` keyword.

**Comment by joke2k** [comment]
Just to integrate, the `clone()` method applied to a BelongsToMany with pivot, removes all pivot fields from select.

use built-in `clone`
