### ISSUE TITLE
component class is not receiving any values

### ISSUE THREAD

**Issue by danielzzz** [laravel/framework#36256]
- Laravel Version: 8.12
- PHP Version: PHP Version 7.2.34-9+ubuntu20.04.1+deb.sury.org+1
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

--

### Description:
it seems like the same bug as this issue: https://github.com/laravel/framework/issues/31919 

no props or variables are passed to the component class.
the attributes appear in the template but not the variables.

I've tried proposed solutions from #31919 but it did not work for me..

### Steps To Reproduce:
my component class
```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Checkboxes extends Component
{
    public $data;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        var_dump('render called');
        var_dump($this); //everything is null here
        return view('components.form.checkboxes');
    }
}

```

registered in AppServiceProvider: 
```
public function boot()
    {
        
        Blade::component('checkboxes', Checkboxes::class);
    }
```

this is the component template:
```
@php
var_dump(@$data);
$data = $data ?? [];
$name = @$attributes['name'] ?? "name";
$id = @$attributes['id'] ?? 'id';
$fieldName = @$attributes['field'];
$inline= @$attributes['inline'] ? 'flex' : '';
@endphp
<ul class="<?= $inline ?>">
    @foreach ($data as $item)
    @php
    $fieldId = $fieldName."_".$item->id; //TODO not working o
    @endphp
    <li>
        <?= Form::checkbox($fieldName.'[]', $item->$id, null, ['id'=>$fieldId]) ?>
        <label for="<?=$fieldId ?>" class="font-bold mr-2"><?=$item->name ?></label>
    <li>
        @endforeach
</ul>
```

and this is how I call it in another template:
```
<x-checkboxes field="roles" name="name" value="id" :data="$roles" inline="true">
                </x-checkboxes>
```

cheers, dan

**Comment by azzumed** [comment]
I'm have a similar one problem, with passing data to component.
The example in doc doesn't works: [link](https://laravel.com/docs/8.x/blade#data-properties-attributes)
First, if i pass the message variable, component didn't see it, and i got `$message` is undefined.
Second the `$type` is always `info`, and didn't changes if i pass it to `<x-alert type="error"` using `@props` directive.

**Comment by danielzzz** [comment]
there was a moment I thought it might be something related to component caching or something, but clearing up everything
did not help either...

```
php artisan clear-compiled
php artisan optimize:clear

php artisan view:clear
php artisan debugbar:clear
php artisan event:clear
php auth:clear-resets

# fix auth links missing
php artisan key:generate

composer dump-autoload

```

**Comment by driesvints** [comment]
@azzumed that example works just fine for me. Have you set the message variable in your view?

```php
<x-alert type="error" message="Hello World" class="mb-4"/>
```

![Screenshot 2021-02-15 at 10 04 20](https://user-images.githubusercontent.com/594614/107925817-3bcbc980-6f75-11eb-8283-473ee47580d1.jpg)

**Comment by driesvints** [comment]
@danielzzz `data` is a reserved keyword, which is why this doesn't works for you. This isn't very obvious however. I'm going to talk it over with the team on how we're going to improve this. Either by documenting it or explicitly throwing a warning if you attempt to use it.

**Comment by driesvints** [comment]
https://github.com/laravel/framework/blob/8.x/src/Illuminate/View/Component.php#L238

**Comment by azzumed** [comment]
> @azzumed, этот пример отлично подходит для меня. Вы установили переменную сообщения в своем представлении?
> 
> ```
> <x-alert type = "error" message = "Hello World"  class = "mb-4" />
> ```
> 
> ![Скриншот 15.02.2021 в 10 04 20](https://user-images.githubusercontent.com/594614/107925817-3bcbc980-6f75-11eb-8283-473ee47580d1.jpg)

do you used the @props directive?

**Comment by driesvints** [comment]
@azzumed I used the exact example from the docs.

**Comment by azzumed** [comment]
> @azzumed Я использовал точный пример из документации.

![image](https://user-images.githubusercontent.com/76779534/107932433-9c1b3500-6f8e-11eb-83db-7fd07bf4b284.png)
same, using the example from docs.

**Comment by driesvints** [comment]
Works for me. Try clearing your views `php artisan view:clear`

**Comment by azzumed** [comment]
> Works for me. Try clearing your views `php artisan view:clear`

I'm created repository with representation of bug, try it.
https://github.com/azzumed/laravel-blade-test-props-directive

**Comment by driesvints** [comment]
@azzumed please re-create that and commit your custom changes separately as I can't possible figure out all of the custom code myself.

**Comment by azzumed** [comment]
> @azzumed please re-create that and commit your custom changes separately as I can't possible figure out all of the custom code myself.

recreated
https://github.com/azzumed/laravel-blade-test-props-directive

**Comment by driesvints** [comment]
@azzumed you've created classes for these components without defining properties and initializing them through the constructor. The example you reference is for anonymous components which don't have classes. That's why it's not working for you.

**Comment by azzumed** [comment]
@driesvints thanks for explanation.

**Comment by danielzzz** [comment]
@driesvints it's not working for me. not sure if I am doing something wrong.

this is my component:
```
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Testa extends Component
{
    public $koko;
    public $zaza;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.testa');
    }
}
```

the view (in components/view)
```
<div>
    test component koko:{{$koko }}, zaza:{{json_encode($zaza)}}
</div>
```

how it's called
```
<x-testa koko="baba" zaza="['a'=>1]" />
```

and what it returns:

```

<div>
    test component koko:, zaza:null
</div>


```

I must be missing something, but I cannot pin down what.

I cleared everything I could:

```
php artisan clear-compiled
php artisan optimize:clear

php artisan view:clear
php artisan debugbar:clear
php artisan event:clear
php auth:clear-resets

# fix auth links missing
php artisan key:generate

# fix cached classes 
composer dump-autoload
```

any ideas? thanks in advance

**Comment by driesvints** [comment]
@danielzzz you're not instantiating the properties. See the example here: https://laravel.com/docs/8.x/blade#passing-data-to-components

```php
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($koko, $zaza)
    {
        $this->koko = $koko;
        $this->zaza = $zaza;
    }
```

**Comment by danielzzz** [comment]
ok, after adding these lines it does work. thanks!

I had seen this:

> All public properties on a component will automatically be made available to the component's view. 

taken from https://laravel.com/docs/8.x/blade#passing-data-to-components

I guess I misunderstood it as "all public properties on a component are automatically hydrated  in the component.

cheers, dan

**Comment by HadiNiazi** [comment]
php artisan clear-compiled
php artisan optimize:clear

Worked for me, Thanks @danielzzz

**Comment by felix-penrose** [comment]
I also spent a while tackling a similar sounding issue. For me I fell into a trap of the lazy developer using PHPStorm to auto add properties, and by default the properties were added as **private** rather than **public** attributes. Once made public, the component variables work fine
