### ISSUE TITLE
Do not increment attempts on RateLimitedWithRedis (not a duplicate of the other issues)

### ISSUE THREAD

**Issue by lucabartoli** [laravel/framework#36250]
Hi all, I'm trying to create a Rate limited job which doesn't increase attempts.
The behaviour should be "Delay the job indefinitely if you don't have slots to process, but fail after N tries (one or more) if it's processed and an exception is thrown".
The reason for that is to deal with external api throttling and long queues, without keeping jobs in the queue if they already failed during real execution.
This used to be problematic, as resetting attempts could have allowed for potentially endless jobs.
This is not true with middlewares, as the tooManyAttempts is stored in a dedicated key, and this particular case can be addressed in the handleJob method of RateLimitedWithRedis.
I came out with a partial solution, which works, but it's not clean at all.

```
<?php
namespace App\Jobs\Middleware;

use Illuminate\Queue\Middleware\RateLimitedWithRedis as Middleware;
use Log;

class RateLimitedWithRedisNoAttempts extends Middleware {
    /**
     * Handle a rate limited job.
     *
     * @param  mixed  $job
     * @param  callable  $next
     * @param  array  $limits
     * @return mixed
     */
    protected function handleJob($job, $next, array $limits)
    {
        foreach ($limits as $limit) {
            if ($this->tooManyAttempts($limit->key, $limit->maxAttempts, $limit->decayMinutes)) {
                if($this->shouldRelease) {
                    //Horrible syntax
                    $c = '\\'.\get_class($job);
                    $job->delete();
                    //It's 3am, this is the best i could possibly write atm
                    $c::dispatch(...array_values((array)$job))
                        ->delay($this->getTimeUntilNextRetry($limit->key));
                }
                return false;
            }
        }

        return $next($job);
    }

}
```

Problems of this approach:

- `$c = '\\'.\get_class($job);` and `$c::dispatch(...array_values((array)$job))` are horrible :)
- The jobs are cloned, so Horizon counts more jobs than processed (as it counts all the job entered, so the original ones plus every re-add to queue)
- Suppose a job is allowed to fail (let's say) 3 times, and it already failed twice. If it hits the limiter in the third run, it is added back to the queue with 0 attempts. This is not a huge deal, as the queue will eventually ends at some time, but it's not perfect.
- Not the proper solution, more an ugly hack

Generally speaking, the proper solution would be to not to increment attempts, but I didn't find a way to do that, as the real issue lays under the hood, in markJobAsReserved, which take care of reserving the job, plus incrementing the attempts.
So, every time the job is accessed and reserved, the counter increments, whatever happens before or later.

If anyone has better ideas or suggestions i'm glad to get some help.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
