### ISSUE TITLE
Queueable is not waiting for all database transactions to complete.

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/framework#36269]
- Laravel Version: 8.21.0
- PHP Version: 8.0.0
- Database Driver & Version: Amazon RDS

### Description:
I have a peculiar issue with nested transactions and transaction aware event dispatching. Let's say I have a function which looks something like this :
```php
function a() {
  return DB::transaction(function() {
    return b();
  });
}

function b() {
  return DB::transaction(function() {
    event(new SomeEvent());
    return true;
  });
}
```
It appears `SomeEvent` will be dispatched after the first transaction is committed as I have my queue config `'after_commit' => true,` Now I'm not really sure as to why this is happening, shouldn't this be firing after the second transaction is committed too? Now I know this is happening because on my vapor ui, it shows me an exception of `ModelNotFoundException` and this only happens some of the time. Now I checked the database and the record is there.

### Steps To Reproduce:
I hope this is pretty self-explanatory on how to reproduce this bug.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by driesvints** [comment]
Btw, in between: this could be a number of reasons ranging from implicit commits: https://github.com/laravel/docs/blob/8.x/database.md#implicit-commits to gotcha's using nested transactions. Please try one of the support channels first and then report back if you can confirm this is a bug.

**Comment by m1stermanager** [comment]
I'm experiencing the same issue and we don't have _anything_ interesting happening around nested transactions etc...

**Comment by m1stermanager** [comment]
Just so I'm up-to-date on the process..... I should be checking the 6 other communication channels first to see if @KieronWiltshire received an answer on one of those so the 7th communication channel can eventually be updated? I'm reporting the same issue but without nested transactions.... 

I'm as far as discord and laracasts. I will work my way through this list. 

our composer.lock file specifies v8.9.0 of laravel/framework, queue.php contains the following:

```
 'connections' => [

        'sync' => [
            'driver' => 'sync',
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            //block 15 seconds between asking redis for more jobs...
            'block_for' => 15,
            //if a database transaction is active, wait until after the commit of all transactions
            //to dispatch a queueable thing (event listener, notification, mailable, etc)
            'after_commit' => true
        ],

    ],
```

the code in question is simply `event(new Registered($user, $request->token, $invitation));` and our listener is setup as `class DispatchProfileUpdate implements ShouldQueue` w/ a function declaration of `public function handle(Registered $event)`

we are using the `Event::cache` as well, which may be part of our issue? 
we also have the following in `EventServiceProvider`:
```
    public function shouldDiscoverEvents()
    {
        return true;
    }
```

I'll leave this here, I hope we can reopen this issue? maybe others who come to github issues for issues will be more likely to see it if they don't have to remove the `open` filter?

**Comment by m1stermanager** [comment]
I also believe the implicit commits would actually make this problem a non-issue and would simple mean a transaction that would have otherwise failed and been rolled back would be committed. this is the opposite problem of the transaction having _not_ committed prior to the job/listener/etc hitting the queue.....

that said, i'm not doing anything that would cause an implicit commit

**Comment by m1stermanager** [comment]
ok, the answer is: https://github.com/laravel/horizon/pull/948/files

We need to bump our horizon install by a minor version.

hopefully this helps someone else as well

**Comment by KieronWiltshire** [comment]
> ok, the answer is: https://github.com/laravel/horizon/pull/948/files
> 
> We need to bump our horizon install by a minor version.
> 
> hopefully this helps someone else as well

Interesting you say this because I’m using Vapor, so I wonder if there’s something that needs fixing there too? @nunomaduro maybe you could explain what’s going on?

**Comment by KieronWiltshire** [comment]
@m1stermanager did you ever figure out what was going wrong? I still have this issue.

**Comment by KieronWiltshire** [comment]
@driesvints I think this needs to be reopened. I have been doing some digging and I believe I have found the cause. The `after_commit` queue config option doesn't propagate to events, it only propagates to listeners, so when models that are serialized within events are then processed by the queue, the event cannot run because it can't find the model instance. This actually prevents broadcasting from working correctly unless explicitly specifying the `afterCommit` object paremeter.

**Comment by themsaid** [comment]
@KieronWiltshire I don't seem to understand your issue. Can you elaborate?

**Comment by KieronWiltshire** [comment]
> @KieronWiltshire I don't seem to understand your issue. Can you elaborate?

Sure, so if you have an event that is dispatched from inside a database transaction, then the dispatcher will dispatch this event despite the after_commit queue config parameter. You have to explicitly set the event to dispatch after the transaction has committed. If you do not explicitly do this then the event is serialized before the database transaction completes and the queue worker will attempt to process the event and call it's listeners, however this falls over if you have `SerializeModels` trait because when the event is to be processed by the queue worker, it will attempt to deserialize the model by retrieving it from the database and fail due to the transaction not being committed at this point in time.

**Comment by themsaid** [comment]
@KieronWiltshire I can't replicate your issue. If `after_commit` is set, all dispatches are delayed unless a listener explicitly has `afterCommit = false`.

Also setting `afterCommit` on an event doesn't affect the listeners at all. Are you talking about broadcasted events or queued listeners?

**Comment by KieronWiltshire** [comment]
> @KieronWiltshire I can't replicate your issue. If `after_commit` is set, all dispatches are delayed unless a listener explicitly has `afterCommit = false`.
> 
> Also setting `afterCommit` on an event doesn't affect the listeners at all. Are you talking about broadcasted events or queued listeners?

Not really talking about listeners here though, just the event itself. I'm using Vapor if that somehow changes things?

**Comment by themsaid** [comment]
In your comment you are talking about listeners, so I'm still not sure what your issue is exactly.

**Comment by KieronWiltshire** [comment]
> In your comment you are talking about listeners, so I'm still not sure what your issue is exactly.

Forgive me if I'm explaining myself poorly. I'll show you the event class that I'm dispatching (it has no listeners associated with it)
```php
<?php

namespace Domain\Deposit\Events;

use App\Transformers\DepositTransformer;
use Domain\Deposit\Deposit;
use Illuminate\Broadcasting\BroadcastEvent;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use Support\Serializers\Fractal\OptionalDataKeySerializer;

class DepositCreatedEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * @var bool
     */
    public $afterCommit = true;

    /**
     * @var Deposit
     */
    private $deposit;

    /**
     * Create a new event instance.
     *
     * @param Deposit $deposit
     */
    public function __construct(Deposit $deposit)
    {
        $this->deposit = $deposit;
    }

    /**
     * Retrieve the created deposit.
     *
     * @return Deposit
     */
    public function deposit()
    {
        return $this->deposit;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return PrivateChannel
     */
    public function broadcastOn()
    {
        return new PrivateChannel('user.'.$this->deposit->user_id);
    }

    /**
     * The event's broadcast name.
     *
     * @return string
     */
    public function broadcastAs()
    {
        return 'deposit.created';
    }
}
```

**Comment by themsaid** [comment]
Ok what's the error you're getting?

**Comment by KieronWiltshire** [comment]
> Ok what's the error you're getting?

It would be the `ModelNotFoundException`.

**Comment by themsaid** [comment]
Remove ` public $afterCommit = true;` completely. Don't set it to `false`. Just remove it and all should work.

**Comment by KieronWiltshire** [comment]
> Remove ` public $afterCommit = true;` completely. Don't set it to `false`. Just remove it and all should work.

It doesnt.

**Comment by themsaid** [comment]
What database connection are you using?

**Comment by themsaid** [comment]
Seems to me you are dispatching on a connection different than the connection that you set `after_commit = true` for.

**Comment by KieronWiltshire** [comment]
> Seems to me you are dispatching on a connection different than the connection that you set `after_commit = true` for.

I'm not, I've checked this, but to confirm I set my queue config as follow:
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Queue Connection Name
    |--------------------------------------------------------------------------
    |
    | Laravel's queue API supports an assortment of back-ends via a single
    | API, giving you convenient access to each back-end using the same
    | syntax for every one. Here you may define a default connection.
    |
    */

    'default' => env('QUEUE_CONNECTION', 'sync'),

    /*
    |--------------------------------------------------------------------------
    | Queue Connections
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Laravel. You are free to add more.
    |
    | Drivers: "sync", "database", "beanstalkd", "sqs", "redis", "null"
    |
    */

    'connections' => [

        'sync' => [
            'driver' => 'sync',
            'after_commit' => true,
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
            'after_commit' => true,
        ],

        'beanstalkd' => [
            'driver' => 'beanstalkd',
            'host' => 'localhost',
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => 0,
            'after_commit' => true,
        ],

        'sqs' => [
            'driver' => 'sqs',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'prefix' => env('SQS_PREFIX', 'https://sqs.us-east-1.amazonaws.com/your-account-id'),
            'queue' => env('SQS_QUEUE', 'your-queue-name'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'after_commit' => true,
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            'block_for' => null,
            'after_commit' => true,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Failed Queue Jobs
    |--------------------------------------------------------------------------
    |
    | These options configure the behavior of failed queue job logging so you
    | can control which database and table are used to store the jobs that
    | have failed. You may change them to any database / table you wish.
    |
    */

    'failed' => [
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
        'driver' => 'database-uuids'
    ],

];

```

**Comment by themsaid** [comment]
Something is wrong with your configurations. I can't replicate your issue. All queued jobs including broadcasted events are delayed if `after_commit` is true on the connection.

**Comment by KieronWiltshire** [comment]
> Something is wrong with your configurations. I can't replicate your issue. All queued jobs including broadcasted events are delayed if `after_commit` is true on the connection.

I'm going to try something and get back to you.

**Comment by KieronWiltshire** [comment]
@themsaid  Oh I'm such a stupid idiot. Sorry for wasting your time, the bug is down to when I added in $afterCommit = true, the configuration was using after_commits with an older version of laravel/framework. Updating the framework and using the configuration above seems to have resolved the issue. My apologies.

**Comment by themsaid** [comment]
@KieronWiltshire no problem. Glad it's solved :)

**Comment by KieronWiltshire** [comment]
> @KieronWiltshire no problem. Glad it's solved :)

I spoke too soon. It still doesn't work.

**Comment by r4y7s** [comment]
@themsaid Is there any reason for the sync driver, to ignore the config?

`        'sync' => [
            'driver' => 'sync',
            'after_commit' => true,
        ],`

**Comment by judgej** [comment]
Just going to add a note for others coming across this issue, since it is not at all obvious where teh problem may lie. The queue drivers are written to support `afterCommit()` and/or `'after_commit'`. Some third party drivers may not support it. Some are not up-to-date with the queue driver API in Laravel 9, with a number of changes. If a third-party queue driver is having the problem of not waiting until after the current database transaction is complete before dispatching, then look specifically at the queue driver package in the first instance.

**Comment by nadirabbas** [comment]
@r4y7s  I need `afterCommit` to work on the `sync` driver since that is what I am using for testing. It seems like the `sync` driver does not care about `afterCommit` and dispatches the job instantly. I found a package that is like `sync` driver but honors `afterCommit`. But this package is not up-to-date for Laravel 9 and fails on queueable event listeners, it works for Jobs tho: https://github.com/jlorente/laravel-transaction-commit-queue
