### ISSUE TITLE
ShouldBeEncrypted and jobs console logging

### ISSUE THREAD

**Issue by grcasanova** [laravel/framework#36267]
### Environment
- Laravel Version:  8.22.1
- PHP Version: 7.4.3
- Database Driver & Version: mysql, 8.0.22

### Description:

in the terminal, jobs implementing the _ShouldBeEncrypted_ contract are never displayed as completed (green), instead they will just appear in yellow (in execution). Removing the contract and executing the job again, a yellow and green log will appear instead.

**Comment by driesvints** [comment]
Please provide exact steps to reproduce.

**Comment by grcasanova** [comment]
Let's say I have a job that pings an URL and then returns. If the URL is not available, an exception is generated.
Now in the console I should see

```
[2021-02-10 10:00:04][56] Processing: App\Listeners\URLPinger (in yellow)
[2021-02-10 10:00:04][56] Processed:  App\Listeners\URLPinger (in green)
```
Instead I see just 
```
[2021-02-10 10:00:04][56] Processing: App\Listeners\URLPinger (in yellow)
```
but the job is actually executed as the URL is correctly pinged.

**Comment by driesvints** [comment]
Please provide the code to reproduce this.

**Comment by grcasanova** [comment]
```
<?php

namespace App\Jobs;

use \Exception;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Http;
use Illuminate\Contracts\Queue\ShouldBeEncrypted;

class URLPinger implements ShouldQueue, ShouldBeEncrypted
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $url;

    public function __construct($url)
    {
        $this->url = $url;
    }

    public function handle()
    {
        $response = Http::timeout(30)->retry(3, 100)->get($this->url);

        if ($response->status() != 200) {
            throw new Exception('IPN failed');
        }
    }
}

```

**Comment by themsaid** [comment]
<img width="487" alt="Screen Shot 2021-02-15 at 6 09 38 PM" src="https://user-images.githubusercontent.com/4332182/107969841-fcbf6780-6fb8-11eb-885d-fc351882731c.png">

Works here. Seems like your job is actually still processing.

**Comment by taylorotwell** [comment]
Hmm, I am also unable to recreate.

**Comment by grcasanova** [comment]
> Works here. Seems like your job is actually still processing.

Ok I'll test if it's a queue driver problem and reopen the issue if the error persists. Thanks
