### ISSUE TITLE
PHPUnit argument passed after artisan test --parallel command do not work

### ISSUE THREAD

**Issue by ProteanCode** [laravel/framework#36265]
- Laravel Version: 8.27.0
- PHP Version: 7.4
- Database Driver & Version: Postgres 13

### Description:

Command `php artisan test --parallel --do-not-cache-result` fails to run with error message

> The "--do-not-cache-result" option does not exist. 

 but according to the docs at https://laravel.com/docs/8.x/testing#running-tests

> "Any arguments that can be passed to the phpunit command may also be passed to the Artisan test command"

 it should work just fine.

The command itself works fine without the `--parallel` parameter, but I want to run it in parallel so...

The --do-not-cache-result command is documented here:
https://phpunit.readthedocs.io/en/9.5/textui.html?highlight=--do-not-cache-result%20#command-line-options

### Steps To Reproduce:

Run `php artisan test --parallel --do-not-cache-result` command

**Comment by nunomaduro** [comment]
That's a current limitation of the underlying dependency [Paratest](https://github.com/paratestphp/paratest). Just added a note on docs about that: https://github.com/laravel/docs/pull/6836.
