### ISSUE TITLE
Sharing session in domain and sub-domain

### ISSUE THREAD

**Issue by maqsudinamdar** [laravel/framework#36279]
- Laravel Version: v8.27
- PHP Version: 8.0.1

## Description :

I've two Laravel application on same server but on different path. And I want to merge both application by sharing session. 

Both of these application has domain and sub-domain combination namely:
- `example.com`
- `tool.example.com`

And I'd like authenticate user in `tool.example.com` from authenticating in `example.com` using following [articles.][1]

>Note: That I'm not passing any username and password while accessing the `/home` route in `tool.example.com`. 

------

## Problem Statement:

However, while accessing the route `/home` in `tool.example.com` giving me **Unauthenticated**.

> **Exception has occurred.** Illuminate\Auth\AuthenticationException: Unauthenticated.

---

## I tried the following:

 1. ***Sharing the cookies, sessions and users between the applications*** 
 2. ***Setting the same `APP_KEY`*** 
 3. ***Setting the same `SESSION_DOMAIN` with prefix `.`***
 
---

`example.com` Laravel application I did the following:

`.env`
```
DB_DATABASE=common_database
SESSION_DRIVER=database
APP_KEY=same_key
SESSION_DOMAIN=".example.com"
```  
- Storing session in database. [link][2]

- In `example.com` we're using `example` **Guards** with `example` **Provider** using `Example` **Model** to authenticate web request.

`config/auth.php`
```
    'guards' => [
        'example' => [
            'driver' => 'session',
            'provider' => 'example',
        ],
    ],

    'providers' => [
        'example' => [
            'driver' => 'eloquent',
            'model' => App\Example::class,
        ],
    ],
```

---

Similarly, `tool.example.com` :

`.env`
```
DB_DATABASE=common_database
SESSION_DRIVER=database
APP_KEY=same_key
SESSION_DOMAIN=".example.com"
```  
- In `tool.example.com` I've assigned the `$table` variable as `example` in `User` **Model** to access `example` table to authenticate the request.

`User.php`
```
class User extends Authenticatable 
{
    protected $table = 'example';
```
`config/auth.php`
```
    'guards' => [
        'example' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
```
>Note: I'm expecting to use `example` table to authenticate request in both application.

---

Any help is greatly appreciated. Thanks! in advance.

  [1]: https://medium.com/@zsolt.gyure96/how-to-share-sessions-between-two-laravel-applications-4b9d061fa599
  [2]: https://laravel.com/docs/8.x/session#database

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
