### ISSUE TITLE
Field 'uuid' doesn't have a default value. `failed_jobs` table

### ISSUE THREAD

**Issue by timurlatypov** [laravel/framework#36273]
- Laravel Version: 8.26.1
- PHP Version: 7.4.11
- Database Driver & Version: MYSQL  Ver 8.0.21-12 for Linux on x86_64 (Percona Server (GPL), Release '12', Revision '7ddfdfe')

### Description:
I have caught this type of error on production for a failed_jobs:
SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value (SQL: insert into `failed_jobs` (`connection`, `queue`, `payload`, `exception`, `failed_at`) values ( etc.

For some time I couldn't find the answer why so I have found this:
That is your default migration schema for `failed_jobs` table
https://github.com/laravel/laravel/blob/8.x/database/migrations/2019_08_19_000000_create_failed_jobs_table.php

And this is your upgrade guide to 8.x from 7.x
https://laravel.com/docs/8.x/upgrade#failed-jobs-table-batch-support

In upgrade guide you suggest to alter `failed_jobs` with column `uuid` with unique and **_nullable_** flags.
The probrem is that your initial migration schema for `failed_jobs` table doesn't support **_nullable_**

**Comment by driesvints** [comment]
You're referencing the migration file of the skeleton which is already set up to use uuid's by default.

**Comment by timurlatypov** [comment]
@driesvints Yes, but please read again my issue and try to catch the idea. Your migration file of the skeleton doesn't make 'uuid' column **nullable**

**Comment by driesvints** [comment]
It doesn't needs to be nullable. It makes use of the `database-uuids` driver by default: https://github.com/laravel/laravel/blob/8.x/config/queue.php#L84

**Comment by timurlatypov** [comment]
It seems I got the reproduction steps. If you create laravel 8 project from scratch with migration file of skeleton, where `uuid` is not nullable and then explicitly change driver back to `database. (ex.  'driver' => env('QUEUE_FAILED_DRIVER', 'database')... Then you'll catch my issue. I had to do this change cause i needed to use **artisan queue:retry {id}**, but instead it worked only like this **artisan queue:retry {uuid}**

**Comment by driesvints** [comment]
Ah I see what you mean. We don't recommend doing that. If you explicitly want to do that you can manually adjust the migration if you need to.

**Comment by timurlatypov** [comment]
Anyway, if it's not an issue, thank you for your clarification!
I'll do it manually with extra migration.

**Comment by adrianblynch** [comment]
I'm on Laravel 10, updated from Laravel 5 so many config hasn't been kept up to date.

I recently started using jobs asynchronously and I encouted the same issue.

I had to add the UUID driver for things to work:
```
'failed' => [
    'driver'   => 'database-uuids', <---< This wasn't present
    'database' => env('DB_CONNECTION', 'mysql'),
    'table'    => 'failed_jobs',
],
```
