### ISSUE TITLE
Redis error

### ISSUE THREAD

**Issue by trollsk1n** [laravel/framework#36272]
- Laravel Version: 8.27.0
- PHP Version: 7.4.3
- Database Driver & Version: Redis6 (phpRedis)

### Description:

When I try to connect to my redis server I get an error: ```RedisException
ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?```

### Steps To Reproduce:

Install php-ext redis.
Set redis config in config/database.php:

```
'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

    ],
```
Set variables in .env:
```
REDIS_HOST=dkwjrweio42384728934.mdb.qqwesad.net
REDIS_PASSWORD=weriuweiofusjdifwer89723894uwer
REDIS_PORT=26379
```
But every time, when i try to create job, i get error.
But if I make a direct connection, then everything goes fine

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
