### ISSUE TITLE
Illuminate\Auth\AuthenticationException : Unauthenticated at web driver

### ISSUE THREAD

**Issue by Medboubazine** [laravel/framework#36283]
- Laravel Version: 8.27.0
- PHP Version: 7.4
- Database Driver & Version: MYSQL 7.4.10

### Description:
1.When user logged in with social account the session  password_hash_web not set or set null
And at middleware class Illuminate\Session\Middleware\AuthenticateSession@handle the condition in line 54 will be "true"
and logout from browser and have a problem when login to account with throwin Illuminate\Auth\AuthenticationException
![scrnli_16_02_2021_14-53-22](https://user-images.githubusercontent.com/39988497/108072154-d2c47e80-7066-11eb-8f48-a638b34a7fbb.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
