### ISSUE TITLE
When use ->sync() with condition wherePivot() deleted or deleting events dont firing

### ISSUE THREAD

**Issue by junnysolano** [laravel/framework#36291]
- Laravel Version: 6.18.10
- PHP Version: 7.3.5
- Database Version:  MySQL 5.7.29

*****Sorry for my terrible english**

**Description:** 
When I use function ->sync() with condition wherePivot() the events of deleted and deleting do not fire, for example: $task->users()->wherePrivot('is_student', true)->sync([1, 2 , 3]);

**Extended example:**

**tasks Table**
```
+----+------------------+
| id |             name |
+----+------------------+
|  1 |             Task1|
|  2 |             Task2|
|  3 |             Task3|
+----+------------------+
```

**users Table**
```
+----+------------------+
| id |             name |
+----+------------------+
|  1 |             Matt |
|  2 |            Bruce |
|  3 |              Jay |
|  4 |             Clay |
+----+------------------+
```

**task_user Table**
```
+----+------------+---------+-----------+
| id |    task_id | user_id | is_student|
+----+------------+---------+-----------+
|  1 |          1 |       1 |         1 |
|  3 |          2 |       3 |         0 |
+----+------------+---------+-----------+
```

**Task Model**
```
class Task extends Model
{
    public function students()
    {
        return $this->belongsToMany(User::class)
            ->wherePivot('is_student', true)
            ->using(TaskUser::class)
            ->withTimestamps();
    }

    public function teachers()
    {
        return $this->belongsToMany(User::class)
            ->using(TaskUser::class)
            ->wherePivot('is_student', false)
            ->withTimestamps();
    }
}
```

**TaskUser Model**
```
class TaskUser extends Pivot
{
    public static function boot()
    {
        parent::boot();

        static::created(function (TaskUser $taskUser){
          var_dump($taskUser); //Work fine
        });

        self::deleted(function (TaskUser $taskUser){
          var_dump($taskUser); // Not working
        });

        self::deleting(function (TaskUser $taskUser){
          var_dump($taskUser); // Not working
        });
    }
}
```

If I use:
```
//Work fine, return user 1
$task->whereId(1)->first()->students; 

//Work fine, return user 3
$task->whereId(2)->first()->teachers; 

//Work fine add relate task 3 with users 2, 4 and the created event is triggered
$task->whereId(3)->first()->students()->attach([2, 4]);
```

But the problem is with the sync method, when i use:
```
//The detach of user 1 work fine, but none of the removal events (deleted, deleting) are triggered
$task->whereId(3)->first()->students()->sync([2, 4]);
```

If I use for example -> where ('is_student', true) instead of -> wherePivot ('is_student', true), the delete events if it works but does not respect the is_student condition and deletes all related records

I hope I have explained myself as well as possible and that they can help me with this case or if there is a solution.

Thanks greetings.

**Comment by taylorotwell** [comment]
This behavior goes back to here: https://github.com/laravel/framework/pull/27997

When any where conditions exist on the pivot it will not use the custom cast to execute the query.

**Comment by taylorotwell** [comment]
This behavior could probably be improved but it would have to work by retrieving all of the matching pivot models and deleting them one by one.

**Comment by junnysolano** [comment]
Thank you very much for your prompt response, I understand what you say.

Based on your comment apply the following:

```
$task->students()->syncWithoutDetaching([2, 4]);
$task
     ->students
     ->whereNotIn('id', [2, 4])
     ->each(function ($user){
           $user->pivot->delete();
     });
```

If you have a better idea, it is welcome.
Tks.
