### ISSUE TITLE
Username parameter not supported for redis connection

### ISSUE THREAD

**Issue by SPie** [laravel/framework#36298]
- Laravel Version: 8.28.1
- PHP Version: 7.4.15
- Database Driver & Version: Redis 6.0.10 using predis

### Description:
I'm using a Redis DB with the ACL feature, added in version 6, but I can't use the auth command with username and password because in `Illuminate\Redis\RedisManager::parseConnectionConfiguration` the username gets removed from the parameters.
```php
return array_filter($parsed, function ($key) {
    return ! in_array($key, ['driver', 'username'], true);
}, ARRAY_FILTER_USE_KEY);
```
The username parameter is supported now by predis.

### Steps To Reproduce:
```php
'client' => env('REDIS_CLIENT', 'predis'),
'session' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'port' => env('REDIS_PORT', '6379'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'database' => env('REDIS_DB', '0'),
 ],
```

Trying to use session handling with Redis throws a `Predis\Connection\ConnectionException`
`AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?`

**Comment by taylorotwell** [comment]
Can you submit a PR that fixes your issue?
