### ISSUE TITLE
syntax error, unexpected ')'

### ISSUE THREAD

**Issue by nugastudio** [laravel/framework#36297]
- Laravel Version: 8.12
- PHP Version: 7.3.+
- Database Driver & Version: Mysql > libmysql - 5.6.43

### Description:

i have install laravel 8.x
webserver nginx 
PHP 7.3.27-4+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 14 2021 14:25:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-4+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
but this error refers to files :
/vendor/laravel/framework/src/Illuminate/Testing/Concerns/TestDatabases.php
![image](https://user-images.githubusercontent.com/78015471/108211233-0b478380-715f-11eb-91e1-8fe715f9317a.png)

![image](https://user-images.githubusercontent.com/78015471/108211546-5feafe80-715f-11eb-8733-e159c07e8f14.png)

anyone have same with this issue ?

**Comment by taylorotwell** [comment]
Your CLI PHP version is not PHP 7.3 or greater.

**Comment by rachediabdenacer** [comment]
i think you are using the version 8.27.0 or higher !
this is the commit who caused this bug : 3d5c09717ea693b8e3475ca8e8e2f966b169ddb8
