### ISSUE TITLE
SetRequestForConsole.php passing null to Request::create()

### ISSUE THREAD

**Issue by Naghal** [laravel/framework#36315]
- Laravel Version: 8.28.1
- PHP Version: 7.4.3

### Description:
When running composer install, the post-autoload-dump script fails with error code 1.
The following error is logged to the console:
```
@php artisan package:discover

In Request.php line 335:
                                                                               
  Argument 1 passed to Symfony\Component\HttpFoundation\Request::create() mus  
  t be of the type string, null given, called in /app/vendor/laravel/framewor  
  k/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32    
                                                                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
The command '/bin/sh -c composer install' returned a non-zero code: 1
```

### Steps To Reproduce:
Open a terminal in projet root and run `composer install`.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
