### ISSUE TITLE
Creating CSV From a database table with 300 Thousands rows and save it in server

### ISSUE THREAD

**Issue by apurbatechnoexponent** [laravel/framework#36314]
Hello,
I am unable to create a csv from a table which has 300 Thousands rows. Using eloquent i have fetch all the table data then loop through all the data and use fputcsv($file, array($row['title'])); to write each row in csv. But i am getting time out issue. Can anyone please help me out.

Thanks in advance.

**Comment by technoexponent02** [comment]
I am also facing the same kind of issue. It is showing time out. Please help.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
