### ISSUE TITLE
when i just use the "illuminate/support" package, it throw a exception that Class 'PhpOption\Option' not found in /illuminate/support/Env.php file

### ISSUE THREAD

**Issue by jason-liang** [laravel/framework#36316]
- Laravel Version: 8.5.10
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
when i just use the "illuminate/support" package, it throw a exception that Class 'PhpOption\Option' not found in /illuminate/support/Env.php file, so I watch the composer.json file and i dont find a reqiure that "phpoption/phpoption" in composer.json of  "illuminate/support"

### Steps To Reproduce:
please write "phpoption/phpoption" package into  composer.json of  "illuminate/support"

**Comment by dinhquochan** [comment]
Just use yourself! Env class require `vlucas/phpdotenv`.

[/src/Illuminate/Support/composer.json:49](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/composer.json#L49)

**Comment by driesvints** [comment]
See the answer above. The package is in the suggest list which are optional dependencies you need to install yourself.
