### ISSUE TITLE
Laravel count is showing all count in case of creating new object

### ISSUE THREAD

**Issue by hafizSiddiq7675** [laravel/framework#36319]
- Laravel Version: 5.8.*
- PHP Version: 7.1
- Database Driver & Version: mysql 5.8

### Description:
I am facing a strange behavior of eloquent ORM, I am creating an empty object of the model so that I can access its properties easily in blade view. these properties will be empty. 

### Steps To Reproduce:
```
$model = new Model;
$count = $model->count();
```
the `$count` is always the total number of records in the DB table, in this case, it should be 0

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by dkulyk** [comment]
`$model->count();` is equivalent of `$model->newQuery()->count();`
Model does not have count() method.

**Comment by hafizSiddiq7675** [comment]
So there is no way to get 0
