### ISSUE TITLE
dont find a reqiure that "phpoption/phpoption" in composer.json of  "illuminate/support"

### ISSUE THREAD

**Issue by jason-liang** [laravel/framework#36311]
- Laravel Version: 8.5.10
- PHP Version: 7.2.0
- Database Driver & Version:

### Description:
dont find a reqiure that "phpoption/phpoption" in composer.json of  "illuminate/support"

### Steps To Reproduce:
please write "phpoption/phpoption" package into  composer.json of  "illuminate/support"

**Comment by driesvints** [comment]
Not sure why you'd expect that to be in there?

**Comment by jason-liang** [comment]
when i just use the support package, it throw a exception that Class 'PhpOption\Option' not found in /illuminate/support/Env.php file

**Comment by jason-liang** [comment]
> Not sure why you'd expect that to be in there?

when i just use the support package, it throw a exception that Class 'PhpOption\Option' not found in /illuminate/support/Env.php file

**Comment by crynobone** [comment]
`Illuminate/Support/Env` needs `vlucas/phpdotenv` which would provide `phpoption/phpoption
