### ISSUE TITLE
Validation rule "integer" behaviour with (bool) true

### ISSUE THREAD

**Issue by danilopolani** [laravel/framework#36321]
Currently the validation rule **[integer](https://laravel.com/docs/8.x/validation#rule-integer)** passes if the given input is `(bool) true` because it relies on `filter_var($value, FILTER_VALIDATE_INT)` which returns `1` for a `true` input due to internal casting.

Should the `integer` behaviour be changed (in 9.x/10.x) to return `false`? An example is better than 1000 words:

```php
filter_var(true, FILTER_VALIDATE_INT); // 1

// Therefore...
$v = Validator::make(
    ['input' => true],
    ['input' => 'required|integer']
);

$v->passes(); // true
$v->validated(); // ['input' => true]
```

Using this data for any DB interaction (or anything) where a `int` is expected would throw an exception because it could return a boolean and not only integers despite its name. For a given input `true` I would expect the validation to fail.

Currently I'm avoiding using the rule in favor of `regex:/^[0-9]+$/` (I'm not dealing with negative numbers), but would nice to hear from you about this before creating a _"real_integer"_ custom rule.

_Originally posted by @danilopolani in https://github.com/laravel/framework/discussions/36218_

**Comment by driesvints** [comment]
Heya. This is the current expected behavior. What you're looking for is the `numeric` rule in combination with the `integer` rule which was specifically designed to use the `FILTER_VALIDATE_INT` behavior:

```php
$v = Validator::make(
    ['input' => true],
    ['input' => 'required|integer|numeric']
);
```

That should give you the result you need. Granted this isn't very clear in the docs for `integer` atm so I'll try to PR a clarification for that.

PS. next time please fill out the issue template.

**Comment by danilopolani** [comment]
Oh, didn't get about the combination of those two rules. Sorry about the template, I imported the issue from a discussion and it does not apply any template :face_with_head_bandage:
