### ISSUE TITLE
Implementing ShouldBeEncrypted on job writing a output in cli Differently

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/framework#36322]
- Laravel Version: 8.27.0
- PHP Version: 7.4.11
- Database Driver & Version:
10.4.14-MariaDB

### Description:

when i implement `ShouldBeEncrypted` interface on my job output of command `artisan queu:work` is only printing `[2021-02-19 10:12:17][12] Processing: App\Jobs\MyJob` its never displaying Job as Processed but the job is actually is processed and there is no issues in that.

But when I remove the `ShouldBeEncrypted` interface from my job its Working fine. I am not sure it is a bug or not.

### Steps To Reproduce:

Step 1: Create a new job with command  `php artisan make:job MyTestJob`
Step 2: Dispatch 5 to 10 Number of Jobs(Without implemting `ShouldBeEncrypted`)
Step 3: Start the queue worker by running `php artisan queu:work --queue default`
Step 4: Now implement the `ShouldBeEncrypted` to job
Step 5: Restart the queue worker
Step 6: Compare the output of Both Jobs

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
