### ISSUE TITLE
Redis & RedisCluster eval with serializer & compression

### ISSUE THREAD

**Issue by TheLevti** [laravel/framework#36337]
- Laravel Version: 8.28.1
- PHP Version: 8.0.2
- Database Driver & Version: phpredis 5.3.3

### Description:

The eval call is missing proper argument serialization and compression if php-redis extension is configured to do so.

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/RedisLock.php#L51

### Steps To Reproduce:

Install igbinary, install phpredis, configure laravel to use redis as cache driver. Use the lock functionality as described here: https://laravel.com/docs/8.x/cache#atomic-locks

In the following section you can see the code example, the console and the redis monitor output.

#### No serializer enabled

![lock_serializer_none_code](https://user-images.githubusercontent.com/7612582/108636991-01888d80-7489-11eb-994d-03127cdb8f42.png)

![lock_serializer_none_output](https://user-images.githubusercontent.com/7612582/108636996-08170500-7489-11eb-80e4-8b69246672d8.png)

![lock_serializer_none_monitor](https://user-images.githubusercontent.com/7612582/108636998-0c432280-7489-11eb-9ba7-03ea65e1c6fe.png)

#### Igbinary serializer enabled

![lock_serializer_igbinary_code](https://user-images.githubusercontent.com/7612582/108637008-16fdb780-7489-11eb-9d56-a01518970450.png)

![lock_serializer_igbinary_output](https://user-images.githubusercontent.com/7612582/108637015-1bc26b80-7489-11eb-8846-3e6c0b362b21.png)

![lock_serializer_igbinary_monitor](https://user-images.githubusercontent.com/7612582/108637031-21b84c80-7489-11eb-8169-9e3520771e14.png)

As you can see in the second example the final lock release is not happening and the lock stays in redis until it times out or if no timeout set, will stay there forever. The reason for this is that the phpredis extension can not know which arguments are keys and which are values that need to be serialized and thus the responsibility to do so is in the hands of the extension user to serialize the values in the same way as the extension is currently configured. I have fixed another lock library already, but unfortunately I am not aware how to contribute in the laravel framework.

The solution would be in https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/RedisLock.php#L51

```php
/**
 * Release the lock.
 *
 * @return bool
 */
public function release()
{
    /* If a serialization mode such as "php" or "igbinary" is enabled, the arguments must be
     * serialized by us, because phpredis does not do this for the eval command.
     *
     * The keys must not be serialized.
     */
    $owner = $this->owner;
    $client = $this->redis->client();
    $clientClass = get_class($client);
    if ($clientClass === 'Redis' || $clientClass === 'RedisCluster') {
        $owner = $client->_serialize($owner);
    }

    return (bool) $this->redis->eval(LuaScripts::releaseLock(), 1, $this->name, $owner);
}
```

I have tested this code and it works.

**IMPORTANT**

A similar change needs to be done for the compression options. There, we have no access to an internal function like with the serializer (`_serialize($x)`), but rather have to check the options that are set (`$redis->getOption(Redis::OPT_COMPRESSION);`).

This fix would be also a pre condition to introduce those phpredis options to the general redis config.

**Comment by driesvints** [comment]
Thanks. I don't have experience with Redis clusters myself but your fix seems straight forward to me. Can you send in a PR for that?

**Comment by TheLevti** [comment]
Sure, will prepare a pull request these days.

**Comment by TheLevti** [comment]
> Thanks. I don't have experience with Redis clusters myself but your fix seems straight forward to me. Can you send in a PR for that?

Pull reques submitted. As a result I also submitted two phpredis issues where one needs investigation/fix (https://github.com/phpredis/phpredis/issues/1939) and one would be a good to have (https://github.com/phpredis/phpredis/issues/1938).

**Comment by TheLevti** [comment]
So basically this is my test using laravel's redis cache locking mechanism:

```php
$client->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_NONE);
$client->setOption(Redis::OPT_COMPRESSION, Redis::COMPRESSION_LZ4);
$client->setOption(Redis::OPT_COMPRESSION_LEVEL, 0);

$lock = $store->lock('foo', 10);
$this->assertTrue($lock->get());
// Do something while holding the lock...
$lock->release();
$this->assertNull($store->lockConnection()->get($store->getPrefix().'foo')); // Make sure that the key is gone after our lock was released.
```

Test result:

![image](https://user-images.githubusercontent.com/7612582/109396366-73515300-7931-11eb-9711-cf5055314c02.png)

Redis monitor result:

```
1614450355.729803 [0 10.150.2.1:58410] "SET" "laravel_database_laravel_cache:foo" "\xef\x10\x00\x00\x00\xf0\x01qN1EMnzkvtPonkJi" "EX" "10" "NX"
1614450355.730312 [0 10.150.2.1:58410] "EVAL" "if redis.call(\"get\",KEYS[1]) == ARGV[1] then\n    return redis.call(\"del\",KEYS[1])\nelse\n    return 0\nend" "1" "laravel_database_laravel_cache:foo" "\x10\x00\x00\x00\xf0\x01qN1EMnzkvtPonkJi"
1614450355.730342 [0 lua] "get" "laravel_database_laravel_cache:foo"
1614450355.730460 [0 10.150.2.1:58410] "GET" "laravel_database_laravel_cache:foo"
```

As you can see there is no lua execution that calls `del` as for example with LZF it looks like this:

```
1614450513.021563 [0 10.150.2.1:58432] "SET" "laravel_database_laravel_cache:foo" "\x0f26jsySpY1HOFwAqe" "EX" "10" "NX"
1614450513.021865 [0 10.150.2.1:58432] "EVAL" "if redis.call(\"get\",KEYS[1]) == ARGV[1] then\n    return redis.call(\"del\",KEYS[1])\nelse\n    return 0\nend" "1" "laravel_database_laravel_cache:foo" "\x0f26jsySpY1HOFwAqe"
1614450513.021885 [0 lua] "get" "laravel_database_laravel_cache:foo"
1614450513.021891 [0 lua] "del" "laravel_database_laravel_cache:foo"
1614450513.021935 [0 10.150.2.1:58432] "GET" "laravel_database_laravel_cache:foo"
```

**Comment by driesvints** [comment]
Thanks @TheLevti!
