### ISSUE TITLE
Scoped implicit route binding not working without custom keys

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#36330]
- Laravel Version: 8.28.1
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Description:

The Laravel documentation says you can add scoped implicit route binding and customize its behavior using the `resolveChildRouteBinding` method.

But the method is only called if the child binding uses a custom key. If you just use the default keys, the ids of each model, the method  `resolveChildRouteBinding` is not called.

### Steps To Reproduce:

1. Add a Post model

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
}
```

2. Add `resolveChildRouteBinding` method to `User` model and add `dd(...)` inside the methode
```php
namespace App\Models;

class User extends Authenticatable
{
    public function resolveChildRouteBinding($childType, $value, $field)
    {
        dd('The `resolveChildRouteBinding` method is called!');
    }
}
```

3. Test the following web routes:
```php
use App\Models\Post;
use App\Models\User;
use Illuminate\Support\Facades\Route;

Route::get('/user/{user:id}/post/{post:id}', function (User $user, Post $post) {
    // ✅ The `resolveChildRouteBinding` is called
});
Route::get('/user/{user}/post/{post:id}', function (User $user, Post $post) {
    // ✅ The `resolveChildRouteBinding` is called
});
Route::get('/user/{user:id}/post/{post}', function (User $user, Post $post) {
    // ❌ The `resolveChildRouteBinding` is NOT called
});
Route::get('/user/{user}/post/{post}', function (User $user, Post $post) {
    // ❌ The `resolveChildRouteBinding` is NOT called
});
```

**Comment by taylorotwell** [comment]
Yeah, I think that is how it was intended to behave by design. It could be tweaked but doing so would maybe be a breaking change.
