### ISSUE TITLE
Triggering an Error inside QueuedClosure fails

### ISSUE THREAD

**Issue by Korko** [laravel/framework#36332]
- Laravel Version: 8.26.1
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
CallQueuedHandler::failed $e can be of type Throwable while CallQueuedClosure::failed $e only accept Exception. Native PHP Errors are not exceptions.

### Steps To Reproduce:
`$dummy = new Dummy();
dispatch(function () use ($dummy ) {
    $dummy ->shouldFail();
});`

`class Dummy
{
    public function shouldFail(int $v) {}
} `

Expected: Should display a Too few arguments to function shouldFail.
Current Behavior: Displays Argument 1 passed to Illuminate\Queue\CallQueuedClosure::failed() must be instance of Exception, instance of ArgumentCountError given

Proposed solution:
Replace "Exception" in CallQueuedClosure with "Throwable"

**Comment by taylorotwell** [comment]
This was recently fixed.
