### ISSUE TITLE
Laravel Reset Password Notification does not get dispatched in test but does send an email

### ISSUE THREAD

**Issue by FrazeColder** [laravel/framework#36333]
- Laravel Version: 8.15.0
- PHP Version: 7.4.11
- Database Driver & Version: MariaDB

### Description:
I am writing tests for my Laravel project. Right now I am testing the authentication code like login, logout, reset password and so on. 

Sadly, my test is failing because there is no notification send. I have mocked the notifications but `assertSendTo` always fails with the reason `The expected [Illuminate\Auth\Notifications\ResetPassword] notification was not sent.`.  Also when trying `assertQueued` I get the error that `Illuminate\Auth\Notifications\ResetPassword]` is not queued. 

However, when actual requesting a reset password email (not in the test, as a normal user on my website) I indeed do get an reset password email. So, it is functional and working but not in my test. How can this be? The `.evn` is also correct, I have set my mail host to `mailtrap.io` and I also receive this email... 

### Steps To Reproduce:
Here is my test:
```
use App\Models\User;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Tests\TestCase;

class AuthTest extends TestCase
{
    /** @test */
    public function a_not_logged_in_user_can_request_a_new_password()
    {
        Notification::fake();

        $email = Str::random() . "@gmail.com";
        $current_password = Str::random(16);
        $current_password_hash = Hash::make($current_password);

        $user = User::factory()->create([
            'email' => $email,
            'password' => $current_password_hash
        ]);

        $response = $this->json('POST', route('password.email'), ['email' => $email]);

        $response->assertStatus(200);
        $response->assertLocation(route('home'));
        
        //$this->expectsNotification($user, ResetPassword::class);
        Notification::assertSentTo($user, ResetPassword::class);
    }
}
```

This is the error I get when executing the test with `assertSentTo`
```
1) Tests\Feature\Auth\LoggedIn\ForgotPassword\AuthTest::a_not_logged_in_user_can_request_a_new_password
The expected [Illuminate\Auth\Notifications\ResetPassword] notification was not sent.
Failed asserting that false is true.

MyWebsiteProject/vendor/laravel/framework/src/Illuminate/Support/Testing/Fakes/NotificationFake.php:68
/MyWebsiteProject/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
MyWebsiteProject/tests/Feature/Auth/LoggedIn/ForgotPassword/AuthTest.php:35
```
And this is the error I get when executing it with `expectsNotification`
```
1) Tests\Feature\Auth\LoggedIn\ForgotPassword\AuthTest::a_logged_in_user_can_request_a_new_password
The following expected notification were not dispatched: [Illuminate\Auth\Notifications\ResetPassword]

MyWebsiteProject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php:281
MyWebsiteProject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:237
MyWebsiteProject/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:153
```

I have already asked this in Laracast (link) and also copied code from google which is testing the forgot password controller... However, also those lines don't work. I am very confused!

**Comment by lk77** [comment]
Hello,

i tried your test by copy pasting it, and it works, there is something wrong with your project i think

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by denniskoster** [comment]
@FrazeColder I have exactly the same issue. I first tried `Mail::fake()` but was then told to use `Notification::fake()`. Unfortunately with the same results. Did you manage to fix this?

- Laravel version: 8.26.1
- PHP version: 7.4.13
- DB: PostgreSQL 13.2

**Comment by denniskoster** [comment]
I have since found that using the user instance to assert the notification works, but the anonymous notifiable does not.

**Works:**
```php
Notification::assertSentTo(
    $user,
    ResetPassword::class
);
```

**Does not work**
```php
Notification::assertSentTo(
    new AnonymousNotifiable(),
    ResetPassword::class,
    function ($notification, $channels, $notifiable) use ($user)  {
        return $notifiable->routes['mail'] === $user->email;
    }
);
```

**Comment by FrazeColder** [comment]
Hi, I have finally found out why my notification is not being send.... It is because I am using a custom notification... Sorry for opening this topic!

**Comment by warrenwalt** [comment]
Hello, Could you kindly elaborate more on what you mean by saying "custom notification"?
I am experiencing similar problem and was following along. Thanks.

**Comment by mihai-craita** [comment]
Hi, in model User.php I was overwriting the function **sendPasswordResetNotification**. This was sending another custom notification found in App\Notifications\ResetPasswordNotification (like @FrazeColder mentioned).
Hope this helps.

**Comment by camiant** [comment]
I've run into the same issue and solved this way ↓↓↓

My app was initially created in L5 when the default `User.php` fully qualified class name was
`App\User.php` but, according to L8 new pattern, I've duplicated it (to avoid refactoring.... my fault) to `App\Models\User.php`.

____________________________________
![image](https://user-images.githubusercontent.com/7567420/149109529-9e2c1c7b-f4dd-452b-809c-2eddf6f04cb0.png)
____________________________________

This partial misalignment, though, left some of my tests behind, expecially the ones involving fake-notifications in which `UserFactory` kept dispatching (via `NotificationFake.php`) to `App\User.php` instead of `App\Models\User.php` and determining the `assertSentTo` to fail.

**_TLDR_**
make sure that `config/auth.php` (param `providers.users.model`)  and `UserFactory.php` rely on the same model.

**Comment by armineslami** [comment]
If inside your `User` model you are overwriting `sendPasswordResetNotification` using your custom notification class, then make sure inside your test file replace 
`Notification::assertSentTo($user, ResetPassword::class);`
with
`Notification::assertSentTo($user, YOUR_CUSTOM_CLASS::class);`
