### ISSUE TITLE
PusherBroadcaster not compatible with pusher-php-server 5.0

### ISSUE THREAD

**Issue by Koozza** [laravel/framework#36339]
- Laravel Version: 8.28.1
- PHP Version: 7.3.26
- Database Driver & Version: MySQL 5.7.32

### Description:

When attempting to broadcast to a pusher channel with the pusher-php-server 5.x package a exception is thrown:
`array_merge(): Expected parameter 2 to be an array, null given`

Last lines of the stacktrace:

```
/vendor/pusher/pusher-php-server/src/Pusher.php:519
/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:114
/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php:65
```

### Steps To Reproduce:

Create a new Event that implements `ShouldBroadcast`. Set ENV `BROADCAST_DRIVER=pusher` and dispatch the created job. Above exception should be thrown.

**Comment by driesvints** [comment]
Hi @Koozza. Laravel atm only supports 4.0. We'd appreciate a PR to make it also compatible with 5.0

https://github.com/laravel/framework/blob/8.x/composer.json#L147

**Comment by xlcrr** [comment]
I created the same issue here

https://github.com/pusher/pusher-http-php/issues/286
