### ISSUE TITLE
Invalid type-hint and return value for __unserialize method

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#36341]
- Laravel Version: 8.28.1
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0.23

### Description:

Hi, all

I'm facing with an error regarding type-hint for `__unserialize` method (https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/SerializesModels.php#L53)
I've override this method with type-hint (like for phpdoc comment in the SerializesModels class):
![Screenshot from 2021-02-22 17-24-39](https://user-images.githubusercontent.com/7753600/108721298-e7a38500-7532-11eb-9ba5-5eee4505bbdb.png)

And after upgrading php to 8 version I'm getting an error: `::__unserialize(): Return type must be void when declared`.
Of course I've removed type-hint for this method and this fixed my problem.

But I've a **main question**: why are using `@return array` annotation in phpdoc and return array from `__unserialize` method in the `SerializesModels` class if in the documentation the return type of this method is `void` [unserialize](https://www.php.net/manual/en/language.oop5.magic.php#object.unserialize) ?

![Screenshot from 2021-02-22 17-33-49](https://user-images.githubusercontent.com/7753600/108722388-284fce00-7534-11eb-929a-0be6b5d179a3.png)

### Steps To Reproduce:
-

**Comment by taylorotwell** [comment]
Feel free to make a PR to correct it since it is just a doc block issue.
