### ISSUE TITLE
withoutMiddleware and Closure middleware

### ISSUE THREAD

**Issue by dugi-x** [laravel/framework#36350]
- Laravel Version: 8.23.1
- PHP Version: 7.3
- Database Driver & Version:

### Description:
When using the feature withoutMiddleware and have anonymos function as Closure middleware inside the __construct of the controller, The following error is returned:
```
class_exists() expects parameter 1 to be string, object given
vendor/laravel/framework/src/Illuminate/Routing/Router.php:728
```
```
728: if (! class_exists($name)) {
729:      return false;
730: }
```
the $name variable is Closure($request, $next)

### Steps To Reproduce:
app/Http/Controllers/AppController.php
```
class AppController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            return $next($request);
        });
    }
}
```
routes/web.php
```
Route::post('/test', [AppController ::class, 'test'])->withoutMiddleware([\App\Http\Middleware\VerifyCsrfToken::class]));
```

**Comment by derekmd** [comment]
https://github.com/laravel/framework/pull/36293 was merged 5 days ago so the fix should be tagged in tomorrow's 8.x release.
