### ISSUE TITLE
Calling relationship with non existing foreign key returns null instead of throwing error

### ISSUE THREAD

**Issue by mesiarm** [laravel/framework#36353]
- Laravel Version: #.#.#
- 8.27.0
- PHP Version: #.#.#
- 7.4.3
- Database Driver & Version:
- Postgres 13

### Description:
Calling relationship with non existing foreign key returns null instead of throwing error.

### Steps To Reproduce:
1. Create relationship in model (for example $user->role)
2. Fill custom non-existing foreign key (for example: (return $this->belongsTo(Role::class, 'x');)
3. Create $user = new User(); object and set role_id property to existing role id.
3. Calling relationship $user->role returns null (looks like role doesnt exist in database) instead of throwing error.

**Comment by taylorotwell** [comment]
Feel free to PR a change in behavior you want to make - sounds like this would be a breaking change though.
