### ISSUE TITLE
Missing validation messages for additional email rules (email:rfc,dns)

### ISSUE THREAD

**Issue by pultho** [laravel/framework#36360]
- Laravel Version: 7.30.4
- PHP Version: 7.4
- Database Driver & Version: MariaDB

### Description:
After asking via Github discussions already I currently can't find any way (or any part in the documentation) for translating the additional email rules like `email:dns` or `email:rfc,dns`

See ticket here: https://github.com/laravel/framework/discussions/36282

Current result of the validator's message bag: (`$validator->getMessageBag()`);
```
result = {Illuminate\Support\MessageBag} [2]
 messages = {array} [1]
  email = {array} [1]
   0 = "my-entererd@email-address.com"
```

### Steps To Reproduce:
- Implement validation rule `email:dns`
- What validation message to add via `lang/en/validation.php`? https://github.com/laravel/laravel/blob/8.x/resources/lang/en/validation.php

Or is this intended?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
