### ISSUE TITLE
Route parameters in view routes

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#36368]
- Laravel Version: 8.27.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8

### Description:
I'm not sure if this is a bug or if the documentation is just confusing...

The [docs for view routes](https://laravel.com/docs/8.x/routing#view-routes) reference being able to use route parameters (_"When using route parameters in view routes..."_). This would be useful in cases where you wanted to pass a URL parameter as part of the view data (either as a plain string or via dependency injection) without the overhead of a controller. 

However, there doesn't seem to be any way to actually use route parameters in a view route. The docs are clear about how you might pass static data to a view, but not how you can reference a route parameter.

### Steps To Reproduce:

Create a view route with a parameter and try to pass that parameter to the view:

```php

Route::view("foo/bar/{baz}", "foo.bar", ["baz", $baz, "{baz}...]???

```

**Comment by rodrigopedra** [comment]
You can use the `request()` helper for that.

~~~php
// ./routes/web.php

Route::view('/test/{name}', 'test');
~~~

The in the view

~~~blade
<h1>{{ request()->route('name') }}</h1>
~~~

**Comment by rodrigopedra** [comment]
Just to add: under the hood `Route::view()` uses `\Illuminate\Routing\ViewController`, and you can see no additional arguments are passed down, besides the ones defined in the route registration:

https://github.com/laravel/framework/blob/b69db31d47342f41878c20cbdce35edc8ea56147/src/Illuminate/Routing/Router.php#L274-L283

https://github.com/laravel/framework/blob/b69db31d47342f41878c20cbdce35edc8ea56147/src/Illuminate/Routing/ViewController.php#L33-L38

**Comment by adamthehutt** [comment]
Thanks @rodrigopedra. That makes sense, although it would be nice if there were a way to use the service container for route-model binding (although I admit at that point you should probably just use a controller).

**Comment by rodrigopedra** [comment]
You're welcome @adamthehutt 

For route model binding to work it needs the type hints to "know" to which class it should try binding.

But I think if you define explicit route binding in your `RouteServiceProvider`,  it might work:

https://laravel.com/docs/8.x/routing#explicit-binding
