### ISSUE TITLE
Squashing migrations does not work for migrations outside database/migrations folder.

### ISSUE THREAD

**Issue by NemanjaMilosevic** [laravel/framework#36370]
Squashing Migrations https://laravel.com/docs/8.x/migrations#squashing-migrations,
is not working for migrations registered outside database/migrations

- Laravel Version: 8.29.0
- PHP Version: 7.4.13
- Database Driver & Version: PostgreSQL 10.12

### Description:
Squashing Migrations https://laravel.com/docs/8.x/migrations#squashing-migrations,
is not working for migrations registered outside database/migrations

### Steps To Reproduce:
1. Create a migration file outside ```database/migrations``` folder
2. Register migration in your service provider using `$this->loadMigrationsFrom(__DIR__ . $pathOutsideDatabaseMigrations);`
3. Run squash migrations command ```php artisan schema:dump```

The expected output is that all loaded migrations are included in schema dump and that its possible to also prune migrations outside ```database/migrations```

**Comment by taylorotwell** [comment]
Yeah - have to use the conventional folder.
