### ISSUE TITLE
Artisan::output() returns empty string 

### ISSUE THREAD

**Issue by yoeriboven** [laravel/framework#36379]
- Laravel Version: 8.29.0
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
I'm trying to write the output of (scheduled) commands to a log file.

I expect `Artisan::output()` to return the output. This only works when the command is called manually. This method returns an empty string when the command was called through the command line or scheduler.

Artisan uses the `lastOutput` property for this. This property is set in [`Artisan::call()`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Application.php#L185).

Running commands in the cli or through the scheduler doesn't call this command. These use the [`run()`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Application.php#L81) command.

### Steps To Reproduce:

1. Add a place to test

```php
use Illuminate\Console\Events\CommandFinished;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Event;

Event::listen(function (CommandFinished $event) {
    dump('Artisan output: '. Artisan::output());

    // Here I could log the output
});
```
2. Run a test from the cli and one from tinker

**Manually**
![Schermafbeelding 2021-02-24 om 18 37 06](https://user-images.githubusercontent.com/4047804/109042144-23278600-76d0-11eb-97f0-a558cf156cf5.png)

**CLI**
![Schermafbeelding 2021-02-24 om 18 35 50](https://user-images.githubusercontent.com/4047804/109042141-21f65900-76d0-11eb-882e-90352cab08a5.png)

### Possible solution:
If possible, set the `lastOutput` property in the `run()` method instead of `call()`.

**Comment by taylorotwell** [comment]
The CommandFinished event seems to already have an `$output` property?

```php
$output = $event->output;
```

**Comment by driesvints** [comment]
Been digging into this one but can't figure out why it's not working on the CLI. It seems the output buffer is cleared somehow before the process has ended.

**Comment by yoeriboven** [comment]
@taylorotwell Before resorting to `Artisan::output()` I tried that. `$event->output` returns an instance of `\Symfony\Component\Console\Output\OutputInterface` and I can't seem to get string values out of that. 

Optimal would be if `$event->output` returned some kind of string or an array of lines. Wouldn't fix this issue though.

**Comment by driesvints** [comment]
@yoeriboven you can try to do the same thing the output method doet and check for a fetch method which you can call:

```
    /**
     * Get the output for the last run command.
     *
     * @return string
     */
    public function output()
    {
        return $this->lastOutput && method_exists($this->lastOutput, 'fetch')
                        ? $this->lastOutput->fetch()
                        : '';
    }
```

**Comment by driesvints** [comment]
Nvm, doesn't seems to be available

**Comment by yoeriboven** [comment]
@driesvints Yeah, tried that already... 😬

**Comment by yoeriboven** [comment]
Probably because:

```php
// Illuminate\Console\Application
$this->lastOutput; // returns \Symfony\Component\Console\Output\BufferedOutput

// Illuminate\Console\Events\CommandFinished
$event->output; // returns \Symfony\Component\Console\Output\OutputInterface
```

**Comment by driesvints** [comment]
Yeah I just figured out that myself. I'm wondering why `run` and `call` have different fallbacks for the output implementation.

**Comment by taylorotwell** [comment]
I'm not sure we have a great solution at the moment. Best advice I can give you right now is instead of scheduling the Artisan command directly schedule a callback which calls Artisan::call:

```php
$schedule->call(function () {
    Artisan::call('inspire');
});
```

**Comment by taylorotwell** [comment]
This should fix the problem: https://github.com/laravel/framework/pull/36404

Will require updating your "artisan" file to use Illuminate\Console\BufferedConsoleOutput instead of just ConsoleOutput.
