### ISSUE TITLE
How to require array in Laravel validation and prevent getting unexpected keys

### ISSUE THREAD

**Issue by mahdyaslami** [laravel/framework#36374]
- Laravel Version: 8.12.0
- PHP Version: 8.02
- Database Driver & Version:

### Description:

I want to set require validation for array of objects in laravel and used following rule:

```php
[
    'translations.*.languageId' => ['required', 'numeric', Rule::in(Language::all()->pluck('id'))],
    'translations.*.data.title' => 'required|string',
]
```

but there is problem when i send request without `translations` key the `validate` function does not throw require error for `translation` key.

so i add `translations` key separately too.

```php
[
    'translations' => ['required', 'array'],
    'translations.*.languageId' => ['required', 'numeric', Rule::in(Language::all()->pluck('id'))],
    'translations.*.data.title' => 'required|string',
]
```

But there is a problem if an extra key is sent that should not be in the `translations` array (like `locale`), it can still be seen in the output of the `validate` function.

how can i prevent this unexpected result?

### Steps To Reproduce:

- Create validation for a key contain array of objects.
- Validate object keys in array.
- The key that is contain the array have to be require.
- Send extra key in objects of array.
- get extra key from `validate` function !!!!!.

**Comment by taylorotwell** [comment]
Filter the array to only have the items you actually want after validation.

**Comment by Robbuss** [comment]
We ran into this issue too. We used this validated function to check if there are other keys in the rules defined:
Custom Validator class which extends Illuminate\Validation\Validator
```
public function validated()
    {
        if ($this->invalid()) {
            throw new ValidationException($this);
        }

        $results = [];

        $missingValue = Str::random(10);

        $rules = array_keys($this->getRules());
        foreach ($rules as $key) {
            foreach ($rules as $key2) {
                if (Str::startsWith($key2, $key . '.'))
                    continue 2;
            }
            $value = data_get($this->getData(), $key, $missingValue);

            if ($value !== $missingValue) {
                Arr::set($results, $key, $value);
            }
        }

        return $this->replacePlaceholders($results);
    }
```

To override validator class: https://stackoverflow.com/questions/66544779/extending-overriding-laravel-validator-class
