### ISSUE TITLE
ArrayObject cast does not serialize empty array to empty object

### ISSUE THREAD

**Issue by danilopolani** [laravel/framework#36376]
- Laravel Version: 8.29.0
- PHP Version: 8.0.2
- Database Driver & Version: N/A

### Description:
Using the `AsArrayObject` cast I expect an empty array to be JSON serialized into an empty object, like the native behaviour, but instead it serialize into an empty array.

For example with a given `Model` with the `AsArrayObject` cast to `field` attribute:

```php
json_encode(['field' => new ArrayObject([])]); // {"field":{}}
(new Model(['field' => []))->toJson(); // {"field":[]}
```

However passing MANUALLY the `ArrayObject` to wrap the field content, it works.

```php
(new Model(['field' => new ArrayObject([])))->toJson(); // {"field":{}}
```

### Steps To Reproduce:

> <small>A demo repository is available here: https://github.com/danilopolani/laravel-arrayobject. Just run it with `sail up` and go to `http://localhost` to see dumps.</small>

1. Create a Model assigning `AsArrayObject` cast to a field:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\AsArrayObject;
use Illuminate\Database\Eloquent\Model as BaseModel;

class Example extends BaseModel
{
    /**
    * The attributes that are mass assignable.
    *
    * @var array
    */
    protected $fillable = [
        'content',
    ];

    /**
    * The attributes that should be cast to native types.
    *
    * @var array
    */
    protected $casts = [
        'content' => AsArrayObject::class,
    ];
}
```

2. Create a Model with some data and JSON-serialize it.

```php
$model = new Model([
    'content' => [],
]);

dd($model->json()); // {"content":[]}
```

**Comment by browner12** [comment]
Is it as simple as adding a `JSON_FORCE_OBJECT` to the `json_encode` call here:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Casts/AsArrayObject.php#L26

**Comment by danilopolani** [comment]
Ok, going in depth on this I may have found the issue: `\Illuminate\Database\Eloquent\Casts\ArrayObject::toArray()`.

It has been added (I guess) to let users do `$model->content->toArray()` as a shortcut to `$model->options->getArrayCopy()`, but it is invoked in the Jsonify too and what happens is that `json_encode` encodes a basic array and not a `ArrayObject`.

The flow is like: `$model->toJson()` -> `json_encode($model->jsonSerialize())` -> `$model->toArray()` -> `attributesToArray()` that's gonna handle every cast serialization.

A solution could be to edit `jsonSerialize` of `ArrayObject` to return itself, instead of an array and then exclude `ArrayObject` instances from `addCastAttributesToArray`, this would still allow users to write `$model->content->toArray()` but also correctly serialize empty arrays into an object, **BUT** it would introduce a breaking change because `$model->content` won't be anymore an array but an instance of `ArrayObject`.

Idk if this is solvable at all without introducing a breaking change, atm I'm just gonna stick with my own `AsArrayObject` implementation I guess.

**Comment by taylorotwell** [comment]
I don't really see a big problem with the current behavior.

**Comment by danilopolani** [comment]
The problem is that `ArrayObject([])` natively serializes to `{}`, but the current `AsArrayObject` cast serializes to `[]`, and if you work with JSON having a correct serialization taking advantage of `ArrayObject` would be great. It's like we're using `ArrayObject` but we're not really. 

Anyway I guess we have to continue with a custom implementation, thank you anyway :)
