### ISSUE TITLE
The controller property for serialized route via Illuminate\Routing\Route::prepareForSerialization() is not null for home route only.

### ISSUE THREAD

**Issue by namaan7372** [laravel/framework#36381]
- Laravel Version: 8.29.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.31

### Description

I have a route cache implementation and am running into a strange bug that is caused by the Illuminate\Routing\Route for the home route to fail to null the controller property after preparing for serialization. This causes the route caching to fail of course since the controller property of just this home route contains a non-null closure, as opposed to all the other routes which, after calling $route->prepareForSerialization(), have their controller property set to null.

### Steps To Reproduce

I am using the following routes for testing, but you can try changing the products route to anything that points to an existing controller other than the HomeController. Perhaps it has to do something with all the other routes (in my codebase) pointing to controllers that are in a subdirectory as opposed to the home route which points just to 'HomeController'.

```
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('products', ['as' => 'products', 'uses' => 'Models\Products\ProductLinesController@index']);
```

And then when I run the following routine, I can see that the home route still has a closure defined in its controller property:

```
        $routes = Route::getRoutes();

        foreach ($routes as $route)
        {
            $route->prepareForSerialization();
        }

        dd($routes);
```

Currently, I just put a kludge that manually nullifies the controller property after calling prepareForSerialization() as a workaround.

**Comment by danilopolani** [comment]
I didn't get the issue 100%, but in the past I had issues with routes defined as `MyController@action` syntax, instead switching that code to the L8 syntax  `[MyController::class, 'action']` solved.

**Comment by namaan7372** [comment]
I just realized at least one part of my report is erroneous, namely where I said "...as opposed to all the other routes which, after calling $route->prepareForSerialization(), have their controller property set to null," because all the other routes don't "have their controller property set to null," as far as I can tell, but rather that the controller property on all routes besides the home route is null to begin with.

And I tried updating the routing syntax for the home route to ```Route::get('', [HomeController::class, 'index'])->name('home');``` but I still have the same issue of the controller property being defined with a closure.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
