### ISSUE TITLE
The avg() method should return a float|int instead of string (or mixed)

### ISSUE THREAD

**Issue by Livijn** [laravel/framework#36391]
- Laravel Version: 8.0
- PHP Version: 8.0
- Database Driver & Version: MySQL

### Description:
When using the *avg()* method, the return value is a string when it should return a float. For example this line of code `round($this->reviews->avg('rating'))` produces this error:
> TypeError : round(): Argument #1 ($num) must be of type int|float, string given

This only affects PHP 8.

**Comment by taylorotwell** [comment]
We return what PDO returns. You can cast it if you need to. But, changing it on a patch release would be a breaking change.
