### ISSUE TITLE
Illuminate ArrayConstraint Namespace error in Lumen testing

### ISSUE THREAD

**Issue by Paladin** [laravel/framework#36393]
- Lumen Version: Lumen (8.2.3) (Laravel Components ^8.0)
- PHP Version: 8.0.1
- Database Driver & Version: N/A (No Database involved)
- PHPUnit Version 9.5.1

### Description:
When running a simple test against a JSON response, the test

 $this->response->assertJson(['seed' => 'fred']);

fails, I suspect because of a name spacing error/change.

### Steps To Reproduce:

1. Set up a controller that will return a response of a single JSON pair. I was returning { 'seed': 'fred'} in this instance, just noodling around.
2. Run the above test on the response.

It will fail with the message:

TypeError: PHPUnit\Framework\Constraint\Constraint::fail(): Argument #3 ($comparisonFailure) must be of type ?PHPUnit\SebastianBergmann\Comparator\ComparisonFailure, SebastianBergmann\Comparator\ComparisonFailure given, called in lumen-project/vendor/illuminate/testing/Constraints/ArraySubset.php on line 85

On line 8 of the ArraySubset.php is the ComparisonFailure reference:

`use SebastianBergmann\Comparator\ComparisonFailure;`

I find replacing that with

`use PHPUnit\SebastianBergmann\Comparator\ComparisonFailure;`

cures this issue.

It doesn't appear to be a regression, so is this perhaps a change introduced by later versions of PHPUnit (see version above)? Or did I screwup my baseline install somehow (always possible, after all, this *is* the first start I've made with Lumen).

**Comment by driesvints** [comment]
The `PHPUnit\SebastianBergmann\` doesn't exists afaik. Can you point out the package that provides that namespace?

**Comment by Paladin** [comment]
Well, after spending time looking for the exact source file for it, I left it aside.

Where I *do* find it is in the class declaration for ComparisonFailure, but the only place I found that was in the file /usr/local/opt/phpunit/bin/phpunit -- the context for it is included here:

declare (strict_types=1);
/*
 * This file is part of sebastian/comparator.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace PHPUnit\SebastianBergmann\Comparator;

use RuntimeException;
use PHPUnit\SebastianBergmann\Diff\Differ;
use PHPUnit\SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder;
/**
 * Thrown when an assertion for string equality failed.
 */
class ComparisonFailure extends \RuntimeException
{


Which starts at line 8470 in my copy of that file.

**Comment by Paladin** [comment]
For those coming to this issue and expecting not to be left hanging, I have a resolution:

The root cause is PHPUnit installation method. I'm using a PHPUnit installed via phar, and when it's installed via phar, this class (and many others) are namespaced to PHPUnit by PHP-spacer. If your PHPUnit is installed via Composer, the PHPUnit prefix is not added to the classes.

**Comment by xrobau** [comment]
> The root cause is PHPUnit installation method

Thanks @Paladin for that! This was news to me, especially because as part of our default PHP Docker Container we install /usr/bin/phpunit (as a phar), so it's in the default $PATH. Everything has worked flawlessly until today, when I tried to do a test of `$this->getJson($url)->assertJson(["foo" => "bar", "bar" => "foo"]);` (Also deliberately adding some keywords so this answer gets some google juice).

So simply remove the phpunit that's in your $PATH, or If you can't for whatever reason, instead of running `phpunit test/Unit/FooTest.php`, run `vendor/bin/phpunit test/Unit/FooTest.php`.
