### ISSUE TITLE
Eloquent: String with dots are splitted, causing SQL syntax error

### ISSUE THREAD

**Issue by sinnrrr** [laravel/framework#36405]
- Laravel Version: 8.29.0
- PHP Version: 8.0.2
- Database Driver & Version: php8.0-mysql 8.0.2-3+ubuntu20.04.1+deb.sury.org+1

### Description:
When doing a query in which the string contains dots, for example, `'pass.evoraid.com.ua'`, in SQL it translates as follows: ```SQL: select `pass`.`ua`.`com`.`evoraid` ...```, which causes SQL syntax error.

### Steps To Reproduce:
1) Fresh laravel project, with database connection set up
2) `Model::first(['custom_field' => 'pass.evoraid.com.ua']);`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
