### ISSUE TITLE
Do Laravel's model support $dateFormat property? If yes, why model's toArray method can't change the format

### ISSUE THREAD

**Issue by leopoldwong** [laravel/framework#36420]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

**Comment by rodrigopedra** [comment]
`$dateFormat` is meant to be used to format for databases.

For serializing to Array/JSON use the `serializeDate()` method:

https://laravel.com/docs/8.x/eloquent-serialization#date-serialization

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
