### ISSUE TITLE
Laravel Sail share via expose doesn't seem to function at all

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#36425]
- Laravel Version: 8.29.0
- PHP Version: 8.0.2
- Database Driver & Version: N/A

### Description:
[Originally posted as a discussion](https://github.com/laravel/framework/discussions/35987), but it seems I'm not the only one with this issue so I thought I would escalate into a bug report.

Trying to share my Laravel site with my phone to do some testing via Laravel Sail.

So I type in `sail share` and get the usual output. When I visit the dashboard URL that appears on my Mac, I get Site cannot be reached.

When I try to visit the URL generated by sail locally and via my phone, I get `ERR_EMPTY_RESPONSE` in Chrome.

Not sure whats going on? I'm using Docker Desktop for Mac. Am I doing something wrong here?

### Steps To Reproduce:

1. Install Laravel on MacOS
2. Install Laravel Sail with the PHP 8 runtime
3. Make sure your Laravel welcome page is showing locally
4. Run `sail share` to start sharing your site
5. See that you cannot visit the shared site with the given link
6. See that you also cannot see the dashboard

**Comment by driesvints** [comment]
Yeah it's broken for me as well. I'll check in with @mpociot.

**Comment by Khalid3bdallah** [comment]
+1

**Comment by taylorotwell** [comment]
Pushed up a patch.

**Comment by Jamesking56** [comment]
Thanks for the speedy patch @taylorotwell @driesvints :+1:

**Comment by jearsonbgomez** [comment]
@taylorotwell Thanks for the updates.

**Comment by Jamesking56** [comment]
@taylorotwell @driesvints This has broken again with the release of Sail 1.4.7

**Comment by bjuppa** [comment]
This issue is back for me as well, both on `v1.4.7` & `v1.4.8`...

However, I do get sharing working again when downgrading to Sail `v1.4.6`!

**Comment by driesvints** [comment]
Which OS?

**Comment by bjuppa** [comment]
I'm on  macOS 11.2.3

Could this be a problem in the `latest` expose server that was changed in this PR and released in `v1.4.7`?
https://github.com/laravel/sail/commit/cebaebc0bb3806f4cf7bc71564acbfe8c12a8923

**Comment by driesvints** [comment]
I wouldn't see how? It just pulls in the latest version which fixed the previous issue.
