### ISSUE TITLE
foreignIdFor()->constained() doesn't work when model table name is customized

### ISSUE THREAD

**Issue by shawnhooper** [laravel/framework#36438]
- Laravel Version: 8.30.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8.0.22

### Description:

If a model has a custom table name, using it as the the model argument of the foreignIdFor() Blueprint method doesn't work. It still tries to use the default table name.

### Steps To Reproduce:

1. Create the models and migrations:

`sail artisan make:model -m Widget && sail artisan make:model -m Basket`

2. Update the Widget model, adding a custom table name:

```
class Widget extends Model
{
    use HasFactory;
    
    protected $table = 'my_widgets';
}
```

3. Update the migration for the Widget model to use the custom table name:
```
class CreateWidgetsTable extends Migration
{
    public function up()
    {
        Schema::create('my_widgets', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });
    }
}
```

4. Update the migration for the Basket model to add a foreign ID reference to Widget:

```
class CreateBasketsTable extends Migration
{
    public function up()
    {
        Schema::create('baskets', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Widget::class)->constrained();
            $table->timestamps();
        });
    }
}
```

4. Run `sail artisan migrate` 

The error:

SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'widgets' (SQL: alter table `baskets` add constraint `baskets_widget_id_foreign` foreign key (`widget_id`) references `widgets` (`id`))

**Comment by taylorotwell** [comment]
Here is how the method works: 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/463230/109823827-e5f65300-7bfd-11eb-913d-0675ecc6decb.png">

If that convention doesn't work for you don't use that method.

**Comment by halivert** [comment]
@shawnhooper I don't know if this works for you, but `constrained` method, could receive table name as first parameter.
