### ISSUE TITLE
WITH clause in Query Builder for subquery factoring

### ISSUE THREAD

**Issue by random-42** [laravel/framework#36439]
I've been reading through \Illuminate\Database\Query\Builder and other relevant files but have been unable to see a way to append or wrap any SQL with the WITH clause for subquery factoring. At the moment my query preforms multiple joinSub from the same query, which I would like to change to being within a WITH clause for optimization.

**Comment by rodrigopedra** [comment]
CTE (Common Table Expressions)  are not yet supported by the query builder.

Alternatives are:

- Use the `->fromQuery()` method:

~~~php
$sql = 'WITH(...) SELECT ...';

$posts = Post::fromQuery($sql, $bindings);
~~~

- Search for a third-party package that adds this feature
- Submit a PR to add this feature.

**Comment by mtorromeo** [comment]
Is CTE support even being considered yet?

Closing this issue did not help keep track of it, I guess.

Why not integrate the functionality from https://github.com/staudenmeir/laravel-cte ?
