### ISSUE TITLE
DB Migrate with .dump

### ISSUE THREAD

**Issue by vladislavtkachenko** [laravel/framework#36434]
- Laravel Version: 8.22.1
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 5.7

### Description:
When using Manage Service for MySQL and trying to perform migrations, have error
ERROR 3159 (HY000): Connections using insecure transport are prohibited while --require_secure_transport=ON.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
