### ISSUE TITLE
Laravel 8 Collection::prepend with `$key = null` results in "" array key instead of `0`

### ISSUE THREAD

**Issue by Levivb** [laravel/framework#36446]
- Laravel Version: `v8.30.0`
- PHP Version: `7.4.14`
- Database Driver & Version: `mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for osx10.15 (x86_64) using readline 5.1`

### Description:
The resulting array from `Illuminate\Support\Collection::prepend` with `$key = null` as parameter changes from Laravel 7 to Laravel 8.
In Laravel 7 the following is executed:
1. `$collection = new Illuminate\Support\Collection([$someVariable1]);`
1. `$collection->prepend($someVariable2, null);`
2. `$this->items = Arr::prepend($this->items, $value, $key);`
3. 
```php
public static function prepend($array, $value, $key = null)
    {
        if (is_null($key)) {
            array_unshift($array, $value);
        } else {
            $array = [$key => $value] + $array;
        }
```
Resulting in running `array_unshift($array, $value);` because `$key === null`.
The keys of `$array` are:
```
Illuminate\Support\Collection^ {#5146
  #items: array:2 [
    0 => 0
    1 => 1
  ]
}
```

In Laravel 8 a similar flow, with a subtle but important difference is executed:
1. `$collection = new Illuminate\Support\Collection([$someVariable1]);` // same
1. `$collection->prepend($someVariable2, null);` // same
2. `$this->items = Arr::prepend($this->items, ...func_get_args());` // almost same, but not the culprit
```php
public static function prepend($array, $value, $key = null)
    {
        if (func_num_args() == 2) { // not the same.
            array_unshift($array, $value);
        } else {
            $array = [$key => $value] + $array;
        }
```
Resulting in running `$array = [$key => $value] + $array;` because `$key` might be explicit `null`, but it is passed on. Making `func_num_args() === 3`
The keys of `$array` are now:
```
Illuminate\Support\Collection^ {#4489
  #items: array:2 [
    0 => ""
    1 => 0
  ]
}
```

In our case the following code crashes:
```
// $this = Collection subclass
        return $this
            ->each(
                function (Component $component, $i): void {
                    $prevComponent = $this->get($i - 1) ?: null;
                    $component->previousComponent = $prevComponent;

                    $nextComponent = $this->get($i + 1) ?: null;
                    $component->nextComponent = $nextComponent;
                },
            );
```
`$i` used to be `0` and `1`, but is now `""` and `0`. Casing php to crash on `'' -1`

Is this expected behaviour or a refactor oversight?
`""` isn't really an expected key when working with a numerical indexed Collection.

### Steps To Reproduce:
In Laravel 7 and 8:
```
dd((new Illuminate\Support\Collection(['1']))->prepend('2', null)->keys())
```

**Comment by taylorotwell** [comment]
Unlikely we would change this back to some previous behavior because of just creating another breaking change on v8.
