### ISSUE TITLE
"php artisan route:cache" should produce the same file when nothing changed in the (unnamed) routes

### ISSUE THREAD

**Issue by MircoBabin** [laravel/framework#36448]
- Laravel Version: 7.30.0
- PHP Version: 7.2.31
- Database Driver & Version: MySql 8.0.16

### Description:
I expect the `routes-v7.php` to be determenistic, giving the same result for the same set of routes, when the routes did not change.

`php artisan route:cache` generates each time a different **bootstrap/cache/routes-v7.php** file, when there are **unnamed routes**. Unnamed routes are currently assigned a random name in `Illuminate\Routing\AbstractRouteCollection`

```php
    /**
     * Get a randomly generated route name.
     *
     * @return string
     */
    protected function generateRouteName()
    {
        return 'generated::'.Str::random();
    }

```
Because part of my workflow is to always call the `route:cache` before a `git push` there is always a different `bootstrap/cache/routes-v7.php` build. The changed `routes-v7.php` file is committed and is deployed from the git repository, because there is no SSH access on the production server. The production server in on shared hosting.

So I have many unnecessary commits, because there were changes in the `routes-v7.php` file, while there was no change in the routes ( `routes/web.php` ).

P.S. the `route:cache` is automated so I don't have to think about rebuilding the route cache when something changes.

### Steps To Reproduce:

1) have a `routes/web.php` with unnamed routes e.g.

```
<?php

    Route::get('login', 'Auth\\AuthController@getLogin')->name('login');
    Route::post('login', 'Auth\\AuthController@postLogin');
    Route::get('logout', 'Auth\\AuthController@getLogout');
    Route::post('logout', 'Auth\\AuthController@getLogout')->name('logout');

```

2) call `php artisan route:cache`
3) copy `bootstrap/cache/routes-v7.php` to `bootstrap/cache/routes-v7.php.first`
4) call `php artisan route:cache`
5) compare `bootstrap/cache/routes-v7.php` with `bootstrap/cache/routes-v7.php.first`. They are different, but should be the same.

### Other

See also my question in discussions which yielded no answer: https://github.com/laravel/framework/discussions/33963

**Comment by taylorotwell** [comment]
This isn't really a "bug" in the framework.

**Comment by MircoBabin** [comment]
In what category does this issue belong , if this is not considered a bug?

Should I file it somewhere else ?

**Comment by driesvints** [comment]
> The changed routes-v7.php file is committed and is deployed from the git repository

Because this is your specific workflow which is different from the framework's default setup this isn't considered a bug. We can't help you here.

**Comment by MircoBabin** [comment]
Sorry to hear Laravel does not support hosting without SSH access.

Well I guess I have to live with this ever changing routes-v7.php file then.

Because this really bugs me, if I would create a pull request regarding this issue, would that be a candidate for being merged. Or has such an attempt no chance ?

**Comment by lk77** [comment]
You could just name all your routes, it's not really a good practice to have unnamed routes anyway

**Comment by MircoBabin** [comment]
> Mathias E. sent me an email: You could just name all your routes, it's not really a good practice to have unnamed routes anyway

Thanks for this suggestion. I just named my unnamed routes "unnamed.1" to "unnamed.259". Yep there are 259 unnamed routes, because this project originates from Laravel 4.2 and was shifted to Laravel 7.

After naming everything (don't forget `api.php` and other files in the `routes` folder), the `php artisan rout:cache` is finally determenistic.

**Comment by driesvints** [comment]
> Sorry to hear Laravel does not support hosting without SSH access.

That doesn't really have anything to do with this. You can't edit the cached routes file. We can't control what env you choose to host your project. If you don't have SSH access then some things like route caching is unavailable for you.
