### ISSUE TITLE
Config or env helpers wasn't recognized when using a dispatched class or just within a closure

### ISSUE THREAD

**Issue by legendofporg** [laravel/framework#36475]
- Laravel Version: v7.30.4 on composer.lock
- PHP Version: ^7.2.5
- Database Driver & Version:
mysql with QUEUE_CONNECTION=database 

### Description:
My challenge is that I have a Mailable class with custom template that sends email to multiple accounts.
With that said I need to put it on a dispatch helper or a ShouldQueue class.

### Steps To Reproduce:
handle function on ShouldQueue class
        Mail::to($email)->send(new OrgInvitation($organization_details, $invitation_details));

on the controller or command handle
        dispatch(new InviteQueue($email, $organization_details, $invitation_details));
        
 assuming all entries are correct and all classes required are imported properly,
 the error occurs when checking env MAIL_FROM_ADDRESS goes missing on triggering by dispatch.

**Comment by paras-malhotra** [comment]
Don't use env outside of your config files. Env function calls return null when config is cached. Docs [here](https://laravel.com/docs/8.x/configuration#configuration-caching).

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
