### ISSUE TITLE
Horizon: Target class [Illuminate\Database\Eloquent\Factory] does not exist.

### ISSUE THREAD

**Issue by samstreet** [laravel/framework#36505]
- Laravel Version: 8.31.0
- PHP Version: PHP 8.0.1
- Database Driver & Version: N/A

### Description:
Target class [Illuminate\Database\Eloquent\Factory] does not exist.
Horizon starts fine with no issues, issues arise after I try and access the /horizon url. From here the error is logged but the queue still runs, but the url returns a 400.

Looking through the code for 8.x, `Illuminate\Database\Eloquent\Factory` does no longer exist. This issue blocks up access to the Horizon dashboard but I am also experiencing issues elsewhere in our codebase where we have references to Illuminate\Database\Eloquent\Factory especially in places that extends the `ServiceProvider` of which we have many.

### Steps To Reproduce:
- Base Laravel install (8.x)
- Composer install Horizon
- Add relevant Horizon provider
- Run horizon
- Try and access /horizon and see a 400 error, in the logs see reference to `Target class [Illuminate\Database\Eloquent\Factory] does not exist.`

**Comment by driesvints** [comment]
There's no usages of this anymore in the latest Horizon. Please update your Horizon version.

**Comment by samstreet** [comment]
Horizon is up to date, this issue is present in the core laravel framework as seen in the following link; [no Factory class here](https://github.com/laravel/framework/tree/8.x/src/Illuminate/Database/Eloquent).

**Comment by driesvints** [comment]
I think the issue is coming from your code in your app instead. Did you upgrade to Laravel 8 and read the upgrade guide? Check this step: https://laravel.com/docs/8.x/upgrade#model-factories
