### ISSUE TITLE
The resource routes still working if the URL consists of alphanumeric for resource id

### ISSUE THREAD

**Issue by sachinkumar121** [laravel/framework#36517]
- Laravel Version: 7.30.4
- PHP Version: 7.3.7
- Database Driver & Version: MySql Server version: 10.3.16-MariaDB

### Description:

I am working on a Laravel application and I come across a very strange issue. I have defined the routes using the Route::resource function 

	Route::resource('posts', 'PostController');

and I generate the PostController using 

> php artisan make:controller PostController --resource --model=Post

command so it is using Implicit Binding for Post resource.

Now the URLs are 

	GET			/posts
	GET			/posts/create
	POST		/posts
	GET			/posts/{post}
	GET			/posts/{post}/edit
	PUT/PATCH	/posts/{post}
	DELETE		/posts/{post}

Everything is working fine. Let say I have a post whose id is 146. so the URL for the post detail page will be

	http://localhost/laravel-app/posts/146

This URL is working fine. But when I open the following URL it still working.

	http://localhost/laravel-app/posts/146re4dasdasda

	http://localhost/laravel-app/posts/146re4

	http://localhost/laravel-app/posts/146re

So I expected that the above mention URLs should return a 404 not found page. But it still shows the detail page for the post whose id is 146.

and the URLs are also working for edit, update or delete operations. i.e

	GET			/posts/146re4/edit
	PUT/PATCH	/posts/146re4
	DELETE		/posts/146re4

### Steps To Reproduce:
- Create a new Laravel project.
- Generate PostController using the "php artisan make:controller PostController --resource --model=Post" command
- create a sample post. let say the id is 121.
- Open /posts/121 it will works
- Open /posts/121abc/ it still working. But it should return 404 i.e. ModelNotFoundException

### key note:
- The same thing is also happening with apiResource. ie. Route::apiResource('posts', 'PostController');

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
