### ISSUE TITLE
Uuid of an sqs message is not preserved on message handling retry

### ISSUE THREAD

**Issue by SCIF** [laravel/framework#36514]
- Laravel Version: 8.25.0
- PHP Version: 7.4.15
- Database Driver & Version: SQS queue

### Description:

The body of an sqs message does contain `uuid` of original/first-attempt message rather than actual one. So collation/search of failed jobs is quite hard.

### Steps To Reproduce:

1. Put an invalid message into an SQS queue
2. Try to handle it with `queue:work`. Console output will be something like: 
```
[2021-03-09 11:22:44] [ab234df-dsfdfs-3243-vdsfdsfds] Processing: App\…
```
Uuid in message body will be: `ab234df-dsfdfs-3243-vdsfdsfds`. Message must fail and return back to the queue.
3. Try to handle it one more time. Console ouput will be something like:

```
[2021-03-09 11:22:50] [badf32432-dsfs543r4-76764-fdbfdf4sd] Processing: App\…
```

But `uuid` in message body will still be `ab234df-dsfdfs-3243-vdsfdsfds`

![sqs](https://user-images.githubusercontent.com/671925/110419002-6258cc80-80fd-11eb-8dcc-bee887927c82.png)

So either message id must be preserved or updated on every message handling attempt.

**Comment by driesvints** [comment]
> Laravel Version: 8.0.25

This version doesn't exists. Please provide the exact Laravel version you're experiencing this issue with.

**Comment by SCIF** [comment]
@driesvints 
Corrected, thanks!

**Comment by driesvints** [comment]
Hey @SCIF, this is the way it works atm. A retried job is a new job and therefor it needs a new ID and/or UUID. See https://github.com/laravel/laravel/blob/8.x/database/migrations/2019_08_19_000000_create_failed_jobs_table.php#L18

A correlation UUID sounds useful but that's more of a feature request. It's best that you either open an issue on the ideas repo or attempt a PR. Thanks

**Comment by SCIF** [comment]
@driesvints , the issue is not a new id itself, but the `uuid` property in the body of payload of a failed job is not up-to-date.

The failed job from my example has uuid `badf32432-dsfs543r4-76764-fdbfdf4sd` but the payload dump in failed_jobs table still has `uuid": "ab234df-dsfdfs-3243-vdsfdsfds"`.

This is not a feature request but a bug. I want to confirm this as a bug and I can make a PR fixing that.

**Comment by SCIF** [comment]
@taylorotwell , that's simple, let me show you.

Database jobs have DatabaseUuidFailedJobProvider [preserving](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php#L46-L67) UUID on fail and [replacing](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php#L93) id with UUID on fetch. But SQS doesn't have such database failed job provider and just [show](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Jobs/SqsJob.php#L90-L93) a messageId which is refreshed on every attempt while payload's uuid is not refreshed.

**Comment by taylorotwell** [comment]
Feel free to PR a fix.
