### ISSUE TITLE
RefreshDatabase trait does not execute schema:dump file.

### ISSUE THREAD

**Issue by tombanksme** [laravel/framework#36523]
- Laravel Version: 8.30.0
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0.23-0ubuntu0.20.04.1

### Description:

I've encountered the issue mentioned in #36294  and think I've managed to reproduce it in a fresh Laravel installation. Someone mentioned that I might be better making a new issue.

Hope this helps.

### Steps To Reproduce:

I've linked a GitHub repo with the exact code that I ran but here's a quick overview of how to replicate it.
- Created a new Laravel project.
- Created a "testing" connection in my config/database.php file & updated the phpunit.xml file to use it.
- Added RefreshDatabase trait to my TestCase class
- Created the Purchase model.
- Migrated, dumped & pruned the database.
- In the Feature/ExampleTest I attempt to get all Purchases from the database and get a table not found error.

https://github.com/tombanksme/laravel-prune-testing-issue

**Comment by taylorotwell** [comment]
On a fresh Laravel application I don't seem to have any issue - I don't need the $migrated = true stuff @crynobone mentioned:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/463230/110490430-eb4c1580-80b5-11eb-96d9-9198bc97c923.png">

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/463230/110490464-f4d57d80-80b5-11eb-8fec-b954dbcecee3.png">

**Comment by tombanksme** [comment]
Thank you for your responses. If I start a new project and add Taylor's code to my ExampleTest my tests also run correctly. The issue appears when I create a seperate database connection for the tests to run under.

So that the tests don't delete all of the data in my dev database I have a separate connection for my tests:
```
'testing' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'test_' . env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

Which I then add to my phpunit.xml using `<server name="DB_CONNECTION" value="testing"/>`.  The interesting thing is that the issue persists even if remove the "test_" from my database name. If phpunit.xml isn't using the default mysql connection the test fails with:

![Error Message](https://i.gyazo.com/4feb85e60484074e3780c83cd36b63d0.png)

**Comment by taylorotwell** [comment]
You need to schema:dump both connections (make sure both are fully currently migrated first):

```bash
php artisan schema:dump
php artisan schema:dump --database=testing
```

Then you will be able to test.
