### ISSUE TITLE
Service providers ignoring server variables set in phpunit.xml when running tests with artisan

### ISSUE THREAD

**Issue by PHLAK** [laravel/framework#36530]
- Laravel Version: 8.32.1
- PHP Version: 7.4.9 (don't think this matters though)
- Database Driver & Version: Any

### Description:

When running tests with artisan (i.e. `artisan test`) and access configuration variables in a provider class, server variables set in `phpunit.xml` are not read. This also applies to parallel tests.

### Steps To Reproduce:

  1. Create a new Laravel app (`laravel new laratest`)
    a. Note the `.env` file has an `APP_ENV` value of `local` 
    b. Note that the `phpunit.xml` file has an `APP_ENV` value of `testing`
  2. Dump the environment config value in the `AppServiceProvider`
  
      ```php
      class AppServiceProvider extends ServiceProvider
      {
          public function register()
          {
               dd(config('app.env'));
          }
      }
      ```

  3. Run the test suite with artisan (`artisan test`)
    a. **The output will be `local`** 
  4. Run the raw command (`vendor/bin/phpunit`)
    a. **The output will be `testing`**

**NOTE:** This also affects methods that rely on these environment variables (e.g. `$app->environment()` and `$app->isRunningUnitTests()`)

---

### Additional Information

After doing some digging I was able to dump the raw command that is [passed to the `Symfony\Component\Process\Process` class](https://github.com/nunomaduro/collision/blob/a31c2c41f413940afd087d0961195a1af3d72f22/src/Adapters/Laravel/Commands/TestCommand.php#L85-L97) under the hood when running `artisan test`. On my system that was the following.

```
'/usr/bin/php7.4' 'vendor/phpunit/phpunit/phpunit' '--configuration=/tmp/laratest/phpunit.xml' '--printer=NunoMaduro\Collision\Adapters\Phpunit\Printer'
```

Running this command worked as expected (output was `testing`).

**Comment by nunomaduro** [comment]
There is no issue here.

When you run "php artisan test" command, Laravel will boot itself with the console kernel using environment "local". Then it will run the "vendor/bin/phpunit" using the environment "testing".

Here is one example to understand that the "php artisan test" command is working as expected:

```php
class ExampleTest extends \Tests\TestCase
{
    public function testBasicTest()
    {
        dd(config('app.env'));
    }
}
```

<img width="1005" alt="Screenshot 2021-03-10 at 15 40 01" src="https://user-images.githubusercontent.com/5457236/110655680-2d10b500-81b7-11eb-988d-cdfb466dd938.png">

**Comment by PHLAK** [comment]
I understand but disagree that this is how it _should_ work. The Laravel documentation sets up an expectation that the variables set in `phpunit.xml` will apply to your tests.

> When running tests, Laravel will automatically set the configuration environment to testing because of the environment variables defined in the `phpunit.xml` file.

The fact that this doesn't (fully) apply when running `artisan tests` has and will continue to cause confusion at the least. In our case we resolve objects differently in the service providers based on environment variables (a common practice) and the difference in behavior between commands means we can't use `artisan tests` (without a work around).

If this is truly the expected behavior and wont be changed it should _at least_ be documented since running tests with artisan will behave differently than with the raw `phpunit`/`paratest` commands.

**Comment by nunomaduro** [comment]
@PHLAK The variables set in "phpunit.xml" do apply in your tests.

When you run "php artisan test", you do boot the framework - and run all services providers - to run artisan itself, therefore the environment is "local". Yet, once you use a feature test, the framework will be re-booted, this time with the environment "testing" and all the variables set in "phpunit.xml" - just like the normal PHPUnit command. Hope this clarifies things for you.

And by the way, the same thing applies to "php artisan test --parallel".
