### ISSUE TITLE
[8.x] Factory state return always the same value when seeding the database

### ISSUE THREAD

**Issue by ludo237** [laravel/framework#36541]
- Laravel Version: 8.32.1
- PHP Version: 8.0
- Database Driver & Version: MariaDB 10.5

### Description:

When I use a Database factory with a particular state, which randomize a column value, it works for a single creation but when I introduce either `times()` or `count()` the created records have always the same value for the given state.

### Steps To Reproduce:

- Create a Database Factory, for example `UserFactory`
- Add a definition
- Add a state like this

```php
    public function withName() 
    {
        return $this->state([
            "name" => $this->faker->name,
        ]);
    }
```

- Create a database seeder and paste this code `UserFactory::new()->count(30)->withName()->create();`
- Run the seeder

The expected result is 30 records each with a different name instead I get 30 records all with the same name.

### What I tried so far

- Call the factory from the model perspective with `User::factory()` 
- Force the name to be empty or null inside the definition
- Use `times()` instead of `count()` 

Nothing worked, I still get 30 rows all with the same name.

Am I missing something here?

**Comment by browner12** [comment]
Is this documented at all? I also recently ran into this issue, couldn't find anything in the docs, but was lucky enough to remember having seen this issue come up recently.

Also, is there a use case for it not behaving this way always?  Wouldn't we always want states to serve up different values, and if so, shouldn't we adjust core to handle this for us?

**Comment by ludo237** [comment]
@browner12 it's not documented that's why it was confusing.
