### ISSUE TITLE
An argument with name "class" already exists.

### ISSUE THREAD

**Issue by code2prog** [laravel/framework#36557]
- Laravel Version: 8.32.1
- PHP Version: 7.4.16
- Database Driver & Version: -

### Description:
After upgrade laravel/framework from v. 8.31.0 to 8.32.1 throw error in console `An argument with name "class" already exists.` after dump-autoload. Reverting to a previous version fixes the problem

### Steps To Reproduce:
`composer upgrade laravel/framework`

**Comment by driesvints** [comment]
I'm pretty sure that this is caused by https://github.com/laravel/framework/pull/36513 but I don't see how that's breaking. Are you modifying the command in any way? We'll need a lot more info here. How are you calling your seeder classes? Are there internal artisan calls in your code/tests?

/cc @jasonmccreary

**Comment by code2prog** [comment]
@driesvints I didn't change anything. The only thing that might have to do with it is tenancy/multi-tenant. But this package was not updated at the same time

**Comment by driesvints** [comment]
@code2prog ah I wasn't asking if you changed anything. I'm asking how you're calling the db:seed command.

**Comment by code2prog** [comment]
https://github.com/tenancy/multi-tenant/issues/988
It seems that here is the reason

**Comment by jasonmccreary** [comment]
@driesvints, if you're worried about conflicts with community packages, we should try to rename it to `seeder`. But what's to say another package doesn't call it that. 🙃

**Comment by driesvints** [comment]
Not entirely worried, was just wondering how your change broke certain use cases.

**Comment by driesvints** [comment]
In general that wasn't part of the public API. If people are overwriting it in that way then we can't protect against that.

**Comment by jonquintero** [comment]
That is not true at all, rather this new change overwritten something and broke a package

**Comment by driesvints** [comment]
@jonquintero we can't control the ways in how someone overwrites this. If you're overwriting a command and adding arguments of your own then you should be aware that an upstream change can break it. This is different from, for example, method signatures which are part of the public API of a codebase.

**Comment by jonquintero** [comment]
@driesvints I understand your point and it is totally valid, but my point is that this new change [#36513](https://github.com/laravel/framework/pull/36513) overwritten something that the mentioned package had been using for a long time and broke it, reverting to a previous version fixes the problem (8.31.0). What's great about all this? That forces developers to update their packages and not forget about them

**Comment by driesvints** [comment]
@jonquintero you can't expect us to keep in mind every single way someone overwrites something in the framework. If we had to do that we had to do new major releases each week just to make sure that no small change breaks something in a third party app.

**Comment by jonquintero** [comment]
@driesvints I know and you are right, that what I said: What's great about all this? That forces developers to update their packages and not forget about them @ArlonAntonius

**Comment by driesvints** [comment]
ah sorry, I misunderstood you there 👍

**Comment by ArlonAntonius** [comment]
Tbh, I really hope Laravel is not gonna think too much about community packages and all the stuff they do; would be a mess and they would not be able to add anything anymore to the ecosystem.

The PR they did was perfect, it's simply up to us to fix the package, thanks for finding this problem and taking the time to investigate and discuss this topic 🙏

**Comment by fulopattila122** [comment]
For the sake of reference, I'm adding here another constellation that breaks.
I'm having the same error, without having `tenancy/multi-tenant` installed.
I have another similar package though, `stancl/tenancy` - v3.4.0.


```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading laravel/framework (v8.29.0 => v8.32.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading laravel/framework (v8.32.1)
  - Upgrading laravel/framework (v8.29.0 => v8.32.1): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

                                                 
  An argument with name "class" already exists.  
                                                 

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
