### ISSUE TITLE
Cursor on query ignores trashed relations

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#36565]
- Laravel Version: 6.20.18
- PHP Version: 7.3.25
- Database Driver & Version: MySQL 5.7.31

### Description:
Cursor on query ignores withTrashed() on relations.

### Steps To Reproduce:
Lets say we have a Contact model with phones that have types and we want to take deleted phones also
```
$query = Contact::query();
$query->with([
    'phone'             => function($q) {
        $q->with('types');
        $q->withTrashed();
    },
]);
$query->whereHas('cars', function(Builder $builder1) use ($car) {
    $builder1->where('car_id', '=', $car);
});
```

if you have 10 phones and 2 are deleted and you do 
`$query->get() `
it will bring all 10 results
If you do loop with cursor
` $query->cursor() as $item`
 and try to get **$item->phone->number**
 it will bring return null for those 2 deleted records

**Comment by crissi** [comment]
pretty sure with() does not work at all with cursor()

**Comment by mariosvasiliou** [comment]
> 
> 
> pretty sure with() does not work at all with cursor()

If you do the below you will see that works...
` $query = Contact::query();
        $query->with('phone');
        foreach ($query->cursor() as $item){
            logger($item->phone->number);
        }`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
