### ISSUE TITLE
Laravel 8 console exception not returning proper exit code

### ISSUE THREAD

**Issue by Swanty** [laravel/framework#36571]
- Laravel Version: 8.28.1
- PHP Version: 7.3.27
- Database Driver & Version: N/A

### Description:
I tried to deploy new project, but deployer didn't fail on exception due to improper exit code.

### Steps To Reproduce:
```
sudo chmod 000 storage/logs/laravel.log
php artisan tinker --execute="throw new \Exception('test')"
echo $?
```

Output:
```
➜  sudo chmod 000 storage/logs/laravel.log && php artisan tinker --execute="throw new \Exception('test')"; echo $?

   UnexpectedValueException

  The stream or file "/Users/otm/work/aviator/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:111
    107▕             restore_error_handler();
    108▕             if (!is_resource($this->stream)) {
    109▕                 $this->stream = null;
    110▕
  ➜ 111▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $this->url));
    112▕             }
    113▕         }
    114▕
    115▕         if ($this->useLocking) {

      +7 vendor frames
  8   app/Exceptions/Handler.php:47
      Illuminate\Foundation\Exceptions\Handler::report(Object(UnexpectedValueException))

      +2 vendor frames
  11  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException(Object(UnexpectedValueException))
0
➜  
```
Note the 0 above. It should be 1.  

I would appreciate if anyone could help me understand why exit code was not 1 🙏

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
