### ISSUE TITLE
getDirty() not working for datetime and date fields + carbon

### ISSUE THREAD

**Issue by abrampl** [laravel/framework#36582]
When cast datetime, even if orginal = attribute same carbon date, always show changes. Cast is not enought.

Quick fix: 

To model add 

```
protected $dates = ['my_date'];

protected $casts = ['my_date' => 'datetime:Y-m-d']
```

**Comment by martindanielsson** [comment]
That's really funny, I was just going to create an issue for this. The problem occurs when you have a custom format to the cast, it causes `HasAttribute::getCastType` to return `custom_datetime` and `isDirty()` will only validate date objects properly if the cast type is date or datetime.

```
    protected function isDateCastable($key)
    {
        return $this->hasCast($key, ['date', 'datetime']);
    }
```

I was going to suggest a PR that adds `custom_datetime` to `HasAttribute::isDateCastable` :)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
