### ISSUE TITLE
[8.x] Between method doesn't change cron expression in Scheduler

### ISSUE THREAD

**Issue by tcov189** [laravel/framework#36581]
- Laravel Version: 8.31.0
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 5.7

### Description:
When defining a new schedule command, the `between` method doesn't appear to be applying to the cron expression.

```php
// app/Console/Kernel

protected function schedule(Schedule $schedule)
    {
        $schedule->command('foo')
          ->hourly()
          ->between('4:00', '5:00');
    }
```
Running `php artisan schedule:list` shows the wrong intervals and next due to be after `5:00`

![image](https://user-images.githubusercontent.com/8125119/110958434-4ed27f00-8312-11eb-8729-ccd679b19be5.png)

### Steps To Reproduce:
1. Add the above task to `app/Console/Kernel.php@schedule` 
2. Open terminal and run `php artisan schedule:list`
3. Should see Interval set to `0 * * * *` and Next Run will be set to time after end time

**Comment by driesvints** [comment]
Yeah I see the same. But this is more of a feature request than a bug. We'd appreciate a PR if anyone can help us out with this one. Thanks

**Comment by tcov189** [comment]
@driesvints Thank you for looking at this.

Can I ask why this is a feature request and not a bug? 

The documentation says that using `schedule:list` will show you when the task is scheduled to run again, but it's clearly not doing that for schedules using the `between` method.

**Comment by driesvints** [comment]
Okay, I'll re-open this. Appreciating a PR regardlessly.

**Comment by tcov189** [comment]
I'll take a crack at it

**Comment by taylorotwell** [comment]
Looking at the code it is because the `between` method really just registers a `when` callback that is evaluated at runtime. The cron expression itself is not modified. So, the definition will still be respected and the command will only run at the specified times - but just the `schedule:list` doesn't reflect that.

**Comment by tcov189** [comment]
@taylorotwell I see. I have a PR coming soon that I think will fix the issue with `schedule:list`, but I am not sure if the implementation is correct.

**Comment by tcov189** [comment]
After many attempts to fix this for all scenarios (I could think of), I am throwing in the towel.

I am going to close this out as it seems like many people are not concerned about it.

Thanks for your time and for the great framework!
