### ISSUE TITLE
Testing Job Batching 

### ISSUE THREAD

**Issue by clevonnoel** [laravel/framework#36590]
- Laravel Version: 8.31.1
- PHP Version: 7.4
- Database Driver & Version: Msyql

### Description:

When testing job batching, without initially specifying the batch, the pending batch count return 0.

### Steps To Reproduce:

```php

$batch = Bus::batch([])
    ->allowFailures()
    ->dispatch();

Transaction::cursor()
    ->map(fn(Transaction $transaction) => new ProcessTransaction($transaction))
    ->filter()
    ->chunk(1000)
    ->each(function (LazyCollection $jobs) use ($batch){
        $batch->add($jobs);
    });

```

In a test class

```php
Bus::assertBatched(function(PendingBatch $batch){
    return $batch->jobs->count() === 3; // batch count returns 0
});
```

**Comment by themsaid** [comment]
The `PendingBatch` object only stores the initial jobs passed to the batch, not jobs that was added later.

**Comment by clevonnoel** [comment]
@themsaid yes I noticed. Since the dispatch function is called before the new jobs are added the PendingBatch object is not updated. 

The application works okay but the test fails. The fake bus should be able to catch all jobs added after so that the assertion is correct.

**Comment by driesvints** [comment]
@clevonnoel I've attempted a PR for this. Can you please check it and try it out? You'll need to remove the type-hint from the assertion though: https://github.com/laravel/framework/pull/37877

**Comment by taylorotwell** [comment]
Don't dispatch the pending batch until it is fully hydrated.

```php
$batch = Bus::batch([])->allowFailures();

$batch->add([...]);

$batch = $batch->dispatch();
```
