### ISSUE TITLE
[6.x] Cookie encryption changes broke vue & laratrust

### ISSUE THREAD

**Issue by Jelle-S** [laravel/framework#36599]
- Laravel Version: 6.18.43
- PHP Version: 7.4.12
- Database Driver & Version:
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Description:
When updating my laravel application to 6.18.43 (with a vue frontend that uses cookies, not bearer tokens), the vue api calls started failing (HTTP 401). After digging through the changelog I found https://github.com/laravel/framework/pull/33662, where @danielsefton suggested downgrading to 6.18.26 fixed the issue for them. I can confirm this fixes it for me as well, but obviously it's not the ideal solution.

### Steps To Reproduce:
Set up a laravel application with laratrust  (cookie authentication) & vue in laravel <=6.18.26, then upgrade to laravel >=6.18.27

**Comment by driesvints** [comment]
These changes were part of a security release and are unfortunately not reversible. Please see https://blog.laravel.com/laravel-cookie-security-releases
