### ISSUE TITLE
[8.x] pushMiddlewareToGroup not working on Provider::register method

### ISSUE THREAD

**Issue by lk77** [laravel/framework#36604]
- Laravel Version: 8.32.1
- PHP Version: 7.2.27
- Database Driver & Version: mysql 5.7

### Description:

It seems that pushMiddlewareToGroup is not working when inside a provider register method

### Steps To Reproduce:

Add a middleware inside register method, it does not work :

```
Route::pushMiddlewareToGroup('web', MyMiddleware::class);
```
middleware is not called at all.

add the same code in boot() method and see that it works

it was working fine on v8.25.0

### My Use Case

i'm using https://github.com/NoelDeMartin/laravel-dusk-mocking to mock some facades inside my dusk tests, like Socialite,
and since their middleware is added in their provider, it cease to work at some point. 

if i edit this file :
https://github.com/NoelDeMartin/laravel-dusk-mocking/blob/master/src/MockingServiceProvider.php

and move `pushMiddlewareToGroup` calls to the boot method, it works again.

thanks.

**Comment by driesvints** [comment]
It's not meant that you execute services like this in a service provider's register method. The register methods are only there to wire things into Laravel's container. The boot method is the correct place for this.

**Comment by lk77** [comment]
yes but it was working fine previously and a lot of third party packages were relying on it

**Comment by driesvints** [comment]
@lk77 that wasn't intended to work. Sorry if this broke anything but we don't consider that a BC.
