### ISSUE TITLE
User is not authenticated even if Auth::login() have been executed.

### ISSUE THREAD

**Issue by sawirricardo** [laravel/framework#36614]
- Laravel Version: 8.32.1
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
I use Valet, and mailhog for the email testing. This is just basic sign up form. User are not authenticated even if in the register path, they have been logged in right after the user instance has been created.

### Steps To Reproduce:
In POST /register controller
```
Auth::login($user= User::create([...])); <-- here we login the user right after the user created.
event(new Registered($user));
```

then, when user activate from their email, this happened.
```
Route::get('email/verify/{id}/{hash}',function (EmailVerificationRequest $request) {
 // user is not authenticated, thus redirected again to login route.
 // this happened again and again when we click the link from email verification.
})->middleware(['auth','signed',...]);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lk77** [comment]
You can't know for sure which browser will be used when clicking on a link from a mail, 
the user will have to login

**Comment by sawirricardo** [comment]
Hi @lk77, thanks for clarifying this. I thought the same. However, when I learnt from the docs https://laravel.com/docs/8.x/verification#the-email-verification-handler,  it implies that the route should use "auth" middleware.

The EmailVerificationRequest also still uses the $this->user()->getKey() validation (which will return null in this case anyway).

P.S. To you who face this in the future. My temporary suggestion is to not use EmailVerificationRequest. Do what @lk77 say above. Thank you
