### ISSUE TITLE
Database Testing, `for` does not seem to work?

### ISSUE THREAD

**Issue by MeerKatDev** [laravel/framework#36611]
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
I'm trying to use a Seeder with multiple factories. I understand from [here](https://laravel.com/docs/8.x/database-testing#belongs-to-relationships) that it works like this:
```php
$user = User::factory()->create();

$posts = Post::factory()
            ->count(3)
            ->for($user)
            ->create();
```
so I'm writing this:
```php
      $taste = Taste::factory()->create();
      $brand = Brand::factory()->create();
      $brand_datasheet = BrandDatasheet::factory()
        ->for($taste)
        ->for($brand)
        ->create();
```
both `BrandDatasheet` and `Product` have the `brand_id` and `taste_id`. Upon running it in tinker manually, or using 

```
php artisan db:seed --class=ProductSeeder
```

I obtain this:

```
   BadMethodCallException 

  Call to undefined method App\Models\BrandDatasheet::taste()
```
All the parties involved have `use HasFactory`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MeerKatDev** [comment]
@driesvints this in facts seems to me like a bug, that's why I opened it as a bug report. I mimicked the steps in your docs and it just doesn't work, how do you know it's not a bug?
