### ISSUE TITLE
laravel/breeze replace everything...

### ISSUE THREAD

**Issue by bastienu** [laravel/framework#36628]
- Laravel Version: 8.12
- PHP Version: 7.4.16

### Description:
_(I can't create an issue on laravel/Breeze repo, so I'm creating one here)_

I have installed laravel/Breeze by `composer require laravel/Breeze --dev` and then make a `php artisan Breeze:install`, as explained [in the documentation here](https://laravel.com/docs/8.x/starter-kits#laravel-Breeze).

But I had a lot of things already created in my application and this installation replace all the existing files Breeze use, for example :

- resources/views/layouts/app.blade.php, which contains the layout of my application, totally replaced by the Breeze layout ;
- routes/web.php, totally replaced by the routes/web.php of Breeze ;
- webpack.mix.js totally replaced ;
- resources/js/app.js, totally replaced by the Breeze file (with two lines) ;
- app/Providers/RouteServiceProvider.php, replaced also ;
- resources/views/welcome.blade.php, totally replaced ;
- etc.

Fortunately I have a Git repo for my project, so I can merge my files with the Breeze file, one by one, by using git diff.
But, is this normal? I have to admit that I'm a little angry after this. I did not read anywhere that this will happen and I did not see any warnings. I'm wasting my time here...

Thanks for your reply.

**Comment by driesvints** [comment]
Laravel breeze is intended for new apps only and not for existing apps

**Comment by bastienu** [comment]
There is no warning, **anywhere**, about this behavior. Something like: "Warning: do not install Breeze on an existing application!"

Losing your file is not something fair! I think the document must be updated with an alert about this.
This is why I created this issue.

**Comment by driesvints** [comment]
The Readme at the very top reads:

> Breeze provides a minimal and simple starting point for building a Laravel application

Further down you see:

> Laravel starter kit

It also says:

> Breeze publishes authentication controllers and views to your application

If anything is not clear to you then feel free to send in a pr 👍

**Comment by wpas81** [comment]
I agree with bastienu. We don't always start with the authentication-package. It should not replace stuff, only add/change. I started my app with Jetstream but couldn't customize it enough to my liking so I switched to breeze. Luckily I got backups. @bastienu  thanks for pointing out what's been changed.

**Comment by bastienu** [comment]
Thanks @wpas81 !

Please note that my PR for changing the documentation (and add an alert about the fact that it's replacing assets) was closed by @taylorotwell without any explanation... So I have the feeling that nothing is going to change :-(
