### ISSUE TITLE
ThrottlesExceptions method backoff method accepts seconds. But this is implicitly converted to minutes.

### ISSUE THREAD

**Issue by tairau** [laravel/framework#36637]
- Laravel Version: 8.33.1
- PHP Version: 8.0.2
- Database Driver & Version: psql v. 13

### Description:
Docblock [says](https://github.com/laravel/framework/blob/9c9f85896472511696b52561cfa372e2b3748fa7/src/Illuminate/Queue/Middleware/ThrottlesExceptions.php#L138):
> Specify the number of seconds a job should be delayed when it is released (before it has reached its max exceptions).

But here [here](https://github.com/laravel/framework/blob/9c9f85896472511696b52561cfa372e2b3748fa7/src/Illuminate/Queue/Middleware/ThrottlesExceptions.php#L40)
> The number of minutes to wait before retrying the job after an exception.

[And in the end it boils down to the fact that we indicate the minutes](https://github.com/laravel/framework/blob/9c9f85896472511696b52561cfa372e2b3748fa7/src/Illuminate/Queue/Middleware/ThrottlesExceptions.php#L107)

Where is the truth? I think seconds more useful here.

**Comment by driesvints** [comment]
You're correct, this should be minutes. Thanks for catching that.

https://github.com/laravel/framework/pull/36642
