### ISSUE TITLE
ShouldBeUnique doesn't work with event listeners

### ISSUE THREAD

**Issue by p4rse** [laravel/framework#36632]
- Laravel Version: 8.33.1
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.15

### Description:
Event listeners are always getting added to the queue even with the presence of `ShouldBeUnique` interface, and `uniqueId` and `uniqueFor` methods or properties.

I have done the same implementation for a `Job` and worked as expected.

### Steps To Reproduce:
1. Create a new event and its listener. (e.g: UserRegistered)
2. Register the event via the `EventServiceProvider $listen` array.
3. Add `ShouldBeUnique` to the event listener.
4. Add `uniqueId` and `uniqueFor` methods or properties.
5. The `uniqueId` value should be hardcoded (say: `123`) for the sake of this bug. 
5. Dispatch the event several times. (e.g: `UserRegistered::dispatch($userId)`)
6. Check the `jobs` table and you will see many rows of the same dispatched event.
7. When I tested it with a `Job`, it creates only 1 job in the `jobs` table, and also checked Redis cache and found that there's a `laravel_unique_job:App\\Jobs\\TestJob` key which goes away when I run the queue worker `php artisan queue:work`

Let me know if you need more details.

**Comment by driesvints** [comment]
`ShouldBeUnique` only works for queued jobs atm so this is more of a feature request. I'll ping the team internally to see if we could add it.

**Comment by priithansen** [comment]
Same is true for Notifications that can implement ShouldQueue but doesn't work with ShouldBeUnique which would be very convenient.

**Comment by ukenpachi** [comment]
> `ShouldBeUnique` only works for queued jobs atm so this is more of a feature request. I'll ping the team internally to see if we could add it.

Hi, I know this reply is more than a year old but I wanted to ask what do you mean by `only works for queued jobs`  but if I do something like this

```
class InventoryRecalculationJob implements ShouldQueue, ShouldBeUnique
{

 public function uniqueId() {
        return 123;
    }   

}
```
```
//controller
 public function test()
    {
        $x = 1;

        while($x <= 3) {
            $this->dispatch(new newJob());
            $x++;
        }
    }
    
     public function test2()
    {
        $x = 1;

        while($x <= 3) {
            $job = (new newJob())->onQueue('high');
            $this->dispatch($job);
            $x++;
        }
    }
```

In both cases it still create 3 of the same jobs. So how does this `shouldbeUnqiue `work? p.s. I am using version 8.2.3

**Comment by PDXfoster** [comment]
Was this "enhancement" ever addressed? It seems like if a listener implements the ShouldQueue interface, all the standard queueable interface options should be available, an error should be thrown when implemented on a component that isn't supported, or it should minimally be in the documentation that the shouldbeUnqiue interface doesn't work on listeners. 

I'm happy to submit a PR for an update to documentation, but won't spend the time if there's any intention of adding support for ShouldBeUnique inside listeners.

Thanks!

**Comment by sezohessen** [comment]
@driesvints any recommendation for solution ?
