### ISSUE TITLE
[8.x.] Nested Relationship Models Factory

### ISSUE THREAD

**Issue by uzkurama** [laravel/framework#36643]
I have 4 related models: Orders, OrderDetails, OrderMarkets, OrderInventories

Orders (hasMany) -> OrderDetails (belongsTo)
OrderDetails (belongsToMany) -> OrdersMarkets (pivot)
OrderDetails (belongsToMany) -> OrderInventories  (pivot)

Well, I made OrdersFactory, but I get an error, "order_details_id" haven't a default value" when I'm seeding.

```
class Orders extends Model
{
    use HasFactory;
    
    public function order_details(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(OrderDetails::class, 'orders_id', 'id')->orderBy('id');
    }
}

class OrderDetails extends Model
{
    use HasFactory;

    public function orders(): BelongsTo
    {
        return $this->belongsTo(Orders::class, 'id', 'orders_id')->with('clients', 'tm');
    }

    public function inventories(): BelongsToMany
    {
        return $this->belongsToMany(Inventory::class, 'orders_inventories', 'order_details_id', 'inventory_id');
    }

    public function markets(): BelongsToMany
    {
        return $this->belongsToMany(Markets::class, 'orders_markets', 'order_details_id', 'market_id');
    }
}

class OrdersSeeder extends Seeder
{
    public function run()
    {
        $inventory = Inventory::all()->random();
        $details = OrderDetails::factory();
        $markets = OrdersMarkets::factory()->count(2);
        $inventories = OrdersInventories::factory()->count(2);
        $orders = Orders::factory()
            ->has($details->count(2)
                ->hasAttached(
                    $inventories, ['inventory_id' => $inventory->id], 'inventories'
                )
                ->hasAttached(
                    $markets, ['market_id' => $inventory->market_id], 'markets'
                ), 'order_details'
            )
            ->count(10000)
            ->create();
    }
}
```

I read the documentation but didn't find information about the nested relationships, but I did all the by documentation.

Is this bug, or I did something wrong?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
