### ISSUE TITLE
phpdoc mismatch in Illuminate\Support\Facades\App.

### ISSUE THREAD

**Issue by mohamad-norouzi** [laravel/framework#36645]
- Laravel Framework Version: 8.33.0

### Description:
In the `src/Illuminate/Support/Facades/App.php` file, line `18`, phpdoc for `basePath` method, you forgot the `string $path = ''` argument. This causes IDE's to throw false errors during package development.

### Steps To Reproduce:
Calling `Illuminate\Support\Facades\App::basePath('something')` shows you that the method does accept an argument.

**Comment by driesvints** [comment]
feel free to send in a pr 👍
