### ISSUE TITLE
Http::fake() doesn't work if doesntExpectEvents() is called afterwards

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#36679]
- Laravel Version: 8.33.1
- PHP Version: 7.4.16
- Database Driver & Version: not relevant

### Description:
`Http::fake()` doesn't work if `$this->doesntExpectEvents` is called afterwards.

If `$this->doesntExpectEvents` is called before `Http::fake()` then everything works as expected.

### Steps To Reproduce:
The test below demonstrates the bug:
```php
/** @test */
function http_fake_not_working()
{
    Http::fake();

    $this->doesntExpectEvents([
        UserRegistered::class,
    ]);

    $response = Http::get('https://catfact.ninja/fact');

    // this fails because a real http request was made
    $this->assertSame('', $response->body());
}
```

**Comment by driesvints** [comment]
`doesntExpectEvents` is the old way of working with event mocking and it isn't documented anymore for that reason. If you use the new way things will work as you expect:

```php
    /** @test */
    public function http_fake_not_working()
    {
        Http::fake();
        Event::fake();

        $response = Http::get('https://catfact.ninja/fact');

        Event::assertNotDispatched(Registered::class);

        // this fails because a real http request was made
        $this->assertSame('', $response->body());
    }
```

**Comment by SjorsO** [comment]
@driesvints What do you think of marking these deprecated methods with a `@deprecated` phpdoc? If we do that, they'll show up like this in IDEs:
![image](https://user-images.githubusercontent.com/7202674/111968553-8c48c080-8af9-11eb-8d04-5a411ff5393e.png)

If this method was marked as deprecated it would have saved me a bunch of trouble.

**Comment by driesvints** [comment]
I'm not sure if Taylor wants that. I'll bring this up internally.
