### ISSUE TITLE
Eloquent builder "value" method with raw expression fails to pick the value

### ISSUE THREAD

**Issue by donnysim** [laravel/framework#36672]
- Laravel Version: 7.x/8.x
- PHP Version: 7.2/7.3
- Database Driver & Version:

### Description:
Trying to upgrade laravel from v6 to v7 encountered a bug in the eloquent query builder where the `value` method of the eloquent builder does not pick up the value from raw expression: `$query->value(DB::raw('COUNT(DISTINCT a.id)')`

https://github.com/laravel/framework/blob/72ea328b456ea570f8823c69f511583aa6234170/src/Illuminate/Database/Eloquent/Builder.php#L555

returns `id)` as the column to pick which is present in v7 and v8 of laravel. Based on the expression anything will fail such as `COUNT(DISTINCT a.id) AS id`  - returned as `id) AS id` etc.. Accessing it via direct query builder `$query->getBuilder()->value(DB::raw('COUNT(DISTINCT a.id)')` works as intended.
 
### Steps To Reproduce:

Have any eloquent query with raw expression such as `$query->value(DB::raw('COUNT(DISTINCT a.id)')`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by donnysim** [comment]
It is a bug and a breaking one at that, where in Laravel 6 everything works fine but on Laravel 7 and 8 it does not. It was updated without raw expressions in mind and now anything that is not in `table.column` or `column` format just plainly fails with returning a `null` value. If it is intended, then it is not documented in the breaking changes guide, though I highly doubt it is the case.
