### ISSUE TITLE
Function of controller got wrong injection when I use domain() in route files

### ISSUE THREAD

**Issue by boxshadow** [laravel/framework#36682]
- Laravel Version: 7.* latest
- PHP Version: 7.4.16
- Database Driver & Version: mysql 5.7.*

### Description:
when I use function domain like this:
```php
Route::domain('{account}.xxx.com')->group(function ($api) {
   $api->get('/users/{user}', [Controller::class, 'show']);
});
```
function in Controller
```php
public function show(User $user) {
 ...
}
```
if domain is **wook.xxx.com**

the **$user** in **show** function got string **wook** always.

Injected models will trigger this problem.

**Comment by sonja-turo** [comment]
Given your route, I suspect your show method has the wrong parameters. Try:
```
public function show($account, User $user) {
  ...
}
```

**Comment by boxshadow** [comment]
> Given your route, I suspect your show method has the wrong parameters. Try:
> 
> ```
> public function show($account, User $user) {
>   ...
> }
> ```
Thanks,
yes, It's correct like this, but must I inject $account in every function?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by boxshadow** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.
> 
> Thanks!

Laravel 8.5.14 has the same issue
![image](https://user-images.githubusercontent.com/8577474/111903676-70540900-8a7e-11eb-81f2-d9bbba35abe4.png)

```php
Route::domain('{account}.laravel.test')
    ->get('/users/{user}', [\App\Http\Controllers\UserController::class, 'show']);
```

UserController
```php
<?php
declare(strict_types=1);
namespace App\Http\Controllers;

use App\Models\User;

class UserController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        dd($user);
    }
}
```

and I change type for param $user to  string, the output value is the value of {account}

![image](https://user-images.githubusercontent.com/8577474/111903761-ccb72880-8a7e-11eb-9f57-b417fa808b9e.png)

**Comment by sonja-turo** [comment]
> > ```
> > public function show($account, User $user) {
> >   ...
> > }
> > ```
> 
> 
> Thanks,
> 
> yes, It's correct like this, but must I inject $account in every function?

Yes, because you have two parameters `{account}` and `{user}` in your url, so you need them in your controller as well, in that order.

if you want to avoid the account in your controller, I recommend dropping the domain method, and instead creating a middleware that looks up the domain instead and add the result to the request.

Stackoverflow may be a more appropriate place for this question as well: https://stackoverflow.com/questions/tagged/laravel

**Comment by boxshadow** [comment]
> > > ```
> > > public function show($account, User $user) {
> > >   ...
> > > }
> > > ```
> > 
> > 
> > Thanks,
> > yes, It's correct like this, but must I inject $account in every function?
> 
> Yes, because you have two parameters `{account}` and `{user}` in your url, so you need them in your controller as well, in that order.
> 
> if you want to avoid the account in your controller, I recommend dropping the domain method, and instead creating a middleware that looks up the domain instead and add the result to the request.
> 
> Stackoverflow may be a more appropriate place for this question as well: https://stackoverflow.com/questions/tagged/laravel

got it!
Thank you very much!
