### ISSUE TITLE
Str::pluralStudly with 0

### ISSUE THREAD

**Issue by tigrouuu** [laravel/framework#36692]
- Laravel Version: 8.33.1
- PHP Version: 7.4.9

### Description:

Hi everybody,

When i use `Str::pluralStudly('command', 0);`, the result is `commands`. There should be no "s" when there is 0 or 1 command.

### Steps To Reproduce:

`Str::pluralStudly('command', 0);` --> commands
`Str::pluralStudly('command', 1);` --> command
`Str::pluralStudly('command', 2);` --> commands

**Comment by u01jmg3** [comment]
0 commands is correct

https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun

**Comment by SjorsO** [comment]
In English, every number that is not 1 is considered plural. In your example, "0 commands" is correct English.
