### ISSUE TITLE
User-Agent does not work on HTTP Client.

### ISSUE THREAD

**Issue by jerodion** [laravel/framework#36695]
For example, the nominatim api requires a user-agent to be specific in the request.

This works:

    $url = 'https://nominatim.openstreetmap.org/search.php?q=' . urlencode($this->address) . '&polygon_geojson=1&format=json';
    $context = stream_context_create(['http' => ['header' => 'User-Agent: '. config('app.name') . ' ' . config('app.version')]]);
    $json = json_decode(file_get_contents($url, false, $context));

    $this->polygons =  $json[0]->geojson;

This does not work:

    $response = Http::withHeaders([
        'User-Agent' => config('app.name') . ' ' . config('app.version'),
    ])->get('https://nominatim.openstreetmap.org/search.php', [
        'q' => urlencode($this->address),
        'polygon_geojson' => true,
        'format' => 'json',
    ]);

    if ($response->ok()) {
        $this->polygons = $response->json('0.geojson');
    }

In the `file_get_contents` example, I receive the correct response.

In the HTTP client example, the body is empty every time.

**Comment by jerodion** [comment]
Doesn't work when using guzzle options either:

        $response = Http::withOptions([
            'headers' => ['User-Agent' => config('app.name') . ' ' . config('app.version')]
        ])->get('https://nominatim.openstreetmap.org/search.php', [
            'q' => urlencode($this->address),
            'polygon_geojson' => true,
            'format' => 'json',
        ]);

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jerodion** [comment]
@driesvints ???

I just posted a bug not a support request. What are you doing?
