### ISSUE TITLE
Revert AWS-SDK-PHP

### ISSUE THREAD

**Issue by JoeCianflone** [laravel/framework#36694]
There's a bug in the aws/aws-sdk-php that's breaking endpoints...I just hit this a moment ago after upgrading laravel to the latest: https://github.com/aws/aws-sdk-php/issues/2209 

Honestly, I'm not sure if this is Laravel that needs to revert or Flysystem or both

**Comment by ahinkle** [comment]
You can update your own application to use a version (such as 3.173.23) that's not causing the breaking bug.

https://github.com/laravel/framework/blob/213b58db3736ba99f856a5bbf030fa7084ec8aef/composer.json#L81

**Comment by driesvints** [comment]
See the above

**Comment by sebastiansulinski** [comment]
I was trying to figure it out whole day today 😓
