### ISSUE TITLE
Laravel is selecting from "information_schema" on every create() or updateOrCreate()

### ISSUE THREAD

**Issue by byGits** [laravel/framework#36706]
- Laravel Version: 8.33.1
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 5.7.x

### Description:
Every time I use eloquent to do a simple `create()` or `updateOrCreate()`,  Laravel performs an additional query...

**Example 1:**
Eloquent:
```
UserLog::create([... an array of all the required data ...]);
```
Executed Queries:
```
1. select column_name as `column_name` from information_schema.columns where table_schema = 'database_name' and table_name = 'user_logs'
2. insert into `user_logs` (...) values (...)
```

**Example 2:**

Eloquent:
```
$this->someRelationship()->updateOrCreate([
    // ...
],[
    // ...
]);
```
Executed Queries:
```
1. select * from `table` where (`user_id` = 1 and `type` = 'something' and `some_id` = '257') limit 1

// Again...
2. select column_name as `column_name` from information_schema.columns where table_schema = 'database' and table_name = 'table'

3. insert into `table` (`user_id`, `type`, `some_id`, `some_value`, `updated_at`, `created_at`) values (1, 'something', '257', 1, '2021-03-20 00:57:16', '2021-03-20 00:57:16')
```

**If the check is necessary, shouldn't it be cached at least?**

### Steps To Reproduce:

Just using `create()` or `updateOrCreate()` methods.

**Comment by driesvints** [comment]
That's part of the Eloquent's guard functionality to protect at unwanted input. Feel free to send in a PR to optimize this if you want 👍 

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L220-L222
