### ISSUE TITLE
assertSoftDeleted assertion passes incorrectly when database is SQLite

### ISSUE THREAD

**Issue by Rorymercer** [laravel/framework#36702]
- Laravel Version: 8.33.1
- PHP Version: 8.0.1
- Database Driver & Version: SQLite version 3.32.3

### Description:
When using SQLite as the database driver in the testing environment, the `assertSoftDeleted()` assertion passes incorrectly for models that do not even use soft deletes.  I wonder if this is related to [Quirk 10](https://www.sqlite.org/quirks.html#dubious_sql_is_allowed_without_any_error_or_warning) of SQLite where dubious sql is allowed without any error or warning.  It seems wrong that the assertion doesn't fail on this driver however.  

### Steps To Reproduce:

1. Fresh install of Laravel 8
2. Switch to SQLite for database testing in PHPUnit.xml
3. Add a test that asserts that a freshly created user should be soft deleted:

```
public function testSoftDeleteBehaviour()
    {
        $user = User::factory()->create();

        $this->assertSoftDeleted('users',['id'=>$user->id]); 
    }
```

The above test passes incorrectly on SQLite; fails as expected for MySql.

**Comment by driesvints** [comment]
I can't reproduce this. The test fails for me.
