### ISSUE TITLE
Issue sending mail with Mailgun

### ISSUE THREAD

**Issue by PFloyd1888** [laravel/framework#36714]
I'm posting this issue trying to make sense of a recent event.

I've been successfully sending mail via Mailgun for many years with the following code:

```
        try {
            Mail::to($sendTo)->bcc($users)->send($mail);
        } catch (Throwable $e) {
            $this->warn('Aborting ...' . $e->getMessage());
            return 1;
        }
```

I last did this on March 4, 2021 and it worked fine.  But on March 20, 2021, it didn't work fine.

I received this message:  **fwrite(): send of 6 bytes failed with errno=32 Broken pipe**.

After looking into this matter, I found this SwiftMailer issue.  

<img width="1370" alt="Screen Shot 2021-03-23 at 9 29 08 AM" src="https://user-images.githubusercontent.com/8575379/112158458-908ae180-8bbe-11eb-9a74-ceb5947d8911.png">

I am not sure if this contributed to my problem.  But it does appear that Mailgun deprecated something on March 8, 2021 that may affect SwiftMailer.

Is it possible this contributed to my issue?  Any help or advice to make my code work again is appreciated.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
