### ISSUE TITLE
RedisCluster::eval(): All keys do not map to the same slot

### ISSUE THREAD

**Issue by phuongdm1987** [laravel/framework#36711]
- Laravel Version: 8.3
- PHP Version: 8.0.1
- Database Driver & Version:

### Description:
I used redis-cluster to cache, session, queue, and horizon
I have a problem with the queue (send verify email)
![image](https://user-images.githubusercontent.com/3963180/112130094-acac7400-8bfa-11eb-858c-53458607ae76.png)

RedisCluster::eval(): All keys do not map to the same slot

### Steps To Reproduce:
- send verify email
$notification = new VerifyRegisteredUser();
        $notification
            ->locale(App::currentLocale())
            ->onQueue('emails');
        $this->notify($notification);
- Redis config
`'client' => env('REDIS_CLIENT', 'phpredis'),
        'options' => [
            'cluster' => 'redis',
            'password' => 'password',
            'persistent' => true,
            'timeout' => 1.5,
            'read_timeout' => 2,
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'clusters' => [
            'default' => [
                [
                    'host' => 'redis-cluster-1',
                    'port' => '6379',
                    'read_write_timeout' => 60,
                ],
                [
                    'host' => 'redis-cluster-2',
                    'port' => '6379',
                    'read_write_timeout' => 60,
                ],
                [
                    'host' => 'redis-cluster-3',
                    'port' => '6379',
                    'read_write_timeout' => 60,
                ],
            ],
        ],`

**Comment by driesvints** [comment]
Which Redis version are you running?

**Comment by phuongdm1987** [comment]
I used redis 6.0

**Comment by driesvints** [comment]
What exact version? And which version of the PHP extension?

**Comment by phuongdm1987** [comment]
do you mean the predis? I used predis/predis": "^1.1"

**Comment by driesvints** [comment]
Both Redis on your server and predis version. Check your composer.lock for Predis and run `redis-cli --version` to see what Redis version you're running.

**Comment by phuongdm1987** [comment]
redis-cli 6.0.9, predis v1.1.6

**Comment by driesvints** [comment]
I see you're not using the latest Laravel version. Can you update Laravel and Horizon to the latest versions and try again?

**Comment by phuongdm1987** [comment]
I updated laravel and horizon, but still had this error
"name": "laravel/horizon",
            "version": "v5.7.2",
"name": "laravel/framework",
            "version": "v8.33.1",

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new laravel-issue-36711 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by phuongdm1987** [comment]
I have tried to get example code https://laravel.com/docs/8.x/redis#transactions

```
$value = Redis::eval(<<<'LUA'
        local counter = redis.call("incr", KEYS[1])

        if counter > 5 then
        redis.call("incr", KEYS[2])
        end

        return counter
        LUA, 2, 'first-counter', 'second-counter');
```

But still error:
`RedisCluster::eval(): All keys do not map to the same slot`

**Comment by phuongdm1987** [comment]
In queue config, I change queue name:
'driver' => 'redis',
'connection' => 'default',
'queue' => '{default}',

It work without horizon.
As I see in https://github.com/laravel/horizon/issues/274, the horizon did not work with redis cluster

**Comment by driesvints** [comment]
Please create a repo that reproduces the issue
