### ISSUE TITLE
Laravel RouteServiceProviders routes namespace is not set to null

### ISSUE THREAD

**Issue by nmp4817** [laravel/framework#36721]
- Laravel Version: 8.x
- PHP Version: 7.2
- Database Driver & Version:

### Description:
I installed Laravel using this instruction https://laravel.com/docs/8.x/installation#installation-via-composer
And was trying to use this https://laravel.com/docs/8.x/controllers#api-resource-routes
Was constantly getting BindingResolutionException

After digging deeper it seems `$namespace` inside `RouteServiceProvider` supposed to be set to null.
https://laravel.com/docs/8.x/upgrade#routing

Took me an hour to figure out, can you update `RouteServiceProvider` so by default it's set to null.

### Steps To Reproduce:
- install Laravel 8.x
- add `apiResource` in `api.php` for some API controller
- try to access that route
- will see an exception

<img width="1439" alt="Screen Shot 2021-03-23 at 12 56 30 PM" src="https://user-images.githubusercontent.com/17420461/112195770-52022080-8bd8-11eb-9c4c-9316ef8b68ec.png">

**Comment by rodrigopedra** [comment]
Just tried and it worked.

~~~bash
$ composer create-project laravel/laravel example
$ cd example
$ php artisan make:controller TestController --api
~~~

Changed `./routes/api.php` to:

~~~php
<?php

use Illuminate\Support\Facades\Route;

Route::apiResource('users', \App\Http\Controllers\TestController::class);
~~~

Start server

~~~bash
$ php artisan serve
~~~

Open other terminal

~~~bash
$ curl -o /dev/null -s -w "%{http_code}\n" http://127.0.0.1:8000/api/users
200
~~~

**Comment by nmp4817** [comment]
@rodrigopedra can you please share your `RouteServiceProvvider.php` here.
What is the `$namespace` in it?

**Comment by rodrigopedra** [comment]
Well, I deleted the project just after posting, as I created it for testing this only.

But, as I created it from composer, it should have been the same as the laravel/laravel repo:

https://github.com/laravel/laravel/blob/6bc0b1cfcbc35d89b3e4ec31d83d7b409f9bf595/app/Providers/RouteServiceProvider.php

Github says last change to this was 5 months ago, so it has been a while this line is commented out by default:

https://github.com/laravel/laravel/blob/6bc0b1cfcbc35d89b3e4ec31d83d7b409f9bf595/app/Providers/RouteServiceProvider.php#L29

**Comment by nmp4817** [comment]
@rodrigopedra Thanks I appreciate your response

Intriguing though because when I did follow the same steps my project's `RouteServiceProvider` had `$namespace` uncommented
