### ISSUE TITLE
Illuminate\Queue\SerializesAndRestoresModelIdentifiers redoes relationship query without its closure

### ISSUE THREAD

**Issue by ipontt** [laravel/framework#36735]
- Laravel Version: 8.32.1
- PHP Version: 7.4.11
- Database Driver & Version: psql (PostgreSQL 10)

### Description:
Loading a relationship with extra conditions attached inside the constructor of a job class doesn't seem to work correctly. When dumping the data inside the constructor and the inside the handle method, the same variable shows two different results.

Using the sync Queue driver, I made a route to dispatch this job and check the results in the browser. The dumped results are different.

### Steps To Reproduce:

Set queue driver to sync.
Make a job that accepts a model.
Make a route that dispatches the job. 
Cehck browser.

Job class:
```php
class SomeJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected User $user;

    public function __construct(User $user)
    {
        // load children (user hasMany children) relationship where field = 3
        $this->user = tap($user)->load([
            'children' => function ($children) {
                $children->where('field', 3);
            }
        ]);

        dump($this->user->children->toArray()); // dump shows ONLY related children with field = 3
    }

    public function handle()
    {
        dump($this->user->children->toArray()); // dump shows ALL related children regardless of field.
    }
}
```

According to laravel debugbar, the relationship query is repeated inside `\vendor\laravel\framework\src\Illuminate\Queue\SerializesAndRestoresModelIdentifiers.php:102` but without the Closure. Here's a copy of what I see in my bar.
|query|location|
|-|-|
|select * from "users" where "users"."id" = 6 and "users"."deleted_at" is null limit 1|\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:23|
|select * from "children" where "children"."usuario_id" in (6) and "field" = 3 and "children"."deleted_at" is null|\app\Jobs\SomeJob.php:30|
|select * from "users" where "users"."id" = 6 limit 1|\vendor\laravel\framework\src\Illuminate\Queue\SerializesAndRestoresModelIdentifiers.php:102|
|select * from "children" where "children"."usuario_id" in (6) and "children"."deleted_at" is null|\vendor\laravel\framework\src\Illuminate\Queue\SerializesAndRestoresModelIdentifiers.php:102|

**Comment by crynobone** [comment]
This would be a hard problem to fix:

* When we serialize the model, we no longer have any knowledge of relationship custom constraints, so it can be replicated on restores.
* Storing related model ids would be fine in some cases (low relation count), but what if you are loading large number of ids which would require more data to be stored as payloads.

**Comment by driesvints** [comment]
I don't think you should do these things inside a constructor. A constructor is for property assignment and basic data processing. Anything that hits outside of the object like a database query doesn't belongs in a constructor.

**Comment by ipontt** [comment]
> This would be a hard problem to fix:
> 
> * When we serialize the model, we no longer have any knowledge of relationship custom constraints, so it can't be replicated on restores.
> * Storing related model ids would be fine in some cases (low relation count), but what if you are loading a large number of ids which would require more data to be stored as payloads.
> * If payloads become too large, job might failed to be created and cause more issues.

Thanks for the explanation. I wasn't sure if it was intended behavior or not.
