### ISSUE TITLE
Resource controller create with artisan make:controller create not working parameter name

### ISSUE THREAD

**Issue by rabol** [laravel/framework#36739]
- Laravel Version: 8.34.0
- PHP Version: 8.0.1
- Database Driver & Version:

### Description:
Using the php artisan make:controller to create a resource controller generate a controller with wrong parameter names  

### Steps To Reproduce:

```
php artisan make:controller Family/FamilyMemberPlanSettingController -r --model FamilyMemberPlanSetting
```

Generate the this:
```
/**
     * Display the specified resource.
     *
     * @param  \App\Models\FamilyMemberPlanSetting  $familyMemberPlanSetting
     * @return \Illuminate\Http\Response
     */
    public function show(FamilyMemberPlanSetting $familyMemberPlanSetting)
    {
        //

        dd($familyMemberPlanSetting);
    }
```

in web.php

```
Route::resource('member-plan-setting',\App\Http\Controllers\Family\FamilyMemberPlanSettingController::class);
```

the routes will then look like this:

```
family/member-plan-setting/{member_plan_setting} 
```

Notice the difference in the route parameter and the method in the controller
The result is that $familyMemberPlanSetting is just a empty object and not a initialised object due to the name difference

**Comment by driesvints** [comment]
The `make:controller` doesn't generates routes. You need to implement the full parameter name into your resource route. If you change it to the one below with the `family-` prefix it'll work:

```php
Route::resource('family-member-plan-setting',\App\Http\Controllers\Family\FamilyMemberPlanSettingController::class);
```

**Comment by rabol** [comment]
Aha.... Thanks
Took me a while and a few readings before I understood the relation.
Maybe add a 'Tip' in the doc ?
