### ISSUE TITLE
Potential issues with migrating `cursor()` or `chunk()` to `lazy()`

### ISSUE THREAD

**Issue by crynobone** [laravel/framework#36742]
- Laravel Version: 8.34.0
- PHP Version: 7.4+
- Database Driver & Version: all

### Description:

Based on the documentation, `lazy()` tries to solve `chunk()` and `cursor()` limitation. However it uses pagination query mimicking `chunkById()`. This worked find for new code however when you migrating from `cursor()` or `chunk()` where you already using `latest()`, `oldest()` or `orderBy()` will see `lazy()` will skipped rows.

### Steps To Reproduce:

Imagine you have 5000 users.

```php
User::latest()->cursor()->each->touch();
```
and change it to

```php
User::latest()->lazy(1000)->each->touch();
```

The generated SQL would be:

```sql
# FIrst SQL
SELECT * FROM users ORDER BY id DESC LIMIT 1000;

# Second SQL
SELECT * FROM users WHERE id>4000 ORDER BY id LIMIT 1000;
```

### Possible Solutions:

I would suggest when doing query using `lazy()` and `lazyForId()` we should reset any registered `orders`.

```php
if ($this instanceof \Illuminate\Database\Eloquent\Builder) {
    $this->getQuery()->orders = [];
} else {
    $this->orders = [];
}
```

**Comment by driesvints** [comment]
@JosephSilber do you have any ideas here?

**Comment by JosephSilber** [comment]
> However it uses pagination query mimicking `chunkById()`.

Only `lazyById` does. [The regular `lazy` method runs the same queries as the `chunk` method](https://github.com/laravel/framework/blob/f75e51084689330ba59ae09d1dd50ab507b10555/src/Illuminate/Database/Concerns/BuildsQueries.php#L182).

> ```php
> # Second SQL
> SELECT * FROM users WHERE id>4000 ORDER BY id LIMIT 1000;
> ```

Are you sure you're getting that from `lazy`, and not `lazyById`?

**Comment by crynobone** [comment]
@JosephSilber you're right, must been mixed in trying to figure out why code wasn't working locally made me conclude this wrongly.
