### ISSUE TITLE
WithoutOverlapping queue middleware do not delete job from queue with dontRelease

### ISSUE THREAD

**Issue by dkulyk** [laravel/framework#36745]
- Laravel Version: 8.33.1
- PHP Version: 8.0.1
- Database Driver & Version: -

### Description:
When job executing is locked by other job WithoutOverlapping don't delete job from queue and job try to run again after 60(backoff) seconds.

### Steps To Reproduce:
```php
    public function middleware(): array
    {
        return [
            (new WithoutOverlapping)
                ->expireAfter(60 * 5)
                ->dontRelease(),
        ];
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
