### ISSUE TITLE
InteractsWithQueue::fail() breaks when used with Dispatchable::dispatchNow()

### ISSUE THREAD

**Issue by axlon** [laravel/framework#36740]
- Laravel Version: 8.32.1
- PHP Version: 7.4.14
- Database Driver & Version: n/a

### Description:
When dispatching a job synchronously via the `dispatchNow()` method, the framework will throw an error if `$this->fail()` is called from within that job.

This seems to happen because when dispatchNow is called a sync job instance is attached with an empty payload, when the framework attempts to run the `failed` method on the job it tries to read the job payload and breaks with the following error:

```
ErrorException: Undefined index: job
```

### Steps To Reproduce:
- Create a job with `$this->fail()` in the handle method, it doesn't matter if you pass an exception to the fail method or not
- Dispatch the job synchronously via `MyJob::dispatchNow()`

### Workaround
Right now a simple workaround is to throw the exception instead of calling `fail()`, however with `dispatchNow()` specifically this will cause the job's `failed($e)` method to not be called.

**Comment by driesvints** [comment]
Thanks for reporting. I've sent in a PR for this: https://github.com/laravel/framework/pull/36743

**Comment by driesvints** [comment]
See https://github.com/laravel/framework/pull/36743#issuecomment-811107049
