### ISSUE TITLE
Mailable : Trying to get property 'email' of non-object

### ISSUE THREAD

**Issue by benjaminbra** [laravel/framework#36754]
- Laravel Version: 8.34.0
- PHP Version: 7.3.27
- Database Driver & Version: N/A

### Description:

I discovered an issue when my Laravel website was in production.
When i try to submit an email, the following error message appears :  `Trying to get property 'email' of non-object`
and this happens at : [`vendor/laravel/framework/src/Illuminate/Mail/Mailable.php:621`](https://github.com/laravel/framework/blob/f75e51084689330ba59ae09d1dd50ab507b10555/src/Illuminate/Mail/Mailable.php#L621)
Here is my code (simplified to mainly show the part where i send the email) :

```php
use Illuminate\Support\Facades\Mail;
use Illuminate\Http\Request;

public function sendRegister(Request $request){
    $inputs = $request->all();

    $user = new User();
    $user->email = $inputs['email'];
    $user->save();

    Mail::to($user->email)->send(new EmailConfirmation($user->name);

    return redirect('/');
}
```

And my EmailConfirmation class : 

```php
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class EmailConfirmation extends Mailable
{
    use Queueable, SerializesModels;

    public $username;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($username)
    {
        $this->username = $username;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->from(env('mail_from_address'), env('mail_from_name'))->subject(__('potat0s.email.confirmation'))->view('emails.confirm');
    }
}
```

### Possible fix:
When i was debugging the issue, i found out that sometimes `$recipient` was NULL.

So in `Illuminate\Mail\Mailable.php` lines `619-622`. It would be a good idea to check if `$recipient` is null.
Maybe like this : 

```php
protected function setAddress($address, $name = null, $property = 'to')
{
    foreach ($this->addressesToArray($address, $name) as $recipient) {
        $recipient = $this->normalizeRecipient($recipient);

        if(!empty($recipient)){
            $this->{$property}[] = [
                'name' => $recipient->name ?? null,
                'address' => $recipient->email,
            ];
        }
    }

    return $this;
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by benjaminbra** [comment]
hi @driesvints 
It actually concerns the library itself, since the anomaly occurs on Mailable.php.
