### ISSUE TITLE
Eloquent: touching owners on delete and Scout indexing

### ISSUE THREAD

**Issue by janpantel** [laravel/framework#36752]
This issue is about this line: https://github.com/laravel/framework/blob/f75e51084689330ba59ae09d1dd50ab507b10555/src/Illuminate/Database/Eloquent/Model.php#L1124

Imagine the following scenario, we have 2 models `Post` and `Comment`:

```php
class Post extends Model
{
    use Searchable;

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
    
    public function shouldBeSearchable()
    {
        return $this->comments()->exists();
    }
}

class Comment extends Model
{
    protected $touches = ['post'];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}
```

Since we only want posts to be indexed in case they have comments, we also want them to be removed from the index if we delete their last comment.

The problem at hand is that the touch happens before the actual delete. This will make the `Post` model events fire before the `Comment` is removed from the database and therefore the `->exists()` call will return `true` which will make Scout not remove the `Post` from the index.

A workaround is to add the following to the `Comment` model, yet this will make us touch parents twice and add another round trip to the database.
```php
protected static function booted()
{
    self::deleted(fn (Comment $comment) => $comment->touchOwners());
}
```

I'm not sure if there is a strong reason why the touch happens before the delete and therefore wanted to draft an issue before changing it in in a PR.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
