### ISSUE TITLE
Documentation does not describe case for returning null for Model:delete();

### ISSUE THREAD

**Issue by SaxJ** [laravel/framework#36759]
https://github.com/laravel/framework/blob/f75e51084689330ba59ae09d1dd50ab507b10555/src/Illuminate/Database/Eloquent/Model.php#L1102

The documentation for the Model:delete() method does not describe the case in which it would return null. Since the method returns bool|null, it's not clear why null would be returned without looking at the source.

See documentation: https://laravel.com/api/master/Illuminate/Database/Eloquent/Model.html#method_delete

**Comment by driesvints** [comment]
Feel free to send in a pr 👍
