### ISSUE TITLE
Translator should use fallback.json

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#36760]
- Laravel Version: 8.27
- PHP Version: 8.0
- Database Driver & Version: Mysql 8.0

### Description:

According to documentation, you can define `<locale>.json` instead of a bunch of `*.php` files, this is really cool feature for real applications where strings translate by non-developers. Unfortunately, `Translator` doesn't load `<fallback>.json` it trying to find string in `*.php` instead. So you must sync `<locale>.json` **and** a bunch of `*.php` files 😥 

### Steps To Reproduce:

1) Create `/storage/lang/en.json: {"string": "translated"}`  
2) Create `/storage/lang/ru.json: {}`
3) `app()->setLocale('ru');`
4) `__('string')`  

### Actual result:

```
string
```

### Expected result

```
translated
```

**Comment by driesvints** [comment]
This is intended. The behavior for JSON translation is that the string *is* the fallback itself. Therefor it cannot make use of the fallback locale.

From the docs: https://laravel.com/docs/8.x/localization#retrieving-translation-strings

> Again, if the translation string does not exist, the __ function will return the translation string key that it was given.

**Comment by LastDragon-ru** [comment]
> Again, if the translation string does not exist, the __ function will return the translation string key that it was given.

@driesvints this is not true! the translator will use value from `*.php` file.

**Comment by driesvints** [comment]
How is it suppose to return a value from a php file when it's not dot separated? How is your fallback locale file named and what are its contents?

**Comment by LastDragon-ru** [comment]
@driesvints we use "dot separated" strings and they also work well with json, except this issue  

Current structure:

0) Standard files in `resources/lang/en` (but they are not used at all and needed only to track changes between Laravel updates)

1) `resources/lang/en.json`

```json
{
    "validation.accepted":"The :attribute must be accepted.",
    "validation.somethingnew":"The :attribute must be a bla bla bla."
}
```

2) `resources/lang/fr.json`

{
    "validation.accepted": "Le champ :attribute doit être accepté.",
}
```

3) `app()->setLocale('fr')`

4) `__('validation.accepted')` -> `Le champ :attribute doit être accepté.` (from `fr.json`)

5) `__('validation.active_url')` -> `The :attribute is not a valid URL.` (fallback from `*.php`)

6) `__('validation.somethingnew')` -> `validation.somethingnew` -> no fallback but should be `The :attribute must be a bla bla bla.`

**Comment by driesvints** [comment]
This is the expected behavior. It'll find the fallback in the language file.

**Comment by LastDragon-ru** [comment]
> This is the expected behavior.

This is very weird behavior :(

**Comment by cioroianudenis** [comment]
@LastDragon-ru indeed it is very confusing, Taylor should fix this, or at least explain is properly in the docs.
