### ISSUE TITLE
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Bluesky97** [laravel/framework#36767]
- Laravel Version: Laravel Framework version 4.2.22
- PHP Version: 5.6
- Database Driver & Version:
        Server: Localhost via UNIX socket
        Server type: MariaDB
        Server connection: SSL is not being used Documentation
        Server version: 10.3.28-MariaDB - MariaDB Server
        Protocol version: 10
        User: cpses_u7tbaykp9v@localhost
        Server charset: cp1252 West European (latin1)

### Description:
When I tried to load pages that includes to show or retrieve the values from GET (API), it returns Failed to load resource: net::ERR_TOO_MANY_REDIRECTS after that, I pressed F12 and show console. 

show this error message
/api/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS

### Steps To Reproduce:
1. Open the web page inventory.terantrindotama.com
2. Enter username: superadmin and password: qwerty123
3. Click Login
4. Open Transactions or Perusahaan (Company) in side bar menu and the data would not loaded (pressed f12 to check with the error message)
5. Show error message /api/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS will shown in console log

index.php --> <?php header('Location: public/'); (outside of the laravel apps)
index.php (inside public folder)
require __DIR__.'/../bootstrap/autoload.php';
$app = require_once __DIR__.'/../bootstrap/start.php';

htaccess
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

I hope from this statement you would find the solution for me to fix the issues.

Thank you

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
