### ISSUE TITLE
Http facade doesn't wrap Guzzle's RequestException

### ISSUE THREAD

**Issue by AdirYad** [laravel/framework#36763]
- Laravel Version: 8.30.1
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0.23

### Description:
When I use Laravel's `Http` facade, I expect it to wrap any exception that Guzzle throws.
There's Laravel's exception: `Illuminate\Http\Client\RequestException`
And Guzzle's exception: `GuzzleHttp\Exception\RequestException`

In my code, I catch only Laravel's exception, and for some reason, a Guzzle's exception is thrown, I wasn't prepared for it and I believe it's not the intended behavior.

I'm using a proxy for HTTP, sometimes it fails and causes this exception to be thrown.

### Steps To Reproduce:

```php
try {
  Http::withOptions([
     'proxy' => config('app.proxy_url')
  ])->get('https://example.com/users')->throw();
} catch (Illuminate\Http\Client\RequestException $exception) {
  Log::error('Exception caught', ['message' => $exception->getMessage()]);
} catch (GuzzleHttp\Exception\RequestException $exception) {
  // For some reason this exception is throws instead of Laravel's exception
}
```

```
GuzzleHttp\Exception\RequestException
cURL error 56: Received HTTP code 502 from proxy after CONNECT (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://example.com
```

![image](https://user-images.githubusercontent.com/45428455/112613616-5aa16380-8e31-11eb-9725-6d23477584a2.png)

Is that the intended behavior? `Http` wraps Guzzle, I personally expect it to convert Guzzle's exceptions to Laravel's ones.

**Comment by driesvints** [comment]
I get the laravel exception with your exact piece of code.

**Comment by AdirYad** [comment]
> I get the laravel exception with your exact piece of code.
Are you sure that Laravel converts 100% guzzle exceptions into Laravel exceptions, did you check my stack trace?
I have this exception once to a few minutes using proxies, when I remove the proxies it works fine.

**Comment by driesvints** [comment]
If you can someone share the exact code to reproduce this I'll try again 👍

**Comment by AdirYad** [comment]
> If you can someone share the exact code to reproduce this I'll try again
You can see my example code above.

**Comment by driesvints** [comment]
@AdirYad I can't reproduce it with your code.
