### ISSUE TITLE
queue:restart does not clear cached values for Job queue name and timeout

### ISSUE THREAD

**Issue by ibnIrshad** [laravel/framework#36774]
- Laravel Version: 8.31.0
- PHP Version: 7.4.12
- Database Driver & Version: pgsql (database queue driver)

### Description:

I've noticed that if I deploy new code to production which changes the queue name for a job, or changes other Job metadata like timeout values, the production queue workers don't actually pick up these changes until I clear the cache (`php artisan cache:clear`).

So clearly doing `queue:restart` is not enough. `queue:restart` should clear cached values for Job metadata. I'm using the database queue driver.

If someone can show me where the queue metadata is cached I can write a PR to fix this myself.

### Steps To Reproduce:

1. Create a job and set `$this->queue = 'foo'` in the Job constructor
2. Deploy to production and start some workers
3. Change to `$this->queue = 'bar'` and deploy again
4. Run `queue:restart`
5. Workers still think the job should be on queue `foo`

**Comment by taylorotwell** [comment]
Yeah - just doesn't work that way. The job is already in the queue.
