### ISSUE TITLE
Tagged Caches `getMultiple` method does not work correctly

### ISSUE THREAD

**Issue by anik786** [laravel/framework#36778]
- Laravel Version: 8.34.0
- PHP Version: 7.3.21
- Database Driver & Version: N/A

### Description:
The `getMultiple` method does not work correctly for tagged caches.

### Steps To Reproduce:

```
Cache::tags(['foo'])->put('a', 5)
Cache::tags(['foo'])->put('b', 10)
Cache::tags(['foo'])->put('c', 20)
```

The following:
```
Cache::tags(['foo'])->getMultiple(['a', 'b', 'c', 'x']);
```

Should return:
```
[
   'a' => 5,
   'b' => 10,
   'c' => 20,
   'x' => null
]
```

But instead returns:

```
[
     "" => null,
]
```

### Fix
I'm in the process of submitting a PR that fixes this issue.

**Comment by driesvints** [comment]
Confirmed this.
