### ISSUE TITLE
Unable to dispatch an event with halt option

### ISSUE THREAD

**Issue by erisrayanesh** [laravel/framework#36789]
Hi.
Is there a way to use the `halt` option of `dispatch` method from `Illuminate\Foundation\Events\Dispatchable` trait? As you definitely know this trait will be used in event classes
https://github.com/laravel/framework/blob/90fbaa7ec53410508cd73c09e3f788e458dd8b92/src/Illuminate/Events/Dispatcher.php#L221

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by erisrayanesh** [comment]
@driesvints I know. Off course it is a question but it doesn't mean it can not be a bug or NFR. I googled for solutions or workaround but nothing found.

A quick answer could be: **There is no way to do it**.

However stopping event propagation is available by returning false value from `handle` method of listener but if `halt = true` then the `dispatch` method stops propagation and returns the listener's response if it is not null.

The problem is that this option is not available through the `dispatch` method of `Illuminate\Foundation\Events\Dispatchable` trait
