### ISSUE TITLE
Nested Route Parameters Not Being Modified From Routes

### ISSUE THREAD

**Issue by JeffreyDavidson** [laravel/framework#36804]
- Laravel Version: 8.34.0
- PHP Version: 8.0.3
- Database Driver & Version: none 

### Description:

When working with nested resources it is possible for a developer to want to change the name of one or more of the parameters in the URI. 

From inside of my `web.php` routes file I have a route ressource that points to CourseSectionsController that uses a parent route resource called `course`.

`Route::resource('courses', CoursesController::class);
    Route::resource('courses.course-sections', CourseSectionsController::class)->parameters(['course_section' => 'section']);`

### Steps To Reproduce:

When I run `php artisan route:list` it gives me the following uris. I'm only including one to show both parameters.

`GET|HEAD  | courses/{course}/course-sections/{course_section}      | courses.course-sections.show     | App\Http\Controllers\CourseSectionsController@show `

**Comment by flaviosilveira** [comment]
@JeffreyDavidson Try this:
```php
Route::resource('courses.course-sections', CourseSectionsController::class)->parameters(
    ['course-sections' => 'section']
);
```

The `parameters` method expects an associative array where the index should match exactly the resource name. Since you declared your resource as `'courses.course-sections'` you should use `'course-sections'` as the key.

**Comment by JeffreyDavidson** [comment]
That does solve my problem. Thank you for your help.
