### ISSUE TITLE
method not calling laravel 5.1 to laravel 8.* upgrade

### ISSUE THREAD

**Issue by astutesixface** [laravel/framework#36809]
- Laravel Version: 8.*
- PHP Version: 7.*
- Database Driver & Version:

### Description:
I need some clarification with dynamic controller method i upgrading the laravel 5.1 to 8.*, all is done, but only one bug, my url is admin/admin-profile in 5.1 is working fine, but laravel 8 is not working 404 page error is showing. this url will call method getAdminProfile(){ } but is not calling. if this functionality is not available in laravel 8, then how can i manage this, if single url i will create route, but my application have more than 100 url like this, so please help me to solve this... i was check this issues by compare all file both laravel 5.1 and laravel 8 missing one file to capture the like this problem from ControllerInspector from routing folder. so please help to solve this.. i can't write each method in web.php

Route::controller('admin', 'AdminController');
class AdminController extends BaseController {

    public function getIndex()
    {
        //
    }

    public function getAdminProfile()
    {
        //
    }

    public function anyLogin()
    {
        //
    }

}

**Comment by myckhel** [comment]
If you can share the content of your `web.php` we could be able to spot out some issues.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
