### ISSUE TITLE
Migrations creates a nullable timestamps using the method timestamps()

### ISSUE THREAD

**Issue by fabiiomiiguel** [laravel/framework#36805]
- Laravel Version: 8.12
- PHP Version: 8.0
- Database Driver & Version: Mysql 8.0

### Description:

The `timestamps()` of migrations creates a nullable **created_at** and **updated_at** and that should only occur with `nullableTimestamps()` as you can see on next print screen of dbeaver.

![image](https://user-images.githubusercontent.com/27894544/112890669-0adfc800-90cf-11eb-8b03-d0efbddeafcc.png)

The problem it is on `Illuminate\Database\Schema\Blueprint` like you can see on the next picture.

![image](https://user-images.githubusercontent.com/27894544/112890291-9a38ab80-90ce-11eb-9a55-fdbb2f16114c.png)

**Comment by sonja-turo** [comment]
I don't think this is a bug (as the behaviour isn't broken as such). But I can kind of see that it is confusing, as having "nullableTimestamps" seems to suggest there is an option where timestamps are not nullable, which is not the case.

I don't think this will be fixed, however, as from what I can tell, these nullable timestamps are fairly ingrained into Eloquent and having them potentially non-nullable would probably be a breaking change.

**Comment by driesvints** [comment]
I don't see a bug here.
