### ISSUE TITLE
Upgrade 8.34 to 8.35 DynamoDB from EC2 Role Errors

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/framework#36819]
- Laravel Version: 8.35.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL 5.7

### Description: After upgrade Laravel Framework to 8.35 with composer update i receive this errors
Credentials must be an instance of Aws\Credentials\CredentialsInterface, an associative array that contains "key", "secret", and an optional "token" key-value pairs, a credentials provider function, or false.

### Steps To Reproduce: If return version 8.34 is normal, my application not have problem...

![schermata](https://user-images.githubusercontent.com/5731295/113031533-7455ea00-9154-11eb-83c1-033139b0dd22.jpg)

**Comment by driesvints** [comment]
We'll need a lot more info here. Please share how you're using dynamodb and what your database config file looks like.

**Comment by massimodellarovere** [comment]
```
aws/aws-sdk-php                  3.176.4   AWS SDK for PHP - Use Amazon Web Services in your P...
aws/aws-sdk-php-laravel          3.6.0   A simple Laravel 5/6/7/8 service provider for inclu...
league/flysystem-aws-s3-v3   1.0.29   Flysystem adapter for the AWS S3 SDK v3.x
```

**Comment by driesvints** [comment]
I see the issue now. I'll send in a fix for this. Sorry this has caused your troubles.

**Comment by driesvints** [comment]
https://github.com/laravel/framework/pull/36822
