### ISSUE TITLE
Components: The ")" character, this may cause an error

### ISSUE THREAD

**Issue by mxgrim** [laravel/framework#36815]
- Laravel Version: 8.34.0
- PHP Version: 7.4.16
- Database Driver & Version: -

### Description:
If you use the ")" character in a declared attribute of a component, this will result in an error:
_ParseError
syntax error, unexpected .._

### Steps To Reproduce:
**Declare an attribute on a component:**
`public function __construct($title = '')`

**Run from any .blade.php:**
`<x-forms.input title="test test )"/>`

**Comment by selcukcukur** [comment]
Can you share all the codes you use exactly because I have not encountered such a problem, you may be making a mistake while using it. @mxgrim

**Comment by selcukcukur** [comment]
I think this is a problem caused by a user error. I applied the necessary tests, but I did not encounter the same error. @driesvints

**Comment by mxgrim** [comment]
**app/View/Components/Forms/Test.php**

```
<?php

namespace App\View\Components\Forms;

use Illuminate\View\Component;

class Test extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($test = '')
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.forms.test');
    }
}

```

**resourses/views/components/forms/test.blade.php**

```
<div>
    test
</div>
```

**resourses/views/index.blade.php**

`<x-forms.test test=")"/>`

----

**Error:**

_ParseError
syntax error, unexpected 'forms' (T_STRING), expecting ']'_

**Compiled file (storage/framework/views/...):**

```
<?php if (isset($component)) { $__componentOriginal40e62d942e0a3dbd05627ad21d1c6a1a4a3b111f = $component; } ?>
<?php $component = $__env->getContainer()->make(App\View\Components\Forms\Test::class, ['test' => '); ?>
<?php $component->withName('forms.test'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>'])
<?php $component->withAttributes([]); ?>
<?php if (isset($__componentOriginal40e62d942e0a3dbd05627ad21d1c6a1a4a3b111f)): ?>
<?php $component = $__componentOriginal40e62d942e0a3dbd05627ad21d1c6a1a4a3b111f; ?>
<?php unset($__componentOriginal40e62d942e0a3dbd05627ad21d1c6a1a4a3b111f); ?>
<?php endif; ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
```

**The problem is here:**
**`make(App\View\Components\Forms\Test::class, ['test' => '); ?>`**

**Comment by selcukcukur** [comment]
https://github.com/laravel/framework/blob/d118c0df39e7524131176aaf76493eae63a8a602/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php#L23

The problem is here. I'm sending a pull request.

**Comment by driesvints** [comment]
I've tracked it down to `compileStatements` in `BladeCompiler`  which incorrectly removes the `'])` part at the end. Currently trying to see if I can adjust the regex.

**Comment by driesvints** [comment]
Here's a PR with a failing test: https://github.com/laravel/framework/pull/36843
