### ISSUE TITLE
Fix PHP 8.1 build failures

### ISSUE THREAD

**Issue by driesvints** [laravel/framework#36813]
We have a working PHP 8.1 build now on the 8.x branch but there are still quite a few build failures which we should try to fix.

https://www.stitcher.io/blog/new-in-php-81

**Comment by bogdankharchenko** [comment]
@driesvints examples?

**Comment by driesvints** [comment]
Sorry I should have linked to a failing build. See here: https://github.com/laravel/framework/runs/2247074654

Basically you can inspect the "Execute tests" step of the PHP 8.1 build on the 8.x branch.

**Comment by bogdankharchenko** [comment]
@driesvints thanks, I'll PR some of these

**Comment by jrmajor** [comment]
> Integers and floats in result sets will now be returned using native PHP types instead of strings when using emulated prepared statements. This matches the behavior of native prepared statements. You can restore the previous behavior by enabling the PDO::ATTR_STRINGIFY_FETCHES option.

https://github.com/php/php-src/blob/96fe8141c397518e4ee10e65a7b921d779d332b6/UPGRADING#L117-L126

DatabaseEloquentBelongsToManySyncReturnValueTypeTest::testSyncReturnValueType()
testSyncWithPivotDefaultsReturnValueType
Illuminate\Tests\Integration\Database\EloquentBelongsToManyTest::testCustomPivotClass
testCustomPivotClassUpdatesTimestamps
Integration\Database\EloquentCollectionLoadCountTest::testLoadCount()
testLoadCountWithSameModels

**Comment by jrmajor** [comment]
> Integers and floats in result sets will now be returned using native PHP types instead of strings when using emulated prepared statements. This matches the behavior of native prepared statements. You can restore the previous behavior by enabling the `PDO::ATTR_STRINGIFY_FETCHES` option.

(from https://github.com/php/php-src/blob/96fe8141c397518e4ee10e65a7b921d779d332b6/UPGRADING#L117-L126)

`PDO::ATTR_STRINGIFY_FETCHES` is explicitly disabled here:
https://github.com/laravel/framework/blob/93019f17ea1373a2cb3eb9747a561592730eca6b/src/Illuminate/Database/Connectors/Connector.php#L20-L26

I don't know what's the difference between emulated and native prepared statements. What confuses me is `PDO::ATTR_EMULATE_PREPARES => false`, which looks like emulated prepared statements being disabled, and this change is supposed to apply only to them. I would appreciate it if somebody could demystify that for me.

Anyway, many DB tests are failing because of this change. Would you accept a PR adding version checks like this:

```diff
- $this->assertSame('2', $post->comments_count);
+ $this->assertSame(PHP_VERSION_ID >= 81000 ? 2 : '2', $post->comments_count);
````

or do you prefer another solution?

**Comment by driesvints** [comment]
Atm this issue is blocked by https://github.com/aws/aws-sdk-php/pull/2269

@jrmajor thanks for that. I'll take a look at it as soon as the above is unblocked.

**Comment by driesvints** [comment]
Blocked by https://github.com/aws/aws-sdk-php/pull/2284 for now.

**Comment by driesvints** [comment]
AWS PHP SDK is now unblocked. Sent in a PR to the next blocking repo: https://github.com/dflydev/dflydev-dot-access-data/pull/40

**Comment by driesvints** [comment]
Next up is a Mockery fix for PHP 8.1 return types. Waiting until @GrahamCampbell has https://github.com/mockery/mockery/commit/b4da5440991f6c2f517e2879b5bb15772a2a8796 committed to master.

**Comment by drbyte** [comment]
Fortunately only 2 source files appear to be affected by this deprecation:
https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime
https://github.com/laravel/framework/search?q=strftime

**Comment by Sn0wCrack** [comment]
Looks like those references to strftime are in an SQLite generated query, so doesn't look like either is affected by this deprecation.

Also looks like Mockery is waiting on this PR now https://github.com/mockery/mockery/pull/1140

**Comment by drbyte** [comment]
> Looks like those references to strftime are in an SQLite generated query, so doesn't look like either is affected by this deprecation.

Oy! True. I had apparently been staring at too much code when I dug into that.  Thanks for pointing it out.  💯

**Comment by driesvints** [comment]
Gonna close this to continue the discussion in the related PR.
