### ISSUE TITLE
SQLSTATE[HY000]: General error: 1005 Can't create table payouts (errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by karaOdin** [laravel/framework#36821]
- Laravel Version: 7.29
- PHP Version: 7.4.12
- Database Driver & Version: 10.4.16-MariaDB 

### Description: (errno: 150 "Foreign key constraint is incorrectly formed")
i'm trying to create new table payouts contain user_id but always get this error message (errno: 150 "Foreign key constraint is incorrectly formed") 

### Steps To Reproduce:
User migration 
`$table->bigIncrements('id');
            $table->string('name')->unique();
            $table->string('company_name')->nullable()->unique();
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->string('photo')->default('/images/users/avatar.png');
            $table->string('address')->nullable();
            $table->string('phone')->nullable();
            $table->string('willaya')->nullable();
            $table->boolean('new')->default(1);
            $table->boolean('status')->default(1);
            $table->string('secret')->default('azerty');
            $table->rememberToken();
            $table->timestamps();`
and payouts table migration 
 `$table->bigIncrements('id');
            $table->bigInteger('user_id')->unsigned();
            $table->date('date_paid')->nullable();
            $table->text('description')->nullable();
            $table->double('amount')->nullable();
            $table->double('fee')->nullable();
            
            $table->string('rib')->nullable();
            $table->enum('status',['pending','paid','rejected','refunded','failed'])->nullable();
            $table->string('username')->nullable();

            $table->foreign('user_id')->references('id')->on('users');

`

users table is already created and i wanted to add this new table payouts but i can't

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
