### ISSUE TITLE
Datetime precision lost when altering column in migration using ->change()

### ISSUE THREAD

**Issue by kwhohasamullet** [laravel/framework#36838]
- Laravel Version: 8.34.0
- PHP Version: 8.0.0
- Database Driver & Version: mysql (DBAL 3.0)

### Description:
When modifying a column type of datetime with the precision set the resulting CHANGE query does not specify the precision. In mysql this results in precision being set to 0 on the column

**Query being produced**
**$table->dateTime('end_at', 3);**
`art migrate --pretend`
`alter table `sets` add `end_at` datetime(3) not null`

**$table->dateTime('end_at', 3)->change()**
`art migrate --pretend`
`ALTER TABLE sets CHANGE end_at end_at DATETIME DEFAULT NULL`

### Steps To Reproduce:
1) Create a migration that adds a datetime with the precision set: ie

```
        Schema::table('test', function (Blueprint $table) {
            //Make end_at column nullable
            $table->dateTime('end_at', 3);
        });
```
2) Create a new migration which modifies the previously made column
```
        Schema::table('test', function (Blueprint $table) {
            //Make end_at column nullable
            $table->dateTime('end_at', 3)->nullable()->change();
        });
```
3) Column in Mysql will now be set to precision of 0

**Comment by kwhohasamullet** [comment]
I had a bit of a go at figuring it out myself (First time I have gone diving into the framework so may be very wrong!)

Appears that DBAL is responsible for this and is not adding in precision as part of generating the change. It appears that in the Mysql Library it is set to just return DATETIME without any precision. 
[https://github.com/doctrine/dbal/blob/20bcec57aae2e24b82a32a33d2e9227dde6c1bba/src/Platforms/MySQLPlatform.php#L208](https://github.com/doctrine/dbal/blob/20bcec57aae2e24b82a32a33d2e9227dde6c1bba/src/Platforms/MySQLPlatform.php#L208)
It appears that other database types do varying things from no precision to setting default precision values (SQLServer returns DATETIME(6) for the same method)

This issue  seems to have been encountered before with timestamps with a new timestamptype (Illuminate\Database\DBAL\TimestampType) class being created and included:
[https://laravel.com/docs/8.x/migrations#prerequisites](https://laravel.com/docs/8.x/migrations#prerequisites)

The fix for this could be to add a new DateTimeType class which correctly uses the provided precision values  and returns the appropriate result. The code for this would be nearly identical to the timestamp code (obviously replacing timestamp with appropriate datetime column types for each database type)

The only issue with this approach is when these additional classes are added into the DBAL/Types instance it will not include a class if it already exists (which datetimetype will). Further it uses Type::addType() which will fail as datetimetype already exists, in this instance we would need to call Type::overrideType() to add the custom class.
[https://github.com/laravel/framework/blob/843f8bb4269bb983826ba709d49cd697a040e85a/src/Illuminate/Database/DatabaseServiceProvider.php#L117](https://github.com/laravel/framework/blob/843f8bb4269bb983826ba709d49cd697a040e85a/src/Illuminate/Database/DatabaseServiceProvider.php#L117)

If I am on the right track happy to have a go at a fix myself but seems like a few things would need to change to fix this up

**Comment by driesvints** [comment]
Hey @kwhohasamullet, thanks for the thorough investigation here. I indeed also believe the problem lies with DBAL. Like you indicated we'd need to override their DateTimeType class to fix this. Best that you open an issue on their issue tracker.

**Comment by kwhohasamullet** [comment]
Thanks @driesvints 

I've had more of a look into this and it appears that this has been flagged with DBAL previously and they are not keen on changing it. Reason being is there is a large variance in support for datetime precision across database types. It seems most of their issue with this is around retrieving data. It has been stated in some places support for this was due in doctrine 3 but this has come and gone with no fixes or mention of it again.

[https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/known-vendor-issues.html](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/known-vendor-issues.html)
[https://github.com/doctrine/dbal/issues/2873](https://github.com/doctrine/dbal/issues/2873)

The specific issue with Laravel is because we are not using doctrine to create the columns, only when modifying them it means the framework can handle precision without issue on a column creation but then no longer be able to when changing a column. This is quite confusing from an end user standpoint and has the potential to introduce difficult to identify bugs.
In my case I only use the precision in backend tasks and never display it in the front end I managed to go a few hours without any apparent issue in my use case. The only reason I found it is that I noticed my times all ended in .000 when I was looking in the DB at something else!

Because of this I believe we need to address this in one way or another. 

### Few possible solutions to this:
**1) Overwrite the DBAL datetime class** - This introduces an maintenance burden which makes it not a great solution
**2) Create a new custom type (ie DatetimeWithMilliseconds)** - This can be included in the same way as the existing timestamp custom type. We can then detect if precision has been specified and if so make use of the new class.
**3) Remove the ability to create datetime with precision** - This will make for a more consistent experience for users but result in a loss of features from migration
**4) Big explanation in the Docs warning people of this caveat** - .....Please don't choose this as the best option

As before I am quite happy to put this together and create a PR for it - Just want some guidance from the team as to the best approach.

**Comment by driesvints** [comment]
Hey @kwhohasamullet, thanks for that. I think 1) will probably not be accepted. You can try a PR for 2) to see if Taylor would accept it but I doubt it. 3) definitely isn't an option so I think 4) will be the best solution.
