### ISSUE TITLE
Local Query Scope combined with orWhere() leads to wrong Pagination

### ISSUE THREAD

**Issue by HepplerDotNet** [laravel/framework#36839]
- Laravel Version: 8.34.0
- PHP Version: 8.0.3
- Database Driver & Version: MariaDB 10.5.9

### Description:
I'm using a local query scope to implement Full Text Search in one of my Models.
Combining search with `orWhere()` and Pagination returns wrong results count.

```php
public function scopeSearch($query, $term)
{
        $columns = implode(',', $this->searchable);
 
        return $query->whereRaw("MATCH ({$columns}) AGAINST (? IN BOOLEAN MODE)" ,$term);
}
```

### Steps To Reproduce:
```php
$accounts = Account::search($search)->orderBy('fullname')->paginate(10);
```
Searching for 'Foo' returns 4 results and, as expected, no pagination links are rendered.

```php
$accounts = Account::search($search)
                ->orWhere('fullname', 'LIKE', '%'.$search.'%')
                ->orWhere('email', 'LIKE', '%'.$search.'%')
                ->orderBy('fullname')->paginate(10);
```
Searching for 'Foo' also returns 4 results, but Paginator renders "Showing 1 to 4 of 11" and two pagination links.
Where 11 is the count of all rows in database.

**Comment by dkulyk** [comment]
try to wrap search:
```php
Account::where(function($builder) {
                $builder->search($search)
                ->orWhere('fullname', 'LIKE', '%'.$search.'%')
                ->orWhere('email', 'LIKE', '%'.$search.'%');
                })->orderBy('fullname')->paginate(10);
```

**Comment by HepplerDotNet** [comment]
@dkulyk this works. But I wonder why I have to wrap it?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by HepplerDotNet** [comment]
@driesvints no, I still consider this is a bug! Because same queries are handled different depending on the way they get called.

Using a scope on a model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class Account extends Model
{
    use HasFactory;
    protected $searchable = [
        'fullname',
        'email',
    ];

public function scopeSearch(Builder $query, string $term): Builder
    {
        $columns = implode(',', $this->searchable);

        return $query->whereRaw("MATCH ({$columns}) AGAINST (? IN BOOLEAN MODE)", $this->removeSymbols($term));
    }

    protected function removeSymbols(string $term): string
    {
        // removing symbols used by MySQL
        $reservedSymbols = ['-', '+', '<', '>', '@', '(', ')', '~', '*', '%'];
        $term = str_replace($reservedSymbols, '', $term);

        $words = explode(' ', $term);

        foreach ($words as $key => $word) {
            /*
             * applying + operator (required word) only big words
             * because smaller ones are not indexed by mysql
             */
            if (strlen($word) >= 3) {
                $words[$key] = '+'.$word.'*';
            }
        }

        return implode(' ', $words);
    }
```
Running this:
```php
$accounts = Account::search($search)
                ->orWhere('fullname', 'LIKE', '%'.$search.'%')
                ->orWhere('email', 'LIKE', '%'.$search.'%')
                ->orderBy('fullname')->paginate(10);
```
Searching for 'Foo' returns 4 results, but Paginator renders "Showing 1 to 4 of 11" and two pagination links.
Where 11 is the count of all rows in database.

But running this:
```php
$accounts = Account::whereRaw("MATCH (name) AGAINST (? IN BOOLEAN MODE)", $search)
                ->orWhere('fullname', 'LIKE', '%'.$search.'%')
                ->orWhere('email', 'LIKE', '%'.$search.'%')
                ->orderBy('fullname')->paginate(10);
```
Searching for 'Foo' also returns 4 results, but Paginator doesn't render, as expected because there are no pages needed.

**Comment by driesvints** [comment]
@HepplerDotNet I think it's best that you attempt a PR with a failing test if you believe there's a bug here.

**Comment by HepplerDotNet** [comment]
@driesvints the issue is that pagination does not use the **exact** same query to aggregate the result count.
It's omitting the `order by fullname`, which for some reason results in a different count.
**I think this is a bug in MariaDB.**

```sql
select count(*) as aggregate 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%';
```
For some reason, this returns 11 (the total count of all rows) at the first run.

```sql
select count(*) as aggregate 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%' ;
select * 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%';
select count(*) as aggregate 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%';
```
Running this in a GUI like HeidiSQL returns:
1. 11 (wrong count)
2.  4 results which match the query
3.  4 (the correct count)

```sql
select count(*) as aggregate 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%' ;
select * 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%' order by fullname asc;
select count(*) as aggregate 
from `accounts` 
where MATCH (fullname) AGAINST ('+foo*' IN BOOLEAN MODE) 
   or `fullname` LIKE '%foo%';
```
Running this in a GUI like HeidiSQL returns:
1. 11 (wrong count)
2.  4 results which match the query
3.  11 (the wrong count)

**Comment by jnjacobson** [comment]
Hey, we also think this is a bug.

We expected this code to work:
```php
$paginator = DB::table('users')
    ->orderBy('id')
    ->where('name', '=', 'x')
	->orWhere('email', '=', 'y');
	->cursorPaginate(10)
    ->withQueryString();
```
but `$paginator->cursor->encoded` is the same as `$paginator->cursor->encoded` for the second page. Also the results are not correct.

After finding this issue, we wrote this workaround, which works fine:
```php
$paginator = DB::table('users')
    ->orderBy('id')
    ->where(function ($builder) {
        $builder
            ->where('name', '=', 'x')
            ->orWhere('email', '=', 'y');
    })
	->cursorPaginate(10)
    ->withQueryString();
```

Why do we need to wrap the where statements when there is more than one? If this is expected behaviour, can you tell me where it is documented?

**Comment by driesvints** [comment]
Please submit a PR with a failing test.
