### ISSUE TITLE
It's not possible to use a fluent like factory states

### ISSUE THREAD

**Issue by beniaminorossini** [laravel/framework#36849]
- Laravel Version: 8.12
- PHP Version: 8.0

### Description:
Hi everyone and thx for good work on factories, very appreciated.
I'm trying to implement a logic-based state application on factories, but it seems it is not possible to store a factory var and then apply states conditionally.
Entities created by factory is always base factory without  a state.
Instead, if i write in one line every state, everything is correctly applied.

Maybe i'm missing something in factory's state logic?

### Steps To Reproduce:

Factory class
```
class FollowupFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Followup::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'covid_diagnosis'       => false,
            'covid_synthomps'       => false,
            'covid_hospitalization' => false,
            'treatments_suspended'  => false,
            'covid_vaccination'     => false,
            'answered'              => false,
        ];
    }

    public function hasCovidDiagnosis()
    {
        return $this->state(function (array $attributes) {
            return [
                'covid_diagnosis'    => true,
                'covid_diagnosis_at' => Carbon::now()->subMonths(1),
            ];
        });
    }
//..........
```

Seeder class
```
class FollowupBaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//....
$patients->each(function (Patient $patient) use ($doctor) {
            for ($i = 0; $i < rand(0, 5); $i++) {
                $followup = Followup::factory();
                if (rand(0, 100) > 60) {
                    $followup->hasCovidDiagnosis();
                    if (rand(0, 100) > 60) {
                        $followup->hasCovidSynthomps();
                    }
                    if (rand(0, 100) > 40) {
                        $followup->hasVaccination();
                    }
                }
                if (rand(0, 100) > 30) {
                    $followup->hasAnswer();
                    $followup->for($doctor, 'doctorAnswered');
                }
                $followup->for($patient)->create();
            }
        });
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by beniaminorossini** [comment]
ok thx sorry, i’m not sure that it is a bug or missin feature

**Comment by brunogaspar** [comment]
I consider it as a bug or maybe a missing feature..

I had this same issue not so long ago, but didn't bothered to much with it, as i suspected, if i opened the issue here, it would be closed. While i understand that is cool and all too have low issues count, it is very premature to close issues without even understanding if it's a question, a bug, new feature request or perhaps a user mistake.

--

But anyway.. In regards to the OP issue, basically, to address it on your end, you need to do `$followup = $followup->hasCovidSynthomps();` (which i assume you know, but just leaving it here) and so on, it's not the ideal thing but at least it works.

Just an example of the code i have (which looks very random)

```php
protected function resolveModelFactoryInstance(): Factory
{
    $modelFactoryInstance = $this->resolveModel()->factory();

    foreach ($this->factoryState as $state) {
        $modelFactoryInstance = $modelFactoryInstance->{$state}();
    }

    return $modelFactoryInstance;
}
```

**Comment by beniaminorossini** [comment]
> I consider it as a bug or maybe a missing feature..
> 

Maybe it's a little confusing feature because it seems that we can apply the states to the same factory instance instead of returning a new one every time.
However your solution works perfectly 

Would it be useful to update the documentation probably?
 
> ```
> protected function resolveModelFactoryInstance(): Factory
> {
>     $modelFactoryInstance = $this->resolveModel()->factory();
> 
>     foreach ($this->factoryState as $state) {
>         $modelFactoryInstance = $modelFactoryInstance->{$state}();
>     }
> 
>     return $modelFactoryInstance;
> }
> ```
