### ISSUE TITLE
Str::plural('travel') doesn't return travels but travel.

### ISSUE THREAD

**Issue by glamax13** [laravel/framework#36852]
- Laravel Version: 8.12
- PHP Version: 7.4.16

### Description:
The pluralization of the word travel is incorrect.

### Steps To Reproduce:
Launch laravel tinker
>>> Str::plural('travel');
=> "travel"

**Comment by driesvints** [comment]
It depends: https://www.wordhippo.com/what-is/the-plural-of/travel.html

![Screenshot 2021-04-02 at 15 08 21](https://user-images.githubusercontent.com/594614/113418202-4fb47900-93c5-11eb-92d5-4d9282040584.jpg)

**Comment by glamax13** [comment]
Ho! That's ... interesting to be sure.
I actually checked before making this issue but i guess i still got it wrong.
Source: https://www.merriam-webster.com/dictionary/travel
travels plural : an account of one's travels.

I was afraid it could be a corner case but i if that's the case i will just deal with it.

Thank you and have a good day!
