### ISSUE TITLE
Laravel pagination renders links for no records and page number greater than 1

### ISSUE THREAD

**Issue by asifmulla** [laravel/framework#36854]
- Laravel Version: 8.35.1
- PHP Version: 8.0
- Database Driver & Version:
MySQL 5.7
### Description:

$paginator->hasPages() always returns true, if there are no records and forcefully changing URL query parameter "page" to number greater than 1; which results in rendering $paginator->links(). Am I missing something?
![carbon (1)](https://user-images.githubusercontent.com/196736/113429654-835bc700-93f6-11eb-9a13-ccd257c47a26.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
