### ISSUE TITLE
php artisan make customize file paths

### ISSUE THREAD

**Issue by fast-oopdev** [laravel/framework#36863]
- Laravel Version: 8.12
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
I needed to change the path to create the provider. I used this command
Error in namespace

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/28774865/113474195-0afe1000-94a1-11eb-903e-608db15d741e.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
