### ISSUE TITLE
 can't export multiple excel files laravel.

### ISSUE THREAD

**Issue by giangca3010** [laravel/framework#36867]
- Laravel Version: 5.8

### Description:
 I can't export multiple excel files. I have been query an array data and I want to export and save it "in public". But the error is "Call to a member function all () on null"

### Steps To Reproduce:
Code:
public function collection()
    {
        $Partners = RetailPartner::get();
        foreach ($Partners as $key => $Partner) {
            $PartnerArray = $Partner[$key];
        }

        return $PartnerArray;
    }
    
Controller:
 public function export()
    {
        $today = date("Y_m_d");
        return Excel::store(new TestExport(), 'excel/test_'. $today .str_random(2) .'.xlsx', 'excel_public');
    }

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
