### ISSUE TITLE
Class based component may not work arter updating the constructor

### ISSUE THREAD

**Issue by nshiro** [laravel/framework#36869]
- Laravel Version: 8.35.0
- PHP Version: 8.0.1

### Description:
Class based component may not work arter updating the constructor because of cached view file.

### Steps To Reproduce:
First you make a component.

`php artisan make:component Alert`

Then call that component with an attribute.
`<x-alert name="John" />`

After you see the page with your browser, then you change Alert Component constructor like so.
```php
    public $name;

    public function __construct($name)
    {
        $this->name = $name;
    }
```
Then you get an error like this.
`Illuminate\Contracts\Container\BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> $name ]] in class App\View\Components\Alert (View: /...path.../resources/views/home.blade.php)`

It seems cached view file is remembering that the 'name' is an attribute but it is not after updating the constructor.
```php
// cached view file
<?php $component->withAttributes(['name' => 'John']); ?>
```
So when you clear cached files or update your calling view file, You get your expected behavior.
Should we always clear cache after updating constructor ?

Thank you in advance.

**Comment by driesvints** [comment]
Yes always clear your views.
