### ISSUE TITLE
php artisan make customize file paths

### ISSUE THREAD

**Issue by fast-oopdev** [laravel/framework#36862]
- Laravel Version: 7.29
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:
I needed to change the path to create the provider. I used this command 

PHP Artisan Make: Provider.. /.. /packages/we

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/28774865/113473304-7cd35b00-949b-11eb-8ec2-0b7c415c8247.png)

**Comment by crynobone** [comment]
That not a supported command option.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
