### ISSUE TITLE
Batches with failed jobs are not marked as finished

### ISSUE THREAD

**Issue by sebdesign** [laravel/framework#36864]
- Laravel Version: 8.34.0
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 5.7.33

### Description:

I'm using job batching with Horizon, and I noticed that a batch that **allows failures** is not marked as finished,
although all jobs have been processed (some are successful and some are failed). Is this the correct behavior?
I expected that the batch would be finished, even if the number of `failed_jobs` is greater than 0 (the `pending_jobs` is also equal to `failed_jobs`).

In the Horizon dashboard, the batch has a `Finished` badge because the progress is `100`.
But the `Batch::progress()` method is not very accurate, because it rounds the number of processed jobs divided by the number of total jobs.

E.g. for a total of 1000 jobs where 1 failed, that calculates `round(((1000 - 1) / 1000)) * 100)` which returns `100`.
But for 100 total jobs that would return `99`.

I think the expected behavior would be to have the `finished_at` timestamp set after the queue has finished processing all the jobs, irregardless of the successes and failures. That way I would know if a batch is still in progress or if it has finished, if I can dispatch a new batch or I would still have to wait or cancel, etc.

Also these batches cannot be pruned with `artisan queue:prune-batches` because the `finished_at` timestamp is `null`.

### Steps To Reproduce:

```php
class Success {
    use Illuminate\Bus\Batchable;

    public function handle () {
        //
    }
}

class Failure {
    use Illuminate\Bus\Batchable;

    public function handle () {
        abort(500);
    }
}

$batch = Bus::batch(collect()
    ->times(999, fn () => new Success())
    ->add(new Failure())
)->name('99.9% success')->allowFailures()->dispatch();

// After the batch has been "processed"

$batch->totalJobs; // 1000
$batch->pendingJobs; // 1
$batch->failedJobs; // 1
$batch->processedJobs(); // 999
$batch->progress(); // 100
$batch->finished(); // false
$batch->cancelled(); // false
```

**Comment by themsaid** [comment]
This is the correct behaviour. A batch is only finished when all its jobs run successfully.

**Comment by driesvints** [comment]
I'll send in a PR to the docs.

**Comment by sebdesign** [comment]
If that's the case, then Horizon should be updated as well, because it's reporting that a batch has finished, while it has failed jobs.

**Comment by themsaid** [comment]
I can't replicate that. Whenever a job in a batch fails, the status of the batch on Horizon appears as "Failures".

**Comment by sebdesign** [comment]
@themsaid I'm referring to batches that are dispatched using `allowFailures()`.

![image](https://user-images.githubusercontent.com/667144/113586808-a1176f00-9636-11eb-8fb8-5b0a48200488.png)

**Comment by themsaid** [comment]
I'm testing using `allowFailures()`. Can't replicate. Please open an issue on Horizon with steps of replication.
