### ISSUE TITLE
Unable to unit test console commands

### ISSUE THREAD

**Issue by ragingdave** [laravel/framework#36878]
- Laravel Version: 8.35.1
- PHP Version: 7.4.3

### Description:
Perhaps the title should more read "unable to easily unit test console commands", but here goes.

When attempting to unit test a console command, the docs say to use `$this->artisan('command:name')` which works for very simplistic checks around output expections and the like. That works but a potential common case of needing to mock out a method on the command results in a much harder to test situation.

For example, in attempting to mock out a method on the command in order to test a certain condition, maybe hitting an api for data, or just more easily having that method throw an exception, isn't possible.

```    
    /** @test */
    public function it_imports_stuff()
    {
        $this->mock(ApiService::class, function ($mock) {
            return $mock->shouldReceive('getListOfStuff')
                ->andReturn(LazyCollection::make(function () {
                    yield [
                        'type' => 'F',
                        'code' => 12345,
                        'name' => 'Test Name',
                        'address' => '1600 Pennsylvania Avenue',
                        'city' => 'Washington',
                        'state' => 'DC',
                        'zip' => '20003',
                    ];
                }));
        });

        $this->partialMock(ImportStuff::class, function ($mock) {
            return $mock->shouldAllowMockingProtectedMethods()
                ->shouldReceive('getThings')
                ->andReturn(collect());
        });

        $this->artisan('import:stuff');
    }
```
In attempting this, I get 
```
Symfony\Component\Console\Exception\LogicException: Command class "Mockery_3_App_Console_Commands_ImportStuff" is not correctly initialized. You probably forgot to call the parent constructor.
```
The mocking (maybe, because I can't actually test it) works to swap the api service being injected, but I can't mock a method of the console command. This seems very counterintuitive, as I'm trying to test the various conditions around the command, and other than directly calling the handle method, which ends up being pretty nasty compared to all the good work that laravel does to make DX great.

Maybe this is more of a question then, but how exactly in a clean way, are we supposed to test console commands if not using the documented artisan call (while still being able to assert output expections and the like) as this clearly doesn't work fully?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ragingdave** [comment]
I understand I framed it as a question, but it is still a bug. As I outlined, you can't use the documented artisan call in tandem with documented mocking of the command itself. The question was intended as a follow up assuming that it isn't a bug in the eyes of the framework team.

**Comment by driesvints** [comment]
Hey @ragingdave, you're right but as you indicated it seems more like a limitation than an actual bug. We do appreciate PRs to the docs or the framework to improve things though.
