### ISSUE TITLE
Problem in pagination links

### ISSUE THREAD

**Issue by parsampsh** [laravel/framework#36874]
# Problem in pagination links
There is a problem in pagination link handling.
The GET query string will not be included in the links.
For example, in the `/posts?search=something`, we expect some links like this:
```
/posts?search=something&page=1
/posts?search=something&page=2
/posts?search=something&page=3
...
```
But the output is:
```
/posts?page=1
/posts?page=2
/posts?page=3
...
```

**Comment by brunogaspar** [comment]
https://laravel.com/docs/8.x/pagination#appending-query-string-values

See if that helps.

**Comment by parsampsh** [comment]
Thank you so much!
