### ISSUE TITLE
The resource routes still working if the URL consists of alphanumeric for resource id

### ISSUE THREAD

**Issue by sachinkumar121** [laravel/framework#36871]
- Laravel Version: 8.0.0
- PHP Version: 7.3.7
- Database Driver & Version: MySql Server version: 10.3.16-MariaDB

### Description:

I am working on a Laravel application and I come across a very strange issue. I have defined the routes using the Route::resource function 

	Route::resource('posts', 'PostController');

and I generate the PostController using 

> php artisan make:controller PostController --resource --model=Post

command so it is using Implicit Binding for Post resource.

Now the URLs are 

	GET			/posts
	GET			/posts/create
	POST		/posts
	GET			/posts/{post}
	GET			/posts/{post}/edit
	PUT/PATCH	/posts/{post}
	DELETE		/posts/{post}

Everything is working fine. Let say I have a post whose id is 146. so the URL for the post detail page will be

	http://localhost/laravel-app/posts/146

This URL is working fine. But when I open the following URL it still working.

	http://localhost/laravel-app/posts/146re4dasdasda

	http://localhost/laravel-app/posts/146re4

	http://localhost/laravel-app/posts/146re

So I expected that the above mention URLs should return a 404 not found page. But it still shows the detail page for the post whose id is 146.

and the URLs are also working for edit, update or delete operations. i.e

	GET			/posts/146re4/edit
	PUT/PATCH	/posts/146re4
	DELETE		/posts/146re4

### Steps To Reproduce:
- Create a new Laravel project.
- Generate PostController using the "php artisan make:controller PostController --resource --model=Post" command
- create a sample post. let say the id is 121.
- Open /posts/121 it will works
- Open /posts/121abc/ it still working. But it should return 404 i.e. ModelNotFoundException

### key note:
- The same thing is also happening with apiResource. ie. Route::apiResource('posts', 'PostController');
- I raise this issue for Laravel 7.3.7([issue 36517](https://github.com/laravel/framework/issues/36517)) but the support suggests me to upgrade to the latest version and see if your problem persists. I upgrade the framework to v8.0.0.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sachinkumar121** [comment]
I asked on the [stackoverflow](https://stackoverflow.com/questions/66541288) but some suggest that this is an issue in Laravel. So thats why I posted this issue here. The actual issue is that if I created resource routes then it should not be working with alphanumerics resource URLs. It should only be working with numeric resource URLs.

**Comment by rs-sliske** [comment]
looks like the id is being cast as an integer somewhere, do you have telescope/debugbar/mysql general log to see what query was ran?

**Comment by rodrigopedra** [comment]
Models cast keys to integer by default:

https://github.com/laravel/framework/blob/4f289b0b3f6c5ad7818bc81b230c8b0c497d2348/src/Illuminate/Database/Eloquent/Model.php#L56-L68

https://github.com/laravel/framework/blob/4f289b0b3f6c5ad7818bc81b230c8b0c497d2348/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1138-L1150

PHP tries to casts strings starting with a number sequence to integer by using this start-sequence:

https://3v4l.org/aQZfa

So `"146re4"` gets cast to `146`

You can mitigate this by using parameter constraints on your route definitions:

https://laravel.com/docs/8.x/routing#parameters-regular-expression-constraints

Or globally to avoid repeating it on every route:

https://laravel.com/docs/8.x/routing#parameters-global-constraints

**Comment by laurencei** [comment]
Hi,

I remember we discussed this for Laravel 5 like 3-4 years ago. Its not a routing issue. Its a database SQL issue.

If I remember correctly, if you try

```
DB::table('users')->where('id', '123abc')->first();
```

It will select the user with an ID of 123, instead of returning 0 records.

I'll try and find the old issues where it was discussed at length.

**Comment by rodrigopedra** [comment]
@laurencei  thanks, didn't know that MySQL (tested in it) had that same string coercion behavior as PHP.

Tested in this fiddle:

https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=c8b4863c3451a1ba1e0ea08d13833d68

With this simple code:

~~~sql
CREATE TABLE `users`
(
    `id` INTEGER,
    `name` VARCHAR(100)
);

INSERT INTO `users` (`id`, `name`) VALUES (1, 'foo');

SELECT * FROM `users` WHERE `id` = '1abc';
~~~

And it returns the user:

| id | name |
|----|---------|
| 1  | foo    |

In any case it is not a Laravel fault, both PHP and MySQL allows this unexpected behavior.

Laravel actually allows to mitigate this, using the route parameter constraints as I suggested previously.

Thanks again @laurencei , for the heads up.

**Comment by laurencei** [comment]
Thanks - I remember because if you do this on Laravel Forge and do a Server ID of "123abc", it has the same issue :)

The only way I can think of to solve it is, if you have numeric only model ID (as opposed to UUID), then you could write a custom route model matcher, that first does a validation that the supplied ID is numeric only.

If it contains anything other than `0-9`, then you return 404. If it is only `0-9`, then do a normal model lookup.

Maybe it could be a feature in Laravel for "strict model numeric ID routing" or something.

**Comment by rodrigopedra** [comment]
> If it contains anything other than 0-9, then you return 404. If it is only 0-9, then do a normal model lookup.

I think this feature I linked before solves that:

https://laravel.com/docs/8.x/routing#parameters-regular-expression-constraints

> Maybe it could be a feature in Laravel for "strict model numeric ID routing" or something.

But I agree this could be a nice feature to add, as remembering to define the constraints for every route model binding is a very repetitive task and prone to errors.

Maybe checking the model's `$keyType` property here and sanitizing it could be a good idea:

https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Database/Eloquent/Model.php#L1716-L1726

As this function is called once per route resolution, it shouldn't affect performance in a noticeable way.

**Comment by sachinkumar121** [comment]
I have tried to set the [regular-expression-constraints](https://laravel.com/docs/8.x/routing#parameters-regular-expression-constraints)

but I don't find how do we can set for the resource routes.

`Route::resource('posts', 'PostController')->where('post', '[0-9]+');`

As I get the following error when I set the above route rule

> array_merge(): Expected parameter 2 to be an array, string given

**Comment by rodrigopedra** [comment]
For resource routes you should pass the parameter as an array:

~~~php
Route::resource('posts', 'PostController')->where(['post' => '\d+']);
~~~
