### ISSUE TITLE
Storage Linking Issue in Laravel

### ISSUE THREAD

**Issue by MSAAD-F** [laravel/framework#36882]
- Laravel Version: 8.35.1
- PHP Version: 8.0.0

**Description:**
I'm uploading an image with laravel using this code:

```
 $product_image = $request->file('product_image');
 $product_image_extension = $product_image->extension();
 $product_image_name = time() . '.' . $product_image_extension;
 $product_image->storeAs('/media/product_images', $product_image_name);
 $model->product_image = $product_image_name;
```

It works fine, the file is uploaded to storage/app/media/product_images/.

Then, I run the command `php artisan storage: link ` to create the symlink in public.
The Command Execute Like this:

```
Local NTFS volumes are required to complete the operation.
The [E:\Complete Programming Bootcamp\laravel Work\ecom-project\cyber_shopping\public\storage] link has been connected to [E:\Complete Programming Bootcamp\laravel Work\ecom-project\cyber_shopping\storage\app/public].
The links have been created.
```

I am Using This Code To Display Image:

`{{asset('storage/media/product_images/' . $list->product_image)}}`

But Image is not displaying on the frontend.

PLz, Help Me.
Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
