### ISSUE TITLE
[8.x] SQLite add column + drop column ignores add statement

### ISSUE THREAD

**Issue by ddzobov** [laravel/framework#36880]
Laravel Version: 8.35.1
PHP Version: 7.4.16
Database Driver & Version: sqlite

### Description:

We have migration:
```
public function up()
    {
        var_dump(Schema::getColumnListing('organizations'));
        Schema::table('organizations', function (Blueprint $table) {
            $table->string('address')->nullable();
            $table->dropColumn('description');
        });
        var_dump(Schema::getColumnListing('organizations'));
    }
```

Here we have "description" field and trying to remove it and add "address" field instead of:
```
array(6) {
  [0]=>
  string(2) "id"
  [1]=>
  string(4) "name"
  [2]=>
  string(11) "description"
  [3]=>
  string(10) "created_at"
  [4]=>
  string(10) "updated_at"
  [5]=>
  string(10) "deleted_at"
}
```

"description" dropped, but "address" not added:
```
array(5) {
  [0]=>
  string(2) "id"
  [1]=>
  string(4) "name"
  [2]=>
  string(10) "created_at"
  [3]=>
  string(10) "updated_at"
  [4]=>
  string(10) "deleted_at"
}
```

### Steps To Reproduce:
1. Create migration
2. Run migration

**Comment by driesvints** [comment]
Please see the docs: https://laravel.com/docs/8.x/migrations#dropping-columns

![Screenshot 2021-04-05 at 22 08 43](https://user-images.githubusercontent.com/594614/113621110-886d8000-965b-11eb-8710-cd43d40abbf1.jpg)

**Comment by ddzobov** [comment]
What about add some exception?
