### ISSUE TITLE
Memory exhausted using "$with" in the model but not with "Xpto::with()"

### ISSUE THREAD

**Issue by RicardoRibeirorr** [laravel/framework#36894]
- Laravel Version:  8.33.1
- PHP Version: 7.4.1
- Database Driver & Version: MAMP
- Database: Sqlite

### Description:
I was creating a shopping list system using 2 tables "ShoppingList" & "ShoppingItems" with a relationship between them, where has 1 record in each table.

While using the Eager Loading by default <code>$with = ['shoppingItems']</code> on the ShoppingList, whatever i tried to get data from it like <code>auth()->user()->shoppingLists()->first();</code>, the system was throwing:
<code>PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in D:\Projects\Aulas\thepriceisright\vendor\symfony\error-handler\Error\FatalError.php on line 1</code>

Then, when I removed the Eager Loading by default from the model, and tried to use the Eagle Loading function <code>auth()->user()->shoppingLists()->with("shoppingItems.product")->first();</code>, where I even included the "product" relation, it works fine.

###### ShoppingLists
        Schema::create('shopping_lists', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger("user_id");
            $table->boolean("closed")->default(false);
            $table->timestamps();
        });
        
###### ShoppingItems
        Schema::create('shopping_items', function (Blueprint $table) {
            $table->id();
            $table-> unsignedBigInteger("shopping_list_id");
            $table-> unsignedBigInteger("product_id");
            $table-> double("quantity");
            $table->timestamps();
        });

###### ShoppingList
    protected $with = ["shoppingItems"];
    public function shoppingItems(){
        return $this->hasMany(ShoppingItem::class);
    }

###### ShoppingItem
    public function shoppingList(){
        return $this->belongsTo(ShoppingList::class);
    }
    
    
#### Reproduzing error
On the shopping list controller, use any function that return data, ex:
auth()->user()->shoppingLists()->first();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
