### ISSUE TITLE
DatabaseNotification $casts type is not array

### ISSUE THREAD

**Issue by lucasjose501** [laravel/framework#36897]
https://github.com/laravel/framework/blob/91c454715b81b9a39f718651d4e2f8104d45e7c2/src/Illuminate/Notifications/DatabaseNotification.php#L43

I think it should be "protected array $casts"

I was having this fatal error: Type of Illuminate\Notifications\DatabaseNotification::$casts must be array (as in class Illuminate\Database\Eloquent\Model)"

Making this change solved the problem for me.
Ps: I'm probably wrong here, I'm still a junior dev.

**Comment by driesvints** [comment]
We don't use property type hints. And even can't because we still support php 7.3
