### ISSUE TITLE
Flashed session data doesn't disappear

### ISSUE THREAD

**Issue by DanielMalmgren** [laravel/framework#36901]
- Laravel Version: 8.36.1
- PHP Version: 7.4.13
- Database Driver & Version: Mysql 5.7.29

### Description:
I am flashing a variable like this:
```
     \Session::flash('warning', __('Test!'));
```
...and then I display it in my Blade template like this:
```
@if(session('warning'))
   <div class="alert alert-warning">
        {{session('warning')}}
    </div>
@endif
```

This works fine. However I need to put some html formatting in my warning message, so I changed my {{ and }} tags to {!! and !!} instead to show the message raw. What happens now is that the flashed variable isn't removed properly, so on next page I navigate to, the warning message lingers. On the next change of page after that it disappears, but it's one click too late.

I can't really see the connection between how I display the message and how it's purged (or not) from the session, but it seems to be the case somehow.

### Steps To Reproduce:
1. Flash a session variable
2. Display it unescaped in a Blade template

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DanielMalmgren** [comment]
Ok, seems I was digging in the wrong corner here. I was under the impression that I could flash a session variable and return a view and then that variable would only be active for that page, but it seems it isn't purged until after next time the page is reloaded/changed. Leaves me clueless on how to flash a variable that I only want to use on one page...

**Comment by Krisell** [comment]
If you want data in the same request, you simply pass that data to the view (check out the docs on views). Flashing is for accessing the data after a redirect (on the next request).

**Comment by DanielMalmgren** [comment]
Yes, that's of course what I'd normally do. But for warning and error messages I alreay have logic in place to show what's in the session variables, it would be kinda handy to use the same Blade logic to show them also in cases like this.

For now I have put the following lines in the template, right after the point where the warnings are showed. It fulfills my purposes, but I guess it would be considered very ugly  :-)

```
@php
    \Session::forget(['warning', 'success', 'error']);
@endphp
```
