### ISSUE TITLE
Blade unable to compile @foreach

### ISSUE THREAD

**Issue by nuernbergerA** [laravel/framework#36900]
- Laravel Version: 8.36.1
- PHP Version: 7.4.16
- Database Driver & Version: n/a

### Description:
After [this commit](https://github.com/laravel/framework/commit/e8cdea86e3d365e1825d86fe12d61a966b83f583) blade is unable to render
```blade
@foreach(resolve('App\\DataProviders\\'.$provider)->data() as $key => $value)
    <input {{ $foo ? 'bar': 'baz' }}>
@endforeach
```

and throws and error
```bash
Undefined offset: 1
 framework/src/Illuminate/View/Compilers/Concerns/CompilesLoops.php:95
 framework/src/Illuminate/View/Compilers/BladeCompiler.php:439
 framework/src/Illuminate/View/Compilers/BladeCompiler.php:421
 framework/src/Illuminate/View/Compilers/BladeCompiler.php:420
 framework/src/Illuminate/View/Compilers/BladeCompiler.php:389
 framework/src/Illuminate/View/Compilers/BladeCompiler.php:242
```

**Comment by driesvints** [comment]
Thanks @nuernbergerA. I've sent in a PR to revert all changes that were made to the BladeCompiler in the last few days: https://github.com/laravel/framework/pull/36902

**Comment by nuernbergerA** [comment]
Thanks you @driesvints!

#36901 might be the same issue

**Comment by driesvints** [comment]
No that seems to be something different.
