### ISSUE TITLE
Paginate make response slow with large database records

### ISSUE THREAD

**Issue by mahmoudshahin1111** [laravel/framework#36908]
- Laravel Version: 8.0.0
- PHP Version: 7.4.#
- Database Driver & Version:Ver 8.0.21 for Win64 on x86_64 (MySQL Community Server - GPL)

### Description:
when I using paginate with models directly the response be very slow when working with large databases
`Model::paginate ();`
[Video for the problem](https://www.youtube.com/watch?v=J57fXl3WOx0)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by AlaaKanaan** [comment]
I've opted for the Laravel **simplePaginate()** method here because our specific use case involves returning a JSON response, and **simplePaginate()** neatly provides only 'Next' and 'Previous' links—exactly what we need. It has also noticeably improved performance. While I haven't delved into the inner workings of paginate() with large datasets yet, I might explore the implementation details later on.

**Comment by drewgallagher** [comment]
Is it possible for Laravel to run a slimmed down version of the query (i.e. only selecting `count(*)`) concurrently and then to combine the result? 

I'm not sure how the count query currently works but if a concurrent/parallel query could run to just get the count/pages that may speed it up without having to switch pagination. 

What do you think?
