### ISSUE TITLE
Psql query parameter casting sequence changing result value

### ISSUE THREAD

**Issue by gilbertorussi** [laravel/framework#36916]
- Laravel Version: v8.34.0
- PHP Version: 7.4.10 
- Database Driver & Version: PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

### Description:
There is some strange behavior going on when casting named parameters twice on query builder; It seems like the first time one named attribute is casted, it changes it's value for the next cast

### Steps To Reproduce:
Running this code on tinker:

```php
>>> \DB::select("SELECT :date::DATE, :date::TIMESTAMPTZ", ['date' => '2021-01-01 10:00:00']);
=> [
     {#4825
       +"date": "2021-01-01",
       +"timestamptz": "2021-01-01 00:00:00+00",
     },
   ]
>>> 
```

I was expecting for the timestamptz to be "2021-01-01 10:00:00+00"...

But if I change the select order, it does work:

```php
>>> \DB::select("SELECT :date::TIMESTAMPTZ, :date::DATE", ['date' => '2021-01-01 10:00:00']);
=> [
     {#4818
       +"timestamptz": "2021-01-01 10:00:00+00",
       +"date": "2021-01-01",
     },
   ]
```

Is this a Laravel thing or should I open this up somewhere else?

Note: When running the same query on psql terminal, I get the expected result:
```
# \set date '2021-01-01 10:00:00'
# SELECT :'date'::DATE, :'date'::TIMESTAMPTZ;
    date    │      timestamptz       
════════════╪════════════════════════
 2021-01-01 │ 2021-01-01 10:00:00+00
(1 row)
```

**Comment by rodrigopedra** [comment]
Does it work as expected with just using PDO? 

Also when testing with raw PDO be sure to use the same PDO attributes Laravel uses by default for comparision, specially `ATTR_EMULATE_PREPARES`

Can you try using SQL-standard casts? `SELECT CAST(:date AS TIMESTAMPTZ), cast(:date AS DATE)`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by gilbertorussi** [comment]
It does seems to be a problem with PDO. Thanks anyway!

**Comment by rodrigopedra** [comment]
@gilbertorussi I was about to post the same after some testing:

~~~php
<?php

$pdo = new PDO('pgsql:host=127.0.0.1;port=5432', 'postgres', 'Rodrigo123456', [
    PDO::ATTR_CASE => PDO::CASE_NATURAL,
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_ORACLE_NULLS => PDO::NULL_NATURAL,
    PDO::ATTR_STRINGIFY_FETCHES => false,
]);

$date = '2021-01-01 10:00:00';

// original order
$stmt = $pdo->prepare('SELECT :date::DATE, :date::TIMESTAMPTZ');
$stmt->bindParam('date', $date);
$stmt->execute();

print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo $date, PHP_EOL;


// using casts
$stmt = $pdo->prepare('SELECT CAST(:date AS DATE), CAST(:date AS TIMESTAMPTZ)');
$stmt->bindParam('date', $date);
$stmt->execute();

print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo $date, PHP_EOL;


// inverted order
$stmt = $pdo->prepare('SELECT :date::TIMESTAMPTZ, :date::DATE');
$stmt->bindParam('date', $date);
$stmt->execute();

print_r($stmt->fetchAll(PDO::FETCH_ASSOC));
echo $date, PHP_EOL;
~~~

output

~~~text
Array
(
    [0] => Array
        (
            [date] => 2021-01-01
            [timestamptz] => 2021-01-01 00:00:00+00
        )

)
2021-01-01 10:00:00
Array
(
    [0] => Array
        (
            [date] => 2021-01-01
            [timestamptz] => 2021-01-01 00:00:00+00
        )

)
2021-01-01 10:00:00
Array
(
    [0] => Array
        (
            [timestamptz] => 2021-01-01 10:00:00+00
            [date] => 2021-01-01
        )

)
~~~

Can't say it is a known issue with PDO or if there is a bug tracker open within PHP itself.
