### ISSUE TITLE
withCount not respecting additional join clauses

### ISSUE THREAD

**Issue by karlerss** [laravel/framework#36910]
- Laravel Version: 8.36.1
- PHP Version: 7.4.1

- Database Driver & Version: MySQL 5.7

### Description:

When a relation definition has joins appended, those joins are discarded when assembling the relation count subselect. In the eloquent `withAggregate` function's relations loop we can see that `mergeConstraintsFrom` adds all wheres, but ignores joins. 

### Steps To Reproduce:

This is the relation definition I'm trying to load counts for:
```
/**
 * This relation gives a collection of messages but there will be
 * at most one message in the result.
 * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
 */
public function lastMessages()
{
    return $this->morphToMany(Message::class, 'messageable')
        ->using(Messageable::class)
        ->select(['messages.*'])
        ->whereNotNull('messageables.sent_at')
        ->leftJoin('messageables as m2', function ($q) {
            $q->on('m2.messageable_id', 'messageables.messageable_id')
                ->on('messageables.sent_at', '<', 'm2.sent_at');
        })->whereNull('m2.sent_at');
}
```

Loading the model `withCount(['lastMessages'])` results "Column not found: 1054 Unknown column 'm2.sent_at' in 'where clause". The composed subselect looks as follows:

```
... (select count(*) from `messages` inner join `messageables` on `messages`.`id` = `messageables`.`message_id` where `candidates`.`id` = `messageables`.`messageable_id` and `messageables`.`messageable_type` = App\Models\Candidate and `project_id` = 4) as `messages_count` ...
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by karlerss** [comment]
Hey, thanks for the swift response. To reiterate, this is not a support request - the issue can be easily mitigated by adding the join clause in `->withCount(['messages as last_messages' => fn($q) $q->join(...)])`. 

Per your suggestion, I posted the Issue in Discord too.

**Comment by karlerss** [comment]
@driesvints to convince you that this is indeed a bug, here's a test:

https://github.com/karlerss/framework/commit/11eb52029330b2c1b13840f0f96cc60c8e6be150

Assertion on line 85 passes OK, but fails on line 87 (loadCount):

```
$ pu --filter EloquentWithCountTest
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.1
Configuration: C:\Projects\laravel_framework\phpunit.xml.dist

...[31;1mE[0m                                                                4 / 4 (100%)

Time: 00:00.243, Memory: 124.00 MB

There was 1 error:

1) Illuminate\Tests\Integration\Database\EloquentWithCountTest\EloquentWithCountTest::testRespectsJoins
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such column: two2.id (SQL: select "id", (select count(*) from "two" where "one"."id" = "two"."one_id" and "two2"."id" is null) as "twos_with_join_count" from "one" where "one"."id" in (1))

...

C:\Projects\laravel_framework\tests\Integration\Database\EloquentWithCountTest.php:87

```

**Comment by driesvints** [comment]
Can you first try some support channels like I asked? Thanks
