### ISSUE TITLE
Expected response code 250 but got code "554", with message "554 Message rejected | Laravel Using TO Email

### ISSUE THREAD

**Issue by maqsudinamdar** [laravel/framework#36923]
- Laravel Version: 8.27
- PHP Version `$ php --version`: PHP 8.0.3 (cli)
- Database Driver & Version $ `mysql --version`: mysql  Ver 8.0.23-0ubuntu0.20.04.1
---

**Problem Statement:**

I'm getting **`TO`** email in **`FROM`** email which of course will not be verified in Amazon SES in **`POST`** `password/email`.

---

**Description:**

Let *to@example.com* will ask for Password Reset Link via email. Generally *from@example.com* will send password reset link. However, In my case *to@example.com* is trying to send password reset link to itself.

In Amazon SES we need to verify email to send mail through SES service. So I've verified *from@example.com*.

---

**Exception:**

> Swift_TransportException (554)

> Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region REGION: to@example.com "

---
**Configuration:**

```
$ php artisan route:list
```

```
+--------+----------+-----------------------------------------------+------------------------------------+-------------------------------------------------------------------------------+-------------------------------------------------------+
| Domain | Method   | URI                                           | Name                               | Action                                                                        | Middleware                                            |
+--------+----------+-----------------------------------------------+------------------------------------+-------------------------------------------------------------------------------+-------------------------------------------------------+
|        | POST     | password/email                                | password.email                     | App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail         | web                                                   |
```

`App\Http\Controllers\Auth\ForgotPasswordController.php`

```
namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\SendsPasswordResetEmails;

class ForgotPasswordController extends Controller
{

    use SendsPasswordResetEmails;
```

`vendor\laravel\ui\auth-backend\SendsPasswordResetEmails.php`

```
namespace Illuminate\Foundation\Auth;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;
use Illuminate\Validation\ValidationException;

trait SendsPasswordResetEmails
{
 

    public function sendResetLinkEmail(Request $request)
    {
        $this->validateEmail($request);

        $response = $this->broker()->sendResetLink(
            $this->credentials($request)
        );

        return $response == Password::RESET_LINK_SENT
                    ? $this->sendResetLinkResponse($request, $response)
                    : $this->sendResetLinkFailedResponse($request, $response);
    }
```

`vendor\laravel\framework\src\illuminate\Auth\Passwords\PasswordBroker.php`

```
namespace Illuminate\Auth\Passwords;

use Closure;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Contracts\Auth\PasswordBroker as PasswordBrokerContract;
use Illuminate\Contracts\Auth\UserProvider;
use Illuminate\Support\Arr;
use UnexpectedValueException;

class PasswordBroker implements PasswordBrokerContract
{

    public function sendResetLink(array $credentials, Closure $callback = null)
    {

        $user = $this->getUser($credentials);

        if (is_null($user)) {
            return static::INVALID_USER;
        }

        if ($this->tokens->recentlyCreatedToken($user)) {
            return static::RESET_THROTTLED;
        }

        $token = $this->tokens->create($user);

        if ($callback) {
            $callback($user, $token);
        } else {

            $user->sendPasswordResetNotification($token);
        }

        return static::RESET_LINK_SENT;
    
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
