### ISSUE TITLE
Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found when running migration that change a column

### ISSUE THREAD

**Issue by renoirtech** [laravel/framework#36936]
- Laravel Version: 7.29
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 5.7

### Description:

Folks, im facing `Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found` exception when running `php artisan migrate:fresh --seed` on a project that was shifted from Laravel 6 to 7.

After some research on google about the issue, i've found that some people resolved the problem by downgrading the doctrine/dbal package to version ^2, but i don't feel confortable to do that without a solid explanation.

And even if the solution found on other forums is right, isn't it the case to change the laravel 7 composer.json to require doctrine/dbal ^2?

### Steps To Reproduce:

1. Create a migration that modify a column on a table
2. Run `php artisan migrate:fresh --seed`
3. Exception pops out when the artisan migration command try to run the migration with modifying function

```   Error 

  Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

  at vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:64
    60|      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
    61|      */
    62|     protected function getDoctrineDriver()
    63|     {
  > 64|         return new DoctrineDriver;
    65|     }
    66| }
    67| 

      +8 vendor frames 
  9   database/migrations/2020_02_27_132227_alter_parts_table_change_serial_field_length.php:18
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +32 vendor frames 
  42  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))```
      
      
     Thanks in advance!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
