### ISSUE TITLE
Event assertListening expects both the params to be string

### ISSUE THREAD

**Issue by chaudigv** [laravel/framework#36939]
- Laravel Version: 8.36.2
- PHP Version: 7.4.12

### Description:
I am creating a simple test to make sure verification email is sent upon successful registration. According to [documentaion](https://laravel.com/docs/8.x/mocking#event-fake), I am suppose to use `assertListening`.
e.g.
```
Event::assertListening(
    OrderShipped::class,
    [SendShipmentNotification::class, 'handle']
);
```

### Steps To Reproduce:
```
    public function test_send_verification_email_on_registered_event()
    {
        Event::fake();

        // throws error
        Event::assertListening(Registered::class, [SendEmailVerificationNotification::class, 'handle']);

        // Instead this works. Both the params must be strings
        Event::assertListening(Registered::class, SendEmailVerificationNotification::class);
    }
```

Am I missing something from [void assertListening(string $expectedEvent, string $expectedListener)](https://laravel.com/api/8.x/Illuminate/Support/Testing/Fakes/EventFake.html#method_assertListening)?

**Comment by driesvints** [comment]
Thanks. The example in the docs indeed seems wrong to me. I've sent in a PR to update the docs: https://github.com/laravel/docs/pull/6980
