### ISSUE TITLE
Double-wrapping of resource collections that use with

### ISSUE THREAD

**Issue by Synchro** [laravel/framework#36943]
- Laravel Version: 8.36
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 8

### Description:
I'm running into a problem very much like #22209 and #21650, but slightly different. Like the second of those examples I am using a resource collection that returns a set of resources wrapped in a `data` element, and this is the *only* element returned, so it's really not necessary to wrap it further. I am using pagination, which adds extra top-level metadata, and that's what's discussed in those other tickets. However, if I remove pagination, the problem still occurs, and this seems to be caused by having a `with` method that has a similar effect of adding top-level metadata. If I disable both pagination and the `with` method, the problem goes away. I am also disabling wrapping globally in the json provider, and also calling `withoutWrapping()` on all single resources. I can't see any way out of this: I have a choice of double wrapped data, no wrapping at all, or do without pagination and metadata, none of which are good. How can I avoid this double wrapping the docs promise they will never do? If this isn't the double wrapping that it speaks of, what is?

### Steps To Reproduce:
Code as in #21650, but with this collection:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class CompanyCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request
     * @return array
     */
    public function toArray($request)
    {
        return ['data' => $this->collection];
    }

    public function with($request)
    {
        return ['meta' => ['thing' => 'abc']];
    }
}
```

**Comment by driesvints** [comment]
Adding metadata to a JsonResource seems to always require a wrapping key. That's why disabling of double wrapping here doesn't works. You can, however, still make use of the static `$wrap` property:

```php
class UserCollection extends ResourceCollection
{
    public static $wrap = 'user';

    public function with($request)
    {
        return ['meta' => ['thing' => 'abc']];
    }
}
```

I'll PR the docs which make it more clear that using metadata will always invoke wrapping of the resource.

**Comment by driesvints** [comment]
Actually I've found out that this is already documented here: https://laravel.com/docs/8.x/eloquent-resources#data-wrapping-and-pagination

**Comment by Synchro** [comment]
Yes, that's for pagination, but it also happens if you use `with`, even if you don't use pagination. My main concern is really that a `data` wrapper is added even if there is one present already – would it not make more sense to merge into the existing structure than to blindly wrap it again?

**Comment by driesvints** [comment]
I don't get the double wrapping behavior. Please provide the exact code that causes this.

**Comment by Synchro** [comment]
It's just like in [the first example from the docs](https://laravel.com/docs/8.x/eloquent-resources#writing-resource-collections):

```php
class UserCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'data' => $this->collection,
            'links' => [
                'self' => 'link-value',
            ],
        ];
    }
```

If I add a `with` method, as above, to this collection class it will result in double-wrapping of the `data` element.

I can avoid it in simple cases like this, which adds a data wrapper and behaves when using `with`:

```php
public function toArray($request)
    {
            return UserResource::collection($this->collection),
    }
```
But if I need to create my own `data` element, it will always result in double-wrapping. At the moment the only solution seems to be to never create your own `data` element, and always use `with` to add extra top-level metadata.

**Comment by driesvints** [comment]
```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class UserCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'data' => $this->collection,
            'links' => [
                'self' => 'link-value',
            ],
        ];
    }

    public function with($request)
    {
        return ['meta' => ['thing' => 'abc']];
    }
}
```

This gives me:

```json
{
  "data": [
    {
      "id": 1,
      "name": "Stacy Herzog",
      "email": "margarita80@example.org",
      "email_verified_at": "2021-04-12T13:48:01.000000Z",
      "created_at": "2021-04-12T13:48:01.000000Z",
      "updated_at": "2021-04-12T13:48:01.000000Z"
    },
    {
      "id": 2,
      "name": "Miller Schneider MD",
      "email": "will.camryn@example.net",
      "email_verified_at": "2021-04-12T13:48:01.000000Z",
      "created_at": "2021-04-12T13:48:02.000000Z",
      "updated_at": "2021-04-12T13:48:02.000000Z"
    }
  ],
  "links": {
    "self": "link-value"
  },
  "meta": {
    "thing": "abc"
  }
}
```

**Comment by Synchro** [comment]
OK, thanks for trying it. I have another idea about where the problem may be coming from. In your example, does making this change result in double wrapping?

```php
        return [
            'data' => UserResource::collection($this->collection),
            'links' => [
                'self' => 'link-value',
            ],
        ];
```

I'm not entirely clear where I should use `UserResource::collection($this->collection)` vs just `$this->collection`.

**Comment by Synchro** [comment]
Oh. I guess you may not have a `UserResource` class defined.

**Comment by driesvints** [comment]
Ah sorry, I tried with the collection class. Using `UserResource` gives the same JSON payload as above.

**Comment by Synchro** [comment]
Oh well. Now I'm even more confused! I'll persevere and see if I can figure it out. Thanks very much for trying.
