### ISSUE TITLE
RequiredIf validator with multiple values fails validating boolean 0

### ISSUE THREAD

**Issue by Norgul** [laravel/framework#36952]
- Laravel Version: 8.36.2
- PHP Version: 7.4.1
- Database Driver & Version: not related to the issue

### Description:

Since `boolean` [validation rule](https://laravel.com/docs/8.x/validation#rule-boolean) accepts and validates several boolean value variants I wanted to enable `required_if` validator to accept and validate against those values as well, however it fails having `0` as a value.

### Steps To Reproduce:

Correct behavior 1:
```php
// Validation
'some_bool_field' => 'required|boolean',
'check_against_1' => 'required_if:some_bool_field,true',
'check_against_2' => 'required_if:some_bool_field,false',

// Payload
'some_bool_field' => true, // will trigger 'check_against_1'
'some_bool_field' => false, // will trigger 'check_against_2'
```

Correct behavior 2:
```php
// Validation
'some_bool_field' => 'required|boolean',
'check_against_1' => 'required_if:some_bool_field,1',
'check_against_2' => 'required_if:some_bool_field,0',

// Payload
'some_bool_field' => 1, // will trigger 'check_against_1'
'some_bool_field' => 0, // will trigger 'check_against_2'
```

Invalid behavior:
```php
// Validation
'some_bool_field' => 'required|boolean',
'check_against_1' => 'required_if:some_bool_field,1,true',
'check_against_2' => 'required_if:some_bool_field,0,false',

// Payload
'some_bool_field' => true, // will trigger 'check_against_1'
'some_bool_field' => false, // will trigger 'check_against_2'
'some_bool_field' => 1, // will trigger 'check_against_1'

'some_bool_field' => 0, // should trigger 'check_against_2', but triggers both
```

**Comment by driesvints** [comment]
It only triggers `check_against_2` for me:

```php
Validator::make(['some_bool_field' => 0], [
    'some_bool_field' => 'required|boolean',
    'check_against_1' => 'required_if:some_bool_field,1,true',
    'check_against_2' => 'required_if:some_bool_field,0,false',
]);
```

```json
{
  "check_against_2": [
    "The check against 2 field is required when some bool field is 0."
  ]
}

**Comment by Norgul** [comment]
@driesvints for which Laravel version?

Doing exactly what you did:
```php
Route::get('test', function(){
    Validator::make(['some_bool_field' => 0], [
        'some_bool_field' => 'required|boolean',
        'check_against_1' => 'required_if:some_bool_field,1,true',
        'check_against_2' => 'required_if:some_bool_field,0,false',
    ])->validate();
});
```

And the response:
```php
{
    "message": "The given data was invalid.",
    "errors": {
        "check_against_1": [
            "The check against 1 field is required when some bool field is 0."
        ],
        "check_against_2": [
            "The check against 2 field is required when some bool field is 0."
        ]
    }
}
```

**Comment by driesvints** [comment]
@Norgul I get a validation exception for that code. Laravel v8.36.2

**Comment by driesvints** [comment]
![Screenshot 2021-04-12 at 13 24 05](https://user-images.githubusercontent.com/594614/114532926-a0da2d80-9c4d-11eb-9ada-493d2fbe8b15.jpg)

**Comment by driesvints** [comment]
![Screenshot 2021-04-13 at 11 44 34](https://user-images.githubusercontent.com/594614/114532954-a9caff00-9c4d-11eb-81b9-14eb545fdd4a.jpg)

**Comment by Norgul** [comment]
@driesvints you are doing it wrong. You are dumping the current rule only. Run my exact route to reproduce.

**Comment by driesvints** [comment]
I did run your exact code.

**Comment by Norgul** [comment]
@driesvints but you are showing a dump, not a response?

**Comment by driesvints** [comment]
This is the validation exception I get when calling the `validate` method from your code example. In your route example you're not returning anything.

**Comment by Norgul** [comment]
@driesvints Try putting it within `api` routes without dumping, so that you'll get `422` with all error messages.

**Comment by calkeo** [comment]
If you call this within the API middleware with the correct `Accept: application/json` header, then I also receive the validation exception for both `check_against_1` and `check_against_2` when using the string boolean representation i.e. `true/false`.

For example:
```
Validator::make(['some_bool_field' => 0], [
        'some_bool_field' => 'required|boolean',
        'check_against_1' => 'required_if:some_bool_field,true',
        'check_against_2' => 'required_if:some_bool_field,false',
    ])->validate();
```
Returns
```
{
    "message": "The given data was invalid.",
    "errors": {
        "check_against_1": [
            "The check against 1 field is required when some bool field is 0."
        ],
        "check_against_2": [
            "The check against 2 field is required when some bool field is 0."
        ]
    }
}
```

Whereas

```
Validator::make(['some_bool_field' => 0], [
        'some_bool_field' => 'required|boolean',
        'check_against_1' => 'required_if:some_bool_field,1',
        'check_against_2' => 'required_if:some_bool_field,0',
    ])->validate();
```
Returns
```
{
    "message": "The given data was invalid.",
    "errors": {
        "check_against_2": [
            "The check against 2 field is required when some bool field is 0."
        ]
    }
}
```

However, the behaviour is different when running PHP 8 vs PHP 7.4. PHP 8 correctly evaluates the string values `true/false` as booleans, whereas 7.4 does not.

**Comment by driesvints** [comment]
I can indeed confirm that the difference in PHP version was the culprit. This seems like another regression introduced by https://github.com/laravel/framework/pull/36504 and related to https://github.com/laravel/framework/issues/36540. 

I've attempted a fix here: https://github.com/laravel/framework/pull/36967
