### ISSUE TITLE
Invalid Json in request Does not call custom validation rule also passes the validation and Controller method is called

### ISSUE THREAD

**Issue by bhaveshdaswani93** [laravel/framework#36957]
- Laravel Version: 8.35.1
- PHP Version: 7.4.11
- Database Driver & Version: not related to the issue

### Description:
Validation passes if an invalid value is provided.  I am validating Json using custom rule and passing invalid JSON by pass the validation and hit the controller method. Instead, it should  through validation exception or some kind but the controller method should not be reached

### Steps To Reproduce:
We will try to check that a JSON passes name attribute and is not empty
1. Create Form Request
```
public function rules()
{
    return [
        'json_check' => [new CheckJsonRule()]
   ];
}
```

2. Create custom rule

```
public function passes($attribute,$value) {
    if(!array_key_exists('name',$value)) {
        return false;
   }
    if(empty($value['name'])) {
       return false;
   }   
 
   return true;
}

```

3. Passing Data

Correct behavior 1:

Pass valid JSON (Postman)
This will pass the validation

 ```
{
    "json_check":{"name":"john"}
}
```

Correct behavior 2:

This will fail the validation and will through validation exception

 ```
{
    "json_check":{}
}

```

Invalid behavior:

This will pass the validation, the problem appears here

 ```
{
    "json_check":{"age:26,}
}

```

The above is invalid JSON and it will not call the custom rule and it will directly call the controller method
I would like to have an exception raised and skip the call to the controller method

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bhaveshdaswani93** [comment]
Thanks, @driesvints 
I had debugged (using xdebug) the code and it appears to be an issue let me provide you exact code from the framework that I identified

```
/**
     * Validate a given attribute against a rule.
     *
     * @param  string  $attribute
     * @param  string  $rule
     * @return void
     */
    protected function validateAttribute($attribute, $rule)
    {
        $this->currentRule = $rule;

        [$rule, $parameters] = ValidationRuleParser::parse($rule);

        if ($rule === '') {
            return;
        }

        // First we will get the correct keys for the given attribute in case the field is nested in
        // an array. Then we determine if the given rule accepts other field names as parameters.
        // If so, we will replace any asterisks found in the parameters with the correct keys.
        if (($keys = $this->getExplicitKeys($attribute)) &&
            $this->dependsOnOtherFields($rule)) {
            $parameters = $this->replaceAsterisksInParameters($parameters, $keys);
        }

        $value = $this->getValue($attribute);

        // If the attribute is a file, we will verify that the file upload was actually successful
        // and if it wasn't we will add a failure for the attribute. Files may not successfully
        // upload if they are too large based on PHP's settings so we will bail in this case.
        if ($value instanceof UploadedFile && ! $value->isValid() &&
            $this->hasRule($attribute, array_merge($this->fileRules, $this->implicitRules))
        ) {
            return $this->addFailure($attribute, 'uploaded', []);
        }

        // If we have made it this far we will make sure the attribute is validatable and if it is
        // we will call the validation method with the attribute. If a method returns false the
        // attribute is invalid and we will add a failure message for this failing attribute.
        $validatable = $this->isValidatable($rule, $attribute, $value);

        if ($rule instanceof RuleContract) {
            return $validatable
                    ? $this->validateUsingCustomRule($attribute, $value, $rule)
                    : null;
        }

        $method = "validate{$rule}";

        if ($validatable && ! $this->$method($attribute, $value, $parameters, $this)) {
            $this->addFailure($attribute, $rule, $parameters);
        }
    }
```

This is the code that get hits  and the exact variable is $validatable whose value is false and that's why it does not call the custom validator. To be more specific this is the code I am talking about

```
// If we have made it this far we will make sure the attribute is validatable and if it is
        // we will call the validation method with the attribute. If a method returns false the
        // attribute is invalid and we will add a failure message for this failing attribute.
        $validatable = $this->isValidatable($rule, $attribute, $value);

        if ($rule instanceof RuleContract) {
            return $validatable
                    ? $this->validateUsingCustomRule($attribute, $value, $rule)
                    : null;
        }
```

I think you should give it a time instead of redirecting me to stackoverflow
