### ISSUE TITLE
Unresolvable dependency resolving in Illuminate\Database\Migrations\MigrationCreator

### ISSUE THREAD

**Issue by nestesitio** [laravel/framework#36954]
- Laravel Version: 8.36.0
- PHP Version: 7.3.27-9
- Database Driver & Version:

### Description:
With any php artisan command ou composer command i get
In Container.php line 1064:
                                                                                                                                          
  Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator 

### Steps To Reproduce:
php artisan migrate or composer dump-autoload

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nestesitio** [comment]
Hi https://github.com/driesvints but it seems to me that is a bug in package files.
I solved it temporarily in the Illuminate\Database\Migrations\MigrationCreator file by addding default value in constructor method:
public function __construct(Filesystem $files, $customStubPath = null)
    {
        $this->files = $files;
        $this->customStubPath = $customStubPath;
    }
