### ISSUE TITLE
A key is stored correctly in the session file, but the same key cannot be obtained!!!!

### ISSUE THREAD

**Issue by enaeim** [laravel/framework#36951]
- Laravel Version: 6.20.22
- PHP Version: 7.3.24

### Description:
I saved a key value correctly in the session file. But I can not get the same key.

### Steps To Reproduce:
I use the file driver for my session:
```php
return [
    'driver' => env('SESSION_DRIVER', 'file'),
    'files' => storage_path('framework/sessions'),
]
```

I used the following way to save the key value  in the session:
```php
$request->session()->put('state', Str::random(40));
```

I get session id = `QRTa6JTe5zNduQocU6MLTAxclZr7m3QL54geyazs`

Content of `storage/framework/sessions/QRTa6JTe5zNduQocU6MLTAxclZr7m3QL54geyazs` file:
`a:4:{s:6:"_token";s:40:"xrS4N0IGghaS5DGjg9nIUNuAVoYmg6gq3DPwOfjx";s:9:"_previous";a:1:{s:3:"url";s:28:"http://my-site.com/login";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}s:28:"state";s:40:"drA3BGZY0Sg3w2MKx5p22o5s4biAt1Vzi0zhAM89";}`

I printed the all contents of the session:
```php
dd($request->session()->all());
```
result:
```
array:3 [
    "_token" => "xrS4N0IGghaS5DGjg9nIUNuAVoYmg6gq3DPwOfjx"
    "_previous" => array:1 [
        "url" => "http://my-site.com/login"
    ]
    "_flash" => array:2 [
        "old" => []
        "new" => []
    ]
]
```
or
```php
dd($request->session()->pull('state'));
dd($request->session()->get('state'));
```
result: `null`

While in the contents of the session file it is clear that there is the 'state' key and its value.

### Please help me how to solve this problem.
Thanks.

**Comment by driesvints** [comment]
Works fine for me. Remember that `pull` will get and remove the `state` key.

```php
Route::get('/', function (Request $request) {
    $request->session()->put('state', Str::random(40));

    return view('welcome');
});

Route::get('/test', function (Request $request) {
    return [
        $request->session()->all(),
        $request->session()->get('state'),
        $request->session()->pull('state'),
    ];
});
```

![Screenshot 2021-04-12 at 13 24 05](https://user-images.githubusercontent.com/594614/114387177-6d869880-9b92-11eb-9765-e9fe37261a7e.jpg)
