### ISSUE TITLE
Add validation error messages to new rules like prohibited and prohibited_unless, problem with :value

### ISSUE THREAD

**Issue by Farhan25** [laravel/framework#36965]
- Laravel Version: 8.36.2
- PHP Version: 7.4.13
- Database Driver & Version:

### Description:
add an error message to return when one of the new validation rules is fired, currently this is happening:
```
{
    "message": {
        "image_text": [
            "validation.prohibited"
        ]
    }
}
```

### Steps To Reproduce:
add new elements to validation translation array, like below for prohibited:
```
'prohibited' => 'The :attribute field is prohibited.',
```
It works for prohibited rule but I fail to implement it for prohibited_unless because :value is not solved through the message, I tried adding the below line to validation translation array:
```
'prohibited_unless' => 'The :attribute field is prohibited unless :other is :value.',
```
But it when it's fired, it returns something like this:
```
"image_text": [
            "The image text field is prohibited unless type is :value."
        ]
```

**Comment by driesvints** [comment]
https://github.com/laravel/laravel/blob/8.x/resources/lang/en/validation.php#L107

**Comment by Farhan25** [comment]
@driesvints Thanks for the quick reply! I appreciate it.
