### ISSUE TITLE
withoutOverlapping() does not always delete mutex 

### ISSUE THREAD

**Issue by halaei** [laravel/framework#36964]
- Laravel Version:  6.20.22
- PHP Version: 7.4.15
- Database Driver & Version: MySql 8
- Cache Driver: Redis

### Description:
In production, I found that scheduled commands with `withoutOverlapping()` wasn't running. For some reason, the mutex for those commands was not deleted. So I manually deleted them from cache:
```php
cache::forget($schedule->...->withoutOverlapping()->mutextName());
```
It will be great if someone detects the cause and fixes it so it never happens anymore. Meanwhile, I wonder if you can add some output like this to `schedule:run` command:

```
The artisan command `do:something` is skipped because it is overlapping with another running command. If the command is not running anymore, run "php artisan cache:forget framework/schedule-bad0552359181e1a787a47daa08c9100e45011fa" to delete the mutex. The overlapping will be automatically deleted after 4 hours and 24 minutes.
```

### Steps To Reproduce:
I don't know what causes the issue and how often does this happen.

**Comment by driesvints** [comment]
Clear your cache before deploying your new scheduled commands.

**Comment by halaei** [comment]
@driesvints I don't get your point. Why should I clean my cache on deploy. I have millions of other records in the cache?

**Comment by halaei** [comment]
Also I haven't add any scheduled commands to this project for months.

**Comment by driesvints** [comment]
Sorry, I misunderstood this. Can you please share your scheduler code?

**Comment by halaei** [comment]
Sure. I just obfuscated some class/function names:
```php
    protected function schedule(Schedule $schedule)
    {
        $schedule->call(function ()
        {
            SomeClass::someFunction();

        })->hourly();
        $schedule->command(CacheAdsData::class)->everyFiveMinutes()->runInBackground()->withoutOverlapping();
        $schedule->command(CountMembers::class)->everyMinute()->runInBackground()->withoutOverlapping();
        $schedule->command(IndexAudio::class)->everyMinute()->runInBackground()->withoutOverlapping();
        $schedule->command(MigrateTracks::class)->everyMinute()->runInBackground()->withoutOverlapping();
        $schedule->command(NoQueryBroadcast::class)->everyMinute()->runInBackground()->withoutOverlapping();
        $schedule->command(InactiveBroadcast::class)->everyMinute()->runInBackground()->withoutOverlapping();

        $schedule->command(MapAudios::class,['--continue'])->everyFiveMinutes()->runInBackground()->withoutOverlapping()->between('22:30', '5:30');
        $schedule->command(CacheCharts::class, ['--aggregate'])->hourlyAt(30)->runInBackground()->withoutOverlapping();

        $schedule->command(CleanupDatabase::class, ['--all'])->dailyAt('04:04')->runInBackground()->withoutOverlapping();
        $schedule->command('horizon:snapshot')->everyFiveMinutes();
        $schedule->command(RefreshContextImages::class)->hourlyAt(19);
        $schedule->command(ScanAll::class, ['--something'])->dailyAt('00:12')->withoutOverlapping(60 * 24 * 3);
    }
```

**Comment by halaei** [comment]
The commands used to be in signature string format. I changed them to class format today to see if it fixes my problem. It didn't. The mutext names seems to be the same as before.

**Comment by driesvints** [comment]
I'm sorry @halaei but this seems very specific to you. We haven't gotten any other reports on it and thus I don't want to spend tons of time to debug this. Even more so because there are no steps to reproduce this. Feel free to send in a PR if you can figure out what's going wrong.

**Comment by AbdelElrafa** [comment]
I haven't dug too deep into this yet, but it looks like when a job is marked to run in the background, the `withoutOverlapping` muted doesn't get cleared until it expires. 

Don't know what the solution is yet, but just putting this here for anyone else that runs into this.
