### ISSUE TITLE
Migrating to DB with ssl enabled

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#36989]
- Laravel Version: 8.37.0
- PHP Version: 7.3.27
- Database Driver & Version: MYSQL 5.7.33

### Description:
When I try to migrate new database from dump created from laravel i get this error
In my database configuration I have added  PDO::MYSQL_ATTR_SSL_CA and is working properly... 
It seems that process for loading dump it doesn't take SSL from config and add parameters like --ssl-ca --ssl-capath
```
 Symfony\Component\Process\Exception\ProcessFailedException: The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.

Exit Code: 1(General error)

Error Output:
================
ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.
```

### Steps To Reproduce:
Add this to MySQL connection in database connections
```
 'options'        => \extension_loaded('pdo_mysql') ? \array_filter([
                //The path to the SSL certificate authority.
                PDO::MYSQL_ATTR_SSL_CA     => env('MYSQL_ATTR_SSL_CA', storage_path('certs/BaltimoreCyberTrustRoot.crt.pem')),
                //The path to the directory with the trusted SSL CA certificates, in PEM format.
                PDO::MYSQL_ATTR_SSL_CAPATH => env('MYSQL_ATTR_SSL_CAPATH', storage_path('certs'))
                ]
```
Run artisan command to dump database and run command to migrate db...

**Comment by driesvints** [comment]
We can't control how you dump your database I'm afraid.

**Comment by mariosvasiliou** [comment]
@driesvints Hello, actually is not how i dump it... you didn't understand well.
This is problem with laravel artisan commands.
Run laravel artisan command for schema dump...
Add SSL options to database configurations... all serious applications are using SSL for communication with SQL servers.
Run laravel artisan command for migrate...
It will fail because laravel command MigrateCommand is using MySqlSchemaState which does not add correct parameters for migrating the database from the dump which is created and this is an issue with the framework because customers cannot migrate using laravel command.
I am disappointed how quickly you close the tickets without even investigate the issues the past year...
I know you are  having a lot of requests but at least check it out before closing the ticket.
Thanks

**Comment by driesvints** [comment]
This seems like a very specific use case to you. Feel free to send in a PR if you think something is broken 👍
