### ISSUE TITLE
use strict comparison for object casting

### ISSUE THREAD

**Issue by christophmayrhofer** [laravel/framework#36984]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: Mysql

I realized that laravel/eloquent does not save my model when I change a column with an object cast like this:

```
$original = '{"test": null}';
$new = '{"test": false}';
```

The reason is that attributes that are casted as an object are evaluated like this (to find out if the record is dirty) in HasAttributes.php::R1577:

```
 } elseif ($this->hasCast($key, ['object', 'collection'])) {
            return $this->castAttribute($key, $attribute) ==
                $this->castAttribute($key, $original);
```

I.e. it uses == to compare the two objects. So the problem can be recreated like this:

```
        $original = '{"test": null}';
        $new = '{"test": false}';

        $originalObject = json_decode($original, true);
        $newObject = json_decode($new, true);

        $original == $new; // false
        $originalObject == $newObject; // true <-- this is what laravel does and therefore thinks there was no change
        $originalObject === $newObject; // false <-- this is what I want (unless there is a reason not to do it)
```

Is there a reason that it compares using == instead of === ? And is there some way to force it to use strict comparison instead?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
