### ISSUE TITLE
Type CustomType already exists

### ISSUE THREAD

**Issue by MeerKatDev** [laravel/framework#37012]
- Laravel Version: 8.37.0
- PHP Version: 7.4.3
- Database Driver & Version: MongoDB 4

### Description:
I cannot run `cache:config` when specifying types in the `register` of `AppServiceProvider`
```
pro@MBP-Macbook lookinglass-backend % php artisan config:cache                 
Configuration cache cleared!

   Doctrine\DBAL\Exception 

  Type App\Casts\CustomJsonObject already exists.

  at vendor/doctrine/dbal/src/Exception.php:120
    116▕     }
    117▕ 
    118▕     public static function typeExists(string $name): self
    119▕     {
  ➜ 120▕         return new self('Type ' . $name . ' already exists.');
    121▕     }
    122▕ 
    123▕     public static function unknownColumnType(string $name): self
    124▕     {

      +2 vendor frames 
  3   app/Providers/AppServiceProvider.php:17
      Doctrine\DBAL\Types\Type::addType("App\Casts\CustomJsonObject", "App\Casts\CustomJsonObject")

      +21 vendor frames 
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
### Steps To Reproduce:
In `AppServiceProvider.php` I'm registering Doctrine types:
```php
    public function register()
    {
        Type::addType(\App\Casts\CustomJsonObject::class, \App\Casts\CustomJsonObject::class);
  ...
        //
    }
```
and I run `php artisan config:cache`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MeerKatDev** [comment]
The app works normally with them, the only problem presents when I run Artisan, and I don't see why it should happen, so that's why I'm filing a bug.
