### ISSUE TITLE
Why is .idea and .vscode added to .gitignore when this is not recommended in Laravel?

### ISSUE THREAD

**Issue by fylzero** [laravel/framework#37017]
Just wondering what the thought behind this is.  Not trying to be a pest.  A co-worker of mine recently tried adding .idea to one of our project .gitignore files and mentioned this as existing in laravel/framework which puts a bit of a hole in my argument.  Should this be removed here?  Or is there a specific reason it is good in this repo?

File in question:
https://github.com/laravel/framework/blob/37ba32dc5f52d261b482815d194fba1476b725a2/.gitignore#L7
https://github.com/laravel/framework/blob/37ba32dc5f52d261b482815d194fba1476b725a2/.gitignore#L8

References to this being a bad practice:
https://github.com/laravel/framework/pull/11790
https://github.com/laravel/framework/pull/28556
https://github.com/laravel/framework/pull/22550

**Comment by driesvints** [comment]
We were tired of removing those files from prs for framework

**Comment by fylzero** [comment]
@driesvints I figured that was the reason but also was curious if there was more to it.  It does feel like that could be said of any project though.  Anyway, I appreciate the quick response!  Thanks!

**Comment by rodrigopedra** [comment]
From git blame I found this:

https://github.com/laravel/framework/pull/19323#issuecomment-303722088
