### ISSUE TITLE
Laravel 7.0.8 http client bug in get query get params

### ISSUE THREAD

**Issue by vitorhugosg** [laravel/framework#37010]
- Laravel Version: 7.0.8
- PHP Version: 7.3.24
- Database Driver & Version:

### Description:

Hello, how is everything?

I was using the new HTTPCLIENT class in laravel 7, however I already tried in the get function to put query params in several ways, and none of them successfully.

Follows images of prints, the code always send without query params.

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/17458174/114953725-6334fa80-9e2f-11eb-8ab0-9f91df5843ff.png)
![image](https://user-images.githubusercontent.com/17458174/114953756-76e06100-9e2f-11eb-9290-d03663c4bcc5.png)
![image](https://user-images.githubusercontent.com/17458174/114953892-cc1c7280-9e2f-11eb-9554-0f8b1d0f368c.png)

**URL:**
![image](https://user-images.githubusercontent.com/17458174/114953850-b444ee80-9e2f-11eb-897a-914c028186d8.png)

**Comment by mfn** [comment]
Laravel 7 isn't supported anymore => https://laravel.com/docs/7.x/releases#support-policy

**Comment by vitorhugosg** [comment]
> Laravel 7 isn't supported anymore => https://laravel.com/docs/7.x/releases#support-policy

Sorry for my ignorance, but do you know where I can get help for this function?
