### ISSUE TITLE
Auth:attempt() fails when a Global Scope has been added to User model

### ISSUE THREAD

**Issue by csimpi** [laravel/framework#37027]
- Laravel Version: 8.35.1
- PHP Version: 7.3
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) 

### Description:
I set a global scope that sets a default `select('id', 'first_name', 'last_name')` on the `User` model. Sensitive user data for example email addresses should not retrieve default.
When I try to log in with `Auth::attempt()` using email and password, it fails (with the right credentials). If I remove the global scope, the login works.

### Steps To Reproduce:

`User.php`

```
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('default', function (Builder $builder) {
            $builder->select('id', 'first_name', 'last_name');
        });
    }
```

`UserController.php` - `login() function`

```
        $credentials = $request->only('email', 'password');
        if ($token = Auth::attempt($credentials)) {

```

### Suggestion
In `UserProvider` the `retrieveByCredentials` function should not respect the global scope, or just use `select('*')`

```
        $query = $this->newModelQuery();
        $query->select('*');
        $query->withoutGlobalScopes();

```

**Comment by driesvints** [comment]
I kind of see your point although I think your practical use case isn't a valid one (using a select statement). I'll discuss this with the team.

**Comment by csimpi** [comment]
@driesvints Yes, I agree. I couldn't make up a better example. If you focus on the question itself and don't care about my case, maybe it's cleaner. 
Basically what I would like to suggest here is, `Auth:attempt` shouldn't care about the User model's scopes, maybe the best would be adding `withoutGlobalScope()` instead of my prev suggestion with `select()`.

BTW: I use a select statement because I felt it the most secure way to make confidential data hidden as much as possible.

**Comment by taylorotwell** [comment]
I couldn't really change this on a patch release - and even if we did change it, it just opens up the door for someone to say it *should* use global scopes. Who would be correct?

**Comment by csimpi** [comment]
@taylorotwell  Yes, this was my question too, maybe this has been worked this way before and somebody reported as a bug. 

I still think **Authorization HAS NOTHING TO DO with scopes** and any other changes on the model, it makes the whole authorization weak, if somebody can change the model some way, they can avoid and hack the authorization too.

Closing this just like this a bit rude BTW

**Comment by driesvints** [comment]
> Closing this just like this a bit rude BTW

I think Taylor just doesn't wants to break somebody else's use case. There's a lot of people using the framework. We need to consider all angles. Since this is how things work atm we won't be changing anything here.

**Comment by csimpi** [comment]
@driesvints I understand but still, I had still something to tell and discuss. What you tell is: - We should not fix the bugs because somebody might use Laravel with the bugs :) Everybody does that and waiting for the fix. So still, this way it's a bit rude, make me feel what the hell I would like to help here... :/

**Comment by driesvints** [comment]
@csimpi maintainers still reserve the privilege of having the final say no matter how short or long a discussion. We have lots of other repositories/projects to handle so we have to mindful of our time. I definitely don't mean to be rude by saying that but that's how it is.

**Comment by csimpi** [comment]
@driesvints Do you call this opensource? This is a dictatorship.
But now I understand, you guys working on Laravel for your own exclusive purpose, not for the community. 
It's OK I'll override these things and do it on my own. If you don't need valuable supporters, I can't help here.
