### ISSUE TITLE
`dispatchSync` always return 0

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#37023]
- Laravel Version: 8.32
- PHP Version: 8

### Description:
`disptachNow()` returns the `handle()` result, But `dispatchSync` only return 0, So if the `disptachNow()`  will be [deprecated](https://github.com/laravel/framework/pull/36834) in future of laravel version, How can i deal with it ?  I need the result of the `handle` method not only 0

```php

$result = MyJob::dispatchSync('input');

// result always is 0

```

**Comment by driesvints** [comment]
Please post your job class.

**Comment by driesvints** [comment]
Just realized you're not actually dispatching a job

**Comment by foremtehan** [comment]
@driesvints try this:

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        dump('dispatched');

        //should return null but instead return 0
    }
}
```

```php
\App\Jobs\TestJob::dispatchSync()
```

The code inside of `handle` method are executed but `dispatchSync` always return 0

**Comment by foremtehan** [comment]
i found the problem:

https://github.com/laravel/framework/blob/24e639cace7929727bb2525b6d3081e6db0bb90c/src/Illuminate/Queue/SyncQueue.php#L36-L51

as you can see it always return 0

**Comment by driesvints** [comment]
You're correct. Even though I personally think jobs shouldn't return anything from their handle method (See the DocBlock). I can see this being problematic for people switching from `dispatchNow`. I'll discuss this with the team.

**Comment by foremtehan** [comment]
Can we just revert the [PR](https://github.com/laravel/framework/pull/36834) ? no need to remove `dispatchNow` we can have both methods

**Comment by SjorsO** [comment]
A possible solution could be to call your job like a normal class:
```php
$result = (new TestJob())->handle();

// or if your job uses dependency injection:

$result = app()->call([TestJob::class, 'handle']);
```

This won't trigger any job-related events though.

**Comment by taylorotwell** [comment]
`dispatchSync` dispatches the job on the sync queue and doesn't return anything by design. If you have a "job" that you need a return value from and to run synchronously, I suggest just making a regular class. Jobs should not return values.

**Comment by francoism90** [comment]
This is really confusion, also see: https://github.com/laravel/framework/issues/37778

It's 2023, and I still need to remove `implements ShouldQueue`, to make `->dispatchSync` to work.

Really weird, why not simple ignore the middlewares?

**Comment by Briareos17** [comment]
> `dispatchSync` dispatches the job on the sync queue and doesn't return anything by design. If you have a "job" that you need a return value from and to run synchronously, I suggest just making a regular class. Jobs should not return values.

So, if I need to do same things in queue and also in sync to return with response, I need to make another boilerplate service class to cal lfrom job or from my controller, why?
