### ISSUE TITLE
Database seeder factory does not seed models created in other namespace/dir 

### ISSUE THREAD

**Issue by marvinhosea** [laravel/framework#37038]
- Laravel Version: 8.37.0
- PHP Version: 7.4.16
- Database Driver & Version: MySql

### Description:

I have created a domain namespace where I have all my domains in the root dir eg Domain/User domain.
Inside User domain dir, I have my models (Domain/User/Models). And moved my User model to the Domain/User/Models dir.
When I tried to run DB:seed for my UserFactory, I got this error
```
  Class 'Database\Factories\Domain\User\Models\UserFactory' not found

```

The UserFactory is available in the factory dir.

### Steps To Reproduce:

- Create Domain (or any folder name) in the project root dir.
- Add the Dir as a new namespace. 
```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Domain\\": "Domain/"
```

- Create a domain dir for example User domain and inside the dir create models folder.
- Move user model to the models dir created above
- Update User factory
- Run PHP artisan db:seed

**Comment by marvinhosea** [comment]
I fixed this issue by overriding newFactory function in my model as below

```
protected static function newFactory()
    {
        return CurrencyFactory::new();
    }
```

But I think this should be reviewed and the seeder should be able to seed factories despite their location within the application. 

Because of that, I will leave this issue open but if it does not make sense then feel free to close it.

**Comment by driesvints** [comment]
Your solution is the correct one. The factories expect a specific namespace.
