### ISSUE TITLE
ENV when running a scheduler command

### ISSUE THREAD

**Issue by beez** [laravel/framework#37046]
- Laravel Version: 8.33.1
- PHP Version: 7.3.27
- Database Driver & Version: -

### Description:
I am not using .env for my server environment variables. All works fine in tinker `env('APP_ENV')` and in bash `$APP_ENV`, but when I run a command through schedule `$schedule->command('myCommand')` it doesn't gets the correct environment variables. After I use `artisan config:cache` it works as intended.

I think Schedule should use the server's environment variables as the application does when no .env file is present. It feels weird and buggy that they works differently.

### Steps To Reproduce:
See description above

**Comment by driesvints** [comment]
Works fine for me:

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class FooCommand extends Command
{
    protected $signature = 'foo-command';

    protected $description = 'Command description';

    public function handle()
    {
        logger(env('APP_NAME'));

        return 0;
    }
}
```

```php
<?php

namespace App\Console;

use App\Console\Commands\FooCommand;
use App\Jobs\FooJob;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        FooCommand::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('foo-command')->everyMinute();
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
```

`php artisan schedule:run`

![Screenshot 2021-04-19 at 16 28 48](https://user-images.githubusercontent.com/594614/115253169-68928d80-a12c-11eb-916a-646cfb88cd90.jpg)

**Comment by beez** [comment]
Thank you for your swift reply. I missed to write that is with the use of config(), where config in turn uses env().
