### ISSUE TITLE
Cannot use queued job properties other than the ones it's serialized with in `failed` method

### ISSUE THREAD

**Issue by nikazooz** [laravel/framework#37043]
- Laravel Version: 8.21.0 (but any really)
- PHP Version: 7.4.14
- Database Driver & Version: PostgreSQL 12

### Description:
When queued job fails, we can do something using `failed` method in the job class. We can use job instance properties, but only with values the job had when serialized. So if we've updated a property in the `handle` method we cannot use the updated value when handling failure.

### Steps To Reproduce:

1. Create an example job class:
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class ExampleJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $number = 0;

    public function handle()
    {
        foreach (range(1, 10) as $number) {
            $this->number = $number;

            if ($number === 5) {
                $this->fail();
            }
        }
    }

    public function failed()
    {
        Log::debug($this->number);
    }
}
```
2. Dispatch the job
3 Inspect the log, it will show something like `[2021-04-19 09:49:38] local.DEBUG: 0`

**Expected:** I'd expect to see "5" in the log and not "0"

I've found an earlier issue https://github.com/laravel/framework/issues/30739#issuecomment-562238460 but the question was not answered. Is this a bug or intended behavior, and if so why? If it is intended behavior it should be documented. I'll gladly submit a PR to docs if so.

Thanks in advance,
Cheers!

**Comment by driesvints** [comment]
This is by design.

**Comment by driesvints** [comment]
Welcoming PR's 👍

**Comment by nikazooz** [comment]
@driesvints Is a PR to make it possible to do also welcome? 🙂

**Comment by driesvints** [comment]
You can always try but Taylor reviews PRs, not me.

**Comment by glmdev** [comment]
I ran into this while trying to add a generic helper that will delete temp files created while the job was running. (e.g. the job runs and temp files are stored in an array on the job instance, however that array was obviously empty when the `failed` method was called, causing files to be left behind)

A convenient way to accomplish this can be done using the `__destruct` method of the job. Something like:

```php
class MyJob {
    use InteractsWithQueue;

    function __destruct() {
        if ( !is_null($this->job) ) {  // Only do cleanup if the job was created by CallQueuedHandler
            $this->cleanup();
        }
    }

    protected function cleanup() { /* ... */ }
}
```
