### ISSUE TITLE
Environment variables in Config not used by Scheduled Command

### ISSUE THREAD

**Issue by beez** [laravel/framework#37049]
I've filed this earlier today, but that one got closed before I could clarify the case properly. I'm trying agin with a full reproducible example.

- Laravel Version: 8.33.1
- PHP Version: 7.3.27
- Database Driver & Version: -

### Description:
I am not using a .env file for my server environment variables. All works fine in tinker when using `config('app.foo')`, the config is in turn using `env('FOO')` like the example below. When I on the other hand run it as a command from the schedule, like the code below the outcome is different, the server environment variable is not being used. After I run `php artisan config:cache` it works as intended (the server env variable is being used by the scheduled command through config).

As you can see in my example below there is a difference if config is cached or not. I think Schedule should use the server's environment variables as the application does when no .env file is present. It feels weird and buggy that they (command and schedule) works differently.

### Steps To Reproduce:
```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class FooCommand extends Command
{
    protected $signature = 'foo-command';

    protected $description = 'Command description';

    public function handle()
    {
        logger(config('app.foo'));

        return 0;
    }
}
```
---------------
```
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use App\Console\Commands\FooCommand;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        FooCommand::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('foo-command')->everyMinute();
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
```
---------------
config/app.php
```
return [
    'foo' => env('FOO', 'FooBar'),
];
```
---------------
Environment variable
```
FOO="Bar"
```
---------------
$ php artisan config:clear
local.DEBUG: FooBar

$ php artisan config:cache
local.DEBUG: Bar

---------------
$ php artisan config:clear
$ php artisan foo-command
local.DEBUG: Bar

$ php artisan config:cache
$ php artisan foo-command
local.DEBUG: Bar

**Comment by driesvints** [comment]
Hey @beez. I tried again with the exact code from above, and without an `.env` file but with the existing `app.name` config:

```php
APP_NAME=Test php artisan schedule:run  
```

Outputs:

```
[2021-04-20 08:48:18] local.DEBUG: Test  
```

So this seems to work as intended. I don't know why it doesn't for you but I'm afraid we can't help you further. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by beez** [comment]
@driesvints Could you please not close the issue before I have been able to respond.

When I do what you did and execute `php artisan schedule:run` I get one output in my log that says "Test" after that the "everyMinute()" schedule keeps outputting the default value ("FooBar") and not "Test" Could you please have a look in your log?

This is what I got:
```
[2021-04-20 11:06:02] local.DEBUG: FooBar  
[2021-04-20 11:07:02] local.DEBUG: FooBar  
[2021-04-20 11:07:23] local.DEBUG: tuut  
[2021-04-20 11:08:03] local.DEBUG: FooBar  
[2021-04-20 11:09:02] local.DEBUG: FooBar  

```

**Comment by driesvints** [comment]
@beez please try a support channel. I don't think there's a bug here and this issue tracker is only for bug reporting. We don't provide support here, sorry.

**Comment by beez** [comment]
@driesvints It seems like it differs when schedule cron is the one executing `schedule:run` and not manually… I still think it's something that needs to be explored.

**Comment by beez** [comment]
@driesvints Sorry to hear you see this as a support issue. But I'll leave you with it and find a workaround.

**Comment by driesvints** [comment]
@beez if you can identify this as a bug then definitely feel free to report back 👍
