### ISSUE TITLE
JSON contains method not working with URLs

### ISSUE THREAD

**Issue by maicol07** [laravel/framework#37048]
- Laravel Version: 8.37.0
- PHP Version: 8.0
- Database Driver & Version: MariaDB 10.3.25

### Description:
The `whereJsonContains` method of the database builder does not work if the value is an URL.
I think the issue here is that Laravel doesn't add the required quotes (`"`) at the beginning and at the end of the URI.

### Steps To Reproduce:
1. Create a table with a JSON field
2. Populate the JSON field with a JSON array (example: `["a","b","https://laravel.com"]
3. Try the following statements (`$db` must be an instantiated DB call, such as `DB::table('db_table')`:
```php
DB::enableQueryLog();
$res1 = $db->whereJsonContains($query, 'a')->get();
$res2 = $db->whereJsonContains($query, 'https://laravel.com')->get();
$res3 = $db->whereRaw("JSON_CONTAINS(`$query`, '\"https://laravel.com\"')")->get()
dd(DB::getQueryLog(), $res1, $res2, $res3);
```
4. Notice how the first statement worked, the second no, and the third worked

**Comment by staudenmeir** [comment]
You need to escape the slashes because `whereJsonContains()` runs the value through `json_encode()`: `"https:\/\/laravel.com"`

**Comment by maicol07** [comment]
> You need to escape the slashes because `whereJsonContains()` runs the value through `json_encode()`: `"https:\/\/laravel.com"`

The escaped string works in the raw statement like the non escaped one. What changes are the quotes

**Comment by staudenmeir** [comment]
> I think the issue here is that Laravel doesn't add the required quotes (") at the beginning and at the end of the URI.

`whereJsonContains()` does add the quotes, they are coming from `json_encode()`.

**Comment by staudenmeir** [comment]
How do you mean? The issue are the unescaped slashes. `whereJsonContains()` works best/only with JSON values that got encoded and inserted by Laravel.

**Comment by driesvints** [comment]
Hey @maicol07. Please see the responses by @staudenmeir above.

**Comment by maicol07** [comment]
Seems that the value in the DB must be escaped as well to get it work
