### ISSUE TITLE
Bug in Http Client after multiple requests

### ISSUE THREAD

**Issue by Sergiobop** [laravel/framework#37047]
- Laravel Version: 8.37.0
- PHP Version: 7.4.14
- Database Driver & Version: postgres (PostgreSQL) 12.3

### Description:
I'm using a public API to fill my database (Example route: https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1).
When i do multiple requests, the Laravel HTTP Client fails (at the time, is failing after 79 successful requests)
When i change the Http Client to use Guzzle, the error does not happen.

### Steps To Reproduce:
I created a simple and fast custom method to reproduce the bug:
```
 $calls = 0;
 for ($i = 0; $i <= 500; $i++) {
       try {
            $request = Http::get("https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1")->throw();
            $calls++;
            echo "$calls\n";
       }  catch (ConnectionException $connectionException) {
            Log::error($connectionException->getMessage());
       }
}
```

It logs after the 79th request:
```
[2021-04-19 15:47:38] local.ERROR: cURL error 6: Could not resolve host: maps.andalucia.org (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1  
```
If i try retrying the request, like this:
```
$request = Http::retry(5, 1000)
                    ->get("https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1")
                    ->throw();
```

It logs:
```
[2021-04-19 15:45:47] local.ERROR: cURL error 6: getaddrinfo() thread failed to start
 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1  
 ```

If i try with Guzzle, the bug does not happen and the loop ends without problems:
```
 $calls = 0;
 for ($i = 0; $i <= 500; $i++) {
       try {
            // using GuzzleHttp\Client
            $request = new Client();
            $response = $request->get("https://maps.andalucia.org/rest-turistico/rest/visit/list?first=0&size=1");
            $calls++;
            echo "$calls\n";
       }  catch (ConnectionException $connectionException) {
            Log::error($connectionException->getMessage());
       }
}
```

**Comment by driesvints** [comment]
Hey @Sergiobop, I don't get the errors with your code. It can handle 500 requests fine without curl errors. So I believe this is specific to your device/network. Please try a support channel as there's nothing we can do ourselves here:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by Sergiobop** [comment]
Thank you for your time @driesvints , but i don't think is a device/network issue, since using guzzle http client instead of the Laravel Facade, gives me no issues. FYI i tested it using a Tinker session.

I changed my code to use the Guzzle client meanwhile. 
Thanks again.

**Comment by driesvints** [comment]
@Sergiobop that might be the problem. I don't think a REPL is suited for such a test. Try it within an actual app instead.

**Comment by crux** [comment]
this is totally bizarre, I can exactly reproduce that bug. Different url, different API, different Header, Params etc, BUT:

After EXACTLY 79 request it fails. With the same curl 6 error message. 

 "laravel/framework", "version": "v8.47.0",
 php --version -> PHP 8.0.3 (cli) (built: Apr 25 2021 08:04:33) ( NTS )
 
 running on a mac osx: Big Sur 11.4
Darwin yoyoto.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64


And I can reproduce that with coding it directly with the guzzle client I have no problem at all. 

Another co-worker, must still check his env, but with his machine the problem doesn't occure. 

I am not running it in REPL. plain PHP artisam command line. So it seems clear to me it is related to the larval layer on top of guzzle in combination with the curl under it. 

to be continued, maybe, if i find time to debug it.

**Comment by crux** [comment]
on this system the bug does not occur:

Linux rog 5.10.41-1-MANJARO #1 SMP PREEMPT Fri May 28 19:10:32 UTC 2021 x86_64 GNU/Linux
