### ISSUE TITLE
when we try to download large files gives out of memory errors

### ISSUE THREAD

**Issue by mrgiant** [laravel/framework#37042]
https://github.com/laravel/framework/blob/cada3d21c7f127ba01bb949b2fa045b7faaedbca/src/Illuminate/Filesystem/FilesystemAdapter.php#L170

Laravel Version: 7.30.4
PHP Version: 7.4.0

**Description:**
we noticed that fpassthru is used in PHP code, which is known to have problems.

we did some test and we able to fetch the pdf file via CURL if specifying the full-path to the static file, but something wrong when we try to fetch the file using the "friendly" URL that goes through the PHP code. In other words, fetching the static file works fine, but going through the PHP code to get the file doesn't. Check below:

Working scenario:

curl -o out.bin -D - --cookie ARRAffinity=c0f955200062b837a8b06271f039c1d9a6aa1309ada101b0e47bf4c23c0ba3a3 "https://example.com/storage/inflight-readings/April2020/JT7e5y4Q4O3AhCPo7VFc.pdf"

 

Not working scenario:

curl -o out.bin -D - --cookie ARRAffinity=c0f955200062b837a8b06271f039c1d9a6aa1309ada101b0e47bf9c93c0ba3a3 --header "Host: www.example.com" "http://ip:8080/gbl/en/inflight-reading/download/ar/Volume-1-2020"

 

So, stop using fpassthru() , you could mitigate by editing the following file:

[/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php]

 ```
$response->setCallback(function () use ($path) {

            $stream = $this->readStream($path);

            fpassthru($stream);

            fclose($stream);

        });
```

**Replace with:**
```
$response->setCallback(function () use ($path) {
            $fp = fopen($path, 'rb');
            while(!feof($fp))
            {
                print(fread($fp, 8192));
            }
            fclose ($fp);
        }); 
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mrgiant** [comment]
Hi There,

We already provide the solution for the issues.



[/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php]

```
$response->setCallback(function () use ($path) {

           $stream = $this->readStream($path);

           fpassthru($stream);

           fclose($stream);

       });
```
**Replace with:**

```
$response->setCallback(function () use ($path) {
            $fp = fopen($path, 'rb');
            while(!feof($fp))
            {
                print(fread($fp, 8192));
            }
            fclose ($fp);
        }); 
```
