### ISSUE TITLE
WasChanged return false - in case it should return true

### ISSUE THREAD

**Issue by georgenis** [laravel/framework#37041]
- Laravel Version: 8.25.0
- PHP Version: 7.4
- Database Driver & Version: MariaDB

### Description:
I updated a model, but the wasChanged method returns false. In this case the given attribute was changed. Check out the reproduce steps...

### Steps To Reproduce:
1. Save a model 
2. Update change the property but dont save 
3. Call 'wasChanged(attribute)'
4. It returns false (I expected true)

### Code
...Query Model...
$dp->name = $request->input('name');
$dp->net_price = $request->input('net_price');
$stripePrice = $stripeHelper->findDPrice($dp->price_stripe_id);
\Log::debug($dp->net_price);
\Log::debug($dp->getOriginal('net_price'));
\Log::debug($request->input('net_price'));
\Log::debug($dp->wasChanged('net_price') ? 't' : 'f');

### Log
[2021-04-19 06:40:17] local.DEBUG: 25.00  
[2021-04-19 06:40:17] local.DEBUG: 24  
[2021-04-19 06:40:17] local.DEBUG: 25.00  
[2021-04-19 06:40:17] local.DEBUG: f

**Comment by themsaid** [comment]
use `isDirty()` instead.

`hasChanged()` checks if a saved model has changed. Your model wasn't saved.
