### ISSUE TITLE
WithoutOverlapping Job Middleware does not release lock on failed jobs

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/framework#37060]
- Laravel Version: 8.37.0
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 8.0.21

### Description:
I have noticed strange behavior after we started to use the new WithoutOverlapping middleware that was introduced in 8.11. The setup is that we are running three horizon workers using one redis instance. We use same id for different jobs, but I looked and the middleware seems to create a job aware key for each. After we added the middleware we started to notice strange problems with failed jobs.

Biggest issue is that jobs are not picked up by the queue worker. The workers are running and the job just sit there. Sometimes flushing the redis database helps with this issue. So I am guessing the middleware thought that the job is running and releasing it over and over again? I've also noticed that might be certain keys that are permanently locked, since other jobs triggered in the same time are processed normally.

Is there any way to debug this, because this middleware would be exactly what we would need. Should I try manually setting the expireAfter so that the lock would be released?

### Steps To Reproduce:

Use the WithoutOverlapping middleware without expireAfter and generate some failed jobs. By theory is that the lock is never released.

**Comment by paras-malhotra** [comment]
> We use same id for different jobs, but I looked and the middleware seems to create a job aware key for each.

This is the expected behaviour. This middleware is meant to eliminate job overlaps for the same job class, and isn't meant to be used across different job classes. If there are 2 jobs of the same class, it will generate the same lock key.

> My theory is that the lock is never released.

Can you provide some steps on how to reproduce this? I'm curious to know how you're failing a job - exception, timeout?

**Comment by lasselehtinen** [comment]
> This is the expected behaviour. This middleware is meant to eliminate job overlaps for the same job class, and isn't meant to be used across different job classes. If there are 2 jobs of the same class, it will generate the same lock key.

Just so that I understood correctly, if I have JobOne and JobTwo both having the exact same key passed ($this->model->id) to the middleware, is it OK or will they collide? If yes, that would probably be solved by adding something class specific to the key like 'JobOne' . $this->model->id?
 
> > My theory is that the lock is never released.
> 
> Can you provide some steps on how to reproduce this? I'm curious to know how you're failing a job - exception, timeout?

I am not sure which one is it exactly as we are getting both normal exceptions and the ones thrown by Laravel, like the MaxAttemptsExceededException. I guess this would be testable by creating a job with middleware that throws an exception immediately and then you dispatch another job with the same key.

I tried to look at the middleware and could not find anything related to releasing the lock failed jobs, so I just assumed that it does not release the lock automatically when the job fails. Is my theory correct?

If that is the case, I guess there are two options. Adding the expireAfter which would be the same as the max timeout for the job. Another option would that the jobs failed() method would release the lock. I am not sure if this is actually something that should be on by default? I guess it depends if you want the jobs to processed exactly the same order that they came in.

**Comment by paras-malhotra** [comment]
> if I have JobOne and JobTwo both having the exact same key passed ($this->model->id) to the middleware, is it OK or will they collide
They won't collide. The FQCN is appended to the key [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Middleware/WithoutOverlapping.php#L139).

> I tried to look at the middleware and could not find anything related to releasing the lock failed jobs, so I just assumed that it does not release the lock automatically when the job fails. Is my theory correct?

The lock is released when an exception happens in the job. My guess is your job timed out and that's why the lock wasn't released. Here's the code for releasing the job after the job executes:

https://github.com/laravel/framework/blob/597f5ab16d0d2df67e50fedfd2fa66789b29998c/src/Illuminate/Queue/Middleware/WithoutOverlapping.php#L65-L77

So, if an exception is thrown, the finally block releases the lock.

**Comment by lasselehtinen** [comment]
Thanks for the clarification about the id, so that was not causing the issue.

I did not catch the logic with the try finally block, it makes sense now. Yes we had some of those jobs throw the MaxAttemptsExceededException. We have long running jobs doing some encoding and sometimes the external APIs are finicky. So could it be that with the MaxAttemptsExceededException the lock is never released for that job and id combination? Just a reminder that releaseAfter and expiresAfter are not defined in the middleware, so both are 0.

So I just need to set those and the problem would be solved? Only negative side is that you have wait until the job expires. In this case it is quite long but that is acceptable.

**Comment by driesvints** [comment]
Glad this one got figured out. We always appreciate PR's to the docs if things can be clarified further 👍

**Comment by paras-malhotra** [comment]
@lasselehtinen yes, if the issue is caused by job timeouts, I recommend setting a lock timeout equal to your job timeout (maybe 1 second higher to be safe). That should solve the issue.

**Comment by lasselehtinen** [comment]
Yeah this probably should be clarified in the documentation. I will make PR. I was thinking, if no releaseAfter is defined, would it make sense that it would always be the same as the timeout for the job? Like as a sensible default?

**Comment by paras-malhotra** [comment]
@lasselehtinen, yeah I agree. A clarification note in the docs would really help. I don't think the default should be set as the timeout + 1 sec. Firstly, finding the timeout itself is going to be a pain (can be defined at the job or queue level). 

Also, this would only be an issue if the job is susceptible to timeouts (maybe jobs that call unstable APIs). In general, with reliable jobs it shouldn't be an issue. Plus, it's going to be a breaking change if we change the default value.
