### ISSUE TITLE
Allow morph key type other than 'int' or 'uuid' in Schema/Builder

### ISSUE THREAD

**Issue by jonagoldman** [laravel/framework#37067]
- Laravel Version: 8.38.0
- PHP Version: 8.0.1
- Database Driver & Version: MySQL 8.0.23

### Description:
Pull request https://github.com/laravel/framework/pull/34145 added a new `$defaultMorphKeyType` property to the Schema Builder:

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Schema/Builder.php#L42-L47

This is nice, but restricts its usage to `int` or `uuid` only:
https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Schema/Builder.php#L72-L85

I am using the [UID Symfony Component](https://symfony.com/doc/current/components/uid.html#ulids) to generate 26 characters ULIDs,
and would like to have the option to use `char` or `binary` column types too.

Is it possible not to throw an exception when setting other column types? Thanks.

**Comment by rodrigopedra** [comment]
As a workaround, `Blueprint` class is macroable, so you can define new methods without extending it.

For example, add this to your `AppServiceProvider`'s `boot` method:

~~~php
// don't forget to import it
// use Illuminate\Database\Schema\Blueprint;

Blueprint::macro('morphsUlid', function ($name, $indexName = null) {
    // $this inside this closure will refer to the Blueprint instance
    $this->string("{$name}_type");

    $this->char("{$name}_id", 26);

    $this->index(["{$name}_type", "{$name}_id"], $indexName);
});
~~~

Then you can use it in your migrations, like this:

~~~php
$table->morphsUlid('model');
~~~

**Comment by jonagoldman** [comment]
@rodrigopedra Thanks, that's exactly the macro I wrote!
If the morph column type is not used in other parts of the framework then it's not a bug, but if it is used for example when creating tests databases or in Eloquent itself, then it might be.
I'm just not sure where this column definition is being used by the framework.

**Comment by taylorotwell** [comment]
This is a feature request and not a bug.
