### ISSUE TITLE
SoftDeletes Trait Method Doc Error

### ISSUE THREAD

**Issue by dongm2ez** [laravel/framework#37069]
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Database Driver & Version:

### Description:
https://github.com/laravel/framework/blob/fbf25e13b7ce9847fcc336bb3125933638acb936/src/Illuminate/Database/Eloquent/SoftDeletes.php#L9
https://github.com/laravel/framework/blob/fbf25e13b7ce9847fcc336bb3125933638acb936/src/Illuminate/Database/Eloquent/SoftDeletes.php#L107

restore() method with same name already defined in this class，and this function, not a static function.

**Comment by driesvints** [comment]
A PR was already merged
