### ISSUE TITLE
league/flysystem ~1.0 not working with PHP8 and Laravel as S3 Driver for Filesystem

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#37061]
- Laravel Version: v8.38.0
- PHP Version:  PHP 8.0.3
- Sail Version: v1.4.12

### Description:
When trying to add S3 as a Driver for @frankdejonge his package on a PHP 8 versioned app, it results in problems. 
I'm using Sail, that's why composer calls are prefixed with `$ sail`; so it'll be executed inside the container.

### Steps To Reproduce:
I need to add the S3 driver to be added to use via the filesystem. Docs telling to add this package: `league/flysystem-aws-s3-v3 ~1.0`
`$ sail composer require league/flysystem-aws-s3-v3 ~1.0`
This results in:
>  no such user or named directory: 1.0

And when trying it without the `~1.0`:
`▶ sail composer require league/flysystem-aws-s3-v3`
It results in: 
> Using version ^2.0 for league/flysystem-aws-s3-v3
> ./composer.json has been updated
> Running composer update league/flysystem-aws-s3-v3
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - league/flysystem-aws-s3-v3[2.0.0, ..., 2.x-dev] require league/flysystem ^2.0.0 -> found league/flysystem[2.0.0-alpha.1, ..., 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.0.0-RC1] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
>     - Root composer.json requires league/flysystem-aws-s3-v3 ^2.0 -> satisfiable by league/flysystem-aws-s3-v3[2.0.0-alpha.1, ..., 2.x-dev].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ERROR: 2

When trying it outside Sail (it will not work, because I'm running PHP 7.4 and project needs ^8.0:
`composer require league/flysystem-aws-s3-v3 ~1.0
zsh: no such user or named directory: 1.0`
```
▶ composer require league/flysystem-aws-s3-v3     
Using version ^2.0 for league/flysystem-aws-s3-v3
./composer.json has been updated
Running composer update league/flysystem-aws-s3-v3
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/once 3.0.0 requires php ^8.0 -> your php version (7.4.16) does not satisfy that requirement.
    - laravel/nova 3.23.2 requires spatie/once ^1.1|^2.0|^3.0 -> satisfiable by spatie/once[3.0.0].
    - laravel/nova is locked to version 3.23.2 and an update of this package was not requested.
```

**Comment by ankurk91** [comment]
```
sail composer require league/flysystem-aws-s3-v3:~1.0
```

This the correct command.
https://stackoverflow.com/questions/40914114/how-to-install-a-specific-version-of-package-using-composer

**Comment by Jaspur** [comment]
Then the docs are incorrect ;-)
