### ISSUE TITLE
nullable() modifier after the contraints() modifier in migrations not working

### ISSUE THREAD

**Issue by gauravmak** [laravel/framework#37071]
- Laravel Version: 8.37.0
- PHP Version: 8
- Database Driver & Version: MySQL v8

### Description:

The column is not set as `nullable` if the modifier is at the end as per the attached screenshot. And no error is shown when mograting the DB. Moving it before the `constrained()` modifier solved the issue.

### Steps To Reproduce:

Keep `nullable()` modifier at the end as per the red section in the attached image.

![image](https://user-images.githubusercontent.com/11887260/115577067-b997b280-a2e1-11eb-9dc5-30e8e075ec66.png)

**Comment by driesvints** [comment]
This is intended. Please see the docs: https://laravel.com/docs/8.x/migrations#foreign-key-constraints

![Screenshot 2021-04-22 at 10 48 34](https://user-images.githubusercontent.com/594614/115685248-59902300-a358-11eb-919a-9c8a8668248c.jpg)
