### ISSUE TITLE
Validating arrays allows for non validated fields to be present

### ISSUE THREAD

**Issue by BertvanHoekelen** [laravel/framework#37081]
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Database Driver & Version:

### Description:
When validating arrays I expect that only the data that is validated is returned from the `validate()` or `$request->validate()` method.

### Steps To Reproduce:
In the following example I have made myself `super_admin`. I would have expected that the `role` field was ignored. I also don't see another way to enforce this behavior. 

``` php

use Illuminate\Support\Facades\Validator;

$data = [
    'users' => [
        [
            'email' => 'john@example.com',
            'role' => 'super_admin',
        ],
    ],
];

$validator = Validator::make($data, [
    'users' => ['max:5'],
    'users.*.email' => ['required', 'email'],
]);

Users::createMany($validator->validate());
```

Current behavior:
```
[
    "users" => [
        [
            "email" => "john@example.com",
            "role" => "super_admin",
        ],
    ],
]
```

Expected behavior:
```
[
    "users" => [
        [
            "email" => "john@example.com",
        ],
    ],
]
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DanielGSoftware** [comment]
@driesvints Hey Dries, are you sure closing this is the right thing to do? To me this sounds like a more like a bug/security issue, rather than a question for support. The functionality returns unexpected behaviour, and might potentially cause harm to your system, given by Bert's example.

**Comment by driesvints** [comment]
Yeah this is expected. But I see this isn't documented. We'd appreciate PR's to the docs 👍
