### ISSUE TITLE
realpath() expects parameter 1 to be a valid path

### ISSUE THREAD

**Issue by flysion** [laravel/framework#37082]
laravel version: Laravel Framework 5.4.36

The following error occurred during the upgrade of kubernetes-1.12 to kubernetes-1.14:
laravel.log
> [2021-04-22 13:54:41] production.ERROR: LogicException: You must call one of in() or append() methods before iterating over a Finder. in /data/sdkapi_v5.com/appapi/vendor/symfony/finder/Finder.php:564
> Stack trace:
> #0 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(87): Symfony\Component\Finder\Finder->getIterator()
> #1 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(64): Illuminate\Foundation\Bootstrap\LoadConfiguration->getConfigurationFiles(Object(Illuminate\Foundation\Application))
> #2 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\Foundation\Application), Object(Illuminate\Config\Repository))
> #3 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
> #4 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
> #5 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
> #6 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
> #7 /data/sdkapi_v5.com/appapi/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #8 {main}  

php-fpm log
> [22-Apr-2021 13:53:21 Asia/Shanghai] PHP Warning:  realpath() expects parameter 1 to be a valid path, string given in /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 85
> [22-Apr-2021 13:53:21 Asia/Shanghai] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
> Stack trace:
> #0 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('view')
> #1 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('view')
> #2 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('view')
> #3 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('view')
> #4 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make('view')
> #5 /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(148): Illuminate\Contain in /data/sdkapi_v5.com/appapi/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
