### ISSUE TITLE
Broken original $component in compiled views

### ISSUE THREAD

**Issue by saho-tabakov** [laravel/framework#37098]
- Lumen Version: 8.1.1
- PHP Version: 8.0.3
- Database Driver & Version: N/A

### Description:

For compiled blade views, a component will not be properly brought back  (i.e. original restored) in case the next component in row returns `false` from its `shouldRender()` method.

This is an excerpt from `Illuminate\View\Compilers\Concerns\CompilesComponents` trait:

`<?php if (isset($component)) { $__componentOriginal'.$hash.' = $component; } ?>` - Push the **original** component here. 
`<?php $component = $__env->getContainer()->make(...); ?>` - Create the **current** component.
`<?php $component->withName('.$alias.'); ?>`
`<?php if ($component->shouldRender()): ?>` - Determine if **current** is rendable.
...
`<?php if (isset($__componentOriginal'.$hash.')): ?>`
`<?php $component = $__componentOriginal'.$hash.'; ?>` - Will restore the **original** here *only* if **current** was rendable.
`<?php unset($__componentOriginal'.$hash.'); ?>`
`<?php endif; ?>`

`<?php echo $__env->renderComponent(); ?>` 
`<?php endif; ?>`

So at that point `$component` variable holds a reference to the *non-rendable* instead of the **original** component.

### Steps To Reproduce:

This is observable in any compiled blade view containing components.

A very common case will be a sub-menu containing menu-items, where each menu item has a reference to its parent. If you don't want to render an item, for any reason, the next menu-item will get a broken menu reference.

**Comment by driesvints** [comment]
Lumen doesn't supports Blade components. Please use Laravel instead.

**Comment by saho-tabakov** [comment]
It's the same in Laravel, besides @ https://lumen.laravel.com/docs/8.x/views we read:

**There are no differences between using views in Lumen and using views in Laravel; therefore, please consult the full Laravel documentation for usage examples.**

**Comment by saho-tabakov** [comment]
If you check: https://github.com/laravel/framework/blob/8.x/src/Illuminate/View/Compilers/Concerns/CompilesComponents.php, you will see the same code.

**Comment by driesvints** [comment]
Sorry, I was indeed incorrect. Blade Components should work fine.

Please provide the exact code to reproduce this.

**Comment by saho-tabakov** [comment]
> Sorry, I was indeed incorrect. Blade Components should work fine.
> 
> Please provide the exact code to reproduce this.

It's OK. 

The complete code to reproduce it will be quite complex - it has to include at least two components, a blade to use them, a controller class, as well as the compiled view code.

Maybe you can verify the code snippet from my original post.

**Comment by driesvints** [comment]
I'll need code to reproduce this otherwise it's gonna be hard for me to verify it.
