### ISSUE TITLE
Multiple Illuminate\Support\Facades\Validator rules bug

### ISSUE THREAD

**Issue by Pragma-Edragon** [laravel/framework#37100]
- Laravel Version: 
Laravel Framework 8.38.0

- PHP Version: 
PHP 7.4.15 (cli) (built: Feb 20 2021 09:45:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

### Description:
If user will create multiple rules for Validator as an array object and use Validator::make with this rules, user will always receive this error: `The 0 field is required`.

### Steps To Reproduce:
First of all we need to create rules for our Validator:
```php
$rules = array([
            'Email' => 'required|email',
            'lol' => 'required',
            'Password' => 'required|alphaNum|min:3',
            'ConfirmPassword' => 'required|same:Password',
        ]);
```

With this blade inputs: 
```html
<form method="POST">
                    @csrf
                    <input type="text" name="Email" placeholder="Email">
                    <input type="text" name="lol" placeholder="Secret phrase">
                    <input type="password" name="Password" placeholder="Password">
                    <input type="password" name='ConfirmPassword' placeholder="Confirm Password">
                    <input type="submit" name="Submit" value="Register">
                </form>
```

After - Create Validator and input our rules as object:
`$validator = Validator::make($request->input(), $rules);`

You are ready to receive this error!
I tried to switch amount of inputs. Only with 3 named and 1 submit it could work. 

Full code: 
```php
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class RegisterController extends Controller {
    public function CreateIfNotExist(Request $request) {
        switch ($request->method()) {
            case "POST":
                // if method POST and user already registered
                // TODO: need to flash about it.
                $validator = Validator::make($request->all(), [
                    'Email' => 'required|email',
                    'Secret_phrase' => 'required',
                    'Password' => 'required|alphaNum|min:3',
                    'ConfirmPassword' => 'required|same:Password',
                ]);
                if ($validator->fails()){
                    /*
                    return redirect('register')
                        ->withErrors($validator)
                        ->withInput()->exceptInput('Password');
                    */return $validator->errors();
                }
                if (DB::selectOne('SELECT email FROM users WHERE (email = ?)', [$request->input('Email')])) {
                    return "User with this Email already exists";
                } else {
                    // inserting with auto-increment of IDs
                    // using bCRYPT 'cause of Auth::class
                    // needs it by default.
                    DB::table('users')->insertGetId([
                        'email' => $request->input('Email'),
                        'secret' => $request->input('Secret_phrase'),
                        'password' => bcrypt($request->input('Password')),
                        'name' => 'hacker1337',
                        'created_at' => now(),
                        'updated_at' => now()
                    ]);
                }
                // Make flash message here
                return redirect('register');
            case "GET":
                return view('register');
            default:
                // If method is not supported
                // create custom view or idk
                return "Nothing found.";
        }
    }
}
```

My blade template with extension:
```html
@extends('layouts.authbase')

@section('page-title', 'Sign-up')

@section('page-content')
	<div class="login-reg-panel">
		<div class="login-info-box">
			<h2 class="text-bright">Have an account?</h2>
			<p>Lorem ipsum dolor sit amet</p>
			<label id="label-register" for="log-reg-show">Login</label>
			<input type="radio" name="active-log-panel" id="log-reg-show"  checked="checked">
		</div>

		<div class="register-info-box">
			<h2>Already registered?</h2>
			<p>Lorem ipsum dolor sit amet</p>
			<label id="label-login" for="log-login-show">Login</label>
			<input type="radio" name="active-log-panel" id="log-login-show">
		</div>

		<div class="white-panel">
			<div class="login-show">
				<h2>LOGIN</h2>
				<input type="text" placeholder="Email">
				<input type="password" placeholder="Password">
				<input type="button" value="Register">
			</div>
			<div class="register-show show-log-panel">
				<h2>REGISTER</h2>
                <form method="POST">
                    @csrf
                    <input type="text" name="Email" placeholder="Email">
                    <input type="text" name="lol" placeholder="Secret phrase">
                    <input type="password" name="Password" placeholder="Password">
                    <input type="password" name='ConfirmPassword' placeholder="Confirm Password">
                    <input type="submit" name="Submit" value="Register">
                </form>
			</div>
		</div>
	</div>
@endsection
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Pragma-Edragon** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Tbh, I looked all this links (close to) and there are some problems with > 3 values of Validator. So, i gues that's bug and you could reproduce it by yourself...
