### ISSUE TITLE
Bug: resource routing replaces 'ta' with 'um'

### ISSUE THREAD

**Issue by jakback** [laravel/framework#37120]
Hello there devs, today i found out an annoying problem with routing:

Route::resource('dentista', DentistaController::class);

please note the 'ta' at the end of the word

doing a php artisan route:list i get:

GET|HEAD  | dentista                             | dentista.index    | App\Http\Controllers\DentistaController@index     | web
POST           | dentista                            | dentista.store     | App\Http\Controllers\DentistaController@store     | web
GET|HEAD  | dentista/create                 | dentista.create   | App\Http\Controllers\DentistaController@create   | web
GET|HEAD  | dentista/{dentistum}        | dentista.show     | App\Http\Controllers\DentistaController@show     | web
PUT|PATCH | dentista/{dentistum}        | dentista.update | App\Http\Controllers\DentistaController@update  | web
DELETE       | dentista/{dentistum}        | dentista.destroy | App\Http\Controllers\DentistaController@destroy | web
GET|HEAD  | dentista/{dentistum}/edit | dentista.edit       | App\Http\Controllers\DentistaController@edit        | web

notice the replacing of 'ta' with 'um'. That happens with any word that ends in 'ta'

_Originally posted by @netunof in https://github.com/laravel/framework/discussions/37114_

**Comment by driesvints** [comment]
The parameter is the singular form of the name you provide. This is done by the Doctrine Inflector. If you believe this is incorrect please open an issue on their repo.

**Comment by jakback** [comment]
Almost thought so, thanks for clarifying @driesvints.
