### ISSUE TITLE
Collect() only gets last element when collecting from some SimpleXMLElement objects - (Has Workaround)

### ISSUE THREAD

**Issue by x7ryan** [laravel/framework#37126]
- Laravel Version: 8.33.1
- PHP Version: 7.4.16
- Database Driver & Version: N/A

### Description:
When working with some XML strings using PHP's `simplexml_load_string()` I have discovered an issue where only the last element ends up in a collection when using `collect()`.

### Steps To Reproduce:
I have specifically ran into this problem when using an XML response from this one API. For example, take the successful sample XML response found [here](https://api.sedo.com/apidocs/v1/Basic/functions/sedoapi_DomainList.html#example-get).

Assuming that XML is loaded into a string called `$xml` The following will return a collection containing a representation of only the last _<item>_ tag: `collect(simplexml_load_string($xml));` . I have tried with a small simple XML document without issue, for example the same error response in the API doc. So this seems like it might be related to either the size or complexity of the XML perhaps.

NOTE: While the sample XML response contains only 2 items, I can confirm it is showing the last _<item>_ element rather than just ignoring the first by manually adding a third _<item>_ tag, then attempting to collect, in that case I still only see the last _<item>_ element.

#### Workaround:
I have discovered a workaround that I am using for now. If I `json_encode()` then `json_decode()` (either as an array or object) I get the full expected collection. Comparing a dump of the object returned by `simplexml_load_string()` and the object returned by `json_decode()` I can confirm that structurally they look exactly the same except `simplexml_load_string()` has an object type of _SimpleXMLElement_ while `json_decode()` returns a standard PHP object. Therefore I believe it is an issue specifically when working with a _SimpleXMLElement_ object (that is either large and/or complex as noted above) only and for now am resolving by converting to a plain PHP object by using `json_encode()` and `json_decode()` before attempting a `collect()`, specifically using `collect(json_decode(json_encode(simplexml_load_string($xml)), false));`

However in spite of this workaround I felt it appropriate to report this for a proper fix, if possible.

**Comment by driesvints** [comment]
I'm not sure what `simplexml_load_string` has to do with Laravel, sorry.

**Comment by x7ryan** [comment]
The issue is with Laravel's `collect()` method when using `simplexml_load_string()` to make object to be collected. Was that not clear? I sure thought so.

**Comment by driesvints** [comment]
`simplexml_load_string` returns an instance of https://www.php.net/manual/en/class.simplexmlelement.php that isn't usuable with a collection instance.

**Comment by x7ryan** [comment]
It works, inconstantly as noted. Perhaps an exception should be thrown instead so it's clear that shouldn't be done?

**Comment by driesvints** [comment]
`SimpleXMLElement` indeeds implements `Traversable` which is supported by the Collection instance: https://github.com/laravel/framework/blob/7ad5e59a7130143db98d6302a9427fd7dc033062/src/Illuminate/Collections/Traits/EnumeratesValues.php#L929

If that doesn't works it's best that you submit a PR with a failing test that proves it doesn't integrates properly. Although I believe it's probably an issue with `SimpleXMLElement` directly.

**Comment by x7ryan** [comment]
Well I indeed did outline a specific XML string and showed how it returns a partial collection. Which I can get to work correctly, and return the full collection, if I instead encode then decode as json first.

**Comment by driesvints** [comment]
Please provide an exact code snippet for me to reproduce this.

**Comment by x7ryan** [comment]
`Route::get('/xmltest', function () {
    $xml = '<?xml version="1.0" encoding="UTF-8"?>
    <SEDODOMAINLIST ver="1.0">
        <item>
            <domain type="xsd:string">example.com</domain>
            <category>
                <cat1 type="xsd:int">1</cat1>
                <cat2 type="xsd:int">2</cat2>
                <cat3 type="xsd:int">3</cat3>
            </category>
            <forsale type="xsd:int">1</forsale>
            <price type="xsd:double">99.99</price>
            <minprice type="xsd:double">0.00</minprice>
            <fixedprice type="xsd:int">1</fixedprice>
            <currency type="xsd:int">1</currency>
            <domainlanguage type="xsd:string">en</domainlanguage>
        </item>
        <item>
            <domain type="xsd:string">example.net</domain>
            <category>
                <cat1 type="xsd:int">1</cat1>
                <cat2 type="xsd:int">2</cat2>
                <cat3 type="xsd:int">3</cat3>
            </category>
            <forsale type="xsd:int">1</forsale>
            <price type="xsd:double">99.99</price>
            <minprice type="xsd:double">0.00</minprice>
            <fixedprice type="xsd:int">1</fixedprice>
            <currency type="xsd:int">1</currency>
            <domainlanguage type="xsd:string">en</domainlanguage>
        </item>
        <item>
            <domain type="xsd:string">example.org</domain>
            <category>
                <cat1 type="xsd:int">1</cat1>
                <cat2 type="xsd:int">2</cat2>
                <cat3 type="xsd:int">3</cat3>
            </category>
            <forsale type="xsd:int">1</forsale>
            <price type="xsd:double">99.99</price>
            <minprice type="xsd:double">0.00</minprice>
            <fixedprice type="xsd:int">1</fixedprice>
            <currency type="xsd:int">1</currency>
            <domainlanguage type="xsd:string">en</domainlanguage>
        </item>
    </SEDODOMAINLIST>';

    $simple_xml = simplexml_load_string($xml);
    dump($simple_xml);
    $xml_collection = collect($simple_xml);
    dump($xml_collection);
});`

Then visit the xmltest route in your browser. If you compare the two dumps you will see that the collection is incomplete, it only contains the last <item> element in the XML where as the object returned by `simplexml_load_string()` is complete so the issue lies in how `collect()` is parsing the SimpleXMLElement object.

**Comment by driesvints** [comment]
I think you might have found a bug in PHP itself. Seems like `iterator_to_array` cannot convert a `SimpleXMLElement` properly. It should be perfectly fine to convert any `Traversable` but fails for an `SimpleXMLElement`. 

I recommend you report this to PHP's issue tracker.

**Comment by rodrigopedra** [comment]
Hey @x7ryan as a workaround try this:

~~~php
collect($simple_xml->xpath('.//item'))->dump();
~~~

As @driesvints said, bug, (or not well-documented usage), seems to be on PHP itself. For example if you do this:

~~~php
var_dump(iterator_to_array($simple_xml));
~~~

You will get a similar result as the collection from the instance.

**Comment by x7ryan** [comment]
@driesvints Thanks for looking into it, I will be sure to do that.

@rodrigopedra I like your workaround a bit cleaner than mine.
