### ISSUE TITLE
A line of code that does not know the meaning

### ISSUE THREAD

**Issue by liamhao** [laravel/framework#37127]
https://github.com/laravel/framework/blob/7ad5e59a7130143db98d6302a9427fd7dc033062/src/Illuminate/Routing/RouteFileRegistrar.php#L33

It's this line. What does it do?

![image](https://user-images.githubusercontent.com/31812811/116101676-9ce3ec00-a6e0-11eb-8c97-a7d68160d728.png)

**Comment by driesvints** [comment]
It opens up the `$router` variable to route files like https://github.com/laravel/laravel/blob/8.x/routes/web.php
