### ISSUE TITLE
Method limit() and method offset() should not exist independently

### ISSUE THREAD

**Issue by wxb** [laravel/framework#37132]
- Laravel Version: 8.30.0
- PHP Version: 7.3.25
- Database Driver & Version: mysql 5.6.28

### Description:
`LIMIT` is MySQL keyword，`OFFSET` is not a MySQL keyword！

* If you want to have `OFFSET`, you must have `LIMIT` first
![image](https://user-images.githubusercontent.com/7111495/116178900-e831e500-a748-11eb-9207-5ec2f87a2809.png)

* `OFFSET ` is just for PostgreSQL compatibility
![image](https://user-images.githubusercontent.com/7111495/116179395-d997fd80-a749-11eb-88a3-9436a6bbbff5.png)

* `offset()` method should not be used to retrieve all rows from a certain offset up to the end of the result set, You should use the `LIMIT` like this
![image](https://user-images.githubusercontent.com/7111495/116179700-5cb95380-a74a-11eb-979c-d9f70069a55f.png)

### Steps To Reproduce:

* Query users information
```php
$users = DB::table('users')->offset(10)->limit(5)->get();
```
is OK!
But when you do a query like this
```php
$users = DB::table('users')->offset(10)->limit(null)->get();
// OR
$users = DB::table('users')->offset(10)->get();
```
MySQL will have an error：
![image](https://user-images.githubusercontent.com/7111495/116201382-0826d000-a76c-11eb-86e9-dd3e664d0ea3.png)

* I think
1. The framework should not assume that the user will always call the `limit()` method when using the `offset` method
2. The framework defines the `limit()` method and `offset()` method independently, so the user has the right to use them independently, but this can lead to errors
3. If it is officially approved, I suggest fixing this problem, or I am also willing to provide PR

**Comment by driesvints** [comment]
I don't see the issue here. You just need to be mindful in how you use this just like when you write a normal query.
