### ISSUE TITLE
Cannot use @directive in component tag

### ISSUE THREAD

**Issue by PH7-Jack** [laravel/framework#37131]
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Database Driver & Version: mysql 8.0.3

### Description:
I cannot use **@customDirective** in blade component tag inside a view, it throw an error: `syntax error, unexpected token "endif", expecting end of file`
ex: 
```
 <x-button @customDirective('foo')>
       Click me
 </x-button>
```

PS: cannot use **@if, @unless...**

Its a bug or not is possible?

**Comment by ahinkle** [comment]
Hey @PH7-Jack ,

Can you give an example of why you would want to use an inline blade directive on a component? :) I can't think of a practical use case.

**Comment by PH7-Jack** [comment]
@ahinkle 
I need to use a directive to call js method, **@confirm({ foo: 1, bar: 2})**
Thats directive return value `onclick="window.$app.confirm({ params }, variableInsertedInDirectiveMethod)"`

**Comment by driesvints** [comment]
Please see https://laravel.com/docs/8.x/blade#component-attributes

![Screenshot 2021-04-27 at 09 49 02](https://user-images.githubusercontent.com/594614/116205274-db5bc400-a73d-11eb-8905-eb20b71c3360.jpg)
