### ISSUE TITLE
Laravel missing login session after redirecting to url or refreshing page

### ISSUE THREAD

**Issue by MahdiPishguy** [laravel/framework#37133]
- Laravel Version: "^8.32.1",
- PHP Version: 8.0.3
- Database Driver & Version: MariaDB

### Description:

As we know we can simply use `Auth::loginUsingId` to login on every users which stored into database. in this simple below `route` i try to login with this method and when i commenting that. i expected i want to have login session for example:

```php
Route::get('/test', function () {
    Auth::loginUsingId(1,true);
    dd(Auth::check());
})->name('test');
```

checking auth return true. now after commenting `Auth::loginUsingId(1,true);` and i'm refreshing the page, checking authentication return false

UPDATED:

i tested this scenario on `laravel 8.12` and its work fine, but i have this problem on `laravel 8.32`

**Comment by lk77** [comment]
Hello,

we are on v8.38.0, and we don't have this issue.

```
Auth::loginUsingId($userId);

return redirect()->to('/');
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
