### ISSUE TITLE
Failing assertDontSee

### ISSUE THREAD

**Issue by Hewbruce** [laravel/framework#37139]
- Laravel Version: 8.25.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.21

### Description:
Displaying an error of a class not existing, but that class does exist. When I searched the error message, it was abnormal that the error was in a kind of loop and not a normal work flow. See the HTML zip.

### Steps To Reproduce:
A calling of assertDontSee when PHPUnit testing.
[🧨 Target class [App_Http_Controllers_Channel] does not exist..html.zip](https://github.com/laravel/framework/files/6384129/Target.class.App_Http_Controllers_Channel.does.not.exist.html.zip)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
