### ISSUE TITLE
Relations does not work when using select 

### ISSUE THREAD

**Issue by VeRJiL** [laravel/framework#37138]
- Laravel Version: 8.38.0
- PHP Version: 7.4.7
- Database Driver & Version: mysql8.0.18

### Description:
if you use `->select([])` in ORM and get data of relations with that Entity it's always null unless You remove `->select()` from the ORM query chain

### Steps To Reproduce:

Create models like Article and Comment and add some data using factories and database seeders and then try to query data in this manner:
`$events = Article::query()
            ->select(['id', 'name'])
            ->with('comments')
            ->get();`
`dd($events[0]->comments);`
        

the result is **null**

after you remove the `->select()` statement its working fine!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by liamhao** [comment]
Try :
```php
$events = Article::query()->with('comments')->get(['id', 'name']);
```
