### ISSUE TITLE
Artisan serve command does not work without env file

### ISSUE THREAD

**Issue by ugorur** [laravel/framework#37141]
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
When I use serve command without .env file and with local env variables, it doesn't work.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lk77** [comment]
Hello,

you could do something like that :

printenv | sed -e 's/=/="/g' -e 's/$/"/g' > .env
