### ISSUE TITLE
url call returns invalid url with S3 filesystem when path contains special characters defined in RFC 3986 2.2

### ISSUE THREAD

**Issue by tdondich** [laravel/framework#37159]
- Laravel Version: 
- PHP Version: 5.5 and Above
- Database Driver & Version: n/a

### Description:
When utilizing an S3 filesystem with the 'url' config parameter to specify a base URL (for example, a cloudfront distribution), it's possible the url method returns an invalid URL when the path contains special characters that are inside RFC 3986 2.2. 

### Steps To Reproduce:

1. Store a file in S3 bucket that has the '+' character in it (example: 'My+Example.jpg')
2. Configure a filesystem disk for S3, pointing to bucket, and specify a new base url (For example, a cloudfront disitrubtion)
3. Call Storage::disk('s3')->url('My+Example.jpg');
4. See it return the path as '/My+Example.jpg', which is an invalid S3 object uri.

### Reasons for breakage
When not specifying the 'url' config parameter, the url() call calls getAwsUrl() in FilesystemAdapter. That call properly uses the AWS S3 SDK to get the Object URL which will return a valid URI to point to an S3 object, with certain characters encoded.

When specifying the 'url' config parameter, the getAwsUrl() simply concats the requests path to the url, which avoids any encoding of special characters, creating an invalid key.

### Solution
The getAwsUrl() can continue to use the AWS S3 SDK to get the object url with special characters encoded and then pull the path out of the url utilizing PHP's parse_url() function, specifying to return only the URL path.  Then it can concat that path to the url configured for the disk.  Note, we should not attempt to encode the characters ourselves but instead rely on the AWS SDK to ensure we use their character encoding.

Pull Request: https://github.com/laravel/framework/pull/37160

### See Also
* https://tools.ietf.org/html/rfc3986#section-2.2
* https://forums.aws.amazon.com/thread.jspa?threadID=55746

**Comment by driesvints** [comment]
Looks like Taylor rejected the pr for this.
