### ISSUE TITLE
Laravel eager loading nested columns issue

### ISSUE THREAD

**Issue by raimondslindezutzu** [laravel/framework#37153]
- Laravel Version: 8.39.0
- PHP Version: 7.4.16
- Database Driver & Version:

### Description:
I'm unable to select nested model columns. Only the whole model can be selected.

### Steps To Reproduce:
1) 'owner' => $this->owner()->with('profile')->select('id','email')->first(),
2) 'owner2' => $this->owner()->with('profile:first_name,last_name')->select('id','email')->first(),
3) 'owner3' => $this->owner()->with(['profile' => function ($query) {
    $query->select('first_name','last_name');
}])->select('id','email')->first(),

1) works
2) doesn't work
3) doesn't work

owner() is Model\Company $this->belongsTo(User::class, 'owner_id');
profile() is Model\User $this->hasOne(UserProfile::class);

Model\Company has an owner
Owner is Model\User
User/Owner has a Model\Profile

1) 'owner' =>
select * from `user_profiles` where `user_profiles`.`user_id` in (3)
select `id`, `email` from `users` where `users`.`id` = 3 and `users`.`deleted_at` is null limit 1
2) 'owner2' =>
select `first_name`, `last_name` from `user_profiles` where `user_profiles`.`user_id` in (3)
select `id`, `email` from `users` where `users`.`id` = 3 and `users`.`deleted_at` is null limit 1
3) 'owner3' =>
select `first_name`, `last_name` from `user_profiles` where `user_profiles`.`user_id` in (3)
select `id`, `email` from `users` where `users`.`id` = 3 and `users`.`deleted_at` is null limit 1

**Comment by gregorip02** [comment]
The reason it doesn't work is probably because you exclude the foreign key from its "profile" relationship. [See the docs](https://laravel.com/docs/8.x/eloquent-relationships#eager-loading-specific-columns). 

Please try the following.

```php
<?php

# Owner 2
$this->owner()->with('profile:id,first_name,last_name')->select(['id','email'])->first();

# Owner 3
$this->owner()->with(['profile' => function ($query) {
    $query->select(['id', 'first_name','last_name']);
}])->select('id','email')->first();
```

**Comment by raimondslindezutzu** [comment]
@gregorip02 I tried both load and with together with "id" fields and they both return profile: null

Currently I'm separating owner and owner_profile - this way I can use resource to select fields

**Comment by gregorip02** [comment]
Maybe including the foreign key?

**Comment by raimondslindezutzu** [comment]
@gregorip02 Yep! This works:
`$this->owner()->with('profile:id,user_id,first_name,last_name')->select(['id','email'])->first()`

Thanks!

**Comment by gregorip02** [comment]
Happy to help :)
