### ISSUE TITLE
[6.x] Tests are run with MySQL 5.7 instead of MySQL 5.6

### ISSUE THREAD

**Issue by matteotrubini** [laravel/framework#37161]
https://github.com/laravel/framework/blob/09bf1457e9df53e172e6fd5929cbafb539677c7c/.github/workflows/tests.yml#L18-L19

I know it's EOL, but shouldn't it be `mysql:5.6` as per https://laravel.com/docs/6.x/database#introduction ?

If my doubt is right, it should be changed also in 7.x branch.

**Comment by driesvints** [comment]
No, it's fine.
