### ISSUE TITLE
Custom pivot class isn't using $table attribute 

### ISSUE THREAD

**Issue by madman-81** [laravel/framework#37162]
- Laravel Version: 8.38.0
- PHP Version: 7.4
- Database Driver & Version: sqlite

### Description:
This might be more a feature request than a bug. For many-to-many relations it is possible to use a custom pivot class. This class extends Model, but it doesn't use the $table attribute to determine the table name. Of course it's possible to give this table name as second argument with the `belongsToMany()` function, but then there is not a single point of definition. 

### Steps To Reproduce:
```php
class Post extends Model
{
    public $table = 'posts';
    public $timestamps = true;

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->using(PostTags::class);
    }
}

class Tag extends Model
{
    public $table = 'tags';
    public $timestamps = true;

    public function posts()
    {
        return $this->belongsToMany(Post::class)->using(PostTags::class);
    }
}

class PostTags extends Pivot
{
    protected $table = 'posts_tags';
}
```

Using the relation this way similar to this:
```php
$post->tags()->attach($tag->id);
```
will result in a error "no such table: post_tag", which is de default table name 

Because Pivot extends Model, one would expect this to work. And it will result in cleaner code. Hopefully this is something that can be fixed easily!

**Comment by staudenmeir** [comment]
Please see https://github.com/laravel/framework/issues/30183#issuecomment-538492165.
