### ISSUE TITLE
pgsql queries with boolean columns type missmatch in PHP 7.4.18

### ISSUE THREAD

**Issue by Zabrr** [laravel/framework#37179]
- Laravel Version: v8.40.0
- PHP Version: 7.4.18
- Database Driver & Version: pgsql 10.15

### Description:
After upgrading php from **7.4.16** to **7.4.18**, all queries (select/insert/update/delete) with boolean columns broke.

`SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: select * from "users" where "active" = '1'
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select * from "users" where "active" = '1')`

Problem is in Illuminate\Database\Connection::prepareBindings method:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Connection.php#L610
all boolean values are transforms to integers.

If rewrite select query with raw:
```php
$user::query()->whereRaw('"active" = true')->get();
```
`select * from "users" where "active" = true`
all is works fine. But we can't do it for inserts/updates.

### Steps To Reproduce:
1) create table with boolean columns, e.g
```php
Schema::create('users', function (Blueprint $table) {
    $table->id();
    $table->boolean('active');
});
```
2) perform create
```php
$user->create(['active' => true]);
```
or select
```php
$user::query()->where('active', true)->get();
```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/pull/37168

**Comment by mfn** [comment]
> upgrading php from **7.4.16** to **7.4.18**

🤔

https://www.php.net/ChangeLog-7.php only list 7.4.16

**Comment by Madhusudan16** [comment]
I have the same issue,  any luck?
