### ISSUE TITLE
Laravel v8.40.0: Empty payload for sync job

### ISSUE THREAD

**Issue by andrefvidal** [laravel/framework#37181]
Hello. I'm trying to understand what is occurring on this handle error on Sentry. 

Can some on help me, please.
Error: Argument 2 passed to Sentry\Laravel\Tracing\EventHandler::Sentry\Laravel\Tracing\{closure}() must be of the type string, null given

<img width="1072" alt="Captura de pantalla 2021-04-29 a las 17 16 41" src="https://user-images.githubusercontent.com/20708881/116575184-b4a0b780-a90e-11eb-9216-0a736631cf41.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
