### ISSUE TITLE
ENV Variable Returning NULL 

### ISSUE THREAD

**Issue by iamwebdev** [laravel/framework#37192]
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version: mysql8

### Description:
env variables throwing null value . I tried with clearing cache and everything. I also tried php artisan config:clear then too its showing null. 

### Steps To Reproduce:
![dsds](https://user-images.githubusercontent.com/47749809/116694614-1cbdcf00-a9dd-11eb-83a3-210d437748c5.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
