### ISSUE TITLE
Unable to query for "true" in where() statement in Laravel query builder  with PostgreSQL

### ISSUE THREAD

**Issue by mrcage** [laravel/framework#37205]
- Laravel Version: 8.40.0
- PHP Version: 7.4.18
- Database Driver & Version: pgsql (11.11 (Debian 11.11-0+deb10u1))
- OS: Linux
- Web server: Apache

### Description:

I get a database exception when trying to execute a query involving boolean values on a PostgreSQL database. The code worked flawlessly until today, when this error suddenly popped up; maybe related to a DB software update on the hosting providers site, but not entirely sure. Nevertheless, the problem is, that it seems I can no longer query a where condition for "true" with Laravel/Eloquent, as it seems that Eloquent is converting "true" to 1 and then sending this to the database.

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ...nt(*) as aggregate from "products" where "is_available" = $1
                                                                   ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select count(*) as aggregate from "products" where "is_available" = 1)
```

### Steps To Reproduce:

Related code:
```
Product::available()->count();
````

Related model:
```
class Product extends Model
{
    // ...
    protected $casts = [
        'is_available' => 'boolean',
    ];

    public function scopeAvailable(Builder $qry)
    {
        $qry->where('is_available', true);
    }
}
```

Schema definition:
```
    Schema::create('products', function (Blueprint $table) {
        $table->id();
        // ...
        $table->boolean('is_available')->default(true);
        $table->timestamps();
    });
```

Database Configuration in database.php (standard, nothing changed):

```
        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
```

### Workaround:

I am using a raw database statement to create a "real" "true" value for the database:

```
public function scopeAvailable(Builder $qry)
{
    $qry->where('is_available', DB::raw('true'));
}
```

**Comment by malohtie** [comment]
It a php bug in 7.4.18, downgrading to 7.4.16 fix the issue
Please see #37168

**Comment by ajohnson6494** [comment]
Having same issue. Needs fixed ASAP production environment broken right now with no way to downgrade from php 8.0.5

**Comment by driesvints** [comment]
We can't do anything ourselves about this. All you can do is wait for the next PHP patch.

**Comment by ajohnson6494** [comment]
@driesvints The suggested PR #37168 fixes the problem. Why was it not merged?

**Comment by malohtie** [comment]
@ajohnson6494  it a breaking change, read this https://github.com/php/php-src/pull/6801#issuecomment-828783810

**Comment by driesvints** [comment]
@ajohnson6494  because that'd be a huge breaking change on a minor release.

**Comment by danijelmaric** [comment]
> It a php bug in 7.4.18, downgrading to 7.4.16 fix the issue in my case
> Please see #37168

Any instructions on how to downgrade to PHP 7.4.16 using brew/valet on mac? Thanks in advance!

**Comment by njoguamos** [comment]
> Any instructions on how to downgrade to PHP 7.4.16 using brew/valet on mac? Thanks in advance!


@danijelmaric [Follow this instruction](https://gist.github.com/sawant/6ea10e45de7d09e966a1dc6afea3bffb)
