### ISSUE TITLE
MariaDB: json column falls back to longtext

### ISSUE THREAD

**Issue by cajakre** [laravel/framework#37208]
- Laravel Version: 8.39.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 8 or MariaDB 10

### Description:

MariaDB is not officially supported by the Laravel Framework, but it is known as a drop-in replacement for MySQL and offered by Laravel Sail.

After creating a column as `json`, MariaDB falls back to `longtext`. But TablePlus lets me select `json` manually.

MySQL creates the column correctly as `json`.

### Steps To Reproduce:
1. Add `$table->json('column')` to a database migration.
2. `php artisan sail:install`, choose MariaDB.
3. `sail up`, then `sail artisan migrate`.
4. Open TablePlus or whatever suits you and verify the table structure (data_type `longtext` in my case).
5. Repeat these steps with MySQL (`json`).

**Comment by staudenmeir** [comment]
MariaDB doesn't have a native JSON column type: https://mariadb.com/kb/en/json-data-type/

**Comment by cajakre** [comment]
Yeah, literally read that a second ago and then your reply came. Should have read the docs first, sorry.
