### ISSUE TITLE
Blade exceptions are not reported (logged) in production

### ISSUE THREAD

**Issue by halaei** [laravel/framework#37213]
- Laravel Version:  6.20.26
- PHP Version: 7.4.16
- Database Driver & Version: none

### Description:
In production, we usually don't install composer dev dependencies, `composer install --no-dev`. So in a default Laravel 6.x project `facade/ignition` is not installed. Not having Ignition causes blade exceptions to be ignored and not reported.

In Laravel 8.x a PR has already fixed it: https://github.com/laravel/framework/pull/33323 but I am not sure the PR was intended to fix this issue. Can we have it in 6.x as well? If not, is it OK to move `facade/ignition` from `require-dev` to `require` in composer.json so we have Ignition in production as well?

### Steps To Reproduce:
1. Install a fresh Laravel 6.x app.
2. Install dependencies via `composer install --no-dev`
3. Add some code in welcome blade to throw an exception, e.g. `{{ $laravel }}`.
4. Check the log file. An error should be there but it is not.

**Comment by rodrigopedra** [comment]
Could not reproduce.

Steps:

~~~bash
#!/usr/bin/env bash
composer create-project laravel/laravel:^6 play
cd ./play
composer update
composer install --no-dev
echo '{{ $laravel }}' > ./resources/views/welcome.blade.php
php artisan serve
~~~

Visit http://localhost:8000

![image](https://user-images.githubusercontent.com/5470108/116870912-c96c9c00-abe9-11eb-8860-cbb6a0362abe.png)

Even after trying `APP_ENV=production` and `APP_DEBUG=false`, it work as expected:

![image](https://user-images.githubusercontent.com/5470108/116871049-ff118500-abe9-11eb-98d1-d9949028267a.png)

**Comment by halaei** [comment]
@rodrigopedra The error is missing in the log file (storate/logs/laravel.log), not in the http response. Can you see errors in log file?

**Comment by taylorotwell** [comment]
The bug fix should be able to be ported to 6.x as we are still accepting bug fixes for that version. Are you able to PR it?

**Comment by halaei** [comment]
@taylorotwell I am not confident yet to send a PR.
Also I added ignition in production and it apparently caused a memory leak while working with sitemaps.
This is the related Laravel issue: https://github.com/laravel/framework/issues/31505
Issue in sitemap package: https://github.com/Laravelium/laravel-sitemap/issues/170

**Comment by rodrigopedra** [comment]
My bad then. Thanks for the heads up! I will try a PR then :)

**Comment by rodrigopedra** [comment]
Sent PR #37235 , thanks again @halaei
