### ISSUE TITLE
Unique Validation Rule idColumn parameter is not considered

### ISSUE THREAD

**Issue by gabrieljenik** [laravel/framework#37210]
- Laravel Version: 8
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:

I am using this rule 'unique:App\Domains\Agents\Models\AgentProfile,slug,3,id_user'.
The id_user =3 is not ignored from the validation.

I think the issue is here:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L750

Should be like this:
`$idColumn = $parameters[3] ?? $idColumn ?? 'id';`

First use parameter, then $idColumn the 'id'.

**Comment by taylorotwell** [comment]
Can you use the `Rule` class to build the validation rule instead: 

<img width="745" alt="image" src="https://user-images.githubusercontent.com/463230/116882083-a346fc00-abe9-11eb-8fee-98861c0f9751.png">

**Comment by gabrieljenik** [comment]
Well, yes. I could. But the "string" mechanism is not deprecated yet and allows me to define rules on static attribtutes.
I mean, why close it? Although there are alternatives, still this is a bug with current release, right?
