### ISSUE TITLE
use of undefined constant stdin - assumed 'stdin'

### ISSUE THREAD

**Issue by rahulmanek** [laravel/framework#37219]
I have VPS hosting
When i run **composer install** command in home directory of laravel app using SSH it shows me this error

> PS: app is working fine when i open public folder of laravel

Also can anyone tell me what is the perfect method to live project, i have centos apache server
Please help me out

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
