### ISSUE TITLE
Encrypted attributes can't be null (DecryptException with message 'The payload is invalid.')

### ISSUE THREAD

**Issue by gbalduzzi** [laravel/framework#37229]
- Laravel Version: 8.38.0
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 8

### Description:
I'm using the `encrypted` attribute casting to store some values into database. The problem is, some of these fields are optional and sometimes they are saved as null (the database field is nullable). However, when you set the field to null and try to save it, it throws `DecryptException` with message 'The payload is invalid.'.

Is this the intended behaviour? I can try to create a pull request to support null values if there is interest in the feature. I would expect laravel as null in the database itself

This problem is a feature killer for me, I would have to either migrate a ton of application login to remove any reference to null fields or implement a different encryption library.

### Steps To Reproduce:

In your model:

```
protected $casts = [
  'field_name' => 'encrypted',
];
```

Then:
```
$model->field_name = null;
$model->save(); // Exception is thrown here
```

**Comment by taylorotwell** [comment]
Sure - please send a PR to support `null`.
