### ISSUE TITLE
PHP8: Cannot use positional argument after named argument

### ISSUE THREAD

**Issue by hmhofman** [laravel/framework#37231]
- Laravel Version: 7.24.0
- PHP Version: 8.0.5
- Database Driver & Version: n.a. (mariadb  Ver 15.1 Distrib 10.5.9-MariaDB, for Linux (x86_64) using readline 5.1)

### Description:
PHP 8 now has named arguments (on method calls).
When coming from a route and loading the class, those arguments are build into an array at Illuminate/Routing/RouteDependencyResolverTrait.php, method resolveMethodDependencies

This $parameters array will be filled like so: 
```
array:4 [▼
  0 => Illuminate\Http\Request {#...}
  "file" => App\Models\Files\File {#...}
  1 => false
]
```

As you can see, the numbering is off, but PHP7 allows for this. 

### Steps To Reproduce:
Give the controller method multiple arguments, make sure to have an argument after the argument you define in de route. 
For instance: FileController::get(Request $request, File $file, $forceFromDisk = false) {...}
Create the route: Route::get('/{file}/get', 'FileController@get');
in PHP7, this will call the method, no errors
in PHP8, this will fail: 

```
{
    "class": "Error",
    "message": "Cannot use positional argument after named argument",
    "code": 0,
    "file": "/var/www/stellingkast.nl/toomba/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
    "trace": [
        "/var/www/stellingkast.nl/toomba/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
        "/var/www/stellingkast.nl/toomba/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45",
        "/var/www/stellingkast.nl/toomba/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239",
        ...
```
        
### Possible Solution
Either make sure the resulting array is all positional arguments or named arguments, not both. 
This can be accomplished by updating the `resolveMethodDependencies` method on `Illuminate\Routing`.`RouteDependencyResolverTrait`:
```
    public function resolveMethodDependencies(array $parameters, ReflectionFunctionAbstract $reflector)
    {
        $instanceCount = 0;

        $values = array_values($parameters);

        $skippableValue = new \stdClass;
        $result = [];

        foreach ($reflector->getParameters() as $key => $parameter) {
            $instance = $this->transformDependency($parameter, $parameters, $skippableValue);
            if (array_key_exists($parameter->name, $parameters)) {
                $result[$parameter->name] = $parameters[$parameter->name];
            } elseif ($instance !== $skippableValue) {
                $instanceCount++;

                $result[$parameter->name] = $instance;
            } elseif (! isset($values[$key - $instanceCount]) &&
                      $parameter->isDefaultValueAvailable()) {
                $result[$parameter->name] = $parameter->getDefaultValue();
            }
        }

        return $result;
    }
```
This way, the resulting parameters array, used in the `Illuminate\Routing`.`ControllerDispatcher`::`dispatch` method (`$controller->callAction()`), will have the arguments named AND in the right order, being compatible with PHP8 and still backwards compatible with previous versions of both PHP and Laravel.

**Comment by hmhofman** [comment]
Awaiting a solution, I used this workaround. 

All my Controllers have been derived of an intermediate controller. 
So my `App\Http\Controllers\FileController` 
extends `App\Http\Controllers\Controller`
extends `Illuminate\Routing\Controller`

I have overridden the methods `callAction` in `App\Http\Controllers\Controller` like this: 
```
    /**
     * Execute an action on the controller.
     *
     * Overrides the function at Illuminate\Routing\Controller
     * Awaiting a fix for PHP8 named arguments:
     * @link https://github.com/laravel/framework/issues/37231
     * @link https://lindevs.com/named-arguments-in-php-8-0/
     * @link https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments
     *
     * @param  string $method
     * @param  array  $parameters
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function callAction($method, $parameters)
    {
        $paramList = [];
        foreach ($parameters as $key => $value) {
            $paramList[] = $value;
        }
        return call_user_func_array([$this, $method], $paramList);
    }
```
For anyone else who has this problem

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by hmhofman** [comment]
Hi @driesvints 
You are right. This has been 'fixed' by changing the `Controller`.`callAction` function to: 
```
    public function callAction($method, $parameters)
    {
        return $this->{$method}(...array_values($parameters));
    }
```
I'm pretty sure the spread operator did not exist in php7. 
So.. The above workaround could patch it for anyone using laravel 7 on php8. 
The better solution will be: upgrade Laravel to the newest version. 

Thanks @driesvints
