### ISSUE TITLE
artisan console asking for confirmation

### ISSUE THREAD

**Issue by fake-fur** [laravel/framework#37230]
- Laravel Version: 8.39.0
- PHP Version: 7.4.11
- Database Driver & Version: MariaDb 10.4.18

### Description:
when asking for confirmation the prompt (yes/no) is automatically added to the input question, implying that "yes" is required to confirm the question, however "y" or "ye" also work and i think this is slightly misleading and potentially dangerous

### Steps To Reproduce:
prompt for confirmation in an artisan command and only type "y" or "ye" instead of "yes"

**Comment by driesvints** [comment]
@fake-fur it's very common for CLI's to offer shorthand for answers on these types of prompts. This isn't Laravel specific.
