### ISSUE TITLE
Unable to fake cc in Mail::fake

### ISSUE THREAD

**Issue by rakishii13** [laravel/framework#37238]
- Laravel Version: 8.40.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql

### Description: Unable to test any emails with `cc()`.

It is because Illuminate/Support/Testing/Fakes/MailFake has no `cc()` and this also causes you to not test `hasCc()` in `assertSent()` for emails that were cc'd instead of `to()`.

### Steps To Reproduce:

1. Setup any email with `cc()`

`Mail::cc('test@tester.com')->send(new TestMail());`

2.  Try to have a test to check if the mail was sent. 

```
Mail::assertSent(TestMail::class, function ($mail) {        
    return $mail->hasCc('test@tester.com');
});
```

**Comment by taylorotwell** [comment]
Please send a PR to correct.

**Comment by rakishii13** [comment]
Will you reopen the issue once I a submit a PR or should I open a new issue?
