### ISSUE TITLE
operator does not exist: boolean = integer\n

### ISSUE THREAD

**Issue by drmax24** [laravel/framework#37234]
- Laravel Version: 8.0.39
- PHP Version: 8.0.5
- Database Driver & Version: PDO Postgresql 12.5

### Description:
I have smth nasty boolean/integer database problems starting from april 30 builds. A lot of errors like:
Undefined function: 7 ERROR:  
  operator does not exist: boolean = integer\n
  LINE 1: ...where \"user_staff_house_of_culture\".\"is_director\" = $1 and \"...\n                                                             ^\nHINT:  
  No operator matches the given name and argument types. You might need to add explicit type casts. 
  (SQL: select \"user_staff\".*, \"user_staff_house_of_culture\".\"house_of_culture_id\" as 
  \"laravel_through_key\" from \"user_staff\" inner join \"user_staff_house_of_culture\" on 
  \"user_staff_house_of_culture\".\"user_staff_id\" = \"user_staff\".\"user_staff_id\" 
  where \"user_staff_house_of_culture\".\"is_director\" = 1

### Steps To Reproduce:

I never pass integer as boolean. Column that causes error is boolean.
I think this error appeared when php was apdated exactly to 8.0.5

I suppose hasOneThrough is affected.
P.S.: Select query is performed not an insert query.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/37201 and many other issues already posted.
