### ISSUE TITLE
Jobs have duplicated queries

### ISSUE THREAD

**Issue by rakishii13** [laravel/framework#37236]
- Laravel Version: 8.40.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql

### Steps To Reproduce:

1.  Create a dummy job with empty `handle()` method.

```<?php

namespace App;

use Illuminate\Support\Collection;

class Job
{
    public Collection $models;

    /**
     * Create a new job instance.
     *
     * @param  \Illuminate\Support\Collection  $models
     * @return void
     */
    public function __construct(Collection $models)
    {
        $this->models = $models;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {

    }
}
```
2. Dispatch the job through tinker `dispatch(new Job(collect(App\Model::find(1))))`
3. Through telescope you can see that there are duplicated queries just to find the record.

**Comment by bkuhl** [comment]
This is not a bug and is expected behavior.  `Mode::find()` will query for the record and put it in memory.  The model is then serialized as part of the `Job` and re-queried when a consumer picks it up to ensure it's processed using the latest data.
