### ISSUE TITLE
Dispatching Shorthand in Routes Issue

### ISSUE THREAD

**Issue by rakishii13** [laravel/framework#37233]
- Laravel Version: 8.40.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql

### Description: It seems you cannot enter shorthand functions to callback to dispatch function.

The function inside the dispatch then goes into a forever loop. It then has to be hard reset to actually be stopped. 

### Steps To Reproduce:

`Route::get('test', fn () => dispatch(fn () => App\Model::find(1)));`

**Comment by taylorotwell** [comment]
`dispatch` returns an object which can't be returned from a route.

**Comment by rakishii13** [comment]
Could you explain a bit more because it seems to be working in long hand function 

```
Route::get('test', function () {
    dispatch(function () { 
        App\Model::find(1);
     });
});
```

**Comment by crynobone** [comment]
shorthand function automatically return the result, while longhand you will need to explicitly write `return dispatch()`
