### ISSUE TITLE
Deprecation warnings from League CommonMark

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#37256]
- Laravel Version: 8.40.0
- PHP Version: 8.0.1
- Database Driver & Version: MySQL driver with MariaDB 10.4

### Description:

Deprecation warnings keep on happening every time a markdown email is sent:

```
Passing an $environment into the "League\CommonMark\CommonMarkConverter" constructor is deprecated in 1.6 and will not be supported in 2.0; use MarkdownConverter instead
```

### Steps To Reproduce:

1. Install fresh Laravel
2. Create a markdown email
3. Send it and see deprecation warnings in logs / Sentry / other error tracker

**Comment by driesvints** [comment]
Nothing's broken. This is simply a deprecation warning.
