### ISSUE TITLE
Cast from bool to int breaks PostgreSQL queries

### ISSUE THREAD

**Issue by UnSciPreneur** [laravel/framework#37261]
* Laravel Version: 4/5/6/7/8
* PHP Version: 7.4.18+
* Database Driver & Version: PostgreSQL 11/12/13

## Disclaimer

I know there have been plenty of similar issues and they all have been closed referring to "a bug in PHP". But `boolean` in PostgreSQL simply is not `tinyint(1)`. So casting a boolean variable to int and expecting PHP/PDO to magically resolve this does not feel right.
So why does the `Illuminate\Database\Connection.php` do a MySQL specific cast for every statement here when it uses the grammar to distinguish between MySQL/Postgres/MSSQL/SQLite just one line before?

## Description:

Since PHP 7.4.18 [patched an issue](https://www.php.net/ChangeLog-7.php#7.4.18) in PDO_pgsql ("PDO::PARAM_INT is treated the same as PDO::PARAM_STR") every Postgres sql statement that involves a boolean column breaks!

### Steps to reproduce

Assume you have a model `User` with a boolean attribute `premium_account` and assume that this attribute is set to `false` for the user with `id=1`. Then 

```
$user = User::find(1);
$user->premium_account = true;
$user->save();
```
results in a `PDOException(code: 42804)`.

The root cause is line 610ff. of `Illuminate\Database\Connection.php`:
```
    public function prepareBindings(array $bindings)
    {
        $grammar = $this->getQueryGrammar();

        foreach ($bindings as $key => $value) {
            // We need to transform all instances of DateTimeInterface into the actual
            // date string. Each query grammar maintains its own date string format
            // so we'll just ask the grammar for the format to get from the date.
            if ($value instanceof DateTimeInterface) {
                $bindings[$key] = $value->format($grammar->getDateFormat());
            } elseif (is_bool($value)) {  // line 610
                $bindings[$key] = (int) $value;
            }
        }

        return $bindings;
    }
```

This might be fine when using MySQL as there `boolean` and `tinyint(1)` are the same. But not so for PostgreSQL where these queries will fail with
```
PDOException(code: 42804): SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column \"premium_account\" is of type boolean but expression is of type integer
[...]
```

A quick fix might be to replace the cast to (int) by 
```
$bindings[$key] = $value ? 'true' : 'false';
```
as both MySQL and PostgreSQL would accept this (but other databases might not).

**Comment by mfn** [comment]
https://github.com/laravel/framework/issues/37201 , it's sticky

**Comment by mycarrysun** [comment]
Why does this still happen for me? Is it a regression? 

```SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "enabled" is of type boolean but expression is of type integer LINE 1: update "freezer_alerts" set "enabled" = 1, "updated_at" = '2... ^ HINT: You will need to rewrite or cast the expression. (Connection: pgsql, SQL: update "freezer_alerts" set "enabled" = 1, "updated_at" = 2024-10-07 23:10:04 where "id" = 8)```

PHP 8.3.11
Laravel 11.21.0

![image](https://github.com/user-attachments/assets/24537020-7d9f-45c5-9b4f-dda094c7a7ec)

--
Also worth noting that I am emulating prepares because of the prepared statements going away too soon:
```
// in config/database.php -> pgsql config
'options' => [
                PDO::ATTR_EMULATE_PREPARES => true,
            ]
            ```

**Comment by mycarrysun** [comment]
@driesvints
