### ISSUE TITLE
Security checker

### ISSUE THREAD

**Issue by valeriy-efimov** [laravel/framework#37272]
- Laravel Version: v7.30.4
- PHP Version: 7.4.16
- Database Driver & Version: Mysql

### Description:
I got this error with security-checker
and cant get success on CI/CD 
![image](https://user-images.githubusercontent.com/5989188/117194029-45363680-adec-11eb-8675-af709d61b036.png)
how can i fix it?

### Steps To Reproduce:
run security-checker

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
