### ISSUE TITLE
Custom Date or DateTime casts stop the attribute from being formatted for insertion

### ISSUE THREAD

**Issue by olivergiess** [laravel/framework#37277]
- Laravel Version: 8.40.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 5.7.34

### Description:

Eloquent Model Attributes with _date_ or _datetime_ casts with a format specified (_custom_datetime_) do not format the date prior to database insertion.

This causes an `Illuminate\Database\QueryException` when an ISO 8601 date is provided as the attribute and the database is Mysql 5.7 (which does not support ISO 8601 dates).

[Documentation regarding casts](https://laravel.com/docs/8.x/eloquent-mutators#date-casting)

### Steps To Reproduce:

1. Create a table and migration with a `dateTime()`
```
public function up()
{
    Schema::create('foos', function (Blueprint $table) {
        $table->id();
        $table->dateTime('date');
        $table->timestamps();
    });
}
```

2. Create a model for the table and set the `$casts` array to cast the attribute with a specified format
```
class Foo extends Model
{
    use HasFactory;

    protected $casts = [
        'date' => 'datetime:Y-m-d h:i:s',
    ];
}
```

3. Create an instance of the model.
```
$foo = new Foo();
```
4. Set the attribute to be an ISO 8601 date.
```
$foo->date = '2021-05-06T05:45:20+0000';
```
5. Save the model.
```
$foo->save();
```

Output:
```

   Illuminate\Database\QueryException 

  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2021-05-06T05:45:20+0000' for column 'date' at row 1 (SQL: insert into `foos` (`date`, `updated_at`, `created_at`) values (2021-05-06T05:45:20+0000, 2021-05-06 05:58:07, 2021-05-06 05:58:07))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +12 vendor frames 
  13  app/Console/Commands/Test.php:43
      Illuminate\Database\Eloquent\Model::save()

      +13 vendor frames 
  27  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by driesvints** [comment]
I think you misunderstood how this works. The format set on the cast is used when the model is serialized using `toArray` or into a JSON payload. You're trying to store a date time string which is incompatible with MySQL's `datetime` column that only accepts the `YYYY-MM-DD hh:mm:ss` syntax: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

Either convert the column to a `timestamp` type or convert the value to the proper format.

**Comment by olivergiess** [comment]
If that is the case then it is misbehaving under specific circumstances, if only `datetime` is specified an ISO 8061 Date is being formatted to `YYYY-MM-DD hh:mm:ss` when it is `datetime:YYYY-MM-DD` it is not.

I agree the purpose of the casts is as the documentation specifies, however the inconsistency is more so the issue I intended to raise.

It should either always format the date regardless of a `custom_datetime` or it should never.
