### ISSUE TITLE
Method name conflict breaks a (potentially) common use of scopes

### ISSUE THREAD

**Issue by danyellnoe** [laravel/framework#37273]
- Laravel Version: 8.35.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Description:

The introduction of SQL aggregation functions to the [QueriesRelationships](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php) trait in [PR #34965](https://github.com/laravel/framework/pull/34965) includes the addition of the _withColumn()_, _withMax()_, _withMin()_, _withSum()_ and _withAvg()_ methods.  These function names seem (to me) to be very generic, which increases the likelihood of a naming conflict arising.  And I feel that way because their introduction was a breaking change in my code.

### Steps To Reproduce:

Add a dynamic query scope to any model, with the goal of offering a generic process by which query results will be filtered by an arbitrary column in the model's related database table.  Name the function _scope{WithMin || WithMax, etc.}()_ and attempt to run a query using that scope.

#### Specifics of the scenario which brought me here

In my case, I have an **Artist** model, which represents a musician, band, DJ, etc.  I frequently query this model to find **Artists** with a minimum number of followers, minimum number of upcoming shows, etc.  As such, I created a local query scope as shown below in the **Artist** model:

```
use Illuminate\Database\Eloquent\Builder;
// ...

class Artist extends Model
{

    // ...

    /**
     * Query scope for filtering by the minimum number of a given attribute.
     *
     * @param Builder $query
     * @param string $attribute
     * @param integer $min
     * @return Builder
     */
    public function scopeWithMin(Builder $query, string $attribute, int $min): Builder
    {
        return $query->where($attribute, '>=', $min);
    }

    // ...
}
```

Prior to updating to Laravel 8.x, the following calls to retrieve a filtered set of **Artists** from my _ArtistController_ executed without issue:

```
// fetch only Artists with a minimum number of followers
Artist::withMin('followers', $minFollowers)->get();

// fetch only Artists with a minimum number of upcoming performances
Artist::withMin('upcoming_performances', $minPerformances)->get();
```

However, after updating to 8.x, the following errors will be returned for these calls:
```
BadMethodCallException
Call to undefined method App\Artist::followers()

BadMethodCallException
Call to undefined method App\Artist::upcoming_performances() 
```

The specific conflict that occurred and brought this to my attention was with the [withMin()](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L458) function of the **QueriesRelationships** trait.  And, since this trait is used within the Builder class, which is tightly coupled with query scopes (a **Builder** _$query_ is passed in as the first parameter && scopes return a **Builder** instance), this means that no dynamic query scopes such as I have been leveraging can be created with any of the aforementioned method names.

### Solution(s):

This whole thing might sound nitpicky but, as I mentioned, it was a breaking change for my application.  And since I just tracked down the issue, I thought it would at least be helpful to bring it up for consideration and share the experience and offer a couple solutions.

One immediate fix is to remove the _scopeWithMin()_ query scope I created and replace it with multiple scopes, i.e. _withMinFollowers()_ and _withMinUpcomingPerformances()_.  However, this approach clearly sacrifices some of the power of dynamic scoping.

Alternatively, I could rename the scope to something like _withMinCount()_ or something similar.  That works, of course.  But if this is the preferred solution, it might make sense to update the documentation to throw a quick warning to avoid naming scopes these specific (and seemingly common) names.  If not in the [Query Scopes](https://laravel.com/docs/8.x/eloquent#query-scopes) section, then _at very least_ it should be mentioned somewhere in the [Upgrade Guide](https://laravel.com/docs/8.x/upgrade).

Personally, I feel that a better solution is to be more verbose in the naming of these functions within the **QueriesRelationships** trait, i.e. _withRelationColumn()_, _withRelationMax()_, _withRelationMin()_, _withRelationSum()_ and _withRelationAvg()_.  This would eliminate the issue I encountered by allowing developers to use those method names and would simultaneously create a more fluid and easy to read code base.

In theory, this could presumably provide motivation to also rename the _withCount()_ method to _withRelationCount()_ as well for consistency's sake.  However, I am pretty sure that would be a more substantial / breaking change that we wouldn't want to take on.  These other methods have only just been added in 8.x, so I presume changing them would be much more manageable.

Interested to hear thoughts / feedback.  If any of the solutions I suggest (update Query Scopes section of documentation || update the 7.x to 8.x Update Guide || update the names of the SQL aggregation functions) seems feasible, let me know and I will create a PR.  Thanks!

**Comment by paras-malhotra** [comment]
Your recommended solution is a breaking change for everyone that use the `withMin`, `withMax`, etc. methods introduced in October. Don't think we can do anything about it now except add it to the upgrade guide perhaps.

**Comment by driesvints** [comment]
I'm sorry @danyellnoe but extending the public api on a minor release is part of semver, the versioning scheme we use. Like @paras-malhotra said, removing them now would mean real breaking changes. Sorry for this.

**Comment by danyellnoe** [comment]
I understand and suspected that would be the case.

I've just now implemented the fix for my application by changing the query scope to `scopeWithMinimum(Builder $query, string $attribute, int $min)`, so the only damage done is the time spent scratching my head as to why it broke.

Still, seems that if it was important enough to warrant adding a section to the docs ([Other Aggregate Functions](https://laravel.com/docs/8.x/eloquent-relationships#other-aggregate-functions)), it seems like it would be worth a mention in the Upgrade Guide?

_Side note, I used Laravel Shift to assist in the upgrade and the issue wasn't identified there either, so will probably shoot a message to JMac so that potential head scratching might be avoided by others using that service._

**Comment by driesvints** [comment]
The reason why I don't think we should add this to the upgrade guide is because then we'd also have to do that for many many other method additions on minor releases. The upgrade guide would become unmanageable and huge and a gigantic work for us to maintain. We already provide a detailed changelog which is the proper place for these additions I believe.

**Comment by danyellnoe** [comment]
Cool, except that these changes are not mentioned in the [release notes](https://laravel.com/docs/8.x/releases) or the [changelog](https://github.com/laravel/laravel/blob/8.x/CHANGELOG.md).   Oh well.  Thanks for considering.

**Comment by driesvints** [comment]
@danyellnoe That's the changelog for the skeleton, not the framework. The framework's changelog can be found in this repo. Here's the version you're seeking: https://github.com/laravel/framework/blob/8.x/CHANGELOG-8.x.md#v8120-2020-10-29

The release notes you linked to are the release notes when a new major version is released. It's never used for minor or patch releases.

**Comment by danyellnoe** [comment]
@driesvints Ah, I see now.  Okay, thanks for the clarification.  I see that as one downside to the new annual release cycle - there are going to be plenty of releases with changes that goes unnoticed until something breaks.  Guess I'll have to try and keep a closer eye on the current state of affairs 🧐
