### ISSUE TITLE
Distinct validation bug when using different rules for array

### ISSUE THREAD

**Issue by amir9480** [laravel/framework#37282]
- Laravel Version: 8.40.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0.22

### Description:
When using distinct validation rules and using different rules for each array element, distinct validation will not work as expected.
This bug only exists when we put array element rules after a distinct validation rule.

#### Example code with wrong output:
```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.*' => 'distinct',
        'value.0' => 'numeric|min:10|max:30',
        'value.1' => 'numeric|min:20|max:40'
    ]
);
$v->errors()->all() // [], Not what expected when value is [25, 25]
```

#### Working examples with expected output:
```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.0' => 'numeric|min:10|max:30', 
        'value.1' => 'numeric|min:20|max:40',
        'value.*' => 'distinct'
    ]
);
$v->errors()->all(); // The value.0 field has a duplicate value., The value.1 field has a duplicate value.
```

---

```php
$v = Validator::make(
    ['value' => [25, 25]], 
    [
        'value.*' => 'distinct'
    ]
);
$v->errors()->all(); // The value.0 field has a duplicate value., The value.1 field has a duplicate value.
```

Note: Previous issue (#37257) closed but issue not solved yet.

**Comment by driesvints** [comment]
Like Taylor said here: https://github.com/laravel/framework/pull/37260#issuecomment-832148347, you're probably using distinct in a way that's not intended, sorry.

**Comment by amir9480** [comment]
@driesvints 
Is the order of validation rules even matters?
I'm sure this should be considered a bug. I'm pretty sure.

**Comment by amir9480** [comment]
@driesvints 

These two arrays are equivalent.
```php
[
    'value.*' => 'distinct',
    'value.0' => 'numeric|min:10|max:30',
    'value.1' => 'numeric|min:20|max:40'
]
```
---
```php
[
    'value.0' => 'numeric|min:10|max:30', 
    'value.1' => 'numeric|min:20|max:40',
    'value.*' => 'distinct'
]
```

But validator output is different for each one which the second one is accurate.

**Comment by amir9480** [comment]
@driesvints

**Comment by driesvints** [comment]
I'm sorry but I'm gonna have to close this one. You can always attempt a new pr but I believe Taylor was clear.
