### ISSUE TITLE
SwiftMailer has different behaviour with queue:listen and queue:work (__destruct method not called)

### ISSUE THREAD

**Issue by Kwaadpepper** [laravel/framework#37299]
- Laravel Version: 7.x, 8.x ?
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:
https://github.com/swiftmailer/swiftmailer/issues/1287

SwiftMAiler uses a __destruct method to remove its temp folders/files (for the mail body)

This method is called using queue:listen, but not with queue:work, leaving all files.
These are putted in ```/tmp```, so the issue may not be a big thing, but we have the possibility to use another folder.
So it would never be cleaned. I also has the issue on a site in production where it has filled up  ```/tmp``` causing crashes and failed jobs that could not send emails anymore.

### Steps To Reproduce:

- Change swift tmp folder using ```\Swift_Preferences::getInstance()->setTempDir($tmpDir); ```
- ````watch -n 0.1 ls storage/tmp``` or ```watch -n 0.1 ls /tmp```
- Make a job sending mail
- Test to run it using ```queue:listen``` and then ```queue:work```
- notice files are not removed using ```queue:work``` (because swiftmail __desctruct is not called)
- https://github.com/swiftmailer/swiftmailer/blob/23e9ffaf6e8c716bce31bde1be708a405b1fbdf9/lib/classes/Swift/ByteStream/TemporaryFileByteStream.php#L39

**Comment by driesvints** [comment]
This seems more like a SwiftMailer issue than a Laravel issue to me. `queue:work` is meant to be a long running process so `__destruct` methods never get called. I'm afraid we can't do anything about this here. I'd argue that `__destruct` isn't the best place to clear our the `/tmp` files. Either it's best that SwiftMailer tackles this differently or you clear `/tmp` manually yourself either through code or a server specific solution.

**Comment by Kwaadpepper** [comment]
OK this is the feeling I had about that, but you gave me the confirmation of it. Thank you for your time.
