### ISSUE TITLE
Middleware not redirecting properly in Laravel 8.12

### ISSUE THREAD

**Issue by cwdabba** [laravel/framework#37317]
- Laravel Version: 8.12
- PHP Version: 8.05
- Database Driver & Version: MYSQL 8

### Description:

Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    Route::get('/{post}', [PostController::class, 'show'])->name('show');
});

Route::group(['middleware' => 'user-auth'], function () {
    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        /************** THIS IS NOT GETTING REDIRECTED TO LOGIN  IF USER NOT LOGGED IN *************/
        Route::get('/create', [PostController::class, 'create'])->name('create'); 
    });
});

Following is my middleware

public function handle($request, Closure $next)
{
    if (!session()->has('user_details')) {
        return redirect()->route('auth.login');
    }
    return $next($request);
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by cwdabba** [comment]
Thank you got the issues fixed by myself.
