### ISSUE TITLE
Dot access error in method `Arr:forget()`

### ISSUE THREAD

**Issue by selcukcukur** [laravel/framework#37318]
- **Laravel Version:** 8.40.0
- **PHP Version:** 8.0 & 8.1 & 7.4
- **Database Driver & Version:** -

### Description:
When accessing an item with dot access, the partition operation is performed incorrectly in the `Arr::forget()` method.

### Steps To Reproduce:
1. Install a new Laravel.
2. Create the array as below.
```php
$tempArray = [
    'emails' => [
        'foo@bar.com' =>
            ['name' => 'Joe'],

        'baz@bam.com' =>
            ['name' => 'Doe']
]];
```
3. Try to forget the 2nd part key in the series.
```php
Arr::forget($tempArray, ['foo@bar.com', 'baz@bam.com']);

// Expected Result : ['emails' => []] 
// Returning result : ['emails' => ['foo@bar.com' => ['name' => 'Joe'], 'baz@bam.com' =>['name' => 'Doe']]];
```
I have investigated the reason for this and need help finding a method of fixing it without breaking other functions to fix it.

This is because :
- Array `.` It breaks into pieces according to the sign.
- The above example is based on the sequence below while processing the array.
```
emails > foo@bar > com
emails > baz@bam > com
```
- But if it is not a sub-sequence, it should interpret this situation differently. Sample :
```
emails > foo@bar.com
emails > baz@bam.com
```

**Comment by driesvints** [comment]
A dot is a reserved character to target nested keys. You can't use them as array keys in combination with the Arr class.
