### ISSUE TITLE
Incorrect check in rehashUserPassword 

### ISSUE THREAD

**Issue by meyyappanv** [laravel/framework#37321]
- Laravel Version: 8.37.0
- PHP Version: 7.4.16
- Database Driver & Version: mongo 4.4.4

### Description:

As in the description using logoutOtherDevices() will invalidate all other user's session only, https://laravel.com/docs/8.x/authentication

In the change password scenario, when we call logoutOtherDevices(), 
$password is supposed to hold the new password.
This method calls rehashUserPassword() where the new password is checked against the current password's hash, which will never match.

    if (! Hash::check($password, $this->user()->{$attribute})) {
        throw new InvalidArgumentException('The given password does not match the current password.');
    }

Then in next line, the new password's hash is created and saved. 

Also not able to see a point why this would be `InvalidArgumentException`? Shouldn't this be `AuthenticationException` ?

### Steps To Reproduce:

A code snippet to show the example

    if ($validation->passes()) {

        User::updatePassword($uid, Request::get('password'));

         Auth::logoutOtherDevices(Request::get('password'));

        $this->reset(['current_password', 'password', 'password_confirmation']);

        return $this->dispatchBrowserEvent('success', [
            'title' => 'Password updated successfully!',
            'icon'  => 'success',
        ]);
    }

**Comment by paras-malhotra** [comment]
Don't see how this is a bug. Sounds to me like you just implemented it incorrectly. Firstly, it's odd that you want to update the password and logout other devices in the same request.

Even if you do want to do that, you need to update the cached user instance held by the auth guard. 

By doing `User::updatePassword` you forget to reset the cached version of the user, and so `logoutOtherDevices` still holds the old password. This is an issue with your implementation, and not a bug in the framework.

To fix this, you should do something like:
```php
$request->user()->forceFill(['password' => Hash::make($request->input('password'))])->save();

Auth::logoutOtherDevices(....);
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
