### ISSUE TITLE
Eloquent - nested relations lost when calling refresh on model

### ISSUE THREAD

**Issue by netdown** [laravel/framework#37329]
Hi,

I have found a bug/bad practice regarding the refresh method. If nested relations have been loaded, calling refresh on the main model causes loss of the nested relations. The direct relations of the main model get refreshed, but without loading the nested relations. Clearly, if I was using nested relations and I call refresh, I would still want to have all the relations.

I have made a simple workaround for my use case (this is only for iterable relations):
```
$relations = [];
foreach($this->getRelations() as $relationName => $value) {
	if(is_iterable($value) && $value->count() > 0) {
		$nestedRelations = $value->first()->getRelations();

		if(count($nestedRelations) > 0) $relations[$relationName] = array_keys($nestedRelations);
	}
}

$this->refresh();

foreach($relations as $relation => $nestedRelations) {
	foreach($this->$relation as $relatedInstance) {
		$relatedInstance->load($nestedRelations);
	}
}
```

Illuminate/database version: v8.27.0

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by netdown** [comment]
What does make this look like a question for you? I have a workaround for my use case, I just reported the problem...
