### ISSUE TITLE
pluck() with array key by default

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#37327]
- Laravel Version: 8.40.0
- PHP Version: 7.4.13
- Database Driver & Version:

### Description:
I faced this when manipulating table rows/columns, i.e. 2D arrays
It would be good for `pluck()` to return with the existing keys if it was provided.

The current behavior can be maintained by additionally passing the results through `array_values()`, otherwise, I suspect most existing code do not care about the key which makes this change non impacting.

### Steps To Reproduce:
```PHP
$array = [
    3 => ['developer' => ['id' => 1, 'name' => 'Taylor']],
    2 => ['developer' => ['id' => 2, 'name' => 'Abigail']],
];

$names = Arr::pluck($array, 'developer.name');

// Expected
// [3 => 'Taylor', 2 => 'Abigail']

// Current
// ['Taylor', 'Abigail']

**Comment by bilogic** [comment]
I could file a PR if this is acceptable. Thank you.

**Comment by dinhquochan** [comment]
It should be to `9.x`, BC alert!

**Comment by driesvints** [comment]
Seems like a feature request. Feel free to attempt a PR, thanks.
