### ISSUE TITLE
Running different seeders with RefreshDatabase trait

### ISSUE THREAD

**Issue by gauravmak** [laravel/framework#37339]
- Laravel Version: 8.37.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.0.24

### Description:
If we wish to run different seeders using the `$seeder` property for each test, only the seeder from the first test is run.

The `RefreshDatabase` trait runs for the first test and seeds accordingly. For the rest of the tests, the seeders are not run because the database has already migrated.

### Steps To Reproduce:

Add a couple of tests with the `RefreshDatabase` trait and use different seeders for the `$seeder` property of both the tests. The second test seeder will not run.

**Comment by driesvints** [comment]
Please post of the failing tests.

**Comment by gauravmak** [comment]
Added sample code in [this gist](https://gist.github.com/gauravmak/98907c8daa03c64dfbf7df5bcd129450).

The `CountryTest` passes but the `StateTest` fails because the `StatesSeeder` does not run.

**Comment by driesvints** [comment]
I can confirm this. I'll try to investigate this.

**Comment by driesvints** [comment]
So what I discovered is that this is probably by design because of the `RefreshDatabaseState::$migrated` here: 

https://github.com/laravel/framework/blob/5d0d6cf39cb212adb9f04a6a4328f9d18b351883/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L64-L70

This causes the fresh command to only be run once and afterwards all state is managed with database transactions. But this definitely isn't clear enough in the docs. I'm unsure if this is intended or not.

I also discovered an additional concern with this with that seeders aren't run at all when running tests using an in-memory Sqlite database. I'm not sure if that's intended or not.

I'll need @taylorotwell to confirm the above two things and see how we're going to tackle this.

**Comment by taylorotwell** [comment]
It is definitely intended to only migrate once and then use transactions as that is the main benefit of the trait. Personally I would just call `$this->seed()` in your tests when you actually want to seed your database.

**Comment by taylorotwell** [comment]
IMO the PRs to add this `$seeder` property weren't very thought out. I probably should have just rejected them.

**Comment by taylorotwell** [comment]
I'm going to undocument that entire feature because it's just broken and poorly thought out.

**Comment by taylorotwell** [comment]
Redid the documentation for this feature. The `$seed` and `$seeder` properties only make sense to be defined on the base test class.

**Comment by gauravmak** [comment]
@taylorotwell @driesvints [A note](https://github.com/laravel/docs/commit/967b638e518654120735c13f40c4b7495b5b3dd8#commitcomment-51165186) here

**Comment by slavicd** [comment]
According to 8.x docs 

> Alternatively, you may instruct Laravel to automatically seed the database before each test that uses the RefreshDatabase trait. You may accomplish this by defining a $seed property on your base test class

which actually is incorrect. Can we update the documentation? I spent more than an hour to debug this.

**Comment by HasanMothaffar** [comment]
Can we please update documentation for the `RefreshDatabase` feature? As other comments mention in this thread, the docs do not reflect how it works correctly.

Here's an excerpt from the [11.x database testing docs](https://laravel.com/docs/11.x/database-testing#running-seeders)

>When the $seed property is true, the test will run the Database\Seeders\DatabaseSeeder class before each test that uses the RefreshDatabase trait. 

First, what do we mean by each test? Each test class or each test method defined in a test class? I will assume that it's before each test method.

Second, `RefreshDatabase` does not seed the database before each test. it only seeds before the **_first_** test class that uses the `RefreshDatabase` trait and extends from the abstract `TestCase` class (which has `$seed = true`). The code responsible for this can be found in [this comment](https://github.com/laravel/framework/issues/37339#issuecomment-840520926).

Also, which specific test invokes the database seeding? I have many test classes that have the `RefreshDatabase` trait, and some that don't. What if Laravel chooses to run a test that doesn't have this trait as the first test, will the database be seeded or not?

**Comment by 3Descape** [comment]
While writing the tests I only run a single method that I'm working on with BetterPHPUnit and the current behaviour of RefreshDatabase actually executes the seed, as it is the first test that runs, and the test succeeds. Same for running the entire file.

But once I run the entire suite (with multiple testcase files), they test in question fail, as the seed is not executed.
