### ISSUE TITLE
response()->file() return damaged pdf

### ISSUE THREAD

**Issue by michele-grifa** [laravel/framework#37343]
- Laravel Version: 8.40.0
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
i use the following code to return a file from my storage
```php
response()->file(Storage::disk('docuvision')->path($filename))
```

but sometimes when the file is a pdf, in mozilla i get a damaged file.
I temporary resolved the problem using the following code, and i get the right pdf files

```php
$file = Storage::disk('docuvision')->get($filename);
$headers = array(
    'Content-type' => Storage::disk('docuvision')->getMimetype($filename)
);

return Response::make($file, 200, $headers);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by chmoelders** [comment]
Hi @michele-grifa !

I have the same issue. Do you found a solution?
I would be very grateful for a tip.

**Comment by michele-grifa** [comment]
> Hi @michele-grifa !
> 
> I have the same issue. Do you found a solution?
> I would be very grateful for a tip.
> 

I resolved using:
```
$headers=array('Content-Type' => 'mime-type');
return Response::make($file, 200, $headers);
```
