### ISSUE TITLE
Illuminate/View subtree out of sync

### ISSUE THREAD

**Issue by jordyvanderhaegen** [laravel/framework#37342]
- Laravel Version: 8.x
- PHP Version: 8.0
- Database Driver & Version: -

### Description:
The [illuminate/view](https://github.com/illuminate/view) subtree split seems to be out of sync with the actual framework. Can we expect any updates on this or should we just require the entire framework? This is used in [jigsaw](https://github.com/tighten/jigsaw/blob/main/composer.json#L20) for example.

**Comment by taylorotwell** [comment]
Fixed.

**Comment by jordyvanderhaegen** [comment]
Thanks 👍
