### ISSUE TITLE
"There is already an active transaction" when using DB::transaction with Galera

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/framework#37358]
- Laravel Version: 6.20.23
- PHP Version: 7.4.18
- Database Driver & Version: mysql

### Description:
We are receiving the following error when Laravel Horizon workers that create an transaction to a loadbalanced Galera cluster. 
```
[2021-05-12 14:29:18] production.ERROR: There is already an active transaction {"exception":"[object] (PDOException(code: 0): There is already an active transaction at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:133)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(133): PDO->beginTransaction()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(115): Illuminate\\Database\\Connection->createTransaction()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(23): Illuminate\\Database\\Connection->beginTransaction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction(Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#5 /var/www/html/app/Jobs/TestJob.php(66): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\TestJob->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
```
After some debugging and adding a `report($e);` to line 54 of the `Illuminate\Database\Concerns\ManagesTransactions.php` it becomes clear that the commit of the transaction fails with a deadlock. 
```
[2021-05-12 14:29:18] production.ERROR: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction {"exception":"[object] (PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:49)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(49): PDO->commit()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction(Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#3 /var/www/html/app/Jobs/TestJob.php(66): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\TestJob->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
```
This error on commit can occour due to the nature of Galera's optimistic locking. And when this happens the transaction is never rolledback. Which results in the `There is already an active transaction` exception. 

I believe that when a commit fails it should still rollback the transaction instead of doing nothing.

### Steps To Reproduce:

I'm afraid its fairly hard to reproduce, but if anyone wants to try. You'll need:
- A connection to a load balanced Galera cluster (multi-node)
- Horizon queue with multiple workers, for example:
```
'supervisor-test' => [
    'connection' => 'redis',
    'queue' => ['test'],
    'balance' => 'auto',
    'processes' => 10,
    'tries' => 1,
],
```
- A command that spawns the job to the worker, for example:
```
for ($i = 0; $i < 1000; $i++) {
    $job = new TestJob();

    dispatch($job->onQueue('test'));
}
```
- A TestJob that uses the DB::transaction wrapper
```
$first = DB::table('test_one')->first();

// Fails.
DB::transaction(function () use ($first) {
    DB::table('test_one')->where('id', $first->id)->update([
        'number' => DB::raw('number + ' . 1),
    ]);
});

// Works.
// try {
//     DB::beginTransaction();

//     DB::table('test_one')->where('id', $first->id)->update([
//         'number' => DB::raw('number + ' . 1),
//     ]);

//     DB::commit();
// } catch (\Exception $e) {
//     Log::info($e);

//     DB::rollback();
// }
```

The first method fails, the last one works due to the DB:commit being wrapped inside the try/catch.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jeffreyzant** [comment]
This is actually not a question, but a bug report. I believe the commit inside the DB::transaction should rollback when receiving a deadlock exception.

**Comment by micobarac** [comment]
I am having the same issues...

[https://github.com/laravel/framework/issues/21725#issuecomment-901648783](https://github.com/laravel/framework/issues/21725#issuecomment-901648783)

**Comment by erikvanzijst** [comment]
Same.

/CC @driesvints

**Comment by AllexNogue** [comment]
O Mesmo 

> I am having the same issues...
> 
> [#21725 (comment)](https://github.com/laravel/framework/issues/21725#issuecomment-901648783)
> 
> I couldn't find any explanation or solution on forums listed above. Can anyone look into it?
> 
> The database is Gallera cluster, Laravel 8.

**Comment by foremtehan** [comment]
I have an infinite loop of this error on my queue workers

**Comment by mnoquiao** [comment]
Does anybody able to solve this issue? I am having this issue in related to my queue jobs.

**Comment by mnoquiao** [comment]
Does anybody able to solve this issue? I am having this issue related to my queue jobs.

**Comment by jeffreyzant** [comment]
The only way we managed to get rid of the error is by configuring a read/write setup. We've created a tool with Go that selects a sticky node for writing and swaps when a cluster node is down. Reads are done through all the cluster nodes with the normal Galera service.

The database.php configuration looks like:
```
        'mysql' => [
            'driver' => 'mysql',
            'read' => [
                'host' => [
                    env('DB_HOST', 'localhost'),
                ],
            ],
            'write' => [
                'host' => [
                    env('DB_HOST_WRITE', null) ?? env('DB_HOST', 'localhost'),
                ],
            ],
            'sticky' => true,
            ...
        ],
```

**Comment by sagar03d** [comment]
As a last resort, I had to add the queue:restart command to my cron job to handle this error.

**Comment by sagar03d** [comment]
> The only way we managed to get rid of the error is by configuring a read/write setup. We've created a tool with Go that selects a sticky node for writing and swaps when a cluster node is down. Reads are done through all the cluster nodes with the normal Galera service.
> 
> The database.php configuration looks like:
> 
> ```
>         'mysql' => [
>             'driver' => 'mysql',
>             'read' => [
>                 'host' => [
>                     env('DB_HOST', 'localhost'),
>                 ],
>             ],
>             'write' => [
>                 'host' => [
>                     env('DB_HOST_WRITE', null) ?? env('DB_HOST', 'localhost'),
>                 ],
>             ],
>             'sticky' => true,
>             ...
>         ],
> ```

since I am handling this with a load balancer, it look like this 
```'mysql' => [
            'read' => [
                'host' => [
                    env('DB_READ_HOST', '127.0.0.1'),
                ],
            ],
            'write' => [
                'host' => [
                    env('DB_WRITE_HOST', '127.0.0.1'),
                ],
            ],
            'sticky' => true,
            'driver' => 'mysql',
```

but still not working for me
