### ISSUE TITLE
Malformed DSN string creation in PostgresConnector if database name is null

### ISSUE THREAD

**Issue by jonagoldman** [laravel/framework#37353]
Laravel Version: 8.41.0
PHP Version: 8.0.1
Database Driver & Version: PostgreSQL 13.2

If the database name is null or not set, the `getDsn` method will return a malformed string:

```
"pgsql:host=127.0.0.1;dbname=;port=5432"
```

This sets `dbname` to `port=5432` and throws an exception:

```php
SQLSTATE[08006] [7] FATAL:  database "port=5432" does not exist 
```

This is because the `dbname` is concatenated without checking:

https://github.com/laravel/framework/blob/4ffb75c3f30ff3f4a9b1c1f7fb297ea153d1e71a/src/Illuminate/Database/Connectors/PostgresConnector.php#L149

As a side note, not forcing the database name on the connection can be useful,
for example to create the first server database with `Schema::createDatabase('my_db')`.

**Comment by driesvints** [comment]
Looks like more of a feature request than a bug to me. Feel free to attempt a PR, thanks.
