### ISSUE TITLE
FileStore and ArrayStore expiration inconsistency

### ISSUE THREAD

**Issue by AidasK** [laravel/framework#37361]
- Laravel Version: 8.41.0
- PHP Version: 7.4.1
- Database Driver & Version: x

### Description:
https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Cache/FileStore.php#L258
https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Cache/ArrayStore.php#L60

Array cache expires if expiry date is greater than or equal in seconds as of now and file cache expires if expiration date is greater than.

Tried writing a unit test for RateLimiter and after switching the driver my tests crashed. Drivers should be consistent even if it's only one second difference.

IMO FIleCache implementation is correct one.

**Comment by driesvints** [comment]
If I update the array store to the same behavior of filestore I get a bunch of failing tests. If you really believe this behavior should be fixed feel free to send in a PR with passing tests 👍
