### ISSUE TITLE
Yield default value and variable

### ISSUE THREAD

**Issue by Korko** [laravel/framework#37364]
- Laravel Version: 8.41.0
- PHP Version: 8.0.5
- Database Driver & Version:

### Description:
If I put a variable in the default value of a yield, I have the php exposed.

### Steps To Reproduce:
I have a variable targetName defined in the blade file,
I have a `@yield('title', 'Message from {{ $targetName }}')`
When displayed, I have `Message from <?php echo e(A); ?>`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Korko** [comment]
Not sure the answer is appropriate. It is not a question, I don't need answer. If the behavior would be not to parse variables, then I would have "Message from {{ $targetName }}" but I have the PHP exposed and that is a bug. Either Blade parse the variable AND eval the php or is does neither.

**Comment by BrandonSurowiec** [comment]
Try `@yield('title', "Message from {$targetName}")`

**Comment by Korko** [comment]
That work for sure but I insist that showing PHP to the user is a bug. Either you don't parse the mustache syntax and let the variable as is or you fully parse the php too.
