### ISSUE TITLE
Route-Cache issue with Closures not named "uses"

### ISSUE THREAD

**Issue by kronthto** [laravel/framework#37375]
- Laravel Version: v8.41.0
- PHP Version: 8.0.2
- Database Driver & Version: -

### Description:

A route that uses an "unnamed" (i.E. by the array index "uses") Closure **in the options array** is (arguably not good style but) apparently valid and the route resolves:
```php
Route::get('/', [function () {
    return view('welcome');
}]);
```
There is code and a comment that does it so I suppose it's intended: https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Routing/RouteAction.php#L39-L44

However, the `route:cache` seems to not consider that case fully: https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Routing/Route.php#L1196-L1206

And generates in `routes-v7.php` both, the `uses` as the Opis Closure but also the array index 0 with a `Closure::__set_state`:
```php
      'action' => 
      array (
        'middleware' => 
        array (
          0 => 'web',
        ),
        0 => 
        Closure::__set_state(array(
        )),
        'uses' => 'C:32:"Opis\\Closure\\SerializableClosure":256:{@uH+RkO598+i+UXP1lH/+ZuFm23DDPBZwco8GD69jcGI=.a:5:{s:3:"use";a:0:{}s:8:"function";s:44:"function () {
    return \\view(\'welcome\');
}";s:5:"scope";s:37:"Illuminate\\Routing\\RouteFileRegistrar";s:4:"this";N;s:4:"self";s:32:"000000003139b27a000000001223ca07";}}',
```

--> Which then causes the error (on web calls): 
**"Call to undefined method Closure::__set_state()"**

### Steps To Reproduce:

Literally just a clean `laravel new` and add 2 square brackets around the default example route Closure:

**Comment by driesvints** [comment]
That's not a valid use case afaik and I don't think we document that anywhere I believe.

**Comment by kronthto** [comment]
:+1: It's probably a fragment from Laravel 4 times indeed that that survived. Introduced in https://github.com/laravel/framework/commit/a4d8d950e49dc7d0de153513994a23e9343cfd4e#diff-efe2a07687b9b821bbd99ae38a9329253f032e6df04bdea02bba9303a2b2beadR543 it is VERY old. The "style" was mentioned in 5.2 docs too, but removed from the docs in 5.3 .
I just happened to upgrade a Laravel 5 project to v8 recently that was/is using this all over the routes.
