### ISSUE TITLE
assertJsonValidationErrors false positive

### ISSUE THREAD

**Issue by damieneskimo** [laravel/framework#37378]
- Laravel Version: 8.40.0
- PHP Version: 7.3
- Database Driver & Version: mysql 8.0

### Description:
assertJsonValidationErrors gives false positive on multiple fields validation.

### Steps To Reproduce:
```
      $data = [
            'name' => '', // required field
            'email' => '' // required field
      ];
     // or $data = [];

      $this->postJson('api/users', $data)
            ->assertStatus(422)
            ->assertJsonValidationErrors(
                ['name']
            );
```

This will pass, which I expect to fail because name and email fields are both required and should be both in the validation errors. Is it intentional or I am doing something wrong? Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
