### ISSUE TITLE
Some generator commands don't use custom stubs

### ISSUE THREAD

**Issue by Radiergummi** [laravel/framework#37389]
- Laravel Version: 8.37.0
- PHP Version: 8.0.5
- Database Driver & Version: --

### Description:
Using `artisan stub:publish`, you can [publish the stubs](https://laravel.com/docs/8.x/artisan#stub-customization) used by the various `make:*` commands of the framework. Some commands, however, ignore custom stubs, and none are published for them either.  
This seems to be an oversight: We should be able to use a custom stub for those classes, too.

#### Commands disregarding custom stubs
- [`make:channel`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/ChannelMakeCommand.php#L50-L53)
- [`make:component`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/ComponentMakeCommand.php#L122-L125)
- [`make:event`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/EventMakeCommand.php#L47-L50)
- [`make:exception`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/ExceptionMakeCommand.php#L36-L47)
- [`make:notification`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/NotificationMakeCommand.php#L87-L92)
- [`make:listener`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/ListenerMakeCommand.php#L64-L75)
- [`make:mail`](https://github.com/laravel/framework/blob/11387ec9b12703fdaef6013fd9e7143594b5d91a/src/Illuminate/Foundation/Console/MailMakeCommand.php#L87-L92)
- [`make:provider`](https://github.com/laravel/framework/blob/ac2a366a200ba2d806c22bf5d80b706d91664140/src/Illuminate/Foundation/Console/ProviderMakeCommand.php#L35-L38)

### Steps To Reproduce:

 1. Execute `php artisan stub:publish`
 2. Notice the lack of eg. `./stubs/notification.stub` and `./stubs/markdown-notification.stub`
 3. Create `notification.stub` manually: `touch ./stubs/notification.stub`
 4. Create a notification using artisan: `php artisan make:notification`
 5. A notification is created using the default stub at [`src/Illuminate/Foundation/Console/stubs/notification.stub`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/stubs/notification.stub)

These steps may be repeated with any of the commands listed above.

I'll gladly submit a PR, unless this behavior is intentional for some reason. In general, I believe the `resolveStubPath` method employed by _some_ make commands should be moved into [`GeneratorCommand`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/GeneratorCommand.php), so all generators may resolve stubs uniformly.

**Comment by driesvints** [comment]
This seems like a feature request. Feel free to submit a PR. Please be aware that some stubs have been rejected in the past. Search for these PR's before submitting. Thanks

**Comment by Radiergummi** [comment]
@driesvints I'd rather consider it inconsistent and undocumented behavior of the framework, but I'll go with the flow. PR incoming soon. Thanks
