### ISSUE TITLE
Primitive contextual binding does not work with Blade components 

### ISSUE THREAD

**Issue by felixdorn** [laravel/framework#37381]
- Laravel Version: 8.41.0
- PHP Version: 8.0.5

### Description:

```php
// app/Providers/AppServiceProvider.php in the register() method
$this->app
    ->when(Honda\Ui\Components\Input::class)
    ->needs('$color')
    ->give('blue');
```

```php
namespace Honda\Ui\Components;

class Input {
    public function __construct(
        public string $color
   ) {}
}
```

```html
<x-ui-input />
```

This throws :

```
Unresolvable dependency resolving [Parameter #1 [ <required> string $color ]] in class Honda\Ui\View\Components\Input
```

But the expected behavior is that the container properly resolves the input with contextual bindings when available and needed.

If this is an actual issue and not me being stupid in which case I apologize, I can submit a PR, no problem.

**Comment by driesvints** [comment]
This indeed isn't supported.
