### ISSUE TITLE
Scheduler runInBackground is not working with appendOutputTo/sendOutputTo

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#37382]
- Laravel Version: 7.28.4
- PHP Version: 7.4.16
- Database Driver & Version: MySQL 5.7.26

### Description:
It seems that `runInBackground`  and `appendOutputTo/sendOutputTo` can't work together.

### Steps To Reproduce:
For simplicity I created dummy Command which only outputs a line `$this->info('This is output');` inside `handle` method.

When I call this command in scheduler it outputs "This is output" in file:
```
$schedule->command('dummy')
    ->everyMinute()
    // ->runInBackground()
    ->appendOutputTo($filepath);
```
But when I uncomment `runInBackground` and run again I get this in my file `^C`, and there is no output.

**Comment by driesvints** [comment]
This is expected. Running the command in the background won't output anything.

**Comment by kikky7** [comment]
Then how to track commands that run in the background without including Horizon or custom logging in handlers?
