### ISSUE TITLE
eloquent memory esage

### ISSUE THREAD

**Issue by vadimoncheck** [laravel/framework#37386]
on each iteration there is a request in a DB and after each request the volume of the used memory increases
```for ($i = 1; $i < 10000; $i++) {
            if ($i % 2) {
                $q = '+';
            } else {
                $q = '-';
            }
            Period::select('id')->where('name', '=', 'Production Base Values 21-04')->first();
            $a  = 1 . $q . $i;
            file_put_contents('test.txt', "iteration - $i - " . memory_get_usage() . "\n", FILE_APPEND);
        }
        dd(\DB::getQueryLog());```

iteration - 1 - 27805632
iteration - 2 - 27810616
iteration - 3 - 27815600
iteration - 4 - 27820584
iteration - 5 - 27825568
iteration - 6 - 27830552
iteration - 7 - 27835536
iteration - 8 - 27840840
iteration - 9 - 27845824
iteration - 10 - 27850808
iteration - 11 - 27855792
iteration - 12 - 27862056

iteration - 9982 - 72468912
iteration - 9983 - 72473264
iteration - 9984 - 72477616
iteration - 9985 - 72481968
iteration - 9986 - 72486320
iteration - 9987 - 72490672
iteration - 9988 - 72495024
iteration - 9989 - 72499376
iteration - 9990 - 72503728
iteration - 9991 - 72508080
iteration - 9992 - 72512432
iteration - 9993 - 72516784
iteration - 9994 - 72521136
iteration - 9995 - 72525488
iteration - 9996 - 72529840
iteration - 9997 - 72534192
iteration - 9998 - 72538544
iteration - 9999 - 72542896

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
