### ISSUE TITLE
Class League AwsS3Adapter not found in FilesystemManager

### ISSUE THREAD

**Issue by aureliotechnology** [laravel/framework#37383]
- Laravel Version: 8.12
- PHP Version: 7.4.16
- Database Driver & Version: PostgreSQL 12

### Description:
When trying to use the Storage class to list a directory with the code below:
`$directories = Storage::disk('s3')->allDirectories("/");`

I got the following error:
> Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found

I checked the files in the vendor folder and they are all there. I'm using version 1.0 of league / flysystem-aws-s3-v3 as you can see below in my composer require.

>"require": {
>>"php": "^7.3|^8.0",
>>"fideloper/proxy": "^4.4",
>>"fruitcake/laravel-cors": "^2.0",
>>"guzzlehttp/guzzle": "^7.0.1",
>>"laravel/framework": "^8.12",
>>"laravel/tinker": "^2.5",
>>"league/flysystem-aws-s3-v3": "^1.0",
>>"league/flysystem-cached-adapter": "^1.1",
>>"paquettg/php-html-parser": "^3.1",
>>"tymon/jwt-auth": "^1.0"
>}

I am without direction of what may be wrong, I appreciate any help.

**Comment by driesvints** [comment]
Not sure what's wrong there because it's definitely there: https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/src/AwsS3Adapter.php#L17

**Comment by aureliotechnology** [comment]
This is exactly the problem, if it is there, why is it giving an error?

**Comment by driesvints** [comment]
Please try a support channel:  

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
