### ISSUE TITLE
Paginators in JsonResources are calling toArray() on items twice

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#37395]
- Laravel Version: 8.41.0
- PHP Version: 8.0.6
- Database Driver & Version: mysql 8

### Description:
In `(Cursor)Paginator->toArray()` (see [here](https://github.com/laravel/framework/blob/5894ac9e4101e3d06f40edc6bb632c4d9a0c1b33/src/Illuminate/Pagination/CursorPaginator.php#L129-L138) or [here](https://github.com/laravel/framework/blob/5894ac9e4101e3d06f40edc6bb632c4d9a0c1b33/src/Illuminate/Pagination/Paginator.php#L141-L154)) the method iterates over all items, calling `toArray()` to create the `data` key for normal, paginated responses.

However, in case a paginator is being used inside a `JsonResource`, this will:
1. Create the `data` array using the `JsonResource(Collection)`
2. Create a `data` array using the `Paginator` when calling `PaginatedResourceResponse::paginationInformation`
3. Merge everything but the paginator `data` into the resource response

Hence, the models are being iterated over twice.

Here's a timeline screenshot from Blackfire showing the initial, unnecessary iteration:
![image](https://user-images.githubusercontent.com/429147/118626002-c9b08e00-b7ca-11eb-984e-34dcd2b72b8f.png)

### Steps To Reproduce:

1. Create a model + JsonResource
2. Call `ModelResource::collection(Model::query()->paginate())` in a controller

**Comment by driesvints** [comment]
Feel free to PR something if you think this can be improved. Closing this as nothing is really broken here.
