### ISSUE TITLE
Parent placeholder rendered in view

### ISSUE THREAD

**Issue by SamSalvatico** [laravel/framework#37396]
- Laravel Version: v8.41.0
- PHP Version: 8.0.5
- Sail Version: v1.5.1

### Description:
I have an _a.blade.php_ view that, in body, contains a _@yield_ directive like this

`@yield('post_body_scripts')`

Then, the view is included in another one, _b.blade.php_ that holds data for the _post_body_scripts_ section

```
@extends('partials.layouts.app')
...
@include('c', ['foo' => 'bar'])
@section('post_body_scripts')
    <script src="{{ asset('js/b.js') }}"></script>
@endsection
```

The included _c_ view contains another part of the _post_body_scripts_ section

```
@section('post_body_scripts')
@parent
<script src="https://cdn/ajsfile.js"></script>
@endsection
```

The **@parent** directive correctly works, but an hashtag starting placeholder is shown when the render of the view starts

```
<?php $__env->startSection('post_body_scripts'); ?>

##parent-placeholder-1a5ac98c3addb84257eb2d5b7ffee8f1cbf3b352##
<script src="https://cdn/ajsfile.js"></script>
<?php $__env->stopSection(); ?><?php /**PATH /var/www/html/resources/views/c.blade.php ENDPATH**/ ?>
```

### Steps To Reproduce:

1. Create a base view that contains a _@yield_ directive;
2. Create a view that extends the previous one and uses a _@section_ directive for the previous _yield_;
3. Include, in the view created at point 2, another sub view;
4. In the view included at point 3, use a _@section_ directive that starts with _@parent_ for the declared _yield_.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
