### ISSUE TITLE
`SessionGuard::logout()` doesn't remove `password_hash` from session

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#37393]
- Laravel Version: 8.36.0
- PHP Version: 8.0.x
- Database Driver & Version: MySQL 8.0

### Description:

`SessionGuard::logout()` doesn't remove `password_hash` from the session and for this reason `AuthenticateSession` middleware will throw an "Unauthenticated" error if login as the second user.

![image](https://user-images.githubusercontent.com/1329824/118618138-5e6bb980-b7d4-11eb-9c8b-30f56ad074fa.png)

There are a lot of issues about this problem (#31621, #27105, #2345, etc) but it still exists.

### Steps To Reproduce:

1) Login as User 1 via `SessionGuard::attempt()`
2) `SessionGuard::logout()`
3) Login as **User 2 with different password**(!) via `SessionGuard::attempt()`

**Comment by driesvints** [comment]
I don't get the same with these steps. It works just fine for me.

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by layerok** [comment]
This problem still exists

**Comment by layerok** [comment]
Here is a pest test for this bug

```php
test('user is not automatically logged out after logging in as a different user', function (): void {
    // this test ensures that we fixed this bug https://github.com/laravel/framework/issues/37393
    withoutExceptionHandling();

    $password1 = 'password1';
    $password2 = 'password2';

    $user1 = User::factory()->create([
        'email' => 'user@exonn.de',
        'password' => Hash::make($password1),
    ]);

    $user2 = User::factory()->create([
        'email' => 'different-user@exonn.de',
        'password' => Hash::make($password2),
    ]);

    $commonHeaders = [
        'accept' => 'application/json',
        'referer' => config('sanctum.stateful')[0],
    ];

    post(route('auth.login-browser'), [
        'email' => $user1->email,
        'password' => $password1,
    ], $commonHeaders)->assertStatus(200);

    get(route('auth.get-authenticated-user'), $commonHeaders)->assertStatus(200);

    // we reset auth guard to 'web' after each request
    // to match real world scenario
    // in real world the auth guard is reset automatically after each request
    // but in test environment we need to do it manually
    Auth::shouldUse('web');

    post(route('auth.logout-browser'), [], $commonHeaders)->assertStatus(200);

    Auth::shouldUse('web');

    post(route('auth.login-browser'), [
        'email' => $user2->email,
        'password' => $password2,
    ], $commonHeaders)->assertStatus(200);

    Auth::shouldUse('web');

    get(route('auth.get-authenticated-user'), $commonHeaders)->assertStatus(200);
});
```

Here is routes
```php
Route::post('login/browser', [AuthController::class, 'loginBrowser'])->name('auth.login-browser');
Route::middleware('auth:sanctum')->group(static function (): void {
    Route::get('user', [AuthController::class, 'getAuthenticatedUser'])->name('auth.get-authenticated-user');
    Route::post('logout/browser', [AuthController::class, 'logoutBrowser'])->name('auth.logout-browser');
});
```

Here is controller
```php
class AuthController extends Controller
{
    public function loginBrowser(LoginBrowserRequest $request): JsonResource
    {
        $rememberMe = $request->input('remember_me');

        if (! Auth::attempt($request->only(['email', 'password']), $rememberMe)) {
            throw new UnauthorizedHttpException('', 'The provided credentials do not match our records');
        }

        // Fixes https://github.com/laravel/framework/issues/37393
        collect(Arr::wrap(config('sanctum.guard')))->each(fn ($driver) => Session::remove('password_hash_'.$driver));

        return new UserResource(Auth::user());
    }

    public function logoutBrowser(): void
    {
        Auth::guard('web')->logout();
    }

    public function getAuthenticatedUser(): JsonResource
    {
        return new UserResource(Auth::user());
    }
}
```

**Comment by upngo** [comment]
This issue still persists.
When you logout all it does it clear `login_$this->name_XXX` but the password hash is left behind so when you login as another user the password hash from laravel (relating to the second user) doesn't match the password hash in session (relating to first user) and session is flushed and you end up back at login and an empty session so have to try again.

on logout you'll need to call this
`session()->forget('password_hash_web')`

This bug has been around for years and gets ignored every time so unlikely to be fixed...
#23457 
#27105
