### ISSUE TITLE
Boot method in service provider won't fire

### ISSUE THREAD

**Issue by MarekGogol** [laravel/framework#37403]
- Laravel Version: v8.42.0
- PHP Version: 8.0.5

### Description:
If service provider is registered in other service provider in boot state, boot method won't fire in registered provider. Behaviour broken/changed in v8.42.0. In previous version v8.41.0 works as expected.

### Steps To Reproduce:
1. Clone repo https://github.com/MarekGogol/laravel-test
-> TestServiceProvider is registred in AppServiceProvider, boot method should fire. In previous laravel version this method fires...
2. Run app, and you should see dd('booted') from App/Providers/TestServiceProvider

**Comment by it-can** [comment]
Take a look at this commit

https://github.com/laravel/framework/commit/90ad97ca05ad10370122c5cdab59cf61125944c6

could you test if this could be it?

**Comment by MarekGogol** [comment]
> Take a look at this commit
> 
> [90ad97c](https://github.com/laravel/framework/commit/90ad97ca05ad10370122c5cdab59cf61125944c6)
> 
> could you test if this could be it?

Yes, foreach causes problem. array_walk works fine.

**Comment by ConsoleTVs** [comment]
Yup, there's a PR to revert it. Sorry guys!

**Comment by parsagholipour** [comment]
PHP foreach doesn't traverse the appended items inside the block.

**Comment by realtebo** [comment]
It's a pity that NO TEST CASE detected this issue

**Comment by ConsoleTVs** [comment]
An open PR was added to fix this @realtebo

**Comment by taylorotwell** [comment]
Fixed by 8.42.1
