### ISSUE TITLE
Accessor to the $appends of the model, the processing is 4x slower. 

### ISSUE THREAD

**Issue by maiconmva** [laravel/framework#37404]
- Laravel Version: 8.42.0
- PHP Version: 7.4.11
- Database Driver & Version: mysql

### Description:

hello guys, 
I don't know if anyone has been there, 

if I add the Accessor to the $appends of the model, the processing is 4x slower. 

I did a test, took the $appends out of the model and went through the records and filled it out through the accessor and it was much faster, 

see the examples of my tests .. does anyone know anything?

![image](https://user-images.githubusercontent.com/5194641/118723837-42800c00-b804-11eb-89ba-49346f822d80.png)

**Comment by maiconmva** [comment]
here is a simple example

![image](https://user-images.githubusercontent.com/5194641/118727217-cfc55f80-b808-11eb-83ad-6ea155f5732b.png)

and this is the acessors, all attributes are on database, so nothing of much processing

![image](https://user-images.githubusercontent.com/5194641/118727254-dfdd3f00-b808-11eb-9885-68541246a05c.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
