### ISSUE TITLE
Migrate failed to drop default constrains in an mssql databases

### ISSUE THREAD

**Issue by MichaelGottschlich** [laravel/framework#37419]
Hi,

if you work in a MSSQL database not in the default schema dbo, then faild to delete default constraint via "php artisan migrate".
The problem is in the function compileDropDefaultConstraint in class Illuminate\Database\Schema\Grammars\SqlServerGrammar . In the function the dbo schema is hard coded. 

in Illuminate\Database\Schema\Grammars\SqlServerGrammar.php
```
    /**
     * Compile a drop default constraint command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropDefaultConstraint(Blueprint $blueprint, Fluent $command)
    {
        $columns = "'".implode("','", $command->columns)."'";

        $tableName = $this->getTablePrefix().$blueprint->getTable();

        $sql = "DECLARE @sql NVARCHAR(MAX) = '';";
        $sql .= "SELECT @sql += 'ALTER TABLE [dbo].[{$tableName}] DROP CONSTRAINT ' + OBJECT_NAME([default_object_id]) + ';' ";
        $sql .= 'FROM SYS.COLUMNS ';
        $sql .= "WHERE [object_id] = OBJECT_ID('[dbo].[{$tableName}]') AND [name] in ({$columns}) AND [default_object_id] <> 0;";
        $sql .= 'EXEC(@sql)';

        return $sql;
    }
```
On version "Laravel Framework 8.42.0"

**Comment by taylorotwell** [comment]
I have no plans to look into this on my end so feel free to send a PR.

**Comment by MichaelGottschlich** [comment]
hi,
step to reproduce:

1.  create an new Mircosoft SQL database 
2. create an new schema in the database
3. create an new sql user, set default schema on new schema and get right to create,edit and delte tabelles and data.
4. create new migrate
`
class TEST extends Migration {
    public function up()
    {
        Schema::create('testTable', function (Blueprint $table) {
            $table->integer('id')->autoIncrement();
            $table->date('dateCloumn')->default(DB::raw('GETDATE()'));
            $table->timestamps();
        });
        Schema::table('testTable', function (Blueprint $table) {
            $table->date('dateCloumn')->default(null)->change();
        });
    }
}
`
5. execute migrate
` Illuminate\Database\QueryException 
  SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DF_FDF4D9DA_7A859515' is not a constraint. (SQL: ALTER TABLE testTable DROP CONSTRAINT DF_FDF4D9DA_7A859515)`

**Comment by driesvints** [comment]
@MichaelGottschlich that's not a valid use case. It doesn't makes sense to change a column immediately in the same migration. Does this happen in different migrations?

**Comment by MichaelGottschlich** [comment]
this also happens when you do it in different migrations. 

I just put it in one migration for better reproduction.

**Comment by driesvints** [comment]
Closing this because we only have gotten one report so far for this. We'll not be pursuing a fix for this atm.

**Comment by jlevers** [comment]
I'm running into this problem when trying to rename two columns (and add a column) in the same migration:

```php
class Repro extends Migration
{
    public function up()
    {
        Schema::table('table', function (Blueprint $table) {
            $table->renameColumn('foo', 'bar');  // string column
            $table->renameColumn('asdf', 'qwerty');  // also a string column

            $table->string('xyz')->default('pdq');
        });
    }

    // ...
}
```

Error:

```
Illuminate\Database\QueryException 

SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DF_BFB93FBC_503917DA' is not a constraint. (SQL: ALTER TABLE table DROP CONSTRAINT DF_BFB93FBC_503917DA)
```

**Comment by Pixdigit** [comment]
I'm having the same issue.
This also is a valid use-case when adding a new non-null column without default. SQL Server rejects the statement because the new column will contain null as default however it is marked as non-null. However I want all succinct inserts to explicitly insert a value into the column and not use a default value. Since one cannot do that otherwise apart from raw SQL this is a valid use-case.

**Comment by Pixdigit** [comment]
I've also opened an issue with DBAL. Though I don't know if it makes more sense to use the existing `compileDropDefaultConstraint` from SQLServerGrammar.php or wait on Doctrine/DBAL to fix the issue.
