### ISSUE TITLE
[L8.42] Latest version breaks Laravel Socialite Providers

### ISSUE THREAD

**Issue by robtesch** [laravel/framework#37416]
- Laravel Version: v8.42.0
- PHP Version: 7.4.14
- Database Driver & Version: mysql 8.0.23

### Description:
The latest version of Laravel (v8.42.0) breaks socialite custom providers from the https://socialiteproviders.com/ set of providers (specifically the Microsoft Driver in my case). Reverting to v8.41.0 fixes the issue. My suspicion is that something changed in the events system because these custom socialite providers work by listening for the "\SocialiteProviders\Manager\SocialiteWasCalled" event and then calling the "extendSocialite" method in response to that event.

I have tried to register the provider in AppServiceProvider like so:

```php
$socialite->extend(
                'microsoft',
                function ($app) use ($socialite) {
                    $config = $app['config']['services.microsoft'];
                    return $socialite->buildProvider(MicrosoftSocialiteProvider::class, $config);
                }
            );
```

But this led to another issue of the provider not picking up the provided config.

It might also be worth noting the versions I have for Socialite (v5.2.3) and the provider (4.1.1). Both have not been updated for a at least a few weeks, and I do not believe them to be the cause of this issue since everything works fine with the same versions and Laravel 8.41.0

### Steps To Reproduce:

Standard laravel install of L8.42.0
Install Laravel Socialite - https://laravel.com/docs/8.x/socialite#installation
Install Socialite Microsoft Provider - https://socialiteproviders.com/Microsoft/

Attempt to redirect for Microsoft auth as follows:

```php
return Socialite::driver('microsoft')->redirect();
```

This results in an InvalidArgumentException with the message "Driver [microsoft] not supported."

**Comment by mstaack** [comment]
yeah revert to 8.41 for now. latest master already contains fix for this.

see https://github.com/laravel/framework/pull/37392

**Comment by robtesch** [comment]
Thanks... I've reverted. Luckily this didn't break a bunch of other stuff (I think) and I caught it relatively quickly.
