### ISSUE TITLE
MorphMap does not work at 8.42.0

### ISSUE THREAD

**Issue by lamtranb** [laravel/framework#37415]
- Laravel Version: 8.42.0
- PHP Version: 7.4.13
- Database Driver & Version: PostgreSQL 13.1

### Description:
I can't use morphMap at 8.42.0

### Steps To Reproduce:

Register a morphMap:

```php
Relation::morphMap([
     'user' => User::class,
]);
```
I got

```
Class 'user' not found
```
Here is my full error info:
[https://ideone.com/wayKgv](https://ideone.com/wayKgv)

**Comment by taylorotwell** [comment]
Please try with 8.42.1.

**Comment by lamtranb** [comment]
> Please try with 8.42.1.

Thanks @taylorotwell , it worked.
