### ISSUE TITLE
Upgrade from 8.41 to 8.42 breaks "$this->authorize()"

### ISSUE THREAD

**Issue by realtebo** [laravel/framework#37414]
- Laravel Version: 8.42
- PHP Version: 7.4.14
- Database Driver & Version: mongodb 4.0

### Description:

Today we upgraded from laravel 8.41 o 8.42.

After doing this, all places where we use `$this->authorize()` or `@can` don't work anymore.

I can specify we are using gates and NOT model policies

### Steps To Reproduce:

We are still investigating, 

The only things we do is 
- force laravel/framework versione to 8.42.0 
- do a composer update
- now it's broken
- force downgrade to 8.41.0
- do a composer update
- now it works

Prefectly repeatable in our codebase

### added notes

We are actually investiganting what changed between 8.41 and 8.42 and try to diagnose what insider the framework now breaks our policies (gates, for precision)

**Comment by mstaack** [comment]
probably also related to the array_walk changes...

https://github.com/laravel/framework/pull/37405

**Comment by realtebo** [comment]
"probably", ok

but why closed?
