### ISSUE TITLE
Illuminate\Validation\Rules\Password has same name as Illuminate\Support\Facades\Password

### ISSUE THREAD

**Issue by ashrafbendary** [laravel/framework#37430]
- Laravel Version: 8.42.0
- PHP Version: 7.4
- Database Driver & Version: MySql

### Description:
Illuminate\Validation\Rules\Password has same name as Illuminate\Support\Facades\Password 

and both of them used in ResetsPasswords.php file to enhance reset password rules.

**Comment by crynobone** [comment]
You meant ResetPasswords.php from `laravel/ui`?

https://github.com/laravel/ui/blob/9b5182cf94f60cfe6729dc5daffba792fd7dc0e9/auth-backend/ResetsPasswords.php#L55-L75

**Comment by driesvints** [comment]
Seems like the correct namespace is still used: https://github.com/laravel/ui/blob/9b5182cf94f60cfe6729dc5daffba792fd7dc0e9/auth-backend/ResetsPasswords.php#L73
