### ISSUE TITLE
Required_if in v.6.20.23 broken

### ISSUE THREAD

**Issue by warna720** [laravel/framework#37435]
- Laravel Version: v.6.20.23+
- PHP Version: 8.*
- Database Driver & Version: ...

### Description:
https://github.com/laravel/framework/commit/9e24afbfa89b53a7687f8fa61f45fe068924e5db#diff-70ef27942ad37ee73b4490629b132d4440252c5ecddb3fa171cdab95f55f62a1R1478 breaks how `required_if` worked before.

Previously we specified the rule by `required_if:<field>,1` or `required_if:<field>,0` when `<field>` is a boolean. With this change we need to change `1` to `true` and `0` to `false`.

This change is not documented and is breaking minor update.
Also referring to previously recommended solution: https://github.com/laravel/framework/issues/8194

**Comment by driesvints** [comment]
That commit was later reverted by another PR. The commit you're referencing is a revert of a fix that broke something. In the later merged PR's more fixes were added. Please upgrade to v6.20.27 to see if the later version fixes things for you. If it doesn't please report back and paste a code example that you believe isn't working properly.
