### ISSUE TITLE
UploadFile::fake() not working when fake file uploads in phpunit 

### ISSUE THREAD

**Issue by frank505** [laravel/framework#37445]
my test case looks like this
```
public function test_submit_edit_profile_picture()
    {
        $user = $this->userAccount();

        Storage::fake('local');
        $width = 200;
        $height = 200;
        $file =  UploadedFile::fake()->image('avatar.jpg', $width, $height)->size(100);
        $response =   $this->actingAs($user)->call('PATCH',
            '/panel/profile/edit-profile-picture',
            array(
            '_token' => csrf_token(),
                'file' => $file
        ));

//        Storage::disk('local')->assertExists($file->hashName());

        $response->assertJson([
            'success'=>true
        ]);

    }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
