### ISSUE TITLE
PHP Error when PHP8 named arguments get forwarded using __call() and Illuminate\Support\Traits\ForwardsCalls

### ISSUE THREAD

**Issue by ipontt** [laravel/framework#37452]
- Laravel Version: 8.42.1
- PHP Version: 8.0.6
- Database Driver & Version: sqlite3

### Description:

Using [PHP8's named arguments syntax](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) creates errors when the method gets forwarded.

### Steps To Reproduce:

1. Default laravel installation
2. Uncomment the line on DatabaseSeeder.php
3. Migrate and seed the database (this should give us an users table with some users created.)
4. `php artisan tinker`
```php
use App\Models\User;

// this should give the same result.
User::get()->pluck('id');
User::all()->pluck('id');
User::pluck('id');

// this throws an error
User::pluck(value: 'id');
// this, does not.
User::get()->pluck(value: 'id');
```
Similarly, using a named argument in a migration's default()'s method.
```php
$table->string(column: 'password')->default(value: 'do not actually do this');
```
---
this is because named arguments get passed as associative arrays in the `__call($method, $parameters)`  method.

For example,
 -  `->default('a string')` get turned into `$method = 'default', $parameters = [0 => 'a string']`
 -  `->default(value: 'a string')` get turned into `$method = 'default', $parameters = ['value' => 'a string']`

**Comment by driesvints** [comment]
This indeed isn't supported.
