### ISSUE TITLE
Model factory throws error when using method for() before method times()

### ISSUE THREAD

**Issue by misbahansori** [laravel/framework#37454]
- Laravel Version: 8.40
- PHP Version: 7.4
- Database Driver & Version: sqlite :memory:

### Description:
When I want to create a product using a model factory with this code :
```
$products = Product::factory()
            ->for(Category::factory())
            ->times(10)
            ->create();
```

it will throw an error like this :
`Integrity constraint violation: 19 NOT NULL constraint failed: products.category_id`

But if I reorder the method like this :
```
$products = Product::factory()
            ->times(10)
            ->for(Category::factory())
            ->create();
```
It will successfully create the product.

**Comment by driesvints** [comment]
That's right. `times` or `count` needs to come first because it'll instantiate a new factory.
