### ISSUE TITLE
Parallel testing 

### ISSUE THREAD

**Issue by Livijn** [laravel/framework#37467]
- Laravel Version: 8.42.1
- PHP Version: 8.0.5
- Database Driver & Version: mysql 8.0.23

### Description:
I tried the `php artisan test --parallel` and noticed that 75% of my tests were skipped and the rest threw exceptions like this:
216) Tests\Unit\Requests\SearchRequestTest::it_requires_a_valid_name
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000] [1049] Unknown database 'xxx_test_5'

```
// php artisan test --parallel
FAILURES!
Tests: 216, Assertions: 0, Errors: 216.

// php artisan test
OK (960 tests, 4177 assertions)
```

I am using my default MySQL connection since I use features that doesn't exist in SQLite. I've [read the docs](https://laravel.com/docs/8.x/testing#running-tests-in-parallel) but it doesn't say anything about db drivers.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by monaye** [comment]
@Livijn did you find out the cause of the error?
