### ISSUE TITLE
Password reset e-mail address is duplicating information with custom APP_URL

### ISSUE THREAD

**Issue by andrechalom** [laravel/framework#37462]
- Laravel Version: 8.42.1
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0.23

### Description:
When using a custom APP_URL to serve the application under a http://server/my_app/ location, the e-mail sent to reset password is duplicating the "my_app" portion of the path, so the link ends up in the e-mail as "http://server/my_app/my_app/reset_password/{token}".

### Steps To Reproduce:
- Install Laravel, configure .env to use a custom path APP_URL=http://server/my_app/
- Add "URL::forceRootUrl(env('APP_URL'));" to routes/web.php 
- Attempt to send a password reset e-mail. The e-mail will be sent successfully, but the link will be wrong.

### Idea on how to fix
Class Illuminate\Auth\Notifications\ResetPassword has the following code on lines 69-72:
```php
            $url = url(route('password.reset', [
                'token' => $this->token,
                'email' => $notifiable->getEmailForPasswordReset(),
            ], false));
```

I believe this issue can be resolved by changing that to 

```php
            $url = route('password.reset', [
                'token' => $this->token,
                'email' => $notifiable->getEmailForPasswordReset(),
            ], true);
```

However, as I'm not familiar with Laravel internals, I'm not sure if this will introduce any unforeseen side-effects.

**Comment by driesvints** [comment]
Running Laravel under a subdirectory isn't supported, sorry. Please see the note in the docs.
