### ISSUE TITLE
HasOne ofMany does not apply the callback in the first level of join subqueries

### ISSUE THREAD

**Issue by algm** [laravel/framework#37473]
- Laravel Version: 8.42.1
- PHP Version: 7.4.14
- Database Driver & Version: Mysql 8

### Description:

When you define a One of Many relationship in which you want to remove a global scope from the related subquery, the removal is applied to the inner level of the join subquery but not the first one. In general, any filtering or logic you apply to the subquery is only applied in the inner level. This could be intentional but it would be useful to be able to inject behavior at the first level of the join subquery.

So far I have worked it around by extending the HasOne relationship and overriding the ofMany method behavior to look like this:

```php
<?php

// code ...
 if (isset($closure)) {
      $closure($subQuery);
  }

  if (isset($previous)) {
      $this->addOneOfManyJoinSubQuery($subQuery, $previous['subQuery'], $previous['column']);
  }

// more code ...

```

### Steps To Reproduce:

1. Add an eloquent global scope.
2. Add a one of many relationship and remove the global scope from the subquery callback.
3. Run any query using the relationship. The global scope will still be there.

I'll add a related pull request whenever I have time to reproduce (and maybe try to fix) the issue.

**Comment by taylorotwell** [comment]
Ping @cbl

**Comment by cbl** [comment]
@algm You can disable global query scopes at runtime:
```php
public function latestLogin()
{
    $this->withoutGlobalScopes();

    return $this->hasOne(...)->ofMany(...);
}
```

**Comment by jtomek** [comment]
For anybody looking for a solution how to disable global scopes on a related model

```php

public function currentResult()
{
    return $this
        ->hasOne(Data::class)
        ->ofMany(['id' => 'max'], fn ($query) => $query->withoutGlobalScopes());
}
```
