### ISSUE TITLE
withoutWrapping not working for Collection Resources !

### ISSUE THREAD

**Issue by LastRemaining** [laravel/framework#37472]
- Laravel Version: 8.40.0
- PHP Version: 8.0.0

### Description:
`<?php

namespace App\Providers;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        JsonResource::withoutWrapping();
    }
}`

`new UserResource(User::find(1)); // returns unwrapped data`

`UserResource::collection(User::all()); // returns wrapped data`

I used Illuminate\Http\Resources\Json\ResourceCollection::withoutWrapping() but nothing changed.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
