### ISSUE TITLE
v8.43.0 new methods break widely used NestedSet package for omonimy

### ISSUE THREAD

**Issue by realtebo** [laravel/framework#37486]
- Laravel Version: 8.43.0
- PHP Version: <any>
- Database Driver & Version: <ininfluent>

### Description:

See this: https://github.com/lazychaser/laravel-nestedset/issues/509#issuecomment-848531323

### Steps To Reproduce:

We are using backpack for laravel with nested set package. It's a common scenario.

the nested set package has a function named  `getRelationQuery `

So when backpack call this function, in v8.42 all works, but in v8.43 it breaks because your newly introduced function name

Due to large diffusion of nested set usage we ask you kindly to rename the new function

**Comment by driesvints** [comment]
Adding new methods to the public API is allowed under SemVer. We're sorry that something breaks for you but we won't be reverting this. The package will need to make adjustments I'm afraid. Sorry about this.

**Comment by realtebo** [comment]
> Adding new methods to the public API is allowed under SemVer. We're sorry that something breaks for you but we won't be reverting this. The package will need to make adjustments I'm afraid. Sorry about this.

Yes I know. But the nested set package is widely used and v 8.43.0 is new, I am sure you will not break anything with a rename. 

I kindly you to be fair in respect of other open source projects. I ask you an exception.
