### ISSUE TITLE
Laravel model attributes not properly casting after refreshing

### ISSUE THREAD

**Issue by tantee** [laravel/framework#37488]
- Laravel Version: 8.43.0
- PHP Version: 8.0
- Database Driver & Version: MySQL 8

### Description:
Model attributes did not get casting properly after refreshing.

### Steps To Reproduce:
1. get model instance, change some values and save
2. refreshing model by call fresh() method
3. attributes are not casting

Code example

`$user = \App\Models\Users::find(1);`
`$user->name = "new name"; //at this time created_at was casted as Carbon Datetime`
`$user->save();`
`$user->fresh(); //$user->created_at was not casted and will be string`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
