### ISSUE TITLE
artisan schedule:work  It can only be run in the same directory as the artisan file, otherwise the report

### ISSUE THREAD

**Issue by OneSeven** [laravel/framework#37499]
- Laravel Version: 8.41.0
- PHP Version: 7.3.28
- Database Driver & Version: Mysql5.7

### Description:
php artisan schedule:work 
It can only be run in the same directory as the artisan file, otherwise the report: Could not open input file: artisan
Such as: php /home/project/artisan schedule:work error!
php artisan schedule:work is normal

### Steps To Reproduce:

Such as: php /home/project/artisan schedule:work error!
php artisan schedule:work is normal

**Comment by themsaid** [comment]
`php /home/project/artisan schedule:work` works fine. Contact your server administrator to debug the issue for you.

**Comment by OneSeven** [comment]
> `php /home/project/artisan schedule:work` works fine. Contact your server administrator to debug the issue for you.

![dasda](https://user-images.githubusercontent.com/17974392/119789958-181a0700-bf06-11eb-8efb-f4433f1290b4.png)

I am sure that there will be a problem
Same on windows and linux
