### ISSUE TITLE
[6.0] Required Validation rule allows empty string.

### ISSUE THREAD

**Issue by minedun6** [laravel/framework#37502]
- Laravel Version: 6.18.43
- PHP Version: 7.226

### Description:
Validation rule **required** return true also on empty string.
It should not pass, right ?

![Capture d’écran 2021-05-27 à 12 36 57](https://user-images.githubusercontent.com/4510058/119819437-4983da00-bee8-11eb-861a-da6789661d36.png)

### Steps To Reproduce:
![Capture d’écran 2021-05-27 à 12 37 56](https://user-images.githubusercontent.com/4510058/119819538-5f919a80-bee8-11eb-8254-1d4561f04596.png)

**Comment by driesvints** [comment]
Works fine for me on latest 6.x release: 

```php
Route::get('/', function () {
    return dd(\Validator::make(['foo' => ''], ['foo' => 'required'])->passes());
});
```

![Screenshot 2021-05-27 at 14 12 15](https://user-images.githubusercontent.com/594614/119823839-8bffe380-bef5-11eb-844c-b084e27a75ff.jpg)
