### ISSUE TITLE
Multiple events in Eloquent model registered but not fired

### ISSUE THREAD

**Issue by Develgold** [laravel/framework#37500]
- Laravel Version: v8.43.0
- PHP Version: 8.0.0
- Database Driver & Version: PostgreSQL 12

### Description:
![изображение](https://user-images.githubusercontent.com/27425101/119790018-024c1800-beed-11eb-8970-6329868b5e70.png)

![изображение](https://user-images.githubusercontent.com/27425101/119790658-8bfbe580-beed-11eb-9cd9-2246b03813b7.png)

![изображение](https://user-images.githubusercontent.com/27425101/119790495-6b339000-beed-11eb-9991-9c679df0cf44.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Develgold** [comment]
I thought it was a bug since the events were registered but not fired.
