### ISSUE TITLE
float values not increment correctly in Cache::increment()

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#37522]
- Laravel Version: 8.42.1
- PHP Version: 8.0.5

### Description:
When i want to increment the cache key by floats the results doesnt count the number from the right side.

### Steps To Reproduce:

```php
Cache::increment('key', 1.5);
Cache::increment('key', 1.5);

should be 3, but the result is 2.5
```

**Comment by driesvints** [comment]
You can only use integers.

**Comment by foremtehan** [comment]
@driesvints 

https://github.com/laravel/framework/blob/593f0dde0b64f6850a226ebcdb36700ad4ca6276/src/Illuminate/Cache/FileStore.php#L164-L171

The only issue is the `(int)` cast, There is no way i can make my own macro because the `getPayload` method is protected, the timestamp is important

**Comment by driesvints** [comment]
Only integers are supported: https://laravel.com/docs/8.x/cache#incrementing-decrementing-values

![Screen Shot 2021-05-28 at 16 49 54](https://user-images.githubusercontent.com/594614/120002080-bd9bac00-bfd4-11eb-9d8a-efb1e80e5312.jpg)

**Comment by foremtehan** [comment]
Another thing, the `+` operator cast the values to the number no need to cast manually imo
