### ISSUE TITLE
Weird numeric constraint behaviour

### ISSUE THREAD

**Issue by SCIF** [laravel/framework#37529]
- Laravel Version: 8.40.0
- PHP Version: 7.4.19
- Database Driver & Version: doesn't matter

### Description:

A quote from https://laravel.com/docs/8.x/validation#rule-numeric

> nullable
> The field under validation may be null.
>
> numeric
> The field under validation must be [numeric](https://www.php.net/manual/en/function.is-numeric.php)

So when I supply a value `''` I'm expecting to have a failure as none of rules are met.

### Steps To Reproduce:
```php ./artisan tinker
$v = app('validator');
$try = $v->make(['empty' => ''], ['empty' => 'nullable|numeric');
>>> $try->validated();
=> [
     "empty" => "",
   ]
>>> is_numeric('');
=> false
```

**Comment by devcircus** [comment]
Might be the "ConvertEmptyStringsToNull" middleware that runs by default in Laravel applications. You should be able to remove that from the kernel.php and get the result you want. However, you may want to rethink the logic, as converting empty strings to null is the most common way of handling empty strings in form submissions.

**Comment by SCIF** [comment]
Hi @devcircus , sorry but your suggestion is actually a workaround for sourcing data from a request. The question is about validation and constraints so doesn't matter where the data comes from.

**Comment by driesvints** [comment]
So the way the validator works is that it'll allow the data to pass when it's not "required". You aren't requiring `empty` to be present so therefor it's not checked to be `numeric` either. It passes because an empty string doesn't holds a value in the validator's eyes and therefor can pass through. If you add `required` to your ruleset you should get the behavior that you're looking for:

```php
$v->make(['empty' => ''], ['empty' => 'required|numeric');
```

**Comment by SCIF** [comment]
Hi @driesvints , thanks for the response.

However, it's far from obvious behavior and must be clearly stated.

Moreover, it doesn't work and doesn't provide the required (and clearly explained in docs) behavior:

```
$try = $v->make(['empty' => null], ['empty' => 'numeric|required']);
>>> $try->errors()->all();
=> [
     "The empty must be a number.",
     "The empty field is required.",
   ]
```

**Comment by driesvints** [comment]
@SCIF in that case you need to add the nullable rule as well. We definitely welcome prs to the docs if you think something can be more clear 👍

**Comment by SCIF** [comment]
Hi @driesvints , I checked that behavior before filing this issue:

```>>> $try = $v->make(['empty' => null], ['empty' => 'numeric|required|nullable']);
>>> $try->errors()->all();
=> [
     "The empty field is required.",
   ]
```

**Comment by driesvints** [comment]
I'm sorry but that looks good to me. Like I said if any is unclear feel free to send in a pr to the docs.

**Comment by SCIF** [comment]
So there is no way to be sure whether a field has value of `null` or `numeric`?

**Comment by SCIF** [comment]
> I'm sorry but that looks good to me. Like I said if any is unclear feel free to send in a pr to the docs.

Sorry, but I don't really understand how to explain that check for `null` and check for `is_numeric` doesn't allow me to check whether value is `null|numeric` (in psalm notation). Both checks are simple and clear but doesn't work. Should I add to both rules «Be aware, it works occasionally»? :)

**Comment by SCIF** [comment]
Or may be `nullable` check should be considered «conflicting for combining»? I.e. `nullable` cannot be used in any conjunction with other type constraints and in fact means `''` or `null`? That would explain the behavior a little bit as I'm still not certain how does it work (disregard unclear of docs, just to achieve my goals I have to guess/brut force combinations of constraints).
