### ISSUE TITLE
PHP  artisan make:component issue with '.' in component name

### ISSUE THREAD

**Issue by ploaiza** [laravel/framework#37528]
- Laravel Version: 8.44.0
- PHP Version: 8.0.6
- Database Driver & Version: n/a

### Description:
PHP  artisan make:component behaves non-logically when you put a period in the component name

### Steps To Reproduce:
PHP artisan make:component Test.TestComponent

Creates  file: app\View\Components\Test.TestComponent.php
Creates folder and file:  resources\views\components\test\\-test-component.blade.php

Folder is created in resources but not in app\View
File name is resources has - prepended

**Comment by driesvints** [comment]
A dot isn't supported. Use:

```
php artisan make:component Test/TestComponent
```
