### ISSUE TITLE
Call to an undefined static method Illuminate\Support\Facades\Queue::after()

### ISSUE THREAD

**Issue by jbruni** [laravel/framework#37538]
- Laravel Version: 8.42.1
- PHP Version: 8.0.5
- Database Driver & Version: none

### Description:

Code is available in documentation:
- https://laravel.com/docs/8.x/queues#job-events

When running [phpstan](https://phpstan.org/) level 3, it complains:

`Call to an undefined static method Illuminate\Support\Facades\Queue::after()`

It is possible to workaround it using `app('queue')->after()` instead of `Queue::after()`, but it would be nice to have the documentation example passing the static code analysis.

All the other usages of Facades in the application pass the static code analysis (eg, `Storage::disk()`) - making me believe this is a "fixable" issue.

### Steps To Reproduce:

Code is available in documentation:
- https://laravel.com/docs/8.x/queues#job-events

To install PHPStan: `composer require --dev phpstan/phpstan`

This is the script in  `composer.json`:

```json
    "scripts": {
        "phpstan": "phpstan analyse --level 3 app",
    }
```

To run it: `composer run phpstan`

**Comment by driesvints** [comment]
Hey @jbruni. We don't optimize for tools like phpstan. If you think there's a bug we're welcoming PRs. Thanks.
