### ISSUE TITLE
Cannot dispatch job after batch is completed successfully

### ISSUE THREAD

**Issue by dianfishekqi** [laravel/framework#37531]
- Laravel Version 8.44.0
- PHP Version: 8.0.6
- Database Driver & Version: pgsql 12.5
- Horizon: 5.7.8

### Description:
Queueing a job in the then method of a batch not possible

Horizon output:
https://raw.githubusercontent.com/dianfishekqi/pastebin/main/paste1.txt

### Steps To Reproduce:
``` 
class ... implements ShouldQueue, ShouldBeUnique{

....

function handle(){
...
  $batch = Bus::batch(
      array_map(
          fn ($i) => new GenerateGroups($i),
          $jobs
      )
  )->then(function () {
      Feeder::dispatch($this->max_id);
  });
...
}
...
}
```

**Comment by dianfishekqi** [comment]
I've found the culprit!

It seems SerializeCallback fails to report the error, but you can't use `$this` inside the callback,
it's not related to the ability to queue a new job in the then funtion!

Extracting `$max_id `to a local var and passing it throught `use ($max_id)` fixed the problem.

Maybe this should be noted in the documentation?

**Comment by themsaid** [comment]
Yes, avoid using `$this` in closures that will be serialized.

**Comment by yoeriboven** [comment]
You should also avoid `auth()->id()`. 

Couldn't figure out what was happening since I wasn't using `this` but apparently `auth()->id()` uses something similar.
