### ISSUE TITLE
Mocking custom validation rule does not work properly

### ISSUE THREAD

**Issue by dorinniscu** [laravel/framework#37535]
- Laravel Version: 8.27
- PHP Version: 8.0
- Database Driver & Version: MySQL 5.7.33
- Jetstream 2.1
- Livewire 2.0

I created a custom validation rule

```
class Recaptcha implements Rule
{
    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value): bool
    {
        $response = Http::post('https://www.google.com/recaptcha/api/siteverify', [
            'secret' => config('services.recaptcha.secret'),
            'response' => $value
        ])->json();

        return $response['success'];
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message(): string
    {
        return 'Recaptcha verification failed.';
    }
}
```

I am using it in the validation rules

```
[
    'full_name' => ['required'],
    'email' => ['required', 'email'],
    'message' => ['required', 'string'],
    'recaptcha' => ['required', new Recaptcha()],
]
```

I am trying to mock it inside a test but it fails.

```
$this->mock(Recaptcha::class, function (MockInterface $mock) {
    $mock->shouldReceive('passes')->andReturn(true);
});
```

**Component has errors: "recaptcha"
Failed asserting that false is true.**

**Comment by mfn** [comment]
Because
> new Recaptcha()

and
> $this->mock(Recaptcha::class

When you directly instantiate a class, you're not requesting it from the container where `->mock` registered it, hence it's not possible to receive the mock.

Probably nothing prevents it so resolve it via `app(Recaptcha::class)` and you should be good.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
