### ISSUE TITLE
Route model binding returns 500 where should return 404

### ISSUE THREAD

**Issue by fcolecumberri** [laravel/framework#37549]
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version: PostgreSQL

### Description and steps To Reproduce:

If created a route like:
```php
Route::get("user/{user:id}", ...);
```

lets assume `id` is UUID on the DB

If the user types `user/14be773e-c781-49f4-871b-787242b0cced` and there is no user with id `14be773e-c781-49f4-871b-787242b0cced`, then the system will return an 404 error (As it should since a user with id `14be773e-c781-49f4-871b-787242b0cced` was not found).
However if the user types `user/14be773e-c781-49f4-871b-787242b0cce` since `14be773e-c781-49f4-871b-787242b0cce` is not an UUID (notice the missing last character), the route binding will throw a `QueryException` with the text `ERROR: invalid input syntax for type uuid` when the SQL querry fails to compare the string with the UUID and will make the system returns a `500` error (which should not be correct because **a typo on the URL shouldn't generate a system error**).

I think that the correct way to proceed should to catch the `QueryException` here

https://github.com/laravel/framework/blob/6383cc852f81bc9634919c0b38ab696eea48c351/src/Illuminate/Database/Eloquent/Model.php#L1795

and from there just return `NULL` (which is the value that the function `first()` returns when the collection is empty).

Something like:

```php
public function resolveRouteBinding($value, $field = null)
{
    try{
        return $this->where($field ?? $this->getRouteKeyName(), $value)->first();
    }catch (QueryException $e){
        // URL type failed to cast into the DB type
        return null;
    }
}
```

**Comment by driesvints** [comment]
I see your point. Feel free to attempt a PR 👍

**Comment by fcolecumberri** [comment]
taylorotwell  suggested to used

```php
Route::get('/users/{id}', ...)->whereUuid('id');
```
As a patch this works, but the downside for now is that doesn't work with model binding.

**Comment by fcolecumberri** [comment]
Ok, I just realized it also works with model binding, I need to do
```php
Route::get('/users/{user:id}', ...)->whereUuid('user');
```
