### ISSUE TITLE
HTTP client keep many CLOSE_WAIT connections on queue wokers

### ISSUE THREAD

**Issue by juanparati** [laravel/framework#37545]
- Laravel Version: 8.1
- PHP Version: 8.05 (With JIT activated)
- Database Driver & Version: n/a
- OS: Debian Linux 10 (Kernel 4.0.5)

### Description:
Note: This may be not be a Laravel issue but a Guzzle problem. 

I notice that when I use the Laravel's Http client (Guzzle wrapper) in a queue worker, many connections remain on CLOSE_WAIT state despite that class that perform the request is destroyed when the tasks is finished.

I try to instantiate the Http client using Factory class instead to call directly thought the facade because I observed that facade use singleton pattern.

I suspect this issue may be related to some curl stack (Handlerstack) that avoids to PHP garbage collector to close the connections.

### Steps To Reproduce:

1. Queue worker run the job that perform the requests
1. Class that perform the request is instantiate
2. Http client is instantiate thought the factory (new \Illuminate\Http\Client\Factory) or using the facade.
3. Class that perform the request is destroyed

### Expected results

- All finished connections are closed.

### Received results

- Some connections remains on CLOSE_WAIT state and they are never closed (`lsof | grep CLOSE_WAIT | grep php`)

### Notes

I am very aware that to run queue jobs or run Laravel using Octane is different paradigm that running it only thought PHP-FPM, and I am always taking care of free the resources and close file handlers when a job is finished.

I also tried to pass the option "CURLOPT_FORBID_REUSE => true" but the problem still persist.

I was also thinking that may be a good idea in the future Laravel releases to provide a method in order to force down to close the connection after the request.

**Comment by driesvints** [comment]
Hi @juanparati. I'm afraid this issue is a bit beyond what the Laravel framework issue tracker is intended for. We cannot provide support here to solve this issue. Please either try reporting this to the Guzzle issue tracker or a support channel. If you have a specific way you want to solve anything we're welcoming PR's. Thanks and sorry.
