### ISSUE TITLE
Using array_key_exists() on objects is deprecated in Collections\\Arr.php

### ISSUE THREAD

**Issue by robertgm** [laravel/framework#37541]
I have Laravel 8.4 on Windows on Xampp. I changed in Xampp to use PHP 7.4.
Now I have error:
"message": "array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead",
    "exception": "ErrorException",
    "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php",
    "line": 155,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php",
            "line": 155,
            "function": "array_key_exists"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php",
            "line": 253,
            "function": "exists",
            "class": "Illuminate\\Support\\Arr",
            "type": "::"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php",
            "line": 491,
            "function": "forget",
            "class": "Illuminate\\Support\\Arr",
            "type": "::"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\UploadedFile.php",
            "line": 84,
            "function": "pull",
            "class": "Illuminate\\Support\\Arr",
            "type": "::"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\UploadedFile.php",
            "line": 36,
            "function": "storeAs",
            "class": "Illuminate\\Http\\UploadedFile",
            "type": "->"
        },
        {
            "file": "C:\\xampp\\htdocs\\myproj\\app\\Http\\Controllers\\EmailTemplateController.php",
            "line": 370,
            "function": "store",
            "class": "Illuminate\\Http\\UploadedFile",
            "type": "->"
        },

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
