### ISSUE TITLE
Operation failed fopen(php://stderr) processing big data on command

### ISSUE THREAD

**Issue by Darkhyrax** [laravel/framework#37555]
Hey guys.

I have created a command which checks a folder to verify if there are txt files to process and if it finds one, it opens it and begins to read each line to perform a series of activities such as connecting to webservices and saving the response of each of these in database.

The command works perfectly with small data (Less than 1100 records or lines).

After that amount it always throws me this error:

![image](https://user-images.githubusercontent.com/33364564/120275469-58b7ae80-c27f-11eb-9e84-16524238aad0.png)

So I must modify the task so that it skips the lines that I already process and continue with the ones that have not yet been read and so on until the task manages to finish reading the file each time it is executed.

I set the php.ini file by setting the memory_limit attribute to -1 and max_execution_time to 0 to check if it was a runtime or resource issue, but the failure time varies.

What should I configure so that this does not happen?

I just wrote this on file Kernel.php:

`$schedule->command('imp:kenan')->hourly()`

Hope you guys can help me.

Greetings and thanks in advance.

**Comment by crynobone** [comment]
You can consider doing the following:

1. Instead of running heavy task on schedule, push it to queue.
2. Load data using LazyCollection to reduce memory usage.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
