### ISSUE TITLE
src/Illuminate/Auth/SessionGuard.php `logoutOtherDevices` is not compatible with non Eloquent model objects

### ISSUE THREAD

**Issue by cgaube** [laravel/framework#37552]
- Laravel Version: 8.44.0
- PHP Version: 7.4.19
- Database Driver & Version: N/A

### Description:

Session Guard `user()` function return an `Illuminate\Contracts\Auth\Authenticatable` 

The `logoutOtherDevices()` function expects the `user()` object to be an Eloquent model. 

This means that `logoutOtherDevices()` can only work if your application uses an eloquent model for your `Illuminate\Contracts\Auth\Authenticatable`.
As far as i know  this should not be a constraint.

The way i think it should work is that `logoutOtherDevices` can only use functions that are defined in the interface. 

```
protected function rehashUserPassword($password, $attribute)
{
    if (! Hash::check($password, $this->user()->$attribute)) { // should be probably be $this->user()->getAuthPassword()

```

for `forceFill`:
```
 return tap($this->user()->forceFill([
            $attribute => Hash::make($password),
        ]))->save();
```

we should probably create a new function in the `lluminate\Contracts\Auth\Authenticatable`  interface

something along the line

`return $this->user()->setAuthPassword() `

### Steps To Reproduce:

- Use a non eloquent model for the application `Illuminate\Contracts\Auth\Authenticatable` 
- try to use Auth::logoutOtherDevices()

**Comment by driesvints** [comment]
This sounds more like a feature request. Welcoming PR's 👍

**Comment by cgaube** [comment]
Well it leads to fatal error if you dont have an eloquent model as `illuminate\Contracts\Auth\Authenticatable` so personally i think it is a bug, except if somewhere in the laravel documentation it says that all `Authenticatable` should be eloquent models
