### ISSUE TITLE
Eloquent Issue when using ->select() after ->withExists()

### ISSUE THREAD

**Issue by lk77** [laravel/framework#37557]
- Laravel Version: 8.43.0
- PHP Version: 7.3.28
- Database Driver & Version: mariadb 10.0

### Description:

Hello, 

when i'm calling ->withExists and then ->select, the *_exists field is missing from the data,
the only solution to make it work is to move the select before the withExists.

### Steps To Reproduce:

add a dummy relation to User referencing itself:

```
public function dummy()
{
    return $this->belongsTo(User::class, 'id');
}
```
then in a controller :

```
dump(User::withExists('dummy')->select('*')->first()->dummy_exists); // return null
dump(User::withExists('dummy')->first()>dummy_exists); // return true
```
there is no scenario where dummy_exists could be null or false, since it's referencing itself, it should always exist no matter what.

moving the select before the withExists fix the issue
```
dump(User::withExists('dummy')->select('*')->first()->dummy_exists); // return null
dump(User::select('*')->withExists('dummy')->first()->dummy_exists); // return true
```

i've not created a github repo for this since i think this behaviour is easily testable with any given project with a user model.

thanks.

**Comment by driesvints** [comment]
I see in all of the tests of `withExists` that `select` comes before `withExists` so that's indeed probably required. If this isn't clear in the docs we'd appreciate PR's 👍
