### ISSUE TITLE
Http::attach error: A 'contents' key is required

### ISSUE THREAD

**Issue by leogitpro** [laravel/framework#37562]
- Laravel Version: 8.44.0
- PHP Version: 8.0.6
- Database Driver & Version: 5.7

### Description:

Http client send file with error: A 'contents' key is required.
Ref: [Http Client multipart request](https://github.com/laravel/framework/issues/32058)

### Steps To Reproduce:

```
$result = Http::attach(
                'doc', $xml->get(), $xml->getClientOriginalName()
            )->post($api, [
                'token' => 'abc',
//                'xpath' => ['/entry/title', '/entry/'author'],  // Will be occured error: A 'contents' key is required.
                'xpath' => '/entry/title',  // Will be OK.
            ])->throw()->json();
```

Is the post file can not with array params? Thanks very much!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
