### ISSUE TITLE
Command mysql not found

### ISSUE THREAD

**Issue by nckg** [laravel/framework#37579]
- Laravel Version: 8.44.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 5.7.34

### Description:

I've implemented https://github.com/laracasts/cypress into our application. It injects endpoints into the framework to enable migrations from a Javascript API. It basically does this:

```php
Route::post('/__cypress__/artisan', function (Request $request)
{
    Artisan::call($request->input('command'), $request->input('parameters', []));
}
```

I've also used `php artisan schema:dump --prune` to clear our migrations. The endpoint returns the following error when I call it.

I suspect it has to do with this line of code. It works when I replace the `mysql`-command with the full path command.

```
[2021-06-03 14:48:07] local.ERROR: The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.

Exit Code: 127(Command not found)

Working directory: /Users/nick/Code/pixeo-flowlab/public

Output:
================


Error Output:
================
sh: mysql: command not found
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"mysql  --user=\"${:LARAVEL_LOAD_USER}\" --password=\"${:LARAVEL_LOAD_PASSWORD}\" --host=\"${:LARAVEL_LOAD_HOST}\" --port=\"${:LARAVEL_LOAD_PORT}\" --database=\"${:LARAVEL_LOAD_DATABASE}\" < \"${:LARAVEL_LOAD_PATH}\"\" failed.

Exit Code: 127(Command not found)

Working directory: /Users/nick/Code/pixeo-flowlab/public

Output:
================


Error Output:
================
sh: mysql: command not found
 at /Users/nick/Code/pixeo-flowlab/vendor/symfony/process/Process.php:267)
[stacktrace]
#0 /Users/nick/Code/pixeo-flowlab/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php(77): Symfony\\Component\\Process\\Process->mustRun(NULL, Array)
#1 /Users/nick/Code/pixeo-flowlab/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(145): Illuminate\\Database\\Schema\\MySqlSchemaState->load('/Users/nick/Cod...')
#2 /Users/nick/Code/pixeo-flowlab/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(113): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->loadSchemaState()
#3 /Users/nick/Code/pixeo-flowlab/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(77): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by pablorsk** [comment]
Your machine dont have mysql-cli installed. Install, for example, with

```bash
apt install default-mysql-client
```

**Comment by nckg** [comment]
There was a problem with my mysql installation. The problem was resolved after upgrading to mysql 8 🤷
