### ISSUE TITLE
Pagination ( onEachSide(5) ) function is not working.

### ISSUE THREAD

**Issue by TahmidFarzan** [laravel/framework#37571]
- Laravel Version: 8.35.1
- PHP Version: 7.4.7
- Database Driver & Version: 10.4.13-MariaDB

### Description:
pagination ( onEachSide(5) ) function is not working.
I want control how many additional links are displayed on each side of the current page during pagination using onEachSide(5).
But it does not work.

### Steps To Reproduce:
 1) Create a database and migrate a table.
2) Add several dummy records on that table.
3) Use pagination to get the date and view it on view page and use onEachSide(5) to control how many additional links are displayed.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by halivert** [comment]
I've found the same issue, the function `onEachSide` is not working

**Comment by LukeTowers** [comment]
See https://wintertricks.com/tricks/paginator-with-limited-number-of-pages-displayed-at-once for an example of how you can implement a completely custom onEachSide link window yourself in your views.
