### ISSUE TITLE
L8.45 - Undefined index: column

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#37581]
- Laravel Version: 8.45.0
- Database Driver & Version: MariaDB 10.3 and 10.5

### Description:

After update Laravel from 8.44 to 8.45 I am receiving this error: "undefined index: column". It happens here:

https://github.com/laravel/framework/commit/7ad6ba202920e28c8fc8c78df55a92743d223478#diff-2ed94a0ea151404a12f3c0d52ae9fb5742348578ec4a8ff79d079fa598ff145dR1988

**Comment by Aurion72** [comment]
I confirm I just encountered the same problem and I checked the Laravel issues since I didn't change anything in particular. For now i'm locking my project at v8.44 which works fine.

**Comment by toyi** [comment]
Same problem here, locking at 8.44 until this is fixed, I'm sure it'll be quick.

**Comment by taylorotwell** [comment]
Will revert that change now.

**Comment by Javdu10** [comment]
hi @rentalhost, @toyi , 
Firstly sorry for that i'm not aware of all the inner workings of the framework, 
Would you share with me when this kind of scenario happen, what part in your code broke?
When `unionOrders` or `orders` is initialised , is an array, has elements but don't have a column attribute?
Thanks! You can PM me on Discord if you want to share more info: Jav#7775

**Comment by rentalhost** [comment]
@Javdu10 I could not reproduces it now, but by checking my source code, maybe it is related to `orderByRaw()` usage.

**Comment by toyi** [comment]
@Javdu10 I was about to dig in to reproduce this bug but it seems you found a fix :)

**Comment by Javdu10** [comment]
Ohh that makes sense! I've added an isset(), so it should work properly now, I wasn't aware of this edge case, thank you!
