### ISSUE TITLE
Odd issue when running "pluck()" against a single model

### ISSUE THREAD

**Issue by junioro12** [laravel/framework#37585]
- Laravel Version: 8.42.1
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.0.22

### Description:
Odd behaviour when mistakenly using `pluck()` on a single model...found this out examining an older project but this behaviour persists.

If one fetches a single record, and tries to pluck a property from it, for some reason the framework pulls that property from the entire database table.

The use of pluck here was mistaken by a developer, however it resulted in the framework choosing the first overall value in the database that matched the query, not the one tied to the model being examined.

### Steps To Reproduce:

`$user->keys()->active()->first()` <-- this properly returns the one key (in a hasOne relationship) for this user...

While this next statement is technically wrong...it actually plucks all of the codes from the entire database table:

`$user->keys()->active()->first()->pluck('code')`

I would have expected the pluck method to either complain about not being run on a collection, or perhaps returning an empty collection, or even returning the `code` property from the chosen model.  In this case, instead somehow the entire database table of `code` fields was returned.

Technically we shouldn't have been using pluck there...however this resulted in the code mistakenly getting back codes from ALL users, not the one we were dealing with.

**Comment by lk77** [comment]
Hello,

i think it's the expected behaviour here,

````
$user->keys()->active()->first()->pluck('code');
````

equals

```
User::pluck('code');
```

it's misleading but i don't think there is an easy way to solve that.

**Comment by staudenmeir** [comment]
We also discussed this in #28549.
