### ISSUE TITLE
Ordinal prefixes can't be used for naming migration files.

### ISSUE THREAD

**Issue by nefcanto** [laravel/framework#37600]
- Laravel Version: 8.45.1
- PHP Version: 7.4.18
- Database Driver & Version: 10.5.10-MariaDB-1:10.5.10+maria~focal

### Description:

Ordinal prefixes can't be used for naming migration files.

### Steps To Reproduce:

Create a simple Laravel app. Add two migrations:

```
php artisan make:migration first_table

php artisan make:migration second_table

```
Now run the migration using `:fresh` switch:

`php artisan migrate:fresh`

It runs.

Now remove the timestamp prefix of file names, and replace them with ordinals as follow:
```
001_first_table.php
002_second_table.php
```

Now run migration again:

`php artisan migrate:fresh`

This time it complains that:

> Cannot declare class FirstTable, because the name is already in use

**Comment by driesvints** [comment]
That's indeed not supported. The timestamps are required.

**Comment by TimothyDLewis** [comment]
Following-up, as this was a recent question on Stackoverflow. There's this post that suggests this is possible:

https://laracasts.com/discuss/channels/laravel/can-you-rename-migration-files-to-your-own-custom-format

Was this something that _was_ supported in the past (given the age of the post)? Or is this article just completely wrong?

**Comment by rs-sliske** [comment]
im not sure if its ever been supported but i feel like numbering them rather than timestamps will lead to issues as soon as any collaboration is involved so i would recommend against it
