### ISSUE TITLE
[8.x] Relation HasOne OfMany w/ Soft Deletes failing on MySQL

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/framework#37608]
### Environment:

- Laravel Version: 8.45.1
- PHP Version: 8.0.7
- Database Driver & Version: MySQL (8.0.25)

### Description:

It appears that the "hasOneOfMany" concept paired with soft deletion fails to run on MySQL environments.

Here's an example:
```php
class Country extends Model
{
    public function largestState()
    {
        return $this->hasOne(State::class)->latestOfMany('population');
    }
}

class State extends Model
{
    use SoftDeletes;
}
```

In this particular setup, a call to `$country->largestState` produces the following exception:

> Illuminate\Database\QueryException: SQLSTATE[HY093]: Invalid parameter number (SQL: select * from `states` inner join (select MAX(id) as id, `states`.`country_id` from `states` inner join (select MAX(population) as population, `states`.`country_id` from `states` where `states`.`country_id` = 1 and `states`.`country_id` is not null and `states`.`deleted_at` is null group by `states`.`country_id`) as `largestState` on `largestState`.`population` = `states`.`population` and `largestState`.`country_id` = `states`.`country_id` where `states`.`deleted_at` is null group by `states`.`country_id`) as `largestState` on `largestState`.`id` = `states`.`id` and `largestState`.`country_id` = `states`.`country_id` where `states`.`country_id` = ? and `states`.`country_id` is not null and `states`.`deleted_at` is null limit 1)

When manually running this SQL (with bindings injected) on the raw MySQL connection, the SQL runs without error, and returns the expected result. Therefore, this issue appears to be related to Eloquent and/or PDO.

### Steps To Reproduce:

**1)** Clone my [example project](https://github.com/tylernathanreed/has-one-of-many) for this issue
**2)** Use sail (project is configured for this), or host on MySQL connection
**3)** Run `vendor/bin/phpunit`, which will result in an exception (actual), rather than success (expected)

### Resolution:

It appears that when Laravel attempts to run the query, there's a missing binding (note the remaining "`?`" in the SQL above). If I include the missing binding, the query resolves as expected:

```php
// yields an instance of App\Models\State
$country->largestState()->addBinding($country->id)->getResults();
```

For now, I can get my code to behave as expected if I change the relationship in the following way:

```php
/**
 * Returns the largest state that belongs to this country.
 *
 * @return \Illuminate\Database\Eloquent\Relations\HasOne
 */
public function largestState()
{
    return $this->hasOne(State::class)->latestOfMany('population')->addBinding($this->getKey());
}
```

Granted, this additional step should not be required, and instead work as-is.

### Related Issue:

Running this test in SQLite also fails (without throwing an exception), as the relationship returns null, when it should clearly be not null. The SQL that the query is trying to run also functions as expected on the database connection directly, but fails to work as designed within Laravel.

I'm guessing that SQLite handles the lingering "`?`" differently, and chooses to perform some sort of string-based comparison, rather than outright fail.

**Comment by tylernathanreed** [comment]
I've updated the title of this issue to include "Soft Deletes", as I've discovered that to be a requirement of the issue.

I've created a sample project ([found here](https://github.com/tylernathanreed/has-one-of-many)), which reproduces this issue. I plan to update the reproduction steps above to include said project.

**Comment by driesvints** [comment]
Ping @cbl

**Comment by Sergiobop** [comment]
This one may be related to my comments in the original PR... 
I was using softDeletes too
https://github.com/laravel/framework/pull/37362#issuecomment-854485099

**Comment by cbl** [comment]
@tylernathanreed thanks for the example project, that really helped!

**Comment by driesvints** [comment]
@cbl thanks for the PR
