### ISSUE TITLE
BroadcastEvents calls non-static method trashed statically 

### ISSUE THREAD

**Issue by ejunker** [laravel/framework#37601]
- Laravel Version: 8.45.1
- PHP Version: 8.0.6
- Database Driver & Version: MySQL 5.7

### Description:

I have a base Model class where I added: `use BroadcastsEvents;`

I get this error:
```php
Non-static method App\Models\Campaign::trashed() cannot be called statically
```

Which makes sense because in `Illuminate\Database\Eloquent\SoftDeletes` it defines the `trashed()` method as:
`public function trashed()` but in `BroadcastEvents` it calls it like this:
```php
static::trashed(function ($model) {
    $model->broadcastTrashed();
});
```

### Steps To Reproduce:

- add `use BroadcastsEvents;` to a model that also has `use SoftDeletes;`
- try to persist an instance of the model

**Update:** while there is a "restored" model event, there doesn't appear to be a "trashed" model event.

**Comment by driesvints** [comment]
From: https://github.com/laravel/framework/pull/37491

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/framework/pull/37618
