### ISSUE TITLE
Attributes indicated by array `$append` with accessor method are not appended to JSON when included in `$cast` at the same time

### ISSUE THREAD

**Issue by nagmat84** [laravel/framework#37607]
Laravel Version: 8.40.0
PHP Version: 7.4.16

### Description

Let's assume I have a model which has some "virtual" attributes that needs to be appended to the serialized array, which are are get-only and which are defined through an accessor method.
At the same time an inbound cast prevents the attribute from being set accidentally.
The following code does not work as expected.

```php
class MustNotSetCast implements CastsInboundAttributes {
  public function set($model, string $key, $value, array $attributes): void {
    throw new \BadMethodCallException('must not set read-only attribute \'' . $key . '\'');
  }
}

/**
 * @property string $actual_property
 * @property string $virtual_property
 */
class MyModel extends Model {
  protected $casts = [ 'virtual_property' => MustNotSetCast::class ];
  protected $appends = [ 'virtual_property' ];

  protected function getVirtualPropertyAttribute(): string {
    return strtolower($this->actual_property);
  }
}
```

**Expected Behaviour**

```php
$model = new MyModel();
$model->actual_property = "Hello";
$model->toArray(); // should return [ 'actual_property' => 'Hello', 'virtual_property' => 'hello' ]
$model->virtual_property = "Bye"; // should throw an exception
```
   
**Actual Behaviour**

```php
$model = new MyModel();
$model->actual_property = "Hello";
$model->toArray(); // returns [ 'actual_property' => 'Hello', 'virtual_property' => n ]
```

### The underlying cause
    
IMHO, the bug is in `Illuminate\Database\Eloquent\Concerns\HasAttributes::mutateAttributeForArray`. Essentially, the method does the following

```php
$value = $this->isClassCastable($key)
  ? $this->getClassCastableAttributeValue($key, $value)
  : $this->mutateAttribute($key, $value);
```

I.e., it first checks if there is an cast for the attribute and then uses a mutator (actually an accessor) to get the attribute.
In other words, casts have a higher priority than explicitly defined accessors.

This is contrary to `Illuminate\Database\Eloquent\Concerns\HasAttributes::transformModelValue` which is internally called by `getAttributeValue`.
The method `transformModelValue` works as follows

```php
if ($this->hasGetMutator($key)) {
  return $this->mutateAttribute($key, $value);
}
if ($this->hasCast($key)) {
  return $this->castAttribute($key, $value);
}
```

This is quite the opposite and gives higher priority to explicitly defined accessors (called "get mutator" here).
This is also in line with the official documentation which says that accessors/mutators take precedence over casts, but an accessor/mutator may be call a cast internally without ending up in an infinite loop.

Unfortunately, the different approach between `mutateAttributeForArray` and `transformModelValue` makes it impossible to combine casts and mutators such that they work correctly for both cases.
Either the rule should be "accessors/mutators take precedence over casts" or "casts take precedence over accessors/mutators".
As the former rule seems to be the dominant one, IMHO `mutateAttributeForArray` must be fixed to follow the same rule.

**Comment by nagmat84** [comment]
### Proposed patch

```php
protected function mutateAttributeForArray($key, $value)
{
  if ($this->hasGetMutator($key)) {
    $value = $this->mutateAttribute($key, $value);
  }
  if ($this->isClassCastable($key)) {
    $value = $this->getClassCastableAttributeValue($key, $value);
  }

  return $value instanceof Arrayable ? $value->toArray() : $value;
}

**Comment by driesvints** [comment]
I don't think mutators and casts are meant to be used in combination with each other.
