### ISSUE TITLE
redirect back withInput or with after store data in session

### ISSUE THREAD

**Issue by moisesf10** [laravel/framework#37614]
- Laravel Version: 8.36.2
- PHP Version: 7.3.27
- Database Driver & Version:

### Description:
I have a page that has a <form method="post">. In addition to it, the page makes several ajax calls that are intended to store data in the session.
When I submit the form without using ajax calls to store data, everything works fine and in the controller, I am able to return the input data via redirect()->back()->withInput($request-> all()), just for additional information, redirect()->back()->with('key', 'value') also works... however, if you try this same process after making an ajax call to write data in the session, withInput($request->all()) returns empty to the view, that is, the "_old_input" field of the session doesn't even exist in this situation. In this case, redirect()->back()->with('key', 'value') doesn't work either

### Steps To Reproduce:
1. Have a form with POST method on the page
2. On this same page, be able to make an ajax call that will save some data in the session via session()->put('key', 'value')
3. After successfully making the ajax call, submit the form that will contain some filled field, as the idea is to return this value through ->withInput($request->all())
4. In the controller do redirect()->back()->withInput($request->all())
5. Back on the page containing the form try to retrieve the value via old('name') or via {{dd(session()->all())}}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
