### ISSUE TITLE
When a model joins a table by default (global scope) id is ambiguous when route binding

### ISSUE THREAD

**Issue by MordiSacks** [laravel/framework#37615]
- Laravel Version: 8.42.0
- PHP Version: 8.0.7
- Database Driver & Version: Database client version: libmysql - mysqlnd 8.0.7, 10.5.10-MariaDB-1:10.5.10+maria~buster

### Description:
When a model joins a table by default (global scope) id is ambiguous when route binding

### Steps To Reproduce:
1. Create a generic database table "authors" that has at least 2 columns (id, 'name').
2. Create a generic model "Book" (with an column author_id).
3. Add a global scope to Book model that joins authors, see sample code below.
4. Create a route that loads the book (`Route::get('books/{book}', fn(Book $b) => dd($b));`).
5. Create appropriate records (1 book, 1 author).
5. Access route.

#### Scope code
```php
public static function booted()
{
    static::addGlobalScope('withAuthor', function (Builder $query) {
        $query->join('authors', function (JoinClause $j) {
            $j->on('authors.id', '=', 'books.author_id');
        });
        
        $query->addSelect([
            'authors.name AS author_name',
        ]);
    });
}
```

Error should be
`Illuminate\Database\QueryException`
`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous`

Query  
```SQL
select `authors`.`name` as `author_name`
from `authors`
         inner join `authors` on `authors`.`id` = `books`.`author_id`
where `id` = 331
limit 1
```

## Proposed solution
add the table name to 
`Illuminate/Database/Eloquent/Model.php:1752`
```php
    public function resolveRouteBinding($value, $field = null)
    {
        return $this->where($field ?? ($this->getTable() . '.' . $this->getRouteKeyName()), $value)->first();
    }
```

**Comment by driesvints** [comment]
That's not supported I'm afraid. In general, global scopes are meant to provide extra filtering on the main model table and not be used in combination with joins. That's why the docs also don't have examples for joins: https://laravel.com/docs/8.x/eloquent#global-scopes
