### ISSUE TITLE
7.x -> 8.x Undocumented Breaking Change

### ISSUE THREAD

**Issue by bogdankharchenko** [laravel/framework#37622]
Hi,

I recently was upgrading Laravel 7 -> Laravel 8 -- via guide [https://laravel.com/docs/8.x/upgrade](https://laravel.com/docs/8.x/upgrade)

Noticed in 8.x the `deleted_at` column was no longer being added to `$dates` property on the Model, but instead if added to the casts property -- which is not documented in the upgrade guide.

Behavior in 7x with SoftDeletes Trait applied

```php
return (new User())->getDates()
```
```
[
   "deleted_at",
   "created_at",
   "updated_at"
]
```

Running same exact code with SoftDeletes Trait applied in 8.x produces

```php
[
   "created_at",
   "updated_at"
]
```

Laravel 8.x - [SoftDeletes 8.x](https://github.com/laravel/framework/blame/8.x/src/Illuminate/Database/Eloquent/SoftDeletes.php#L37)
```php
if (! isset($this->casts[$this->getDeletedAtColumn()])) {
    $this->casts[$this->getDeletedAtColumn()] = 'datetime';
}
```

Laravel 7.x - [SoftDeletes 7.x](https://github.com/laravel/framework/blame/7.x/src/Illuminate/Database/Eloquent/SoftDeletes.php#L36)
```php
  $this->dates[] = $this->getDeletedAtColumn();
```

I'm not sure if this was already addressed somehow but took me a bit to figure out what changed here.

**Comment by driesvints** [comment]
Feel free to send in a pr to the docs 👍
