### ISSUE TITLE
Laravel Cursor Pagination SQL Server Datetime Conversion Failed

### ISSUE THREAD

**Issue by muhammadnan** [laravel/framework#37629]
- Laravel Version: 8.45.1
- PHP Version: 8.0.5
- DBMS: Microsoft SQL Server (ver. 15.00.4123) 
- Case sensitivity: plain=mixed, delimited=mixed
- Driver: Microsoft JDBC Driver 9.2 for SQL Server (ver. 9.2.0.0, JDBC4.2)

### Description:
![screenshot-localhost_8000-2021 06 08-20_08_03](https://user-images.githubusercontent.com/30528814/121190442-44823b80-c895-11eb-80e0-263b8423bdc6.png)

when i use sql server as dbms, then i create pagination with cursor but i find an anomaly when i press 'next' that is 'Conversion failed when converting date and/or time from character string. '

### Steps To Reproduce:
just use the `cursorPaginate()` to ur project for this with DBMS SQL Server

### Steps to Solve
i can solve this with `Eloquent Accessor` & `Carbon` in `created_at` attribute but i have in mind that this is less simple, is there any way to solve this by making it default in laravel? or just like this?

```
   /**
     * @param $date
     * @return mixed
     * @author Muhammad Adnan <naravaya04@gmail.com>
     */
    public function getCreatedAtAttribute()
    {
        return $this->attributes['created_at'] != null ? Carbon::parse($this->attributes['created_at'])
            ->translatedFormat('Y-m-d H:i:s') : null;
    }

    /**
     * @param $date
     * @return mixed
     * @author Muhammad Adnan <naravaya04@gmail.com>
     */
    public function getUpdatedAtAttribute()
    {
        return $this->attributes['updated_at'] != null ? Carbon::parse($this->attributes['updated_at'])
            ->translatedFormat('Y-m-d H:i:s') : null;
    }
```

**Comment by driesvints** [comment]
Ping @paras-malhotra

**Comment by IgorGaming** [comment]
+1. I just ran into the same problem. 

But this problem appears not only when using the SQL Server DBMS.
When used in MySQL, the exact same query is made(it does not cause an error, but returns 0 results.
It causes the error 'Only arrays and objects are supported when cursor paginating items.' (in Illuminate/Pagination/AbstractCursorPagination.php):

```
/**
     * Get the cursor parameters for a given object.
     *
     * @param  \ArrayAccess|\stdClass  $item
     * @return array
     *
     * @throws \Exception
     */
    public function getParametersForItem($item)
    {
        return collect($this->parameters)
            ->flip()
            ->map(function ($_, $parameterName) use ($item) {
                if ($item instanceof ArrayAccess || is_array($item)) {
                    return $item[$parameterName] ?? $item[Str::afterLast($parameterName, '.')];
                } elseif (is_object($item)) {
                    return $item->{$parameterName} ?? $item->{Str::afterLast($parameterName, '.')};
                }
                
                throw new Exception('Only arrays and objects are supported when cursor paginating items.');
            })->toArray();
    }
```

This can be solved by adding the following code to the `getParametersForItem()` method (redefining the Illuminate\Pagination\CursorPaginator class):

```
public function getParametersForItem($item)
    {
        $parameters = collect($this->parameters)
            ->flip()
            ->map(function ($_, $parameterName) use ($item) {
                if ($item instanceof ArrayAccess || is_array($item)) {
                    return $item[$parameterName] ?? $item[Str::afterLast($parameterName, '.')];
                } elseif (is_object($item)) {
                    return $item->{$parameterName} ?? $item->{Str::afterLast($parameterName, '.')};
                }
                
                throw new Exception('Only arrays and objects are supported when cursor paginating items.');
            })->toArray();
            
         foreach($parameters as $column => $parameter) {
             if ($parameter instanceof Carbon) {
                 $parameters[$column] = Carbon::parse($parameter)->format($item->getDateFormat());
             }
         }
         
         return $parameters;
    }

```

**Comment by driesvints** [comment]
Is this the same issue as https://github.com/laravel/framework/issues/37400 ?

**Comment by muhammadnan** [comment]
it's closer to #37400 than here and that can be an option to solve the problem that is in #37400

**Comment by IgorGaming** [comment]
So, I did some research.
First, **these are different issues**. #37400 reports things that are not related to this issue.
The error of this issue is that SQL cannot handle such strings(this can be solved by executing `->format()` or similar on `Carbon` object).
Secondly, the problem I had was something else. The thing is that when using `json_encode()`, Carbon timezone doesn't seem to be saved without `->format()` or similar (maybe I'm doing something wrong?). So i also need use `->format()`.

I think the "solution" to this problem can't be at the CursorPagination level. Because it is related to behavior of Carbon, not CursorPagination.

**Comment by IgorGaming** [comment]
This issue has been fixed in v8.48.2(#37785).
But if your dates has precision(like `2021-07-02 17:49:03.351`), than cursor pagination won\`t work properly, because __toString method of Carbon instance uses the default format `Y-m-d H:i:s`, not `Y-m-d H:i:s.u`. 
So, any developer, who uses cursor pagination and dates with precision **must** override `\Illuminate\Pagination\CursorPaginator` class or i missed something?

**Comment by driesvints** [comment]
@IgorGaming think that's something you need to do in your model as detailed in the post by the OP here.

**Comment by IgorGaming** [comment]
@driesvints, But I need to get an instance of `Carbon` when I use `$model->created_at`, not just a string. So the only option for me is to redefine the base class(in any case, I have to do this for ajax purposes).
