### ISSUE TITLE
Adding unique constraint to migration file causes rows to be out of order

### ISSUE THREAD

**Issue by asinia01** [laravel/framework#37628]
- Laravel Version: #.#.#
- Laravel Framework 8.42.1
- PHP Version: #.#.#
- PHP 8.0.3 (cli) (built: Mar  4 2021 20:42:56)
- Database Driver & Version:
- JDBC4 10.3.28-MariaDB

### Description:
Adding a composite unique key on two columns with datatype `string (50)` causes the rows to be out of order

### Steps To Reproduce:
In our migration file
![image](https://user-images.githubusercontent.com/12041031/121186204-d86feb00-c834-11eb-9e7a-29092176147d.png)

, without a unique constraint, the seeded data is ordered correctly
![image](https://user-images.githubusercontent.com/12041031/121185522-259f8d00-c834-11eb-9755-3d0d582c7d3b.png)
Adding the unique constraint
![image](https://user-images.githubusercontent.com/12041031/121186247-e45bad00-c834-11eb-8e02-8f413278c5d0.png)
gives us this
![image](https://user-images.githubusercontent.com/12041031/121185687-4ff14a80-c834-11eb-90ef-06c861a33bf4.png)
Switching the column order of the unique constraint
![image](https://user-images.githubusercontent.com/12041031/121186294-f0476f00-c834-11eb-9349-728a859716f3.png)
gives us this
![image](https://user-images.githubusercontent.com/12041031/121185912-8a5ae780-c834-11eb-8480-5b49c3ff952d.png)

relevant fiddle
https://www.anyfiddle.com/p/asiniarski/r4jj1ou2

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
