### ISSUE TITLE
TestCase on laravel new...

### ISSUE THREAD

**Issue by Eugene-Melbourne** [laravel/framework#37623]
- Laravel Version: 8.45.1
- PHP Version: 7.4
- Database Driver & Version: none

### Description:
Can anyone please fix the  project\tests\Unit\ExampleTest.php
When creating new project it creates this ExampleTest with 
    `use PHPUnit\Framework\TestCase;`
when it needs to be 
    ` use Tests\TestCase;`

**Comment by driesvints** [comment]
It doesn't. Unit tests don't need to boot the framework. If you need the framework write a feature test instead.
