### ISSUE TITLE
Cannot dispatch closure using use($var)

### ISSUE THREAD

**Issue by meyer59** [laravel/framework#37627]
- Laravel Version: 8.40.0
- PHP Version: 7.3.5
- Database Driver & Version: mysql 8.0.22

### Description:
Hello
I'm trying to dispatch a closure to a queue as mentionned [here ](https://laravel.com/docs/8.x/queues#queueing-closures) in the doc.
I am getting a weird issue
```
 +"message": "serialize(): __sleep should return an array only containing the names of instance-variables to serialize."
  +"exception": "ErrorException"
  +"file": "\vendor\opis\closure\src\SerializableClosure.php"
  +"line": 155
```
### Steps To Reproduce:
Try to dispatch a closure with a use($var) 
```
dispatch(function () use ($var) // <--- use() makes the error
 {
          
 });
``` 
Cordially

**Comment by driesvints** [comment]
Works fine for me:

```php
Route::get('/', function () {
    $var = 'Hello World';

    dispatch(function () use ($var) {
        logger($var);
    });

    return view('welcome');
});
```

![Screen Shot 2021-06-08 at 12 55 02](https://user-images.githubusercontent.com/594614/121173162-c3a54e80-c858-11eb-9a1d-bc06c65efb33.jpg)

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by meyer59** [comment]
The problem seems to happen when $var is an object. In my case it was a Carbon date.

**Comment by driesvints** [comment]
I'll take another try tomorrow or so. Thanks

**Comment by allowing** [comment]
I have encountered the same problem. I was `use (/*
\Illuminate\Http\Request */ $request)`. This should be related to serialization, it may be that the object cannot be serialized.

**Comment by driesvints** [comment]
Seems like an issue in opis/closure: https://github.com/opis/closure/issues/75
