### ISSUE TITLE
BelongsToMany::touch should respect parentKeyName, not the primary key

### ISSUE THREAD

**Issue by renzo-s** [laravel/framework#37635]
- Laravel Version:  8.29.0
- PHP Version: 7.4.19
- Database Driver & Version: PostgreSQL 11.12

### Description:

When creating a `belongsToMany` relation with custom pivot keys (other than the primary key), touching the parent will result in an SQL error (int vs string error for example).

This is since `Illuminate/Database/Eloquent/Relations/BelongsToMany.php@1074` get's the ID by doing `$this->getRelated()->getKeyName()`, and uses that column for the update statement.

A fix would be if BelongsToMany respects it's `parentKeyName` assignment. So replacing line `1074` with `$key = $this->getParentKeyName();` would be better.

### Steps To Reproduce:

1. Create a relation for example a customer with many phone numbers, and a phone number attached to multiple customers. On which the phone number, touches the customers updated_at timestamp. Define a custom parent and related keys:

```
        return $this->belongsToMany(
            Customer::class,
            'customer_phone_number',
            'phone_number_uuid',
            'customer_uuid',
            'uuid',
            'uuid',
        );
```

2. Save a phone number, and let it touch the parent:

```
$phoneNumber = \App\Models\PhoneNumber::find(1);
$phoneNumber->customers()->touch();
```

Example error:

```
Illuminate\Database\QueryException with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "6491a3b5-b9cd-4c54-9d91-ce8ea83849cb" (SQL: update "customers" set "updated_at" = 2021-06-09 09:18:44 where "id" in (6491a3b5-b9cd-4c54-9d91-ce8ea83849cb))'
```

**Comment by renzo-s** [comment]
Allright, that was fairly straight forward. I took the liberty to change the repo name in place of your suggestion ;)

The repo is here: https://github.com/renzo-s/framework-issue-37635

To reproduce (also in readme)

```
1. ./artisan migrate
2. ./artisan db:seed
3. ./artisan trigger-error
```

To drive the point home, I want to emphasis that it's not the use of the UUID's here, but when defining all the arguments in a `belongsToMany` relation, it should respect these too in touching the parent timestamps.

Hope this helps.

**Comment by driesvints** [comment]
Hey @renzo-s. I see quite a bit of things amis in your code. First of all you should indicate on the model when a primary key is other than `id`. Secondly, the key type should also be set to string if it's a UUID. I suggest you read up here: https://laravel.com/docs/8.x/eloquent#primary-keys

If there's anything else you want to ask I want to forward you to the following support channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Good luck!

**Comment by renzo-s** [comment]
okay, but the uuid's aren't the primary key. I choose it as an example, I could have just named them 'lastname' or anything else. Point was that the [parent]->touch() method is not working.
