### ISSUE TITLE
HTTP test fails when testing images

### ISSUE THREAD

**Issue by dorinniscu** [laravel/framework#37638]
- Laravel Version: 8.45.1
- PHP Version: 8.0.7
- Database Driver & Version: MySQL 8.0.25

I am trying to create a test to check the response status for an image.

The image works fine in browser:
https://mydomain.test/storage/images/j2L3G12eel9sqsuNSGOYmcdqwUdchZtsfFGMeY90.jpg

Also Http get works fine:
Http::get('https://mydomain.test/storage/images/j2L3G12eel9sqsuNSGOYmcdqwUdchZtsfFGMeY90.jpg')->status();

```
/**
 * @runInSeparateProcess
 */
 public function test_can_see_image()
 {
     $this->get('https://mydomain.test/storage/images/j2L3G12eel9sqsuNSGOYmcdqwUdchZtsfFGMeY90.jpg')->assertOk();
 }
```

The test fails.

Response status code [404] does not match expected 200 status code.
Failed asserting that false is true.

**Comment by ajest** [comment]
It is not working for me, DNS_PROBE_FINISHED_NXDOMAIN error thrown

**Comment by driesvints** [comment]
You're trying to execute a web request on a test domain. Try proxying it with something like ngrok.

**Comment by dorinniscu** [comment]
@driesvints Yes. It is my local test domain (Laravel Homestead). 
Http:get() works as expected. I tought the test should work as well.

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
