### ISSUE TITLE
Filter on (wherePivot or wherePivotNull) gives an error

### ISSUE THREAD

**Issue by philipboeken** [laravel/framework#37636]
- Laravel Version: 8.40.0
- PHP Version: 7.4.13
- Database Driver & Version: Microsoft SQL Server 2017

### Description:
wherePivot, wherePivotNull etc. cannot be used in a nested where clause.

### Steps To Reproduce:
Suppose I have a many-to-may relation (User - Role) with custom table names and primary keys, and a pivot table ‘UserRole’ with a ‘dateValidFrom’ column on the pivot table. If I define the relation on the User model and want to filter like this:
```
public function roles()
{
    return $this->belongsToMany(Role::class, 'UserRole', 'userID', 'roleID', 'userID', 'roleID')
        ->wherePivot('dateValidFrom', '<=', now())->wherePivotNull('dateValidFrom', 'or');
}
```
then all rows with dateValidFrom set to null are returned, as mentioned in [this issue](https://github.com/laravel/framework/issues/34840). Alternatively one could try 
```
public function roles()
{
    return $this->belongsToMany(Role::class, 'dbo.UserRole', 'userID', 'roleID', 'userID', 'roleID')
        ->where(function ($query) {
            $query->wherePivot('dateValidFrom', '<=', now())->wherePivotNull('dateValidFrom', 'or');
        });
}
```
which gives the following error:

SQLSTATE[42S22]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'pivot'. (SQL: select [Roles].*, [dbo].[UserRole].[userID] as [pivot_userID], [dbo].[UserRole].[roleID] as [pivot_roleID] from [Roles] inner join [dbo].[UserRole] on [Roles].[roleID] = [dbo].[UserRole].[roleID] where [dbo].[UserRole].[userID] = 261 and ([pivot] = dateValidFrom and [pivot_null] = dateValidFrom))

It seems that the nested query does not handle the withPivot condition properly, and that either

- this bug should be fixed,
- or that the withPivot, withPivotNull, ... functions should not facilitate this ‘or’ option, in which case the wherePivot conditions can be chained without nested where's and all is well.
- or that I'm overlooking something and it does work in some other way, in which case I apologise.

**Comment by driesvints** [comment]
Looks like this is stretching what pivots are meant to be used for. Try converting to an actual Eloquent model.
