### ISSUE TITLE
Can NOT access download method in Storage facade

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [laravel/framework#37633]
- Laravel Version: 8.12
- PHP Version: 7.3|^8.0
- Database Driver & Version: MySQL WITH version 5.1.0

### Description:
When I write `return  Storage::download(request()->file('img'), 'laravel');` the ERROR `Method Illuminate\Filesystem\Filesystem::download does not exist.` happens as shown <a href="https://imgur.com/a/W3jbH6A">here</a>

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
