### ISSUE TITLE
`queue:work` + `sticky` database - following a write job, subsequent jobs use the write PDO instead of the read PDO

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel/framework#37646]
- Laravel Version: v8.44.0 (also tested with v8.46.0)
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 5.7.32

### Description:

The `queue:work` combined with the database connection option `sticky` persists using the write PDO when processing jobs after a previous job wrote to the DB.

e.g.,
job 1: no writes, uses read PDO
job 2: some writes, uses write PDO
job 3: no writes, uses write PDO

In the docs there is a caveat:

> In addition, remember that any static state created or modified by your application will not be automatically reset between jobs.

However, I think the DB connection should be reset back to the read PDO when processing the next job.

### Steps To Reproduce:

```
dispatch(function () {
    // this will use the read PDO
    DB::table('test_table')->select()->get()->all();
});
dispatch(function () {
    // this will use the write PDO
    DB::table('test_table')->insert(...);
});
dispatch(function () {
    // this will use the write PDO
    DB::table('test_table')->select()->get()->all();
});
```

**Comment by driesvints** [comment]
Upgrade to latest version. There have been fixes for read/write operations.

**Comment by matthewnessworthy** [comment]
@driesvints upgraded Laravel to `v8.46.0`, the issue still exists as described above

**Comment by matthewnessworthy** [comment]
I suppose it's possible to listen for the `JobProcessing` event that the queue worker fires before processing a job, and call `DB::connection()->forgetRecordModificationState();`.
Something built-in to the framework would probably be better and I doubt I'm the only one with rogue high write DB usage without a clear cause.

**Comment by themsaid** [comment]
Yes you have to call `DB::connection()->forgetRecordModificationState();` inside the `JobProcessing ` event or the `Looping` event.

We can't enforce this or it'll be a breaking change.

**Comment by matthewnessworthy** [comment]
@themsaid / @driesvints I'm really struggling to accept that this is the expected and desired behaviour of the database sticky function.
Conceptually the feature is described to run per request (i.e., it's effect persisted until the end of a request cycle). 
Queue job processing bears many conceptual similarities to the request cycle.

An example:
Assuming you have only 1 long running queue processor that at some point in the past wrote something to the DB. Every subsequent DB access from dissimilar and unrelated queue jobs would now use the write PDO.

**Comment by themsaid** [comment]
This has been true for a long time so we have to keep it that way since nobody complained that this needs to change. Changing it would be breaking.

You can do it for your app the way you like, some people would keep the switch to write connection for a few seconds before they want workers to go back to reading from the read connection. Job processing is very fast and many people will want jobs to read the latest data that was written on the write instance.

**Comment by matthewnessworthy** [comment]
@themsaid how do you imagine switching back to the read connection after a couple of seconds? Is there a setting for that?

**Comment by matthewnessworthy** [comment]
@driesvints I've made a repo to better illustrate my points https://github.com/matthewnessworthy/sticky-db-queue-write-pdo

Keep in mind, if you have multiple queue processes, the write PDO state is not shared between them.
So having multiple processes, some having seen writes, and some not, will lead to a worse situation.

Chained jobs appear unaffected and switch to the write PDO after the first write action since they are processed within 1 "job".

Multiple processes can each have a different transitory read/write status depending on the history of that process.

And unless you have some for of process restart / management in place, once you switch to the write PDO there's nothing that automatically switches it back.

**Comment by themsaid** [comment]
@matthewnessworthy what you're saying is all true. All I'm saying is that we can't change that now or it'll be a breaking change. If you wish, you can send a PR for Laravel 9 to switch back the read connection after each job. Similar to how we do it in Octane: https://github.com/laravel/octane/blob/1.x/src/Listeners/FlushDatabaseRecordModificationState.php

**Comment by matthewnessworthy** [comment]
PR https://github.com/laravel/framework/pull/37668 created

**Comment by stillzombie** [comment]
@themsaid 
hi, i dont know this looks like uncommented thing that maybe it could be added on the upgrade list, in my case i struggle for a week trying to figure out a similar issue, i have a multi tenant app now running on laravel 9, that all the jobs are stored on the landlord connection and then when i handle the job i store some events or anything into the tenant connection, before in laravel 8 this was working fine but i believe due the sticky connection the behavior is like the first run everything works fine but if run dispatch again the job it will give me the following error: "Error: Call to a member function prepare() on null "


there is anyway to avoid the sticky connection?

i could use the mentioned DB::connection()->forgetRecordModificationState(); but i will need to do it in all my jobs right

**Comment by AidasK** [comment]
It's weird that @themsaid is calling this a "breaking change" as it's not breaking. Probably nobody using Laravel intended to use the sticky db option across jobs. I think Laravel just left it as an unintended bug. Fixing this is easy. Just do it in a major version, e.g., in Laravel 13.x, and mention it in the docs as a low-impact change. 

Besides this, it would be nice to hear why this is not a bug. Is there any practical example of why the sticky option should not be reset between jobs?

**Comment by Vladelis** [comment]
Agree with @AidasK. If you're not **very** careful on how you set up your queues (have both read and write jobs on the same queue) this can cause major unintended load on the main database thats also hard to debug, because in isolated environment the read job will always use the read connection.

**Comment by emycakes** [comment]
This issue persists, why is it closed? This should not be the default behavior.

**Comment by robert-moore96** [comment]
> It's weird that [@themsaid](https://github.com/themsaid) is calling this a "breaking change" as it's not breaking. Probably nobody using Laravel intended to use the sticky db option across jobs. I think Laravel just left it as an unintended bug. Fixing this is easy. Just do it in a major version, e.g., in Laravel 13.x, and mention it in the docs as a low-impact change.
> 
> Besides this, it would be nice to hear why this is not a bug. Is there any practical example of why the sticky option should not be reset between jobs?

while i agree with the general suggestion of do it in a major version, possibly with a way to control it via config / something in the jobs

as for an example of where preserving sticky would be desired, stuff around chained jobs + job batches seems like the obvious example 

tbh im having a harder time thinking of jobs i would want running against readonly connection than scenarios where switching back to it would break things

**Comment by importerror-fitful356** [comment]
> [@driesvints](https://github.com/driesvints) I've made a repo to better illustrate my points https://github.com/matthewnessworthy/sticky-db-queue-write-pdo
> 
> Keep in mind, if you have multiple queue processes, the write PDO state is not shared between them. So having multiple processes, some having seen writes, and some not, will lead to a worse situation.
> 
> Chained jobs appear unaffected and switch to the write PDO after the first write action since they are processed within 1 "job".
> 
> Multiple processes can each have a different transitory read/write status depending on the history of that process.
> 
> And unless you have some for of process restart / management in place, once you switch to the write PDO there's nothing that automatically switches it back.





https://django-paginationcute21.github.io/squirm/
