### ISSUE TITLE
Declare show route before create route in web.php give 404 not found

### ISSUE THREAD

**Issue by sawstar** [laravel/framework#37645]
- Laravel Version: 8.39.0
- PHP Version: 7.4.19
- Database : MySQL

### Description:

In web.php file if i declare show route before create route i get a 404 not found error when i try to access model/create URI for the example below 

**http://127.0.0.1:8000/passwordsManagement/categorie/create**

### Steps To Reproduce:

Error 404 : 
```
Route::prefix('passwordsManagement')->group(function(){
        Route::get('categorie',[CategorieController::class,'index'])->name('categorie.index');
        Route::get('categorie/{categorie}',[CategorieController::class,'show'])->name('categorie.show');
        Route::get('categorie/create',[CategorieController::class,'create'])->name('categorie.create');
        Route::post('categorie',[CategorieController::class,'store'])->name('categorie.store');
        Route::delete('categorie/{categorie}',[CategorieController::class,'destroy'])->name('categorie.destroy');
        Route::put('categorie/{categorie}',[CategorieController::class,'update'])->name('categorie.update');
});
```
Work : 
```
Route::prefix('passwordsManagement')->group(function(){
        Route::get('categorie',[CategorieController::class,'index'])->name('categorie.index');
        Route::get('categorie/create',[CategorieController::class,'create'])->name('categorie.create');
        Route::get('categorie/{categorie}',[CategorieController::class,'show'])->name('categorie.show');
        Route::post('categorie',[CategorieController::class,'store'])->name('categorie.store');
        Route::delete('categorie/{categorie}',[CategorieController::class,'destroy'])->name('categorie.destroy');
        Route::put('categorie/{categorie}',[CategorieController::class,'update'])->name('categorie.update');
});
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
