### ISSUE TITLE
Route::model('status', Status::class) explicit binding causes route not found for SPA route

### ISSUE THREAD

**Issue by asolopovas** [laravel/framework#37651]
- Laravel Version: 8.40
- PHP Version: 7.4.1
- Database Driver & Version:

### Description:
If I add `Route::model('status', Status::class)`  to `RouteServiceProvide.php` it results in the following query call `select * from statuses where id = 200 limit 1`  as well as not found returned when it should return `app.blade.php`, if I change `Route::model('statuses', Status::class)` it works normal.

### Steps To Reproduce:
https://github.com/asolopovas/laravel-status-bug

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by asolopovas** [comment]
It looks like a bug not support request
