### ISSUE TITLE
Validation Digits Between Rules Error

### ISSUE THREAD

**Issue by J2TeamNNL** [laravel/framework#37652]
- Laravel Version: ^8.12
- PHP Version: 7.4.11

## Description:
When frontend post JSON array to backend validate, I got success even it should be invalid.
### Request:
```json
{
    "tiers": [
        {
            "discount": "0"
        }
    ]
}
```

### Code Validate Request:
```php
public function rules(): array
{
    return [
        'tiers' => [
            'array',
        ],
        'tiers.*.discount' => [
            'integer',
            'digits_between:1,100',
        ],
    ];
}

protected function prepareForValidation(): void
{
    $this->merge(
        [
            'tiers' => json_decode($this->tiers, true),
        ]
    );
}
```
## Response Expect:
```json
{
    "message": {
        "tiers.0.discount": [
            "The tiers.0.discount must be between 1 and 100 digits."
        ]
    }
}
```
## Or this:
```json
{
    "message": {
        "tiers.0.discount": [
            "The tiers.0.discount must be an integer."
        ]
    }
}
```
But no, it passed. When I changed to min:1, max:100, it worked perfectly.

**Comment by jhuyvu** [comment]
Okay

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by J2TeamNNL** [comment]
Sorry but I think you made some misunderstanding @driesvints, I am reporting a bug, not asking the answer for my code

**Comment by driesvints** [comment]
@J2TeamNNL looks like a support request. Please try one of the channels above.

**Comment by J2TeamNNL** [comment]
Excuse me, I think this is a bug (and I had found a solution for myself), please read my code, I had to make it look clean and easy to see.
Sorry for bothering @driesvints  @taylorotwell.

**Comment by driesvints** [comment]
@J2TeamNNL look, if you really think this is a bug then please send in a PR with a failing test.

**Comment by J2TeamNNL** [comment]
@driesvints sorry again for my mistake about this function rule, it is about length, I thought that was about the min-max value. Thanks for your patience.
