### ISSUE TITLE
schema:dump generating errors in command line

### ISSUE THREAD

**Issue by jamespavett** [laravel/framework#37654]
- Laravel Version: 8.46.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.21

### Description:

Potentially same issue as [#34078](https://github.com/laravel/framework/issues/34078) that was mentioned to be fixed by commit [`d67be13`](https://github.com/laravel/framework/commit/d67be1305bef418d9bdeb8192177202f9d705699)  in a comment on PR [#34140](https://github.com/laravel/framework/pull/34140)

I am unable to run the schema:dump command in my current Laravel install. When ran I get the follow errors below suggesting `column-statistics=0` and `set-gtid-purged=OFF` are unknown variables. I know the `MySqlSchemaState` class was modified to prevent these issues, but I am unclear why they are still happening even though I am on the latest version.

![image](https://user-images.githubusercontent.com/10764464/121592341-7381e400-ca32-11eb-86e0-d63c9466954f.png)

![image](https://user-images.githubusercontent.com/10764464/121593064-631e3900-ca33-11eb-9f40-399de5a74383.png)

### Steps To Reproduce:

Run schema:dump on a fresh Laravel install using the aforementioned MySQL version.

Any help would be appreciated!

**Comment by driesvints** [comment]
I don't get the same error on MySQL 8.0.25 which is the latest version. Please upgrade MySQL and try again. Thanks

![Screen Shot 2021-06-11 at 11 43 41](https://user-images.githubusercontent.com/594614/121667321-71f40280-caaa-11eb-9c90-3ee62472cf39.jpg)

**Comment by jamespavett** [comment]
@driesvints is that actually an acceptable solution for this problem? Wasn't the commit introduced to fix this issue on earlier versions on MySQL?

**Comment by driesvints** [comment]
We can't account for every patch version of MySQL.

**Comment by jamespavett** [comment]
@driesvints I just updated my MySQL version to 8.0.25 and still get the same error?

Could the ticket please be reopened please.

**Comment by driesvints** [comment]
I can't reproduce it on that version. Please try a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks
