### ISSUE TITLE
Ably Event broadcasting not working

### ISSUE THREAD

**Issue by GamerFac3** [laravel/framework#37669]
I tried out ably as broadcasting Service. I followed the laravel documentation about installing and configuring the key.

When I try to create an Event Class with the "ShouldBroadcast" Interface, sometimes the event is recognized by ably in the developer console, sometimes its not. But it doesnt show up in the channel or includes it's public properties. 

When I use the AblyRest Class manually there is no problem, event triggers correctly everytime and includes the properties. 

Versions used:
PHP 8.0
Laravel 8.46.0
ably-php 1.1.4

Steps to reproduce:

1.  Install ably as described in laravel documentation
2. Create Event class and add "ShouldBroadcast" as interface, as you would normally do
3. Broadcast Event (I did this in the default / Route in web.php)
4. Keep an eye on ably developer console

**Comment by GamerFac3** [comment]
Well, looks like the debug tool at ably is not the best, the top table doesnt show any events for public channels. When I subsribed to public:testing I can see the events.

I propose to edit the laravel docs, because I couldn't find any notice that I need to add a public:<channel_name> to subscribe to the channel.  

Same is for private: and presence:

**Comment by driesvints** [comment]
Feel free to send a PR to the docs!

**Comment by bhfish2020** [comment]
they still have not fixed it, but yes if anyone sees this,
`public:test`

Should be the channel you watch in dev console.
`{
    "channelName":"testing",
    "message":"Hi there"
}`
Should be the post request to your server
