### ISSUE TITLE
middleware not accepting named parameter

### ISSUE THREAD

**Issue by codetestmg** [laravel/framework#37678]
- Laravel Version: ^8.40
- PHP Version:8.0.1

### Description:

```
Route::middleware( middleware:'guest')->group( callback: function () {

})

```
this will produce error below 

> ErrorException
> Undefined array key 0

if i remove `middleware:` then it works fine .

**Comment by netpok** [comment]
Yes, because `middleware` is not a real function it is implemented via magic `__call` method [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/Router.php#L1318) so it does not support named variables.
