### ISSUE TITLE
Laravel creating extra cookies with cookie as session driver

### ISSUE THREAD

**Issue by khavishbhundoo** [laravel/framework#37676]
- Laravel Version: v8.5.18
- PHP Version: 8.x
- Database Driver & Version:

### Description:
I am using the `cookie` SESSION_DRIVER and i notice that each time i close my browser and reopen my site i get  one extra cookie that get added and this behavior will eventually lead to cookie limit and browsers will refuse to fulfill the request.

See screenshot below
https://i.gyazo.com/7bd36cac35968ee0dacdf8920cecbd35.png

### Steps To Reproduce:
1.Set the `SESSION_DRIVER` to `cookie`
2.Set `expire_on_close` to true
3.Inspect cookies 
You will see `XSRF-token`, your site session cookie and one random hash cookie as expected
4.Close the browser and then reopen the site url again
Now you see the 3 cookies earlier + one extra random cookie
5.A additional random cookie will keep getting added each time you close the browser and reopen.

**Comment by khavishbhundoo** [comment]
I can reproduce this issue in chrome and firefox but not in opera

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by khavishbhundoo** [comment]
@driesvints I have been searching all over the internet including the resources above.The closest i found is this post on SO

https://stackoverflow.com/questions/36342882/laravel-cookie-storage-gets-exceeded-after-every-few-visits

I suspect it could also be the following:

https://bugs.chromium.org/p/chromium/issues/detail?id=128513

It would be great if you can reopen this issue so that we can have a discussion and a possible workaround so that we don't hit cookie limit when using cookie session driver

**Comment by driesvints** [comment]
@khavishbhundoo think it's best that you try writing down your own issue on Laracasts or so and also post on Discord. That's the fastest way someone can help you out.
