### ISSUE TITLE
Mistakenly overriding the CSRF token leads to a 404 error message

### ISSUE THREAD

**Issue by xwiz** [laravel/framework#37673]
- Laravel Version: 8.46.0
- PHP Version: 7.3.11
- Database Driver & Version: MariaDB 10.4

### Description:
Throws a 404 error instead of a CSRF token mismatch.

### Steps To Reproduce:

Create any form with csrf token and include the following in the html

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>$("form").on('submit', function(){  $("input['type=hidden']").val("2021-12-12") });</script>
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
