### ISSUE TITLE
helpers#method-str-replace

### ISSUE THREAD

**Issue by FranciscoCaldeira** [laravel/framework#37687]
- Laravel Version: 8.35.1
- PHP Version: 7.4.9
- Database Driver & Version: 10.5.5-MariaDB-1:10.5.5+maria~focal

### Description:
Tried to use the Str::replace() as in the [docs](https://laravel.com/docs/8.x/helpers#method-str-replace) but get error on tinker.

### Steps To Reproduce:
In tinker past the code from docs.
```
root@c6dd4af63e3c:/var/www/html# php artisan tinker
Psy Shell v0.10.7 (PHP 7.4.9 — cli) by Justin Hileman
>>> Illuminate\Support\Str::replace('8.x', '9.x', 'oi 8.x');
BadMethodCallException with message 'Method Illuminate\Support\Str::replace does not exist.'
>>> 
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by FranciscoCaldeira** [comment]
To test just did other test like Route::get('/test', function () {
    return Illuminate\Support\Str::replace('8.x', '9.x', 'Laravel 8.x');
});

**Comment by IgorGaming** [comment]
> To test just did other test like
> 
> ```
> Route::get('/test', function () {
>     return Illuminate\Support\Str::replace('8.x', '9.x', 'Laravel 8.x');
> });
> ```

Update laravel to [8.41.0](https://github.com/laravel/framework/releases/tag/v8.41.0)

**Comment by FranciscoCaldeira** [comment]
@IgorGaming Thanks will try and give feedback
