### ISSUE TITLE
Method Modules\Auth\Http\Controllers\AuthController::username does not exist Laravel 6

### ISSUE THREAD

**Issue by SevymolSebastian** [laravel/framework#37681]
- Laravel Version: 6.20.18
- PHP Version: 7.3.12

### Description:

When trying to integrate limit login attempts to custom controller in Laravel 6, I got the following error:

`exception: "BadMethodCallException"
file: "D:\\wamp64\\www\\alphabilling\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php"
line: 68
message: "Method Modules\\Auth\\Http\\Controllers\\AuthController::username does not exist."`

AuthController:

```
<?php

namespace Modules\Auth\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

use Auth;
use Validator;
use Illuminate\Foundation\Auth\ThrottlesLogins;

class AuthController extends Controller
{
    use ThrottlesLogins;

    protected $maxAttempts = 5;

    protected $decayMinutes = 1;

    public function login(Request $request)
    { 
        $input = $request->all();
        $rules = [
            'username'      =>  'required|email',
            'password'      =>  'required'
        ];
        $validator = Validator::make($input, $rules);
        if ($validator->fails()) {
            return false;
        }

        if (method_exists($this, 'hasTooManyLoginAttempts') &&
            $this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        $authenticated = Auth::attempt([
            'email'         =>  $request->input('username'), 
            'password'      =>  $request->input('password')
        ]);

        if($authenticated){
            $this->clearLoginAttempts($request);
        } else {
            $this->incrementLoginAttempts($request);
        }
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
