### ISSUE TITLE
Can Model::all() really return an array?

### ISSUE THREAD

**Issue by mattfoster7** [laravel/framework#37707]
The docblock here suggests `Model::all()` can return an array, which is throwing a Psalm error for me when I do `Model::all()->pluck.(..`. The way I see it, `Model:all()` will always ultimately return a `new Collection()`. What am I missing?

https://github.com/laravel/framework/blob/bda382f041ce5a3a6807976a693a6c272de2759a/src/Illuminate/Database/Eloquent/Model.php#L516

**Comment by driesvints** [comment]
We don't optimize for tools like psalm, sorry

**Comment by mattfoster7** [comment]
My question was more about whether the docblock is correct to say it can return an array of Models. I don't think it is correct.
