### ISSUE TITLE
Renaming a column doesn't rename the foreign key and the index name

### ISSUE THREAD

**Issue by binarweb** [laravel/framework#37705]
- Laravel Version: 8.46.0
- PHP Version: 7.4.4
- Database Driver & Version:  MariaDB 10.4.11

### Description:
As the title states, renaming a column in a migration doesn't rename the foreign key and the index name, leading to a problem in the future. Any drop statements of foreign key or the index will fail.

### Steps To Reproduce:

Create the new column:

```php
Schema::table('articles', function (Blueprint $table) {
    $table->unsignedBigInteger('new_user_id')
        ->nullable()
        ->after('id');
    $table->index('new_user_id');
    $table->foreign('new_user_id')->references('id')->on('users')->onDelete('set null')->onUpdate('cascade');
});
```

Now, the index name is called `articles_new_user_id_index` and the foreign key is called `articles_new_user_id_foreign`.  

Rename the column:

```php
Schema::table('articles', function (Blueprint $table) {
    $table->renameColumn('new_user_id', 'user_id');
});
```

Now, if I want to drop the column, without disabling foreign key checks, I would run:

```php
Schema::table('articles', function (Blueprint $table) {
    $table->dropForeign(['user_id']);
    $table->dropColumn('user_id');
});
```

And it would search for `articles_user_id_index` and `articles_user_id_foreign`,  
but in fact they are called `articles_new_user_id_index` and `articles_new_user_id_foreign`.

**Comment by lk77** [comment]
Hello,

you should call renameIndex method in your migration

**Comment by driesvints** [comment]
See the above. Thanks

**Comment by binarweb** [comment]
@lk77 I haven't considered this solution. Thanks for the solution!
