### ISSUE TITLE
PhpRedis zrevrangebyscore wrong signature

### ISSUE THREAD

**Issue by JimChenWYU** [laravel/framework#37701]
- Laravel Version: 6.20.27
- PHP Version: 7.2.*
- Database Driver & Version: Redis 2.8

### Description:

I find `zrevrangebyscore` signature is not same as official site.

https://redis.io/commands/zrevrangebyscore
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L263

Maybe should rename the parameters.

### Steps To Reproduce:

Redis client
```shell
> ZADD example 1 foo 2 bar 3 zoo
```

project
```php
$phpredisClient->zrevrangebyscore('example', 1, 3); // no data
$phpredisClient->zrevrangebyscore('example', 3, 1); // return data
```

**Comment by driesvints** [comment]
As you see from the internals the options already allow for both options to be passed.

**Comment by JimChenWYU** [comment]
![image](https://user-images.githubusercontent.com/12371374/122501953-3caa6000-d028-11eb-9376-5f75d646e668.png)
---
![image](https://user-images.githubusercontent.com/12371374/122502016-5ba8f200-d028-11eb-906a-92c0a211a6c7.png)

@driesvints It's all right?

**Comment by JimChenWYU** [comment]
https://github.com/phpredis/phpredis/#zrangebyscore-zrevrangebyscore

**Comment by driesvints** [comment]
@JimChenWYU feel free to attempt a PR if you really think it should be changed 👍
