### ISSUE TITLE
Integrity constraint violation for belongsToMany relationship inside a pivot table

### ISSUE THREAD

**Issue by pmochine** [laravel/framework#37711]
- Laravel Framework: v8.46.0
- PHP Version: 7.4.12
- Database Driver & Version: SQL lite

### Description:

I try to explain it simply. But please have a look first at:

[![enter image description here][1]][1]

To make it more understandable. We have three "normal" models (**User**, **Course** and **Lesson**) and two Pivot tables (**enrollments** should actually be called course_user but I changed the name so it is more clear and **enrollment_lesson**).

**My goal:** 

I just want to call the relationship: enrollment->lessons

But I get the error:

```
1) MyPackage\Course\Tests\Unit\EnrollmentTest::student_can_be_enrolled_to_a_lesson
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: enrollment_lesson.enrollment_id (SQL: insert into "enrollment_lesson" ("lesson_id", "enrollment_id", "created_at", "updated_at") values (2, ?, 2021-06-17 08:00:02, 2021-06-17 08:00:02))
```

Here is my code:

**course.php**
```
class Course extends Model
{
    /**
     * A course has many students enrolled.
     *
     */
    public function enrolledStudents()
    {
        return $this->belongsToMany(config('auth.providers.users.model'), 'enrollments', 'course_id', 'student_id')
            ->using(Enrollment::class)
            ->as('enrollment')
            ->withPivot('progress')
            ->withTimestamps();
    }
}
```

**enrollment.php**
```
use Illuminate\Database\Eloquent\Relations\Pivot;

class Enrollment extends Pivot
{
    protected $guarded = [];

    public $incrementing = true;

    public function lessons()
    {
        return $this->belongsToMany(Lesson::class, 'enrollment_lesson', 'enrollment_id', 'lesson_id')
            ->using(EnrollmentLesson::class)
            ->as('enrolledLesson')
            ->withTimestamps();
    }
}
```

And that is my code that results the error:

`$course->enrolledStudents()->first()->enrollment->lessons()->attach(2)`

Didn't get any answers on [StackOverflow](https://stackoverflow.com/questions/67990237/laravel-how-load-relationship-inside-pivot-relationship-without-using-third-par) and [Laracast](https://laracasts.com/discuss/channels/eloquent/can-you-load-a-relationship-inside-a-pivot-table)

  [1]: https://i.stack.imgur.com/tt4qD.png

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by pmochine** [comment]
@driesvints thank you for your fast reply!

Have a look at this repository: https://github.com/pmochine/bug-report-pivot

**Comment by driesvints** [comment]
When I debug your attach call it gives the following for the parent: 

```
App\Models\Enrollment {#2313
  #guarded: []
  +incrementing: true
  #connection: "sqlite"
  #table: "enrollment"
  #primaryKey: "id"
  #keyType: "int"
  #with: []
  #withCount: []
  +preventsLazyLoading: false
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:5 [
    "course_id" => "1"
    "student_id" => "2"
    "progress" => "0"
    "created_at" => "2021-06-17 17:02:52"
    "updated_at" => "2021-06-17 17:02:52"
  ]
  #original: array:5 [
    "course_id" => "1"
    "student_id" => "2"
    "progress" => "0"
    "created_at" => "2021-06-17 17:02:52"
    "updated_at" => "2021-06-17 17:02:52"
  ]
```

This is incorrect as this isn't the parent that needs to be used to make the insertion. I'm not sure if there's a bug here but I think there's things misconfigured on one of your models. I cannot immediately see what. But I suggest you continue to try a support channel. If you really believe there's a bug then we're open to PRs. Thanks

**Comment by pmochine** [comment]
@driesvints Thanks for the reply, but I'm still sure it's a bug.
I have updated the code on https://github.com/pmochine/bug-report-pivot and made it more minimalistic and more readable by not having my own name conventions.

[![Screenshot-2021-06-18-at-12-27-32.png](https://i.postimg.cc/NGD1L7yM/Screenshot-2021-06-18-at-12-27-32.png)](https://postimg.cc/bdGGBn9c)

Still, this doesn't work and bugs completely out. Please have another check.

And which "support channel" do you mean?

Can I maybe get help by @taylorotwell ?

**Comment by donnysim** [comment]
You need to specify custom parent key, it tries to read `course_user_id` from `course_user` but it doesn't exist, it has `user_id`:
```php
public function lessons()
{
    return $this->belongsToMany(Lesson::class, 'course_user_lesson', 'course_user_id', 'lesson_id', 'user_id')
        ->using(CourseUserLesson::class)
        ->withTimestamps();
}
```

**Comment by donnysim** [comment]
If `id` is intended, then most likely you just have to do:
```php
public function users()
{
    return $this->belongsToMany(User::class)
        ->using(CourseUser::class)
        ->withPivot(['id', 'progress']) // include "pivot" id
        ->withTimestamps();
}
```

**Comment by pmochine** [comment]
@donnysim hey! thanks for helping. This makes perfect sense. We get closer! Somehow I get the error:

General error: 1 no such table: main.course_users (SQL: insert into "course_user_lesson" ("lesson_id", "course_user_id", "created_at", "updated_at") values (1, 1, 2021-06-18 11:55:12, 2021-06-18 11:55:12))

Why is course_users set to plural?

**Comment by donnysim** [comment]
Laravel pluralizes all model names, CourseUser = course_users, if it doesn't match the table you created and want to use, you can set it via `$table` property in the model.

**Comment by pmochine** [comment]
@donnysim I really appreciate your help but the $table property in CourseUser doesn't change a thing. Still it says "General error: 1 no such table: main.course_users "

**Comment by donnysim** [comment]
Is there any details or reproduction how you get it?
```
General error: 1 no such table: main.course_users (SQL: insert into "course_user_lesson" ("lesson_id", "course_user_id", "created_at", "updated_at") values (1, 1, 2021-06-18 11:55:12, 2021-06-18 11:55:12))
```
does not make sense as the provided sql does not contain course_users table.

**Comment by pmochine** [comment]
@donnysim 

Yeah, I'm going to debug why it sets the table name in the plural. 

And what do you man, I just run the code in phpunit test. This is the full output:

```
1) Tests\Unit\EnrollmentTest::student_can_be_enrolled_to_a_lesson
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: main.course_users (SQL: insert into "course_user_lesson" ("lesson_id", "course_user_id", "created_at", "updated_at") values (1, 1, 2021-06-18 12:12:35, 2021-06-18 12:12:35))

/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:701
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:656
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:490
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:442
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2997
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1650
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1123
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1088
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:929
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:292
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:263
/Users/someuser/bug-report/tests/Unit/EnrollmentTest.php:47

Caused by
PDOException: SQLSTATE[HY000]: General error: 1 no such table: main.course_users

/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:483
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:694
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:656
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:490
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Connection.php:442
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2997
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1650
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1123
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1088
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:929
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:292
/Users/someuser/bug-report/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:263
/Users/someuser/bug-report/tests/Unit/EnrollmentTest.php:47

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by donnysim** [comment]
Oh, because you need to provide the pivot table for:
```php
return $this->belongsToMany(User::class, 'the_table')
```
otherwise it tries to resolve it by itself by glueing the 2 models - Course + User = course_users.

**Comment by donnysim** [comment]
You have an issue in the migration:

```php
$table->foreignId('course_user_id')->index()->constrained('course_user'); // <- need to point to course_user
```
and sqlite ignores it and hides the real issue when executing the query.

**Comment by pmochine** [comment]
@donnysim omg thank you 😭😭
