### ISSUE TITLE
Str::slug now returns different results

### ISSUE THREAD

**Issue by kofeinstyle** [laravel/framework#37714]
Laravel Version: 8.40.0
PHP Version: 7.4.20
Database Driver & Version: MySQL 8
Description:
I have a slug from string with Russian text in DB such as 'Анимационная студия Паровоз' and after update from Laravel 6 to Laravel 8 Str::slug generates different version Slug from this string.  

Steps To Reproduce:

Laravel 6:
```
>>> Str::slug('Анимационная студия Паровоз')
=> "animatsionnaya-studiya-parovoz"
```

Laravel 8:
```
>>>  Str::slug('Анимационная студия Паровоз')
=> "animacionnaya-studiya-parovoz"
```
It's a problem for me right now because sometimes I need to find DB row by sluggable string

**Comment by netpok** [comment]
I don't know russian, but based on a random tool that I found on google the Laravel 8 behavior seems to be correct. In this case you probably should update your links (which is probably not possible) or add a compatibility fallback to try the old style name if the new one fails.

You should compare the 
6.x ascii method: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Support/Str.php#L84 and the
8.x ascii method: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/Str.php#L97

**Comment by driesvints** [comment]
Feel free to send a note to the upgrade guide if you want 👍

**Comment by kofeinstyle** [comment]
> I don't know russian, but based on a random tool that I found on google the Laravel 8 behavior seems to be correct. In this case you probably should update your links (which is probably not possible) or add a compatibility fallback to try the old style name if the new one fails.
> 
> You should compare the
> 6.x ascii method: https://github.com/laravel/framework/blob/6.x/src/Illuminate/Support/Str.php#L84 and the
> 8.x ascii method: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/Str.php#L97

Thank you. I saw the difference between laravel 6.x and 8.x ascii method. New version uses external lib instead of laravel native ascii method.
This means I need regenerate slugs in DB via new ascii method. I hope this helps me!

**Comment by netpok** [comment]
Yeah, if the original data is available then just simply update the old slugs with the new slugs. If you have external links you may want to store the old ones somewhere and use it to map them to the new ones.
