### ISSUE TITLE
Update JSON Attribute blocked by Guarded Check

### ISSUE THREAD

**Issue by jonrobinson** [laravel/framework#37724]
- Laravel Version: 8.47.0
- PHP Version: 7.4.14
- Database Driver & Version:

### Description:
The JSON `->` update helper, as described here: https://laravel.com/docs/8.x/eloquent-mutators#array-and-json-casting, does not work. 

```
$user = User::find(1);

$user->update(['options->key' => 'value']);
```

### Steps To Reproduce:
1. Create a model with `protected $guarded = ['id'];` and `protected $casts = [ 'options' => 'array'];`
2. Grab a model instance. `$user = $user->find(1);`
3. Attempt to update a nested value: `$user->update(['options->dinner' => 'pizza']);`

### Area of Code
This fails in the trait `Illuminate\Database\Eloquent\Concerns\GuardsAttributes` because when checking `$this->isFillable($key)` the `$this->isGuarded($key)` will return `true`. 

In this part of logic you are guarding anything that _is not_ a "valid, guardable column" or basically in the database schema. 
LINE 208: `! $this->isGuardableColumn($key = 'options->dinner')` 

But the issue is that a key of `'options->dinner'` will not be in the database. 

### Solution
Taylor removed this check for JSON: https://github.com/laravel/framework/commit/897d107775737a958dbd0b2f3ea37877c7526371

I think the solution is just to add it back:
```
/**
     * Determine if the given key is guarded.
     *
     * @param  string  $key
     * @return bool
     */
    public function isGuarded($key)
    {
        if (empty($this->getGuarded())) {
            return false;
        }
        
       // < -- here -->  
        if (strpos($key, '->') !== false) {
             $key = Str::before($key, '->');
        }

        return $this->getGuarded() == ['*'] ||
               ! empty(preg_grep('/^'.preg_quote($key).'$/i', $this->getGuarded())) ||
               ! $this->isGuardableColumn($key);
    }

```

**Comment by driesvints** [comment]
Heya, thanks for reporting. This change was made intentional and isn't a bug.
