### ISSUE TITLE
ShouldBeUnique doesn't clear lock when job is finished.

### ISSUE THREAD

**Issue by rflatt-reassured** [laravel/framework#37729]
- Laravel Version: 8.47.0
- PHP Version: 7.4.10
- Horizon Version 5.7.9

### Description:
ShouldBeUnique and ShouldBeUniqueUntilProcessing do not release lock unless a timeout is set, and then it only releases after the timeout has expired, not after the job has been processed.

### Steps To Reproduce:
```
class ... implements ShouldQueue, ShouldBeUnique
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    private $userId;

    /**
     * The unique ID of the job.
     *
     * @return string
     */
    public function uniqueId()
    {
        return $this->userId;
    }    

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($userId)
    {
        $this->userId = $userId;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        try {
            //call the stored proc to assign a lead:
            $assigned = \DB::select('CALL ...(' . $this->userId . ')');
            $data = [
                'Status' => 'success',
                'result_id' => $result[0]->id
            ];
            event(new BroadcastToUser($this->userId, 'event', $data));

        } catch (\Exception $e) {
            event(new BroadcastToUser($this->userId, 'event', ['Status' => 'error']));
        }
    }
```
The above job runs once for $this->userId, but then will never be added to the queue again, unless I remove `ShouldBeUnique`.

**Comment by driesvints** [comment]
What do you mean with "do not release lock"? There's not a lot of info here. Not sure what's wrong?

**Comment by rflatt-reassured** [comment]
I can add a job with a $userId = 123 (for example) to the queue, and it will process it. If I try adding it to the queue again, it won't add it because the lock for $this->userId  is still there: 
```
    /**
     * The unique ID of the job.
     *
     * @return string
     */
    public function uniqueId()
    {
        return $this->userId;
    } 
```

I briefly changed the cache driver for the job locks to be database:
```
    /**
     * Get the cache driver for the unique job lock.
     *
     * @return \Illuminate\Contracts\Cache\Repository
     */
    public function uniqueVia()
    {
        return Cache::driver('database');
    }
```
The expiration was set to 24 hours from now. The lock did not seem to be released after the job was processed. There were no failed jobs,

So the lock for userId = 123 still existed, and I could not add any further jobs to the queue for that id, even when there were no jobs in the queue.

**Comment by driesvints** [comment]
What cache driver are you using at first?

**Comment by rflatt-reassured** [comment]
I was using redis. 

The problem seems to have cleared itself. Removing ShouldBeUnique, sending jobs with the same id, and then putting it back seems to have fixed the issue with no other code changes. It is a bit concerning, but I can no longer replicate the issue.

**Comment by driesvints** [comment]
Good that you got it solved 👍

**Comment by guilheb** [comment]
Not sure how to request to have the issue reopened, but I have the exact same issue with the file cache driver.

**Comment by mfauveau** [comment]
@driesvints 

I'm seeing the same issue using Redis or other cache drivers.

I dispatch the job, I see the lock created in the cache and then I see the job completed in Horizon. However, checking cache again, the lock is still here and any attempt to dispatch the job again will not succeed unless the lock is removed manually.

Documentation states that the lock should be released when the job is completed but that doesn't happen.

I tried looking for ShouldBeUnique in the code base to see where in the code Laravel looks for that interface to see if it should release the lock but was unable to find it.

Are we all missing something?
