### ISSUE TITLE
Http Client: ConnectionException occurs when sending certain amount of requests

### ISSUE THREAD

**Issue by buildkloe** [laravel/framework#37723]
- Laravel Version: ^8.37.0
- PHP Version: 8.0.7
- Database Driver & Version:

### Description:
ConnectionException occurs when sending certain amount (around 80 times)  of Http requests back to back.
The code is working fine in 8.36.0 but not the newer versions. It seems the issue is related to the new added concurrent async request feature.

- Tested environment: macOS 11.4

### Steps To Reproduce:

Code to reproduce the issue
```
        try {
            foreach (range(0, 200) as $number) {
                dump($number);
                // adding sleep doesn't seem to have any impact
                usleep(100000);
                Http::get('https://example.com');
            }
        }catch (\Exception $ex) {
            dump($ex);
        }
```

Exception:
```
Illuminate\Http\Client\ConnectionException^ {#7605
  #message: "cURL error 6: Could not resolve host: example.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://example.com"
  #code: 0
  #file: "./vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php"
  #line: 663
  -previous: GuzzleHttp\Exception\ConnectException^ {#7644
    -request: GuzzleHttp\Psr7\Request^ {#7636
      -method: "GET"
      -requestTarget: null
      -uri: GuzzleHttp\Psr7\Uri^ {#7633
        -scheme: "https"
        -userInfo: ""
        -host: "example.com"
        -port: null
        -path: ""
        -query: ""
        -fragment: ""
      }
....      
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
