### ISSUE TITLE
Getting an occasional MissingAppKeyException

### ISSUE THREAD

**Issue by bruffstar** [laravel/framework#37721]
- Laravel Version: 8.47.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL MariaDB 10.4.11

### Description:
I have all my env variables setup correctly, key is generated, etc. I have an ImageController which returns images from the storage directory, only if that particular image is "unlocked", so there is a tiny bit of logic which handles this (no DB stuff). Everything works fine 99.9% of the time, however, on a page with many images, I sometimes get a 500 response on 1 or 2 images. When I check the logs, I see a MissingAppKeyException was thrown. This is of course not correct, because the key is set and the other 99% of images load just fine. Note: it is random which images fail, they are not the same every time.

I logged out the key in `Illuminate\Encryption\EncryptionServiceProvider.php` ...

![image](https://user-images.githubusercontent.com/1890098/122481751-903c8f80-cfcf-11eb-931a-307ef8edad60.png)

As you can see, for the occasion when it failed, it switches to "production" and the key is null. It seems like when too many requests, the env file is not being read.

Any help with this would be great. It may be a local issue with PHP memory or something similar, I have no clue.

### Steps To Reproduce:
I created a fresh install and was able to replicate the issue. You will find the repo here: 
https://github.com/bruffstar/laravel-bug 

Just go to "/" and hard refresh the page a couple of times, eventually you will see that some images return a 500 error:

![image](https://user-images.githubusercontent.com/1890098/122485394-0b557400-cfd7-11eb-9ecc-42a7a4ac0c43.png)

I created a new branch with the changes: https://github.com/bruffstar/laravel-bug/pull/1/files

I also commited the log file with the errors: https://github.com/bruffstar/laravel-bug/blob/reproduce/storage/logs/laravel.log

**Comment by donnysim** [comment]
You should cache your config if you want to avoid it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bruffstar** [comment]
@donnysim yes, I tried this and it worked. However, I would still like to know what the root cause of this is.

**Comment by donnysim** [comment]
I believe it's mostly related to how php and apache env works as `getenv` is not thread safe or something. You could go dig around https://github.com/vlucas/phpdotenv issues that explain such edge cases.

**Comment by bruffstar** [comment]
Yeah, sounds like that's the problem (https://github.com/vlucas/phpdotenv/issues/248#issuecomment-450903446). 

Oh well, config cache does fix the issue anyway.
