### ISSUE TITLE
Can't override HTTP client headers

### ISSUE THREAD

**Issue by atymic** [laravel/framework#37748]
- Laravel Version: v8.47.0
- PHP Version: 7.4

### Description:

Basically, it's not possible to override headers set on the http client properly. 

For example this code:

```
$response = Http::asForm()
                ->contentType('a-custom-content-type')
                ->post('https://example.come', $['a' => 'b']);
```

Will cause a request to be send with two content type headers, both `application/x-www-form-urlencoded` and `a-custom-content-type` which is breaking the API i'm trying to interact with.

I thought it would be possible to override the content type headers, but the `withHeaders` method always adds a new header, instead of replacing it.

Ideally, it specifying a header that already exists would just replace it, instead of sending double headers. Or a way to remove a set header.

Thanks!

**Comment by driesvints** [comment]
That's intended. You're using `asForm` which will add the `application/x-www-form-urlencoded`. If you don't need that then don't use that method.

**Comment by atymic** [comment]
The same example would apply if you set the content type header twice by accident. I guess maybe worth a note in the docs at least that withHeaders duplicates instead of replaces existing headers?

**Comment by driesvints** [comment]
Would appreciate a pr. Thanks
