### ISSUE TITLE
[BUG] `NotificationFailed` event not fired when a notification fails

### ISSUE THREAD

**Issue by mohammed-elhaouari** [laravel/framework#37749]
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: N/A

### Description:

Laravel fires a list of events when sending notifications through different channels. as documented here: https://laravel.com/docs/8.x/notifications#notification-events

The bug is related to the notifications events, not being fired properly, more precisely the `NotificationFailed` event not being fired at all, and the class not being used at all inside laravel core code. 

The `NotificationFailed` class was added in this PR https://github.com/laravel/framework/pull/14874 but it seems that the implementation was not complete or for some reason, the class was just added as a placeholder.

### Steps To Reproduce:

- **Step 1**: Add the following to the `EventServiceProvider`

```php
  /**
   * Track notification sending events.
   * @see https://laravel.com/docs/8.x/mail#events
   */
  NotificationSending::class => [
      LogSendingNotification::class,
  ],
  NotificationSent::class => [
      LogSentNotification::class,
  ],
  NotificationFailed::class => [
      LogFailedNotification::class,
  ],
```
- **Step 2**: Create the following Listeners `LogSendingNotification`,`LogSentNotification`,`LogFailedNotification` 
- **Step 2**: Add some wrong `SMTP` credentials
- **Step 3**: Dispatch any email notification. ex (WelcomeEmailNotification)

- Outcome: 
The `NotificationFailed` event will not fire, even though the notification has been failed. 
if you put a correct SMTP credential and fire the same notification, the `NotificationSent` & `NotificationSending` events will fire properly.

The code in question is : 

```php
    protected function sendToNotifiable($notifiable, $id, $notification, $channel)
    {
	protected function sendToNotifiable($notifiable, $id, $notification, $channel)
            return;
        }

        $response = $this->manager->driver($channel)->send($notifiable, $notification);

        $this->events->dispatch(
            new NotificationSent($notifiable, $notification, $channel, $response)
        );
    }
  ```
I have opened a pull request (https://github.com/laravel/framework/pull/37722) that explores a way of solving this issue, but it has been closed by @taylorotwell

**Comment by driesvints** [comment]
I'm sorry but your PR was closed. We won't be doing any changes in this area for now.

**Comment by Dartui** [comment]
@mohammed-elhaouari hi, I have encountered same problem, but I have made workaround. You need to override `MailChannel` with your own implementation with try/catch block. A lot of work needs to be done for achieving simple behavior but hey, it works.

```php
// app/Providers/AppServiceProvider.php

namespace App\Providers;

use App\Support\Notifications\MailChannel;
use Illuminate\Notifications\Channels\MailChannel as BaseMailChannel;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        // other code...

        // Replace base mail channel implementation.
        $this->app->bind(BaseMailChannel::class, MailChannel::class);
    }
}
```

```php
// app/Support/Notifications/MailChannel.php

namespace App\Support\Notifications;

use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Contracts\Mail\Factory as MailFactory;
use Illuminate\Mail\Markdown;
use Illuminate\Notifications\Channels\MailChannel as BaseMailChannel;
use Illuminate\Notifications\Events\NotificationFailed;
use Illuminate\Notifications\Notification;
use Throwable;

class MailChannel extends BaseMailChannel
{
    protected Dispatcher $dispatcher;

    /**
     * Create a new mail channel instance.
     *
     * @param \Illuminate\Contracts\Events\Dispatcher $dispatcher
     * @param \Illuminate\Contracts\Mail\Factory      $mailer
     * @param \Illuminate\Mail\Markdown               $markdown
     */
    public function __construct(
        Dispatcher $dispatcher,
        MailFactory $mailer,
        Markdown $markdown
    ) {
        $this->dispatcher = $dispatcher;
        $this->mailer     = $mailer;
        $this->markdown   = $markdown;
    }

    /**
     * Send the given notification.
     *
     * @param mixed                                  $notifiable
     * @param \Illuminate\Notifications\Notification $notification
     *
     * @return bool
     */
    public function send($notifiable, Notification $notification): bool
    {
        try {
            parent::send($notifiable, $notification);
        } catch (Throwable $e) {
            $this->dispatcher->dispatch(
                new NotificationFailed($notifiable, $notification, 'mail')
            );

            return false;
        }

        return true;
    }
}
```

Now is tricky part. You cannot throw exception in `MailChannel::send` method, because it will stop executing other channels. You cannot prevent dispatching `NotificationSent` event, but you can use `$event->response` in your `NotificationSent` listener to prevent it's logic to execute. 

```php
namespace App\Listeners;

use Illuminate\Notifications\Events\NotificationSent;

class NotificationSentListener
{
    /**
     * Handle the event.
     *
     * @param \Illuminate\Notifications\Events\NotificationSent $event
     *
     * @return void
     */
    public function handle(NotificationSent $event)
    {
        /*
         * Do not store sent notification log if response from
         * channel `send` method returns false.
         */
        if ($event->response === false) {
            return;
        }

        // rest of your logic...
    }
}
```

It's a pity that this wasn't merged. Hope that my solution will help.

**Comment by mohammed-elhaouari** [comment]
Thanks, @Dartui. Yeah, I think the notification's system needs a revamp for a better multichannel support.

**Comment by DePalmo** [comment]
The code that @Dartui provided works well, but not in combination with Queue. When checking the execution through `queue:listen`, it shows as that the job completed successfully and it's not failing it. Because of this, the job is then not moved into `failed_jobs` table and can't be re-tried at later time. I tried a lot of combinations on how to fail a job (since the `send()` method in `MailChannel` is an extension of original, was expecting that this would work), but failed.

Any ideas on how to forward the same response from `send()` method that `MailChannel` extends? Since if I remove the try-catch block, then the job fails properly and can then be re-tried at later time.
