### ISSUE TITLE
FileFactory can't create gif files

### ISSUE THREAD

**Issue by AmirRezaM75** [laravel/framework#37742]
- Laravel Version: 8.43.0
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 8.0

### Steps To Reproduce:
I needed to create **image** file with **gif** extension in my tests.
```
$this->post('dashboard/media', [
    'image' => UploadedFile::fake()->image('example.gif')
])->assertRedirect('dashboard/media');
```
I get image file using `` $request->file('image')`` and save it in storage disk.
It saves the file with correct extension but when I'm using ``mime_content_type``, it returns ``image/png``.

### Description:
I scanned the code base and I noticed we can only create jpeg or png files with this class.

https://github.com/laravel/framework/blob/952f84a3a5449a5f80190479240fce15bdaad558/src/Illuminate/Http/Testing/FileFactory.php#L57-L59

**Comment by driesvints** [comment]
Seems like a feature request. Seems like you already attempted a pr. Thanks.
