### ISSUE TITLE
Parallel Testing fails to use SQLite and instead uses Production MySQL

### ISSUE THREAD

**Issue by byteasc** [laravel/framework#37741]
- Laravel Version: 8.46.0
- PHP Version: 8.0.6
- Database Driver & Version: SQLite / MySQL

### Description:
While doing some experimenting to see if Laravel's Parallel Unit testing was viable for our infrastructure, it ended up deleting some data on our production databases. 

We're taking steps to mitigate by addressing the availability of DB Credentials prior to the testing, but we aren't seeing the same issue with PHPUnit by itself, nor with Paratest. 

I would expect that running `php artisan test --parallel` would use the same `phpunit.xml` file as the others, ran from the same folder, which designates what database driver etc.

**Comment by driesvints** [comment]
> I would expect that running php artisan test --parallel would use the same phpunit.xml file as the others, ran from the same folder, which designates what database driver etc.

It does. If not, feel free to try to provide a repo which reproduces this and I'll re-open.

Also: I strongly suggest to not run tests in production to prevent things like this.
