### ISSUE TITLE
Log exceptions in queue:work

### ISSUE THREAD

**Issue by dihak** [laravel/framework#37755]
https://github.com/laravel/framework/blob/952f84a3a5449a5f80190479240fce15bdaad558/src/Illuminate/Queue/Console/WorkCommand.php#L158-L162

How to add exceptions to the work command? I want some error is not inserted into the database.

Thank you

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
