### ISSUE TITLE
how pass data to x-slot?

### ISSUE THREAD

**Issue by miladkhodaverdi23** [laravel/framework#37758]
- Laravel Version: 8.32.1
- PHP Version: 7.4

### Description:

I want to pass a variable to the x-slot
The slot is rendered before the component is rendered . why? is big problem :(((((

components\data-table.blade.php

```
<div >
    <table id="{{$id}}" class="table">
        <thead class="thead-light">
        <tr>
            @foreach($columns as $column)
                 {{$test1}}
            @endforeach
        </tr>
        </thead>
    </table>
</div>
```

app.blade.php

```
<x-data-table
                :columns="[
                        ['title'=>'','data'=> 'id', 'orderable'=> false],
                        ['title'=>'First Name', 'data'=> 'first_name', 'orderable'=> false],
                        ['title'=>'Last Name', 'data'=> 'last_name',  'orderable'=> false],
                        ['title'=>'National Code', 'data'=> 'national_code',  'orderable'=> false],
                        ['title'=>'Phone', 'data'=> 'phone', 'orderable'=> false],
                        ['title'=>'','data'=> 'action', 'orderable'=> false]
                    ]"
                url="http://portal.test/users?section=triage&triage=true"
>
<x-slot name="test1" >
     {{$column->id}}
</x-slot>
</x-data-table>
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by NorthBlue333** [comment]
Hello,
My comment is about this issue and also this PR https://github.com/laravel/framework/pull/29111.

I know it is a bit old, but I'd like to add my point of view.

I agree with @Angelinsky7, we should be able to customize __some display logic, in specific places decided by the component creator__. In fact, as @browner12 says: 
> Components are responsible for the display logic. Slots are ways to pass data to the component.

This is correct, but not entirely : you may have a (big) component, i.e. a datatable with filters, headers, etc. (a lot of logic and display logic you do NOT want to be duplicating), but you may also want to allow the developer to use the component and customize what is displayed inside each cell.

This exemple is what is available in Vuetify (VueJS), here is the doc https://vuetifyjs.com/en/components/data-tables/#item.

**Comment by NorthBlue333** [comment]
Hello,
My comment is about this issue and also this PR https://github.com/laravel/framework/pull/29111.

I know it is a bit old, but I'd like to add my point of view.

I agree with @Angelinsky7, we should be able to customize some display logic, in specific places decided by the component creator. In fact, as @browner12 says:

Components are responsible for the display logic. Slots are ways to pass data to the component.

This is correct, but not entirely : you may have a (big) component, i.e. a datatable with filters, headers, etc. (a lot of logic and display logic you do NOT want to be duplicating), but you may also want to allow the developer to use the component and customize what is displayed inside each cell.

This exemple is what is available in Vuetify (VueJS), here is the doc https://vuetifyjs.com/en/components/data-tables/#item.

I have also found this https://github.com/laravel/ideas/issues/2116, where the PR for `@aware` directive is mentioned. But this directive only allows access to component attributes and not loop variables (i.e.).

**Comment by robsontenorio** [comment]
@NorthBlue333 your example does not solve the original comment. Or am I missing something?

```
<x-slot name="test1" >
     {{$column->id}} <—- how to access current item from loop ?
</x-slot>
```

**Comment by NorthBlue333** [comment]
@robsontenorio indeed it does not. My example does not use x-slot at all as it is a workaround using «sub-components».

**Comment by mshamaseen** [comment]
I'm facing the same issue.
It is weird that this is not of interest to the community; how do you guys make dynamic tables then :thinking:

**Comment by mshamaseen** [comment]
ok I found a workaround for this, base a function as an attribute and execute it in the component, like:

## Base
```
<x-pagination.length-aware-pagination :columns="[
'name',
'status'
]" :paging="$entities">
    <x-slot:status :html="fn($entity) => $entity->status.' worked' ">

    </x-slot:status>
</x-pagination.length-aware-pagination>
@endsection
```

## component
```
 @foreach($columns as $column)
    @if(isset($$column) && $$column instanceof \Illuminate\View\ComponentSlot)
        <th>{{$$column->attributes->get('html', fn() => $$column)($entity)}}</th>
    @else
        <th>{{$entity[$column]}}</th>
    @endif
@endforeach
```
