### ISSUE TITLE
Json columns can be set using object syntax but not retrieved

### ISSUE THREAD

**Issue by coleshirley** [laravel/framework#37767]
- Laravel Version: 8.47.0
- PHP Version: 8.0.5
- Database Driver & Version: mysql 8.0

### Description:

If you have an eloquent model that utilizes json columns it is possible to use object property syntax to set a value within the json column but you are unable to retrieve and values from the json column using the same syntax. 

For example (assuming I have a Post model defined with a "properties" json column):

![image](https://user-images.githubusercontent.com/84236864/122828665-307e0700-d2a3-11eb-87a1-a17b7dd7c59d.png)

This ability to set a json attribute using object syntax is found in laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php  setAttribute($key, $value) lines 778 - 780 where a check is done to see if $key contains '->'. 

The equivalent code for getAttribute($key) in the same file does not exist

### Steps To Reproduce:

Base Laravel Install +

app/Models/Post.php

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
}
```

database/migrations/2021_06_21_192942_create_posts_table.php

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePostsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->json('properties')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('posts');
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by coleshirley** [comment]
@driesvints Maybe I didn't explain it the right way but this issue is related to missing functionality in the framework not a support request.

If you look at my tinker output that I included an image of I demonstrated that 

```php
$model->{'properties->title'} = 'My Title';
```

works just the way you would expect and sets the title key in the $properties json attribute. 

However running

```php
echo $model->{'properties->title'};
```

returns null when it would be expected that it would return 'My Title'

I don't see how this is a support request

**Comment by driesvints** [comment]
It was removed due to it being a security breach. Please ask on a support channel or look around for relevant articles.

**Comment by coleshirley** [comment]
For anyone interested in this functionality it can be added to an eloquent model class with the following code:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class Post extends Model
{
    /**
     * Get an attribute from the model.
     *
     * @param  string  $key
     * @return mixed
     */
    public function getAttribute($key)
    {
        $value = parent::getAttribute($key);

        if (is_null($value) && Str::contains($key, '->')) {
            $value = $this->getJsonAttribute($key);
        }

        return $value;
    }

    /**
     * Get a given JSON attribute on the model.
     *
     * @param  string  $key
     * @return $this
     */
    public function getJsonAttribute($key)
    {
        [$key, $path] = explode('->', $key, 2);

        return Arr::get($this->getArrayAttributeByKey(
            $key
        ), str_replace('->', '.', $path));
    }
}
```

**Comment by browner12** [comment]
anyone have any idea where it was removed? i've been digging and cannot find it. would love to read more about it, and see if 3 years later we can do this without the security issue.

**Comment by browner12** [comment]
I think I finally found some related stuff:

https://github.com/laravel/framework/pull/33777
https://github.com/laravel/framework/pull/34640
https://github.com/laravel/framework/pull/37726
