### ISSUE TITLE
Eloquent Builder whereIn method returning incorrect query result

### ISSUE THREAD

**Issue by zebamba** [laravel/framework#37768]
- Laravel Version: 8.47.0
- PHP Version: 7.4.8
- Database Driver & Version: MySql & MariaDB 10.3.29

### Description:
During developing an app and testing filtering some data I found that `whereIn()` method was returning an incorrect query result

The method on my model receives an arrays of integers and returns the builder instance.

```php
    return $this->model->whereHas('relationship', function ($query) use ($ids) {
        $query->whereIn('some_id', $ids);
    });
```

I noticed that the query result it was not the expected result, so I decided during  debugging the code to check the SQL statement.

As the filter class has the builder instance I ran `$buider->toSql()` and the `whereIn()` method generates SQL statement as you can see the example bellow.

```sql
    SELECT * from `table` 
    WHERE `some_id` IN (1) 
    AND `some_id` IN (10) 
    AND `table`.`deleted_at` IS NULL 
    ORDER BY `name` ASC;
```

In my scenario the records does not contain some of the provided ids, because `AND` operator is added when the code loops on the array provided, the query result was incorrect. 

So, for now I decided to replace `whereIn()` by `whereRaw()`

```php
    $ids = implode(',', $ids);

    return $this->model->whereHas('relationship', function ($query) use ($ids) {
        $query->whereRaw('homebuilder_id IN ('. $ids . ')');
    });
```

The expected SQL Statement now is:

```sql
    SELECT * from `table` 
    WHERE `some_id` IN (1,10) 
    AND `table`.`deleted_at` IS NULL 
    ORDER BY `name` ASC;
```

My suggestion is to generate something along with `WHERE field IN (?)`  not with `AND` operator .

Thank you.

**Comment by Nacoma** [comment]
Can you provide the code used in the defined relationship and verify that your ID array contains what you're expecting? I'm unable to replicate this in any capacity.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by martinbean** [comment]
@driesvints Apologies, but this is definitely a bug and not a “support” issue.

I’ve just tried to fetch some orders that have an item related to a subset of SKUs in my application. My code looks like this:

```php
```

```sql
select count(*) as aggregate from "orders" where exists (select * from "order_items" where "orders"."id" = "order_items"."order_id" and 0 = 1)
```
