### ISSUE TITLE
Http Pool results should maintain original order of requests

### ISSUE THREAD

**Issue by lukeb** [laravel/framework#37774]
- Laravel Version: 8.47.9
- PHP Version: 8.0.2
- Database Driver & Version:

### Description:
The responses from Http::pool should remain in the order that they were added to the pool.
When adding to the pool with as('string'), the responses are reordered by key alphanumerically.
This is not the desired outcome, since it is expected that they are in the same order.

### Steps To Reproduce:
```
$responses = Http::pool(fn (Pool $pool) => [
    $pool->as('luke')->get('https://onjax.com/team/luke-brookhart'),
    $pool->as('brian')->get('https://onjax.com/team/brian-lopresto'),
    $pool->as('alison')->get('https://onjax.com/team/alison-brookhart'),
    $pool->as('chris')->get('https://onjax.com/team/chris-ruggiero'),
]);

dd(array_keys($responses));
```

### Expected results
['luke','brian','alison','chris']

### Actual results
['alison','brian','chris','luke']

**Comment by driesvints** [comment]
seems like a feature request. I see you already sent in a PR 👍
