### ISSUE TITLE
The dispatchSync method doesn't respect middleware

### ISSUE THREAD

**Issue by sharifzadesina** [laravel/framework#37778]
- Laravel Version: ^8.0
- PHP Version: ^7.3
- Database Driver & Version: Doesn't Matter

### Description:

Hello,
If you remember issue #29917, people were asking sync jobs to respect the middleware option.
So, thanks to Taylor, we got a new method called `dispatchSync`, which respects middleware for sync jobs.
but there is a major problem with it, imagine we have these two jobs:

```php
class OurMiddleware
{
}

class SyncJob
{
    public function middleware()
    {
        return [new OurMiddleware];
    }
}

class NormalJob implements ShouldQueue
{
    public function middleware()
    {
        return [new OurMiddleware];
    }
}
```

Obviously, the `SyncJob` class, doesn't implement the `ShouldQueue` interface, because it is a sync job, and we don't want it to be queued. so what will happen?
Well! the middleware will run perfectly for the `NormalJob`, but when we will try to run `SyncJob` using `dispatchSync`, the middleware won't run, because it doesn't implement `ShouldQueue` interface.
We wanted to solve this issue by adding the great `dispatchSync` method, but it is now just like `dispatchNow`.

Because of this problem, we can't use the `OurMiddleware` class for all jobs and we need to implement it the traditional way.

**Comment by sharifzadesina** [comment]
I think the non-breaking workaround for this, is to add middleware logic to the `dispatchNow` method, so the `dispatchSync` method will be able to respect middleware.

I personally prefer removing the `if ($job instanceof ShouldQueen)` condition, but the return value for async jobs is `0`, and not the actual value of the job itself.

This is a bit confusing, you can change the return type of `dispatchSync` method, by simply adding `ShouldQueen` interface.

For example:

```php
dispatchSync(new SyncJob())
// returns actual value

dispatchSync(new NormalJob())
// returns 0
```

**Comment by driesvints** [comment]
`dispatchSync` was specifically designed to not run any middleware. See the original PR by Taylor here: https://github.com/laravel/framework/pull/32559

> Added a new dispatchDirectly (later `dispatchSync`) method to execute a job directly within the command bus without using the sync queue or job middleware (basically the old dispatchNow behavior).

I see the docs don't reflect this well so I'll send in a PR for that. Thanks for noting that here.

> I think running dispatchSync should always return actual value.

No, `dispatchSync` is specifically designed to never return a value. Queued Jobs in all essence should never return values.

**Comment by sharifzadesina** [comment]
> Queued Jobs in all essence should never return values.
@driesvints This I agree, but it returns the actual value when we use `ShouldQueue`. You don't think this is an inconsistency?

**Comment by driesvints** [comment]
@sharifzadesina no. I rather think the other way around shouldn't be happening either. When you use jobs (or a command bus in general), commands/jobs are actions that are executed as a separate process (either sync or async). Any value you need later on in the process needs to be created up front. If you need a value from such a job you're better off to create a non-queueable implementation like a service class.

**Comment by taylorotwell** [comment]
Frankly I think if you aren't planning to EVER queue the job, you shouldn't be using jobs. You are trying to hack some sort of behavior into the framework that wasn't really intended. Jobs are intended to be queued in general. Sometimes they can run synchronously in special circumstances - but that is generally an exceptional case.

If you have a "job" that is NEVER queued, just make it a regular class that you invoke. Or, if you want it to behave like a job, put the ShouldQueue interface on it.

**Comment by sharifzadesina** [comment]
@taylorotwell Yes, I think it is a mistake to use jobs for actions that we never want to be queued.
I think deprecating `dispatchNow` was a good idea and will bring constancy to the framework.
To clarify this more, what do you think about deprecating calling normal classes using `dispatchSync`?
I mean, if the class doesn't implement the `ShouldQueue` interface, we can just throw an error. **(on v9)**
This way, people won't use the job dispatcher for the action classes, and the middleware will always run. plus we will always have a fixed return type.
