### ISSUE TITLE
Laravel Sail Share and URLs

### ISSUE THREAD

**Issue by liamoreilly** [laravel/framework#37773]
### Discussed in https://github.com/laravel/framework/discussions/36942

<div type='discussions-op-text'>

<sup>Originally posted by **liamoreilly** April 11, 2021</sup>
Hi,

When using `sail share` the web pages do not function correctly as the generated URLs for assets do not use the exposed hostname. 

As an example, let's consider a run of `sail share`. This produces the output on the terminal:

```
Thank you for using expose.
Local-URL:		host.docker.internal:80
Dashboard-URL:		http://127.0.0.1:4040
Expose-URL:		http://ykn4nriozw.laravel-sail.site:8080
```

Navigating to http://ykn4nriozw.laravel-sail.site:8080 does yield the website, but with no Javascript nor CSS. An inspection of the page source shows the problem:

```
<link href="http://host.docker.internal/css/app.css" rel="stylesheet">
<script src="http://host.docker.internal/js/app.js" defer></script>
```

The URLs for CSS and Javascript are produced using the Local-URL which is not accessible for those accessing the site with the Expose-URL. 

I would imagine the correct behaviour would be that the generated URLs should be 

```
<link href="http://ykn4nriozw.laravel-sail.site:8080/css/app.css" rel="stylesheet">
<script src="http://ykn4nriozw.laravel-sail.site:8080js/app.js" defer></script>
```

That is, they are built with the Expose-URL.

Is there a flag or setting that enables this behaviour?

It seems the ability to share is more or less not functional with local assets. Anyone viewing the site with the Expose-URL only gets the HTML (and no assets).

The problem is actually a little worse, as all URLs are affected including those used anchor tags. Thus, page navigation also does not function.

Any ideas, hints, or tips are welcome.

Thanks,
Liam</div>

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by liamoreilly** [comment]
Hi @driesvints,

With respect, I disagree that this is a support request.

This occurs with a fresh install: if one creates a fresh install and site with two pages where one provides a hyperlink to the other then this will not function correctly with the current default setup of `sail share`.

If the scenario I describe was a complex setup then I would agree this is more a support request. However, as this happens on a clean install of Laravel and a single a page with a simple link, then I feel this is a bug worth discussing or at least a feature that does not work in its current state.

Best,
Liam

**Comment by lk77** [comment]
Hello,

see https://laravel.com/docs/8.x/sail#sharing-your-site

you need to configure TrutProxies middleware

**Comment by liamoreilly** [comment]
Thanks Mathias!
I am really not sure at all how I missed this
