### ISSUE TITLE
laravel/lumen Migration command issue

### ISSUE THREAD

**Issue by shalinis34** [laravel/framework#37786]
- Laravel Lumen Version: 8
- PHP Version: 8

### Description:
Issue with this file `vendor/illuminate/database/Console/Migrations/MigrateCommand.php`
 `signature` and `description` have type defined as `String`  where other many vendor files don't have type defined explicitly causing issue error

`Type of Illuminate\Database\Console\Migrations\MigrateCommand::$signature must be string (as in class Illuminate\Console\Command) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Illuminate\\Database\\Console\\Migrations\\MigrateCommand::$signature must be string (as in class Illuminate\\Console\\Command) at vendor/illuminate/database/Console/Migrations/MigrateCommand.php:11)`

### Steps To Reproduce:
Just add any command file for lumen 
https://laravel.com/docs/8.x/artisan#command-structure

**Comment by driesvints** [comment]
These files don't have this type implemented: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Console/Migrations/MigrateCommand.php

**Comment by shalinis34** [comment]
This is for lumen application

**Comment by driesvints** [comment]
Lumen uses this command directly
