### ISSUE TITLE
`before_or_equal` fails if reference is null and value in future

### ISSUE THREAD

**Issue by Sysix** [laravel/framework#37787]
- Laravel Version: 8.47.#
- PHP Version: 8.0.*
- Database Driver & Version: Mysql 8 

### Description:

The Validation rule `before_or_equal` is inconsistent when the parameter is null.
When the date is in the past, the validation rule is passing. 
When the date is in the future, it fails.

### Steps To Reproduce:

Here is my TestCode:

```
<?php


namespace Tests\Feature;


use Illuminate\Translation\ArrayLoader;
use Illuminate\Translation\Translator;
use Illuminate\Validation\Validator;
use Tests\TestCase;

class ValidatorBeforeOrEqualTest extends TestCase
{

    public function testProbablyBug()
    {
        $trans = $this->getIlluminateArrayTranslator();

        $rules = [
            'a.*.x' => 'required|date_format:Y-m-d|before_or_equal:a.*.y',
            'a.*.y' => 'nullable|date_format:Y-m-d|after_or_equal:a.*.x'
        ];

        // passes
        $v = new Validator($trans, ['a' => [['x' => '2012-01-15', 'y' => '2012-01-16']]], $rules);
        $this->assertTrue($v->passes());

        // passes
        $v = new Validator($trans, ['a' => [['x' => '2012-01-15', 'y' => null]]], $rules);
        $this->assertTrue($v->passes());
        
        // passes
        $v = new Validator($trans, ['a' => [['x' => '2030-01-15', 'y' => '2030-01-16']]], $rules);
        $this->assertTrue($v->passes());

        // fails
        $v = new Validator($trans, ['a' => [['x' => '2030-01-15', 'y' => null]]], $rules);
        $this->assertTrue($v->passes());
    }

    public function getIlluminateArrayTranslator()
    {
        return new Translator(
            new ArrayLoader, 'en'
        );
    }
}

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
