### ISSUE TITLE
Sqlite composite primary key

### ISSUE THREAD

**Issue by ImSuperlative** [laravel/framework#37788]
- Laravel Version: 8.48.0
- PHP Version: ^7.3
- Database Driver & Version: sqlite

### Description:
Creating composite primary key with sqlite no longer works. Not sure if intended but seems related to this [PR](https://github.com/laravel/framework/pull/37715/files#diff-7cf2f940b724463282b1dbae24464cb3a7c7c0864d40b4c3706eb99f65994d2cL63)

```PHP
 Schema::create(‘models’, function (Blueprint $table) {
    $table->integer('id'); 
    $table->integer('application');
     //… 
     $table->timestamps();
      
      $table->primary(['id', 'application']);
 });
```

Creates a schema without any primary keys. Causing issues with `Model::upsert()`

### Steps To Reproduce:

`DB_CONNECTION=sqlite`  
`php artisan make:model Model -m`
```PHP
public function up()
{
     Schema::create(‘models’, function (Blueprint $table) {
        $table->integer('id'); 
        $table->integer('application');
         $table->timestamps();
          
          $table->primary(['id', 'application']);
     });
 }
```

```PHP
Model::upsert(
    [
        ['id' => 1, 'application' => 1, 'updated_at' => now()->toDateTimeString()],
        ['id' => 2, 'application' => 1, 'updated_at' => now()->toDateTimeString()],
    ],
    ['id', 'application'],
    ['updated_at'],
);
```

**Comment by driesvints** [comment]
Eloquent models don't support composite primary keys.

**Comment by ImSuperlative** [comment]
I’m aware of eloquent not supporting composite keys, it was just an example to recreate. Dropping support for creating composite keys in migrations using sqlite seems unintended.
