### ISSUE TITLE
Not following RFC standards on SMTP EHLO handshake when bootstrapped through artisan console, causing laravel to be blocked by Google's smtp-relay service since January 2021

### ISSUE THREAD

**Issue by SignetPlanet** [laravel/framework#37798]
- Laravel Version: 8.48.0
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:
When using artisan to invoke an email via smtp, Laravel is not passing anything to Swiftmail extension. So Switfmail assigns its default which is [127.0.0.1] and then it uses that in the EHLO handshake which as of January 2021, Google's smtp relay servers will now silently drop those connections. Google announced back in 2010 that they would start dropping these in January 2021 (and they did although I never noticed them send out any further announcements or reminders since). Now any EHLO handshake where the incoming SMTP announces itself as a localhost or some form of that will be silently dropped. This is not an issue when bootstrapped via the HTTP/web as it gets the domain name properly and uss it during the EHLO handshake 

For more details see my longer post on [laracasts](https://laracasts.com/discuss/channels/laravel/laravel-incorrectly-handling-ehlo-for-smtp-from-artisancli-issues-with-gmails-smtp-relay-resolved)

### Steps To Reproduce:
Have an artisan command send an email to a google smtp-relay server (that is obviously already configured properly to allow smtp-relay from IP and/or user) and you will see something like:
```php
Swift_TransportException: Expected response code 250 but got an empty response
```
Initiate that via http/web process and it will work fine. I used wireshark and verified if I initiate email through http/web the EHLO handshake uses my domain name and google gives a connection response to continue. If I initiate through artisan the packets are showing me the EHLO using [127.0.0.1] as the server name and google silently drops the connection.

It doesn't make sense to fix the default in Swiftmail as it doesn't make sense for it to know what our domain would be if Laravel doesn't pass it from the console.

### work around, possible fix
I found a simple work around was in config/mail.php to add to the smtp config the 'local_domain' as that is what Swiftmail is looking for from Laravel. If I set it to a qualified domain name it works and even if I set it to a valet test domain like "blog.test" it works.

Maybe you want to add to the config/mail.php the following (note the local_domain line everything else is the same)
```php
'mailers' => [
        'smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'auth_mode' => null,
            'local_domain' => env('MAIL_EHLO_DOMAIN',parse_url(env('APP_URL'))['host']),
```
This will take the host portion of the APP_URL and use it as that should be in a domain name format, and like I mentioned about it works on *.test domains as well. I only added the MAIL_EHLO_DOMAIN name there so if someone wanted better control between test/stage/prod environments they could specify it separately but it wouldn't need to be there and you could likely use the following as a safe alternative.
```php
'local_domain' => parse_url(env('APP_URL'))['host'],
```

**Comment by driesvints** [comment]
Hey @SignetPlanet. This seems like a very specific issue for this specific use case. You're free to attempt a PR to laravel/laravel if you like. Thanks for the thorough explanation.

**Comment by bhulsman** [comment]
I believe adding `SERVER_NAME=example.com` to the .env file solves this issue.

**Comment by SignetPlanet** [comment]
Hi @driesvints,

I would argue this isn't a a specific use case as an SMTP standard should be followed regardless of how many providers ignore them. As of 2020 over 6 million businesses use Google Workspace (formerly GSuite) and Google provides each of those businesses access to their smtp-relay services which gives each of them 10,000 free emails per day.

I've seen comments of others struggling with what I can see was exactly this issue but as no one understood what was happening they are primarily being told to use a paid service like Mailgun or Postmark as that is more reliable but I would argue if Laravel followed SMTP standards they wouldn't have issues. I've also noticed google's smtp-relay service is faster and more reliable than either of those services as well.

Hi @bhulsman,
Adding SERVER_NAME to the .env file does work but it changes the name globally reglardless if you connect via artisan/queue or web interfaces. I fear that would affect multi-tenent sites that use multiple domains or domains with wildcards. Perhaps I'm wrong on that as I don't have any of those anymore to test but that is my hunch.

I guess you could put it in a boot() section of the AppServiceProvider() and make it conditional of running in a console. Something like:
```php
if (app()->runningInConsole()) {
    $_SERVER["SERVER_NAME"] = 'domain';
}
```
**As a console would be less likely to mess with multitenant sites, but again it comes back to why should someone be required to  add code to make Laravel follow SMTP standards in the first place. **

I do see that putting 'local_domain' in the config/mail.php mailers -> smtp section will only be passed to Swiftmail and the domain assigned there wouldn't affect multi-tenent sites so I still think that is the better option.

**Comment by driesvints** [comment]
@SignetPlanet it's best that you attempt either a PR to the docs or the skeleton
