### ISSUE TITLE
retryUntill doesn't work like in documentation

### ISSUE THREAD

**Issue by glamorous** [laravel/framework#37804]
- Laravel Version: 7.x, 8.x
- PHP Version: every
- Database Driver & Version: /

### Description:
The documentation in 7.x and 8.x are talking about a returning a DateTime interface and have an example like this.

```
/**
 * Determine the time at which the job should timeout.
 *
 * @return \DateTime
 */
public function retryUntil()
{
    return now()->addSeconds(5);
}
```

But the Job interface is talking about returning an int or null. 

### Steps To Reproduce:

Copied from vendor/laravel/framework/src/Illuminate/Queue/Worker.php:473

```
$retryUntil = $job->retryUntil();

if ($retryUntil && Carbon::now()->getTimestamp() <= $retryUntil) {
    return;
}
```

Having a DateTime interface here is causing a Notice in the code and it would skip this and stop after first try instead of retrying itself.

So 2 possible solutions for this "bug":

- It's a bug and dateTime interface should be supported, as well as an integer (I can create a PR for that)
- It's not a bug, the documentation is wrong (I can create a PR for that)

**Comment by driesvints** [comment]
You're confusing the Job contract (which is for driver based queued jobs) with an actual app job. This contract isn't meant to be implemented on an application Job. The docs aren't wrong and the Job contract is never referenced in it.

**Comment by glamorous** [comment]
Why are you closing this? We have seen this going wrong in our application. The queued job has a function retryUntill() which returns a Carbon date (like in the documentation). But the code is copied is form the queued worker and we saw indeed that after fist try the maxAttemptsException was thrown. So please look into this because just closing it doesn't make any sense.

**Comment by driesvints** [comment]
@glamorous I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by glamorous** [comment]
The documentation link: https://laravel.com/docs/8.x/queues#time-based-attempts (DateTime reference)

The code in vendor/laravel/framework/src/Illuminate/Queue/Worker.php

```
/**
     * Mark the given job as failed if it has exceeded the maximum allowed attempts.
     *
     * This will likely be because the job previously exceeded a timeout.
     *
     * @param  string  $connectionName
     * @param  \Illuminate\Contracts\Queue\Job  $job
     * @param  int  $maxTries
     * @return void
     *
     * @throws \Throwable
     */
    protected function markJobAsFailedIfAlreadyExceedsMaxAttempts($connectionName, $job, $maxTries)
    {
        $maxTries = ! is_null($job->maxTries()) ? $job->maxTries() : $maxTries;

        $retryUntil = $job->retryUntil();

        if ($retryUntil && Carbon::now()->getTimestamp() <= $retryUntil) {
            return;
        }

        if (! $retryUntil && ($maxTries === 0 || $job->attempts() <= $maxTries)) {
            return;
        }

        $this->failJob($job, $e = $this->maxAttemptsExceededException($job));

        throw $e;
    }
```

The problem is that we're checking an integer from `->getTimestamp()` against the return of the function of `retryUntil()` (in the code that is hinted to be `int|null` but in the documentation (see link above) it returns a Carbon object.

If you still want to test it, you can do it with this in a sandbox:

```
$dateTimeInterfaceObject = new DateTime();
$retryUntil = new DateTime('2022-01-01');

if ($retryUntil && $dateTimeInterfaceObject->getTimestamp() <= $retryUntil) {
            echo "timestamp is before give date";
}
```

The result is: `Notice:  Object of class DateTime could not be converted to int` and it would not return early so the job would be marked as failed.

If it's still unclear for your after above examples, I will make a project with some examples, but I think its easier is I just create a PR with the needed change to support both options.

**Comment by driesvints** [comment]
Yes, please provide a project that reproduces this.

**Comment by glamorous** [comment]
Hi Dries, I have to apologize. Setup the repository and tried a couple of scenario's but could replicate it anymore with a simple example. Will look into you application code again and figure out why it wasn't working in our case because my used example now is working like expected. Even with returning an integer instead of the required DateTime (regarding the docs)
