### ISSUE TITLE
Swapping implementations of core contracts

### ISSUE THREAD

**Issue by jrmajor** [laravel/framework#37812]
- Laravel Version: 8.48.1
- PHP Version: 8.0.7

### Introduction

Consider the following classes:

```php
interface ComponentContract { }
class LaravelComponent implements ComponentContract { }
class UserlandComponent implements ComponentContract { }
```

Laravel components are registered in service container by simple string keys (`app('component')` returns instance of `LaravelComponent`). This happens in `ComponentServiceProvider`:

```php
$app->singleton('component', fn () => new LaravelComponent());
```

Both `ComponentContract` and `LaravelComponent` are then registered as aliases to `component`. This happens in `Illuminate\Foundation\Application::registerCoreContainerAliases()`:

```php
$app->alias('component', ComponentContract::class);
$app->alias('component', LaravelComponent::class);
```

### Description

I've run into this problem when developing a package which replaces the default Laravel translator with a custom one (https://github.com/jrmajor/laravel-fluent).

Using the example from the introduction, I want to replace `LaravelComponent` with `UserlandComponent` in my application. It should work like this:

```php
app('component')              instanceof UserlandComponent::class;
app(ComponentContract::class) instanceof UserlandComponent::class;
app(LaravelComponent::class)  instanceof LaravelComponent::class;
app(UserlandComponent::class) instanceof UserlandComponent::class;
````

I've managed to accomplish this by registering my component like that:

```php
$laravelComponent = app(LaravelComponent::class);

$app->singleton(UserlandComponent::class, fn () => new UserlandComponent());
$app->bind(ComponentContract::class, UserlandComponent::class);
$app->alias(ComponentContract::class, 'component');
$app->instance(LaravelComponent::class, $laravelComponent);
```

But this can’t be done in `register()`, because `LaravelComponent` is not registered yet. It works only when it’s done in `boot()`.

To make it work in `register()` method, I would have to copy all the logic for building `LaravelComponent` from Laravel’s service provider and put it into the last line of the above code.

Alternatively, I can register it like it’s registered by Laravel:

```php
$app->singleton('component', fn () => new UserlandComponent());
$app->alias('component', UserlandComponent::class);
```

But it makes it impossible to resolve `LaravelComponent` from service container (it would always return `UserlandComponent`), which would break dependency injection for a class with type hinted `LaravelComponent`

### Solution

If Laravel registered it’s core services like this:

```php
$app->singleton(LaravelComponent::class, fn () => new LaravelComponent());
$app->bind(ComponentContract::class, LaravelComponent::class);
$app->alias(ComponentContract::class, 'component');
```

These two lines in service provider would be enough to make everything work as expected:

```php
$app->singleton(UserlandComponent::class, fn () => new UserlandComponent());
$app->bind(ComponentContract::class, UserlandComponent::class);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jrmajor** [comment]
I’ve moved it to discussions (#37816).
