### ISSUE TITLE
Swiftmailer error

### ISSUE THREAD

**Issue by JustJoni** [laravel/framework#37813]
- Laravel Version: 6.0.4 
- PHP Version: 7.3.11 
- Database Driver & Version: 10.3.18-MariaDB

### Description:
I have been sending emails to users with laravel (I use jobs) for over a year now. All this time there was no such problem. But yesterday emails were not sent and an error appeared in the Laravel logs: production.ERROR: fwrite (): SSL: Broken pipe {"exception": "[object] (ErrorException (code: 0): fwrite (): SSL: Broken pipe at /srv/www/site.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:231) There were no code updates before this. How can I fix this?

### Here is my config data:
config/mail
```
<?php
return [
    'driver' => env('MAIL_DRIVER', 'smtp'),
    'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
    'port' => env('MAIL_PORT', 587),
    'from' => [
        'address' => 'my_mail@yandex.ru',
        'name' => 'MyName',
    ],
    'encryption' => env('MAIL_ENCRYPTION', 'ssl'),
    'username' => env('MAIL_USERNAME'),
    'password' => env('MAIL_PASSWORD'),
    'sendmail' => '/usr/sbin/sendmail -bs',
];
```
config/services
```
<?php

return [

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
    ],

    'ses' => [
        'key' => env('SES_KEY'),
        'secret' => env('SES_SECRET'),
        'region' => 'us-east-1',
    ],

    'sparkpost' => [
        'secret' => env('SPARKPOST_SECRET'),
    ],

    'stripe' => [
        'model' => Inform\User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],
];
```
Sending letter
```
Mail::to($email)
                ->bcc('email@my-domen.ru')
                ->send(new EveryDayReport($subject, $viewData));
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
