### ISSUE TITLE
How to generate "make:model -a" with the correct directory structure?

### ISSUE THREAD

**Issue by amberlex78** [laravel/framework#37814]
- Laravel Version: 8.48.1
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 8.0.25

### Description:

Bug or needs improvement when `make:model` with `-a` parameter?

### Steps To Reproduce:

Who will explain to me where is the logic?

**First**

a)

```
$ php artisan make:model Blog/Category -r
Model created successfully.
Controller created successfully.
```

I am getting the following files:

```
Models/Blog/Category.php                    // It's ok!
app/Http/Controllers/CategoryController.php // It's not ok!
```

In case `php artisan make:model Blog/Category -r` and if I need create `php artisan make:model Shop/Category -r` I will get the error: `Controller already exists!` The model will be created correctly `Models/Shop/Category.php`

I would like to see `Http/Controllers/Blog/CategoryController.php` and `Http/Controllers/Shop/CategoryController.php`

b)

```
$ php artisan make:controller Blog/Category -r
Controller created successfully.
```

I am getting the following:

```
Http/Controllers/Blog/Category.php
```

I would like to see `Http/Controllers/Blog/CategoryController.php`

Do we need a suffix  `Controller` or not if I using `make:controller`? 

To get a suffix - you need to write it explicitly `php artisan make:controller Blog/CategoryController -r`

**Second**

The same situation will be with migrations.

```
$ php artisan make:model Blog/Category -m
Model created successfully.
Created Migration: 2021_06_25_040809_create_categories_table
```

I would like to see `2021_06_25_040809_create_blog_categories_table`

```
$ php artisan make:model Shop/Category -m
Model created successfully.

InvalidArgumentException 
A CreateCategoriesTable class already exists.
```

If we use two parameters `-rm` at once, then we will not even get to the error with migrations due to a controller error.

**Third**

It turns out in this case we can't create controllers and migrations `-rm`. Let's try a flag `-f` for the factory, everything is logical here.

```
$ php artisan make:model Blog/Category -f
Model created successfully.
Factory created successfully.

$ php artisan make:model Shop/Category -f
Model created successfully.
Factory created successfully.
```

```
database/factories/Blog/CategoryFactory.php  // It's ok!
database/factories/Shop/CategoryFactory.php  // It's ok!
```

**Fourth**

Let's try seeder and getting a warning

```
$ php artisan make:model Blog/Category -s
Model created successfully.
Seeder created successfully.

$ php artisan make:model Shop/Category -s
Model created successfully.
Seeder already exists!
```

I am getting the following:

```
database/seeders/CategorySeeder.php
```

I would like to see something like this `database/seeders/Blog/CategorySeeder.php`

Further more interesting:

```
$ php artisan make:seeder Blog/Category
Seeder created successfully.

$ php artisan make:seeder Shop/Category
Seeder created successfully.
```

I am getting the following:

```
database/seeders/Blog/Category.php
database/seeders/Shop/Category.php
```

But there is generally strange behavior:

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class Blog/Category extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }
}
```

If you create via `make: seeder`, it is fine, but as in the case with the controller, you need to add the suffix `Seeder`

```
$ php artisan make:seeder BlogCategory
Seeder created successfully.

$ php artisan make:seeder BlogCategorySeeder
Seeder created successfully.
```

```
database/seeders/BlogCategory.php
database/seeders/BlogCategorySeeder.php
```

**What do we have for such a case?**

I need to do this can be done manually in this order:

```
$ php artisan make:model Blog/Category -f
Model created successfully.
Factory created successfully.

$ php artisan make:model Shop/Category -f
Model created successfully.
Factory created successfully.

$ php artisan make:seeder BlogCategorySeeder
Seeder created successfully.

$ php artisan make:seeder ShopCategorySeeder
Seeder created successfully.

$ php artisan make:migration CreateBlogCategoriesTable
Created Migration: 2021_06_25_043557_create_blog_categories_table

$ php artisan make:migration CreateShopCategoriesTable
Created Migration: 2021_06_25_043606_create_shop_categories_table

$ php artisan make:controller Blog/Category -r --model=Blog/Category
Controller created successfully.

$ php artisan make:controller Shop/Category -r --model=Shop/Category
Controller created successfully.
```

**Total**

I think it would be logical to create directories for the namespace when creating

```
php artisan make:model Blog/Category -a
```

and get something like this structure

```
Model created successfully:      app/Models/Blog/Category.php
Factory created successfully:    database/factories/Blog/CategoryFactory.php
Created Migration:               2021_06_25_055915_create_blog_categories_table (!)
Seeder created successfully:     database/seeders/BlogCategorySeeder.php (!)
                                 or database/seeders/Blog/CategorySeeder.php
Controller created successfully: app/Http/Controllers/Blog/CategoryController.php (!)
```

And added to the model property `protected $table = 'blog_categories;`

There will be more than one controller in the `Shop` or `Blog` directory - this would better separate the structure and tables with prefix `shop_` or `blog_`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by amberlex78** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

I don't know where to suggest an improvement. This is either a mistake or a flaw.
What I wanted from `php artisan make: model Blog/Category -a` is detailed here. 
You can do it step by step in another way, but what's the point in the `make:model` command with the `-а` parameter if it does not work quite correctly?
Maybe you should pay attention to this and fix/modify it in the next versions of Laravel?

**Comment by ammannbe** [comment]
I have the same problem and think this worked in older laravel versions (8.x).

I also think this is a bug, because in my eyes the behaviour in the namespace resolution of
`make:model Blog/Category -a`
should be the same as
`make:controller Blog/Category`
which is not the case.
