### ISSUE TITLE
Maintenance mode in Laravel Vapor fails to pass requests to the framework.

### ISSUE THREAD

**Issue by KieronWiltshire** [laravel/framework#37825]
- Laravel Version: 8.0.0
- PHP Version: 8.0.0

### Description:
Laravel Vapor always provides a default template when placed into maintenance mode. This means that [this if](https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Console/stubs/maintenance-mode.stub#L11-L14) statement always returns false. This means that Vapor fails to recognise the "except" routes inside of the [CheckForMaintenanceMode](https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php#L24) middleware.

It should also be worth noting that enabling maintenance mode on Laravel Vapor does not support passing through a bypass secret or any other variables in the Laravel Vapor GUI for allowing a user to bypass the maintenance mode as described [here](https://laravel.com/docs/8.x/configuration#bypassing-maintenance-mode).

### Steps To Reproduce:

1. Create a Laravel Vapor project.
2. Add some test routes which return dummy data.
3. Add those routes to the `except` variable in the `CheckForMaintenanceMode` middleware.
4. Deploy the application.
5. Place the deployment into maintenance mode and attempt the routes to be ignored by the maintenance mode.
6. Watch it always return a 503.

**Comment by driesvints** [comment]
Hey @KieronWiltshire. It's best that you send a ticket to Vapor support about this. Thanks
