### ISSUE TITLE
Postgres String Primary Key Migration Fail

### ISSUE THREAD

**Issue by ahawlitschek** [laravel/framework#37820]
- Laravel Version: 8.48.1 
- PHP Version: 8.0.6 
- Database Driver & Version: postgres (PostgreSQL) 13.2 with PostGIS 3

### Description:
After Updating to the newest Laravel Version (previously 8.47.0), the default Session migration from Laravel Jetstream causes the following exception:

` SQLSTATE[42P16]: Invalid table definition: 7 ERROR:  multiple primary keys for table "sessions" are not allowed (SQL: alter table "sessions" add primary key ("id"))`

Other migrations with integer primary keys are fully fine. 
It seems like the problem is caused by the string primary key.
Here is the migration from jetstream:

```php
Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            $table->foreignId('user_id')->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->text('payload');
            $table->integer('last_activity')->index();
        });
```

We tried this on several machines from different people working on the project. 

### Steps To Reproduce:

We tried to reproduce this issue with a completely new laravel jetstream project. But the error does not appear.
I will try to create a demo project the next days

**Comment by driesvints** [comment]
Most likely caused by https://github.com/laravel/framework/pull/37715 as well.

**Comment by khalilst** [comment]
@driesvints I have created a project connected to `Postgres.
And put the above migration there.
It was working without any problem!!!

My guess there is something missing in the migration code like this:
```php
Schema::create('sessions', function (Blueprint $table) {
            $table->string('id')->primary();
            //...
            $table->primary('id);
        });
```

And the error was obvious here and not related to  #37715 .

**Comment by driesvints** [comment]
@khalilst how do you explain this working in v8.47.0 then? It broke after v8.48.0 and that PR is the only database related change.

**Comment by khalilst** [comment]
@driesvints, brief answer: probably wrong bug report.

For more clarification:
1. Install a fresh Laravel project
2. Create a migration with the following code.
3. Connect to `Postgres` and migrate.
4. It was working without any error.

@ahawlitschek  Please provide steps to reproduce to help me to fix it, no need for the demo project.

**Comment by ahawlitschek** [comment]
So, I created another a fresh instance and tested each other dependency from our project one by one until I have found the dependency that need to be added in order to achieve this behaviour. 

Add 
`"mstaack/laravel-postgis": "^5.2",` to the dependencies in composer.json and it works with laravel 8.47.0, but not with the new framework.

**Comment by driesvints** [comment]
@khalilst the OP's migration is the base sessions table that ships with Laravel: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Session/Console/stubs/database.stub

**Comment by khalilst** [comment]
@driesvints I have tried it in Laravel 8.48.1 and it was OK, 

@ahawlitschek Just let me fix it.

**Comment by studnitz** [comment]
There is also an issue and PR at the `bosnadev/database` repository, which is what `mstaack/laravel-postgis` depends on.

https://github.com/bosnadev/database/issues/48
https://github.com/bosnadev/database/pull/49

**Comment by driesvints** [comment]
Thanks @studnitz. I've sent in a PR to revert all of this: https://github.com/laravel/framework/pull/37826

**Comment by khalilst** [comment]
As @studnitz said:
This bug related to the third-party package overriding the `Blueprint` and there is a PR to fix this problem in that package.

The package name: `bosnadev/database`
File path: `Bosnadev/Database/Schema/Blueprint.php`
It is required by ` mstaack/laravel-postgis`.

I think this PR #37826 is not fair because of a third-party package.
