### ISSUE TITLE
Undefined array key "column"

### ISSUE THREAD

**Issue by michele-grifa** [laravel/framework#37827]
- Laravel Version: 8.48.1
- PHP Version: 8.0
- Database Driver & Version: SQL Server v15.00.4043

### Description:
Today i updated Laravel from 8.45.1 to 8.48.1 and when i try to use paginate method from Livewire the following error popped out
```php
Undefined array key "column"

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php:220
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
