### ISSUE TITLE
Blade Engine: Using preg_match in @if statement failes depending on the regular expression

### ISSUE THREAD

**Issue by lsblsb** [laravel/framework#37831]
- Laravel Version: 8.4.0 (using sail)
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.0.25

### Description:

The Following code inside a blade component failes (example):

```
@if(preg_match('#disableOthers\(([^\)]+)\)#', $onclick, $matches))
  TEST
@endif
```
Error:
```
Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}
resources/views/components/form/input.blade.php:1

ParseError
syntax error, unexpected token ":" (View: /var/www/html/resources/views/components/form/input.blade.php) 
```

This on the other hand works:
```
@if(preg_match('#teststring#', $onclick, $matches))
  TEST
@endif
```

### Steps To Reproduce:

just create a blade component, add test the code.
The $onclick variable should exist.

**Comment by driesvints** [comment]
Assign the statement to a variable and use the variable in the if statement.

**Comment by lsblsb** [comment]
@driesvints I tried that, and got another error. But tried it again now, and it was another cause.

This is a fix for that **bug**:

```
@php
$onclick = "testme";
$regexp = '#disableOthers\(([^\)]+)\)#';
@endphp

@if(preg_match($regexp, $onclick, $matches))
  TEST
@endif
```

**Comment by driesvints** [comment]
```blade
<?php $foo = preg_match('#teststring#', $onclick, $matches); ?>

@if($foo)
  TEST
@endif
```

**Comment by lsblsb** [comment]
@driesvints
`'#teststring#'` also works inline (directly inside a preg_match inside the @if statement) - and certain other regular expressions too.

this is one specific expression, that does NOT work, when used inline:
`'#disableOthers\(([^\)]+)\)#'`
