### ISSUE TITLE
Collection::mergeRecursive appends a *items element

### ISSUE THREAD

**Issue by xstat** [laravel/framework#37834]
- Laravel Version: 8.46.0
- PHP Version: 7.3.28-2+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version:

### Description:

In some cases Collection::mergeRecursive appends an *items key.

### Steps To Reproduce:

`$collection1 = collect([
    'level_1' => collect([
        [
            'id' => 1,
            'name' => 'One',
        ],[
            'id' => 2,
            'name' => 'Two',
        ],
    ]),
]);
$collection2 = collect([
    'level_1' => collect([
        [
            'id' => 3,
            'name' => 'Three',
        ],[
            'id' => 4,
            'name' => 'Four',
        ]
    ])
]);
return $collection1->mergeRecursive($collection2)->first();
`

Couldn't get the code properly formatted, I apologize.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JonErickson** [comment]
@xstat did you find a resolution? Experiencing this as well.

**Comment by sanneterpstra** [comment]
@xstat @JonErickson @driesvints Experiencing the same.. Did you guys find a solution?
