### ISSUE TITLE
Cannot update mulltiple "keys" of a jsonb column in PostgresSQL

### ISSUE THREAD

**Issue by sai-ekkaldevi** [laravel/framework#37836]
- Laravel Version: 8.47.0
- PHP Version: 8.0.3
- Database Driver & Version: PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

### Description:
When trying to update multiple keys of a jsonb columns in PostgresSQL driver, it fails and generates incorrect SQL query.

**Schema**
```php
Schema::create('specs', function (Blueprint $table) {
    $table->id();
    $table->jsonb('options')->nullable();
});
```

The values of `options` columns will have multiple keys for example: `php`, `laravel`, `db`
```json
{"php": "7.0.8", "laravel": "8.47.0", "db": "postgres 13.3"}
```

If we run below `update` statement with given values, it fails and gives following exception
```php
$values = [
   "options->php" => "8.1.0",
   "options->laravel" => "master",
   "options->db" => "14",
];
Specs::where('id', 1)->update($values);
```

It gives following error
```log
SQLSTATE[42601]: Syntax error: 7 ERROR:  multiple assignments to same column "options" (SQL: update "specs" set "options" = jsonb_set("options"::jsonb, '{"php"}', "8.1.0"), "options" = jsonb_set("options"::jsonb, '{"laravel"}', "master"), "options" = jsonb_set("options"::jsonb, '{"db"}', "14"), where "id" = 1)
```

The correct SQL query should be either of following
```sql
-- Recursive
update "specs"
set "options" = jsonb_set(
		jsonb_set(
			jsonb_set(
				"options" :: jsonb,
				'{"db"}',
				"14"
			),
			'{"laravel"}',
			"master"
		),
		'{"php"}',
		"8.1.0"
	),
where "id" = 1;

-- Merge
update "specs"
set "options" = options || '{"php": "8.1.0", "laravel": "master", "db": "14"}',
where "id" = 1
```

### Steps To Reproduce:
Use above schema migration & update statement

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
