### ISSUE TITLE
JsonResource class - method toArray(), $request variable is not typed 

### ISSUE THREAD

**Issue by codebjorn** [laravel/framework#37848]
- Laravel Version: 8.45.1
- PHP Version: 8.0.5

### Description:
https://github.com/laravel/framework/blob/3a8082e9403d1dc64da912900593e0bcea7bdf22/src/Illuminate/Http/Resources/Json/JsonResource.php#L113

The issue itself is that `JsonResource` in method `toArray()`, `$request` variable is not typed. 
This causes issues on overwriting this method, and on keeping strict typing on the project.  

The suggestion is to add type hinting to this types of methods:

```PHP
public function toArray(Request $request) 
```

**Comment by driesvints** [comment]
This isn't an issue in Laravel. You can't type a method if the parent doesn't implement it as you say.

**Comment by codebjorn** [comment]
> This isn't an issue in Laravel. You can't type a method if the parent doesn't implement it as you say.

Okay, so why not implement in framework type hinting for return methods like this? 
Because I know that the LTS version now is Laravel 6.0, and Laravel 6.0 requires PHP 7.2 that has the possibility to add type hinting for parameters in functions/methods type of object or class name.
