### ISSUE TITLE
Seems There is a Bug in Route::apiResources

### ISSUE THREAD

**Issue by saadabdurrazaq** [laravel/framework#37841]
I use `Route::apiResources(['staff-management' => StaffController::class]);` along with anoher route API inside middleware below.
 
`Route::group(['prefix' => 'staff', 'middleware' => ['auth:staff-api', 'scopes:staff']], function () {
    Route::get('staff-management/search/{keyword}', [StaffController::class, 'searchStaff']);
    Route::get('staff-management/download-pdf', [StaffController::class, 'downloadPDF']);
});`

The result is, `download-pdf` route getting blank when I access it using Postman. So, I decide to remove `Route::apiResources` and now, it's working. Try to fix this problem. I think this problem is considered to be bug. 

For more clear, you can refer to https://stackoverflow.com/questions/68147080/laravel-api-getting-blank-response

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by saadabdurrazaq** [comment]
I report the bug, not asking the solution. I just tell you that ```Route::apiResources``` considered to be bug related to this problem. The problem itself has been solved by me. So, I am here not to ask to the solution. I just tell the bug. That's it!
