### ISSUE TITLE
Can't add tinyText() on migration

### ISSUE THREAD

**Issue by tfevan** [laravel/framework#37843]
- Laravel Version: 8.26.1
- PHP Version: 8.0.6
- Database Driver & Version: MariaDB 10.4.19

### Description:
I can't add [tinyText()](https://laravel.com/docs/8.x/migrations#column-method-tinyText), I got `Method Illuminate\Database\Schema\Blueprint::tinyText does not exist` :
```
public function up()
{
  Schema::create('posts', function (Blueprint $table) {
      $table->id();
      $table->tinytext('notes');
  });
}
```
Error : 

>Migrating: 2021_06_25_195747_create_posts_table
>BadMethodCallException
>Method Illuminate\Database\Schema\Blueprint::tinyText does not exist.
>  at C:\Users\evan\Desktop\url\url\vendor\laravel\framework\src\Illuminate\Macro
able\Traits\Macroable.php:103
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tfevan** [comment]
@driesvints I report the bug, it looks like a bug for me. Would you please check. The `tinyText()` method works on my Laravel 5.8, but I got the error on Laravel 8
