### ISSUE TITLE
Redis Cache Tags Breaks With Read Only Replica

### ISSUE THREAD

**Issue by lonnylot** [laravel/framework#37849]
- Laravel Version: 6.20.17
- PHP Version: 7.3.27
- Database Driver & Version: Redis 5.0.5

### Description:

If you use Cache Tags and have a master/replica setup using Redis it will fail with `READONLY You can't write against a read only replica.` when you try to get a key that is not in the cache yet.

### Steps To Reproduce:

app/config/cache.php:

```php
<?php

'stores' => [
        'redis' => [
            'client' => 'predis',
            'driver' => 'redis', 
            'connection' => 'default',
        ],

        'redis_read_only' => [
            'client' => 'predis',
            'driver' => 'redis', 
            'connection' => 'redis_read_only',
        ],

    ],
```

General code:

```php
Cache::store('redis_read_only')->tags(['some_tag'])->get('my_key', function() {
  return Cache::store('redis')->tags(['some_tag'])->put('my_key', 'value');
});
```

On initial request the `get` causes a failure because we try to set the [tagIds](https://github.com/laravel/framework/blob/v6.20.17/src/Illuminate/Cache/TagSet.php#L54) since they don't exist (stack trace below).

I would think that we don't want to write when doing a read command.

Stack trace:
```
{
    "exception": {
        "class": "RedisException",
        "message": "READONLY You can't write against a read only replica.",
        "code": 0,
        "file": "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116",
        "trace": [
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:519",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:85",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:171",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TagSet.php:54",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TagSet.php:87",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TagSet.php:76",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TagSet.php:66",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TaggedCache.php:102",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/TaggedCache.php:91",
            "/var/www/html/gdm/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:97",
            ...snip
        ]
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by lonnylot** [comment]
Hi @driesvints, yes I will check those out, but could you explain what you mean by 'identify this as a bug'?

The framework tries to write on a read command and it breaks if you have a master/replica setup. What else is needed for me to 'identify this as a bug'?

**Comment by lonnylot** [comment]
I'm not sure what you wanted so I just created PR #37851 37851
