### ISSUE TITLE
Refresh does not refresh pivots

### ISSUE THREAD

**Issue by jaulz** [laravel/framework#37862]
- Laravel Version: #.#.#
- PHP Version: 8.48
- Database Driver & Version:

### Description:

Currently, when you call `refresh` on an instance it doesn't reload morph relations that extend `MorphPivot` class, e.g.:
```php
    public function latestComment()
    {
        return $this->morphOne(Comment::class, 'commentable')->ofMany(['id' => 'max']);
    }
```

I already created https://github.com/laravel/framework/pull/37819 but since it was closed I think this issue should anyway keep track of the problem.

### Steps To Reproduce:

You can clone the corresponding branch of the PR:
https://github.com/jaulz/framework/tree/fix/refresh-all-relations

I removed the potential solution so you should be able to reproduce the issue by running the `EloquentModelRefreshTest` test:
```sh
vendor/bin/phpunit --filter Refresh
```

**Comment by driesvints** [comment]
Since Taylor closed your fix we have no plans to revisit this atm.

**Comment by jaulz** [comment]
@driesvints I'm not sure if he closed it because of the suggested solution or because of the issue itself. I understood that the suggested solution is a breaking change but I don't understand why fixing this issue would be a breaking change?
