### ISSUE TITLE
Design or Bug? When I run php artisan:make test --unit the TestCase comes from `use PHPUnit\Framework\TestCase;`

### ISSUE THREAD

**Issue by alnutile** [laravel/framework#37861]
- Laravel Version: 8.48.2
- PHP Version: 8.0.5

### Description:
When I run `php artisan make:test FooTest --unit` I expect the test to be able to use Facades and other features.
But I was getting a lot of errors

  * Target class [config] does not exist.
  * A facade root has not been set

etc.

Once I changed the `TestCase` import from 

```
use PHPUnit\Framework\TestCase;
```

to 

```
use Tests\TestCase;
```

It all worked as expected. Maybe this is "correct" in that "Unit" is trying to really focus at that level?

### Steps To Reproduce:

Run the command 

```
php artisan make:test FooTest --unit
```
Open the file

add a test, for example:

```
    use RefreshDatabase;

    public function test_new_user()
    {
        $user = User::factory()->create();

        $this->assertNotNUll($user);
    }
```

See an error:

```
  Tests\Unit\UserTest > new user
   InvalidArgumentException 

  Unknown formatter "name"

  at vendor/fakerphp/faker/src/Faker/Generator.php:300
    296▕                 return $this->formatters[$formatter];
    297▕             }
    298▕         }
    299▕ 
    300▕         throw new \InvalidArgumentException(sprintf('Unknown formatter "%s"', $formatter));
    301▕     }
    302▕ 
    303▕     /**
    304▕      * Replaces tokens ('{{ tokenName }}') with the result from the token method call

      +2 vendor frames 
  3   database/factories/UserFactory.php:28
      Faker\Generator::__call()

      +7 vendor frames 
  11  tests/Unit/UserTest.php:17
      Illuminate\Database\Eloquent\Factories\Factory::create()
```

Change `use PHPUnit\Framework\TestCase;` to `use Tests\TestCase;` and it works.

**Comment by crynobone** [comment]
That's an expected behavior, use feature tests if you need access to the Framework.

**Comment by alnutile** [comment]
@crynobone thanks. I see it now in the docs.
