### ISSUE TITLE
Collection method unique with boolean values has a bag

### ISSUE THREAD

**Issue by sidigi** [laravel/framework#37872]
- Laravel Version: 8.48.1
- PHP Version: 8.0.7
- Database Driver & Version:

### Steps To Reproduce:

```dd(collect(true,false)->unique())```

```Illuminate\Support\Collection {#3722
     all: [
       true,
     ],
   }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Nacoma** [comment]
@sidigi 

```php
Psy Shell v0.10.4 (PHP 7.4.20 — cli) by Justin Hileman
>>> collect(true, false);
=> Illuminate\Support\Collection {#7332
     all: [
       true,
     ],
   }
>>> collect([true, false]);
=> Illuminate\Support\Collection {#7335
     all: [
       true,
       false,
     ],
   }
>>> 

```
