### ISSUE TITLE
Laravel multilang fallback language doesn't work as intended

### ISSUE THREAD

**Issue by cioroianudenis** [laravel/framework#37876]
- Laravel Version: 7.x
- PHP Version: 7.4.16
- Database Driver & Version: Not required

### Description:
So I have an app that has 3 lang files in resources/lang (ro.json, en.json, de.json).
The first two lang files (ro.json, en.json) both have all the possible keys the app is using, but the `de.json` file has 0 keys.
Laravel app is configured to use `en` as the fallback_language in app/config.php .
I have the following lang key: `user_not_found` which exists in `en.json` but not in `de.json`. As per the documentation you would expect that if the current language (which is `de`) doesn't have the key, it should next look into `en.json` file for that key. But it doesn't, it immediately looks inside "/resources/lang/de/user_not_found.php" which doesn't exist because that's the key inside `en.json` file, not a file inside `de` folder(which is non-existant).

The following code is responsible for this behaviour from `Translator.php` class:

```php
public function get($key, array $replace = [], $locale = null, $fallback = true)
    {
        $locale = $locale ?: $this->locale;

        // For JSON translations, there is only one file per locale, so we will simply load
        // that file and then we will be ready to check the array for the key. These are
        // only one level deep so we do not need to do any fancy searching through it.
        $this->load('*', '*', $locale);

        $line = $this->loaded['*']['*'][$locale][$key] ?? null;

        // If we can't find a translation for the JSON key, we will attempt to translate it
        // using the typical translation file. This way developers can always just use a
        // helper such as __ instead of having to pick between trans or __ with views.
        if (! isset($line)) {
            [$namespace, $group, $item] = $this->parseKey($key);

            // Here we will get the locale that should be used for the language line. If one
            // was not passed, we will use the default locales which was given to us when
            // the translator was instantiated. Then, we can load the lines and return.
            $locales = $fallback ? $this->localeArray($locale) : [$locale];

            foreach ($locales as $locale) {
                if (! is_null($line = $this->getLine(
                    $namespace, $group, $locale, $item, $replace
                ))) {
                    return $line ?? $key;
                }
            }
        }

        // If the line doesn't exist, we will return back the key which was requested as
        // that will be quick to spot in the UI if language keys are wrong or missing
        // from the application's language files. Otherwise we can return the line.
        return $this->makeReplacements($line ?: $key, $replace);
    }
```

This here:
```
$this->load('*', '*', $locale);
$line = $this->loaded['*']['*'][$locale][$key] ?? null;
```
only looks in the first locale `de` but not in the fallback locale `en`.
I think after the first lookup, there should be this code:
```
if (! isset($line)) {
$this->load('*', '*', $this->fallback);
$line = $this->loaded['*']['*'][$this->fallback][$key] ?? null;
}
```

Thank you!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by cioroianudenis** [comment]
@driesvints Hello, I just tried the same thing on a Laravel 8.16.1 installation and it's the same bug.

**Comment by driesvints** [comment]
@cioroianudenis I don't think that's a bug. 

Please try a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

There's also been a few issues opened about this in the past so maybe try search the issue tracker as well.

**Comment by cioroianudenis** [comment]
@driesvints can you please point me into the right direction? I have search for a couple of hours, but nothing about this particular case came up.

**Comment by driesvints** [comment]
I'd have to do the same search as you. Please ask on a support channel.

**Comment by lk77** [comment]
It works as intended, everytime i forgot a translation, the english one appear.

**Comment by cioroianudenis** [comment]
@lk77 but that is so confusing, what if I have lots of big text, can you imagine how the files would look like? Big keys and big values..... Coming from i18n, this is really weird.

**Comment by lk77** [comment]
Well there is no way around that,
if you split the translations, there is no way to tell in which file laravel should pick it up.
