### ISSUE TITLE
Helpers empty/filled don't work with collections

### ISSUE THREAD

**Issue by davi5e** [laravel/framework#37870]
- Laravel Version: 8.49.0
- PHP Version: 8.0.7
- Database Driver & Version: PostgreSQL 13.3.0

### Description:

Helper functions `empty` and `filled` should handle the `Illuminate\Database\Eloquent\Collection` class.

### Steps To Reproduce:

```php
# should return true
empty(collect([]))
```

**Comment by JohnKlein1991** [comment]
@davi5e why standard PHP function empty should return false for custom class, e.g  Collection?
From manual: "empty() is essentially the concise equivalent to !isset($var) || $var == false."
https://www.php.net/manual/en/function.empty.php
But empty collection return false in both cases: and !isset($var) and $var == false

**Comment by davi5e** [comment]
It's a standard function? I thought it was one of the helpers functions provided by the framework...

In any case, and empty collection shouldn't yield true using `empty()`?

Here we always need to cast the collection to array in order to use `empty` and sometimes people forget this trick...

**Comment by JohnKlein1991** [comment]
Really, it's not a function, but language construct and I don't know is it possible to change its behaviour with custom objects. 

> In any case, and empty collection shouldn't yield true using `empty()`?

no

> sometimes people forget this trick

If somebody uses function/construct from PHP, it's better to know how this function work. If he doesn't know - this is his problems

**Comment by mitchierichie** [comment]
@davi5e use collection method isEmpty, or isNotEmpty instead. For example:

```php
$collection = collect();

echo $collection->isEmpty();
// true
```

Or, if you're calling empty() because you don't know if the value is a collection, you can check if it is an instance of Enumerable (interface that Collection implements):

```php

if($someValue instanceof Enumerable) {
    $empty = $someValue->isEmpty();
} else {
    $empty = empty($someValue);
}
```

You should close this issue. This isn't something you can avoid with the Collection class. empty() is a standard PHP function and will not return true on an object, like a Collection instance.

**Comment by davi5e** [comment]
> If he doesn't know - this is his problems

It's true and I understand the logic behind your affirmation, but it's hardly practical once we need to manage other people...

We'll start using `isEmpty()` or the snipped, thanks @mitchierichie

**Comment by mfn** [comment]
@davi5e `empty()` and `isset()` truly can be fragile to work with; one would have to memoize e.g. https://www.php.net/manual/en/types.comparisons.php , which gives quite some examples.

There's (currently) no magic method on objects evaluated by this construct and I doubt it ever will.

If I may, I would recommend to **never** (<sup>1</sup>) use `empty()` on a "known variable". That is, if you _have_ a variable `$collection` in your context, do _not_ use `empty()`. Use explicit `null !==` or `[] !==` checks (some may say `!$collection` is also okay-ish).

One aspect of empty() is that, even if the var is _not declared_ before, the code just goes on. This makes it IMHO dangerous in non-template-y use-cases.

Of course for the `Collection` class, my above suggestion are not useful. Their intrinsic behviour is that they're stateful so you have to use their methods to check them, like it was suggested.

HTH!


<sup>1)</sup> There's always a "but" somewhere ;)

**Comment by davi5e** [comment]
I understand all the explanations and all the reasoning. I also agree with everything that is written in this thread.

Anyhow, given the amount of helper functions Laravel deploys, I still think the could be a replacement for ```empty``` and ```filled``` to simplify this cases. I suppose my lack of knowledge about ```empty``` being a PHP native construct can generate bugs in other peoples' code (if people start using PHP because of Laravel as it was the case here).

As for now, we're using ```empty($collection->toArray())``` for internal reasons.
