### ISSUE TITLE
DB Connection new won't work MongoDB

### ISSUE THREAD

**Issue by blpraveen** [laravel/framework#37883]
Thus my model. I am calling

     ( new Tenant())->configure()->use();

It still uses the  default connection

    namespace App\Models;

    use Illuminate\Database\Eloquent\Factories\HasFactory;
    use Jenssegers\Mongodb\Eloquent\Model;
    use Illuminate\Support\Facades\DB;
    use Illuminate\Support\Facades\Schema;

    class Tenant extends Model
    {
        use HasFactory;
        protected $connection = 'landlord';

        protected $guarded = [];
         /**
         *
         */
        public function configure()
        {
            config([
                'database.connections.tenant.database' => $this->database,
            ]);

            DB::purge('tenant');
            DB::reconnect('tenant');
            Schema::connection('tenant')->getConnection()->reconnect();

            return $this;
        }

        /**
         *
         */
        public function use()
        {
            app()->forgetInstance('tenant');

            app()->instance('tenant', $this);

            return $this;
        }
    }

- Laravel Version:10
- PHP Version: 7.4
- Database Driver & Version:
Mongodb
### Description:

DB connection is not working after I purge and reconnect. when I migrate it still points to Default Connection

### Steps To Reproduce:

            DB::purge('tenant');
            DB::reconnect('tenant');
            Schema::connection('tenant')->getConnection()->reconnect();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
