### ISSUE TITLE
Laravel latest version Target class [Illuminate\Routing\Middleware\ThrottleRequests] does not exist 

### ISSUE THREAD

**Issue by Phojie** [laravel/framework#37891]
This issue has been closed. But when I upgraded my laravel from v8.48.2  to the latest. It does again.

I am using laravel passport

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
