### ISSUE TITLE
Wrong data used in Mailable with Redis Queue

### ISSUE THREAD

**Issue by neoteknic** [laravel/framework#37894]
- Laravel Version: 8.49.0
- PHP Version: 8.0.7
- Database Driver & Version: 10.5.10-MariaDB
- Queue : Redis + Horizon

### Description:
outdated data in email with queue

### Steps To Reproduce:
use this kind of code in static function boot() : 

```
Reservation modal class boot method :


self::updated(function(Reservation  $reservation){
	if($reservation->isDirty(['room_id','start_at'])){
		//dd($reservation);
		Mail::to($reservation->email)->send(new MailConfirmationReservation($reservation));
		$reservation->notifyAdmin();
	}
});


mail class  : 

class MailConfirmationReservation extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;


    protected $reservation;

    public function __construct(Reservation $reservation)
    {
       $this->reservation=$reservation;
    }

    public function build()
    {
	setlocale(LC_TIME,'fr_FR.UTF-8');
	Carbon::setLocale('fr');
    	$this->subject('Confirmation de votre réservation');
        return $this->view('emails.reservation-v2',['reservation'=>$this->reservation]);
    }
}
    
```

(same problem with updating)

In the received email after queue process I have the values from "original", instead of "attributes" :
```
#attributes: array:30 [▼
    "id" => 4853
    "room_id" => "3"
    "players" => "3"
 ...
    "start_at" => "2020-08-10 09:30:00" <= Should have this value in email
...    
    "created_at" => "2020-08-11 11:27:23"
    "updated_at" => "2021-07-02 22:24:07"
  ]
  #original: array:30 [▼
    "id" => 4853
    "room_id" => 3
    "players" => 3
  ...
    "start_at" => "2020-08-13 11:30:00" <= But I have this value
   ...
    "created_at" => "2020-08-11 11:27:23"
    "updated_at" => "2021-07-02 22:21:27"
  ]

```

If I dump with $reservation->toArray() I have the attributes field, but email have data from original

**Comment by neoteknic** [comment]
Quick fix with 1 second delay :
Mail::to($reservation->email)->later(now()->addSecond(),new MailConfirmationReservation($reservation));

On redis data dump of wrong email , only Reservation objet with id is passed : maybe redis/horizon is  too fast, mailable job processed before the database save. But strange because I am in the updated event, it should not do that, (maybe not in "updating" either).

**Comment by neoteknic** [comment]
Test with QUEUE_DRIVER=sync  (instead of QUEUE_DRIVER=redis)
No problem, good data in email

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by neoteknic** [comment]
@driesvints It's not a question, because I know the answer and the fix, it is just a bug, I use redis, I dispatch a job in a model event, The job will have outdated data in "saved event" , how can it be possible ? it's a bug with the event system ? I know that the job wil request the DB to retrieve the object, ok but it should be done AFTER the save ? Why in the saved event data are not really saved in the DB ? It can be a "bug" with the DB/filesystem, or laravel horizon ?
Bug with QUEUE_DRIVER=redis, no bug with QUEUE_DRIVER=sync
