### ISSUE TITLE
Custom Validation Rule used in string context does not pass on error messages

### ISSUE THREAD

**Issue by roni-estein** [laravel/framework#37895]
- Laravel Version: I can do 8.49.1
- PHP Version: 8.0.7
- Database Driver & Version: sqlite / testing

### Description:
When creating a custom Rule, if you use the rule in Tuple Syntax, the `message()`function returns the error message, but if you leave your validations in string form, they don't. Here is a complete Rule with code and example.

### Steps To Reproduce:

Rule:
```php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class LocalPhone implements Rule
{
    /**
     * Create a new rule instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }
    
    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value): bool
    {
        return $this->checkPhoneLength($this->onlyDigits($value));
    }
    
    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message(): string
    {
        return 'The :attribute must be a valid phone number 1 XXX-XXX-XXXX.';
    }
    
    private function onlyDigits($text): array|string|null
    {
        return  preg_replace('/[^0-9]/', '', $text);
    }
    
    private function checkPhoneLength($number): bool
    {
        $i = -10 + strlen($number);
        return (
            ((strlen($number) == 11 && $number[0] == "1") ||
                (strlen($number) == 10 && $number[0] != "1")) &&
            ((int) $number[0 + $i] >= 2) &&
            ((int) $number[3 + $i] >= 2)
        );
    }
}

```

AppServiceProvider - boot()

```php

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Validator::extend('phone', 'App\\Rules\LocalPhone@passes');


```

Usage (works but message is not passed back):

```php

$rules = [ 'model.phone' => 'required|phone',]

```

![Screen Shot 2021-07-03 at 12 45 22 AM](https://user-images.githubusercontent.com/8517475/124344464-f6144400-db97-11eb-9822-a7ec4b1c2636.png)

Usage (works as expected):

```php

$rules = [ 'model.phone' => ['required', new LocalPhone()],]

```

![Screen Shot 2021-07-03 at 12 46 37 AM](https://user-images.githubusercontent.com/8517475/124344490-23f98880-db98-11eb-9b28-a6836a394335.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
