### ISSUE TITLE
Pagination links with additional query generates links that not contain this query data

### ISSUE THREAD

**Issue by PunyFlash** [laravel/framework#37907]
- Laravel Version: 8.49.1
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 10.4.18-MariaDB

### Description:
When using any type of pagination (`paginate`, `simplePaginate`, `cursorPaginate`) with additional query data, paginator generates links that not contain provided query data. In my opinion returned on pagination `next_page_url` and `prev_page_url` should keep any aditional query parameters that not related to pagination. I do believe that there is no such condition when you want to flush other query parameters on pagination. In my case I do want to extract cursor from `next_page_url` mannualy and build URL by myself on frontend wich is not that comfortable.

### Steps To Reproduce:
1) Build controller that return paginated data:
```php
/**
 * GET: http://127.0.0.1/api/categories
 */
public function index()
{
    // QueryBuilder applies database query parameters like `where`, 'with', 'orderBy' etc for provided model
    // depending on URL query parameters. Returns instance of Illuminate\Database\Query\Builder
    return \Spatie\QueryBuilder\QueryBuilder::for(Category::class)
        ->allowedFields(['name', 'id', 'category_id'])
        ->allowedFilters('name', 'id', 'category_id')
        ->allowedSorts('name', 'id', 'category_id')
        ->allowedIncludes('subcategories', 'supercategory', 'products')
        ->cursorPaginate(5);
}
```
2) Make request with additional query data (`sort` used in example):
```json
// GET http://127.0.0.1/api/categories?sort=name

{
  "data": [
    {
      "id": 27,
      "category_id": null,
      "name": "Autem.",
      "created_at": "2021-07-02T22:12:23.000000Z",
      "updated_at": "2021-07-02T22:12:23.000000Z"
    },
    {
      "id": 23,
      "category_id": 14,
      "name": "Consequatur tempore.",
      "created_at": "2021-07-02T22:12:22.000000Z",
      "updated_at": "2021-07-02T22:12:22.000000Z"
    },
    {
      "id": 14,
      "category_id": null,
      "name": "Cum reiciendis.",
      "created_at": "2021-07-02T22:12:22.000000Z",
      "updated_at": "2021-07-02T22:12:22.000000Z"
    },
    {
      "id": 24,
      "category_id": 23,
      "name": "Distinctio eligendi.",
      "created_at": "2021-07-02T22:12:23.000000Z",
      "updated_at": "2021-07-02T22:12:23.000000Z"
    },
    {
      "id": 11,
      "category_id": 10,
      "name": "Dolores placeat.",
      "created_at": "2021-07-02T22:12:22.000000Z",
      "updated_at": "2021-07-02T22:12:22.000000Z"
    }
  ],
  "path": "http://127.0.0.4/api/categories",
  "per_page": 5,
  "next_page_url": "http://127.0.0.4/api/categories?cursor=eyJuYW1lIjoiRG9sb3JlcyBwbGFjZWF0LiIsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0",
  "prev_page_url": null
}
```
3) Returned `next_page_url` should be: 
```
http://127.0.0.4/api/categories?sort=name&cursor=eyJuYW1lIjoiRG9sb3JlcyBwbGFjZWF0LiIsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
