### ISSUE TITLE
Validating INF and NAN values using multiple_of rule causes an error

### ISSUE THREAD

**Issue by hafezdivandari** [laravel/framework#37902]
- Laravel Version: 8.49.1
- PHP Version: 7.4.6

### Description:
Validating `INF` and `NAN` values using `multiple_of` rule causes an error:
> ErrorException(code: 0): bcmod(): bcmath function argument is not well-formed

### Steps To Reproduce:
```php
Validator::make([
    ['upper_endpoint' => INF],
    ['upper_endpoint' => NAN],
], [
    '*.upper_endpoint' => 'required|numeric|multiple_of:0.01'
])->passes();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by hafezdivandari** [comment]
Hi @driesvints, It is a bug not a question!
Since `INF` and `NAN` constants are numeric in PHP and we don't check this edge cases on [`validateMultipleOf`](https://github.com/laravel/framework/blob/65d12ca73ef0b184d89de74566af5a8f1daf75d4/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1297) function, the `bcmod('INF', ...` leads to an error:

https://github.com/laravel/framework/blob/65d12ca73ef0b184d89de74566af5a8f1daf75d4/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1297-L1310

We expect validation to return `true` or `false` but not throwing an error.
Please recheck **step to reproduce** section and re-open this issue.

**Comment by driesvints** [comment]
These aren't supported.
