### ISSUE TITLE
Unresolved routes are forwarded to exception handler

### ISSUE THREAD

**Issue by BasvanH** [laravel/framework#37913]
### Versions
- Laravel Version: 7.29.3
- PHP Version: 7.4.13
- Database Driver & Version: Mysql 8.0

### Description:
I have a Route::fallback('fallbackClass@unresolved') defined in my web and api route files. An unresolved route gets forwarded to that class, but it also get's forwarded to the default /App/Exceptions/Handler::class .

If the unresolved route is captured by the fallback route, why does it still throw an exception?

...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php(162): Illuminate\\Routing\\AbstractRouteCollection->handleMatchedRoute() 1 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(639): Illuminate\\Routing\\RouteCollection->match() 2 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->findRoute() 3 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute() 4 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch()

I'm asking as I want to create an hook on the Exception handler, then I discovered these reports which I think is incorrect.

### Steps To Reproduce:
- Add a failback into web or api routes file.
- In App\Exceptions\Handler create a hook in report() method.
- Request a non-existing route.
- You will see the request is forwarded to the fallback but an exception is also triggered.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by BasvanH** [comment]
Upgraded to Laravel 8, and now it works as expected. Using a fallback route does not trigger an exception.
