### ISSUE TITLE
Unreadable directories in config folder causes a Runtime Exception

### ISSUE THREAD

**Issue by fetzi** [laravel/framework#37914]
- Laravel Version: 8.49.0
- PHP Version: 7.x, 8.0
- Database Driver & Version: -

### Description:
The `--delay-updates` parameter on rsync generates a temporary directory owned by the executing user (root in our case) and copies all changed config files in there.

When accessing the application during the rsync it produces a `RuntimeException` because this directory is not accessible.

### Steps To Reproduce:
1. create a folder in `config/` and set access rights to `root:root` and put a `.php` file in there
2. open the application

This bug can be fixed by adding `->ignoreUnreadableDirs()` in `LoadConfiguration::getConfigurationFiles`. If  you want I can send a PR to fix this.

**Comment by driesvints** [comment]
I don't think we can be responsible for what rsync does. In general, directories indeed need to be accessible by whatever user that runs the app.

**Comment by fetzi** [comment]
@driesvints I totally understand that, but I think that hidden or unreadable directories should always be excluded from iterations.

**Comment by driesvints** [comment]
@fetzi im not sure I agree there. Typically, there wouldn't be any hidden directories in that config folder.

**Comment by fetzi** [comment]
@driesvints: maybe not in this particular case, but in general when you iterate over files and folders you want to exclude dot files and folders per default, because they should not be considered.

I think the change has no downsides or side effects and would make the implementation more robust.
