### ISSUE TITLE
Random test failure when ran parallel due VarDumper TypeError

### ISSUE THREAD

**Issue by flexchar** [laravel/framework#37912]
- Laravel Version: 8.47.0
- PHP Version: 8.0.3 (built: Apr 10 2021 13:25:28)
- Database Driver & Version: 8.0.23 - MySQL Community Server - GPL 

### Description:

When running `php artisan test --parallel` random tests may start failing. Recreate databases do not seem to have an affect.

![image](https://user-images.githubusercontent.com/9198896/124459964-9f4b6d80-dd43-11eb-85c7-1e8005778dfb.png)

However tests always pass when running `artisan test`.

When a fail occurs it's always the same `TypeError` of `VarDumper` class. There are no left `dd/ddd/dump` code snippets.
```bash
TypeError: Symfony\Component\VarDumper\Server\Connection::__construct(): Argument #1 ($host) must be of type string, null given, called in /var/www/vendor/beyondcode/laravel-dump-server/src/DumpServerServiceProvider.php on line 49

/var/www/vendor/symfony/var-dumper/Server/Connection.php:32
/var/www/vendor/beyondcode/laravel-dump-server/src/DumpServerServiceProvider.php:49
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:672
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:75
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:649
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:237
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:310
/var/www/tests/CreatesApplication.php:18
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:108
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:85
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
