### ISSUE TITLE
after_or_equal rule

### ISSUE THREAD

**Issue by cezar62882** [laravel/framework#37910]
- Laravel Version: 8.45.1
- PHP Version: 7.4.16

### Description:

Wrong validation after_or_equal rule if the second value is null

### Steps To Reproduce:

```
$data = [
    'date_1' => null,
    'date_2' => '2021-04-05'
];

try {
    $data = Validator::make($data, [
        'date_1' => 'nullable|date|date_format:Y-m-d',
        'date_2' => 'nullable|date|date_format:Y-m-d|after_or_equal:date_1'
    ])->validate();
    dump($data);
} catch (\Illuminate\Validation\ValidationException $exception) {
    dd($exception->errors());
}
```

Expected result: validation passed.
Actual result: validation failed.

**Comment by driesvints** [comment]
The current behavior is correct. `date_1` is nullable so it should pass.

**Comment by cezar62882** [comment]
You can run code and you will see that validation failed.

**Comment by driesvints** [comment]
@cezar62882 sorry, I took another look at this and you're correct. The current behavior is indeed that `date_1` is implicitly required when using `after_or_equal` even if you make it `nullable`. 

If anything is not clear in the docs we'd appreciate PR's for that.

**Comment by cezar62882** [comment]
Another side, if remove` date_format:Y-m-d ` from date_2 you will see the right behavior.

```
$data = Validator::make($data, [
        'date_1' => 'nullable|date|date_format:Y-m-d',
        'date_2' => 'nullable|date|after_or_equal:date_1'
])->validate();
```
