### ISSUE TITLE
RefreshDatabase table not found - delaying execution of script until database is ready

### ISSUE THREAD

**Issue by longestdrive** [laravel/framework#37916]
- Laravel Version: 8.47.0
- PHP Version: 7.4.5
- Database Driver & Version: sqlite 3.22 (testing)

### Description:
I'm trying to test a class that fetches data from the database from within the `__constructor`. It works in a live environment but fails when running tests.

It appears that at the point of initialising the class the database is not ready and I'm unable to find a way to delay initialising until the database is ready.

I am using `RefreshDatabase` 

### Steps To Reproduce:

Here is the class I'm trying to initialise:
Here's the basics of the class I'm tryting to test:

class PlayerRounds
{

    use EclecticPresenter;

    private RoundRepository $roundRepository;

    private CourseRepository $courseRepository;

    private $courseHoles;

    public function __construct(RoundRepository $roundRepository, CourseRepository $courseRepository)
    {
        $this->roundRepository = $roundRepository;
        $this->courseRepository = $courseRepository;
        $this->init();

    }

  private function init()
    {
        $this->courseHoles = $this->courseRepository->all();
    }

    /**
     * generates eclecic rounds for each league the player is in
     * @param Player $player
     */
    public function getAllEclecticRounds(Player $player)
    {
        $allEclecticRounds = collect();

        $leagues = $player->league()->where('league_type', 'eclectic')->get();

        $leagues->each(function ($league) use ($player, $allEclecticRounds) {
            $newRound = $this->getPlayerEclecticRound($player, $league);
            $allEclecticRounds->put($league->id, $newRound);
        });

        return $allEclecticRounds;
    }
```
The test fails at the init() method with `sql general error table not found: course`. The fetch $this->courseHoles = $this->courseRepository->all(); the the test fails with a table not found error if it's within the constructor, It works if I place this piece of code within each method that needs it but means I call it often rather than once.

Here's my test:

class PlayerRoundsTest extends TestCase
{
    use RefreshDatabase;
    use EclecticTestHelper;
    use WithFaker;

    private $playerRounds;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(CourseTableSeeder::class);

        $this->playerRounds = app()->make(PlayerRounds::class);
    }

    /**
     * @test
     * @covers PlayerRounds::getAllEclecticRounds
     * @description:
     */
    public function it_returns_an_eclectic_round_for_all_leagues()
    {
        $player = Player::factory()->has(League::factory()->count(3))->create();

        foreach ($player->league()->get() as $league) {
            for ($x = 0; $x <= 3; $x++) {
                $this->createScores($league, $player);
            }
        }

        $result = $this->playerRounds->getAllEclecticRounds($player);

        $this->assertCount(3, $result);
        $result->each(function($collection) {
            $this->assertCount(1, $collection);
        });
Are there any ideas how I can initiate the class correctly and get the test set up correct and ensure the database is ready for the test. I assumed using RefreshDatabase was the correct approach and I had things in the correct order.

Thank you

**update If I change the constructor to this:

   public function __construct(RoundRepository $roundRepository, CourseRepository $courseRepository)
    {
        $this->roundRepository = $roundRepository;
        $this->courseRepository = $courseRepository;
    }
and then place the code that calls on the database to the method used in the test back to this:

public function getPlayerEclecticRound(Player $player, League $league, $maxDate = null)
    {
        // FIXME: Initiate at start in constructor but fails in tests
        $this->courseHoles = $this->courseRepository->all();

       //rest of code removed for brevity
    }
This then passes the test.

This class needs the data in $this->courseHoles for a number of methods to work so I'm aiming to just call this once at initialization rather than every time I access the method as it is now but can' get it to work in a testing environment.

note I'm using a mysql database on the server but a sqlite memory database in testing

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by longestdrive** [comment]
Hi - thank you. I will try the forums as suggested - I've seen similar questions to this.
I'd like to understand the sequence Laravel uses to create the application in testing - it looks as if it's booting and pulling in my class early in the process (even though not I assumed actually created until I called `app()->make()` on the class. 
Where can I find that information?

**Comment by longestdrive** [comment]
Hi -appreciate this is closed but wonder if this is the expected behavior.
I've tracked the issue to a command that has a dependency on the class in question - assuming these commands are loaded as part of `CreateApplication` but before `RefreshDatabase` has had a chance to do it's stuff.
So is this a bug or expected behavior I need to work around.?

**Comment by X-Coder264** [comment]
Constructors shouldn't have side effects (like in your example loading stuff from the database). The proper fix is to move that logic out of the constructor.
