### ISSUE TITLE
CockroachDB Issue With Queue Skip Locking

### ISSUE THREAD

**Issue by chris-rutherfurd** [laravel/framework#37928]
- Laravel Version: 8.49
- PHP Version: 8.0.6
- Database Driver & Version: pgsql

### Description:
In Illuminate/Queue/DatabaseQueue.php method getLockForPopping all pgsql connections above v9.5 include `FOR UPDATE SKIP LOCKED` however CockroachDB, which uses PostgreSQL does not support skip locked and so is causing issues with using the database as a queue engine and I can't find anyway to override this behavior to prevent skip locking from taking place. A check of the version string returned by PDO shows that this only returns as 9.5, it does not include any identifying marks such as CRDB as MariaDB does and so am struggling to figure out a way to manually override this.

Information on CockroachDB's recommended approach to work queue implementation without skip locking is at https://forum.cockroachlabs.com/t/how-to-implement-a-work-queue-without-skip-locked/3109 but appears to boil down to the use of the query addition `AS OF SYSTEM TIME`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
