### ISSUE TITLE
$dontReport in App\Exception\Handler does not seem work

### ISSUE THREAD

**Issue by BasvanH** [laravel/framework#37923]
- Laravel Version: 8.49.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL

### Description:
$dontReport in App\Exception\Handler does not seem to work.

Occording to the [docs](https://laravel.com/docs/8.x/errors#ignoring-exceptions-by-type) you should add the exception class to $dontReport. I want to exclude messages regarding methods not found on routes.

**Exception trace:**
```
0 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\AbstractRouteCollection.php(103): Illuminate\\Routing\\AbstractRouteCollection->methodNotAllowed()
1 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\AbstractRouteCollection.php(40): Illuminate\\Routing\\AbstractRouteCollection->getRouteForMethods()
2 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\CompiledRouteCollection.php(144): Illuminate\\Routing\\AbstractRouteCollection->handleMatchedRoute()
3 ...\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(647): Illuminate\\Routing\\CompiledRouteCollection->match()
```

**Dump of get_class($exception):**
```
Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException
```

**I have tried:**
```
protected $dontReport = [
  Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException::class,
  MethodNotAllowedHttpException::class,
  'Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException'
];
```

None seems to exclude this exception.

**Comment by ajuchacko91** [comment]
Hi, @BasvanH 

Just to be clear, you will see an exception in the browser even if you put that exception in `$dontReport` variable but it will avoid logging things like that.

As you may have already read in the [docs](https://laravel.com/docs/8.x/errors#ignoring-exceptions-by-type) "Behind the scenes, Laravel already ignores some types of exceptions internally for you" (last paragraph beside light bulb)

Laravel ignores this exception by default internally `Symfony\Component\HttpKernel\Exception\HttpException::class` which is a parent class of `Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException::class` So that exception won't report as well.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by BasvanH** [comment]
> Just to be clear, you will see an exception in the browser even if you put that exception in `$dontReport` variable but it will avoid logging things like that.

In App\Exception\Handler report() method I dump the exception. So it's not about rendering to the browser, I see unknown method request entering the report() method while I would expect they would be skipped bij $dontReport.

I asume the build in skip types are defined in the parent ExceptionHandler class.

**Comment by ajuchacko91** [comment]
@BasvanH I'd like to take a look into the code if you point me to that repo or some where

**Comment by BasvanH** [comment]
@ajuchacko91, thanks.

The App\Exception\Handler class extends [Handler.php](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Exceptions/Handler.php)

https://github.com/laravel/framework/blob/ab5a864c147fdbfcce9f1a81fe56743977ede210/src/Illuminate/Foundation/Exceptions/Handler.php#L59
https://github.com/laravel/framework/blob/ab5a864c147fdbfcce9f1a81fe56743977ede210/src/Illuminate/Foundation/Exceptions/Handler.php#L274

**Comment by BasvanH** [comment]
I think I got it, the $dontReport in App\Exception\Handler class works **after** the parent::report($exception). So every exception is passed in the report() method of App\Exception\Handler.

You dont have to search any further @ajuchacko91 .

**Comment by ajuchacko91** [comment]
@BasvanH App\Exception\Handler class doesn't have a report method defined it actually extends from parent. I guess you defined it yourself and forgot to called to parent::report($e). That's why I asked to show me the repo(laravel app) not the laravel source code.
Good you found out yourself.
