### ISSUE TITLE
same bad method call issue 

### ISSUE THREAD

**Issue by Fawadkhan-rgb** [laravel/framework#37924]
Method Illuminate\Validation\Validator::validateUsername does not exist

how to add username to  validator im facing this issue when i am validating username in register controller please help

**Comment by ajuchacko91** [comment]
Hi, @Fawadkhan-rgb 

You actually have a question here not an issue. For which is what there is some [forums already created.](https://linktr.ee/ajuchacko) So you can ask this types questions there.

[Laravel Docs on how to do validations](https://laravel.com/docs/8.x/validation#introduction)

Anyways, you can validate username like so if you want
`$validated = $request->validate(['username' => 'required|unique:users|max:255']);`
