### ISSUE TITLE
Queue worker sending prepare statement twice

### ISSUE THREAD

**Issue by grushkoyevhen** [laravel/framework#37931]
- Laravel Version: 8.48.2 
- PHP Version: 7.4.16
- Database Driver & Version:  MySQL 8.0.23

### Steps To Reproduce: 
1. php artisan queue:listen database
2. check query log. You'll see that every worker that scans jobs table sending prepare statement twice.
Query START TRANSACTION
Prepare SELECT * FROM jobs ...
Same command Prepare SELECT * FROM jobs ...
Execute
Close stmt
Query COMMIT

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
