### ISSUE TITLE
sometimes validation rule not working just on input[type=file]

### ISSUE THREAD

**Issue by r-shaygan** [laravel/framework#37933]
` return [
            'firstname' => 'required|alpha|min:2|max:30',
            'lastname' => 'required|alpha|min:2|max:30',
            'city' => 'required|alpha|max:30|min:2',
            'meli'=>'required|numeric|digits:10',
            'dob'=>'required|date|before:07/06/2014',
            'email'=>'email:rfc',
            'image'=>'sometimes|required|image',
        ];`

i want when image field is present in form , be required ..so wrote that code
But despite that image field is in form and is sent empty , passes validation..
about other fields i tryed  'somtimes' rule and  is working well..

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
