### ISSUE TITLE
The DatabaseBatchRepository does not handle DB transaction failure resulting in unfinished batches.

### ISSUE THREAD

**Issue by adrianb93** [laravel/framework#37948]
- Laravel Version: 8.47.0
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 8.x

### Description:

I was looking through the logs and found that a DB lock was unable to be obtained for a transaction. The stack led me to `\Illuminate\Bus\DatabaseBatchRepository@updateAtomicValues` and `\Illuminate\Bus\Batch@decrementPendingJobs`.

Because the DB transaction to decrement the pending count could not commit, the batch was never able to decrement to 0, meaning the then/finally hooks were never triggered.

**Comment by ajuchacko91** [comment]
Hi @adrianb93,

Have you got this exception =>
[timestamp]  Illuminate\Database\QueryException in 
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: ...

then, you can avoid this either by changing the code or [retrying](https://laravel.com/docs/8.x/helpers#method-retry) also transaction method got a [second argument ](https://laravel.com/docs/8.x/database#handling-deadlocks) which allows you to retry the transaction when a deadlock occurs


if not, can you provide some steps on how to reproduce this issue

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
