### ISSUE TITLE
Problem in test_users_can_authenticate_using_the_login_screen from breeze

### ISSUE THREAD

**Issue by cjatoba** [laravel/framework#37940]
- Laravel Version: 8.49.2
- PHP Version: 7.4.18
- Database Driver & Version: mysql or sqlsrv

### Description:

When running tests with default test classes created by Laravel Breeze, database tables that are not listed in the migrations folder are cleared

### Steps To Reproduce:

1. I created a test project to report the bug with the command `laravel new bug-report --github =" - public "`

2. I created a database called bug_report

3. I ran the `php artisan migrate` command to perform the migrations

4. I created a table called test just to demonstrate the bug, the database structure looks like this:

![database structure](https://imgur.com/v3qMdnp.png)

5. I installed Laravel Breeze as per the documentation with the commands below:
- `composer require laravel/breeze --dev`
- `php artisan breeze:install`
- `npm install`
- `npm run dev`
- `php artisan migrate`

6. I ran the `php artisan test` command to run the tests, getting this return:

![Test return](https://imgur.com/M6LyBr8.png)

7. After running the tests, the test table created in step 2 is deleted:

![Database](https://imgur.com/OG2Eoqi.png)

This happens with any other existing tables in the database.

### Repository to demonstrate the problem
https://github.com/cjatoba/laravel_test_bug_report

**Comment by ajuchacko91** [comment]
Hi, @cjatoba 

You actually have a question here not an issue. For which is what there is some [forums already created.](https://linktr.ee/ajuchacko) So you can ask this types questions there

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by cjatoba** [comment]
Good afternoon,

Thank you, posted here that actually what causes the database cleanup is the `use RefreshDatabase;` parameter at the beginning of the test classes.
