### ISSUE TITLE
L8 - Overwrite replyTo once for single mailable and ignore global mail config

### ISSUE THREAD

**Issue by mstaack** [laravel/framework#37945]
- Laravel Version: 8.49.2
- PHP Version: 7.4
- Database Driver & Version: postgres 13

### Description:

I would like to overwrite the replyTo array once completely for a single mailable.
But global replyTo (from config) will always be added after(!) Mailable:build().
So there is no way to achieve this?

```php
// will be added to the replyTo for this mailable but also contains the mail-config replyTo
$mailable->replyTo(
    'demo@demo.com,
    'name'
);
```

So i thought i could simply overwrite that var, as its public:

```php
// this does not work, global replyTo will be added after build()
$mailable->replyTo = [
      'name' => 'demo@demo.com,
      'address' => 'name'
]
```

Responsible Mailer Code:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Mail/Mailer.php#L499

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mstaack** [comment]
Well the issue is, that there is no way to replace that replyTo only once without rebinding a custom mailer i guess.

**Comment by ajuchacko91** [comment]
Hey @mstaack,

Laravel has become huge now and you're less likely to have problem implementing something 😀

In this case you can send mail with different ```reply-to``` header without merging with global mail config


```
/**
 * Build the message.
 *
 * @return $this
 */
public function build()
{
    $this->view('emails.orders.shipped');

    $this->withSwiftMessage(function ($message) {
        $message->getHeaders()->addTextHeader(
            'Custom-Header', 'Header Value'
        );

        $message->setReplyTo(array(
            'person2@otherdomain.org' => 'Person 2 Name',
          ));
    });

    return $this;
}
```

Also Keep in mind that this place ain't meant for asking these sort of things
