### ISSUE TITLE
Bus::fake single job class will cause Bus::batch not work.

### ISSUE THREAD

**Issue by jspekken** [laravel/framework#37957]
### Discussed in https://github.com/laravel/framework/discussions/35808

<div type='discussions-op-text'>

<sup>Originally posted by **bolechen** January  7, 2021</sup>
- Laravel Version: v8.19.0
- PHP Version: 7.4.13

### Description:

Bus::fake single job class will  cause Bus::batch not work.

### Steps To Reproduce:

```php
<?php
// TestCase
    protected function setUp(): void
    {
        Bus::fake([SomeJobNeedFake::class]);
    }
?>
```

```php
<?php
$batch = Bus::batch([])->dispatch();
$batch->add([new AnotherJob()]);

// AnotherJob not execute!
?>


Is something wrong? Or is it a bug in laravel?

When i comment this line

```
Bus::fake([SomeJobNeedFake::class]);
```

all my test is pass.


My test is like this, I ask this to stack-overflow & Discord, but no one have know why this. :(

```php
class ExampleTest extends TestCase
{
    public function testBusFake()
    {
        Bus::fake([NeedFakeJob::class]);

        Bus::batch([
            new NeedFakeJob(),
            new NormalJob(),
        ])->dispatch();

        Bus::assertDispatched(NeedFakeJob::class);
    }
}
```

i make a fresh install laravel to reproduce this, could u have time to look? very thx. https://github.com/bolechen/busfake-bug

more info at bolechen/busfake-bug#1</div>

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by turgutsaricam** [comment]
`BusFake::batch()` method directly returns a `PendingBatchFake`. While its several other methods first check if the job should be faked, this method ignores the to-be-faked job classes.

https://github.com/laravel/framework/blob/3337c029e1bb31d9712d27437cc27010ba302c9e/src/Illuminate/Support/Testing/Fakes/BusFake.php#L625-L634

I think this should not be the case. The `BusFake` class should allow to not fake the batched jobs.
