### ISSUE TITLE
syntax error, unexpected token "endif". in components 

### ISSUE THREAD

**Issue by ahmetbarut** [laravel/framework#37972]
- Laravel Version: 8.x
- PHP Version: 8.0.7
- 
### Description:
Hi, I am using Laravel components. When I put the components in @if it says it is closed and @endif. I didn't write anything like that. It will be better understood with the output.

### Steps To Reproduce:
```php
@if (Session::has("formError"))
    <x-toast-alert title="{{ Session::get("title") }}" message="{{ Session::get("message") }}"></x-toast-alert>
@endif
```

### Output
```php
<?php if(Session::has("formError")): ?>
    <x-toast-alert title=" <?php echo e(Session::get("title")); ?> " message=" <?php echo e(Session::get("message")); ?> "> <?php if (isset($__componentOriginal)): ?>
<?php $component = $__componentOriginal; ?>
<?php unset($__componentOriginal); ?>
<?php endif; ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php endif; ?>
```
### Error
```php
Illuminate \ View \ ViewException (E_ERROR)
syntax error, unexpected token "endif", expecting end of file (View: /srv/http/web/resources/views/layouts/footer.blade.php) (View: /srv/http/web/resources/views/layouts/footer.blade.php) (View: /srv/http/web/resources/views/layouts/footer.blade.php)
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
