### ISSUE TITLE
Unable to make spy on the "Schema" facade

### ISSUE THREAD

**Issue by awjudd** [laravel/framework#37974]
- Laravel Version: 8.49.2
- PHP Version: 8.0.7
- Database Driver & Version: N/A

### Description:
When testing and trying to mock/spy the `Schema` object (i.e. `Schema::spy()`), as soon as you apply any expectations you receive an error.

### Steps To Reproduce:

1 - Create a test case
2 - Call the following:
```php
Schema::spy()
    ->shouldReceive('hasTable')
```
3 - When you run the test case, you will receive the following error:
```
TypeError: Illegal offset type in isset or empty

/Users/judda/code/schema-facade/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:128
/Users/judda/code/schema-facade/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:52
/Users/judda/code/schema-facade/tests/Feature/ExampleTest.php:18
```

Commit with the issue:
https://github.com/awjudd/laravel-schema-issue/commit/11cc50c7dab273fd4fdfc6a848cf0f55147bee33#r53308692

### Extra Information

When digging a little deeper, it looks like there are at least 2 spots that have the same issue. In `src/Illuminate/Support/Facades/Schema.php` the following methods:
* `swap`
* `isMock`

I believe that it has to do with the following change:
https://github.com/laravel/framework/commit/63d87d78e08cc502947f07ebbfa4993955339c5a

The reason being, at this point in time the method no longer could be trusted to only return a string, so doing the dictionary lookup was ignored in one spot (https://github.com/laravel/framework/commit/63d87d78e08cc502947f07ebbfa4993955339c5a#diff-85c2ee3096a7c4457f3abe3785b2584af93e1672402207cee10195543acbba49R167)

**Comment by driesvints** [comment]
I've not meant to be used like this. See https://laravel.com/docs/8.x/mocking#facade-spies

**Comment by awjudd** [comment]
@driesvints Even using it the way suggested in the documentation does not work.
https://github.com/awjudd/laravel-schema-issue/commit/9040182ce26fc4572c6c79f6200d13d12ddc8042
