### ISSUE TITLE
Calling spy method on facade a second time returns null

### ISSUE THREAD

**Issue by awjudd** [laravel/framework#37975]
- Laravel Version: 8.49.2
- PHP Version: 8.0.7
- Database Driver & Version: N/A

### Description:
Despite what the contract of the `spy` method states in the docblock, if you call the `spy` method twice on a Facade, the second time it will return `null` instead of the mock.

### Steps To Reproduce:

1 - Create a test case
2 - Call the `spy` method twice
3 - The second time if you chain anything off of it, it will result in an error since it is returning `null`

Commit with the issue:
https://github.com/awjudd/laravel-double-call-spy/commit/ccb0b167634df23041e63aa7bb8c9e2a8b46cf0c#r53309385

**Comment by ajuchacko91** [comment]
Hi @awjudd,

If I remember correctly calling ```spy``` on facades returns ```Mockery spy```
you can learn more about it [here](http://docs.mockery.io/en/latest/reference/spies.html)

**Comment by driesvints** [comment]
You shouldn't call it twice.

**Comment by awjudd** [comment]
> Hi @awjudd,
> 
> If I remember correctly calling `spy` on facades returns `Mockery spy`
> you can learn more about it [here](http://docs.mockery.io/en/latest/reference/spies.html)

The first time it does, the second time it does not.



> You shouldn't call it twice.

If I shouldn't be using the mock that comes back, then is there a ready why this function actually returns a value and not null always?

**Comment by ajuchacko91** [comment]
Hi awjudd,

Let's be clear I said ```Mockery spy``` Not ```Mock``` they are different.

spies record any interaction between the spy and the code being tested
```
        $spy = Facade::spy());
        Facade::foo();
        $spy->shouldHaveReceived('foo'); // it's assertions are based on past actions
```

while mock
```
       $mock = Facade::shouldReceive('foo')->once()->with('bar')->andReturn('biz')->getMock(); // based on future actions
       $this->assertSame('baz', Facade::bar());
```

any no one would ever spy on a spy 😀

**Comment by awjudd** [comment]
Sorry - yes I used the wrong terminology out of a bad habit.
