### ISSUE TITLE
When calling update on an existing model, and using a where, model identity gets ignored

### ISSUE THREAD

**Issue by jimrubenstein** [laravel/framework#37979]
- Laravel Version: 8.42.0
- PHP Version: 7.4.8
- Database Driver & Version: mysql - MariaDB 10.4.13

### Description:

If you're attempting to update a model, and using a where clause to ensure the model is only updated in a specified use-case, the query builder leaves out the `WHERE model@keyName() = model@getKey()` clause of the query.

This seems pretty counter-intuitive, and requires what would seem like a superfluous `where` statement in the update definition.

### Steps To Reproduce:

1. create a few models
2. query for a single one
3. run an update w/a where clause
4. observe, all models matching the where are updated, not just the model you're operating on

**Example**
https://gist.github.com/jimrubenstein/b5fbbb7f77d4cf7a862b4a32448e04d9

```php
$thing = TestThing::find(1);
$thing->whereNull('a_value')->update(['a_value' => 'noooo']);
```

**Output (from example)**

```php
array:5 [
  0 => array:4 [
    "id" => 1
    "a_value" => "noooo"
    "created_at" => "2021-07-11T09:24:08.000000Z"
    "updated_at" => "2021-07-11T09:24:08.000000Z"
  ]
  1 => array:4 [
    "id" => 2
    "a_value" => "noooo"
    "created_at" => "2021-07-11T09:24:08.000000Z"
    "updated_at" => "2021-07-11T09:24:08.000000Z"
  ]
  2 => array:4 [
    "id" => 3
    "a_value" => "noooo"
    "created_at" => "2021-07-11T09:24:08.000000Z"
    "updated_at" => "2021-07-11T09:24:08.000000Z"
  ]
  3 => array:4 [
    "id" => 4
    "a_value" => "noooo"
    "created_at" => "2021-07-11T09:24:08.000000Z"
    "updated_at" => "2021-07-11T09:24:08.000000Z"
  ]
  4 => array:4 [
    "id" => 5
    "a_value" => "noooo"
    "created_at" => "2021-07-11T09:24:08.000000Z"
    "updated_at" => "2021-07-11T09:24:08.000000Z"
  ]
]
```

**Comment by ajuchacko91** [comment]
Hi @jimrubenstein,

```TestThing``` is an Eloquent model in which ```whereNull``` method is defined
```$thing = TestThing::find(1);```

```
$test_thing->whereNull('price'); // output is give below
=> Illuminate\Database\Eloquent\Builder {#4101}
```

which is also same as
```
TestThing::query();
=> Illuminate\Database\Eloquent\Builder {#4309}
```

Therefore you can chain methods on this and [this is a very well know feature of laravel](https://laravel.com/docs/8.x/eloquent#mass-updates):

**Comment by staudenmeir** [comment]
Please see #28549 where we discussed the general issue.

**Comment by driesvints** [comment]
See the above.

**Comment by jimrubenstein** [comment]
I understand the breaking change nature of this issue, but, nonetheless, it seems unintuitive.

The code above reads as: 'update $thing, set a_value to "nooo" as long as a_value is not currently set'

I understand the use-case of `model@query` generating a new query object, but would argue that if you're not calling `->query()` directly, or you're not calling `->whereXXXX` on a non-existing model, then the code -as its written- suffers from the same misunderstanding trap.

If i came upon the example code in a repo I would expect a 1 or 0 (or true or false) result indicating whether my specific instance has been updated or not, and that only 1 database row would be modified.

Like I said though: I understand the consequences that would come of making this change, and no matter how many people agree with my view it's unlikely to change, simply because of the wide usage of this type of behavior, and the size of the potential problems that could come from changing the api in this way.

Nonetheless, I just wanted to document my perception here.

Thanks for the links to the other [similar] issues, and all the work you put into triaging/dealing with incoming issues :cheers:
