### ISSUE TITLE
HandlesAuthorization deny method code parameter doesn't change 

### ISSUE THREAD

**Issue by valehasadli** [laravel/framework#37978]
- Laravel Version: 8.49.2
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 8.0

### Description:
I am using a Policy class and using the deny allow methods in the HandleAuthorization class as Trait, the deny method accepts the status code as the second parameter, even though I give the 403 code, I get a response code as 401 every time.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by valehasadli** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Hi, I don't mind it's a question, it looks like a bug. Because given status code not reflect to response.
