### ISSUE TITLE
Incorrect accepted types for leftJoinSub

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#37982]
- Laravel Version: 8.19.0
- PHP Version: 8.0.0
- Database Driver & Version: Irrelevant

### Description:
Some Query\Builder methods such as `leftJoinSub`, `selectSub` etc. have incorrect accepted argument types.
Even though they accept both Query\Builder and Eloquent\Builder instances, the latter isn't mentioned in the `@param` annotation and the IDE marks the following method call as incorrect.

![image](https://user-images.githubusercontent.com/13980973/125274514-53ce2c00-e30e-11eb-9f40-1b3a08725874.png)

I can make a PR with a fix for this if you want.

**Comment by KKSzymanowski** [comment]
I just noticed it has already been fixed in a newer version. Sorry.

**Comment by ajuchacko91** [comment]
I was about to say the same #067483
