### ISSUE TITLE
Not triggerring Laravel model observer updated & deleted events

### ISSUE THREAD

**Issue by MERLIN-Flotilla** [laravel/framework#37993]
@acasar 

- Laravel Version: 8
- PHP Version: 7.3
- Database Driver & Version: pgsql-13

### Observer:
    class FileLogObserver
    {
     public function updated(FileLogs $fileLogs)
      {
        $fileChangeLogs = FileChangeLogs::firstWhere('fileId', $fileLogs->filedId);

        if ( !empty($fileChangeLogs)) {
            $fileChangeLogs->save([
                'logDetails' => '1 file updated',
            ]);
        }
    }
    }
### Controller:
    class FileLogController extends Controller
     {
        public function update(Request $request,$id){  
            
            $validator = Validator::make(
                $request->all(),
                [
                    
                    'orderId'    => 'required|integer',
                    'fileId'    => 'required|integer',
                    'status'    => 'required|string'
                ]
            );
    
            if ($validator->fails()) {
                return response()->json($validator->errors(), 400);
            }
    
            $data = FileLogs::find($id); 
            if($data){
               $data->orderId=$request->orderId;
               $data->fileId=$request->fileId;
               $data->status=$request->status;
               $data->update();
            
                return response()->json(['status'=>'success','StatusCode'=> 200,'message'=>'Successfully Updated','data'=>$data]);
            }
            else{
                return response()->json(['status'=>'Failed','message'=>'Update Failed'],400);
            }
        }
     }
### Description:
The created & retrieved methods are being properly triggered. However, the updated & deleted methods not triggered. Gone through many links & read that a reason can be becoz the update is not directly on the model. so, i tried like below in my controller. But that too doesn't trigger the `updated` event. Any help is much appreciated.

            $data=FileLogs::find($id)->update(['orderId'=>$request->orderId,'fileId'=>$request->fileId,'status'=>$request->status]);

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
