### ISSUE TITLE
CursorPaginate not working well with ResourceCollection

### ISSUE THREAD

**Issue by kamui545** [laravel/framework#37999]
- Laravel Version: 8.50.0
- PHP Version: 8.0.8
- Database Driver & Version: MySQL

### Description:

I noticed another issue while playing around with the cursor pagination. (please don't hate me 🙈)
If you actually use a `ResourceCollection` as output, the wrong cursor will be used for the pagination links.

For example if you're sorting on `pivot.id`, it will use `user.id`.

### Steps To Reproduce:

If you pull [my repo](https://github.com/kamui545/laravel-cursor) previously created for https://github.com/laravel/framework/pull/37915, there is a new route `/collection` with some debug outputs.

<img width="336" alt="Screen Shot 2021-07-13 at 22 02 22" src="https://user-images.githubusercontent.com/356978/125518370-18aa9c2c-2f96-403a-bf93-e2a354323caf.png">

In this case, it should always be `26` instead of `42`.

**Comment by driesvints** [comment]
Thanks @kamui545. I'll take a look later this week.

**Comment by driesvints** [comment]
Got it: https://github.com/laravel/framework/pull/38026
