### ISSUE TITLE
Blade components do not like double quotes inside attributes

### ISSUE THREAD

**Issue by mityukov** [laravel/framework#38003]
- Laravel Version: 8.44.0
- PHP Version: 8.0.7
- Database Driver & Version: Mysql 5.7

### Description:

There is a small difference in how attributes work on regular HTML elements and on blade components.
See the screenshot:
![image](https://user-images.githubusercontent.com/1751910/125595779-2ba327b6-6f44-42b2-b85c-2ec4732a44c6.png)

The worst thing here is the misleading error message, to my opinion. Spent some time figuring this out…

**Comment by driesvints** [comment]
This isn't supported by the parser. Try:

```blade
:href="url('accounts/'.$subdomain.'/settings?p=karta')"
```
