### ISSUE TITLE
[Router Bug] [8.50.0] Default Namespace into RouteServiceProvider

### ISSUE THREAD

**Issue by ajmeireles** [laravel/framework#38013]
- Laravel Version: 8.50.0
- PHP Version: 7.3
- Database Driver & Version: MariaDB 10.X

### Description:
When defining the API controllers namespace natively in RouteServiceProvider, only resource method is working fine without import the namespace for use. Below, some photos are attached:

1. RouteServiceProvider:
![image](https://user-images.githubusercontent.com/60591772/125691071-7c3400c8-4991-492f-bde2-a5aaa9e94c97.png)

2. TestController:
![image](https://user-images.githubusercontent.com/60591772/125691137-89b8eedf-8842-432e-8882-6d5524c80f0a.png)

3. API Routes:
![image](https://user-images.githubusercontent.com/60591772/125691191-24a2a39b-b192-471c-a355-0b813de69384.png)

4. Try to access ``http://localhost:8080/api/test:``
![image](https://user-images.githubusercontent.com/60591772/125691706-3d3a5082-e2ab-4eb7-9824-000c27e1313e.png)

---

## Default Method:

1. RouteServiceProvider:
![image](https://user-images.githubusercontent.com/60591772/125691595-3333a015-693d-40af-ac18-c9c5168eb002.png)

2. API Routes:
![image](https://user-images.githubusercontent.com/60591772/125691626-f4ffc526-cd36-4944-9ce3-92da0b44405e.png)

3. Try to access ``http://localhost:8080/api/test:``
![image](https://user-images.githubusercontent.com/60591772/125691664-20affb25-9b20-4a03-bb7f-d5f2d02d7be4.png)

### Steps To Reproduce:

1. Set a default namespace in App\Providers\RouteServiceProvider: ``'App\\Http\\Controllers\\Api'``
2. Create a new controller, like: ``TestController``, into: App\Http\Controllers\Api
3. Set the namespace of this controller: App\Http\Controllers\Api
4. Create a new route::get in routes/api.php without import the namespace
5. Try to acess: /api/test

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
