### ISSUE TITLE
Eloquent morphTo eager loading scoping

### ISSUE THREAD

**Issue by janverhulst** [laravel/framework#38014]
- Laravel Version: v8.49.2
- PHP Version: 8.0.8
- Database Driver & Version: postgres 12

### Description:

When trying to scope an eager loaded morphTo relationship, the scope function is executed on the model itself, instead of on the related model.

#### Invitation model
```
<?php
class Invitation extends Model
{
    /**
     * Scope a query to only include a user's accessible results.
     *
     * @param Builder $query
     * @param User $user
     * @return Builder
     */
    public function scopeAccessible(Builder $query, ?User $user): Builder
    {
        Log::debug('accessible invitation');
        return $query;
    }

    public function invitable()
    {
        return $this->morphTo('invitable');
    }
}

```

#### Project model

```
<?php
class Project extends Model
{
    /**
     * Scope a query to only include a user's accessible results.
     *
     * @param Builder $query
     * @param User|null $user
     * @return Builder
     */
    public function scopeAccessible(Builder $query, ?User $user): Builder
    {
        Log::debug('accessible project');
        if ($user->hasOneOfGlobalRoles([GlobalRole::SUPERADMIN])) {
            return $query;
        }
        return $query->whereIn('id', $user->projectMembershipIds);
    }
}
```

#### Query that's going wrong

```
$result = \App\Models\Invitation::with([
            'invitable' => function ($q) {
                $q->accessible(request()->user());
            }
        ])->findOrFail($itemId);
```

#### Result

I get a log saying "accessible invitation". I would expect a log of "accessible project" and the related query being scoped by the `scopeAccessible` scoping function on the Project model.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by janverhulst** [comment]
I'm sorry, but there's no way you could've actually read what I posted in under a minute and decided it's not a bug. It is an easily reproducible bug.

**Comment by derekmd** [comment]
There is a section in the documentation for this type of morph eager loading: https://laravel.com/docs/8.x/eloquent-relationships#constraining-eager-loading-of-morph-to-relationships

`MorphTo::constrain()` must be called inside the `with()` Closure for per-class scopes. Your example names the `Closure` argument `$q` but that object is an `MorphTo` instance, not the `Builder` query class. The given argument changes depending on the relationship type being eager-loaded.

```php
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\MorphTo;

App\Models\Invitation::with([
    'invitable' => function (MorphTo $morphTo) {
        $morphTo->constrain([
            Project::class => function (Builder $query) {
                $query->accessible(request()->user());
            },
        ]),
    },
])->findOrFail($itemId)
```

**Comment by janverhulst** [comment]
@derekmd Thank you so much for your input! I was unaware of this, seems to be what I'm looking for though! I'll check it out.
