### ISSUE TITLE
[ Console\Kernel ] ->bootstrap() method calls ->loadDeferredProviders() forcing that Deferrable stuff disabled

### ISSUE THREAD

**Issue by 6562680** [laravel/framework#38012]
- Laravel Version: latest, 14 Jul 21
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0

### Description:
[ Console\Kernel ] ->bootstrap() method calls ->loadDeferredProviders() forcing that Deferrable stuff disabled.
Disabling (via extending) this stuff causes artisan to fail cause of each command defines some deferred services.

Seems it is not a problem for console (actually - performance), but really i used boot() to load create services and configure it as a second step.

Look for my way:
1. i write model generator.
2. i run it via console - it deletes some model files to regenerate it.
3. next i try to run it again - it wont work cause of deleted files was dependencies of classes that was deferrable on "web" kernel, but by some reason immediate in console.

Additional stupidity is loading all the commands into memory on each command call instead of deferred resolving once called. If you need cache of defined commands - it should work like a router with cache adapter, somebody was very lazy creating "load all" button

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by 6562680** [comment]
idiot. it is a bug

**Comment by ajuchacko91** [comment]
Does't sound like it is

**Comment by 6562680** [comment]
Stupid support.
If programmer with 12 years of php skill sad "IT IS A BUG" you will ask "PLEASE EXPLAIN" and "i dont keep it in my mind and going home at 17.00"
