### ISSUE TITLE
[8.x] ModelNotFoundException on 'deleted', 'trashed' model events

### ISSUE THREAD

**Issue by shehi** [laravel/framework#38051]
- Laravel Version: One could say "all versions so far"
- PHP Version: Irrelevant
- Database Driver & Version: Irrelevant

### Description:
I am sure this problem has been mentioned countless times, but I still fail to craft a solution:
Model events `trashed` and `deleted`, naturally when passed to event listeners, cause `ModelNotFoundException`s if listener is run in some kind of async queue. I understand why.
What I don't understand is: why these events have been enabled in Broadcasting feature (which literally are event-based) and documented as if it is possible to broadcast them. There is `BroadcastsEvents` trait which extensively implement these events. In reality, it is absolutely impossible to process any of them in an async worker, because all of those jobs will fail to `restoreModel()`. If this is the case, why nowhere in documentation this (quite predominant) case isn't mentioned? Is it a documentation bug, or am I missing something here? And since these events can't be "listened-to"/"broadcast", why no "do-not-restore-from-db-upon-wakeup" logic/parameter etc wasn't implemented? I mean seriously, one doesn't really need to `restoreModel()` in quite many occasions, but just `__wakeup()`, and use the payload as it was queued. So what am I missing here?

This is rather an implementation question, than a possible bug report. Please do not close this issue and disregard it, coz posting it on stackexchange.com and hoping for a developer feedback is futile. I greatly appreciate any input from devs in advance!

CC: @taylorotwell , @GrahamCampbell

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by seobrain** [comment]
Hey guys,

I can also confirm that `BroadcastableModelEventOccurred` is not able to handle `deleted` and `trashed` models. 

The obvious reason is the usage of `Illuminate\Queue\SerializesModels` trait. By simply disabling this trait things start working properly, as expected. I might miss something, but is there a way to disable serialization for specific event types, e.g. `deleted`?

Thanks in advance!
