### ISSUE TITLE
Model factory encryption

### ISSUE THREAD

**Issue by kiwina** [laravel/framework#38050]
- Laravel Version: 8.5.022
- PHP Version: 8.0.6
- Database Driver & Version:

### Description:
A database encrypted attribute should be in plain text when using User::factory()->make();
This is not the case, it returns the value as encrypted text.
A plain User::make() works as expected

Steps To Reproduce:

-  add  `'username' => $this->faker->name(),` to the User factory
- add `$table->text('username');` to the user migration
- add ` 'username' => 'encrypted',` to the castable attributes
- migrate
- test

**Comment by ajuchacko91** [comment]
✅ 'secret' => $this->faker->name(), to the User factory
✅ $table->text('secret'); to the user migration
✅ 'secret
<img width="1308" alt="Screenshot 2021-07-19 at 6 29 40 PM" src="https://user-images.githubusercontent.com/13982547/126164036-3017104f-c3aa-431d-aebe-efb45355a013.png">
' => 'encrypted', to the castable attributes
✅ migrated

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kiwina** [comment]
Well should a factory make not be behaving exactly as the function on the model?

**Comment by kiwina** [comment]
> 
> 
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
>     * [Laracasts Forums](https://laracasts.com/discuss)
> 
>     * [Laravel.io Forums](https://laravel.io/forum)
> 
>     * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> 
>     * [Discord](https://discordapp.com/invite/KxwQuKb)
> 
>     * [Larachat](https://larachat.co)
> 
>     * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

"Please only use this issue tracker for reporting bugs"
if a factory dosn't behave like the class implementation it is a BUG!
