### ISSUE TITLE
artisan route:list command without sorting option throws undefined index error

### ISSUE THREAD

**Issue by Fedrosa** [laravel/framework#38065]
- Laravel Version: 8.50.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7

### Description:
When executing route:list command without sort option, method "sortRoutes" is called with null sort value and this results an undefined index error exception, this change was made https://github.com/laravel/framework/commit/32f21da8e0b231e55603ea4a2b1258409a2d1c3a#diff-5b8c5f56d305d5031a6925c7776edfa7d09d22dd178bdb1ae5c8276f87786765 , when " !== 'precedence'" added, and sort option is null if statement result true (null !== 'precedence')

### Steps To Reproduce:

execute php artisan route:list command without sort option

**Comment by ajuchacko91** [comment]
<img width="1418" alt="Screenshot 2021-07-19 at 7 01 47 PM" src="https://user-images.githubusercontent.com/13982547/126168486-da980ecd-ea9c-4789-a567-ee55382e97cd.png">
