### ISSUE TITLE
env variable with whitespace incorrect after upgrading from a previous version of PHP 8.0 to PHP 8.0.8

### ISSUE THREAD

**Issue by Olayiwola72** [laravel/framework#38073]
- Laravel Version: 8.48
- PHP Version: 8.08
- Database Driver & Version: MySql 8.0

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/40915435/126270912-d8cd035a-9315-433f-a573-afb9c83e65b8.png)

bootstrap/cache/config.php
![image](https://user-images.githubusercontent.com/40915435/126270583-eb705a2c-2ce4-4bba-b369-a01a062c2df0.png)

![image](https://user-images.githubusercontent.com/40915435/126270656-8cc3d144-5d3b-4fca-bf4e-6e007284a3c9.png)

![image](https://user-images.githubusercontent.com/40915435/126271472-592ecbf8-7af1-4184-a252-5300584063a5.png)

![image](https://user-images.githubusercontent.com/40915435/126271532-7ea34caf-cdb5-4a9b-8538-8e20291aef10.png)

**Comment by ajuchacko91** [comment]
Hi @Olayiwola72,

I was unable to reproduce issue.
Have you tried?```php artisan config:clear && php artisan config:cache```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
