### ISSUE TITLE
Implicit model binding parent and child not working as advertised unless you slug the param key

### ISSUE THREAD

**Issue by tarreislam** [laravel/framework#38094]
- Laravel Version: 8.51.0
- PHP Version: 7.4.1
- Database Driver & Version: mariadb latest

### Description:

Implicit model binding parent and child not working as advertised unless you slug the param key

According to [this](https://laravel.com/docs/8.x/routing#implicit-model-binding-scoping) and this [this](https://laravel.com/docs/8.x/routing#customizing-the-default-key-name) `{file}` should be the same as`{file:id}` but in my case its not

### Steps To Reproduce:

Context: freshly installed, no 3rd party magic

**table `files`**

| id | contact_id |
|:-:|:-:|
| 1 | 2 |
| 2 | 1 |

```php
// api.php
Route::delete('contacts/{contact}/files/{file}', [..., 'destroy'])
// Controller
public function destroy(Contact $contact, File $file) {
    $file->delete();
}
// Test
$response = $this->json('DELETE', '/api/contacts/1/files/1'); 
$response->assertNotFound(); // fails because the status was 200 and not 404

$response = $this->json('DELETE', '/api/contacts/1/files/2'); 
$response->assertOk(); // passes (expected)
```

however if I change `{file}` to `{file:id}` the assertion is successful

```php
// api.php
Route::delete('contacts/{contact}/files/{file:id}', [..., 'destroy'])
// Controller
public function destroy(Contact $contact, File $file) {
    $file->delete();
}
// Test
$response = $this->json('DELETE', '/api/contacts/1/files/1'); 
$response->assertNotFound(); // now passes!

$response = $this->json('DELETE', '/api/contacts/1/files/2'); 
$response->assertOk(); // passes (expected)
```

**Comment by christoph-kluge** [comment]
Can you post your Model definitions for `Contact` and `File` including the `files()` relationship inside `Contact`?

* How are your pimary keys defined?
* Do you use a custom routing key? (`getRouteKeyName`)

**Comment by tarreislam** [comment]
I leave everything to laravel magic, so there is nothing much going on so primary keys and routing keys are default, like i said in OT

### App\Models\Contact.php

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model {

    public function files()
    {
        return $this->hasMany(File::class);
    }
}
```

### App\Models\File.php

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model {

    public function contact()
    {
        return $this->belongsTo(Contact::class);
    }
}
```

**Comment by Jubeki** [comment]
This should be intended behaviour:
https://laravel.com/docs/8.x/routing#implicit-model-binding-scoping
