### ISSUE TITLE
Eloquent Model update() method unknown behaviour

### ISSUE THREAD

**Issue by tauseefsshah** [laravel/framework#38119]
- Laravel Version: 8.44.0
- PHP Version: 8.0.6
- Database Driver & Version: 10.4.19-MariaDB

### Description:
The `update()` method updates all entries in the table with the new input value if the `protected $primaryKey` value is set to `null` in the model.

### Steps To Reproduce:
Repository - [https://github.com/tauseefsshah/larvel-eloquent-update-bug](https://github.com/tauseefsshah/larvel-eloquent-update-bug)
Steps to reproduce in repository README.

**Comment by ajuchacko91** [comment]
yes, you're correct. I wonder why would any developer make ```$primaryKey as null``` I don't see any point in doing so

**Comment by tauseefsshah** [comment]
@ajuchacko91 Not all tables necessarily require a primary key e.g a pivot table. In such cases we can set the `$primaryKey` to `null` otherwise laravel throws a QueryException.

**Comment by ajuchacko91** [comment]
FYI: pivot models as extended from ```use Illuminate\Database\Eloquent\Relations\Pivot```

**Comment by tauseefsshah** [comment]
Figured what's causing this bug. What's happening is `firstWhere()` is returning the model instance and then when `update()` method is called it  adds a where clause to the query in which it sets the key for update but since  `$primaryKey` is set to `null`, it fails to add that where clause and hence the bug.

Here's the step wise complete internal functioning (`\Illuminate\Database\Eloquent\Model::class`):
1. `firstWhere()` returns the model instance.
2. `update()` method  internally calls the `fill()` method first and then `save()` method.
3. The `save()` method internally calls `performUpdate()` method which calls the `setKeysForSaveQuery()` method which basically adds a where clause to the query (In case of this bug it fails to do so).

I'm confused if it' an expected behaviour or not since we're just used to:
```
Model::findOrFail($id)->update([]);
Model::firstWhere($columnName, $value)->update([]);
```

**Comment by ajuchacko91** [comment]
see https://github.com/laravel/framework/issues/37979

**Comment by driesvints** [comment]
A primary key can never be null.
