### ISSUE TITLE
Password::min() on failure attribute is not translated

### ISSUE THREAD

**Issue by jva91** [laravel/framework#38120]
- Laravel Version: 8.51.0
- PHP Version: 8.0.1
- Database Driver & Version: MySQL 8.0.25

### Description:
When the min validation failed the attribute is not translated.

### Steps To Reproduce:
In request class:

    public function rules(): array
    {
        return [
            'new_password' => [Password::min(8)]
        ];
    }

    public function attributes(): array
    {
        return [
            'new_password' => trans('user.new_password')
        ];
    }

    protected function failedValidation(Validator $validator): void
    {
        throw new HttpResponseException(response()->json($validator->errors(), 422));
    }

Snippet of testcase:

    $response = $this->put(
            route('api.user.credentials.update'),
            [
                'new_password' => 'abcde',
            ]
        )->assertStatus(422);
        self::assertEquals(
            trans('validation.min.string', ['attribute' => trans('user.new_password'), 'min' => 8]),
            $response->json()['new_password'][0]
        );

Outcome of testcase:

    Failed asserting that two strings are equal.
    Expected :'Nieuw wachtwoord dient minimaal 8 karakters te bevatten.'
    Actual   :'New password dient minimaal 8 karakters te bevatten.'

**Comment by derekmd** [comment]
https://github.com/laravel/framework/pull/38114 merged today will fix that in next Tuesday's 8.x release.
