### ISSUE TITLE
Component not rendering value on error return

### ISSUE THREAD

**Issue by JohnWeidmann** [laravel/framework#38125]
- Laravel Version: 8.#.#
- PHP Version: 8.#.#
- Database Driver & Version:

### Description:

Component doesn't render attribute values on error return

### Steps To Reproduce:

text.blade.php component
```
 <input name="{{$name}}"  type="text"   placeholder="{{ $placeholder }}"  value="{{ old($name,$value) }}" 
    class="form-control @php echo $class; echo $sizor(); @endphp
    @error($name) is-invalid @enderror
    ">
@if($errors->has($name))
        @php $message = $errors->first($name); @endphp
        <x-form.validation-error 
            :message="$message"
        >
        </x-form.validation-error>
 @endif
```

```
class ValidationError extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public $message;
    public function __construct($message)
    {
       $this->message;
    }
```
validation-error.blade.php comp
```
<div>
    <!-- Waste no more time arguing what a good man should be, be one. - Marcus Aurelius -->
    <div class="invalid-feedback">{{$message}}</div>
</div>

```

HTML output - message not rendered. Also tried message="testing" same result

`<div class="invalid-feedback"></div>`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JohnWeidmann** [comment]
Thanks for the help. I posted it here because it seems like a library bug. Its a pretty straight forward test. I'll do some more digging. Maybe i am wrong.

**Comment by titantwentyone** [comment]
I think this may be related to a question I found on StackOverflow as I have come across the same issue: [https://stackoverflow.com/questions/66790126/cannot-access-blade-component-variables-inside-the-view](https://stackoverflow.com/questions/66790126/cannot-access-blade-component-variables-inside-the-view). The solutions there didn't work for me (i.e. clearing the cache, renaming classes etc) I'm at a loss as to why the prop isn't passed.
