### ISSUE TITLE
Laravel port changes automaically

### ISSUE THREAD

**Issue by nattive** [laravel/framework#38135]
- Laravel Version: 8.40
- PHP Version: PHP 8.0.3 (
- Database Driver & Version: Mysql

### Description:
 

I am facing a strange problem.  Whenever i try fetch some queries in the database, the Laravel port changes automatically.  I have reinstalled XAMPP, used "php -S localhost:8000 -t public/", Even when i use "--port". The server shuts down. 

I used ports like 5555, that I know no app is running on, Same problem

### Steps To Reproduce:

https://github.com/nattive/aswebapi.git 
![image](https://user-images.githubusercontent.com/53889328/126959301-e9d8c4fd-1c97-4a15-af5d-c969aa22ff82.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
