### ISSUE TITLE
`->cursorPaginate` and `getOriginalColumnNameForCursorPagination()`

### ISSUE THREAD

**Issue by DannyEndert** [laravel/framework#38138]
- Laravel Version: ^8.40
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:

https://github.com/laravel/framework/blob/cf26e13fa45ac5d9e64ddd0c830ed78e56e3fd4d/src/Illuminate/Database/Concerns/BuildsQueries.php#L308

Line No. 315 from the link above uses `$this->getOriginalColumnNameForCursorPagination($this, $column),`, accordingly line No. 308 should also use `$this->getOriginalColumnNameForCursorPagination($this, $previousColumn),`. Otherwise an alias might be used that does not exist in the outer scope, for example.

**Comment by driesvints** [comment]
Thanks, I've sent in a PR for this: https://github.com/laravel/framework/pull/38203
