### ISSUE TITLE
--realpath and --fullpath have no effect on make:migration

### ISSUE THREAD

**Issue by mxts** [laravel/framework#38141]
- Laravel Version: 8.51.0
- PHP Version: 7.4.21
- Database Driver & Version: MySQL 8.0.21

### Description:
--realpath is declared as a switch and does not accept values.
As a result, returned value is always false, caused by $this->option('realpath') always false.

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Console/Migrations/BaseCommand.php#L37-L40

--fullpath also faces the same issues and make:migration currently will never display the fullpath

https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php#L113-L115

### Steps To Reproduce:
All 3 commands below write to the same folder, which I think is incorrect, --fullpath also has no effect.
```
php artisan make:migration testmigration --path=/abcd
php artisan make:migration testmigration --path=/abcd --fullpath 
php artisan make:migration testmigration --path=/abcd --fullpath --realpath
```

I can file a PR. Thank you.

**Comment by ajuchacko91** [comment]
![Uploading Screenshot 2021-07-27 at 11.22.45 AM.png…]()

**Comment by mxts** [comment]
@ajuchacko91 yes?

**Comment by ajuchacko91** [comment]
<img width="1102" alt="Screenshot 2021-07-27 at 11 22 45 AM" src="https://user-images.githubusercontent.com/13982547/127112019-3ff9b073-740c-4c6c-8bf5-0341347ad2cc.png">

**Comment by mxts** [comment]
Ok, but doesn't work for me. I'm on a CentOS 8 guest running off Windows 10.

**Comment by driesvints** [comment]
Appreciating PR's, thanks.

**Comment by mxts** [comment]
I realized my issue, sharing here in case it helps someone

```PHP
# doesn't work
$this->call('make:migration', [
    'name' => "table_name",
    '--fullpath' => '',
    '--realpath' => '',
    '--path' => $path,
]);

# works
$this->call('make:migration', [
    'name' => "table_name",
    '--fullpath' => true,
    '--realpath' => true,
    '--path' => $path,
]);

```
