### ISSUE TITLE
Unknown option "--quiet"

### ISSUE THREAD

**Issue by FranciscoCaldeira** [laravel/framework#38140]
- Laravel Version: 8.49.2
- PHP Version: PHP 7.4.9
- Database Driver & Version: XXX

### Description:
By doing `php artisan test -h` it shows a list of options and one is like: `-q, --quiet Do not output any message`, but when I do `php artisan test --quiet ` it gives an error.

> Unknown option "--quiet"

And

> Unknown option "-q"

### Steps To Reproduce:
On console do `php artisan test --quiet` or `php artisan test -q` the output is the error.

**Comment by derekmd** [comment]
I just ran `php artisan test --quiet` on a fresh Laravel 8.51.0 app and it correctly turned verbose mode off and didn't output an `Unknown option "--quiet"` error. 

That error output is from "symfony/console" (used to run PHPUnit) so your app may be on a package version older than the latest stable suggested by:

https://github.com/laravel/framework/blob/7a82103f839d094ea007a233cfd8c00f678f271b/composer.json#L34

Remove any "symfony/console" line in the app composer.json file then run `composer update` and composer.lock should read:

```json
    "packages": [
        {
            "name": "symfony/console",
            "version": "v5.3.4",
```

**Comment by driesvints** [comment]
Thanks @derekmd

**Comment by JohnnyWalkerDesign** [comment]
I have this issue, even with a new installation of Laravel.

> composer global require laravel/installer
> 
> Changed current directory to /Users/you/.composer
> Using version ^4.2 for laravel/installer
> ./composer.json has been updated
> Running composer update laravel/installer
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 1 install, 0 updates, 0 removals
>   - Locking laravel/installer (v4.2.17)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>   - Downloading laravel/installer (v4.2.17)
>   - Installing laravel/installer (v4.2.17): Extracting archive
> Generating autoload files
> 15 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> ➜  16:18:07 ~/Dropbox/Work/SGL/TESTS laravel new empty-app
> 
>    _                               _
>   | |                             | |
>   | |     __ _ _ __ __ ___   _____| |
>   | |    / _` | '__/ _` \ \ / / _ \ |
>   | |___| (_| | | | (_| |\ V /  __/ |
>   |______\__,_|_|  \__,_| \_/ \___|_|
> 
> Creating a "laravel/laravel" project at "./empty-app"
> Installing laravel/laravel (v9.3.8)
>   - Downloading laravel/laravel (v9.3.8)
>   - Installing laravel/laravel (v9.3.8): Extracting archive
> Created project in /Users/johnnywalker/Dropbox/Work/SGL/TESTS/empty-app
> > @php -r "file_exists('.env') || copy('.env.example', '.env');"
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 107 installs, 0 updates, 0 removals
>   - Locking brick/math (0.10.2)
>   - Locking dflydev/dot-access-data (v3.0.1)
>   - Locking doctrine/inflector (2.0.5)
>   - Locking doctrine/instantiator (1.4.1)
>   - Locking doctrine/lexer (1.2.3)
>   - Locking dragonmantank/cron-expression (v3.3.2)
>   - Locking egulias/email-validator (3.2.1)
>   - Locking fakerphp/faker (v1.20.0)
>   - Locking filp/whoops (2.14.5)
>   - Locking fruitcake/php-cors (v1.2.0)
>   - Locking graham-campbell/result-type (v1.1.0)
>   - Locking guzzlehttp/guzzle (7.5.0)
>   - Locking guzzlehttp/promises (1.5.2)
>   - Locking guzzlehttp/psr7 (2.4.1)
>   - Locking hamcrest/hamcrest-php (v2.0.1)
>   - Locking laravel/framework (v9.31.0)
>   - Locking laravel/pint (v1.2.0)
>   - Locking laravel/sail (v1.16.0)
>   - Locking laravel/sanctum (v3.0.1)
>   - Locking laravel/serializable-closure (v1.2.2)
>   - Locking laravel/tinker (v2.7.2)
>   - Locking league/commonmark (2.3.5)
>   - Locking league/config (v1.1.1)
>   - Locking league/flysystem (3.5.2)
>   - Locking league/mime-type-detection (1.11.0)
>   - Locking mockery/mockery (1.5.1)
>   - Locking monolog/monolog (2.8.0)
>   - Locking myclabs/deep-copy (1.11.0)
>   - Locking nesbot/carbon (2.62.1)
>   - Locking nette/schema (v1.2.2)
>   - Locking nette/utils (v3.2.8)
>   - Locking nikic/php-parser (v4.15.1)
>   - Locking nunomaduro/collision (v6.3.0)
>   - Locking nunomaduro/termwind (v1.14.0)
>   - Locking phar-io/manifest (2.0.3)
>   - Locking phar-io/version (3.2.1)
>   - Locking phpoption/phpoption (1.9.0)
>   - Locking phpunit/php-code-coverage (9.2.17)
>   - Locking phpunit/php-file-iterator (3.0.6)
>   - Locking phpunit/php-invoker (3.1.1)
>   - Locking phpunit/php-text-template (2.0.4)
>   - Locking phpunit/php-timer (5.0.3)
>   - Locking phpunit/phpunit (9.5.25)
>   - Locking psr/container (2.0.2)
>   - Locking psr/event-dispatcher (1.0.0)
>   - Locking psr/http-client (1.0.1)
>   - Locking psr/http-factory (1.0.1)
>   - Locking psr/http-message (1.0.1)
>   - Locking psr/log (3.0.0)
>   - Locking psr/simple-cache (3.0.0)
>   - Locking psy/psysh (v0.11.8)
>   - Locking ralouphie/getallheaders (3.0.3)
>   - Locking ramsey/collection (1.2.2)
>   - Locking ramsey/uuid (4.5.1)
>   - Locking sebastian/cli-parser (1.0.1)
>   - Locking sebastian/code-unit (1.0.8)
>   - Locking sebastian/code-unit-reverse-lookup (2.0.3)
>   - Locking sebastian/comparator (4.0.8)
>   - Locking sebastian/complexity (2.0.2)
>   - Locking sebastian/diff (4.0.4)
>   - Locking sebastian/environment (5.1.4)
>   - Locking sebastian/exporter (4.0.5)
>   - Locking sebastian/global-state (5.0.5)
>   - Locking sebastian/lines-of-code (1.0.3)
>   - Locking sebastian/object-enumerator (4.0.4)
>   - Locking sebastian/object-reflector (2.0.4)
>   - Locking sebastian/recursion-context (4.0.4)
>   - Locking sebastian/resource-operations (3.0.3)
>   - Locking sebastian/type (3.2.0)
>   - Locking sebastian/version (3.0.2)
>   - Locking spatie/backtrace (1.2.1)
>   - Locking spatie/flare-client-php (1.3.0)
>   - Locking spatie/ignition (1.4.1)
>   - Locking spatie/laravel-ignition (1.5.0)
>   - Locking symfony/console (v6.0.12)
>   - Locking symfony/css-selector (v6.0.11)
>   - Locking symfony/deprecation-contracts (v3.0.2)
>   - Locking symfony/error-handler (v6.0.11)
>   - Locking symfony/event-dispatcher (v6.0.9)
>   - Locking symfony/event-dispatcher-contracts (v3.0.2)
>   - Locking symfony/finder (v6.0.11)
>   - Locking symfony/http-foundation (v6.0.12)
>   - Locking symfony/http-kernel (v6.0.12)
>   - Locking symfony/mailer (v6.0.12)
>   - Locking symfony/mime (v6.0.12)
>   - Locking symfony/polyfill-ctype (v1.26.0)
>   - Locking symfony/polyfill-intl-grapheme (v1.26.0)
>   - Locking symfony/polyfill-intl-idn (v1.26.0)
>   - Locking symfony/polyfill-intl-normalizer (v1.26.0)
>   - Locking symfony/polyfill-mbstring (v1.26.0)
>   - Locking symfony/polyfill-php72 (v1.26.0)
>   - Locking symfony/polyfill-php80 (v1.26.0)
>   - Locking symfony/polyfill-php81 (v1.26.0)
>   - Locking symfony/polyfill-uuid (v1.26.0)
>   - Locking symfony/process (v6.0.11)
>   - Locking symfony/routing (v6.0.11)
>   - Locking symfony/service-contracts (v3.0.2)
>   - Locking symfony/string (v6.0.12)
>   - Locking symfony/translation (v6.0.12)
>   - Locking symfony/translation-contracts (v3.0.2)
>   - Locking symfony/uid (v6.0.11)
>   - Locking symfony/var-dumper (v6.0.11)
>   - Locking theseer/tokenizer (1.2.1)
>   - Locking tijsverkoyen/css-to-inline-styles (2.2.5)
>   - Locking vlucas/phpdotenv (v5.4.1)
>   - Locking voku/portable-ascii (2.0.1)
>   - Locking webmozart/assert (1.11.0)
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Package operations: 107 installs, 0 updates, 0 removals
>   - Downloading laravel/pint (v1.2.0)
>   - Installing doctrine/inflector (2.0.5): Extracting archive
>   - Installing doctrine/lexer (1.2.3): Extracting archive
>   - Installing symfony/polyfill-ctype (v1.26.0): Extracting archive
>   - Installing webmozart/assert (1.11.0): Extracting archive
>   - Installing dragonmantank/cron-expression (v3.3.2): Extracting archive
>   - Installing symfony/deprecation-contracts (v3.0.2): Extracting archive
>   - Installing psr/container (2.0.2): Extracting archive
>   - Installing fakerphp/faker (v1.20.0): Extracting archive
>   - Installing symfony/polyfill-mbstring (v1.26.0): Extracting archive
>   - Installing symfony/http-foundation (v6.0.12): Extracting archive
>   - Installing fruitcake/php-cors (v1.2.0): Extracting archive
>   - Installing psr/http-message (1.0.1): Extracting archive
>   - Installing psr/http-client (1.0.1): Extracting archive
>   - Installing ralouphie/getallheaders (3.0.3): Extracting archive
>   - Installing psr/http-factory (1.0.1): Extracting archive
>   - Installing guzzlehttp/psr7 (2.4.1): Extracting archive
>   - Installing guzzlehttp/promises (1.5.2): Extracting archive
>   - Installing guzzlehttp/guzzle (7.5.0): Extracting archive
>   - Installing laravel/pint (v1.2.0): Extracting archive
>   - Installing voku/portable-ascii (2.0.1): Extracting archive
>   - Installing symfony/polyfill-php80 (v1.26.0): Extracting archive
>   - Installing phpoption/phpoption (1.9.0): Extracting archive
>   - Installing graham-campbell/result-type (v1.1.0): Extracting archive
>   - Installing vlucas/phpdotenv (v5.4.1): Extracting archive
>   - Installing symfony/css-selector (v6.0.11): Extracting archive
>   - Installing tijsverkoyen/css-to-inline-styles (2.2.5): Extracting archive
>   - Installing symfony/var-dumper (v6.0.11): Extracting archive
>   - Installing symfony/polyfill-uuid (v1.26.0): Extracting archive
>   - Installing symfony/uid (v6.0.11): Extracting archive
>   - Installing symfony/routing (v6.0.11): Extracting archive
>   - Installing symfony/process (v6.0.11): Extracting archive
>   - Installing symfony/polyfill-php72 (v1.26.0): Extracting archive
>   - Installing symfony/polyfill-intl-normalizer (v1.26.0): Extracting archive
>   - Installing symfony/polyfill-intl-idn (v1.26.0): Extracting archive
>   - Installing symfony/mime (v6.0.12): Extracting archive
>   - Installing symfony/service-contracts (v3.0.2): Extracting archive
>   - Installing psr/event-dispatcher (1.0.0): Extracting archive
>   - Installing symfony/event-dispatcher-contracts (v3.0.2): Extracting archive
>   - Installing symfony/event-dispatcher (v6.0.9): Extracting archive
>   - Installing psr/log (3.0.0): Extracting archive
>   - Installing egulias/email-validator (3.2.1): Extracting archive
>   - Installing symfony/mailer (v6.0.12): Extracting archive
>   - Installing symfony/error-handler (v6.0.11): Extracting archive
>   - Installing symfony/http-kernel (v6.0.12): Extracting archive
>   - Installing symfony/finder (v6.0.11): Extracting archive
>   - Installing symfony/polyfill-intl-grapheme (v1.26.0): Extracting archive
>   - Installing symfony/string (v6.0.12): Extracting archive
>   - Installing symfony/console (v6.0.12): Extracting archive
>   - Installing symfony/polyfill-php81 (v1.26.0): Extracting archive
>   - Installing ramsey/collection (1.2.2): Extracting archive
>   - Installing brick/math (0.10.2): Extracting archive
>   - Installing ramsey/uuid (4.5.1): Extracting archive
>   - Installing psr/simple-cache (3.0.0): Extracting archive
>   - Installing nunomaduro/termwind (v1.14.0): Extracting archive
>   - Installing symfony/translation-contracts (v3.0.2): Extracting archive
>   - Installing symfony/translation (v6.0.12): Extracting archive
>   - Installing nesbot/carbon (2.62.1): Extracting archive
>   - Installing monolog/monolog (2.8.0): Extracting archive
>   - Installing league/mime-type-detection (1.11.0): Extracting archive
>   - Installing league/flysystem (3.5.2): Extracting archive
>   - Installing nette/utils (v3.2.8): Extracting archive
>   - Installing nette/schema (v1.2.2): Extracting archive
>   - Installing dflydev/dot-access-data (v3.0.1): Extracting archive
>   - Installing league/config (v1.1.1): Extracting archive
>   - Installing league/commonmark (2.3.5): Extracting archive
>   - Installing laravel/serializable-closure (v1.2.2): Extracting archive
>   - Installing laravel/framework (v9.31.0): Extracting archive
>   - Installing laravel/sail (v1.16.0): Extracting archive
>   - Installing laravel/sanctum (v3.0.1): Extracting archive
>   - Installing nikic/php-parser (v4.15.1): Extracting archive
>   - Installing psy/psysh (v0.11.8): Extracting archive
>   - Installing laravel/tinker (v2.7.2): Extracting archive
>   - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
>   - Installing mockery/mockery (1.5.1): Extracting archive
>   - Installing filp/whoops (2.14.5): Extracting archive
>   - Installing nunomaduro/collision (v6.3.0): Extracting archive
>   - Installing sebastian/version (3.0.2): Extracting archive
>   - Installing sebastian/type (3.2.0): Extracting archive
>   - Installing sebastian/resource-operations (3.0.3): Extracting archive
>   - Installing sebastian/recursion-context (4.0.4): Extracting archive
>   - Installing sebastian/object-reflector (2.0.4): Extracting archive
>   - Installing sebastian/object-enumerator (4.0.4): Extracting archive
>   - Installing sebastian/global-state (5.0.5): Extracting archive
>   - Installing sebastian/exporter (4.0.5): Extracting archive
>   - Installing sebastian/environment (5.1.4): Extracting archive
>   - Installing sebastian/diff (4.0.4): Extracting archive
>   - Installing sebastian/comparator (4.0.8): Extracting archive
>   - Installing sebastian/code-unit (1.0.8): Extracting archive
>   - Installing sebastian/cli-parser (1.0.1): Extracting archive
>   - Installing phpunit/php-timer (5.0.3): Extracting archive
>   - Installing phpunit/php-text-template (2.0.4): Extracting archive
>   - Installing phpunit/php-invoker (3.1.1): Extracting archive
>   - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
>   - Installing theseer/tokenizer (1.2.1): Extracting archive
>   - Installing sebastian/lines-of-code (1.0.3): Extracting archive
>   - Installing sebastian/complexity (2.0.2): Extracting archive
>   - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
>   - Installing phpunit/php-code-coverage (9.2.17): Extracting archive
>   - Installing phar-io/version (3.2.1): Extracting archive
>   - Installing phar-io/manifest (2.0.3): Extracting archive
>   - Installing myclabs/deep-copy (1.11.0): Extracting archive
>   - Installing doctrine/instantiator (1.4.1): Extracting archive
>   - Installing phpunit/phpunit (9.5.25): Extracting archive
>   - Installing spatie/backtrace (1.2.1): Extracting archive
>   - Installing spatie/flare-client-php (1.3.0): Extracting archive
>   - Installing spatie/ignition (1.4.1): Extracting archive
>   - Installing spatie/laravel-ignition (1.5.0): Extracting archive
> 51 package suggestions were added by new dependencies, use `composer suggest` to see details.
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
>    INFO  Discovering packages.  
> 
>   laravel/sail .......................................................... DONE
>   laravel/sanctum ....................................................... DONE
>   laravel/tinker ........................................................ DONE
>   nesbot/carbon ......................................................... DONE
>   nunomaduro/collision .................................................. DONE
>   nunomaduro/termwind ................................................... DONE
>   spatie/laravel-ignition ............................................... DONE
> 
> 81 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> > @php artisan vendor:publish --tag=laravel-assets --ansi --force
> 
>    INFO  No publishable resources for tag [laravel-assets].  
> 
> > @php artisan key:generate --ansi
> 
>    INFO  Application key set successfully.  
> 
>    INFO  Application ready! Build something amazing.
> 
> ➜  16:18:34 ~/Dropbox/Work/SGL/TESTS cd empty-app 
> ➜  16:18:36 ~/Dropbox/Work/SGL/TESTS/empty-app php artisan test -q
> PHPUnit 9.5.25 #StandWithUkraine
> 
> Unknown option "-q"
