### ISSUE TITLE
Method Illuminate\Http\JsonResponse::statusMessageWithValidationErrors does not exist.

### ISSUE THREAD

**Issue by ozanhazer** [laravel/framework#38159]
- Laravel Version: 8.52.0
- PHP Version: 8.0.8
- Database Driver & Version:

### Description:

BadMethodCallException is thrown when `assertStatus(422)` is used. There's a leftover after refactoring done in #38088 :

```
    protected function statusMessageWithException($expected, $actual, $exception)
    {
        if ($exception instanceof ValidationException) {
            return $this->statusMessageWithValidationErrors($expected, $actual, $exception);
        }
```

Apparently `statusMessageWithValidationErrors` method was removed but I think forgotten here..

### Steps To Reproduce:

Create a unit test and check for 422 status:

` $this->post('/some-endpoint', ['foo' => 'bar'])->assertStatus(422);`

**Comment by themsaid** [comment]
fixed https://github.com/laravel/framework/commit/cde36626376e014390713ab03a01eb4dfe6488ce
