### ISSUE TITLE
Carbon diffForHumans function returning wrong string

### ISSUE THREAD

**Issue by ehtishamHK95** [laravel/framework#38155]
- Laravel Version:  8.52.0
- PHP Version: 7.3.29
- Database Driver & Version: 10.4.20-MariaDB (XAMPP 7.3.29-1-VC15)

### Description:
diffForHumans() function returning string "ago" when parsing any date.
Even Carbon::now()->diffForHumans() returning the same ("ago").

`public function timestamp()
    {
        return Carbon::parse($this->created_at)->diffForhumans();
    }`

### Steps To Reproduce:

`Carbon::now()->diffForhumans();
`

Tested with both dd and return.
P.S: It was working fine before I moved the project to a newer machine.
![1](https://user-images.githubusercontent.com/87918502/127219339-24f2dac2-9db2-4dbc-95ca-8ec369375d59.PNG)
![2](https://user-images.githubusercontent.com/87918502/127219347-8c807bdf-03d1-4f83-9366-55aa9722ed1b.PNG)

**Comment by vladislavtkachenko** [comment]
`Carbon::parse($this->created_at)->diffForhumans(now());`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
