### ISSUE TITLE
Laravel subdomain routing not working as expected

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [laravel/framework#38150]
- Laravel Version: 8.40
- PHP Version: 8.0.8
- Database Driver & Version: ((Not relevant for this issue))

### Description:

The subdomain routing feature in Laravel isn't working as expected.
I have three routing files inside `routes` folder:

- web.php
- api.php
- admin.php

I've registered the file `admin.php` inside `boot()` method of `RouteServiceProvider` as following:

```
public function boot() {
    $this->configureRateLimiting();

    $this->routes(function () {
        Route::domain("admin." . env("APP_URL"))
            ->namespace($this->namespace)
            ->group(base_path("routes/admin.php"));

        Route::domain("api." . env("APP_URL"))
            ->middleware("api")
            ->namespace($this->namespace)
            ->group(base_path("routes/api.php"));

        Route::middleware("web")
            ->namespace($this->namespace)
            ->group(base_path("routes/web.php"));
    });
}
```

Let's say i've defined the following route in `web.php`:

```
Route::get("test", function() {
    return "Hello from website route";
});
```
If i try to access this route using `mywebsite.com/test` it acts like expected. 
However, if i try to access the link `admin.mywebsite.com/test` it would still some how falls back to `mywebsite.com/test` and give the exact same output.
I'm expecting it to throw 404.

### Steps To Reproduce:

1. Create subdomain group
2. Define a route outside the subdomain
3. Try to access the defined route from within the subdomain

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Eyad-Mohammed-Osama** [comment]
In case someone came here in future for the same problem, the solution would be to add a `domain()` for the web routes and pass it `env("APP_URL")` .
The documentation doesn't mention obviously (or perhaps at all) that the routes defined inside `web.php` are available to all subdomains, and neither it does provide enough information about subdomain routing.

```
Route::middleware("web")
   ->domain(env("APP_URL")) // Add this line
   ->namespace($this->namespace)
   ->group(base_path("routes/web.php"));
```

Please see this question for further info: https://stackoverflow.com/questions/68547094/laravel-subdomain-routing-not-working-as-expected/68548067#68548067

**Comment by brunogaspar** [comment]
@Eyad-Mohammed-Osama Just a FYI, the  `env` helper should only be used within the config files.

So on your routes and everywhere else within your application, you should use the `config` helper.

Main reason for it is that, if you cache the config by using `php artisan config:cache`, the `env` helper will no longer work as expected, and your application will be on a broken state.

**Comment by Eyad-Mohammed-Osama** [comment]
@brunogaspar I've almost forgot this point
Thank you very much for drawing my attention to this scenario
