### ISSUE TITLE
cache folder create by root

### ISSUE THREAD

**Issue by sedattcom** [laravel/framework#38160]
- Laravel Version: 8.x
- PHP Version: 7.4.21
- Database Driver & Version:

### Description:
Sometimes cache folder create by root user and then i got an error as "failed to open stream: Permission denied"
![Screen Shot 2021-07-28 at 11 01 24](https://user-images.githubusercontent.com/3106412/127286495-24e33cb8-c138-4f9c-b5b0-163136b29f25.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
