### ISSUE TITLE
Nested array in request...

### ISSUE THREAD

**Issue by VictorPullzz** [laravel/framework#38169]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: mysql 5.7

### Description:
This really strange bug, when I send to laravel nested array. For example:
![image](https://user-images.githubusercontent.com/23406402/127477589-f280f73b-e372-49d6-ba32-4a8ddae9e7e4.png)
![image](https://user-images.githubusercontent.com/23406402/127477816-5f6041b5-bc19-4fd0-97cc-6d1462c468b2.png)

And when I try to display all the data ``` dd($request->all()); ``` I get this: 
![image](https://user-images.githubusercontent.com/23406402/127478029-d1c78af7-75b6-4f3e-bdf6-d06a710abea2.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
