### ISSUE TITLE
Missing error message when aborting a transaction (with postgres)

### ISSUE THREAD

**Issue by jacob418** [laravel/framework#38172]
- Laravel Version: 8.59.2 (Sail 1.8.4)
- PHP Version: 8.0.8
- Database Driver & Version: 
  - `sail php -r "echo(phpversion('pgsql'));"` -> 8.0.8
  - Postgres: 13.3-1.pgdg100+1

### Description:

When a transaction is aborted due exception the following PGSQL error message is written to the logs:

```
[2021-07-29 12:09:18] local.ERROR: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block (SQL: select * from "trainings" where "trainings"."id" = 0a959b11-52a3-4f5f-b92b-0daf00e2bd4a limit 1) {"userId":"f013bd08-646f-45fe-bcdb-859fe00e27af","exception":"[object] (Illuminate\\Database\\QueryException(code: 25P02): SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block (SQL: select * from \"trainings\" where \"trainings\".\"id\" = 0a959b11-52a3-4f5f-b92b-0daf00e2bd4a limit 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(652): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(360): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2351): Illuminate\\Database\\Connection->select()
// -- snip...
```

However this is not useful for debugging since it does not provide information about the error itself. It seems like while handling the original exception it does not get logged and is replaced by the `SQLSTATE[25P02]` exception, dropping the information about the original error. The only way to find out what went wrong is to follow the transaction step by step, wait for the exception to occur and then read the message with the debugger. The SQL statement within the error log is not the failing one, it was executed with the expected result and without error! The Exception message found with the debugger:

```
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "appointment_module" does not exist
LINE 1: select * from "appointment_module" where "appointment_module...
                      ^ (SQL: select * from "appointment_module" where "appointment_module"."appointment_id" = 81e18055-fcb5-49ef-8829-bac8fa5d87e6)
```
*(I ran into this because I forgot to migrate ;P )*

In my opinion the original message should also be included/logged somehow for debugging reasons. That's why I consider this a bug though it is not stopping an error-free app from working properly.

*If I don't remember it wrong MySQL will include the error that failed the transaction into the transaction error message, making this less problematic but I'm not sure about this. Also I have not tested it for other RDBMS like Oracle/MSSQL.*

### Steps To Reproduce:

1. Create new Laravel project and configure it for PGSQL
2. Create a transaction with `\DB::beginTRansaction();`
3. Execute a failing SQL statement like access to a non-existing table
4. Commit the transaction via `\DB::commit();`
5. Trigger execution
4. Try to determine the error that failed the transaction from the logs

**Comment by driesvints** [comment]
Thanks. We'd definitely welcome PR's for this.

**Comment by jacob418** [comment]
> Thanks. We'd definitely welcome PR's for this.

But why immediate closing? A mistake?

I never digged that deep into Laravels DB-Code but I can certainly give it a try.

**Comment by jacob418** [comment]
Though this issue has been closed without reason, for anyone stumbling upon this via google this is the solution I came up with:

Insert this code 

```php
if (DB::transactionLevel() > 0 &&
    $this->getDriverName() === 'pgsql'
) {
     app(Handler::class)->report(new QueryException(
        $query, $this->prepareBindings($bindings), $e
     ));
}
```

just before
```php
throw new QueryException(
    $query, $this->prepareBindings($bindings), $e
);
```

in `vendor/laravel/framework/src/Illuminate/Database/Connection.php::runQueryCallback` (L 672)

Obviously editing vender files can be a really bad idea. In this case I can accept it, since it has no impact on production systems.

**Comment by aliwesome** [comment]
@jacob418 I'm facing this issue right now, I tried your approach but it didn't solve the issue. do you have any new ideas about that problem?
