### ISSUE TITLE
Mail Driver / Transport Prerequisites: SES and Guzzle version clash

### ISSUE THREAD

**Issue by sebastiansulinski** [laravel/framework#38184]
- Laravel Version: 8.52.0
- PHP Version: 8.0.8

### Description:

Installing guzzle followed by aws sdk throws error:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - aws/aws-sdk-php[3.186.0, ..., 3.186.2] require guzzlehttp/psr7 ^1.7.0 -> found guzzlehttp/psr7[1.7.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires aws/aws-sdk-php ^3.186 -> satisfiable by aws/aws-sdk-php[3.186.0, 3.186.1, 3.186.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Steps To Reproduce:

As per instructions [Mail](https://laravel.com/docs/8.x/mail#driver-prerequisites)

```bash
composer require guzzlehttp/guzzle
```

followed by

```bash
composer require aws/aws-sdk-php
```

It works fine if you only install aws sdk without guzzle first.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
