### ISSUE TITLE
Blueprint according to [8.x] Add ignoreTrashed to Unique validation rule

### ISSUE THREAD

**Issue by Eskaaa** [laravel/framework#38180]
- Laravel Version: 8.52.X

### Description:

With this [PR - [8.x] Add ignoreTrashed to Unique validation rule](https://github.com/laravel/framework/pull/38124) we get a unique validation rule, that takes care of soft deleted records.

But personally I miss the adaptation to the database migrations. 

There is a risk of database errors here if a unique index is set on several columns and the softDeletes are not included at this point. The validation with Laravel works as expected, but the data record cannot be created in the database.

The simplest solution would of course be to specify the deleted_at column in the ```unique```-call. But a generic approach might increase usability.

### Steps To Reproduce:

Imagine a migration like this:

```php

    protected function defineTableSchema(
        Blueprint $table
    ): void {
        $table->id();

        $table->string('name');
        $table->string('airline');

        $table->softDeletes();

        $table->unique(['name', 'another'], $indexName);
    }

```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
