### ISSUE TITLE
Laravel web route resource methods like show must accepts integer I think but it accepts string

### ISSUE THREAD

**Issue by Mohsen-Amani** [laravel/framework#38195]
- Laravel Version: 8.49.2
- PHP Version: 8.0.7
- Database Driver & Version:  10.5.10-MariaDB

### Description:
I faced an issue while creating routes for my project, where I had to have two resource routes _devices.types_ and _devices.types.properties_ the second resource route had a portion of its URL similar to first resource route,
while I was trying to access the second route index method It was executing the show of the first method of first route for me 

`Route::resource('devices/types', App\Http\Controllers\DeviceTypesController::class);`
 `Route::resource('devices/types/properties', App\Http\Controllers\DeviceTypesPropertiesController::class);`

problem was that by accessing _devices/types/properties_ URL it was going to _devices/types_ URL assuming reset of the URL as parameters for first resource route causing show method of first resource route to be called;

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
