### ISSUE TITLE
Api route fallback issue

### ISSUE THREAD

**Issue by gihanrangana** [laravel/framework#38191]
- Laravel Version: 8.40
- PHP Version: 7.4.3
- Database Driver & Version: Mysql  15.1

### Description:
i'm trying to add route fallback to api routes for handle the 404 routes error, but my Route::falback() is not fired when i navigate to the 404 route

this is my api.php 

```
Route::fallback(function () {
    return response()->json([
        'message' => 'Page Not Found. If error persists, contact info@website.com'
    ], 404);
});
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
