### ISSUE TITLE
Count on model eloquent builder don't provide proper value.

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#38198]
- Laravel Version: 8.52.0
- PHP Version: 8.0.9
- Database Driver & Version: pgsql & 13.3

### Description:
When try make Eloquent count on query, results isn't proper.

### Steps To Reproduce:
```php
$query = Model::query()->getModel()->setTable('o')
    ->from('orders AS o')
    ->select(['columns'])
    ->leftJon() // some relation
    ->where('status', 100)
    ->when() // some condition
    ->distinct()
    ->groupBy(['columns']);

echo $query->count(); // 1 // this is described right here: https://laravel.com/docs/8.x/eloquent#retrieving-aggregates
echo $query->get()->count(); // 16001 // it takes RAM consumption, but value is proper.
```
when I change select to:
```php
->select(DB::raw('COUNT(o.id AS some_count)')) // or
->select(DB::raw('COUNT(*)'))
```
it gives for me 9 models with one attribute with value 9. Wired.

That error is commonly mentioned in the Internet.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by LocalHeroPro** [comment]
Bug as always and you are closing.
