### ISSUE TITLE
Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by Davidnadejdin** [laravel/framework#38201]
- Laravel Version: 8.52.0
- PHP Version: 7.4.18
- Database Driver & Version: pdo_sqlite

### Description:
If I try to add a not null column to the next migration after the table has already been created, I get this error. In MySQL, this works without a problem.
```
Schema::create('users', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->string('email')->unique();
    $table->string('password');
    $table->rememberToken();
    $table->timestamps();
});
```

```
Schema::table('users', function (Blueprint $table) {
    $table->timestamp('next_payment_at');
});
```

### Steps To Reproduce:
1. Create any table
2. Add not null column to table, in next migration
3. Run migrations

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Davidnadejdin** [comment]
@driesvints This problem only occurs on sqlite. Any new column to an existing table, even if there is no data in it, raises this error. It turns out that we have to make the columns nullable, only in order to support sqlite in our project, for example, to run tests. It seemed to me to be a bug. As a solution to the problem, make all new columns nullable at the driver level?
