### ISSUE TITLE
Many-to-many pivot updates cause an error with numeric string primary keys in MySQL strict mode

### ISSUE THREAD

**Issue by zesbr** [laravel/framework#38207]
- Laravel Version: 8.52.0
- PHP Version: 7.4.21
- Database Driver & Version: MySQL (strict mode)

### Description:

Method `updateExistingPivot` throws `QueryException` with message `SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value` in strict mode, when the given IDs are numeric strings that are read from the keys of an associative array. Method `parseId()` of `InteractWithPivot` trait should (probably) return casted key value to make sure that the related keys are correctly casted. 

I can create a pull request if the issue is considered worth fixing.

#### Example

Let's say our schema would look like this:

```
posts
    id - string
    title - string
    content - text

tags
    id - string
    name - string

post_tag
    post_id - string
    tag_id - string
    order - integer
```

and we would execute the following code.

```php
<?php

use App\Models\Post;
use App\Models\Tag;

// Create a new post.
$post = Post::create([
    'title' => 'Lorem ipsum dolor sit amet',
    'content' => '...'
]);

// Create a new tag with numeric string as id.
$tagWithNumericStringId = Tag::create([
    'id' => '1',
    'name' => 'Foo'
]);

// Create a new tag with uuid as id.
$tagWithUuidId = Tag::create([
    'id' => '629b1c4e-4de9-411d-a108-88c1dd8556ac',
    'name' => 'Bar'
]);

// Attach tags to post. This works fine!
$post->tags()->attach([
    $tagWithUuidId->id => ['order' => 1],
    $tagWithNumericStringId->id => ['order' => 2],
]);

//  Update the order in pivot table. Exception is thrown!!!
$post->tags()->sync([
    $tagWithNumericStringId->id => ['order' => 1],
    $tagWithUuidId->id => ['order' => 2],
]);

// "SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '629b1c4e-4de9-411d-a108-88c1dd8556ac'
// (SQL: update `post_tag` set `order` = 2 where `post_tag`.`post_id` = 49463754-d8e8-4d0a-933b-81e596e11949 and `tag_id` in (1))
```
#### Reason

I believe the issue is caused by the `parseId()` method of `InteractsWithPivot` trait that does not cast given key(s) if they were read from key list of an associative array. The PHP itself will cast valid numeric string keys to integers as mentioned in the [docs](https://www.php.net/manual/en/language.types.array.php) which is why they should be manually casted based on the defined type of the related key.

#### Why this is important

Let's assume that some years ago we had established our database using auto-incrementing primary keys and now, we would like to change our primary keys to be UUIDs instead. To do this, we would alter the type of "id" columns from `INTEGER` to `VARCHAR(36)` in our database. Since our database is already in production and primary keys are being referenced throughout the database (possible on third-party as well), we would like to avoid changing the values of our IDs and rather leave them as numeric strings (eg.` "1"`).

Our code calls `sync()` and `updateExistingPivot()` extensively which currently causes frequent failures since our new schema can have mixed numeric strings and UUIDs as related keys. The hotfix is to disable the strict mode from MySQL driver or refactor the code where `sync()` and `updateExistingPivot()` are being called, but we would prefer keeping our codebase intact.

### Steps To Reproduce:

[Here's](https://github.com/zesbr/laravel-bug-report) a link to bug report demo that includes instructions to reproduce the issue.

**Comment by driesvints** [comment]
That's something we don't support sorry. Either use string based primary keys or integer ones but not a combination of both.

**Comment by zesbr** [comment]
@driesvints Thank you for the response!

Nevertheless, I feel this is somewhat unexpected behaviour from Eloquent. Methods `sync()` and `updateExistingPivot()` are the only operations that will fail on this I believe, since they accept attributes mapped by an ID.

Shouldn't string primary key be allowed to have a numeric value if the unique constraint stays unviolated?

**Comment by JieAnthony** [comment]
@zesbr I also encountered this problem, how did you solve it?
