### ISSUE TITLE
[Queue] Model serialization does not consider selected columns from the original query 

### ISSUE THREAD

**Issue by ahmedash95** [laravel/framework#38205]
- Laravel Version: 5.7
- PHP Version: 7.4
- Database Driver & Version: Mysql 7

### Description:
Custom attributes in models get lost after serialization for the queue.
```
$users = Users::select('email')->where('is_active', 0)->get();

DeactivationReminderJob::dispatch($users);
```

When the job runs in the worker. Unserialize method will execute the query like
```mysql
select * from users where is_active = 0

// instead of 

select emails from users where is_active = 0
```

### Expected behavior

Expected behaviour is that the serializer should respect the selected columns

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
