### ISSUE TITLE
Missing Dispatchable trait on Laravel auth events

### ISSUE THREAD

**Issue by michaloravec** [laravel/framework#38214]
- Laravel Version: 8.28.1
- PHP Version: 7.3.5
- Database Driver & Version: 5.7.26

### Description:

All Laravel auth events doesn't have `Dispatchable` trait.

This problem is on all version of Laravel, of course on all Laravel Auth events.

### Steps To Reproduce:

When do you call  

```
Registered::dispatch($user = $this->create($request->all()));
```

You get an error: _Call to undefined method Illuminate\Auth\Events\Registered::dispatch()_.

Everything is alright when you dispatch an event with the `event` helper.

```
event(new Registered($user = $this->create($request->all())));
```

**Comment by driesvints** [comment]
Feel free to attempt a PR if you want. Thanks
