### ISSUE TITLE
ShouldBeUnique doesn't work with scheduled task "job()"

### ISSUE THREAD

**Issue by thkarcher** [laravel/framework#38219]
Hi there,

I found the ShouldBeUnique interface on a job not working if the job gets started by the task scheduler. My intention is to let a job run fairly often but avoid "overtaking", thus not even dispatching the following run if the previous is still running.

To reproduce, create a basic job:

```
class TestJob implements ShouldQueue, ShouldBeUnique
{
... // sometimes long running job
}
```

... and schedule it in app/Console/Kernel.php:

```
class Kernel extends ConsoleKernel
{
    protected function schedule(Schedule $schedule)
    {
        $schedule->job(new TestJob)->everyMinute();
    }
}
```

If the previous instance is still running, the task scheduler still dispatches the job; a congestion occurs.

If I instead schedule the job as follows, ShouldBeUnique works as intended and documented:

```
$schedule->call(function () { TestJob::dispatch(); }
		)->name('TestJob')->everyMinute();
```

If this behavior is intended, then I propose mentioning this in the documentation.

Thank you!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
