### ISSUE TITLE
Horizon WithoutOverlapping: Can't call has and get cache methods on laravel-queue-overlap

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#38232]
- Laravel Version: 8.52.0
- PHP Version: 8.0.9
- Database Driver & Version:

### Description:
Can't use `has` or `get` on cache pair (key, value), stored by Horizon WithoutOverlapping .

### Steps To Reproduce:
```php
// in job class
    public function middleware(): array
    {
        return [
            (new WithoutOverlapping('awesome-key')->dontRelease();
        ];
    }

// in controller, after job is dispatched
$key = 'laravel-queue-overlap:App\Jobs\JobClassName:awesome-key';

try {
    Cache::store('redis')->has($key); // thow an the exception only if thet key exist!
    $value = Cache::store('redis')->get($key); // thow an the exception only if thet key exist!
} catch (Throwable $e) {
    // unserialize(): Error at offset 0 of 16 bytes
    // vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php: 345
}

Cache::store('redis')->forget($key); // success id key exists or not
// if $key exist, it that line deleted that pair from cache.
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by LocalHeroPro** [comment]
Another BUG and you closing it as quick as possible. Damn

**Comment by LocalHeroPro** [comment]
Issue still exists in 8.53.0
