### ISSUE TITLE
Some methods are missing from Filesystem contract

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/framework#38235]
- Laravel Version: 8.51.0

### Description:

I'm going to use in my controller 

```php
return Storage::disk('documents')->download($file);
```

but VSCode returns an error `Undefined method 'download'` even if the code is working correctly.

Using 

```php
return Storage::download($file);
```

it gives no error.

This is because `Storage` facade point to `Illuminate\Filesystem\FilesystemManager` while `disk` method returns a `\Illuminate\Contracts\Filesystem\Filesystem`.

**Comment by driesvints** [comment]
No methods are missing. Not all implementations have this method. You'd need to type hint the concrete implementation if you want driver specific functionality.

**Comment by alberto-bottarini** [comment]
I'm sorry but why `FilesystemManager` manager has this method?

It has no sense

**Comment by ebulku** [comment]
You can fix it by defining it this way:

```
/** @var Illuminate\Filesystem\FilesystemAdapter */
$filesystem = Storage::disk('documents');
return $filesystem->download($file);
```
