### ISSUE TITLE
APP_KEY not cached unless config:cache is run twice

### ISSUE THREAD

**Issue by bluezio** [laravel/framework#38242]
- Laravel Version: 8.42.1
- PHP Version: 7.4.3

### Description:

In one of our automated deployment processes for a pre-production environment, we have had a strange issue in the way that APP_KEY is cached. We always deploy from a clean checkout of the repository (symlinking to a persistent `storage` directory, but with a clean `bootstrap/cache` folder), and in the last steps of the process we run `key:generate` and `cache:config`.

We're noticing that if we only run `cache:config` once, the `bootstrap/cache/config.php` file will *not* have the APP_KEY value cached (`key` will just have '') - all other values are cached just fine (e.g. database passwords and so on). If we run `cache:config` again (without touching anything else or running any other commands), then it will have the APP_KEY value correctly cached.

Any ideas as to why we'd need to run `config:cache` twice? It does work this way, but it feels wrong :-).

### Steps To Reproduce:

If at the end of our deployment process we run the below commands, `bootstrap/cache/config.php` will not have APP_KEY cached (but will have everything else cached just fine).

```sh
php artisan migrate --force --seed
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan key:generate
umask 0007
php artisan config:cache
php artisan up
sudo /usr/sbin/service php7.4-fpm reload
```

If we change it so it runs `config:cache` twice, it will have APP_KEY cached:

```sh
php artisan migrate --force --seed
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan key:generate
umask 0007
php artisan config:cache
php artisan config:cache
php artisan up
sudo /usr/sbin/service php7.4-fpm reload
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by roksprogar** [comment]
I am having the exact same issue in production (Ubuntu EC2 instance), the first time the config:cache command is run, the APP_KEY is missing, the 2nd time it appears.

I can't replicate the issue on my dev/staging server, hovewer, even though I have it set up to resemble the production environment as as closely possible. The only major difference I can think of rn is that in production everything is run under the www-data user, while on dev/staging I run everything under a local user.

**Comment by nick322** [comment]
I ran into this issue too. I later noticed that it's mentioned in the documentation:
https://laravel.com/docs/12.x/configuration#additional-environment-files
