### ISSUE TITLE
Signed URLs for routes with custom-key implicit binding no longer generate correctly

### ISSUE THREAD

**Issue by aryehraber** [laravel/framework#38248]
- Laravel Version: `8.53.0`
- PHP Version: `8.0.9`
- Database Driver & Version: `MySQL 8.0.19`

### Description:
After updating to Laravel `8.53.0` today, one of my tests using signed URLs started failing. I downgraded to `8.52.0` and everything still works there, so it's definitely something in the latest release.

My User model has an `id` (primary key) & `uuid` column. The upgrade seems to ignore the custom key in the route definition and uses the primary key instead.

`8.52.0` and earlier generated:
```
https://app.test/demo-login/b7c62dfa-3361-4fb1-bb32-f8958f890be1?signature=[long_signature]
```

`8.53.0` generates:
```
https://app.test/demo-login/1?signature=[long_signature]
```

I will add the route in question below with the failing test.  Please let me know if any further details are needed!

### Steps To Reproduce:

`routes/web.php`
```php
Route::middleware(['guest', 'signed'])->get('/demo-login/{user:uuid}', function (User $user) {
    Auth::login($user);

    return redirect()->route('dashboard');
})->name('demo-login');
```

Failing test
```php
/** @test */
public function signed_demo_login_url_can_login_a_user()
{
    $user = User::factory()->create();

    $response = $this->get(URL::signedRoute('demo-login', $user));

    $response->assertRedirect(route('dashboard'));
    $this->assertAuthenticatedAs($user);
}
```

**Comment by driesvints** [comment]
Thanks for the report. I've sent in a PR for this.

**Comment by aryehraber** [comment]
Amazing, thank you for the quick work!
