### ISSUE TITLE
Domain-specific cookies don’t honour domain

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#38267]
- Laravel Version: 8.40.0
- PHP Version: 8.0.7
- Database Driver & Version: Postgres

### Description:
I’m testing a basic affiliate system in a multi-tenant application where a code is specified as a query string parameter and then stored in a cookie.

My middleware looks like this:

```php
class PersistAffiliateCode
{
    public function handle(Request $request, Closure $next)
    {
        if ($code = $request->query('aff')) {
                Cookie::queue(cookie('affiliate_code', $code, 1440 * 7, '/', $request->getHost()));
        }

        return $next($request);
    }
}
```

My test looks like this:

```php
// Set code on first domain
$this->get('https://website1.test/?aff=TEST')->assertCookie('affiliate_code', 'TEST');

// Test cookie is not present from another domain
$this->get('https://website2.test/?aff=TEST')->assertCookieMissing('affiliate_code');
```

However, this test fails as the cookie set for `website1.test` is actually present in the response when making the request to `website2.test`. I’d not expect this cookie to returned given I set it for domain and making a request to another.

```
There was 1 failure:

1) Tests\Feature\Website\AffiliatesTest::testAffiliateCodeSetForOneWebsiteIsNotPresentOnAnoth er
Cookie [affiliate_code] is present on response.
```

I can confirm that this implementation _does_ work as expected in the browser, but it seems Laravel’s tests don‘t discriminate against hostname when attaching cookies to responses, and just attaches _any_ cookies set in a test to any subsequent HTTP requests in that test case.

### Steps To Reproduce:

As above.

**Comment by driesvints** [comment]
Hey @martinbean, thanks for the report. The issue here is that you're executing two get requests in the same test method (something Laravel doesn't and has never supported). Event though many people try and usually succeed, it isn't technically possible to execute two such requests in one test because there's no way to clear the entire state of the application once the first request has been executed. Only separate test methods can clear that application state.

You might be better off with writing a Dusk test? I'm not 100% sure but I think that should work.

**Comment by martinbean** [comment]
> something Laravel doesn't and has never supported

@driesvints Then why isn’t this enforced by the framework? If this isn’t how the test suite is meant to be used, then it might be worth raising an error whenever a second request is issued in the same test? But I think we both know that will break a lot of test suites.

Is it not an issue here that requests in tests don‘t behave the same way those requests would in a “real” environment? If requests in tests don’t behave like they would in a real scenario, how can I possibly have confidence in my tests written with Laravel?

**Comment by driesvints** [comment]
>  Then why isn’t this enforced by the framework?
> But I think we both know that will break a lot of test suites.

You answered your own question : )

And like I said:

> Event though many people try and usually succeed

So there isn't a good reason to hard-enforce this at the time. 

> Is it not an issue here that requests in tests don‘t behave the same way those requests would in a “real” environment? If requests in tests don’t behave like they would in a real scenario, how can I possibly have confidence in my tests written with Laravel?

Well that's subjective as what you considered a "real" environment. A "real" environment in my eyes is a single web request cycle (for example, executing a HTTP request) and that "real" environment is executed once in a single test method, not twice. A "real" browser request can't be executed twice, it's always a single execution. I know opinions differ here but I also know other people also think about test methods in the same way.
