### ISSUE TITLE
Route prefixes not appending in the correct order

### ISSUE THREAD

**Issue by juliomotol** [laravel/framework#38261]
- Laravel Version: 8.53.1
- PHP Version: 7.4.13
- Database Driver & Version: N/A

### Description:

In the Router, when grouping with a prefix then creating a single prefixed route inside, it prepends the prefix inside instead of appending it to the group's prefix.

See https://github.com/juliomotol/lapiv/issues/1#issuecomment-894349325 for more details.

### Steps To Reproduce:

```php
Route::prefix('first')->group(function () {
    Route::prefix('second')->get('foo', [FooController::class, 'index']);
});

// Generates `second/first/foo` instead of `first/second/foo`.
```

**Comment by driesvints** [comment]
```
Route::prefix('first')->group(function () {
    Route::get('second/foo', [FooController::class, 'index']);
});
```

**Comment by juliomotol** [comment]
Yeah, but we are macroing the Router to apply a prefix.

```php
Router::macro('customMacro', function () {
    return Route::prefix('some-prefix');
})
```
