### ISSUE TITLE
Why laravel email validation accepting emojis & special characters other then @ sign?

### ISSUE THREAD

**Issue by mtt786** [laravel/framework#38279]
😔@gmail.com, a#1@gmail.com etc.

Laravel email validation accepting these types of emails with emoji & special characters.

`$request->validation(['email' => 'required|email']);`

**Comment by rs-sliske** [comment]
not sure about the emoji but email addresses are allowed to contain special characters (even if your chosen mail provider wont let you register an email with those characters in, that is a restriction of that particular mail provider not the email address spec)
