### ISSUE TITLE
Artisan execute command on another env version that specified

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#38277]
- Laravel Version: 8.53.1
- PHP Version: 8.0.9
- Database Driver & Version:

### Description:
When specify env that doesn't exists, called method execute command on existing env, for example production ;)

### Steps To Reproduce:
```shell
$ php artisan db:wipe --env=testing
```
In that way we have wiped out production database !)

**Comment by driesvints** [comment]
That's intended. Don't execute on a non-existing env. And don't execute `db:wipe` on production 😅

**Comment by LocalHeroPro** [comment]
So we have lottery on what artisan command get env. 
NOT nice.

**Comment by driesvints** [comment]
There's no way of knowing what environments exist. There's no concept of such a list in Laravel.

**Comment by LocalHeroPro** [comment]
It point to another bug. If we have few env files without .example extension, application can randomly get config data.
It's so week.
