### ISSUE TITLE
Laravel blade nearly infinite recursive loop when rendering menu-like items

### ISSUE THREAD

**Issue by windstep** [laravel/framework#38272]
- Laravel Version: 8.53.1
- PHP Version: 7.3.24
- Database Driver & Version: ---

### Description:
Nearly infinite loop of laravel blade rendering recursive loops.
I've edited only resources/views folder

### Steps To Reproduce:

1. `git clone https://github.com/windstep/test_blade_error.git`
2. `cd test_blade_error`
3. `composer install`
4. `cp .env.example .env`
5. `php artisan serve`
6. navigate to `127.0.0.1:8000`

**Comment by viiuszko** [comment]
Included file using `@include` doesn't make them isolated so that's the expected behavior. You should use component to achieve what you are trying to do.

**Comment by windstep** [comment]
Thanks!
