### ISSUE TITLE
Bitwise NOT operator does not work for MariaDB

### ISSUE THREAD

**Issue by joostdebruijn** [laravel/framework#38300]
- Laravel Version: 8.52.0
- PHP Version: 8.0.9
- Database Driver & Version: MariaDB 10.6.4

### Description:
MariaDB supports a bitwise NOT operator [as follows](https://mariadb.com/kb/en/bitwise-not/):

`SELECT 3 &~ 1;`

Laravel seems not be able to parse a query like this correctly. The operator is replaced by `=`.

### Steps To Reproduce:
Create a query with a bitwise not operator like this:

`Model::where('status', '&~', Model::STATUS)->toSql();`

Results in:

```"select * from `model` where `status` = ?"```

I would expect:

```"select * from `model` where `status` &~ ?"```

**Comment by driesvints** [comment]
Seems like a feature request. Welcoming PRs for this.
