### ISSUE TITLE
firstOrCreate prioritizes first parameters over second parameters

### ISSUE THREAD

**Issue by Sirfrummel** [laravel/framework#38302]
- Laravel Version: 8.53.1
- PHP Version: 8.0.9
- Database Driver & Version:  mysql

### Description:

firstOrCreate is prioritizing the FIND parameters _over_ the CREATE parameters, and this seems backwards to me.  For example:
`      $project = Project::firstOrCreate([
          'name' => 'someExistingName',
        ],
        [
          'name' => 'myNewCreateName'
        ]
      );`
I want to say  "find a project by this name, OR create by this other name", and you'll see "someExistingName" is what gets inserted into the database.

I double checked the code and it looks like it's because of how PHP merges 2 arrays, due to this line:
https://github.com/laravel/framework/blame/8.x/src/Illuminate/Database/Eloquent/Builder.php#L484

So if you want to know the actual real world example, of how the _Create_ parameter would be different than the find parameter, take using an object with uuids:

`    $project = Project::firstOrCreate([
          'uuid' => $request->uuid
        ],
        [
          'uuid' => Str::uuid()
        ]
      );
`
So what is happening here, is that it is not over-riding the request UUID with the generated one.  Because basically, if my project doesn't exist with the UUID given by the frontend, I want to generate my own on the backend.  

I feel like it should logically play out like this:
"Use these parameters to FIND the object, if it doesn't exist, use THESE PARAMETERS to CREATE the object"...  it **makes sense** that the FIND parameters should **influence** the CREATE parameters, however, they should not **take precedence** over parameters specifically passed in through the CREATE parameters.

I hope that helps give context and makes sense.  Please tell me if there is something obvious I missed because I am basically a Laravel newbie :)

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
