### ISSUE TITLE
Attaching multiple items with additional pivot data attempts to store as incorrect data type

### ISSUE THREAD

**Issue by Healyhatman** [laravel/framework#38308]
- Laravel Version: 
- PHP Version: 7.30.4
- Database Driver & Version:
sqlsrv  I'm not sure which version sorry
### Description:

When attaching multiple models to another model via a many-to-many with additional pivot data, in groups of more than about 20, I get an error like `Conversion failed when converting the nvarchar value '17.85' to data type int` even though the column is decimal

### Steps To Reproduce:
I have an NdisRunReport model, and a Trans table, with ndis_run_report_trans in between them.

the transactions() relation on NdisRunReport looks like this
```
public function transactions()
	{
        return $this
            ->belongsToMany(Trans::class, 'ndis_run_report_trans')
            ->withPivot(['claim_reference', 'claim_amount', 'quantity', 'hours', 'unit_price', 'claim_type', 'cancellation_reason']);
    }
```
The ndis_run_report_trans table looks like this
![image](https://user-images.githubusercontent.com/13272508/128796670-c5c5561d-d27c-4237-8206-992eaea69bf5.png)

After creating the NdisRunReport model, I build an array of Trans IDs and associated pivot data like this
```
$pivotData[$transaction->SYSID] = [
    'claim_reference' => $claim_reference,
    'claim_amount' => $transaction->calculated_total_including_cancellation,
    'support_number' => $transaction->Service->ndis_support_number,
    'quantity' => $transaction->qty,
    'hours' => $transaction->hours,
    'unit_price' => $transaction->UNITCOST,
    'claim_type' => $transaction->ndis_export_claim_type,
    'cancellation_reason' => $transaction->cancelCode->ndiaCancellationCode->code ?? null
];
```
claim_amount and quantity are both floats - the first being an accessor that explicilty returns a float, the other I would assume is a float from the way it's initialised. 

`$transaction->qty = ($transaction->QUANTITY ?: 0) * $workerCount;`

(QUANTITY is a float and workerCount is an int)

I attach the models like this
// Attach the pivot data. Chucked due to max binding error
foreach(collect($pivotData)->chunk(200) as $chunk) {
    $report->transactions()->attach($chunk);
}

I get the error somewhere in the second chunk loop. If I set the chunk size to 20, I get it after 260 elements (chunk number 13). 

I DON'T get an error if the chunk size is less than 15 or so, or if the chunk size is 1, so there's nothing wrong with the data itself. I also don't get the error if I force the variables to floats using (float)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Healyhatman** [comment]
@driesvints sorry just making sure you read the full "steps to reproduce"? Especially the last sentence? If you have and you still think it's just a support issue please reply as such and I'll ask there.

**Comment by driesvints** [comment]
Yeah, please try a support channel.
