### ISSUE TITLE
Wrong type declaration in Illuminate\Database\Eloquent\Factories\Factory::createMany

### ISSUE THREAD

**Issue by patryk-k** [laravel/framework#38318]
- Laravel Version: 8.53.1
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 8.0.25

### Description:
createMany function of Illuminate\Database\Eloquent\Factories\Factory accepts any iterable variable as its first argument. It then tries to pass it to array_map which accepts only arrays.

```
  /**
   * Create a collection of models and persist them to the database.
   *
   * @param  iterable  $records
   * @return \Illuminate\Database\Eloquent\Collection
   */
  public function createMany(iterable $records)
  {
      return new EloquentCollection(
          array_map(function ($record) {
              return $this->state($record)->create();
          }, $records)
      );
  }
```

### Steps To Reproduce:
`$modelWithFactory::factory()->createMany(collect([['foo' => 'bar'],['foo' => 'baz']]));`

The model and factory is irrelevant, the code will produce the following PHP error before getting anywhere regardless

`array_map(): Argument #2 ($array) must be of type array, Illuminate\Support\Collection given`

**Comment by driesvints** [comment]
Thank you. I've sent in a PR for this: https://github.com/laravel/framework/pull/38319
