### ISSUE TITLE
Creating factory data doesn't work when created by another factory

### ISSUE THREAD

**Issue by JamesFreeman** [laravel/framework#38323]
- Laravel Version: 8.53.1
- PHP Version: 7.3.28
- Database Driver & Version: N/A

### Description:

When trying to create a factory relationship through another factory call it is not creating the nested model data in the correct way.

```php
public function test_example()
{
    Order::factory()
       ->hasItems(
           OrderItem::factory()
               ->hasProduct(
                  Product::factory()->state(['barcode' => '12345'])
               )
       )
       ->create();

    $this->assertCount(1, Order::all());
    $this->assertEquals('12345', Product::first()->barcode); // fails and inherits from the Product::factory() faker instead
}
```

### Steps To Reproduce:

https://github.com/JamesFreeman/factory-helper-issue/commit/bb27c89b40572135c156f87f0d71bfc7a2308306

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
