### ISSUE TITLE
Session expire on recieving POST request from other Domain

### ISSUE THREAD

**Issue by saaiful** [laravel/framework#38339]
- Laravel Version: 8.40
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:
Most payment processor sends callback to requested URL using POST method.  When Laravel receives POST request from "other domain" it accepts the request (as the URL is excluded in `VerifyCsrfToken`), but the issue is my user gets logged out. 

Why is this happening ?

In previous version of Laravel it works without any issue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
