### ISSUE TITLE
Undefined offset: 1 when using cursorPagination

### ISSUE THREAD

**Issue by exzachlyvv** [laravel/framework#38347]
- Laravel Version: 8.53.0
- PHP Version: 7.4.21
- Database Driver & Version: Mysql@5.7

### Description:
**Prerequisite**: In the database query, any column must have alias "x AS y". Note that "x as y" (lower case "as") will work.

When fetching page 2 and up while using cursorPagination, this stack trace is thrown:

> ErrorException : Undefined offset: 1
> vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:358

### Steps To Reproduce:
1. Use cursorPagination on a database query that has an alias "x AS y"
2. Fetch the first page, this will work
3. Using the next page URL fetch the 2nd page <-- error thrown

**Comment by driesvints** [comment]
We fixed this in https://github.com/laravel/framework/pull/38251 so please update.
