### ISSUE TITLE
`Arr::has()` returns false for empty set of keys

### ISSUE THREAD

**Issue by nizacegodk** [laravel/framework#38340]
- Laravel Version: 8.53.1
- PHP Version: 7.4.0
- Database Driver & Version: mariadb:10.6.4

### Description:
When calling `Arr::has($data, $keys)` with an empty `$keys` array, `FALSE` will be returned - where `TRUE` would be expected.

We have a case where we need to dynamically verify that a set of keys exists within an array, and one case is that we have no requirements. Currently running `Arr::has($data, [])` returns false, breaking our code.

### Steps To Reproduce:

- Run `Arr::has(['key' => 'value'], []); // FALSE`

**Comment by driesvints** [comment]
This is the expected behavior.

**Comment by nizacegodk** [comment]
@driesvints I know from the code that this how it should be. But what is the reasoning behind this choice?

The example above do contain all of the listed keys (none), and I would therefore expect it to return true?
