### ISSUE TITLE
->update(['property' => 'value']) also updates all other "dirty" properties - is this intended?

### ISSUE THREAD

**Issue by eblumstengel** [laravel/framework#38342]
- Laravel Version: 8.50.0
- PHP Version: 8.0.6
- Database Driver & Version: mysql & 5.7

### Description:

Performing `->update()` on a model after changing an attribute, causes changes to columns that weren't included in the passed array.

I'm not quite sure if this is considered as a bug, according to the documentation it sounds like *only* the passed array values/attributes should be updated.

> The update method, like the insert method, accepts an array of column and value pairs indicating the columns to be updated.

Source: https://laravel.com/docs/8.x/queries#update-statements

Is it intended that dirty attributes that are set outside of the `->update()` method get updated too?

### Steps To Reproduce:

```php
$user = User::first();

$user->name = 'This should not be updated';

$user->update(['email' => 'only-email@should-be-updated.com']);

return $user;
```

This will return the user *with* an updated name, although it wasn't included in the `->update()` array.

```
=> App\Models\User {
     id: 1,
     name: "This should not be updated",
     email: "only-email@should-be-updated.com",
     created_at: "2021-08-11 11:00:00",
     updated_at: "2021-08-11 12:00:00",
   }
```

**Comment by driesvints** [comment]
Yes, that's intended.
