### ISSUE TITLE
lazy() on foreach loop

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#38365]
- Laravel Version: 8.54.0
- PHP Version: 8.0.9
- Database Driver & Version:

### Description:
Lazy method iterate on ALL model entities.

### Steps To Reproduce:
```php
$count = User::query()->count(); // 86

foreach (User::query()->offset($count / 4)->limit($count / 40)->lazy() as $user) {
    Log::channel('testing')->info(1); //  86 times // wrong
}

foreach (User::query()->offset($count / 4)->limit($count / 40)->cursor() as $user) {
    Log::channel('testing')->info(1); // 2 times // good
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
So, what's happening here is that the `cursor` method is the thing that you want. The `lazy` method is an undocumented internal method to facilitate lazy loading and shouldn't be used in userland. You can read more about lazy collections here: https://laravel.com/docs/8.x/collections#lazy-collections
