### ISSUE TITLE
When docs are printed, partially covered by an "Ads by Carbon" ad

### ISSUE THREAD

**Issue by barobba** [laravel/framework#38360]
- Laravel Version: 8.x (DOCS)

### Description:

I don't know who needs to see this issue or where to post it.

The bottom-right corner of printed pages are covered by an "Ads via Carbon" ad. This makes it impossible to read the full docs from a printed version because a portion of the sentences are covered up with an ad.

### Steps To Reproduce:

Print out a few pages in the docs.

For example: https://laravel.com/docs/8.x/mail (print this)

**Comment by driesvints** [comment]
No plans to change this ourselves. You're always free to attempt a PR. Thanks

**Comment by barobba** [comment]
I didn't realize I could do PR!

I will take a look.

I found this: https://github.com/laravel/laravel.com-next

I assume this is what is currently used.

**Comment by barobba** [comment]
Ok, I submitted a pull request.
