### ISSUE TITLE
preventLazyLoad() Makes whenLoaded() Useless

### ISSUE THREAD

**Issue by wildangunawan** [laravel/framework#38368]
- Laravel Version: 8.54.0
- PHP Version: 7.4.15
- Database Driver & Version: MariaDB / 10.4.17

### Description:

Turning on `Model::preventLazyLoading(! app()->isProduction());` in `AppServiceProvider.php` makes developer should eager load the data. This is a great feature to prevent N+1 problem and already helped me so much.

But when using this with withLoaded() in API resource class, the withLoaded() becomes useless since we should eager load it anyway.

### Steps To Reproduce:

In my ItineraryResource.php, I have some whenLoaded like schedules, cities, creator, and tags. 

```php
public function toArray($request)
{
    return [
        'name' => $this->name,
        'slug' => $this->slug,
        'description' => $this->whenAppended('full_info', $this->description),
        'schedule' => $this->whenLoaded('schedules', new ItineraryScheduleCollection($this->schedules)),
        'cities' => $this->whenLoaded('cities', CityResource::collection($this->cities)),
        'creator' => $this->whenLoaded('creator', [
            'name' => $this->creator->name,
            'username' => $this->creator->username,
        ]),
        'tags' => $this->whenLoaded('tags', $this->tags),
    ];
}
```

When showing list of itinerary, I only want `creator` and `tags` to be shown. 

```php
public function index()
{
    return ItineraryResource::collection(
        Itinerary::with(['creator', 'tags'])->paginate()
    );
}
```

But since I disable lazy loading, it throws an exception since I haven't eager load `schedules` and `cities`. If I eager load it, then schedules and cities also appear in the result, since it's loaded.

![image](https://user-images.githubusercontent.com/35158077/129302407-db0641cf-7b79-4ef4-a9fd-2d6881183c75.png)
![image](https://user-images.githubusercontent.com/35158077/129302423-04b833ec-1fe0-4825-9bf4-cc2bce54624c.png)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by ryangjchandler** [comment]
@wildangunawan I think you've actually got an issue with how you're using the `$this->whenLoaded` method, it should look something like this:

```php
public function toArray($request)
{
    return [
        'name' => $this->name,
        'slug' => $this->slug,
        'description' => $this->whenAppended('full_info', $this->description),
        'schedule' => new ItineraryScheduleCollection($this->whenLoaded('schedules')),
        'cities' => CityResource::collection($this->whenLoaded('cities')),
        'creator' => $this->whenLoaded('creator', [
            'name' => $this->creator->name,
            'username' => $this->creator->username,
        ]),
        'tags' => $this->whenLoaded('tags'),
    ];
}
```

This will only include the `cities` and `schedule` keys when they have been eager-loaded. Your original code would _always_ been accessing `$this->schedules`, therefore trying to load the relationship and triggering a lazy-load exception.

**Comment by driesvints** [comment]
Thanks @ryangjchandler!

**Comment by wildangunawan** [comment]
> @wildangunawan I think you've actually got an issue with how you're using the `$this->whenLoaded` method, it should look something like this:
> 
> ```
> public function toArray($request)
> {
>     return [
>         'name' => $this->name,
>         'slug' => $this->slug,
>         'description' => $this->whenAppended('full_info', $this->description),
>         'schedule' => new ItineraryScheduleCollection($this->whenLoaded('schedules')),
>         'cities' => CityResource::collection($this->whenLoaded('cities')),
>         'creator' => $this->whenLoaded('creator', [
>             'name' => $this->creator->name,
>             'username' => $this->creator->username,
>         ]),
>         'tags' => $this->whenLoaded('tags'),
>     ];
> }
> ```
> 
> This will only include the `cities` and `schedule` keys when they have been eager-loaded.
> 
> Your original code would _always_ been accessing `$this->schedules`, therefore trying to load the relationship and triggering a lazy-load exception.
> 
> The update code I have provided uses the recommended method as seen in the documenation (https://laravel.com/docs/8.x/eloquent-resources#conditional-relationships)

Welp, even the docs mentioned that. Where did I got my code? Haha!

Thanks @ryangjchandler
