### ISSUE TITLE
Mac M1 Docker Laravel  Sail MySQL 8 won't pull arm arch

### ISSUE THREAD

**Issue by j3rrey** [laravel/framework#38370]
Laravel Version: 8.54.0
PHP Version: 8.0
Database Driver & Version: MySQL 8
MacOS: Big Sur 11.5.2

Mac M1 Docker Laravel  Sail MySQL 8 won't pull arm arch
The example app won't "sail up" (docker-compose up) on M1 chips 

Error:
```
Pulling mysql (mysql:8.0)...
8.0: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

https://github.com/laravel/framework/blob/fc0a4a7400cf528d05fd5660ffe8db372c50baa9/docker-compose.yml#L9
An easy fix would be 
`image: 'mariadb'`
Done 🎉 

If you really need MySQL:
Terminal -> 
`softwareupdate --install-rosetta`

Docker-compose.yml
```   
    mysql:
        platform: linux/x86_64
        image: 'mysql:8.0'
```

After that, the correct MySQL image will be pulled. 

```
sail up

Pulling mysql (mysql/mysql-server:8.0.23)...
8.0.23: Pulling from mysql/mysql-server
```
Done 🎉 

other links:
https://docs.docker.com/docker-for-mac/apple-silicon/
https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

**Comment by driesvints** [comment]
We use this mainly for internal purposes. It's not really meant to be used by the wide public. Thanks for mentioning though!
