### ISSUE TITLE
Inconsistency in `in` validation

### ISSUE THREAD

**Issue by eithed** [laravel/framework#38378]
- Laravel Version: 8.52.0
- PHP Version: 8.0
- Database Driver & Version: n/a

### Description:

Provided following validation rules:

```
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

$validator = Validator::make(['data' => true], [
    'data' => [
        Rule::in([1]),
    ],
]);

dd($validator->passes());
```
> true

```
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

$validator = Validator::make(['data' => false], [
    'data' => [
        Rule::in([0]),
    ],
]);

dd($validator->passes());
```
> false

```
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

$validator = Validator::make(['data' => 1], [
    'data' => [
        Rule::in([true]),
    ],
]);

dd($validator->passes());
```
> true

```
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

$validator = Validator::make(['data' => 0], [
    'data' => [
        Rule::in([false]),
    ],
]);

dd($validator->passes());
```
> false

If true is synonymous with 1, then false should be synonymous with 0 - as such 0/false validation should pass.
If false is not synonymous with 0, then true should not be synonymous with 1 - as such 1/true validation should not pass.

**Comment by driesvints** [comment]
I do agree that's a weird discrepancy but since this has always been the behavior I don't consider this a bug. You're always free to attempt a PR to master to update the behavior for the next major version if you like. Thanks
