### ISSUE TITLE
Job Batch Unexpected Behaviour

### ISSUE THREAD

**Issue by halimsupranata** [laravel/framework#38399]
- Laravel Version: 8.54.0
- PHP Version: 7.4.3
- Database Driver & Version: 8.0.26

### Description:
I copy data using job batch and chunk. If I create about 400 job in 1 batch, it will start unexpected behaviour. Copy 40.000 data and the result only 38.421 or 39511.  The chunk is 100, but it can give 21 or 11. I don't know where it is from. If I change the chunk to 1000, so it's only 40 job. It's work fine, copy 40.000 data result in 40.000 data.

### Steps To Reproduce:
Make a batch with a lot of job, for example 400 job in one batch

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by halimsupranata** [comment]
@driesvints It is not a question, but it's a report. This is the bug with laravel 8 job batch
