### ISSUE TITLE
$_ENV vars are not available in listeners registerd in EventServiceProvider $listen

### ISSUE THREAD

**Issue by ctwillie** [laravel/framework#38409]
- Laravel Version: 8.54.0
- PHP Version: 7.4.14
- Database Driver & Version: Mysql / 8.0.23

### The Problem

A composer package my app requires uses $_ENV to access env vars. I'm using a class from this package in a listener that is registered in ```EventServiceProvider``` in the ```$listen``` property. The $_ENV values are not set. The $_ENV variables are correctly loaded from .env everywhere else. This package is not Laravel specific, so ```env()``` helper is not an option.

[This issue](https://github.com/laravel/framework/issues/6647), which is closed, mentions the same issue but, I thought ```getenv``` is discouraged and should be avoided being it is not thread safe.

### Steps To Reproduce:

- Register a listener in EventServiceProvider@$listen
```php

// EventServiceProvider.php
protected $listen = [
        \App\Events\FooEvent::class    => [
            \App\Listeners\FooListener::class,
        ],
];
```
- In FooListener::class, call $_ENV['FOO'];

**Comment by ctwillie** [comment]
@taylorotwell @GrahamCampbell 
Is this a Laravel issue, or am I missing something here? Thanks!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ctwillie** [comment]
@driesvints

Thanks for the reply, 

But how is a php super global not being available in this php framework not a bug?
