### ISSUE TITLE
Email validation passes email with space characters

### ISSUE THREAD

**Issue by neacon-ivalkenburg** [laravel/framework#38401]
- Laravel Version: 8.54.0
- PHP Version: 8.0.7
- Database Driver & Version: Not applicable

### Description:
The email validation rule passes email address with certain space characters:
john.doe @example.com
john.doe@ example.com

At first i thought this was some sort of trimming issue, but " john.doe@example.com" does not pass.

### Steps To Reproduce:
Run the following in tinker:
```validator(['email' => 'john.doe@ example.com '], ['email' => ['required', 'email']])->fails()```
```validator(['email' => 'john.doe @example.com '], ['email' => ['required', 'email']])->fails()```

**Comment by driesvints** [comment]
You're responsible for trimming the input beforehand. Usually this is done by the TrimStrings middleware in Laravel.

**Comment by buismaarten** [comment]
@driesvints this will remove whitespaces at the beginning/end of the string, not spaces in the middle of the string.

@neacon-ivalkenburg to give a solution, you can use the `'email' => 'email:rfc,dns'`.
See: https://laravel.com/docs/8.x/validation#rule-email
