### ISSUE TITLE
Call loadMissing() in a isolated model replica

### ISSUE THREAD

**Issue by kodewbit** [laravel/framework#38423]
- Laravel Version: 8.46.0
- PHP Version: 8.0.7
- Database Driver & Version:

### Description:
I have a question maybe a little silly. I'm trying to replicate and store a model instance in a variable to call the ```loadMissing``` method. The idea is to call the ```loadMissing``` method without being affected by the original model. 

### Steps To Reproduce:
I have the following method in my ```User``` model: 

```
class User extends Authenticatable
{
   ...

   public function myCustomMethod()
   {
        $cloned = $this->replicate()
            ->loadMissing('roles.permissions')
            ->getAttribute('roles')
            ->flatMap(function ($role) {
                return $role->permissions
            });

        return $cloned;
   }
```
The problem is that in this way the original model instance is affected, and it loads in the original instance all the relations that I am loading only in this method.
My question is: is there a way to load and isolate relationships in a replica of the model instance without affecting the original model?

I have also tried cloning the instance and trying to use the ```loadMissing``` method on the cloned instance, but the original instance is also affected. For example:

```
class User extends Authenticatable
{
   ...

   public function myCustomMethod()
   {
        $original = $this;
        $cloned = clone $original;

        $cloned->loadMissing('roles.permissions');

        dump($original);
        dump($cloned);

        die();
   }
```

But in this way, I get the following results. Notice that both the original and the cloned instance are loading the relationships when I'm just trying to load the relationships in the cloned instance:

```$original```

![1](https://user-images.githubusercontent.com/70990619/129827208-91ce813f-41f0-4da6-a27c-738c3d899946.png)

```$cloned```

![imagen](https://user-images.githubusercontent.com/70990619/129827318-f94914ed-69c5-4cae-8874-b7ddcc5eda89.png)

I was wondering if this is normal behavior. If it is a normal behavior, which I suppose it is not, I was wondering if there is any way to use the ```loadMissing``` method on a copy, replica or clone of an instance without modifying the original instance. Thank you very much in advance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
