### ISSUE TITLE
Eloquent's `fresh` method does not run scope queries

### ISSUE THREAD

**Issue by elnurvl** [laravel/framework#38431]
- Laravel Version: 8.54.0
- PHP Version: 8.0.9
- Database Driver & Version: mysql:8.0.17

### Description:

There are additional columns appended to an Eloquent model using the `addSelect` in global scopes. `fresh` method on the model does not update the data for those columns. However, `first` method does. Is this an intended feature?

### Steps To Reproduce:

Let's say we defined an anonymous scope for an Eloquent model `Item` allowing to get the saved status of each item for the authenticated user:

```

static::addGlobalScope('is_saved', function (Builder $builder) {
            $builder->addSelect([
                'is_available' => DB::table('item_user_saved')
                    ->join('items', 'item_user_saved.item_id', '=', 'items.id')
                    ->selectRaw('COUNT(*)')
                    ->whereColumn('item_user_saved.property_id', 'items.id')
                    ->where('item_user_saved.user_id', auth()->id())
            ]);
        });
```

When I create the model and then make some changes in the database, I need to update the model loaded in the memory to fill the properties as well as the `is_available`. I expect, `$model->fresh()` would do the job, but it does not run the scope queries.

**Comment by driesvints** [comment]
Yes that's intended.
