### ISSUE TITLE
APP_KEY re-generation blocks encrypted casted attribute writting

### ISSUE THREAD

**Issue by pyrou** [laravel/framework#38434]
- Laravel Version: 8.52
- PHP Version: 8.0
- Database Driver & Version: Any

### Description:

When a model attribute is using the `encrypted` cast (or any other variants such as `encrypter:json`), an APP_KEY update would block any future update on the model. A `DecryptException` will be thrown at save. 

Of course, it is totally expected to be facing this exception when READING the encrypted attribute, but this souldn't (IMHO) occur when simply trying to write a new value.

### Steps To Reproduce:

1. Create a simple table + model using encrypted cast
```php
Schema::create('tests', function (Blueprint $table) {
    $table->id();
    $table->string('private_column');
    $table->timestamps();
});

class Test extends Model
{
    protected $casts = [
        "private_column" => "encrypted",
    ];
}
```

2. Create a first record
```php
$model = new Test();
$model->private_column = "secret";
$model->save();
```

3. Update app key
```bash
php artisan key:generate
```

4. Try to update the record (Let's say to re-encrypt the value with the new `APP_KEY`)
```php
$model = Test::first();
$model->private_column = "secret";
$model->save(); // or $model->update();

Illuminate\Contracts\Encryption\DecryptException with message 'The MAC is invalid.'
```

**Comment by driesvints** [comment]
This is how things work. The model is hydrated with the encrypted value which is being decrypted. And thus fails because your app key got changed.
