### ISSUE TITLE
Cursor pagination does not work with orderBy() using a sub query

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#38447]
- Laravel Version: 8.52.0
- PHP Version: 8.0.3
- Database Driver & Version: maria db 10.3.12

### Description:
When doing an orderBy using a sub query and using cursor pagination i get this error

`array_flip(): Can only flip string and integer values, entry skipped`

The error is coming from here
https://github.com/laravel/framework/blob/453508e8d03a274a6cc91dfdff6a91acf003b387/src/Illuminate/Pagination/AbstractCursorPaginator.php#L199

By the way using the same query with other paginators works perfectly fine

### Steps To Reproduce:

```php
Model::orderBy(
SomeOtherModel::select('name')->whereColumn('model.id', 'some_other_model.model_id')
)
```

**Comment by driesvints** [comment]
This isn't supported. A cursor based paginator needs a column with unique values to order.

**Comment by shadoWalker89** [comment]
@driesvints From my understanding cursor pagination does not stop you from using additional order by other then the primary key order by.

So this is the query that i'm aiming for 

`select * from `courses` order by `id` asc, (select `name` from `subjects` where `subjects`.`id` = `courses`.`subject_id`) asc limit 16`

Having two order by is not supported ?

**Comment by driesvints** [comment]
Sub queries aren't supported no. You're always free to attempt to make it work through a pr if you wish.
