### ISSUE TITLE
withTrashed on routes not working with route caching

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#38441]
- Laravel Version: 8.55.0
- PHP Version: 8.0.9
- Database Driver & Version: Postgres 13.4

### Description:
I've just started using `withTrashed` on routing which was introduced in #38348. I had test coverage to ensure that certain routes worked with soft deleted records, and those tests continued to pass following the change. Also worked as expected when testing in a browser.

However, once running `route:cache` the tests stop working. In the browser you'll now get a `404` when hitting a route with a soft deleted record. My tests fail when the routes have been cached, and pass again once the route cache has been cleared.

Something about route caching is preventing `withTrashed` from working.

### Steps To Reproduce:

1. Create a record and soft-delete it
```php
$user = User::factory()->create();

$user->delete();
```

2. Create a route using `withTrashed()`
```php
Route::get('/users/{user}', function (User $user) {
    return $user;
})->withTrashed();
```

3. Cache the routes
```sh
php artisan route:cache
```

4. Hit the route
```sh
curl -I http://laravel.test/users/1
```

**Comment by driesvints** [comment]
Thanks for reporting this. It'll be in next week's release.
