### ISSUE TITLE
Wrong password reset link sent when running laravel on /some-path

### ISSUE THREAD

**Issue by kushal9291** [laravel/framework#38458]
- Laravel Version: 8.12
- PHP Version: 8.0
- Database Driver & Version: mysql

### Description:
Currently I'm running Laravel on path /backend. I  also set APP_URL to domain.com/backend. 

However when I received password reset link it's directed to domain.com/reset-password instead of domain.com/backend/reset-password.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
