### ISSUE TITLE
OFFSET without LIMIT throws mysql syntax error

### ISSUE THREAD

**Issue by glingy** [laravel/framework#38452]
**What was the original problem?**
When using a paginator with a negative 'perPage' value, the limit clause is removed, but the offset remains, causing a mysql syntax error. I'm not sure if this is intended usage, but it seems useful to have a "no limit" value for a generic paginator. This also appears when using `->offset(0)` or `->forPage(0, -1)`. 

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0' at line 1 (SQL: select * from `contacts` offset 0) 
```

**Suggested fix**
Only apply offset clauses if a limit clause exists in the query prior to the offset clause.

**Example**
```
Route::get('/test', function()
{
	// Works as expected
	$contacts = \App\Models\Contact::limit(1)->offset(0)->get();
	
	// Mysql Error
	$contacts = \App\Models\Contact::offset(0)->get();
});
```

**Comment by driesvints** [comment]
This isn't supported.
