### ISSUE TITLE
[8.x] Array to string conversion error while checking response status code in unit tests

### ISSUE THREAD

**Issue by galvesband** [laravel/framework#38464]
- Laravel Version: >8.51.0
- PHP Version: 7.4.20
- Database Driver & Version: Not database related

### Description:

Sorry if this is not the right place for my issue. I'll try to be brief.

In [this pull](https://github.com/laravel/framework/pull/38025), exception tracking during unit testing is introduced. Looking at [FoundationServiceProvider](https://github.com/laravel/framework/pull/38025/commits/d74b8ca2bd07427babb9b792cdb475dea929848a) code you can see the exception tracking code checks the context of every logged event looking for an 'exception' key. The code assumes the content of that 'exception' key to be an exception (or at least something that can be turned into a string) and adds it to a LoggedExceptionCollection instance bound for the test.

This change brakes many of my unit tests, the reason being I tend to include exceptions in the context of log messages already transformed into arrays in an 'exception' key, so they end up nicely serialized in log files. The listener code that checks log events for exceptions in the FoundationServiceProvider just looks into the 'exception' key in the context and runs with its content, which is a bit too broad in my opinion. Am I the only one using 'exception' in log contexts already transforming its content into arrays? It seemed a somewhat reasonable compromise...

I understand I can work around this issue rewriting my code into exceptions that handle their own log representation and sending those exceptions in the logs, which is probably the long term better approach. But I don't think this behaviour is intended and the code that reports exceptions from log messages should not assume so much from the log context's content.

I'm reporting this because I think it is not intended. I'm a big fan of the project, by the way.

### Steps To Reproduce:

 - 1. Anywhere in your code reachable by an http request. For example in api.php:
    ```php
    Route::get('exception', function () {
      Log::info("Hi there", ['exception' => ['this can not be converted to a string']]);
      return response()->json(['The deed is done!']);
    });
    ```
 - 2. An integration test:
   ```php
   class ExceptionTest extends TestCase
   {
       /** @test */
       public function check_response_status()
       {
           $response = $this->json('GET', '/api/exception');
           $response->assertStatus(200); // Throws an "Array to string conversion" error
       }
   }
   ```

**Comment by X-Coder264** [comment]
https://github.com/Seldaek/monolog/issues/1535#issuecomment-813045906

So yes, it's a general convention that the `exception` key has an exception object.

**Comment by taylorotwell** [comment]
Yeah - no plans to change anything here. See comment above.
