### ISSUE TITLE
file_put_contents("cache_folder_path_which_is_not_present"): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0):

### ISSUE THREAD

**Issue by MORIKazuki** [laravel/framework#38478]
- Laravel Version: 6.20.2
- PHP Version: 7.4.15

### Description:
The issue is happening on APIs route with throttle:60,1 as a protection for these routes. I use the file driver cache.

For some requests but not all of them, I've got the following exception. It seems that the same user does not have this exception all the time.

```
file_put_contents(/{project root}/storage/framework/cache/data/{directory}/{directory}/{file name}): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/newsletter/storage/framework/cache/data/{directory}/{directory}/{file name}): failed to open stream: No such file or directory at //{project root}/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/{project root}...', 133, Array)
#1 //{project root}/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('//{project root}...', '1629462332i:162...', 2)
#2 //{project root}/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/newsle...', '1629462332i:162...', true)
#3 //{project root}/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(211): Illuminate\\Cache\\FileStore->put('fa755791d0509bb...', 1629462332, 60)
#4 //{project root}/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(316): Illuminate\\Cache\\Repository->put('fa755791d0509bb...', 1629462332, 60)
#5 //{project root}/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(60): Illuminate\\Cache\\Repository->add('fa755791d0509bb...', 1629462332, 60)
```

### Steps To Reproduce:

I tracked down the bug to the FileStore.php:74, where we can see a call to the ensureCacheDirectoryExists and the put which throw the exception but I don't get why in such a short period of time the directory exists.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by vrgblzs** [comment]
I bumped into a similar problem. The specific cache subdirectory the rateLimiter tried to write the values did exist, but was not writeable to www-data user. 

(and why? In my case because the `php artisan view:cache` command was issued by the root user, and it created this subdirectory with root user and group)
