### ISSUE TITLE
Validation rule parser removes unvalidated data from Form Requests

### ISSUE THREAD

**Issue by sander3** [laravel/framework#38505]
- Laravel Version: v8.55.0
- PHP Version: v8.0.8
- Database Driver & Version: N/A

### Description:
The new (https://github.com/laravel/framework/blob/578a76c2d53e416ce7037bc01c96be7877ed8442/src/Illuminate/Validation/ValidationRuleParser.php) validation rule parser removes any unvalidated data from Form Requests. Previously one could not define validation rules for a certain parameter in order to allow it pass through to the validated result array. While this might be intended behaviour, it is a change that breaks some applications.

### Steps To Reproduce:

1. Create a new Form Request
2. Define some validation rules
3. Add a parameter without validation rules
4. Call `$request->validated()`
5. See that the unvalidated data is missing

```php
public function rules()
{
    return [
        'title' => 'required|unique:posts|max:255',
        'body' => '',
    ];
}

```

**Comment by driesvints** [comment]
Thanks for reporting. I'll leave it to @taylorotwell to decide if that's a breaking change. Personally I don't think it is.

**Comment by Krisell** [comment]
Thanks @sander3 for reporting this, we hit the same issue now when we tried to update. 

Turns out we had lots of `'attribute' => ''` rules for some reason, just to include these in `$data->validated()` or being returned from the `->validate()`. 

Our tests caught this and using `'nullable'` instead seems to resolve it.

**Comment by Boorinio** [comment]
> Thanks @sander3 for reporting this, we hit the same issue now when we tried to update.
> 
> Turns out we had lots of `'attribute' => ''` rules just to include these in `$data->validated()` or being returned from the `->validate()` call.
> 
> Our tests caught this and using `'nullable'` instead seems to resolve it.

Nullable is not always the intended behaviour of those empty validation rules!

**Comment by sander3** [comment]
https://laravel.com/docs/8.x/validation#rule-present might cover it.

**Comment by taylorotwell** [comment]
Yeah, if you put `nullable` on the attribute or something that should cover it.
