### ISSUE TITLE
[8.x] schema:dump on mariadb gives error

### ISSUE THREAD

**Issue by eboye** [laravel/framework#38532]
- Laravel Version: 8.55.0
- PHP Version: 7.4.22
- Database Driver & Version: Ver 15.1 Distrib 10.6.4-MariaDB, for osx10.16 (x86_64) using readline 5.1

### Description:
When running `php artisan schema:dump` it throws an error:

```
mysqldump: Couldn't execute 'SHOW FUNCTION STATUS WHERE Db = 'table_name'': Cannot load from mysql.proc. The table is probably corrupted (1728)

Symfony\Component\Process\Exception\ProcessFailedException

The command "mysqldump  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --skip-add-locks --skip-comments --skip-set-charset --tz-utc "${:LARAVEL_LOAD_DATABASE}" --routines --result-file="${:LARAVEL_LOAD_PATH}" --no-data" failed.

Exit Code: 2(Misuse of shell builtins)

Working directory:

Output:
================


Error Output:
================
mysqldump: Couldn't execute 'SHOW FUNCTION STATUS WHERE Db = 'table_name'': Cannot load from mysql.proc. The table is probably corrupted (1728)

  at vendor/symfony/process/Process.php:270
    266▕      */
    267▕     public function mustRun(callable $callback = null, array $env = []): self
    268▕     {
    269▕         if (0 !== $this->run($callback, $env)) {
  ➜ 270▕             throw new ProcessFailedException($this);
    271▕         }
    272▕
    273▕         return $this;
    274▕     }

      +16 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Steps To Reproduce:

make a laravel project with some migrations using mariadb.
run `php artisan schema:dump`

**Comment by driesvints** [comment]
Please see the docs: https://laravel.com/docs/8.x/migrations#squashing-migrations

It's only available for MySQL, PostgreSQL and SQLite at this time.

![Screen Shot 2021-08-25 at 12 24 56](https://user-images.githubusercontent.com/594614/130774207-bbcc69e2-ad8d-4718-8a76-d221acd219fe.jpg)

**Comment by andrewminion-luminfire** [comment]
I just ran into this problem; running `mysql_upgrade` [as described here](https://github.com/laravel/framework/issues/35784) worked for me.

**Comment by eboye** [comment]
> I just ran into this problem; running `mysql_upgrade` [as described here](https://github.com/laravel/framework/issues/35784) worked for me.

WOW! Amazing! It worked! Thanks a bunch :D
