### ISSUE TITLE
HTTP Client not reusing Guzzle client

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#38539]
- Laravel Version: v8.54.0
- PHP Version: 8.0.8

### Description:

The HTTP Client is currently building a Guzzle client and telling it to persist cookies between requests:

``` php
public function buildClient()
{
    return $this->client = $this->client ?: new Client([
        'handler' => $this->buildHandlerStack(),
        'cookies' => true,
    ]);
}
```

But on every call we do it creates a new PendingRequest instance, which instantiates a Guzzle client from scratch:

``` php
public function __call($method, $parameters)
{
    if (static::hasMacro($method)) {
        return $this->macroCall($method, $parameters);
    }

    return tap($this->newPendingRequest(), function ($request) {
        $request->stub($this->stubCallbacks);
    })->{$method}(...$parameters);
}
```

Meaning it will not be able to persist a cookie received on a previous request. Unless it's a pool, but those are for async calls, and sometimes we just need to use the same client on synchronous requests.

This is something we can do on pure Guzzle that, seems to me, it's not possible with Laravel's implementation:

``` php
function getPosts()
{
    // Instantiate
    $client = new \GuzzleHttp\Client(['cookies' => true]);

    // Login payload
    $payload = '{
          "UserName": "user",
          "Password": "pass"
    }';

    // Do the login and keep the cookies
    $client->request('POST', 'https://site.com/login', [
        'body' => $payload,
    ]);

    // Use the cookies to get the posts
    $response = $client->request(
        'GET',
        'https://site.com/posts',
    );
}
```

**Comment by driesvints** [comment]
Hey @antonioribeiro. You're correct, it does seems that this is the way things work right now. However, I don't consider that a bug sorry. I do see your use case and maybe we can accept a PR that adds a new method to persist the cookies between requests?

**Comment by antonioribeiro** [comment]
Well, if `'cookies' => true` doesn't do what it's supposed to do because the class is not reusing the same client, that's definitely a bug.

Because:

- Cookies will not be forwarded to the next requests.
- The behaviour of cookies on an async pool are unknown, if they are all dispatched at the same time, cookies are not being persisted either.

So if you want to make it a feature, you need to remove `'cookies' => true` from the code and say in the docs _"This client will not persist your cookies."_
