### ISSUE TITLE
OpenSSL-bug for uppercase cipher names

### ISSUE THREAD

**Issue by Krisell** [laravel/framework#38558]
- Laravel Version: 8.56.0
- PHP Version: 7.3, 7.4
- Database Driver & Version: N/A

Support for GCM mode of operation encryption (AES-128-GCM and AES-256-GCM) was recently added. The default config file was also updated to use the new mode but that change was reverted after an error report (https://github.com/laravel/laravel/commit/c512ba2b160d1e87205dd45b60d8c0cfab230025). I have done some more digging into this problem with the help of @sangnguyenplus

When asking him for the result of `openssl_get_ciphers()`, the list included AES-128/256-GCM but only in lowercase, not in uppercase. Recent versions of OpenSSL only use lowercase names (but accept both), whereas in older versions both cases were used, however there seems to be a bug causing these lists to diverge and only lowercase to function where they differ. Switching from `AES-256-GCM` to `aes-256-gcm` did resolve the issue for @sangnguyenplus.

Here's this specific bug reported for OpenSSL and php repectively:
https://github.com/openssl/openssl/issues/6921
https://bugs.php.net/bug.php?id=74116

From my understanding, we can resolve this issue by always using the lower case names. The necessary changes in Laravel are minimal and non-breaking. Only `Encrypter.php` needs to be updated with `$cipher = strtolower($cipher);` in the constructor and updating the list of supported ciphers to lowercase. That way, the config file does not need to change.

This is not a PR because I would like some additional input/verification that lower case cipher names indeed work on all systems, for instance on Windows. I'm also not sure of the exact relationship between PHP versions and OpenSSL versions. Are these locked, or do they depend on the system such that even PHP 8 might have this problem?

**Comment by Krisell** [comment]
@sangnguyenplus could you by any chance do a `phpinfo()` and see what version of OpenSSL you have?

To answer my own question above, PHP is compiled with an installed version of OpenSSL, so this may differ on different systems for the same php version. There is also a `--with-system-ciphers` option which affects available ciphers.
https://www.php.net/manual/en/openssl.installation.php

Perhaps the only completely safe option is to actually peek at `openssl_get_cipher_methods()` and check for both upper- and lowercase, and pick the available version or throw a `Cipher Missing` exception. That of course complicates the code a little bit and I'm not sure of the performance aspects of asking for the cipher list (but probably negligible in comparison with actually performing an encryption). Another option is to assume the lower-case version and only use `openssl_get_cipher_methods()` if an exception is thrown when trying to use the cipher.

However, if the problem is rare and likely to be resolved over time (systems updates openssl), perhaps it is reasonable to just wait with using GCM as the default encryption mode and keep using the uppercase name for CBC mode.

**Comment by sangnguyenplus** [comment]
@Krisell Yes, it's here.
<img width="994" alt="Screen Shot 2021-08-28 at 5 48 57 PM" src="https://user-images.githubusercontent.com/6972407/131215541-8e9fbef2-9de3-4c84-80a4-9ac917cbbfd2.png">

**Comment by Jubeki** [comment]
@nunomaduro 
https://www.php.net/manual/en/function.openssl-get-cipher-methods.php#refsect1-function.openssl-get-cipher-methods-returnvalues

It says in the Return Values Section that it only returns lower case values:

_An array of available cipher methods. Note that prior to OpenSSL 1.1.1, the cipher methods have been returned in upper case and lower case spelling; as of OpenSSL 1.1.1 only the lower case variants are returned._

**Comment by Jubeki** [comment]
@Krisell 
https://www.php.net/manual/en/function.openssl-get-cipher-methods.php#refsect1-function.openssl-get-cipher-methods-returnvalues

It says in the Return Values Section that it only returns lower case values:

_An array of available cipher methods. Note that prior to OpenSSL 1.1.1, the cipher methods have been returned in upper case and lower case spelling; as of OpenSSL 1.1.1 only the lower case variants are returned._

**Comment by Krisell** [comment]
@Jubeki Yes for newer versions of OpenSSL all ciphers are lowercase (but the cipher string can be used case-insensitively, so no problem there). For older versions, it sounds (in the text you quoted) like all ciphers should be reported in both upper- and lowercase, but that is not the case (no pun intended). Since all uppercase cipher names did not work for @sangnguyenplus, I currently don't feel certain that lowercase will work in all versions and on all systems.

**Comment by driesvints** [comment]
Is there only one report about this so far? Because if this isn't a widespread issue then I'm not sure we can dedicate time to this and it might be better that someone proposes something through a PR.

**Comment by Krisell** [comment]
Since the default config was reverted, the number of developers that have tried GCM mode is probably low, and the ones that have tried it are perhaps more likely to use updated systems and versions of php where the problem doesn't exist.

However it's quite unfortunate if GCM mode can't be the default going forward since it does have performance and at least theoretical security advantages, and also it's quite hard for apps to migrate the cipher method in the future. I can try to attempt an all-lowercase PR, possibly in combination with `openssl_get_cipher_methods()`, and I'm also fine with closing this  issue for now until someone that's actually hit by the problem reports it.

**Comment by driesvints** [comment]
Yeah in that case I think it's best to close this for now. We'd very much appreciate a PR which will enable us to make GCM the default but safely so we don't break apps. Thanks @Krisell.
