### ISSUE TITLE
Has One Of Many not always working correctly

### ISSUE THREAD

**Issue by rubenvanerk** [laravel/framework#38574]
- Original issue: #38571
- Laravel Version: 8.56.0
- PHP Version: 8.0.9
- Database Driver & Version: MariaDB 10.6.4-1

### Why I recreated this issue:

I still believe this is a problem in Laravel. I asked around in various channels, but nobody was able to solve the problem (without changing Laravel itself).  
Since the previous issue was closed, I added [a new test](https://github.com/rubenvanerk/laravel-of-many-bug-report/commit/fcb8c8b44fa254e5cc1b3ae7487252206d091663) and [a workaround/hack](https://github.com/rubenvanerk/laravel-of-many-bug-report/commit/98d833d321ed31834969625e4542d6deaa057488) to my test repo that does give me the results I expect.

### Description:

I am using a Has One Of Many relationship and I'm passing a closure to further narrow down the results. In this closure, I'm querying a relationship. This goes well until there's a record with the same `min` (or `max`) value. Then the query on the relationship is ignored. Here's an example:

```php
class Product extends Model
{
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}


class Category extends Model
{
    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

class Brand extends Model
{
    public function cheapestProduct(): HasOne
    {
        return $this->hasOne(Product::class)->ofMany(['price' => 'min'], function ($query) {
            $query->whereHas('category', function ($query) {
				  // this is ignored if there are 2 products with the same lowest price
                $query->where('published', true);
            });
        });
    }
}
```

I then make 2 categories, one published and one not. I put some products in both categories that all have the same brand. Assume there are 2 products in both categories that both have the same, lowest price of all products.  
If I then run `Brand::first()->cheapestProduct`, I get the last inserted product of the 2 cheapest products, which can have a category that is not published.

### Steps To Reproduce:

1. Clone my [bug report project](https://github.com/rubenvanerk/bug-report) for this issue
2. Run the test, or seed the database and go to `/`

**Comment by cbl** [comment]
Hey @rubenvanerk, could you share the generated mariadb query, maybe in a [fiddle](https://dbfiddle.uk/?rdbms=mariadb_10.6).

Please do not use the workaround as it is wrong. It may fix this specific case but it will break other behaviour.

**Comment by rubenvanerk** [comment]
Thanks for looking into this @cbl, here's the fiddle: https://dbfiddle.uk/?rdbms=mariadb_10.6&fiddle=a3b47792122e8903323866b6cd262ba5

I wasn't planning on using the workaround, but I thought it could point someone into the right direction.

**Comment by cbl** [comment]
This query shows a `MAX(id)` where else there should be a `MIN(id)`:

<img width="617" alt="Bildschirmfoto 2021-09-01 um 15 51 07" src="https://user-images.githubusercontent.com/29352871/131683493-4ca88229-59ea-425c-9766-ca565c6ad17b.png">

When I replace `MAX` -> `MIN` it returns the correct result. I wonder why this happens for the MariaDB driver. Is this the query that was generated from the example code in your bug-report repository?

**Comment by rubenvanerk** [comment]
It's just a coincidence that it gives you the correct result when you change `MIN(id)` to `MAX(id)`. If you use `MIN(id)` and swap which categories are published, then it gives a wrong result again: https://dbfiddle.uk/?rdbms=mariadb_10.6&fiddle=dde4e68b8855b097521c438cf57fbc76. This outputs a product that is in an unpublished category.

I don't think this is specific to MariaDB, if you switch to MySQL it also gives the wrong result: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=dde4e68b8855b097521c438cf57fbc76

The query is generated with the [bug report repository](https://github.com/rubenvanerk/bug-report) by running the project and visiting `/`. I copied the query from [debugbar](https://github.com/barryvdh/laravel-debugbar)

**Comment by driesvints** [comment]
@cbl did you have any more insights for the above?

**Comment by cbl** [comment]
Hey, sorry for the late response, I have been very busy lately.

@rubenvanerk I think I found the issue. When we only run the inner join query ([fiddle](https://dbfiddle.uk/?rdbms=mariadb_10.6&fiddle=8012a4a9de225fbca97b8361be57ba44)), the results show, that only a `price` and a `brand_id` is returned which is then used to  load the result with the min id. However the `category_id` is needed as well to restrict the group.

When I add the `category_id` to the join constraints, the correct result is loaded: [fiddle](https://dbfiddle.uk/?rdbms=mariadb_10.6&fiddle=21d6548e291b267b4a130866831cc353)

This in fact seems like an edge case that I haven't thought of before.  We need to find a way to access the join clause builder within the relationship method of your model.

**Comment by cbl** [comment]
I'll try to come up with a pr to solve this.

**Comment by driesvints** [comment]
Since only one person has reported this so far I'm going to close this one. Feel free to send in a PR so we can accommodate for this edge case. Thanks
