### ISSUE TITLE
Error while using laravel failover mailer with queue

### ISSUE THREAD

**Issue by obinnaelviso** [laravel/framework#38578]
- Laravel Version: 8.57.0
- PHP Version: 8.0.8
- Database Driver & Version: 10.4.20-MariaDB

### Description:
I set up my Laravel application Mail with the failover mailer according to the documentation.
https://laravel.com/docs/8.x/mail#failover-configuration
It works fine when I send mail directly but fails when I send mail using queue, thereby giving the error below:

InvalidArgumentException: Mailer [failover] is not defined. in /path/to/app/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php:111

**Comment by Jubeki** [comment]
I tried it on a fresh laravel application: https://github.com/Jubeki/laravel-bug-report-38578

It's working as intended. Please ask on a support channel for help. Probably something is still misconfigured.
https://laravel.com/docs/8.x/contributions#support-questions

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks @Jubeki
