### ISSUE TITLE
Default parameters not included in URI as query string

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#38607]
- Laravel Version: 8.6.1
- PHP Version: 7.4

### Description:

Parameters set by `\Illuminate\Contracts\Routing\UrlGenerator::defaults([...])` are only included if the routes contain placeholders for that parameters. Otherwise, they are ignored and not added as query string parameters.

### Steps To Reproduce:

In routes/web.php:
```
 Route::get('/', '\App\Http\Controller\TestController@indexAction')->name('test');
```
During bootstrapping:
```
\Illuminate\Contracts\Routing\UrlGenerator::defaults( ['currency' => 'EUR'] );
```
In Blade template:
```
route('test');
```

Expected result would be `/?currency=EUR`, actual result is `/`.

The problem is here:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteUrlGenerator.php#L84-L88

**Comment by driesvints** [comment]
This is expected.
