### ISSUE TITLE
Call to undefined method when using nested relationships on aggregate function

### ISSUE THREAD

**Issue by adesege** [laravel/framework#38603]
- Laravel Version: 8.57.0
- PHP Version: 8.0
- Database Driver & Version: Postgres 13

### Description:
`Call to undefined method` error is thrown when using nested relationship on aggregate functions like `withAvg`. I was able to debug this and found out that `getRelationWithoutConstraints` is directly calling the relation parameter as a function.

In my use case, I'm trying to get the average of book reviews from a shelf model.

```php
Shelf::withAvg('books.reviews', 'rating');
```

Getting the reviews directly from the book model works fine, however.

Related to #38049 and #38079 

### Steps To Reproduce:

1. Create 3 models with the following relationships; A -> B -> C.
1. Then get the average of `C` through model A; `A::withAvg('b.c', 'd')`; // This will throw an error
1. If you do `B::withAvg('c', 'd')` instead, it will not throw an error.

**Comment by driesvints** [comment]
This is a feature request.
