### ISSUE TITLE
Custom `MorphPivot` pivot model's `$table` attribute not respected.

### ISSUE THREAD

**Issue by David-Petrov** [laravel/framework#38616]
- Laravel Version: 8.58.0
- PHP Version: 7.4.22
- Database Driver & Version: MySQL

### Description:
When using a custom `MorphPivot` intermediate table model with a `$table` property set, the `morphedByMany` and `morphToMany` relationship methods don't respect it to deduce the pivot table's name, even when `->using()` has been set, and it's still necessary to pass the table's name explicitly.

### Steps To Reproduce:
A repository with a minimal working example can be found [here](https://github.com/David-Petrov/MorphPivotWithTable).

**Comment by driesvints** [comment]
Please use a dedicated Eloquent model when you need to do that.
