### ISSUE TITLE
Cannot queue a Job that has a circular reference in the model property - fails serializing

### ISSUE THREAD

**Issue by powellblyth** [laravel/framework#38614]
- Laravel Version: Laravel Framework 8.56.0
- PHP Version: PHP 8.0.9
- Database Driver & Version: Mysql 8.0.35 (sail)
- Sail version 1.10.1

### Description:
The steps are in the readme, I hope that's clear enough (lots of context). Basically with a model (model 1) with a reference to another model (model 2) that  relates to Model 1, the job silently fails to create, and wont dispatch synchronously

The example above is derived from a real world problem, but I tried to make it simple with a Book / Shelf example.

### Steps To Reproduce:
https://github.com/powellblyth/laravel-recursive-jobs-issue
The steps are in the readme, I hope that's clear enough (lots of context). Basically with a model (model 1) with a belongsTo relation to another model (model 2) that has a belongsTo relation to Model 1, the job silently fails to create, and wont dispatch synchronously

**Comment by driesvints** [comment]
This indeed isn't supported. You should build your job in a way that the circular dependency is not present. The example you gave with the primary identifiers is a good solution to the problem.
