### ISSUE TITLE
Route namespace is not taken into account on some route declarations

### ISSUE THREAD

**Issue by ipontt** [laravel/framework#38645]
- Laravel Version: 8.55.0
- PHP Version: 7.4.0
- Database Driver & Version: sqlite

### Description:
Controller namespace is not taken into account in certain routes.

### Steps To Reproduce:

Declare a route group with a namespace. 
```php
<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::middleware('web')
                ->namespace('App\\Http\\Controllers')
                ->group(base_path('routes/web.php'));
        });
    }
}
```
Declare a route with the syntax `Route::{verb}({uri}, [{controller}, {action}]);` inside the `routes/web.php` file. (I found the bug with a `put` route but I don't think that's relevant)
```php
Route::get('user/action', [UserController::class, 'action'])->name('user.action');
```
Run artisan `r:l` command, an exception will be thrown.
 
> 
>   Illuminate\Contracts\Container\BindingResolutionException
>
>  Target class [UserController] does not exist.
>

A workaround is using `uses()` instead. 

```php
// invokable
Route::get('user/action', UserController::class)->name('user.action'); // works
// resource
Route::resource('users', UserController::class); // works
// explicitly using uses()
Route::get('user/action')->uses([UserController::class, 'action'])->name('user.action'); // works
```

https://github.com/ipontt/Laravel-Challenge-Cleanup-Routes/commit/526ce676e31715b48c90789339969c313a8a1c35

**Comment by driesvints** [comment]
You can't use the `::class` notation like that in combination with the `->namespace` method. Either clear the namespace and use `::class` or add the namespace and use `UserController@action`.

**Comment by ipontt** [comment]
That seems pretty arbitrary.
