### ISSUE TITLE
Illuminate\Testing\PendingCommand::doesntExpectOutput() does not accept patterns

### ISSUE THREAD

**Issue by raszi** [laravel/framework#38657]
- Laravel Version: v8.58.0
- PHP Version: 7.4.16
- Database Driver & Version: does not matter

### Description:

If in your console command you are writing multiple lines to the output then the only chance to write a proper test for it is to use the `Mockery::pattern()` method to create and match patterns:

#### Working code

```php
public function test(): void
{
    $this->artisan('command')->expectsOutput(Mockery::pattern('/foo.*?bar/s'));
}
```

It works as expected but `Illuminate\Testing\PendingCommand::doesntExpectOutput()` uses the not expected value as the key of an associative array which makes it impossible to use `Mockery::pattern()`.

#### Example code:

```php
public function test(): void
{
    $this->artisan('command')->doesntExpectOutput(Mockery::pattern('/foo.*?bar/s'));
}
```

This will throw an error like:

```
ErrorException: Illegal offset type

/path/to/source/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:144
/path/to/source/tests/ExampleTest.php:15
```

**Comment by driesvints** [comment]
Hi there, this seems like a feature request to me so I'm moving it to the discussions section instead.
