### ISSUE TITLE
Event Listener Queue Error Number Format

### ISSUE THREAD

**Issue by muhammadnan** [laravel/framework#38665]
- Laravel Version: 8.58.0
- PHP Version: 8.0.7
- Database Driver & Version: psql (PostgreSQL) 13.4 (Ubuntu 13.4-0ubuntu0.21.04.1)

### Description:
I don't know if this is a bug or not, but I ran into a problem when when I tried to dispatch an event listener with a queue, the error was **`number_format(): Argument #2 ($decimals) must be of type int, string given`**
this error does not occur in the context of the same table but only differs in the delivery of the data payload.
lately, this problem occurs only with me implementing queue but if without queue it runs smoothly as usual.

- first payload

![Screenshot 2021-09-03 at 21-10-38 Order Baru - Great SMM](https://user-images.githubusercontent.com/30528814/132019342-ffbc9aaf-02d5-499f-8dd7-c4d413ce1edf.png)

- after i dispatchevent then send it to queue via listener it generates error like this

![Screenshot 2021-09-03 at 21-13-05 Order Baru - Great SMM](https://user-images.githubusercontent.com/30528814/132019600-a5880867-2cdc-463a-9d01-6f5ab54d7471.png)

- then after that I tried to create another payload but in the context of the same table, here is the payload: 

![Screenshot 2021-09-03 at 21-15-55 Order Baru - Great SMM](https://user-images.githubusercontent.com/30528814/132020103-4e255bfd-ba5a-4a8b-9ec1-a80abbd51782.png)

- then then i do resubmit and generate this
![Screenshot 2021-09-03 at 21-00-07 Order Baru - Great SMM](https://user-images.githubusercontent.com/30528814/132020437-75a15faf-24cb-4f9e-b9c8-f2b6f6fded7b.png)

this my event code
```
<?php

namespace App\Events\User\Order;

use App\Models\Service;
use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use App\Models\ServiceOrder;

class OrderProcessed
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(
        public ServiceOrder $order
    )
    {}
}
```
and this my listener
```
<?php

namespace App\Listeners\User\Order;

use App\Events\User\Order\OrderProcessed;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
//
class SendOrderToApi implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * The number of seconds the job can run before timing out.
     *
     * @var int
     */
    public $timeout = 3600;

    /**
     * The number of times the queued listener may be attempted.
     *
     * @var int
     */
    public $tries = 5;

    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  OrderProcessed  $event
     * @return void
     */
    public function handle(OrderProcessed $event)
    {

        dd(
            $event
        );
    }
}
```

thanks

**Comment by gorge2004** [comment]
did you add event and listener to EventServiceProvider?
