### ISSUE TITLE
Type Error (missing argument) Illuminate\Queue\Console\RestartCommand

### ISSUE THREAD

**Issue by bruno-farias** [laravel/framework#38661]
- Laravel Version: 8.56.0
- PHP Version: 8.0.0
- Database Driver & Version: MySql 5.7

### Description:

Upgrading from Laravel 8.55.0 to newer versions break tests using Cache::spy() and multiple tests cases, running individually seems to not be an issue, but together they break with the following stack trace:

TypeError: Illuminate\Queue\Console\RestartCommand::__construct(): Argument #1 ($cache) must be of type Illuminate\Contracts\Cache\Repository, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php on line 751

/var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/RestartCommand.php:40
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php:751
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:869
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:754
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:841
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:692
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:826
/var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:260
/var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:274
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:396
/var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:151
/var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:74
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:330
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:263
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:219
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:367
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:66
/var/www/html/tests/Feature/Commands/SendUsageNotificationsTest.php:271

It seems related to the change introduced in version 8.58.0 at src/Illuminate/Cache/CacheServiceProvider.php
`
$this->app->singleton(RateLimiter::class, function ($app) {
    return new RateLimiter($app->make('cache')->driver(
        $app['config']->get('cache.limiter')
    ));
});
`

Changing to the previous version it fixes the issue:
`
$this->app->singleton(RateLimiter::class);
`

### Steps To Reproduce:

Write multiple tests using Cache::spy() and Cache::shouldReceive();

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
