### ISSUE TITLE
artisan migrate:fresh does not work with --database parameter when using schema:dump

### ISSUE THREAD

**Issue by dreadkopp** [laravel/framework#38682]
- Laravel Version: 8.58.0
- PHP Version: 8.0.10
- Database Driver & Version: mariadb 10.4

### Description:

artisan migrate:fresh command will ignore restore of schema dump when using --database parameter

### Steps To Reproduce:

 - create a fresh project (https://laravel.com/docs/8.x/installation)
 - copy mysql connection in config/database.php , name it migration_connection
 - install mysqldump and mariadb-client in laravel.test container ($apt-get update && apt-get install mariadb-client)
 - create a db dump via artisan schema:dump and clear the existing migrations (./vendor/bin/sail artisan schema:dump --prune)
 - run artsan migrate:fresh --database=migration_connection 
 - see that schema dump is not applied and database is empty

```
    ~/Dokumente/php/example-app  ./vendor/bin/sail artisan migrate:fresh                                                                                                                                   ✔ 
Dropped all tables successfully.
Migration table created successfully.
Loading stored database schema: /var/www/html/database/schema/mysql-schema.dump
Loaded stored database schema. (220.25ms)
Nothing to migrate.


    ~/Dokumente/php/example-app  ./vendor/bin/sail artisan migrate:fresh --database=migration_connection                                                                                                   ✔ 
Dropped all tables successfully.
Migration table created successfully.

```

**Comment by driesvints** [comment]
This indeed is not supported

**Comment by sca1235** [comment]
Would be nice to add this feature. For security purposes we have separate db connections to run migrations.
