### ISSUE TITLE
\Illuminate\Encryption\Encrypter::supported now expects a lowercase value when it previously expected an uppercase value

### ISSUE THREAD

**Issue by Sn0wCrack** [laravel/framework#38690]
- Laravel Version: 8.58.0
- PHP Version: 7.3.0
- Database Driver & Version: N/A

### Description:

In prior versions of Laravel, the \Illuminate\Encryption\Encrypter::supported function would expect an uppercase cipher, however, it appears since the recent changes with adding GCM support has made running this function expect a lowercase value instead.

This has recently caused a breakage in code where we run this particular function, and as our cipher value was in all uppercase rather than all lowercase this caused encryption related code to begin failing due to an unsupported key.

### Steps To Reproduce:

Use illuminate/encryption v8.54.0 and run the supported function with an uppercase cipher ran and it should return true.

Use illuminate/encryption v8.58.0 and run the support function with an uppercase cipher and it will now return false.

**Comment by Krisell** [comment]
You're right @Sn0wCrack, the switch to lowercase was made due to a bug in OpenSSL that uppercase did not work in all versions for the GCM mode specifically. However, we definitely should perform the `strtolower()` in the supported method as well. I'll make a PR for this.
