### ISSUE TITLE
Route resource parameter rename not working

### ISSUE THREAD

**Issue by zynth17** [laravel/framework#38709]
- Laravel Version: 8.40
- PHP Version: 7.4.3
- Database Driver & Version: 8.0.24

### Description:
the route resource parameter rename does not work
i've try to change it but it still showing the old one
i've try to clear the route cache does not work also

```php 
  Route::get('tipe-servis/table', [TipeServisController::class, 'table'])->name('tipe-servis.table');
  Route::get('tipe-servis/unpaginate', [TipeServisController::class, 'unpaginate'])->name('tipe-servis.unpaginate');
  Route::resource('tipe-servis', TipeServisController::class)
      ->except('show')
      ->parameter('tipe_servi' , 'tipe_servis')
      ->missing(fn () => (redirect()->route('tipe-servis.index')));
```

the result on the artisan route:list

![image](https://user-images.githubusercontent.com/45350572/132459867-2939bc5f-1e1b-48e6-a03e-90b6a8ced8fc.png)

### Steps To Reproduce:
1. create resource controller
2. try to change the parameter using the parameter method

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
