### ISSUE TITLE
Custom date casting results in false positive attributes in $model->getDirty()

### ISSUE THREAD

**Issue by macbookandrew** [laravel/framework#38719]
- Laravel Version: 8.60.0
- PHP Version: 8.0.9
- Database Driver & Version: n/a

### Description:

Model attributes cast as custom date(time) formats are incorrectly marked as dirty attributes when the value has not in fact changed.

I first noticed this happening as part of a Livewire controller, but it’s not limited to just Livewire.

### Steps To Reproduce:

Example repository: https://github.com/macbookandrew/laravel-bug-report/

Simple example:

1. Add a [custom date(time) cast](https://github.com/macbookandrew/laravel-bug-report/blob/e44c1422b154b02bb59c2aedae3c9ce45798bc2d/app/Models/Event.php#L18) to a model attribute
2. Use `$model->getDirty()`/`$model->isDirty('<attribute name>')` to determine whether it’s changed (e.g., to [send a notification](https://github.com/macbookandrew/laravel-bug-report/blob/e44c1422b154b02bb59c2aedae3c9ce45798bc2d/app/Observers/EventObserver.php#L18-L20) to event registrants)
3. If the attribute is not the exact same `Carbon`/`CarbonImmutable` instance  [even with the **same** datetime value](https://github.com/macbookandrew/laravel-bug-report/blob/e44c1422b154b02bb59c2aedae3c9ce45798bc2d/tests/Feature/EventDateTest.php#L41) (i.e., if Livewire or something else has rehydrated the model or attribute), the `$model->getDirty()`/`$model->isDirty()` falsely reports that it has changed

Cause: the `HasAttributes` `originalIsEquivalent` method does not treat custom date/immutable_date attributes as date objects and does a strict comparison; if the Carbon instance has changed, it fails.

Suggested solution: if an attribute `isDateCastable()` then compare them using `fromDateTime()` rather than creating new Carbon instances and comparing them.

**Comment by macbookandrew** [comment]
Perhaps similar to #36582

**Comment by driesvints** [comment]
Thanks. Let's see how your PR goes.

**Comment by macbookandrew** [comment]
@driesvints In general would you prefer a bug report issue + a PR, or just a PR with all the details there?

**Comment by driesvints** [comment]
If you can send a PR right away it's always best to include all the details on the PR so taylor has the best picture at what it fixes. Thanks!
