### ISSUE TITLE
Memcached: persistent-connection does not work with options.

### ISSUE THREAD

**Issue by junjihashimoto** [laravel/framework#38727]
- Laravel Version: All
- PHP Version: All
- Database Driver & Version: 
    php-memcached (https://github.com/php-memcached-dev/php-memcached)
      Version: All

### Description:

Current memcached driver always call `setOptions`-method when creating memcached-object.
We should avoid calling `setOptions` when we already have a connection.
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/MemcachedConnector.php#L18-L59

Some options quit connections by calling `send_quit`-function  of libmemcached library every time, so persistent-connection does not work.
https://github.com/awesomized/libmemcached/blob/193e5b33334e6209b87d23740a93db8eeef942b1/src/libmemcached/behavior.cc#L48-L282

The options are as follows.

```
Memcached::OPT_BINARY_PROTOCOL
Memcached::OPT_NO_BLOCK
Memcached::OPT_USE_UDP
Memcached::OPT_TCP_NODELAY
Memcached::OPT_TCP_KEEPALIVE
Memcached::OPT_SOCKET_SEND_SIZE
Memcached::OPT_SOCKET_RECV_SIZE
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by driesvints** [comment]
Also next time please fill out the full issue template with versions.

**Comment by junjihashimoto** [comment]
Thank you for kindly telling me about channels. I will open a new issue with versions.

**Comment by junjihashimoto** [comment]
@driesvints 
I've opened a thread on laravel.io.
https://laravel.io/forum/memcached-persistent-connection-does-not-work-with-options
