### ISSUE TITLE
Serializable interface is depreciated.

### ISSUE THREAD

**Issue by rakshit087** [laravel/framework#38732]
- Laravel Version: 8.6.2
- PHP Version:  8.1.0RC1
- Database Driver & Version: None

### Description:
After the PHP update 8.1, the Serializable interface is deprecated, however, illuminate/queue uses it, which is breaking the installation.

### Steps To Reproduce:
1. Update Laravel to Latest Version (If you are using Globel Installation) and create a new application by `laravel new example-app`  or directly create a new app by `composer create-project laravel/laravel example-app`
2.  You will get this error `  Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in
   addition, if support for old PHP versions is necessary)`
I am attaching relevant screenshots. :)

![image](https://user-images.githubusercontent.com/50898928/132677479-1645019b-761f-484a-9cfe-1fade2a32188.png)
![image](https://user-images.githubusercontent.com/50898928/132677505-64792330-d324-41b6-9c4d-0b68e9f1069e.png)

**Comment by Jubeki** [comment]
A PR for PHP 8.1 Support is already in draft state. https://github.com/opis/closure/pull/103

Also for PHP 8.1 Support in Laravel is currently on its way. https://github.com/laravel/framework/pull/38404

**Comment by rakshit087** [comment]
Great! Thanks, closing the issue. :)
