### ISSUE TITLE
PHP min requirements changed to v7.4 during L8 lifecycle

### ISSUE THREAD

**Issue by abejenaru** [laravel/framework#38747]
- Laravel Version: 8
- PHP Version: 7.3
- Database Driver & Version: -

### Description:
Laravel 8 changed minimum PHP version requirement during a minor release (traced it back to the dependency on league/config v1.1.0).
Now we are stuck on v8.49 as we don't have control over our hosting environment (presumably it will get upgraded to PHP 7.4, but that is handled by another division of a big institution with their own agenda).
I'm not expecting a fix for this, what I will appreciate is that you are careful not to make breaking changes during minor releases.

Cheers!

**Comment by Jubeki** [comment]
Commonmark 1.6 still uses php ^7.1 so maybe you should require common mark ^1.6 instead of ^2.0.
Laravel 8.x should support both

**Comment by lk77** [comment]
Laravel 8 is supporting 7.3, there is php tests for it.

**Comment by X-Coder264** [comment]
league/config v1.1.0 requires PHP >= 7.4

The only way you could get it is if you ran `composer update` on a PHP 7.4+ installation so this is not Laravel's fault.

You should always run `composer update` on the same version as you have on production to avoid issues like this.

**Comment by driesvints** [comment]
Please see the above

**Comment by abejenaru** [comment]
> league/config v1.1.0 requires PHP >= 7.4
> 
> The only way you could get it is if you ran `composer update` on a PHP 7.4+ installation so this is not Laravel's fault.
> 
> You should always run `composer update` on the same version as you have on production to avoid issues like this.

Thank you @X-Coder264, indeed that was the case and of course, totally not Laravel's fault.
Very unexpected on our side and a surprisingly quiet behavior from Composer; at least you can _fix_ it to a specific version of PHP using the config settings "platform->php".
