### ISSUE TITLE
The regex taken from Symfony being used in `validateUrl` is not correct

### ISSUE THREAD

**Issue by summercms** [laravel/framework#38761]
- Laravel Version: all versions
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

The code found here: https://github.com/laravel/framework/blob/240bf68c252a2cc21a68658f92a3356c3b073559/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1907-L1937

This is not correct and doesn't bother to check the IANA standards which lists the URI scheme formats.

Currently Laravel is giving incorrect results.

It's seems like the Laravel team have just assumed the code taken from Symfony is correct and not done any proper testing!

### Steps To Reproduce:

If you look at the regex it just gives a list of protocols followed by `://` on code line: https://github.com/laravel/framework/blob/240bf68c252a2cc21a68658f92a3356c3b073559/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1919

The trouble with this is that half of the protocols listed in IANA do not use `://`

Here's an example:

The protocol `bitcoin` found here: https://www.iana.org/assignments/uri-schemes/prov/bitcoin

Scheme syntax:

```
bitcoin:<address>[?[amount=<size>][&][label=<label>][&][message=<message>]]
```

Above says it's using `:` and not `://` after the protocol name `bitcoin`

This page gives even more examples: https://en.bitcoin.it/wiki/BIP_0021

Notice none have `://` and all use `:` after the protocol name `bitcoin`

e.g.

```
bitcoin:<address>
```

not

```
bitcoin://<address>
```

### Laravel Tests

```php
$value = 'bitcoin://34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo';
$attribute = 'url';

var_dump(validateUrl($attribute, $value));
```

Outputs the result of `bool(true)` which is incorrect.

```php
$value = 'bitcoin:34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo';
$attribute = 'url';

var_dump(validateUrl($attribute, $value));
```

Outputs the result of `bool(false)` which is incorrect.

---

You can repeat the test for many other protocols listed in IANA and you will see the exact same error!

**Comment by summercms** [comment]
@driesvints Can you give a reason why you would close this issue, when I have reported a bug and shown steps to repeat the bug in the code!  Have I reported this issue in the wrong place or does Laravel just want to create a buggy framework? I would like to help to get this code issue fixed.

**Comment by Jubeki** [comment]
Take a look at this issue: https://github.com/laravel/framework/issues/29301

It is primarily used for validating http:// and https:// URLs
If you want URI support another validator needs to be used.
(URL <> URI <> URN)

**Comment by summercms** [comment]
@Jubeki Thank you.

**Comment by summercms** [comment]
As per conversation Symfony side:

> Note this is a URL validator, not a URI one. AFAIK the // is required in URLs.

The issue here is that Laravel has URI's listed in the regex on this code line:

https://github.com/laravel/framework/blob/240bf68c252a2cc21a68658f92a3356c3b073559/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1919

It would be better if the URI schemes got removed from the regex and the URL ones were kept. only.

**Comment by summercms** [comment]
As per conversation Symfony side:

> Note this is a URL validator, not a URI one. AFAIK the // is required in URLs.

The issue here is that Laravel has URI's listed in the regex on this code line:

https://github.com/laravel/framework/blob/240bf68c252a2cc21a68658f92a3356c3b073559/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1919

It would be better if the URI schemes got removed from the regex and the URL ones were kept only.

For reference examples can be found here: https://en.wikipedia.org/wiki/List_of_URI_schemes

**Comment by driesvints** [comment]
@summercms please don't submit issues by skipping things in the issue template

**Comment by lk77** [comment]
I don't think it's possible to have one rule that will work for everyone. There is so many protocols out there. 
I think having something like `'url:https,sftp,wss'` for example would be more usefull
