### ISSUE TITLE
$connection property ignored in migrations

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [laravel/framework#38777]
- Laravel Version: 8.60.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8.0.25

### Description:
The [documentation](https://laravel.com/docs/8.x/migrations#setting-the-migration-connection) states that you can create a migration connection by using the $connection property. I have done this with 70 migrations in my project and can confirm that the default connection was used for all migrations. 

### Steps To Reproduce:
1. Create a second database
2. Create a new migration that you wish to use with the second database
3. Add `protected $connection = 'second_database';` to the top of your migration.
4. Run migration.

The migration should use the connection specified in the `$connection` property, but it will ignore it and use the default connection.

**Comment by derekmd** [comment]
Commit that changed the behavior starting in laravel/framework 7.0.0: https://github.com/laravel/framework/commit/f4bd05fc1015a1a49dd6850d6817a10d129143c8

Pull request https://github.com/laravel/framework/pull/35842 was rejected earlier this year but I think only because it lacked a bug report description and the addition of tests to cover documented behavior.

**Comment by lk77** [comment]
I've tested it and it work :

```
class TestMigration extends Migration
{
    protected $connection = 'does_not_exist';
    [...]
}
```

```
Migrating: 2021_09_13_090345_test_migration

   InvalidArgumentException 

  Database connection [does_not_exist] not configured.

  at vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:152
    148▕         // If the configuration doesn't exist, we'll throw an exception and bail.
    149▕         $connections = $this->app['config']['database.connections'];
    150▕ 
    151▕         if (is_null($config = Arr::get($connections, $name))) {
  ➜ 152▕             throw new InvalidArgumentException("Database connection [{$name}] not configured.");
    153▕         }
    154▕ 
    155▕         return (new ConfigurationUrlParser)
    156▕                     ->parseConfiguration($config);

      +23 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
