### ISSUE TITLE
Eager Loading withCount() ignores distinct()

### ISSUE THREAD

**Issue by ascentcreative** [laravel/framework#38799]
- Laravel Version: 8.60.0
- PHP Version: 7.4.16
- Database Driver & Version: 8.0.18

### Description:

When running a belongsToMany query, with 'distinct()' set, getting the collection shows the right (distinct) models, so if I count that collection it shows the right value.

However, using that in a list of items runs the query each time, so I wanted to use withCount to eager load it. This ignores the 'Distinct' and returns a user for each intermediary table row. 

It seems to be an issue with the hard coded '*' on line 559 of Illuminate\Database\Eloquent\Concerns\QueriesRelationships. 

This produces a sub-select of

```
... (select count(*) from users inner join comments on users.id = comments.user_id where posts.id = comments.post_id) as users_count ...
```

If I manually run the full query, but edited to 

```
... (select count(distinct users.id) from users inner join comments on users.id = comments.user_id where posts.id = comments.post_id) as users_count ...
```
I get the correct number in the users_count column

If the withCount() function definition could be made to detect the distinct flag from the Query Builder, and insert the foreign table id, that might correct it (however, I'm guessing from an initial dive into the code).

(Sorry for pulling this in as a discussion initially - didn't realise that was bad form...)

### Steps To Reproduce:

Repository: https://github.com/ascentcreative/withcountexample

The welcome blade loads all posts and demonstrates the issue with the columns in the table. 

It also shows the query as generated by the current laravel code, and the suggested correct query if the code honours the distinct.

1) Create three models with a belongsToMany relationship (Post / Comment / User) where Comment has both post_id and user_id columns

2) On the Post, create a function to get the distinct users via the comments:

```
public function users() 
{
     return $this->belongsToMany(User::class, Comments::class)->distinct();
}
```

3) `$post->users->count()` <- This produces the correct number

4) Eager load a query using `Post::withCount('users')->get()` - duplicates the users in the count for each comment they have left - i.e. the Distinct does not fire.

**Comment by driesvints** [comment]
This seems like an edge case to me as we haven't received any other reports for this. I don't think we'll spend time investigating this ourselves but we're always open to prs if you want to send one in. Sorry

**Comment by ascentcreative** [comment]
Ah ok - that's a shame, as it creates a performance hit. I'll take a look at a PR (but I'm pretty new to the codebase).

**Comment by sezohessen** [comment]
The same issue
