### ISSUE TITLE
installation issue at localhost

### ISSUE THREAD

**Issue by fazlur10** [laravel/framework#38806]
when i try to install a laravel application at localhost and run following errors occur, How can i solve these?
Fatal error: Uncaught RuntimeException: A facade root has not been set. in C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:258 Stack trace: #0 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(426): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array) #1 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(403): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #2 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(314): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException)) #3 C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(211): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Compone in C:\xampp\htdocs\mahar.lk\install\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 258

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
