### ISSUE TITLE
When `then()` callback adds a job to batch, it creates a loop

### ISSUE THREAD

**Issue by radmen** [laravel/framework#38804]
- Laravel Version: 8.60.0
- PHP Version:  8.0.8
- Database Driver & Version: probably all (tested on Sqlite & Postgres 13)

### Description:

When creating a batch with `then()` callback, the batch will loop over the given `then()` if it adds other jobs to the batch.

### Steps To Reproduce:

Create a following batch:

```php
<?php

Bus::batch([
    function () {
        logger()->debug('-----> Start');
    },
])->then(function (Batch $batch) {
    logger()->debug('Then()');

    if ($batch->createdAt->diffInSeconds(now()) < 5) {
        sleep(1);
        $batch->add(function () { });
    }
})->finally(function () {
    logger()->debug('-----> Done!');
})->dispatch();
```

### Actual result

(this is an excerpt from logs)

```
[2021-09-13 22:14:31] local.DEBUG: -----> Start
[2021-09-13 22:14:31] local.DEBUG: Then()
[2021-09-13 22:14:32] local.DEBUG: Then()
[2021-09-13 22:14:33] local.DEBUG: Then()
[2021-09-13 22:14:34] local.DEBUG: Then()
[2021-09-13 22:14:35] local.DEBUG: Then()
[2021-09-13 22:14:36] local.DEBUG: Then()
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
[2021-09-13 22:14:36] local.DEBUG: -----> Done!
```

### Expected result

Similar to JS promises, the `then()` callback should be executed only once. After processing all jobs queued in the `then()` callback, the batch should jump to the following `then()` callbacks, or execute `finally()` callback.

`finally()` should be executed only once.

**Comment by driesvints** [comment]
The current behavior is the expected one. Don't add new jobs within then catch or finally.

**Comment by radmen** [comment]
Could it be possible to at least update the docs, or add a fail-fast trigger that throws an exception when adding jobs in `then()` callbacks?

I spent literally hours to find out why my batches don't finish as I was expecting that the `then` / `finally` callbacks are something more similar to Javascripts _thenables_. I understand that the approach I took is not the correct one, though there was no warning or anything.

**Comment by driesvints** [comment]
Yes feel free to send in a PR, thanks.
