### ISSUE TITLE
Model::updateOrInsert() returns an eloquent Builder object instead of bool

### ISSUE THREAD

**Issue by baueri** [laravel/framework#38839]
- Laravel Version: 8.48.1

- PHP Version: 7.4.19
- Database Driver & Version: 10.3.27-MariaDB

### Description:
When I call on an Eloquent Model the `updateOrInsert()` method, it returns a Illuminate\Database\Eloquent\Builder object, however regarding the documentation it should return a boolean. 

![screenshot](https://user-images.githubusercontent.com/11177064/133629428-813569b2-5a14-4ff6-a447-58687e0b8d98.png)

**Comment by derekmd** [comment]
This is fixed in 9.x: https://github.com/laravel/framework/pull/37956 + maybe https://github.com/laravel/framework/pull/38802 if it's merged.

For 8.x, call `Model::query()->toBase()` to evaluate the boolean return value:

```php
App\Models\User::query()->toBase()->updateOrInsert(
    ['userID' => 1],
    ['userCountry' => 'UK']
);
// => true
```
