### ISSUE TITLE
Database connection time included in query execution time

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#38846]
- Laravel Version: 8.16.0
- PHP Version: 8
- Database Driver & Version: MySQL 8.0.19

### Description:

MySQL/database connection time is included in first db query time stat.

### Steps To Reproduce:

Perform select query e.g:

```php
use App\User;

DB::listen(function($q) {
	var_dump($q->time);
});

User::first(); // 15ms
User::first(); // 0.68ms
User::first(); // 0.66ms
```

Notice how the first query time logged is much slower than the second and third. This is because Laravel has to connect to mysql, which is included in the time.

This has implications on things like Debugbar:

![image](https://user-images.githubusercontent.com/1702638/133681598-5f52d976-4a7a-445d-98e5-54f12035ffa2.png)

This is the very first query that runs and it says it takes 15ms - it doesn't. It takes 0.6ms. It's good to bring awareness of how long db takes to connect, but should it be doing it through a particular query? Is this intended behaviour?

**Comment by driesvints** [comment]
Yeah, this has been the behavior for a while now. I agree it's not ideal but I don't think there's much we can do in the framework for this. Appreciating a PR if you discover an improvement here though.
