### ISSUE TITLE
Breaking change with Bearer tokens that contain a comma

### ISSUE THREAD

**Issue by rdrenth** [laravel/framework#38840]
- Laravel Version: 8.56.0
- PHP Version: 7.4.23

### Description:

This week I encountered an issue with an application that implements an API with Bearer tokens (using the TokenGuard) after the composer dependencies were updated. One of dependencies was laravel/framework.

The API endpoints guarded with the TokenGuard suddenly resulted in a 401 Unauthorized response, so I digged into the matter and discovered the following Pull Request was the cause of this changed behaviour: https://github.com/laravel/framework/pull/38426
We were using an API key (Bearer token) with a comma, and this **breaking change** results in not getting the Bearer token from the Request anymore.

Edit: Apart from the fact that you maybe shouldn't use a comma in your token or API keys, it still is a breaking change.

**Comment by Jubeki** [comment]
@rdrenth just saw your edit, but I still want to say something about the bearer token.

The following RCF defines how a Bearer Token should be formatted and which characters are allowed: https://datatracker.ietf.org/doc/html/rfc6750#section-2.1

So you should probably avoid using a comma in your bearer token.
In This RFC https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2 it also says that values can be comma separated.

So I would rather they Laravel did a bug fix there to follow the rfc guide lines.

**Comment by driesvints** [comment]
> Apart from the fact that you maybe shouldn't use a comma in your token or API keys, it still is a breaking change.

Hey @rdrenth, as @Jubeki explains above this is treated as a bug fix and I don't see any breaking change here. Please make sure your code conforms to the related RFC shared by @Jubeki.
