### ISSUE TITLE
Custom Attributes Issue In Language Files

### ISSUE THREAD

**Issue by developman-akl** [laravel/framework#38878]
Laravel Version: 8.61.0
PHP Version: 7.4

### Description:
Custom `:attribute` names are not fetched anymore from the `attributes` array of the `resources/lang/xx/validation.php` language file. It was working fine in version 8.57.0

### Steps To Reproduce:
The rule:
```
public function rules()
{
    return [
        'lines.*.darabszam' => [
            'integer',
            'required',
            'min:1',
            'max:999999999999',
        ]
    ],
}
```

`resources/lang/hu/validation.php`
```
'attributes' => [
    'lines.*.darabszam' => 'Darabszám',
]
```

```
'custom' => [
    'lines.*.darabszam' => [
        'min' => 'A(z) :attribute -nak legalább ennyinek kell lennie: :min.',
    ]
]
```

![image](https://user-images.githubusercontent.com/48017129/133983253-6ccee58c-1f35-4b30-b9cb-0d6187ab8d2c.png)

It was still working in version 8.57.0
![image](https://user-images.githubusercontent.com/48017129/133983554-cda2bf09-d399-4acb-a8f6-6c63d8a3ddb5.png)

**Comment by driesvints** [comment]
Thanks @derekmd

**Comment by developman-akl** [comment]
@derekmd Sorry for late reply. Thanks for the detailed description. This is an issue with Livewire >2.6.0. so Laravel works fine as you described. Waiting for a fix for Livewire.
