### ISSUE TITLE
find() vs findMany() what is the purpose while both can do same work ?

### ISSUE THREAD

**Issue by SaaberDev** [laravel/framework#38881]
### Discussed in https://github.com/laravel/framework/discussions/38875

<div type='discussions-op-text'>

<sup>Originally posted by **SaaberDev** September 20, 2021</sup>
Can anyone tell me what is the purpose and use-case of this ? It clearly shows that find can use multiple id and also findMany can use multiple id, so why not we use find for single id and findMany for multiple id ? In that way find method will be lighter.

![image](https://user-images.githubusercontent.com/60372951/133959140-b8cc5a21-3238-4bbc-955d-082b59c74e34.png)
</div>

**Comment by JayBizzle** [comment]
Developer convenience I guess.

Also, find() does not imply one, it could be one or many.

**Comment by SaaberDev** [comment]
Then what is the purpose of findMany() .... ?? Don't you think it will be better if we use find() for single instance and findMany() for multiple ? It will improve slight performance, I guess.

**Comment by devcircus** [comment]
You'll find this same pattern used throughout the framework and this is a good thing.

Laravel tries to make the api as intuitive as possible. Like was mentioned before, it's developer convenience. Many developers would expect "find" to work this way. Making methods work the way a developer thinks they should work, is a positive. There's no problem with an extra line of code that checks for one or many. It's not adding any "weight" to the codebase.

Often, Laravel developers can not only guess how a method works, but guess what methods exist on an object. This is one of the many things that draw developers to the framework.
