### ISSUE TITLE
Call to undefined method `App\Models\User::history()`

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [laravel/framework#38895]
I was deal WITH `softDeletes` trait, and when I use the `history` method as exists in the <a href="https://laravel.com/docs/8.x/eloquent#restoring-soft-deleted-models">docs</a> the `Call to undefined method App\Models\User::history()` issue is triggered, here is my code

```php
public function restoreUser(Request $request)
{
     $user_id = $request->route()->parameter('user');
     $user = User::onlyTrashed()->get()->find($user_id);

     if ($user->trashed()) {
        $user->history()->restore();
     }

     return redirect()->route('users.trashed');
}
```

**Comment by Krisell** [comment]
`->history()` is just an example [relationship](https://laravel.com/docs/8.x/eloquent-relationships) for the `Flights` model in the docs, it's not a framework method.

**Comment by mahmoudmohamedramadan** [comment]
@Krisell Thanks
