### ISSUE TITLE
Wrong values inside docs bloc

### ISSUE THREAD

**Issue by Temepest74** [laravel/framework#38905]
- Laravel Version: 8.61.0
- PHP Version: 8.0.10

### Description:

If you go to vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php to the function cursorPaginate from the line 2411 you fill see that the @retrun from the doc block is \Illuminate\Contracts\Pagination\CursorPaginator insead of Illuminate\Pagination\CursorPaginator which is shown if I dump the content returned by the function

**Comment by X-Coder264** [comment]
There's nothing wrong with that docblock. `\Illuminate\Pagination\CursorPaginator` implements the `\Illuminate\Contracts\Pagination\CursorPaginator` interface and the docblock says that the `cursorPaginate` method returns an `\Illuminate\Contracts\Pagination\CursorPaginator` implementation (which it does).

**Comment by Temepest74** [comment]
is there any case where it return something else other than \Illuminate\Pagination\CursorPaginator?

**Comment by X-Coder264** [comment]
Somebody can override that method since it's public and they are required to return an `\Illuminate\Contracts\Pagination\CursorPaginator` implementation from it (be it the one that already exists in the framework or a custom one).
