### ISSUE TITLE
Batch Job didn't wait delayed time 

### ISSUE THREAD

**Issue by mohamedali-pelcro** [laravel/framework#38915]
- Laravel Version: ^8
- PHP Version: 7.4
- Database Driver & Version: Mysql 8 

### Description:
$jobs[] =  (new FirstJob)->delay(now()->addSeconds(90));
$jobs[] =  (new SecondJob)->delay(now()->addSeconds(120));

Bus::batch([$jobs])->->dispatch();

the first job dispatched without waiting to it's delayed time

**Comment by tsybenko** [comment]
Laravel uses "sync" queue driver by default. Did you try to run it with some another driver?

**Comment by mohamedali-pelcro** [comment]
> Laravel uses "sync" queue driver by default. Did you try to run it with some another driver?

Yes I tried with redis

the issue here they add them as a chain but the first one dispatched first

[https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Bus/Batch.php#L161-L197](https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Bus/Batch.php#L161-L197)
