### ISSUE TITLE
`Queue::fake()` inconsistencies between `assertPushed` and `assertPushedOn`

### ISSUE THREAD

**Issue by adevade** [laravel/framework#38924]
- Laravel Version: 8.61.0
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 8.0.25

### Description:

`Queue::assertPushed()` accepts an integer as the last argument, to assert that the job was pushed that many times. Works fine!

[The docblock for `Queue::assertPushedOn()`](https://github.com/laravel/framework/blob/6216534f14c7cb8bdfa213e5f7e3d357119a4579/src/Illuminate/Support/Facades/Queue.php#L21-L22) states that it also accepts an integer as the last argument, but when I try that I get: `Error: Value of type int is not callable.`

```
* @method static void assertPushed(string|\Closure $job, callable|int $callback = null)
* @method static void assertPushedOn(string $queue, string|\Closure $job, callable|int $callback = null)
```

I think that `assertPushedOn` should match `assertPushed` and accept an integer as the last argument.

### Steps To Reproduce:

https://github.com/adevade/queue-assert-bug

Run PHPUnit and see it fail due to `assertPushedOn` not accepting an integer as the last argument.

**Comment by driesvints** [comment]
Fixed, thanks.
