### ISSUE TITLE
Passing LazyCollection to Blade view causes query to execute twice

### ISSUE THREAD

**Issue by awebartisan** [laravel/framework#39003]
- Laravel Version: 8.61.0
- PHP Version: 7.4.22
- Database Driver & Version: MySQL v8

### Description:
When a `LazyCollection` instance is passed to Blade view and looped via `@foreach` directive, it causes the query to execute twice. Believe that its because of how `foreach` directive is compiled under the hood and how `count` and `last` record of the `Countable` is managed inside [ManagesLoops](https://github.com/laravel/framework/blob/8.x/src/Illuminate/View/Concerns/ManagesLoops.php#L25) file.

### Steps To Reproduce:
- Inside controller or route file
```php
    $users = User::lazy();
    return view('welcome', ['users' => $users]);
```
- Inside blade view
```php
    @foreach($users as $user)
        <div>{{ $user->name }}</div>
    @endforeach
```
- Queries detected using Ray
![image](https://user-images.githubusercontent.com/29105478/135037266-727dd888-5e88-42e8-9498-5314752e6a51.png)

### GitHub Repo
https://github.com/awebartisan/lazy-collection-blade-query-bug

**Comment by driesvints** [comment]
Yes, that's indeed how things work atm. I don't really see a bug here tbh.

**Comment by awebartisan** [comment]
It can be a feature request? Where Blade compiler pays attention to specifics of LazyCollection and deal it differently than normal Collection?
