### ISSUE TITLE
DB::transaction commit even tho exception has been thrown

### ISSUE THREAD

**Issue by mathias-poweredsoft** [laravel/framework#39017]
- Laravel Version: 8.62.0
- PHP Version: 8.0.11
- Database Driver & Version: mysql 8.0

### Description:
According to the documentation (https://laravel.com/docs/8.x/database#database-transactions)
DB::transaction should automatically DB::rollBack() when an exception is thrown in his closure but it is not the case.

### Steps To Reproduce:
Create a new feature test and run this specific test
```PHP
<?php

namespace Tests\Feature;

use Exception;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Tests\TestCase;

class LaravelTest extends TestCase
{
    /**
     * BUG: DB::transaction is not supose to commit when an exception is thrown
     * https://laravel.com/docs/8.x/database#database-transactions
     * @return void
     */
    public function test_transaction_bug()
    {
        $tableName = Str::random(24);
        try {
            DB::transaction(function() use ($tableName) {
                Schema::create($tableName, function(Blueprint $table) {
                    $table->id();
                    $table->string('test', 64)->nullable();
                });

                DB::table($tableName)->insert([
                    'test' => 'hello world'
                ]);

                throw new Exception('Huh?');
            });
        }
        catch(Exception $e) {
        }

        $data = null;
        try {
            $data = DB::table($tableName)->get();
        } catch(Exception $e) {

        }

        Schema::dropIfExists($tableName);
        // as you can see the data was actually loaded from the DB
        var_dump($data);
        $this->assertTrue($data == null);
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by lk77** [comment]
You should be using InnoDB engine if you want your transactions to work

**Comment by mathias-poweredsoft** [comment]
the engine is InnoDB

**Comment by lk77** [comment]
DatabaseTransactionsManager::rollback is indeed called and no transaction is left behind

**Comment by mathias-poweredsoft** [comment]
I have no clue how to explain how my test fail (aka having data in the database)
Here is the exact step I did to reproduce it:
```BASH 
curl -s "https://laravel.build/example-app?with=mysql,redis" | bash
cd example-app
./vendor/bin/sail up
```
Once the containers are up enter it with 
```BASH
docker exec -it <container> bash
php artisan make:test LaravelTest
```
Copy my test method in the test file and run it with
```BASH
php artisan test tests/Feature/LaravelTest.php
```

**Comment by mathias-poweredsoft** [comment]
Big update I figure out why that was happening

when Schema::create is place inside DB::transaction it commit the transaction right away and everything coming after is not part of the transaction anymore and thats why the insert is commited even tho I threw an exception. I know I've discovered this bug else where in our project and created this test to figure it out but I wasn't using Schema::create so there might be other DB:: Schema:: methods out there that can cause the same issue.

Working test
```PHP
public function test_transaction_bug()
    {
        $tableName = Str::random(24);
        try {
            Schema::create($tableName, function(Blueprint $table) {
                $table->id();
                $table->string('test', 64)->nullable();
            });
            
            DB::transaction(function() use ($tableName) {
                DB::table($tableName)->insert([
                    'test' => 'hello world'
                ]);

                throw new Exception('Huh?');
            });
        }
        catch(Exception $e) {

        }

        $data = null;
        try {
            $data = DB::table($tableName)->get();
        } catch(Exception $e) {

        }

        Schema::dropIfExists($tableName);
        if ($data->count() == 0)
            $data = null;
            
        $this->assertNull($data);
    }
```

**Comment by lk77** [comment]
```
The CREATE TABLE statement in InnoDB is processed as a single transaction. This means that a ROLLBACK from the user does not undo CREATE TABLE statements the user made during that transaction.
```

from mysql doc : https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html
