### ISSUE TITLE
empty morphMany Relation show the wrong result

### ISSUE THREAD

**Issue by gfernandez-me** [laravel/framework#39025]
- Laravel Version: 8.40
- PHP Version: 7.4.3

### Description:
When you test if a morphMany relation is empty with empty() it says it's not empty, but count() will return zero.

### Steps To Reproduce:
```
class Tag extends Model
{
}

class Entity extends Model
{

    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
    }
}

$entity = new Entity();

//when
$result = empty($entity->tags);

//then
$this->assertEquals(true, $result);
```

https://pasteboard.co/4guuHRxWuunA.png

**Comment by derekmd** [comment]
```php
$this->assertTrue($entity->tags->isEmpty());
// or
$this->assertCount(0, $entity->tags);
```

PHP `empty()` is not the same as Laravel's `Collection::isEmpty()`. PHP `empty($var)` is equivalent to `! isset($var) || ! $var` and the `$entity->tags` relation is always a `Collection` object which is PHP "truthy". So `empty($entity->tags)` is always `false` no matter the item count.

**Comment by driesvints** [comment]
Thanks @derekmd
