### ISSUE TITLE
[8.x] Cannot test with fake emails when using Email Validation rules.

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#39040]
- Laravel Version: 8.61.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.26

### Description:

There is no way to fake an email on testing when dealing with a route validating email with RFC, DNS, or a custom one. Since [the rule cannot be bypassed](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L683) instead of mocked or faked (just for the email), any test fails, unless the whole validation system is faked in an additional test case.

### Steps To Reproduce:

1. Create any test with this code.

```php
use Illuminate/Support/Facades/Route;

public function test_bad()
{
    Route::post('test', function (Request $request): string {
        $request->validate(['email' => 'email:dns,rfc']);

        return 'ok';
    });

    $this->post('test', ['email' => 'testemail@email.com'])->assertOk();
}
```

The is no way to allow to bypass email validation, leaving these alternatives:

1. Faking the validation entirely on a separate test.
2. Enabling validation for that rule separately using `app()->environment('testing')` conditionally.

### Possible solutions.

1. Allow the container to resolve the `EmailValidator` instance so it can be faked/mocked.
2. Create a `fakeRules()` helper for the Validator to allow bypassing certain keys, or certain rule keys.

**Comment by driesvints** [comment]
This is a feature request so I'm moving it to discussions. Also please note that you can't perform two HTTP calls in a single test as that's not a real-life scenario.
