### ISSUE TITLE
Signed URL validation fails

### ISSUE THREAD

**Issue by marcelvossmint** [laravel/framework#39051]
- Laravel Version: 8.46.0
- PHP Version: 8.0.5

### Description:

Signed URL validation fails in this Laravel Version.
Downgrading to 8.36 fixed the issue.

Reason seems to be this change
https://github.com/laravel/framework/pull/37432/commits/891945034dc08e980d187d705fbaaefedee33724

URL called was like this:
https://foo.bar/confirmationLink?expires=1633098759&signature=f3c3...a84c2

Output of $request->server->get('QUERY_STRING') was like this:
/confirmationLink&expires=1633098759

Somehow the path param was suddenly part of the query string.

### Steps To Reproduce:
1. Create signed url.
2. Open signed url.
3. Validation fails.

**Comment by Krisell** [comment]
Could you provide some more details about exactly how you are generating the URL and calling the verification. The steps you mentioned are not sufficient as the URL signing validation seems to work for everyone else. 

Are you saying that `$_SERVER['QUERY_STRING']` is not the actual query string on your server?

**Comment by marcelvossmint** [comment]
Issue was due to wrong nginx config, thank you!

**Comment by Krisell** [comment]
Thanks for the update! Just out of curiosity, could you share the problem? If you don't want to post it here, feel free to hit me up via my email.

**Comment by marcelvossmint** [comment]
Below config was used and in the marked line the path seems to be added to the query...

https://gist.github.com/ashleydw/afd389b1e763d3c1cf1f#file-nginx-conf-L35
