### ISSUE TITLE
Built-in Password validation rule uses hardcoded error messages

### ISSUE THREAD

**Issue by lanbotdevman** [laravel/framework#39058]
- Laravel Version: 8.61.0
- PHP Version: 7.4.0
- Database Driver & Version: N/A

### Description:
The new build-in Password validation rule uses hardcoded error messages. They should be translatable in same way as other built-in validation rules with 'validation.rulename' keys.
Most of the Password validation logic returns hardcoded and untranslatable strings, for example:
```
if ($this->letters && ! preg_match('/\pL/u', $value)) {
    $this->fail('The :attribute must contain at least one letter.');
}
```

For example Password::min() works since it uses built-in "min" validation rule.

Code reference: [framework/src/Illuminate/Validation/Rules/Password.php](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Rules/Password.php) 

### Steps To Reproduce:

1.  Use in a form request validation, for example:
`
'password' => ['required', 'confirmed', 'max:255', Password::min(2)->letters()],
`
2. Submit an invalid password (only numbers) as one of the input fields

#### Expected result
Validation rule returns a translation key as the message.

#### Actual result
Validation rule returns always '_The :attribute must contain at least one letter._' message regardless of the context language.

**Comment by derekmd** [comment]
Line 334:

https://github.com/laravel/framework/blob/a0fd30ffc59075448bec9f2e430b8af7b9f4cdf6/src/Illuminate/Validation/Rules/Password.php#L331-L340

The rule does invoke the translator to fetch a JSON file-stored translation if it exists.

### resources/lang/es.json

```
{
    "The :attribute must contain at least one letter.": "El :attribute debe contener al menos una letra. "
}
```

**Comment by lanbotdevman** [comment]
Thanks for the input - quick test shows that indeed it's a valid solution and it works if application is using translation strings as keys for localization strategy.
Yet based on Laravel - Validation documentation, short keys are used. Quote:
> Laravel's built-in validation rules each has an error message that is located in your application's **resources/lang/en/validation.php** file.

Reference: [Displaying The Validation Errors - Customizing The Error Messages](https://laravel.com/docs/8.x/validation#quick-customizing-the-error-messages)
It was confusing where the messages are coming from and how can I translate them when trying to use the Password rule for the first time.

Based on above, there are some options:

- Add clarifying documentation to the Password rule that "translation strings as keys" are being used instead
  - This option would force applications to use two strategies if short keys are being used as a primary source for translation
- Convert Password rule implementation to use short keys
  - Not a backward compatible for solutions that are already using Password rule with translation strings as keys
- Add optional logic to Password rule to use validation short keys
  - E.g. `'password' => ['required', 'confirmed', 'max:255', Password::min(2)->letters()->withShortKeys()]`,
- Some other solution..

**Comment by driesvints** [comment]
We have no plans to change this atm, sorry.
