### ISSUE TITLE
ValidationData::initializeAndGatherData returns duplicates

### ISSUE THREAD

**Issue by lurza** [laravel/framework#39076]
- Laravel Version: 8.59.0
- PHP Version: 7.4.21
- Database Driver & Version:

### Description:

I am creating a custom validation rule that checks if max one value is true in an array. Because it works on arrays I tried reusing some of the same logic as the Laravel validator. The ValidationData::initializeAndGatherData returns duplicate data if attribute is "*".

### Steps To Reproduce:

Illuminate\Validation\ValidationData::initializeAndGatherData("*", ["a", "b", "c"]); 

expected: ["a", "b", "c"]
returns ["a", "b", "c", "a", "b", "c"]

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
