### ISSUE TITLE
Eloquent model relationships are loaded after attributes when unserializing in queue

### ISSUE THREAD

**Issue by yosifeldman** [laravel/framework#39101]
- Laravel Version: 6.x
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:

When passing an Eloquent model to the queue Job with some loaded relationships, it tries to reload them before the model attributes are loaded.

In my use case, it was a problem, because I used some attributes in the relationship function (maybe I was wrong to assume it should work?)

So, since the relationship was loaded already, using empty attributes, and was equal to NULL, then later in the code, when I tried to use it, it was not reloaded and caused issues.

### Steps To Reproduce:

Have relationship something like I had:

```
class MyModel extends Eloquent {
        .....
        public function myRelation(): HasOneThrough
       {
            return $this->hasOneThrough(
                Related::class,
                Through::class,
                'id',
                'through_table_id',
                'related_table_id',
                'id'
             )
                ->where("some_column", $this->some_attribute);
       }
}
```
Load this relationship in the model, and then pass the model as a parameter to the Queue Job class.

### Explanation

When the Job starts, the model is reloaded from DB, and all relationships too.
But, in some reason, when i's loading this relationship, `$this->attributes` equals `[0]` on the model.
This causes the relationship not to load, but still be created on the object as `$this->myRelation = null`.

### Should be
(per my assumption) - loading relationships *after* `$this->attributes` is filled

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
