### ISSUE TITLE
Unique Jobs are not unique when using Dependency Injection

### ISSUE THREAD

**Issue by rela589n** [laravel/framework#39113]
- Laravel Version: 8.61.0, but whatever
- PHP Version: 8.0.9, but whatever
- Database driver: not involved
- Cache driver: redis, but whatever

### Description:

There's an job `SaveEMAFromKlines` implementing `ShouldQueue`, `ShouldBeUnique` interfaces with an implementation of `uniqueId()` method.
As well, there's console command, which dispatches loads of `SaveEMAFromKlines` jobs. However framework doesn't look on `ShouldBeUnique` interface and doesn't pay attention that unique job is not processed yet, but anyways dispatches all jobs. 

### Steps To Reproduce:

Job class

```php
#[Immutable]
final class SaveEMAFromKlines implements ShouldQueue, ShouldBeUnique
{
    use Queueable;

    private const DEFAULT_QUEUE = 'save_ema_from_klines_queue';

    private function __construct(
        public string $symbol,
        public int $period,
        string $queue,
    ) {
        $this->onQueue($queue);
    }

    public function lowPriority(string $symbol, int $period): self
    {
        return new self($symbol, $period, self::DEFAULT_QUEUE);
    }

    public function uniqueId(): string
    {
        return $this->symbol.'#'.$this->period;
    }

    public function handle(): void
    {
        $timeInSeconds = 10;
        sleep($timeInSeconds);
    }
}
```

Command to dispatch jobs:

```php
<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Domain\Service\Kline\Command\SaveKlinesFromApi;
use Illuminate\Console\Command;
use Illuminate\Contracts\Bus\Dispatcher as BusDispatcher;

use function mt_rand;

final class FetchPricing extends Command
{
    protected $signature = 'price:eager-fetch {--symbol=} {--minutes=}';

    public function __construct(
        private BusDispatcher $busDispatcher,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $symbol = $this->option('symbol');

        for ($i = 0; $i < 1000; ++$i) {

            // if dispatch() function was used or Dispatchable trait was added to job,
            // there would be no problems, however both solutions are anti-patterns 

            $this->busDispatcher->dispatch(
                SaveKlinesFromApi::lowPriority(
                    $symbol,
                    mt_rand(max: 2),
                ),
            );
        }

        return 0;
    }
}
```

Now, you should run worker and see that code you added in `\Illuminate\Foundation\Bus\PendingDispatch::shouldDispatch`, you did forget to add into `\Illuminate\Bus\Dispatcher::dispatch`. AFAIK, technical solution utilizes cache locks with `laravel_unique_job` prefix. I searched for it and it seems to be only in 2 places, which contain duplicated logic. One place is hidden in `dispatch()` function, which makes other place useless if we use DI.

Thanks!

**Comment by X-Coder264** [comment]
I'm glad that you are so familiar with my posts that you were able to find and link them within two minutes of my previous reply :)

Anyway unlike my posts which were trying to be useful (one is giving my opinion about a PR that the author wanted to get into the framework, the other is about actually contributing to the framework which got merged too) the sentences you wrote did not bring anything useful to the table here. And I think we went hugely off-topic here already so there's no need for further comments about this.

**Comment by LastDragon-ru** [comment]
There is another real issue related to this - cron jobs. When you do `$schedule->job(Job)` it doesn't check `ShouldBeUnique` and the job will be dispatched again. This is the real problem for very long-running jobs. 

_PS: Should I create a new issue?_

**Comment by driesvints** [comment]
> I don't want to offed you all, however those antipatterns you promote (like facades, global functions) are making code unmaintainable mess (if use documentation examples) and furthermore, people trying to avoid all this framework sh** and write clean code using Dependency Injection and Dependency Inversion principles, are subject to not working framework functionality. Well, welcome to Laravel....

@rela589n I'll take a look at your issue when you've managed to submit a polite report.

@derekmd I truly appreciate all you've done so far on this issue tracker and get that you were reacting to their post but it's indeed best to not react to those kind of things. Thanks for your reply though.

@X-Coder264 Derek was reacting to an edited part of their post. In general I want to mention I that I appreciate both of your help on this repo but this issue tracker isn't the place for these kind of debates.

@LastDragon-ru I'm not sure if it was ever intended for the scheduler to ever check that interface. I believe it's normal that the job is dispatched again according to the `everyXtime` method? If you think this is an issue maybe indeed open a separate issue.

**Comment by ukenpachi** [comment]
Hi did you managed to get `ShouldBeUnique` working? I am having the same issue [#42297](https://github.com/laravel/framework/issues/42297)
