### ISSUE TITLE
Bus::fake(NonBatchedJob::class) prevents any Bus::batch() from executing

### ISSUE THREAD

**Issue by jesseschutt** [laravel/framework#39200]
- Laravel Version: v8.64.0
- PHP Version: 8.0.10
- Database Driver & Version: sqlite (using default framework configuration)

### Description:
When I use `Bus::fake(NonBatchedJob::class)` in a test other portions of my application fail due to expectation `Bus::batch()` will run.

### Steps To Reproduce:

1. Add `Bus::fake(NonBatchedJob::class)` to any test that triggers a separate `Bus::batch()`.
2. The `NonBatchedJob` will correctly be faked.
3. The unrelated `Bus::batch()` will not be executed.

#### Example Batched Job

```php
class BatchedJob implements ShouldQueue
{
    use Batchable, Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        event(new \App\Events\BatchedJobEvent());
    }
}
```

#### This Test Fails

```php
    public function test_example()
    {
        Bus::fake(NonBatchedJob::class);
        Event::fake();

        Bus::batch([
            new BatchedJob(),
        ])
            ->dispatch();

        Event::assertDispatched(BatchedJobEvent::class);
    }
```

#### This Test Passes

```php
    public function test_example()
    {
        // Bus::fake(NonBatchedJob::class);
        Event::fake();

        Bus::batch([
            new BatchedJob(),
        ])
            ->dispatch();

        Event::assertDispatched(BatchedJobEvent::class);
    }
```

[Example Repository](https://github.com/jesseschutt/batch-fake)

**Comment by driesvints** [comment]
If you use `Bus::fake` then all of the `Bus` usage will be faked. Events for `dispatch` won't be sent at all. Instead of `PendingBatch` instances, `PendingBatchFake` instances will be used behind the scenes.
