### ISSUE TITLE
`runningInConsole()` return false when using Octane

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#39225]
- Laravel Version: 8.*
- PHP Version: 8.*

### Description:

As my understanding when we use laravel octane and start the swoole serve the whole app is running in console right ? but the `runningInConsole` return false hence we can not run some artisan commands that requires app in running in console like scout:

```php
//AppServiceProvider.php

Octane::tick('inspire.key', function () {
    Artisan::call('scout:import');
});

```
Exception: 

> The command "scout:import" does not exist.

**Comment by driesvints** [comment]
> As my understanding when we use laravel octane and start the swoole serve the whole app is running in console right ?

No, it's basically a web server running like `artisan serve`. So not in a console.
