### ISSUE TITLE
QueryException::formatMessage() replacing all question marks

### ISSUE THREAD

**Issue by lupinitylabs** [laravel/framework#39239]
- Laravel Version: 8.53.1
- PHP Version: 8.0.11
- Database Driver & Version: MySQL 8.0.26

### Description:
The `formatMessage()` method in `\Illuminate\Database\QueryException` provides the failed query as SQL string with bindings replaced as follows:

```php
        return $previous->getMessage().' (SQL: '.Str::replaceArray('?', $bindings, $sql).')';
```

This naive approach will of course replace ALL question marks within the query string, including question marks that may exist in parts of the query including, but not limited to raw statements (select, order, subqueries) or SQL comments.

**However** there are a couple of reasons not to act on this:
* this issue exists since 8 years now, so I suppose it is not really a concern
* it is only cosmetic.
* fixing this is not trivial. Using a regex could mitigate the easy cases, but to really tackle this might require parsing.

### Steps To Reproduce:

```php
  User::selectRaw('"Hello??"')->whereType('SomeParameter')->find(4)
```
![grafik](https://user-images.githubusercontent.com/17774818/137678333-1bb2dec6-7d09-46a3-8d9c-b91d19ffde03.png)

```php
  User::selectRaw('"Test?" /* Some comment? */')->whereType('SomeParameter')->find(4)
```
![grafik](https://user-images.githubusercontent.com/17774818/137679473-0f9b0f2b-e38b-4878-9830-5c8f4df29219.png)

**Comment by driesvints** [comment]
Yeah, I don't really see a big issue here if it's been in here so long and no one has reported it so far. Appreciate you informing us however 👍  But I think we're gonna let this one be.
