### ISSUE TITLE
Unexpected `->value()` return.

### ISSUE THREAD

**Issue by Aferz** [laravel/framework#39431]
- Laravel Version: 8.68.1
- PHP Version: 8.0
- Database Driver & Version: MySQL 8.0

### Description:

When using `->value` method on a query to retrieve the first result of the specified column, it acts in a weird behavior depending if you used the `->select` clause.

### Steps To Reproduce:

Use any model you have  in any of your projects and execute this in tinker:

```php
// Example 1
Model::query()->select('id', 'field')->value('field');

// Example 2
Model::query()->select('*')->value('field');
```
You'll see tinker outputs the field `id` instead of the one you selected.

--- 

Looking at how the `->value` it's implemented, it's obvious why this is failing:

```php
public function value($column)
{
    $result = (array) $this->first([$column]);

    return count($result) > 0 ? reset($result) : null;
}
```

If `select` clause is provided in the query, the fields passed in `first` are ignored, which could be fine in the vast majority of scenarios **BUT** it causes a lot of confusion in these specific cases due this method doesn't take care if the column provided is even in the result or not. It just returns the first item in the array **using order of the fields in the select clause** which leads to unexpected output.

The first example could be easily "fixed" removing the `select` clause because the ID is not even necessary there, but the second is not so easily fixable due it could be, for example, a cherry-pick of fields from joined tables, making this method buggy unless you order your select fields (which is not intuitive at all).

I don't know if this is on purpose and you have to use this method only when you are selecting one column or not selecting at all, but I think if that's the case, this method makes you misuse it due to its implicit constraints.

Thanks!

**Comment by driesvints** [comment]
Works fine for me:

![Screen Shot 2021-11-01 at 11 49 22](https://user-images.githubusercontent.com/594614/139660431-818b4fa1-a4df-48e5-975c-41b10ab69a9f.jpg)

**Comment by Aferz** [comment]
@driesvints Wtf now I can't reproduce it myself. Sorry for wasting your time.
