### ISSUE TITLE
Laravel Migration Silently Fails with SQLite when Dropping and Adding a Column in the Same Modification

### ISSUE THREAD

**Issue by mishagp** [laravel/framework#39442]
**Versions:**

- PHP: 8.0.12
- SQLite: 3.36.0
- Laravel: 8.86.1
- doctrine/dbal: 3.1.3

I was just making the switch to using SQLite as a test db connection and encountered a strange issue where a migration was failing without error where it normally succeeds on MySQL and SQL Server.

```php
Schema::table('example_table', function (Blueprint $table) {
    $table->dropColumn('old_column');
    $table->json('new_json_column');
});
```

I traced the changes to a SQLite file database while stepping through the migrations and found that the `old_column` would be correctly removed but the `new_json_column` wasn't added and no error was thrown.

It looks like `Illuminate\Database\Schema\Blueprint::ensureCommandsAreValid()` isn't throwing an error because this migration doesn't satisfy the following criteria:

https://github.com/laravel/framework/blob/6651d7e575e5954e90a71c1bca0292e550e99176/src/Illuminate/Database/Schema/Blueprint.php#L154-L166

Relevant documentation: https://laravel.com/docs/8.x/migrations#dropping-columns

So my question is: should `ensureCommandsAreValid()` handle circumstances like these or is there something strange about my environment that is causing the issue? A colleague was able to reproduce this as well, FWIW.

I would love to submit a PR, I just want to confirm it would be welcome. Thanks!

**Comment by mishagp** [comment]
Note, in my codebase I resolved it by breaking them out into separate modifications and everything works smoothly:
```php
Schema::table('example_table', function (Blueprint $table) {
    $table->dropColumn('old_column');
    $table->json('new_json_column');
});

if (config('database.default') === 'sqlite') {
    Schema::table('example_table', function (Blueprint $table) {
        if (!Schema::hasColumn('example_table', 'new_json_column'))
        {
            $table->json('new_json_column');
        }
    });
}
```

**Comment by driesvints** [comment]
I can't seem to reproduce it with the given example.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Sunhat** [comment]
I've experienced this in two separate Laravel projects. 

PHPUnit, in-memory sqlite DB

**Comment by rennokki** [comment]
@Sunhat it's not a good practice to alter multiple columns in a single alter statement as sqlite does not support it: https://stackoverflow.com/questions/6172815/sqlite-alter-table-add-multiple-columns-in-a-single-statement 

Keep them separated and problem solved. 

I don't wanna express my views on the attitude. Read the LICENSE file in this repo and you'll find all the reasons.

**Comment by Nilpo** [comment]
I'll point out that this isn't a bug in Laravel. Laravel (or any other framework for that matter) is not responsible for failing gracefully when you perform an unsupported action that violates best practices. If **you** wish to see this handled more gracefully, but all means submit the PR.
