### ISSUE TITLE
Missing Queue::ignoreMigrations() method

### ISSUE THREAD

**Issue by Traqza** [laravel/framework#39465]
- Laravel Version: 8.^
- PHP Version: 8.x
- Database Driver & Version:

### Description:

Passports, and Cashier have an option to `ignoreMigrations()`, however the QueueServiceProvider does not have this method, or option to ignore running the `Jobs` migration file.

### Steps To Reproduce:
See Line 71 on ...\Passport\src\PassportServiceProvider.php 
See Line 126 on ...\Cashier\src\Cashier.php

**Comment by Traqza** [comment]
This would also resolve a fairly common issue with things like  Issue #23194

**Comment by driesvints** [comment]
No plans for this.
