### ISSUE TITLE
QueryBuilder `firstOrNew` and `firstOrCreate` not working with PHP 8.1 enum casts

### ISSUE THREAD

**Issue by jerodev** [laravel/framework#39471]
- Laravel Version: 8.69.0
- PHP Version: PHP 8.1.0RC6
- Database Driver & Version: mariadb 10.3

### Description:
Having PHP 8.1 enum casts causes an issue where `firstOrNew` and `firstOrCreate` no longer work. 

### Steps To Reproduce:
```php
class User extends Model
{
    public $casts = [
        'role' => RoleEnum::class,
    ];
}

User::firstOrNew(['role' => RoleEnum::Admin]);
```

The example above will crash when parameters are being bound to the SQL query because the query builder cannot cast the enum to a string.  
However, if we would pass the enum value instead, this example will fail because it cannot set the attribute on the newly created instance because we try to get the property `$value` on a string

#### Exception when passing enum
> Error: Object of class App\Models\Enums\RoleEnum could not be converted to string
> 
> vendor/laravel/framework/src/Illuminate/Database/Connection.php:610
> vendor/laravel/framework/src/Illuminate/Database/Connection.php:362
> vendor/laravel/framework/src/Illuminate/Database/Connection.php:696
> vendor/laravel/framework/src/Illuminate/Database/Connection.php:663
> vendor/laravel/framework/src/Illuminate/Database/Connection.php:367
> vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2351
> vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2339
> vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2873
> vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2340
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:615
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:599
> vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:259
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:464

#### Exception when passing enum value
> ErrorException: Attempt to read property "value" on string
> 
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:929
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:797
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:431
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:212
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:496
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1330
> vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:468

**Comment by themsaid** [comment]
@jerodev  casting happens after the model is retrieved and before it gets saved, not while querying the database.

**Comment by jerodev** [comment]
@themsaid I am aware.
But because both the query builder and the eloquent model constructor expect another value type, it is currently not possible to use `firstOrNew` using enums.

The query builder expects the value to be a string or integer and the model constructor expects the attribute to be an enum.

**Comment by driesvints** [comment]
> It is currently not possible to use firstOrNew using enums.

@jerodev I think you're just trying to use something that isn't yet possible in Laravel. The Enum casts were solely intended to be used with casting. I see your use case but it's not a bug, just something that hasn't been added to Laravel yet.

**Comment by themsaid** [comment]
@jerodev that is expected with all casting types when it comes to these two methods. Querying requires the raw value while creating requires the casted value.

When you're dealing with any casted attribute, you'll need to do the querying first using the raw value and then create using the casted version if the query returned null.

**Comment by jerodev** [comment]
@driesvints @themsaid I see, I wasn't aware that it was not yet intended to be used in this way. Thanks for the explanation. :)
