### ISSUE TITLE
Interaction trait incorrectly handles keys that includes dot `.`

### ISSUE THREAD

**Issue by yu-ichiro** [laravel/framework#39472]
- Laravel Version: 8.66.0
- PHP Version: 8.0.11
- Database Driver & Version: N/A

### Description:

When trying to assert a key that includes a dot with `AssertableJson`, the assertion succeeds but the `interacted()` check of the `Interaction` trait fails.

### Details:

at [src/Illuminate/Testing/Fluent/Concerns/Interaction.php#L25](../blob/master/src/Illuminate/Testing/Fluent/Concerns/Interaction.php#L25), `Str::before` trims off anything after the first dot assuming that the dot means a nested access, but ordinary keys with dots (such as validation errors) also falls in here, resulting in wrong key being inserted to the `interacted` prop, eventually resulting in a failure at `interacted()`

### Fix:

I was thinking of making a PR fixing this issue by adding `$key` to `interacted` as well as adding `$prop` to it, but it will introduce several condition checks, so I wanted to check if that was the correct way to approach this issue.

**Comment by yu-ichiro** [comment]
The diff of what I was thinking of implementing

```diff
    /**
     * Marks the property as interacted.
     *
     * @param  string  $key
     * @return void
     */
    protected function interactsWith(string $key): void
    {
        $prop = Str::before($key, '.');

        if (! in_array($prop, $this->interacted, true)) {
            $this->interacted[] = $prop;
        }

+       if ($key !== $prop && ! in_array($key, $this->interacted, true)) {
+           $this->interacted[] = $key;
+       }
    }
```

**Comment by yu-ichiro** [comment]
Note that this fix **doesn't** cover an array that consists a key of the first part before the period of another key

```
$json = AssertableJson::fromArray([
   'hoge' => 1
   'hoge.foo' => 2
])

$json->where('hoge.foo', 2)
// no exception is thrown despite the fact that the key `hoge` is not checked
```

**Comment by driesvints** [comment]
Provide a way to reproduce please.

**Comment by yu-ichiro** [comment]
sorry for not including a reproduction on the first place. below is a test code that can be put in to `tests/Testing/Fluent/AssertTest.php`:
```
    // this fails incorrectly
    public function testAssertDotAccessIncorrect()
    {
        $assert = AssertableJson::fromArray([
            'foo.bar' => 1
        ]);

        $assert->where('foo.bar', 1);
        $assert->interacted();
    }

    // while this succeeds correctly
    public function testAssertDotAccessWorking()
    {
        $assert = AssertableJson::fromArray([
            'foo' => [
                'bar' => 1
            ]
        ]);

        $assert->where('foo.bar', 1);
        $assert->interacted();
    }
```

**Comment by yu-ichiro** [comment]
I initially confused the automatic call of `interacted()` as a feature of `AssertableJson` itself while in reality it was a feature of `TestResponse->assertJson()`. Sorry for the incomplete description.

**Comment by driesvints** [comment]
You cannot use dot notation in JSON keys, that's why this doesn't work. You need to use array's as in your second example.

**Comment by pOmelchenko** [comment]
> You cannot use dot notation in JSON keys, that's why this doesn't work.

You can use dot notation in JSON keys:

```php
<?php

var_dump(json_decode('{"data": {"key.name": "value"}}'));
```
result
```text
object(stdClass)#2 (1) {
  ["data"]=>
  object(stdClass)#1 (1) {
    ["key.name"]=>
    string(5) "value"
  }
}
```

[sandbox](https://3v4l.org/M72tX)

In JS you can use it too
```js
let json = {"data": {"key.name": "value"}};

console.log(json.data["key.name"]);
```
result
```text
value
```
[sandbox](https://codepen.io/pOmelchenko/pen/qBQbYdv?editors=1111)

**Comment by pOmelchenko** [comment]
hah! If you have this JSON you can use that key in php too

```php
<?php

$json = json_decode('{"data": {"key.name": "value"}}');

$key = 'key.name';

var_dump($json->data->$key);  // string(5) "value"
var_dump($json->data->{"key.name"}); // string(5) "value"
```
