### ISSUE TITLE
Bug or inconsistency between the code and the docs ?

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#39534]
- Laravel Version: 8.69.0
- PHP Version: 8.0.3
- Database Driver & Version: Mariadb 10.3.12

### Description:
I quote from the documentation the description of the `exclude_if` validation rule

```
The field under validation will be excluded from the request data returned by the validate and validated methods if the anotherfield field is equal to value.
```

From my understanding this will only exclude the key from the $data returned from the `validate` and the `validated` methods but what is happening is that the validation will fail.

So is the documentation correct and this is a bug, and the validator should be fixed to only exclude the key from the returned data and not fail the validation ?
Or is the code correct and the docs is not mentioning this behavior ?

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by shadoWalker89** [comment]
Hi @driesvints 

I really think this is not a question that should be asked in the forum

There is a difference between what the docs says and what the code does.

So I think, that one of the laravel team members is the qualified person to answer the question and not just any one from the community.

Thanks for your understanding
