### ISSUE TITLE
[8.x] QueryBuilder `cleanBindings` refactoring lead to "Array to string conversion" error

### ISSUE THREAD

**Issue by nuernbergerA** [laravel/framework#39553]
- Laravel Version: v8.70.0
- PHP Version: 8.0.12
- Database Driver & Version: sqlite 3.35.5 (but doesn't really matter)

### Description:
Since #39492 `cleanBindings()` will have a different output then before because of `toArray()` instead of `all()` and result in a `Array to string conversion` error in some cases.

### Steps To Reproduce:
Given a **User** model with a `settings` field that is **casted** to a `collection`

```php
User::query()->insertOrIgnore([
    ['username' => 'driesvints', 'settings' => collect(['macUser' => true])],
    ['username' => 'nuernbergerA', 'settings' => collect(['macUser' => false])],
]);
```

**Comment by taylorotwell** [comment]
I think I can just safely update that from `toArray` to `all`. Will push a fix.
