### ISSUE TITLE
when using `selectRaw`, array bindings are flattened 

### ISSUE THREAD

**Issue by atymic** [laravel/framework#39554]
- Laravel Version:8.70.1
- PHP Version: 8.0
- Database Driver & Version: Mysql 8.0

### Description:

Take the following query:

```php
DB::table('whatever')
    ->selectRaw("SUM('case(`status` in (?)) as total_pending", [[1,2,3]])
    ->where('user', 1)
    ->groupBy('something')
    ->get()
```

When laravel runs this query, the bindings are flattened, which results in 
```sql
SELECT SUM('case(`status` in (1)) as total_pending from whatever where user = 2 group by something
```

Possibly a security issue if query params are passed into a select raw? see https://github.com/laravel/framework/pull/35865 

Anyhow, I don't see why array bindings flattened, as they are supported by the database.

**Comment by RahulDey12** [comment]
You could use like this.

DB::table('whatever')
    ->selectRaw("SUM('case(`status` in (?)) as total_pending", [json_encode([1,2,3])])
    ->where('user', 1)
    ->groupBy('something')
    ->get()

**Comment by bastien-phi** [comment]
@atymic Did you try with laravel 8.70.2 ? I think this was fixed with https://github.com/laravel/framework/commit/74dcc024d5ac78a1c7c23a95c493736c2cd8d5a7

**Comment by RahulDey12** [comment]
@bastien-phi no it is not fixed

**Comment by nuernbergerA** [comment]
This seems to be related to #39553 and #39492 

@taylorotwell I assume it the same issue on this line https://github.com/laravel/framework/blob/dec9524cd0f9fa35a6eb8e25d0b40f8bbc8ec225/src/Illuminate/Database/Query/Builder.php#L3266

**Comment by RahulDey12** [comment]
@nuernbergerA Still same

**Comment by jakubthedeveloper** [comment]
There is a mistake in the query:

```
    ->selectRaw("SUM('case(`status` in (?)) as total_pending", [[1,2,3]])
```
The apostrophe before "case" is not needed.

Of course, removing it will not solve the problem, but may help debugging it.

**Comment by driesvints** [comment]
Should be fixed with https://github.com/laravel/framework/commit/da7aa3870fa2aac57bbffa061f7491455bb3e105. Thanks

**Comment by atymic** [comment]
@driesvints apologies for the delay. I don't think this is fixed for sum/case in statements.

The issue seems to be that when I bind an wherein, the query builder is smart enough to put the correct amount of placeholders in, but it can't tell that when doing a selectraw with bound arrays. 

Will try to repro and find a workaround.

**Comment by jimktrains** [comment]
There is a similar issue when doing something like `whereIn(DB::raw('(a,b)', [[1,2]])`, as it only generates `where (a,b) in (?)` instead of `where (a,b) in ((?,?))`. (Or otherwise keep the single ? and bind it to `'(1,2)'`).

Should I open a separate ticket for that?

**Comment by driesvints** [comment]
@jimktrains best if you can send in a PR with a failing test so we can verify the bug.
