### ISSUE TITLE
psr/container requires php >= 7.4

### ISSUE THREAD

**Issue by nicolauns** [laravel/framework#39594]
- Laravel Version: 8.70.2
- PHP Version: 7.3
- Database Driver & Version: none

### Description:
I simply installed laravel 8.70.2 on a server with php 7.3 and it gave incompatibility because psr/container updated the required version to >= 7.4

### Steps To Reproduce:
only install a laravel project on php 7.3

**Comment by BrandonSurowiec** [comment]
In your `composer.json` file you can lock down the PHP version. Then when you run `composer update` it won't pull in anything that requires a higher PHP version.

```
{
   ...
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.3.20"
        }
    }
}
```

**Comment by driesvints** [comment]
Most likely, you ran composer require locally on a php version higher than 7.3 to update your lock file. Make sure you always use the same php version locally and on production.
