### ISSUE TITLE
[Broadcasting][Redis Driver] Channel name string can not include REDIS_PREFIX

### ISSUE THREAD

**Issue by pietrushek** [laravel/framework#39660]
- Laravel Version: v8.71.0
- PHP Version: `all`
- Database Driver & Version: `n/a`

### Description:

https://github.com/laravel/framework/blob/cea563d48e944a55f8e42042a5a93013ed58d4ad/src/Illuminate/Broadcasting/Broadcasters/RedisBroadcaster.php#L60-L75

Shortly:
Line 63 `str_replace` remove all appearances of prefix in channel name.
Why not use https://laravel.com/docs/8.x/helpers#method-str-after instead?

### Steps To Reproduce:

n/a

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
