### ISSUE TITLE
Pagination and API Resources

### ISSUE THREAD

**Issue by Livijn** [laravel/framework#39665]
- Laravel Version: 8
- PHP Version: 8

### Description:
Right now, there is an inconsistent behavior with pagination and API Resources. This issue is related to #32548 and #39070. It seems they were given up upon.

The issue appears when you want to return more data than just a paginated resource. This is a common situation and I think this issue has created problems for a bunch of people. [Here is a link](https://laracasts.com/discuss/channels/laravel/paged-resource-collection-not-working) to a discussion on Laracasts about this topic.

In short, this is where the problem lies:
```php
// This doesn't include meta-data
return response()->json(new PageCollection(Page::paginate()));

// But this does
return new PageCollection(Page::paginate());
```

The difference between these two are that on the first, the `toArray()` method is called, while on the second the `toResponse()` method is called. The pagination data is only added to the `toResponse()` method as you can see here: 

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Resources/Json/ResourceCollection.php#L114

Right now, my solution is:
```php
return response()->json(new ResourcePaginator(PageResource::collection(Page::paginate())));

// ResourcePaginator: https://gist.github.com/Livijn/6754194d52775892d2a678d2814d98e6
```

I think this is more of a bug than a feature request due to the inconsistency in the behavior. Another inconsistency is that the default paginator doesn't have the same structure as those inside of a resource. 🤯

**Comment by driesvints** [comment]
Use `return PageResource::collection(Page::paginate());`

**Comment by Livijn** [comment]
Not sure whether you misunderstood or if I was unclear. But the problem lies here:

> The issue appears when you want to return more data than just a paginated resource.

I actually covered your suggestion if you would look again, but that doesn’t solve this issue. Please reopen again

**Comment by driesvints** [comment]
@Livijn if you could stop downvoting my replies then that'd make me a whole lot more willingly to help you.

**Comment by Livijn** [comment]
Haha sorry about that. So to clearify, here are two examples where you would encounter this issue:

```php
return Inertia::render('Pages', ['pages' => new PageCollection(Page::paginate())]);
```

```php
return response()->json(['pages' => new PageCollection(Page::paginate()), 'more' => 'data']);
```

**Comment by driesvints** [comment]
I see what you mean. But `response()->json()` isn't supported. You need to use `return new PageCollection(Page::paginate());` as you demonstrated yourself.

**Comment by Livijn** [comment]
Well, I see from the source code that it isnt supported. But in my opinion it should be, for consistency.

Maybe you consider this more of a feature request. Would you be open for a PR implementing this behavior?

**Comment by driesvints** [comment]
You can always try to see if Taylor accepts it.

**Comment by valkedev** [comment]
It was completely unclear for me that JsonResponse doesn't supported and i glad i've fount the issue. But still why? I got used to wrap all my controllers responses to JsonResponse just to clearify and now i should do all the way behind to remove it...

**Comment by nicogominet** [comment]
I'm with you @valkedev @Livijn, I don't understand why `response()->json()` isn't supported.
Either I go back and change all my controllers `return` statements and functions typing or I do exceptions when returning a paginated result and I don't feel comfortable with either of these options.

**Comment by hairullana** [comment]
**paginate()** function will return an **LengthAwarePaginator**.
To handel **LengthAwarePaginator** on Resource, you can use this return format on toArray() to handle it.

```
public function toArray($request)
    {
        return [
            'current_page' => $this->currentPage(),
            'data' => MyModelResource::collection($this->items()),
            'first_page_url' => $this->url(1),
            'from' => $this->firstItem(),
            'last_page' => $this->lastPage(),
            'last_page_url' => $this->url($this->lastPage()),
            'next_page_url' => $this->nextPageUrl(),
            'path' => $this->path(),
            'per_page' => $this->perPage(),
            'prev_page_url' => $this->previousPageUrl(),
            'to' => $this->lastItem(),
            'total' => $this->total(),
        ];
    }
```

on **MyModelResource::collection($this->items())** is other resource to handle the data inside the pagination. It's work on my laravel 9 project.

**Comment by Tankonyako** [comment]
I use solution with resource for pagination, who has relation to specify resource,
link that:

**PaginateResource.php**
```php
<?php

namespace App\Http\Resources\API;

use Illuminate\Http\Resources\Json\JsonResource;

class PaginateResource extends JsonResource
{
     /**
     * Create a new resource instance.
     *
     * @param  mixed  $resource
     * @return void
     */
    public function __construct($resource, public $resourceClass = null)
    {
        parent::__construct($resource);
    }

    public function collect($resource)
    {
        return $this->resourceClass::collection($resource);
    }

    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'current_page' => $this->currentPage(),
            'data' => $this->collect($this->items()),
            'first_page_url' => $this->url(1),
            'from' => $this->firstItem(),
            'last_page' => $this->lastPage(),
            'last_page_url' => $this->url($this->lastPage()),
            'next_page_url' => $this->nextPageUrl(),
            'path' => $this->path(),
            'per_page' => $this->perPage(),
            'prev_page_url' => $this->previousPageUrl(),
            'to' => $this->lastItem(),
            'total' => $this->total(),
        ];
    }
}
```

Then usage:
```php
PaginateResource::make($paginated, YourResource::class)
```

**Comment by Tankonyako** [comment]
Also will cool if Laravel add it from the box

**Comment by siarheipashkevich** [comment]
@Tankonyako you can use `AnonymousResourceCollection`

**Comment by Isaque-Claudino-dos-Santos** [comment]
```php
return response()->json(ExampleResource::collection(ExampleModel::paginate());
```
```json
{
  "data": [],
  "links": {
    "first": "http://localhost:8000/api/ex?page=1",
    "last": "http://localhost:8000/api/ex?page=1",
    "prev": null,
    "next": null
  },
  "meta": {
    "current_page": 1,
    "from": null,
    "last_page": 1,
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "page": null,
        "active": false
      },
      {
        "url": "http://localhost:8000/api/ex?page=1",
        "label": "1",
        "page": 1,
        "active": true
      },
      {
        "url": null,
        "label": "Next &raquo;",
        "page": null,
        "active": false
      }
    ],
    "path": "http://localhost:8000/api/ex",
    "per_page": 15,
    "to": null,
    "total": 0
  }
}
```
