### ISSUE TITLE
Nova sets limit to 0 on BelongsTo

### ISSUE THREAD

**Issue by ImJustToNy** [laravel/framework#39662]
- Laravel Version: 8.71.0
- PHP Version: 8.0.10
- Database Driver & Version: psql 13.4

### Description:
![image](https://user-images.githubusercontent.com/5730766/142257951-f53c2b3c-6779-4cd7-9268-517d02efd171.png)

Commit that introduces problem: https://github.com/laravel/framework/commit/62273d20dd13b7e35885436d7327be31e3f54b0e

### Steps To Reproduce:
Create BelongsTo:: relation inside nova resource e.g.:
```php
BelongsTo::make('Category')
                ->searchable()
                ->withSubtitles()
                ->showCreateRelationButton(),

**Comment by driesvints** [comment]
Please update Laravel to the latest version

**Comment by lisotton** [comment]
I'm also having the same issue and I'm using the latest version o Laravel (8.71.0) and the latest version of Laravel Nova (3.30.0).

The cast was actually introduced in the latest Laravel version.

**Comment by lisotton** [comment]
Fixed by: https://github.com/laravel/framework/pull/39644
