### ISSUE TITLE
Collection::collapse() has different behavior for php stdClass object

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#39674]
- Laravel Version: 8.71
- PHP Version: 8.0.12

### Description:
When using collapse on php stdClass, It doesnt collapse the items instead it flush the items entirely:

### Steps To Reproduce:

when input is stdClass:

```php
$object = new \stdClass();
$object->id = 1;
$object->item = 'data';

collect([$object])->collapse();

//empty array returns
```
![image](https://user-images.githubusercontent.com/53290883/142383591-dc8cefcf-ada9-4de5-a4ef-9c118bf4db32.png)

when is array:

```php
$array = [];
$array['id'] = 1;
$array['item'] = 'data';

collect([$array])->collapse();
```

result for array:

![image](https://user-images.githubusercontent.com/53290883/142383710-afefdb0e-929d-43d4-8863-4955f664b39b.png)

**Comment by driesvints** [comment]
The method is intended to only work with arrays.

**Comment by foremtehan** [comment]
But i wrap the object with array : `collect([$object])->collapse();`

**Comment by driesvints** [comment]
@foremtehan you misunderstand the use of the method. It's intended to only work with arrays. If an object is the value of an array you need to do: `collect([[$object]])->collapse()`.

See https://laravel.com/docs/8.x/collections#method-collapse
