### ISSUE TITLE
strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Salem-Matloob-Al-Twami** [laravel/framework#39686]
- Laravel Version: 8.64.0
- PHP Version: 8.1.0

### Description:

strtolower(): Passing null to parameter #1 ($string) of type string is deprecated. 

To my humbling understanding,

This issue is there because we create an object of Swift_SmtpTransport with $transport = new SmtpTransport( $config['host'], $config['port'] ); on MailManage.php and on the constructor of Swift_SmtpTransport public function __construct($host = 'localhost', $port = 25, $encryption = null) and the default value of $encryption would be null and we call $this->setEncryption($encryption); on it!! 
I had to downgrade my PHP to 8.0 to avoid this issue. 

Is there any other fix to it?

![strtolowernullerror](https://user-images.githubusercontent.com/24455243/142496571-ebe96b02-58b7-488b-895e-302533fcf8c9.png)
Thank you

**Comment by driesvints** [comment]
Please upgrade to Swiftmailer 6.3.0 which provides PHP 8.1 support.
