### ISSUE TITLE
Custom Doctrine database column types can't be renamed

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/framework#39682]
- Laravel Version: 8.72.0
- PHP Version: 8.0.12
- Database Driver & Version: Postgres 13.4

### Description:

Columns using custom Doctrine database types cannot be renamed because the types are not registered properly, even when listed in `config/database.php` as described in the docs.

I know that the code responsible for actually changing the column itself is part of `doctrine/dbal` and not Laravel, but this issue is specifically about how Laravel registers custom column types from its config.

The code responsible for registering these custom types, in the framework's `DatabaseServiceProvider`, adds the "type" to Doctrine's registry but doesn't add the "type mapping":

https://github.com/laravel/framework/blob/ccea1bfcbb37cf923dc1bb30cdbf2effbfb1619c/src/Illuminate/Database/DatabaseServiceProvider.php#L123-L129

It actually did do both at one point, by calling `Schema::registerCustomDoctrineType()`, but this was removed (see https://github.com/laravel/framework/commit/382445f8487de45a05ebe121837f917b92560a97#diff-6122e442c6d761f6a9c1cfcc5f14af3306fccea75d8eb94fecbd399660e72c54).

Also, the test for this behaviour actually calls `Schema::registerCustomDoctrineType()` directly.

As far as I know, the fix for this issue is simply using `Schema::registerCustomDoctrineType()` again, which I'll PR shortly!

### Steps To Reproduce:

Given a custom Doctrine column type definition like this:

```php
namespace App\Support;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;

class XmlType extends Type
{
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return 'xml';
    }

    public function getName()
    {
        return 'xml';
    }
}
```

And a macro to let us refer to the type as just `xml` in migrations:

```php
PostgresGrammar::macro('typeXml', fn () => 'xml');
```

And with the type added to the database config [according to the documentation on modifying columns](https://laravel.com/docs/8.x/migrations#modifying-columns):

```php
// config/database.php
return [
    // ...
    'dbal' => [
        'types' => [
            'xml' => \App\Support\XmlType::class,
        ],
    ],
];
```

Assuming we already have a table with a column of this type:

```php
Schema::create('table_one', function (Blueprint $table) {
    $table->addColumn('xml', 'test_xml');
});
```

The custom column type still can't be renamed, this code throws an exception about an unknown database type `xml`:

```php
Schema::table('table_one', function (Blueprint $table) {
    $table->renameColumn('test_xml', 'test_renamed');
});
```

Repository with an app that reproduces the issue: https://github.com/bakerkretzmar/laravel-doctrine-type-registration-bug

Failing test in the app: https://github.com/bakerkretzmar/laravel-doctrine-type-registration-bug/blob/main/tests/Feature/ExampleTest.php

Failing GitHub Actions run showing test failure: https://github.com/bakerkretzmar/laravel-doctrine-type-registration-bug/runs/4246935916?check_suite_focus=true

**Comment by driesvints** [comment]
Thanks for reporting. Like Taylor indicated in the other PR, we'll need a more thorough fix for that. But since we won't be spending time on it ourselves, I'll close this issue report.
