### ISSUE TITLE
Missing "through" in the collection documentation

### ISSUE THREAD

**Issue by pixieaka** [laravel/framework#39690]
### Discussed in https://github.com/laravel/framework/discussions/39689

There's no documentation for "through" in entire Laravel documentation.

<div type='discussions-op-text'>

<sup>Originally posted by **pixieaka** November 19, 2021</sup>
https://laravel.com/docs/8.x/collections#method-map

![image](https://user-images.githubusercontent.com/17777237/142516241-92e68da1-c018-46ab-80fe-2da17ae93fef.png)
</div>

**Comment by driesvints** [comment]
Feel free to PR something. Don't open issues for this.
