### ISSUE TITLE
DateTime throws warning when it shouldn't

### ISSUE THREAD

**Issue by KreshnikUkmata** [laravel/framework#39699]
- Laravel Version: 8.72.0
- PHP Version: 8.0.12
- Database Driver & Version: 

### Description:
I have a place in my project where I need to validate to dates, they need to be consecutive, so I use something like this: 
```php
Illuminate\Support\Facades\Validator::make(
    [
        'start_date'    => now(),
        'end_date'      => now()->addMinute(1),
    ], [
        'start_date'    => 'date',
        'end_date'      => ['date', 'after:start_date'],
    ])->validate()
```

This code does return properly but it throws a warning:

```php
PHP Warning:  DateTime::modify(): Failed to parse time string (start_date) at position 0 (s): The timezone could not be found in the database in /var/www/integra2/app/vendor/nesbot/carbon/src/Carbon/Traits/Modifiers.php on line 439
=> [
     "start_date" => Illuminate\Support\Carbon @1637316876 {#1672
       date: 2021-11-19 11:14:36.510942 Europe/Berlin (+01:00),
     },
     "end_date" => Illuminate\Support\Carbon @1637316936 {#1673
       date: 2021-11-19 11:15:36.510979 Europe/Berlin (+01:00),
     },
   ]
```
I do not believe this is a situation where a warning should be thrown, could we do something about it?
### Steps To Reproduce:

You can run the code above to reproduce.

**Comment by driesvints** [comment]
This works for me in the latest Laravel release. 

![Screen Shot 2021-11-19 at 12 12 32](https://user-images.githubusercontent.com/594614/142613464-2abf196a-6a44-421a-945b-9ef1db152675.jpg)

![Screen Shot 2021-11-19 at 12 12 27](https://user-images.githubusercontent.com/594614/142613472-552b52b8-3a9c-4256-90e3-f15aac76f871.jpg)

**Comment by KreshnikUkmata** [comment]
@driesvints Yes, as I mentioned, it does work, but it throws a warning, try running it on tinker/tinkerwell to see the warning, here's the one liner: `Illuminate\Support\Facades\Validator::make(['start_date'=> now(),'end_date'=> now()->addMinute(1),],['start_date'=>'date','end_date'=>['date', 'after:start_date']])->validate();`

**Comment by driesvints** [comment]
I'll need to be able to reproduce in a Laravel app.
