### ISSUE TITLE
Laravel 9 crashes Apache on PHP 8.1

### ISSUE THREAD

**Issue by JackJohansson** [laravel/framework#39716]
- Laravel Version: 9.x-dev
- PHP Version: 8.1.0RC6
- Database Driver & Version: MySQL 8.0.23

### Description:
I've recently installed the development version of Laravel to test some PHP 8.1 features, however I'm unable to get it to work while using apache.

Using `php artisan serve` works just fine, but Apache crashes with the exception code of `Exception code: 0xc00000fd` which is related to recursively calling an action with no exit. In PHP, it seems to be related to sending a header without calling `exit();`. Disabling cache won't help. I don't think the issue is related to the Blade engine, as I can't even terminate the app via a middleware/service provider ( die() or exit() does nothing ).

### Steps To Reproduce:

- Install the latest version of Apache, PHP and MySQL. 
- Try to install the latest Laravel version ( 9.x ) using composer. 
- Now, create a virtual host ( optional ) and access the URL via browser. There will be a `Connection Reset` error. 
- Check the system's event log ( I'm running Windows 11 ) and you will notice there's an error indicating that Apache has crashed. Also, you will get an error similar to this in your apache log: `Parent: child process xxxx exited with status 255 -- Restarting.`

**Comment by GrahamCampbell** [comment]
We're gonna need more information than that. Can you run with xdebug and provide us with a stack trace? If not, is PHP segfaulting? If so, this is a bug in PHP itself, and a minimal replication example needs to be given to the PHP code team so that it can be fixed (either by one of them, or the wider community).

**Comment by JackJohansson** [comment]
@GrahamCampbell Thanks for the response!

I've grabbed a trace of the script execution. This is the entire file, and I'm not sure why there's no "TRACE END".

[trace.70521222.txt](https://github.com/laravel/framework/files/7576953/trace.70521222.txt)

If you need any more details, please let me know.

**Comment by GrahamCampbell** [comment]
Installing and enabling xdebug will prevent infinite recursive calls. You don't need to turn on any tracing. If it still segfaults, then this means there is no infinite recursion.

**Comment by GrahamCampbell** [comment]
Interesting the last thing I see in that trace is a call to preg_match. Is that when it crashed? Is the preg JIT enabled (this is not the same as the PHP JIT)?

**Comment by GrahamCampbell** [comment]
Does this script segfault for you? I cannot get it to crash for me.

```
<?php

var_dump(preg_match('(([\\r\\n]{1,1000})|([^\\S\\r\\n]{1,1000})|(\\\\)|(\')|(")|(\\#)|(\\$)|(([^(\\s\\\\\'"\\#\\$)]|\\(|\\)){1,1000}))A', 'Laravel', $matches));
```

**Comment by JackJohansson** [comment]
I was just doing that when you posted this! No, it doesn't output anything for me. The issue goes away when I set the `pcre.jit` to 0. I guess I take it to PHP support then.

Thanks for the heads up!

**Comment by GrahamCampbell** [comment]
Can you report this bug to PHP please?

**Comment by JackJohansson** [comment]
Of course, already did. Here's the link if anyone wants to check it out later:

**Comment by devcircus** [comment]
Don't know if it is related, but I ran into a similar problem running 8.1 on forge. Kept getting pcre & preg_match in my logs. Ended up having to upgrade libpcre2 via apt and everything started working.

**Comment by GrahamCampbell** [comment]
Oh, you must be using PHP compiled with dynamic linking against the system version instead of the bundled version. You do need the very latest version of that lib for PHP 8.1 to work properly.

**Comment by JackJohansson** [comment]
@devcircus Probably related. The differences are that I'm on windows, so the libraries are compiled and bundled with PHP itself. Also I wasn't getting any errors AT ALL. Just crash.

What I'm not sure about is that why `php artisan serve` works just fine, since I'm using the same php.ini for Apache and CLI.
