### ISSUE TITLE
Databases not being created when using parallel testing

### ISSUE THREAD

**Issue by Livijn** [laravel/framework#39711]
- Laravel Version: 8.73
- PHP Version: 8
- Database Driver & Version: MySQL 8

### Description:
When I run `php artisan test --parallel` I get an exception:
> Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000] [1049] Unknown database 'xxx_test_1'

My tests can run if I create the databases manually. So I looked into the source to see where it goes wrong. What I found was that this try/catch block is where something is messed up (for me at least). It seems like Laravel tries to use a database, and whenever it stumbles upon an exception it assumes that it should recreate the database.

However, for me, the exception that is thrown is of another type: `Doctrine\DBAL\Driver\PDO\Exception` not `Illuminate\Database\QueryException`.  So if I change that catch-handler to the right exception type it works.

https://github.com/laravel/framework/blob/f60e5ceccac453864edbf001b665450886cda8fc/src/Illuminate/Testing/Concerns/TestDatabases.php#L78-L89

Why is this happening? Is there something I've missed in an earlier Laravel upgrade? Or is it a bug?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Livijn** [comment]
So, I've tried to pin point the reason for this behavior. I found that this happens when requiring these two packages in a brand new Laravel installation:

```
"doctrine/dbal": "^2.8",
"grimzy/laravel-mysql-spatial": "^5.0",
```

I'm pretty sure its the [laravel-mysql-spatial](https://github.com/grimzy/laravel-mysql-spatial) that is causing these issues. Something similar stated here: https://github.com/grimzy/laravel-mysql-spatial/issues/178
