### ISSUE TITLE
High volume batched jobs resulting deadlock on database server degrading queue performance severely

### ISSUE THREAD

**Issue by gm-lunatix** [laravel/framework#39722]
We're using postgresql (v11), and horizon with redis for our queues. Using batched jobs forces us to use the database overhead since the batch progress is tracked in a database table (job_batches). 

If I have let say 1000 jobs in the batch and those are processed on 4 supervisors' 100 workers on two servers, then 2 x 4 x 100 concurrent job is trying to update the relevant fields (total_jobs, pending_jobs or failed_jobs). Since an update always starts with a "select * for update" the concurrency causes a long row level lock for most of the jobs (https://www.postgresql.org/docs/11/explicit-locking.html#LOCKING-ROWS). That in our case from ~800 concurrent jobs creates a race condition on the database server, snowballing the issue back to the queues, where jobs normally processed under 1 sec are now processed in 3-4+ secs, creating a huge backlog on the queues, stressing the db server and the queue worker servers further. Here's a snapshot of our database server top SQL queries showing the tuple (batch id) and transaction (update to increment a field) lock severity.
![image](https://user-images.githubusercontent.com/73477545/139495250-7b641ad0-eba7-4fdc-9042-493927157b81.png)

_Originally posted by @gm-lunatix in https://github.com/laravel/framework/issues/36478#issuecomment-955021257_

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by gm-lunatix** [comment]
I tried all support options, from laracast forums to discord. One month later didn't get any response. This is not the only oppened issue with this problem and one I tried to comment on (https://github.com/laravel/framework/issues/36478#issuecomment-955021257) was closed with the label "more info needed". I provided more info, not sure what else I can do. But fine if you do not care about this then don't.

**Comment by gm-lunatix** [comment]
Just for the record if anyone facing the same issue. 

In postgresql we can use 'fillfactor' to fine tune the heap only tuple for the table. Using the following change:
`ALTER TABLE job_batches SET (fillfactor = 80);`
significantly reduced the lock:tuple wait occurrences on the table while processing 4 times more jobs than I originally could when reported this issue
![image](https://user-images.githubusercontent.com/73477545/142919861-c47953af-19ce-43ac-bee0-6bf9abfaee7c.png)

Not sure how this translates to a possible pull request since my solution is PSQL specific. Maybe a mention in the documentation.

Sources: 
1) https://www.cybertec-postgresql.com/en/hot-updates-in-postgresql-for-better-performance/
2) https://www.cybertec-postgresql.com/en/what-is-fillfactor-and-how-does-it-affect-postgresql-performance/
