### ISSUE TITLE
Collection::collapse() reseting array keys

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#39732]
- Laravel Version: 8.70
- PHP Version: 8

### Description:
When using collapse on neste array it reset the keys order just like `values`, But this is unwanted imh

### Steps To Reproduce:
```php
$data = [
    [
        1 => [
            'name' => 'value'
        ],
        2 => [
            'name' => 'value'
        ]
    ]
];

collect($data)->collapse();
```

keys order has been reset:

![image](https://user-images.githubusercontent.com/53290883/143005276-98023648-27db-4342-b0cf-bb3f7adcd843.png)

**Comment by driesvints** [comment]
This is expected.
