### ISSUE TITLE
There is no assertModelExists method when testing

### ISSUE THREAD

**Issue by gutyina70** [laravel/framework#39733]
- Laravel Version: 8.59.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql version 15.1

### Description:
When testing with `PHPUnit`, and using the  `RefreshDatabase` trait, `assertModelExists` and `assertModelMissing` methods should exist, but they don't.

### Steps To Reproduce:
Start with a new Laravel project.
Use the `RefreshDatabase` trait in `Tests/TestCase.php`.
In tinker run the following:
```
>>> $test = new \Tests\Feature\ExampleTest();
>>> $test->assertModelExists()
PHP Error:  Call to undefined method Tests\Feature\ExampleTest::assertModelExists() in Psy Shell code on line 1
>>> $test->assertModelMissing()
PHP Error:  Call to undefined method Tests\Feature\ExampleTest::assertModelMissing() in Psy Shell code on line 1
```
You can see from the output, those methods were undefined

For testing the code above, it throws other errors than `undefined method` when calling an existing method, as it should:
```
>>> $test->assertDeleted()
PHP Error:  Call to protected method Illuminate\Foundation\Testing\TestCase::assertDeleted() from context '' in Psy Shell code on line 1
```

**Comment by driesvints** [comment]
Update your Laravel installation.
