### ISSUE TITLE
Testing\DatabaseMigrations trait incompatible with sqlite in-memory databases

### ISSUE THREAD

**Issue by BreiteSeite** [laravel/framework#39734]
- Laravel Version: 8.65.0
- PHP Version: 8.0.12
- Database Driver & Version: sqlite

### Description:
My tests fail with

```
Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 1 no such table: migrations (SQL: select "migration" from "migrations" order by "batch" asc, "migration" asc)
vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
vendor/laravel/framework/src/Illuminate/Database/Connection.php:663
vendor/laravel/framework/src/Illuminate/Database/Connection.php:367
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2351
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2563
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2873
vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2565
vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:53
vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:106
vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:85
vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:585
vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:94
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
vendor/laravel/framework/src/Illuminate/Container/Util.php:40
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
vendor/laravel/framework/src/Illuminate/Container/Container.php:653
vendor/laravel/framework/src/Illuminate/Console/Command.php:136
vendor/symfony/console/Command/Command.php:299
vendor/laravel/framework/src/Illuminate/Console/Command.php:121
vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:68
vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php:28
vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/FreshCommand.php:55
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
vendor/laravel/framework/src/Illuminate/Container/Util.php:40
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
vendor/laravel/framework/src/Illuminate/Container/Container.php:653
vendor/laravel/framework/src/Illuminate/Console/Command.php:136
vendor/symfony/console/Command/Command.php:299
vendor/laravel/framework/src/Illuminate/Console/Command.php:121
vendor/symfony/console/Application.php:978
vendor/symfony/console/Application.php:295
vendor/symfony/console/Application.php:167
vendor/laravel/framework/src/Illuminate/Console/Application.php:94
vendor/laravel/framework/src/Illuminate/Console/Application.php:186
vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:263
vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:219
vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:367
vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:66
vendor/laravel/framework/src/Illuminate/Foundation/Testing/DatabaseMigrations.php:16
vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:125
vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:90
tests/TestCase.php:37
```

because `\Illuminate\Database\Schema\SqliteSchemaState::load()` spawns a new process to run the sqlite3 binary to import the migration dump. This means, this process uses it's own isolated memory and therefor it's own in-memory database. The migrations are never reaching the in-memory database of the test.

### Steps To Reproduce:

1. ensure you have database migrations
2. setup your phpunit.xml and .env file to use `DB_DATABASE=:memory"` and `DB_CONNECTION=sqlite`.
3. run a test that uses the `\Illuminate\Foundation\Testing\DatabaseMigrations` trait

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by BreiteSeite** [comment]
Hey @driesvints this may look like a question, but really is a bug-report. :)

**Comment by driesvints** [comment]
<img width="710" alt="Screenshot 2021-11-23 at 15 06 24" src="https://user-images.githubusercontent.com/594614/143038863-ea3a1b46-adde-4009-9f8d-f104100f0f4e.png">

**Comment by BreiteSeite** [comment]
@driesvints thank you for the highlighted section. You are right then, this is documented and thus expected behaviour. Sorry for filing this issue then.

It would be nice in the future to consider throwing an appropriate exception when an in-memory database is used while trying to restore a dump. :)

Thanks again.
