### ISSUE TITLE
Swiftmailer should be replaced with Symfony's Mailer

### ISSUE THREAD

**Issue by robinheidrich** [laravel/framework#39737]
- Laravel Version: 8.73.2
- PHP Version: 8.0.13
- Database Driver & Version: 

### Description:
When upgrading Laravel to the latest version (8.73.2), a warning is displayed that "swiftmailer/swiftmailer" has been abandoned and "symfony/mailer" should be used instead.

### Steps To Reproduce:

```composer update```

**Comment by driesvints** [comment]
Symfony Mailer will be part of Laravel 9
