### ISSUE TITLE
Mail::panel component showing RAW html in email

### ISSUE THREAD

**Issue by emoss08** [laravel/framework#39753]
- Laravel Version: 8.73.2
- PHP Version: 8.0.0
- Database Driver & Version: Microsoft SQL Server 2019

### Description:
![Screenshot 2021-11-24 115650](https://user-images.githubusercontent.com/66630775/143282952-0aea7a47-371f-4dd6-b51f-c355e6e78d47.png)

@component('mail::panel') is showing raw html when emailed out.

### Steps To Reproduce:

Create view.blade.php for mail notification

Add  

```
@component('mail::message')
    # Test Output

    @component('mail::panel')
        Test Message
    @endcomponent

    Thanks,
    Laravel
@endcomponent
```

**Comment by rubengg86** [comment]
Just delete the space ant the beginning of @component

`@component('mail::message')
    # Test Output

@component('mail::panel')
        Test Message
@endcomponent

    Thanks,
    Laravel
@endcomponent`

**Comment by driesvints** [comment]
You're writing markdown. Spaces in front of words will invoke a code block.

**Comment by emoss08** [comment]
I removed the spaces

> You're writing markdown. Spaces in front of words will invoke a code block.

Thanks :)
