### ISSUE TITLE
Class circular reference：PendingRequest.php

### ISSUE THREAD

**Issue by ddzhi** [laravel/framework#39762]
- Laravel Version: 8.65
- PHP Version: 7.3.0
- Database Driver & Version:

### Description:
Memory leak

### Steps To Reproduce:
- Resident process consumption: new PendingRequest();
- https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Client/PendingRequest.php

- php artisan queue:work --queue=test:test:test
```php
    public function handle()
    {
        $request = new PendingRequest();
        //dump($request);
        echo round(memory_get_usage() / 1024 / 1024, 5)."m\n";
    }
```

![image](https://user-images.githubusercontent.com/20588527/143376727-36f9c15f-63e0-45eb-b311-c7c349ae5bec.png)

![image](https://user-images.githubusercontent.com/20588527/143375976-30b2d437-294f-41e8-88f1-a7d09dc81c80.png)

![image](https://user-images.githubusercontent.com/20588527/143376567-d8864d4e-c751-4869-b327-42c623d0bcb4.png)

**Comment by driesvints** [comment]
I'm not really sure I see an issue here sorry. If you want to provide a fix feel free to attempt a PR.
