### ISSUE TITLE
Parallel tests does not works with Postgres when default schema is different than `public`.

### ISSUE THREAD

**Issue by robsontenorio** [laravel/framework#39775]
- Laravel Version:  8.73.2
- PHP Version:  8.0.12
- Database Driver & Version: Postgres 13.0

### Description:

Parallel tests does not works with Postgres when default is schema different than `public`. Paratest always tries to use `public` schema. This is a problem, because sometimes you don't want to use `public` schema for security reasons.

```
SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  schema "myblog" does not exist at character 14 (SQL: create table "myblog"."migrations" ("id" serial primary key not null, "migration" varchar(255) not null, "batch" integer not null))
```

### Steps To Reproduce:

- Works : php artisan test
- Works: php artisan test --parallel

```
'pgsql' => [
            'driver' => 'pgsql',
            ....
            'schema' => 'public',
        ],
```

- Works : php artisan test
- **Dont Work**: php artisan test --parallel

```
'pgsql' => [
            'driver' => 'pgsql',
            ....
            'schema' => 'myblog',
        ],
```

**Comment by driesvints** [comment]
Since we don't consider running tests as part of production, we don't consider using public insecure. Atm this only works with public but we'd welcome PR's that also make this available for other schemes. Thanks.

**Comment by robsontenorio** [comment]
@driesvints  It has to do with https://github.com/laravel/framework/pull/37264/files

**Comment by driesvints** [comment]
Please see Taylor's comment: https://github.com/laravel/framework/pull/37264#issuecomment-833017437

**Comment by driesvints** [comment]
Sorry just saw https://github.com/laravel/framework/pull/37264#issuecomment-834501665. We won't be considering changes to this, sorry. Please use `public` for testing.
