### ISSUE TITLE
Js::from not working after release.

### ISSUE THREAD

**Issue by tanthammar** [laravel/framework#39777]
In PR #39389 a first version of a `Js::from` helper was created.

When performing tests in local projects it was working as described.

Now, that it is implemented in Laravel v8.73.2 it doesn't work anymore.

I don't recognize the code that has changed a lot since the PR, so I am not able to point out what went wrong.

With the code in the original PR
In a blade file `{{ \Illuminate\Support\Js::from($array) }}`
where $array = 
```php
$array = [
  "wrap" => true
  "enableTime" => false
  "weekNumbers" => true
  "altInput" => true
  "altFormat" => "M d, Y"
  "dateFormat" => "Y-m-d"
  "minDate" => "2020-10-01"
  "maxDate" => Illuminate\Support\Carbon {...}
  "locale" => "sv"
]
```
Became:
```json
JSON.parse(atob('eyJ3cmFwIjp0cnVlLCJlbmFibGVUaW1lIjpmYWxzZSwid2Vla051bWJlcnMiOnRydWUsImFsdElucHV0Ijp0cnVlLCJhbHRGb3JtYXQiOiJNIGQsIFkiLCJkYXRlRm9ybWF0IjoiWS1tLWQiLCJtaW5EYXRlIjoiMjAyMC0xMC0wMSIsIm1heERhdGUiOiIyMDIxLTEyLTI1VDIwOjMxOjUzLjkwMTAwNVoiLCJsb2NhbGUiOiJzdiJ9'
```

But now it outputs this, which doesn't work, for the intended purpose.
```json
JSON.parse('{\u0022wrap\u0022:true,\u0022enableTime\u0022:false,\u0022weekNumbers\u0022:true,\u0022altInput\u0022:true,\u0022altFormat\u0022:\u0022M d, Y\u0022,\u0022dateFormat\u0022:\u0022Y-m-d\u0022,\u0022minDate\u0022:\u00222020-10-01\u0022,\u0022maxDate\u0022:\u00222021-12-25T20:50:12.752608Z\u0022,\u0022locale\u0022:\u0022sv\u0022}'
```

Change history of the Js class.
https://github.com/laravel/framework/commits/8.x/src/Illuminate/Support/Js.php

**Comment by derekmd** [comment]
What does "doesn't work anymore" cover? Those two JavaScript statements for a PHP array have the same result when copy and pasted into a web browser console:

![js-snippet](https://user-images.githubusercontent.com/823566/143500606-36a05768-6f45-4c0d-8461-b5efb65133cf.png)

If there's a failing `Js::from()` return value (like a string that causes a JavaScript syntax error), a test case PR can be submitted to the framework.

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.
