### ISSUE TITLE
Model events not firing when modified via relationship without retrieval 

### ISSUE THREAD

**Issue by danjdewhurst** [laravel/framework#39787]
- Laravel Version: v8.73.1 (Sail running in WSL2)
- PHP Version: 8.0.12
- Database Driver & Version: MySQL (MariaDB 10.6.4)

### Description:

I have discovered that model events do not fire when you're accessing a relationship with brackets and calling `update()`. Removing the brackets of your relationship so that it's retrieved solves this, but I don't think you should need to.

I get why this happens, I just don't think it's great or obvious default behaviour. I for one would assume my model events would get fired as I'm accessing an Eloquent relationship.

### Steps To Reproduce:

1. Create a model that has a `hasOne()` relationship to another. Let's say `Customer` `hasOne()` `Order`.
2. Set a property of `Order` as fillable. I'll use `ref` as an example.
3. Add an event closure and listen for `updating` or `updating`. Stick a `dd()` in there or anything else to tell you if it gets hit.
4. Call `$customer->order()->update(['ref' => 'foobar'])`
5. The events don't get called.
6. Now remove the brackets next to order so you have  `$customer->order->update(['ref' => 'foobar'])`
7. The events now get called.

**Comment by driesvints** [comment]
This indeed is the expected behaviour. The first one is a direct query you're running, the second one a call on an actual model.

**Comment by brynj-digital** [comment]
Is this highlighted in the documentation at all? It's got some quite spectacular potential for bugs to be introduced in an app. 

Relationships in Laravel are defined in the model class, referencing other model classes - so I'm unclear how an update method called on a relationship wouldn't be updating the related models?

**Comment by johanrosenson** [comment]
@brynj-digital 

it's mentioned in the documentation, it apples to your usage with relationships also, even though it doesn't mention that specifically.

> When issuing a mass update or delete query via Eloquent, the saved, updated, deleting, and deleted model events will not be dispatched for the affected models. This is because the models are never actually retrieved when performing mass updates or deletes.

https://laravel.com/docs/8.x/eloquent#events
