### ISSUE TITLE
Cannot get the current login user in the login event listener when I re-login

### ISSUE THREAD

**Issue by yankewei** [laravel/framework#39796]
- Laravel Version: 8.65.0
- PHP Version: 8.0.12
- Database Driver & Version: Mysql 8.0.26

### Description:
Cannot get the current login user in the login event listener when I re-login, it returns null when using the `Auth::user()` 

### Steps To Reproduce:
- Create login event listener and write the `Log::info("Current user:", ['user' => Auth::user()]);` in the handle method
- The Authentication Guards driver is session
- Login the web
- Call `Auth::logout()` to log out of the currently logged-in user
- Call `Auth::loginUsingId($another_user_id)` to log in to the specified user

### Result
In the log file we got the message `local.INFO: Current user: {"user":null}`, we cannot get the current login user
### Excepted
local.INFO: Current user: {"user": {"name": "another user"}}
### Reason
The [loggedOut](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Auth/SessionGuard.php#L96) property is set to true once the Auth::logout() method has been called, it will be set to false when we re-login the user, but the login event has been fired before the loggedOut property is updated.
### Suggestion
When we call the `login()` method, we could always set the loggedOut property to true.

I am not the native english speaker, sorry for my bad english.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
