### ISSUE TITLE
Bug in implicit model binding when using withTrashed method on Route declaration and resolveRouteBinding in Model.

### ISSUE THREAD

**Issue by dopesky** [laravel/framework#39799]
- Laravel Version: 8.73.2
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 10.4.17 - MariaDB

### Description:
There seems to be an omission in implicit model binding on routes for Soft Deleted Models. When using the `withTrashed` method, the `resolveRouteBinding` method in the Model is not called. When `withTrashed` method is removed from the route declaration, the method `resolveRouteBinding` is called as expected.

### Steps To Reproduce:

Use this  route example:
```
Route::get('user/{user}', function(SoftDeletedModel $user) {
    dd($user);
})->withTrashed(); //withTrashed is used
```

SoftDeletedModel.php
```
use SoftDeletes;

public function resolveRouteBinding($value, $field = null) {
    dd("Successfully Substituted Bindings when using WithTrashed."); //This is not displayed.
    return parent::resolveRouteBinding($value, $field);
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
