### ISSUE TITLE
Undefined methods or wrong methods in migration does not throw error

### ISSUE THREAD

**Issue by ehsanrasta** [laravel/framework#39802]
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: mysql 7 

### Description:

After spending 2 hours to find out why migration does not create a foreign key with "on delete cascade" I figured out that I typed the method name wrong and the method name should start with a lowercase letter.
That was my mistake and I admit but I think it should return an error when chained methods are wrong or undefined instead of ignoring the wrong part and running the query.

### Steps To Reproduce:

Wrong typed migration:

`
 $table->foreign('list_id')->references('id')->on('lists')->OnDelete('cascade');
`

**Comment by DarkGhostHunter** [comment]
Laravel 7 is out of support since October 6th, 2020. You should upgrade.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
