### ISSUE TITLE
Undefined or wrong methods in migration does not throw error

### ISSUE THREAD

**Issue by ehsanrasta** [laravel/framework#39806]
- Laravel Version: 8.12
- PHP Version: 8.0.10
- Database Driver & Version: mysql 8

Description:
Due to #39802, I've tested on laravel 8 and the issue still exists

Steps To Reproduce:
Wrong typed migration:

`$table->foreign('list_id')->references('id')->on('lists')->OnDelete('cascade');`

**Comment by driesvints** [comment]
Use proper casing.

**Comment by ehsanrasta** [comment]
Do you even read the description?
It seems that laravel maintainers just want to close issues immediately. 
I know that casing is wrong, as I said in #39802, the laravel does not care about method names in migration and simply ignores wrong methods.
It should throw an error or show some warning during migration.

**Comment by ehsanrasta** [comment]
@driesvints

**Comment by driesvints** [comment]
I did. Don't uppercase your method names. I don't think we should throw any errors here.
