### ISSUE TITLE
Problem updating existing database fields

### ISSUE THREAD

**Issue by aa24615** [laravel/framework#39825]
- Laravel Version: 7.30.4
- PHP Version: 7.4.22
- Database Driver & Version:mysql5.6.20

### Description:
Failed to update the table when the database table name contains `-` when the SQL language name is not generated

This problem occurs when updating existing fields

The sample

```
Schema::table('table-name', function (Blueprint $table) {
    $table->renameColumn('field', 'field2');
});
```

error info

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use
 near '-name CHANGE `field` field2 INT DEFAULT 0 NOT NULL COMMENT 'xxx'' at line 1 (SQL: ALTER TABLE work_table-name CHANGE `field` field2 INT DEFAULT 0 NOT NULL COMMENT 'xxx')
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
