### ISSUE TITLE
Using enums does not work with query()->firstWhere

### ISSUE THREAD

**Issue by ismailnakkar** [laravel/framework#39834]
- Laravel Version: 8.74.0
- PHP Version: 8.1.0
- Database Driver & Version: - 

### Description:

Using enums does not work with query()->firstWhere in DB query builder

### Steps To Reproduce:

Use firstWhere with the new enums of php8.1

**Comment by driesvints** [comment]
This is a feature request.

**Comment by ismailnakkar** [comment]
It's not as using it with query()->where works fine

**Comment by marvinrabe** [comment]
@ismailnakkar Probably the same issue as #41098. Are your enums valid operators like `=`?
