### ISSUE TITLE
Laravel Framework uses swiftmailer dependency which is abandoned

### ISSUE THREAD

**Issue by the-hardik-sisodia** [laravel/framework#39852]
- Laravel Version: 8.74.0
- PHP Version: 8.0.10
- Database Driver & Version: 10.4.21-MariaDB

### Description:
Package [swiftmailer/swiftmailer](https://github.com/swiftmailer/swiftmailer) is abandoned, you should avoid using it. Use [**symfony/mailer**](https://github.com/symfony/mailer) instead.

### Steps To Reproduce:
If symfony/mailer works well, we can change [swiftmailer](https://github.com/swiftmailer/swiftmailer) to [symfony/mailer](https://github.com/symfony/mailer) in `composer.json` file

**Comment by driesvints** [comment]
Search the issue tracker before posting
