### ISSUE TITLE
Incorrect type hint for Illuminate\Database\Query\Builder::whereDate

### ISSUE THREAD

**Issue by wimski** [laravel/framework#39867]
- Laravel Version: 8.73.2
- PHP Version: 8.0.13
- Database Driver & Version:  MariaDB 10

### Description:
The `whereDate` method of `Illuminate\Database\Query\Builder` has an incorrect type hint for the `$column` parameter.

https://github.com/laravel/framework/blob/f4f8e32fcbc1d0ef8d70fbb47236003134e86620/src/Illuminate/Database/Query/Builder.php#L1245

It says it only accepts a string, but it also works with an instance of `Illuminate\Database\Query\Expression` (and maybe other types?).

My static analysis tool correctly generates an error for this:
```
Parameter #1 $column of method Illuminate\Database\Query\Builder::whereDate() expects string, Illuminate\Database\Query\Expression given. 
```

I've tried to change the raw `Expression` to a string like this:
```php
// cast as string
->whereDate((string) DB::raw('some statement'), $date)

// use string value
->whereDate(DB::raw('some statement')->getValue(), $date)
```

...but this results in the following error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'some statement' in 'where clause'
```

**Comment by driesvints** [comment]
If you want to change anything feel free to PR something. Thanks
