### ISSUE TITLE
BelongsToMany::syncWithPivotValues problem

### ISSUE THREAD

**Issue by kirya-dev** [laravel/framework#39889]
Problem exact in detaching process.
Detaches all models. By im expect only with save pivot values.

### Source data:
| product_id  |  category_id | assign_type  | 
|---|---|---|
|  200 | 31 | 1  | 
| 200 | 32 | 2 |
| 200 | 33 | 3 |

Run code
```php
$product->categories()->syncWithPivotValues([40, 41], ['assign_type' => 1]);
```

### Actual Data after:
| product_id  |  category_id | assign_type  | 
|---|---|---|
|  200 | 31 | 1  | 
| 200 | 32 | 2 |
| 200 | 33 | 3 |

### Expect Data after:
| product_id  |  category_id | assign_type  | 
|---|---|---|
| 200 | 32 | 2 |
| 200 | 33 | 3 |
|  200 | 40 | 1  | 
|  200 | 41 | 1  | 

---
```
$ composer show laravel/framework
name     : laravel/framework
descrip. : The Laravel Framework.
keywords : framework, laravel
versions : * v8.69.0
```

**Comment by kirya-dev** [comment]
At all working correct for me when:
```php
$pivot = ['assign_type' => 1];
$product->categories()->where($pivot)->syncWithPivotValues([40, 41], $pivot);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kirya-dev** [comment]
Ithink not. But I sure currently its a bug.
