### ISSUE TITLE
InvoicePaid and Illuminate\Bus\Queueable define the same property ($afterCommit) in the composition (docs)

### ISSUE THREAD

**Issue by LastDragon-ru** [laravel/framework#39888]
- Laravel Version: v8.74.0
- PHP Version: 8.0
- Database Driver & Version:

### Description:

The documentation contains an invalid example of Queued notification: https://laravel.com/docs/8.x/notifications#queued-notifications-and-database-transactions  `Illuminate\Bus\Queueable` cannot be used if you want to redefine default values of `$afterCommit`, `$queue` and other properties.

### Steps To Reproduce:

1. Copy-paste code from https://laravel.com/docs/8.x/notifications#queued-notifications-and-database-transactions
2. Try to send a notification

```php
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

class InvoicePaid extends Notification implements ShouldQueue
{
    use Queueable;

    public $afterCommit = true;
}
```

**Comment by LastDragon-ru** [comment]
Maybe something like can be used

```php
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

class InvoicePaid extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * @return array<string,string>
     */
    public function viaQueues(): array {
        $this->queue       = 'queue';
        $this->afterCommit = true;

        return [];
    }
}
```

**Comment by driesvints** [comment]
@LastDragon-ru does it work if you remove the Queueable trait altogether and keep the property?

**Comment by LastDragon-ru** [comment]
Yes, it will work. The problem is PHP doesn't allow redefining values of trait properties (https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.properties).

**Comment by driesvints** [comment]
Thanks, I've sent in a PR to the docs: https://github.com/laravel/docs/pull/7485
