### ISSUE TITLE
Foundation pushes exception from log context to LoggedExceptionCollection

### ISSUE THREAD

**Issue by Plytas** [laravel/framework#39904]
- Laravel Version: 8.74.0
- PHP Version: 7.4.26
- Database Driver & Version: not needed

### Description:
In our application we had set up a new logging channel and we were passing an array to log context with key `exception`. FoundationServiceProvider picks up this key and pushes it to LoggedExceptionCollection and that in turn makes tests fail that check response status.

This happens because [FoundationServiceProvider](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php#L109-L114) listens to `MessageLogged` event and pushes `$event->context['exception']` to `LoggedExceptionCollection`. [TestResponse](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Testing/TestResponse.php#L191-L195) sees this exception and tries to cast it to string.

I'm not sure if exception key in log context should be treated as real exception. If this behavior is intended, we will adjust our code accordingly.

### Steps To Reproduce:
1. Create a fresh laravel application
2. Change `web.php` route to include a log with `exception` array in context:
```PHP
Route::get('/', function () {
    \Illuminate\Support\Facades\Log::info('foo', [
        'exception' => [
            'bar'
        ]
    ]);

    return view('welcome');
});
```
3. Run default provided test
```PHP
public function test_example()
{
    $response = $this->get('/');

    $response->assertStatus(200);
}
```
4. See `ErrorException : Array to string conversion`

**Comment by X-Coder264** [comment]
This behavior is intended -> see https://github.com/laravel/framework/issues/38464 for more details.

**Comment by Plytas** [comment]
@X-Coder264 thank you. Somehow wasn't able to find mentioned issue.
