### ISSUE TITLE
PHP 8.1 int enums not working as default value in migrations

### ISSUE THREAD

**Issue by mpskovvang** [laravel/framework#39912]
The default grammar casts a default non-boolean value to a string.
```PHP
enum QuoteStatus: int
{
    case DRAFT = 1;
    case SENT = 2;
    case ACCEPTED = 4;
    case REJECTED = 8;
    case CANCELLED = 16;
}
```
```PHP
public function up()
{
    Schema::create('quotes', function (Blueprint $table) {
        $table->id();
        $table->unsignedTinyInteger('status')->default(QuoteStatus::DRAFT);
    });
}
```
> Object of class App\Enums\QuoteStatus could not be converted to string at vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/Grammar.php:276

https://github.com/laravel/framework/blob/1638472a7a5ee02dc9e808bc203b733785ac1468/src/Illuminate/Database/Schema/Grammars/Grammar.php#L294-L303

**Comment by mpskovvang** [comment]
I just learned that native enums act like an object.

The following snippet works:

```PHP
if (is_object($value) && enum_exists(get_class($value))) {
   return "'" . $value->value . "'";
}
```

**Comment by driesvints** [comment]
Resubmit this with a filled out issue template
