### ISSUE TITLE
Migration Blueprint does not accept native enum as default value

### ISSUE THREAD

**Issue by mpskovvang** [laravel/framework#39914]
- Laravel Version: 8.70.2
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 5.7.25

### Description:
The migration `Blueprint` does not accept a native enum as a default value.

> Object of class App\Enums\QuoteStatus could not be converted to string
  at vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/Grammar.php:276

The reason seems to be Laravel trying to cast the value to a `string`:

https://github.com/laravel/framework/blob/1638472a7a5ee02dc9e808bc203b733785ac1468/src/Illuminate/Database/Schema/Grammars/Grammar.php#L294-L303

### Steps To Reproduce:

1. Create a native enum:

```PHP
<?php

namespace App\Enums;

enum QuoteStatus: int
{
    case DRAFT = 1;
    case SENT = 2;
    case ACCEPTED = 4;
    case REJECTED = 8;
    case CANCELLED = 16;
}
```

2. Create a new migration file:

```PHP
<?php

return new class extends Migration
{
    public function up()
    {
        Schema::create('quotes', function (Blueprint $table) {
            $table->id();
            $table->unsignedTinyInteger('status')->default(QuoteStatus::DRAFT);
        });
    }
}
```

3. Run `php artisan migrate`

### Addtional information

The native enum act like an object. If enums should be supported, it seems a new condition must be added to the `getDefaultValue` method like:

```PHP
if (is_object($value) && function_exists('enum_exists') && enum_exists(get_class($value))) {
   return "'" . $value->value . "'";
}
```

*The snippet above is not tested for side effects.*

### Alternative

If decided to now support enums, the solution is to use the `value` property of the enum object:
```PHP
$table->unsignedTinyInteger('status')->default(QuoteStatus::DRAFT->value);
```

**Comment by driesvints** [comment]
This is a feature request, not a bug. Recently, enums in migrations got rejected here: https://github.com/laravel/framework/pull/39854
