### ISSUE TITLE
Array key control in validation rules

### ISSUE THREAD

**Issue by eminkokdemir** [laravel/framework#39949]
### Discussed in https://github.com/laravel/framework/discussions/39948

<div type='discussions-op-text'>

<sup>Originally posted by **eminkokdemir** December  8, 2021</sup>
Hi all, can we define rules according to the key of the values sent in Array type?
If there is no such feature, can you add it?
For example, it could be:

`'currencies.[*]' => '...',`

![Screen Shot 2021-12-09 at 00 26 56](https://user-images.githubusercontent.com/70816881/145286909-0c56a14d-f75d-4fc9-a38e-eac7155a00d3.png)
</div>

**Comment by driesvints** [comment]
Please don't convert discussions to issues.
