### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by yurih567** [laravel/framework#39964]
- Laravel Version: 8.75.0
- PHP Version: 8.1.0

### Description:

I'm getting several depreciation alerts when running tests in phpunit, for example:

`
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 276
.....
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 276
.
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 276
.
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 276
.
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php on line 276
`

**Comment by driesvints** [comment]
Try adding this line to your `logging.php` file: https://github.com/laravel/laravel/pull/5711/files#diff-9ba917899def7f26cdd2c34da749863fbb2797a40aed5e41a1166a022b10d7dfR33
