### ISSUE TITLE
Macro's with pass by reference parameters don't work

### ISSUE THREAD

**Issue by lurza** [laravel/framework#39966]
- Laravel Version: 8.75.0
- PHP Version: 8.1

### Steps To Reproduce:

```php
function passByReferenceBug(&$array) {
	$array[] = "should be appended";
}

Arr::macro("testBug", "passByReferenceBug");

$array = [];

Arr::testBug($array);

dump($array); // returns []

passByReferenceBug($array);

dump($array); // returns ["should be appended"] <== this time it actually appends like it should
```

**Comment by driesvints** [comment]
Hey @lurza, this indeed doesn't work and is expected. If you want to attempt to change this behaviour, feel free to attempt a PR.

**Comment by lurza** [comment]
For future reference:

Macro's use __call and __callStatic internally. These don't support call by reference.
