### ISSUE TITLE
qualifyColumns has inconsistent behavior between model and query instance in Laravel 8

### ISSUE THREAD

**Issue by glmdev** [laravel/framework#39962]
- Laravel Version: 8.74.0
- PHP Version: 7.4.21
- Database Driver & Version:

### Description:
When upgrading an application from Laravel 7 to Laravel 8, I discovered a bug where the behavior of `qualifyColumns` differs between Model and Builder instances, which it didn't do in Laravel 7.

The Builder version of `qualifyColumns` no longer properly handles multiple parameters passed in. It just returns the qualified form of the first param, whereas in Laravel 7 and the Model version, it returns qualified form of all parameters.

#### Laravel 7 Behavior (consistent)
```txt
Psy Shell v0.10.8 (PHP 7.4.21 — cli) by Justin Hileman
>>> (new App\Models\User)->qualifyColumns('a', 'b')
=> [
     "users.a",
     "users.b",
   ]
>>> (new App\Models\User)->query()->qualifyColumns('a', 'b')
=> [
     "users.a",
     "users.b",
   ]
>>> app()->version()
=> "7.30.4"
>>>
```

#### Laravel 8 Behavior (inconsistent)
```txt
Psy Shell v0.10.12 (PHP 7.4.21 — cli) by Justin Hileman
>>> (new App\Models\User)->qualifyColumns('a', 'b')
=> [
     "users.a",
     "users.b",
   ]
>>> (new App\Models\User)->query()->qualifyColumns('a', 'b')
=> [
     "users.a",
   ]
>>> app()->version()
=> "8.74.0"
>>>
```

**Comment by driesvints** [comment]
Heya. This behaviour got changed between major versions so that's allowed. This might have been better updated in the upgrade guide though. We welcome PR's for that. Thanks.
