### ISSUE TITLE
Job backoff array accessed by number of job attempts instead of failures

### ISSUE THREAD

**Issue by matheusb-comp** [laravel/framework#39976]
- Laravel Version: 8.74.0
- PHP Version: 7.4.26
- Database Driver & Version: N/A

### Description:
The [documentation about job failures](https://laravel.com/docs/8.x/queues#dealing-with-failed-jobs) states about `backoff`:
> Using the --backoff option, you may specify how many seconds Laravel should wait before retrying **a job that has encountered an exception**.

And then:
> You may easily configure "exponential" backoffs by returning an array of backoff values from the backoff method

However, [when accessing this array](https://github.com/laravel/framework/blob/cf00a5621f2eacdb978d3176e6d601193d9dc57d/src/Illuminate/Queue/Worker.php#L600), the 
 `Illuminate\Queue\Worker` class uses `$job->attempts()` and not the number of failures as the index.

Since the number of attempts also increases when using the `release` function, some elements of the backoff array may never be used as the "backoff value" when unhandled exceptions are detected by the queue worker.

For example, if the backoff array is defined as: `[5, 50, 500]`, the following could happen:
```
- Attempt #1: throw new Exception();
... wait 5 seconds
- Attempt #2: $this->release();
... wait 0 seconds
- Attempt #3: throw new Exception();
... wait 500 seconds
- Attempt #4...
```

The number of failures is [counted in the Cache](https://github.com/laravel/framework/blob/cf00a5621f2eacdb978d3176e6d601193d9dc57d/src/Illuminate/Queue/Worker.php#L550) and used for the [max exceptions](https://laravel.com/docs/8.x/queues#max-exceptions) option.
Shouldn't this value also be used as the index when accessing the backoff array?

### Steps To Reproduce:

- Create a Job class with a `backoff` array with at least two elements
- In the first attempt of the job, call `$this->release()`
- In the second job attempt, throw an `Exception`
- The backoff time until the third job attempt will be the second element of the `backoff` array, and not the first.

<details>
  <summary>Example Job class (will never use the 10s backoff)</summary>

```
<?php

namespace App\Jobs;

use Exception;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 10;
    public $maxExceptions = 5;

    public function __construct()
    {
        //
    }
    
    public function backoff()
    {
        return [10, 20, 30];
    }

    public function handle()
    {
        if ($this->attempts() > 1) throw new Exception();
        $this->release();
    }
}
```
</summary>

**Comment by driesvints** [comment]
Let's see how the PR goes.
