### ISSUE TITLE
Segfault on handle excecptions

### ISSUE THREAD

**Issue by PedroPMS** [laravel/framework#40016]
- Laravel Version: 8.50.0
- PHP Version: 7.4.21

### Description:
Hi, I'm using the laravel-imap library to read emails. This library is triggering a notice while reading, laravel is trying to process this error in Illuminate\Foundation\Bootstrap\HandleExceptions but during this process it is generating a segfault.

If I run the process using tinker, only the notice is thrown and the process continues, if I run it using `php artisan command:name` the segfault happens.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by PedroPMS** [comment]
Running using `php artisan`
![segfault](https://user-images.githubusercontent.com/48099126/145809266-9932a09a-6609-46e0-a5f4-1f77366d4220.png)

Running using tinker
![notice](https://user-images.githubusercontent.com/48099126/145809268-7980d47d-da78-4100-9477-b7fdad4def7d.png)
