### ISSUE TITLE
sync([]) does not detach all existing relations

### ISSUE THREAD

**Issue by heyjoe1984** [laravel/framework#40017]
- Laravel Version: 8.65
- PHP Version: 8
- Database Driver & Version: MySql 8

### Description:

Calling `sync` using an empty array or null value does not detach all existing relationships.

From the docs:

> If you do not want to detach existing IDs that are missing from the given array, you may use the syncWithoutDetaching method

To me, this tells me that it should detach all existing records if an empty array is passed to `sync`, no?

**Comment by driesvints** [comment]
No, that's not how `sync` works. An empty array will be ignored. Since this has been asked about a couple of times, I'll send in a PR to the docs about this: https://github.com/laravel/docs/pull/7506

You're looking for `$user->roles()->detach();`

**Comment by heyjoe1984** [comment]
It actually does work with empty arrays, it was Livewire having problems with checkbox arrays that caused my issue. 

So it wasn't a laravel problem, that's why I closed it. But thank you for your time.

**Comment by driesvints** [comment]
@heyjoe1984 ah okay, thanks for confirming that 👍
