### ISSUE TITLE
The method upsert() does not add the parent id when inserting on the relationship

### ISSUE THREAD

**Issue by adiafora** [laravel/framework#40049]
- Laravel Version: 8.75.0
- PHP Version: 8.0.13
- Database Driver & Version: PostgreSQL 13.4

### Description:

If you want to use the ```upsert()``` method to insert or update relationships, then it will not add the id of the parent model.
For example, a similar ```createMany()``` method adds the id of the parent model.

### Steps To Reproduce:

1. Create a Post model with one-to-many User relationships. Migration can look like this:
```php
Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(User::class)
                ->index()
                ->constrained()
                ->onDelete('cascade');
});
```
2. Define relationships in models:

```php
class User extends Model
{
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

class Post extends Model
{
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
``` 

3. Add multiple posts via relationships:
```php
$user = User::find($id);
$postsRequest = $request->all();

$user->posts()
     ->upsert($postsRequest, ['id']);
```

4. In response, you will receive an error:

```sql
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "user_id" of relation "posts" violates not-null 
constraint DETAIL: Failing row contains...
```
And if you print out the INPUT data, you will see that there really is no "user_id" field.

**Comment by driesvints** [comment]
Hi @adiafora. I'm not sure support for upserting on relationships is supported at the time. There's an open PR now to add this so let's see how that goes. Thanks
