### ISSUE TITLE
Blade component as translation variable is not rendered

### ISSUE THREAD

**Issue by rapkis** [laravel/framework#40051]
- Laravel Version: 8.66.0
- PHP Version: 8.0.12
- Database Driver & Version: MySQL 8.0

### Description:
I've run into an issue where I need to wrap a part of a translation string with one of my Blade Components, yet the rendering of it breaks.
For example, let's assume I have a string `If you need help, please contact us`, where the "contact us" part should be a hyperlink.
When using regular HTML markup, I could achieve my result by creating a translation string as such:

```php
'contact_us' => 'If you need help, please :LINKOPENcontact us:LINKCLOSE',
```

and rendering it as such:

```
<div>
    @lang('contact_us', ['LINKOPEN' => '<a href="#">', 'LINKCLOSE' => '</a>'])
</div>
```

However, if I do the same approach and simply change my anchor tag to a custom blade component (which simply contains the same anchor tag with a slot), the rendering breaks (in some cases for the whole file):

```
<div>
    @lang('contact_us', ['LINKOPEN' => '<x-custom-link href="#">', 'LINKCLOSE' => '</x-custom-link>'])
</div>
```

results in this markup:

```
<div>
    ('contact_us', ['LINKOPEN' =&gt; '<a href="#">
        ', 'LINKCLOSE' =&gt; '
    </a>
'])
</div>
```

I've also attempted other functions such as `{!! trans() !!}` and `{!! __() !!}` which have similar results. What's interesting to note here, is that the opening and closing tags `{!!` and `!!}` and actually echoed/rendered in the final HTML as plain text.

I'd also like to stress out that it doesn't matter wether or not the blade component's opening and closing tags are split into two variables or passed into a single variable. For example, the usage below still results in incorrect markup being rendered:

```
// language file
'contact_us' => 'If you need help, please :FOO',

// blade file
@lang('contact_us', ['FOO' => '<x-custom-link href="#">bar</x-custom-link>',])
```

### Steps To Reproduce:

- Create a custom Blade Component
- Create a translation string with variables
- When rendering the string, pass your custom blade component tag as your translation variables
- It doesn't matter wether or not the blade component's opening and closing tags are split into two variables or passed into a single variable.

**Comment by driesvints** [comment]
That's not supported I'm afraid. Blade components are meant to be in views so the compiler can detect them and render them. You can't dynamically insert them into the view.
