### ISSUE TITLE
HTTP client automatically throws exception after retrying

### ISSUE THREAD

**Issue by mattkingshott** [laravel/framework#40055]
- Laravel Version: 8.75.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8.0.27

### Description:

When a retry is specified within the HTTP client, and the retry limit is reached, then the response is automatically thrown. Since there is no way to hook into the `throw` method, you'll always get a `RequestException`. Therefore, you cannot do things like `$response->failed()`

The problem lies within `Illuminate\Http\Client\PendingRequest`, on lines 682-684:

```php
if ($this->tries > 1 && ! $response->successful()) {
    $response->throw();
}
```

### Steps To Reproduce:

Simply, add a retry configuration to the HTTP client:

```php
Http::fake([
    '*' => Http::response(['error'], 403),
]);

$response = Http::retry(3, 5000)->post('https://example.com/route'); 

// The above line throws a RequestException, so the below error handling will not be reached

if ($response->failed()) {
    // error handling
}
```

**Comment by driesvints** [comment]
Hey @mattkingshott, this is the expected behaviour. Please see the docs here:

![Screenshot 2021-12-16 at 14 28 39](https://user-images.githubusercontent.com/594614/146380700-f3b62baa-b45d-4b3e-9aab-d5343e5b2f0a.png)

If you want to see a different behaviour then please attempt a PR. Thanks

**Comment by mattkingshott** [comment]
Oh my. Sorry I missed that. Maybe will attempt a PR for this.
