### ISSUE TITLE
[8.x] Factory needs to guess the model name, even though it's created from one

### ISSUE THREAD

**Issue by borys-p** [laravel/framework#40068]
- Laravel Version: 8.x
- PHP Version: 8.x
- Database Driver & Version: n/a

### Description:

I noticed this seemingly unnecessary complexity when setting up factories for models in nested namespaces. To make it work I had to add or override decent amount of code, even though it seems not really needed in the first place.

How it works right now:

1. Factory instance is created by calling `ModelName::factory()`, which then calls `Factory::factoryForModel()`. 
2. The call is made with the model class name as an argument and it is used to determine the factory class name. So far so good.
3. The newly created factory instance has no ties back to the original model, so it guesses the model class name using its own class name. At this point the original namespace of the model is lost, **even though we had it available at the beginning**.

Unless I'm missing something obvious here, `$factory::new()` could keep the model class name, which could be optionally overridden by `static::$modelNameResolver` and the `$model` property just as it is now. The default resolver isn't particularly useful anyway, as it just searches for the class in two default namespaces (`App\Models` and `App`).

But before I invest time into preparing a PR I would like to get a confirmation whether that's actually a bug or there is a scenario that needs to have it done this way.

### Steps To Reproduce:

As above

**Comment by driesvints** [comment]
Please resubmit this with exact versions and exact steps to reproduce. Thanks
