### ISSUE TITLE
Date validation nullable with before_or_equal or after_or_equal broken

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#40086]
- Laravel Version: 8.76.0
- PHP Version: 7.4.4
- Database Driver & Version: MySQL 5.7.31

### Description:
Validation for nullable dates looks "broken", or better not working as before.
After the last updates, some of our validations throw exceptions for invalid data.
The issue seems to be with a combination of nullable and before_or_equal  or after_or_equal.
I believe the issue caused by https://github.com/laravel/framework/commit/d1ef8e588cc7efc3b3cf925b42f134aa54a4f9c7

### Steps To Reproduce:
```
$validation0 = Validator::make(['date_from' => '2020-01-01'], [
    'date_from' => 'required|before_or_equal:date_to|date_format:Y-m-d',
    'date_to'   => 'nullable|after_or_equal:date_from|date_format:Y-m-d',
]);

$validation0->validate(); // THROWS EXCEPTION NOW, BEFORE NO

$validation1 = Validator::make(['date_from' => '01-01-2020'], [
    'date_from' => 'required|before_or_equal:date_to|date_format:d-m-Y',
    'date_to'   => 'nullable|after_or_equal:date_from|date_format:d-m-Y',
]);

$validation1->validate();// THROWS EXCEPTION NOW, BEFORE NO

$validation2 = Validator::make(['date_from' => '2020-01-01'], [
    'date_from' => 'required|before_or_equal:date_to|date_format:Y-m-d',
    'date_to'   => 'nullable|date_format:Y-m-d',
]);

$validation2->validate();// THROWS EXCEPTION NOW, BEFORE NO

$validation3 = Validator::make(['date_from' => '2020-01-01'], [
    'date_from' => 'required|before_or_equal:date_to|date_format:Y-m-d',
    'date_to'   => 'nullable',
]);

$validation3->validate();// THROWS EXCEPTION NOW, BEFORE NO
```

**Comment by driesvints** [comment]
@mariosvasiliou thanks for your report. I dived into this and managed to come up with a fix: https://github.com/laravel/framework/pull/40088

I'd appreciate it if you could try it out for your use cases.

**Comment by mariosvasiliou** [comment]
@driesvints Thank you for your fast response. I have tried it. Your fix looks that solve the issue.
Thanks

**Comment by Daniel-HBK** [comment]
strange. I have the same issue with after and before.

`                    'instalment_1'            => 'required|numeric',
                    'date_1'                  => 'required|date|after:yesterday',
                    'instalment_2'            => 'nullable|numeric',
                    'date_2'                  => 'nullable|date|after:date_1|before:date_3',
                    'instalment_3'            => 'nullable|numeric',
                    'date_3'                  => 'nullable|date|after:date_2|before:date_4',
                    'instalment_4'            => 'nullable|numeric',
                    'date_4'                  => 'nullable|date|after:date_3',`


- Laravel Version: 9.36.4
- PHP Version: 8.1.11
