### ISSUE TITLE
Enum validation rule does not have translatable message

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#40080]
- Laravel Version: 8.76.2
- PHP Version: 8.1.0
- Database Driver & Version: 8.0.27

### Description:

Hi all.

I want to try [Enum validation rule](https://laravel.com/docs/8.x/validation#rule-enum) and find that the `message` not translatable for this rule.

Is it possible to make this message translatable without extending this rule and overriding this method?

### Steps To Reproduce:

Use Enum validation rule with different languages.

**Comment by driesvints** [comment]
Hey @siarheipashkevich. Thanks for your report. I've sent in a PR for this here: https://github.com/laravel/framework/pull/40089
