### ISSUE TITLE
php artisan migrate:reset not reseting other database connections

### ISSUE THREAD

**Issue by Nimaw** [laravel/framework#40097]
- Laravel Version: 8.28.1
- PHP Version: 8.0.9
- Database Driver & Version: MYSQL 10.4.20-MariaDB

### Description:
When i've running command `php artisan migrate:reset` it reseting created tables but it isn't reset other database connections. 

### Steps To Reproduce:
Create some migrations with different database connections then run `php artisan migrate`, it runs all migrations on multiple connections, but  after if you run `php artisan migrate:reset` it isn't reset all tables.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
