### ISSUE TITLE
Fix deprecation warning for filesystemmanager / s3

### ISSUE THREAD

**Issue by Atomzwieback** [laravel/framework#40109]
- Laravel Version: 8.76.1
- PHP Version: 8.1.0

### Description:

The value `$root` @ /src/Illuminate/Filesystem/FilesystemManager.php:222
should not return "null" due the S3 Client throws an deprecation waring if "null" is provided.
Instead "null" an empty string should be returned

**Comment by driesvints** [comment]
This value gets set [here](https://github.com/thephpleague/flysystem-aws-s3-v2/blob/master/src/AwsS3Adapter.php#L93) and then [here](https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/AbstractAdapter.php#L28) where it is typecast before it's set. Are you on the latest Flysystem v1 and flysystem-aws-s3-v2 versions?

**Comment by Atomzwieback** [comment]
but the typecast is not the problem.

`Passing null to parameter #1 ($string) of type string is deprecated`

Problem is the warning deprecated spam for passing null

**Comment by driesvints** [comment]
Please share your flysystem and flysystem-aws-s3-v2 versions.

**Comment by Atomzwieback** [comment]
flysystem-aws-s3-v3: 1.0.29

not v2 or standalone flysystem?

**Comment by driesvints** [comment]
I'm sorry but I don't see an issue with Laravel here. Feel free to try a support channel or open an issue on the flysystem issue tracker.
