### ISSUE TITLE
Illuminate\Database\Connection->$tablePrefix is an array

### ISSUE THREAD

**Issue by aleksrutins** [laravel/framework#40117]
- Laravel Version: 8.76.2
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8.0.27

### Description:
When running any database-related Artisan command (e.g. `migrate`, `schema:dump`), it spits out an `Array to string conversion` error:
```
❯ php artisan migrate

   ErrorException 

  Array to string conversion

  at vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php:41
     37▕      * @return bool
     38▕      */
     39▕     public function hasTable($table)
     40▕     {
  ➜  41▕         $table = $this->connection->getTablePrefix().$table;
     42▕ 
     43▕         return count($this->connection->select(
     44▕             $this->grammar->compileTableExists(), [$this->connection->getDatabaseName(), $table]
     45▕         )) > 0;

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
❯ php artisan schema:dump

   ErrorException 

  Array to string conversion

  at vendor/laravel/framework/src/Illuminate/Database/Console/DumpCommand.php:69
     65▕      */
     66▕     protected function schemaState(Connection $connection)
     67▕     {
     68▕         return $connection->getSchemaState()
  ➜  69▕                 ->withMigrationTable($connection->getTablePrefix().Config::get('database.migrations', 'migrations'))
     70▕                 ->handleOutputUsing(function ($type, $buffer) {
     71▕                     $this->output->write($buffer);
     72▕                 });
     73▕     }

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

This appears to result from the concatenation of `connection->tablePrefix` with various strings, which would mean that, although `tablePrefix` is annotated as a `string`, something is assigning it to an array.

### Steps To Reproduce:

I'm not entirely sure what caused this. It started happening immediately after I created a new migration, but I hadn't run the 
`migrate` command in a while, so it could have been something else. Also, when I moved all of my custom migrations out of the `database/migrations` directory, it continued to occur. I will attach a GitHub repo as soon as possible.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
