### ISSUE TITLE
Postgres read/write connection not working right...

### ISSUE THREAD

**Issue by mayken** [laravel/framework#40120]
- Laravel Version: 8.76.2
- PHP Version: 8.1
- Database Driver & Version: Postgres 14

### Description:
I have some database configuration:

```
'pgsql' => [
            'driver' => 'pgsql',
            'read' => [
                'host' => env('DB_HOST', '127.0.0.1'),
                'port' => env('DB_PORT', '5432'),
            ],
            'write' => [
                'host' => env('DB_HOST_WRITE', '127.0.0.1'),
                'port' => env('DB_PORT_WRITE', '5432'),
                'database' => env('DB_DATABASE_WRITE', 'forge'),
                'username' => env('DB_USERNAME_WRITE', 'forge'),
                'password' => env('DB_PASSWORD_WRITE', ''),
            ],
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'sticky' => true,
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => env('DB_SSLMODE', 'disable'),
        ],
```

Also used the package https://github.com/umbrellio/laravel-pg-extensions for some models.

Any call Model (without use laravel-pg-extensions) execute select query from write connection, but no from read connection. How fix this Problem?

**Comment by driesvints** [comment]
We can't provide support for that package sorry. Please try one of these channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
