### ISSUE TITLE
Visual bug with bootstrap 5

### ISSUE THREAD

**Issue by angeloskalaitzakis** [laravel/framework#40125]
- Laravel Version: v8.77.0
- PHP Version: v8.0.13
- Database Driver & Version:

### Description:
Laravel update bootstrap 4 to 5 but the forms are still using bootstrap 4 so it doesn't display properly.
For example:
`<label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>`
should be:
`<label for="email" class="col-md-4 col-form-label text-md-end">{{ __('E-Mail Address') }}</label>`
 
the _"text-md-right"_ not longer used in bootstrap 5 should be _"text-md-end"_

**Comment by driesvints** [comment]
This will be fixed in today's release of laravel/ui. Thanks
