### ISSUE TITLE
[8.x] Pivot ids are strings not integers

### ISSUE THREAD

**Issue by dillingham** [laravel/framework#40136]
- Laravel Version: 8.54
- PHP Version: 8.0
- Database Driver & Version: mysql 5.7

### Description:
The automatic pivot ids are strings when other ids are ints

Failed asserting that 1 is identical to '1'.
Failed asserting that 2 is identical to '2'.

### Steps To Reproduce:

```php
->assertJsonPath('post.id', $post->id) ✅
->assertJsonPath('tag.pivot.post_id', $post->id) 🚫
->assertJsonPath('tag.pivot.tag_id', $tag->id); 🚫
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
