### ISSUE TITLE
Redis::sscan(): Argument #2 ($i_iterator) must be passed by reference, value given

### ISSUE THREAD

**Issue by akalongman** [laravel/framework#40149]
- Laravel Version: 8.77.1
- PHP Version: 8.0.13
- Database Driver & Version: 8.0.14
- Redis Version: 5.3.4
- Driver: PhpRedis

### Description:
Looks like its related to Redis tagged cache. 

```
ErrorException
Redis::sscan(): Argument #2 ($i_iterator) must be passed by reference, value given
vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:384
```

### Steps To Reproduce:

Just call
```php
app(\Illuminate\Contracts\Cache\Repository::class)->tags(['some', 'tags'])->flush();
```

**Comment by it-can** [comment]
@dkuzmenchuk

**Comment by dkuzmenchuk** [comment]
@it-can I'm not sure, because the implementation of the `sscan` method in client was not changed. I just used already existing method.

**Comment by driesvints** [comment]
A fix was merged and will be released tomorrow. Thanks

**Comment by akalongman** [comment]
@driesvints latest Laravel release does not have this fix?

**Comment by driesvints** [comment]
Some stuff has been reverted it seems. We don't want to introduce breakages but if you can figure out a non breaking way to fix this we're welcoming PR's.

**Comment by akalongman** [comment]
@driesvints maybe it is worth to reopen this issue first?

**Comment by driesvints** [comment]
We won't be reopening this sorry. If it can be solved non-breaking we're welcoming PR's.

**Comment by akalongman** [comment]
Sorry, but I did not get what is happening now. 

So, I found a bug in the Laravel framework (introduced in this PR #39939 ), reported it, then you closed the issue without fixing it and did not want to open it? 
Why?

cc @taylorotwell
