### ISSUE TITLE
 make route name wrong in Illuminate\Foundation\Auth\Access\AuthorizesRequests.php's authorizeResource method 

### ISSUE THREAD

**Issue by dds813** [laravel/framework#40152]
- Laravel Version: 8.65
- PHP Version: 8.1
- Database Driver & Version:mysql & 5.7

### Description:
authorizeResource这个函数在使用过程中有问题呀，我看了他的源码，发现他生成的middleware指向的路由名称不对，比如我的model是model，我要调用show这个方法的时候，那么它最后生成的$this->middleware($middlewareName, $options)->only($methods);这里的only里面指向的路由名称是show，而实际上应该指向的是novels.show,所以我每次使用这个生成的middleware来验证都会返回403错误，我在Illuminate\Foundation\Auth\Access\AuthorizesRequests.php的authorizeResource里面加了一行$routePrefixName = Str::snake(class_basename($model)).'s';然后在生成$middleware 这个数组的时候改成了$middleware["can:{$ability},{$modelName}"][] = $routePrefixName.'.'.$method;这样他就可以指向novels.show，然后验证就通过了，但是我不知道我这样是否正确，站长帮忙看看是否可行，是否还有其他方法，或者是不是我的使用方法根本就有错误，才导致出现这个问题的

There is a problem in the use of the authorizeresource function. I looked at its source code and found that the name of the route pointed to by the middleware generated by it is wrong. For example, my model is model. When I want to call the show method, it finally generates $this - > middleware ($middlewarename, $options) - > only ($methods); The route name pointed to in only here is show, but actually it should point to novels Show, so every time I use the generated middleware to verify, I will return 403 error. I'm in illuminate \ foundation \ auth \ access \ authorizesrequests PHP adds a line $routeprefixname = STR:: snake (class_basename ($model)). ' s'; Then, when generating the array of $middleware, it is changed to $middleware ["can: {$ability}, {$modelname}"] [] = $routeprefixname. '$ method; So he can point to novels Show, and then the verification passed, but I don't know if I'm right. The webmaster helps to see if it's feasible, if there are other methods, or if there's a mistake in my use method, which leads to this problem
before
![image](https://user-images.githubusercontent.com/23622494/147369340-1c8fe9ff-85a4-426a-a07e-249f9e238e5b.png)
after
![image](https://user-images.githubusercontent.com/23622494/147369313-4877e113-b044-48e9-9572-f0b330a37061.png)

**Comment by masterwto** [comment]
I met this problem today. Seems something wrong, leading to my PolicyClass not called properly and giving me 403.
