### ISSUE TITLE
`php artisan db` command does not work when separate read and write hosts are configures in db config

### ISSUE THREAD

**Issue by aleexdhillon** [laravel/framework#40186]
- Laravel Version: 8.77.1
- PHP Version: 7.4.27
- Database Driver & Version:
mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Description:
I have configured separate read and write connections in database config file, like below

![Screenshot 2021-12-28 153939](https://user-images.githubusercontent.com/85165956/147557966-def2bc82-c903-4b00-b82a-f3c26f37aba1.png)

And when running the `php artisan db` it cannot find the host and throw exception.

![Screenshot 2021-12-28 154159](https://user-images.githubusercontent.com/85165956/147558122-eedfdbbc-cbc5-4363-aa5a-6a2c67e526ca.png)

### Steps To Reproduce:
1. Setup the separate read write connections for mysql in database config
`'read' => [
                'host' => [
                    env('DB_HOST_SLAVE', '127.0.0.1')
                ],
            ],
            'write' => [
                'host' => [
                    env('DB_HOST_MASTER', '127.0.0.1')
                ],
            ],`
2. Run `php artisan db` or `php artisan db mysql`

**Comment by jelib3an** [comment]
You can use `php artisan db --read` or `php artisan db --write` to specify which host to use. But it appears there is a bug with that too. It doesn't work if `host` is an array...

This works though
```php
'read' => [
    'host' => env('DB_HOST_SLAVE', '127.0.0.1'),
],
'write' => [
    'host' => env('DB_HOST_MASTER', '127.0.0.1'),
],
```
But this does NOT...
```php
'read' => [
    'host' => [
        env('DB_HOST_SLAVE', '127.0.0.1'),
    ],
],
'write' => [
    'host' => [
        env('DB_HOST_MASTER', '127.0.0.1'),
    ],
],
```
