### ISSUE TITLE
Date cast on eloquent model returns a new Carbon instance each time the property is accessed

### ISSUE THREAD

**Issue by developerbmw** [laravel/framework#40195]
- Laravel Version: 8.77.1
- PHP Version: 8.0.14
- Database Driver & Version: mysqlnd 8.0.14

### Description:
Date casts on eloquent models are done when the property is accessed (with no caching) resulting in a new/separate Carbon instance being returned each time. This causes two issues:
1. Poor performance with heavy use of the date property - it's being re-parsed from the underlying string every time it's accessed.
2. Confusing behavior with mutable date objects - for example `$model->date->addMinutes(15)` doesn't modify the data on the model.

### Steps To Reproduce:
Create a model with a date cast:
```
class Example extends Model
{
    protected $casts = ['date' => 'datetime'];
}
```

Observe strange behavior:
```
$example = new Example();
$example->date = '2021-12-01 00:00:00'; // Simulate date string from database
$example->date->addDays(2);
echo $example->date->toDateString(); // Outputs the original unmodified date
```

**Comment by driesvints** [comment]
Hey there. I'm sorry but we don't consider this a bug. This has been the behaviour ever since date time casting was introduced. I realise this might be unexpected but for now the best thing you can do is write your own cast if you want the specific behaviour you require. Sorry
