### ISSUE TITLE
Php 8.1 controller error with optional parameter

### ISSUE THREAD

**Issue by salimkanoun** [laravel/framework#40219]
- Laravel Version: 8.77.1
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:

I have a simple route with an optional parmeter, my controller is type hinted as followed to benefit from dependency injection.
When an HTTP request is sent on this route with the missing optional parameter, I got a PHP error saying arugment 1 should be int but recieved Request object (and thus output 500 error)

Sounds like the optional parameter is not assigned to its default value when missing in the controller.
This issue is thrown by php 8.1.1 but not php 8.0

### Steps To Reproduce:
`Route::get('centers/{code?}', [CenterController::class, 'getCenter']);`
`public function getCenter(?int $code=null, Request $request, GetCenterRequest $getCenterRequest, GetCenterResponse $getCenterResponse, GetCenter $getCenter)`

Best regards,

Salim

**Comment by BrandonSurowiec** [comment]
This is a PHP error, not a Laravel one. It is yelling because your required parameters are not first. Reorder your params:

```
public function getCenter(
	  Request $request,
	  GetCenterRequest $getCenterRequest,
	  GetCenterResponse $getCenterResponse,
	  GetCenter $getCenter,
	  ?int $code=null
) {
    // ...
}
```

**Comment by salimkanoun** [comment]
Sorry, the error was on my side, the route variable should be declared after the injected depencies. 
So by reodering the variable as following solved the problem : 
`public function getCenter(Request $request, GetCenterRequest $getCenterRequest, GetCenterResponse $getCenterResponse, GetCenter $getCenter, ?int $code=null)`

optional parameter in first position was accepted by php<=8.0 but not starting 8.1

Sorry for disturbing, good luck to laravel community and thank you for you amazing work ! 
Thank you @BrandonSurowiec for your help !
