### ISSUE TITLE
a bug using json fields with casts enebled !

### ISSUE THREAD

**Issue by Hadjjo** [laravel/framework#40225]
- Laravel Version: 9.x-dev
- PHP Version: 8.0
- Database Driver & Version: 8.7

### Description:
a problem that insert a json data with backslases in mysql db only when casts is enabled and set to object
but i commented it out it inserted the data normale without backslashes you can see the diff in the picture attached

### Steps To Reproduce:
- Create a model factory
- Create migration that has a json field
- Seed the db with some json data without casts enabled // Works fine in this
- Now try to enable casts on the model on the json field with a type of object and feed the db again
- it feed the db with back slashes  indicated that is type of 

https://i.imgur.com/xaJuIkC.png

**Comment by BrandonSurowiec** [comment]
This isn't an issue with Laravel. You are assigning the model value as a string and not an array.

Doing something like:

```
$model->meta = "{foo: bar}";
```

That is why it is surrounded with double-quotes and then the inner double-quotes are escaped. 

You should be doing this:

```
$model->meta = ['foo' => 'bar'];

// or

$model->meta = json_decode("{foo: bar}");

```

I suggest you review the documentation: <https://laravel.com/docs/8.x/eloquent-mutators#array-and-json-casting>

Hope that helps!

**Comment by driesvints** [comment]
Thanks @BrandonSurowiec
