### ISSUE TITLE
SQLite Grammar ignored with column type change

### ISSUE THREAD

**Issue by Korko** [laravel/framework#40224]
- Laravel Version: v8.77.1
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:
When changing a column type, SQLite Grammar is ignored leading sometimes to unknown column type. There errors does not happen when creating the table.

### Steps To Reproduce:
Create a migration with a simple column typed tinyText.
Create a migration to change it to another column that works anyway like "text".
Create a third migration to change it back to tinyText.

The migration will run perfectly on MySQL but not in SQLite (test database for example).

See my example-app just created https://github.com/Korko/example-app
With the feature ExampleTest `sail artisan test`

> Unknown column type "tinytext" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

**Comment by driesvints** [comment]
Tinytext doesn't exists in SQLite.

**Comment by Korko** [comment]
That's exactly the whole point. You CAN make a Blueprint::tinyText column in SQLite because the SQLiteGrammar converts it into "text" but you CANNOT change a column into Blueprint::tinyText as the Grammar is not applied.

**Comment by Korko** [comment]
You really should consider reopening this ticket as it's a real issue and the reason you gave is the exact reason this ticket is.
