### ISSUE TITLE
The issue is a new pattern of Attribute Cast

### ISSUE THREAD

**Issue by michaelnabil230** [laravel/framework#40230]
I'm using the new version of `Attribute Cast` in the Laravel version: 8.77 but showed this error when logged in authorization with guard admin 

- Laravel Version: 8.77.1
- PHP Version: 8.0

### Error:
![image](https://user-images.githubusercontent.com/46572405/147882230-c67acc1d-1056-464d-8043-edd094bd25ed.png)

### Model Admin:
```php
<?php

namespace App\Models\Tenant;

use Illuminate\Database\Eloquent\Casts\Attribute;

class Admin extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    /**
     * The authentication guard name.
     *
     * @var string
     */
    public $guard = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    /**
     * Set the admin's Hash password.
     *
     * @return Attribute
     */
    protected function password(): Attribute
    {
        return new Attribute(
            set: fn($value) => Hash::make($value),
        );
    }
}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by michaelnabil230** [comment]
Hi there,
It's not a question but it seems to be a bug 
Now, I'm asking how to report this bug correctly

**Comment by michaelnabil230** [comment]
Hi there,
It's not a question but it seems to be a bug
Now, I'm asking how to report this bug correctly

**Comment by BrandonSurowiec** [comment]
@michaelnabil230 @driesvints I believe this is a legitimate bug. All the tests that Taylor wrote tests the attribute when there is a value set. But if you don't set one and the model is blank, you get this error:

![image](https://user-images.githubusercontent.com/5625680/147948840-ccbac1b9-f517-4762-bd24-d15d9450d754.png)

**Comment by driesvints** [comment]
Thanks @BrandonSurowiec. I'll check into that.

**Comment by michaelnabil230** [comment]
Thanks @driesvints @BrandonSurowiec ♥️

**Comment by michaelnabil230** [comment]
@driesvints 
And thanks to me because i reported this bug also 😄

**Comment by michaelnabil230** [comment]
Thanks @driesvints @BrandonSurowiec ♥️

**Comment by driesvints** [comment]
I did an attempt at fixing this but think there's still a caveat to work around before we can merge it. I've put up the PR for Taylor to review: https://github.com/laravel/framework/pull/40245
