### ISSUE TITLE
Old and new Mutators/Accessors results not always the same

### ISSUE THREAD

**Issue by hmennen90** [laravel/framework#40242]
- Laravel Version: 8.77.1
- PHP Version: 8.1.1
- Database Driver & Version: None

### Description:

Laravel is used without Database Access. This part is provided by a additional C# Backend.

Using own getter and setter to the "old" schema:

set{Attribute}Attribute and get{Attribute}Attribute like the following works without any Problems:

```
public function setAgreementsAttribute(object|array|null $agreements) {
        if($agreements === null) {
            $agreements = collect();
        }

        if(!$agreements instanceof Collection) {
            $agreements = collect($agreements);
        }

        $this->attributes['agreements'] = $agreements->map(function($agreement) {
            return !$agreement instanceof Agreement ? new Agreement((array)$agreement) : $agreement;
        });
    }

    public function getAgreementsAttribute() {
        return $this->attributes['agreements'];
    }

```
Using the new schema:

```
protected function agreements(): Attribute {
        return new Attribute(
            get: fn($agreements) => $agreements,
            set: function($agreements) {
                if($agreements === null) {
                    $agreements = collect();
                }

                if(!$agreements instanceof Collection) {
                    $agreements = collect($agreements);
                }

                return $agreements->map(function($agreement) {
                    return !$agreement instanceof Agreement ? new Agreement((array)$agreement) : $agreement;
                });
            }
        );
    }
```

Results in my Tests with the following Message:

Failed asserting that stdClass Object (...) is an instance of class "Illuminate\Support\Collection".

Note: If a leave the old schema together with the new, it works. This error occurs only, if I do only use the new schema.

### Steps To Reproduce:

=> Use Http Fake for fetching a Model with a Relation

=> Override the all() Method to simply execute this Http Request and get the Faked Response

=> Use the old Accessor/Mutator => $agreementType->agreements works

=> Use the new Accessor/Mutator => $agreementType->agreements is simply an Object, not a Collection.

Note: the Object seems to be a wrong converted array:

{#2553
  +"0": {#2606
    +"id": 634
    +"doubleOptIn": false
    +"name": "Abdullah Grady PhD"
    +"label": "Jovanny Rowe"
    +"description": "aliquid eum eaque consequatur accusantium"
    +"sort": 4
    +"active": true
    +"required": false
    +"agreementTypeId": 924
  }
  +"2": {#2623
    +"id": 812
    +"doubleOptIn": true
    +"name": "Virgil Purdy"
    +"label": "Leanna Brakus I"
    +"description": "non rerum necessitatibus aperiam necessitatibus"
    +"sort": 5
    +"active": true
    +"required": true
    +"agreementTypeId": 924
  }
  +"4": {#2622
    +"id": 700
    +"doubleOptIn": false
    +"name": "Prof. Ruth Heathcote DVM"
    +"label": "Prof. Nestor Block V"
    +"description": "numquam eos placeat et nesciunt"
    +"sort": 3
    +"active": true
    +"required": false
    +"agreementTypeId": 924
  }
  +"6": {#2621
    +"id": 270
    +"doubleOptIn": true
    +"name": "Dallas Kling"
    +"label": "Blaise O'Connell"
    +"description": "ipsa quo et id praesentium"
    +"sort": 4
    +"active": true
    +"required": true
    +"agreementTypeId": 924
  }
  +"8": {#2620
    +"id": 57
    +"doubleOptIn": false
    +"name": "Jermey Heathcote I"
    +"label": "Rosalyn Schaefer"
    +"description": "eius consequuntur magnam sit ut"
    +"sort": 3
    +"active": true
    +"required": false
    +"agreementTypeId": 924
  }
}

**Comment by hmennen90** [comment]
I've just found this:

Modifying the __get Method in Model like this:

```
public function __get($key) {
        if(Arr::has($this->attributes, $key) && !is_object($this->attributes[$key])) {
            return $this->getAttribute($key);
        }
        return $this->attributes[$key] ?? null;
    }
```

Is working as Expected. So I'm not sure, if it is a bug or simply my mistake?

**Comment by BrandonSurowiec** [comment]
It is not recommended to override the native `__get` method of the `Model` class. So this is an issue caused by your modifications and not Laravel. If you comment out your `__get` method you will see that it works as intended.

Seems you were trying to cache the value of your attributes so they wouldn't be evaluated again. Would recommend you remove that customization and find another way to do what you want that isn't so invasive. Caching perhaps. Otherwise, you'll want to fix your code.

**Comment by driesvints** [comment]
Thanks @BrandonSurowiec

**Comment by hmennen90** [comment]
@BrandonSurowiec by default, I do not override the __get Method of the Model class. It was during the debugging Process and not in productive Code.

`return $this->attributes[$key] ?? null;`

Returns the Collection as I wanted. 

`return $this->getAttribute($key);`

Produces the odd JSON

**Comment by BrandonSurowiec** [comment]
@hmennen90 You're right, I can't read. 😅

**Comment by hmennen90** [comment]
No Problem ;-) @BrandonSurowiec

**Comment by BrandonSurowiec** [comment]
@hmennen90 The object output is due to filtering the collection and not running `collect(---)->values()` to re-index the array keys. (You'll notice keys 0, 2, 4, 6, 8.) So maybe see if adding a `->values()` call in your controller helps. Seems like you're returning an object for json array output.

**Comment by hmennen90** [comment]
@BrandonSurowiec I didn't saw this - but your hint was the key :-D
