### ISSUE TITLE
jsonOptions call in collection now breaks resources

### ISSUE THREAD

**Issue by philcross** [laravel/framework#40258]
- Laravel Version: 8.78.0
- PHP Version: 7.4.26
- Database Driver & Version: mysql:5.6 (not applicable)

### Description:

Applicable line that breaks: https://github.com/laravel/framework/commit/53a9850acc47bddbd88323f654f8d5a9836b9777#diff-c4c25c5d79379e9906d8542c16c242a333232362f6222b8568cdc2ce6aba3f0dR66

In our resource classes we either type hint the model in the constructor, or allow multiple parameters, or additional classes / datatypes to be passed in to the constructor, or sometimes I use a domain model rather than an eloquent model (for example, if we have some data we store in a config file that we want to return using a resource)

```php
class UserResource extends JsonResource
{
    public function __construct(User $resource) {}
    // or sometimes stuff like
    public function __construct(User $resource, array $somethingElse) {}
    // or some domain model
    public function __construct(SomeNonEloquentClass $resource) {}
}
```

However in this change merged yesterday 
 - https://github.com/laravel/framework/commit/53a9850acc47bddbd88323f654f8d5a9836b9777#diff-c4c25c5d79379e9906d8542c16c242a333232362f6222b8568cdc2ce6aba3f0dR66 , when creating a resource collection, it now attempts to fetch `JsonOptions` from the singular resource class, by new-ing up an instance of it with an empty array. 

This breaks any resource that typehints or uses multiple required parameters in the constructor. It now forces you to use a typehint-less constructor with a single parameter. 

This is the first couple of lines of the stack trace during:

```
#0  App\Http\Resources\Api\V1\Claims\BasicClaimResource->__construct() called at [/var/www/projects/xyz/vendor/laravel/framework/src/Illuminate/Http/Resources/CollectsResources.php:66]
#1  Illuminate\Http\Resources\Json\ResourceCollection->jsonOptions() called at [/var/www/projects/xyz/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php:28]
```

With the addition of the code in the PR, it now attempts to create an instance of `BasicClaimResource` with an empty array, just to call the `jsonOptions` method

It's not the biggest of problems and is fairly straight forward to fix ourselves by overriding the jsonOptions method in our resource collections to prevent it trying to new up a singular resource, but it has taken a little while to debug why updating a minor version has broken my existing resources and feels like it warrants an issue report, if anything to help other developers that may experience the same issue.

### Steps To Reproduce:

https://github.com/philcross/laravel-jsonOptions-bug

I've added a feature test in `tests/Feature/BugTest.php` and added an action to run it: https://github.com/philcross/laravel-jsonOptions-bug/runs/4709456339?check_suite_focus=true

Reproduction steps:

1) Create new project
2) Create a new UserResource and UserResourceCollection class
3) In the `UserResource` class, declare the constructor and typehint the `User` model
4) in a controller, attempt to create a new instance of the `UserResourceCollection` class by passing in a collection of User models

**Comment by kyryl-bogach** [comment]
The root problem is in:

```php
// src/Illuminate/Http/Resources/CollectsResources.php

public function jsonOptions()
{
    $collects = $this->collects();

    return $collects ? (new $collects([]))->jsonOptions() : 0;
}
```

Where an empty collection is being created sending an array instead of the class we are expecting (`new $collects([])`)

**Comment by driesvints** [comment]
Thanks!
