### ISSUE TITLE
New Accessor not working during save events

### ISSUE THREAD

**Issue by mpie** [laravel/framework#40268]
- Laravel Version: 8.78.1
- PHP Version: 8.0.12
- Database Driver & Version: MySQL 8.0.26

### Description:
When calling a method during a saving event, the attribute is marked as dirty, which results in a wrong query:
```sql
1054 Unknown column 'bar' in 'field list'
```
 
With the old Mutators/Accessors the attribute is not marked as dirty and the query runs just fine.

### Steps To Reproduce:
Create a method that calls the accessor.
For example:
```php
protected function bar(): Attribute
{
    return new Attribute(
        get: fn () => 1,
    );
}

public function foo() 
{
    return $this->bar;
}
```

Call foo() in the saving event in the model for example:
```php
public static function boot()
{
    static::saving(function ($model) {
        $model->foo();
    }
}
```

Save the model to trigger the event:
```php
$model->update(['something' => true]);
```

**Comment by driesvints** [comment]
We'll look into this. Thanks!

**Comment by taylorotwell** [comment]
I've tried to recreate this but can't on latest Laravel 8.x commit...

User model:

<img width="560" alt="CleanShot 2022-01-06 at 10 08 45@2x" src="https://user-images.githubusercontent.com/463230/148413086-8f594d46-45a1-4354-9a31-41a8afef2683.png">

Route:

<img width="537" alt="CleanShot 2022-01-06 at 10 09 10@2x" src="https://user-images.githubusercontent.com/463230/148413107-bf750cab-71ef-4b62-bfcd-31193a52f02f.png">

No errors and query executed:

<img width="576" alt="CleanShot 2022-01-06 at 10 09 23@2x" src="https://user-images.githubusercontent.com/463230/148413137-d737a2a1-2201-4717-a46e-a04eefb10cbf.png">

**Comment by mpie** [comment]
@taylorotwell it happens during the boot() not booted()
I see that I've forgotten to close the `static::saving()` in my example. But you get the point hehe.

**Comment by mpie** [comment]
@taylorotwell I've got one that can be reproduced easily for you:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $guarded = [];

    public static function boot()
    {
        parent::boot();

        static::saving(function ($model) {
            $model->foo();
        });
    }

    protected function bar(): Attribute
    {
        return new Attribute(
            get: fn () => collect(['apples', 'bananas']),
        );
    }

    public function foo()
    {
        return $this->bar->map(function ($x) {
            return new \stdClass($x);
        });
    }
}
```

You can use the same route that you already have to try out.

**Comment by driesvints** [comment]
@mpie I don't understand the bug. You're defining an accessor for a column that doesn't exists? That's not supported.

**Comment by mpie** [comment]
@driesvints so... you're telling me that computed values are not supported? xD

**Comment by driesvints** [comment]
@mpie ah sorry, my bad. I forgot for a sec that we indeed also support computed values:

<img width="723" alt="Screenshot 2022-01-07 at 12 33 41" src="https://user-images.githubusercontent.com/594614/148538367-8c8dc10e-438a-438e-945c-65334a6a2896.png">

**Comment by mpie** [comment]
@driesvints you had me worried for a second there hehe

**Comment by Jubeki** [comment]
@driesvints @taylorotwell 
If you have the following Model:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory;

    protected function bar(): Attribute
    {
        return new Attribute(
            get: fn () => collect(),
        );
    }

    public function getFooAttribute()
    {
        return collect();
    }
}

```

If you execute the following Code:
```php
$user = User::factory()->create();
dump($user);
$x = $user->bar;
$y = $user->foo;
dd($user);
```

You will get the following Dumps:
```
// dump
App\Model\User {
    // ...

    attributeCastCache: [ ]

    // ...
}

// dd
App\Model\User {
    // ...

    attributeCastCache: array:1 [
        "bar" => Illuminate\Support\Collection{...}
    ]

    // ...
}
```

So the issue seems to be that the new Attribute Accessor write into attributeCastCache while the old one does not.

You can test this with the following repository: https://github.com/Jubeki/laravel-bug-report-40268

**Comment by taylorotwell** [comment]
Fixed: https://github.com/laravel/framework/commit/29a6692fb0f0d14e5109ae5f02ed70065f10e966
