### ISSUE TITLE
Rules digits and digits_between don't work with fractional numbers

### ISSUE THREAD

**Issue by sera527** [laravel/framework#40264]
- Laravel Version: 5.2 and later

### Description:
I believe that the fix on this [issue](https://github.com/laravel/framework/issues/14647) should not have been approved. The rules now only supports integer values. And this does not match the description in the documentation: "The field under validation **must be numeric** and must have an exact length of value."

### Steps To Reproduce:

```php
<?php

$validator = Validator::make(
    ['fractional_value' => 1.2],
    ['fractional_value' => 'digits_between:1,10']
);
$validator->errors()->first(); // The fractional value must be between 1 and 10 digits.

**Comment by driesvints** [comment]
We've merged this and it'll be released next Tuesday. Thanks for reporting.
