### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by niyazialpay** [laravel/framework#40288]

**Comment by driesvints** [comment]
Please do not disclose security vulnerabilities publicly. Please refer to our security policy: https://github.com/laravel/framework/security/policy

**Comment by driesvints** [comment]
I couldn't reproduce any of that. Please send a report through the security policy which much more specific steps to reproduce.

**Comment by niyazialpay** [comment]
Sorry, I couldn't realize that. I have send email about  this subject.

**Comment by muhammadnan** [comment]
can security related issues be removed? @driesvints
