### ISSUE TITLE
SQL Injection vulnerability occurs when I use without any filtering for address variables

### ISSUE THREAD

**Issue by niyazialpay** [laravel/framework#40289]
- Laravel Version: 8.77.1
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Description:

SQL Injection vulnerability arises when querying the database with the Query Builder structure without any filtering for address variables in the Laravel routing structure. For example:

### Steps To Reproduce:

web.php

Route::get('/brands/category/{category_id}/{type?}', 'BrandsController@brandList');

SQL Injection vulnerability occurs when I use $category_id and $type variables in SQL query without any filtering.

SQL Injection payload:

GET /brands/category/-1'%20OR%203*2*1=6%20AND%20000316=000316%20--%20/url HTTP/1.1
X-Requested-With: XMLHttpRequest

Can't a structure be made that will automatically filter the address variables coming from the Laravel routing structure? It provides filtering by making special definitions as string or integer for the variables coming from the address in the Python Flask structure. I think something like this could work for Laravel as well. If you make an update on this topic, you will save many Laravel users who do not have special filtering for the address structure from the vulnerability.

**Comment by driesvints** [comment]
Stop opening these please.
