### ISSUE TITLE
#40119 broke how `dbal` array in `config/database.php` is handled.

### ISSUE THREAD

**Issue by canvural** [laravel/framework#40297]
- Laravel Version: 8.78.1
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8

### Description:

#40119 introduced an improvement for handling custom Doctrine types. But for some people it broke the test suites. (https://github.com/laravel/framework/pull/40119#issuecomment-1005854737 and https://github.com/laravel/framework/pull/40119#issuecomment-1006906061)

For sequential test runs issue happens when there is only the `dbal` array in `config/database.php` And the issue is gone when adding `DB::registerDoctrineType call` to `AppServiceProvider`. Which is not a good solution because it causes the application to make DB connection while the app is booting.

For parallel test runs issue happens in both cases.

### Steps To Reproduce:

[This](https://github.com/canvural/doctrine-type-bug) repo shows the bug.

**Comment by skollro** [comment]
@canvural Thank you for creating an issue out of our previous discussion!

> And the issue is gone when adding DB::registerDoctrineType call to AppServiceProvider.

This only works for sequential test runners. As soon as you run `php artisan test --parallel` both ways of custom DBAL type registration are broken.

**Comment by driesvints** [comment]
@bakerkretzmar @TomHAnderson if we can't find a solution right now it might be best that we revert the PR.

**Comment by bakerkretzmar** [comment]
@canvural thanks a lot for reproducing it in a repo, I'll dig into this right now. @driesvints agreed, I can do that later today if we can't figure this out.

**Comment by TomHAnderson** [comment]
I've been working with @bakerkretzmar all day.  I think his PR #40303 addresses 1) problems with running unit tests in series and 2) accounts for unit tests in parallel and makes concessions for them.

I'm not certain parallel testing is 100% because I've been unable to run such tests locally.  I don't feel reverting the #40119 is the right move.
