### ISSUE TITLE
Gte/Lte/Lt/Gt incorrectly treat strings as numeric?

### ISSUE THREAD

**Issue by sparxooo** [laravel/framework#40308]
- Laravel Version: 8.75.
- PHP Version: 8.1.1

### Description:
When validating strings using Gte/Gt/Lte/Lt, as per the Laravel docs, it should count characters in strings, as per the size validator.

When validating "password" using rule "gte:8" it will fail
When validating "8" using rule "gte:8" it will pass
When validating "7" using rule "gte:8" it will fail
When validating "9" using rule "gte:8" it will pass

Size works correctly: 

When validating "password" using rule "size:8" it will pass
When validating "8" using rule "size:8" it will fail

If i'm doing it wrong, I apologise!

### Steps To Reproduce:

Validate a string with lte/lt/gt/gte to match lengths

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sparxooo** [comment]
Hi driesvints,

Either the documentation is wrong, or there is a bug.

[Validation Rule GTE](https://laravel.com/docs/8.x/validation#rule-gte)

```
Rule GTE
The field under validation must be greater than or equal to the given field. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the size rule.
```

The problem is that it _does not_ evaluate it the same as the size rule. There is some more logic in the code before it uses the getSize function (and I believe part of the issue is that it checks the type of the parameter, which is always going to be a number, and so it never actually gets to calling getSize).

**Comment by sparxooo** [comment]
Furthermore to this issue, i've managed (finally! :) ) to set up PHP debugging, and i've stepped through the code:

I believe that Issue #33711 and #28174 have both contributed to this change in behaviour (and this was commented about in the latter!)

It immediately falls into the below, as $parameters[0] is 8: 

https://github.com/laravel/framework/blob/b0a2d855cdbec8638e9eb7fa9d433ceb84137a84/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1077-L1079

and then falls into this block, as obviously a string is not the same type as a number:

https://github.com/laravel/framework/blob/b0a2d855cdbec8638e9eb7fa9d433ceb84137a84/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1085-L1087


The docs should probably be changed to point out that you cannot use these operators (Gt/Gte/Lt/Lte) for string comparisons  (at the very least, i've not tested other results). I can't see what i'm doing grossly incorrectly from the docs.

**Comment by sparxooo** [comment]
See PR for final change, I was incorrect in my initial reasoning.
