### ISSUE TITLE
MakeListener Command overwrites existing class

### ISSUE THREAD

**Issue by stephanbouman** [laravel/framework#40315]
- Laravel Version: 8.78.1
- PHP Version: 8.0.8

### Description:
When running `php artisan make:listener MyEventListener`, the command overwrites my existing class. The Illuminate\Foundation\Console\ListenerMakeCommand class overwrites the  alreadyExists() method of  Illuminate\Console\GeneratorCommand and does a simple check if the classname (MyEventListener) exists with php's default class_exists(). This returns a false every time since we do not provide a fully qualified class name.

### Steps To Reproduce:
Run php artisan make:listener MyEventListener multiple times

**Comment by tkuijer** [comment]
Can confirm this also happens on php 8.0.13.
Appears to be fixed for the generating of events: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/EventMakeCommand.php#L36

**Comment by driesvints** [comment]
Let's see how the PR goes, thanks
