### ISSUE TITLE
Scheduled task running repeatedly one minute long in the minute they should run

### ISSUE THREAD

**Issue by derMart** [laravel/framework#40325]
- Laravel Version: 8.77.1
- PHP Version: 7.4.3
- Database Driver & Version: mysql / Server version: 5.5.5-10.6.4-MariaDB-1:10.6.4+maria~focal mariadb.org binary distribution
- Queue Driver: database
 
### Description:

I've added an artisan command to be scheduled every two minutes.
The command dispatches one job on the queue. Running the command using php artisan manually correctly only one job is executed on the queue.
Running php artisan schedule:run in a loop every second the following happens:
- In every even minute, the job runs repeatedly as often as possible, so everytime schedule:run is invoked and the job is not running, it seems that the job is dispatched, even if it sucessfully ran already in that minute.
- In every odd minute nothing happens 

### Steps To Reproduce:

1. Schedule a command in the console kernel using
```
$schedule->command('command:name')->everyTwoMinutes();
```

2. Run `php artisan schedule:run` every second.

### Expected Behaviour
I would expect the command / job to be executed only once every two minutes, instead of as often as possible every even minute.

**Comment by derMart** [comment]
same Behaviour also happens if I schedule the job directly using:
```
$schedule->job(new JobName)->everyTwoMinutes();
```

**Comment by derMart** [comment]
not using cron job, using a docker container which invokes php artisan schedule:run every second. But, that is actually not the problem here ... schedule:run is invoked correctly every second

**Comment by SjorsO** [comment]
The Laravel cron is made to run exactly once a minute. If you want to run a cron shorter than that maybe you can use this package: https://github.com/spatie/laravel-short-schedule

**Comment by derMart** [comment]
What is Laravel cron? The issue here is that if `php artisan schedule:run` is invoked it dispatches scheduled jobs again, which already were completed.

**Comment by derMart** [comment]
https://laravel.com/docs/8.x/scheduling#running-the-scheduler states:
```
The schedule:run Artisan command will evaluate all of your scheduled tasks and determine if they need to run based on the server's current time.
```
which is not the case here, as it reruns already completed tasks

**Comment by driesvints** [comment]
Thanks @SjorsO @Krisell

**Comment by derMart** [comment]
> From the docs: `The schedule:run Artisan command will evaluate all of your scheduled tasks and determine if they need to run based on the server's current time.` So if the current minute matches the scheduled minute, it fires.
> 
> There is no concept of "completed" for scheduled jobs as that status is not saved anywhere. However you can prevent overlapping: https://laravel.com/docs/8.x/scheduling#preventing-task-overlaps

prevent task overlap is currently also not working: https://github.com/laravel/framework/issues/37243
https://github.com/laravel/framework/discussions/37255
Why is that ticket even closed and send to discussion?

**Comment by derMart** [comment]
For schedule:run to be independent of the frequency and time it is invoked it is also not necessary to save the completed jobs. Only necessity is to save the last time it was executed. With that information all jobs which need to be fired could be executed.
