### ISSUE TITLE
Add to the phpdoc that count accepts an array too

### ISSUE THREAD

**Issue by williamdes** [laravel/framework#40337]
phpstan:
```
Parameter #1 $columns of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::count() expects string, array<int, string> given.
```
(to be fixed) count:
https://github.com/laravel/framework/blob/84ba139bba247592159cb471fc0c4c99b965d2b6/src/Illuminate/Database/Query/Builder.php#L2757

get:
https://github.com/laravel/framework/blob/84ba139bba247592159cb471fc0c4c99b965d2b6/src/Illuminate/Database/Query/Builder.php#L2367

My code
```php
            ->distinct()
            ->count([
                'my_table.col_1',
                'my_table.col_2',
            ]);
```

**Comment by driesvints** [comment]
Hey @williamdes. Can you please not ignore the issue template when filling out issues?

Also, there's not a bug here. No code is broken. So this issue tracker isn't the right place (see the issue templates when opening new issues). If you want to change anything here feel free to send in a PR.

**Comment by williamdes** [comment]
> Hey @williamdes. Can you please not ignore the issue template when filling out issues?
Also, there's not a bug here. No code is broken. So this issue tracker isn't the right place (see the issue templates when opening new issues). If you want to change anything here feel free to send in a PR.

Hey, I am very sorry for that. GitHub removed the template when I used the link "create an issue from" on the blame line..

Sure, I will send a PR ASAP

**Comment by driesvints** [comment]
> GitHub removed the template when I used the link "create an issue from" on the blame line

Ah that's good to know actually. I didn't know you could do that. What are the steps to reproduce that? Then I can forward it to GitHub.

**Comment by williamdes** [comment]
use one of my source links and follow this screenshot :)
It's a pain that it scrapes templates, this is not the first time I fall into this ..
![image](https://user-images.githubusercontent.com/7784660/148934308-5d8939f1-f42e-4191-8e52-db52e71d4aa5.png)

**Comment by driesvints** [comment]
Thanks @williamdes for letting me know 👍

**Comment by williamdes** [comment]
Hi @driesvints 
What branch should I push this change for it to be merged up ?

**Comment by driesvints** [comment]
@williamdes bug fixes need to be sent to 8.x, thanks
