### ISSUE TITLE
Passing the FQCN to make:seeder command produces unexpected output

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/framework#40338]
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version: 

### Description:

when I run a seeder command with additional path it produces the unexpected output.

### Steps To Reproduce:

In a fresh laravel app run the following command 

`php artisan make:seed PathOne/PathTwo/SeederClass`

This will create a file in `database_path('seeders/PathOne/PathTwo')` with following content

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PathOne/PathTwo/SeederClass extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }
}
```

**Comment by driesvints** [comment]
`class PathOne/PathTwo/SeederClass` is not valid PHP.

**Comment by driesvints** [comment]
I can reproduce this. I'll see what's up.

**Comment by driesvints** [comment]
It seems there's no support for this yet. Only for single classes. If you wish to have namespace support as well we're welcoming PR's. I might take a look at this myself eventually but for now we're welcoming PR's. Thanks
