### ISSUE TITLE
Artisan command make:policy generates invalid policy code with a non-default user provider configuration

### ISSUE THREAD

**Issue by slavicd** [laravel/framework#40345]
- Laravel Version: 8.78.1
- PHP Version: 7.4, 8.0

### Description:

`php artisan make:policy` will produce invalid output, similar to what's been reported [here](https://github.com/laravel/framework/issues/32647), [here](https://github.com/laravel/framework/issues/32397) and [here](https://github.com/laravel/framework/issues/21117) (missing user class) if a non-default `auth.providers.users` configuration is in place.

### Steps To Reproduce:

1. `composer create-project laravel/laravel`
2. Change the user provider configuration. E.G: 
```php
// config/auth.php
// ...
    'providers' => [
        'users' => [
            'driver' => 'database',
            'table' => 'users',
        ],
    ],
// ...
```
3. `php artisan make:policy CommentPolicy --model=Comment`

Note the generated code in Policies: it is missing the User class and is invalid. 

I realized this happens when the provider configuration is missing the `model` key, which was my case too (except I had a custom driver, and I never needed the `model` key).

### Expected behaviour

The `make:policy` command throws an error if it needs explicit user class configuration or otherwise inserts a default user class.

**Comment by hmennen90** [comment]
Just tested it with a new Laravel Project:

```
'providers' => [
        //'users' => [
        //    'driver' => 'eloquent',
        //    'model' => App\Models\User::class,
        //],

         'users' => [
             'driver' => 'database',
             'table' => 'users',
         ],
    ],
```

Output:
```

❯ php artisan make:policy CommentPolicy --model=Comment
Policy created successfully.
```

**Comment by slavicd** [comment]
@hmennen90 check the generated policy code.

**Comment by hmennen90** [comment]
The Target Models are in use Statements using App\Models Namespace in both cases: -m and --model

If no Model is specified, there is a blank Policy created

```
use App\Models\Comment;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;
```

**Comment by hmennen90** [comment]
hmm i try it on php 8.0 - i'm currently on 8.1.1

**Comment by hmennen90** [comment]
Results on PHP8.0 and PHP7.4 are same as at PHP8.1.1

Maybe anyone else can reproduce your issue?

**Comment by hmennen90** [comment]
@slavicd command back ;-) Can now confirm your issue also on PHP 8.1.1 - had the config cached...

Did you mean the following Output?

```
namespace App\Policies;

use App\Models\Comment;
use Illuminate\Auth\Access\HandlesAuthorization;
use ;

class CommentPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any models.
     *
     * @param  \  $
     * @return \Illuminate\Auth\Access\Response|bool
     */
    public function viewAny( $)
    {
        //
    }
```

**Comment by driesvints** [comment]
You're changing the guard to one that doesn't have a model. Then it's normal that you'll get an error. A policy always requires a model.

**Comment by slavicd** [comment]
@driesvints the command is generating invalid code. The fact that I have a custom user provider is not documented anywhere as related to this, and even if it were, spitting out an error or warning or an explanatory message all seem more appropriate than generating a half-stub that is really hard to decode.

**Comment by driesvints** [comment]
@slavicd ah I see what you mean. What would need to happen here is that the `if (! $model) {` throws an exception I think instead of the stub. Because a model is clearly required here.

**Comment by slavicd** [comment]
Precisely. I'll try to write a PR now.
