### ISSUE TITLE
Automatically detect Markdown mail indentation

### ISSUE THREAD

**Issue by bram-pkg** [laravel/framework#40356]
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0

### Description:

When formatting a file according to the same logic other views (i.e. indenting after a `@component` tag), the Markdown is rendered as a code block. I think it would be more user friendly if the Markdown mailer automatically detects the minimum indent level, and strips those whitespaces. 

### Steps To Reproduce:

Create Markdown mailable with content:

```md
@component('mail::message')
    # Welcome
    
    Body of email
    
    @component('mail::button', ['url' => $url])
        Open PDF
    @endcomponent
    
    With kind regards,
    
    {{ config('app.name') }}
@endcomponent

```

**Comment by driesvints** [comment]
This seems like a feature request and this issue tracker isn't the right place for it. I also believe this would be too much of a breaking change but you're always free to try a PR. Thanks

**Comment by bram-pkg** [comment]
My bad, I will open a discussion. It would indeed be a breaking change.

**Comment by hichemfantar** [comment]
Same thing happens when formatting is applied to the email file generated by `php artisan vendor:publish --tag=laravel-notifications` related to #43395
