### ISSUE TITLE
Extending the translator to provide additional replacements results in an error when validation attempts to format a message.

### ISSUE THREAD

**Issue by tylerherrin** [laravel/framework#40377]
- Laravel Version: 8.67.0
- PHP Version: 7.4.21
- Database Driver & Version: Mysql 5.7.22

### Description:
After the release of  `laravel/framework:8.67.0` `Translator::makeReplacements()` has been changed to use the `strtr` function instead of `str_replace`. [strtr](https://www.php.net/manual/en/function.strtr.php) **_only_** accepts a single string for the first argument, whereas [str_replace](https://www.php.net/manual/en/function.str-replace.php) would accept a single string or an array of strings. This is usually fine but...

When Laravel performs validation and validation fails it attempts to format a message based on the rule that failed. While searching to see if any custom messages exist, and none do, it eventually makes an attempt with the key `validation.custom`, but that key returns an array of strings. This is seemingly intentional behavior as part of [wildcard custom messages](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Validation/Concerns/FormatsMessages.php#L138).

This isn't an issue when using the base laravel `Translator::get()` since `validation.custom` causes it to [return the "line"](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Translation/Translator.php#L127) (it's an array...) and never call `makeReplacements()`.

But extending Laravel's translator by taking the line returned from the base translator and making an additional call to `makeReplacements()` for further replacement results in an error when the key `validation.custom` is attempted because `$line` is an array and `strtr` cannot handle that.

### Steps To Reproduce:

Extend `Translator::get()` and take the line returned from the parent method and feed it back into `makeReplacements()`. Have validation fail for a rule where there is no custom validation message so Laravel falls into checking for wildcard custom messages. `strtr` will error out inside of `makeReplacements()` when the key `validation.custom` is attempted.
```
public function get($key, array $replace = [], $locale = null, $fallback = true)
{
    $line = parent::get($key, $replace, $locale, $fallback);
    
    return $this->makeReplacements($line, $this->getDynamicReplacements());
}
```

**Comment by driesvints** [comment]
Since you're extending Laravel's translator here and adjusting the intended behaviour, there's nothing much we can do I'm afraid... 

Is it also broken for you on the latest Laravel version? I think I remember we did a fix in a later version.

**Comment by derekmd** [comment]
Your custom translator probably needs to implement an alternate `makeReplacements()` method or copy this `Translator@getLine()` snippet into `get()`:

https://github.com/laravel/framework/blob/b3329fad6809d69679075bee42b14d685e189217/src/Illuminate/Translation/Translator.php#L194-L202

Before the v8.67.0 change was made, [I suggested](https://github.com/laravel/framework/issues/39258#issuecomment-947191238) it may need to target 9.x for situations like this but the replacements bug was deemed important enough to fix it immediately in the 8.x branch.

FYI, the `makeReplacements()` method always had this docblock:
https://github.com/laravel/framework/blob/b3329fad6809d69679075bee42b14d685e189217/src/Illuminate/Translation/Translator.php#L208

That it previously supported an `array $line` argument was happy coincidence. Unless behavior is covered on laravel.com/docs or protected in the framework's test suite, it's best to cover extending-behavior in your application/package test suite in case minor versions modify framework internals.

**Comment by tylerherrin** [comment]
Yes, it's broken in the most recent version as well. I just tried `8.79.0` since it was released yesterday, still no such luck.

I was afraid we were extending the translator in an odd, unintended, way. Thanks for the info! I'll try derekmd's suggestions, I think it's clear at this point the problem is on our side.

**Comment by driesvints** [comment]
Thanks @derekmd 

I'm very sorry @tylerherrin but since we never intended the validator to work this way I'm afraid there's nothing we can do. Sorry this hit you.
