### ISSUE TITLE
SQLite Issue when dropping columns in migrations

### ISSUE THREAD

**Issue by awjudd** [laravel/framework#40379]
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version: Sqlite 3.36.0

### Description:
When php artisan migrate:refresh is called (and this script already exists), you receive the following error.

**Preconditions:**
1 - Migration has already been run (i.e. the column exists)
2 - You are using "sqlite" as the database driver with a file as the target.

### Steps To Reproduce:
1 - Set up a brand new Laravel application
2 - Change the `.env` so that you are set to point to an actual SQLite database:
```
DB_CONNECTION=sqlite
DB_DATABASE=./database/database.sqlite
```
3 - Create the database file:
```
touch ./database/database.sqlite
```
4 - Create a new migration with the following:
```php
/**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->string('sample')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('sample');
        });
    }
```
5 - Run `php artisan migrate` to migrate the data
6 - Run `php artisan migrate:refresh` to clear and recreate the database.

**Expected**: 
The database is re-created.

**Actual**:
```
➜  test git:(main) ✗ php artisan migrate:refresh
Rolling back: 2022_01_11_221731_add_sample_column_to_users_table

   Error 

  Class "Doctrine\DBAL\Driver\AbstractSQLiteDriver" not found

  at vendor/laravel/framework/src/Illuminate/Database/PDO/SQLiteDriver.php:8
      4▕ 
      5▕ use Doctrine\DBAL\Driver\AbstractSQLiteDriver;
      6▕ use Illuminate\Database\PDO\Concerns\ConnectsToDatabase;
      7▕ 
  ➜   8▕ class SQLiteDriver extends AbstractSQLiteDriver
      9▕ {
     10▕     use ConnectsToDatabase;
     11▕ }
     12▕ 

      +11 vendor frames 
  12  database/migrations/2022_01_11_221731_add_sample_column_to_users_table.php:30
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +34 vendor frames 
  47  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Please refer to the below commit for an example.

https://github.com/awjudd/laravel-sqlite-drop-column/commit/3076a97e1e64d9a5b67428a68a6151b129848ba6#commitcomment-63655326

**Comment by awjudd** [comment]
Please Note: This works perfectly for mysql.

**Comment by driesvints** [comment]
You need the `doctrine/dbal` package: https://laravel.com/docs/8.x/migrations#modifying-columns

<img width="759" alt="Screenshot 2022-01-13 at 10 20 52" src="https://user-images.githubusercontent.com/594614/149301811-7e830cf2-4df5-432d-ad17-81a07e6c6262.png">
