### ISSUE TITLE
Basic (not backed) native Enums are not supported in casting or validation

### ISSUE THREAD

**Issue by chojnicki** [laravel/framework#40380]
- Laravel Version: 8.78.0
- PHP Version: 8.1
- Database Driver & Version: Mysql 8.0.27

### Description:

Backed enums are working just fine, like
```
enum Demo: int
{
    case AAA = 1;
    case BBB = 2;
    case CCC = 3;
}
```

or

```
enum Demo: string
{
    case AAA = 'AAA';
    case BBB = 'BBB';
    case CCC = 'CCC';
}
```

In my case I need to use strings, but second option is repetitive and easy for typo in long lists.

Simple (not backed) enum are simpler and suitable option:

```
enum Demo
{
    case AAA;
    case BBB;
    case CCC;
}
```

But based on changes in #39315 and #39608 it uses `from()` method on Enum to find value, which does not exist on non-backed enum.

`Call to undefined method App\\Enums\\Demo::from()`

Is there any reason for that? Is it on purpose or bug? Sure that I can just give up on enums and use strings, but non-backend enums are also helpful. In my case I want to create enum in Lighthouse to pass it directly to GraphQL schema. It's good practice to use same enum definition in both PHP and graphql schema, to avoid bugs, but currently it's not possible with Laravel/Lumen and non-backed enums.

For tests purposes I changed some lines here
_illuminate/database/Eloquent/Concerns/HasAttributes.php_
```
protected function getEnumCastableAttributeValue($key, $value)
{
    if (is_null($value)) {
        return;
    }

    $castType = $this->getCasts()[$key];

    if ($value instanceof $castType) {
        return $value;
    }

    // HERE
    return $castType::cases()[array_search($value, array_column($castType::cases(), 'name'))];
    // return $castType::from($value);
}
```

Sure it's just quick and ugly fix, code could by nicer and this will broke backed enums, but it worked just fine for my case. 

But problem will maintain also in other places, like validation:

_Illuminate\Validation\Rules\Enum_
```
public function passes($attribute, $value)
{
    if (is_null($value) || ! function_exists('enum_exists') || ! enum_exists($this->type) || ! method_exists($this->type, 'tryFrom')) {
        return false;
    }

    return ! is_null($this->type::tryFrom($value));
}
```

Validation uses `tryFrom`, so same problem.

I can make this on app Level by making Trait (and use it in every enum file) that will mimic `::tryFrom()` and `::from`, but trying to reproduce PHP methods feels to much like hacking for me...

So to summary, shouldn't this be supported by Laravel itself? 
I really do not see any good point of making enum like
`case DEMO = 'DEMO';`
or
`case DEMO = 'demo';`

Thanks for reading :)

**Comment by driesvints** [comment]
> Laravel Version: 8.3.1

This Laravel version doesn't supports Enums. Please update Laravel and try again. If the issue persists please try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by chojnicki** [comment]
@driesvints Like I said, backed enums are working just fine. I simply typed wrong version in this Issue, my bad. I also showed source code from `illuminate/database` which is coming from new versions that supposed to support Enums.

So please reopen issue since fixing by upgrade does not apply here ;)

**Comment by driesvints** [comment]
Hey @chojnicki. This seems like a feature request to us and we're open to PR's if you want to send one in. Thanks

**Comment by chojnicki** [comment]
@driesvints Reproduction is pretty straight forward, same as in issue. Just trying to cast enum, like described in Laravel documentation.

_app/Enums/DemoEnum.php_
```
<?php

namespace App\Enums;

enum DemoEnum
{
    case A;
    case B;
    case C;
}
```
_app/Models/Demo.php_
```
<?php

namespace App\Models;

use App\Enums\DemoEnum;
use Illuminate\Database\Eloquent\Model;

class Demo extends Model
{
    protected $casts = [
        'demo' => DemoEnum:class,
    ];
}

```


Now trying to accessing this attribute

`$demoModel->demo; // enum supposed to be cased`

will lead to 

`Call to undefined method App\\Enums\\Demo::from()`

Similar thing with validation, but there will be error about `tryFrom`.


But if I change my enum to backed one (like described in first post), everything works fine.

Like I said, everything is caused by relying on `from()` and `tryFrom()` that are not available in PHP for basic enums, just backed ones.

So I do not feel like it's really feature request, because enums supposed to be already supported, but they are not fully. Again, in Laravel documentation, PRs, Laravel news etc everywhere it stays that Laravel supports enums, but that's not 100% true, that's just 66% true because there are three types of enums: basic, backed strings and backed integers, while Laravel works with last two ;) Hope I described this well enough.

Or maybe I'm missing something and it supposed to works with basic as well (even that I do not see this in illuminate code)?

**Comment by driesvints** [comment]
I'm sorry but I'm going to leave it at this. Feel free to PR something if you really believe things can improve.

**Comment by chojnicki** [comment]
@driesvints thanks for fast replies. Sorry to hear that but really no any explanation just "leave at it is" (meaning broken)? 
Closing issues without resolving them is just like swiping under carped :( I get that this is open source project, and I know that I or someone else can try to make PR, but this does not mean it is resolved in any way. Also less people will be willing to do PR's to issue that's is closed and forgotten by that. Any issue in any repository can be resolved by "do a PR" and close, but what's the point of issues then? My comment is offtopic, but I spend a lot of time trying to debug that and to write that issue with as much info I could to help address issue. All for nothing, just so it can be closed to meet some `Issues (0)` goal by maintainers? Well, I can just hope that it will be fixed in future, maybe if more people will have similar problem. Anyway, have a nice day :)

**Comment by themsaid** [comment]
@chojnicki only BackedEnum is supported at the moment. Feel free to open a PR to introduce support to regular Enums.

Thanks.
