### ISSUE TITLE
Why is Str::contains() not updating

### ISSUE THREAD

**Issue by CleisonPaiva** [laravel/framework#40391]
- Laravel Version: ^8.79.0
- PHP Version: ^ 8.0
- Database Driver & Version: PostgreSQL 11.2

### Description:
I updated my project to use the improvement made in Str::contains(), but even after the update the method remains in the old format

Before (even after updating my method did not change):
```
public static function contains($haystack, $needles)
    {
        foreach ((array) $needles as $needle) {
            if ($needle !== '' && mb_strpos($haystack, $needle) !== false) {
                return true;
            }
        }

        return false;
    }
```

Later (should have updated for this):

```
 public static function contains($haystack, $needles, $ignoreCase = false)
    {
        if ($ignoreCase) {
            $haystack = mb_strtolower($haystack);
            $needles = array_map('mb_strtolower', (array) $needles);
        }

        foreach ((array) $needles as $needle) {
            if ($needle !== '' && str_contains($haystack, $needle)) {
                return true;
            }
        }

        return false;
    }
```

### Steps To Reproduce:

`composer install`

`composer update`

**Comment by driesvints** [comment]
These changes are on Laravel 9 which hasn't been released yet.

**Comment by CleisonPaiva** [comment]
Is there any release date?

**Comment by driesvints** [comment]
Tuesday January 25: https://laravel.com/docs/8.x/releases#support-policy
