### ISSUE TITLE
[8.x] Laravel responds with empty error message when no route matches

### ISSUE THREAD

**Issue by axlon** [laravel/framework#40407]
- Laravel Version: 8.78.1
- PHP Version: 8.0.10
- Database Driver & Version: n/a

### Description:
Currently Laravel responds with an empty JSON response when a request expecting JSON is made against an endpoint that does not match a route.

Example:
```json
{
    "message": ""
}
```

This is because an exception is thrown without a message here https://github.com/laravel/framework/blob/25aa82ed9dcda14cb91e047a5118692e7502ea0f/src/Illuminate/Routing/AbstractRouteCollection.php#L43

Then, when the exception handler converts the exception to JSON, it will use the exception's empty message for the response because it is an HTTP exception.
 https://github.com/laravel/framework/blob/25aa82ed9dcda14cb91e047a5118692e7502ea0f/src/Illuminate/Foundation/Exceptions/Handler.php#L668

A previous attempt to fix this issue in #39893 was closed, so I decided to create an issue first before I created a pull request. My proposed fix would be to add a simple message such as `Not Found` to the exception to fix the issue. Another option could be to automatically have the handler fall back to HTTP status texts when receiving a HTTP exception without a message, though this may have unintended side-effects for people relying on current behaviour

### Steps To Reproduce:

- Call a Laravel application via cURL, Postman or something similar, hitting a URL that is not defined on the application

**Comment by axlon** [comment]
@driesvints the exception handler specifically has logic for pulling the exception message out of a given HTTP exception when its preparing a JSON response, so this explanation doesn't really hold up because it clearly was intended to work this way. Every other exception not resulting in a HTTP 500 status code also has a message associated (e.g. ValidationException, AuthenticationException).

Even within the 404 responses this isn't consistent, because a ModelNotFoundException will trigger a 404 response with a message.

**Comment by driesvints** [comment]
@axlon you can always re-try a PR. Try building a really good case in your description.
