### ISSUE TITLE
[8.x] escapeWhenCastingToString Breaks Collection items when casting a Collection to an Array

### ISSUE THREAD

**Issue by adrianpaiva1** [laravel/framework#40420]
- Laravel Version: 8.7.9
- PHP Version: 8.0.7
- Database Driver & Version: MySQL 8.20

### Description:

When casting a Collection to an array, without using toArray() or all(). The Collection no longer simply returns an array of the items, but includes also includes 'escapeWhenCastingToString' => false as  avalue. This is an issue when using type hinting expecting an array but passing a Collection. 

This was not the behaviour previously on Laravel 8.40.

### Steps To Reproduce:

`dd((array) collect(["Laravel", "Github", "Google"]));`

returns 

![image](https://user-images.githubusercontent.com/19557611/149576584-04484f2f-801e-4625-b80b-880bbbabd8ed.png)

instead of 

![image](https://user-images.githubusercontent.com/19557611/149576651-a3ecf995-80dd-46fb-99d4-050c75478ad0.png)

**Comment by orange-alien** [comment]
Maybe, it seems PHP Language specification.

### Converting to array 
https://www.php.net/manual/en/language.types.array.php#language.types.array.casting

**Comment by sajjadgol** [comment]
Convert Illuminate\Support\Collection to array !!!
use below code 
` dd ( collect(["Laravel", "Github", "Google"])->toArray()) `

**Comment by driesvints** [comment]
I don't get the "instead of" on any Laravel 8 version (even older ones). The only thing that has changed afaik is that `escapeWhenCastingToString` was added.

**Comment by c3r0** [comment]
yet another reason to kick all frameworks to the curb.
