### ISSUE TITLE
Delete Me

### ISSUE THREAD

**Issue by liamh101** [laravel/framework#40423]

**Comment by Jubeki** [comment]
Please don't disclose security-related issues publicly:
For Reporting use the Security Policy: https://github.com/laravel/framework/security/policy
And write an email to taylor@laravel.com

@taylorotwell @driesvints

**Comment by liamh101** [comment]
Done, please delete this issue.

**Comment by Jubeki** [comment]
That is not possible for me as I am no maintainer of the project.
Can you please edit your issue and just leave the description it empty?
Please also change the title to "Issue" and then you can close it.
