### ISSUE TITLE
(yes/no) accepted `y` as correct answer in artisan migration

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#40439]
- Laravel Version: 8.77.1
- PHP Version: 8
- Database Driver & Version: PosgreSQL

### Description:

![image](https://user-images.githubusercontent.com/53290883/149662731-069184d9-1b42-4c8f-b2c0-ad285c27d2f3.png)

Is it intentional ? I typed `y` instead of 'yes' or 'no' and it run the migration... (in phpstorm terminal)

**Comment by humaneguy** [comment]
Yeah. It covers both cases. It is assumed "y" stands for "yes" and "n" for "no". Pretty nifty, you see?

**Comment by bernardwiesner** [comment]
it is common behavior on command line when prompted for answers to just reply with `y`, you can try it with other tools such as yum, apk, rm, etc.

**Comment by driesvints** [comment]
Thanks @humaneguy @bernardwiesner
