### ISSUE TITLE
Rate Limiter cache not clearing with php artisan cache:clear

### ISSUE THREAD

**Issue by atlasmercan** [laravel/framework#40447]
hi guys,

i made an api and set rate limiting for a link groups

```php
RateLimiter::for('register', function (Request $request) {
  return Limit::perMinute(40)->perHour(1000)->by($request->ip());
});
```

after 40 requests i'm getting 429 too many request exception so it is all ok but exception continues even though i clear it with php artisan cache:clear  ... 

i do clear it in redis by flushall but when i call any register api link i'm getting 429 exception again and again and again  ...

where is the problem ?

i'm using laravel 8.0 with sail ... ( win10 - ubuntu 20.04 )

Why does it come back after i delete it? I'm about to go crazy

**Comment by bernardwiesner** [comment]
what do you have set as `limiter` ?

https://laravel.com/docs/8.x/rate-limiting#cache-configuration

**Comment by atlasmercan** [comment]
i found my fault ... 

i added an if else so if my app running on test configureRateLimiting methods run empty so it caused set maxAttemps to 0 and it means every request max attempts not increment. i change the if else like below

```php
RateLimiter::for('api', function (Request $request) {
  return $this->appIsTest() ? Limit::none() : Limit::perMinute(40)->by($request->ip());
});
```

than it is done ...

it means if you want use the ratelimiter as unlimited don't call it emtpy, call Limit::none() , right ?
