### ISSUE TITLE
[8.x] Collection undot() children are array instead of Collection

### ISSUE THREAD

**Issue by TivoSoho** [laravel/framework#40469]
- Laravel Version: 8.74.
- PHP Version: 7.4.27

### Description:
When you use "undot" on a Collection, only the returned item is Collection, but not the children

### Steps To Reproduce:
1. Call undot on a "dot notation" keyed (Eloquent) Collection
2. Result is an (Eloquent) Collection of arrays

### Expected result:
Collection holding Collections

### Why is it a problem
1. You cannot chain or transform "lower level" items - it breaks after first level, you would have to manually traverse it (with whatever function you are using) to convert the children to Collection, then traveling that child's children etc. In the case of Eloquent Collection it is a bad mix of an Eloquent Collection having arrays as children until the final item is the original Eloquent Model.
2. This is also unexpected behavior for a Collection method as other methods return Collection of Collection, e.g. groupBy.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by TivoSoho** [comment]
I dot not have a usage question as it is very clear how it works. However I find how it works to be a bug as it has an unexpected behavior. Yes, I can see that undot is simply a wrapper for Arr::dot.  I find it incorrect - if you were to incorporate a Collection method, it should act accordingly. Otherwise one could simply do the same lines manually without the Collection's undot method.
