### ISSUE TITLE
[6.*] min-Validator throws 'mb_strlen() expects parameter 1 to be string, object given' error

### ISSUE THREAD

**Issue by sebastiandeppisch** [laravel/framework#40462]
- Laravel Version: v6.18.13
- PHP Version: 7.4.24
- Database Driver & Version: --- 

### Description:

When I'm using the 'min' Validator with an object as data the following error is thrown: 
`[2022-01-17 21:03:16] testing.ERROR: mb_strlen() expects parameter 1 to be string, object given {"exception":"[object] (ErrorException(code: 0): mb_strlen() expects parameter 1 to be string, object given at /path/to/project/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:1839)`

### Steps To Reproduce:

```
//route & controller
Route::post("test", function (Request $request) {
    $request->validate([
        'some_field' => ['required', 'string', 'min:30'],
    ]);
    return "some data";
});
```

```
//feature test 
public function testExample()
 {
      $data = new stdClass();
      $data->someKey = 42;
      $data->someOtherKey = false;

      $response = $this->post('/api/test', [
          'some_field' => $data
      ]);

      $response->assertSuccessful();
    }
```

**Comment by sebastiandeppisch** [comment]
The responsible code from ValidateAttributes.php
To fix it, the size of an object (in case of validation) must be defined 
```
protected function getSize($attribute, $value)
    {
        $hasNumeric = $this->hasRule($attribute, $this->numericRules);

        // This method will determine if the attribute is a number, string, or file and
        // return the proper size accordingly. If it is a number, then number itself
        // is the size. If it is a file, we take kilobytes, and for a string the
        // entire length of the string will be considered the attribute size.
        if (is_numeric($value) && $hasNumeric) {
            return $value;
        } elseif (is_array($value)) {
            return count($value);
        } elseif ($value instanceof File) {
            return $value->getSize() / 1024;
        }

        return mb_strlen($value);
    }
```
How should the size of an object be defined?
- count of attribues (like for array)
- the length of a string-serialization

**Comment by driesvints** [comment]
Objects aren't allowed with this rule.
