### ISSUE TITLE
selectRaw and addSelect(DB::Raw)) are wiping all existing selects.

### ISSUE THREAD

**Issue by mikemike** [laravel/framework#40463]
- Laravel Version: 8.74.0
- PHP Version: 7.4.19
- Database Driver & Version: MySQL 5.7.33

### Description:
Adding a `selectRaw` or an `addSelect(DB::Raw())` in a scope wipes all existing attributes.

### Steps To Reproduce:

1. Add the following to a model:

```
public function scopeSearchLatLng($query, array $latlngArr)
{
    return $query->addSelect(
        DB::Raw("
            ST_Distance_Sphere(
                point(longitude, latitude),
                point(?, ?)
            ) * .000621371192 AS distance
        ")
    )
    ->addBinding($latlngArr[1], 'select')
    ->addBinding($latlngArr[0], 'select')
    ->orderBy('distance', 'asc');
}
```

2. Run the following in a controller:

```
$modelsFull = Model::all();
$modelsTruncated = Model::searchLatLng([53.784696, 2.299806])->get();

dd($modelsFull, $modelsTruncated);
```

The expected result would be two collections with the same number of items, with the second having an extra item of `distance` (coming from the scope).

The actual result is two collections of the same number of items, the first collection has all expected attributes, the second has just a single attribute, 'distance'.

My workaround is to add `, table.*` to the `DB::Raw` in the scope, but that's obviously not ideal.

**Comment by driesvints** [comment]
I think this is expected. I don't think you should use `->addBinding` there and instead you should rely on `->selectRaw` to pass the bindings:

```php
return $query->selectRaw("
    ST_Distance_Sphere(
        point(longitude, latitude),
        point(?, ?)
    ) * .000621371192 AS distance
", [$latlngArr[1], $latlngArr[0]])
->orderBy('distance', 'asc');
```

**Comment by mikemike** [comment]
The same thing happens when using `selectRaw` with bindings

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by BrandonSurowiec** [comment]
@mikemike Add this to the top of your scope:

```

        // Select all only if needed
        if (is_null($query->getQuery()->columns)) {
            $query->select($this->qualifyColumn('*'));
        }
```
