### ISSUE TITLE
Str::headline does not work with umlauts

### ISSUE THREAD

**Issue by cemrich** [laravel/framework#40468]
- Laravel Version: 8.78.1
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:
`Illuminate\Support\Str::headline` does not support umlauts (like ö,ä,ü). There are two related bugs I can see:
1. Uppercase umlauts are not detected as uppercase.
2. Umlauts at the beginning of a word do not get capitalized.

#### Umlauts at the beginning of a word do not get capitalized

    public function test_make_umlauts_uppercase() {
        $input = 'ärmere-öffentliche-überraschungen-sind-öde';
        $expected = 'Ärmere Öffentliche Überraschungen Sind Öde';
        $output = Str::headline($input);
        $this->assertEquals($expected, $output);
    }

Yields the output: 

    Failed asserting that two strings are equal.
    Expected :'Ärmere Öffentliche Überraschungen Sind Öde'
    Actual   :'ärmereöffentlicheüberraschungen Sindöde'

#### Uppercase umlauts are not detected as uppercase

    public function test_detect_uppercase_umlauts() {
        $input = 'sindÖdeUndSo';
        $expected = 'Sind Öde Und So';
        $output = Str::headline($input);
        $this->assertEquals($expected, $output);
    }

Yields the output: 

    Failed asserting that two strings are equal.
    Expected :'Sind Öde Und So'
    Actual   :'SindÖde Und So'

**Comment by foremtehan** [comment]
@stevebauman

**Comment by driesvints** [comment]
We'd welcome PR's for this, thank you.

**Comment by stevebauman** [comment]
This is because `ucwords()` doesn't handle unicode characters:

```php
// ärmere öffentliche
echo ucwords('ärmere öffentliche');
```

This means `Str::studly()` or anything relying on that method also does not work with unicode characters.

We'll have to be crafty and use `mb_convert_case()`. I'll see if I can come up with something 👍
