### ISSUE TITLE
[8.x] Custom channels for model broadcasting are ignored

### ISSUE THREAD

**Issue by wokes** [laravel/framework#40478]
- Laravel Version: 8.80.0
- PHP Version: 7.4.24
- Database Driver & Version: not pertinent

### Description:
Model broadcasting seemed like a very convenient way for real-time updates on the frontend, so I gave it a try.
Ran into an issue when I wanted to change the channel the events are broadcasted on.
As per docs, I added `BroadcastsEvents` trait on the model along with
```
    public function broadcastOn($event)
    {
        return [new PrivateChannel('foo-bar-baz')];
    }
```

This did not yield expected results, as the events kept broadcasting only on the default model channel.

I dug around for a bit and the culprit seems to be in https://github.com/laravel/framework/blob/8940ff3c9c643f8abcca026a6341fdfcfc83e983/src/Illuminate/Database/Eloquent/BroadcastsEvents.php#L112

We check `if (! empty($this->broadcastOn($event)) || ! empty($channels)) {` to ensure that there are channels to broadcast on, however:
`return broadcast($instance->onChannels(Arr::wrap($channels)));`
we completely ignore the channels we defined in `broadcastOn`. It's only broadcasted on `$channels`.

Changing https://github.com/laravel/framework/blob/ac6fc32c2933d5868a2c0d2aea4af9405d710378/src/Illuminate/Database/Eloquent/BroadcastsEvents.php#L119
to `return broadcast($instance->onChannels(array_merge(Arr::wrap($channels), $this->broadcastOn($event))));` rectifies the issue.

### Steps To Reproduce:

1. Set up model broadcasting
2. Add `broadcastOn` to the model definition as shown in the description above
3. Create/update/delete the model
4. Model will be sent on the default auto-generated channel instead of the provided one

**Comment by driesvints** [comment]
See the closed PR by Taylor.
