### ISSUE TITLE
[8.74.0] Factory sequence not reset for sub factories using has

### ISSUE THREAD

**Issue by DeanWhitehouse** [laravel/framework#40482]
- Laravel Version: 8.74.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0

### Description:
Reading the documentation on sequences and relationships i'd have expected the below code to reset the `$sequence->index` within the report factory after each user was created, however it persists for all users.

The intended effect should be each user has 90 days of reports from now, however the increment keeps growing meaning in the end the last user reports end 900 days ago (not 90).

### Steps To Reproduce:
In my example below it means that the parent counts correct from 1-10 but the child counts from 1-900 rather than to 90 and reset. This seems like a bug to me, or at least behaviour that needs documenting as it’s unexpected
```
<?php
\App\Models\Recipient::factory(10)
            ->sequence(fn ($sequence) => [
                'player_id' => $playerIds[$sequence->index]
            ])
            ->has(
                \App\Models\Report::factory(90)
                    ->sequence(fn ($sequence) => [
                        'created_at' => now()->subDay($sequence->index)
                    ])
                    ->state(fn (array $attributes, \App\Models\Recipient $recipient) => [
                        'player_id' => $recipient->player_id,
                        'user_id' => $recipient->user_id
                    ])
            )
            ->create([
                'user_id' => 34
            ]);
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by DeanWhitehouse** [comment]
Hey @driesvints,

This has been raised on Slack and Discord, another user has replicated the issue on Discord and it does appear to be a bug. What more do you need from me to flag it as a bug? I'm a bit confused as to what more I can provide other than a working example of the bug

Cheers

**Comment by driesvints** [comment]
Please link to the conversations.

**Comment by DeanWhitehouse** [comment]
@driesvints https://larachat.slack.com/archives/C03ALD0QD/p1642685764025100?thread_ts=1642496273.006400&cid=C03ALD0QD

**Comment by markandrewkato** [comment]
Hi @DeanWhitehouse, did you got a chance to find a fix for this? I'm also having the same issue.

**Comment by DeanWhitehouse** [comment]
> Hi @DeanWhitehouse, did you got a chance to find a fix for this? I'm also having the same issue.

Unfortunately not yet, and with it being marked as closed on here I doubt anyone else will be looking into it - send me a direct message if you wish to try collaborate on resolving it.

A quick fix is to create your own loop rather than use a sequence, not ideal though

**Comment by markandrewkato** [comment]
@DeanWhitehouse you're right, i think this won't be resolved anytime soon or it might not be an issue for them. anyway, I'll let you know if I can make some time for this but I'm currently stuffed on work right now so I'll just create my own loop like you said. thanks!
