### ISSUE TITLE
[8.x] Parallel testing databases are never created when using doctrine/dbal

### ISSUE THREAD

**Issue by koenhoeijmakers** [laravel/framework#40488]
- Laravel Version: 8.77.1
- PHP Version: PHP 8.0.14
- Database Driver & Version: mysql 8.0.27

### Description:
Laravel's parallel testing feature creates testing databases when an `Illuminate\Database\QueryException` is thrown after checking if the database is reachable, this seems to only work without `doctrine/dbal` as said package overrides the default PDO Connection and changes the Exception being thrown.

```
protected function createPdoConnection($dsn, $username, $password, $options)
{
    if (class_exists(PDOConnection::class) && ! $this->isPersistentConnection($options)) {
        return new PDOConnection($dsn, $username, $password, $options);
    }

    return new PDO($dsn, $username, $password, $options);
}
```

### Steps To Reproduce:
Require the `doctrine/dbal` package, then try to run parallel tests.

### Possible fix:
Exception being caught should also include the Doctrine/DBAL exception, this does differ per package version (2.x / 3.x) and i'd like someone else to have a look at it before creating a fix.

**Comment by nunomaduro** [comment]
I've just created a fresh Laravel project, required `doctrine/dbal`, and included the `RefreshDatabase` trait on the feature test. The result was a database being created for the feature test, as expected.

Can you create a new issue, including a link for a Laravel project on GitHub, so I can reproduce the issue locally? Feel free to add instructions on the readme of the project.

**Comment by koenhoeijmakers** [comment]
I don't seem to be able to reproduce this on a fresh install, but it somehow does throw a `PDOException` in our project instead of the excepted `QueryException`, super odd.

**Comment by koenhoeijmakers** [comment]
Found the culprate, it was a package for spatial functions that was overriding the MysqlConnection and therefore throwing the incorrect exception.
