### ISSUE TITLE
Y-m-d Date Validation failed

### ISSUE THREAD

**Issue by TheArKaID** [laravel/framework#40485]
- Laravel Version: 8.74.0
- PHP Version: 8.0.14
- Database Driver & Version: 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64

### Description:
Laravel date Validation failed to validate `Mon Dec 08 1997 16:14:36` as `Y-m-d` format

### Steps To Reproduce:

1. Set Request `rule` validation for `birth_date` with `'birth_date' => 'required|date:Y-m-d'`,
2. Send Postman POST Request with `x-www-form-urlencoded` and `birth_date` with value `Mon Dec 08 1997 16:14:36`,
3. `PDOException` thrown:
```
PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: 'Mon Dec 08 1997 16:14:36' for column
'birth_date' at row 1 in
```

### Expected
```
"errors": {
   "birth_date": [
        "The birth date is not a valid date."
    ]
}
```

**Comment by dinhquochan** [comment]
Use `date_format:Y-m-d` not `date`

**Comment by TheArKaID** [comment]
@dinhquochan My bad. Thanks.
