### ISSUE TITLE
[8.80.0] Controller group and attributes

### ISSUE THREAD

**Issue by Velman04** [laravel/framework#40486]
- Laravel Version: 8.80.0
- PHP Version: 7.4.27
- Database Driver & Version: not pertinent

### Description:
Previously, you could specify attributes in the router group.

Example:
```
Route::group(['as' => 'users.', 'prefix' => 'users'], function () {
    Route::get('/users', [UserController::class, 'index'])->name('index');
    Route::get('/users/{user_id?}', [UserController::class, 'item'])->name('item');
});
```
Now if you do the same with a group of controllers, an error will be displayed.

Example:
```
Route::controller(UserController::class)->group(['as' => 'users.', 'prefix' => 'users'], function () {
    Route::get('/users', 'index')->name('index');
    Route::get('/users/{user_id?}', 'item')->name('item');
});
```
Error:
![🧨 Array to string conversion - Google Chrome](https://user-images.githubusercontent.com/50420634/150090773-7f716d7c-8fca-4180-a5df-9721fdfe397c.png)

**Comment by andrey-helldar** [comment]
Did you come up with resource routes?

https://laravel.com/docs/8.x/controllers#resource-controllers

**Comment by andrey-helldar** [comment]
@Velman04, by the way, instead of

```php
Route::group(['as' => 'users.', 'prefix' => 'users'], function () {
    Route::get('/users', [UserController::class, 'index'])->name('index');
    Route::get('/users/{user_id?}', [UserController::class, 'item'])->name('item');
});
```

it is better to write:

```
Route::prefix('users')
    ->name('users')
    ->group(function () {
        Route::get('/users', [UserController::class, 'index'])->name('index');
        Route::get('/users/{id}', [UserController::class, 'item'])->name('item');
    });

// /users/users
// /users/users/{id}
```

Better yet, use resource routes:

```php
Route::resource('users', UserController::class)
    ->only('index', 'show');
```

**Comment by demiurge-ash** [comment]
He is talking about new feature: [ a route group controller](https://github.com/laravel/framework/pull/40276)

**Comment by andrey-helldar** [comment]
@demiurge-ash, that feeling when the main project uses Lumen 6 and you don't have time to follow the innovations 😅

**Comment by koenhoeijmakers** [comment]
This doesn't seem to have anything to do with the newly added `controller` method and this seems to work like intended. Just a bit unexpected.

In your "before" example `Route::group()` calls the `Router@group(array $attributes, $routes)` method as thats the facade accessor.

In your "after" example you're calling `controller()` first, which will return a `RouteRegistrar` of which the method definition is: `RouteRegistrar@group($callback)`.

That being said, the `Route` facade seems to have an incorrect definition for `group` as it should never be able to call the `RouteRegistrar@group` method?

```
@method static \Illuminate\Routing\Router|\Illuminate\Routing\RouteRegistrar group(\Closure|string|array $attributes, \Closure|string $routes)
```

**Comment by lukeraymonddowning** [comment]
You need to use one paradigm or the other as @koenhoeijmakers has alluded to. In your case, move 'controller' to a key in the group method array instead.

**Comment by driesvints** [comment]
It indeed seems we don't document the below usage anywhere:

```php
Route::someMethod(...)->group([...], function () {
```

If you can point me out to where we document that I can maybe have a look. But as it seems, I don't think that's expected to work.
