### ISSUE TITLE
Undot fails when key ends in a period

### ISSUE THREAD

**Issue by yormy** [laravel/framework#40500]
When the key ends in a period, the undot is incorrect. 

```
        $array = [
            'user.name' => 'Kevin Malone',
            'user.occupation.' => 'Accountant',
        ];

        $array = Arr::undot($array);

        dd($array);
```

results in
```
array:1 [▼
  "user" => array:2 [▼
    "name" => "Kevin Malone"
    "occupation" => array:1 [▼
      "" => "Accountant"
    ]
  ]
]
```

expected
```
array:1 [▼
  "user" => array:2 [▼
    "name" => "Kevin Malone"
    "occupation." => "Accountant"
  ]
]
```

**Comment by yormy** [comment]
Never mind...any dot in they key will probably break

**Comment by michael-rubel** [comment]
@yormy take a look at:

https://github.com/michael-rubel/framework/commit/3b92a3494f8a04bd5f28bcdf85b4e977fdeac858
https://github.com/michael-rubel/framework/commit/f333614ab51e2f55d77e7a536e47090a80fbd42e

But not sure if @taylorotwell would want to merge this.

P.S. PHP 8 required.

**Comment by yormy** [comment]
I had a similar solution. But a dot somewhere else in the key will still fail. So I abandoned that solution
