### ISSUE TITLE
before_or_equal/after_or_equal with nullable broken (already fixed if format is defined, but not with simple date rule)

### ISSUE THREAD

**Issue by danielpdm** [laravel/framework#40517]
- Laravel Version: 8.80
- PHP Version: 8.0
- Database Driver & Version: sqlsrv (MSSQL)

### Description:

before_or_equal/after_or_equal with nullable broken (already fixed if format is defined, but not with simple date rule)

### Steps To Reproduce:

Rules (example):

'first_date' => 'nullable|date|before_or_equal:second_date', 
'second_date' => 'nullable|date|after_or_equal:first_date|exclude_if:some_key,y',
'some_key' => 'nullable|string',

Request data:

some_key: "y"
first_date: "2022-01-10T00:00:00"
second_date: null

Error I get:

The first date must be a date before or equal to second date.

------------

Solution: like in the other bug -> return true, if any of this nullable dates is null (just ignoring this check)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
