### ISSUE TITLE
before_or_equal/after_or_equal with nullable broken (with date as rule and without date_format rule)

### ISSUE THREAD

**Issue by danielpdm** [laravel/framework#40525]
- Laravel Version: 8.80
- PHP Version: 8.0
- Database Driver & Version: sqlsrv (MSSQL)

### Description:

before_or_equal/after_or_equal with nullable broken (already fixed if format is defined, but not with simple date rule)

currently I found a workaround: using date_format:Y-m-d\TH:i:s instead of date

Bug is in Class Illuminate\Validation\Concerns\ValidatesAttributes and method compareDates. If a format is set it goes into checkDateTimeOrder which returns true if second date is null. In the case you use date as rule instead of date_format it goes further and into the function compare with a date and null and compares both, which results in a false.

### Steps To Reproduce:

Rules (example):

'first_date' => 'nullable|date|before_or_equal:second_date', 
'second_date' => 'nullable|date|after_or_equal:first_date|exclude_if:some_key,y',
'some_key' => 'nullable|string',

Request data:

some_key: "y"
first_date: "2022-01-10T00:00:00"
second_date: null

Error I get:

The first date must be a date before or equal to second date.

------------

Solution: like in the other bug -> return true, if any of this nullable dates is null (just ignoring this check)

protected function compareDates($attribute, $value, $parameters, $operator)
    {
        if (! is_string($value) && ! is_numeric($value) && ! $value instanceof DateTimeInterface) {
            return false;
        }

        if ($format = $this->getDateFormat($attribute)) {
            return $this->checkDateTimeOrder($format, $value, $parameters[0], $operator);
        }

        if (! $date = $this->getDateTimestamp($parameters[0])) {
            $date = $this->getDateTimestamp($this->getValue($parameters[0]));
        }

        return $this->compare($this->getDateTimestamp($value), $date, $operator);
    }

to

protected function compareDates($attribute, $value, $parameters, $operator)
    {
        if (! is_string($value) && ! is_numeric($value) && ! $value instanceof DateTimeInterface) {
            return false;
        }

        if ($format = $this->getDateFormat($attribute)) {
            return $this->checkDateTimeOrder($format, $value, $parameters[0], $operator);
        }

        if (! $date = $this->getDateTimestamp($parameters[0])) {
            $date = $this->getDateTimestamp($this->getValue($parameters[0]));
        }

        if (is_null($date)) return true;

        return $this->compare($this->getDateTimestamp($value), $date, $operator);
    }

**Comment by driesvints** [comment]
I don't think there's a bug here. If you really think there's a bug feel free so send in a PR with a failing test. Thanks

**Comment by danielpdm** [comment]
@driesvints this bug got partially solved : https://github.com/laravel/framework/issues/40086 - only for validations where a date format is defined in the rules. but the bug still exists if it doesn't have a defined format. I debugged it and I don't think it should work inconsistent like now. why are you always closing this bug? I even posted how it can be reproduced and an extended explaination and also a solution to this BUG! in the other case you saw it as a bug and fixed it, why not in this case?

**Comment by driesvints** [comment]
Hmm seems you're right. There are some strange things going on with these rules. I also discovered that, for example, the below doesn't fails:

```php
new Validator($trans, ['x' => '2012-01-15', 'y' => '2012-01-14'], ['x' => 'before_or_equal:y'])
```

Gonna dig into all of this. Sorry about that.

**Comment by driesvints** [comment]
It seems this isn't easily solvable. I've added extra tests to confirm the current behaviour here: https://github.com/laravel/framework/pull/40543

Btw, `'before_or_equal:y'` was failing because `y` is allowed in `date` in PHP so it's best to use actual field names instead of single characters. 

There's currently, as far as I can see, no good solution for this issue. We've decided we won't be spending more time into this but would appreciate PR's if anyone wants to solve this in a clean way. 

For now, we suggest you use a different approach at validating this data.

**Comment by danielpdm** [comment]
> 
@driesvints

new Validator($trans, ['x' => '2012-01-15', 'y' => '2012-01-14'], ['x' => 'before_or_equal:y']) this may not fail, but


new Validator($trans, ['start' => '2012-01-15', 'end' =>null], ['start' => 'nullable|date|before_or_equal:end',
'end' => 'nullable|date|after_or_equal:start',]) should fail - to reproduce this bug.


dont use x and y als attributes!!! first it tries strtotime and y = yesterday which is totally fine. if it doesn't get a valid date from strtotime it tries to find if there is a other attribute with this name to get its value. i debugged it and tested it and also have given u a solution!!!


```
protected function compareDates($attribute, $value, $parameters, $operator)
{
if (! is_string($value) && ! is_numeric($value) && ! $value instanceof DateTimeInterface) {
return false;
}

    if ($format = $this->getDateFormat($attribute)) {
        return $this->checkDateTimeOrder($format, $value, $parameters[0], $operator);
    }

    if (! $date = $this->getDateTimestamp($parameters[0])) {
        $date = $this->getDateTimestamp($this->getValue($parameters[0]));
    }

    return $this->compare($this->getDateTimestamp($value), $date, $operator);
}
```

this is the current code

u need to change it to the following:

```
protected function compareDates($attribute, $value, $parameters, $operator)
{
if (! is_string($value) && ! is_numeric($value) && ! $value instanceof DateTimeInterface) {
return false;
}

    if ($format = $this->getDateFormat($attribute)) {
        return $this->checkDateTimeOrder($format, $value, $parameters[0], $operator);
    }

    if (! $date = $this->getDateTimestamp($parameters[0])) {
        $date = $this->getDateTimestamp($this->getValue($parameters[0]));
    }

    if (is_null($date)) return true;

    return $this->compare($this->getDateTimestamp($value), $date, $operator);
}
```


only one line to solve it:

`if (is_null($date)) return true;`

it's not really that complicated. i would really need this fix quick to release a module on our test system for our customer to test it and fixing it there in the vendor is not an option. using workarounds also not an option if i have a correct bugfix recommendation to be merged in.

sorry i dont know the process with pr and so on here. but i worked myself in the code and i'm sure it's correct.

**Comment by driesvints** [comment]
If you implement that line you'll notice other tests will fail.

**Comment by danielpdm** [comment]
maybe some test could be wrong or inconsistant with date_format functionality - this is why i ask

@driesvints

**Comment by danielpdm** [comment]
@driesvints 

i checked which tests doesn't work:

```
$v = new Validator($trans, ['foo' => '2012-01-15 11:00', 'bar' => null], ['foo' => 'before_or_equal:bar']);
$this->assertTrue($v->fails());
```

why ->fails() - it looks inconstent?! why should it only pass, if a date format is defined

```
$v = new Validator($trans, ['foo' => '2012-01-15 11:00', 'bar' => null], ['foo' => 'before_or_equal:bar', 'bar' => 'nullable']);
$this->assertTrue($v->fails());
```

same

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => null], ['start' => 'before:ends', 'ends' => 'nullable']);
$this->assertTrue($v->fails());
```

same

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => null], ['start' => 'before:ends']);
$this->assertTrue($v->fails());
```

same

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => '31/12/2000'], ['start' => 'before:ends', 'ends' => 'after:start']);
$this->assertTrue($v->fails());
```

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => '31/12/2013'], ['start' => 'before:ends', 'ends' => 'after:start']);
$this->assertTrue($v->fails());
```

has to be analysed

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => '31/12/2000'], ['start' => 'after:31/12/2000', 'ends' => 'after:start']);
$this->assertTrue($v->fails());
```

has to be analysed

```
$v = new Validator($trans, ['x' => '31/12/2012'], ['x' => 'after:31/12/2000']);
$this->assertTrue($v->fails());
```

has to be analysed

```
$v = new Validator($trans, ['x' => '31/12/2000'], ['x' => 'before:31/02/2012']);
$this->assertTrue($v->fails());
```

has to be analysed

**Comment by danielpdm** [comment]
@driesvints i now fixed and tested it using following tests:

```
$x = new ValidationValidatorTest();
$x->testWeakBeforeAndAfter();
$x->testBeforeAndAfter();
$x->testBeforeAndAfterWithFormat();
$x->testValidateImplicitEachWithAsterisksBeforeAndAfter();
$x->testValidateSometimesImplicitEachWithAsterisksBeforeAndAfter();
$x->testAfterCallbacksAreCalledWithValidatorInstance();
```

some tests were wrong (=inconsistant with the checks using date_format)

i also fixed them

```
    /**
     * Compare a given date against another using an operator.
     *
     * @param string $attribute
     * @param mixed $value
     * @param array $parameters
     * @param string $operator
     * @return bool
     */
    protected function compareDates($attribute, $value, $parameters, $operator)
    {
        if (!is_string($value) && !is_numeric($value) && !$value instanceof DateTimeInterface) {
            return false;
        }

        if ($format = $this->getDateFormat($attribute)) {
            return $this->checkDateTimeOrder($format, $value, $parameters[0], $operator);
        }

        if (!$date = $this->getDateTimestamp($parameters[0])) {

            if (!Arr::has($this->data, $parameters[0])) return false;
            $date = $this->getDateTimestamp($this->getValue($parameters[0]));
        }

        if ($date === false) return false;

        if (is_null($date)) return true;

        return $this->compare($this->getDateTimestamp($value), $date, $operator);
    }
```

added

`if (!Arr::has($this->data, $parameters[0])) return false;`

it checks if even this attribute exists, if not it should be false

`if ($date === false) return false;`

checks if date could not be converted to a timestamp -> returns false

`if (is_null($date)) return true;`

checks if second date is null and returns true to skip it



```
    /**
     * Get the date timestamp.
     *
     * @param mixed $value
     * @return int|false
     */
    protected function getDateTimestamp($value)
    {
        if (is_null($value)) return null;

        $date = $this->getDateTime($value, false);

        return $date ? $date->getTimestamp() : false;
    }
```

returns false, if conversion failed



```
    /**
     * Get a DateTime instance from a string with no format.
     *
     * @param string $value
     * @param boolean $value
     * @return \DateTime|null|false
     */
    protected function getDateTime($value, bool $ignoreErrors = true)
    {
        try {
            return $ignoreErrors ? (@Date::parse($value) ?: null) : (Date::parse($value) ?: null);
        } catch (Exception $e) {
            return false;
        }
    }
```

can be more strict, when date couldn't be converted - and returns also false



corrected tests:

```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => null], ['start' => 'before:ends']);
$this->assertTrue($v->passes());
```

open end should be ok, like using date format


```
$v = new Validator($trans, ['start' => '31/12/2012', 'ends' => null], ['start' => 'before:ends', 'ends' => 'nullable']);
$this->assertTrue($v->passes());
```


```
$v = new Validator($trans, ['foo' => '2012-01-15 11:00', 'bar' => null], ['foo' => 'before_or_equal:bar']);
$this->assertTrue($v->passes());
```


```
$v = new Validator($trans, ['foo' => '2012-01-15 11:00', 'bar' => null], ['foo' => 'before_or_equal:bar', 'bar' => 'nullable']);
$this->assertTrue($v->passes());
```


could you evaluate it with your team? fixing this bug is really important to me

**Comment by danielpdm** [comment]
@driesvints 

in addition maybe following change will be needed:

```
        if (!$date = $this->getDateTimestamp($parameters[0])) {
            $date = $this->getDateTimestamp(
                Arr::has($this->data, $parameters[0]) ? $this->getValue($parameters[0]) : false
            );
        }
```

so the end (second date) doesn't need to be in the request

**Comment by danielpdm** [comment]
@driesvints should be dates in this asserts '2012-12-31' and not '31/12/2012'?

**Comment by driesvints** [comment]
@danielpdm please just pr something if you want.
