### ISSUE TITLE
hardcoded default redis connection 

### ISSUE THREAD

**Issue by raftx24** [laravel/framework#40530]
- Laravel Version: 8.68.1
- PHP Version: 8.0
- Database Driver & Version:

### Description:
In many places, we have a hardcoded `default` Redis connection that we cannot customize[for example, in rate limiter!].
is it possible instead of hardcoded `default` to use `database.redis.default` ?
For example RedisManager.php line 
```php
    public function purge($name = null)
    {
        $name = $name ?: 'default';

        unset($this->connections[$name]);
    }
```
we change it to:

```php
    public function purge($name = null)
    {
        $name = $name ?: $this->config['default_connection'];

        unset($this->connections[$name]);
    }
```

**Comment by driesvints** [comment]
This is a feature request. Please attempt a pr. Thanks
