### ISSUE TITLE
Doc - "assertSimilarJson" link is missing 

### ISSUE THREAD

**Issue by vlauciani** [laravel/framework#40531]
### Description:
In the "Response Assertions" Doc section:
- https://laravel.com/docs/8.x/http-tests#response-assertions

the link to "assertSimilarJson", doesn't exist:
- https://laravel.com/docs/8.x/http-tests#assert-similar-json

**Comment by driesvints** [comment]
Please send in a PR

**Comment by vlauciani** [comment]
A PR with what?

Remove the link? Update the link to the correct section (I do not know where is...)
