### ISSUE TITLE
Getting exception Call to undefined method, when trying to append accessor with new syntax

### ISSUE THREAD

**Issue by itxshakil** [laravel/framework#40556]
- Laravel Version: 8.77.1
- PHP Version: 8.0
- Database Driver & Version: mysql

### Description:
I am getting issue
Call to undefined method App\Models\Product::getLowestPriceAttribute()
Even though I have defined lowestPrice function that returns CastsAttribute.

`public function lowestPrice()`
 `   {`
 `       return \Illuminate\Database\Eloquent\Casts\Attribute::get(function(){`
`            return 0; #some calculation`
`        });`
`    }`

Working:
`$product->lowestPrice`

Not Working:
`$product->append('lowestPrice');`

Throws
`Call to undefined method App\Models\Product::getLowestPriceAttribute()`

**Comment by Jubeki** [comment]
You probably must access the Property with snake case: `lowest_price` / `lowest_vendor` 
See also https://github.com/laravel/framework/pull/40551

(I an not sure about this)

**Comment by driesvints** [comment]
Please use lowercase like @Jubeki suggests (thanks)
