### ISSUE TITLE
Memory leak in tests because HandleExceptions never cleans up

### ISSUE THREAD

**Issue by donnysim** [laravel/framework#40554]
- Laravel Version: 8.x (though any version with the same logic has this issue)
- PHP Version: 8.0.6/8.1.1
- Database Driver & Version: -

### Description:
Theres a problem of [HandleExceptions](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php) keeping the handler itself and the old [Application](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Application.php) instances throughout the whole test run, this is because of how `set_error_handler`, `set_exception_handler` and in addition `register_shutdown_function` work. All of these functions keep all the handlers in a memory stack, meaning they all reside in memory until the equivalent handler is restored or the application shuts down - which only happens when all tests have finished running.

To prove it, we can add:
```php
dump('cleanup', spl_object_id($this), spl_object_id($this->app));
```

to the the `__destruct`  handler or `handleShutdown` function of the `HandleExceptions` and it will only be executed after all tests are done. In addition, it will also execute n times, where n is the number of tests executed and all their ids are different meaning the handler and the application object it's holding to is no the same as previous execution, resulting in memory leak.

We can also test that this is the case using
```php
$prevHandler = set_error_handler([$this, 'handleError']);

// Make sure it's not the PHPUnit handler but our registered array
if (is_array($prevHandler)) {
    $isThis = $prevHandler[0] === $this; // always false
    $isSameApp = $prevHandler[0]->app === $this->app; // always false
}
```

### Steps To Reproduce:

While super basic and barebones test, I created 1000 tests with just bool assertion:

```php
protected function doAction()
{
    $this->assertTrue(true);
}

public function test_example()
{
    $this->doAction();
}

public function test_example2()
{
    $this->doAction();
}

// ... test_example1000
```

just commenting out or storing the handler as a static class variable to keep it single and just switching the $app variable in bootstrap
```php
set_error_handler([$this, 'handleError']);

set_exception_handler([$this, 'handleException']);

register_shutdown_function([$this, 'handleShutdown']);
```

saves 6 MB memory in total, tested with forced GC to avoid any memory fluctuations. Now if we have a `__destruct`, it will be called after each test and not after all tests are done, meaning it can now clean the object instantly without waiting for the process to finish. With more complex tests the memory difference can be greatly increased depending on the state the Application is holding on to.

I could make a PR but I have no idea what would be the best approach to keep a single exception handler instead of initiating it every time so knowledge about internals would help here. The main problem I see here is that if the HandleExceptions is to be instantiated every time, it needs to call `restore_error_handler` and `restore_exception_handler` before registering new handlers and `register_shutdown_function` should be registered only once no matter how many instances there are because it will prevent it from cleaning up.

**Comment by driesvints** [comment]
Thanks @donnysim for the detailed report. We'll have a look what we can do here 👍

**Comment by driesvints** [comment]
@donnysim can you attempt a PR?

**Comment by donnysim** [comment]
@driesvints yeah, sure, I can try to get something up once free after work.
