### ISSUE TITLE
Notification::assertSentTo doesn't work when multiple tests are runned

### ISSUE THREAD

**Issue by airdev-web** [laravel/framework#40559]
- Laravel Version: 8.80.0
- PHP Version: 7.4.26
- Database Driver & Version: MySQL

### Description:
In my UserController when a user is registered, I Notify admin's that the new user is registered.

```php
public function register_daily(RegisterUserDailyRequest $request)
{
    $user = User::where('email', '=', $request->email)
        ->first();

    if (!$user) {
        $user_lang = $request->cookie('LANG_SELECTED') ? explode('|', \Crypt::decryptString($request->cookie('LANG_SELECTED')))[1] : config('app.locale');

        $user = User::create([
            'email' => $request->email,
            'confirmed_user' => false,
            'role' => 'guest',
            'lang' => $user_lang,
        ]);

        // Send notification to admin's
        $admins = User::where('role', 'suadmin')->get();
        foreach ($admins as $admin) {
            $admin->notify(new NewUserRegistrationNotification($user));
        }
        
        // ...
```

And created a test for that :

```php
public function test_register_daily_mean_admin_is_notified()
{
    Notification::fake();

    $suadmins = User::factory(5)->create(['role' => 'suadmin']);
    $guests = User::factory(5)->create();

    $this->post(route('api.user.register_daily'), [
            'email' => 'test@mail.com',
        ])->assertStatus(200);

    Notification::assertSentTo($suadmins, NewUserRegistrationNotification::class);
    Notification::assertNotSentTo($guests, NewUserRegistrationNotification::class);
}
```

### Steps To Reproduce:

Running only this test and it passed.
But running all my tests using `php artisan test` failed only this test
```
• Tests\Feature\UserTest > register daily mean admin is notified
  The expected [App\Notifications\NewUserRegistrationNotification] notification was not sent.
  Failed asserting that false is true.
```

I have the same issue about another test, about cookie :

```php
public function test_register_daily_user_is_registered_with_lang_cookie()
{
    $email_test = 'test@mail.com';
    $lang = 'en';

    $this->withCookie('LANG_SELECTED', 'en');

    $this->post(route('api.user.register_daily'), [
        'email' => $email_test,
    ])->assertStatus(200);

    // Test the user is created with the selected lang
    $this->assertDatabaseHas('users', [
        'email' => $email_test,
        'lang' => $lang
    ]);
}
```

In my controller, I `dump($request->cookie('LANG_SELECTED')`. When running only this specific test, it works (`cookie = en`) but when running all my tests via `php artisan test` it fails and my `cookie = null`

Any idea ? Should I use a specific trait for my feature test ?

Thanks!

**Comment by koenhoeijmakers** [comment]
When you're running all your tests i suspect your database isn't cleaned in between tests and you're therefore getting a user found, thus `$user` resolves to `false` and your code doesn't get in the `if` branch, you could try using the `DatabaseTransactions` trait in your base `TestCase` to prevent your database from cloggin up.

**Comment by airdev-web** [comment]
I tried it, but still not work.. I really don't understand what's going on.

```php
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseTransactions;

    public function actingAsSuadmin()
    {
        $user = User::factory()->create(['role' => 'suadmin']);
        $this->actingAs($user);
    }

    public function actingAsGuest()
    {
        $user = User::factory()->create();
        $this->actingAs($user);
    }
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by airdev-web** [comment]
Hey there,

Thanks, here is the git repository : https://github.com/airdev-web/laravel-issue-40559

Meanwhile, a same kind of problem with another test :

```php
public function test_user_can_update_its_profile()
{
    $user = User::factory()->create();
    $this->actingAs($user);

    $response = $this->put(route('user.update', ['user' => $user]), [
        'email' => 'test@mail.com',
        'firstname' => 'firstname_test',
        'lastname' => 'lastname_test',
        'subscribed' => false,
        'lang' => 'en'
    ])
        ->assertSessionHasNoErrors();

    $updated_user = User::find($user->id);

    $this->assertEquals($updated_user->email, 'test@mail.com');
    $this->assertEquals($updated_user->firstname, 'firstname_test');
    $this->assertEquals($updated_user->lastname, 'lastname_test');
    $this->assertEquals($updated_user->subscribed, false);
    $this->assertEquals($updated_user->lang, 'en');
}
```

All tests are in `tests/Feature/UserTest.php`

Thanks! 😄

**Comment by driesvints** [comment]
@airdev-web seems like you committed all your changes in the first commit. Please re-read my instructions and make sure to commit your custom changes **separately**.

**Comment by airdev-web** [comment]
I do not really understand how to make it works.. Is there any other solution I can share you my code ?

**Comment by driesvints** [comment]
Doesn't that command I posted work for you?

**Comment by driesvints** [comment]
The repo should already be created with the --git flag. I'm very sorry but it seems you're having a bit of trouble with providing a repo. Can you first try a support channel? As I can't invest so much time right now in helping you out with this.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
