### ISSUE TITLE
model scopes not accepting named arguments

### ISSUE THREAD

**Issue by parmonov98** [laravel/framework#40575]
- Laravel Version: 8.54
- PHP Version: 8.0
- Database Driver & Version: docker, mysql, nginx
![image](https://user-images.githubusercontent.com/24564577/150725291-94458759-fa1a-493a-b137-9349d7e5d07a.png)

### Description:
I can't pass named arguments to scope of models.

### Steps To Reproduce:
create a model, create scope with 2 extra params excluding $query,  try to pass one param with name of second param in scope from controller or somewhere else. 
you'll get the passed value as first param.

**Comment by driesvints** [comment]
We don't specifically support named arguments sorry.
