### ISSUE TITLE
Batch job got 1205 "Lock wait timeout exceeded" error

### ISSUE THREAD

**Issue by walkonthemarz** [laravel/framework#40574]
- Laravel Version: 8.78.1
- PHP Version: 8.0.13
- Database Driver & Version: Mysql  Ver 8.0.27
- Queue Driver: SQS

### Description:
I have some jobs always get 1205 "Lock wait timeout exceeded" errors at the first beginning of starting dispatching a batch.
After some digging, I think the assumption below may explain the error I got. Please correct me if you got other ideas about that.

When a batch has many jobs like over 10,000 jobs and each job can be finished in several seconds, the batch may take several minutes to dispatch all jobs to SQS, during that time some of the dispatched jobs that have been consumed by workers will be waiting MySQL lock to decrement the pending jobs number in `queued_job_batches` table that the MySQL lock is still being occupied by the dispatching process. After waiting for 50 seconds which is the MySQL `innodb_lock_wait_timeout` value but the dispatching still has not finished yet, an "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded" error will be thrown in the worker process.

When dispatching, the below step may take a long time to finish and the MySQL transaction will lock the batch row for a long time.
https://github.com/laravel/framework/blob/master/src/Illuminate/Bus/Batch.php#L186-L194
```php
        $this->repository->transaction(function () use ($jobs, $count) {
            $this->repository->incrementTotalJobs($this->id, $count);

            $this->queue->connection($this->options['connection'] ?? null)->bulk(
                $jobs->all(),
                $data = '',
                $this->options['queue'] ?? null
            );
        });
```

Some of the dispatched jobs that have been consumed by workers are trying to decrement pending jobs but will have to wait for the transaction above to commit.
https://github.com/laravel/framework/blob/master/src/Illuminate/Bus/DatabaseBatchRepository.php#L138-L152
```php
    public function decrementPendingJobs(string $batchId, string $jobId)
    {
        $values = $this->updateAtomicValues($batchId, function ($batch) use ($jobId) {
            return [
                'pending_jobs' => $batch->pending_jobs - 1,
                'failed_jobs' => $batch->failed_jobs,
                'failed_job_ids' => json_encode(array_values(array_diff(json_decode($batch->failed_job_ids, true), [$jobId]))),
            ];
        });

        return new UpdatedBatchJobCounts(
            $values['pending_jobs'],
            $values['failed_jobs']
        );
    }
```

### Steps To Reproduce:

I have a crontab that will dispatch a batch with over 9,000 jobs to SQS each day and most of the jobs just need several seconds to finish.
Every day I can observe some first jobs will throw errors "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded" and a few minutes later the errors totally disappear.

Below is part of the exception trace:
![image](https://user-images.githubusercontent.com/9317172/150718931-69da3c97-f1eb-4c22-804c-897fbaedc196.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by walkonthemarz** [comment]
Thank you for the reply. 
But I do think the [bulk() method](https://github.com/laravel/framework/blob/57c1bd80baacce4fb02c5896418bbd15eb324a6a/src/Illuminate/Bus/Batch.php#L189) in the Batch dispatch method will potentially cause a long time database transaction that may block other updates on a row of the `queued_job_batches` table.

**Comment by llioor** [comment]
I have the same issue.
When I reach to 2 millions jobs in a batch I see lock time of 8 seconds.
I have mysql version 8.0 with 32 CPUs and 64GB memory, it is not dev ops issue.
Anyone?

**Comment by cyppe** [comment]
I see same issue.

It was described by another user here: https://github.com/laravel/ideas/issues/2591


This is the average time for me when monitoring queries from jobs.

```
array (
    'raw_query' => 'select * from `job_batches` where `id` = \'9b1b0d8a-ebf7-46b8-abce-927881af358e\' limit 1 for update',
    'time' => 4690.58,
  ),
```

And this is a common sight in mysql when running batches.


<img width="1095" alt="image" src="https://github.com/laravel/framework/assets/591720/1caadf57-8a9d-457e-a126-af356bf637d3">

**Comment by walkonthemarz** [comment]
Hi @cyppe, one possible solution to avoid the lock wait timeout is to dispatch the batch with empty jobs, so the batch can be inserted into database quickly without waiting for all jobs to be dispatched. After that, use $batch instance to dispatch job one by one:
```php
$batch = Bus::batch()->dispatch(); // Dispatch an empty Batch immediately

foreach ($jobs as $job) {
    $batch->add($job);
}
```

**Comment by cyppe** [comment]
Thanks! Interesting concept. Will try it.   I just tried to use this example from the previous thread, and it's lightning fast compared to original. But have not tested it enough to understand if it's bullet proof. 

So will for sure try your method now as it does not go away from standard code.

**Comment by cyppe** [comment]
I tried your method now.

Yes it removed the lock from the jobs. But now the dispatching of jobs is the bottleneck instead. Now it takes more time then before until all jobs are processed as workers are waiting for jobs.

So now it can $batch->add about 4 jobs per second if I add them one by one.


Queries during $batch->add() if I add them one by one, like so:

`		$jobs = $categories->map( function ( $category ) use ( $batch ) {			
			$batch->add( new cacheAllCategoriesDataJob( $category ) );
			Log::debug( DB::getRawQueryLog() );
			DB::flushQueryLog();
		} )->all();`


```

`[2024-01-16 13:06:20] local.DEBUG: array (
  0 =>
  array (
    'raw_query' => 'update `job_batches` set `total_jobs` = total_jobs + 1, `pending_jobs` = pending_jobs + 1, `finished_at` = null where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\'',
    'time' => 64.41,
  ),
  1 =>
  array (
    'raw_query' => 'select * from `job_batches` where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\' limit 1',
    'time' => 63.49,
  ),
)


[2024-01-16 13:06:20] local.DEBUG: array (
  0 =>
  array (
    'raw_query' => 'update `job_batches` set `total_jobs` = total_jobs + 1, `pending_jobs` = pending_jobs + 1, `finished_at` = null where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\'',
    'time' => 87.71,
  ),
  1 =>
  array (
    'raw_query' => 'select * from `job_batches` where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\' limit 1',
    'time' => 63.46,
  ),
)


[2024-01-16 13:06:20] local.DEBUG: array (
  0 =>
  array (
    'raw_query' => 'update `job_batches` set `total_jobs` = total_jobs + 1, `pending_jobs` = pending_jobs + 1, `finished_at` = null where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\'',
    'time' => 63.63,
  ),
  1 =>
  array (
    'raw_query' => 'select * from `job_batches` where `id` = \'9b1b2ddf-410e-486b-ae9e-5cb436b4630e\' limit 1',
    'time' => 63.56,
  ),
)`
```


And if I create empty batch and then $batch->add all the jobs instead.

Like so:

`	$batch = Bus::batch( [] )->name( 'cacheAllCategoriesDataJob batch' )->dispatch();
		
		$jobs = $categories->map( function ( $category ) use ( $batch ) {	
			return new cacheAllCategoriesDataJob( $category );
		} )->all();
		
		$batch->add( $jobs );`


Then we are back to table locks issue again.

<img width="1338" alt="image" src="https://github.com/laravel/framework/assets/591720/72cb3426-e317-4135-908c-068e233e8a62">


Maybe I do something wrong?

Otherwise I will continue to test the extended class methods as they seem to work really good so far. But need to test what happens during failed jobs etc.

**Comment by walkonthemarz** [comment]
How about dispatch by chunks? like split all jobs into chunks by 1000 jobs each chunk and dispatch them? By adjusting the number of jobs for each chunk, you may find an appropriate number for it.

**Comment by cyppe** [comment]
Still slower than I want on the dispatching end. But good advice as it's a bit better than default.

I have a working concept where I use redis as the storage for batches.  It's fully compatible with Horizon aswell.

It's not finished yet, but it's working really good so far. And it's really fast compared to database.

In case someone with experience with writing packages want to continue this work, as I think it's a good concept for a lot of people.

Here is the current work in progress:

https://gist.github.com/cyppe/3a099fb97273f5ac08c6bb215792b538

It's still under construction with some additional logging.  

Please leave a comment on the gist if anyone tries it. Would love to see it going into Laravel in future as most people use Redis as queues anyway it makes sense to also store batch information there.

**Comment by PankovAlxndr** [comment]
same problem :(
![Снимок экрана от 2024-01-20 13-49-16](https://github.com/laravel/framework/assets/3092550/28784d19-846d-463e-b0cf-b7482541a22b)

**Comment by cyppe** [comment]
Yes, the bundled database solution is not good when using many workers. It's a bit strange not more people complain about it. Maybe it will be more apparent now when people start using Laravel Pulse and see slow queries. I have a feeling most people have not realized the problem and just added more workers and thinking it was just slow jobs when in fact most of the time spent in jobs can be just waiting to get lock on job_batches table, and blocking workers from processing new jobs until they do.

Try my solution above to use Redis for taking over what job_batches currently is doing. I've been polishing it a little bit last days and I am using it in production now with success. But would be nice to get some feedback on it.

**Comment by cyppe** [comment]
I actually took my code and published a package now if anyone is interested. Please provide feedback on the repo. It's still work in progress. 

https://github.com/cyppe/laravel-batch-jobs-redis-driver
