### ISSUE TITLE
Laravel 8 / PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by byteasc** [laravel/framework#40594]
- Laravel Version: 8.80.0
- PHP Version: 8.1

### Description:

Is there plans to address deprecation warnings due to the handling of the null values in internal php functions in PHP 8.1?
https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg

It seems they're mostly all in Str.php currently, based on logging. It's making it hard to monitor my own internal areas that need to be updated due to this change in 8.1 and while its not detrimental, would like to clean it up. 

Or will we need to just adjust our usage of the Str:: methods to make sure we're not sending in null values anymore?

**Comment by X-Coder264** [comment]
All methods in the `Str` class have something along the lines of `@param  string  $string` in docblocks so from Laravel perspective it's up to the calling code to adhere to this contract, in which case there's no issue. Having a string typehint on those methods would be much better though.

**Comment by byteasc** [comment]
> All methods in the `Str` class have something along the lines of `@param string $string` in docblocks (meaning nulls are not allowed) so from Laravel perspective it's up to the calling code to adhere to this contract, in which case there's no issue. Having a string typehint on those methods would be much better though.

Yep! I noticed it was all properly phpdoc'd but after code review, we only utilize the particular method thats showing up in logs, in one spot... and doesn't appear to be the culprit so digging around deeper

**Comment by driesvints** [comment]
Like @X-Coder264 says, you're responsible for making sure to only send in strings to these methods. If there's really an issue somewhere with `null` being allowed and it's piped down to an internal PHP string function then we'd appreciate PR's to fix those. Thanks.
