### ISSUE TITLE
Inconsistent PHP requirements in composer.json

### ISSUE THREAD

**Issue by zeriyoshi** [laravel/framework#40601]
- Laravel Version: 7.x (EOL), 6.x
- PHP Version: 8.1.2
- Database Driver & Version: none

### Description:

Currently, the composer.json for Laravel 7.x and 6.x specifies `^8.0` as the required PHP version.

But, Laravel 7.x and 6.x do not currently support the PHP 8.1 strictness. Also, looking at the official tables, 7.x and 6.x are not supported by PHP 8.1.

https://laravel.com/docs/8.x/releases#support-policy

This is a barrier to creating packages for Laravel that support multiple versions.

It is suggested to specify the PHP version as <8.1 in the composer.json of 7.x and 6.x.

### Steps To Reproduce:

```
$ php -v
PHP 8.1.2 (cli) (built: Jan 21 2022 04:47:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
$ composer require laravel/framework "6.*"
```

**Comment by driesvints** [comment]
We can't change anything about this sorry. Please just don't use these Laravel versions on php 8.1
