### ISSUE TITLE
A nested Model can resolve its Factory, but the resolved nested Factory can't resolve its Model

### ISSUE THREAD

**Issue by IgorLockyh** [laravel/framework#40614]
- Laravel Version: 8.80.0
- PHP Version: 8.1.1 (sail)
- Database Driver & Version: MySql Server 8.0 (sail)

### Description:
A nested Model can resolve its Factory, but the resolved nested Factory can't resolve its Model.
Model is using its namespace to resolve a factory, but Factory is using only its "baseclass"
and can't resolve its model that is nested in the same way.

### Steps To Reproduce:

1. php artisan make:model User/Profile -f
2. Run the code snippet

```
// Model is using its namespace to resolve a factory (the Factory::resolveFactoryName() function actually)
// $factory is an instanceof \App\Database\Factories\User\ProfileFactory
$factory = \App\Models\User\Profile::factory();

// Factory is using only its "baseclass" and can't resolve a model that is nested in the same way
//Error:  Class "App\Profile" not found
$factory->create();
```

**Comment by driesvints** [comment]
So, I looked into this and managed to solve it although I'm not 100% sure it was intended or not. It does look like a bug but I'm gonna await Taylor's review on this first. See https://github.com/laravel/framework/pull/40616
