### ISSUE TITLE
Queuing events with unicode (non-ascii) payload strings fails

### ISSUE THREAD

**Issue by mixdf** [laravel/framework#40617]
- Laravel Version: 8.80.0
- PHP Version: 8.1.1
- Database Driver & Version: N/A (MySQL 5.7)

### Description:
Trying to queue an event with a queued event listener will fail if the event payload contains non-ascii characters (at least for the following example).

### Steps To Reproduce:

Consider the following event/listener and the use-case:
```php
class SampleEvent
{
    public function __construct(public string $unicodeString)
    {
    }
}

class SampleEventListener implements ShouldQueue
{
    public function handle(SampleEvent $event): void
    {
         // Do whatever!
    }
}

// Somewhere in the code
Event::dispatch(new SampleEvent('敏琳张'));
```

If we register a queued event listener for this event, Laravel will fail to serialize it with this message: `Unable to JSON encode payload. Error code: 5`

The problem is that `json_encode` fails to serialize the payload.

**Comment by driesvints** [comment]
I'm very sorry but it seems we don't support this right now. If you could figure out a way to make this work, we would appreciate a PR 👍

**Comment by mixdf** [comment]
@driesvints The fix was simple. Propose a fix in [this PR](https://github.com/laravel/framework/pull/40625).

**Comment by halaei** [comment]
@driesvints @mixdf Do you know what was actually wrong and how the PR fixed it? I am guessing the accepted PR may be a breaking change if the queue is stored in a mysql table with old `utf8` instead of `utf8mb4` charset.

**Comment by mixdf** [comment]
@halaei Good point, although I'm still unsure if that would be problematic since decoding both versions results in the same array.

**Comment by halaei** [comment]
@mixdf I am thinking your issue wasn't really about non-ascii characters. Maybe the queue driver you are using has limitation on the number of characters, e.g. the MySQL column is defined as `varchar(256)` instead of `text`.

**Comment by mixdf** [comment]
@halaei I'm using Redis as the queue driver and the actual error was encountered when trying to `json_encode` the event payload. The funny thing is that it doesn't happen when using `json_encode` on the string itself, so you might be right about some part of it. I'll try to see if I can narrow the issue down and fix the actual root cause.

**Comment by cristiancalara** [comment]
> @driesvints @mixdf Do you know what was actually wrong and how the PR fixed it? I am guessing the accepted PR may be a breaking change if the queue is stored in a mysql table with old `utf8` instead of `utf8mb4` charset.

This was indeed a breaking change in our case. It resulted in the job's payload actually being truncated at the point where the Unicode character was (in our case, an emoji).

**Comment by amcsi** [comment]
The fix to this issue caused breakage in my MSSQL usage. There's a `⚬` character that would normally take up more than 1 byte and PHP serializes it with that expectation. But when it gets inserted to the `jobs` database table, all such characters get converted to single character `?`s, and then when trying to process the queue, the job always fails with `ErrorException: unserialize(): Error at offset 1234 of 2345 bytes`.

Please revert this change. It doesn't make sense how Japanese characters couldn't be encoded. Doing this with the isuse's example works fine for me out of the box without special json_encode() options:

```php
11092 ± php artisan tinker
Psy Shell v0.10.7 (PHP 8.1.8 — cli) by Justin Hileman
>>> json_encode('敏琳张')
=> ""\u654f\u7433\u5f20""
>>> 

```
