### ISSUE TITLE
Image generated in test doesn't pass the Image validation rule

### ISSUE THREAD

**Issue by meyer59** [laravel/framework#40624]
- Laravel Version: 8.79.0
- PHP Version: 7.4
- Database Driver & Version: MysQl 8.22.0

### Description:
Hello
When you generate an image in a test for uploading purpose it doesn't pass the validation  [image rule](https://laravel.com/docs/8.x/validation#rule-image). I think the main reason is because the mimetype is not matching with the rule. The generated image has a `application/octet-stream` but in the image rule it checks for ` ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'webp']`
Cordially

### Steps To Reproduce:
In a test, generate a fake image:
`  $fakeImage = UploadedFile::fake()->image((string)Str::uuid()); //application/octet-stream`
Post it to a controller and validate it with the [image rule](https://laravel.com/docs/8.x/validation#rule-image).
You will get a 422 error that the image is not valid.

**Comment by theoboldalex** [comment]
I think this is the desired behaviour. A uuid won't have a `mimeTypeToReport` meaning that you would need to pass a string containing a filetype extension matching one of those described in the image rule in order to get the correct return value from `File::getMimeType`.

**Comment by agus24** [comment]
it works fine for me using this `UploadedFile::fake()->image('photo2.jpg')`

**Comment by meyer59** [comment]
I understand your point of view but `mimetype `has no connection with the extension.
In our app we are receiving a lot of images from Storage providers (S3, GCP etc) and they have not extension at all. 
In fact, if you check collection items on opensea.io all the images are using google sizing api and have no extension. 
For me, generating an image would mean generating a proper mimetype first.
Anyways, i will close this issue since i find out you can manually set the `mimetype ` on the testing file:
`$fakeImage->mimeType('image/jpeg');`
