### ISSUE TITLE
Multiple bootable model traits is not working

### ISSUE THREAD

**Issue by elkebirmed** [laravel/framework#40645]
- Laravel Version: 8.81.0
- PHP Version: 8.1.1
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.33, for Win64 (x86_64)

Using multiple boot traits with the same event will fire just the first one and ignore the rest bootable traits.

```php
class Tag extends Model
{
    use HasKey; // this will work (but if i put it bellow it will not work)
    use HasSlug; // this's not (but if i put it above it will work)

    public function getSlugKey(): string
    {
        return 'name';
    }
}
```

```php
trait HasKey
{
    public static function bootHasKey()
    {
        static::creating(
            fn (Model $model) => $model->key = 'value'
        );
    }
}
```

```php
trait HasSlug
{
    abstract public function getSlugKey(): string;

    public static function bootHasSlug()
    {
        static::creating(
            fn (Model $model) => $model->slug = $model->generateSlug($model->getSlugKey())
        );
    }

    protected function generateSlug(string $source): string
    {
        return 'value';
    }
}
```

**Comment by driesvints** [comment]
This indeed isn't supported.

**Comment by elkebirmed** [comment]
This must be in the roadmap

**Comment by kaydenvanrijn** [comment]
@elkebirmed 
Take a look at [this issue (#32159)](https://github.com/laravel/framework/issues/32159).
As of Laravel 8.x, you should be able to convert those to regular functions, i.e:

```php
trait HasKey
{
    public static function bootHasKey (): void
    {
        static::creating(function (Model $model) {
            $model->key = 'value'
            // or $model->setAttribute('key', 'value');
        });
    }
}
```
This *should* allow you to use multiple traits on the same model.
Credit to @danielsdeboer for helping me solve this issue.

@driesvints [Please don't close issues immediately (#34777)](https://github.com/laravel/framework/issues/34777)
