### ISSUE TITLE
ForeignKey-Migrations don't add an index, if there is still an other index containing that column

### ISSUE THREAD

**Issue by ALaDST** [laravel/framework#40655]
- Laravel Version: 8.80.0
- PHP Version: 8.0.10
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.5.12-MariaDB

### Description:
If there is a table with a column C which is already part of an (combined) unique index (maybe it happens with other indeces too) and you try to add a foreign key to C referencing some other table, the migration succeeds without any error. But if I look into the database, I can verify that no additional index (foreign-key-index) got created for C, which is wrong. The Foreignkey itself gets created correctly, but not the corresponding index.

### Steps To Reproduce:
- Create a table 'users' containing the columns [ Integer 'id' (PrimaryKey) ]
- Create a table 'test' containing the columns [ Integer 'id' (PrimaryKey) | Integer 'user_id' | Integer 'team_id' ]
- Add combined unique index to user_id + team_id by:
`Schema::table('test', function (Blueprint $table) { $table->unique(['user_id', 'team_id']); });`
- Add the foreign_key for the user_id column by:
`Schema::table('test', function (Blueprint $table) { $table->foreign('user_id')->references('id')->on('users'); });`

The user_id column has now a foreign key but no foreign key index. If you do the same with the team_id column it works. So it seems to be only a problem for the first column in the combined index.

### Workaround:
You can add the index manually afterwards:
`Schema::table('test', function (Blueprint $table) { $table->index('user_id', 'users_user_id_foreign'); });`
This at least fixes it, but that's not the right way.
(But for everyone encountering this problem, this could help for the moment)

**Comment by IgorLockyh** [comment]
Indices for foreign keys are added on MySql/MariaDB side. Probably the cause of your problem is that MariaDB can use composite ['user_id', 'team_id'] index instead of just 'user_id', therefore it optimizes index away

**Comment by driesvints** [comment]
This is intended I think. If you want to adjust this behaviour feel free to attempt a PR.
