### ISSUE TITLE
mysql performance_schema is not working with laravel

### ISSUE THREAD

**Issue by raftx24** [laravel/framework#40652]
- Laravel Version: 8.68.1
- PHP Version: 8.0.0
- Database Driver & Version: 8.0.27

### Description:
MySQL cannot capture queries that are performed by laravel and we cannot see them in performance_schema.

### Steps To Reproduce:
1. run this query:
```
DB::select("select * from users")
```
2. you won't see anything in performance_schema.prepared_statements_instances or other tables.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by eusonlito** [comment]
By default laravel set `PDO::ATTR_EMULATE_PREPARES => false` to improve query performance.

You can change this value with `PDO::ATTR_EMULATE_PREPARES => true` in `database.connections.mysql.options` array.

**Comment by raftx24** [comment]
@eusonlito hey thanks for replying.
It's not a good solution. Right now mysql performance schema supports prepared statements too. But it cannot capture Laravel queries. Maybe it's a PDO bug.

**Comment by eusonlito** [comment]
Please, read the full answer posted in https://stackoverflow.com/a/49792394

**Comment by raftx24** [comment]
@eusonlito check this too!
https://stackoverflow.com/a/10455228/4500653

**Comment by eusonlito** [comment]
@raftx24 yes! but these answer is from about 10 years ago and the question is related with `performance_schema` reports, not how `PDO::ATTR_EMULATE_PREPARES` works. Good luck fixing your issue!
