### ISSUE TITLE
Laravel won´t update column listing after migration which adds a new not null column and won´t allow insert into that column

### ISSUE THREAD

**Issue by mesiarm** [laravel/framework#40653]
- Laravel Version: 8.36.2
- PHP Version: 8.0.15
- Database Driver & Version: mysql:8.0

### Description:
fill() method in Illuminate\Database\Eloquent\Model  checks if attribute is fillable or not guarded. But isGuarded() in Illuminate\Database\Eloquent\Concerns\GuardsAttributes trait checks if column isGuardableColumn() an that method checks if column is in static::$guardableColumns, which is column listing from database (it is not well documented for isFillable() method). But static::$guardableColumns is only loaded once if not set and won´t update after running migration, if more migrations are migrated during one run of MigrateCommand command.
static::$guardableColumns should be updated after running Schema::table migration.

static::$guardableColumns could be moved to Illuminate\Database\Eloquent\Concerns\HasAttributes trait, renamed to $databaseColumns and checked in fill method in Illuminate\Database\Eloquent\Model class separately before $this->isFillable($key) checking for better readibility.

### Steps To Reproduce:
1. Create migration for table items and create model Item with guarded property id
`protected $guarded = ['id']; `
2. Create migration, which adds new column to existing table
```
Schema::table('items', function (Blueprint $table) {
            $table->string('slug');
        });
```
3. Create another migration which creates new models of Item, fills all attributes including slug and saves.
```
$data = ['slug' => 'test'];
            $item = new Item();
            $item->fill($data);
            $item->save();
```
4.  Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value is returned

### Workaround:
```
$item = new Item();
$item->setRawAttributes($data);
$item->save();
```

**Comment by mesiarm** [comment]
static::$guardableColumns could be moved to Illuminate\Database\Eloquent\Concerns\HasAttributes trait, renamed to $databaseAttributes and checked in fill method in Illuminate\Database\Eloquent\Model class  separately before $this->isFillable($key) checking for better readibility.

**Comment by mesiarm** [comment]
Workaround is to use setRawAttributes() method:
```
$item = new Item();
$item->setRawAttributes($data);
$item->save();
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by mesiarm** [comment]
When created new repository with current version of laravel framework, I could not reproduce the issue. I have found it was already fixed in newer version of laravel (https://github.com/laravel/framework/pull/39880)

**Comment by driesvints** [comment]
@mesiarm glad you found a fix 👍
