### ISSUE TITLE
enum arrayable casting

### ISSUE THREAD

**Issue by makroxyz** [laravel/framework#40693]
- Laravel Version: 8.81.0
- PHP Version: 8.1.1

### Description:
Different behaviour when casting to array an Enum implementing Arrayable class from collection and from eloquent model attribute.

### Steps To Reproduce:

I have this enum
```php
enum Status: string implements Arrayable
{
    case pending = 'pending';
    case done = 'done';
    
    /**
     * @inheritDoc
     */
    public function toArray()
    {
        return [
            'name' => $this->name,
            'value' => $this->value,
            'description' => "description of {$this->name}",
        ];
    }
}
```

In collection:
```php
collect(Status::pending)->toArray();
/**
[
     "name" => "pending",
     "value" => "pending",
     "description" => "description of pending",
   ]
*/
```

in Model:
```php
class MyModel extends Model
{
    protected $casts = [
        'status' => Status::class
    ];
}


MyModel::first()->toArray();
/**
[
    'id' => 1,
    'status' => 'pending'
]
*/
```

Even without Arrayable interface on enum the result is different.

Is it right? 

How can I cast MyModel to array and have enum attribute (automatically) casted following the Arrayable interface?

This is related to a (closed) PR #40605. Should it be considered for 9.x?

**Comment by driesvints** [comment]
Heya, this seems to be rejected. You can indeed always attempt a new PR for 9.x but it's up to Taylor in the end to accept or not.
