### ISSUE TITLE
Naming issue in Filesystem Manager

### ISSUE THREAD

**Issue by Tylerian** [laravel/framework#40706]
### Versions
- Laravel Version: `all`

### Description:
The Filesystem Manager's [`getDefaultDriver` method ](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemManager.php#L308) is returning the default `disk` name and it's confusing. Instead, it should be renamed to `getDefaultDisk`.

**Comment by driesvints** [comment]
Resubmit this with a filled out issue template.
