### ISSUE TITLE
Missing fluent string method "scan"

### ISSUE THREAD

**Issue by DeMossiah** [laravel/framework#40715]
- Laravel Version: 8.80.0
- PHP Version: 8.1.2
- Database Driver & Version: -

### Description:
The Laravel documentation shows Fluent strings should have a method called "scan" (https://laravel.com/docs/master/helpers#method-fluent-str-scan), this method does not exist.

### Steps To Reproduce:
```
use Illuminate\Support\Str;

$collection = Str::of('filename.jpg')->scan('%[^.].%s');
```

#### Expected output
`collect(['filename', 'jpg'])`

#### Actual output
`Method Illuminate\Support\Stringable::scan does not exist.`

**Comment by Jubeki** [comment]
Please upgrade to `8.81.0` this method was added there.

**Comment by DeMossiah** [comment]
Oh my, terribly sorry for that one...
