### ISSUE TITLE
[9.x] Target [Illuminate\Contracts\Broadcasting\Factory] is not instantiable while testing If any report is configured.

### ISSUE THREAD

**Issue by fcno** [laravel/framework#40714]
- Laravel Version: 9.x
- PHP Version: PHP 8.1.1 (cli) (built: Dec 15 2021 10:31:43) (ZTS Visual C++ 2019 x64)
    Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

- Database Driver & Version: none

### Description:
At the end of the tests execution, If file `phpunit.xml` is configured to generate a report, the following error is being thrown, causing the suite to fail, even though all tests have passed.

```bash
Target [Illuminate\Contracts\Broadcasting\Factory] is not instantiable
```

This behavior does not occur in Laravel 8.x, only in 9.x.

Command & output

```baseh
$ php artisan test

   PASS  Tests\Unit\ExampleTest
  ✓ that true is true

   PASS  Tests\Feature\ExampleTest
  ✓ the application returns a successful response

  Tests:  2 passed
  Time:   0.40s

Target [Illuminate\Contracts\Broadcasting\Factory] is not instantiable.
```

### Steps To Reproduce:

1. Create a fresh Laravel 9.x application
2. Add the following configuration in phpunit.xml file (the report part).
  ```xml
    <coverage processUncoveredFiles="true">
        [...]
        <report>
            <html outputDirectory="build/coverage"/>
        </report>
    <coverage processUncoveredFiles="true">
  ```
3. Do not change anything else in the application, use everything with default values generated by Laravel.
4. Execute `php artisan test`

If you follow the steps above, in Laravel 8 there won't be the error, but in Laravel 9 there will be.

**Comment by derekmd** [comment]
I think you need to direct this issue to https://github.com/nunomaduro/collision/issues that provides `php artisan test`.

"laravel/laravel" 9.x bumps "nunomaduro/collision" to ^6.0: https://github.com/laravel/laravel/pull/5660/files

A `--coverage` option was also just added 11 days ago: https://github.com/nunomaduro/collision/pull/206

**Comment by driesvints** [comment]
Thanks @derekmd
