### ISSUE TITLE
Illuminate/view has hidden dependency on illuminate/conditionable not specified in composer.json

### ISSUE THREAD

**Issue by calvinalkan** [laravel/framework#40724]
- Laravel Version: 8.81
- PHP Version:  7.4.27
- Database Driver & Version: standalone blade package.

### Description:

I'm using Blade as a standalone templating engine without the full framework.
There is a hidden dependency in the illuminate/view package that will cause a Fatal Error At runtime.

`Fatal error: Trait 'Illuminate\Support\Traits\Conditionable'`

The [ComponentAttributeBag](https://github.com/laravel/framework/blob/v8.81.0/src/Illuminate/View/ComponentAttributeBag.php) requires `Illuminate\Support\Traits\Conditionable` but that package is not specified in [composer.json](https://github.com/laravel/framework/blob/v8.81.0/src/Illuminate/View/composer.json)

**Comment by driesvints** [comment]
This trait is present in the support component which is a dependency of the view component in 8.x so this can't happen under the version you specified. However, it seems this dependency is indeed missing in 9.x so I've sent in a fix for that: https://github.com/laravel/framework/pull/40725

Thanks

**Comment by driesvints** [comment]
I also think this already works in 9.x because conditionable is a dependency of support which is a dependency of view.

**Comment by calvinalkan** [comment]
I double-checked again why this happens. It happens when you run composer install with the --prefer-lowest option, which I need in CI/CD. And since the Conditionable trait was added in illuminate/support 8.45 ( I think ) it blows up because it will install 8.0.0

**Comment by calvinalkan** [comment]
@driesvints So basically the first tagged version of `illuminate\view` that uses the Conditionable trait should explicitly set the `illuminate/support` version to `^8.45"`. [First introduced in 8.45](https://github.com/laravel/framework/commit/45ff23c6174416f63ea7dbd77bc7fe8aafced86b#diff-e2f597fdca8b411b08956d2bc32a6ddbe376b9f7edb83c4f26b55932456ef03e)

**Comment by driesvints** [comment]
@calvinalkan I see. Yeah we can do that. Feel free to send in a PR 👍

**Comment by calvinalkan** [comment]
@driesvints How would you go about this?

The problem also exists for other dependencies. For example, illuminate view will also break with any version of collections lower than 8.32 due to the value() helper not accepting args.
[see](https://github.com/laravel/framework/commit/a5d9b455af1dc91bf73aee95147029fd8b540f78#diff-35610154a978a826c69ebffb89e10e007c00fed3c624983fd863e0d12ea21c92) here.

**Comment by driesvints** [comment]
Yeah we'll need to update the constraints everywhere where a minimum dependency is needed of another component.
