### ISSUE TITLE
SQS Prefix config var is not actually acting as a prefix

### ISSUE THREAD

**Issue by stemis** [laravel/framework#40743]
- Laravel Version: 8.82.0

### Description:
I'd like to make use of the `prefix` option for SQS. However, the `prefix` var right now is not actually a prefix, it's actually just your account URL, you cannot add anything after that. The reason is because it always add a `/` add the end followed by your queue name.

I would like to configure my prefix as follows:
```php
[
    'prefix' => 'https://sqs.us-east-1.amazonaws.com/your-account-id/production-',
    'queue' => 'default'
]
``` 

Then if I queue anything on `queueOn('notifications')`, I expect the URL to be:
`https://sqs.us-east-1.amazonaws.com/your-account-id/production-notifications`
However, this is not the case. the URL now is:
`https://sqs.us-east-1.amazonaws.com/your-account-id/production-/notifications` which is an invalid sqs URL altogether.

The code responsible for this is the following:

https://github.com/laravel/framework/blob/00cdf85281788d01e0bbfd66577a11b20ff98b79/src/Illuminate/Queue/SqsQueue.php#L202-L211

I would expect the prefix to work exactly like any prefix, but right now it's completely limited to your account URL, you cannot provide a true `prefix` which would be much more convenient for the use case I just laid out.

I'd be happy to see if I can make a PR for this that's also backwards-compat with new env vars and some docs. Looking forward to hear your opinion about this.

Related: #32081 #32098

**Comment by driesvints** [comment]
@stemis think you can attempt a new PR for this. Make sure there's no breaking changes or send to the next major version branch. Thanks
