### ISSUE TITLE
Enum is weird in php 8.1 

### ISSUE THREAD

**Issue by magic-thomas** [laravel/framework#40753]
- Laravel Version: 8.82.0
- PHP Version: 8.1.0
- Database Driver & Version: 10.6.4-MariaDB

### Description:

Retriving and displaying Enum values raise error after changing Enum values in Enum class. 

### Steps To Reproduce:

in Post model

```php 
    namespace App\Models;

    use App\Enums\PostStatus;

    class Post extends Model
    {
        protected $fillable =[
            'status',
        ];
        
        protected $casts = [
            'status'=> PostStatus::class,
        ];
    }
```

in PostStatus Enum

```php 
    namespace App\Enums;

    enum PostStatus: string
    {
        case ACTIVE ='ACTIVE';
    }

```

in controller 

```php
    function save() {
        $post_cat = new Post;
        $post_cat->status = PostStatus::ACTIVE ;
        $post_cat->save();
    }
```
in router 

```php
    Route::get('/test', function ( Request $request ) {
        return view('test', [
            'post'=> Post::find(1)
        ]);
    });
```

in test.blade.php 

```php 
{{  $post->status->value  }}
```

And then I visted '/test' . It is ok.

```html 
ACTIVE
```

But I changed PostStatus Enum value.

```php 
    namespace App\Enums;

    enum PostStatus: string
    {
        case ACTIVE = 'I changed Value';
    }

```
and the '/test' shows error .

```sh 

"ACTIVE" is not a valid backing value for enum "App\Enums\PostStatus"

```

I wonder why I must not change Enum values. 

Is it just intended feature?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
