### ISSUE TITLE
Allow all policy abilities except attaching

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#40776]
- PHP version: 7.4.27
- Laravel version: 8.80.0
- MySQL version: 8.0.27-0ubuntu0.21.10.1
- MySQL Client version: mysqlnd 7.4.27

### Description:
Not sure if this should come under Laravel or Nova, but here goes

```PHP
// in a policy,

public function before($user, $ability)
{
    // I wish to allow all abilities, except attaching any new Sales Order Item
    // however, $ability does not return any values that start with `attach*`
}

public function attachAnySalesOrderItem(User $user, $model)
{
    return false;
}
```
- If `before()` returns a non-null (`true`/`false`), then `attachAnySalesOrderItem` will never be called.
- If `before()` returns null, `attachAnySalesOrderItem` will be called, but several other methods will also need to be defined, otherwise `view` and `viewAny` are not allowed
- Perhaps check for existence of `attachAnySalesOrderItem` prior to calling `before()`?
- It sounds confusing, but this is because default permissions of `add`, `attach` and `detach` are inverted from the rest
    - https://nova.laravel.com/docs/3.0/resources/authorization.html#undefined-policy-methods
- Perhaps a better name for `before()` is `default()` and it refers to only CRUD (and not relationships) + make this more explicit in the docs?
- Or introduce `after()` like gates?
- I struggled with this for quite a while until it became clear and don't have the best way forward, but I'm sure someone at Laravel does :)

**Comment by driesvints** [comment]
Thanks @rodrigopedra
