### ISSUE TITLE
Validation errors are always empty in Laravel 9.x-dev

### ISSUE THREAD

**Issue by robinheidrich** [laravel/framework#40773]
- Laravel Version: 9.x-dev
- PHP Version: 8.1.2
- Database Driver & Version: MariaDB 10.6.5

### Description:
Since I upgraded to Laravel 9, validation errors are no longer displayed.

The output of `dd($errors)` always returns an empty array, even if there definitely should be an error.

```
Illuminate\Support\ViewErrorBag {[#289 ▼]()
  #bags: []
}
```

I tested if this is definitely an error in Laravel 9 and when downgrading back to Laravel 8 the errors were displayed again.

No idea what the reason is.

### Steps To Reproduce:
- Use a validation in the controller
- Output the content of `$errors` in the view

In Laravel 8 the error is displayed, in Laravel 9 it is not.

**Comment by liviusirbulescu** [comment]
This is due to the new Session Serialization Strategy in 9.x (introduced in beta 4). Errors are empty only when serialization is set to 'json' in config/session.php (current default), either comment or update 'serialization' => 'php' as a temporary workaround.

**Comment by chuckrincon** [comment]
For more information about this change: [[9.x] JSON Session Option](https://github.com/laravel/framework/pull/40595)

**Comment by driesvints** [comment]
I've sent in a PR to revert this. Thanks.
