### ISSUE TITLE
SAIL_XDEBUG_CONFIG does nothing when set as an ENV

### ISSUE THREAD

**Issue by Kyon147** [laravel/framework#40785]
- Laravel Version: 8.75
- PHP Version: 8.0.14
- Database Driver & Version:

### Description:
When using Sail and setting the `SAIL_XDEBUG_CONFIG` env and building the docker container - Xdebug does not update configs which were marked in the ENV.

![image](https://user-images.githubusercontent.com/32519106/152360738-9e7c5927-6092-4975-8180-d91de71d9c01.png)

![image](https://user-images.githubusercontent.com/32519106/152360712-c3bcf2ff-3409-49f0-af3a-6989b3b466cb.png)

### Steps To Reproduce:
1. Install Laravel Sail 8.0 with the following additional envs
SAIL_XDEBUG_MODE=develop,debug
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal start_with_request=yes"

2. `./vendor/bin/sail php -i 
3. Confirm you see `xdebug.start_with_request => default => default` which should have updated to "yes"

**Update**

Some further digging it looks like it is because PHP_FPM is clearing the ENVs as edebug warns.

![image](https://user-images.githubusercontent.com/32519106/152361948-c5821414-a9b3-499c-a4b4-971e19b81309.png)

When setting `xdebug.start_with_request = yes` to the `php.ini` file in /`vendor/laravel/sail/runtimes/8.0` the config gets updated.

Looks like either need to use `clear_env = off` adding that to the dockerfile php.ini or remove `SAIL_XDEBUG_CONFIG` as it currently does nothing anyway.

**Comment by driesvints** [comment]
Thanks @Kyon147 for your investigating. Can you send in a PR to the different runtimes of Sail?

**Comment by Kyon147** [comment]
> Thanks @Kyon147 for your investigating. Can you send in a PR to the different runtimes of Sail?

Hey, @driesvints - sure thing will sort out a PR to get it working as intended.
