### ISSUE TITLE
Notification broadcastType not working as expected

### ISSUE THREAD

**Issue by kikky7** [laravel/framework#40798]
- Laravel Version: 8.52.0
- PHP Version: 7.4.25
- Database Driver & Version: mysql 8.0.26

### Description:

According to the documentation https://laravel.com/docs/8.x/notifications#customizing-the-notification-type I should be allowed to customize the type of my notifications instead of having full class names as type. However, type is still saved as full class name in database.

### Steps To Reproduce:

This is my broadcastType method inside my Notification class:
```
public function broadcastType()
{
    return 'test-type';
}
```
It works only for client:
```
Echo.private("App.User." + id).notification((notification) =>
    console.log(notification)
);
```
This is what I get in console log:
```
{
  "id": "notification-db-id",
  "type": "test-type",
  ...
}
```
In database it is saved as full class name `App\Notifications\MyTestNotification` and when I fetch notifications via available relations `notifications` or `unreadNotifications`, I get full class name for type instead of my custom `test-type` value.

EDIT: I realized that broadcastType is only for broadcast (client) message, but is there a way to customize database type too or use same type name? I can't find anything about it in docs.

**Comment by driesvints** [comment]
Right now, there is no way to customise the notification type saved in the database. I also wish this was possible but it's proven to be very difficult to implement unfortunately.
