### ISSUE TITLE
Bug in insert query with eloquent model

### ISSUE THREAD

**Issue by michaelnabil230** [laravel/framework#40797]
There is a problem with the query Database. I know that it is a rather selective problem, but we must solve it

- Laravel Version: 8.82
- PHP Version: 8.1
- Database Driver & Version: MySql 10.4.22-MariaDB

### Description:
When inserting values in the database, I have that the keys are the same when they should be different 

## My test case

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Product;
use App\Models\Attribute;
use App\Models\AttributeOption;
use App\Models\ProductAttributeValue;
use Illuminate\Support\Facades\Artisan;

class DataBaseTest extends TestCase
{
    public function test_seed()
    {
        Artisan::call('migrate:fresh');

        $this->assertTrue(true);
    }

    public function test_add_product()
    {
        $product = Product::create([
            'name' => 'test Product'
        ]);

        $this->assertEquals(1, $product->id);
    }

    public function test_add_attribute()
    {
        $attribute = Attribute::create([
            'name' => 'Color'
        ]);

        $this->assertEquals(1, $attribute->id);
    }

    public function test_add_another_attribute()
    {
        $attribute = Attribute::create([
            'name' => 'Ram'
        ]);

        $this->assertEquals(2, $attribute->id);
    }

    public function test_add_attributeOption()
    {
        $attributeOption = AttributeOption::create([
            'name' => 'Red',
            'attribute_id' => 1
        ]);

        $this->assertEquals(1, $attributeOption->id);
    }

    public function test_add_another_attributeOption()
    {
        $attributeOption = AttributeOption::create([
            'name' => 'Black',
            'attribute_id' => 1
        ]);

        $this->assertEquals(2, $attributeOption->id);
    }

    public function test_insert_with_same_columns()
    {
        $result = ProductAttributeValue::insert([
            [
                'attribute_id' => 1,
                'attribute_option_id' => 1,
                'product_id' => 1,
            ],
            [
                'attribute_id' => 1,
                'product_id' => 1,
                'attribute_option_id' => 2
            ]
        ]);

        $this->assertTrue($result);
    }

    public function test_insert_with_different_columns()
    {
        $result = ProductAttributeValue::insert([
            [
                'attribute_id' => 1,
                'attribute_option_id' => 1,
                'product_id' => 1,
            ],
            [
                'attribute_id' => 2,
                'product_id' => 1,
                'text_value' => '15 Gb'
            ]
        ]);

        $this->assertTrue($result);
    }
}
```

## My result test
![image](https://user-images.githubusercontent.com/46572405/152448129-68ef57d6-8310-4eeb-9292-513d64019ad8.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by michaelnabil230** [comment]
Thanks, @driesvints. But it is not a question. It is a bug and I have limited the problem to the test until I present it to you until you solve it in the next version. Please do not send the same message and pay attention to the problem. I'd say it's a logical problem, but it has a solution

**Comment by driesvints** [comment]
I'm sorry but all of this seems custom to me. Please try a support channel.

**Comment by michaelnabil230** [comment]
@BrandonSurowiec Can you help me clarify the problem?

**Comment by BrandonSurowiec** [comment]
@michaelnabil230 This is intended behavior. `ProductAttributeValue::insert([...])` is a mass insert, which means that all the attributes being inserted MUST be declared for each array item.

Look at the query and you'll see the columns are declared once, and then all the values that come after reference the same columns.  You would have to format your data to something like this:

```php
$result = ProductAttributeValue::insert([
    [
        'attribute_id' => 1,
        'attribute_option_id' => 1,
        'product_id' => 1,
        'text_value' => ''
    ],
    [
        'attribute_id' => 2,
        'attribute_option_id' => null,
        'product_id' => 1,
        'text_value' => '15 Gb'
    ]
]);
```

Don't use mass-insert and instead loop over the array to create them one by one:

```php
$attributes = [
    [
        'attribute_id' => 1,
        'attribute_option_id' => 1,
        'product_id' => 1,
    ],
    [
        'attribute_id' => 2,
        'product_id' => 1,
        'text_value' => '15 Gb'
    ]
];

foreach($attributes as $insert) {
    ProductAttributeValue::create($insert);
}
```

Or you can leverage Eloquent methods. Your `ProductAttributeValue` model looks like a pivot table. If you want to leverage relationships you would look over these parts of the docs:

- <https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models>
- https://laravel.com/docs/8.x/eloquent-relationships#updating-many-to-many-relationships
- https://laravel.com/docs/8.x/eloquent-relationships#attaching-detaching (look at the array method that allows passing extra data)

```php
$user->roles()->attach([
    1 => ['expires' => $expires],
    2 => ['expires' => $expires],
]);
```

Looping and inserting one by one is by far the easiest 👍

**Comment by driesvints** [comment]
Thanks @BrandonSurowiec. 

@michaelnabil230 can you please first try a support channel next time? Usually, lots of these sorts of questions can be resolved before opening an issue. Thanks

**Comment by michaelnabil230** [comment]
Thank @BrandonSurowiec , for your explanation, but I've posted the issue so you can find a solution so we can develop it on Laravel.
And excuse me for not being able to speak English fluently.
