### ISSUE TITLE
Upsert method updates timestamps of records that it shouldn't

### ISSUE THREAD

**Issue by webbby** [laravel/framework#40827]
- Laravel Version: 8.0
- PHP Version: 7.3
- Database Driver & Version: mysql & unknown (mysql 8.0.15)

### Description:
The `updated_at` column of records  that have not been updated is still modified when it shouldn't

`addresses` table `city_id, post_code_id` pairs are unique
```php
$upserts = [
   [  'city_id' => 11, 'post_code_id' => 543  ], 
   [  'city_id' => 23, 'post_code_id' => 987  ], 
   [  'city_id' => 39, 'post_code_id' => 1277 ], 
   [  'city_id' => 43, 'post_code_id' => 1387 ],    
];

Address::query()->upsert(
    $upserts,
    ['city_id', 'post_code_id'],
    ['city_id', 'post_code_id'],
);
```

In my case record  ` [  'city_id' => 11, 'post_code_id' => 543  ]` was identical in the db so obviously no changes should be inflicted on the record. But still `updated_at` column was changed with a new timestamp.

Without investigating my guess is the `ON DUPLICATE KEY` query should be build with the provided on invocation columns of significance with conditional compared statements for each 

```mysql
UPDATE updated_at = IF(city_id=VALUES(city_id),updated_at,NOW()),
       updated_at = IF(post_code_id=VALUES(post_code_id),updated_at,NOW())
```
as far as mysql  is concerned. What's the case with Postgre and is it affected with similar issue I don't know. 

### Steps To Reproduce:
Just try to upsert to a few records that are identical with values of the upserted array items and expect the `updated_at` column to be changed.

**Comment by driesvints** [comment]
This cannot be known upfront because you're directly using a query. We don't know what the data is since we haven't retrieved it and thus don't know if it matches. We always touch the updated_at timestampt.

Your solution seems viable but I don't know if it can match the current inner workings of how query upserting/updating works. Feel free to send in a PR though if you can improve this.

**Comment by webbby** [comment]
> This cannot be known upfront because you're directly using a query. We don't know what the data is since we haven't retrieved it and thus don't know if it matches. We always touch the updated_at timestampt.
> 
> Your solution seems viable but I don't know if it can match the current inner workings of how query upserting/updating works. Feel free to send in a PR though if you can improve this.

What do you mean you don't know, of course you do that's how the method works!
It's a simple check by operator concatenation of the columns provided by the first argument of the method in the generated query

```
updated_at=IF(
  `city_id`<=>VALUES(`city_id`)&&
  `post_code_id`<=>VALUES(`post_code_id`)&&
  .....
,`updated_at`, NOW())
```

**Comment by driesvints** [comment]
@webbby if you think this can be improved you're welcome to send in a PR 👍
