### ISSUE TITLE
Both whereHas and whereRelation dosent support another db connection

### ISSUE THREAD

**Issue by llabbasmkhll** [laravel/framework#40823]
- Laravel Version: 8.54
- PHP Version: 8.0
- Database Driver & Version: MySql mariadb-10.6.5 win64

### Description:

Both whereHas and whereRelation doesnt support another db connection

### Steps To Reproduce:
when i want to fillter by relation . the related table is in other database
OpratorScoreController.php
```php
$scores = OperatorScore::whereHas('visit', function ($query) {
            $query->where('commitment', '88');
        })->get();
```

however i have defined the connection in the model
OperatorScore.php
```php
public function visit()
{
    return $this->setConnection('mysql_cake')->belongsTo(Visit::class, 'visit_id');
}
```
but still it tries to access the incorrect database

**Comment by derekmd** [comment]
Related past issues: https://github.com/laravel/framework/issues/35414 https://github.com/laravel/framework/issues/33402 https://github.com/laravel/framework/issues/23042

https://laravel.com/docs/8.x/eloquent-relationships#querying-relationship-existence

![nein-cross-database-relations](https://user-images.githubusercontent.com/823566/152685569-28977a73-6969-4295-bc1e-dfb57c6de3b6.png)

You can try 3rd-party package https://github.com/hoyvoy/laravel-cross-database-subqueries although its repo is currently archived so someone must fork it to support laravel/framework 9.x.

**Comment by llabbasmkhll** [comment]
ok thanks
