### ISSUE TITLE
Validator::make(...)->passes() is in docs (and works), but the function is not in the Facade's contract

### ISSUE THREAD

**Issue by darynmitchell** [laravel/framework#40843]
- Laravel Version: v8.82.0
- PHP Version: 7.4.26
- Database Driver & Version: N/A

### Description:

The [Validation Docs show usage of a `passes()` function](https://laravel.com/docs/8.x/validation#implicit-rules) like: `Validator::make($input, $rules)->passes();`
This gets marked as an error in my IDE (via inteliphense), but the code works.

This is because:
1. The `Validator` Facade (framework/src/Illuminate/Support/Facades/Validator.php) PHPDoc specifies the return type of `function make` as `\Illuminate\Contracts\Validation\Validator`
```
 * @method static \Illuminate\Contracts\Validation\Validator make(array $data, array $rules, array $messages = [], array $customAttributes = [])
```
2. That interface (`\Illuminate\Contracts\Validation\Validator`) does not declare a `passes()` function
3. But the implementation of `make()` (vendor/laravel/framework/src/Illuminate/Validation/Factory.php) actually returns an object of type `\Illuminate\Validation\Validator`, which implements not only the Validator contract, but also a `passes()` function.

Thus the **dynamic** call `Validator::make($input, $rules)->passes()` does work, but the IDE is **correct** to flag `passes()` as an error, because the function does not exist on the returned interface documented in the Validator Facade.

Questions:
- Should this be fixed? I'm hoping the answer is yes, as `$validator->passes()` is useful for semantic clarity rather than double negation `!$validator->fails()`
- Would a fix be to add the `passes()` function to `\Illuminate\Contracts\Validation\Validator`? How does the framework team think about the implications of adding to interfaces, when that could be a breaking change for other implementers of the contract?
- If it should not be fixed, should anything be changed about the Validation Docs page, that demonstrate the usage?
- Or should I chill about type hinting errors "as long as the code works" ; )

### Steps To Reproduce:

1. Run PHP Intelephense 1.8.0 (in my case, in VS Code 1.64.0)
2. Have a line of code that calls `->passes()` on the result of `Validator::make(...)`, e.g.
```
Validator::make($input, $rules)->passes();
```
3. Observe intelephense error "Undefined method 'passes'." on the above line of code

**Comment by driesvints** [comment]
Feel free to attempt a PR, thanks.

**Comment by driesvints** [comment]
> Or should I chill about type hinting errors "as long as the code works"

Btw, mostly this. We'd appreciate PR's to improve docblocks etc but don't actively manage issues for them.
