### ISSUE TITLE
Schema::hasColumn has problems in some scenarios

### ISSUE THREAD

**Issue by OneSeven** [laravel/framework#40842]
- Laravel Version: 8.82
- PHP Version: 8.0.9
- Database Driver & Version: mysql8.0.26

### Description:
After model is set from(), in addGlobalScope, query field does not exist column through Schema::hasColumn is true

### Steps To Reproduce:
```php
User::query()->from('user', 'u')->leftJoin('test','u.id','test.id')->get();
 protected static function booted()
    {
        static::addGlobalScope('orderBy', function (Builder $builder) {
            if (Schema::hasColumn($builder->getModel()->table, 'created_at')) { //user table has no created_at column
                $builder->orderBy($builder->getModel()->table.'.created_at', 'desc');
            }
        });
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
