### ISSUE TITLE
[9.x] Conditionable::when returns Collection when callback or default return empty value (e.g. 0)

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#40877]
- Laravel Version: 9.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8

### Description:
I have the following snippet that calculates a number of serviced hours based on a condition:

```php
$hours = $patient->serviceEntries->whenNotEmpty(
    static fn (Collection $entries) => $calculator->calcRegular($entries),
    static fn () => 0,
);
```

In case the calculator returns 0 hours (or the entries are empty) the expected result would be `0`.
However, the function returns the collection itself, as the `Conditionable` trait returns `$this` when the return value is "empty":

https://github.com/laravel/framework/blob/ca336306542ad8a78c8199be2566e0e83ce3acf9/src/Illuminate/Conditionable/Traits/Conditionable.php#L28-L32

The same logic applies to the unless function as well.

A possible solution is to use `??` instead of `?:`. Not sure if this is a breaking change though (as it has worked before).

### Steps To Reproduce:
```php
$shouldBeZero = collect([1,2,3])->whenNotEmpty(fn () => 0, fn () => 0);
// returns the collection instance (with 1,2,3 as values)
```

**Comment by spaceemotion** [comment]
I just tried the example out in Tinkerwell Web, it correctly returns `0` (as expected). Not sure which version of PHP and Laravel is bundled there, but my local tinker session has the following output:

```
$ php artisan tinker
Psy Shell v0.11.1 (PHP 8.1.2 — cli) by Justin Hileman
>>> collect([1,2,3])->whenNotEmpty(static fn () => 0, static fn () => 0)
=> Illuminate\Support\Collection {#4755
     all: [
       1,
       2,
       3,
     ],
   }
```

**Comment by driesvints** [comment]
Seems like this is more of a feature request as this behavior is unchanged from 8.x? You mention: ` (as it has worked before).` so was this different for you on 8.x?

**Comment by spaceemotion** [comment]
Yes, this happened after the upgrade to v9 yesterday.

**Comment by driesvints** [comment]
@inxilpro is this because of https://github.com/laravel/framework/pull/37632 ?

**Comment by spaceemotion** [comment]
It seems like it is because of #37632.

The original code did not have the `?: $this` appended:

https://github.com/inxilpro/laravel-framework-fork/blob/18e9c8f937861f13bd70669de735fa64b6fab062/src/Illuminate/Collections/Traits/EnumeratesValues.php#L470-L474

**Comment by driesvints** [comment]
@spaceemotion you're correct! Can you send in a PR?

**Comment by spaceemotion** [comment]
I can try this afternoon 👍

**Comment by inxilpro** [comment]
I think the reason I sent this PR to 9.x was because of this change. `when()` had very slightly different behavior across the framework, and that PR was meant to unify the behavior. I'll take a look a little later today to confirm.

**Comment by inxilpro** [comment]
Yeah, if you read #37632, I called this behavior out specifically. The reason for the change was to unify the behavior of `when()` across all implementations—some places used the ternary return and  others didn't.

I agree with @spaceemotion that using the null coalesce operator would be preferable—I just used the ternary shorthand because that was what is used everywhere else in the framework.

**Comment by driesvints** [comment]
Can one of you send in a PR?

**Comment by inxilpro** [comment]
Yeah, I can push up a PR.
