### ISSUE TITLE
Laravel blade components fatal error when random `$attributes` in scope

### ISSUE THREAD

**Issue by dianfishekqi** [laravel/framework#40873]
- Laravel Version: 9.0
- PHP Version: 8.1

### Description:
Having a variable with name `attributes` declared before a component causes fatal `Call to a member function getIterator() on array` error.

compiled blade error line:
`$component = $__env->getContainer()->make(Illuminate\View\AnonymousComponent::class, ['view' => 'jetstream::components.confirmation-modal', 'data' => ['wire:model' => 'deactivateModal']] + (isset($attributes) ? (array) $attributes->getIterator() : []))
`

### Steps To Reproduce:

```blade

@php
    $attributes = [];
@endphp

<x-jet-confirmation-modal wire:model='showModal'>
...
</x-jet-confirmation-modal>

```

**Comment by driesvints** [comment]
Attributes is a reserved keyword that's used to propagates element attributes. You cannot overwrite this. Please see the many examples at https://laravel.com/docs/9.x/blade#component-attributes

**Comment by christianjburger** [comment]
Spent some time debugging this issue after upgrading a project from Laravel 8. In our case it was a property being passed from a controller:

### Steps to reproduce 

```
return view('product/view', [
    'attributes' => []
]);
```
