### ISSUE TITLE
[9.x] Connection could not be established with host smtp and a different port from 465 with tls enabled

### ISSUE THREAD

**Issue by nicolalazzaro** [laravel/framework#40887]
- Laravel Version: 9.0.0
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:
I have created a new application and receive the following linked error when sending an email.

With the same smtp parameters the error does not occur on the same machine but with laravel version 8.83.0.

I then created a new project using the new library "symfony/mailer" but the sending of the email is successful.

Flare error url: [https://flareapp.io/share/B5ZYQWg7#F55](url).

**Comment by driesvints** [comment]
@nicolalazzaro how did you solve this?

**Comment by nicolalazzaro** [comment]
> @nicolalazzaro how did you solve this?

I'm working on it, it's a problem with the certificate of authority for my machine. 
For this reason, the error is not related to Laravel, so I have "closed" this issue.

**Comment by wfern** [comment]
@nicolalazzaro please, if you solve this issue, report it here.

**Comment by mattkingshott** [comment]
I can confirm this happens to me too.

**Comment by driesvints** [comment]
I'll have a look tomorrow.

**Comment by nicolalazzaro** [comment]
Comparing the arguments of the **Transport/Smtp/SocketStream.php** class.
What I noticed is that the argument "tls" is true even when the port is not the correct one, as in the comment below "465".
As a result the prefix ssl:// is added to the host and this generates the above error.

**Laravel**
Create a new Laravel v9.0.0 project

> **CASE 1**
> MAIL_MAILER=smtp
> MAIL_HOST=smtp.mailtrap.io
> MAIL_PORT=2525
> MAIL_ENCRYPTION=tls
>
> _In the above class to the function "initialize" the arguments are as follows:_
>
> #stream: null
> #in: null
> #out: null
> -debug: ""
> -host: "smtp.mailtrap.io".
> **-port: 2525**
> **-tls: true**
> -sourceIp: null
> -streamContextOptions: []

> **CASE 2**
> MAIL_MAILER=smtp
> MAIL_HOST=smtp.gmail.com
> MAIL_PORT=465
> MAIL_ENCRYPTION=tls
>
> _In the above class to the "initialize" function the arguments are as follows:_
>
> #stream: null
> #in: null
> #out: null
> -debug: ""
> -host: "smtp.gmail.com".
> **-port: 465**
> **-tls: true**
> -sourceIp: null
> -streamContextOptions: []

**Blank project**
Create a blank project and install the "symfony/mailer" package:

> **CASE 1**
> smtp://username:password @ smtp.mailtrap.io:2525
>
> _In the above class to the function "initialize" the arguments are as follows:_
>
> #stream: null
> #in: null
> #out: null
> -debug: ""
> -host: "smtp.mailtrap.io"
> **-port: 2525**
> **-tls: false**
> -sourceIp: null
> -streamContextOptions: []

> **CASE 2**
> smtp://username:password @ smtp.gmail.com:465
>
> _In the above class to the function "initialize" the arguments are as follows:_
>
> #stream: null
> #in: null
> #out: null
> -debug: ""
> -host: "smtp.ionos.it"
> **-port: 465**
> **-tls: true**
> -sourceIp: null
> -streamContextOptions: []

Here is a similar case history of the error and useful information: [https://github.com/symfony/symfony/issues/34846#issuecomment-580190302](url)

**Comment by driesvints** [comment]
Can everyone confirm they have their ports/SSL settings set correctly?

**Comment by mattkingshott** [comment]
I have this:

```php
'smtp' => [
    'transport'  => 'smtp',
    'host'       => env('MAIL_HOST', 'smtp.mailtrap.io'),
    'port'       => env('MAIL_PORT', 2525),
    'encryption' => env('MAIL_ENCRYPTION', 'tls'),
    'username'   => env('MAIL_USERNAME'),
    'password'   => env('MAIL_PASSWORD'),
    'timeout'    => null,
],
```

I attempted ports `25`, `2525`, `465` and `587`.

**Comment by nicolalazzaro** [comment]
> I have this:
> 
> ```
> 'smtp' => [
>     'transport'  => 'smtp',
>     'host'       => env('MAIL_HOST', 'smtp.mailtrap.io'),
>     'port'       => env('MAIL_PORT', 2525),
>     'encryption' => env('MAIL_ENCRYPTION', 'tls'),
>     'username'   => env('MAIL_USERNAME'),
>     'password'   => env('MAIL_PASSWORD'),
>     'timeout'    => null,
> ],
> ```
> 
> I attempted ports `25`, `2525`, `465` and `587`.

Does sending the email work if you set the MAIL_ENCRYPTION option to null?

**Comment by driesvints** [comment]
I'm going to close this as there's an easy fix to the problem. We don't document port 2525 anywhere anymore it seems. I see the default settings from Mailtrap are incorrect as they recommend setting encryption to tls for port 2525. I suggest you contact them to fix that.

Thanks all.

**Comment by nicolalazzaro** [comment]
> @nicolalazzaro seems that does it for me. `encryption` needs to be `null` when using `2525` as a port for Mailtrap.

This was not the case in the past, in fact if you copy the configuration from mailtrap it suggests that you set "tls" in the MAIL_ENCRYPTION option.

I think the problem lies in the interfacing with the new symfony library.

In @fabpot's comment below there should be the reason.
https://github.com/symfony/symfony/issues/34846#issuecomment-580190302

**Comment by driesvints** [comment]
> in fact if you copy the configuration from mailtrap it suggests that you set "tls" in the MAIL_ENCRYPTION option.

This seems wrong to me

**Comment by nicolalazzaro** [comment]
> > in fact if you copy the configuration from mailtrap it suggests that you set "tls" in the MAIL_ENCRYPTION option.
> 
> This seems wrong to me

If you use the symfony/mailer package,  add the prefix "ssl//:" to the host only with port 465, otherwise it is not added and the "tls" connection uses "starttls". 

When using a different port it is not enabled to use the "ssl/:" prefix on the host.

This is what I was able to figure out.

<img width="1093" alt="Schermata 2022-02-10 alle 14 23 43" src="https://user-images.githubusercontent.com/26198330/153417051-1ff1bd79-b142-4134-9f93-0af15acdcccd.png">

**Comment by driesvints** [comment]
Yeah this seems like a change in behavior in Symfony Mailer to me. We'd welcome PR's to add something to the upgrade guide 👍

**Comment by nicolalazzaro** [comment]
@driesvints In Laravel 9 if you dump $this->stream->isTLS() in the first line before vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:252 you will always get true, even if the port is different from 465. 

If you create an empty project and install the symfony/mailer package this does not happen, if the port is different from 465 then $this->stream->isTLS() returns false.

Around here should be the problem, unfortunately I'm in the office now and have no way of investigating.

**Comment by driesvints** [comment]
@nicolalazzaro hmm odd. Would be happy to see what your findings are here...

**Comment by nicolalazzaro** [comment]
> I have this:
> 
> ```
> 'smtp' => [
>     'transport'  => 'smtp',
>     'host'       => env('MAIL_HOST', 'smtp.mailtrap.io'),
>     'port'       => env('MAIL_PORT', 2525),
>     'encryption' => env('MAIL_ENCRYPTION', 'tls'),
>     'username'   => env('MAIL_USERNAME'),
>     'password'   => env('MAIL_PASSWORD'),
>     'timeout'    => null,
> ],
> ```
> 
> I attempted ports `25`, `2525`, `465` and `587`.

Port 465 should work correctly though, have you tried using the package "symfony/mailer" outside of laravel and testing sending the email? Otherwise it is a problem related to the configuration of your machine, you can also try gmail smtp which allows you to connect with port 465.
