### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $auth_key ]] in class Pusher\Pusher

### ISSUE THREAD

**Issue by krixnaas** [laravel/framework#40881]
- Laravel Version: 5.3.31
- PHP Version: 7.0.33
- Database Driver & Version: MySQL 

### Description:
Upgrading the Laravel version from 5.2 to 5.3. 
 [Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $auth_key ]] in class Pusher\Pusher

### Steps To Reproduce:
[2022-02-09 14:57:08] production.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $auth_key ]] in class Pusher\Pusher in /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php:850
Stack trace:
#0 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(817): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))
#1 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(789): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('Pusher\\Pusher', Array)
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('Pusher\\Pusher', Array)
#4 /var/www/api/vendor/laravel/framework/src/Illuminate/Container/Container.php(864): Illuminate\Foundation\Application->make('Pusher\\Pusher')

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
