### ISSUE TITLE
hasOneThrough debug on toSql method

### ISSUE THREAD

**Issue by AlexJungCelmer** [laravel/framework#40909]
- Laravel Version:  8.19.0
- PHP Version: 7.4.13
- Database Driver & Version: MySql 5.7.24

### Description:
I have a hasOneThrough relationship.
I have the Models of "Brand", "Modelo", "Product" where "Brands" hasMany "Modelo" and "Modelo" hasMany "Product" the hasOneThrough is in "Product" to get the "Brand" of the "Product". I wanted to debug the generated SQL to be able to create some wheres to bring only where marcas.id = '1'

So to find out what's going on I used toSql() and it just returns 'select * from products'

I find out this by trying to query all products with "brands.id = 1" 

### Steps To Reproduce:
$produtos = Produtos::with(['modelo', 'marcaModelo']);
return $produtos->toSql();

**Comment by AlexJungCelmer** [comment]
If helps, here is my migrations

```
Schema::create('marcas', function (Blueprint $table) {
   $table->id();
   $table->text('nome');
   $table->timestamps();
});
```

```
Schema::create('modelos', function (Blueprint $table) {
    $table->id();
    $table->text('nome');
    $table->foreignId('marca_id')->constrained('marcas');
    $table->timestamps();
});
```

```
Schema::create('produtos', function (Blueprint $table) {
   $table->id();
   $table->text('nome');
   $table->foreignId('modelo_id')->constrained('modelos');
   $table->timestamps();
});
```

**Comment by ManojKiranAppathurai** [comment]
Can you try this.

https://laravel-relation-helper.dev/

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
