### ISSUE TITLE
Getting error when trying to cast a model attribute to enum Call to undefined method App\\Enums\\UserType::from()

### ISSUE THREAD

**Issue by Brotzka** [laravel/framework#40905]
- Laravel Version: 9.0.1
- PHP Version: 8.1
- Database Driver & Version: Mysql8

### Description:
I have a attribute on my user model named "type". This one should be casted to App\Enums\UserType. 

My User-model:

```php
<?php

namespace App\Models;

use App\Enums\UserType;
use FaarenTech\LaravelCustomUuids\Interfaces\HasCustomUuidInterface;
use FaarenTech\LaravelCustomUuids\Models\UuidModel;
use Illuminate\Auth\MustVerifyEmail;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableInterface;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableInterface;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Auth\Authenticatable;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Auth\Passwords\CanResetPassword;

class User extends UuidModel implements
    AuthorizableInterface,
    AuthenticatableInterface,
    CanResetPasswordInterface,
    HasCustomUuidInterface
{
    use
        HasApiTokens,
        HasFactory,
        Notifiable,
        Authenticatable,
        Authorizable,
        CanResetPassword,
        MustVerifyEmail,
        SoftDeletes;

    public function getUuidPrefix(): string
    {
        return "user";
    }


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'type' => UserType::class
    ];
}
```

And my Enum:

```php
<?php

namespace App\Enums;

enum UserType
{
    case CUSTOMER;
    case PARTNER;
    case ADMIN;
}
```

When I want to read one or more entries from my database I get the following error:

> Call to undefined method App\\Enums\\UserType::from()

Of course it's obvious that I have to implement the static method `from()`. But what should this method do/accomplish? The documentation about enum casting  doesn't mention something about a `from()` method.

**Comment by X-Coder264** [comment]
You don't have to implement the `from` method. Eloquent casting works only with backed enums (which have that method by default). Basically what this means is that you have to give a value to each case in your enum for it to work as expected.

[https://www.php.net/manual/en/language.enumerations.backed.php](https://www.php.net/manual/en/language.enumerations.backed.php)

**Comment by themsaid** [comment]
What @[X-Coder264](https://github.com/X-Coder264) said.

**Comment by Brotzka** [comment]
Thanks a lot!

**Comment by henzeb** [comment]
@Brotzka, easy fix, but it is really weird that we have to do this. I really want to be able to make my unit enums castable. I can simply implement the CastsAttributes interface, but I am being blocked by the fact that it checks if is an enum and not if it is a backed enum. I will file a bug report for this.
