### ISSUE TITLE
[9.x] FTP file driver not properly documented and doesn't upload files (worked with v8)

### ISSUE THREAD

**Issue by dizco** [laravel/framework#40910]
- Laravel Version: 9.0.1
- PHP Version: 8.1
- Database Driver & Version:

### Description:
3 things all related to FTP file driver
1. [Upgrade from 8.x to 9.x](https://laravel.com/docs/9.x/upgrade#flysystem-3) should probably document the fact that the Flysystem FTP adapter must now be added manually, as mentionned in #33612 
    ```
    composer require league/flysystem-ftp
    ```
<details>
<summary>Error details</summary>

```
   Error

  Class "League\Flysystem\Ftp\FtpAdapter" not found

  at C:\Users\Gabriel\Documents\Github\dizco\laravel-template\template\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:195
    191▕      * @return \Illuminate\Contracts\Filesystem\Filesystem
    192▕      */
    193▕     public function createFtpDriver(array $config)
    194▕     {
  ➜ 195▕         $adapter = new FtpAdapter(FtpConnectionOptions::fromArray($config));
    196▕
    197▕         return new FilesystemAdapter($this->createFlysystem($adapter, $config), $adapter, $config);
    198▕     }
    199▕

  1   C:\Users\Gabriel\Documents\Github\dizco\laravel-template\template\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:149
      Illuminate\Filesystem\FilesystemManager::createFtpDriver(["ftp", "ftp.kiosoft.ca", "<username>", "<pwd>"])

  2   C:\Users\Gabriel\Documents\Github\dizco\laravel-template\template\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemManager.php:117
      Illuminate\Filesystem\FilesystemManager::resolve("ftp")
```

</details>

2. [FTP Driver configuration](https://laravel.com/docs/9.x/filesystem#ftp-driver-configuration) should also mention that the package must be installed
3. Even after adding the package explicitly, my files are not uploading. This same code used to work for v8. See below

### Steps To Reproduce:
```php
$files = File::allFiles($screenshotsFolderPath);

if ($files) {
    foreach ($files as $file) {
        $filePath = $file->getPathname();

        $this->info("Copying file to {$filePath}@browser-test-results");
        $success = Storage::disk('browser-tests-results')
            ->put($filePath, $file->getContents());
        if (!$success) {
            $this->warn("Unable to copy file (result: {$success})");
        }
    }
}
```

Output:
```
Copying file to tests/Browser/results/localresult/endpoints___-.png@browser-tests-results
Unable to copy file (result: )
Copying file to tests/Browser/results/localresult/endpoints___-en.png@browser-tests-results
Unable to copy file (result: )
```

This is my file disk config:
```php
'browser-tests-results' => [
    'driver' => 'ftp',
    'host' => env('BROWSER_TESTS_RESULTS_FTP_SERVER'),
    'username' => env('BROWSER_TESTS_RESULTS_FTP_USERNAME'),
    'password' => env('BROWSER_TESTS_RESULTS_FTP_PASSWORD'),
    'port' => 21,

    // Optional FTP Settings...
    // 'port' => 21,
    // 'root' => '',
    // 'passive' => true,
    // 'ssl' => true,
    // 'timeout' => 30,
    //'passive' => false,
    //'ignorePassiveAddress' => true,
],
```

**Comment by driesvints** [comment]
I already sent in a PR to document the driver requirement, thanks: https://github.com/laravel/docs/pull/7696

I'll look into the 3rd point now.

**Comment by frankdejonge** [comment]
Hi @dizco,

Could you perhaps provide a little bit more information about your situation. What kind of FTP server are you talking to? Also, have you tried configuring the passive mode?

As a possible route, you could try using Flysystem directly, which should expose the underlying exception which may contain a little bit more information. While your issue is very descriptive, it doesn't have much details that we can use to assess _why_ it is happening.

**Comment by dizco** [comment]
@frankdejonge does this help understand the issue?
![image](https://user-images.githubusercontent.com/7740408/153430090-332d074f-368e-4dd5-a82a-c941846fcdad.png)
![image](https://user-images.githubusercontent.com/7740408/153430106-375b4ad1-c836-42b7-a48e-dfb4a0799526.png)

Perhaps Laravel doesnt set the `root` option https://github.com/thephpleague/flysystem/blob/77adbc9815550b53f2be39a9cfea0807c7002cf2/src/Ftp/FtpConnectionOptions.php#L187
Or the needed configuration has changed, and now `root` is mandatory?

**Comment by dizco** [comment]
I confirm that the fix for my issue was to uncomment the `'root' => ''` config for my FTP disk. Perhaps the only resolution for this issue would be to update the documentation to make sure that the `root` property is not optional.

**Comment by dizco** [comment]
I assume it does yes. I have set my field to empty string and it works now.

**Comment by driesvints** [comment]
This one adds a `/` as the root path so that's a bit different.

**Comment by frankdejonge** [comment]
@dizco flysystem 3.0.4 has been tagged which ships the fix for this on my end. PR #40939 also fixes it from Laravel's end. A composer update would now fix your issue without changes on your end.

**Comment by dizco** [comment]
That's awesome. Thanks everyone for your amazing reactivity!
