### ISSUE TITLE
Custom reset password mail passes token instead of full reset url in callback

### ISSUE THREAD

**Issue by stefanfortuin** [laravel/framework#40925]
- Laravel Version: 8.75
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8.0

### Description:
When making a custom reset password email using the "toMailUsing" function it generates the reset password url incorrectly.
In the callback we only get the reset token instead of the full url.

Making a custom verify email does give the full url.

### Steps To Reproduce:

```php
ResetPassword::toMailUsing(function ($notifiable, $url) {
            return (new MailMessage)
                ->subject('Wachtwoord Herstellen')
                ->line('Je ontvangt deze mail omdat je wachtwoord herstel hebt aangevraagd voor je account.')
                ->action('Wachtwoord herstellen', $url)
                ->line('Deze wachtwoord herstel link verloop in '. config('auth.passwords.'.config('auth.defaults.passwords').'.expire') .' minuten.')
                ->line('Heb je geen wachtwoord herstel aangevraagd, negeer dan deze mail.');
        });
```

The $url variable here will only be the token instead of the full url.
In the toMailUsing function in the VerifyEmail class this is done correctly.

ToMail from ResetPassword.php
```php
public function toMail($notifiable)
    {
        if (static::$toMailCallback) {
            return call_user_func(static::$toMailCallback, $notifiable, $this->token);
        }

        return $this->buildMailMessage($this->resetUrl($notifiable));
    }
```

ToMail from VerifyEmail.php
```php
public function toMail($notifiable)
    {
        $verificationUrl = $this->verificationUrl($notifiable);

        if (static::$toMailCallback) {
            return call_user_func(static::$toMailCallback, $notifiable, $verificationUrl);
        }

        return $this->buildMailMessage($verificationUrl);
    }
```

In VerifyEmail the verificationUrl is build first and then passed in the callback function.
In ResetPassword this is only the token that gets sent back in the callback function.

Possible fix (have never made my first pull request)
Same way as VerifyEmail. Build url first, then use in callback and buildMailMessage().
```php
public function toMail($notifiable)
    {
        $resetUrl = $this->resetUrl($notifiable);
        
        if (static::$toMailCallback) {
            return call_user_func(static::$toMailCallback, $notifiable, $resetUrl);
        }

        return $this->buildMailMessage($resetUrl);
    }
```

**Comment by crynobone** [comment]
This was attempted in the past and caused breaking changes to 3rd party packages using `ResetPassword::toMailUsing()`.

The solution needs to be able return green on https://github.com/crynobone/framework/blob/9.x/tests/Integration/Auth/ForgotPasswordTest.php

**Comment by driesvints** [comment]
We're not changing this because previous attempts broke Nova. But welcoming PR's that can solve this in a non-breaking way.
