### ISSUE TITLE
[9.x] Regex validation rules for array items containing 'or' seperators cause ErrorException on input validation

### ISSUE THREAD

**Issue by jnoordsij** [laravel/framework#40924]
- Laravel Version: 9.0.1
- PHP Version: 8.1.2
- Database Driver & Version: irrelevant

### Description:
Using an or sign (`|`) within a regex validation rule for an array item breaks on Laravel 9.x. This works fine on Laravel 8.x.

It seems somewhere the rules are parsed and the `|` is interpreted as start of another validation rule instead of as being part of the regex rule, causing the parsed regex rule to be `regex:/^(typeA|`. 

Most probably related to https://github.com/laravel/framework/pull/40498.

### Steps To Reproduce:

See https://github.com/jnoordsij/laravel/tree/regex-validation-bug-8.x for the (working) 8.x version and https://github.com/jnoordsij/laravel/tree/regex-validation-bug-9.x for the test breaking on 9.x.

1. clone repo
2. `composer install`
3. `cp .env.example .env.testing`
4. `php artisan key:generate --env=testing`
5. `php artisan test tests/Feature/SimpleRequestTest.php`

Resulting exception:
`ErrorException: preg_match(): No ending delimiter '/' found in ...`

**Comment by jbrooksuk** [comment]
You should wrap your `regex` rule in an array. For example, this will fail:

```php
$v = new Validator($trans, ['x' => 'foo'], ['x' => 'Regex:/^(taylor|james)$/i']);
$this->assertTrue($v->passes());
```

But this will pass:

```diff
-$v = new Validator($trans, ['x' => 'foo'], ['x' => 'Regex:/^(taylor|james)$/i']);
+$v = new Validator($trans, ['x' => 'foo'], ['x' => ['Regex:/^(taylor|james)$/i']]);
$this->assertTrue($v->passes());
```

**Comment by jbrooksuk** [comment]
Sorry, I see this is more nuanced as it's affecting nested rules only. I'll re-open whilst I investigate.

**Comment by jnoordsij** [comment]
The regex rule is actually in array form; I could understand that using something like `'contact.phonenumbers.*.type' => 'regex:/^(typeA|typeB|typeC)$/|required|string'` would be too ambiguous to parse, but the example I provided seems to comply with what the documentation intructs.

**Comment by jbrooksuk** [comment]
Right, this passes in 8.x but fails in 9.x.

```php
$v = new Validator($trans,
    ['x' => ['y' => ['z' => 'james']]],
    ['x.*.z' => [
        'required',
        'string',
        'Regex:/^(taylor|james)$/i'
    ]]
);
$this->assertTrue($v->passes());
```

```
1) Illuminate\Tests\Validation\ValidationValidatorTest::testValidateRegex
preg_match(): No ending delimiter '/' found
```

**Comment by GrahamCampbell** [comment]
Is this issue specific to Laravel 9?

**Comment by rodrigopedra** [comment]
@stevebauman in 8.x  when `$rule` was a regex and reached here:

https://github.com/laravel/framework/blob/4c7cd8c4e95d161c0c6ada6efa0a5af4d0d487c9/src/Illuminate/Validation/ValidationRuleParser.php#L85-L98

It was wrapped into an array, now it reaches here as a string, thus it gets on the first `if` clause that explodes it.

One other thing: if the regex validation rule is a top-level rule it works. It only fails when it is nested.

**Comment by rodrigopedra** [comment]
@stevebauman if we change this line:

https://github.com/laravel/framework/blob/4c7cd8c4e95d161c0c6ada6efa0a5af4d0d487c9/src/Illuminate/Validation/ValidationRuleParser.php#L145

back to as it was in 8.x

~~~php
foreach ((array) $rules as $rule) {
~~~

It works. From the blame this line was changed by you on PR #40498

I will run the tests with this change and report back

**Comment by rodrigopedra** [comment]
@stevebauman Changing it back as of my last comment makes these two tests fail:

~~~
There were 2 failures:

1) Illuminate\Tests\Validation\ValidationRuleParserTest::testExplodeHandlesArraysOfNestedRules
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'users.0.name' => Array (
-        0 => 'required'
-        1 => 'in:"taylor"'
+        0 => Array (...)
+        1 => Array (...)
     )
     'users.1.name' => Array (
-        0 => 'required'
-        1 => 'in:"abigail"'
+        0 => Array (...)
+        1 => Array (...)
     )
 )

/home/rodrigo/code/open-source/framework/tests/Validation/ValidationRuleParserTest.php:171

2) Illuminate\Tests\Validation\ValidationRuleParserTest::testExplodeHandlesRecursivelyNestedRules
Failed asserting that null matches expected 'Taylor Otwell'.

/home/rodrigo/code/open-source/framework/tests/Validation/ValidationRuleParserTest.php:192
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/NestedRules.php:37
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:122
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:96
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:71
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:201
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:187
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:159
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:67
/home/rodrigo/code/open-source/framework/src/Illuminate/Validation/ValidationRuleParser.php:49
/home/rodrigo/code/open-source/framework/tests/Validation/ValidationRuleParserTest.php:209
~~~

I have an appointment in 10 minutes, so I will only be able to look into it further later. Hope it helps you out :)
