### ISSUE TITLE
[9.x] src/Illuminate/Validation/Concerns/ValidatesAttributes.php uses non-existing dependency SpoofCheckValidation

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [laravel/framework#40920]
- Laravel Version: 9.0.1
- PHP Version: 8.1.1
- Database Driver & Version: -

### Description:

Just upgraded to Laravel 9 and one of my tests failed, it seems `src/Illuminate/Validation/Concerns/ValidatesAttributes.php` [see here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php) uses the following non-existing dependency `Egulias\EmailValidator\Validation\SpoofCheckValidation`, that dependency seems to exist in [v2.1](https://github.com/egulias/EmailValidator/tree/2.1.x/src/Validation) but not in [3.x](https://github.com/egulias/EmailValidator/tree/3.x/src/Validation) which laravel 9.x is set to use [^3.1](https://github.com/laravel/framework/blob/e76a1ececa68948fa8dee61149a7f7020ed9d127/composer.json#L23)

### Steps To Reproduce:

Use a validator with the following rule and you will get the following message:

`Error: Class "Egulias\EmailValidator\Validation\SpoofCheckValidation" not found in /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:745`

```php
<?php

$rules = ['email' => 'email:spoof']

```

**Comment by SamuelMwangiW** [comment]
Seems to have been moved to `Egulias\EmailValidator\Validation\Extra\SpoofCheckValidation` in [egulias/EmailValidator/commit#cc695081fd08508604f257172da24c5d98c74132](https://github.com/egulias/EmailValidator/commit/cc695081fd08508604f257172da24c5d98c74132)

**Comment by eduardor2k** [comment]
@SamuelMwangiW Thanks, fixing the namespace and my tests worked perfectly
