### ISSUE TITLE
[9.x] Unable to queue Mailable if using priority

### ISSUE THREAD

**Issue by giggsey** [laravel/framework#40922]
- Laravel Version: 9.0.1 (I think I saw this in 8.x too, but didn't investigate)
- PHP Version: 8.0.14

### Description:

If your Mailable has a priority (assuming the bug in #40916 has been fixed), then the message will fail to queue with:

```
Serialization of 'Closure' is not allowed
```

This is because the priority setting is done through a callback within Mailable.

### Steps To Reproduce:

```php
class MyTestEmail extends Mailable implements ShouldQueue {
    public function __construct() {
        $this->priority(1);
    }
}

\Mail::to('test@example.com')->queue(new MyTestEmail());

```

**Comment by giggsey** [comment]
Moving `priority()` into the build function instead of the constructor works enough as a workaround, so maybe that's fine.

**Comment by driesvints** [comment]
Yes please move this to the build method. Thanks
