### ISSUE TITLE
[9.x] Route::resource doesn't leverage the new Controller Route Groups properly

### ISSUE THREAD

**Issue by pindab0ter** [laravel/framework#40930]
- Laravel Version: 9.0.0
- PHP Version: 8.1.2
- Database Driver & Version: n/a

### Description:

The `Route::resource` method doesn't leverage the new Controller Route Groups properly.

### Steps To Reproduce:

```php
Route::controller(PostController::class)->group(function () {
    // Works:
    Route::resource('posts', PostController::class);

    // Should work, but doesn't:
    Route::resource('posts');
});
```

**Comment by driesvints** [comment]
This isn't supported. If you need to use resources you can't use the controller method.
