### ISSUE TITLE
MessageSent Event return wrong class

### ISSUE THREAD

**Issue by henryavila** [laravel/framework#40959]
- Laravel Version: 9.0.2
- PHP Version: 8.0.12

### Description:
The Event `Illuminate\Mail\Events\MessageSent` return a `Symfony\Component\Mime\Email` as message, but the corrected should be `Symfony\Component\Mailer\SentMessage`.

This object (`Symfony\Component\Mailer\SentMessage`) contains informations about the sent mail that can't be retrieved with  `\Symfony\Component\Mime\Email`.

One example is the MessageId. In `SwiftMailer`, we could define the messageId, but now it's no more possible with `Symfony Mailer`.
The only way to the the message ID now is from `Symfony\Component\Mailer\SentMessage` that is not returned by `MessageSent` event.

One problem with the current class returned is when we use the mailer webhooks to log the mail delivery/open/etc.
If we sent the message using queue, we don't have access to `SentMessage` and the MessageId.

This simple code change solve the problem
```diff
public function send($view, array $data = [], $callback = null)
{
...
if ($this->shouldSendMessage($symfonyMessage, $data)) {
          $sentMessage = $this->sendSymfonyMessage($symfonyMessage);
-         $this->dispatchSentEvent($message, $data);
+         $this->dispatchSentEvent($sentMessage , $data);
            ...
        }
}
```

*ps: In this code sample, I'm considering just the class returned, not the validations required, the chanfe on `MessageSent` class, etc

It's not just more semantical, but give a lot of usefull data that can't be get from another way

**Comment by driesvints** [comment]
We're checking if https://github.com/laravel/framework/pull/40963 could fix things.

**Comment by driesvints** [comment]
Thanks. We'll try to patch this soon!

**Comment by henryavila** [comment]
Amazing. Thanks @driesvints
