### ISSUE TITLE
Global contextual information doesn't included if set context per log

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#40976]
- Laravel Version: 8.83.0
- PHP Version: 8.1.2
- Database Driver & Version: mysql 8.0.28

### Description:

Log doesn't include global context if we are setting context per log.

### Steps To Reproduce:

1) Set the context as written in the [documentation](https://laravel.com/docs/8.x/logging#contextual-information).
(I put this side by side just for example)

![Screenshot from 2022-02-12 15-07-30](https://user-images.githubusercontent.com/7753600/153710667-eda1d9ef-83db-47ed-9c6d-6071265d5b1d.png)

2) Global context is ignored
![image](https://user-images.githubusercontent.com/7753600/153710785-94929f01-1169-4160-808a-11bce426eecd.png)

Could you please explain why the global context is missing?

**Comment by driesvints** [comment]
Seems like the Slack channel doesn't supports this yet. You're always free to attempt a PR. Thanks
