### ISSUE TITLE
Laravel 9 command serve does not use custom .env file

### ISSUE THREAD

**Issue by fbsanchez** [laravel/framework#40978]
- Laravel Version: 9.0.1
- PHP Version: 8.0.15
- Database Driver & Version: php-mysqlnd-8.0.15-1.fc35 connected to mysql:8 (docker)  / sqlite3

### Description:

command `php artisan serve --env=testing` seems not to be working since it is still using default `.env` file instead.

### Steps To Reproduce:

With mysql running using default .env file (configured against mysql)
![image](https://user-images.githubusercontent.com/12999095/153712716-1a33b23a-8666-4a3e-90cf-797ea5a27b61.png)

With mysql stopped using custom .env.testing file (configured against sqlite)
![image](https://user-images.githubusercontent.com/12999095/153712744-476c5733-32e4-48d1-b3df-dbd5aae7fde9.png)

With mysql stopped moving .env.testing to .env file
![image](https://user-images.githubusercontent.com/12999095/153712793-d8ef0666-bcd7-44d5-bb75-17a5ba51c399.png)

Another easy test is not having a `.env` file at all and specify custom one:

![image](https://user-images.githubusercontent.com/12999095/153712853-abd581d8-5a44-4ac2-b38c-286ddb75d467.png)

This time results into a err 500 

```
local.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /tmp/laravel-serve-bug/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
```

Thanks

**Comment by fbsanchez** [comment]
Git repository with the code used to take the screenshots:

https://github.com/fbsanchez/laravel-serve-bug

**Comment by fbsanchez** [comment]
Thought this issue affects `https://github.com/laravel/laravel` instead but I didn't see how to report it :sweat_smile:

**Comment by driesvints** [comment]
@ugorur seems like your PR broke this? https://github.com/laravel/framework/pull/37142. Can you confirm you added a bad negation there?

**Comment by taylorotwell** [comment]
I actually can't recreate the issue. Does your `.env.testing` file actually contain `APP_ENV=testing`. If not - add it - that solves the root issue for me.

**Comment by fbsanchez** [comment]
Hello @taylorotwell by adding `APP_ENV=testing` instead local this seems to be working fine

Thank you!
