### ISSUE TITLE
Could not find package laravel/laravel with version 8 in a version installable using your PHP version, PHP extensions and Composer version.

### ISSUE THREAD

**Issue by amiralidevmoon** [laravel/framework#40985]
- Laravel Version: 9.0.0
- PHP Version: 8.1

### Description:
Hi I wanna install laravel 8 but whenever I execute this command "composer create-project laravel/laravel:^8.0 example-apps" 
I'm getting this error  "Could not find package laravel/laravel with version 8 in a version installable using your PHP version, PHP extensions and Composer version."

but I have all the requirements. what is the issue? thanks

**Comment by Jubeki** [comment]
I am using PHP `8.1.2` and used the command you provided. It then started to install Laravel `v8.6.11`

Still I would recommend you don't create a Laravel 8 Project anymore and start working directly on a Laravel 9 Project.

**Comment by rimace** [comment]
Can confirm it works as expected for me.
What version of PHP are you using? Sorry for asking that, but the Laravel version you provided in the first line is wrong (9.0), so I'm not sure if the PHP version is also a mistake.
I guess your environment does not have all the requirements. What PHP extension have you installed?

**Comment by driesvints** [comment]
Seems like this works as expected. Thanks @Jubeki & @rimace.
