### ISSUE TITLE
When I get an error in validate, it takes me back to the welcome page

### ISSUE THREAD

**Issue by i74ifa** [laravel/framework#40996]
- Laravel Version: 9.0.3
- PHP Version: 8.0.14
- Database Driver & Version: mysql  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

### Description:
I'm working on the api and when I get an error in validate it return to the welcome page
I can solve it temporarily when I enter it in ```try``` and ```catch```

### Steps To Reproduce:
```php
$data = $this->validate($request, [
    'name' => 'string',
    'email' => 'email|unique:users',
]);
```
+ request with email duplicate

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
