### ISSUE TITLE
Laravel tinker and test is broken with enum

### ISSUE THREAD

**Issue by dityaaa** [laravel/framework#40993]
- Laravel Version: 9.0.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0

### Description:
Using enum in test and tinker somehow cannot find the enum class.

### Steps To Reproduce:
First, we need to create enum class
![image](https://user-images.githubusercontent.com/25661768/153797722-e217bfcc-5ba8-457e-94f0-a192cfe4d7fe.png)

Then try to use it in tinker
![image](https://user-images.githubusercontent.com/25661768/153797940-026b7827-028c-4c52-8b4b-59583d24a619.png)

Voila, tinker cannot find the enum class

Try to use enum inside factory, then test is. Error also thrown
![image](https://user-images.githubusercontent.com/25661768/153798145-c174f96d-3f84-4aa0-a9b2-2538586c24f9.png)

Even more confusing, I cannot even quit using the usual exit command. I need to use exit() instead.
![image](https://user-images.githubusercontent.com/25661768/153798036-7ea36168-b933-4e67-a4a0-2d2dda452e12.png)

**Comment by donnysim** [comment]
Works fine for me, maybe try `composer dump`?

**Comment by dityaaa** [comment]
Well well. Apparently I need to take a cup of coffee to see better. Silly me because of short opening tag

![image](https://user-images.githubusercontent.com/25661768/153832740-c9c40ae5-c750-4102-9ec4-4b7a143f95f7.png)
