### ISSUE TITLE
Eloquent `appends` can only use `getXXXAttribute` notation, not `XXX()` (returning an `Attribute` object)

### ISSUE THREAD

**Issue by ijpatricio** [laravel/framework#41004]
- Laravel Version: 9.0.2
- PHP Version: 8.1.2
- Database Driver & Version: mysql 8

### Description:

In an `Illuminate\Database\Eloquent\Model::appends`, it seems that I can't use a method that returns an `Illuminate\Database\Eloquent\Casts\Attribute`.

### Steps To Reproduce:

For instance, on a `User` model, if we have:

```
protected $appends = [
        'isAdmin',
    ];

public function isAdmin(): Attribute
    {
        return new Attribute(
            get: fn() => $someCondition,
        );
    }
```

it will fail with message:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26031459/153830451-8938c2cb-fd69-472f-af93-d3cf42f637cc.png">

If we use the "old way" returning an `Attribute` object, all good. (using `getIsAdminAttribute` as method name)

Let me know if this would be a good issue for me to try to solve, I would gladly work on a PR.

Thanks for all the work ❤️

**Comment by driesvints** [comment]
You need to use the suggestion from above. Thanks @alecpl.

**Comment by ijpatricio** [comment]
It does! 

I feel stupid now! So sorry!!

Thanks!!
