### ISSUE TITLE
No ending delimiter '#' found in file

### ISSUE THREAD

**Issue by GTS-MEGHNI** [laravel/framework#41023]
- Laravel Version: 9.0.2
- PHP Version: 8.1.2
- Database Driver & Version: Mysql 8.0.28

### Description:
The regular expression validation does not work when applying it on nested attributes

### Steps To Reproduce:
Having a payload like : 
```
{
	"a":"123456",
	"b" : {
		"c" : [{
			"d": {
				"test": "123456"
			}
		}]
	}
}
```

Having a form request with the array rules like : 
```
public function rules(): array
    {
        return [
           'b.c.*.d.test' => ['required', 'string', 'distinct',
                'regex:'.GlobalRegex::COLOR_HEX_CODE_PATTERN],
            'a' => ['required', 'string', 'distinct',
                'regex:'.GlobalRegex::COLOR_HEX_CODE_PATTERN],
        ];
    }
}
```
With the constant 
`const COLOR_HEX_CODE_PATTERN = '#^([0-9A-F]{3}|[0-9A-F]{6}|[0-9A-F]{8})$#';
`

**The error occurs when validating the test attribute**

**Comment by driesvints** [comment]
This is fixed in the framework version that'll be released today. Thanks

**Comment by zlodes** [comment]
@driesvints could you please link the commit here?

**Comment by driesvints** [comment]
https://github.com/laravel/framework/pull/40941
