### ISSUE TITLE
Exception thrown when dispatching a job

### ISSUE THREAD

**Issue by utsarajoro** [laravel/framework#41032]
- Laravel Version: 9.0
- PHP Version: 8.1
- Database Driver & Version: mysql & v8

### Description:
This error occurs when i use queue job (at dispatching)
![image](https://user-images.githubusercontent.com/99734788/154067990-5033ede6-3c4f-4830-a722-b145043d1835.png)

**Comment by driesvints** [comment]
Seems to happen in Ignition. Please open an issue on their repo.
