### ISSUE TITLE
PendingRequest breaks if we pass connect_timeout with withOptions

### ISSUE THREAD

**Issue by kalberto** [laravel/framework#41044]
- Laravel Version: 9.0.0
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:

If we create a client with the following code it will not work:
```
$client = Http::timeout(20)
            ->withOptions([GuzzleHttp\RequestOptions::CONNECT_TIMEOUT => 20])
            ->withTracer()
            ->async($this->async);
```

Because the PendingRequest class now has a default connect_timeout in the constructor

### Steps To Reproduce:

Create a new client:
```
$client = Http::timeout(20)
            ->withOptions([GuzzleHttp\RequestOptions::CONNECT_TIMEOUT => 20])
            ->withTracer()
            ->async($this->async);
```
Make a get request:
```
$result = $this->getClient()->get(", [
            'limit' => $limit,
        ]);
```

**Comment by derekmd** [comment]
Related: https://github.com/laravel/framework/issues/40465

A new `connectTimeout()` method was [added](https://github.com/laravel/framework/pull/40466):

https://laravel.com/docs/9.x/http-client#timeout

```php
Http::timeout(20)
    ->connectTimeout(20)
    ->withTracer()
    ->async($this->async);
```
