### ISSUE TITLE
MySQL driver might modify custom casted date

### ISSUE THREAD

**Issue by Naoray** [laravel/framework#41041]
- Laravel Version: 9.0.2
- PHP Version: 8.0.2
- Database Driver & Version: MySQL v5.7, 8 & 10

### Description:
Setting a custom date format which does not follow the American approach and list the year first, will be altered when the related model is saved to the MySQL DB driver. I went ahead and created a PR that adds a failing test in #41040.

### Steps To Reproduce:
```php
class TestModel extends Model
{
    protected $casts = [
        'custom_date' => 'date:d.m.Y'
    ];
}

TestModel::create(['custom_date' => '26.01.2022']);

//  custom_date is set to 20.01.2026 instead of the expected date
TestModel::first()->custom_date->format('d.m.Y') === '26.01.2022'; // false
```

**Comment by driesvints** [comment]
Let's work from your PR, thanks
