### ISSUE TITLE
Class "Illuminate\Log\Logger" not found

### ISSUE THREAD

**Issue by Mishanki** [laravel/framework#41070]
- Laravel Version: 8.83.1
- PHP Version: 8.1.0
- Database Driver & Version: Pgsql

### Description:

**When calling a non-existent routing**

local.ERROR: Class "Illuminate\Log\Logger" not found {"userId":10,"exception":"[object] (Error(code: 0): Class \"Illuminate\\Log\\Logger\" not found at /var/www/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:180)

### Steps To Reproduce:

Call any non-existent endpoint

**Comment by driesvints** [comment]
This will be fixed in the next patch release.

**Comment by Levivb** [comment]
Unfortunately issue isn't really fixed.
It seems to be related to a bug in php's opcache: https://github.com/php/php-src/issues/8164

Will leave a comment there tomorrow
