### ISSUE TITLE
The @aware tag doesn't get default property values from parent components

### ISSUE THREAD

**Issue by nihilsen** [laravel/framework#41076]
- Laravel Version: v8.83.1
- PHP Version: 8.1.1
- Database Driver & Version: MariaDB 10.6.5

### Description:
It appears the new `@aware` tag cannot access default property values from parents. It can only get properties that were explicitly given. If a parent component has a property that was left as the default, the corresponding property in the `@aware` tag of a child component will be `null`.

You will need to repeat the value as a default value in the `@aware` tag in the child component. This is not ideal. Ideally the `@aware` tag would get the default value of whatever parent component it is in, so the same child component can be reused for different parent components.

### Steps To Reproduce:

1. Create the following two anonymous components.

```PHP
<!-- /resources/views/components/parent.blade.php --> 

@props(['name' => 'Mother'])
<ul>
    {{ $slot }}
</ul>
```

```PHP
<!-- /resources/views/components/child.blade.php --> 
 
@aware(['name'])
<li>{{ "$name has a $slot" }}</li>
```

2. Add the following tags, and observe that the one without an explicitly defined name property does not render as you would expect.

```
{{-- Works fine --}}
<x-parent name="Father">
    <x-child>daughter</x-child>
    <x-child>son</x-child>
</x-parent>

{{-- Does not work. The default value "Mother" is not passed on to the child component. --}}
<x-parent>
    <x-child>daughter</x-child>
    <x-child>son</x-child>
</x-parent>
```

**Comment by driesvints** [comment]
This, unfortunately, isn't possible. It's a limitation of `@aware` that we can't overcome. The values in `@aware` need to be the same as in the parent component.

I've sent in a PR to clarify this: https://github.com/laravel/docs/pull/7721
