### ISSUE TITLE
Storage::delete(null) throws a TypeError

### ISSUE THREAD

**Issue by zarunet** [laravel/framework#41102]
- Laravel Version: 9.1.0
- PHP Version: 8.0.15
- Database Driver & Version: n/a

### Description:
Since Laravel 9, calling `Storage::delete()` with a path that resolves to `null`, the following exception is thrown:
```
TypeError: League\Flysystem\Filesystem::delete(): Argument #1 ($location) must be of type string, null given, called in /path/to/project/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 462
```

This is in contrast to Laravel 8 and earlier, which simply returned `false`.

Looking at the code, it looks like Flysystem 3.x has a `string` type-hint on their `delete()` method, which wasn't there in 1.x.

For context, we were using this behavior while deleting models, to make sure related files are removed everytime

```php
/**
 * @property string|null $logo_path
 */
class Company extends Model
{
    protected static function booted()
    {
        self::deleted(function (self $company) {
            Storage::disk('public')->delete($company->logo_path);
        });
    }
}
```

### Steps To Reproduce:

1. Install Laravel 9
2. Run `php artisan tinker`
3. In the Tinker console, run `Storage::delete(null)`

### Possible Fixes:
- in `Illuminate\Filesystem\FilesystemAdapter::delete()`, either...
  - add a null-check and return early
  - call `array_filter()` on `$paths` to eliminate null values
- let the user deal with it, with a note in [the docs](https://laravel.com/docs/9.x/filesystem#deleting-files) warning about this

I can send a PR for either of these choices, depending on what you think would be best.

**Comment by driesvints** [comment]
The docblock of that methods mentions you can only pass a `string` or `array` so there's no bug here. You should pass the correct type in userland.

**Comment by zarunet** [comment]
> You should pass the correct type in userland.

I'm ok with that. However, the behavior *did* change between versions. Should a mention about it be added to the upgrade guide?
