### ISSUE TITLE
Laravel 9 - Error when sending email with priority using MailMessage

### ISSUE THREAD

**Issue by kido1611** [laravel/framework#41119]
- Laravel Version: 9.1.0
- PHP Version: 8.0.8

### Description:
Sending email with priority using Illuminate\Notifications\Messages\MailMessage cause error:
```
Call to undefined method Illuminate\Mail\Message::setPriority()
```
This is because calling wrong function name. Need to replace from `setPriority()` to `priority()` in Illuminate\Notifications\Channels\MailChannel:146

**Comment by Jubeki** [comment]
This was fixed in Laravel 9.0.2 so just run `composer update`

**Comment by kido1611** [comment]
> 

I'm sorry, I'm typo when writing laravel version and the class name. I have edit it.

**Comment by driesvints** [comment]
A PR was sent in for this, thanks @Jubeki
