### ISSUE TITLE
Model Serialization on queue don't  respect attribute cast

### ISSUE THREAD

**Issue by henryavila** [laravel/framework#41111]
- Laravel Version: 9.1.0
- PHP Version: 8.0.15

### Description:
When a model is serialized to add a notification to queue, on unserialize, the relationship of the main model don't respect the cast.

### Steps To Reproduce:
```php
class City extends Model
{
  protected $casts = [
        'id' => 'string'
    ];
  ...
}


class MainModel extends Model
{
  ...
   public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }
   ...
}



class SampleNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(public MainModel $model) { }
}
```

When I try to send this notification with
```php
Notification::route('mail', $email)->notify(new SampleNotification($mainModel));
```

I get
![image](https://user-images.githubusercontent.com/8429941/154745409-bb0f4d9c-7cd5-40cc-a223-ed3170f36c4d.png)
The error is with the generated query:
```diff
SELECT 
  * 
FROM 
  cidades 
WHERE 
  cidades.id IN 
--(3560)
++ ("3560")
```

but if I remove the queue from notification, I have no error
```php
class SampleNotification extends Notification //implements ShouldQueue
{
    //use Queueable;

    public function __construct(public MainModel $model) { }
}
```

Ps: In this case, the ID is indead a string on DB, and can contain letters

**Comment by driesvints** [comment]
Thanks @rodrigopedra

**Comment by henryavila** [comment]
Thanks @rodrigopedra, I forgot about `$keyType` property.
Its working. Thanks again!
