### ISSUE TITLE
[Laravel 9] static::creating didn't happen when boost

### ISSUE THREAD

**Issue by nausixkiz** [laravel/framework#41122]
- Laravel Version: `9.1.0`
- PHP Version:
`
PHP 8.0.15 (cli) (built: Jan 21 2022 04:34:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
`
- Database Driver & Version: `MariaDB 10.6.4-MariaDB Homebrew`

### Description:

I am implementing Uuid model in Laravel 9 like that

My ```App\Traits\ UuidTrait .php```

```

<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

trait UuidTrait
{
    /**
     * Boot functions from Laravel.
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Model $model) {
            $model->primaryKey = 'uuid';
            $model->keyType = 'string';
            $model->incrementing = false;

            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = Str::uuid()->toString();
            }
        });
    }

    /**
     * Get the value indicating whether the IDs are incrementing.
     *
     * @return bool
     */
    public function getIncrementing(): bool
    {
        return false;
    }

    /**
     * Get the auto-incrementing key type.
     *
     * @return string
     */
    public function getKeyType(): string
    {
        return 'string';
    }
}

```

My ```Menu.php``` model

```
<?php

namespace App\Models;

use App\Traits\UuidTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Menu extends Model
{
    use HasFactory, UuidTrait;

    public $incrementing = false;
    protected $primaryKey = 'uuid';
    protected $keyType = 'string';

    protected $fillable = [
        'uuid',
        ...
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'uuid' => 'string'
    ];

    ....
}
```

My `menus` table

```
Schema::create('menus', function (Blueprint $table) {
            $table->uuid()->primary();
            ...
        });
```

After that, when i tried to call `Menu::insert(...)` from my ```MenuSeeder.php``` (No `uuid` field) then got a message "SQLSTATE[HY000]: General error: 1364 Field 'uuid' doesn't have a default value"

Then I tried debugging and realized in `UuidTrait.php` this `creating` event didn't happen

```
... 
protected static function boot()
    {
        parent::boot();
        
        static::creating(function (Model $model) {
            // Nothing happen
            dd("Model creating");
            $model->primaryKey = 'uuid';
            $model->keyType = 'string';
            $model->incrementing = false;

            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = Str::uuid()->toString();
            }
        });
    }
...
```

Did something go wrong here? Everything is still working normally in Laravel 8.x

**Comment by derekmd** [comment]
`Menu::insert()` for many models will not fire Eloquent events. It would only be fired on `Menu::create()` of a single instance.

Given your example `Menu` model, `UuidTrait`, `menus` database table, and an empty `MenuFactory` definition, I was able to call `App\Menu::factory()->create()` and have it successfully create a single model and fill the `uuid` attribute via the Eloquent 'creating' hook.

For composable Eloquent traits, to prevent trait conflicts the typical pattern is to use the `boot{TraitName}()` magic method definition: https://github.com/laravel/framework/blob/a228123bf050167e2faef7c0bdb84bef7ed173bd/src/Illuminate/Database/Eloquent/Model.php#L252

e.g.,

```php
trait HasUuid
{
    protected static function bootHasUuid()
    {
        static::creating(static fn (static $model) => $model->fillUuid());
    }

    public function fillUuid()
    {
        $this->primaryKey = 'uuid';
        $this->keyType = 'string';
        $this->incrementing = false;

        if ($this->getKey() === null) {
            $this->setAttribute($this->getKeyName(), Str::uuid()->toString());
        }
    }
}
```

Given that definition, you could call `fillUuid()` in `MenuSeeder` or have the `MenuFactory` class auto-fill the `uuid` attribute on mass-inserts in a dev environment.

**Comment by driesvints** [comment]
Thanks @derekmd

**Comment by nausixkiz** [comment]
Thanks @derekmd 
It worked like a charm when call `boot{TraitName}()` magic method
