### ISSUE TITLE
When updating with a qualified updated_at column, the current time is still persisted

### ISSUE THREAD

**Issue by PiranhaGeorge** [laravel/framework#41128]
- Laravel Version: 8.64.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0.20

### Description:

When the `updated_at` column is manually updated using a qualified column name, the current time is still persisted. If the column name is not qualified, it works as expected.

### Steps To Reproduce:

This works:
```php
MyModel::whereIn('my_model.id', $ids)->update(['updated_at' => $date]);
```

But this results in the `updated_at` column being set to the current time rather than the provided time:
```php
MyModel::whereIn('my_model.id', $ids)->update(['my_model.updated_at' => $time]);
```

**Comment by driesvints** [comment]
Gonna see how @rodrigopedra's PR goes. Thanks for reporting.
