### ISSUE TITLE
getAwsTemporaryUrl() method does not pass the $options to $client->createPresignedRequest()

### ISSUE THREAD

**Issue by saeeddirect1** [laravel/framework#41143]
- Laravel Version: 9.1.0
- PHP Version: 7.4.4
- Database Driver & Version: MariaDB 10.3

### Description:

**Some Background:** We wanted to create S3 temporaryURL for future such as a temporary signed url that is allowed in a specific time window e.g. tomorrow 00:00 to 23:00.  Upon research, we found put that Aws S3 allows "start_time" value to be set when sending presigned url request.

We know that temporaryUrl() method on the Storage disk takes the $options array and then passes it to `Illuminate/Filesystem/FilesystemAdapter::getAwsTemporaryUrl()` , BUT the thing is that inside the `getAwsTemporaryUrl()`, $options are passed only to the $client->getCommand() and NOT $client->createPresignedRequest()

hence passing 'start_time' key in $options has no effect.

We are currently solving the issue for ourselves by creating custom client and passing the options.

https://github.com/laravel/framework/blob/95b732f30adba8f02fca47e4af625e221691cc81/src/Illuminate/Filesystem/FilesystemAdapter.php#L622

**Comment by driesvints** [comment]
`getAwsTemporaryUrl` doesn't exists in Laravel v9. What method do you mean?

**Comment by driesvints** [comment]
If you pass $options as the third param for `createPresignedRequest` does it work for you?

**Comment by aneesdev** [comment]
> `getAwsTemporaryUrl` doesn't exists in Laravel v9. What method do you mean?

It exists in laravel 8.x.

**Comment by aneesdev** [comment]
> If you pass $options as the third param for `createPresignedRequest` does it work for you?

yes we tried to add it like this and it worked

```php
$uri = $client->createPresignedRequest(
    $command, $expiration, ['start_time' => '1645459200']
)->getUri();
```

**Comment by aneesdev** [comment]
@driesvints same thing in Laravel 9.x... the `temporaryUrl()` method takes $options array but doesn't pass it to `->createPresignedRequest()` method

**Comment by aneesdev** [comment]
@driesvints maybe we can allow a fourth argument $presignedOptions array instead of existing $options which gets merge with:

```php
$command = $client->getCommand('GetObject', array_merge([
            'Bucket' => $adapter->getBucket(),
            'Key' => $adapter->getPathPrefix().$path,
        ], $options)); 
```

**Comment by saeeddirect1** [comment]
> `getAwsTemporaryUrl` doesn't exists in Laravel v9. What method do you mean?

My bad, I meant 8.x

But even in 9.x, $options array is not passed to createPresignedRequest() in temporaryUrl() in AwsS3v3Adapter::class

**Comment by driesvints** [comment]
This sounds more like a feature request. Feel free to send in a pr to 9.x 👍
