### ISSUE TITLE
Cannot rename a timestamp column "Too-big precision 10 specified"

### ISSUE THREAD

**Issue by hailwood** [laravel/framework#41154]
- Laravel Version: 9.1.0
- PHP Version: 8.0.5
- Database Driver & Version: Mysql 8.0.19

### Description:
Attempting to use `$table->renameColumn('service_starts_at', 'sort_date');` on a timestamp column (created using `$table->timestamp('service_starts_at')->nullable();`) fails with the following error

> SQLSTATE[42000]: Syntax error or access violation: 1426 Too-big precision 10 specified for 'sort_date'. Maximum is 6. (SQL: ALTER TABLE funerals CHANGE service_starts_at sort_date TIMESTAMP(10) NULL DEFAULT NULL)

### Steps To Reproduce:

1. Add a new `timestamp()` column to a table via a migration.
2. Attempt to rename the created table in a later `Schema::table`

**Comment by driesvints** [comment]
We don't maintain the code that changes columns, we use Doctrine DBAL for that. Please open an issue on their repo.

**Comment by hailwood** [comment]
Hi @driesvints,

Happy to open an issue there but I'd like to confirm that this really is their problem as Doctrine DBAL doesn't have a native TimestampType so **Laravel maintains [Illuminate\Database\DBAL\TimestampType](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/DBAL/TimestampType.php)**.

In there we [specifically check if the Column definition has a precision](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/DBAL/TimestampType.php#L40-L42), and if it does we add this to the declaration.
Where the issue arises is that Doctrine\DBAL\Schema\Column [defaults the precision to 10 if none is found](https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Column.php#L24).

* [Mysql only supports a precision up to 6 (default 0)](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-syntax.html#:~:text=zero%E2%80%9D%20TIMESTAMP%20value.-,An%20optional%20fsp%20value%20in%20the%20range%20from%200%20to%206%20may%20be%20given%20to%20specify%20fractional%20seconds%20precision.%20A%20value%20of%200%20signifies%20that%20there%20is%20no%20fractional%20part.%20If%20omitted%2C%20the%20default%20precision%20is%200.,-The%20way%20the)
* [Postgres supports a precision of up to 6 (default 0)](https://www.postgresql.org/docs/9.1/datatype-datetime.html#:~:text=By%20default%2C%20there%20is%20no,the%20full%20range%20of%20values.)
* [MSSQL only supports a precision of up to 7 (default 7)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver15#:~:text=Precision%2C%20scale,is%207%20digits.)
* [SQLite ignores the precision anyway](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/DBAL/TimestampType.php#L85)

I believe the appropriate fix is actually on our side to check if the precision is > {6,7} as appropriate and ignore it if so as this would mean we're in fact using the server default precision.

**Comment by driesvints** [comment]
@hailwood we accepted a PR to add that class to cater to people's needs for such a type. But we don't actively maintain it. Please feel free to send in a PR if you think a fix is in order, thanks.
