### ISSUE TITLE
$connection property not working in Migration. 

### ISSUE THREAD

**Issue by Yszty** [laravel/framework#41153]
- Laravel Version: 8.75
- PHP Version: 8.1
- Database Driver & Version: mariadb

### Description:

After declaring `protected $connection = 'mysql_external';`  Schema facade still using default connection, but should declared in `$connection` property. 

So, fix the framework or change documentation... https://laravel.com/docs/8.x/migrations#setting-the-migration-connection

I see the problem exist form laravel 5, and still arent fixed, but issue closed? https://github.com/laravel/framework/issues/31060

Resulting problems:
-php artisan mirgrate:fresh not droping external db tables

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/23386525/155025931-ce3b94fd-4b88-4dbe-b21a-7d2b0961f90c.png)

**Comment by derekmd** [comment]
Mar 2021 comment from Taylor about the state of things: https://github.com/laravel/framework/issues/36596#issuecomment-799784094

`$connection` alone can't be used to configure a secondary database. `Schema::connection()` is required too:

```php
protected $connection = 'mysql_external';

function down()
{
    Schema::connection('mysql_external')->drop('user_settings');
}
```

or:

```php
function down()
{
    Schema::drop('user_settings');
}
```

```
php artisan migrate:rollback --database=mysql_external
```

---

This docs section was added last year: https://github.com/laravel/docs/commit/f3f5a24aa228290d69404f4f4fbdb41a4b0b7d1b

![connect-me-not](https://user-images.githubusercontent.com/823566/155074967-69a6e1b6-3386-4fc2-8f6d-70bcc66db4eb.png)

I'm unsure if the framework behaved this way after looking at branches 7.x, 6.x, 5.8, 5.7, then back to 5.4. I can't find anytime `Illuminate\Database\Migrations\Migration@getConnection()` was explicitly switched into per migration before methods `up()` or `down()` are called. That `$connection` is only used by `DB::transaction()` and `DB::pretend()` but the queries would still run using the default connection (or the `--database` command override.)

A bug fix PR was attempted last year (https://github.com/laravel/framework/pull/35841 https://github.com/laravel/framework/pull/35840) but it lacked important additional tests on a critical feature (:rotating_light:) so it was closed.

I just a crack at it https://github.com/laravel/framework/compare/8.x...derekmd:fix-migrations-connection-property?expand=1 but some code duplication with `Migrator::withConnection()` isn't great. If `$connection` is used, I assume the `migrations` table row should still be using the default connection (or `--database`) so the `Migrator::respository` instance shouldn't be modified per migration.

Either a bug fix PR like mine can be merged to 8.x or the docs snippet needs expanding with `Schema::connection()`.

**Comment by driesvints** [comment]
Thanks @derekmd. I feel like your PR can be attempted. If Taylor rejects it we can maybe look into a docs update.

**Comment by ImChriz** [comment]
I am also affected by this issue. Will this problem be addressed in the near future or should I look for a solution myself?

**Comment by driesvints** [comment]
@ImChriz see the convo above
