### ISSUE TITLE
strtolower() warning in the query builder

### ISSUE THREAD

**Issue by ju5t** [laravel/framework#41151]
- Laravel Version: 9.1.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8

### Description:

A little reluctant to call this a bug but we're seeing warnings in production (hooray for the log deprecations channel!).

```
strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in
./vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 841 (and 840)
```

### Steps To Reproduce:

I didn't see a trace but I'm guessing this is triggered in the `where` method, as we short-cut it often, but I have not been able to pin-point the exact source of the error unfortunately.

**Comment by gguney** [comment]
`    /**
     * Determine if the given operator is supported.
     *
     * @param  string  $operator
     * @return bool
     */
    protected function invalidOperator($operator)
    {
        return ! in_array(strtolower($operator), $this->operators, true) &&
               ! in_array(strtolower($operator), $this->grammar->getOperators(), true);
    }`

This part of the code threw that error. I guess you are giving wrong parameter when you are using where method, can you add your code that generating this error?

**Comment by ju5t** [comment]
I found what's causing this and it is in fact an error from our end, however, I still think this is a bug.

For simplicity, our query looks like this (with expanded variables):

```php
$query->where('some_field', null);
```

The order for the `where` method is:

- Check for invalidOperator(), calling what you've mentioned @gguney. If it's null, `strtolower()` warns about it.
- Later on there is an `is_null` check that catches our null value and passes it onto `whereNull`.

This seems to be fixed in https://github.com/laravel/framework/pull/41091 though. I haven't tested it yet but the check for `! is_string()` should catch it.
