### ISSUE TITLE
Jobs uses a sticky pdo connection, causing "Call to a member function prepare() on null" issues  

### ISSUE THREAD

**Issue by stillzombie** [laravel/framework#41163]
- Laravel Version: 9.1.0
- PHP Version: 8.1.2 
- Database Driver & Version: mysql

### Description:
Having a multi tenant application where jobs are stored on a "landlord" connection and later on processed on a "Tenant" connection, i believe this sticky pdo causes a lot problems,

lets imagine this flow:

on Tenant app we dispatch a job this job is store on the landlord db and when a worker pick up this it process the job and store some data on the tenant connection

So this flow works fine if we run it the first time, running the same process a second time this will cause a pdo error "Error: Call to a member function prepare() on null" btw this was working fine on laravel 8

so if there is any configuration that i can use to stop using the sticky pdo on queues that will be great also i think this is worth mention to comment on the upgrade notes, since there there is nothing about this sticky functionality, this can cause big issues for people running a system when they need to change pdos on queues

### Steps To Reproduce:

* Have a landlord app with their own database
* Have a tenant app with a dinamic connection that it will resolve depending on the tenant being used
* Configure the queues to use createPayloadUsing to pass the right tenant to the job and usee $event->job->payload() to get the right tenant while processing the job
* on tenant app dispatch a job on a landlord connection
* that job will be handle by a worker and write something on the tenant connection
* repeat dispatching a job on a landlord connection
* this will give you a pdo error

**Comment by stillzombie** [comment]
Well digging on the source code i started to doubt that the sticky has something to do, so im a bit lost what is the cause of this error

**Comment by driesvints** [comment]
This sounds like a userland issue rather than a framework issue. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by stillzombie** [comment]
solved thank you indeed was a userland issue,

so in my job i needed to auth a user so i was using 

Auth::loginUsingId($this->userId);

for some weird issue this was causing the issue i mention, i changed my code to use
            
auth()->onceUsingId($this->userId);

this solved my issues maybe cause the sessionguard when using "loginUsingId" it sends some header and make the pdo sticky and using onceUsingId it just set the auth user.
