### ISSUE TITLE
Atomic lock control in multiple environments with the same cache server

### ISSUE THREAD

**Issue by lucaspanik** [laravel/framework#41182]
- Laravel Version: 8.48.1
- PHP Version: 7.4.21
- Database Driver & Version: mysqlnd 7.4.9

#### [TL;DR]

The same cache server used in the production and staging environment prevents the schedule from working correctly with `->onOneServer()` because the generated mutex key to perform an atomic lock does not take into account the environment in which the schedule is running, causing the message `Skipping command (has already run on another server)`.

---

I started an investigation because I've been experiencing problems with `Skipping command (has already run on another server)` in my schedule jobs on the staging server, however, I only have a single stage server.

I checked that for `->onOneServer()` to work, it needs an atomic lock that uses the mutex below to perform the atomic lock:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Scheduling/CallbackEvent.php#L160

![Illuminate/Console/Scheduling/CallbackEvent.php#L160](https://user-images.githubusercontent.com/7035554/155173267-082d6d48-594e-4f6f-bc6c-29f702a6ff69.png)

In search of finding who would be `$this->description`, I confirmed that it would be defined through the `->name()` method when the job is called by the schedule:

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Console/Scheduling/Schedule.php#L153

![Illuminate/Console/Scheduling/Schedule.php#L153](https://user-images.githubusercontent.com/7035554/155173076-a56ffef4-5886-4313-acf0-d5aaa4a353d4.png)

I found that the mutex creates an atomic lock according to the job name and nothing else, that's when I identified the problem, I use the same cache server (Redis) for both my environments, production and staging, both have the schedule of the same job, but running in different environments and in different queues.

Which made me wonder if it would be necessary to add the APP_ENV along with the job name so that the mutex takes into account the environment being generated when using the same cache server and the atomic lock can distinguish which environment it is:

![Illuminate/Console/Scheduling/Schedule.php#L153](https://user-images.githubusercontent.com/7035554/155173481-82c70da2-a0c6-4401-82c4-0934cf3f9dd1.png)

I don't know exactly if the best place for correction would be exactly where I put it. Let me know if you want a PR for this modification.

**Note:** as we are dealing with a single redis server, our queues are prefixed with the environment where they are running, that is, the default queue is actually `production-default` or `staging-default`

### Steps To Reproduce:

1) Generate a job to be executed in `App\Console\Kernel@schedule` with the configuration `->onOneServer()`;
2) Have only one Redis cache server configured;
3) Have two servers (docker) running the application with different APP_ENV (production and staging for example);
4) Have the schedule cron set to write to a log file
```bash
* * * * * cd /path-to-your-project && php artisan schedule:run >> /tmp/schedulelog.txt 2>&1
```
5) You will see in `/tmp/schedulelog.txt` the message `Skipping command (has already run on another server)` on one of the servers (docker).

**Comment by ankurk91** [comment]
The lock key should use the prefix from config

**Comment by lucaspanik** [comment]
> The lock key should use the prefix from config
> 
> https://github.com/laravel/laravel/blob/969ff64e02b5ba316ebfe58aba76ca9ceac34542/config/cache.php#L108

Thanks for the reply @ankurk91 

By default Laravel uses `APP_NAME` for the prefix of the keys, maybe it should already use` APP_ENV`, right?

Or is my case considered an isolated case? Because I don't see the need for a small application to have two Redis servers for both environments (production and staging), only a single Redis server would be able to handle it if Laravel's default configuration could already provide that, in my opinion.

Because` APP_NAME` is less likely to change between environments than `APP_ENV`, after all we are thinking about development cores.

If by default Laravel already defined `APP_ENV` instead of `APP_NAME`, it would suit both scenarios, where the application has only a single Redis server in two environments, or when you have a Redis server for each environment.

I think we've gone from a bug to a standard definition, conceptually...

**Comment by driesvints** [comment]
> Have two servers (docker) running the application with different APP_ENV (production and staging for example);

So I believe this is the actual issue. It's not wanted or intended to use the same resources (a single redis server) for two different environments. The way environments work is like you say, production, staging, etc. But accessing the same resources like a redis server for both production and staging is unwanted imo. You'd never want to share that to prevent your production resources be borked because of something you did in staging.

That being said, this case is indeed one of manually editing your config to your own needs. Therefor this is more of a documentation issue and you're welcome to send in a PR if you like. Thanks
