### ISSUE TITLE
Upgrading Laravel 5.5 to 5.6 gives error on PackageManifest.php 

### ISSUE THREAD

**Issue by krixnaas** [laravel/framework#41185]
- Laravel Version: 5.6.*
- PHP Version: 7.4 

### Description:
Upgrading steps by steps until Laravel version-8. Gives the error in PackageManifest.php. 
I wonder how GitHub file of Laravel https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/PackageManifest.php 
is different than composer installed file "laravel/framework": "5.6.*" on local machine. 

### Steps To Reproduce:
Tried solution for updating as found on Stackoverflow: 
changing files as shown, https://github.com/laravel/framework/commit/65a555105f7812e87888245c8123cad027bf88df

leads to 
\vendor\laravel\framework\src\Illuminate\Container\Container.php:826
    822|
    823|             // If the class is null, it means the dependency is a string or some other
    824|             // primitive type which we can not resolve since it is not a class and
    825|             // we will just bomb out with an error since we have no-where to go.
  > 826|             $results[] = is_null($dependency->getClass())
    827|                             ? $this->resolvePrimitive($dependency)
    828|                             : $this->resolveClass($dependency);
    829|         }

  1   ReflectionParameter::getClass()
      C:\xampp\htdocs\root\betengine\vendor\laravel\framework\src\Illuminate\Container\Container.php:826

  2   Illuminate\Container\Container::resolveDependencies()
      C:\xampp\htdocs\root\betengine\vendor\laravel\framework\src\Illuminate\Container\Container.php:795

Also Tried: 

Composer dump-autoload
downgrading composer versions 

It won't work. 
Any help is appreciated.

**Comment by rodrigopedra** [comment]
Laravel version `5.6` is not supported anymore. 

As such,o I think it is better seek for help on the support channels:

https://laravel.com/docs/9.x/contributions#support-questions

Out of my head, the only thing I can suggest is to check if you are using composer v2 or v1. Probably it doesn't work with v2.

```bash
$ composer self-update --1
```

But I guess you already tried that.

Another tip, as you seem to want to upgrade to a more recent version afterwards is to look at Laravel Shift service. It is a paid service, from a third party, that automates most upgrading changes needed.

Good Luck!

**Comment by krixnaas** [comment]
@rodrigopedra 
Thankyou for your response.
