### ISSUE TITLE
Links containing Response for file downloads are broken

### ISSUE THREAD

**Issue by cooperinho** [laravel/framework#41184]
- Laravel Version: 8
- PHP Version: 7.3

### Description:

I am creating a download link and sending it by Mail to a user, then the button contains a link to the download route with the file id.

I am trying to download a file from Amazon S3 using `Illuminate\Support\Facades\Response;`:
```
// in the controller:

public function download_file(Request $request) {
    $headers = [
        'Content-Type' => 'text/xlsx',
    ];
    return Response::make(Storage::disk('s3')->get($path), '200', $headers);
}
```

But I encounter an odd behavior: The link opens a blank page in the browser, and the address bar says Untitled.
When I refresh the page then the Untitled changes to the correct download link and the file downloads, then the tab quickly closes.

Also, when I `dd(Storage::disk('s3')->get($path));` it outputs the correct file data.

But still, the browser hangs on a blank page until I refresh it. 

### Steps To Reproduce:

* Upload file to S3 (Or might also work locally)
* Add download route in `web.php` :
```
Route::get('/download_route', [FilesController::class, 'download_file/{id}']);
```
* Send a Mail to a user containing a link to the route and the file id in the database (Or however you decide to create the link):

`https://my-website/download_route/<file_id>`

* In the controller handle download like so:
```
public function download_file(Request $request) {
    // get the correct file parameters..

    $headers = [
        'Content-Type' => 'text/xlsx',
    ];
    return Response::make(Storage::disk('s3')->get($path), '200', $headers);
}
```

* Click the download link and you might also see the browser open a blank tab and will not download the file until you refresh it

**Comment by derekmd** [comment]
https://laravel.com/docs/8.x/filesystem#downloading-files

The disk instance has a `download()` method to stream binary downloads and avoid bringing complete file contents into PHP memory:

```php
return Storage::disk('s3')->download($path, $name, [
    'Content-Type' => 'text/xlsx',
]);
```

**Comment by cooperinho** [comment]
I tried that as well, but getting the same behavior: blank page opens with Untitled in the address bar and after refresh then it downloads it and closes the tab

**Comment by lkgitacc** [comment]
I was also thinking about it but then I did not see any warning/error in the browser

**Comment by derekmd** [comment]
It may also be a web browser caching issue from a S3 download failing once earlier. `Response::make(Storage::disk('s3')->get(...))` wouldn't have set HTTP header `Content-Disposition: attachment; filename="filename.xlsx"` which hints to browsers the file should be saved locally. The `download()` method adds this. After changing to call `Storage::disk('s3')->download(...)`, the browser may have returned an earlier cached response.

From a Laravel perspective, there isn't much support that can't be given without digging into these troubleshooting steps:

1. Delete your default browser's local cache and history.
   * Which web browser and version are you using?
2. Try setting your operating system's default browser to an alternate like Mozilla Firefox or MS Edge and see if the same behavior persists.
3. Inspect the HTTP response using browser devtools
4. As previously mentioned, see if the devtools console log shows security error messages related to HTTP(s) or certificate handling
5. Check if `storage/logs/*.log` contains recent exceptions related to Amazon S3.

---

With test file `storage/app/scrobbles.xlsx` and route:

```php
Route::get('download', function () {
    return Storage::download('scrobbles.xlsx', null, ['Content-Type' => 'text/xlsx']);
});
```

Using Firefox I could successfully download that file (wtih no security warnings) when clicking a http://laravel.localhost/download link from outlook.com webmail and then from a local Windows desktop shortcut:

![shirtcort](https://user-images.githubusercontent.com/823566/155436435-b367c3d2-44d0-42d4-b8ea-1cca2216ece3.png)

**Comment by cooperinho** [comment]
Thank you guys, 
@derekmd good to know it did work, so the issue might be something local.
@tben I have checked and it did not show up anything though

**Comment by driesvints** [comment]
Seems like this works for other repliers so I doubt this is a bug with Laravel. Feel free to continue the discussion here if you need help. Thanks @derekmd & @tben
