### ISSUE TITLE
Method flash() not defined in \Illuminate\Contracts\Session\Session

### ISSUE THREAD

**Issue by kellerjmrtn** [laravel/framework#41183]
- Laravel Version: 9.1.0
- PHP Version: 8.1.2
- Database Driver & Version: MariaDB 10.4.13

### Description:
The function `session()` in `\Illuminate\Http\Request` has a return type of `\Illuminate\Contracts\Session\Session`. However, this interface does not define the `flash()` function, which is implemented in `\Illuminate\Session\Store`. In practice, this results in calls like `$request->session()->flash('status', 'Task was successful!');` (as [defined in the docs](https://laravel.com/docs/9.x/session#flash-data)) showing errors in IDEs, and potentially encountering issues if the implementation were to be changed and the `flash()` method not implemented.

### Steps To Reproduce:
```
<?php

namespace App\Http\Controllers;

class MyController extends Controller
{
    public function store(Request $request)
    {
        // perform task ...

        $request->session()->flash('status', 'Task was successful!');
    }
}
```

**Comment by gguney** [comment]
I guess this is userspace issue. I did not get this error.

**Comment by X-Coder264** [comment]
@gguney This is not a "userspace" issue. Laravel 9 (correctly) changed the return typehint of the `session` method from `\Illuminate\Session\Store` to `\Illuminate\Contracts\Session\Session` and that contract indeed does not have the `flash` method on it so it's no wonder that IDEs are complaining about it.

https://github.com/laravel/framework/blob/v8.83.2/src/Illuminate/Http/Request.php#L508
https://github.com/laravel/framework/blob/v9.2.0/src/Illuminate/Http/Request.php#L519

**Comment by driesvints** [comment]
Thanks @X-Coder264

**Comment by Eldair** [comment]
@driesvints Should this method be added to the Session contract?
