### ISSUE TITLE
Timestamp column being updated for all the update() on the data.

### ISSUE THREAD

**Issue by sathiyad** [laravel/framework#41194]
- Laravel Version: Laravel Framework 8.49.2
- PHP Version: 7.4.15
- Database Driver & Version: 10.4.17-MariaDB

### Description:
I have created a customized subscription model (not Laravel Cashier).
the Migration as below
```php
public function up()
{
    Schema::create('subscriptions', function (Blueprint $table) {
        $table->id();
        $table->bigInteger('user_id')->unsigned();
        $table->foreign('user_id')->references('id')->on('users');
        .......
        $table->timestamp('subscribed_at');
        $table->timestamp('expires_at')->nullable();
        $table->boolean('is_active')->default(true);
        $table->timestamps();
    });
}
```
and the user model (User.php) relations and methods connected to subscriptions as below
```php
// user - subscription relation 
public function subscriptions(): HasMany
{
    return $this->hasMany(Subscription::class, 'user_id')->orderBy('subscribed_at', 'asc');
}
.
.
.
public function createSubscription(Plan $plan): Subscription
{   
    $transaction = $this->createTransaction($plan);
    $data = [
        ......
        'subscribed_at' => now(),
        'expires_at' => now()->addDays($plan->validity),
        .......
    ];
    $this->subscriptions()->update(['is_active' => false]);
    return $this->subscriptions()->create($data);
}
```

on this update line : `$this->subscriptions()->update(['is_active' => false]);` the subscribed_at column also gets affected with current timestamp. 
And the table column after migration looks as below.
![Screenshot from 2022-02-23 14-28-07](https://user-images.githubusercontent.com/25609136/155288150-9ac7d0f1-271c-4ceb-9837-6e24872ee8c4.png)

After changing the `subscribed_at` as nullable in migration it's working as expected.

https://laravel.com/docs/9.x/migrations#column-method-timestamp
The document doesn't include this kind of nature for the not null timestamp.

Still, have a question why is the column being affected on every update where the migration was never included to do so?

### Steps To Reproduce:
- Create a migration with  column type timestamp
- Run the migration and check the column on table structure added with default updated at value.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Thanks @MehdiAroui
