### ISSUE TITLE
MySqlGrammar::getBitwiseOperators does not exist.

### ISSUE THREAD

**Issue by JexPY** [laravel/framework#41207]
- Laravel Version: 8.83.2
- PHP Version: 8.0.12
- Database Driver & Version: 10.3.31-MariaDB-0+deb10u1  

### Description:
```
BadMethodCallException
Method Illuminate\Database\Query\Grammars\MySqlGrammar::getBitwiseOperators does not exist.
```

### Steps To Reproduce:
For me, this error was caused while running jobs.

**Comment by driesvints** [comment]
Most likely, you need to restart your queues when deploying new code because this was added to the release you mentioned here: https://github.com/laravel/framework/pull/41112/files#diff-7ea7f749a25a923af9ac94f5fabe101c9bbbc98e448f97eeed773da965042a8cR1327
