### ISSUE TITLE
Redirecting in a global filter

### ISSUE THREAD

**Issue by marius-nyxpoint** [laravel/framework#4120]
Hi,

Should returning a redirect in a global filter work? For example:
```php
App::before(function($request)
{
    if(Auth::check() &&  (strpos($request->path(), 'logout') !== 0)) {
        $user = App::make('SomeUserInterface');
        if(!$user->profileIsCompleted(Auth::user()->id)) {
            return Redirect::route('get-user-account'))->with(array(
                'info_message' => Config::get('messages.account_needs_update')
            ));
        }
    }
});
```
This raises an error saying that it calls getAction on a non-object(I think that $this->current is null). The source code indicated is (Routing/Router.php):
```php
public function currentRouteAction()
	{
		$action = $this->current()->getAction();

		return isset($action['controller']) ? $action['controller'] : null;
	}
``` 

I defined a filter to get around this, however, I'm just curios if this is an issue with laravel or not.
Also, I'm using php5.5. Not sure if this is the problem, but I have an vagrant environment with php5.4 and it works just fine.

**Comment by oytuntez** [comment]
I encountered the same problem this morning. Nothing was changed/updated/modified. It was working a moment ago and then...gone. The redirects are in App::before, which worked perfectly well since the beginning.

I had to disable Redirect calls and use PHP's header. Reached the same stacktrace as @marius-nyxpoint.

**Comment by marius-nyxpoint** [comment]
@oytuntez make sure that the ```composer.lock``` file is in your repository and you are not ignoring it. Laravel does not use a semantic versioning scheme and with each update major things are changing inside of it.

You can always drop the App::before filter, make a custom one and apply it to a group of routes.

But I agree, if redirects inside that filter should work, this is definitively a problem with laravel. If not, it's also a problem because it doesn't raise an exception. I'm reopening the issue, maybe we can get more attention.

**Comment by GrahamCampbell** [comment]
Replaced by middlewares in 5.0.

**Comment by marius-nyxpoint** [comment]
As far as I'm aware, 5.0 is still beta. @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Laravel 5 is actually totally complete now. It officially launches in 2 week's time. All that's left to do is remaining documentation updates and bug fixes. The bug fixes bit requires people to use it. :)

**Comment by marius-nyxpoint** [comment]
Great news! I was looking forward to this. Keep up the good work.

**Comment by oytuntez** [comment]
Thanks for the news, @GrahamCampbell. But, does that mean 4.2 will not be supported any more? No bug fixes?

**Comment by GrahamCampbell** [comment]
Once Laravel 5.0 goes PSR-2, 4.2 will only be getting more major fixes, and no more minor features. That will be happening soonish.

**Comment by oytuntez** [comment]
Okay, thanks again for the update.

**Comment by GrahamCampbell** [comment]
np
