### ISSUE TITLE
EloquentBuilder::addNestedWiths overwrites previous `with()` clauses

### ISSUE THREAD

**Issue by shinsenter** [laravel/framework#41214]
The `EloquentBuilder::addNestedWiths()` overwrites previous `with()` clauses.

https://github.com/laravel/framework/blob/6c0d272a914b43b72056bde1eab9275f6e5093e5/src/Illuminate/Database/Eloquent/Builder.php#L1428~L1430

With the example code below, when `$show_rating_users = true;` the where condition for `ratings` will be overridden:

```php
$query = Product::query();

$query->with([
    'ratings' => function ($sub) {
        return $sub->where('ratings', '>', 4);
    },
]);

if ($show_rating_users) {
    $query->with([
        'ratings.owner' => function ($sub) {
            return $sub->select(['user_id', 'fullname']);
        },
    ]);
}

return $query->take(10)->get();
```

**Comment by driesvints** [comment]
This is intended. It's not meant to call that twice.

**Comment by driesvints** [comment]
I've sent in a PR to the docs to clarify this: https://github.com/laravel/docs/pull/7744

**Comment by shinsenter** [comment]
@driesvints 
Thank you for the comments.
I think the code logic was inconsistent so this was confusing.

The above example is just a simple code block to reproduce the issue. In my project, the `with()` function is called multiple times in different contexts, then unexpected errors occurred.
