### ISSUE TITLE
route resource rename attribute with "um" suffix

### ISSUE THREAD

**Issue by MaoX17** [laravel/framework#41223]
- Laravel Version: 8.75
- PHP Version: 8.1.3
- Database Driver & Version: mariadb 10.5.10

### Description:
with this route:
Route::resource('chiamata', 'App\Http\Controllers\ChiamataController');

i have the follow result:
| App\Http\Middleware\Authenticate                   |
|        | GET|HEAD  | chiamata/{chiamatum}                         | chiamata.show              | App\Http\Controllers\ChiamataController@show                           | web                                                |
|        |           |                                              |                            |                                                                        | App\Http\Middleware\Authenticate                   |
|        | PUT|PATCH | chiamata/{chiamatum}                         | chiamata.update            | App\Http\Controllers\ChiamataController@update                         | web                                                |
|        |           |                                              |                            |                                                                        | App\Http\Middleware\Authenticate                   |
|        | DELETE    | chiamata/{chiamatum}                         | chiamata.destroy           | App\Http\Controllers\ChiamataController@destroy                        | web                                                |
|        |           |                                              |                            |                                                                        | App\Http\Middleware\Authenticate                   |
|        | GET|HEAD  | chiamata/{chiamatum}/edit                    | chiamata.edit              | App\Http\Controllers\ChiamataController@edit  

as you can see the parameter "chiamata" is replaced with "chiamatum"

is it a bug?

Thank you

**Comment by driesvints** [comment]
We use the doctrine inflector for this. If you think this is an issue please open an issue on their repo.

**Comment by rodrigopedra** [comment]
@MaoX17 

As a workaround you can override the parameter inflection:

~~~php
Route::resource('chiamata', 'App\Http\Controllers\ChiamataController')
    ->parameter('chiamata', 'chiamata');
~~~

see: https://laravel.com/docs/9.x/controllers#restful-naming-resource-route-parameters
