### ISSUE TITLE
Possible bug/dynamic behaviour in .env and schedule:run

### ISSUE THREAD

**Issue by bernardwiesner** [laravel/framework#41241]
- Laravel Version: 8.31.0
- PHP Version: 7.4

### Description:
If this is a known issue feel free to close this.

Different .env files get loaded when running `php artisan schedule:run` and when running a command directly if you have set `APP_ENV` and have a corresponding environment file.

So for example if you have .env 2 files:

`.env`
```php
APP_ENV=production
TEST_VARIABLE=A
...
```

`.env.production`
```php
APP_ENV=production
TEST_VARIABLE=B
...
```
And I have a task such as `php artisan foo`, scheduled to run every 1 min, the schedule:run will pass the APP_ENV=production to the child job and it will load the `.env.production` with the TEST_VARIABLE=B, while if I run the `php artisan foo:bar` directly in console, it will use the `.env` with TEST_VARIABLE=A.

### Steps To Reproduce:

1- Create new task such as FooTask.php
2- Add task to console Kernel as a scheduled task
3- create .env and .env.production with contents as above
4- run `php artisan schedule:run` -> Task uses TEST_VARIABLE=B
5- run `php artisan foo` -> Task uses TEST_VARIABLE=A

I checked the source code and this is due to this part:
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php#L51-L57

On `php artisan foo` the APP_ENV is null at this point so it returns early. However with `php artisan schedule:run` after it starts up and runs the sub task `foo` it does pass the APP_ENV and uses the different .env file.

This causes unexpected behaviors depending on your deployment, as you might not always be replacing .env with .env.production.

**Comment by WebKenth** [comment]
@bernardwiesner  what is inside the `foo` command? sounds like it doesn't take the environment type into consideration, maybe it is loaded outside of a normal console command scope?

The `schedule:run` is expected to adhere to the APP_ENV type

it is expected behaviour for the application to load .env files based on `APP_ENV`

Documentation quote: 

> Before loading your application's environment variables, Laravel determines if either the `APP_ENV` environment variable has been externally provided or if the `--env` CLI argument has been specified. If so, Laravel will attempt to load an `.env.[APP_ENV]` file if it exists. If it does not exist, the default .env file will be loaded.

https://laravel.com/docs/9.x/configuration#additional-environment-files

**Comment by bernardwiesner** [comment]
@WebKenth 
Yes docs are correct, however the issue relates to schedule:run passing the APP_ENV to the foo task, however when running foo task from console outside schedule:run there is no APP_ENV being passed, causing the dynamic behavior.

If I ssh into the server and do `php artisan foo` there is no APP_ENV being passed.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by WebKenth** [comment]
> @WebKenth Yes docs are correct, however the issue relates to schedule:run passing the APP_ENV to the foo task, however when running foo task from console outside schedule:run there is no APP_ENV being passed, causing the dynamic behavior.
> 
> If I ssh into the server and do `php artisan foo` there is no APP_ENV being passed.

Which leads me to believe the command `foo` is not properly populated if it does not pass the environment type

They are running in two different contexts

I can expand your theory, i just added 3 .env files and ran a few tests

if you add a `.env.dev`
and run `php artisan foo --env="dev"` it will grab the `.env.dev` file
running `php artisan foo --end="production"` grabs the `.env.production`
running `php artisan foo` grabs `.env`

**Comment by bernardwiesner** [comment]
Ok so this is expected? I would think it's better to always pass same .env regardless if running from console directly or from scheduler.

**Comment by bernardwiesner** [comment]
@WebKenth 
Yes you are correct, the issue comes with the schedule:run. Did you try the scenario I demonstrated above?

Have your task inside a schedule and then run the scheduler with `pho artisan schedule:run`, it will use the .env.production rather than the .env.

The issue relates to schedule:run executing foo task vs running foo task directly, behavior is different, when you would expect it to be the same.

**Comment by WebKenth** [comment]
> @WebKenth Yes you are correct, the issue comes with the schedule:run. Did you try the scenario I demonstrated above?
> 
> Have your task inside a schedule and then run the scheduler with `pho artisan schedule:run`, it will use the .env.production rather than the .env.
> 
> The issue relates to schedule:run executing foo task vs running foo task directly, behavior is different, when you would expect it to be the same.

I would expect the `schedule:run` to take the .env.production

not the .env file as that would be a fallback environment file

When you manually decide to run `php artisan foo` you are running in a context outside of the application and must therefore specify which environment you wish to run it as (hence the --env option)

If you run your task via a scheduler, you expect the scheduler to run with an application context so it behaves the way the application behaves

When you made the choice to create a `.env.production` you decided to adhere to this design

If you instead only had one `.env` file this would not be an issue for you

While i do agree it could be documented better with examples, i don't think there is anything inherently wrong with how it is working at the moment

As Laravel is a framework designed to work with both simple and very complex application structures this is an acceptable behaviour :)

**Comment by bernardwiesner** [comment]
@WebKenth 
I understand your point, but let me give you an example where this becomes an issue.

Let's say inside your Kernel file you are checking redis and depending on that you execute certain tasks. Inside .env your cache driver is set to file while inside .env.production it's set to redis.

Do you see the issue? When schedule:run starts it will run inside of .env context, and check file for cache, while when it runs child tasks it will switch context and suddenly pass .env.production and use redis driver for the tasks!

This is a lot of unexpected dynamics.

**Comment by WebKenth** [comment]
> @WebKenth I understand your point, but let me give you an example where this becomes an issue.
> 
> Let's say inside your Kernel file you are checking redis and depending on that you execute certain tasks. Inside .env your cache driver is set to file while inside .env.production it's set to redis.
> 
> Do you see the issue? When schedule:run starts it will run inside of .env context, and check file for cache, while when it runs child tasks it will switch context and suddenly pass .env.production and use redis driver for the tasks!
> 
> This is a lot of unexpected dynamics.

I am confused, you say `schedule:run` switches context, it does not ? it run's with the same application context and a regular http request. unless you decide to switch the context manually by running `php artisan schedule:run --env="development"` doing runtime if it switches context that is application logic and laravel is not responsible for your custom conventions

running a `php artisan` without specifying your environment is not how you should do it, be explicit! ( this applies when you decided to use multiple .env files in your project )

It is not unexpected behaviour, it is in fact documented and it is up to you to use the methods you see fitting to your environment

You decided to use the `.env.production` method and that means you have enabled multi environment files for your project. This is a convention change which requires you to change your behaviour and expectations.

You could easily change this behaviour by just using a single `.env` and have your deployments handle the swapping of environment variables for production vs staging vs development servers

It is also strange behaviour to have one application running in multiple environment contexts on the same setup. The multiple .env files allow you to do this, but it comes at an increased complexity which you have run into.

**Comment by bernardwiesner** [comment]
@WebKenth 
Maybe there is still a misunderstanding. Not sure how to get it across correctly.

`php artisan schedule:run` uses .env by default. However when it executes the tasks declared inside Kernel it has the context of .env that includes APP_ENV, so that is passed to the task and the task is executed as if you were to run it with `APP_ENV=production php aritsan foo`.

So schedule:run uses .env for executing the tasks declared inside Kernel, but the tasks in a different process use .env.production. 

schedule:run
-> Kernel.php (.env)
    -> FooTask.php (.env.production)

**Comment by WebKenth** [comment]
@bernardwiesner  That is not how you described it in your description
![image](https://user-images.githubusercontent.com/13419123/155693721-0d986c2a-a402-4467-b267-4ebe88c67a75.png)
You have swapped the logic

**Comment by bernardwiesner** [comment]
@WebKenth 
Yes the scenario I am giving now is a different one, but it relates to the same issue of dynamic context related to .env

**Comment by WebKenth** [comment]
> @WebKenth Yes the scenario I am giving now is a different one, but it relates to the same issue of dynamic context related to .env and scheduler

New issue then

This issue describes a stand alone command running in a different environment than the `schedule:run` context

As is the expected behaviour

You are now swapping your original statement to say that `schedule:run` in fact runs in the wrong context

These are two seperate accusations and issues

**Comment by bernardwiesner** [comment]
@WebKenth 
Well sure I can open another issue with that scenario. To me they are similar issues related to schedule:run switchings environment context when running child tasks. I would expect if I run schedule with .env that child tasks are also run with .env.

I don't really see how the second scenario is much different from the first, it relates to the exact same issue.

**Comment by bernardwiesner** [comment]
@WebKenth 
I appreciate though you took the time to respond and follow up, however I am not sure if there is much interest in getting this fixed so I will not open another issue.
