### ISSUE TITLE
Mail subject does not work when using queue:work

### ISSUE THREAD

**Issue by edsonfeimberg** [laravel/framework#41240]
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version: mysql

### Description:

I just experienced a problem where for no reason the subject of my emails was not being sent. Googling i found this resource:

https://stackoverflow.com/questions/61836901/laravel-mailable-subject-not-working-if-i-queue-the-mailable

Where it was stated that the problem could be solved by using queue:listen instead of queue:work. Is there an specific reason for why mail subject shouldn't work when using queue:work especially since it is known to have better performance than queue:listen?

**Comment by derekmd** [comment]
You'll need to share your mailable class code and the `Mail` facade call.

The below example shows the expected email subject line is correctly set for both commands `queue:work` and `queue:listen`.

---

### App\Mail\Foo.php

```php
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class Foo extends Mailable
{
    use Queueable, SerializesModels;

    public function build()
    {
        return $this->subject('foo')->view('mail.foo');
    }
}
```

### resources/views/mail/foo.blade.php

```html
bar
```

### .env

```
MAIL_MAILER=log
```

### Laravel Tinker

```php
Mail::to('baz@example.com')->queue(new App\Mail\Foo);
```

### command line

Run `php artisan queue:work`, then repeat the above step and run `php artisan queue:listen`.

### storage/logs/laravel.log

This email header/body is logged using both commands.

```
From: Laravel <no-reply@example.com>
To: baz@example.com
Subject: foo
MIME-Version: 1.0
Date: Fri, 25 Feb 2022 01:00:18 +0000
Message-ID: <e804f4d5cab4d4661ab669c8b83cc03e@example.com>
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

bar  
```

---

Keep in mind if you're using `Mail::fake()` and `Mail::assertSent()`/`assertQueued()` while testing, the mailable instance `build()` method must manually be called to make assertions on the subject line.

```php
use App\Mail\Foo;

Mail::fake();

Mail::to('baz@example.com')->queue(new Foo);

// this fails
Mail::assertQueued(Foo::class, function ($mail) {
    // build() hasn't been called so the subject isn't filled yet
    return $mail->subject === 'foo';
});

// this passes
Mail::assertQueued(Foo::class, function ($mail) {
    return $mail->build()->subject === 'foo';
});
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Thanks @derekmd
