### ISSUE TITLE
Cannot send mailgun email with only cc or bcc and without to

### ISSUE THREAD

**Issue by Eldair** [laravel/framework#41253]
- Laravel Version: 9.x
- PHP Version: 8.x

### Description:

It is imposible to send mailgun email without specifying `to`. The issue is here:
```
protected function createMailgunTransport(array $config)
    {
        $factory = new MailgunTransportFactory();

        if (! isset($config['secret'])) {
            $config = $this->app['config']->get('services.mailgun', []);
        }

        return $factory->create(new Dsn(
            'mailgun+api',
            $config['endpoint'] ?? 'default',
            $config['secret'],
            $config['domain']
        ));
    }
```
It should use `mailgun+https`. I am not sure if this would be a breaking change but otherwise I can make a PR.

### Steps To Reproduce:

Try to send mailgun email without `to`

**Comment by driesvints** [comment]
Why would you send an email without specifying "to"?

**Comment by driesvints** [comment]
We also used the API of Mailgun in Laravel v8 so not sure how this would ever have worked? 

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Mail/Transport/MailgunTransport.php#L74

**Comment by Eldair** [comment]
Example - when sending reports to clients who shouldn't see each other's emails. Shouldn't sending to bcc (or cc) only be available in any case?

I am not sure how it worked in L8 but it did work.

Anyhow, is there some specific reason for using `mailgun+api` instead of `mailgun+https`?

**Comment by Eldair** [comment]
Hi, I think the reason that it worked than (and also works with `mailgun+https` transport) is that L8 used `/messages.mime` endpoint and `mailgun+api` uses `/messages`.

**Comment by driesvints** [comment]
Does it work for you is you use `mailgun+smtps`?

**Comment by Eldair** [comment]
Nope, just `mailgun` or `mailgun+https`
`mailgun+smtps` requires some different auth judging by the exception

**Comment by driesvints** [comment]
I think you're correct. I'm a bit concerned with changing it right now in how people's credentials will be handled with the new protocol. 

Can you send attachments with the https protocol? I've been comparing the https and api ones with each other but I don't see anything about attachments in the https one:

https://github.com/symfony/mailgun-mailer/blob/6.0/Transport/MailgunHttpTransport.php
https://github.com/symfony/mailgun-mailer/blob/6.0/Transport/MailgunApiTransport.php

**Comment by Eldair** [comment]
Yeah, it works (tested with 1 png file)

**Comment by driesvints** [comment]
Thanks, I've sent in a PR for this: https://github.com/laravel/framework/pull/41255
