### ISSUE TITLE
Defining Typed Collection that starts Empty

### ISSUE THREAD

**Issue by jamespavett** [laravel/framework#41252]
- Laravel Version: 9.2.0
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:

To be honest, I'm not sure if this is an issue directly or how I am using the functionality. I raised this issue on the Larastan repo before being instructed that this is related to Laravel directly.

Basically I am typehinting a Support Collection as containing <int, DummyType>

However in the constructor I want to initialise this to an empty collection, and then add DummyType elements to it late on. Is there a way to probably typehint this so that there aren't inspection errors.

Currently I am getting:

`Property App\Services\DummyType Service::$generatedData (Illuminate\Support\Collection<int, App\Services\DummyType>) does not accept Illuminate\Support\Collection<*NEVER*, *NEVER*>.`

Or (when initialising collection via collect helper):

```
Unable to resolve the template type TKey in call to function collect
Unable to resolve the template type TValue in call to function collect
```

Not sure if I am trying to do something wrong here, or if there is something wrong in the background.

### Steps To Reproduce:

```
   /**
     * The retrieved query data
     *
     * @var \Illuminate\Support\Collection<int, object>
     */
    private Collection $queryData;

    /**
     * The generated combined data
     *
     * @var \Illuminate\Support\Collection<int, DummyType>
     */
    private Collection $generatedData;

    /**
     * Constructor.
     */
    public function __construct()
    {

        $this->generatedData = new Collection();

        // or

        $this->generatedData = collect();
    }
```

**Comment by jamespavett** [comment]
Just something weird I have noticed. If I change the typehint to (removing the int bit):

```
    /**
     * The generated combined data
     *
     * @var \Illuminate\Support\Collection<DummyType>
     */
    private Collection $generatedData;
```

This remove the error when initialising the Collection. However then I get undefined property errors everywhere.

**Comment by nunomaduro** [comment]
Please raise this issue on the Larastan repository.

**Comment by jamespavett** [comment]
Hi @nunomaduro, I raised it on there earlier and it was closed straight away as a Laravel issue.

**Comment by nunomaduro** [comment]
We have opened the Larastan's discussions tab for this kind of things. Can you raise your issue there?

**Comment by jamespavett** [comment]
Apologies, have raised it there now
