### ISSUE TITLE
Storage::append always make redundant bytes

### ISSUE THREAD

**Issue by tungvn** [laravel/framework#41259]
- Laravel Version: 8.83.0
- PHP Version: 7.4.28
- Database Driver & Version:

### Description:
The method `Storage::append` always add redundant bytes and make file broken when handle the chunk files.

### Steps To Reproduce:
1. Make a simple form with `Dropzone`. Make sure it support chunk file.
2. Create a controller to handle chunk upload file. It may look like the below
```
$file = $request->file('file');
$path = collect([
    'imports',
    (string)Str::of($model)->plural()->slug(),
])->join('/');
if ($request->dzchunkindex == 0) {
    $filepath = $file->storeAs($path, $request->dzuuid);
} else {
    $filepath = collect([
        $path,
        $request->dzuuid,
    ])->join('/');

    if (!Storage::exists($filepath)) {
        throw new NonExistsFileChunksException;
    }

    Storage::append($filepath, $file->getContent());
}

if ($request->dzchunkindex == $request->dztotalchunkcount - 1) {
    $fileWithClientOriginName = collect([
        $path,
        $file->getClientOriginalName(),
    ])->join('/');
    if (Storage::exists($fileWithClientOriginName)) {
        Storage::delete($fileWithClientOriginName);
    }

    Storage::move($filepath, $fileWithClientOriginName);

    return $fileWithClientOriginName;
}

return $filepath;
```
3. The result file is always bigger than the origin one. The number of redundant bytes is equal with the number of chunks file minus 1. It's really problems with the zip files because it will be broken.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
