### ISSUE TITLE
Email notifications sent to anonymous users fail silently when using MailChannel FCQN

### ISSUE THREAD

**Issue by thejager** [laravel/framework#41261]
- Laravel Version: 8.79.0
- PHP Version: 8.1.2
- Database Driver & Version: N/A

### Description:
When you try to send an email notification to an anonymous user, and use `MailChannel::class` instead of `'mail'` for the route, it will not send anything nor notify you of any issues.

### Steps To Reproduce:

Create a notification as such:

```php
class WelcomeNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function via(): array
    {
        return [MailChannel::class];
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        // Omitted for brevity, not relevant
    }
}
```

Now sent the notification as such:

```php
(new AnonymousNotifiable())
    ->route(MailChannel::class, 'johan@example.com')
    ->notifyNow(new WelcomeNotification());
```

Intuitively to me, this should work. But nothing happens, it will "fail" silently. I only figured out what was wrong after diving into the whole notification system and found this:

```php
public function send($notifiable, Notification $notification)
{
    $message = $notification->toMail($notifiable);

    if (! $notifiable->routeNotificationFor('mail', $notification) &&
        ! $message instanceof Mailable) {
        return;
    }
    
    // ...
}
```

It just returns if there's no `'mail'` key defined in the `AnonymousNotifiable::$routes`. I feel like this function should:

1.  Check `routeNotificationFor(MailChannel::class)`
2. Throw an error instead of return if there is no `'mail'` or `MailChannel::class` route

or am I missing something? Apologies if this expected behavior.

**Comment by derekmd** [comment]
As [documented](https://laravel.com/docs/8.x/notifications#on-demand-notifications), the `'mail'` alias should be used:

```php
(new AnonymousNotifiable)
    ->route('mail', 'johan@example.com')
    ->notifyNow(new WelcomeNotification);
```

You could also change `WelcomeNotification` from a `MailMessage` into `Mailable` and set the `route(MailChannel::class, ...)` recipient using this example: https://laravel.com/docs/8.x/notifications#mailables-and-on-demand-notifications

---

A PR on `MailChannel` could be submitted to make either work, adding a `MailChannel::class` fallback if no `'mail'` recipients are found:

```php
class MailChannel
{
    // ...

    /**
     * Get the notification routing information for the mail driver.
     *
     * @param  mixed  $notifiable
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return mixed
     */
    protected function routeNotificationFor($notifiable, $notification)
    {
        return $notifiable->routeNotificationFor('mail', $notification) ??
            $notifiable->routeNotificationFor(static::class, $notification);
    }

    public function send($notifiable, Notification $notification)
    {
        $message = $notification->toMail($notifiable);

        if ($message instanceof Mailable) {
            return $message->send($this->mailer);
        }

        if (! $this->routeNotificationFor($notifiable, $notification)) {
            // throwing an exception here would be a breaking change that could only target 10.x
            return;
        }

        // ...
    }

    protected function getRecipients($notifiable, $notification, $message)
    {
        if (is_string($recipients = $this->routeNotificationFor($notifiable, $notification))) {
            $recipients = [$recipients];
        }

        // ...
    }
```

Given:

```php
Notification::route('mail', 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

vs.

```php
Notification::route(MailChannel::class, 'taylor@example.com')
            ->notify(new InvoicePaid($invoice));
```

the PR would need to make a sales pitch that the latter should be a support.

**Comment by driesvints** [comment]
This is a feature request. Thanks @derekmd

**Comment by thejager** [comment]
Yea I realise now it is. Apologies.
