### ISSUE TITLE
The new accessor syntax does not work with API resources

### ISSUE THREAD

**Issue by saeed-bd** [laravel/framework#41260]
- Laravel Version: 9.1.0
- PHP Version: 8.1.0
- Database Driver & Version: mysql8

### Steps To Reproduce:

Model : 
```php
protected $appends = ['name'];

   protected function name(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => 'foo',
            set: fn ($value) => strtolower($value),
        );
    }

```

CategoryResource:
```php
 public function toArray($request)
    {
        return [
            'type' => $this->resource->type,
            'name' => $this->resource->name,
        ];
    }
```

CategoryCollection:
```php
 public function toArray($request)
    {
        return [
            self::$wrap => CategoryResource::collection($this->collection)
        ];
    }
```

Controller:
```php
        return new CategoryCollection(PostCategory::query()->get());
```

result : 
```
{
    "categories": [
        {
            "type": "news",
            "name": null
        }
    ]
}
````

**Comment by derekmd** [comment]
Ensure your model imports the `Attribute` class:

```php
use Illuminate\Database\Eloquent\Casts\Attribute;
```

When this import doesn't exist, the cast method's return type actually becomes the root `\Attribute` class that PHP8+ defines: https://www.php.net/manual/en/language.attributes.php Eloquent is ignoring `protected function name(): Attribute` because the return type inspected is `\Attribute`, not `\Illuminate\Database\Eloquent\Casts\Attribute`.

https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor may need a big fat alert for this one.

**Comment by saeed-bd** [comment]
The problem is, that it does work outside API resources and it's working just fine.
However, the old syntax continues to work in API resources.
The problem arises when I use the new syntax for attributes. In this case when I access an attribute inside api resource, it returns null.

**Comment by derekmd** [comment]
### App\Models\User

```php
namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    protected $fillable = ['name', 'email'];
    protected $appends = ['name'];

    protected function name(): Attribute
    {
        return new Attribute(get: fn () => 'bar');
    }
}
```

### App\Http\Resources\UserResource

```php
namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'name' =>  $this->name,
            'email' => $this->email,
        ];
    }
}
```

### App\Http\Resources\UserCollection

```php
namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class UserCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return [
            'wrap' => UserResource::collection($this->collection)
        ];
    }
}
```

### resources/web.php

```php
Route::get('json-resource', function () {
    \Illuminate\Http\Resources\Json\JsonResource::withoutWrapping();

    return new \App\Http\Resources\UserCollection(\App\Models\User::get());
});
```

### ✔️ Endpoint JSON output

```json
{
  "wrap": [
    {
      "name": "bar",
      "email": "foo@example.com"
    },
    {
      "name": "bar",
      "email": "foo2@example.com"
    }
  ]
}
```

The model attribute `name()` get mutator is successfully called. You'll need to share your full class definitions, not just the snippets, to show if there is a problem with the framework implementation.
