### ISSUE TITLE
[9.x] Mocking aliases doesn't mock abstract

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#41264]
- Laravel Version: 9.2.0
- PHP Version: 8.1.3
- Database Driver & Version: N/A

### Description:

Using mocking methods in testing with service alises like `cache` or `files` will return a Mockery exception not extending the service class. This is disruptive to classes who expect a service injection.

This makes these method useless when helpers use aliases to mock.

### Steps To Reproduce:

Bring this simple test.

```php
public function test_cache_expects_store(): void
{
    $this->mock('cache')->expects('foo')->returnUsing(function () {
        // ...
    });

    $this->app->make(TestClass::class);
}

class TestClass
{
    public function (protected Factory $cache)
    {
        // ...
    }
}
```

The error returned:

```
TypeError : Tests\TestClass::__construct(): 
Argument #1 ($factory) must be of type Illuminate\Contracts\Cache\Factory, Mockery_0__cache given
```

## Probable fix

The `Illuminate\Foundation\Testing\Concerns\InteractsWithContainer` trait methods should always check if the string is an alias, and swap the alias for the abstract name that is an interface.

**Comment by driesvints** [comment]
This seems like a feature request to me. You can already directly mock the actual class. Feel free to attempt a PR.
