### ISSUE TITLE
^ symbol shown with dd method

### ISSUE THREAD

**Issue by EslamNemr** [laravel/framework#41278]
- Laravel Version: 9.1.0
- PHP Version: 8.1.3
- Database Driver & Version:

### Description:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/42042051/156095257-4b7f44e0-bf5a-4652-908d-e6e57ace2162.png">

**Comment by driesvints** [comment]
Not sure what you're getting at. If you have any concerns with this please open an issue with symfony's vardumper component.
