### ISSUE TITLE
Trailing slash with cached routes lead to miss route parameter

### ISSUE THREAD

**Issue by stdnpt** [laravel/framework#41277]
- Laravel Version: 8.61.0
- PHP Version: 7.4.13
- Database Driver & Version:

### Description:
Trailing slash with cached routes lead to miss route parameter

### Steps To Reproduce:
**routes/web.php**

`Route::get("/someprefix/{slug}", [SomeController::class,'index'])->name("someprefix.page")->where('slug', 'foo|bar');`

**RouteServiceProvider**

```
class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'App\Http\Controllers';
    
    public function map(): void
    {
        $this->mapWebRoutes();
    }
    
    protected function mapWebRoutes(): void
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('routes/web.php'));
    }
}
```
**Controller with action**

```
class SomeController extends WebControllerAbstract
{
    public function index($slug = null)
    {
        dd($slug);
        $view = $this->view("$slug.index");
        return $view;
    }
}
```

**Clear and build route cache:**
```
artisan.sh route:clear
artisan.sh route:cache
```
**`artisan.sh route:list` shows proper list of routes**

Request `/someprefix/foo` the result is "foo"
Request `/someprefix/foo/` the result is "null"

It looks like trailing slash lead to missing route parameter.

**Comment by driesvints** [comment]
I get "foo" in both times, with or without routes cached. You're also using a `null` default but aren't indicating the route parameter as nullable:

```php
Route::get("/someprefix/{slug?}", [SomeController::class,'index'])->name("someprefix.page")->where('slug', 'foo|bar');
```
