### ISSUE TITLE
Method after columns in migration does not work properly

### ISSUE THREAD

**Issue by davidjr82** [laravel/framework#41271]
- `php artisan --version` = Laravel Version: 9.2.0
- `php --version` = PHP Version: 8.1.2
- `select sqlite_version();` = SQLite 3.34.0

### Description: 
Adding "after" in migrations does not work as expected. It creates the columns at the end of the table, following docs steps:
https://laravel.com/docs/9.x/migrations#column-order

### Steps To Reproduce:

`laravel new my-project`

`php artisan make:migration add_fields_to_users_table`

```php
public function up()
{
    Schema::table('users', function (Blueprint $table) {
        $table->after('password', function ($table) {
            $table->string('address_line1');
            $table->string('address_line2');
            $table->string('city');
        });
    });
}
```

`php artisan migrate`

### Error:
Columns are added at the end of the users table instead of after the password column. It happens in MySQL too.

**Comment by whycomeing** [comment]
error?

**Comment by davidjr82** [comment]
The last line in my message says clearly:

Columns are added **at the end of the users table instead of after the password column**. It happens in MySQL too.

**Comment by driesvints** [comment]
Works fine for me in the latest Laravel version on MySQL 8:

<img width="282" alt="Screenshot 2022-02-28 at 11 43 30" src="https://user-images.githubusercontent.com/594614/155969536-133cedbc-001b-4ed7-aea7-3f170c1f6ff8.png">

**Comment by whycomeing** [comment]
Maybe the column already exists

**Comment by davidjr82** [comment]
I didn't realize I was opening the sqlite table from HeidiSQL, so probably I have not tested it in MySQL. But it happens in SQLite.
