### ISSUE TITLE
bug with unique validation

### ISSUE THREAD

**Issue by H-ishak** [laravel/framework#41285]
- Laravel Version: 8.4.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL

### Description:
i have tried to register a user so before the registration i did set a rule to verify the uniqueness of the phone number .
the problem is when the multiple requests are sent to the endpoint at the same time the validation doesn't work and i get multiple records in the database. further more even if i add an verification after the validation it still doesn't prevent adding the records.

### Steps To Reproduce:
1- set up a laravel project
2- add some models that are dependent 
3- set up an endpoint with the checking and a transaction
4- send multiple async requests at the same time.

code example :

         $request->validate([
            "firstname" => "required|string|min:3",
            "lastname" => "required|string|min:3",
            "phone" => [
                'required',
                new Phone(),
                function ($attribute, $value, $fail) {
                    $client = Client::whereHas('user', fn ($query) => $query->where('phone', $value))->first();
                    if ($client) {
                        $fail('The ' . $attribute . ' is already taken.');
                    }
                },
            ],
            "password" => "required|confirmed|min:6",
            "gender" => ["required", Rule::in([Driver::MEN, Driver::WOMEN])],
            'fcm_token' => "required|string",
            'idToken' => 'required|string'
        ]);
        $message = "Something very weird just happened!";
        $success = false;

        try {
            $auth = app("firebase.auth");
            $firestore = app('firebase.firestore');
            $database = $firestore->database();
            $verifiedIdToken = $auth->verifyIdToken($request->idToken);
            $uid = $verifiedIdToken->claims()->get('sub');
            $user = $auth->getUser($uid);

            throw_if($request->phone != $user->phoneNumber, Exception::class);
            DB::transaction(function () use ($request,$database) {
                $userModel = User::create([
                    "firstname" => $request->firstname,
                    "lastname" => $request->lastname,
                    "phone" => $request->phone,
                    "password" => Hash::make($request->password),
                ]);
                $clientModel = new Client([
                    "gender" => $request->gender,
                    'FCM_token' => $request->fcm_token
                ]);
                $clientModel->user()->associate($userModel);
                $clientModel->save();
                $clientModel->assignRole('client');
                $clientCollection = $database->collection('clients');
                $clientCollection->document('Client-' . $clientModel->id)->set([
                    'userId' => $clientModel->user->id,
                    'userBanStatus' => $clientModel->user->isBanned(),
                ]);
            });

            $success = true;
            $message = 'registration success';
            ClientCreated::dispatch();
        } catch (InvalidToken $e) {
            $message = 'The token is invalid';
        } catch (\InvalidArgumentException $e) {
            $message = 'The token could not be parsed';
        } catch (Throwable $e) {
        }

        return response()->json([
            "success" => $success,
            'message' => $message,
            'data' => []
        ], 200);
    }

and i also registered the time foreach request in the test :
![image](https://user-images.githubusercontent.com/71776062/156171013-4a50d75e-ab23-490a-8ea7-698e03fcba2a.png)

**Comment by rodrigopedra** [comment]
To avoid race conditions you can use Atomic Locks:

> Atomic locks allow for the manipulation of distributed locks without worrying about race conditions.

reference: https://laravel.com/docs/9.x/cache#atomic-locks

Also I'd suggest you add a unique index in your database to ensure data uniqueness on a database level.

**Comment by driesvints** [comment]
Thanks @rodrigopedra

**Comment by H-ishak** [comment]
@rodrigopedra can i use it on a specific session ?
because the register condition depends on the registered user .
