### ISSUE TITLE
whereIn() returns 0 results with 1000 values or more with mariadb 10.3.34

### ISSUE THREAD

**Issue by sventendo** [laravel/framework#41290]
- Laravel Version: v8.83.0
- PHP Version: 8.0
- Database Driver & Version: mariadb 10.3.34

### Description:

With the latest version of mariadb there seems to be an issue with the underlying `WHERE IN()` optimization when the clause has many, many values. The default threshold is 1000+ values. This can be changed with the system variable `in_predicate_conversion_threshold`:
https://mariadb.com/docs/reference/mdb/system-variables/in_predicate_conversion_threshold/

### Steps To Reproduce:

Works:
- use mariadb 10.3.32
- run tinker like `\DB::table('foo')->whereIn('bar', $arrayOf999Values)->count();`
- return 1234 results

Works:
- use mariadb 10.3.34
- run tinker like `\DB::table('foo')->whereIn('bar', $arrayOf999Values)->count();`
- return 1234 results

Works:
- use mariadb 10.3.32
- run tinker like `\DB::table('foo')->whereIn('bar', $arrayOf1000Values)->count();`
- return 1234 results

Doesn't work:
- use mariadb 10.3.34
- run tinker like `\DB::table('foo')->whereIn('bar', $arrayOf1000Values)->count();`
- return 0 results

Is this something that can be fixed on the Laravel side?
I tried implementing a global scope to split the "whereIn" into a chunked "where(whereIn($chunk1)->orWhereIn($chunk2)->orWhereIn(...))" statement but this only works well for arrays of values. If the parameter is another query instance it gets a lot more complex.

**Comment by driesvints** [comment]
This seems like a problem with MariaDB itself? Most likely you'll need to set that system variable higher? Not sure if there's anything we can do here ourselves...

**Comment by RoodFruit** [comment]
@sventendo I just had the same problem and was about to create a ticket. It seems that `addBinding()` is the culprit in `Illuminate/Database/Query/Builder.php`:

```
public function whereIn($column, $values, $boolean = 'and', $not = false)
{
    ...

    $this->addBinding($this->cleanBindings($values), 'where'); 

    return $this;
}
```

You can bypass using the bindings with `whereIntegerInRaw()` or `whereIntegerNotInRaw()`, in case your dataset are integers.

@driesvints why does Laravel only has `whereIntegerInRaw()`? I would think a `whereInRaw()` or `whereNotInRaw()` is pretty nice as well. What do you think?

**Comment by sventendo** [comment]
Seems to be a known issue with the latest release of mariadb, and not a Laravel issue at all:
https://jira.mariadb.org/browse/MDEV-27937

I'm closing this issue.

@RoodFruit FYI Setting the system variable `in_predicate_conversion_threshold` to `0` should "fix" the issue in the meantime.

**Comment by RoodFruit** [comment]
@sventendo I know, but if you do not want to use PDO bindings in Laravel (aka raw query), we should be able to use `whereInRaw()` / `whereNotInRaw()`, which is currently not available yet, although the Grammar is already there. @driesvints Idea to put this in?

**Comment by driesvints** [comment]
Feel free to attempt a pr 👍

**Comment by RoodFruit** [comment]
@driesvints See https://github.com/laravel/framework/pull/41306.
