### ISSUE TITLE
Bus::fake() doesn't respect arguments when using job batching

### ISSUE THREAD

**Issue by yoeriboven** [laravel/framework#41293]
- Laravel Version: 9.2.0
- PHP Version: 8.1.2

### Description:

I'm trying to assert that `FirstJob` dispatches `SecondJob`.

```php
<?php

namespace App\Jobs;

use ...

class FirstJob
{
    use Batchable, Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle() 
    {
        $this->batch()->add(new SecondJob());
    }
{
```
`Bus::fake()` fakes _all_ jobs. You can pass [a parameter](https://github.com/laravel/framework/blob/17c49e589d5e1c9c40ba88e90de522c38f11bb69/src/Illuminate/Support/Facades/Bus.php#L44) and then it should only fake a specific job.

When using `Bus::fake(SecondJob::class)` it should only fake SecondJob.
```php
/** @test */
public function it_dispatches_second_job()
{
    Bus::fake(SecondJob::class);

    Bus::batch(new FirstJob())->dispatch();

    Bus::assertBatched(function (PendingBatch $batch) {
        dump($batch->jobs); // Collection only has the FirstJob
    });
}
```

The code above should run `FirstJob` but not `SecondJob`.

This isn't happening though. `Illuminate\Support\Testing\Fakes\BusFake` isn't respecting the arguments you sent. It fakes _all_ jobs irrespective of whether you sent a specific job.

When calling `dispatch` on a `Bus`, it [checks](https://github.com/laravel/framework/blob/17c49e589d5e1c9c40ba88e90de522c38f11bb69/src/Illuminate/Support/Testing/Fakes/BusFake.php#L553) whether the job should be faked or not.
When calling dispatching a batch or adding a new job to the batch it [doesn't do the check](https://github.com/laravel/framework/blob/d442195be0c1a95324522d733e2369e406db51d1/src/Illuminate/Bus/Batch.php#L189).

Would be nice if this could be fixed.

**Sidenote**
If this is being fixed it would be nice if you could also do `Bus::assertDispatched(SecondJob::class)`. For that to happen similar recording needs to happen like in [`dispatch`](https://github.com/laravel/framework/blob/17c49e589d5e1c9c40ba88e90de522c38f11bb69/src/Illuminate/Support/Testing/Fakes/BusFake.php#L554).

### Steps To Reproduce:

I created [a project](https://github.com/yoeriboven/laravel-bug-bus).

**Comment by driesvints** [comment]
You're dispatching the batch. The second job can never be dispatched.

**Comment by yoeriboven** [comment]
@driesvints Then how do I test that one job can push another job to the queue (in a batch)?

**Comment by yoeriboven** [comment]
I tried to implement partial job faking and it works! Really happy since this problem has been annoying me for a while.

Will send in a PR later. :)

**Comment by driesvints** [comment]
@yoeriboven I think I see what the problem is. You expect `Bus::batch` to not be faked. That's not the case as `Bus::fake(` swaps out the entire command bus for all subsequent code in the same test. That's how it works. We cannot change this as it'd break people's tests.
