### ISSUE TITLE
"php artisan schedule:list" should show mutex

### ISSUE THREAD

**Issue by madman-81** [laravel/framework#41310]
Today I ran into an issue with a scheduled task that wasn't running. It took me a while to figure out was going on, mostly because the `schedule:list` showed nothing out of the ordinary and was updating the "Next Due" timestamp as expected. However the tasks wasn't executed. Long story shot, the tasks got stuck because a mutex wasn't cleared, probably because of an unscheduled server reboot. 

It would have really helped me if the `schedule:list` would indicate that there is still a mutex for a certain command and it would help even more if it would show how old the mutex is (when it was created). Something like this:

```bash
ubuntu@my_server:~/project$ php artisan schedule:list
+----------------------------------------------------------+-------------+--------------------+----------------------------+----------------------------+
| Command                                                  | Interval    | Description        | Next Due                   | Mutex                      |
+----------------------------------------------------------+-------------+--------------------+----------------------------+----------------------------+
| '/usr/bin/php8.0' 'artisan' mycommands:something         | */2 * * * * | Process something  | 2022-03-03 10:22:00 +00:00 | 2022-03-02 12:44:00 +00:00 |
| '/usr/bin/php8.0' 'artisan' mycommands:otherthing        | */2 * * * * | Process otherthing | 2022-03-03 10:22:00 +00:00 |                            |
+----------------------------------------------------------+-------------+--------------------+----------------------------+----------------------------+
```

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
