### ISSUE TITLE
Fresh Install, error artisan route:list

### ISSUE THREAD

**Issue by dgironella** [laravel/framework#41318]
- Laravel Version: v9.3.0
- PHP Version: PHP 8.1.2
- Database Driver & Version: None

### Description:

After a fresh install, execute route:cache and route:list and exception fired.,

### Steps To Reproduce:

I made a fresh install with

composer create laravel/laravel test

cd test

php artisan route:cache
php artisan route:list

And error...

` ReflectionException 

  Class "O:47:"Laravel\SerializableClosure\SerializableClosure":1:{s:12:"serializable";O:46:"Laravel\SerializableClosure\Serializers\Signed":2:{s:12:"serializable";s:295:"O:46:"Laravel\SerializableClosure\Serializers\Native":5:{s:3:"use";a:0:{}s:8:"function";s:77:"function (\Illuminate\Http\Request $request) {
    return $request->user();
}";s:5:"scope";s:37:"Illuminate\Routing\RouteFileRegistrar";s:4:"this";N;s:4:"self";s:32:"00000000000002d30000000000000000";}";s:4:"hash";s:44:"Wl3vmm7PTYqPG0N8Pm85TCwJiITBVFJMMMs+7LPOb5A=";}}" does not exist

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/RouteListCommand.php:223
    219▕         if ($route->action['uses'] instanceof Closure) {
    220▕             $path = (new ReflectionFunction($route->action['uses']))
    221▕                                 ->getFileName();
    222▕         } elseif (is_string($route->action['uses'])) {
  ➜ 223▕             $path = (new ReflectionClass(explode('@', $route->action['uses'])[0]))
    224▕                                 ->getFileName();
    225▕         } else {
    226▕             return false;
    227▕         }`

**Comment by driesvints** [comment]
Caused by https://github.com/laravel/framework/pull/41254. We're investigating, thanks.

**Comment by markwalet** [comment]
Weird, I tried this and couldn't reproduce it with a fresh install. Found out I was on version `9.3.1`. Downgraded Laravel from `9.3.1` to `9.3.0`.

Looks like it got fixed in `9.3.1`. @dgironella could you verify that?

**Comment by dgironella** [comment]
In version 9.3.1 is solved. My error was produced in version 9.3.0 caused by #41254
