### ISSUE TITLE
Error executing 'npm run dev' Laravel Breeze

### ISSUE THREAD

**Issue by calebeso** [laravel/framework#41329]
- Laravel Version: 8.0
- PHP Version: 7.4.9
- Database Driver & Version: 

### Description:
I'm trying to install Laravel Breeze in my Laravel 8.0 fresh installation, everything works fine until I run the command `npm run dev`, wich is giving me the following error: 

`     Asset     Size   Chunks             Chunk Names
/js/app.js  706 KiB  /js/app  [emitted]  /js/app

ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-import requires PostCSS 8.`

I was looking for related topics and nothing was about Laravel Breeze, already tried these steps in 2 different OS system, Windows 10 and Ubuntu 20.04 with different NodeJS versions (15, 16, 17) and the error still persisting. 

I already tried those steps to uninstall TailwindCSS PostCSS and AutoPrefixer, but It doesn't work. 

### Steps To Reproduce:
Just Install Laravel 8.0 via composer and then tried to install Laravel Breeze with any NodeJS version.

**Comment by driesvints** [comment]
Why are you starting from Laravel v8 instead of v9?

**Comment by calebeso** [comment]
Because we're currently using php 7.4.

**Comment by driesvints** [comment]
We don't recommend starting new Laravel 8 projects. Please use Laravel 9.
