### ISSUE TITLE
Laravem Multiple Dynamic Mail configuration from database not working for Laravel Queue

### ISSUE THREAD

**Issue by nareshvegad** [laravel/framework#41332]
- Laravel Version: #.#.#
- PHP Version: 7.4.2
- Database Driver & Version:

### Description:
If i set multiple mail configuration from database instead of from env file it's not use dynamic mail configuration but taking default env file.

i used below code:

```
    Config::set('mail', $config);
```
before sending mail i want to set dynamic mail config. based on condition but for queue it takes default from env file.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
