### ISSUE TITLE
DB fetching requests go to read replica even though $connection is specified

### ISSUE THREAD

**Issue by SCIF** [laravel/framework#41331]
The code

```class TestMigration extends Migration
{
    protected $connection = 'myconn::write';
    
    public function up(): void
    {
        $rows = DB::table('table')…
```

will request read replica servers even though `::write` suffix is specified in `$connection` property.

Versions met:

- Laravel Version: 8.83.1
- PHP Version: 8.1
- Database Driver & Version: mysql

But most likely all versions affected

### Description:

To force reading from `write` replica the connection must be explicitly specified at all times. Like:

```class TestMigration extends Migration
{
    protected $connection = 'myconn::write';
    
    public function up(): void
    {
        $rows = DB::connection($this->connection)->table('table')…
```

I believe you will close this issue as «not gonna be fixed and behavior is expected» but encourage you at least to mention this behavior in docs

**Comment by driesvints** [comment]
@derekmd didn't we fix this in https://github.com/laravel/framework/pull/41161 ?

@SCIF please post your `database.php` config file.

**Comment by SCIF** [comment]
@driesvints , the fix you are referring to, doesn't fix the issue, as works with `Schema` only but I point out the issue of requesting via `DB`/`Model`

```
<?php

$connections = [];

foreach ([
    'admin' => 'Admin',
    'data' => 'Data',
] as $name => $dbName) {
    $useRoReplica = 'cli' === PHP_SAPI || 'admin' === $name;
    $connections[$name] = [
        'driver'    => 'mysql',
        'database'  => env('DB_NAME_PREFIX') . $dbName,
        'username'  => env('DB_USERNAME'),
        'password'  => env('DB_PASSWORD'),
        'charset'   => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix'    => '',
        'strict'    => false,
    ];

    if ($useRoReplica) {
        $connections[$name]['read']   = ['host' => [env('DB_RO_HOST') ?? env('DB_HOST')]];
        $connections[$name]['write']  = ['host' => [env('DB_HOST')]];
        $connections[$name]['sticky'] = false;
    } else {
        $connections[$name]['host'] = env('DB_HOST');
    }
}


return [
	'fetch' => PDO::FETCH_CLASS,
	'default' => 'admin',
	'connections' => $connections,
	'migrations' => 'migrations',


	'redis' => [
		'client' => 'phpredis',
		'cluster' => env('REDIS_CLUSTER', false),
		'default' => array(
			'host'     => env('REDIS_DEFAULT_HOST', 'redis'),
			'port'     => env('REDIS_DEFAULT_PORT', 6379),
			'database' => env('REDIS_DEFAULT_DB', 0),
		),
	],
];
```

**Comment by driesvints** [comment]
@SCIF ah I totally missed that. Yeah that can never work sorry. You have to reference the connection on the migration class. The connection property only applies to schema changes.

Feel free to send in a PR to the docs if you want.
