### ISSUE TITLE
It's need to release directory lock. to avoid error: rmdir($directoru); Text file busy.

### ISSUE THREAD

**Issue by mouyong** [laravel/framework#41353]
https://github.com/laravel/framework/blob/a9098eed14b79f570b84e4698b5b1f296758cd04/src/Illuminate/Filesystem/Filesystem.php#L703

```
        // need unset $items before remove am empty dir.
        unset($items); // here. 
        if (! $preserve) {
            @rmdir($directory); // Text file busy
        }
```

**Comment by mouyong** [comment]
Is there no repair plan for the time being? @driesvints

**Comment by driesvints** [comment]
@mouyong please use a support channel

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by driesvints** [comment]
Or attempt a PR

**Comment by mouyong** [comment]
When I use $this->app->files->deleteDriectory(); it cannot remove the directory. because $items = new FilesystemIterator($directory); take the resource lock, but not release the lock.
