### ISSUE TITLE
Blind copies are not sent by sendmail transport

### ISSUE THREAD

**Issue by DA40** [laravel/framework#41357]
- Laravel Version: 9.3.1
- PHP Version: 8.0.14
- Database Driver & Version: N/A

### Description:
Using a mail controller like this:

```php
class SendmailController extends Controller
{
	public function post_sendmail(Request $request)
	{
		$email = new Sendmail($request->subject, $request->msg);

		Mail::to($request->to)
			->bcc($request->bcc)
			->send($email);

		return "Email sent";
	}
}
```

If MAIL_MAILER=smtp in the .env file, and a suitable SMTP server is configured, the blind copy is sent, but when MAIL_MAILER=sendmail it isn't.

### Steps To Reproduce:
1. Extract the sendmail app from the attached archive to a linux system with a sendmail binary.
2. cd sendmail
3. composer update
4. cd public
5. php -S 127.0.0.1:8080
6. In a web browser, browse to http://127.0.0.1:8080/
7. Complete the fields in the form.
8. Click Send.

[sendmail.tar.gz](https://github.com/laravel/framework/files/8191129/sendmail.tar.gz)

**Comment by ajuchacko** [comment]
[Take a look](https://github.com/laravel/framework/pull/41362#issue-1160618726)

**Comment by cuppett** [comment]
I didn't do a direct comparison of both 8.x and 9.x with the same user code, but I believe the previous mailer likely emitted the Bcc: headers as part of the $message->toString() and then they got picked up by anything which was using the raw message. I did definitely see they weren't there as part of the output when stepping through with the debugger. I don't know if that's required, optional behavior for these mailers or just was a happy coincidence.

My PR in #41362 helps stay within AWS SES' rules of a 50 recipient limit and at the same time breaks reliance on that circumstance/behavior.

**Comment by cuppett** [comment]
@driesvints I do not believe my PR will resolve this issue.

**Comment by DA40** [comment]
I can confirm that this worked with earlier versions of Laravel that used Swift Mailer.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by DA40** [comment]
@driesvints I'm not familiar with the process you asked me to undertake, but I've done my best and shared the repository with you.  Please let me know if I've missed anything.

**Comment by driesvints** [comment]
I took a deeper look into this and found https://github.com/symfony/symfony/issues/40070 & https://github.com/symfony/symfony/pull/39744.

It seems this is related to the usage of `-t` which is the default in Laravel: https://github.com/laravel/laravel/blob/93395a3468b7827bae2117de7543eddd5eb4a4e5/config/mail.php#L61.

Try changing `/usr/sbin/sendmail -t -i` to `/usr/sbin/sendmail -bs -i` to see if it works?

**Comment by DA40** [comment]
Good call! That fixes it.  Thanks for your help.

**Comment by driesvints** [comment]
Cool, I sent a PR to change the default: https://github.com/laravel/laravel/pull/5836
