### ISSUE TITLE
`LazyCollection::every()` type inferences by PHPStan are completely broken 

### ISSUE THREAD

**Issue by mpyw** [laravel/framework#41369]
- Laravel Version: 9.3.1
- PHPStan Version: 1.4.5
- Larastan Version: 1.0.3
- PHP Version: 8.1

### Description & Reproduction Steps:

```php
$collection = new LazyCollection([new \stdClass]);
\PHPStan\dumpType($collection->every(...));
```

#### Expected: 

```yaml
Dumped type: Closure((callable(stdClass, int): bool)|stdClass|string, mixed, mixed): bool
```

#### Actual:

```yaml
Dumped type: Closure((callable(int, int): bool)|int|string, mixed, mixed): bool
```

Though I haven't determined yet whether it is a PHPStan bug or a Laravel bug, I'll submit it as a Laravel issue for the time being.

**Comment by mpyw** [comment]
I hope that https://github.com/laravel/framework/discussions/40889 should be resolved although it is not directly related. It is very inconvenient that `Collection<Item>` is not considered a subtype of `Collection<ItemInterface>` whereas `Item[]` is considered a subtype of `ItemInterface[]`.

**Comment by mpyw** [comment]
Related

- https://github.com/laravel/framework/pull/38538 by @nunomaduro 
- https://github.com/laravel/framework/pull/39506 by @sebdesign

**Comment by driesvints** [comment]
Please just attempt a PR if you want to adjust anything. No code is broken.

**Comment by mpyw** [comment]
@driesvints I confirmed that it's not reproducible in newly cloned `laravel/laravel` apps, however, it actually appears in my existing app. I'll research some more.

**Comment by mpyw** [comment]
It's very odd, looks like `LazyCollection::every()` specific.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1351893/157180739-31492eff-4e66-4cff-b49d-015fceeacce9.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1351893/157180923-fec04963-bf63-47f2-b6f4-1b1ac30d6a12.png">

**Comment by mpyw** [comment]
wtf???

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1351893/157182197-cff1e8e9-205b-4638-bca9-2c5ee86af481.png">

<img width="536" alt="image" src="https://user-images.githubusercontent.com/1351893/157182244-4d00f859-e73f-4541-8f30-8ab4d663963a.png">

| Method | Collection | LazyCollection |
|:---|:---|:---|
| `every()` | ✅  | :x: |
| `some()` | :x: | :x: |
| `map()` `filter()` | ✅ | ✅ |

**Comment by mpyw** [comment]
A clean install solved the problem. I can't reproducd the bug anymore regardless I haven't touch directly inside `vendor` and prepare the same version of `composer.lock` as before. I have no idea what's going on. Was the cache corrupted?

**Comment by mpyw** [comment]
Reproduced again

**Comment by mpyw** [comment]
Confirmed that the `TValue` inferencing is unexpectedly replaced with `TKey`.

![image](https://user-images.githubusercontent.com/1351893/157243984-0f3831fc-87ff-4da0-a0fe-4c36db1377b4.png)
![image](https://user-images.githubusercontent.com/1351893/157243992-d8e0f6b0-0f30-4d7e-a577-5565d75f13ff.png)
![image](https://user-images.githubusercontent.com/1351893/157244012-2929f125-6152-43b6-9b67-033656bbfc48.png)

**Comment by mpyw** [comment]
Re-published as a PHPStan issue: https://github.com/phpstan/phpstan/issues/6768
