### ISSUE TITLE
Updating a JSON column of a single model doesn't work

### ISSUE THREAD

**Issue by dees040** [laravel/framework#41375]
- Laravel Version: 9.3.1
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0

### Description:

According to the docs I should be able to update a JSON column of a model using the following code:

```php
$user->update(['data->foo' => 100]);
```

But when trying to do so in a fresh Laravel installation, nothing seems to be changed:

![image](https://user-images.githubusercontent.com/5390555/156989831-54357a61-5aac-4d8e-9d01-c33da3d9ebf8.png)

When trying to update all models it does seem to work for me.

```php
User::query()->update(['data->foo' => 100]); // Works

$user = User::find(1);

$user->update(['data->foo' => 100]); // Doesn't work
```

### Steps To Reproduce:

1. Fresh install of Laravel 
2. Add a JSON column to the user migration (`$table->json('data');`)
3. Add `data` to `$fillable` array
4. Add the field to the casting array in the User model (`'data' => 'array',`)
5. Try to update a single model `$user->update(['data->foo' => 10]);`

**Comment by driesvints** [comment]
You need to explicitly add `data->foo` in the fillable array:

`protected $fillable = ['data->foo'];`

**Comment by driesvints** [comment]
https://laravel.com/docs/9.x/eloquent#mass-assignment-json-columns

![Uploading Screenshot 2022-03-07 at 17.55.13.png…]()
