### ISSUE TITLE
error front-end bug | Error disappears

### ISSUE THREAD

**Issue by amirhossein-fzl** [laravel/framework#41373]
- Laravel Version: 9.3.1
- PHP Version: 8.0.15
- Database Driver & Version: mysql, 5.7.33
- Google Cgrome: 99.0.4844.51

### Description:

Hello. When I get an error in Laravel, when I scroll the page or click on any of the links on the error page, the page appears as follows.

![ignition 00_00_00-00_00_30](https://user-images.githubusercontent.com/53816722/156986137-69d8cd66-9862-4c81-b326-8e01df7cf38f.gif)

The browser console also shows this error !!

![issue](https://user-images.githubusercontent.com/53816722/156986213-88f22ca3-cb49-43a8-93fc-dedc416c3d6e.png)

**Comment by driesvints** [comment]
Please open this issue on the spatie ignition repo as we don't maintain this.
