### ISSUE TITLE
Use laravel9 package extension development Use pushMiddlewareToGroup to add middleware group invalid

### ISSUE THREAD

**Issue by shijie1991** [laravel/framework#41386]
- Laravel Version: 9.3.1
- PHP Version:  8.1.1

Description:

Use laravel9 package extension development Use pushMiddlewareToGroup to add middleware group invalid

Steps To Reproduce:

**CoreServiceProvider.php**
<img width="817" alt="image" src="https://user-images.githubusercontent.com/11606404/157098371-d9135331-8a46-4378-9729-46f7d4e8ae61.png">

output

![image](https://user-images.githubusercontent.com/11606404/157098543-9d81daa0-c6c4-4b57-8df3-7a7bef301410.png)

**AuthController.php**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/11606404/157098826-38c36a58-9705-4a32-ab70-c2f0957d0157.png">

output

![image](https://user-images.githubusercontent.com/11606404/157098938-cd98d534-e0c4-4e72-87bf-952f071c834e.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by shijie1991** [comment]
laravel8 works fine
