### ISSUE TITLE
HTTP Client query parameters not merged as expected after upgrading

### ISSUE THREAD

**Issue by Victor-emil** [laravel/framework#41382]
- Laravel Version: v8.83.3
- PHP Version: 8.1.1
- Database Driver & Version: PostgreSQL 13

### Description:

I just upgraded Laravel from v8.83.0 to 8.83.3 and started experiencing issues with query parameters not being merged as expected via 
```
public function __construct()
{
    $this->client = Http::baseUrl('https://api.hubapi.com')
        ->withOptions([
            'query' => [
                'hapikey' => config('services.hubspot.api_key'),
            ],
        ]);
}
```
```
public function getPipelines(): array
{
    return $this->client
        ->asJson()
        ->get('/crm/v3/pipelines/deals')
        ->throw()
        ->json();
}

query: ""
```
I am aware that the get() method takes an array as a second argument for populating the query parameters. But I would expect the above to work anyway, since this would work using Guzzle directly. If I add an empty array `->get('https://google.com', [])` it works as expected and correctly appends `?test=test` to the url. I encountered this issue, since I am declaring a class property of type PendingRequest that I reuse for different purposes. It did not break any ->post() or ->patch() methods, but it started failing for all the ->get() methods. 

I could add the placeholder array to all occurrences, but at the moment I have around 100 places where I use this. I also suspect that other people might encounter this issue.

### Steps To Reproduce:
Does not add query parameters

```
Http::withOptions([
    'query' => [
      'test' => 'test',
    ]
])->get('https://google.com')

query: ""
```

Correctly adds query parameters

```
Http::withOptions([
    'query' => [
      'test' => 'test',
    ]
])->get('https://google.com', [])

query: "?test=test"
```

**Comment by driesvints** [comment]
It seems https://github.com/laravel/framework/pull/41055 isn't present on 8.x which is probably needed.

@Victor-emil if you change https://github.com/laravel/framework/blob/e6da0b8a7485276faad228e1270e6987f9fa888e/src/Illuminate/Http/Client/PendingRequest.php#L798 to `return is_array($laravelData) ? $laravelData : [];`, does it work for you?

**Comment by Victor-emil** [comment]
@driesvints. Unfortunately that didn't work. I suspect it might have something to do with one of following commits. 

https://github.com/laravel/framework/commit/30e341b7fe4e4d9019df42b7eff6c7dfa5ea30e5
https://github.com/laravel/framework/commit/d037fc509c8928f451f74ae80ff72074beba721b

I also see that another person also seems to have problems using withOptions for sending json with Get Requests.

**Comment by driesvints** [comment]
> I also see that another person also seems to have problems using withOptions for sending json with Get Requests.

That got fixed on 9.x with the PR I linked to. 

I can confirm the above two commits break it, most notable mine. I'll work on a fix to make sure both use cases are supported.

**Comment by driesvints** [comment]
I attempted a fix here: https://github.com/laravel/framework/pull/41392

**Comment by Victor-emil** [comment]
@driesvints. I just upgraded to the latest version of Laravel v9.4.1 and the problem has now been solved for me. Thanks for the assistance. 🤘
