### ISSUE TITLE
Migrate command is trying to migrate a non-existent personal_access_tokens migration file

### ISSUE THREAD

**Issue by ejlocop** [laravel/framework#41391]
- Laravel Version: 9.3.1
- PHP Version: 8.0.9
- Database Driver & Version: MySql 14.14 Distrib 5.7.24, for Win64 (x86_64)

### Description:
php artisan migrate command is still trying to migrate a non-existent personal_access_tokens migration file in the database/migrate directory. 

I've also tried to run the composer dumpautoload command after renaming the file but it still fails.

Note: the reason I rename the migration files into `00_00_00_00` before deploying to any server is because we're a small team and we don't want to keep adding more files in the migration directory. 
we always want to keep our migration directory as straightforward as possible before any deployments to a server.

![image](https://user-images.githubusercontent.com/12082880/157176142-09451f57-52cb-48d4-b486-824cefaa120c.png)

composer file
```
"require": {
  "php": "^8.0.2",
  "guzzlehttp/guzzle": "^7.2",
  "laravel/framework": "^9.2",
  "laravel/sanctum": "^2.14.1",
  "laravel/tinker": "^2.7",
  "maatwebsite/excel": "^3.1",
  "phpoffice/phpspreadsheet": "^1.22",
  "psr/simple-cache": "^1.0"
},
"require-dev": {
  "fakerphp/faker": "^1.9.1",
  "laravel/sail": "^1.0.1",
  "mockery/mockery": "^1.4.4",
  "nunomaduro/collision": "^6.1",
  "phpunit/phpunit": "^9.5.10",
  "spatie/laravel-ignition": "^1.0"
}
```

### Steps To Reproduce:

- create a new fresh laravel instance
- rename the existing personal_access_tokens file (see image above)
- run the migration

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by TomasMatusek** [comment]
Yes I am facing same issue here. I deleted all migration files but that personal_access_tokens table is still created even I dumped everything.

`"require": {
        "php": "^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.54",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.3"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },`
