### ISSUE TITLE
Unable To Customise Route Resource Parameter Name for URLs with Slug case

### ISSUE THREAD

**Issue by emmannl** [laravel/framework#41399]
- Laravel Version: 9.4.1
- PHP Version: 8.1.3
- Database Driver & Version: N/A

### Description:
When defining an apiResource route, we have the ability to overwrite the parameter name used for example in route model binding.

For example:
`Route::apiResource('my-action', MyActionController::class)->parameter('my_action', 'userAction');`

should allow us to access the parameter bound to the given model in our controller like so:

```php
    public function update(Model $userAction, Request $request)
    {
        return $userAction;
    }
```

However, hitting this endpoint will return a response with an empty JSON object.

### Steps To Reproduce:

Create a resource or apiResource route, the URL path should be in slug-case, eg:
`Route::resource('my-action', MyActionController::class))->parameter('my_action', 'userAction');`

Next run `php artisan route:list` and notice the the parameter name for the declared route is `my_action`, instead of the expected `userAction`

Next, define another route with the URL not being in slug-case:
`Route::resource('anotherAction', MyActionController::class))->parameter('action', 'userAction');`

Run `php artisan route:list` and notice the the parameter name has been changed from `anotherAction` to `userAction` - which is the expected behaviour

**Comment by marvin-wtt** [comment]
Shouldn't it be `Route::resource('my-action', MyActionController::class))->parameter('my-action', 'userAction');` instead? The minus is only converted to an underscore later to generate a valid php variable name

**Comment by emmannl** [comment]
> Shouldn't it be `Route::resource('my-action', MyActionController::class))->parameter('my-action', 'userAction');` instead? The minus is only converted to an underscore later to generate a valid php variable name

My bad. Your are very correct!
