### ISSUE TITLE
Issue with `afterResolving` when the class had already been resolved.

### ISSUE THREAD

**Issue by pxpm** [laravel/framework#41394]
Hello guys! 

I have a question regarding the `afterResolving` callbacks.  First of all sorry if I miss something basic here, I will try my best to explain it clearly. The question first and I will give the context after to don't biase the answer to a concrete example:

- **What is expected to happen when you define a `afterResolving` callback to some class that had already been resolved in the container ? Shoudn't that callback be imediatelly run on the already resolved class ?** 

https://github.com/laravel/framework/blob/22c2cee98a229d8da6ae02caadda6848565dfd94/src/Illuminate/Container/Container.php#L1154

#### Context of my use case: 

So the documented way to add custom blade directives is by going into the ServiceProvider `boot()` method and use the `Blade::directive()`. All fine. 

For long long time I've been using the following to add my own directives: 

```php

// NOTE: this on the register() method of my provider

$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
    $bladeCompiler->directive(someDirective', function ($parameter) {
        // ....
    });
});
```

Everything works fine as long as  **MyProvider is loaded before** other providers that define the blade directives with `Blade::directive()`, otherwise it would resolve the class first, and my registered callback would never run. I can see it in the `afterResolvingCallbacks` but the `blade.compiler` is already resolved when I register my callback if any other ServiceProvider is registering the diirectives without using `afterResolving()`!

![image](https://user-images.githubusercontent.com/7188159/157238139-dc388970-15a4-4437-8ee7-4b8a766b2da6.png)

My expectation would be that an `afterResolving` callback would be called if the class is already resolved, probably it would be impossible to do that for a `beforeResolving` since at that time it's already resolved, but for a `afterResolving` can't we work something out ? 

The reason why I asked first is because I don't expect answers like `change your directive definition`, I want the focus to be, what happens when I define a `afterResolving` callback to some class that had already been resolved. 

Thanks for your time  and patience! Let me know if I wasn't clear enough!

Pedro

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by pxpm** [comment]
@driesvints sure, I reposted the issue in some Laravel channels. 👍 

Can you just let me know what you think should happen in the specific scenario when the class had been resolved, and someone register an `afterResolving` callback for it? Just bad lucky day then ? There is nothing Laravel can do about it ? 

Thanks for your time 🙏 

Pedro

**Comment by driesvints** [comment]
@pxpm sorry, I closed this mainly because I didn't see a filled out issue template. This isn't really the appropriate place to ask these questions. Try discussions or the other channels above. Please also see the issue templates when you open an issue. I don't have time to answer every question sorry.

**Comment by pxpm** [comment]
Understandable, and I didn't see the issue templates, sorry for that. I will be filling a full issue template later if I don't get the answer from the channels I've posted this question.

I am not even sure if this is or should be considered an issue, that's why I phrased it as a question, but technically it's some internal Laravel behaviour. 

The question is pretty straightforward but I get it would take some time to properly answer. 
I was considering not event post the concrete example because I know it would lead this to be seen more like a support question than rather a Laravel internal behaviour discussion, my bad on this one too, should had left the blade compiler example out of the question. 

Anyway, thanks 🙏

If anyone come here from the post I did in some channels, please the focus is: **What happens in Laravel when you define a after resolving callback to a class and the class is already resolved when your callback is registered.**
