### ISSUE TITLE
Error bag contents are not passed to components

### ISSUE THREAD

**Issue by Healyhatman** [laravel/framework#41390]
- Laravel Version:  8.83.2
- PHP Version: 7.4.14
- Database Driver & Version: SQL Server

### Description:
When using withErrors to pass errors to a view, those errors are not rendered in components. The $errors variable is still available, it's just a different object to the one available in the main view itself. To get the correct error bag you have to explicitly pass it using `:errors="$errors"`

### Steps To Reproduce:

Create a component in views/components and use its name in the test (I am using a component called bootstrap-alert)

The following tests should both pass, but only the second one passes

```
        $this
            ->withViewErrors(['name' => ['This is an error']])
            ->blade('<x-bootstrap-alert>@dump($errors->first())</x-bootstrap-alert>')
            ->assertSee('This is an error');

        $this
            ->withViewErrors(['name' => ['This is an error']])
            ->blade('<x-bootstrap-alert :errors="$errors">@dump($errors->first())</x-bootstrap-alert>')
            ->assertSee('This is an error');
```

**Comment by driesvints** [comment]
> To get the correct error bag you have to explicitly pass it using :errors="$errors"

This is intentional. Components don't take over this variable to be isolated from other views, etc.

**Comment by Healyhatman** [comment]
> > To get the correct error bag you have to explicitly pass it using :errors="$errors"
> 
> This is intentional. Components don't take over this variable to be isolated from other views, etc.

Why do they still have their own separate empty errors variable made available then? That appears to be shared between all the components? Where is it being instantiated?

**Comment by Healyhatman** [comment]
@driesvints  ? Where is it being instantiated?

And from the documentation:
> An $errors variable is shared with all of your application's views by the Illuminate\View\Middleware\ShareErrorsFromSession middleware, which is provided by the web middleware group. When this middleware is applied an $errors variable will always be available in your views, allowing you to conveniently assume the $errors variable is always defined and can be safely used.
