### ISSUE TITLE
$deleteWhenMissingModels no work

### ISSUE THREAD

**Issue by YangHaHabiu** [laravel/framework#41403]
- Laravel Version: 9.x
- PHP Version: 8.1.3
- Database Driver & Version: mysql 5.7

### Description:
A table in the database does not exist;

set $deleteWhenMissingModels = false

Failed method will not be triggered
will not send data to failed_jobs

### demo
```
 class TestJob implements ShouldQueue
  {

    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $deleteWhenMissingModels = false;


    public function __construct()
    {
        
    }

    public function handle()
    {
        // Table 'users' doesn't exist
        $model = new User();
        $arr = [
            'name' => "test"
        ];
        $model->fill($arr)->save();
    }

    public function failed(Exception $ex)
    {
        //no work
        print_r($ex->getMessage());
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
