### ISSUE TITLE
Route group issue Laravel 9

### ISSUE THREAD

**Issue by gifary** [laravel/framework#41402]
- Laravel Version: 9.2
- PHP Version: 8.0.12
- Database Driver & Version: mariadb  Ver 15.1 Distrib 10.3.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Description:
Route group issue tested on API.php always return Unauthenticated

### Steps To Reproduce:

`
Route::group(['as'=>'api.'], function () {

    Route::group(['middleware' => ['auth:api'],'as'=>'admin.','prefix'=>'admin'], function () {
        Route::apiResource('business-verticals', \App\Http\Controllers\Api\Admin\BusinessVerticalsController::class);
        Route::apiResource('companies', \App\Http\Controllers\Api\Admin\CompaniesController::class);
        Route::apiResource('locations', \App\Http\Controllers\Api\Admin\LocationsController::class);
    });

    Route::group(['middleware' => ['auth:api'],'prefix' => '{company}','as'=>'company.'], function () {

        Route::get('/',[\App\Http\Controllers\Api\Company\CompaniesController::class,'show'])->name('show');
        Route::patch('/',[\App\Http\Controllers\Api\Company\CompaniesController::class,'update'])->name('update');
    });

    Route::get('countries', [\App\Http\Controllers\Api\CountriesController::class,'index'])->name('countries.index');
});
`
1. Try to access /api/countries will be return Unauthenticated
2. change the order countries route like below 

`
Route::group(['as'=>'api.'], function () {

    Route::get('countries', [\App\Http\Controllers\Api\CountriesController::class,'index'])->name('countries.index');
    Route::group(['middleware' => ['auth:api'],'as'=>'admin.','prefix'=>'admin'], function () {
        Route::apiResource('business-verticals', \App\Http\Controllers\Api\Admin\BusinessVerticalsController::class);
        Route::apiResource('companies', \App\Http\Controllers\Api\Admin\CompaniesController::class);
        Route::apiResource('locations', \App\Http\Controllers\Api\Admin\LocationsController::class);
    });

    Route::group(['middleware' => ['auth:api'],'prefix' => '{company}','as'=>'company.'], function () {

        Route::get('/',[\App\Http\Controllers\Api\Company\CompaniesController::class,'show'])->name('show');
        Route::patch('/',[\App\Http\Controllers\Api\Company\CompaniesController::class,'update'])->name('update');
    });
});`

Try to access /api/countries will be return the data without authenticated

**Comment by SupianIDz** [comment]
This is not a bug, It is caused by `'prefix' => '{company}'`, when you call /api/countries `countries` will be treated as `{company}`

To solve this, you can change to `'prefix' => 'companies/{company}'`

**Comment by driesvints** [comment]
Thanks @SupianIDz
