### ISSUE TITLE
`Route:view()` are not listed when using `--except-vendor`

### ISSUE THREAD

**Issue by AliSaleem27** [laravel/framework#41416]
- Laravel Version: 9.4.1
- PHP Version: 8.1.1

### Description:
Any routes defined using the `Route::view()` method are not shown in the route list when ignoring vendor routes.

Since these routes are defined in the users app, they should be shown even when ignoring vendor routes from the list.

Could this be occurring because the `view()` method forwards the actual handling to a controller located in the vendor directory?

### Steps To Reproduce:
1. Start from clean Laravel installation.
2. Replace the contents of `routes/web.php` with the following
```
<?php

Route::view('/', 'welcome');
```
3. Run `php artisan route:list --except-vendor`

##### Expected Result
```
GET|HEAD  / .........................................................
```

##### Actual Result
```
Your application doesn't have any routes matching the given criteria.
```

**Comment by selcukcukur** [comment]
Isn't it normal for a new laravel install also to have a route included from the vendor package, which is why the app says so?

@AliSaleem27

**Comment by selcukcukur** [comment]
I did not encounter the problem you describe. @AliSaleem27

**Comment by karmadice** [comment]
@AliSaleem27 I using Laravel in same environment and I am not able to duplicate this behaviour. Maybe one of the package that you have used is causing it.
