### ISSUE TITLE
Cache::lock()->get() doesn't prevent race condition if two processes is concurrent

### ISSUE THREAD

**Issue by sayabakso** [laravel/framework#41410]
Laravel Version: v5.8 (but has been an issue for a long time)
PHP Version: 7.4
Queue Driver: Redis

I'm having an issue, I use Jmeter as well to send a request to dispatch 2 concurrent job to test race condition with redis atomic lock
After logging the result of redis setnx, both jobs got return value of 1
Apparently, the redis setnx cannot prevent race condition because the function itself can get into race condition situation
Maybe real world cases won't have 2 processes call redis setnx function at the same time, but knowing with Jmeter is still doesn't prevent race condition 100% make it a bit unreliable, but is this how it's supposed to be?

I'm using Laravel 5.8, and I know the code for acquiring lock is different in newer version. Is the newer one works better than in 5.8?
This is the code in 5.8 that I modify to include logging the result of redis setnx

```
public function acquire()
    {
        $result = $this->redis->setnx($this->name, $this->owner);

        \Log::info("Redis setnx result: $result");

        if ($result === 1 && $this->seconds > 0) {
            $this->redis->expire($this->name, $this->seconds);
        }

        return $result === 1;
    }
```

and this is the log
<img width="658" alt="Screen Shot 2022-03-09 at 23 17 27" src="https://user-images.githubusercontent.com/54876752/157483466-40c6c161-f251-447d-bff4-ac9659e6227e.png">

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
