### ISSUE TITLE
Can't seem to Update a single child of a oneToMany relationship

### ISSUE THREAD

**Issue by Designkago** [laravel/framework#41413]
- Laravel Version: 8.83.3
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.28

##### User Migration
```
Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->unique();
            $table->string('email')->unique();
            $table->string('first_name');
            $table->string('last_name');

```
##### Order Migration
```
Schema::create('orders', function (Blueprint $table) {
            $table->uuid('id');
            $table->foreign('id')->references('id')->on('users')->onDelete('cascade');
            $table->string('number')->unique();
            $table->string('client');
```

##### User Model
```
class User extends Authenticatable {
    use Uuid;

    /**
     * Get the orders associated with the user.
    */
    public function order() {
        return $this->hasMany(Order::class, 'id');
    }
```
##### Order Model
```
class Order extends Model {
    use Uuid;

    /**
     * Get the orders associated with the user.
    */
    public function user() {
        return $this->belongsTo(User::class, 'id');
    }
```
##### OrderController
```
$validator = Validator::make($request->all(), [
            'order_number' => 'required|string|min:2|max:100',
        ]);
        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'message' => 'Order number must be a string',
                'data' => $validator->errors()
            ], Response::HTTP_UNPROCESSABLE_ENTITY);
        }
        $order = Order::find($id)->where('number', $request->order_number)->first();
        $order->status = 'pending';
        $order->save();
```

This updates all order status to 'pending' instead of just a single order with the order 'number' as $request->order_number.

Any help in getting this done would be highly appreciated.

**Comment by netpok** [comment]
Please format your code with code blocks (tripple backticks):
````markdown
```php
    Your code here
```
````

**Comment by Designkago** [comment]
> Please format your code with code blocks (tripple backticks):
##### User Migration
```
Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->unique();
            $table->string('email')->unique();
            $table->string('first_name');
            $table->string('last_name');

```
##### Order Migration
```
Schema::create('orders', function (Blueprint $table) {
            $table->uuid('id');
            $table->foreign('id')->references('id')->on('users')->onDelete('cascade');
            $table->string('number')->unique();
            $table->string('client');
```

##### User Model
```
class User extends Authenticatable {
    use Uuid;

    /**
     * Get the orders associated with the user.
    */
    public function order() {
        return $this->hasMany(Order::class, 'id');
    }
```
##### Order Model
```
class Order extends Model {
    use Uuid;

    /**
     * Get the orders associated with the user.
    */
    public function user() {
        return $this->belongsTo(User::class, 'id');
    }
```
##### OrderController
```
$validator = Validator::make($request->all(), [
            'order_number' => 'required|string|min:2|max:100',
        ]);
        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'message' => 'Order number must be a string',
                'data' => $validator->errors()
            ], Response::HTTP_UNPROCESSABLE_ENTITY);
        }
        $order = Order::find($id)->where('number', $request->order_number)->first();
        $order->status = 'pending';
        $order->save();
```

**Comment by marvin-wtt** [comment]
What is the primary key for the Order Model?
Also I'd change the name from orders.id to orders.user_id to avoid confusion.

I don't think that this is an actual issue so I think it can be moved to the discussion section.

**Comment by Designkago** [comment]
> What is the primary key for the Order Model? Also I'd change the name from orders.id to orders.user_id to avoid confusion.
> 
> I don't think that this is an actual issue so I think it can be moved to the discussion section.

'id' is the primary key.

I'd like to know if there is a better way around it I wouldn't mind restructuring my code.
Thank you.

**Comment by marvin-wtt** [comment]
So in general, I would personally avoid using UUIDs as primary key because afaik they scale very bad performance wise.
But to come back to your problem:

You are using `id` as your primary key, but also declared it as a foreign key.

```php
    Schema::create('orders', function (Blueprint $table) {
            $table->uuid('id')->primary();  // Primary key of orders
            $table->uuid('user_id');  // UUID of the related user
            $table->string('number')->unique();
            $table->string('client');
            // ...

            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade'); // Refernece to the primary key in the users table
    }
```

I don't really understand what the `$id` parameter is referencing to. Is it the user id or the order id? And if it is the order id, what are you trying to accomplish with the number
Maybe you can post the function body and your route.

**Comment by AstonGemmy** [comment]
> So in general, I would personally avoid using UUIDs as primary key because afaik they scale very bad performance wise. But to come back to your problem:
> 
> You are using `id` as your primary key, but also declared it as a foreign key.
> 
> ```
>     Schema::create('orders', function (Blueprint $table) {
>             $table->uuid('id')->primary();  // Primary key of orders
>             $table->uuid('user_id');  // UUID of the related user
>             $table->string('number')->unique();
>             $table->string('client');
>             // ...
> 
>             $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade'); // Refernece to the primary key in the users table
>     }
> ```
> 
> I don't really understand what the `$id` parameter is referencing to. Is it the user id or the order id? And if it is the order id, what are you trying to accomplish with the number Maybe you can post the function body and your route.

This works. The foreign key constraint on 'id' was the problem. Thank you very much @marvin-wtt

However, I've got another problem. I am building a laravel API and I've tried uploading files but always get 'null' as file field in my request. I've been stuck with it for hours yet no solution. Any help would be highly appreciated as well. Thank you!

**Comment by netpok** [comment]
Also please note, that
```php
Order::find($id)->where('number', $request->order_number)->first();
```
is not doing what you are expecting.

`find()` will resolve a model and the where call will create a new query builder on it translating to:
```sql
select * from `orders` where `number` = '$request->order_number'
```

Meaning it's the same as:
```php
Order::where('number', $request->order_number)->first();
```

---

You probably want:
```php
Order::where('id', $id)->where('number', $request->order_number)->first();
```

Which will translate to:
```sql
select * from `orders` where `id` = '$id' and `number` = '$request->order_number'
```

**Comment by netpok** [comment]
@AstonGemmy There is a high chance you're file is too big, you should test it with a small file and if it works you need to set the `upload_max_filesize` and `post_max_size` in your php.ini.

The `post_max_size` should be big enough to handle both the uploaded files and any additional data so if you want to upload 5 4M files in a single form you need to set the `upload_max_filesize` to 4M and the `post_max_size` to at least 21M (5x4M + a little for anything else)

Also there is a chance your webserver is limiting it for example if your using nginx you need to set the `client_max_body_size` to at least 21M too in your nginx config.

**Comment by AstonGemmy** [comment]
> @AstonGemmy There is a high chance you're file is too big, you should test it with a small file and if it works you need to set the `upload_max_filesize` and `post_max_size` in your php.ini.
> 
> The `post_max_size` should be big enough to handle both the uploaded files and any additional data so if you want to upload 5 4M files in a single form you need to set the `upload_max_filesize` to 4M and the `post_max_size` to at least 21M (5x4M + a little for anything else)
> 
> Also there is a chance your webserver is limiting it for example if your using nginx you need to set the `client_max_body_size` to at least 21M too in your nginx config.

Well I don't think it's the file size because even a single file of 34kb isn't received by the server.

NOTE: It's an API and not a normal web app that laravel is kind of built for by default and I've been seeing posts about request headers when sending files in Laravel.

My observation is that other input values are received by the server except files.

In addition, I have a normal Laravel web app where file upload is working perfectly but that same code structure isn't working for the API I'm building currently.
That's where I don't understand what magic is happening. 😄

**Comment by netpok** [comment]
@AstonGemmy You can only send files in a multipart form request, see https://stackoverflow.com/questions/4083702/posting-a-file-and-associated-data-to-a-restful-webservice-preferably-as-json

@driesvints This issue turned into a giant support thread, I think it can be closed.

**Comment by Designkago** [comment]
> @Designkago The reason for updating all the relation is that it think id is your primary key, so it will try to update your model with it:
> 
> ```sql
> update `orders` set `status` = 'pending' where `id` = '$order->id';
> ```
> 
> Assuming order number is your primary key you need to define it on the model:
> 
> ```
> class Order extends Model
> {
>     protected $primaryKey = 'number'; // the primary key is the `number` column
>     protected $keyType = 'string'; // it's a string
>     public $incrementing = false; // and of course it's not incrementing (since it is a uuid string)
> }
> ```
> 
> You also want to help the database engine by defining it primary key instead of unique:
> 
> ```
> Schema::create('orders', function (Blueprint $table) {
>     $table->uuid('id');
>     $table->foreign('id')->references('id')->on('users')->onDelete('cascade');
>     $table->string('number')->primary();
>     $table->string('client');
> }
> ```
> 
> If this is not the case you need to create a primary key as laravel can't handle composite keys.
> 
> Also please note, that
> 
> ```
> Order::find($id)->where('number', $request->order_number)->first();
> ```
> 
> is not doing what you are expecting.
> 
> `find()` will resolve a model and the where call will create a new query builder on it translating to:
> 
> ```sql
> select * from `orders` where `number` = '$request->order_number'
> ```
> 
> Meaning it's the same as:
> 
> ```
> Order::where('number', $request->order_number)->first();
> ```
> 
> You probably want:
> 
> ```
> Order::where('id', $id)->where('number', $request->order_number)->first();
> ```
> 
> Which will translate to:
> 
> ```sql
> select * from `orders` where `id` = '$id' and `number` = '$request->order_number'
> ```
> 
> This have not caused a problem for you because the order number is unique, after setting the `$primaryKey` you can just simply use the following code to achieve current working:
> 
> ```
> Order::find($request->order_number);
> ```

This is perfectly understood and it works. Thanks a lot!

**Comment by AstonGemmy** [comment]
> @AstonGemmy You can only send files in a multipart form request, see https://stackoverflow.com/questions/4083702/posting-a-file-and-associated-data-to-a-restful-webservice-preferably-as-json
> 
> @driesvints This issue turned into a giant support thread, I think it can be closed.

Thank you very much @driesvints I have found a way through.

**Comment by driesvints** [comment]
Thanks all for helping out here 👍
