### ISSUE TITLE
handleLazyLoadingViolation shouldn't throw for newly created model instances

### ISSUE THREAD

**Issue by rogatty** [laravel/framework#41420]
- Laravel Version: 9.1.0
- PHP Version: 8.1.3
- Database Driver & Version: N/A

### Description:
https://github.com/laravel/framework/blob/91c60eaeb3534d57703b3251eb56839009bfd69d/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L517-L524

`HasAttributes::handleLazyLoadingViolation` shouldn't throw `LazyLoadingViolationException` if model instance was created in memory, and not fetched from the database. It's impossible to eager load relations for a model that doesn't exist yet. Throwing an exception in this scenario doesn't prevent unnecessary database queries and requires manual bypassing.

I solved it by adding the following to `AppServiceProvider`:
```
Model::handleLazyLoadingViolationUsing(
	static function (Model $model, string $relation) {
		// It's fine that you didn't eager load relations for a new model as it wouldn't make sense
		if (!$model->exists || $model->wasRecentlyCreated) {
			return;
		}

		throw new LazyLoadingViolationException($model, $relation);
	}
);
```

I believe this condition should be built into `HasAttributes::handleLazyLoadingViolation`.

### Steps To Reproduce:

Fixed by checking `!$model->exists`:
```
$model = ParentModel::make();
$childModel = ChildModel::make();
$model->children->push($childModel);
```

Fixed by checking `$model->wasRecentlyCreated`:
```
$model = Model::make();
$model->save();
$model->children->each(
	function (ChildModel $child) {
		$child->parent_id = $model->id;
		$child->save();
	}
);
```
`!$model->exists` isn't enough in the second case because relation wasn't initialized before saving the model.

### Why I bumped into this issue:

I expect the question "why do you use relations like that?" so let me answer upfront. I'm trying to use a DDD approach where the operations are split into stages (simplified):
- Load models from database
- Modify models – make new children instances and push them to relation collection (or not, depends on request data)
- Persist models to database - iterate over relation collection items, set the parent ID and save to database

**Comment by driesvints** [comment]
Heya, yes this seems reasonable to us. Can you send in a PR?
