### ISSUE TITLE
Route list sort option "precedence" does not work anymore

### ISSUE THREAD

**Issue by maarsson** [laravel/framework#41437]
- Laravel Version: 9.4.1
- PHP Version: 8.1.0
- Database Driver & Version: irrelevant

### Description:
The very handy feature sorting routes by their precedence by the `artisan route:list --sort=precedence` does not work anymore.

### Steps To Reproduce:
1. Install a fresh Laravel project
2. Run command `php artisan route:list --sort=precedence`
3. See error exception

**Comment by sedattcom** [comment]
Accepted values are host, method, uri, name, action or middleware.

**Comment by epixian** [comment]
Is `precedence` spelled correctly on the commandline?

**Comment by selcukcukur** [comment]
Sorting by precedence is currently not available.

**Comment by maarsson** [comment]
I spelled with an extra "n" consistently here, thanks @epixian. Issue is updated to the correct `precedence`.
Anyways the problem is still exists. I also took a closer look: it was working with framework 9.0.2 and stopped working from 9.1.0

**Comment by driesvints** [comment]
This value isn't an accepted one.
