### ISSUE TITLE
connect docker mysql error

### ISSUE THREAD

**Issue by miaotiao** [laravel/framework#41440]
- Laravel Version: 8.78.1
- PHP Version: 8.0.14
- Database Driver & Version:  mysql 5.7.36

### Description:

I can connect mysql by :

![image](https://user-images.githubusercontent.com/28383349/157893494-f815d47a-e173-4be1-a6d5-740d51cbc777.png)

but , laravel cant connect mysql，exception is ：

![image](https://user-images.githubusercontent.com/28383349/157893765-5ee97ecc-620e-4439-b456-ad05a8ae3965.png)

Maybe the reason is mysql PDO ?

**Comment by epixian** [comment]
Check to make sure your `.env` is updated with the correct username and password.

**Comment by miaotiao** [comment]
> Check to make sure your `.env` is updated with the correct username and password.

username and password is correct .

**Comment by epixian** [comment]
```
DB_CONNECTION=mysql
DB_HOST=localhost # <-- for docker, this is the container running mysql in your docker-compose.yml, see below
DB_PORT=3306
DB_DATABASE=bill
DB_USERNAME=root
DB_PASSWORD=123123
```
```
# docker-compose.yml

  mysql: # <-- container name running mysql
    ...
    ports:
     - "${DB_PORT}:3306"
```
Also make sure your app and database containers are on the same network.

**Comment by miaotiao** [comment]
> ```
> DB_CONNECTION=mysql
> DB_HOST=localhost # <-- for docker, this is the container running mysql in your docker-compose.yml, see below
> DB_PORT=3306
> DB_DATABASE=bill
> DB_USERNAME=root
> DB_PASSWORD=123123
> ```
> 
> ```
> # docker-compose.yml
> 
>   mysql: # <-- container name running mysql
>     ...
>     ports:
>      - "${DB_PORT}:3306"
> ```
> 
> Also make sure your app and database containers are on the same network.

database is running in docker， and app running on my windows10

**Comment by miaotiao** [comment]
![image](https://user-images.githubusercontent.com/28383349/157900188-fef6800b-7389-461a-88ad-52d01d5f8d60.png)

**Comment by epixian** [comment]
`(using password: NO)` tells me that your app is not sending a password when trying to connect.  If your .env is correct as you say, make sure `config/database.php` isn't overriding it.  You can also try `php artisan config:clear`.

**Comment by stevebauman** [comment]
Hi @miaotiao,

Don't use `localhost`, use `127.0.0.1`. This should resolve your issue 👍

**Comment by miaotiao** [comment]
> `(using password: NO)`告诉我您的应用在尝试连接时未发送密码。如果您的 .env 如您所说是正确的，请确保`config/database.php`没有覆盖它。你也可以试试`php artisan config:clear`。



> `(using password: NO)`告诉我您的应用在尝试连接时未发送密码。如果您的 .env 如您所说是正确的，请确保`config/database.php`没有覆盖它。你也可以试试`php artisan config:clear`。

You are right! Thanks!

> `(using password: NO)` tells me that your app is not sending a password when trying to connect. If your .env is correct as you say, make sure `config/database.php` isn't overriding it. You can also try `php artisan config:clear`.

You are right! Thanks!

**Comment by miaotiao** [comment]
> `(using password: NO)` tells me that your app is not sending a password when trying to connect. If your .env is correct as you say, make sure `config/database.php` isn't overriding it. You can also try `php artisan config:clear`.

You are right! Thanks!

**Comment by miaotiao** [comment]
> Hi @miaotiao,
> 
> Don't use `localhost`, use `127.0.0.1`. This should resolve your issue 👍
> 
> I've had issues with using `localhost`. It appears it may be something to do with PDO in PHP not resolving `localhost`, but I haven't dug deep enough to be sure.
> 
> Though these types of questions should be moved to discussions or to a forum. Laravel GitHub issues are for bug reports only.

OK, I thought it`s bug before i found the answer.... Sorry

**Comment by stevebauman** [comment]
No need to apologize @miaotiao 🙏
