### ISSUE TITLE
[9.x] calling Collection::implode('_') throws error

### ISSUE THREAD

**Issue by taka-oyama** [laravel/framework#41466]
- Laravel Version: 9.x-dev
- PHP Version: 8.0.16

### Description:
The following pull request broke parts of our code.
https://github.com/laravel/framework/pull/41405

### Steps To Reproduce:

```php
collect([1,2,3])->implode('_')
```

Throws the following error.

```
_() expects exactly 1 argument, 2 given 
```

This is because '_' is a function defined by the gettext extension.

Checking with `is_callable` is probably not suitable here.

**Comment by eusonlito** [comment]
Fix PR pending to merge https://github.com/laravel/framework/pull/41468
