### ISSUE TITLE
Ignition solution not appearing

### ISSUE THREAD

**Issue by WalterWoshid** [laravel/framework#41484]
- Laravel Version: 9.4.1
- PHP Version: 8.1.2

### Description:
I added a custom exception which implements `Facade\IgnitionContracts\ProvidesSolution`, but it doesn't appear on the error page.

FfprobeLengthException.php:
```php
<?php

namespace App\Exceptions;

use Exception;
use Facade\IgnitionContracts\BaseSolution;
use Facade\IgnitionContracts\ProvidesSolution;
use Facade\IgnitionContracts\Solution;

class FfprobeLengthException extends Exception implements ProvidesSolution
{
    public function getSolution(): Solution
    {
        return BaseSolution::create('There was an error with the ffprobe command')
            ->setSolutionDescription("The video file may be invalid");
    }
}
```

RunCode.php
```php
use App\Exceptions\FfprobeLengthException;

throw new FfprobeLengthException("Could not get video length");
```

Result:
![image](https://user-images.githubusercontent.com/36635504/158341535-d92e75cf-d3d7-48e8-8e62-ea2dc9a76ac6.png)

**Comment by driesvints** [comment]
Heya, we don't maintain this code. Please post an issue on the spatie ignition tracker.

**Comment by WalterWoshid** [comment]
@driesvints Oh, I thought you guys would maintain this code, thanks for the info :)
