### ISSUE TITLE
HTTP Client beforeSending does not take callables

### ISSUE THREAD

**Issue by MariusTechweb** [laravel/framework#41486]
- Laravel Version:  8.7
- PHP Version: 8.1
- Database Driver & Version: 5.7

### Description:

The `beforeSending` method on the `PendingRequest` class says that it takes a `callable $callback`, however, this is not entirely true. When the callback is called, it is done so using `$callback->__invoke(...)` and not `$callback(...)`. This makes the following syntax result in error "`Call to a member function __invoke() on array`":

```php
protected function buildRequest(): PendingRequest
{
    return Http::baseUrl('https://api.example.org')
        ->beforeSending([ $this, 'prepareRequest' ])
        ->asJson()
        ->withoutVerifying();
}

protected function prepareRequest(Request $request, array $options, PendingRequest $pendingRequest)
{
    $headers = [
        'X-Test-A' => 'test',
        'X-Test-B' => 'test',
        'X-Test-C' => 'test',
    ];

    $pendingRequest->withHeaders($headers);
}
```

I expect the code above to execute the `prepareRequest` method as the callable with the params passed. This happens if the callback would be called using `$callback(...)`.

### Steps To Reproduce:

1. Create a PendingRequest using Http fascade.
2. Set `beforeSending` to a callable referencing method on object using array syntax as demonstrated in description example,
3. Send request.
4. See error.

**Comment by driesvints** [comment]
Thanks, I've sent in a PR for this: https://github.com/laravel/framework/pull/41489
