### ISSUE TITLE
Test command with parallel and recreate-databases does not recreates databases

### ISSUE THREAD

**Issue by bastien-phi** [laravel/framework#41492]
- Laravel Version: 9.5.1
- PHP Version: 8.1.2
- Database Driver & Version: Postgresql 13

### Description:

Running `php artisan test --parallel --recreate-databases` with pest does not recreates databases. Not sure why, I looked a bit a this problem but I did not find any clue. Not even sure the problem is located in Laravel...

It looks like to work with PHPUnit.

For information, I'm using :
nunomaduro/collision: 6.1.0
laravel/framework: 9.5.0
pestphp/pest: 1.21.2
pestphp/pest-plugin-parallel: 1.0.0
brianium/paratest: 6.4.3

**Comment by driesvints** [comment]
> Not even sure the problem is located in Laravel...

Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by bastien-phi** [comment]
Thanks @driesvints 

The problem indeed does not comes from the framework (https://github.com/pestphp/pest/issues/501)
