### ISSUE TITLE
Illuminate\Http\Resources\Json\JsonResource::__construct() & Illuminate\Support\Traits\EnumeratesValues::mapInto() cause unexpected behavior.

### ISSUE THREAD

**Issue by Smoggert** [laravel/framework#41493]
- Laravel Version: 8.83.4
- PHP Version: 7.3.27
- Database Driver & Version: N/A

### Description:
Json resource's constructor is being misused when triggering mapInto by for example using 
`JsonResource::collect();`

JsonResource's constructor:
```php
    public function __construct($resource)
    {
        $this->resource = $resource;
    }
```

How i's being used:
```php
trait EnumeratesValues

// ...
    /**
     * Map the values into a new class.
     *
     * @param  string  $class
     * @return static
     */
    public function mapInto($class)
    {
        return $this->map(function ($value, $key) use ($class) {
            return new $class($value, $key);
        });
    }
```

Extending the resource without DEEP knowledge of the underlying system causes unexpected behavior because the constructor of JsonResource doesn't correctly imply that it can receieve a 2nd argument (a collection key)

### Steps To Reproduce:
1 / Extend a JsonResource with an aditional parameter in the constructor.
2/ Create a custom ResourceCollection with said extended Resource.
`$collects = \App\Http\Resources\MyNewExtendedResource`

3/ Watch as your new added logic in the constructor gets butchered by random collection keys.

### Steps To Solve:

Use a JsonResource specific mapInto that doesn't pass collection-keys.

or

add a mixed `$key `as optional 2nd argument to the constructor of a resource.

**Comment by driesvints** [comment]
> Extend a JsonResource with an aditional parameter in the constructor.

Please don't do this. This isn't supported.
