### ISSUE TITLE
MS SQL Server migration not working

### ISSUE THREAD

**Issue by manojmilani** [laravel/framework#41515]
- Laravel Version: 8.61.0
- PHP Version: 7.3.33
- Database Driver & Version:  sqlsrv & 2019

I am getting below error when I run the command php artisan migrate

SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'xxxxx_id_foreign' on table 'xxxxx' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints. (SQL: alter table "xxxxx" add constraint "xxxxx_id_foreign" foreign key ("xxxxx_id") references "xxxxx" ("id") on delete cascade on update cascade)

We have assigned cascading on multiple columns for one table in our migration files.

### Steps To Reproduce:

1. Create a table called events

```
Schema::create('events', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedBigInteger('user_id');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreignId('access_method_id')->nullable()->constrained('access_methods')->onUpdate('cascade')->onDelete('cascade');
            $table->timestamps();
        });
```

2. Run the command `php artisan migrate`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
