### ISSUE TITLE
Merging http data resetting its index

### ISSUE THREAD

**Issue by aldesrahim** [laravel/framework#41511]
Hello, i've some issue with Http Client, please take a look. Thank you !

https://github.com/laravel/framework/blob/650ca875d3bd7e876ed89f803c705d5d6c121d90/src/Illuminate/Http/Client/PendingRequest.php#L745-L747

in above code, `parseHttpOptions()` merge `$options` from `send(string $method, string $url, array $options = [])`, this could be an issue for data like this:
```
$data = [
    '990240202' => config('auth.username'),
    '990240302' => config('auth.password'),
]
```

example code `Http::asForm()->post('https://example.com', $data);`, when using `dd()` to display request output this is what i got:
```
Illuminate\Http\Client\Request {[#337 ▼]()
  #request: GuzzleHttp\Psr7\Request {[#335 ▶]()}
  #data: array:2 [[▼]()
    0 => "username"
    1 => "password"
  ]
}
```

it should have been like this:
```
Illuminate\Http\Client\Request {[#337 ▼]()
  #request: GuzzleHttp\Psr7\Request {[#335 ▶]()}
  #data: array:2 [[▼]()
    990240202 => "username"
    990240302 => "password"
  ]
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by aldesrahim** [comment]
Hi, thanks for your response. thank you for suggesting me, i'll try to post on forums/links you have suggested.

just curiosity, is that behavior (the one i reported) intentional ? Thank you in advanced.
