### ISSUE TITLE
Builder::whereDate() prevents the use of indexes

### ISSUE THREAD

**Issue by NickStallman** [laravel/framework#41522]
- Laravel Version: ^8
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0

### Description:

Using Builder::whereDate() forces the WHERE condition to wrap the column name in the MySQL DATE() function, this is quite detrimental as it means MySQL needs to process the value of every single column, and it precludes the use of indexes.

I think my use case is a fairly common one, I have a table that grows over time, and a query where I want to filter just the rows from the last 7 days for example.
I had a index on the TIMESTAMP field to ensure a this filtering could be done efficiently.

My code seemed to be quite logical, using the ideal :
```php
Model::whereDate('created_at', '>', now()->subDays(30)->setTime(0, 0, 0)->toDateTimeString())
```

This exact query is actually in the documentation.
```
The whereDate method may be used to compare a column's value against a date:

$users = DB::table('users')
                ->whereDate('created_at', '2016-12-31')
                ->get();
```

However this resulted in the p90 latency of my application doing this:
![image](https://user-images.githubusercontent.com/136553/158699539-473d2778-f522-45e5-968e-11fdda472c98.png)

I'm not sure exactly what the solution here is, as after looking at it in detail whereDate is to make it easier to do date based comparisons, not really for a comparison like my query.
However these date based functions are guarenteed never hit any index which is far from ideal especially since filtering data by dates is an extremely common use case. The current implementation is guarenteed to make slower queries.

Perhaps the generated queries should be rewritten?
Rather than
```
WHERE DATE(created_at) = '2016-12-05'
```
The same functionality can be queried better by changing it to:
```
WHERE (created_at >= '2016-12-05' AND created_at < '2016-12-06')
```
Since that avoids putting any database functions around the column, and thus the database doesn't work anywhere near as hard, and indexes can be used.

**Comment by driesvints** [comment]
Isn't the solution here to just not use `whereDate`? That method was indeed specifically created to make use of SQL's `DATE` function. We cannot know upfront which columns use indexes.

**Comment by driesvints** [comment]
I think it's best to just avoid usage of that method here.

**Comment by NickStallman** [comment]
Yes that was my solution, however reading the documentation you'd never realise that whereDate is a terrible solution in it's current form in many use cases.
The example usage is very similar to my real world usage but I don't think that latency graph is "working well and as expected".

The documentation should at least note that database indexes will never be used with any of those date/time functions.

And it would be ideal to fix the functions so they work as designed and generate queries which can be use indexes.

**Comment by rebbieboi** [comment]
They should specify in the documentation that whereDate will not be able to use the indexes. We all use these functions for convenience not knowing the bottleneck they will bring and they need to define that.

**Comment by SilvioDoMine** [comment]
I can confirm this is still happening in Laravel 9.x

**Comment by chamyeongdo** [comment]
I wasted a day because of this

**Comment by horaceho** [comment]
`whereBetween` is an alternative:
```
$date = Carbon::parse(`2016-12-31`);

$users = DB::table('users')
    ->whereBetween('created_at', [
        $date->clone()->startOfDay(),
        $date->clone()->endOfDay(),
    ])
    ->get();
```
Credit: https://dev.to/nicolus/how-to-properly-retrieve-laravel-models-between-two-dates-1bek
