### ISSUE TITLE
Collection select()

### ISSUE THREAD

**Issue by roberto-butti** [laravel/framework#41536]
### Discussed in https://github.com/laravel/framework/discussions/41521

<div type='discussions-op-text'>

<sup>Originally posted by **roberto-butti** March 16, 2022</sup>
- Class: Collection
- Method: select()

When you have a bi dimensional array like this one (an array of associative arrays):
```
    [
            ['product' => 'Desk', 'price' => 200, 'active' => true],
            ['product' => 'Chair', 'price' => 100, 'active' => true],
            ['product' => 'Door', 'price' => 300, 'active' => false],
            ['product' => 'Bookcase', 'price' => 150, 'active' => true],
            ['product' => 'Door', 'price' => 100, 'active' => true],
        ]
```
You can apply method for filtering (**where()**), sorting (**sortBy()**) and so on ...
If you want to select and "pick" just few keys or columns or fields, probably, as a developer, you want to use a method to specify the keys you want:
```
$collection->select(["product", "price"])
        ->where("price", ">", 100)
        ->sortBy("price")
        ->all()
```
I would like to suggest implementing "**select**()" method where the developer can define a list of keys to "extract".
Think to a bi- dimensional array like a db table where you have columns, and you need to perform a select operation to select just some columns.

The result is something like that:
```php
$a = Collection::make(
    [
            ['product' => 'Desk', 'price' => 200, 'active' => true],
            ['product' => 'Chair', 'price' => 100, 'active' => true],
            ['product' => 'Door', 'price' => 300, 'active' => false],
            ['product' => 'Bookcase', 'price' => 150, 'active' => true],
            ['product' => 'Door', 'price' => 100, 'active' => true],
        ]
)
        ->select(["product", "price"])
        ->where("price", ">", 100)
        ->sortBy("price")
        ->all();
var_export($a);
/*
array (
  3 =>
  array (
    'product' => 'Bookcase',
    'price' => 150,
  ),
  0 =>
  array (
    'product' => 'Desk',
    'price' => 200,
  ),
  2 =>
  array (
    'product' => 'Door',
    'price' => 300,
  ),
)
*/
```

I could have the code already implemented. I added also the static method to Arr class.
If you agree with this suggestion, I can open a PR, if not: "amici come prima 🇮🇹 " 🥳 
</div>

**Comment by driesvints** [comment]
Please keep feature requests in the Discussions section, thanks.
