### ISSUE TITLE
Duplicated Events when shouldDiscoverEvents is true

### ISSUE THREAD

**Issue by SupianIDz** [laravel/framework#41558]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.28

### Description:
When events are registered manually and `shouldDiscoverEvents` returns `true` there will be duplication of Event Listener.

Based on the code snippet below, the Listener should be unique when it will be registered.

https://github.com/laravel/framework/blob/a25eb78d289186a099de60614612f4fda7f7eccb/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php#L90-L93

https://github.com/laravel/framework/blob/a25eb78d289186a099de60614612f4fda7f7eccb/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php#L40-L46

## `shouldDiscoverEvents = false`
<img width="923" alt="Screen Shot 2022-03-18 at 21 10 43" src="https://user-images.githubusercontent.com/37969970/159009509-629d27c7-e633-47ab-ac92-7b7eb930efa6.png">

## `shouldDiscoverEvents = true`
<img width="927" alt="Screen Shot 2022-03-18 at 21 11 02" src="https://user-images.githubusercontent.com/37969970/159009496-a1cc659c-6bfc-4eb7-8db8-eb2db7a288e5.png">

### Steps To Reproduce:
1. Create event and listener
2. Manually Registering Events
3. Set `shouldDiscoverEvents` to `true`

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by SupianIDz** [comment]
> Heya, thanks for reporting.
> 
> We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.
> 
> ```shell
> laravel new bug-report --github="--public"
> ```
> 
> Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.
> 
> Thanks!

https://github.com/SupianIDz/bug-report/tree/duplicated-event

**Comment by SupianIDz** [comment]
> Heya, thanks for reporting.
> 
> We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.
> 
> ```shell
> laravel new bug-report --github="--public"
> ```
> 
> Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.
> 
> Thanks!

https://github.com/SupianIDz/bug-report/tree/duplicated-event

<img width="950" alt="Screen Shot 2022-03-18 at 21 45 17" src="https://user-images.githubusercontent.com/37969970/159014093-df029fda-55e4-475c-bd34-0a53955b34b3.png">

**Comment by driesvints** [comment]
This is normal. You've both enabled event discovery and manually registered the event. You need to do one or the other.
