### ISSUE TITLE
Fallbacks not working with .json translation files

### ISSUE THREAD

**Issue by felipe-dsdev** [laravel/framework#41565]
- **Laravel Version:** 9.4.1
- **PHP Version:** 8.1.1
- **Database Driver & Version:** MySQL 8.0.28 for Linux on x86_64

### Description:
Fallbacks not working with .json translation files

### Steps To Reproduce:

- In configuration
  - Add any language as default language
  - Add other language as fallback language
- Create an empty .json file for these languages
- In .json of fallback language add a key with translation
- In your code call this translation with the key (added in previous step)

**Comment by felipe-dsdev** [comment]
To fix this behavior I modified the method bellow:
https://github.com/laravel/framework/blob/6094c427834827b9932f848b6a37d788c181e814/src/Illuminate/Translation/Translator.php#L100-L135

I added the following code after line 109:
```php
if ($fallback && $line === null) {
    $this->load('*', '*', $this->fallback);
    $line = $this->loaded['*']['*'][$this->fallback][$key] ?? null;
}
```

The complete code:

```php
public function get($key, array $replace = [], $locale = null, $fallback = true) 
{ 
    $locale = $locale ?: $this->locale; 

    // For JSON translations, there is only one file per locale, so we will simply load 
    // that file and then we will be ready to check the array for the key. These are 
    // only one level deep so we do not need to do any fancy searching through it. 
    $this->load('*', '*', $locale); 

    $line = $this->loaded['*']['*'][$locale][$key] ?? null;

    if ($fallback && $line === null) {
        $this->load('*', '*', $this->fallback);
        $line = $this->loaded['*']['*'][$this->fallback][$key] ?? null;
    }

    // If we can't find a translation for the JSON key, we will attempt to translate it 
    // using the typical translation file. This way developers can always just use a 
    // helper such as __ instead of having to pick between trans or __ with views. 
    if (! isset($line)) { 
        [$namespace, $group, $item] = $this->parseKey($key); 
  
        // Here we will get the locale that should be used for the language line. If one 
        // was not passed, we will use the default locales which was given to us when 
        // the translator was instantiated. Then, we can load the lines and return. 
        $locales = $fallback ? $this->localeArray($locale) : [$locale]; 
  
        foreach ($locales as $locale) { 
            if (! is_null($line = $this->getLine( 
                $namespace, $group, $locale, $item, $replace 
            ))) { 
                return $line; 
            } 
        } 
    } 

    // If the line doesn't exist, we will return back the key which was requested as 
    // that will be quick to spot in the UI if language keys are wrong or missing 
    // from the application's language files. Otherwise we can return the line. 
    return $this->makeReplacements($line ?: $key, $replace); 
} 
```

**Comment by driesvints** [comment]
The current code works as intended. With JSON translations, there is no usage of a fallback language. The key is the translation.

**Comment by felipe-dsdev** [comment]
Okay, I will implement it directly in my code. Thanks.

**Comment by chludwig** [comment]
But it would be nice to have the opportunity to have a "changeable" fallback language.

Three use cases.

1. Changing the default translation
If there is a typo in the default (fallback) translation. Currently you'll have to find and replace all appearances of this string, in every template and every other languages. This can only be done by a global search and replace.  
If the fix is merged, you simply have to create a language file for the default (fallback) language and can add the key with the typo and the corrected text it in the value.

2. The translation has variations
If you'll have an English word, that has multiple meanings in other languages. It's impossible to handle this with json files only because you would have to use the same key twice. 

3. Changing the fallback language
The most horrible use case because you'll have to search for every keys in every view files and language files and replace them with the strings of the new fallback language. It would be so easy, simply changing the value of "fallback_language" in the config/app.php file.

In all use cases you'll have to swap back to the php files where all these problems can be solved with a fingertip. Why is the user forceed to do so. It wouldn't be a breaking change when handling json translation files in the same way as php translation files, or would it?

**Comment by andrey-helldar** [comment]
I also faced the problem while testing the application.

`config/app.php`:

```php
return [
    'locale' => 'en',
    'fallback_locale' => 'fr',
];
```

`lang/fr.json`:

```json
{
    "All rights reserved.": "Tous droits réservés."
}
```

`lang/en.json` doesn't exist.

```php
return __('All rights reserved.');
// Returned "All rights reserved." instead of "Tous droits réservés."
```

Personally, this behavior misleads me, given that there are no such problems when using php files.

**Comment by andrey-helldar** [comment]
@felipe-dsdev, as a temporary solution, I used your code by creating a [Laravel-Lang/json-fallback-hotfix](https://github.com/Laravel-Lang/json-fallback-hotfix) project.

To get the latest version of [`Laravel Lang: JSON Fallback Hotfix`](https://github.com/Laravel-Lang/json-fallback-hotfix), simply require the project using Composer:

```bash
composer require laravel-lang/json-fallback-hotfix
```

Next, in the `providers` section of the `config/app.php` file, replace `Illuminate\Translation\TranslationServiceProvider::class`
with `LaravelLang\JsonFallbackHotfix\TranslationServiceProvider::class`.

Compatible with Laravel 6-9.

**Comment by bmellink** [comment]
Thanks @andrey-helldar. works like a charm. 

@driesvints you indicate  "The current code works as intended" but others (including me) do not seem to agree. Can you elaborate on this? There are multiple use cases as indicated by @chludwig and I can think of a few more (for instance to ensure there is always a logical message on the screen (in the fallback language) when new code is deployed, even if translation in a less important target language is still using an older version of the json file that does not yet include the new strings). Please reconsider to include the change in the main code branch.

**Comment by andrey-helldar** [comment]
Indeed, if the language of the fallback application is English, then there are no problems, but since this option is placed in the configuration file and allows you to change the localization, then, I think, it will be correct to change the json keys too, and not just php.

**Comment by dac-humi** [comment]
I have found that if I do something like this in a HTTP middleware, the feature is re-enabled. 🤷‍

```php
app()->setLocale($lang1)
app()->setFallbackLocale($lang2)
```

**Comment by andrey-helldar** [comment]
> I have found that if I do something like this in a HTTP middleware, the feature is re-enabled. 🤷‍
> 
> ```
> app()->setLocale($lang1)
> app()->setFallbackLocale($lang2)
> ```

Json keys doesn't works with this way.

**Comment by dac-humi** [comment]
My mistake.

**Comment by nielspeen** [comment]
Ran into this as I was puzzled why I had short keywords show up in new languages as opposed to my expected fallback texts from en.json.

Having the key function as the fall-back has a big downside: if you ever decide you need a better fallback text you are forced to update the key in all json language files.

The hotfix provided by @andrey-helldar works with Laravel 10. Please reconsider changing this in Laravel itself.

**Comment by func0der** [comment]
> The current code works as intended. With JSON translations, there is no usage of a fallback language. The key is the translation.

@driesvints Where does it say that in the documentation?

Here it says: https://laravel.com/docs/12.x/localization#configuring-the-locale

>You may also configure a "fallback language", which will be used when the default language does not contain a given translation string. Like the default language, the fallback language is also configured in the config/app.php configuration file, and its value is typically set using the APP_FALLBACK_LOCALE environment variable.

So how would one know that this apparently does not work with json files, (but with PHP maybe?)

If this issues does not quality for changes in the code, it should at least qualify for some changes in the docs.

**Comment by func0der** [comment]
@andrey-helldar Thanks for the quick reply. I mean, you could read it like that, I guess.

Either way it is confusing to say the least that if I use short keys vs. translation strings which are both basically just identifiers in a key value store, the behaviour changes that significantly.

**Comment by andrey-helldar** [comment]
> Either way it is confusing to say the least that if I use short keys vs. translation strings which are both basically just identifiers in a key value store, the behaviour changes that significantly.

I agree. This behavior is completely unobvious and contradictory.

**Comment by kronthto** [comment]
I too think the current behaviour excluded valid use-cases, like: 
- Application strings are mainly coded in German
- English translations are complete
- Swedish translations are incomplete, so fallback_locale=en would be preferable to falling back to German strings on the Swedish view

Are there any issues with the suggested code-change?

The current implementation also weirdly pollutes the `loaded` Array with group entries for each attempted string.
