### ISSUE TITLE
Bootstrap config file showing env secret keys

### ISSUE THREAD

**Issue by videsh-4433** [laravel/framework#41567]
- Laravel Version: 7.0
- PHP Version: 7.4.0
- Database Driver & Version: MySql  8.0.27

### Description:
I have an issue with bootstrap cache files, because the bootstrap folder always need read write permission and when i am giving this permission the config.php file inside bootstrap/cache folder are showing my secret keys like all env variables are showing over there, So this issue will compromise my personal keys, please let me know how can i hide this. Thanks

**Comment by mikeydevelops** [comment]
Yes that is how Laravel caches configuration, by default the cache folder in bootstrap is ignored from git,  so it won't be uploaded and no secrets will be shared.
And in terms of public access, this is what the public forlder is for. You configure your server to allow access to the public folder only, anything else should not be accessable if it is, you have misconfigured your server.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
