### ISSUE TITLE
[9.x] Collection `times` method type error (phpstan)

### ISSUE THREAD

**Issue by fragkp** [laravel/framework#41566]
- Laravel Version: 9.5.1
- PHP Version: 8.1.x
- Database Driver & Version: -

### Description:

PHPStan reports an error when the collection method `times` is called without the callback parameter.
Note: This behaviour is not [documented](https://laravel.com/docs/9.x/collections#method-times).

_Unable to resolve the template type TTimesValue in call to method static method Illuminate\Support\Collection<(int|string), mixed>::times()_

### Steps To Reproduce:

```php
Collection::times(42);
```

### Possible Solution

I couldn't find a good solution. `@return static<int, int|TTimesValue>` didn't fix the problem.

Maybe it would be better to require the 2nd parameter callback. In addition, allow a single parameter for the `range` method.

**Comment by driesvints** [comment]
Hey. No code is broken here so this isn't a bug. If you want to fix a phpstan issue we appreciate prs. Thanks.

**Comment by fragkp** [comment]
Hey @nunomaduro,

maybe you could give me a hint on how to fix this problem? 😃 Would sent than a PR.
