### ISSUE TITLE
Eloquent bug

### ISSUE THREAD

**Issue by Traqza** [laravel/framework#41583]
- Laravel Version: 8.83.4
- PHP Version: 8

Apologies on title, not sure how to title it...

If you had a list of say 10 customers; and you attempted to view any of the customers. It would result in the viewing of one particular customer (customer would not be the first record in the system). The UUID of the customer would change, but the outcome would be the same.

model method of

```
    public static function getCustomerById($id): UuidInterface
    {
        return self::where('id', $id)->first();
    }

```

Mistakenly added `firstOrFail()` onto the model method from within the controller view method.

```
     $customer = Customer::getCustomerById($id)->firstOrFail()
```

 -- High level footnote; You want to view customer A, it will show C, if you tried customer B, it would show C. E to C, F to C.

I'm not sure how you could yield an error from chaining a `first()` and a `firstOrFail()` together but this was a weird bug that I thought could be prevented -- Ideally from the developer, but just in case error result?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
