### ISSUE TITLE
Laravel 9 Remove Headers from Amazon SES Transport

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/framework#41585]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 5.7

### Description:
After upgrade Laravel 9 I not receive SES Message ID from Header

### Steps To Reproduce:
vendor/laravel/framework/src/Illuminate/Mail/Transport/SesTransport.php (old set)
![image](https://user-images.githubusercontent.com/5731295/159186322-4ec80462-9503-44d3-82c1-8288d6c97dc9.png)
vendor/laravel/framework/src/Illuminate/Mail/Transport/SesTransport.php (new set)
![image](https://user-images.githubusercontent.com/5731295/159186368-e4733b04-66f4-4544-8ac3-184c2371c8d8.png)

My Procedure Failed until check
![image](https://user-images.githubusercontent.com/5731295/159186422-aae4f841-5cde-48f6-94b1-331460e309d4.png)

**Comment by driesvints** [comment]
You need to use the `$sent` property on the message instead to get the correct message header. With this you can use `getMessageId` which will return the correct message ID. This got changed with the new Symfony Mailer implementation. I'll send a note to the upgrade guide.

`$event->sent->getMessageId()`

**Comment by driesvints** [comment]
Here: https://github.com/laravel/docs/pull/7819

**Comment by massimodellarovere** [comment]
Now the problem is that MessageId is not same value the X-SES-Message-Id.. Message Id is create from Symphony with domain used.. But the Amazon call API SES return an value different that is important for check the notifications above status message as BOUNCED, DELIVERED etc.. Amaozn not use MessageId generated Synphony.. In version 8 MessageId e SesMessageid has same value. But Now en Laravel 9 MessageId has a value and SES Messageid tha is different now is not present..
