### ISSUE TITLE
Error using AWS SDK in artisan command

### ISSUE THREAD

**Issue by uz-bueno** [laravel/framework#41590]
- Laravel Version:  8.83.0
- PHP Version: 7.4.28
- Database Driver & Version:
mysql 5.7

### Description:

An exception is thrown when trying to create an instance of Aws\Ssm\SsmClient in an artisan command:

```bash
  Call to undefined function Aws\is_valid_hostlabel()

  at vendor/aws/aws-sdk-php/src/ClientResolver.php:1052
    1048▕      * @return bool
    1049▕      */
    1050▕     private static function isValidRegion($region)
    1051▕     {
  ➜ 1052▕         return is_valid_hostlabel($region);
    1053▕     }
    1054▕ }
```

I have added the same code in a route handler and it works without issues, but does not work on artisan command.

### Steps To Reproduce:

```bash
composer require aws/aws-sdk-php

php artisan make:command GenerateEnv --command="env:generate"

# Add this code in the handle method of command
use Aws\Ssm\SsmClient;

...

$client = new SsmClient([
     'region' => 'us-west-2',
     'version' => '2014-11-06',
]);

# Execute command
php artisan env:generate
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
