### ISSUE TITLE
Http:retry(...) does not retry request when throw param is set to false

### ISSUE THREAD

**Issue by Cintrust** [laravel/framework#41601]
- Laravel Version: 9.2.0
- PHP Version: 8.1.0
- Database Driver & Version: MSQL v8.0.27

### Description:
Calling `Http::retry(3, 100, function(){return true} ,throw: false)->post(...);` does not retry the request but returns the response of the first attempt.

### Steps To Reproduce:
run `php artisan tinker` and paste the following code.
or just paste it inside any controller
```php
$response = Http::retry(3, 100,function($e){
 report($e);
return true;
},   false)->post("https://sandbox.monnify.com/api/v2/bank-transfer/reserved-accounts");
```
check logs. No error would be reported

**Comment by JawadR1** [comment]
It is retrying. According to [Laravel documention](https://laravel.com/docs/9.x/http-client#retries)

> When throw exception is disabled, the last response received by the client will be returned after all retries have been attempted

Please try a Laravel forum if you need more information.

**Comment by eduance** [comment]
In addition to what @JawadR1 has posted I wanted to confirm that it was actually retrying the given request.

`Http::retry(3, 100, function ($exception) {
    report($e);
}`

The `retry()` method simply sets some properties within the PendingRequest class, free of charge! 

However, it is important to understand what those properties will end up being used for. Like grannie always tell me, you can have loads of properties, as long as you make some profit on them.

The first parameter is the amount of tries, the second is the time in between the requests and the third is a parameter named when which basically asks the developer: **when** do you want to retry?

Therefore the report() function doesn't make sense within this callback, as the docs say:

`The third argument should be a callable that determines if the retries should actually be attempted. For example, you may wish to only retry the request if the initial request encounters an ConnectionException.`

Now, my last point was that I wanted to make sure that I wasn't being too hasty with my answer and wanted to make sure that it did actually try to retry the request. The `post()` method calls the `send()` method which ends up calling the retry() helper. 

This method has a beautiful test written for it and works like a charm and has last been tested less than a month ago, feel free to check it out here: 

https://github.com/laravel/framework/blob/9.x/tests/Support/SupportHelpersTest.php#L572

If you are too lazy to find out all that, you can simply copy & paste the command I quickly used to check if the retry() helper functioned properly:

`<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use RuntimeException;

class TestRetries extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'request:retry';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @throws \Exception
     */
    public function handle()
    {
        $attempts = retry(2, function ($attempts) {
            if ($attempts > 1) {
                return $attempts;
            }

            throw new RuntimeException;
        }, 100);

        echo $attempts;
    }
}`

Last but not least, as has been pointed out by @JawadR1 we can say that everything is working as supposed to as the last boolean accepted by the `Http::retry()` method is whether you want the method to throw a guaranteed `RequestException` or to just output the last response.

Hopefully this has clarified some of the confusion, check out Laracasts or other forums to ask all your questions or check out the documentation: https://laravel.com/docs/9.x/http-client#retries

**Comment by littleblue50** [comment]
I know I'm not the OP but I am having this exact issue too and thank you for your well thought out and thorough response, but in my case (and I think the OPs if I'm reading it correctly) the retry isn't actually done. I tested this by logging calls to the retried endpoint as well as within the closure itself to confirm it doesn't.

**Comment by eduance** [comment]
> Reference in

Could you show how you are using the retry method?

**Comment by Cintrust** [comment]
@eduance,
I have looked at the test refferenced at
https://github.com/laravel/framework/blob/9.x/tests/Support/SupportHelpersTest.php#L572

I could not see any test for `Http:retry()`
Which is what I am having issues with. 
The retry function as you mentioned works as it should.

**Comment by eduance** [comment]
@Cintrust Sorry for the late reply. I see what you mean, I indeed don't see it retry when the throw parameter is set to false. I'll see when I have time to help out with a PR.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
A fix for this was submitted by @gdebrauwer, thanks!

**Comment by jordanade** [comment]
I'm having a related problem: when retry() is used, it seems to work, but exceptions are thrown for 4xx errors instead of the documented default behavior.
