### ISSUE TITLE
php artisan config:cache error

### ISSUE THREAD

**Issue by Tofandel** [laravel/framework#41613]
- Laravel Version: 9.5.1
- PHP Version: 8.0.16
- Database Driver & Version: Mariadb but doesn't matter

### Steps To Reproduce:

Just run `php artisan config:cache` a bunch of times, around 1 out of 2 times (if it was already cached) the following error appears

```txt
Configuration cache cleared successfully.

   ErrorException

  require(releases/55a338ab2cb555eb6a03cbcdd176d1f1473d89ef/bootstrap/cache/config.php): Failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:28
     24▕         // First we will see if we have a cache configuration file. If we do, we'll load
     25▕         // the configuration items from that file so that it is very quick. Otherwise
     26▕         // we will need to spin through every configuration file and load them all.
     27▕         if (is_file($cached = $app->getCachedConfigPath())) {
  ➜  28▕             $items = require $cached;
     29▕
     30▕             $loadedFromCache = true;
     31▕         }
     32▕

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

This seems to be a problem with `opcache.enable_file_override` which caches the result of is_file

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
I don't think this is an issue with Laravel or we should be seeing way more reports for this. Please try a support channel. Thanks

**Comment by Tofandel** [comment]
It is but with a specific configuration

With `opcache.enable_file_override = 1` in your php ini

Then is_file is cached, but the require fails because it doesn't actually exist, though a fix is really trivial with a try {} catch around the require

**Comment by driesvints** [comment]
Feel free to attempt that fix if you want 👍

**Comment by crynobone** [comment]
If you want to use OpCache on CLI mode, the deployment flow (where you run `config:cache`) should also clear OpCache. Otherwise you will see other issues between deployment.

Tool such as https://gordalina.github.io/cachetool/ should be useful.

**Comment by Tofandel** [comment]
@crynobone But in this case the problem is both is_file happens during the same command, so clearing the cache before will not change anything

Basically running the command loads the config on bootsrap, so is_file was cached and will now return true for the rest of the script
The cache file is unlinked
The cache is regenerated and for this it loads the config again with the call to is_file which is true

**Comment by crynobone** [comment]
https://engineering.facile.it/blog/eng/realpath-cache-is-it-all-php-opcache-s-fault/

**Comment by Tofandel** [comment]
What am I supposed to take from this article?

I'm talking about https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.enable-file-override

And I have `validate_timestamp` set to 1, but the issue is the `is_file` is still cached until the end of the request (in this case the end of the script)
