### ISSUE TITLE
Class "Postmark\Transport" not found

### ISSUE THREAD

**Issue by StevyMarlino** [laravel/framework#41633]
- Laravel Version: 8.75
- PHP Version:  8.1.0,
- Database Driver & Version: mysql : 5.7.24

### Description:
Good morning ! I have a problem with the configuration of sending emails with the postmark method!! I don't know if this is due to the abadon of the swiftmailer/swiftmailer package in brackets
but after configuring my service to send email I come across a message telling me Class "Postmark\Transport" not found I checked the trace and indeed my idea tells me that the path use Postmark\Transport as PostmarkTransport; in the MailManager.php file is not defined

![post1](https://user-images.githubusercontent.com/25743606/159681796-47aefbc2-8872-4314-89f8-408e42c929d8.PNG)
![mailManage](https://user-images.githubusercontent.com/25743606/159682084-4d5014b9-ef05-4da5-b31d-f331a6d6aacd.PNG)

### Steps To Reproduce:

```bash
composer require symfony/postmark-mailer symfony/http-client
```
# Configure config/mail.php

- change the default mailer to postmark
```
'default' => env('MAIL_MAILER', 'postmark'),
```
# put the token configuration postmark config/services.php
```
'postmark' => [
        'token' => env('POSTMARK_TOKEN','12345678-3594-4437-2589-123456789'),
    ],
```

**Comment by driesvints** [comment]
You're trying this on Laravel v8 which doesn't supports Symfony Mailer. Please upgrade to Laravel v9 to use this.

**Comment by X-Coder264** [comment]
Yeah, on Laravel 8 you need to require the `wildbit/swiftmailer-postmark` package in order for the Postmark driver to work.

https://github.com/laravel/framework/blob/v8.83.5/src/Illuminate/Mail/composer.json#L42
