### ISSUE TITLE
Collection - not possible group by with Stringable

### ISSUE THREAD

**Issue by medeiroz** [laravel/framework#41649]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: N/A

### Description:
When need use the groupBy method with Stringable column on collection. then error has been displayed

### Steps To Reproduce:

Make the collection with Stringable

```php
<?php

$data = collect([
	[
		'category' => \Str::of('fruits'),
		'name' => 'Apple',
	],
	[
		'category' => \Str::of('fruits'),
		'name' => 'Banana',
	],
	[
		'category' => \Str::of('vegetable'),
		'name' => 'Cucumber',
	],
]);

```

Then call groupBy method

```php
<?php

$data->groupBy('category');
```

![image](https://user-images.githubusercontent.com/11270546/159924453-5c05b47c-41d2-4226-a540-b5fd2d4080f2.png)

**Comment by eduance** [comment]
Could you add the errors?

**Comment by medeiroz** [comment]
> Could you add the errors?

Sure,

**Comment by karam-mustafa** [comment]
This is because Str::of return Stringable instance first,
Try to use plain string 

```
<?php

$data = collect([
	[
		'category' => 'fruits',
		'name' => 'Apple',
	],
	[
		'category' => 'fruits',
		'name' => 'Banana',
	],
	[
		'category' => 'vegetable',
		'name' => 'Cucumber',
	],
]);
```

**Comment by medeiroz** [comment]
This bug was solved by [PR-41650](https://github.com/laravel/framework/pull/41650)
