### ISSUE TITLE
PHP 8.1: Passing null to non-nullable parameters of built-in functions is deprecated

### ISSUE THREAD

**Issue by selfsimilar** [laravel/framework#41643]
- Laravel Version: 9.3..1
- PHP Version: 8.1.x
- Database Driver & Version:

### Description:

See [Migrating from PHP 8.0.x to PHP 8.1.x - Deprecated Features](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal)

A PHP warning is emitted when `trim()` is passed a `null`. `trim()` is used extensively throughout the framework,
but specifically in [`src/Illuminate/View/Compilers/Concerns/CompilesStacks.php`](https://github.com/laravel/framework/blob/6f743e236a49df03dd579933e2360a3304b55c5b/src/Illuminate/View/Compilers/Concerns/CompilesStacks.php#L41) the framework sets `$id` to `null`
as part of default behavior when processing a standard Blade `pushOnce` directive. There may be other instances
in the framework where this happens, but I have only triggered this particular instance.

### Steps To Reproduce:

This was discovered by running [`tlint`](https://github.com/tighten/tlint) in a repository where the `pushOnce` directive was used.

### Recommendation

Replace `null` with the empty string `''` when setting a default 'empty' value that will be passed on to `trim()`.

**Comment by selfsimilar** [comment]
Apparently a lot of the string functions, not just `trim()` have more strongly-typed parameters now. It's probably a decision better made by the maintainers whether to fix everything in on big PR (probably just casting with `(string)` before parameter #1 is sufficient where appropriate), or to spread the fixes over many PRs in more easily reasoned-about chunks.

**Comment by tristanh00** [comment]
> Apparently a lot of the string functions, not just `trim()` have more strongly-typed parameters now. It's probably a decision better made by the maintainers whether to fix everything in on big PR (probably just casting with `(string)` before parameter # 1 is sufficient where appropriate), or to spread the fixes over many PRs in more easily reasoned-about chunks.

How would casting (string) resolve this on a null parameter?  Would the value just be "null"?

**Comment by selfsimilar** [comment]
As a follow-up thought, this deprecation seems like an indication that PHP is becoming more strongly typed, and it's likely worth having a long think about whether or not casting null values will be enough in the long-term. There's probably a good case to be made that adding type declarations wherever possible (function arguments, return values, class properties) should be a part of the fix, in order to better align with the direction that PHP is headed. There's probably a lot of other things I'm not considering here in terms of knock-on effects of a stronger type system or a move away from ad hoc type juggling.

**Comment by tristanh00** [comment]
@selfsimilar Thank you for those links, and I strongly agree that the fix should be future proof for the direction PHP is heading.   Probably starting off multiple small PRs is the way to go to start enforcing strictly typed variables in Laravel.

**Comment by driesvints** [comment]
A PR was sent in for this, thanks.
