### ISSUE TITLE
trans_choise is not working properly inside toMail

### ISSUE THREAD

**Issue by mfmarques** [laravel/framework#41646]
- Laravel Version: 9.3.1
- PHP Version: 8.1.2

## Description:

The trans_choise function does not work properly when called inside the toMail

## Steps to Reproduce:

Job: `\Log::info(['job' => trans_choice('messages.apples', 2)]);`
Notification constructor: `\Log::info(['notification constructor' => trans_choice('messages.apples', 2)]);`
Notification toMail: `\Log::info(['notification toMail' => trans_choice('messages.apples', 2)]);`

## Translation:

'apples' => 'There is one apple|There are many apples',

## Result

[2022-03-23 22:33:27] local.INFO: array ('job' => 'There are many apples')  
[2022-03-23 22:33:27] local.INFO: array ('notification constructor' => 'There are many apples')  
[2022-03-23 22:33:27] local.INFO: array ('notification toMail' => 'There is one apple')

**Comment by eduance** [comment]
I have just tried recreating it but was not able too.

![unrecreatble](https://user-images.githubusercontent.com/101891339/159809780-b172811c-a885-4744-b0d9-25f95335c4d9.gif)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
