### ISSUE TITLE
dimensions:ratio return 302 when upload big image

### ISSUE THREAD

**Issue by trappistes** [laravel/framework#41677]
- Laravel Version: 8.83.2
- PHP Version: 8.0
- Database Driver & Version:

### Description:
dimensions:ratio validation all ways return 302 when the image with or height has more then 30000 pixel
30000x15000 isok
30002x15001 return 302

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
