### ISSUE TITLE
db: The `save` function does not work properly when updating a row with the Postgres database.

### ISSUE THREAD

**Issue by ialaminpro** [laravel/framework#41678]
- Laravel Version: 8.75
- PHP Version: 8.0
- Database Driver & Version: pgsql & postgres (PostgreSQL) 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

### Description:
```
$movie = Movie::find(1855613);
$movie->title = 'Ponteng School';
$movie->save();
```

This code not only updates the given ID, It is updates all my rows with the same title. After the disaster, I had to restore the backup of the 10 GB size database. Luckily I had a backup. 

I was running the same code on **MySQL server** it is working fine, but on **Postgres server** it is not working as I like. I saw the problem was `save` function then I skipped save function and use `update` function

`
Movie::where("id", 1855613)->update(["title" =>'Ponteng School']);
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by amims71** [comment]
@driesvints , if a `save()` method updates all the rows, that is a **bug**.

**Comment by ialaminpro** [comment]
@driesvints, Will you review the issue again? Something strange is happening with the `save()` function at `Postgres Server`.

**Comment by driesvints** [comment]
I doubt there's a real issue here or we should be seeing way more reports about this. Most likely, something is off with your specific app. Please try a support channel.

**Comment by crynobone** [comment]
@driesvints  is correct.

```php
$movie = Movie::find(1855613);
```
This would make `$model` equals to `null`.

How is it possible that you can do `$movie->title = 'Foo';` when `$movie` clearly is `null`. 

Either you have some other issue on your app or what's reported above is incomplete and require more investigation. Which best discuss/debug on support channel first.

![image](https://user-images.githubusercontent.com/172966/160115533-8d666578-8089-4888-ae4f-d2cb30df59d9.png)

![image](https://user-images.githubusercontent.com/172966/160115564-9fd1e696-84c0-49b6-8118-32b817e2b631.png)

**Comment by ialaminpro** [comment]
@crynobone 

Why `$movie = Movie::find(1855613);` is should be return `null ` if `1855613`  ID is exists in the database?

![save](https://user-images.githubusercontent.com/11612614/160124795-c97aee04-6ae7-461d-a3a4-7f7bdda42355.jpg)


Do you mean
```
$flight = App\Flight::find(1);
$flight->name = 'New Flight Name';
$flight->save(); //this will UPDATE the record with id=1
```
this is not possible ?

**Comment by crynobone** [comment]
@ialaminpro If you believe there a bug, submit a failing test PR. You can use https://github.com/crynobone/framework/commit/a271266c95ebe44af9ed1e83bc04ad0e44b8c630 as reference.
