### ISSUE TITLE
artisan test coverage command not working

### ISSUE THREAD

**Issue by ArielMejiaDev** [laravel/framework#41690]
- Laravel Version: 9.2.x
- PHP Version: 8.0.17
- Database Driver & Version: sqlite

### Description:

with Laravel Valet it always return "Unable to get coverage using Xdebug. Did you set Xdebug's coverage mode?"

I already have Xdebug installed:
![Screen Shot 2022-03-25 at 5 44 45 PM](https://user-images.githubusercontent.com/31971074/160215609-6ade647e-94d7-4118-860b-4c6cac7a3628.png)

Here the message:
![Screen Shot 2022-03-25 at 5 44 26 PM](https://user-images.githubusercontent.com/31971074/160215619-9ef2f139-813a-4c93-9291-e3270349785d.png)

### Steps To Reproduce:

- Create a new Laravel app: `laravel new example`
- Run artisan test command: `php artisan test`
- It works, then run the same command with coverage flag: `php artisan test --coverage`
- You can set `XDEBUG_MODE` in the `env` file as: `XDEBUG_MODE=coverage`
- Then run again the artisan command with the flag: `php artisan test --coverage` and it still showing the same message
- With Sail you can set `SAIL_XDEBUG_MODE=coverage`, but the result is the same using sail

<br>

## The only way it works locally with Valet is by adding the XDEBUG_MODE in the terminal like this:
```
XDEBUG_MODE=coverage php artisan test --coverage
```

## How to solve it

You can set the XDEBUG value in your `php.ini` file locally to get the `php.ini` file for the current php version that is running in valet you can use this command:

```php
php --ini
```

Then get the path of the php.ini file and update this values:

```php
zend_extension="xdebug.so"
xdebug.mode=develop,debug,coverage
```

Search in the file, maybe you have already installed `zend_extension="xdebug.so"` as it comes in the default installation of Laravel Valet.

Now you are able to use the command in your project:

```php
php artisan test --coverage
```

and it should work.

**Comment by tylerwiegand** [comment]
This just helped me. Thanks @ArielMejiaDev !

**Comment by LeoScripts** [comment]
Thanks. @ArielMejiaDev !

**Comment by rindibudiaramdhan** [comment]
thanks @ArielMejiaDev . this solve my problem!
