### ISSUE TITLE
Adding global scopes in traits is deprecated

### ISSUE THREAD

**Issue by hicham-saddek** [laravel/framework#41693]
- Laravel Version: 9.x
- PHP Version: 8.1.x
- Database Driver & Version: mariadb:latest

### Description:
The laravel static method is no longer usable inside traits, because of Static Trait Methods deprecation in PHP 8.1.x
Link to docs: [PHP Doc: Static Traits Methods Deprecation](https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.static)

Is there any solution for the time being to use it, without getting any deprecation errors in our sonar ?

**Comment by driesvints** [comment]
That's not possible anymore no
