### ISSUE TITLE
Can't use camelCase naming with new Eloquent attribute syntax

### ISSUE THREAD

**Issue by timhoeppner** [laravel/framework#41704]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.28-1debian10

### Description:
I cannot use camelCase attribute names with the new Eloquent attribute syntax.

### Steps To Reproduce:

The following code results in `Call to undefined method App\Models\MyModel::getTestFooAttribute()`. Modifying the $appends to use 'test_foo' correctly calls the custom attribute.

Camel case attributes are supported using the get...Attribute() and set...Attribute() syntax which is why I believe this to be an error.

```php
class MyModel extends Model
{
  protected $appends = ['testFoo'];

  protected function testFoo(): Attribute
  {
    return Attribute::make(
      get: fn () => 'test'
    );
  }
}
```

**Comment by driesvints** [comment]
`$appends` needs to be `test_foo`

**Comment by timhoeppner** [comment]
I respect that's how it works right now I just thought this may be a bug since you can use camel case attributes with the older get...Attribute() and set...Attribute() syntax.
