### ISSUE TITLE
whereNotNull  does not work

### ISSUE THREAD

**Issue by chowjiawei** [laravel/framework#41712]
- Laravel Version: 8.83
- PHP Version: 8.0.10
- Database Driver & Version: mysql8

### Description:

whereNotNull    does not work

![image](https://user-images.githubusercontent.com/59349609/160369368-1ccdb607-4223-4639-ad5c-87ba7ad395b5.png)
![image](https://user-images.githubusercontent.com/59349609/160369435-25993f3c-8bcc-482d-b424-cc7026b99d46.png)

![image](https://user-images.githubusercontent.com/59349609/160369507-1e5bce92-7597-403f-9fd5-eb9c351605cb.png)

**Comment by driesvints** [comment]
Probably does into your if statement because $type equals 1.

**Comment by chowjiawei** [comment]
> 
![image](https://user-images.githubusercontent.com/59349609/160370813-1097b1cc-6f2e-42e8-a05d-63c4c2f839d1.png)


In fact, it has nothing to do with tpye

**Comment by crynobone** [comment]
> In fact, it has nothing to do with type

Are you absolutely sure?

![image](https://user-images.githubusercontent.com/172966/160371540-bb08e622-8d2c-4078-b1f8-2fef53eea0f4.png)

**Comment by chowjiawei** [comment]
> > In fact, it has nothing to do with type
> 
> Are you absolutely sure? try `dd($searchType)`
> 
> ![image](https://user-images.githubusercontent.com/172966/160371540-bb08e622-8d2c-4078-b1f8-2fef53eea0f4.png)

I am sure ~
![image](https://user-images.githubusercontent.com/59349609/160371912-bd22e1cc-0fed-44f7-b46f-154f98a90dd9.png)

**Comment by chowjiawei** [comment]
> > In fact, it has nothing to do with type
> 
> Are you absolutely sure? try `dd($searchType)`
> 
> ![image](https://user-images.githubusercontent.com/172966/160371540-bb08e622-8d2c-4078-b1f8-2fef53eea0f4.png)

sorry
My code is wrong

thank you
