### ISSUE TITLE
Laravel Eloquent with does not work in MariaDB 10.7.3

### ISSUE THREAD

**Issue by CeoTang** [laravel/framework#41728]
I have been tried to install Mariadb 10.7.1 and 10.7.3 versions in my docker. I found 10.7.3 (MariaDB) will not get the data when using with function in eloquent. But I have tried to dump the SQL and run it in MariaDB with raw SQL, it works fine. Laravel 6 and Laravel 9 got the same issues.

**Comment by driesvints** [comment]
Please don't ignore the issue template when posting issues. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
