### ISSUE TITLE
Console argument() method should include bool return type

### ISSUE THREAD

**Issue by jamesabell** [laravel/framework#41737]
- Laravel Version: 9.x.x
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
`Console/Concerns/InteractsWithIO.php@argument()` should include bool (`@return string|array|null|bool`) in its return types.

By calling `Artisan::call([command], [ 'fooBool' => true ])` the value returned from `$this->argument('fooBool')` would be a boolean. 

---

My thoughts: Should be a simple update, but I'm not sure if we would need to account for that anywhere else.

### Steps To Reproduce:
* Create a command that compares `$this->argument('fooBool') === false`
* IDEs will complain, phpStan will flag this as an error

**Comment by driesvints** [comment]
Please just attempt a PR. Also don't submit half-filled in issue templates.
