### ISSUE TITLE
Breeze starter kit installation removed contents of route file web.php instead of appending auth routes.

### ISSUE THREAD

**Issue by gmbhurgri** [laravel/framework#41739]
- Laravel Version: 9.5.1
- PHP Version: 8.1.2

### Description:
I had wrote some my app specific routes in `web.php`.

After running command:

`php artisan breeze:install`

all the previous contents of `web.php` deleted.

It looks instead of appending `auth` related routes in the end of `web.php` laravel replaces `web.php` file with some predefined `web.php` file.

`
### Steps To Reproduce:
1. Write some routes in `web.php` file
2. Install **breeze** starter kit
3. It removes all previous contents of `web.php` route file.

**Comment by driesvints** [comment]
Breeze is intended for new Laravel applications, not existing ones. You should never install Breeze in an existing app.

**Comment by yasinrahnaward** [comment]
Always do install laravel breeze in a fresh project, not in the old one or instead do have a backup.

**Comment by NielsKoomans97** [comment]
Routes aren't the only things altered. I understand that it's a starter kit, but an entire package.json removed and other components of the project screwed up. Why does it delete files that aren't necessary for breeze to be deleted?
