### ISSUE TITLE
Nullable MorphTo relation query throws a query exception

### ISSUE THREAD

**Issue by modstore** [laravel/framework#41730]
- Laravel Version: 9.5.1
- PHP Version: 8.0.17
- Database Driver & Version: mysql

### Description:
If you have a nullable Morph To relation and try and query it when the relation is null, it will throw a query error like this:
```
Illuminate\Database\QueryException : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comments.' in 'where clause' (SQL: select * from `comments` where `comments`.`` is null limit 1)
```

Example of querying the relation that will cause the error:
```
$comment->commentable()->first()
```

### Steps To Reproduce:

Here's a repo and the commit for reproducing: https://github.com/modstore/morph-to-issue/commit/60e1db13cf321d4ba8c0a3efb0a737f5270f4bc3

Here is where the query is built differently due to that being null: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L261

**Comment by driesvints** [comment]
Doing `$comment->commentable()->first()` makes no sense because you're targeting a single model, not a collection. `first` also isn't a method on the `MorphTo` relationship.

Just try `$comment->commentable`.

**Comment by modstore** [comment]
@driesvints Yep I understand that you can just do $comment->commentable, but this behaviour seems inconsistent with any other relationship where you get a valid builder instance.

**Comment by driesvints** [comment]
@modstore I don't understand why you try to call `->first()` as that simple doesn't exists for MorphTo.

**Comment by modstore** [comment]
I thought it was possible to essentially get a query builder instance from any relation called as a method. Even though in general you'd just call it like `$comment->commentable`, but I thought you could still expect query building to work e.g.
`$comment->commentable()->get()`
`$comment->commentable()->where('anything', true)->get()` etc.
