### ISSUE TITLE
Limit for brute force tokens

### ISSUE THREAD

**Issue by tabuna** [laravel/framework#41757]
- Laravel Version: 9.5.1
- PHP Version: 8.1.2 
- Database Driver & Version: None

### Steps To Reproduce:

Hi, I'm making a simple API that uses `api_token` for `/config/auth.php`:

```php
'guards' => [
    // ...
    'api' => [
        'driver'   => 'token',
        'provider' => 'users',
        'hash'     => true,
    ],
],
```

This will authorize the user when the request has:

```php
https://example.com/api/ping?api_token=*****
```

This method was added a long time ago and still works great ([but was removed from the documentation](https://laravel.com/docs/5.8/api-authentication#generating-tokens)). The problem is that with this use, the standard enumeration limiter stops working: https://github.com/laravel/laravel/blob/f7b982ebdf7bd31eda9f05f901bd92ed32446156/app/Providers/RouteServiceProvider.php#L46-L50 and https://github.com/laravel/laravel/blob/f7b982ebdf7bd31eda9f05f901bd92ed32446156/app/Http/Kernel.php#L43

I check in the following way:

```php
public function testLimitAuthRequest(): void
{
    $statuses = collect(range(0, 200))->map(function ($i){
        return $this->json('POST', route('api.ping'), [], [
            'Authorization' => 'Bearer ' . Str::random($i)
        ])->getStatusCode();
    });

    $this->assertContains(429, $statuses);
}
```
And the entire set only contains 401 statuses.

Any help is welcome.

**Comment by AlexWinder** [comment]
I believe the new logic you are looking for has been moved to [Sanctum](https://laravel.com/docs/9.x/sanctum).

HTTP 401 is an unauthorised, suggesting that your `route('api.ping')` is protected someway. You are sending a `Bearer` token which is typically sent as an `Authorization` header, however your example is making use of passing in the API token in as a GET variable:

```
https://example.com/api/ping?api_token=*****
```

Ignoring the obvious security issues with your example endpoint, the reason yours isn't working is because you don't appear to be sending the API token correctly to your endpoint.

**Comment by tabuna** [comment]
I understand why the `401` is happening. I am intentionally entering the wrong token many times in the hope that I will get a `429` error due to too many IP calls:

```php
RateLimiter::for('api', function (Request $request) {
    return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
});
```

This is the whole problem, that `throttle:api` does not work with this

**Comment by AlexWinder** [comment]
I believe middlewares work in layers. As soon as the first one fails then it prevents subsequent ones from even being attempted. It could be that your middleware for authentication is failing before the throttling even has a chance to start.

**Comment by driesvints** [comment]
I indeed think the auth middleware fails first before throttling can start. Otherwise the `$request->user()` part doesn't makes sense in the throttle callback.

**Comment by driesvints** [comment]
Thanks @AlexWinder
