### ISSUE TITLE
Str::plural() cannot correctly pluralise ID to IDs

### ISSUE THREAD

**Issue by ziadoz** [laravel/framework#41763]
- Laravel Version: 8.83.6, likely 9.x too
- PHP Version: 8.0.12

### Description:
I've noticed that the `Str` class cannot correctly pluralise [ID](https://www.oxfordlearnersdictionaries.com/definition/english/id_2) (short form of identifier/identity/identification) to IDs. The Doctrine Inflector correctly returns IDs, but when case matching occurs the plural string result is changed to IDS.

I did look at opening a PR to fix this, but the only solutions I could see were to hardcode in an exception for ID to IDs, or to skip the `matchCase()` call, which is a breaking change. Neither seemed ideal.

### Steps To Reproduce:
```
echo Str::plural('ID'); // Returns IDS instead of IDs
```

**Comment by driesvints** [comment]
We use the Doctrine inflector for this so if you think this isn't correct please open an issue on their repo. Thanks

**Comment by ziadoz** [comment]
@driesvints The Doctrine Inflector returns the correct result of IDs. It's the `Pluralizer::matchCase()` method that changes it from IDs to IDS.

**Comment by ziadoz** [comment]
Yes, there's no PR worth opening that I could think of. I guess I'll macro away the edge case. Thanks anyway.
