### ISSUE TITLE
Blade foreach too slow

### ISSUE THREAD

**Issue by MichailSuroven** [laravel/framework#41761]
- Laravel Version: 8.12
- PHP Version: 7.4

### Description:
I try to optimize simple e-commerce site with products, having huge amount of props. All blade template have huge amount of loops.
My goal is render product list page around 200 ms. I noticed that loops take too many time.

### Steps To Reproduce:

I create empty controller, that return this view
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

    </head>
    <body>

        @php $data = collect(array_fill(0, 100000, '123')); @endphp
        
        @php $start = microtime(true); @endphp
        @foreach ($data as $item)

        @endforeach
        @php \Debugbar::addMeasure('default foreach', $start, microtime(true)); @endphp

        @php $start = microtime(true); @endphp
        @php foreach ($data as $item): @endphp

        @php endforeach; @endphp
        @php \Debugbar::addMeasure('pure foreach', $start, microtime(true)); @endphp

    </body>
</html>
```

Two loops, first - blade directive, second - pure foreach. Here timings
![изображение](https://user-images.githubusercontent.com/29775460/160984854-4006891d-688d-4299-b657-2b8b9d62f36b.png)

I guess loop manipulations on Illuminate\View\Concerns\ManagesLoops like array_merge take too many time.
May be is good to add pure foreach loop directive.

**Comment by MichailSuroven** [comment]
In my project i dont use $loop var in loops, so i just create custom foreach directive in service provider

`Blade::directive('foreach', function ($expression) {
            return "<?php foreach({$expression}): ?>";
        });
        
        Blade::directive('endforeach', function () {
            return "<?php endforeach; ?>";
        });`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
