### ISSUE TITLE
[Eloquent] Union Limit Produces invalid query

### ISSUE THREAD

**Issue by Tofandel** [laravel/framework#41777]
- Laravel Version: 9.6.0
- PHP Version: 8.1.16
- Database Driver & Version: MariaDB 10.3.34

### Description:

Running
```php
class Model extends Illuminate\Database\Eloquent\Model {}; 
Model::query()->union(Model::query())->limit(1)->toSql();
```

Produces the following SQL
```mysql
(select * from `model`) union (select * from `model`) limit 1
```

Which is invalid SQL and will not run

Here is the SQL that would run correctly

```mysql
select * from ((select * from `model`) union (select * from `model`)) limit 1
```

**Comment by staudenmeir** [comment]
> Which is invalid SQL and will not run

What error are you getting?

**Comment by Tofandel** [comment]
My bad, seems it does work with MariaDB, but phpMyAdmin and phpStorm are both not happy about this syntax and show an error, and in fact the SQLite driver uses the second syntax
