### ISSUE TITLE
Dynamically Registered Event Listeners `assertListening` Fails

### ISSUE THREAD

**Issue by gofish543** [laravel/framework#41771]
- Laravel Version: 9.5.1
- PHP Version: 8.1.0
- Database Driver & Version:

### Description:
A dynamically registered event listener using the `EventServiceProvider@shouldDiscoverEvents => returns true` registers the listener in the dispatcher as a `string` value.

This is fine, and the listener fires correctly. However, if a call is made to the `EventFake@assertListening(...)`, it will fail because the `$actualListener` variable is a string `class@method` syntax not matching any of the equals statements found. 

### Steps To Reproduce:
1) Create a UserLogin Listener `REGISTERED DYNAMICALLY`
```php
<?php

namespace App\Listeners\Auth;

use Illuminate\Auth\Events\Login;
use Illuminate\Http\Request;

class LoginListener
{
    /**
     * Create the event listener.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return void
     */
    public function __construct(
        protected Request $request
    ) {
        //
    }

    /**
     * Handle the event.
     *
     * @param  \Illuminate\Auth\Events\Login  $event
     * @return void
     */
    public function handle(Login $event)
    {
        $event->user->logins()->create([
            'source_ip' => $this->request->ip(),
        ]);
    }
}
```
and the EventServiceProvider...
```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array<string, string[]>
     */
    protected $listen = [
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Determine if events and listeners should be automatically discovered.
     *
     * @return bool
     */
    public function shouldDiscoverEvents(): bool
    {
        return true;
    }
}
```

2) Create a test case to test the registration using `assertListening`
```php
<?php

namespace Tests\Unit\Listeners\Auth;

use App\Listeners\Auth\LoginListener;
use App\Models\User;
use Illuminate\Auth\Events\Login as LoginEvent;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class LoginListenerTest extends TestCase
{
    /**
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();

        Event::fake([
            LoginEvent::class
        ]);
    }

    /**
     * @small
     */
    public function testListenerRegistered()
    {
        Event::assertListening(LoginEvent::class, LoginListener::class);
    }

    /**
     * @medium
     */
    public function testRecordsLoginEvent()
    {
        Event::fake();

        $user = User::factory()->create([
            'password' => 'testing543',
        ]);

        $this->post(route('login'), [
            'email' => $user->email,
            'password' => 'testing543',
        ]);

        Event::assertDispatched(LoginEvent::class);
    }
}
```

3) Observe the test case failing
![image](https://user-images.githubusercontent.com/10394554/161192665-55f4c2fc-4c6a-4aad-809c-a5bdc1476370.png)

4) Navigate to the file throwing the error `Illuminate/Support/Testing/Fakes/EventFake.php` line `58`

5) Dump the `$actualListener` and `$expectedListener` variables (We can assume a string is never an instance of `Closure` or `Closure::class` so we need the `$actualListener === $expectedListener` to work)
![image](https://user-images.githubusercontent.com/10394554/161192765-f240cad7-cd78-4bc8-b3ab-67502b1aa840.png)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Hey @gofish543. Feel free to provide that repo and I'll re-open.

**Comment by gofish543** [comment]
> > Hey @gofish543. Feel free to provide that repo and I'll re-open.
> 
> I'll get something up late tonight or tomorrow. You'll have it Monday.

Scratch that...

https://github.com/gofish543/bug-report

**Comment by driesvints** [comment]
Thanks @gofish543. I managed to reproduce this. I've sent in a PR for this: https://github.com/laravel/framework/pull/41820
