### ISSUE TITLE
Invalid number returned by withCount method.

### ISSUE THREAD

**Issue by aleksander237** [laravel/framework#41785]
- Laravel Version: 9.5.1
- PHP Version: 8.1.4
- Database Driver & Version: MariaDB 10.5

### Description:

If you create a model related to itself in One to many relation, the method `withCount(['children'])` always returns 0. The mehtod `with(['children'])` returns the correct collection of children records.

### Steps To Reproduce:

Let's say that we are implementing a category tree with infinite possible numer of levels, so the database table could look like this:

```sql
CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(10) unsigned DEFAULT NULL,
  `name` char(32) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `categories_parent_id_foreign_idx` (`parent_id`),
  CONSTRAINT `categories_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
);
```
there are following records in our database:
| id        | parent_id           | name  |
| ------------- |:-------------:| -----:|
| 1      | NULL | Parent1 |
| 2      | 1      |   Child2 |
| 3 | 1      |    Child3 |
| 4 | 1      |    Child4 |

on the laravel part we have the Category model class:
```php
class Category extends Model {
    public function children() {
        return $this->hasMany(Category::class,'parent_id','id');
    }
}
```
now, when we call `Category::query()->where(parent_id,null)->with(['children'])->get()` we get one parent whith collection of three children, but when we call `Category::query()->where(parent_id,null)->withCount(['children'])->get()` we get one parent with field `children_count` set to 0, which is incorrect.

The folowing code:
```php
Category::query()->withCount(['children' => function(BuilderContract $builder) {
                \ChromePhp::log($builder->toSql());
            }]);
```
produces this query to the console:
```sql
select count(*) from `categories` where `categories`.`id` = `categories`.`parent_id`
```
which is invalid in this case.

**Comment by Tofandel** [comment]
I'm guessing it's missing an alias in the generated query

```mysql
select count(*) from `categories` as count_table where count_table.`id` = `categories`.`parent_id`
```

**Comment by Tofandel** [comment]
Did you try with a `belongsTo` ?

```php

    public function children() {
        return $this->belongsTo(Category::class,'parent_id','id');
    }
```

**Comment by staudenmeir** [comment]
Please log the executed queries and the result:

```php
DB::enableQueryLog();

dd(
    Category::query()->where('parent_id',null)->withCount(['children'])->get()[0]->getAttributes(),
    DB::getQueryLog()
);
```

Does your `Category` model contain anything else besides the `children` relationship?

**Comment by Tofandel** [comment]
I'm getting

```
Category::query()->withCount(['children' => function($builder) {
                var_dump($builder->toSql());
            }]);
string(116) "select count(*) from `categories` as `laravel_reserved_2` where `categories`.`id` = `laravel_reserved_2`.`parent_id`"
```

So there is definitely something wrong with your setup, please provide a reproduction repository if you want further help

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
