### ISSUE TITLE
Fatal Error at function pipeThrough

### ISSUE THREAD

**Issue by hamilton-martins-dev** [laravel/framework#41780]
- Laravel Version: v8.83.6
- PHP Version: 8
- Database Driver & Version: MySql 8

### Description:
Fatal error at function **pipeThrough** - framework/src/Illuminate/Collections/Traits/**EnumeratesValues.php** 
There is a comma that causes the error **ParseError: syntax error, unexpected ')' in /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:739**

### Steps To Reproduce:
No need to reproduce, just call the function and the error is thrown.

**Comment by X-Coder264** [comment]
You are obviously not using PHP 8 as that syntax has been allowed ever since PHP 7.3

https://wiki.php.net/rfc/trailing-comma-function-calls

**Comment by driesvints** [comment]
Thanks @X-Coder264
