### ISSUE TITLE
Eloquent builder macro PHP8 named arguments breaks Builder->__call()

### ISSUE THREAD

**Issue by ainesophaur** [laravel/framework#41798]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Database Driver & Version: mysqlnd 8.1.3

### Description:
Creating an eloquent builder macro using PHP8 named arguments breaks `Builder->__call()` as `$arguments` is no longer an index based array, but instead, an array of the named arguments.

### Steps To Reproduce:

1. Register a eloquent macro using named arguments (in my case, I was adding this to a Scope)
```php
 protected function addWithServiceAccount(Builder $builder)
    {
        $builder->macro(name: 'withServiceAccount', macro: function (Builder $builder, $withServiceAccount = true) {
            if (! $withServiceAccount) {
                return $builder->withoutServiceAccount();
            }

            return $builder->withoutGlobalScope(scope: $this);
        });
    }
```

2. Try to use the macro

```
   ErrorException 

  Undefined array key 0

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1681
    1677▕      */
    1678▕     public function __call($method, $parameters)
    1679▕     {
    1680▕         if ($method === 'macro') {
  ➜ 1681▕             $this->localMacros[$parameters[0]] = $parameters[1];
    1682▕ 
    1683▕             return;
    1684▕         }
    1685▕ 

      +1 vendor frames 
  2   app/Models/Scopes/ExcludeServiceAccounts.php:96
      Illuminate\Database\Eloquent\Builder::__call()

  3   app/Models/Scopes/ExcludeServiceAccounts.php:41
      App\Models\Scopes\ExcludeServiceAccounts::addWithoutServiceAccount()

```

When debugging the call, `$parameters` will only have `['name'=>'WithoutServiceAccount', 'macro' => [...somecallback]]`

**Comment by ainesophaur** [comment]
I've found this same behavior outside of Eloquent's builder (same behavior exists when setting the middleware for routes). With named arguments gaining traction it might help to have a document which outlines areas where named arguments shouldn't be used, but it may not be feasible to collect such a list. At a minimum, hopefully this issue can provide insight to anyone who comes across this issue. I understand if this isn't something that is fixable.


```
 ErrorException 

  Undefined array key 0

  at vendor/laravel/framework/src/Illuminate/Routing/Router.php:1368
    1364▕             return $this->macroCall($method, $parameters);
    1365▕         }
    1366▕ 
    1367▕         if ($method === 'middleware') {
  ➜ 1368▕             return (new RouteRegistrar($this))->attribute($method, is_array($parameters[0]) ? $parameters[0] : $parameters);
    1369▕         }
    1370▕ 
    1371▕         return (new RouteRegistrar($this))->attribute($method, array_key_exists(0, $parameters) ? $parameters[0] : true);
    1372▕     }

      +2 vendor frames 
  3   routes/web.php:32
      Illuminate\Support\Facades\Facade::__callStatic()

      +4 vendor frames 
  8   app/Providers/RouteServiceProvider.php:37
      Illuminate\Routing\RouteRegistrar::group()

```

**Comment by driesvints** [comment]
I just don't think we support named arguments there. If you can think of a backwards compatible fix, feel free to send in a PR. For now, just avoid named arguments.
