### ISSUE TITLE
HTTP Client is currently not applying the base URL to pool requests

### ISSUE THREAD

**Issue by srdante** [laravel/framework#41790]
- Laravel Version: 9.6.0
- PHP Version: 8.1.3
- Database Driver & Version: Irrelevant

### Description:

HTTP Client is currently not applying the base URL to pool requests.

### Steps To Reproduce:

```php
use Illuminate\Http\Client\Pool;
use Illuminate\Support\Facades\Http;

$client = Http::baseUrl('https://blockstream.info/api/');

$responses = $client->pool(fn (Pool $pool) => [
    $pool->get('tx/173a7bce237dabe4a806b3dda1df52b8f9a4abc3f15679a5f5d7ca0d29d30154'),
    $pool->get('tx/be78293aa29da520a3a33bd9f32a65559bbd9f9acea973acf0060a821f04c951'),
    $pool->get('tx/ebe215defd53eba5a0e36c12a6cb3fbab211e827ac7b24d88639686f5c56fc23'),
]);

dd($responses);

// cURL error 6: Could not resolve host: tx (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for tx/9dc88b187b846bbd670ef7db46b928ed08089431f47a49794cfb0b534784c24e
```

**Comment by SachinBahukhandi** [comment]
Seeing the section even they are using absolute URL instead of using relative url.
https://laravel.com/docs/9.x/http-client#concurrent-requests

**Comment by driesvints** [comment]
Thanks @SachinBahukhandi

**Comment by ThaDaVos** [comment]
Sorry for commenting on a closed issue - but I ran into the exact same issue just now... it also seems you cannot use `->baseUrl` on the Pool object as it breaks it - does one really need to use an absolute URL for this functionality? Or has it just been an oversight?

**Comment by srdante** [comment]
@ThaDaVos Yes, you need to use the absolute path and Laravel don't want to make this feature works or add a comment warning about this lack of feature on their documentation.

**Comment by SachinBahukhandi** [comment]
@ThaDaVos This issue seems to be from guzzle. Maybe you can post it as an issue there as an enhancement.

**Comment by killgt** [comment]
To make it worse, retry and timeout options will fail silently, as they are not applied:

```php
$responses = Http::pool(fn (Pool $pool) => [
    $pool->timeout(50)->get('tx/173a7bce237dabe4a806b3dda1df52b8f9a4abc3f15679a5f5d7ca0d29d30154'),
    $pool->timeout(50)->get('tx/be78293aa29da520a3a33bd9f32a65559bbd9f9acea973acf0060a821f04c951'),
    $pool->timeout(50)->get('tx/ebe215defd53eba5a0e36c12a6cb3fbab211e827ac7b24d88639686f5c56fc23'),
]);
```
neither

```php
$responses = Http::timeout(50)->pool(fn (Pool $pool) => [
    $pool->get('tx/173a7bce237dabe4a806b3dda1df52b8f9a4abc3f15679a5f5d7ca0d29d30154'),
    $pool->get('tx/be78293aa29da520a3a33bd9f32a65559bbd9f9acea973acf0060a821f04c951'),
    $pool->get('tx/ebe215defd53eba5a0e36c12a6cb3fbab211e827ac7b24d88639686f5c56fc23'),
]);
```

**Comment by srdante** [comment]
@binbyz no, only hard typing the url.

**Comment by stephan-v** [comment]
So why has this been closed because this seems odd that you suddenly have to manually specify the base url.

Why not pass in the current PendingRequest to the Pool so asyncRequests are based of the client with whatever the options are at that time?

If you have created an API client to consume an API and you have set up a client this is a pretty big hassle to all of a sudden having to switch back to absolute urls.
