### ISSUE TITLE
Laravel - Unlike the public channels, private channels don't work

### ISSUE THREAD

**Issue by hamedgasemi200** [laravel/framework#41804]
I'm using `Laravel 9.1`, and trying to broadcast on private channels, but unlike the public channels, it doesn't work for some reason!

I have an event like this:

```
class newMessage implements ShouldBroadcast
{
   use Dispatchable, InteractsWithSockets, SerializesModels;

   public string $message;

   public function __construct($message = null)
   {
       $this->message = $message;
   }

   public function broadcastOn()
   {
       return new PrivateChannel('notification.' . auth()->user()->username);
   }
}
```

When in `broadcastOn` I return an instance of `Channel`, everything works pretty well, but when I change it to `PrivateChannel`, it doesn't work anymore.

`channels.php`

```
Broadcast::channel('notification.{username}', function ($user, $username) {
    return true;
});
```

> I've tried both `soketi` and `websockets`; In both, I had the same result.

# Configs

In the the `BroadcastServiceProvider.php` file, I've tried all these possibilities:

+ `Broadcast::routes();`
+ `Broadcast::routes(['middleware' => ['auth:api']]);`

none of them worked.

config/broadcasting.php

```
      'pusher' => [
          'driver' => 'pusher',
          'key' => env('PUSHER_APP_KEY'),
          'secret' => env('PUSHER_APP_SECRET'),
          'app_id' => env('PUSHER_APP_ID'),
          'options' => [
              'cluster' => env('PUSHER_APP_CLUSTER'),
              'host' => env('PUSHER_HOST', '127.0.0.1'),
              'port' => env('PUSHER_PORT', 6001),
              'scheme' => env('PUSHER_SCHEME', 'http'),
              'useTLS' => false,
              'encrypted' => false,
          ],
      ],
```

# Note

When I broadcast on public channels, `websockets` console returns:

```
Connection id 76490676.561659290 sending message {"channel":"notification.admin","event":"App\\Events\\newMessage","data":"{\"message\":\"[2022\\\/04\\\/03 06:26:53]: Pigeon had finished. 'As if it wasn't very civil of you to learn?' 'Well, there was mouth enough for it now, I suppose, by being drowned in my size; and as Alice could not be denied, so she tried.\",\"date\":\"2022-04-03T06:26:53.988364Z\"}"}
```

But in private channels, when I try to broadcast something, it doesn't return or log anything at all; so it looks for some reason, Laravel even doesn't send the request to the socket server.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
@hamedgasemi200 I doubt this is broken or we'd have many more reports. Please try a support channel.

**Comment by hamedgasemi200** [comment]
I really have no idea what could be the problem

https://stackoverflow.com/questions/48299669/private-channel-not-working-in-laravel

There have been some other people who have had the same issue, but no one has answered them, too.

It's almost been a week I'm looking for an answer, but I couldn't solve the problem.

**Comment by hamedgasemi200** [comment]
@driesvints I really have no idea what could be the problem

https://stackoverflow.com/questions/48299669/private-channel-not-working-in-laravel

There have been some other people who have had the same issue, but no one has answered them, too; it's almost been a week since I'm looking for an answer, but I couldn't solve the problem.

I wish you could help me, or mention someone who knows about Laravel's internal codes; I really think the problem has something to do with the Laravel itself because my code used to work last year.

**Comment by driesvints** [comment]
Please try some more channels first like Laravel's Discord.

**Comment by irpcpro** [comment]
> 

Hi.
did you find out about this problem ?
i have the same issue.

**Comment by Tiamenti** [comment]
I'm not sure how relevant this will be now, but recently I came across this problem. And maybe it will help someone.

By default, `BroadcastServiceProvider` loading is disabled in Laravel. All you have to do is go to `config/app.php` and uncomment the line `App\Providers\BroadcastServiceProvider::class`.
