### ISSUE TITLE
Router bug on search form

### ISSUE THREAD

**Issue by elisonkaloshi** [laravel/framework#41819]
- Laravel Version: 9
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Router bug on the search form

### Steps To Reproduce:

1. Create a router with date params `router-name/{start_date}/{end_date}`
2. Create a form in a blade view, with an action that contains get method and dates will be as params
3. Submit dhe form.

After submitting the form the route will be, `router-name/13/03/2022/04/04/2022` and it will cause an error because it will not know which is the route param because of `/`.

### Solutions for me:

1. Change time format to 13-03-2022
2. Using a post request to get the data, and the body contains the data(in this case the `start` and `end` date)
3. Use Request class inside controller to get the data even using a get action method.

**Comment by driesvints** [comment]
`outer-name/13/03/2022/04/04/2022` doesn't matches `router-name/{start_date}/{end_date}`. Try `router-name/13-03-2022/04-04-2022`.

**Comment by elisonkaloshi** [comment]
> `outer-name/13/03/2022/04/04/2022` doesn't matches `router-name/{start_date}/{end_date}`. Try `router-name/13-03-2022/04-04-2022`.

what solutions are there if you want to pass that date format in the router?
