### ISSUE TITLE
Redis facade hset doesn't allow passing multiple fields/values

### ISSUE THREAD

**Issue by jonnylink** [laravel/framework#41829]
- Laravel Version: 9.6.0
- PHP Version: 8.1.2
- Redis Version: 6.2.6
- Redis Connection: PhpRedis

### Description:
Laravel PHP Redis Connection's `hset` implementation doesn't properly allow passing multiple fields/values. `hmset` does allow this, but it is deprecated as of Redis v4. I would expect `hset` to function properly like `hmset`. 

I did a quick dig and it looks like hset is really using `hsetnx` behind the scenes which is confusing since the [Laravel docs](https://laravel.com/docs/9.x/redis#interacting-with-redis) specifically say the facade can call any Redis command.

### Steps To Reproduce:

Easily reproduced in tinker
```
>>> use Illuminate\Support\Facades\Redis;
>>> Redis::hset('foo', 'cow', 'moo', 'sheep', 'baa')
TypeError: Redis::hSet() expects exactly 3 arguments, 5 given

>>> Redis::hmset('foo', 'cow', 'moo', 'sheep', 'baa')
=> true

>>> Redis::hgetall('foo')
=> [
     "cow" => "moo",
     "sheep" => "baa",
   ]
```

[In the docs](https://redis.io/commands/hset/) and as demonstrated in the redis-cli below, `hset` allows multiple entries:
```
redis /run/redis/redis.sock> hset 'bar' 'cat' 'meow' 'dog' 'bark'
(integer) 2

redis /run/redis/redis.sock> hgetall 'bar'
1) "cat"
2) "meow"
3) "dog"
4) "bark"
```

**Comment by jonnylink** [comment]
Damnit. This is an issue further upstream: https://github.com/phpredis/phpredis/issues/1768

**Comment by eduance** [comment]
In case anyone is still finding this thread, by serializing the array it will work.

I have fixed it by:

```Redis::hset(123, 'subjects', json_encode($request->get('subjects')));```

```Redis::hget(123, 'subjects');```
