### ISSUE TITLE
database config 'mysql.version' and 'mysql.server_version' used in the same way

### ISSUE THREAD

**Issue by bjhijmans** [laravel/framework#41823]
- Laravel Version: 8.83.5
- PHP Version: 8.0.14
- Database Driver & Version: MySQL (any version)

### Description:

Our customer uses an Azure MySQL database, and automatic version detection for those databases is not implemented in DBAL. As a result we had to add an option to set the server version in the database config. However I found that the config `database.mysql.version` and `database,mysql.server_version` both have to be set.

This line uses `server_version`:

https://github.com/laravel/framework/blob/bb071a97b4cc14ab66605fea30c6d3766d474a77/src/Illuminate/Database/Connection.php#L1011

and this line uses `version`:

https://github.com/laravel/framework/blob/bb071a97b4cc14ab66605fea30c6d3766d474a77/src/Illuminate/Database/Connectors/MySqlConnector.php#L200

I couldn't find anything about it in the documentation, and as far as I can tell the two fields should always have the same value. It's really counterintuitive that you would need to fill out both of these fields.

**Comment by driesvints** [comment]
Heya, Isn't this because the doctrine connection can be a different server version? I think it's best that if you want to optimize something here that you attempt a PR, thanks.
