### ISSUE TITLE
Unable to use default values with built-in JSON casts

### ISSUE THREAD

**Issue by flexchar** [laravel/framework#41833]
- Laravel Version: 9.6.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL Community Server 8.0.23

### Description:

Attempting to set [default values ](https://laravel.com/docs/9.x/eloquent#default-attribute-values)for a json column causes a fatal error anytime a new instance of the model is being created. 

```
TypeError: json_decode(): Argument #1 ($json) must be of type string, array given

/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1186
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1958
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1905
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1839
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasTimestamps.php:50
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1153
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1003
/var/www/tests/Feature/DatabaseCustomCastsTest.php:41
```

![image](https://user-images.githubusercontent.com/9198896/161730104-a59d5d69-fe33-466f-96b8-3fd2d49a766d.png)

### Steps To Reproduce:

I've created a pull request with a test for this bug. Notice the added attributes to already written test by Laravel. 

Request: https://github.com/laravel/framework/pull/41832

Test: https://github.com/laravel/framework/blob/60d60c5e4032702c95bc93fea1c3102587e8bd20/tests/Integration/Database/DatabaseCustomCastsTest.php

Cheers!

**Comment by driesvints** [comment]
Heya. You've already sent in a PR with a failing test so let's take it from there. No need to have duplicate posts : )

Thanks

**Comment by flexchar** [comment]
Alrighty! I thought an _issue_ is necessary. I've merged the contents of the post to the PR. :))

**Comment by flexchar** [comment]
@driesvints just seen! Perhaps I can solve this myself and update PR with a fix! It'd be an amazing experience for me!

**Comment by driesvints** [comment]
@flexchar does it work for you if you do:

```
protected $attributes = [
        'array_object_json' => (object) [
            'name' => 'Bob',
            'age' => 0
        ],
    ];
```

**Comment by MohammedAttya2** [comment]
After some investigations, you have 2 options
1. Set the attribute `array_object_json` as string (`json`)
2. Not cast the `array_object_json` as `ArrayObject::class`

If any change need, I am willing to work on it

**Comment by driesvints** [comment]
Yeah indeed @MohammedAttya2 is right actually. This needs to be set as a string, not an array.

**Comment by flexchar** [comment]
@driesvints Casting array as an object doesn't help. 

However setting as a `json` string works. (2nd option from @MohammedAttya2).
That's also the workaround I'm using right now. 

Should we update the documentation if it's intended behavior?

**Comment by driesvints** [comment]
> Should we update the documentation if it's intended behavior?

Where do you see your own example? What do you want to update?

**Comment by flexchar** [comment]
These two links in question: 
https://laravel.com/docs/9.x/eloquent-mutators#array-and-json-casting
https://laravel.com/docs/9.x/eloquent#default-attribute-values

Since I interact with `AsArrayObject` class as an array my first understanding was that I shall also set it as an a array to the default Model attributes. We've discovered that this is not the case. The documentation doesn't talk about this at all. 

My proposition is to add a small paragraph saying that if you want set default values for attributes that has custom casts defined, they shall be written the same as they were stored in the database. In this case, a `json` string. 

What do you think?

**Comment by driesvints** [comment]
Yeah I think some clarification can be useful as I've seen more cases of people running into this. Feel free to add that as well as a small code snippet with an example 👍
