### ISSUE TITLE
Calling Artisan::call('migrate:fresh') in a controller after performing a schema dump results in 'mysql: command not found'

### ISSUE THREAD

**Issue by francoislevesque** [laravel/framework#41841]
- Laravel Version: 9.1.4
- PHP Version: 8.0.17
- Database Driver & Version: MySQL 8.0.27
- Using Laravel Valet 2.0

### Description:

Calling Artisan::call('migrate:fresh') in a controller after performing a schema dump results in 'mysql: command not found'.

### Steps To Reproduce:

- Copy this project https://github.com/francoislevesque/schema-dump-issue
- Run `php artisan migrate:fresh`
- Run `php artisan schema:dump`
- Open `/` and see exception thrown : 

```
The command "mysql --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}"
```

**Comment by driesvints** [comment]
You should not call migration commands from a controller.

**Comment by driesvints** [comment]
Hmm, I'm sorry but I think those migration commands should always be run from the CLI...
