### ISSUE TITLE
Stringable exactly not match other Stringable

### ISSUE THREAD

**Issue by medeiroz** [laravel/framework#41845]
- Laravel Version: 9.5.1
- PHP Version: 8.1
- Database Driver & Version: N/A

### Description:
When need compare two Stringable variables with exactly method. Then false is returned

### Steps To Reproduce:

```php
<?php

$first = \Str::of('name');
$second = \Str::of('name');
$first->exactly($second);
//  => false

// true is expected but false is returned

```

![image](https://user-images.githubusercontent.com/11270546/161881856-151f8c08-cbf7-4a06-afcc-385fb840b5bc.png)

**Comment by medeiroz** [comment]
link this isseu with this [PR-41846](https://github.com/laravel/framework/pull/41846)

**Comment by driesvints** [comment]
There is no bug here. You can only pass a string to this method.

**Comment by driesvints** [comment]
I see what you mean now but this is a feature request. Let's see how your pr goes.
