### ISSUE TITLE
Migration timestamps() should useCurrent() and useCurrentOnUpdate()

### ISSUE THREAD

**Issue by newton4al** [laravel/framework#41857]
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Version: MySQL

### Description:
Maybe not particularly a bug, but when creating migrations and using the `$table->timestamps()`, the current definition from the `Illuminate\Database\Schema\Blueprint` class is;

```php
    /**
     * Add nullable creation and update timestamps to the table.
     *
     * @param  int  $precision
     * @return void
     */
    public function timestamps($precision = 0)
    {
        $this->timestamp('created_at', $precision)->nullable();

        $this->timestamp('updated_at', $precision)->nullable();
    }
```

The timestamp columns usually get nicely handled by eloquent when you're dealing with a single model instance.

In my opinion, I think this implementation completely assumes that the table will always have an eloquent model and that Eloquent will always handle the timestamps that go in there.

Even with Eloquent, those timestamp columns however don't get updated when you do mass inserts/updates/upserts/deletes. For example;

```php
User::where('status', true)->update(['status' => false]);
```
Also, if for some reason, I were to write some quick custom query directly in MySQL CLI, I'd expect that those columns get handled internally by MySQL.

### My Proposition
What I think that the `$table->timestamps()` should be doing internally is something like;

```php
    /**
     * Add creation and update timestamps to the table.
     *
     * @param  int  $precision
     * @return void
     */
    public function timestamps($precision = 0)
    {
        $this->timestamp('created_at', $precision)->useCurrent();

        $this->timestamp('updated_at', $precision)->nullable()->useCurrentOnUpdate();
    }
```
Notice that `created_at` isn't nullable, since in fact, every DB row must be created and of course should have a creation timestamp. 

This way, when eloquent is not involved, mysql can handle it internally. (PS: I know there may some timezone considerations, but that's a different topic).

Off course, I can easily use the methods `useCurrent();` and `useCurrentOnUpdate();` provided by the `Illuminate\Database\Schema\Blueprint` class in my migrations or make my own macro to wrap the definitions, but it usually feels better to use built-in methods than creating custom ones.

I hope all of this makes any sense at all.

**Comment by JackWH** [comment]
This would make it very difficult to temporarily disable timestamps when working with Eloquent models. For example, you might have a `User` model which records a `last_login_at` timestamp. Without timestamps being enforced at the database level, you can write:

```php
$user = Auth::user();
$user->timestamps = false;
$user->last_login_at = now();
$user->save();
```

This updates the `last_login_at` field, but without modifying `updated_at`. You might want to do this if you have application logic which checks the `updated_at` column to see the last time a user changed their account settings, for example.

I guess adding a new `timestampsWithUpdates()` function would be a better approach than modifying the existing `timestamps()` default.

**Comment by newton4al** [comment]
@JackWH  valid point for the `updated_at` field!

But with your example, it then means the `updated_at` field is not actually a source of truth. Because ideally, when you do `$user->last_login_at = now()`, you have actually updated the row, and your `updated_at` field should reflect that change, else the table isn't idiot-proof.

How about the `created_at` field? I suppose you can only create a DB row once, and that timestamp remains forever unchanged.

**Comment by ankurk91** [comment]
The `useCurrent()` method does not honor the timezone of application, does not fire eloquent model events either

**Comment by driesvints** [comment]
This is a feature request. I don't think we'll take any action here at the risk of breaking changes.
