### ISSUE TITLE
No longer possible to see name/description for scheduled closure in schedule:list

### ISSUE THREAD

**Issue by ehamrin** [laravel/framework#41852]
- Laravel Version: v9.7.0
- PHP Version: 8.0.17
- Database Driver & Version: Not applicable

### Description:
Adding a description/name to CallbackEvent is ignored on the schedule:list command, the closure location is printed. 

Seems to have broken by [#41535 ](https://github.com/laravel/framework/pull/41535)

### Steps To Reproduce:
Add the following in app/Console/Kernel.php
```php
$schedule
	->call(function() {
		//Do stuff here
	})
	->name('My pretty description');
```

The following is printed when running `php artisan schedule:list` 
```
* * * * *  Closure at: app\Console\Kernel.php:32 ................................................... Next Due: 34 seconds from now

```

Expected output is 
```
* * * * *  My pretty description ................................................... Next Due: 34 seconds from now
```

**Comment by driesvints** [comment]
Ping @xiCO2k

**Comment by xiCO2k** [comment]
I think the pretty description will be available if you run with `php artisan schedule:list -v`.

**Comment by ehamrin** [comment]
Glad to see it's still available with `-v`.

It should be reversed though, I'm setting the name explictly to differentiate the callbacks. Having up towards 100 scheduled commands with a closure location tells me nothing of what they do - the name does. And it gets bloated with multiple lines using verbose.

The location is great for debugging purposes, and should be visible with the verbose flag and the name/description should be the default output.

**Comment by driesvints** [comment]
Seems this was intentional. You can always attempt a pr to change Taylor's mind. Thanks all.
