### ISSUE TITLE
Specifying a specific seeder on base test class does not apply when using in-memory Sqlite DB

### ISSUE THREAD

**Issue by cicnavi** [laravel/framework#41863]
- Laravel Version: 8.76.0
- PHP Version: 7.3.25 
- Database Driver & Version: in-memory Sqlite

### Description:
According the [docs for seeding while testing](https://laravel.com/docs/8.x/database-testing#running-seeders), we can specify a specific seeder on the base test class which would then be ran instead of the default Database\Seeders\DatabaseSeeder class. This does not work if in-memory SQLite DB is used.

My first thought is that this is because artisan migrate command does not accept seed class parameter (used here https://github.com/laravel/framework/blob/45de4c45dc3908a7f8149af34603684311cd0d0e/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L45),
while artisan migrate:fresh command does (used here https://github.com/laravel/framework/blob/45de4c45dc3908a7f8149af34603684311cd0d0e/src/Illuminate/Foundation/Testing/RefreshDatabase.php#L70)

Is there a reason for not running aditional artisan db:seed command in \Illuminate\Foundation\Testing\RefreshDatabase::refreshInMemoryDatabase() method instead of seeding it using artisan migrate (if seeding is enabled and specific seeder is set on base test class)? 

To address this I simply seed with specific seeder on my test class using $this->seed('SpecificSeeder') method.

The problem was mentioned [here](https://github.com/laravel/framework/issues/37339#issuecomment-840520926), however it was not addressed further.

Thank you for your valuable work...

### Steps To Reproduce:
Set a specific seeder class in base test class while using in-memory Sqlite DB.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by cicnavi** [comment]
Hi, here is the repo:

https://github.com/cicnavi/bug-report

with one commit https://github.com/cicnavi/bug-report/commit/023154160801cb15a67fd65f54d4b9fd6973db1e

As per docs, I have added a $seeder prop in \Tests\TestCase which points to custom seeder \Database\Seeders\TestDatabaseSeeder. 

The test \Tests\Feature\SeedingUsingCustomSeederTest::testSampleFromTestSeederExists fails because it expects a Sample in DB which should have been seeded from custom seeder \Database\Seeders\TestDatabaseSeeder instead of default \Database\Seeders\DatabaseSeeder (as per docs).

**Comment by driesvints** [comment]
@cicnavi your test contains `test` as a value while your seeder contains `default`.

**Comment by cicnavi** [comment]
@driesvints Erm, please check again: https://github.com/cicnavi/bug-report/blob/023154160801cb15a67fd65f54d4b9fd6973db1e/database/seeders/TestDatabaseSeeder.php#L17

**Comment by driesvints** [comment]
Sorry, I misread that. You're correct, this seems broken right now.

**Comment by driesvints** [comment]
I managed to write a fix for this. Please check and test https://github.com/laravel/framework/pull/41869. I managed to get your test passing with it.

**Comment by cicnavi** [comment]
That was quick... Tried it out on a real project and works as expected.
I hope it will also be fixed in v9.*...
Thanks and best regards

**Comment by driesvints** [comment]
@cicnavi yeah bug fixes are merged upstream so it'll land in 9.x as well if it gets merged.
