### ISSUE TITLE
ValidationException coudn't be fully localized

### ISSUE THREAD

**Issue by perkthefox** [laravel/framework#41876]
- Laravel Version: 9.7.0
- PHP Version: 8.1.3

### Description:
\Illuminate\Validation\ValidationException end of `message` saying "and <count> more errors" coudn't be translated to any other languages rather than default English.

That problem definetely coming from `summarize` method of \Illuminate\Validation\ValidationException class
```php
protected static function summarize($validator)
    {
        $messages = $validator->errors()->all();

        if (! count($messages)) {
            return 'The given data was invalid.';
        }

        $message = array_shift($messages);

        if ($additional = count($messages)) {
            $pluralized = $additional === 1 ? 'error' : 'errors';

            $message .= " (and {$additional} more {$pluralized})";
        }

        return $message;
    }
```
I propose to replace a default hardcoded string ` " (and {$additional} more {$pluralized})"` to something like `__('validation.more_errors', ['count' => 1])` in order to be more accurate when it comes to localization process.

### Steps To Reproduce:
Throw any ValidationException with more than one error.

**Comment by derekmd** [comment]
* https://github.com/laravel/framework/issues?q=is%3Aissue+ValidationException+translate
* https://github.com/laravel/framework/pulls?q=is%3Apr+ValidationException+translate

This message isn't meant for users in production. The exception handler reports it in the local/staging environment for developers. Method `ValidationException@errors()` returns localized translations.

**Comment by driesvints** [comment]
Heya, Please try to search the issue and PR trackers first before posting, thanks.

Thanks @derekmd
