### ISSUE TITLE
Allowed memory size exhausted during PHPUnit tests since version 9.

### ISSUE THREAD

**Issue by MichMich** [laravel/framework#41873]
- Laravel Version: 9.7.0
- PHP Version: PHP 8.0.17
- Database Driver & Version: sqlite (during tests)

### Description:

Ever since I've upgraded to Laravel 9, I've been unable to run my tests via `php artisan test` or `./vendor/bin/phpunit`. Both result in Fatal error: Allowed memory size exhausted after ~40% of the tests (790 in total). 

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 69632 bytes) in /Users/Michael/Code/project-name/vendor/fakerphp/faker/src/Faker/Provider/Base.php on line 202

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /Users/Michael/Code/project-name/vendor/symfony/string/AbstractUnicodeString.php on line 208
```

Note that the actual place of the fatal error changes every time.

It seems I am not the only user with this problem: https://stackoverflow.com/questions/71333320/phpunit-fails-with-allowed-memory-size-of-134217728-bytes-exhausted-tried-to-a/71663309#71663309

I've tried increasing the memory limit, but this didn't solve the issue. 

I found two workarounds: 

- Run the unit tests in isolation: `processIsolation="true"`
- Use `php artisan test --parallel`

Before Laravel 9 the tests seem to run fine. 

### Steps To Reproduce:

Unfortunately I'm unable to share the repository. And a memory issue is hard to debug, so I understand this isn't of any help. But it might be good to record this issue here in case other run into the same problem. 

Let me know if you want me to try something out to see if it helps. 

Thanks!

**Comment by driesvints** [comment]
> Unfortunately I'm unable to share the repository. 

I'm afraid we won't be able to be of much help if the problem cannot be reproduced in a fresh Laravel repository. You might also want to be aware of https://github.com/laravel/framework/issues/30736

I'm going to have to ask you to try a support channel instead, sorry:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by MichMich** [comment]
Ok, no worries. That mentioned issue might indeed be the issue.

**Comment by MichMich** [comment]
For anyone stumbling upon this issue: it turns out php8 and/or php unit has a memory leak. The reason why this gave me real issues is that it turned out I had a manual memory override in my code somewhere:

```
ini_set('memory_limit', '256M');
```

After removing this, my tests run without issues. Of course this isn't a solution for the memory leaks, but at least my tests are able to run. 

If you have the same issues, check your code for similar mistakes.

**Comment by zombiesplat** [comment]
> For anyone stumbling upon this issue: it turns out php8 and/or php unit has a memory leak. The reason why this gave me real issues is that it turned out I had a manual memory override in my code somewhere:
> 
> ```
> ini_set('memory_limit', '256M');
> ```
> 
> After removing this, my tests run without issues. Of course this isn't a solution for the memory leaks, but at least my tests are able to run.
> 
> If you have the same issues, check your code for similar mistakes.

This saved me SOOO much time! thank you for posting it
