### ISSUE TITLE
Calling toBase() on relationships removes soft-deleted condition in Laravel 9 compared to Laravel 8

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#41885]
- Laravel Version: 9.7.0
- PHP Version: 8.1.1

### Description:
In Laravel 9 the `toBase()` function behaves differently than in Laravel 9 when used on a relationship: The `deleted_at IS NULL` condition of the `SoftDeletes` scope was still applied to relationship queries in Laravel 8 when calling `toBase()`, but in Laravel 9 the condition is missing. However calling `toBase()` on a normal Eloquent query still retains the `deleted_at IS NULL` condition of the `SoftDeletes` trait in Laravel 9.

### Steps To Reproduce:

```php
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class ModelA extends Model
{
    use SoftDeletes;
    
    public function modelsB(): HasMany
    {
        return $this->hasMany(ModelB::class);
    }
}

class ModelB extends Model
{
    use SoftDeletes;
}

Model::unguard();
$modelA = new ModelA(['id' => 1]);

// Laravel 8: [...] where [...] and "model_b_s"."model_a_id" is not null and "model_b_s"."deleted_at" is null
// Laravel 9: [...] where [...] and "model_b_s"."model_a_id" is not null and "model_b_s"."deleted_at" is null
$modelA->modelsB()->dump();

// Laravel 8: [...] where [...] and "model_b_s"."model_a_id" is not null and "model_b_s"."deleted_at" is null
// Laravel 9: [...] where [...] and "model_b_s"."model_a_id" is not null and "model_b_s"."deleted_at" is null
$modelA->modelsB()->getQuery()->dump();

// Laravel 8: [...] where [...] and "model_b_s"."model_a_id" is not null and "model_b_s"."deleted_at" is null
// Laravel 9: [...] where [...] and "model_b_s"."model_a_id" is not null
$modelA->modelsB()->toBase()->dump();

// Laravel 8: [...] where "model_a_s"."deleted_at" is null
// Laravel 9: [...] where "model_a_s"."deleted_at" is null
$modelA->newQuery()->toBase()->dump();
```

**Comment by driesvints** [comment]
I'm not 100% sure but think it has got something to do with https://github.com/laravel/framework/pull/37956 maybe? @inxilpro do you have any ideas here?

**Comment by driesvints** [comment]
If I changed `toBase` to the below with `applyScope` then it works for me:

```php
    /**
     * Get a base query builder instance.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    public function toBase()
    {
        return $this->query->applyScopes()->getQuery();
    }
```

@tpetry can you try that out? I have no idea if there are more implications...

**Comment by inxilpro** [comment]
> I'm not 100% sure but think it has got something to do with https://github.com/laravel/framework/pull/37956 maybe? @inxilpro do you have any ideas here?

#37956 was reverted before 9.0 was released, so I don't think this has anything to do with that. I can take a peek in a bit, though!

**Comment by driesvints** [comment]
@inxilpro I think I found the solution (see my comment above) but need some more eyes on it to make sure we don't break anything...

**Comment by tpetry** [comment]
I can verify that the soft-deletes are now handled correctly, but something is still incorrect. I am researching a many hundreds of lines hand-optimized query built with the query builder. I guess your change is having another side effect.

**Comment by tpetry** [comment]
@driesvints My mistake, I can say that your change to test fixes the problem completely. It didn't have any side effects for me with this complex query, the query is now identical in Laravel 8 and Laravel 9.

**Comment by driesvints** [comment]
Thanks all. I sent in a PR here: https://github.com/laravel/framework/pull/41918
