### ISSUE TITLE
Integer Validation permits boolean true

### ISSUE THREAD

**Issue by luke-navitas** [laravel/framework#41884]
- Laravel Version: 9.7.0
- PHP Version: 8.1.4
- Database Driver & Version: N/A

### Description:

When enforcing `integer` validation. the boolean true is allowed

### Steps To Reproduce:

- Make a request class, that has a single field to validate

```
public function rules()
{
    return [
        'age' => ['nullable', 'integer']
    ];
}
```

- Make an API reuest passing boolean `true` for age parameter
- Expected validation to fail, but it passes

This is becasue filter_var (used here.... https://github.com/laravel/framework/blob/e03e904a20f50c9cb21887ab60c0546fcf2aba3d/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L1218) has inconsitencies see this demo (https://3v4l.org/Jll7b).

**Comment by luke-navitas** [comment]
using `return is_int($value)` would likely solve this incosistency.

**Comment by driesvints** [comment]
The current behavior is correct. See the docs:

<img width="726" alt="Screenshot 2022-04-08 at 11 13 03" src="https://user-images.githubusercontent.com/594614/162404921-550a0a8f-61eb-4496-941f-7ef71c405073.png">
