### ISSUE TITLE
Defining a database connection in the Bus class

### ISSUE THREAD

**Issue by olekjs** [laravel/framework#41892]
- Laravel Version: 9.7.0
- PHP Version: 8.0.17
- Database Driver & Version: sqlsrv, sqlite

### Description:
I have two databases, one is **sqlsrv** and the other is **sqlite**. The first SQL database is the master database. The **sqlite** database is used to hold everything related to queues, i.e. the tables jobs, job_batches, failed_jobs.

I would like to create a job batch so that the record is saved in the **sqlite** table. In the .env file, under the DB_CONNECTION variable, I have the **sqlsrv** database - because it's my main database.

By default, the Illuminate\Bus\BatchRepository class uses the connection that is defined under the DB_CONNECTION variable. Not did I find a method that would change the connection this class uses.

There is an `onConnection` method in the Bus class, except that it defines the connection not for the bus but for individual jobs.

Is there a method I can't see or is it just impossible to change the bus batch connection at the moment?

### Steps To Reproduce:

It is enough to create two databases, one of them should be set in .env under the DB_CONNECTION variable.

Then you need to create a migration for the job_batches table pointing to the connection to the second database, the one that is not defined in .env under the DB_CONNECTION variable.

```php
protected $connection = 'sqlite'; // In my case I have sqlsrv under DB_CONNECTION and sqlite database here

public function up(): void
{
    Schema::create('job_batches', function (Blueprint $table) {
        $table->string('id')->primary();
        $table->string('name');
        $table->integer('total_jobs');
        $table->integer('pending_jobs');
        $table->integer('failed_jobs');
        $table->text('failed_job_ids');
        $table->mediumText('options')->nullable();
        $table->integer('cancelled_at')->nullable();
        $table->integer('created_at');
        $table->integer('finished_at')->nullable();
    });
}
```

Then you need to create a bus batch:

```php
return Bus::batch([
    new SomeJob(),
])->dispatch();
```
Then we get an error:

`SQLSTATE[HY000]: General error: 20018 Invalid object name 'job_batches'. [20018] (severity 16)`

**Comment by korkoshko** [comment]
Hi!

> Is there a method I can't see or is it just impossible to change the bus batch connection at the moment?

You can set up "batch" connection via queue config, just add key "batching.database" with value "sqlite".
`    'batching' => ['database' => 'sqlite'],
`
See to [BusServiceProvider](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Bus/BusServiceProvider.php#L49).

**Comment by olekjs** [comment]
This is what I was looking for! I missed somewhere that this class can be defined in the provider.

Thank you very much @korkoshko!
