### ISSUE TITLE
Type signatures in Illuminate\Log\Logger are incompatible with Psr\Log\LoggerInterface, triggering PHPStan warnings

### ISSUE THREAD

**Issue by luke8086** [laravel/framework#41909]
- Laravel Version: 9.7.0
- PHP Version: 8.1.4
- Database Driver & Version: -

### Description:

The PHPDoc type signatures of `$message` params in the logging functions of [`Illuminate\Log\Logger`](https://github.com/laravel/framework/blob/v9.7.0/src/Illuminate/Log/Logger.php#L52) are incompatible with its parent interface [`Psr\Log\LoggerInterface`](https://github.com/php-fig/log/blob/master/src/LoggerInterface.php#L30).

In `LoggerInterface` they are `string|\Stringable`, while in `Logger` they are: `\Illuminate\Contracts\Support\Arrayable|\Illuminate\Contracts\Support\Jsonable|\Illuminate\Support\Stringable|array|string`, and don't include plain `\Stringable`

This causes PHPStan warnings when directly passing common stringable types like exceptions/throwables.

There are also intelephense warnings in VSCode, directly in `Illuminate\Log\Logger`, for example: `Method 'Illuminate\Log\Logger::emergency()' is not compatible with method 'Psr\Log\LoggerInterface::emergency()'.intelephense(1038)`, 

Simply adding `\Stringable` to the list should work, because `$message` gets casted to string in [`formatMessage()`](https://github.com/laravel/framework/blob/v9.7.0/src/Illuminate/Log/Logger.php#L265)

### Steps To Reproduce:

```php
use Illuminate\Support\Facades\Log;
use Throwable;

try {
    // ...
} catch (Throwable $e) {
    Log::error($e);
}
```

PHPStan output:

```
Parameter #1 $message of static method Illuminate\Log\Logger::error() expects array|Illuminate\Contracts\Support\Arrayable|Illuminate\Contracts\Support\Jsonable|Illuminate\Support\Stringable|string, Throwable given.
```

**Comment by driesvints** [comment]
This isn't really a bug since it doesn't breaks anything. Feel free to send a PR if you want to change anything, thanks.
