### ISSUE TITLE
Mimetype of `UploadedFile::fake()` lost when saved in storage in Laravel 9 compared to Laravel 8

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#41916]
- Laravel Version: 9.7.0
- PHP Version: 8.0.3

### Description:

I recently upgraded a project from Laravel 8 to Laravel 9, and I noticed that saving a `UploadedFile` instance in Laravel Storage results in the loss of the mime type of that `UploadedFile` instance. This was not the case in Laravel 8.

This currently results in the inability to write tests for code where the mime type of a file is validated. For example, if you want to fake a CSV file, then that is currently not possible because the mime type of that fake file will never be "text/csv".

### Steps To Reproduce:

```php
Route::get('/', function () {
    // Fake file has mime type "text/csv"
    dump($fakeFile = \Illuminate\Http\UploadedFile::fake()->create('test.csv', 123, 'text/csv'));

    dump($savedFilePath = Storage::put('tmp', $fakeFile));

    // Now the saved file does not have mime type "text/csv" anymore. It is now "application/x-empty".
    // If you run this in a Laravel 8 project, you will get "text/csv" as mime type.
    dump(Storage::mimetype($savedFilePath));
});
```

**Comment by driesvints** [comment]
This seems to be a change in Flysystem between v1 and v2 & v3. In v1 it seems this was detected and a fallback to the extension name was used. See https://github.com/thephpleague/flysystem/blob/094defdb4a7001845300334e7c1ee2335925ef99/src/Adapter/Local.php#L325-L327

In v3 I don't see any such fallback method (not in `league/mime-type-detection` or in Flysystem itself). I don't see any mention of this in Flysystem's upgrade guide so my best guess is that this was forgotten: https://flysystem.thephpleague.com/docs/upgrade-from-1.x/

It's best that you report this to the Flysystem issue tracker.
