### ISSUE TITLE
Translate whole file while using replacements

### ISSUE THREAD

**Issue by lenssoft** [laravel/framework#41917]
- Laravel Version: 8.83.7
- PHP Version: 7.4.28
- Database Driver & Version: mysql 8

### Description:

Translator throws warning when trying to translate a whole translation file containing array keys and using replace keys feature.

Last known to work with v8.61.0

### Steps To Reproduce:

trans('validation', ['key' => 'to_replace'], 'en')

outcome:
<warning>PHP Warning:  strtr() expects parameter 1 to be string, array given in /app/vendor/laravel/framework/src/Illuminate/Translation/Translator.php on line 226</warning>

**Comment by driesvints** [comment]
You're trying to call `trans` on an entire validation file. You should call it like `trans('validation.<your-key-here>', ['key' => 'to_replace'], 'en')`.

**Comment by lenssoft** [comment]
It is easy to close since translating an entire file is not mentioned in the documentation but it used to work.

Here is the output using v8.83.7 raising a warning

![image](https://user-images.githubusercontent.com/9431885/162733634-28703e98-df43-4e02-9079-44ba8a5e8298.png)

And this is the output using v8.66.0 , which had no problem replacing even in nested translation keys.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/9431885/162734028-80039d31-4318-4765-b4c3-c86fec2b13c9.png">

My real world usecase was tranlating an entire file with nested translation keys in one go, which used to work before https://github.com/laravel/framework/pull/39298

I will get around it, but I still consider it a regression since it used to work.
