### ISSUE TITLE
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by mafecito** [laravel/framework#41929]
- Laravel Version: 9.7.0
- PHP Version: 8.1.4

### Description:

Accessing a route with // in the path like http://127.0.0.1:8000//hello emits a deprecated notice. 

Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /workspaces/xxx/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php on line 6

### Steps To Reproduce:

Add a route.
```php
Route::get('/hello', function () {
    return 'hello world';
});
```
```bash
> php artisan serve
```
Access de route with browser.

**No notice:**
- http://127.0.0.1:8000/
- http://127.0.0.1:8000//
- http://127.0.0.1:8000/hello
- http://127.0.0.1:8000/hello/
- http://127.0.0.1:8000//hello/

**Deprecated Notice:**
- http://127.0.0.1:8000//hello

Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /workspaces/xxx/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php on line 6

It should show the 404 template, without the notice.

**Comment by driesvints** [comment]
It's showing the 404 template for me

<img width="1857" alt="Screenshot 2022-04-12 at 08 44 06" src="https://user-images.githubusercontent.com/594614/162897428-e1e70e99-10b4-497b-927e-87644e824c5f.png">

**Comment by driesvints** [comment]
Ah that was the wrong url. I can reproduce this.

**Comment by moamahfouz** [comment]
Thanks for sharing such issue, that is why we all love open source. ❤️
