### ISSUE TITLE
Unable to override command (introduced in 9.6.0)

### ISSUE THREAD

**Issue by vadimpronin** [laravel/framework#41946]
- Laravel Version: 9.6.0-9.8.1
- PHP Version: 8.1

### Description:

It is currently impossible to override a command handler provided by a package by creating a new command in **app/Console/Commands** with the same signature.
For example, package **laravel/vapor-core** has "stub" command **vapor:handle** which only throws exception with a request to create a custom **vapor:handle** command to process the input. But creating custom command with the same signature does not have any effect. Running `php artisan vapor:handle PayLoaD` still executes the handler from the **vapor-core** package and ignores custom handler from **app/Console/Commands** (or any other package)

### Steps To Reproduce:

1. Install vapor-core: `composer require laravel/vapor-core`
2. Create new command overriding default handler from vapor-core: `php artisan make:command CustomHandler --command="vapor:handle {payload}"`
3. Run command: `php artisan vapor:handle PayLoaD`

GitHub repository demonstrating the issue: https://github.com/vadimpronin/bug-report

### Possible cause:
I was able to pinpoint the problem to the new method **getDefaultName** in **src/Illuminate/Console/Command.php** in this commit: https://github.com/laravel/framework/commit/628d39f02cdb78ecb3049db8ce75fca2b3d20ec0#diff-132f1c15b2ac9b4ff179e85239c0a55e0daead42be5a2095b0fe765d3bc9ebd0R95

Specifically when this method is deleted (thus the parent method is used instead) everything works fine.
The parent method returns **null** for the overriding command's class, while the new method returns **string "vapor:handle"** taken from command's signature. I didn't quite understand how it affects the behaviour of overriding

**Comment by driesvints** [comment]
Thanks @vadimpronin. We're going to revert that commit.

**Comment by driesvints** [comment]
We've reverted this. This will be in Tuesday's release. Thanks
