### ISSUE TITLE
Route Model Binding not working on changed structure

### ISSUE THREAD

**Issue by alexgaal** [laravel/framework#41952]
- Laravel Version: 9.6.0
- PHP Version: 8.1.3
- Database Driver & Version:

### Description:
I decided to change the default directory structure of Laravel in a specific project. Now I am implementing my test cases and I recognized through these that somehow route model binding is not working correctly.

**Example of directory structure**
```
/bootstrap
/config
/database
/public
/resources
/routes
/src
/storage
/tests
```

I obviously had to change the autoload of my `composer.json` to this:
```
"autoload": {
    "psr-4": {
        "App\\": "src/App/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/",
        "Domain\\": "src/Domain/",
        "Support\\": "src/Support/"
    }
},
```

`php artisan route:list`
```
  GET|HEAD        api/users ................................... users.index › App\Api\User\Controllers\UserController@index
  POST            api/users ................................... users.store › App\Api\User\Controllers\UserController@store
  GET|HEAD        api/users/{user} ............................ users.show › App\Api\User\Controllers\UserController@show
  PUT|PATCH       api/users/{user}  ........................... users.update › App\Api\User\Controllers\UserController@update
  DELETE          api/users/{user} ............................ users.destroy › App\Api\User\Controllers\UserController@destroy
  PUT             api/users/{user}/restore .................... users.restore › App\Api\User\Controllers\UserController@restore
```

e.g. `UserController@restore`
```
public function restore(User $user, RestoreUserAction $restoreUserAction): UserResource
```

If I run `dd($user)` it returns a empty User object.

### Steps To Reproduce:

1. Clone a empty Laravel project
2. Run `composer require regnerisch/laravel-beyond`
3. Run `php artisan beyond:setup`
4. Change autoload of your `composer.json`
5. Create an example route and an example controller for that test case and try to model bind it to a route.

**Comment by driesvints** [comment]
I don't think in general that we support changing the app directory.

**Comment by farhad-rohani** [comment]
hello i have this problem .

**Comment by abdulrehman25** [comment]
After searching for 2 hours I got the issue details

### For route binding to work, your type-hinted variable name must match the route placeholder name

For example my edit method

Here is my route URI for the edit

```
user/role/{role}/edit
```

As you can see there is {role} placeholder in the route definition, so the corresponding variable must be called $role.

```
public function edit(Role $role)
{
   return view('role.edit',compact('role'));
}
```
