### ISSUE TITLE
Unable to retrieve the mime_type for file with Storage::download

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [laravel/framework#41960]
- Laravel Version: 9.8.1
- PHP Version: 8.1.3
- league/flysystem 3.0.16

### Description:
```
$headers["Content-Type"] = "text/plain";
$headers["Content-Length"] = $file_size;
$headers["Accept-Ranges"] = "bytes";
$headers["Content-Disposition"] = "attachment; filename={$id}.left";
$headers["Content-Range"] = "bytes " . 0 . "-" . ($file_size) . "/" . $file_size;
Storage::disk("localdisk")->download($id.".left", $headers);
```
Results in the following error:
```
local.ERROR: Unable to retrieve the mime_type for file at location: 737.found.  {"exception":"[object] (League\\Flysystem\\UnableToRetrieveMetadata(code: 0): Unable to retrieve the mime_type for file at location: 737.found.  at /var/www/hostname/vendor/league/flysystem/src/UnableToRetrieveMetadata.php:49)
```
I believe this is caused by me having a non-standard extension, which is fine since I provided the content-type in the headers explicitly. But instead I'm getting errors now with my recent upgrade from laravel 8 to laravel 9. Any way to make this work?

**Comment by TheWorkingDeveloper** [comment]
I searched extensively but this is an almost undocumented error with very few people running into it (because everyone uses default file extensions). And to my knowledge there is nothing within laravel that can be changed to resolve this issue.
@driesvints

**Comment by driesvints** [comment]
Please use the correct file extension for this.

**Comment by TheWorkingDeveloper** [comment]
What is the correct file extension for an arbitrary file for custom software? I believe there should be a default / settable fallback or optional way to specify non-standard file extensions and tie them to a known content-type. I believe I saw a commit on it a few days ago in the flysystem, but it didn't quite seem to work from what I can tell. (https://github.com/thephpleague/flysystem/commit/e8515341994dc2feb13a5723316ae521841eda0f)

For example csv, tsv, xml, json are all common filetypes that could also be .txt all the same.

**Comment by TheWorkingDeveloper** [comment]
@driesvints what is the 'correct file extension' for a custom file format?

**Comment by henrik9999** [comment]
same problem here we also use custom file formats and arent able to use them in storage because of this
