### ISSUE TITLE
FromRaw description is wrong

### ISSUE THREAD

**Issue by gorbit99** [laravel/framework#41975]
- Laravel Version: 9.6.0
- PHP Version: 8.1.4
- Database Driver & Version: MySQL/MariaDB 10.7.3

### Description:
The description of the "fromRaw" method on query builders says "Adds a raw from clause to the query", even though it sets the from clause, making it impossible to add more without overriding previous ones.

### Steps To Reproduce:

Run the following in for example tinker.

```
DB::table("test")->fromRaw("test2 as A")->fromRaw("test3 as B")->toSql();
```

Result:
```
select * from test3 as B
```

Both the original table and the first fromRaw disappeared.
Because fromSub also uses fromRaw, it's impossible to add a raw sub from expression without overriding other ones.

**Comment by driesvints** [comment]
This is expected. You can only have one from statement here.

**Comment by gorbit99** [comment]
In this case could the documentation be changed to say that it sets the clause and doesn't add it?

**Comment by gorbit99** [comment]
Wait, there can only be one FROM statement, but in that from statement you could have multiple tables referenced. And you can mix and match sub query from clauses and regular from clauses, which currently cannot be done in laravel query builder without writing the whole thing as a raw expression
