### ISSUE TITLE
BCC is not working

### ISSUE THREAD

**Issue by mantas-done** [laravel/framework#41972]
- Laravel Version: 9.1.5
- PHP Version: 8.0.16
- Database Driver & Version:

### Description:
BCC is not added to the email and the bcc recipient doesn't get an email.
On Laravel 8 the same code works. On Laravel 9 it doesn't work even on the new project.

### Steps To Reproduce:
Mail::to('no-reply@test.com')->bcc('bcc@bcc.com)->send(new OrderShipped());

![image](https://user-images.githubusercontent.com/17127206/163336355-b74b2093-ff32-465b-8354-a6b53dc4d153.png)

**Comment by driesvints** [comment]
BCC isn't added to your log since it's not added to message body but as a header. This might be different from SwiftMailer now that we've switched to Symfony Mailer. Afaik, BCC works fine.
