### ISSUE TITLE
Use InnoDb as the default database engine

### ISSUE THREAD

**Issue by mwakalingajohn** [laravel/framework#41996]
- Laravel Version: 9.8.1
- PHP Version: 8.1.1
- Database Driver & Version:

### Description:
When I create a new Laravel project and install fortify, sanctum, or jetstream, then run the migration, I get the error string length of 1000 is too long. The solution was to add "Schema::defaultStringLength(191)", in previous versions, but now, the solution is to add "InnoDB" in the database configuration for "engine"

### Steps To Reproduce:
Install new Laravel project
Install jetstream
Install configure the database in .env
Run migrations

**Comment by mwakalingajohn** [comment]
Wrong repository, this issue was supposed to be in laravel/laravel

**Comment by driesvints** [comment]
This isn't a bug. Please search around closed issues and prs before posting a new one.
