### ISSUE TITLE
Eloquent unable to get collection more than 999 records

### ISSUE THREAD

**Issue by rationalthinker1** [laravel/framework#42011]
- Laravel Version: v8.83.0
- PHP Version 8.0.17
- mariadb:10.5

### Description:
The collection shows up empty when it's more than 999 records

### Steps To Reproduce:
I have a `Job` model as followed:
```php
<?php

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $table = 'job';
}
```
Just for testing purposes, I ran this code in the first custom middleware that I registered.
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Job;

class BeforeMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param Request $request
     * @param Closure $next
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next): mixed
    {
        /* @var $collection Collection */
        $collection = Job::findMany([60255,60631,60695,60718,60723 ...]); // 999 ids
        dd($collection->count()); // outputs 999, as it should
        return $next($request);
    }
}
```
However, if there is more than 999 ids, it shows as 0, and the collection is empty. I've been using Laravel since 2014 version 4 and I never had this type of error. I also played around a lot with using another model, adding `select('id')` and other things in general but to no avail. This is happening on production and on my local computer.

**Comment by BrandonSurowiec** [comment]
I wonder if PHP's PDO driver itself has a binding limit of max 999 variables for a single query.

Chunking and querying would get around this, Does it work if you use a `whereRaw()`?

```php
$keys = implode(',', [1,2,3]);
$collection = Job::query()->whereRaw("id IN ({$keys})")->get();
dd($collection->count())
```

**Comment by rationalthinker1** [comment]
Yes! @BrandonSurowiec, that worked. I didn't about the limitation of PHP PDO. The code that you put worked perfectly! I do use chunking afterwards when I use `whereIn('id, $keys)` but I abstracted that on the example. Despite chunking later on, it was still showing up as zero results.
