### ISSUE TITLE
Schedule list command: CallbackEvent with custom description is ignored.

### ISSUE THREAD

**Issue by pionl** [laravel/framework#42018]
- Laravel Version: 9.8.1
- PHP Version: 8.1

### Description:

Before [0256484f71a9100405c2ae6f9bc9f850e6d640cf  commit](https://github.com/laravel/framework/commit/0256484f71a9100405c2ae6f9bc9f850e6d640cf) we were able to see set `description` for `CallbackEvent`. 

Now we are able too see only  `Closure at: vendor/laravel/framework/src/Illuminate/Console/Scheduling/Schedule.php:144`.

**Would be great to leave the description / command if the description is set?**

Thank you

### Steps To Reproduce:

<img width="1904" alt="Snímek obrazovky 2022-04-17 v 14 24 52" src="https://user-images.githubusercontent.com/1878831/163714159-b8ec9918-8cff-4da7-85c6-dc10522b7db3.png">

**Comment by driesvints** [comment]
This is expected. You can show the description with the verbose flag.

**Comment by pionl** [comment]
thanks for the answer, I wonder if it should be the opposite but OK. have a great day
