### ISSUE TITLE
The mail facade cannot be use smtps with a port number other than the well known ports

### ISSUE THREAD

**Issue by hryktrd** [laravel/framework#42025]
- Laravel Version: 9.7.0
- PHP Version: 8.0.16
- Database Driver & Version: none

### Description:
When I'm using mail server that's smtps port 12345(not 465), but smtp is selected by source code at follows.
```
vendor/laravel/framework/src/Illuminate/Mail/MailManager.php
```

```php
protected function createSmtpTransport(array $config)
    {
        $factory = new EsmtpTransportFactory;

        $transport = $factory->create(new Dsn(
            ! empty($config['encryption']) && $config['encryption'] === 'tls' ? (($config['port'] == 465) ? 'smtps' : 'smtp') : '',

```

### Steps To Reproduce:
- set SMTP server that use smtps protocol only.
- set smtps port other than 465.
- set smtps port at .env file.
- send mail from mail facade.

**Comment by driesvints** [comment]
Symfony Mailer only accepts 465: https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Mailer/Transport/Smtp/EsmtpTransport.php#L51. You'll have to open an issue on their repo if you think this should be changed.

**Comment by hryktrd** [comment]
When using symphony mailer directly, it will only determine if the port is 465 if tls is not explicitly true.
But if tls is explicitly true, tls will be enabled no matter which port I use.
When using mail facade, whether to select smtps is determined only by whether the value of `$config['code']` is 465, and if it is another port, smtp is selected.

Isn't smtps available even if I select another port number here?
