### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by renkx** [laravel/framework#42024]
- Laravel Version: 9.8.1
- PHP Version: 8.1.4
- Redis Version：4.0.14

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/26194193/163745415-ec0f1289-6e15-43c8-9720-554c24ed77f6.png">

### Description:
redis occasionally returns false

Occasionally, not easy to reproduce

[#35461](https://github.com/laravel/framework/issues/35461)

**Comment by driesvints** [comment]
If there's nothing to reproduce then there's nothing we can do about it I'm afraid.

**Comment by reza305z** [comment]
I had the same problem and it was a redis container problem.

**Comment by coclav** [comment]
Doing a `artisan cache:clear` solved the issue (although we still don't know the root cause, at least we have the application running
