### ISSUE TITLE
8.x upgrade to 9.x upgrade breaks migration creation when migration stubs use the class placeholder

### ISSUE THREAD

**Issue by shortontech** [laravel/framework#42030]
- Laravel Version: 9.8.1
- PHP Version: 8.1.1
- Database Driver & Version: MySQL Community Server - GPL 8.0.27

### Description:
I recently upgraded from 8.x to the most recent version of laravel/framework, and I was attempting to create database migrations using the make:migration command, however after it succeeded, I was getting a syntax error surrounding my migration, which attempts declares a class named "{{ class }}".

MigrationCreator is no longer replacing the class placeholder, which means for those of us with stubs published before [8.37.0](https://github.com/laravel/framework/releases/tag/v8.37.0), this change is breaking, but isn't mentioned as a possible breaking change in the [upgrade guide](https://laravel.com/docs/9.x/upgrade). 

I've updated both of my migration stubs, so I don't need support to resolve any issue, I'm just reporting so that either the documentation can be fixed, or the [changes](https://github.com/illuminate/database/commit/7c2c330de17b16bfcfadd5689bf5a15c262165da) made to MigrationCreator can be reversed.

### Steps To Reproduce:

1. Have an existing instance of Laravel v8.x
2. Run artisan stub:publish or have the stubs already published.
3. Upgrade to the Laravel v9
4. Use the make:migration command to create a database migration

**Comment by driesvints** [comment]
Laravel 9 uses anonymous migrations by default so the class name isn't needed anymore. Feel free to PR the upgrade guide 👍
