### ISSUE TITLE
db:wipe multiple databaes

### ISSUE THREAD

**Issue by jhjm32087** [laravel/framework#42047]
- Laravel Version: 8.83
- PHP Version: 7.4.29
- Database Driver & Version:
- MySQL 5.7

### Description:
I have two databases/schemas in MySQL, during Unit Testing with the RefreshDatabase trait. On the second execution all tests will fail.  Under the hood, the migrate:reset and then db:wipe commands are called. It will only affect the default database(schema) and not the rest of them. 

I would expect the db:wipe command to wipe out all databases in unit testing, not just the default.

* schema1
* schema2

### Steps To Reproduce:
1)  Create a unit test that uses the RefreshDatabase Trait
2) Create a migration with two schemas
3) Run the tests

**Comment by derekmd** [comment]
Do you mean to use trait `DatabaseMigrations`? Trait `RefreshDatabase` only runs migrations once and then wraps each test case in a transaction that rolls back updates.

https://laravel.com/docs/9.x/database-testing#resetting-the-database-after-each-test

![transaction](https://user-images.githubusercontent.com/823566/164360797-f00d2ad8-ce27-403d-bc06-f3542b9a9fe4.png)

The `DatabaseMigrations` trait drops and recreates the database for each case. It allows method `migrateFreshUsing()` to be defined for customizing arguments passed to Artisan command `migrate:fresh`. https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Testing/Traits/CanConfigureMigrationCommands.php#L12 The `runDatabaseMigrations()` method can be overridden to `migrate:fresh` many database connections.

**Comment by driesvints** [comment]
`db:wipe` only targets the default connection without a `--database` flag.

**Comment by driesvints** [comment]
Thanks @derekmd

**Comment by driesvints** [comment]
Yes, like I said, this is expected. If you want to change this behavior, please attempt a PR.
