### ISSUE TITLE
Fix bug in BelongsToMany where non-related rows are returned

### ISSUE THREAD

**Issue by marcovo** [laravel/framework#42049]
- Laravel Version: 9.8.1
- PHP Version: *
- Database Driver & Version: *

### Description:
After a pull request of mine was closed I wrote an explanation on the issue at hand, regarding three BelongsToMany methods that, in my opinion, can be rather confusing when you don't know the details/pitfalls hidden in them. The full PR can be found in #41881 . Now I come to understand that tickets that have been closed may never be looked at again, so I hope to find some opinions here. (Is this the place?)

Please do read up on the PR. In short, I think the behaviour of `firstOrNew()`, `firstOrCreate()` and `updateOrCreate()` in laravel 8.* was great and in 9.* can be confusing (up to the point that the difference in behaviour can lead to hard-to-find bugs and probably even security-related issues). I do understand there might have been a reason for the change, but I suspect the 'right' fix might have to be slightly different than the current implementation, as outlined in my [last message](https://github.com/laravel/framework/pull/41881#issuecomment-1093033906).

Also, I'm still interested in what the exact reasons/examples were for the change in laravel 9.*, since no tests were added for it.

Any thoughts?

**Comment by driesvints** [comment]
Please re-submit the PR with the new explanation, thanks.
