### ISSUE TITLE
fresh laravel install ignore env configuration

### ISSUE THREAD

**Issue by nimiboid** [laravel/framework#42042]
- Laravel Version: 9.2
- PHP Version: 8.15
- Database Driver & Version: mysql 8.0.27

### Description:
A fresh install of latest Laravel on MBP M1 ignores .env file:
- neither writes app-key
- nor uses provided db configurations

### Steps To Reproduce:
MacOS Monterey 12.3

```
ms git:(main) ✗ brew -v 
Homebrew 3.4.7
Homebrew/homebrew-core (git revision fa272dd75c2; last commit 2022-04-19)
Homebrew/homebrew-cask (git revision 353787487f; last commit 2022-04-19)
```

```
ms git:(main) ✗ brew info php
php: stable 8.1.5 (bottled), HEAD
```

```
ms git:(main) ✗ valet --version
Laravel Valet 3.1.6
```

Steps to reproduce
```
ws ✗ composer create-project laravel/laravel ms
ws ✗ cd ms
ms ✗ git init
ms git:(main) ✗ cat .env | grep APP_KEY= --> see APP_KEY is empty
ms git:(main) ✗ php artisan key:generate
Application key set successfully.
ms git:(main) ✗ cat .env | grep APP_KEY= --> see APP_KEY is continues to be empty
```

Connecting to a DB provided by DBngin (as suggested by the documentation) doesn't work as well as env variables are not loaded from .env as expected. 

Am I missing something?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nimiboid** [comment]
@driesvints  Sure, sorry.

FYI I've git it to work - upgrade laravel from 9.15 to ^9.8 did the trick and now it works. Indeed composer create-project installs 9.1.5.

I've just repeated all the steps I did today to reproduce the issue and try to narrow it down but I can no longer reproduce it. 🤪

Looks like leaving the MBP sleep for couple of hours did the trick . Please delete the issue to remove noise from the repo.

**Comment by adduc** [comment]
I was able to replicate. In my case, running Laravel in a docker container with a different path from where `composer create-project laravel/laravel` was performed caused cache files to be created with incorrect paths. Once `artisan optimize:clear` was run in the docker container, .env was read correctly.
