### ISSUE TITLE
Laravel UI Registration Issue

### ISSUE THREAD

**Issue by imran300** [laravel/framework#42056]
- Laravel Version: 9.0
- PHP Version: 8.1
- Database Driver & Version:

### Description:
Hello,
I am usng Laravel UI for Auth. I have customized Registration process. The problem i am facing is user is not redirected to concern route instead it redirects back to login if in case an exception is thrown. Here is my Code. Please review what m i doing wrong.

/**
     * Create a new user instance after a valid registration.
     *
     * @param array $data
     * @return \Illuminate\Http\RedirectResponse
     */
   ```
 protected function create(array $data)
    {

        try {
            //            \DB::transaction(function () use ($data) {
            $timezone = Timezone::where('country_id', $data['location_name'])->first();
            //dd($timezone);
            $company_id = Company::create([
                'company_name' => $data['company_name'],
                'country_id' => $timezone->country_id,
                'timezone_id' => $timezone->id
            ])->id;

            $role = Role::where('role_name', config('app.user.default_role'))->firstOr(function ($company_id) {
                return Role::create([
                    'role_name' => config('app.user.default_role'),
                    'company_id' => $company_id
                ]);
            });
            $verification_code = Str::random(30);
            $verified = 0;
            //                }

            $trial_days = 14;
            $trial_ends_at = null;
            
            // if trial days is not zero we will set trial_ends_at to ending date


            if (intval($trial_days) > 0) {
                $trial_ends_at = now()->addDays(14);
            }

            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make($data['password']),
                'company_id' => $company_id,
                'trial_ends_at' => now()->addDays(15),
//                'trial_ends_at' => $trial_ends_at,
                'role_id' => $role->id,
                'verification_code' => $verification_code,
                'verified' => $verified
            ]);

            return $user;
        } catch (\Throwable $e) {
            DB::rollback();
            \Log::error($e->getCode() . ' ' .$e->getLine().' '. $e->getMessage());
            return redirect('register')->with('error',$e->getMessage());
        }
//                return redirect(RouteServiceProvider::Error);

    }
```
Kindly help please...
Thank You.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
