### ISSUE TITLE
Artisan command calls during tests do not run app()->terminate like they would when run normally

### ISSUE THREAD

**Issue by Orrison** [laravel/framework#42061]
- Laravel Version: 9.9.0
- PHP Version: 8.0.16
- Database Driver & Version: MySQL 5.7

### Description:

When run in tests via `$this->artisan('some:command');` or `Artisan::call('some:command');` commands do not run `terminate` like it would when run normally. This makes it challenging to test that the proper things were run with `terminate` when running a console command.

### Steps To Reproduce:

1. Add a closure to `terminating` in `AppServiceProvider@boot`
```php
$this->app->terminating(function () {
    Log::debug('Application is terminating');
});
```
2. Run a command normally via CLI or scheduler
3. You should see the log
4. Create a test that calls the command
```php
$this->artisan('some:command');
```
5. Run the test
6. You should not see the log as `terminate` is not properly run after the command is executed.

https://github.com/Orrison/laravel-console-test-terminate

**Comment by driesvints** [comment]
That's because it's not actually run. It's a mocked pending command that's used for testing. There's no way atm to simulate this.
