### ISSUE TITLE
queue:listen not passing on --force flag

### ISSUE THREAD

**Issue by fjahn** [laravel/framework#42063]
- Laravel Version: 9.9.0
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:

The `queue:listen` command does not pass down the `--force` flag to its underlying `queue:work` command. I believe the flag should be added at around [\Illuminate\Queue\Listener:153](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Queue/Listener.php#L153).

### Steps To Reproduce:

- Enable maintenance mode
- Dispatch a job to a queue
- Run queue:listen
- _The job will not be processed_
- Stop queue:listen
- Disable maintenance mode
- Run queue:listen
- _The job will be processed now_

**Comment by driesvints** [comment]
Yeah, I think that's valid. Can you send in a PR?
