### ISSUE TITLE
route resource bug

### ISSUE THREAD

**Issue by MrPoper** [laravel/framework#42064]
- Laravel Version: 9.8.1
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:
Bug when use resource route in group with prefix and name , 
```php
Route::group(['middleware'=>'auth','prefix'=>'roles','as'=>'roles.'],function(){
      Route::resource(`/',RoleController::class);
})
```
### OUTPUT :
```powershell
  GET|HEAD        roles/{} ................................................................................................................................................................................................ roles.show › RoleController@show  
  PUT|PATCH       roles/{} ............................................................................................................................................................................................ roles.update › RoleController@update  
  DELETE          roles/{} .......................................................................................................................................................................................... roles.destroy › RoleController@destroy  
  GET|HEAD        roles/{}/edit ........................................................................................................................................................................................... roles.edit › RoleController@edit 
```

**without a parameters `{}`  because the name of route it `/` and its in group route resource he don't take name from group prefix
and i fixed by : ** 
```php
Route::group(['middleware'=>'auth'],function(){
   Route::resource('/roles',RoleController::class);
   Route::group(['prefix'=>'roles','as'=>'roles.'],function(){
        Route::get('r1/{id?}',[RoleController::class,'g1'])->name('r1');
        Route::get('r2/{id?}',[RoleController::class,'g2'])->name('r2');
        Route::post('fd',[RoleController::class,'fd'])->name('fd');
    });

   })
```

### Steps To Reproduce:
> * Route group
> * Route::resource(`'/'`,RoleController::class);

**Comment by jangaraev** [comment]
Discovered the same unexpected behavior.

- Laravel Version: 8.83.6
- PHP Version: 8.0.8

### Description:

In case of empty resource route name in a grouped (prefixed) route Laravel uses a plain action name => which is pretty unexpected thing.

In my case I expect the following route name `campaign.store` instead of just `store`.

**Reproduce steps**: refer to the roures definition below
**Expected result**: for store action Laravel assigns the route name `campaign.store`
**Actual result**: Laravel assigns a route name `store` (which in my case rewritten the previously declared one)

### Routes definition:

```
Route::get('store/{location}', 'StoreController@show')->name('store');
...
Route::group(['prefix' => 'campaign', 'namespace' => 'Campaign'], function () {
    Route::resource('', 'InsertionController')->only(['index', 'store'])->names(['index' => 'campaign']);
    // the 'store' action of the route above gets "store" route name

    ....
});
```

**Comment by jangaraev** [comment]
Can my expectation be wrong and the behaviour is pretty fine? So we just need to adjust our routes declaration.

Btw, for now I ended up with the following:

```
    Route::resource('', 'InsertionController')->only(['index', 'store'])->names(['index' => 'campaign', 'store' => 'campaign.store']);
```

**Comment by jangaraev** [comment]
I inspected the source code of ResourceRegistrar & Route classes and saw that in the register method of ResourceRegistrar we have an access to the upper route groups, so it's possible to build up a proper route name there using prefix and/or name of a higher-level group.

Should I prepare a PR for that?

**Comment by driesvints** [comment]
A resource always needs a value, not a `/` or prefix`.
