### ISSUE TITLE
RedisTaggedCache::put standard_ref Set overflow

### ISSUE THREAD

**Issue by wenjy** [laravel/framework#42071]
- Laravel Version: 8.83.8
- PHP Version: 7.4.22
- Database Driver & Version:
redis 5
### Description:

https://github.com/tymondesigns/jwt-auth/issues/2179

### Steps To Reproduce:
```
for ($i = 0; $i < 10; $i++) {
    Cache::tags('test')->put('test_' . Str::random(), time(), 60);
}
```

**Comment by wenjy** [comment]
tag:test:key [6260f211bf58c364964784]

after ttl
Set 6260f211bf58c364964784:standard_ref Members not deleted

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
