### ISSUE TITLE
`Crypt` facade throws errors when mocking

### ISSUE THREAD

**Issue by PHLAK** [laravel/framework#42085]
- Laravel Version: `9.8.1`
- PHP Version: `8.1.5`
- Database Driver & Version: N/A

### Description:

The `Crypt` facade throws errors when mocking (i.e. `Crypt::shouldReceive()`)

### Steps To Reproduce:

In a _brand new_ Laravel application add the following route and test case and run the tests.

```php
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return response(Crypt::encrypt('laravel'));
});
```

```php
use Illuminate\Support\Facades\Crypt;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_application_returns_a_successful_response()
    {
        Crypt::shouldReceive('encrypt')->with('laravel')->once()->andReturn('something');

        $response = $this->getJson('/');

        $this->assertEquals('something', $response->getContent());
    }
}
```

```
$ artisan test tests/Feature/ExampleTest.php

   FAIL  Tests\Feature\ExampleTest
  ⨯ the application returns a successful response

  ---

  • Tests\Feature\ExampleTest > the application returns a successful response
  Failed asserting that two strings are equal.

  at tests/Feature/ExampleTest.php:22
     18▕         Crypt::shouldReceive('encrypt')->with('laravel')->once()->andReturn('something');
     19▕ 
     20▕         $response = $this->getJson('/');
     21▕ 
  ➜  22▕         $this->assertEquals('something', $response->getContent());
     23▕     }
     24▕ }
     25▕ 
  --- Expected
  +++ Actual
  @@ @@
  -'something'
  +'{\n
  +    "message": "Received Mockery_0_Illuminate_Encryption_Encrypter::getKey(), but no expectations were specified",\n
  +    "exception": "Mockery\\Exception\\BadMethodCallException",\n
  +    "file": "/tmp/laratest/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code",\n
  +    "line": 931,\n
  +    "trace": [\n
  +        [OMITTED FOR BREVITY, FULL OUTPUT BELOW]
  +    ]\n
  +}'

  Tests:  1 failed
  Time:   0.25s
```

<details>
<summary>Full response trace</summary>

<pre>
'{\n
    "message": "Received Mockery_0_Illuminate_Encryption_Encrypter::getKey(), but no expectations were specified",\n
    "exception": "Mockery\\Exception\\BadMethodCallException",\n
    "file": "/tmp/laratest/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code",\n
    "line": 931,\n
    "trace": [\n
        {\n
            "file": "/tmp/laratest/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code",\n
            "line": 1064,\n
            "function": "_mockery_handleMethodCall",\n
            "class": "Mockery_0_Illuminate_Encryption_Encrypter",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",\n
            "line": 180,\n
            "function": "getKey",\n
            "class": "Mockery_0_Illuminate_Encryption_Encrypter",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",\n
            "line": 67,\n
            "function": "encrypt",\n
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 116,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Routing/Router.php",\n
            "line": 726,\n
            "function": "then",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Routing/Router.php",\n
            "line": 703,\n
            "function": "runRouteWithinStack",\n
            "class": "Illuminate\\Routing\\Router",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Routing/Router.php",\n
            "line": 667,\n
            "function": "runRoute",\n
            "class": "Illuminate\\Routing\\Router",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Routing/Router.php",\n
            "line": 656,\n
            "function": "dispatchToRoute",\n
            "class": "Illuminate\\Routing\\Router",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",\n
            "line": 167,\n
            "function": "dispatch",\n
            "class": "Illuminate\\Routing\\Router",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 141,\n
            "function": "Illuminate\\Foundation\\Http\\{closure}",\n
            "class": "Illuminate\\Foundation\\Http\\Kernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",\n
            "line": 21,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php",\n
            "line": 31,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",\n
            "line": 21,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",\n
            "line": 40,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",\n
            "line": 27,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php",\n
            "line": 86,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php",\n
            "line": 49,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Http\\Middleware\\HandleCors",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php",\n
            "line": 39,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 180,\n
            "function": "handle",\n
            "class": "Illuminate\\Http\\Middleware\\TrustProxies",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",\n
            "line": 116,\n
            "function": "Illuminate\\Pipeline\\{closure}",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",\n
            "line": 142,\n
            "function": "then",\n
            "class": "Illuminate\\Pipeline\\Pipeline",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",\n
            "line": 111,\n
            "function": "sendRequestThroughRouter",\n
            "class": "Illuminate\\Foundation\\Http\\Kernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php",\n
            "line": 526,\n
            "function": "handle",\n
            "class": "Illuminate\\Foundation\\Http\\Kernel",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php",\n
            "line": 492,\n
            "function": "call",\n
            "class": "Illuminate\\Foundation\\Testing\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php",\n
            "line": 305,\n
            "function": "json",\n
            "class": "Illuminate\\Foundation\\Testing\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/tests/Feature/ExampleTest.php",\n
            "line": 20,\n
            "function": "getJson",\n
            "class": "Illuminate\\Foundation\\Testing\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/Framework/TestCase.php",\n
            "line": 1545,\n
            "function": "test_the_application_returns_a_successful_response",\n
            "class": "Tests\\Feature\\ExampleTest",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/Framework/TestCase.php",\n
            "line": 1151,\n
            "function": "runTest",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/Framework/TestResult.php",\n
            "line": 726,\n
            "function": "runBare",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/Framework/TestCase.php",\n
            "line": 903,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestResult",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/Framework/TestSuite.php",\n
            "line": 677,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestCase",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/TextUI/TestRunner.php",\n
            "line": 673,\n
            "function": "run",\n
            "class": "PHPUnit\\Framework\\TestSuite",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/TextUI/Command.php",\n
            "line": 143,\n
            "function": "run",\n
            "class": "PHPUnit\\TextUI\\TestRunner",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/src/TextUI/Command.php",\n
            "line": 96,\n
            "function": "run",\n
            "class": "PHPUnit\\TextUI\\Command",\n
            "type": "->"\n
        },\n
        {\n
            "file": "/tmp/laratest/vendor/phpunit/phpunit/phpunit",\n
            "line": 98,\n
            "function": "main",\n
            "class": "PHPUnit\\TextUI\\Command",\n
            "type": "::"\n
        }\n
    ]\n
}'
</pre>
</details>

### Additional Information

The same applies when using the `Crypt::encryptString()` function.

I also tried injecting/mocking the `Encrypter` contract directly (with and without a `getKey` expectation) and got the same error.

```php
use Illuminate\Contracts\Encryption\Encrypter;
use Illuminate\Support\Facades\Route;

Route::get('/', function (Encrypter $encrypter) {
    return response($encrypter->encrypt('laravel'));
});
```

```php
use Illuminate\Contracts\Encryption\Encrypter;
use Mockery\MockInterface;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_application_returns_a_successful_response()
    {
        $this->mock(Encrypter::class, function(MockInterface $mock): void {
            $mock->shouldReceive('getKey')->andReturn('key'); // Tried with and without this
            $mock->shouldReceive('encrypt')->with('laravel')->once()->andReturn('something');
        });

        $response = $this->getJson('/');

        $this->assertEquals('something', $response->getContent());
    }
}
```

**Comment by driesvints** [comment]
So, I'll try to explain what happens here. When mocking facades, you're not just swapping out *just* the facades but also the underlying service on the container. This means that all calls to the underlying service needs to be mocked. If you'd disable the `EncryptCookies` middleware your test will pass. Similarly, if you attempted to mock the `Session` facade, the `StartSession` middleware would fail. This is how the mechanism works under the hood.

Mocking the Crypt facade on a full app lifecycle will be very hard to do with the `EncryptCookies` middleware. What I suggest you do is that you try to isolate the piece of code you want to mock in a separate job or service class and then mock that part.

**Comment by taylorotwell** [comment]
You could also not mock encryption at all and just decrypt the encrypted value to make sure it matches the value you expected after your test has run.

**Comment by PHLAK** [comment]
Thanks. I was able to extract the code to an "action" class and tested it separately (outside of the context of a request).
