### ISSUE TITLE
Builder does not support all postgres operators

### ISSUE THREAD

**Issue by markuskooche** [laravel/framework#42101]
It is not possible to use the ``` IS ``` or ``` IS NOT ``` operators for example in the whereRelation() function.

The problem is that the``` Illuminate\Database\Query\Builder ``` does not support these operators.
It would work if these operators were included in this array.

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Query/Builder.php#L199-L206

And the whereRelation() calls the where() function inside the builder, which changes unsupported operators to ``` = ```. 

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Query/Builder.php#L739-L741

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
