### ISSUE TITLE
if post method send nothing. gets a error:Call to a member function runningInConsole() on null

### ISSUE THREAD

**Issue by tyonly** [laravel/framework#42113]
- Laravel Version: 8.83.9
- PHP Version: 7.4.28
- Database Driver & Version: 

### Description:
when change a get method url to post method url. then throw a error : Call to a member function runningInConsole() on null
example:
    url: http://www.demo.com/test   ===> this url is in except_list of VerifyCsrfToken.php

first get the url: use GET method ,it's normal.
then get the url: use POST method. it's display a error: Call to a member function runningInConsole() on null

vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:107

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tyonly** [comment]
OK,i will report the issue on [Laracasts Forums](https://laracasts.com/discuss)

**Comment by tyonly** [comment]
i have comment the code in vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:107 ,then i get's a normal at POST method
