### ISSUE TITLE
Weird problem with loading values from config helper

### ISSUE THREAD

**Issue by negoziator** [laravel/framework#42127]
- Laravel Version: 9.9.0
- PHP Version: 8.1.4
- Database Driver & Version: mysql 8.0

### Description:
So i have no idea about how to describe this other than:

After upgrade to Laravel **9.9.0** from **9.8.1** we have started to see this really weird behavior, where the **config(...)**-helper suddenly is returning **null** - but only _sometimes._

We discovered it because our automated tests was complaining about a **null** value.

Turns out that in production the same behavior ocours ( But it really seems to only be sometime 🤔  )

![image](https://user-images.githubusercontent.com/2228675/165139421-a09ab966-c31d-4e98-a375-5858935844b8.png)

![image](https://user-images.githubusercontent.com/2228675/165139502-d06e5c36-12b8-4d76-ac18-deeaf0c81528.png)

### Steps To Reproduce:

I'm really sorry - but i don't know how to reproduce it other than installing Laravel 9.9.0

I tried to read through all changed files from **9.8.1** -> **9.9.0** - but i could'nt see anything that would stand out to trigger this bug.

I'm wondering if it could be a caching problem when using **php artisan cache:clear**

**Let me know - if anyone else is experiencing this - else i'll get back to the drawing board and look deeper into it 😄**

**Comment by driesvints** [comment]
Or re-cached it with `php artisan config:cache`?

**Comment by negoziator** [comment]
I just tried to isolate the update to be **only** the laravel upgrade, just to be 100% sure that this is the **only** change.

Behavior starts immediately when doing update from **9.8.1** to **9.9.0**

Tried both:

`php artisan config:clear`
`php artisan config:cache`

There's an important context to know.

All our configs are not present in the `/config`  folder.

We are running: `artisan vendor:publish --tag=x-service --force` on build time.

I think i narrowed it down to be somewhere here the problem ocours.

```php
    public function register()
    {
        $this->app->bind(QuickpayService::class, function ($app) {
            $client = Http::baseUrl(config('quickpay.api_base_url'))
                ->acceptJson()
                ->withHeaders([
                    'Accept-Version' => 'v10',
                    'Authorization' => 'Basic ' . base64_encode(':' . config('quickpay.api_key')),
                ]);

            return new QuickpayService(new QuickPayClient($client));
        });
    }

    public function boot()
    {
        $this->publishes([
            __DIR__ . '/../config/quickpay.php' => config_path('quickpay.php'),
        ], 'x-service');
    }
```

As you can see the `Http::baseUrl(config(...))` uses the `config(...)` helper to instantiate the PendingRequest class.

I can recreate the problem in this particular case when i call: `artisan vendor:publish --tag=x-service --force`

```bash
  Illuminate\Http\Client\PendingRequest::baseUrl(): Argument #1 ($url) must be of type string, null given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Client/Factory.php on line 394

  at vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:216
    212▕      *
    213▕      * @param  string  $url
    214▕      * @return $this
    215▕      */
  ➜ 216▕     public function baseUrl(string $url)
    217▕     {
    218▕         $this->baseUrl = $url;
    219▕ 
    220▕         return $this;

      +2 vendor frames 
  3   app/Integrations/Billing/Providers/QuickPayServiceProvider.php:23
```

So it seems like it tries to call the `Http::baseUrl` before it calls the `->publishes()`

**Note:** We can as a workaround just move all our configs to `/config` instead of having them in separate folders. I have already tried just moving the `quickpay.php` to `/config` - then it works just fine ( of course 😄  )

**I'll keep digging.**

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by negoziator** [comment]
Hey @driesvints 

I'll try and do that 👍🏼

**Comment by driesvints** [comment]
Yeah if we can recreate it in a fresh Laravel app it'd be helpful to debug.

**Comment by negoziator** [comment]
@driesvints You can close this!! Found the bug! Still don't know why the difference between **9.8.1 vs 9.9.0** though.

**BUT** i was actually a rooky mistake! 

So found out that a collegue had made a command class and tried to dependency inject it in the commands **constructor** 
- which is an absolutely **no-go** - because that means that it will be instantiated on basically ALL boots of the framework.

**DONT DO THIS 👎🏼**
![image](https://user-images.githubusercontent.com/2228675/165297920-e15348ca-bbf3-44c1-83d0-c3962d332249.png)

**DO THIS 👍🏼**
![image](https://user-images.githubusercontent.com/2228675/165297833-c777d183-b250-4d66-9ed3-8a5b48ba6579.png)


**Sorry for wasting your time 😓 **
