### ISSUE TITLE
Passing null to can method in Illuminate/Foundation/Auth/Access/Authorizable returns true

### ISSUE THREAD

**Issue by DavidJapan** [laravel/framework#42139]
- Laravel Version: 8.7.5
- PHP Version: 7.4.28
- Database Driver & Version: pgsql, Postgresql 12.9

### Description:
In my application I don't pass literal strings to the can method of an authenticated user. Instead, I generate permission strings from constants in a config file. Because of my own mistake, I ended up passing `null `to the `can()` method of an authenticated user. This unexpectedly gave the user permission to do something they didn't have permission to do. I know my code shouldn't pass `null `to the `can `method, but unexpected `null `values seem like quite a likely runtime problem to me.

### Steps To Reproduce:
Get an instance of the current user:
`$user = Auth::user();`
then pass null to the can method:
`$returnVal = $user->can(null);`

The `$returnVal` is unexpectedly true. This seems risky to me. Shouldn't it return `false `or even throw an exception?

**Comment by guushuizen** [comment]
To bring a bit more context to the issue you're describing, what were the consequences in your application?

Me thinking bluntly - I'd say, an user is always able to nothing (`null`). Therefore returning `true` seems in place.

**Comment by DavidJapan** [comment]
One part of the application is the navigation menu in a sidebar on the left. The user should only see menu items that they have permission to see. Where I mistakenly passed null to the can method, the user was allowed to see a menu item that they shouldn't and open the related page. 

My workaround is to test for null and if null is detected, pass false to the can method, which returns false - that's what I want. I think if a user can do nothing (i.e. null), they should not be given permission. Returning true is counterintuitive for me.

**Comment by driesvints** [comment]
Laravel doesn't uses strict types in method signatures to enforce type safety. This parameter is marked as `iterable|string` only and we indeed consider this to be a userland thing to ensure.

I do have to agree that we could maybe throw an exception to warn people about improper usage. But unsure if that should be done in the current stable release (breaking change). You may attempt a PR to either 9.x or master if you like to see what Taylor says. Thanks
