### ISSUE TITLE
Bus::chain() cannot accept an empty array

### ISSUE THREAD

**Issue by emargareten** [laravel/framework#42145]
- Laravel Version: 9.9.0
- PHP Version: 8.1.0
- Database Driver & Version: N/A

### Description:
`Bus::chain()` cannot accept an empty array, this is because PendingDispatcher is using the `$firstJob` in the chain which is `null` therefore an exception is thrown `PHP Error:  Call to a member function chain() on null`.

### Steps To Reproduce:

Run in tinker:
```
Bus::chain([])->dispatch();
```

**Comment by driesvints** [comment]
I'm not sure I see the bug here? Using an empty array there indeed isn't allowed.
