### ISSUE TITLE
[v9.10.0] Run test on api route will result in `Target class [api] does not exist.`

### ISSUE THREAD

**Issue by kocoten1992** [laravel/framework#42156]
- Laravel Version: v9.10.0 (on github lastest is v9.9.0 but on packagist there is a v9.10.0 version https://packagist.org/packages/laravel/framework#v9.10.0)
- PHP Version: 8.1.5
- Database Driver & Version: irrelevant

### Description:
running test on api route will result in `Target class [api] does not exist.`

### Steps To Reproduce:
Running these code:
```php
# this is in tests/Feature/
$this->post("/api/randomtest");
```

Will result in:
```
Target class [api] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:877
    873▕ 
    874▕         try {
    875▕             $reflector = new ReflectionClass($concrete);
    876▕         } catch (ReflectionException $e) {
  ➜ 877▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    878▕         }
    879▕ 
    880▕         // If the type is not instantiable, the developer is attempting to resolve
    881▕         // an abstract type such as an Interface or Abstract Class and there is
```

**Comment by driesvints** [comment]
Was this after you updated? In which Laravel version did this work for you?

**Comment by kocoten1992** [comment]
yes, it was after update, v9.9.0 work for me

**Comment by driesvints** [comment]
Can you clear route cache with `php artisan route:clear` or try re-caching with `php artisan route:cache`?

**Comment by kocoten1992** [comment]
I've try `composer dump` and `php artisan route:clear` (`php artisan optimize:clear` too), does not work.

I'll try to reproduce with a newly install laravel and post a link here.

**Comment by kocoten1992** [comment]
@driesvints ho, most thing is broken on v9.10.0, this don't even work

```
composer create-project laravel/laravel example-app
cd example-app
php artisan make:controller ApiController
```
```

   InvalidArgumentException 

  Attribute [route] does not exist.

  at vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php:107
    103▕      */
    104▕     public function attribute($key, $value)
    105▕     {
    106▕         if (! in_array($key, $this->allowedAttributes)) {
  ➜ 107▕             throw new InvalidArgumentException("Attribute [{$key}] does not exist.");
    108▕         }
    109▕ 
    110▕         if ($key === 'middleware') {
    111▕             foreach ($value as $index => $middleware) {

      +2 vendor frames 
  3   routes/api.php:21
      Illuminate\Support\Facades\Facade::__callStatic()

      +4 vendor frames 
  8   app/Providers/RouteServiceProvider.php:34
      Illuminate\Routing\RouteRegistrar::group()
```

**Comment by kocoten1992** [comment]
Hello, I'm unable to reproduce on newly installed laravel app, but problem still there in an old app, I think I'll close this issue and start debugging on the old app and create a new issue if I find root cause (if you disagree can open this again). Thank you very much!
