### ISSUE TITLE
Change in middlewareGroup function behaviour introduces a breaking change in v9.10.0 

### ISSUE THREAD

**Issue by toyi** [laravel/framework#42159]
- Laravel Version: 9.10.0
- PHP Version: 8.1.3
- Database Driver & Version: -

### Description:

Since the `v9.10.0`, I encounter many issues on a large project. I can only say "many issues" for now, because it's "just" failling tests here and there that doesn't seem related to each other, even if everything works fine when I roll back to `v9.9.0`. 

I'm still in the process of digging the problem and to figure out why and when it happens.

However, I've determined this commit  https://github.com/laravel/framework/commit/05365f8186044af51fc55fb1e2b5b97caaac59e8 (part of `v9.10.0`) is the cause of these problems. If I checkout on it, it still doesn't work, the moment I manually revert the changes in the `middlewareGroup` public function, it works. With this reverted change, `v9.10.0` works fine too.

In the previous version, prior to https://github.com/laravel/framework/commit/05365f8186044af51fc55fb1e2b5b97caaac59e8, the entire middleware group was replaced by a new set of middlewares. In the new version, after https://github.com/laravel/framework/commit/05365f8186044af51fc55fb1e2b5b97caaac59e8, only the missing ones are added. At least it's what I understand for now.

Even if it's a small change, it's a breaking change that should be reverted.

What do you think?

### Steps To Reproduce:

Not yet but the change in behaviour is clear enough to be discussed.

**Comment by kocoten1992** [comment]
can confirm this, revert https://github.com/laravel/framework/commit/05365f8186044af51fc55fb1e2b5b97caaac59e8 fix my problem too (https://github.com/laravel/framework/issues/42156)

**Comment by marvin-wtt** [comment]
This commit was added with #42004

**Comment by suleymanozev** [comment]
I am also having the same problem. I was creating middleware group with empty array to tag routes. Framework cannot find middleware group when I run it with this pr(#42004)

**Comment by rodrigopedra** [comment]
Behavior of the `middlewareGroup` method changed after PR #42004 as it no longer defines a middleware group when the group is an empty array.

I sent PR #42161 with a proposed fix.

**Comment by driesvints** [comment]
Thanks all. We'll try to get this fixed asap.

**Comment by driesvints** [comment]
We got this reverted and will cut a release shortly. Thanks all.
