### ISSUE TITLE
Global scopes cannot be removed from inside a logical group

### ISSUE THREAD

**Issue by danharrin** [laravel/framework#42172]
- Laravel Version: 9.10.0
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.28

### Description:

Users of my package may define their own "filters", which are closures that alter an Eloquent query. Filters may be applied to the query in any combination.

To ensure that filters with `orWhere()` clauses do not conflict with one another, each filter is assigned a [logical `where()` group](https://laravel.com/docs/9.x/queries#logical-grouping).

However, when building something like an `onlyTrashed()` filter, which requires the `SoftDeletingScope` to be removed, the scope remains. This is a symptom of removing the scope from within the logical group.

Is this an Eloquent bug, or expected behaviour? I am more than happy to PR a fix if you are happy.

### Steps To Reproduce:

Without grouping, removing a global scope works:

```php
User::query()
    ->withoutGlobalScope(SoftDeletingScope::class)
    ->onlyTrashed()
    ->toSql();
```

```sql
select * from `users` where `users`.`deleted_at` is not null ✅
```

With grouping...

```php
User::query()
    ...
    ->where(function (Builder $query): Builder {
        return $query
            ->withoutGlobalScope(SoftDeletingScope::class)
            ->onlyTrashed();
    })
    ...
    ->toSql();
```

```sql
select * from `users` where (`users`.`deleted_at` is not null) and `users`.`deleted_at` is null ❌
```

**Comment by driesvints** [comment]
Yes this is expected since you're only scoping the part within the closure. If you want to get rid of the trait on the full query you'll have to target the base query:

```php
User::query()
    ->withoutGlobalScope(SoftDeletingScope::class)
    ->where(function (Builder $query): Builder {
        return $query
            ->onlyTrashed();
    })
    ->toSql();
```
