### ISSUE TITLE
Faking dates with Carbon breaks the session persistence

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#42183]
### Versions

Laravel Version: 8.83.9
PHP Version: 8.0.11
Database Driver & Version: MariaDB 10.5.8

### Description:

Adding something like this anywhere in a middleware or even the AppServiceProvider breaks session:

``` php
Carbon::setTestNow($now = '2022-04-20 11:39:45');
```

### Steps To Reproduce:

1) Create a middleware 

``` php
<?php

namespace App\Http\Middleware;

use Closure;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Illuminate\Http\Request;

class FakeNow
{
    public function handle(Request $request, Closure $next)
    {
        if (app()->environment('local')) {
            Carbon::setTestNow($now = '2022-04-20 11:39:45');
            CarbonImmutable::setTestNow($now);
        }

        return $next($request);
    }
}
```

2) Add it first in the web stack

3) Refresh a page with a csrf_token()

Token is refreshed every time.

**Comment by driesvints** [comment]
Hey @antonioribeiro. This `setTestNow` call is only intended to be used in tests and not in app code. We do not recommend to use it outside testing classes.
