### ISSUE TITLE
Deprecations log missing the trace

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#42189]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5

### Description:
Deprecation logs look like this, making it impossible to debug in some cases:
```log
pipeline.WARNING: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 944  
pipeline.WARNING: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 944  
pipeline.WARNING: mb_strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 787 
```

It's missing the stack trace, dissimilar to the rest of the exceptions & PHP errors.

### Steps To Reproduce:

1. Clean install Laravel
2. Configure the deprecations logs [as per documentation](https://laravel.com/docs/9.x/logging#logging-deprecation-warnings) by setting an .env variable: `LOG_DEPRECATIONS_CHANNEL=stack`
3. Trigger any PHP deprecation: `str_replace(null, '', '')`
4. See a deprecation log without any stack trace in the log, besides the specific file/line where it occurred: `pipeline.WARNING: str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in /app/some/file.php on line 123`

**Comment by marvin-wtt** [comment]
@driesvints I think what OP means is that it's hard to debug when calling the substring method of the Laravel Support Str class with null as the trace will point to the support class rather than the caller

**Comment by driesvints** [comment]
Hmm yes I see the issue now. I agree that that can be improved but it's rather an enhancement than an issue. We'd welcome Pr's for this. Here's where the call gets made:

https://github.com/laravel/framework/blob/ab1506091b9f166b312b3990d07b2e21d971f2e6/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L105-L107

**Comment by oprypkhantc** [comment]
@driesvints I'll do that now. Thanks
