### ISSUE TITLE
Pagination localization causing Array to String error

### ISSUE THREAD

**Issue by eirworks** [laravel/framework#42196]
- Laravel Version: 9.8.*
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
There are some localization issue inside `laravel/framework/src/Illuminate/Pagination/resources/views/tailwind.blade.php`, for example in line 38, there is this `__('results')` that will throw Array to string conversion error because I have file named `results.php` in lang folder. Honestly, I am not sure which repository (laravel/framework or laravel/laravel) I should report this and this is my first time reporting bug.

### Steps To Reproduce:
1. create `lang/results.php` with any localization content
2. create a controller to paginate some model
3. display pagination in the view file, for example `$users->links()`. The error page will highlight exactly that code.

**Comment by driesvints** [comment]
Hi @eirworks. You reported this to the right repo. Unfortunately, having files names the same as translation keys is not supported right now. Please see https://laravel.com/docs/9.x/localization#using-translation-strings-as-keys

![Uploading Screenshot 2022-05-02 at 10.20.02.png…]()
