### ISSUE TITLE
[9.10.1] Fix sortMiddleware not working

### ISSUE THREAD

**Issue by PooX** [laravel/framework#42201]
- Laravel Version: 9.10.1
- PHP Version: 8.0.13
- Database Driver & Version: 

### Description:
After update to 9.10 version, my application was fully broken. Error about Router:sortMiddleware has showed.
```
[2022-04-30 21:37:26] local.ERROR: Illuminate\Routing\Router::sortMiddleware(): Argument #1 ($middlewares) must be of type Illuminate\Support\Collection, Hyperf\Utils\Collection given, called in C:\laragon\www\pt9\vendor\laravel\framework\src\Illuminate\Routing\Router.php on line 779 {"exception":"[object] (TypeError(code: 0): Illuminate\\Routing\\Router::sortMiddleware(): Argument #1 ($middlewares) must be of type Illuminate\\Support\\Collection, Hyperf\\Utils\\Collection given, called in C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php on line 779 at C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php:788)
[stacktrace]
#0 C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(779): Illuminate\\Routing\\Router->sortMiddleware(Object(Hyperf\\Utils\\Collection))
#1 C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(737): Illuminate\\Routing\\Router->resolveMiddleware(Object(Hyperf\\Utils\\Collection), Array)
#2 C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(223): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#3 C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(195): Illuminate\\Foundation\\Http\\Kernel->gatherRouteMiddleware(Object(Illuminate\\Http\\Request))
#4 C:\\laragon\\www\\pt9\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(180): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#5 C:\\laragon\\www\\pt9\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#6 {main}
"} 
```

I really don't know how to fix this.

**Comment by rodrigopedra** [comment]
Problem happens as both Laravel and Hyperf defines a `collect` helper that return different objects:

https://github.com/laravel/framework/blob/ab1506091b9f166b312b3990d07b2e21d971f2e6/src/Illuminate/Collections/helpers.php#L6-L20

https://github.com/hyperf/hyperf/blob/837900dd4e44cc3867468b68066aa3c37f2575dc/src/utils/src/Functions.php#L105-L116

So depending on which helpers file is loaded first the `collect()` helper will be defined differently. And where the error is being thrown, a collection is constructed with the `collect()` helper just before the offended method is called.

Not sure how you would work around this. Even if you find a reproducible way to define which file is loaded first, any other call to a method which typehints a Collection could fail somewhere else.

You could send a PR changing the usage of all `collect()` helpers call to its static constructor `Collection::make()`, so framework wise one is always sure which object is constructed. But I doubt such a big change would be accepted.

Maybe Hyperf is not meant to be used alongside Laravel?

I saw in other of their helpers files that they have a lot of helpers named the same as Laravel (actually copied from Laravel). Which could conflict if one of the sides change implementations and you are not sure which is loaded first.

**Comment by driesvints** [comment]
Thanks @rodrigopedra. You indeed can't define these two at the same time.
