### ISSUE TITLE
`php artisan down --refresh=5` does not work in combination with ` --render="maintenance.index"`

### ISSUE THREAD

**Issue by lordisp** [laravel/framework#42208]
- Laravel Version: 9.9.0
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:
`php artisan down --refresh=5` does not work in combination with ` --render="maintenance.index"`   

### Steps To Reproduce:

create a custom `maintenance.index` view

run `php artisan down --refresh=5 --render="maintenance.index"`

#### Expected behavior:
`maintenance.index` view will be rendered and refreshed every 5 seconds

#### Actual behavior:
`maintenance.index` view will be rendered but **NOT** refreshed every 5 seconds

I found this issue on [stackoverflow ](https://stackoverflow.com/questions/72004966/laravel-maintenance-mode-refresh-and-render-parameter)and proposed the below workaround

### current workaround:

Parsing the `--refresh=5` argument from `$_SERVER['argv']` if available and conditionally add  a refresh meta tag in the blade
```template
$result = array_values(preg_grep('/(--refresh)/', array_values( $_SERVER['argv'] ) ));
if(!empty($result)){
  $refresh = substr($result[0], strpos($result[0], "=") + 1);
}
```

```php
@if(isset($refresh))
   <meta http-equiv="refresh" content="{{$refresh}}">
@endif
```

**Comment by driesvints** [comment]
Thank you for reporting this. I've sent in a fix for this here: https://github.com/laravel/framework/pull/42217

**Comment by driesvints** [comment]
Will be in next release. Thanks!
