### ISSUE TITLE
nested $loop->last not working

### ISSUE THREAD

**Issue by jayenne** [laravel/framework#42218]
- Laravel Version: 9.10.1
- PHP Version: 8.1.5
- Database Driver & Version: mysql 8.0.28

### Description:
I *think* there may be a bug in the foreach $loop code whereby the $loop->last isn't working as expected.  
The $loop->last within a nested foreach isn't working as expected.

### Steps To Reproduce:
pass this nested array...
```
$data= [
  'items' => [
    '0' => [
      'var' => 'zero'
      ],
    '1' => [
      'var' => 'one'
    ],
    '2' => [
      'var' => 'two'
    ]
  ]
];
```
To this blade
```
      @foreach($data as $item)
      <div class="column">
        @foreach($item->var as $var)
          @if($loop->first)
          <div class="wrapper">
          @endif
            {{ $var }}
          @if($loop->last)
          </div>
          @endif
        @endforeach
      </div>
      @endforeach
```
Notice that the `<div class="column">` gets nested as the `</div>` within $loop->last isn't being added.
where as changinf to `$loop->index === n` is fine...
```
      @foreach($data as $item)
      <div class="column">
        @foreach($item->var as $var)
          @if($loop->first)
          <div class="wrapper">
          @endif
            {{ $var }}
          @if($loop->index == $loop->count)
          </div>
          @endif
        @endforeach
      </div>
      @endforeach
```

**Comment by driesvints** [comment]
Your `$data` array isn't correct. You need to use `$data['items']`. `$item->var` isn't correct either and needs to be `$item['var']`. 

Further, I've tested several scenarios and all calls to `$loop->last` worked for me.

**Comment by jayenne** [comment]
Sorry for my poor issue then. Than kyou for checking and confirming this though. I did wonder if this could really be a bug.
- I still can't get a value for $loop->last (or $loop->count, $loop->remaining etc) I'll keep working on it.
