### ISSUE TITLE
Incorrect parameter type for validation concerns

### ISSUE THREAD

**Issue by phanan** [laravel/framework#42236]
- Laravel Version: v9.10.1
- PHP Version: v8.1
- Database Driver & Version: Irrelevant

### Description:

Given this custom validator code that was working fine before:

```php
private const MAX_SIZE_IN_KB = 5 * 1024; // 5MB

public function validate($attributes, $value, $parameters, Validator $validator): bool
{
    return $validator->validateMax($attributes, $value, [self::MAX_SIZE_IN_KB]);
}
```

The change introduced 2e2e57c3670b9f09711252e2793a1734290cc54a (PR #42151) now causes PHPStan (or Psalm, for that matter) to report a type error:

```
 ------ ------------------------------------------------------------------- 
  Line   /Dir/CustomFileSizeValidator. php
 ------ ------------------------------------------------------------------- 
  28     Parameter #3 $parameters of method                                 
         Illuminate\Validation\Validator::validateMax() expects array<int,  
         string>, array<int, int> given.                                    
 ------ ------------------------------------------------------------------- 
```

A workaround could be to convert `self::MAX_SIZE_IN_KB` to string, but I believe this should be fixed from the cause — maybe to use `array<int, int|string>` instead of `array<int, string>`.

The example above is for `validateMax`, but the problem may happen for other methods found in the `ValidatesAttributes` trait as well.

### Steps To Reproduce:

N/A.

**Comment by driesvints** [comment]
We don't consider PHPStan or Psalm errors as actual bugs. Feel free to PR something to fix anything you have in mind 👍

**Comment by phanan** [comment]
@driesvints Sure, I can send a PR over. I'd argue though, that this is an actual bug (documented type and actual support type don't match). What static analyzers do in this case is to make it visible.

**Comment by driesvints** [comment]
No code will break because of this.

**Comment by phanan** [comment]
It doesn't take breaking code to be a bug IMHO, but I get where you're coming from. I'll see what I can do.
