### ISSUE TITLE
FTP writing error throws exceptions that doesn't implement League\Flysystem\UnableToWriteFile intferface

### ISSUE THREAD

**Issue by Keryx42** [laravel/framework#42234]
- Laravel Version: 9.10.1
- PHP Version: 8.1.0
- Database Driver & Version:  MySQL (ver. 5.7.36)
- league/flysystem-ftp 3.0.9

### Description:
According to the Laravel documentation storage writing errors (with throwing enabled) should throw exceptions that implement the interface `League\Flysystem\UnableToWriteFile`

https://laravel.com/docs/9.x/filesystem#failed-writes

If you're using an ftp configuration where everything except the `root` is valid.
And do a writing operation. Than the following problem occurs:

- The by laravel used flysystem generates a warning due to the usage of the native php function ftp_chdir
  - [FtpAdapter](https://github.com/thephpleague/flysystem-ftp/blob/38d829f6bbb1a5368e9bf9117273df6aaaa51938/FtpAdapter.php#L649)
- Laravels error handler turns this warning into an ErrorException
  - [HandleExceptions.php](https://github.com/laravel/framework/blob/a880574f5ada4c9aa0c9353a8cfae3e71f981e7a/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L68)

The ErrorException does of course not implement the UnableToWriteFile interface. Which is the Bug.
So in my opinion the Laravel [FilesystemAdapter](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemAdapter.php) should take care if this ErrorException and re-throw it implementing the correct interface. Or some solution that brings a similar result :)

#### Additional Notes
I don't think this is a league/flysystem bug. As they say in the documentation that every exceptions implements the FilesystemExcption Interface. But from the view of the package this is only a warning.
https://flysystem.thephpleague.com/docs/usage/exception-handling/

### Steps To Reproduce:

I created a public repository as wished https://github.com/Keryx42/laravel-filesystem-bug-showcase

I also repeat now what I did to get to the probem

- Add an ftp configuration to the config/filesystems.php file
  - Everthing must be valid except the `root`
  - `throws` must be true
  - See https://github.com/Keryx42/laravel-filesystem-bug-showcase/blob/ba684d5475e7f6c3ac4c841b343f13b7735baa80/config/filesystems.php#L59
- Try to execute a writing operation to that disk
  - Like `    Storage::disk('bug_showcase_ftp')->put('bug_showcase.txt','bug showcase');`
- This should lead to an ErrorException

### Final Notes
This is my first bug report. Feel free to ask any question

Thanks for creating laravel I love it <3

**Comment by driesvints** [comment]
Hey @Keryx42, thanks for the report. It's definitely well written.

I'm not sure I agree this is a Laravel issue. We can't catch all ErrorExceptions in the filesystem adapter because that would hide actual errors/bugs. I feel like this should either be caught by the Flysystem FTP adapter and converted into a dedicated exception or this should bubble up to the app like it does now so it's explicit that there's something wrong with the code that calls the filesystem. I'll discuss this with @frankdejonge.

**Comment by driesvints** [comment]
This is going to be addressed within Flysystem soon. Thanks!

**Comment by Keryx42** [comment]
@driesvints Thanks so much :) Have a great day!

**Comment by Keryx42** [comment]
Final update for completeness :)

The problem got solved here
https://github.com/thephpleague/flysystem/blob/3.0.19/CHANGELOG.md
