### ISSUE TITLE
Component overrides variable on view

### ISSUE THREAD

**Issue by datlechin** [laravel/framework#42240]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- Database Driver & Version: 8.0.28 MySQL Community Server

### Description:
Component modifies the variable passed from controller to view.

Controller
```php
$attributes = Attribute::query()->paginate();

return view('admin.attributes.index', compact('attributes'));
```

View
```html
...
<!-- $attributes is pagination -->
<x-link :href="route('admin.attributes.create')"/>
<!-- $attributes now is collection -->
...
{{ $attributes->link() }} <!-- Collection::links() not found -->
```

Above the component the `$attributes` variable is **Pagination** but below the component `$attributes` is **Collection**. So the Component changed the `$attributes` variable.

### Steps To Reproduce:

N/A

**Comment by driesvints** [comment]
Heya. Attributes is a reserved keyword within Blade and should be avoided in your views for app-related code.
