### ISSUE TITLE
How to add extra data on session guard recaller

### ISSUE THREAD

**Issue by PaolaRuby** [laravel/framework#42271]
### Discussed in https://github.com/laravel/framework/discussions/42067

<div type='discussions-op-text'>

<sup>Originally posted by **PaolaRuby** April 20, 2022</sup>
Only admit 3 segments, `id`,`token`,`hash`
https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Auth/Recaller.php#L80-L85
Is there a config for set a custom recaller with more segments?
Is there a way or a plugin for customize session recaller?</div>

If we create a custom session class extending `SessionGuard`, or we change the `remember me` cookie on login, we need a way to get the extra data from recaller
This is useful when you have a multi company login, or when needs an extra id/value to rebuild the session

**Comment by PaolaRuby** [comment]
Let's be honest, @taylorotwell only reviews PR from known collaborators, he closes everyone else without reviewing with the same copy/paste message
>Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include.

**Comment by driesvints** [comment]
Hey @PaolaRuby, please don't move discussions to issues.

Also, Taylor is free to merge whatever he prefers into the codebase. I'm sorry you feel differently.

**Comment by taylorotwell** [comment]
Also, Laravel has over 2,000 contributors - so, no, they are not all my "known collaborators".

**Comment by PaolaRuby** [comment]
Multi company login, is a manyToMany relation, on login user pick wich company use for session, on "remember me" rebuild the user session but not the company, of course i can create another cookie for rebuild the picked company, but would be great if the recaller can handle that extra id/ids

@taylorotwell thank, first time you answer me
>Also, Laravel has over 2,000 contributors - so, no, they are not all my "known collaborators".
Sorry ,I don't know how to solve it
