### ISSUE TITLE
Change Http::post Signature to allow payloads of array|null|object

### ISSUE THREAD

**Issue by declum** [laravel/framework#42288]
- Laravel Version: ^9.

### Description:
Allow the post payload to support object|null|array. 

1. To support, passing null as payload, 
2. To support, passing empty object {} as payload, 

### Steps To Reproduce:

Http::withBasicAuth($username, $password)
            ->withHeaders([
                'Accept' => 'application/json'
            ])
            ->post('http://hostname/login', null)->throw()->json(); # <------ IDE show warning since end argument is supposed to be array

Http::withBasicAuth($username, $password)
            ->withHeaders([
                'Accept' => 'application/json'
            ])
            ->post('http://hostname/login', (object)[])->throw()->json(); # <------ IDE show warning since end argument is supposed to be array, but i have to pass empty object {} to server

**Comment by driesvints** [comment]
No code is broken here. You're free to attempt a pr if you want to change the docblock
