### ISSUE TITLE
`CursorPaginator::onLastPage` method mentioned in docs but does not exist

### ISSUE THREAD

**Issue by elidrissidev** [laravel/framework#42296]
- Laravel Version: 9.11.0
- PHP Version: 8.1.4
- Database Driver & Version: MariaDB 10.7.3

### Description:

The method `onLastPage` is mentioned in [pagination docs](https://laravel.com/docs/9.x/pagination#cursor-paginator-instance-methods) but when calling it on the cursor instance it throws an error. `onFirstPage` works just fine.

### Steps To Reproduce:

- Use cursor paginator on any model and try to access the `onLastPage` method like so:
```php
App\Models\Repository::orderBy('id')->cursorPaginate()->onFirstPage(); // Works fine
App\Models\Repository::orderBy('id')->cursorPaginate()->onLastPage(); // Throws 'Method Illuminate\Database\Eloquent\Collection::onLastPage does not exist.'
```

**Comment by driesvints** [comment]
Thanks, a PR was sent in 👍
