### ISSUE TITLE
[9.x] Attributes on Auth::user() instance have relationships inside them - they're marked as dirty

### ISSUE THREAD

**Issue by tntsoft** [laravel/framework#42300]
- Laravel Version: v9.11.0
- PHP Version: 8.1.5
- Database Driver & Version: 10.5.13-MariaDB - Homebrew

### Description:
I've opened a PR attempting to patch this problem #42292 

I've detailed everything I could there. I'm happy to get on a call and provide more context, I've tried to explain the problem as best as I could in the PR.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
