### ISSUE TITLE
Laravel `unsignedFloat` creates unsigned DOUBLE (8, 2) column #bug

### ISSUE THREAD

**Issue by raimondslinde** [laravel/framework#42308]
- Laravel Version: 8.83.11
- PHP Version: 8.0
- Database Driver & Version: MariaDB latest

### Description:
Laravel `unsignedFloat` creates unsigned DOUBLE (8, 2) column #bug

### Steps To Reproduce:
```
        Schema::create('test_table', function (Blueprint $table) {
            $table->unsignedFloat('quantity')->default(1);
        });
```

**Comment by driesvints** [comment]
Please see previous issues around this subject why we can't change this.

Thanks @rodrigopedra

**Comment by raimondslinde** [comment]
I ended up, after creating DOUBLE (8, 2), using ALTER TABLE:

```DB::statement('ALTER TABLE `test_table` CHANGE COLUMN `quantity` `quantity` FLOAT UNSIGNED NOT NULL DEFAULT 1');```
