### ISSUE TITLE
WTF dynamic prefix

### ISSUE THREAD

**Issue by MrTomek** [laravel/framework#42319]
NOT WORK
```
        DB::setTablePrefix($this->prefix);
        $schema = DB::getSchemaBuilder();
        $prefix = DB::getTablePrefix();

        if(!$schema->hasTable('migrations')) {
            $schema->create('migrations', function ($table) {
                $table->increments('id');
                $table->string('migration');
                $table->integer('batch');
            });
        }
```

WORK
```
        DB::setTablePrefix($this->prefix);
        $schema = DB::getSchemaBuilder();
        $prefix = DB::getTablePrefix();

        if(!$schema->hasTable('migrations')) {
            $schema->create($prefix . 'migrations', function ($table) {
                $table->increments('id');
                $table->string('migration');
                $table->integer('batch');
            });
        }
``

**Comment by rodrigopedra** [comment]
What is wrong? What did you expect to happen?

Database prefix is not applied to the `migrations` table. If you want to customize the `migrations` table name, you should modify the `migrations` key on your app's `./config/database.php` file.

https://github.com/laravel/laravel/blob/7216fa7e9a797227f303630d937a0722878b753b/config/database.php#L98-L109

Next time use more polite wording and try adding a better description of what is wrong and justify why do you think something is a bug. This is free software and a great part of the contributions are made by volunteers on their free time, be respectful.

**Comment by MrTomek** [comment]
In hasTable prefix is not needed and in create already there?

This is not a solution to the problem, it needs to dynamically change the prefix (multi tenant single database)

**Comment by MrTomek** [comment]
```
// $this->prefix == '123_'
DB::setTablePrefix($this->prefix);
$schema = DB::getSchemaBuilder();
$prefix = DB::getTablePrefix();
$schema->hasTable('migrations'); // Reality check is '123_migrations'
            $schema->create($prefix . 'migrations', function ($table) {  // create '123_migrations'
                $table->increments('id');
                $table->string('migration');
                $table->integer('batch');
            });
```

**Comment by rodrigopedra** [comment]
Why do you want a separate migration table for each prefix?

if you are storing all tables into the same database, won’t a single migration table suffice for you use case?

The migration will be aware of all tables with each prefix and you won’t have to manage changing the migration table name each time you want to run a new migration.

If you believe this is something that is justified to be added in the franework, send a PR proposing the change, or open a discussion thread to gather other opinions.

Current behavior is by design and therefore not a bug. Your use case is a feature request and not a bug report.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MrTomek** [comment]
@rodrigopedra Thanks for the explanation here, you are right about the migration as one table, although laravel probably does not have this correct function completely, so give another example: 

```
    public function handle()
    {
        DB::setTablePrefix('test_');
        Artisan::call('migrate');
    }
```

This returns an error:
```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations' already exists (SQL: create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(191) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

**Comment by rodrigopedra** [comment]
@MrTomek 

~~~php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;

Artisan::command('local:test', function () {
    Artisan::call('db:wipe');

    $this->info('Migrating first');
    Config::set('database.connections.mysql.prefix', 'first_');
    DB::purge(); // recreate connection to apply new prefix
    Artisan::call('migrate');


    $this->info('Migrating second');
    Config::set('database.connections.mysql.prefix', 'second_');
    DB::purge(); // recreate connection to apply new prefix
    Artisan::call('migrate');
});
~~~
