### ISSUE TITLE
Exception::__construct(): Argument #2 ($code) must be of type int, string given at .../Illuminate/Database/Concerns/ManagesTransactions.php:94)

### ISSUE THREAD

**Issue by Brenneisen** [laravel/framework#42317]
- Laravel Version: 9.11.0
- PHP Version: 8.0.18
- Database Driver & Version: 

### Description:

After updating to v9.11.0, we are conveniently seeing this error in our log:

`Exception::__construct(): Argument #2 ($code) must be of type int, string given at .../Illuminate/Database/Concerns/ManagesTransactions.php:94)`

It seems to be related to this PR https://github.com/laravel/framework/pull/42129.

**Comment by rodrigopedra** [comment]
In theory `->getCode()` should return an `int`, as seen here:

https://www.php.net/manual/en/throwable.getcode.php

I know PHP is not yet enforcing method signature on extended classes, but I would say the exception being caught and wrapped is not conforming to the definition.

Can you share the full stack trace, so we can assess the original Exception? 

Or, if what originates this error is a custom exception defined in your app, check if its `getCode` is returning an `int`, or is being constructed with a `string` code instead of an `int`?

The `$code` argument for `Exception` descendants, should be an `int`, while not yet being enforced:

https://www.php.net/manual/en/exception.construct.php

**Comment by rodrigopedra** [comment]
To illustrate what I meant:

~~~php
class OtherException extends RuntimeException {}

Artisan::command('local:test', function () {
    try {
        throw new RuntimeException('foo', 'bar'); // <<< code should be an int here
    } catch (Throwable $e) {
        throw new OtherException($e->getMessage(), $e->getCode(), $e);
    }
});
~~~

As the first `RuntimeException` thrown is not honoring the constructor signature, when this is wrapped into another inside the catch, it fails, as this wrapper exception defines the scalar type hint `int`.

In my opinion, the fault is from the inner exception which is not respecting the constructor signature, and not from the wrapping exception.

But if this signature mismatch is from a third-party package and not from code you own, a middle ground would be to propose to remove the typehints from the `DeadlockException` constructor signature.

**Comment by driesvints** [comment]
I doubt this is an issue with Laravel itself for the reasons @rodrigopedra explained. Maybe if @rodrigopedra's PR gets merged you can see what the actual exception is.

Thanks for the help always @rodrigopedra, we appreciate it 👍

**Comment by rodrigopedra** [comment]
Thank you @driesvints for your hard work and all Laravel team.

Laravel changed my life, whenever I have the time it is my pleasure to give back something to the project =)

**Comment by Brenneisen** [comment]
@driesvints @rodrigopedra 

Please have a look at: https://www.php.net/manual/en/exception.getcode.php

"Returns the exception code as int in [Exception](https://www.php.net/manual/en/class.exception.php) but possibly as other type in [Exception](https://www.php.net/manual/en/class.exception.php) descendants (for example as string in [PDOException](https://www.php.net/manual/en/class.pdoexception.php))."

It seems that the `PDOException` returns a `string`. The previous exception is a `Illuminate\Database\QueryException extends PDOException` that returns a `string` instead of an `int`.

**Comment by Brenneisen** [comment]
@driesvints @rodrigopedra 

A fix should be made in `Illuminate\Database\QueryException:39` where `$this->code = $previous->getCode();` could result in a string if the previous exception is a PDOException.

**Comment by rodrigopedra** [comment]
@Brenneisen I just noticed that `DeadlockException` constructor does not enforce any type hints:

https://github.com/laravel/framework/blob/544ee0d2add5619ea85993c6462e86a1a250ecbe/src/Illuminate/Database/DeadlockException.php#L1-L10

So the error message is very weird...

- Do you have any special setup such as enforcing strict types on all files?
- Or maybe this error message is from a static analyzer or something like that?

**Comment by driesvints** [comment]
This seems more of a bug in PHP to me... PDOException indeed doesn't have a constructor so it inherits the one from Exception: https://www.php.net/manual/en/class.exception.php

This one only accepts an `int` while it should accept a `int|string` for PDOException. Imo, the `PDOException` exception should have its own constructor.

**Comment by Brenneisen** [comment]
The following code throws the reported exception:

```
DB::transaction(function() {
    throw new PDOException('Deadlock found when trying to get lock', 'Test');
})
```

**Comment by driesvints** [comment]
Yes, that's because of what I explained above. I think the PHP PDOException should have its own constructor.

**Comment by Brenneisen** [comment]
@rodrigopedra There is no original exception in my codebase. The problem is caused by a deadlock, which is handled correctly by Laravel within a transaction. A deadlock can happen in principle and is usually solved by trying again. So a `PDOException` is caught, which happens during a mysql query. But this exception then has no `int`, but a `string` as code. I do not know why.

Maybe a `(int) $this->getCode()` in `Illuminate/Database/Concerns/ManagesTransactions.php:93` could fix this problem.

**Comment by Brenneisen** [comment]
@driesvints The `Illuminate\Database\QueryException` is thrown in Laravel and handled as a deadlock. The `TypeError` was added in v9.11.0. I understand that my PR is not the best solution but then the `DeadlockException` should be reverted instead. So it is not usable and so it is a bug in laravel, because the original exception happens in laravel.

**Comment by Verification39** [comment]
@Brenneisen https://stackdev.space/questions/is-the-security-of-redbean-orm-reliable-in-php
