### ISSUE TITLE
About onWriteConnection method's return value

### ISSUE THREAD

**Issue by daikisuyama-fs** [laravel/framework#42322]
- Laravel Version: 5.6.40
- PHP Version: 7.4.29

### Description:

Here is the definition of onWriteConnection in \Illuminate\Database\Eloquent\Model.

```
/**
* Begin querying the model on the write connection.
*
* @return \Illuminate\Database\Query\Builder
*/
public static function onWriteConnection()
{
  $instance = new static;

  return $instance->newQuery()->useWritePdo();
}
```

I use this method to init builder for select clause in the method of ToDo class which extends model class.

```
$builder = self::onWriteConnection();
```

In onWriteConnection's doc, onWriteConnection must return \Illuminate\Database\Query\Builder, but it returns \Illuminate\Database\Eloquent\Builder. 

If we use this method like me, same situation will happen. So, onWriteConnection should be like below.

```
/**
* Begin querying the model on the write connection.
*
* @return \Illuminate\Database\Eloquent\Builder
*/
public static function onWriteConnection()
{
  $instance = new static;

  return $instance->newQuery()->useWritePdo();
}
```

Plus, I checked 9.x's code, maybe same problem can happen.
So, if I don't bother you, please check it...

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by daikisuyama-fs** [comment]
This fix was merged.

https://github.com/laravel/framework/pull/43512
