### ISSUE TITLE
Migration inconsistency when using change() for default value 

### ISSUE THREAD

**Issue by Jeroenwv** [laravel/framework#42336]
- Laravel Version: 8.83.10
- PHP Version: 8.1.5
- Database Driver & Version: MariaDB 10.7.3 (also on MySQL)

### Description:
When creating a new column using migrations, it is possible to set the column default value. Sometimes it is necessary to pass the default as raw to use native MySQL functions like UUID(). We can do this by utilising the DB::raw() function. The migration below creates a column with the default value `(REPLACE(UUID(),'-',''))` as expected.

```php
Schema::create('example', function (Blueprint $table) {
    $table->uuid('uuid')->default(DB::raw('(replace(uuid(),\'-\',\'\'))'));
});
```

Using the same methodology to change an existing column produces a different result. Even though the DB::raw() function is used, the passed value will be quoted and becomes a string `'(REPLACE(UUID(),'-',''))'`.

```php
Schema::table('example', function (Blueprint $table) {
    $table->uuid('uuid')->default(DB::raw('(replace(uuid(),\'-\',\'\'))'))->change();
});
```

### Steps To Reproduce:
Create a migration with the following snippet to add a new table. When you check the default value in MySQL or add a new record, the default value works as expected.
```php
Schema::create('example', function (Blueprint $table) {
    $table->id();
    $table->uuid('uuid')->default(DB::raw('(replace(uuid(),\'-\',\'\'))'));
});
```

Now create a second migration to change the default value. We'll try to repace _ instead of - as example.
```php
Schema::table('example', function (Blueprint $table) {
    $table->uuid('uuid')->default(DB::raw('(replace(uuid(),\'_\',\'\'))'))->change();
});
```
If you check the default value in MySQL or add a new record, the default value is a string.

**Comment by eduance** [comment]
@driesvints Currently trying to solve this issue, but would prefer your advice.

The change method compares doctrine objects using the TableDiff, we try to get the AlterTableSQL from a custom database platform.

Essentially it tries to call the getDefaultValueDeclarationSql() which does some checks but does not do the same checks Laravel does as Laravel checks for the default column whether the value is an instance of the Query builder expression.

What are your thoughts on a good solution?

1. Overriding the abstract platform.
2. Overriding all platforms Laravel implements, binding them and adding custom default checks?
3. Looking for a different way to compare the Doctrine objects and generating the SQL

Would love moving forward on this today.

**Comment by driesvints** [comment]
Please don't use `DB::raw` for setting the default. We use `doctrine/dbal` behind the scenes to do the migration changes and using raw statements gives no guarantee that things will go as expected.

**Comment by eduance** [comment]
@driesvints Is it allowed to add this to documentation or look for a way of using DB::raw within the default? It is possible to fix this by extending the MYSQL platform and modying the default value in order for this to work but this would cause a maintenance burden for MYSQL upgrades.

**Comment by driesvints** [comment]
Adding this to the docs that it's not supported can indeed be helpful. Looking for a way to make this work with DB raw isn't a path I'd take.
