### ISSUE TITLE
Event::fake() breaks extended HTTP status assertion error messages

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#42334]
- Laravel Version: 9.11.0
- PHP Version: 8.1.5

### Description:
Laravel has recently introduced a feature that prints exceptions and/or validation errors that occurred during a request from a test case: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Testing/TestResponse.php#L234

Having a fake dispatcher (one that doesn't actually propagate events) breaks this functionality: https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php#L116

### Steps To Reproduce:
1. Run the following test:
```php
Event::fake();

Route::get('test', function () {
    throw new \Exception();
});

$this->getJson('test')
    ->assertOk();
```

**Comment by driesvints** [comment]
These two features are not compatible unfortunately.
