### ISSUE TITLE
[9.12.0] Enum bug within relationship

### ISSUE THREAD

**Issue by it-can** [laravel/framework#42338]
- Laravel Version: 9.12.0
- PHP Version: 8.1.5
- Database Driver & Version: MariaDB 

### Description:
I suddenly get these errors after this commit (laravel v9.12.0), commit #42100.
v9.11.0 and earlier works correct...

```
str_starts_with(): Argument #1 ($haystack) must be of type string, App\Models\Enums\ProductType given
```

Seems to be caused by this line, https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L786=

### Steps To Reproduce:
I have a product model, with a product_type with an enum. The problem appears when doing something like this

--
This is located in my Product model

```
/**
     * Get all sub products
     *
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function simpleProducts()
    {
        return $this->hasMany(self::class, 'parent_id', 'id')
            ->where('active', 1)
            ->where('product_type', ProductType::SIMPLE)
            ->orderBy('sort');
    }
```

ProductType enum
```
namespace App\Models\Enums;

enum ProductType: string
{
    case SIMPLE = 'simple';
    case GROUPED = 'grouped';
    case CONFIGURABLE = 'configurable';
}
```

```
return Product::withCount('simpleProducts')
    ->get();
```

Calling this works correct....

```
return Product::where('product_type', ProductType::SIMPLE)
    ->get();
```

**Comment by rodrigopedra** [comment]
Sent PR #42341 to address this issue.
