### ISSUE TITLE
Str::between return full subject if no match is found

### ISSUE THREAD

**Issue by RomainGoncalves** [laravel/framework#42332]
- Laravel Version: 8.83.2
- PHP Version: 8.1.2
- Database Driver & Version: /

### Description:
When using `Str::between($subject. $from, $to)` and no match is found, the method returns the value of `$subject`. Is that intentional? I would expect `null|undefined`. As I am trying to know if there is a string between quotes, if there are no quotes, I expect null to be returned.

### Steps To Reproduce:
`Str::between('this is my name', '"', '"'); // => 'this is my name'`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by RomainGoncalves** [comment]
I was also wondering if it was intentional behaviour, and if not, then it's an issue :D
