### ISSUE TITLE
Cache Repository remember() when callback returns null then write null value to redis frequently

### ISSUE THREAD

**Issue by zmou** [laravel/framework#42343]
- Laravel Version: 8.49.2
- PHP Version: 7.4.29
- Database Driver & Version: Mysql 5.7

### Description:
When remember a key to redis,if Closure callback returns a value null,A null value is written to Redis.However,Next time read the key from Redis,you get a NULL,but remember func just return immediately when a value is not null,At this point, null will continue to be stored into Redis.This would cause an endless loop of writing null to Redis.
```
/**
 * Get an item from the cache, or store the default value.
 *
 * @param  string  $key
 * @param  \DateTime|int  $minutes
 * @param  \Closure  $callback
 * @return mixed
 */
public function remember($key, $minutes, Closure $callback)
{
    // If the item exists in the cache we will just return this immediately
    // otherwise we will execute the given Closure and cache the result
    // of that execution for the given number of minutes in storage.
    if (! is_null($value = $this->get($key))) {
        return $value;
    }

    $this->put($key, $value, $minutes);

    return $value;
}
```
In our online production environment,We found that some keys are written to null frequently. Redis command: 
`SETEX cacheKey 3600 N;` 
This results in very high QPS for redis writes under very high concurrency, but these writes are useless and do nothing.

### Steps To Reproduce:
Create a cache key on purpose, let the closure return NULL, and open the Redis audit log, pressure your page, and watch the Redis write log.

So I want to determine the result of closure execution before writing to Redis. If it is null, I will return it directly. If it is not null, I will write to Redis to ensure that no NULL value is stored in redis.
```
/**
 * Get an item from the cache, or store the default value.
 *
 * @param  string  $key
 * @param  \DateTime|int  $minutes
 * @param  \Closure  $callback
 * @return mixed
 */
public function remember($key, $minutes, Closure $callback)
{
    // If the item exists in the cache we will just return this immediately
    // otherwise we will execute the given Closure and cache the result
    // of that execution for the given number of minutes in storage.
    if (! is_null($value = $this->get($key))) {
        return $value;
    }

    // If the result of Closure is null,then return null immediately
    $value = $callback();
    if (is_null($value)) {
        return null;
    }

    $this->put($key, $value, $minutes);

    return $value;
}
```

**Comment by Yi-pixel** [comment]
@driesvints 

> I don't think it makes sense to store `null` in cache. Also see the note here about cache misses in the PSR-16 standard (which is what you're experiencing and causing the infinite loop). You're responsible to check this in the app.
> 
> https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-16-simple-cache.md
> 
> <img alt="Screenshot 2022-05-12 at 10 44 31" width="1121" src="https://user-images.githubusercontent.com/594614/168030404-ccc2224b-efda-46f5-ba3b-be65e7eb6ba0.png">


> I don't think it makes sense to store null in cache.

Agreed, but I think the solution here is to not use put to put null in the cache when $callback() returns null here.

So need to add a judgment condition here. If the result of $callback() is null , there is no need to put.

Because when the previous code gets the value from the cache, it only judges whether it is null or not. So you shouldn't store a null here (meaningless value, it will always cause the previous judgment to be true)

![Snipaste_2022-05-12_17-02-40](https://user-images.githubusercontent.com/31845646/168033971-44ee8e45-317d-4837-af86-6bd2a7cfd0dd.png)


- [Illuminate/Cache/Repository.php](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Cache/Repository.php#L391)

**Comment by driesvints** [comment]
It's still valid to store `null` in cache. Even if Redis can't handle it (then you need to take care of this yourself) there might be other cache stores that do.

**Comment by driesvints** [comment]
What I'm trying to say is that the spec allows for it and thus we allow it too. I'm not saying it makes sense to store `null` in cache, just saying that right now we adhere to the spec.

**Comment by Yi-pixel** [comment]
> What I'm trying to say is that the spec allows for it and thus we allow it too. I'm not saying it makes sense to store `null` in cache, just saying that right now we adhere to the spec.

If this is the case, then replace the previous get with has(eg: Redis exits), which may be more appropriate?

**Comment by Yi-pixel** [comment]
@driesvints 

I think I understand what you said now, but null can be regarded as a special existence in this block of code, because the previous get judgment only uses is_null.

So, if want to eliminate this ambiguity, then maybe change the previous get + is_null to the exists method of the cache (eg: Redis exists).

**Comment by zmou** [comment]
> What I'm trying to say is that the spec allows for it and thus we allow it too. I'm not saying it makes sense to store `null` in cache, just saying that right now we adhere to the spec.

There's nothing wrong with following the norm, but I don't think it's a mandatory norm. From a user's perspective, when a closure returns NULL, it means undefined or nonexistent. In this case, we do not want it to trigger the cache operation, but to return NULL. If we really want to solve the similar cache breakdown problem, we can write null to the cache, but we should consider a key valid if it exists in the cache. For example, we use the EXISTS command of Redis to determine the existence of the key. But here remember function does not need to solve the problem of cache breakdown, and should be stored value effectively, to sum up is simply, if the cache key exists, we shall immediately return the contents of this key storage, and should not to judge whether the content is null, because to do so is pointless, contradictory.
