### ISSUE TITLE
redis connection faild

### ISSUE THREAD

**Issue by yexk** [laravel/framework#42348]
- Laravel Version: 8.12
- PHP Version: 7.2
- Database Driver & Version: redis-5.2

### Description:
```
[2022-05-11 08:57:39] prod.ERROR: Connection refused [tcp://redis.vnkash:tcp://10.233.24.65:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 111): 
Connection refused [tcp://redis.vnkash:tcp://10.233.24.65:6379] at /www/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
[stacktrace]
#0 /www/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\\Connection\\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /www/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Parameters), 'tcp://redis.vnk...', 4)
#2 /www/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parameters))
#3 /www/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#4 /www/vendor/predis/predis/src/Connection/StreamConnection.php(258): Predis\\Connection\\AbstractConnection->connect()
#5 /www/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\\Connection\\StreamConnection->connect()
#6 /www/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\\Connection\\AbstractConnection->getResource()
```

### Steps To Reproduce:
I use k8s deploy . But I got my port wrong.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
