### ISSUE TITLE
TypeError when using Redis pipeline

### ISSUE THREAD

**Issue by timndus** [laravel/framework#42375]
- Laravel Version: 9.1.8
- PHP Version: 8.1.2
- Redis Version: 6.2.6

### Description:
https://github.com/laravel/framework/blob/016b0c1801f4c6b0bb79b0d82791f4853ed19fc5/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L117  

This will try to get values of a Redis object instead of an array if we use the HMGET in a PIPELINE 
 
`array_values(): Argument #1 ($array) must be of type array, Redis given`  

  -----
  
  
detail:  
```
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(117): array_values()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(276): Illuminate\Redis\Connections\PhpRedisConnection-&gt;hmget()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Redis\RedisManager-&gt;__call()
#3 /var/www/html/routes/api.php(21): Illuminate\Support\Facades\Facade::__callStatic()  
```  

### Steps To Reproduce:
```
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Route;

Route::get('/test', function (){
    Redis::HMSET(
        'test',
        [
            'name' => 'timndus',
            'age' => '64',
            'color' => 'green'
        ]
    );

    Redis::PIPELINE();
    Redis::HMGET('test', ['name', 'age']);
    $test = Redis::EXEC();
    
    return $test;
});
```

**Comment by driesvints** [comment]
Please fill out the issue template when submitting issues.

**Comment by timndus** [comment]
> Please fill out the issue template when submitting issues.

Sorry about that, I updated the issue. Can u open it or should I submit a new one? @driesvints

**Comment by eduance** [comment]
@driesvints I can have something ready by tonight!

**Comment by timndus** [comment]
> Thanks. Can you maybe send in a PR for this?

Here is a PR, but honestly I'm not sure of my solution
https://github.com/laravel/framework/pull/42383

**Comment by eduance** [comment]
@timndus This is not the correct usage of the pipeline method, after some studying and reading into the predis test suite, this is how a pipeline should be built:

``
    $pipe = Redis::pipeline();

    $pipe->hmget('test', ['name', 'age', 'color']);

    $results = $pipe->exec();

    return $results;
``

Or you could instead use:

``
    Redis::pipeline(function ($pipe) {
        $pipe->hmget('test', ['name', 'age']);
    });
``

This is as how predis suggests it in their documentation. Therefore, there is no need to change the `hmget()` as it currently is working properly in Laravel.

Your code would not be able to work properly because the pipeline method would always return a redis object, and as it isn't yet retrieved, hmget would not function properly.

**Comment by timndus** [comment]
> @timndus This is not the correct usage of the pipeline method  

@eduance You are absolutely correct, thanks for the explanation 🙏
@driesvints This issue can be closed 🙏. And the related PR https://github.com/laravel/framework/pull/42383
