### ISSUE TITLE
Set mutator is being called multiple time in create 

### ISSUE THREAD

**Issue by Zaak22** [laravel/framework#42387]
- Laravel Version: 9.6.0
- PHP Version: 8.1.4

### Description:

I have a Service Controller with store method:
![image](https://user-images.githubusercontent.com/74628308/168422271-ac5c0b29-7fec-4253-95a2-3041aefbf9ce.png)

And inside Service model:
![image](https://user-images.githubusercontent.com/74628308/168421723-4e5bd52a-d244-4251-b25a-1cb8dffbd4e2.png)

And inside File Controller:
![image](https://user-images.githubusercontent.com/74628308/168421768-74bd3e52-720b-4430-8866-dcec7d88ce0e.png)

When I am trying to create new service icon file is creating many times:
![image](https://user-images.githubusercontent.com/74628308/168421840-5d0e4a76-b88d-4f50-8d97-769c069013e9.png)

Why Laravel call this set method multiple times ? 
On the other side I tried to use setIconAttribute method:
![image](https://user-images.githubusercontent.com/74628308/168421922-8c7dbcef-fad2-428a-8ded-f66629645423.png)

The file created once but icon column in database is null ! 

So where is the problem and what should I use for scenarios like this?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by raiika** [comment]
Thanks @korkoshko ,
Using below works for me

    Attribute::make(...)->withoutObjectCaching()

Do you think upload file on saving with additional "isDirty" checking is better than upload file in mutator ?
