### ISSUE TITLE
`Rule::in` does not work as expected in array mode.

### ISSUE THREAD

**Issue by ranpro** [laravel/framework#42399]
- Laravel Version: v9.9.0
- PHP Version: 8.0.18
- Database Driver & Version: MySQL 5.7

### Description:

When I tried to check the array with "Rule::in" following the official example, the result was not as expected.

### Steps To Reproduce:

```php
// https://laravel.com/docs/9.x/validation#rule-in
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

$input = [
    'airports' => ['NYC', 'LAS'],
];

$validator = Validator::make($input, [
    'airports' => [
        'required',
        'array',
        Rule::in(['NYC', 'LIT']),
    ],
]);

dd($validator->invalid());
```

Output:

```
[]
```

It works with following code:

```php
$input = [
    'airports' => ['NYC', 'LAS'],
];

$validator = Validator::make($input, [
    'airports' => [
        'required',
        'array',
    ],
    'airports.*' => Rule::in(['NYC', 'LIT']),
]);

dd($validator->invalid());
```

Output:

```
array:1 [
  "airports" => array:1 [
    1 => "LAS"
  ]
]
```

It looks like it was [this commit](https://github.com/laravel/framework/commit/732686785d16968964e0216379eca4b4d781b0a1) undermines the expected behaviour.

**Comment by driesvints** [comment]
The example in the docs is incorrect. Your second example is the correct one. I'll PR a fix.

**Comment by driesvints** [comment]
https://github.com/laravel/docs/pull/7940
