### ISSUE TITLE
Dumping with dd() & dump() helpers add (^) caret before data.

### ISSUE THREAD

**Issue by medabkari** [laravel/framework#42396]
- Laravel Version: v9.12.2
- PHP Version: v8.0.12
- OS: Windows 10
- Environment: Local

### Description:
dd() and dump() helpers add a (^) caret before data.

### Steps To Reproduce:
- dd('Laravel');
- dump('Laravel');

**Comment by eduance** [comment]
@medabkari I am not able to recreate this bug in a fresh Laravel installation. Could you recreate this issue within a repository with a fresh Laravel instance?

**Comment by medabkari** [comment]
> @medabkari I am not able to recreate this bug in a fresh Laravel installation. Could you recreate this issue within a repository with a fresh Laravel instance?

Sure! Here is a fresh Laravel instance repository: https://github.com/medabkari/laravel-caret

**Comment by eduance** [comment]
@medabkari Still not able to recreate this issue. I'm pretty sure this is a local issue you're having.

https://user-images.githubusercontent.com/101891339/168525852-b77d687d-3233-4075-8a21-65c4aad82b27.mp4

**Comment by medabkari** [comment]
> @medabkari Still not able to recreate this issue.
> 
>  github-laravel-issue.mp4

Well, this is really weird. I asked people on the official Laravel server on Discord and one of the moderators checked with me and confirmed the bug. I don't see how it works fine in your machine.

I guess we're gonna have to wait for some other contributors to confirm.

**Comment by driesvints** [comment]
See the above.
