### ISSUE TITLE
Missing attributes on custom pivot table in deleting/ed events

### ISSUE THREAD

**Issue by EriBloo** [laravel/framework#42415]
- Laravel Version: 8.83.7
- PHP Version: 8.0.13
- Database Driver & Version: MySql 5.7.24 and MariaDB 10.3.28

### Description:
Model passed to deleting/ed Closures is missing attributes which makes accessing relations from pivot impossible.

### Steps To Reproduce:
Create db structure as described in [many to many polymorphic docs](https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-polymorphic-relations).

Create custom pivot class like this:
```php
class Taggable extends MorphPivot
{
    public static function boot()
    {
        parent::boot();
        
        static::created(static function ($model) {
            var_dump($model);
        });

        static::deleted(static function ($model) {
            var_dump($model);
        });
    }

    public function tag(): BelongsTo
    {
        return $this->belongsTo(Tag::class);
    }

    public function taggable(): MorphTo
    {
        return $this->morphTo();
    }
}
```

and use it on relations, eg. Post:

```php
class Post extends Model
{
    /**
     * Get all of the tags for the post.
     */
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable')->using(Taggable::class);
    }
}
```

Difference will show when attaching or detaching relations.

Screenshots taken from my application (using sync from Task class). When attaching there are no problems, all attributes in pivot are present:

![image](https://user-images.githubusercontent.com/19932449/168836607-525878dd-f555-4f45-bcd3-1c9de67ec71e.png)
 
But when detaching only 2 attributes are present:

![image](https://user-images.githubusercontent.com/19932449/168836772-694ccd2f-9ce1-4b52-8590-541e3cb71e2f.png)

This makes accesing taggable relation from within pivot delete closure impossible. Please note that it works with no problem in create closure or tinker.

Edit: Ok, as a workaround you can add $model->refresh() to deleting event which loads all attributes and makes them accesible from deleted event as well. Not an ideal solution, but fixes the problem. I assume sync doesn't load pivot tables completly which makes this not a bug, but maybe it's worth noting it somewhere in docs? (or it is added, but I missed that information)

**Comment by driesvints** [comment]
I think it's to prevent too much data being loaded when performing mass-detaches on a many to many relationship.
