### ISSUE TITLE
Get Symfony FileSytem Type error when developing package

### ISSUE THREAD

**Issue by SilvaQ** [laravel/framework#42435]
- Laravel Version: 9.x
- PHP Version: 8.1.16
- OS:
  - macos [ok]
  - centos [not ok]

I made my own package by imitating Laravel architecture. The development was normal on MacOS without any problems, but the project of installing online centos server started to report errors, and the installation was terminated due to abnormal installation dependency

Because I don't know whether I can get the answer from Laravel, Symfony or Composer, I decide to submit the issue in all three places. I hope you can help me

composer issue:
https://github.com/composer/composer/issues/10786

symfony issue:
https://github.com/symfony/symfony/issues/46402

![image](https://user-images.githubusercontent.com/46706370/169193576-22796f63-9ee1-4a80-86a3-7b5f8f9dac22.png)
 
all details for this problem I write in : 
https://github.com/composer/composer/issues/10786

**Comment by driesvints** [comment]
Please don't post on multiple issue trackers and try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by SilvaQ** [comment]
I've looked for them all, but I didn't find the answer。

and it is belong to disable function symlink problem:

https://github.com/symfony/symfony/issues/46402#event-6640805257
