### ISSUE TITLE
Unable to disable ViewServiceProvdier

### ISSUE THREAD

**Issue by bmtKIA6** [laravel/framework#42450]
- Laravel Version: 9.1.6
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:

Unable to disable the view service provider.

### Steps To Reproduce:

composer create-project laravel/laravel=9.1.8 example-app
edit config/app.php, remove ViewsServiceProvider
edit routes.php

Route::get('/', function () {
    return 'Hello World';
});

artisan serve

Seems to work with 8.x

**Comment by digitlimit** [comment]
@bmtKIA6 what do you mean to disable ViewServiceProvdier?

**Comment by digitlimit** [comment]
This is not an issue.
 I could not reproduce this.
 
 ~/projects> composer create-project laravel/laravel=9.1.8 example-app
Creating a "laravel/laravel=9.1.8" project at "./example-app"
Info from https://repo.packagist.org: #StandWithUkraine
Installing laravel/laravel (v9.1.8)


![image](https://user-images.githubusercontent.com/2041419/169390638-85402a36-a3f3-4bf1-b410-c2e68927f895.png)


On `php artisan serve`, I got a response


![image](https://user-images.githubusercontent.com/2041419/169391249-95e18d1a-4f44-4003-a2af-ab96bb3bc30e.png)

**Comment by bmtKIA6** [comment]
> @bmtKIA6 what do you mean to disable ViewServiceProvdier?

Apologies. Added a missing step of removing the views service provider from the config/app.php $providers list.

I do not need blade/views. I am building an API, which only deals with json responses

**Comment by adideas** [comment]
You need to register the ServiceProvider. Name it JsonServiceProvider style. Create your Factory class. Or just register "midleware". After the $next function exits, do the processing as you need.

**Comment by adideas** [comment]
> > @bmtKIA6 what do you mean to disable ViewServiceProvdier?
> 
> Apologies. Added a missing step of removing the views service provider from the config/app.php $providers list.
> 
> I do not need blade/views. I am building an API, which only deals with json responses

You need to register the ServiceProvider. Name it JsonServiceProvider style. Create your Factory class. Or just register "midleware". After the $next function exits, do the processing as you need.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
