### ISSUE TITLE
Nested Eager Loading not working when Eager Loading Specific Columns

### ISSUE THREAD

**Issue by Nimaw** [laravel/framework#42470]
- Laravel Version: 8.83.10
- PHP Version: 8.1.1
- Database Driver & Version: MySQL, Latest version

### Description:
Hello dear support.

### With this code books, books author and books publisher will return corecct
```php

public function mainPage()
    {
        return $this->success([
            'sections' => SectionsResource::collection(Section::with('authors:id,name', 'books', 'books.author', 'books.publisher')->get()),
        ]);
    }
```
### But if we want to select specific fields from `books` relation and eager load relations on `Book` model like this code, It will return null for publisher and author relations. 
```php

public function mainPage()
    {
        return $this->success([
            'sections' => SectionsResource::collection(Section::with('authors:id,name', 'translators:id,name', 'publishers:id,name', 'books:id,name,price,text', 'books.author', 'books.publisher')->get()),
        ]);
    }
```

**Comment by igorgaming** [comment]
I think its related to https://laravel.com/docs/9.x/eloquent-relationships#eager-loading-specific-columns
Try to specify all FK columns for all relations.

**Comment by Nimaw** [comment]
> I think its related to https://laravel.com/docs/9.x/eloquent-relationships#eager-loading-specific-columns (see note with !) Try to specify all FK columns for all relations.

Thanks for you response,
I've tried that, Not worked.

**Comment by eduance** [comment]
@Nimaw 

Could you show how you've tried eager loading the foreign keys? I'm mostly certain this is due to not selecting the right foreign keys as has been pointed out by igorgaming.

`'sections' => SectionsResource::collection(Section::with('authors:id,name', 'translators:id,name', 'publishers:id,name', 'books:id,name,price,text', 'books.author', 'books.publisher')->get()),`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
