### ISSUE TITLE
`TestResponse` fails to capture complete streamed response if system-under-test uses `ob_flush`

### ISSUE THREAD

**Issue by nagmat84** [laravel/framework#42482]
- Laravel Version: 8.83.13
- PHP Version: 8.0.16
- Database Driver & Version: n/a

### Description:

The class `TestResponse` fails to capture complete streamed response if the system-under-test uses `ob_flush()`. Currently, the method `TestResponse::streamedContent` looks like this

https://github.com/laravel/framework/blob/127a9caa8ed3965aeae0eb388967fc1030fc8f86/src/Illuminate/Testing/TestResponse.php#L1553-L1557

This code does not work, if `sendContent()` internally invokes `ob_flush()` as recommended by best-practices. `ob_get_clean()` does not return content which has been flushed and will always return the empty string.

### Steps To Reproduce:

- Create a Laravel application which uses a `StreamedResponse` with a response generator which generates some output and calls `ob_flush` at least one time
- Create a test case which tries to capture the streamed response
- Note that the captured response in incomplete

**Comment by driesvints** [comment]
Thanks. Seems like you already sent in a PR so let's see how that goes.

**Comment by nagmat84** [comment]
May I kindly ask why you close an issue if it isn't solved yet? The issue would be closed automatically if the linked PR has been merged, but until then (or until another solution has been implemented) the issue still exists.

**Comment by driesvints** [comment]
There's a PR for it already so let's continue the discussion there.
