### ISSUE TITLE
BelongsTo relation with nullable relations

### ISSUE THREAD

**Issue by pionl** [laravel/framework#42493]
- Laravel Version: 9.13.0
- PHP Version: 8.1.2

### Description:

- While using belongsTo relations (`with/load`) there can be situations when  there are no relations (nullable relations) to be loaded and query is "invalid". -> ```select `id`, `name`, `public_name` from `options` where 0 = 1 ```. 
- This similar issue can be potentially found on other relations
- This bug is not noticeable if the results contains at least 1 value in the relation (if you have pagination, some pages can contain this error).

### Steps To Reproduce:

1. Create a table with optional belongsTo relations
2. Build a query to get the results (all results should contain null)
3. Here a screenshot of a real queries 
<img width="2025" alt="Snímek obrazovky 2022-05-24 v 14 22 56" src="https://user-images.githubusercontent.com/1878831/170034097-9867c867-bf9c-4100-bff0-6ecee1426097.png">

#### Fix

1. In `Illuminate\Database\Eloquent\Relations\Relation` add property `protected bool $hasValidConstrains = true;`
2. Change the implementation of `Illuminate\Database\Eloquent\Relations\Relation::getEager `
```php
 public function getEager()
    {
        if ($this->hasValidConstrains) {
            return $this->get();
        }
        return new Collection();
    }
```
3. Change the implementation of `Illuminate\Database\Eloquent\Relations\BelongsTo::addEagerConstraints`
```php
public function addEagerConstraints(array $models)
    {
        // We'll grab the primary key name of the related models since it could be set to
        // a non-standard name and not "id". We will then construct the constraint for
        // our eagerly loading query so it returns the proper models from execution.
        $key = $this->related->getTable().'.'.$this->ownerKey;

        $whereIn = $this->whereInMethod($this->related, $this->ownerKey);

        $eagerModelKeys = $this->getEagerModelKeys($models);

        if ($eagerModelKeys === []) {
            $this->hasValidConstrains = false;
            return;
        }

        $this->query->{$whereIn}($key, $eagerModelKeys);
    }
```

**Result**

<img width="1650" alt="Snímek obrazovky 2022-05-24 v 14 26 39" src="https://user-images.githubusercontent.com/1878831/170034353-efb760fa-95d9-47a6-873f-f2735f05a72c.png">

I can make PR if you consider this a bug (which I believe it is) and don't have the time to make the fix.

Thank you for your time.
Martin.

**Comment by driesvints** [comment]
I personally don't see a big issue here but you're free to attempt that PR if you like 👍

**Comment by pionl** [comment]
Hey @driesvints what do you mean? This triggers a query on database that is not needed. I see it as a bug right?
