### ISSUE TITLE
Using parameterless WithoutOverlapping makes it impossible to run jobs after single one of them fails

### ISSUE THREAD

**Issue by verybigelephants** [laravel/framework#42497]
- Laravel Version: 9.2.0
- PHP Version: 8.1.5
- Database Driver & Version: pgsql 14.2

### Description:
I have a simple job that dispatches on a specific model `ProcessFile::dispatch($file);` on `database` queue. This job uses such resources in a way that i do not want to have multiple ProcessFile jobs ran at the same time, even if they were dispatched for the different `$file` models.

In order to achieve this i am using WithoutOverlapping like 
```
    public function middleware()
    {
        return [new WithoutOverlapping()];
    }
```
which works.

However, the problem is that when one such job timeout/fails for maximum amount of times, **all** of the future jobs that are dispatched automatically fail, even though they are jobs ran on different models, with error message `App\Jobs\ProcessFile has been attempted too many times or run too long. The job may have previously timed out`

`WithoutOverlapping` probably sets the unique job id to null and Laravel thinks it's the same job and fails them right away.

When i provide a specific id like this `new WithoutOverlapping($this->file->id)` the future dispatched jobs don't fail anymore, but this does not guarantee that two `ProcessFile` jobs won't run concurrently. 

So it's impossible to specify that the same job cannot be run at the same time with `WithoutOverlapping`, without breaking all the other future jobs in case a single one of them fails.

### Steps To Reproduce:
1) Create a job that will do something on a model like
```
<?php

namespace App\Jobs;
use App\Models\File;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\Middleware\WithoutOverlapping;

class ProcessFile implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $deleteWhenMissingModels = true;
    
    public function middleware()
    {
        return [new WithoutOverlapping()];
    }

    protected $file;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(File $file)
    {
        $this->file = $file;
    }
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $this->file->doSomething();
        //sleep(100); //make a single job time out and fail, and all the future jobs will fail too
    }
}

```

2) Make a single job to fail by uncommenting the sleep line (sleep for more seconds than your `config(queue.database.retry_after)`)

3) Comment the line back out and all the future jobs will fail, even though they are different jobs with different files

**Comment by ankurk91** [comment]
https://github.com/laravel/horizon/issues/1075

**Comment by driesvints** [comment]
What you want is unfortunately not possible. You indeed need the unique key to differentiate between the models. They way the key-less `WithoutOverlapping` works is that it's intended to be used with a non-specific payload (common recurring tasks). What you want is to not overlap the job while there's still a specific payload. Right now, I don't see a way of doing that.

**Comment by driesvints** [comment]
@verybigelephants yeah I agree. Can you send in a PR?

**Comment by verybigelephants** [comment]
@driesvints I'm sorry, i'm not exactly sure what you mean, i have never contributed to the Laravel before and i don't want to screw something up:)

Would you like me to make a pull request to the Laravel codebase and rewrite the name of the `WithoutOverlapping`, or find the repository for the documentation, placing the warning in it?

**Comment by garrettboone** [comment]
@driesvints Although it's not related to renaming the function, I recently tried something along these lines here, but didn't get anywhere: https://github.com/laravel/docs/pull/8094

Related question with no guidance: https://github.com/laravel/framework/discussions/43502#discussioncomment-3325161
