### ISSUE TITLE
add support Query\Builder::union methods for PHPStan and Larastan

### ISSUE THREAD

**Issue by fagai** [laravel/framework#42508]
### Discussed in https://github.com/laravel/framework/discussions/42476

<div type='discussions-op-text'>

<sup>Originally posted by **fagai** May 23, 2022</sup>
Hello.

Previously I opened the following PR.
https://github.com/laravel/framework/pull/42374

This was a PR to deal with PHPStan getting an error because there is no Eloquent Builder description in the phpdoc of the query builder union method.

However, this PR was closed due to the contributor's misunderstanding.

I opened a similar PR for Larastan.
This PR was successfully approved.
https://github.com/nunomaduro/larastan/pull/1231

I'm hoping that the PR on the framework side will be merged, but I opened this because I don't know what to do.</div>

The Builder::union method is supports `Illuminate\Database\Eloquent\Builder`, but an error occurs because there is no description.

**Steps to reproduce**

```php
$first = User::where('id',8);

$users = User::where('id',2)->union($first)->get();
```

**Error Report**

```
Parameter #1 $query of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::union() expects Closure|Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder given.
```

**Description**

**`Illuminate\Database\Eloquent\Builder` is not a subtype of `Illuminate\Database\Query\Builder`.**

Illuminate\Database\Eloquent\Builder
```php
use Illuminate\Contracts\Database\Eloquent\Builder as BuilderContract;
class Builder implements BuilderContract
{
```

Illuminate\Database\Query\Builder
```php
use Illuminate\Contracts\Database\Query\Builder as BuilderContract;
class Builder implements BuilderContract
{
```

**Comment by driesvints** [comment]
Please don't move discussions to issues.

**Comment by fagai** [comment]
okay, sorry
