### ISSUE TITLE
unable to access dynamic attributes in new Attribute set method

### ISSUE THREAD

**Issue by pintend** [laravel/framework#42537]
- Laravel Version: 9.14.1
- PHP Version: 8.0.18 & 8.1.5
- Database Driver & Version: DBngin - mysql 8.0.27

### Description:
Dynamic attributes which exist are not always accessible in Attribute set method whereas non existent attributes return null
I'm seeing this specifically when using a callback for groupBy or transform

As well as when using transform i can't access dynamic attributes after my custom Attribute

##### What doesn't work:
```php
Example::all()->transform(fn ($item) => [
    'test' => $item->test,
    'date' => $item->created_at,
]);

Example::all()->groupBy(fn ($item) => $iitem->test->id);
```

##### What sometimes can work:
```php
// Access other attributes first
Example::all()->transform(fn ($item) => [
    'date' => $item->created_at,
    'test' => $item->test,
]);
```

### Steps To Reproduce:
```php
public function test(): Attribute
    {
        return Attribute::make(
            get: function($value, $attributes) {
                return (object) ['id' => 1];
                return 'wont call set if this is returned from';
            },
            set: function($value, $attributes) {
                // Why is this undefined if attribute caching is enabled?
                dd($this->created_at);

                // This dumps null as expected.
                dd($this->something_non_existent);
            }
        );
    }
```

This works as expected
```php
Example::first()->test;
Example::first()->test = 'something';
```

This does not
```php
Example::all()->groupBy(fn ($item) => $item->test->id)
```

During the the loop, the set callback is executed and in tinker I get
```php
...

App\Models\Example {#4447
    ⚠: Symfony\Component\VarDumper\Exception\ThrowingCasterException {#4461
        #message: "Unexpected ErrorException thrown from a caster: Undefined property: App\Models\Example::$created_at",
    },
    +incrementing: true,
    +preventsLazyLoading: false,
    +exists: true,
    +wasRecentlyCreated: false,
    +timestamps: true,
},

...
```

In the browser i get 
```
ErrorException
Undefined property: App\Models\Example::$created_at
```

https://github.com/pintend/bug-report

**Comment by rodrigopedra** [comment]
As a workaround, or maybe it is intended usage, you can access the other attributes on the `$attributes` parameter passed to both closures.

Just out of curiosity, what is your use case for accessing other attributes inside a mutator? in other words, inside a `Attribute`'s `set` callback?

**Comment by pintend** [comment]
The ```$attributes``` array won't contain "virtual" attributes e.g. ```$this->fullName``` and the values are not casted, so created_at is not a carbon instance...

**Comment by driesvints** [comment]
Calling the model through `$this` inside an attribute is not supported.

**Comment by Tofandel** [comment]
@pintend I think it's because of a php limitation, if you are within the __set or __get method and are trying to access another magic property from this PHP doesn't do recursion (I don't actually know if that's the case, but it seems like it could be that)

**Comment by rodrigopedra** [comment]
thanks @Tofandel , I didn't know that. From my testing I guess this is the problem.

**Comment by pintend** [comment]
@Tofandel Makes sense that would be the issue, but why wouldn't it be an issue with the non existent attribute?
