### ISSUE TITLE
whereRaw with Optional Array throws an SQLSTATE[08P01]: <<Unknown error>>

### ISSUE THREAD

**Issue by askdkc** [laravel/framework#42557]
- Laravel Version: 9.14.1
- PHP Version: 8.1.4
- Database Driver & Version: PostgreSQL, PGroonga 2.3.6

### Description:
When using whereRaw to search data in jsonb column on PostgreSQL, passing optional array throws an error.

Using whereRaw without passing optional array works fine.
```
whereRaw('jsonbdata &` \'(paths @ "title" || paths @ "body") && query("string", "cat alice")\''); 

->This works fine.
```

But using whereRaw with optional array throws an error.
```
whereRaw('jsonbdata &` \'(paths @ "title" || paths @ "body") && query("string", "?")\'', ["cat alice"]); 

->This throws "SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR: bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000003" requires 0" error
```

### Steps To Reproduce:

I created a repo to reproduce this error.

https://github.com/askdkc/whereraw_laravel

**Comment by rodrigopedra** [comment]
Can you try using the question mark without quotes? Usually PDO auto quote based on data type, but it maybe need due to being a JSON query.

I don't have PostgreSQL installed to try it out.

~~~php
->whereRaw('jsonbdata &` \'(paths @ "title" || paths @ "body") && query("string", ?)\'', ["cat alice"]); 
~~~

**Comment by askdkc** [comment]
without quotes still causes the same error.

```
Illuminate \ Database \ QueryException                  PHP 8.1.4   Laravel 9.14.1
SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR: bind message supplies 1 parameters, 
but prepared statement "pdo_stmt_00000003" requires 0

select count(*) as aggregate from "posts" where jsonbdata &` '(paths @ "title" || paths @ "body") && query("string", cat alice)'
```

**Comment by taai** [comment]
I'm pretty sure this is a problem with PHP PDO, not Laravel. It appears that [PHP PDO does not consider question mark as a parameter in strings](https://www.php.net/manual/en/pdo.prepare.php#111458) (the part in your raw SQL that is wrapped with single quotes).

To prove the theory - here is a code you can test anywhere without your specific setup (only requirement is PostgreSQL and existing "users" or any other table, of course):

```php
// this will not throw any exception
\DB::table('users')->whereRaw("'cat' = ?", ["cat"])->get();

// this will throw \Illuminate\Database\QueryException
// because the question mark is wrapped in single quotes
\DB::table('users')->whereRaw("'cat' = '?'", ["cat"])->get();
```

In your case I would write the code like this:

```php
$input = 'cat alice';
$query->whereRaw('jsonbdata &` ?', [
    '(paths @ "title" || paths @ "body") && query("string", "'. addslashes($input) .'")'
]);
```

And the code still *should* be safe against SQL injections.

The ```addslashes()``` if just so you can search also for ```cat alice'``` and ```cat alice"```.

The idea came from https://github.com/pgroonga/pgroonga/issues/45

**Comment by driesvints** [comment]
Thanks @taai

**Comment by askdkc** [comment]
Thank you Artisans!

I've been struggling with this all weekend. So grad to see it finally working💓

**Comment by rodrigopedra** [comment]
You can also consider using `PDO::quote` for escaping the value

~~~php
DB::connection()->getPdo()->quote('cat alice');
~~~

reference: https://www.php.net/manual/en/pdo.quote.php
