### ISSUE TITLE
Auth()->user() -> magic vars not available inside scope class

### ISSUE THREAD

**Issue by TakeoO** [laravel/framework#42569]
- Laravel Version: 9.10.1
- PHP Version: 8.1.0
- Database Driver & Version: (un related)

### Description:

I'm creating a multitenant (single DB) system -> I want to add scoped queries to the ORM models (some of them, like Users, Accounts, invoices, etc). When implementing this, there are two problems:
* The auth()->user()->***tenant_id*** is not available during the page refresh (user is logged in)
* First point crashes the app -> and does not return any errors -> 502 Bad Gateway, nginx/1.18.0 (Ubuntu) -> Homestead v13.2.1 

I found out the problem (the missing information inside the identity object) via debugger. 

### Steps To Reproduce:

1. Create an Scope class (in my case) TenantScope
2. Add: 
```
/**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('tenant_id', auth()->user()->tenant_id);
    }

```

4. Use the Scope using Booted function:
```
protected static function booted()
    {
        static::addGlobalScope(new TenantScope());
    }


```
<img width="419" alt="Screenshot 2022-05-30 at 14 41 29" src="https://user-images.githubusercontent.com/8413270/170994539-6f283c8a-506b-4be9-b9f5-a2e8c464b418.png">
<img width="623" alt="Screenshot 2022-05-30 at 14 41 35" src="https://user-images.githubusercontent.com/8413270/170994546-5190a7fe-5051-4c82-80bb-a60b46c20e8b.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
