### ISSUE TITLE
Don't rely on the composer.json file

### ISSUE THREAD

**Issue by bertoost** [laravel/framework#42573]
Hi there,

Just discovered that you rely on the composer.json file which should not.
Because when you deploy your application with as less files you want, you should be able to remove the composer.json file. Therefore composer compiles a couple of autoloading files in it's vendor/composer/ directory. I guess that should be used instead?

https://github.com/laravel/framework/blob/ffc35c59f1b3b8cc0b2316460b3b14780fbbbd51/src/Illuminate/Foundation/Application.php#L1414

Regards, Bert

**Comment by ankurk91** [comment]
I think it is being used for auto package discovery feature

**Comment by driesvints** [comment]
You should never remove your composer.json file from your project and always commit it to git.

**Comment by bertoost** [comment]
@driesvints I do not remove it from git.. but I removed it from deployment to the production environment.. my point here is that the framework should never rely on the composer.json file itself

**Comment by driesvints** [comment]
@bertoost Atm, Laravel relies on this file. We have no plans on changing that.

**Comment by bertoost** [comment]
That kinda sucks! This file should be removable safely for production environments... I have never worked with a framework/application that relies on that file either.
