### ISSUE TITLE
Inconsistent route definition

### ISSUE THREAD

**Issue by daniel-de-wit** [laravel/framework#42579]
- Laravel Version: 9.14.1
- PHP Version: 8.1.0
- Database Driver & Version: MariaDB 10

### Description:
Defining a route fluently is inconsistent for method `view` compared to `get`, `post`, etc.

```php
Route::get()->name();        // Works
Route::name()->get();        // Works

Route::view()->name();       // Works
Route::name()->view();       // Does not work
```

Updating the passthru methods on the RouteRegistrar would solve this issue. 
Is there any reason why this has not been added?

```php
class RouteRegistrar
{
    /**
     * The methods to dynamically pass through to the router.
     *
     * @var string[]
     */
    protected $passthru = [
        'get', 'post', 'put', 'patch', 'delete', 'options', 'any', 'view', // <--- this
    ];
}
```

If not by design, I would gladly submit a PR.

P.s: I know there are more methods, like `redirect`.

**Comment by driesvints** [comment]
`Route::name()->view();` and `Route::name()->get();` are not supported.
