### ISSUE TITLE
Force SerializesAndRestoresModelIdentifiers to use Read PDO

### ISSUE THREAD

**Issue by zek** [laravel/framework#42584]
- Laravel Version: 9.4.0
- PHP Version: 8.1
- Database Driver & Version: mysql 8

### Description:

I have 1 master 2 replica database servers and what I'm trying to reduce load on master database and make sure only write operations done in master db. However queue workers are always restoring `notifiable` from master. 

There is `useWritePdo` in `restoreCollection` and I couldn't find any way to disable it.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/3463291/171164013-2375ed57-cc28-40ce-8446-4f2bb697a810.png">

**Comment by zek** [comment]
@driesvints thanks for the keeping issue not locked.

I guess this is more like a future request than a bug. Can you please move the issue to discussions?

**Comment by driesvints** [comment]
@zek best that you open a new one in discussions.
