### ISSUE TITLE
Database query builder: having() has invalid type hinting

### ISSUE THREAD

**Issue by Maxoulak** [laravel/framework#42589]
- Laravel Version: 9.10.1
- PHP Version: 8.1.5
- Database Driver & Version: MySQL - 5.7

### Description:

Hi everyone !

I've just increased my PHPstan level from 5 to 6, and started encounter this error message :

`Parameter #3 of method Illuminate\Database\Eloquent\Builder<App\Models\Client>::having() expects string|null, int given`.

According to [the method documentation](https://laravel.com/api/9.x/Illuminate/Database/Query/Builder.html#method_having), we can see the same type hinting for parameters `operator` and `value` : `string|null`.
I think it's missing the `int` and `float` types.

Is it possible to type hint `$operator` to `string|float|int|null`, or maybe just `mixed`, and same for `$value` ? (in case we use the `$operator` param for the `$value`) ?

### Steps To Reproduce:

Here is my current code snippet (even if we can reproduce the error with any having clause with `int` or `float` variable as the second or third parameter) :

```php
$clientsIds = Client::selectRaw('COUNT(reservations.id) as aggregate_nb_reservations, clients.id')
                ->join('reservations', 'reservations.client_id', 'clients.id')
                ->join('slots', 'slots.id', 'reservations.slot_id')
                ->join('services', 'services.id', 'slots.service_id')
                ->where('services.restaurant_id', 1)
                ->where('clients.owner_id', 1)
                ->whereNull('clients.status')
                ->where('reservations.status', 'over')
                ->groupBy('reservations.client_id')
                ->having('aggregate_nb_reservations', '>=', 5)
                ->pluck('clients.id');
```
This works fine, but PHPstan doesn't like it.

**Comment by driesvints** [comment]
Heya. Since there is no real bug I'm going to close this. We'd welcome PR's to improve the docblocks.
