### ISSUE TITLE
Folders created for a new file with public permissions are created with private permissions (the resulting file would not accessible publicly)

### ISSUE THREAD

**Issue by hmones** [laravel/framework#42586]
- Laravel Version: 9.11
- PHP Version: 8.1
- Database Driver & Version: NA

### Description:
If the user wants to store a new file (with public permissions) in the storage folder in a path that has folders that do not exist at the time of file creation. Then the folders will be created with private permissions and not public permissions like the file. This will render the file inaccessible.

### Steps To Reproduce:

- Make sure the permissions are stored correctly in `flysystems.php` for public folders `0755` and for private folders `0700`
- Go to tinker and paste this command to create a new file `Storage::put('hello/world/helloworld.txt', 'hello', 'public');` or `Storage::put('hello/world/helloworld.txt', 'hello');`
- Go to the folder `/app/storage/app` and view the permissions for folder `hello`

### Expected Result:

- The folders `hello` and `world` will have 0755 permission (public).

### Actual Result:

- The folders `hello` and `world` will have 0700 permission (private).

**Comment by madalinignisca** [comment]
Have you checked your php configuration? The permissions for new files/directories are respected umask set for the php process. If you want to enforce different behaviour, it will break for everybody who handles file permissions by server configuration. PHP can handle using umask or chmod the permissions, but this is against expectations on many enterprise deployments where umask is controlled by configuration and other linux capabilities.

**Comment by madalinignisca** [comment]
PS, you can set chmod on the file after yourself so you get your exact expectations.

**Comment by driesvints** [comment]
I can confirm there's something off here between Laravel 8 and Laravel 9.

**Comment by driesvints** [comment]
Actually, this is because Flysystem v3 is a bit stricter on directory permissions and has private visibility for directories by default. The files will also still be accessible. I tried that with setting the public storage link and put the directory and the file in the `storage/app/public` directory and I was able to access the file through the web. It doesn't matter if the directory is private.

You can set a separate `'directory_visibility' => 'public',` in your disk config if you want.

**Comment by hmones** [comment]
@driesvints The reason why it worked for you when you tested is that you did everything with the same user, (the default permissions on laravel 9 would work fine, because the owner of the directory can do mostly everything even on private folders created by the same user) which will work by default. In Laravel documentation https://laravel.com/docs/9.x/filesystem#local-files-and-visibility, there's a section for setting the permissions on the desk for private and public folders and files. If you change that in the config (that's what I did) and you try to create a file in a new path e.g. 'storage/app/public/new/folder/test.file' then the newly created folders would take the permission specified for the private directory configuration and not the permission specified for the public directory. 

For my use case, we had that bug right after updating to laravel 9, the system broke with permissions. Our code creates the file inside a job, that is run by the scheduler, and the scheduler is running on root user. On the other hand, the web application is running on www-data. When the file is created by the job that is run by the scheduler it wouldn't be accessible by the web process and can not be download  because it's a different user and that's why the private permissions wouldn't render the public file placed in a private folder accessible. This broke our production environment right after we updated from laravel 8-9. So the bug exist because the behavior is different from laravel 8 by default. However, if you want to really test it you have to create the file from a process that runs by a user that is different from the web user or group. 
To debug the issue, we tried changing the configuration in filesystems.php and add the permissions as recommended by the documentation, but then we realized that all directories are created using the private permission not the public, even though the file is public, which is weird and different than laravel 8. Before in laravel 8, it was not like that, the same system worked on laravel 8 with no issue. 

The way we fixed the bug temporarily was to set the private folder permissions to 0755 too, but we are not able to create then private folders through the app because we altered the permission.

**Comment by driesvints** [comment]
Hey thanks for that detailed explanation @hmones. I do think it's important to let the scheduler run by the same user the app runs on. On Forge, for example, we recommend to use the forge user. Using a different one can lead to unexpected situations like this one.

**Comment by mrm** [comment]
I also ran into the same problem and it took me quite a bit of time to figure out why the directories had the wrong permissions (as I was passing in `public`).

When calling `Storage::put` with the `directory_visibility` it indeed seems to work as intended:
```
Storage::put('hello/world/helloworld.txt', 'hello', [
    'visibility' => 'public',
    'directory_visibility' => 'public'
])
```

Currently in the [FilesystemAdapter](https://github.com/laravel/framework/blob/964c2b468a12338c07527af26a3d4ab2582095cf/src/Illuminate/Filesystem/FilesystemAdapter.php#L334) the `public` parameter is only converted to the file visibility, not new directories:
```
$options = is_string($options)
             ? ['visibility' => $options]
             : (array) $options;
```

@driesvints wouldn't it make sense in that case to also include the `'directory_visibility' => $options` to the array?

Especially when looking at the [docs](https://laravel.com/docs/9.x/filesystem#local-files-and-visibility), there (usually/by default) is no difference between the user permissions for public and private for both files (`6`) and directories (`7`), only for groups (`4`/`5` -> `0`). So by using the `public` visibility you're only changing the group permissions of the file. When new directories for that specific `put()` call have the private group permissions it basically makes the file private for the group even though that's the only difference between `public` and `private`.

Otherwise adding the `directory_visibility` option to the documentation would be helpful, it might save people some time figuring out why the directories have private permissions. 

In any case I'd be happy to create a PR.

**Comment by driesvints** [comment]
We could maybe add the option commented out in the skeleton. I still think private by default is probably the better default.

**Comment by ARehmanMahi** [comment]
@mrm ``` "So by using the public visibility you're only changing the group permissions of the file." ```
I don't think that's what's happening, the `public` visibility changes the file permissions as defined in the permissions array, not just group permissions. so with default settings the file would have 644 for the public.

```
'local' => [
    'driver' => 'local',
    'root' => storage_path('app'),
    'permissions' => [
        'file' => [
            'public' => 0644,
            'private' => 0600,
        ],
        'dir' => [
            'public' => 0755,
            'private' => 0700,
        ],
    ],
],
```

And if you override the array and change the public permissions to be 640 the file would have 640.
The folder permissions don't get affected, it doesn't matter whatever you supply in `directory_visibility`.
Which I think is broken at the flysystem end.

if you set 700 in directory_visibility the folder still gets whatever is set in the public directive of folders; default/overridden whatever.

**Comment by serdarcevher** [comment]
For anyone ending up here because of new folders being created with the 700 permission, this is how I've solved the issue for me:

```
$path = Storage::putFileAs(
    $main_folder . $folder, 
    $file, 
    $filename,
    [
        'visibility' => 'public',
        'directory_visibility' => 'public'
    ]
);
```

**Comment by vitomeuli** [comment]
Same problem on Laravel 10.
The problem is not visible in the dev instance, where Sail uses the same Docker  container for PHP end Nginx. The problem arises on our staging/production instances, where Laradock uses several Docker containers: php-fpm and nginx. As far as I know they should be executed by the same user, I can't explain why such problem arises.

The undocumented feature 'directory_visibility' in Storage::put() solves the problem for me (thanks @serdarcevher )

**Comment by ARehmanMahi** [comment]
@Fossil01 Same bro, 

> "I can set ['visibility' => 'public', 'directory_visibility' => 'public'] as the options that make it work. But this should be fixed or have some info added to the docs."

This destroys the benefits of using `disks` having the default pre-sets in the disk config. 

This is the exact issue I've been facing since 2022 as posted in the above comments.
These directory permissions should work on the disk config level. There still no answer to this problem

**Comment by mirko77** [comment]
2024 and still facing this in Laravel 11...

**Comment by JshGrn** [comment]
Half way through 2025 still facing this issue in Laravel 11, is this project abandoned?

**Comment by bsienn-khan** [comment]
once they close the issue, they become deaf.
Try this in config/filesystem.php

```php
<?php

declare(strict_types=1);

$permissions = [
    'file' => [
        'public' => 0664,
        'private' => 0644,
    ],
    'dir' => [
        'public' => 0775,
        'private' => 0755,
    ],
];

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. The "local" disk, as well as a variety of cloud
    | based disks are available to your application for file storage.
    |
    */

    'default' => env('FILESYSTEM_DISK', 'local'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Below you may configure as many filesystem disks as necessary, and you
    | may even configure multiple disks for the same driver. Examples for
    | most supported storage drivers are configured here for reference.
    |
    | Supported drivers: "local", "ftp", "sftp", "s3"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app/private'),
            'serve' => true,
            'throw' => false,
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
            'permissions' => $permissions,
            'throw' => false,
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Symbolic Links
    |--------------------------------------------------------------------------
    |
    | Here you may configure the symbolic links that will be created when the
    | `storage:link` Artisan command is executed. The array keys should be
    | the locations of the links and the values should be their targets.
    |
    */

    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],

];
```

**Comment by mirko77** [comment]
Still an issue in Laravel 12

We ended up adding a helper method, so we are sure we can update Laravel without breaking things in production.

```

/**
 * Ensure a directory exists and has public visibility on the specified disk.
 *
 * Useful when facing 700 permission errors in testing or production with Laravel's filesystem.
 *
 * @param string $diskName   The configured disk name from config/filesystems.php (e.g. 'local', 's3', etc.)
 * @param string $directory  The relative path to the directory (e.g. project ref or user id folder)
 */
function ensurePublicDirectory(string $diskName, string $directory): void
{
    $disk = Storage::disk($diskName);

    try {
        if (!$disk->exists($directory)) {
            // Create the directory if it doesn't exist
            $disk->makeDirectory($directory);
        }

        // Set visibility to public to avoid 700 permission issues (especially for exported media or thumbnails)
        $disk->setVisibility($directory, 'public');
    } catch (\Throwable $e) {
        // Optional: log the error for debugging
        Log::error("Failed to set up public directory", [
            'disk' => $diskName,
            'directory' => $directory,
            'error' => $e->getMessage(),
        ]);

        // Re-throw or handle based on your app's needs
        throw $e;
    }
}

```
