### ISSUE TITLE
Using `setRelation` before passing model into job causes segmentation fault

### ISSUE THREAD

**Issue by gbradley** [laravel/framework#42598]
- Laravel Version: 9.15.0
- PHP Version: 8.1.5
- Database Driver & Version: Mysql 8.0

### Description:

Under a specific scenario, calling `setRelation()` triggers a segmentation fault.

[gbradley/laravel-segfault](https://github.com/gbradley/laravel-segfault) is simple app where `User`s have many `Post`s. A segmentation fault can be caused by:

- Iterating through a collection of `$user->posts`
- manually setting the post's `user` relation
- dispatching a job with the user (or post) passed into the constructor

I'm guessing this is caused by circular reference ($user->posts followed by $post->user) when serializing the model relationships.

### Steps To Reproduce:

    $ git clone git@github.com:gbradley/laravel-segfault.git
    $ cd laravel-segfault && composer install
    $ php artisan migrate
    $ php artisan breakme

The breakme command simply executes the steps listed above; commenting out line 47 avoids the segmentation fault.

**Comment by rodrigopedra** [comment]
> I'm guessing this is caused by circular reference

Yes, the circular reference is culprit here. As you can see in the comment linked below that dispatching a job with circular references is not supported:

> You should build your job in a way that the circular dependency is not present.

https://github.com/laravel/framework/issues/38614#issuecomment-909141398

**Comment by rodrigopedra** [comment]
In your sample job, you can try the following to avoid the circular reference:

~~~php
public function handle()
{
    // Create a user.
    $user = new User([
        'name'      => 'Foo',
        'email'     => time() . '@example.com',
        'password'  => 'xyz',
    ]);
    $user->save();

    // Create a post.
    $user->posts()->create();

    foreach ($user->posts as $post) {
        // Avoids circular reference
        $post->setRelation('user', $user->unsetRelation('posts'));

        Sample::dispatch($user);
    }
}
~~~

**Comment by gbradley** [comment]
Ah, not sure how I didn't come across that previous issue, thanks.

Preventing the circular reference is easy enough; in my case it was discovering the segfault itself that was the hard part because it didn't crop up in unit tests.

Since this is a known limitation I'll just close the issue.
