### ISSUE TITLE
v9.15 has breaking change in route() helper: Unidentified array key 0

### ISSUE THREAD

**Issue by mortenscheel** [laravel/framework#42605]
- Laravel Version: 9.15.0
- PHP Version: 8.0.18
- Database Driver & Version: MySQL 8.0

### Description:
In v9.15.0 calling the route() helper with model parameters in a non-associative array will result in an ErrorException "Unidentified array key 0" being thrown in Route.php line 539.
I realize that the use of non-associative arrays is no longer documented, but as long as the order of the parameters was correct, it has worked until v9.14.0. 
If there have been any warnings in the upgrade guides that this would happen, I must have missed it. And it's especially unexpected in a minor release.

### Steps To Reproduce:
```php
route('route.name', [$someModel]); // Throws ErrorException
route('route.name', $someModel); // Also worked up until v9.14.0, now it throws ErrorException
```

**Comment by ksassnowski** [comment]
I swear to God, I must have hit every single possible edge case with my initial PR 🙈 

The fix is rather straight forward, but I this behavior is pretty weird to begin with (what does `http://example.com/foo?1` even mean?). Since this is technically a breaking change in a non-major version, we should still fix this, however. I'll send a PR for this shortly.

**Comment by mortenscheel** [comment]
@ksassnowski I completely agree it's a weird edge case. I believe it arose because the model used to be a route param, then the route definition was changed to not include the model, without updating the route() call. Like I said, it flew under the radar because the generated URL worked as expected, even though it had a non-sensical `?1` tagged on.
As always, [xkcd said it best](https://xkcd.com/1172/)

I'll re-open the issue as suggested.

**Comment by ksassnowski** [comment]
The PR already got merged by the way, so you can close the issue again 😅 #42606
