### ISSUE TITLE
TypeError: Illuminate\Mail\PendingMail::send(): Argument #1 ($mailable) must be of type Illuminate\Contracts\Mail\Mailable, string given

### ISSUE THREAD

**Issue by systemsolutionweb** [laravel/framework#42607]
- Laravel Version: 8.x Latest
- PHP Version: 8.1
- Database Driver & Version: MariaDB

### Description:

When i try to send a mail using a view inside a Job doesn't work, on sync works

### Steps To Reproduce:
This code works,
```php
\Mail::send('mails.emergency_call', [], function ($message) {
    $message->to('my_email@email.com', 'Email Example');
});
```
but if you put the same code inside of handle method on a Job and when i call `dispatch` i get 
```
Illuminate\Mail\PendingMail::send(): Argument #1 ($mailable) must be of type Illuminate\Contracts\Mail\Mailable, 
string given, called in /var/www/app/Jobs/SendView.php on line 52
{"exception":"[object] (TypeError(code: 0): Illuminate\\Mail\\PendingMail::send(): 
Argument #1 ($mailable) must be of type Illuminate\\Contracts\\Mail\\Mailable, 
string given, called in /var/www/app/Jobs/SendView.php on line 52 
at /var/www/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php:122)
[stacktrace]
#0 /var/www/app/Jobs/SendView.php(52): Illuminate\\Mail\\PendingMail->send('mails.emergency_call.', Array, Object(Closure))
```
```php
class SendView implements ShouldQueue{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    
    public function __construct(){
         $this->onConnection('database');
    }
    public function handle(){
        \Mail::send('mails.emergency_call', [], function ($message) {
            $message->to('my_email@email.com', 'Email Example');
        });
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by fredsal** [comment]
@driesvints looks like a bug to me
