### ISSUE TITLE
latestOfMany() slow with group by on full table

### ISSUE THREAD

**Issue by zKoz210** [laravel/framework#42621]
- Laravel Version: [v9.15.0](https://github.com/laravel/framework/releases/tag/v9.15.0)
- PHP Version: 8.1
- Database Driver & Version: PostgreSQL 14.2

### Description:

I am using latestOfMany() to get the latest status of an entity. One-to-many relationship.

### Steps To Reproduce:
`reception_signs`
| ID  | NAME |
| ------------- | ------------- |
| 1  | test_receptions  |

`reception_statuses`
| ID  | NAME | RECEPTION_ID
| ------------- | ------------- | ------------- |
| 1  | none  | 1
| 2  | is_progress  | 1
| 3  | confirmed  | 1

reception relation
```
    public function lastStatus(): HasOne
    {
        return $this->hasOne(ReceptionStatus::class, 'reception_id')->latestOfMany();
    }
```

MY HACK only for whereHas()
```
    public function customLastStatus(): HasOne
    {
        return $this->hasOne(ReceptionStatus::class, 'reception_id')
            ->ofMany(
                ['id' => 'MAX'],
                function ($q) {
                    $q->whereRaw('"reception_signs"."id" = "reception_statuses"."reception_id"');
                }
            );
    }
```

Tests were carried out on reception - 600.000, receptions_statuses - 2.000.000

```
ReceptionSings::whereHas('lastStatus', fn ($q) => $q->whereStatus(ReceptionStatus::CONFIRMED))->get();
```

![image](https://user-images.githubusercontent.com/30200168/171474211-a13a7dd4-b58b-4201-8721-c4a35dc9cd6f.png)

```
ReceptionSings::whereHas('customLastStatus', fn ($q) => $q->whereStatus(ReceptionStatus::CONFIRMED))->get();
```
![image](https://user-images.githubusercontent.com/30200168/171474283-dc256710-e804-43ee-a0c0-248f4a0b4978.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by zKoz210** [comment]
@driesvints it is a bug with query performance. we do unnecessary actions and cause the degradation of the speed of the sql query

We do a SELECT sorted by MAX("ID") on all records, even those that are not in the current query.

**Comment by driesvints** [comment]
This seems more like an app optimization to me than a real performance issue. For example, I don't see why reception_statuses needs to be a table. That could be constants or an enum.

**Comment by zKoz210** [comment]
@driesvints for logging statuses and how the flow changed

**Comment by driesvints** [comment]
I think in this case, you want to avoid latestOfMany and build a separate query that's more performant for your use case. I don't see a different way in which latestOfMany can be implemented. It's most likely not intended to be used with so many records involved.
