### ISSUE TITLE
Console Commands only accept One Array Argument/Options

### ISSUE THREAD

**Issue by mpoma** [laravel/framework#42625]
- Laravel Version: 8.83.7
- PHP Version: 8.1.5
- Database Driver & Version: Mysql 8

You create an Artisan Console command, with two or more options array like
'mail:send {--id=*} {--client=*}' 

When you used it, 
php artisan mail:send --id=3 --id=5 --id=6 --client=8 --client=9

them the client array is empty. 
Like
options=>[
id=>[3,5,6],
client=>[]
]

If you dont use --id option in the command line, the client array has values.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
