### ISSUE TITLE
Mail::fake() returns null when using send()

### ISSUE THREAD

**Issue by yob-yob** [laravel/framework#42638]
- Laravel Version: `9.15.0`
- PHP Version: `8.1.4`
- Database Driver & Version: `I don't think it's important in this issue`

### Description:

When using `Mail::fake()` then sending an email using `Mail::to($this->email)->send(new MemberInvitation($data))`, it does not return `\Illuminate\Mail\SentMessage` rather it return `null`.

this should be considered as a Bug because `Mail::assertSent(MemberInvitation::class)` does not fail... 

why should it fail? **see steps to reproduce section**

### Steps To Reproduce:

here's a test case instead of github repo

```php
/** @test */
public function replicate_bug_error() 
{
    // Arrange 
    Mail::fake();

    $mailable = new class() extends Mailable {};

    // Act (can be a model action or something)
    $sent = Mail::to('text@example.com')->send($mailable);
    $hasDoneSomethingOnDB = false;

    if ($sent) {
      // should modify something on the database only if mail was sent...
      $hasDoneSomethingOnDB = true;
    }

    // Assert 
    Mail::assertSent($mailable::class);
    $this->assertTrue($hasDoneSomethingOnDB, "Mail was not sent");
}
```

the test case above has contradicting assertions... First `Mail::assertSent($mailable::class);` did not fail... but when I checked that `$hasDoneSomethingOnDB ` is `true` it failed...

imagine if `$hasDoneSomethingOnDB` is something you do on the database only if the mail was sent, then you would have no idea what is going on because your code is working properly on the browser but fails when testing on PhpUnit...

This would also raise issues when testing for `Mail::assertNotSent()` because now... this test is passing... but for the wrong reasons...

Say we have 2 mailers... 1 should only be sent on specific criteria,

```php
/** @test */
public function replicate_bug_error() 
{
    // Arrange 
    Mail::fake();

    $mailable = new class() extends Mailable {};
    $mailable2 = new class() extends Mailable {};

    // Act (can be a model action or something)
    $sent = Mail::to('text@example.com')->send($mailable2);
    $hasDoneSomethingOnDB = false;

    if ($sent) {
      // should modify something on the database only if mail was sent...
      $hasDoneSomethingOnDB = true;
    }

    // Assert 
    Mail::assertNotSent($mailable::class);
    // $hasDoneSomethingOnDB is false even if $mailable2 is sent (this line should fail!)
    $this->assertFalse($hasDoneSomethingOnDB, "Mail was not sent");
}
```

### Temporary fix

You can check your environment on the `if statement`, but this is not something you really want as fix, honestly...

```php
if ($sent || app()->environment() === 'testing') {
  $mailSent = true;
}
```

**Comment by driesvints** [comment]
Heya, this is expected. If you fake an email send, there's nothing to send and thus there's no sent message. If you rely on the behavior of sending an email. You should choose something like the array transport for your tests.
