### ISSUE TITLE
Pluck does not return expected result

### ISSUE THREAD

**Issue by mah484** [laravel/framework#42653]
- Laravel Version:  9.14.1
- PHP Version: 8.1.2
- Database Driver & Version: MariaDB 10.3.32

### Description:
Running the code in the [documentation](https://laravel.com/docs/9.x/collections#method-pluck) for the `pluck` method of collections, you actually get an array within an array.  So for the third example, using dot notation, the return value is `[['Rosa','Judith']]` and not `['Rosa','Judith']`.

If I do not add the wrapping array like so, pluck returns nothing, which doesn't seem like the expected behavior.

```
        $collection = collect([
            'speakers' => [
                'first_day' => ['Rosa', 'Judith'],
                'second_day' => ['Angela', 'Kathleen'],
            ],
        ]);
```

### Steps To Reproduce:
Run the code sample in the documentation.

**Comment by magnusvinsjevik** [comment]
That is expected result.

If you read the whole documentation you see that this is expected result:

```php
$collection = collect([
    [
        'speakers' => [
            'first_day' => ['Rosa', 'Judith'],
            'second_day' => ['Angela', 'Kathleen'],
        ],
    ],
]);
 
$plucked = $collection->pluck('speakers.first_day');
 
$plucked->all();
 
// ['Rosa', 'Judith']
```
The documentation could be more clear on that section, and may not have been noticed since it only has one "first_day" and the array only contains one item.

The documentation should display: (showing this may also be wrong since $collection['speakers']['first_day'] will return ['Rosa', 'Judith'])
```php
// [['Desk', 'Chair']]
```

```php
$collection = collect([
    ['product_id' => 'prod-100', 'name' => 'Desk'],
    ['product_id' => 'prod-200', 'name' => 'Chair'],
]);
 
$plucked = $collection->pluck('name');
 
$plucked->all();
 
// ['Desk', 'Chair']
```
Desk and Chair is returned since it is "nested" array with single values.

We can take your example like this:
```php
$collection = collect([
	'speakers 1' => [
		'first_day' => ['Rosa 1', 'Judith 1'],
		'second_day' => ['Angela', 'Kathleen'],
	],
	'speakers 2' => [
		'first_day' => ['Rosa 2', 'Judith 2'],
		'second_day' => ['Angela', 'Kathleen'],
	],
	'speakers 3' => [
		'first_day' => 'Rosa 3',
		'second_day' => ['Angela', 'Kathleen'],
	],
]);

$plucked = $collection->pluck('first_day');

// [['Rosa 1', 'Judith 1'], ['Rosa 2', 'Judith 2'], 'Rosa 3']
```
You may flat the result to get single array as you want:
```php
$plucked_flat = $collection->pluck('first_day')->flatten();

// ['Rosa 1', 'Judith 1', 'Rosa 2', 'Judith 2', 'Rosa 3']
```

**Comment by mah484** [comment]
I see what you are saying.  I guess there are two confusing parts.  First to clarify, my only concern/confusion here is using the `pluck()` method _in conjunction with dot notation_.  All other examples of `pluck()` make sense and return what I would expect to be the result.

The first confusing part is that indicating `['Rosa', 'Judith']` as the return value of plucking with the dot notation, in the documentation, when the actual value is `[['Rosa', 'Judith']]` causes confusion in how to expect `pluck()` to work in this case with nested keys (almost like `config()` would work with dot notation).

I am not clear however on your reference to `$collection['speakers']['first_day']` because neither of the follow examples are valid.

```
        $collection = collect([
            [
                'speakers' => [
                    'first_day' => ['Rosa', 'Judith'],
                    'second_day' => ['Angela', 'Kathleen'],
                ],
            ],
        ])->toArray();

        $collection['speakers']['first_day'];
```

or

```
        $collection = collect([
            [
                'speakers' => [
                    'first_day' => ['Rosa', 'Judith'],
                    'second_day' => ['Angela', 'Kathleen'],
                ],
            ],
        ]);

        $collection['speakers']['first_day'];
```

For this reason, I think there is definitely an issue in the documentation then.  However, I can see that the following example would work work as expected according to your response, and provides a little more clarity.

```
        $collection = collect([
            [
                'speakers' => [
                    'first_day' => ['Rosa', 'Judith'],
                    'second_day' => ['Angela', 'Kathleen'],
                ],
                'attendees' => [
                    'first_day' => ['George', 'Bill'],
                    'second_day' => ['David', 'Melissa'],
                ],
            ],
            [
                'speakers' => [
                    'first_day' => ['Dwight', 'Brittany'],
                    'second_day' => ['Frank', 'Jessica'],
                ],
                'attendees' => [
                    'first_day' => ['William', 'John'],
                    'second_day' => ['Ingrid', 'Jack'],
                ],
            ]
        ]);

        $plucked = $collection->pluck('speakers.first_day');

        $plucked->all();
        // [['Rosa', 'Judith'], ['Dwight', 'Brittany']]
```

The second, and this I believe is my misunderstanding and perhaps then a feature request, is that maybe there should be a similar method for retrieving nested values from a _keyed_ collection since the dot notation is very useful for this situation in particular and seems intuitive to use this way.  That is why updating the documentation at least to indicate the real value would be very helpful.  Just a quick example (and I acknowledge calling `->all()` for the string is a bit confusing in implementation here).

```
        $collection = collect([
            'key1' => [
                'product_id' => 'prod-100',
                'name' => 'Desk'
            ],
            'key2' => [
                'product_id' => 'prod-200',
                'name' => 'Chair'
            ],
        ]);

        $plucked = $collection->pluck('key1.product_id');

        $plucked->all();
        // prod-100
```

Unfortunately, it seems I cannot comment without closing this issue, so hopefully this gets seen.  Appreciate the clarification nonetheless.

**Comment by mah484** [comment]
I can reopen it seems, so will try in the hopes that my response is valuable.

**Comment by driesvints** [comment]
Heya, it seems you're correct. However, I feel like we can't change this behavior now as it'd be a breaking change to many users who are using it now. I've sent in a PR to document the current behavior: https://github.com/laravel/docs/pull/7974
