### ISSUE TITLE
Eloquent enum casting: toArray throws exception when overriding getEnumCastableAttributeValue

### ISSUE THREAD

**Issue by henzeb** [laravel/framework#42658]
- Laravel Version: 9.16.0
- PHP Version: 8.1.6
- Database Driver & Version: -

### Description:
I have been trying to get basic enumerations to work for a package of mine, but I keep hitting walls (also see #42648)
When trying to use getEnumCastableAttributeValue / setEnumCastableAttribute this works perfectly, but when using toArray after setting a basic enum value, UnitEnum instance that is, it is casting it back in to an enum and is trying to use it's value property, on line 301 in HasAttributes.

### Steps To Reproduce:
just clone and install https://github.com/henzeb/laravelCastbug

then run ./artisan test:bug

You can find the code in the standard User.php model, \App\MyUnitEnum enum and in \App\Console\Commands\testBugCommand.

**Comment by rodrigopedra** [comment]
@henzeb I sent a new comment to the discussion #42648  that might help you out with your package

Check it out: https://github.com/laravel/framework/discussions/42648#discussioncomment-2881040

**Comment by driesvints** [comment]
Seems this is a Symfony issue. Please don't upgrade to Symfony v6.1 for now and wait until they release a patch release.

**Comment by driesvints** [comment]
ah sorry, we received tons of issues about a symfony breakage and thought this one was one as well. There's no bug here though. The behavior you mentioned isn't supported. Please see Rodrigo's comment.

**Comment by henzeb** [comment]
Alrighty then. Workaround with checking where the method is called and return anonymous class with value when needed it is then....
