### ISSUE TITLE
Pluck collection method not working as expected

### ISSUE THREAD

**Issue by 008anas** [laravel/framework#42673]
- Laravel Version: 9
- PHP Version: 8.1.5

[https://laravel.com/docs/9.x/collections#method-pluck](url)

**Pluck method not returning the same result as example in documentation**

With this code:

`$collection = collect([
            ['product_id' => 'prod-100', 'name' => 'Desk'],
            ['product_id' => 'prod-200', 'name' => 'Chair'],
        ]);

        $plucked = $collection->pluck('name', 'product_id');

        $plucked->dd();`

I get:

```
^ array:2 [
  "prod-100" => "Desk"
  "prod-200" => "Chair"
]
```

While in documentation:

`// ['prod-100' => 'Desk', 'prod-200' => 'Chair']`

**Comment by eusonlito** [comment]
```php
array:2 [
  "prod-100" => "Desk"
  "prod-200" => "Chair"
]
```
Is the same as:
```php
['prod-100' => 'Desk', 'prod-200' => 'Chair']
```
Or formatted:
```
[
    'prod-100' => 'Desk',
    'prod-200' => 'Chair'
]
```
