### ISSUE TITLE
BinaryFileResponse content corruption under nginx on Azure app service (Linux)

### ISSUE THREAD

**Issue by aokrasavin** [laravel/framework#42685]
- Laravel Version: 9.10.1
- PHP Version: 8.0.17 (cli) (built: Mar 25 2022 18:59:25) ( NTS )
- Database Driver & Version: N/A (not used, not relevant to this issue)

### Description:
A fairly simple controller which picks form input, chooses image from the disk and then returns it to webbrowser. Eg

      $img = .... <get data object describing image>

        $response = response()->file(Storage::disk('public')->path($img->filename));
        $response->headers->set('Content-Type', $img->mime);
        $response->headers->set("Cache-Control", "max-age=86400");
        return $response;
    
The code works absolutely perfectly on local development instance of Laravel (Windows 10), but corrupts data when deployed on Azure PHP App Service  on Linux.

I could confirm from debug that the file exists, could be read and contains correct data.

However, when the data arrives to web browser, it is corrupted in  a particular way:
1. All headers are delivered correctly with code 200
2. The binary payload for actual image have first 117 bytes stripped out. Eg after the headers, the binary data starts at byte 118, where byte 0 should have been. The rest of the bytes arrive correctly and at the end there are 117 empty bytes (eg 0x00), so the total size is correct.
3. I have attached an example - the image as expected and the image as delivered
4. The rest of the application works correctly (Json responses, etc), but any functionality relying on BinaryFileResponse is broken
5. The issues exists for any files (not just images), for different types of images, for different security (eg HTTP or HTTPS)
6. The amount of bytes missing at start seems to be always the same and unrelated to image content (eg no magic byte sequence)
7. The rest of the (fairly complciated) app funcitonality works perfectly - no issues
8. There is no magical numerology - the numbers of bytes missed seemingly do not correlate with anything (I wish)

### Steps To Reproduce:

Run the same code under Windows 10 and under Azure App Service on Linux for PHP 8.0. Below are attached two images - the image stored locally and the image as delivered.

<img width="80" alt="logo 5 good" src="https://user-images.githubusercontent.com/54442217/172258194-9c888fb4-6543-4648-b097-6ceb5fce4fa8.png">

![logo 5 bad](https://user-images.githubusercontent.com/54442217/172258214-12490c51-6769-43b7-a2ae-ca0b507bea2b.png)

### Fix

After lots of headscratching, I found a work around in Symfony code, HOWEVER the problem is not happening in "vanilla" PHP app using Symfony, so I suspect there is a problem with the way Laravel and Symfony interact.

The problem code is this one

_namespace Symfony\Component\HttpFoundation;
......
class BinaryFileResponse extends Response
.....
    public function sendContent(): static
{
......
   **stream_copy_to_stream($file, $out, $this->maxlen, $this->offset);**
......
}_

to fix, I implemented the following - eg PHP native function stream_copy_to_stream is replaced with a custom function, which does (as far as I could tell) the same thing (I have Ranges disabled globally, hence always serve the entire file).

_**function pipe_streams($in, $out)
    {
        $size = 0;
        while (!feof($in)) $size += fwrite($out,fread($in,8192));
        return $size;
    }**

    public function sendContent(): static
{
......
   **$this->pipe_streams($file, $out);**
......
}_

**Comment by rodrigopedra** [comment]
Can you try the workaround suggested here: https://github.com/laravel/framework/issues/42681#issuecomment-1147625966

**Comment by LrMiLoef** [comment]
I have also the same issue. By adding the workaround method **_function pipe_streams($in, $out)** the response works fine. Are there any news about this topic?

**Comment by LrMiLoef** [comment]
I'm running the laravel application in an kubernetes environment in the azure cloud. 
i mounted an azure persistent storage to the pod.
Now i'd like to return an image that's located on in the mounted folder like this:

`return response()->file('/mnt/test.png');`

this will result an corrupted image:

![image](https://user-images.githubusercontent.com/14238642/180419725-596ecf09-ac0a-4bd4-8a0c-251432975f6f.png)

now i copy the image via `cp /mnt/test.png /var/www/html/public/test.png` to the public folder of my laravel application. then i return the image from that source. Now it works totally fine. 

Only from the mounted folder it doesn't work. In my local dev environment i'm using a kubernetes cluster running on my machine. there i also mounted a folder to the pod, but in this case i'm using a local folder on my machine, not the azure storage. When i now try to return the image, everything works as expected. 

as i mentioned before: by overriding the stream_copy_to_stream method with the pipe_streams logic, it works with azure. 

any ideas here?

**Comment by klodoma** [comment]
I am having a similar issue, some details here:
https://stackoverflow.com/questions/73280423/php-readfile-content-corruption-on-azure-web-applinux

**Comment by aokrasavin** [comment]
> I am having a similar issue, some details here: https://stackoverflow.com/questions/73280423/php-readfile-content-corruption-on-azure-web-applinux

It is a different manifestation of the same issue. I raised a ticket with Azure.

**Comment by klodoma** [comment]
Yeah, just found the same azure link. Thanks for the update. 

It seems the `stream_copy_to_stream` function to be the problem.
