### ISSUE TITLE
GetChanges() on model fails when data stored in MySQL json type

### ISSUE THREAD

**Issue by sfilzek** [laravel/framework#42691]
- Laravel Version: 9.16.0
- PHP Version: PHP 8.1.3
- Database Driver & Version: MySQL 5.7.24

### Description:
When updating a model which uses a mysql json column, the getChanges() call on the model always returns the json data as having changed even when it has not.

I believe this is because mysql re-orders the json data so that keys are sorted from shortest to longest and then alphabetically, and this causes the comparison to fail in Illuminate\Database\Eloquent\Concerns\HasAttributes where originalIsEquivalent() using castAttribute() performs an === equivalence check to see if the two arrays match. Even if the arrays contain the same data, if the keys have a different order then the test fails.

I'm not sure if this is just a mysql thing or if other databases also mess with the order of the stored json data.

## Model
```
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JsonTest extends Model
{
    public $timestamps = false;
    protected $casts = [
        'sample_data' => 'array',
    ];    
}
```
## Migration
```
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('json_tests', function (Blueprint $table) {
            $table->increments('id');
            $table->json('sample_data');
        });
    }
};
```
## Test
```
$sampleData = [
    'aa' => 1, // Note the ordering.
    'b' => 2   // Mysql will reorder this element to be first
];

$jsonTest = new App\Models\JsonTest;
$jsonTest->sample_data = $sampleData;
$jsonTest->save();

$jsonTest2 = App\Models\JsonTest::find(1);

$jsonTest2->sample_data = $sampleData;
$jsonTest2->save();
dump($jsonTest2->getChanges());
```

This will output:
```
[
    "sample_data" => "{"aa":1,"b":2}",
]
```

**Comment by eusonlito** [comment]
Same with PostgreSQL, but PostgreSQL store data as binary, then you can not know how a JSON will be returned. Only array order is preserved on store.

**Comment by hmennen90** [comment]
@sfilzek @eusonlito I've opened a PR after your Steps to Reproduce - the getChanges() Array is empty as expected. (SQLite)

Additionally I will setup tests using PostgreSQL and MYSQL too.

**Comment by hmennen90** [comment]
Testing at MySQL, i can confirm this.

**Comment by hmennen90** [comment]
![Bildschirmfoto 2022-06-08 um 08 21 33](https://user-images.githubusercontent.com/77828605/172545983-e9e3f903-b7a3-4163-b69d-18c502ec7557.png)

I can only confirm this on MySQL - the Postgres SQL and SQLite Tests are successful expecting and getting empty arrays

**Comment by driesvints** [comment]
It seems that right now, we're not looking into fixing this. We'd appreciate a PR to the docs if you're willing. Thanks

**Comment by hmennen90** [comment]
@driesvints I would like to do that - how can i do this?

**Comment by driesvints** [comment]
Here's the repo: https://github.com/laravel/docs
