### ISSUE TITLE
Route generation broken

### ISSUE THREAD

**Issue by mrmonat** [laravel/framework#42707]
- Laravel Version: 9.17.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8.0

### Description:
When updating to Laravel > 9.13 route generation breaks.
I tested with 9.14, 9.15, 9.16 and 9.17.
I think the bug got introduced by #42425 

### Steps To Reproduce:

Route in web.php:
```PHP
Route::group([
    'prefix' => 'extranet',
    'as' => 'extranet.',
    'middleware' => 'auth',
], function () {
    Route::get('gallery/{folder:slug}/albums', [GalleryFolderAlbumsController::class, 'index'])->name('gallery-folders.albums.index');
});
```

Laravel v9.13 (correct behaviour):
```PHP
dd(route('extranet.gallery-folders.albums.index', $folder)); // -> http://localhost/de/extranet/gallery/aut-neque-dicta-qui-possimus-porro-sit-vel-iusto-voluptatem-quia-ut-excepturi-quaerat-labore-nobis-nesciunt-id-alias-voluptas-voluptatem/albums
```

Laravel v9.17 (wrong behaviour):
```PHP
dd(route('extranet.gallery-folders.albums.index', $folder)); // -> http://localhost/de/extranet/gallery/1/albums
```

**Comment by driesvints** [comment]
@ksassnowski

**Comment by driesvints** [comment]
Although it would seem odd that a model's route key suddenly isn't used here anymore. Please share your Folder model?

**Comment by mrmonat** [comment]
```PHP
class GalleryFolder extends Model
{
    protected $fillable = [
        'title',
        'slug',
    ];

    public function albums(): HasMany
    {
        return $this->hasMany(GalleryAlbum::class);
    }

    public static function booted()
    {
        static::deleting(function (GalleryFolder $galleryFolder) {
            $galleryFolder->albums->each->delete();
        });
    }
}
```

**Comment by driesvints** [comment]
@ksassnowski thinking it might be best to just revert everything to the original code as more problems keep popping up here.

**Comment by driesvints** [comment]
@mrmonat you're sure you're on the latest Laravel version? Can you provide a repo with a fresh laravel install that reproduces this issue?

**Comment by mrmonat** [comment]
I found that it works in a fresh installation, but I found out that the problem only occurs when `URL::defaults(...)` is used:

```PHP
    public function test_routing_without_defaults() // passes
    {
        $url = new UrlGenerator(
            $routes = new RouteCollection,
            Request::create('http://www.foo.com/')
        );

        $route = new Route(['GET'], 'posts/{post:slug}', ['as' => 'routable']);
        $routes->add($route);

        $post = Post::create(['title' => 'Test title', 'slug' => 'test-slug']);

        $this->assertSame('/posts/test-slug', $url->route('routable', $post, false));
        $this->assertSame('/posts/test-slug', $url->route('routable', ['post' => $post], false));
        $this->assertSame('/posts/test-slug', $url->route('routable', [$post], false));
    }

    public function test_routing_with_defaults() // does not pass
    {
        $url = new UrlGenerator(
            $routes = new RouteCollection,
            Request::create('http://www.foo.com/')
        );

        $url->defaults(['locale' => 'de']); // URL::defaults(['locale' => 'de']);

        $route = new Route(['GET'], '{locale}/posts/{post:slug}', ['as' => 'routable']);
        $routes->add($route);

        $post = Post::create(['title' => 'Test title', 'slug' => 'test-slug']);

        $this->assertSame('/de/posts/test-slug', $url->route('routable', $post, false));
        $this->assertSame('/de/posts/test-slug', $url->route('routable', ['post' => $post], false));
        $this->assertSame('/de/posts/test-slug', $url->route('routable', [$post], false));
    }
```

Output of the failing test:
```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/de/posts/test-slug'
+'/de/posts/1'
```

**Comment by driesvints** [comment]
It's not meant to use the url generator like that. Is this reproducable with an example from the docs?

https://laravel.com/docs/9.x/urls#default-values

**Comment by ksassnowski** [comment]
I think that that test case actually demonstrates the bug. The `locale` parameter gets correctly replaced with the default value, but the lookup for the binding field fails because it tries to look up the binding field for the `post` parameter by index. The `parameters` property now contains two parameters, however:  `locale` and `post`. So it erroneously looks up the `locale` instead and falls back to the `getRouteKey` method for the model.

I think we should revert the original changes for now since there seem to be a million different places that got affected by this change. Maybe we can keep the added tests around, so we don't lose that information?

**Comment by mrmonat** [comment]
The use of ```$url->defaults(...)``` is just needed for this test case, I took it from https://github.com/laravel/framework/blob/9.x/tests/Routing/RoutingUrlGeneratorTest.php#L240 

In the real app `URL::defaults()`is called inside a middleware like described in the docs. But as soon as ```defaults``` are used, the route generation breaks. 

Repo with tests:
https://github.com/mrmonat/route-test

**Comment by driesvints** [comment]
> Maybe we can keep the added tests around, so we don't lose that information?

Yes definitely. And if we can probably add a test for this case as well.

**Comment by ksassnowski** [comment]
The only thing that needs to be reset in that case is the `bindingFieldFor` method of the `Route` class. I did already revert all the other changes in one of the follow-up PRs. Just as a heads up, the test case for the bug that I initially tried to solve in #42425 will start failing. The test case that reproduces this ticket would look like this

```php
// tests/Routing/RoutingUrlGeneratorTest.php

public function testRoutableInterfaceRoutingWithUrlDefaults()
{
    $url = new UrlGenerator(
        $routes = new RouteCollection,
        Request::create('http://www.foo.com/')
    );

    $url->defaults(['locale' => 'foo']);
    $route = new Route(['GET'], '{locale}/bar/{baz:slug}', ['as' => 'routable']);
    $routes->add($route);

    $model = new RoutableInterfaceStub;
    $model->key = 'routable';

    $this->assertSame('/foo/bar/test-slug', $url->route('routable', $model, false));
    $this->assertSame('/foo/bar/test-slug', $url->route('routable', [$model], false));
    $this->assertSame('/foo/bar/test-slug', $url->route('routable', ['baz' => $model], false));
}
```

**Comment by bretto36** [comment]
Am also encountering this bug. We will revert to 9.12 for now which seems to work

**Comment by driesvints** [comment]
Can anyone provide me with a repo that produces this?

```bash
laravel new bug-report --github="--public"
```

**Comment by mateusjunges** [comment]
Hey @driesvints I was able to reproduce the issue in this repo:

https://github.com/mateusjunges/laravel-bug-report-42707

Steps to run the project:
- Clone the repo
- Create a database and configure your .env
- Run `php artisan migrate --seed`
- Start the server with `php artisan serve`
- Open your browser and go to `http://localhost:8000`

Hope it helps

**Comment by driesvints** [comment]
I can confirm this bug. Will investigate.

**Comment by driesvints** [comment]
Trying to find a solution before rolling back. But it's proving difficult...

**Comment by ksassnowski** [comment]
Yeah, this one also had me stumped 😞

**Comment by driesvints** [comment]
I finally found a potential fix. Dug deep into this one 😅 

@mateusjunges @mrmonat can you both try it out? https://github.com/laravel/framework/pull/42942

**Comment by mateusjunges** [comment]
@driesvints I've tried it locally and everything works fine now

**Comment by driesvints** [comment]
We had to revert the fix for this. 

@ksassnowski next week I'm going to look into reverting all code related to the original PR by you. There's been too many breakages unfortunately. I think for now, we're going to consider https://github.com/laravel/framework/pull/42425 as a no-fix.
