### ISSUE TITLE
Validator always gets array, not object from json input

### ISSUE THREAD

**Issue by NicoHood** [laravel/framework#42719]
- Laravel Version: v9.15.0
- PHP Version: 8.1.x
- Database Driver & Version: sqlite

### Description:
Hi! I want to write a simple validation rule that requires to only accepts json dicts `{ "example": 42}` rather than json arrays `[ "example" ]`. I've noticed, that I will always get a `$value` of type `array`, never an object:

```php
$rules = [
    'myjsonattribute' => ['array', 'present',
                function ($attribute, $value, $fail) {
                    $fail('You can see that {} will be converted to: ' . json_encode($value));
                }]
]
```

When I input an empty object `{}` you can see that the error message will show it as `[]`. Of course this error message is just for debugging.

Edit: It seems to be always the case, so there is no effective way to tell if an empty array or object is received at all. Also this gets converted wrong from `{}` to `[]` inside the database, meaning **I am unable to ever save `{}`, as it will always be converted**. That does not sound correct to me.

Can someone please give me more insides?

**Comment by NicoHood** [comment]
I could imaging, that this is the place, where the error is generated:
```
./vendor/laravel/framework/src/Illuminate/Http/Request.php:            $this->json = new ParameterBag((array) json_decode($this->getContent(), true));
```

The `true` parameter destroys the type, as it always outputs an associative array. Why?

**Comment by rasha-mt** [comment]
Hi,
json_encode() will always return [] if array is empty, to solve this issue you can use only  json_encode($value,JSON_FORCE_OBJECT)
and it will be solved
[https://stackoverflow.com/questions/28189390/json-encode-function-not-return-braces-when-array-is-empty-in-php](url)

**Comment by NicoHood** [comment]
It will not encode to `[]` if the `true` parameter was not used. If i start using `JSON_FORCE_OBJECT` I cannot differenciate between arrays and objects.

[`json_encode(json_decode ("{}")` results in `"{}"`, which is also correct.](https://stackoverflow.com/questions/62544764/is-it-okay-to-represent-json-and-as-different-values-in-php)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by NicoHood** [comment]
This is not a question, to me this sounds like a bug. You will never be able to differenciate between arrays and dicts in laravel. This makes no sense to me and sounds like a poor limitation. Could you please review this once more?

**Comment by NicoHood** [comment]
I tracked down the issue to very old laravel4. It seems that when initially commiting this, nobody thought of this usecase and limitation. I'd love to reopen the discussion to add support for objects.
https://github.com/laravel/framework/commit/cd9fcd06b3970641e91d6127b31b39fc239521e2
