### ISSUE TITLE
PHP 8.1 - Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by oktaykalfa** [laravel/framework#42720]
- Laravel Version: 8.83.14
- PHP Version: 8.1.6
- Database Driver & Version:

### Description:

Hello, 

Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated
/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php in League\Flysystem\AwsS3v3\AwsS3Adapter::setPathPrefix at line 537

![phpstorm64_EhcLrs124S](https://user-images.githubusercontent.com/47442988/172709281-39da9fcc-4edf-4790-9d18-f269d035bb1a.png)

### Steps To Reproduce:
it's simple to reproduce it. just check the image that I attached.

**Comment by DarkGhostHunter** [comment]
It was [fixed months ago](https://github.com/thephpleague/flysystem-aws-s3-v3/commit/4a0bc7011d9764c87f6406e9cd09b1109565c043).

You should update your S3 Adapter to the latest version.
