### ISSUE TITLE
Single validation message for array based fields is not working as expected

### ISSUE THREAD

**Issue by kskrlinnorth2** [laravel/framework#42725]
- Laravel Version: 9.10.1
- PHP Version: 8.1.0
- Database Driver & Version: Not important for this issue

### Description:
According to the [documentation](https://laravel.com/docs/9.x/validation#custom-validation-rules) there is option to provide single error message for array validation rules. However, this doesn't work or the documentation is not correct.

### Steps To Reproduce:
```
$data = $request->validate([
    // Some other rules not important for this issue...
    'team.*.email' => 'required|string|email|max:255|distinct',
], $messages);
```
This returns error for each field in array (if I have 4 items in array it will return 4 errors) which I want to avoid and return single error no matter how many items failed:
```
$messages = [
    'team.*.email.distinct' => __('Email is duplicated for participant #:position.'),
];
```

Following the provided documentation link, one of those 2 solutions should work, but it doesn't and it just returns multiple default error messages:
```
$messages = [
    'team.*.email' => [
        'distinct' => 'Each participant must have unique email address.',
    ],
];
```
```
$messages = [
    'custom' => [
        'team.*.email' => [
            'distinct' => 'Each participant must have unique email address.',
        ],
    ],
];
```

I expect to get just one error: `[ "message" => "Each participant must have unique email address" ]`, but I get this:
```
[
    "message" => "The team.0.email field has a duplicate value. (and 1 more error)",
    "errors" => [
        "team.0.email" => [
            "The team.0.email field has a duplicate value."
         ],
         "team.1.email" => [
            "The team.1.email field has a duplicate value."
        ]
    ]
]
```

**Comment by matiaslauriti** [comment]
The URL is https://laravel.com/docs/9.x/validation#validating-nested-array-input pointing to what you want.

As the documentation mentions, you need to have a file in `lang/xx/validation.php` (`xx` would be `us` for you I assume), and that file needs to have:
```php
'custom' => [
    'team.*.email' => [
        'distinct' => 'Each participant must have unique email address.',
    ]
],
```

But you need to have that in the file. I am not sure if that will work if you have it as `$messages = [ ... ]` in your validator (I never used this and I also did not check the source code).

Could you shared where are you using `$messages`? Show the entire validator call please

**Comment by kskrlinnorth2** [comment]
So this works exclusively via validation file? I never use files to write validation rules, I pass array of rules and array of validation messages for those specific rules to `validate` method.

**Comment by SreeAnir** [comment]
I was not able to fix it by adding the custom message array in validation.php.Got any fix for it?

**Comment by kskrlinnorth2** [comment]
> I was not able to fix it by adding the custom message array in validation.php.Got any fix for it?

In your lang/{lang}/validation.php file add this (must be under custom):

```
'custom' => [
       'prices.list.*.amount' => [
            'required' => 'Enter amount for each price.',
            'numeric' => 'Price amount is invalid.',
            'min' => 'Price amount is invalid.',
        ],
        // other validation messages...
]
```

And in rules:
```
'prices.list' => 'nullable|array',
'prices.list.*.amount' => 'required|numeric|min:0',
```

This will return just 1 message per validation rule, regardless how many price list items failed; otherwise you would get errors like prices.list.0.amount is required, prices.list.1.amount is required, etc.

**Comment by Observer1995** [comment]
same isuue
i could not fix by adding custom messages in lang/{lang}/validation.php
Laravel Version: 7
PHP Version: 7.4

`
 public function rules()
    {
        return [

            'networks' => 'nullable|array',
            "networks.*.max_deposit" =>['required','string'],

        ];
    }
    
    
    
    'custom' => [
        'networks.*.max_deposit' => [
            'required' => 'Enter max deposit amount for each network.',
        ],
    ],
    
`

**Comment by matiaslauriti** [comment]
> same isuue
> i could not fix by adding custom messages in lang/{lang}/validation.php
> Laravel Version: 7
> PHP Version: 7.4
> 
> `public function rules()
>     {
>         return [
> 
>             'networks' => 'nullable|array',
>             "networks.*.max_deposit" =>['required','string'],
> 
>         ];
>     }
>     
>     
>     
>     'custom' => [
>         'networks.*.max_deposit' => [
>             'required' => 'Enter max deposit amount for each network.',
>         ],
>     ],`
>  
>     
> 
> 

Laravel 7 uses `resources/lang` not `lang`...

**Comment by Observer1995** [comment]
> Laravel 7 uses `resources/lang` not `lang`...

i put custom messages in resources/lang/fa/validation.php but still not working
my locale in `config/app.php` is also set to `fa`
my validation.php 

` 'custom' => [
        "networks.*.max_deposit"=>[
            "required" =>"Enter max deposit amount for each network."
        ]
    ],
    
   
    {
    "message": "The given data was invalid.",
    "errors": {
        "networks.0.max_deposit": [
            "Enter max deposit amount for each network."
        ],
        "networks.1.max_deposit": [
            "Enter max deposit amount for each network."
        ]
    }
}`

**Comment by matiaslauriti** [comment]
> > Laravel 7 uses `resources/lang` not `lang`...
> 
> i put custom messages in resources/lang/fa/validation.php but still not working
> my locale in `config/app.php` is also set to `fa`
> 
> 
> `'custom' => [
>         "networks.*.max_deposit"=>[
>             "required" =>"Enter max deposit amount for each network."
>         ]
>     ],
>     `
>    
>    Errors  shown as below
>  `   {
>     "message": "The given data was invalid.",
>     "errors": {
>         "networks.0.max_deposit": [
>             "Enter max deposit amount for each network."
>         ],
>         "networks.1.max_deposit": [
>             "Enter max deposit amount for each network."
>         ]
>     }
> }`

Create a new issue as the original issue has another laravel version

**Comment by matiaslauriti** [comment]
> > Laravel 7 uses `resources/lang` not `lang`...
> 
> i put custom messages in resources/lang/fa/validation.php but still not working
> my locale in `config/app.php` is also set to `fa`
> 
> 
> `'custom' => [
>         "networks.*.max_deposit"=>[
>             "required" =>"Enter max deposit amount for each network."
>         ]
>     ],
>     `
>    
>    Errors  shown as below
>  `   {
>     "message": "The given data was invalid.",
>     "errors": {
>         "networks.0.max_deposit": [
>             "Enter max deposit amount for each network."
>         ],
>         "networks.1.max_deposit": [
>             "Enter max deposit amount for each network."
>         ]
>     }
> }`

It is working, it is literally printing your desired error....

**Comment by Observer1995** [comment]
> It is working, it is literally printing your desired error....

No, i want it return just 1 message per validation rule, regardless how many network items items failed.

In my case i want somthing like
` { "message": "The given data was invalid.", "errors": { "networks.max_deposit": [ "Enter max deposit amount for each network." ] } }  `
