### ISSUE TITLE
Validation exception message has hardcoded english text.

### ISSUE THREAD

**Issue by Otisz** [laravel/framework#42736]
- Laravel Version: 9.17.0
- PHP Version: 8.1.6
- Database Driver & Version: Not important for this issue

### Description:

In the [ValidationException.php](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Validation/ValidationException.php#L86) the `summarize` method returns the `message` string for the response. It is only available in English.

If I want to translate the errors into any other language, I get the text in a mixed language, which feels kinda off.

In English: `'The name field is required. (and 1 more error)'`

In Hungarian:
Actual output: `A(z) név megadása kötelező! (and 1 more error)`
Expected output: `A(z) név megadása kötelező! (és 1 további hiba)`

In German:
Actual output: `Name muss ausgefüllt werden. (and 1 more error)`
Expected output: `Name muss ausgefüllt werden. (und 1 weiterer Fehler)`

It would be nice to be able to translate this little string.

### Steps To Reproduce:

1. Publish any language from [Laravel-Lang/lang](https://github.com/Laravel-Lang/lang) (DE and HU in this issue)
2. (translate the necessary custom attributes)
   - lang/de/validation.php: `'attributes' => ['name' => 'Name', 'country' => 'Land'],`
   - lang/hu/validation.php: `'attributes' => ['name' => 'név', 'country' => 'ország'],`
3. Set the app locale `app()->setLocale('DE')`
4. Perform any validation 

```php
<?php

app()->setLocale('DE'); // or 'HU'

Validator::validate([], [
    'name' => ['required'],
    'country' => ['required'],
]);
```

**Comment by driesvints** [comment]
Hi there. This message should not reach any end users. We do not consider this a bug.

**Comment by Otisz** [comment]
Hi!

What do you mean it should not reach the end user? This message is part of the response, so it reaches the user.
I accept the fact you are not showing exactly this message in your first-party frontend.

On the other hand, if it is an API that has been created for use by other applications, you have no control over how its use there. 
In the end, it gives the feeling of a less quality application, because the B2B user will get the message in mixed language.
