### ISSUE TITLE
Cannot migrate 2nd connection postgres database. Thinks migration table does not exist, then tries to make it, and fails because it does exist.

### ISSUE THREAD

**Issue by SimonMacIntyre** [laravel/framework#42738]
- Laravel Version: 9.17.0
- PHP Version: 8.0.19

- Database Driver & Version: pgsql, Postgresql 12 &  Timescale 13.7 for the 2nd connection in question

### Description:
After updating to laravel 9, suddenly our migration script stopped working for our 2nd DB connection. You can see in the screenshot that I can query the migrations table, however status cannot find the table. So the migrate attempt itself will fail, because it tries to create the migrations table, but then errors because ofcourse that table already exists.

![Screen Shot 2022-06-09 at 10 28 45 AM](https://user-images.githubusercontent.com/1260938/172901617-360fd41d-24f3-4a21-abee-0188a19f86f1.png)

![Screen Shot 2022-06-09 at 10 18 21 AM](https://user-images.githubusercontent.com/1260938/172903228-a0512fd4-ed95-48f7-83a8-747087f17543.png)

database.php
```php
 'connections' => [

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => 'db',
            'port' => '5432',
            'database' => 'tenant',
            'username' => 'username',
            'password' => 'password',
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],

        'audits' => [
            'driver' => 'pgsql',
            'host' => 'db2',
            'port' => '5432',
            'database' => 'audits',
            'username' => 'username',
            'password' => 'password',
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
            'options' => [
                PDO::ATTR_EMULATE_PREPARES => true,
            ],
        ],

    ],
```

### Steps To Reproduce:

I'm not sure. Have 2 db connections, both postgres, and try to migrate the 2nd connection?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by SimonMacIntyre** [comment]
Classic.

**Comment by yairmishnayot** [comment]
I'm having the same problem as well

**Comment by SimonMacIntyre** [comment]
@yairmishnayot  I was not able to find the time to look into it any deeper, and I felt I provided enough details to show that it seems like a Laravel framework code problem. Good luck, not sure if they will open the issue, we got the dreaded copypasta immediately so. 🤷

**Comment by yairmishnayot** [comment]
So what do you do in order to keep the development with postgres? Rolled back to laravel 8?

**Comment by SimonMacIntyre** [comment]
In our unique circumstance, we were lucky enough that we did not _need to migrate the 2nd table to continue_, so we literally are just treading water and luckily our second table does not _need_ migrations right now. No solution was found.
