### ISSUE TITLE
XSRF-Token not getting recognized if sent by Fetch API

### ISSUE THREAD

**Issue by NK0D1NG** [laravel/framework#42751]
- Sanctum Version: v2.15.1
- Fortify Version: v1.13.0
- Laravel Version: v9.17.0
- PHP Version: PHP 8.1.6
- Database Driver & Version: Based on Laravel Sail (docker): image: 'mysql:8.0'

### Description:
The function `protected function getTokenFromRequest($request)` in `/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php` expects the X-XSRF-TOKEN to be uppercase (hard-coded). Axios sends the header name in uppercase - that's no problem. If using the Fetch API additional HTTP headers are sent in lowercase. It's not possible to change that. According to the RFCs [2616](https://datatracker.ietf.org/doc/html/rfc2616#page-31) and [7540](https://datatracker.ietf.org/doc/html/rfc7540) HTTP Headers should be case-insensitive - so the Fetch API is doing nothing wrong there.

### Fix:
Laravel should search case-insensitive for the header or the header name should be configurable.

### Steps To Reproduce:
I am calling the Laravel Backend using a composable function on a frontend Nuxt App like this:
```
export const useLogin = async (email, password) => {
  const config = useRuntimeConfig()
  const tokenResponse = await $fetch(config.baseURL + '/sanctum/csrf-cookie', {
    method: 'GET',
    credentials: 'include'
  })
  const token = getCookie('XSRF-TOKEN')
  console.log(token)
  const loginResponse = await $fetch(config.baseURL + '/login', {
    method: 'POST',
    headers: {
      'X-XSRF-TOKEN': token,
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: {
      "username": email,
      "password": password
    }
  })
}
```

Then I call it in a LoginForm-Component:
```
<template>
    <form @submit.prevent="login()" class="bg-blue-500 flex flex-col rounded-xl p-4 text-white">
        <h1 class="text-center mb-4">Login</h1>
        <label for="fname">Email</label>
        <input v-model="form.email" class="rounded-md h-8 mb-4 text-black" type="text" id="email" name="email"><br><br>
        <label for="password">Password</label>
        <input v-model="form.password" class="rounded-md h-8 mb-4 text-black" type="password" id="password" name="password"><br><br>
        <button class="rounded-md bg-orange-700 cursor-pointer" type="submit">Login</button>
    </form>
</template>

<script setup>

const form = {
    email: '',
    password: ''
}

function login() {
    useLogin(form.email, form.password)
}

</script>
```
The problem is that I get 419 errors (csrf mismatch) back from the login route although the X-XSRF-Token is set in the request headers (like described in the Laravel Sanctum docs). But when using the Fetch API the token is sent lowercase and so Laravel sends a 419.

### Additional information

I posted this issue on the Laravel Sanctum Repository but it seems the issue is in the Laravel Core Code. There are some more details about the issue: https://github.com/laravel/sanctum/issues/370

**Comment by NK0D1NG** [comment]
Hey there,
I misinterpreted my error logs and found that there is another small difference using Axios and Fetch API:
Axios seems to decode the X-XSRF-TOKEN whereas Fetch API does not.

So this example token is sent by Fetch API:
`eyJpdiI6IkRScW9GNGtIbndWWFdKbzRiN0VWVkE9PSIsInZhbHVlIjoiNUNuQStiZGt0Y3l0cXhReThHSEJxbCsxRmZvbFFHKzhQV3ArSlg0cjVQVm5qSDZoQ3ZsSERnUTREUXRvczdMOHhYSHFqbm5FUjd2dFpGMlN4bU81NWJ5SWpmem5BQi9vRmJBRFZZWmFSZFlqcHNxbTZ5N1Z0cGJzSmMwcUFRaXUiLCJtYWMiOiI4MjM1MTQ2ODExNzhlY2ExNDk1NDhhOWEwNzE0OWJlMzViOGQxNDJhMTY0YTI2NzYwMThjMzQ5ODVmMDYwMjk1IiwidGFnIjoiIn0%3D`

And this example token is sent by Axios:
`eyJpdiI6IisydDZOOFJoREp5ZnZudUtjRk1teXc9PSIsInZhbHVlIjoiV1dQdjJDZlNrcW43Zlg4TW1yRFdjOVJWVnJkaC9CZndxejJLQ3JEUkJIRXJ3Z2pNb2pxSUJYN0Y2RDBxZ1hKd01mNHF6empsRkFIeEFOSkJKbi8vT0hWOFBYMDdlMkZybzBZdllJQlBFa1lHTytZd1E0aU9vL2pOM1ZRZWwxV0ciLCJtYWMiOiI3NTczZGJiMjg5MWZmOTUzMjhiMTZhNjAxM2ZiZmVjODVjYjc2MGRiMGJkMTFkOGYzOWQzYWQ5MjI5YWIwOTA5IiwidGFnIjoiIn0=`

There is a very small difference at the end of the token string (= vs. %3D).

Laravel itself sends the Token value URIEncoded (with %3D) but seems to expect the token with = at the end.

There is nothing about that in the docs but this issue kept me searching for days and was not that obvious.

I changed my code to:
```
export const useLogin = async (email, password) => {
  const config = useRuntimeConfig()
  const tokenResponse = await $fetch(config.baseURL + '/sanctum/csrf-cookie', {
    method: 'GET',
    credentials: 'include'
  })
  const token = decodeURIComponent(getCookie('XSRF-TOKEN')) // <---- CHANGED
  console.log(token)
  const loginResponse = await $fetch(config.baseURL + '/login', {
    method: 'POST',
    credentials: 'include',
    headers: {
      'X-XSRF-TOKEN': token,
      'Accept': 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'X-Requested-With': 'XMLHttpRequest'
    },
    body: {
      "email": email,
      "password": password
    }
  })
}
```

And now the login is working using the standard Fetch API.

I was not able to reproduce the uppercase/lowercase problem so that seems to be no issue. I am closing this now.

I hope this helps someone else debugging their login flow.

Greetings.

**Comment by Robertv9** [comment]
Thanks for your help! 
If some one have problesm with the getCookie function like me I add this function.
```

function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}
```
