### ISSUE TITLE
Custom file formats not supported

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [laravel/framework#42758]
Re-opening this because it's an issue for every application that use non-standard filetypes.
https://github.com/laravel/framework/issues/41960#issuecomment-1152703807_

- Laravel Version: 9.8.1
- PHP Version: 8.1.3
- league/flysystem 3.0.16

### Description:
```
$headers["Content-Type"] = "text/plain";
$headers["Content-Length"] = $file_size;
$headers["Accept-Ranges"] = "bytes";
$headers["Content-Disposition"] = "attachment; filename={$id}.left";
$headers["Content-Range"] = "bytes " . 0 . "-" . ($file_size) . "/" . $file_size;
Storage::disk("localdisk")->download($id.".found", $headers);
```
Results in the following error:
```
local.ERROR: Unable to retrieve the mime_type for file at location: 737.found.  {"exception":"[object] (League\\Flysystem\\UnableToRetrieveMetadata(code: 0): Unable to retrieve the mime_type for file at location: 737.found.  at /var/www/hostname/vendor/league/flysystem/src/UnableToRetrieveMetadata.php:49)
```
I believe this is caused by me having a non-standard extension, which is fine since I provided the content-type in the headers explicitly. But instead I'm getting errors now with my recent upgrade from laravel 8 to laravel 9. Any way to make this work?

**Comment by rodrigopedra** [comment]
Sent PR #42759 to propose a fix

**Comment by henrik9999** [comment]
> Sent PR #42759 to propose a fix

I don't think your fix really fixes the underlining issue of it not accepting custom file types or being able to set them if I understand yours correctly all it does it fix it for download but it probably happens everywhere it's using minetype not just download

**Comment by rodrigopedra** [comment]
Closed PR #42759 in favor of PR #42760 targeting 9.x

**Comment by rodrigopedra** [comment]
The `Illuminate\Filesystem\FilesystemAdapter@mimeType` is only called in two other places:

https://github.com/laravel/framework/blob/2bc180295ebf8c4848a6b9c4ae8fa0d00ec75217/src/Illuminate/Mail/Attachment.php#L98

Where it appears after the null coalesce operator, so it will only be executed if `$attachment->mime` fails.

And

https://github.com/laravel/framework/blob/2bc180295ebf8c4848a6b9c4ae8fa0d00ec75217/src/Illuminate/Mail/Mailable.php#L453-L466

Which will indeed fail when attaching a custom file format. Will add a commit to address this.

**Comment by rodrigopedra** [comment]
Sent a different PR #42761 , to address only the mime type method. Thanks for the heads-up

**Comment by henrik9999** [comment]
> Sent a different PR #42761 , to address only the mime type method. Thanks for the heads-up

What would happen if the flysystem driver internally uses mimetype tho then it would still explode there I guess🤔

**Comment by rodrigopedra** [comment]
Well, as flysystem is a third-party package, my suggestion is to you propose a change on their repo if you believe this behavior should be changed.

Or write some code to contribute with a PR either there or here, I guess :thinking:

**Comment by henrik9999** [comment]
> Well, as flysystem is a third-party package, my suggestion is to you propose a change on their repo if you believe this behavior should be changed.
> 
> Or write some code to contribute with a PR either there or here, I guess 🤔

There was https://github.com/thephpleague/flysystem/issues/1448 but all that was done was adding phar as a mime type

**Comment by driesvints** [comment]
Seems like a PR was sent in to resolve the main issues here. Thanks
