### ISSUE TITLE
status as parameter to blade does not seem to operate well.

### ISSUE THREAD

**Issue by henzeb** [laravel/framework#42756]
- Laravel Version: 9.17.0
- PHP Version: 8.1.6

### Description:
When passing 'status' as parameter to Blade's render option, I get an exception. It seems that when the name 'status' is used, the echoHandlers are not being executed. 

Further investigation finds that it is only happening with '{{$status}}' and not with '{{ $status }}' or  '{{$anythingElse}}'  or '{{ $anythingElse }}'. 

Before you close this: I know the one with spaces is the correct syntax, but either do not accept it at all or keep it consistent is my opinion. It's an odd behavior and 'status' is a common used word.

So the bug is either: status cannot be used when {{$status}}
or: Blade accepts {{$anything}} which should not be the case.

### Steps To Reproduce:

    class str {
        public function get()
        {
            return 'laravel';
        }
    }

    Blade::stringable(str::class, function(str $string){
        return $string->get();
    });

   Blade::render('{{$status}}', ['status'=>new str()]);

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by henzeb** [comment]
No. Because I already identified it as a bug. So this is a bug or a won't fix. At least try my code and/or explain why you won't fix it.
