### ISSUE TITLE
Create CSV file with expected result line break CRLF in Laravel

### ISSUE THREAD

**Issue by codeOraaange** [laravel/framework#42766]
- Laravel Framework Version: 5.6
- PHP Version: 7.1.3
- Database Driver: MySQL

```
$file = fopen($file_path,"w");
fputcsv($file, $headers, ';');
$data = Data::select('*');

foreach ($data as $line) {
	fputs($file, implode(';', $line)."\r\n");
	// fputs($file, nl2br(implode(';', $line)."\r\n"));
}
fclose($file);
```

Notes: 
- **$file_path** is my specific path
- **$headers** is group naming columns in array
- **Data** is my model name

My CSV file is fine but I want CRLF result for line break, with \n is working I get LF but with \r\n not working for get CRLF. And i found function nl2br() is the same not change to CRLF. Can anyone help with this?

**Comment by rodrigopedra** [comment]
From: https://laravel.com/docs/9.x/contributions#support-questions

> Laravel's GitHub issue trackers are **not intended to provide Laravel help or support**. Instead, use one of the following channels:
> 
> - [GitHub Discussions](https://github.com/laravel/framework/discussions)
> - [Laracasts Forums](https://laracasts.com/discuss)
> - [Laravel.io Forums](https://laravel.io/forum)
> - [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> - [Discord](https://discord.gg/laravel)
> - [Larachat](https://larachat.co/)
> - [IRC](https://web.libera.chat/?nick=artisan&channels=#laravel)
