### ISSUE TITLE
Attribute That Returns Array Fills Model When Not Expected

### ISSUE THREAD

**Issue by jjjrmy** [laravel/framework#42773]
- Laravel Version: v19.17.0
- Database Driver & Version: Mysql

### Description:

The `Steps` column is JSON / Array. In the Attribute, if the Setter returns an array the keys are used as fields on the model. It's expected it should fill the column with the array data. If you take off the `->toArray()` it saves it fine, but this seems like a bug.

```php
protected function steps(): Attribute
{
    return Attribute::make(
        get: function ($value) {
                $value = Collection::wrap(json_decode($value));
            return Step::query()->whereIn('id', $value)->get();
        },
        set: fn ($value) => $value->pluck('id')->unique()->toArray(),
    );
}
```

```php
$steps = Step::where(...)->get();
$history = History::first();

$history->steps->push(... $steps);

return $history;
```

```
App\Models\History{
  steps: "[]",
  0: "<id>",
  1: "<id2>",
  2: "<id3>",
}
```

**Comment by rodrigopedra** [comment]
Actually this is documented behavior:

> Sometimes your mutator may need to set multiple attributes on the underlying model. To do so, you may return an array from the `set` closure.

https://laravel.com/docs/9.x/eloquent-mutators#mutating-multiple-attributes

So as you returning an array Eloquent assumes you want to set multiple columns, and as the returned array's are numeric this fails.

This works without the `->toArray()` call, as you are returning a `Collection`  instance instead.

If you want, or need in another mutator, to return an array, you can return an array with the syntax `['column => $value]', which in your case would look something like this:

~~~php
public function steps(): Attribute
{
    return Attribute::make(
        get: function ($value) {
            $modelKeys = Arr::wrap(json_decode($value ?? '[]'));
            return Step::query()->findMany($modelKeys);
        },
        set: fn ($collection) => [
            'steps' => $collection->pluck('id')->unique()->all(),
        ],
    );
}
~~~

**Comment by jjjrmy** [comment]
Yes, I understand you'd want to set multiple attributes, as I do that in other cases. But I think the difference with this is the return value has numeric keys and array_is_list. Seems weird you'd have model fields as 0,1,2,3,...

**Comment by rodrigopedra** [comment]
I don´t actually see this as an issue, as it is now, but if you think this behavior should be changed, you can try to propose a fix.

The method you will need to change is this one:

https://github.com/laravel/framework/blob/2bc180295ebf8c4848a6b9c4ae8fa0d00ec75217/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1658-L1668

This method checks if the value is already an array, assuming the developer already sent in the `[$key => $value]` format, and if it is not and array it converts the attribute to the `[$key => $value]` format.
