### ISSUE TITLE
Saving model with negative id.

### ISSUE THREAD

**Issue by jtuta** [laravel/framework#42771]
- Laravel Version: `5.8` upgrade to `9.0`
- PHP Version: `7.3` upgrade to `8.1`
- Database Driver & Version: MySql `8.0.27`

### Description:
Not sure if this would be classified as a bug but I encountered problems with saving models with negative ids in my PHPUnit tests while upgrading an older Laravel application from `5.8` to `9.0`.

I have a model that has one-to-many submodels:
```php
class Model extends \Illuminate\Database\Eloquent\Model {

   public function submodels() {
      return $this->hasMany(Submodel:class);
   }

}
```

In the seeding for my Unit tests I populate database with:
```php
$model = new Model();
$model->id = -1;
//other attributes
$model->save();

$submodel = new Submodel();
//set $submodel's attributes
$model->submodels()->save($submodel);
```

These tests run great in old environment (Laravel `5.8` and `php:7.3-fpm`) but in new (Laravel `9.0` and `php:8.1-fpm`) they failed.

With testing I have narowed issue to the PHP's [PDO::lastInsertId()](https://www.php.net/manual/en/pdo.lastinsertid.php) function in php `8.1` versus `7.3`. The problem is that Model after saving has value of `$model->id` set to `18446744073709551615` when in the database it has value `-1`.

My tests were failing as foreign key constraint for `Submodel` table failed as there was no `Model` with id `18446744073709551615`, only one with `id` set to `-1`.

Now, I personally think that this is a bug in PHP and have opened bug report issue in their repo: php/php-src#8746 but got an explanation that this is by design of MySQL API which returns `uint64_t` value for last insert id and as `-1` is negative this results in number `18446744073709551615`. As can bee seen in the issue I opened in PHP source repository they will not change this, as MySQL actually returns unsigned integer. I must say I can see why PDO should be designed like this and I understand their decision.

I think there should be a "fix" in Laravel - model after saving (`$model->save();`) should afterall represent state in the database and have in my case `id` set to `-1`.

I am just a Laravel user and I am not greatly familiar with the innerworkings of laravel/framework but I do not see a clear way of fixing this. I think Laravel cannot know if id was intentionally changed (with for example a before insert trigger) and `PDO::lastInsertId()` is returning the correct new id, or if returned id is "wrong" and data in the database actually has id set to the value in the attributes.

**Comment by rodrigopedra** [comment]
It looks like your model does not have an auto incrementing id. If that is the case, set your model's `$incrementing` property to `false` to tell Eloquent to not set it using `PDO::lastInsertId()`.

~~~php
class MyModel extends Model {
    public $incrementing = false;
}
~~~

By default Eloquent assumes the primary key is an integer auto incrementing key, as stated in the docs:

https://laravel.com/docs/9.x/eloquent#primary-keys

**Comment by matiaslauriti** [comment]
I am just curious, why would you use a negative ID? (you are not using it to get one model but using it to store a model)

**Comment by jtuta** [comment]
@matiaslauriti I have negative ids due to some legacy things we have to support. As we need to support negative ids we have some database seeding for our PHPUnit test and that is how I discovered this issue after migration form Laravel 5.8.

@rodrigopedra I agree that in my case - as I am setting id manually in PHPUnit test I should have set `$incrementing = false;` which would solve issue.
