### ISSUE TITLE
JsonResource::withoutWrapping() on Octane, affects all children and it's not what a developer would expect

### ISSUE THREAD

**Issue by madalinignisca** [laravel/framework#42777]
- Laravel Version: ^8.0||^9.0
- PHP Version: ^8.0
- Database Driver & Version: any (not DB related)

### Description:
When using AnyExtendingJsonResource::withoutWrapping(), it affects all after first usage, when using Octane, and it is thought to be happening only on the extending JsonResource called. This is because a static property is shared among all children when modified.

### Steps To Reproduce:

Create a new JsonResource, apply *::withoutWrapping() anywhere using it, try to look at any other response for another resource, and `data` is gone on all.

**Comment by madalinignisca** [comment]
With Octane, I think a lot of STATIC PROPERTIES abuse should be reevaluated, as those properties will be shared with all extending children on all requests in Octane (Swoole).

**Comment by rodrigopedra** [comment]
This is documented behavior, there is a warning note in the documentation stating:

> The `withoutWrapping` method only affects the outermost response and will not remove `data` keys that you manually add to your own resource collections.

reference: https://laravel.com/docs/9.x/eloquent-resources#data-wrapping

You can still manually wrap any resources you want with a `data` key, and Laravel won't remove them automatically:

> You may be wondering if this will cause your outermost resource to be wrapped in two `data` keys. Don't worry, Laravel will never let your resources be accidentally double-wrapped

reference: https://laravel.com/docs/9.x/eloquent-resources#wrapping-nested-resources

Note this behavior is not exclusive to Octane, but it is the default behavior on any Laravel app.

If you believe this need to be changed, you can propose a PR.

**Comment by rodrigopedra** [comment]
Another thing I am wondering, and hope you can clarify. Regarding this:

> I think a lot of STATIC PROPERTIES abuse should be reevaluated

Do you have any examples where do you think the usage of static properties are being "abused"?

I am not aware of any static properties, in Laravel, that is not available to allow a developer to change a global behavior by opting-in to a feature. Which, in my opinion, is a nice way to allow behavior customization, and far from being an "abuse".

The ones I am aware are also have their usage very well documented. So you left me curious about which other properties you are referring to as being an "abuse".

**Comment by madalinignisca** [comment]
OH, now I get it. This is me, as I switch recently to Octane, I was calling ::withoutWrapping on the extended resource in the controller, before returning the response. Was very convenient to have this only on some occasions needed.

About statics, maybe it's just me, a bit more against using statics. I still consider that statics will create a lot of confusion with Octane for some developers.

**Comment by arukompas** [comment]
One of my packages was using `JsonResource::withoutWrapping()` which was spilling outside the package's routes into the rest of the user's Laravel application.

I fixed it with a middleware for my package routes:

```php
use Closure;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class JsonResourceWithoutWrappingMiddleware
{
    public function handle(Request $request, Closure $next)
    {
        $originalWrappingBehaviour = JsonResource::$wrap;

        JsonResource::withoutWrapping();

        $response = $next($request);

        JsonResource::wrap($originalWrappingBehaviour);

        return $response;
    }
}
```
