### ISSUE TITLE
Exception in route model binding using postgres

### ISSUE THREAD

**Issue by MohammadMirsafaei** [laravel/framework#42786]
- Laravel Version: 9.9.0
- PHP Version: 8.1.5
- Database Driver & Version: pqsql, 14.2

### Description:
I've setup laravel route model binding like below:
`Route::get('{sample}', [SampleController::class, 'show'])->name('show');`

Primary key for `Sample`  model is laravel's default `id`. And here is how I used it in controller:
`public function show(Sample $sample): View { ... }`
 
It is working fine when I pass an integer to route like : `/11`, but when I pass a string like : `/test`, it breaks. I remember in previous versions of laravel and while using mysql everything was ok and a 404 response was returned instead of server error. I know there are some techniques for handling this, but I think laravel must handles this internally.

Error:
`SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "test" CONTEXT: unnamed portal parameter $1 = '...'`

**Comment by rodrigopedra** [comment]
I think what happens with MySQL is that it doesn't throw an exception when comparing an integer column to a string. As no records are found, Laravel ends up throwing an exception.

I don't use postgres, but I agree, if this is reproducible, that it seems to be a bug.

As a workaround you can use a route constraint to tell the router to only accept numeric sequences for that specific route.

In your case it should be something like this:

~~~php
Route::get('{sample}', [SampleController::class, 'show'])
    >where('sample', '\d+')
    ->name('show');
~~~

As the router will not find a matching route when the parameter is not a numerical sequence, the request will end up being a 404.

reference: https://laravel.com/docs/9.x/routing#parameters-regular-expression-constraints

**Comment by MohammadMirsafaei** [comment]
Yes you're right, thanks. Also global constraints in `RouteServiceProvider` will work too. But consider whenever we are using laravel with Postgres we must define these constraints. Every time for each project. I've opened a bug report but maybe what I'm requesting is a feature request. That is laravel handles this internally.

**Comment by driesvints** [comment]
Heya. We don't consider this to be a bug. Please use proper data sanitisation on the route param as shown in the example by @rodrigopedra.
