### ISSUE TITLE
Collection methods don't work with built-in PHP functions

### ISSUE THREAD

**Issue by Danon** [laravel/framework#42789]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:

Built-in PHP functions can't be used with `Collection` methods.

### Steps To Reproduce:

In PHP there are a lot of types of `callable`, for example `Closure` is callable, anonymous function, also `[$this, 'method']` and `"strtoupper"` for example.

This kind of code work fine:
```php
$collection = collect(['one']);

$collection->map(function ($value) { return strtoupper($value); });
```
but this one doesn't
```php
$collection = collect(['one']);

$collection->map('strtoupper');
```

it throws
```
ArgumentCountError : strtoupper() expects exactly 1 argument, 2 given
```

#### About PHP functions

`"strtoupper"` is a valid callable in PHP, for example

```php
is_callable("strtoupper"); // true
```
and also
```php
$function = "strtoupper";
$function("one"); // "ONE"
```

It also works fine with `array_map()`:
```php
array_map(['one', 'two'], 'strtoupper'); // ["ONE", "TWO"]
```

**Comment by rodrigopedra** [comment]
~~~
ArgumentCountError : strtoupper() expects exactly 1 argument, 2 given
~~~

Collection@map passes two arguments to the callback, the item value and the item key, as shown on docs.

And as the error message says, `strtoupper` expects only one, not two arguments.

It does not fail because `strtouppee` is nor accepted as a call back. But because this particular function does not access more than one argument.

**Comment by Danon** [comment]
@rodrigopedra So how do you explain the difference between these two
```
$collection = collect(['one']);
$collection->map(function ($value) { return strtoupper($value); });
```
vs.
```
$collection = collect(['one']);
$collection->map('strtoupper');
```

**Comment by Danon** [comment]
> I don't see this as a problem, framework chose to provide you with a key in case you need it

By doing so, causes the method to not work with built-in functions directly.

**Comment by donnysim** [comment]
And why is that a framework problem?

**Comment by rodrigopedra** [comment]
@Danon  try this:

~~~php
function myAwesomeFunction($argument) { return strtoupper($argument); }

collect(['a'])->map('myAwesomeFunction');
~~~

Now, how do you explain this to work:

~~~php
collect(['a'])->map('str_pad');
~~~

Although not very useful, this yields interesting results, but the key here is to demonstrate it working if a "built-in" PHP function.

And a @donnysim said, if you do:

~~~php
array_map('strtoupper', ['a'], ['b']);
~~~

This will fail as well. Or according to your definition: `PHP functions don't work with built-in PHP functions`.

I recommend you believing error messages more than intuition. The error message is very clear: the function expects one parameter, and two are passed.

There is nothing to do with the callback being a PHP built-in function or not.

**Comment by Danon** [comment]
I think think you fully understand the issue I'm trying to raise here. Let me reclarify.

There are different types of `callable` in PHP:

- Built-in functions: `strtoupper()`, `strtolower()`
- user functions: `function my_function() {}`
- anonymous functions `return function (string $s) {};`
- a.ka. "method reference": `[$this, 'method']`
- a.ka "static method reference": `[MyClass::class, 'method']`

All of them are valid PHP callables. Works for `is_callable`, works for passing it as `callable` type-hint, you can call it normally, like that `$func();` or with `call_user_func()`.

Two of them ignore superfluous arguments, the remaining not - for example `strtoupper()` throws a warning.

The rational way explain is that, if a method needs a single argument, it should be called with a single argument.

But `collect()->map()` calls its callback with two arguments, relying on the fact that anonymous functions are the most common parameters and also happen to ignore superfluous arguments.

It basically means that author of this method chose to not support php built-in methods, but only anonymous methods (or didn't know that built-in methods would not be supported).

PS: If there comes an update in PHP, which prohibits superfluous arguments in lambdas (like in python, ruby and other languages) there's going to be a problem.

**Comment by Danon** [comment]
> > By doing so, causes the method to not work with built-in functions directly.
> 
> It works with `str_pad`, a built-in function. If the framework chose to not pass 2 arguments it would not work with `str_pad`.

By "works" you mean "doesn't throw"? 

Yes, it doesn't.  If the interface of `->map()`  was that "callback receives a value and the number of left padding" that would be fine. But the second argument isn't the padding, it's `index`.

**Comment by rodrigopedra** [comment]
>  If the interface of ->map() were that "callback receives a value and the number of left padding" that would be fine. 

Well the interface of `->map()` is: "callback receive the element and its index", as stated in Laravel documentation:

https://laravel.com/docs/9.x/collections#method-map

So, by your own criteria, you are the one not adhering to the documented interface. So by your own terms, you are not accepting the isse, this is not a frameworks problem.

> There isn't a usecase for collect()->map('str_pad') (passing index as a padding), doesn't make sense.

Of course there is:

~~~php
collect(array_fill(1, 10, 'X'))->map('str_pad')->implode("\n");
~~~

This will generate a triangular pattern, which could be used in a CLI program to output cool effects. Due to you not finding a use case, doesn't mean there is not an use case.

@Danon I am actually the one who thinks you are not understanding the issue.

I won't reply anymore, I suggest you do either the following:

1. Accept not everything works as we expect and embrace error messages to improve your code 
2. Propose a PR to Laravel modifying `Collection@map` to use PHP's reflection to assess its callback arity and conform to the user expected "interface"
3. Propose a RFC to PHP to change the language behavior when a built-in function is called with parameters in excess, so users are not surprised when they don't read, or don't like to read, documentation.

Good luck ;)

**Comment by foremtehan** [comment]
I also would like to use php functions in `map` method REALITY BAD!

```php
$collection->map('strtolower');
```

**Comment by marvin-wtt** [comment]
I hope this wasn't already discussed earlier and I missed it:

How about a new method `mapValues` shouldn't that fix all "problems"?

**Comment by Danon** [comment]
> I hope this wasn't already discussed earlier and I missed it:
> 
> How about a new method `mapValues` shouldn't that fix all "problems"?

That would be a possible solution, among others.

**Comment by Danon** [comment]
@rodrigopedra Let's just make sure we're not talking passed one-another. Me voicing my opinion, you voicing yours.

**Had** the laravel documentation present the `Collection.map()` in the documentation like this:

```php
collect([])->map(function ($value, $key) {
});
```
and described it as "function that maps a value and a key to other value", and also probably written "There is no function to map only the value to another value". Then you would have all the rights in the world. You would be most kind of correct, and noone could argue with you otherwise. Actually, I would agree with you more than I can say. That function should only work with `callables` that accept two arguments and should not work with `"strtoupper"`. No question about it.

But that's not the case.

What Laravel documentation now says is

This is fine. `Collection.map()` "*maps one value to another*". It presents the `map()` function as a function that works fine with one argument. 
```
collect([])->map(function ($value) {
});
```

And it works.... only if you pass in a function that ignores superfluous arguments, because if you pass a function that doesn't (like `"strtoupper"`) it throws an error. Why? Because that is a lie. It's not a function that accepts one argument. It only works, because the documentation and most of the use-cases are filled with anonymous functions which ignore the superfluous arguments. It's actually fooling its users to believe that the function "has a variable amount of arguments". If you pass `function ($value) {}` it accepts one, if you pass `function ($value, $key) {}` i accepts two. But it's not a feature of `Collection.map()`, but of a subset of PHP functions - lambdas.

It's bad design.

In my opinion, the right way to handle it would be:

- Not pass second argument as `->map()` (and instead add function like `mapEntries()`)
- Accept `Closure` instead of `callable`, then you can pass all the superfluous arguments you want (because all `Closure` will ignore them)
- Something else.

**Comment by rodrigopedra** [comment]
@Danon 

> Let's just make sure we're not talking passed one-another. Me voicing my opinion, you voicing yours.

Agree 100%

> What Laravel documentation now says is
> 
> This is fine. Collection.map() "maps one value to another". It presents the map() function as a function that works fine with one argument.
> 
>  ~~~
> collect([])->map(function ($value) {
> });

Not sure which part of the documentation you are referring to. Right now the example includes the `$key` parameter, and it states:

> The `map` method iterates through the collection and passes each value to the given callback.

https://github.com/laravel/docs/blob/378b3faeb70edb807ac44a118e97fa616ad57ec8/collections.md?plain=1#L1271-L1286

And from history it is been like this for the last 7 years.

reference: https://laravel.com/docs/9.x/collections#method-map

But, let's agree on disagree and hope for PR #42815 to get merged =)

**Comment by Danon** [comment]
> Not sure which part of the documentation you are referring to.

For example here: https://laravel.com/docs/9.x/collections there are 5 usages of `->map()` in the documentation, 4 of which use lambda with a single argument. It would seem the documentation suggests that the `callable` of `map()` receives a single argument, and thus should be applicable to `strtoupper()`.

> Not sure which part of the documentation you are referring to. Right now the example includes the `$key` parameter, and it states:
> 
> > The `map` method iterates through the collection and passes each value to the given callback.

Exactly. `passes each value to the given callback` - not "passes each value **and key** to the given callback"

> And from history it is been like this for the last 7 years.
> 
> reference: https://laravel.com/docs/9.x/collections#method-map

Yes, I'm aware. However that in and of itself is not a credential of a well-designed function.


My point is:

Would PHP igonre superfluous arguments in every `callable` (like JavaScript), that'd be fine. But it doesn't.
