### ISSUE TITLE
isDirty not working for json object

### ISSUE THREAD

**Issue by VSG24** [laravel/framework#42788]
- Laravel Version: 8.83.16
- PHP Version: 8.0
- Database Driver & Version: mySQL 8.0

### Description:
I'm trying to detect if an object is changed after the value of a property of a json field is updated. However, It's not detecting the change if the new value is a number with leading zeros. Note that the number is saved as a **string** so technically there shouldn't be any issues storing it along with all of its zeros.

### Steps To Reproduce:

The aim is to update a property (`account_number`) of `bban` field (json object) on the `$bankAccount` object.
The code responsible for updating the values:

```php
// dump the original value
dump($bankAccount->bban);
// update the json object
$bankAccount->bban = $this->dto->getBban();
// dump the updated value
dump($bankAccount->bban);
            
if ($bankAccount->isDirty(['bban'])) {
    // NEVER HITS!
    dd('values updated');
}
```

The result of dumping the json variable `bban` before and after the update:
<img width="381" alt="Screenshot 2022-06-13 at 11 24 58" src="https://user-images.githubusercontent.com/7500363/173324314-83329a9f-54fd-45a3-a76d-16403500bebd.png">

As can be seen, the value is updated **however the `isDirty` method isn't able to detect the change, as a result, `dd('values updated');` is never executed.**

It only fails when the new value has leading zeros. Also worth noting is that I am casting the `bban` field to json as it is the recommended approach.

```php
protected $casts = [
    'bban' => 'object',
];
```

**Comment by rodrigopedra** [comment]
This seems to be fixed by #41337 

But that PR was only sent to 9.x. If maintainers consider this a bug fix, can you send a PR backporting it to 8.x?

**Comment by VSG24** [comment]
@rodrigopedra Thank you, I do want to create a PR to fix it for 8.x as well.

**Comment by VSG24** [comment]
@rodrigopedra PR created. https://github.com/laravel/framework/pull/42793
