### ISSUE TITLE
Folder permission issue on request->file->store method

### ISSUE THREAD

**Issue by ARehmanMahi** [laravel/framework#42814]
- Laravel Version: 8.83.16
- PHP Version: 7.4.29
- Database Driver & Version: N/A

### Description:

# Found some insight related to the problem and posted an issue on the flysystem repo [link to issue](https://github.com/thephpleague/flysystem/issues/1483)

```
$request->file('member_image')->store('/members', 'public');

'public' => [
    'driver' => 'local',
    'root' => storage_path('app/public'),
    'url' => env('APP_URL').'/storage',
    'visibility' => 'custom',
    'permissions' => [
        'file' => [
            'private' => 0600,
            'public' => 0640,
            'custom' => 0660,
        ],
        'dir' => [
            'private' => 0700,
            'public' => 0750,
            'custom' => 0770,
        ],
    ],
],
```

After saving file, members folder gets created but with 0750(public) permission instead of 0770(custom), file gets correct permissions though. Tested on new blank project with just a form, and file store code on post route.

Using the following to make folder works correctly as expected. But that is an extra step when disk is already configured with permissions.
> Storage::disk('public')->makeDirectory('/members'); // sets 0770

### Steps To Reproduce:

1) Upload a file using form
2) On post route store the file using `$request->file('member_image')->store('/members', 'public');`
3) public disk is configured as shown on above code.

Reproduce able git repo bellow. During composer install the `storage link command` auto runs as already configured in composer file.

[Github repo](https://github.com/ARehmanMahi/laravel-bug)

**Comment by driesvints** [comment]
See https://github.com/laravel/framework/issues/42586
