### ISSUE TITLE
Accessor attribute with underscore number calls to undefined method 'getColumnNameAttribute'

### ISSUE THREAD

**Issue by f21gerb** [laravel/framework#42834]
- Laravel Version: 9.17.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0.25

### Description:
Accessor attributes with 'column_number' (i.e. 'foo_1') as a name in database do not work throws an exception (referring to old accessor syntax?) whilst 'columnnumber' (i.e. 'foo1') does work.

### Steps To Reproduce:

This works in User model:

`protected $appends = ['name2'];`

```
protected function name2(): Attribute
{
    return Attribute::make(
        get: fn ($value) => 'test',
    );
}
```

`return $user->toArray();`

And this does not work in User model:

`protected $appends = ['name_2'];`

```
protected function name2(): Attribute
{
    return Attribute::make(
        get: fn ($value) => 'test',
    );
}
```

`return $user->toArray();`

BadMethodCallException with message 'Call to undefined method App\Models\User::getName2Attribute()'

**Comment by driesvints** [comment]
The current behavior is as expected. Underscores for numbers in column names are not supported.
