### ISSUE TITLE
Illuminate\Foundation\Exceptions\Handler.php causes infinite redirect loop in a corner case

### ISSUE THREAD

**Issue by misog** [laravel/framework#42830]
- Laravel Version: 9.17.0
- PHP Version: 8.1.3

### Description:
`Illuminate\Foundation\Exceptions\Handler.php` causes infinite redirect loop in a corner case:
```
    /**
     * Convert a validation exception into a response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Validation\ValidationException  $exception
     * @return \Illuminate\Http\Response
     */
    protected function invalid($request, ValidationException $exception)
    {
        return redirect($exception->redirectTo ?? url()->previous())
                    ->withInput(Arr::except($request->input(), $this->dontFlash))
                    ->withErrors($exception->errors(), $request->input('_error_bag', $exception->errorBag));
    }
```

### Steps To Reproduce:

1. Visit url `/somemodel/{id}` with GET in browser
2. Remove the model with the `id` from DB (migrate:fresh)
3. Again visit/refresh url `/somemodel/{id}` with GET in browser
4. Let validator validate the `id` with rule `exists,somemodels,id`
5. Validation fails and exception is created
6. In `invalid` method in `Illuminate\Foundation\Exceptions\Handler.php` the `$exception->redirectTo` is null and `url()->previous()` is the same as the current URL (which is the problem)
7. Redirect to the current URL is send to the browser -> go to step 3 (infinite redirect loop)

So, the method is responsible for this:
```
Convert a validation exception into a response.
```

I think that the method should also handle this case when the previous URL is the same as the current one. This can generally and often happen while creating GET requests in a sequence while using validators. This does not happen in GET-POST mixed request sequence, because _current url_ is switching (get, post, get, post, ...).

The general problem is that if URL is the same across GET requests, server state data (DB, session, cookies, ...) (which are inputs to a validator) can change any time and cause infinite redirect loop.

One solution would be to create default/fallback redirect which could be in config. Or maybe the right solution would be that if the handler detects redirect loop then it sends `410 Gone` response, or `404 Not Found` response or `400 Bad Request` response instead of redirect.

Or, other opinions on status codes related to a server state: https://stackoverflow.com/questions/3290182/which-status-code-should-i-use-for-failed-validations-or-invalid-duplicates

**Comment by taylorotwell** [comment]
This issue feels a bit contrived to me. If the conventional behavior doesn't work for your scenario, don't use it. Use `$validator->passes()` manually and then redirect wherever you want on failure.
