### ISSUE TITLE
Str::snake does not work correctly with Unicode

### ISSUE THREAD

**Issue by zabavnikov** [laravel/framework#42851]
- Laravel Version: 9.17.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Description:
Str::snake('простаяСтрока') returns 'простаястрока', but should return 'простая_строка'.

**Comment by zabavnikov** [comment]
Since the function does not work correctly with unicode, this [test](https://github.com/zabavnikov/framework/blob/edb438abf88cf4d272c31841f7d2f9ac29d2d86e/tests/Support/SupportStrTest.php#L603), although it passes, returns incorrect results. Actually, the result should be like this - żółta_łódka

**Comment by DarkGhostHunter** [comment]
The same way would happen on a language that doesn't have uppercase, like arabic, chinese, korean or japanese.

You may need to create an snake function for your language exclusively.

**Comment by driesvints** [comment]
You'll need to create your own function for this.
