### ISSUE TITLE
Str::mask get wrong result when first letter equal to second letter

### ISSUE THREAD

**Issue by FuS1** [laravel/framework#42867]
- Laravel Version: 8.83.16
- PHP Version: 7.4.3
- Database Driver & Version: null

### Description:

Str::mask('abcde', '*', 1, -1); =>"a***e"
Str::mask('aaaba', '*', 1,  3);  => "a***a"
Str::mask('abcde', '*', -4, 3);  =>"a***e"
Str::mask('aaaba', '*', -4, 3);  =>"a***a"

But I below case will get wrong result string

Str::mask('aaaaa', '*', 1, -1);  => "***aa"
Str::mask('aaaab', '*', 1,3);     => "***ab"
Str::mask('aaaaa', '*', -4, 3);  => "***aa"
Str::mask('aaaab', '*', -4, 3);  => "***ab"

**Comment by nielsdos** [comment]
This does like the occurrence of this issue: https://github.com/laravel/framework/pull/42295 (which was fixed in 9.x) in 8.x

**Comment by BrandonSurowiec** [comment]
You can make a PR to backport [#42295](https://github.com/laravel/framework/pull/42295) to 8.x as bug fixes are still accepted there.

**Comment by FuS1** [comment]
OK，thanks all
