### ISSUE TITLE
Redis cluster with recent Laravel and phpredis throws various errors with TLS connection.

### ISSUE THREAD

**Issue by InputOutputZ** [laravel/framework#42863]
Hi there, 

I'm reporting a bug and a fix in Redis cluster configuration handling, given recent php Redis no longer expects requirepass as it's deprecated, but expects the auth with user and password in the 6th parameter of RedisCluster as well as context with array of stream keyed array member for Client and CA certificates files location variable, that is in order to establish successful TLS connection with REDIS cluster nodes having tls-auth-clients set to yes in cluster nodes configs.

- Laravel Version: 9.2
- PHP Version: 8.1.3
- Database Driver & Version: Redis, phpredis 6.0.0-dev.

### Description:
I can't get REDIS cluster to work, when I configure Laravel to use phpredis 6.0.0-dev cluster in database.php with TLS scheme and client certificate authentication enabled, it throws " Connection lost at PhpRedisConnector.php:192 " as well as "AUTH failed while reconnecting at PhpRedisConnector.php:189 " after " Couldn't map cluster keyspace using any provided seed " and with some debugging it returns this error 

```
(ErrorException(code: 0): RedisCluster::__construct(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A00045C:SSL routines::tlsv13 alert certificate required 
```

and in Redis logs returns:-

`Error accepting a client connection: error:0A0000C7:SSL routines::peer did not return a certificate
`

### Steps To Reproduce:
-1 Configure Laravel to use redis cluster with phpredis 6.0.0-dev and TLS scheme with client certificates auth enabled and open Laravel public directory in browser or run php artisan cache:clear.

### Additional Information

This is how I fixed it

Modify createRedisClusterInstance in laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:190 with following:-
```

        if (version_compare(phpversion('redis'), '4.3.0', '>=') && version_compare(phpversion('redis'), '6.0.0-dev', '<')) {
            $parameters[] = $options['password'] ?? null;
        }

        if (version_compare(phpversion('redis'), '5.3.2', '>=') && !is_null($context = Arr::get($options, 'context'))) {
            $parameters['auth'] = $context['auth'];
            $parameters['context'] = $context['stream'];
        }
```

Good luck.

Zakaria.

**Comment by InputOutputZ** [comment]
> Changing the API to work with phpredis 6.0.0-dev is risky, it may change during the development.
> 
> Does it work with PhpRedis 5.3.7?

I haven't tested phpredis 5.3.7. I think it will return the same results using phpredis 6.0.0 that is similar to dev, i.e. an invitable bug that has to be fixed since password meant to work with the deprecated requirepass and flattening of options in parameters array removes auth keys i.e. password and username which is optional yet if had any including itself which is required as well as context and stream in order for at least phpredis 6.0.0 to pick the authentication certificate and pass it to redis successfully otherwise SSL failure errors will be thrown, Please correct me if my findings are incorrect.

Zakaria.

**Comment by tillkruss** [comment]
Can you reproduce this with a 2-3 line non-Laravel script?

If this a bug in PhpRedis we need to report it.

**Comment by InputOutputZ** [comment]
> Can you reproduce this with a 2-3 line non-Laravel script?
> 
> If this a bug in PhpRedis we need to report it.

No its not phpredis extension and it works fine but its Laravel API integration and its incompatible with phpredis 6.0.0.

I am certain in incoming releases the issue will appear to more users therefore addressing it now, should be a good idea, its easy to install the recent phpredis extension locally and test by yourself. Configure the redis cluster nodes with auth client enabled, and pass cafile, local pk and cert file and you will see the errors in logs file leading to internal server error.

Also, make sure to set redis driver for sessions and cache in env.

**Comment by tillkruss** [comment]
I can't reproduce this without a code sample.
