### ISSUE TITLE
I can't eager load a pivot table relation

### ISSUE THREAD

**Issue by jihad28** [laravel/framework#42860]
- Laravel Version: 9.17.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL - v8.0.27

### Description:
Hi everyone

My issues is that i can't eager load a pivot relation only lazy loading is available.

For example i have the following tables

#### Products
| id | name      | barcode_type | barcode      | unit_id | cost | price |
|----|-----------|--------------|--------------|-----------------|------|-------|
| 1  | Product 1 | code128      | 000000000001 | 1               | 10   | 12    |

#### Purchases
| id | warehouse_id | supplier_id | status   | date                | reference_no | note | total |
|----|--------------|-------------|----------|---------------------|--------------|------|-------|
| 1  | 1            | 1           | received | 2022-06-17 17:19:34 | NULL         | NULL | 120   |

#### Units
| id | unit_id | name       | code | multiplier |
|----|---------|------------|------|------------|
| 1  | NULL    | Piece      | Pcs  | 1          |
| 2  | 1       | Dozen - 12 | D-12 | 12         |

And now the pivot table
#### product_purchase
| purchase_id | product_id | unit_id | quantity | cost | subtotal |
|-------------|------------|---------|----------|------|----------|
| 1           | 1          | 2       | 1        | 10   | 120      |

### Models
```php
// Product Model
public function purchases()
{
    return $this->belongsToMany(Purchase::class, 'product_purchase', 'product_id', 'purchase_id')
        ->withPivot('unit_id', 'quantity', 'cost', 'subtotal')
        ->using(ProductPurchase::class);
}

public function unit()
{
    return $this->belongsTo(Unit::class, 'unit_id', 'id');
}


// Purchase Model
public function products()
{
    return $this->belongsToMany(Product::class, 'product_purchase', 'purchase_id', 'product_id')
        ->withPivot('unit_id', 'quantity', 'cost', 'subtotal')
        ->using(ProductPurchase::class);
}


// ProductPurchase Model that extends Pivot
public function unit() // I need to eager load this
{
    return $this->belongsTo(Unit::class, 'unit_id', 'id');
}
```

Note that i want the unit which the product was purchased with not the default product unit

I want to eager load the unit like this.

This will throw that pivot relation does not exist.
```php
$purchase = Purchase::with(['products.pivot.unit'])->first();
```

But i can access it via lazy loading like so:
```php
$purchase = Purchase::with(['products'])->first();

foreach($purchase->products as $product) {
    info($product->pivot->unit);
}
```
But this will produce N+1 queries

This is the desired output for `$purchase`
```json
{
    "id": 1,
    "warehouse_id": 1,
    "supplier_id": 1,
    "status": "received",
    "date": "2022-06-17 07:16:35 AM",
    "reference_no": null,
    "total": 120,
    "note": null,
    "created_at": "2022-06-17 10:53:46 AM",
    "updated_at": "2022-06-17 06:51:27 PM",
    "products": [
        {
            "id": 1,
            "name": "Product 1",
            "barcode_type": "code128",
            "barcode": "000000000001",
            "unit_id": 1,
            "cost": 10,
            "price": 12,
            "pivot": {
                "purchase_id": 1,
                "product_id": 1,
                "unit_id": 2,
                "quantity": 1,
                "cost": 10,
                "subtotal": 120,
                "unit": {
                    "id": 2,
                    "unit_id": 1,
                    "name": "Dozen - 12",
                    "code": "D-12",
                    "multiplier": 12
                }
            }
        }
    ]
}
```

**Comment by ankurk91** [comment]
Can you try this? 

```php
$purchase = Purchase::with(['products.unit'])->first()
```

**Comment by jihad28** [comment]
> Can you try this? 
This will get the default product unit not the pivot unit which the product was purchased on.


The first product was purchased on unit 2 (Dozen-12) this will get unit 1 (Pieces) which is the default unit.

**Comment by alitokmakci** [comment]
`$purchase = Purchase::with(['products.pivot.unit'])->first();`
This will not work cause you don't have relationship called pivot.

Did not test it but maybe this can work.
```
$purchase = Purchase::with('products', function($q) {
    $q->pivot->unit()->get();
})->get();
```

or you can create a new relationship method:
```
// App\Models\Product.php

public function purchasedUnits() {
    return $this->belongsToMany(Unit::class, 'product_purchase')
        ->withPivot('unit_id', 'quantity', 'cost', 'subtotal');
}

// Controller
Purchase::with('products.purchasedUnits')->first();
```
This should give you something like:

```
{
    "id": 1,
    "warehouse_id": 1,
    "supplier_id": 1,
    "status": "received",
    "date": "2022-06-17 07:16:35 AM",
    "reference_no": null,
    "total": 120,
    "note": null,
    "created_at": "2022-06-17 10:53:46 AM",
    "updated_at": "2022-06-17 06:51:27 PM",
    "products": [
        {
            "id": 1,
            "name": "Product 1",
            "barcode_type": "code128",
            "barcode": "000000000001",
            "unit_id": 1,
            "cost": 10,
            "price": 12,
            "purchased_units": [
                 {
                    "id": 2,
                    "unit_id": 1,
                    "name": "Dozen - 12",
                    "code": "D-12",
                    "multiplier": 12,
                    "pivot": {
                        "purchase_id": 1,
                        "product_id": 1,
                        "unit_id": 2,
                        "quantity": 1,
                        "cost": 10,
                        "subtotal": 120,
                     },
                 },
             ],
         }
     ]
}
```

and sorry but I still do not understand why you need a ProductPurchase model.

**Comment by jihad28** [comment]
Hi thanks for your time

> Did not test it but maybe this can work.

Tried this but no luck same error as `$purchase = Purchase::with(['products.pivot.unit'])->first();` relation pivot not found

> or you can create a new relationship method:

This will change the data structure pivot will be inside `purchased_units` as it should be `unit` inside `pivot`

> and sorry but I still do not understand why you need a ProductPurchase model.

Well I made this pivot model to get the unit that the product was purchased with.

Also I can still get the unit with lazy load like I mentioned before but I wanted to prevent N+1 quires and eager load it.
I looked through docs and other forms but unfortunately pivot relations can't be eager loaded.

If eager loading can be implemented for pivot relations it will help in a lot of projects and cases.

**Comment by SuperDJ** [comment]
@jihad28 perhaps you can take a look at the https://github.com/ajcastro/eager-load-pivot-relations package. This has a `pivot` relation.

**Comment by jihad28** [comment]
@SuperDJ Hi I saw this package but last release was 3 years ago and doesn't support Laravel 9

**Comment by SuperDJ** [comment]
@jihad28 where does it say it doesn't support Laravel 9? I'm using it with Laravel 9 and PHP8.1. As far as I know and can tell it only requires PHP5.6 or higher.

**Comment by jihad28** [comment]
@SuperDJ Well latest release is written Added support for Laravel 6 so I just thought it doesn't work for v9 sorry 😃.

I will try for Laravel 9 and see if it works well. Thanks.

**Comment by jihad28** [comment]
@SuperDJ 
Tried this package with Laravel 9 and doesn't work throws error.
I made a git repo to test it if you want to try it yourself or anyone else.

https://github.com/jihad28/test-eager-load-pivot-relation

Also made a seeder so you can just run the command and test it.

**Comment by rodrigopedra** [comment]
So you want to use a 3-way pivot table. As your pivot table have keys for products, purchases and units.

I am assuming this from your reply to @ankurk91 , as you said eager loading `products.unit` would not load the correct unit, as you expect the unit recorded on the `product_purchase` table to be loaded, not the one from `products` table.

Laravel does not support this out of the box. 

You can try to write a custom relation, or add a join statement to your relation definition. Or to eager load after first retrieval:

~~~php
$purchases = Purchase::with(['products'])->get();

$purchases->flatMap(fn ($purchase) => $purchase->products)->pluck(`pivot')->load('unit');
~~~

But this will only work due to you have a `unit` relation defined in your pivot model.

Further helping you with this would be beyond the scope of this issue tracker, so I advise you to seek help in the support channels as outlined on the documentation:

https://laravel.com/docs/9.x/contributions#support-questions

**Comment by jihad28** [comment]
@rodrigopedra 
I knew Laravel didn't support this but wanted to know of a way to eager load it.
I was thinking of a join but yours is better for multiple relations with pivot table.

I'm going to close this issue as it's solved.
Thank you so much.

**Comment by rodrigopedra** [comment]
@jihad28 as you already knew this was an unsupported feature and not a bug, please next time open a discussion or seek help in the support forums as it is stated in the docs.

This issue tracker is for bugs only.

**Comment by jihad28** [comment]
@rodrigopedra 

I only knew that after a lot of looking, it would be better if it was stated in the docs as warning.
First I thought it was a bug but it wasn't. 

Next time I will put it on a support forum, Sorry for the mistake.

**Comment by etimashev** [comment]
I solve this on Laravel 10 by [https://github.com/ajcastro/eager-load-pivot-relations](https://github.com/ajcastro/eager-load-pivot-relations).

// Department class
`use EagerLoadPivotTrait;`

// Profile class
```
public function departments(): BelongsToMany
{
    return $this->belongsToMany(Department::class)
        ->using(DepartmentProfile::class)
        ->withPivot(['category_id', 'subcategory_id']);
}
```

// DepartmentProfile class
```
public function category(): HasOne
{
    return $this->hasOne(Category::class, 'id', 'category_id');
}

public function subcategory(): HasOne
{
    return $this->hasOne(Subcategory::class, 'id', 'subcategory_id');
}
```

```
dd(Profile::with([
     'departments.pivot.category',
     'departments.pivot.subcategory',
])->latest()->first());
```
returns
```
App\Models\Profile {#▼
  #relations: array:1 [▼
    "departments" => Illuminate\Database\Eloquent\Collection {# ▼
      #items: array:1 [▼
        0 => App\Models\Glossaries\Department {# ▼
          #...
          #relations: array:1 [▼
            "pivot" => App\Models\Pivots\DepartmentProfile {#▼
              #...
              #relations: array:2 [▼
                "category" => App\Models\Glossaries\Category {}
                "subcategory" => App\Models\Glossaries\Subcategory {}
              ]
            }
        }
    }
}
```

**Comment by artygrand** [comment]
@etimashev is it really works without any tweaks?

I also on Laravel 9, as op, and get error
"Call to undefined relationship [pivot] on model [App\Models\Yard]."
when call
"with('yards.pivot.confirmed')"
