### ISSUE TITLE
In resources, conditional attributes don't respect the when condition

### ISSUE THREAD

**Issue by Ham3D** [laravel/framework#42866]
- Laravel Version: 9.17
- PHP Version: 8.1
- Database Driver & Version:

### Description:
Imagine this scenario:
in our resource we have a function that does some calculation, lets name it `foo()`

a user can be an admin, if a user with admin privilege logs in, we load some additional info for user, for example :
**normal user :** 
* $user->isAdmin = false
* $user->adminInfo = null

**admin user:**
* $user->isAdmin=true
* $user->adminInfo = some data

when in resources we check for this status like this:

    return [
      ...
      'adminInfo'=> $this->when($user->isAdmin, $this->foo($user)),
    ];

and foo function:

    foo($user){
	    // some calculations on $user->adminInfo
    }

for admin users this works fine but for normal users that `$user->isAdmin == false` and we know `$user->adminInfo` is **null**, in resource it still try to run the foo method but  `$user->adminInfo` is null and this creates an error.

in my opinion, in `$this->when()` scenario, when the condition is false, the rest should be skipped (instead of calculatin the result but if the condition is false just dont return anything)

**Comment by ash-jc-allen** [comment]
Hey @Ham3D! I might be wrong here, but I think you need to change your code from:

```php
  'adminInfo'=> $this->when($user->isAdmin, $this->foo($user)),
```

to:

```php
  'adminInfo'=> $this->when($user->isAdmin, fn() => $this->foo($user)),
```

With the way you have it written at the moment, `$this->foo($user)` will be invoked straight away. Whereas, if you wrap it in a closure, it'll only get run if the framework invokes it behind-the-scenes.

It covers it briefly in this part of the docs: https://laravel.com/docs/9.x/eloquent-resources#conditional-attributes

Hopefully that helps a little bit? 🙂

**Comment by Ham3D** [comment]
@ash-jc-allen  silly me, you are right

**Comment by ash-jc-allen** [comment]
It happens to the best of us! Glad it was a nice, easy fix 😄
