### ISSUE TITLE
array|nullabe validation rule does not  work as expected (does not retrieve the value if its null)

### ISSUE THREAD

**Issue by AlEsGoGit** [laravel/framework#42877]
- Laravel Version: 9.17.0
- PHP Version: 8.1.4
- Database Driver & Version:

### Description:
Adding an 'array|nullable' validation rule to the request input does not return the field when the input is null.

`$input = $request->validate([
            'foo' => 'array|nullable',
            'foo.bar' => 'integer|nullable',
]);`

When the value of test is null in the request, the validate method does not return the value, so $input does not have the test key as expected.

Expected -> $input  = [test => null]

Current behaviour -> $input = []

It seems to be related with the nested rules, when the foo.bar rule is not present it works fine.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by GTCrais** [comment]
Bump on this, I think this is a valid issue.

If request data is `['foo' => null]` and you validate it through `'foo' => ['nullable', 'array']`, `$validated` data will be `[ ]` when I would expect it to be `['foo' => null]`.

**Comment by helitik** [comment]
For information, its a breaking changes with 9.x : https://laravel.com/docs/9.x/upgrade#unvalidated-array-keys

**Comment by nafetsrybak** [comment]
Why its closed? This is a bug

**Comment by nafetsrybak** [comment]
> For information, its a breaking changes with 9.x : https://laravel.com/docs/9.x/upgrade#unvalidated-array-keys

Why its closed? This is a bug
