### ISSUE TITLE
Not working dynamic database connection with new configuration files.

### ISSUE THREAD

**Issue by manojkumarlinux** [laravel/framework#42876]
### Discussed in https://github.com/laravel/framework/discussions/42875

<div type='discussions-op-text'>

<sup>Originally posted by **manojkumarlinux** June 20, 2022</sup>
Now Laravel Config::set is not working.
So I'm trying to connect my database dynamically with my new config(config/module_name/database.php) file but not worked.

```
class User extends Authenticatable
{
    protected $connection = Config::get("module_name.database.connection");

}
```
due to this vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php line number: 163

`        $connections = $this->app['config']['database.connections'];
`

The database manager only checks inside the connection (config/database.php) array.
but I'm using a new config file config/module_name/database.php

I tried to write my own Class DatabaseManger, Interface Illuminate\Database\ConnectionResolverInterface with a class name alias not working because of the file location. 
</div>

**Comment by driesvints** [comment]
Please don't move discussions to issues.
