### ISSUE TITLE
Faker singleton does not behave like singleton when providing locale

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#42880]
- Laravel Version: 9.17.0
- PHP Version: 8.1.7

### Description:

When making multiple fakers with a specific locale, the `unique` method does not work because it is being reset every time you want a faker with a specific locale. This does not seem correct when faker is registered as as singleton:
https://github.com/laravel/framework/blob/8902690a87f87f516e298c6e00fa1dbf8a0224dd/src/Illuminate/Database/DatabaseServiceProvider.php#L89-L99
The `static::$fakers[$locale]->unique(true);` should not be there, I think.

### Steps To Reproduce:

```php
$a = app()->make(\Faker\Generator::class);
$a->unique()->numberBetween(1, 1);
// Returns 1

$b = app()->make(\Faker\Generator::class);
$b->unique()->numberBetween(1, 1);
// This throws an exception, which is correct
```

When using a "locale" parameter:
```php
$a = app()->make(\Faker\Generator::class, ['locale' => 'en']);
$a->unique()->numberBetween(1, 1);
// Returns 1

$b = app()->make(\Faker\Generator::class, ['locale' => 'en']);
$b->unique()->numberBetween(1, 1);
// Returns 1
// But this should throw an exception, because the value '1' has already been used!
```

**Comment by driesvints** [comment]
This was changed here: https://github.com/laravel/framework/pull/32703. @deleugpn can you weigh in here?

**Comment by timacdonald** [comment]
Just an FYI that this problem doesn't exist with the new global `fake()` helper...

```php
fake()->unique()->numberBetween(1, 1)
// => 1

fake()->unique()->numberBetween(1, 1)
// OverflowException with message 'Maximum retries of 10000 reached without finding a unique value'

fake('en_AU')->unique()->numberBetween(1, 1)
// => 1

fake('en_AU')->unique()->numberBetween(1, 1)
// OverflowException with message 'Maximum retries of 10000 reached without finding a unique value'

fake()->unique()->numberBetween(1, 1)
// OverflowException with message 'Maximum retries of 10000 reached without finding a unique value'

fake('en_AU')->unique()->numberBetween(1, 1)
// OverflowException with message 'Maximum retries of 10000 reached without finding a unique value' 
```

**Comment by driesvints** [comment]
@gdebrauwer as a workaround, for now, please use the new global fake helper.
