### ISSUE TITLE
Dependency (Symfony 6.1) requires PHP 8.1

### ISSUE THREAD

**Issue by qminds** [laravel/framework#42891]
- Laravel Version: 9.16.0
- PHP Version: 8.0.19

### Description:

Laravel framework requires `Symfony` packages of the `^6.0` version, so the (currently latest) 6.1 version is installed. However, due to [this post](https://symfony.com/blog/symfony-6-1-will-require-php-8-1), there is a breaking change in this minor update that requires at least PHP 8.1, which leads to the following message:

> Your Composer dependencies require a PHP version ">= 8.1.0"

Ignoring the Composer platform recommendations doesn't seem right.

Does this mean that PHP 8.0 is no longer supported?

**Comment by driesvints** [comment]
PHP 8.0 is still supported on 9.x but you'll need to use Symfony 6.0.x. Normally Composer can always handle the resolving of this. However, it's recommend that you upgrade to PHP 8.1 as much libraries are requiring this as a minimum these days.

**Comment by qminds** [comment]
For some reason Composer didn't handle it.
I solved the issue by requiring the `6.0.*` versions of Symfony-related packages in my `composer.json`.
Thanks.
