### ISSUE TITLE
Cannot differenciate between json object or array

### ISSUE THREAD

**Issue by NicoHood** [laravel/framework#42904]
- Laravel Version: 9.15.0
- PHP Version: 8.1.x
- Database Driver & Version: sqlite

### Description:
Following up on #42719 I want to report, that there is currently no way to differenciate between a json object `{}` or array `[]` as the `Request` class [decodes the json always into an associated php array](https://github.com/laravel/framework/commit/cd9fcd06b3970641e91d6127b31b39fc239521e2). This gives us no option to ever know the difference between object or array.

This code was added in the early 4.0 beta, so I expect that this has room to reevaluate.

### Steps To Reproduce:
1. Create a simple json rest api
2. Send e.g. a json array or object
3. There is no way to programatically differenciate between the two

I want to note that there is a workaround, but the workaround does not fit all use cases. You could use [`array_is_list()`](https://www.php.net/manual/en/function.array-is-list.php) to check if the array is more a list or an object. However this function is super wonky, you can see the examples in the php docs. Also this will never ever work with empty arrays/lists.

If we could return objects instead of associated arrays, we also have the option to add an `object` validation rule to the validator. This way we could only allow json arrays or objects, and not just both.

**Comment by NicoHood** [comment]
I am sorry, I have no clue what you are talking about. Do I need to precise my question? I do not get what you want to tell me.

**Comment by driesvints** [comment]
Giving that this has been the behavior since Laravel 4, I don't think there's any issue here. We're not looking to make changes to this implementation to be mindful of BC breakages.

**Comment by NicoHood** [comment]
No way? What about in newer versions? I mean this would be an essential feature, that is just currently not possible to use. Arn't there any options to keep backward compatibility but still allow a bugfix?
