### ISSUE TITLE
Trying to add a macro for the Eloquent Builder causes an error if you use named parameters

### ISSUE THREAD

**Issue by tminich** [laravel/framework#42905]
- Laravel Version: 9.18.0
- PHP Version: 8.1.7
- Database Driver & Version: not relevant

### Description:

Calling the `macro` method on the Eloquent Builder class using named parameters causes an error. As Laravel 9 dropped support for PHP-versions that do not support named parameters this should definitely work.

### Steps To Reproduce:

```php
use Illuminate\Database\Eloquent\Builder;

Builder::macro(name: 'testMacro', macro: function () {
    // ...
});
```

Result:
```

   ErrorException

  Undefined array key 0

  at <redacted>\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:1854
    1850▕      */
    1851▕     public static function __callStatic($method, $parameters)
    1852▕     {
    1853▕         if ($method === 'macro') {
  ➜ 1854▕             static::$macros[$parameters[0]] = $parameters[1];
    1855▕
    1856▕             return;
    1857▕         }
    1858▕

  1   <redacted>\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:1854
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 0", "<redacted>\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php")
```

(I'm not using mixins, but the code handling the `mixin` method a few lines below the line causing the exception will probably not work either)
Edit: Same issue will probably affect local macros in the `__call` method of the Eloquent Builder.

**Comment by driesvints** [comment]
Just don't use named parameters here.
