### ISSUE TITLE
FirstOrNew Eloquent Method inside Jobs returning \ModelNotFoundException instead of a new Model instance.

### ISSUE THREAD

**Issue by devsquad-victor-lima** [laravel/framework#42910]
- Laravel Version: 9.18.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0

### Description:
Hello guys, I got into this situation today where I have a Job running on Horizon, implementing the `ShouldQueue` interface, and then when `Model::firstOrNew` is called and the database record is not found, it's acting like `firstOrFail` method and returning `Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\...]`.

When I remove the ShouldQueue interface it works.
The error also happens if I just change the `QUEUE_CONNECTION` to `sync` instead of `redis` or `database`.
I think it's related to this interface, I don't know, but I thought it'd nice to report it here.

### Steps To Reproduce:
Run any `firstOrNew` method inside a queued job.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
