### ISSUE TITLE
Blade if statement not working well inside tag

### ISSUE THREAD

**Issue by omerfdmrl** [laravel/framework#42911]
- Laravel Version: 9.17.0
- PHP Version: 8.0.11
- Database Driver & Version: 10.4.21-MariaDB

### Description:
I'm trying to use if statement inside class attribute in **i** tag.  When I don't use veriable directly it's working.

### Steps To Reproduce:
1. Create function inside my model file;
```php
public function getIsDownAttribute($value){
    return $this->attributes['is_down'] = in_array(Auth::user()->id ?? 0,(array)json_decode($this->attributes['down']));
}
```
2. Try to use inside blade;
```blade
<i  class="down fa fa-arrow-down @if($post->is_down) active @endif"></i>
```
This code not working. When I try outside of i tag;
```blade
@if($post->is_down) foo @endif
<i class="down fa fa-arrow-down"></i>
```
**foo** is displaying on screen.
3. Don't use veriable directly.
```blade
@php
    $a = $post->is_down;
@endphp
<i class="down fa fa-arrow-down @if($a) active @endif"></i>
```
it's working successfully.

Note: I try this codes too;
`{{$post->is_down ?? 'active'}}`
`{{$post->is_down ? 'active':''}}`

Note2: Here is my outputs;
`dd($post->is_down)` => `True` ([ScreeShot](https://prnt.sc/bLBROohnSdag))
`var_dump($post->is_down)` => `bool(true)`
`gettype($post->is_down)` => `boolean`

**Comment by dev-buntoo** [comment]
```
class User extends Model
{
    /**
     * Get the user's first name.
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function firstName(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => ucfirst($value),
        );
    }
}
```

**Comment by TENMAJKL** [comment]
Maybe try to look at the compiled template in storage/framework/views and send how does look this part.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
