### ISSUE TITLE
Passing a PHP expression with an incomplete set of parentheses to a component results in an exception

### ISSUE THREAD

**Issue by tkuijer** [laravel/framework#42939]
### Versions
- Laravel Version: 9.18.0 (Also tested on 9.2.0 and 8.71.0)
- PHP Version: 8.1.1 (zend engine 4.1.1, opcache 8.1.1, xdebug 3.1.1)
- Database Driver & Version: PDO MySQL 5.7.34

### Description:
When I pass a PHP expression which contains an incomplete set of parentheses to a component, the resulting rendered template contains invalid PHP.

While the testcase is minimal, the same thing also occurs when passing the parentheses to a string for translation: 
for example `__('(error')`

### Steps To Reproduce:
1. create a view-only component that accepts a prop `php artisan make:component Component --view`
2. include the component and pass a php value containing a incomplete set of parentheses:
```html
<!-- This results in an 'syntax error, unexpected token "endif", expecting end of file' Exception -->
<x-component :value="'(error'" />
<!-- This results in an 'syntax error, unexpected identifier "component", expecting "]"' Exception -->
<x-component :value="'error)'" />
<!-- This works -->
<x-component :value="'(works)'" />
```

### Repository displaying the bug
https://github.com/tkuijer/blade-stringbug

**Comment by driesvints** [comment]
This is best passed a variable.

**Comment by tkuijer** [comment]
@driesvints 
That would work for the example minimal breaking case, but is unusable when building a form that has translations for example.

**Comment by rodrigopedra** [comment]
> In my opinion something as simple as...

PRs are welcome =)
