### ISSUE TITLE
Laravel-echo : Customizing The Authorization Request

### ISSUE THREAD

**Issue by ParzivalLashly** [laravel/framework#42947]
### Discussed in https://github.com/laravel/framework/discussions/42946

<div type='discussions-op-text'>

<sup>Originally posted by **ParzivalLashly** June 25, 2022</sup>
hi, im using **Laravel 8** for api backend and **Reactjs** for frontend, **Laravel echo@1.11.7** and **Laravel echo server** with **socket.io-client** for ws connections between front and backend
for some reasons i need to authenticate private channels with custom route and controller.
problem is Laravel echo authorizer not working ( actually nothing happend ).

```
window.Echo = new Echo({
    // ...
    authorizer: (channel, options) => {
        return {
            authorize: (socketId, callback) => {
                axios.post('/api/broadcasting/auth', {
                    socket_id: socketId,
                    channel_name: channel.name
                })
                .then(response => {
                    callback(false, response.data);
                })
                .catch(error => {
                    callback(true, error);
                });
            }
        };
    },
})
```
</div>

**Comment by driesvints** [comment]
Please don't move discussions to issues.
