### ISSUE TITLE
Passing a PHP expression with an incomplete set of parentheses to a component results in an exception

### ISSUE THREAD

**Issue by tkuijer** [laravel/framework#42940]
Because in my opinion the last issue got closed without valid reason:

> This is best passed as a variable.

That would work for the example minimal breaking case, but is unusable when building a form that has translations for example. The bug occurs when having any missing parenthesis in any PHP expression passed to a component.

**Something as simple as an unclosed set of parentheses should NEVER result in the blade compiler breaking.**

### Versions
- Laravel Version: 9.18.0 (Also tested on 9.2.0 and 8.71.0)
- PHP Version: 8.1.1 (zend engine 4.1.1, opcache 8.1.1, xdebug 3.1.1)
- Database Driver & Version: PDO MySQL 5.7.34

### Description:
When I pass a PHP expression which contains an incomplete set of parentheses to a component, the resulting rendered template contains invalid PHP.

While the testcase is minimal, the same thing also occurs when passing the parentheses to a string for translation: 
for example `__('(error')`

### Steps To Reproduce:
1. create a view-only component that accepts a prop `php artisan make:component Component --view`
2. include the component and pass a php value containing a incomplete set of parentheses:
```html
<!-- This results in an 'syntax error, unexpected token "endif", expecting end of file' Exception -->
<x-component :value="'(error'" />
<!-- This results in an 'syntax error, unexpected identifier "component", expecting "]"' Exception -->
<x-component :value="'error)'" />
<!-- This also doesn't work -->
<x-component :value="__('(error')" />
<x-component :value="ucfirst('error)')" />
<!-- This works -->
<x-component :value="'(works)'" />
```

### Expected result:
I expect the value to get rendered without exceptions, and containing the single parenthesis

### Repository displaying the bug
https://github.com/tkuijer/blade-stringbug

**Comment by driesvints** [comment]
Please don't re-open closed issues. Just use a variable in this case.

**Comment by tkuijer** [comment]
@driesvints 
Then please re-open the original issue, since using a variable is the solution to this case, but doesn't fix the bug at all.

**Comment by driesvints** [comment]
There's no bug. The Blade compiler cannot handle every situation. For this case, you should use a variable.
