### ISSUE TITLE
Cookie::expire & Cookie::forget Not recognised by IDE

### ISSUE THREAD

**Issue by wavedeck** [laravel/framework#42958]
- Laravel Version: v9.18.0
- PHP Version: 8.1.6
- PHPStorm Version: 2021.3.3
- Laravel IDE Plugin: 0.15.4

### Description:
I am trying to delete a Cookie by using ```Cookie::expire($cookie_name)``` of the \Illuminate\Support\Facades\Cookie class.
It works as expected, but PHPStorm doesn't recognise these Methods. I tried to reindex the project but that didn't solve the issue. Warning:  ```Method 'expire' not found in Illuminate\Support\Facades\Cookie```

### Steps To Reproduce:

1. Create a new Composer Project in PHPStorm with the laravel/laravel package.
2. Make a Route to create a cookie using  \Illuminate\Support\Facades\Cookie::queue(...)
3. Make another Route to expire/delete the Cookie using \Illuminate\Support\Facades\Cookie::expire('SAME_COOKIE_NAME')

Admire PHPStorm complaining, that there is no ```expire``` Method on the Cookie Facade.

**Comment by selcukcukur** [comment]
Have you tried the `cookie()->expire('cookieName')` method for this?

**Comment by wavedeck** [comment]
Hi @selcukcukur. YESS! IDE Intellisense works using the cookie() helper function. Thank you for this tipp! I'm wondering why this is nowhere mentioned in the official laravel docs.

**Comment by selcukcukur** [comment]
@wavedeck I don't have clear information on this subject, it may have been overlooked.

**Comment by rodrigopedra** [comment]
Façades provides a way to proxy static method calls to an instance resolved from the container. Therefore they don't contain the underlying methods themselves and IDE cannot guess which methods it proxies without aids such as dokblocks or shallow classes that replicate the inner instance.

A IDE, as I am writing this, will resolve from the `Cookie` façade, in addition to the methods already defined in it, the methods: `getQueuedCookie()`, `unqueue()` and `queue()`, as the three of them are defined in the `Cookie` façade's class docblock:

https://github.com/laravel/framework/blob/4d46bda6f19d490080512fa053065081f737bf2f/src/Illuminate/Support/Facades/Cookie.php#L5-L12

This methods don't exist in the `Cookie` façade class definition, but a call to each of them is proxied to the underlying `\Illuminate\Cookie\CookieJar` instance, as noted on the `@see \Illuminate\Cookie\CookieJar` docblock tag above.

But `\Illuminate\Cookie\CookieJar` defines many other public methods, such as the `expire()` and `forget()` you noticed as not recognized by your IDE.

This is why packages such as https://github.com/barryvdh/laravel-ide-helper exist. To create shallow class stubs to help IDE resolve façade references, among other things such as a model field, that in the Eloquent ORM are not defined before hand, and as such an IDE won't suggest to autocomplete them automatically.

If you search previous PRs, there a several PRs that progressively adds missing public methods from a façade's underlying instance  to a façade class definition, to provide IDE autocompletion without the need to install an additional package. 

If you follow this search link: https://github.com/laravel/framework/pulls?q=is%3Apr+is%3Amerged+docblock+facade you will see most PRs in the results just add missing public methods to a Façade's class definition docblock. And I am sure many other PRs doing the same are not listed by this query string.

There was a discussion some years ago if this docblocks should be maintained in sync with their underlying instances counterpart's public methods by maintainers, or by the community. And it was decided they would be added by demand from PRs contributed by the community.

The reason the `cookie()` helper works as you'd expect, is that the `cookie()` helper's docblock informs the IDE its return type is a `\Illuminate\Cookie\CookieJar` instance, so the IDE can auto-guess the methods:

https://github.com/laravel/framework/blob/4d46bda6f19d490080512fa053065081f737bf2f/src/Illuminate/Foundation/helpers.php#L293-L307

As such, an IDE not being able to autocomplete a method proxied by a façade, is not a bug. And even if your IDE complains it cannot resolve a method, your code would still work, again not rendering it as a framework's bug.

I do understand the benefits of having autocompletion, and code inspection from an IDE automatically working. I can suggest you 4 alternatives here:

1. Contribute a PR adding the missing public methods from the `\Illuminate\Cookie\CookieJar` to the `Cookie` façade class definition docblock. This a very nice first time contribution =)
2. Use a third-party package such as https://github.com/barryvdh/laravel-ide-helper to provide your IDE with the shallow stubs it needs to properly autocomplete and inspect code
3. As you said you are using PHPStorm, you can consider installing a plugin that helps with this, such as Laravel Idea. Note this is a paid plugin
4. Open a feature request within your IDE issue tracker asking them to add to the IDE code inspection engine the ability to resolve Laravel's façade proxy calls.

A good read about the matter, is the documentation page about Façades:

https://laravel.com/docs/9.x/facades

Hope this helps you out. Happy coding =)

**Comment by wavedeck** [comment]
@rodrigopedra That's a great explaination why things are as they are. Thank you for the Tip that other IDE Plugins might help with that, i'll install one right now ;)

**Comment by rodrigopedra** [comment]
You're welcome! Back in the days I started with Laravel I had the same doubts... Have a nice day =)
