### ISSUE TITLE
Unexpected behaviour when registering multiple Model::creating() event callbacks

### ISSUE THREAD

**Issue by JackWH** [laravel/framework#42952]
- Laravel Version: 9.18.0
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 8

### Description:

Applications may register several Eloquent model callbacks for the same event. In my app, I'm automatically assigning certain values to models throughout their lifecycle. When registering multiple `creating` callbacks, they cause an unexpected early `INSERT` if any of the callbacks return a "truthy" value.

This might be a bug, or it might just be inconsistent behaviour, I'm not sure. Either way it doesn't seem to be documented anywhere, and [works the opposite way](https://laravel.com/docs/9.x/events#stopping-the-propagation-of-an-event) to how we'd normally stop event propagation. If I register several `static::creating()` handlers on the same model class, I'd expect them to run sequentially, and for them *all* to complete, before the model can be considered `created`.

I was caught out by this because of using PHP's short function syntax to define my callback, as shown in the example below. 

### Steps To Reproduce:

1. Create the database schema:

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('my_models', function(Blueprint $table) {
            $table->increments('id');
            $table->string('optional_column')->nullable();
            $table->string('required_column');
            $table->timestamps();
        });
    }
}
```

2. Create the model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class MyModel extends Model
{
    protected $fillable = [
        'optional_column',
        'required_column',
    ];

    protected static function booted(): void
    {
        // 1: Log a message with the Model's initial (empty) attributes when it's being created
        // (This behaves "normally", it logs and continues execution to the next callback as we'd expect.)
        static::creating(static fn(Model $model) => Log::info('Log 1', $model->getAttributes()));

        // 2A: Assign an optional value to the Model, if not already set, using arrow syntax.
        // (🧨 This causes an SQL INSERT error. Returning the model in the callback caused an immediate insert.)
        static::creating(static fn(Model $model) => $model->optional_column === null
            ? $model->optional_column = 'hello world'
            : $model
        );

        // 2B: Assign an optional value to the Model, if not already set, WITHOUT using arrow syntax.
        // (✅ This works as expected. The model attribute is updated and the next callback is handled.)
        static::creating(static function(Model $model) {
            $model->optional_column === null
                ? $model->optional_column = 'hello world'
                : $model;
        });
        
        // 4: Assign a required value to the Model.
        // After this callback executes, the model will be saved successfully.
        static::creating(static function(Model $model) {
            $model->required_column = 'lorem ipsum';
        });
    }
}
```

3. In Artisan, call `\App\Models\MyModel::create()`.

**Comment by mateusjunges** [comment]
Hey @JackWH, it happens because the `creating` model event, dispatched inside the `performInsert` method, is fired using event halting:
https://github.com/laravel/framework/blob/4d46bda6f19d490080512fa053065081f737bf2f/src/Illuminate/Database/Eloquent/Model.php#L1168

This is the signature of `fireModelEvent`:
https://github.com/laravel/framework/blob/4d46bda6f19d490080512fa053065081f737bf2f/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L169

So, when you register a listener for that event calling `static::creating`, if your listener returns any not null values then the `Dispatcher` class will instantly return that response, and the `performInsert` method will try to insert the model to the database.
https://github.com/laravel/framework/blob/4d46bda6f19d490080512fa053065081f737bf2f/src/Illuminate/Events/Dispatcher.php#L254-L256

@driesvints I don't know if you'll consider this a bug, but I kind of agree with @JackWH on this one. I wouldn't expect for the model to be inserted into the database before all the listeners defined for `creating` (which means before inserting the model) are executed. Please let me know your thoughts on this and I can make a PR if it is indeed a bug.

**Comment by rodrigopedra** [comment]
I also agree I would expect a different behavior, specially now when arrow functions that auto-return a value are more common.

@JackWH in the meanwhile, you could convert your arrow functions to regular closures without a return statement.

The only thing I kind of don´t agree is this would be bug.

It is surely unexpected behavior, but changing this behavior that is around for so long looks more like a feature request, at least in my opinion.

But it would be nice if someone could better explain this behavior on the documentation. 

Note all "before" events (the ones ending in `-ing`, such as `creating`) are dispatched using `Dispatcher@until`, which will stop in the first non-null response from a listener, while the "after" events (the ones ending in `-ed`, such as `created`) are dispatched using `Dispatcher@dispatch` which will only halt on the first response equals to `false`. So using arrow functions on these "after" events is fine, as long they don't explicitly return `false`. 

This difference could be better explained in the docs.

**Comment by driesvints** [comment]
> Applications may register several Eloquent model callbacks for the same event.

Afaik we don't document this anywhere and I don't think we support that. What's the reason you can't use a single callback?

**Comment by JackWH** [comment]
@driesvints Traits might want to register their own callbacks in the `bootTrait()` method. For example:

```php
trait HasUuids
{
    public static function bootHasUuids(): void
    {
        static::creating(static fn(WithUuid $model) => $model->{$model->getUuidField()} = Str::uuid()->toString());
    }

    // ...
}
```

A quick search of my codebase shows 3 different packages registering their own model callbacks using traits.

**Comment by driesvints** [comment]
Hah, I forgot we had support for that. We should document that really.

**Comment by driesvints** [comment]
It looks like this will require a change in behavior so for now, we're not categorizing this as a bug. A PR to attempt to change this behavior has been opened at master. Let's see how that goes.
