### ISSUE TITLE
Cursor pagination fails if records have been deleted

### ISSUE THREAD

**Issue by claudiofabiao** [laravel/framework#42962]
- Laravel Version: 9.18.0
- PHP Version: 8.1.2
- Database Driver & Version: MariaDB 10.4.22

### Description:
When trying to follow a cursor returned by `cursorPaginate()`, if records have been deleted, a server error response (500) is returned.

An exception with the message "only arrays and objects are supported when cursor paginating items" is being thrown by Laravel.

This does not appear to be the expected behavior.

### Steps To Reproduce:
Simply use cursor pagination (with `cursorPaginate()`) in a query, retrieve part of the records, delete all records and try to follow the cursor.

**Comment by selcukcukur** [comment]
@claudiofabiao It is difficult to understand in this way, can you explain all the methods and processes you use in order to understand.

**Comment by claudiofabiao** [comment]
Hi, @selcukcukur.

I created a repository to demonstrate: [](https://github.com/claudiofabiao/bug-report).

Steps to reproduce:

- clone the repository
- run `php artisan migrate --seed
- load the first 25 tasks into _/tasks_ and store `next_cursor` for later use
- delete all DB tasks
- now try following the stored `next_cursor` via /tasks?cursor=CURSOR_HERE

An exception will be thrown.

**Comment by selcukcukur** [comment]
`return Task::query()->cursorPaginate(25);`

I didn't have any problems with a clean install this way.

**Comment by selcukcukur** [comment]
@claudiofabiao It looks like everything is fine. Something you did or an external action you did is causing the problem. Everything seems fine in my tests. I also followed the steps you did.

**Comment by selcukcukur** [comment]
@php
    $users = \App\Models\User::query()->cursorPaginate(1);
            @endphp

    <div class="container">
        @foreach ($users as $user)
            {{ $user->name }}
        @endforeach
    </div>
    {{ $users->links() }}

I haven't fully studied your usage, though. This is the shape you should use.

**Comment by claudiofabiao** [comment]
Hi, @selcukcukur.

Sorry, but I do not understand.

Did you delete the records and then try to follow `next_cursor`?

What was the response received?

I've attached the response I get.
![Screenshot](https://user-images.githubusercontent.com/25290007/175833563-32b4fa28-4bd2-4b46-9d6f-e861c60a7c4b.png)

**Comment by selcukcukur** [comment]
@claudiofabiao I misunderstood what you said. Now I fully understand.

**Comment by rodrigopedra** [comment]
Sent PR #42963 to address this issue

**Comment by claudiofabiao** [comment]
Hi, @selcukcukur and @rodrigopedra.

I thank you very much for your attention.

I will follow the PR #42963.

I am available to help, if needed.
