### ISSUE TITLE
Bus::batch gives incorrect information ?

### ISSUE THREAD

**Issue by ahmetbarut** [laravel/framework#42968]
- Laravel Version: 8.40
- PHP Version: 8.0
- Database Driver & Version: mysql  Ver 15.1

### Description:
Greetings, I'm trying to use `Bus::batch` to monitor the status of Queues but it gives wrong information about queue status. And it turned out to be -67, although the total row was 111?

### Steps To Reproduce:
```php
      // ImportController.php
        Bus::batch($queues)
            ->name('import-company')
            ->dispatch();
```
```php
// InternshipImport.php

namespace App\Jobs;

use App\Models\City;
use App\Models\User;
use Illuminate\Bus\Batchable;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;

class InternshipImport implements ShouldQueue
{
    use Batchable, Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $users;

    public $timeout = 150;

    public $tries = 25;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Collection $users)
    {
        $this->users = $users;
    }
    
    ...
```

![Ekran Resmi 2022-06-27 14 35 09](https://user-images.githubusercontent.com/36641723/175932287-03d329b2-fe77-4be6-bc4d-2f5388cb5ebb.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by ahmetbarut** [comment]
@driesvints I asked for help with this problem in the channels you specified, but since there was no response, I opened the problem here.
