### ISSUE TITLE
Laravel 9.18.0 breaks with no discernible error

### ISSUE THREAD

**Issue by gioblu** [laravel/framework#42972]
- Laravel Version: 9.18.0
- PHP Version: 8.1.5
- Database Driver & Version: N/A

### Description:
Laravel breaks (without a discernible error message) when a route is defined with the same name as a directory present in the public folder. @jucode77

### Steps To Reproduce:
1. Define a route with the name "test"
2. Creare a directory "test" in public
3. The error will occur trying to resolve the address of the defined route

**Comment by driesvints** [comment]
What "breaks"? What happens and what do you expect to happen?

**Comment by lk77** [comment]
Laravel can't do anything about server misconfigurations

**Comment by ankurk91** [comment]
What web server you are using to serve the project?

If you are using apache, make sure rewrite module is enabled
