### ISSUE TITLE
Can't use @class on nested anonymous component

### ISSUE THREAD

**Issue by bram-pkg** [laravel/framework#42977]
- Laravel Version: 9.18.0
- PHP Version: 8.1.7
- Database Driver & Version: MySQL (not relevant)

### Description:

When using `@class` in Blade, on an anonymous, nested component, it does not pick up the component and renders `<x-icon></x-icon>`, without any processing.

### Steps To Reproduce:

https://github.com/bram-pkg/class-directive-bug

Use `@class` on a component, results in the component not rendering as the contents of that component, but just the raw tag. In this case `<x-icon/>`

**Comment by aguingand** [comment]
A workaround is to use:
```blade
<x-icon :class="Arr::toCssClasses(['...'])" />
```

**Comment by driesvints** [comment]
@bram-pkg can you re-create that repo with the following command please so the skeleton isn't in the same commit?

```bash
laravel new bug-report --github="--public"
```

**Comment by bram-pkg** [comment]
Sure thing.

**Comment by bram-pkg** [comment]
https://github.com/bram-pkg/class-directive-bug

@driesvints

**Comment by bram-pkg** [comment]
The output of `welcome.blade.php` is now:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Component &#64;class bug</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>

<div>
    <x-icon class="bi-umbrella pe-2"/>
    Umbrella
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>
```

But should include the `<i class.....></i>` tag from `components/icon.blade.php`.

**Comment by driesvints** [comment]
Thanks @bram-pkg, that was helpful. We can confirm this bug. Would appreciate any help with figuring out a fix for the compiler.

**Comment by aguingand** [comment]
What about allowing array syntax directly as attribute ? 
```blade
<x-icon :class="['pr-3' => true]" />
```

**Comment by bram-pkg** [comment]
Spent an hour digging into the source code, and debugging is a bit hard with all these regexes :sweat_smile:. Hopefully someone more knowledgeable on the inner workings of the Blade compiler engine have an idea.

**Comment by driesvints** [comment]
I'm going to close this one right now since this really just isn't something we support right now. But I'm hopeful for the PR sent in by @aguingand which looks promising. Thanks all.

**Comment by Naoray** [comment]
I think this bug is still not 100% solved. It now works for anonymous components that don't have any slots, but using a default slot will throw an exception `syntax error, unexpected token "endif", expecting end of file`

```html
<! -- works -->
 <x-button.outlined-link @class(['text-3xl'])" />

<! -- will throw ParseException -->
<x-button.outlined-link @class(['text-3xl'])">
    Foo
</x-button.outlined-link>
```

**Comment by aguingand** [comment]
@Naoray You have an extra `"`, it should work if you remove it
```diff
- <x-button.outlined-link @class(['text-3xl'])">
+ <x-button.outlined-link @class(['text-3xl'])>
```

**Comment by Naoray** [comment]
@aguingand corrected! I didn't have it when trying it out locally.

**Comment by aguingand** [comment]
My PR is not released but you can try it by requiring `9.x-dev` version

**Comment by Naoray** [comment]
@aguingand ah right. I thought it was already released. Sorry for the trouble :)
