### ISSUE TITLE
New fake() helper breaks previous custom providers

### ISSUE THREAD

**Issue by Patabugen** [laravel/framework#42988]
- Laravel Version: 9.18.0
- PHP Version: 8.0.20

### Description:
The `fake()` helper [introduced last week](https://github.com/laravel/framework/commit/7746337149a7ffd6b4a862d9bd54593cf3520708) correctly [segments singletons by locale](https://github.com/laravel/framework/issues/42880) however this also means it breaks custom providers (since it changes the abstract name passed to `app()->singleton()`.

I'm not sure what the best solution is, whether to just add it to the upgrade notes as a breaking change (is it breaking if the helper is new?), whether to have segmenting by locale as optional, or perhaps change the behaviour of `fake()` somehow?

### Demonstration

Before:

```diff
class FakerServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
-        $this->app->singleton(Generator::class, function () {
+        $this->app->singleton(Generator::class.':en_GB', function () {
            $faker = Factory::create();
            $faker->addProvider(new LatLng($faker));

            return $faker;
        });
    }
```

**Comment by timacdonald** [comment]
Hey @Patabugen glad to hear you are jumping on the new `fake()` helper!

Here is what you will wanna do in your project...

```php
class FakerServiceProvider extends ServiceProvider
{
    public function register()
    {
        // Attaching a provider for a specific locale, such as "en_AU"...
        $this->app->afterResolving('Faker\Generator:en_AU', function (Generator $instance) {
            $instance->addProvider(new YourProviderHere($instance));
        });

        // Attaching a provider to every locale...
        $this->app->afterResolving(function (mixed $instance) {
            if ($instance instanceof Generator) {
                $instance->addProvider(new YourProviderHere($instance));
            }
        });
    }

```

as a real-world working example...

```php
// For a specific locale...
$this->app->afterResolving('Faker\Generator:en_AU', function (Generator $instance) {
    $instance->addProvider(new class () {
        public function enAuProvider()
        {
            return "en_AU_PROVIDER";
        }
    });
});

// For every locale...
$this->app->afterResolving(function (mixed $instance) {
    if ($instance instanceof Generator) {
        $instance->addProvider(new class () {
            public function globalProvider()
            {
                return 'GLOBAL_PROVIDER';
            }
        });
    }
});

fake()->globalProvider();
// "GLOBAL_PROVIDER"

fake('en_AU')->globalProvider();
// "GLOBAL_PROVIDER"

fake()->enAuProvider();
// InvalidArgumentException with message 'Unknown format "enAuProvider"'

fake('en_AU')->enAuProvider();
// "en_AU_PROVIDER"
```

Hopefully that gets you back on track. Let me know if you have any other issues.

**Comment by Patabugen** [comment]
Hey @timacdonald , thanks for that! Your former example is essentially what I've ended up doing, but your second example of adding one to every locale is handy to have!

**Comment by joelharkes** [comment]
I ended up removing my custom faker providers and use some form of composition instead. PHPStan (laraStan) couldnt find those providers either so it's for the best i think.

**Comment by Lukasss93** [comment]
Once `afterResolving` is used, the `fake()` helper works perfectly with custom Faker providers — **but it breaks inside factories** when calling `$this->faker->customMethod()`.

**Error:**
```
InvalidArgumentException
Unknown format "customMethod"
```

This happens because factories use a completely different logic to resolve Faker instances, making it impossible to add custom providers that are picked up consistently.

https://github.com/laravel/framework/blob/0fa420f961b890af0c1dae46c0cd63a83864384c/src/Illuminate/Database/DatabaseServiceProvider.php#L97-L114

Is there a way to register custom Faker providers that works **both** with the `fake()` helper **and** with `$this->faker` inside Laravel factories?
