### ISSUE TITLE
Vite manifest not found at: .../public/build/manifest.json

### ISSUE THREAD

**Issue by dajoeberlei** [laravel/framework#42991]
- Laravel Version: 9.19.0
- PHP Version: 8.0.19
- Database Driver & Version: mysql 8.0.29

### Description:
I just happen to start a new project today without knowing about vite and wanted to to a laravel jetstream livewire project.
Im assuming its a new bug regarding the just newly released vite features so i opened the issue here instead of within the jetstream issue board. 

### Steps To Reproduce:
- laravel new bug-report
- composer require laravel/jetstream
- php artisan jetstream:install livewire --teams
- npm install && npm run dev
- php artisan test

**Comment by dajoeberlei** [comment]
`npm run build` helped. sry for bothering.

**Comment by timacdonald** [comment]
Glad you got it sorted @dajoeberlei 

You may also run `npm run dev` if you are working locally and want Hot Module Reloading.

**Comment by dajoeberlei** [comment]
@timacdonald thanks! Yes that's what I read in the docs first :) but without doing the build before it didn't work. 
So I had to do 'npm run build' and then 'npm run dev'

**Comment by ju5t** [comment]
@timacdonald sorry to bug you; we are having similar issues as @dajoeberlei but we don't really fancy building assets there. Would there be a reason not to commit `manifest.json` to our repo?

**Comment by timacdonald** [comment]
this is a question for you and your team, really. Personally I find committed assets a pain as they cause so much noise in Git + forgetting to rebuild and commit etc. - but there is nothing fundamentally wrong with it.

May I ask what the issues are though? I followed the steps in the initial post and it worked on my end. Would love to get it fixed if we can for the next people who run into it.

**Comment by ju5t** [comment]
Ah, I shortened my message and removed some crucial stuff. Sorry.

Our situation is a little different. We're seeing this error when we're running our tests in CI. We're not using any boilerplate like Jetstream though. On local machines it all works because the manifest is there, but CI is showing this error. It's especially weird that it only happens on one test. Everything else is fine.

This test is simple. It calls route and asserts if the status is 200. 

The error is coming from our view. In the compiled view there's:

```
<?php echo app('Illuminate\Foundation\Vite')(['resources/css/app.css', 'resources/js/app.js']); ?>
```

Which is fine, but because the manifest is not there, it throws an error.

The fix would be to compile assets in our CI or to publish our manifest file; but neither would be preferable.

What do you think?

**Comment by timacdonald** [comment]
If this is in a test suite and you haven't built (or committed) your assets, you should utilise the `$this->withoutVite()` helper function, which is similar to Mix's `$this->withoutMix()` functionality.


```
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
         parent::setUp();

        $this->withoutVite();
    }
}
```

**Comment by ju5t** [comment]
🤦

Somewhere hidden in my brain I knew about `withoutMix()` but apparently we've always committed the manifest. I will add the helper. Sorry for hijacking this issue about a non-issue!

**Comment by timacdonald** [comment]
No troubles at all. Hopefully it’ll help get you back on track 🤘

**Comment by marwan-ahmed-23** [comment]
I have this " @vite('resources/css/app.css') " When I upload it to the server, this problem appears to me " Vite manifest not found at: /home/u406368550/domains/00000000.com/laravel_blog/public/build/manifest.json "

**Comment by ju5t** [comment]
@HenkPoley perhaps its a Windows issue. It's better to raise a new issue with all the details. I wouldn't expect closed issues to be read by the Laravel team.
