### ISSUE TITLE
QueryBuilder- sort change the number of results

### ISSUE THREAD

**Issue by ali-sorri** [laravel/framework#43019]
- Laravel Version: 9.18.0
- PHP Version: 8.0.0
- Database Driver & Version:

### Description:
When use lazyById  with order column different than id you specified, you will receive different  number of results.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ali-sorri** [comment]
No, Iam reporting a bug
They lazyById function is conflict with ordering query, therefore will receive different number of results when you change the orderBy .
