### ISSUE TITLE
Datetime columns lose timezone info when set

### ISSUE THREAD

**Issue by MikeParkin** [laravel/framework#43036]
- Laravel Version: v9.10.1
- PHP Version: 8.1
- Database Driver & Version: Sail latest

### Description:

Assignment of a carbon object to a model with a datetime cast in memory loses the timezone and the timestamp shifts.

Created an issue previously which was closed (https://github.com/laravel/framework/issues/42993), I commented with an update but had no reply so re-opening with a much more concise example. 

Note this has nothing to do with serialization to the database, the timezone information is lost and therefore the wrong time stored upon assignment to the datetime cast column on the model (i.e without calling save).

### Steps To Reproduce:

```
$date = Carbon::make('2022-06-28T12:52:02+01:00');

// outputs 1656417122
echo $date->timestamp;

$foo = new Foo;
$foo->set_at = $date;

// outputs 1656420722
echo $foo->set_at->timestamp;

```

Why is the default behaviour when assigning a carbon instance from a timezone not in UTC to simply discard the timezone information, rather than converting to the application timezone?

(Model foo definition can be seen in the previous issue linked above if required)

**Comment by driesvints** [comment]
Hi @MikeParkin, this is intended. There is no mechanism in Laravel that saves the timezone for you. You need to convert the timezone to UTC first and then save it. In general, it's always recommended to work with UTC based timestamps and save the timezone in a separate column.

**Comment by Tofandel** [comment]
The problem is not really that the timezone is lost, the problem is that the timezone is not converted to the app timezone before it is saved in the database

Why is it a problem, well because when it retrieves it it assumes it was saved in the app timezone

**Comment by develgold** [comment]
It can be resolved with
```php
$model->setDateFormat('Y-m-d H:i:sP');
```
default date format is Y-m-d H:i:s, but it would be nice if we could customize it with config
