### ISSUE TITLE
personal_access_tokens_tokenable_type_tokenable_id_index

### ISSUE THREAD

**Issue by btn-ninja** [laravel/framework#43032]
- Laravel Version: 9.8.1
- PHP Version: 8.0.13
- Database Driver & Version: WAMP server using 10.6.5-MariaDB - mariadb.org binary distribution
- & installation included Laravel Breeze

### Description:

I am new user (front-end coder) trying to create my first migration using this tutorial: https://www.youtube.com/watch?v=MYyJ4PuL4pY
While following these steps almost exactly (except that I'm on WAMP and Windows), I encountered an issue in which migration fails at personal_access_tokens, ~minute 53 in video.  

Along the way, I discovered that there are 2 migration files for this: one in \database\migrations and one in \vendor\laravel\sanctum\ \database\migrations.  It took me several hours to find this solution on codegrepper, which stopped the error, but I am unsure if it will cause me some other issue later: 

```
//Update your /app/Providers/AppServiceProvider.php to contain:

use Illuminate\Support\Facades\Schema;

public function boot() {
    Schema::defaultStringLength(191);
}
```

### Steps To Reproduce:

- Create a very simple model, ie for 'listings'
- Create a migration:  `php artisan make:migration create_listings_table`
- Run `php artisan migrate`
Receive error about personal_access_tokens_table:  `SQLSTATE[42S01]: Base table or view already exists `
- Run `php artisan migrate:fresh`
Receive new error:  `SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table 'personal_access_tokens' add index 'personal_access_tokens_tokenable_type_tokenable_id_index'('tokenable_type', 'tokenable_id')) `
- After adding the solution above, I am finally able to create a new table.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
