### ISSUE TITLE
Resource data wrapping not working when there is a data attribute

### ISSUE THREAD

**Issue by brinkonaut** [laravel/framework#43037]
Laravel Version: v9.14.1

When you have a data attribute in your eloquent model the data wrapping disappears from the response. When I delete the data attribute in the database, the data wrapped correctly in the response again.

```
public function show(App\Models\Location $location)
{
    return new \App\Http\Resources\Location($location);
}
```

**Comment by feliciotravareli** [comment]
I tracked the issue to file _"Illuminate\Http\Resources\Json\ResourceResponse.php"_ in the method "_haveDefaultWrapperAndDataIsUnwrapped_" on line **84** it checks:
`!array_key_exists($this->wrapper(), $data)`
if we remove this condition it works as it should, but I don't know what else this change would imply....

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
