### ISSUE TITLE
Global Reply-To not applied to mail in testing

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#43034]
- Laravel Version: 9.19.0
- PHP Version: 8.1

### Description:

I have a utility function like this:
```
public function sendMail(Mailable $mail)
{
    // there's more code, but only this is relevant
    $mail->replyTo($replytoAddress, $replytoName);
    Mail::send($mail);
}
```
I also have defined `mail.reply_to.address` config parameter. This produces a Reply-To header with **two email addresses**. This might be intended in some situations, but it isn't for me. 

Problem is that I didn't catch it in testing. If I use mail fake as documented, the Mailable argument of `assertSent()` callback will contain **only one address** in Reply-To (I var_dump'd it), the one defined by my code above, but not the configured global.

I'm not sure it is related to `MAIL_MAILER=array` or the global Reply-To setting does not apply in the "fake mode".

**Comment by mateusjunges** [comment]
The global addresses are added to the mailable here:
https://github.com/laravel/framework/blob/9544b13b03871e560689aa920743426801aa57b0/src/Illuminate/Mail/MailManager.php#L130-L132

But when you use the `Mail::fake()`, this code is not executed, and laravel just adds the mailable to the `mailables` array withing the MailFake class.
