### ISSUE TITLE
Blade Props, Attributes and Slots - unexpected behavior

### ISSUE THREAD

**Issue by misog** [laravel/framework#43068]
- Laravel Version: 9.17.0
- PHP Version: 8.1.3

### Description:

This issue exists in anonymous components. Class components were not tested.

Tests A, B, C without `@props` work as expected and `$variable` is always created. In test C, the `$variable` will contain `asSlot` (slot is prioritized):
```
{{-- testcomponent.blade.php --}}
<div>
    {{ $variable }}
</div>

{{-- Test A --}}
<x-testcomponent :variable="'asAttribute'">

</x-testcomponent>

{{-- Test B --}}
<x-testcomponent>
    <x-slot:variable>asSlot</x-slot:variable>
</x-testcomponent>

{{-- Test C --}}
<x-testcomponent :variable="'asAttribute'">
    <x-slot:variable>asSlot</x-slot:variable>
</x-testcomponent>
```

However when `@props([])` is defined (empty) then things get unexpected in one case.

Test D is expected, `$variable` is undefined (Undefined variable $variable) even if attribute is passed, because the `@props` is empty:
```
{{-- testcomponent.blade.php --}}
@props([])
<div>
    {{ $variable }} {{-- undefined --}}
</div>

{{-- Test D --}}
<x-testcomponent :variable="'asAttribute'">

</x-testcomponent>
```
Test E shows that the `$variable` is created and contains `asSlot` even with empty `@props([])`. OK, maybe `@props` is related only to attributes and has nothing to do with slots:
```
{{-- testcomponent.blade.php --}}
@props([])
<div>
    {{ $variable }} {{-- asSlot --}}
</div>

{{-- Test E --}}
<x-testcomponent>
    <x-slot:variable>asSlot</x-slot>
</x-testcomponent>
```

However Test F is unexpected. The `$variable` is undefined (Undefined variable $variable) even with defined slot. Why it is undefined when there is a slot which has nothing to do with `@props([])`? It should work as in Test E, where slot was passed just like there. In other words, just including conflicting attribute, behavior changed. 
Or this Test F is correct and Test E failed and `@props` should also guard slots?
```
{{-- testcomponent.blade.php --}}
@props([])
<div>
    {{ $variable }} {{-- undefined --}}
</div>

{{-- Test F --}}
<x-testcomponent :variable="'asAttribute'">
    <x-slot:variable>asSlot</x-slot>
</x-testcomponent>
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
