### ISSUE TITLE
Laravel Request Input Replacing Behavior

### ISSUE THREAD

**Issue by WildEgo** [laravel/framework#43069]
- Laravel Version: 9.19.0
- PHP Version: 8.1.7
- Database Driver & Version: Non relevant

### Description:
When creating a request with file and strings in the same array it overwrites the strings for the files.

Expected behavior: [1, 2, File]
Current behavior: [File, 2]

### Steps To Reproduce:
This [repository](https://github.com/WildEgo/larave-post-parse-reproduction) has everything needed to reproduce it.
You serve the project and open the main page, run it without a file in the file input and everything works correctly, when you add said file it'll replace the first item of the array with the file instead of adding to said file.

### Suggested Fix:
This [repository](https://github.com/WildEgo/laravel-request-merge/commit/df01fcf9c5d05f6fe24de5836ce49c6c689f40f7) has the changes that make it work as I expected it.

### Drawbacks:
The arrays __CAN__ have their keys changed, such as fields with keys starting with 1 being set to 0 and from there on.

### Discussion related to the issue #43062

**Comment by nshiro** [comment]
@WildEgo Hi. 😀
I saw your discussions and I see your point.
Personally, I'd just add an index to the uploaded file.

e.g.

```
  "media": [
    1,
    2,
    "upfile": {} <- This is a file
  ],
```

This is a workaround.

But if you think this is a bug and should be fixed, you can send a PR for it (you already have a fix for it) ⚽ and see how Laravel team thinks about it. 
If the fix contains breaking change, then you send a PR for the master branch.

One thing I noticed is that in your solution uploaded file always gets placed last.

e.g.
(1)
```
  "media": [
    {} <- This is a file
    1,
    2,
  ],
```

(2)
```
  "media": [
    1,
    2,
    {} <- This is a file
  ],
```

They both get the same result.

```
  "media" => array:3 [▼
    0 => "1"
    1 => "2"
    2 => {}   <- This is a file (always last)
  ]
```

which I feel somehow different. 🤔

**Comment by driesvints** [comment]
Hi. This seems like a request in behavior. You are free to attempt a PR if you want.
