### ISSUE TITLE
GroupBy issue with belongsToMany 

### ISSUE THREAD

**Issue by n8udd** [laravel/framework#43078]
- Laravel Version: 9.19.0 (latest)
- PHP Version: 8.1.7
- Database Driver & Version: 8.0.29

### Description:
When trying to `groupBy` on a `BelongsToMany`, the builder appends pivot values to the `select` which aren't included in the `groupBy`. This is different to the output when using `->toSql()`.

### Steps To Reproduce:

```
class Order extends Model 
{
...
    public function grandTotal()
    {
        return $this->belongsToMany(Item::class, 'item_order')
            ->selectRaw('sum(item_order.quantity * item_order.unit_price) as total')
            ->groupBy('item_order.order_id');
    }
}
```

```
$o = Order::first();
$o->grandTotal()->toSql();
```
Outputs the following:

```
SELECT
	sum(item_order.quantity * item_order.unit_price) AS total
FROM
	`items`
	INNER JOIN `item_order` ON `items`.`id` = `item_order`.`item_id`
WHERE
	`item_order`.`order_id` = 1
GROUP BY
	`item_order`.`order_id`
```

Whereas:

```
$o = Order::first();
$o->grandTotal()->get();
```
Outputs the following SQL in the error:

```
SELECT list is not in GROUP BY clause and contains nonaggregated column 'example_order_item.item_order.item_id' which is not functionally dependent on columns in GROUP BY clause;
```

```
SELECT
	sum(item_order.quantity * item_order.unit_price) AS total,
	`item_order`.`order_id` AS `pivot_order_id`,
	`item_order`.`item_id` AS `pivot_item_id`
FROM
	`items`
	INNER JOIN `item_order` ON `items`.`id` = `item_order`.`item_id`
WHERE
	`item_order`.`order_id` = 1
GROUP BY
	`item_order`.`order_id`;
```

For some reason the pivot values are being included in the select, which is then breaking the groupBy.

https://github.com/n8udd/example-order_item

**Comment by arafatkn** [comment]
In a Many-to-Many relationship, Laravel will automatically load the pivot columns which are being used for the relationship between two tables.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
