### ISSUE TITLE
idle User logout on session expired. In which file it will check the expiration session time when user is idle?

### ISSUE THREAD

**Issue by kailasb10** [laravel/framework#43073]
- Laravel Version: 8.61.0
- PHP Version: 7.3.32
- Database Driver & Version: MariaDB & 10.5.12

### Description:
I'm trying to do a DB operation when a user is idle for the session expiration time. before the user session is cleared need to update the user status in the database. but it's not working when I refresh the page it redirected to the login page because the user session is already cleared.

### Steps To Reproduce:
- Created a middleware to add "last_activity" time in session
- Every time route is called "last_activity" time is updated
- But when a user is idle up to session expiration time & after that, I refresh the page it redirected to the login page.

can you guide me on this how can I do some DB operation/ extra code before the user session expired?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
