### ISSUE TITLE
`Blade::render()` String same as Component Name

### ISSUE THREAD

**Issue by jjjrmy** [laravel/framework#43081]
- Laravel Version: 9.2
- PHP Version: 8.1

### Description:

If you have a component with the same name as the text you want to `Blade::render` then it will use that component instead.
This doesn't seem like expected behavior as it's not mentioned in the docs.
I'm sure this only happens in rare cases but when using user inputed content, it can happen.

```php
return Blade::render('Loader');
```

I think this is what's causing it.
https://github.com/laravel/framework/blob/1beaaf5092af9eb7ad8e57bf9c3afda41c808d3d/src/Illuminate/View/Component.php#L77-L79

**Comment by jjjrmy** [comment]
Should I submit a PR?

```php
return Blade::render('Loader', ignoreBladeTemplate: true);
```

**\Illuminate\Support\Facades\Blade.php**
```diff
-  * @method static string render(string $string, array $data = [], bool $deleteCachedView = false)
+  * @method static string render(string $string, array $data = [], bool $deleteCachedView = false, bool $ignoreBladeTemplate = false)
```
**\Illuminate\View\Compilers\BladeCompiler.php**
```diff
$view = Container::getInstance()
            ->make(ViewFactory::class)
-           ->make($component->resolveView(), $data);
+           ->make($component->resolveView($ignoreBladeTemplate), $data);
```
**\Illuminate\View\Component.php**
```diff
-return strlen($view) <= PHP_MAXPATHLEN && $factory->exists($view)
+return !$ignoreBladeTemplate && strlen($view) <= PHP_MAXPATHLEN && $factory->exists($view)
            ? $view
            : $this->createBladeViewFromString($factory, $view);
```

**Comment by BrandonSurowiec** [comment]
A workaround is to append a character at the start of your string like `#` and then remove it afterwards.

```php
Str::of(Blade::render('#Loader'))->substr(1);
```

You can try a PR.

**Comment by driesvints** [comment]
Right now we're not planning to make changes to this behavior but you're always free to attempt a PR with a different method. Thanks

**Comment by jjjrmy** [comment]
> Right now we're not planning to make changes to this behavior but you're always free to attempt a PR with a different method. Thanks

so what method name would you suggest?

**Comment by BrandonSurowiec** [comment]
@jjjrmy I would go with that method name for now. If anyone else has a better name, they can suggest it in the PR.
