### ISSUE TITLE
multipart/form-data is not supported

### ISSUE THREAD

**Issue by ExecPHP** [laravel/framework#43115]
- Laravel Version: 9.19.0
- PHP Version: 8.1
- Database Driver & Version: -- 

### Description:
How to enable multipart support?

Request:
`Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0xxx`

Exemple:
  Header: 
     - `accept: application/json, text/javascript, */*; q=0.01`
     - `content-type: multipart/form-data; boundary=----WebKitFormBoundaryEZTjT0mJBxglE228`
 Body:
```
------WebKitFormBoundaryuAWf8BC0NzZmhR19
Content-Disposition: form-data; name="files"; filename="test.xml"
Content-Type: text/xml


------WebKitFormBoundaryuAWf8BC0NzZmhR19
Content-Disposition: form-data; name="id"

223
------WebKitFormBoundaryuAWf8BC0NzZmhR19
```

As a result, the request returns an empty array, it cannot read the `multipart/form-data format; boundary=*`

**Comment by bert-w** [comment]
Never had issues with this. You have to provide a case to reproduce your issue.

**Comment by ExecPHP** [comment]
I found the [answer](https://laracasts.com/discuss/channels/laravel/laravel-8-put-multipartform-data-on-update) the problem was in PUT

https://laravel.com/docs/8.x/blade#method-field

However, there is no solution for rest api requests.
If you only send the parameter with a castlet: `_method: PUT`
