### ISSUE TITLE
Model `increment()` does not update timestamps immediately

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#43113]
- Laravel Version: 9.x
- PHP Version: 8.x
- Database Driver & Version: N/A?

### Description:
Calling `increment()` (or `decrement()` too probably) on an Eloquent model with timestamps enabled doesn't update the `updated_at` column immediately.

### Steps To Reproduce:
```php
// Get a random user object.
$user = User::find(1);
// Dump current `updated_at`.
dump($user->updated_at);
// Increment some numerical column.
$user->increment('credits', 10);
// Dump the new `updated_at`.
dump($user->updated_at);
```
Result: the second `updated_at` dump shows the same value.
Expected result: show the new `updated_at` value.

When calling `$user->refresh()` after the last dump (or checking the database), the `updated_at` column DOES appear to have been updated though.

I went through the code looking for a spot to fix it but I got lost at the syncing logic that writes results back to the model. I'm not sure how different the `increment()` function is to the `update()` one and if this bug is feasible to be fixed.

**Comment by bert-w** [comment]
Line from `protected function incrementOrDecrement(...)`:
https://github.com/laravel/framework/blob/6dd688461ff7a402efc7f939267087ccafebcc96/src/Illuminate/Database/Eloquent/Model.php#L861

Just wanted to add that apparently any properties that you change during the `updating` event are not actually changed in the model. It is simply disregarded. There appears to be an `$extra` parameter for the `increment()` function that accomplishes that using a different route.

**Comment by bert-w** [comment]
https://github.com/laravel/framework/blob/6dd688461ff7a402efc7f939267087ccafebcc96/src/Illuminate/Database/Eloquent/Model.php#L865

Does anything prevent us to use `$this->getDirty()` here for the `$extra` param (or merge them), similar to how it happens in the `update()` function?

**Comment by milwad-dev** [comment]
No bug, I test increment & it's true & update (updated_at)
```
    public function increment($column, $amount = 1, array $extra = [])
    {
        return $this->toBase()->increment(
            $column, $amount, $this->addUpdatedAtColumn($extra)
        );
    }
```

**Comment by driesvints** [comment]
I don't think there's a right way to solve this one. Here's an issue with more details on this: https://github.com/laravel/framework/issues/32567.

There's no way to know if the dirty values at the time of incrementing are going to be the values that need to be saved.
