### ISSUE TITLE
HTTP Facade memory exhaustion 

### ISSUE THREAD

**Issue by Moonrag** [laravel/framework#43167]
- Laravel Version: 9.19.0
- PHP Version: 8.1.8

### Description:
When I trying to send large amount of data (about 1 million rows .csv file) by parts (25'000 rows each) with Http::post() method it ends with "Allowed memory size of 134217728 bytes exhausted (tried to allocate 18874840 bytes)". There are no issues when using cURL or Guzzle (on which Laravel's facades based on)

### Steps To Reproduce:
1. Install Laravel through composer
2. Create simple post route in /routes/api.php
```
Route::post('/test', function (Request $request) {
    return 'ok';
});
```
3. Serve with `php artisan serve`
4. Generate big .csv file
```
$file = fopen('test.csv', 'w+');
$fields = [];
for ($i = 0; $i < 100; $i++) {
    $fields[] = 'test_field_' . $i;
}
for ($i = 0; $i < 200000; $i++) {
    fputcsv($file, $fields);
}
fclose($file);
```
5. Try to send this file by parts with following code:
```
$file = fopen('test.csv', 'rb');

$lines_count = 0;
$part = '';
while (!feof($file)) {
    $part .= fgets($file);
    $lines_count++;
    if ($lines_count == 25000) {
        $mem = number_format(memory_get_usage(true)/(1024 * 1024), 2);
        echo "mem $mem MB\n";
        
        $result = Http::post('http://127.0.0.1:8000/api/test', [
            'data' => $part,
        ]);
        $lines_count = 0;
        $part = '';
    }
}

fclose($file);    
```

Result: 
![image](https://user-images.githubusercontent.com/4313097/178714744-46e59a99-79a2-4992-8d6b-d8ce26a9cf6c.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Moonrag** [comment]
@driesvints It is exactly bug, because the facade doesn't collect garbage after request, how it can be just a question?
