### ISSUE TITLE
Paginator::resolveCurrentPage returns unexpected default value

### ISSUE THREAD

**Issue by brausepulver** [laravel/framework#43178]
- Laravel Version: 9.17.0
- PHP Version: 8.1.2

### Description:
Hi, this is a very minor issue. I was trying check whether a route is paginated using `Illuminate\Pagination\Paginator::resolveCurrentPage(default: false)`. Even though no pagination is ongoing, this returns 1 rather than false. Maybe it would be possible to return null in the default currentPageResolver: https://github.com/laravel/framework/blob/c41c1b37aff95e8f5fb2f5f556e30adb1318a348/src/Illuminate/Pagination/PaginationState.php#L19-L27
The default value passed to resolveCurrentPage could then be returned by checking for null:
https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Pagination/AbstractPaginator.php#L505-L512

### Steps To Reproduce:

1. In a route, invoke `Illuminate\Pagination\Paginator::resolveCurrentPage(default: false)` when there is no pagination.
2. 1 is returned, rather than false.

**Comment by driesvints** [comment]
This value should always be an int higher than 1:

https://github.com/laravel/framework/blob/c99868f1c9bf2f5d250993121838db905591864f/src/Illuminate/Pagination/AbstractPaginator.php#L502

**Comment by brausepulver** [comment]
Maybe the documentation should state the higher than 1 constraint in that case, since I could also pass a default of 0 and expect it to return that.
