### ISSUE TITLE
Laravel v9.19.0 vite causes incompatibility with vendor packages that rely on mix() helper function.

### ISSUE THREAD

**Issue by jan-edge** [laravel/framework#43185]
After upgrading to Laravel v9.19.0 I noticed that the assets of some vendor packages wouldn't load. These vendor packages are Laravel 9.x compatible, but rely on `mix()` to load their assets. According to the [Bundling Assets (Vite)](https://laravel.com/docs/9.x/vite) documentation, they should use `@vite` instead of `mix()` . This breaks backwards compatibility for all packages using `mix()` as of Laravel V9.19.0 .

**Comment by driesvints** [comment]
If you rely on `mix` for some packages then `vite` is unfortunately not an option for you. These packages will need to be updated first. Afaik there's no BC break as the mix helper is still there for you to use.

**Comment by driesvints** [comment]
Also please fill out the issue template next time.
