### ISSUE TITLE
Validating field names or values that contain a pipe no longer work in Laravel 9

### ISSUE THREAD

**Issue by jryd** [laravel/framework#43192]
- Laravel Version: 9.19.0
- PHP Version: 8.1.1
- Database Driver & Version: Postgres 13.6

### Description:
We've been in the process of upgrading a project from Laravel 8 to Laravel 9.

Our project receives a number of requests from an external system that sends data to our platform as JSON where the "keys" often contain special characters - including the pipe character.

We've built a number of validation rules for the data we receive, however, this validation broke in Laravel 9.

This seems linked to the issue raised where the pipe character was used in regex; https://github.com/laravel/framework/issues/40924

Looking at the fix for that bug, we detect if the rule is regex, otherwise we explode on the pipe character.

Whilst the pipe character has been used in string rules as a separator, we've used the array syntax to previously allow us to specify fields that have a pipe character in them (more details in the reproduction steps).

It seems the changes introduced to support the `Rule::forEach()` disallow you from using the pipe character in any field names or field values, even if you are using the array syntax (unless it is a regex rule).
Given this wasn't the behaviour in Laravel 8, and doesn't appear to be an intended effect of adding the `Rule::forEach` feature, I wanted to raise this and ask whether this was a desired side-effect?

The issue appears whenever you have a string based validation rule that contains a field with a pipe character. Based on this, I believe the following rules would be impacted by this (assuming I was validating a field called `|myfield`:

* `accepted_if:|myfield,value`
* `declined_if:|myfield,value`
* `different:|myfield`
* `exclude_if:|myfield,value`
* `exclude_unless:|myfield,value`
* `exclude_without:|myfield,value`
* `gt:|myfield`
* `gte:|myfield`
* `in_array:|myfield`
* `lt:|myfield`
* `lte:|myfield`
* `prohibited_if:|myfield,value`
* `prohibited_unless:|myfield,value`
* `prohibits:|myfield`
* `required_if:|myfield,value`
* `required_unless:|myfield,value`
* `required_with:|myfield`
* `required_with_all:|myfield,|anotherfield`
* `required_without:|myfield`
* `required_without_all:|myfield,|anotherfield`
* `same:|myfield`

This also extends to string based validation rules where a value contains a pipe character:

* `ends_with:|foo,|bar`
* `in:|foo,|bar`
* `not_in:|foo,|bar`
* `starts_with:|foo,|bar`

To be clear, it would be expected that you couldn't use a field or value that contained a pipe within a string validation sequence:

```
public function rules()
{
    return [
        'foo' => 'string|same:|myfield'
    ];
}
```

However, you'd work around this by using an array of rules instead:

```
public function rules()
{
    return [
        'foo' => [
            'string',
            'same:|myfield'
        ],
    ];
}
```

The above works in Laravel 8, but is no longer working in Laravel 9.

### Steps To Reproduce:

```
// We'd expect this to fail as status is a string and doesn't match the rules for status
>>> Validator::make(['repeater' => [['status' => 'string']]], ['repeater' => ['array'], 'repeater.*.status' => ['array', 'required_array_keys:|code,|terminology']])->passes()
BadMethodCallException with message 'Method Illuminate\Validation\Validator::validateCode, does not exist.'
```

```
// We'd expect this to pass as status contains the array keys we require
>>> Validator::make(['repeater' => [['status' => ['|code' => 123, '|terminology' => 'openehr']]]], ['repeater' => ['array'], 'repeater.*.status' => ['array', 'required_array_keys:|code,|terminology']])->passes()
BadMethodCallException with message 'Method Illuminate\Validation\Validator::validateCode, does not exist.'
```

```
// We'd expect this to pass as `|code` is being provided
>>> Validator::make(['|code' => '1234', '|terminology' => 'openehr'], ['|code' => 'required_if:|terminology,openehr'])->passes()
InvalidArgumentException with message 'Validation rule required_if requires at least 2 parameters.'
```

```
// We'd expect this to fail as `|code` is being provided
>>> Validator::make(['|code' => '1234', '|terminology' => 'openehr'], ['|code' => 'required_unless:|terminology,openehr'])->passes()
InvalidArgumentException with message 'Validation rule required_unless requires at least 2 parameters.'
```

```
// We'd expect this to pass as `|code` is truthy
>>> Validator::make(['|code' => true, '|terminology' => 'openehr'], ['|code' => 'accepted_if:|terminology,openehr'])->passes()
InvalidArgumentException with message 'Validation rule accepted_if requires at least 2 parameters.'
```

```
// We'd expect this to fail as the string does not end with `|foo` or `|bar`
>>> Validator::make(['myfield' => 'test'], ['myfield' => ['ends_with:|foo,|bar']])->passes()
BadMethodCallException with message 'Method Illuminate\Validation\Validator::validate|foo,|bar does not exist.'
```

**Comment by driesvints** [comment]
Hi @jryd. I don't think we ever intended fields with pipe characters to be supported. Therefor we don't consider this a breaking change. Sorry that this is causing issues for you.

**Comment by Kussie** [comment]
Honestly I think that's a bit short sighted, as the original poster stated this has been working right through all versions until Laravel 9, as he also mentioned there was similar issues occurring for Regex fields however it was fixed there, pipes in field names are an acceptable character according to the spec.  Seems a bit overbearing to be trying to dictate how potentially third party and external vendors send data

**Comment by driesvints** [comment]
If someone would come up with a PR to make this work we can definitely consider it 👍
