### ISSUE TITLE
Wrong doctype \Illuminate\Contracts\Container\ContextualBindingBuilder::give()

### ISSUE THREAD

**Issue by BreiteSeite** [laravel/framework#43204]
- Laravel: latest 8 & 9

### Description:

Documentation states that injecting any primitive value (such an int) is okay:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/2171105/179231500-aeb8f414-0bea-4851-a9a7-800521232d68.png">

However, the docbloc only accounts for string
https://github.com/laravel/framework/blob/ca3c274725a62fb464327f92324de9cf647abe5a/src/Illuminate/Contracts/Container/ContextualBindingBuilder.php#L18

### Steps To Reproduce:

```php
        $this->app
            ->when(SomeClass::class)
            ->needs('$someVariable')
            ->give((1);
```

run larastan

> Parameter #1 $implementation of method Illuminate\Contracts\Container\ContextualBindingBuilder::give() expects array|Closure|string, int given.

**Comment by driesvints** [comment]
Please don't open issues for docblocks. Nothing is broken here. If you want to change a docblock type feel free to send in a PR.
