### ISSUE TITLE
Using URL::defaults() breaks tests

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/framework#43201]
- Laravel Version: 9.20.0
- PHP Version: 8.0.21
- Database Driver & Version: MySQL 8.0

### Description:
Since v9.19.0 this functionality is broken. If you setup a URL::defaults in your TestCase class (or any test class for that matter), all controllers using parameters injection will miss those default parameters.

### Steps To Reproduce:

**routes/web.php**
```php
use App\Models\User;

Route::get('/{locale}/user/{user}', function (string $locale, User $user) {
    return compact('locale', 'user');
})->name('user');
```

**tests/Features/ExampleTest.php**
```php
use App\Models\User;
use Illuminate\Support\Facades\URL;

/** @test */
public function test_passes_without_url_defaults()
{
    $this->get(route('user', [
        'locale' => 'en',
        'user' => User::factory()->create(),
    ]))->assertStatus(200);
}

/** @test */
public function test_fails_with_url_defaults()
{
    URL::defaults([ 'locale' => 'en' ]);

    $this->get(route('user', [
        'user' => User::factory()->create(),
    ]))->assertStatus(200);
}
```

**Comment by driesvints** [comment]
We reverted the causing PR. Thanks
