### ISSUE TITLE
ClassMorphViolationException exception with `model:show` artisan command

### ISSUE THREAD

**Issue by SamuelMwangiW** [laravel/framework#43216]
- Laravel Version: 9.x-dev
- PHP Version: 8.1.7
- Database Driver & Version: Mariadb 10.7

### Description:
Thanks a lot for the amazing work @jessarcher on #43156 .

Am getting an `Illuminate\Database\ClassMorphViolationException` because I have Relation::enforceMorphMap for some classes. Kindly confirm if this is the desired behavior 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1807304/179328644-e032d353-6b3d-4fd3-b3b7-f583ebddf837.png">

```php
Relation::enforceMorphMap([
    'post' => Post::class,
    'video' => Video::class,
]);
```
It otherwise works perfectly fine when the enforceMorphMap is commented out:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1807304/179328821-021536ff-4d33-44c5-ac0d-fc77f60a6c9d.png">

### Steps To Reproduce:

- Add `Relation::enforceMorphMap(['model'=>'App\Models\Model'])` in the `boot` method of `AppServiceProvider` and omitting to add `\App\Models\User`
- Run `artisan model:show User`

**Comment by jessarcher** [comment]
Hi @SamuelMwangiW, I think this is expected. The `tokens` and `notifications` relationships on your `User` model are both `MorphMany` relationships, so you'd need to specify a morph map for them to work in this scenario. You would get the same exception if you tried to access those relations anywhere else in your application.

If you're not using these relationships, you may consider removing the `HasApiTokens` and `Notifiable` traits from the model.

I've confirmed that the exception is *not* thrown if an "unmapped" model doesn't have any polymorphic relations, so I wouldn't consider this a bug.

**Comment by SamuelMwangiW** [comment]
Thanks @jessarcher
