### ISSUE TITLE
cli and web execution using different database host

### ISSUE THREAD

**Issue by parmonov98** [laravel/framework#43218]
- Laravel Version: "^8.75"
- PHP Version: 8
- Database Driver & Version: Mysql 5.7

### Steps To Reproduce:
create laravel project and put it in docker container (laradock)
create a artisan command and make a query to DB using any model. 

![image](https://user-images.githubusercontent.com/24564577/179337345-480e008f-a61a-49cd-90ac-c9179682d3d3.png)

in my case: I set DB_HOST=mysql since laradock configured like this. 
It works well with web requests but when it comes to cli mode it doesn't work. 
if I set DB_HOST to 127.0.0.1 then it works in cli mode.

**Comment by jessarcher** [comment]
Hi @parmonov98, This doesn't seem like a Laravel issue.

The Docker host `mysql` will not resolve on your host machine, so you would need to run your artisan command inside a container on the same Docker network as the MySQL container, like this: https://laradock.io/documentation/#run-artisan-commands
