### ISSUE TITLE
Add Flags to Route Listing, to enable listing a particular Routes file like php artisan route:list --api-only

### ISSUE THREAD

**Issue by zaghadon** [laravel/framework#43214]
### Discussed in https://github.com/laravel/framework/discussions/43213

<div type='discussions-op-text'>

<sup>Originally posted by **zaghadon** July 15, 2022</sup>
Can We Add Flags to Route Listing, to enable listing a particular Routes file like `php artisan route:list --api-only` to list only the API Routes, or `php artisan route:list --web-only` and so forth.

First String in the flag should be the same as the routes filename.</div>

**Comment by zaghadon** [comment]
Eduance says there's already a way to do this, on the discussion. He said, 
"There is already a way to do this; you can use the php artisan route:list --path=api/". 

I didn't find this on the documentation, can we include this in the Docs.

**Comment by milwad-dev** [comment]
I work on this

**Comment by zaghadon** [comment]
> I work on this

Great 👍✅. I already included it in the Documentation, I hope the PR would be merged in coming reviews.

**Comment by driesvints** [comment]
Please do not move discussions to issues.
