### ISSUE TITLE
NULL currently authenticated user in `handle` method of the queue

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [laravel/framework#43248]
- Laravel Version: 9.19
- PHP Version: ^8.0.2
- Database Driver & Version: phpMyAdmin 5.1.1

### Description:

I noticed that when I try accessing the currently authenticated user in the `__construct` magic method everything goes well but, when trying to access it in the `handle` method, it returns NULL.

![issue](https://user-images.githubusercontent.com/48416569/179441514-3f82db03-446b-4957-ab5c-2c511896df24.png)

**Comment by milwad-dev** [comment]
Are you sure user logged in?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mahmoudmohamedramadan** [comment]
@milwad-dev Yup, the currently authenticated user data returned on the `__construct ` method

**Comment by mahmoudmohamedramadan** [comment]
@driesvints Sir, it's not a question, it's an issue because I've logged in and the authenticated user's data is back from the `__construct` method, but it returns NULL when trying to access it from the `handle` method.

**Comment by milwad-dev** [comment]
You can make property in ``__construct`` and send auth user to property & use in handle :)!

**Comment by mahmoudmohamedramadan** [comment]
@milwad-dev I know, I already do it but, it's still an issue.
