### ISSUE TITLE
Laravel queries database each time Auth::check() is called

### ISSUE THREAD

**Issue by gordenis** [laravel/framework#43266]
- Laravel Version: 9.19.0
- PHP Version: 8.1.8
- Database Driver & Version: MySQL

### Description:
When authenticating a user (say, with an access token) and the user is not authenticated (not found in the database), the user is `null` and it seems Laravel does not cache the `null` user (the fact that user is not found). As a result, each time I call `Auth::check()`, `Auth::user()`, `$request->user`, etc. within the request lifecycle, it attempts to authenticate again and again, making additional identical DB queries.

If, however, a user is successfully authenticated, then the user is cached and all next calls for `Auth::check()` within request lifecycle do not produce additional queries to the db. 

Imagine, we must allow both authenticated and non-authenticated users to access the specific route and, based on the authentication status, allow or disallow some features. So there might be multiple auth checks in models, controllers, custom components, etc., within the same request lifecycle. If there is no user found/authenticated (say, with the provided token), it would produce a lot of identical queries to the database with each `Auth::...` call.

### Steps To Reproduce:
1. Correct access token provided and user authenticated (works as expected): 
1st call `Auth::check()` - query to the database
2nd call `Auth::check()` - no query
3rd call `Auth::user()` - no query
4th call `$request->user()` - no query
....
2. Incorrect token provided, user not authenticated (**here is the issue**):
1st call `Auth::check()` - query to the database
2nd call `Auth::check()` - query to the database
3rd call `Auth::user()` - query to the database
4th call `$request->user()` - query to the database
...

So the case 2 is where the issue occures. 

Thank you.

**Comment by seriquynh** [comment]
Do you mean calling Auth::check() multiple times during the single request?

I took a look at where the logic is implemented:

- Auth::check() calls Auth:user() to check whether the resolved user is null.
- If the resolved user is null and token from the request is set, Auth::user() always tries to resolve again whenever it is called. https://github.com/laravel/framework/blob/b9203fca96960ef9cd8860cb4ec99d1279353a8d/src/Illuminate/Auth/TokenGuard.php#L84

I am not sure what is your exact problem. For example, if the request is unauthenticated, why do you allow it to go through your controller which has ton of other Auth::check() or Auth::user() calls?

**Comment by milwad-dev** [comment]
If cache user sometimes be problem

**Comment by driesvints** [comment]
This is the expected behavior.

**Comment by gordenis** [comment]
> I am not sure what is your exact problem. For example, if the request is unauthenticated, why do you allow it to go through your controller which has ton of other Auth::check() or Auth::user() calls?

In my case it must allow both authenticated and non-authenticated users to access the specific page/route and then, based on the authentication status, allow/disallow some specific features.

**Comment by gordenis** [comment]
> > I am not sure what is your exact problem. For example, if the request is unauthenticated, why do you allow it to go through your controller which has ton of other Auth::check() or Auth::user() calls?

In my case it must allow both authenticated and non-authenticated users to access the specific page/route and then, based on the authentication status, allow/disallow some specific features within controllers, models, etc. Is there any alternative way I can do that without creating a custom guard/provider?
