### ISSUE TITLE
EloquentUserProvider RetrieveById & RetrieveByToken - Ambiguous ID

### ISSUE THREAD

**Issue by BenWalters** [laravel/framework#43274]
- Laravel Version: 9.11.0
- PHP Version: 8.1.8
- Database Driver & Version: MySQL - 8.0.26

### Description:
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous
Caused by Illuminate\Auth\EloquentUserProvider:52 (retrieveById)

When applying a global scope to our Users model that also has an ID field, the above mentioned function is not qualifying the field name (adding the table prefix), thus causing the "'id' in where clause is ambiguous" error.

Seemingly the same issue was raised here - https://github.com/laravel/ideas/issues/1956
I believe that wrapping `$model->getAuthIdentifierName()` in `$model->qualifyColumn()` would resolve the issue and should be implemented in both the `retrieveById` and `retrieveByToken` functions of EloquentUserProvider.

**Comment by driesvints** [comment]
Let's see how your PR goes 👍
