### ISSUE TITLE
Error: Cannot unpack Traversable with string keys when using model:show

### ISSUE THREAD

**Issue by aneesdev** [laravel/framework#43285]
- Laravel Version: 9.21.0
- PHP Version: 8.0.11
- Database Driver & Version: mysql (mariadb 10.3.31) 

### Description:

When running `model:show` command I get this error:

![image](https://user-images.githubusercontent.com/92947803/179793846-f2ea7553-1096-4f1b-bca0-a6d0d3dd4d2c.png)

Maybe [these unpacking arrays also work with string-key arrays only in **PHP 8.1**?](https://stackoverflow.com/a/68376623) If true then it should not be used because Laravel 9 minimum **PHP is >= 8.0** 😄 

### Steps To Reproduce:

None

**Comment by aneesdev** [comment]
@nunomaduro @jessarcher

**Comment by jessarcher** [comment]
Sorry about that @aneesdev! I've addressed this in #43301.
