### ISSUE TITLE
Error with model:show artisan command with model named "Event"

### ISSUE THREAD

**Issue by stef686** [laravel/framework#43289]
- Laravel Version: 9.21.0
- PHP Version: 8.1.1
- Database Driver & Version: MySql

### Description:
I have a model called **Event**. Running the new `php artisan model:show Event` command outputs an error:

![image](https://user-images.githubusercontent.com/917453/179802224-f9e7b0a7-f6ee-4c12-95b2-8d235298455e.png)

Running `php artisan model:show /Event` works correctly.

### Steps To Reproduce:
`php artisan model:show Event`

**Comment by jessarcher** [comment]
Sorry about that @stef686! There was an issue with any models that share the same name as an aliased facade. #43301 address this.
