### ISSUE TITLE
Error with model:show and enum column

### ISSUE THREAD

**Issue by ejunker** [laravel/framework#43298]
- Laravel Version: 9.21.0
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 5.7.34

### Description:

I have `doctrine/dbal` installed and I get this error:

```php
❯ php artisan model:show Member

In AbstractPlatform.php line 396:

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```

I then read that I might need to map enum to a string so in my AppServiceProvider I added this:
```php
DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
```

That did not fix it but now getting a different error:
```php
❯ php artisan model:show Member

In ForwardsCalls.php line 71:

  Call to undefined method Illuminate\Database\Eloquent\Builder::getRelated()
```

**Comment by jessarcher** [comment]
Hi @ejunker,

I'm not sure if the second error is related to the first. When using an enum column I am able to show the model successfully after registering the enum mapping.

Could you please provide more information about your `Member` model? If you're unable to provide the full class, it would be great to at least know:

* What class it extends.
* What types of relations it has (e.g. `hasMany`).
* Whether any public methods contain calls to a relation method (e.g. `$this->hasMany()`) without just directly returning that method.

I've come up with a solution that should prevent the error you're seeing, however without knowing more about the relation, it might just hide the relation completely.

**Comment by jessarcher** [comment]
@ejunker The error should be prevented with #43301, but I'd still like to know more about your model in case there's anything else we should be doing.

**Comment by ejunker** [comment]
@jessarcher this is a strange one. It turns out that a commented out line of code was the problem

```php
    public function companyJobs()
    {
        //return $this->hasMany('App\Models\Job', 'parentID', 'memberIdOfParent');
        return Job::where('parentID', $this->memberIdOfParent);
    }
```

Since the commented out line contains `hasMany` it incorrectly thought it was a relationship.

**Comment by jessarcher** [comment]
@ejunker Thanks! Makes sense. My PR will address that scenario because it ensures that a `Relation` instance is returned from the method.
