### ISSUE TITLE
On logout session destroyed but new session created and user is still logged in

### ISSUE THREAD

**Issue by MirzaazriM** [laravel/framework#43292]
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:
On logout session destroyed but new session created and user is still logged in
Logout -> session destroyed -> user redirected -> code goes through middlewares -> in VCT middleware user session exists

### Steps To Reproduce:
On logout following code is executed:
$this->guard()->logout();
$request->session()->invalidate();
return $this->loggedOut($request) ?: redirect('/login')->withHeaders(['Clear-Site-Data' => '"cache", "storage"']);

If I log session()->all() and auth()->user() before redirect, both of them are null - also session file in frameworks/sessions is deleted.

After login page is rendered in browser and I refresh it, im redirected to application main page which can only be accessible if user is authenticated - and for some reason user has session even though the session should be destroyed on logout.

Middlewares executed on redirect:
 \App\Http\Middleware\EncryptCookies::class,
  \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
  \Illuminate\Session\Middleware\StartSession::class,
  \Illuminate\Session\Middleware\AuthenticateSession::class,
  \Illuminate\View\Middleware\ShareErrorsFromSession::class,
  \App\Http\Middleware\VerifyCsrfToken::class, 

I was tracking user session and in VerifyCsrfToken user has session even though session should be cleared.

This does not happen on each logout which makes things even more strange.

**Comment by rodrigopedra** [comment]
For routes inside the `web` middleware stack a visitor will always have a session sent back, either if they are logged in as a user or not.

A session is not bound to the authentication flow. When using session based authentication the logged in user id will be stored in the session data. On logout this session is destroyed and on the same response a fresh new session cookie is sent. This is one should not have the user id.

It is not clear from you description what your issue is, might be a misunderstanding as English is not my native language.

Are you adding the `auth:web` middleware to the route you want to be protected? This is required to keep the route safe.

**Comment by MirzaazriM** [comment]
Yes, auth middleware is set on the route, and that is my problem - if i logged out how can it be that after redirect I have authenticated user, if I didnt logged in again.
As wrote already, just before redirect on logout route my auth()->user() is null, but already in VerifyCsrfToken (during the redirect) I have authenticated user.

I noticed that on my homepage there are some Ajax requests which are not finished before I log out - can it be that those Ajax requests keep the user logged in somehow?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
