### ISSUE TITLE
issue with build with new default vite - how to build the bootstrap and admin-lte packages? 

### ISSUE THREAD

**Issue by bhojkamal** [laravel/framework#43304]
- Laravel Version: 9.20
- PHP Version: 8.0.15

### Description:
It was easy before with laravel-mix and it is removed in new laravel and we don't have good documentation for us who develop small application using bootstrap and admin-lte packages. 

Before it was working perfectly with the following code for laravel-mix in `bootstrap.js`
```
import _ from 'lodash';
window._ = _;

try {
    window.Popper = require('popper.js').default;
    // window.$ = window.jQuery = require('jquery'); // not needed
    require('bootstrap');
    require('admin-lte');
} catch (e) { }

import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```
and on app.js just this -> `import './bootstrap';`

Now it is now working, It is pulling the bootstrap js and admin-lte js. 

So, how to import bootstrap js and admin-lte js from the packages? 

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
