### ISSUE TITLE
Unable to get database notifications created_at field converted to Carbon diffForHumans

### ISSUE THREAD

**Issue by acgtwentyone** [laravel/framework#43315]
### Discussed in https://github.com/laravel/framework/discussions/43282

<div type='discussions-op-text'>

<sup>Originally posted by **acgtwentyone** July 19, 2022</sup>
Hi,

We have an application running in production and displaying notifications as well. We have implemented this functionality using Laravel [Notifications](https://laravel.com/docs/9.x/notifications). As part of this implementation we are storing the notifications registry in database table named notifications, and it's working.

Currently we are unable to display the notifications sent date using some [Carbon](https://carbon.nesbot.com/docs/) feature such as $notf->created_at->diffForHumans().

Note that we created a vuejs component that is responsible for showing the unreaded notifications. But we are stuck in this part as we can't format the created_at field to something like:
'4 days ago' instead of 2022-07-15 11:39:23.

### Show notifications list
![Screenshot 2022-07-19 at 11 59 39](https://user-images.githubusercontent.com/94224806/179756236-ecab4874-1083-4cd2-8dbc-8ff15d927c92.png)

### Notification class
```php
<?php

namespace App\Notifications\Factura;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Auth;

class FacturaCertificated extends Notification implements ShouldQueue
{
    use Queueable;
    private $factura;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($factura)
    {
        $this->factura = $factura;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return $notifiable->perfers_email('NVE_A1EJS5HGV9') ? ['database','mail'] : ['database'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
                    ->line('Notificação')
                    ->action('Ver',route("pagamento.show",$this->factura->id))
                    ->line("Factura ".$this->factura->cod_ref." certificado no contrato ".$this->factura->contratos->cod_ref."");
    }

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toDatabase($notifiable)
    {
        return [
            "icon"=> "attach_money",
            "bg"  => "bg-success",
            "link" => route("pagamento.show",$this->factura->id),
            "text" => "Factura <b>".$this->factura->cod_ref."</b> certificado no contrato <b>".$this->factura->contratos->cod_ref."</b>"
        ];
    }
}
```

### Database registry
![Screenshot 2022-07-19 at 12 06 45](https://user-images.githubusercontent.com/94224806/179757482-e3866f12-b413-47a3-9b1a-22c979053ffc.png)

### Current implementation
```php
function getUnreadNotifications(){
    try{
        return json_encode(auth->user()->unreadNotifications()->paginate(8));
    }catch (\Throwable $th){
       Helpers::throw($th, 'ApiNotifications');
    }
}
```

### Also tried this way but the notifications does not appear
```php
 try{
    return json_encode(auth->user()->unreadNotifications()->paginate(8)->map(function($n){
        $n->sent_date = $n->created_at->diffForHumans;
        return $n;
    }));
}catch (\Throwable $th){
   Helpers::throw($th, 'ApiNotifications');
}
```

Any help is welcome.</div>

**Comment by aneesdev** [comment]
> @aneesdev Actually, even if i use $n->created_at->diffForHumans(); it does not work. In fact the () was not copied while posting this issue.

Then I think you need to parse it using carbon yourself like this:

```php
Carbon\Carbon::parse($n->created_at)->diffForHumans()
```

**Comment by driesvints** [comment]
Please don't move discussions to issues.
