### ISSUE TITLE
Problem with illuminate/console - Call to undefined function resolve()

### ISSUE THREAD

**Issue by dominikhalvonik** [laravel/framework#43313]
- Lumen Version: v9.0.3
- PHP Version: 8.1.4-FPM
- Database Driver & Version: MySQL 8.0

### Description:
Hi guys, today we tried to do a release on QA env of our application which is wrriten in Lumen. The application is build as Docker Image and served as K8s Pod with 2 containers - NginX 1.20 / PHP-FPM 8.1.4. After the Pod is created we run php artisan migrate. We noticed that our application throws the following error:

`
In Component.php line 89:
Call to undefined function Illuminate\Console\View\Components\resolve()
`

We checked the problem and based on our investigation the problem is that in file: vendor\illuminate\console\View\Components\Component.php on line 86 and 89 is used method resolve() which is not part of any helper so it is not recongnized in abstract class Component. We also noticed that protected function compile($view, $data) has defined in the comment that it is void (@return void) but there is a return statement in the end of the method which we think is incorrect. 

We checked the version of illuminate/console and the problematic version is v9.21.0 . When we switched to older version of our application, everthing is working correctly. We checked the laravel/lumen-framework and illuminate/console and it was:

laravel/lumen-framework: v9.0.2
illuminate/console: v9.17.0

We also tried other command like php artisan cache:clear but with the same result. 

### Steps To Reproduce:

1. Create new Lumen app - composer create-project --prefer-dist laravel/lumen blog
2. Type php artisan migrate via command line

**Comment by janyskk** [comment]
Same issue happend to us. please fix asap

**Comment by mgemmel** [comment]
I just updated project and same issue... pls fix

**Comment by marcinovp** [comment]
I have the same issue

**Comment by martinrozboril** [comment]
same issue, fix please

**Comment by 10peter10** [comment]
We've got same issue,
please fix it asap.

**Comment by DevilQo** [comment]
I have the same issue

**Comment by duansk75** [comment]
Same problem here, please fix.

**Comment by nunomaduro** [comment]
This is fixed: https://github.com/laravel/framework/releases/tag/v9.21.1.
