### ISSUE TITLE
Pagination buttons are huge after upgrading Laravel

### ISSUE THREAD

**Issue by programmin1** [laravel/framework#43328]
- Laravel Version: v9.21.3
- PHP Version: 8.1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu

### Description:

After upgrade of Laravel and PHP, I found that the prev/next selectors are a really enormous svg icon:
```
<svg fill="currentColor" viewBox="0 0 20 20" class="w-5 h-5"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
```
20 what? 20 lines? That appears to be what it is setting.
If I change it to viewBox="0 0 20px 20px" it is at least as small as the other numbered ones, but it is still off. You can see an example at https://hearham.com/repeaters/all at the far bottom of the page.

### Steps To Reproduce:

Upgrade an older Laravel project that has pagination with paginate():
```
return view('somelisting')->with([...
             'items' => $items->paginate(1000)
]);
```
and in the view:

	{{ $items->links() }}

The paginate links are somewhat off, although they do work correctly.

**Comment by driesvints** [comment]
@programmin1 are you on the latest bootstrap 5 version? 

The default classes got changed here: https://github.com/laravel/framework/pull/43319

**Comment by milwad-dev** [comment]
Add bootstrap to service provider

**Comment by driesvints** [comment]
I think you're probably not on the latest bootstrap version. Please upgrade and try again.

**Comment by programmin1** [comment]
Upgrade how? There is no mention of Bootstrap in https://laravel.com/docs/9.x/upgrade
