### ISSUE TITLE
expectsOutput on PendingCommand does not work with new artisan look

### ISSUE THREAD

**Issue by RikSomers** [laravel/framework#43339]
- Laravel Version: 9.21.3
- PHP Version: 8.1.4
- Database Driver & Version: n/a

### Description:
When you try to assert an output for a command, it does not work correctly for the commands that use the new artisan look.

Following the docs (https://laravel.com/docs/9.x/console-tests) this is the only way to assert output of these commands, which is now broken.

### Steps To Reproduce:
```php
    public function it_clears_the_route_cache()
    {
        // some other code

        $this->artisan('route:clear')
            ->expectsOutput('Route cache cleared successfully.')
            ->assertExitCode(0);

        // some other code
    }
```

Above code was working before, now it fails on the output expectation.

**Comment by nunomaduro** [comment]
That's expected. The `expectsOutput` works with our public API to display output:

```
$this->info,
$this->warn,
etc...
```

**Comment by RikSomers** [comment]
Ok.. But how should I test this code then @nunomaduro ?

**Comment by nunomaduro** [comment]
@RikSomers You want to test framework commands from your application?

**Comment by RikSomers** [comment]
We have a command that has extended a framework command and want to make sure the framework portion of the command is still being called correctly.

But even if we didn't, there is no (easy/documented) way to test the new output now, if we wanted to use the new structure ourselves?

**Comment by nunomaduro** [comment]
The new output is not public, meaning that you are suppost to use `$this->components->info` yourself. Yet, to under your question, you can use:

```
        $this->artisan('route:clear')
            ->expectsOutputToContain('Route cache cleared successfully.')
            ->assertExitCode(0);
```

**Comment by RikSomers** [comment]
Ah great, that works! Thanks 👍

**Comment by surgiie** [comment]
Looking for way to do the same on a [laravel-zero](https://github.com/laravel-zero/laravel-zero) application. Any `expectsOutput*` assertion doesnt assert any output from `$this->components` for some reason. Not sure if im just missing something or if not supported.
