### ISSUE TITLE
View::composer('layouts.master') view file is not found after upgrade to Laravel 9

### ISSUE THREAD

**Issue by daanadriaan** [laravel/framework#43349]
- Laravel Version: 4.12.6
- PHP Version: 8.0.20

### Description:
Since upgrading to Laravel 9, View::composer('layouts.master') is not found as a view file. The file is in /views/layouts/master.twig and is extended by all page view files.

View::composer('*') does the trick, so the issue is in the 'layouts.master'. I don't want all view files to go though the view composer so '*' is not a solution for me.

Please help!

`<?php
    namespace App\Providers;

    use App\Http\ViewComposers\WebsiteComposer;
    use Illuminate\Support\Facades\View;
    use Illuminate\Support\ServiceProvider;

    class ComposerServiceProvider extends ServiceProvider {

        public function boot(): void {
            View::composer('layouts.master', WebsiteComposer::class);
        }
    }
`

**Comment by driesvints** [comment]
Afaik, we don't support twig files.

**Comment by daanadriaan** [comment]
@driesvints Well, up until Laravel 8 Twig was always supported. It stopped working after the upgrade. So unless this was a choice, I would mark actually this issue as unresolved. I will try to find a workaround for now, but I figure lots of people will run into this problem.

**Comment by driesvints** [comment]
@daanadriaan I really think we never ever supported Twig. I have no idea why it would work for you.

**Comment by daanadriaan** [comment]
@driesvints I'm sorry, you're right! I forgot about [Twig bridge](https://github.com/rcrowe/TwigBridge). That's gotta be it!
