### ISSUE TITLE
actingAs makes user available without specifying guard in controller

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/framework#43346]
- Laravel Version: 8.78.1
- PHP Version: 8.1.8
- Database Driver & Version: MySQL

### Description:

When using `actingAs($user, 'some-guard')` in endpoint tests, there is no need to specify a guard in the relevant controller method when calling e.g. `$request->user()`. E.g., when using api authentication for routes outside of `auth:api` middleware, `$request->user()` will return a user when `actingAs` is used in tests, but when running the actual application, it returns `null`. This leads to false negatives in tests that are hard to debug.

### Steps To Reproduce:

I want an endpoint with optional authentication, so add the route without `auth:api` middleware in `routes/api.php`.

```php
Route::post('some-endpoint', ...)
```

In a test, call:

```php
$this->actingAs($user, 'api')->json('POST', 'some-endpoint')
```

In matching controller method:

```php
$request->user(); // returns User instance, but should return null because the api guard isn't specified.
```

When running the same in production, `$request->user()` returns `null`. Instead, I need to use `$request->user('api')`

**Comment by driesvints** [comment]
Heya. This looks more like a request to change the behavior for this method. I doubt we're going to do that as that would be a breaking change to users. Feel free to send in a PR with a different solution if you can come up with one. Thanks

**Comment by WouterFlorijn** [comment]
@driesvints I feel like this is more of a bug really, since the method does not do what it implies. I.e. it makes the user available through all guards instead of the just the one specified. So essentially the second argument does nothing in the context of routes with optional authentication. This is inconsistent with its documentation and its behavior on routes with auth middleware.

Anyone relying on this bug for their tests will likely experience issues in production because their tests produce false negatives, which is exactly what happened for us. Therefore, I'd call this a fixing change rather than a breaking change.

Unfortunately I don't have the knowledge to fix it. Looking at `InteractsWithAuthentication::actingAs`, it seems to do what it's supposed to, so it must be something about the testing environment that's messing things up.

**Comment by driesvints** [comment]
@WouterFlorijn you're right. This isn't clear in the docs atm. I've sent in a PR to help clarify the behavior: https://github.com/laravel/docs/pull/8065

**Comment by X-Coder264** [comment]
This is definitively a bug, a big one. It bit me more than once. What's the point of a test if it passes while the real app behavior is broken? The `actingAs` method behavior should be IMO changed for the next major framework release. It makes no sense for that method to set the default guard (aka call the `shouldUse` method on the `AuthManager`) as that is not something that happens during a real HTTP request unless the route has explicit `auth` middleware attached (e.g. `auth:api` ).

**Comment by driesvints** [comment]
We're not going to change the behavior on a patch release and break apps that rely on the current behavior. You're free to attempt a PR to the next major version.
