### ISSUE TITLE
Laravel 9.21 break guards on laravel octane

### ISSUE THREAD

**Issue by farmani** [laravel/framework#43353]
- Laravel Version: 9.21.0
- PHP Version: 8.1.8
- Database Driver & Version: Mongodb

### Description:

I'm using octane and openswoole after upgrading to laravel 9.21 all guards stop working and cannot authenticate logged in users and return 401 (unauthenticated)
revert to laravel 9.20 resolve the issue.

**Comment by driesvints** [comment]
Hey @farmani. Can you try out 9.21 and revert the changes below to see if that works?

<img width="1384" alt="Screenshot 2022-07-22 at 09 32 06" src="https://user-images.githubusercontent.com/594614/180387686-75648483-6b7e-4476-b117-0020fc182cb4.png">

**Comment by driesvints** [comment]
Thanks, I've sent in a PR to revert this. We'll cut a new release hopefully soon.
