### ISSUE TITLE
updateOrCreate ignoring mutator

### ISSUE THREAD

**Issue by Minhyme** [laravel/framework#43350]
- Laravel Version: 9.20.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.28

### Description:
When using updateOrCreate on a model which uses a mutator, the mutator is not utilized in determining if the attributes match a given record in the DB. This results in duplicates being created in the database.

### Steps To Reproduce:

Add mutator to model such as:
```
    protected function sentiment(): Attribute
    {
        return Attribute::make(
            get: function (?int $value) :string {
                return match ($value) {
                    null => 'neutral',
                    1 => 'positive',
                    0 => 'negative',
                };
            },
            set: function (string $value): ?int {
                return match ($value) {
                    'neutral' => null,
                    'positive' => 1,
                    'negative' => 0,
                };
            }
        );
    }
```

Call updateOrCreate on the model multiple times with the same data.

Expected:
Single entry persisted in database regardless of number of times the method is called.

Actual:
When `src/Illuminate/Database/Eloquent/Builder.php::firstOrCreate()` is called, no results are found and another model is created.

**Comment by msonowal** [comment]
@Minhyme 
please share the code of the where you are calling the updaOrCreate with the parameters

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
