### ISSUE TITLE
New artisan look on windows

### ISSUE THREAD

**Issue by Eldair** [laravel/framework#43364]
- Laravel Version: 9.21.5
- PHP Version: 8.1.3
- Database Driver & Version:

### Description:

New artisan look introduced in https://github.com/laravel/framework/pull/43065/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34 looks broken on windows 11 using WSL 2 via MS terminal (12pt font size, 140 columns terminal width)

![image](https://user-images.githubusercontent.com/470003/180423555-b1287b2e-8db2-44ff-a171-ec180a7ddfc5.png)

### Steps To Reproduce:

Run any artisan command which returns the new look.

**Comment by nunomaduro** [comment]
We've tested this on Windows 10, and Windows 11, using the software you specified, and we are unable to reproduce your issue. We will need to wait for a few more reports, before spending more time investigating this issue. Meanwhile, fell free to do a pull request that fixes the issue for you.

**Comment by Eldair** [comment]
Hi @nunomaduro can you send Terminal settings you tested on so I can check it out?
