### ISSUE TITLE
Lazy loaded relations inside whenLoaded()

### ISSUE THREAD

**Issue by leuchte** [laravel/framework#43379]
- Laravel Version: 9.21.6
- PHP Version: 8.1.7
- Database Driver & Version: SQLite 3.36.0 / MariaDB 10.3.12

### Description:

Hello. When i use `$this->whenLoaded('relation', [])` in my resource file, the checked relation is lazy loaded. This is not a expected behavior, i think. When the relation is not present yet, the code inside the brackets should not be visible in the resource output and the relation shouldn't be loaded.

I got this simple relation in `App\Models\User`

```
public function relations()
 {
     return $this->hasMany(Relation::class);
 }
```

Call to the resource 

```
Route::get('/', function () {
    $user = User::first();

    return new App\Http\Resources\User($user);
});
```

The resource `App\Http\Resource\User`

```
public function toArray($request)
{
    return [
        'name' => $this->name,
        'email' => $this->email,
        'is_loaded_first' => $this->relationLoaded('relations'),
        'relations' => $this->whenLoaded('relations', [
            'objects' => Relation::collection($this->relations)
        ]),
        'is_loaded_second' => $this->relationLoaded('relations')
    ];
}
```

Expected output:
```
{
    "data": {
        "name": "Test User",
        "email": "test@example.com",
        "is_loaded_first": false,
        "is_loaded_second": false
    }
}
```

Given output:
```
{
    "data": {
        "name": "Test User",
        "email": "test@example.com",
        "is_loaded_first": false,
        "relations": {
            "objects": [
            {
                "name": "Darren Collins"
            }
        ]},
        "is_loaded_second": true
    }
}
```

Thank you, for your time.

**Comment by Rizky92** [comment]
You may be able to return the relation as closure that returns plain collection.  
```php
$this->whenLoaded('relation', fn () => Relation::collection($this->relation))
```

**Comment by leuchte** [comment]
Thank you @Rizky92 that helps.

For clarification: When to output a simple collection, its better to use it like that
```php
use App\Http\Resources\Relation;

return [
    'relations' => Relation::collection($this->whenLoaded('relations'))
];
```
Thats, what the documentation says and it works. 

In my case, i tried to sum up numbers from the relation within the `whenLoaded()` method

```php
return [
    'relationsNumbersSum'  => $this->whenLoaded('relations', $this->relations->sum('numbers'))
];
```

This does not work, resp. the relationship got lazy loaded. That was the point, where i tested the code in my initial post, not to realize, that i used it not how it was designed.

Anyway, with a closure like you suggested, it works fine.

```php
return [
    'relationsNumbersSum'  => $this->whenLoaded('relations', fn () => $this->relations->sum('numbers'))
];
```

Thanks again!

**Comment by rotarustefan** [comment]
@radmen sincerely I don't really understand all this, sorry. Done some changes but this doesn't work anymore when pushing the edited purchase request.
