### ISSUE TITLE
Using a custom FormRequest always modify the language of \Locale class from intl PHP extension

### ISSUE THREAD

**Issue by faeby** [laravel/framework#43371]
- Laravel Version: 9.21.0
- PHP Version: 8.1
- Database Driver & Version: MySQL / N/A

### Description:
We are using the intl PHP extension to localize dates in our views. Since the [pull request #42080](https://github.com/laravel/framework/pull/42080) was merged, the selected locale is always overriden by the framework when we use a custom `FormRequest` in the controller. The problem is not present if we use the default `Request` instead of a custom one.

We are setting the locale of the extension in the `app/Providers/AppServiceProvider.php`, in the `boot` method like this:

```php
    public function boot(): void
    {
        \Locale::setDefault(\App::getLocale());
    }
```

When the custom request is created from the base request, the default language is set in the file `src/Illuminate/Http/Request.php`, line 426:
```php
    $request->setDefaultLocale($from->getDefaultLocale());
```
and because the locale is null, the default Locale is also modified (line 1335):
```php
    /**
     * Sets the default locale.
     */
    public function setDefaultLocale(string $locale)
    {
        $this->defaultLocale = $locale;

        if (null === $this->locale) {
            $this->setPhpDefaultLocale($locale);
        }
    }
```
line 1869 of the Symfony vendor file `symfony/http-foundation/Request.php`:
```php
    private function setPhpDefaultLocale(string $locale): void
    {
        // if either the class Locale doesn't exist, or an exception is thrown when
        // setting the default locale, the intl module is not installed, and
        // the call can be ignored:
        try {
            if (class_exists(\Locale::class, false)) {
                \Locale::setDefault($locale);
            }
        } catch (\Exception) {
        }
    }
```

### Steps To Reproduce:
As requested, here is a repo that replicate the issue: https://github.com/faeby/laravel-issue-43371

1. create a new laravel project
2. set the default language in french in app.php
```php
    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => 'fr',
```
4. set the intl locale in the default locale of the app in the app service provider (shown above) 
```php
    public function boot(): void
    {
        \Locale::setDefault(\App::getLocale());
    }
```
5. create a custom request with the command `php artisan make:request ShouldBeInFrench` and authorize every to access it
6. add the followings routes in `routes/web.php`
```php
Route::get('/requests/custom', function (\App\Http\Requests\ShouldBeInFrench $request) {
    dump("INTL locale: " . \Locale::getDefault());
    return "I'm the custom request. <a href='/requests/base'>Go to base request</a>";
});

Route::get('/requests/base', function (\Illuminate\Http\Request $request) {
    dump("INTL locale: " . \Locale::getDefault());
    return "I'm the original request. <a href='/requests/custom'>Go to custom request</a>";
});
```
7. serve the app and navigate to the given URLs, and the intl locale shown is different
![image](https://user-images.githubusercontent.com/7632591/180475428-b5bf71de-04a0-4b83-b9ba-d5008feed638.png)
![image](https://user-images.githubusercontent.com/7632591/180475483-b2be0de5-9f76-40e6-a852-aaab3c68f095.png)

### Workaround:
As a workaround, we are manually setting the request default locale in the `AppServiceprovider` boot method. This is not perfect but we did not found a way to configure the request locale in a better way.
```php
    public function boot()
    {
        // Functional workaround.
        $this->app->afterResolving(FormRequest::class, function ($request, $app) {
            $app['request']->setDefaultLocale(App::getLocale());
        });

        \Locale::setDefault(App::getLocale());
    }
```

**Comment by driesvints** [comment]
Please recreate the repo with the following command and commit any custom changes into a single commit:

```bash
laravel new bug-report --github="--public"
```

Thanks!

**Comment by faeby** [comment]
Here is the new repository, created as requested: https://github.com/faeby/laravel-issue-43371
This is my first time submitting a bug report, so I hope this is correct this time.

**Comment by driesvints** [comment]
Thanks. I've sent in a PR for this: https://github.com/laravel/framework/pull/43426
