### ISSUE TITLE
Email content rendered inside code tag when formatted

### ISSUE THREAD

**Issue by hichemfantar** [laravel/framework#43395]
- Laravel Version: 9.11
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0.27

### Description:
When I tried formatting the `\resources\views\vendor\notifications\email.blade.php`, everything was rendered inside a code tag.
Not sure if this is a bug with the formatter or the Laravel blade parser however I believe It's related to laravel because from what I've seen, the content hasn't changed.

### Steps To Reproduce:
1. run `php artisan vendor:publish --tag=laravel-notifications`
2. Open the generated file `\resources\views\vendor\notifications\email.blade.php`
3. Format the file using this [extension](https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter)
4. Everything inside the file is now rendered inside an html code tag

Non formatted file:
```blade
@component('mail::message')
{{-- Greeting --}}
@if (! empty($greeting))
# {{ $greeting }}
@else
@if ($level === 'error')
# @lang('Whoops!')
@else
# @lang('Hello!')
@endif
@endif

{{-- Intro Lines --}}
@foreach ($introLines as $line)
{{ $line }}

@endforeach

{{-- Action Button --}}
@isset($actionText)
<?php
    $color = match ($level) {
        'success', 'error' => $level,
        default => 'primary',
    };
?>
@component('mail::button', ['url' => $actionUrl, 'color' => $color])
{{ $actionText }}
@endcomponent
@endisset

{{-- Outro Lines --}}
@foreach ($outroLines as $line)
{{ $line }}

@endforeach

{{-- Salutation --}}
@if (! empty($salutation))
{{ $salutation }}
@else
@lang('Regards'),<br>
{{ config('app.name') }}
@endif

{{-- Subcopy --}}
@isset($actionText)
@slot('subcopy')
@lang(
    "If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\n".
    'into your web browser:',
    [
        'actionText' => $actionText,
    ]
) <span class="break-all">[{{ $displayableActionUrl }}]({{ $actionUrl }})</span>
@endslot
@endisset
@endcomponent
```
Formatted file:
```blade
@component('mail::message')
    {{-- Greeting --}}
    @if (!empty($greeting))
        # {{ $greeting }}
    @else
        @if ($level === 'error')
            # @lang('Whoops!')
        @else
            # @lang('Hello!')
        @endif
    @endif

    {{-- Intro Lines --}}
    @foreach ($introLines as $line)
        {{ $line }}
    @endforeach

    {{-- Action Button --}}
    @isset($actionText)
        <?php
        $color = match ($level) { 'success', 'error' => $level,  default => 'primary' };
        ?>
        @component('mail::button', ['url' => $actionUrl, 'color' => $color])
            {{ $actionText }}
        @endcomponent
    @endisset

    {{-- Outro Lines --}}
    @foreach ($outroLines as $line)
        {{ $line }}
    @endforeach

    {{-- Salutation --}}
    @if (!empty($salutation))
        {{ $salutation }}
    @else
        @lang('Regards'),<br>
        {{ config('app.name') }}
    @endif

    {{-- Subcopy --}}
    @isset($actionText)
        @slot('subcopy')
            @lang("If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\n" . 'into your web browser:', [
                'actionText' => $actionText,
            ]) <span class="break-all">[{{ $displayableActionUrl }}]({{ $actionUrl }})</span>
        @endslot
    @endisset
@endcomponent

```

**Comment by ankurk91** [comment]
Please search for existing similar issue.

It is not recommended to format email blade templates

**Comment by hichemfantar** [comment]
Maybe this should be mentioned in the official documentation?

**Comment by Rizky92** [comment]
This issue isn't related to the framework, but maybe the extension you mentioned. Report to their repository instead.

**Comment by hichemfantar** [comment]
@Rizky92 as @ankurk91 already mentioned. The extension works as intended.

This is related to the way Laravel parses email templates apparently.

**Comment by Rizky92** [comment]
Indeed the extension works as intended. But you shouldn't be formatting your email template since it will be parsed to markdown format, that takes account of indentation.

**Comment by driesvints** [comment]
Indented code in a markdown file will always be rendered in a code tag. Don't do that when working with email templates.

**Comment by pixelated-au** [comment]
In PHPStorm, if trying to disable the auto-indent on blade (mail) markdown files, **make sure the [formatter comment markers has been enabled](https://www.jetbrains.com/help/phpstorm/2022.2/settings-code-style.html#formatter-control).**

Then you can add in a comment at the beginning of your blade file `{{--@formatter:off--}}`. This will disable all auto-formatting on the blade file

Full example:
```blade
{{--@formatter:off--}}
@component('mail::message')
# {{ config('app.name') }} Account Created
Your message body.
@component('mail::button', ['url' => 'https://examplecom'])
    Verify
@endcomponent
Thanks,<br>
{{ config('app.name') }}
@endcomponent
```

**Comment by hichemfantar** [comment]
VSCode solution:
https://github.com/shufo/vscode-blade-formatter#ignoring-files-bladeignore

**Comment by ItsDannyH** [comment]
For me using vscode I solved it by clicking blade in the bottom right then clicking:

> Configure 'blade' language based settings...

at the top of the screen.
Then adding the following line: 

> "editor.formatOnSave": false,

and that fixed my issue with editing mail templates without installing an extension
