### ISSUE TITLE
Phpunit Variables are not loading on Test Environment

### ISSUE THREAD

**Issue by Mekaeil** [laravel/framework#43409]
- Laravel Version: 9.x ( latest version )
- PHP Version: 8.1
- Database Driver & Version: mysql 8

### Description:
Phpunit.xml variables are not loaded on abstract TestCase!
After clearing cache, config, etc., I was unable to create a test environment with different DB.
 It is not possible for me to get the test  environment variable.

### Steps To Reproduce:

There are 2 ways to see the bug:
1. after changing you phpunit.xml file in your Abstract TestCase add this method and you can see the result:
```
    protected function setUp(): void
    {
        parent::setUp();

        dump(env('APP_NAME'));
        dd(env('APP_ENV'));
     }
```

After clearing cache, run test command (`php artisan test`)

2. change your bootstrap/app.php:

Create `.env.testing` file and change your app file:
```
$app = new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

$app->loadEnvironmentFrom('.env.testing');

dump(env('APP_NAME'));  // still load from .env
dd(env('APP_ENV'));  // still load from .env
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
