### ISSUE TITLE
Laravel/Eloquent Subquery binding backsquote issue

### ISSUE THREAD

**Issue by Jungminkyung** [laravel/framework#43415]
- Laravel Version: 9.20.0
- PHP Version: 8.1.6
- Database Driver & Version: mysql.exe  Ver 15.1 Distrib 10.4.24-MariaDB, for Win64 (AMD64)

### Description:
When i was binding Eloquent Model's subquery ,   I find bug that backsqurt is  bad placed
Please see that bold place

This is Error Source

DB::enableQueryLog();
$query = DB::table('quote_requests')->leftJoin('countries as c1', 'quote_requests.origin_country_iso', '=', 'c1.iso')
                ->leftJoin('countries as c2', 'quote_requests.destination_country_iso', '=', 'c2.iso')
                ->select('quote_requests.*', 'c1.english as origin_country', 'c2.english as destination_country')
                ->where('quote_requests.user_id','=',$user->id)
                ->whereNotIn('quote_requests.user_id', function($query){
                    _**$query->select('user_id')->from('invisible_quotes')->where('invisible_quotes.quote_id','=','quote_requests.id');**_
                })
                ->orderBy('quote_requests.id', 'desc');
Log::info(DB::getQueryLog());				

I want This Result 

select quote_requests.*, `c1`.`english` as `origin_country`, `c2`.`english` as `destination_country`
            from `quote_requests`
            left join `countries` as `c1` on `quote_requests`.`origin_country_iso` = `c1`.`iso` 
            left join `countries` as `c2` on `quote_requests`.`destination_country_iso` = `c2`.`iso`
            where `quote_requests`.`user_id` = 1 and quote_requests.user_id NOT IN (select user_id from invisible_quotes where _**invisible_quotes.quote_id = quote_requests.id**_ )
            order by `quote_requests`.`id` desc limit 10 offset 0

but getQueryLog()'s result is 

```
select `quote_requests`.*, `c1`.`english` as `origin_country`, `c2`.`english` as `destination_country` 
from `quote_requests` 
left join `countries` as `c1` on `quote_requests`.`origin_country_iso` = `c1`.`iso` 
left join `countries` as `c2` on `quote_requests`.`destination_country_iso` = `c2`.`iso` 
where `quote_requests`.`user_id` = '1' and `quote_requests`.`user_id` 
not in (select `user_id` from `invisible_quotes` 
where `invisible_quotes`.`quote_id` = 'quote_requests.id') order by `quote_requests`.`id` desc limit 10 offset 0
```                                        
                                        ↗ ↗↗↗  here

```
`quote_results.id`   is wrong sql. The correct sql is       `quote_results`.`id`
```

sorry for my bad skills.
and Thanks for reading.

**Comment by Smoggert** [comment]
Where only handles column = value cases.
are you thinking of whereColumn ?
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Query/Builder.php#L922

aka not a bug.

**Comment by Jungminkyung** [comment]
Thanks . :+1:
