### ISSUE TITLE
`route:list` command fails when an exception is thrown from the controller constructor

### ISSUE THREAD

**Issue by Kolyunya** [laravel/framework#43419]
- Laravel Version: v9.19.0
- PHP Version: 8.1.8

### Description:
`route:list` command fails when an exception is thrown from the controller constructor.

### Steps To Reproduce:
1. Create a route.
2. Create a controller for the route.
3. Inject a HTTP request into the controller constructor.
4. Throw an exception from the controller constructor, when the request is invalid.
5. Run `php artisan route:list` command.

Expected behaviour: command yields a list of routes.

Actual behaviour: command fails with an unhandled exception from the controller constructor because the default request is invalid.

### Possible solution
An instance of the controller [is created](https://github.com/laravel/framework/blob/8974fcc7659ef4879505a7748fa0e430de91d439/src/Illuminate/Routing/Route.php#L275) with the only purpose of determining a list of controller middleware.

I would suggest catching exceptions in the [getMiddleware()](https://github.com/laravel/framework/blob/61eac9cae4717699ecb3941b16c3d775820d4ca2/src/Illuminate/Foundation/Console/RouteListCommand.php#L208) method and printing something like `[unable to determine]` in the `middleware` column in case an exception occurred.

**Comment by driesvints** [comment]
I don't think we can really call this a bug in Laravel. This is a more of an issue in your own app.

**Comment by Kolyunya** [comment]
@driesvints how come an unhandled exception is not a bug?

Throwing exceptions from a controller is not a bug. The controller receives an invalid request and it throws a bad request exception which is not handled correctly by the `route:list`.

The command could display everything except for the middleware of one controller and instead, it just fails in the middle of the execution.

**Comment by driesvints** [comment]
No exceptions should occur during the instantiation of controllers or middleware. Only when handling controller methods or handling middleware.

**Comment by Kolyunya** [comment]
@driesvints is this an actual architectural limitation of the framework? I mean, could anything else (except for the broken `route:list` command) break in case of throwing from the controller constructor?
