### ISSUE TITLE
Can't use 'read' & 'unread' scopes from DatabaseNotification model

### ISSUE THREAD

**Issue by amrography** [laravel/framework#43425]
- Laravel Version: 8.x
- PHP Version: 7.4
- Database Driver & Version: mysql 8.x

### Description:

When trying to make a simple query for `DatabaseNotification` model. `DatabaseNotification::unread()->where('type', 'danger')->get()`, it throws an error. Because, it calls the **[unread](https://github.com/laravel/framework/blob/9d0dffff96c33939b1be336655ad12523138d16c/src/Illuminate/Notifications/DatabaseNotification.php#L97)** function instead of **[scopeUnread](https://github.com/laravel/framework/blob/9d0dffff96c33939b1be336655ad12523138d16c/src/Illuminate/Notifications/DatabaseNotification.php#L119)**.

I believe the same issue apply on **read** too. 

### Steps To Reproduce:

- I added a new column, type, to notifications table
- Call the query: `DatabaseNotification::unread()->where('type', 'danger')->get()` in my controller.

**Comment by Rizky92** [comment]
Turns it into query first.
```php
DatabaseNotification::query()
    ->unread()
    ->get();
```

**Comment by driesvints** [comment]
You indeed need to turn it into a query first. Thanks @Rizky92
