### ISSUE TITLE
Vite override via callbacks is not working

### ISSUE THREAD

**Issue by davidjr82** [laravel/framework#43424]
- Laravel Version: 9.21.6
- PHP Version: 8.1.2
- Database Driver & Version: NA

### Description:
Using this [documentation ](https://laravel-vite.dev/guide/essentials/tag-generation.html#override-via-callbacks) I want to override the vite tag generation, but it throws the following error:
```php
Call to undefined method Illuminate\Foundation\Vite::makeScriptTagsUsing()
```

### Steps To Reproduce:

Install fresh laravel application, and in the service provider insert the following code. Then the error is thrown.

```php
    public function boot()
    {
        // Overrides script tag generation
        Vite::makeScriptTagsUsing(function (string $url, Chunk $chunk = null): string {
            return sprintf('<script type="module" src="%s" defer></script>', $url);
        });

        // Overrides style tag generation
        Vite::makeStyleTagsUsing(function (string $url, Chunk $chunk = null): string {
            return sprintf('<link rel="stylesheet" href="%s" crossorigin="anonymous" />', $url);
        });
    }
```

**Comment by driesvints** [comment]
That's a different package? Maybe try their issue tracker?

**Comment by davidjr82** [comment]
I see... as that was the first entry in google, I thought it was the documentation of Laravel Vite 😒 

Is there any easy way to override the vite scripts?

**Comment by davidjr82** [comment]
I see it is an open discussion here in fact:

https://github.com/laravel/framework/discussions/43413

Thanks!
