### ISSUE TITLE
syntax error, unexpected token ")" when using version 6.0 of symfony/css-selector as part of illuminate/mail dependencies.

### ISSUE THREAD

**Issue by garethdaine** [laravel/framework#43427]
- Laravel Version: ^8.40
- PHP Version: ^8.0
- Database Driver & Version: Serverless v1 MySQL 5.7 (Laravel Vapor)

### Description:

I've come across a bug when sending out email via AWS SES (on Laravel Vapor) when the version of **symfony/css-selector** a dependency of **tijsverkoyen/css-to-inline-styles** which is a dependency in **illuminate/mail** is version 6.0.

Essentially, any time an email is sent (notification, password reset, email verification etc), it results in a 500 error with the message **syntax error, unexpected token ")"**.

Locking **symfony/css-selector** to version 5.4.3 fixes this issue and mail is sent fine.

### Steps To Reproduce:

With all versions above the same, simply try to send an email via AWS SES on Laravel Vapor.

**Comment by driesvints** [comment]
Symfony v6 is not compatible with Laravel 8. Please upgrade to Laravel 9.

**Comment by garethdaine** [comment]
> Symfony v6 is not compatible with Laravel 8. Please upgrade to Laravel 9.

Understood, but the dependencies and versions used are coming from **illuminate/mail** and we've not manually modified these (only added symfony/css-selector version 5.4.3 in the main project composer.json to downgrade the version to fix this issue).

As I say, we've not specifically or purposefully upgraded to Symfony 6 and our Laravel version is set to 8.83.22, so not entirely sure why symfony/css-selector 6.0 is being used.

**Comment by garethdaine** [comment]
@driesvints I've noticed that in the composer.json of the **tijsverkoyen/css-to-inline-styles** repo there is a dependency requirement for **"symfony/css-selector": "^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0"**, and as **illuminate/mail** has **"tijsverkoyen/css-to-inline-styles": "^2.2.2"** as a requirement, if a composer update was ran, would this essentially upgrade **symfony/css-selector** to version 6.0?

With Laravel 8 not being compatible with version 6 of Symfony, this may well be what caused the issue?

**Comment by driesvints** [comment]
This really seems like an incompatibility upstream rather than Laravel.

**Comment by garethdaine** [comment]
Thanks for the feedback @driesvints This was indeed due to platform specific issues when running composer update and has been resolved thanks to https://github.com/symfony/symfony/issues/47064.
