### ISSUE TITLE
Custom casts permanent isDirty if returned Carbon object.

### ISSUE THREAD

**Issue by Quiss** [laravel/framework#43428]
- Laravel Version: 9.21.6
- PHP Version: 8.1.0
- Database Driver & Version: PGSql 12

### Description:
If cast returned Carbon object than field permanent isDirty
This case don't reproduce for "date" or "custom_date" cast... because 
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1948
usage custom rule check

### Steps To Reproduce:
1. Create Custom Cast with return Carbon object
2. Setup usage custom cast
3. Get field from model
4. Check dirty

<img width="712" alt="2022-07-25_20 24 02" src="https://user-images.githubusercontent.com/4972114/180991872-4d8a9fad-7ad4-47ca-946a-b2af30f18238.png">
<img width="1057" alt="2022-07-25_20 27 45" src="https://user-images.githubusercontent.com/4972114/180991892-1bc3760c-db50-4753-bd59-92041b6ab3f2.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Quiss** [comment]
@driesvints I couldn't find the answer on discord.

**Comment by driesvints** [comment]
Please try one of the forums first

**Comment by andrey-helldar** [comment]
@driesvints, it's a really bug:

```php
$model = new TestEloquentModelWithCustomCast;

$this->assertFalse($model->wasChanged('birthday_at')); // ok
$this->assertFalse($model->isDirty('birthday_at')); // ok
$this->assertTrue($model->isClean('birthday_at')); // ok

$some = $model->birthday_at;

$this->assertFalse($model->wasChanged('birthday_at')); // ok
$this->assertFalse($model->isDirty('birthday_at')); // failed
$this->assertTrue($model->isClean('birthday_at')); // failed
```

Tested on https://github.com/laravel/framework/blob/9.x/tests/Integration/Database/DatabaseEloquentModelCustomCastingTest.php#L103-L105

**Comment by driesvints** [comment]
I'll take another look next Thursday. Feel free to send in a draft PR with a failing test that I can maybe use. Thanks!

**Comment by andrey-helldar** [comment]
> I'll take another look next Thursday. Feel free to send in a draft PR with a failing test that I can maybe use. Thanks!

I managed to study the problem. It occurs due to the fact that when creating the model, the "syncOriginal" method is called, which processes the [`classCastCache`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1618-L1635) array, which is empty at that time.

Therefore, by checking the attribute through the `isDirty` method, we get an exit from the function because the attribute key does not exist in the `$original` array:

```php
public function originalIsEquivalent($key)
{
    if (! array_key_exists($key, $this->original)) {
        return false; // returns that
    }

    // ...
}
```
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1929-L1939

```php
public function getDirty()
{
    $dirty = [];

    foreach ($this->getAttributes() as $key => $value) {
        if (! $this->originalIsEquivalent($key)) { // then true
            $dirty[$key] = $value;                 // and pushed to array
        }
    }

    return $dirty;
}
```
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1901-L1917

**Comment by Quiss** [comment]
@andrey-helldar @driesvints i think just add code like as https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L293-L300
to https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1935

**Comment by andrey-helldar** [comment]
@Quiss, can you try to add this code and run tests?

**Comment by Quiss** [comment]
@andrey-helldar Yeap. I'll let know the results ;)

**Comment by andrey-helldar** [comment]
@Quiss, can you create a PR then?

**Comment by Quiss** [comment]
@driesvints @andrey-helldar I have a bad news, there are two problems... 

Just keep the test case https://gist.github.com/Quiss/9bd87b9c53cf77dd284486140d4ee078

by @andrey-helldar case: attribute key doesn't exist in $originals
my case: attribute exist and not pass check.

**Comment by andrey-helldar** [comment]
In this case, it turns out that there is no error when creating a model using `new Model()`, but there is an error when requesting data from the database.

**Comment by Quiss** [comment]
@driesvints what do you need a repository for? There is a failed tests... 
https://gist.github.com/Quiss/9bd87b9c53cf77dd284486140d4ee078

**Comment by driesvints** [comment]
Please reproduce this issue on a fresh Laravel app for me with the above command so I can debug this better.

**Comment by Quiss** [comment]
Ok, i will create repo tomorrow

**Comment by driesvints** [comment]
I'll reopen this once a repo is provided.
