### ISSUE TITLE
Server stop caused by undefined array key 

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/framework#43433]
- Laravel Version: 9.22.0
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:
![image](https://user-images.githubusercontent.com/14665300/181038190-c23c0ec3-7948-47dc-b2ea-d3172d59429f.png)

### Steps To Reproduce:
I am using Laravel Nova V3, the errors occur a few seconds after the page is successfully served.

**Comment by nunomaduro** [comment]
@AbdelkaderBah Can't reproduce that issue locally. Did you modified the "server.php" in the root directory if your project?

**Comment by vitorsemeano** [comment]
I have a normal installation of laravel, and after a composer update, i am experiencing the same thing. After some requests, the command crashes with a undefined array key [random number].

Running php 8.0.17 and laravel 9.22.0. 

Reverting to 9.21.6 fixes the issue.

**Comment by RosiersRobin** [comment]
I have placed more information about when this occurres (almost instantaniously) in the PR;

https://github.com/laravel/framework/pull/43375#issuecomment-1195634397

**Comment by nunomaduro** [comment]
@antonkomarev @RosiersRobin @ankurk91 Can you share the full console output please?

**Comment by nunomaduro** [comment]
We've found the issue. It only happens on Windows - Powershell. We are working on a solution.

**Comment by ajibbagja14** [comment]
hello, i am encountering same issue with fresh Laravel v9.22.0 (using PHP v8.1.4) installation with no add on/other package installed, its really fresh from `composer create-project laravel/laravel`. In my case, the error occur when accessing the website via `http://localhost:8000`. My console log is looks like this : 

![Screenshot_427](https://user-images.githubusercontent.com/106526280/181053302-961a22b8-0443-48d6-b9cc-b410cec46388.png)

I am using PHP v8.1.4 and Windows 10 OS. 
Is there any way to fix this ? Thank you very much

**Comment by nunomaduro** [comment]
It's fixed on the latest version.

**Comment by nicolaibaaring** [comment]
The error is still on version 9.22.1, which as of this time is latest. I added my comments for it on the pull request #43437
