### ISSUE TITLE
Site breaks if no `manifest.json` file present

### ISSUE THREAD

**Issue by czernika** [laravel/framework#43430]
- Laravel Version: 9.21.6 with `laravel-vite-plugin` for assets
- PHP Version: 8.0
- Database Driver & Version: Mysql 8

### Description:
If `manifest.json` file was deleted (or just not present in `build` folder), "Missing Vite Manifest File" exception overrides any status response and shows blank page for production mode. We were updating our site from older Laravel version step by step and suddenly found out, 503 page is not shown - because `manifest.json` file was not present. Also it kinda breaks whole site, as now I can't see any page

### Steps To Reproduce:

1.Run `php artisan down`
2. Add `@vite(...)` directive to blade file
3. Delete `manifest.json` file (or do not "create" it)

Expected - 503 page
Actual - blank page for production, error page for local development (which is good for local, but for production I would like to see status page anyway)

**Comment by driesvints** [comment]
You don't need to add the vite directive to these pages. I can see the default 503 page just fine in a fresh Laravel app with Vite.
