### ISSUE TITLE
Artisan and empty lines in a containerized environment

### ISSUE THREAD

**Issue by mystygage** [laravel/framework#43435]
- Laravel Version: 9.21.6
- PHP Version: 8.1.8
- Database Driver & Version: mariadb 10

### Description:

Artisan's fresh look introduced in #43065 is really beautiful, but two empty lines are added to each call when a command like `php artisan schedule:run` is executed. This improves the readability immensely when these commands are executed in a developer's console.

As we run this command every 60 second in a containerized environment with log collection this creates a lot of noise:
```
[...]
service   |
service   |    INFO  No scheduled commands are ready to run.
service   |
service   |
service   |    INFO  No scheduled commands are ready to run.
service   |
service   |
service   |    INFO  No scheduled commands are ready to run.
service   |
service   |
service   |    INFO  No scheduled commands are ready to run.
service   |
[...]
```

It would be awesome to have an option like `--compact` to remove these empty lines.

### Steps To Reproduce:

Run a command like `php artisan schedule:run` and observe the empty lines around the actual response:

```
laravel@fc3108fb14:/var/www/html# php artisan schedule:run

   INFO  No scheduled commands are ready to run.

```

**Comment by nunomaduro** [comment]
Sorry, at this time there is no built-in solution for this. You can, of course, use bash in docker to "trim" those extra lines so they don't appear in your logs.
