### ISSUE TITLE
Mailer is encoding char = as =3D

### ISSUE THREAD

**Issue by bernardo-campos** [laravel/framework#43479]
- Laravel Version: 9.22.1
- PHP Version: 8.1.4
- Database Driver & Version:

### Description:
When sending an email, laravel is encoding the char **=** to **=3D**, it is a problem when sending HTML emails since it is not rendered properly

### Steps To Reproduce:

1. clone repository
2. php composer.phar install
3. copy .env and set MAIL_MAILER=log
4. php artisan key:generate

php artisan tinker

`Mail::raw('Hello=hola', function ($message) { $message->to('a@example.com')->subject('english=spanish');});`

laravel.log

> [2022-07-29 23:33:49] local.DEBUG: Laravel <hello@example.com>
> To: a@example.com
> Subject: english=spanish
> MIME-Version: 1.0
> Date: Fri, 29 Jul 2022 23:33:49 -0300
> Message-ID: <9641d97296a4ea13e386dae4de0a9431@example.com>
> Content-Type: text/plain; charset=utf-8
> Content-Transfer-Encoding: quoted-printable
> 
> Hello=3Dhola

One repo example:

https://github.com/bernardo-campos/testing-laravel-packages

**Comment by driesvints** [comment]
This would be an issue with symfony mailer as that's used under the hood to send the mail. Feel free to open an issue on their repo.
