### ISSUE TITLE
Expected a scalar, or an array as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::set()", "stdClass" given.

### ISSUE THREAD

**Issue by aneesdev** [laravel/framework#43478]
- Laravel Version: 9.22.1
- PHP Version: 8.0.11
- Database Driver & Version: MariaDB 10.3.31

### Description:

Hi. when using `$request->merge()` I'm getting this error:

![image](https://user-images.githubusercontent.com/92947803/181816760-e25db77c-df8d-4de2-b948-7cceac9426f7.png)
![image](https://user-images.githubusercontent.com/92947803/181816790-9c5df518-ff97-4492-aa60-a9dfc1fdcd01.png)

### Steps To Reproduce:

None

**Comment by Silinator** [comment]
Why did you close it? I have excat the same issue.

**Comment by aneesdev** [comment]
> Why did you close it? I have excat the same issue.

That's because I was casting a array into `(object)`:

![image](https://user-images.githubusercontent.com/92947803/211173619-34f72196-0b9f-49c9-87b1-71d789692762.png)

Which in Laravel 9. the internal Symfony HTTP component doesn't support

**Comment by Silinator** [comment]
> Which in Laravel 9. the internal Symfony HTTP component doesn't support

oh ok. But still isn't that kind of an odd thing? Or is there a reason behind it?
