### ISSUE TITLE
Invalid locale loaded for translator when page visited from hibernated device

### ISSUE THREAD

**Issue by ProteanCode** [laravel/framework#43486]
- Laravel Version: 8.54
- PHP Version: 8.1
- Database Driver & Version: Postgres

### Description:

When user visits the page from something that I may describe as hibernated device state (ie. the tablet screen was off for 3 minutes) the loaded locale is not valid. Using the `dd(app('translator'))` code line shows that loaded locale **is not** en, but en_US.

Reloading the page manually actually sets the locale correctly to just "en".

As a workaround, I did a symlink from en.json to en_US.json, and translation "works", but this is a hack nevertheless.

### Steps To Reproduce:

1. If you have a browserstack account, visit your page on ipad air 4 (using safari, but afaik other web browsers also have that problem).
2. At this stage the page translations you see should be fine, click on "stop session" to "hibernate" device
3. Open the closed device once again by clicking on it from the list, browserstack saves your last url so you will be now redirected to previous location, but with missing translations as the locale has been set to en_US

I have no idea why this happens, maybe it is some preflight / head request that is different from user hitting "reload" button, maybe there is a request made by javascript, but I know that at least once the same error has been reproduced on physical device therefore it is not browserstack fault.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
