### ISSUE TITLE
Auth()->User() Returning Wrong User?

### ISSUE THREAD

**Issue by haleyngonadi** [laravel/framework#43491]
- Laravel Version: 9.21.5
- PHP Version: 8.1.7
- Database Driver & Version: MYSQL / 5.7.37

### Description:
A user just tried to delete their account (they are logged in using their own username / password) but instead of deleting their account, it deleted my admin account (I was currently logged in on my own computer, in a completely different company). I believe this is a bug related to auth()->user() as another user tried to like a post but it liked it as me (the admin), even though I was never logged into their account. auth()->user() is seemingly returning the wrong user?

### Steps To Reproduce:

1. In UserController, create a deleteAccount function: 

```
public function deleteAccount()
  {

 $user = auth()->user();
 $user->delete();
 return redirect('/');
}
```

2. Using a form to send a post request and the user deleted should be the currently signed-in user on their own computer, and not you, the admin.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
