### ISSUE TITLE
validate empty string will do nothing, all is pass

### ISSUE THREAD

**Issue by ab0029** [laravel/framework#43506]
- Laravel Version: 6.* - 9.*
- PHP Version: 7+
- Database Driver & Version:

### Description:
validate empty string will do nothing, all the data is pass

like this:

`
    $data = [
        'a' => '',
        'b' => '',
    ];

    $v = Validator::make($data, [
        'a' => 'integer',
        'b' => [function($attribute, $value, $fail) {
            // validate something
            // here is no process
            var_dump($attribute, $value);
        }]
    ]);
    dd($v->validated());
`

**Comment by ab0029** [comment]
how can i validate with Closure when the data is a empty string

**Comment by ab0029** [comment]
here is the larave code:
Illuminate\Validation\Validator
when check the data is validatable , the method is all passed when the data is empty string
`
    protected function presentOrRuleIsImplicit($rule, $attribute, $value)
    {
        if (is_string($value) && trim($value) === '') {
            return $this->isImplicit($rule);
        }

        return $this->validatePresent($attribute, $value) ||
               $this->isImplicit($rule);
    }
`

**Comment by rodrigopedra** [comment]
Did you try adding the `required` rule?

~~~php
$data = [
    'a' => '',
    'b' => '',
];

$v = Validator::make($data, [
    'a' => ['required', 'integer'],
    'b' => ['required', function($attribute, $value, $fail) {
        // will process this rule if the value is present
        var_dump($attribute, $value);
    }]
]);

dd($v->validated());
~~~

**Comment by ab0029** [comment]
sometimes the data is no required，but need valiate with Closure , not is no process

**Comment by rodrigopedra** [comment]
But do you need to validate an empty string inside the closure?

Anyway, I believe you might be after creating an implicit custom rule:

> By default, when an attribute being validated is not present or contains an empty string, normal validation rules, including custom rules, are not run. [...]
>
> For a custom rule to run even when an attribute is empty, the rule must imply that the attribute is required. [...]
>
> **Warning**
> An "implicit" rule only implies that the attribute is required. Whether it actually invalidates a missing or empty attribute is up to you.

reference: https://laravel.com/docs/9.x/validation#implicit-rules

*PS: I omitted some parts from the docs for brevity*

**Comment by ab0029** [comment]
> But do you need to validate an empty string inside the closure?
> 
> Anyway, I believe you might be after creating an implicit custom rule:
> 
> > By default, when an attribute being validated is not present or contains an empty string, normal validation rules, including custom rules, are not run. [...]
> > For a custom rule to run even when an attribute is empty, the rule must imply that the attribute is required. [...]
> > Warning
> > An "implicit" rule only implies that the attribute is required. Whether it actually invalidates a missing or empty attribute is up to you.
> 
> reference: https://laravel.com/docs/9.x/validation#implicit-rules
> 
> _PS: I omitted some parts from the docs for brevity_

this code is run:

```
$data = [
    'b' => null,
];

$v = Validator::make($data, [
    'b' => [function($attribute, $value, $fail) {
        // will process this rule if the value is null
        var_dump($attribute, $value);
    }]
]);

dd($v->validated());
```

**Comment by ab0029** [comment]
the null data is run in Closure, the empty string is not work

**Comment by rodrigopedra** [comment]
Well, although I agree one would expect a `null` value to behave like a missing field or an empty string, the current behavior is actually inline with the docs for the implicit rules I linked above:

> By default, when an attribute being validated **is not present** or **contains an empty string**, normal validation rules, including custom rules, are not run.

It only skips other validation rules if the value is either:

- not present
- is an empty string

In the case of passing a `null` value, the field **is present** and **does not contain an empty string**, so the remaining rules will be checked.

Maybe this is an edge case that should be treated as a bug, as -- again -- I believe most people would expect `null` to behave like an empty or missing value. At least have a note added to the docs.

But I doubt the behavior on how validation rules are processed would be changed in a minor release. Specially as the current behavior is verbatim to what is written on the docs. 

I also believe that if this behavior would be changed, `null` values would behave like missing or empty strings, in other words, remaining rules would not be processed by default.

Right now, for the use case you described, it seems your only option is to create and use a custom implicit rule as linked above.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
