### ISSUE TITLE
[9.x] Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by kayw-geek** [laravel/framework#43510]
PHP version: 8.1.7
Laravel version: v9.21.6

### Description:
We have a problem that passing null to non-nullable parameters of built-in functions, the causes the log file to become very large, I try to fix it, but you don't seem to agree with my approach, Can you tell me what I should do?

#43508 
#43507

**Comment by driesvints** [comment]
Typecast your value before calling the methods.
