### ISSUE TITLE
Laravel casting empty JSON objects as empty arrays on the Illuminate\Http\Request class

### ISSUE THREAD

**Issue by lgrassini** [laravel/framework#43513]
- Laravel Version: 9.22.1
- PHP Version: 8.0.2
- Database Driver & Version: None

### Description:

When sending a POST or PUT request providing JSON data in the body the `Illuminate\Http\Request` class will cast any empty JSON object as empty array.

### Steps To Reproduce:

Create a simple route that will just output the received request:

```
    Route::post('/test', function (Request $request) {
        return $request;
    });
```

Send a POST or PUT request to the above created endpoint with a JSON payload containing an empty JSON object:

```
POST /api/test HTTP/1.1
Accept: application/json
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:8000
Content-Length: 48

{"order_id":123,"customer_id":321,"products":{}}
```

The response of that request will be:

```
{
  "order_id": 123,
  "customer_id": 321,
  "products": []
}
```

Note how `Illuminate\Http\Request` is casting `"products":{}` as `"products": []`. 
We are expecting the empty object `products` to be casted as it is, an empty JSON object, instead of an empty array.

This is also replicable on Laravel 8.x.
A similar issue was already reported [here](https://github.com/laravel/framework/issues/443) and closed without solution.

**Comment by driesvints** [comment]
Requests are decoded as associative arrays. After doing that, there's no way of knowing what was an array and what was an object.
