### ISSUE TITLE
Database seeder output is messed up by new Artisan look

### ISSUE THREAD

**Issue by halloei** [laravel/framework#43515]
- Laravel Version: 9.22.1
- PHP Version: 8.1.8
- Database Driver & Version: MySQL 8.0

### Description:
In my database seeders I'm writing output to the console via `$this->command->info()`. Unfortunately #43065 messed it up:

```shell
~$ ./artisan db:seed 

   INFO  Seeding database.  

  Database\Seeders\Users\GroupSeeder ..................................................................................................... 12ms DONE
  Database\Seeders\Users\PermissionSeeder Deleted 0 and created 0 permissions
................................................................................................ 18ms DONE

```

If you're wondering what I'm doing here: I'm hardcoding the user groups and permissions of my application into seeders. The seeders then keep the database in sync.

### Steps To Reproduce:

Create a new seeder an run database seeding:
```php
class TestSeeder extends Seeder
{
    public function run()
    {
        $this->command->info('Lorem ipsum');
    }
}
```

**Comment by ankurk91** [comment]
![Screenshot from 2022-08-03 10-33-46](https://user-images.githubusercontent.com/6111524/182528157-b0af62e0-e552-425b-a897-2930a52171e8.png)
![Screenshot from 2022-08-03 10-34-08](https://user-images.githubusercontent.com/6111524/182528161-b9632cd1-e199-4fa3-8838-8e3001b8be55.png)

**Comment by nunomaduro** [comment]
@ankurk91 With the console output improvements, we don't really expect "output" in the middle of seeders. Same goes when calling `Artisan::call(` within seeders, can you consider running that command discarding the output?

**Comment by ankurk91** [comment]
One can do like

```php
<?php

class DatabaseSeeder extends Seeder
{
   
    public function run()
    {
        // So laravel team does not recommand to do this in seeders?
        $this->command->info('Importing huge data from csv');
  
        Artisan::call(ImportCSVCommand::class, [
            'file' => database_path('raw/huge-csv.csv'),
            '--force' => true,
        ], $this->command->getOutput()); // We should not supply the last argument here? 

  }
```

I have tried to remove the last parameter from `Artisan::call`, but now it does not show any output form artisan command.
The artisan command has lines like
```php
$this->line(now().' Starting file import ...');
```
which we want to append on the terminal when running from seeder. we have been doing this from years already.


> we don't really expect "output" in the middle of seeders.

Then we should also deprecate the  `$this->command` in seeder

**Comment by halloei** [comment]
@nunomaduro Doesn't sound like an improvement, at least for me.

Wouldn't it be possible to display the output similar to `./artisan route:list --verbose`?

![image](https://user-images.githubusercontent.com/4547019/182573420-6d8ca9fd-22f4-4d31-b552-761ca348913d.png)

The rows that are used to display the middleware (groups) here could be our output instead.

I think this would be a useful addition as there are likely other use cases in the future.

**Comment by ankurk91** [comment]
ping @nunomaduro 
We have not heard from you.

**Comment by nunomaduro** [comment]
We are going to address this issue soon.
