### ISSUE TITLE
Translation of array attributes from validator

### ISSUE THREAD

**Issue by FranciscoCaldeira** [laravel/framework#43532]
- Laravel Version: 8.83.11
- PHP Version: 7.4.28 (cli)
- Database Driver & Version: MariaDB 10.8.3

### Description:
Translate keys from the validator attributes when it is array.

### Steps To Reproduce:

1º Have validator with arrays ('image.author' and 'image.book').
```
$validator = Validator::make($request->all(), [
    'title' => 'required|unique:posts|max:255',
    'body' => 'required',
    'image.author' => 'required',
    'image.book' => 'required',
]);
```
2º Add on validation.php these attributes.
```
'attributes' => [
    'image.author' => image of author',
    'image.book' => 'image of book',
],
```
3º Use tinker to debug:
 `__('validation.attributes.image.author');`
>"validation.attributes.image.author"

And the output corret should be:
>"image of author"

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
