### ISSUE TITLE
League\Flysystem\FileNotFoundException for existing files

### ISSUE THREAD

**Issue by Artem-Schander** [laravel/framework#43534]
- Laravel Version: 8.83.23
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8

### Description:
Sometimes I get said exception regardless of the files being accessible.
The only thing that helps is to clear the cache `php artisan cache:clear`.
This is extremely annoying for my customers, since they need to notice it and to inform me to get access to their files.
Is there anything I can do to avoid this?[
Original ticket at thephpleague/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3/issues/306)

### Steps To Reproduce:
This issue can not be reproduced at will

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
