### ISSUE TITLE
fake() helper doesn't work with own faker provider (extended)

### ISSUE THREAD

**Issue by fcno** [laravel/framework#43539]
- Laravel Version: 9.23.0
- PHP Version: 8.1.1
- Database Driver & Version: MySql 8, but its not important

### Description:
Helper fake() has a different implementation that makes it not possible to use it if you need to create your own faker, extending the provided generators. Using the old recommendation (Laravel 8.x) ($this->faker...) works.

I think it would be correct to implement the fake() helper to resolve the faker instance in the same way as $this->faker, making both approaches compatible.

### Steps To Reproduce:
1) Create a fresh laravel application;

2) Create a faker provider;

```php
<?php

namespace App\Faker;

use Faker\Provider\Base;

class SomeTextProvider extends Base
{
    public static function someText()
    {
        return 'something';
    }
}
```

3) Register the Laravel provider
```php
<?php

namespace App\Providers;

use App\Faker\SomeTextProvider;
use Faker\Factory;
use Faker\Generator;
use Illuminate\Support\ServiceProvider;

class FakerServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(Generator::class, function () {
            $faker = Factory::create();
            $faker->addProvider(new SomeTextProvider($faker));

            return $faker;
        });
    }

    public function boot()
    {
        //
    }
}
```

```php
// config/app.php

'providers' => [
        /*
         * Application Service Providers...
         */
        App\Providers\FakerServiceProvider::class,
    ],
```

4. Finally, use it
```php
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class MyFactory extends Factory
{
    public function definition()
    {
        return [
            'some_column' => fake()->someText(), //Don't Work
            // 'some_column' => $this->faker->someText(), //Works
        ];
    }
}

```

5. The output

The approach that doesn't work throws the exception

InvalidArgumentException
- Unknown format "someText"

**Comment by timacdonald** [comment]
See: https://github.com/laravel/framework/issues/42988#issuecomment-1169450207

**Comment by fcno** [comment]
@timacdonald It seems that the bug is with me that I didn't know how to look in the already closed issues.
It worked perfectly and sorry for the wrong issue.

**Comment by timacdonald** [comment]
No need to apologise at all and glad you got it sorted 🤘

**Comment by JonMoreno** [comment]
Nothing from above seem to help in my case:

Im using Laravel 10.10  
I was attempting to "\Ottaviano\Faker\Gravatar" to the current Laravel faker() helper.
Here is also a list of more third party libraries one can add https://fakerphp.github.io/third-party/

This is what worked:

`
use Faker\Factory;
use Faker\Generator;
use \Ottaviano\Faker\Gravatar;
use Illuminate\Support\ServiceProvider;

class FakerServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(Generator::class, function () {
            $faker = Factory::create();
            $faker->addProvider(new Gravatar($faker));
            return $faker;
        });

        $this->app->bind(
            Generator::class . ':' . config('app.faker_locale'),
            Generator::class
        );
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}`


Lastly make sure the new provider is register in app.php under "propviders":

`
 'providers' => ServiceProvider::defaultProviders()->merge([
         /* here */
        App\Providers\FakerServiceProvider::class,

   ])->toArray(),`
