### ISSUE TITLE
Laravel uses `--column-statistics=0` with MariaDB

### ISSUE THREAD

**Issue by direc85** [laravel/framework#43530]
- Laravel Version: 8.83.23 (but it looks like it exist in Laravel 9, too)
- PHP Version: 8.1.2
- Database Driver & Version: 10.19 Distrib 10.6.7-MariaDB

### Description:
`artisan schema:dump` (and some migrations) generates the dump, but produces the following warning:

`mysqldump: unknown variable 'column-statistics=0'`

### Steps To Reproduce:

I was running Laravel in a Docker container with Ubuntu 21.04, PHP 7.4 and MariaDB 10.3. I then updated the docker config files to kick it to Ubuntu 22.04, PHP 8.1 and MariaDB 10.6. After upgrading the database using `mysql_upgrade` I started to poke the system to see what works and what doesn't. The first thing I tried was `artisan schema:dump` and it worked, but it produced the error message above.

So, I guess the steps to reproduce are either:

1) Setup Ubuntu 21.04 with PHP 7.4 and MariaDB 10.3
2) Install Laravel 8 with MariaDB
3) Update to Ubuntu 22.04 with PHP 8.1 and MariaDB 10.6
4) Upgrade the database
5) `artisan schema:dump`

Or simply:

1) Setup Ubuntu 22.04 with PHP 8.1 and MariaDB 10.6
2) Install Laravel 8 with MariaDB
3) `artisan schema:dump`

I also found #34442 which fixed the issue back in 2020 by inserting `--column-statistics=0` only if the connection is not MariaDB, but the change has been edited out at some point. The function `baseDumpCommand()` is identical in `master`, `8.x` and `9.x` branches, and thus I considered this bug report still valid, although I am still at Laravel 8 (I will be updating to Laravel 9 soon, I hope.)

I then fixed the issue for myself by editing `vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlSchemaState.php` as follows:

```php
protected function baseDumpCommand()
{
    $command = 'mysqldump '.$this->connectionString().' --no-tablespaces --skip-add-locks --skip-comments --skip-set-charset --tz-utc';

    if (! $this->connection->isMaria()) {
        $command .= ' --set-gtid-purged=OFF --column-statistics=0';
    }

    return $command.' "${:LARAVEL_LOAD_DATABASE}"';
}
```

One unknown in this equation for me is that why `mysqldump` 10.3 didn't complain about this, but 10.6 now does.

Thanks!

**Comment by direc85** [comment]
Okay, it looks like Laravel [8.83.19](https://github.com/laravel/framework/releases/tag/v8.83.19) has #43027 which explicitly reverts this, but that makes the warning appear for me. I updated Composer packages before running the first `artisan` command, the current version is 8.83.23, and I am now affected.

Also, in #43027 the affected setup us using Sail, wheras I'm not. These two seem to behave differently in this context. I think the underlaying issue is somewhere there (artisan vs. sail).

**Comment by driesvints** [comment]
I think right now, if things work with our own Docker provider (Sail) that we won't take an action to remove that flag if it risks breaking things again. If you figure out a way that solves this without breaking Sail then we'd be happy to receive a PR to 9.x. Sorry.

**Comment by direc85** [comment]
Thanks for the reply. It's a Sail issue, as it always installs `mysql-client` even if only MariaDB is installed. I'll try to figure out how to properly solve the issue, but that's going to happen sometime next week, I think.

**Comment by direc85** [comment]
It's not the `mariadb-client` installation that breaks the command (I should have reported this earlier, sorry).

I have performed a clean install on a new host, taken Sail into use in my existing environment, and even performed the aforementioned Laravel 8 -> 9 upgrade with a purpose-built Ubuntu 20.04 -> 22.04 virtual machine, but I always get the `mysqldump: unknown variable 'column-statistics=0'`. I still believe this is a valid issue.
