### ISSUE TITLE
Missed some spaces in some Artisan commands with new look

### ISSUE THREAD

**Issue by sarukomine** [laravel/framework#43543]
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version:

### Description:
Thanks @nunomaduro for a great work at #43065, I already like it, but I found some places that make me uncomfortable...

The places that the red arrow point at, I think that there should be the additional space.

![Screenshot 2022-08-04 at 2 16 39 PM](https://user-images.githubusercontent.com/39088208/182777862-17341b1b-6e0c-4e3e-894e-f5fbba0add6f.png)
![Screenshot 2022-08-04 at 2 20 48 PM](https://user-images.githubusercontent.com/39088208/182777868-a36b629f-94f4-4245-8ba9-89dadfdd387c.png)
![Screenshot 2022-08-04 at 2 21 31 PM](https://user-images.githubusercontent.com/39088208/182777871-cfa4cf12-2860-4b00-9ad0-9810afe9e170.png)

### Steps To Reproduce:

run `artisan migrate` / `artisan migrate:refresh --step=3 --seed` / `artisan db:seed` / `artisan migrate:rollback` / `artisan migrate:fresh`

**Comment by lk77** [comment]
I don't see any reason to have a space after the output

**Comment by driesvints** [comment]
Not sure I see a real bug here but rather an improvement. Feel free to attempt a PR if you like 👍
