### ISSUE TITLE
Storage::exists() may throw a UnableToCheckDirectoryExistence Excepion

### ISSUE THREAD

**Issue by CSalih** [laravel/framework#43552]
- Laravel Version: 9.x
- PHP Version: --
- Database Driver & Version: --

### Description:

The `Storage::exists` has since v9.x under some conditions a side effect witch leads to an unexpected behavior. With `league/flysystem-aws-s3-v3 "^3.0"` the behavior of `League\Flysystem\Filesystem::has()` has changed compared to `league/flysystem-aws-s3-v3 "^1.0"`:

When calling `Storage::disk('s3')->exists()` with a file witch does not exist on S3 the underlying Flysystem Adapter will call [directoryExists()](https://github.com/thephpleague/flysystem/blob/1eb269b0a4ad2003cd451f872700a628fc270b31/src/Filesystem.php#L48) as Fallback and this will now cause a `UnableToCheckDirectoryExistence` Exception when the List-Permission  is missing (due to some security conditions).

I think this unexpected behavior should be documented in the Upgrade Guide, so others can notice this breaking change. As an alternative (or maybe a better solution) the `Filesystem` Interface could expose `fileExists()` and `directoryExists()` so that the user have control (this would also avoid this double check of the S3 Adapter).

### Steps To Reproduce:

1. AWS IAM without List Permissions
2. Run following: `Storage::disk('s3')->exists('this-should-not-exists')`

#### Before:
The S3 Adapter returned false (See: [doesDirectoryExist()](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/af286f291ebab6877bac0c359c6c2cb017eb061d/src/AwsS3Adapter.php#L716))

#### Now:
The S3 Adapter now throw a `UnableToCheckDirectoryExistence` Exception (See: [directoryExists](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/257893ef7398b3c9255b26dff8b0118bb93fc5ff/AwsS3V3Adapter.php#L180))

**Comment by driesvints** [comment]
This is a breaking change in Flysystem, not Laravel and should go into the Flysystem upgrade guide.
