### ISSUE TITLE
php artisan docs command opens a new shell window instead of browser 

### ISSUE THREAD

**Issue by hopkins385** [laravel/framework#43561]
Hi guys, I'm very excited about the new artisan docs command. 
Unfortunately on my local dev machine the behavior is not as expected.

I'm using vscode with powershell and the artisan docs command does open a new shell window intead of opening my browser. 
Might be solveable via a local config update .. but idk where. 

Anyone who can give advice?

- Laravel Version: Laravel Framework 9.23.0
- PHP Version: PHP 8.1.6 (cli)
- Database Driver & Version:
- OS: Win10 x64
- PowerShell: PSVersion 5.1.19041.1682
- VSCode: 1.70.0
- NodeJS: v18.1.0
- Xampp: Xampp with php 8.1.6

### Description:
php artisan docs opens a new shell window instead of opening my browser 

### Steps To Reproduce:
1.) Enter in vscode shell console `php artisan docs validation rules`

### Hint
If I enter into the same console `start https://laravel.com/docs/9.x/validation#available-validation-rules ` then it is working as expected and a new tab is opened in my standard browser

**Comment by scajal** [comment]
I'm facing the same issue in the exact same version.

**Comment by Saifallak** [comment]
i guess this is solved by https://github.com/laravel/framework/pull/43566

**Comment by timacdonald** [comment]
I believe this will be fixed by the above mentioned PR and will be released on Tuesday. Please let me know if issues still persist.

**Comment by hopkins385** [comment]
Confirmed. Works now as expected.

**Comment by timacdonald** [comment]
Fantastic news. Thanks for reporting back @hopkins385
