### ISSUE TITLE
SQLSTATE[HY000] [2002] Operation timed out when using session database driver

### ISSUE THREAD

**Issue by cris-m** [laravel/framework#43570]
- Laravel Version: 9.20.0
- PHP Version: 8.1.9
- Database Driver & Version: 10.4.21-MariaDB

### Description:
I am using database session. Some time the project throw the following exception if I closed the the the project and browser without logout.
```
SQLSTATE[HY000] [2002] Operation timed out
select * from `sessions` where `id` = w83nMPCSXBBMDbqRGCyVTzSZaqGyND14budSPb7A limit 1
```
The `id` change depending of the session.

<img width="1792" alt="Screen Shot 2022-08-06 at 12 56 52" src="https://user-images.githubusercontent.com/29815096/183232732-0315a7fe-08b4-4c84-9f96-476abb0fd0e2.png">

### Steps To Reproduce:
- Change `SESSION_DRIVER` value to `database` in `.env` file.
- Create a session table. `php artisan session:table` and migrate using `php artisan migrate`.
- Create a new user.
- Login using the new user. After login close the browser without logout.
- Stop the project and mysql service.
- Restart the mysql service and Start the project.
- Try to access any route of the project and the error will be reproduce.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
