### ISSUE TITLE
Laravel 6.x distinct validation deep level array problem.

### ISSUE THREAD

**Issue by rifqi96** [laravel/framework#43579]
- Laravel Version: 6.20.44
- PHP Version: 7.4.3
- Database Driver & Version: mysql 8.0

### Description:
Validation `distinct` doesn't work well with multi level array.

### Steps To Reproduce:

Validator:
```php
Validator::make($data, [
  'value.our_team.*.personalities.*.type' => 'distinct'
])->validate();
```

#### Test case

Data `$data`:
```json
{
    "value": {
        "our_team": [
            {
                "user": 4,
                "avatars": [ 2560, 2561 ],
                "personalities": [
                    {
                        "type": "tvk",
                        "value": "tea"
                    },
                    {
                        "type": "cvd",
                        "value": "cats"
                    }
                ]
            },
            {
                "user": 1,
                "avatars": [ 2562, 2563 ],
                "personalities": [
                    {
                        "type": "tvk",
                        "value": "tea"
                    },
                    {
                        "type": "cvd",
                        "value": "cats"
                    }
                ]
            }
        ]
    }
}
```

#### Test case: Result

**Failed**. Because it also checks against `our_team[1].personalities[0].type` in the validation.

#### Test case: Expected behaviour

**Success**. As it should only validate `our_team[0].personalities[*].type`.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
