### ISSUE TITLE
When all field names on a page are integers, validations fail

### ISSUE THREAD

**Issue by chuckgreenman** [laravel/framework#43581]
- Laravel Version: 9.19
- PHP Version: 8.0.2
- Database Driver & Version: MySQL

(Current Sail Setup)

### Description:
When all inputs in a request are integers Laravel's validator returns a zero indexed array of the right size.

[This  repository has a minimal Laravel app that can be sail'd up](https://github.com/chuckgreenman/validator-bug-demo)

<img src="https://i.imgur.com/OWvsXlg.png" />

The issue appears to be in the addRules function in Validator.php:
```
public function addRules($rules)
    {
        // The primary purpose of this parser is to expand any "*" rules to the all
        // of the explicit rules needed for the given data. For example the rule
        // names.* would get expanded to names.0, names.1, etc. for this data.
        $response = (new ValidationRuleParser($this->data))
                            ->explode(ValidationRuleParser::filterConditionalRules($rules, $this->data));

        $this->rules = array_merge_recursive(
            $this->rules, $response->rules
        );

        $this->implicitAttributes = array_merge(
            $this->implicitAttributes, $response->implicitAttributes
        );
    }
```

```
<?php

$rules = [];
$response = [
  1 => [0 => 'required'],
  2 => [0 => 'required'],
  3 => [0 => 'required'],
];

var_dump(array_merge_recursive($rules, $response));
```
Which Yields:

```
array(3) {
  [0]=>
  array(1) {
    [0]=>
    string(8) "required"
  }
  [1]=>
  array(1) {
    [0]=>
    string(8) "required"
  }
  [2]=>
  array(1) {
    [0]=>
    string(8) "required"
  }
}
```

My initial idea was to rekey with arrays, casting the integer keys to strings, but that did not work.

### Steps To Reproduce:
1. Create a fresh Laravel Application.
2. Create a controller to facilitate your form's execution.
3. Create a view with a form where the field names are integers, starting from a non-zero number.
4. Require each field
5. View the errors, the keys will inaccurately start from zero.

**Comment by chuckgreenman** [comment]
I've opened a PR with a fix here, please let me know what you think.

**Comment by driesvints** [comment]
I don't think we support this because of PHP's behavior of how array's are indexed.
