### ISSUE TITLE
DatabaseRule doesn't work with enum

### ISSUE THREAD

**Issue by develgold** [laravel/framework#43603]
- Laravel Version: 9.23.0
- PHP Version: 8.1.0

### Description:
DatabaseRule doesn't work with enum

### Steps To Reproduce:

```php
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Enums\UnitType;

Validator::make([], ['type' => UnitType::weight]);
```
This code returns error ``` PHP Error:  Object of class App\Enums\UnitType could not be converted to string in  ```

**Comment by driesvints** [comment]
Seems like a feature request.
