### ISSUE TITLE
Collection: sortBy() on multiple attributes doesn't keep original keys

### ISSUE THREAD

**Issue by arthurperton** [laravel/framework#43608]
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version: N/A

### Description:
After using the [sortBy()](https://laravel.com/docs/9.x/collections#method-sortby) method the sorted collection is supposed to 'keep the original array keys'. And this is what is does, unless you pass an array of sort operations. Then the original keys are lost.

### Steps To Reproduce:

Code:
```php
$data = collect(['a' => ['sort' => 2], 'b' => ['sort' => 1]]);
$data = $data->sortBy([['sort', 'asc']]);

dd($data->all());
```

Expected output:
```php
array:2 [▼
  'b' => array:1 [▼
    "sort" => 1
  ]
  'a' => array:1 [▼
    "sort" => 2
  ]
]
```

Actual output:
```php
array:2 [▼
  0 => array:1 [▼
    "sort" => 1
  ]
  1 => array:1 [▼
    "sort" => 2
  ]
]
```

**Comment by driesvints** [comment]
I was looking into this but looks like you already sent in a fix. Thanks! :)

**Comment by arthurperton** [comment]
You're welcome 👍🏻
