### ISSUE TITLE
Problem with the new db:show command

### ISSUE THREAD

**Issue by Sergiobop** [laravel/framework#43622]
- Laravel Version: 9.24.0
- PHP Version: 8.1
### Description:

The command works fine, but i get multiple errors in my log:
local.ERROR: Undefined array key "engine" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"engine\" at ...vendor/doctrine/dbal/src/Schema/Table.php:888)

### Steps To Reproduce:
Using the new `php artisan db:show`

**Comment by jbrooksuk** [comment]
What database engine are you using?

**Comment by ZebTheWizard** [comment]
It appears this new command also has problems showing enum data types

**Comment by Sergiobop** [comment]
Hi @jbrooksuk , i'm using pgsql driver. The config is the default:
```
  'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],
```

I get multiple times the error:
Undefined array key "engine" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"engine\" at .../vendor/doctrine/dbal/src/Schema/Table.php:888)


Maybe it's related to the array config keys? In the mysql driver, we have that 'engine' key.

Thanks

**Comment by driesvints** [comment]
Seems a PR was sent in. Thanks all.
