### ISSUE TITLE
Undefined array key -1 Sqlite

### ISSUE THREAD

**Issue by andresilvagomez** [laravel/framework#43640]
- Laravel Version: 9.24.0
- PHP Version: 8.1.8
- Database Driver & Version: 

### Description:

   ErrorException 

  Undefined array key -1

  at vendor/doctrine/dbal/src/Schema/SqliteSchemaManager.php:605
    601▕         $foreignKeyCount   = count($foreignKeyDetails);
    602▕ 
    603▕         foreach ($columns as $i => $column) {
    604▕             // SQLite identifies foreign keys in reverse order of appearance in SQL
  ➜ 605▕             $columns[$i] = array_merge($column, $foreignKeyDetails[$foreignKeyCount - $column['id'] - 1]);
    606▕         }
    607▕ 
    608▕         return $columns;
    609▕     }

### Steps To Reproduce:

In Each Test.

**Comment by yelloalejo** [comment]
This is a doctrine/dbal package issue, they will fix that with next release (4.0.1 )
https://github.com/doctrine/dbal/issues/5584#issuecomment-1210723304
