### ISSUE TITLE
Cannot override relationship select statement.

### ISSUE THREAD

**Issue by ZebTheWizard** [laravel/framework#43649]
- Laravel Version: 9.24
- PHP Version: 8.1.8
- Database Driver & Version: MySql 8

### Description:

Calling `select` after relationship causes unexpected behavior.

### Steps To Reproduce:

I have a table called `releases` which holds two polymorphic relationships like the following and I am using it as a pivot table.

Releasable_id | Releaseable_type | Releaser_id | Releaser_type | version
|---|---|---|---|---|
89 | App\Models\App | 3 | App\Models\Team | 1.0.1
89 | App\Models\App | 3 | App\Models\Team | 1.0.2
89 | App\Models\App | 4 | App\Models\Team | 1.0.1
89 | App\Models\App | 4 | App\Models\Team | 1.0.2
89 | App\Models\App | 4 | App\Models\Team | 1.0.3

When I go to select the related `Teams` for a given `App`, I get back duplicate results because the version number makes a given relationship unique.

```
App::find(89)
    ->morphedByMany(
        Team::class, 
        'releaser', 
        'releases', 
        'releasable_id', 
        'releaser_id'
    );
```

teams (id) | Pivot 
|---|---|
3 | 1.0.1
3 | 1.0.2
4 | 1.0.1
4 | 1.0.2
4 | 1.0.3

### Attempted Workaround
I tried working around the default relationship by providing a new select clause then grouping by the team id.

```
App::find(89)
    ->morphedByMany(
        Team::class, 
        'releaser', 
        'releases', 
        'releasable_id', 
        'releaser_id'
    )
    ->select('teams.*')
    ->groupBy('teams.id')
;
```

When I print the SQL for the query above I get the following:
```
select `teams`.* 
from `teams` 
inner join `releases` 
    on `teams`.`id` = `releases`.`releaser_id` 
where `releases`.`releasable_id` = ? 
    and `releases`.`releaser_type` = ? 
    and `teams`.`deleted_at` is null 
group by `teams`.`id`
```

However, when I call `get()` on the relationship. The `groupBy` statement fails because Laravel adds additional select statements to provide pivot data. 
```
`releases`.`releasable_id` as `pivot_releasable_id`, `releases`.`releaser_id` as `pivot_releaser_id`, `releases`.`releaser_type` as `pivot_releaser_type
```

See error below:

```
Syntax error or access violation: 1055 Expression #10 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mydb.releases.releasable_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `teams`.*, `releases`.`releasable_id` as `pivot_releasable_id`, `releases`.`releaser_id` as `pivot_releaser_id`, `releases`.`releaser_type` as `pivot_releaser_type` from `teams` inner join `releases` on `teams`.`id` = `releases`.`releaser_id` where `releases`.`releasable_id` = 89 and `releases`.`releaser_type` = App\Models\Team and `teams`.`deleted_at` is null group by `teams`.`id`)'
```

### Question
If this is not a bug, how can I override the default select statement on a relationship query, or even better, how can I create a polymorphic many-to-many relationship which has two polymorphic types?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
