### ISSUE TITLE
Samae validation rule with null values

### ISSUE THREAD

**Issue by khairy-pelcro** [laravel/framework#43643]
- Laravel Version: 8.x
- PHP Version: 7.4

### Description:
when using the same validation rule with nullable fields it always gives a validation error with fields does not match if another field is null

### Steps To Reproduce:

```php
$v = new Validator($trans, ['foo' => 'bar', 'baz' => null], ['foo' => 'Same:baz']);
$this->assertTrue($v->passes());

```

@taylorotwell if this test case should pass I will create PR to handle this

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by khairy-pelcro** [comment]
Hey @driesvints 

I have tried in laravel 9 and this problem still there will create another issue for laravel 9
