### ISSUE TITLE
Samae validation rule with null values 

### ISSUE THREAD

**Issue by khairy-pelcro** [laravel/framework#43657]
- Laravel Version: 9.x
- PHP Version: 8.1

### Description:
when using the same validation rule with nullable fields it always gives a validation error with fields does not match if another field is null

### Steps To Reproduce:

```php
$v = new Validator($trans, ['foo' => 'bar', 'baz' => null], ['foo' => 'Same:baz']);
$this->assertTrue($v->passes());

```

**Comment by khairy-pelcro** [comment]
Hey @driesvints 

if you approved that this is an issue will create a PR to fix it

**Comment by driesvints** [comment]
Hi there, this is the expected behavior.

**Comment by khairy-pelcro** [comment]
Hey @driesvints 

But a different validaiton rule has different behavior than this for null values it skips the validation if the other value is null so what do you think?
