### ISSUE TITLE
withWhereHas with whereRaw does not correctly bind parameters.

### ISSUE THREAD

**Issue by joao-uefrom** [laravel/framework#43650]
- Laravel Version: 9.24.0
- PHP Version: 8.1.0
- Database Driver & Version: pgsql - v13.5

### Description:

If I use withWhereHas with whereRaw in my model, the query builder doesn't correctly bind the parameters.

In the example I show, it doesn't put the quotes in the permission name.

I put a repository with the migrations and seeds needed to run the bug.

Repository: https://github.com/joao-uefrom/laravel-bug-report

![Captura de tela 2022-08-10 230543](https://user-images.githubusercontent.com/48249229/184053045-f49f9bab-380a-4b5c-9026-33244e760923.png)
![Captura de tela 2022-08-10 230508](https://user-images.githubusercontent.com/48249229/184053050-8331ce29-f8de-40cd-9ace-e813138ac982.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
