### ISSUE TITLE
Blade component ignores provided error bag

### ISSUE THREAD

**Issue by Jacobs63** [laravel/framework#43656]
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version: N/A

### Description:
Whenever a Blade component is used in a Blade template, which had an error bag explicitly assigned, then any component used in such view will not have access to this error bag. Instead, the components will only access the error bag globally shared, by default via `\Illuminate\View\Middleware\ShareErrorsFromSession`.

Is this done on purpose?

### Steps To Reproduce:
1. Create a validator instance:
```php
$validator = \Validator::make([], ['test' => 'required'])
```
2. Create a blade component:
```html
<label class="form-field form-field--light {{ $labelClass }}" for="{{ $id }}">
    <input type="{{ $type }}"
           class="form-field__input {{ $errors->has($name) ? 'has-error' : '' }} {{ $value ? 'filled' : '' }} {{ $class }}" required
           name="{{ $name }}" value="{{ $value }}"
           id="{{ $id }}"
           {{ $attributes }}
    >
    <span class="form-field__label">{{ $label }}</span>
    @error($name)
    <span class="invalid-feedback">{{$message}}</span>
    @enderror
</label>
```
3. Create a blade view with a component:
```html
            <x-components::forms.input
                    label="Test"
                    type="text"
                    name="test"
                    id="test"
                    :value="old('test')"
            />
```

4. Validate input & render the Blade template:
```php
        if (! $validator->passes()) {
            return view('name')
                ->withErrors($validator)
                ->render();
        }
```
5. The blade component will not render the `has-error` class, nor will it render the `invalid-feedback` span - as the global error bag does not contain the errors passed to the component's owner view.

**Comment by driesvints** [comment]
Afaik, it's not meant to explicitly assign errors to a Blade component.
