### ISSUE TITLE
Impossible to translate null and bools on required_if rules

### ISSUE THREAD

**Issue by allanmcarvalho** [laravel/framework#43664]
- Laravel Version: 9.23.0
- PHP Version: 8.1.1
- Database Driver & Version: Mysql 5.7

### Description:

When I using the `required_if` rule it's impossible to translate the :value attribute from message because it is returned as a string in `getDisplayableValue` method from `FormatsMessages` trait (used in Validator class).

It's expected that this english word can be translated and I believe that using the same logic of translate :attributes we can translate this default :value or :values easily.

### Steps To Reproduce:

```php
/**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {

        return [
            'email' => 'nullable|email:dns|required_if:phone,null',
            'phone' => 'nullable|required_if:email,null',
        ];
    }
// we cannot translate the :value in:
//'required_if' => 'The :attribute field is required when :other is :value.',
```

**Comment by allanmcarvalho** [comment]
I tried to add a customValues with the method `setValueNames` from Validator, but this it's impossible with 'null' :value due it isn't accessible (I can't put a null as a key in an array) in array at 100th line of `FormatsMessages` trait.

**Comment by driesvints** [comment]
Right now, this isn't possible as this is a reserved word.

**Comment by allanmcarvalho** [comment]
What did you mean with your last message? I am a little confused because this is really boring for everyone that use Laravel in other language that is not English.
I can say truly, that every user of my system will not able to understand what's "O campo email é obrigatório quando o quando email é empty|true|false".

If the problem is that you have more "important" problems to solve instead this polish problems, tell me, and I try to propose a PR.

Thanks in advanced!

**Comment by allanmcarvalho** [comment]
I can't see the limitation of resolve this issue due the argument of "this is a reserved word".
I believe that is simple, for who translated, is displayed in the right way for that language... for who do nothing, continues like now!

**Comment by pjotrsavitski** [comment]
I'm surely late to the party, but one of the possibilities is to just use the custom message instead as documented [here](https://laravel.com/docs/11.x/validation#customizing-the-error-messages).
