### ISSUE TITLE
Command db:show doesn't handle unkown type exception properly

### ISSUE THREAD

**Issue by Slubby** [laravel/framework#43670]
- Laravel Version: 9.24.0
- PHP Version: 8.1.8
- Database Driver & Version: MySql 5.7.39

### Description:
When you run the commanf `php artisan db:show` and you have a table in your database with an enum column it will throw an exception. 
```php
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:418
```

### Steps To Reproduce:
1. Create a database with a table where one column is an enum type
2. Run the command `php artisan db:show`
3. See the exception

**Comment by jbrooksuk** [comment]
This was fixed in https://github.com/laravel/framework/pull/43635 and will be released shortly.

**Comment by Slubby** [comment]
O sorry didn't see that one
