### ISSUE TITLE
withSum is casting numeric aggregates to string values

### ISSUE THREAD

**Issue by robertmarney** [laravel/framework#43679]
- Laravel Version: 9.24.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 8.0

### Description:

When using withSum to load an aggregate from a relation, the aggregate returned natively is cast to a string value, even when the underlying field is a numeric type (decimal 13,4) in the db and cast to a numeric (e.g. float) type in the related class via the `casts` array.

Would hope the value respects the native type.

### Steps To Reproduce:

1. Create two classes, with the child relation containing a decimal/float column, in my case we have an `Order::class` and `OrderInvoice::class`, ensure the decimal/float column is cast on the child relation to a numeric type in the `casts` array.

2. Query with a `withSum` using the child relation and the numeric column, e.g.

```php

Order::with(['vendorBusiness:id,business_name'])->where(
            'project_id',
            $this->project->id
        )
            ->withSum('invoices as invoiced_costs', 'project_currency_subtotal')
            ->withSum('invoices', 'project_currency_subtotal');

```

3. See text values:

```php
[
...
"invoiced_costs" => "6345195829.10",
"invoices_sum_project_currency_subtotal" => "6345195829.10",
...
];
```

I noted that if I create a cast on the parent class (e.g. `Order::class` the cast will be applied, this is a manageable work around, but gets unwieldy.

1. Add the cast to `Order::class`

```php

 protected $casts = [
       ...
        'invoiced_costs' => 'float',
    ];

```

returns a result of:

```php
[
...
"invoiced_costs" => 6345195829.1,
"invoices_sum_project_currency_subtotal" => "6345195829.10",
...
];
```
Note the value where we have defined the cast is the expected type, the use of an alias in the withSum definition does not impact the native casting behaviour.

**Comment by driesvints** [comment]
This is expected. It's necessary to apply the proper cast.

**Comment by robertmarney** [comment]
@driesvints - respectfully I do not believe that the coercing of native numeric types to string in a mathematical aggregate function is expected behavior. This is compounded by the fact that you cannot use `->withCasts()` on the collection.

e.g.

```php
Order::with(['vendorBusiness:id,business_name'])->where(
            'project_id',
            $this->project->id
        )
            ->withSum('invoices as invoiced_costs', 'project_currency_subtotal')
            ->withSum('invoices', 'project_currency_subtotal')
            ->withCasts(['invoices_sum_project_currency_subtotal' => 'float']);
```

**Comment by acirinelli** [comment]
> robertmarney

Did you ever find a good solution?

**Comment by acirinelli** [comment]
> @driesvints - respectfully I do not believe that the coercing of native numeric types to string in a mathematical aggregate function is expected behavior. This is compounded by the fact that you cannot use `->withCasts()` on the collection.
> 
> e.g.
> 
> ```
> Order::with(['vendorBusiness:id,business_name'])->where(
>             'project_id',
>             $this->project->id
>         )
>             ->withSum('invoices as invoiced_costs', 'project_currency_subtotal')
>             ->withSum('invoices', 'project_currency_subtotal')
>             ->withCasts(['invoices_sum_project_currency_subtotal' => 'float']);
> ```

Did you ever find a good solution?

**Comment by robertmarney** [comment]
> > @driesvints - respectfully I do not believe that the coercing of native numeric types to string in a mathematical aggregate function is expected behavior. This is compounded by the fact that you cannot use `->withCasts()` on the collection.
> > e.g.
> > ```
> > Order::with(['vendorBusiness:id,business_name'])->where(
> >             'project_id',
> >             $this->project->id
> >         )
> >             ->withSum('invoices as invoiced_costs', 'project_currency_subtotal')
> >             ->withSum('invoices', 'project_currency_subtotal')
> >             ->withCasts(['invoices_sum_project_currency_subtotal' => 'float']);
> > ```
> 
> Did you ever find a good solution?

Not an ideal one, but a workaround was to transform the data and add additional casts once it is in a collection before sending it out the door.

e.g.

```php

return $orders->transform(function (Order $order) {
            $order->mergeCasts(['invoices_costs' => 'float']);
 //...
           return $order;
}));

```
