### ISSUE TITLE
Translator throwing TypeError with nested arrays in replacements

### ISSUE THREAD

**Issue by lucasjose501** [laravel/framework#43672]
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Database Driver & Version: mariadb 10.3.34

### Description:
Not sure if this is exactly a bug or just an edge case, but when using translation with an nested array in the replacements it will throw an TypeError `mb_substr(): Argument #1 ($string) must be of type string, array given` caused by `Str::substr'.

The action is called in this foreach: https://github.com/laravel/framework/blob/fdf3ae9760729652673359d3e2cced727ba25b92/src/Illuminate/Translation/Translator.php#L226

I know that I should not put an nested array there (and there are ways to prevent it), but I though that would be a good idea to report here. 

### Steps To Reproduce:
1. New laravel project
2. Create file 'messages.php' inside 'lang/en' folder.
3. Populate it with: 
```
    return [
        'welcome' => 'Welcome, :name',
    ];
```
4. Inside any blade or controller use: `{{ __('messages.welcome', ['name' => 'Lucas', 'something' => ['foo', 'bar']]) }}`

### Fix? (Not really)

To test and avoid it, I put one check inside the foreach in the `makeReplacements` function like this `if (is_array($value)) continue;` just to ignore if the replacement is an array, and that "fixed" the behavior, but I know it is not the best option.

### Why?

As I said, it is an edge case. I'm populating some translations dynamically and sometimes the array returned will have nested arrays. I can prevent it filtering to remove the array before populating the function arguments.

Thank you and I'm sorry for any inconvenience.

**Comment by driesvints** [comment]
>  I can prevent it filtering to remove the array before populating the function arguments.

I think this is best.
