### ISSUE TITLE
dbal enum problem on artisan db:show

### ISSUE THREAD

**Issue by estagent** [laravel/framework#43684]
- Laravel Version: 9.24
- PHP Version: 8.1
- Percona-server  Myql 8

### Description:

**artisan db:show**  

In AbstractPlatform.php line 418:
                                                                                                     
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it

DBAL ENUM PROBLEM

exception is thrown only/when database has any Enum field defined.

**Comment by jbrooksuk** [comment]
This is already fixed and will be available in the next release.
