### ISSUE TITLE
Does eloquent require pivot models to have a unique non-composite id?

### ISSUE THREAD

**Issue by EugeneErg1** [laravel/framework#43691]
The [documentation page](https://laravel.com/docs/9.x/eloquent#composite-primary-keys) has the following requirement: 

_Eloquent requires each model to have at least one uniquely identifying "ID" that can serve as its primary key. "Composite" primary keys are not supported by Eloquent models. However, you are free to add additional multi-column, unique indexes to your database tables in addition to the table's uniquely identifying primary key._

Does this requirement apply to the **Pivot** models?

**Comment by rodrigopedra** [comment]
The [documentation page](https://laravel.com/docs/9.x/contributions#support-questions) also states the following:

> Laravel's GitHub issue trackers are not intended to provide Laravel help or support. Instead, use one of the following channels

For not letting you without an answer, the requirement aforementioned does not apply to pivot models. You cans see below it handles the *expected* composite key:

https://github.com/laravel/framework/blob/1814e8066a6ba658ad42a662de9d3263b9637f9c/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php#L86-L116

By *expected* I mean the foreign keys to a pivot related to two tables. If you have a pivot related to more tables, or if you will need to manipulate custom fields on the pivot by retrieving pivot models directly, I would consider adding a dedicated primary key.

Just don't forget to set its `$incrementing` property back to `true` if you are using an incrementing ID.

Next time, please use one of the support channels listed on the docs for this kind of questions. Thanks!
