### ISSUE TITLE
Session Driver Cookie Middleware Ordering Issue

### ISSUE THREAD

**Issue by pascal-hauser** [laravel/framework#43693]
I had an issue that Session Driver `cookie` was not working due to the re-ordering of the middleware as defined in `Kernel.php` as `$middlewarePriority`.

The cookie driver requires the `AddQueuedCookiesToResponse` middleware. It is also required that this middleware is before the `StartSession` middleware, as the `AddQueuedCookiesToResponse` writes the cookies that are queued up by `StartSession` to the response as post processing.
Now in my case mutiple middleware groups were merged together and the priority ordering re-ordered the middlewares to have first the `StartSession` and afterwards the `AddQueuedCookiesToResponse`, causing the session data not be sent back as a cookie.

Can `\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,` be added to `Illuminate\Foundation\Http\Kernel.php` to ensure the ordering is always correct?

**Comment by driesvints** [comment]
Is this a feature request? Because the issue template is missing. If so, feel free to attempt a PR.
