### ISSUE TITLE
Artisan’s `db:show`, `db:table` & `model:show` don’t work with MySQL Spatial types

### ISSUE THREAD

**Issue by miclf** [laravel/framework#43697]
- Laravel Version: 9.24.0
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 5.7.36

### Description:

If a given MySQL table has at least one column using a spatial type (e.g. `point`, `linestring`), a `Doctrine\DBAL\Exception` is thrown when running Artisan’s `db:show`, `db:table` (for the given table) or `model:show` (for the Eloquent model associated to the table) commands.

For a `point` column, the exception message will be:

> Unknown database type point requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

Spatial types have been officially supported in Laravel migrations (`point()`, `lineString()`,…) for a while. As I understand it, Doctrine’s DBAL allows to write mappings for custom column types. It would be nice to have support for spatial types, otherwise the new Artisan commands stop to be usable as soon as a single column in a table uses one of these types.

### Steps To Reproduce:

- Create a vanilla Laravel project
- Make a migration for a new table, and a related Eloquent model.
- In the migration, add a column using any spatial type.
- Try to run any of the three Artisan commands this issue is about.

Relevant commit on a demo repository: [example app](https://github.com/miclf/example-app/commit/cd40950f4d1d5bad1f5b7c6ca37a538595ae65b6)

**Comment by MarienMupenda** [comment]
I am facing the same issue with `php artphp artisan db:show` as i use `enum` on my migrations             `$table->enum('status', [...])->default('pending')`;

- Laravel Version: 9.24.0
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 5.7.33

```
   Doctrine\DBAL\Exception 

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Platforms\AbstractPlatform.php:418
    414▕
    415▕         $dbType = strtolower($dbType);
    416▕
    417▕         if (! isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 418▕             throw new Exception(
    419▕                 'Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.'
    420▕             );
    421▕         }
    422▕

  1   D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Schema\MySQLSchemaManager.php:178
      Doctrine\DBAL\Platforms\AbstractPlatform::getDoctrineTypeMapping("enum")

  2   D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Schema\AbstractSchemaManager.php:1351
      Doctrine\DBAL\Schema\MySQLSchemaManager::_getPortableTableColumnDefinition()isan db:show

   Doctrine\DBAL\Exception 

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Platforms\AbstractPlatform.php:418
    414▕
    415▕         $dbType = strtolower($dbType);
    416▕
    417▕         if (! isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 418▕             throw new Exception(
    419▕                 'Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.'
    420▕             );
    421▕         }
    422▕

  1   D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Schema\MySQLSchemaManager.php:178
      Doctrine\DBAL\Platforms\AbstractPlatform::getDoctrineTypeMapping("enum")

  2   D:\Projets\Lab\Laravel\Lipa\vendor\doctrine\dbal\src\Schema\AbstractSchemaManager.php:1351
      Doctrine\DBAL\Schema\MySQLSchemaManager::_getPortableTableColumnDefinition()
```

**Comment by miclf** [comment]
@MarienMupenda Good catch 👍  I guess it throws an exception for any column type that is not strictly “standard” SQL.

**Comment by jbrooksuk** [comment]
This is fixed but has not yet been released.

**Comment by miclf** [comment]
@jbrooksuk Thanks! Curious to see what approach you guys decided to take to fix this :)
