### ISSUE TITLE
Null compatibility broken

### ISSUE THREAD

**Issue by ASYOU99** [laravel/framework#43704]
- Laravel Version: 8.83.23
- PHP Version: 8.0.10
- Database Driver & Version:
MySql 8
### Description:
When we use a cast of type 'object', 'collection' and we have the original value null, we get an error when trying to decode json.
This change appeared in the PR and is still relevant even for version 9.
[PR](https://github.com/laravel/framework/pull/42793/files#diff-59d24f1a8f0dd1e51ee7dffc8778133711634e928ecef4a91b63fc3851cb1579)
We get the warning 

> PHP Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
