### ISSUE TITLE
HTTP Client Post - Multipart with multidimensional array body

### ISSUE THREAD

**Issue by codoffer** [laravel/framework#43710]
- Laravel Version: 9.27,
- PHP Version: 8.1.7
- Database Driver & Version: MySQL

### Description:

I am getting errors with attaching a file and body with the multi-dimensional array.  I want to send multi-dimensional array with attachments files (with attachment field).

Same issue was opened before but closed without solution.

https://github.com/laravel/framework/issues/37174

### Steps To Reproduce:

**NOT WORKING**

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\File;

$path = storage_path('file.txt');

```
Http::acceptJson()
    ->attach('attachments[]', File::get($path), File::basename($path))
    ->post($destination, [
        'name' => 'John Smith',
        'providers' => [1,2,3]
]);
```

with throw InvalidArgumentException with message 'A 'contents' key is required'
whereas will be just fine

**WORKING**

```
Http::acceptJson()
    ->attach('attachments[]', File::get($path), File::basename($path))
    ->post($destination, [
        'name' => 'John Smith',
        'providers' => '1'
]);
```

**Comment by driesvints** [comment]
You're trying to post an array (`providers`) in a multipart HTTP request. That doesn't work. You're not sending JSON here but file parts.

**Comment by codoffer** [comment]
I have tried without JSON also. But it's not accepting.

**Comment by driesvints** [comment]
You can't send files over JSON. You need multipart for that.

**Comment by codoffer** [comment]
I want to send 

{
  "reply": {
    "body": "string",
  },
  "attachments": [
    "string"
  ]
}

attachments must upload the entire payload as `multipart/form-data` content-type and want to specify each parameter as form-data together with `attachments[]` as files.

I am not sure, How to handle this.

**Comment by virkse** [comment]
You need to send it like

`Http::acceptJson()
    ->attach('attachments[]', File::get($path), File::basename($path))
    ->post($destination, [
        [
            'name' => "first_name",
            "content" => "John Smith"
        ],
        [
            'name' => "providers",
            "content" => 1,
        ],
        [
            'name' => "providers",
            "content" => 2,
        ],
        [
            'name' => "providers",
            "content" => 3,
        ],
]);`

Breakdown your providers with multiple arrays
