### ISSUE TITLE
inability to catch ModelNotFoundException

### ISSUE THREAD

**Issue by silenseram** [laravel/framework#43713]
- Laravel Version: 9.24
- PHP Version: 8.0.1
- Database Driver & Version: not DB related

### Description:
Illuminate\Foundation\Exceptions\Handler::prepareException for some reason replaces ModelNotFoundException to NotFoundHttpException (wich is 2 different types of exceptions) that's makes impossible to register it through "renderable" method in exception handler 

### Steps To Reproduce:
Write code like that in exception handler "register" method:
```
        $this->renderable(function (ModelNotFoundException $exception, $request) {
            return \Response::json([
                'error' => 'Record not found'
            ], 404);
        });

        $this->renderable(function (NotFoundHttpException $e, Request $request) {
            return \Response::json([
                'error' => 'Route not found',
            ], 404);
        });
```
then we expect to get "Record not found" on ModelNotFoundException and on NotFoundHttpException - "Route not found", instead of this we get "Route not found" on both exceptions

**Comment by driesvints** [comment]
This is expected. `ModelNotFoundException` is part of a list of reserved exceptions that are converted specific HttpExceptions.

**Comment by szekeresa** [comment]
```
        $this->renderable(function (NotFoundHttpException $e, $request) {
            if ($e->getPrevious() instanceof ModelNotFoundException) {
                return \Response::json(['error' => 'Record not found'], 404);
            } else {
                return \Response::json(['error' => 'Route not found'], 404);
            }
        });
```
