### ISSUE TITLE
Value translation in validation does not support dot notation

### ISSUE THREAD

**Issue by Yinci** [laravel/framework#43717]
### Versions:
- Laravel Version: 8.83.10
- PHP Version: 8.0.18
- Database Driver & Version: MySQL 5.7.32

### Description:
When validating rules such as `required_if`, the `:value` will not be translated as described in the [docs](https://laravel.com/docs/8.x/validation#specifying-values-in-language-files) when the `:other` attribute contains dots.

### Steps To Reproduce:
Create simple HTML:

```html
<input type="radio" value="image" name="media[type]" id="type-image">
<label for="type-image">Foto</label>
<input type="radio" value="video" name="media[type]" id="type-video">
<label for="type-video">Video<label>

<input type="text" name="media[image]">
<input type="text" name="media[video]">
```

Set up your validation:
```php
class MediaFormRequest extends FormRequest
{
     public function rules()
    {
        return [ 
            'media.type' => ['required', 'in:image,video'],
            'media.image' => ['nullable', 'required_if:media.type,image'],
            'media.video' => ['nullable', 'required_if:media.type,video'],
       ];
    }
}
```

Validation lang file:
```php
'required_if' => ':Attribute is verplicht indien :other gelijk is aan :value.',

'attributes' => [
    'media.type' => 'media type',
    'media.image' => 'foto',
    'media.video' => 'video',
],

'values' => [
    'media.type. => [
        'image' => 'foto',
        'video' => 'video',
    ],
],
```

#### Results:
In the case you select "foto" with value "image", the expected result is:
"Foto is verplicht indien media type gelijk is aan foto."

However, the _actual result_ is:
"Foto is verplicht indien media type gelijk is aan image."

When I change the name to `media_type`, then it works as expected. Perhaps the code is literally translating the key? 
E.g. `return __("validation.values.{$attribute}.{$value}");` instead of
```php
$values = __('validation.attributes');
if (is_array($values) {
    return Arr::get(Arr::get($values, $attribute), $value);
}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by Yinci** [comment]
Hey @driesvints,

Upgrading to L9 is not an option at this point. However, I've decided to look at the source code and it seems that the code is indeed literally translating the value.

The value is translated in [`Illuminate/Validation/Concerns/FormatMessages@427`](https://github.com/laravel/framework/blob/423915f552367213ec7c014c03c4d7df9fc6fab2/src/Illuminate/Validation/Concerns/FormatsMessages.php#L427). You can see on L433 - L435 that the key is translated in a literal form, compared to attributes that get translated at line 295 using the following code: `Arr::get($this->translator->get('validation.attributes'), $name);`.

I would open a PR but I have no knowledge on how to. Any chance you or someone on the team could have a look at it?
