### ISSUE TITLE
model:show and db:show commands are broken

### ISSUE THREAD

**Issue by Sergiobop** [laravel/framework#43726]
- Laravel Version: 9.25.0
- PHP Version: 8.1

### Description:
The command is not working after update to 9.25 since @taylorotwell changed the method name in this commit: https://github.com/laravel/framework/commit/8ec9ede5eb3af7c4463bd05b48badbe41c3983d5
registerTypeMapping to registerTypeMappings, and in the ShowModelCommand is not changed:

` Method Illuminate\Foundation\Console\ShowModelCommand::registerTypeMapping does not exist. ` (exist with one s at the end)

This makes the db:show command fail too.

**Comment by taylorotwell** [comment]
Fixed.
