### ISSUE TITLE
Serialization fails for typed custom Eloquent Collections that are empty

### ISSUE THREAD

**Issue by hxnk** [laravel/framework#43732]
- Laravel Version: 9.25.1
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 8.0.27

### Description:

When queueing a job that has a **custom** Eloquent Collection as a typed property, and it holds an empty collection, (un)serializing fails with a Type Error, since it tries to assign the base Eloquent Collection to the property:

```php
class SomeJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public OrderCollection $orders;

    public function __construct(OrderCollection $orders)
    {
        $this->orders = $orders;
    }

    public function handle()
    {
        //
    }
}

$job = new SomeJob(new OrderCollection());

$serialized = serialize($job)

unserialize($serialized)

```

Result:

`TypeError : Cannot assign Illuminate\Database\Eloquent\Collection to property SomeJob::$orders of type App\Eloquent\OrderCollection`

### Steps To Reproduce:

I've added a failing test to prove the bug is there:
https://github.com/hxnk/framework/commit/ac6ed8ba058ae007c73e352c332fd4fb1070c1df

**Comment by driesvints** [comment]
Thanks, I confirmed this and sent in a fix.
