### ISSUE TITLE
When SERVER_PORT is changed in .env and server restarts, old port is used instead

### ISSUE THREAD

**Issue by shaedrich** [laravel/framework#43739]
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:
When I change `SERVER_PORT` in my .env, the change is correctly detected as with any other environment variable. However, when the server restarts, it still starts with the old port.

### Steps To Reproduce:
1. Add `SERVER_PORT=11111` to your .env
2. Run `php artisan serve`
> Starting Laravel development server: http://127.0.0.1:11111
[Wed Aug 17 15:06:37 2022] PHP 8.1.5 Development Server (http://127.0.0.1:11111) started
3. Change `SERVER_PORT` to `22222` in your .env
> Environment modified. Restarting server...
[Wed Aug 17 15:06:37 2022] PHP 8.1.5 Development Server (http://127.0.0.1:11111) started
4. Kill the running `php artisan serve` process by pressing <kbd>Ctrl</kbd> + <kbd>C</kbd> &rarr; Workaround
5. Run `php artisan serve` again
> Starting Laravel development server: http://127.0.0.1:22222
[Wed Aug 17 15:06:37 2022] PHP 8.1.5 Development Server (http://127.0.0.1:22222) started

**Comment by rcerljenko** [comment]
that's not a bug... env is read only once when artisan:serve starts and it's not re-read again until next (re)start

**Comment by driesvints** [comment]
@rcerljenko is correct. This doesn't changes anything for the current url that's served.

**Comment by shaedrich** [comment]
Then why do you restart the server in the first place? Isn't that completely pointless then?
