### ISSUE TITLE
Possible bug on model Accessors on new release

### ISSUE THREAD

**Issue by caiokawasaki** [laravel/framework#43735]
- Laravel Version: 9.25.1
- PHP Version: 8.1.8
- Database Driver & Version: mysql ('mysql/mysql-server:8.0')

### Description:
Today I ran `composer update` in my application, the Framework version got updated to `9.25.1`, the previous version was `9.23.0`.

This was working before on version `9.23.0`:

```php
public function totalValue(): Attribute
{
    $receivedMessages = $this->total_received_messages * $this->environment->singleReceivedMessageValue();
    $sentMessages = $this->total_sent_messages * $this->environment->singleSentMessageValue();

    return new Attribute(
        get: fn($value) => MoneyService::format(
            value: $receivedMessages + $sentMessages
        )
    );
}
```

I got this in the log after the update:

```
Call to a member function singleReceivedMessageValue() on null
```
I didn't understand why this was happening and it took me a while to find the problem.

However, if I change the accessor to the following everything works normally:

```php
public function totalValue(): Attribute
{
    return new Attribute(
        get: fn($value) => MoneyService::format(
            value: $this->total_received_messages * $this->environment->singleReceivedMessageValue() +
            $this->total_sent_messages * $this->environment->singleSentMessageValue()
        )
    );
}
```

On version `9.25.1` this accessor is not working, looks like the acessor can't access relations outside the `return new Attribute` function, is this right? Or is it a bug?

**Comment by morloderex** [comment]
@caiokawasaki What is the value of `$this->environment` if it is supposed to be a relation, then this would make a lot of sense. Sense the environment relation could potentially not be available at the time the totalValue needs to be computed.

**Comment by caiokawasaki** [comment]
@morloderex the relation is being eagger loadded, isn't it strange that I can access the relation only inside the Attribute function?

**Comment by taylorotwell** [comment]
I think we need more context here. Like a full route example that is broken.

**Comment by taylorotwell** [comment]
@driesvints pointed out this PR: https://github.com/laravel/framework/pull/43554

But, it's not clear to me atm how that PR would cause the behavior you describe.

**Comment by pintend** [comment]
I wonder if this is related https://github.com/laravel/framework/issues/42537 in my testing there is something funny going with with object caching

**Comment by ollieread** [comment]
@caiokawasaki could you dump your __WHOLE__ model in a gist, please?

**Comment by serpentblade** [comment]
> @serpentblade any ideas here? If we can't figure this one out it's probably best that we revert your PR.

My PR was related to casts.  The major change was the inclusion of the new casts cache to reduce repeated calls to cast type name conversions.  However, that's not to say it can't somehow be involved.

A stack trace for the error would be helpful to understand the full context of when the accessor is being called in the model's lifecycle.  There are a number of places where the accessor method is called and getting a full trace would help identify which path is the problem. 

IMO, the "working" code identified in the original post is the correct way to implement attribute accessors, as you want the evaluation of the accessor to occur when Attribute::get() is called and NOT when the Attribute accessor is first defined.

@caiokawasaki were any other packages besides updated at the same time?

**Comment by Tofandel** [comment]
I also fail to see how the casts PR would have any effect on this, I'm also enclined to say that it may be another package update, where is this `environment` property coming from?

**Comment by driesvints** [comment]
@caiokawasaki can you please provide a repo that reproduces this?

```bash
laravel new bug-report --github="--public"
```

**Comment by caiokawasaki** [comment]
Sorry for the delay, I ended up running out of internet in the last few days, I'll provide a repository with the problem described, in a few minutes I'll send the repository here.

**Comment by caiokawasaki** [comment]
[https://github.com/caiokawasaki/laravel-bug-report](https://github.com/caiokawasaki/laravel-bug-report)

I recreated the code in a new repository, added all the dependencies from the original project and still didn't get the problem, I'll dig deeper to try to find out what might be going on in my project.

**Comment by driesvints** [comment]
Feel free to provide a repo once you managed to recreate it 👍
