### ISSUE TITLE
route:list command gives wrong hyphenated variable name

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#43733]
- Laravel Version: 9.24.0
- PHP Version: 8.1.8
- Database Driver & Version: n/a

### Description:
When a resource route with a hyphenated name is defined the `route:list` command outputs an incorrect name for the variable.
For example, for a route of `Route::resource('brand-categories', BrandCategoryController::class)` the `route:list` command outputs: 

```
  GET|HEAD        brand-categories ................................................... brand-categories.index › BrandCategoryController@index
  POST            brand-categories ................................................... brand-categories.store › BrandCategoryController@store
  GET|HEAD        brand-categories/create .......................................... brand-categories.create › BrandCategoryController@create
  PUT|PATCH       brand-categories/{brand_category} ................................ brand-categories.update › BrandCategoryController@update
  DELETE          brand-categories/{brand_category} .............................. brand-categories.destroy › BrandCategoryController@destroy
  GET|HEAD        brand-categories/{brand_category}/edit ............................... brand-categories.edit › BrandCategoryController@edit
```

Note the variable `{brand_category}` - this is incorrect. The actual variable name registered is `{brand-categories}`, the same as the route's first segment. 

### Steps To Reproduce:

To reproduce, create a route as defined above and run `route:list`.
Now if you try to change the parameter name:

```php
Route::resource('brand-categories', BrandCategoryController::class)->parameters([
    'brand_category' => 'category'
]);
``` 

The variable should be updated and changed to `{cagegory}`, but it is not. To get it to work you have to use:

```php
Route::resource('brand-categories', BrandCategoryController::class)->parameters([
    'brand-categories' => 'category'
]);
``` 

As `route:list` gives the wrong name, debugging the issue can take a lot of guesswork and time to work out.

**Comment by aryan-arabshahi** [comment]
Based on the Laravel documentation, to change the resource parameter name you must pass the "resource name" and the "parameter name" as key/value pair. Check the link [here](https://laravel.com/docs/9.x/controllers#restful-naming-resource-route-parameters).

**Comment by tobz-nz** [comment]
@aryan-arabshahi yes that's correct - I'm saying the `route:list` command gives the wrong variable name in its output.
... ah I see what you mean. The variable name is correct, its just confusing as to what the resource value should be.

The docs say its a "singularized" version of the resource name, which is not the case when there is a hyphen. The resource name for `brand-categories` should be `brand-category` but it isn't. 
I think that's what confused me so much - the docs saying to use `brand-category` but that not working.

Perhaps just an update to the docs might clear things up somewhat?

**Comment by driesvints** [comment]
Feel free to attempt a PR to the docs, thanks.
