### ISSUE TITLE
Relation::getEager() returns an array, but is typed as a collection

### ISSUE THREAD

**Issue by ollieread** [laravel/framework#43752]
- Laravel Version: 9.x
- PHP Version: 8.1

### Description:
While working on #43746 I broke several unit tests and in the process of trying to fix them, discovered that it was because the method `Relation::getEager()` returns an `array`, and I was treating it as a `Collection`.

### Steps To Reproduce:
Dump out `get_debug_type($relation->getEager())`.

**Comment by driesvints** [comment]
I'm not sure that should be possible in a real-life app. If there's something wrong with mocking in the tests then we'd appreciate it if you could send in a PR, thanks.
