### ISSUE TITLE
Migration startingValue for exisitng table doesnt work

### ISSUE THREAD

**Issue by codetestmg** [laravel/framework#43762]
- Laravel Version: 9.19
- PHP Version:8.1.6
- Database Driver & Version:  10.4.24-MariaDB - mariadb.org binary distribution

### Description:
`$table->id()->startingValue(50)->change();`
modifying the existing table doesn't work. it inserts default increment ids 1,2,3,...... Only if fresh migration runs then it works.
any workaround for this

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
