### ISSUE TITLE
Invalid callable parameter return type of method `\Illuminate\Support\Collection::transform()`

### ISSUE THREAD

**Issue by Jacobs63** [laravel/framework#43773]
- Laravel Version: 9.25.1
- PHP Version: 8.1.7
- LaraStan Version: 2.1.12
- Database Driver & Version: N/A

### Description:
`\Illuminate\Support\Collection::transform()` has an invalid callable return type. The callable can return anything, as such the return type should be similar to `\Illuminate\Support\Collection::map()` - returning a templated value, such as `TTransformValue`.
This causes false errors when using static analysis tools such as LaraStan.

### Steps To Reproduce:
1. Create a collection containing items:
```php
        $collection = collect(['a', 'b']);
```
2. Transform these items, purposely returning a type different from the `$value` type:
```php
        $collection->transform(static fn (string $value, int $key): int => 1);
```
3. Static analysis understands the callback's return type as invalid, due to invalid PHPDOC:
```php
Parameter #1 $callback of method Illuminate\Support\Collection<int,string>::transform() expects callable(string, int): string, Closure(string, int): 1 given.
```

**Comment by driesvints** [comment]
This isn't a bug. If you want to adjust something to a DocBlock we're welcoming PR's.
