### ISSUE TITLE
Prohibited Validation rule fails on empty array

### ISSUE THREAD

**Issue by Grldk** [laravel/framework#43776]
- Laravel Version: 9.25.1
- PHP Version: 8.1.6
- Database Driver & Version: N/A

### Description:

```
$v = Validator::make(['test' => []], ['test' => 'prohibited']);
$v->fails();
```
This returns `true`. 

Docs for this validation rule say: 

> The field under validation must be empty or not present.

So I expected this to pass. (Array is empty after all). Not sure if this is a bug or incomplete docs?

**Comment by driesvints** [comment]
I think this specifically was added for strings, not array but I do agree with the confusion here. Will talk it over with the team.

**Comment by SamuelMwangiW** [comment]
Similar result with `NULL`. 

```php
$v = \Illuminate\Support\Facades\Validator::make(['test' => NULL], ['test' => 'prohibited']);
$v->fails(); //true
```

```php
$v = \Illuminate\Support\Facades\Validator::make(['test' => ''], ['test' => 'prohibited']);
$v->fails(); // false
```

**Comment by driesvints** [comment]
@SamuelMwangiW that's expected actually. The key `test` is present. So I'd expect that to fail.

**Comment by driesvints** [comment]
I've sent in a PR to the docs to clarify that this rule only works with strings. Thanks

**Comment by proudust** [comment]
@driesvints It seems that the documentation corrected in laravel/docs#8150 has been reverted back to the incorrect description by laravel/docs@edf107be3918200984e2f5723c3e1137dbe6469d.
If the behavior has not changed due to an update, I believe it needs to be corrected again.

**Comment by driesvints** [comment]
Honestly it's been too long since I gave this any thought. If you feel the docs are incorrect feel free to attempt a PR 👍

**Comment by SamuelMwangiW** [comment]
@proudust I just tested with the latest version of the framework and validation no longer fails on an empty array or `NULL`.

Below is my test.

```PHP
use Illuminate\Support\Facades\Validator;

test('prohibited allows empty values',function (mixed $value){
    $v = Validator::make(['test' => $value], ['test' => 'prohibited']);

    expect($v->fails())->toBeFalse();
})->with([
    'null' => [null],
    'empty array' => [[]],
    'empty string' => [''],
    'empty collection' => [collect()],
]);
```
