### ISSUE TITLE
Migrating with schema file, but without migration files.

### ISSUE THREAD

**Issue by mikield** [laravel/framework#43775]
- Laravel Version: 8.86.16
- PHP Version: 8.1.8
- Database Driver & Version: PostgreSQL 14.3

#### Without migration files with a new database.
Using `artisan migrate` command will run schema import even if there is nothing to migrate.
Problem exists if I will squash all my migration files to schema and remove them from disk.

After releasing my application - first `migrate` call will import schema. But `migrations` table will be empty. (cause schema do not contains any data)
After the next release, if I call `migrate` - it will do the same, even if my database is already migrated from the last release.

The `Migrate` command is checking if any migration was run already before schema load.
https://github.com/laravel/framework/blob/6c87065b3e310f60079b724d88560c35b7487294/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L123-L125

But I propose to check if `migrations` table exits before loading schema.
Checking `migrations` table will mean that database is already populated with the schema file, even if there is no data in it.

### Steps To Reproduce:

1) Create some migration files and some fake seeder.
2) Run `php artisan migrate --seed && php artisan schema:dump`
3) Remove migration files.
4) Use `php artisan migration:fresh --seed` (as it was a fresh database)
5) Run `php artisan migrate`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by mikield** [comment]
Yes, Laravel 9 now has inserts in schema dump. That was fixed.
