### ISSUE TITLE
`model:show` seems to describe all tinyints as boolean

### ISSUE THREAD

**Issue by lupinitylabs** [laravel/framework#43786]
- Laravel Version: 9.25.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.28

### Description:

The `artisan model:show` command seems to list any `TINYINT` column as `boolean`.

### Steps To Reproduce:

Create a `sort` column with `$table->unsignedTinyInteger('sort');` and it will show up in `model:show` as `boolean unsigned`:

![grafik](https://user-images.githubusercontent.com/17774818/185719352-85ff351c-3946-4263-808d-6a8812b31517.png)

**Comment by lupinitylabs** [comment]
I am aware that internally, all booleans are tinyints on DB level, so I see why it's probably hard to discriminate between the two uses just by looking at the database types.

However, since there cannot be signed/unsigned booleans, so an unsigned flag could be one indicator that it's not intended as boolean. 

It is also bizarre that when explicitly casting the column to int, the command still lists a boolean type, along with the int cast:

![grafik](https://user-images.githubusercontent.com/17774818/185719805-82e5bc61-97b2-4cfd-ba99-c0e24703c6ce.png)

**Comment by lupinitylabs** [comment]
I think the most correct and straight-forward solution might be to always output the database type (tinyint) instead of boolean. Technically, this is always correct and no guesswork.

**Comment by driesvints** [comment]
We use DBAL to get the type so if it's wrong it's best to open an issue on their repo. We don't own the code to this.

**Comment by allanlaal** [comment]
isn't it linked to Laravel using tinyint(1) instead of boolean?
.. since in Ancient times MySQL didn't have bool: https://github.com/laravel/framework/issues/1202
