### ISSUE TITLE
Cannot access Illuminate\Http\Client\Response body in any queued listener

### ISSUE THREAD

**Issue by introwit** [laravel/framework#43807]
- Laravel Version: 9.25.1
- PHP Version: 8.1.1
- Database Driver & Version: mysql 8

### Description:

- If you have an event that has an object of `Illuminate\Http\Client\Response` as a property, you cannot access it in any queued listener that listens to that event.  

- For example, you make a request to some third party API and you fire of an event:

```php
$response = Http::post(...);

event(new OrderIdReceived($response));
```

- If you use a queued listener, and in the listener if you do `$event->response->json()`, it will result in a guzzle related error `TypeError: fseek(): Argument #1 ($stream) must be of type resource, int given`. 

- If you make the listener non-queued, it works fine. My assumption is that the serialisation isn't happening correctly. 

- This has been reported before as well #37959 , but was closed inappropriately. 

### Steps To Reproduce:

- Fire an HTTP request and create a queued listener that listens to the inbuilt `Illuminate\Http\Client\Events\ResponseReceived` event since it has the response as a property already, and in that listener just do `$event->response->json()`

**Comment by driesvints** [comment]
You can't serialize a streamed response. This can't possible work. You need to pass a non-streamed response or perform the HTTP call inside the listener.
