### ISSUE TITLE
Duplicate Mail

### ISSUE THREAD

**Issue by l0rb** [laravel/framework#43810]
- Laravel Version: 9.19.0
- PHP Version: 8.1.9
- Database Driver & Version: mysql

### Description:

Trying to send the same mailable instance multiple times sends it too often. It seems the `to` is extended each time. Not sure if it is relevant but I tested this using the sparkpost driver from vemcogroup.

### Steps To Reproduce:
```
$mailable = new someMailable();
Mail::to('mail@example.com', $mailable); // sends 1 email
Mail::to('mail@example.com', $mailable); // sends 2 emails
Mail::to('mail@example.com', $mailable); // sends 3 emails
// ... and so on for further calls
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
