### ISSUE TITLE
Having an issue when uploading filename with RLM

### ISSUE THREAD

**Issue by hsul4n** [laravel/framework#43822]
- Laravel Version: 8.83.23
- PHP Version: 8.1.9
- Database Driver & Version: MySQL

Getting `Corrupted path detected` when uploading a file that contains [right-to-left-mark](https://en.wikipedia.org/wiki/Right-to-left_mark) (RLM).

Here's an example for filename
```
Foo Bar - (Without RLM)
Foo‏ Bar - (With RLM)
```

Here's a the file which throws exception:
```
League\Flysystem\CorruptedPathDetected 
…/vendor/league/flysystem/src/CorruptedPathDetected.php15
```

I'am getting this with both *api* & *web* routes.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by hsul4n** [comment]
@driesvints I've test it on latest Laravel version (9.3.4) and also the issue still there.

**Comment by driesvints** [comment]
This seems like a flysystem issue and not a Laravel one.
