### ISSUE TITLE
Http client is not overwriting the content type header when attaching a file or even if you manually call another method

### ISSUE THREAD

**Issue by Erth0** [laravel/framework#43827]
- Laravel Version: 8.83.16
- PHP Version: 8.1.5
- Database Driver & Version: mysql

### Description:
I came across a strange issue with the http client where the `Content-Type` header is not being overwritten by any method which will be called after the first set. See examples below.

### Steps To Reproduce:
I have the base http client set to the below code example.
```php
Http::asJson()
    ->baseUrl('https://webhook.site/')
    ->attach('File', $fileContent, 'testing-file.png')
    ->post('a808f079-7df8-4492-b553-6fde48ce64aa')
``` 

I have set it that I want the content type to be `application/json` within the attach method though there is a method `asMultipart()` which is called and this should overwrite the previous `Content-Type` header, however this doesn't overwrite it instead uses the `application/json`.

This issue is as well even if you don't use the `attach` method but instead you overwrite it at a later stage for example:
```php
Http::asJson()
    ->baseUrl('https://webhook.site/')
    ->timeout(30)
    ->asMultipart()
    ->post('a808f079-7df8-4492-b553-6fde48ce64aa')
```
The above code will have the same issue expectation is the `Content-Type` to be set to `multipart/form-data` however it is still set to `application/json`.

> In another try of trying to fix the above issue I tried to set manually the headers with the `withHeaders` method and when I set the `Content-Type` to `multipart/form-data` It was appended instead of overwritten .

Not sure if that one is an issue or it is meant to be in that way just though to mention it.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
