### ISSUE TITLE
Call to undefined method `Symfony\Component\HttpFoundation\Response::statusText()` 

### ISSUE THREAD

**Issue by lptn** [laravel/framework#43825]
- Laravel Version: v9.26.0
- PHP Version: 8.1.9

### Description:

This happens on testing 404 responses
```php
$response = $this->get('images/not_exist.jpg');
$response->assertNotFound();
```

Issue introduced in v9.26.0, on v9.25.1 and previous versions it worked without any issues. Namely, this commit https://github.com/laravel/framework/commit/1ae8ffda89c550b08b920e87c5dffe49ba4be141

**Comment by driesvints** [comment]
Thanks. We reverted this one.
