### ISSUE TITLE
OrderByRaw response different result when binding

### ISSUE THREAD

**Issue by J2TEAM** [laravel/framework#43830]
- Laravel Version: 8.83
- PHP Version: 8.0.0
- Database Driver & Version: MariaDB 10.3.35

### Description:
![image](https://user-images.githubusercontent.com/5250117/186239442-1b0a102e-e401-408d-8084-26b8d51b5b85.png)
The result is different when the array contains any number

### Steps To Reproduce:
Example code:

```php
$a = $query->clone()
    ->orderByRaw("field(location_code, ?) desc", $locations)
    ->get();

$b = $query->clone()
    ->orderByRaw("field(location_code,'".implode("','", $locations)."') desc")
    ->get();

dd($a->toArray(),$b->toArray());
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
