### ISSUE TITLE
URL Validation fails basic URL without a schema: www.google.com

### ISSUE THREAD

**Issue by gthedev** [laravel/framework#43840]
- Laravel Version: 9.23.0
- PHP Version: 8.1.6

### Description:
The `url` validation rule fails on a basic URL starting with www (without specifying the schema), e.g. `www.google.com`

### Steps To Reproduce:
```
>>> Validator::validate(['test' => 'www.google.com'], ['test' => 'url'])
Illuminate\Validation\ValidationException
```

**Comment by driesvints** [comment]
A valid url starts with a scheme.
