### ISSUE TITLE
Tags not cleaned up from Redis cache

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#43850]
- Laravel Version: 9.11.0
- PHP Version: 8.1.6

### Description:

When an item is saved into Redis cache with tags and an expiry (`Cache::tags(['one', 'two'])->put('key', 'value', 3600)`) the following happens:
 1. A value is saved under a generated key name with an expiry date: `laravel:6c017031f987fbd8828ea55044d67f6bb9dd6316:key` -> `s:5:"value";`
 2. A set of key names is saved under tag name without expiration: `laravel:6307213384953462982890:standard_ref` -> `[laravel:6c017031f987fbd8828ea55044d67f6bb9dd6316:key]`
 3. A generated string value is saved under tag name without expiration: `laravel:tag:one:key` -> `6307213384953462982890`

The value expires as it should, and Laravel handles it correctly. The problem are the other two keys which **don't** expire ever, because they do also take up space. This caused our production Redis to use more than a gigabyte of space in a week (just in stale tags alone, _without the values_) when we tried to use them to cache data on per-user basis.

Since Redis does not allow individual values in a set to have an expiry date, the [usual approach is to run a Lua script](https://github.com/stackify/redis-tagging-locking-sample/blob/master/src/RedisWithTaggingAndLocking/Scripts/CleanupTags.lua) to cleanup those tags manually. Laravel should introduce a command to run on a schedule that cleans up those leftover tag values.

### Steps To Reproduce:

1. Use `CACHE_DRIVER=redis`
2. Create tagged values that will expire shortly:
```php
Cache::tags(['one'])->put('key2', 'value', 2);
Cache::tags(['one', 'two'])->put('key1', 'value', 2)
```
3. After 2 seconds pass, execute `KEYS *` on your Redis and see the leftover tag keys (note the keys that hold the values are gone):
```
0)	laravel:tag:two:key
1)	laravel:tag:one:key
2)	laravel:6307238514508800660377:standard_ref
3)	laravel:63072380e1b1c629296883:standard_ref
```

**Comment by driesvints** [comment]
> Laravel should introduce a command to run on a schedule that cleans up those leftover tag values.

I think this is a good idea. Can you send in a PR? Thanks!

**Comment by oprypkhantc** [comment]
@driesvints Yep, doing that. Thanks for the response.

**Comment by oprypkhantc** [comment]
The package we ended up writing is this: https://github.com/tenantcloud/laravel-better-cache

It uses Redis' sorted sets with timestamp scores instead of sets to efficiently clean up expired tags, and it also improves performance by eliminating unneeded Redis calls for tagged cache gets/puts.

We've used it for a couple days and so far it's been working great for us. Memory usage reduced 3 times by almost 1GB just by getting rid of half a million tags.

Hope Laravel adopts this implementation.

**Comment by taylorotwell** [comment]
> Hope Laravel adopts this implementation.

@oprypkhantc can you PR that implementation to Laravel?

**Comment by oprypkhantc** [comment]
> > Hope Laravel adopts this implementation.
> 
> @oprypkhantc can you PR that implementation to Laravel?

@taylorotwell I can. My implementation isn't a 100% compatible, there are things in tags API that need to be changed - hence would require a breaking change. Almost every method exposed by `Cache::tags()->getTags()` isn't backwards-compatible. 

Also, any existing tagged data from cache would be inaccessible - because of the way tags & tagged data is stored has changed. Not only for `redis` driver, but all of the existing stores that support tags.

If all of this is ok, I'll proceed with a PR. Also, someone should look through the implementation beforehand so I don't lose time on this if there isn't a chance to get this merged.

**Comment by taylorotwell** [comment]
@oprypkhantc circling back to the flush command you originally PR'd since it would presumably be backwards compatible. What is the performance of that like in your experience? Maybe it would be a better option for us atm because of BC?

**Comment by oprypkhantc** [comment]
> @oprypkhantc circling back to the flush command you originally PR'd since it would presumably be backwards compatible. What is the performance of that like in your experience? Maybe it would be a better option for us atm because of BC?

The results from my local machine:
 - cleaning up 50k stale tags, deleting all as stale: new 0.2s, old 347s
 - cleaning up 50k stale tags, not touching any (all not stale): new 0.2s, old 6s
 - putting 50k tagged values in cache: new 18s, old 23s
 - getting 50k tagged values from cache: new 8s, old 16s

For us the performance benefit was a deciding factor. Mind you the new implementation still requires a flush command to be ran regularly, but it's just incredibly fast.

Laravel 10 release is weeks away, there's definitely not enough time to get the whole thing ready for merge. The only way I can think of to merge this into 10.x is by changing the API of `Cache::tags()->getTags()` now, before the release, so that we can avoid a BC down the road. Of course that assumes that inaccessible cached data is not considered a BC.

**Comment by oprypkhantc** [comment]
The LUA approach is definitely more performant, but it's simply unsafe to run it as it might end up locking Redis for way too long.

**Comment by taylorotwell** [comment]
@oprypkhantc I've managed to port over your solution into laravel/framework for the 10.x release, can you review it here and let me know your thoughts?

https://github.com/laravel/framework/pull/45690/files
