### ISSUE TITLE
Eloquent Model GetKey shouldn't return castable object

### ISSUE THREAD

**Issue by aliowacom** [laravel/framework#43864]
- Laravel Version: 9.19
- PHP Version: 8.1.4
- Database Driver & Version: MySql

### Description:
Model's `getKey()` method returns primary key attribute. There are multiple places where `getKey()` is expected to be a string, but `getAttribute()` could actually return a castable class.

If casted object is returned, `getKeyForSelectQuery()` would return it as well and `setKeysForSelectQuery()` would end up like `where id = {}`

### Steps To Reproduce:
Dirty way, would throw `Object of class App\Http\Controllers\UserId could not be converted to string`

```
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class UserId
{
    public function __construct(private readonly string $uuid)
    {}

    public function value(): string
    {
        return $this->uuid;
    }
}
class User extends Model
{
    public $incrementing = false;
    protected $keyType = 'string';
    protected $fillable = ['id'];
    
    public function id(): Attribute
    {
        return new Attribute(
            get: fn ($value, $attributes) => new UserId($value),
            set: fn ($value) => ['id' => $value->value()],
        );
    }
}

$model = new User();
$model->id = new UserId('25ebacb2-552c-4553-89d1-c4850f851552');
$model->exists = true;

$model->save();
```

**Comment by rodrigopedra** [comment]
From the docs:

> Eloquent will also assume that each model's corresponding database table has a primary key column named `id`.  If necessary, you may define a protected `$primaryKey` property on your model to specify a different column that serves as your model's primary key
>
> In addition, Eloquent assumes that the primary key is an incrementing integer value, which means that Eloquent will automatically cast the primary key to an integer. If you wish to use a non-incrementing or a non-numeric primary key you must define a public `$incrementing` property on your model that is set to `false`
> 
> If your model's primary key is not an integer, you should define a protected `$keyType` property on your model. This property should have a value of `string`

reference: https://laravel.com/docs/9.x/eloquent#primary-keys

In other words, an Eloquent model primary key should be either an integer value or a string value. Objects of any types are not supported as a valid primary key for Eloquent Models.

If you believe this is a feature Laravel should add, you can either:

- Propose a PR
- Start a discussion, on the discussion session here at GitHub, as described in the docs

reference: https://laravel.com/docs/9.x/contributions#core-development-discussion

**Comment by aliowacom** [comment]
Updated example with `$keyType` and `$incrementing`, result is the same.
> In other words, an Eloquent model primary key should be either an integer value or a string value. Objects of any types are not supported as a valid primary key for Eloquent Models.

Exactly, this is what I'm saying, Eloquent tries to cast primary key to possible castable object if it exists when it shouldn't.

**Comment by driesvints** [comment]
What you try to do is simply not supported.

**Comment by kirkbushell** [comment]
> > Exactly, this is what I'm saying, Eloquent tries to cast primary key to possible castable object if it exists when it shouldn't.
> 
> Not actually, as the docs implies, Eloquent expects the developer will provide either an integer or a string value as the primary id, therefore it does not need to check for castable objects or any sort of objects.
> 
> By defining an accessor/mutator for your model's `id` property, you are breaking this deal. Is not Eloquent't job to ensure keys are either an integer or a string when using it, is your job to provide Eloquent an integer or a string as the model's primary key.
> 
> Eloquent will assume the developer is providing an scalar integer or string and will use it like this. Simple as that.
> 
> In your case, you can try to override the `getKey()` method in your model, doing the cast you need, to see if this solves your issue.
> 
> But be aware that if this solution works now, it is still a workaround that might break in the future, as using a Value Object as the primary key is a unexpected use case and the maintainers don't need to consider this personal use case of yours on future changes or enhancements.
> 
> As suggested, if you believe Laravel should support this use case, which is totally a new feature request and not a bug correction, either send a PR, or start a discussion as stated on the docs.

Although you're right, when it comes to writing applications that are less prone to simple mistakes, this is not exactly a great outcome of Laravel. I want to use value objects for my IDs, but Laravel won't let me (one of the few times I've actually found myself fighting Laravel!)

A problem here is that even the primary keys should respect casts of those same values, and if they need to be accessed as strings, Laravel should at least respect Stringable implementations (which my IDs are).
