### ISSUE TITLE
Artisan about - no composer version displayed when using composer.phar

### ISSUE THREAD

**Issue by MircoBabin** [laravel/framework#43878]
- Laravel Version: 9.26.1
- PHP Version: 8.1.7
- Database Driver & Version: MySql 8.0.16
- Windows/10 latest version

### Description:

The `artisan about` does not show the correct composer version when using `composer.phar`.

![image](https://user-images.githubusercontent.com/8981285/186911788-a2843b9c-a332-4fd1-93bd-e0e8949f213b.png)

### Steps To Reproduce:

- Have a composer.phar in the root of the project.
- Don't have composer installed otherwise.
- Execute `php artisan about`
- Observe there is no composer version displayed

**Comment by jbrooksuk** [comment]
Can you please provide us with the output of `php composer.phar -V`?

**Comment by MircoBabin** [comment]
The output of `php composer.phar -V`:

![image](https://user-images.githubusercontent.com/8981285/186915404-2147452f-612b-4f5a-b877-9cf1de39f710.png)

**Comment by nunomaduro** [comment]
Can you go to `Illuminate\Support\Composer` and die var_dump the variable "$command" on the line 118?

**Comment by MircoBabin** [comment]
`var_dump($command)`:

![image](https://user-images.githubusercontent.com/8981285/186923812-74f5d09b-fde2-44a7-8417-83c8bbee9225.png)

**Comment by MircoBabin** [comment]
L118: I also dumped current working directory
L124: I also `var_dump($output)` (which is empty and I guess the problem)

![image](https://user-images.githubusercontent.com/8981285/186926176-753dd73d-a6ec-41c4-83f5-3680a6cd421a.png)

**Comment by nunomaduro** [comment]
So, apparently, `d:\projects\bin\php-8.1.7-x64\php.exe` is not a valid binary, or your user don't have permissions to access it. You should be able to fix this issue by re-installing that PHP version, or fixing the permissions of that binary.

**Comment by MircoBabin** [comment]
That is an incorrect conclusion:

![image](https://user-images.githubusercontent.com/8981285/186926666-e3c8d14c-d300-46ea-bac7-231f9cfb9ac0.png)

**Comment by MircoBabin** [comment]
L124: I added `var_dump(['output' => $output, 'errorOutput' => $process->getErrorOutput()]);`

```
array(2) {
  ["output"]=>
  string(0) ""
  ["errorOutput"]=>
  string(134) "'"\"d:\projects\bin\php-8.1.7-x64\php.exe\""' is not recognized as an internal or external command,
operable program or batch file.
"
}
```

**Comment by MircoBabin** [comment]
So the problem is that the executable is wrongly escaped, because it is enclosed in " ".

I changed L84 to not escape the phpBinary() and then it works for me (on Windows).

2 Observations about my quick-and-dirty fix:
- I don't know if this handles spaces in the path correctly.
- I don't know if this will work on Unix.
- I noticed that vendor\symfony\process\Process.php - public function start(callable $callback = null, array $env = []) - $commandline is really wrong when passed in the wrong phpBinary() value.

```
    /**
     * Get the PHP binary.
     *
     * @return string
     */
    protected function phpBinary()
    {
        return strval((new PhpExecutableFinder)->find(false));    // MircoBabin - L84: changed to strval()
    }
```


![image](https://user-images.githubusercontent.com/8981285/186932088-23199eb1-70c0-417c-94a2-5a34939f374c.png)

**Comment by jbrooksuk** [comment]
@MircoBabin can you please try with https://github.com/laravel/framework/pull/43880

**Comment by MircoBabin** [comment]
After applying #43880 I can confirm it works. I even put "php.exe" in a path with spaces `d:\projects\bin\With Spaces php-8.1.7-x64\php.exe` and it still works.

To dump some settings I put some `var_dump` in:
1)  Composer.php - getVersion()

```php
    /**
     * Get the version of Composer.
     *
     * @return string|null
     */
    public function getVersion()
    {
        $command = array_merge($this->findComposer(), ['-V', '--no-ansi']);
        var_dump(['Composer.php L118 - $command' => $command, 'getcwd()' => getcwd(), '$this->workingPath' => $this->workingPath]);

        $process = $this->getProcess($command);

        $process->run();
        var_dump(['Composer.php L129 - $process->wait' => $process->wait()]);

        $output = $process->getOutput();
        var_dump(['Composer.php L131 - $output' => $output, 'errorOutput' => $process->getErrorOutput()]);

        if (preg_match('/(\d+(\.\d+){2})/', $output, $version)) {
            return $version[1];
        }

        return explode(' ', $output)[2] ?? null;
    }
```

2) vendor\symfony\process\Process.php - start()

```php
    /**
     * Starts the process and returns after writing the input to STDIN.
     *
     * This method blocks until all STDIN data is sent to the process then it
     * returns while the process runs in the background.
     *
     * The termination of the process can be awaited with wait().
     *
     * The callback receives the type of output (out or err) and some bytes from
     * the output in real-time while writing the standard input to the process.
     * It allows to have feedback from the independent process during execution.
     *
     * @param callable|null $callback A PHP callback to run whenever there is some
     *                                output available on STDOUT or STDERR
     *
     * @throws RuntimeException When process can't be launched
     * @throws RuntimeException When process is already running
     * @throws LogicException   In case a callback is provided and output has been disabled
     */
    public function start(callable $callback = null, array $env = [])
    {
...
        var_dump(['Process.php L347 - $commandline' => $commandline]);
        $this->process = @proc_open($commandline, $descriptors, $this->processPipes->pipes, $this->cwd, $envPairs, $this->options);
...
}
```

The output with both #43880 and my `var_dump` additions is:
```text
d:\Projects\Webpage\tripportals>php artisan about
array(3) {
  ["Composer.php L118 - $command"]=>
  array(4) {
    [0]=>
    string(49) "d:\projects\bin\With Spaces php-8.1.7-x64\php.exe"
    [1]=>
    string(13) "composer.phar"
    [2]=>
    string(2) "-V"
    [3]=>
    string(9) "--no-ansi"
  }
  ["getcwd()"]=>
  string(31) "D:\Projects\Webpage\tripportals"
  ["$this->workingPath"]=>
  string(31) "D:\Projects\Webpage\tripportals"
}
array(1) {
  ["Process.php - $commandline"]=>
  string(208) "cmd /V:ON /E:ON /D /C ("d:\projects\bin\With Spaces php-8.1.7-x64\php.exe" composer.phar -V --no-ansi) 1>"C:\Users\Mirco\AppData\Local\Temp\sf_proc_00.out" 2>"C:\Users\Mirco\AppData\Local\Temp\sf_proc_00.err""
}
array(1) {
  ["Composer.php L129 - $process->wait"]=>
  int(0)
}
array(2) {
  ["Composer.php L131 - $output"]=>
  string(44) "Composer version 2.2.9 2022-03-15 22:13:37
"
  ["errorOutput"]=>
  string(0) ""
}
```

![image](https://user-images.githubusercontent.com/8981285/187129847-502fede3-fc52-4240-abb3-c7f037bc00bd.png)

**My conclusion is that the PR works, even with a path with spaces in it.**

**Comment by driesvints** [comment]
It seems like we're not going to take action here right now, sorry.
