### ISSUE TITLE
AbstractCursorPaginator::getParametersForItem() ErrorException Undefined index When transforming items

### ISSUE THREAD

**Issue by HANKSIE** [laravel/framework#43871]
- Laravel Version: 8.83.23
- PHP Version: 7.3.17
- Database Driver & Version: SQLite

### Description:
When using AbstractCursorPaginator::through() to transform each item,  calling AbstractCursorPaginator::toJson() implicitly or obviously will give an error: `Undefined index`
Paginate and SimplePaginate don't have this problem.

This error occur in AbstractCursorPaginator::getParametersForItem() so the total number of pages for pagination needs to be greater than 1 when demonstrating. 

https://github.com/laravel/framework/blob/bdc707f8b9bcad289b24cd182d98ec7480ac4491/src/Illuminate/Pagination/AbstractCursorPaginator.php#L218

### Steps To Reproduce:
```php
$cursorPaginate = User::cursorPaginate($this->_perPage);
$cursorPaginate->through(function ($data) {
    return ['data' => $data, 'extra_field' => '...']; // Any key-value pair except original data
});
$cursorPaginate->toJson(); // ErrorException Undefined index: id ...
```

here is demo repository: https://github.com/HANKSIE/CursorPaginatorErrorDemo

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
