### ISSUE TITLE
Eloquent doesn't work well with orderByRaw and cursorPaginate

### ISSUE THREAD

**Issue by bency** [laravel/framework#43874]
If you use `orderByRaw` with cursorPaginate, you will receive an array_flip error exception
```
{
  "message": "array_flip(): Can only flip string and integer values, entry skipped",
  "exception": "ErrorException",
  "file": "/app/path/vendor/laravel/framework/src/Illuminate/Collections/Collection.php",
  "line": 408,
...
}
```

Following is my sample code
```
<?php
namespace App\Http\Controllers;

class TestController extends Controller
    public function test()
    {
        $posts = $tag ->posts()
            ->orderByRaw('`comments_count` * 0.5 + `likes_count` * 0.5 DESC')
            ->cursorPaginate();
        return $posts;
    }
```

1. The method `orderByRaw` create an array in the form of
```
[
    `type` => `Raw`,
    `sql` => `SOME ORDER_BY QUERY`
]
```
2. And it became `null` after `pluck` method at L413
```
^ array:1 [
    0 => null
]
```
3. Illuminate\Pagination\AbstractCursorPaginator::getParametersForItem needs to flip parameters which is `$orders` in `Illuminate/Database/Concerns/BuildsQueries.php#L413`

https://github.com/laravel/framework/blob/d23de5f9af1bd253a9d8b823cec9bf37987facf2/src/Illuminate/Database/Concerns/BuildsQueries.php#L413

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
