### ISSUE TITLE
After `route:cache`, `Route::current()->getPrefix()` returns route prefix without slash at the start.

### ISSUE THREAD

**Issue by JirakLu** [laravel/framework#43882]
- Laravel Version: 9.23.0
- PHP Version: 8.1.9
- Database Driver & Version: X

### Description:
After `route:cache`, `Route::current()->getPrefix()` returns the current route prefix without slash at the start.
I think it would be better to unify this and always return prefix without slash at the start.

## Not Cached
`Route::current()->getPrefix()` returns "/testPrefix";

## Cached
`Route::current()->getPrefix()` returns "testPrefix";

This only happens for grouped routes:
```php
// Broken, getPrefix() returns -> NOT CACHED: "/test" | CACHED: "test"
Route::prefix("/test")->group(function () {
    Route::view("/", "pages.test")->name("test");
});

// Broken, getPrefix() returns -> NOT CACHED: "/test" | CACHED: "test"
Route::group(["prefix" => "/test"], function () {
    Route::view("/", "pages.test")->name("test");
});

// Broken, getPrefix() returns -> NOT CACHED: "/test" | CACHED: "test"
Route::controller(TestController::class)->prefix("/test")->group(function () {
    Route::view("/", "pages.test")->name("test");
});

// Working as expected, getPrefix() returns -> NOT CACHED: "test" | CACHED: "test"
Route::view("/", "pages.test")->prefix("/test")->name("test");
```
I think the problem is in the `RouteGroup::formatPrefix()` method.

https://github.com/laravel/framework/blob/2a1a55caf3c65a74f173f47be594587cb931f22c/src/Illuminate/Routing/RouteGroup.php#L64-L73

Here if the old prefix isnt set it basically does this - `"" . "/" . "newPrefix"` ->  adds slash at the start because the old prefix is an empty string.

I managed to fixed the problem by adding ltrim to the return.
```php
$old = $old['prefix'] ?? '';

if ($prependExistingPrefix) {
    return ltrim(isset($new['prefix']) ? trim($old, '/').'/'.trim($new['prefix'], '/') : $old, '/');
} else {
    return isset($new['prefix']) ? trim($new['prefix'], '/').'/'.trim($old, '/') : $old;
}
```
If my understanding of the problem is correct, I would be happy to submit a PR to fix this.

#43376 # Steps To Reproduce:

**Comment by driesvints** [comment]
We should indeed fix this but the cached behavior should adopt to the non-cached behavior, not the other way around.

**Comment by JirakLu** [comment]
The problem is that the behavior differs even for not cached routes as i described here.
It depends if you use route group or not.

```php
// Broken, getPrefix() returns -> NOT CACHED: "/test" | CACHED: "test"
Route::group(["prefix" => "/test"], function () {
    Route::view("/", "pages.test")->name("test");
});

// Broken, getPrefix() returns -> NOT CACHED: "/test" | CACHED: "test"
Route::controller(TestController::class)->prefix("/test")->group(function () {
    Route::view("/", "pages.test")->name("test");
});

// Working as expected, getPrefix() returns -> NOT CACHED: "test" | CACHED: "test"
Route::view("/", "pages.test")->prefix("/test")->name("test");
```

**Comment by driesvints** [comment]
> `Route::view("/", "pages.test")->prefix("/test")->name("test");`

This isn't valid code. I don't think we document using prefixes like that on single routes anywhere.

**Comment by JirakLu** [comment]
Oh, my bad.
Then i guess the problem would be somewhere here.
https://github.com/laravel/framework/blob/45cd804928f4c1a42fafd2b78c7fa023a59c542a/src/Illuminate/Routing/Route.php#L804-L809
You are basically trimming the slash at the start from the `$newPrefix`.
I managed to fix it by replacing `trim` by `rtrim`.
```php
protected function updatePrefixOnAction($prefix)
{
    if (! empty($newPrefix = rtrim(rtrim($prefix, '/').'/'.ltrim($this->action['prefix'] ?? '', '/'), '/'))) {
        $this->action['prefix'] = $newPrefix;
    }
}
```
This works for me and the prefix is always returned with slash at the start. Cached or not cached.

**Comment by driesvints** [comment]
Can you try to send in a PR?

**Comment by JirakLu** [comment]
Done. Here is the PR: https://github.com/laravel/framework/pull/43932.

**Comment by JirakLu** [comment]
Ima close this issue for now. I will create a new one with proper explanation of the problem soon.
