### ISSUE TITLE
[9.x] Return data type of the `GeneratorCommand::handle()` method

### ISSUE THREAD

**Issue by imdhemy** [laravel/framework#43889]
Using `bool|null` as a return type from `GeneratorCommand::handle()` method is
a bit confusing. The returned value is used by Symfony command `run()` method 
that expects `1` for FAILURE and `0` for SUCCESS.

Here, In an _error case_, `false` is returned (_a failure status  `1`  is intended_), but a success 
status (`0`) is returned by Symfony command `run` method.

https://github.com/laravel/framework/blob/2a1a55caf3c65a74f173f47be594587cb931f22c/src/Illuminate/Console/GeneratorCommand.php#L149-L153

The same applies to the following code:

https://github.com/laravel/framework/blob/2a1a55caf3c65a74f173f47be594587cb931f22c/src/Illuminate/Console/GeneratorCommand.php#L162-L168

Note: This may exist in other commands, but I started with this one.

---

If my understanding is correct, I would be happy to submit a PR to fix this.

**Comment by driesvints** [comment]
I don't see anything wrong here.

**Comment by imdhemy** [comment]
@driesvints 
Could you please have a look at this test?

https://github.com/imdhemy/laravel.framework/blob/generator-command/tests/Console/GeneratorCommandTest.php#L39

This following assertion fails:
```php
$this->assertSame(Command::FAILURE, $sut->run($input, $output));

// Failed asserting that 0 is identical to 1.
```

**Comment by driesvints** [comment]
If you want to change anything feel free to send in a PR 👍
