### ISSUE TITLE
Laravel with hasMany(Trade::class, 'data->order_id', 'id') is empty

### ISSUE THREAD

**Issue by phpmac** [laravel/framework#43899]
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Version:

### Description:

when "with hasMany(not data->xx)" its ok,else  empty.

<img width="1004" alt="截屏2022-08-28 15 44 10" src="https://user-images.githubusercontent.com/86544347/187063769-eda3d835-08ec-45ee-a268-814e7daede42.png">
<img width="960" alt="截屏2022-08-28 15 44 00" src="https://user-images.githubusercontent.com/86544347/187063774-d666d705-b13e-4963-9d3c-de3b443cbdd4.png">
<img width="819" alt="截屏2022-08-28 15 43 49" src="https://user-images.githubusercontent.com/86544347/187063779-e8c01f18-5824-4782-b9c1-a7360f2c0dbc.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
