### ISSUE TITLE
Return response()->file() stored in Aws s3

### ISSUE THREAD

**Issue by davymaish** [laravel/framework#43907]
### Discussed in https://github.com/laravel/framework/discussions/43906

<div type='discussions-op-text'>

<sup>Originally posted by **davymaish** August 29, 2022</sup>
Thank you for the great framework.
I have been having a problem while returning file response from a controller.
Im getting this error;

The file "https://web.s3.eu-west-2.amazonaws.com/...." does not exist 

If I open the url in its own tab, the image is dislpayed. As per my code, its a must i return the file as a response()->file() without downloading or streaming.

My partial code is as below

`$url = Storage::disk('s3)->temporaryUrl(
                $file->file_path.$file->name, now()->addMinutes(5)
            );
            return response()->file($url);`

I would appreciate your response and assistance. Thank you.
</div>

**Comment by driesvints** [comment]
Please don't move discussions back to issues.

**Comment by davymaish** [comment]
Just help, don't discriminate my issue
