### ISSUE TITLE
vite not found at after deploying

### ISSUE THREAD

**Issue by mrinvo** [laravel/framework#43903]
After deploying my laravel 9 project in 2 different hosts , i have faced the same issue regarding vite .
vite not found at .
knowing that i have run both of npm install and npm run dev before deploying 
and regarding running the commands (npm install , npm run dev ) on the host  , i am face the issue which is shared hosting does not provide node easily so on two different hosts i couldn't run my project .
are there any solutions for my issue ?

**Comment by timacdonald** [comment]
You should not be running `npm run dev` on deploy. You should run `npm run build`.

If you are unable to run `npm` commands on your shared hosting, you should run `npm run build` locally and commit  the assets in the `public/build` directory.

**Comment by mrinvo** [comment]
that's exactly what i have done
i ran npm run build locally and committed the changes but still I'm getting
the same error

**Comment by timacdonald** [comment]
Can you provide the stacktrace or a screenshot? Will need more information to provide context.
