### ISSUE TITLE
Internal server error with large json file uploads

### ISSUE THREAD

**Issue by wjonkerhulst** [laravel/framework#43931]
- Laravel Version: 9.26.1
- PHP Version: 8.1.9
- Database Driver & Version: PDO ODBC with Custome DB2 driver

### Description:
I use the PHP stream functionality to make it possible to upload large files. Following is the code that is responsible for the upload.
```
$this->s3Client()->registerStreamWrapperV2();

$src = $request->getContent(true);
$dest = fopen($this->getUri($fileName), 'w');

stream_copy_to_stream($src, $dest);

fclose($src);
fclose($dest);
```
The streaming functionality makes it possible to upload very large files without hanging PHP because of memory limits. The exceptions is when I want to upload a json file and the Content-Type header is set to application/json. This will result in a 500 internal server error. The uploaded json file is 20MB in size.
`2022/08/30 11:55:22 [error] 72213#72213: *421 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/{redacted}/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 405PHP message: PHP Stack trace:PHP message: PHP   1. {main}() /var/www/html/{redacted}/public/index.php:0PHP message: PHP   2. Illuminate\Http\Request::capture() /var/www/html/{redacted}/public/index.php:52PHP message: PHP   3. Illuminate\Http\Request::createFromBase($request = class Symfony\Component\HttpFoundation\Request { public $attributes = class Symfony\Component\HttpFoundation\ParameterBag { protected $parameters = [...] }; public $request = class Symfony\Component\HttpFoundation\InputBag { protected $parameters = [...] }; public $query = class Symfony\Component\HttpFoundation\InputBag { protected $parameters = [...] }; public $server = class Symfony\Component\HttpFoundation\ServerBag { protected $parameters = [...] }; public $files = class Symfony\Component\HttpFoundation\FileBag { protected $parameters = [...] }; public $cookies = class Symfony\Component\HttpFoundation\InputBag { protected $parameters = [...] }; public $headers = class Symfony\Component\HttpFoundation\HeaderBag { protected $headers = [...]; protected $cacheControl = [...] }; protected $content = NULL; protected $languages = NULL; protected $charsets = NULL; protected $encodings = NULL; protected $acceptableContentTypes = N...PHP message: PHP   4. Illuminate\Http\Request->json($key = *uninitialized*, $default = *uninitialized*) /var/www/html/{redacted}/vendor/laravel/framework/src/Illuminate/Http/Request.php:489PHP message: PHP   5. json_decode($json = '{"data":[{"productNumber":"AAX10057","onStock":false},{"productNumber":"AA00001","onStock":true},{"productNumber":"AA00002","onStock":false},{"productNumber":"AA00003","onStock":false},{"productNumber":"AA00004","onStock"`

The cause is the special handling of json data by laravel Illuminate\Http\Request::createFromBase() function. This function loads the whole body into memory if the content-type is  application/json.

To mitigate this problem I have advised my customer to set the content-type to text/plain when uploading json files. But this leaves me vulnerable to people who want to DDOS my php process. The only thing they need to do is setting the  content-type to application/json.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by wjonkerhulst** [comment]
@driesvints It is not really a question. I can see what the cause is, and have the problem resolved for my personal case. I just wanted to notify you about something I think is a problem.

**Comment by driesvints** [comment]
Hey @wjonkerhulst. I think in this case what you're trying to do just isn't fit for your use case. It's best that you look for an alternative way to handle the upload for these kind of large files.
