### ISSUE TITLE
Filled method of the request returns true for empty array

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#43940]
- Laravel Version: 9.26.1
- PHP Version: 8.1.9
- Database Driver & Version:

### Description:

In the [documentation](https://laravel.com/docs/9.x/requests#determining-if-input-is-present) we have:
`
If you would like to determine if a value is present on the request and is not empty, you may use the filled method:
`

Please pay attention to: ...**and is not empty**..

### Steps To Reproduce:
```
$request = Request::create('/', 'GET', ['foo' => []]);
$this->assertTrue($request->filled('foo'));
```

Is it correct?

**Comment by Sergiobop** [comment]
Yeah, this happened to me too before. I think is a bug or a misconception.

I had a query condition like this one:
```
...
 ->when($request->filled('array_with_ids'),
                fn($query) => $query->whereIn('id', $request->input('array_with_ids'))
  )
...
```

And passing an empty array, caused the query to fail.

I had to do this:
```
...
 ->when($request->filled('array_with_ids') && count($request->input('array_with_ids')),
                fn($query) => $query->whereIn('id', $request->input('array_with_ids'))
  )
...
```

**Comment by driesvints** [comment]
This method is for strings specifically. I've sent in a PR to the docs to clarify this.

**Comment by siarheipashkevich** [comment]
@driesvints do you plan to extend this for array also?

**Comment by driesvints** [comment]
No, sorry. You can always attempt a PR if you want.

**Comment by siarheipashkevich** [comment]
@driesvints got it, thank you for response.

Maybe clarify comment of the method also?

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Http/Concerns/InteractsWithInput.php#L137
