### ISSUE TITLE
Unnecessary query parameter (_id is not null) in Eloquent relationships

### ISSUE THREAD

**Issue by taai** [laravel/framework#43948]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9
- Database Driver & Version: PostgreSQL 14.5

### Description:

I'm really confused about the SQL query that is being generated when fetching records by a relationships (for example, ```HasMany``` and ```MorphMany```).

```php
// for HasMany relationship
$meeting->participants()->toSql();
// returns
// select * from "meeting_participants" where "meeting_participants"."meeting_id" = ? and "meeting_participants"."meeting_id" is not null

// I would expect this:
// select * from "meeting_participants" where "meeting_participants"."meeting_id" = ?


// for MorphMany relationship
$post->media()->toSql();
// returns
// select * from "media" where "media"."model_type" = ? and "media"."model_id" = ? and "media"."model_id" is not null

// I would expect this:
// select * from "media" where "media"."model_type" = ? and "media"."model_id" = ?
```

There **should not** be an extra query parameter that checks if the related ID is not null, because there is already comparison of ID's done and also the the primary key of the related model is never going to be null anyway... Who knows how this extra query parameter affects database's query planner...! :thinking: 

Probably this is happening since #37451 , but I'm not sure about that.

### Steps To Reproduce:

Make Eloquent models with ```HasMany``` and/or ```MorphMany``` relationships. Probably the same issue affects other types of relationships as well.

```php
class Meeting extends Model
{
    public function participants()
    {
        return $this->hasMany(MeetingParticipant::class);
    }
}

class MeetingParticipant extends Model
{
}

$meeting = new Meeting();
$meeting->id = 123; // fake an existing record

// display the generated SQL query
echo $meeting->participants()->toSql();
```

**Comment by rodrigopedra** [comment]
This check was introduced in PR #8033 from 2015 to Laravel 5.0.

Check the discussion on the PR above for the rational and discussion. Also see issues/PR referencing the PR above and the reasons for not reverting this behavior.

**Comment by taka-oyama** [comment]
Someone already attempted to simplify it but was rejected.
https://github.com/laravel/framework/pull/36905

**Comment by driesvints** [comment]
Heya, if you want this to be reconsidered feel free to reattempt the PR. Thanks
