### ISSUE TITLE
touchParent wont work if table a name is specified in the model.

### ISSUE THREAD

**Issue by deeputvr** [laravel/framework#43960]
touchParent wont work if table a name is specified in the model.

Steps to recreate:
1. create a user model. Give `$table = 'test_users';`
2. create belongsToMany relation to roles model
3. Now use `->sync(...)` to assign some roles
4. See if touch parent worked. Since the checking is based on old code, the feature is not working
5. We needed to call `setTouchedRelations()` manually to work this.
This becomes an issue when we follow own convention for table names. We will have many tables and relations in the project. It wold be great if it handles automatically.

![image](https://user-images.githubusercontent.com/43330049/173629354-768b70f6-54af-485e-93c3-d4fd785f91f8.png)
https://github.com/laravel/framework/blob/ccefc764871fe263dd20f8f7108c18180f78241b/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L1142

_Originally posted by @deeputvr in https://github.com/laravel/framework/discussions/42808_

**Comment by driesvints** [comment]
Please don't move discussions to issues.
