### ISSUE TITLE
Multiple Queue Workers Don't Respect Job Chains Containing Batches

### ISSUE THREAD

**Issue by clanofartisans** [laravel/framework#43970]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9
- Database Driver & Version: Redis 7.0.4

### Description:
I have created a job chain that runs a batch, then a few other, simpler jobs. I am noticing that, when running multiple queue workers (using Horizon in my case), the batch that is "step one" in my chain doesn't necessarily complete before "step two" begins, despite everything being in the same chain.

### Steps To Reproduce:
Here is a simplified version of the code I'm having issues with.

```
Bus::chain([
    function () use ($list) {
        $batch = [];
        foreach ($list as $id) { // Creates about 100 JobOne jobs
            $batch[] = new JobOne($id);
        }
        Bus::batch($batch)->dispatch();
    },
    new JobTwo($handler),
    new JobThree($handler),
    new JobFour($handler)
])->dispatch();
```

In this example, JobOne is a batch that begins processing and JobTwo is starting before the entirety of the batch has completed, despite being ahead of it in the chain.

**Comment by driesvints** [comment]
You can't execute batches inside batches. That's not supported.

**Comment by clanofartisans** [comment]
@driesvints If the distinction matters, this is a batch inside a chain, not a batch inside a batch. I actually got the idea from watching @themsaid on Laracasts describing exactly this process [here](https://laracasts.com/series/laravel-queue-mastery/episodes/5) at 3:48.

**Comment by driesvints** [comment]
@themsaid I don't think this is supported? We don't document this anywhere?
