### ISSUE TITLE
Problem in the __call() method of Eloquent query builder

### ISSUE THREAD

**Issue by tobia** [laravel/framework#43973]
- Laravel Version: 9.x (git head)

### Description:

The Eloquent query builder (`Illuminate\Database\Eloquent\Builder`) has a [__call() method](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Builder.php#L1822) that forwards unknown method calls to the wrapped query builder instance (`$this->qurey`) but then always returns its own `$this`.

This makes it impossible to call methods on the base query builder that are meant to return something different than `$this`, such as `newQuery()`. Moreover, calling such methods does not throw an error, instead silently returning the wrong `$this` instance, causing hard to debug situations.

The `__call()` method should probably check whether the value returned by the wrapped method call is the same `$this->query` on which it was invoked, and only replace it with its own `$this` in that case; otherwise it should leave the return value unchanged.

**Comment by driesvints** [comment]
Not sure I really see a bug here. If there's something you want to improve feel free to attempt a PR. Thanks
