### ISSUE TITLE
`RouteGroup::merge` adds slash to the route prefix, when parent RouteGroup prefix is empty / not set.

### ISSUE THREAD

**Issue by JirakLu** [laravel/framework#43997]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9
- Database Driver & Version: X

This is a follow up issue to my old one, where i miss understood the problem.
## Description:
Route prefix is returned with slash at the start when parent RouteGroup prefix is empty.
For exmaple:
```php
Route::middleware("auth")->group(function () { // parent RouteGroup prefix is empty
    Route::view("/", "page.test");

    Route::prefix("dashboard")->group(function () { // we add another group with its own prefix
        Route::view("/settings", "page.test");
    });
});
```
### Expected behavior:
When user visits `*/dashboard/settings` the `Route->current()->getPrefix()` should return `dashboard`
### Actual behavior:
The route prefix is returned with slash at the start -> `/dashboard`

This only happens when parent RouteGroup prefix is empty
For example this code would work as expected:
```php
Route::prefix("admin")->group(function () { // parent RouteGroup prefix is set to admin
    Route::view("/", "page.test");

    Route::prefix("dashboard")->group(function () { // we add another group with its own prefix
        Route::view("/", "page.test");
    });
});
```
When user visits `*/admin/dashboard` the `Route->current()->getPrefix()` returns `admin/dashboard` as expected.

**The main problem is that route like this wouldn't work too.**
```php
Route::group(["prefix" => "dashboard"], function () {
    Route::view('/', "page.test");
});
```
When user visits `*/dashboard` the `Route->current()->getPrefix()` returns `/dashboard`

This is because all routes inside `web.php` are loaded using group with empty prefix in `RouteServiceProvider` boot method.
```php
Route::middleware('web')
                ->group(base_path('routes/web.php')); // RouteGroup prefix is empty
```

## Source of the problem
If i understood the problem correctly i think the issue is in the `RouteGroup::formatPrefix` method.
https://github.com/laravel/framework/blob/7fa4beb386a139cabb730a7e3b9571ba8ea2a181/src/Illuminate/Routing/RouteGroup.php#L64-L73
Here the `$old` variable  is set to empty string, when the parent  RouteGroup prefix is empty / not set.
And now when the old prefix is empty and new prefix is set. 
This is what happens in the code on line 69  -> `"" . "/" . "newPrefix"`
There is **slash** added to the start of the new prefix.

I also managed to write a failing test for this issue.
```php
$old = []; // leave array empty, this is what happens when loading routes in RouteServiceProvider
$this->assertEquals(['prefix' => 'foo', 'namespace' => null, 'where' => []], RouteGroup::merge(['prefix' => 'foo'], $old)); // add prefix to route group
```
### Test output
```
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'prefix' => 'foo'
+    'prefix' => '/foo'
     'namespace' => null
     'where' => Array ()
 )
```

## My solution
I managed to fix this issue by wrapping the return from `formatPrefix` in trim.
Reference:
https://github.com/laravel/framework/blob/7fa4beb386a139cabb730a7e3b9571ba8ea2a181/src/Illuminate/Routing/RouteGroup.php#L64-L73
My fix:
```php
return trim(isset($new['prefix']) ? trim($old, '/').'/'.trim($new['prefix'], '/') : $old, '/');
```
This should guarantee the prefix is always returned without slash at the start as expected.
I also tried running all the tests in the Routing folder after this fix and all of them have passed.

If my understanding of the problem is correct i would be open to submit a PR with fix and some additional test.

**Comment by driesvints** [comment]
Feel free to send in a PR but keep in mind that none of the existing behavior for non-cached routes can change.

**Comment by ruedigerm-playster** [comment]
I just wanna leave this comment in case others have the same issue as I:
this change introduced a breaking change. before, the function $request->route()->getPrefix() returned the prefix with "/" at the beginning. Now this slash is removed.
While the new behavior is cleaner and better, it broke my application and required some refactoring.

**Comment by driesvints** [comment]
@ruedigerm-playster did this break something for you in non-cached route behavior or with cached routes?

**Comment by ruedigerm-playster** [comment]
I think non-cached behavior. (at least I'm not using any caching explicitly)

I use prefix like 
`Route::prefix('my-api')->group(function () {`

Old behavior: `$request->route()->getPrefix()` returned the prefix as "/my-api"
New behavior: `$request->route()->getPrefix()` returned the prefix as "my-api"

**Comment by driesvints** [comment]
@JirakLu we're going to roll back your PR. Seems it did break something while routes aren't cached. We cannot change the behavior for non-cached routes on patch releases.
