### ISSUE TITLE
Bug when setting a 'root' path in s3 disk

### ISSUE THREAD

**Issue by Omar-Ess** [laravel/framework#43998]
### Description

This issue occurs when using s3 disk and specifying root path in the config. what happens is when generating a s3 url using the storage facade the end path character "/" is being converted to "%5C" which is  the hex ASCII representation of "backslash" . if I remove the root path from the config , then everything works as expected . I saw a couple of people reporting this issue and they claim that it only occurs in Laravel v9

#### How to reproduce

1. Setup a disk in config filesystem.php that uses the s3 driver
2. Define a 'root' key in the filesystem config for that disk 
```php
 s3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
            'root' => "tenants/" // when specifying root the issue occurs
        ],
```
3. Try to generate an s3 url or temporary url using the Storage facade

```php
Storage::disk("s3")->url("media/1/picture.png");
```
#### Expected result

`https://bucket-name.s3.amazonaws.com/tenants/media/1/picture.png`

#### Actual results

`https://bucket-name.s3.amazonaws.com/tenants%5Cmedia/1/picture.png`

**Comment by rodrigopedra** [comment]
Have you tested without the forward slash at the end?

~~~php
'root' => "tenants",
~~~

All code snippets in the docs that set a root property for a file storage does not contain this extra forward slash

https://laravel.com/docs/9.x/filesystem

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by syamsoul** [comment]
i also face this issue

**Comment by syamsoul** [comment]
i just solved the issue... i think this issue is only occurred on Windows ... because default `directory_separator` in Windows is `\` ..

to change the `directory_separator`, just simply add to your disk configuration...

for example:
```
     s3' => [
          'driver' => 's3',
          'key' => env('AWS_ACCESS_KEY_ID'),
          'secret' => env('AWS_SECRET_ACCESS_KEY'),
          'region' => env('AWS_DEFAULT_REGION'),
          'bucket' => env('AWS_BUCKET'),
          'url' => env('AWS_URL'),
          'endpoint' => env('AWS_ENDPOINT'),
          'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
          'throw' => false,
          'root' => "tenants",
          'directory_separator' => '/', // ADD THIS LINE, and your problem solved
    ],
```

**Comment by muhammedshiffin** [comment]
@syamsoul you are life saver!! 🔥❤
