### ISSUE TITLE
Mailable ignoring markdown with Indentation

### ISSUE THREAD

**Issue by philharmonie** [laravel/framework#44008]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9
- Database Driver & Version: mysql 8
_Btw: Using the `php artisan about` template here would be cool_

### Description:
Usually developers use some formatters that auto format code on document save. This is good and helpful and end in beautiful formatted code. To add and use indentation is a common standard.

### Steps To Reproduce:
Having this return statement in a mailable's build function:
```
return $this->subject('Foo')
            ->markdown('mail.bar');
```
and this `resources/views/mail/bar.blade.php` view with correct indentation:
```
@component('mail::message')
    # Mail
    **Test**
@endcomponent
```
results in an email with a formatted h1 but with Test not printed in bold but as `**Test**`.
Having the view without indentation like
```
@component('mail::message')
# Mail
**Test**
@endcomponent
```
the output is correct.

For more complex emails with tables and if-elses this is very bad to read and in general very annoying to disable the auto formatter every time you save a mailable view.

**Comment by driesvints** [comment]
Indentation in markdown results in a code block. This is how markdown behaves and there's nothing we can do about this.

**Comment by philharmonie** [comment]
Is there a way to disable code block detection?
