### ISSUE TITLE
`storage:link` is unsuccessful when using custom public path

### ISSUE THREAD

**Issue by Rizky92** [laravel/framework#44001]
- Laravel Version: 9.26.1
- PHP Version: 8.1.6
- Database Driver & Version: N/A
- OS: Windows 10 21H2

### Description:
WHen trying to run `storage:link` on custom public path, Laravel falsely reported successful symbolic link folder generation. Notice the storage folder is absent in `public_html` folder:
![Screenshot (8)](https://user-images.githubusercontent.com/18244409/188333720-a30e72f6-fce7-4740-9861-322b95bf5397.png)

However, Laravel reported correct custom public path:
![Screenshot (7)](https://user-images.githubusercontent.com/18244409/188333685-0d308cd5-4d85-4725-bee7-57355613a41c.png)

At the moment, this is resolvable by providing hardcoded custom public path:
![image](https://user-images.githubusercontent.com/18244409/188334294-9464aa51-fc68-48f8-8d30-625ac0cedb31.png)

### Steps To Reproduce:
1. Rename public folder to something else. (e.g. `public_html`)
2. Bind customized public folder in ServiceProvider, like below
3. Run `php artisan storage:ink`

In `AppServiceProvider@boot`:
```php
$this->app->bind('path.public', function() {
    return realpath(base_path().'/public_html');
});
```

**Comment by timacdonald** [comment]
Looks like this is caused by the `links` configuration in the `config/filesystems.php` file:

```php
    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],
```

Because config is resolved _before_ userland service providers, it resolves the default public directory instead of the one specified in the applications service provider, i.e.

```php
$this->app->instance('path.public', $this->app->basePath('public_html'));
```

For a fix now, you can manually configure the public directory in the `filesystems.php` config:

```php
    'links' => [
        base_path('public_html') => storage_path('app/public'),
    ],
```

Looks like we use a few path helpers in configuration files, so if you are changing anything you may need to tweak your config files manually to accommodate that.

Alternatively, you could leave the `public` directory in place and create a symlink between your `public_html` => `public`. I've done that before when I was unable to control the public directory on the hosting.

**Comment by driesvints** [comment]
We do not support modifying the public path, sorry.

**Comment by Rizky92** [comment]
> Alternatively, you could leave the `public` directory in place and create a symlink between your `public_html` => `public`. I've done that before when I was unable to control the public directory on the hosting.

I think I'll try this one. Thanks.

**Comment by Sebastiangperez** [comment]
I just achieve this using ln command , i told to the guys from the hosting to do that. and worked.

**Comment by starcevpro** [comment]
```php
'links' => [
    base_path('public_html\storage') => storage_path('app/public'),
],
```

**Comment by sadiqsalau** [comment]
Update in `bootstrap/app.php`


```php



/*
|--------------------------------------------------------------------------
| Update application paths
|--------------------------------------------------------------------------
|
| Here we update application paths such as the public path
|
*/

$app->usePublicPath(
    "public_html"
);

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;

```
