### ISSUE TITLE
A migration with both creation and renaming of columns will delete the table

### ISSUE THREAD

**Issue by 0notole** [laravel/framework#44006]
- Laravel Version: 9.21.6
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8.0.30

### Description:
A migration with both (1) creation of new columns (tested with float and booleans in particular) and (2) renaming an existing column – such a migration will delete the whole table. No errors in the console, all is done and successful but the table is gone with all the contents.

### Steps To Reproduce:

1. Create a migration,
2. Add a $table->float() and $table->rename() to the up() function,
3. Run the migration.

**Comment by driesvints** [comment]
It's best that you use separate `Schema::table` statements for these as shown in the docs: https://laravel.com/docs/9.x/migrations

**Comment by 0notole** [comment]
@driesvints 

Absolutely, as a workaround perhaps. But would you agree that ideally this combination should produce an error or warning?

**Comment by driesvints** [comment]
You can always attempt a pr 👍
