### ISSUE TITLE
Relation::withDefault() on `HasOne` or `BelongsTo` returns empty array instead of null

### ISSUE THREAD

**Issue by shaedrich** [laravel/framework#44004]
- Laravel Version: 8.83.20
- PHP Version: 8.1.5
- Database Driver & Version: sqlite 3.31.1

### Description:
When I define a `HasOne` or `BelongsTo` relationship in a model and for a specific model instance there's no related record, Laravel returns `null` for the relation&mdash;so far so good. In some cases, I have a default related model, in others, I don't. So I use `Relation::withDefault()` and return `null` when there is no default relation. I expected, the relation to be null, then, but it is returned as `[]`. I looked up the source code and it indicated, I better return `false` instead. I did that, but the result was still `[]`. Is this a bug or is it indeed intended?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by shaedrich** [comment]
Hey Dries,

the file wasn't changed between 8.x and 9.x (or master)
