### ISSUE TITLE
`APP_URL` appears to be ignored on blade with `asset()` and `route()`

### ISSUE THREAD

**Issue by AlexWinder** [laravel/framework#44015]
- Laravel Version: 9.26.1
- PHP Version: 8.1
- Database Driver & Version: `mysql` with MariaDB

### Description:

The `APP_URL` which is tied to `config('app.url')` does not appear to be factored into the the `asset()` and `route()` on Blade.

I have a Laravel application which is served via an Nginx Docker container. In front of this Docker container I have another Nginx service on a host which is acting as a reverse proxy to route traffic through to the Laravel Nginx Docker container.

In my environment my `APP_URL` is set to `https://mysite.com`.

I have a strange issue whereby the `asset()` and `route()` values on the page are being returned as HTTP, even though my `APP_URL` is set to HTTPS. When I visit my site in a browser they are being set to `http://mysite.com`.

If I go access the Nginx Docker container and view the source of the web page via its local IP address of `127.0.0.1:8080`, the values returned are all `http://127.0.0.1:8080`, and not `https://mysite.com` as is set in `SITE_URL`.

My understanding of `APP_URL` is that this is the address used for things such as `asset()` and `route()` to act as a domain for the application.

If I go into `artisan tinker` to check the values of `route()` and `asset()` they are all returning as I would expect. Is there anything in Blade which makes these act in a different way?

As a workaround I have found that one solution is to just force everything to HTTPS, however I would prefer to know the reason behind what I am seeing so that I can fix it in the code rather than having a handle on everything.

```php
if(config('app.env') === 'production') 
{
    URL::forceScheme('https');
}
```

**Comment by AlexWinder** [comment]
So the issue I am having appears to be with my reverse proxy with the request to `https://mysite.com` is being passed through to `http://127.0.0.1:8080`, which is being picked up as a request in PHP to `http://127.0.0.1:8080` However, this doesn't explain why `artisan tinker` which appears to be returning the values with `APP_URL`.

**Comment by crynobone** [comment]
There no actual request when running Laravel from console command, Laravel instead set the request from config during bootstrap: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by AlexWinder** [comment]
Thanks for the pointer @crynobone - however I would expect the default behaviour for at least `route()` to factor in this `APP_URL` which doesn't seem to be the case. It makes it quite confusing. Could you recommend any alternative helper which I could use which factors in both the response of `route()` and the `APP_URL`?

@driesvints Appreciate that it could be asked on a support channel, however this appears to be an issue (or an undocumented feature) of Laravel.

The [documentation for `asset()`](https://laravel.com/docs/9.x/helpers#method-asset) says:

> The asset function generates a URL for an asset using the current scheme of the request (HTTP or HTTPS):

This is fine, I can understand why I was getting the response I was getting based on this. I will set the `ASSET_URL` value in my environment to fix these. 

However the [documentation for `route()`](https://laravel.com/docs/9.x/helpers#method-route) does not explain this behaviour. I would expect `route()` to return factoring in the `APP_URL`, especially when using named routes which is how I am using it. I have been using Laravel since 5.4 and it has always been my understanding that this is the behaviour so it has come as a surprise to me that this isn't the case. If this isn't the best helper to access named routes which factors in `APP_URL` then please could you point me in the right direction?

**Comment by driesvints** [comment]
I'm sorry @AlexWinder, I don't think there's an issue with these features as these are heavily utilised by hundred of thousands of apps. Please try a support channel if you have questions about these or try a PR if you really think there's a bug.

**Comment by AlexWinder** [comment]
I have since found out that the reason for this is caused by my `TrustProxies` was not updated to accept from certain addresses, such as my reverse proxy address. I have set the protected `$proxies` value to `*` in `app\Http\Middleware\TrustProxies.php` and this has resolved my issue.

```php
class TrustProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var array<int, string>|string|null
     */
    protected $proxies = '*';

    /**
     * The headers that should be used to detect proxies.
     *
     * @var int
     */
    protected $headers =
        Request::HEADER_X_FORWARDED_FOR |
        Request::HEADER_X_FORWARDED_HOST |
        Request::HEADER_X_FORWARDED_PORT |
        Request::HEADER_X_FORWARDED_PROTO |
        Request::HEADER_X_FORWARDED_AWS_ELB;
}
```
