### ISSUE TITLE
Mail::alwaysTo() is not overriding mailable

### ISSUE THREAD

**Issue by divdax** [laravel/framework#44024]
- Laravel Version: 9.27.0
- PHP Version: 8.1.9

### Description:

`Mail::alwaysTo()` in ServiceProvider is ignored when make use of a custom mailer to send a mailable.

### Steps To Reproduce:

 env is `local`.

AppServiceProvider
```php
public function boot()
{
  if (!app()->environment('production')) {
    Mail::alwaysTo('test@example.com');
  }
}
```

DocumentMail.php
```php
public function build(): DocumentMail
{
    $this->mailer('invoice'); // use another mailer defined in config/mail.php

    $this->from(config('mail.from.invoice.address'));
    if(!count($this->to)) {
        $this->to('custom@example.com');
    }
    $this->subject('your document');
    $this->view([])->withSymfonyMessage(
        fn($msg) => $msg->text('plain mail')
    );

    return $this;
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
