### ISSUE TITLE
Http client is not overwriting the content type header when attaching a file or even if you manually call another method

### ISSUE THREAD

**Issue by Erth0** [laravel/framework#44028]
- Laravel Version: 9.27.0
- PHP Version: 8.1.5
- Database Driver & Version: mysql

### Description:
I came across a strange issue with the http client where the `Content-Type` header is not being overwritten by any method which will be called after the first set. See examples below.

### Steps To Reproduce:
I have the base http client set to the below code example.
```php
Http::asJson()
    ->baseUrl('https://webhook.site/')
    ->attach('File', $fileContent, 'testing-file.png')
    ->post('a808f079-7df8-4492-b553-6fde48ce64aa')
``` 

I have set it that I want the content type to be `application/json` within the attach method though there is a method `asMultipart()` which is called and this should overwrite the previous `Content-Type` header, however this doesn't overwrite it instead uses the `application/json`.

This issue is as well even if you don't use the `attach` method but instead you overwrite it at a later stage for example:
```php
Http::asJson()
    ->baseUrl('https://webhook.site/')
    ->timeout(30)
    ->asMultipart()
    ->post('a808f079-7df8-4492-b553-6fde48ce64aa')
```
The above code will have the same issue expectation is the `Content-Type` to be set to `multipart/form-data` however it is still set to `application/json`.

> In another try of trying to fix the above issue I tried to set manually the headers with the `withHeaders` method and when I set the `Content-Type` to `multipart/form-data` It was appended instead of overwritten .

Not sure if that one is an issue or it is meant to be in that way just though to mention it.

**Comment by Cbrad24** [comment]
Indeed, I replaced all my API classes that were loading their own GuzzleHttp instance with the new Laravel Http wrapper. At construction of the class I store the Pending Request inside the class and ended up running into the same issue when a single API endpoint demanded `text/plain` for a `DELETE` request.

I had to create my own workaround using this:
```php
abstract class HttpClient
{
    /**
     * The Http prepared request.
     *
     * @var \Illuminate\Http\Client\PendingRequest
     */
    protected PendingRequest $request;

    /**
     * Override the Accept header with a new one rather than appending one.
     *
     * @param  string  $type
     * @return $this
     */
    protected function overrideAccept(string $type): static
    {
        return tap($this, function () use ($type) {
            $this->request->withOptions([
                \GuzzleHttp\RequestOptions::HEADERS => [
                    'Accept' => $type,
                ],
            ]);
        });
    }
}
```

From what I worked out at the time, it seems that `PendingRequest::withHeaders()` always merges recursively which causes the `Accept` header to combine into an array behind the scenes. The only way to override it once set was with the `PendingRequest::withOptions(['headers' => ['Accept' => 'text/plain']])` method.

This functionality doesn't happen with most of the other methods on the `PendingRequest` class, for instance using `withToken`, `withUserAgent`, or `timeout` for example will always override the set value.

I suspect this was done on purpose however as [it is valid](https://www.w3.org/Protocols/HTTP/HTRQ_Headers.html) to specify multiple values for the Accept header, but I do agree it was unexpected functionality.

Maybe the solution is to expose two methods, for instance `accept` and `alsoAccept`?

**Comment by Erth0** [comment]
Your solution seems good to me thanks for that! 

It seems strange though because the attach method is calling `asMultipart` method which by looking on it you assume that changes or adds it to the headers although that doesn't update it.
At the moment I have done some workaround which calls dynamically the given method I assign but I am wondering if this can be fixed or if it is porously like that.

**Comment by driesvints** [comment]
Hi there. It's expected that `attach` uses multipart as that's the content type we need to do file uploads.

**Comment by Erth0** [comment]
> Hi there. It's expected that `attach` uses multipart as that's the content type we need to do file uploads. 

But that's the issue that is not overwriting to use multipart instead uses the previous defined method

**Comment by driesvints** [comment]
Ah I see. Your actual issue is that you shouldn't use `asJson` at all when uploading files.
