### ISSUE TITLE
The middleware "SetCacheHeaders" doesn't work with file responses

### ISSUE THREAD

**Issue by clementbirkle** [laravel/framework#44036]
- Laravel Version: 9.26.1
- PHP Version: 8.1.8

### Description:

The middleware "SetCacheHeaders" (cache.headers) doesn't work with file responses because in this case "! $response->getContent()" seems to be empty: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Http/Middleware/SetCacheHeaders.php#L24

I use a simple response like that: https://laravel.com/docs/9.x/responses#file-responses

Is it normal or it is a bug?

**Comment by driesvints** [comment]
I don't think it makes sense for file responses? Should those even be cached?

**Comment by clementbirkle** [comment]
Yes, I think it can make sense.

In my case, I use file responses for protected files. Each request make a query to the database to retrieve the path of the file and then return the response.

Put the file in browser cache could avoid to make this call 20 times for the same file/same user.

**Comment by driesvints** [comment]
Feel free to attempt a PR if you want 👍
