### ISSUE TITLE
Paginator count prequery ignores aliased selects

### ISSUE THREAD

**Issue by inDeev** [laravel/framework#44076]
- Laravel Version: 9.28
- PHP Version: 8.0.22
- Database Driver & Version:
sqlite, mariadb
### Description:
When asking to return paginated results, when search is made through aliased column, paginator's count query returns wrong result - always 0 and then query itself is not fired.

### Steps To Reproduce:
```
$employees = Employee::select('employees.*', 'salaries.salary as salariesSalary')
            ->leftJoin('salaries', 'salaries.id', 'employees.active_salary_id')
            ->where('salariesSalary', 'LIKE', '%' . $search . '%')
            ->paginate(10);
```
count query then looks like:
```
SELECT COUNT(*) as aggregate
FROM "employees" 
LEFT JOIN "salaries" on "salaries"."id" = "employees"."active_salary_id"  
WHERE "salariesSalary" LIKE '%15000%'
```
and 0 is returned as there is missing alias select. First line should look like
```
SELECT count(*) as aggregate, select 'salaries'.'salary' as salariesSalary
```

**Comment by DarkGhostHunter** [comment]
Try first with not aliasing a the column and set the explicit where with a table, like `salaries.salary` instead of `salariesSalary`.

BTW, use `e($search)` to at least sanitize the string to search.

**Comment by inDeev** [comment]
Aliasing is used there because of Blades - Query count optimization. What you see in my issue report is only part of my query and yes, I know about use of `salaries.salary' in WHERE condition and it is working right when used. But this Issue is not about that. I think, that prequery should implement aliased select as it it part of working query builder, because if not, it means, that it returns wrong result e.g.  0 vs 500 without pagination used.
