### ISSUE TITLE
named routes not added into look-up table

### ISSUE THREAD

**Issue by pYr0x** [laravel/framework#44077]
- Laravel Version: 9.28.0
- PHP Version: 8.1
- Database Driver & Version:

### Steps To Reproduce:

the example on the laravel doc 
```
Route::get('/user/profile', function () {
    //
})->name('profile');
```
set a route-name. But this name does not get added to the route look-up table on the `RouteCollection.php`

so don't get the named route back if you call `$router->has('profile');`.

i dont know if this was the purpose.

**Comment by DarkGhostHunter** [comment]
Must be something in your end. I just added the same example in `web.php` in a project and `Route::has('profile')` returns true.

Try this:

```shell
php artisan route:list
```

BTW, don't add a Route while the app is running, as it won't persist after the request ends. If you're adding a route will need to refresh the name lookups and action lookups.

```php
use Illuminate\Support\Facades\Route;

Route::get('something', function() {
    // ...
})->name('cool');

Route::getRoutes()->refreshNameLookups();
Route::getRoutes()->refreshActionLookups();
```

**Comment by driesvints** [comment]
Works fine for me for both cached and none-cached routes.
