### ISSUE TITLE
Prevent silently discarding attributes feature is not working

### ISSUE THREAD

**Issue by nshiro** [laravel/framework#44094]
- Laravel Version: 9.29.0
- PHP Version: 8.0.13

### Description:
New feature introduced in Ver.9.28.0 #43893 is not working as expected.

### Case1

AppServiceProvider
```php
    public function boot()
    {
        Model::preventSilentlyDiscardingAttributes();
    }
```

User.php
```php
protected $fillable = ['name'];
```

web.php
```php
Route::get('/', function () {
    $user = new User();
    $user->fill(['hoge' => 'bar']);

    return 'ok';
});
```

This echos `ok`.
But this should throw an exception, right?

### Case2
My bad. This is not a bug. This is related https://github.com/laravel/framework/pull/33777.

> AppServiceProvider
> ```php
>     public function boot()
>     {
>         Model::preventSilentlyDiscardingAttributes();
>     }
> ```
> 
> User.php
> ```php
> protected $guarded = ['id'];
> ```
> 
> web.php
> ```php
> Route::get('/', function () {
>     $user = new User();
>     $user->fill(['hoge' => 'bar']);
> 
>     return 'ok';
> });
> ```
> 
> This throws MassAssignmentException.
> `Add [hoge] to fillable property to allow mass assignment on [App\Models\User].`
> 
> `hoge` should be filled, right? If I'm not mistaken.

**Comment by driesvints** [comment]
Ping @ralphjsmit

**Comment by nshiro** [comment]
I think `$this->fillableFromArray($attributes)` filters the attributes which are not listed in the 'fillable' property which prevents from working correctly.

https://github.com/ralphjsmit/framework/blob/847064365a71d896f73387a022fd99536137155f/src/Illuminate/Database/Eloquent/Model.php#L444

**Comment by ralphjsmit** [comment]
Was afk today, will check this tomorrow!

**Comment by nshiro** [comment]
One thing I noticed.
I didn't know about this feature #33777.
So `Case2` described above is not a bug at all.
I was mistaken. 👎

**Comment by driesvints** [comment]
This got fixed
