### ISSUE TITLE
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS

### ISSUE THREAD

**Issue by kmarshgov** [laravel/framework#44120]
- Laravel Version: 9.30.0
- PHP Version: 8.1
- Database Driver & Version: pgsql
- vue: "^3.2.39"

### Description:
Github dependabot generates the following security alert. 
The package terser before 4.8.1, from 5.0.0 and before 5.14.2 are vulnerable to Regular Expression Denial of Service (ReDoS) due to insecure usage of regular expressions.

### Steps To Reproduce:
Inside package-lock.json terser used in multiple places:
"terser": "^4.6.3"

**Comment by driesvints** [comment]
Not sure this is Laravel related or anything we can do?

**Comment by kmarshgov** [comment]
I got this notification on a fresh install of Laravel/Vue.
