### ISSUE TITLE
Able to dispatch empty batches that can only be pruned using --unfinished

### ISSUE THREAD

**Issue by Healyhatman** [laravel/framework#44126]
- Laravel Version: 
- PHP Version: 8.1.2
- Database Driver & Version: 8.83.23

### Description:

You can dispatch a batch with no jobs - it will sit there forever and you can only prune it using `--unfinished`

### Steps To Reproduce:

`Bus::batch([])->dispatch();`

Then you can try `php artisan queue:prune-batches --hour=-1` and note that doesn't remove it, but --unfinished=-1 does.

Also, I would expect using `hours=0` to prune things older than "now" and therefore remove the ones I've just done, but that's probably just me misunderstanding.

**Comment by driesvints** [comment]
I'm not sure what the benefit is of pushing empty batches?

**Comment by Healyhatman** [comment]
I didn't say there was any benefit to it, but if you're creating the batches programmatically, such as from a collection, you can end up pushing empty batches and finding yourself in this situation - the same way I did.  You can check that the batch isn't empty before dispatching it, but it still makes sense to me that you should be able to prune empty batches without doing `--unfinished.

**Comment by driesvints** [comment]
I'd just check if a batch is empty before pushing it. But you're free to send in a PR to improve things if you like.

**Comment by Healyhatman** [comment]
Will do, thanks. Should I target Laravel 8 or just go from 9?
