### ISSUE TITLE
Middleware cannot release SendQueuedMailable again

### ISSUE THREAD

**Issue by dododedodonl** [laravel/framework#44123]
- Laravel Version: 9.30.0
- PHP Version: 8.1.10
- Database Driver & Version: mariadb 10.3 and 10.9

### Description:
It looks like the `Illuminate\Queue\InteractsWithQueue` trait is missing on `Illuminate\Mail\SendQueuedMailable`, which results in an PHP error when using middleware like https://github.com/laravel/framework/pull/37568

### Steps To Reproduce:
Tested with `QUEUE_CONNECTION` set to `database` and `sync`, and `MAIL_MAILER` set to `log` and `smtp`

- clone https://github.com/dododedodonl/mail-middleware/commit/39cff6c6676a7e99aefd3630d3984f14b6c97223
- trigger the mail `\Illuminate\Support\Facades\Mail::send(new \App\Mail\RandomMail());`
  - this works as expected (the rate limiter is set for 1 per hour)
- trigger the mail again `\Illuminate\Support\Facades\Mail::send(new \App\Mail\RandomMail());`
  - rate limiter does what it should
  - it should release the job back onto the queue with a delay, but results into an exception
```
PHP Error:  Call to undefined method Illuminate\Mail\SendQueuedMailable::release() in vendor/laravel/framework/src/Illuminate/Queue/Middleware/RateLimited.php on line 91
```

**Comment by rodrigopedra** [comment]
I needed this recently, I extended `Illuminate\Mail\SendQueuedMailable` and added the trait manually. 

Then in the mailables I added a custom trait that overrode `newQueuedJob()` to return my local instance. 

I also tweaked  how middleware is handled as on the original `newQueuedJob()` it will run middleware defined on the mailable right after instantiating the job, and I wanted middleware to be ran by the queue as other jobs.

I didn't try a PR at the time as I thought my use-case might be a corner case.

For reference here is:

<details>
<summary>my custom job "wrapper"</summary>

~~~php
<?php

namespace App\Jobs;

use Illuminate\Mail\SendQueuedMailable;
use Illuminate\Queue\InteractsWithQueue;

class MailableJob extends SendQueuedMailable
{
    use InteractsWithQueue;

    public bool $failOnTimeout = true;

    public function middleware(): array
    {
        // read job middleware from wrapped mailable
        return \array_merge(
            \method_exists($this->mailable, 'middleware') ? $this->mailable->middleware() : [],
            $this->mailable->middleware ?? [],
        );
    }

    public function backoff(): array
    {
        return [60, 105, 120];
    }

    public function retryUntil(): ?\DateTimeInterface
    {
        if (\method_exists($this->mailable, 'retryUntil')) {
            return $this->mailable->retryUntil();
        }

        return null;
    }
}
~~~

</details>

<details>
<summary>
and the trait I add to my mailables to use my custom job class intead of `SendQueuedMailable`
</summary>

~~~php
<?php

namespace App\Jobs;

trait UsesMailableJob
{
    protected function newQueuedJob(): MailableJob
    {
        return new MailableJob($this);
    }
}
~~~

</details>

**Comment by ankurk91** [comment]
I reported the issue in past

https://github.com/laravel/framework/issues/43571

@driesvints How we (reporters) improve so that such issues get attention by Laravel team.

**Comment by driesvints** [comment]
@ankurk91 like I suggested on the issue, try a support channel first and get confirmation by others that it's an actual bug. Then repost the issue with links to those forum threads.

**Comment by ankurk91** [comment]
@driesvints Thanks, i would prefer to create a minimal reproduction and share the git repo link.
