### ISSUE TITLE
hasOne ofMany with json foreign key bug

### ISSUE THREAD

**Issue by yehuda-hybiz** [laravel/framework#44143]
- Laravel Version: 9.30.0
- PHP Version: 8.1.9
- Database Driver & Version: mysql 8.0.30

### Description:
The `hasOne()->latestOfMany()` relation fails when the foreign key is a json key.

This works:
```php
public function latestPayment(): HasOne
{
    return $this->hasOne(Payment::class, 'meta->order_id');
}
```

This fails:
```php
public function latestPayment(): HasOne
{
    return $this->hasOne(Payment::class, 'meta->order_id')->latestOfMany();
}
```

Error message:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'latestOfMany.meta' in 'on clause'
```

### Steps To Reproduce:
Create a hasOne relation where the foreign key is a json column key.

**Comment by driesvints** [comment]
I don't think we support this.

**Comment by yehuda-hybiz** [comment]
Is the fact that this works a happy accident?

```php
public function latestPayment(): HasOne
{
    return $this->hasOne(Payment::class, 'meta->order_id');
}
```
