### ISSUE TITLE
Config facade giving no expectation error during tests

### ISSUE THREAD

**Issue by michaelcozzolino** [laravel/framework#44150]
- Laravel Version: 9.19.0
- PHP Version: 8.1.0

### Description:
I'm trying to test the calls to the `Config` facade but I get the following error:

`Mockery\Exception\BadMethodCallException : Received Mockery_0_Illuminate_Config_Repository::offsetGet(), but no expectations were specified`

### Steps To Reproduce:
`app/Http/Controllers/ConfigController.php`
``` <?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ConfigController extends Controller
{
    public function get()
    {
        $configValue = \Config::get('key');
        return $configValue;
    }
}
```
`routes/web.php`
```
Route::get('/get-config', [\App\Http\Controllers\ConfigController::class, 'get'])->name('config.get');
```

`tests/Feature/Http/Controllers/ConfigControllerTest.php`

```
<?php declare(strict_types=1);

namespace Http\Controllers;

use Tests\TestCase;

class ConfigControllerTest extends TestCase
{
    public function testGet()
    {
        \Illuminate\Support\Facades\Config::shouldReceive('get')->once()->with('key')->andReturn('value');
        $this->get(route('config.get'));
    }
}
```
I tried the same test by using the `Cache` facade and it worked without errors.

**Comment by driesvints** [comment]
Please see: https://laravel.com/docs/9.x/mocking

<img width="756" alt="Screenshot 2022-09-16 at 11 52 17" src="https://user-images.githubusercontent.com/594614/190612248-2e11959c-51b4-4f21-bfcc-5116cbf12ec0.png">
