### ISSUE TITLE
Eloquent query builder does not work correct for morph to relation

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#44159]
- Laravel Version: 9.30.1
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8.0.29

### Description:

Hi all.

I'm using [Constraining Eager Loads With Relationship Existence](https://laravel.com/docs/9.x/eloquent-relationships#constraining-eager-loads-with-relationship-existence) but getting unexpected result. Please see my code:

In `Comment` model I have morph to relation:
```
public function commentable(): MorphTo
{
    return $this->morphTo();
}
```

`Country` model use `SoftDeletes` trait.

And test:
```
public function testWithWhereHas()
{
    $user = User::factory()->create();

    Comment::factory()
        ->for($user)
        ->for(Country::factory()->trashed(), 'commentable') // trashed country <--
        ->create();

    Comment::factory()
        ->for($user)
        ->for(Country::factory(), 'commentable')
        ->create();

    // I want to get all users which has comments with not deleted `commentable` relation, but I'm getting
    // comments with trashed commentable relation also. why?
    User::query()
        ->withWhereHas('comments.commentable')
        ->each(function (User $user) {
            // should be 1
            dump($user->comments->count());

            $user->comments->each(function (Comment $comment) {
                dump(['comment_id' => $comment->id, 'commentable_id' => $comment->commentable?->id]);
            });
        });
}
```
![image](https://user-images.githubusercontent.com/7753600/190609050-155636b1-f67d-43fe-873e-00c1e877f236.png)

Why `withWhereHas` method returns comment which has **trashed** `commentable` relation?

### Steps To Reproduce:

Please see description above.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by siarheipashkevich** [comment]
@driesvints it's obviously a bug, I've described all steps how you can reproduce it and attach link to the documentation where described how it's should work.

**Comment by driesvints** [comment]
Please try a support channel first.

**Comment by siarheipashkevich** [comment]
https://laravel.io/forum/eloquent-query-builder-does-not-work-correct-for-morph-to-re
