### ISSUE TITLE
QueryBuilder ignores microseconds when processing DateTime arguments

### ISSUE THREAD

**Issue by paulandroshchuk** [laravel/framework#44157]
- Laravel Version: 9.30.1
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8.0.30

### Description:

I came across this issue when I was writing tests for a "reporting" feature which goal was to count all records between two dates (on a high precision date time column). And I just accidentally noticed that not all records were taken into account so I started digging what could've went wrong and noticed an interesting article that explained how MySQL works with such columns: https://medium.com/bumble-tech/high-precision-time-how-to-use-fractional-seconds-in-mysql-and-php-fd9b89afe9ad

### Steps To Reproduce:
1. Create a table with [high precision timestamps](https://laravel.com/docs/9.x/migrations#column-method-timestamp)
2. [Set the corresponding date format](https://laravel.com/docs/9.x/eloquent#timestamps) in the model
3. Perform a (where/whereBetween) query using DateTime objects

```php
User::whereBetween('created_at', [
  today(),
  today()->endOfDay(),
])->count();

User::where('created_at', today()->endOfDay())->count();
```

| Created At  | Counted / Ignored |
| ------------- | ------------- |
| 2022-01-01 23.59.**58**.999999  | Counted  |
| 2022-01-01 23.59.**59**.111111  | Ignored  |
| 2022-01-01 23.59.**59**.999999  | Ignored  |

### Links
* Bug-report repository: https://github.com/paulandroshchuk/bug-report
* My attempt to fix this issue: https://github.com/laravel/framework/pull/44158

**Comment by driesvints** [comment]
This is not needed. It's intended for microseconds not to be saved here.

**Comment by paulandroshchuk** [comment]
> This is not needed. It's intended for microseconds not to be saved here.

@driesvints what's the reason to ignore microseconds here? Just curious..

**Comment by driesvints** [comment]
Because it just doesn't works the same across all engines.

**Comment by trevorgehman** [comment]
> Because it just doesn't works the same across all engines.

@driesvints For SQL Server the datetime format is overridden: 

https://github.com/laravel/framework/blob/74cad576dbc3f48c6f529950cee52bc948371f63/src/Illuminate/Database/Query/Grammars/SqlServerGrammar.php#L535-L543

What if we did something similar inside `Illuminate/Database/Query/Grammars/MySQLGrammar`? I believe that would not be a breaking change, and would continue to work properly for MySQL even in situations where the precision is 0 and no microseconds are stored in the database, as the extra precision would just be dropped when the insert/select statement is performed:

<img width="280" alt="CleanShot 2022-09-16 at 08 33 55@2x" src="https://user-images.githubusercontent.com/3209864/190651194-3ff31233-f34e-4563-afb0-9e45468f6e7f.png">

```
INSERT INTO `test_table` (timestamp_1, timestamp_2, timestamp_3, timestamp_4, timestamp_5, timestamp_6)
VALUES ('2022-12-30 12:00:00.123456', '2022-12-30 12:00:00.123456', '2022-12-30 12:00:00.123456', '2022-12-30 12:00:00.123456', '2022-12-30 12:00:00.123456', '2022-12-30 12:00:00.123456')
```

<img width="1195" alt="CleanShot 2022-09-16 at 08 34 36@2x" src="https://user-images.githubusercontent.com/3209864/190651350-7eeff284-0d99-42b4-b037-54626660b97f.png">

**Comment by driesvints** [comment]
@trevorgehman can you attempt a PR?

**Comment by driesvints** [comment]
I don't think we'll change this any time soon, sorry. It's too dangerous as it could lead to break a whole lot of apps. Feel free to PR the docs if you want to.
