### ISSUE TITLE
Artisan command "queue:prune-failed" is not deleting any entries

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/framework#44165]
- Laravel Version: 9.30.0
- PHP Version: 8.1.20
- Database Driver & Version: MySQL 8.0

### Description:
Hi,

Not sure if it's a documentation issue or a code issue but running the artisan command **queue:prune-failed** will not delete any failed jobs that were created within the past 24 hours. 

It seems a bit counter intuitive to have an optional argument altering the default behaviour of the command. The documentation states:
>If you provide the --hours option to the command, only the failed job records that were inserted within the last N number of hours will be retained.

It does not mention that failed jobs are always kept for 24 hours by default, I had to dig through the code to figure that one out. 

### Steps To Reproduce:

1. Create a failed job
2. Run the artisan command **queue:prune-failed**.
3. Output says: "0 entries deleted."

**Comment by driesvints** [comment]
https://laravel.com/docs/9.x/queues#pruning-failed-jobs

<img width="748" alt="Screenshot 2022-09-19 at 09 57 40" src="https://user-images.githubusercontent.com/594614/190973530-44b892f8-f012-4357-8aa3-e317b84bb209.png">
