### ISSUE TITLE
Adding additional Symfony Transports getting erro "Mailer [sendgrid] is not defined."

### ISSUE THREAD

**Issue by khaledelmahdi** [laravel/framework#44169]
- Laravel Version: 9.30.1
- PHP Version: 8.1.9
- Database Driver & Version: mysql latest

### Description:

Adding additional Symfony Transports as per the documentation here: https://laravel.com/docs/9.x/mail#additional-symfony-transports not working.

### Steps To Reproduce:

Hi,

I am getting this error when I try to register SendGridTransport:

***Mailer [sendgrid] is not defined.***

I've added the package:

```
composer require sendgrid/sendgrid
```

I've edited the `AppServiceProvider` file:

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\ServiceProvider;
use Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridTransportFactory;
use Symfony\Component\Mailer\Transport\Dsn;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        Mail::extend('sendgrid', function () {
            return (new SendgridTransportFactory)->create(
                new Dsn(
                    'sendgrid+api',
                    'default',
                    config('services.sendgrid.key')
                )
            );
        });
    }
}

```

I've edited the `config\services.php` file:

```
'sendgrid' => [
        'key' => env('SENDGRID_API_KEY'),
],
```

What I am doing wrong here?

**Comment by rodrigopedra** [comment]
Did you add just `sendgrid/sendgrid`? 

or did you also add Symonfy's mailer?

~~~
composer require symfony/sendgrid-mailer
~~~

Also, it might not be clear in the docs if you skipped right to the additional transport section, but this section is actually a subsection of the "Custom Transports" section.

https://laravel.com/docs/9.x/mail#custom-transports

The final step is to add a new mailer definition to your `./config/mail.php` file. 

Did you add it?

It is the last paragraph just above the "Additional Symfony Transports" sub-sectioin

https://laravel.com/docs/9.x/mail#additional-symfony-transports

**Comment by driesvints** [comment]
You need to add the symfony transport as @rodrigopedra explains.
