### ISSUE TITLE
Laravel couldn't find uploaded files from storage and i get 404

### ISSUE THREAD

**Issue by pishguy** [laravel/framework#44162]
- Laravel Version: "laravel/framework": "^9.14",
- PHP Version: `8.1`

### Description:

After making a simple link for `laravel` storage and uploading files. my files can successfully put into `storage/app/public` directory and when i try to show image such as this link:

```
https://next.my-site.in/storage/38/0bfc02b202f084e57012988db4671fae.png
```

`laravel` could't find that and i get `404` error, but this link work fine:

```
https://next.my-site.in/storage/app/public/38/0bfc02b202f084e57012988db4671fae.png
```

creating storage link command result:

```
[my-site@cpsrv next]$ php artisan storage:link

   INFO  The [public/storage] link has been connected to [storage/app/public].
```

BTW, `laravel` installed in subdomain 

storage link in `public` folder:

```
lrwxrwxrwx  1 my-site my-site 47 Sep 16 14:48 storage -> /home/my-site/public_html/next/storage/app/public
```

`filesystem.php` contains:
```php
<?php

return [
    'default' => env('FILESYSTEM_DISK', 'local'),

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'throw' => false,
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
            'throw' => false,
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
        ],

    ],


    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],

];
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
