### ISSUE TITLE
No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select count(*) as aggregate from "food_types" where "type"->>'ar' = وجبة الفطار and "id" <>  )

### ISSUE THREAD

**Issue by Barbar0sssa** [laravel/framework#44193]
- Laravel Version: 9
- PHP Version:8.1
- Database Driver & Version: postgres in heroku

### Description:

I built a laravel project, and i made it to work with multible language Ar, En so i make column in my table on database take array {ar, en} by using spatie package, it works on my local server xampp , but when i upload my project on heroku my project works in regist and login, but when i add something in database this error occures , so what it is the solution of this problem,,

SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying ->> unknown LINE 1: ...unt() as aggregate from "food_types" where "type"->>'ar' = ... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select count() as aggregate from "food_types" where "type"->>'ar' =وجبة الفطار and "id" <> )

**Comment by rodrigopedra** [comment]
Please read:

https://laravel.com/docs/9.x/contributions#support-questions

Likely the database version available in heroku is not the same you have installed on your local machine. If you have locally MySQL 8 and heroku provides MySQL 5.7, most of JSON functions won't work.

If it is working on your local machine, it is not a Laravel issue. Please use the issue tracker only for bugs, as described on the link above, and also as described on the screen when you click "new issue".

**Comment by Barbar0sssa** [comment]
ok sir, but know what can i do ?i am a beginner

> Please read:
> 
> https://laravel.com/docs/9.x/contributions#support-questions
> 
> Likely the database version available in heroku is not the same you have installed on your local machine. ~If you have locally MySQL 8 and heroku provides MySQL 5.7, most of JSON functions won't work~. EDIT I missed you are using Postgres, evenb though check if there is a version mismatch between your local install and heroku.
> 
> If it is working on your local machine, it is not a Laravel issue. Please use the issue tracker only for bugs, as described on the link above, and also as described on the screen when you click "new issue".

ok sir, but know what can i do ?i am a beginner

**Comment by rodrigopedra** [comment]
> ok sir, but know what can i do ?i am a beginner

Read the docs, and post the question in one of the support forums? There are plenty of people willing to help in the support forums.

Read the issue opening page and do not post support questions on the issue tracker?

Being a beginner is a better reason to always follow the rules =)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
