### ISSUE TITLE
problem parsing .env file

### ISSUE THREAD

**Issue by valentinomariotto** [laravel/framework#44206]
- Laravel Version: 9.30.1
- PHP Version: 8.1.10
- Database Driver & Version: MariaDB 10

### Description:
`php artisan package:discover` fails, but **only** when called by `composer update` autoload
error:
```
> @php artisan package:discover --ansi

<comment>In LoadConfiguration.php line 66:</comment>
<error>    </error>
<error>    </error>
<error>    </error>

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

Looking in LoadConfiguration.php it turns out that this exception is thrown when the program is unable to read the config/app.php file. But I'm unable to spot the issue.

Things I tried:
- converting my .env from UTF8 to ANSI (I'm on linux): no effect.
- replacing the line endings from \n to \r\n: no effect
- replacing my .env file with .env.example: error changed:
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
```
> @php artisan package:discover --ansi
The environment file is invalid!
Failed to parse dotenv file. Encountered an invalid name at [APP_NAME].
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```
- using double quotes in .env.example APP_NAME="thename": back to the original error: so at least I get more meaningful errors by using no quotes or single quotes instead of the double quotes.

What is going on?

### Steps To Reproduce:

?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by valentinomariotto** [comment]
might it be that php 8.1.10 is too new?
