### ISSUE TITLE
`model:show` does not honor composer autoload

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#44212]
- Laravel Version: 9.30.1
- PHP Version: 8.1.9
- Database Driver & Version: pgsql 14

### Description:
First off, thanks @jessarcher for your work on the model show command! It's very convenient and I expect to get a lot of mileage from it.

`model:show` seems to only search for models in the `App\` directory (unless there's a config variable I missed) instead of honoring composer's autoload. I'm not sure if this is the desired behaviour or not (for instance, Tinker will auto-alias a model found in autoload), but my application is organized by (sub)domains and it quickly becomes inconvenient to type out the full namespace that's several levels deep.

If this is not a bug, would you please consider honoring autoload (like Tinker) for convenience? 

Thanks!

### Steps To Reproduce:
Try to list the details for any model not in `App\` but available through composer autoloading.
`artisan model:show <Model>`

**Comment by driesvints** [comment]
Hi there. Right now this is indeed limited to the App namespace. Feel free to attempt a PR to change that.

**Comment by jbrooksuk** [comment]
It's worth noting here that you may pass through the entire namespace, for example, `artisan model:show Laravel\\Cashier\\Subscription`
