### ISSUE TITLE
Enum route binding: Default values not working

### ISSUE THREAD

**Issue by levu42** [laravel/framework#44249]
- Laravel Version: 9.31.0
- PHP Version: 8.1.10
- Database Driver & Version: irrelevant

### Description:

Binding enums to route parameters works fine (yay!) but it doesn't work with default values given in the controller function signature:

`public function index(PostsStatus $status = PostsStatus::published)`. See the steps to reproduce below.

I found a (not-nice) workaround, by doing `app()->bind(PostsStatus::class, fn() => PostsStatus::published)` - but this is then a global default for the whole app instead of a default parameter for a route.

### Steps To Reproduce:

When creating a route with enum route binding ([see example repository](https://github.com/levu42/enum-route-binding-bug-report/commit/6372f55aee727b39dc8d5f501881f177fc55c2ec)):

```php
// routes/web.php
Route::get('/posts/{status?}', [PostsController::class, 'index']);

//app/Controllers/PostsController.php
public function index(PostTypeEnum $status = PostTypeEnum::Published) {}
```

It works fine with `/posts/drafts` - `$status` is correctly `PostTypeEnum::Drafts`. But when I try to call `/posts/`, it gives me an `TypeError` with the message

> App\Http\Controllers\PostsController::index(): Argument #1 ($status) must be of type App\PostTypeEnum, null given, ...

**Comment by gthedev** [comment]
I am getting the same result as well.

In `src/Illuminate/Routing/RouteDependencyResolverTrait.php` on line `80` you can see it resolving the value to `null` if default value is is available. Replacing that `null` with `$parameter->getDefaultValue()` fixes this issue, however, might have side-effects in Model Route Binding as I haven't tested that yet.

**Comment by driesvints** [comment]
Hi there. This is unsupported at the moment. Feel free to attempt a PR but indeed keep in mind other route model binding situations like @gthedev mentioned.

**Comment by levu42** [comment]
@driesvints I attempted a PR in #44255 that shouldn't have any influence on route model binding.
