### ISSUE TITLE
I think I see an error in the PHPDoc for function sortBy in Collection

### ISSUE THREAD

**Issue by rationalthinker1** [laravel/framework#44259]
I think it's missing a `>` for the first array definition.
https://github.com/laravel/framework/blob/3f3a57ae87f76aa69d8122acb6d367d03c795fc9/src/Illuminate/Collections/Collection.php#L1324

from 
```php
@param  array<array-key, (callable(TValue, TKey): mixed)|array<array-key, string>|(callable(TValue, TKey): mixed)|string  $callback
```
to
```php
@param  array<array-key, (callable(TValue, TKey): mixed)>|array<array-key, string>|(callable(TValue, TKey): mixed)|string  $callback
```

**Comment by driesvints** [comment]
Can you send in a pr?

**Comment by rationalthinker1** [comment]
https://github.com/laravel/framework/pull/44262
Did I do it correctly?
