### ISSUE TITLE
APP_URL doesn't work as expected

### ISSUE THREAD

**Issue by xm-yang** [laravel/framework#44270]
- Laravel Version: 9.22.1
- PHP Version: 8.1.8
- Database Driver & Version:

### Description:
In .env file, I set:
APP_ENV=https://example.com

In the page navigation bar, I generate urls with url('path') function.
When user visit my site via https://**www**.example.com, I expect the navigation bar will send user to https://example.com, as configured in .env
But to my surprise, the url('path') actually return url with www.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
