### ISSUE TITLE
X-Forwarded-For ignored

### ISSUE THREAD

**Issue by NilLlisterri** [laravel/framework#44271]
- Laravel Version: 9.17.0
- PHP Version: 8.0.21

### Description:
Our website is behind a load balancer. In order to make `request()->ip()` return the user's IP, I've added the `X-Forwarded-For` header in the Nginx configuration. It is received correctly by PHP (`$_SERVER["X-Forwarded-For"]` is the correct client IP).

I've set the TrustProxies Middleware $proxies to `*`, and `$headers = Request::HEADER_X_FORWARDED_FOR;`, but `request()->ip()` keeps returning the client IP.

While digging, I've found that [getTrustedValues@Request.php](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpFoundation/Request.php#L1957) searches the header in its `$headers` variable, which is populated from certain values from the server variables ([here](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpFoundation/ServerBag.php#L26)).
After reviewing this code, I've modified the Nginx server to set the `HTTP_X-Forwarded-For` header instead of `X-Forwarded-For`.

This made the `request()->ip()` finally display the correct IP, but left me wondering if this is intended and not a dirty trick. In the [trusted proxies documentation](https://laravel.com/docs/9.x/requests#configuring-trusted-proxies) it seems it should work with the `X-Forwarded-For` header.

Thanks for any help!

**Comment by brunogaspar** [comment]
Yup, i had this exact same problem and had to adjust Nginx config as well for that same value, which was quite hard to figure out at first :)

**Comment by taylorotwell** [comment]
If something needs to be changed in the framework we would welcome a PR!

**Comment by fideloper** [comment]
Hi!

You'll need to share some more information about your configuration to get more help I think. This doesn't sound like a Laravel issue tho.

1. Is Nginx your load balancer or is it something hosted from a service, perhaps AWS?
2. Does the load balancer not add `X-Forwarded-*` headers itself?

If the load balancer is setting those headers, then Nginx should be seeing and transforming those headers for PHP to see automatically (in `$_SERVER['HTTP_X_Forwarded_For']`, which Laravel/Symfony classes then read/transform into a Request object).

**Some general info:**

When Nginx is sending requests over fastcgi to PHP-FPM, it's not setting headers but instead setting fastcgi "parameters". 

In PHP, all HTTP headers start with `HTTP_`, and they populate the `$_SERVER` global.

So, to add an HTTP header that PHP-FPM sees, it usually looks like this:

```
location ~ \.php$ {
    fastcgi_param HTTP_X_FORWARDED_FOR $whatever;
    // and so on...
}
```

Note that this means when you say:

> It is received correctly by PHP ($_SERVER["X-Forwarded-For"] is the correct client IP).

That's actually incorrect - `$_SERVER` should have a value of `$_SERVER["HTTP_X_Forwarded_For"]`


So, overall, something sounds funky in your configuration. Having to add `HTTP_` in your header sounds like it's related to getting the correct value into PHP (which Laravel would then read). 

Are you using PHP-FPM? Perhaps you're using Octane?

**Comment by driesvints** [comment]
Thanks @fideloper. Feel free to continue to discuss the issue here 👍

**Comment by NilLlisterri** [comment]
Thanks for the detailed answer @fideloper,

As you guessed, I'm using fastcgi and PHP-FPM.

Having to add the `HTTP_` part in the `fastcgi_param HTTP_X-Forwarded-For $proxy_protocol_addr;` line, so it can be detected by Laravel, was what felt hacky.

What I was missing was:
> having to use fastcgi_param and prepending the header with HTTP_ is totally normal.

I feel better knowing that. I've been trying to find a mention of this anywhere in the docs with no luck, but I guess its something you learn along the way.

Thanks everyone!
