### ISSUE TITLE
Symfony process passes ENV variables to child process.

### ISSUE THREAD

**Issue by matt-h** [laravel/framework#44278]
Symfony process passes ENV variables to child process.

- Laravel Version: 9.28.0
- PHP Version: 8.1.10
- Database Driver & Version: 10.9.3-MariaDB (any is affected)

### Description:

I had noticed this awhile ago when using Symfony processes but wanted to bring it up now with the attention of the [`Process` convenience layer](https://github.com/laravel/framework/pull/43977) being added. When this addition lands Symfony process will probably get more use in Laravel.

Right now when using Symfony processes all of the Laravel environment variables get passed through to the child process.

### Steps To Reproduce:

You can see that with this example:
```php
// Symfony processes example.
$process = new \Symfony\Component\Process\Process(['env']);
$process->run();
dd($process->getOutput());
// Or Facade example.
$result = \Illuminate\Support\Facades\Process::run('env');
dd($result->output());
```

For most things, this probably isn't much of an issue, although `DB_PASSWORD` is included in the environment.

What I did find was an issue was it made it impossible to run Laravel artisan command from one application inside of another. You run the process command in Application One calling Application Two's artisan command. And as you can see from the result, even though it runs the code from Application Two, it uses the environment and database from Application One.

```php
// Symfony processes example.
$process = new \Symfony\Component\Process\Process(['php', '/path/to/another/laravel/app/artisan', 'db:show']);
$process->run();
dump($process->getOutput());
$process = new \Symfony\Component\Process\Process(['php', '/path/to/another/laravel/app/artisan', 'about']);
$process->run();
dump($process->getOutput());
// Or Facade example
$result = \Illuminate\Support\Facades\Process::run('php /path/to/another/laravel/app/artisan db:show');
dump($result->output());
$result = \Illuminate\Support\Facades\Process::run('php /path/to/another/laravel/app/artisan about');
dump($result->output());
```

### Resolutions:

I'm not sure if this should be changed in Symfony's Process in the `getDefaultEnv` function, although any change there would be a breaking change. With Laravel's process facade not landed yet it is probably best to address it there before any breaking changes are needed.

My assumption is that the Laravel environment variables would not need to be passed to the child process in most cases so should be excluded by default and when they are needed they can be added with the `setEnv` function on `Process`.

My workaround so far was to extend Symfony process and remove the Laravel environment variables, although this is just a hack and is not a good solution for everyone's environment.

```php
<?php

namespace App\Support;

use Dotenv\Dotenv;
use Illuminate\Support\Facades\File;
use Symfony\Component\Process\Process as SymfonyProcess;

class Process extends SymfonyProcess
{
    private $laravel_env = null;
    private $backup_env = null;
    private $backup_server = null;

    public function start(callable $callback = null, array $env = [])
    {
        $this->sanitizeEnv();

        parent::start($callback, $env);

        $this->restoreEnv();
    }

    public function sanitizeEnv()
    {
        if (is_null($this->laravel_env)) {
            $this->laravel_env = Dotenv::parse(File::get(base_path('.env')));
        }
        $this->backup_env = $_ENV;
        $this->backup_server = $_SERVER;
        foreach ($this->laravel_env as $key => $_value) {
            unset($_ENV[$key]);
            unset($_SERVER[$key]);
        }
    }

    public function restoreEnv()
    {
        $_ENV = $this->backup_env;
        $_SERVER = $this->backup_server;
    }
}
```

**Comment by nunomaduro** [comment]
We've taken your feedback in consideration. By default, Laravel processes inherit all the env vars defined in your system / application, and the same happens when regular Symfony processes.

We see our Process facade as an API for the most common use cases. For more advanced scenarios, such as the case your describe, we advice you to use the Symfony Process class directly, and unset the system / application environment variables using something like so:

```php
$process = new Process(['...'], null, [
    'APP_ENV' => false,
    'CUSTOM_ENV' => false,
]);
```

**Comment by matt-h** [comment]
Thanks for your your consideration here. I agree it is more of an edge case and won't affect most use cases of it.

I brought it up since you are making Process a first class part of Laravel now and not just using Symfony process as a dependency and it may unknowingly leak `.env` variables to other processes.

Thanks for the example as well, that will help me improve my workaround that I'm already using.
