### ISSUE TITLE
There are have an error after this changes Fixes artisan serve command with PHP_CLI_SERVER_WORKERS environment variable #44204

### ISSUE THREAD

**Issue by geldibayev** [laravel/framework#44282]
- Laravel Version: 9.31.0
- PHP Version: 8.1.5
- Database Driver & Version:

### Description:
When I run php artisan serve command I get the following errors
https://stackoverflow.com/questions/73829417/how-can-i-fix-the-error-undefined-array-key-1-on-laravel?noredirect=1#comment130365550_73829417

**Comment by nunomaduro** [comment]
Can you please provide more information, such as the operating system and the output of the `dump($regex, $line, $matches);` variables?

**Comment by driesvints** [comment]
We don't support microsoft Windows 8.1, sorry. Please upgrade to Windows 11.

**Comment by inxty** [comment]
@driesvints @taylorotwell can the information of the supported Windows version be added into official documentation?
