### ISSUE TITLE
Send mail by tinker not working

### ISSUE THREAD

**Issue by flaviolopesw** [laravel/framework#44284]
- Laravel Version: 8.75
- PHP Version: 8.1

### Description:
I'm testing sending email through Tinker, but it doesn't work. I also tested a command but for sending email, without success.
Note: it works with mailhog, but when I use the production email service it doesn't work.

### Steps To Reproduce:
Create a new project with laravel 8.75, install or sail.
Create a Mailable with the command 'make:mail YourNameMail'.
Create a view with 'Hello world' in the content.
Create a command with the command 'make:command YourNameCommand'.
Change the signature of the command you created 'example:command', put the following script in the command:

$to = [
            [
                'email' => 'your.email@teste.com',
                'name' => 'Your Name',
            ]
        ];
Mail::to($to)->send(new YourNameMail);

Execute command with sail, 'sail artisan example:command'.

**Comment by nunomaduro** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by flaviolopesw** [comment]
@nunomaduro Hello!

I believe it is a bug, because if the routine is started via the web, the email is sent, but if it is a routine that is started by a command, the email is not sent.

However, I already started the discussion about laracast, here is the link: https://laracasts.com/discuss/channels/laravel/send-mail-by-tinker-not-working

**Comment by flaviolopesw** [comment]
I found out what was going on and came back to give feedback here. In fact what happened was that Outlook itself was blocking the receipt of emails.
