### ISSUE TITLE
Unable to run aggregate queries (withSum, etc.) for pivot table columns on self-referencing many-to-many relations

### ISSUE THREAD

**Issue by kayrunm** [laravel/framework#44285]
- Laravel Version: 9.31.0 (from what I can see, also on 8.x)
- PHP Version: 8.1.10 (also on 7.4.x)
- Database Driver & Version: MySQL 8.0.30, SQLite 3.39.3

### Description:

An SQL error occurs when trying to add an aggregate (e.g. `withSum`) for a pivot column on a many-to-many relation that has both sides of the relationship from the same table.

For example, in an application which contains a `transactions` table, I may be able to have positive (+) and negative (-) transactions and I am able to allocate positive transactions to a negative transaction. Take the following list of transactions

| ID | Description |   Amount |
|----|-------------|---------:|
| 1  | Invoice 1   |  -500.00 |
| 2  | Invoice 2   | -1000.00 |
| 3  | Invoice 3   |  -200.00 |
| 4  | Payment 1   |  1700.00 |

In this example, I want to allocate:
* 500 from Payment 1 to Invoice 1
* 1000 from Payment 1 to Invoice 2
* 200 from Payment 1 to Invoice 3

I can achieve this through a `transaction_transaction` pivot table with an `amount` column signifying how much was allocated from one transaction to another. 

### Steps To Reproduce:

In my use case, I want to be able to allocate different amounts of Payment 1 across the invoices. I would end up with an intermediate table like this:

| allocated_from | allocated_to |  amount |
|----------------|--------------|--------:|
| 4              | 1            |  500.00 |
| 4              | 2            | 1000.00 |
| 4              | 3            |  200.00 |

And two relationships on my `Transaction` model like so:
```php
    public function allocatedTo(): BelongsToMany
    {
        return $this->belongsToMany(
            Transaction::class,
            'transaction_transaction',
            'allocated_from_id',
            'allocated_to_id',
        )->withPivot('amount');
    }

    public function allocatedFrom(): BelongsToMany
    {
        return $this->belongsToMany(
            Transaction::class,
            'transaction_transaction',
            'allocated_to_id',
            'allocated_from_id',
        )->withPivot('amount');
    }
```

When running the following:
```php
$result = Transaction::query()
    ->withSum('allocatedTo as total_allocated', 'transaction_transaction.amount')
    ->first();
```

I get the following error in SQLite (I get a similar one in MySQL as well)
```
Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 1 no such column: laravel_reserved_0.transaction_transaction.amount (SQL: select "transactions".*, (select sum("laravel_reserved_0"."transaction_transaction"."amount") from "transactions" as "laravel_reserved_0" inner join "transaction_transaction" on "laravel_reserved_0"."id" = "transaction_transaction"."allocated_to_id" where "transactions"."id" = "transaction_transaction"."allocated_from_id") as "total_allocated" from "transactions" limit 1)
```

The problem seems to come from [line 625–627 in `QueriesRelationships`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L625):
```php
                $hashedColumn = $this->getQuery()->from === $relation->getQuery()->getQuery()->from
                                            ? "{$relation->getRelationCountHash(false)}.$column"
                                            : $column;
```

Because the current query (`$this->getQuery()`) is for the `ledger_entries` table, and the relation query's base (`$relation->getQuery()->getQuery()`) is also for `ledger_entries`, we end up with `laravel_reserved_0` prefixed onto the column provided (`transaction_transaction.amount`).

**Note:** This works totally fine if the two sides of the many-to-many are different tables. You can see an example of this in my reproduction repository,

## Repo
https://github.com/kayrunm/laravel-sum-pivot-issue

I have provided a passing test case for when this is done for two different tables, and a failing test case for my situation. You can find this in [ExampleTest.php](/blob/main/tests/Feature/ExampleTest.php)

**Comment by kayrunm** [comment]
I think I may have a solution for this, so I will try and work one out and if so, reference this issue with a PR.

**Comment by driesvints** [comment]
Let's see how the PR goes 👍
