### ISSUE TITLE
[9.x] `db:seed` command doesn't show seeder info when using with `--class` argument

### ISSUE THREAD

**Issue by aneeskhan47** [laravel/framework#44294]
- Laravel Version: 9.31.0
- PHP Version: 8.1.8
- Database Driver & Version: MariaDB 10.3.31

### Description:

When running `db:seed` with `--class` flag. it doesn't show info about seeder class e.g 'time elapsed' as it does in `migrate --seed`.

**Issue:**
![image](https://user-images.githubusercontent.com/30714223/192150551-12702527-c857-4397-9d6a-1fb7140a58dd.png)

**My BigRecordSeeder class:**
![image](https://user-images.githubusercontent.com/30714223/192150653-07c64b2b-574b-4c31-bc51-129f4c6cb5fb.png)

**It should display info about the seeder class just like in `migrate --seed`:**
![image](https://user-images.githubusercontent.com/30714223/192150720-f714bfe0-01c8-44e6-a398-1526fbc8fd34.png)

### Steps To Reproduce:

Run `php artisan db:seed --class=YourSeederClass`

**Comment by aneeskhan47** [comment]
ping @nunomaduro. sorry to ping you but does this can be caused due to the new artisan output look?

**Comment by driesvints** [comment]
This seems like a feature request. Feel free to attempt a PR if you like.
