### ISSUE TITLE
"str_getcsv" convert chinese has error

### ISSUE THREAD

**Issue by Sun-FreePort** [laravel/framework#44317]
I know this Issue: https://github.com/laravel/framework/issues/29617.

But in **feature test**, use `setlocale(LC_ALL, 'zh_CN.UTF-8');` or `setlocale(LC_ALL, 'zh_CN.UTF8');` is not working -- at `index.php`.

You can use `str_getcsv("\"未定义\",\"良品\",\"二手\",\"瑕疵\",\"良品无吊牌\"")` to test it error.

---

https://github.com/laravel/framework/blob/8a02e8fc5ad22e47cc0ebec075d6ff7edf0e7b8c/src/Illuminate/Validation/ValidationRuleParser.php#L275-L285

Why not use `explode()`?

I can't undestand necessity by use it.

thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
