### ISSUE TITLE
Scoped Storage drivers returning incorrect url with url() function

### ISSUE THREAD

**Issue by iotronlab** [laravel/framework#44327]
- Laravel Version: 9.32.0
- PHP Version: 8.1.4
- Database Driver & Version:

### Description:
Scoped storage driver cannot be used out of the box as "league/flysystem-path-prefixing": "^3.3", is in require-dev and not in require. So it isn't installed on default laravel installation.

Solution: Update the doc to include installation of driver when using scoped drivers.
```
composer require league/flysystem-path-prefixing
```

Scoped drivers on local not prefixing the prefix-path to base disk path in Storage::url() function. So it returns incorrect url for scoped local drivers.
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemAdapter.php#L621
```
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
            'throw' => false,
        ],

        'public-blogs' => [
            'driver' => 'scoped',
            'disk' => 'public',
            'prefix' => 'blogs',
        ],

```
```
    public function url($path)
    {
        $adapter = $this->adapter;

        if (method_exists($adapter, 'getUrl')) {
            return $adapter->getUrl($path);
        } elseif (method_exists($this->driver, 'getUrl')) {
            return $this->driver->getUrl($path);
        } elseif ($adapter instanceof FtpAdapter || $adapter instanceof SftpAdapter) {
            return $this->getFtpUrl($path);
        } elseif ($adapter instanceof LocalAdapter) {
            return $this->getLocalUrl($path);
        } else {
            throw new RuntimeException('This driver does not support retrieving URLs.');
        }
    }
```
### Steps To Reproduce:
Default Laravel installation v.9.30^

**Comment by frankdejonge** [comment]
Ill have a look tonight :)
