### ISSUE TITLE
`dd` source file shows compiled view file instead of original one.

### ISSUE THREAD

**Issue by aneeskhan47** [laravel/framework#44332]
- Laravel Version: 9.32.0
- PHP Version: 8.1.8
- Database Driver & Version: N/A

### Description:

When using `dd` in a view file. the source file line of it is displayed of a compiled view file instead of the original one:

![image](https://user-images.githubusercontent.com/30714223/192633531-b7dcfb27-ff3e-42f7-a4ff-99e2897783aa.png)
 
### Steps To Reproduce:

1. Make sure you are on Laravel 9.32.0 version.
2. Add dd in a view file like: 
`@php 
dd('hello from view'); 
@endphp`
3. See the output

**Comment by aneeskhan47** [comment]
@ping @nunomaduro

**Comment by nunomaduro** [comment]
https://github.com/laravel/framework/pull/44347
