### ISSUE TITLE
Task Scheduling: twiceDaily

### ISSUE THREAD

**Issue by sn-sharma** [laravel/framework#44337]
- Laravel Version: 9.11
- PHP Version: 8.4
- Database Driver & Version: MariaDB 10.6

### Description:
The following schedule command is working fine. Running the task daily at 1:00 & 13:00.

`$schedule->command('foo:bar')->withoutOverlapping()->twiceDaily(1, 13);`

But when I am trying to schedule the following command. It is not working.

`$schedule->command('foo:bar')->withoutOverlapping()->twiceDaily('01:30', '13:30');`

**It returns the following error.** 

[2022-09-28 06:15:02] local.ERROR: Invalid CRON field value 01:30,13:30 at position 1 {"exception":"[object] (InvalidArgumentException(code: 0): Invalid CRON field value 01:30,13:30 at position 1 at /home/public_html/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php:231)

### Steps To Reproduce:

1. Create a schedule for twice daily for times 1:30 & 13:30. 
2. Let the command execute. 
3. Check the Laravel log.

**Comment by GC-Mark** [comment]
This would work...

```php
$schedule->command('foo:bar')->withoutOverlapping()->twiceDailyAt(1, 13, 30);
```

Your example would be hard to allow for as how would the cron expression look if you specified different minutes on each hour.

```php
$schedule->command('foo:bar')->withoutOverlapping()->twiceDaily('01:45', '13:30');
```

**Comment by sn-sharma** [comment]
@GC-Mark You wanna say they, I can't use hour and minute both in `twiceDaily`. Right? I have to do something like that

`$schedule->command('foo:bar')->withoutOverlapping()->twiceDailyAt(1, 13, 30);`

**Comment by GC-Mark** [comment]
Correct 👍

**Comment by sn-sharma** [comment]
@GC-Mark I think this one is the limitation with CRON configuration. Not an issue with Laravel. Right?

**Comment by GC-Mark** [comment]
Basically, yes.

Laravel could support with some changes...
```php
$schedule->command('foo:bar')->withoutOverlapping()->twiceDaily('01:30', '13:30');
```
...but it would open up the possibility for developers to pass parameters that would not convert to a CRON expression

**Comment by sn-sharma** [comment]
@GC-Mark Got your point. Thanks

**Comment by driesvints** [comment]
Seems like this is a feature request. Feel free to attempt a PR 👍
