### ISSUE TITLE
Laravel Passport for multiple auth security problem

### ISSUE THREAD

**Issue by hesami** [laravel/framework#44345]
- Laravel Version: 9.19
- PHP Version: 8.1.0
- Laravel/passport: ^11.2
### Description:
Laravel Passport returns true for several different guards with different tables and the same ID.
For example, if an admin has ID 1 in the admins table and a user has ID 1 in the users table, the user can identify himself as an admin during authentication.

If a normal user logs into the system with ID 1 and gets an access token, he can access the admin user account number 1! And in the same way, user number 2 can access the account of admin number 2!!!!!

Is this a bug or do we have to use only one table for all users when using Laravel Passport?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
