### ISSUE TITLE
RedisStore serializer type inconsistencies check 

### ISSUE THREAD

**Issue by danielpopdan** [laravel/framework#44344]
- Laravel Version: >=6
- PHP Version: >=4.2

### Description:
The [validation for serializer ](https://github.com/laravel/framework/blob/5dd58d428c64811b70ecba57a75e77c136578410/src/Illuminate/Cache/RedisStore.php#L332) is type inconsistent.  The `is_numeric` function validates if a value is numeric without checking for a specific type, the accepted type is mixed. This means that a string representing a number will return true. However, the `is_nan` check is only accepting float. Currently, the serialization is passing and not throwing an error because strict types are not enforced.

### Steps To Reproduce:
Have a numeric value represented as a string, ex: `$value = "123";'

`is_numeric($value) && ! in_array($value, [INF, -INF]) && ! is_nan($value)` will return true, because it is not enforcing types, however this can break if `strict_types` are set or in possible future PHP versions. 

### Proposed solutions:
Convert the value to float if it is a numeric value. See https://github.com/laravel/framework/pull/44348.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by danielpopdan** [comment]
Hello @driesvints, I may have misunderstood how to specify the Laravel version. The code was introduced in Laravel 6, but it is still the same in the codebase in the currently supported version, Laravel 9.

**Comment by driesvints** [comment]
I don't see an issue here sorry.
