### ISSUE TITLE
max_digits validation rule does not accept negative numbers

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#44358]
- Laravel Version: 9.32.0
- PHP Version: 8.1.8
- Database Driver & Version:

### Description:

Validating that the max_digits of a negative number always fails regardless of length.

### Steps To Reproduce:

```php
use Illuminate\Support\Facades\Validator;

Validator::make(['amount' => -100], ['amount' => 'max_digits:6000'])->validate();
// The amount must not have more than 6000 digits.
```

**Comment by driesvints** [comment]
Digits only accept positive numbers.
