### ISSUE TITLE
Rule::requiredIf validation string

### ISSUE THREAD

**Issue by ronssij** [laravel/framework#44361]
- Laravel Version: 9.28.0
- PHP Version: 8.1.6
- Database Driver & Version: MYSQL 8.0.29

### Description:
The `Rule::requiredIf()` does not use the right validation string. where it should use the `requierd_if` validation string not the `required`.

[required_if:anotherfield,value,...](https://laravel.com/docs/9.x/validation#rule-required-if)

if you want to change the validation message() it should anticipate the eg. `'email.required_if' => 'blah blah blah'`

![image](https://user-images.githubusercontent.com/24932380/192935233-c0cdb5e0-8c70-4dc1-a090-4c3464014493.png)

### Steps To Reproduce:
- Create a custom validation request.
- user the `Rule` class with `Rule::requiredIf()`.
   eg. 
   ```
   'email'        => [Rule::requiredIf(!$this->filled('phone_number') && !$disable)],
   'phone_number' => [Rule::requiredIf(!$this->filled('email') && !$disable)]
   ```
if you want to change the validation  message on `message()` it should anticipate the eg. `'email.required_if' => 'blah blah blah'`

**Comment by nuernbergerA** [comment]
Hey @ronssij 

`required_if` as a string version works completely different then `Rule::requiredIf()`.

`required_if` will always be included in the "compiled" rules array.
`Rule::requiredIf()` will only include a `required` in the "compiled" rules array if the condition is true.

so you have to you `'email.required' => 'blah blah blah'` to control the message.

**Comment by driesvints** [comment]
See the answer above. 

Thanks @nuernbergerA
