### ISSUE TITLE
$model->getMorphClass() displays QCN instead of my custom name

### ISSUE THREAD

**Issue by ta369e** [laravel/framework#44372]
- Laravel Version: 9.32.0
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 8

### Description:
my morphmap array looks like overwritten to an empty array for some reason.

when creating new records in database, morphmap custom names are used
but when trying to retrieve these relations, QCN is used! So i always get null in this case

AppServiceProvider.php
```
public function boot()
    {
        if (! app()->environment('local')) {
            URL::forceScheme('https');
        }

        Relation::enforceMorphMap([
            'managers' => 'App\Models\Manager',
        ]);
    }
```

Entity.php Model
```
public function owner () 
     {
         return $this->morphTo();
     }
```    

Manager.php
```
public function entity()
    {
        return $this->morphOne(Entity::class, "owner");
    }
```    

I have run and made sure appserviceprovider is executed
```
php artisan cache:clear
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
