### ISSUE TITLE
PostgreSQL updateFrom() is not applying global scopes

### ISSUE THREAD

**Issue by peanutsmcgee** [laravel/framework#44380]
- Laravel Version: 9.22.1
- PHP Version: 8.0.21
- Database Driver & Version: PostgreSQL 13.2

### Description:
When performing an update using `->updateFrom()` (as opposed to `->update()`), global scopes are not being applied to the query.

It looks like normally the eloquent method `Illuminate\Database\Eloquent\Builder::update()` is called, which applies scopes and then forwards to `Illuminate\Database\Query\Builder::update()`. But there is no `Illuminate\Database\Eloquent\Builder::updateFrom()` method, so calling `->updateFrom()` goes directly to `Illuminate\Database\Query\Builder::updateFrom()`, without having the global scopes applied.

### Steps To Reproduce:

1. Define a global scope on a model.
2. Run an `updateFrom` query using that model.

**Comment by driesvints** [comment]
Thanks. I sent in a PR for this: https://github.com/laravel/framework/pull/44391
