### ISSUE TITLE
Artisan db command fails when using read/write hosts

### ISSUE THREAD

**Issue by necrogami** [laravel/framework#44383]
- Laravel Version: 9.32.0
- PHP Version: 8.1.10
- Database Driver & Version: mysqlnd

### Description:
When executing the `php artisan db` console command while having read and write hosts setup in `config/database.php` it returns this error: 
```
╰─ﬀ php artisan db

   ErrorException

  Undefined array key "host"

  at vendor/laravel/framework/src/Illuminate/Database/Console/DbCommand.php:141
    137▕      */
    138▕     protected function getMysqlArguments(array $connection)
    139▕     {
    140▕         return array_merge([
  ➜ 141▕             '--host='.$connection['host'],
    142▕             '--port='.$connection['port'],
    143▕             '--user='.$connection['username'],
    144▕         ], $this->getOptionalArguments([
    145▕             'password' => '--password='.$connection['password'],

      +16 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

### Steps To Reproduce:

1. Setup mysql to use read and write hosts
2. execute `php artisan db`

**Comment by necrogami** [comment]
I understand that i can select --read or --write but it should throw a warning or a better error in my opinion if there's no default host and only using read/write as exampled here: https://laravel.com/docs/9.x/database#read-and-write-connections

**Comment by necrogami** [comment]
Or select read by default

**Comment by driesvints** [comment]
Thanks. We added a more descriptive message for this.
