### ISSUE TITLE
FTP Filesystem sends wrong FTP commands that leads to "550 Filename invalid" error

### ISSUE THREAD

**Issue by msm81** [laravel/framework#44387]
- Laravel version: 9.26.1
- PHP version: 8.0
- Browser: Google Chrome 105.0.5195.128 (Official Build) (64-bit)
### Description:
When attempting to upload something using the functions provided by the framework, a strange behavior will be seen from the vision of log file in the FTP Server.
### Current behavior:
FTP Commands sent from the Laravel application:
```
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 230 Logged on
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> PASV
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 227 Entering Passive Mode (127,0,0,1,200,119)
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> NOOP
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 200 OK
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> CWD
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 250 Broken client detected, missing argument to CWD. "/" is current directory.
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> CWD test
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 250 CWD successful. "/test" is current directory.
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> NOOP
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 200 OK
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> CWD
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 250 Broken client detected, missing argument to CWD. "/test" is current directory.
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> TYPE I
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 200 Type set to I
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> STOR test/sample.jpg
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 550 Filename invalid
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> QUIT
(000024)07/07/1401 23:43:35 p.m - admin (127.0.0.1)> 221 Goodbye
```
### Expected behavior:
FTP commands sent from native PHP:
```
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 230 Logged on
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> CWD test
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 250 CWD successful. "/test" is current directory.
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> TYPE I
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 200 Type set to I
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> PORT 127,0,0,1,210,206
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 200 Port command successful
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> STOR sample.jpg
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 150 Opening data channel for file transfer.
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 226 Transfer OK
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> QUIT
(000029)08/07/1401 00:26:24 a.m - admin (127.0.0.1)> 221 Goodbye
```
--------------
Here we have two major notes to improve + one critical error:
1. Why Laravel keeps using `NOOP` as it's not necessary because those commands are executed after each other without latency. (`NOOP` is used to keep the connection alive)
2. We use `CWD` just for changing the directory and not print the current directory. Actually this command is also used instead of `PWD` in addition to it's main goal.
3. BUT the reason that produced the "**550 Filename invalid**" error is that here Laravel has used a full path ("STOR test/sample.jpg") instead of a filename ("STOR sample.jpg").
### Steps To Reproduce:
1. Create a FTP driver disk in `config/filesystems.php`.
2. Use `Storage::disk('ftp')->putFileAs('path/to', new File('path/to/the/file'), 'new-name.jpg');`

This leads to "ftp_fput(): Filename invalid" ErrorException which is because of the "550 Filename invalid" FTP error mentioned above.

**Comment by driesvints** [comment]
Our filesystem is a wrapper around flysystem which makes using file based operations universal for all storages. If you claim that the FTP implementation behaves differently from other storages then I think it's probably related to flysystem itself and not laravel. Can you please try a support channel first and then if that doesn't help the flysystem issue tracker?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
