### ISSUE TITLE
Updating symfony/http-foundation (v6.1.4  => v6.1.5) brokes file download

### ISSUE THREAD

**Issue by realtebo** [laravel/framework#44399]
- Laravel Version: 9.280
- PHP Version: 8.1.2
- Database Driver & Version: Not influent

### Description:

We upgraded from v9.27.0 => v9.28.0.

This syntax, note $headers, not works anymore

        $headers = [
            'Content-Type: application/pdf',
        ];

          . ...  . omissis ..

        return response()->file($pathToFile, $headers);

This only works now 

        $headers = [
            'Content-Type: application/pdf',
        ];

          . ...  . omissis ..

        return response()->file($pathToFile, $headers);

This is due to the upgrade from a symfony package

      symfony/http-foundation (v6.1.4 => v6.1.5)

Actual result is that downloading a pdf with a mimetype is not working anymore because we syy in the response an header "0" with value of   'Content-Type: application/pdf'

### Steps To Reproduce:

Go back until symfony/http-foundatio will back to 6.1.4. 

Use old syntax

Upgrade until  symfony/http-foundatio will upgrade to 6.1.5.

String array will no work any amore.
Only associative array works.

This is the guilty commit: https://github.com/symfony/symfony/commit/7023db1659313c3e51f1922e506c5fd289cfbfd7
I opened an issue on symfony also :  https://github.com/symfony/symfony/issues/47747

**Comment by driesvints** [comment]
Thanks for making us aware. We hope Symfony patches this soon.

**Comment by wouterj** [comment]
For information of other Laravel users ending up here instead of in the Symfony issue:

Passing the headers as a list (`['Content-Type: application/pdf']`) has never worked, an associative array (`['Content-Type' => 'application/pdf'])` works.

It appears 6.1.5 includes a bug in the automatic configuration of content-type. As the content-type header was never understood, code using this is relying on the automatic configuration.

**Comment by driesvints** [comment]
Thanks @wouterj. I don't think we document using it like that and if we do we'd be happy to correct those if anyone can find them.

**Comment by realtebo** [comment]
> For information of other Laravel users ending up here instead of in the Symfony issue:
> 
> Passing the headers as a list (`['Content-Type: application/pdf']`) has never worked, an associative array (`['Content-Type' => 'application/pdf'])` works.

Not true. We were  (guilty and wrongly) using it in 3 different projects and it worked (since a lot of time, about 2 year the oldest commit).

Anywhere, there is no documentation about HOW to send headers and I think laravel doc team should add a small example

**Comment by realtebo** [comment]
> Thanks @wouterj. I don't think we document using it like that and if we do we'd be happy to correct those if anyone can find them.

Yes, but also there is not documentation about the _right_ way to do it. There is no documentation about HOW to send headers and I think laravel doc team should add a small example

**Comment by wouterj** [comment]
> Not true. We were (guilty and wrongly) using it in 3 different projects and it worked (since a lot of time, about 2 year the oldest commit).

It has worked by the shear luck that the automatic content type algorithm produced the same content type as you were passing. Doing `$response->headers->allPreserveCaseWithoutCookies()` (which is what is send to the client) shows `0 => "Content-Type: application/json"` in any version of Symfony.

> I think laravel doc team should add a small example

I'm sure they welcome contributions :)

**Comment by realtebo** [comment]
I understand and I agree. 
We was 'lucky' ... no more lucky now

**Comment by realtebo** [comment]
>. Doing `$response->headers->allPreserveCaseWithoutCookies()` (which is what is send to the client) with the provided code example shows `0 => "Content-Type: application/json"` in any version of Symfony.

I have not clear in mind why.. but in previous version of pair laravel + httpfoundation it worked in a different way. 
But I hope this issue will help future googlers to avoid our mistake or fix if someone did same mistake we make: we surely copy/pasted something from somewhere and from somelucky it someworked ... :)

**Comment by ryanmortier** [comment]
Ran into this today. All my streamed PDFs look like this:

![image](https://user-images.githubusercontent.com/2053960/193659846-a5f3f911-1b10-40d0-8083-b379dc40b8fa.png)

**Comment by marin246** [comment]
Apparently, this should be fixed with the next symfony release: [Symfony Github](https://github.com/symfony/symfony/pull/47746)

Does anybody know when that will be relased?
