### ISSUE TITLE
Laravel auto clear session when submit form with large input

### ISSUE THREAD

**Issue by holdon1996** [laravel/framework#44418]
- Laravel Version: 5.5
- PHP Version: 7.4.15
- Database Driver & Version: Mysql 5.7

### Description:

When I submit the form with a large request and fail in validation then redirect with input => laravel auto clear session.
I tried changing column type "payload" in the session table from text to long text then it can handle success.

### Steps To Reproduce:

1. Submit the form with a large request.
2. When check validate => auto redirect with input large will be clear all session

Could you help me to check it?

**Comment by rodrigopedra** [comment]
Laravel 5.5 is unsupported. Please see the Support Policy:

https://laravel.com/docs/9.x/releases#support-policy

Also, if you try it on a supported version and the error still exists, please give more info, "large" input is very subjective and time consuming to reproduce -- how large is good enough to stop testing if the error is not reproducible?

It is better if you can provide a public repository that allows to reproduce the error quicker.

**Comment by holdon1996** [comment]
@rodrigopedra 
Sorry for my mistakes.
I tried with Laravel version 8.75 and it will be an error.
It's my repository that I have already tested.
https://github.com/holdon1996/session_laravel_error/tree/main/routes
Step1: Visit /test
Step2: Click submit button
=> Error payload in the session table

**Comment by rodrigopedra** [comment]
@holdon1996 

As you are using the database session driver the payload is limited to the size its column data type. And has you are redirecting back with the input, all the request payload is written to the session. When the data you want to store is larger than a database can store, the database usually errors out, thus not saving your session at all and rendering it invalid.

Change this line:

https://github.com/holdon1996/session_laravel_error/blob/cc5dcdfb3589172fa9f07766890e105d991debbb/database/migrations/2022_10_03_055636_create_sessions_table.php#L21

to either:

~~~php
$table->mediumText('payload');
// or
$table->longText('payload');
~~~

to allow supporting greater payload sizes.

If you are using MySQL you can find how big this data types' content can be here:

https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings

Other databases might support similar sizes for the equivalent data types, but it is better to check it before.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
