### ISSUE TITLE
BadMethodCallException: Method [loginUsingId] does not exist.

### ISSUE THREAD

**Issue by kali-kb** [laravel/framework#44439]
- Laravel Version: ^9.19
- PHP Version: 8.1.6
- Database Driver & Version: pgsql

Hello, I'm a laravel begginer and I'm facing a problem, the problem is that I was using the Auth facade to handle authentication and the framework is throwing a `BadMethodCallException: Method [loginUsingId] does not exist.`  error when i call loginUsingId method on Auth like `Auth::loginUsingId($id)` by using an actual user id that exists in the database, I double checked the documentation and the method exists, so any help would be appreciated, here is the code.

![code](https://user-images.githubusercontent.com/78846980/193633306-47176d92-7c81-45f6-ac9b-8dc936a4a683.jpg)

Stack trace

![stack-trace](https://user-images.githubusercontent.com/78846980/193633239-985a645b-1f00-4f93-9e50-ed3651bfffa4.png)

Steps I Used To Reproduce:
I checked for subsequent updates of the framework to see what has changed or been introduced in which case I would 
try to perform a safe version update to my current version of Laravel but I found out that's not the case.

**Comment by danilopinotti** [comment]
This is a possible limitation of the JWT lib that you are using.

I suggest you get help in the Official Laravel Discord Server: https://discord.com/invite/mPZNm7A

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
