### ISSUE TITLE
Eloquent `upsert()` method doesn't work with UUID primary key

### ISSUE THREAD

**Issue by plakhin** [laravel/framework#44430]
- Laravel Version: 9.33.0
- PHP Version: 8.1.10
- Database Driver & Version: mysql  Ver 8.0.30 for macos12.4 on arm64 (Homebrew)

### Description:
Users table migration creates the UUID `id` column: `$table->uuid('id')->primary();`.
Users model uses `Illuminate\Database\Eloquent\Concerns\HasUuids` trait.
When trying to upsert a number of records, getting the error: `PDOException: SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value in...`

When using auto-incrementing `id` column all works fine.

**Comment by driesvints** [comment]
Not sure this is compatible with upsert.

**Comment by plakhin** [comment]
@driesvints some mention in the docs would be nice then, either on `upsert()` section, or `UUID` section, or both.

**Comment by driesvints** [comment]
@plakhin we'd welcome a PR for that 👍

**Comment by plakhin** [comment]
@driesvints please check https://github.com/laravel/docs/pull/8274
