### ISSUE TITLE
Factory autocomplete

### ISSUE THREAD

**Issue by Sergiobop** [laravel/framework#44432]
- Laravel Version: 9.33
- PHP Version: 8.1

### Description:
Factory autocompletion works when using the factory itself, but not using the factory() method

### Steps To Reproduce:

First option; Autocomplete working:
```
    $cat = CatFactory::new()->makeOne();
    // This works, cat is an instance of Cat instead of Model
    $cat->property = '';
```

Second option; Autocomplete NOT working:
```
    $cat = Cat::factory()->makeOne();
    // This one says: Potentially polymorphic call. The code may be inoperable depending on the actual class instance passed as the argument. (because cat is an instance of Model, not Cat)
    $cat->property = '';
```

Am i doing something wrong here?
My Cat model uses the HasFactory trait, and the factory has the right `@extends Factory<Cat>` docblock before the class definition

I also see that https://github.com/laravel/framework/blob/9.x/types/Database/Eloquent/Factories/Factory.php contains only assertions using the first option. If the second option is not the standard; why the docs point me to using it? (https://laravel.com/docs/9.x/eloquent-factories#instantiating-models)

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
