### ISSUE TITLE
Error : Class "Illuminate\Support\Testing\Fakes\UpdatedBatchJobCounts" not found

### ISSUE THREAD

**Issue by sashaskr** [laravel/framework#44434]
Hello everyone!
Seems like import of `UpdatedBatchJobCounts` is missing here:

https://github.com/laravel/framework/blob/23e8dd8fac5910edd20327a23529b52af8a77268/src/Illuminate/Support/Testing/Fakes/BatchFake.php#L128

I opened a PR with a fix https://github.com/laravel/framework/pull/44435

**Comment by driesvints** [comment]
Thanks! I saw your PR so let's follow up there.
