### ISSUE TITLE
withSum issue

### ISSUE THREAD

**Issue by kmarshgov** [laravel/framework#44452]
- Laravel Version: 9.23.0
- PHP Version: 8.1
- Database Driver & Version: postgres

### Description:
withSum on a relation does not recognize alias column name.

### Steps To Reproduce:

Step1: Please make sure User model is declared properly.
```
class User extends Model 
{
   public function userDatas(){
         return $this->hasMany(UserData::class, 'user_id');
   }
}
```

Step2: Please make sure UserData model is declared properly.
```
class UserData extends Model 
{
public function user(){
         return $this->belongsTo(User::class, 'user_id');
   }
}
```

Step3: Call.
```
$sums = User::select('user_id')->withSum(
    ['userDatas' => function($query) {
        $query->where('code_type ', 'P');
    }],
    'Paused'
     )
    ->withSum(
    ['userDatas' => function($query) {
        $query->where('code_type ', 'A');
    }],
    'Active'
    )
    ->groupBy('user_id')
    ->orderBy('user_id', 'DESC')-first()
```
With the above I get ```ERROR: column user_datas.Paused does not exist```

**Comment by kmarshgov** [comment]
I also updated to the latest v9.34.0 Laravel version and ended with the same issue.

**Comment by driesvints** [comment]
This indeed isn't supported, sorry.

**Comment by kmarshgov** [comment]
@driesvints here is my second attempt without aliases and still having difficulties. 
```
$sums = User::select('user_id')->withSum(
    ['userDatas' => function($query) {
        $query->where('code_type ', 'P');
    }],
    'id'
     )
    ->withSum(
    ['userDatas' => function($query) {
        $query->where('code_type ', 'A');
    }],
    'code_type'
    )
    ->groupBy('user_id')
    ->orderBy('user_id', 'DESC')-first()
```

This throws a different error ```No function matches the given name and argument types. You might need to add explicit type casts.```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
