### ISSUE TITLE
9.x branch tests are failing.

### ISSUE THREAD

**Issue by ArdaKaraderi** [laravel/framework#44475]
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Version: Postgre 14

### Description:
Content up on 9.x branch is breaking tests.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/22325146/194062320-802db196-aae8-40ed-987a-c4bc5434e2b5.png">

### Steps To Reproduce:
`composer install`
`vendor/bin/phpunit`

**Comment by jbrooksuk** [comment]
You need to install the `gmp` extension.

**Comment by falahatiali** [comment]
how we can install gmp ? and if we want to install it with docker how we can install it? I tried many ways but they failed.

**Comment by Chance-fyi** [comment]
> how we can install gmp ? and if we want to install it with docker how we can install it? I tried many ways but they failed.

```bash
apt-get install libgmp-dev
docker-php-ext-install gmp
```
