### ISSUE TITLE
Observer not called when calling update on hasMany

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#44470]
- Laravel Version: v9.34.0
- PHP Version: 8.1.6

### Description:

My expectation is that the Observer of a Model is always called when a mutation is done via an Eloquent way.

But this is not calling the Observer of Basket:
```
$order->baskets()->update(['amount' => 10]);
```
Result is fine; results are set to an amount of 10, but Observer is not called.

I have to loop through to baskets of the order, and update the amount separately :
```
foreach ($order->baskets as $basket) {
	$order->update(['amount' => 10]);
}
```
When I do this, the Observer is called.

### Steps to reproduce 
Make an Observer.

```
# EventServiceProvider
protected $observers = [
     Basket::class => [BasketObserver::class],
];

```
Set this inside the Observer:
```
public function updating(Basket $basket)
{
	if ($basket->isDirty('amount')) {
		ray('Not called');
	}
}

```
Update the records in the way shown before.

Is this a bug or a feature?

**Comment by eduance** [comment]
According to the documentation:

```
When issuing a mass update via Eloquent, the saving, saved, updating, and updated model events will not be fired for the updated models. This is because the models are never actually retrieved when issuing a mass update.
```

https://laravel.com/docs/9.x/eloquent#mass-updates

To answer your question, this was a feature since 2016. 

You could override the update method by creating a custom builder and still send out the event manually.
