### ISSUE TITLE
Eloquent canUseExistsForExistenceCheck does not consider all cases

### ISSUE THREAD

**Issue by gufoe** [laravel/framework#44483]
- Laravel Version: any
- PHP Version: any
- Database Driver & Version: postgres

### Expected behaviour
The following calls should produce the same query.
```php
Post::whereHas('comments', fn()=>null, '>=', 1)->get();
Post::whereHas('comments', fn()=>null, '>', 0)->get();
```
The first one is converted into an `exists` sql clause, but the second is not.

### Description:
To improve database performance on relation filters, Eloquent replaces subquery `count` with the `exists` sql function.
For example, when I do
```php
Post::whereHas('comments')->get()
```
laravel decides to replace the normal query
```sql
select * from posts where
(select count(*) from comments where post_id=posts.id) >= 1
```
with an optimized query using exists (which is waaay faster to execute in many cases):
```sql
select * from posts where
exists(select * from comments where post_id=posts.id)
```

This is thanks to the "[canUseExistsForExistenceCheck](https://github.com/laravel/framework/blob/b7d97686cf48bb518a997fed4f6ad4a3b5d83a98/src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php#L875)" function.

The issue is that this is not applied when the query uses `x > 0` instead of `x >= 1`.
For instance, 
```php
Post::whereHas('comments', fn()=>null, '>', 0)->get()
```
Will not apply the transformation.

**Comment by driesvints** [comment]
Please fill out the issue template when submitting issues and don't skip versions.

**Comment by eduance** [comment]
@gufoe Yes.
