### ISSUE TITLE
From address is not set for Mailables when using Mail:fake()

### ISSUE THREAD

**Issue by hmazter** [laravel/framework#44486]
- Laravel Version: 9.34.0
- PHP Version: 8.1.10
- Database Driver & Version: MySQL 5.7 (But no database is used in the issue)

### Description:
When testing the sending of mailables using `Mail::fake()` the `from` address (and other properties) configured in `build()` is not set.
i.e it seems that `build()` is not called at all when using Mail::fake().

Is that expected behavior that `build()` is not called in test?
if that is the case the documentation at https://laravel.com/docs/9.x/mocking#mail-fake where it shows asserting from address and subjects etc does not work. 

I hope my explanation makes sense. And let me know if I can supply another example or similar.

### Steps To Reproduce:

I have a test repo here: https://github.com/hmazter/laravel-mail-test-fail
With a mail here: https://github.com/hmazter/laravel-mail-test-fail/blob/main/app/Mail/WelcomeMail.php
And a test here: https://github.com/hmazter/laravel-mail-test-fail/blob/main/tests/Feature/ExampleTest.php

**Comment by driesvints** [comment]
Seems like we have no plans to change or implement this, sorry.
