### ISSUE TITLE
Removing imports from same namespace is not loading Eloquent relationships

### ISSUE THREAD

**Issue by thebazshah** [laravel/framework#44488]
- Laravel Version: 9.19
- PHP Version: 8.1.11
- Database Driver & Version:
- Ubuntu 22.04

### Description:
In current Laravel version (v9.19) I am having this issue. In my model classes, Pint removes imports from same namespace i.e. models imported from same namespace. And because of this the eloquent relationships are not loading even when I query my model using `with` clause. Here is the code I have written in my controller function.

```php
$item = Item::with([
    'grade' => function ($q) {
        $q->select('id', 'title', 'slug', 'description', 'org_search_key', 'isActive');
    },
    'subject' => function ($q) {
        $q->select('id', 'title', 'slug', 'description', 'org_search_key', 'isActive');
    },
])->where('id', $request->itemId)->first();
```

In the model class if I import `Grade` and `Subject` classes, these relationships work fine. If classes are not imported (i.e. removed by Pint), the relationships turn out to be `null`.

### Steps To Reproduce:
Create an API call that loads the `Item` model from database. You only need one relationship with another model like `Grade` or `Subject` in this example. If you use above PHP code, and remove imports from same namespace, you might see this happening.

**Comment by driesvints** [comment]
I think I closed a similar issue in the Pint repo? Please don't open duplicate issues and try a support channel.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
