### ISSUE TITLE
Cannot overwrite default database config

### ISSUE THREAD

**Issue by mouyong** [laravel/framework#44499]
- Laravel Version: 9.x
- PHP Version: 8.0+
- Database Driver & Version: mysql 8

### Description:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/10336437/194484093-f6c7367b-44d7-45e8-aed4-2a140b61cf34.png">

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/10336437/194483489-a5282486-b7e2-49b8-9e74-df8053fb9e20.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/10336437/194483986-e8b88f67-5fda-4c5b-b3ae-5e9f5443a1b5.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mouyong** [comment]
https://discord.com/channels/297040613688475649/486650445297877003/1028113278649508000

when use `\DB::purge();` after changing connection config programatically afaik. it ok.

**Comment by mouyong** [comment]
DatabaseServiceProvider 在 register 时会注册单例 db=>DatabaseManager,
DatabaseManager 在初始化时会将connection存到数组中,
然后 调用DB facade时 DBfacade又会把 app('db') 放到cache数组中,
当修改database config时  如果不重新执行(new DatabaseServiceProvider(app()))->register()  则连接配置不会有任何改变

当执行register后 app('db')拿到的就是修改后的连接配置。
此时 如果DB facade的cached是true的话

则DB facade拿到的依然是旧的连接配置,

综上 如果想修改连接配置并生效
1. 如果想通过register()就重置所有配置 还需要将DB facade的 cached改为false ,
2. 调用DB::purge() 或 app('db')->purge() 

结论：

因 Support\Facades\DB 不可修改 cache 属性，故建议动态修改数据库配置后，调用 DB::purge(); 更新连接配置信息

感谢 @盖世嘤雄 的帮助。
