### ISSUE TITLE
Error dump from.

### ISSUE THREAD

**Issue by mouyong** [laravel/framework#44498]
- Laravel Version: 9.x
- PHP Version: 8.0+
- Database Driver & Version: mysql 8

### Description:

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/10336437/194482277-d907fbfa-cf57-410d-a5c5-f3e20a65bb25.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/10336437/194482394-4a9a1f8e-1b3d-47af-8abd-9c19d63e4f99.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/10336437/194482170-9f18c538-df1b-4d51-8445-30d2008f968d.png">

### Steps To Reproduce:

just dump 123 in DatabaseServiceProvider

**Comment by driesvints** [comment]
Most likely this happens because not all services needed for dumping are registered yet.
