### ISSUE TITLE
App\Http\Kernel::getMiddlewarePriority method cannot be used to specify middleware priority

### ISSUE THREAD

**Issue by standaniels** [laravel/framework#44502]
- Laravel Version: 9.34.0
- PHP Version: n/a
- Database Driver & Version: n/a

### Description:

Custom middleware priority cannot be specified by overwriting the `Illuminate\Foundation\Http\Kernel::getMiddlewarePriority` method in `App\Http\Kernel`. This method is only called in [`KernelTest.php`](https://github.com/laravel/framework/blob/9.x/tests/Foundation/Http/KernelTest.php#L42), but it should also be called by [`Illuminate\Foundation\Http\Kernel::syncMiddlewareToRouter`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Http/Kernel.php#L442), shouldn't it?

### Steps To Reproduce:

1. Add `getMiddlewarePriority` method to `App\Http\Kernel`.
2. Merge a custom array with the array returned by the parent method.

```php
// app/Http/Kernel.php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;
// ...

class Kernel extends HttpKernel
{
    // ...

    public function getMiddlewarePriority()
    {
        return array_merge(parent::getMiddlewarePriority(), [
            \App\Middleware\SomeMiddleware::class,
        ]);
    }
}
```

[Documentation states](https://laravel.com/docs/9.x/middleware#sorting-middleware) to overwrite the `$middlewarePriority` property, but the solution above should also be supported imo, since it's less prone to changes in the parent class as it's not required to copy the default definition of the property.

### Use Case:

In our app we wanted to make sure `App\Middleware\SomeMiddleware::class` has the highest priority of all the app middlewares. We were not interested in altering the priority of the default middlewares.

**Comment by rodrigopedra** [comment]
>but it should also be called by [Illuminate\Foundation\Http\Kernel::syncMiddlewareToRouter](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Http/Kernel.php#L442), shouldn't it?

I agree. 

In the meanwhile you could call:

~~~php
app(\Illuminate\Contracts\Http\Kernel)->appendToMiddlewarePriority(\App\Middleware\SomeMiddleware::class);**
~~~

From any Service Provider's `boot()` method to avoid copying the parent class default definition array just to append a new one.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
