### ISSUE TITLE
Policy before method skipped if it has a mandatory user and the method does not

### ISSUE THREAD

**Issue by hdimitrov1** [laravel/framework#44501]
* Laravel Version: 8.x
* PHP Version: 7.2
- Database Driver & Version: n/a

### Description:

The before method in a policy skips if it doesn't have an optional user

### Steps To Reproduce:

Essentially, with this code, in a policy

```php
public function before(User $user) {
    return false;
}
public function viewAny(?User $user) {
    return true;
}
```

this will allow anyone not logged in to access the resource (provided there's no `auth` middleware), but block anyone that's actually logged in.

This seems like a potential oversight. Feels like this should just throw a PHP error telling me I can't pass null into a mandatory parameter with the before method. Is this intentional?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
