### ISSUE TITLE
Model retrieved from session and saving to database inside a transaction sometimes not being saved to database.

### ISSUE THREAD

**Issue by nk-square** [laravel/framework#44522]
- Laravel Version: 8.83.23
- PHP Version: 8.0.6
- Database Driver & Version: Maria DB 10.4.19

### Description:
Adding an unsaved model to session and then retrieving the same model from session and then saving the model inside a database transaction sometimes results in the model not being saved in the database. This is observed to occur whenever an exception is thrown in the code where the $model->save() is being called.

### Steps To Reproduce:
```php
use App\Models\MyModel;
use DB;

// instantiate the model but do not save the model to database
// add the model to session
public function preview()
{
    $model = new MyModel;
    $model->name = 'test';
    session()->put('model',$model);
}

// retrieve the model from the session and save to database
public function submit()
{
    $model = session('model');

    DB::beginTransaction();

    $model->save();

    // sometimes an exception my occur in my code and when the user reloads the page and submit() is called again the model is not being saved in the database
   // assume that the exception is not thrown in the second execution of this submit() function when the user reloads the page
    throw new Exception(); 

    DB::commit();
}
```

**Comment by morloderex** [comment]
@nk-square Which session driver are you using?

**Comment by nk-square** [comment]
I'm using the default file session driver.

**Comment by andersonef** [comment]
If the exception is getting throwed, then the transaction is not getting commited. So, what's wrong here?

**Comment by nk-square** [comment]
Say the user submits a form and the `submit()` function is executed and an exception is thrown showing 500 screen on the browser, the model is not saved to the database which is the expected behavior. However, say the user reloads the page and the page and the `submit()` function is executed again and **this time the exception is not thrown** (note that the exception thrown is situational and sometimes it is not thrown), on second execution the `submit()` function completes successfully but the model is not being saved to database.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
