### ISSUE TITLE
RefreshDatabase deleted all existing data and dropped current tables

### ISSUE THREAD

**Issue by asg452** [laravel/framework#44535]
- Laravel Version: 8.83.23
- PHP Version:7.4
- Database Driver & Version: mysql 5.7

### Description:
Trying to run Pest tests against staging database. On running tests with the trait RefreshDatabase to be applied to all tests - it dropped all tables and removed all data. It does run migration afterwards but all staging data is now gone. 

### Steps To Reproduce:

1.  new laravel app
2. Run users migration and create a table called my_table directly from mysql with a column "id"
3. Add a new user to the users table
4. Update your Pest.php file as below
5. Run ./vendor/bin/pest 
6. You will notice data in the user table is gone and my_table is dropped

In your pest.php do this

`uses(TestCase::class,CreatesApplication::class, RefreshDatabase::class)
->beforeEach(function() {
    self::withHeaders([ 'accept' => 'application/json', ]);
})->in('Feature','Unit');`

**Comment by timacdonald** [comment]
This is the intended functionality of `RefreshDatabase`. It drops your data and migrates the database again.

If you want to keep the current data in place, you may need to try `Illuminate\Foundation\Testing\DatabaseTransactions`

**Comment by asg452** [comment]
Thanks! I could be wrong here but I felt the way documentation presents refresh database trait is different than how it functions. It doesn’t mention anything about dropping tables or removing existing data. It does mention that the main use is so your previous test data doesn’t cause issues with the new test data.

I can submit a new doc pr if that’s acceptable?

On Oct 10, 2022, at 5:52 PM, Tim MacDonald ***@***.***> wrote:

﻿
CAUTION: External to USask. Verify sender and use caution with links and attachments. Forward suspicious emails to ***@***.***


This is the intended functionality of RefreshDatabase. It drops your data and migrates the database again.

If you want to keep the current data in place, you may need to try Illuminate\Foundation\Testing\DatabaseTransactions
