### ISSUE TITLE
migrations with schemas do not work in a docker container

### ISSUE THREAD

**Issue by delboy1978uk** [laravel/framework#44542]
- Laravel Version: v8.83.23
- PHP Version: 8.0.12
- Database Driver & Version: mariadb:10.7.1
### Description:

Migrations will use PHP to connect to MySQL without problems, but if there are schema SQL files then Laravel will attempt to use the `mysql` command, which is not available in a docker container (or indeed any server without MySQL where the DB is hosted elsewhere), and so requires the dependency of the MySQL client in order for the migrations to succeed .

This issue has already been discussed here https://github.com/laravel/ideas/issues/2638 where the installation of another dependency (mysql-client) was described as an elegant solution. I'm not sure I agree. If we can use the database connection normally via Laravel, now THAT would be elegant.

### Steps To Reproduce:

- Launch a docker compose setup with Laravel in a PHP container and MySQL  in its own container
- squash some migrations so you have a database schema sql file
- attempt to migrate

### Expected result :
```
Database seeding completed successfully.
```
### Actual Result 
```
Migration table created successfully.
Loading stored database schema: /var/task/database/schema/your-schema.dump

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command "mysql  --user="${:LARAVEL_LOAD_USER}" --*** --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.

Exit Code: 127(Command not found)

Working directory: /var/www/html

Output:
================


Error Output:
================
sh: mysql: not found

  at /var/task/vendor/symfony/process/Process.php:272
    268▕      */
    269▕     public function mustRun(callable $callback = null, array $env = []): self
    270▕     {
    271▕         if (0 !== $this->run($callback, $env)) {
  ➜ 272▕             throw new ProcessFailedException($this);
    273▕         }
    274▕ 
    275▕         return $this;
    276▕     }

      +22 vendor frames 
  23  /var/task/artisan:43
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Logs: You may review its logs using the `hook:log 2145551` command.
Error: Process completed with exit code 1.
```
### Temporary Fix
- In the Dockerfile of the PHP container, install another mysql 
  (`RUN apt-get -y --no-install-recommends install default-mysql-server`)

**Comment by eusonlito** [comment]
It Is right, if you want to import a sql schema from file you need the database client, no way to do it with native php code.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by delboy1978uk** [comment]
@eusonlito you have the same issue, what version of Laravel are you using?

**Comment by eusonlito** [comment]
@delboy1978uk, no, I always install the `mysql-client` inside my docker images. SQL dumps are complicated to parse, and the PDO can not do the task. Then you only can use the `mysql-client` to import a database dump. Same as PostgreSQL (binary dumps), or SQLite.

**Comment by lk77** [comment]
any container that should interact with the database should have the mysql binary

**Comment by delboy1978uk** [comment]
Remember of course that this issue isn't necessarily restricted to any docker container type setup, it also applies to any web hosting where the database is hosted on a different IP, where devs may or may not be able to install additional dependencies.

Also when it comes to difficulty in parsing SQL dumps, remember that this issue is only in the context of the schema dump whilst squashing migrations, meaning that the dump will contain only create table statements.
