### ISSUE TITLE
Error when uploading GPX files

### ISSUE THREAD

**Issue by rtfmfm** [laravel/framework#44546]
- Laravel Version: v9.35.1
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.30

### Description:
When trying to upload GPX file the framework does not return an error and "uploads" an empty file. 
The `var_dump($request->file('gpx_file'));` returns:
```
object(Illuminate\Http\UploadedFile)[1509]
  private 'test' (Symfony\Component\HttpFoundation\File\UploadedFile) => boolean false
  private 'originalName' (Symfony\Component\HttpFoundation\File\UploadedFile) => string 'file.gpx' (length=8)
  private 'mimeType' (Symfony\Component\HttpFoundation\File\UploadedFile) => string 'application/octet-stream' (length=24)
  private 'error' (Symfony\Component\HttpFoundation\File\UploadedFile) => int 1
  protected 'hashName' => null
  private 'pathName' (SplFileInfo) => string '' (length=0)
  private 'fileName' (SplFileInfo) => string '' (length=0)
```

Tried on `apache2` and `nginx` web servers. 

### Steps To Reproduce:
Try to upload a GPX file using form.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
