### ISSUE TITLE
php artisan view:cache returns an error since laravel 9.35 :   Unable to locate a class or view for component [mail::message].

### ISSUE THREAD

**Issue by amarmain** [laravel/framework#44544]
- Laravel Version: 9.35
- PHP Version: 8.0.19
- Database Driver & Version:

### Description:

Since I run a composer update to get the latest laravel version (9.35), my deployment script crashes.

If I go back to laravel 9.34, the error does not occur anymore.

### Steps To Reproduce:

Just run these commands:

composer dump-autoload
php artisan view:cache

**Comment by DougSisk** [comment]
Same here. Seems to be an issue with PR #44527

**Comment by browner12** [comment]
![Screen Shot 2022-10-11 at 10 15 56 AM](https://user-images.githubusercontent.com/5232313/195132400-7156745f-ea5a-446a-b1bd-fff09d62445c.png)

**Comment by hungthai1401** [comment]
I think we only need because we don't load views of mail

src/Illuminate/View/Compilers/ComponentTagCompiler.php line 315
```php
if (Str::startsWith($component, 'mail::')) {
   return $component;
}
```

**Comment by mateuslecchi** [comment]
Same problem here, have to downgrade to 9.34

**Comment by AyoobMH** [comment]
Same problem here!

**Comment by nunomaduro** [comment]
We are aware of this issue. And, Taylor will address it just after his lunch time. 👍🏻

**Comment by taylorotwell** [comment]
Fixed in 9.35.1.

**Comment by amarmain** [comment]
thanks it works!

**Comment by tomhapbia** [comment]
> I think we only need check component start with prefix because we don't load views of mail
> 
> src/Illuminate/View/Compilers/ComponentTagCompiler.php line 315
> 
> ```
> if (Str::startsWith($component, 'mail::')) {
>    return $component;
> }
> ```

Valuable comment!

**Comment by hungthai1401** [comment]
> > I think we only need check component start with prefix because we don't load views of mail
> > src/Illuminate/View/Compilers/ComponentTagCompiler.php line 315
> > ```
> > if (Str::startsWith($component, 'mail::')) {
> >    return $component;
> > }
> > ```
> 
> Valuable comment!

@tomhapbia thanks
