### ISSUE TITLE
Misleading error message for incorrect rendering of  components.

### ISSUE THREAD

**Issue by brunoalfred** [laravel/framework#44553]
![Screenshot 2022-10-12 at 08 19 34](https://user-images.githubusercontent.com/55545250/195256531-0eda8818-ea9b-48cd-99c7-e711a11f83e7.png)

### Steps To Reproduce:

1. Create a component are described in [docs](https://laravel.com/docs/9.x/blade#anonymous-index-components)

Example:

`resources/views/components/reuse.blade.php`
```html
<div>
	Hello! I'm a Component!
</div>
```
2. Render the components in another view.
Example:
`resources/views/welcome.blade.php`
```html

<x-reuse  > 
<!-- Instead of <x-reuse  /> --!>
```

3. The message display when the view is return. 

![Screenshot 2022-10-12 at 08 28 51](https://user-images.githubusercontent.com/55545250/195257642-c5cb93d3-54bc-4b22-873c-bc6b0bae2902.png)

I think a better error message explaining that there is a missing character on the syntax could be more helpful.

**Comment by driesvints** [comment]
This seems like a feature request and an attempted PR wasn't accepted so it would seem we're not going to change anything here right now.
