### ISSUE TITLE
`sometimes` validation rule has preg_match exception for keys with `*` and containing `/`

### ISSUE THREAD

**Issue by KenoKokoro** [laravel/framework#44567]
- Laravel Version: v9.35.1
- PHP Version: 8.0.19
- Database Driver & Version:

### Description:
Whenever I use `sometimes` on a nested validation rule with the format: `keys.*.strings.*.text` where the structure is like: "keys.some/path/to/file.json.strings.*.text" it throws `preg_match` exception inside the `ValidationData:60`. 

![image](https://user-images.githubusercontent.com/10259827/195544943-5af41ab9-31cd-4283-8563-ef385eb4830c.png)

Seems like the `some/path/to/file.json` is not escaped properly:

```php
// On ValidationData:57
$pattern = str_replace('\*', '[^\.]+', preg_quote($attribute));

// And then on ValidationData:60 
if ((bool)preg_match('/^' . $pattern . '/', $key, $matches)) {
    $keys[] = $matches[0];
}
```
The `$pattern` variable here looks like: `/^keys\.some/path/to/file7Vn8vEcotPKW69qIjson\.strings\.da\.text/` where the `/` from `some/path/to/file` are not escaped, which results in the error from the screenshot above

However, replacing the `sometimes` with `present` or just removing it (which is not ideal for my case, since this field can be omitted too), fixes the issue.

### Steps To Reproduce:
Create an endpoint where it is validated with something like:
```php
return [
    'keys.*.strings.*.text' => ['sometimes', 'string', 'nullable']
];
```

Send a payload with:
```json
{
   "keys":{
      "some/path/to/file.json":{
         "name":"some/path/to/file.json",
         "strings":{
            "da":{
               "text":"This is translation"
            }
         }
      }
   }
}
```

**Comment by driesvints** [comment]
Forward slashes need to be escaped in JSON keys. This is something you'll need to do yourself beforehand.
