### ISSUE TITLE
Invalid php dependancy

### ISSUE THREAD

**Issue by dlnsk** [laravel/framework#44566]
- Laravel Version: 6.20.44, 7.*
- PHP Version: 8.1

### Description:

"php": "^7.2.5|^8.0" record in composer.json means ">=7.2.5" && "<8.0" or ">=8.0" && "<9.0" (https://getcomposer.org/doc/articles/versions.md#caret-version-range-)
so php 8.1 includes in that range. But 8.1 isn't compatible with 6.x, 7.x (8.x not tested) and fall with:

> During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillCha  
>   nge] attribute should be used to temporarily suppress the notice in /var/www/attestation/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1277

**Comment by crynobone** [comment]
Also, those are depreciation warning and you still be able to use PHP 8.1. Unless there are other error or actual compatibility that can prevent you from using PHP 8.1
