### ISSUE TITLE
blank($value) helper

### ISSUE THREAD

**Issue by romanstingler** [laravel/framework#44570]
- Laravel Version: 9.351
- PHP Version: 8.2
- Database Driver & Version: PG14

### Description:
I wanted to ask if there is a reason why the `blank` helper doesn't include an `isset` check?

```
    function blank($value)
    {
        if (is_null($value)) {
            return true;
        }
    ....
```
should be
```
    function blank($value)
    {
        if (!isset($value) || is_null($value)) {
            return true;
        }
    ....
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rodrigopedra** [comment]
> isset — Determine if a variable is declared and is different than null

https://www.php.net/manual/en/function.isset.php

As `$value` is always declared inside the function scope it is a parameter, checking only for null is sufficient.
