### ISSUE TITLE
Unknown named parameter $directory  on BLade::componentNamespace function

### ISSUE THREAD

**Issue by WeedTest** [laravel/framework#44574]
![image](https://user-images.githubusercontent.com/71571547/195638214-b8119c4e-012b-45ca-9cc3-4cd30ff88c0a.png)

### Description:
![image](https://user-images.githubusercontent.com/71571547/195638943-8cf468f2-e6ce-43d1-9f1a-c7136b6b53d6.png)

docblock in Illuminate\Support\Facades\Blade
![Capture d’écran du 2022-10-13 15-16-03](https://user-images.githubusercontent.com/71571547/195639607-7d8e8b6b-682b-4745-887a-7484d2ba3f68.png)

is defferent from Illuminate\View\Compilers\BladeCompiler::componentNamespace

![Capture d’écran du 2022-10-13 15-16-25](https://user-images.githubusercontent.com/71571547/195639659-5a8b2e9b-444f-42ad-9f5e-27c0f957d88e.png)

thanks.

**Comment by rodrigopedra** [comment]
> [Named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments) are not covered by Laravel's backwards compatibility guidelines. **We may choose to rename function arguments when necessary in order to improve the Laravel codebase**. Therefore, using named arguments when calling Laravel methods should be done cautiously and with the understanding that the parameter names may change in the future.

https://laravel.com/docs/9.x/releases#named-arguments

**Comment by rodrigopedra** [comment]
@WeedTest in short: Laravel does not guarantee parameter names won't change. 

So, avoid using named parameters when calling framework level methods.

Also I don't think your `Blade@componentNamespace` usage is correct. You seem to be using using a class name as the namespace parameter. 

Please check usage in the link below:

https://laravel.com/docs/9.x/blade#manually-registering-package-components

**Comment by WeedTest** [comment]
thanks @rodrigopedra
