### ISSUE TITLE
WhereHas and has not working with Model Connection property take default connection

### ISSUE THREAD

**Issue by MohinSandhi** [laravel/framework#44587]
- Laravel Version: 9.35.1
- PHP Version: 8.0.3
- Database Driver & Version:
Mysql 5.7.12

### Description:
on server, there is 2 database running on the same rds
database 1 has a user table and user model connection name is old_database
database 2 has a corporate user and the Corporate user model connection name is mysql (default)

when I try to perform any action like whereHas or has via the corporate user to a user then laravel orm ignores connection it always take the default database connection but it is working perfectly with() method

### Steps To Reproduce:

User Default table provided by laravel
corporate_users user table 

CREATE TABLE `corporate_users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL COMMENT 'This id will be user id',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mobile_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gender` enum('male','female') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'male',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

query
CorporateUser::has('user')->count('id')

Corporate User model
![image](https://user-images.githubusercontent.com/88226058/195842649-fa539102-a45c-4ab0-b131-055edd13131a.png)

User Model
![image](https://user-images.githubusercontent.com/88226058/195842855-065ab530-ff39-49e4-89aa-14da90512f17.png)

relationship 

 public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    
    
    Database config

       'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        'old_database' => [
            'driver' => 'mysql',
            'url' => env('OLD_DATABASE_URL'),
            'host' => env('OLD_DB_HOST', '127.0.0.1'),
            'port' => env('OLD_DB_PORT', '3306'),
            'database' => env('OLD_DB_DATABASE', 'forge'),
            'username' => env('OLD_DB_USERNAME', 'forge'),
            'password' => env('OLD_DB_PASSWORD', ''),
            'unix_socket' => env('OLD_DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

**Comment by dsnetrizon** [comment]
Same problem. $table is not ignored but in my case i have dynamic database name so i must use $connection.

**Comment by dsnetrizon** [comment]
I did few tests and $connection isnt ignored. For all whereHas $connection is set from main model 
`User::whereHas('Roles')->get();` For this Roles using main model $connection = User model connection.
U can work on $table variable and this will work good but if your both databases use other mysql user than this do not work.

**Comment by MohinSandhi** [comment]
> I did few tests and $connection isnt ignored. For all whereHas $connection is set from main model `User::whereHas('Roles')->get();` For this Roles using main model $connection = User model connection. U can work on $table variable and this will work good but if your both databases use other mysql user than this do not work.

I checked but if both tables are on the same DB then it's not generate any error but if one table is in another database then its generates error because it always use the parent model connection

**Comment by dsnetrizon** [comment]
Yes but if both tables are on same server and 1 user have access to them u can set $table like `$table = 'second_db.users';` and this will work. If u have pivot table than u must set this also in relation (second parameter in belongsToMany).
If databases are on different server than RIP 💀

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MohinSandhi** [comment]
> Yes but if both databases are on same server and 1 user have access to them u can set $table like `$table = 'second_db.users';` and this will work. If u have pivot table than u must set this also in relation (second parameter in belongsToMany). If databases are on different server than RIP 💀

we have 4 database 2 for dev and 2 for producation

**Comment by MohinSandhi** [comment]
model connection is working perforate  with with or withcount it is only generating errors with has and whereHas
it taking the parent model connection value 

Here is Error Reproduce here is code for Reproduce
just clone repo and make 2 database test_1 and test_2 and i also added factory as well 
in index route I added code which generates errors 

corporates table is on test 1 database
employees table is on test 2 database

SELECT
  *
FROM
  `corporates`
WHERE
  EXISTS (
    SELECT
      *
    FROM
      `employees`
    WHERE
      `corporates`.`id` = `employees`.`corporate_id`
      AND `status` = active
  )

Steps To Reproduce with code ;
https://gitlab.com/MohinSandhi/laravel-wherehas-and-has-issue
