### ISSUE TITLE
Nested validation and the sometimes rule

### ISSUE THREAD

**Issue by rubenvanassche** [laravel/framework#44586]
- Laravel Version: 9.27.0
- PHP Version: 8.1.8
- Database Driver & Version: Mysql 8

### Description:

The sometimes rule allows us to only validate a field when it is present but it has some strange behavior when being used in nested rules.

### Steps To Reproduce:

First a working example:

```php
$v = Validator::make([
    'user' => [
        'name' => 'Ruben',
        'age' => 28,
    ],
], [
    'user' => ['sometimes', 'array'],
    'user.name' => ['string', 'required'],
    'user.age' => ['int', 'required'],
]);
```

The complete payload is provided so no problems here. When we remove the required fields in the nested object, the validator complains about missing fields. Again, perfect behavior.

```php
$v = Validator::make([
    'user' => [],
], [
    'user' => ['sometimes', 'array'],
    'user.name' => ['string', 'required'],
    'user.age' => ['int', 'required'],
]);
```

Now when we remove the object key, which is allowed by the sometimes rule:

```php
$v = Validator::make([], [
    'user' => ['sometimes', 'array'],
    'user.name' => ['string', 'required'],
    'user.age' => ['int', 'required'],
]);
```

We get two validation errors:

```php
"user.name" => array:1 [
  0 => "Required"
]
"user.age" => array:1 [
  0 => "Required"
]
```

Which is kinda weird, because we told earlier that the object will sometimes not be present, yet we're evaluating rules for nested fields of the object.

A solution could be to add sometimes to all the fields of the nested object like this:

```php
$v = Validator::make([
], [
    'user' => ['sometimes', 'array'],
    'user.name' => ['sometimes', 'string', 'required'],
    'user.age' => ['sometimes','int', 'required'],
]);
```

This works, but completely breaks the validation of the nested object. Since we probably want the `required` rules to run when an object is passed, this is not going to happen. Passing in an empty object will validate without errors.

Is this behavior correct? When we're working with an array of objects the problem doesn't exist but I'll guess that's implemented completely different within the validator.

Is there a better way to solve this problem? Maybe a bit of reasoning here, I'm the maintainer of the spatie/laravel-data package which will automatically generate rules for data objects and nested data objects. At the moment our validation logic is kinda broken, so I'm open for all suggestions how to fix this 😄.

**Comment by timacdonald** [comment]
I've run into this exact thing when building up some complicated validation logic for object based data. But I think I have the right incantation for you.

We ended up doing it the other way around, where we made the children's "required" state dependent on the parent's existence...

```php
Validator::make([
    'user' => ['name' => 'tim'],
], [
    'user' => ['array'],
    'user.name' => ['string', 'required_with:user'],
    'user.age' => ['int', 'required_with:user'],
])->errors()->all();

// [
//   "The user.age field is required when user is present.",
// ]

// failed
```

However, due to the nature of the Laravel validator, an empty string and an empty array will not invoke the required rules (this is the same the for standard "required" rule)...

```php
Validator::make([
    'user' => [],
], [
    'user' => ['array'],
    'user.name' => ['string', 'required_with:user'],
    'user.age' => ['int', 'required_with:user'],
])->errors()->all();

// []

// passed
```

or an empty string...

```php
Validator::make([
    'user' => '',
], [
    'user' => ['array'],
    'user.name' => ['string', 'required_with:user'],
    'user.age' => ['int', 'required_with:user'],
])->errors()->all();

// []

// passed
```

So now we will make it that if `user` is in the request, it must have a non-value with `"filled"`.

```php
Validator::make([
    'user' => [],
], [
    'user' => ['array', 'filled'],
    'user.name' => ['string', 'required_with:user'],
    'user.age' => ['int', 'required_with:user'],
])->errors()->all();

// [
//    "The user field must have a value.",
// ]

// failed


Validator::make([
    'user' => ['foo' => 'bar'],
], [
    'user' => ['array', 'filled'],
    'user.name' => ['string', 'required_with:user'],
    'user.age' => ['int', 'required_with:user'],
])->errors()->all();

// [
//   "The user.name field is required when user is present.",
//   "The user.age field is required when user is present.",
// ]

// failed

```



Lastly, I don't think the `"sometimes"` rule is doing anything here. You can probably remove it and you will have exactly the same result to my knowledge, as the default behaviour is that rules are not run if the data is not present.

**Comment by viiy** [comment]
```php
$v = Validator::make([], [
    'user' => ['sometimes', 'array'],
    'user.name' => ['string', 'required'],
    'user.age' => ['int', 'required'],
]);
```
my fast solution to get this code to work correctly

```php
class Validator extends BaseValidator
{
    protected function validateAttribute($attribute, $rule)
    {
        if ($this->hasParentSometimes($attribute)) {
            return true;
        }
        parent::validateAttribute($attribute, $rule);
    }

    protected function hasParentSometimes($attribute): bool
    {
        $parents = explode('.', $attribute);
        array_pop($parents);
        foreach ($parents as $parent) {
            if ($this->getRule($parent, 'Sometimes') && !Arr::has($this->data, $parent)) {
                $this->excludeAttribute($attribute);
                return true;
            }
        }
        return false;
    }
}
```


also will work 
```php
$v = Validator::make([], [
    'user' => ['sometimes', 'array'],
    'user.phone.number' => ['string', 'required'],
]);
```

maybe it will be useful to someone 😎
