### ISSUE TITLE
Job issue for model without db table

### ISSUE THREAD

**Issue by ayophanz** [laravel/framework#44581]
is there a way to avoid this issue for model without db table?

error:
![image](https://user-images.githubusercontent.com/24581584/195753673-c33c87db-09ec-4a17-9a22-3cb37211d6f2.png)

model without table:
![image](https://user-images.githubusercontent.com/24581584/195753708-7029f64f-a930-4e2e-853b-a2eeb9043a18.png)

job:
![image](https://user-images.githubusercontent.com/24581584/195753918-b7cd746f-6876-464a-b673-b69588f56f78.png)

Thank you

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
