### ISSUE TITLE
Using route/url in an attribute "not supported" won't generate a link to the correct scheme

### ISSUE THREAD

**Issue by Marwelln** [laravel/framework#44594]
- Laravel Version:  9.2
- PHP Version: 8.1
- Virtual machine running on Amazon EC2

### Description:
Using `route` in an attribute "not supported" won't generate link to `https` but instead `http`.

### Steps To Reproduce:

1. Viewing your page with `https`, open any blade file.
2. Add `<a href='{{ route('foobar') }}'>link</a>` anywhere – this works, link will be https://foobar
3. Add `<a foo='{{ route('foobar') }}'>link</a>` anywhere – doesn't work, link will be http://foobar – why?

This is an issue when using `<picture>` as you're using `srcset` instead of `src`. In the example below, only the `img` tag is linking to the `https` scheme. Every `source` tags are linking to a `http` page, making them unusable when browsing the page with `https`. Changing `srcset` to `src` will result in a correct scheme.

    <picture>
        <source srcset="{{ route('file.view', ['file' => $file, 'size' => null]) }}" media="(min-width: 700px)">
        <source srcset="{{ route('file.view', ['file' => $file, 'size' => 700]) }}" media="(min-width: 500px)">
        <source srcset="{{ route('file.view', ['file' => $file, 'size' => 500]) }}" media="(min-width: 350px)">
        <source srcset="{{ route('file.view', ['file' => $file, 'size' => 350]) }}" media="(min-width: 200px)">
        <img src="{{ route('file.view', ['file' => $file, 'size' => 200]) }}">
    </picture>

I have tested this on two different Laravel applications (not freshly installed but updated to latest Laravel version). I have also checked the generated blade file to confirm there's not a browser issue.

**Comment by BrandonSurowiec** [comment]
Do your local env `APP_URL` start with `http://`? If so, changing that to `https` should fix it.

**Comment by Marwelln** [comment]
After checking trough the Laravel code on how the scheme is set I solved this by removing Cloudflare proxy and then issuing a new ssl certificate on my server without Cloudflare interference. 

Super weird case but at least it is fixed.
