### ISSUE TITLE
Fix getTokenForRequest return type

### ISSUE THREAD

**Issue by ilyub** [laravel/framework#44597]
- Laravel Version: 9.35.1
- PHP Version: 8.0.6
- Database Driver & Version:

### Description:

getTokenForRequest documented return type is "string".
But it actually can return "mixed" as can be seen from screenshot:
![image](https://user-images.githubusercontent.com/70687432/195969893-3349f656-0943-42dd-a829-1fc540aee55b.png)

### Steps To Reproduce:

See screenshot

**Comment by driesvints** [comment]
Heya. This doesn’t seem like a bug. Feel free to send a pr if you want to adjust a docblock
