### ISSUE TITLE
Route name not working with DB

### ISSUE THREAD

**Issue by Nelnaji** [laravel/framework#44596]
- Laravel Version: 9.3.3
- PHP Version: 8.1.8
- Database Driver & Version:MySQL 5.7.33

### Steps To Reproduce:

Hello

I've been working on a project lately, I've created a ressource:get with a name route called 'welcome" that return my welcome view.

In my DB I have a table that is seeded with route('welcome') that I send through an appserviceprovider to a component. so that I can modify all my route with just the name

The problem is that when I send the data in my href  <a href={{ db->href }}> link </a>

what's returned in my webbrowser is ; http://127.0.0.1:8000/route('welcome')  and I don't know why especially knowing that everything was working fine.

You can check the issue by cloning my repo https://github.com/Nelnaji/Himara  it's the branch features that has the bug.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Nelnaji** [comment]
I found the problem, the route() method was not called.

It was a syntax error on my part, I forgot to remove the issue, thank you for closing it.
