### ISSUE TITLE
Connection:: beforeExecuting() cannot be executed on all SQL

### ISSUE THREAD

**Issue by lanrenbulan** [laravel/framework#44603]
- Laravel Version: 9.*
- PHP Version: 8.*
- Database Driver & Version: mysql8

### Description:

Connection:: beforeExecuting() cannot be executed on all SQL, such as the SET command. See MySQL Connector.

It is expected that all SQL can be processed by Connection:: run().

In my application, I use database middleware, such as shardingsphere or mycat.

Select the data source by adding annotations before SQL, as follows:

/* ShardingSphere hint: dataSourceName=db_1 */select * form user;

In addition, in order to ensure the use of transactions, it cannot directly use the PDO method(PDO::beginTransaction() PDO::commit （） PDO::rollBack()) to execute transaction operations, but needs to execute transaction SQL. All the above needs to be annotated, which leads to the need for larravel to provide the method type to execute transaction operations.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
