### ISSUE TITLE
Segmentation fault with combined use of queues and container's when-needs-give for LoggerInterface

### ISSUE THREAD

**Issue by amcsi** [laravel/framework#44618]
- Laravel Version: 9.26.1
- PHP Version: 8.1.11
- Database Driver & Version: none

### Description:

When using any non-sync queue (e.g. redis), and you have a service class (e.g. `\App\MyCrashingService`) with `\Psr\Log\LoggerInterface` as a dependency, and you want to override that interface's implementation for just `\App\MyCrashingService`  by doing `$app->when(\App\MyCrashingService::class)->needs(`\Psr\Log\LoggerInterface::class`)->give(fn() => \Log::driver('whatever'))`, and you request MyCrashingService in the non-sync queue, Laravel crashes with a segfault in the queue worker.

Note:
* This happens with the database queue driver too, not just redis.
* This happens while in a non-sync queue. This can't be reproduced with a sync queue or directly requesting the service from the container in a CLI command, nor can it be reproduced from an HTTP request context.
* In `->give()`, `$this->app->get(LogManager::class)->driver('whatever')` also causes a crash, not just `\Log::driver('whatever')`.
* If I do _not_ dependency inject LoggerInterface in MyCrashingService and instead request `\Log::driver('whatever')` during runtime (or even the constructor), it does _not_ crash.

I know I could just request the logger that I want during runtime with `\Log::driver('whatever')`, but in my project I would like to have LoggerInterface dependency injected, because in tests I want to stub it with an alternative logger to make assertions on what gets logged. This segfaulting is preventing me from doing so, however.

### Steps To Reproduce:

https://github.com/amcsi/loggerinterface-crash-example

You need to make sure that a redis service is running under the default port, and make sure to set `QUEUE_CONNECTION=redis`.

Video:

https://user-images.githubusercontent.com/116494/196158393-0ab246bb-1061-4a83-bfbf-98bab104831b.mp4

**Comment by X-Coder264** [comment]
This seems to be the same issue that I've reported over two years ago (a recursion that happens while trying to contextually bind a logger implementation) -> https://github.com/laravel/framework/issues/33114

That issue was closed with an explanation that doesn't really make too much sense to me, but I've never had time to dig back into the issue and the Laravel container internals regarding it.

The explanation was:

> So, when you say "when the Foo class needs "log", resolve "log"... that's recursive and I'm not sure there is any way around that really - not just for log but for any binding. It just doesn't make sense.

When I write such contextual binding I don't see it as `when the Foo class needs "log", resolve "log"`, I see it as "when you reach the LoggerInterface typehint in the Foo constructor inject whatever this contextual binding closure returns".

**Comment by amcsi** [comment]
What I didn't mention is that if I resolved the dependency in advance, I still get a segmentation fault:

```php
$myLogger = \Log::driver('stderr');
$this->app->when(MyCrashingService::class)->needs(LoggerInterface::class)->give($myLogger);
```

So something fishy is going on even if I don't resolve something from LogManager "during resolving a LoggerInterface dependency".

It would be a huge bummer if I couldn't use good PHP practices of dependency-injecting interfaces with the help of Laravel's container features :/ as you demonstrated in #33114 you are able to resolve the dependency by manually constructing the instance in the container factory callback, so I it should be possible to achieve this to work.

**Comment by driesvints** [comment]
Thanks for reporting. As said on the other issue we don't believe there's a solution to this. We'd welcome PR's if anyone has any idea on how to solve this, thanks.

**Comment by EdgarSedov** [comment]
@driesvints Sorry, but could please explain what's the problem? I'm not familiar with laravel codebase and practices, but for whose who are, doesn't it look pretty simple?

I mean u have array of `ReflectionParameter` inside `\Illuminate\Container\Container::resolveDependencies`. All what's left is just to pass class, which is being resolved, as 2nd parameter to `resolveDependencies` and then pass it to `hasParameterOverride` function or its analogue to check if there's any `$this->contextual[$concrete][$dependency]`. Could u please explain what's wrong with this concept?

**Comment by EdgarSedov** [comment]
Looks like i found the answer in comment https://github.com/laravel/framework/issues/33114#issuecomment-639549198.

Kinda don't get why Psr Logger Interface is hardcoded to LogManager internally, looks like not a good solution imo. But even with that, i still think my proposal should work (not 100% sure ofc since i'm not familiar with codebase enough)

**Comment by EdgarSedov** [comment]
Also, respect @amcsi for debug time spent and issue created. Have the same problem on staging myself and spent a ton of time to find the source of problem. Kinda strange what this happens only for services, which are being used in jobs (even when u're resolving them in tinker and not in worker)

**Comment by EdgarSedov** [comment]
Oh, looks like i get it. You override loggerinterface classname with 'log' literal even on contextual binding creation
