### ISSUE TITLE
View composer namespaced wildcards no longer work

### ISSUE THREAD

**Issue by jasonvarga** [laravel/framework#44634]
- Laravel Version: 9.36.0
- PHP Version: 8.1.6
- Database Driver & Version: N/A

### Description:

Using a view composer with a namespaced wildcard no longer works as of 9.36.0. Likely due to #44487 since it's all about views.

```php
public function boot()
{
    $this->loadViewsFrom(resource_path('namespaced'), 'namespaced');

    View::composer('namespaced::*', fn ($view) => $view->with('foo', 'bar'));
}
```

```blade
{{ $foo }}
```

```
Undefined variable $foo
```

Using a complete wildcard still works. `View::composer('*', ...)`
It's just the namespaced version that doesn't. `View::composer('namespace::*', ...)`

### Steps To Reproduce:

Here's a GitHub repo with the issue reproduced. Link to commit that adds the problematic bits:
https://github.com/jasonvarga/laravel-view-composer-issue/commit/1548cefdba11aa2c660eb2aab6eb5b5fef2d1958

**Comment by jasonvarga** [comment]
I'll take a stab at a PR.

**Comment by KennedyTedesco** [comment]
Yeah, I can confirm the issue. We need to work a bit more on `shouldCallComposers`. Good luck on the PR! =D

**Comment by jasonvarga** [comment]
I had a feeling it would be much faster for Nuno. 🤣

**Comment by nunomaduro** [comment]
@jasonvarga Can you test if the changes I've made fix the issue you were having in your application? It does fix the issue on the application you have prepared on the issue.

**Comment by jasonvarga** [comment]
Yup, fixes it for us too. Thanks @nunomaduro

**Comment by jasonvarga** [comment]
Thank you for the speedy turnaround!
