### ISSUE TITLE
[BUG] in filesystem#file-uploads ```$request->file('avatar')->store('avatars')```

### ISSUE THREAD

**Issue by SathishKumarA2001** [laravel/framework#44649]
- Laravel Version: 9.26.1
- PHP Version: 8.1.2
- Database Driver & Version: MySQL & 8.0.30

### Description:

1. This is my storage area for storing upload images `www/billitesaas/storage/app/public/{logo}` from end-user.

2. Important Note: The logo directory doesn't have write permissions.

3. When I upload image file using ```$request->file('image_file')->store('public/logo')``` this method, the "image_file" doesn't stored in the logo directory, However this method ```$request->file('image_file')->store('public/logo')``` did returns the path of the "image_file", It should have thrown "Upload file" exception rather than return the path of the "image_file".

4. After I have given permission to the logo directory and sent another request with a new "image_file" again, the old "image_file" has also been stored with the new "image_file" in the logo directory. Does Laravel store the old image_file storing in any temporary cache or something in laravel? I don't know what behavior is this in laravel.

### Steps To Reproduce:
```
<?php
 
namespace App\Http\Controllers;
 
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
 
class UserAvatarController extends Controller
{
    public function update(Request $request)
    {
        $path = $request->file('image_file')->store('public/logo'); // Absolute path is www/billitesaas/storage/app/public/logo
 
        return $path;
    }
}
```
'logo' directory permission in Linux is ```dr--r--r-x 2 www-data www-data 4096 Oct 18 17:18 logo```
1. Send any image file in the request from the front end without giving written permission to the logo directory (send request at least 3 or 4 for better glance).
2. Next, send a second request with an image file from frontend after giving permission to the logo directory.
3. Do and see what happens in the $path variable and in the logo directory to understand the bug.
---

Kindly suggest if you want more explanation or changes to my above question, give me which part of my question so that it'll help me to elaborate. However, I have provided as much detail about the bug.

**Comment by ankurk91** [comment]
https://github.com/laravel/laravel/blob/586b9e7bf5efef4d205552cc285a3f8498767578/config/filesystems.php#L44

**Comment by sathish-kumar-7777** [comment]
> https://github.com/laravel/laravel/blob/586b9e7bf5efef4d205552cc285a3f8498767578/config/filesystems.php#L44

It's not working out. I have changed either way to true and false in the filesystems config ``` throw => false ```. Could you explain a little elaborate about it?

**Comment by ankurk91** [comment]
Laravel 9 does not throw exception if any file system operation fails. But if set `throw` to true, it will

**Comment by SathishKumarA2001** [comment]
@ankurk91 
I have changed ``` throw => true ``` in the filesystems config. It's returning NULL instead of an error. But in past its returning the path of the image_file path without storing the file. I couldn't understand this behavior of laravel.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
