### ISSUE TITLE
Igbinary serializer in Redis cache driver not working properly

### ISSUE THREAD

**Issue by andreyzp87** [laravel/framework#44652]
- Laravel Version: 8.83.25
- PHP Version: 8.1.1
- Database Driver & Version:
Redis 6.0.6 on Ubuntu 22.04
Redis 6.2.7 on Fedora 36
PhpRedis 5.3.7

### Description:
When you enable igbinary serializer for redis in `database.php`, the actual value stored in redis is serialized with php serializer and some igbinary bytes are added at beginning.

Example:
`\Cache::put('test', ['a', 'b'])`

Actual value saved in Redis:
`\x00\x00\x00\x02\x11\x1ea:2:{i:0;s:1:\"a\";i:1;s:1:\"b\";}`

As for me, it looks like value is serialized with php serializer and afterwards is serialized with igbinary

Expected value in Redis (from igbinary_serialize()):
`\0\0\0\x02\x14\x02\x06\0\x11\x01a\x06\x01\x11\x01b`

Value from Redis if default serializer is used:
`a:2:{i:0;s:1:"a";i:1;s:1:"b";}`

As you see, default serializer value is even shorter than igbinary one, which should never be the case

Checked with more complex stuff, for example putting the model into cache, issue is the same - some bytes from igbinary in beginning and default serializer value aftrewards.

### Steps To Reproduce:
1. Enable `Redis::SERIALIZER_IGBINARY` serializer in `config/database.php`
2. Save some array or object to cache
3. Go to redis-cli and compare the value inside redis with `igbinary_serialize()` result

**Comment by it-can** [comment]
does ```\Cache::get('test')``` also show incorrect data?

**Comment by andreyzp87** [comment]
> does `\Cache::get('test')` also show incorrect data?
> 
> If I test it:
> 
> Redis stores this <img alt="Schermafbeelding 2022-10-19 om 19 47 11" width="374" src="https://user-images.githubusercontent.com/644288/196766580-0fdc2513-b3a8-443c-8a97-2e492a7de1c3.png">
> 
> ```
> \Cache::put('test', ['a', 'b']);
> dd(\Cache::get('test'));
> ```
> 
> ```
> array:2 [▼ // app/Http/Controllers/HomeController.php:27
>   0 => "a"
>   1 => "b"
> ]
> ```
> 
> For me it seems to work...

Actually you confirmed the bug :)

The cache put-get works, no problem with it. Problem is in the actual data stored in Redis.
If you encode it with igbinary `igbinary_encode(['a','b'])` you will see that there is no such stuff as `a:2:{i:0` - it's php serializer format, igbinary has much more compact representation for arrays.

What it means in real life for the project where I work - when igbinary serializer worked fine, all our redis cache took around 1.2-1.5 gigabytes of RAM. When this bug appeared - redis RAM usage stared hitting 5+ gigabytes.
And when I switched to regular php serializer - these 5 gigabytes stayed the same, so igbinary now does not give any benefits right now.

The problem appeared when we migrated from ubuntu 18.04 to 22.04 and php 8.0 to php 8.1 and updated all project dependencies.

**Comment by it-can** [comment]
ok but is this a laravel or phpredis bug then?

**Comment by andreyzp87** [comment]
Not sure if I can confirm that. Will try our previous setup with latest laravel and get back here.

**Comment by andreyzp87** [comment]
It's not phpredis bug, try this code:

```
$client = new \Redis();

$client->connect('127.0.0.1', 6379);

$client->select(0);
$client->setOption(Redis::OPT_PREFIX, 'r:');
$client->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);

$client->set('test', ['a', 'b']);
var_dump($client->get('test'));
```

When I check it in redis-cli:
```
127.0.0.1:6379> get r:test
"\x00\x00\x00\x02\x14\x02\x06\x00\x11\x01a\x06\x01\x11\x01b"

```

So the actual value in redis is the expected igbinary encoded array. But it's not the case with laravel Cache
Need some more time to check our old setup

**Comment by it-can** [comment]
can you also post some version numbers?

**Comment by it-can** [comment]
Laravel seems to set the serializer config option correct on the connector though...

<img width="770" alt="Schermafbeelding 2022-10-20 om 10 18 24" src="https://user-images.githubusercontent.com/644288/196895082-bc98baeb-0de6-4ae1-8e43-ce1b5e52ec3d.png">

**Comment by andreyzp87** [comment]
Same as in my initial message:
Laravel Version: 8.83.25
PHP Version: 8.1.1
Database Driver & Version:
Redis 6.0.6 on Ubuntu 22.04
Redis 6.2.7 on Fedora 36
PhpRedis 5.3.7

Just checked our old setup, it has the same problem, not sure why memory consumption increased.

Please, check this one, there is a hardcoded php serializer there:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/RedisStore.php
line 334

So how it works now in laravel - we always encode everything with php serializer, and afterwards redis encodes serialized string with igbinary.
As I understand it - there is no point on using the igbinary serializer in redis config, it just adds some overhead to redis. We already pass serialized string as value.

It would be a nice feature to have in config - change the serializer/unserializer function. So use `igbinary_serialize` instead of default `serialize`.
For now for my project I'll just extend the RedisStore overriding the `serialize/unserialize` functions in this class.

Sorry for wasting your time, you can convert this ticket to a feature request if you think it's nesessary.

**Comment by webard** [comment]
I think `serialize` method should be used by framework only when `'serializer'` option in config is set as `Redis::SERIALIZER_NONE`. In other serializers, even `Redis::SERIALIZER_PHP`, the extension is reponsible for serializing data.

**Comment by it-can** [comment]
> I think `serialize` method should be used by framework only when `'serializer'` option in config is set as `Redis::SERIALIZER_NONE`. In other serializers, even `Redis::SERIALIZER_PHP`, the extension is reponsible for serializing data.

this library seems to do this

https://github.com/akalongman/laravel-lodash#redis-using-igbinary

**Comment by webard** [comment]
Yeah and look what they do with `serialize`/`unserialize`: https://github.com/akalongman/laravel-lodash/blob/67b4d5206d3118cff9bce3d4f718ebd9b2ee6491/src/Lodash/Cache/RedisStore.php#L11-L19

**Comment by andreyzp87** [comment]
Just tested such setup:
```
<?php

namespace App\Extensions;

use Illuminate\Cache\RedisStore;

class RedisStoreFixed extends RedisStore
{
    public function serialize($value)
    {
        return $value;
    }

    public function unserialize($value)
    {
        return $value;
    }
}
```

And it's loaded like that:
```
    protected function createRedisDriver(array $config)
    {
        $redisConfig = config('database.redis', []);

        if (class_exists('Redis')
            && defined('Redis::SERIALIZER_NONE')
            && isset($redisConfig['options']['serializer'])
            && $redisConfig['options']['serializer'] !== \Redis::SERIALIZER_NONE
        ) {
            $redis = $this->app['redis'];

            $connection = $config['connection'] ?? 'default';

            $store = new RedisStoreFixed($redis, $this->getPrefix($config), $connection);

            return $this->repository(
                $store->setLockConnection($config['lock_connection'] ?? $connection)
            );
        }

        return parent::createRedisDriver($config);
    }
```

Everything works flawlessly with any serializer.

I'm not sure how to do it properly in a form of a pull-request, it would be nice if someone makes it.

**Comment by webard** [comment]
Did you check `Redis::SERIALIZER_NONE`?

**Comment by andreyzp87** [comment]
> $redisConfig['options']['serializer'] !== \Redis::SERIALIZER_NONE

I don't load modified RedisStore if serializer is none:
`$redisConfig['options']['serializer'] !== \Redis::SERIALIZER_NONE`

**Comment by it-can** [comment]
Why is the serialize() function there in the first place? Is that needed for predis?

**Comment by andreyzp87** [comment]
> Why is the serialize() function there in the first place? Is that needed for predis?

Not sure about that, I did not follow the development.
I guess previously it was used with `none` serializer from phpredis, and an option to use redis serializer was added not so long ago.

**Comment by webard** [comment]
Laravel supports native phpredis extension and predis library written in pure PHP. Predis seems not support serialisation, so Laravel implementation should call serialize/igbinary_serialize/msgpack_pack to serialize data. If PHPRedis is used, serialisation should be matter of extension, not framework. Option `\Redis::SERIALIZER_NONE` should be unavailable, default option should be `\Redis::SERIALIZER_PHP`, because of compatibility.

PR should be simple, but the problem is with existing records. It is very likely that records saved before change will be corrupted.

**Comment by ReDev1L** [comment]
This is long time ignored bug.
https://github.com/laravel/framework/issues/26186

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
