### ISSUE TITLE
View events not firing anymore since 9.36

### ISSUE THREAD

**Issue by stayallive** [laravel/framework#44650]
- Laravel Version: 9.36.2 (same for 9.36.0 & 9.36.1)
- PHP Version: 8.1.10

### Description:

Listening to composing events no longer seems to work, probably related to: #44487.

```php
$this->app['events']->listen('composing:*', ...);            // barryvdh/laravel-debugbar
$this->app['events']->listen("composing: {$viewName}", ...); // laracasts/utilities
```

Unsure if this was ever intended to work but this seems like a very breaking change since this always used to work and people are seemingly relying on it. It looks like an unintentional BC slipped in the 9.36 release.

### Steps To Reproduce:

The easiest is to install `barryvdh/laravel-debugbar` (barryvdh/laravel-debugbar#1354, barryvdh/laravel-debugbar#1355) for example which will no longer show any views being rendered. This also breaks `laracasts/utilities` and of course any userland code using events directly to listen for `composing:` or other view related events not registered using `View::composer`.

**Comment by bjhijmans** [comment]
I noticed the same thing. It only threw the event for the outermost view, but not for any views included from there.

**Comment by nunomaduro** [comment]
On the PR https://github.com/laravel/framework/pull/44487, I've consider that there is no need to fire view events if no "creators" and "composers" exist. Yet, seem that a few packages were relying on these events even without registering "creators" and "composers".

So, there is two solutions:

- 1: Revert the micro-optimization that avoids 2 events being dispatched every time a view / component gets rendered.
- 2: Pull request to those 2 lines for those packages:

```
$this->app['view']->creator('*', fn () => true);
$this->app['view']->composer('*', fn () => true);
```

**Comment by stayallive** [comment]
These are the 2 cases identified, probable that many other packages do something similar and/or userland code also relies on this. Personally I feel like this should be changed in 10.x and basically deprecate the view events.

Seems more than fine to refactor code to use `creator` and `composer` directly but it seems a little on the BC break path... but I'll leave that call up to you how you consider this since you could also argue that it was never intended for anyone to use those events directly.

**Comment by nunomaduro** [comment]
Prepared the PR, in case we decide to revert the code: https://github.com/laravel/framework/pull/44653.
