### ISSUE TITLE
Error when making assertions on mail attachments

### ISSUE THREAD

**Issue by rjorel** [laravel/framework#44666]
- Laravel Version: 9.36.3
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0

### Description:
Hey,
I've just tried the new assertions of `Mailable` class, and I've got this error when I call `assertHasAttachment()`:
`Error : Call to undefined method Illuminate\Support\Testing\Fakes\MailFake::render()`

My debugger says the error comes from `src/Illuminate/Mail/Mailable.php:1524`

### Steps To Reproduce:
Create a test for sending mail, and in `Mail::assertSent()` callback do
```php
Mail::assertSent(MyMail::class, function (MyMail $mail) {
    $mail->build();
    $mail->assertHasAttachment('foo.txt'); // Error
});
```

**Comment by eduance** [comment]
You can provide the assertSent a second argument, where the second argument is to pass a given truth test.

For example;

```
Mail::assertSent(function (OrderShipped $mail) use ($order) {
    return $mail->order->id === $order->id;
});
```
So for you to check whether the mailables have sent _when they do end up having an attachment_ would be like:

```
Mail::assertSent(MyMail::class, function (MyMail $mail) {
    $mail->build();
    $mail->assertHasAttachment('foo.txt'); // Error
});
```
You can read more about it in the documentation:
https://laravel.com/docs/9.x/mocking#mail-fake

**Comment by rjorel** [comment]
Of course, my example was not complete, I gave a way to reproduce the bug. In my actual case, I return a boolean to successfully pass the assertion.

But using `assertHasAttachment()` raises exception `Error : Call to undefined method Illuminate\Support\Testing\Fakes\MailFake::render()`.

**Comment by eduance** [comment]
@rjorel 

You shouldn't be calling the build method at all and second; you have to return the actual boolean.

```
Mail::assertSent(MyMail::class, function (MyMail $mail) {
    return $mail->assertHasAttachment('foo.txt');
});
```
You can read more about it in the documentation:
https://laravel.com/docs/9.x/mocking#mail-fake

**Comment by rjorel** [comment]
`assertHasAttachment()` method doesn't return a boolean : https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L1402

**Comment by eduance** [comment]
@rjorel Why are you rendering the mailable if you are using a fake?

If you want to actually test the rendering, an approach posted in [#2400](https://github.com/laravel/framework/issues/24005) might help you get started.

You could try;

```
        $mailerOriginal = Mail::getFacadeRoot();
        static::assertTrue(\assert($mailerOriginal instanceof MailManager));
        Mail::fake();

        // --- Your test logic. --- 

        // Note that the callback will be called as many times as there
        // were emails sent (of the given type).
        Mail::assertSent(DocumentShareAccess::class, function (DocumentShareAccess $mail) use ($mailerOriginal): bool {
            // The fake has no rendering capability, so have to swap back.
            Mail::swap($mailerOriginal);

            $mail->assertSeeInHtml('contact the document owner');
            static::assertTrue($mail->hasTo($invitee->email), $invitee->email);

            return true;
        });
```

**Comment by rjorel** [comment]
I don't understand your purpose in telling me how to test sending mails.
I'm not facing a problem, I'm just reporting an error coming from a new assertion method added in Laravel 9.36 for attachments (https://laravel-news.com/laravel-9-36-0).

Calling `build()` or not doesn't change anything: an error is raised, coming from
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L1404
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L1515

**Comment by eduance** [comment]
> I don't understand your purpose in telling me how to test sending mails. I'm not facing a problem, I'm just reporting an error coming from a new assertion method added in Laravel 9.36 for attachments (https://laravel-news.com/laravel-9-36-0).
> 
> Calling `build()` or not doesn't change anything: an error is raised, coming from https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L1404 https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L1515

My apologies, just misunderstood you then!

**Comment by rjorel** [comment]
No problem 🙂

**Comment by rjorel** [comment]
Hey,

I hope I correctly did what you asked, here is my repo with the commit to reproduce the bug: https://github.com/rjorel/laravel-bug-report.

**Comment by driesvints** [comment]
I think you're confused how this is used. These methods are used to test mails separately without being sent. Please see the docs here: https://laravel.com/docs/9.x/mail#testing-mailables

**Comment by IanEdington** [comment]
I'm surprised at this answer. Why would the framework limit us from testing render in this context when there's no technical reason not to?

For context, I come from an integration test heavy background, common at many large companies. Instead of instantiating a mailer directly, this strategy tests many internal components at the api/view level. For applications with tightly coupled components this strategy allows more flexibility with the same amount of coverage at the expense of additional test runtime.

One of the benefits of this strategy is that your tests don't break as often with refactors. For example if I were to change the structure of the data going into a mailier and had tests at the mailier level, I would have to change the structure of the data in every the tests. In the view/api level test, the data structure would be changed in both the call location and the class signature so no change to the tests would be needed.

Why does Laravel intentionally block me from being able to do this?

**Comment by willpower232** [comment]
I am here to second the above comment and also thank the OP for the `getFacadeRoot` approach.
