### ISSUE TITLE
Sometimes EncryptionServiceProvider not getting configs form .env "No application encryption key has been specified" error!

### ISSUE THREAD

**Issue by ss-koshala** [laravel/framework#44684]
- Laravel Version: 8.33.25
- PHP Version: 8.0.13
- Database Driver & Version: MySQL 5.7.36

### Description:
Sometimes EncryptionServiceProvider not getting configs form .env
$config = $app->make('config')->get('app');
here $config not getting from .env file. So key filed empty and getting "No application encryption key has been specified" error.

### Steps To Reproduce:
In laravel nova admin load "View" on a resource
"nova-api/roles/actions?viaResource=users&viaResourceId=2&viaRelationship=roles&relationshipType=morphToMany&display=index"
like this.

I know it is nova related issue but issue with laravel. Hope some one can help this.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
