### ISSUE TITLE
[Queue] Backoff is ignored if a job is retried after it was killed due to timeout

### ISSUE THREAD

**Issue by hjeldin** [laravel/framework#44680]
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Version: MySQL

### Description:
Basically a duplicate of https://github.com/laravel/framework/issues/30509
We have a job that uploads data to an S3 bucket. Sometimes the S3 API we're using stalls due to a temporary networking issue.
We'd like to be able to specify a different retry time via the backoff function available on the job interface.
The backoff parameter gets ignored if the worker has a timeout inferior to the stall time of the job. 
This is due to the different path a worker uses to be killed when a job times out (see [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Queue/Worker.php#L164) and [here](https://github.com/laravel/framework/blob/a709c26b8e37b20826e8ebe7fa14d29751fedcc5/src/Illuminate/Queue/Worker.php#L429)).

In order for the worker to be killed correctly after a timeout and the job to use the backoff parameter correctly we applied this patch, which introduces a new Exception type, handles the timeout exception and then kills the worker.
```git
diff --git a/src/Illuminate/Queue/JobTimeoutException.php b/src/Illuminate/Queue/JobTimeoutException.php
new file mode 100644
index 0000000000..c65073766d
--- /dev/null
+++ b/src/Illuminate/Queue/JobTimeoutException.php
@@ -0,0 +1,19 @@
+<?php
+
+namespace Illuminate\Queue;
+
+use RuntimeException;
+
+class JobTimeoutException extends RuntimeException
+{
+    /**
+     * Create a new exception instance.
+     *
+     * @param  string|null  $message
+     * @return void
+     */
+    public function __construct($message = null)
+    {
+        parent::__construct($message ?: json_last_error());
+    }
+}
diff --git a/src/Illuminate/Queue/Worker.php b/src/Illuminate/Queue/Worker.php
index 039cbebb30..48616824c4 100644
--- a/src/Illuminate/Queue/Worker.php
+++ b/src/Illuminate/Queue/Worker.php
@@ -223,7 +223,7 @@ protected function registerTimeoutHandler($job, WorkerOptions $options)
                 );
             }
 
-            $this->kill(static::EXIT_ERROR);
+            $this->handleJobException($job->getConnectionName(), $job, $options, new JobTimeoutException("Job timeout reached"));
         });
 
         pcntl_alarm(
@@ -473,7 +473,11 @@ protected function handleJobException($connectionName, $job, WorkerOptions $opti
             }
         }
 
-        throw $e;
+        if($e instanceof JobTimeoutException) {
+            $this->kill(static::EXIT_ERROR);
+        } else {
+            throw $e;
+        }
     }
 
     /**

```

If nobody sees anything wrong with this i'd like to open a pull request with these changes.

### Steps To Reproduce:

Create a new job with backoff, timeout, retries and in its handle method put a sleep for more than the job's timeout.
Example code:
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class BackoffJobDelay implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function backoff() {
        return [5, 10, 20];
    }

    public $timeout = 10;
    public $tries = 4;

    public function handle()
    {
        Log::info("PCNTL installed: ". (extension_loaded("pcntl") ? "true" : "false"));
        Log::info("Sleeping for 120 seconds");
        sleep(120);
        Log::info("Resumed from sleep");
    }
}

```
Start a queue worker:
```sh
$ php artisan queue:work
```

Dispatch the job via tinker onto a mysql db:
```sh
$ php artisan tinker
> \Bus::dispatch(new \App\Jobs\BackoffJobDelay());
```
After the canonical 90 seconds the worker gets killed and the job is dispatched again without waiting for the specified backoff time.

**Comment by taylorotwell** [comment]
If you feel a change should be made you can open a PR for review.
