### ISSUE TITLE
request()->merge(...) does not work any more after `v9.36.4`  update

### ISSUE THREAD

**Issue by buglinjo** [laravel/framework#44687]
- Laravel Version: 9.36.4
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.1

### Description:
After update to 9.36.4 `request()->merge(...)` stopped working and does not replace the input.

### Steps To Reproduce:
Use the `request()->merge(['a' => 'c'])` on the json request which has `{"a": "b"}` in the request body.

**Comment by buglinjo** [comment]
This is the actual change what is causing this problem.

![image](https://user-images.githubusercontent.com/1254208/197274564-4d1ede1f-81cc-436d-9e6a-1099276353df.png)

**Comment by rodrigopedra** [comment]
Can't reproduce on a fresh Laravel install. Can you provide a public repo with the code to reproduce?

Steps I made:

~~~shell
$ laravel new test
// output hidden for brevity
$ cd test
$ php artisan --version
Laravel Framework 9.36.4
$ php artisan serve

   INFO  Server running on [http://127.0.0.1:8000].  

  Press Ctrl+C to stop the server
~~~

Changed `./routes/web.php` to:

~~~php
Route::get('/', function () {
    return view('welcome');
});

Route::post('/', fn () => request()->merge(['a' => 'c'])->all());
~~~

And `./resources/views/welcome.blade.php` to:

~~~blade
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
    </head>
    <body>
    <form action="/" method="POST">
        @csrf
        <input type="text" name="a" value="b">
        <button type="submit">send</button>
    </form>
    </body>
</html>
~~~

Visited http://127.0.0.1:8000/ and hit the send form button.

Result:

~~~json
{"_token":"wUamevrMvmL0QvdmmVg4eYt5aMw3I0aDNrO2NcPE","a":"c"}
~~~

If I am doing something wrong, please let me know.

**Comment by buglinjo** [comment]
@rodrigopedra Thanks for the response.

Unfortunately the repo I'm using this is private and can't share the code here.

From you testing I see that you are using the same instance of `request()`. Please try this instead:
```php
    Route::post('/', function() {
        request()->merge(['a' => 'c']); 
        
        return request()->all();
    });
```

**Comment by rodrigopedra** [comment]
@buglinjo I did the change you suggested and I still can't reproduce...

I uploaded a repository, so you can double check:

https://github.com/rodrigopedra/laravel-issue-44687

I even used `composer bump` to ensure Laravel is in 9.36.4 version

**Comment by rodrigopedra** [comment]
@buglinjo 

I just made a commit with a route that merges data into the request inside a validation rule. And it still behaves as expected. 

Please review it, if you can, and add any comments on how to reproduce it.

I somehow missed your last comment regarding you were using a validation rule.

**Comment by rodrigopedra** [comment]
@buglinjo 

one more thing: if you find anything that should be changed, it is easier if you send a PR to the repository.

Also, I checked two of my own projects where I use `$request->merge()` after a form request's validation to replace, for example, dates with carbon instances into the request, and they are working as expected with Laravel latest version.

**Comment by siarheipashkevich** [comment]
The same issue also.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by rodrigopedra** [comment]
@buglinjo I answered your PR with additional info: https://github.com/rodrigopedra/laravel-issue-44687/pull/1#issuecomment-1289449990

Unfortunately, as you can read there, this is a known behavior and kind of expected behavior in the maintainers' opinion.

**Comment by buglinjo** [comment]
@rodrigopedra 
Oh, I see now what's going on. So the recent changes just made it clear and it is expected. I'll have to rewrite huge amount of code to make this work, but I don't see any other option. I have been using this approach for lots of requests.

Thanks for clarifying!

**Comment by rodrigopedra** [comment]
@buglinjo I agree with you in that matter, so I sent the PR I talk about in the comment linked above. 

But sometimes we have to deal with how things are... Good luck and sorry for not finding a solution. Have a nice day =)

**Comment by siarheipashkevich** [comment]
@rodrigopedra thanks for your response.

Could you please help me how I need rewrite my code by new style?

![image](https://user-images.githubusercontent.com/7753600/197625783-d8f99713-4acf-4bad-a621-7b4287bb7f76.png)

`$input` data doesn't merge to the request and doesn't pass to proxy and.

**Comment by rodrigopedra** [comment]
@siarheipashkevich this kind of question is suits better a support channel, as per Laravel docs:

https://laravel.com/docs/9.x/contributions#support-questions

That said, I guess you need to merge your data with the request instance you created manually and are dispatching. When manually creating a request instance it won't inherit the data from any other instance automatically.

~~~php
protected function getToken(Request $request)
{
    $input = array_merge($this->getClientCredentials(), [
        'username' => $request->input('email'),
        'password' => $request->input('password'),
        'grant_type' => 'password',
        'scope' => '',
    ]);

    // $request->merge($input); // <<< I GUESS THIS IS UNNEEDED

    $proxy = Request::create('/oauth/token', 'POST');

    $proxy->merge($input); // <<< ADDED THIS

    return Route::dispatch($proxy);
}
~~~

Please next time look for a support channel for this kind of questions =)

**Comment by buglinjo** [comment]
Just letting you know how I fixed the issue.

I just added this code in my controller after validation and everything seems to be fixed. Not sure if this is clean solution or correct solution, but this works 😄 

```php
$request->merge(request()->all());
```
