### ISSUE TITLE
BadMethodCallException with appended Laravel 9 Accessors

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#44688]
- Laravel Version: 9.36.1
- PHP Version: 8.1.11
- Database Driver & Version: PgSQL 14

### Description:
Calling `toArray()`/`attributesToArray()` on a model that has an appended Laravel 9 accessor generates the following error:

```
BadMethodCallException: Call to undefined method <model>::get<attribute>Attribute()

/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71
/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:36
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2321
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:657
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:707
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:213
/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1629
// ...
```

### Steps To Reproduce:
1. Define a Laravel 9 Attribute on a model
2. Add the attribute to the `$appends` property
3. Attempt to convert model to array

**Comment by KadSin** [comment]
I think it's better to define an accessor method which return your model's attribute, refer to uncle bob's clean code when you determine a attribute, if it is read only then you should isolate your attribute.

```php
protected function <attributeName>(): Attribute
{
    return Attribute::get(fn () => $this-><attributeName>);
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by CalebDW** [comment]
@driesvints,

Thanks for responding, the repo is below. After further inspection the problem seems to lie with `camelCase` attribute names---I defined two accessors on the User model (`initials` and `firstName`), but only `firstName` throws the BadMethodCallException when converting the model to an array.

https://github.com/CalebDW/bug-report

Commands to reproduce:
```php
sail up -d
sail art migrate --seed
sail tinker

$u = User::first()
$u->initials // works
$u->first_name // works

$u->toArray() // fails with trying to call `getFirstNameAttribute()`
```
However, if you take `firstName` out of the `$appends` array then the above code works without issue.

Thanks!

**Comment by CalebDW** [comment]
Actually, looks like the issue was in how I defined the accessor in the `appends` array, updating to `first_name` causes the above code to work:

```php
    protected $appends = [
        'firstName', // should be 'first_name'
        'initials',
    ];
```

I suppose we can close this issue, but perhaps you would still like to update the framework to generate a more meaningful error or cast all of the `appends` to `snake_case` to prevent this from occuring?

**Comment by driesvints** [comment]
Ah yes we don't support camelcase. Only snake case. I'm not sure it's possible to throw a specific exception there as the model has no idea how the columns look like. There's no way to know if there is a `firstName` column or not.
