### ISSUE TITLE
Unexpected behavior with authentication

### ISSUE THREAD

**Issue by ax-ross** [laravel/framework#44699]
- Laravel Version: 9.31.0
- PHP Version: 8.1.11
- Database Driver & Version: Mysql 8

### Description:
I'm not sure if this is a bug, but it's very strange behavior in my opinion.
I'm using sanctum spa auth with session. My session driver is cookie. I authenticated in my web site and went to do other things (seeding DB). When I comeback in my web site I saw what now I another user (not the one who I authenticated). This happened (I think) because I authenticated like user with id 10 then I deleted user with this id from my DB and create new user with same id. Because I used cookie session driver, session is still valid for user with id 10. May be for many this behavior its normal, but it turned out not expected for me.

### Steps To Reproduce:

I described it above

**Comment by eduance** [comment]
Could you share some code with us to reproduce it?

If you feel it's an issue with sanctum, feel free to open a ticket on the Sanctum repository: https://github.com/laravel/sanctum

**Comment by ax-ross** [comment]
Yes, I can.
Its not specific only for sanctum.

I created repo: https://github.com/ax-ross/laravel_session_auth_issue/tree/master

You just need clone it, run migrate, npm install and php artisan serve. Then you need to create user. For example: "name": "test", "email": "test@gmail.com". You will see its data on dashboard page after registration. Next, you go to sqlite database (in my case I'm using phpstorm) and remove this user. Next, you create new user with same ID (1, its important!) and another data, for example "name": "test2", email: "test2@gmail.com". Now, back to your browser to dashboard page and press F5. You will see new authed user with new credentials, but you don't need to login (session cookie is valid).

**Comment by eduance** [comment]
@ax-ross As far as I can tell this is necessary due to the session needing some kind of identifier; I don't see any problems with this as the session is only held by one user. What could be your concern?

**Comment by ax-ross** [comment]
@eduance For example, I will describe such a case:
I have some user with bad nickname and with ID 10. He's authenticated on web site. After some time Admin saw his nickname and delete this user from admin panel. Next, on web site register new admin user, who have now ID 10. As a result user with bad nickname authorized on site with admin permissions.
It's far-fetched case, because usually in users table we are using softDeletes, but  I faced with similar case when I seeding my DB. 
If you think it's okey, I'm sorry for wasting your time.
