### ISSUE TITLE
Different R/W databases causes batches to fail

### ISSUE THREAD

**Issue by RyonMB** [laravel/framework#44691]
- Laravel Version: 9.12.2
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8.0
- Using Laravel Horizon

### Description:
When using different read and write databases in production between your web server and worker servers, some batches will fail randomly.

Error:
`PHP Error:  Call to a member function add() on null in /home/forge/./vendor/laravel/framework
/src/Illuminate/Bus/PendingBatch.php on line 259`

![CleanShot 2022-10-22 at 15 56 35@2x](https://user-images.githubusercontent.com/43067960/197343015-5d30e21b-6ac8-442f-9dcc-ca7cb6734fa1.png)

### Steps To Reproduce:

```
class getDataJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public $page = 1;

    public function __construct($page = 1)
    {
        $this->page = $page;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $batch = Bus::batch([])
            ->allowFailures()
            ->name('... - ' . Carbon::now()->toDayDateTimeString())
            ->onQueue('bol_jobs')
            ->dispatch();

        Team::cursor()
            ->filter(function ($team) {return $team->owner->is_subscribed == true && $team->connected;})
            ->map(fn(Team $team) => new getData($team, $this->page))
            ->chunk(100)
            ->each(function (LazyCollection $jobs) use ($batch) {
                $batch->add($jobs);
            });
    }
}
```

Database setup:
Using 2 databases:
A: 1 (main database) r/w
B: 1 (read slave) r

For the webserver we used this setup
- A for w
- B for r

For the worker servers
- We only use database A for r/w

When switching the web server to only use database A for r/w everything works fine.

**Comment by driesvints** [comment]
I don't think you're using this how it was intended. Adding jobs to batches is only intended to do from within a job that belongs to a batch. Your code doesn't seem to match that and you're already dispatching the batch on a queue while adding jobs later on. 

Please read the example at https://laravel.com/docs/9.x/queues#adding-jobs-to-batches thoroughly and if you need further help try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by abhiburk** [comment]
Hi,
Well I am facing same error,
I have a Job `TestBatchableJob.php` which use `Batchable` trait and inside this job I am using `$this->batch()->add(New MyJob())`.

So In my case sometimes I do use `$this->batch()` in some jobs and sometimes I don't use `$this->batch()` at all but still it throws me the error
`PHP Error:  Call to a member function add() on null in /home/forge/./vendor/laravel/framework /src/Illuminate/Bus/PendingBatch.php on line 259`

I am not using `$this->batch()` outside the batchable job. 

Note: This doesn't happen every time. The same job runs successfully and sometimes this error is being thrown. This happens in few batchable jobs.
