### ISSUE TITLE
Database: Relations with key type string not found if case mismatch

### ISSUE THREAD

**Issue by xerenahmed** [laravel/framework#44692]
- Laravel Version: Just using database package
- PHP Version: 8.1.11
- Database Driver & Version: v9.36.4

### Description:
Relations with key type string not found if case mismatch

### Steps To Reproduce:

I have three tables. Just example

Table `players`:
username | string | primary
other stuff | any | any

Table `player_groups`
username | string | foreign key
group_label | string | foreign key
other stuff | any | any

Table `perm_groups`
label | string | primary key
other stuff | any | any

I wrote relation like this:
```php
public function groups(): BelongsToMany{
    return $this->belongsToMany(PermGroupModel::class, 'player_groups', 'username', 'group_label');
}
```

If `players.username` is 'xerenahmed' and `player_groups.username` is 'xErenAhmed' groups gets empty. If I get SQL from belongsTo and run it on MySQL, I see the rows that should be.

**Comment by xerenahmed** [comment]
Related here https://github.com/illuminate/database/blob/bd88721cabecee43c9ebc4398a9fcedea7f22092/Eloquent/Relations/BelongsToMany.php#L278-L290

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Also please specify the laravel version next time.
