### ISSUE TITLE
Can't prevent error 500 using Route::resource/apiResource in pgsql

### ISSUE THREAD

**Issue by crazynds** [laravel/framework#44697]
- Laravel Version: 9.35.1
- PHP Version: 8.1.4
- Database Driver & Version: pgsql 13

### Description:

I came across the problem started while testing a route generated using Route::apiResource, and noticed that when any string is sent as a parameter, an error 500 occurs due to Laravel performing a database query.

When an integer is set as the parameter, it finds the model by its id and binds it properly:
![image](https://user-images.githubusercontent.com/36674096/197398300-73bee07b-2523-496c-895a-a102b7bd7201.png)

On the other hand, it throws a status of 500 when the parameter is a string:
![image](https://user-images.githubusercontent.com/36674096/197398351-489206ef-b38b-40a8-a3be-6a06b9ccb062.png)

The route is defined as follow:
```php
<?php

use Illuminate\Support\Facades\Route;

// /api/...

Route::apiResource('client', 'ClientController');
```
Some solutions I thought of:

- Catch the exception and ignore it. However, this solution prevents other database exceptions from being logged that have not yet been identified in the system.
- Apply a regex to the parameter and laravel just ignores the route and displays a 404. However, it is not possible to apply a regex to a resource or an apiResource. *

Without the regex rule, the server receiving a string when it expects to receive an integer in the parameter returns an error 500, which should not happen. It should just show that the route was not found (404) or that the request is invalid (400 or 422), since its a client error, not the other way around.

*There is a way to define a pattern in a route parameter, and this pattern applies to resources as well, as explained in this [thread](https://stackoverflow.com/questions/22622629/regular-expression-route-constraint-for-a-resource-route), however, it does not scale.

### Why shouldn't we let error 500 happen?

Code 500 is defined as "The server has encountered a situation it does not know how to handle.". And in this case we know exactly what the problem is and if we can ignore the request, or respond with a status of an invalid request (400-499), so if we want to keep track of all the server errors 500 to be able to fix them in the future, the system will be filled with false errors. 

### Steps To Reproduce:

- Create a complete CRUD of one model and use resource to bind the routes.
```php
<?php

use Illuminate\Support\Facades\Route;

// /api/...

Route::apiResource('client', 'ClientController');
```
- Send a request with string instead of integer in the parameter
- Error 500 happened 😔

Edit:

As mentioned by @dwightwatson, this error only happens when using postgresql.

**Comment by mateusmdr** [comment]
I have experienced the same problem when passing the wrong parameters to the API using Postman.

It turns out that the parameter name was not the same as the intended for that route, so the request was like: 
    GET /api/resource/:id

I didn't find any workarounds for it not raising a status 500, so I didn't bother too much with it.

**Comment by dwightwatson** [comment]
I think this is specifically a Postgres issue - I believe that MySQL will still run the SQL, find no result and 404 as expected. I define a bunch of patterns in my `RouteServiceProvider` in order to avoid this - but like you mention it's not great.

```php
Route::pattern('user', '[0-9]+');
```

Not sure how best you could solve this. Under the hood I suspect it's using `UrlRoutable` on the model, so perhaps you could overwrite [`resolveRouteBinding`](https://github.com/laravel/framework/blob/82c7dac8c403c4c1782a169b3f55c953cb0be3d9/src/Illuminate/Database/Eloquent/Model.php#L2036-L2039) on your models to cast the value to an integer first?

**Comment by crazynds** [comment]
> I think this is specifically a Postgres issue - I believe that MySQL will still run the SQL, find no result and 404 as expected. I define a bunch of patterns in my `RouteServiceProvider` in order to avoid this - but like you mention it's not great.
> 
> ```
> Route::pattern('user', '[0-9]+');
> ```
> 
> Not sure how best you could solve this. Under the hood I suspect it's using `UrlRoutable` on the model, so perhaps you could overwrite [`resolveRouteBinding`](https://github.com/laravel/framework/blob/82c7dac8c403c4c1782a169b3f55c953cb0be3d9/src/Illuminate/Database/Eloquent/Model.php#L2036-L2039) on your models to cast the value to an integer first?

This way i think will work, but I don't think it's the cleanest way to code. I'll implement it in my project to temporarily resolve, but I believe laravel should add a validation in the resource paths would be very important.

I think the best solution to this problem is to add a [*where, whereNumber, whereAlpha*](https://laravel.com/docs/9.x/routing#parameters-regular-expression-constraints) function to the Route::resource like the normal routes (get, post, put).

In this way the router never enter in the route if the regex fail, and return 404 error.

**Comment by driesvints** [comment]
There is no way for us to know up front that the value can't be handled by the database. You need to sanitize the parameter as @dwightwatson indicates.
