### ISSUE TITLE
Vite with React refresh blocked by Content-Security-Policy

### ISSUE THREAD

**Issue by oulfr** [laravel/framework#44708]
- Laravel Version: 9.36.4
- PHP Version: 9.0

### Description:
Vite '@viteReactRefresh' directive is blocked by CSP (Content-Security-Policy)

### Steps To Reproduce:
use @viteReactRefresh in welcome.app.php

**Comment by driesvints** [comment]
I don't get any error in my console. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by oulfr** [comment]
@driesvints : you need to enable the CSP, by adding the CSP middleware like in the doc for example

**Comment by driesvints** [comment]
What CSP middleware?

**Comment by oulfr** [comment]
this is the middleware:

https://laravel.com/docs/9.x/vite#content-security-policy-csp-nonce

Now in the file Vite.php there is a methode like this:

`/**
     * Generate React refresh runtime script.
     *
     * @return \Illuminate\Support\HtmlString|void
     */
    public function reactRefresh()
    {
        if (! $this->isRunningHot()) {
            return;
        }

        return new HtmlString(
            sprintf(
                <<<'HTML'
                <script type="module">
                    import RefreshRuntime from '%s'
                    RefreshRuntime.injectIntoGlobalHook(window)
                    window.$RefreshReg$ = () => {}
                    window.$RefreshSig$ = () => (type) => type
                    window.__vite_plugin_react_preamble_installed__ = true
                </script>
                HTML,
                $this->hotAsset('@react-refresh')

            )
        );
    }`

This script is bloqued by the CSP policies beccause it's not containes the nonce

**Comment by driesvints** [comment]
I don't think you can combine those, sorry.
