### ISSUE TITLE
Database: Relations with key type string ignoring if case mismatch in case insensitive table

### ISSUE THREAD

**Issue by xerenahmed** [laravel/framework#44709]
https://github.com/laravel/framework/issues/44692

MySql server version: `8.0.29`
MySql server running on docker: `mysql@sha256:548da4c67fd8a71908f17c308b8ddb098acf5191d3d7694e56801c6a8b2072cc`
Database engine and collation: `InnoDB & utf8_turkish_ci`

I do not use laravel where I use `illuminate/database` so I can not give laravel version.

**Comment by driesvints** [comment]
Please don't link to other issues and provide a FULLY written out issue template. Please replace the laravel version with the illuminate database version that you're using.
