### ISSUE TITLE
Route::controller doesn't exist

### ISSUE THREAD

**Issue by TrinhLeOpteon** [laravel/framework#44720]
- Laravel Version: v8.73.2

### Description: In the laravel document, I see route controller as below, but i can't find out function in laravel router.
![image](https://user-images.githubusercontent.com/112928992/197643367-41a0ed5e-4eda-42fe-8d8a-ff3372b69a91.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
