### ISSUE TITLE
Broken fresh laravel project on v9.37.0

### ISSUE THREAD

**Issue by lmeraki** [laravel/framework#44738]
- Laravel Version: 9.37.0
- PHP Version: 8.1.11
- Database Driver & Version: MariaDB 10.6.10

### Description:
 a blank page on fresh laravel project after running `npm run dev`, while `npm run build` works fine. I think after this PR #44096.

Additional:
- nodejs: 16.18.0
- npm: 8.19.2
- vite: 3.1.8

### Steps To Reproduce:
1. `composer create-project laravel/laravel example-app`
2. `composer require laravel/breeze --dev`
3. `php artisan breeze:install vue`
4. `npm run dev`

**Comment by iquad** [comment]
+1 for broken fresh page. 

I assume [that](https://github.com/laravel/breeze/pull/196/files#diff-c1bb84007e95fb4ddf60a69603865922b4d22d4899f7f45551fa52a1ddeb901b) change brokes. 

#44096 should add needed link headers, but seems like `Vite::preloadedAssets()` returns empty.

Changing `@vite("resources/js/Pages/{$page['component']}.vue")` to `@vite('resources/js/app.js')` works.

**Comment by joshuadabejero** [comment]
+1 for broken fresh page.
Displays Blank Screen.

![image](https://user-images.githubusercontent.com/29270980/197957349-777f105e-7a4d-4854-b70d-d1c2e16c11ba.png)

Hopefully will get the fix soon!

Thanks @lmeraki for the report, now I have a peace of mind that it's not only me having this issue.

**Comment by driesvints** [comment]
Hey all. We released a fix for Breeze. Thanks!

**Comment by iquad** [comment]
Can confirm fix works.

For existing projects, no need to call `breeze:install` again.
Just change `@vite("resources/js/Pages/{$page['component']}.vue")` to `@vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])` on `resources/views/app.blade.php`

**Comment by timacdonald** [comment]
This one has been fixed in the latest release (just tagged). Sorry about that folks.

Using:

```
@vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
```

will retain the new preloading functionality and continue to work in dev mode.
