### ISSUE TITLE
Blade::compileString doesn't handle @push directives properly

### ISSUE THREAD

**Issue by adam-jones-net** [laravel/framework#44735]
I have a pretty simple blade template that I want to open and read, evaluate and then add to the output of my page.   I want to do this using code and the Blade::compileString() function.

Why do I want to do this and not just include() it within a parent blade template using standard blade directives?    Well it's because for various reasons I want this to work via a function in back-end code.

I should point out that using Blade::compileString() works fine if I load a blade template that just contains simple HTML.   However I actually need to blade @push directive and that is where the problem is.

So I have this test.bade.php template as follows:

```
@push('extra_scripts')
<script>
var helloValue="world";
</script>
@endpush
<div>
    The content in this template says: Hello <script>echo $helloValue;</script>
</div>
```

It _pushes_ the JavaScript into the main page template, received in the main templates html page header, with a @stack('extra_scripts') directive.         

If within a blade template I use _@include('test')_ then it works fine.   However doing by code doesn't.    My code is:

```
function renderTestTemplate(){
	$bladeTemplate=file_get_contents('../resources/views/test.blade.php');
	$result=Blade::compileString($bladeTemplate);
	return $result;
}
```

and what happens is that in the resulting page, the initial push directive from the blade appears as html in the visible output of the page.  I see the following appear at the start of the included test.blade.php output:  

> startPush('extra_scripts'); ?> stopPush(); ?>

I should point out that the template WAS included correctly, ie the push directive did actually work and the JavaScript in the template WAS pushed into the main page template so it could run correctly.   There is just this odd side effect that the opening blade tag is translated and appears on screen.

**Comment by driesvints** [comment]
Please fill out the issue template when submitting bug reports.

**Comment by adam-jones-net** [comment]
> Please fill out the issue template when submitting bug reports.

Ah ok sorry, when I started the post it didnt show that default text.    If I update appropriately you can re-open ?

**Comment by driesvints** [comment]
Can you try updating
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
