### ISSUE TITLE
Updating nested JSON with Eloquent requires empty $guarded array

### ISSUE THREAD

**Issue by elev8studio** [laravel/framework#44734]
- Laravel Version: 8.83.18
- PHP Version: 8.0.22
- Database Driver & Version: MySQL 8.0.30

### Description:

When trying to add or update a nested property in a JSON field using Eloquent model update, I am required to either:
- Enter every possible nested json property that may need to be updated in the fillable property on the model
- Use an empty guarded property on the model

The first option is unusable for a couple of reasons:
- JSON fields are often used for storing data with unpredictable keys. I don't want to have to keep editing the list of fillable properties all the time.
- If you have a table with lots of columns, it just becomes extremely verbose to list every column.

The second option is a security risk. For example:

Let's say I want to update a nested JSON property in the `data` column. 
```php
$model->update(["data->something_else" => [...]]);
```
That only works if my `$guarded` property is an empty array. Well, that's a big security risk. I want my guarded property to look this and still be able to update a nested property in a JSON column. 
```php
$guarded = ["id"]`;
```

Why does guarding the `id` column prevent me from updating the `data` column? Surely that's completely unnecessary? 

Please update the code so that I can update a nested property in a JSON column _without_ having to unguard my `id` column.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by elev8studio** [comment]
That link shows you support security fixes until January 24th, 2023. This has security implications.
