### ISSUE TITLE
No way to check for attribute existence in Eloquent Strict Mode

### ISSUE THREAD

**Issue by levu42** [laravel/framework#44746]
- Laravel Version: 9.35.1
- PHP Version: 8.1.11

### Description:

Imagine a conditional loading of a count in an Eloquent query:

```php
if ($bool) $query = $query->withCount('foo');
```

Then I want to check in blade whether the count is loaded or not, but in the new Eloquent strict mode, all options I tested threw a `MissingAttributeException`:

```php
@if($model->foo_count)
@if(isset($model->foo_count))
```

And some years and Laravel versions back there [was a decision made against a `hasAttribute` method on the `HasAttributes` trait](https://github.com/laravel/framework/pull/22250).

I think this should be reconsidered now, either fixing it so that you can check with `isset` on the existence of attributes, or include a `hasAttribute` method.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/pull/44717

**Comment by levu42** [comment]
@driesvints thank you, didn't notice that one :)

**Comment by royduin** [comment]
It's added in Laravel 11.3: https://github.com/laravel/framework/pull/50909
