### ISSUE TITLE
Invokeable Rules don't work for Rule::forEach() under nested array property validation.

### ISSUE THREAD

**Issue by nearueng** [laravel/framework#44756]
- Laravel Version: 9.37.0
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8

### Description:

Validation: Having an invokeable Rule object as part of the `Rule::forEach` closure in a nested array throws an error on the latest version of Laravel.

The error is: `trim(): Argument #1 ($string) must be of type string, Illuminate\Validation\InvokableValidationRule given`

Stack trace:

```
TypeError : trim(): Argument #1 ($string) must be of type string, Illuminate\Validation\InvokableValidationRule given
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:250
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:232
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1030
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1011
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:752
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:709
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:601
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:417
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:448
 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:490
 /var/www/html/vendor/livewire/livewire/src/ComponentConcerns/ValidatesInput.php:206
```

### Steps To Reproduce:

- Have a validation rule for a nested array property like the following.

```
            'additional_users.*.email' => [
                'bail',
                'required',
                'email',
                Rule::forEach(function ($value, $attribute) {
                    return [
                        new EnsureUserEmailDoesNotAlreadyExistInAdditionalUsersColumn($this->booking, $value),
                    ];
                }),
            ],
```

`EnsureUserEmailDoesNotAlreadyExistInAdditionalUsersColumn` is a new Invokeable rule and thus causes an error.

**Comment by dyriavin** [comment]
@nearueng I guess it will be nice to attach implementation of your Invokable rule.

**Comment by nearueng** [comment]
@dyriavin In this instant, I just converted it to an inline rule for now to keep it working, but I'll put the original implementation below. Interestingly enough, even a regular rule was causing an error here.

```
class EnsureUserEmailDoesNotAlreadyExistInAdditionalUsersColumn implements InvokableRule
{
    public function __construct(
        protected Booking $booking,
        protected ?string $email
    ) {
    }

    /**
     * Run the validation rule.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  \Closure(string): \Illuminate\Translation\PotentiallyTranslatedString  $fail
     * @return void
     */
    public function __invoke($attribute, $value, $fail)
    {
        $emailAlreadyExists = collect($this->booking->additional_users)->pluck('email')->contains($this->email);

        if ($emailAlreadyExists) {
            $fail('This email already exists on this booking.');
        }
    }
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
I'll re-open this once a repo is provided.

**Comment by abbluiz** [comment]
I'm having the exact same problem.

**Comment by abbluiz** [comment]
I have reproduced the error in Laravel v9.39.0, v9.38.0 and v9.36.4.

Had to downgrade to v9.19.0 which was the version I was using before upgrading, and then it worked.

@driesvints Apparently to reproduce you just have to use an InvokableRule as one of the rules used in a `Rule::forEach()`, not sure why you're asking for a repository.

**Comment by aihowes** [comment]
Are you sure this issue relates to the invokable rule and not how you're using `Rule::forEach`?

I've just been burned by the change in this [PR](https://github.com/laravel/framework/pull/43897) that breaks how you/I'm using `Rule::forEach`.

If you change your validation to the following in the latest Laravel version, does it work?:

```
'additional_users.*.email' => Rule::forEach(function ($value, $attribute) {
    return [
        'bail',
        'required',
        'email',
        new EnsureUserEmailDoesNotAlreadyExistInAdditionalUsersColumn($this->booking, $value),
    ];
}),
```

**Comment by abbluiz** [comment]
Well, I'm not sure. I'm

**Comment by abbluiz** [comment]
@aihowes Now I'm not sure, but here's how I'm using it.
```
            'access_roles.*.role_id' => [
                'bail',
                'present',
                'nullable',
                'integer',
                'exists:roles,id',
                'distinct',
                Rule::forEach(fn ($value, $attribute) => [
                    new RoleMustBeOfTheSameModule(
                        moduleIdArrayKey: Str::replace('role_id', 'module_id', $attribute)
                    ),
                ]),
            ],

**Comment by abbluiz** [comment]
Now I get it. We have to include everything inside the `Rule::forEach()` callback:

```php
public function rules(): array
{
    return [
        'access_roles.*.role_id' => [
            Rule::forEach(fn ($value, $attribute) => [
                'bail',
                'present',
                'nullable',
                'integer',
                'exists:roles,id',
                'distinct',
                new RoleMustBeOfTheSameModule(
                    moduleIdArrayKey: Str::replace('role_id', 'module_id', $attribute)
                ),
            ]),
        ],
    ];
}
```
Now it works, but it also breaks the way errors are returned in responses.

**Comment by aihowes** [comment]
Remove the array outside of the Rule::forEach:

```
public function rules(): array
{
    return [
        'access_roles.*.role_id' => Rule::forEach(fn ($value, $attribute) => [
            'bail',
            'present',
            'nullable',
            'integer',
            'exists:roles,id',
            'distinct',
            new RoleMustBeOfTheSameModule(
                moduleIdArrayKey: Str::replace('role_id', 'module_id', $attribute)
            ),
        ]),
    ];
}
```

**Comment by nearueng** [comment]
@aihowes thanks! Just came back to this and your method looks good!

**Comment by Tofandel** [comment]
I had the same issue, the error message is so obscure.. Maybe a note on the documentation of `Rule::forEach` is warranted or a runtime check?
