### ISSUE TITLE
Array to string conversion when formatting QueryException message

### ISSUE THREAD

**Issue by bastien-phi** [laravel/framework#44750]
- Laravel Version: 9.37.0
- PHP Version: 8.1.11
- Database Driver & Version: Postgresql 13 (reproduced on sqlite)

### Description:
Writing 
```php
Post::query()->insert([[
    'tags' => ['foo', 'bar'],
]]);
```
is incorrect because `Illuminate\Database\Eloquent\Builder::insert` is proxified to `Illuminate\Database\Query\Builder::insert` and it does not handle casts.

In this case, we would expect a `Illuminate\Database\QueryException` to be thrown.

Instead of this, we get an `ErrorException` with `Array to string conversion`.

Full stack trace
```
ErrorException: Array to string conversion

/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:259
/project/vendor/laravel/framework/src/Illuminate/Support/Str.php:832
/project/vendor/laravel/framework/src/Illuminate/Database/QueryException.php:57
/project/vendor/laravel/framework/src/Illuminate/Database/QueryException.php:40
/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php:761
/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php:720
/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php:546
/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php:498
/project/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3218
/project/tests/Feature/ExampleTest.php:16
```

I spent a lot of time figuring why my code wasn't working because of not having the error message... 
    
### Steps To Reproduce:

See https://github.com/bastien-phi/laravel-query-insert-bug-report

**Comment by morloderex** [comment]
When running the query builder directly you must make sure that the values you insert are serialized correctly.

In your case i would try to convert it to a string somehow. Sense the query builder can't know how your database table is created.

I get that you would be expecting a queryException to be thrown but i believe that the code works as expected.

**Comment by bastien-phi** [comment]
@morloderex I get your point but I think this is not that simple : 
- when writing `Post::query()->insert(...)` you have no idea that `insert` is not a method of Eloquent Builder (compare with `Post::query()->create(...)`)
- This code 
```php
Post::query()->insert([[
    'tags' => Collection::make(['foo', 'bar']),
]]);
``` 
actually works.

**Comment by morloderex** [comment]
> @morloderex I get your point but I think this is not that simple : 
> - when writing `Post::query()->insert(...)` you have no idea that `insert` is not a method of Eloquent Builder (compare with `Post::query()->create(...)`)
> - This code 
> ```php
> Post::query()->insert([[
>     'tags' => Collection::make(['foo', 'bar']),
> ]]);
> ``` 
> actually works.

That code snippet works because collection is serializable so that means it will be serialized automatically I believe.

**Comment by driesvints** [comment]
I'm sorry but to us it looks like you're simply misusing the query builder here. I'm not sure how we'd provide an error message since in some situations an array could be expected. You wouldn't know up front, only after a query exception.

If you have any ideas on how this can be done better we'd welcome PR's. Thanks

**Comment by bastien-phi** [comment]
@driesvints My point was exactly that. I was misusing the query builder but the error did not give me any clue on what was going on.

I was getting an ErrorException, located in the QueryException message parsing.

**Comment by bastien-phi** [comment]
The bug, in my opinion, is not having the QueryException because of the ErrorException hiding it.

**Comment by driesvints** [comment]
@bastien-phi we'd welcome PR's to improve this
