### ISSUE TITLE
Sometimes EncryptionServiceProvider not getting configs form .env "No application encryption key has been specified" error!

### ISSUE THREAD

**Issue by ss-koshala** [laravel/framework#44755]
- Laravel Version: 9.37.0
- PHP Version: 8.0.13
- Database Driver & Version: MySQL 5.7.36

### Description:
Sometimes EncryptionServiceProvider not getting configs form .env
$config = $app->make('config')->get('app');
here $config not getting from .env file. So key filed empty and getting "No application encryption key has been specified" error.

### Steps To Reproduce:
In laravel nova admin load "View" on a resource

nova-api/hotel-reservations?search=&filters=W10%3D&orderBy=&perPage=5&trashed=&page=1&viaResource=members&viaResourceId=1&viaRelationship=hotelReservations&relationshipType=hasMany

"nova-api/roles/actions?viaResource=users&viaResourceId=2&viaRelationship=roles&relationshipType=morphToMany&display=index"
like this.

I know it is nova related issue but issue with laravel. Hope some one can help this.

**Comment by brunoalod** [comment]
This is most likely a problem caused by running and accessing the app in the same root environment where you run other apps, as in domain.com/app1, domain.com/app2.

**Comment by driesvints** [comment]
Please contact Nova support about this, thanks.
