### ISSUE TITLE
Eloquent / query build should never burry a where clause

### ISSUE THREAD

**Issue by ActualFab** [laravel/framework#44760]
- Laravel Version: 6.x to 9.x
- PHP Version: 7.2 to 8.1
- Database Driver & Version: any

### Description:

When Eloquent/Query Builder are handling a where clause on a null column, the clause is just ignored as if none was added at all.
This is particularly problematic on updates as instead of preventing an obviously wrong query, it silently allow for a massive update one much more line than initially intended.

**Comment by driesvints** [comment]
Not sure I see a bug here. Seems you want a different behavior than the standard one. I doubt we'll modify this since it's present for so long.

**Comment by ActualFab** [comment]
I don't think that allowing potentially massive update when it is so obvious it should not append can ever be considered as _standard_.

DBMS now what to do in such case, by no mean an ORM should ever silently hide query error like that.
