### ISSUE TITLE
Eloquent / query builder should never burry a where clause

### ISSUE THREAD

**Issue by ActualFab** [laravel/framework#44762]
**Since [Eloquent / query builder should never burry a where clause](https://github.com/laravel/framework/issues/44760) was closed before I even got a chance to finish it, I repast it to at least leave an occasion to read the report before closing it again.**

- Laravel Version: 6.x to 9.x
- PHP Version: 7.2 to 8.1
- Database Driver & Version: any

### Description:

When Eloquent/Query Builder are handling a where clause on a null column with a null value, the clause is just ignored as if none was added at all.
This is particularly problematic on updates as instead of preventing an obviously wrong query, it silently allow for a massive update on much more line than initially intended. 

Imagine this case for example:
````php
User::where(null, '=', null)->update([...]);
````
This is obviously wrong, no need to argue on that, but laravel will just ignore the where clause and in fact do : 
````php
User::query()->update([...]);
````
That is update every single user.

This comes from the underlying call to `Arr::wrap($columns)` which will return `[]` when $column is null while in this particular case we would actually want `[null]` instead to let the dbms issue an exception as expected, or some more code for laravel itself to prevent mass update.

### Steps To Reproduce:

````php
User::where(null, '=', null)->update(['email' => 'email@example.com']);
````

Will update every single User emails to email@example.com

**Comment by ActualFab** [comment]
correction, the bug only triggers when both column and value are null ... I know this is a more than edgy case, but still a potentially nasty one

**Comment by ActualFab** [comment]
bottom line, it is arguable that this is a bug since the way it would work as it is would be to end up with a : 
````sql
null IS NULL
````

though it is still arguable because we used the `=` operator which would indeed translate to an impossible query should it be kept, and I can't find any legit usage of a `where(null, '=', null)` that would be actually intended as an `whereNull(null)`

For the story, this was triggered by a `setKeysForSaveQuery` on a model with composite keys which was thus entirely not handelable, both `getKeyName` and `getKeyForSaveQuery` returned null as expected and the call to `setKeysForSaveQuery` was thus totally wrong in its meaning.

**Comment by timacdonald** [comment]
I agree there is a bug, but seems to me like a bug in the consuming code. 

The `$column` only accepts `\Closure|string|array`, so passing `null` is not supported.

**Comment by driesvints** [comment]
See the answer above please

**Comment by ActualFab** [comment]
it is going through on php up to 8.0, but you are right, this is probably not an issue any more
