### ISSUE TITLE
Notifications table continues to throw duplicate entry for id column

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/framework#44765]
- Laravel Version: 9.37.0
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 5.7

### Description:

When sending notifications, the `notifications` table throws the following error:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '67f394ac-b1be-4300-8a7e-7f4daf6f65ee' for key 'PRIMARY' in /var/www/domain-monitor-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545

### Steps To Reproduce:

I have 85,000 notifications in my `notifications` table for reference.

I've come across [this](https://github.com/laravel/framework/issues/28271) discussion from 2019, except my `notifications` table's `id` column length is perfectly fine at 36 characters, what's more, my table migration for `notifications` for the `id` column also matches recommendations:

```php
Schema::create('notifications', function (Blueprint $table) {
    $table->uuid('id')->primary();
    $table->string('type');
    $table->morphs('notifiable');
    $table->text('data');
    $table->timestamp('read_at')->nullable();
    $table->timestamps();
});
```

I'm not sure why this keeps happening randomly, I'll attach a screenshot of my phpmyadmin table structure for `notifications` as I get this error randomly both locally and in production - I think others will be getting this error still 👍 
![notification_table_schema](https://user-images.githubusercontent.com/25177538/198388726-4917766e-2d20-4667-a51d-e4862ff3b48a.PNG)

**Comment by ankurk91** [comment]
What is the reason behind using uuid in notifications table?

**Comment by sts-ryan-holton** [comment]
@ankurk91 That's the default schema inherited from earlier versions of Laravel. When running the `php artisan notifications:table` command a `notifications` table is generated and the `uuid` is what Laravel generates.

**Comment by aanfarhan** [comment]
Just curious, @sts-ryan-holton did you run your notifications in queue?

**Comment by sts-ryan-holton** [comment]
@aanfarhan Yeah, they're running in a queue, using Supervisor, and I have about 28 workers running.

**Comment by driesvints** [comment]
Your "Steps To Reproduce:" don't provide any code that reproduces this. Except for the issue you linked to I don't think we've ever had this issue already. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
