### ISSUE TITLE
[9.x] php artisan serve issue printing arrays to console via print_r

### ISSUE THREAD

**Issue by samypr100** [laravel/framework#44781]
- Laravel Version: 9.36.4
- PHP Version: 8.1.12
- Database Driver & Version: N/A

### Description:

Previously in Laravel 8.x and below, the output buffer using `php artisan serve` didn't had a custom handler. This handler was introduced in this commit a52f623cf6e7ed9be7f6e87f5eb411a383ad42fc via `handleProcessOutput`. 

The issue is that the current `handleProcessOutput` doesn't seem to handle well when `error_log` or `Log::` is used to print complex objects (e.g. via `print_r`).

Previous to this commit in 9.x, printing an array on a server running under `php artisan serve` would look like this:

```php
[Some Date] Array
(
    [0] => Foo
    [1] => Bar
)
```

After the commit, printing an array on a server running under `php artisan serve` would look like this (verbatim):

```php
   WARN  Array.  

   WARN  (.  

   WARN  => Foo.  

   WARN  => Bar.  

   WARN  ).  
```

As you can see, the `handleProcessOutput` is mangling the desire output on this scenario, something that didn't used to happen before.

### Steps To Reproduce:

Use `php artisan serve` and on any desired controller route use `Log::info(print_r($complexArray, true));` or `error_log(print_r($complexArray, true));`

### Next Steps:

Currently I'm manually changing back `./vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php`

```diff
-$process->start($this->handleProcessOutput());
+$process->start(function ($type, $buffer) {
+    $this->output->write($buffer);
+});
```

An ideal solution would be to introduce maybe a new flag to allow the end-user to customize this, such as:

```php
if ($this->option('no-output-handling')) {
    $process->start(function ($type, $buffer) {
        $this->output->write($buffer);
    });
} else {
    $process->start($this->handleProcessOutput());
}
```

or in a smaller form-factor

```php
$outputHandler = $this->option('no-output-handling') ? fn($type, $buffer) => $this->output->write($buffer) : $this->handleProcessOutput();
$process->start($outputHandler);
```

```diff
    protected function getOptions()
    {
        return [
            ['host', null, InputOption::VALUE_OPTIONAL, 'The host address to serve the application on', Env::get('SERVER_HOST', '127.0.0.1')],
            ['port', null, InputOption::VALUE_OPTIONAL, 'The port to serve the application on', Env::get('SERVER_PORT')],
            ['tries', null, InputOption::VALUE_OPTIONAL, 'The max number of ports to attempt to serve from', 10],
            ['no-reload', null, InputOption::VALUE_NONE, 'Do not reload the development server on .env file changes'],
+           ['no-output-handling', null, InputOption::VALUE_NONE, 'Do not process server output buffer'],
        ];
    }
```

I'd be happy to open a PR if you think this is something that could be added and you'd think it's not more complicated than what I depicted above.

Very open to feedback if I missed something that might resolve this. I'm trying to avoid using the built-in php dev server as `php artisan serve` provides me with a lot of goodies. I could not find any other alternate way to make it print like it used to before without extensive pre-formatting of the output string on the application side.

Other ideas for flag names: `no-output-processing`

I opened this as an issue as I didn't think this would be a "new feature" given that it used to work in previous versions.

**Comment by driesvints** [comment]
Seems like this is something we don’t support anymore sorry
