### ISSUE TITLE
[9.33+, Octane] Controller Middleware is not working as expected

### ISSUE THREAD

**Issue by bcalik** [laravel/framework#44788]
- Laravel Version: 9.33.0+
- PHP Version: 8.1

### Description:

After upgrading Laravel Framework from 9.32 to 9.33, controller middleware has started to behave unexpected on Octane Swoole.

### Steps To Reproduce:

Lets we have controller like this.

```php
class FooController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->foo = "bar";
            return $next($request);
        });
    }

    public function index()
    {
        dd($this->foo);
    }
}
```

When you use Laravel Octane on Laravel Framework v9.32, you will get "bar" output as expected.

But after upgrading to v9.33+, you will get "bar" **only** on first run, then we will get _Undefined property $foo_ exceptions.

**Comment by nunomaduro** [comment]
Duplicated of https://github.com/laravel/octane/issues/594. We've sent in some fixes for this. These will be released on Tuesday.
