### ISSUE TITLE
[9.x] Broken layout with Blade @push directive when using CSS directives

### ISSUE THREAD

**Issue by yungfox** [laravel/framework#44785]
- Laravel Version: 9.19.0
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.25

### Description:
I had some CSS code containing ```@media``` and ```@keyframes``` directives inside a plain ```<style>``` tag in a Blade template, and decided to put it in a ```@push``` directive block to better organize CSS across components. When I did that, the layout on the component containing the code with CSS directives broke, as if there was a missing closing tag or the Blade compiler misintepreted the ```@media``` and ```@keyframes``` directives. No error message was displayed, just the broken layout. Is this a known issue?

### Steps To Reproduce:
Just try adding a ```@media``` query inside a ```@push``` block

**Comment by tontonsb** [comment]
Did you do double `@@` to escape?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
