### ISSUE TITLE
Problem when trying to cache views

### ISSUE THREAD

**Issue by Sebteams69** [laravel/framework#44794]
### Discussed in https://github.com/laravel/framework/discussions/44729

<div type='discussions-op-text'>

<sup>Originally posted by **Sebteams69** October 25, 2022</sup>
Hi everybody,
I deployed in production my backend which use laravel. After deploying I ran into an issue a I don't understand how to solve it.
The problem occurs when I run the command php artisan view:cache
An exception is raised in Illuminate\Foundation\Console\ViewCacheCommand::Illuminate\Foundation\Console\{closure}(Object(Symfony\Component\Finder\SplFileInfo), "vendor/laravel/framework/src/Illuminate/Notifications/resources/views/email.blade.php"

I have upgraded my composer to the latest laravel/framework version but still have the same issue.
Could anyone help me please?

Regards,
Sebastien</div>

**Comment by driesvints** [comment]
Please don't move discussions to issues, thanks.
