### ISSUE TITLE
`Storage::assertDirectoryEmpty` return green test even the folder not exists

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#44830]
- Laravel Version: 9.*
- PHP Version: 8.1

### Description:
The `Storage::assertDirectoryEmpty`  does not check whether the path exist, It should fail when a path is not exist.

### Steps To Reproduce:

```php
Storage::assertDirectoryEmpty('not-exists') // true
```

**Comment by driesvints** [comment]
This is the expected behavior.
