### ISSUE TITLE
Callback of `Model::handleMissingAttributeViolationUsing` called when using `isset` to check if attribute exists

### ISSUE THREAD

**Issue by gdebrauwer** [laravel/framework#44834]
- Laravel Version: 9.38.0
- PHP Version: 8.1.3

### Description:

When a custom callback is defined to handle missing attribute violations (introduced in https://github.com/laravel/framework/pull/44664), then that callback is also called when using the `isset` function to check if an attribute exists. That is not correct, because it is not a violation when using `isset`

### Steps To Reproduce:

```php
Model::shouldBeStrict(true);

Model::handleMissingAttributeViolationUsing(function ($model, $key) {
    dump('this should not be called!');
});

$user = User::factory()->create();

if (isset($user->fresh()->foobar)) {
  // ...
}
```

**Comment by driesvints** [comment]
We have no plans anymore to change this behavior, please see the convo at https://github.com/laravel/framework/pull/44717

**Comment by gdebrauwer** [comment]
The discussion in that PR seems to be around something else. This issue is caused by the fact that the offsetExists method tries to catch an exception that will never be thrown. The catch makes sense when no `missingAttributeViolationCallback` is defined, but when there is callback defined the catch does nothing.
https://github.com/laravel/framework/blob/0de8734170de48926e5a65c44e898b7078a0da0e/src/Illuminate/Database/Eloquent/Model.php#L2239-L2246
https://github.com/laravel/framework/blob/0de8734170de48926e5a65c44e898b7078a0da0e/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L465-L478

**Comment by sebastiaanluca** [comment]
Got bit by the same bug, see https://github.com/laravel/framework/pull/44642#issuecomment-1344964691. Was a really nice feature, but unusable unless you directly access the attribute.
