### ISSUE TITLE
Email validation allows spaces example : testemail @gmail.com

### ISSUE THREAD

**Issue by andrisunardi** [laravel/framework#44837]
- Laravel Version: 9.36.4
- PHP Version: 8.1.12
- Database Driver & Version: Mysql

### Description:
Requests Validation Email, not validate space after at, example testemail @gmail.com

### Steps To Reproduce:
Create LoginRequest
```
        $rules['email'] = [
            'required',
            'email',
            'min:6',
            'max:255',
        ];
```

Issue references : Email validation allows spaces #28233

**Comment by driesvints** [comment]
Hi, if you think this is an invalid email address you should open a ticket with https://github.com/egulias/EmailValidator which we use under the hood to validate these. Thanks

**Comment by kapersoft** [comment]
@andrisunardi See https://github.com/egulias/EmailValidator/issues/302#issuecomment-897970814
