### ISSUE TITLE
Storage functions don't work

### ISSUE THREAD

**Issue by AkramZerarka** [laravel/framework#44851]
- Laravel Version: 9.38
- PHP Version: 8.1.11

### Description:
Hello every one 
Well, I have a problem with storage functions when I call for example Storage::path()
I get `Call to undefined method League\Flysystem\Filesystem::path()`
Thank you

**Comment by barthelemy-ehui** [comment]
hi,

work fine for me under

- Laravel Version 9.38
- PHP 8.1.12

path() method is declared inside Illuminate\Filesystem\FilesystemAdapter which is an instance somewhere in

lluminate\Filesystem\FilesystemManager, the latter is used by FilesystemServiceProvider.

When the method you are calling is not available in FilesystemAdapter, the magic __call takes the lead and tries to ask  League\Flysystem\Filesystem...

Try dump(Storage::getFacadeRoot()); you will find out which instance it brings you up.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
