### ISSUE TITLE
queue:listen (with force flag) doesn't process jobs in maintenance mode 

### ISSUE THREAD

**Issue by JamesHemery** [laravel/framework#44861]
- Laravel Version: 9.38.0
- PHP Version: 8.1.0
- Database Driver & Version: Mysql 8.0

### Description:

When maintenance mode is enabled, the command `queue:listen --force` doesn't process jobs but `queue:work --force` works.

The flag `--force` is well documented for the `queue:listen` command.

### Steps To Reproduce:

1. Clone this repo: https://github.com/JamesHemery/laravel-queue-force-bug
2. Create and migrate database
3. Make sure that QUEUE_CONNECTION=database
4. Run `php artisan down`
5. Run `App\Jobs\TestJob::dispatch();` in tinker
6. Run `php artisan queue:listen --force` (don't work)
7. Run `php artisan queue:work --force` (work well)

**Comment by driesvints** [comment]
Seems like you sent in a PR to fix this so let's see how it goes. Thanks
