### ISSUE TITLE
Str::wrap() method does not take into account existing start and end of string

### ISSUE THREAD

**Issue by Allemweich** [laravel/framework#44886]
- Laravel Version: 9.39.0
- PHP Version: 8.1
- Database Driver & Version: irrelevant

### Description:
In https://github.com/laravel/framework/commit/8ea50bc1b7bab7507ca5b9d3761c45cee450b9f0 a new static method `Illuminate\Support\Str::wrap($str, $before, $after)` was added. This method does not take into account if $str already starts / ends with the given $before and $after sequences.

I mark this as a bug because I believe a number of people already had a Str::wrap() mixin in place that includes these checks and is in line with how the Arr::wrap() method works. The new Str::wrap() method takes precedence over the mixin and changes behavior in existing applications.

### Steps To Reproduce:
```php
$this->assertEquals('/some/string/', Str::wrap('some/string', '/')); // ok
$this->assertEquals('/some/string/', Str::wrap('/some/string/', '/')); // should succeed but fails
```

**Comment by driesvints** [comment]
We unfortunately cannot account for use cases where this method was already introduced.
