### ISSUE TITLE
Illuminate\Database\Eloquent\Relations\Pivot::updateOrCreate broken

### ISSUE THREAD

**Issue by Anticom** [laravel/framework#44882]
- Laravel Version: 9.39.0
- PHP Version: 8.1.12
- Database Driver & Version: MySQL, 8.0.31

### Description:
It appears that `Pivot::updateOrCreate` breaks whenever an actual update is necessary.

### Steps To Reproduce:

I've created an example Laravel app illustrating the issue. Please clone the repo and follow the instructions in the README:

https://github.com/Anticom/LaravelPivotUpdateOrCreate

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Anticom** [comment]
@driesvints  What do you mean by actually identifying it as a bug? I've went through the trouble of providing a concise and minimal example that clearly illustrates the bug (unless I'm using the framework incorrectly that is).

Running the commands stated in the README of my example yields

```
   DEPRECATED  str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 762.

   DEPRECATED  str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 762.

   DEPRECATED  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 62.

   DEPRECATED  str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 148.

   DEPRECATED  explode(): Passing null to parameter #2 ($string) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 73.

   DEPRECATED  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 62.

   DEPRECATED  str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 148.

   DEPRECATED  explode(): Passing null to parameter #2 ($string) of type string is deprecated in vendor/laravel/framework/src/Illuminate/Database/Grammar.php on line 73.

   Illuminate\Database\QueryException  SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: update `role_user` set `comment` = Something else, `role_user`.`updated_at` = 2022-11-09 07:51:36 where `` = 1 and `` = 1).
```

Taking the deprecation notices aside as you can see that the code clearly doesn't work as intended and due to the simple nature of my example I don't see where I could have messed up.

**Comment by Anticom** [comment]
Adding a superficial id column to the pivot table resolves the issue.

This sort of makes sense, however it doesn't align with with [the documentation](https://laravel.com/docs/9.x/eloquent-relationships#many-to-many-table-structure).

**Comment by driesvints** [comment]
Heya yeah, I'd just create an actual model here.
