### ISSUE TITLE
flash session data not working when redirect to intended()

### ISSUE THREAD

**Issue by aneesdev** [laravel/framework#44881]
I'm trying to redirect to the intended URL after login, and flash some session data together to show a popup modal only once.

If I do this, it works:

`return redirect(RouteServiceProvider::HOME)->with('showWelcome', true);`

I can retrieve the session in blade view as such:

```
@if (session('showWelcome'))
    // show modal..
@endif
```
However, if I use intended(), the session is no way to be found:

`return redirect()->intended(RouteServiceProvider::HOME)->with('showWelcome', true);`

I've also tried the following:

using the following instead of with():

`$request->session()->flash('showWelcome', true);`

using the \Session Class instead of the session() helper to retrieve the session data:

```
@if (\Session::has('showWelcome'))
    // show modal
@endif
```
Unfortunately, the problem persists where it only works when I'm not using intended().

I've searched high and low but couldn't exactly find any solution to this.

Am I doing something wrong or understanding how redirect works incorrectly?

Same problem when using Inertia.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
