### ISSUE TITLE
HTTP Client Middleware not working

### ISSUE THREAD

**Issue by 4nik3t** [laravel/framework#44897]
- Laravel Version: 9.39.0
- PHP Version: 8.0.24
- Database Driver & Version:8.0.31

### Description:
I am trying to execute the sample code provided here https://laravel.com/docs/9.x/http-client#guzzle-middleware

```php
$response = Http::withMiddleware(
        GuzzleHttp\Middleware::mapRequest(function (Psr\Http\Message\RequestInterface $request) {
            $request->withHeader('X-Example', 'Value');
            return $request;
        })
    )->get('https://example.com');
```

But when I check the request inside of laravel telescope it seems that the request is not getting modified using this middleware.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/48653948/201044849-57bd95a9-e29e-4bb9-b5ba-51fc29d90711.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/48653948/201044930-175a8548-6314-4117-881e-5fcdb2963f20.png">

I even tried changing the request method to post but that also did not seem to work

**Comment by driesvints** [comment]
Unfortunately, because of the way Guzzle works, it's not possible to gather headers set this way. They're populated after Laravel already instructed Guzzle to send the request and thus there's no way to gather them for Telescope. We'd appreciate a PR if someone ever figures out how to do this.

**Comment by 4nik3t** [comment]
@driesvints Does this means that the request is actually sent along with the headers and only not showing inside laravel telescope?

**Comment by driesvints** [comment]
Yes I think so.
