### ISSUE TITLE
Rule::when validation rule includes field in validated request even if no validations are ran against the field

### ISSUE THREAD

**Issue by krisi1998** [laravel/framework#44896]
- Laravel Version: 9.39.0
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:
Using just the Rule::when($condition, $rules) on a field, includes the field on $request->validated() even if $condition fails and $rules are not actually checked. I would not expect the field to be included in $request->validated() if $condition does not pass, and no other validation rules are checked on the field.

### Steps To Reproduce:
On a FormRequest:

``` php
public function rules(): array
    {
        return [
            'url_field' => [
                Rule::when(filter_var($this->url_field, FILTER_VALIDATE_URL), ['sometimes', 'required', 'url', 'bail'])
            ],
        ];
    }
```

-- Request passes validation (expected)
-- Field is present in validated attributes (not expected)
-- dd of $request->validated() on controller:
![image](https://user-images.githubusercontent.com/70098279/201040606-d1fd3f98-6130-4bb2-9371-2535aa9bfb73.png)

**Comment by krisi1998** [comment]
Current solution using array unpacking (requires PHP ^8.1):

``` php
public function rules(): array
    {
        return [
             ...(filter_var($this->url_field, FILTER_VALIDATE_URL)) ? [
                'url_field' => ['required', 'url', 'bail']
             ] : [],
        ];
    }
```

**Comment by driesvints** [comment]
Please provide an example I can run with a simple Validator::make call.

**Comment by krisi1998** [comment]
Sure, hope this helps. Let me know if something else is needed.

``` php
$cases = [
    'non_url_field' => 'no file provided!', // fails when condition
    'empty_field' => '',                    // fails when condition
    'correct_field' => 'https://www.example.de/63344d8899032.jpg' // passes
];

$validator = Validator::make(
    data: $cases,
    rules: [
        'non_url_field' => Rule::when(
            $cases['non_url_field'] !== 'no file provided!',
            ['required', 'url']
        ),
        'empty_field' => Rule::when(
            !empty($cases['empty_field']),
            ['required', 'url']
        ),
        'correct_field' => Rule::when(
            filter_var($cases['correct_field'], FILTER_VALIDATE_URL),
            ['required', 'url']
        ),
    ]
);

return response()->json([
    'validated' => $validator->validated(), // all three fields
    'failed' => $validator->failed()        // empty array
]);
```

Response:
``` json
{
    "validated": {
        "non_url_field": "no file provided!",
        "empty_field": "",
        "correct_field": "https://www.example.de/63344d889903232532.jpg"
    },
    "failed": []
}
```
'non_url_field' and 'empty_field' are present in validated even tho clearly no rules are ran against them, (not including 'when' itself).

**Comment by driesvints** [comment]
The `validated` method returns the fields that were validated, meaning all fields, not just the passing ones. Please see https://laravel.com/docs/9.x/validation#working-with-validated-input

The `Rule::when` adds rules based on if the boolean returns true. Since the first two return false, only the last defined rules are added.
