### ISSUE TITLE
PDO Statement execute() return value should be checked!

### ISSUE THREAD

**Issue by klodoma** [laravel/framework#44899]
- Laravel Version: 9.20.0
- PHP Version: 8.0
- Database Driver & Version: 

### Description:

Maybe this can be considered as an improvement request. 

I open this issue, as a side-effect of this bug:
https://jira.mariadb.org/browse/MDEV-27937

When certain queries are executed the `$statement->execute()` return false and `$statement->fetchAll()` returns `[]` and empty array. 
This lead to some very strange bugs in our application. 

There are cases when  `$statement->execute()` fails it returns `false` but no exception is being thrown as expected. I am unsure if this is a PHP PDO issue or not. 

As I see it in 
`https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Connection.php` implementation the 
`$statement->execute()`  should be checked to be `true` otherwise an exception should be thrown. 

### Steps To Reproduce:

If you execute the following against `mariadb:10.4.24` it will fail, `$res === false` 
If you provide a proper `$idList`, `$data` will be empty. 

```php
        $count = 9999;
        $idList = array_fill(0, $count, 'xxx');

        $params = implode(',', array_fill(0, $count, '?'));

        $query = "select * from `products` where `id` IN ($params)";

        $pdo = \DB::getPdo();
        $statement = $pdo->prepare($query);
        foreach ($idList as $key => $value) {
            $statement->bindValue($key + 1, $value);
        }
        $res = $statement->execute();

        $data = $statement->fetchAll();

        var_dump($pdo->errorInfo());
        var_dump($res);
        print_r($data);
```

**Comment by driesvints** [comment]
> Maybe this can be considered as an improvement request.

If you want to improve something, feel free to send in a PR 👍
