### ISSUE TITLE
Scoped and read-only filesystems don’t work out of the box

### ISSUE THREAD

**Issue by malinowskip** [laravel/framework#44935]
- Laravel Version: 9.39.0
- PHP Version: 8.1.12
- Database Driver & Version: *not applicable*

### Description:
The `prefix` and `read-only` filesystem options don’t work out of the box, because they require additional dependencies which are not included by Laravel by default. Those dependencies are `league/flysystem-path-prefixing` and `league/flysystem-read-only` and Laravel only requires them as dev dependencies.

As a result, in addition to the [steps outlined in the documentation](https://laravel.com/docs/9.x/filesystem#scoped-and-read-only-filesystems), it is necessary to install the two missing packages:
```
composer require league/flysystem-path-prefixing
composer require league/league/flysystem-read-only
```
Related issue: https://github.com/laravel/framework/issues/44327

### Steps To Reproduce:
Set up a disk with `prefix` and/or `read-only` options as [outlined in the documentation](https://laravel.com/docs/9.x/filesystem#scoped-and-read-only-filesystems).

**Comment by driesvints** [comment]
Feel free to send in a PR to the docs 👍
