### ISSUE TITLE
编写全局作用域后，使用英文模糊查询，令牌会失效，退出登录

### ISSUE THREAD

**Issue by erxiaosoul** [laravel/framework#44952]
- Laravel Version: 9.3.10
- PHP Version: 8.1.12
- Database Driver & Version: mysql 8.0

### Description:
编写全局作用域后，使用英文模糊查询后，令牌会失效，退出登录。

### Steps To Reproduce:
1.[新建 文件](php artisan make:scope SearchScope)
再文件apply方法中添加如下代码
$builder->when(request('search'), function ($query) {
    $query->where('name', 'like', '%' . request('search') . '%');
});
2.UserController.php控制器文件添加如下代码:
public function __construct()
{
    $this->middleware(['auth:sanctum']);
}
public function index()
{
    return UserResource::collection(User::latest()->paginate(request('per_page', 15)));
}
3.添加路由：
Route::apiResource('user', UserController::class);
4.先登录之后，再GET请求  /api/user?search=abc

此时就会退出登录 {"message":"Unauthenticated."}

**Comment by driesvints** [comment]
Please repost this in English
