### ISSUE TITLE
Impossible to disable encryption for Mail from .env

### ISSUE THREAD

**Issue by Synchro** [laravel/framework#44953]
- Laravel Version: 9.39
- PHP Version: 8.1.12
- Database Driver & Version: n/a

### Description:

I'm relaying mail through a local mail server without auth or encryption, so my `.env` contains this:

```ini
MAIL_MAILER=smtp
MAIL_HOST=localhost
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

My `config/mail.php` contains the default:

    'encryption' => env('MAIL_ENCRYPTION', 'tls'),

Ultimately, this value is [passed to Symfony Mail](https://github.com/symfony/mailer/blob/6.1/Transport/Smtp/EsmtpTransport.php#L50), where encryption is not used if the `$tls` parameter is `null`.

The upshot of this arrangement is that it's not possible to disable encryption from the `.env` file. If you set it to null in `.env`, config will end up with the default `tls` value, so you have to edit the config file, which has knock-on consequences when it comes to future framework upgrades.

Symfony actually tries to solve this by disabling TLS if the hostname is `localhost`, however, Laravel's behaviour means it will never match that condition.

So my request here is to introduce a non-null value that results in `null` being passed to the `$tls` parameter of Symfony mail, perhaps `none`. We effectively already have some "magic" values for controlling this parameter (inherited from Symfony), so it's not a great departure, and strikes me as exactly the kind of thing that a facade wrapper should handle. I know this is a small thing, but it also enables the simplest possible SMTP config for Laravel. From my experience with PHPMailer, I know that SMTP to localhost is both faster and safer than using PHP's `mail()` function or calling a sendmail binary via a shell.

**Comment by bbashy** [comment]
What about this?
```
MAIL_ENCRYPTION=false
```

**Comment by bbashy** [comment]
```
> null === false
= false
```

It should then hit https://github.com/symfony/mailer/blob/6.1/Transport/Smtp/EsmtpTransport.php#L57-L59 no?

**Comment by Synchro** [comment]
That's a good point – the second test is `if (!$tls) {`, which is less picky. I'd also not noticed that the `$tls` param is defined as `bool $tls = null`, so it doesn't actually let you specify the type of TLS connection, only turn it on or off. But I think that will do, thanks for the bandwidth!

**Comment by bbashy** [comment]
Yep, and env allows `false` as the value
```
> env('MAIL_ENCRYPTION', 'tls')
= false
```

Enjoy!

**Comment by danatemple** [comment]
For anyone having this problem and arriving here, on Laravel 10.42 with Symfony/Mailer 6.4.2 I found that MAIL_ENCRYPTION=false did not have any effect. I found in the CHANGELOG under Symfony 4.4 this:

 * add DSN parameter `verify_peer` to disable TLS peer verification for SMTP transport

Sure enough, this is what is used in `vendor/symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php` 

        if ('' !== $dsn->getOption('verify_peer') && !filter_var($dsn->getOption('verify_peer', true), \FILTER_VALIDATE_BOOL)) {
            $streamOptions['ssl']['verify_peer'] = false;
            $streamOptions['ssl']['verify_peer_name'] = false;
        }

So the solution in my config/mail.php is now, the following, which works for MAIL_ENCRYPTION=false:

        'smtp' => [
            'transport' => 'smtp',
            'url' => env('MAIL_URL'),
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'verify_peer' => !!env('MAIL_ENCRYPTION'),
         ],

(I can find no hint of any use of MAIL_ENCRYPTION anywhere. )
