### ISSUE TITLE
Should "retry" be ignored when sending async/pool requests.

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/framework#44955]
Hi,

I'm currently using the Laravel Http Client extensively, and in particular async requests. One item I seem to be noticing is that when my code uses async requests, it seems to ignore the retry option.

So
```php
Http::retry(3)->get('https://httpbin.org/headers');
```
Will retry correctly if there's an issue but:

```php
Http::pool(fn (Pool $pool) => [
    $pool->retry(3)->get('https://httpbin.org/headers'),
    $pool->retry(3)->get('https://httpbin.org/headers'),
);
```

Does not.

Looking into the `PendingRequest` class I can see where I think the problem begins. Around line 778 in the `send` function, we return early with a promise if the request is to be `async` just before the retry code is applied to the non-async request.

https://github.com/laravel/framework/blob/213e07ef363bb6f2355254a5a9a0da33dcd692ad/src/Illuminate/Http/Client/PendingRequest.php#L758-L785

Is this intentional? Is there a reason why we can't apply the retry options to an async request. Would that force the promise to need to be resolved first before it could check and therefore negate any benefit of using an async request in the first place?

I see this also mentioned here: https://github.com/laravel/framework/issues/41790#issuecomment-1143319214 but the issue was closed with no comment about it.

Just want to check before I go down a large rabbit hole trying to make this work, if the maintainers already had a solid reason for the current design and it's not possible!

Thank you.

**Comment by jonnywilliamson** [comment]
I've no issue asking on support channels (https://laracasts.com/discuss/channels/laravel/should-retry-be-ignored-when-sending-asyncpool-requests).

But it appears unclear if this is **intended design** or a bug, hence the issue. Just wanted to know your thoughts.

Thank you.

**Comment by phuclh** [comment]
@jonnywilliamson Did you figure it out?

**Comment by shdehnavi** [comment]
Still the same issue

**Comment by diegocam** [comment]
This is still a problem.

**Comment by haipham** [comment]
The same.
