### ISSUE TITLE
After the global scope is written, the token will be invalidated and the login will be logged out using the English fuzzy query 

### ISSUE THREAD

**Issue by erxiaosoul** [laravel/framework#44956]
- Laravel Version: 9.3.10
- PHP Version: 8.1.12
- Database Driver & Version: mysql 8.0

### Description:
After the global scope is written, the token will be invalidated and the login will be logged out using the English fuzzy query。

### Steps To Reproduce:
1.execute `php artisan make:scope SearchScope` Create a file.
Add the following code to the file add method.
```
$builder->when(request('search'), function ($query) {
    $query->where('name', 'like', '%' . request('search') . '%');
});
```
2.UserController.phpAdd the following code to the controller file:
```
public function __construct()
{
    $this->middleware(['auth:sanctum']);
}
public function index()
{
    return UserResource::collection(User::latest()->paginate(request('per_page', 15)));
}
```
3.Adding a route:
Route::apiResource('user', UserController::class);
4.After you log in, GET the request  /api/user?search=abc
The following information is displayed：
` {"message":"Unauthenticated."}`

This is an example that I just added:
https://github.com/erxiaosoul/laravel-scope

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
