### ISSUE TITLE
Result of toArray depends on the order of attribute assignment

### ISSUE THREAD

**Issue by timohund** [laravel/framework#44969]
- Laravel Version: 9.17.0
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 5.7

### Description:
Order of items in toArray depends on the order of assignment.

The order of the attributes in the toArray result depends on the order of the assignment.
I would expect, that the order is same, independent from the order of the calls.

### Steps To Reproduce:

```
        $foo = new Foo();
        $foo->name = 'bla';
        $foo->folder = 1;
        var_dump($foo->toArray());
        $foo2 = new Foo();
        $foo2->folder = 1;
        $foo2->name = 'bla';
        var_dump($foo->toArray());
```

**Comment by araeuchle** [comment]
Can confirm it, i would expect the same as @timohund said.

**Comment by driesvints** [comment]
I get the same order.

<img width="1670" alt="Screenshot 2022-11-17 at 10 11 23" src="https://user-images.githubusercontent.com/594614/202404445-0082d997-c957-41fd-83a6-d9926301d017.png">

**Comment by araeuchle** [comment]
@driesvints Thank you for your fast response. With what Laravel Version did you tested this? As timohund and i have the same version and it is not working with that.

**Comment by driesvints** [comment]
Latest one.

**Comment by araeuchle** [comment]
Ah ok, than it might be an issue only in the 9.17 version of Laravel

**Comment by araeuchle** [comment]
@driesvints  i would like to reopen the issue as i recognized, that you called $foo twice rather than $foo and $foo2. That is why the results are the same! 
i tried it with laravel 9.38 and still got this output

**Comment by araeuchle** [comment]
Hey @driesvints as mentioned before we would like to reopen this issue as the error still exists. Please reopen it!

**Comment by driesvints** [comment]
Hi there. I just copy pasted the example the OP gave which is why I didn't see. However, I don't think there's a real issue here. I believe this is the expected behavior.
