### ISSUE TITLE
Seeder output could be better

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#44978]
- Laravel Version: 9.40.1
- PHP Version: 8.1.12

### Description:

I have such a seeder:
```
class DatabaseSeeder extends Seeder
{
    public function run()
    {
        $this->call([
            Seeds\IP4NetSeeder::class,
            Seeds\TenantSeeder::class,
            Seeds\DiscountSeeder::class,
            Seeds\DomainSeeder::class,
            Seeds\SkuSeeder::class,
            Seeds\PackageSeeder::class
        ]);
    }
}
```
And here's the output of `artisan migrate:refresh --seed`

![seeders-output](https://user-images.githubusercontent.com/546788/202409369-4a41e526-930c-43b3-8dac-34bbdc49e846.png)

As you see there are two problems:
1. Duplicate line for RUNNING and DONE. Could the first one be replaced with DONE-line when done?
2. Redundant empty line between sub-seeders.

**Comment by driesvints** [comment]
Sorry but we have no plans to change this.
