### ISSUE TITLE
Error with new aws/aws-sdk-php

### ISSUE THREAD

**Issue by labomatik** [laravel/framework#44977]
- Laravel Version: 9.40.1
- PHP Version: 8.1.5
- Database Driver & Version: Mysql 8.0.28

### Description:
We are currently using a filesystem that is hosted at DigitalOcean (space), we are using the AWS adapter requiring a few packages, one of the packages: aws/aws-sdk-php

By upgrading from 3.242.1 to 3.243.0 we suddenly got issues in our system (a nasty Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames)
![image](https://user-images.githubusercontent.com/179987/202395901-25a8ba8a-4d80-478c-aada-ac7f1b79dc06.png)

We tested by pinning in our composer.json
"aws/aws-sdk-php": "3.242.1", -> OK
"aws/aws-sdk-php": "3.243.0", -> NOT OK

After investigation, we identified this bug reported on that repo:
https://github.com/aws/aws-sdk-php/issues/2563

We tried to apply the patch proposed on src/Illuminate/Filesystem/FilesystemManager.php (before $client = new S3Client($s3Config)):
`$s3Config['endpoint_provider'] = PartitionEndpointProvider::defaultProvider(); `
and that fixes the issue...

Seems like it's linked to a file  that starts with / (example : /private/image.gif )

**Comment by driesvints** [comment]
Seems like they fixed it in `3.244.1` so please upgrade to that version.

**Comment by labomatik** [comment]
We updated to 3.245.0 but the issue was still present.

**Comment by driesvints** [comment]
Please open an issue with the AWS PHP SDK as this is a breaking change with them.

**Comment by georgeboot** [comment]
Possibly related to https://github.com/aws/aws-sdk-php/issues/2567

**Comment by georgeboot** [comment]
Seems like Laravel injects `token` option to some sdk clients as a root option, instead of it being inside the `credentials` key.

**Comment by labomatik** [comment]
I'm not sure it's related because by patching src/Illuminate/Filesystem/FilesystemManager.php and adding 
`$s3Config['endpoint_provider'] = PartitionEndpointProvider::defaultProvider();` it's solving the issue. But there is something wrong with the combination laravel and aws-sdk-php 3.245.0 (after 3.242.1 at least)

**Comment by driesvints** [comment]
@labomatik can you try the PR by @georgeboot to see if that resolves your issue? https://github.com/laravel/framework/pull/44979

**Comment by labomatik** [comment]
That's not working with that PR

**Comment by driesvints** [comment]
Please open an issue on the AWS PHP SDK then as this does not seem like a bug within Laravel.

**Comment by labomatik** [comment]
Yes i'll do ;-)

**Comment by stobrien89** [comment]
Hi @driesvints, @georgeboot,  @labomatik,

Apologies for all of the issues. 

@labomatik,

Glad you were able to patch this for now, but I'd like to get this addressed if this is an issue with our implementation. Could you open an issue against our repository with more information about the operations/config you're using for this library?

Thanks!
