### ISSUE TITLE
Route name view not found

### ISSUE THREAD

**Issue by mariosvasiliou** [laravel/framework#44981]
- Laravel Version: 8.83.26
- PHP Version: 8.0.14
- Database Driver & Version: 8.0.31

### Description:
When adding routes with controller and name view it throws an exception that view is not found. More specific 

>  UnexpectedValueException
>   Invalid route action: [view].

### Steps To Reproduce:

Create a controller with a public method view.
Go to the route file and add something like 

```
  Route::prefix('reports')
         ->controller(ReportController::class)
         ->name('reports.tasks.')
         ->group(function () {
             Route::get('view', 'view')->name('view');
         });
```

Run any command like PHP **artisan route:clear**

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
