### ISSUE TITLE
withAggregate and polymorphic relationships

### ISSUE THREAD

**Issue by JerryBels** [laravel/framework#44996]
- Laravel Version: 9.40.1
- PHP Version: 8.1.3
- Database Driver & Version: mysql 

### Description:

Using a polymorphic relationship with `withAggregate`, Laravel tries to find the column in the current table. For example, as per the [docs](https://laravel.com/docs/9.x/eloquent-relationships#one-to-many-polymorphic-table-structure) with `Comment::withAggregate('commentable', 'name')->get()`, I would expect to get a `post_name` or a `video_name` column. Rather, this error shows up : `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'`

![image](https://user-images.githubusercontent.com/4408419/202504465-0caf7637-5de5-4dd3-b3dc-bc2c89777a99.png)

### Steps To Reproduce:

https://github.com/JerryBels/with-aggregate-morph-bug

Migrate and seed, then access homepage.

**Comment by teikun-86** [comment]
Correct me if I wrong,
From my understanding, the `withAggregate` method is called when the relationship is `one-to-many` such as `Post` model.
For example:
```php
Post::withAggregate('comments', 'id')->get();
```
will result:
```
[
    "id" => 1
    "name" => "a post"
    "created_at" => "2022-11-19T05:53:53.000000Z"
    "updated_at" => "2022-11-19T05:53:53.000000Z"
    "comments_id" => 1
]
```
and
```php
Post::withCount('comments')->get();
```
will result:
```
[
    "id" => 1
    "name" => "a post"
    "created_at" => "2022-11-19T05:53:53.000000Z"
    "updated_at" => "2022-11-19T05:53:53.000000Z"
    "comments_count" => 1
]
```

So when you call it from the `Comment` model, it will result an error even on a `withCount` method.
![image](https://user-images.githubusercontent.com/60819208/202838179-a9f2bc6b-e7f2-4f37-8988-b0a886c5e2b9.png)

If you want to get the commentable's name, just simply use `Comment::with('commentable')` to retrieve the commentable model, it will result:
```
[
    "id" => 1
    "commentable_id" => 1
    "commentable_type" => "App\Models\Post"
    "created_at" => "2022-11-19T05:53:53.000000Z"
    "updated_at" => "2022-11-19T05:53:53.000000Z"
    "commentable" => [
      "id" => 1
      "name" => "a post"
      "created_at" => "2022-11-19T05:53:53.000000Z"
      "updated_at" => "2022-11-19T05:53:53.000000Z"
    ]
]
```

**Comment by JerryBels** [comment]
Well, `withAggregate` do work when used on a `belongsTo` but not polymorphic relationship. For example, if I have a role_id in my users table so User belongs to Role, I can do `User::withAggregate('role', 'name') and get the `role_name` in the query.

In the example with `Comment` and `Post`, the Comment morphs to Post or Video (basically a polymorphic belongsto), so I would expect it to behave the same way and be able to get the name of the corresponding table, under a common alias like `commentable_name`.

This is useful to be able to `orderBy` the query by `commentable_name` when in a `pagination` setup. If using `with`, we can't order the query.

**Comment by driesvints** [comment]
I don't think it's meant that `withAggregate` is publicly used as we don't document it anywhere.
