### ISSUE TITLE
Vite.php is not using custom manifest file generated by laravel-vite-plugin

### ISSUE THREAD

**Issue by ngstwr** [laravel/framework#45002]
- Laravel Version: 9.32
- PHP Version: 8.1

### Description:
Vite.php has 'manifest.json' hardcoded in manifestPath method!

protected function manifestPath($buildDirectory)
{
    return public_path($buildDirectory.'/manifest.json');
}

### Steps To Reproduce:
1. Install laravel-vite-plugin
yarn add laravel-vite-plugin -D

2. Change manifest file name to 'custom-manifest.json' in vite.config.js
build: {
    manifest: 'custom-manifest.json',
}

3. Build the application
yarn prod

**Comment by driesvints** [comment]
Seems like this is a feature request. Feel free to send in a PR 👍

**Comment by ngstwr** [comment]
I don't understand how is this a feature request! 

An official plugin 'laravel-vite-plugin', is generating the manifest file and Vite.php facade is using the same manifest file to map and provide resources. 

Now, laravel-vite-plugin provides an option to generate manifest, named as per user provided configuration. However Vite.php hasn't been updated to allow this.

Anyway, I don't have a problem sending in a PR, but I am new to Laravel and have no idea on how to write tests!
