### ISSUE TITLE
Undefined method 'isProduction'

### ISSUE THREAD

**Issue by LeeConnelly12** [laravel/framework#45018]
- Laravel Version: 9.19
- PHP Version: 8.0.2
- Database Driver & Version: mysql-server:8.0
- Editor: Visual Studio Code

### Description:
Followed the docs to enable strict mode in the AppServiceProvider's boot method
```
Model::shouldBeStrict(!$this->app->isProduction());
```
But the PHP Intelephense extension complains about isProduction being an undefined method

![image](https://user-images.githubusercontent.com/25698647/202804926-49db0196-e131-4b2e-803e-b6423ede30d4.png)

isDownForMaintenance works and is picked up and autocompleted with no error.
```
Model::shouldBeStrict(!$this->app->isDownForMaintenance());
```

Autocompletion works if I add an isProduction method to the `/Illuminate/Contracts/Foundation/Application` file
```
/**
 * Determine if the application is in the production environment.
 *
 * @return bool
*/
public function isProduction();
```

### Steps To Reproduce:

- Use Visual Studio Code with the PHP Intelephense extension
- Add the following code to your AppServiceProvider's boot method
```
Model::shouldBeStrict(!$this->app->isProduction());
```

Issue happens on this new Laravel repo I made
https://github.com/LeeConnelly12/invoice-app

**Comment by driesvints** [comment]
There does not seem to be a bug here, just an intelephense warning.
