### ISSUE TITLE
\Illuminate\Database\Eloquent\Casts\AsArrayObject json cannot set options

### ISSUE THREAD

**Issue by shuqingzai** [laravel/framework#45022]
- Laravel Version: 8.54.#
```shell
-> % php artisan --version
Laravel Framework 8.54.0
```
- Database Driver & Version:
mysql8.0.18
### Description:
When the Eloquent model uses \Illuminate\Database\Eloquent\Casts\AsArrayObject to convert the json type, the json option cannot be set, which will cause UNICODE to fail to be converted into entity words, such as Chinese will be lost

![image](https://user-images.githubusercontent.com/44406033/202830424-853fd691-2b10-42dc-83e2-2181a2171868.png)

![image](https://user-images.githubusercontent.com/44406033/202830453-50b29c9b-69dc-4d8b-88d8-60965a937976.png)

It should actually be "加购-4"

### Steps To Reproduce:
Set the content of the json field to "加购-4", serialization and saving will become UNICODE garbled characters

**Comment by shuqingzai** [comment]
It seems that many classes do not support setting json options like: \Illuminate\Http\Client\Response or \Illuminate\Database\Eloquent\Casts\AsCollection

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
