### ISSUE TITLE
Is anybody aware of this old problem with cache-ing using tags in Redis?

### ISSUE THREAD

**Issue by maxi032** [laravel/framework#45035]
- Laravel Version: 8.83.23
- PHP Version: 7.4.32
- Database Driver & Version:
mysql 7.4
phpinfo shows:

Redis Version | 5.3.7
Redis Sentinel Version | 0.1
Available serializers | php, json

Redis Desktop Manager shows redis_version 7.0.2

### Description:
References to deleted tags still maintained after keys expired.
This was first mentioned 5 years ago here: https://laracasts.com/discuss/channels/laravel/tagged-cache-items-with-ttl-mess-up-redis-cache-in-laravel
Then 3 years ago, 2 years ago and 10 month ago. I also have it so I thought it is a good idea to point it out here  

### Steps To Reproduce:
Change your cache driver to redis 
Install predis/predis": "^2.0 with composer  and cache some keys using tags.
Monitor the state of the cache with "Another Redis Desktop Manager"

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
