### ISSUE TITLE
Request::merge() replaces, not merges

### ISSUE THREAD

**Issue by phh** [laravel/framework#45038]
- Laravel Version: 9.38.0
- PHP Version: 8.1.2
- Database Driver & Version: Mysql 5.7.40

### Description:

When using the `Request::merge()` method, the docs state (and I would assume) that the parameters get merged, not replaced.

This is fine when you do `$request->merge(['votes' => 0])`, however, when you add another level to the array, it replaces the full url.

### Steps To Reproduce:

```php
Route::get('merge', function (Request $request) {
    $request->merge([
        'type' => [
            'foo' => 'bar',
        ],
    ]);

    dump($request->all());
    // ['type' => ['bar' => 'foo']]

    $request->merge([
        'type' => [
            'bar' => 'foo',
        ],
    ]);

    dump($request->all());
    // ['type' => ['foo' => 'bar']]
});
```

Expected:
```php
[
    'type' => [
        'foo' => 'bar',
        'bar' => 'foo',
    ],
]
```

Actual:
```php
[
    'type' => [
        'bar' => 'foo',
    ],
]
```

Happy to PR and add the tests but would like to know if this is the wanted/expected behavior.

**Comment by driesvints** [comment]
Think you misunderstood how this works. It'll merge additional input, meaning that if the key exists, it'll overwrite it. I'll PR to the docs for a better explanation.

**Comment by phh** [comment]
Nvm that's replacing all of them.
