### ISSUE TITLE
Pre-rendered Maintenance Mode is not rendered as if it was in Maintenance Mode

### ISSUE THREAD

**Issue by Cbrad24** [laravel/framework#45033]
- Laravel Version: v9.38.0
- PHP Version: v8.1.12
- Database Driver & Version: Postgres

### Description:
The pre-rendered maintenance mode using the `php artisan down --render="errors::503"` command does not show up as if it was actually in maintenance mode.

### Steps To Reproduce:
1. Create a `resources/views/errors/503.blade.php` with the following contents:
```blade
@extends('errors::minimal')

@if(App::isDownForMaintenance())
    @section('title', __('Down for Maintenance'))
    @section('code', '503')
    @section('message', __('Down for Maintenance'))
@else
    @section('title', __('Service Unavailable'))
    @section('code', '503')
    @section('message', __('Service Unavailable'))
@endif
```
2. Run the command `php artisan down --render="errors::503"`.
3. View the application in a browser.
4. You will see 'Service Unavailable' instead of desired output 'Down for Maintenance'. This only happens with the pre '--render' flag.

It would be nice to be able to differentiate between maintenance mode and otherwise to display a more detailed reason for a 503 error to the user without having to boot the entire framework.

**Comment by lk77** [comment]
When the view is rendered, the framework is not yet in maintenance mode

**Comment by driesvints** [comment]
As said on https://github.com/laravel/framework/pull/45131 this is a bit of an edge case and thus we're not going to take any action here, sorry.
