### ISSUE TITLE
$model->count() != 1

### ISSUE THREAD

**Issue by interludic** [laravel/framework#45048]
- Laravel Version: 8.40
- PHP Version: 8.1.9
- Database Driver & Version: Mysql/Mariadb

### Description:
"when $model is a collection returned from the database however there is only 1"
$model->count() returns the total number of $models within the table rather than just 1 when counting on.

eg: $users->count() = 3000+

### Steps To Reproduce:

My workaround...
            $count = 1;
            if (!empty($users->count()) && (get_class($users) != 'App\Models\User')) {
                $count = $users->count();
            }

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by s-patompong** [comment]
@interludic what you say shouldn't be possible. I have a project with Laravel 8 and it's running fine. Maybe something is wrong with the current code in your project?

For `Collection::count()`, it will always return 1 if there is only one element in the collection.
For `Builder::count()`, it will always count the records in the table.
