### ISSUE TITLE
Model `increment()`/`decrement()` is unstable and may update everything

### ISSUE THREAD

**Issue by bert-w** [laravel/framework#45043]
- Laravel Version: 9.x
- PHP Version: 8.x
- Database Driver & Version: MySQL/MariaDB

### Description:
I ran into yet another issue with the current increment/decrement functions on an Eloquent model. The issue with Eloquent's increment/decrement is that it seems to follow a completely different route than an update-statement would, resulting in weird behaviour like the following:

```php
// Assume a random $user (id:1) with a hasMany relation named `userConfig()`,
// which simply allows you to save custom properties attached to a user:
$cfg = $user->userConfig()->firstOrNew([
    // 'user_id' => 1, // (we don't need to set this explicitly because of the relation, which is correct)
    'name' => 'some_custom_property',
    'value' => 100,
]);

// Lets increment the value of this property with 200 (atomic query):
$cfg->increment('value', 200);
```

Expected outcome:
- Updated `value=300` for user_config `name=some_custom_property` for `user_id=1`

Actual outcome:
- If the userConfig record already exists -> expected outcome (correct behaviour)
- If the userConfig record does not exist (thus `$cfg` is a new userConfig object in the example above) -> ALL values in the user_config table are updated, not just for `user_id=1` and not just for `name=some_custom_property`. This is obviously not correct.

# Test case branch
https://github.com/bert-w/framework/tree/bug-increments-everything has both scenarios quickly hacked into a unit test. 

# Solution
See my previous PR: https://github.com/laravel/framework/pull/43646. This PR streamlines the `increment()` function to use the existing `update()` logic. This PR has some other nice possibilities as well like the ability to do:
```php
$model->update([
    'internet_points' => $model::expectable('+', 10),
    'coins' => $model::expectable('-', 5),
]);
```
This `expectable` is a wrapper class to help with determining the outcome of a query, based on the value the Eloquent model currently knows about a column (e.g. `internet_points + 10` would result in `15` if the `internet_points` in memory is equal to `5`). A hack for this is already used in Laravel at the moment where the new value is guesstimated in the model's `updated` event.

# Related
#43113, #32567

EDIT: changed the actual outcome description since the query is actually worse than I described: it updates the complete table with no where-statements whatsoever.

**Comment by bert-w** [comment]
https://github.com/laravel/framework/blob/daf094441404d0c51084abb6c03a64da1391a798/src/Illuminate/Database/Eloquent/Model.php#L951-L957

Maybe this if-statement should just `return false`, similar to how `update()` does it. All database tests still seem to pass. But thats kinda the reason to refactor this code: the `increment()` and `update()` functions basically do the same thing.

However, in order to not make 2 queries (1 for creating the unexisting model and 1 for incrementing it) while still making use of the atomic `value = value + 10` syntax, it would still be great to use something like:
```php
$existingOrUnexistingModel->fill(['likes' => $model::expectable('+', 10)])->save();
```

**Comment by driesvints** [comment]
`increment`/`decrement` can only be used with existing models. We'd appreciate a PR to the docs to clarify this further.

**Comment by driesvints** [comment]
You can always try it
