### ISSUE TITLE
Laravel Migration Silently Fails with SQLite when Dropping and Adding a Column in the Same Modification

### ISSUE THREAD

**Issue by Sunhat** [laravel/framework#45056]
https://github.com/laravel/framework/issues/39442

- Laravel Version: 8 Latest
- PHP Version: 8.1
- Database Driver & Version: SQLite 3
- OS: MacOS and Docker ubuntu latest

### Description:
This is an easily re-producible bug that is consistent across new and old installations of Laravel 8. It was already reported, and has been a bug in Laravel for over a year. @driesvints couldn't be bothered to investigate, so closed the issue.

https://github.com/laravel/framework/issues/39442

- Create migration with drop col and new columns
- Write a test that reads or writes this field
- Watch it not exist

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
