### ISSUE TITLE
Laravel Migration Silently Fails with SQLite when Dropping and Adding a Column in the Same Modification

### ISSUE THREAD

**Issue by Sunhat** [laravel/framework#45057]
https://github.com/laravel/framework/issues/39442

Laravel Version: 9.38.0
PHP Version: 8.1
Database Driver & Version: SQLite 3
OS: MacOS and Docker ubuntu latest
Description:
This is an easily re-producible bug that is consistent across new and old installations of Laravel 8 & 9. It was already reported, and has been a bug in Laravel for over a year. @driesvints couldn't be bothered to investigate, so closed the issue.

https://github.com/laravel/framework/issues/39442

Create migration with drop col and new columns
Write a test that reads or writes this field
Watch it not exist

@driesvints In my previous ticket, I reported this as Laravel 8 forgetting Laravel 9 exists. I'm using Laravel 9. The same bug exists. If you waste more of my time, I'll bill you.

**Comment by driesvints** [comment]
> If you waste more of my time, I'll bill you.

This is open source. I suggest you find another framework to work with 👋
