### ISSUE TITLE
public proparty is nont accessable from class of the class based component tocomponnet view

### ISSUE THREAD

**Issue by mina20088** [laravel/framework#45063]
- Laravel Version: 9.41.0
- PHP Version: php artisan --version
- Database Driver & Version: 
-Description:
  there is an issue in laravel component issue which i noticed that spicially in class based component when i add data to the 
  constracor according to the documnetation it sppose to be availibel to the component view if it is public but that is no happening and 
  included the code that i did 
 1- componet class code :
```
<?php

namespace App\View\Components\users;

use Illuminate\View\Component;

use function PHPSTORM_META\type;

class UsersList extends Component
{
    // public $type;
    public string $message;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->type = $type;
        $this->message = "mina";
    }

    /**
     * Get the view / contents that represent the component.    
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.users.userslist');
    }
}
```
2- component View 
```
<div>
    {{ $message }}
</div>
```

3- plcae where the compnet is acceesd
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>
</head>

<body>
    <x-users.userslist />

</body>
</html>

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
