### ISSUE TITLE
Eloquent Api Resource ignores cast formatting

### ISSUE THREAD

**Issue by DrowningElysium** [laravel/framework#45076]
- Laravel Version: All
- PHP Version: All
- Database Driver & Version: All

### Description:
In the documentation of [Model Casts](https://laravel.com/docs/9.x/eloquent-mutators#date-casting) it shows an example where you can provide a format when the model is serialized or converted to an array. 

Eloquent API Resources are also meant to format your resources (For example models). However these resources call the $model->{$key} basically, which ignores the format as it's just converted to an object. Because of this the casts format is ignored.

### Steps To Reproduce:
Model:
```php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Example extends Model
{
    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'birthday' => 'date:Y-m-d',
    ];
}
```
ApiResource:
```php
namespace App\Resources;

use Illuminate\Http\Resource\Json\JsonResource;

class ExampleResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
     public function toArray(Request $request)
    {
        return [
            'birthday' => $this->birthday,
        ];
    }
}
```

### Expected result:
```json
{
    'birthday': '2022-11-24'
}
```

### Actual result:
I have written this of memory, so the actual format might be different, but it's the ISO8601 format. 
```json
{
    'birthday': '2022-11-24T00:00:00'
}
```

**Comment by ankurk91** [comment]
You can do like:

```php
public function toArray(Request $request)
    {
        return $this->only(['birthday']);
    }
```

**Comment by driesvints** [comment]
Hey there. This is the expected behavior. The JSON API Resources are meant to give you control over this so it doesn't converts to the cast.

**Comment by DrowningElysium** [comment]
@driesvints, I don't find it expected behavior. The docs tell you to call your attributes for the model and show examples where it only calls $model->created_at. As the docs say it's for serialization, it kinda gives the idea that the resource would respect the formatting of the cast. 

This is what the combination of the two pages create as expectation. So I would think it might be good to make this more clear on the documentation of the Eloquent Api Resources, as there is currently nothing that tells the user about casts there.

**Comment by driesvints** [comment]
We'd always appreciate a PR to the docs to clarify anything.

**Comment by tuckerww** [comment]
Since the Resource ignores the Model's casts, what is the recommended way to apply the Model's casts to a Resource? (Or to apply the same casts manually in the Resource?)

I understand the reasoning now, but I would agree that having the model's casts apply to the resource would seem like the expected out-of-the-box behavior.

**Comment by tuckerww** [comment]
I ended up using the `format()` method on individual fields in the Resource to replicate the casts from the Model, like so:

```
return [
    ...,
    "deadline" => $this->deadline->format("Y-m-d"),
    ...
];
```

That works pretty well.  That said, please let me know if there's a better, less redundant way to do this.
