### ISSUE TITLE
Syntax error: unexpected token '?'

### ISSUE THREAD

**Issue by tiger-githubb** [laravel/framework#45086]
- Laravel Version:  v9.41.0
- PHP Version : v8.1.5
- Database Driver & Version: 10.00.22621.819

### Description:
I just created a new laravel 9 project and in my console I got two errors "Syntax error: unexpected token '?'" and "Syntax error: unexpected token 'Requirement'" 

![Screenshot 2022-11-25 124302](https://user-images.githubusercontent.com/98205891/203988367-a378faaf-424a-44a5-8115-be8dc3aa2e13.png)

### Steps To Reproduce:

-Just create a new laravel project

**Comment by driesvints** [comment]
Setting up a new project works just fine for me.

**Comment by lk77** [comment]
You are likely on a php version lower than 7.4
