### ISSUE TITLE
FormRequest out of range integer throws Laravel exception instead of FormError with Inertia and React

### ISSUE THREAD

**Issue by felixele217** [laravel/framework#45085]
- Laravel Version: 9.40.1
- PHP Version: 8.1.12
- Database Driver & Version: mysql 8.0

### Description:
I am using Laravel + Inertia + React.js and the https://inertiajs.com/forms useForm() hook which usually throws very nice form errors if the validation fails.

I have 
``` 
'studies_completed' => 'integer'
```
in a FormRequest-Class.

If I try to submit the form with a integer that is out of range, I receive a Laravel Error instead of receiving a form error from Inertia:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/50794814/203983327-6bc860d1-d32d-4ce9-996e-77ceb61295f3.png">

I worked around this issue with creating a custom Rule:
```
'studies_completed' => new ValidInteger,
```
where in ValidInteger Rule Class I do
```
    public function passes($attribute, $value): bool
    {
        return is_int($value);
    }

    public function message(): string
    {
        return 'The :attribute is out of range.';
    }
```

It would be nice if this would already be handled automatically. :) 
Anyways this is my first time reporting an issue, so if you need further information hit me up.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
