### ISSUE TITLE
Anonymous blade component props executed/resolved twice

### ISSUE THREAD

**Issue by bradietilley** [laravel/framework#45094]
- Laravel Version: 9.41.0
- PHP Version: 8.1.9
- Database Driver & Version: irrelevant

### Description:

Props passed to anonymous Blade components are being executed twice during the render of a view. Second execution of the code is irrelevant and not even used by Blade itself (see below for explanation).

Possible issues caused by this issue:
  - Duplicate logging, if the method you call performs an audit log or something similar.
  - Duplicate DB queries (if you dare query the DB within blade!)
  - Duplicate Mail attachments (as seen below)
  - Time consuming and wasteful, especially if the method you call is expensive.

### Steps To Reproduce:

I installed a fresh Laravel and all within [this single commit](https://github.com/bradietilley/laravel-mail-bug/commit/90795f770077d971aa7b96e7812d3b0cf4d3da6b) I managed to reproduce the issue (excuse the grammar in my doc comments lol). To clarify, my test focuses around a mail view with the [double] execution of `$message->embed()`, however, this issue applies to normal views as well as demonstrated here in [a second commit](https://github.com/bradietilley/laravel-mail-bug/commit/b2933167d095c9e0eecabcb30d3fcf45d00884b1).

A step-by-step breakdown to reproduce this issue:

- Add anonymous blade component with a prop (doesn't matter what the prop is or what happens to it -- just echo it inside the component)
- Add a view that includes this blade component (via `<x-component>`) and,
  - for the prop's value, reference a class method or global function (e.g. `:my-prop="$user->doSomething()"`)
- Do something in this class method or function that you would only want executed once (logging, db query, etc)
- Add the view to a new route (`Route::get('test', fn () => view('my-view') );`)
- Load the route

Even tried variations of:
- `:src="$message->embed()"`
- `src="{{ $message->embed() }}"`
- with `@props([ 'src' ])` inside the anonymous component blade file.

#### Expect:

The method or function (`$user->doSomething()`) to be run only once

#### Actual:

The method or function (`$user->doSomething()`) is run twice. The result from the first run is displayed, the second is tossed in the void (I think).

**Comment by bradietilley** [comment]
Just to bring what I wrote in my commit into this discussion, there's two possible fixes:

- `Blade` should remember the prop's resolved value and re-use it, and/or
- `Message` should remember files that it embeds to prevent duplicate embeds

**Comment by bradietilley** [comment]
Inside one of the blade files in `storage/framework/views` there's a line that looks like (YOUR_EXPRESSION_HERE being the expression used as the prop):

```php
<?php $component->withAttributes(['src' => ''.e(YOUR_EXPRESSION_HERE).'']); ?>
```

This is the second reference of YOUR_EXPRESSION_HERE here this file.

A simple fix is to remove this withAttributes for anonymous components (unless I'm missing something and it's actually needed twice) or more simply to change it to the below for anonymous components:

```php
<?php $component->attributes ?? $component->withAttributes(['src' => ''.e(YOUR_EXPRESSION_HERE).'']); ?>
```

Could be overlooking something obvious but to me it seems like something ain't right here with the code being referenced and run twice.

**Comment by driesvints** [comment]
Hi @bradietilley. That's a indeed a bit annoying. But in general I'd suggest to not perform such operations in an attribute. It's best to perform the operation up front before passing it to the attribute:

```blade
<div>
    <x-logo
        :src="$srcPath"
    />
</div>
```

That way you don't risk it being run twice. That's also the reason why we don't document passing an operation as an attribute.

**Comment by bradietilley** [comment]
Fair enough - we've just gone ahead with a workaround of passing the message variable to the child component and we do it there.

I'm still confused though - is there any reason why the props are computed twice instead of each prop being cached after the first execution?

**Comment by driesvints** [comment]
I'm not sure, sorry.
