### ISSUE TITLE
Anonymous Global Scopes does not apply after $model->refresh()

### ISSUE THREAD

**Issue by amshehzad** [laravel/framework#45091]
- Laravel Version: 9.41.0
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:
When a refresh method is called on a model,  the Anonymous Global Scope does applied on model

### Steps To Reproduce:
In User Model, apply a global scope to select a column like this:

 ```
  protected static function booted()
  {
      static::addGlobalScope(fn(Builder $builder) => $builder
          ->when(
              is_null($builder->getQuery()->columns),
              fn(Builder $builder) => $builder->addSelect('*')
          )
          ->selectRaw("34 AS age")
      );
  }
```

Then in UserController:

```
$user = \App\Models\User::first();
$user->age;  // 34
$user->refresh();
$user->age;  // null
```

**Comment by WendellAdriel** [comment]
I think the same can be achieved using the `$attributes` array in the model instead of the global scope or am I missing something @amshehzad?

**Comment by amshehzad** [comment]
@WendellAdriel Yes that would be right if I had the same exact same attribute. I just added it here as an example, 
Actual code was this:
```
static::addGlobalScope(fn(Builder $builder) => $builder
            ->when(
                is_null($builder->getQuery()->columns),
                fn(Builder $builder) => $builder->addSelect('*')
            )
            ->selectRaw('IFNULL((SELECT SUM(amount) FROM leave_transactions WHERE user_id = users.id), 0) AS leave_balance')
        );
```

**Comment by WendellAdriel** [comment]
@amshehzad oh got it!
Can’t you do that with an `$appends` attribute using the relation between the two models?

**Comment by mattford** [comment]
I'm not sure you're using global scopes as intended, it looks like perhaps you need an accessor:

```
public function getAgeAttribute()
{
    return 34;
}
```

**Comment by taylorotwell** [comment]
I don't think we would global scopes to apply on a `refresh` call - you could fail to retrieve the model entirely this way.
