### ISSUE TITLE
Laravel Form Validation Inconsistency

### ISSUE THREAD

**Issue by sedattcom** [laravel/framework#45146]
- Laravel Version: 9.42.0
- PHP Version: 8.1.13
- Database Driver & Version:

### Description:
Before laravel 9 update, form rules were working as I wanted. It started behaving differently after the update.

While the same code and the same request occur without an error in laravel 8, error code 422 is returned in laravel 9.

### Steps To Reproduce:
```
Route::post('test', function (\Illuminate\Http\Request $request) {
    $request->validate([
        'type' => [
            'bail',
            'exclude_if:type,',
            'in:individual,corporate',
        ],
        'name' => [
            'bail',
            'exclude_if:type,',
            'required_with:type',
            'min:3',
            'max:49',
        ],
        'id' => [
            'bail',
            'exclude_if:type,',
            'required_with:type',
            'digits:10',
        ],
        'tax_office' => [
            'bail',
            'exclude_unless:type,corporate',
            'required_if:type,corporate',
            'min:2',
            'max:99',
        ],
    ], $request->all());
});
```

Request:
```
curl --location --request POST 'https://site.dev/api/test' \
--header 'Accept: application/json' \
--header 'X-Requested-With: XMLHttpRequest' \
--header 'Content-Type: application/json;charset=UTF-8' \
--form 'type=""' \
--form 'name=""' \
--form 'id=""' \
--form 'tax_office=""'
```

Laravel 8.21.0 response status code: 200
Laravel 9.42.0 response status code: 422

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by sedattcom** [comment]
Hello again,

this is definitely a bug.
After "exclude_if:type," in the first rule (in $this->data used on line 1730 in ValidatesAttributes.php in v9.42.0), the type is deleted, returning true here when checking the second rule. But here it checks the name field even though it returns true.

**Comment by sedattcom** [comment]
This problem started after upgrading from v8.38.0 to v8.39.0. I couldn't find where the validateExcludeIf method is being called. The problem is probably from there.

**Comment by sedattcom** [comment]
ok i found the problem.

in ValidatesAttributes.php
if (! Arr::has($this->data, $parameters[0])) {
             return true;
         }

Here it should return false, not true.
