### ISSUE TITLE
save() updates different row than expected when using <Model>::join()

### ISSUE THREAD

**Issue by pawel-baster** [laravel/framework#45143]
- Laravel Version: 9.17.0
- PHP Version: 8.1.9
- Database Driver & Version: php8.1-mysql 8.1.9

### Description:

If you call `::join()` on a model to query the database and then attempt to update one of the retrieved objects, then you are very likely to unexpectedly update an entirely different record.

### Steps To Reproduce:

For a simple one-to-many relation defined by migrations:

```
Schema::create('stores', function (Blueprint $table) {
    $table->id();
    $table->timestamps();
});

Schema::create('customers', function (Blueprint $table) {
    $table->id();
    $table->foreignId('store_id')->constrained()->onDelete('cascade');
    $table->string('name');
    $table->timestamps();
});
```

and empty model classes `Store` and `Customer` generated by laravel, the following unit test fails: 

```
class UpdateTest extends TestCase
{
    use RefreshDatabase;

    public function testUpdate()
    {
        // fixtures:
        $store = Store::create(['id' => 2]);

        $customerToBeUpdated = Customer::create([
            'id' => 1,
            'store_id' => $store->id,
            'name' => 'Alice',
        ]);
        $customerNotToBeUpdated = Customer::create([
            'id' => 2,
            'name' => 'Bob',
            'store_id' => $store->id,
        ]);

        // Query with ::join() that is causing the problem
        $query = Customer::join('stores', 'store_id', 'stores.id')->where(['name' => 'Alice']);

        // sanity checks, in order to be sure that the query returns just one record: $customerToBeUpdated
        $this->assertEquals(1, $query->count());
        $customer = $query->first();
        $this->assertInstanceOf(Customer::class, $customer);
        $this->assertEquals('Alice', $customer->name);

        // update which is not working as expected:
        $customer->name = 'updated name';
        $customer->save();

        $customerToBeUpdated->refresh();
        $customerNotToBeUpdated->refresh();

        // All three following assertions fail, because in fact 
        // $customerNotToBeUpdated was updated instead of $customerToBeUpdated.

        $this->assertEquals('updated name', $customerToBeUpdated->name,
                 'the name in this record should just have been updated, but it still returns "Alice"');
        $this->assertEquals('Bob', $customerNotToBeUpdated->name, 
                'this record should not have been updated, but the name returns "updated name" now');

        // this seems to be the root cause of the problem:
        $this->assertEquals($customerToBeUpdated->id, $customer->id);
    }
}
```

### Expected behavior:

Either updating the correct customer or throwing an exception saying that updates of records retrieved from queries like this one are not supported.

### Likely root cause:

When `JOIN` clause is added, then the `id` column in the resultset no longer contains `customers.id` but `stores.id` instead. Laravel apparently does not take it into account when updating the customer using `$customer->save()` or `$customer->update(...)` and therefore incorrectly uses store's id as if it was the customer's id in `UPDATE customers SET ... WHERE id = ?`. 

This is the actual query logged by the query log in the above test:
```
"update `customers` set `name` = ?, `customers`.`updated_at` = ? where `id` = ?"
```
Bindings: `['updated name', "2022-11-29 21:30:28", 2]`
The third param should have been set to 1 (`$customerToBeUpdated`'s id), not 2 (`$customerToBeUpdated->store`'s id).

### Workaround:

Adding `->select('customers.*')` to the query prevents overwriting customer's id with store's id and then all the assertions pass.

**Comment by driesvints** [comment]
The workaround is the actual solution here. You're basically using Eloquent models like the query builder in Laravel and when you retrieve *all* columns from both joined tables then yes colliding columns will be overwritten. If you want to prevent this then either retrieve only the column you need (like your solution) or use proper relations which Eloquent is smart enough to handle.
