### ISSUE TITLE
BelongsToMany Pivot Model Global Scopes are never run.

### ISSUE THREAD

**Issue by jonathan-bird** [laravel/framework#45151]
- Laravel Version: 9.42.2
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.30

### Description:
BelongsToMany Pivot Model Global Scope is never run.

As of Laravel 5.8, Pivots are basically models. You can call them easily using the `using()` method, however even though the "withGlobalScope" is run in the Pivot's `booted` method, the global scopes of the Pivot are never called, thus never actually get run.

### Steps To Reproduce:

Relationship (works correctly): 

```
// Call the relationship, using the Pivot
public function classes()
{
    return $this
        ->belongsToMany(SchoolClass::class)
        ->using(SchoolClassSchoolStudent::class);
}
```

Pivot model:

```
<?php

namespace App\Models\SchoolPublisher\Pivots;

use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Database\Query\Builder;
use XYZ\ABC\Scopes\SyncActive;

class SchoolClassSchoolStudent extends Pivot
{
    public $timestamps = true;

    protected $table = 'school_class_school_student';

    protected static function booted()
    {
        // Test manually
        static::addGlobalScope('test2', function (Builder $builder) {
            dd('never applied.');
            $builder->where('sync_active', '=', true);
        });

        // Test using class scope, doesn't work either.
        static::addGlobalScope(new SyncActive());
    }
}
```

Interestingly enough, the global scope is applied when running code like, as the detach doesn't want to work and there is no way that I can find that I can use `->using(SchoolClassSchoolStudent::class)` and remove the global scope either - the `withoutGlobalScopes()` doesn't remove the scope on the pivot model:

```
$schoolStudent->classesWithoutGlobalScopes()->detach($schoolClass->uuid);
```

Usage:

```
@foreach ($schoolStudent->classes as $key => $schoolClass)
  // Standard loop usage, issue is that it's showing both inactive & active rows, 
  // despite global scope, as it is never called.
@endforeach
```

### Workaround:

I have found that the basic `->wherePivot()` method works if you apply it directly after `->using()`.

I think I'm also better off not using a Pivot model at all as even when I use global scope, as explained above, I can't find a way to remove it as required.

Is there something I'm missing here?

**Comment by driesvints** [comment]
In this case I'd suggest to just use an Eloquent model. There are some limitations to Pivot models and events/scopes are one of them. For example, the soft delete trait on pivot models also doesn't work: https://laravel.com/docs/9.x/eloquent-relationships#defining-custom-intermediate-table-models

If you run into limitations on pivot models then the best choice is always to convert it to an Eloquent model.

**Comment by jonathan-bird** [comment]
@driesvints Yeah I tried soft deletes and found that too, ended up coding a solution for soft deletes with pivots but I think you're right there, I'll just use an Eloquent model.

Thanks mate :)
