### ISSUE TITLE
Blade components can not receive the data from @yield() directive.

### ISSUE THREAD

**Issue by aknEvrnky** [laravel/framework#45161]
- Laravel Version: 9.31.0
- PHP Version: 8.1.11
- Database Driver & Version:
- mysql@8.0.31

### Description:
Blade components can not receive the data from @ yield() directive. I want to pass activeStep data to my layout and then
to my blade component. I can pass the data to layout, but the layout can not pass the data to component. It passes the string `@yield()` as string. I've used `View::getSections()['activeStep']` for temporary solution, but I think it is a bug since we can
use these approach with html markup.

### Steps To Reproduce:

```php
<x-front.order.order-process active="@yield('activeStep')" />
// dd($active) => "@yield('activeStep')" 
// passes as string
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
