### ISSUE TITLE
The WithoutModelEvents trait breaks seeding for UUID fields.

### ISSUE THREAD

**Issue by aleksejjj** [laravel/framework#45177]
- Laravel Version: 9.42.2
- PHP Version: 8.1.12
- Database Driver & Version:

### Description:
Hi. Maybe it's just docs issue:

The `WithoutModelEvents` trait breaks seeding for UUID fields.

### Steps To Reproduce:
Uncomment and use `Illuminate\Database\Console\Seeds\WithoutModelEvents` in `DatabaseSeeder`
Change `users` table `id` to `uuid` - `$table->uuid('id');`
Add `HasUuids` trait to `User` model
Run DB seed with `\App\Models\User::factory(10)->create();`

**Comment by rodrigopedra** [comment]
Regular IDs are auto-generated by the database. UUIDs are not. 

The `HasUuids` trait autopopulates a UUID to each new model by leveraging model events. So it feels seamlessly when moving from auto-increment IDs.

If you want to add the `WithoutModelEvents` to your seeder, you will need to manually provide a UUID in your model factory.

Just add:

```php
'id' => fake()->uuid(),
```

To your `UserFactory@definition` method's returned array.

**Comment by driesvints** [comment]
Model events are needed for this trait.
