### ISSUE TITLE
Can't create FKs using `foreignIdFor` on not auto-incremented IDs

### ISSUE THREAD

**Issue by d3v4nt** [laravel/framework#45186]
- Laravel Version: 9.35.1
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 5.7

### Description:
Method `foreignIdFor` on `Illuminate\Database\Schema\Blueprint` not working with not incremented IDs.
I really hope I'm not miss understanding the problem and it's not intended to be this way.
I wasn't able to find a logical explanation of why this check is needed...
```php
public function foreignIdFor($model, $column = null)
    {
        if (is_string($model)) {
            $model = new $model;
        }

        // -------------------------------------------------👇
        return $model->getKeyType() === 'int' && $model->getIncrementing()
                    ? $this->foreignId($column ?: $model->getForeignKey())
                    : $this->foreignUuid($column ?: $model->getForeignKey());
    }
```

### Steps To Reproduce:
Create a migration with the table that does not increment the id:
(I do that because the brands are imported and I want to maintain original IDs)
```php
Schema::create('brands', function (Blueprint $table) {
    $table->unsignedBigInteger('id')->primary();
});
```

Use the model class in the `foreignIdFor` helper method:
```php
 Schema::table('cars', function (Blueprint $table) {
    $table->foreignIdFor(Brand::class)->nullable()->constrained()->nullOnDelete();
});
```

### Temporal solution:
I get that it can be solved just defining the relation manually. I just prefer using helper methods when it's possible 🤷‍♂️
```php
Schema::table('cars', function (Blueprint $table) {
    $table->unsignedBigInteger('brand_id')->after('id')->nullable();
    $table->foreign('brand_id')->references('id')->on('brands')->nullOnDelete();
});
```
p.s.: Also would really like to know why that check should be there if I'm missing something.

**Comment by d3v4nt** [comment]
@driesvints will do, thank you for getting back to me! Is there any explanation why, just curious?

**Comment by driesvints** [comment]
I don't have any, sorry.
