### ISSUE TITLE
app('router')->getRoutes() only returns rotations in one language.

### ISSUE THREAD

**Issue by mertbuldur** [laravel/framework#45194]
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version:

### Description:
Hello, I'm using the mcamara package. I'm trying to switch languages on the site.
However, in the code below, I cannot capture the routes in lang/en/routes.php. While it works in Laravel 7, it does not work in 8.
It just returns the rotation in lang/en/routes.php.

```
$url = url()->previous();
        $route = collect(app('router')->getRoutes())->first(function($route) use($url){
        return $route->matches(request()->create($url));
});
```

Web.php

```
Route::group(['as' => 'visit.'], function () {
        Route::get(LaravelLocalization::transRoute('routes.visit'), [\App\Http\Controllers\front\visit\indexController::class, 'index'])->name('index');
        Route::get(LaravelLocalization::transRoute('routes.visit_detail'), [\App\Http\Controllers\front\visit\indexController::class, 'page'])->name('page');
    });
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
