### ISSUE TITLE
Eloquent Global Scopes are applied on update queries

### ISSUE THREAD

**Issue by 4ice** [laravel/framework#45205]
- Laravel Version: v9.42.2
- PHP Version: 8.1.12
- Database Driver & Version: SingleStore version 7.9.13

### Description:
When adding a global scope to a model, the global scope is applied on all queries. For instance, if you add a orderBy scope, it is applied on  update queries, here is an example for an update:
```update `filter_tags` set `group_type` = CHECKBOX, `filter_tags`.`updated_at` = 2022-12-06 16:04:59 where `group_type` is null order by `sort_order` asc```.

The last part of the query: ```order by `sort_order` asc``` is allowed my MySQL, but for other database drivers, such as SingleStore, this query is not valid.

I think that global scopes should not be applied to update queries.

### Steps To Reproduce:

1. Create a Eloquent Model
2. Add a global scope to the model:
```php
    public static function bootHasSortOrder()
    {
        static::addGlobalScope('ordered', function(Builder $builder) {
            $builder->orderBy('sort_order','asc');
        });
    }
```
3. Run the `update`-function on an instance of the model that was created in step 1
4. dd the statement that is about to be executed by going to the file `Illuminate\Database\Connection` and the function `affectingStatement` just before the line `$statement->execute();` with the following code:
```php
dd($statement);
```

**Comment by 4ice** [comment]
The same issue is occurring when using the `delete()`-function

**Comment by driesvints** [comment]
This is the expected behavior. I'd suggest to not use a global scope for this.

**Comment by 4ice** [comment]
Why is is expected behavior to for instance run `order by` on update or delete? I can not see how there could be a use case for this.

**Comment by 4ice** [comment]
@driesvints  - Why is this the expected behaviour? I can not see any reason for why an `order by` should ever be added to a update or delete statement.

**Comment by 4ice** [comment]
For anyone that reads this in the future, I got the following answer from Taylor Otwell in the Laravel discord channel:

> I personally am not a fan of global scopes and try to avoid them when possible - in your situation i would probably put access to this resource behind a repository class or something that ensures the order is always present as needed... then only access that model through that repository
