### ISSUE TITLE
Custom model attribute date casts ("date:d-m-Y") using a non-UTC date do not seem to work as intended

### ISSUE THREAD

**Issue by Restartz** [laravel/framework#45201]
- Laravel Version: 8.83.23
- PHP Version: 7.4.27
- Database Driver & Version: MariaDB 10.7.3

### Description:

> If a custom format is applied to the date or datetime cast, such as datetime:Y-m-d H:i:s, the inner timezone of the Carbon instance will be used during date serialization. Typically, this will be the timezone specified in your application's timezone configuration option. - https://laravel.com/docs/8.x/eloquent-mutators#custom-casts

This doesn't seem to work as intended when defining a field in both the $dates and the $casts array with fi. "date:d-m-Y".

It seems the `attributesToArray` method first converts all $dates to iso 8601 strings (to UTC) calling the `addDateAttributesToArray` method, and afterwards tries to convert the $casts using `addCastAttributesToArray` but by then they are already converted to UTC string representations, and thus the original timezone seems to be disregarded.

### Steps To Reproduce:

Have any non-UTC date in your database (fi. date_of_birth in a 'Europe/Amsterdam' timezone)

app.php:

`'timezone' => 'Europe/Amsterdam',`

User.php:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $dates = [
        'date_of_birth'
    ];

    protected $casts = [
        'date_of_birth' => 'date:d-m-Y',
    ];
}

```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
