### ISSUE TITLE
Error in Component Slots

### ISSUE THREAD

**Issue by joaopalopes24** [laravel/framework#45204]
- Laravel Version: 9.41.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL v8.0

### Description: 

Inside my application I have an `x-card` component that has a slot for the footer as follows:

```
@if (isset($footer))
    <div {{ $footer->attributes->class('flex') }}>
        {{ $footer }}
    </div>
@endif
```

And I have another component in my application called `x-modal-card` that uses the `x-card` and passes the footer as follows:

```
@if(isset($footer))
    <x-slot name="footer">
        {{ $footer }}
    </x-slot>
@endif
```

But I'm having trouble passing the attributes in the `x-modal-card` component. I tried the following solutions:

```
@if(isset($footer))
    <x-slot name="footer" {{ $footer->attributes }}>
        {{ $footer }}
    </x-slot>
@endif

@if(isset($footer))
    <x-slot name="footer" {{ $footer->attributes->toHtml() ?? '' }}>
        {{ $footer }}
    </x-slot>
@endif

@if(isset($footer))
    <x-slot name="footer" {{ $footer->attributes->getAttributes() ?? [] }}>
        {{ $footer }}
    </x-slot>
@endif
```

But all of them didn't work and returns error.

### Images:

![01](https://user-images.githubusercontent.com/45684782/206011353-3081d0cf-14a9-45cc-9a9c-c4362e4f26d3.jpeg)
![02](https://user-images.githubusercontent.com/45684782/206011406-739fa2d3-5f27-4406-980a-d97ad374e621.jpeg)
![03](https://user-images.githubusercontent.com/45684782/206011400-e0d49f80-9580-4563-abb2-a73789afe0e0.jpeg)
![04](https://user-images.githubusercontent.com/45684782/206011399-f39e3c8f-790f-406d-96a2-3622390da9d2.jpeg)
![05](https://user-images.githubusercontent.com/45684782/206011394-c5b5887f-802a-4d30-8b03-de97562f1450.jpeg)
![06](https://user-images.githubusercontent.com/45684782/206011390-53e78331-06af-4bfd-8c6a-986509e92cb7.jpeg)

That's how it works:

![07 - run with success](https://user-images.githubusercontent.com/45684782/206011506-4ab594b6-1ef0-42b0-93f3-0db728b8a411.jpeg)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
