### ISSUE TITLE
Bug in ServiceProvider / mergeConfigFrom()

### ISSUE THREAD

**Issue by theupriser** [laravel/framework#45213]
- Laravel Version: 9.43
- PHP Version: 8.1.11
- Database Driver & Version:

### Description:

Hello, 

I've been trying to merge a config via a ServiceProvider using the mergeConfigFrom function. I got this error:
![image](https://user-images.githubusercontent.com/5661837/206144287-2682fd8c-a8e3-4915-9ffb-ba3bfa84c701.png)

After some searching and debugging in the mergeConfigFrom function I changed the array_merge to this:
![image](https://user-images.githubusercontent.com/5661837/206145249-8a4657cb-e464-43ff-bdcf-76d55231d107.png)

I understand that it shouldn't be this way because of the array_merge overwriting in the wrong order. But why does the `require $path` in front of the `$config->get($key, [])` not work for me? Is it an IO thing?

edit: The problem also occurs when the config file is returning an empty array. File permissions look good.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
