### ISSUE TITLE
`renderable` ignores Throwable

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#45220]
- Laravel Version: 9.*
- PHP Version: 8.1
- Database Driver & Version:

### Description:

```php
namespace App\Exceptions;

public function register()
{
    $this->renderable(function (Throwable $e) {
        //won't reach here when an exception occur in the app
        Slack::sendMessage($e->getMessage());

    });
}
```

As you can see i registered `Throwable` (all kind of exception) in the renderable method, But when an exception occur in the app, it does not call the closure.

### Steps To Reproduce:

```php
Route::get('test', function(){
    throw new InvalidArgumentException('Test Exception');
});
```

**Comment by driesvints** [comment]
Works fine for me.

<img width="496" alt="Screenshot 2022-12-08 at 15 25 32" src="https://user-images.githubusercontent.com/594614/206471568-18af5bb6-083d-49e2-802c-316f2aa4f31d.png">
<img width="874" alt="Screenshot 2022-12-08 at 15 25 43" src="https://user-images.githubusercontent.com/594614/206471569-d1cd1d68-085c-4d1f-bc52-eedee6e23e3f.png">
<img width="544" alt="Screenshot 2022-12-08 at 15 25 59" src="https://user-images.githubusercontent.com/594614/206471573-66079ea0-52e7-4768-aefb-c3fd1ffd061a.png">
