### ISSUE TITLE
Validation rule "exists" passes soft deletes

### ISSUE THREAD

**Issue by robvan2** [laravel/framework#45224]
- Laravel Version: 9.34.0
- PHP Version: 8.1.6
- Database Driver & Version: MariaDB 10.4.24

### Description:
Laravel validation rule exists doesn't test on soft deletes by default.

### Steps To Reproduce:
tables : 
- categories:
        -id
        -name
- product:
        -id
        -category_id
        -name ....

example:
I deleted a category `id==1` and I added a product with `category_id == 1` it just adds it to the table the
`Rule::exists('categories', 'id')` is returning true.

Rules :
`$rules =   [
            'name'          => 'required|string|max:160',
            'category_id'   => ['required', Rule::exists('categories', 'id')],
        ];`

**Comment by driesvints** [comment]
Soft deletes aren't covered by this rule. You need to explicitly add a constraint for this.
