### ISSUE TITLE
Migrasi yang gagal menambahkan index tidak bisa dikembalikan,

### ISSUE THREAD

**Issue by cambagulung** [laravel/framework#45228]
- Laravel Version: 9.19
- PHP Version: 8.1

### Description:
Saya membuat migration seperti di bawah ini,

        Schema::create('metas', function (Blueprint $table)
        {
            $table->id();
            $table->timestamps();
            $table->bigInteger('metable_id');
            $table->string('metable_type');
            $table->string('key')->index();
            $table->longtext('value');

            $table->unique(['metable_model, 'metable_id', 'key']); // ini akan memicu error karena salah memasukan nama kolom
            $table->index(['key', 'metable_type']);
        });

saat menjalankan migrasi ini laravel akan menghasilkan error seperti yang sudah saya jelaskan sebelumnya, setelah saya memperbaiki error dan mencoba menjalankan migrasi tabel metas sudah ada di dalam database sehingga migrasi tidak bisa dijalankan.

saya bermaksud menghapus tabel metas dengan cara melakukan rollback tapi itu tidak berhasil dan saya harus menghapus tabelnya secara manual menggunakan database client.

**Comment by driesvints** [comment]
Unfortunately we can only provide support in English.
