### ISSUE TITLE
The log driver for mail is adding some extra characters in the log file.

### ISSUE THREAD

**Issue by sachinkumar121** [laravel/framework#45245]
Here are the details of the packages.

- Laravel Version: 9.43.0
- PHP Version: 8.1.11
- Database Driver & Version: Server version: 8.0.25 - MySQL

### Description:

I update the Laravel version to 9. Everything is working fine after the upgrade.
 
I am using the Log driver for mail as I am developing on my local system but the mail content inserts in my `laravel.log` file append some extra content so it is difficult to open the URL. 
The next line is converted into `=` and I don't know what is this `--443HnvBP--`. 

This extra append string makes the verification link invalid. (i.e 404 page)

> MAIL_MAILER=log

Here is the example(User verification email)

***Text version***
       
    Thanks for crea=
    ting an account with InstaWP.
    
    Verify your email account by clicking on=
     below button
    
    Verify Email Address: http://localhost:8000/email/verify=
    /3/744ff86c600429114e8bcbfcf2c38d23b227ad74?expires=3D1670592804&signature=
    =3D55417e62485ca154af312bd48703c3e1849379ef7a0a0398d2378a4ae2638b04
    
    Re=
    gards,
    InstaWP Team

***HTML version(I didn't provide the entire content but you get the idea)***

    <html>
    <table>
    <a href=3D"http://localhost:8000/email/verify/3/744ff86c6=
    00429114e8bcbfcf2c38d23b227ad74?expires=3D1670592804&amp;signature=3D55417e=
    62485ca154af312bd48703c3e1849379ef7a0a0398d2378a4ae2638b04" class=3D"button=
     button-primary" target=3D"_blank" rel=3D"noopener" style=3D"box-sizing: bo=
    rder-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Robot=
    o, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Se=
    goe UI Symbol'; position: relative; -webkit-text-size-adjust: none; border-=
    radius: 4px; color: #fff; display: inline-block; overflow: hidden; text-dec=
    oration: none; background-color: #2d3748; border-bottom: 8px solid #2d3748;=
     border-left: 18px solid #2d3748; border-right: 18px solid #2d3748; border-=
    top: 8px solid #2d3748;">Verify Email Address</a>
    =
    </table>
    </td>
    </tr>
    </table>
    </td>
    </tr>
    </table>
    </body>
    =
    </html>
    --443HnvBP--

### Steps To Reproduce:

- Install the latest Laravel version with the User and Auth system.
- set `MAIL_MAILER=log` in the .env file.
- implement the `MustVerifyEmail` contract on the `User.php` Model.
- create a user and check the mail content produced by the framework in the `laravel.log` file.

**Comment by driesvints** [comment]
There's no issue here. The HTML version is generated by Symfony Mailer. We don't control the content. Given that Symfony Mailer is a highly tested and tried component you can be sure this is safe.

**Comment by sachinkumar121** [comment]
I tested this by installing a new version as well. I have the same issue. Should I raise an issue to the "Symfony Mailer" repo?
