### ISSUE TITLE
Sessions stop working once you override SessionsManager

### ISSUE THREAD

**Issue by maktouch** [laravel/framework#45252]
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: whatever version that comes with a fresh installation

### Description:

From what I understand, it's 

SessionServiceProvider -> SessionManager -> Store & EncryptedStore

When I override SessionServiceProvider, it's fine. 
As soon as I override SessionManager, my CSRF token stops showing up on my frontend. I even tried a simple extend without overriding any methods, and it's the same issue. It's as if `\Illuminate\Session\SessionManager` is hardcoded somewhere. 

### Steps To Reproduce:

Repo: https://github.com/maktouch/laravel-session-extend-bug
- Git clone, composer install, sails up
- http://localhost/login
- Open inspector.. CSRF token are null. 
- Open app/Session/SessionServiceProvider
- uncomment line 7 to `use Illuminate\Session\SessionManager;`
- Refresh login page.. CSRF Token are back. 

The commits are small: https://github.com/maktouch/laravel-session-extend-bug/commit/d542f257c063dfc36d6a7ef570892918e4701ae6

**Comment by driesvints** [comment]
I'm sorry but we cannot provide support for any customization you make here. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
