### ISSUE TITLE
Request ->validated() call returns arrays in different order to the payload

### ISSUE THREAD

**Issue by bretto36** [laravel/framework#45269]
- Laravel Version: 9.36
- PHP Version: 8.0.24
- Database Driver & Version: -

### Description:

Since the release of #37943 using the ->validated() method has resulted in arrays having different sort order

```
'services'            => 'required|array|min:1',
'services.*.service'  => 'sometimes|required_without:services.*.content',
'services.*.content'  => 'sometimes|required_without:services.*.service',
```

So the ->validated() call will return an array and it will preference the array values that match the first few rules. So any that match services.*.content will be last no matter what order they appeared in the payload.

Is this expected that the sort order of arrays in the payload can be different? Does this need to be added to the docs? I've had to call $request->get() instead of using the validated data array which i prefer to use

### Steps To Reproduce:

If you were to post 

```
$data = [
'services' => [
    '0' => ['custom' => 'This is custom text and should be at the top'],
    '1' => ['service' => 'This uses a service'],
]];
```

request->validated() will be [1] =>, then [0] =>

**Comment by driesvints** [comment]
Yeah I don't think we ever intended that sort order matters here.
