### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Serialization of 'finfo' is not allowed in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:155

### ISSUE THREAD

**Issue by deepak-a-insnapsys** [laravel/framework#45326]
- Laravel Version: 9.43.0
- PHP Version: 8.2.0
- Database Driver & Version: Mariadb Database v10.6
- Queue Driver : database.

### Description:
I receive the above error when attempting to dispatch a Batch Job. My code was working on the Laravel 8 version at the time.

Here is full strace
`
PHP Fatal error:  Uncaught Exception: Serialization of 'finfo' is not allowed in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(158): serialize()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(127): Illuminate\Queue\Queue->createObjectPayload()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(105): Illuminate\Queue\Queue->createPayloadArray()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(92): Illuminate\Queue\Queue->createPayload()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\Queue\DatabaseQueue->push()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(246): Illuminate\Queue\Queue->pushOn()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\Bus\Dispatcher->pushCommandToQueue()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\Bus\Dispatcher->dispatchToQueue()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\Bus\Dispatcher->dispatch()
#9 [internal function]: Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#10 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php on line 158
`

### Steps To Reproduce:

- Create New Job using `php artisan make:job TestJob`
- Add Batchable trait to Test job.
- Create test data array `$testData= [ "name"=> "Hello World"]`
- Add Test job in the batch Bus 
 `$batch = Bus::batch([new TestJob($testData)])
    ->then(function (Batch $batch) {
        // All jobs completed successfully...
    })
    ->catch(function (Batch $batch, \Throwable $e) {
        // First batch job failure detected...
    })
    ->finally(function (Batch $batch) {
        // The batch has finished executing...
    })
    ->dispatch();`
- Run Above code using tinker and you will get following error
`  WARNING  file_get_contents(eval()'d code): Failed to open stream: No such file or directory in vendor/laravel/serializable-closure/src/Support/ReflectionClosure.php on line 829.`
`Call to a member function bindTo() on null in vendor/laravel/serializable-closure/src/Serializers/Native.php on line 194.`
- And if we dispatch same job from schedule (Kernal.php) function we will get the following error.
`PHP Fatal error:  Uncaught Exception: Serialization of 'finfo' is not allowed in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:155`

**Comment by abbood** [comment]
@deepak-a-insnapsys You said:
> I receive the above error when attempting to dispatch a Batch Job. My code was working on the Laravel 8 version at the time.

However I tested your repro steps on both laravel 8 and laravel 9, and I got the same error on both:
- [laravel 9 testing branch](https://github.com/abbood/laravel-9-sandbox/tree/laravel-issue-45326)
- [laravel 8 testing branch](https://github.com/abbood/laravel-8-test/tree/laravel-issue-45326)

**Comment by abbood** [comment]
@deepak-a-insnapsys I took a further look, this code works fine from tinker:

```
$batch = Bus::batch([new TestJob($testData)])->dispatch();
= Illuminate\Bus\Batch {#3772
    +id: "980cad39-fd7a-4803-930a-b85ef77674f5",
    +name: "",
    +totalJobs: 1,
    +pendingJobs: 1,
    +failedJobs: 0,
    +failedJobIds: [],
    +options: [],
    +createdAt: Carbon\CarbonImmutable @1671802132 {#3678
      date: 2022-12-23 13:28:52.0 UTC (+00:00),
    },
    +cancelledAt: null,
    +finishedAt: null,
  }
```

but once you add closures, things blow up:

```
Bus::batch([new TestJob($testData)])->catch(function (Batch $batch, \Throwable $e) {})->dispatch();
   ERROR  Call to a member function bindTo() on null in vendor/laravel/serializable-closure/src/Serializers/Native.php on line 201.
```

and that's b/c closures cannot be serialized, see here: https://www.php.net/manual/en/function.serialize.php#113305

I hope this helps

**Comment by deepak-a-insnapsys** [comment]
@abbood
Thank you for your time.

Yes, you are correct. When we add a closure, we get an error.
I investigated the problem further and discovered that when we create a new class object (custom class) in the Job constructor function, the following error occurs.
` PHP Fatal error: Uncaught Exception: Serialization of 'finfo' is not allowed in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:155 `

So I removed the object creation code from the Job constructor  function, and it is now working.
But, to my surprise, my code worked in Laravel 8, PHP 7.3.33.

**Comment by abbood** [comment]
I'm glad it worked @deepak-a-insnapsys! As I mentioned [here](https://github.com/laravel/framework/issues/45326#issuecomment-1363874475), the problem also happened in laravel 8 so it makes sense for the fix to also work in laravel 8. 

@driesvints can you please mark this ticket as closed?

**Comment by driesvints** [comment]
Thanks
