### ISSUE TITLE
Cursor pagination when using group by and ordering by aggregate function

### ISSUE THREAD

**Issue by sajke-shevchenko** [laravel/framework#45320]
- Laravel Version: 9.43.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL (ver. 8.0.24)

### Description:

I have the following code in repository:
```
  return $this->query()
      ->select(['support_tickets.*', DB::raw('max(support_ticket_messages.id) as last_message')])
      ->join(
          'support_ticket_messages',
          'support_tickets.id',
          '=',
          'support_ticket_messages.ticket_id'
      )
      ->groupBy('support_tickets.id')
      ->orderByDesc('last_message')
      ->cursorPaginate($perPage);
```

When we use the cursor, it builds the query:
```
1 => array:3 [
      "type" => "Nested"
        +bindings: array:9 [
          "select" => []
          "from" => []
          "join" => []
          "where" => array:1 [
            0 => 284
          ]
          "groupBy" => []
          "having" => []
          "order" => []
          "union" => []
          "unionOrder" => []
        ]
        +aggregate: null
        +columns: null
        +distinct: false
        +from: "support_tickets"
        +joins: null
        +wheres: array:1 [
          0 => array:5 [
            "type" => "Basic"
            "column" => Illuminate\Database\Query\Expression {#16925
              #value: "max(support_ticket_messages.id)"
            }
            "operator" => "<"
            "value" => 284
            "boolean" => "and"
          ]
        ]
        +groups: null
        +havings: null
        +orders: null
        +limit: null
        +offset: null
        +unions: null
        +unionLimit: null
        +unionOffset: null
        +unionOrders: null
        +lock: null
        +beforeQueryCallbacks: []
        +useWritePdo: false
      }
      "boolean" => "and"
    ]
  ]
  +groups: array:1 [
    0 => "support_tickets.id"
  ]
  +havings: null
  +orders: array:1 [
    0 => array:2 [
      "column" => "last_message"
      "direction" => "desc"
    ]
  ]
  +limit: 21
```
It breaks with a syntax error, because we have the aggregate function in the 'wheres' array, but it should be in the 'havings' array.

Error message:
````Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1111 Invalid use of group function (SQL: select `support_tickets`.*, max(support_ticket_messages.id) as last_message from `support_tickets` inner join `support_ticket_messages` on `support_tickets`.`id` = `support_ticket_messages`.`ticket_id` where (`support_tickets`.`author_id` = 3059 or `support_tickets`.`recipient_id` = 3059) and (max(support_ticket_messages.id) &lt; 307) and `support_tickets`.`deleted_at` is null group by `support_tickets`.`id` order by `last_message` desc limit 21)````

**Comment by driesvints** [comment]
This just seems like a too complicate query to do with cursor based pagination. Please try a support channel if you need help:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
