### ISSUE TITLE
Blade renderer breaks when mixing 2 @php-syntaxes in the same view

### ISSUE THREAD

**Issue by rikvdh** [laravel/framework#45329]
- Laravel Version: 8.83.27
- PHP Version: 7.4.32
- Database Driver & Version: n/a

### Description:

When mixing `@php(..)` and `@php`/`@endphp` later in the view the renderer breaks and gives preference to the @php/endphp pair above the parentheses.

### Steps To Reproduce:

See https://github.com/rikvdh/laravel-broken-blade-view/blob/master/resources/views/welcome.blade.php

In this repo I've created a test-command to render the view (havent set up a webserver etc). But that doesnt matter.
This view is rendered wrong. You expect absolutely no output. But this breaks.

The rendered view:
```php
<?php($hello = 'welcome')
@php
    $hello = 'goodbye';
?>

<?php echo e($hello); ?>

<?php /**PATH /Users/rikvdh/tmp/broken-view/resources/views/welcome.blade.php ENDPATH**/ ?>%                  
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by rikvdh** [comment]
@driesvints this also applies to newer versions..

**Comment by driesvints** [comment]
I advice against mixin it like that.
