### ISSUE TITLE
Query builder keeps on using dropped column

### ISSUE THREAD

**Issue by valentinomariotto** [laravel/framework#45335]
- Laravel Version: 9.41.0
- PHP Version: 8.1.12
- Database Driver & Version: RDS 8.0.mysql_aurora.3.02.0 and MariaDB 8 both

### Description:
I dropped a column from one of my tables using the following migration script: 
```
    public function up()
    {
        Schema::table('payouts', function (Blueprint $table) {
            $table->integer('authorized_by')->unsigned()->nullable()->after('paid_at');
            $table->dropColumn('paid');
        });
    }
```

Since then, I cannot reliably to update() or save() on the model. 
I get the following error:
`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'paid' in 'field list' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:566 `

The update() method never seem to work. The save() method sometimes works. But then it doesn't. 

But of course the column "paid" appears NOWHERE in my model or my scripts. I also tried a full search in every folder, but nothing turned up. Example of a script that fails with the error above:
```
            $payout = Payout::findOrFail( $validated['payout_id'] );
            $payout->update([
                'paid_at'       => $payout->paid_at ?: Carbon::now(),
                'status'        => PayoutStatusEnum::Approved,
                'method'        => PayoutMethodEnum::from($validated['transfer_method']),
                'transaction_id'=> @$validated['transfer_reference'],
                'details'       => @$validated['details'],
                'authorized_by' => auth()->user()->id
            ]);
```

Clearing the cache has no effect.
Why does the query builder still use that column?

### Steps To Reproduce:
I couldn't reproduce the problem on a different table, but the behavior is the same in dev and production.

**Comment by valentinomariotto** [comment]
renaming `App/Models/Payout.php` to something else "solves" the issue for me

but I'd like to keep the original name..

**Comment by ankurk91** [comment]
Are you sure "paid" columns no longer exists in the payouts table?
 Check your mysql schema via mysql terminal.
 +
 If you are using op-cache, make sure to flush it properly.
 
 FYI: Laravel pulls the table columns before firing the update query
 
https://github.com/laravel/framework/blob/a67043763ef330015acc1ffe45ba6302a648389c/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L215

**Comment by driesvints** [comment]
Thanks for helping @ankurk91.

I also often recommend to put any column renames or drops in a separate `Schema::table(` call as that's often the culprit. Anyway, please try a support channel if you need further help or feel free to continue the discussion here:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by valentinomariotto** [comment]
> Are you sure "paid" columns no longer exists in the payouts table? Check your mysql schema via mysql terminal. + If you are using op-cache, make sure to flush it properly.
> 
> FYI: Laravel pulls the table columns before firing the update query
> 
> https://github.com/laravel/framework/blob/a67043763ef330015acc1ffe45ba6302a648389c/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L215

Of course I'm sure. Why would you think I opened an issue here?
Besides, the error says it cannot find the column in the DB. 
And renaming the model solves the issue. And I can see with any DB tool that the column has been dropped.
So the problem is clearly on the laravel side, not on the db side. 
There's some caching problem. 

No, I'm not using OP-cache

**Comment by valentinomariotto** [comment]
> Thanks for helping @ankurk91.
> 
> I also often recommend to put any column renames or drops in a separate `Schema::table(` call as that's often the culprit. Anyway, please try a support channel if you need further help or feel free to continue the discussion here:
> 
> * [Laracasts Forums](https://laracasts.com/discuss)
> * [Laravel.io Forums](https://laravel.io/forum)
> * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> * [Discord](https://discordapp.com/invite/KxwQuKb)
> * [Larachat](https://larachat.co)
> * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Do you mean a separate Schema::table()  call when you use the dropColumn() method?

Maybe that should be documented

**Comment by valentinomariotto** [comment]
I see the issue is closed, congratulations on fixing the bug so quickly

**Comment by ankurk91** [comment]
This feature was introduced a long time ago
https://github.com/laravel/framework/pull/33777

No one has reported such issue so far.

**Comment by valentinomariotto** [comment]
that's not the issue
