### ISSUE TITLE
Blade renderer breaks when mixing 2 @php-syntaxes in the same view

### ISSUE THREAD

**Issue by rikvdh** [laravel/framework#45330]
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: n/a

### Description:

When mixing `@php(..)` and `@php`/`@endphp` later in the view the renderer breaks and gives preference to the @php/endphp pair above the parentheses.

Same issue as just posted, but tested in V9. @driesvints your excuse of "don't use it" is from my perspective not really an excuse. If you have a view of 400+ lines add `@php/@endphp` somewhere in the bottom and you didn't notice that someone else added `@php(..)` somewhere higher up in that same file you pull your hair out on why it doesn't work. Because the errors get quite weird when mixing things with other directives in between.

### Steps To Reproduce:

See https://github.com/rikvdh/laravel-broken-blade-view/blob/v9/resources/views/welcome.blade.php

You expect 'goodbye' as output. But this breaks.

The rendered view:
```php
<?php($hello = 'welcome')
@php
    $hello = 'goodbye';
?>

<?php echo e($hello); ?>

<?php /**PATH /Users/rikvdh/tmp/broken-view/resources/views/welcome.blade.php ENDPATH**/ ?>%                  
```

**Comment by driesvints** [comment]
Don't mix these up.

**Comment by driesvints** [comment]
If you want, feel free to send in a PR that would provide a solution to this.

**Comment by rikvdh** [comment]
It is a bit lame to just 'shut your eyes' for this obvious bug. There is no mention in the documentation on not mixing these kinds of methods, that makes it a bug. Keeping the issue open for someone else to work on or when I get the time to do it if you don't feel like it.

**Comment by tylernathanreed** [comment]
@driesvints 

I'm confused as to why this was closed. According to the documentation (https://laravel.com/docs/9.x/blade#raw-php), both `@php(...)` and `@php ... @endPhp` are supported, and nowhere does it state that you can't use both.

If not being to mix the two is the official stance of Laravel, then it needs to be called out in the documentation. Otherwise, this is a bug, and should be treated as such.

**Comment by driesvints** [comment]
We're not going to spend time looking into this ourselves. You're welcome to send in a PR. This is all easily solved by just using regular PHP tags.

**Comment by rikvdh** [comment]
@driesvints Why dont deprecate @php tags then entirely? If the behavior is buggy and wont be fixed and the answer is 'just using regular PHP tags'.

**Comment by ssddanbrown** [comment]
@rikvdh dries didn't say this won't be fixed, he welcomed a PR. Deprecating would like put an unnecessary change on many existing use-cases. 

Just a note, this thread [was shared on reddit](https://www.reddit.com/r/laravel/comments/zml7iv/thoughts_on_community_atmosphere_and_toneofvoice/) by the OP so may receive additional activity due to this.

**Comment by rikvdh** [comment]
@ssddanbrown From my perspective if something is buggy and you are advised to use something else by maintainers the feature has no reason to exist.

The reason I've shared this on Reddit is not really part of this actual issue. But I'm quite new into the community and am used to a lot of other OS communities and worked a lot of places and program PHP for over 15 years and the way of communicating and closing issues with a 'dont use it' within 1 minute feels very rude to me and something I've never seen before. I understand it in a way, but on the other hand doesnt feel very welcoming to someone trying to contribute to this project.

'yeah you can submit a PR, but idc.' is the tone it arrives at for me.

Feel free to lock this issue for commenting.

**Comment by lewislarsen** [comment]
> Don't mix these up.

Yikes.

**Comment by ericjamesturner** [comment]
rikvdh: "There's ice on the sidewalk"
Dries: "Don't slip! or feel free to fix it..."

I agree with dries. - this is something that isn't a big issue, is likely to affect very few people, and those people can just be more careful, or if those people feel strongly about it, fix the issue for the benefit of the community... or you can get a refund if you'd like

**Comment by rikvdh** [comment]
> rikvdh: "I'd rather go complain on reddit until someone else fixes it"

That is a little bit short sighted. I can fix it myself, but I don't feel very invited to do so. I remove the link to this issue on Reddit to prevent making this personal to anyone. That is not the goal.

**Comment by driesvints** [comment]
Hi all. I'm sorry if you feel I was a bit short sighted in this. My two cents are just that this is an easy fix by using PHP tags. I don't see a big bug here and that's my personal opinion. We're open to PR's welcome bug fixes for this but we won't be spending time on this ourselves hence me closing this. If you don't like the way we want to maintain our projects then I'm sorry but we just do what we feel that works for us.

**Comment by taylorotwell** [comment]
We close issues we don't plan to work on. Google still surfaces closed issues. Anyone can still search closed issues. That's how we work. 👍

**Comment by tylernathanreed** [comment]
@taylorotwell, @driesvints 

If the expectation is that the community has to fix small bugs like this, is there an easy way to find closed, but unresolved, issues like this?

I feel like if I wanted to start contributing, I'd start on issues like these.

**Comment by tylernathanreed** [comment]
@taylorotwell, that sounds fantastic! I'd be happy if something like was done for issues closed in this manner moving forward.
