### ISSUE TITLE
Test: unknown options `--ansi` and `--no-ansi`

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#45340]
- Laravel Version: `9.41.0`, `9.44.0`
- PHP Version: 8.1.13
- Database Driver & Version: ---

### Description:

`--ansi` and `--no-ansi` options do not work when running `php artisan test` command.

![image](https://user-images.githubusercontent.com/10347617/208080274-fc926c76-13f5-435f-8864-7e92926f7fe0.png)

### Steps To Reproduce:

Run the `php artisan test --ansi` or `php artisan test --no-ansi` console command.

```bash
$ php artisan test --ansi
Warning: TTY mode is not supported on Windows platform.
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Unknown option "--ansi"
```

```bash
$ php artisan test --no-ansi
Warning: TTY mode is not supported on Windows platform.
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Unknown option "--no-ansi"
```

In the Jenkins doesn't work too:

![image](https://user-images.githubusercontent.com/10347617/208084586-6d8e7020-19f3-4523-ade0-1cd60bec71ed.png)

**Comment by driesvints** [comment]
Thanks. @nunomaduro do you know what's going on here? Are these forwarded properly?

**Comment by andrey-helldar** [comment]
In comparison, there are no problems with the `migrate` command:

```bash
Helldar@HellPC MINGW64 /d/domains/catalog
$ art migrate --no-ansi

   INFO  Nothing to migrate.


Helldar@HellPC MINGW64 /d/domains/catalog
$ art test --no-ansi
Warning: TTY mode is not supported on Windows platform.
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Unknown option "--no-ansi"
```

**Comment by andrey-helldar** [comment]
I think I know what the problem is: `phpunit` doesn't know about the existence of the `--ansi` and `--no-ansi` options.

And the presence of this indication when executing the `art test --help` command is misleading.

```bash
$ vendor/bin/phpunit --no-ansi
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Unknown option "--no-ansi"
```

**Comment by nunomaduro** [comment]
@andrey-helldar Do you mind of making a pull request to https://github.com/nunomaduro/collision, that does what you have suggested? Please target Collision `v7.0` that is the up coming version of Collision.

**Comment by andrey-helldar** [comment]
@nunomaduro, ok, no problem 🤝
