### ISSUE TITLE
Illuminate\Support\Facades\URL::forceScheme() has no effect on request()->url()

### ISSUE THREAD

**Issue by miloslavkostir** [laravel/framework#45353]
- Laravel Version: 9.44.0
- PHP Version: 8.1.8
- Database Driver & Version: no database

### Description: 
Behind reverse proxy there are all requests through HTTP. 
![behind proxy server](https://cylab.be/storage/blog/122/files/eSf2nkfQqEn8Z06zhAoCQYlIV3KU8r3ZsvHqnxRW.png)
https://cylab.be/blog/122/using-https-over-a-reverse-proxy-in-laravel

And `url()->current()` generates URL `http://example.com` instead of real `https://example.com`. If I use `\Illuminate\Support\Facades\URL::forceScheme('https');` in `AppServiceProvider::boot()` URL generator generates right URL address. But `request()->url()` generates wrong (http) URL:
```php
dump(url()->current());  // https://example.com
dump(request()->url());  // http://example.com
```
The same problem is with method `\Illuminate\Support\Facades\URL::forceRootUrl();`

### Steps To Reproduce:
1. install clean Laravel
2. Add `\Illuminate\Support\Facades\URL::forceScheme('https');` to `App\Providers\AppServiceProvider::boot()`
3. In `routes/web.php` create route:
```php
Route::get('/https-test', function () {
    dump(url()->current());
    dump(request()->url());
});
``` 
4. Ensure you are behind reverse proxy and go to URL `/https-test`  

If you can't try it behind proxy, try force whatever:
```php
\Illuminate\Support\Facades\URL::forceScheme('foo-bar');
dump(url()->current());  // foo-bar://example.com
dump(request()->url());  // http(s)://example.com
```

**Comment by driesvints** [comment]
Did you set the correct url for `APP_URL`?

**Comment by miloslavkostir** [comment]
> Did you set the correct url for `APP_URL`?

Yes, it has no effect. I think the problem is:
- `Illuminate\Http\Request` extends `Symfony\Component\HttpFoundation\Request`
- `Illuminate\Http\Request::url()` uses `Symfony\Component\HttpFoundation\Request::getUri()`
- `getUri()` -> `getSchemeAndHttpHost()` -> `getScheme()` -> `isSecure()`
- see `Symfony\Component\HttpFoundation\Request::isSecure()`. There is trusted proxy settings. I can't use trusted proxy because of Apache module `mod_remoteip`

Maybe `Illuminate\Http\Request` should override `isSecure()` method and take into account `\Illuminate\Routing\UrlGenerator::$forceScheme`?

**Comment by driesvints** [comment]
Seems like Taylor gave a solution in the linked PR.
