### ISSUE TITLE
[9.44.0] ->before() does not work in migrations

### ISSUE THREAD

**Issue by lk77** [laravel/framework#45370]
Hello

- Laravel Version: 9.44.0
- PHP Version: 8.1.10
- Database Driver & Version: Mariadb 10

### Description:

`->before()` is not working when doing `php artisan migrate`, the field is put at the end of the table and not before the specified field

When using --pretend the query does not seems to contain anything related to before : 

--pretend using ->before()
```
 alter table `table_name` add `another_field` tinyint(1) not null default '0' comment 'should be first'
```
--pretend using ->afete()
```
alter table `table_name` add `another_field` tinyint(1) not null default '0' comment 'should be first' after `a_field`
```

### Steps To Reproduce:

1 / Create a table with a field in a migration
```
Schema::create('table_name', function (Blueprint $table) {
    $table->boolean('a_field')->default(false)->comment('should be second');
});
```
2 / Add a field to that table in a second migration using ->before(), so that second field should end up before the first one
```
Schema::table('table_name', function (Blueprint $table) {
    $table->boolean('another_field')->default(false)->before('a_field')->comment('should be first');
});
```
3 / See that fields are in wrong order in the table, ->before() seems to be doing nothing

![Screenshot from 2022-12-20 10-55-24](https://user-images.githubusercontent.com/9606882/208641069-c935449e-a9dd-407f-99d5-47658c3edaf2.png)

Repo :

https://github.com/lk77/laravel-migration-before

**Comment by driesvints** [comment]
`before` doesn't seems to be documented: https://laravel.com/docs/9.x/migrations. It's also not present on the Blueprint class so unsure if we even support that?

**Comment by lk77** [comment]
I didn't check if that method actually exist, i assumed it was since it was not triggering any exception
