### ISSUE TITLE
Problem directive @endphp after upgrade version to 9.45

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/framework#45388]
- Laravel Version: 9.45.0
- PHP Version: 8.1.13
- Database Driver & Version: MYSQL 5.7

### Description:
After upgrade version 9.44 to 9.45 my rendere view script have problem. This result screenshot

![image](https://user-images.githubusercontent.com/5731295/208987688-f1e576e0-a997-4071-be4b-2755cbdafd13.png)

If execute downgrade to versione 9.4 is OK

![image](https://user-images.githubusercontent.com/5731295/208987939-1e9d81b2-3415-4036-b1a5-865780d2389b.png)

This is example code

```
@php (
    $classes = [
        'admin-font-mono', // Font weight
    ])
@endphp

<span class="{{ eHtml::classes($classes) }}">{!! $value !!}</span>
```

**Comment by taylorotwell** [comment]
Reverted problem PR.
