### ISSUE TITLE
Laravel 9 route:list trimmed output

### ISSUE THREAD

**Issue by katzda** [laravel/framework#45384]
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: irrelevant

### Description:
Ever since I upgraded to laravel 9, the route:list command outputs routes in a trimmed format. I need it the way it was before.

![image](https://user-images.githubusercontent.com/12850106/208952827-2a025924-799f-47a8-bdcc-1689a3cfc13e.png)

If I filter by route name, the line is still trimmed:

![image](https://user-images.githubusercontent.com/12850106/208952087-ce8a2c9d-ee2e-4e08-9d5f-9d86a789e0c7.png)

**Comment by nunomaduro** [comment]
You can use the `-v` option to display the entire information.
