### ISSUE TITLE
Laravel Queue Job Chaining Terminates on Queue Restart

### ISSUE THREAD

**Issue by Monilsh** [laravel/framework#45409]
- Laravel Version: 8.0.0
- PHP Version: 8.0
- Database Driver & Version: Redis

### Description:
This bug originated in the Job chaining (https://laravel.com/docs/8.x/queues#job-chaining) feature present in laravel for version 8.0 and above. So whenever we dispatch a job chain, the worker starts executing the jobs sequentially. But as soon as we restart the queue forcefully (Just to test things out), the chained jobs do not execute the remaining jobs present in the chain and it moves the job to failed job table after the timeout value is reached. 

### GitHub Project Link:
 https://github.com/Monilsh/Laravel-Queue-Job-Chain

### Steps To Reproduce:
To reproduce the problem we have exposed a API `{host}/chainJobs` (https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/routes/web.php), which takes n number of names and dispatches a chain of Jobs called `JobChain`(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/app/Jobs/JobChain.php) which displays name and sleeps for 5 second to add delay between jobs. 

We also have exposed another API `{host}/getName`(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/routes/web.php) which dispatch a job `PrintName`(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/app/Jobs/PrintName.php) and is just used to display or print the name passed. 

- Start the php server using the command `php artisan server`
- Start the worker using the command `php artisan queue:work`
- Dispatch the JobChain event by hiting the following API `{host}/chainJobs`
- Also dispatch the `getName` Job by hitting the following API `{host}/getName`
- Quickly restart the worker(terminate the worker and again start it).
- The results would be as follows the chained job would not continue to execute after restart, and it would fail after the timeout value is reached.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by Monilsh** [comment]
Thanks for the help, will try to upgrade the laravel version and check
