### ISSUE TITLE
paginate method is ignoring order by if query has group by and having

### ISSUE THREAD

**Issue by Sherlockboy** [laravel/framework#45400]
- Laravel Version: 9.45.1
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8

### Description:
Main problem here, although it is mentioned inside `protected function runPaginationCountQuery($columns = ['*'])` method of Query Builder class that if there is grouping or having then it should not ignore orderby. But, now `paginate` method is ignoring it.

### Steps To Reproduce:
Example query:
```
User::query()
    ->groupBy('id')
    ->havingRaw('TIMESTAMPDIFF(minute, created_at, updated_at) = 1')
    ->latest()
    ->paginate(100));
```

This results in following two queries:
```
select
  *
from
  `users`
group by
  `id`
having
  TIMESTAMPDIFF(minute, created_at, updated_at) = 1
order by
  `created_at` desc
limit
  100 offset 0
```
```
select
  count(*) as aggregate
from
  (
    select
      *
    from
      `users`
    group by
      `id`
    having
      TIMESTAMPDIFF(minute, created_at, updated_at) = 1
  ) as `aggregate_table`
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
