### ISSUE TITLE
Wrong row id in response of Create func of modal.

### ISSUE THREAD

**Issue by 4nkitd** [laravel/framework#45417]
- Laravel Version: 9.2
- PHP Version: 8.1.10
- Database Driver & Version:

### Description:
I was testing an application to, so to keep track of things. I added a table and created a event listener to log all request and quires in that DB. `I was not allowed to use telescope`. it was working fine for normal use. when we did a load testing it started giving us id of logging table, when a create query is run on a diff modal.

### Steps To Reproduce:

- Create a Model to log all requests and queries. 
- Do a load test

### Note 
every time I just cleared the database and run fresh migrations the issue was resolves for some time. the issue was only with id every other datapoint was correct.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
