### ISSUE TITLE
Increment on a field with custom cast checks for method on one class but calls another

### ISSUE THREAD

**Issue by Sjord** [laravel/framework#45415]
- Laravel Version: illuminate/database v8.83.25
- PHP Version: 7.4.33
- Database Driver & Version: MySQL PDO

### Description:

I'm calling `increment` on a field that has a custom cast. The Laravel Model class checks whether a custom `increment` implementation exists. However, it checks on one class and then performs the call on another class.

### Steps To Reproduce:

I have a `Member` model with an `amount` field, which is of type `Euro`, and casting is provided by `EuroCaster`. The problem is that calling `increment` checks for `Euro->increment`, and if that exists calls `EuroCaster->increment`.

```
final class Euro implements Castable {
    public static function castUsing(array $arguments) {
        return EuroCaster::class;
    }
}

final class Member extends Model {
    protected $casts = [
        'amount' => Euro::class,
    ];

    public function incrementAmount(Euro $amount) {
        $this->increment('amount', $amount->toDecimal());
    }
}
```

The problem is in [Model.incrementOrDecrement](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Eloquent/Model.php#L853-L855):

```
        $this->{$column} = $this->isClassDeviable($column)
            ? $this->deviateClassCastableAttribute($method, $column, $amount)
            : $this->{$column} + ($method === 'increment' ? $amount : $amount * -1);
```

The last line won't work, since adding `Euro` with `+` isn't possible. Our column should be "class deviable". The function [`isClassDeviable`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1613-L1618) checks whether the methods exist:

```
    protected function isClassDeviable($key)
    {
        return $this->isClassCastable($key) &&
            method_exists($castType = $this->parseCasterClass($this->getCasts()[$key]), 'increment') &&
            method_exists($castType, 'decrement');
    }
```

It checks this on the `Euro` class. If these methods exist, [`deviateClassCastableAttribute`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L882-L887) is called. This calls [`resolveCasterClass`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1641), which actually checks whether the class implements Castable and calls `castUsing` to get `EuroCaster`.

So it checks for `Euro->increment`, and then calls `EuroCaster->increment`. I believe this is a bug.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by Sjord** [comment]
Thanks, I created #45418
