### ISSUE TITLE
Laravel Queue Job Chaining Terminates on Queue Restart

### ISSUE THREAD

**Issue by Monilsh** [laravel/framework#45426]
- Laravel Version: 9.40.1
- PHP Version: 8.2.0
- Database Driver & Version: Redis

### Description:
This bug originated in the Job chaining (https://laravel.com/docs/8.x/queues#job-chaining) feature present in laravel for version 8.0 and above. So whenever we dispatch a job chain, the worker starts executing the jobs sequentially. But as soon as we restart the queue forcefully (Just to test things out), the chained jobs do not execute the remaining jobs present in the chain and it moves the job to failed job table after the job's timeout value is reached.

### GitHub Project Link:
https://github.com/Monilsh/Laravel-Queue-Job-Chain

### Steps To Reproduce:
To reproduce the problem we have exposed an API {host}/chainJobs (https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/routes/web.php), which takes n number of names and dispatches a chain of Jobs called JobChain(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/app/Jobs/JobChain.php) which displays name and sleeps for 5 seconds to add a delay between jobs.

We also have exposed another API {host}/getName(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/routes/web.php) which dispatches a job PrintName(https://github.com/Monilsh/Laravel-Queue-Job-Chain/blob/master/app/Jobs/PrintName.php) and is just used to display or print the name passed.

- Start the PHP server using the command PHP artisan server
- Start the worker using the command PHP artisan queue:work
- Dispatch the JobChain event by hitting the following API {host}/chainJobs
- Also, dispatch the getName Job by hitting the following API {host}/getName
- Quickly restart the worker(terminate the worker and again start it).
- The results would be as follows the chained job would not continue to execute after the restart, and it would fail after the timeout value is reached.

**Comment by jaouadk** [comment]
Any update on this one?

- JJineyzz

**Comment by driesvints** [comment]
This is the expected behavior. You should wait and let any jobs in the chain finish before quitting the process.
