### ISSUE TITLE
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

### ISSUE THREAD

**Issue by rchitector** [laravel/framework#45438]
- Laravel Version: 9.45.1
- PHP Version: 8.2.0
- Database Driver & Version: MySQL 8.0.3

### Description:
In my controller I'm just trying to get the table column type, but I got an `Doctrine\DBAL\Exception` exception:

`Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.`

### Steps To Reproduce:

```
$table_name = 'agencies';
$has = Schema::hasColumn($table_name, 'id');
dump($has); // <-- "true" here
$type = Schema::getColumnType($table_name, 'id'); // <-- Doctrine\DBAL\Exception here
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
