### ISSUE TITLE
id and uuid can not be both used at same time

### ISSUE THREAD

**Issue by dotZoki** [laravel/framework#45431]
- Laravel Version: 9.45.1
- PHP Version: 8.1.11

### Description:

I want to have a table that uses numeric id as primary key but also want for each row to have uuid. Having both and using `HasUuids` trait in the model causes issue as it is trying to insert uuid into id field.

Running: `artisan migrate:fresh --seed`  casues

```
 SQLSTATE[01000]: Warning: 1265 Data truncated for column 'id' at row 1 (SQL: insert into `profiles` (`bio`, `id`, `updated_at`, `created_at`) values (Some bio info, 98146819-14d5-4dfe-8d04-7cec07c2d0d8, 2022-12-27 09:42:12, 2022-12-27 09:42:12))
```

### Steps To Reproduce:
Migration
```
Schema::create('profiles', function (Blueprint $table) {
    $table->id();
    $table->uuid();
    $table->text('bio');
    $table->timestamps();
});
```

Profiles factory
```
return [
    'bio' => "Some bio info",
];
```

Profile model uses `HasUuids` trait.

**Comment by driesvints** [comment]
You can customize this behavior by overwriting `uniqueIds`. See https://laravel.com/docs/9.x/eloquent#uuid-and-ulid-keys

**Comment by dotZoki** [comment]
OK, thanks. 

Just a thought: Might it be better that implementation of `uniqueIds` uses  name `uuid` as default since signature in migration for uuid field is `public function uuid($column = 'uuid')` and if you change it then you overwrite it?
