### ISSUE TITLE
withCount and Pagination overrides paginations `columns` part

### ISSUE THREAD

**Issue by iquad** [laravel/framework#45449]
- Laravel Version: 9.43.0
- PHP Version: 8.2.0
- Database Driver & Version: PostgreSQL 14.6

### Description:
When using `withCount` with pagination, it overrides paginations columns part.

```php
\App\Models\User::paginate(10, ['id', 'email']);
```

returns
```sql
select
  "id"
from
  "users"
limit
  10 offset 0
```
but
```php
\App\Models\User::withCount('transportations')->paginate(10, ['id', 'email']);
```
returns
```sql
select
  "users".*,
  (
    select
      count(*)
    from
      "transportations"
    where
      "users"."id" = "transportations"."user_id"
      and "transportations"."deleted_at" is null
  ) as "transportations_count"
from
  "users"
limit
  10 offset 0
```

### Steps To Reproduce:
1. Create new project.
2. Create relationship.
3. Query with `withCount`

**Comment by driesvints** [comment]
withCount can't be combined with this.

**Comment by iquad** [comment]
Can't because eloquent not capable or any particular reason? 🤔
