### ISSUE TITLE
Changing view dir when compiling templates leads to unexpected results

### ISSUE THREAD

**Issue by douglassdavis** [laravel/framework#45440]
Please see function below  

Intended input: a view directory/path and a template name, e.g. "standard", template vars  

Intended output: the rendered template.  

Current problem: If called with the code below:

```
$html_one = get_html($dir_one, 'standard', []);
$html_two = get_html($dir_two, 'standard', []);
```
Both $html_one and $html_two will contain the rendered standard.blade.php template from $dir_one. Laravel will ignore the standard.blade.php template in $dir_two.  I think previously compiled templates should only be used when the path of the uncompiled template matches the path of the uncompiled template that the compiled template was compiled from.  Is that incorrect?

    
```

     function get_html($dir, $templateName, $templateVars)
     {
         $viewFinder = View::getFinder();

         $oldPaths = $viewFinder->getPaths();

         $viewFinder->setPaths( [$dir]);

         $newHTML = view($templateName, $templateVars)->render();

         $viewFinder->setPaths($oldPaths);

         return $newHTML;                  
     }
```

**Comment by driesvints** [comment]
I don't think I see a bug here. If you want to try to change anything here feel free to attempt a pr 👍

**Comment by douglassdavis** [comment]
Ok, I'll give it a try

**Comment by douglassdavis** [comment]
Note for anyone with the same problem:  I found out that after calling setPath() you have to call flush() or it will ignore the paths set when a template has the same name as a previously viewed template.    Apparently this is the expected behavior, but it makes it look like setPath() isn't working.  Perhaps it should be documented better that a call to flush() is necessary after a call to setPath()???  I don't know, but wanted to comment just in case.
