### ISSUE TITLE
Decimal loses precision because of internal cast to float

### ISSUE THREAD

**Issue by Sjord** [laravel/framework#45454]
- Laravel Version: illuminate/database 9.45
- PHP Version: PHP 8.2.0
- Database Driver & Version: none

### Description:

When specifying a field to be cast as decimal, it is still internally converted to float by the [call to `number_format`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1319-L1322). This loses precision.

### Steps To Reproduce:

```
<?php

require('vendor/autoload.php');

use Illuminate\Database\Eloquent\Model;

final class Member extends Model {
    public $timestamps = false;
    protected $casts = [
        'amount' => 'decimal:20',
    ];
}

$member = new Member();
$member->amount = '0.1';
var_dump($member->amount);
```

Outputs:
```
string(22) "0.10000000000000000555"
```

Expected:

```
string(22) "0.10000000000000000000"
```
```

**Comment by timacdonald** [comment]
I've opened a PR to start addressing this. We can continue the conversation in the PR instead.
