### ISSUE TITLE
PHPRedis mget error, keys empty array

### ISSUE THREAD

**Issue by iDGE90** [laravel/framework#45469]
Laravel Version .................................................................. 9.21.6
PHP Version ........................................................................ 8.1.0
Composer Version ............................................................ 2.4.4
Redis Version ...................................................................... 7.0.5

Using latest https://pecl.php.net/package/redis/5.3.7/windows

Using redis cache `many` with an empty array throws an error: 

```
local.ERROR: array_map(): Argument #2 ($array) must be of type array, bool given {"userId":1,"exception":"[object] (TypeError(code: 0): array_map(): Argument #2 ($array) must be of type array, bool given at C:\\Users\\Igor\\Projects\\homie\\api\\vendor\\laravel\\framework\\src\\Illuminate\\Redis\\Connections\\PhpRedisConnection.php:70)
```
The code in question returns `false`:
https://github.com/laravel/framework/blob/8209afde1d14d4342ecb1457b7e6ee2ce51caee1/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L70

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
