### ISSUE TITLE
Annotation difference between interface and implementation

### ISSUE THREAD

**Issue by araeuchle** [laravel/framework#45480]
- Laravel Version: 9.42.2
- PHP Version: 8.1.12
- Database Driver & Version: MySQL 5.7

### Description:
We were using a Filesystem interface to store files in S3 and using the FilesystemAdapter implementiation with that. 
So when we want to store a file we call disk->put to store it. 

 $disk = Storage::disk($diskName);
 return $disk->put($filepath, $content);

What we get here is, an error from phpstan telling us that we want to return only bool but are returning bool|string. 
This is because in the Filesystem interface the annotation sais: @return bool and in the FilesystemAdapter it is @return bool|string which is inconsistent. 

### Steps To Reproduce:

1. Make a controller with an upload action
2. Create a disk:  $disk = Storage::disk($diskName);
3. put a file to the disk: $disk->put($filepath, $content);

**Comment by driesvints** [comment]
I don't really see a bug here. Your app will work just fine without phpstan. If you want to change a docblock feel free to attempt a PR thanks.
