### ISSUE TITLE
HTTP request method gets changed

### ISSUE THREAD

**Issue by sn-sharma** [laravel/framework#45496]
- Laravel Version: ^9.11
- PHP Version: 8.1
- Database Driver & Version: 10.6.11-MariaDB - MariaDB Server

### Description:
We are getting a weird issue in the dev server. When we are trying to save data from a text editor (e.g. CKEditor), if the text editor includes a normal text like `<p>This is <span>test</span></p>` then it will save the data in the database and everything working fine. 
But if we add a style to the text like `<p style="color:red;">This is <span>test</span></p>` then the server will throw an error 405 Method not allowed. 
Means if we are adding any style the HTTP request method gets changed anyhow.

![image](https://user-images.githubusercontent.com/71202563/210302110-b2b463e3-93f6-46fc-8308-6533b1cc7f44.png)
![image](https://user-images.githubusercontent.com/71202563/210302131-86b4d662-10a7-4de0-9128-6d731d293b54.png)

### Steps To Reproduce:
It is only happening on dev server working fine in local server.

**Comment by driesvints** [comment]
If it's a different behavior between systems then I don't think the issue relies with Laravel. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
