### ISSUE TITLE
[9.x] Validation rule `Rule::exists` does not support `orWhere` clauses.

### ISSUE THREAD

**Issue by aneesdev** [laravel/framework#45508]
- Laravel Version: 9.45.1
- PHP Version: 8.2.0
- Database Driver & Version: MariaDB 10.6.11

### Description:

Hi,

When using the validation rule `Rule::exists` custom where. it seems that it doesn't support `orWhere` clauses. it throws a database error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'salesman_uuid' in 'where clause`

BTW I'm using a form request class.

**See below:**

![image](https://user-images.githubusercontent.com/92947803/210558102-74d9cf7b-416a-4cc2-81ee-50bb97f2b9ed.png)

### Steps To Reproduce:

1. Make a new laravel 9 project.
2. Create a form request class.
3. Add a validation rule `Rule::exists` with multiple where clauses.

**Comment by timacdonald** [comment]
I'm not sure this is an issue with the orWhere clauses. It looks like this issue is the `users` table doesn't have a `salesman_uuid` column and the `exists` rule is using the input key as the column key.

To achieve what you are trying to do, I would recommend using two Rule::exists() calls:

```php
'salesman_uuid' => [
    // ...
    Rule::exists('users', 'uuid'),
    Rule::exists('users', 'direct_uuid'),
];
```

or you could try the following...

```php
'salesman_uuid' => [
    // ...
    Rule::exists('users', 'uuid')->where(fn ($q) => $q->orWhere('direct_uuid', $salesman_uuid)),
];
```

but I'm unsure if the orWhere query will be scoped properly.

**Comment by aneesdev** [comment]
> ```
>     Rule::exists('users', 'uuid'),
>     Rule::exists('users', 'direct_uuid'),
> ```

@timacdonald Sorry but both of these 2 solutions didn't work. it still gives `unknown column salesman_uuid`

**Comment by aneesdev** [comment]
@timacdonald I suppose that the `Rule::exists` should be me the eloquent builder instance. so that I can do any query I want.

**Comment by aneesdev** [comment]
> Can you show me the exact code you used for this version:
> 
> ```
> 'salesman_uuid' => [
>     // ...
>     Rule::exists('users', 'uuid'),
>     Rule::exists('users', 'direct_uuid'),
> ];
> ```

This also doesn't work because the first `Rule::exists('users', 'uuid')` throws the error. and so the `Rule::exists('users', 'direct_uuid')` didn't even ran.

**Comment by timacdonald** [comment]
ahh, yes of course. That won't work.

I would recommend using an `after` validation hook and performing the check manually as the exists rule doesn't support multiple columns

See: https://laravel.com/docs/9.x/validation#adding-after-hooks-to-form-requests

**Comment by aneesdev** [comment]
@timacdonald 

Well, I have used closure-based validation.

![image](https://user-images.githubusercontent.com/92947803/210904914-e79e8796-b266-4ef9-ae4c-b5d0da9bc32d.png)

**Comment by timacdonald** [comment]
ayyyy! nice one. Even better!
