### ISSUE TITLE
Storage::path not found but can be used

### ISSUE THREAD

**Issue by jyxjjj** [laravel/framework#45514]
- Laravel Version: 9.46.0
- PHP Version: 8.2.0
- Database Driver & Version: N/A

### Description:

Here i found [a file diff of a commit](https://github.com/laravel/framework/commit/5d37c0f6012fa25631ddc92df8e8f11c8cba7b01#diff-19919d76a5cf86ca98852bf91d9e121ef58e81e93512059b94d54c4d6c0a9d90)
That removed Storage::path

The Doc said: [Storage::path](https://laravel.com/docs/9.x/filesystem#file-paths) to get the path string.

It is conflicted.

**Comment by jyxjjj** [comment]
And #44851 said this.

**Comment by jyxjjj** [comment]
Is that a merge issue or a provider removal?

**Comment by jyxjjj** [comment]
I think it is still [here](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Filesystem/FilesystemAdapter.php#L245)

**Comment by timacdonald** [comment]
I've just opened #45517, which should fix this for you.
