### ISSUE TITLE
Inconsistent behavior with setAttribute() and custom mutators

### ISSUE THREAD

**Issue by adamthehutt** [laravel/framework#45537]
- Laravel Version: 9.44.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8

### Description:

There is some inconsistent behavior with Eloquent's ```setAttribute()``` method depending on whether or not a custom mutator has been defined. 

If there is no custom mutator, then ```setAttribute()``` returns the model itself. This is useful for chaining, as in:

```php

$model = new Car;
$model
    ->setAttribute("color", "red")
    ->setAttribute("make", "Corvette");
```

But when a mutator has been defined using the Attribute::make() approach, then the setAttribute method seems to always return null.

### Steps To Reproduce:

Here's a simple Pest test:

```php
class TestModel extends Model
{
    public function foo(): Attribute
    {
        return Attribute::make(
            set: fn ($val) => $val
        );
    }
}

it ("returns the model", function () {
    $model = new TestModel();
    $subject1 = $model->setAttribute("bar", "abc123");
    $subject2 = $model->setAttribute("foo", "abc123");

    expect($subject1)->toBe($model)
        ->and($subject2)->toBe($model);
});

```

With the above test, the first expectation passes but the second fails.

**Comment by driesvints** [comment]
Hey @adamthehutt. Thanks for sending this in. I've sent a fix for this: https://github.com/laravel/framework/pull/45539
