### ISSUE TITLE
The `size/max/min` validation rules perform incorrect validation with `decimal` rule

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#45532]
- Laravel Version: 9.26.1
- PHP Version: 8.1.13
- Database Driver & Version: Postgres 14

### Description:
Hello,

The docs for the `size` validation rule show that when used with `integer` or `numeric` it validates against an integer value:

> For numeric data, value corresponds to a given integer value (the attribute must also have the numeric or integer rule).

However, when `size` used with the new `decimal` rule it is using string validation (that is, number of characters). The expected behaviour is that `size/min/max` would be the same with `decimal` as with `numeric`.

### Steps To Reproduce:

```
Validator::make(['decimal' => 250.0], [
  'decimal' => ['required', 'decimal:0,2', 'max:200'], // passes
  'decimal' => ['required', 'numeric', 'max:200'], // fails
  ])->validate()
```

**Comment by driesvints** [comment]
Will need to be added here: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Validation/Validator.php#L277

Can you send in a PR?

**Comment by mikdanjey** [comment]
Can you try latest version of Laravel

Today's latest version is 9.46.
