### ISSUE TITLE
@json directive doesn't render with the correct $echoFormat

### ISSUE THREAD

**Issue by thomas-alrek** [laravel/framework#45542]
- Laravel Version: 9.46.0
- PHP Version: 8.1.10
- Database Driver & Version: mysql 8.0.30

### Description:

The BladeCompiler class has the method `withDoubleEncoding`. This method configures the `$echoFormat` variable in such a way that subsequent calls to `htmlspecialchars` from the `e` echo helper method used by Blade, are called with the `$double_encode` argument set to `true`.

This works fine when using the regular echo syntax of Blade `{{ json_encode($data) }}`, however it doesn't apply at all when using the json directive `@json($data)`.

### Steps To Reproduce:

Let's say we have the given example data `$data`:

```php
$data = ['foo' => 'bar'];
```

And the following view that get's passed the `$data` variable:

```html
<some-vue-component v-model="@json($data)"></some-vue-component />
{{-- vs --}}
<some-vue-component v-model="{{ json_encode($data) }}"></some-vue-component />
```

I would expect both to produce the same output. However, the compiled output looks like the following:

```html
<some-vue-component v-model="{"foo":"bar"}"></some-vue-component />

<some-vue-component v-model="{&quot;foo&quot;:&quot;bar&quot;}"></some-vue-component />
```

**Comment by thomas-alrek** [comment]
I have proposed a fix in my PR #45543

**Comment by driesvints** [comment]
Can't you just use:

`{!! json_encode($data) !!}`

**Comment by thomas-alrek** [comment]
@driesvints I figured since Blade already has the convenience `@json` directive, it would make sense that it also respected the `echoFormat` from the BladeCompiler, since it's already acting as a shorthand for doing `{{ json_encode($data) }}`.

This would also make the `@json` directive more consistent with the echo syntax of Blade.

One use-case for using the double encoding option is with Vue components.

It would make the Blade code more readable in my opinion:

Today you would have to do:

```html
<some-vue-component
    :foo="{!! json_encode($foo) !!}"
    :bar="{!! json_encode($bar) !!}"
>
    Hello World!
</ some-vue-component>
```

Versus:

```html
<some-vue-component
    :foo="@json($foo)"
    :bar="@json($bar)"
>
    Hello World!
</ some-vue-component>
```

**Comment by driesvints** [comment]
We actually don't support using directives within component tags at this time: I suggest to use the `{!! !!}` tags.

<img width="729" alt="Screenshot 2023-01-06 at 12 29 16" src="https://user-images.githubusercontent.com/594614/211003988-8162d875-9c29-4985-b96b-377956147f2b.png">

**Comment by thomas-alrek** [comment]
@driesvints this example isn't using a Blade component tag. The specific example was for a Vue component rendered through a Blade view.

**Comment by driesvints** [comment]
I see. But it’s the same. The compiler cannot handle this atm.
