### ISSUE TITLE
@json directive doesn't render with the correct $echoFormat

### ISSUE THREAD

**Issue by thomas-alrek** [laravel/framework#45541]
- Laravel Version: 8.83.27
- PHP Version: 7.4.30
- Database Driver & Version: mysql 8.0.30

### Description:

The BladeCompiler class has the method `withDoubleEncoding`. This method configures the `$echoFormat` variable in such a way that subsequent calls to `htmlspecialchars` from the `e` echo helper method used by Blade, are called with the `$double_encode` argument set to `true`.

This works fine when using the regular echo syntax of Blade `{{ json_encode($data) }}`, however it doesn't apply at all when using the json directive `@json($data)`.

### Steps To Reproduce:

Let's say we have the given example data `$data`:

```php
$data = ['foo' => 'bar'];
```

And the following view that get's passed the `$data` variable:

```html
<some-vue-component v-model="@json($data)"></some-vue-component />
{{-- vs --}}
<some-vue-component v-model="{{ json_encode($data) }}"></some-vue-component />
```

I would expect both to produce the same output. However, the compiled output looks like the following:

```html
<some-vue-component v-model="{"foo":"bar"}"></some-vue-component />

<some-vue-component v-model="{&quot;foo&quot;:&quot;bar&quot;}"></some-vue-component />
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by thomas-alrek** [comment]
I can confirm this issue is still present in the latest version of Laravel.

The `@json` Blade directive is implemented in the following file: https://github.com/laravel/framework/blob/9.x/src/Illuminate/View/Compilers/Concerns/CompilesJson.php#L28 which hasn't seen any changes in the past 5 years.

If you want, I can propose a fix for this.
