### ISSUE TITLE
Delete symlink  not work in Windows

### ISSUE THREAD

**Issue by pemudakoding** [laravel/framework#45579]
- Laravel Version: 8.83.27
- PHP Version: 8.0.0
- Database Driver & Version: MYSQL 8 

### Description:
In some case we can't enforce developer to use WSL in windows in some reason so they can still developing Laravel project with pure Windows environtment. the actual problem is when play around with symlink, Windows and Linux has different way to treat the symlink I guess. 

let me give you an example.
when you run  `php artisan storage:link --force` it won't work and still give an error message

![image](https://user-images.githubusercontent.com/62993054/211476703-259dbb0a-df4d-4be2-896d-84ba51440950.png)

why it isn't work? see image below

![image](https://user-images.githubusercontent.com/62993054/211476984-11f62a84-96fe-4f70-a9d6-7eae89d2b78c.png)

```php
if (is_link($link)) {
    $this->laravel->make('files')->delete($link);
}
```
that conditional  always return false because windows treat the symlink as directory (shorcut) so that's why that function cannot see it's a symlink or not, what if just delete with conditional and directly delete? it won't work too, because delete() purpose remove file not directory. it also happens outside storage:link command.

i've feature that need make symlink oftenly.

![image](https://user-images.githubusercontent.com/62993054/211477803-d3349c87-d459-4179-84b2-3f44ac444ed2.png)

i need to make 2 lines to delete an symlink in different os, what iff it happen it another files i need to make 2 lines over and over again, definitely it for development purpose, because we'll deploy the project in Linux env, but it'll make  unknown critical error when the developer using Windows and deploy to Linux.

I think to make unlink() method to filesystem class purpose unlink the symlink only.
#### First way
1. run php artisan storage:link --force in windows it won't work

#### Second way
1. Create symlink using filesystem link() in windows
2. and delete() with filesystem

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by pemudakoding** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!

Hi i tested with my latest project using Laravel 9. still facing the same issue.
![image](https://user-images.githubusercontent.com/62993054/211551193-8deea1e0-234c-4eb8-a8d9-2c463c7f1491.png)
