### ISSUE TITLE
Make Model Folder allice different Model name the same

### ISSUE THREAD

**Issue by RasimAghayev** [laravel/framework#45573]
- Laravel Version: <5.6
- PHP Version: >5.7

### Description:

Hello. 

I call all the functionality under the model. Which has been used since Laravel 5.6.
```shell
php artisan makeImodel Front\Home -a
```

This command creates the following files.

```shell
INFO  Model [...\app/Models/Front/Home.php] created successfully.  

INFO  Factory [...\database/factories/Front/HomeFactory.php] created successfully.  

INFO  Migration [...\database\migrations/2023_01_08_193234_create_homes_table.php] created successfully.  

INFO  Seeder [...\database/seeders/HomeSeeder.php] created successfully.  

INFO  Request [...\app/Http/Requests/StoreHomeRequest.php] created successfully.  

INFO  Controller [...\app/Http/Controllers/HomeController.php] created successfully.

INFO  Policy [...\app/Policies/HomePolicy.php] created successfully.
```

I apply the same command for another folder.

```shell
php artisan makeImodel Admin\Home -a
```
This command creates the following files.
```shell
INFO  Model [...\app/Models/Admin/Home.php] created successfully.

INFO  Factory [...\database/factories/Admin/HomeFactory.php] created successfully.

INFO  Migration [...\database\migrations/2023_01_08_193241_create_homes_table.php] created successfully.

ERROR  Seeder already exists.

ERROR  Controller already exists.

ERROR  Policy already exists.
```

The problem is that since the name of the migration file is newly created, both data will work there.
If our project is old, the same Append will delete the old data and create a new one.

```shell
[info] INFO  Migration [...\database\migrations/2023_01_08_193234_create_homes_table.php] created successfully.  
[bug] INFO  Migration [...\database\migrations/2023_01_08_193241_create_homes_table.php] created successfully.
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
