### ISSUE TITLE
Benchmark wrong measure over 20000 iteration

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#45587]
- Laravel Version: 9.46
- PHP Version: 8.1

### Description:
The following code took over 2 seconds:

```php
Benchmark::measure(fn() => data_get([], 'a.b.c'), 20000)
```

But it returns: 

```
0.0011045550000002
```

**Comment by nunomaduro** [comment]
The reason for this is that the measurement setup utilizing `20000` iterations is both time- and memory-intensive. However, the resulting average speed for that specific closure is `0.0011045550000002`.
