### ISSUE TITLE
Eloquent Model create() method doesn't allow array for JSON columns

### ISSUE THREAD

**Issue by kusiormarcin** [laravel/framework#45591]
### Versions

- Laravel Framework 9.44.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0 (sail)

### Description

When you try to create a model using its create() method, it won't allow you to add an array field.

It will however work if you are using this way:
$model->field = ['property' => 'value'];
$model->save();

### Steps to reproduce

1. Create a model with JSON type field.
2. Set model's $guarded = []
3. Set JSON field to be casted as array in model's $casts property
3. Try to create a model using Model::create(['field-name' => ['property' => 'key']])

**Comment by driesvints** [comment]
This is intentional as it allows a mass assignment vulnerability.
