### ISSUE TITLE
Using dynamic where with column name, and named function arguments don't play well with each other.

### ISSUE THREAD

**Issue by Ham3D** [laravel/framework#45595]
- Laravel Version: 9.42.2
- PHP Version: 8.1.13

### Description:
when using both magic where with a column name and PHP's new feature, named arguments they are not playing well.

### Steps To Reproduce:

we have a model named 

`User`

this model has a `name` field

try : 

`$user = User::whereName(value:'Ham3d')->first();`

this throws unrelated errors.

**Comment by driesvints** [comment]
This is indeed not supported. This is a dynamic method call where named parameters cannot be used.
