### ISSUE TITLE
[9.x] Database session driver `SESSION_DRIVER=database` flash messages doesn't work in `try/catch` block.

### ISSUE THREAD

**Issue by aneesdev** [laravel/framework#45597]
- Laravel Version: 9.30.0
- PHP Version: 8.1.0
- Database Driver & Version: MariaDB 10.6.11
- Session Driver: `database`

### Description:

Hi, 

It seems that when the `SESSION_DRIVER` is set to `database`. The session flash message doesn't work when using in `try/catch` block.

```php
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $uuid)
    {
        $wallet = Wallet::where('uuid', $uuid)
            ->firstOrFail();

        $request->validate([
            'code' => [
                'required',
                'string'
            ]
        ]);

        try {
            $this->voucherRedeemingService
            ->redeem($wallet, $request->code);

            return redirect()
                ->route('admin.wallets.show', $uuid)
                ->with('success', 'Voucher has been redeemed.');
        } catch (Throwable $th) {
            if($th instanceof InvalidDataException) {
                throw ValidationException::withMessages([
                    'code' => $th->getMessage()
                ]);
            }
            return redirect()->back()->with('error', 'Something went wrong during redeeming');
        }
    }
```
But if I take the flash message e.g. the `redirect()->back()->with('error', 'Something went wrong during redeeming')` outside the `try/catch` block it works. this issue is only on the `database` session driver. the `file` & `redis` session driver works well (in or out of try/catch block).

Meaning the issue is that the flash message e.g. in my case its `error` or `success` is empty when redirected back. whether its blade view or inertiajs (share flash messages prop).

**Video demonstration:**

https://user-images.githubusercontent.com/92947803/211647879-ca8d53d1-d7c8-4014-9135-3ce59af2bfe5.mp4

### Steps To Reproduce:

1. Create a new Laravel 9 project.
2. Set your `SESSION_DRIVER` to `database`. Of course, you need to have the `sessions` table. (`php artisan session:table`)
3. Do some crud (store resource e.g post) in the controller with try/catch block. and catching an exception then redirecting back with the flash error message.

**Comment by aneesdev** [comment]
@driesvints @timacdonald

**Comment by some0ne2** [comment]
> @driesvints @timacdonald

I don't think this is good style to "push" and cause some feelings of rush to the maintainers.

**Comment by aneesdev** [comment]
> > @driesvints @timacdonald
> 
> I don't think this is good style to "push" and cause some feelings of rush to the maintainers.

oh I really sorry about that. my apologies.

**Comment by aneesdev** [comment]
The issue was that my redeem service class was also doing try/catch.
