### ISSUE TITLE
TrustProxies can not be configured to trust 2 or more (except all) forwarded headers

### ISSUE THREAD

**Issue by damijank** [laravel/framework#45612]
- Laravel Version: 9.45.1
- PHP Version: 8.0.26 (irrelevant)
- Database Driver & Version: (irrelevant)

### Description:
First of all, the TrustProxies `$headers` can not be configured via the `config/trustproxy.php` configuration file any more. Maybe that's documented somewhere, and this behaviour is removed, but I can't seem to find a reason why this would have been removed, whereas the `$proxies` still can be configured from there.

To come to the matter at hand... I have a specific situation where my application has to trust only 2 headers from the available ones, namely the `X-FORWARDED-FOR` and `X-FORWARDED-PROTO`. This is currently unsupported by the Laravel Framework, since the `getTrustedHeaderNames()` method can only resolve to:
* one of the possibilities,
* the AWS combo (which is different from what I need), or
* all headers as the default.

When extending the `TrustProxies` middleware and setting the `$headers` to the two values I need, this method still resolves to the default.

Of course, I solved this by overriding the resolving method and returning a "fixed" value of what is needed by my app (and, mind you, added reading it from `trustedproxy.headers` configuration value). But, the original implementation does not work in the way it is "advertised"... the phpdoc block above the method says *"Retrieve trusted header name(s), falling back to defaults if config not set."* ... the plural here misleads a bit. Currently, if `$headers` is a bit field of only two header constants, the method still falls back to default, which is all headers.

### Steps To Reproduce:
* extend the `TrustProxies` middleware
* set the `$headers` property as
`$headers = Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_PROTO`
* **ACTUAL**: the `getTrustedHeaderNames()` method still returns `62` (that's `0b111110`, the combo of the 5 base header-values)
* **EXPECTED**:  the `getTrustedHeaderNames()` method returns `10` (`0b001010`, the bit-field for the two specified headers)

I perfectly understand the need for a resolver method, any unexpected values must be filtered out. But, the current implementation does not do that, and rather only allows for single header, the AWS combo, or all headers. Instead, it should resolve to a value which acknowledges the `$headers` value in the bitwise manner for all specified headers. It should be as simple as this to filter out the unwanted bits:
`return $this->headers & 0b111111;`
Of course, if reading from the config, and not hard-coding it like this, it should be more elaborate, but this is in a nutshell.

### Another note
Somewhat unrelated to the above, but it's in the same realm... I had to change the `$proxies` value in my app from `'**'` to `'0.0.0.0/0'` to be able to get the actual client's IP address. The `'*'` and `'**'` configuration values are now behaving exactly the same... whereas up until now (we've been on Laravel 5, don't ask) the double-star config actually resolved to "all proxies" instead of the current `$_SERVER['REMOTE_ADDR']`.

Was this intentionally deprecated, or did someone make a mistake here? Or, maybe, someone mistakenly thought that this is actually correct?

**Comment by driesvints** [comment]
Hey @damijank, thank you for the thorough issue. I think right now, since you found a solution to your use case, we won't take any action here. I don't think anything was intentionally deprecated. If you want, you could attempt a PR with your suggestion to get the behavior you desire. Right now we don't have any other reports about this not working as expected. Thanks
