### ISSUE TITLE
session store not getting session value if session key number string

### ISSUE THREAD

**Issue by andiLeong** [laravel/framework#45610]
- Laravel Version: 9.46.0
- PHP Version: 8.1.12
- Database Driver & Version: mysql

### Description:
session store not getting session value if session key number string eg
"99","88","77"

### Steps To Reproduce:
I created a 3 simple route , one is to set session , secodn is to get session ,third is show all session like below :

```
Route::get('/set-session', function () {
    \Illuminate\Support\Facades\Session::put('999','bar');
});

Route::get('/get-session', function () {
    $value = \Illuminate\Support\Facades\Session::get('999','default');
    return $value;
});

Route::get('/all', function () {
    $value = \Illuminate\Support\Facades\Session::all();
    return $value;
});

```

issue : 

1, the second route ```get-session``` alwasy get string 'default'
2 , the third route ```all``` endpoint doesnt show that '999' inside the all session keys , instead I see ```"0": "bar",```
3, If I hit the first route ```set-session``` endpoint multiple times, unnecesssary session created like below

this is the all endpoint returned json
```
{
  "0": "bar",
  "1": "bar",
  "2": "bar",
  "3": "bar",
  "4": "bar",
  "_token": "WZMd51Tq1hjuimv4HgpIsLZtxHSFYK2ZAPV0iGWH",
  "_previous": {
    "url": "http://127.0.0.1:8000/set-session"
  },
  "_flash": {
    "old": [
      
    ],
    "new": [
      
    ]
  }
}

```

reason why is when we read the session data we use array_merge which doesn keey the number index , it will always create new number index.

I had created a pr here
[45607](https://github.com/laravel/framework/pull/45607)

**Comment by driesvints** [comment]
Seems like you already created a PR so let's see how it goes
