### ISSUE TITLE
Validation Rule Unique/Database ignores additional where() callbacks

### ISSUE THREAD

**Issue by bhaidar** [laravel/framework#45623]
- Laravel Version: 9.46.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL v8

### Description:
I have two tables:
- Sites:id,name  
- Endpoints:id,location,site_id

One site has many endpoints. 

My goal is not to allow duplicate locations within the same site.
 
I add a validation rule when updating the endpoint. However, the unique database validation rule ignores the where() clause to define the site_id.

My validation rule looks like this:

```php
public function rules(): array
    {
        return [
            'location' => [
                'required',
                Rule::unique('endpoints')->where(fn ($query) => $query->where('site_id', $this->endpoint->site_id)),
            ],
            'frequency' => ['required', new Enum(EndpointFrequency::class)],
        ];
    }
```

I debugged the Unique rule to understand what is the validation string representation. This is what is being generated:

```
"unique:endpoints,NULL,NULL,id"
```

As you can see, the `site_id` is being ignored somehow.

### Steps To Reproduce:

You can check this repository. It uses Laravel and Inertia JS.

https://github.com/bhaidar/laravel-uptime-monitor

**Comment by denizgolbas** [comment]
For store request:

```php
public function rules(): array
    {
        $site_id = $this->your_binding_key->site_id;
        return [
            'location' => [
                'required',
                   Rule::unique('endpoints')->where(function($query) use ($site_id) {
                    return $query->where('site_id', $site_id);
                }),
            ],
            'frequency' => ['required', new Enum(EndpointFrequency::class)],
        ];
    }

```


For update request:

```php
public function rules(): array
    {
        $site_id = $this->your_binding_key->site_id;
        return [
            'location' => [
                'required',
                   Rule::unique('endpoints')->where(function($query) use ($site_id) {
                    return $query->where('site_id', $site_id);
                })->ignoreModel($this->your_binding_key),
            ],
            'frequency' => ['required', new Enum(EndpointFrequency::class)],
        ];
    }

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by bhaidar** [comment]
Sure @driesvints I will. Thank you

**Comment by bhaidar** [comment]
@denizgolbas It's the same code as the one I pasted. Same result.
