### ISSUE TITLE
Calling a model factory within another factory breaks in a namespaced package 

### ISSUE THREAD

**Issue by cannycookie** [laravel/framework#45635]
- Laravel Version: 9.47.0
- PHP Version: 8.1.11
- Database Driver & Version: mysql

### Steps To Reproduce:

In a package create a Factory and call another factory from within it.

```php
namespace Visualbuilder\Core\Database\Factories;

use Visualbuilder\Core\Models\Form;
use Visualbuilder\Core\Models\Layout;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<\Visualbuilder\Core\Models\Form>
 */
final class FormFactory extends Factory
{

	protected $model = Form::class;
	
	public function definition(): array
	{
		
		return [
			'name'      => $this->faker->name,
			'layout_id' => Layout::factory()
		];
	}
}

```

Run the seeder and this error is thrown:-
```bash
Class "App\Layout" not found
```

The namespace is lost due to a borked function modelName() in:-

```src/Illuminate/Database/Eloquent/Factories/Factory.php```

propose changing:- 
```php
 public function modelName()
    {
        $resolver = static::$modelNameResolver ?? function (self $factory) {
	        $namespacedFactoryBasename = Str::replaceLast(
		        'Factory', '', Str::replaceFirst(static::$namespace, '', get_class($factory))
	        );
	
	        $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));
	
	        $appNamespace = static::appNamespace();
	
	        return class_exists($appNamespace.'Models\\'.$namespacedFactoryBasename)
		        ? $appNamespace.'Models\\'.$namespacedFactoryBasename
		        : $appNamespace.$factoryBasename;
        };

        return $this->model ?? $resolver($this);
    }
```

to

```php
 public function modelName()
   {
       $resolver = static::$modelNameResolver ?? function (self $factory) {
	        $namespacedFactoryBasename = Str::replaceLast(
		        'Factory', '', Str::replaceFirst(static::$namespace, 'Models\\', get_class($factory))
	        );
	
	        $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));
			
	        $appNamespace = static::appNamespace();
	
	        return class_exists($namespacedFactoryBasename)
		        ? $namespacedFactoryBasename
		        : $appNamespace.$factoryBasename;
        };

        return $this->model ?? $resolver($this);
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by cannycookie** [comment]
OK, I will do, but I have other commitments for the next couple of weeks..
 I need to create a new package, publish it and install it to demo the
problem.

Regards
Lee

[image: Lee Evans] <http://www.ekouk.com/>

Lee Evans MSc, MCSE
Cloud Architect, Systems Analyst, White Hat

Technical Director at *Eko UK Limited*

2 Friar Walk, Worthing, BN13 1BL

t: +44 (0)1273 455 706 <01273-455706>

e: ***@***.***

m: +44 (0) 7789 204 174 <+447789204174>

w: https://www.ekouk.com

[image: twitter] <https://twitter.com/CannyCookie>

[image: facebook] <https://www.facebook.com/AcroYogaNinja>

[image: instagram] <https://www.instagram.com/acroyoganinja/>

I also teach acroyoga and partner acrobatics to adults and children.
Find out more at Aantara Acrobatics <https://aantara.com/>

[image: Lee Evans - Partner Acrobatics Instructor]

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

WARNING: Computer viruses can be transmitted via email. The recipient
should check this email and any attachments for the presence of viruses.
The company accepts no liability for any damage caused by any virus
transmitted by this email. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by cannycookie** [comment]
Made a new package as simple as can be and as a result, found the *bug* was user error 😳😳

The factory was missing the model definition.  
```php
protected $model = Layout::class;
```

Urgh, wasted hours and it was the simplest of things.  Case closed.
