### ISSUE TITLE
app()->makeWith defaulting optional DateTime constructor params to UTC now

### ISSUE THREAD

**Issue by ax-rfarmer** [laravel/framework#45691]
- Laravel Version: 9.48.0
- PHP Version: 8.2.1
- Database Driver & Version: n/a

### Description:

Calling app()->makeWith without constructor params defaults optional DateTime constructor params to UTC now:

```php
class TestClass
{
    /** @var DateTime|null */
    public $dateTime = null;

    public function __construct(DateTime $dateTime = null)
    {
        $this->dateTime = $dateTime;
    }
}
```

```php
$instance = app()->makeWith(TestClass::class, [
    // no constructor params
]);
```

$instance->dateTime is not null, but is instead UTC now

Expected: 
optional params should be defaulted to the default value specified on constructor when not passed to makeWith function (null in above test)

### Steps To Reproduce:

Create new laravel project, add in test class shown above and update '/' route to call makeWith:

```php
Route::get('/', function () {

    $instance = app()->makeWith(TestClass::class, [
        // no constructor params
    ]);

    return $instance->dateTime == null ? "null" : $instance->dateTime->format('Y-m-d H:i:s');
});
```

Will print out UTC now (or defaulted date) rather than null

It doesn't matter if param is marked as nullable or not (?), will still default param to a DateTime rather than default value specified (null)

**Comment by WendellAdriel** [comment]
@ax-rfarmer I followed the steps you said to reproduce the issue but I'm not able to do so.

I have this class

```php
<?php

namespace App\Support;

class TestClass
{
    public $dateTime = null;

    public function __construct(DateTime $dateTime = null)
    {
        $this->dateTime = $dateTime;
    }
}
```

This in the route:

```php
Route::get('test', function () {
    $instance = app()->makeWith(TestClass::class, [
        // no constructor params
    ]);

    return $instance->dateTime == null ? "null" : $instance->dateTime->format('Y-m-d H:i:s');
});
```

And this test:

```php
public function test_issue()
{
    $response = $this->get('/test');
    $content = $response->getContent();
    $this->assertSame('null', $content);
}
```

And the test is passing without issues.

**Comment by ax-rfarmer** [comment]
Thanks mate, will try test function on mine as well, also want to try it on a different machine to rule other things out. If still see it will attach my test proj ...

**Comment by ax-rfarmer** [comment]
[test_proj.zip](https://github.com/laravel/framework/files/10449637/test_proj.zip)
@WendellAdriel, I have tested using feature test you added and still see same result. I also tested on a PC using example app (work on Mac) and see the same behavior there as well (that one uses php 8.1.12, Mac uses php 8.2.1).

Stepping through the code, what is happening for me is the catch here is not being executed for the $dateTime param:
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Container/Container.php#L1057
because the try above that does not fail, looking at the constructor for that, Laravel is getting the default params for the DateTime object recursively, the constructor for DateTime is
```php
public DateTime::__construct(string $datetime = "now", ?DateTimeZone $timezone = null)
```
which is what I'm seeing being returned

In my earlier testing I saw this was not an issue when using php ^7.4 so something may have changed in ^8.0 to cause that catch to not be exercised and thus the param to not return its default.
 
I've attached the test_proj.zip to show what I'm running (includes the feature test), 
```shell
php -v           
PHP 8.2.1 (cli) (built: Jan  5 2023 20:07:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies
```

**Comment by WendellAdriel** [comment]
I’m not at my desk now but I tested that with Laravel 9.48 and PHP 8.2

**Comment by ax-rfarmer** [comment]
No worries mate, yeah that is what the test_proj I attached is using as well (latest framework in composer.lock, running on php 8.2.1)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
