### ISSUE TITLE
Making `pluck('id')` on many-many relation, where pivor have it's own `id` cause PDOException

### ISSUE THREAD

**Issue by Briareos17** [laravel/framework#45739]
- Laravel Version: 8.83.26
- PHP Version: 7.4.30
- Database Driver & Version: MySQL 8.0.30

### Description:
Making `pluck('id')` on many-many relation, where pivor have it's own `id` cause `PDOException: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous`

### Steps To Reproduce:
Create three models, use one of them as pivot of other two.
```
users
    id - integer
    name - string
 
roles
    id - integer
    name - string
 
user_roles
    id - integer
    user_id - integer
    role_id - integer
```
Then call `$user->roles()->pluck('id');`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Briareos17** [comment]
I'm still sure that this is a bug

**Comment by denizgolbas** [comment]
Put a finisher after roles():
$user->roles()->get()->pluck('id');`
`
