### ISSUE TITLE
Illuminate Filesystem replace() leaves file executable

### ISSUE THREAD

**Issue by JohntheFish** [laravel/framework#45779]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
Illuminate\Filesystem\Filesystem::replace() implements an atomic update to a file by creating a temporary file with 0777 permission. When the temporary file is renamed to replace the original, it is left with the 0777 permissions. The permissions are:

- Not revised to match the original file permission
- Leave the file executable

### Steps To Reproduce:

https://github.com/illuminate/filesystem/blob/6ca65f4f24d3277e22b8e8e7c62557c118209d0f/Filesystem.php#L200

**Comment by driesvints** [comment]
Fix will be released today, thanks.
