### ISSUE TITLE
dispatch method does not respect ShouldBeUnique on jobs

### ISSUE THREAD

**Issue by ankurk91** [laravel/framework#45781]
- Laravel Version: 9.48..0
- PHP Version: 8.2
- Database Driver & Version: MySql
- Cache and Queue driver - Redis v7

### Steps To Reproduce:

Create a test job:
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue, ShouldBeUnique
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct()
    {
        //
    }

    public function handle()
    {
        info("Running the job");
        sleep(3);
    }
}
```
Then create a Controller and dispatch the job via `dispatch()` helper available in all Controllers
```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Jobs\TestJob;

class TestController extends Controller
{
    public function index()
    {
        // TestJob::dispatch(); // works as expected 
        // dispatch(new TestJob()); // works as expected
        
        $this->dispatch(new TestJob()); // causing the issue
    }
}

```
Start the worker
```bash
php artisan queue:work --sleep=3
```

Now hit the controller via a route twice, notice worker will process the job twice.

The problem lies here in this trait

https://github.com/laravel/framework/blob/247735e224d27898197699c73909ee5ee2f93e01/src/Illuminate/Foundation/Bus/DispatchesJobs.php#L17

This method is dispatching the jobs in a different way which does not respect the `ShouldBeUnique` contract

**Comment by driesvints** [comment]
This is intentional I feel. The former methods you used are all actions on the jobs themselves while the Dispatcher just works differently. If you want to use the ShouldBeUnique you already have two ways of making that work.

**Comment by driesvints** [comment]
Feel free to send in a pr 👍

**Comment by driesvints** [comment]
I meant to say: send in a PR to the docs. We can't change the behavior here.

**Comment by alies-dev** [comment]
Just a note for someone who experienced the same issue (to save your time): `\Illuminate\Support\Facades\Bus::dispatch` also doesn't respect `ShouldBeUnique` (it proxies calls to the \Illuminate\Bus\Dispatcher that probably used by @ankurk91 at the original message/example: `$this->dispatch()`)
