### ISSUE TITLE
Cascade: Soft-Delete Children Records

### ISSUE THREAD

**Issue by gul-ahmad** [laravel/framework#45794]
- Laravel Version: 9+
- PHP Version:8.1
- Database Driver & Version:MySql(Laragon)

### Description:
Laravel softdelete does not work in the case when there is One to Many relationship exists . Let assume my case when a Column has many Cards and Cards belongs to Column.
The Card is implementing the softdelete way but parent either implements or not but in my case the parent is not implementing it ,just the children is implementing it.And in children migration we are using the softDeletes to have deleted_at.
When we delete any Column,then all its relevant children(cards) must be deleted and its working fine but they are not getting softDeleted instead they are deleted like forceDelete.
I hope I have correctly explained the issue.

**Comment by gul-ahmad** [comment]
To support my issue see the following details as well

https://blog.quickadminpanel.com/one-to-many-with-soft-deletes-deleting-parent-restrict-or-cascade/

Many people using this package for it.

https://github.com/michaeldyrynda/laravel-cascade-soft-deletes

**Comment by driesvints** [comment]
Hi there, this is currently the expected behavior. If you would like to have a different behavior you can attempt a PR, thanks.
