### ISSUE TITLE
Bug with named morphTo relationships and LazyLoadingViolationException

### ISSUE THREAD

**Issue by Sergiobop** [laravel/framework#45800]
- Laravel Version: 9.48
- PHP Version: 8.1
- Database Driver & Version: psql

### Description:
When you have a custom named morphTo relationship, Laravel throws the LazyLoadingViolationException, even though the relationship is loaded.

### Steps To Reproduce:
Given the model "Model", which has a nullable morph, 'item'

Model 

```
public function item(): MorphTo
{
      return $this->morphTo();
}

public function simple_item(): MorphTo
{
      return $this->morphTo('item')->select(['id', 'name']);
}
```

If we do:

```

$models = Model::query()->with(['simple_item'])->get();

foreach($models as $model) {
      $itemName = $model->item->name;
}

```

The exception is thrown:

```
Attempted to lazy load [item] on model [App\Models\Model] but lazy loading is disabled
````

If we dd, the query, the relationship 'item' is filled and the 'simple_item' is null:

```
$models = Model::query()->with(['simple_item'])->get()->dd();
```

```
#relations: array:3 [
      "simple_item" => null
      "item" => App\Models\.. 
]
```

If we debug the model to see what relationships are loaded:
```
dd($this->relationLoaded('item')); // false even though item is filled with the model
dd($this->relationLoaded('simple_item')); // true even though simple_item is null
```

UPDATE:

As a workaround, this works without additional database queries:
```
$models = Model::query()->with(['simple_item'])->get();

foreach($models as $model) {
      $model->loadMissing('item'); // This line actually doesn't call the DB
      $itemName = $model->item->name;
}
```

**Comment by eduance** [comment]
We need to gather some more details to assist you in your journey.

1. Could you specify which model you're trying to actually make morphable?
2.  When you call ``Model::query()``, which model are you actually referring to?
3.  What is the value of ``$modelsShouldPreventLazyLoading`` inside your model?

After creating a fresh Laravel app, reproducing the steps I was unable to recreate this bug. Could you provide a repository with this exact issue?

This was my setup:

```$images = Image::query()->with(['item'])->get();```

```
class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'url',
        'imageable_id',
        'imageable_type'
    ];

    /**
     * Get the parent model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function imageable()
    {
        return $this->morphTo('item');
    }

    /**
     * Get the parent model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function item()
    {
        return $this->morphTo();
    }
}
```
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
      'name'
    ];

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}
```

Thanks.

**Comment by Sergiobop** [comment]
Hi @eduance thank you for your response.

The example you posted is not the same as mine. The bug is produced if you change your setup to this one:

```
class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'url',
        'imageable_id',
        'imageable_type'
    ];

    public function imageable()
    {
        return $this->morphTo('item');
    }

    public function item()
    {
        return $this->morphTo();
    }
}
```

```
class Post extends Model
{
    use HasFactory;

    protected $fillable = [
      'name'
    ];

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}
```

Code:
```
$images = Image::query()->with(['imageable'])->get();

foreach($images as $image) {
      $itemName = $image->item->name; // This throws the LazyLoadingViolationException
}
```


Debug:
If we dd, the query, the relationship 'item' is filled and the 'imageable' is null:

```
$models =  Image::query()->with(['imageable'])->get()->dd();
#relations: array:3 [
      "imageable" => null
      "item" => App\Models\.. 
]
```

If we debug the model to see what relationships are loaded:
```
dd($this->relationLoaded('item')); // false even though item is filled with the model
dd($this->relationLoaded('imageable')); // true even though imageable is null
```

**Comment by eduance** [comment]
@Sergiobop Thanks for the detailed overview.

The way the morphTo works is that it by default sets the name of your relation equal to the class, so image would become imageable_type and so on. If you now rename your morphTo it will do the assumption you have renamed your names as well and you got a column named 'item_type' and 'item_id'.

So, if you replace your morphTo with a specified type and id, it works like magic.

```
    /**
     * Get the parent model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphTo
     */
    public function imageable()
    {
        return $this->morphTo('item', 'imageable_type', 'imageable_id');
    }
```

So, if you take a dive into the process that Laravel tries to achieve:

1. You are trying to get the imageable.
2. The imageable relationship is renamed to item, Laravel follows that trace.
3. Laravel looks for the item_type and item_id, and is unable to find these fields.
4. You are now trying to call the item on an image, and this will work, because it has an imageable_type and imageable_id therefore loading these records.
5. You're eagerloading the imageable, then trying to call the name on another relationship named item which won't work due to these now being separate relationships but you most likely have strict loading enabled.

By default lazy loading is disabled, therefore you're getting this exception.

The fix above should solve your problem, if not, let's see if we can solve it together.

Happy eagerloading!

![bitmoji](https://sdk.bitmoji.com/render/panel/a41da708-81e9-4ec3-9364-9d8748f7063d-74de0b43-c667-43ae-a025-e23fead9ef9c-v1.png?transparent=1&palette=1&width=246)

**Comment by Sergiobop** [comment]
Hi @eduance thank you again for your response, but i think the bug is still there. Let me change the example with some complexity.

Imagine the Post model have multiple attributes ('name', 'description' ....) and it morphs to many Image, since the post can have multiple images in the database.

We have 2 morphsTo relationships, one with a constrain because sometimes we want to eager load the entire post, and sometimes we want to eager load only the simplified post:

```
class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'url',
        'imageable_id',
        'imageable_type'
    ];

    public function imageable()
    {
        return $this->morphTo();
    }

    public function simplified_imageable()
    {
        return $this->morphTo('imageable')
        ->constrain([
               Post::class => function ($query) { $query->select(['id', 'name']); },
           ]);
    }
}
```

```
class Post extends Model
{
    use HasFactory;

    protected $fillable = [
      'name',
      'description',
      'other_field',
    ];

    public function image()
    {
        return $this->morphMany(Image::class, 'imageable');
    }
}
```

Code:
```
$images = Image::query()->with(['simplified_imageable'])->get();

foreach($images as $image) {
      $itemName = $image->imageable->name; // This throws the LazyLoadingViolationException
}
```


Debug:
If we dd, the query, the relationship 'imageable' is filled and the 'simplified_imageable' is null:

```
$models =  Image::query()->with(['simplified_imageable'])->get()->dd();
#relations: array:3 [
      "simplified_imageable" => null
      "imageable" => App\Models\.. 
]
```

If we debug the model to see what relationships are loaded:
```
dd($this->relationLoaded('imageable')); // false even though item is filled with the model
dd($this->relationLoaded('simplified_imageable')); // true even though imageable is null
```


Sorry if I didn't explain myself well and thank you for your attention

**Comment by eduance** [comment]
This bug is indeed a problem. I'm looking into it at a later point, in a way you could say this is intended behavior, but we will have to verify it.

**Comment by eduance** [comment]
I was swamped at work as we're releasing a new feature, will look into this issue tonight.

**Comment by bert-w** [comment]
I cant seem to reproduce your exact situation, some of the code samples are not adding up it seems.

I suggest creating a testcase in this file (it has most of the things you need predefined already) and see if it still occurs:
```
\laravel-framework\tests\Integration\Database\EloquentMorphConstrainTest.php
```

**Comment by huiyang** [comment]
i am facing simlar issue, and i digged into the code, seem like the relation name is mixed with morph name

```
public function book() {
return $this->morphTo('borrowable');
}
```

(morph columns: `borrowable_type` and `borrowable_id`)

morph name: borrowable
relation name: book / borrowable? (currently laravel used morph name as relation name)

to me, relation name should be book, instead of borrowable.
so that i can get related models by `$parent->book` instead of `$parent->borrowable`

please correct me if i missed out anything / have any misunderstanding.

**Comment by cosmastech** [comment]
@Sergiobop 
>```php
>$images = Image::query()->with(['simplified_imageable'])->get();
>
>foreach($images as $image) {
>      $itemName = $image->imageable->name; // This throws the LazyLoadingViolationException
>}
>```

I think this is technically the correct behavior. If you're eager loading a relationship which extends another relationship, then the child relationship should be loaded & set, not the parent.

In the PR I linked, the relationship `simplified_imageable` would be properly loaded (and set as $image->simplified_imageable), but `imageable` would still throw a LazyLoadViolation unless you included it in `with()`.

**Comment by driesvints** [comment]
It seems this isn't supported, sorry.

**Comment by Geovanek** [comment]
I'm having problems with MorphTo too.

The relationship always returns null, except when the type_id = 1 (invitationable_id) in my case.

**Model Invitation**
```
public function invitationable(): MorphTo
    {
        return $this->morphTo();
    }
```

**Test in controller**
```
dd(Invitation::with('invitationable')->get());
```

**Result**
```Illuminate\Database\Eloquent\Collection {#1802 ▼ // app/Http/Controllers/Company/InvitationsController.php:18
  #items: array:4 [▼
    0 => App\Models\Invitation {#1814 ▼
      #table: "invitations"
      +preventsLazyLoading: true
      #attributes: array:13 [▶]
      #original: array:13 [▶]
      #relations: array:1 [▼
        "invitationable" => null
      ]
      ...

1 => App\Models\Invitation {#1798 ▼
      #connection: "mysql"
      #table: "invitations"
      #attributes: array:13 [▶]
      #original: array:13 [▶]
      #relations: array:1 [▼
        "invitationable" => App\Models\Coach {#1843 ▼
          #connection: "mysql"
          #table: "coaches"
          #attributes: array:8 [▶]
          #original: array:8 [▼
            "id" => **1**
            "uuid" => "46b6f6d2-3048-4d4c-9f2c-356f5f7abbe8"
            "company_id" => 1
            "role_id" => 1
            "about" => "Quia ad nulla eu labore iusto nulla aut at anim ab in fugit magna at eveniet"
            "created_at" => "2023-03-03 13:07:31"
            "updated_at" => "2023-04-06 16:14:39"
            "deleted_at" => null
          ]
```

But when I do the test in Tinker, it returns correctly.
