### ISSUE TITLE
Artisan command test doesn't seem to commit created DB record

### ISSUE THREAD

**Issue by Adesin-fr** [laravel/framework#45811]
- Laravel Version: tried with v8.83.27 and v9.48.0
- PHP Version: 8.1.14
- Database Driver & Version: Sqlite3 (SQLite Library => 3.37.2) and MySQL

### Description:
When my Artisan command is run, it creates a model record in the database. die & dumping the table `count()` after the create show one record, but asserting table count in the test gives zero.
Tried with mysql and sqlite : in mysql I could workaround the problem with adding a DB::commit() just after the create (the assert then passes), but in sqlite, it had no effect.

### Steps To Reproduce:
Create a simple artisan command, that tries to `Create` a model : 
```php
<?php

namespace App\Console\Commands;

use App\Models\RegisteredApplication;
use Illuminate\Console\Command;

class RegisterApplication extends Command
{

    protected $signature = 'register:application';
    protected $description = 'Register a new application to the signature service.';

    public function handle()
    {
        $registerd = RegisteredApplication::create(["name"=> "a name"]);

        return true;
    }
}
```
Create the model and the migration with `php artisan make:model -mf RegisteredApplication`

Create a test that runs this command : 
```php
<?php

namespace Tests\Feature;

use App\Models\RegisteredApplication;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ArtisanTest extends TestCase
{
    use RefreshDatabase;

    /** @test  */
    public function ItCreatesAnApplicationRecord()
    {
        $artisan = $this->artisan("register:application");
        $this->assertDatabaseCount("registered_applications",1);
    }
}
```

Run the test : the `assertDatabaseCount` fails.

Github repo to illustrate the issue : `https://github.com/Adesin-fr/LaravelArtisanTest`

PS : as I suspect, it seems to be artisan "mockery" : replacing the line `$artisan = $this->artisan("register:application");` with `Artisan::call("register:application");` makes the test pass, but I can't interact with inputs...

PS2 : I had to open a new issue since the previous was closed and locked so quickly that I couldn't argue !

**Comment by sethsandaru** [comment]
You need to invoke the `execute()` method. Otherwise, the command won't run (only run when destructing the object, check `PendingCommand` for more refs)

```php
$this->artisan("register:application")->execute();
```

**Comment by Adesin-fr** [comment]
Yes, that did the trick.

The doc should be updated to mention this, since there is no mention of this `execute()` method !

**Comment by driesvints** [comment]
Thanks @sethsandaru. We'd appreciate a PR to the docs 👍
