### ISSUE TITLE
Inconsistent encoding behavior of ComponentAttributeBag

### ISSUE THREAD

**Issue by slelorrain** [laravel/framework#45821]
- Laravel Version: 9.48.0
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 5.7.40

### Description:

Calling an anonymous component with a variable containing a string having specific characters (e.g. &, ', ") is working as expected.

But doing the same through another anonymous component generate a different encoding of the bag.

### Steps To Reproduce:

I was able to reproduce it by updating an existing test, please see following gist:
https://gist.github.com/slelorrain/22b2cafd0b9d8be4fec5300ca809073c

I added output of the phpunit command in comment of the gist, and you can see that two first tests work as expected but last one fails.

**Comment by driesvints** [comment]
It seems the compiler currently cannot handle this. What I suggest you do is to use a variable to send the string to the component as an intermediate solution.

**Comment by slelorrain** [comment]
Thank you for your reply @driesvints but I'm not sure to correctly understand what you are suggesting.

Please find below an extract of what I'm trying to do:

Call to anonymous component "date"
```
@php
$name = 'o&k';
@endphp
<x-forms.date :$name/>
```

Anonymous component "date"
```
<x-forms.input {{ $attributes->merge(['type' => 'date', 'name' => 'date') }}/>
```

Anonymous component "input"
```
@php
$type = $type ?? 'text';
$name = $name ?? '';
@endphp
<input type="{{ $type }}" name="{{ $name }}">
```

Thank you again

**Comment by driesvints** [comment]
Does it help when you escape the name?

```
@php
$name = e('o&k');
@endphp
```

**Comment by slelorrain** [comment]
Thank you for your quick answer. 

Unfortunately it doesn't help, it even amplifies the issue as you see:
`<input type="date" name="o&amp;amp;k"`

It "works" if I remove the escaping around $value in sanitizeComponentAttribute($value) of CompilesComponents ...but it voids the purpose of this function i guess 😭

**Comment by driesvints** [comment]
hmm yeah. What if you this?

```
@php
$name = 'o&k';
@endphp
<x-forms.date name={{ $name }}/>
```

**Comment by slelorrain** [comment]
Thank you again, but it's still not ok 😢

With what your proposal:
```<input type="date" name="1"```

If I try with quotes around {{ $name }}:
```<x-forms.date name="{{ $name }}"/>```

I get again:
```<input type="date" name="o&amp;k"```

**Comment by driesvints** [comment]
Wait try:

```
@php
$name = 'o&k';
@endphp
<x-forms.date name={!! $name !!}/>
```

**Comment by slelorrain** [comment]
Indeed it solves the encoding issue.

But as it is less "sexy" :p :
`<x-forms.date name="{!! $name !!}" label="{!! $label !!}" description="{!! $description !!}"`

I think I will finally use directly the anonymous "input" component:
`<x-forms.input type="date" icon="date" :$name :$label :$description`

Thank you again for your help, have a nice day and a nice weekend.
