### ISSUE TITLE
Artisan/ShowModel: Error `Array to string conversion` when attribute has array as default

### ISSUE THREAD

**Issue by vHeemstra** [laravel/framework#45857]
#### Env
Laravel Framework 9.33.0

#### Problem / issue
If you set a model's attribute to have an array as default, the Artisan show model command (`php artisan model:show SomeModel`) will throw an ErrorException: `Array to string conversion`.

#### Origin of the problem
This line:
https://github.com/laravel/framework/blob/bdbd1aa6145f6a88244eb8f78e08e332dcf0e3b1/src/Illuminate/Foundation/Console/ShowModelCommand.php#L375

#### Possible solution
Possible solution is to check for non-stringable default values and either:
a. have them be JSON encoded (or something smarter?) before display
b. or use a string placeholder like `Array`/`Object`

<details>
<summary><b><i>Example to reproduce</i></b></summary>

#### Create `app/Models/SomeModel.php`:
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SomeModel extends Model
{
  use HasFactory, SoftDeletes;

  /**
   * The model's default values for attributes.
   *
   * @var array
   */
  protected $attributes = [
    'name' => '',
    'content' => [], // <-- array/object as default value
  ];
```

#### Run in terminal
```sh
php artisan model:show SomeModel
```

</details>

**Comment by driesvints** [comment]
Don't you need to have the content as a encoded JSON string instead of an array in your attributes array?

**Comment by vHeemstra** [comment]
As a default, in my case, I need this attribute to start as an empty array.

To store it in the database, I use the Json class from the [Custom Casts example](https://laravel.com/docs/9.x/eloquent-mutators#custom-casts) as the type cast.

Or should my default start as how it would be stored in the database?

**Comment by vHeemstra** [comment]
Ah ok, the docs about setting default attributes didn't mention this, so I assumed it should be the value after casting.

Should that be added to that part of the docs?

**Comment by driesvints** [comment]
You can always try a PR 👍
