### ISSUE TITLE
Global scope applied twice

### ISSUE THREAD

**Issue by bertoost** [laravel/framework#45865]
- Laravel Version: 8.83.27
- PHP Version: 7.4.33
- Database Driver & Version: MySQL 8.0.19

### Description:
Applied global scope runs twice.
First time with xdebug it does not trigger my breakpoint. Second time it does and debugging the builder will result in already applied scope results.

### Steps To Reproduce:

1. Create a simple model with a "name" field
2. Apply a global scope like this
```php
public static function boot(): void
{
    parent::boot();

    static::addGlobalScope('order', static function (Builder $query) {
        $query->orderBy('name');
    });
}
```
3. When printing the $builder->toSql(); you will see the order by is applied twice.

I found this based on a global scope added by a scope class, same behavior.

Another example
https://stackoverflow.com/questions/73155783/laravel-global-scope-apply-function-runs-twice

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by bertoost** [comment]
Sorry, I didn't realized that. We are heading an upgrade to Laravel 9, but still running on 8 for time being.
I have tested it on a clean install of Laravel 9, and it seems not to be an issue anymore.
