### ISSUE TITLE
Authenticate middleware doesn't redirect to sub domains correctly

### ISSUE THREAD

**Issue by NinjaJake86** [laravel/framework#45875]
- Laravel Version: 9.48.0
- PHP Version: 8.2
- Database Driver & Version: mysql (deployed by sail)
- Vite Version: 4.0.4
- Using Inertia & Vue3

### Description:
After customising Authenticate middleware RedirectTo function to return to different sub domains based on route.

Laravel redirects to the correct path but DOES NOT go to the correct sub domain but remains on the top domain/sub domain of the original request (only tested on top domain).

It will also render the route correctly but refreshing the page returns a 404 as that route is not valid unless on the sub domain

### Steps To Reproduce:
Install inertia and vue3 into new laravel application (deployed by sail)
Customise RouteServiceProvider to process different sub domains:

```
Route::domain(env('APP_DOMAIN'))
                ->middleware('web')
                ->group(base_path('routes/web/web.php'));
Route::domain('app.' . env('APP_DOMAIN'))
                ->middleware('app')
                ->group(base_path('routes/app/app.php'));
Route::domain('partners.' . env('APP_DOMAIN'))
                ->middleware('partners')
                ->group(base_path('routes/partners/partners.php'));
Route::domain('database.' . env('APP_DOMAIN'))
                ->middleware('database')
                ->group(base_path('routes/database/database.php'));
```

Customise RedirectTo function to return different sub domains based on path

```
protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            if ($request->routeIs('web.*') || $request->routeIs('app.*')) {
                return route('app.login');
            } elseif ($request->routeIs('partners.*')) {
                return route('partners.login');
            } elseif ($request->routeIs('database.*')) {
                return route('database.login');
            }
        }
    }
```
Create routes protected by auth middleware and also auth routes for login
Navigate to route protected by auth middleware

**Comment by NinjaJake86** [comment]
I've checked through the vendor files and it is creating a RedirectRequest with the correct url and sub domain but it still isn't redirecting correctly

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by NinjaJake86** [comment]
Thanks for the reply! While making the bud-report repo i found that it was actually working, this appears to be related to Inertia and how it handles redirects and is not actually a Laravel issue. This Issue can be closed. If anyone would like more info about the particular issue being experienced then please refer to: https://github.com/inertiajs/inertia-laravel/issues/431

Thanks for the help!
