### ISSUE TITLE
Wrong order when sorting by a JSON field

### ISSUE THREAD

**Issue by salvisb** [laravel/framework#45880]
- Laravel Version: 9.45.1
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0.31

### Description:
Sorting by JSON fields is not quite right. Please see example below.

Result when sorting by a regular field (this is fine):
- A
- Āa
- Ab
- b
- C
- D

Result when sorting by JSON field (this is not ok).
- A
- Ab
- C
- D
- b
- Āa

The issue goes away when default collation is applied to Illuminate\Database\Query\Grammars\MySqlGrammar::wrapJsonSelector.

```return 'json_unquote(json_extract('.$field.$path.')) COLLATE \'utf8mb4_unicode_ci\'';```

### Steps To Reproduce:

- Create roles table with a name field (type of the field should be "text").
- Seed records with the above values, e.g. "{"lv": "A"}", "{"lv": "Ab"}", ...
- Run Role::orderBy('name->lv')->get();

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
