### ISSUE TITLE
[10.x] PostgreSQL identity columns broken

### ISSUE THREAD

**Issue by tpetry** [laravel/framework#45907]
- Laravel Version: `10.x @ d89a6a0`
- Database Driver: PostgreSQL

### Description:
While testing Laravel 10 for [tpetry/laravel-postgresql-enhanced](https://github.com/tpetry/laravel-postgresql-enhanced), I found a bug in the PostgreSQL grammar. When @hafezdivandari added the ability to change columns without `doctrine/dbal` (e901b026dccd96f7f6ce87bbb7d57af1c7f80c97), the behaviour of identity columns was changed. In Laravel 9 identity column could be created by using `generatedAs` without any arguments. But now this behaviour has changed to completely ignore that a column is an identity column.

> **Note**
> Identity columns are the the same as MySQL's `auto_increment` functionality, but they are part of the SQL standard. They are the expected way to have automatic numbered columns in a SQL standard compliant way.

### Steps To Reproduce:

```php
Schema::create('table', function (Blueprint $table): void {
  $table->bigInteger('col1')->generatedAs();
  $table->bigInteger('col2')->generatedAs()->always(true);
});
```

Laravel 9:
```sql
create table "table" (
  "col1" bigint generated by default as identity not null,
  "col2" bigint generated always as identity not null
)
```

Laravel 10:
```sql
create table "table" (
  "col1" bigint not null,
  "col2" bigint not null
)
```

**Comment by eduance** [comment]
@tpetry I am looking into this, where did you get your SQL from?

```
$blueprint->increments('foo')->generatedAs();
```

Generates the following SQL:

```
  0 => "alter table "users" add column "foo" integer not null generated by default as identity primary key"
```

This:

```
$blueprint->bigInteger('col2')->generatedAs()->always(true);
```

Generates:

```
  0 => "alter table "users" add column "col2" bigint not null generated always as identity"
```

Would love to help you further.

**Comment by tpetry** [comment]
Its happening for me when creating a table. Like with the code I shared. Didn‘t test changing a table, but that seems to work for you 👍

**Comment by eduance** [comment]
I have been testing it using the create method on the Blueprint, this generates the following SQL:

```
        $blueprint = new Blueprint('users');
        $blueprint->create();
        $blueprint->bigInteger('foo')->generatedAs()->always(true);
        $blueprint->bigInteger('foo2')->generatedAs()->always(true);
        $statements = $blueprint->toSql($this->getConnection(), $this->getGrammar());
```

Will generate:

```
create table "users" ("foo" bigint not null generated always as identity, "foo2" bigint not null generated always as identity)
```

I saw the reply in your repository that you're currently running this against the tests in your own repository, could you show the test you're using to recreate this issue? It could expose further details about the scope that influences it as i'm unable to recreate it in a new laravel project (using pgsql + master branch) / laravel framework. The Schema facade is simply a proxy for the builder, and essentially will generate a blueprint and wrap it with the Build method. As everything seems to work good in the Blueprint class, it 

_p.s: nice package, finally no raw queries to add materialized views :)_

**Comment by hafezdivandari** [comment]
@tpetry You are overriding the `$modifiers` property at your package [on this line](https://github.com/tpetry/laravel-postgresql-enhanced/blob/96ebd81a5510a478ff199b3680a35760df7fc046/src/Schema/Grammars/Grammar.php#L19), I think you may have missed the newly added `GeneratedAs` element to this array. Check this change: https://github.com/laravel/framework/commit/e901b026dccd96f7f6ce87bbb7d57af1c7f80c97#diff-653f90bd1ee0a1c7c7970912484e98c8bbd30c8e9a3d2f544d53834d54e7ce7cR25

**Comment by tpetry** [comment]
That was a dumb mistake by me. I expected the bug to be in my driver (as I have to support many versions it is much more complex). When testing it with my Laravel demo application I forgot that the enhanced PG driver was installed and therefore I never tested it without my modifications.

@eduance @hafezdivandari Sorry for the unnecessary work I have caused you.

**Comment by eduance** [comment]
@tpetry It's all good, glad you found your issue. Goodluck with your upgrade!
