### ISSUE TITLE
Escaping Blade directives with @@ is broken

### ISSUE THREAD

**Issue by palypster** [laravel/framework#45915]
- Laravel Version: 9.50.1
- PHP Version: 8.2.1
- Database Driver & Version: (irrelevant)

### Description:
[Escaping Blade directives](https://laravel.com/docs/9.x/blade#blade-and-javascript-frameworks) with `@` symbol is broken in some cases.

### Steps To Reproduce:

Consider this valid blade:
```
@php
    $columns = [];
    $locales = [];
@endphp

@foreach($columns as $col)
    @if($col == 'foo')
        <div></div>
    @elseif($col == 'bar')
        @@foreach($locales as $locale)
            <div></div>
        @@endforeach
    @else
        <div></div>
    @endif
@endforeach
```

Expected behaviour:
Blade will complile. Double `@@` should just produce one `@`, just like written in the documentation (and how it worked few weeks ago, something must have break just lately).

I'm getting:
```
syntax error, unexpected token "endforeach", expecting "elseif" or "else" or "endif"
```

One solution is to instead of using `@@` to use `{{'@'}}`. If you prefer this solution, then please update the documentation so this is the recommended way.

**Comment by taylorotwell** [comment]
@imanghafoori1 this (https://github.com/laravel/framework/pull/45490) is still broken. I think we need to revert everything back to its original state?

**Comment by imanghafoori1** [comment]
I take a look into that right now, I need a few hours to investigate the problem.
