### ISSUE TITLE
No support for DynamoDB Map functionality?

### ISSUE THREAD

**Issue by LiamMcLeodNDL** [laravel/framework#45926]
- Laravel Version: 9.2
- PHP Version: 8.1.8
- Database Driver & Version: N/A

### Description:
Storing objects when using DynamoDB Store generates long and unnecessary stringified results over using the existing Map functionality of DynamoDB. Surely this isn't the intended behaviour.

### Steps To Reproduce:
Store any object using DynamoDB. You get unnecessarily awkward input to work with. Especially if you use this cache for other non-PHP/non-Laravel related applications. Example below:

`a:7:{s:2:"id";i:1;s:8:"username";s:13:"xyz";s:5:"email";s:33:"xyz@xyz.io"....;}`

### Potential Solution???
Since Laravel already uses the `aws-sdk-php` packages i.e `Aws\DynamoDb\DynamoDbClient`, why not make use of the marshaler - `Aws\DynamoDb\Marshaler` - that comes with it and support Maps and data types beyond string and integer, which is all I can see within the current serialization function. 

Just something incredibly basic that I already have working in my own project but an example nonetheless.

#### Put - DynamoDbStore.php
```php 
$marshaler = new Marshaler();

// INSERT IF TYPE - Marshal and Map???
$value = ['M' => $marshaler->marshalItem($value)];
// INSERT ELSE - Default Serialize???
//$value = [$this->type($value) => $this->serialize($value)];

 $this->dynamo->putItem([
  'TableName' => $this->table,
  'Item' => [
      $this->keyAttribute => [
          'S' => $this->prefix . $key,
      ],
      $this->valueAttribute => $value,
      $this->expirationAttribute => [
          'N' => (string) $this->toTimestamp($seconds),
      ],
  ],
]);
```

#### Get - DynamoDbStore.php
```php
  $marshaler = new Marshaler();
  $value = json_decode($marshaler->unmarshalJson($response['Item']));
```

I'm not 100% sure where to post this. It's something I started writing as a bug report and gradually ended up compiling into this long issue that probably more resembles a feature request by now, since I can't see any reference of DynamoDB maps anywhere. 

Perhaps it's a bug, perhaps it isn't advisable, perhaps it's not in line with the vision, or there's no intention to support or use the existing marshaler or DynamoDB Maps. 

Perhaps I'm over simplifying a functionality that requires far more than a surface level adjustment that I have the liberty to make because I know that's all I need it for.

Anyway - Thanks for your time, folks. Apologies if this is the wrong place for this, it's just an issue I encountered and spent much too long trying to figure out. Maybe if it's here it'll help someone else if they encounter this same problem.

**Comment by driesvints** [comment]
Just to be clear: this is the DynamoDB cache driver you're working with?

**Comment by LiamMcLeodNDL** [comment]
It is indeed, yes. I use multiple stores for my project. Dynamo being one of them.

```php
Cache::store('dynamodb')->put($key, [...$data]);
````

I'm sure you don't need to know, but this is how it gets called within the context of my project.

**Comment by LiamMcLeodNDL** [comment]
I feared that would be the case. 😬 

I very much lack the "under the hood" knowledge to contribute in any meaningful capacity beyond what has been shared in my original post. But it's there for someone who may want to take up the challenge I suppose.

Thank you for your time, dude. Keep doing what you do! All the best. ✊
