### ISSUE TITLE
using File::types(['p12', 'pfx']) in as validation rules will reject valid .pfx file

### ISSUE THREAD

**Issue by rabol** [laravel/framework#45921]
- Laravel Version: 9.50.0
- PHP Version: 8.1.3
- Database Driver & Version:
mysql v 8.0.27
### Description:
When using the File::types() method in the rules of a FormRequest or validator, it reject valid files

### Steps To Reproduce:

repo to reproduce: https://github.com/rabol/filetypebug.git
code is in /routes/web.php

storage folder contains a valid pfx file

A new file can be generated like this:

```bash
openssl req -x509 -newkey rsa:4096 -sha256 -keyout storage/filetypebug.key -out storage/filetypebug.crt -subj "/CN=Test Certificate /OU=FileTypeBug" -days 600 -passout pass:123456
```

```bash
openssl pkcs12 -export -name filbug.test -out storage/filetypebug.pfx -inkey storage/filetypebug.key -in storage/filetypebug.crt -passin pass:123456 -passout pass:123456
```

**Comment by driesvints** [comment]
Hi. You're trying to validate by mime type, not by file extension. Try:

```php
$validator = Validator::make($request->all(), [
    'pfxfile' => ['required', 'file', File::types(['application/x-pkcs12'])],
]);
```

**Comment by rabol** [comment]
Not really sure why you closed this issue: your suggestion does not work.

And the doc state that one should use the extension, and on top of the extension the rule would read the file and validate the mime type

https://laravel.com/docs/9.x/validation#validating-files-file-types

and the list of extension for the different mime types:

https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
