### ISSUE TITLE
bug with nested conditional rules in validation

### ISSUE THREAD

**Issue by zserhiy** [laravel/framework#45940]
- Laravel Version: 9.50.2
- PHP Version: 8.1
- Database Driver & Version: any

### Description:
When conditional rules (Rule::when) are nested, we get error "Object of class Illuminate\Validation\ConditionalRules could not be converted to string"

### Steps To Reproduce:
```
class TestRequest extends FormRequest
{
    public function rules()
    {
        return [
            'test' => Rule::when(true, ['nullable', Rule::when(true, 'bail')]),
        ];
    }
}

```

**Comment by driesvints** [comment]
I'm gonna on a hunch and say this isn't supported I'm afraid. Maybe you can send in a PR so this is supported?
