### ISSUE TITLE
CROSS JOIN not working in query builder

### ISSUE THREAD

**Issue by AnoplexAdmin** [laravel/framework#45955]
Hello, I'm seeing an issue in Laravel 8.83.26 where the crossJoin method in the Query Builder returns no results, while the same query in plain SQL returns the expected results. 

This returns nothing...

`DB::table('t1')->crossJoin('t2')->where('t1.c1', 't2.c2')->select('t1.*', 't2.*')->get();`
   
Output: `select 't1'.*, 't2'.* from  't1' cross join 't2' where 't1'.'c1' = 't2'.'c2'`
   
This works fine...   

`DB::select('SELECT t1.*, t2.* FROM t1 CROSS JOIN t2 WHERE t1.c1 = t2.c2');`

Output: `SELECT t1.*, t2.* FROM t1 CROSS JOIN t2 WHERE t1.c1 = t2.c2`

Any help is much appreciated.  Haven't had any trouble using joins in the query builder before this issue.

**Comment by staudenmeir** [comment]
Use `whereColumn()`:

```php
DB::table('t1')->crossJoin('t2')->whereColumn('t1.c1', 't2.c2')->select('t1.*', 't2.*')->get();
```

`where()` compares a column with a value, but you want to compare two columns.

**Comment by AnoplexAdmin** [comment]
I thought of that too, but 
`->where('t1.c1', 't2.c1')`
Also returned no results, while `WHERE t1.c1 = t2.c1`. works fine.  

And you can see the SQL output from the query builder is the same as the raw SQL output except with inserted backticks.

**Comment by staudenmeir** [comment]
> `->where('t1.c1', 't2.c1')`
> Also returned no results

`->where()` or `->whereColumn()`?

**Comment by AnoplexAdmin** [comment]
`->where()`  - comparing the same column - c1.

**Comment by AnoplexAdmin** [comment]
> > `->where('t1.c1', 't2.c1')`
> > Also returned no results
> 
> `->where()` or `->whereColumn()`?

`whereColumn()` works.  Thanks.  t1.c1 and t2.c1  is a different column since it's in a different table.  Same column name != same column.  My fault.

Still don't get why the same SQL output between the query builder and raw SQL returns different results.

**Comment by gashra-aecor** [comment]
@AnoplexAdmin 
Have you used this?
`->where('t1.c1',\DB::raw( 't2.c2') )`

**Comment by ghanu119** [comment]
@AnoplexAdmin 
Have you used this?
`->where('t1.c1',\DB::raw( 't2.c2') )`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
