### ISSUE TITLE
Mockery related regression?

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#45978]
- Laravel Version: 9.50.2
- PHP Version: 8.1.14

### Description:

I'm not sure when that happened (in last two months I guess), but my tests stopped working because of missing Mockery package. For example a simple test containing:
```
$this->artisan('discounts')->assertExitCode(0);
```
gives now:
```
Error: Class "Mockery" not found
/.../vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:370
/.../vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:293
/.../vendor/laravel/framework/src/Illuminate/Testing/PendingCommand.php:481
/tests/Feature/MyTest.php:129
```

I understand the error. Problem is that it used to work before with some older 9.x versions. And I was never requiring `mockery/mockery` in my composer.json file.

So, when that changed? Is it documented? Should such a simple test require mockery or is it a bug?

**Comment by driesvints** [comment]
Heya, what version of PHPUnit have you got running?

**Comment by alecpl** [comment]
9.6.3.

**Comment by driesvints** [comment]
I'm not sure why you're now required to use Mockery. I've traced back the requirement all the way to 2018 so unsure why you weren't required to use it before... Right now it seems like a simple fix by requiring mockery in your composer.json so going to let this one rest.

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Testing/PendingCommand.php#L370

**Comment by alecpl** [comment]
Fair enough, maybe indeed some of my dependencies required it before. That being said, maybe Laravel documentation should be more clear about it. Even the Testing/Mocking section does not say you have to require Mockery on your own. "These helpers primarily provide a convenience layer over Mockery so you do not have to manually make complicated Mockery method calls." suggests the same.

**Comment by driesvints** [comment]
@alecpl I guess it's because by default you have Mockery in your skeleton when you start a new app. Maybe you can attempt to send in a PR to the docs if you feel it would make things more clear?
