### ISSUE TITLE
$table->foreignIdFor() migration references wrong table/model

### ISSUE THREAD

**Issue by ppshobi** [laravel/framework#45972]
- Laravel Version: 9.50.2  
- PHP Version: 8.2.1
- Database Driver & Version:MySQL 8

### Description:
```php
Schema::create('cattle', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(\App\Models\Cattle::class, 'mother_id')
                         ->nullable()
                         ->constrained()
                         ->nullOnDelete(); // self referencing foreignId
});
```
when this migration is run, it produces the following error

>  SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'mothers' (SQL: alter table `cattle` add constraint `cattle_mother_id_foreign` foreign key (`mother_id`) references `mothers` (`id`) on delete set null)

Even though the model given was `\App\Models\Cattle::class`, but without the `->constrained()` call, the migration works fine.

### Steps To Reproduce:
1. $ php artisan make:model Cattle -m
2. update the migration file with code sample from description
3. run migration

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
