### ISSUE TITLE
updateOrCreate method bug

### ISSUE THREAD

**Issue by davidistores** [laravel/framework#45975]
- Laravel Version: 9.43
- PHP Version: 8.1
- Database Driver & Version:

### Description:
There is an issue while using updateOrCreate method,
for example code

`self::query()->updateOrCreate(
            ['condition1' => $condition1, 'condition2' => $condition2],
            ['value' => $value]
        )`

In this case I want to find rows match the **_condition1_** and **_condition2_** and update if exist or create new with them and the value.
this works great, unless one case
if the _**$primaryKey**_ variable inside the model equals '**_condition1_**' for example so when the method doing update action it is updating all the rows matching the condition1 and ignoring the **_condition2_**.

when I chane the **_$primaryKey_** to something else that not one of the **_updateOrCreate_** condition it works great (for example column named "id" or etc...)

I tried to dig dipper and got some similiar issues while doing
`$variable = self::query()->where(['condition1' => 1, 'condition2' => 2])->first();`

the result that assigned to the **_$variable_** does contains the first result match instacne.
but in some cases then you use this techniq and then continue to update rows like:

`        $variable = self::query()->where(['condition1' => 1, 'condition2' => 2])->first();
        $variable->colum1 = 'column1';
        $variable->colum2 = 'columns';
        $variable->save();`
        
       in some cases it is ovveriding a lot of rows on save() and not only the first match (and I saw you use this inside the updateOrCreate() so I assume there is connection for this issues not)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
