### ISSUE TITLE
Global scopes and automatic resolver

### ISSUE THREAD

**Issue by JerryBels** [laravel/framework#45981]
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0.32

### Description:
When having a global scope with joins, like : 

```php
class SomeScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        if(session()->has('providers')) {
            $builder
                ->select('users.*')
                ->join('providers', 'users.provider_id', '=', 'providers.id')
                ->whereIn('providers.id', session()->get('providers')->pluck('id'));
        }
    }
}
```

we get `SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous`. Indeed, in the query, the `User`'s id is called directly, without qualifying the column, so the DB engine can't know it's the user's id since there is a join. So calling the regular route to show the user won't work. `public function show(User $user)` will throw.

Now, if we overwrite the `getRouteKeyName` function in the `User` model : 

```
public function getRouteKeyName()
    {
        return $this->getQualifiedKeyName();
    }
```

It does work, BUT now every route defined with the full `$user` model as attribute won't. `route('users.show', $user)` will throw `Missing required parameter for [Route: users.show] [URI: users/{user}] [Missing parameter: user]`. Indeed, if we take a look at `\Illuminate\Database\Eloquent\Concerns\HasAttributes::getAttribute` it searches for `array_key_exists($key, $this->attributes)` : a key matching the NOT QUALIFIED column name. So, looking for `users.id` it fails. 

One solution is simply not to define routes like that, and always do `route('users.show', $user->id)`. But still, it's a bug.

### Steps To Reproduce:

- Add a global scope including joins to a model.
- Bind this model to a route.
- Try to reach that route.

**Comment by driesvints** [comment]
The use case you want is unfortunately not supported. I can't currently see a way how this ever would work, sorry.

**Comment by JerryBels** [comment]
@driesvints I'm sorry but I don't understand why it wouldn't be supported, isn't it just basic behavior of core elements? Or, if global scopes aren't supposed to support joins, maybe it should be mentionned in the doc? Or is there a deeper issue I can't see?

**Comment by driesvints** [comment]
This just seems like a non supportive use case sorry. The error shows this can't be done.

**Comment by JerryBels** [comment]
@driesvints I'm sorry if it's a bother, but I would really like to know if there is a deeper issue. Defining 

```
public function getRouteKeyName()
    {
        return $this->getQualifiedKeyName();
    }
```

On my model and then only calling route with `user-id` parameter definitely works. Do I setup myself for further trouble that way or would you say it's fine, except for the fact I'm losing the ability to use routes in a specific way for that model? I can see an issue rising in the future if I'm using a package that relies on that route syntax for example... what do you think, is it a bad idea?
