### ISSUE TITLE
[9.x] Facade Fakes lose macros

### ISSUE THREAD

**Issue by stevebauman** [laravel/framework#45986]
- Laravel Version: v9.50.2 
- PHP Version: v8.1.14
- Database Driver & Version: N/A

### Description:

I'm attempting to extend Laravel's `Event` facade with additional macros for an application feature.

However, during testing, these macros are lost and cannot be called after calling `Event::fake()`, due to the instance being swapped out with a new implementation.

### Steps To Reproduce:

For example:

```php
Event::macro('bundle', fn (Bundleable $event) => (
    Bundle::add($event)
));

Event::macro('assertBundled', fn ($event) => (
    Bundle::assertExists($event)
));
```

In the test:

```php
Event::fake(SomeEventToFake::class);

// Do something...

Event::assertDispatched(SomeEventToFake::class);

Event::assertBundled(SomeOtherEvent::class); // Throws exception
```

### Solution

With all "fake" implementations, we could forward missing method calls back onto their root instances that are `Macroable`, which allows the macros to be accessible:

```php
// src/Illuminate/Support/Testing/Fakes/EventFake.php

class EventFake implements Dispatcher
{
    use ForwardsCalls;

    // ...

    /**
     * Handle dynamic method calls to the dispatcher.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        return $this->forwardCallTo($this->dispatcher, $method, $parameters);
    }
}
```

I can submit a PR with this added, but wanted to get everyones thoughts on this, and whether this behaviour is intentional and whether I'm using macros in an incorrect way.

Thanks so much for your time! ❤️

**Comment by driesvints** [comment]
Heya. This just doesn't seems possible right now. Seems you already sent in a PR so let's see how it goes 👍
