### ISSUE TITLE
Blueprint: Foreign id definition sets incorrect table name when renaming table

### ISSUE THREAD

**Issue by nandi95** [laravel/framework#46013]
- Laravel Version: 9.46.0
- PHP Version: 8.1.14
- Database Driver & Version: mysql - 8.0.31

### Description:
If you trying to rename a table and add a foreign index in the same closure within Schema::table the generated alter table statement will be using the incorrect old name.

It has an easy work around (just don't rename in the same callback but, no harm in reporting it.

### Steps To Reproduce:

```php
// have existing tables
Schema::create('products', static function (Blueprint $table) {
    $table->id();
});
Schema::create('features', static function (Blueprint $table) {
    $table->id();
});

// alter the features table and reproduce the bug
Schema::table('features', static function (Blueprint $table) {
    $table->rename('product_features');
    $table->foreignId('product_id')
        ->references('id')
        ->on('products');
});
```
This will yield
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my-schema.features' doesn't exist (SQL: alter table `features` add constraint `features_product_id_foreign` foreign key (`product_id`) references `products` (`id`))
```

**Comment by anilkumarthakur60** [comment]
```
Schema::table('features', static function (Blueprint $table) {
    $table->rename('product_features');
});
Schema::table('product_features', static function (Blueprint $table) {
    $table->foreignId('product_id')
        ->references('id')
        ->on('products');
});

```

make separate migrate this might work for you

**Comment by driesvints** [comment]
You'll need separate migrations for this.

**Comment by nandi95** [comment]
> It has an easy work around (just don't rename in the same callback but, no harm in reporting it.

I am aware of the workaround, hence why the above is in the description.
I take it this means, no plan on fixing this?
