### ISSUE TITLE
Problem with cast and validation

### ISSUE THREAD

**Issue by skalero01** [laravel/framework#46012]
- Laravel Version: 9.45.1
- PHP Version: 8.1.4
- Database Driver & Version: mysql 8.0.19

### Description:
Apparently when we have casts the validation stop working.

### Steps To Reproduce:

Have this model
```php
class Invoice extends Model
{
    protected $guarded = [];
    protected $casts = [
        'is_completed' => 'boolean',
        'is_paid' => 'boolean',
        'finished' => 'boolean',
        'is_related' => 'boolean',
        'has_file' => 'boolean',
        'paid_at' => 'datetime:Y-m-d',
        'value' => 'double',
    ];
```

And executed this on Tinker
```php
> $invoice = App\Models\Invoice::find(21553);
= App\Models\Invoice {#5636
    id: 21553,
    number: "asdasdasd",
    file: null,
    value: 115.52,
    value_with_vat: 113.0,
    is_completed: 0,
    issue_date: null,
    due_date: null,
    currency_code: "MXN",
    provider_id: 1,
    company_id: 1,
    payment_term_id: 1,
    payment_method_id: 1,
    paid_at: null,
    created_at: "2023-02-07 16:27:16",
    updated_at: "2023-02-07 16:27:25",
  }

> $invoice->value = 'asdasd';
= "asdasd"

> $validator = Validator::make($invoice->toArray(), ['value' => 'required|numeric']);
= Illuminate\Validation\Validator {#6049
    +customMessages: [],
    +fallbackMessages: [],
    +customAttributes: [],
    +customValues: [],
    +excludeUnvalidatedArrayKeys: true,
    +extensions: [],
    +replacers: [],
  }

> $validator->fails()
= false
```

if i do the same but remove the casts of Value on the model i get the next response
```php
> $invoice = App\Models\Invoice::find(21553);
= App\Models\Invoice {#5636
    id: 21553,
    number: "asdasdasd",
    file: null,
    value: 115.52,
    value_with_vat: 113.0,
    is_completed: 0,
    issue_date: null,
    due_date: null,
    currency_code: "MXN",
    provider_id: 1,
    company_id: 1,
    payment_term_id: 1,
    payment_method_id: 1,
    paid_at: null,
    created_at: "2023-02-07 16:27:16",
    updated_at: "2023-02-07 16:27:25",
  }

> $invoice->value = 'asdasd';
= "asdasd"

> $validator = Validator::make($invoice->toArray(), ['value' => 'required|numeric']);
= Illuminate\Validation\Validator {#6049
    +customMessages: [],
    +fallbackMessages: [],
    +customAttributes: [],
    +customValues: [],
    +excludeUnvalidatedArrayKeys: true,
    +extensions: [],
    +replacers: [],
  }

> $validator->fails()
= true
```

Does somebody know what happens here? I think the casts is being made before the validation, but not sure why or if we have already other way to do this validation.

Regards

**Comment by klynicol** [comment]
It is cast before the validation. Casting happens during the `toArray()` phase. Can you provide more context into why you'd use something like this?

**Comment by skalero01** [comment]
Hi @klynicol of course. I am using Livewire to update Models, so on this case i make the changes directly to the object and after the validation I just save the object with the changes. But with this error it cannot work like that.

Reference to Livewire: https://laravel-livewire.com/docs/2.x/properties#binding-models 

Thanks!

**Comment by klynicol** [comment]
Yes I see how that could be frustrating. I think most would agree that casting on `toArray()` is very much intentional, so there's no changing that. I would suggest creating your own trait and then use it at the top of models you wish to check before casting.

```
trait ToArrayIgnoreCast
{
    public function toArrayIgnoreCast()
    {
        $attributes = [];
        foreach ($this->getAttributes() as $key => $value) {
            $attributes[$key] = $value;
        }
        return $attributes;
    }
}
class Invoice extends Model{
    use ToArrayIgnoreCast;
}
```

Hope it helps.

**Comment by hschimpf** [comment]
What about using `Model::getAttributes()` instead ?
```php
$validator = Validator::make($invoice->getAttributes(), ['value' => 'required|numeric']);
```

**Comment by skalero01** [comment]
Yeah, i agree with [hschimpf](https://github.com/hschimpf) its easier just using $invoice->getAttributes(), ok, so i guess this could be improved on Livewire side instead of Laravel side. This makes sense

**Comment by driesvints** [comment]
Thanks all
