### ISSUE TITLE
Memory Leak when running anonymous class migrations in PHPUnit test

### ISSUE THREAD

**Issue by dbohn** [laravel/framework#46029]
- Laravel Version: 9.51.0
- PHP Version: 8.2.2
- Database Driver & Version: SQLite 3.37.2

### Description:

During the update of our codebase, we migrated our migration files to the new anonymous class system. When running our tests, we noticed, that our tests were consuming much more memory, to the point, that the tests started to fail.
When reverting the change, we noticed, that the memory consumption dropped to an acceptable level again.

### Steps To Reproduce:

You can find a reproduction here: https://github.com/dbohn/laravel-anonymous-class-migration-report

It runs a lot of migrations and a lot of test cases to illustrate the impact of the memory issue, in the first execution round using the new migration style, and afterwards the same test cases with the old migration style.

When executing the `run.sh` script in the repository, we observe the following results:

![image](https://user-images.githubusercontent.com/166164/217543713-4dedad4c-5726-48ee-a301-887dd1b2bfb2.png)

The top shows the anonymous class migrations, the bottom show the classic migrations. The only difference between the migrations is the definition style. Which shows, that the legacy syntax only consumes 15% of the memory.

**EDIT**: I noticed, that I still had xdebug enabled (it was a long debugging session to isolate this), so the numbers (especially the execution time) were a bit higher. Here is another screenshot with PHP 8.2.2 without xdebug:

![image](https://user-images.githubusercontent.com/166164/217546811-08fb3887-4095-412e-8cda-1e16d0002e1f.png)

I also switched to PHP 8.1 to check if it is an error with PHP 8.2, but there is a similar difference in memory consumption:

![image](https://user-images.githubusercontent.com/166164/217546227-15e662c9-4abc-4e42-8150-4cbd8bb896e9.png)

**Comment by phh** [comment]
I changed my migrations back to named classes instead of anonymous and it was much faster and using less memory.

Before: 
`Time: 00:12.996, Memory: 116.50 MB`

After:
`Time: 00:07.089, Memory: 104.50 MB`

**Comment by rojtjo** [comment]
The issue seems to be happening in the [`Migrator` on line 514](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Migrations/Migrator.php#L514).

[This change](https://github.com/rojtjo/framework/commit/18cbc8087111c0d738bdcea78277d56a0f42df74) would fix the memory issue, but I don't think a static property is the answer here. It would also mean that migrations that use additional state would no longer start with a clean slate for a new test.
