### ISSUE TITLE
Inconsistency in migrations when DBAL is used

### ISSUE THREAD

**Issue by asiral** [laravel/framework#46024]
- Laravel Version: 9.50.1
- PHP Version: 8.1.14
- Database Driver & Version: MariaDB 10.6.11

### Description:
I have multiple database connections configured in my application.  I have also configured a separate connection for migrations and that user has the necessary elevated privileges to perform these types of queries.

Laravel supports defining the database connection to use as a property of the `Migration` class.  When writing migrations for the various databases we have configured, we use this connection property and also specify the database with the table name.

When a migration requires DBAL, the specification of the database is ignored and the database of the `$connection` property is used.

### Steps To Reproduce:

```
return new class extends Migration
{

    //database connection, configured with a different database name (e.g. new_database) than below (database_name)
    protected $connection = 'migrations';

    public function up()
    {
        //will work because does not use DBAL
        Schema::table('database_name.table_name', function (Blueprint $table) {
            $table->boolean('new_column');
        });
        //will not work, database is ignored when passed to DBAL
        Schema::table('database_name.table_name', function (Blueprint $table) {
            $table->boolean('new_column')->default(0)->change();
        });
    }

};
```

An example database configuration (config/database.php) for added clarity:

```
return [
    'connections' => [
        'migrations' => [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'new_database',
            //this user also has required privileges on 'database_name' below
            'username' => 'migrations_user',
            'password' => '*****',
            'unix_socket' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null
        ],
        'main' => [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => '3306',
            'database' => 'database_name',
            'username' => 'database_user',
            'password' => '***',
            'unix_socket' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
        ]
    ]
];
```

This will produce the error that the column does not exist, because it checks for the column on the table in the default database for the `migrations` connection.

```
 Doctrine\DBAL\Schema\Exception\ColumnDoesNotExist 

  There is no column with name "new_column" on table "table_name".

  at vendor/doctrine/dbal/src/Schema/Exception/ColumnDoesNotExist.php:16
```

**Comment by hafezdivandari** [comment]
I understand that it may not be possible for you atm, but one solution is to upgrade to Laravel 10.x and remove `doctrine/dbal` package.

**Comment by driesvints** [comment]
Please try the suggestion by @hafezdivandari

**Comment by asiral** [comment]
The issue still persists in the latest Laravel release, 10.14.1.

**Comment by hafezdivandari** [comment]
@asiral As I said before, You may remove `doctrine/dbal` package or call `Schema::useNativeSchemaOperationsIfPossible()` method within the `boot` method of your `App\Providers\AppServiceProvider` class.
