### ISSUE TITLE
Running PHP Stan having conflict with Laravel Breeze's VerifyEmailController file

### ISSUE THREAD

**Issue by kpebron** [laravel/framework#46022]
- Laravel Version: 9.48.0
- Laravel Breeze: 1.18.0
- PHP Version: 8.0.2
- Database Driver & Version:

### Description:
When running PHPStan to check bugs, it is returning error `Parameter #1 $user of class Illuminate\Auth\Events\Verified constructor expects  Illuminate\Contracts\Auth\MustVerifyEmail, App\Models\User|null given.`

Checking on the Illuminate\Auth\Events\Verified class, method __construct expects a @param \Illuminate\Contracts\Auth\MustVerifyEmail  $user but in VerifyEmailController sends `$request->user()`

### Steps To Reproduce:

install phpstan and run `./vendor/bin/phpstan analyse --memory-limit=1G; composer dump-autoload`

I know this is a very minor bug.

**Comment by kpebron** [comment]
I am still new to breeze so I dont know how this will affect the overall code.

**Comment by driesvints** [comment]
Heya, a PHPStan issue is not a bug so please feel free to send in a PR if you like.
