### ISSUE TITLE
Incompatible polymorphic relationship with new "through" builder

### ISSUE THREAD

**Issue by Sammyjo20** [laravel/framework#46031]
- Laravel Version: v9.51.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.?

### Description:

I have just updated my composer dependencies which installed v9.51.0 of the framework, and I'm now getting an error with my "MorphTo" relationship. This works in the previous release (v9.50.2)

```php
public function through(): MorphTo
{
    return $this->morphTo();
}
```

Error: 

![Screenshot 2023-02-08 at 14 35 11](https://user-images.githubusercontent.com/29132017/217560217-7a0300ad-f7f9-476a-aa24-21a24dc7ffdd.png)

I believe this may have been caused by: https://github.com/laravel/framework/pull/45894 but I'm not certain.

### Steps To Reproduce:

Try to add a relationship like mine, and run `composer test` or try to interact with the model. PHP should throw an incompatibility error.

**Comment by Sammyjo20** [comment]
Ah, I think it's because my relationship name is `through`. I will close for now.

**Comment by timacdonald** [comment]
Sorry you ran into this Sammy. Looks like it is an unfortunate naming collision on this one.

**Comment by Sammyjo20** [comment]
No worries Tim, thank you for building a cool feature. We were able to fix it quite quickly!
