### ISSUE TITLE
Savepoint not released in nested transactions

### ISSUE THREAD

**Issue by korkoshko** [laravel/framework#46040]
- Laravel Version: 9.50.1
- PHP Version: 8.1.14
- Database Driver & Version: MySQL 5.7

### Description:
Hi! 
Is there any reason why the `commit` [method](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Concerns/ManagesTransactions.php#L192)  doesn't release the `savepoint` if the transaction is nested ?  Without using `release savepoint` we can rollback the savepoint (via  raw pdo connection) even if the nested transaction was committed with the `commit` method. Certainly, all savepoints are automatically deleted after the main transaction is commited, so that's  not a problem, but being able to rollback savepoint after commit is a strange. 

Popular ORMs such as Doctrine in PHP or TypeORM in Typescript use `savepoint release` when committing nested transactions.

### Steps To Reproduce:
```PHP
 \DB::transaction(static function () use ($user) {
        $user->update(['created_at' => '2023-02-08 00:00:00']);

        \DB::transaction(static fn () => $user->update(['created_at' => '2024-01-01 00:00:00']));

        \DB::getPdo()->exec('rollback to savepoint trans2');
    });
```
**Expected behavior:**  `PDOException` with message `SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans2 does not exist`

**Current behavior**:  successfuly rollback to savepoint 'trans2'.

**Comment by driesvints** [comment]
Seems like we don't want to change this right now, sorry.
