### ISSUE TITLE
Laravel cors problem

### ISSUE THREAD

**Issue by soixt** [laravel/framework#46059]
Laravel Version: 9.51.0  
PHP Version: 8.1.3  
Composer Version: 2.4.4  
Environment: local  
Debug Mode: ENABLED  
URL: dev.my-domain.app  
Maintenance Mode: OFF

Not sure if this could be nginx configuration issue or I have some problem no one can answer on forums :smiley: 

Anyway, I keep getting:

`Access to XMLHttpRequest at 'https://dev.my-domain.app/storage/files/DWvHfglNXOlppAVv77fhQAz6fcfzDOz8klZF58Yc.png' from origin 'https://user-1.dev.my-domain.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Now I tried:
Editing `cors.php` config with clearing the config cache:

```
return [
    'paths' => ['*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => ['*'],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,
];
```
I tried hard coding it in bootstrap/app.php:

```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: Origin, X-Requested-With,Authorization,  Content-Type, Accept');
```

I tried adding it to site nginx config:

```
location /storage/ {
    add_header Access-Control-Allow-Origin *;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, PATCH, DELETE';
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
}
```

But seems like nothing works, I am using stancl tenancy v3 but not sure if it has anything to do with that?

Also, SESSION_DOMAIN is set to .dev.my-domain.app, if that may cause a problem?
Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
