### ISSUE TITLE
`.env` cannot be parsed with some auto-generated database names

### ISSUE THREAD

**Issue by anafro** [laravel/framework#46065]
- Laravel Version: 9.51.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8.0.31

### Description:
After creating a new project via `laravel new "Sakurator (New)" --jet`, I got an error after trying to launch my application with `php artisan serve`:

```
The environment file is invalid!
Failed to parse dotenv file. Encountered unexpected whitespace at [sakurator (new)].
```

It seems like Laravel doesn't wrap the auto-generated database name with quotation marks or doesn't do something to get rid of the whitespaces, e.g. replacing them with dashes "-":

```
# Inside the .env
DB_DATABASE=sakurator (new)
```

### Steps To Reproduce:
1. Create a new project via `laravel new "Project name" --jet`. Make sure to leave a space inside the project name.
2. Try to run the server via `php artisan serve`

Probably Laravel should do some more manipulations with project name, probably wrapping the name with "<project-name>" or replacing spaces with dashes.
Probably the database name should be `sakurator-new` or `"sakurator (new)"` in the `.env`

**Comment by driesvints** [comment]
"sakurator (new)" indeed isn't a valid database name. I'd argue that `"Sakurator (New)"` isn't really a common name people choose for their project name. Usually that's a hyphened name like `sakurator-new`. I don't think we're going to take any action here right now sorry.
