### ISSUE TITLE
PaginatedResourceResponse skips paginating info when response

### ISSUE THREAD

**Issue by projct1** [laravel/framework#46083]
- Laravel Version: 7.30.6
- PHP Version: 7.4.29
- Database Driver & Version: MySQL 5.7.38

### Description:
```php
class SearchResource extends ResourceCollection
{
    public function toArray($request)
    {
        return $this->resource->map(function(stdClass $bar) {
            return [
                'id' => $bar->id,
                'name' => $bar->name
            ];
        });
    }
}

class SearchController extends Controller
{
    public function indexAction(Request $request)
    {
        $resource = DB::table('bars')->paginate();

        return [
            'bars' => new SearchResource($resource), // result without `links` and `meta`
            'bars1' => (new SearchResource(resource))->toResponse($request) // error
        ];
    }
}
```
- As result i got only collection (without paginator `links` and `meta`).
- When i try to add `toResponse`, got error `Undefined property: stdClass::$resource`.
- When i delete this code https://skr.sh/sILCemPB7FJ from `PaginatedResourceResponse` all works fine, but with unnecessary keys https://skr.sh/sILLJsr18pa

### Steps To Reproduce:
1) Create any ResourceCollection with `LengthAwarePaginator` as `$this->resource`;
2) In controller return as array (example above).

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
