### ISSUE TITLE
Migration's foreignIdFor() missing foreignUlid()

### ISSUE THREAD

**Issue by iamcarlos94** [laravel/framework#46082]
- Laravel Version: 10.x
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
When creating a new migration column using [foreignIdFor()](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Schema/Blueprint.php#L935), it doesn't account for the foreign key type ULID.

### Steps To Reproduce:
N/A

**Comment by driesvints** [comment]
We'd appreciate a PR to provide support for this.
