### ISSUE TITLE
Laravel 10 asset helper

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#46092]
- Laravel Version: in title
- PHP Version: na
- Database Driver & Version: na

### Asset helper all explained here: https://laracasts.com/discuss/channels/laravel/laravel-10-asset-helper
Basically instead of:
```
<link href="http://localhost/laravel10/assets/css/dog/style.css" rel="stylesheet">
```

you get:
```
<link href="/assets/css/dog/style.css" rel="stylesheet">
```
if clicked on
```
http://localhost/assets/css/dog/style.css
```
The laravel10 part is missing.

### Just use asset helper

Note I was just testing new version prior to release.

**Comment by rbarden** [comment]
Your issue seems to be coming from https://github.com/laravel/laravel/pull/6089 and not related to the framework itself. Though I'm still unsure of what your actual issue is.

**Comment by timacdonald** [comment]
For new applications, the default asset URL has changed. This can still be configured by removing the new default value in `config/app.php`.

You do not need to make this change when upgrading an existing application to Laravel 10.

**Comment by jimgwhit** [comment]
@timacdonald Thanks, I figured this out.  I wish you guys would remember it's a php framework, and not be so concerned about vite, which I do not use. But yes an easy fix in this case.
