### ISSUE TITLE
WithoutEvents trait fails due to missing withoutEvents() method

### ISSUE THREAD

**Issue by spaceemotion** [laravel/framework#46118]
- Laravel Version: 10
- PHP Version: 8.2.2
- Database Driver & Version: 8.0.32

### Description:
After upgrading to Laravel 10, a test of mine that uses the `WithoutEvents` trait, started to fail due to a missing `withoutEvents` method. 

```
Unable to disable events. ApplicationTrait not used.
```

The now missing method seems to have been included in a deprecated trait in laravel 9:

https://github.com/laravel/framework/blob/3bbc6c52477033e1f3d16ba84c673dac66e1b29c/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php#L101

The upgrade guide also does not mention the `WithoutEvents` trait being superseded by another.

Is this a dropped feature, or do I have to replace the trait with a method call?

**Comment by derekmd** [comment]
`$this->withoutEvents()` calls should be replaced with `Event::fake()`, `Event::fakeFor()`, etc.

The `MocksApplicationServices` trait has been marked `@deprecated` since the laravel/framework 8.x. The 10.x upgrade guide does mention its removal but the note doesn't mention `withoutEvents` by name: https://laravel.com/docs/10.x/upgrade#service-mocking

**Comment by korkoshko** [comment]
This method contained in the [MocksApplicationServices](https://github.com/laravel/framework/blob/3bbc6c52477033e1f3d16ba84c673dac66e1b29c/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php#L101) trait , which was [deprecated](https://github.com/laravel/framework/pull/36716)  in the 8.x and [removed](https://laravel.com/docs/10.x/upgrade#service-mocking) in version 10.x. You  just need  use `Event::fake `.

**Comment by spaceemotion** [comment]
Ah alright, thanks! I only searched for mention of the `WithoutEvents` trait.
