### ISSUE TITLE
Does not work with `laravel new example-application --pest`

### ISSUE THREAD

**Issue by brocard** [laravel/framework#46114]
Using version ^1.22 for pestphp/pest
./composer.json has been updated
Running composer update pestphp/pest --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pestphp/pest[v1.22.0, ..., v1.22.1] require nunomaduro/collision ^5.10.0|^6.0 -> found nunomaduro/collision[v5.10.0, v5.11.0, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - pestphp/pest[v1.22.2, ..., v1.22.4] require nunomaduro/collision ^5.11.0|^6.3.0 -> found nunomaduro/collision[v5.11.0, v6.3.0, v6.3.1, v6.3.2, v6.4.0] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires pestphp/pest ^1.22 -> satisfiable by pestphp/pest[v1.22.0, ..., v1.22.4].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require pestphp/pest:*" to figure out if any version is installable, or "composer require pestphp/pest:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by driesvints** [comment]
Are you on v4.4 of the installer?

**Comment by brocard** [comment]
Yep sorry upgrade the installer to v4.4, i dont know the first time that i executed `composer global update laravel/installer` doesn`t gotten new files
