### ISSUE TITLE
PHPStan failing to assert that filled() and blank() will never return nulls

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#46110]
- Laravel Version: 9.50.1
- PHP Version: 8.1.13

When analysing a Laravel application code using `filled()` or `blank()` PHPStan fails to understand that a call to `blank()` will never allow nulls to move forward (to parse_url) when testing it like this:

```php 
public function isUrl(string|null $url): bool
{
    if (blank($url)) {
        return false;
    }

   $parsed = parse_url($url); // PHPStan will flag that nulls cannot be passed here

   return is_array($parsed);
}
```

[The solution PHPStan folks found](https://github.com/phpstan/phpstan/issues/7607#issuecomment-1179710647) for this was to add an annotation to tell PHPStan this would not return null, but it seems it would need to be added at the framework level:

```php
/**
 * Determine if the given value is "blank".
 *
 * @param  mixed  $value
 * @return bool
 *
 * @phpstan-assert-if-false !null $value
 */
public function blank($value)
{
    ...
}
```

**Comment by driesvints** [comment]
Hi there. We don't consider PHPStan errors to be actual bugs. Please send in a PR if you want to change anything here. Thanks
