### ISSUE TITLE
Laravel 10 authentication issue 

### ISSUE THREAD

**Issue by parasshah438** [laravel/framework#46128]
- Laravel Version: v10.0.0
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
Run the npm run build command after showing this error.

![image](https://user-images.githubusercontent.com/47562591/219015340-0831d5cb-32c8-4dc6-8cd0-5a7e1f0ad02a.png)

### Steps To Reproduce:

I install fresh laravel 10 project and run this last command npm run build for authentication.

### Steps To Solved:

I find some solution for this issue
Go to /resources/js/bootstrap.js
replace that code import _ from 'lodash'   to   window._ = require('lodash');
Again run npm run build.

Please also share other solution

Thank you

**Comment by santigp258** [comment]
I think just installing the package would be enough, running:
```bash
npm run build
```

**Comment by lazer-hybiz** [comment]
@parasshah438 are you sure you installed a fresh laravel 10 project? I think laravel 10 does not have this line at all

**Comment by rodrigopedra** [comment]
- How is this related to authentication?
- As said by @santigp258 Laravel 10 does not ship `lodash`, it was removed from the skeleton 2 days ago, before Laravel 10 final release. https://github.com/laravel/laravel/pull/6095

**Comment by parasshah438** [comment]
> @parasshah438 are you sure you installed a fresh laravel 10 project? I think laravel 10 does not have this line at all

Yes I am installing a fresh laravel 10 version,
Go to this directory and check

resources/js/bootstrap.js (Line no 1st)

import _ from 'lodash';

Note : I also have some solution
1 : If I comment this line and run **npm run build** command it's working perfectly
2 : Also run command : **npm i lodash** it's working perfectly
Thank you

**Comment by rodrigopedra** [comment]
You might have installed one day before the final release. That line is not present anymore on new installs, since the PR linked above, and was never there since the 10.0 official release:

https://github.com/laravel/laravel/blob/ad279a61d1a5df6c98e8de667cd4ade18df52bed/resources/js/bootstrap.js#L1-L16

And before sending my answer I did check, both on the skeleton repository, and by installing a local version and running the `npm run build` command. In both places, there is no reference to `lodash`, as expected. 

Installing `lodash` will make it work, of course. If you are happy with this, then great.

But there isn't a current problem with neither `npm run build`, nor with ***authentication*** (which I am still curious how all this could be related)

**Comment by parasshah438** [comment]
> You might have installed one day before the final release. That line is not present anymore on new installs, since the PR linked above, and was never there since the 10.0 official release:
> 
> https://github.com/laravel/laravel/blob/ad279a61d1a5df6c98e8de667cd4ade18df52bed/resources/js/bootstrap.js#L1-L16
> 
> And before sending my answer I did check, both on the skeleton repository, and by installing a local version and running the `npm run build` command. In both places, there is no reference to `lodash`, as expected.
> 
> Installing `lodash` will make it work, of course. If you are happy with this, then great.
> 
> But there isn't a current problem with neither `npm run build`, nor with _**authentication**_ (which I am still curious how all this could be related)

@rodrigopedra

Yes now lodash is remover from package.json and bootstrap.js,
But when I run bellow command like
**php artisan ui bootstrap or vue or react**
then this code  **import _ from 'lodash';**  import in bootstrap.js
still same error show after **npm run build**

[vite]: Rollup failed to resolve import "lodash" from "/resources/js/bootstrap.js".

**Comment by driesvints** [comment]
I've released a patch version of UI so this should be fixed

**Comment by parasshah438** [comment]
> I've released a patch version of UI so this should be fixed

@driesvints 
Ok thank you so much.

**Comment by MirwaisFahim** [comment]
@parasshah438

thanks it worked
