### ISSUE TITLE
API Documentation ver 10

### ISSUE THREAD

**Issue by jimgwhit** [laravel/framework#46120]
- Laravel Version: 10
- PHP Version: na
- Database Driver & Version:na

### Steps To Reproduce:  Go to https://laravel.com/docs/10.x and click the API Documentation link.  Then change
```
https://laravel.com/api/9.x/

to

https://laravel.com/api/10.x/
```

And you get: 
404
Not Found

**Comment by tontonsb** [comment]
Those URLs seem to be working fine for me at the moment. Do you still have the problem?

**Comment by jimgwhit** [comment]
No, it is now fixed, thanks.
