### ISSUE TITLE
API Resource whenHas is undefined

### ISSUE THREAD

**Issue by codiant-manish-yadav** [laravel/framework#46125]
- Laravel Version: 9.45.1
- PHP Version: 8.1.6
- Database Driver & Version: mysql

### Description:
When I use `whenHas` method on UserResource it gives an undefined `whenHas` method error.

### Steps To Reproduce:

I have this UserResource

```
class UserResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'country' => $this->whenHas('country'),
        ];
    }
}
```
And if I execute it like
http://laravel9.test/users/2 then I got the below error
**Call to undefined method App\Http\Resources\UserResource::whenHas()**

**Comment by zeeshanmughaltherightsw** [comment]
You cannot call where has on a modal object $this is not a query builder instead it is a modal object it self thus you cannot call whereHas

**Comment by codiant-manish-yadav** [comment]
> You cannot call wherehas on a modal object. "$this" is not a query builder instead it is a modal object itself thus you cannot call whereHas using $this and thats why its throwing exception

I am using whenHas (not whereHas) which is documented here [https://laravel.com/docs/9.x/eloquent-resources#conditional-attributes](url)

**Comment by rojtjo** [comment]
You are using Laravel 9.45.1, but the `whereHas()` method was only added in Laravel 9.46.0. Just update your dependencies and it should work.

**Comment by falko100** [comment]
> You are using Laravel 9.45.1, but the `whereHas()` method was only added in Laravel 9.46.0. Just update your dependencies and it should work.
> 
> https://github.com/laravel/framework/blob/9.x/CHANGELOG.md#v9460---2023-01-03

You mean whenHas. 😉  On everything else it seems you are entirely correct.
