### ISSUE TITLE
Exception in CompilerEnginer.php

### ISSUE THREAD

**Issue by afridi315** [laravel/framework#46139]
- Laravel Version: 9.x and 10
- PHP Version: 8.x

### Description:
There is an exception regarding array offset in `CompilerEngine.php` file on line 61, whenever I run the `serve` command or try to access the app URL, it shows **Illegal offset type in `isset` or `empty`** error.

### Steps To Reproduce:
By replacing `! isset($this->compiledOrNotExpired[$path])` with `! isset($path)` resolved the issue but I don't think this is the valid solution.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
