### ISSUE TITLE
Cannot provide a list of attributes to a slot

### ISSUE THREAD

**Issue by julien-fontaine** [laravel/framework#46154]
- Laravel Version: 10.0.3
- PHP Version: 8.2.3

### Description:

When providing a ComponentAttributeBag to a slot using the _attributes_ attribute, the component bag is treated as a single attribute and its values are converted to string.

This does not happen when providing a ComponentAttributeBag to a Blade component using the _attributes_ attribute, it handles it as a list of attributes passed to the component.

### Steps To Reproduce:

A component like this one:
```php
<x-custom-component :attributes="new ComponentAttributeBag('', ['class' => 'demo-component'])">
    <x-slot name="demoSlot" :attributes="new ComponentAttributeBag('', ['class' => 'demo-slot'])"></x-slot-name>
</x-custom-component>
```
is rendered as:
```html
<div class="demo-component">
    <div attributes="class=\"demo-slot\""></div>
</div>
```
instead of expected:
```html
<div class="demo-component">
    <div class="demo-slot"></div>
</div>
```
### Why this is happening?

The issue comes from the method `\Illuminate\View\ComponentSlot::withAttributes`, which does not mimic the behavior of the method `\Illuminate\View\Component::withAttributes`.

### Possible fix:

```php
    // ./vendor/laravel/framework/src/Illuminate/View/ComponentSlot.php
    /**
     * Set the extra attributes that the slot should make available.
     *
     * @param  array  $attributes
     * @return $this
     */
    public function withAttributes(array $attributes)
    {
        $this->attributes = $this->attributes ?: new ComponentAttributeBag();

        $this->attributes->setAttributes($attributes);

        return $this;
    }
```
I can make a PR if needed.

**Comment by driesvints** [comment]
I don't think we support using ComponentAttributeBag directly and we don't document this anywhere. I'm sorry but this seems out of scope what you're trying to do.

**Comment by julien-fontaine** [comment]
@driesvints In fact I don't use ComponentAttributeBag directly, it's the type of the `$attributes` variables provided inside the Blade components' template, and the type of slots' `attributes` property.

Both of them are well documented:
* https://laravel.com/docs/10.x/blade#component-attributes
* https://laravel.com/docs/10.x/blade#slot-attributes

The behavior of `:attributes` is documented here: https://laravel.com/docs/10.x/blade#passing-data-to-components. This is how data is passed to component template.

I'm trying to pass down a list of attributes from a parent component slot to a child component slot.

After checking, it seems that data cannot be passed to a slot at all, and yes this behavior is not clearly documented for slots. I guess this is why we cannot do this...

**Comment by driesvints** [comment]
I don't see any usage of `:attributes` on that page.
