### ISSUE TITLE
Validate `after:1970-01-01` not works

### ISSUE THREAD

**Issue by ulcuber** [laravel/framework#46150]
- Laravel Version: 10.x
- PHP Version: 8.1

### Description:

Timestamp for `after:1970-01-01` = 0 which executes condition and sets `$date` to null then any not zero number is more than null

https://github.com/laravel/framework/blob/0bd303853444de33f4fcb16d13bd7574030aa3d4/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L252

### Steps To Reproduce:

Use validation rule `date|after:1970-01-01`

Expected to throw:

```php
validator(['date' => '0001-01-01T00:00'], ['date' => 'date|after:1970-01-01'])->validate()
```

**Comment by u01jmg3** [comment]
@driesvints: a PR was merged against this issue so perhaps it can be closed now?
