### ISSUE TITLE
Unused required parameter

### ISSUE THREAD

**Issue by bulentAkgul** [laravel/framework#46151]
- Laravel Version: 10.0.3
- PHP Version: 8.2.2

### Description:
The method down below expects a required argument despite the fact that it does nothing with it.

File: /Illuminate/Database/Query/Expression.php
```php
/**
 * Get the value of the expression.
 *
 * @param  \Illuminate\Database\Grammar  $grammar
 * @return string|int|float
 */
public function getValue(Grammar $grammar)
{
    return $this->value;
}
```

I've been using it as I'm going to show, but it doesn't work anymore.

```php
DB::raw(
    "DATE_FORMAT({$column}, '{$formatter}') as {$key}"
)->getValue();
```

**Comment by driesvints** [comment]
It's for grammars that overwrite the method.

**Comment by bulentAkgul** [comment]
Ok, but how to get value which is a protected property?

**Comment by driesvints** [comment]
It's in the upgrade guide: https://laravel.com/docs/10.x/upgrade#database-expressions
