### ISSUE TITLE
ULID column return all record when filter =1

### ISSUE THREAD

**Issue by akmalabaa99** [laravel/framework#46177]
- Laravel Version: 9.4.8
- PHP Version: 8.1
- Database Driver & Version: MySQL

### Description:
I have table with ULID as primary key.

### Steps To Reproduce:
When i filter the table like select * from ref_negara where id=1, it return all record. But it only happen with =1, if i changed it, it wont happen..

**Comment by hussonkevin** [comment]
You must re-open this ?! I think there is a security issue...
@akmalabaa99 have you found any solution ?
