### ISSUE TITLE
Type hint a bit broken for Query\Builder::leftJoin

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/framework#46171]
- Laravel Version: 10.0.3
- PHP Version: 8.2.1
- Database Driver & Version: irrelevant

### Description:

After upgrading to Laravel 10, the IDE complains that `Expression` object cannot be used for the first argument of `leftJoin`:
![image](https://user-images.githubusercontent.com/13980973/219961629-5a831c0a-593e-487f-9e28-dabe8349686e.png)

However this code works without any issues (and also worked in Laravel 9). Does it work by accident and this is not an intended use of this method or is there a mistake in the doc block?

**Comment by jonnywilliamson** [comment]
@KKSzymanowski - Probably linked: https://github.com/laravel/framework/pull/46160

**Comment by jerodev** [comment]
@jonnywilliamson Indeed, I have updated the PR to include join functions

**Comment by driesvints** [comment]
Thank you but we don't consider IDE warnings as bugs. We'd appreciate PRs for those and seems like one was sent in 👍
