### ISSUE TITLE
Mailable custom theme incorrectly applied

### ISSUE THREAD

**Issue by AEM5299** [laravel/framework#46179]
- Laravel Version: 9.51.0
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 5.7

### Description:
When a Mailable with a custom theme is sent before another Mailable with implicit default (`$theme = null`) in the same process (e.g., a queue), the second Mailable also gets the custom theme. As far as I can tell this happens because the [markdown renderer class is a singelton](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L325) and the theme is only updated [if it's **not null**](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L327).

If someone can confirm this is indeed not the intended behaviour, I can probably send in a PR. I have been trying to debug this for hours at this point so might be missing something trivial here.

### Steps To Reproduce:

1. Create a Mailable `MailableA` and set `public $theme = 'custom';`
2. Create another Mailable `MailableB` and don't set a theme (or set it to null)
3. Queue `MailableA` first then `MailableB` in the same queue and run the queue
4. `MailableB` will have the `'custom'` theme apllied, when it should be the default

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by AEM5299** [comment]
Bug report repo is here https://github.com/AEM5299/bug-report. If you run `php artisan serve` and visit the `/test` route, it will log both mails. In **both logged mails** you'll see that the body tag has a `style="background-color: salmon;"` while the `custom-theme` is **only** applied to `MailableA`

**Comment by driesvints** [comment]
I can confirm this. 

> As far as I can tell this happens because the [markdown renderer class is a singelton](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L325) and the theme is only updated [if it's not null](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Mail/Mailable.php#L327).

I don't think that's the cause. It's the markdown renderer that's a singleton, not the mailable.

I currently have no idea what the cause is here and would appreciate any insights or help

**Comment by AEM5299** [comment]
The markdown renderer is indeed the singelton, but the theme value is set on the Markdown renderer as well (not just the mailable, see [here](https://github.com/laravel/framework/blob/1e66370c68ef9fed7a2d82e30ea645061a5b02de/src/Illuminate/Mail/Mailable.php#L328))

**Comment by driesvints** [comment]
Hmm yeah but doesn't that gets set again every time `buildMarkdownView` is called?

**Comment by AEM5299** [comment]
It does, [but only if it's not `null`](https://github.com/laravel/framework/blob/1e66370c68ef9fed7a2d82e30ea645061a5b02de/src/Illuminate/Mail/Mailable.php#L327). And it's `null` [by default](https://github.com/laravel/framework/blob/1e66370c68ef9fed7a2d82e30ea645061a5b02de/src/Illuminate/Mail/Mailable.php#L166)

**Comment by driesvints** [comment]
Great catch. I did not see that. I guess the fix lies in setting the theme back to `null` right before we check the if statement. Can you send in a PR?

**Comment by AEM5299** [comment]
PR opened #46200.

**Comment by driesvints** [comment]
ks!
