### ISSUE TITLE
Cookie::queue() not working

### ISSUE THREAD

**Issue by AlinIonut** [laravel/framework#46182]
- Laravel Version: 10.0.3
- PHP Version: 8.2.1
- Database Driver & Version:

### Description:

Cookie::queue() it not working as intended.

### Steps To Reproduce:

`Route::get('/set', function () {
            Cookie::queue('test', 'foo', 10);
        });`

`Route::get('/get', function () {
            dd(Cookie::get('test'));
        });`

/get endpoint return null on cookie value after set.

The cookie value is set in plain text, not encrypted.

**Comment by driesvints** [comment]
Works for me on a fresh Laravel v10 install.

<img width="585" alt="Screenshot 2023-02-20 at 14 23 12" src="https://user-images.githubusercontent.com/594614/220120491-048cd821-f84b-46e6-9ab1-a79483e964bc.png">

**Comment by AlinIonut** [comment]
@driesvints  I have manage to pinpoint my particular issue, and reproduce it even on a fresh install.

Try add a throttle to the web group in kernel.

If the throttle is added as the first middleware in the group, you will reproduce the problem. If you add it after the EncryptCookies middleware, looks ok.

**Comment by driesvints** [comment]
@AlinIonut can you try a support channel first please?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
