### ISSUE TITLE
Argument #1 ($manager) must be of type Illuminate\Mail\MailManager

### ISSUE THREAD

**Issue by alexgaal** [laravel/framework#46180]
- Laravel Version: 10.0.3
- PHP Version: 8.2.0
- Database Driver & Version:

### Description:
We are using `Mail::fake` in a test and since we upgraded to Laravel 10 it's failing with following exception:

```
Illuminate\Support\Testing\Fakes\MailFake::__construct(): Argument #1 ($manager) must be of type Illuminate\Mail\MailManager, Illuminate\Support\Testing\Fakes\MailFake given, called in /var/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Mail.php on line 68
```

```
Mail::fake();
Mail::assertNothingSent();
expect(fn () => $votingCard->approveRequest())->not()->toThrow(\Symfony\Component\Mime\Exception\LogicException::class);
```

**Comment by driesvints** [comment]
This was changed here: https://github.com/laravel/framework/pull/46055 because of https://github.com/laravel/framework/pull/45988

@joelbutcher @stevebauman do you have any ideas here on how to fix this?

**Comment by joelbutcher** [comment]
@driesvints I can't replicate this... I've [written a test](https://github.com/laravel/framework/compare/10.x...joelbutcher:framework:test-mailable-sent) that that should cover this in the framework

**Comment by driesvints** [comment]
Thanks @joelbutcher. @alexgaal can you check this? ^

**Comment by joelbutcher** [comment]
I've [raised a PR](https://github.com/laravel/framework/pull/46181) for this, too

**Comment by joelbutcher** [comment]
@alexgaal @maloun96 if you run the following in tinker, what do you get?

```shell
> app('mail.manager')
```

The only thing I can think of is an incorrectly configured service provider binding that's causing `app('mail.manager')` to resolve to the `MailFake` class instead of `MailManager`.

**Comment by maloun96** [comment]
I believe it's because we declared multiple times:
```php
    protected function setUp(): void
    {
        parent::setUp();
        Mail::fake();
    }

    public function test_123(): void
    {
        Mail::fake();
```
Before it worked. Now we should declare only once

**Comment by driesvints** [comment]
@maloun96 that doesn't seems like valid code to me (even if it was working before).

**Comment by maloun96** [comment]
@driesvints indeed, legacy code...

**Comment by driesvints** [comment]
@alexgaal are you faking emails in a similar way?

**Comment by maloun96** [comment]
Tested with a fresh laravel app and still error.
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/8277264/220120878-a0852721-a42f-4631-8a4c-1609962b1d11.png">

**Comment by joelbutcher** [comment]
@alexgaal this is because your test uses `PHPUnit\Framework\TestCase` instead of `Tests\TestCase`

**Comment by maloun96** [comment]
True, thanks to all!

**Comment by joelbutcher** [comment]
@driesvints this issue raises a good point about testing though. If a facade implements a `fake` method that then builds an object based on that facade's root and returns it, any test suit that declares `Facade::fake()` more than once (like the above, `setUp` and then `testItDoesX` will break.

@taylorotwell Might it be worth covering this use-case in the [testing docs](https://laravel.com/docs/10.x/testing#main-content)?

**Comment by driesvints** [comment]
@joelbutcher I don't think we document using faking like that anywhere?

**Comment by alexgaal** [comment]
> @alexgaal @maloun96 if you run the following in tinker, what do you get?
> 
> ```shell
> > app('mail.manager')
> ```
> 
> The only thing I can think of is an incorrectly configured service provider binding that's causing `app('mail.manager')` to resolve to the `MailFake` class instead of `MailManager`.

Psy Shell v0.11.12 (PHP 8.2.0 — cli) by Justin Hileman
> app('mail.manager')
= Illuminate\Mail\MailManager {#5302}

> @alexgaal are you faking emails in a similar way?

We are using `Mail::fake` twice in different tests:
<img width="894" alt="Bildschirm­foto 2023-02-20 um 16 08 12" src="https://user-images.githubusercontent.com/12985989/220142356-26401201-646c-4796-a833-84b21343d00c.png">

**Comment by driesvints** [comment]
@alexgaal can you share the full test please?

**Comment by alexgaal** [comment]
@driesvints Sure!

```
test('missing emails do not cause a http 500', function () {
    /** @var VotingCard $votingCard */
    $votingCard = VotingCard::factory()
        ->for(
            Voter::factory()
                ->has(
                    Study::factory(['email' => ''])->for(
                        EducationalInstitutionFieldOfStudy::factory()
                            ->for(EducationalInstitution::factory())
                            ->for(FieldOfStudy::factory())
                    )
                )
        )->create();

    Mail::fake();
    Mail::assertNothingSent();
    expect(fn () => $votingCard->approveRequest())->not()->toThrow(\Symfony\Component\Mime\Exception\LogicException::class);
})->group('ewas', 'votings-cards');
```

**Comment by driesvints** [comment]
You're calling `Mail::fake();` multiple times in a single test because of the `collect->each`. That's not supported afaik.

**Comment by alexgaal** [comment]
Oh, thank you Dries! I fixed that, it's working now. Thanks to all of you.

**Comment by joelbutcher** [comment]
@alexgaal @driesvints I'm working on a PR to fix this

**Comment by driesvints** [comment]
Thanks all

**Comment by schonhoff** [comment]
Hi @joelbutcher,
I'm not into the Facade fake awareness but could this PR fix the problem with laravel-helo and ide-helper?
https://github.com/beyondcode/helo-laravel/issues/37
Maybe you have could have a look? Would be much appreciated :-) Just if you have the time to have a look into the issue. If not I will wait for the PR to be tagged and will try it myself.

Thanks and have a nice day/night.

**Comment by joelbutcher** [comment]
@driesvints @taylorotwell I think we need to consider documenting using `fake()` once in tests as since #46188 has caused quite a few issues with packages upgrading to Laravel v10?
