### ISSUE TITLE
What happened to the links for API documentation for laravel 8x and below?

### ISSUE THREAD

**Issue by projectmentor** [laravel/framework#46185]
- Laravel Version: 7.x
- PHP Version: 7.x
- Database Driver & Version: all

### Description:
The links to API documentation for laravel versions 8.x and below are no longer available from the url https://laravel.com/api/<major-version>.x/

If this was done on purpose, please kindly reconsider as having the documentation easily available for older versions of laravel is a lifeline for many working developers! 

### Steps To Reproduce:

1. browse to: `https://laravel.com/api/7.x`
2. see 404 error

**Comment by jonnott** [comment]
+1 to this! A lifeline indeed.

**Comment by WendellAdriel** [comment]
I'm not sure but it could be related to the Support Policy: https://laravel.com/docs/10.x/releases#support-policy
As you can see, from Jan 24th Laravel 8 reached its end of life.

**Comment by jonnott** [comment]
> I'm not sure but it could be related to the Support Policy: https://laravel.com/docs/10.x/releases#support-policy As you can see, from Jan 24th Laravel 8 reached its end of life.

I don't think a version reaching EOL in terms of support / fixes/ security patches necessarily justifies removing the documentation for it. It's not like there's any great maintenance overhead to keeping an old version documented in that way, is there?

**Comment by WendellAdriel** [comment]
> > I'm not sure but it could be related to the Support Policy: https://laravel.com/docs/10.x/releases#support-policy As you can see, from Jan 24th Laravel 8 reached its end of life.
> 
> I don't think a version reaching EOL in terms of support / fixes/ security patches necessarily justifies removing the documentation for it. It's not like there's any great maintenance overhead to keeping an old version documented in that way, is there?

I don't think it would be an overhead maintaining a website with the info. I just think it could be a way to encourage devs to update their applications. But this is all my own opinion. We would need to wait for a core team member to say something about this

**Comment by jonnott** [comment]
I am the hugest advocate of keeping everything as up to date as possible. I usually update to every new major (and minor) version of Laravel as soon as possible after they are released.

But unfortunately realities mean that real-world projects are often held up by dependencies, client needs, budgets, timescales, development priorities, etc which mean those upgrades can't happen as quickly as one would like.

For example, I am involved in projects running on L8.x still, which have upgrade branches for L9.x and now even L10.x, but they're waiting on combinations of these other factors..

**Comment by WendellAdriel** [comment]
> I am the hugest advocate of keeping everything as up to date as possible. I usually update to every new major (and minor) version of Laravel as soon as possible after they are released.
> 
> But unfortunately realities mean that real-world projects are often held up by dependencies, client needs, budgets, timescales, development priorities, etc which mean those upgrades can't happen as quickly as one would like.
> 
> For example, I am involved in projects running on L8.x still, which have upgrade branches for L9.x and now even L10.x, but they're waiting on combinations of these other factors..

I totally understand.
I was able to migrate our main API here at the company to Laravel 9 just some months ago :sweat_smile:

**Comment by dougd-unc** [comment]
I don't understand this either.  Removing documentation is not a good way to force people to upgrade, it's just a way to make it more difficult to support current sites.  I'm not sure how it makes any sense.

**Comment by mbabker** [comment]
Is there something special about that section of the website that you'd need over reviewing the source code?  All the `/api` section is is basically the doc blocks from all the classes transformed into a somewhat human-friendly interface, all the information still exists in your project's `vendor` folder.

**Comment by jonnott** [comment]
> Is there something special about that section of the website that you'd need over reviewing the source code? All the `/api` section is is basically the doc blocks from all the classes transformed into a somewhat human-friendly interface, all the information still exists in your project's `vendor` folder.

But it's searchable! That's the key. I suppose if this isn't going to be resolved, we could run Doctum locally ourselves..

**Comment by driesvints** [comment]
We got those docs back btw 👍
