### ISSUE TITLE
belongsToMany returns more (all) records than it should

### ISSUE THREAD

**Issue by liepumartins** [laravel/framework#46194]
- Laravel Version: 9.51.0, also 10.0.3, possibly more
- PHP Version: 8.1.0
- Database Driver & Version: mysql 8.0.27-0ubuntu0.20.04.1

### Description:
If belongsToMany relation is accesed `$model->relModels` from within a scope applied to other relation all records are returned.

```php

class User extends Authenticatable
{
    public function groups(): BelongsToMany
    {
        return $this->belongsToMany(Group::class);
    }
}
```

```php
class Item extends Model
{
    public function itemProperties(): HasMany
    {
        return $this->hasMany(ItemProperty::class)->scopes('forUser');
    }

    public function forcedItemProperties(): HasMany
    {
        return $this->hasMany(ItemProperty::class)->scopes('forcedUser');
    }
}
```

```php
final class ItemProperty extends Model
{

    public static function scopeForUser(Builder $builder): void
    {
        $user = auth()->user();
        if ($user) {
            $builder->whereIn('group_id', $user->groups->pluck('id'));
            // will display number of records in group_user table
            //dd($user->groups);
            Log::debug($user->groups);
        }
    }

    public static function scopeForcedUser(Builder $builder): void
    {
        $user = auth()->user();
        if ($user) {
            $builder->whereIn('group_id', $user->load('groups')->groups->pluck('id'));
            // will display correct number of records that actually belong to user
            //dd($user->groups);
            Log::debug($user->groups);
        }
    }
}
```

This shows way more itemProperties because in the scope `$user->groups` returned all groups instead of the groups user actually belongs to.
```php
$items = \App\Models\Item::with('itemProperties')->get();
foreach ($items as $item) {
        dump($item->itemProperties);
    }
```

### Steps To Reproduce:
Reproduced on fresh install
https://github.com/liepumartins/laravel-belongstomany-bug

**Comment by driesvints** [comment]
`$this->hasMany(ItemProperty::class)->scopes('forcedUser')`

I can't find a usage of this anywhere in our documentation so I don't think we support this. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by liepumartins** [comment]
Wait what? :)
`->scopes('myScope')` use on relationship definitions is not supported? It just happened to work by accident?

Apart from this case, use of scopes on has worked excellent, hard to believe this was not intended.

Thanks for looking into this!
