### ISSUE TITLE
Laravel 8 docs are missing a mention of date mutation changing to casting

### ISSUE THREAD

**Issue by aaronpk** [laravel/framework#46193]
- Laravel Version: 8

### Description:

I recently migrated a project from Laravel 7 to 10. I read through all the very helpful upgrade guides for each version incrementally. Once I was done, I was getting errors about some date properties on my models. I was able to track it down to a change from Laravel 7 to 8 that isn't in the upgrade guide.

### Steps To Reproduce:

* Laravel 8 upgrade guide: https://laravel.com/docs/8.x/upgrade contains no mention of date casting or mutations
* Laravel 7 docs has a section on [Date Mutators](https://laravel.com/docs/7.x/eloquent-mutators#date-mutators), where you define a class attribute to list which DB columns will be casted to date objects: `protected $dates = ['expires_at']`
* Laravel 8 docs has a section on [Date Casting](https://laravel.com/docs/8.x/eloquent-mutators#date-casting) where this syntax is changed completely: `protected $casts = ['expires_at' => 'datetime:Y-m-d'];`

The result is any code that assumes the value is a date object, (e.g. `$object->expires_at->format('Y-m-d')`) results in an error.

This should be pointed out in in the upgrade guide for Laravel 8.

**Comment by driesvints** [comment]
The `$dates` property wasn't removed in v8, it was removed in v10. You can still use `$dates` in v8 even though it's deprecated. For v10 it's mentioned here: https://laravel.com/docs/10.x/upgrade#model-dates-property

**Comment by boryn** [comment]
So it's missing information it was deprecated. I as well didn't catch that before doing regular upgrades.
