### ISSUE TITLE
After orm update or create, column which use DB:raw() not right

### ISSUE THREAD

**Issue by y2468101216** [laravel/framework#46204]
- Laravel Version: 10.0.2
- PHP Version: 8.1
- Database Driver & Version: mysql

### Description:
if you use Eloquent ORM and you update or create,
column you use DB:raw() in model not refresh and update or create will success

see example

### Steps To Reproduce:

```php
/* table orders has column amount and it's type int */

$order = Order::updateOrCreate([
   'id' => 1
], [
   'amount' => DB:raw("amount+1")
]);

echo $order->amount > 1; // will fail because it's class not int
```

### Discuess

This issue can be solved by using refresh()
```php
/* table orders has column amount and it's type int */

$order = Order::updateOrCreate([
   'id' => 1
], [
   'amount' => DB:raw('amount+1')
])->refresh();

echo $order->amount > 1; // it's ok
```
so I don't know is it a bug?
if it's a bug, I think there are two way to solve it.

1. throw expection like CantUseDBrawFillColumnExpection to stop fill it.
2. when fill column, check column. if column is not natual type, refresh it.

I think the second way is better, because mysql and postgresql support like below.

```sql
UPDATE t1 SET col1 = col1 + 1, col2 = col1;
```

I can try to send pr this.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
