### ISSUE TITLE
Laravel does not use more than 512MB memory on Redis. 

### ISSUE THREAD

**Issue by magic-thomas** [laravel/framework#46214]
- Laravel Version: 9.51.0
- PHP Version: 8.2.2
- Database Driver & Version: 
-redis server : Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 
- composer.json 
```json 
"predis/predis": "^2.0",
```

### Description:
I have chunk files to append into one file  in a directory. 
If it is over 512MB, it cause error. 
```sh
Predis\Response\ServerException: ERR string exceeds maximum allowed size (512MB) in file vendor/predis/predis/src/Client.php on line 354
```

I set `maxmemory` of redis-server 

```
127.0.0.1:6379> config get maxmemory
1) "maxmemory"
2) "16106127360"
```

I set php memory_limit 

```conf
// /etc/php/8.2/fpm/php.ini
memory_limit = 20G

// /etc/php/8.2/cli/php.ini
memory_limit = -1
```

// database.php 
```php
'redis' => [
    'client' => 'predis',
    ;
],
```

So it means I am using `predis`.

Even with above configs, the error still comes out.

### Steps To Reproduce:

I run this code in Controller which runs from  web Router. 

```php
$chunks_dir = 'somewhere_dir';

$files = scandir($chunks_dir);
$redis_key = 'key';
Redis::set($redis_key , null);
foreah( $files as $chunk_file_path) {
    Redis::append($redis_key, Storage::disk($disk)->get($chunk_file_path) );
}
```
`Redis::append` makes error.

To see the error, the  'somewhere_dir' size should be bigger than 512MB .

**Comment by jameshulse** [comment]
Are you sure it works in the console?

Redis documentation says that it has a [maximum key and value size of 512 MB](https://redis.io/docs/data-types/tutorial/#:~:text=Values%20can%20be%20strings%20(including%20binary%20data)%20of%20every%20kind%2C%20for%20instance%20you%20can%20store%20a%20jpeg%20image%20inside%20a%20value.%20A%20value%20can%27t%20be%20bigger%20than%20512%20MB.) which matches with the error you are seeing. I believe the `maxmemory` setting is increasing the total memory that Redis will use across all keys and values, not the individual key/value size. So changing this setting won't affect the limitation in redis.

This doesn't look like a Laravel bug, but a limitation in Redis.

**Comment by driesvints** [comment]
Thank you but see the above. 

Thanks @jameshulse
