### ISSUE TITLE
Collection sorting appears to be altered on v10.1.0

### ISSUE THREAD

**Issue by browner12** [laravel/framework#46213]
- Laravel Version: 10.1.0
- PHP Version: 8.2.2
- Database Driver & Version: MySQL 8.0.32

### Description:

After upgrading to Laravel 10.1.0, I was getting some test failures that appeared to be related to Collection sorting.  I reverted back to Laravel v10.0.3 and all tests passed again.

I haven't had time to deep dive in yet, but will soon and report back with more info.

### Steps To Reproduce:

Possibly use the Collection `sort()` method. Will provide more details as I dig in.

**Comment by taka-oyama** [comment]
If you're using `Arr::random` `Arr::shuffle` `Collection::random` `Collection::shuffle`, then the internal implementation changed with https://github.com/laravel/framework/pull/46105.

**Comment by zeriyoshi** [comment]
Are you using one of the following functions? If so, the #46105 may be affected

- srand
- rand
- mt_srand
- mt_rand
- shuffle
- str_shuffle
- array_rand

**Comment by nunomaduro** [comment]
It should be fixed on the `10.1.2` release. Thank you for reporting this.
