### ISSUE TITLE
Query Builder - Incomplete Type Hint for whereIn / orWhereIn

### ISSUE THREAD

**Issue by madhurbhaiya** [laravel/framework#46222]
- Laravel Version: 10.0.0
- PHP Version: 8.1.14
- Database Driver & Version: MySQL 8.0.31

### Description:
Query Builder's ```whereIn / orWhereIn``` method supports having a ```DB::raw(..)``` expression in the first parameter (```$column```).

Prior to Laravel v10, the IDE (PHPStorm) did not give any incompatible type warning.

However, in the recent upgrade, due to a change in type hint in the Doc Blocks, PHP Storm is giving "strong yellow" warning, where-ever DB::raw() expression is used as column.

### Steps To Reproduce:

Please check the following screenshot:

![image](https://user-images.githubusercontent.com/66555943/220613016-5d440108-73c7-4708-b066-fd0b571ed27d.png)

Sample code can be:

```php

// Warning generated at whereIn because of DB::raw() expression
$q = DB::query()->whereIn(DB::raw("COALESCE(match_status, 'PENDING')", ['MATCHED', 'MISMATCHED']));
```

Casting to string will not work, because in case of string column, Query Builder changes the expression by adding backticks, which does not work in this case.

If this is not the preferred way, then how could we handle Raw Column Expressions with ```IN(...)``` SQL condition

**Comment by nunomaduro** [comment]
Fixed by: https://github.com/laravel/framework/pull/46160.
