### ISSUE TITLE
Database sequence is included when squashing Migration

### ISSUE THREAD

**Issue by wildanafifi** [laravel/framework#46221]
- Laravel Version:  8.83.26
- PHP Version: 8.0.3
- Database Driver & Version: postgresql 12.13

### Description:
When squashing migration using `php artisan migrate:dump --prune`
a pgsql-schema.dump file is created on database/schema folder and all migrations file is deleted on database/migrations folder.

But when i try to migrate to another database (empty database) using `php artisan migrate` (which will use the new file pqsql-schema.dump) it successfully create all the tables, but also including sequences with last value seq from previous database. 

When I check the pqsql-schema.dump file, i found that the last seq value is dumped on that file.

Is it possible to not include the last seq value when squashing migration? Often times we only want the tables and the sequence but the seq is back from 0.

### Steps To Reproduce:
- From existing database with existing data, dump and prune all migrations code using
`php artisan migrate:dump --prune`
- Create another database (empty database with no tables)
- Modify environment to point to new database
- Migrate to new database using
`php artisan migrate`
- Check table sequences on new database

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
