### ISSUE TITLE
PGSQL - getDoctrineSchemaManager calls undefined function in connection.php

### ISSUE THREAD

**Issue by 7Jhanson** [laravel/framework#46238]
- Laravel Version: 10.0.3
- PHP Version: 8.1
- Database Driver & Version: Pgsql 12.3.3

### Description:
I'm trying to use the `Schema::getConnection()->getDoctrineSchemaManager()` function but I'm getting this error: 

![image](https://user-images.githubusercontent.com/90181016/220893354-d7d43127-504c-4f81-b596-74a85ced5c1f.png)

In Connection.php, ligne 1112 `getDoctrineSchemaManager()` returns `$connection->createSchemaManager()` which **DOES NOT EXIST**
I tried resolving myself but I had some trouble.

### Steps To Reproduce:

- Use a PGSQL database connection
- try using `Schema::getConnection()->getDoctrineSchemaManager()`

**Comment by driesvints** [comment]
What `doctrine/dbal` version are you using?

**Comment by 7Jhanson** [comment]
`"doctrine/dbal": "^2.12.1"`

**Comment by driesvints** [comment]
We no longer support DBAL v2 in Laravel v10. But it seems we forgot to mention this in the upgrade guide. I've sent in a PR: https://github.com/laravel/docs/pull/8611

Please upgrade to DBAL v3, thanks.
