### ISSUE TITLE
RedisStore depending on Redis configuration, array value will be serialized twice

### ISSUE THREAD

**Issue by dave2309** [laravel/framework#46236]
- Laravel Version: 9.41.0
- PHP Version: 8.0.27
- Redis: 5.0.7

### Description:
The context involve sharing data stored in a Redis database between different applications using different frameworks.
The issue is visible while using the `Cache::store('redis')` vs. `Redis` facades.

By default, the Redis configuration does not set any serializer, in real life, one can easily use `Redis::SERIALIZER_MSGPACK`, `Redis::SERIALIZER_IGBINARY` etc... (use `Redis::SERIALIZER_PHP` is the one with which you can actually see the result, because when using compression or other serializer it is obviously hidden)

By default then if one want to store an array in Redis, using `Redis` facade that will not be successful as without serializer option the value is just passed as is. The `Cache` facade in the contrary would use `serialize()` function before to enter the `Redis::set()` then the value is serialized and usable.
If you setup a serializer option in the Redis configuration though, the `Redis` would serialize the array (correctly). But then if one uses the `Cache` facade the value would be serialized twice (one from the `RedisStore::serialize()` method and the second by `Redis` engine itself due to the configuration.

Issues here are:
- There is a lack of consistency between using `Cache::store('redis')` and `Redis` facades.
- Behaviour then is not directly usable with another framework/app because of the double serialization.

1. Maybe an option would be to add some comments on the default part of Redis database cache configuration? Saying that a serializer is greatly recommended, but if so, the value (array type) will be serialized twice.
2. I believe that serializer option should probably have a default value in general. So then the `serialize/unserialize` in `RedisStore` would be unnecessary?

### Steps To Reproduce:
Using `Redis::set()` with an SERIALIZER_PHP option Redis value is
`a:1:{s:7:"results";s:128:"Court,Energy,Enemalta,Gozo,Planning Authority,Crime,Justice,Murder,Music,Italy,Construction,Environment,History,Comment,Football";}`
Same array using `Cache::store('redis')->set()`
`s:157:"a:1:{s:7:"results";s:128:"Court,Energy,Enemalta,Gozo,Planning Authority,Crime,Justice,Murder,Music,Italy,Construction,Environment,History,Comment,Football";}";`

I hope I am being clear enough. 

This is not exhaustive, I did not test that with other `Stores`.
Not saying that the issue is a bug.
But interoperability is an issue, as one must to not use one of the facades if one wants to share data between project.

More detail or advices can be discussed if needed

Thanks for your attention.

Regards,
Dave

**Comment by driesvints** [comment]
Hi Dave. Thank you for reporting this. However, as you said, I think this falls out of scope of what Laravel can offer.

If you'd like this to work, you can always attempt a PR, thanks.

**Comment by jyxjjj** [comment]
I think it because whatever config files set, 
```
            'serializer' => Redis::SERIALIZER_NONE,
            'compression' => Redis::COMPRESSION_NONE,
```
or
```
            'serializer' => Redis::SERIALIZER_IGBINARY,
            'compression' => Redis::COMPRESSION_NONE,
```
or
```
            'serializer' => Redis::SERIALIZER_MSGPACK,
            'compression' => Redis::COMPRESSION_NONE,
```
This function in `RedisStore` will also be used.
```
protected function serialize($value)
    {
        return is_numeric($value) && ! in_array($value, [INF, -INF]) && ! is_nan($value) ? $value : serialize($value);
    }
```

@dave2309 Am i right?

If i am right , @driesvints , why you said `this falls out of scope of what Laravel can offer`?

**Comment by dave2309** [comment]
hi @driesvints sorry to come back to this just now.
I think things have changed since PR#54221
and seems to address the issue
