### ISSUE TITLE
Bug In cash keys

### ISSUE THREAD

**Issue by GamerClassN7** [laravel/framework#46244]
- Laravel Version: 9.52.2 & 10.1.0
- PHP Version: 8.2.3 & 8.2.3
- Database Driver & Version:

### Description:
this case is nev case as required in #46242 as requested by @driesvints . 
how ever beavior is exactly same.

When i use `Cache::remember("comment-".$comment->id."-project", 60, 2)` i get this error:

I even found where problem lies when folowing cache key is used: "filter-13-organization"
The file name should be this md5 hash: `3cfc118695be71111eebccec273a3665ba31fd37`
but is `3c/fc/3cfc118695be71111eebccec273a3665ba31fd37` instead zou can notice 2 additional / in string formate whitch are then pased as 2 subdirectories whitch due not exists!

**Comment by driesvints** [comment]
What error do you get?

**Comment by GamerClassN7** [comment]
I is exactly the same as in original Issue unforchunately :(

**Comment by driesvints** [comment]
What cache store?

**Comment by GamerClassN7** [comment]
CACHE_DRIVER=file

**Comment by GamerClassN7** [comment]
Interestin is that only KEyis vith INT in middle like `filter-13-organization` are affected and not on the end or start `filter-organization-13`

**Comment by driesvints** [comment]
> Cache::remember("comment-".$comment->id."-project", 60, 2)

This isn't even valid usage as the third param should be a closure, not an int. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
