### ISSUE TITLE
Bug In cash keys

### ISSUE THREAD

**Issue by GamerClassN7** [laravel/framework#46242]
- Laravel Version: 8.83.24
- PHP Version: 8.1.2-1
- Database Driver & Version:

### Description:
When i use `Cache::remember("comment-".$comment->id."-project", 60, 2)` i get this error:
![image](https://user-images.githubusercontent.com/22167469/220930339-83a7de84-8b03-4a76-90e2-baab9a70566f.png)

I even found where problem lies when folowing cache key is used: "filter-13-organization"
The file name should be this md5 hash: `3cfc118695be71111eebccec273a3665ba31fd37`
but is `3c/fc/3cfc118695be71111eebccec273a3665ba31fd37` instead  zou can notice 2 additional / in string formate whitch are then pased as 2 subdirectories whitch due not exists!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by GamerClassN7** [comment]
> Hey there,
> 
> Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!
Hello,

in Fact i already tried that in local docker enviroment, i tryed larave 9.52.2 and 10.1.0 whith is latest i think i am able to get by composer. With same outcome Exactly same error an behavior :(

I just specified version where i found it first sorry for that.

**Comment by GamerClassN7** [comment]
Do i need to open nev issue in that case ?
