### ISSUE TITLE
StreamedResponses send session cookie with requested domain, instead of config.session.domain

### ISSUE THREAD

**Issue by adantart** [laravel/framework#46262]
- Laravel Version: 9
- PHP Version: 8.2.1
- Database Driver & Version:

### Description:
I have a config.session.domain set to .mydomain.com
My authed section of my app is in back.mydomain.com
And it's working well ;-)

When you create a normal request being authenticated, the cookie session is set with the domain set in config.session.domain

Error 1
But when you create a stream request being authenticated, the cookie session is set with the domain that generates the request (in my case back.mydomain.com), instead of the config.session.domain (in my case, mydomain.com)

Error 2 (generated by 1, but other error)
This leads to have 2 session cookies with same name and different domains (mydomain.com and back.mydomain.com), leading in some crashes when authenticate again.

**Comment by ankurk91** [comment]
Can you share a little example of your controller?

**Comment by adantart** [comment]
> Can you share a little example of your controller?

Which Controller ?
The test is done with a simple simple method (both of them, the "normal" one, and the Stream one)

``` 
    public function standard()
    {
        return "hi!";
    }

    public function stream()
    {
        return response()->stream(function () {
            while (true) {
                echo "event: ping\n";
                $curDate = date(DATE_ISO8601);
                echo 'data: {"time": "' . $curDate . '"}';
                echo "\n\n";

                ob_flush();
                flush();

                if (connection_aborted()) {break;}
                sleep(2);
            }
        }, 200, [
            'Cache-Control' => 'no-cache',
            'Content-Type' => 'text/event-stream',
        ]);


    }
```

**Comment by adantart** [comment]
The error seems to be here (but I don't understand why)

In the handleStatefulRequest function of StartSession.php,

It's the line 
``` 
$response = $next($request);
```

Before that line, in the session manager ($this->manager), the config session domain value is the one set in the config.session file.

After that line, in the session manager, that value takes the value of the domain of the request.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
