### ISSUE TITLE
Algolia site search results not indexed in Laravel documentation for version 10

### ISSUE THREAD

**Issue by lunfel** [laravel/framework#46263]
This is a bug report on search engine of the documentation on the web site and not the framework itself. I put it here because it is not possible to open issues in the Laravel Doc repository (only PR). And since I do not know how to fix the problem, I can't put a PR.

When I go to https://laravel.com/docs/10.x and I search (via Algolia site search) for `whereHasMorph`, I get no result. If I go to this page https://laravel.com/docs/10.x/eloquent-relationships#querying-morph-to-relationships and search directly in the page (via browser search) I can find `whereHasMorph`.

If I do the same with https://laravel.com/docs/9.x/eloquent-relationships or https://laravel.com/docs/8.x/eloquent-relationships, I can see the Algolia site search result pointing me to the right section.

Since this feature is not deprecated or removed in version 10, I would expect to have search results for `whereHasMorph` in all three of the mentioned versions.

**Comment by driesvints** [comment]
We're currently looking into this. Thank you.

**Comment by shortcuts** [comment]
Hey, this seems to have been resolved in the latest Crawl (scheduled: `at 05:00 on Thursday`). Don't hesitate to bump the crawl frequency if you wish, and let me know if you observe some inconsistencies :)
