### ISSUE TITLE
Where - convert string to Int.Perfomance problem

### ISSUE THREAD

**Issue by IMCAgro** [laravel/framework#46278]
- Laravel Version: 8.75
- PHP Version:  7.4.33
- Database Driver & Version:
- 8.0.30 - MySQL

### Description:
Simple query 

```
$order_uniq = "107137949"
$order = OrdersModel::where('uniq_id', $order_uniq)
```
is generate mysql query "select * from `api_orders` where `uniq_id` = 107137949"

uniq_id - is has type varchar in mysql db and has index.
But if we pass uniq_id as INT - 

![image](https://user-images.githubusercontent.com/39766903/221419164-fc29a55f-645b-4ff4-afa7-0cdfe8f2f9b4.png)

Mysql is skeep use index 

![image](https://user-images.githubusercontent.com/39766903/221419192-24cdef96-2b9e-415e-9cf7-3b08c5c6e40a.png)

I think that this is not quite correct, that I pass the string type, and the builder changes it to an int
Of course I can use Db::raw - but it's not very convenient

### Steps To Reproduce:
```
$order_uniq = "107137949"
$order = OrdersModel::where('uniq_id', $order_uniq)
```

**Comment by IMCAgro** [comment]
```
    protected $casts = [
        'uniq_id'       => 'string',
        'transaction_id' => 'string',
    ];
```

**Comment by rodrigopedra** [comment]
Set `$keyType` to `string`. Look the following example from the official docs for reference.

```php
<?php
 
class Flight extends Model
{
    /**
     * The data type of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';
}
```

reference: https://laravel.com/docs/10.x/eloquent#primary-keys

**Comment by IMCAgro** [comment]
Its not a key

**Comment by IMCAgro** [comment]
> 

Its not a primary key.And i had cast for it into string

<?php
 protected $casts = [
      'uniq_id'       => 'string',
      'transaction_id' => 'string',
];

**Comment by IMCAgro** [comment]
> Set `$keyType` to `string`. Look the following example from the official docs for reference.
> 
> ```
> <?php
>  
> class Flight extends Model
> {
>     /**
>      * The data type of the auto-incrementing ID.
>      *
>      * @var string
>      */
>     protected $keyType = 'string';
> }
> ```
> 
> reference: https://laravel.com/docs/10.x/eloquent#primary-keys

Its not a primary key.Inside model i had cast it to string
```
 <?php
    protected $casts = [
        'uniq_id'       => 'string',
        'transaction_id' => 'string',
    ];
```

**Comment by rodrigopedra** [comment]
My bad, sorry

**Comment by rodrigopedra** [comment]
Laravel 8.x is unsupported. 

https://laravel.com/docs/10.x/releases#support-policy

I tried in Laravel 10, and it works fine. Can you try to upgrade?

How I tested:

~~~php
// ./routes/console.php

Artisan::command('app:test', function () {
    User::where('email', '12345')->get();
});
~~~

on a terminal

```bash
$ php artisan app:test
$ tail -f /var/lib/mysql/localhost.log
2023-02-27T06:12:51.503306Z     16456 Close stmt
2023-02-27T06:12:51.503342Z     16456 Prepare   set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
2023-02-27T06:12:51.503358Z     16456 Execute   set session sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
2023-02-27T06:12:51.503442Z     16456 Close stmt
2023-02-27T06:12:51.503551Z     16456 Prepare   select * from `users` where `email` = ?
2023-02-27T06:12:51.503614Z     16456 Execute   select * from `users` where `email` = '12345'
2023-02-27T06:12:51.503698Z     16456 Close stmt
2023-02-27T06:12:51.507878Z     16456 Quit
2023-02-27T06:12:52.182802Z        10 Close stmt
2023-02-27T06:12:52.182863Z        10 Close stmt
```

As you can see, the query was executed with `12345` as a string. I also added a cast to string on the model.

You might need to enable `general_log` on MySQL if you want to inspect all queries execute.

**Comment by IMCAgro** [comment]
ok  i  will check it on 10

**Comment by IMCAgro** [comment]
Hm - result is same)
"laravel/framework": "^10.0",

"select * from `orders` where `uniq_id` = 107137949" // app/Http/Controllers/MainController.php:22

**Comment by rodrigopedra** [comment]
Can you generate a public repository that makes it easy to reproduce the problem?

**Comment by IMCAgro** [comment]
Oh sorry - its realy my mistake

![image](https://user-images.githubusercontent.com/39766903/221521174-a2532bcb-6da6-4dfc-b5d0-02940f174d34.png)

And tnen

All is ok - so query builder - work as need
![image](https://user-images.githubusercontent.com/39766903/221521244-8e34a1bb-2abc-4757-805c-38023b75d44b.png)

Here is our bindings
![image](https://user-images.githubusercontent.com/39766903/221521359-72ae4c51-742a-4ffa-ba8e-dcf5a561c4d8.png)


Evrything work as need
