### ISSUE TITLE
Where() method on Collections gives inconsistent responses on Booleans

### ISSUE THREAD

**Issue by Rorymercer** [laravel/framework#46270]
- Laravel Version: 10.1.5
- PHP Version: 8.1.3
- Database Driver & Version: N/A - db not required 

### Description:

When using `where()` on a Collection of objects (base Collection or Eloquent Collection) that contains booleans - the response changes to either be a keyed collection or a flat collection depending on the order of the variables.  This causes problems when passed to Inertia/other front ends:

#### In Tinker:

```
$test = collect([
    (object)['value'=>true],
    (object)['value'=>true],
    (object)['value'=>false]
]);

$true = $test->where('value',value: true);
$false = $test->where('value',value:false);
```

#### Results
**$true**
```
> $true = $test->where('value',value: true);
= Illuminate\Support\Collection {#5192
    all: [
      {#5193
        +"value": true,
      },
      {#5239
        +"value": true,
      },
    ],
  }
```

**$false - _note that this collection is now keyed_**
```
> $false = $test->where('value',value:false);
= Illuminate\Support\Collection {#5216
    all: [
      2 => {#5215
        +"value": false,
      },
    ],
  }
```

This behaviour persists when an operator is specified, and using the WhereStrict() methods also.

If you change the first object to have a value of 'false' rather than true, both collections are always keyed - try with:
```
$test = collect([
    (object)['value'=>false],
    (object)['value'=>true],
    (object)['value'=>false]
]);

$true = $test->where('value',value: true); // Is now keyed where was not previously
$false = $test->where('value',value:false); // Is still keyed as previously 
```

**Comment by WendellAdriel** [comment]
I think that’s expected. The first example where it’s not keyed is because the result collection has all the elements in the same order before applying the where call. The other ones are keyed because the result collection has the items in diff order than the original collection.

**Comment by Rorymercer** [comment]
Interesting - thanks @WendellAdriel & @rodrigopedra.  This is indeed the same behaviour when you use the array_filter built in methods, so I will close the issue as not Laravel related.
