### ISSUE TITLE
Parameters in Route::redirect() are handled differently for implicit/explicit bindings

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#46273]
- Laravel Version: 10.1.3
- PHP Version: 8.2.0
- Database Driver & Version: MySQL 8.0

### Description:

Consider the following:

```php
// web.php
Route::redirect('user/{user}', '/user/{user}/overview');
Route::get('user/{user}/overview', UserController::class);

// app/Http/Controllers/UserController.php
class UserController
{
    public function __invoke(User $user)
    {
          // ...
    }
}

```

When ran as-is and hence implicitly binding the User model, the redirect works as expected. The `redirect()` method receives a user id and splices it into the destination URL. As a consequence the `{user}` parameter is only substituted in the second request (after the redirect).

When explicitly defining the binding, things change:
```php
// app/Providers/RouteServiceProvider.php : boot()
Route::bind('user', function ($id) {
    return User::findOrFail($id); // probably extended with additional query logic.
});
```

The `{user}` parameter is now also substituted in the **first** request, meaning that the framework's  `RedirectController` receives a full user model which it'll be unable to easily splice into the destination URL. Ultimately the application breaks and an exception is thrown.

Writing logic in the binding to check for redirect routes feels rather cumbersome.
I think this is a valid use case for the framework to disable the `SubstituteBindings` middleware in case of redirect routes... Can't think of any scenario where raw request parameters shouldn't end up in the destination url as-is.

**Comment by timacdonald** [comment]
Opened a PR to fix this issue: https://github.com/laravel/framework/pull/46281

**Comment by Propaganistas** [comment]
Thanks for the quick follow-up!

**Comment by timacdonald** [comment]
no sweat. thanks for reporting the issue.
