### ISSUE TITLE
high size problem

### ISSUE THREAD

**Issue by Yusufkulcu** [laravel/framework#46283]
- Laravel Version: 10.1.5
- PHP Version: 8.2
- Database Driver & Version: 10.4.27-MariaDB

### Description: 

When I try to install laravel with Composer it installs too many unnecessary packages. An empty laravel project becomes 1.85gb in size. When I try it on another device, there is no problem, but my device has such a problem. I've deleted everything and reinstalled just to be sure, but the result is the same. Can you help me

**Comment by timacdonald** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
