### ISSUE TITLE
Faker unique() not working properly

### ISSUE THREAD

**Issue by binaryfire** [laravel/framework#46287]
- Laravel Version: 10.0.3
- PHP Version: 8.2.3
- Database Driver & Version: MySQL 8.032

### Description:
`fake()->unique()` doesn't seem to be working properly, at least for the generators I've tried. Some examples:

`numberBetween`
`domainName`
`domainWord`
`word`

Some variations I've tried that have created dupes:
```
'invoice_number' => fake()->unique()->numberBetween($min = 1, $max = 999),
'invoice_number' => fake()->unique(true)->numberBetween($min = 1, $max = 999),
'domain' => fake()->unique()->domainName,
'domain' => fake()->unique()->word,
```

Example error msg:
` SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pollich.biz' for key.........`

I'm only creating 200-300 records so `numberBetween` shouldn't be running out of unique values. But according to the Faker docs an exception should be thrown if a duplicate value is generated: https://fakerphp.github.io/#modifiers

A few others are having the same issue too: https://laracasts.com/discuss/channels/laravel/faker-unique-not-always-working

_To reproduce:_
1. Do a migrate:fresh
2. Create some factories using the generators I mentioned above
3. Seed a few hundred records
4. Rinse and repeat steps 1-3 a few times. At some point you'll end up with dupes. No exceptions will be thrown.

**Comment by timacdonald** [comment]
@binaryfire the unique aspect of faker is only during a single invocation of the Framework.

For example:

```
# Invocation 1
php artisan migrate:fresh --seed

# Invocation 2
php artisan db:seed --class=Foo

# Invocation 3
php artisan tinker
```

Within each of these commands Faker should generate unique values, however it does not generate unique values _across_ them. So unique values generated in Invocation 1 may also be generated in Invocation 2 and 3.

Each time PHP shuts down Faker will reset its unique cache and may then generate the same values again.

Within a single invocation:

<img width="876" alt="Screen Shot 2023-02-28 at 8 22 15 am" src="https://user-images.githubusercontent.com/24803032/221688524-bd2b6a34-904b-40a6-955a-9d26c742451f.png">

Across multiple invocations:

<img width="534" alt="Screen Shot 2023-02-28 at 8 24 21 am" src="https://user-images.githubusercontent.com/24803032/221688876-bc445025-9803-4f74-ac18-5b92738dde47.png">

Hope this helps, but let us know if we have missed something.

**Comment by timacdonald** [comment]
Looks like `numberBetween` is not respecting the unique constraint.

**Comment by binaryfire** [comment]
@timacdonald Hey Tim. Yeah I’m aware of that. The problem occurs on a single invocation. What I meant by “rinse and repeat” is to “nuke the db and try again” if you can't reproduce the problem the first time. Hitting a dupe isn’t guaranteed even if unique() is broken-  it’s a matter of probability.

Did you try creating hundreds of records and attempt to reproduce the problem more than once, starting with an empty db each time? Here's some dummy files to use:

Factory:
```
<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'first_name' => fake()->unique()->firstName(),
            'last_name' => fake()->unique()->lastName(),
            'email' => fake()->unique()->word(),
            'password' => fake()->unique()->domainName(),
            'remember_token' => fake()->unique(true)->numberBetween($min = 1, $max = 999),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
```

Seeder:
```
<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // Create lots of users
        User::factory(500)->create();

    }
}
```

Example of the problem in action on a fresh db:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/5361908/221709964-43a03b5d-ae61-4b0c-8e16-3cd75d752608.png">

**Comment by binaryfire** [comment]
@timacdonald Have done a bit more investigation. I'm using `unique(true)` for `numberBetween` because of this: https://github.com/fzaninotto/Faker/issues/1512. 

From the Faker docs:
```
// you can reset the unique modifier for all providers by passing true as first argument
$faker->unique($reset = true)->randomDigitNotNull(); // will not throw OverflowException since unique() was reset
// tip: unique() keeps one array of values per provider
```

But using that for a single generator breaks exception handling for all the other generators. Using `unique(true)` for everything does greatly improve the odds of avoiding dupes, but it'll still happen after 5 or 6 attempts.

Is there anything that can be done to improve this? I could generate emails and domains using `bothify()` but I'm not sure there's a way of generating unique numbers between a range without using `numberBetween`.

**Comment by binaryfire** [comment]
@timacdonald Calling faker directly works 100% of the time, so it does seem to be an issue with the Laravel helper function.

This will work:
`<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\User;
use Faker\Factory as Faker;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $faker = Faker::create();

        return [
            'first_name' => $faker->unique()->firstName(),
            'last_name' => $faker->unique()->lastName(),
            'email' => $faker->unique()->email(),
            'password' => $faker->unique()->domainName(),
            'remember_token' => $faker->unique()->numberBetween($min = 1, $max = 999),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
`

**Comment by pxlrbt** [comment]
@binaryfire I think the reset flag shouldn't be used inside factories (`$this->faker->unique(true)`) as it *resets* the unique cache on every call. That's why you are getting random collisions.

**Comment by telkins** [comment]
> @binaryfire Are you using seeders at all? We're experiencing something similar and it's been quite frustrating. I haven't confirmed, but it seems like it might be that all tests where it might fail have a seeder called.
> 
> EDIT: I just realized you are seeding, at least in some of the instances where you're seeing the error. Perhaps this is why/how. Perhaps it's because the seeding is a different invocation even if it's within a single test run. 🤔

Well, I just did some basic tests, a la @timacdonald 's, and it seems to work as expected.  That is, the numbers generated in the seeder are respected in the rest of the test context.

This is really bothersome.  😒

**Comment by telkins** [comment]
Two things discovered so far:

- Some tests that should use `RefreshDatabase` were not using `RefreshDatabase`.  That has been remedied and explains some of the issues.
- Some tests explicitly override/set an attribute when calling the factory's `create()` method.  In these cases, faker is not at all aware of the value passed/used.  (Faker still generates a unique value in those cases, which increases the chances of faker later generating a unique value that has already been used...because it has been hard-coded, so to speak.)  We have to go in and clean up these tests.

Once we address these issues, I suspect we'll be out of the woods and home free.  🤓

**Comment by timacdonald** [comment]
@telkins, sorry for the troubles. Although painful, it sounds like this might have help surface some things for you.

Appreciate the updates to help guide others in the future.

**Comment by anchan42** [comment]
Found the same thing here when trying to generate 5000 users. It always get to about 5xx users before alarm out.

My factory:

```
<?php

namespace Database\Factories;

use App\Models\CostCenter;
use Faker\Factory as Faker;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Role;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {

        $faker = Faker::create();
        return [
            'id' =>  $faker->randomNumber(8, false),
            'email' =>  $faker->unique()->companyEmail(),
            'username' =>  $faker->unique()->userName(),
            'email_verified_at' => now(),
            'password' => bcrypt('letmein'), // password
            'remember_token' => Str::random(10),
            'first_name' =>  $faker->firstName(),
            'last_name' =>  $faker->lastName(),
            'active' => true,
            'title' =>  $faker->jobTitle(),
            'department' =>  fake()->department(),
            'start_date' =>  $faker->dateTimeBetween('-15 year', '-1 year'),
            'mobile' =>  $faker->phoneNumber(),
            // 'manager_id' => '48060405'
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    public function configure(): static
    {
        return $this->afterCreating(function (User $user) {
            $user->costCenters()->attach(CostCenter::inRandomOrder()->take(10)->pluck('id'), ['bdr_visibility' => true, 'bdr_notification' => true]);
            $user->assignRole(Role::inRandomOrder()->take(1)->pluck('name'));
        });
    }
}

```

The error:

```
 Illuminate\Database\UniqueConstraintViolationException

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'qrohan' for key 'users.users_username_unique' (Connection: mysql, SQL: insert into `users` (`id`, `email`, `username`, `email_verified_at`, `password`, `remember_token`, `first_name`, `last_name`, `active`, `title`, `department`, `start_date`, `mobile`, `updated_at`, `created_at`) values (80990411, tre.armstrong@kunde.info, qrohan, 2024-07-27 12:23:55, $2y$10$w3EPhA5PbTazB8hEsX8FjeQ.h1s3MtuuHWzbb80n.zZEf3LyoGOmy, KDuvzEhMAq, Samir, Hackett, 1, Rail Yard Engineer, Toys & Games, 2015-10-25 17:39:22, 1-318-379-0050, 2024-07-27 12:29:09, 2024-07-27 12:29:09))

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:824
    820▕         // message to include the bindings with SQL, which will make this exception a
    821▕         // lot more helpful to the developer instead of just the database's errors.
    822▕         catch (Exception $e) {
    823▕             if ($this->isUniqueConstraintError($e)) {
  ➜ 824▕                 throw new UniqueConstraintViolationException(
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕

  1   vendor\laravel\framework\src\Illuminate\Database\Connection.php:587
      PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'qrohan' for key 'users.users_username_unique'")

  2   vendor\laravel\framework\src\Illuminate\Database\Connection.php:587
      PDOStatement::execute()
```
