### ISSUE TITLE
Laravel 10 custom date casts with formatting skipping serializeDate

### ISSUE THREAD

**Issue by jackkitley** [laravel/framework#46286]
- Laravel Version: 10.1.5
- PHP Version: 8.2.2
- Database Driver & Version: Mysql 8.0.32

### Description:

Before mandatory casts for $dates i was able to define my custom dates for example `valid_until` and i was able to define a format and it would always hit `serializeDate`. 

In Laravel 10 it breaks when i define my custom date and define a format. It skips right over the custom date.

`serializeDate` only works if it is defined as a datetime or date cast but with no formatting for that specific date?

This is affecting how i use dates with timezone centrally.

### Steps To Reproduce:

Define a custom datetime column and define it in $casts with a `datetime:Y:m:d`. It skips serializeDate

dd($deal,$deal->toArray());

The bottom valid_until is the desired output.

![Screenshot 2023-02-27 at 16 51 59](https://user-images.githubusercontent.com/3243014/221596460-803e7efc-1ee3-4892-ac1d-615bb28f9fae.png)

**Comment by rodrigopedra** [comment]
What is not working?

Your casts `datetime:Y:m:d` does not match the desired format of `2023-03-04 01:30:00` highlighted in the picture. Maybe could be it?

Try using this: 

```php
protected $casts = [
    'valid_until' => 'datetime:Y-m-d H:i:s',
];
```

**Comment by jackkitley** [comment]
@rodrigopedra Sorry, was a typo my side when logging this.

I did try with `'valid_until'         => 'datetime:Y-m-d H:i:s',` and is still doesnt go through serializeDate().

It should go through as both of these go through.

`
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
`

**Comment by rodrigopedra** [comment]
Is `valid_until` calculates as a custom attribute (mutator/accessor)? If so, it will skip `$casts` all together.

https://laravel.com/docs/10.x/eloquent-mutators

Or is it a database field? Note that even if it is a database field, having a mutator/accessor will also skip `$casts`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by cwilby** [comment]
Oh yeah, super completed 👏

This was another reference to the terrible deprecation of $dates.
