### ISSUE TITLE
Resource Collections work twice when used in a controller

### ISSUE THREAD

**Issue by kon3ko** [laravel/framework#46282]
- Laravel Version: 8.83.27
- PHP Version: 8.0.27
- Database Driver & Version: MySQL 8

### Description:
If using Resource Collections, there will be two calls `toArray` per call to the Controller.

### Steps To Reproduce:

```php
//in UserController.php
class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return UserResource::collection($users);
    }
}

//in UserResource.php
class UserResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
        ];
    }
}
```

when the controller is invoked
The `toArray` method is called for the number of items and recursively.
Ex. with 20 total items, `toArray` will be called 40 times.

And if I create an attribute and have a database call on it make it call 2 times
https://laravel.com/docs/8.x/eloquent-serialization#appending-values-to-json

But if you use `make` it will run only once.
```php
return UserResource::make($user);
```

**Comment by dwightwatson** [comment]
Can you replicate this in a fresh Laravel app? I just tried to replicate it in my app (logging every time it calls into `toArray` and seeing that it matches the number of items in the collection).

Curious what you mean by referencing that `make` as that's only relevant for a single record rather than a collection.

**Comment by kon3ko** [comment]
> Can you replicate this in a fresh Laravel app? I just tried to replicate it in my app (logging every time it calls into `toArray` and seeing that it matches the number of items in the collection).
> 
> Curious what you mean by referencing that `make` as that's only relevant for a single record rather than a collection.

It doesn't seem to happen with fresh Laravel app.
Can you have some advice for me? which part should I check? Because my code is a lot and I just discovered it a moment ago.

**Comment by kon3ko** [comment]
Or is there any tool that I can track down the cause?

**Comment by dwightwatson** [comment]
Very hard to say if it doesn't occur in a fresh Laravel app.

Double-check that what you think is happening is happening - are you absolutely positive `toArray` is being called more than you expect?

Are you customising the framework in any way that might contribute to this - does reverting those changes make a difference?

Walk through your controllers and your code to see if you can find the exact cause of this duplication and then see if you can cause that to occur in a fresh app as well.

Without a replication there's not much else that can be done here.

**Comment by kon3ko** [comment]
@dwightwatson  
I'm sure because I use Ray to check multiple places.
It definitely happens in `toArray`

It was very difficult to replicate. Because I have been working on this project for more than 1 year.
May I ask It has a tool that says In which file does the code run at startup? Until the end of work? I'll try to check the problem from those files.

thank you

**Comment by kon3ko** [comment]
@dwightwatson 
I've tried testing my code.
If I don't use Cache, the system works fine.
But if I use Cache, it behaves incorrectly.
```php
class TestController extends Controller
{
    public function index()
    {
        $users = Cache::remember('users', now()->addHour(), function ()  {
            return User::paginate(5);
        });
        ray('users', $users);
        ray('users count', $users->count());

        return UserResource::collection($users);
    }
}
```

![image](https://user-images.githubusercontent.com/50349884/221473085-7ef80bde-f340-408f-b3ad-dc4329905b2f.png)



I tried with fresh Laravel app, it works fine.
Do you have any advice? Where should I check?

**Comment by kon3ko** [comment]
is it because Telescope https://laravel.com/docs/8.x/telescope
and it works normally on production 🙆🏼‍♂️
