### ISSUE TITLE
Required if bug

### ISSUE THREAD

**Issue by soixt** [laravel/framework#46298]
When I use form validation rules in array way:

`['name' => ['required_if:type,1', 'min:4']]`

If type is not 1, it still validates the min rule and returns error, however when I use:

`['name' => 'required_if:type,1|min:4']`

If the type is not 1, it skips every other rule for that value.

Not sure why would different type of writing have different outcome.

**Comment by timacdonald** [comment]
Hey there,

I'm unable to reproduce this on a fresh Laravel installation.


<img width="875" alt="Screen Shot 2023-03-01 at 9 59 38 am" src="https://user-images.githubusercontent.com/24803032/222001143-19ceaa9d-b7cc-48d8-841f-924077fe8ae3.png">


Can you please create a minimal reproduction for this and we take a closer look?

```
laravel new bug-report --github="--public"
```
