### ISSUE TITLE
Sync Queue driver does not respect the ```afterCommit``` setting.

### ISSUE THREAD

**Issue by dciprian-petrisor** [laravel/framework#46296]
- Laravel Version: 9.52.0
- PHP Version: 8.2.3
- Database Driver & Version: MySQL 5.7

### Description:

```Illuminate\Queue\SyncQueue``` does not implement support for the ```$afterCommit``` attribute or ```after_commit``` configuration option and seems to immediately dispatch all jobs, regardless of how the driver or job was configured.

### Steps To Reproduce:

1. Set queue driver to ```sync```.

2. Create an event such as:
```php
class PodcastPublished
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;

    public $afterCommit = true;
}
```

3. Dispatch the event during a transaction:
```php
public function publishPodcast() {
  DB::transaction(function () {
  // some DB inserts, etc
  // fire the event -- expectation is to queue job to run at the end of the tx
  PodcastPublished::dispatch();
 // some more db activities...
});
}
```

4. The event will be dispatched in-place instead of at the end of the transaction.
 
### Possible causes

The ```push``` method in ```Illuminate\Queue\SyncQueue```  seems to be the culprit here:
https://github.com/laravel/framework/blob/5e8f9b0249e9a0b67d674621f7047c4e7eaf9e00/src/Illuminate/Queue/SyncQueue.php#L36-L51

Unlike other Queue drivers, this one does not make use of the ```enqueueUsing``` method in the parent ```Illuminate\Queue\Queue``` class, which handles dispatching the jobs only after transactions are finished when ```afterCommit=true``` :

https://github.com/laravel/framework/blob/5e8f9b0249e9a0b67d674621f7047c4e7eaf9e00/src/Illuminate/Queue/Queue.php#L302-L318

### Notes

I strongly believe the above should not be the case, as it is unexpected behaviour to silently ignore the ```afterCommit``` setting for this queue driver.

I would be interested in submitting a PR to handle this, if maintainers also see this as a problem.

**Comment by driesvints** [comment]
This is the expected behavior. a SyncQueue will always immediately dispatch jobs.

**Comment by dciprian-petrisor** [comment]
Thank you for the reply, I understand now that this was the Laravel team's intent.

It is, however, very undesirable to have such differences, which are nowhere documented. 

As I see it, the sync queue driver silently ignores the setting, causing unexpected behaviour for developers. 

It is also pretty much impossible to workaround during development/testing without resorting to an alternative sync queue implementation that honors the after commit setting.

Given that technically speaking there is little change to be made and it would be backwards compatible (after_commit = false keeps the current behaviour), would maintainers consider adding this as an improvement to the sync driver?
