### ISSUE TITLE
Parallel testing and code coverage is not working after upgrading to Laravel 10.x

### ISSUE THREAD

**Issue by pacoorozco** [laravel/framework#46294]
- Laravel Version: 10.1.5
- PHP Version: 8.1.6
- Database Driver & Version: mysql 8.0.31

### Description:
After upgrading to Laravel 10.x the command I was using to run the test in parallel is not working anymore. 

After debugging a lot I've seen that the problem is raised when you are using the `test` artisan command with the `--coverage` parameter. It this scenario the test stop working an a message like the one below is print:

```
sail artisan test --parallel --coverage 
ParaTest v7.0.6 upon PHPUnit 10.0.12 by Sebastian Bergmann and contributors.

Cache for static analysis has not been configured
```

If you specify a directory using the parameter `--cache-directory /tmp`, the tests are passing again. 

**So either the Laravel documentation is wrong (Upgrade guide) or the parameter should be used as default.**

### Steps To Reproduce:

Before the upgrade to Laravel 10.x and PHPUnit 10.x the GHA was running well:

https://github.com/pacoorozco/gamify-laravel/actions/runs/4005748733/jobs/6876481733

After the upgrade, it's failing:

https://github.com/pacoorozco/gamify-laravel/actions/runs/4270741375/jobs/7434731232

And finally If you set the `--cache-directory` parameter is working again:

https://github.com/pacoorozco/gamify-laravel/actions/runs/4293263511/jobs/7480722154

**Comment by pacoorozco** [comment]
I'm not interested on using the `cache-directory` because I'm running the test in a CI/CD pipeline. But If I try to disable this cache using the `--do-not-cache-result` and error is raised:

```
The "--do-not-cache-result" option does not exist.  

paratest [-m|--max-batch-size MAX-BATCH-SIZE] [--no-test-tokens] [--passthru-php PASSTHRU-PHP] [-p|--processes PROCESSES] [--runner RUNNER] [--tmp-dir TMP-DIR] [-v|--verbose] [--bootstrap BOOTSTRAP] [-c|--configuration CONFIGURATION] [--no-configuration] [--cache-directory CACHE-DIRECTORY] [--testsuite TESTSUITE] [--exclude-testsuite EXCLUDE-TESTSUITE] [--group GROUP] [--exclude-group EXCLUDE-GROUP] [--filter FILTER] [--strict-coverage] [--strict-global-state] [--disallow-test-output] [--dont-report-useless-tests] [--stop-on-defect] [--stop-on-error] [--stop-on-failure] [--stop-on-warning] [--stop-on-risky] [--stop-on-skipped] [--stop-on-incomplete] [--fail-on-incomplete] [--fail-on-risky] [--fail-on-skipped] [--fail-on-warning] [--order-by ORDER-BY] [--random-order-seed RANDOM-ORDER-SEED] [--colors [COLORS]] [--no-progress] [--display-incomplete] [--display-skipped] [--display-deprecations] [--display-errors] [--display-notices] [--display-warnings] [--teamcity] [--testdox] [--log-junit LOG-JUNIT] [--log-teamcity LOG-TEAMCITY] [--coverage-clover COVERAGE-CLOVER] [--coverage-cobertura COVERAGE-COBERTURA] [--coverage-crap4j COVERAGE-CRAP4J] [--coverage-html COVERAGE-HTML] [--coverage-php COVERAGE-PHP] [--coverage-text [COVERAGE-TEXT]] [--coverage-xml COVERAGE-XML] [--coverage-filter COVERAGE-FILTER] [--no-coverage] [--] [<path>]
```

**Comment by nunomaduro** [comment]
Fixed in Collision `v7.1.0`.

**Comment by pacoorozco** [comment]
Thanks a lot for the quick fix :-*

**Comment by xvilo** [comment]
I'm having the same while setting it up for the first time:
```
$ export CPUS=`nproc`
$ eval "$TOOLS_DIR/vendor/bin/paratest -p ${CPUS} tests/ --bootstrap vendor/autoload.php --coverage-text --colors=never -v"
ParaTest v7.1.2 upon PHPUnit 10.0.19 by Sebastian Bergmann and contributors.
Cache for static analysis has not been configured
```

What should I do? I'm at `v7.1.2`

**Comment by baschnipke** [comment]
Same issue on 7.1.3
