### ISSUE TITLE
Eloquent Builder methods returns static

### ISSUE THREAD

**Issue by localusercamp** [laravel/framework#46292]
### Discussed in https://github.com/laravel/framework/discussions/46291

<div type='discussions-op-text'>

<sup>Originally posted by **localusercamp** February 28, 2023</sup>
I found that Illuminate\Database\Eloquent\Builder methods `@return` phpDoc annotations contains both `Model` and `static` type or (`Collection` and `static[]`). Why it so? When builder can return array of queries from `get()` call?

![image](https://user-images.githubusercontent.com/45385480/221791638-a163ca33-195d-410e-a630-d691545341c4.png)
</div>

**Comment by driesvints** [comment]
Please do not move discussions to issues.
