### ISSUE TITLE
Laravel 10 High RAM usage

### ISSUE THREAD

**Issue by akbarali1** [laravel/framework#46339]
- Laravel Version: 10.1.5
- PHP Version: PHP 8.2.0 (cli) (Openserver)
- Database Driver & Version: MYSQL

### Description:
I made a project in laravel 10 and after few page refreshes it is taking up 3GB of Ram space and then it crashes.  Laravel didn't tell me about problems when I checked through Debugbar. 
![image](https://user-images.githubusercontent.com/39323182/222658622-d03fd5cd-5c67-45df-a796-b18b7e4a92ac.png)
![image](https://user-images.githubusercontent.com/39323182/222658545-d73f4c5f-126d-4055-89c4-883fbb6395ad.png)
![image](https://user-images.githubusercontent.com/39323182/222658674-3bb31fe2-9fca-4d5b-ae97-e192e4ed191d.png)

How can I identify the error?

![image](https://user-images.githubusercontent.com/39323182/222659423-9f8d36cd-60ba-4a51-86fc-1e63291222d0.png)
![image](https://user-images.githubusercontent.com/39323182/222659320-ffec3d95-6788-4c0a-96cb-0ee6194b92ae.png)

😅😅😅😅

**Comment by akbarali1** [comment]
![image](https://user-images.githubusercontent.com/39323182/222659112-0d183169-2436-4246-be9c-4c767b69b6f8.png)
😅😅😅😅

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
