### ISSUE TITLE
Redis port setting bugs

### ISSUE THREAD

**Issue by AyubM** [laravel/framework#46335]
- Laravel Version: 10
- PHP Version: 8.2
- Database Driver & Version:

### Description:
When using the socket connector for Redis with PhpRedis, here are the problems when you set REDIS_PORT:

If you set it to `REDIS_PORT=null`:
` DEPRECATED  Redis::connect(): Passing null to parameter #2 ($port) of type int is deprecated in vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php on line 161.`

The connection still works. I am worried about the deprecation notice.

If you set it to `REDIS_PORT=6379`:
` RedisException  No such file or directory.`

If you set it to `REDIS_PORT=`:
` TypeError  Redis::connect(): Argument #2 ($port) must be of type int, string given.`

**This is a separate bug in and of itself -- the database.php config file uses strings for the port instead of int**

If you set it to `REDIS_PORT=0`:
It works, but this feels hacky. Presumably the code somewhere is checking for the ports existence before it appends and this bypasses that as it evaluates to false.

Ideally the solution is that either setting it to null isn't deprecated, or setting it to empty doesn't cause an error.

### Steps To Reproduce:
Configure redis to use a socket connection by adding the following to your redis config:

```
unixsocket /run/redis/redis.sock
unixsocketperm 777
```

database.php redis config is stock save for the addition of `scheme` in the `options` section (and setting it to unix in .env)
```php
 'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
            'scheme' => env('REDIS_SCHEME', 'tcp'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],
```

**Comment by driesvints** [comment]
> The connection still works. I am worried about the deprecation notice.

Thank you for posting this. A deprecation notice isn't an actual bug so therefor I'm closing this. We'd appreciate a PR that would solve the deprecation notice.
