### ISSUE TITLE
Paginate gives wrong result if the initial query has “distinct” in it

### ISSUE THREAD

**Issue by Temepest74** [laravel/framework#46343]
- Laravel Version: v9.52.4
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.24

### Description:

Paginate count does not care about “distinct”

### Steps To Reproduce:

1. Create a query which will output duplicated records
2. The result of ```$query->distinct()->paginate(10)->total()``` is higher than if you are using ```$query->distinct()->get()->count()```

**Comment by rodrigopedra** [comment]
It seems, from the comment linked below

**Comment by rodrigopedra** [comment]
It seems, from the comment linked below, that specifying the individual columns you want to be retrieved, when using DISTINCT + pagination, works:

https://github.com/laravel/framework/issues/42660#issuecomment-1146826413

Other than that, there are numerous issues and PRs on the same matter. 

- https://github.com/laravel/framework/issues?q=is%3Aissue+is%3Aclosed+paginate+distinct
- https://github.com/laravel/framework/pulls?q=is%3Apr+paginate+distinct

From memory, maintainers are not against a general "fix", they usually say they are open to a PR that doesn't overcomplicate maintenance, and doesn't break any other query builder features. 

But a PR that fulfills those criteria is yet to be seen. If you have an idea on how to make it work, you could give it a try.

**Comment by driesvints** [comment]
We'd appreciate a PR that would resolve this in a non-breaking way, thanks.

**Comment by Temepest74** [comment]
> We'd appreciate a PR that would resolve this in a non-breaking way, thanks.

Kind of stupid for you to close the issue. At least make a "know bugs" thread or smth. I don't have time for it.
