### ISSUE TITLE
Validation rule `regex` doesn't work correctly

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#46347]
- Laravel Version: 9.52.4
- PHP Version: 8.2.3
- Database Driver & Version: MySQL 8.0.29

### Description:

`regex` validation rule doesn't return false if I pass places more then 3:

Correct test:
```
public function testCorrectRegexValidationRule(): void
{
    $data = ['quantity' => 0.3489];
    $rules = ['quantity' => 'regex:/^\d*(\.\d{1,3})?$/'];

    $validator = validator($data, $rules);

    $this->assertTrue($validator->fails());
}
```

Incorrect test:
```
public function testIncorrectRegexValidationRule(): void
{
    $data = ['quantity' => 0.30000000000000004];
    $rules = ['quantity' => 'regex:/^\d*(\.\d{1,3})?$/'];

    $validator = validator($data, $rules);

    $this->assertTrue($validator->fails());
}
```

In the incorrect test validator should fails.

What am I doing wrong?

**Comment by timacdonald** [comment]
You are possibly running into an issue with _computers_, rather than Laravel.

`0.30000000000000004` is converted to `0.3` due to how computers handle floating point numbers. You may need to wrap the value in a string.

<img width="259" alt="Screen Shot 2023-03-06 at 9 16 43 am" src="https://user-images.githubusercontent.com/24803032/222988943-20d66bea-ba49-4a58-a4ae-45d1d2eb5467.png">

**Comment by siarheipashkevich** [comment]
@timacdonald I'm using DO servers which served by Forge (ubuntu 20.04, 22.04) and also it's reproduced on, my local machine (ubuntu 22.10). Yes, it is probably computer problem, but in laravel we have some validation rules (regex, decimals) which can can handle precision and it does not work correctly. Am I wrong?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by timacdonald** [comment]
@siarheipashkevich you will want to handle numbers as strings. This is a universal problem unrelated to Laravel, PHP, Ubuntu, etc.

I'd also recommend checking out the `brick/math` library for manipulating arbitrary precision numbers.
