### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by lucifer-crybaby** [laravel/framework#46341]
- Laravel Version: 10.0.3
- PHP Version: 8.2.3
- Database Driver & Version: MySQL: 8.0.32

### Description:
According to the doc if you want to [allow mass assignment on your model](https://laravel.com/docs/10.x/eloquent#allowing-mass-assignment) you have to do this: 
`protected $guarded = [];`
 
But it causes ` Array to string conversion` error when creating model. However if you put empty string inside array like below it will work as intended:
`protected $guarded = [''];`

I know it's not that big of a bug but I was so confused and struggled almost an hour. I think the doc needs some updating or framework needs to work as described in the doc. Sorry for my bad english :smile:

### Steps To Reproduce:
Create model class, make it mass assignable and create new model using create() function.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
