### ISSUE TITLE
Error in SSL certificate verification Password::uncompromised() validation rule.

### ISSUE THREAD

**Issue by smarcelloc** [laravel/framework#46353]
- Laravel Version: 10.1.5
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8

### Description:

I encountered an SSL certificate verification error when including the Password::uncompromised() password validation rule.

Generated log file:
`
[2023-03-04 17:21:57] local.ERROR: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.pwnedpasswords.com/range/0D9B1 {"userId":1,"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.pwnedpasswords.com/range/0D9B1
`

### Steps To Reproduce:

It is important to test in an environment without HTTPS, as sometimes in development we do not use a valid SSL certificate.

1. After installing laravel and making the initial configurations.
2. Create a password field for validations.
3. In the `app\Providers\AppServiceProvider.php` file include this code to add a default rule for password fields:

```php

   /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Password::defaults(fn () => Password::min(8)->letters()->numbers()->symbols()->uncompromised());
    }
}

```

4. In a FormRequest file include the validation rules:

```php
   /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\Rule|array|string>
     */
    public function rules(): array
    {
        return [
            'password_old' => ['required', 'string', 'max:80', 'current_password'],
            'password_new' => ['required', 'string', Password::defaults(), 'max:80', 'confirmed'],
        ];
    }

```

5. After that check the system error log.

**Comment by ankurk91** [comment]
You may want to specify your environment and operating system.
It might be related to CURL.

**Comment by smarcelloc** [comment]
My server is an IIS and the operating system is Windows 11.

**Comment by ankurk91** [comment]
https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by driesvints** [comment]
I can't reproduce this so this seems to be specific to your environment. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
