### ISSUE TITLE
CORS errors during development if the code throws an exception. (example: 500-error)

### ISSUE THREAD

**Issue by engenes** [laravel/framework#46363]
- Laravel Version: 10.2.0
- PHP Version:  8.1.0 

### Description:
I still get the  CORS-error when an 500-error occurs on the server.
For example, if I make a syntax error in the code, causing the application to crash, then the headers will not be set and the browser will show CORS errors.

That is, code execution does not reach ` \Illuminate\Http\Middleware\HandleCors::class` in `app/Http/Kernel.php` if there is a 500-error

Installed clean Laravel and intentionally made a mistake in the code, and again I see the CORS-error, instead of an error message.

It is no longer possible to quickly identify the source of an error in the console during development SPA

I have to open the log file all the time, without normal highlighting

![image](https://user-images.githubusercontent.com/38880660/223036925-04da22b3-643a-4a6f-b571-60529cd9935a.png)

### Steps To Reproduce:

1. install Laravel
2. configure CORS for your client domain
3. create a route

```
Route::get('/test', function () {
     return 111;
});
```
 in routes/api.php

4. send a request from your client domain to this route
5. make sure everything works and there are no CORS errors
6. make a syntax error in routes/api.php and run the request again

result: CORS-error
expect: standard Laravel syntax error message

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
