### ISSUE TITLE
Model appended attribute returns null when model is initiated through dependecy injection

### ISSUE THREAD

**Issue by mohamedds-12** [laravel/framework#46379]
- Laravel Version: 8.83.27
- PHP Version: 8.1.10
- Database Driver & Version: Mysql 8.0.30

### Description:
I have an appended attribute that works when I do `Model::first()->appended_attribute`, but when get the model object instantiated through laravel's route dependency injection like below :
```php
public function update(UserRequest $request, User $user)
{
 $user->appended_attribute; // returns null       

}
```
When I access it it returns `null`, Though when I do `$user->toArray()` the appended attributes does exist but with a value of null.
And if I do this : 
```php
public function update(UserRequest $request, User $user)
{
 User::find($user->id)->appended_attribute; // returns it's correct value

}
```
It does work.

The append attribute method : 
```php
public function getCurrentRoleAttribute()
{
  return $this->roles->first();
}
```

**Is there anything I'm missing ?**

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
