### ISSUE TITLE
return back() is broken in laravel 10.3 version

### ISSUE THREAD

**Issue by aknEvrnky** [laravel/framework#46388]
- Laravel Version: 10.3.0
- PHP Version: 8.2.3 with FPM apache
- Database Driver & Version: Ver 15.1 Distrib 10.2.44-MariaDB, for Linux (x86_64) using readline 5.1
- OS: CentOS 7 with Plesk

### Description:
In my controllers, return back() redirects to homepage instead of previous page. This bug only produced on server side for laravel 10.3 version. When I downgrade to laravel 10.2, there are no any mis redirect.

### Steps To Reproduce:
I change laravel/framework version to 10.2 from composer.json. There are no anything unusual.
Then, I change the version to 10.3 or ^10.0.
return back() function redirects to homepage.

But It only happens in my production server which is CentOS 7 with plesk.

**Comment by browner12** [comment]
Bug is due to this PR:

https://github.com/laravel/framework/commit/552f353676f50228f639955421d4d1ca9faca689

My guess is because it's looking at "url" and not "route" it can't distinguish between the same PATH with a different METHOD.  

I am getting the same error, when a POST route is trying to redirect back to the GET route with the same path.

**Comment by aknEvrnky** [comment]
https://github.com/aknEvrnky/laravel-10-3-is-broken.git
you can test is with this repo. Redirect back method fails again in local machine.

**Comment by rodrigopedra** [comment]
looking into that

**Comment by rodrigopedra** [comment]
@aknEvrnky 

Can you give more details on how to reproduce this? I tested with the home button, and it seems to be working


https://user-images.githubusercontent.com/5470108/223556420-8a4335fa-ea0e-430c-b61c-88089f2c6fd9.mp4

**Comment by rodrigopedra** [comment]
nevermind, I just got what is the problem now. working in a fix

**Comment by rodrigopedra** [comment]
Fix sent. Fingers crossed =)

**Comment by driesvints** [comment]
10.3.1 should revert the faulty pr.

**Comment by martinbean** [comment]
You wouldn’t believe how long I spent battling this, thinking I was going crazy…

**Comment by rodrigopedra** [comment]
Sorry to hear that @martinbean 😢
