### ISSUE TITLE
php artisan test --env=testing only using .env instead of .env.testing

### ISSUE THREAD

**Issue by drewg2009** [laravel/framework#46386]
- Laravel Version: 10.3.0
- PHP Version: 8.2.1
- Database Driver & Version:
mysql 
### Description:
When I run `php artisan test --env=testing`

It always uses the .env instead of the .env.testing file

The only way I can fix it is overriding the env in the `phpunit.xml` with 

`      <env name="APP_ENV" value="testing"/>
`

### Steps To Reproduce:

1. Follow https://laravel.com/docs/10.x/testing#environment to create .env.testing file
2. Create tests using database docs
3. run `php artisan test --env=testing`

**Comment by nunomaduro** [comment]
Can you share your "composer.json" file please?

**Comment by driesvints** [comment]
@drewg2009 we couldn't manage to reproduce this for the latest Laravel v10 version sorry. Everything is working as expected. We did manage to reproduce this for Laravel v9 and are looking into that.

**Comment by drewg2009** [comment]
@driesvints can you reopen this so I can share my composer.json and get more support? 

this is still not resolved

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by millancore** [comment]
@driesvints could you please share the commit with the fix for the previous versions.  Thanks

**Comment by MariaMozgunova** [comment]
On local development, I was caching config files with `php artisan config:cache`. This command loads `.env` file.
As explained [here](https://stackoverflow.com/a/70388663/13907973), Laravel does not load `.env` file if one was already loaded.

I managed to use `.env.testing` if I run `php artisan config:clear` before running tests.

It is also worth noting, that when upgrading to Laravel 10 from previous versions, you would need to upgrade some composer dev dependencies and update `phpunit.xml` file. Refer to [Laravel docs](https://laravel.com/docs/10.x/upgrade#updating-dependencies).

> Furthermore, if you wish to use [PHPUnit 10](https://phpunit.de/announcements/phpunit-10.html), you should delete the processUncoveredFiles attribute from the <coverage> section of your application's phpunit.xml configuration file. Then, update the following dependencies in your application's composer.json file:
> 
> - nunomaduro/collision to ^7.0
> - phpunit/phpunit to ^10.0
