### ISSUE TITLE
Incorrect authentication credential error messages not returned in Laravel 10.3.0

### ISSUE THREAD

**Issue by bordermedia** [laravel/framework#46393]
- Laravel Version: 10.3.0
- PHP Version: 8.1.15
- Laravel Breeze: 1.19.2

### Description:

When a user enters incorrect authentication credentials (ie. wrong email or wrong password), they are just redirected to the login page again with no error messages returned.

In Laravel 10.2.0, when incorrect credentials are entered, you get a 'Whoops! Something went wrong' error message and a 'These credentials do not match our records' error message.

### Steps To Reproduce:

- Upgrade to Laravel 10.3.0.
- Try and log in with incorrect credentials. eg. wrong password.
- No error messages received.
- Downgrade to Laravel 10.2.0.
- Error messages are received as expected.

**Comment by jshah4517** [comment]
I believe related to https://github.com/laravel/framework/issues/46388

**Comment by driesvints** [comment]
10.3.1 should revert the faulty pr
