### ISSUE TITLE
Str::kebab return wrong kebab-case if string has number 

### ISSUE THREAD

**Issue by arttiger** [laravel/framework#46399]
- Laravel Version: 9.45.1
- PHP Version: 8.1.0
- Database Driver & Version:

### Description:

See title

### Steps To Reproduce:

1. Pass string with number to the Str::kebab

### Workaround:

```
$str = 'string with 1 number';
echo(Str::kebab($str)); // string-with1-number
```

There must be a correct kebab-case "string-with-1-number"

**Comment by driesvints** [comment]
It seems we have no intention of changing this behavior ourselves, sorry.
