### ISSUE TITLE
scopeBindings should not break silently when there is an invalid parent route

### ISSUE THREAD

**Issue by alexking** [laravel/framework#46404]
- Laravel Version: 10.3.2
- PHP Version: 8.2.3
- Database Driver & Version: 

### Description:
`->scopeBindings()` checks that models in a route are related to eachother - this can be handy to reduce boilerplate checks in the controller. It only works if model bindings are in the route sequentially - so `{parent}/{child}` or `{parent}/and/{child}`. However, if one adds an additional plain parameter between the related ones, it silently stops checking that the two models are related - so `{parent}/{plain}/{child}` would no longer enforce scoped bindings. This makes it easy to accidentally break the bindings.

Instead this should throw an exception if `->enforcesScopedBindings()` is true and the parent route isn't valid for a binding, to alert the developer there is an issue they should fix or turn off scope bindings. See this section in [`ImplicitRouteBinding`]( https://github.com/laravel/framework/blob/be2ddb5c31b0b9ebc2738d9f37a9d4c960aa3199/src/Illuminate/Routing/ImplicitRouteBinding.php#L49) for where that would be modified.

### Steps To Reproduce:
Add a plain parameter between two bound parameters with `scopeBindings()` on in a route.

[Demo repository](https://github.com/alexking/scoped-bindings-bug-report) is available here - tests are setup to pass to demonstrate the issue.

**Comment by driesvints** [comment]
Thank you for reporting. This isn't an actual bug but the expected behavior. If you'd like the framework to explicitly warn about this by throwing an exception you can attempt a PR. Otherwise we'd appreciate a PR to the docs to make this more clear. Thanks
