### ISSUE TITLE
datetime cast do not handle timezone correctly 

### ISSUE THREAD

**Issue by ivanomatteo** [laravel/framework#46401]
- Laravel Version: 10
- PHP Version: 8.1
- Database Driver & Version: mysql 8

### Description:

When using datetime cast, and the format of the assigned value contains also the timezone,
for example "2023-01-01T23:00:00.000Z" 
the conversion do not consider the configured app timezone.

### Steps To Reproduce:

**config: app.timezone = 'Europe/Rome'**

```
class FooModel extend Model {

  protected $casts [
     'date_time_field'=>'datetime',
  ];

} 

// .....

$m = new FooModel;

$m->date_time_field = '2023-01-01T23:00:00.000Z'; // UTC string
// internally became: 2023-01-01 23:00:00

$date = $m->date_time_field;
// $date is:
// Illuminate\Support\Carbon @1672610400 {#4851
//     date: 2023-01-01 23:00:00.0 Europe/Rome (+01:00),
// }

```

### Suggested BugFix
this could be fixed changing this line:
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1385

from this:
`return $date ?: Date::parse($value);`

to this:
`return $date ?: Date::parse($value)->timezone(config('app.timezone'));`

**Comment by ivanomatteo** [comment]
**This is a problem also using UTC as app.timezone !!! **

in fact:


**config: app.timezone = 'UTC'**

```
class FooModel extend Model {

  protected $casts [
     'date_time_field'=>'datetime',
  ];

} 

// .....

$m = new FooModel;

$m->date_time_field = '2023-01-01T23:00:00+03:00';
// internally became: 2023-01-01 23:00:00

$date = $m->date_time_field;
// $date is:
// Illuminate\Support\Carbon @1677538800 {#4857
//    date: 2023-02-27 23:00:00.0 UTC (+00:00),
//  }

```

**Comment by ankurk91** [comment]
Similar issue
https://github.com/laravel/framework/issues/45201

**Comment by ivanomatteo** [comment]
> Similar issue
> 
> https://github.com/laravel/framework/issues/45201

Yes, the fix I suggested should solve also that.

**Comment by driesvints** [comment]
Please see https://laravel.com/docs/10.x/eloquent-mutators#date-casting-and-timezones

**Comment by ivanomatteo** [comment]
> Please see https://laravel.com/docs/10.x/eloquent-mutators#date-casting-and-timezones

I'm agree that's better to use UTC, ok.

Regardless of the configured timezone,  the problem is the loss of information:


```
> $d = Date::parse('2023-01-01T23:00:00+03:00')
= Illuminate\Support\Carbon @1672603200 {#4920
    date: 2023-01-01 23:00:00.0 +03:00,
  }

> $m->from_date = $d
= Illuminate\Support\Carbon @1672603200 {#4920
    date: 2023-01-01 23:00:00.0 +03:00,
  }

> $m->from_date
= Illuminate\Support\Carbon @1672614000 {#4914
    date: 2023-01-01 23:00:00.0 UTC (+00:00),
  }

```

**the resulting date, is not coverted in UTC,  it's simply wrong!!!**
