### ISSUE TITLE
Storage link removed

### ISSUE THREAD

**Issue by stefaanbeernaert** [laravel/framework#46414]
- Laravel Version:10.0
- PHP Version: 8.1.0
- Database Driver & Version:

### Description:
Everytime i run php artisan migrate:fresh --seed i need to redo php artisan storage:link.
The map is still there but it doesn't recognize it. The link between the storage map and public map is broken.
I have to delete the public map and redo php artisan storage:link to fix it.

**Comment by marcellus-ku-283** [comment]
It should work fine. You must miss a step OR something in your setup.

I reproduce this issue and in mine with a fresh laravel set-up, it is working fine.
Laravel Version:10.0.4
PHP Version: 8.1.16

I tried the same as you said.
I run the below commands,
- php artisan migrate:fresh --seed
- php artisan storage:link

Then I test the profile user's profile picture working fine. ( For quick, I used jetstream livewire set up for media test).
Then I again only run ```php artisan migrate:fresh --seed``` it worked no need to do storage:link command again.

Thanks.

**Comment by stefaanbeernaert** [comment]
Did u test by uploading an image? Because it does say the link is still there but it just doesn't move it to the public map. So i remove the public map do again php artisan storage:link and then it works i upload an image and it shows in the public map.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
