### ISSUE TITLE
Class "App\Http\Controllers\SaleController" not found

### ISSUE THREAD

**Issue by ushab6** [laravel/framework#46421]
- Laravel Version: 9.0.0
- PHP Version: 8.0.25
- Database Driver & Version:

### Description:
I have SaleController.php  and Quickpick.controller.php
when I am using the 
class QuickpickController extends SaleController{

}
In my QuickpickController
It is showing me the error

Class "App\Http\Controllers\SaleController" not found 
What do I need to include in my QuickpickController

**Comment by zulfikar-ditya** [comment]
@ushab6 please describe your error, like with you related file like ```web.php``` or ```api.php``` or ```...controllers.php```. maybe this related links helps you.

[mising namespace](https://stackoverflow.com/questions/33711379/class-controller-not-found-in-laravel-5)
github issue #34204

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
