### ISSUE TITLE
Declaration mismatch for routing controller

### ISSUE THREAD

**Issue by MordiSacks** [laravel/framework#46446]
Declaration of Illuminate\Support\Traits\Macroable::__call($method, array $parameters) must be compatible with Illuminate\Routing\Controller::__call($method, $parameters)

- Laravel Version: 10.3.3
- PHP Version: 8.2.3
- Database Driver & Version: MariaDB 10.10.3

### Description:
It seems like we have a mismatch between 
https://github.com/laravel/framework/blob/v10.3.3/src/Illuminate/Routing/Controller.php
and
https://github.com/laravel/framework/blob/v10.3.3/src/Illuminate/Macroable/Traits/Macroable.php

### Steps To Reproduce:
I encounterd this issue while using `tightenco/ziggy` on [dev-master](https://github.com/tighten/ziggy/commit/ded224950c301d6791e93bde5f9f43ea139c160a)
simply calling `(string)(new Ziggy());`

Initially I believed this was an issue with Ziggy, but after finding this mismatch I bealive this is an issue with Laravel

**Comment by driesvints** [comment]
Thank you. I've sent in a PR to revert this.
