### ISSUE TITLE
[Notification] Failing the sending process if one channel failed

### ISSUE THREAD

**Issue by balazs1396** [laravel/framework#46447]
There is no error handling in each channels or here.: https://github.com/laravel/framework/blob/10.x/src/Illuminate/Notifications/NotificationSender.php#L104

If you have multiple channel, like mail, fcm and the first one (mail) failing (For example mailing issue) the other channels (on this example only one, the fcm) will not be fired, so every notification will lost.
If I extend the MailChannel and override the send() method with try catch block, the problem is solved, but the NotificationSent event fired. So this is solved the problem, because i want to get NotificationFailed event.

**Comment by ankurk91** [comment]
Feel free to send a PR

**Comment by driesvints** [comment]
We'd appreciate a PR, thanks.
