### ISSUE TITLE
Validator seems to hang php-fpm

### ISSUE THREAD

**Issue by Fossil01** [laravel/framework#46444]
- Laravel Version: 10.3.3
- PHP Version: 8.2.3 (ARM64 on Apple M1)
- Database Driver & Version: MySQL10.11.2-MariaDB-1:10.11.2+maria~ubu2004 (ARM64 on Apple M1)
- Environment: Ubuntu ARM64 using latest Laravel Homestead on MacOS 13.2.1 with Parallels Desktop 18.2.0 on an Apple M1 Pro CPU.

### Description:
I am in the process of upgrading my project from Laravel 9.x to 10.x. I have noticed that my registration form does not work anymore. I am not 100% sure if this started with Laravel 10 as I haven't tried to register a test user for ages.

Anyway. My whole application seems to run fine except the register function. Whenever I register a user and click the submit button the browser just hangs there, loading endlessly and finally timing out with a `504 Gateway Time-out` error.

I did some debugging and it seems to hang on `$validator->fails()` as shown in this snippet:

```php
        $validator = Validator::make($request->all(), [
            'username' => ['required', 'string', 'min:5', 'max:255', 'unique:users'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users', 'indisposable'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);


        if ($validator->fails()) {
            $error = $validator->errors()->getMessages();
            $request->flash(); // Flash old input back to session

            return $this->showRegistrationForm($request, $error);
        }
```

When I boil it down to an internal function in the Validator package specifically it seems get hung up on this if() condition:
```php
if ($this->shouldBeExcluded($attribute))
```
On line 411 of this file: https://github.com/illuminate/validation/blob/master/Validator.php#L411
I have tried looking into it with XDebug but as soon as it want's to run the validator the request just hangs, XDebug never even sees it.

After retrying the request many times when I was trying to debug this, PHP8.2-FPM just stopped working entirely. I had to restart the service to get HTTP requests working again.

I have tried reinstalling the whole Homestead box, upgrading it to the latest version, tried using PHP 8.1.16 too. Not much useful info from FPM's error log:

```
[12-Mar-2023 19:50:42] NOTICE: fpm is running, pid 1343123
[12-Mar-2023 19:50:42] NOTICE: ready to handle connections
[12-Mar-2023 19:50:42] NOTICE: systemd monitor interval set to 10000ms
[12-Mar-2023 19:57:20] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
[12-Mar-2023 19:57:42] NOTICE: Terminating ...
[12-Mar-2023 19:57:42] NOTICE: exiting, bye-bye!
```

So I am not sure if this is a Laravel, PHP or FPM thing. But I lack the skills to figure this out...

### Steps To Reproduce:
I wish I knew. Help? :-)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by cennis-ck** [comment]
> So I am not sure if this is a Laravel, PHP or FPM thing. But I lack the skills to figure this out...

this is happening to me too! only on custom validation, but on 8.1 fpm. Did you figure it out??
