### ISSUE TITLE
Illuminate/Contracts/Validation/Validator missing getTranslator() method

### ISSUE THREAD

**Issue by nie7321** [laravel/framework#46452]
- Laravel Version: 9.27.0
- PHP Version: 8.1.5
- Database Driver & Version: n/a

### Description:
In [`Illuminate/Validation/ValidationException::summarize()`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Validation/ValidationException.php#L86), the `$validator` argument is declared as [`Illuminate/Contracts/Validation/Validator`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Contracts/Validation/Validator.php) in the docblock. However, this method calls `getTranslator()`, which is not part of the contract -- only the implementation.

When implementing my own validator using the contract, I didn't know to implement that. I saw some occasional failures when it tried to run `summarize()`. Easy to fix now that I know, but I think the interface should include the `getTranslator()` method.

**Comment by X-Coder264** [comment]
This was fixed by https://github.com/laravel/framework/pull/46378 for Laravel 11.

**Comment by nie7321** [comment]
Ah, splendid! I had only looked at 10.x.
