### ISSUE TITLE
SQL Syntax Error with CanBeOneOfMany if primaryKey of related model is null

### ISSUE THREAD

**Issue by smecnarowski** [laravel/framework#46463]
- Laravel Version: 8.3.4 (Lumen)
- PHP Version: 8.0
- Database Driver & Version:

### Description:
SQL parsers adds empty column to query. Problems exists in core Laravel till today as I see in repo. 

### Steps To Reproduce:
Add relation to your model

```
public function test()
{
    return $this->hasOne(Relation::class)->ofMany('sorted_column');
}
```

Relation have to be with nulled primaryKey

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Relation extends Model
{
    protected $primaryKey = null;

    public $incrementing = false;

    public $timestamps = false;
}
```

Problems starts when `$keyName` became null in here https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Relations/Concerns/CanBeOneOfMany.php#L77

Possible solution is to ignore null here https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Relations/Concerns/CanBeOneOfMany.php#L93 
```
if (!$column) {
    continue;
}
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by driesvints** [comment]
Please also don't open Lumen issues on the framework repo.

**Comment by smecnarowski** [comment]
@driesvints I mentioned in first paragraph "Problems exists in core Laravel till today as I see in repo." So with almost 100% sure it exists in 10.x also.

**Comment by smecnarowski** [comment]
@driesvints are you going to recheck it for 10.x ?

**Comment by smecnarowski** [comment]
still in 11.x
