### ISSUE TITLE
MYSQL 8 Migrating text to alternative text type does not change column

### ISSUE THREAD

**Issue by liamh101** [laravel/framework#46492]
- Laravel Version: 10.3.3
- PHP Version: 8.2.3
- Database Driver & Version: MYSQL 8.0.32
- `doctrine/dbal` Version: 3.6.1

### Description:

The column type change will not be made during a text column's migration to medium or long text. Keeping the column as a text type.

Stepping through the process, `Illuminate\Database\Schema\Grammars\ChangeColumn` class line 44 `$tableDiff->isEmpty()` returns `true`. 

Not sure what other columns this affects. This bug occurred during my migration process to Laravel 9 to 10.

### Steps To Reproduce:

1. Set MySQL config in `database.php` as follows (based on MySQL8 docker image): 
```
        'mysql' => [
            'driver' => 'mysql',
            'url' => null,
            'host' => 'mysql',
            'port' => '3306',
            'database' => 'test',
            'username' => 'root',
            'password' => 'root',
            'unix_socket' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? [
                PDO::MYSQL_ATTR_SSL_CA => null,
                PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 0,
            ] : [],
        ],
```
2. Create a migration that creates a table with three text columns.
3. Create another migration changing these columns:
 ```
    public function up(): void
    {
        Schema::table('tableName', static function (Blueprint $table) {
            $table->mediumText('col1')->change();
            $table->longText('col2')->change();
            $table->mediumText('col3')->change();
        });
    }
```
4. Run migrations.
5. Columns are still `text` type.

**Comment by liamh101** [comment]
Here's a repo that reproduces the error: https://github.com/liamh101/laravel-column-bug

**Comment by ankurk91** [comment]
See https://github.com/laravel/framework/pull/45487

**Comment by liamh101** [comment]
Thanks for the response. I'll remove dbal from our codebase and check if it doesn't affect anything else. 

However, I think this problem should be fixed. On closer inspection, what I believe is happening is the current type and new type is checked using an enum in the dbal library. However, any text column generates the same enum. Meaning the migration thinks nothing has changed.

If there's no movement by the end of today I'll spend some time and get a fix for this over the weekend.

**Comment by driesvints** [comment]
@hafezdivandari what are your thoughts here?

**Comment by liamh101** [comment]
@hafezdivandari @driesvints spoke too soon. 

It does fix the text type bug. However, it has introduced another bug in which a nullable column was not set or reverted. I need to investigate exactly what's happening. Would you like me to append this issue or create a new one?

**Comment by hafezdivandari** [comment]
@liamh101 Would you please check the [L10 documentation on modifying column](https://laravel.com/docs/10.x/migrations#modifying-columns) (it's different than L9), or check the related PR #45487 for more details on the topic.

**Comment by hafezdivandari** [comment]
@liamh101 no problem. Unfortunately this bug on `doctrine/dbal` is not easy to fix (maybe not possible) on Laravel side. Maybe you want to report this issue on their repo instead?

**Comment by mreduar** [comment]
I've also recently run into this problem with a `composer update` I've done in a multitenant project, all the tests and seeders broke because the column can't be changed anymore, in my case I was trying to change from an `enum` to a `string`, but it failed. it was left as `enum`, that was what broke it until i saw the PR with native support and tied the threads.

Doing what @hafezdivandari suggests
```php
Schema::useNativeSchemaOperationsIfPossible()

// migrations here

Schema::useNativeSchemaOperationsIfPossible(false);
```
Solve the problem. thanks for that
