### ISSUE TITLE
accepted_if validation rule when other is bool

### ISSUE THREAD

**Issue by medilies** [laravel/framework#46494]
- Laravel Version: 9.0
- PHP Version: 8.1.6

### Description:

This is considered valid

```php
\Validator::make(['a' => true, 'b' => true], ['a' => 'bool', 'b' => 'accepted_if:a,55'])->validate()
```

**Comment by driesvints** [comment]
This is the expected behavior. `b` is already true so `accepted_if` passes. `accepted_if` only returns false if the field under validation isn't `yes`, `on`, `1` or `true`.
