### ISSUE TITLE
BufferedConsoleOutput gets ignored when using createProgressBar

### ISSUE THREAD

**Issue by riyuk** [laravel/framework#46501]
- Laravel Version: 10.0.0
- PHP Version: 8.1.15

### Description:

We have a Job which calls Artisan Commands. The purpose of this is to display the output of the job to the User who is calling it.
Jobs are Queued and proccessed by the Workers.

The Artisan Command is issued with `Artisan::call($this->command, $this->args, tap(new StreamedOutput(), fn($out) => $out->setHistory($this->historyId)));`.

The StreamedOutput Class is pretty Simple:
```php
use Illuminate\Console\BufferedConsoleOutput;
class StreamedOutput extends BufferedConsoleOutput {
    public int $historyId;

    public function setHistory(int $historyId): void
    {
        $this->historyId = $historyId;
    }

    public function doWrite(string $message, bool $newline)
    {
        event(new Bufferoutput(message: $message . ($newline ? "\n" : ""), historyId: $this->historyId));

        // we should not call parent -> since this would output everything to the console
        // parent::doWrite($message, $newline);
    }
}
```

This way we can listen for Bufferoutput-Events and write the Message to the Database while also broadcasting it to Pusher for viewing a live console output.

This works for Artisan-Commands which call `$this->info()` or `$this->table()` pretty good.
The problem we have now is: when we use `$this->getOutput()->createProgressBar` in our Artisan-Commands the output of that progressbar goes into the Worker instead of the StreamedOutput. We can see the output on the worker for the Progressbar when we run `php artisan queue:work` manually. 
Everything else gets redirected to the StreamedOutput just fine.

If we comment out Line 72 in `symfony/console/Helper/ProgressBar.php` which overwrites the Output by:
```php
if ($output instanceof ConsoleOutputInterface) {
    $output = $output->getErrorOutput(); // <-- comment out this line
}
``` 
everything works as expected again.

My Question is now: Is this rather a problem of Symfony or can Laravel do something about that?
Are we missing something and we are somehow able to also set the error-output to our own Buffered-Output?

**Comment by nunomaduro** [comment]
Hey, before we proceed any further, would you mind giving one of the support channels listed below a shot? If you think you've come across a bug, it'd be super awesome if you could open a pull request to get it fixed. Unfortunately, we're pretty busy at the moment, so we might not be able to help you out right away.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
