### ISSUE TITLE
Http Client `DELETE` Method Doesn't Add `query` Parameters

### ISSUE THREAD

**Issue by ericwang401** [laravel/framework#46506]
- Laravel Version: 9.52.4
- PHP Version: 8.2.3
- Database Driver & Version:
  - MySQL 8.0.29

### Description:

```php
$this->getHttpClient()
            ->withUrlParameters([
                'node' => $this->node->cluster,
                'server' => $this->server->vmid
            ])
            ->delete('/api2/json/nodes/{node}/qemu/{server}', [
                'destroy-unreferenced-disks' => true, 'purge' => true, 'skiplock' => true,
            ])
            ->json();
```

The Laravel HTTP Client doesn't appear to add the payload in the second argument to the `delete` method as query parameters to the request. Though, I am not completely sure that this is the case from my superficial analysis (I can't seem to make sense of the Http Client's code nor am I getting enough information from the `dd` method on the Http Client to properly determine the issue).

When I send the request to the API service ([Proxmox Virtual Environment](https://proxmox.com/en/proxmox-ve)), I receive a HTTP error 501. Here's the contents of the `dd` method on the Http Client. Information like the `base_uri` and any confidential information was redacted and filled with placeholder data.

```
array:13 [ // vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:1102
  "connect_timeout" => 5
  "http_errors" => false
  "timeout" => 15
  "verify" => false
  "base_uri" => "https://redacted.com:8006/"
  "laravel_data" => array:3 [
    "destroy-unreferenced-disks" => true
    "purge" => true
    "skiplock" => true
  ]
  "on_stats" => Closure($transferStats)^ {#5048
    class: "Illuminate\Http\Client\PendingRequest"
    this: Illuminate\Http\Client\PendingRequest {#5019 …}
  }
  "synchronous" => true
  "handler" => GuzzleHttp\HandlerStack^ {#5033
    -handler: Closure(RequestInterface $request, array $options): PromiseInterface^ {#5039
      returnType: "GuzzleHttp\Promise\PromiseInterface"
      class: "GuzzleHttp\Handler\Proxy"
      use: {
        $default: Closure(RequestInterface $request, array $options): PromiseInterface^ {#5026 …}
        $streaming: GuzzleHttp\Handler\StreamHandler {#5036 …}
      }
    }
    -stack: array:7 [
      0 => array:2 [
        0 => Closure(callable $handler): callable^ {#5040
          returnType: "callable"
          class: "GuzzleHttp\Middleware"
          use: {
            $bodySummarizer: null
          }
        }
        1 => "http_errors"
      ]
      1 => array:2 [
        0 => Closure(callable $handler): RedirectMiddleware^ {#5041
          returnType: "GuzzleHttp\RedirectMiddleware"
          class: "GuzzleHttp\Middleware"
        }
        1 => "allow_redirects"
      ]
      2 => array:2 [
        0 => Closure(callable $handler): callable^ {#5042
          returnType: "callable"
          class: "GuzzleHttp\Middleware"
        }
        1 => "cookies"
      ]
      3 => array:2 [
        0 => Closure(callable $handler): PrepareBodyMiddleware^ {#5043
          returnType: "GuzzleHttp\PrepareBodyMiddleware"
          class: "GuzzleHttp\Middleware"
        }
        1 => "prepare_body"
      ]
      4 => array:2 [
        0 => Closure($handler)^ {#5045
          class: "Illuminate\Http\Client\PendingRequest"
          this: Illuminate\Http\Client\PendingRequest {#5019 …}
        }
        1 => ""
      ]
      5 => array:2 [
        0 => Closure($handler)^ {#5046
          class: "Illuminate\Http\Client\PendingRequest"
          this: Illuminate\Http\Client\PendingRequest {#5019 …}
        }
        1 => ""
      ]
      6 => array:2 [
        0 => Closure($handler)^ {#5047
          class: "Illuminate\Http\Client\PendingRequest"
          this: Illuminate\Http\Client\PendingRequest {#5019 …}
        }
        1 => ""
      ]
    ]
    -cached: Closure($request, array $options)^ {#5060
      class: "GuzzleHttp\Middleware"
      use: {
        $handler: GuzzleHttp\RedirectMiddleware {#5059 …}
        $bodySummarizer: null
      }
    }
  }
  "cookies" => GuzzleHttp\Cookie\CookieJar^ {#5049
    -cookies: []
    -strictMode: false
  }
  "allow_redirects" => array:5 [
    "max" => 5
    "protocols" => array:2 [
      0 => "http"
      1 => "https"
    ]
    "strict" => false
    "referer" => false
    "track_redirects" => false
  ]
  "decode_content" => true
  "idn_conversion" => false
]
```

Although [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) specifies that a `DELETE` request may have a body, it seems like many (from my limited search) prefer to use query parameters over using a body.

A workaround I am using is:
```
$this->getHttpClient(options: [
            'query' => [
                'destroy-unreferenced-disks' => true,
                'purge' => true,
            ]
        ])
            ->withUrlParameters([
                'node' => $this->node->cluster,
                'server' => $this->server->vmid
            ])
            ->delete('/api2/json/nodes/{node}/qemu/{server}')
            ->json();
```

I don't feel like this is an ideal workaround and would love to use the expressive syntax of Laravel.

Here are links to the code containing the mentioned snippets.
- [The code](https://github.com/ConvoyPanel/panel/blob/98b44f56b0dc2fdedb220b92e956d27dc0fe3173/app/Repositories/Proxmox/Server/ProxmoxServerRepository.php) where I sent the request with the payload in the `delete` method
- [The code](https://github.com/ConvoyPanel/panel/blob/develop/app/Repositories/Proxmox/Server/ProxmoxServerRepository.php) where I sent the request with the workaround
- [`getHttpClient`](https://github.com/ConvoyPanel/panel/blob/develop/app/Repositories/Proxmox/ProxmoxRepository.php#L68)

### Steps To Reproduce:

A reproduction is possible by running
```php
$httpClient = Http::withOptions([
            'verify' => false,
            'base_uri' => "https://YOUR_DOMAIN/",
            'timeout' => 15,
            'connect_timeout' => 5,
            'headers' => [
                'Authorization' => 'DUMMY AUTHORiZATION HEADER',
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'User-Agent' => null,
            ],
        ]);

$httpClient->delete('/route', [
    'query-parameter' => 'test'
]);
```

If you want a complete reproduction, please install my app using [my documentation](https://docs.convoypanel.com/). It uses Docker containers and the installation process is mostly copy-paste with few interventions to add your desired configuration.

Since my app interacts with an external service, you need to also create a VM, dedicated server, or bare metal that's running ([Proxmox Virtual Environment](https://proxmox.com/en/proxmox-ve)). If you have my app `APP_ENV` to `production`, make sure you generate trusted TLS certificates on the Proxmox Virtual Environment server.

You can then add the Proxmox node to my app using these [documentation](https://docs.convoypanel.com/guide/deployment/adding-nodes.html).

**Comment by ericwang401** [comment]
> have you tried this?
> 
> ```
> $url = "/api2/json/nodes/{$this->node->cluster}/qemu/{$this->server->vmid}?destroy-unreferenced-disks=true&purge=true&skiplock=true";
> 
> $response = $this->getHttpClient()
>     ->withUrl($url)
>     ->json();
>     
> ```

Hello, I did think about that solution but it just doesn't seem right or elegant given the style of its other features, like Url parameter binding, method utilities like `withOptions`, `withBody`, etc.

I plan on also making the query parameters vary based on arguments because this HTTP request is running inside of a reusable function, so the solution you proposed is not a very great workaround.

I would love to contribute a pull request but the code for the http client is confusing to understand-at least for me.

**Comment by andremralves** [comment]
I took a look in the code and saw that by default the `$data` array that you pass with the queries in the delete method is sent as a json to the [Guzzle](https://docs.guzzlephp.org/en/stable/) library to handle it `["json" => $data]`:

```php
public function delete(string $url, $data = [])
{
    return $this->send('DELETE', $url, empty($data) ? [] : [
        // bodyFormat will be "json"
        $this->bodyFormat => $data,
    ]);
}
```
So the Guzzle library will create a request with a json as body. 

In the other hand, the get method sends the data as a query:
```php
public function get(string $url, $query = null)
{
    return $this->send('GET', $url, func_num_args() === 1 ? [] : [
        'query' => $query,
    ]);
}
```
Maybe a solution would be to add an optional third parameter to the delete method that tells whether you want to send the request as a query string or using a json body.

**Comment by cosmastech** [comment]
```php
Http::bodyFormat('query')->delete('your-url', [
    'param1' => 'hello',
    'param2' => 'world',
]);
```

**Comment by cosmastech** [comment]
@ericwang401 I think that's probably the best solution and I would guess there's a very slim chance of an accepted PR where there's another argument added to the `PendingRequest@delete()` method.

**Comment by ericwang401** [comment]
> @ericwang401 I think that's probably the best solution and I would guess there's a very slim chance of an accepted PR where there's another argument added to the `PendingRequest@delete()` method.

I see. I think that is a fair solution! I was also concerned about how the elegant syntax would need to be changed.

Thank you for your feedback!

**Comment by driesvints** [comment]
Think we can close this one. Thanks
