### ISSUE TITLE
CORS check failed on laravel dependency Asm89\Stack

### ISSUE THREAD

**Issue by number201724** [laravel/framework#46510]
- Laravel Version: v9.52.4
- PHP Version: 8.1.16
- Database Driver & Version:

### Description:
The isOriginAllowed function of the CorsService class in laravel dependency package Asm89\Stack is wrongly judged.

### Steps To Reproduce:
```

    public function isOriginAllowed(Request $request): bool
    {
        if ($this->options['allowedOrigins'] === true) {
            return true;
        }

        if (!$request->headers->has('Origin')) {
            return false;
        }

        $origin = $request->headers->get('Origin');

        \Log::info($origin);
        \Log::info($this->options['allowedOrigins']);

        if (in_array($origin, $this->options['allowedOrigins'])) {
            return true;
        }

        foreach ($this->options['allowedOriginsPatterns'] as $pattern) {
            if (preg_match($pattern, $origin)) {
                return true;
            }
        }

        return false;
    }

```

Log::info($origin);
Log::info($this->options['allowedOrigins']);

[2023-03-18 18:39:51] local.INFO: http://localhost:3000  
[2023-03-18 18:39:51] local.INFO: array (
  0 => '*.xxxyyyzzz.net',
  1 => '127.0.0.1:3000',
  2 => 'localhost:3000',
  3 => '*.xxxyyyzzz.net:60080',
  4 => '*.bilibili.com',
)  

failed on:
```
        if (in_array($origin, $this->options['allowedOrigins'])) {
            return true;
        }
```

cors.php:

`'allowed_origins' => ['*.xxxyyyzzz.net', '127.0.0.1:3000', 'localhost:3000', '*.xxxyyyzzz.net:60080', '*.bilibili.com'],`

So both http:// and https:// need to be added here, but the documentation doesn't say that.

**Comment by Angel5a** [comment]
Hi, @number201724 

First of all. This isn't issue of Laravel framework, and should be closed here. You should ask it in [Asm89\Stack](https://github.com/asm89/stack-cors).

Second. The problem is you use wrong configuration. `allowedOrigins` designed to specify **exact** match, and not a partial. So you should place `http://localhost:3000` and not just a `'localhost:3000'` (pay attention on schema). In you need a partial match? like in `'*.bilibili.com'`, then you should place in `allowedOriginsPatterns` config in form of preg expression `'/.*\.bilibili\.com$/'`.

**Comment by number201724** [comment]
> Hi, @number201724
> 
> First of all. This isn't issue of Laravel framework, and should be closed here. You should ask it in [Asm89\Stack](https://github.com/asm89/stack-cors).
> 
> Second. The problem is you use wrong configuration. `allowedOrigins` designed to specify **exact** match, and not a partial. So you should place `http://localhost:3000` and not just a `'localhost:3000'` (pay attention on schema). In you need a partial match? like in `'*.bilibili.com'`, then you should place in `allowedOriginsPatterns` config in form of preg expression `'/.*\.bilibili\.com$/'`.

Ok, but hopefully this is done in the docs, otherwise it's easy to get people wrong.
