### ISSUE TITLE
Methods for Eloquent Accessors & Mutators do not throw an exception when Attribute class is not imported

### ISSUE THREAD

**Issue by debiprasad** [laravel/framework#46521]
- Laravel Version: 10.4.1/9.52.4
- PHP Version: 8.1.13

### Description:

```
<?php
 
namespace App\Models;
 
use Illuminate\Database\Eloquent\Model;
 
class User extends Model
{
    /**
     * Interact with the user's first name.
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function firstName(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => ucfirst($value),
            set: fn ($value) => strtolower($value),
        );
    }
}
```

Like the example above, if the developer has forgotten to import the `Illuminate\Database\Eloquent\Casts\Attribute` class, the `Attribute` class should be aliased to `App\Models\Attribute` and it should throw an exception. Instead, it does not throw any exceptions though accessors & mutators don't work.

### Steps To Reproduce:

Add the following code in the User model. 

```
    /**
     * Interact with the user's first name.
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function firstName(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => ucfirst($value),
            set: fn ($value) => strtolower($value),
        );
    }
```

Save and open Psy Shell: `php artisan tinker`. Run the following code one by one in the Psy Shell.

```
$u = new User()

$u->first_name = "DEBIPRASAD"

$u->first_name
```

The last code will return `"DEBIPRASAD"` and it won't throw an exception that `App\Models\Attribute` was not found.

https://github.com/debiprasad/bug-report

**Comment by driesvints** [comment]
I'm not sure this really qualifies as a bug in the framework sorry. Please make sure you import that namespace. If you can figure out on how to improve this UX we'd appreciate a PR, thanks.
