### ISSUE TITLE
Cursor Paginator $paginator->onFirstPage() return false on the Homepage

### ISSUE THREAD

**Issue by sophy** [laravel/framework#46523]
- Laravel Version: 10.4.1
- PHP Version: 8.2.3
- Database Driver & Version: MySQL

### Description:

I am using **Cursor Pagination** on my application with the default pagination view. It normally works when I click the button **Next**  on the first page (Homepage), and then I click the button **Previous** back to the first page, but I still can click the **Previous** button one more click. 

### Steps To Reproduce:

I try to debug the value of  `$paginator->onFirstPage()`. The first visit homepage returns `true`, and I click on the **Next** button. It returns `false`, and then I click **Previous** to go back to Homepage, it returns `false`, and I click **Previous** again, it returns `true.`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
