### ISSUE TITLE
Queue job implementing ShouldQueue and ShouldBeUnique dispatched via dispatch()->afterResponse() acquires lock and never releases

### ISSUE THREAD

**Issue by spiechu** [laravel/framework#46537]
- Laravel Version: 9.39.0
- PHP Version: 8.1.8
- Database Driver & Version: MariaDB

### Description:
Queue job implementing `ShouldQueue` and `ShouldBeUnique` and dispatched via `Job::dispatch()->afterResponse()`
acquires lock using `UniqueLock` in `PendingDispatch::shouldDispatch()`.
Then job is run using `app(Dispatcher::class)->dispatchAfterResponse($this->job)`.
After job is done there is nothing that runs something similar to `CallQueuedHandler::ensureUniqueJobLockIsReleased()`.

### Steps To Reproduce:
1. Create queue job implementing `ShouldQueue, ShouldBeUnique`
2. Implement `uniqueId()`
3. Dispatch via `Job::dispatch()->afterResponse()`
4. Dispatch again via `Job::dispatch()->afterResponse()` and it will not work since lock is still acquired.

**Comment by cosmastech** [comment]
Assuming the PR I put up doesn't get merged, I believe you can resolve this by adding:
```php
Bus\Dispatcher::map([YourJob::class => YourUniqueJobHandler::class]);
```

To your `AppServiceProvider@boot()` method. The `UniqueJobHandler` class should have either a `handle()` or `__invoke()` method that receives `YourJob $job` and handles running the job and deleting the lock if successful.

**Comment by driesvints** [comment]
Thanks!
