### ISSUE TITLE
Not all validation error messages go into $errors

### ISSUE THREAD

**Issue by amoschou** [laravel/framework#46544]
- Laravel Version: 10.4.1
- PHP Version: 8.1.17
- Database Driver & Version: SQLite 3.40.1

### Description:
Not all validation errors messages go into the message bag when validation fails. `bail` or `stopOnFirstFailure` do not apply.

### Steps To Reproduce:

See [https://github.com/amoschou/validation-example/compare/c05d3f0...4c2341e](https://github.com/amoschou/validation-example/compare/c05d3f0...4c2341e)

The database is prepopulated with a few words, each 4 characters long. There is a form which submits words to the app. If validation is successful, the validated array `$validated` is displayed on the screen. If validation is not successful, the form has error messages appear. Validation is designed to be successful when the submitted word already exists in the database. There are some superfluous validation checks, so there should be several error messages displayed when the form is refreshed, however this is not the case.

At the route `/words/form`:

Submit: `acts`. This word validates against all four rules. Validation succeeds, and `$validated` is displayed. Behaviour is correct.

Submit: `nope`. This word validates against three rules, but does not exist in the database. Validation fails with one message. Behaviour is correct.

Submit: `toolongword`. This word does not validate against three rules `size:4`, `max:5` or `exists:words,name`. However, only two error messages display. Behaviour is not correct.

Submit: `an`. This word does not validate against three rules `size:4`, `min:3` or `exists:words,name`. However, only two error messages display. Behaviour is not correct.

**Comment by driesvints** [comment]
This is intentional. For Exists and Unique, we skip those if previous rules have failed: 

https://github.com/laravel/framework/blob/3a1201b1c19a2edec92d4d6f7a39cffe71fd295b/src/Illuminate/Validation/Validator.php#L716

This is to prevent unnecessary database executions if we already have failures.
