### ISSUE TITLE
Relative paths for SFTP connections become absolute paths.

### ISSUE THREAD

**Issue by CmdMumm** [laravel/framework#46557]
- Laravel Version: 9.52.4
- PHP Version: 8.2.1
- Database Driver & Version: MySQL 8.0.28

### Description:
If an SFTP connection is to be established using a relative path and the root path is not set in the connection configuration, the relative path becomes an absolute path by inserting a leading "/", e.g. **'foo/bar'** becomes **'/foo/bar'**
If it is not possible to change to the resulting path, this error is not passed on upwards, i.e. the error is not noticed. No exception is thrown that gets through.

In Laravel 8.83.27 everything worked as expected, so 'foo/bar' stayed 'foo/bar'

### Steps To Reproduce:

I think the problem is in laravel/framework/src/Illuminate/Filesystem/FilesystemManger.php, method **createSftpDriver()**:
 ```
public function createSftpDriver(array $config)
    {
        $provider = SftpConnectionProvider::fromArray($config);

        $root = $config['root'] ?? '/';
     }
```

If **$config['root']** is not set, a slash is added.

I would rather expect a behaviour like in the  createFtpDriver()-method:
```
 public function createFtpDriver(array $config)
    {
        if (! isset($config['root'])) {
            $config['root'] = '';
        }
```
If **$config['root']** is not set it is set empty and the relative path is preserved.

**Comment by driesvints** [comment]
Hmm I *think* you're correct here. However, we cannot change this in Laravel v10 or v9 as it'd be a breaking change. But you could attempt a PR to master for Laravel v11. Thanks!
