### ISSUE TITLE
Method Illuminate\Contracts\Queue\Job->payload() does not unserialize event body

### ISSUE THREAD

**Issue by ChrAus** [laravel/framework#46554]
- Laravel Version: 8.83.27
- PHP Version: PHP 8.1.13
- Database Driver & Version:

### Description:

So I created an event in AppServiceProvider and tried to access the jobs properties:

```
Queue::after(function (JobProcessed $event) {
            $job = $event->job;
            $jobData = $job->payload();
            }
        });
```
As per contract in Illuminate\Contracts\Queue\Job.php the method payload() should return the decoded body of a job:

```
    /**
     * Get the decoded body of the job.
     *
     * @return array
     */
    public function payload();
```

Debugging the return value of this method gave me this:

```
array (
 'commandName' => 'App\\Jobs\\Bots\\exampleBotJob',
 'command' => 'O:27:"App\\Jobs\\Bots\\exampleBotJob":12:{s:4:"test";s:5:"HALLO";s:8:"customer";s:5:"user1";s:3:"job";N;s:10:"connection";N;s:5:"queue";N;s:15:"chainConnection";N;s:10:"chainQueue";N;s:19:"chainCatchCallbacks";N;s:5:"delay";N;s:11:"afterCommit";N;s:10:"middleware";a:0:{}s:7:"chained";a:0:{}}',
)
```

I can work around it by unserializing the return value of payload() but I think this might be a bug.

### Steps To Reproduce:

1. create an event in AppServiceProvider
2. trigger a job with a public property in tinker

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
