### ISSUE TITLE
Dropping a boolean column from the SQL Server database with a default value is triggering a constraints error

### ISSUE THREAD

**Issue by itwondersteam** [laravel/framework#46567]
- Laravel Version: 10.3.3
- PHP Version: 8.2.2
- Database Driver & Version: sqlsrv (Microsoft SQL Server 2022)

### Description:
Encountered an error when trying to drop a boolean column with default value. 

 SQLSTATE[42000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The object 'DF__AspNetUse__syste__15261146' is dependent on column 'system_admin'. (Connection: sqlsrv, SQL: DECLARE @sql NVARCHAR(MAX) = '';SELECT @sql += 'ALTER TABLE [dbo].[xxx.AspNetUsers] DROP CONSTRAINT ' + OBJECT_NAME([default_object_id]) + ';' FROM sys.columns WHERE [object_id] = OBJECT_ID('[dbo].[xxx.AspNetUsers]') AND [name] in ('system_admin') AND [default_object_id] <> 0;EXEC(@sql);alter table "xxx"."AspNetUsers" drop column "system_admin")

### Steps To Reproduce:

```
    public function up(): void
    {
        Schema::table("xxx.AspNetUsers", function (Blueprint $table) {
            $table->boolean('system_admin')->default(0);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table("xxx.AspNetUsers", function (Blueprint $table) {
            $table->dropColumn('system_admin');
        });
    }
```

Fix by first manually dropping the constraints before running `php artisan migrate:rollback`
```
 ALTER TABLE [xxx].[AspNetUsers] DROP CONSTRAINT "DF__AspNetUse__syste__15261146";
```

related to [issue](https://github.com/laravel/framework/issues/4402)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
