### ISSUE TITLE
CORS Not working

### ISSUE THREAD

**Issue by microsoftjulius** [laravel/framework#46577]
- Laravel Version: ^10.0
- PHP Version: 8.2.2
- Database Driver & Version:
Postfress Database
### Description:
ç
Problem 1
    - fruitcake/laravel-cors[v0.1, ..., v0.1.2] require illuminate/support 4.x -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.2.0, ..., v0.2.3] require illuminate/support ~4.1 -> found illuminate/support[v4.1.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.3.0, ..., v0.4.0] require illuminate/support 5.0.x -> found illuminate/support[v5.0.0, ..., v5.0.33] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.5.0 requires illuminate/support ~5.0.17|5.1.x -> found illuminate/support[v5.0.22, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.6.0 requires illuminate/support 5.0.x|5.1.x -> found illuminate/support[v5.0.0, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.7.0, ..., v0.7.2] require illuminate/support ~5.0.14|5.1.x -> found illuminate/support[v5.0.22, ..., v5.1.41] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.7.3 requires illuminate/support ~5.0.14|5.1.x|5.2.x -> found illuminate/support[v5.0.22, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.8.0 requires illuminate/support 5.1.x|5.2.x -> found illuminate/support[v5.1.1, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.8.1, ..., v0.8.2] require illuminate/support 5.1.x|5.2.x|5.3.x -> found illuminate/support[v5.1.1, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.8.3, ..., v0.9.2] require illuminate/support 5.1.x|5.2.x|5.3.x|5.4.x -> found illuminate/support[v5.1.1, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.9.3, ..., v0.10.1] require illuminate/support 5.3.x|5.4.x|5.5.x -> found illuminate/support[v5.3.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.11.0 requires illuminate/support 5.3.x|5.4.x|5.5.x|5.6.x -> found illuminate/support[v5.3.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.11.1 requires laravel/framework 5.5.x|5.6.x|5.7.x -> found laravel/framework[v5.5.0, ..., v5.7.29] but it conflicts with your root composer.json require (^10.0).
    - fruitcake/laravel-cors v0.11.2 requires illuminate/support 5.5.x|5.6.x|5.7.x -> found illuminate/support[v5.5.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v0.11.3 requires illuminate/support 5.5.x|5.6.x|5.7.x|5.8.x -> found illuminate/support[v5.5.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v0.11.4, v1.0.0] require illuminate/support ^5.5|^6 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v1.0.1, ..., v1.0.2] require php ^7.1.3 -> your php version (8.2.2) does not satisfy that requirement.
    - fruitcake/laravel-cors v1.0.3 requires illuminate/support ^5.5|^6.0|^7.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v1.0.4, ..., v1.0.6] require illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v2.0.0, ..., v2.0.1] require illuminate/support ^5.6|^6.0|^7.0|^8.0 -> found illuminate/support[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors v2.0.2 requires illuminate/support ^6|^7|^8 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - fruitcake/laravel-cors[v2.0.3, ..., v2.2.0, v3.0.0] require illuminate/support ^6|^7|^8|^9 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires fruitcake/laravel-cors * -> satisfiable by fruitcake/laravel-cors[v0.1, ..., v0.11.4, v1.0.0, ..., v1.0.6, v2.0.0, ..., v2.2.0, v3.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require fruitcake/laravel-cors:*" to figure out if any version is installable, or "composer require fruitcake/laravel-cors:^2.1" if you know which you need.

### Steps To Reproduce:

<img width="1435" alt="Screenshot 2023-03-24 at 5 00 23 PM" src="https://user-images.githubusercontent.com/32195353/227540988-9e865904-55f6-4eb0-a0ec-6af602713bce.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
