### ISSUE TITLE
Laravel Breeze API - wrong host on verify-email url

### ISSUE THREAD

**Issue by PrinceNet** [laravel/framework#46571]
- Laravel Version: 10.3.3
- PHP Version: 8.1.11
- Database Driver & Version: 10.8.3-MariaDB Homebrew

### Description:

Get fresh installation of Laravel Breeze & Next.js / API, send verify-email the host in url is not `FRONTEND_URL` as expected.

### Steps To Reproduce:

1. Install latest Laravel Breeze API with [Next.js](https://github.com/laravel/breeze-next) as a front end.
2. Create db and migrate.
3. Make sure `User` model implements `MustVerifyEmail` contract.
4. In `.env` file set `MAIL_MAILER=log`.
5. Register a new user.
6. Take a look at the verify email url inside the logs file, notice the host is the server and not the `FRONTEND_URL` as expected.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
