### ISSUE TITLE
Empty Eloquent collection => map + push => Exception

### ISSUE THREAD

**Issue by levu42** [laravel/framework#46570]
- Laravel Version: 10.4.1
- PHP Version: 8.2.4
- Database Driver & Version: SQLite & MySQL both, irrelevant here

### Description:

When I query e.g. all users, use `->map->email` to get their emails, add an email to it, I have a Collection where I can use e.g. `->contains('some@email')`. However, when the Eloquent collection originally returned is empty, this fails.

### Steps To Reproduce:

See [levu42/eq-collection-first-bug](https://github.com/levu42/eq-collection-first-bug)

```php
    User::create([
        'name' => 'Hello World',
        'email' => 'foo@bar' . now(),
        'password' => '123',
    ]);

    $emptyEloquentCollection = User::where('name', 'Doesnt exist')->get();

    $allEmails = $emptyEloquentCollection->map->email->push('global@email.com');

    dd($allEmails->contains('global@email.com'));
```

Workaround: Explicitly converting it to an `Illuminate\Support\Collection` works:

```php
    $allEmails = collect($allEmails);
```

**Comment by levu42** [comment]
Forgot to add: The error I get is `Call to a member function getKey() on string` https://flareapp.io/share/lm2RAjYm#F50

**Comment by levu42** [comment]
Looks like the problem is in https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Collection.php#L346

```php
    /**
     * Run a map over each of the items.
     *
     * @template TMapValue
     *
     * @param  callable(TModel, TKey): TMapValue  $callback
     * @return \Illuminate\Support\Collection<TKey, TMapValue>|static<TKey, TMapValue>
     */
    public function map(callable $callback)
    {
        $result = parent::map($callback);

        return $result->contains(fn ($item) => ! $item instanceof Model) ? $result->toBase() : $result;
    }
```

On an empty collection it default to returning an Eloquent collection instead of a Support Collection. Changing the default could work, but I don't have the time to do a PR in the next days:

```php
        return $result->contains(fn ($item) => $item instanceof Model) ? $result : $result->toBase();
```

**Comment by driesvints** [comment]
You can first check if your collection is empty before iterating on it.

**Comment by levu42** [comment]
@driesvints wait, what? I'm not iterating on it. It's a case where Eloquent has built-in support for something (mapping models into an attribute of theirs), but it's broken in some edge-case. Do you not consider that a bug?

**Comment by driesvints** [comment]
Ah I see, sorry. No, right now I don't consider that a bug. Converting the collection sounds find to me.

**Comment by brentkelly** [comment]
For others that run into this problem a tidier solution is to just chain `->toBase()` into your call after the map to explicitly force it back to being a standard `\Illuminate\Support\Collection` instance.

It definitely feels like a bug when you run into it, but if the collection is empty there's no real way to reliably guess if the user was using `map` to:
1. alter & return an Eloquent collection of modified models; or
2. using the models to extract out a new collection of mixed types (e.g. as used by @levu42 above)

Personally, I'd have thought the latter the most likely scenario, but everyone's got their own use case and it'd be a breaking change to modify it's behavior.

Here is a different example of the problem with the `->toBase()` fix:

```php
describe('use of Eloquent\Collection::map', function() {
    beforeEach(function() {
        User::factory()->create([
            'name' => 'foo-user',
            'email' => 'foo@foo.nz',
        ]);
    });

    it('works fine if the collection is not empty', function () {
        $emails = User::where('name', 'LIKE', 'foo%')
            ->get()
            ->map(fn ($user) => $user->email)
            ->concat(['foo@foo.nz', 'bar@bar.nz'])
            ->unique()
            ->values();

        expect($emails->all())->toEqual(['foo@foo.nz', 'bar@bar.nz']);
    });

    it('throws an exception if the collection is empty', function () {
        expect(function () {
            User::where('name', 'LIKE', 'bar%')
                ->get()
                ->map(fn ($user) => $user->email)
                ->concat(['foo@foo.nz', 'bar@bar.nz'])
                ->unique()
                ->values();
        })->toThrow(Error::class);
    });

    it('works fine if the collection is empty but we explictly convert to base', function () {
        $emails = User::where('name', 'LIKE', 'foo%')
            ->get()
            ->map(fn ($user) => $user->email)
            ->toBase()
            ->concat(['foo@foo.nz', 'bar@bar.nz'])
            ->unique()
            ->values();

        expect($emails->all())->toEqual(['foo@foo.nz', 'bar@bar.nz']);
    });
})
```
