### ISSUE TITLE
 Swift_Mime_SimpleMessage::attach(): Argument #1 ($entity) must be of type Swift_Mime_SimpleMimeEntity, string given

### ISSUE THREAD

**Issue by KyleEvangelistoRI** [laravel/framework#46583]
- Laravel Version: 8.12
- PHP Version: 8.0.17
- Database Driver & Version: MySQL V8.0.28

### Description:
When using ->attach() on an instance of a Mail Message, passing in a string as the file throws the error: "Swift_Mime_SimpleMessage::attach(): Argument #1 ($entity) must be of type Swift_Mime_SimpleMimeEntity, string given"

I followed the API here: https://laravel.com/api/8.x/Illuminate/Mail/Message.html#method_attach and saw that in the background that a new SwiftAttachment is made from the file string. https://github.com/laravel/framework/blob/1b52a876131611b1297446c24964d8727fe5aef8/src/Illuminate/Mail/Message.php#L216

### Steps To Reproduce:

Here is the code I am running to create this:
```php
\Mail::send([], [], function($message) {
      $message->to("email@email.com")
          ->from("mail@mail.com")
          ->subject("Subject")
          ->setBody($this->Template, 'text/html') //where template is an html string
          ->attach("mydocument.pdf"); //where my document is the full path to the document on the system
     });
```

For the time being I just create a new Instance of a SwiftAttachment and pass that to ->attach() and it works _fine_. I feel like I am just missing something obvious.

```php
->attach(new SwiftAttachment(file_get_contents($fileName), 'name.pdf', 'pdf'))
```

I've never submitted an issue/pr to any Laravel project before, please be gentle if I did something wrong. I don't mean to waste anyone time, but I was curious if I found something here. :)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
