### ISSUE TITLE
EventFake::assertListening and array of listeners

### ISSUE THREAD

**Issue by 1thew** [laravel/framework#46599]
- Laravel Version: 9.52.4
- PHP Version: 8.1.7
- Database Driver & Version: PostgreSQL 13

### Description:
EventFake::assertListening dont work with array? The function signature allows the use of an array

### Steps To Reproduce:

```
        \Event::assertListening(
            MarketingCampaignCreatedEvent::class,
            [MarketingCampaignCreatedListener::class],
        );
```

EventFake::assertListening dock-block:

```
     * @param  string  $expectedEvent
     * @param  string|array  $expectedListener
```

In EventFake::assertListening:
```
        foreach ($this->dispatcher->getListeners($expectedEvent) as $listenerClosure) {
            $actualListener = (new ReflectionFunction($listenerClosure))
                        ->getStaticVariables()['listener'];
            $normalizedListener = $expectedListener;  // string or array
       /** other code */

        if ($actualListener === $normalizedListener || // actualListener always is string! 
       ($actualListener instanceof Closure &&
        /** other code */
```
Will it work?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
