### ISSUE TITLE
Laravel 10 Breeze Install react - ReferenceError: localref not defined

### ISSUE THREAD

**Issue by clouudsolutions** [laravel/framework#46602]
- Laravel Version: 10
- PHP Version: 8.0
- Database Driver & Version:

### Description:
Laravel 10 installation with breeze react is having issue accesing few components, when I tried to install breeze react in laravel10 framework, then 
Welcome page works properly, 
but TextInput component in login page has issue which states error in console.log i.e., RefernceError: localref not defined. 
it can be found in resources>js>components>TextInput.jsx

import { forwardRef, useEffect, useRef } from 'react';

export default forwardRef(function TextInput({ type = 'text', className = '', isFocused = false, ...props }, ref) {
    const input = ref ? ref : useRef();

    useEffect(() => {
        if (isFocused) {
            input.current.focus();
        }
    }, []);

    return (
        <div className="flex flex-col items-start">
            <input
                {...props}
                type={type}
                className={
                    'border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm ' +
                    className
                }
                ref={localref}
            />  
        </div>
    );
});

### Steps To Reproduce:
Currently it works fine with laravel 9 , 

OR you can use typescript upgrade (experimental) in Laravel 10

I trust Laravel Team will fix it ASAP in next update

**Comment by andremralves** [comment]
It was already fixed in #https://github.com/laravel/breeze/pull/277, probably the changes will take effect in the next release of breeze.

If you change`ref={localref}` to `ref{index}` it will work fine.

**Comment by driesvints** [comment]
Thanks. We'll do a new release tomorrow 👍
