### ISSUE TITLE
CommandStarted and CommandFinished no longer testable in PhpUnit

### ISSUE THREAD

**Issue by henzeb** [laravel/framework#46629]
- Laravel Version: 10.4.1
- PHP Version: 8.2.4
- Database Driver & Version: -

### Description:
I traced it back to [this pull request](https://github.com/laravel/framework/pull/46508) which was about memory leaks, but now it does no longer dispatch the Events when running from phpunit. 

That is because of the if statement around it.
https://github.com/laravel/framework/blob/485f22333e8c1dff5bae0fe0421c1e2e139713de/src/Illuminate/Foundation/Console/Kernel.php#L121-L123

This was possible in earlier versions of Laravel, so this is definitely a breaking change.

### Steps To Reproduce:

the following test will succeed in earlier versions of laravel:
```php
public function testFailingCommandEvents()
{
      $actual = false;
      
      Event::listen(CommandStarting::class, function () use (&$actual) {
          $actual = true;
      });

      Artisan::command(
          'myApplication',
          function () {
          }
      );

      Artisan::call('myApplication');

      $this->assertTrue($actual);
}
```

**Comment by crynobone** [comment]
Add the following command if you want to test command events:

```php
$this->app[\Illuminate\Contracts\Console\Kernel::class]->rerouteSymfonyCommandEvents();
```

**Comment by crynobone** [comment]
### Current

![image](https://user-images.githubusercontent.com/172966/228751632-9b8b7fa6-2da1-4754-b415-27cebd8ff928.png)

### If we revert the changes

![image](https://user-images.githubusercontent.com/172966/228751669-93caf4dc-0200-424e-a58b-9a5ca5237708.png)

--------

If we want to revert it then both #46508 and #46442 should be reverted.

**Comment by henzeb** [comment]
so you say, that if we JUST remove the if($app->runningUnitTests()) statement, we have a memoryleak?

**Comment by crynobone** [comment]
yes

**Comment by henzeb** [comment]
Weird. will it be mentioned in the docs? because it took me all day to figure out it was laravel and not my changes in my project.
