### ISSUE TITLE
API Resource Collection gives incomplete JSON output 

### ISSUE THREAD

**Issue by eng-mr-gohari** [laravel/framework#46623]
- Laravel Version: 8.12
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7.33

### Description: 
Hi guys, I add project with Laravel 8 in our new team, But in our project when we use Laravel API Resource everything is good but when we want to use Laravel collection I have an error. My Query return everything but when I send to Resource Collection JSON output don't close JSON file, after last field don't add " and ]} etc. now I don't know how to fix it.

### Steps To Reproduce: First Step I load all User with this code
`
$users = User::all();`
`return BaseCollection::collection($users);`

and In our Resource 
`class ProfileResource extends JsonResource`
`{`
    `/**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */`
`    public function toArray($request)`
`    {`
`        return [`
`            'avatar' => $this->avatar,`
`            'full_name' => $this->name,`
`            'sex' => $this->sex,`
`            'mobile' => $this->mobile,`
`        ];`
`    }`
`}`

But In result 
{"data":[{"avatar":7,"full_name":"Mr. Gohari","sex":"men","mobile":"09371801145"},{"avatar":5,"full_name":"Ms. Jaberi","sex":"women","mobile":"09371801145

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
