### ISSUE TITLE
 SQLSTATE[21000] error when trying to run php artisan migrate

### ISSUE THREAD

**Issue by adilupu7** [laravel/framework#46625]
- Laravel Version: 9.52.4
- PHP Version: 8.1.14
- Database Driver & Version: SQL Server 2016 / php_pdo_sqlsrv_81 / ODBC Driver 18

### Description:

No matter what migration I try to run , I always get this error.

    INFO  Running migrations.

    2018_08_08_100000_create_telescope_entries_table ....................................................................................... 15ms FAIL

    Illuminate\Database\QueryException

     SQLSTATE[21000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL 
    Server]Subquery returned more than 1 value. This is not permitted when 
    the subquery follows =, !=, <, <= , >, >= or when the subquery is used 
    as an expression. (SQL: create table "ZZtelescope_entries" ("sequence" 
    bigint identity primary key not null, "uuid" uniqueidentifier not null, 
    "batch_id" uniqueidentifier not null, "family_hash" nvarchar(255) null, 
    "should_display_on_index" bit not null default '1', "type" nvarchar(20) 
    not null, "content" nvarchar(max) not null, "created_at" datetime null))

    at C:\inetpub\wwwroot\webapp\webapp-beta\vendor\laravel\framework\src\Illuminate\Database\Connection.php:760
    756▕         // If an exception occurs when attempting to run a query, we'll format the error
    757▕         // message to include the bindings with SQL, which will make this exception a
    758▕         // lot more helpful to the developer instead of just the database's errors.
    759▕         catch (Exception $e) {
    ➜ 760▕             throw new QueryException(
    761▕                 $query, $this->prepareBindings($bindings), $e
    762▕             );
    763▕         }
    764▕     }

    1   C:\inetpub\wwwroot\webapp\webapp-beta\vendor\laravel\framework\src\Illuminate\Database\Connection.php:545
    PDOException::("SQLSTATE[21000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Subquery returned more than 1 
    value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.")

    2   C:\inetpub\wwwroot\webapp\webapp-beta\vendor\laravel\framework\src\Illuminate\Database\Connection.php:545
     PDOStatement::execute()

### Steps To Reproduce:

- Run the php artisan migrate in cmd on a Laravel application using a SQL Server database
- Creating the table manually via SQL Management Studio works with no issues

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
