### ISSUE TITLE
Call to a member function get() on array

### ISSUE THREAD

**Issue by axelrindle** [laravel/framework#46631]
## The Problem

I'm building a package and just stumbled upon a broken package discovery.

The package has a `ServiceProvider` and should merge configuration:

```php
$this->mergeConfigFrom($this->base_path('config/frontend.php'), 'frontend');
```

When trying to run `composer install` or e.g. `php artisan optimize:clear` the said error rises:

```
$ php artisan optimize:clear 

In ServiceProvider.php line 138:
                                            
  Call to a member function get() on array
```

## The (possible) solution

I changed the following lines

https://github.com/laravel/framework/blob/485f22333e8c1dff5bae0fe0421c1e2e139713de/src/Illuminate/Support/ServiceProvider.php#L137-L139

to these

```php
$orig = $config->get($key, []);
$config->set($key, array_merge(
    require $path, $orig
));
```

which fixed the error.

Unfortunately I'm unable to explain **why** this fixes the error.

### Versions

- Php: 8.1
- Laravel: 10.4.1

### Configuration File

```php
<?php

use Illuminate\Support\Str;

$config = array_filter($_ENV, function($key) {
    return Str::startsWith($key, 'FRONTEND_');
}, ARRAY_FILTER_USE_KEY);

return [
    'title' => env('FRONTEND_TITLE', env('APP_NAME')),
    'description' => env('FRONTEND_DESCRIPTION'),
    'company' => env('FRONTEND_COMPANY'),
    'email' => env('FRONTEND_CONTACT_EMAIL'),

    'config' => $config,
];
```

**Comment by riyuk** [comment]
it's because of your `$config` variable in your configuration. since the config gets required it throws that error would be my guess. have you tried renaming your variable `$config`?

**Comment by axelrindle** [comment]
@riyuk Makes sense as the variable names are clashing. I'll try that!

**Comment by GempitaRizki** [comment]
can anyone help ? same issue

**Comment by axelrindle** [comment]
@GempitaRizki I just renamed the variable in the configuration file:

```php
$configFrontend = array_filter($_ENV, function($key) {
    return Str::startsWith($key, 'FRONTEND_');
}, ARRAY_FILTER_USE_KEY);
```
