### ISSUE TITLE
Filtering Queries Via Intermediate Table Columns on withCount()

### ISSUE THREAD

**Issue by ronssij** [laravel/framework#46633]
- Laravel Version: 9.52.0
- PHP Version: 8.1.14
- Database Driver & Version: MySQL 8.0.31

### Description:
You cannot apply the `$query->wherePivotNotNull('link')` on the `withCount()` function.
And `wherePivotNotNull` is treated as a column `pivot_not_null` like on a `where` clause magic.

### Steps To Reproduce:
SocilaMedia Model
```
public function users()
    {
        return $this->belongsToMany(User::class)
            ->using(SocialMediaUser::class)
            ->as('social_user_link')
            ->withPivot('link')
            ->withTimestamps();
    }
```

```
$links = SocialMedia::query()
            ->with([
                'users' => fn ($query) => $query->wherePivotNotNull('link'),
                'icon'
            ])
            ->withCount([
                'users' => fn ($query) => $query->wherePivotNotNull('link')
            ])
            ->ordered()
            ->get();

return SocialMediaLinkResource::collection($links);
```

The error
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pivot_not_null' in 'where clause' (SQL: select `social_media`.*, (select count(*) from `users` inner join `social_media_user` on `users`.`id` = `social_media_user`.`user_id` where `social_media`.`id` = `social_media_user`.`social_media_id` and `pivot_not_null` = link and `blocked_at` is null) as `users_count` from `social_media` order by `order` asc)",
    "exception": "Illuminate\\Database\\QueryException
```

The generated query
```
SELECT
	`social_media`.*,
	(
		SELECT
			count(*)
		FROM
			`users`
			INNER JOIN `social_media_user` ON `users`.`id` = `social_media_user`.`user_id`
		WHERE
			`social_media`.`id` = `social_media_user`.`social_media_id`
			AND `pivot_not_null` = link
			AND `blocked_at` IS NULL) AS `users_count`
	FROM
		`social_media`
	ORDER BY
		`order` ASC
```

But when you add the where clause to the relation function it works.

```
public function users()
    {
        return $this->belongsToMany(User::class)
            ->using(SocialMediaUser::class)
            ->as('social_user_link')
            ->withPivot('link')
            ->wherePivotNotNull('link')
            ->withTimestamps();
    }
```

**Comment by ronssij** [comment]
@driesvints Yup I already posted it on discord someone commented to post it here.

**Comment by driesvints** [comment]
Thanks @ronssij. I'll leave this open then so someone can maybe help you out.

**Comment by cosmastech** [comment]
This is the expected behavior 🤷 https://github.com/laravel/docs/blob/10.x/eloquent-relationships.md?plain=1#L1449

**Comment by nunomaduro** [comment]
@ronssij, I noticed that you have submitted a pull request, and I want to express my gratitude for your contribution. Although Taylor initially rejected the request, if you believe that your code effectively addresses a bug in the framework, please "@" mention him in a follow-up comment with a more detailed explanation so that GitHub will notify him. You could also suggest that your bug fix be included in Laravel 11.x.

**Comment by ronssij** [comment]
@nunomaduro Sorry I just reported the issue, it wasn't me who created a pull request twas @cosmastech. Thanks @cosmastech thanks for the and for your PR, I have read @taylorotwell 's reply on you PR and will try it but like I said
moving it (`->wherePivotNotNull('link')`) on the model relationship solves the issue instead puting it on the callback.


```
public function users()
{
        return $this->belongsToMany(User::class)
            ->using(SocialMediaUser::class)
            ->as('social_user_link')
            ->withPivot('link')
            ->wherePivotNotNull('link')
            ->withTimestamps();
}
```
