### ISSUE TITLE
Middleware redirecting to home.

### ISSUE THREAD

**Issue by malf88** [laravel/framework#46632]
- Laravel Version: 10.4.1
- PHP Version: 8.1
- Database Driver & Version: PostgreSQL 10

### Description:
I created a services provider and in the boot method I put the following code
```
Route::prefix($this->prefix)
            ->middleware('auth')
            ->group(app_path($this->module_path. '/Routes/route.php'));
```

When I try to access the routes found in the route file defined in the above file, I am redirected to /home.
The same does not happen when I remove the auth middleware declaration or if I define the route in laravel's default route file. I also got success when I set the routes file in the RouteServiceProvider.
It looks like the redirection only happens when it's defined in another service provider.

### Steps To Reproduce:
1 - Add the code below in a new Service Provider.
```
Route::prefix($this->prefix)
            ->middleware('auth')
            ->group(app_path($this->module_path. '/Routes/route.php'));
```
2 - Register the service provider in the app.php file.
3 - Create the routes in the file defined in the service provider in step 1.
4 - Check that it does not redirect to /home.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
