### ISSUE TITLE
Controller Route Groups bug

### ISSUE THREAD

**Issue by projct1** [laravel/framework#46641]
- Laravel Version: 10.5.1
- PHP Version: 8.1.5

### Description:
I have simple route binding in `web.php`:
```php
Route::controller(CalendarController::class)->middleware('year.validate')->group(function() {
    Route::get('calendar-{month}-{year}', 'month')->where('month', '[a-z]{3,9}')->name('month');
});
```
Simple controller:
```php
class CalendarController extends Controller
{
    public function month(Request $request): MonthResponse
    {
        return new MonthResponse($request->route('year'), $request->route('month'));
    }
}
```
Light middleware:
```php
class YearValidate
{
    public function handle(Request $request, Closure $next)
    {
        $year = $request->route('year');

        return $next($request);
    }
}

```
And easiest classes of responses:
```php
abstract class AbstractResponse implements Responsable
{
    protected int $year;

    public function __construct(int $year)
    {
        $this->year = $year;
    }
}

class MonthResponse extends AbstractResponse
{
    protected string $month;

    public function __construct(int $year, string $month)
    {
        $this->month = $month;

        parent::__construct($year);
    }
}
```
When i open url `/calendar-may-2023` i got error 404.
And in my `YearValidate` i got full url string in `$resuest->route('year')`, not year only...
`dd($request->route()->parameters)` returns this:
```php
array:1 [▼ // app\Http\Middleware\YearValidate.php:13
  "year" => "calendar-may-2023"
]
```

I tried clear all cache, but error do not go out :(

**Comment by realpvz** [comment]
Can you try this ? 

`Route::controller(CalendarController::class)->middleware('year.validate')->group(function() {
    Route::get('calendar-{month}-{year}', 'month')->where([
        'month' => '[a-z]{3,9}',
        'year' => '[0-9]{4}'
    ])->name('month');
});`


add year parameter to where clause |

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by projct1** [comment]
> Can you try this ?

Same :(

**Comment by projct1** [comment]
> Hi there,
> 
> Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

Hello. Why close :( ?
Probably, its framework bug `Route::controller` (relatively new feature) and users not see this issue in fresh opened list of issues.

Declaring from just `Route:get` working fine:
```php
Route::get('calendar-{month}-{year}',  [CalendarController::class, 'month'])
    ->middleware('year.validate')
    ->where('month', '[a-z]{3,9}')
    ->name('month');
```

**Comment by projct1** [comment]
In route group not working:
```php
Route::group(['middleware' => 'year.validate'], function() {
    Route::get('calendar-{month}-{year}', [CalendarController::class, 'month'])
        ->where('month', '[a-z]{3,9}')
        ->name('month');
});
```
Outside route group working:
```php
Route::get('calendar-{month}-{year}', [CalendarController::class, 'month'])
    ->where('month', '[a-z]{3,9}')
    ->name('month');
```

**Comment by projct1** [comment]
```php
//web.php
Route::controller(CalendarController::class)->middleware('year.validate')->group(function() {
    Route::get('some-url/{year?}', 'year')->name('year');
});

//app\Http\Middleware
class YearValidate
{
    public function handle(Request $request, Closure $next)
    {
        dd($request->route('year')); //got `some-url`, not null (as expected)
    }
}
```
If i visit url /some-url, i got `some-url` as {year} parameter.
