### ISSUE TITLE
Automatic registering of commands outside of /app folder

### ISSUE THREAD

**Issue by boryn** [laravel/framework#46656]
- Laravel Version: ^8|^9|^10
- PHP Version: ^7.4|^8

### Description:
Documenation at https://laravel.com/docs/10.x/artisan#registering-commands says: 
"_You are even free to make additional calls to the load method to scan other directories for Artisan commands_"

Though automatic registering commands at `Kernel.php` with `->load()` does not work for commands located outside of `/app` folder.

### Steps To Reproduce:
Let's put additional commands location at `commands()` method:

```php
protected function commands()
{
    $this->load(__DIR__ . '/Commands');
    
    // Neither of these locations would be scanned
    $this->load(__DIR__.'/../../modules/Integrations/Console/Commands');
    $this->load(base_path().'/modules/Integrations/Console/Commands');
}
```
Unfortunately commands at this additional location won't be recognized and upon running a command we'll get:
`There are no commands defined in the "integration:sync" namespace. Did you mean one of these?`

I can see that `load()` method has a "hardcoded" `realpath(app_path())`. It would be great if the restriction of placing commands only in the `/app` folder was lifted and automatic command recognition would work from other locations.

**Comment by driesvints** [comment]
Heya that's correct. This is limited to the app directory. If you want additional directories to be scanned you can maybe attempt a PR?

**Comment by johnturingan** [comment]
@boryn were you able workaround this? I did mine by registering the command directly like
```
use CustomNamespace\Outside\AppFolder\ExportFiles;

protected function commands() {
	$this->load(__DIR__ . '/Commands');
        $this->getArtisan()->resolve(ExportFiles::class);
}
```

**Comment by JeffreyHosler** [comment]
> @boryn were you able workaround this? I did mine by registering the command directly like
> 
> ```
> use CustomNamespace\Outside\AppFolder\ExportFiles;
> 
> protected function commands() {
> 	$this->load(__DIR__ . '/Commands');
>         $this->getArtisan()->resolve(ExportFiles::class);
> }
> ```

The problem with this is you are still manually reregistering the command, instead of auto registering it. And you can also just put this in the the command in `$commands` in `Kernel.php`
```
    protected $commands = [
        ExportFiles::class
    ];
```

What I did was this and it seems to work. I put this in my `Kernel.php`
```
/**
 * Register the commands for the application.
 *
 * @return void
 */
protected function commands()
{
    // we need to load our command from outside the default structure
    $this->loadCommands(
        __DIR__ . "/Commands",
    );

    require base_path('routes/console.php');
}

private function loadCommands(string $path): void {
    $class = new \ReflectionClass($this);
    $namespace = $class->getNamespaceName();

    // go through each file so we can load the command
    foreach ((new Finder)->in($path)->files() as $file) {
        // remove .php, remove the path so we only keep the namespace
        $command = $namespace.str_replace(
            ['/', '.php'],
            ['\\', ''],
            Str::after($file->getRealPath(), realpath(__DIR__))
        );

        // and load the commands
        Application::starting(function ($artisan) use ($command) {
            $artisan->resolve($command);
        });
    }
}
```

**Comment by boryn** [comment]
Hi @JeffreyHosler!

I agree, solution with overwriting the load() method would be the best (and finally publishing it as merge request at Laravel framework). It would be good to keep possibility of passing paths both as string or as an array.

But, unfortunately your solution did not want to work out of the box in my case.
For the regular folder (`__DIR__ . '/Commands'`) I get:
`Target [App\Console\Commands\ScheduleList] is not instantiable.`

For a non standard folder like `$this->loadCommands(__DIR__.'/../../modules/Integrations/Console/Commands');` it gets completely mixed up with the namespaces, while testing on Windows I get:

`Target class [App\ConsoleE:\www\project\modules\Integrations\Console\Commands\MyCustomCommand] does not exist.`
