### ISSUE TITLE
No access to the original attribute value upon a failed transaction

### ISSUE THREAD

**Issue by boryn** [laravel/framework#46655]
- Laravel Version: 10
- PHP Version: 8.1

### Description:
No access to the original value of model attribute if transaction has failed. 
In other words, when transaction failes, the original value is unnecessarily reset.

### Steps To Reproduce:
Let's have a look at this flow and let's assume `$integration->error_count` has now value of `5`, read from the database:
```php
$integration = Integration::find(1);
```

Now, we'll modify the value of `$integration->error_count` to `0` and will fail the transaction:
```php
DB::beforeTransaction();
$integration->error_count = 0;
$integration->save();
DB::rollBack();
```

At this moment, `error_count` value in the database has not been updated and is still `5` (as the transaction failed), and the model's `$integration->error_count` is set to `0` (which is all right, it was set in the object, though not saved). 

On the other hand, `$integration->getRawOriginal('error_count')` returns `0` as well, though IMHO it should not have been reset and still should return `5`, as the `save()` was unsuccessful.

**Comment by marcovo** [comment]
I think this can be a tough issue to fix. I have implemented custom logic for things like this before, but there are edge cases you need to consider.
One problem is, you mention desired behaviour after `rollBack()`, but if you implement such a feature for general rollbacks, you most likely also want to implement such a feature when passing a rollback level `rollBack($toLevel)` for things to stay consistent. But then, you should track changes on each model on each transaction level. This can get pretty messy.
One approach could be to only consider the ultimate `commit()` and full `rollBack()`, but also then there are subtleties to consider: e.g. only model changes of models on the rollbacked connection should be reverted.

The primary use case I was interested in back then, was having a consistent model state when passing an `$attempts > 1` to `DB::transaction()`.

**Comment by nunomaduro** [comment]
There is several factors to consider when improving something like this. Therefore, if you're willing to invest time in addressing this issue and submitting a pull request and proper testing, you're more than welcome to do so. However, for now, we view this as a limitation of Eloquent / DB transactions.
