### ISSUE TITLE
Event `assertListeners` fails with dynamically registered invokable listeners

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#46652]
- Laravel Version: 9.52.4
- PHP Version: 8.1.x
- Database Driver & Version: Postgres 14

### Description:
Hello!

I have turned on auto event/listener discovery and the actual code works fine. However, the tests fail when using `assertListeners` with dynamically registered invokable listeners, it appears they are expected to only have the `handle` method whereas both the `handle` and `__invoke` methods are supported by the autodiscovery.

E.g., 
```php
    Event::assertListening(
        StationAssistanceRequested::class,
        CreateDemandWorkOrder::class, // has __invoke() method
    );
```

**Comment by cosmastech** [comment]
@driesvints should this be marked as closed?

**Comment by driesvints** [comment]
Yup, thanks!
