### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by pneves001** [laravel/framework#46669]
- Laravel Version: ALL

### Description:

Defining Authorization Routes
The section describing defining authorization routes is incomplete.  First when it mentions the Broadcast::routes($attributes) function it fails to state the format or fields or description of the $attributes object.  It doesn't give us a full description on how to define the routes other than to give a variable which is called prefix.  However, this appears to be insufficient to actually create an authorization route in the BroadcastServiceProvider. .  There is no description about possible fields or how to setup new routes. 

Go to the Broadcast Authorization page.

**Comment by lk77** [comment]
i agree it's incomplete, what do you propose ?

**Comment by driesvints** [comment]
Welcoming prs

**Comment by pneves001** [comment]
Is there an actually a way to define an actual route and specify the routes full path instead of just a prefix which is in the docs? I need to define multiple authentication routes for my websocket server where each one has its own authentication scheme. 

I mean what I'm trying to do is resolve an issue where my private websocket is not authorizing to subscribe to a private broadcast channel. I'm getting no error messages its just quietly failing. I figure its something to do with the authentication system. But I'm not sure. Been trying to trace through the code to see.

**Comment by lk77** [comment]
Well this has nothing to do with authentification
