### ISSUE TITLE
Schema builder to have 65,000 (or any other sensible number) as the default length of string fields

### ISSUE THREAD

**Issue by jdecode** [laravel/framework#46664]
- Laravel Version: 10.x
- PHP Version: 8.2
- Database Driver & Version: Postgres 14/15

### Description:
Update the Schema Builder's default string length to 65,000, since the 

### Steps To Reproduce:
Install default Laravel app, use Facebook messenger's browser on iOS (iphone 14 is the device that generated the error for me), but it could be any other device.
Use "request()->userAgent()" as the "name" of the token, and login.

You would get an error (Something on the lines of "Value too long for the column" - or a variant of this, depending on the choice of database)

The list of long-length user-agents is listed on [this gist](https://gist.github.com/etienne-martin/bea6b38c6999c720d91bd77010fae4f4) - this is 6 years old list. 

-----------------
This is one such example, and there could/would be more depending on different use-cases.
The solution to fix this is to set the `$defaultStringLength` variable's length as 65000 in `Illuminate/Database/Schema/Builder`.

All the existing databases supported by Laravel (as mentioned above) support this change.

--------------------
### Use-case [not necessarily an edge case]
Default "string" column type creates the column with 255 as the length - which works great (almost always).

The use case when this does "not" work is that I am saving user-agent as the "name" of the token in `personal_access_tokens` table.

I noticed/realised that Facebook messenger's user-agent is having a rather "LOOOOONG" name (Google helped to identify that there are a lot of variations of this specific user-agent).
One such name that caused me the error was following:

```Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 LightSpeed [FBAN/MessengerLiteForiOS;FBAV/400.1.0.29.86;FBBV/456486911;FBDV/iPhone14,2;FBMD/iPhone;FBSN/iOS;FBSV/16.3.1;FBSS/3;FBCR/;FBID/phone;FBLC/en-GB;FBOP/0]```

Laravel supports following databases:
 - Maria DB
 - MySQL
 - Postgres
 - SQLite
 - SQL server

All of the above default the string length to "at least 65,000: this exact number is of SQL server, mysql, pgsql, maria have 65k+, and SQLite is having a cap of a couple of billion characters (at least much higher than 65,000).

**Comment by driesvints** [comment]
We have no plans to change this sorry.
