### ISSUE TITLE
eloquent morph relation name

### ISSUE THREAD

**Issue by mderakhshi** [laravel/framework#46687]
### Laravel Version

10.6

### PHP Version

8.1

### Description

hi
i use eloquent query with relation specific name.
but eloquent return relation with column name  .

in Log model:
`
    public function authenticatableRelation(): MorphTo {
        return $this->morphTo('authenticatable');
    }
`

in code :
`Log::with('authenticatableRelation')->get();`

result dd code and select result model relations: 
`
#relations: array:2 [▼
      "authenticatableRelation" => null
      "authenticatable" => Modules\Admin\Entities\AdminModel .....
    ]
`

### Steps To Reproduce

laravel new bug-report --github="--public".

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
