### ISSUE TITLE
AliasLoader load Method isset Parameter is Value instead of Key

### ISSUE THREAD

**Issue by ddr5292** [laravel/framework#46699]
### Laravel Version

9.52.5

### PHP Version

8.1.16

### Description

The alias is: "Illuminate\Support\Facades\Mail"
The $this->aliases is:
Array(47)
App:"Illuminate\Support\Facades\App"
Arr:"Illuminate\Support\Arr"
Artisan:"Illuminate\Support\Facades\Artisan"
Auth:"Illuminate\Support\Facades\Auth"
Blade:"Illuminate\Support\Facades\Blade"
...
Mail:"Illuminate\Support\Facades\Mail"
...

The code that seems incorrect is:

if (isset($this->aliases[$alias])) {
    return class_alias($this->aliases[$alias], $alias);
}

Obviously, it will fail here. Did you want: array_search ($alias, $this->aliases)?

### Steps To Reproduce

Not sure reproducing is needed here - the code is simply incorrect - not sure why there are not more impacts. Maybe I am missing something.

**Comment by driesvints** [comment]
Heya, I'm not sure I see an actual bug in this report. If you can, please submit a PR with a failing test that demonstrates the bug. Thanks
