### ISSUE TITLE
Symfony Command Events in TestCase-Class using CreateApplication-Treat will always be rerouted

### ISSUE THREAD

**Issue by cannahan** [laravel/framework#46693]
### Laravel Version

10.5.1

### PHP Version

8.2.4

### Database Driver & Version

MariaDB 10.6.11 on Docker

### Description

In the setUp method of the Illuminate\Foundation\Testing\TestCase-Class, a new app instance is created using the CreatesApplication-Trait:

  ```
namespace Tests;
  
  use Illuminate\Contracts\Console\Kernel;
  
  trait CreatesApplication
  {
      /**
       * Creates the application.
       *
       * @return \Illuminate\Foundation\Application
       */
      public function createApplication()
      {
          $app = require __DIR__.'/../bootstrap/app.php';
  
          $app->make(Kernel::class)->bootstrap();
  
          return $app;
      }
  }
```

In #46508 the rerouteSymfonyCommandEvents() method was added to the constructor of the Illuminate\Contracts\Console\Kernel-Class. The runningUnitTests() method should prevent it from being called during unit tests:

```
if (! $this->app->runningUnitTests()) {
    $this->rerouteSymfonyCommandEvents();
}
```

But since the app instance is not yet bootstrapped when the Kernel-Class is instantiated in the CreatesApplication-Trait, the method call of runningUnitTests() will incorrectly return false.

This could be fixed by registering the call as a booted listener:

```
$this->app->booted(function () {
    if (! $this->app->runningUnitTests()) {
        $this->rerouteSymfonyCommandEvents();
    }
});
```

### Steps To Reproduce

1. Create new test which extends tests\TestCase-Class
2. Call artisan command like $this->artisan('migrate:fresh') in TestCase
3. Check if command will be rerouted

**Comment by crynobone** [comment]
Auto-loading the event on tests environment will create a memory leak, see previously closed issue.

**Comment by cannahan** [comment]
@crynobone I dont want the events to be rerouted in the testing env either, but it still happens if the app is not bootstrapped yet. Then $this->app->runningUnitTests() will always return false even if it is running in the testing env, because env is not bound when the constructor of the Kernel-Class is called. What about my solution by adding $this->app->booted()?
