### ISSUE TITLE
make a route resource of the base url ('/')

### ISSUE THREAD

**Issue by githubBram01** [laravel/framework#46690]
### Laravel Version

10.5.1

### PHP Version

8.1

### Description

The laravel resource of the base url works with the index, store and create public function,
but atleast not with the 'show' function I think its because you have to pass an ID in the url and it give a 404 error. It cant acces the function.

### Steps To Reproduce

FILE (index.blade.php): <a href="{{ route('show', $id) }}">show</a>  "url will look like this: https://yourwebsite.test/{id} this will cause 
                                                                                                         a 404 error"
FILE (web.php): Route::resource('/', navigateToAContoller::class)        "im not sure if the url accesses this route "
FILE (navigateToAContoller.php): public function show(string $id) { } "but atleast its not accessing this public function"

**Comment by drdokk** [comment]
Resource URI for show, update, edit, destroy methods is generated based on resource name so you must provide a name (see Illuminate\Routing\ResourceRegistrar)

valid:
Route::resource('example', ExampleResourceController::class);
Route::resource('prefix/example', ExampleResourceController::class);

invalid:
Route::resource('', ExampleResourceController::class);
Route::resource('/', ExampleResourceController::class);

**Comment by driesvints** [comment]
Please see the above.

**Comment by driesvints** [comment]
Thanks @drdokk

**Comment by githubBram01** [comment]
> Resource URI for show, update, edit, destroy methods is generated based on resource name so you must provide a name (see Illuminate\Routing\ResourceRegistrar)
> 
> valid: Route::resource('example', ExampleResourceController::class); Route::resource('prefix/example', ExampleResourceController::class);
> 
> invalid: Route::resource('', ExampleResourceController::class); Route::resource('/', ExampleResourceController::class);

yes I know but its works with create, store, index on the base url, so in the first time that you make a resource route of the base url you think its going to work if you use it for the functions where it works and later you see that it doesnt work with the other functions, so can't they make it that update, edit, delete and show also work on the base url?
