### ISSUE TITLE
duplication function calls in attribute

### ISSUE THREAD

**Issue by hAz5** [laravel/framework#46727]
### Laravel Version

10.6.1

### PHP Version

8.1.5

### Database Driver & Version

postgres

### Description

Every time i call any attribute in models it calls method agian

### Steps To Reproduce

imagine we have a model like this
```
class TestModel extends Model {
    //......
    //......
    //......
    public function getTitleAttribute()
    {
        $test2 = Test2Model::query()->find($this->id);

        return $test2?->title;
    }
}
```

when I use a query like below
```
 $p = Test2::query()->first();

```
and 
```
    if (isset($p['title'])) {
        $t = $p['title'];
    }

    if (isset($p->title)) {
        $t = $p->title;
    }
```

Everytime i call $t->title, getTitleAttributes() is called again, so if i call it 5 times, 5 times that getTitleAttributes() is called;

$t->title;
$t->title;
$t->title;
$t->title;
$t->title;

**Comment by driesvints** [comment]
I don't really see a bug here.

**Comment by eusonlito** [comment]
```getTitleAttribute``` is called every time you reference the `title` attribute, then you need to add some cache to your code.

```php
class TestModel extends Model
{
    protected array $cache = [];

    public function getTitleAttribute(): string
    {
        return $this->cache['title'] ??= Test2Model::query()->where('id', $this->id)->value('title') ?: '';
    }
}
```
