### ISSUE TITLE
Mutator - set not working with arrays

### ISSUE THREAD

**Issue by sobhan-m94** [laravel/framework#46738]
### Laravel Version

10.5.1

### PHP Version

8.2.4

### Description

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Test extends Model
{
    use HasFactory;

    public function setNamesAttribute($value)
    {
        $this->attributes['names'] = array_map('strtoupper', $value);
    }

    protected function families(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => array_map('strtoupper', $value),
        );
    }

    protected function country(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => strtoupper($value),
        );
    }
}

```
### Tinker 
```
$test=new App\Models\Test;
$test->names=['a','b','c']
$test->families=['d','e','f']
$test->country='us'
$test->names
$test->families
$test->country
$test->getAttributes()
```
### What is the expected result?
```
> $test->getAttributes()
= [
    "names" => [
      "A",
      "B",
      "C",
    ],
    "families" => [
      "D",
      "E",
      "F",
    ],
    "country" => "US",
  ]
```

### What do you get instead?

```
> $test->getAttributes()
= [
    "names" => [
      "A",
      "B",
      "C",
    ],
    0 => "D",
    1 => "E",
    2 => "F",
    "country" => "US",
  ]
```

### Steps To Reproduce

- Make test model
- Define Mutators
- php artisan tinker

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sobhan-m94** [comment]
@driesvints closed ? why ?!
