### ISSUE TITLE
Incorrect date format in SQL query from custom date format cast on model

### ISSUE THREAD

**Issue by vHeemstra** [laravel/framework#46737]
### Laravel Version

10.6.2

### PHP Version

8.1.10

### Database Driver & Version

MySQL 10.4.25-MariaDB (using Xampp with Apache) on Windows 11 Pro

### Description

When updating a model using a PATCH request, a custom date attribute is not being correctly transformed to the valid MySQL date value. Resulting in the error:
```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '20-10-2000' for column `users`.`date_of_birth` at row 1 (Connection: mysql, SQL: update `users` set `date_of_birth` = 20-10-2000, `users`.`updated_at` = 2023-04-10 11:38:19 where `id` = 1)
```

### Database (MySQL)
Column `date_of_birth` is type `DATE`.

### Migration
The column was created using `$table->date('date_of_birth')`

### Model
On the default User model, I added the attribute to fillable and set a custom date cast ([as described in the docs](https://laravel.com/docs/10.x/eloquent-mutators#date-casting)).
```php
protected $casts = [
    // other attributes
    'date_of_birth' => 'date:d-m-Y',
];

protected $fillable = [
    // other attributes
    'date_of_birth',
];
```
And according to the [documentation about date serialization](https://laravel.com/docs/10.x/eloquent-serialization#date-serialization), this should not change the format used for storing it in the database, only the format used in PHP array/JSON model instances.

### Steps/flow
1. When loading the page with an edit form, the attribute on the User model is in the correct `d-m-Y` format.
2. The post/patch request sends the date value in `d-m-Y` format as well.
<details>
	<summary>Route definition in `web.php`</summary>

```php
Route::patch('/users/{user}', [UsersController::class, 'update'])->name('users.update');
```

</details>

3. The values are correctly validated by the rule in `UserUpdateRequest`:

```php
public function rules(): array
{
    return [
        // other attributes' rules 
        'date_of_birth' => 'nullable|date_format:d-m-Y',
    ];
}
```

4. The controller fills the values in the model:

<details>
	<summary>`update` method on the controller</summary>

```php
public function update(UserUpdateRequest $request, User $user)
{
    $user->fill($request->validated());

    // dd($user->date_of_birth); <-- Shows it's a Carbon object with the correct value!

    $user->save();

    return response()->json([
        'status' => 'ok',
        'user' => $user,
    ]);
}
```

</details>

6. The JSON response (back to the form page) has the error:

```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '20-10-2000' for column `users`.`date_of_birth` at row 1 (Connection: mysql, SQL: update `users` set `date_of_birth` = 20-10-2000, `users`.`updated_at` = 2023-04-10 11:38:19 where `id` = 1)
```

Somehow the framework did not correctly turn the Carbon date object into a valid MySQL date representation. So either:
1. there is something wrong in the Carbon to MySQL transformation
2. or the date format defined in the model's `casts` property is wrongly being used here
3. or the documentation ([1](https://laravel.com/docs/10.x/eloquent-mutators#date-casting) and [2](https://laravel.com/docs/10.x/eloquent-serialization#date-serialization)) is incorrect.

Note: Setting the model's attribute cast to `date:Y-m-d` does not produce this error. Of course, this is also the exact format MySQL's DATE field uses. This also indicates the issue is option 2.

Note 2: Sending/posting the same value as currently in the DB/on the model, does not give an error. (I guess the attribute is skipped in the SQL here because it hasn't changed.)

### Update: created example repo
**Repo at:** https://github.com/vHeemstra/laravel-date-format-bug

**To set it up:**
- Clone repo
- Create MySQL database (collation: `utf8mb4_unicode_ci`)
- Set DB credentials in `.env`
- Run composer and NPM install commands
- Run `php artisan migrate`
- Run the website (either with own server or `php artisan serve`)
- Run Vite dev server (`npm run dev`)
- Open site and go to login
- Create/register new user and log in
- Go to "Personen" page and click on the pencil icon to edit (modal pops up)
- Change the "Geboortedatum" (translation: birthday) field to a different `d-m-Y` value
- Click "Opslaan" (Save)
- View the Console log and Network tab in Developer tools in browser

**Comment by tttogo** [comment]
Just FYI, I had a very similar thing with Datetime to Timestamp, where casting just wouldn't work.

Workaround was to write a nutator as per [https://laravel.com/docs/10.x/eloquent-mutators#defining-a-mutator](Laravel 10 Docs)

**Comment by vHeemstra** [comment]
@cosmastech I will try to create a working example.

It might be that MySQL is needed, because the Exception is thrown even before any SQL query is sent. Using:
```php
DB::enableQueryLog();
try {
  $user->save();
} catch (\Exception $e) {}
dd(DB::getQueryLog());
```
The `dd`'ed result was an empty array, so I guess the DB grammar/adopter (idk) checks all of this before sending the query and there finds the wrong format?

As stated in the report above, the date is correctly filled in the user model instance and becomes a Carbon instance with the correct date. It is just that when compiling/preparing the DB query, the Carbon object is turned into a string using the wrong format (that from `$casts` instead of the MySQL one).
Possibly because it might use `HasAttributes::attributesToArray()`? Which calls `HasAttributes::addCastAttributesToArray`, which calls the `format` method on the Carbon instance with the format from `$casts`.

@tttogo Thanks, yeah I might do that for the moment. Or switch to `Y-m-d` and have front-end rearrange the date. 😄

**Comment by vHeemstra** [comment]
> @vHeemstra could you link to a repo that shows this is failing?
> 
> I tried to write a test case and it's not failing. https://github.com/cosmastech/laravel-framework/pull/1/files Do I have some part of the setup wrong? It could be that it's using SQLite instead of MySQL 🤷 but I'll admit I feel that's not the issue.

Repo at: https://github.com/vHeemstra/laravel-date-format-bug

The `.env` is just like `.env.example` but with `DB_DATABASE` set to a new MySQL database.

**Comment by cosmastech** [comment]
The application worked fine for me.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/42181698/231312443-25c437b0-0a8d-4a70-b534-c123907356b1.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/42181698/231312466-df8b9680-d408-4b61-bb2c-7fab17b23f7a.png">

**Comment by vHeemstra** [comment]
@cosmastech First off, thank you so much for taking the time to help!

Second, how strange.. The axios request (when submitting the modal form with a different d-m-Y date) returns with status 200?

I feel OS should not make a difference here. Maybe MySQL versions and/or PHP version, in the way some of the magic getters/setters are implemented??

**Comment by vHeemstra** [comment]
I just made a new clone from the repo and installed using the steps above. After submitting the edit modal form with only the date set, I still get the described error back from the server.

**Comment by cosmastech** [comment]
@tttogo when you were running into this issue, were you using Laravel 10? What version of PHP, DB, etc?

**Comment by cosmastech** [comment]
Now I'm getting the error! I was editing my profile, not the Personen edit page.

**Comment by driesvints** [comment]
It seems Taylor has decided to not take any action here, sorry.

**Comment by vHeemstra** [comment]
But that does not address the issue in the bug report. As Taylor says, the cast format should only be used when model instances become arrays or JSON, but it should not interfere with the way it is stored in the database. (See also the referenced docs in my comment there and in the bug report above.)

So it is still a bug that needs a fix. (Or the docs need changing.)
