### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by mathewparet** [laravel/framework#46758]
### Laravel Version

10.3.1

### PHP Version

8.2

### Description

Cache not respecting TTL.

The project was initially done in Laravel 9 and later upgraded to 10.

I just noticed that TTL isn't respected.

I used Cache::remember and set TTL to 30 (seconds).

But the cache seems to remember for ever.

I tested it by going to `tinker` and setting `Cache::put('name','value',10);` but even after 20-25 seconds the data is still available when using `Cache::get('name')`. 

Note: I am able to clear the cache without issues, so it is definitely not a permission issue.

### Steps To Reproduce

```sh
php artisan tinker
use Illuminate\Support\Facades\Cache

Cache::put('name','value', 10);

# wait 10-15 seconds

Cache::get('name'); # still returns value
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
