### ISSUE TITLE
Queued event listener options aren't taking any affect

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/framework#46756]
### Laravel Version

10.6.2

### PHP Version

8.1.17

### Database Driver & Version

10.5.16-MariaDB - MariaDB Server

### Description

I'm escalating this to the bugs section in Laravel after exhausting Google searches and debugging myself.

I have a queued event listener called `StoreUptimeHourlySummaryStat` which creates a new entry in my database or gets it and increments some columns. However, despite setting `tries`, `timeout`, `maxExceptions` and a `failed` method, none of these are taking any affect in the application.

For example, here's my listener file:

```php
<?php

namespace App\Listeners;

use App\Events\UptimeHourlySummaryStatCreation;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Log;
use App\Models\UptimeHourlySummaryStat;
use Carbon\Carbon;
use Throwable;

class StoreUptimeHourlySummaryStat implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * The name of the connection the job should be sent to.
     *
     * @var string|null
     */
    public $connection = 'database-short-running';

    /**
     * The name of the queue the job should be sent to.
     *
     * @var string|null
     */
    public $queue = 'statistics-hourly';

    /**
     * The number of times the queued listener may be attempted.
     *
     * @var int
     */
    public $tries = 1;

    /**
     * The number of seconds the job can run before timing out.
     *
     * @var int
     */
    public $timeout = 50;

    /**
     * The maximum number of unhandled exceptions to allow before failing.
     *
     * @var int
     */
    public $maxExceptions = 1;

    /**
     * Create the event listener.
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     */
    public function handle(UptimeHourlySummaryStatCreation $event): void
    {
        try {
            $statistic = UptimeHourlySummaryStat::firstOrCreate([
                'user_id' => $event->userId,
                'monitor_id' => $event->monitorId,
                'grouped_at' => Carbon::parse($event->lastCheckedAt)->format('Y-m-d H:00:00')
            ]);

            // set count of each check
            $statistic->total_checks_performed = $statistic->total_checks_performed + $event->totalChecksPerformed;
            $statistic->total_successful_checks_performed = $statistic->total_successful_checks_performed + $event->totalSuccessfulChecksPerformed;
            $statistic->total_failed_checks_performed = $statistic->total_failed_checks_performed + $event->totalFailedChecksPerformed;

            // set the response durations
            $statistic->total_response_duration = $statistic->total_response_duration + $event->totalResponseDuration;

            if (!$statistic->total_checks_performed) {
                $statistic->avg_response_duration = 0;
            } else {
                $statistic->avg_response_duration = round($statistic->total_response_duration / $statistic->total_checks_performed);
            }

            // set checked date and save
            $statistic->last_checked_at = Carbon::parse($event->lastCheckedAt);
            $statistic->save();
        } catch (\Exception $e) {
            Log::channel('statistics_hourly')->info('hourly:stat save error');

            if (config('app.debug')) {
                Log::debug('store_uptime_hourly_summary_stat', [
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                ]);
            }
        }
    }

    /**
     * Handle a job failure.
     */
    public function failed(UptimeHourlySummaryStatCreation $event, Throwable $exception): void
    {
        Log::channel('statistics_hourly')->info('hourly:stat failed error');
        Log::channel('statistics_hourly')->info(json_encode($exception->getMessage()));
    }
}
```

I'm getting lots of failed jobs in my `failed_jobs` table with the same error:

> [2023-04-12 19:01:42] production.INFO: "App\\Listeners\\StoreUptimeHourlySummaryStat has been attempted too many times or run too long. The job may have previously timed out."

I thought, firstly, that having the `failed` method would prevent them ending up in the `failed_jobs` table? But they are.

In addition, setting the number of `tries` has no affect, so much so that my jobs are being attempted up to 4 times weirdly.

What am I missing here? my system is working, yet, none of the listener options are being observed - I just need them not to end up in failed jobs.

If it helps at all, here's my queue connections:

```
// for short running queues
'database-short-running' => [
    'driver' => 'database',
    'table' => 'jobs',
    'queue' => 'short-running',
    'retry_after' => 80,
    'after_commit' => false,
],

'database' => [
    'driver' => 'database',
    'table' => 'jobs',
    'queue' => 'default',
    'retry_after' => 90,
    'after_commit' => false,
],

// for long running queues
'database-long-running' => [
    'driver' => 'database',
    'table' => 'jobs',
    'queue' => 'long-running',
    'retry_after' => 300,
    'after_commit' => false,
],
```

### Steps To Reproduce

1. Create an event
2. Create a listener
3. Set `tries`, `maxExceptions` and `failed` method
4. Run the queue

None of the options are being set

**Comment by cosmastech** [comment]
It looks like you're catching the exception that would normally trigger a failure, no?

**Comment by ankurk91** [comment]
I would suggest to use a job instead.
Listeners does have all of queue job features.

**Comment by sts-ryan-holton** [comment]
@cosmastech Yeah I have the failed method, and the handle method, but the try/catch isn't catching any errors at all, and instead, the failed method is outputting logs.

But it shouldn't end up as a failed job in the database and I shouldn't be seeing my attempts exceed my tries which I am?

**Comment by sts-ryan-holton** [comment]
@ankurk91 I would've thought my set up should be working just fine since they're using the queue anyway? I think something might be wrong in the Laravel code somewhere

**Comment by driesvints** [comment]
Please share links where you've posted this.

**Comment by sts-ryan-holton** [comment]
@driesvints 

- https://github.com/laravel/framework/discussions/46718
- https://stackoverflow.com/questions/75964741/laravel-options-on-event-listener-arent-being-used _(attempted suggestion)_

**Comment by cosmastech** [comment]
Can you put up a github repository that shows this behavior? It doesn't need to be your project code, but if you can make a repo so that this issue is easy to reproduce, that makes it much easier to diagnose and implement a solution.

**Comment by joelharkes** [comment]
This exception comes up when your job runs for too long. Even if your job succeeds in the end. If it goes over timeout it will be added to the failed jobs table

**Comment by sts-ryan-holton** [comment]
@joelharkes I don't know how I'd reproduce this locally at all though. On my production server I have Supervisor configured with 50 workers - that's quite a lot of workers. My jobs never build up so processing capacity is stable. When I seed my database locally with thousands of the `UptimeHourlySummaryStat` model and then start my queue as normal, each one processes instantly, or within a few seconds, so for it to randomly exceed my job's `tries` and `timeout` in production doesn't make any sense to me, they're not being used by the queued event listener - whereas my other jobs have these options set and they do indeed work.

My queued event listener is dispatched from a job in my system called `UptimeChecker`.

**Comment by sts-ryan-holton** [comment]
@cosmastech I'm not sure how I would approach creating a reproduction here.. I'd need to re-create quite a lot.

Above is my Event, with how I'm dispatching it, and the listener further above.

**Comment by cosmastech** [comment]
> @cosmastech I'm not sure how I would approach creating a reproduction here.. I'd need to re-create quite a lot.
> 
> Above is my Event, with how I'm dispatching it, and the listener further above.

I'm not asking for your production code (in fact, it's probably much easier if it's not your production code).

But if there is a minimal Github repo that anyone can clone, install, and see the error, then it's a lot easier to triage this.

The minimal repo need only prove your thesis that there is a problem with the queued event listeners. My thinking is that it would contain an event which is handled by a queued listener, sets similar properties and has a `failed()` method. Running a queue worker shows that it ends up in the failed table.

If you can't provide that or you don't see the error in a fresh install, have you tried step debugging the event listener? You can run a queue:work command with step debugging like:
```zsh
php -dxdebug.mode=debug -dxdebug.client_host=localhost -dxdebug.client_port=9003 -dxdebug.start_with_request=yes artisan queue:work
```

Have you tried changing from from `catch (\Exception $e)` to `catch (\Throwable $e)` instead? (all Exceptions implement Throwable, but there also things like `DivisionByZeroError` which implemented Throwable but are not child classes of \Exception)

**Comment by sts-ryan-holton** [comment]
Changing my catch to `Throwable` makes no difference for me. 

Is there a problem here having 3 different queue connections all pointing to the same jobs table? 

Despite me setting:

```php
public $connection = 'database-short-running';
```

I see that these queues are marked in the connection column of the failed_jobs table as "database" isntead of "database-short-running"?

Moreover, I've just upped the number of processes in my single supervisor config:

```
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/domain-monitor-api/artisan queue:work --queue=on-demand-runs-now,cron,uptime,notifications,statistics-hourly,domains,dns,certificates,domains-expired,subscriptions,blacklists,listeners,statistics-daily,short-running,long-running,default --tries=2 --max-time=900
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=60
redirect_stderr=true
stderr_logfile=/var/www/domain-monitor-api/storage/logs/worker-error.log
stdout_logfile=/var/www/domain-monitor-api/storage/logs/worker.log
stopwaitsecs=1800
```

I'm getting loads of:

> [2023-04-16 15:04:05] production.ERROR: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: select * from `jobs` where `queue` = statistics-hourly and ((`reserved_at` is null and `available_at` <= 1681653845) or (`reserved_at` <= 1681653755)) order by `id` asc limit 1 for update) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (Connection: mysql, SQL: select * from `jobs` where `queue` = statistics-hourly and ((`reserved_at` is null and `available_at` <= 1681653845) or (`reserved_at` <= 1681653755)) order by `id` asc limit 1 for update) at /var/www/domain-monitor-api/vendor/laravel/framework/src/Illuminate/Database/Connection.php:793)

**Comment by cosmastech** [comment]
Databases aren't advised for a lot of job processing. Having three queue connections sharing one `jobs` table should be avoided, and it's going to make it a lot harder to triage the issue you're having.

I can't reproduce this locally with a fresh Laravel install. I would advise switching to a Redis queue and see if the problem persists.

Maybe someone else has a better idea.

**Comment by sts-ryan-holton** [comment]
I'm using the event/listener approach because I thought it was advised to not dispatch a Job from within a Job explicitly? Or is this fine?

**Comment by cosmastech** [comment]
Obviously I don't have full context of your application, but if you're saying that the event is dispatched from a job and is handled by a queued event listener, then you're already dispatching a job from within a job, essentially.

**Comment by nunomaduro** [comment]
Although this issue was created a while ago, I'm still eager to assist you, @sts-ryan-holton, if you're still experiencing difficulties. If that's the case, would you mind creating a **minimal** GitHub repository with a Laravel application that I can use to replicate your problem on my end?

Rest assured, if we determine that there is indeed a bug in the framework, I'll gladly re-open this issue.

**Comment by sts-ryan-holton** [comment]
Yeah still facing the same problem. Sentry is giving me errors on queued event listeners. "Operation in progress", I feel that the closed PR should be re-opened and merged?
