### ISSUE TITLE
Batched Job Chain using Batch-Queue instead of Job-Queue for first job

### ISSUE THREAD

**Issue by tinyoverflow** [laravel/framework#46771]
### Laravel Version

10.5.1

### PHP Version

8.2.4

### Description

When creating a batch with a job chain, the configured queue on the first job inside the chain is ignored and assigned to the queue of the batch instead. All following jobs in the chain are put into their configured queue. This is unexpected for me. I expect the dispatcher to use the queue configured on the job if set, not the batch.

This might be related to #34296, just inverted. If I understand Taylors reply to that issue correctly, my expected behaviour isn't something the Batch should fulfill. Though, it seems like it kinda works.

Is this part related?
https://github.com/laravel/framework/blob/81c61bdd234150667aaea2028914564317fed32f/src/Illuminate/Bus/Batch.php#L171-L176

### Steps To Reproduce

1. Create two jobs, eg `FirstJob` and `SecondJob`.
2. Assign them to a queue using `$this->onQueue('first')` and `$this->onQueue('second')` in their constructor.
3. Batch them as a chain:
```php
$batch = Bus::batch([]);
$batch->add([
    [
        new FirstJob(),
        new SecondJob(),
    ],
]);
$batch->dispatch();
```

The `FirstJob` will be assigned to the default queue (as no queue is set on the batch), which is unexpected. The `SecondJob` will be assigned to the `second` queue as set inside the jobs constructor.

**Comment by driesvints** [comment]
I think the idea here is that you just don't set different queues for jobs within batches. As Taylor said on the other issue, that just won't work. You're trying to do something that is unfortunately not supported.

**Comment by tinyoverflow** [comment]
@driesvints I think I get your point. But I think that there are absolutely valid reasons to do something like this, and this is a practical example of my current situation:

Imagine 3 servers for simplicity: one webserver, one server with a ton of storage and one server with a GPU.

1. The webserver serves the website. Kinda self-explanatory.
2. The storage server should download and store files.
3. The server with the GPU should process video files.

Of course, a video can only be processed after it has been downloaded, therefore the jobs are dispatched as a chain. To make the storage server only download files and the GPU server to only process videos, different queue names can be used. Does that make any sense?

My proposal would be:
1. If jobs are batched/chained, use the jobs queue name if no queue name has been given to the batch/chain.
2. If a queue name has been given to the batch/chain, override _all_ queues on the jobs.

I don't know yet how easy and compatible this approach would be, as I'd have to dig into the Laravel Bus. But would a PR for this be reviewed?
