### ISSUE TITLE
Found a Validation Bug on Laravel Breeze scaffold.

### ISSUE THREAD

**Issue by inckmo** [laravel/framework#46789]
### Laravel Version

10.7.1

### PHP Version

8.2.3

### Database Driver & Version

MySQL 8.0.30

### Found a Bug on Laravel Breeze with Inertia and Vuejs scaffold.

- The ProfileControllerUpdate Request Rules array not validate valid email address.

- Store invalid  email address in DB and user can login with that invalid email address.

### Steps To Reproduce

>
_**Below are some Images Provide for better understanding**_
>
&nbsp;
1. **After Register with demo@demo.com and in profile look like this.**

![ProfileBefore](https://user-images.githubusercontent.com/19841184/232206095-0b23f725-b603-44ee-9120-781bb9bfeacd.png)

>
&nbsp;
**In the MySql DB**

![DB-Before](https://user-images.githubusercontent.com/19841184/232206542-ff87c4f8-9d2d-4a66-93ec-cbc5f279b794.png)

&nbsp;
&nbsp;
2.  **After Email update with invalid  not any tld as ext. it save with no validation**

![Profile-After](https://user-images.githubusercontent.com/19841184/232206333-cd03fd96-23d8-4fbe-b415-13ccbacd001a.png)

>
&nbsp;
**After Save in MYsql DB**

![DB-after](https://user-images.githubusercontent.com/19841184/232206684-714c41b1-d8b4-4430-944a-60bb692bdd9f.png)

**Comment by Jubeki** [comment]
This has already been reported: https://github.com/egulias/EmailValidator/issues/359

**Comment by driesvints** [comment]
Thanks @Jubeki
