### ISSUE TITLE
in validator attributes , mimes: and mimetypes not working for text/* 

### ISSUE THREAD

**Issue by kozhinhikkodan** [laravel/framework#46783]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

in validator , mimes and mimetypes to working for csv, css and othet text/* types

### Steps To Reproduce

make a validator where mime type checking ( mimes or mimetypes ), mimes:csv or mimetypes:csv
check for the validation error , even though correct file checked against , error will be thrown

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
