### ISSUE TITLE
Bulk Insert is very slow when the data contains values with a question mark

### ISSUE THREAD

**Issue by novoselovmaks** [laravel/framework#46781]
### Laravel Version

9.52.5

### PHP Version

8.1.7

### Database Driver & Version

10.6.8-MariaDB-1:10.6.8+maria~stretch

### Description

Hello

Insert is very slow when I want to save values with a question mark.

When processing for a long time, I immediately see my data in the DB table, but insert is still not finished.

but if I escape the question mark with two slashes, then the insertion works quickly. But the data is saved with a single slash.

Tell me how to get around this problem?

### Steps To Reproduce

      for ($i=0;$i<=1000;$i++)
        {
            $data[] = [
                'host' => 'site.ru',
                'url' => "https://site.ru/page/?query=$i",
                'created_at' => \DB::raw('now()'),
                'updated_at' => \DB::raw('now()'),
            ];
        }

        Model::insert($data);

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
