### ISSUE TITLE
Wrong exception thrown while setting method return

### ISSUE THREAD

**Issue by peroxovy** [laravel/framework#46793]
### Laravel Version

10.7.1

### PHP Version

8.2

### Description

While trying to override Controller return type to `View` wrongly, site return wrong hint.

Inside Controller I've used by mistake a:

`use Illuminate\Support\Facades\View;`

instead of: 

`use Illuminate\Contracts\View\View;`

Then inside `index` method I've wanted to override the return type (by default it's blank) to:

```
public function index(UserService $userService) : View
{
    return view('user.index')->with('users', $userService->getAllUsers());
}
```

Inside View I've achieved Error message:

> App\Http\Controllers\UserController::show(): Return value must be of type Illuminate\Support\Facades\View, Illuminate\View\View returned

![image](https://user-images.githubusercontent.com/62743726/232244728-814e6de9-1a15-4226-9c53-fca0abb8aacb.png)

### Steps To Reproduce

Inside Controller instead of `use Illuminate\Contracts\View\View;` use `use Illuminate\Support\Facades\View;` then try to set type of method return to View and try to use browser.

**Comment by driesvints** [comment]
I'm not sure what you mean. You've required the return type to be a view facade and you're not returning that so this error message seems correct.

**Comment by peroxovy** [comment]
> I'm not sure what you mean. You've required the return type to be a view facade and you're not returning that so this error message seems correct.

I thought that in this case where is 

>[...] Illuminate\View\View returned

part with `[...]\Contracts\View[...]` is missing.

If I'm wrong, please close.
