### ISSUE TITLE
setting query parameters with url() only works with routes

### ISSUE THREAD

**Issue by VitorTS** [laravel/framework#46818]
### Laravel Version

10.3.3

### PHP Version

8.2.4

### Description

setting url parameters on a url without routes is currently impossible. The method accepts them without complain, but doesn't return them.

### Steps To Reproduce

`
dd(url('https://www.google.com', ['some_query_parameter' => 'true']));
`
will return
`https://www.google.com`

**Comment by driesvints** [comment]
Looks like a feature request. Feel free to open up a discussion or attempt a PR. Thanks
