### ISSUE TITLE
Route::domain is ignored if method does not exist

### ISSUE THREAD

**Issue by megaezz** [laravel/framework#46823]
### Laravel Version

9.52.5 

### PHP Version

8.2.4

### Description

If create a route for a domain with a method that does not yet exist, the domain is ignored.

### Steps To Reproduce

Let's create some route for domain with non-existent method:

`Route::domain('test.com')->any('/test', ['TestController', 'not_exist']);`

Then check `php artisan route:list`:
`ANY       test .................................................................... TestController@not_exist`

No domain in route. But if we change method to existing:

`Route::domain('test.com')->any('/test', ['TestController', 'exist']);`

`ANY       test.com/test ........................................................... TestController@exist`

Domain is here.

**Comment by driesvints** [comment]
Not sure we can qualify this as a bug in the framework.
