### ISSUE TITLE
loadCount() incorrect for qualified columns in query constraint

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#46825]
### Laravel Version

10.7.2

### PHP Version

8.2.4

### Database Driver & Version

MySQL 8.0.32

### Description

Calling a collection's `loadCount()` method with an additional query constraint works fine when using plain column names:

```php
// $models is a collection.
$models->loadCount(['children' => function($query) {
    $query->where('active', 1);
}]);
```

compiles to

```sql
SELECT id,
(
    SELECT COUNT(*)
    FROM models AS laravel_reserved_0
    WHERE
          models.id = laravel_reserved_0.parent_id
          AND active = 1  // <-- implicitly scoped to the subquery, so affecting the countable rows
) as children_count
FROM models
WHERE models.id IN (...)
```

But when qualifying the query constraint because of a complex constraint with joins having equally named columns, the count fails because the compiled subquery consequently refers to the main query instead:

```php
// $models is a collection.
$models->loadCount(['children' => function($query) {
    $query->where('models.active', 1);
}]);
```

```sql
SELECT id,
(
    SELECT COUNT(*)
    FROM models AS laravel_reserved_0
    WHERE
          models.id = laravel_reserved_0.parent_id
          AND models.active = 1 // <-- explicitly scoped to the main query, so affecting the parent rows instead of the countable rows
) as children_count
FROM models
WHERE models.id IN (...)
```

### Steps To Reproduce

see above

**Comment by cosmastech** [comment]
Is this on a Builder instance or Eloquent Collection?

If it's a Collection, would something like this work?

```php
$models->loadCount(['children' => function($query) {
    $query->where('active', 1)->whereIn('id', $models->whereActive(1)->pluck('id'))
}]);
```

**Comment by Propaganistas** [comment]
It's on collections; thanks - I've added that to the OP.
The example is greatly simplified so I don't think additional where clauses would be beneficial.
But even this simplified example returns unexpected results.

**Comment by Propaganistas** [comment]
I found a working solution but I'm wondering if this is still unexpected framework behavior?


`qualifyColumn()` apparently takes the right (aliased) table when needed.

```php
$models->loadCount(['children' => function($query) {
    $query->where($query->qualifyColumn('active'), 1);
}]);
```

**Comment by driesvints** [comment]
Using `qualifyColumn` here is the correct solution 👍
