### ISSUE TITLE
Routing: look-up tables built before updating group route name

### ISSUE THREAD

**Issue by adil-azmy** [laravel/framework#46834]
### Laravel Version

10.0

### PHP Version

8.0.27

### Database Driver & Version

n/a

### Description

Router could not resolve a route('groupName.subrouteName') declared for a package.

The problem is that its name is not listed on the generated Illuminate\Routing\RouteCollection#nameList when trying to resolve it.

Note:
Even if its not there when resolving, the route is correctly listed under artisan route:list with its correct name.

### Steps To Reproduce

- load route file via a package service provider $this->loadRoutesFrom($path);
- Add a route group with a name as ('group.'), and add a sub route also with a name ('route')
- calling route('group.route') trigger a not found route exception

When checking the route collection, it seems that it have been built taking only the group name in consideration, what erased all the sub routes from figuring inside Illuminate\Routing\RouteCollection#nameList

A step by step debug showed that RouteCollection->addLookups($route) have been called before the subroute Route->name($name).

**[Hints found]**

Seems that the collection need to be refreshed after adding a route:

```
// vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php line 45
public function add(Route $route)
{
  $this->addToCollections($route);
  $this->addLookups($route);
  
  // Adding this line solved the problem
  $this->refreshNameLookups();
  
  return $route;
}
```

or maybe elsewhere inside :

`protected function addToCollections($route)`

A second hint is that Route::name() should be always first, before Route::get(). If this is the case, the documentation should be updated.

**Comment by driesvints** [comment]
> Seems that the collection need to be refreshed after adding a route:

We'd appreciate a PR for this with a test that verifies the issue is fixed.

> A second hint is that Route::name() should be always first, before Route::get(). If this is the case, the documentation should be updated.

`Route::get()` should always come first.

**Comment by nunomaduro** [comment]
I couldn't replicate the problem on my local machine. As you explained, I've created the following files:

```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->loadRoutesFrom(base_path('routes/nuno.php'));
    }
```

My routes file (nuno.php):
```
<?php

Route::name('admin.')->group(function () {
    Route::get('/users', function () {
        //
    })->name('users');
});
```

My view: 
```
<a href="{{ route('admin.users') }}">Users</a>
```

A link to `/admin/users` was successfully generated. Although it is working on my end, I'm still eager to help you. Could you create an open source repository with a new Laravel application and a minimal example of the problem you're experiencing? If I can reproduce the issue on my end, I will reopen this issue, and we can proceed from there.
