### ISSUE TITLE
WithWhereHas error with Builder indication

### ISSUE THREAD

**Issue by Jul000** [laravel/framework#46835]
### Laravel Version

10.4.1

### PHP Version

8.1.1

### Database Driver & Version

MySQL 8.0.28 winx64

### Description

Hello,
it seems to have a minor bug when using withWhereHas as the documentation said :
```
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
 
$users = User::withWhereHas('posts', function (Builder $query) {
    $query->where('featured', true);
})->get();
```

It gives the error "Argument #1 ($query) must be of type Illuminate\Database\Eloquent\Builder, Illuminate\Database\Eloquent\Relations\HasMany given"

This works without Builder indication with only $query :
```
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
 
$users = User::withWhereHas('posts', function ($query) {
    $query->where('featured', true);
})->get();
```

Thanks

### Steps To Reproduce

Just try a withWhereHas method with and without Builder indication to see the error

**Comment by driesvints** [comment]
We'd appreciate a PR to th docs to fix the typehint, thanks.
