### ISSUE TITLE
ORA-01841 : (full) year must be between -4713 and +9999 and not be 0 while storing in Laravel

### ISSUE THREAD

**Issue by manelbenmiled** [laravel/framework#46837]
### Laravel Version

9.11

### PHP Version

8.0.2

### Database Driver & Version

Oracle

### Description

i'm using laravel 9 and currently i occured an error while storing data. it shows 500 server error and in log file it shows :

> Error Message : ORA-01841: (full) year must be between -4713 and +9999, and not be 0
> 
> Position : 248
> 
> Statement : insert into "DEMANDE_CLIENTS" ("NATURE_PLACEMENT", "MONTANT_DEMANDE", "DEVISE", "DU", "AU", "PERIODE_DEMANDE", "POURCENTAGE_DEMANDE", "TYPE_PLACEMENT", "TAUX", "ID_PLACEMENT", "UPDATED_AT", "CREATED_AT") values (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11) returning "ID" into :p12
> 
> Bindings : [Bon de Caisse Précompté 21004,55000.000,TND,2023-04-20 00:00:00,2023-04-23 00:00:00,,variable,TMM+,2,334,2023-04-20 07:22:00,2023-04-20 07:22:00,0]
> 
> at C:\xampp\htdocs\worflow\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8\Statement.php:753) [stacktrace]

my controller : 
`DemandeClient::create($request->only('nature_placement' , 'montant_demande' , 'devise' , 'du' , 'au' , 'periode_demande' , 'pourcentage_demande' , 'type_placement' , 'tauxValue') + ['id_placement' => $placement->id]);`

### Steps To Reproduce

i created a store function in this way : 

`DemandeClient::create($request->only('nature_placement' , 'montant_demande' , 'devise' , 'du' , 'au' , 'periode_demande' , 'pourcentage_demande' , 'type_placement' , 'tauxValue') + ['id_placement' => $placement->id]);`

and while submitting it shows 500 SERVER ERROR

**Comment by driesvints** [comment]
Unfortunately we don't support Oracle as a valid database storage, sorry.
