### ISSUE TITLE
Cannot override artisan command from within package

### ISSUE THREAD

**Issue by MichelJonkman** [laravel/framework#46843]
### Laravel Version

10.8.0

### PHP Version

8.1

### Database Driver & Version

MariaDB 10.6

### Description

When trying to override an artisan command from within a package the constructor get's called but the original command still runs.

### Steps To Reproduce

In this case I tried overriding the migrate command using this code:
```php
class MigrateCommand extends \Illuminate\Database\Console\Migrations\MigrateCommand
{
    public function __construct(Migrator $migrator, Dispatcher $dispatcher)
    {
        echo 'Is called';

        parent::__construct($migrator, $dispatcher);
    }


    public function handle()
    {
        echo 'Is not called';

        return parent::handle();
    }

}
```
```php
    public function register(): void
    {
        $this->app->scoped(Migrator::class, function(Application $app) {
            return $app->make('migrator');
        });
    }

    public function boot(): void
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                MigrateCommand::class
            ]);
        }
    }
```
Output:
![image](https://user-images.githubusercontent.com/24224847/233573179-d0415aa0-4002-42cf-8b70-0474fce28b6b.png)

**Comment by driesvints** [comment]
Unfortunately we do not support overriding artisan commands, sorry. It's best that you create a new command that does what you wish.

**Comment by MichelJonkman** [comment]
Why is this not supported? As far as I know this feature is supported if done in the project itself.
