### ISSUE TITLE
[Bug/Feature] Validating files in nested arrays.

### ISSUE THREAD

**Issue by pxpm** [laravel/framework#46849]
### Laravel Version

10.2

### PHP Version

8.2

### Description

Hey guys! 👋 

I am having troubles using the `File` validation rule in nested arrays.

It fails with the following error when using the `File` validation rule in a nested array:
![image](https://user-images.githubusercontent.com/7188159/233690408-bdecfd37-04ba-4de3-bbe4-9c48f5cc64d5.png)

I've set this bug/feature because I am not sure if the behavior is intended or it was forgotten to add a `toString()` method on `File` rule. 

Cheers

### Steps To Reproduce

```php
// this works
array.*.input => ['file', 'max:1024']

//this don't
array.*.input => [File::types(['pdf'])->max(1024)]
```

**Comment by driesvints** [comment]
Thanks. Let's see how your PR goes.
