### ISSUE TITLE
[Database] Many-to-Many: detach() method builds incomplete pivot object

### ISSUE THREAD

**Issue by shehi** [laravel/framework#46851]
### Laravel Version

10.8.0

### PHP Version

8.1.17

### Database Driver & Version

MariaDb 10.6

### Description

When detaching, e.g.:
```
$ids = [...];
$user->posts()->detach($ids);
```
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L478 is triggered, which builds a Pivot object only with pivot-key attributes (e.g. `user_id` and `post_id`). The remaining pivot attributes don't get included. This becomes a problem especially when this deleted pivot object is passed to some `deleted` event. Deleted object not having all its attributes causes issues where those attributes are needed. And that object being already deleted, unfortunately can't be `refresh()`ed.

At https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L513 we can see it potentially could build full pivot object if `$this->pivotValues` were populated. But the latter is empty.

![image](https://user-images.githubusercontent.com/653569/233748212-b2f1fde5-1377-4983-ac30-4ea42f75ddda.png)

### Steps To Reproduce

Description should be enough.

**Comment by cosmastech** [comment]
Looks like the expected behavior is to hydrate the pivot models and delete them yourself. 🤷

**Comment by cosmastech** [comment]
@driesvints can this be closed? The PR to resolve it was rejected, so I'm guessing this is expected behavior.

**Comment by driesvints** [comment]
Thanks. It indeed seems we're not going to make any changes here right now, sorry.
