### ISSUE TITLE
dynamodb cache driver increment method is incorrect

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#46858]
### Laravel Version

10.8.0

### PHP Version

8.2.5

### Database Driver & Version

N/A

### Description

The correct behaviour of an atomic increment function is to:
1. if the value exists and is not expired, increment it by 1
2. otherwise, set it to 1

The currently implementation fails to do (2). The decrement method has the same issue.

---

https://github.com/laravel/framework/blob/v10.8.0/src/Illuminate/Cache/DynamoDbStore.php#L303-L346

### Steps To Reproduce

Call increment over and over, and eventually it stops working (returns false instead of incrementing). This is a problem in practice, not just in theory, since dynamodb TTL does not clean up items quickly, often taking hours on large tables, with their docs indicating a worst case of 48 hours.

**Comment by Shkeats** [comment]
@GrahamCampbell I had a play around with this for quite a while, it's definitely a tricky corner of overlapping issues. I couldn't find a way to do this within one dynamo request, however the below works by catching the exception and calling forever() if the key is expired. This does a put which overwrites the expired record. Given we can't duplicate the key I think this is the right outcome but obviously two requests isn't ideal.

```
    /**
     * Increment the value of an item in the cache.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return int|bool
     */
    public function increment($key, $value = 1)
    {
        try {
            $response = $this->dynamo->updateItem([
                'TableName' => $this->table,
                'Key' => [
                    $this->keyAttribute => [
                        'S' => $this->prefix.$key,
                    ],
                ],
                'ConditionExpression' => '#expires_at > :now',
                'UpdateExpression' => 'SET #value = if_not_exists(#value, :initial) + :amount',
                'ExpressionAttributeNames' => [
                    '#value' => $this->valueAttribute,
                    '#expires_at' => $this->expirationAttribute,
                ],
                'ExpressionAttributeValues' => [
                    ':amount' => [
                        'N' => (string) $value,
                    ],
                    ':initial' => [
                        'N' => 0,
                    ],
                    ':now' => [
                        'N' => (string) Carbon::now()->getTimestamp(),
                    ],
                ],
                'ReturnValues' => 'UPDATED_NEW',
            ]);

            return (int) $response['Attributes'][$this->valueAttribute]['N'];
        } catch (DynamoDbException $e) {
            if (str_contains($e->getMessage(), 'ConditionalCheckFailed')) {
                $this->forever($key, $value);
                return $value;
            }

            throw $e;
        }
    }
```

Can PR this if you think it's viable. I used the test harness in [my package](https://github.com/blackfrog-co/laravel-event-sourcing-dynamodb) to test this which is what I've done locally so I can put a fork up there if you want to see it working.

**Comment by GrahamCampbell** [comment]
This can be done with a single query for sure. The conditional expression you have there is incorrect though, as it will crash if there's no record. I will provide a fix when I get some time. I have some private code that does something similar to this, which is why I noticed this was wrong.

**Comment by Shkeats** [comment]
@GrahamCampbell t wasn't blowing up, but I had  I'd left out the attribute_exists(#key) bit in ConditionExpression by mistake, the exception catch was causing my test to pass as it was putting the record anyway in the scenario you describe. But it works and is more efficient with it in place so I'll update the example to put it back.

**Comment by nunomaduro** [comment]
Hi @GrahamCampbell, thank you for creating this issue! 

The way atomic increments behave when the value does not exist depends on the implementation and context. There are no strict guidelines or rules established in regards to that matter. In this scenario, it is the responsibility of the programmer to verify that the value exists prior to attempting to increment it.

Moreover, our documentation already indicates that the increment and decrement methods are suitable for **adjust integer items** within the cache. Note that, we are specifically referring to **integer items** in this context. As a result, I wouldn't classify this as a bug; rather, it is a feature request to enhance the reliability of "DynamoDB@increment" by setting the initial increment to 1 in the event that the value does not exist.

**Comment by taylorotwell** [comment]
I think we would likely fix this @nunomaduro. The cache drivers are inconsistent right now. I noticed the `file` and `redis` and `memcached` drivers work correctly, but `database` and `dynamodb` seem to have this issue that @GrahamCampbell is describing.

**Comment by taylorotwell** [comment]
Nevermind - some things are coming back to my memory now. It's best practice to initialize the value with an expiration using `Cache::add` first. Then increment or decrement. 

If you just use `increment` or `decrement` we really have no way to know how long you want the item to last in the cache because those methods don't accept expirations.

**Comment by taylorotwell** [comment]
Updating documentation to cover this.

**Comment by GrahamCampbell** [comment]
Don't we use increment right away for rate limiting, without first initializing?
