### ISSUE TITLE
Model::Upsert throws exception when UUID or ULID is used as a primary key

### ISSUE THREAD

**Issue by naveedali8086** [laravel/framework#46856]
### Laravel Version

9.38.0

### PHP Version

8.0.27

### Database Driver & Version

mysql-8.0.30-winx64

### Description

The laravel framework throws exception when upsert() method of model is used

```
uminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: 
insert into `schools` (`code`, `created_at`, `name`, `updated_at`)  values
 (one 1, 2023-04-23, one, 2023-04-23), 
(two 2, 2023-04-23, two, 2023-04-23), 
(three 3, 2023-04-23, thee, 2023-04-23), 
(four, 2023-04-23, f, 2023-04-23) 
on duplicate key update `code` = values(`code`), `updated_at` = values(`updated_at`))'
```

the "id" column  of school model is of type UUID and primary key column is set this column already.

Here is the School Model class:

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    use HasFactory, HasUuids;

	 protected $fillable = ['name', 'code'];

     public $incrementing = false;

     protected $keyType = 'string';

    protected $dateFormat = 'Y-m-d';

    public function uniqueIds(): array
    {
        return ['id'];
    }
}
`

### Steps To Reproduce

1. Create  model
2. Make necessary changes  in model that Laravel suggest when id is not the primary key and auto-increment
3. Use upsert() method from tinker/controller/command (i was using command and tinker)

**Comment by Rizky92** [comment]
You need to explicitly define UUIDs/ULIDs when using insert/upsert since they're not created automatically.

**Comment by driesvints** [comment]
Please see the above answer. Thanks @Rizky92
