### ISSUE TITLE
Fallback HTTP error pages (4xx.blade.php and 5xx.blade.php) do not work for certain important error codes.

### ISSUE THREAD

**Issue by WEBPerformace** [laravel/framework#46865]
### Laravel Version

10.4.1

### PHP Version

8.2.4

### Description

I tested it and:

- `4xx.blade.php` does not work for `404` (while working for other `4xx` codes).
- `5xx.blade.php` does not work for `500` and `503` (while working for other `5xx` codes).

This forces us to create duplicate files with the exact error codes in the name, i.e. `404.blade.php`, `500.blade.php`, and `503.blade.php`.

### Steps To Reproduce

1. Add custom `4xx.blade.php` and `5xx.blade.php` files to your `resources/views/errors` directory
2. Test them with different error codes (using `abort($code)`).
3. These templates will not work for `404`, `500`, and `503` errors, but they will work for other `4xx` and `5xx` codes.

**Comment by driesvints** [comment]
This is because Laravel ships with dedicated pages for these. You'll always have to overwrite these yourself.

**Comment by weshooper** [comment]
This seems to contradict the documentation @ https://laravel.com/docs/11.x/errors#fallback-http-error-pages ?
