### ISSUE TITLE
Support inline style and script with Vite

### ISSUE THREAD

**Issue by jimblue** [laravel/framework#46861]
### Laravel Version

9.52.6

### PHP Version

8.2.5

### Database Driver & Version

None (using Statamic filesystem driver)

### Description

Hi,

Is it possible to load a `critical.css` file inline with Vite to get the following output ?

```css
<style>the critical.css file content here...</style>
```

I'm maybe wrong, by it does not seems actually possible...

It could be driven by a new `inline` parameter that would permit generation of `<style>` and `<script>` tags only when not in hot reload.

### Steps To Reproduce

The `@vite` does not have any option to generate inline style or script.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jimblue** [comment]
Sure make sens, sorry for the noise.
