### ISSUE TITLE
Brackets after blade directives are gobbled

### ISSUE THREAD

**Issue by amoschou** [laravel/framework#46879]
### Laravel Version

10.7.1

### PHP Version

8.2.2

### Description

If an opening `(` appears after @else or @endif, then the pair of brackets and its contents are gobbled. Unlike @if and some other blade directives, *else* and *endif* should not take arguments.

I noticed this as I am attempting to render something similar to the following:

```
<th>Variant</th>
<td>@if (! is_null($variant)) {{ $variant }} @else (<em>No variant</em>) @endif</td>
```

If `$variant` is `null`, then I would expect **(_No variant_)** to be printed to the screen. Actually, nothing gets printed to the screen.

### Steps To Reproduce

Render the following Blade:

```
<h1>False paragraph</h1>

<p>
    @if (false) (True paragraph)
    @else (False paragraph)
    @endif (Final content)
</p>

<h1>True paragraph</h1>

<p>
    @if (true) (True paragraph)
    @else (False paragraph)
    @endif (Final content)
</p>

<h1>Another false paragraph</h1>

<p>
    @if (false) (True paragraph)
    @else <span></span>(False paragraph)
    @endif <span></span>(Final content)
</p>
```

**Comment by driesvints** [comment]
This syntax unfortunately isn't supported sorry.

**Comment by amoschou** [comment]
Perhaps then documentation should explain that we need to write `@else()`, and not just `@else` in some circumstances.
