### ISSUE TITLE
@json tag with specific PHP expression as its parameter breaks the generated view

### ISSUE THREAD

**Issue by craigpipeandpiper** [laravel/framework#46880]
### Laravel Version

9.50.2

### PHP Version

8.1.11

### Database Driver & Version

MySQL 8.0.32

### Description

When using the `@json()` function in a blade file with specific php expressions within that use a combination of `DB::query()->selectRaw()`, `CONCAT` and single quoted strings, the generation of the view breaks, ending the content of the 
generated PHP script in the middle of the double quoted string and causing a parse error.

In the example statement, `let b0rk = @json(DB::query()->selectRaw("1, CONCAT(2, ' ', 3) AS name")->get());`,  it seems that the `' , '` causes the error to manifest, removing the quoted space makes the error go away, as does moving the query itself into the controller where it belongs.

The error which is produced is a result of this happening to the generated PHP of the view:

```php
   let b0rk = <?php echo json_encode(DB::query()->selectRaw("1, CONCAT(2, ' ') ?>;

</script>
```

![stack trace](https://user-images.githubusercontent.com/108274351/234301548-3239296c-bbc1-472c-a80f-8f47e27346ce.png)

### Steps To Reproduce

Add a statement like the following to a blade file:

```php
let b0rk = @json(DB::query()->selectRaw("1, CONCAT(2, ' ', 3) AS name")->get());
```

This expression should allow reproduction of the bug anywhere, it does not reference any database tables.

**Comment by driesvints** [comment]
The json directive really wasn't meant to be used like this. It's best that you save the value in a variable and pass that to the json directive.

**Comment by craigpipeandpiper** [comment]
I think you missed the point, this could be anything that is not a query, such as a function call with a string in it for language translation, or anything really. To close the issue and dismiss it because the test case isn't best practice seems to be a cop-out, the bug still exists.

**Comment by that-guy-iain** [comment]
@driesvints not wanting to be rude but closing bugs to keep your issue count artificially lower doesn't seem like something that well help with keeping your issue count low since other people will almost certainly find the same bug.

The fact it requires a value to be stored in a variable either needs to be documented or fixed. Just closing the issue just leaves the software with a bug.

**Comment by driesvints** [comment]
I don't want to artificially lower anything. Like I said in my post, the `json` directive simply doesn't supports this syntax. We're welcoming PRs that could improve the docs.
