### ISSUE TITLE
Eloquent can't search by pure enum

### ISSUE THREAD

**Issue by trckster** [laravel/framework#46902]
### Laravel Version

10.8.0

### PHP Version

8.2.5

### Description

I am trying to filter models in database by pure enum, but getting an error: `Object of class App\Enums\Enum2 could not be converted to string`. I am expecting query builder to take enum name and filter by it. That's a thing, because you can pass backed enum (with value), builder will take enum value and it will work without errors. Also pure enums perfectly work with create and update queries. Problem is presented only while trying to filter by pure enums at the moment.

I propose to cast non-backed enumerations to string by taking their's names. I made some research and it seems great place to cast is `Illuminate\Database\Query::where` method. I am ready to create a PR, but first I would like to hear some opinions on my issue. Thanks.

### Steps To Reproduce

Example of models and enumerations that demonstrates the problem:
```php

// Model
class Example extends Model
{
    protected $fillable = [
        'enum1',
        'enum2',
    ];

    protected $casts = [
        'enum1' => Enum1::class,
        'enum2' => Enum2::class,
    ];
}

// Backed enum
enum Enum1: string
{
    case First = 'first';
}


// Pure enum
enum Enum2
{
    case Second;
}

// Testing
Example::create(['enum1' => Enum1::First, 'enum2' => Enum2::Second]); // Works fine
$model = Example::where('enum1', Enum1::First)->first(); // Works fine
$model = Example::where('enum2', Enum2::Second)->first(); 
// Here comes an error:
// Error  Object of class App\Enums\Enum2 could not be converted to string.
```

**Comment by driesvints** [comment]
Heya, this indeed isn't possible right now. You can always attempt a PR if you want, thanks.

**Comment by trckster** [comment]
Can you specify what is actually impossible, please? @driesvints

**Comment by driesvints** [comment]
You can't pass pure enums.

**Comment by trckster** [comment]
Yes, I know I can't. That's the problem I've described. What do you think, will it be good idea to add such possibility? If yes, is it a good place to put pure enum to string cast in `Illuminate\Database\Query::where`?

**Comment by trckster** [comment]
@driesvints
