### ISSUE TITLE
attributes() method not being called from abstract class

### ISSUE THREAD

**Issue by gssj85** [laravel/framework#46901]
### Laravel Version

9.52.4

### PHP Version

8.1.2

### Database Driver & Version

Firebird 3

### Description

I have an abstract class that extends FormRequests and implements most methods.

When I want a FormRequest I just create a class and extend from this abstract class which extends a FormRequest.

The method attributes() should be called but it isn't, I have it only in the abstract class.

Is there anything I'm doing wrong?

```
abstract class AbstractRequest extends FormRequest
{
    public function attributes()
    {
        dd('should enter here');
    }
}
```

and the class used as FormRequest:

```
class PedidoStoreRequest extends AbstractRequest
{
    public function rules()
    {
        //... rules
    }
}
```

### Steps To Reproduce

1. Create an abstract class that extends a FormRequest
2. Put the method attributes() in this class.
3. Create a class that extends the abstract class created in step 1.
4. use it like a normal FormRequest, add rules, etc
5. Note that the attributes() method in the abstract won't be called

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by teguh02** [comment]
Hello all, here i want to help this issue. I was try @gssj85 reproduce steps and finally i found this bug too. Here this is all my code

AbstractRequest.php
```php
<?php
// app/Http/Requests/Abstracts/AbstractRequest.php
namespace App\Http\Requests\Abstracts;

use Illuminate\Foundation\Http\FormRequest;

abstract class AbstractRequest extends FormRequest {
    public function attributes()
    {
        return [
            'name' => "User's Name",
            'phone' => "User's Phone Number",
        ];
    }
}
```
and the i do 2 test case here (i'am test my code using a postman)

### Case 1 (Blank Request Data)
This is my controller 

TestRequest.php
```php
<?php
// app/Http/Controllers/TestRequest.php
namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use Illuminate\Http\Request;

class TestRequest extends Controller
{
    public function catch_request(StorePostRequest $request)
    {
        $input = $request->all();
        dd($input);
    }
}
```
i put blank data request in POST or GET HTTP Method, and then same when i fill only one data request, and here in my postman response

![image](https://user-images.githubusercontent.com/43981051/235460530-eb890b34-e179-4311-b8e4-38b46125e282.png)
![image](https://user-images.githubusercontent.com/43981051/235460670-6a4302f1-4f88-4db0-99b3-eaec36c0231c.png)

and then the response are same, show a main laravel homepage
![image](https://user-images.githubusercontent.com/43981051/235460866-e90c1fb9-7705-4ca8-8134-48ced879aa3e.png)

### Case 2 (Fill All Request Data)
In second case, my controller are same with before case. But when i put all request data the form validation class are work
![image](https://user-images.githubusercontent.com/43981051/235461605-37ed649d-393f-427d-8fe2-4e6600114eda.png)

Is this a bug for all users or bug only me?

**Comment by driesvints** [comment]
Can someone provide me with a repo that reproduces this?

**Comment by gssj85** [comment]
> Can someone provide me with a repo that reproduces this?

I will just a minute, and thank you! thanks also @teguh02

**Comment by gssj85** [comment]
Well that's strange I just created a new project with laravel 8.52.7 (couldn't get 9.52.4 to work with composer create-project) and it worked as it should, it called the attributes() method from the parent abstract class.

Why it isn't working on my works project I guess we will never know...I pretty much copied the class...

**Comment by gssj85** [comment]
Here attributes() work as intended, but hes already on parent class then I comment the method on the child class expecting it to be called from the abstract class but...(see next picture).
![Screenshot from 2023-05-01 12-18-49](https://user-images.githubusercontent.com/66959217/235476190-cc31fdd8-cea4-4841-be32-384f1e29580c.png)

It's not being called from AbstractClass (which extends FormRequest), it just doesn't enter that block of code.
![Screenshot from 2023-05-01 12-15-05](https://user-images.githubusercontent.com/66959217/235476473-012e8593-8b92-4981-b0dd-419cdac15351.png)

In the controller:
![Screenshot from 2023-05-01 12-16-25](https://user-images.githubusercontent.com/66959217/235476720-a3de3260-967f-4bf9-ba2d-50c6b18e0c68.png)

**Comment by driesvints** [comment]
If we can't produce this on a fresh app then I think it's indeed probably something specific to your app. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by gssj85** [comment]
Hey guys just an update, I found out what was causing the issue.

It was the GlobalValidationRules trait which had the attributes() method.

Thanks all for the help!

/close
