### ISSUE TITLE
Attribute setter looses microseconds when using Carbon instance in set:

### ISSUE THREAD

**Issue by Braunson** [laravel/framework#46917]
### Laravel Version

9.52.6

### PHP Version

8.2.5

### Database Driver & Version

Postgres

### Description

I have a model with an attribute where I return a Carbon instance (`now()`) in the setter callback. While this does convert to a datetime string on save it looses the microseconds.

While I do have a workaround, I would think that the microseconds should be maintained through to the save as they are elsewhere i.e. when not using a custom Attribute setter.

### Steps To Reproduce

- Note: Setting `$dates` does not affect things, nor does `$casts` with this timestamp field.

1. Create a new model with two new timestamp fields `set_auto_updates_at` (precision: 3) in addition to the default timestamps (`created_at` and `updated_at`)
2. Set the custom getter/setter methods in the model
3. Run this code:
```php
$model = new YourModel();
$model->auto_updates = true;
$model->save();
```

**Broken: looses microseconds after save**
```php
public function autoUpdates(): Attribute
{
    return Attribute::make(
        get: fn () => $this->set_auto_updates_at !== null,
        set: fn (bool $autoUpdates) => ['set_auto_updates_at' => $autoUpdates ? now()) : null]
    );
}
```

**Working, keeps microseconds after save**
```php
public function autoUpdates(): Attribute
{
    return Attribute::make(
        get: fn () => $this->set_auto_updates_at !== null,
        set: fn (bool $autoUpdates) => ['set_auto_updates_at' => $autoUpdates ? now()->format($this->getDateFormat()) : null]
    );
}
```

**Comment by Angel5a** [comment]
[Docs states](https://laravel.com/docs/10.x/eloquent-mutators#date-casting-and-timezones):

> By default, the date and datetime casts will serialize dates to a UTC ISO-8601 date string (YYYY-MM-DDTHH:MM:SS.uuuuuuZ), regardless of the timezone specified in your application's timezone configuration option.

But [grammar](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Grammar.php#L230-L233) is missing this fractional part:
```
    public function getDateFormat()
    {
        return 'Y-m-d H:i:s';
    }
```

And [code in HasAttributes](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L954-L959):
```
        elseif (! is_null($value) && $this->isDateAttribute($key)) {
            $value = $this->fromDateTime($value);
        }
```
Doesn't respect [manually provided datetime format](https://laravel.com/docs/10.x/eloquent-mutators#date-casting) in cast not only for fractional part, but any of it:
```
protected $casts = [
    'created_at' => 'datetime:Y-m-d',
];
```

It looks bad.

**Comment by Rizky92** [comment]
Per [Carbon docs about laravel](https://carbon.nesbot.com/laravel/#time-precision):
> SQL engines are capable to store date-time millisecond to nanosecond precision, but by default Laravel comes with second-precision.

So if you want to use nanosecond precision, you need to extend your Database QueryGrammar and change `getDateFormat` according to your needs.

```php
<?php

class MySqlGrammar extends \Illuminate\Database\Query\Grammars\MySqlGrammar
{
    public function getDateFormat()
    {
        return 'Y-m-d H:i:s.u';
    }
}
```

**Comment by Braunson** [comment]
I'm using Postgres and this works normally just fine i.e. passing `now()` before saving.. This example code below works just fine and maintains the milliseconds. It's just on the `Attribute` setter it doesn't maintain milliseconds.

```php
$model = new Model();
$model->set_auto_updates_at = now();
$model->save();
```

**Comment by nunomaduro** [comment]
@Braunson, I have made a local test by including a migration with `$table->timestamp('set_auto_updates_at', 3);` and followed to the guidelines outlined on Carbon's website: https://carbon.nesbot.com/laravel/. In both instances, the date was stored and exhibited with a precision of "3".

```php
$user = User::factory()->create();
$user->auto_updates = true;
// or $user->set_auto_updates_at = now();
$user->save();

dd($user->fresh()->set_auto_updates_at); // 2023-05-11 18:40:23.588.
``` 

Please be aware that I used MySQL for the local testing, which is the only deviation from the conditions you described. However, the possibility of any significant impact is minimal.

In any case, would it be possible for you to create an open-source repository that includes a new Laravel application with that problem you are having? This would enable me to clone it and try to replicate the issue on my end. If successful, I will reopen this issue. Thank you.
