### ISSUE TITLE
Calling `InteractsWithDatabase@seed()`within a test breaks DB transaction

### ISSUE THREAD

**Issue by cosmastech** [laravel/framework#46933]
### Laravel Version

9.52.6

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0.31

### Description

Within a test case that employs RefreshDatabase (or LazilyRefreshDatabase), calling `InteractsWithDatabase@seed()` will write to the database outside of the open transaction. It's not just the seeded data either, but any data created AFTER the seeder will not be cleaned up.

```php
use Tests\TestCase;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;

class MyTestCase extends TestCase
{
    use LazilyRefreshDatabase;

    public function testSeedSomeData()
    {
        $this->assertDatabaseEmpty('users');
        User::create(['hello' => 'world']);
        $this->seed(SomeSeeder::class);
        $this->assertCount(1, User::get());
    }
    public function testDatabaseShouldBeEmpty()
    {
        $this->assertDatabaseEmpty('users'); // ❌ 
    }
}
```

**Note that this is also the behavior in 10.x**

### Steps To Reproduce

Description includes example.

I don't suspect this is expected behavior but maybe I'm misunderstanding how InteractsWithDatabase@seed() is supposed to work.

**Comment by cosmastech** [comment]
Looks like the root cause is that my seeder was using `Model::truncate()`.

Lesson learned: don't use truncate in your seeders that you want to want to run tests against. 🤷

**Comment by amadeann** [comment]
Thank you for reporting this, helped me fix my tests too. I had `Model::tuncate()` directly in my test (not seeders), and it was producing failures when I switched testing DB from SQLite to MySQL.
