### ISSUE TITLE
Sleep mysql connections on horizon:work redis

### ISSUE THREAD

**Issue by WZaradzki** [laravel/framework#46953]
### Laravel Version

8

### PHP Version

7.4

### Database Driver & Version

Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64)

### Description

On horizon start, it start multiple processes (depends on number of queues), like 
`artisan horizon:work redis --name=name --supervisor=foo --backoff=0 --max-time=0 --max-jobs=0 --memory=128 --queue=queueName --sleep=3 --timeout=60 --tries=1 --rest=0`

With every this process, it create mysql connection with `command` = 'sleep'. When we have for example, 2 workers and 20 queues, it will be create 40 sleep connections. 

Have you encountered this problem?

### Steps To Reproduce

- new Laravel project
- queue with horizon
- start horizon

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
