### ISSUE TITLE
Array to string conversion error when running php artisan queue:listen or queue:work

### ISSUE THREAD

**Issue by yasar-salim** [laravel/framework#46966]
### Laravel Version

8.7.5

### PHP Version

8.1.2

### Database Driver & Version

Oracle

### Description

I have created a job and when i run it is added to job table and nothing happens. When i check laravel log it shows array to string conversion error. I deleted job from table and laravel log is keep generating this error. I deleted the job class from project and the result is same

### Steps To Reproduce

create new job
php artisan queue:listen

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
