### ISSUE TITLE
Str::snake() function not handling certain string formats correctly

### ISSUE THREAD

**Issue by MrFail** [laravel/framework#47005]
### Laravel Version

10.x

### PHP Version

8.x

### Description

The `Str::snake` function in Laravel does not correctly conversion all uppercase characters to lowercase. For example, the string `LARAVEL` is converted to `l_a_r_a_v_e_l` instead of `laravel`. This is inconsistent with the expected behavior and causes issues when using the function to convert strings to snake case.

Suggestion
-------------------------------

The current implementation of `Str::snake` in Laravel converts all uppercase characters to lowercase and separates them with an underscore. However, if there are multiple consecutive uppercase characters, they are currently separated by underscores as well, which may not be desirable.

To improve the conversion, we can modify the Str::snake function to group consecutive uppercase characters together and convert them as a single group. This would result in a more readable and consistent output when converting strings from CamelCase to snake_case.

For example, the string "userID" would be converted to `user_id` instead of `user_i_d`, and the string `LARAVELFramework` would be converted to `laravel_framework` instead of `l_a_r_a_v_e_l_framework`.

### Steps To Reproduce

1. Use the `Str::snake()` function to convert a  all-caps string formatting to snake case.
2. Observe the resulting string and compare it to the expected result.

**Comment by Rizky92** [comment]
```php
str("LARAVEL IS AWESOME")
    ->lower()
    ->snake();

// laravel_is_awesome
```

**Comment by MrFail** [comment]
> `runAJob` (yes, not the best name, but for the sake of argument) will then be converted to `run_aj_ob` right?

I made a [pull request](https://github.com/laravel/framework/pull/47006), so there u can see my vision of this method.

**Comment by nunomaduro** [comment]
Implementing this change would disrupt the current functionality of Laravel 10. Nevertheless, you are free to suggest this enhancement for Laravel 11 by submitting a pull request and providing **sufficient explanation** on how this new behavior would impact existing customers.

**Comment by gihanwonderlabs** [comment]
@nunomaduro Is there any string helper function to convert `laravel_framework` to `Laravel Framework`. Thank you!
