### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by el-yonousi** [laravel/framework#47015]
### Laravel Version

10.10.0

### PHP Version

8.2.5

### Node Version
18.16.0

### Database Driver & Version

mysql

### Description

I have install laravel with Laravel-breeze using vue ssr
and when I run npm run dev command
the error display 
__dirname is not defined

### Steps To Reproduce

![img2](https://github.com/laravel/framework/assets/44925062/5668018e-05a6-43fb-b7e4-472b20c402d6)
`npm run dev`
![img1](https://github.com/laravel/framework/assets/44925062/defc4610-5ce8-4ab1-8e0d-94ac50cf189c)

**Comment by timacdonald** [comment]
See https://github.com/laravel/vite-plugin/issues/216

**Comment by timacdonald** [comment]
Please upgrade to `0.7.6`. Sorry for the troubles, folks.
