### ISSUE TITLE
laravel resource contoller stub 

### ISSUE THREAD

**Issue by mderakhshi** [laravel/framework#47016]
### Laravel Version

10.10

### PHP Version

8.1

### Description

after command:
```
 php artisan make:controller PhotoController --resource
```
in contoller code not import "Illuminate\Routing\Controller;"
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PhotoController extends Controller
```

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by oleghalin** [comment]
It shouldnt be imported here, you have Controller.php in same namespace

**Comment by nunomaduro** [comment]
As the Controller class is located in the same namespace, importing it is unnecessary. You can find the class here: https://github.com/laravel/laravel/blob/10.x/app/Http/Controllers/Controller.php.
