### ISSUE TITLE
Newly added 'hashed' cast may be incorrect.

### ISSUE THREAD

**Issue by nshiro** [laravel/framework#47028]
### Laravel Version

10.10.0

### PHP Version

8.2

### Description

Newly added `hashed` cast may have been implemented incorrectly.
https://github.com/laravel/framework/pull/46947

As I understand it, Hash::needsRehash() is supposed to take a hashed string as an argument.
https://laravel.com/docs/10.x/hashing
https://www.php.net/manual/en/function.password-needs-rehash

And an already hashed string will be double-hashed if it needs rehashing.

### Steps To Reproduce
```php
$user->password = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi';
$user->save();
```

**Comment by driesvints** [comment]
Ping @gdebrauwer

**Comment by gdebrauwer** [comment]
I created a PR to fix the issue
