### ISSUE TITLE
Problem cooperation Laravel Artisan Test with drone.io - return test "1" returning when testing has been finished

### ISSUE THREAD

**Issue by record223** [laravel/framework#47033]
### Laravel Version

10.4.1

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

After update Laravel to 10.* and try to deploy it on our VPS we have a problem with testing drone.io steps. 

During testing `php artisan test` the testing returning "1" and drone.io return by Exit Code. In older versions it always was "0" so probably drone has problem with handle it. We just wanna know it could be problem with our configuration or mayby something goes wrong after last update to newest Laravel version.

Thanks for your answer!

I attach a screen from drone.io server:
https://ibb.co/DV8CmdZ

### Steps To Reproduce

php artisan test

**Comment by driesvints** [comment]
I'm sorry but we don't provide support for drone.io. If you want to change something you can attempt a PR. Thanks
