### ISSUE TITLE
getCustomMessageFromTranslator not working with flat json files

### ISSUE THREAD

**Issue by SamuelWei** [laravel/framework#47030]
### Laravel Version

10.4.1

### PHP Version

8.1.17

### Description

I use the same localisation file for my vue frontend as for Laravel. Laravel supports nested json files as well as flat json files for all regular translations.

However for validation the following syntax is not working:

```json
"validation.custom.emails.*.distinct": "demo message",
```

The following syntax however is working:
```json
"validation.custom" : {
        "emails.*.distinct": "demo message"
},
```

I guess this is because in getCustomMessageFromTranslator the function tries to get the array "validation.custom" which doesn't exist if the translation file is flat.
https://github.com/laravel/framework/blob/c36812aad058f5c408f79331b8086c0f68f24ae4/src/Illuminate/Validation/Concerns/FormatsMessages.php#L159

### Steps To Reproduce

routes/web.php
```php
...

Route::get('/test', function () {
    $data = [
        'foo'       => [1,1],
        'bar'       => [1,1],
    ];
    $rules = [
        'foo'       => 'array',
        'foo.*'     => 'distinct',
        'bar'       => 'array',
        'bar.*'     => 'distinct'
    ];
    $validator = Validator::make($data, $rules);
    $errors = $validator->errors();
    dd($errors);
});

...
```

lang/en.json
```json
{
    "validation.custom.foo.*.distinct": "test",
    "validation.custom" : {
        "bar.*.distinct": "test"
    }
}
```

**Comment by nunomaduro** [comment]
To add custom messages for specific attributes, according to [our documentation](https://laravel.com/docs/10.x/validation#custom-messages-for-specific-attributes), you currently need to use the `validation.custom` on the array format.

If you believe that this is a bug, or if you think that Laravel should support a different format, we encourage you to submit a pull request that includes the required tests. However, please be aware that your pull request may not be accepted, particularly if there is a risk of introducing breaking changes for existing users.

**Comment by SamuelWei** [comment]
Hi @nunomaduro,  I believe this is a bug because it is inconsistent with the behavior of the translation files in all other areas of the framework. For all other areas, it doesn't matter if the array is written with the dot notation or is nested as a real array.

**Comment by nunomaduro** [comment]
@SamuelWei Got it! Would you like to give it a shot and create a pull request? It's important to keep in mind that the changes you propose may not be accepted, especially if they could cause issues for current users.

**Comment by SamuelWei** [comment]
Hi @nunomaduro, while writing a test a also noticed an other faulty behavoir that is not documented and should also be fixed.

See: https://github.com/SamuelWei/framework/commit/90508e94e10a7eaaab68d95b92068449e58f78e9

This tests shows that the order in which the strings are placed in the localisation file is important.

**Working**
```json
{
    "validation.custom": {
        "users.*.posts.*.name": {
            "required": "post name is required"
        },
        "users.*.name": {
            "required": "user name is required"
        }
    }
}
```

**Failing**
```json
{
    "validation.custom": {
        "users.*.posts.*.name": {
            "required": "post name is required"
        },
        "users.*.name": {
            "required": "user name is required"
        }
    }
}
```
