### ISSUE TITLE
The file "" does not exist in MimeTypeGuesser.php:123 #23492

### ISSUE THREAD

**Issue by n1mah** [laravel/framework#47049]
### Laravel Version

laravel10

### PHP Version

8.2

### Description

`The file " does not exist in MimeTypeGuesser.php:123 #23492`  (error)  Sometimes this happens because of limit uploaded file in Default config on Laravel ." 

### Steps To Reproduce

maximum size is **2Mb** . 
change this on ini.php (server , Host , ...) or set Config

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
