### ISSUE TITLE
[9.19] Applying scopes & count on MorphMany relation doesn't bind relation

### ISSUE THREAD

**Issue by guillaumeboussion** [laravel/framework#47053]
### Laravel Version

9.19

### PHP Version

8.1

### Database Driver & Version

MySQL 8

### Description

When having MorphMany relation, calling it, applying relation's scope & calling `count()` method, the given relation is not filtering on the relation's key, returning ALL records

### Steps To Reproduce

When having MorphMany relation, given I call the relation this way : 

```php
class Rule extends Model {

 public function myRelation(): MorphMany
    {
        return $this->morphMany(MyRelation::class, 'category');
    }

public function getMyAttributeCount(): int
{
    return $this->myRelation()->myRelationScope()->count();
}
```

and I log queries :

`select count(*) as aggregate from 'my_relations' where 'state' != ? and 'ce_id' = ? and 'user_id' = ? and 'payment_date' between ? and ?`

As you can see, relation is not binded to `Rule` model.

But, if I simply `count()` without any scope, the relation is binded.

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
