### ISSUE TITLE
Using name attribute with Scoped Slots

### ISSUE THREAD

**Issue by AntonCooper** [laravel/framework#47057]
### Laravel Version

9.52.7

### PHP Version

8.2.5

### Description

Passing a `name` attribute into a component scoped slot will cause the supplied name attribute to be missing in the scoped slot's attribute variable. This only occurs when `name` is the _first_ attribute passed in.

`ComponentTagCompiler::compileSlots` is responsible for this. My understanding is that slots used to be named by passing a name attribute. This is no longer the documented way of creating a named slot but this check is still in the code to support backwards compatibility. 

Because `name` is a very common HTML attribute used on forms, this gotcha can catch you out very easily and result in some unexpected behaviour of the name attribute just disappearing - which can cause forms to break

### Possible Solutions
- Document this behaviour in the docs
- Deprecate naming slots using the `name` attribute and drop support for in the next major release
- Make the `name` attribute available in the scoped slot's attribute variable

### Steps To Reproduce

Create a component in `resources/views/components/input.blade.php`
```blade
@props([
    'input'
])

<div>
    <input type="text" {{ $input->attributes->class('input') }} />
</div>
```

Render the component, passing a name attribute as the first first attribute
```php
Blade::render('
<x-input>
    <x-slot:input name="my_form_field" class="text-input-lg" data-test="data">Test</x-slot:input>
</x-input>
');
```

Observe, the `name` does not get rendered in the slot's attributes
```html
<div class="block">
    <input type="text" class="input text-input-lg" data-test="data" />
</div>
```

Moving the name attribute to not being the first attribute will make the name attribute render 
```php
Blade::render('
<x-input>
    <x-slot:input class="text-input-lg" name="my_form_field" data-test="data">Test</x-slot:input>
</x-input>
');
```

Outputs
```html
<div class="block">
    <input type="text" class="input text-input-lg" name="my_form_field" data-test="data" />
</div>
```

**Comment by nunomaduro** [comment]
Made a pull request clarifying this situation: https://github.com/laravel/docs/pull/8788. No worries, if Taylor thinks that this issue should be addressed for Laravel 10 or 11, I will follow up. Thanks!

**Comment by taylorotwell** [comment]
This should just be fixed.

**Comment by taylorotwell** [comment]
https://github.com/laravel/framework/pull/47065
