### ISSUE TITLE
Incorrect Ordering in Cursor Pagination when Using DB Query Builder

### ISSUE THREAD

**Issue by opencubicles** [laravel/framework#47078]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

Description:

When utilizing Laravel's cursor pagination feature with the cursorPaginate() method and attempting to navigate to the previous page using the prev_cursor parameter, the retrieved results are not the 10 records immediately preceding the prev_cursor. Instead, the pagination starts from the beginning, returning the first 10 records.

### Steps To Reproduce

**Steps to Reproduce:**

1. Use the cursorPaginate() method for cursor pagination, with the following code:

`$terms =  DB::table('terms')->orderBy('id')->select('id', 'title')->cursorPaginate(10);`

2. Make a request to retrieve the next page of results.

3. Retrieve the prev_cursor value from the response.

4. Make a request to navigate to the previous page, using the prev_cursor as the cursor parameter.

**Expected Result:**

When navigating to the previous page using the prev_cursor, the query should reverse the ordering and retrieve the correct results so that application retrieve the immediate preceding 10 results before the specified cursor. The expected SQL query should be:

`select * from `terms` where (`id` <  200) order by `id` desc limit 11`

Above query always returns 11 records, starting from the first record in the entire database table.

**Actual Result:**
Instead, the generated SQL query is:

`select * from `terms` where (`title` < 200) order by `id` asc limit 11`

Note: Eloquent Models Working Correctly as expected.

**Comment by nunomaduro** [comment]
I've tested locally, and indeed the cursorPaginate method is broken when used with raw query builder. @paras-malhotra Any ideas on this?
