### ISSUE TITLE
Markdown Mailables do not allow image embedding in html templates

### ISSUE THREAD

**Issue by dakira** [laravel/framework#47085]
### Laravel Version

10.10.1

### PHP Version

8.1.17

### Description

When creating a markdown mailable and publishing the templates, embedding an image (e.g. a logo) is not possible because the `$message` variable is not shared with the view in contrast to what is stated [in the documentation](https://laravel.com/docs/10.x/mail#:~:text=Laravel%20automatically%20makes,variable%20available).

The documentation also states, that the `$message` variable is not shared in plain test messages. As markdown mailables are HTML messages, either the info should be changed or this is a bug.

### Steps To Reproduce

1. Create a markdown mailable
  `php artisan make:mail OrderShipped --markdown=emails.orders.shipped`
2. Publish the templates
  `php artisan vendor:publish --tag=laravel-mail`
3. Change *resources/views/vendor/mail/html/message.blade.php* to add this header:
  ```
  <img
      src="{{ $message->embedData(
          data: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" /></svg>',
          name: 'logo.svg',
          contentType: 'image/svg+xml',
      ) }}"
      class="logo"
      alt="Logo"
  />
  ```
4. Open `php artisan tinker` and run
  ```
  Mail::to('a@a')->send(new App\Mail\OrderShipped);
  ```

Here is a repository that shows the [error](https://github.com/dakira/laravel-markdown-embeds/commit/0aec0bdceed8084b3b210fe5cc8723f451f00653) and [another commit](https://github.com/dakira/laravel-markdown-embeds/commit/c6248dbef3cc6255ae88351fd3351b690627d1c8) that shows that embedding files in markdown mailables actually is (and should be) possible by manually embedding the image in the Symfony `Email` message and using the *cid* in the template.

The sample apps / route will send the message (using the configured mailer) and display it.

To further investigate I moved to usage of the `$message` variable from the published html templates to the blade file of the mailable in [this commit](https://github.com/dakira/laravel-markdown-embeds/commit/0b40cbb3f60c0873342631b14445988be270b622) which still has the same problem.

To double-check that it **does** work with a regular view (instead of markdown) I changed the mailable to use a regular view and that did indeed work.

**Comment by dakira** [comment]
I wanted to make a PR for this but for the life of me couldn't figure out at what point the `$message` variable is shared in case of regular HTML mailables, so sorry for that. If you give me a pointer (and also think this is a bug), I will happily work on a PR.

**Comment by taylorotwell** [comment]
$message is set on line 279 of `Mailer`:

```php
$data['message'] = $message = $this->createMessage();
```

**Comment by dakira** [comment]
Phew.. this one really is a rabbit hole.

**Comment by nunomaduro** [comment]
Can you make a pull request, and we can work from there?

**Comment by dakira** [comment]
Sure, I’ll whip something up tomorrow!

**Comment by nunomaduro** [comment]
@dakira You still plan on making your pull request? Otherwise, I will probably take it.
