### ISSUE TITLE
[9.x] - php artisan test always return exit code 0

### ISSUE THREAD

**Issue by acgfbr** [laravel/framework#47101]
### Laravel Version

9.52.7

### PHP Version

8.1.18

### Database Driver & Version

mysql 8.0.32

### Description

hey friends i have a issue with php artisan test on my laravel project, every time that i ran php artisan test, parallel or not, with errors, the exit code is 0, someone can help me please? i don't found any related on internet about this lol and idk how to figure out

example:
```
create a test and instantiate a fake class like:  new ASDASDASD();
error will be:  Class "Tests\Feature\ASDASDASD" not found

php artisan test --verbose --stop-on-failure

after fail
echo $?
0
```

this is breaking my ci because ci expects 1 to stop

### Steps To Reproduce

php artisan test --verbose --stop-on-failure

**Comment by acgfbr** [comment]
hey nuno, i just created a fresh project with this specific version and its returning exit code 2, so, i'm closing this issue because is not framework related and something with project, i will investigate further, thanks for your time 😄

**Comment by nunomaduro** [comment]
No problem.
