### ISSUE TITLE
Already exists table after getting a foreign key exception

### ISSUE THREAD

**Issue by RingLives** [laravel/framework#47106]
### Laravel Version

^8.12

### PHP Version

7.4

### Database Driver & Version

mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

### Description

When I migrate and get an exception. **SQLSTATE[HY000]: General Error: 1215 Cannot add foreign key constraint** But the table is created. Running the migrate command after troubleshooting the migration shows that the table already exists. But the migration file name is not inserted into the migration table. The **migrate:rollback** command is not working for this problem, because the last migration has not been inserted.

### Steps To Reproduce

Creating the exception on CLI:

Migration File 1: 2023_05_16_153923_create_categories_table.php

public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
                    $table->increments('id');
                    $table->timestamps();
        });
    }

Migration File 2: 2023_05_16_154104_create_products_table.php

public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedBigInteger('category_id');    // error here, But that's not the problem I mentioned
            $table->foreign('category_id')->references('id')->on('categories');
            $table->timestamps();
        });
    }
    
    After fixing the migration problem the table must be deleted before running the migrate command.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
