### ISSUE TITLE
Laravel 10 - model with cast encrypted on create return 'The payload is invalid.'

### ISSUE THREAD

**Issue by andreazorzi** [laravel/framework#47108]
### Laravel Version

10.11.0

### PHP Version

8.1.9

### Description

Hi, I have this issue with model encryption cast. The problem seems to appear only when I use the create method of a model with protected cast set to encrypted for certain columns. When I try to create a new entry, it gives me the error 'The payload is invalid.', but when I check in the database the data was actually added and the values are crypted. If I look where the exception happens, I get this message:

```
exception: "Illuminate\\Contracts\\Encryption\\DecryptException"
```

It seems that the error occurs after the data were stored in the database, then Laravel tries to return the model object decrypting the values, failing (I think Laravel tries to decrypt plain data). But if I try to get this model data and display them in a page, I have no error and the encrypted data was actually decrypted.

Below I put my code

Migration
```php
Schema::create('Strutture', function (Blueprint $table) {
    $table->string('Struttura');
    $table->string('Nome');
    $table->text('Username')->nullable();
    $table->text('Password')->nullable();
    $table->text('Wskey')->nullable();

    $table->primary('Struttura');
});
```

Strutture Class
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Struttura extends Model
{
    protected $table = 'Strutture';
    protected $primaryKey = 'Struttura';
    public $incrementing = false;
    public $timestamps = false;
    
    protected $fillable = ['Struttura', 'Nome', 'Username', 'Password', 'Wskey'];
    protected $attributes  = [
        'Nome' => '',
        'Username' => '',
        'Password' => '',
        'Wskey' => ''
    ];
    
    public static function createFromJson(string $json){
        $json = json_decode($json, true);
        
        if(is_null($json)){
            return [
                "status" => false,
                "error" => "Invalid JSON"
            ];
        }
        
        foreach($json as $key => $data){
            if(!$test_login["status"]){
                $errors[] = $key;
                continue;
            }
            
            Struttura::updateOrCreate([
                'Struttura' => $key
            ],
            [
                'Nome' => $data['name'],
                'Username' => $data['username'],
                'Password' => $data['password'],
                'Wskey' => $data['wskey']
            ]);
        }
        
        return [
            "status" => true
        ];
    }
    
    protected $casts = [
        'Username' => "encrypted",
        'Password' => "encrypted",
        'Wskey' => "encrypted"
    ];
}
```

# Update
Today I tried to debug the code and follow every function called when I execute the creation method and find out that the error occurs because the model attribute "original" is empty in this function:

```
Illuminate\Database\Eloquent\Concerns\HasAttributes.php -> originalIsEquivalent()
```

It seems that in this function compare the encrypted data with the original data, but since th original data attribute is empty, it return the error.
I try to rearrange the function:

```
Illuminate\Database\Eloquent\Models.php -> finishSave()
```

I moved the code: $this->syncOriginal(); before the if statement and seems to fix the problem bu I don't know if this change could break something else.

This is the function that I change

```php
/**
 * Perform any actions that are necessary after the model is saved.
 *
 * @param  array  $options
 * @return void
 */
protected function finishSave(array $options)
{
    $this->fireModelEvent('saved', false);
    $this->syncOriginal();

    if ($this->isDirty() && ($options['touch'] ?? true)) {
        $this->touchOwners();
    }
    
    // $this->syncOriginal();
}
```

### Steps To Reproduce

Reported above

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by andreazorzi** [comment]
Hi @nunomaduro I tried a week ago to asking the same question but I haven't had an answer yet.
I tried to search online but it seems that no one has had the same problem.
I also followed two guides that explain how to use encrypted cast ended up with the same error.
Not having a complete understanding of the project, I still tried to follow the procedure of creating a model.
As I wrote, the problem occurs when the model is created, during the data saving phase, the model tries to decrypt the original attributes, which, being empty, goes into error.
A solution could be that in the Model class, when the newInstace() is invoked, the $model->syncOriginal() function could be executed if the variable $model->exists is false in order to set the original attributes only if the model created is a new model.
As I say I don't have a complete undertanding of the project and I don't know if this change could break something else.
Could this be a solution?

Thanks

```php
public function newInstance($attributes = [], $exists = false)
    {
        // This method just provides a convenient way for us to generate fresh model
        // instances of this current model. It is particularly useful during the
        // hydration of new objects via the Eloquent query builder instances.
        $model = new static;

        $model->exists = $exists;

        $model->setConnection(
            $this->getConnectionName()
        );

        $model->setTable($this->getTable());

        $model->mergeCasts($this->casts);

        $model->fill((array) $attributes);
        
        // Set original attributes if it is a new model
        if(!$model->exists){
            $model->syncOriginal();
        }

        return $model;
    }
```
