### ISSUE TITLE
$request->merge() seems to have stopped working

### ISSUE THREAD

**Issue by gilbitron** [laravel/framework#47129]
### Laravel Version

9.52.7

### PHP Version

8.1

### Description

We have a global middleware where we're overriding the route "domain" using a domain from a custom header (sent by a reverse proxy). Simplified example:

```php
$domain = $request->header('apx-incoming-host');
if ($domain) {
    $request->merge(['domain' => $domain]);
}
```

In a separate middleware we later in the request, we try and fetch the domain using:

```php
$request->route('domain')
```

However, the `$request->route('domain')` returns the host from the URL and not the domain from the header that was merged. Note: this seemed to work fine up until this week.

### Steps To Reproduce

* Create a middleware with the "merge" code from above
* Add this middelware to the global `protected $middleware` array in `App\Http\Kernel`
* Create a second middleware that uses `$request->route('domain')`
* Register this middleware in a route
* Run `curl -kH "apx-incoming-host: customdomain.test" https://example.test`

**Comment by gilbitron** [comment]
So I've managed to resolve the issue by:

1. Moving the initial middleware from the global `protected $middleware` to the `web` middleware group
2. Using the following code instead of "merge":

```php
$request->route()?->setParameter('domain', $domain);
```

Note that `$request->route()` was `null` when registered in the global `protected $middleware`.

I'd still be interested to know if there is a reason why this stopped working recently?

**Comment by nunomaduro** [comment]
> I'd still be interested to know if there is a reason why the "merge" solution stopped working recently?

We have recently made a specific modification to the middleware priority. When sorting the middleware priority, we now take into account the parent class as well. You can find more details about this change at: https://github.com/laravel/framework/pull/46972.

Regardless, considering your requirement, it would have been advisable to always use `setParameter` approach. By doing so, your middleware wouldn't have become dependent on the priority or order.

**Comment by driesvints** [comment]
Hi @gilbitron. Sorry you got caught by this. I hope you can see/understand why we did that change?

**Comment by gilbitron** [comment]
Thanks for the explanation @nunomaduro. That makes sense 👍 

@driesvints No problem. I figured my latter approach was a better solution anyway 👍
