### ISSUE TITLE
Some cached views are .php files, some are .blade.php

### ISSUE THREAD

**Issue by szepeviktor** [laravel/framework#47125]
### Laravel Version

10.10.1

### PHP Version

8.2.6

### Database Driver & Version

MariaDB v10.3.38, Debian Linux amd64

### Description

I think it boils down to [blade files](https://github.com/laravel/framework/blob/1719c366d18ebb01fcab77a2a78040fe5c7cded9/src/Illuminate/View/Compilers/Compiler.php#L63) have `$hash.php` cache file names,
[string based](https://github.com/laravel/framework/blob/1719c366d18ebb01fcab77a2a78040fe5c7cded9/src/Illuminate/View/Component.php#L190) ones have `$hash.blade.php`

files in `storage/framework/views/`
```
-rw-r--r-- 1 itmap itmap   497 May 18 08:36 7beab06ef10a8262514a61551bbddfaf.php
-rw-r--r-- 1 itmap itmap   105 May 18 08:37 7c5324e2cef4139f2a7a40f161e4c877.blade.php
-rw-r--r-- 1 itmap itmap  3497 May 18 08:36 8397cfe6be9bbf5a7f82d019c9d4ee18.php
-rw-r--r-- 1 itmap itmap  4652 May 18 08:36 8c58183c610c07d638a9f6e7e375847e.php
-rw-r--r-- 1 itmap itmap   457 May 18 08:37 8d6a3c82d541c18d9dd2d0d95ac5ec62.php
-rw-r--r-- 1 itmap itmap   706 May 18 08:36 8dbe8ef6c4ddfd3c503b0fb419fc98d6.php
-rw-r--r-- 1 itmap itmap   760 May 18 08:36 9014bb0524ddb5f65c0e295935fc236d.php
-rw-r--r-- 1 itmap itmap  1656 May 18 08:36 911ae4c237e11ccc0028e2a44622d819.php
-rw-r--r-- 1 itmap itmap  9759 May 18 08:36 95b1a98d190971d65375792e86ef59ca.php
-rw-r--r-- 1 itmap itmap  3738 May 18 08:36 962648b37edb1d4b338a678441179a89.php
-rw-r--r-- 1 itmap itmap  3397 May 18 08:36 965bf19a935e3904cc0157a10ecd5542.php
-rw-r--r-- 1 itmap itmap   271 May 18 08:37 99a867f530496edb88dca54ef7748a2b.blade.php
-rw-r--r-- 1 itmap itmap  6294 May 18 08:36 99e1a8dfaad0e09a886d0180cc7d0bb9.php
```

Please consider using only one naming pattern.

### Steps To Reproduce

Simply run any Laravel application.

**Comment by driesvints** [comment]
Hi there. If everything is running fine then there's no issue here.

**Comment by szepeviktor** [comment]
I care about every byte in an application.
I regulate these cache file names with a regexp.
