### ISSUE TITLE
remove file in request

### ISSUE THREAD

**Issue by mderakhshi** [laravel/framework#47131]
### Laravel Version

10.11

### PHP Version

8.1

### Description

i have one input file like this:
```
<input type="file" name="company_logo" />
```
after upload in storage, i want change request->input('company_logo') to new name string like : "test_(timestamp).png"

i read document and  classes structure, found $request->files : [FileBag] , remove company_logo in FileBag
but company_logo not removed in request->all():

my code is:

```
                        $request->attributes->remove('company_logo');
                        $request->server->remove('company_logo');
                        $request->query->remove('company_logo');
                        $request->files->remove('company_logo');
                        $request->request->remove('company_logo');
                        $request->merge(['company_logo'=>'test_(timestamp).png']);
                        $request->replace(['company_logo'=>'test_(timestamp).png']);
                        dd($request->all());

```
result is:

```
[
{
"company_logo" => Illuminate\Http\UploadedFile {#563
    -test: false
    -originalName: "1130-lion-hd-wallpapers-background-images-wallpaper-abyss.jpg"
    -mimeType: "image/jpeg"
    -error: 0
    #hashName: "glH5tTHQmCyM1Kkq78xqCjhd8fXv2XZpeW9Ixh3B"
    path: "/tmp"
    filename: "phpYUlITL"
    basename: "phpYUlITL"
    pathname: "/tmp/phpYUlITL"
    extension: ""
    realPath: "/tmp/phpYUlITL"
    writable: false
    readable: false
    executable: false
    file: false
    dir: false
    link: false
  }
]
```

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mderakhshi** [comment]
@driesvints
this not question

```
$request->files->remove('company_logo');
...
$request->files->all() is empty [true]
$request->allFiles() is not empty [have problem]
```

$this->convertedFiles is null , function allFiles must return FileBag[ $this->files->all() ]  is empty :
```
  public function allFiles()
    {
        $files = $this->files->all();

        return $this->convertedFiles = $this->convertedFiles ?? $this->convertUploadedFiles($files);
    }
```

but $this->files restore with magic method __cal or .., i cant find it

**Comment by mderakhshi** [comment]
@driesvints  
When there is a real problem
Let's take action to fix it

You close topics very quickly.

Please reopen this topic, maybe someone will suggest a solution for this issue
