### ISSUE TITLE
Eloquent Duplicating Records on Save when returning file

### ISSUE THREAD

**Issue by redarrowdriver** [laravel/framework#47172]
### Laravel Version

10.3.3

### PHP Version

8.1.2

### Database Driver & Version

MySQL 8.0.33 ubuntu

### Description

Eloquent appears to be duplicating record inserts when using the save() method when returning a file download.

I removed the return and the record saved as expected (only one insert occurred).

### Steps To Reproduce

$lead->name = $request->name;
$lead->phone_number = $request->phone_number;
$lead->email = $request->email;
$lead->save();

return response()->file(storage_path('app/public/downloads/pricingRackCard.pdf'));

Running the above code introduces the bug in my instance.

**Comment by shahadat016** [comment]
I could not reproduce this issue. Working as expected on my machine.

Laravel Versions
10.3.3, 10.11.0

PHP Version
8.1.1, 8.2.4

Database Driver & Version
MySQL 8.0.30, 8.0.33 windows
