### ISSUE TITLE
Laravel schema blueprint default values do not convert PHP Enums to It's primitive scalar type

### ISSUE THREAD

**Issue by Brunnn** [laravel/framework#47183]
### Laravel Version

10.10.1

### PHP Version

8.1.12

### Description

 I'm using the new PHP 8 enums in my repo, and i noticed that laravel already provides compatibility with them in the majority of cases, queries, eloquent models (with casts), etc. So i'm not sure if this is something that was missed...
 But i noticed that it throws an error if used in migrations when defining default values for columns, see the code:
```php
Schema::table('users', function (Blueprint $table) {
   $table->string('role')->default(RoleEnum::CUSTOMER);
});
```
![image](https://github.com/laravel/framework/assets/42523274/9f730e09-bc78-4406-81e1-3d365f30a03a)

Is that intended? This could solved with something like this in framework's  `\Illuminate\Database\Schema\Grammars\Grammar.php`
```php
  /**
   * Format a value so that it can be used in "default" clauses.
   *
   * @param  mixed  $value
   * @return string
   */
  protected function getDefaultValue($value)
  {
      if ($value instanceof Expression) {
          return $this->getValue($value);
      }

      //here
      if ($value instanceof \BackedEnum){
          return "'".$value->value."'";
      }

      return is_bool($value)
                  ? "'".(int) $value."'"
                  : "'".(string) $value."'";
  }
```

I could open a PR for that if its appropriate.

### Steps To Reproduce

-> Create a migration
-> Any column's `default`  method does not accept plain Enum values.

**Comment by henzeb** [comment]
It seems it's not. Interesting PR discussion: https://github.com/laravel/framework/pull/45654

**Comment by driesvints** [comment]
This isn't supported sorry and we have no plans to do this.
