### ISSUE TITLE
[5.0] Improve Migration creation when using Illuminate\Database standalone

### ISSUE THREAD

**Issue by rawebone** [laravel/framework#4719]
This is my first contribution to this project, so I hope I've done this correctly!

It's a very minor thing, but when using the `MigrationCreator` from the Illuminate\Database package the output files refer to `Schema::create()` rather than `Capsule::schema()->create()` as the documentation dictates.

While it is very simple to change this manually, long term is isn't really intuitive. Other than sub-classing and overriding `getStubPath()` and maintaining your own collection of stubs, there is no way to automate the creation process to account for Capsule. 

As such, I propose a very simple switch in the constructor of the `MigrationCreator` to account for Capsule as can be seen [here](https://github.com/rawebone/framework/blob/capsule-migration-fixes/src/Illuminate/Database/Migrations/MigrationCreator.php#L47). There won't be an impact for the main framework as the default is false.

Nick

**Comment by GrahamCampbell** [comment]
Closing due to little interest. This would probably be quite hard to do too.
