### ISSUE TITLE
Registering a new translation path is not used if translations are already loaded

### ISSUE THREAD

**Issue by netpok** [laravel/framework#47194]
### Laravel Version

10.12.0

### PHP Version

8.2.x

### Description

When translations are loaded and a new translation are registered via
`app('translation.loader')->addJsonPath()` and the translations were previously loaded then it wont take effect since the translator considers it already loaded. 

The solution is probably to clear the loaded translations upon a new path registration.

### Steps To Reproduce

- Clone: https://github.com/netpok/laravel-translation-bug
- run `php artisan scribe:generate`
- check public/docs/index.html in browser it will contain invalid translations

- uncomment AppServiceProvider line 17 to clear translation cache before adding other jsonpaths
- run `php artisan scribe:generate`
- check public/docs/index.html in browser it will now contain correct translations

**Comment by driesvints** [comment]
Hi there. Please re-create the repo with a separate commit containing all the custom changes you made apart from the skeleton. Please keep these changes to a minimum.

**Comment by nunomaduro** [comment]
Hey, as suggested by @driesvints, it would be great if you could create a repository with a super simple Laravel application. That way, we can easily replicate the issue on our side. Note that, the problem you described seems to be a recognized bug by the package author. Check it out here: https://github.com/BenSampo/laravel-enum/pull/309.
