### ISSUE TITLE
Misleading typo in phpunit testing with assertDontSeeText

### ISSUE THREAD

**Issue by BiRo96** [laravel/framework#47209]
### Laravel Version

10.10

### PHP Version

8.1

### Description

If **assertDontSeeText()** sees the given text that it shouldn't, it will give a failure report, that the subject **does not contain** the given text instead of saying it indeed contains the text. It's a little bit misleading. I mean it really was in my case :D

I thought it was for **assertSeeText()** until I realized it came from line 44.

![Typo case](https://github.com/laravel/framework/assets/22392953/96ab867e-4e08-494b-b57e-ef9a271c9347)

### Steps To Reproduce

It is seen in the image:
**phpunit test**: in Feature test, use assertDontSeeText() on a page that contains the given text.

**Comment by driesvints** [comment]
It's not included in your screenshot but I think the text before the html output says something like "Failed asserting that ..." which would make it correct.

Anyway, this is a PHPUnit error message and not a Laravel one so we can't do anything about this ourselves, sorry.
