### ISSUE TITLE
hmget no processing bool

### ISSUE THREAD

**Issue by zeromake** [laravel/framework#47212]
### Laravel Version

7.2.2

### PHP Version

7.4.3

### Description

No processing return is `flase`
```
array_values($this->command('hmget', [$key, $dictionary]));
```

error:
```
array_values() expects parameter 1 to be array, bool given
```

https://github.com/illuminate/redis/blob/master/Connections/PhpRedisConnection.php#L110-L117

### Steps To Reproduce

```php
use Illuminate\Support\Facades\Redis;

$r = Redis::connection();
$keys = [];
$r->hmget('test', ...keys);
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
