### ISSUE TITLE
Eloquent AsEncrypted* castables don't use Model::encryptUsing

### ISSUE THREAD

**Issue by krmroland** [laravel/framework#47239]
### Laravel Version

10.11.0

### PHP Version

8.26

### Description

Models casts AsEncryptedArrayObject and AsEncryptedCollection Don't use eloquent's custom encrypter

### Steps To Reproduce

<img width="1072" alt="Screenshot 2023-05-26 at 01 13 08" src="https://github.com/laravel/framework/assets/33207024/90c520dd-5b26-4d31-93be-56fcb9d1c502">

**Comment by krmroland** [comment]
See https://github.com/laravel/framework/discussions/47224

**Comment by driesvints** [comment]
Seems like a feature request. Feel free to attempt a PR 👍
