### ISSUE TITLE
Call to a member function allOnQueue() on null

### ISSUE THREAD

**Issue by marensas** [laravel/framework#47232]
### Laravel Version

10.8.0

### PHP Version

8.2

### Description

I simplified my code to this prototype:

```
// doing some stuff before batch dispatch

$jobChain = [...];

Bus::batch([$jobChain])->then(...)->catch(...)->dispatch(); // error thrown when dispatching

// code is not executed
```

As you can see I need to run jobs in a synchronous way (chain), but also in a batch for having a possibility to use `then` or `catch` callbacks.

The problem is that sometimes my job chain could be empty, so I'm getting a `Call to a member function allOnQueue() on null` error. For me personally, this is unexpected behaviour, because I expecting to run a batch even with an empty job chain and continue processing code where the batch is executed.

Even if this would be not recognized as a bug, I would expect a better error message i.e. "Job chain is empty." or something like that.

### Steps To Reproduce

```
$jobChain = [];
Bus::batch([$jobChain])->dispatch();
```

**Comment by driesvints** [comment]
> The problem is that sometimes my job chain could be empty,

Just check the job chain with an if statement before executing.

**Comment by marensas** [comment]
> > The problem is that sometimes my job chain could be empty,
> 
> Just check the job chain with an if statement before executing.

I'v done that... with a hotfix to production after 1k errors :) This is not expected behaviour for me, that's why I raised this issue.

I.e. why not to skip empty chains?

```
Bus::batch([
  [], // empty
  [...], // full
])->dispatch();

// all works
```
