### ISSUE TITLE
Undefined Js::__set_state() after caching routes, when using JS::from()

### ISSUE THREAD

**Issue by HeySora** [laravel/framework#47251]
### Laravel Version

10.12.0

### PHP Version

8.2.6

### Description

The entire application breaks when caching routes that use Js::from().

Even `php artisan route:clear` cannot work due to the error. Manually deleting `bootstrap/cache/routes-v7.php` is the only way to restore functionality.

This is not specifically new to v10.12.0, as this also happened on v10.9.

### Steps To Reproduce

1. Define a view route using a Js::from() parameter

```php
use Illuminate\Support\Js;

Route::view('/thing', 'my.view', [
    'list' => Js::from([1, 2, 3])
]);
```

2. Cache the route

`php artisan route:cache`

3. The entire application will now be broken, due to the error in routes-v7.php
![image](https://github.com/laravel/framework/assets/17962248/614f6449-0eae-45d4-b36b-a51fcc92b3eb)

Here is the exact generated route code in routes-v7.php
```php
  'generated::icUsDJ3anOXWYT1l' => 
  array (
    'methods' => 
    array (
      0 => 'GET',
      1 => 'HEAD',
    ),
    'uri' => 'thing',
    'action' => 
    array (
      'middleware' => 
      array (
        0 => 'web',
      ),
      'uses' => '\\Illuminate\\Routing\\ViewController@__invoke',
      'controller' => '\\Illuminate\\Routing\\ViewController',
      'namespace' => NULL,
      'prefix' => '',
      'where' => 
      array (
      ),
      'as' => 'generated::icUsDJ3anOXWYT1l',
    ),
    'fallback' => false,
    'defaults' => 
    array (
      'view' => 'my.view',
      'data' => 
      array (
        'list' => 
        // vvvvvv HERE IS THE ERROR vvvvvv
        \Illuminate\Support\Js::__set_state(array(
        // ^^^^^^ HERE IS THE ERROR ^^^^^^
           'js' => 'JSON.parse(\'[1,2,3]\')',
        )),
      ),
      'status' => 200,
      'headers' => 
      array (
      ),
    ),
    'wheres' => 
    array (
    ),
    'bindingFields' => 
    array (
    ),
    'lockSeconds' => NULL,
    'waitSeconds' => NULL,
    'withTrashed' => false,
  ),
```

**Comment by HeySora** [comment]
I'd like to add that the reason I am filling this as a bug is because of the breaking consequences of such an action.

I am of course aware of workarounds, such as using a controller action instead, or even calling `JS::from()` from the view itself.  
If using a `Js` instance in view arguments is unsupported, that's okay but the caching process should actually throw some kind of exception instead of letting the file being written to. (Maybe having a failsafe with a dummy `eval()` of the compiled array to detect any inconsistency and preventing the cached file to be written?)

**Comment by driesvints** [comment]
`Js::from` should only be used in Blade templates.

**Comment by HeySora** [comment]
> `Js::from` should only be used in Blade templates.

@driesvints Alright makes sense, but what about the rest of the issue?

> If using a `Js` instance in view arguments is unsupported, that's okay but the caching process should actually throw some kind of exception instead of letting the file being written to. (Maybe having a failsafe with a dummy `eval()` of the compiled array to detect any inconsistency and preventing the cached file to be written?)

I still don't think it is appropriate of Laravel of softlocking itself without warning if invalid data is present in the routes, requiring manual intervention on the filesystem.

**Comment by driesvints** [comment]
Sorry but this is a bug in your code. If you feel Laravel should behave differently here, please attempt a PR.

**Comment by HeySora** [comment]
It is not a bug in my code, I even provided repro steps from a fresh new project..?

To rephrase the issue shortly: Any attempt to use any object in a route parameter, and then proceeding to cache routes will make Laravel stop working, as `var_export` will generate invalid code (due to those objects missing `__set_state()` definition).

The expected outcome is that Laravel errors out *before* writing that invalid PHP code to the route cache, instead of completely breaking and being unable to recover itself after the fact.
