### ISSUE TITLE
RefreshDatabase trait issue when using mysql instead of sqlite + in-memory database

### ISSUE THREAD

**Issue by absarakram** [laravel/framework#47274]
### Laravel Version

10.10

### PHP Version

8.1

### Database Driver & Version

MySQL 8.0.27

### Description

On a fresh Laravel + Breeze(blade) install,
When `mysql` database is used for `phpunit` instead of `sqlite`, the user email(`test@example.com`) used in `test_profile_information_can_be_updated` and `test_new_users_can_register` causes a conflict.

This results in the following error

````
1) Tests\Feature\ProfileTest::test_profile_information_can_be_updated
Session has unexpected errors:

{
    "default": [
        "The email has already been taken."
    ]
}
Failed asserting that true is false
````

Changing the email(`test@example.com`) in either of the 2 tests fixes the issue for time being. 
A proper fix will likely require updating RefreshDatabase trait for `mysql` or `not-in-memory` databases.

### Steps To Reproduce

Install Laravel (use mysql DB)
Install Breeze
(keep default database config for phpunit.xml)
./vendor/bin/phpunit

**Comment by nunomaduro** [comment]
After freshly installing Breeze in my Laravel project and configuring MySQL in my .env file, I have been unable to replicate the problem you mentioned:

```php
➜ ./vendor/bin/phpunit        
PHPUnit 10.1.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.5
Configuration: /Users/nunomaduro/Work/Code/laravel/phpunit.xml

........................                                          24 / 24 (100%)

Time: 00:01.250, Memory: 40.50 MB

OK (24 tests, 56 assertions)
```

And, I can confirm that the main purpose of the RefreshDatabase trait is to clear the database between tests, so the scenario you described is unlikely to occur.

That been said, can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
