### ISSUE TITLE
Laravel doesn't respect timezone?

### ISSUE THREAD

**Issue by Cellard** [laravel/framework#47300]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

MySQL 8.0.31 for macOS 13.0 on arm64 (Homebrew)

### Description

While saving `datetime` attribute, framework casts it with `Y-m-d H:i:s` format (preparing date for saving to database) and loses timezone information if it present.

### Steps To Reproduce

Create any model class (even without database table) and make such test:

```php
class DatetimeCastingTest extends \Tests\TestCase
{
    public function testDateTimeWithTZ()
    {
        $event = new Event();

        $str = '2023-05-12T15:00:00Z';
        $event->updated_at = $str;
        $this->assertTrue($event->updated_at->eq(Carbon::parse($str)));

        $str = '2023-05-12T15:00:00+07:00';
        $event->updated_at = $str;
        $this->assertTrue($event->updated_at->eq(Carbon::parse($str)));

        $dt = Carbon::parse('2023-05-12T15:00:00Z');
        $event->updated_at = $dt;
        $this->assertTrue($event->updated_at->eq($dt));

        $dt = Carbon::parse('2023-05-12T15:00:00+07:00');
        $event->updated_at = $dt;
        $this->assertTrue($event->updated_at->eq($dt));
    }
}
```

Every assertion fails.

**Comment by driesvints** [comment]
Please see many issues about this in the issue tracker.
