### ISSUE TITLE
Cannot auto-register commands in non-default namespace with multiple namespaces

### ISSUE THREAD

**Issue by CalebDW** [laravel/framework#47312]
### Laravel Version

9.52.7

### PHP Version

8.1.10

### Database Driver & Version

Postgres 14

### Description

Hello!

The `App\Console\Kernel::console()` does not register commands that are outside of the default namespace---this is due to a bug in the class name parsing algorithm which assumes commands are always in the `App` namespace and produces a 'class' that looks like:
```
"App\<namespace_path>\Support\Commands\EventReminders"
```

This can be fixed by replacing the logic in `Kernel::load()`:
https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Foundation/Console/Kernel.php#L337-L341
with the logic from `DiscoverEvents::classFromFile()`:
https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Foundation/Events/DiscoverEvents.php#L88-L97
which the `EventServiceProvider` uses to auto-register listeners (and does work with listeners in non-default namespaces).

Thanks!

### Steps To Reproduce

1. Register 2 different namespace in application
2. Place command in non-default namespace
3. Attempt to auto-register command in Kernel

**Comment by joelbutcher** [comment]
You can create a service provider for that namespace and register the commands within that

```php
<?php

namespace CustomNamespace

use Illuminate\Support\ServiceProvider;

class CustomNamespaceServiceProvider extends ServiceProvider
{
    /**
     * The commands to be registered.
     *
     * @var array
     */
    protected $commands = [
        FooCommand::class,
    ];

    /**
     * Register the service provider.
     */
    public function register(): void
    {
        $this->commands(array_values($commands));
    }
}
```

Then just add the service provider to your projects `./config/app.php` file, inside the `providers` array:

```php
    'providers' => [
        // ...

        \CustomNamespace\ CustomNamespaceServiceProvider::class,

        // ...
    ]
```

**Comment by joelbutcher** [comment]
@CalebDW the only real way to know if it will be accepted is to submit a pull request and find out

**Comment by driesvints** [comment]
This isn't supported sorry. We expect commands to be in the App namespace.
