### ISSUE TITLE
Override request header in Http Client

### ISSUE THREAD

**Issue by DJafari** [laravel/framework#47313]
### Laravel Version

10.12.0

### PHP Version

8.2.6

### Description

in some case if i want change request header, caused dupplicated and only first value passed

check reproduced code and result

### Steps To Reproduce

```php
$request = Http::withHeaders([
    'X' => 'AAA'
]);
$request->withHeaders([
    'X' => 'BBB'
]);
dd($request->getOptions());
```

Result :
```
array:4 [▼ // routes/web.php:28
  "connect_timeout" => 10
  "http_errors" => false
  "timeout" => 30
  "headers" => array:1 [▼
    "X" => array:2 [▼
      0 => "AAA"
      1 => "BBB"
    ]
  ]
]
```

**Comment by joelbutcher** [comment]
@DJafari this is resolved if you use arrays:

```php
request = Http::withHeaders([
    'X' => ['AAA']
]);
$request->withHeaders([
    'X' => ['BBB']
]);

dd($request->getOptions());
```

```shell
array:4 [▼ // routes/web.php:28
  "connect_timeout" => 10
  "http_errors" => false
  "timeout" => 30
  "headers" => array:1 [▼
    "X" => array:2 [▼
      0 => "BBB"
    ]
  ]
]
```

**Comment by DJafari** [comment]
@joelbutcher No, for me the output is still the same.

**Comment by timacdonald** [comment]
Going to close this, as this is a feature request rather than a bug. Both the first and second values for a header are passed, which the spec supports. The consuming client would need to decide how to handle things.

The following app:

```php
Route::get('/', function () {
    return Http::withHeaders([
        'X-Foo' => 'first',
    ])->withHeaders([
        'X-Foo' => 'second',
    ])->get(url('/dump-headers'))->body();
});

Route::get('/dump-headers', fn () => request()->headers);
```

Correctly merges and sends both headers. This is the browser output from that application.

```
Content-Length: 
Content-Type:   
Host:           play.test
User-Agent:     GuzzleHttp/7
X-Foo:          first, second
```

**Comment by timacdonald** [comment]
To replace a header, you may call the `header` function...

```php
Http::withHeaders(['foo' => '1'])
   ->header('foo', '2') // 'foo' is now '2'
   ->post(/* ... */);
```

**Comment by DJafari** [comment]
@timacdonald 
```
Method Illuminate\Http\Client\PendingRequest::header does not exist.
```

so if sending array values is valid, telescope only log first value and and it has bugs

**Comment by timacdonald** [comment]
@DJafari see https://github.com/laravel/framework/pull/47335

**Comment by timacdonald** [comment]
See also https://github.com/laravel/telescope/pull/1355

**Comment by DJafari** [comment]
@timacdonald thanks!
