### ISSUE TITLE
Running Query PostgreSQL via Controller & Nginx fails

### ISSUE THREAD

**Issue by CrazyICT** [laravel/framework#47319]
### Laravel Version

10.12.0

### PHP Version

8.1.19 

### Database Driver & Version

PostgresQL 14.8

### Description

When dispatching a Job or just running a (raw) query via a Controller (endpoint) the database connection to **pgsql** fails. (eg. its working with mysql like a charm)

We updated from Laravel 9 to 10 and upgraded PHP 8.0 to PHP 8.1

If we're using 'php artisan serve' and access the same endpoint, its working fine.

The error:

```
SQLSTATE[08006] [7] connection to server at "private-db-postgresql-*******.ondigitalocean.com" (****), port 25060 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
connection to server at "private-db-postgresql-******.ondigitalocean.com" (1*****), port 25060 failed: FATAL: no pg_hba.conf entry for host "*****", user "xyz", database "xyz", no encryption (Connection: pgsql, SQL: insert into "jobs" ....

```

Works well when:

1. via Tinker 
2. via artisan serve
3. a Command

### Steps To Reproduce

1. Laravel 10.x project
2. Postgresql server 
3. docker container with Nginx & unit php
4. add a simple (raw) query in the welcome endpoint
5. access the endpoint via the nginx container

```
FROM alpine:3.18
RUN apk add --no-cache php81-bcmath php81-ctype php81-curl php81-dom php81-fileinfo \
      php81-openssl php81-phar php81-session php81-zip \
      php81-simplexml php81-xml php81-xmlwriter php81-xmlreader php81-tokenizer php81-gd php81-pecl-imagick \
      php81-pecl-redis php81-pdo php81-pdo_pgsql php81-pdo_mysql php81-pcntl php81-opcache php81-sockets \
      nginx unit unit-php81 libxml2-dev zip curl php81-intl php81-mbstring php81-iconv php81-sodium git make sqlite php81-pdo_sqlite

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by CrazyICT** [comment]
@driesvints  I doubted whether it is support or a bug, but the so specific problem that only occurs in combination with postgresql. I'm almost convinced it's a bug.

Let's see if others have any ideas about it.
