### ISSUE TITLE
Cache headers when using HEAD HTTP method

### ISSUE THREAD

**Issue by maciek-szn** [laravel/framework#47318]
### Laravel Version

10.12.0

### PHP Version

8.2.4

### Description

**Disclaimer: I've googled this issue, but I haven't found any answers, why it is designed this way.**

I'm trying to design an API. The responses are cacheable - I'm using SetCacheHeaders middleware for this:

```
Route::middleware(['cache.headers:public;max_age=3600;etag'])->group(function () {
    Route::get('/aaa', [Controller::class, 'aaa']);
    Route::get('/bbb', [Controller::class, 'bbb']);
});
```

It works fine when using `GET` HTTP method. However when using `HEAD` method cache headers aren't added.

As I understand when using `HEAD` method the headers in the response should be the same as when using `GET` method - [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD).

In SetCacheHeaders.php there are [these lines](https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Http/Middleware/SetCacheHeaders.php#LL44C2-L44C2):

```
if (! $request->isMethodCacheable() || (! $response->getContent() && ! $response instanceof BinaryFileResponse)) {
    return $response;
}
```

When using `HEAD` method the response body should always by empty, so this conditional is always `true` and cache headers are not added to the response. I'm not sure if it is correct.

Another thing is `ETag` header. It is generated as [md5 of a response body](https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Http/Middleware/SetCacheHeaders.php#LL53C80-L53C80):

```
$options['etag'] = $response->getEtag() ?? md5($response->getContent());
```

While `HEAD` response doesn't contain a body `ETag` can't be computed. Maybe there should be some body simulation to generate a correct `ETag` value?

### Steps To Reproduce

1. Use SetCacheHeaders middleware for your routes like this:
```
Route::middleware(['cache.headers:public;max_age=3600;etag'])->group(function () {
    Route::get('/aaa', [Controller::class, 'aaa']);
    Route::get('/bbb', [Controller::class, 'bbb']);
});
```
2. Access your routes using `GET` HTTP method and then `HEAD` method.
3. Observe the differences in returned HTTP headers.

**Comment by driesvints** [comment]
I feel like the current implementation is correct. When returning from a HEAD request, the body doesn't matter as there shouldn't be any, like you said.

**Comment by maciek-szn** [comment]
I'm not talking about body, but about headers. I know you are trying to close issues as quick as possible, but please read it again.

**Comment by driesvints** [comment]
Hi there, I'm sorry, I misread here. You are indeed correct, this seems to be a bug at first sight.

**Comment by driesvints** [comment]
Actually, reading on this further in https://developer.mozilla.org/en-US/docs/Glossary/Cacheable I don't think HEAD is supposed to work with ETag which seems designed specifically for responses with a body. Therefor, this doesn't applies to HEAD requests in my opinion. So I don't think we'll take any action here sorry.

**Comment by chrillep** [comment]
@maciek-szn to solve the issue you can use https://github.com/365Werk/etagconditionals
