### ISSUE TITLE
Laravel scopeBindings() doesn't ensure API routes are secure

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/framework#47322]
### Laravel Version

10.13.0

### PHP Version

8.1.17

### Database Driver & Version

MySQL 8

### Description

Hi, I'm working on a Laravel 10 project that runs as an API. I have an API resource controller for domains, and I'd like to the show the user their domains linked to their account, my API GET request might look something like `/account/5/domains/1` to show the user id of 5 their domain id of 1. Here's my routes:

```php
Route::middleware(['verified'])->group(function () {
    Route::scopeBindings()->group(function() {
        Route::apiResources([
            'account.domains' => DomainController::class,
            'account.domains.certificates' => CertificateController::class,
            'account.domains.blacklists' => BlacklistController::class,
            'account.domains.dns' => DnsController::class
        ]);
    });
});
```

Now, even if I'm logged in as user ID 5, I can copy the curl command, simply change the request's id 5 to 4 and now I'm still able to see user id 4. Why? This shouldn't be happening with scopeBindings.

Here's my show function:

```php
/**
 * Display the specified resource.
 */
public function show(User $account, Domain $domain, Request $request)
{
    $domain = $domain->load([
        'certificate',
        'blacklist',
        'dns',
        'tags'
    ]);

    return new ApiSuccessResponse($domain);
}
```

I'm using Laravel Sanctum, what I missing to ensure user's can't see others

### Steps To Reproduce

N/A

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
