### ISSUE TITLE
Response typehint problems

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#47323]
### Laravel Version

11.x

### Description

While working on #47317 I noticed that some docblock typehints hint `Illuminate\Http\Response`, but can return `Illuminate\Http\RedirectResponse` as well. I fixed it in one place by replacing hint with the lowest common ancestor (`\Symfony\Component\HttpFoundation\Response`), but I noticed another place where this change wouldn't make much sense:

https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Foundation/Exceptions/Handler.php#L685-L705

It would seem wrong to declare that `toIlluminateResponse` returns a Symfony response, so I decided to bring this up for attention as I'm not sure the best way to proceed here.

Maybe there should be a common interface between Response and RedirectResponse? Or RedirectResponse could just extend Response?

**Comment by driesvints** [comment]
Thank you. I think we can use `\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse` here. Feel free to send in a PR 👍
