### ISSUE TITLE
The helper function 'old()' does not work properly in combination with @checked as in the docs example

### ISSUE THREAD

**Issue by michelterstege81** [laravel/framework#47357]
### Laravel Version

10

### PHP Version

8.2

### Database Driver & Version

MySql 8

### Description

In the docs at https://laravel.com/docs/10.x/blade the following example is given:

`<input type="checkbox"
        name="active"
        value="active"
        @checked(old('active', $user->active)) />`

However when $user->active is true and a user unchecks the checkbox the unchecked value is not preserved when form validation fails.

### Steps To Reproduce

Create a form with at a minimum:

`<input type="checkbox"
        name="active"
        value="active"
        @checked(old('active', $user->active)) />`

as per the docs example: https://laravel.com/docs/10.x/blade

make sure $user->active evaluates to true

submit the form

let validation fail.

Expected result:
The checkbox should be unchecked

Actual result:
The checkbox is checked

**Comment by driesvints** [comment]
I can't reproduce this. If I flash the input to the session store right before rendering the Blade template, the checkbox is unchecked even though the default is `true`:

```php
Route::get('/', function () {
    session()->flashInput(['active' => false]);

    return view('welcome', [
        'user' => (object) [
            'active' => true,
        ],
    ]);
});
```

```blade
<input type="checkbox" name="active" value="active" @checked(old('active', $user->active)) />
```

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by michelterstege81** [comment]
That holds true when you manually put it to the session, however if form validation fails in a FormRequest the checkbox input won't be there when it's not checked and therefore the old() function will fallback to the default.

/resources/views/some-form.blade.php:

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="POST" action="/someform">
            @csrf

            <input type="text" name="something" value="" />

             <input type="checkbox" name="active" value="active" @checked(old('active', true)) />

            <input type="submit>
</form
</body>
</html>`

/app/Http/Requests:

`<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreSomethingRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'something' => 'required',
        ];
    }
}
`

/app/Http/Controllers/SomeController.php

`<?php

namespace App\Http\Controllers;

use App\Http\Requests\SomethingRequest;

class SomeController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreSomethingRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSomethingRequest $request, string $subdomain)
    {
       // Do something when validation does not fail.
    }
}`

Submit the form with an empty text input and uncheck the checkbox. After validation fails the checkbox will be checked again.

**Comment by mi-dave** [comment]
I agree that this is a confusing edge case in `old()`, and perhaps a bug in the documentation. I've found two possible solutions.

First, in the HTML, we can specify a hidden value to use if it is unchecked:

```html
<input type="hidden" name="active" value="" />
<input type="checkbox" name="active" value="active" @checked(old('active', true)) />
```

If it is ticked, both values get submitted, but PHP uses the last one. If it is unticked, PHP uses the hidden (empty) value, and `old('active', true)` returns an empty string.

But that doesn't work for all fields - e.g. arrays of inputs like `name="active[]"` would get merged - so the second approach I've used is to check whether the form has been submitted yet by calling `old()` with no parameters:

```html
<input type="checkbox" name="active" value="active" @checked(old() ? old('active') : true) />
```

I wrapped that up into a helper function:

```php
function old_checked($name, $default = false)
{
    return old() ? old($name, false) : $default;
}
```

And another one for arrays:

```php
function old_array($name, $default = [])
{
    return old() ? old($name, []) : $default;
}
```

This does rely in there being at least one field submitted in the form though, as there's no easy way to tell the difference between nothing being flashed and an empty array being flashed.

Hope that helps someone.

**Comment by couto862** [comment]
> I agree that this is a confusing edge case in `old()`, and perhaps a bug in the documentation. I've found two possible solutions.
> 
> First, in the HTML, we can specify a hidden value to use if it is unchecked:
> 
> ```
> <input type="hidden" name="active" value="" />
> <input type="checkbox" name="active" value="active" @checked(old('active', true)) />
> ```
> 
> If it is ticked, both values get submitted, but PHP uses the last one. If it is unticked, PHP uses the hidden (empty) value, and `old('active', true)` returns an empty string.
> 
> But that doesn't work for all fields - e.g. arrays of inputs like `name="active[]"` would get merged - so the second approach I've used is to check whether the form has been submitted yet by calling `old()` with no parameters:
> 
> ```
> <input type="checkbox" name="active" value="active" @checked(old() ? old('active') : true) />
> ```
> 
> I wrapped that up into a helper function:
> 
> ```
> function old_checked($name, $default = false)
> {
>     return old() ? old($name, false) : $default;
> }
> ```
> 
> And another one for arrays:
> 
> ```
> function old_array($name, $default = [])
> {
>     return old() ? old($name, []) : $default;
> }
> ```
> 
> This does rely in there being at least one field submitted in the form though, as there's no easy way to tell the difference between nothing being flashed and an empty array being flashed.
> 
> Hope that helps someone.

I had this bug. Your explanation helped me a lot. Thank you very much.
