### ISSUE TITLE
DD not collapsing

### ISSUE THREAD

**Issue by tomascordero** [laravel/framework#47359]
### Laravel Version

10.13.2

### PHP Version

8.2.5

### Database Driver & Version

N/A

### Description

When using `dd()` to output an array or object, I am unable to collapse the nested arrays. It looks like there was a fix implemented in symfony https://github.com/symfony/symfony/pull/50493. I think symfony/console needs to be bumped to 6.3

### Steps To Reproduce

1. Define an multi dimensional array
2. `dd` the array
3. Try to close the nested children

**Comment by NickSdot** [comment]
Reported just in time. Spent the last hour or so to find out what's going on. In my case it was always expanded. Updating the var dumper fixed it for me!

**Comment by driesvints** [comment]
Can't you just update your dependencies? It should pull in 6.3

```
composer update -W
```

**Comment by driesvints** [comment]
Actually, that fix doesn't seems tagged yet. We'll have to wait until Symfony releases it.

**Comment by tomascordero** [comment]
Yeah running `composer update -W` doesnt update the package that `laravel\framework` uses. 

I think that fix is in 6.3 right? https://github.com/symfony/symfony/releases/tag/v6.3.0

**Comment by NickSdot** [comment]
@tomascordero, the bug was introduced in 6.3. So, we basically wait for 6.3.1. Just fix it manually until it's released.
