### ISSUE TITLE
Pass slot attributes to nested component is not working

### ISSUE THREAD

**Issue by McTom234** [laravel/framework#47360]
### Laravel Version

9.52.0

### PHP Version

8.2.6

### Description

If you try to pass attributes (e.g. class attribute) from a slot a of a blade component to a nested blade component as "merged" attributes (e.g. class in this case: `{{ $attributes->class() }}`...), the attribute is not rendered in the child component and the component is not treated as component anymore.

On the other hand, if you pass the attributes as normal attributes or "PHP-value-attributes" (`:class=""`...), it is working.

PS: While writing this report, I actually thought about this not being a real bug. But I would be interested in what I could to do pass the attributes (in this case the class attributes) while being able to use AttributeBag's merge functions.

### Steps To Reproduce

# Working
`components/icon.blade.php`:
```blade
<i {{ $attributes->class(['fa-md']) }}></i>
```
`components/parent.blade.php`:
```blade
<x-icon :class="$icon->attributes->get('class')"/>
```
`test.blade.php`:
```blade
<x-parent>
    <x-slot:icon class="fas fa-list"/>
</x-parent>
```
Resulting in:
```html
<i class="fa-md fas fa-list"></i>
```

# Not working
`components/icon.blade.php`:
```blade
<i {{ $attributes->class(['fa-md']) }}></i>
```
`components/parent.blade.php`:
```blade
<x-icon {{ $icon->attributes->class([]) }}/>
```
`test.blade.php`:
```blade
<x-parent>
    <x-slot:icon class="fas fa-list"/>
</x-parent>
```
Resulting in:
```html
<x-icon class="fas fa-list"></i>
```

**Comment by McTom234** [comment]
I just tried the following, which is working.
`components/parent.blade.php`:
```blade
<x-icon {{ $attributes->class([]) }}/>
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by McTom234** [comment]
Hey! Thanks for the reply.
I created a test repo: [https://github.com/McTom234/bug-report/](https://github.com/McTom234/bug-report)

I am having a hard time describing the issue any further. I hope the code gives you more info. Maybe you can have a look and ask any questions you have?

**Comment by McTom234** [comment]
Yeah, your code works. Makes sense to me although it really confused me when I encountered it. Thank you!

**Comment by AJDurant** [comment]
I just came across this same issue, and has taken me a while to find this fix. It would be really helpful if this was mentioned in the docs.

In my case I'm using a button component inside another component and passing through the attributes like this:

```php
<x-button onclick='{{ $id }}.showModal()'
          :attributes="$button->attributes">
    {{ $button }}
</x-button>
```
