### ISSUE TITLE
Console commands aren't loaded #47327

### ISSUE THREAD

**Issue by makroxyz** [laravel/framework#47377]
### Laravel Version

10.13.2

### PHP Version

8.1.17

### Description

after update to laravel 10.13.2 my console commands are not loaded

### Steps To Reproduce

my composer.json
```
"autoload": {
        "psr-4": {
            "App\\": "app/App/",
            "Domain\\": "app/Domain/",
           .....
```
due to PR #47327 now Kernel load is trying to load App\App\Console\Commands\MyCommand.php that is a wrong namespace

MyCommand.php file is in app/App/Console/Commands folder and in the App\Console\Commands namespace

**Comment by kristoffermodified** [comment]
Same issue here on the latest version

**Comment by CalebDW** [comment]
@makroxyz,

What does your `->load()` call look like in `Kernel::commands()`?


The best path forward is to probably use the composer autoload classmap to get the class from the filename instead of  trying to make assumptions when parsing the filename---I can PR a fix

**Comment by makroxyz** [comment]
> @makroxyz,
> 
> What does your `->load()` call look like in `Kernel::commands()`?
It is not modified, default one
> 
> 
> The best path forward is to probably use the composer autoload classmap to get the class from the filename instead of  trying to make assumptions when parsing the filename---I can PR a fix

I think it's the best way to fix. Thanks

**Comment by driesvints** [comment]
We reverted the original PR for now. Thanks
