### ISSUE TITLE
WithoutEvents doesn't work

### ISSUE THREAD

**Issue by cosmastech** [laravel/framework#47391]
### Laravel Version

10.13.1

### PHP Version

8.2.4

### Description

https://github.com/laravel/framework/blob/f9a69333127e4758ba9a1b06aac6b456b15fd9bb/src/Illuminate/Foundation/Testing/WithoutEvents.php#L19

I don't see a method in the Laravel codebase for withoutEvents that would apply to a test case. (There is a static method [Model::withoutEvents()](https://github.com/laravel/framework/blob/f9a69333127e4758ba9a1b06aac6b456b15fd9bb/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php#L399)). I also couldn't find an ApplicationTrait that this was referencing, I'm assuming it's long since been removed.

If this is deprecated, indicating that within the class would be better than nothing. Would love if this trait was updated to disable all events for a test though.

### Steps To Reproduce

Create a test case and employ the WithoutEvents trait.

```php
use Illuminate\Foundation\Testing\TestCase;
use Illuminate\Foundation\Testing\WithoutEvents;

class MyTest extends TestCase
{
    use WithoutEvents;

    public function testTrue()
    {
        $this->assertTrue(true);
    }
}
```

Running this test with phpunit will fail having raised this exception: `Exception: Unable to disable events. ApplicationTrait not used.`

**Comment by GrahamCampbell** [comment]
This is not a bug, but a missing upgrading guide step. Laravel 10 no longer supports using the `WithoutEvents` trait, and it as a mistake that this trait was never removed (though it is removed in Laravel 11 - https://github.com/laravel/framework/pull/47180). You instead need to use `Event::fake()`.

**Comment by driesvints** [comment]
Yeah, we no longer support this trait.
