### ISSUE TITLE
Markdown mail::panel shows RAW HTML

### ISSUE THREAD

**Issue by michaelnabil230** [laravel/framework#47400]
### Laravel Version

10.13.0

### PHP Version

8.2

### Description

When using the `mail::panel` component to display a panel in a Markdown mail template, I noticed that the panel content is rendered as raw HTML in the emails instead of properly formatted. This behavior is unexpected and not in line with the intended usage of the component.

<img width="1359" alt="Screenshot 2023-06-10 at 10 05 06 PM" src="https://github.com/laravel/framework/assets/46572405/575bd7e0-305d-41e2-a983-822e2d70d5b3">

<img width="1728" alt="Screenshot 2023-06-10 at 10 06 35 PM" src="https://github.com/laravel/framework/assets/46572405/54c641b0-512b-44ff-a7e1-a420e05a85de">

### Steps To Reproduce

1. Create a Markdown mail template.
2. Use the `mail::panel` component with some HTML content inside it.
3. Send the email using Laravel's mailing functionality.
4. Check the received email, and you'll see that the panel content is displayed as raw HTML code instead of being formatted as a panel.

**Comment by msucevan** [comment]
Do not use tabs or blank spaces in the initial line, this will solve the problem.

**Comment by michaelnabil230** [comment]
‏I did the steps they said and it actually worked

**Comment by michaelnabil230** [comment]
@msucevan ‏I did the steps they said and it actually worked
Thanks 🙏

**Comment by claide** [comment]
Same issue I am encountering, my template dont have additional indentations but still i can see html codes. here's a sample markdown.

```
<x-mail::message>
# Login Verification

We received a request to log in to your account. Use the code below to complete the login.

<x-mail::panel>**{{ $code }}**</x-mail::panel>

**The verification code is valid for 15 minutes.** Enter the code
<a href="{{ $url }}">here</a> to verify your login.

<x-mail::subcopy>
If you did not make this request, please disregard this email. Your account remains safe and no changes have
been made.
</x-mail::subcopy>

</x-mail::message>
```
