### ISSUE TITLE
Model observers not firing via seeders

### ISSUE THREAD

**Issue by jdion84** [laravel/framework#47416]
### Laravel Version

^10.8

### PHP Version

8.2.4

### Database Driver & Version

8.0.32

### Description

My model observers are not firing when seeding the database.

In my user model, I have the following method:

```php
    protected static function booted()
    {
        Log::info('booted');

        static::creating(function (User $user) {
            Log::info('creating');
        });
    }
```

Here is my database seeder code:

```php
        \App\Models\User::factory()->create([
            'name' => 'joe',
            'email' => 'joe@example.com',
        ]);
```

After I run the seeder, all I see is `booted` in the log. I do not see `creating`.

I just recently ran composer update. Was something new added that might be causing this?

### Steps To Reproduce

See description.

**Comment by n8udd** [comment]
Have you added the `User` model and the `UserObserver` classes to the `App\Providers\EventServiceProvider`?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
