### ISSUE TITLE
Multi database test suite

### ISSUE THREAD

**Issue by Guilhem-DELAITRE** [laravel/framework#47428]
### Laravel Version

10.x

### PHP Version

8.1.x

### Description

I do not understand why in the checks that are done on multiple database system by github, the test suite being tested is only tests/Integration/Database, and for example why is tests/Database not included in those.

This caused (with the help of an error on my part of course) the problems described in https://github.com/laravel/framework/pull/46309 subsequently to its merge.

### Steps To Reproduce

Create a PR, only some subset of databases tests are executed on multiple databases

**Comment by driesvints** [comment]
Thanks but this doesn't seems like a bug report. Feel free to send in a PR if you want to change something to the test suite.
