### ISSUE TITLE
I can still access the `users/create` url when I use `only(['store', 'index', 'show', 'destroy'])`

### ISSUE THREAD

**Issue by hareom284** [laravel/framework#47435]
### Laravel Version

9.52.7

### PHP Version

8.1.0

### Description

- I used the `only()` Route's function where I want to use only `store`, `index`, `show` and `destroy` routs methods   <br> ```Route::resource('users', UserController::class)->only(['store', 'index', 'show', 'destroy'])``` 
- I have checked which route is available It is shown below 
![image](https://github.com/laravel/framework/assets/64596861/4b46bf97-c813-4314-915a-8b8ec7ae6254)

My problem I can still access the `users/create` url as below
![image](https://github.com/laravel/framework/assets/64596861/d0a26f8b-2eda-4c7e-a8dd-0985cf890835)

### Steps To Reproduce

My problem I can still access the `users/create` url as below
![image](https://github.com/laravel/framework/assets/64596861/d0a26f8b-2eda-4c7e-a8dd-0985cf890835)

**Comment by n8udd** [comment]
Is this not just accessing your show method and using "create" as the parameter, which presumably is then failing to correctly find the model?

**Comment by msucevan** [comment]
You are accessing the GET route "users/{id}" where the parameter is $create and you receive a error because route show is not implemented, that's my guess

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
