### ISSUE TITLE
When I change the default connection with other connection with the same values the transaction is blocked.

### ISSUE THREAD

**Issue by jubag-93** [laravel/framework#47439]
### Laravel Version

9.2

### PHP Version

8.0.2

### Database Driver & Version

pdo_sqlsrv-5.10.0beta2 on Ubuntu 20.04 

### Description

When I have two or more connections configured on database.php when I change the default connection with other with the same values and set a transaction, this broke and block the database engine

### Steps To Reproduce

*Create two or more database connection, one of all connections need same equal like the default connection set on DB_CONNECTION environtment value.
*Run a transaction like 
`DB::connection('same connection that default')->transaction(function(){
 run insert or update to database
});`

The transacction don't finish.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jubag-93** [comment]
@driesvints this is a bug, because I post it.
