### ISSUE TITLE
db update failed,but save() method return true

### ISSUE THREAD

**Issue by miaotiao** [laravel/framework#47447]
### Laravel Version

10.13.5

### PHP Version

8.1.18

### Database Driver & Version

MySQL 5.7.22 for centos 7.8 on x86

### Description

![image](https://github.com/laravel/framework/assets/28383349/9860c1a9-5c55-4c69-ad4a-c68531ce35d8)

`$res` is true , but this sql run error. 

![image](https://github.com/laravel/framework/assets/28383349/681d29c4-83fd-4db9-9119-ea0e9b514e8a)

So : 
Although this SQL statement executed an error, the `save` method of the `model` returned `true` and no exception was thrown

### Steps To Reproduce

mysql table structure : 

![image](https://github.com/laravel/framework/assets/28383349/44a37455-b5f1-4faf-87d1-9a1bf368a2cd)

**Comment by msucevan** [comment]
`TINYINT` accept value between 0 and 255, so 3+5000 is out of range.
