### ISSUE TITLE
whereBelongsTo does not work with morphTo relationship unless ownerKey is specified explicitely

### ISSUE THREAD

**Issue by Azelen** [laravel/framework#47458]
### Laravel Version

10.13.5

### PHP Version

8.1.11

### Database Driver & Version

MySQL 8.0.31

### Description

Hello.

I have a Comment model and a couple other models (Task, Document, etc) that Comments can belong to using a polymorphic relationship. When I am trying to do Comment::whereBelongsTo($model, 'commentable') query method I get `InvalidArgumentException` with the following message: `Nested arrays may not be passed to whereIn method.` .

After some debugging I've found out that I need to excplicitely specify `ownerKey` in the morphTo() relationship of the Comment model, otherwise it's never resolved and stays null.

### Steps To Reproduce

1. I have a Comment model with the following relationship:
```
    public function commentable(): MorphTo
    {
        return $this->morphTo();
    }
```
2. Next I have a "commentable" model (Task, Document, etc),
3. Then I have the following code in one of my controllers
```
    public function show(Task $task)
    {
        // ...

        // This is a simplified example to demonstrate the problem, I know there are more elegant ways to do this ;)

        $comments = Comment::whereBelongsTo($task, 'commentable')->get();

        // ...
    }
```
4. An `InvalidArgumentException` exception is thrown with the following message: `Nested arrays may not be passed to whereIn method.`

I have spent some time debugging this and it led me to this piece of code in the `\Illuminate\Database\Eloquent\Concerns\QueriesRelationships` trait's `whereBelongsTo` method

```
        $this->whereIn(
            $relationship->getQualifiedForeignKeyName(),
            $relatedCollection->pluck($relationship->getOwnerKeyName())->toArray(),
            $boolean,
        );
```

the `$relationship->getOwnerKeyName()` returns `null` at this point, unless I explicitely provide `ownerKey` in the `commentable` relationship of the Comment model like this:

```
    public function commentable(): MorphTo
    {
        return $this->morphTo(ownerKey: 'id');
    }
```

While this solution works, I believe this should not be necessary. Additionally, different commentable models may have different key names. So alternative solution would be to fetch ownerKey name from the related model like this:

```
        $this->whereIn(
            $relationship->getQualifiedForeignKeyName(),
            $relatedCollection->pluck($relationship->getOwnerKeyName() ?? $related->getKeyName())->toArray(),
            $boolean,
        );
```

but I don't know the code good enough to know if this is a correct solution.

Thank you in advance and sorry if something is missing it is my first time submitting a bug report.

**Comment by Azelen** [comment]
Ok, I have just realized that I cannot use `whereBelongsTo` with a `MorphTo` relationship because it never checks the `commentable_type`, only `commentable_id`. I am not sure if there's a bug with regular `BelongsTo` relationship in this case, so maybe this is irrelevant.

**Comment by driesvints** [comment]
Thank you for investigating this but this indeeds seems unsupported.
