### ISSUE TITLE
Casting a model attribute to an enum does not prevent assigning the attribute to a different enum

### ISSUE THREAD

**Issue by PHLAK** [laravel/framework#47454]
### Laravel Version

10.13.5

### PHP Version

8.2.7

### Database Driver & Version

N/A

### Description

Casting a model attribute to an enum _does not_ prevent assigning the attribute to a different enum or a value not defined as a case on the enum.

For example, if an attribute is cast to `SomeEnum` you can freely set/update the value of that attribute to `AnotherEnum::WHATEVER` or any primitive value. In this event, if the backed value of `AnotherEnum::WHATEVER` or the primitive value matches a case on `SomeEnum` when we retrieve the model from the DB we will get an instance of `SomeEnum` back (fine, but unexpected). However, if the backed value of `AnotherEnum::WHATEVER` or the primitive value _does not_ match a case on `SomeEnum` we will get a `ValueError` on retrieval of the model since it can't create the `SomeEnum` from the value stored in the DB (i.e. `SomeEnum::from($value)`).

I believe the intent to allow setting an (uncast) attribute to an enum is at least somewhat intentional. However, **when the attribute is cast to a specific enum and attempting to assigning it to a _different_ enum or a string that is _not_ defined as a case on the enum should result in a error**. This would proactively avoid storing an incorrect value in the DB, prevent the `ValueError` on retrieval and preserve the benefits of using enums in the first place.

If this sounds like a reasonable change I can create a PR for this. Let me know what you think.

**NOTE:** For your reference and mine [here](https://github.com/laravel/framework/blob/ea5172eb59d4ecd87379591c2a2e34c96ca7d068/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1166-L1191) is the code that sets and gets the value for an attribute cast to an enum.

### Steps To Reproduce

Create some enums.

```php
namespace App\Models\Enums;

enum SomeEnum: string
{
    case FOO = 'foo';
    case BAR = 'bar';
}
``` 

```php
namespace App\Models\Enums;

enum AnotherEnum: string
{
    case BAR = 'bar';
    case BAZ = 'baz';
}
```

Create a Model with an attribute cast to one of the enums.

```php
namespace App\Models;

use App\Models\Enums\SomeEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Example extends Model
{
    use HasFactory;

    protected $casts = [
        'some_enum' => SomeEnum::class,
    ];
}
```

Set the attribute to the incorrect enum value.

```php
> $example = Example::factory()->makeOne(['some_enum' => SomeEnum::FOO])
= App\Models\Example {#6992
    some_enum: "foo",
  }

> $example->some_enum
= App\Models\Enums\SomeEnum {#6239
    +name: "FOO",
    +value: "foo",
  }

> $example->some_enum = AnotherEnum::BAR
= App\Models\Enums\AnotherEnum {#6243
    +name: "BAR",
    +value: "bar",
  }

> $example->some_enum
= App\Models\Enums\SomeEnum {#6238
    +name: "BAR",
    +value: "bar",
  }

> $example->some_enum = AnotherEnum::BAZ
= App\Models\Enums\AnotherEnum {#6211
    +name: "BAZ",
    +value: "baz",
  }

> $example->some_enum

   ValueError  "baz" is not a valid backing value for enum App\Models\Enums\SomeEnum.
```

**Comment by driesvints** [comment]
Hi @PHLAK. Thanks for the detailed report. This indeed seems problematic to me. I think we should also throw a ValueError when you try to assign an incorrect enum. Could you send in a PR? Thanks!
