### ISSUE TITLE
[10.x] Trying to use a named route within route file no longer works as before

### ISSUE THREAD

**Issue by GC-Mark** [laravel/framework#47451]
### Laravel Version

v10.13.5

### PHP Version

8.2.6

### Description

During our upgrade from Laravel 9 to Laravel 10 today, we have hit an issue where it seems we can no longer reference a route by name, within the route definition file.

### Steps To Reproduce

1. Install a fresh installation of Laravel
2. Open `web.php`
3. Paste the following code into there
```php
Route::get('/', function () {
    return view('welcome');
})->name('test.index');

Route::permanentRedirect('advice', route('test.index'));
```
4. Run any artisan command, e.g. `php artisan route:list` and see the following exception...

```
Symfony\Component\Routing\Exception\RouteNotFoundException 

  Route [test.index] not defined.

  at vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:467
    463▕         if (! is_null($route = $this->routes->getByName($name))) {
    464▕             return $this->toRoute($route, $parameters, $absolute);
    465▕         }
    466▕ 
  ➜ 467▕         throw new RouteNotFoundException("Route [{$name}] not defined.");
    468▕     }
    469▕ 
    470▕     /**
    471▕      * Get the URL for a given route instance.

      +1 vendor frames 
  2   routes/web.php:20
      +4 vendor frames 

  7   app/Providers/RouteServiceProvider.php:37
      Illuminate\Routing\RouteRegistrar::group("/Users/xxx/Sites/base-install/routes/web.php")
```

If we add `->refreshNameLookups()` in the `getByName()` method within `\Illuminate\Routing\RouteCollection` class, the error disappears.

It seems somehow that the `RouteCollection` is not being updated properly for some reason.

This might be a related issue #46834

**Comment by driesvints** [comment]
Hi there. I'm sorry you ran into this. However, I don't think we ever advertised or documented this behavior. I don't think we can consider this valid usage, sorry. It's not intended to resolve routes within the routes file.

**Comment by GC-Mark** [comment]
Any idea what changed? Had a look through the PRs, but couldn't see anything related :/
