### ISSUE TITLE
LengthAwarePaginator toArray() returns objects after json_encode()

### ISSUE THREAD

**Issue by camohub** [laravel/framework#47486]
### Laravel Version

8.1

### PHP Version

8.19

### Description

I have a collection which is called via Ajax but as I see LengthAwarePaginator toArray() returns object instead of array. The problem is in toArray() method which is called while json serialization and this method returns object with numeric keys instead of array. 

### Steps To Reproduce

As I found out the solution could be simple add array_values in toArray() method:

	public function toArray()
	{
		return [
			'current_page' => $this->currentPage(),
			'data' => array_values($this->items->toArray()),  // This is the problem. I added array_values()
			'first_page_url' => $this->url(1),
			'from' => $this->firstItem(),
			'last_page' => $this->lastPage(),
			'last_page_url' => $this->url($this->lastPage()),
			'links' => $this->linkCollection()->toArray(),
			'next_page_url' => $this->nextPageUrl(),
			'path' => $this->path(),
			'per_page' => $this->perPage(),
			'prev_page_url' => $this->previousPageUrl(),
			'to' => $this->lastItem(),
			'total' => $this->total(),
		];
	}

I dont know if it can not cause another problem, but I think it should not cause paginated collection is alway array not object. 
What you think about it?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by camohub** [comment]
:(
