### ISSUE TITLE
Blade Rendering Issue with @disabled(true) on Blade Components

### ISSUE THREAD

**Issue by comes** [laravel/framework#47485]
### Laravel Version

10.13.5

### PHP Version

8.2.7

### Database Driver & Version

-

### Description

Hej,

I found a bug within the blade rendering.

Whenever I like to use `@disabled(true)` on a blade component, the component will not be rendered correctly.

for example:
```blade
<x-input @disabled(true) />
```

**Expected**
```html
<input disabled />
```

**Actual**
```html
<x-input disabled />
```

I've added a repository to demonstrate the issue, including the component code and the blade file.

### Steps To Reproduce

You can reproduce the issue by running this repo:
https://github.com/comes/bug-report

Start `php artisan serve` and open the welcome page.

**Comment by driesvints** [comment]
Please see https://laravel.com/docs/10.x/blade#component-attributes

<img width="702" alt="Screenshot 2023-06-19 at 11 09 18" src="https://github.com/laravel/framework/assets/594614/fe6a2e51-0a69-4bc8-87f0-f6ccc6f0f14c">

**Comment by comes** [comment]
sad, but ok. any plans to make this possible?
