### ISSUE TITLE
Slow whereRaw

### ISSUE THREAD

**Issue by t3946** [laravel/framework#47505]
### Laravel Version

8.75

### PHP Version

7.4

### Description

I'm working with "laravel/framework 8.75" and found slow page load problem that cause by whereRaw.
```PHP
        $query1 = DB::table("modx_1_prodazha")
            ->selectRaw("COUNT(*) as cnt_lots")
            ->selectRaw("SUM(price) as price")
            //1: fast
//            ->where('dolg_inn', '=', $this->inn)
            //2: fast
//            ->whereRaw("dolg_inn = ?", $this->inn)
            //3: fast
//            ->whereRaw("dolg_inn = ?", [$this->inn])
            //4: fast
//            ->whereRaw("dolg_inn = ?", [ROUND(6713007120)])
            //5: slow
//            ->whereRaw("dolg_inn = " . 6713007120)
            //6: slow
//            ->whereRaw("dolg_inn = " . 'ROUND(6713007120)')
            //7: slow
            ->whereRaw("dolg_inn = ROUND(6713007120)", [])
        ;

        return $query1->first();
```

All "fast" means page will loaded in 2 sec. and "slow" in 12 sec. My database is Mysql ^8.0

### Steps To Reproduce

Use one of "slow" variants.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by t3946** [comment]
No I can't upgrade my php and thereby laravel version.
