### ISSUE TITLE
Blade: Syntax error, unexpected token ")" when using Null-Coalescing-Operator for array

### ISSUE THREAD

**Issue by Restingo** [laravel/framework#47503]
### Laravel Version

9.52.7

### PHP Version

8.1.13

### Description

When using the following code in a blade file Laravel throws an `Syntax error, unexpected token ")"` error:

`{{ $time->meta?['ticket']['number'] }}`

Code gets cached to the following:

`<?php echo e($time->meta?['ticket']['number']); ?>`

### Steps To Reproduce

Create a blade file with the following content, then browse to it:

`{{ $time->meta?['ticket']['number'] }}`

**Comment by driesvints** [comment]
You can't use the null coalescing operator like that: https://3v4l.org/fElYb
