### ISSUE TITLE
Queues not processing MSSQL database jobs with PHP on Mac

### ISSUE THREAD

**Issue by bebo925** [laravel/framework#47510]
### Laravel Version

10.13.5

### PHP Version

8.2.5

### Database Driver & Version

SQLSRV - MSSQL 2019

### Description

Using Mac Ventura with php installed by Homebrew, when I run `php artisan queue:work` using the database driver on a MSSQL connection, jobs in the database are never processed.  Also, no errors are logged to CLI, only storage/logs/laravel/log:

 `$databaseVersion =$this->database->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION)`  logs the error:

> "SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute {"exception":"[object] (PDOException(code: IM001): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute at ... vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php:263)"

I am assuming the driver doesn't support with the PHP supplied (driver works with same code with MYSQL connection AND in production with a Forge provisioned server).  I tried supplying ./config/database.php with a version number but it kept squawking "Invalid Version" when I placed the key/value at the root of the config, ie` config('database.connections.sqlsrv.version')`.  I feel like the version key should belong in the options array, ie `config('database.connections.sqlsrv.options.version')`.

Possible solution:  
`$databaseVersion = $this->database->getConfig('options.version') ?? $this->database->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION);`

### Steps To Reproduce

Using Mac Ventura with php installed by Homebrew, when I run `php artisan queue:work` using the database driver on a MSSQL connection, jobs in the database are never processed.  No errors are logged to CLI; they are only logged in storage/logs/laravel.log.

**Comment by driesvints** [comment]
Thanks. You've sent in a PR so let's see how it goes.
