### ISSUE TITLE
SES v2 Transport - ReplyTo address incorrectly configured

### ISSUE THREAD

**Issue by ArthurGuy** [laravel/framework#47512]
### Laravel Version

9.52.9 - All versions will be impacted

### PHP Version

8.0

### Description

SESv2 mail transport is incorrectly configuring the reply to address to be the email from address.
This seems to have come about as the SES v2 API method that's now being used is called `sendEmail` and I suspect when this new transport was created a number of items were copied over from the original transport class without updating them.

This is affecting all Versions of Laravel and anyone using the SES v2 transport.

### Steps To Reproduce

Create and send an email via the ses-v2 transport.
The received email will have the optional reply-to address set to the sender address.

If a reply-to the address has been specified it will be ignored.

**Comment by driesvints** [comment]
@ArthurGuy but the method never changed? It was always `sendEmail` from the start? See https://github.com/laravel/framework/pull/45977/files#diff-29d25548df61d32037ab7810dfd1004a3b26d1b3760b7c96278de4688598bf12R60

Ping @jacobmllr95

**Comment by ArthurGuy** [comment]
@driesvints Yep, I am pretty certain the v2 transport has always been a bit broken.

sendRawEmail is the method used in the original ses transport.

**Comment by driesvints** [comment]
Weird because we have not gotten any reports about this so far and it's live since 4 months already. Will see what @jacobmllr95 says.

**Comment by ArthurGuy** [comment]
I don't think the ses-v2 transport is documented anywhere so I doubt many people are using it, coupled with not many people using the ReplyTo functionality there probably aren't many people doing this.

**Comment by jacobmllr95** [comment]
@ArthurGuy You are totally right, the "reply to" addresses handling was completely broken with the SES v2 transport.
We haven't used "reply to" addresses, so I didn't noticed.

I created a PR to fix this.

**Comment by driesvints** [comment]
Thanks @jacobmllr95

**Comment by ankurk91** [comment]
v2 must be default in Laravel 11

**Comment by jacobmllr95** [comment]
@ankurk91 See: https://github.com/laravel/laravel/pull/6205

**Comment by driesvints** [comment]
This is fixed now.
