### ISSUE TITLE
jsonSerialize skiped on related models

### ISSUE THREAD

**Issue by puggan** [laravel/framework#47545]
### Laravel Version

9.30.1

### PHP Version

8.2.5

### Description

# Senario
When running `json_encode($model)` on a model with an HasMany relation, 
we end up running the following methods (trace):

* Model->jsonSerialize https://github.com/laravel/framework/blob/973b54ed201cdf1ec820699831e39189327ae17e/src/Illuminate/Database/Eloquent/Model.php#L1665

* Model->toArray https://github.com/laravel/framework/blob/973b54ed201cdf1ec820699831e39189327ae17e/src/Illuminate/Database/Eloquent/Model.php#L1636

* Model/HasAttributes->relationsToArray https://github.com/laravel/framework/blob/973b54ed201cdf1ec820699831e39189327ae17e/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L354

* Collection/EnumeratesValues->toArray https://github.com/laravel/framework/blob/973b54ed201cdf1ec820699831e39189327ae17e/src/Illuminate/Collections/Traits/EnumeratesValues.php#L865

* Model->toArray

When we reach the 2nd model, the code goes directly to the toArray method.

# Problem
the modifications added in jsonSerialize on that related model is never applied.

# Sugestions

```
    public function jsonSerialize(): array
    {
        return array_merge($this->attributesToArray(), $this->getArrayableRelations());
    }
```

### Steps To Reproduce

```
Class A extends Model
{
   public function jsonSerialize(): array
   {
       return ['type' => A] + $this->attributesToArray();
   }
}

Class B extends Model
{
    public function children(): HasMany
    {
        return $this->hasMany(A::class);
    }
}

echo json_encode(B::first());
```

**Comment by driesvints** [comment]
In your example you're overwriting `jsonSerialize`. I don't think we can consider that as reasonable use case.
