### ISSUE TITLE
Castable interface doesn't work on enums

### ISSUE THREAD

**Issue by jbnv** [laravel/framework#47547]
### Laravel Version

10.0

### PHP Version

8.1

### Description

My apologies if this issue has already been raised. The interface `\Illuminate\Contracts\Database\Eloquent\Castable` is useless on an enum because the framework performs enum resolution before class resolution.

### Steps To Reproduce

```
require __DIR__ . '/vendor/autoload.php';

$app = new \Illuminate\Foundation\Application(\dirname(__DIR__));

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

enum TestEnum implements \Illuminate\Contracts\Database\Eloquent\Castable
{
    case TestCase;
    public static function castUsing(array $arguments)
    {
        return new class() implements CastsAttributes
        {
            public function get($model, string $key, $value, array $attributes)
            {
                if (blank($value)) return TestEnum::TestCase;
                assert(is_string($value));
                return \constant(TestEnum::class . '::' . $value);
            }
        };
    }
}

class TestModel extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'test_enum' => TestEnum::class,
    ];
}

$model = new TestModel;
$model->test_enum = '';
echo $model->test_enum->name;
exit;
```
The output should be `TestCase`. Instead, the output is this stack dump:

```
PHP Fatal error:  Uncaught Error: Undefined constant TestEnum:: in /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1177
Stack trace:
#0 /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1177): constant()
#1 /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1161): Illuminate\Database\Eloquent\Model->getEnumCaseFromValue()
#2 /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(966): Illuminate\Database\Eloquent\Model->setEnumCastableAttribute()
#3 /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2239): Illuminate\Database\Eloquent\Model->setAttribute()
#4 /home/me/test.php(33): Illuminate\Database\Eloquent\Model->__set()
#5 {main}
  thrown in /home/me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 1177
```

The function that throws the exception is `constant($enumClass.'::'.$value);` because there is no constant named (empty string) in the enum. But the point of implementing `Castable` is to catch this particular case.

**Comment by CalebDW** [comment]
Why does an Enum need to implement castable? Backed Enums are already castable:

```php

require __DIR__ . '/vendor/autoload.php';

$app = new \Illuminate\Foundation\Application(\dirname(__DIR__));

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

enum TestEnum: int
{
    case TestCase = 1;
}

class TestModel extends \Illuminate\Database\Eloquent\Model
{
    protected $casts = [
        'test_enum' => TestEnum::class,
    ];
}

$model = new TestModel;
$model->test_enum = 1;
echo $model->test_enum->name;
exit;
```

**Comment by henzeb** [comment]
And I believe even unit enums these days, not sure. But you can use https://packagist.org/packages/henzeb/enumhancer if not.

**Comment by jbnv** [comment]
@CalebDW The use case here is to prevent a crash when the value is missing or not in the enumeration. See what happens when you replace `$model->test_enum = 1;` with `$model->test_enum = '';`. Or remove that statement entirely.

**Comment by CalebDW** [comment]
That seems like a bad use case for an Enum...

You can always just assign the enum case to the attribute:
1. make column nullable
2. use `::tryFrom`
3. when using the enum, just provide a default value if null
```php
$model->test_enum = TestEnum::tryFrom($value);
echo $model->test_enum->name ?? 'Default Value';
```

**Comment by jbnv** [comment]
1) Why is is a bad use case? Your reply literally shows an example of a workaround for that use case. 

1a) An extension of the use case of blank values is working with inconsistent legacy data. The cast could take care of converting bad data into legitimate data values as defined by the enumeration.

2) You're forgetting what happens when you try to access `test_enum` and assuming there's an explicit assignment somewhere. Again, see what happens with `$model = new TestModel;` $model->test_enum->name;`.

3) The whole point of the casting infrastructure is to, paraphrasing the [documentation](https://laravel.com/docs/10.x/eloquent-mutators#attribute-casting), provide a convenient method of converting attributes to common data types. Imagine that this particular property is mutated several different places in a project. You're talking about applying that cast and null check *everywhere* the attribute is mutated. The point of the Castable interface is to define the casting method in the cast class itself and have Laravel take care of casting it automatically. 

4) The documentation doesn't give any indication that this usage of Castable isn't allowed. So it's technically a bug. But even if this is design, I'd like to know why. PHP allows enums to implement interfaces. The only reason this is a bug in Laravel is because Laravel checks for an enum cast before checking for a class/interface cast. That should be an easy fix.

**Comment by CalebDW** [comment]
I wouldn't call this a bug, just an unintended use case, I'm pretty sure class casters have been around a lot long than PHP Enums.

Another option is you could create a *class* caster that just casts the value to the enum or returns a default if one doesn't exist

**Comment by CalebDW** [comment]
@jbnv,

After thinking about it, a mutator is probably the best option (a mutator takes precedence over casts):

```php
    /** @return Attribute<TestEnum, never> */
    protected function testEnum(): Attribute
    {
        return Attribute::get(function (string $value): TestEnum {
                if (blank($value)) return TestEnum::TestCase;
                assert(is_string($value));
                return \constant(TestEnum::class . '::' . $value);
        });
    }
```

**Comment by jbnv** [comment]
@CalebDW Yes you can. You could even extend the Attribute class and have the model attribute extend a new instance of that class. 

1) If you use that enum in multiple models, you have to copy that attribute to every model where you use it. (You can put it in a trait if and only if the attribute has the same name in every model.)

2) Putting the cast in an attribute separates it from the enum itself. As the sole developer of my employer, I want and am expected to structure my code so that if someone else has to work on it, they can easily understand what's going on. Putting the cast in the enum itself fulfills that goal more than creating an attribute.

3) If the Laravel decision makers decide that this is how casts will work, then the documentation needs to reflect it. A developer shouldn't have to dig into Laravel code to understand why his cast isn't working.

**Comment by haltsir** [comment]
I think I have the same issue. I'm casting a backed Enum to a `privacy` property of my model. Inertia returns the value of that property as the value of the enum. I want to use the name of the enum, so I created a `getPrivacyAttribute`. The second I do that, without even putting anything in that method, I get an error `Cannot instantiate enum App\Enums\GroupPrivacy`. I believe it's the same reason as it was originally described in the issue.

The error is thrown in `vendor / laravel / framework / src / Illuminate / Database / Eloquent / Concerns / HasAttributes.php : 1682`.

**Comment by driesvints** [comment]
I don't think `Castable` was intended to be used on enums.

**Comment by jbnv** [comment]
Since you closed this issue as "completed," what action was taken to resolve it?
