### ISSUE TITLE
Model::incrementQuietly() and Model::decrementQuietly() can't be used publicly

### ISSUE THREAD

**Issue by newtonjob** [laravel/framework#47551]
### Laravel Version

10.4.1

### PHP Version

8.2

### Description

`incrementQuietly()` and `decrementQuietly()` can't be used outside the model since they are defined as `protected`.

The following code is currently failing;
```php
$post = Post::first();

$post->incrementQuietly('views'); // Call to undefined method App\Models\Post::incrementQuietly().
```

Is this an intentional behavior?
Made an attempt to fix this here https://github.com/laravel/framework/pull/47480, but no luck.

### Steps To Reproduce

Fetch a new model and attempt to invoke `incrementQuietly`.
```php
$post = Post::first();

$post->incrementQuietly('views'); // Call to undefined method App\Models\Post::incrementQuietly().
```

**Comment by ahmed3mar** [comment]
Fixed:
https://github.com/laravel/framework/commit/42173c82a477ade12c9fc2acd6d586e39c370b45

**Comment by newtonjob** [comment]
Awesome @ahmed3mar thanks.

I'm still curious to learn why Taylor would rather add them to an array check, instead of just making the methods public.

Is there something I'm missing tho?
