### ISSUE TITLE
migration issue: table created without a foreign key  after giving foreign key error 

### ISSUE THREAD

**Issue by rj-eww** [laravel/framework#47570]
### Laravel Version

10.12.0

### PHP Version

8.1.12 

### Database Driver & Version

Server version: 10.4.27-MariaDB

### Description

Issue: SQLSTATE[HY000]: General error: 1005 Can't create table the_service.order_items (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table order_items add constraint order_items_order_id_foreign foreign key (order_id) references orders (id))

Description:
During the execution of a migration in Laravel, an error occurs that prevents the creation of a foreign key constraint between the order_items and orders tables. Instead of throwing an error, the migration continues and creates the order_items table without the expected foreign key relationship. The specific error message received is SQLSTATE[HY000]: General error: 1005 Can't create table the_service.order_items(errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter tableorder_itemsadd constraintorder_items_order_id_foreign foreign key (order_id) references orders (id)).

Expected Result:
The migration process should fail and halt execution when encountering a foreign key constraint error. The error message should be displayed, indicating the issue with the foreign key constraint, and the order_items table should not be created.

Actual Result:
The migration process does not stop despite encountering a foreign key constraint error. Instead, it continues execution and creates the order_items table without the expected foreign key relationship to the orders table. The error message received is SQLSTATE[HY000]: General error: 1005 Can't create table the_service.order_items(errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter tableorder_itemsadd constraintorder_items_order_id_foreign foreign key (order_id) references orders (id)).

Additional Information:
This issue typically occurs when the data type of the foreign key column (order_id) in the order_items table does not match the data type of the referenced column (id) in the orders table. In such cases, MySQL fails to create the foreign key constraint.

### Steps To Reproduce

Steps to Reproduce:

1. Set up a Laravel project with the necessary configurations.
2. Create migration files for the order_items and orders tables**(order table id data type and order_items table foreign key must be different).**
3. Define the schema for both tables in their respective migration files.
4. Include a foreign key constraint in the order_items migration file that references the id column of the orders table.
5. Run the migration command (php artisan migrate) to execute the migrations.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by rj-eww** [comment]
https://github.com/rj-eww/bug-report.git  
check this

**Comment by driesvints** [comment]
```

        Schema::create('subcategories', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedInteger('category_id');
            $table->foreign('category_id')->references('id')->on('categories');
            $table->timestamps();
        });
```

You're trying to set a foreign key on a column that doesn't exists yet. Try splitting this up in a separate create and table function call.
