### ISSUE TITLE
robots.txt / favicon.ico - Call to a member function setTimezone() on null

### ISSUE THREAD

**Issue by ianfortier** [laravel/framework#47591]
### Laravel Version

10.14.0

### PHP Version

8.1.12

### Description

Looks like the new addition in the Http/Kernel is not working with Laravel Vapor.
The setTimezone() method is being called on a null value. This suggests that $this->requestStartedAt is null. 

`$this->requestStartedAt->setTimezone($this->app['config']->get('app.timezone') ?? 'UTC');`

https://github.com/laravel/framework/compare/v10.13.5...v10.14.0#diff-e36bdc4c31d5863d42e9b5322d00d1982187d0239debc74625e1cce2ff7d486aR217-R218

https://flareapp.io/share/yPa2l9K7

### Steps To Reproduce

Laravel 10.14.0
Vapor-core 2.26
Browse to /robots.txt or /favicon.ico

**Comment by ianfortier** [comment]
I'm currently retrying with the latest vapor-core (^2.3)

**Comment by timacdonald** [comment]
Opened a fix to address this: https://github.com/laravel/framework/pull/47596
