### ISSUE TITLE
Mailable with html content inserted to view

### ISSUE THREAD

**Issue by Heddy147** [laravel/framework#47599]
### Laravel Version

10.10

### PHP Version

8.1

### Description

I am using the \Illumiate\Notifications\MailMessage to render a base html mail.
If I use the content method in my custom Mailable class and set the html attribute of the returning content instance the mailable sets the wrong property while ensuring the content.

[\Illuminate\Mail\Mailable:1682](https://github.com/laravel/framework/blob/fff5b0bf6eefccbedfa88405b97435f9eb4e3452/src/Illuminate/Mail/Mailable.php#L1708)

The problem is that the framework wants to render a view not the html and the exception "view not found" is thrown.
If I change this line to
`$this->html($content->html)`
all works fine.

### Steps To Reproduce

- Fresh installation
- create Mailable with "php artisan make:mail MyNewMail"
- use content method and set html with `(new MailMessage())->{...}->render()->toHtml()`
- send mail with `Mail::to('mail')->send(new MyNewMail())`

**Comment by caiowilson** [comment]
A mailable instace has a view related to it, didn't know you could/should render html with its instance (i'm not really up-tp-date with latest laravel versions).
Would making the blade view very costly for your application? it seems you already have the html, i'd be a matter of namespacing and making the views.

**Comment by Heddy147** [comment]
The html is generated by \Illumiate\Notifications\MailMessage
So I don't really have the html.

I should mention that the content method expects an instance of `Illuminate\Mail\Mailables\Content`
The constructor accept a `view` and a `html` parameter. If I pass the view parameter it should render a view.
But if I pass the html parameter it should use the given html.

```php
public function content(): Content
{
    return new Content(
        // view: 'view.name', # can be used for view rendering
        html: '<p>My very good HTML text</p>',
    );
}
```

I pass the html parameter.

For now I can use the `build` method. I want to use the `content` method which is mentioned in the docs of laravel mails.

**Comment by caiowilson** [comment]
Yeah I'm currently using the content but with views as per doc.
Even though it might be a bug and you should be able to pass html, (I'll
try to reproduce it today if I have time) a blade view is quite more
flexible. You should consider it for your use case.
I'll get back to you if I can make it happen here.

**Comment by driesvints** [comment]
`html` needs to be a view. `htmlString` can be a HTML string.

```
    return new Content(
        htmlString: '<p>My very good HTML text</p>',
    );
```

**Comment by Heddy147** [comment]
@driesvints thank you for the explanation.

So `html` AND `view` is for the same thing? Very confusing
