### ISSUE TITLE
Blade Component Attribute Encoding Issue

### ISSUE THREAD

**Issue by chriischambers** [laravel/framework#47605]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

I have ran into an issue where by I am getting a `Parse Error` exception although I am not sure if this is expected behaviour or not. 

Take this HTML/JS code for example - The object action string has had the apostrophe slashed to be valid.  If you put this in a view it works exactly as expected.

```
<div onclick="console.log({ action: 'He\'s going to town' })">click</div>
```

If you apply this same onclick code to a blade component you get the `Parse Error` thrown. 

View : 
```
<x-test onclick="console.log({ action: 'He\'s going to town' })">click</x-test>
```

Component:
```
<div {{ $attributes }}>click</div>
```

A work around I have found is to escape the slash but then this shows errors in the IDE as it's invalid - 

```
<x-test onclick="console.log({ action: 'He\\'s going to town' })">click</x-test>
```

Like i said, i'm not sure if this is by design or not but it does not feel like expected Laravel behaviour.  

Thanks

Chris

### Steps To Reproduce

1. Setup new Laravel project 
2. Create new file `resources/views/components/test.blade.php`
3. Paste the following code into the file - 
```<div {{ $attributes }}>click</div>```
4. Edit `resources/views/welcome.blade.php` and replace entire file contents with - 
```
<!-- <div onclick="console.log({ action: 'He\'s going to town' })">click</div> -->
<x-test onclick="console.log({ action: 'He\'s going to town' })">click</x-test>
```
5. Run app to see error.

**Comment by Rizky92** [comment]
I don't think this is supported behaviour for blade to parse strings contains escapable chars but if it's really necessary, I'd wrap it in a div and place any attribute with weird values there.

```blade
<div onclick="setAction('He\'s doing something')">
    <x-text onclick="console.log({ action })" />
</div>
```

**Comment by chriischambers** [comment]
Thank you for your feedback although my example was a simplified version of the problem I am experiencing. 

My actual issue is with Alpine JS dispatching an event.  In this case the double escaping works but like I said, i wasn't sure if this was intentional or whether I am raising a bug that nobody was aware of. 

```
<x-trach-icon
    x-on:click="$dispatch('confirm-modal', {
        message: '{{ trans('delete-category.title') }}',
        action: 'Livewire.emit(\\'delete\\', {{ $category }})',
    })"
/>
```

**Comment by driesvints** [comment]
I don't think we can consider this supported sorry. In general if you need to output strings in attributes like that it might be best to save them into a variable first.
