### ISSUE TITLE
Laravel is removing "s" from the resource route name

### ISSUE THREAD

**Issue by DhPandya** [laravel/framework#47601]
### Laravel Version

10.14.0

### PHP Version

8.1

### Database Driver & Version

MySQL 8.1

### Description

Laravel removes the "s" from the declared contact_us resource route.

`
Route::resource('contact_us', ContactUsController::class);
`

In the route:list command the 
![image](https://github.com/laravel/framework/assets/46279781/fb48da6b-39c9-413b-b541-9ab8797c4097)

This causes issues when working with the controller and route model binding.
The show, edit, and destroy method returns an empty model.

### Steps To Reproduce

 - php artisan make:model ContactUs -rmc.
 - Declare the above mentioned routes

**Comment by saade** [comment]
> By default, Route::resource will create the route parameters for your resource routes based on the "singularized" version of the resource name.  https://laravel.com/docs/10.x/controllers#restful-naming-resource-route-parameters

Try the following:

```php
Route::resource('contact_us', ContactUsController::class)->parameters([
    'contact_us' => 'contact_us'
]);
```

**Comment by DhPandya** [comment]
Thanks @saade 
On the link doc, it has clearly mentioned the singularized version concept.
But a confusing thing is that the contact_us is already a singular version. Then why the laravel routes is removing "s" from that. ?

By the way thanks for the reference link.
