### ISSUE TITLE
ShouldBroadcast

### ISSUE THREAD

**Issue by Flywall** [laravel/framework#47616]
### Laravel Version

10.14.1

### PHP Version

8.2.7

### Database Driver & Version

sqlite

### Description

With beyond/laravel-websockets (as mentionned on laravel documentation)
Under Windows OS : it's impossible to use ShouldBroadcast implementation for event cause the query to make a dispatch of event create exception (timeout 60 secondes).
Linux : Work well

### Steps To Reproduce

Make new app under Windows

Install php dependencies
- composer require beyondcode/laravel-websockets
- composer require pusher/pusher-php-server

Set laravel-websockets migration and configuration
- php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="migrations"
- php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="config"
- add specific configuration of pusher from laravel-websockets documentation

Modify config/app.php
- Uncomment "App\Providers\BroadcastServiceProvider::class,"

Set .env with thoses variables :
- DB_CONNECTION=sqlite
- BROADCAST_DRIVER=pusher
- PUSHER_APP_ID=local
- PUSHER_APP_KEY=local
- PUSHER_APP_SECRET=local
- PUSHER_APP_HOST=127.0.0.1
- PUSHER_PORT=6001
- PUSHER_SCHEME=http
- PUSHER_APP_CLUSTER=mt1

Create app with 
- One model
- One event (OrderPlaced) 
- > Add Implements ShouldBroadcast
- > public Order $order in constructor
- > Change "PrivateChannel" to "Channel" in BroadcastOn()
- One listener 
- Enables event and listener in EventServiceProvider.php
- One controller with two entry 
- > index (home page with form and button submit)
- > store (post action to do OrderPlaced::dispatch(Order::find(1))
- Define routes/web.php
- Uncomment Echo in bootstrap.js
- Add in boostrap.js "window.Echo.channel('channel-name').listen('OrderPlaced', (e) => { console.log(e); });"

Before running
- php artisan migrate
- with tinker : create Order model

Running
- yarn build
- php artisan websockets:serve (in first terminal)
- php artisan serve (in second terminal)

Problem : When the OrderPlaced::dispatch(Order::find(1)) is called, the server respond exceed limit 60 seconds.
The problem disappear (but not operate as wished) when the "implements ShouldBroadcast" is removed from event.

Note : The same application works well on Linux and not well on Windows...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
