### ISSUE TITLE
OS command injection in Cookie

### ISSUE THREAD

**Issue by fosiul** [laravel/framework#47633]
### Laravel Version

10.12.2

### PHP Version

8.2.7 

### Database Driver & Version

8.0.33

### Description

The Base64-decoded value of the our_app_session cookie appears to be vulnerable to OS command injection attacks. It is possible to use the pipe character (|) to inject arbitrary OS commands. The command output does not appear to be returned in the application's responses, however it is possible to inject time delay commands to verify the existence of the vulnerability.

The payload '|ping -c 21 127.0.0.1 # was submitted in the Base64-decoded value of the medicina_pharmacy_session cookie. The application timed out when responding to the request, indicating that the injected command caused a time delay.

### Steps To Reproduce

GET /consultation/asthma HTTP/2
Host: our_app.ourdomain.uk
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Language: en-US;q=0.9,en;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.50 Safari/537.36
Connection: close
Cache-Control: max-age=0
Cookie: XSRF-TOKEN=eyJpdiI6IlhPL0JTK2V5M2l6WGlrTGZ6WkZNZUE9PSIsInZhbHVlIjoicytjZGlQTjdHazRvbmZibFg5dlR5dlgrTnlzL2MwZHA3TWhLQ1FGT04yQ1BSMDhoSlJmVFcvTTBSdWFjS0doaVFFeGFFNTJwMEpDVEFJb2FGZmZIamsyM3o1ZDA0TWRzeitmWU1OU21VRmxxeU5VeTljL0pEL1FiS3FzTVQ0d3QiLCJtYWMiOiI2ZmIyYmEwMGZkNGNlNjAwOTdkZWUxMGVlMDZmNTgwYWU0N2VhZGE0MjdhMDc1ZjYyNGQ3YzlmZTk1MjdlZDQzIiwidGFnIjoiIn0%3D; our_app_session=eyJpdiI6IkQ4Ni9HZjFOUkFWSGpCVWRlaXo0RFE9PSIsInZhbHVlIjoidkNYUTZHc3RYVm9Pa0UxVk0wKzR4MHJjamRuNTRGazMvN1J6Y2ZjS3pNbm1RbXhoNmdnWURieTBFV0RMSDk5SVJJQXcySVRYVWg2NXlsbExLY21MZU1Yd0JzWjd6WjdwY3YzRmVnWmRqbVQyN0JEN3ZwWVFhcllyL2xaTFlpVWsiLCJtYWMiOiI4OWI1ZGE1NGYxNWU4OWNmMGI2ZjA5YTQyODhlNjNjY2Q4OTQ2MThlOGVjMTY5NTJkNGM3Njg3MzkwOTVkYzU1IiwidGFnIjoiIn0nfHBpbmcgLWMgMjEgMTI3LjAuMC4xICM%3d
Upgrade-Insecure-Requests: 1
Referer: https://ourdomain.co.uk/cat/asthma
Sec-CH-UA: ".Not/A)Brand";v="99", "Google Chrome";v="112", "Chromium";v="112"
Sec-CH-UA-Platform: Windows
Sec-CH-UA-Mobile: ?0
Content-Length: 0

**Comment by henzeb** [comment]
Great. Security issues have a different procedure. Now you are explaining how to attack thousands of laravel applications to potential hackers....

**Comment by taylorotwell** [comment]
Doesn't hang for me - and I see no way putting anything in the MAC could trigger an OS command.

**Comment by fosiul** [comment]
Hi,
Thanks, It was reported by burp suite, so I was not sure if its issues or we doing some thing wrong.
I am speaking with burp suite team, will update shortly.

**Comment by driesvints** [comment]
Feel free to open a new issue when you can confirm this.

**Comment by valorin** [comment]
@fosiul I'm pretty sure this is a false positive, I've run numerous Burp scans on Laravel and it hasn't flagged this before.

The description says the request timed out, which Burp used to indicate confirmation of the injection but that could easily be unrelated - if Burp was running a scan, the server/app might have simply been overloaded.
