### ISSUE TITLE
Redis Subscribe does not exit on SIGINT (CTRL + C) after upgrade from Laravel 9.x to 10.x

### ISSUE THREAD

**Issue by robinnydahl** [laravel/framework#47648]
### Laravel Version

10.14.1

### PHP Version

8.2.5

### Database Driver & Version

Redis 6.0.6

### Description

After having upgraded our application from Laravel 9.x to Laravel 10.x we have noticed that our Redis subscriptions no longer exit when sending the SIGINT from the console via `CTRL + C`.

The Redis subscription does however stop to listen, however the command is never terminated and you have to write `CTRL + \` to force exit instead of `CTRL + C`.

Please see two test cases below to reproduce the issue.

#### Test Case 1

In this case the SIGINT works as expected.

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;
use Symfony\Component\Console\Command\SignalableCommandInterface;

class TestRedisSubscribe extends Command implements SignalableCommandInterface
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'redis:test-subscribe';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        // The command exits on SIGINT (CTRL + C) as expected
        while (true) {
            echo 'Sleep begin...';
            sleep(5);
            echo 'Sleep ended...';
        }
    }

    public function getSubscribedSignals(): array
    {
        return [SIGINT, SIGTERM];
    }

    public function handleSignal(int $signal): void
    {
        if ($signal === SIGINT) {
            echo 'SIGINT';
            exit;
        }
        if ($signal === SIGTERM) {
            echo 'SIGTERM';
            exit;
        }
    }
}
```

#### Test Case 2

In this case we are not able to exit the command using SIGINT. It's also worth mentioning that the subscription stop accepting data and does trigger the SIGINT after sending another message over the subscription after having typed `CTRL + C`, but it still hangs in the terminal.

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;
use Symfony\Component\Console\Command\SignalableCommandInterface;

class TestRedisSubscribe extends Command implements SignalableCommandInterface
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'redis:test-subscribe';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        // The command never exits on SIGINT (CTRL + C)
        Redis::subscribe('ping', function (string $message) {
              echo $message;
          });
    }

    public function getSubscribedSignals(): array
    {
        return [SIGINT, SIGTERM];
    }

    public function handleSignal(int $signal): void
    {
        if ($signal === SIGINT) {
            echo 'SIGINT';
            exit;
        }
        if ($signal === SIGTERM) {
            echo 'SIGTERM';
            exit;
        }
    }
}
```

**Comment by cosmastech** [comment]
Can you specify which redis client you're using?

I tried to recreate with predis and I see that eventually (after 30 seconds or so), I will see `SIGINT` and the command exits.

From my debugging, the problem lies here in [predis' `StreamConnection@read()` function](https://github.com/predis/predis/blob/dd64569e063390a6eae2d0e18b2f71190c4c11ab/src/Connection/StreamConnection.php#L286), which calls fgets() and from some googling, I *believe* that's blocking, so signals don't get handled.

I'm totally out of my element, so I may or may not be wrong.

**Comment by cosmastech** [comment]
Also, not entirely sure what you're trying to achieve. If you want to create a daemon, you could set a `read_write_timeout` in your database config for your Redis connection, then catch the exception and check the stream metadata if `timed_out` is true.

This is my first foray into anything Redis related, so happy to learn if this is something you have already tried.

**Comment by abdallahalsamman** [comment]
Directly related to https://github.com/predis/predis/issues/563

**Comment by cosmastech** [comment]
I think this can be closed, since it's not specific to Laravel, but instead how predis handles reading from a socket. @driesvints

**Comment by driesvints** [comment]
Thanks all

**Comment by robinnydahl** [comment]
I can confirm that the bug has been resolved on the latest version of Laravel, probably via the predis depedency.

Thanks all!
