### ISSUE TITLE
Illuminate\Http\Request and helper request() can have different values

### ISSUE THREAD

**Issue by Samoylenko666** [laravel/framework#47646]
### Laravel Version

10.14.1

### PHP Version

8.2.3

### Description

Good afternoon. It is correct that Illuminate\Http\Request and helper request() may be different.
Simple example:

        $request->request->set('asd', 'test');

        var_dump($request->get('asd')); // return test

        dd(request()->get('asd')); // return null

Shouldn't they be identical?

### Steps To Reproduce

`$request->request->set('asd', 'test');
  dd(request()->get('asd')); // return null`

**Comment by joy2362** [comment]
![image](https://github.com/laravel/framework/assets/49846472/0f765f10-0f23-4086-874b-07c777ee8816)
@Samoylenko666 I have tested but its returns "test" for both output.

Laravel Version
10.14.1

PHP Version
8.2.7
