### ISSUE TITLE
Document Server-Side Rendering (SSR) wrong command ?

### ISSUE THREAD

**Issue by tommy66374** [laravel/framework#47670]
### Laravel Version

10.14.1

### PHP Version

8.1.20

### Description

When we installed Laravel Breeze Starter Kit

https://laravel.com/docs/10.x/vite#ssr

```
npm run build
node bootstrap/ssr/ssr.mjs
```

should be ?

```
npm run build
node bootstrap/ssr/ssr.js
```

### Steps To Reproduce

`node bootstrap/ssr/ssr.mjs` is not exists

it should be `node bootstrap/ssr/ssr.js` ?

**Comment by jessarcher** [comment]
Thanks, @tommy66374!

I've PR'd the docs at https://github.com/laravel/docs/pull/8896.
