### ISSUE TITLE
Laravel-Vapor can't verify csrf token on post request

### ISSUE THREAD

**Issue by MahmoudQassass** [laravel/framework#47685]
### Laravel Version

9.2

### PHP Version

8.1.6

### Database Driver & Version

RDS MySQL 8.0

### Description

Laravel Vapor
Bug on Post Request  >> page expired (419)
Notes : 
*The token included into post form and I check if token included on request input bag or not.
*There is App_key with environment variables.
*I checked and debug vapor post request and I see there is no cookie handling x-csrf token, I don't Know if this normal because I see it when debugging project on my machine.
*verifyCsrfToken middleware causing page expired error, I think because middleware cant find CsrfToken into request header!

 
Http kernal :
 protected $middleware = [
            // \App\Http\Middleware\TrustHosts::class,
            \App\Http\Middleware\TrustProxies::class,
            \Illuminate\Http\Middleware\HandleCors::class,
            \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
            \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
            \App\Http\Middleware\TrimStrings::class,
            \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

 protected $middlewareGroups = [
        'web' => [

            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,

            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,

            \App\Http\Middleware\VerifyCsrfToken::class,
            \App\Http\Middleware\EncryptCookies::class,
        ],
.
.
]

**Comment by GrahamCampbell** [comment]
Laravel 9.2 is not supported. Upgrade to the latest version of Laravel 9 or Laravel 10.

**Comment by driesvints** [comment]
Can you please contact Vapor support? Thanks
