### ISSUE TITLE
Http\Client\Request data-method has incomplete return type or returns wrong value

### ISSUE THREAD

**Issue by renky** [laravel/framework#47727]
### Laravel Version

10.13.5

### PHP Version

8.2.x

### Database Driver & Version

Mysql 5.7

### Description

File Http/Client/Request
method: data() and json()

The Methods both have the return type array (declared in PHPDoc @return array).

But there is a possibility that it returns null - in case of a non-valid json body.
json_decode will return null if the content cannot be decoded or the depth is to high.

so either the return type shall be changed to ?array or the json function should be extended like so
```
$this->data = json_decode($this->body(), true) ?? [];
```

It isn't a huge issue, but when using PHPStan and doing something like that:
```
$data = $request->data() ?? [];
```
it is always complaining about left part can never be null due to return values...

**Comment by driesvints** [comment]
Thanks but we don't consider invalid DocBlock types as bugs. Please see our contribution guide: https://laravel.com/docs/10.x/contributions#bug-reports

We're welcoming PRs to fix any issues.
