### ISSUE TITLE
Queue don’t gracefully exit when running Artisan::call inside a Job

### ISSUE THREAD

**Issue by ChristopheBorcard** [laravel/framework#47724]
### Laravel Version

10.14.1

### PHP Version

8.2.6

### Database Driver & Version

not relevant

### Description

Since this [commit](https://github.com/laravel/framework/commit/33978612dd266803b89c485c4f12f474b2580505) , running an `Artisan::call()` in a Job overwrites the PCNTL signal management of the worker:queue with that of Symfony.

This makes it possible to stop worker processes instantly without finishing the current Job.

This creates a lot of problems when using Horizon in "auto" mode.

### Steps To Reproduce

1. Create a simple job like:
```php
public function handle(): void
{
    Log::debug('Job start');
    Artisan::call('about');
    Log::debug('Start waiting');
    sleep(60);
    Log::debug('Job terminated');
}
```
2. Start the command queue:worker
3. Insert your job
4. Send a sigterm to the queue:worker process
5. The job will exit before the last log: Job terminated

**Comment by driesvints** [comment]
PR was merged. Thanks!
