### ISSUE TITLE
Issue with pluck() when the item being plucked is a Carbon::Carbon object retrieved via __get()

### ISSUE THREAD

**Issue by leenooks** [laravel/framework#47737]
### Laravel Version

10.13.5

### PHP Version

8.1.18

### Database Driver & Version

n/a

### Description

I have an object Class, where the value "date" is retrieved via a call to __get():

```
class Message extends FTNBase
{
...
	public function __get($key)
	{
		switch ($key) {
			case 'date':
				if (str_contains($x=chop(Arr::get($this->header,$key)),"\x00"))
					throw new \Exception('Date contains null values.');

				return Carbon::createFromFormat('d M y  H:i:s O',
					sprintf('%s %s%04d',$x,($this->tzutc < 0) ? '-' : '+',abs($this->tzutc)));
...
       }
...
}
```

When I call `dd(['messages'=>$this->messages->pluck('date')]);` it results in a collection of `null`'s, where $this->messages is a collection of Message::class.

So I added the following line to `src/Illuminate/Collections/helpers.php` data_get() function (line 77).

```
if ($segment === 'date') dd(['a'=>$target->{$segment},'b'=>isset($target->{$segment}),'c'=>$x=$target->{$segment},'d'=>isset($x)]);
```

Which results in the following output:

```
array:4 [ // vendor/laravel/framework/src/Illuminate/Collections/helpers.php:77
  "a" => Carbon\Carbon @1645155150^ {#3897
    #endOfTime: false
    #startOfTime: false
    #constructedObjectId: "0000000000000f390000000000000000"
    #localMonthsOverflow: null
    #localYearsOverflow: null
    #localStrictModeEnabled: null
    #localHumanDiffOptions: null
    #localToStringFormat: null
    #localSerializer: null
    #localMacros: null
    #localGenericMacros: null
    #localFormatFunction: null
    #localTranslator: null
    #dumpProperties: array:3 [
      0 => "date"
      1 => "timezone_type"
      2 => "timezone"
    ]
    #dumpLocale: null
    #dumpDateProperties: null
    date: 2022-02-18 14:32:30.0 +11:00
  }
  "b" => false
  "c" => Carbon\Carbon @1645155150^ {#3901
    #endOfTime: false
    #startOfTime: false
    #constructedObjectId: "0000000000000f3d0000000000000000"
    #localMonthsOverflow: null
    #localYearsOverflow: null
    #localStrictModeEnabled: null
    #localHumanDiffOptions: null
    #localToStringFormat: null
    #localSerializer: null
    #localMacros: null
    #localGenericMacros: null
    #localFormatFunction: null
    #localTranslator: null
    #dumpProperties: array:3 [
      0 => "date"
      1 => "timezone_type"
      2 => "timezone"
    ]
    #dumpLocale: null
    #dumpDateProperties: null
    date: 2022-02-18 14:32:30.0 +11:00
  }
  "d" => true
]
```

IE: "b" is `false` even though "a" shows that it returns a value. 

I was able to resolve this by adding an `__isset()` method to my class, but I was thinking that this really should be fixed another way. Not sure if it is a bug with PHP?

### Steps To Reproduce

Details above...

**Comment by cosmastech** [comment]
Did you try implementing ArrayAccess on your `Message` class? That's potentially workaround for the problem.

Not sure this is a framework issue really.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
