### ISSUE TITLE
Unexpected behavior in translations with parameters containing numbers

### ISSUE THREAD

**Issue by mortenscheel** [laravel/framework#47735]
### Laravel Version

10.15.0

### PHP Version

8.2.8

### Database Driver & Version

Not relevant

### Description

There seems to be something wrong in the way the translation system inserts values into parameter placeholders when those placeholders contain numbers.

Example:
**lang/test.php**
```php
<?php

return [
    'from-to' => 'From :name to :name2'
];
```
**Example**
```php
echo __('test.from-to', ['name' => 'me', 'name2' => 'you']);
// => From me to you (as expected)
echo __('test.from-to', ['name' => 'me']);
// => From me to me2
```

It's a bit of an edge case, but I think it's reasonable to expect that the last example should return `From me to :name2`

### Steps To Reproduce

See description

**Comment by driesvints** [comment]
Thank you. Right now this is the correct expected behavior. We advice to refrain from using trailing numbers and use a different placeholder name.
