### ISSUE TITLE
The context binding in the service provider is not functioning properly.

### ISSUE THREAD

**Issue by xgbnl** [laravel/framework#47751]
### Laravel Version

10.15.0

### PHP Version

8.2

### Database Driver & Version

MYSQL 8.3 for Windows 11

### Description

During the development of my extension package using Laravel components, I have encountered an issue regarding dependency context binding while running test units.
This is the content of the binding.
```php
$this->app->when(ValidateScene::class)
            ->needs(Factory::class)
            ->give(ValidatorFactory::class);
```

This is the content printed through the console.
```php
  +contextual: array:1 [
    "Dingo\Validation\Scenes\ValidateScene" => array:1 [
      "Dingo\Validation\Factory\Contacts\Factory" => "Dingo\Validation\Factory\ValidatorFactory"
    ]
  ]
```

However, when I tried to instantiate the ValidateScene class using a container during testing, it threw the following exception.
```
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Container\Container] is not instantiable while building [Dingo\Validation\Scenes\ValidateScene, Dingo\Validation\Factory\ValidatorFactory].
```
However, I was able to achieve instantiation using the `$this->app->bind()` method.

### Steps To Reproduce

I had hoped that using the when->needs->give syntax would make it work as expected, but unfortunately, it's not meeting my expectations.

**Comment by thraxxdv** [comment]
How were you able to fix this @xgbnl?
