### ISSUE TITLE
Decimal validation rule fails when php converts decimals to scientific notation

### ISSUE THREAD

**Issue by saineshmamgain** [laravel/framework#47778]
### Laravel Version

10.15.0

### PHP Version

8.2.8

### Database Driver & Version

NA

### Description

I am creating an API which accepts amount in decimal and decimal number can be up to 4 decimal places. I am using the decimal rule like this: `amount => decimal:0,4`. It works as expected for `1.00001` but fails for `0.00001`. On further digging I found that the number `0.00001` was being converted to `1.0e-5` causing the decimal rule to fail.

### Steps To Reproduce

Add a validator in a controller and pass the number 0.00001

```
public function store(Request $request)
{
    $validated = $request->validate([
        'amount' => 'decimal:0,4'
    ]);
}
```

This validation will pass for number 0.00001

**Comment by driesvints** [comment]
Seems to work for me

<img width="1021" alt="Screenshot 2023-07-19 at 07 18 11" src="https://github.com/laravel/framework/assets/594614/1c78054b-ff74-46cb-8649-a3311aba3882">
