### ISSUE TITLE
when we give null value to Query builder where method we get where is null

### ISSUE THREAD

**Issue by Lanser0614** [laravel/framework#47772]
### Laravel Version

9.0

### PHP Version

8.1

### Description

<img width="936" alt="image" src="https://github.com/laravel/framework/assets/62260034/5cd57a5b-7684-4f54-87e2-78f5c7c883e9">
<img width="1143" alt="image" src="https://github.com/laravel/framework/assets/62260034/a649c693-eaa4-488b-97f2-074b02b79716">

When we have given null value in the where method on query Builder we get sql query like 
"where external_id is null" and there  have side effect for development and it is not obvious,
i think 
<img width="936" alt="Снимок экрана 2023-07-18 в 21 28 01" src="https://github.com/laravel/framework/assets/62260034/73df20e1-33e3-4ef8-a56b-d0f868c6bcfb">
We can remove this if condition from code

### Steps To Reproduce

<img width="936" alt="Снимок экрана 2023-07-18 в 21 23 00" src="https://github.com/laravel/framework/assets/62260034/f72e0a51-7bcb-411a-a0a7-589ff6e79419">

**Comment by driesvints** [comment]
This is the expected behavior
