### ISSUE TITLE
Laravel Eloquent issue with Mysql 8 | Laravel duplicate prepare statement

### ISSUE THREAD

**Issue by elbyvilayil** [laravel/framework#47796]
### Laravel Version

9

### PHP Version

8.1

### Database Driver & Version

MySQL 8

### Description

Laravel Eloquent query triggering duplicate prepare statement in Mysql 8.x 
When we check Mysql General logs. 
For Example User::find(10); is triggering two prepare statement and one execute query in Mysql. 

But Mysql 5.x is working fine.

**2023-07-21T08:27:06.028226Z 366 Prepare select * from users where users.id = ? and users.deleted_at is null limit 1 
2023-07-21T08:27:06.028488Z 366 Prepare select * from users where users.id = ? and users.deleted_at is null limit 1 
2023-07-21T08:27:06.028527Z 366 Execute select * from users where users.id = 17 and users.deleted_at is null limit 1**

other queries also same. I ran with tinker and other system and projects.

**2023-07-21T08:50:08.253051Z 374 Prepare select * from permission_temp where organization_id = ? and permission_id = ? limit 1 
2023-07-21T08:50:08.253148Z 374 Prepare select * from permission_temp where organization_id = ? and permission_id = ? limit 1 
2023-07-21T08:50:08.253169Z 374 Execute select * from permission_temp where organization_id = 6999 and permission_id = 108789797 limit 1**

### Steps To Reproduce

1. Apache in Ubuntu 20.x / Mac
2. Enable Mysql General logs
3. Use any model or tinker run any Eloquent query 
4. **User::find(1)** something like that 
5. Check Mysql General Query 
We can see duplicate prepare statement and one execute query for your query

**Comment by ionutantohi** [comment]
@elbyvilayil I noticed this myself a few days ago. After some debugging, I determined that is not a laravel issue, because I replicated it without laravel.

I opened this [issue](https://github.com/php/php-src/issues/11744), on php-src repo. 

But, might not be php fault at all. The second prepare might be an internal **reprepare** statement issued by mysql when there are params bound as INT

**Comment by driesvints** [comment]
I don't really see an issue here? If the queries work all is fine imo.
