### ISSUE TITLE
Using `RouteCollectionInterface::match` alters current route

### ISSUE THREAD

**Issue by Yinci** [laravel/framework#47795]
### Laravel Version

10.15.0

### PHP Version

8.1.21

### Database Driver & Version

Ver 14.14 Distrib 5.7.40, for Linux (x86_64)

### Description

When a route has parameters, the parameters are altered when using `RouteCollectionInterface::match` with a manually created request, using a URL that matches the current route.

Purpose of using `match` is to resolve an unknown URL to a route with parameters, as described in [this](https://laracasts.com/discuss/channels/laravel/how-to-get-a-route-from-uri) Laracast answer. It so happened to be resolving a URL with the same route as the current route.

### Steps To Reproduce

- Perform a clean Laravel 10 install, and enable the User factory in the `DatabaseSeeder`, so you have users in your database
- Create a middleware:

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class ResolveRoute
{
    public function handle(Request $request, \Closure $next, ...$guards)
    {
        $uri = '/users/2';
        $request = request()->create($uri);

        Route::getRoutes()->match($request);

        return $next($request);
    }
}
```

- Edit the `web.php` route file:

```php
Route::get('users/{user}', function (\App\Models\User $user) {
    dd($user, \Route::current());
})->name('users')->middleware(\App\Http\Middleware\ResolveRoute::class);
```

- Open the route `users/1` in your webbrowser, and notice how the returned user is a clean instance, and the current route has the parameters of the fresh request, instead of the originally bound model.

**Comment by driesvints** [comment]
I'm sorry but I don't think this is a realistic example. There can't be "two" requests at the same time. The `create` method is also a symfony method which we don't control. Laravel has its own dedicated `createFrom` and `createFromBase` static methods to create a new request. 

I don't think we should do any modification to the route collection here.

**Comment by Yinci** [comment]
@driesvints If it's not the intended behaviour, then sure, that's fine by me. However, then I would like to know an alternative to the answer provided in the Laracast thread, since that answer is the one that is widely spread. As of right now, I, nor the community, see any _other_ way of resolving a URL back to a route, but this is something that I do require, as well as others, hence the Laracast thread.  

Laravel resolves the URL back to a route, as otherwise the current request would not be able to have a route name. However, I assume this is done using the same code. So if that's not the intented way of getting a route from a URL, then what is?

**Comment by driesvints** [comment]
I don't understand what you mean sorry. Can you provide a very simple code example of what you're trying to achieve? You also can't get the route from the request and get its name through it? 

```php
request()->route()->getName();
```

**Comment by Yinci** [comment]
@driesvints Consider the following route:

```php
Route::get('users/{user}', [UserController::class, 'show']->name('users.show'); 
```

We know that `route('users.show', compact('user')` will provide us with the URL `/users/1`. However, what if we have a string of which we know is a URL, but we don't know the route name? It wouldn't be bound to a request, so your provided example would not work.

In one of our projects, the admin can create pages and manually fill the URL, and provide content for this page. By being able to resolve the URL back to a route, we can use the (potential) parameters to create default content. 

So, something like `Route::getRouteFromUrl($url)` would provide a `Illuminate\Routing\Route` object purely from a string URL, which currently is only possible (afaik) by using `Route::getRoutes()->match($request);`

**Comment by driesvints** [comment]
@Yinci I see what you mean now. Right now we don't have anything like that to resolve the route name. You could attempt to send in another PR but it would have to be in a non-breaking way as opposed to your previous one. Thanks!
