### ISSUE TITLE
Cannot bind IPv6 to local development server "artisan serve"

### ISSUE THREAD

**Issue by MuriloChianfa** [laravel/framework#47803]
### Laravel Version

10.15.0

### PHP Version

8.1.21

### Database Driver & Version

Debian 11

### Description

Hello guys, when i decide to reproduce the bug [IPv6 URLs with square brackets are not supported by Laravel's routing system](https://github.com/laravel/framework/issues/46315), i created a new laravel project from streach to try to reproduce this... but dont be possible to run the local development server with "artisan serve" command with IPv6 address:

![image](https://github.com/laravel/framework/assets/60560085/44eb73ff-ddcd-42f4-91a8-ef4af94d95c1)

Notice that only IPv4 is possible.
I have seemed the implementation serve command and have founded the [explode by :](https://github.com/laravel/framework/blob/c59d540ab142d36ee0f62c3ddc749329a968466b/src/Illuminate/Foundation/Console/ServeCommand.php#L204) but it is used when try to bind the IPv6 address as host.

### Steps To Reproduce

- composer create-project --no-install --no-scripts --prefer-dist laravel/laravel test
- cd test
- composer install
- npm install
- composer run-script post-root-package-install
- composer run-script post-create-project-cmd
- php artisan serve --host="[::1]"

**Comment by elijahcruz12** [comment]
I'm curious as to why you would bind to IPv6 with Artisan Serve, as it's meant to use locally, not putting it down, just certainly interesting as I've never thought of that idea.
