### ISSUE TITLE
Collection GroupBy Enum

### ISSUE THREAD

**Issue by megasteve19** [laravel/framework#47810]
### Laravel Version

10.15.0

### PHP Version

8.2.8

### Description

Probably, it's not a bug; it might have been forgotten or intentionally left as is. We cannot group an eloquent collection by an enum column. The following code will throw an error: `array_key_exists(): Argument #1 ($key) must be a valid array offset type`.

```php
Device::orderBy('name')
    ->get()
    ->groupBy('type')
    ->dd();
```

This issue arises because it attempts to set the enum as an index, which is not allowed. However, there is a workaround. If you manually retrieve the value of the enum, everything will work perfectly:

```php
Device::orderBy('name')
    ->get()
    ->groupBy(fn (Device $device) => $device->type->value)
    ->dd();
```

In the second code snippet, we use a callback function in the `groupBy` method to access the `value` of the `type` enum and use it as the index for grouping. This way, the grouping operation works as expected without any errors. I think the framework should handle this situation itself.

### Steps To Reproduce

1. Add an enum cast to a model.
2. Populate the database with it.
3. Then fetch the data and try to group it by the enum column.

**Comment by megasteve19** [comment]
I was about to open a pull request for it, but it was already rejected in #47460

**Comment by osbre** [comment]
Fixed today specifically for `groupBy`: https://github.com/laravel/framework/pull/47823

**Comment by megasteve19** [comment]
@osbre Thanks! I implemented it too, but didn't open a PR :smile:  I guess Taylor woke up on the right side of the bed today.
