### ISSUE TITLE
ofMany fails when using only aggregate or when column is null

### ISSUE THREAD

**Issue by MissaelAnda** [laravel/framework#47836]
### Laravel Version

10.16.0

### PHP Version

8.2.7

### Description

The `ofMany` function in `CanBeOneOfMany` trait breaks when only providing the `aggregate` parameter with a closure because it tries to use `strtolower` with the closure, and if the `column` is set to null (wich the DocComment says it can) it breaks again trying to use `array_key_exists` on null.

Both problems can be fixed changin lines 79-82 with:
```php
$columns = is_string($columns = $column) ? [
    $column => $aggregate,
    $keyName => $aggregate,
] : ($column ?? []);
```

and letting the default values of `column` and `aggregate` to null.

### Steps To Reproduce

Create a Model with the following relation:
```php
public function books(): HasMany
{
    return $this->hasMany(Book::class);
}
```
And any of the next relations:
```php
public function book(): HasOne
{
    return $this->books()->one()->ofMany(aggregate: fn ($query) => $query->where('some_field', true));
}
```
```php
public function book(): HasOne
{
    return $this->books()->one()->ofMany(null, fn ($query) => $query->where('some_field', true));
}
```

**Comment by driesvints** [comment]
Thanks. Are you willing to send in a PR?

**Comment by taylorotwell** [comment]
I don't see this way of using `ofMany` documented anywhere in our documentation. Perhaps the DocBlock should be changed.
