### ISSUE TITLE
When using null value for implicit binding it give null param find error

### ISSUE THREAD

**Issue by Mdhesari** [laravel/framework#47842]
### Laravel Version

10.10

### PHP Version

8.2

### Database Driver & Version

Postgres 15.0

### Description

When attempting to use a null value for implicit binding in the route parameter, an error occurs. Specifically, the problem arises when the route expects a key value through implicit binding, when the given parameter value is null it throws a 500 error instead of not found (404).

### Steps To Reproduce

1. Define the route in web.php or routes/api.php

Route::get('transactions/{transaction}', 'TransactionController@show');

2. Define the "show" method in the "TransactionController":

public function show(Transaction $transaction)
{
    // Code to handle displaying the transaction details
}

3. Now, when a request is made to "/transactions/{transaction}" with the "transaction" parameter as null, the error occurs.

Expected Behavior:
not found (404) response as the null value is not a correct value.

Actual Behavior:
Currently, when passing a null value for the "transaction" parameter, Laravel throws an error similar to the following:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type uuid: "null" (Connection: pgsql, SQL: select * from "transactions" where "id" = null limit 1)

**Comment by driesvints** [comment]
How are you making the request? Please provide some code. Thanks!

**Comment by Mdhesari** [comment]
I'm listening to telescope requests which have been made from front-end devs this is the payload and headers :

<img width="1268" alt="image" src="https://github.com/laravel/framework/assets/28428724/b1de1845-1a70-4b29-a78f-a45d80378b18">

<img width="1268" alt="image" src="https://github.com/laravel/framework/assets/28428724/3551eaa9-382d-42e8-899e-3841444d9a5b">

**Comment by Mdhesari** [comment]
<img width="1268" alt="image" src="https://github.com/laravel/framework/assets/28428724/bae1dc20-9b23-4492-b69d-12a1983051a5">

**Comment by driesvints** [comment]
I'm not sure what you expect here. `null` is being passed and that gives a query exception. You're using implicit model binding for this. If you don't want this to happen then you need to protect the route with a regex: https://laravel.com/docs/10.x/routing#parameters-regular-expression-constraints

Most likely with `whereUuid` in this case.

**Comment by Mdhesari** [comment]
@driesvints 

ok I was asking if that is about query problem trying to find null uuid but it throws an Invalid text representation syntax
