### ISSUE TITLE
When using assertSoftDeleted without deletedAtColumn it always uses deleted at

### ISSUE THREAD

**Issue by Safrankuchen** [laravel/framework#47856]
### Laravel Version

10.14.1

### PHP Version

8.2.7

### Description

When using assertSoftDeleted while my model has a custom DELETED_AT column set, assertsoftdeletes tries using deleted_at

### Steps To Reproduce

create a model with:
```
use SoftDeletes;
protected const DELETED_AT = 'archived_at';
```

and in a test try:
```
$this->assertSoftDeleted(
            Order::class,
            ['id' => $this->order->id,]
        );
```

**Comment by cosmastech** [comment]
Since you are not passing a model instance to `assertSoftDeleted()`, you need to also specify the deletedAtColumn parameter. https://github.com/laravel/framework/blob/45b61f5693e3edd3a5352fac269854e022f5b426/src/Illuminate/Foundation/Testing/Concerns/InteractsWithDatabase.php#L108-L110

**Comment by driesvints** [comment]
Thanks @cosmastech

**Comment by edvordo** [comment]
This seems like it could be a fairly simple thing to handle.

```php
        $this->assertThat(
            $this->getTable($table), 
            new SoftDeletedInDatabase(
                $this->getConnection($connection, $table), 
                $data, 
                $this->newModelFor($table)?->getDeletedAtColumn() ?: $deletedAtColumn
            )
        );
```

Happy to try and throw together a PR if you think it could be beneficial @driesvints

**Comment by driesvints** [comment]
@edvordo you can always try a PR to see if Taylor would accept it 👍
