### ISSUE TITLE
Single log driver not honoring days

### ISSUE THREAD

**Issue by suncoastkid** [laravel/framework#47855]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

Logging is configured for a single file and seven days retention, but the single file retention is lasting 30 days. 

```
'scheduled-jobs' => [
            'driver' => 'single',
            'path' => storage_path('logs/scheduled-jobs.log'),
            'level' => 'info',
            'days' => 7,
        ],
```

### Steps To Reproduce

Set up a log channel and specify single driver and seven days in config/logging. Single log file retains logs for 30 days, not seven.

**Comment by crynobone** [comment]
Only `daily` driver support `days` options: https://github.com/laravel/framework/blob/03564b126a1f0802e7efff5191898e065b9a956c/src/Illuminate/Log/LogManager.php#L307-L315

**Comment by crynobone** [comment]
![image](https://github.com/laravel/framework/assets/172966/f0878e0e-356d-4698-a87f-9eecd8a357cd)
