### ISSUE TITLE
Eager loading fails with foreignUlid and many rows

### ISSUE THREAD

**Issue by guttormf** [laravel/framework#47876]
### Laravel Version

10.16.1

### PHP Version

8.1.13

### Database Driver & Version

mariadb-server-10.5 - mysql driver

### Description

I just saw a strange thing happening with eager loading and foreignUlid. After a certain number of rows, eager loading simply doesn't work. I had about 5000 rows. It works fine with regular incrementing keys. With foreignUlid it works fine with a low number of rows, but not many.

### Steps To Reproduce

For example - we have the models Books and Authors. A migration:

```
        Schema::create('authors', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->timestamps();
            $table->string('name');
        });

        Schema::create('books', function (Blueprint $table) {
            $table->ulid('id')->primary();
            $table->timestamps();
            $table->string('name');
            $table->foreignUlid('author_id')->contrained();
        });
```

Author model:

```
class Author extends Model
{
    use HasFactory, HasUlids;

    protected $fillable = ["name"];

    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

```

```
class Book extends Model
{
    use HasFactory, HasUlids;

    protected $fillable = ["name", "author_id"];

    protected $with = [ "author" ];

    public function author()
    {
        return $this->belongsTo(Author::class);
    }
}

```

Then create 1000 authors with 5 books each:

```
        \DB::beginTransaction();

        for ( $i=1 ; $i<=1000 ; $i++ ) {
            $author = \App\Models\Author::create([
                'name' => "Author $i"
            ]);
            for ( $j=1 ; $j<=5 ; $j++ ) {
                $book = \App\Models\Book::create([
                    'name' => "Book $j",
                    'author_id' => $author->id,
                ]);
            }
        }
        \DB::commit();
```

Then we load the books with author eager loaded:

`$books = \App\Models\Book::with('author')->orderBy('name')->get();`

The authors are not eager loaded - this gives the error:  "Attempt to read property "name" on null".

```
        foreach ($books as $book) {
            echo $book->name . " - " . $book->author->name . "\n";
        }

```
It has something to do with the number of books. This runs fine:

`$books = \App\Models\Book::with('author')->limit(500)->orderBy('name')->get();`

I'm not sure about a limit or if there should be one? But it's strange it just sets $book->author to null. Without the eager loading, the code runs - but of course it's slow because of the number of queries.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by guttormf** [comment]
I found out about it. It's not  a bug in Eloquent, but in some versions of MariaDB server. In Laravel, it happens when using whereIn with more than 999 elements in the array - or when eager loading with uuids or ulids. 

https://jira.mariadb.org/browse/MDEV-27937
