### ISSUE TITLE
Request Merge Problem

### ISSUE THREAD

**Issue by kursadaltanmed** [laravel/framework#47877]
### Laravel Version

9.52.12

### PHP Version

8.0.2

### Database Driver & Version

Mysql

### Description

The request merge function we use in Middleware does not work in this version. It does not merge into the request.

9.52.11 version don't have this problem.

### Steps To Reproduce

Ex:

SomeMiddleware
$request->merge(['fullname' => concate($request->get('name') ?? "", $request->get('lastname') ?? "")]);

Body

Content Type : Json

{
    "name" : "Test",
    "lastname" : "Test",
}

**Comment by taylorotwell** [comment]
What kind of value are you attempting to merge in? 

We had to make changes to the request input due to type changes in Symfony and they have classes marked as final so we have no way to work around it.

**Comment by ImJustToNy** [comment]
I experience similar issue in laravel v9.52.12 / php v8.1.21.

**Comment by kursadaltanmed** [comment]
I have two string input parameters. I concatenate these two strings into a variable, and then I try to merge that variable into the request. It used to work without any issues in older versions, but in the current version, I'm unable to add the concatenated variable to the request.

I want to clarify that I'm using middleware for this code block:

$request->merge(['fullname' => concat($request->get('name') ?? "", $request->get('lastname') ?? "")]);

Both 'name' and 'lastname' are expected to be in string format in the JSON request.

**Comment by manish-pareek** [comment]
Yes same problem for me as well .  @taylorotwell  @kursadaltanmed 

        $request->merge(['country' => 'india']);
        dd($request->country);    //Working
        dd($request->get('country'));  //Not-working..  It was working earlier



        $request->request->add(['country' => 'india']);
        dd($request->country);    //Not Working...  It was working earlier 
        dd($request->get('country'));  //working

**Comment by taylorotwell** [comment]
I would stop using `$request->get`. We never document that method anywhere. It is an internal Symfony method.

**Comment by timacdonald** [comment]
I've created a potential PR to fix this issue: https://github.com/laravel/framework/pull/47914

I'll close this and we can track the issue in the PR.
