### ISSUE TITLE
Vite nonce empty in browser

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#47886]
### Laravel Version

10.16.1

### PHP Version

8.2.7

### Database Driver & Version

N/A

### Description

In a plain Laravel installation, I've followed the docs regarding CSP nonces: https://laravel.com/docs/10.x/vite#content-security-policy-csp-nonce
Unfortunately nonces always remain empty when inspecting the browser, resulting in scripts being blocked.
This happens both for `npm run dev` as `npm run build`.

Weird thing is that when dd'ing the nonce value in the blade file, it's actually defined. But somehow the tag's value gets lost afterwards?

<img width="485" alt="Scherm­afbeelding 2023-07-29 om 10 26 53" src="https://github.com/laravel/framework/assets/6680176/5399c073-7241-4974-b132-bd2b14c4d9e5">

I'm using Laravel Valet.
The image above shows SRI as well; without it the same bug happens.

### Steps To Reproduce

1. Install Laravel
2. Install Laravel Breeze (breeze:install vue)
3. Follow the docs: https://laravel.com/docs/10.x/vite#content-security-policy-csp-nonce
4. Remove the `$role` parameter in the middleware (see https://github.com/laravel/docs/pull/8927)
5. Insert the `AddContentSecurityPolicyHeaders` middleware in the `web` middleware group
6. Either do `npm run dev` or `npm run build`
7. Open browser

**Comment by timacdonald** [comment]
@Propaganistas this is intended behaviour and for security purposes. The browser itself removes the nonce from the DOM. This prevents scripts or other resources from accessing and abusing the nonce.

If the nonce is removed and the script / styling is working, your nonce is doing exactly what it should.

<img width="801" alt="Screen Shot 2023-07-31 at 9 12 09 am" src="https://github.com/laravel/framework/assets/24803032/992e3e2c-161e-4e7d-92ac-b568fd959804">

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding

**Comment by Propaganistas** [comment]
Hi @timacdonald , thanks for the clarification on nonces showing empty in the browser - didn't know that.

Apparently I was experiencing blocked assets as soon as I turned on CSP, but I found that they were caused by the Vue Devtools plugin trying to insert some inline script that is getting blocked straight away.

**Comment by timacdonald** [comment]
I was also confused when I first saw this, so you are not alone!

That makes sense. Can be tricky getting all these things to line up nicely sometimes.
