### ISSUE TITLE
The Process class does not include information about the error reason.

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#47893]
### Laravel Version

10*

### PHP Version

8.2

### Database Driver & Version

pgsql

### Description

When you apply `throw` in Process class like so:

```php
Process::run('not-exit-command')->throw();
```

The exception does not include the reason in the log file:

```
[2023-07-30 07:16:20] testing.ERROR: The process "not-exit-command" failed.
```

But the symfony class also includes the reason:

```
[2023-07-30 07:24:25] testing.ERROR: The command "not-exit-command" failed.

Error Output:
================
sh: exec: line 0: 'not-exit-command': not found
```

So if you want to get the error reason you have to catch the exception and manually log the error:

```php
try {
    Process::run('not-exit-command')->throw();
} catch (ProcessFailedException $e) {
    logger($e->result->errorOutput());
    //manually log error on every usage of Process class
}
```

You cannot reproduce the issue in production if you don't manually log the exception.

**Comment by crynobone** [comment]
You should be able to simplify this using the following:

```php
Process::run('not-exit-command')
    ->throw(fn ($result, $exception) => logger($result->errorOutput()));
```

**Comment by foremtehan** [comment]
What if i used Process in 10 places? It become duplicated

**Comment by crynobone** [comment]
Tested with the latest Laravel Framework 10 and this seems to be already supported.

![image](https://github.com/laravel/framework/assets/172966/7d400ae1-d9c9-47f4-bed6-70836f52b7b3)

**Comment by foremtehan** [comment]
I realized that it does not include when you test it via phpunit, Can you test it on the terminal and see whether you get the reason output?
