### ISSUE TITLE
fwrite(): Write of 2637 bytes failed with errno=122 Disk quota exceeded 

### ISSUE THREAD

**Issue by MohamedAbdel-wahed** [laravel/framework#47900]
### Laravel Version

10.4.1

### PHP Version

8.2

### Database Driver & Version

8.0.3

### Description

i am getting this error :
fwrite(): Write of 2637 bytes failed with errno=122 Disk quota exceeded

only for api routes
i have no idea why it happens to be for api routes only

if there is anyone got solution, please help because this issue happened on production and i am stuck there :(

### Steps To Reproduce

 i have no idea why it happens or how to reproduce it

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by gabriellord137-create** [comment]
> ### Laravel Version
> 10.4.1
> 
> ### PHP Version
> 8.2
> 
> ### Database Driver & Version
> 8.0.3
> 
> ### Description
> i am getting this error : fwrite(): Write of 2637 bytes failed with errno=122 Disk quota exceeded
> 
> only for api routes i have no idea why it happens to be for api routes only
> 
> if there is anyone got solution, please help because this issue happened on production and i am stuck there :(
> 
> ### Steps To Reproduce
> i have no idea why it happens or how to reproduce it
