### ISSUE TITLE
Artisan::call('migrate:fresh') with pgsql-schema.sql fails with error 'could not find a "psql" to execute'

### ISSUE THREAD

**Issue by Gnative** [laravel/framework#47909]
### Laravel Version

10.16.1

### PHP Version

8.2.7

### Database Driver & Version

Postgresql@14

### Description

After squashing a pgsql databsse with 
```
php artisan schema:dump
``` 

running

```
php artisan migrate:fresh
``` 
functions correctly to migrate the squashed database dump.

Running any of:

```
    Artisan::call('migrate:fresh');

    Artisan::call('migrate:fresh', [
        '--database' => 'pgsql',
    ]);
    
    Artisan::call('migrate:fresh', [
        '--database' => 'pgsql',
        '--schema-path' => database_path().'/schema/pgsql-schema.sql',
    ]);
```

Fails with

```
Symfony\Component\Process\Exception\ProcessFailedException: The command "psql --file="${:LARAVEL_LOAD_PATH}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --username="${:LARAVEL_LOAD_USER}" --dbname="${:LARAVEL_LOAD_DATABASE}"" failed.

Exit Code: 1(General error)

Working directory: /Users/Gnative/Development/Sites/Contours/source/http/contours/public

Output:
================


Error Output:
================
could not find a "psql" to execute
could not find a "psql" to execute
psql: fatal: could not find own program executable
```

Running

```
    $output = shell_exec('psql --version');
    dd($output);
```

Outputs correctly the psql version

Tripple checked all my psql paths but as the CLI for command for migrate:fresh and the direct shell_exec output shows psql I'm not sure what is happening. 

### Steps To Reproduce

Debug repo - [https://github.com/Gnative/laravel-debug](https://github.com/Gnative/laravel-debug)

Set up PGSQL database
Added up web routes `routes/web.php` to test the migrations 

`/migrate/pgsql` 

running `php artisan migrate:fresh` will work as will `php artisan migrate:fresh --schema-path=database/schema/pgsql-schema.sql`

**Comment by crynobone** [comment]
#
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? Also do check if manually running the artisan command would fix the issue, which might mean that it only possible to run psql on CLI and not web requests.

If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Gnative** [comment]
ok thanks @crynobone 

My description above does say that running migrate:fresh in the CLI does work but not from with in a web request and i also go on to explain that with in the same web request I checked the existence of pqsql with shell_exec and that it is available..  just using migrate:fresh with a schema-dump file fails. 

I did do extensive searching for a solution before posing this issue here.

**Comment by crynobone** [comment]
The thing is PHP used on the webserver and PHP running on CLI may have different access which causes this issue and it's that is the cause there nothing that Framework can do except to suggest you to use `Artisan::queue()` which then would queue the command to Laravel queue and will be executed within CLI.

**Comment by Gnative** [comment]
OK @crynobone thank you so much for your time. I'll keep digging
