### ISSUE TITLE
Redis Cache Tags unable to flush

### ISSUE THREAD

**Issue by jhemmmm** [laravel/framework#47903]
### Laravel Version

10.16.1

### PHP Version

8.2.8

### Database Driver & Version

mysql  Ver 15.1 Distrib 10.7.8-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

### Description

Hello,

In production, the 
```
Cache::tags('TAGS')->flush();
```

It only works after a few days and then stopped working completely.

```
Cache::tags('TAGS')->get(cache_key(['TAGS' => true, 'PAGE' => 1, 'SORT' => 'newest']));
= Illuminate\Pagination\LengthAwarePaginator {#7281
    +onEachSide: 3,
  }

> Cache::tags('TAGS')->flush();
= true

> Cache::tags('TAGS')->get(cache_key(['TAGS' => true, 'PAGE' => 1, 'SORT' => 'newest']));
= Illuminate\Pagination\LengthAwarePaginator {#8029
    +onEachSide: 3,
  }

> Cache::tags('TAGS')->forget(cache_key(['TAGS' => true, 'PAGE' => 1, 'SORT' => 'newest']));
= true

> Cache::tags('TAGS')->get(cache_key(['TAGS' => true, 'PAGE' => 1, 'SORT' => 'newest']));
= null
```

I was under the expression that it could be the flush function that isn't working so I tried doing the forget function, as expected, it works just fine, but the flush isn't working.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by leo108** [comment]
Same issue, it's very hard to reproduce but causing issues in our production environment.

**Comment by indigoram89** [comment]
Had the same problem in production for long time. We removed ```cache:prune-stale-tags``` command from Console/Kernel.php and it works Ok for these days.

**Comment by MartySVK** [comment]
Don't understand why this issue was closed. Redis cache is totally broken in Laravel 10
