### ISSUE TITLE
whenAggregated never returns MissingValue

### ISSUE THREAD

**Issue by maslennikov-yv** [laravel/framework#47918]
### Laravel Version

10.16.1

### PHP Version

8.2.8

### Description

\Illuminate\Http\Resources\ConditionallyLoadsAttributes::whenAggregated never returns \Illuminate\Http\Resources\MissingValue

### Steps To Reproduce

Returns value when i perform eager aggregate, and return null when i don't

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by maslennikov-yv** [comment]
This is not an IDE warning, this is a logic error, if you don't want to fix it, leave it to the community

**Comment by crynobone** [comment]
The community are free to submit a PR, for now this seems to be more of a docblock issue than anything else.

**Comment by maslennikov-yv** [comment]
This method avoids unnecessarily including the attribute if the relationships aggregation missing by returning MissingValue instance but he doesn't

What about the PR, I'm not familiar enough with laravel  code style

**Comment by crynobone** [comment]
> This method avoids unnecessarily including the attribute if the relationships aggregation missing by returning MissingValue instance but he doesn't

Wouldn't changing from `null` to excluding the key cause a breaking change.

**Comment by maslennikov-yv** [comment]
Yes, but otherwise this method is looks like useless
