### ISSUE TITLE
file_exists(): File name is longer than the maximum allowed path length on this platform (4096)

### ISSUE THREAD

**Issue by diegoanso** [laravel/framework#47947]
### Laravel Version

10.17.1

### PHP Version

8.2.8

### Description

I am going to copy what i already posted in [here](https://github.com/wireui/wireui/issues/707).

I get the following exception when a select is validated, does not meet the validation and so puts the select in red with the validation text 'The x field is required' ('selectModel'=>'required'):

`file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /var/www/vhosts/test.co.uk/test.co.uk/resources/views/&lt;div class=&quot;&quot;&gt; &lt;div class=&quot;relative rounded-md shadow-sm &quot;&gt; &lt;div :class=&quot;{ 'pointer-events-none': config/readonly, 'cursor-pointer': !config/readonly, }&quot;&gt; &lt;template x-if=&quot;!config/multiselect&quot;&gt; &lt;div class=&quot;absolute left-0 inset-y-0 w-[calc(100%-3/5rem)] flex items-center pl-3/5&quot; x-on:click=&quot;toggle&quot;&gt; &lt;span class=&quot;truncate text-sm text-secondary-700 dark:text-secondary-400&quot; x-show=&quot;!isEmpty()&quot; x-html=&quot;getSelectedDisplayText()&quot;&gt; &lt;/span&gt; &lt;/div&gt; &lt;/template&gt; &lt;template x-if=&quot;config/multiselect&quot;&gt; &lt;div class=&quot;absolute inset-y-0 left-0 flex w-full items-center overflow-hidden pl-3 pr-14&quot; x-on:click=&quot;toggle&quot;&gt; &lt;div class=&quot;flex items-center gap-2 overflow-x-auto hide-scrollbar&quot;&gt; &lt;span class=&quot;inline-flex text-sm text-secondary-700 dark:text-secondary-400&quot; x-show=&quot;selectedOptions/length&quot; x-text=&quot;selectedOptions/length&quot;&gt; &lt;/span&gt; &lt;div class=&quot;flex flex-nowrap items-center gap-1&quot; wire:ignore&gt; &lt;template x-for=&quot;(option, index) in selectedOptions&quot; :key=&quot;`selected/${index}`&quot;&gt; &lt;span class=&quot;inline-flex items-center rounded-full border border-secondary-200 bg-secondary-100 py-0/5 pl-2 pr-0/5 text-xs font-medium text-secondary-700 shadow-sm dark:border-none dark:bg-secondary-700 dark:text-secondary-400&quot;&gt; &lt;span class=&quot;truncate&quot; style=&quot;max-width: 5rem&quot; x-text=&quot;option/label&quot;&gt;&lt;/span&gt; &lt;button class=&quot;flex h-4 w-4 shrink-0 items-center justify-center text-secondary-400 hover:text-secondary-500&quot; x-on:click/stop=&quot;unSelect(option)&quot; tabindex=&quot;-1&quot; type=&quot;button&quot;&gt; &lt;svg class=&quot;h-3 w-3&quot; xmlns=&quot;http://www/w3/org/2000/svg&quot; fill=&quot;none&quot; viewBox=&quot;0 0 24 24&quot; stroke=&quot;currentColor&quot;&gt; &lt;path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; stroke-width=&quot;2&quot; d=&quot;M6 18L18 6M6 6l12 12&quot; /&gt; &lt;/svg&gt; &lt;/button&gt; &lt;/span&gt; &lt;/template&gt; &lt;/div&gt; &lt;/div&gt; &lt;/div&gt; &lt;/template&gt; &lt;/div&gt; &lt;input type=&quot;text&quot; autocomplete=&quot;disabled&quot; class=&quot;text-negative-900 dark:text-negative-600 placeholder-negative-300 dark:placeholder-negative-500 border border-negative-300 focus:ring-negative-500 focus:border-negative-500 dark:bg-secondary-800 dark:border-negative-600 form-input block w-full sm:text-sm rounded-md transition ease-in-out duration-100 focus:outline-none shadow-sm pr-8 !dark:text-transparent cursor-pointer overflow-hidden !text-transparent selection:bg-transparent&quot; x-ref=&quot;input&quot; x-on:click=&quot;toggle&quot; x-on:focus=&quot;open&quot; x-on:blur/debounce/750ms=&quot;closeIfNotFocused&quot; x-on:keydown/enter/stop/prevent=&quot;toggle&quot; x-on:keydown/space/stop/prevent=&quot;toggle&quot; x-on:keydown/arrow-down/prevent=&quot;$event/shiftKey || getNextFocusable()/focus()&quot; x-on:keydown/arrow-up/prevent=&quot;getPrevFocusable()/focus()&quot; x-bind:placeholder=&quot;getPlaceholder&quot; x-bind:value=&quot;getSelectedValue&quot; inputmode=&quot;none&quot; name=&quot;person/management_org_id&quot; id=&quot;22056565544999505a408c70e3773d6d&quot; /&gt; &lt;div class=&quot;absolute inset-y-0 right-0 flex items-center gap-x-2 pr-2&quot;&gt; &lt;button x-show=&quot;!isEmpty()&quot; x-on:click=&quot;clear&quot; tabindex=&quot;-1&quot; type=&quot;button&quot; x-cloak&gt; &lt;svg class=&quot;h-4 w-4 text-secondary-400 hover:text-negative-400&quot; xmlns=&quot;http://www/w3/org/2000/svg&quot; fill=&quot;none&quot; viewBox=&quot;0 0 24 24&quot; stroke=&quot;currentColor&quot;&gt; &lt;path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; stroke-width=&quot;2&quot; d=&quot;M6 18L18 6M6 6l12 12&quot; /&gt; &lt;/svg&gt; &lt;/button&gt; &lt;button tabindex=&quot;-1&quot; x-on:click=&quot;toggle&quot; type=&quot;button&quot;&gt; &lt;svg class=&quot;text-negative-400 dark:text-negative-600 h-5 w-5&quot; xmlns=&quot;http://www/w3/org/2000/svg&quot; fill=&quot;none&quot; viewBox=&quot;0 0 24 24&quot; stroke=&quot;currentColor&quot;&gt; &lt;path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; stroke-width=&quot;2&quot; d=&quot;M8 9l4-4 4 4m0 6l-4 4-4-4&quot; /&gt; &lt;/svg&gt; &lt;/button&gt; &lt;/div&gt; &lt;/div&gt; &lt;p class=&quot;mt-2 text-sm text-negative-600&quot;&gt; The management org id field is required/ &lt;/p&gt; &lt;/div&gt;.blade.php`

It happens only in my production server. on localhost works as intended as shown in the picture below:

<img width="661" alt="Screenshot 2023-08-03 at 13 59 21" src="https://github.com/wireui/wireui/assets/50964572/0f7e42df-e2b7-46d0-a040-3daf2dae8511">

**Dependencies**
 "laravel/framework": "^10.10",
 "livewire/livewire": "^2.11",
 "wireui/wireui": "^1.17"

**Desktop:**
 - OS: CentOS Linux
 - Browser: all browsers

I found the same issue [here](https://github.com/laravel/framework/pull/41956), [here](https://github.com/laravel/framework/issues/32254) and [here](https://github.com/wireui/wireui/issues/60) but they do not seem to fix it completely. From what I've seen is not a WireUi problem , its Laravels but it looks they have not fixed it yet. I'll be posting this issue in laravel as well I just want to make this aware cause i know version 2 is coming and in case someone offers a better solution than mine which was to delete the following code from the select component so its not so large:

```
<button tabindex="-1" x-on:click="toggle" type="button">
						<x-dynamic-component
							class="{{ $name && $errors->has($name) ? 'text-negative-400 dark:text-negative-600' : 'text-secondary-400' }} h-5 w-5"
							:component="WireUi::component('icon')" :name="$rightIcon" />
					</button>
```

### Steps To Reproduce

I am using the latest version of laravel with WireUi and livewire version 2. On local environmet it works as intended (i am using Mac M1) but in the production server do not (CentOS Linux), it throws that exception file too large. From my tests it only happens with the select component from WireUi.

**Comment by timacdonald** [comment]
Hey there,

In order to help out with this issue, we will need a minimal reproduction.

```
laravel new bug-report --github="--public"
```

Once you have set this up, please ping this issue and we will re-open and take a look.

**Comment by groxw** [comment]
How to resolve this problem? Ive been dealing with the same issue
