### ISSUE TITLE
Using a different filename for download issue in Chromium browsers

### ISSUE THREAD

**Issue by MJTheOne** [laravel/framework#47944]
### Laravel Version

10.17.1

### PHP Version

8.2.6

### Description

I may be misunderstanding the Laravel Docs about how to rename a downloaded file. But when using this functionality, the Chromium browsers (tested in Chrome and Opera GX) return literally the filename, without extension. But browsers like Firefox and Safari download the file with the new name *and* the extension.

e.g.:
```php
Route::get('/download', function () {
    return response()->download(
        public_path('storage/test.jpg'),
        'newName',
    );
});
```

### Steps To Reproduce

`composer create-project --prefer-dist laravel/laravel test-download`

`php artisan storage:link`

add a test file to the `storage/app/public` directory

edit the web.php and add:
```php
Route::get('/download', function () {
    return response()->download(
        public_path('storage/test.jpg'),
        'newName',
    );
});
```

**Comment by crynobone** [comment]
I believe the fallback name should always contain the extension as indicated in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_response_header_for_the_main_body

However, it does seem that some browser does handle this automatically.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
