### ISSUE TITLE
Eager loading morphTo relations leads to wrong relationship names

### ISSUE THREAD

**Issue by martynaskre** [laravel/framework#47953]
### Laravel Version

10.17.1

### PHP Version

8.1.17

### Database Driver & Version

MariaDB 10.11.2 for macOS 13 on arm64 (Homebrew)

### Description

Lets assume we have two models `User` and `Post`. `Post` model has _morphTo_ relation named `createdBy`, e.g.

```php
public function createdBy(): MorphTo
{
    return $this->morphTo('created_by');
}
```

It is expected that when we eager load `createdBy` relationship, we would have property `createdBy` inside relations array, but instead we get two properties, e.g.

```php
[
    "createdBy" => null
    "created_by" => App\Models\User
]    
```

Based on my testing, if I change _morphTo_ name property to lets say `deleted_by`, the result would change to:

```php
[
    "createdBy" => null
    "deleted_by" => App\Models\User
]    
```

### Steps To Reproduce

1. Clone [https://github.com/martynaskre/laravel-morph-to-bug](https://github.com/martynaskre/laravel-morph-to-bug)
2. Run database migrations and seeders
3. Execute `php artisan test`
4. See the before mentioned bug

**Comment by crynobone** [comment]
This can be fixed by changing the structure using one of the following:

```php
    public function createdBy(): MorphTo
    {
        return $this->morphTo();
    }
```

or

```php
    public function createdBy(): MorphTo
    {
        return $this->morphTo('createdBy');
    }
```

or 

```php
    public function createdBy(): MorphTo
    {
        return $this->morphTo(type: 'created_by_type', id: 'created_by_id');
    }
```
