### ISSUE TITLE
Update to PHP Unit 10.3.0 command artisan test error undefined method numberOfTests

### ISSUE THREAD

**Issue by nathanaelytj** [laravel/framework#47959]
### Laravel Version

10.17.1

### PHP Version

8.2.8

### Description

When running command `php artisan test` at the end of the test error `Call to undefined method PHPUnit\TestRunner\TestResult\TestResult::numberOfTests()` will be thrown.

If test use argument `--filter` like `php artisan test --filter MyTest` then PHP Unit will fail to run and the same `Call to undefined method PHPUnit\TestRunner\TestResult\TestResult::numberOfTests()` will be thrown.

### Steps To Reproduce

1. Create new empty laravel project.
2. Make sure PHP Unit version 10.3.0 is used.
3. Create a new test with any assertion or use the test shipped with laravel skeleton.
4. Run `php artisan test` then error will be thrown.

**Comment by jamband** [comment]
this issue also occurs when running `php artisan dusk` as well.

**Comment by nunomaduro** [comment]
Working on it.

**Comment by nunomaduro** [comment]
Fixed [v7.8.0](https://github.com/nunomaduro/collision/releases/tag/v7.8.0).

**Comment by nathanaelytj** [comment]
> Fixed [v7.8.0](https://github.com/nunomaduro/collision/releases/tag/v7.8.0).

@Mahbubur-rahman-mishal 
I fixed this issue by updating ```nunomaduro/collision``` in **composer.json** to at least version ```"^7.8"```
