### ISSUE TITLE
Incorrect return type in docblock?

### ISSUE THREAD

**Issue by fremantle-matt** [laravel/framework#47966]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

The return type of the `Builder::get()` method is listed as either a `Collection` or `static[]`. Given the method returns `Model::newCollection()`, whose return type is always `Collection`, is it correct to say that `static[]` is a potential option?

Proposal: remove `static[]` as a potential return type in `Builder::get()`.

https://github.com/laravel/framework/blob/fad2aab8486a32f2f6f5d5854a46e07f40f98964/src/Illuminate/Database/Eloquent/Builder.php#L695

### Steps To Reproduce

Review the following line: https://github.com/laravel/framework/blob/fad2aab8486a32f2f6f5d5854a46e07f40f98964/src/Illuminate/Database/Eloquent/Builder.php#L695

**Comment by fremantle-matt** [comment]
(This is causing me lint issues, hence the request)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by FrazerFlanagan** [comment]
https://github.com/laravel/framework/pull/48228
