### ISSUE TITLE
Http `json` method can't get nested array in 10.17.*

### ISSUE THREAD

**Issue by oddvalue** [laravel/framework#47964]
### Laravel Version

10.17.1

### PHP Version

8.1.16

### Description

The `json` method in Request switched from using ParameterBag to InputBag. Aside from that being a different return type, it now means that you can't get an array out of the json request. InputBag will throw an exception if the value is non-scalar.

https://github.com/laravel/framework/commit/25ab9ef34e105e6e135d87fdc5992eb399533444

### Steps To Reproduce

https://github.com/oddvalue/laravel-http-json-bug/

Same test running in v10.16.1 passes and fails on v10.17.1
https://github.com/oddvalue/laravel-http-json-bug/actions/runs/5762323836

**Comment by debuqer** [comment]
**TL;DR**
This is not a framework issue 

Since there was some deprecation in Symfony(deprecated in 5.6 and remove in 6.x) It doesn't work like before, In your TestController use ->all('address') instead of ->get('address')

```php
class TestController extends Controller
{
    public function __invoke(Request $request): void
    {
        $request->json()->all('address');
    }
}
```

More info:
https://github.com/symfony/symfony/issues/44432

**Comment by crynobone** [comment]
We, unfortunately, cannot revert this because of a breaking change in Symfony. Sorry.

**Comment by timacdonald** [comment]
Please note that we don't document the `$request->json()` method. I recommend instead using ht `input` method instead, which does support returning arrays `$request->input('address')`
