### ISSUE TITLE
Call to route behind proxy adds port 0 to URL

### ISSUE THREAD

**Issue by edmandiesamonte** [laravel/framework#47972]
### Laravel Version

10.17.0

### PHP Version

8.2.8

### Description

My setup is Laravel Sail with Caddy added for local https support.

If I set `$proxies = '*'` in TrustProxies.php, URLs generated by `URL::route()` is getting port 0 appended.

![image](https://github.com/laravel/framework/assets/11081512/fd66e639-7c7a-47b6-9aa0-57ec3af0317c)

If I don't set the value for `$proxies`, I always get Invalid Signature error

### Steps To Reproduce

1. Setup Laravel Sail
2. Add Caddy as a docker service
3. Set `$proxies` to `'*'` in TrustProxies.php
4. Generate route via dynamic domain URL pointing to localhost (i.e. `*.localhost.referralplus.dev`)

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jeffochoa** [comment]
I was having the same issue with caddy, fixed by adding the following to the `TrustedProxies::class` middleware:

```
    protected $proxies = ['0.0.0.0', '*'];
```

For disclosure, only tested this solution in the local environment so far. I haven't tested on a production environment yet.

Thanks to [@gergonzalez](https://github.com/gergonzalez) for the tip.

Jeff.
