### ISSUE TITLE
Invalid Lang Facade PHPDoc

### ISSUE THREAD

**Issue by TheArdent** [laravel/framework#48007]
### Laravel Version

9.x+ 

### PHP Version

8.1.10

### Description

The PHPDoc  annotation in _Lang_ facade method _get_ specifies _array|string|null_, but there is no scenario where it returns _array_. _\Illuminate\Translation\Translator_ have same issue

### Steps To Reproduce

```
function getText():string|null
{
   return Lang::get('title');
}
```

**Comment by nunomaduro** [comment]
Thank you for creating this issue - however, there is some scenarios where the return type of that `get` may be an `array`.
