### ISSUE TITLE
Session cookie containing dots does not work, and there is no warning

### ISSUE THREAD

**Issue by billf-pshs** [laravel/framework#48018]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

In my config/session.php, I set the name to "php.connect.sid", viz:
```
'cookie' => 'php.connect.sid'
```

Sessions did not work.  After much debugging, I discovered that the session manager was looking for a cookie called `php_connect_sid`, and not `php.connect.sid`.  Note that the `Set-Cookie:` sent out by the session manager used the cookie name `php.connect.sid`, so Laravel failed to find its own cookie.

I guess one part of the system maps "." in the name to "_", but this is a very obscure rule.  If there's a good reason to disallow "." in session cookie names, then a configuration that breaks this rule should at the very least generate a runtime warning, if not an outright failure.  An assertion failure would do nicely.

I filed this as a bug and not an enhancement, because a perfectly valid cookie name (php.connect.id) does not work, and there is no warning or error message.

### Steps To Reproduce

Configure a session cookie name in the `cookie` variable in `config/session.php` like `foo.bar` in a working project, and notice that sessions don't work, and there is no warning of an "invalid" cookie name.

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/issues/16167#issuecomment-257186898
