### ISSUE TITLE
Breaking change in tests in v10.17.1 regarding console commands

### ISSUE THREAD

**Issue by jkniest** [laravel/framework#48066]
### Laravel Version

>10.17.1

### PHP Version

8.2.8

### Description

Hello,

In this PR #47928 the logic behind the `run` command was changed in the Artisan command.

This update caused my tests to fail.

Currently I have the following test using Pest.

```php
    artisan(UserAddCommand::class, ['email' => 'new@example.com'])
        ->expectsQuestion('What is the name of the new user?', 'Bob Bauer')
        ->expectsQuestion('What is the password of the new user?', 'secret123')
        ->expectsOutputToContain('User created successfully!')
        ->assertOk();
```

This worked fine before the update, but afterwards I am getting the error:

```
Output does not contain "User created successfully."
```

---

The actual console command prints stuff like this using Termwind:

```
        render(
            <<<HTML
    <div class="py-1">
        <div class="px-1 bg-green-600 font-bold">Success</div>
        <em class="ml-1 text-green-600">
            User created successfully.
        </em>
    </div>
HTML
        );
```

**This only happens if more than one test is being executed. One test itself is fine, but as soon as two tests are presend the second one will fail!**

Reverting the change in the `Command.php` class makes my tests green again.

### Steps To Reproduce

1. Copy the code snippets from above into a fresh laravel install  < 10.17.1
2. Run the tests and see that everything is green
3. Update to laravel >= 10.17.1
4. Tests will fail

**Comment by jkniest** [comment]
Also as a follow up, when adding `$this->info` instead of termwind it works again. But it prints the termwind stuff during tests: 

![CleanShot 2023-08-14 at 18 46 40](https://github.com/laravel/framework/assets/15618191/25a65174-fb45-43aa-8821-518d4d6e6a48)

**Comment by driesvints** [comment]
Hey there. I have to say that console output isn't covered by our BC promise. It can totally happen that the text changes during minor or patch releases. 

I do see you assert on `User created successfully!` and the error says `User created successfully.` (notice the exclamation mark difference). 

If it's only the matter of changing the exclamation mark I'd just update your tests. Sorry you got caught with this.
