### ISSUE TITLE
For the validation 

### ISSUE THREAD

**Issue by tszyuloveyou** [laravel/framework#48063]
### Laravel Version

9.19

### PHP Version

8.0.15

### Description

```
public function rules() {
    return [
        "a" => "required_with:b|date",
        "b" => "required_with:a|date",
    ];
}
```
I believe that anyone will also think that if a is empty than b will not be checking the date formal
It should be like nullable / sometimes because a is empty, so, is not required
but on the real, it is not like nullable sometimes, it will keep check date formal
I just can add the nullable / sometimes after than required_with to fix it
but this is not make sense

### Steps To Reproduce

1. add Form Request and set it like:
```
public function rules() {
    return [
        "a" => "required_with:b|date",
        "b" => "required_with:a|date",
    ];
}
```

2. send the form request set a and b fields to empty
3. you will get message like: "The a filed is not a valid date." and "The b filed is not a valid date.".

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by tszyuloveyou** [comment]
I think this submit to StackOverflow will have no reply
and the issuse is by logic and common sense
I don't create the forums

I would like to know that do you thing that required_with function should not be like nullable / sometimes?
and user need on required_with after add nullable / sometimes that is a good idea?
