### ISSUE TITLE
Laravel migration can't change mysql auto increment primary key column type without resorting to raw sql query

### ISSUE THREAD

**Issue by nanaya** [laravel/framework#48072]
### Laravel Version

11.x-dev

### PHP Version

8.2.8

### Database Driver & Version

MySQL 8.0.33

### Description

(only tested with -and probably only relevant for- mysql)

There's currently no syntax to change auto incrementing primary key column datatype (for example from unsigned medium integer to unsigned big integer).

Using `$table->bigIncrements('id')->change();` results in error:

```

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (Connection: mysql, SQL: alter table `post` modify `id` bigint unsigned not null auto_increment primary key)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:795
    791▕         // If an exception occurs when attempting to run a query, we'll format the error
    792▕         // message to include the bindings with SQL, which will make this exception a
    793▕         // lot more helpful to the developer instead of just the database's errors.
    794▕         catch (Exception $e) {
  ➜ 795▕             throw new QueryException(
    796▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    797▕             );
    798▕         }
    799▕     }
```

### Steps To Reproduce

example repository: https://github.com/nanaya/laravel/tree/increment-change

(use mysql database)

(literally just two new migration files as per https://github.com/nanaya/laravel/commit/863ae5e2b0df0b463bc0154c2570f97c002d1ca7 )

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
