### ISSUE TITLE
Session flush removes token

### ISSUE THREAD

**Issue by rklomp** [laravel/framework#48083]
### Laravel Version

10.18.0

### PHP Version

8

### Description

I experienced unexpected 419 http errors when running a `$request->session()->flush()`.
If a user clicked a link twice without the first request fully loaded, the second request would return error 419.

After some digging it turns out the token is also stored in the same array and thus `flush()` also [removes](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Session/Store.php#L542) the `_token`. The first request would change the `_token` and thus the second request still using the old token will fail.

[Session documentation](
https://laravel.com/docs/10.x/session#deleting-data) does not mention `flush()` will cause a token regeneration.

Is this by design? 
If so, I guess it should be more clear in the documentation.
If not, can we keep `_token` while running `flush()`? Or a new function to only flush non `_`-prefixed items.

### Steps To Reproduce

Run `$request->session()->flush()`

**Comment by crynobone** [comment]
Hi there,

I feel it should be expected for `flush()` to clear everything including `_token`. Feel free to submit a PR to documentation if you feel the wording can be clearer.
