### ISSUE TITLE
Memory leak when using TaggableStore with flush method

### ISSUE THREAD

**Issue by mattford** [laravel/framework#48098]
### Laravel Version

9.52.10

### PHP Version

8.1.22

### Description

When using the `tags` method on a cache store in order to namespace certain tagged items, a memory leak occurs if the `flush()` method is called on the taggable store. 

This appears to occur because when the TaggableStore flushes, it does so by resetting the ids used in the tag namespace, meaning attempts to retrieve the data will now result in a cache miss. However, the cached data is left in place indefinitely and cannot be accessed as the tag ids have now been replaced.

As the Store interface does not expose a way of seeing all possible cache keys, the only  fix for this I can think of for this is to have the TaggableStore keep track of the keys within it's namespace, and have it `forget()` them when flush is called.

### Steps To Reproduce

The following code snippet will show a steadily increasing amount of memory in use:

```
$store = cache()->store('array')->tags(['test']);
while (true) {
    $store->flush();
    $key = str_replace('.', '', uniqid());
    $store->set($key, uniqid());
    echo memory_get_usage(true) . PHP_EOL;
}
```

However I would expect all cache values to be cleared on calling `flush()` and therefore the memory use remain steady.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by mattford** [comment]
Will try to reproduce with latest, thanks

**Comment by mattford** [comment]
Was able to reproduce with 10.x so opened https://github.com/laravel/framework/issues/48100
