### ISSUE TITLE
Validator `after` hook ignores `$stopOnFirstFailure` 

### ISSUE THREAD

**Issue by amshehzad** [laravel/framework#48094]
### Laravel Version

10.16.1

### PHP Version

8.1.2

### Description

I'm using a FormRequest and have defined some validation logic in `after` hook. the validation logic depends on one of the required field within the request. so I've set to `$stopOnFirstFailure` to true to make sure that the validation logic should have the valid request data but the validator calls the invokable validation class even there are validation errors in the request. 

### Steps To Reproduce

```
$validator = Validator::make(
    [
        'foo' => 'bar',
        'bar' => 'foo',
    ],
    [
        'foo' => 'integer',
        'bar' => 'integer',
    ]
);

$validator->stopOnFirstFailure();

$validator->after([
   function($validator){
        dd('it should not run');
   }
]);

$validator->validate();
```

this should not call the after hook, as the initial validation is failing.

**Comment by driesvints** [comment]
Heya. This is not how current things work. The after hook is called regardless of the stopOnFirstFailure.

**Comment by amshehzad** [comment]
Perhaps we can add a second bool parameter to the `after` hook to only run the hook if the main validation passes?
