### ISSUE TITLE
Merging Enum to Request throws Expected a scalar, or an array as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::set()

### ISSUE THREAD

**Issue by digvijayad** [laravel/framework#48110]
### Laravel Version

10.19

### PHP Version

8.2.9

### Description

After upgrade to 10.19 from 10.16 the app throws exception when merging Enum to FormRequest object. 

```php
 public function initiateTransaction(CreateTransactionRequest $request): JsonResponse
    {
        $request->merge([
            'status' => TransactionStatus::Initiated,
        ]);
    }
```

```powershell

InvalidArgumentException: Expected a scalar, or an array as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::set()", "App\Enums\TransactionStatus" given. in E:\source\src\laravel10\vendor\symfony\http-foundation\InputBag.php:70
```

### Steps To Reproduce

1. Create a new FormRequest object.
2. In the Controller, merge an enum with form request object.
```php
$request->merge([
            'status' => TransactionStatus::Initiated,
        ]);
```

**Comment by crynobone** [comment]
Unfortunately there was a breaking change in Symfony which made us implement #47838. So this will probably stay, sorry.

**Comment by nea** [comment]
Ahoy @crynobone , but what would be the solution?

I have a form request validation `'type' => [new Enum(UPType::class)],` which triggers this issue, too. So, no Enum Validation usable?

Thanks

**Comment by Babaktrad** [comment]
+1
