### ISSUE TITLE
Date validation not properly validating.

### ISSUE THREAD

**Issue by rklomp** [laravel/framework#48121]
### Laravel Version

10.18.0

### PHP Version

8.2.8

### Description

```php
$validated = $request->validate([
    'my_date' => 'required|date',
]);
```
```html
<input type="date" name="my_date">
```

Tested in both Edge and Firefox. Browser allows to set a year of 5 characters.
This is passed to [validator](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L533) and accepted as a valid date.

### Steps To Reproduce

For example:
```php
<?php
$date = date_parse("19999-02-01");
var_dump(checkdate($date['month'], $date['day'], $date['year']));
var_dump($date);

//result:
bool(true)
array(12) {
  ["year"]=>
  int(2009)
  ["month"]=>
  int(2)
  ["day"]=>
  int(1)
  ["hour"]=>
  bool(false)
  ["minute"]=>
  bool(false)
  ["second"]=>
  bool(false)
  ["fraction"]=>
  bool(false)
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(0)
  ["errors"]=>
  array(0) {
  }
  ["is_localtime"]=>
  bool(false)
}
```

**Comment by crynobone** [comment]
You can add additional regex as the `date` validation rely on `strtotime` PHP functions as mention in the documentation.
