### ISSUE TITLE
Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:65

### ISSUE THREAD

**Issue by emireadcode** [laravel/framework#48120]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

I am a newbie to Laravel and I am trying to install to get started so I ran the following command below

    composer global require laravel/installer

but it turns out to be failing with error that reads Normalizer not found. The console output is here below

    Changed current directory to /home/margaret/.config/composer
Using version ^5.0 for laravel/installer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 17 installs, 0 updates, 0 removals
  - Downloading illuminate/conditionable (v10.19.0)
  - Downloading psr/simple-cache (3.0.0)
  - Downloading psr/container (2.0.2)
  - Downloading illuminate/contracts (v10.19.0)
  - Downloading illuminate/macroable (v10.19.0)
  - Downloading symfony/process (v6.3.2)
  - Downloading symfony/polyfill-mbstring (v1.27.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.27.0)
  - Downloading symfony/polyfill-intl-grapheme (v1.27.0)
  - Downloading symfony/polyfill-ctype (v1.27.0)
  - Downloading symfony/string (v6.3.2)
  - Downloading symfony/service-contracts (v3.3.0)
  - Downloading symfony/deprecation-contracts (v3.3.0)
  - Downloading symfony/console (v6.3.2)
  - Downloading illuminate/collections (v10.19.0)
  - Downloading laravel/prompts (v0.1.5)
  - Downloading laravel/installer (v5.0.3)

Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:65
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width('17')
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps(17)
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start(17)
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait(Array, Object(Symfony\Component\Console\Helper\ProgressBar))
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises(Array)
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#9 /usr/share/php/Composer/Command/RequireCommand.php(430): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/RequireCommand.php(285): Composer\Command\RequireCommand->doUpdate(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Composer\IO\ConsoleIO), Array, 'require', 'require-dev')
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\RequireCommand), Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /usr/share/php/Composer/Command/GlobalCommand.php(119): Composer\Console\Application->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /usr/share/php/Symfony/Component/Console/Application.php(1015): Composer\Command\GlobalCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\GlobalCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /usr/bin/composer(84): Composer\Console\Application->run()
#24 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 65

Even when I tried to install laravel with the following command below

    composer create-project --prefer-dist laravel/laravel vue-advance-search-sort-filter-backend-api

I have the following error below

    Creating a "laravel/laravel" project at "./vue-advance-search-sort-filter-backend-api"
Installing laravel/laravel (v10.2.6)
  - Installing laravel/laravel (v10.2.6): Extracting archive
Created project in /home/margaret/Node/vue-advance-search-sort-filter/backend/Laravel/RestAPI/vue-advance-search-sort-filter-backend-api
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies
Lock file operations: 110 installs, 0 updates, 0 removals
  - Locking brick/math (0.11.0)
  - Locking dflydev/dot-access-data (v3.0.2)
  - Locking doctrine/inflector (2.0.8)
  - Locking doctrine/lexer (3.0.0)
  - Locking dragonmantank/cron-expression (v3.3.3)
  - Locking egulias/email-validator (4.0.1)
  - Locking fakerphp/faker (v1.23.0)
  - Locking filp/whoops (2.15.3)
  - Locking fruitcake/php-cors (v1.2.0)
  - Locking graham-campbell/result-type (v1.1.1)
  - Locking guzzlehttp/guzzle (7.7.0)
  - Locking guzzlehttp/promises (2.0.1)
  - Locking guzzlehttp/psr7 (2.6.0)
  - Locking guzzlehttp/uri-template (v1.0.1)
  - Locking hamcrest/hamcrest-php (v2.0.1)
  - Locking laravel/framework (v10.19.0)
  - Locking laravel/pint (v1.11.0)
  - Locking laravel/prompts (v0.1.5)
  - Locking laravel/sail (v1.23.4)
  - Locking laravel/sanctum (v3.2.5)
  - Locking laravel/serializable-closure (v1.3.1)
  - Locking laravel/tinker (v2.8.1)
  - Locking league/commonmark (2.4.0)
  - Locking league/config (v1.2.0)
  - Locking league/flysystem (3.15.1)
  - Locking league/flysystem-local (3.15.0)
  - Locking league/mime-type-detection (1.13.0)
  - Locking mockery/mockery (1.6.6)
  - Locking monolog/monolog (3.4.0)
  - Locking myclabs/deep-copy (1.11.1)
  - Locking nesbot/carbon (2.69.0)
  - Locking nette/schema (v1.2.4)
  - Locking nette/utils (v4.0.1)
  - Locking nikic/php-parser (v4.17.1)
  - Locking nunomaduro/collision (v7.8.1)
  - Locking nunomaduro/termwind (v1.15.1)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.2.1)
  - Locking phpoption/phpoption (1.9.1)
  - Locking phpunit/php-code-coverage (10.1.3)
  - Locking phpunit/php-file-iterator (4.0.2)
  - Locking phpunit/php-invoker (4.0.0)
  - Locking phpunit/php-text-template (3.0.0)
  - Locking phpunit/php-timer (6.0.0)
  - Locking phpunit/phpunit (10.3.2)
  - Locking psr/clock (1.0.0)
  - Locking psr/container (2.0.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-client (1.0.2)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (2.0)
  - Locking psr/log (3.0.0)
  - Locking psr/simple-cache (3.0.0)
  - Locking psy/psysh (v0.11.20)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking ramsey/collection (2.0.0)
  - Locking ramsey/uuid (4.7.4)
  - Locking sebastian/cli-parser (2.0.0)
  - Locking sebastian/code-unit (2.0.0)
  - Locking sebastian/code-unit-reverse-lookup (3.0.0)
  - Locking sebastian/comparator (5.0.1)
  - Locking sebastian/complexity (3.0.0)
  - Locking sebastian/diff (5.0.3)
  - Locking sebastian/environment (6.0.1)
  - Locking sebastian/exporter (5.0.0)
  - Locking sebastian/global-state (6.0.1)
  - Locking sebastian/lines-of-code (2.0.0)
  - Locking sebastian/object-enumerator (5.0.0)
  - Locking sebastian/object-reflector (3.0.0)
  - Locking sebastian/recursion-context (5.0.0)
  - Locking sebastian/type (4.0.0)
  - Locking sebastian/version (4.0.1)
  - Locking spatie/backtrace (1.5.3)
  - Locking spatie/flare-client-php (1.4.2)
  - Locking spatie/ignition (1.9.0)
  - Locking spatie/laravel-ignition (2.2.0)
  - Locking symfony/console (v6.3.2)
  - Locking symfony/css-selector (v6.3.2)
  - Locking symfony/deprecation-contracts (v3.3.0)
  - Locking symfony/error-handler (v6.3.2)
  - Locking symfony/event-dispatcher (v6.3.2)
  - Locking symfony/event-dispatcher-contracts (v3.3.0)
  - Locking symfony/finder (v6.3.3)
  - Locking symfony/http-foundation (v6.3.2)
  - Locking symfony/http-kernel (v6.3.3)
  - Locking symfony/mailer (v6.3.0)
  - Locking symfony/mime (v6.3.3)
  - Locking symfony/polyfill-ctype (v1.27.0)
  - Locking symfony/polyfill-intl-grapheme (v1.27.0)
  - Locking symfony/polyfill-intl-idn (v1.27.0)
  - Locking symfony/polyfill-intl-normalizer (v1.27.0)
  - Locking symfony/polyfill-mbstring (v1.27.0)
  - Locking symfony/polyfill-php72 (v1.27.0)
  - Locking symfony/polyfill-php80 (v1.27.0)
  - Locking symfony/polyfill-php83 (v1.27.0)
  - Locking symfony/polyfill-uuid (v1.27.0)
  - Locking symfony/process (v6.3.2)
  - Locking symfony/routing (v6.3.3)
  - Locking symfony/service-contracts (v3.3.0)
  - Locking symfony/string (v6.3.2)
  - Locking symfony/translation (v6.3.3)
  - Locking symfony/translation-contracts (v3.3.0)
  - Locking symfony/uid (v6.3.0)
  - Locking symfony/var-dumper (v6.3.3)
  - Locking symfony/yaml (v6.3.3)
  - Locking theseer/tokenizer (1.2.1)
  - Locking tijsverkoyen/css-to-inline-styles (2.2.6)
  - Locking vlucas/phpdotenv (v5.5.0)
  - Locking voku/portable-ascii (2.0.1)
  - Locking webmozart/assert (1.11.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 110 installs, 0 updates, 0 removals
  - Downloading doctrine/inflector (2.0.8)
  - Downloading doctrine/lexer (3.0.0)
  - Downloading symfony/polyfill-ctype (v1.27.0)
  - Downloading webmozart/assert (1.11.0)
  - Downloading dragonmantank/cron-expression (v3.3.3)
  - Downloading symfony/deprecation-contracts (v3.3.0)
  - Downloading psr/container (2.0.2)
  - Downloading fakerphp/faker (v1.23.0)
  - Downloading symfony/polyfill-php80 (v1.27.0)
  - Downloading symfony/polyfill-php83 (v1.27.0)
  - Downloading symfony/polyfill-mbstring (v1.27.0)
  - Downloading symfony/http-foundation (v6.3.2)
  - Downloading fruitcake/php-cors (v1.2.0)
  - Downloading psr/http-message (2.0)
  - Downloading psr/http-client (1.0.2)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading psr/http-factory (1.0.2)
  - Downloading guzzlehttp/psr7 (2.6.0)
  - Downloading guzzlehttp/promises (2.0.1)
  - Downloading guzzlehttp/guzzle (7.7.0)
  - Downloading guzzlehttp/uri-template (v1.0.1)
  - Downloading laravel/pint (v1.11.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.27.0)
  - Downloading symfony/polyfill-intl-grapheme (v1.27.0)
  - Downloading symfony/string (v6.3.2)
  - Downloading symfony/service-contracts (v3.3.0)
  - Downloading symfony/console (v6.3.2)
  - Downloading voku/portable-ascii (2.0.1)
  - Downloading phpoption/phpoption (1.9.1)
  - Downloading graham-campbell/result-type (v1.1.1)
  - Downloading vlucas/phpdotenv (v5.5.0)
  - Downloading symfony/css-selector (v6.3.2)
  - Downloading tijsverkoyen/css-to-inline-styles (2.2.6)
  - Downloading symfony/var-dumper (v6.3.3)
  - Downloading symfony/polyfill-uuid (v1.27.0)
  - Downloading symfony/uid (v6.3.0)
  - Downloading symfony/routing (v6.3.3)
  - Downloading symfony/process (v6.3.2)
  - Downloading symfony/polyfill-php72 (v1.27.0)
  - Downloading symfony/polyfill-intl-idn (v1.27.0)
  - Downloading symfony/mime (v6.3.3)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v3.3.0)
  - Downloading symfony/event-dispatcher (v6.3.2)
  - Downloading psr/log (3.0.0)
  - Downloading egulias/email-validator (4.0.1)
  - Downloading symfony/mailer (v6.3.0)
  - Downloading symfony/error-handler (v6.3.2)
  - Downloading symfony/http-kernel (v6.3.3)
  - Downloading symfony/finder (v6.3.3)
  - Downloading ramsey/collection (2.0.0)
  - Downloading brick/math (0.11.0)
  - Downloading ramsey/uuid (4.7.4)
  - Downloading psr/simple-cache (3.0.0)
  - Downloading nunomaduro/termwind (v1.15.1)
  - Downloading symfony/translation-contracts (v3.3.0)
  - Downloading symfony/translation (v6.3.3)
  - Downloading psr/clock (1.0.0)
  - Downloading nesbot/carbon (2.69.0)
  - Downloading monolog/monolog (3.4.0)
  - Downloading league/mime-type-detection (1.13.0)
  - Downloading league/flysystem (3.15.1)
  - Downloading league/flysystem-local (3.15.0)
  - Downloading nette/utils (v4.0.1)
  - Downloading nette/schema (v1.2.4)
  - Downloading dflydev/dot-access-data (v3.0.2)
  - Downloading league/config (v1.2.0)
  - Downloading league/commonmark (2.4.0)
  - Downloading laravel/serializable-closure (v1.3.1)
  - Downloading laravel/prompts (v0.1.5)
  - Downloading laravel/framework (v10.19.0)
  - Downloading symfony/yaml (v6.3.3)
  - Downloading laravel/sail (v1.23.4)
  - Downloading laravel/sanctum (v3.2.5)
  - Downloading nikic/php-parser (v4.17.1)
  - Downloading psy/psysh (v0.11.20)
  - Downloading laravel/tinker (v2.8.1)
  - Downloading hamcrest/hamcrest-php (v2.0.1)
  - Downloading mockery/mockery (1.6.6)
  - Downloading filp/whoops (2.15.3)
  - Downloading nunomaduro/collision (v7.8.1)
  - Downloading sebastian/version (4.0.1)
  - Downloading sebastian/type (4.0.0)
  - Downloading sebastian/recursion-context (5.0.0)
  - Downloading sebastian/object-reflector (3.0.0)
  - Downloading sebastian/object-enumerator (5.0.0)
  - Downloading sebastian/global-state (6.0.1)
  - Downloading sebastian/exporter (5.0.0)
  - Downloading sebastian/environment (6.0.1)
  - Downloading sebastian/diff (5.0.3)
  - Downloading sebastian/comparator (5.0.1)
  - Downloading sebastian/code-unit (2.0.0)
  - Downloading sebastian/cli-parser (2.0.0)
  - Downloading phpunit/php-timer (6.0.0)
  - Downloading phpunit/php-text-template (3.0.0)
  - Downloading phpunit/php-invoker (4.0.0)
  - Downloading phpunit/php-file-iterator (4.0.2)
  - Downloading theseer/tokenizer (1.2.1)
  - Downloading sebastian/lines-of-code (2.0.0)
  - Downloading sebastian/complexity (3.0.0)
  - Downloading sebastian/code-unit-reverse-lookup (3.0.0)
  - Downloading phpunit/php-code-coverage (10.1.3)
  - Downloading phar-io/version (3.2.1)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading myclabs/deep-copy (1.11.1)
  - Downloading phpunit/phpunit (10.3.2)
  - Downloading spatie/backtrace (1.5.3)
  - Downloading spatie/flare-client-php (1.4.2)
  - Downloading spatie/ignition (1.9.0)
  - Downloading spatie/laravel-ignition (2.2.0)

Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:65
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width('110')
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps(110)
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start(110)
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait(Array, Object(Symfony\Component\Console\Helper\ProgressBar))
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises(Array)
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#9 /usr/share/php/Composer/Command/CreateProjectCommand.php(271): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/CreateProjectCommand.php(168): Composer\Command\CreateProjectCommand->installProject(Object(Composer\IO\ConsoleIO), Object(Composer\Config), Object(Symfony\Component\Console\Input\ArgvInput), 'laravel/laravel', 'vue-advance-sea...', NULL, NULL, false, true, true, NULL, false, false, false, false, Object(Composer\Filter\PlatformRequirementFilter\IgnoreNothingPlatformRequirementFilter), true, false)
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\CreateProjectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\CreateProjectCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /usr/bin/composer(84): Composer\Console\Application->run()
#18 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 65

I've installed php-intl yet it is not working and i truly want to get started as soon as possible.

Please I need help on how to fix this issue.
    

### Steps To Reproduce

__ 
Run either of the following commands

    composer create-project --prefer-dist laravel/laravel vue-advance-search-sort-filter-backend-api

   
    composer global require laravel/installer

**Comment by crynobone** [comment]
Can you share the value of the following command:

```bash
composer diagnose
```

**Comment by emireadcode** [comment]
The installation finally worked after I uninstalled the composer and reinstalled an up-to-date composer version.

**Comment by saimram** [comment]
hi i am seeing hte same issue of class normalizer.
composer diagnose giving below information
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 2.2.6
PHP version: 8.1.27
PHP binary path: /usr/bin/php8.1
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
cURL version: 7.81.0 libz 1.2.11 ssl OpenSSL/3.0.2
zip: extension present, unzip present, 7-Zip not available

Any help please..

**Comment by fiamon** [comment]
@saimram for fix this error, you should do the same as emireadcode. For me, the error started when i tried to install composer with: sudo apt-get composer or sudo snap install composer, but it doesnt matter. You need to uninstall your composer and reinstall it from the website.
