### ISSUE TITLE
Bug with trans_choice and replacement parameters containing pipes

### ISSUE THREAD

**Issue by reneroth** [laravel/framework#48127]
### Laravel Version

8.83.16 && 10.0

### PHP Version

7.4.33 && 8.2.7

### Description

Strange bug that from my understanding of the source code should not happen, but I confirmed it is present in both Laravel 8 and 10. This is especially puzzling as `Translator::choice` from my understanding does the selection prior to and independent of any localization parameter replacement. It does not matter if I'm using the default translation files or directly passing the translation template as `$key` paremter.

### Steps To Reproduce

`trans_choice(':user gave you a foo.|:user gave you :count foos.', 1, ['user' => 'Pro-Gamer']);`  
-> correct output `'Pro-Gamer gave you a foo.'`

`trans_choice(':user gave you a foo.|:user gave you :count foos.', 2, ['user' => 'Pro-Gamer']);`  
-> correct output `'Pro-Gamer gave you 2 foos.'`

`trans_choice(':user gave you a foo.|:user gave you :count foos.', 1, ['user' => 'Pro|Gamer']);`  
-> incorrect output `'Pro'`

`trans_choice(':user gave you a foo.|:user gave you :count foos.', 2, ['user' => 'Pro|Gamer']);`  
-> incorrect output `'Gamer gave you a foo.`

**Comment by reneroth** [comment]
I've dug deeper into the source code, and the issue is indeed that `Translator::get` already calls `makeReplacements`, adding a pipe symbol and throwing off `MessageSelector::choose`.

**Comment by driesvints** [comment]
The Translator unfortunately cannot handle these sort of pipes when also present in replacements. I suggest you don't use these in replacements values, sorry.

**Comment by reneroth** [comment]
I humbly request that this ticket stays open. This seems to be an obvious bug that could definitely be fixed, but at least needs to be documented, as developers need to be aware that user input breaks this common method. I am well aware that I am not entitled to any free labour, but closing this ticket effectively prevents a solution from ever being implemented, including by me - no contributor wants to put time and effort into a PR that goes nowhere.

**Comment by rudiedirkx** [comment]
Woooow this is weird. Laravel translator can't handle pipes? And that's acceptable?? Replacements are very often user input, not hard-coded. Should we tell users "please don't use pipes in your internet, we can't handle those"? 😮

Isn't the fix very simple? **First** choose the string, **then** replace the params.

**Comment by rudiedirkx** [comment]
I think this is all...

```diff
    public function choice($key, $number, array $replace = [], $locale = null)
    {
        $line = $this->get(
-           $key, $replace, $locale = $this->localeForChoice($locale)
+           $key, [], $locale = $this->localeForChoice($locale)
        );

```

**Comment by reneroth** [comment]
Oh yeah, this issue 😀 I think we just solved it for us by doing some very ugly placeholder replacement hacks around it.

Half-serious and half-joking: I am unable to take the boasts of how little open issues there are in the Laravel repos as serious as I did before. The way these kind of bug reports are currently handled can easily be automated with an LLM 😜

As for @rudiedirkx - you can try just putting in a PR. If it’s a small diff, you might get lucky and it’ll be merged - worked for me once with a different bug.

also see #34777 
also see https://twitter.com/taylorotwell/status/1256031217943818242

**Comment by rudiedirkx** [comment]
> I am unable to take the boasts of how little open issues there are in the Laravel repos as serious as I did before.

Right?? 😢

I'm using `cweagans/composer-patches` to patch Laravel core a few times. I don't want to fight about very useful PR anymore. Some of them got it, some of them didn't, I make it work for me. OSS is exhausting.

This one seems truly silly though. How is "pipes don't work, sorry" acceptable? That's like saying "please don't SQL inject us, we don't handle quotes well".
