### ISSUE TITLE
Inconsistent Effect of Dispatched Event When Using expectEvent Assertion

### ISSUE THREAD

**Issue by kazemmdev** [laravel/framework#48148]
### Laravel Version

9.36

### PHP Version

8.1

### Database Driver & Version

MySQL8

### Description

I encountered a possible bug related to the usage of the expectEvent assertion in Laravel 9. When testing a simple payment process that involves dispatching an event and updating payment status, I observed that the desired event is dispatched successfully. However, when using the expectEvent assertion to check for the dispatched event, the test passes without any errors, but the effects of running the dispatched event cannot be verified. 

## Expected Behavior:
The expectEvent assertion should verify the dispatching of the event and allow verification of the effects of running the dispatched event, such as the updated payment status.

## Actual Behavior:
When using the expectEvent assertion, the test passes without any errors. However, the effects of running the dispatched event cannot be verified. The updated payment status or other expected changes are not reflected.

### Steps To Reproduce

- Set up a Laravel 9 application.

- Create a test case for the payment process:

```php
   /** @test */
   public function it_grants_the_user_access_to_the_purchased_product()
   {
      $this->mockPaymentService();
      $this->be(User::factory()->create(), 'api');
      $this->expectsEvents(SubscriptionSuccessEvent::class);

      $product = Product::first();
      $this->assertNotEmpty($product);
      $this->post('api/transactions', ['product_id' => $product->id])->assertOk();

      $transaction = auth()->user()->transactions()->first();
      $this->assertNotEmpty($transaction);
      $this->patch('api/transactions/' . $transaction->id)->assertOk();

      $this->assertEquals('paid', $transaction->fresh()->status);
   }
```

In the code provided, I observed that removing the `expectsEvents` method resolves the issue and the functionality works correctly. However, when reintroducing the expectsEvents method and using the `assertEquals` assertion, the test fails. This indicates that the event responsible for updating the transaction status is not being properly evaluated.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
Also, it might be best to migrate to Event fake instead of using deprecated testing methods

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Testing/Concerns/MocksApplicationServices.php

**Comment by kazemmdev** [comment]
Thank you, @crynobone After reviewing the link you provided, I discovered that when we utilize `expectsEvents` in our tests, it mocks the event dispatcher, causing all events to be muted.
