### ISSUE TITLE
Postgres with multiple schema migrate:fresh not dropping tables

### ISSUE THREAD

**Issue by localusercamp** [laravel/framework#48145]
### Laravel Version

10.20

### PHP Version

8.2

### Database Driver & Version

PostgreSQL | psql (PostgreSQL) 15.1 (Ubuntu 15.1-1.pgdg20.04+1)

### Description

I want to create a multi-schema database to separate my tables.

`php artisan migrate` command works fine for empty database with empty `public` schema.

But `php artisan migrate:fresh` command fails with error:
```
 Illuminate\Database\QueryException

  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "users" already exists (Connection: pgsql, SQL: create table "common"."users" ("id" bigserial not null primary key, "login" varchar(320) not null, "ugraid_login" varchar(255) null, "password" varchar(60) not null, "first_name" varchar(255) null, "last_name" varchar(255) null, "patronymic" varchar(255) null, "remember_token" varchar(100) null, "email_verified_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))
```

From `migrate:fresh --help`
>Description:
  Drop all tables and re-run all migrations

Seems like it not dropping tables, because i wrote a little of dumps at the start of my `up()` migration function and found that table exists.
![image](https://github.com/laravel/framework/assets/45385480/2144d7e1-29da-4b38-83e0-c8f0d44428d2)

`php artisan migrate:fresh` output with dumps:
![image](https://github.com/laravel/framework/assets/45385480/699c20a7-b094-4787-9a4a-c48edaeeb6e1)

### Steps To Reproduce

1. Fresh Laravel app.
2. Migration for schema creation. Simply `DB::statement('CREATE SCHEMA common')`.
3. Migration for schema-scoped model. Simply `Schema::create('common.users', function (Blueprint $table) { ... })`. 
4. `php artisan migrate` works fine.
5. `php artisan migrate:fresh` after `php artisan migrate` fails.

**Comment by localusercamp** [comment]
From screenshots you may see that it fails only on schema-scoped migrations.
These migrations has no schema in their definition so they passed through the `migrate:fresh`: 
- failed_jobs
- password_resets
- sessions

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
You can fixed the issue by editing `config/database.php`:

```php
'search_path' => ['public', 'common'],
```

Or use `php artisan migrate:refresh` instead.

**Comment by localusercamp** [comment]
Thank you for your solution, it works perfectly!

What do you think about creation of Postgres schema auto-resolution mechanism for simplifying this behaviour?

In my opinion it is too verbose to manually set this in configuration file.

It may look something like this:
```php
'search_path' => '*',
```

Is it possible @crynobone ?
