### ISSUE TITLE
$model->getDirty() returns empty array when $afterCommit is set to true on observers.

### ISSUE THREAD

**Issue by nadirabbas** [laravel/framework#48154]
### Laravel Version

9.19

### PHP Version

8.1.12

### Description

When listening for `updated` events in listeners that have the public property `$afterCommit` set to true, the dirty columns are lost.

### Steps To Reproduce

- Create a Model
- Create an Observer for the Model and set $afterCommit to true
- Create a Model instance and persist it to the database
- Update this new record inside a transaction and commit it to the database
- Register a listener for update events on the observer and inspect the $model->getDirty()  function
- The function should return an empty array even if you had actually updated a column

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by likemusic** [comment]
Maybe `wasChanged()` would help.

![image](https://github.com/laravel/framework/assets/603401/9949fbb9-6cca-4bf6-8aa3-bf3bfd5a76f7)
From https://stackoverflow.com/a/49350664
