### ISSUE TITLE
Illuminate\Http\Request json() method should return ParameterBag

### ISSUE THREAD

**Issue by aiwozhe** [laravel/framework#48165]
### Laravel Version

10.17.0

### PHP Version

8.1.22

### Description

Illuminate\Http\Request json() method should return ParameterBag.Otherwise, an error will be reported when a value in JSON is an array or an object

### Steps To Reproduce

Otherwise, an error will be reported when a value in JSON is an array or an object

**Comment by driesvints** [comment]
We can't do this because of a breaking change in Symfony sorry.
