### ISSUE TITLE
Cant add headers to abort 404

### ISSUE THREAD

**Issue by BasvanH** [laravel/framework#48168]
### Laravel Version

9.42.2

### PHP Version

8.1.2

### Description

Cant add **$headers** to abort(404, "message", $headers) because in `Illuminate\Foundation\Application` there's an exception made to route a 404 to `NotFoundHttpException` but they forgot to add the headers.

```
public function abort($code, $message = '', array $headers = [])
{
    if ($code == 404) {
        throw new NotFoundHttpException($message);
    }

    throw new HttpException($code, $message, null, $headers);
}
```

This looks like an oversight, already spotted [here](https://github.com/laravel/framework/issues/30613).

Could this be fixed! Thanks!

### Steps To Reproduce

abort(404, "message", $headers) wont produce a response with the added headers.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
