### ISSUE TITLE
Using Castable with CastsAttributes on a value object, is flattening the attributes array on the model

### ISSUE THREAD

**Issue by kirkbushell** [laravel/framework#48176]
### Laravel Version

10.10

### PHP Version

8.2.9

### Database Driver & Version

MYSQL

### Description

Encountered a weird one here, code below:

```php
abstract class Credentials implements Arrayable, Castable
{
    public static function castUsing(array $arguments): CastsAttributes
    {
        return new class implements CastsAttributes
        {
            public function get(Model $model, string $key, mixed $value, array $attributes): Credentials
            {
                return Credentials::factory($model->mechanism, $value);
            }

            public function set(Model $model, string $key, mixed $value, array $attributes): array
            {
                if (!($value instanceof Credentials)) {
                    throw new \InvalidArgumentException('Provided credentials must be an implementation of Credentials class.');
                }

                return $value->toArray();
            }
        };
    }

    static public function factory(string $mechanism, \stdClass $value): Credentials
    {
        return new EmailCredentials($value->email, $value->password);
    }
}

class EmailCredentials extends Credentials
{
    public function __construct(private string $email, private string $password) {}

    public function toArray(): array
    {
        return [
            'email' => hash('SHA512', $this->email),
            'password' => Hash::make($this->password),
        ];
    }
}

```

I'll explain the class first. I'm testing out the possibility of setting up authenticators as its own table. Each authenticator has a type of credentials (email and password, email only, facebook.etc.)

The abstract credentials class manages the casting of those attributes from the children of Credentials.

Everything is working fine, however - I find that the set method (from the docs) is actually returning the array to the base $attributes property on the model, rather than keeping it as part of the credentials property.

### Steps To Reproduce

Setup a value object htat imkplements Castable, returning a CastsAttributes implementation.

Have the set method return an array as per normal. You'll see that the array is flatted on the model.

**Comment by kirkbushell** [comment]
I found the issue - it's in setClassCastableAttribute. On line 1134:

```php
$this->attributes = array_replace(
    $this->attributes,
    $this->normalizeCastClassResponse($key, $caster->set(
        $this, $key, $value, $this->attributes
    ))
);
```

It's my understanding that my credentials property should be setting the 'credentials' key, not merging it's result with the the main model attributes array.

**Comment by rodrigopedra** [comment]
```php
public function set(Model $model, string $key, mixed $value, array $attributes): array
{
    if (!($value instanceof Credentials)) {
        throw new \InvalidArgumentException('Provided credentials must be an implementation of Credentials class.');
    }
    
    // if $key is always credentials, try
    // return ['credentials => $value->toArray()];
    return [$key => $value->toArray()];
}
```

If you return an array like that, Laravel will understand you want to set multiple attributes, as the code sample in the docs which decodes an Address into `address_line_one` and `address_line_two` attributes.

reference: https://laravel.com/docs/10.x/eloquent-mutators#value-object-casting

There is a note in the docs of cases like yours, but the value object being encoded should implement both `Illuminate\Contracts\Support\Arrayable` **AND** `JsonSerializable` interfaces. (*and* in uppercase and bold to highlight that requirement

In your case, you could try this:

```php
abstract class Credentials implements Arrayable, Castable, \JsonSerializable
{
    public static function castUsing(array $arguments): CastsAttributes
    {
        return new class implements CastsAttributes
        {
            public function get(Model $model, string $key, mixed $value, array $attributes): Credentials
            {
                return Credentials::factory($model->mechanism, $value);
            }

            public function set(Model $model, string $key, mixed $value, array $attributes): array
            {
                if (!($value instanceof Credentials)) {
                    throw new \InvalidArgumentException('Provided credentials must be an implementation of Credentials class.');
                }

                // IMPORTANT: return the value object, not the call to ->toArray()
                // otherwise the properties will be merged as individual attributes
                return $value;
            }
        };
    }

    static public function factory(string $mechanism, \stdClass $value): Credentials
    {
        return new EmailCredentials($value->email, $value->password);
    }
}

class EmailCredentials extends Credentials
{
    public function __construct(private string $email, private string $password) {}

    public function toArray(): array
    {
        return [
            'email' => hash('SHA512', $this->email),
            'password' => Hash::make($this->password),
        ];
    }

    public function jsonSerialize()
    {
        return $this->toArray();
    }
}
```

I never used it like this, but there is an important thing to note, on the anonymous class `set()` method, return the value object instead of calling its `->toArray()` method.

**Comment by kirkbushell** [comment]
Okay, closing - I realised I should be returning a string not an array - when an array is returned, it flattens it to the model.

**Comment by kirkbushell** [comment]
@rodrigopedra haha, very quick - I discovered my issue same time as you responded. Also - thanks for the suggestion on the jsonSerialize - that will also clean it up a little bit.

Cheers! :)

**Comment by rodrigopedra** [comment]
no worries =) I hit the send button just to realize you figured out a solution.

Cheers!

**Comment by kirkbushell** [comment]
@rodrigopedra unfortunately I can't just return the value object - it doesn't recognise it as a valid value. Pretty sure I have to convert to a json string.

**Comment by rodrigopedra** [comment]
Try fixing the return type, I had overseen, so PHP should be complaining

```php
public function set(Model $model, string $key, mixed $value, array $attributes): array
// REMOVE THIS-----------------------------------------------------------------^^^^^^^
```

If your value object implements `\Illuminate\Support\Contracts\Arrayable` it should work:

https://github.com/laravel/framework/blob/4989e6de076688ade265e2f1970ab6f0c1b60fcb/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L315-L317
