### ISSUE TITLE
[DB] [Grammar] `Query\Builder::updateOrInsert()` fails when it needs to insert JSON fields

### ISSUE THREAD

**Issue by shehi** [laravel/framework#48174]
### Laravel Version

10.20.0

### PHP Version

8.1.4

### Database Driver & Version

MariaDb 10.6

### Description

Apparently `Query\Builder::updateOrInsert()` method's [**insert** branch](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Query/Builder.php#L3457) doesn't like JSON vector types. Whereas **update** branch eventually leads to `MySqlGrammar::prepareBindingsForUpdate()` where array-types get `json_encode()`d, "insert" branch has no such logic. It eventually ends up inside `Illuminate\Support\Str::replaceArray()` function where a string replacement is attempted. Once instead of a string an array is encountered, it goes poof: "**Array to string conversion**".

My question is: is it intentional, or a missed use-case, that `MySqlGrammar` (and similar "Grammar"s as well) doesn't have a method called `prepareBindingsForInsert()` or similar, which would handle array-types?

My model has everything it needs:

1. $casts
2. `$table->json()` -created columns.

It works quite OK when a field is assigned array-type value (e.g. `$model->col = ['a', 'b']`). But the moment I want to do this for a non-existent data:

```
Model::query()->updateOrInsert(['id' => 1], ['col' => ['a', 'b']);
```

it goes kaput.

### Steps To Reproduce

Read the description plz.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by shehi** [comment]
Disclaimer: Prepare for a rant, because it is frustrating!

@crynobone , what question/problem? Did you even read what I posted? I clearly showed where the problem lies, to bring the maintainers' (who are supposed to know the codebase) attention to a potential missed use-case (i.e. code that is not complete), to confirm that something is indeed missing there (in order to potentially send a PR that would fill the gap). I don't need to post on SO or whatever, I don't need some random Joe's help or whatever. I really don't understand what someone like you is trying to achieve here: to alienate people from contributing? to bury the existing issues? to demonstrate how clueless or inconsiderate a project maintainer is? Or to hint us "hey we have some internal issue tracking system, so we don't care about public Github" (tho unlikely)?

Please stop treating your userbase like kids and show some respect!

**Comment by crynobone** [comment]
Yes I do read your issue but you also mentioned the following:

> My question is: is it intentional, or a missed use-case, that MySqlGrammar (and similar "Grammar"s as well) doesn't have a method called prepareBindingsForInsert() or similar, which would handle array-types?

Issues are dedicated for confirmed bug.

**Comment by ivankuraev** [comment]
Laravel 11.36

This bug is still present.

If record in database doestn exists, insert throw an error, when trying with array.
To bypass this bug I use collect()->toJson() in values array.

**Comment by afk11** [comment]
@crynobone 

> Yes I do read your issue but you also mentioned the following:
> 
> > My question is: is it intentional, or a missed use-case, that MySqlGrammar (and similar "Grammar"s as well) doesn't have a method called prepareBindingsForInsert() or similar, which would handle array-types?
> 
> Issues are dedicated for confirmed bug.

This issue comes up when I search for my problem, can we count it as confirmed since there are others acknowledging the issue?
