### ISSUE TITLE
Infinite recursion when serializing a model which references itself

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#48172]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

When a class is serialized (for queued jobs, e.g. mailables) it enters infinite recursion when a model references itself. This can cause PHP to quit unexpectedly without any errors or logs.

### Steps To Reproduce

In the below example, a `sameUser` relation is set on the `User` model that references the same model to be serialized.

```php
class User extends \Illuminate\Database\Eloquent\Model {

}

class UserMail {
	use SerializesModels;

	public User $user;

	public function __construct(User $user)
	{
		$this->user = $user;
	}
}

$user = new User;
$user->setRelation('sameUser', $user);

$mail = new UserMail($user);

dd($mail->__serialize()); // this never completes and quits unexpectedly, due to infinite recursion
```

This is the most simplest way to demonstrate the problem. The same problem exists with actual saved model objects.

Most applications this type of recursion would occur when you have a deeply nested eagerly loaded relations, where one or more of those relations refers back to the exact same model instance being serialized. When this happens, it attempts to serialize the same model over and over, creating a loop.

**Comment by garygreen** [comment]
Laravel's [`Illuminate\Queue\SerializesAndRestoresModelIdentifiers`](https://github.com/laravel/framework/blob/f9812236cc64ecf51dc44f9834a46c7e66783f7a/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php#L27-L40) makes a call to `getQueueableRelations()` on the model, which subsequently recursively calls itself for deeply nested relations. So I think that's where this infinite recursion is happening.

https://github.com/laravel/framework/blob/f9812236cc64ecf51dc44f9834a46c7e66783f7a/src/Illuminate/Database/Eloquent/Model.php#L1979-L2004

This [Stackoverflow post](https://stackoverflow.com/a/17241112) may help - it suggests ways of resolving this e.g. by tracking references of same objects with `[spl_object_hash](http://php.net/spl_object_hash)`

**Comment by crynobone** [comment]
The above example doesn't seem like a good use case, we probably need a better real-world use case to consider making any changes to this, and at the same time it may be possible to use `withourRelations` here: https://laravel.com/docs/10.x/queues#handling-relationships

**Comment by garygreen** [comment]
@crynobone This is quite a sinister bug in that it doesn't produce produce any errors in the logs or reports to a tracking tool (Bugsnag/Sentry). At least there's some visibility on this issue now if anyone else comes across this in future.

Laravel creates different model instances/copies when relations are loaded, so this may not be a frequent issue for most. However, it is a massive gotcha if you do make regular use of `setRelation` or `associate()` to set models, and then pass them onto a queued job to be serialized, because it may cause this infinite recursion if there is a circular reference. We make use of those functions for performance reasons, to avoid having to load already loaded models in memory.

This is our real world case, model structure. Assuming `refunds` is loaded and references the same invoice being serialized.

```
Invoice [1]
   refunds =>  Collection [
         Refund
              invoice [invoice_id] => Invoice [1]   (circular reference 🔥)
         Refund
            invoice [invoice_id]  => Invoice [2]
   ]
````

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by paul-thebaud** [comment]
Hello, I'm also experiencing this.
IMO the issue should not be closed, as there should be at least an exception thrown instead of an infinite loop crash.
My current workaround is to use `WithoutRelations` for now.
