### ISSUE TITLE
Cache::flush with Redis throws error: Command 'EXECUTECOMMANDONNODES' is not a registered Redis command

### ISSUE THREAD

**Issue by drewg2009** [laravel/framework#48182]
### Laravel Version

^8.83

### PHP Version

^8.2

### Database Driver & Version

"predis/predis": "^1.1",

### Description

Trying to use Cache::flush() with redis cache driver within laravel. 

It throws an error when I call it: 

Command 'EXECUTECOMMANDONNODES' is not a registered Redis command

### Steps To Reproduce

1. Configure redis with a laravel app
2. Call Cache::flush() in an endpoint

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
