### ISSUE TITLE
Validation UNIQUE rule fails with strings

### ISSUE THREAD

**Issue by juliangarcess** [laravel/framework#48195]
### Laravel Version

10.15.0

### PHP Version

8.2.4

### Database Driver & Version

SQLite

### Description

The `Illuminate\Support\Facades\Validator` UNIQUE rule is broken when comparing strings with different upper case and lower case because it uses the '=' comparator and I think it should use the 'LIKE' comparator.

### Steps To Reproduce

Create a user with email test@example.com and try to pass this validation: 

---

CASE 1 (broken case):
`Illuminate\Support\Facades\Validator::make(['email'=>'test@example.coM'], ['email'=>' required|email|unique: users'])->validate()`
Then, this query gets executed:
`[0.31 ms] select count(*) as aggregate from "users" where "email" = 'test@example.coM' -> 0 results`
RESULT: `Illuminate\Validation\ValidationException  The email has already been taken.`

---

CASE 2:
If you try with the email lowered:
`Illuminate\Support\Facades\Validator::make(['email'=>'test@example.com'], ['email'=>' required|email|unique: users'])->validate()`
Then, this query gets executed:
`[0.31 ms] select count(*) as aggregate from "users" where "email" = 'test@example.com' -> 1 result`
The validation fails.

---

The validation should fail in both cases

**Comment by mjamilasfihani** [comment]
I think, it should use lowercase's rule.

**Comment by juliangarcess** [comment]
Unique in string columns in database level is case insensitive, I understand that the validation should adopt that behaviour.

**Comment by juliangarcess** [comment]
For example you whant that in the table posts the title be unique (example from the docs) and the case doesn't matters. 

`$validated = $request->validate([
        'title' => 'required|unique:posts|max:255',
        'body' => 'required',
]);`

[Laravel Docs](https://laravel.com/docs/10.x/validation#quick-writing-the-validation-logic)

**Comment by crynobone** [comment]
Database case collation is determined by the database configuration, changing this instead of honouring database collation is a breaking change.

**Comment by juliangarcess** [comment]
Now is a security issue because with this validation failure, two users may exist with the same email with different cases which is totally illogical.

**Comment by crynobone** [comment]
So what's you are saying, `$table->string('email')->unique();` did also failed on your database, right? Don't you think that 's the real issue here.

**Comment by juliangarcess** [comment]
Fails on database level but 500 error shows to users

**Comment by juliangarcess** [comment]
On SQLite no error throwed with `$table->string('email')->unique();` if different cases.

**Comment by juliangarcess** [comment]
@crynobone I mention you again because I forgot to mention you on the first last comment. did you read it?

**Comment by crynobone** [comment]
The answer is still the same. This is a breaking changes to other database that can properly handled case insensitive using collation.
