### ISSUE TITLE
classCastCache causes serialization to fail in model event

### ISSUE THREAD

**Issue by Kyzegs** [laravel/framework#48198]
### Laravel Version

10.13.2

### PHP Version

8.1.17

### Database Driver & Version

MySQL 8.0.30 for Win64 on x86_64 (MySQL Community Server - GPL)

### Description

A model with casts that has events registered is not able to have a non-serializable class (`UploadedFile`) assigned to a casted property. I believe this is due to the fact that `classCastCache` passes the non-serializable class even when it's already casted.

```php
App\Models\Convention {#1552 ▼ // vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php:189
  #classCastCache: array:1 [▶
    "thumbnail_url" => Illuminate\Http\UploadedFile {#1533 ▶
      -test: false
      -originalName: "Gojo.jpg"
      -mimeType: "application/octet-stream"
      -error: 0
      #hashName: "pM3oeHUTb770og7YuiNXeiM6ZTgGGCDMOaHRKtxG"
      path: "C:\Users\Kyzegs\AppData\Local\Temp"
      filename: "php4516.tmp"
      basename: "php4516.tmp"
      pathname: "C:\Users\Kyzegs\AppData\Local\Temp\php4516.tmp"
      extension: "tmp"
      realPath: "C:\Users\Kyzegs\AppData\Local\Temp\php4516.tmp"
      aTime: 2023-08-27 01:02:02
      mTime: 2023-08-27 01:02:02
      cTime: 2023-08-27 01:02:02
      inode: 33776997206247486
      size: 1002007
      perms: 0100666
      owner: 0
      group: 0
      type: "file"
      writable: true
      readable: true
      executable: false
      file: true
      dir: false
      link: false
      linkTarget: "C:\Users\Kyzegs\AppData\Local\Temp\php4516.tmp"
    }
  ]
}
```

### Steps To Reproduce

To reproduce the error you'll need the following cast:

```php
<?php

namespace App\Casts;

use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class Image implements CastsAttributes
{
    /**
     * Create a new cast class instance.
     */
    public function __construct(
        private readonly ?string $path = null,
    ) {
    }

    /**
     * Cast the given value.
     *
     * @param  array<string, mixed>  $attributes
     */
    public function get(Model $model, string $key, mixed $value, array $attributes): mixed
    {
        return $value && Storage::exists($value) ? Storage::url($value) : $value;
    }

    /**
     * Prepare the given value for storage.
     *
     * @param  array<string, mixed>  $attributes
     */
    public function set(Model $model, string $key, mixed $value, array $attributes): mixed
    {
        return $value instanceof UploadedFile ? $value->storeAs($this->path ?? $key, $value->hashName()) : $value;
    }
}
```

Ensure the cast is set on your model **that has events registered**:

```php
class Dummy extends Model
{
    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'thumbnail_url' => Image::class.':thumbnails',
    ];
}
```

Then when trying to create an entry that uses it'll result in the error:

```php
Model::create([
    'thumbnail_url' => $request->file('thumbnail_url'),
]);

// Serialization of 'Illuminate\Http\UploadedFile' is not allowed
```
Keep in mind that the entry is actually stored to the database successfully.

**Comment by keyurmodipro** [comment]
The issue you're facing appears to be related to the serialization of an `Illuminate\Http\UploadedFile` instance when it is assigned to a casted property in a model with events registered. Laravel tries to serialize all attributes when firing events, but `Illuminate\Http\UploadedFile` is not serializable by default.

To resolve this issue, you can modify your code to handle the serialization of the `Illuminate\Http\UploadedFile` object in a way that Laravel can understand. One approach is to serialize only the necessary information from the `UploadedFile` object and store it in the database.

Here's how you can modify your `Image` cast to store only the necessary information:

```php
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class Image implements CastsAttributes
{
    public function __construct(private ?string $path = null)
    {
    }

    public function get(Model $model, string $key, $value, array $attributes)
    {
        // Deserialize the value if it's not already an array
        if (!is_array($value)) {
            return $value;
        }

        // Reconstruct the UploadedFile instance
        if (isset($value['originalName'], $value['hashName'])) {
            return new UploadedFile(
                $value['pathname'],
                $value['originalName'],
                $value['mimeType'],
                $value['error'],
                false
            );
        }

        return null;
    }

    public function set(Model $model, string $key, $value, array $attributes)
    {
        if ($value instanceof UploadedFile) {
            // Store only the necessary information for later reconstruction
            return [
                'originalName' => $value->getClientOriginalName(),
                'hashName' => $value->hashName(),
                'pathname' => $value->getRealPath(),
                'mimeType' => $value->getMimeType(),
                'error' => $value->getError(),
            ];
        }

        return $value;
    }
}
```

With this modification, you store the minimal information required to reconstruct the `UploadedFile` instance when retrieving it from the database. This should allow you to work with casted properties without encountering serialization issues.

Make sure to update your migrations to match the changes in your casting. After making these changes, you should be able to create entries without encountering the serialization error.

**Comment by crynobone** [comment]
Thank you @keyurmodipro

**Comment by Kyzegs** [comment]
> The issue you're facing appears to be related to the serialization of an `Illuminate\Http\UploadedFile` instance when it is assigned to a casted property in a model with events registered. Laravel tries to serialize all attributes when firing events, but `Illuminate\Http\UploadedFile` is not serializable by default.
> 
> 
> 
> To resolve this issue, you can modify your code to handle the serialization of the `Illuminate\Http\UploadedFile` object in a way that Laravel can understand. One approach is to serialize only the necessary information from the `UploadedFile` object and store it in the database.
> 
> 
> 
> Here's how you can modify your `Image` cast to store only the necessary information:
> 
> 
> 
> ```php
> 
> use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
> 
> use Illuminate\Database\Eloquent\Model;
> 
> use Illuminate\Http\UploadedFile;
> 
> use Illuminate\Support\Facades\Storage;
> 
> 
> 
> class Image implements CastsAttributes
> 
> {
> 
>     public function __construct(private ?string $path = null)
> 
>     {
> 
>     }
> 
> 
> 
>     public function get(Model $model, string $key, $value, array $attributes)
> 
>     {
> 
>         // Deserialize the value if it's not already an array
> 
>         if (!is_array($value)) {
> 
>             return $value;
> 
>         }
> 
> 
> 
>         // Reconstruct the UploadedFile instance
> 
>         if (isset($value['originalName'], $value['hashName'])) {
> 
>             return new UploadedFile(
> 
>                 $value['pathname'],
> 
>                 $value['originalName'],
> 
>                 $value['mimeType'],
> 
>                 $value['error'],
> 
>                 false
> 
>             );
> 
>         }
> 
> 
> 
>         return null;
> 
>     }
> 
> 
> 
>     public function set(Model $model, string $key, $value, array $attributes)
> 
>     {
> 
>         if ($value instanceof UploadedFile) {
> 
>             // Store only the necessary information for later reconstruction
> 
>             return [
> 
>                 'originalName' => $value->getClientOriginalName(),
> 
>                 'hashName' => $value->hashName(),
> 
>                 'pathname' => $value->getRealPath(),
> 
>                 'mimeType' => $value->getMimeType(),
> 
>                 'error' => $value->getError(),
> 
>             ];
> 
>         }
> 
> 
> 
>         return $value;
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> With this modification, you store the minimal information required to reconstruct the `UploadedFile` instance when retrieving it from the database. This should allow you to work with casted properties without encountering serialization issues.
> 
> 
> 
> Make sure to update your migrations to match the changes in your casting. After making these changes, you should be able to create entries without encountering the serialization error.

I've tried that but that doesn't work. The cast works just fine, as I mentioned. It even stores it in the database as a path. It's the cache of the casts that causes the event to fail.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by Kyzegs** [comment]
I've found out that the issue is related to a package. They serialize the pre-casted values.
