### ISSUE TITLE
Fatal error: Uncaught ReflectionException: Class "config" does not exist in D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php:912

### ISSUE THREAD

**Issue by khaledHAssi** [laravel/framework#48239]
### Laravel Version

10

### PHP Version

8.1

### Database Driver & Version

mmySql 8...

### Description

when i wanna use laravel-dompdf it return this error : 

Fatal error: Uncaught ReflectionException: Class "config" does not exist in D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php:912
Stack trace:
#0 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php(912): ReflectionClass->__construct('config')
#1 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php(795): Illuminate\Container\Container->build('config')
#2 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(937): Illuminate\Container\Container->resolve('config', Array, true)
#3 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#4 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(922): Illuminate\Container\Container->make('config', Array)
#5 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(135): Illuminate\Foundation\Application->make('config')
#6 D:\ContributionApp\vendor\barryvdh\laravel-dompdf\src\ServiceProvider.php(28): Illuminate\Support\ServiceProvider->mergeConfigFrom('D:\\Contribution...', 'dompdf')
#7 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(768): Barryvdh\DomPDF\ServiceProvider->register()
#8 D:\ContributionApp\bootstrap\app.php(45): Illuminate\Foundation\Application->register(Object(Barryvdh\DomPDF\ServiceProvider))
#9 D:\ContributionApp\artisan(20): require_once('D:\\Contribution...')
#10 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php:914
Stack trace:
#0 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php(795): Illuminate\Container\Container->build('config')
#1 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(937): Illuminate\Container\Container->resolve('config', Array, true)
#2 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#3 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(922): Illuminate\Container\Container->make('config', Array)
#4 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(135): Illuminate\Foundation\Application->make('config')
#5 D:\ContributionApp\vendor\barryvdh\laravel-dompdf\src\ServiceProvider.php(28): Illuminate\Support\ServiceProvider->mergeConfigFrom('D:\\Contribution...', 'dompdf')
#6 D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(768): Barryvdh\DomPDF\ServiceProvider->register()
#7 D:\ContributionApp\bootstrap\app.php(45): Illuminate\Foundation\Application->register(Object(Barryvdh\DomPDF\ServiceProvider))
#8 D:\ContributionApp\artisan(20): require_once('D:\\Contribution...')
#9 {main}
  thrown in D:\ContributionApp\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 914

### Steps To Reproduce

I need the solution pls ♥

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
