### ISSUE TITLE
`partialMock` of RateLimiter-Facade does not seem to set the cache property

### ISSUE THREAD

**Issue by m-thalmann** [laravel/framework#48248]
### Laravel Version

10.20.0

### PHP Version

8.2.6

### Database Driver & Version

sqlite

### Description

When writing tests for a rate-limited endpoint I am trying to partially mock the RateLimiter facade to return a constant value for the `availableIn` call:

```php
public function testRateLimitsAfterCertainAmountOfBadRequests(): void {
        RateLimiter::partialMock()
            ->shouldReceive('availableIn')
            ->once()
            ->andReturn(60);

        // ...
}
```

When executing the test the following error occurrs:

`
Error: Call to a member function get() on null in C:\Users\matth\Projects\SecureDAV\vendor\laravel\framework\src\Illuminate\Cache\RateLimiter.php:143
`

Which corresponds to the following line inside of the RateLimiter class (`attempts`-function):
```php
return $this->cache->get($key, 0);
```

To me it seems like using the partial mock, does not initialize the class correctly and therefore does not set the cache property.

Am I doing something wrong here or is this an actual bug?
Thanks!

### Steps To Reproduce

1. Create a simple route with rate-limiting:
```php
Route::post('/test', function (Request $request) {
    $throttleKey = "my-throttle-key-{$request->ip()}";

    if (RateLimiter::tooManyAttempts($throttleKey, 5)) { // max attempts is 5
        $seconds = RateLimiter::availableIn($throttleKey);

        throw new TooManyRequestsHttpException($seconds);
    }

    // in my code there are some checks here; simplified for this example
    if (!false) {
        RateLimiter::hit($throttleKey);

        throw new BadRequestHttpException();
    }

    RateLimiter::clear($throttleKey);

    return redirect()->intended('/');
});
```
2. Create a test:
```php
public function testRateLimitsAfterCertainAmountOfBadRequests(): void {
    RateLimiter::partialMock()
        ->shouldReceive('availableIn')
        ->once()
        ->andReturn(60);

    for ($i = 0; $i < 5; $i++) {
        $response = $this->post('/test');

        $response->assertBadRequest();
    }

    $response = $this->post('/test');
    $response->assertTooManyRequests();
}
```

**Comment by frans-slabbekoorn** [comment]
@m-thalmann did you ever find a solution for this? I'm still encountering this problem in the latest laravel version.

**Comment by m-thalmann** [comment]
@frans-slabbekoorn sadly not really... The mentioned resources did not provide any useful information.
I found a workaround which kinda did what I needed:

```php
function mockRateLimiter(
    array $mockedMethods
): CacheRateLimiter|MockInterface {
    $rateLimiterMock = Mockery::mock(
        CacheRateLimiter::class . '[' . join(',', $mockedMethods) . ']',
        [$this->app->make('cache.store')]
    );

    RateLimiter::swap($rateLimiterMock);

    return $rateLimiterMock;
}
```

```php
$availableIn = 43;

$rateLimiterMock = $this->mockRateLimiter(['availableIn']);
$rateLimiterMock
    ->shouldReceive('availableIn')
    ->once()
    ->andReturn($availableIn);

for ($i = 0; $i < static::LOGIN_THROTTLE_LIMIT; $i++) {
    $response = $this->post('/login', [
        'email' => 'wrong-email@example.com',
        'password' => 'wrong-password',
    ]);

    $response->assertSessionHasErrors(['email' => __('auth.failed')]);
}
```

Hope this helps :)

**Comment by frans-slabbekoorn** [comment]
@m-thalmann Thank you! What i did as workaround for now, is overwriting the rate limit in my test. Hope this will get fixed soon, but wondering why theres not more activity on this issue since it doesn't seem to be a that much of an edgecase
