### ISSUE TITLE
Tests with time travel fail on microseconds

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#48262]
### Laravel Version

10.21.0

### PHP Version

8.2.7

### Database Driver & Version

MySQL 8.0.32

### Description

It appears that built-in date functions are suffering from microsecond differences when time is frozen in a test. This is unexpected given that the time helpers are meant to freeze time throughout the entire application.

The following test makes use of framework methods only but fails.

As you can see the **expected** datetime (being `now()`) has some microseconds while the actual value (making use of `updateTimestamps()` --> `freshTimestamp()` --> `now()`) is put at zero microseconds?

```php
$this->freezeTime();
$user = User::factory()->create();

$this->travel(1)->hour();
$user->updateTimestamps()->save();

$this->assertEquals(now(), $user->updated_at);
```

![image](https://github.com/laravel/framework/assets/6680176/457f243f-0ac4-40b5-a602-608c378ba825)

### Steps To Reproduce

Create a fresh application with the test described above.

**Comment by crynobone** [comment]
I believe this should be expected since most databases (except MSSQL only store DateTime using `Y-m-d H:i:s`). 

You can solve this by setting `$dateFormat` in the model to `Y-m-d H:i:s.u`:

```php
class User extends Model 
{

    /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = 'Y-m-d H:i:s.u';
}
```

See https://github.com/laravel/framework/pull/48267

Also you can also avoid microseconds by using `$this->freezeSecond();` insteads.

**Comment by Propaganistas** [comment]
Wonderful insight about the difference in precision - thanks. It clearly shows that the returned values are actually both correct in their own way: `now()` returns the freezed time in microsecond precision, while database datetimes return values in second precision.

I can confirm that `freezeSecond()` makes the test pass as expected. Perhaps a short elaboration in the docs on why you'd want to use `freezeTime()` vs `freezeSecond()` could help future people running into this:

Current paragraph:
> The freezeTime method may be used to freeze the current time. Similarly, the freezeSecond method will freeze the current time but at the start of the current second.

Suggested:
> The freezeTime method may be used to freeze the current time. Similarly, the freezeSecond method will freeze the current time but at the start of the current second. Because most databases store timestamps without microseconds, the latter could be useful when making comparisons against datetimes stored in a database.
