### ISSUE TITLE
Fresh Migration: 1068 Multiple primary key defined

### ISSUE THREAD

**Issue by Squad-G** [laravel/framework#48272]
### Laravel Version

10.21

### PHP Version

8.1.7

### Database Driver & Version

Azure Pipeline

### Description

Hello,

It will be hard for me to produce logs and stuff because this error happens when deploying the project in Azure Pipeline. I am unsure if this is an actual bug or maybe a system issue.

Basically, the database is fresh with no tables in it. The first command to be issued when the project is deployed is this one:
`php artisan migrate:fresh --force --env=testing`

As you all know it, the fresh command will also drop all tables so the database is for sure empty.

Here's the output from the migration:

`  Dropping all tables ........................................... 3,751ms DONE

   INFO  Preparing database.  

  Creating migration table ........................................ 104ms DONE

   INFO  Loading stored database schemas.  

  database/schema/mysql_xrm_backend-schema.sql ................. 33,571ms DONE

   INFO  Running migrations.  

  2016_06_01_000001_create_oauth_auth_codes_table ................. 173ms FAIL

In Connection.php line 801:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary ke  
  y defined (Connection: mysql_xrm_backend, SQL: alter table `oauth_auth_code  
  s` add primary key (`id`))                                                   
                                                                               

In Connection.php line 580:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary ke  
  y defined`

The oauth_auth_code table is from Laravel passport. If we look at the migration file, here's the structure:
`public function up(): void`
`    {`
`        Schema::create('oauth_auth_codes', function (Blueprint $table) {`
`            $table->string('id', 100)->primary();`
`            $table->unsignedBigInteger('user_id')->index();`
`            $table->unsignedBigInteger('client_id');`
`            $table->text('scopes')->nullable();`
`            $table->boolean('revoked');`
`            $table->dateTime('expires_at')->nullable();`
`        });`
`    }`

The structure appear to be correct. To me, the only explanation is an issue with the migration system trying to attach the PK twice.

When ran on my machine (Windows + XAMPP), the migration doesn't run into any errors.

I would love to help more but I am unsure on how to debug a migration deployment from the Azure Pipeline.

Thank you.

### Steps To Reproduce

N/A

**Comment by driesvints** [comment]
>  I am unsure if this is an actual bug or maybe a system issue.

Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
