### ISSUE TITLE
PHP Deprecated warning in console commands for illuminate/validation

### ISSUE THREAD

**Issue by mx-jhinz** [laravel/framework#48290]
### Laravel Version

10.21

### PHP Version

8.2

### Description

The current illuminate/validation Validator facade calling `Validator::make([...])->validate()` throws `PHP Deprecated` warnings when passing command line options to the validator which are `null`:

```
PHP Deprecated str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated 
    [internal] str_contains
    ./vendor/illuminate/support/Str.php:260 Illuminate\Support\Str::contains
```

### Steps To Reproduce

Create a new command with nullable options and then validate the options by:
```
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class SomeCommand extends Command
{
    protected $signature = 'some-command '
    . '{--some_opt_1= : some optional parameter}'
    . '{--some_opt_2= : some optional parameter}';

    public function handle()
    {
        $requestData = Validator::make([
            'some_opt_1' => $this->option('some_opt_1'),
            'some_opt_2' => $this->option('some_opt_2'),
        ], [
            'some_opt_1' => ['nullable', 'required_with:some_opt_2'],
            'some_opt_2' => ['nullable'],
        ])->validated();

        // do something
    }
}
```

And then call the command `php artisan some-command`. The command output itself does not show the warning, but die warning is detected. I would suggest handling this case to avoid nasty `if($this->option('some_opt_1'))` conditions. The same warning occurs in other case as well (not just for `required_with`)

**Comment by driesvints** [comment]
Thanks. A deprecation warning isn't considered a real issue. We'd appreciate a PR for this if you want to solve this, thanks.
