### ISSUE TITLE
Illuminate\Testing\Fluent\AssertableJson should normalize json before Concerns\Matching is executed

### ISSUE THREAD

**Issue by lk77** [laravel/framework#48293]
### Laravel Version

10.1.16

### PHP Version

8.1.11

### Database Driver & Version

mariadb 10

### Description

Hello,

there is an issue with the way AssertableJson class (https://github.com/laravel/framework/blob/10.x/src/Illuminate/Testing/Fluent/AssertableJson.php) and Matching trait (https://github.com/laravel/framework/blob/10.x/src/Illuminate/Testing/Fluent/Concerns/Matching.php) are setup,

unlike the AssertableJsonString class (https://github.com/laravel/framework/blob/10.x/src/Illuminate/Testing/AssertableJsonString.php)

there is no normalization of the expected/actual json

currently it means that assertion will fail for values like `1.0` that will be silently changed to `1` when the json encoding/decoding occur 

### Steps To Reproduce

simple test : 

```php
public function test_json() {
        $data = [
            'data' => 1.0
        ];
        $response = TestResponse::fromBaseResponse(response($data));
        $response->assertJson(function (AssertableJson $json) use ($data) {
            $json->whereAll($data);
        });
    }
```

test results :

```
Property [data] does not match the expected value.
Failed asserting that 1 is identical to 1.0.
```

You could argue that `1.0` is not really a valid json value and that i should make sure that such value is properly cast to integer, but since this seams to be handled by the rest of the framework, including `AssertableJsonString`, there is still something not right i think, because in the end it means that `TestResponse::assertJson` and `TestResponse::assertExactJson` are not really in the same page regarding that json normalization, because it means that for the exact same payload, `TestResponse::assertJson` will fail and `TestResponse::assertExactJson` will not 

```php
public function test_json() {
        $data = [
            'data' => 1.0
        ];
        $response = TestResponse::fromBaseResponse(response($data));
        // do not fail
        $response->assertExactJson($data);
        // fail
        $response->assertJson(function (AssertableJson $json) use ($data) {
            $json->whereAll($data);
        });
    }
```

**Comment by crynobone** [comment]
From the code it seems that `assertExactJson()` uses less strict assertion `assertEquals` instead of `assertSame`. Not sure if it's wise to make any changes here as the current behaviour might already widely accepted by the community.

**Comment by driesvints** [comment]
I do agree that this might seem odd but for now I don't think we'll take action here. You can change your assertion up front to be `1` so it matches with what you have.
