### ISSUE TITLE
Lazy loading a relation conditionally returns null and `$this->getAttributes()`always returns empty

### ISSUE THREAD

**Issue by rezadsn** [laravel/framework#48295]
### Laravel Version

10.10

### PHP Version

8.1.7

### Database Driver & Version

sqlsrv

### Description

I have a model called Stage. and it has a HasMany relation 'products'. Recently the project was upgraded from version 9 to 10.

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class OrderStage extends \Illuminate\Database\Eloquent\Model
{
    use HasFactory;


    protected $table = 'Order_Stage';

    protected $connection = 'sqlsrv';

    protected $primaryKey = 'OrderID';

    protected $keyType = 'string';

    protected $guarded =[];

    public function products()
    {
        dump($this->getAttributes()); //should not return empty array, but it does.
        return $this->hasMany(OrderProduct::class, 'OrderID', 'OrderID')
            ->where('StageID', $this->StageID);
    }
}
```

If I do the following:

```php
$stages = OrderStage::take(20)->get()->load('products');
$stages->map->products;
```

It is supposed to return the products 

or 

```php
$stages = OrderStage::whereHas('products')->get();
```

Supposed to return at least 1 OrderStage record.

both returns an empty collection.

Even the dump `$this->getAttributes()` returns an empty array. I also tried many options such as `$this->getRawOriginal('StageId').  It always returns null

Howver if I do `$stages->map->products` it returns all the data that I am supposed to get.

### Steps To Reproduce

 To reproduce the error you'll need the following:
 

-  Create 2 models. OrderStage and Products.
-  Database : `MSSQL`

`OrderStage.php`

##### columns:

![image](https://github.com/laravel/framework/assets/124902170/51d33629-6891-4dba-adf0-c94f12b58bf7)

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class OrderStage extends \Illuminate\Database\Eloquent\Model
{
    use HasFactory;


    protected $table = 'Order_Stage';

    protected $connection = 'sqlsrv';

    protected $primaryKey = 'OrderID';

    protected $keyType = 'string';

    protected $guarded =[];

    public function products()
    {
        dump($this->getAttributes()); //should not return empty array, but it does.
        return $this->hasMany(OrderProduct::class, 'OrderID', 'OrderID')
            ->where('StageID', $this->StageID);
    }
}
```

`OrderProduct.php`

##### columns:

![image](https://github.com/laravel/framework/assets/124902170/e3c33273-1e3e-48f6-bf5d-90140dceb7bf)

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

class OrderProduct extends \Illuminate\Database\Eloquent\Model
{
    use HasFactory;

    protected $table = 'Order_Stage_Products';

    protected $primaryKey = 'Ref';

    public $incrementing = true;
}
```

Run the following in tinker well or tinker or wherever it seems fit.

```php
$stages = OrderStage::take(20)->get()
->load('products');
dd($stages->map->products);
```

Expected Output:

![image](https://github.com/laravel/framework/assets/124902170/305c3af3-48fc-4e21-b934-46c3ea6a500b)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
