### ISSUE TITLE
Lazy loading a relation conditionally returns null and `$this->getAttributes()`always returns empty

### ISSUE THREAD

**Issue by rezadsn** [laravel/framework#48301]
### Laravel Version

10.10

### PHP Version

8.1.7

### Database Driver & Version

SQL SR (mssql)

### Description

#48295

### Steps To Reproduce

#48295

**Comment by rezaulhreza** [comment]
Reopen

**Comment by rezadsn** [comment]
reopen

**Comment by rezadsn** [comment]
resolved with https://github.com/topclaudy/compoships
