### ISSUE TITLE
named identifiers in where clause cause wrong  query 

### ISSUE THREAD

**Issue by owis-s** [laravel/framework#48303]
### Laravel Version

10.21.0

### PHP Version

8.2

### Description

when i user $query->where(column:'col_name',value:true);
[named identifiers ] the result query went wrong 
here is my code:
in model :
`public function scopeInprocess(Builder $query)
    {
        return $query
            ->where(column: 'to_show', value: true)
            ->where(column: 'is_accepted', value: false);
    }`
when i use it in my controller :
`public function getMyItems()
    {
        $this->items = $this->project->items()
            ->inprocess()
            ->dd();
    }
`
rhe result is :
`"select * from `items` where `items`.`project_id` = ? and `items`.`project_id` is not null and `to_show` is null and `is_accepted` is null and `items`.`deleted_at` is null ◀"`
when i remove the named identifier
the result is :
`"select * from `items` where `items`.`project_id` = ? and `items`.`project_id` is not null and `to_show` = ? and `is_accepted` = ? and `items`.`deleted_at` is null`
`array:3 [
  0 => 1
  1 => true
  2 => false
]`

### Steps To Reproduce

1. add scope method in model.
2. create livewire component and create function to get the result
3. put the livewire component in view to show it
4. die and dump query result to get the error.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
