### ISSUE TITLE
Set logger on `EsmtpTransportFactory`

### ISSUE THREAD

**Issue by parallels999** [laravel/framework#48317]
### Laravel Version

Current

### PHP Version

8.1

### Database Driver & Version

MariaDB

### Description

By default transport is using `NullLogger`
How to set a logger on `EsmtpTransportFactory`? 
Any chance to change it on demand too?
https://github.com/laravel/framework/blob/909ea24597b86cfc7a49ce41074280d0347bf6a3/src/Illuminate/Mail/MailManager.php#L174-L196

### Steps To Reproduce

The `__construct` needs `LoggerInterface $logger`
[Symfony/Mailer/Transport/AbstractTransportFactory.php#L28-L33](https://github.com/symfony/symfony/blob/2bac801f8a4cba02e8ecc840fa7bf512034f860a/src/Symfony/Component/Mailer/Transport/AbstractTransportFactory.php#L28-L33)
[Symfony/Mailer/Transport/AbstractTransport.php#L41](https://github.com/symfony/symfony/blob/2bac801f8a4cba02e8ecc840fa7bf512034f860a/src/Symfony/Component/Mailer/Transport/AbstractTransport.php#L41)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by parallels999** [comment]
@driesvints it is not a question, there is no way for change `NullLogger` on symfony transport, people on symfony say that the constructor args must be handled by laravel

**Comment by driesvints** [comment]
@parallels999 welcoming PRs for us to review 👍

**Comment by parallels999** [comment]
> welcoming PRs for us to review

Taylor always closes them before any review, and in this case I don't know how to fix it 😔
