### ISSUE TITLE
JsonResource toArray does not handle JsonSerializable

### ISSUE THREAD

**Issue by coppolafab** [laravel/framework#48310]
### Laravel Version

10.22.0

### PHP Version

8.2.10

### Description

When resolving a resource to an array (JsonResource::resolve), the first call to toArray method does not check if the resource implements JsonSerializable and incorrectly calls $resource::toArray method on the resource, causing a "Call to undefined method" error.

Note that JsonResource::resolve correctly checks the JsonSerializable interface after the first toArray method call.

I'm preparing a PR.

### Steps To Reproduce

Define and call a route like this:

```
Route::get('/test', function() {
  $dto = new class implements JsonSerializable {
    public function jsonSerialize()
    {
      return ['foo' => 'bar'];
    }
  };

  return JsonResource::make($dto);
});
```

**Comment by driesvints** [comment]
Seems a PR was made for this so let's continue the discussion there.

**Comment by driesvints** [comment]
It seems Taylor doesn’t wants to make any changes here now sorry. So gonna leave things be 👍
