### ISSUE TITLE
It does not recognize the method ->toArray connection with PostgreSQL

### ISSUE THREAD

**Issue by rmunate** [laravel/framework#48320]
### Laravel Version

10.22

### PHP Version

8.1

### Database Driver & Version

PostgreSQL JDBC Driver 42.5.0 | PostgreSQL 10.13 (Ubuntu 10.13-1.pgdg16.04+1) PostgreSQL 10.13 (Ubuntu 10.13-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit

### Description

When executing a query like the following, the ->toArray() method does not work, it returns an error script in the console that does not print an error with the reason for the failure.

Query Builder:

```php
$query = DB::connection($value)
    ->table('res_partner')
    ->select(
        'id',
        'name',
        DB::raw(($value == 'pgsqlS') ? '1 as company_id' : '2 as company_id')
    )
    ->where('is_company', true)
    ->where('employee', false)
    ->where('active', true)
    ->distinct('id')
    ->get();
```

### Steps To Reproduce

1. Exceute Query From PostgreSQL
2. Use method ->toArray() after ->get()

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
