### ISSUE TITLE
JsonResource response wrong "Associative Arrays" when use number for key

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/framework#48328]
### Laravel Version

10.22.0

### PHP Version

8.2.7

### Database Driver & Version

-

### Description

Get wrong response when response from with `JsonResource` . An "Associative Arrays" that have key as number will response in "Indexed Arrays".

### Steps To Reproduce

```
$associative_array = [
    2 => ['x' => 1],
    3 => ['x' => 1],
    6 => ['x' => 1],
];
```

`return new JsonResource($associative_array);`
![Screen Shot 2566-09-07 at 15 55 31](https://github.com/laravel/framework/assets/6513358/2e919cbd-27e3-46ec-a238-ca0612a598e9)

`return response()->json($associative_array);`
![Screen Shot 2566-09-07 at 15 56 12](https://github.com/laravel/framework/assets/6513358/a3365e7a-38bf-4df4-ac3c-211ce8aebad0)

**Comment by rojtjo** [comment]
In order to preserve the keys you should create a custom resource class and define a `preserveKeys` property on it like this:

```php
class MyResource extends JsonResource
{
    protected bool $preserveKeys = true;
}
```

More info here: https://laravel.com/docs/10.x/eloquent-resources#preserving-collection-keys
