### ISSUE TITLE
inconsistency between Queue:fake() and dispatchSync method

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#48337]
### Laravel Version

10*

### PHP Version

8.2

### Description

When you want to test the job class it self, You cannot do it because the `Queue::fake()` always intercept the job even when using `dispatchSync` method

### Steps To Reproduce

create a job:

```php
class TestJob
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        dump('here');
    }
}
```

create a test:

```php
/** @test */ 
public function exampleTest()
{
    Queue::fake();

    //assert pushed any other jobs here

    //it doesn't run, but i want to test job itself
    TestJob::dispatchSync();

    //
}
```

When you run this the `dump` never executed, The `dispatchNow()` method was working but removed in laravel 10

**Comment by driesvints** [comment]
This is expected. If you need to test the job itself you'd do so without using the queue or `dispatchSync` method. Just call the handle method on the job directly.

**Comment by foremtehan** [comment]
What if the job has the container's dependency?

**Comment by rojtjo** [comment]
You could either just pass the dependencies manually or use the `call` method on the container:

```php
$job = new TestJob();

$this->app->call([$job, 'handle']);

// Or
App::call([$job, 'handle']);

// Or
app()->call([$job, 'handle']);
```

**Comment by foremtehan** [comment]
This is why i create this issue, the removal `DispatchNow` was mistaken
