### ISSUE TITLE
Collection::every return `true` if collect empty

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#48342]
### Laravel Version

10*

### PHP Version

8.2

### Description

Is it expected that the `every` method returns true if the collection items were empty?

### Steps To Reproduce

```php
collect()->every(fn() => die); //true
//doesn't matter what's inside the closure it return true when collection is empty
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
