### ISSUE TITLE
SQLite database being created in the root and without an extension like `.sqlite`

### ISSUE THREAD

**Issue by TheBlckbird** [laravel/framework#48351]
### Laravel Version

10.22.0

### PHP Version

8.2.9

### Database Driver & Version

SQLite 3.29.5

### Description

When using `sqlite` as the database driver, Laravel will ask you if it should create it if it doesn't exist when migrating.
It always created the file as `database/db.sqlite`, but now it creates it in the root of the project, just using the project name without an extension.
This doesn't affect any functionality, as the data is still being stored, but it's just inconvenient.
This also means that it is in version control.

### Steps To Reproduce

- `laravel new bug-report`
- Change the database driver in the `.env` file from `mysql` to `sqlite`.
- `php artisan migrate`
    - Choose "Yes"
- Now a file named `/bug-report` is created and used as the database.

**Comment by rojtjo** [comment]
This happens because you only changed the database driver but left the `DB_DATABASE` value, which is used as the database name for sqlite.

See: https://github.com/laravel/laravel/blob/10.x/config/database.php#L41

**Comment by crynobone** [comment]
Thank you @rojtjo

**Comment by TheBlckbird** [comment]
oh, yes thanks :)
