### ISSUE TITLE
`Model::incrementOrDecrement()` not saving attributes set during `updating` event

### ISSUE THREAD

**Issue by newtonjob** [laravel/framework#48350]
### Laravel Version

10.22

### PHP Version

8.2

### Description

Imagine we have a `Product` model.

We can listen for the `updating` event to always set the `updated_by` column like so;
```php
Product::updating(function ($product) {
    $product->updated_by = Auth::id();
})
```

Now, when we try to update the Product `stock` using the `increment()` method, other attributes set by an observer during the `updating` event do not get saved to the database.

```php
$product->increment('stock', 5); // `updated_by` is set but never saved to the db.
```

Note: In this example, the `updating` event is actually fired, and the observer code actually does set the value of `updated_by`. 
https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Model.php#L964

However, the other dirty attributes set during the `updating` event do not get saved to the database. I notice this happens because the `save()` method is never called (which actually saves all dirty attributes). The call is rather forwarded to the builder's own `increment/decrement` methods.
https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Model.php#L968

The **weirdest** part is that all of the dirty attributes are being synced as changes to the model, even when they were never actually changed/saved in the database.

https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Model.php#L969

This means, invoking `$product->wasChanged('updated_by')` returns `true` which is a false-positive result.

### Steps To Reproduce

See description.

**Comment by crynobone** [comment]
I believe this is expected since it's uses Fluent Query Builder to execute the query, which doesn't trigger any events:

https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Builder.php#L1114-L1127

**Comment by newtonjob** [comment]
@crynobone I think you missed the method I am referring to. What you shared is a different `increment` method which is on the `Builder`. That is not the problem.

The issue is based on the `increment` method that exists on the eloquent `Model`.

https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Model.php#L917-L929

This method calls the underlying `incrementOrDecrement` method which **does** triggers events, but doesn't acknowledge attributes that are set during the `updating` event, leading to false-positive results.

https://github.com/laravel/framework/blob/00894b89e42a9d707c6038084bbeb25422eed5b5/src/Illuminate/Database/Eloquent/Model.php#L952-L976

**Comment by crynobone** [comment]
If you really look at the code, it doesn't use `save()` and instead create a new query builder for insert and update, you may be able to return `false` from `updating` and other stuff from `updated` but that's about it.

**Comment by newtonjob** [comment]
@crynobone are you saying that this is an expected behavior? and not a bug?

```php
$product = Product::find(1);

$product->updated_by; // null

$product->increment('stock');

$product->wasChanged('updated_by'); // true
$product->updated_by; // 1

$product->refresh();

$product->updated_by; // null ???????????
```

**Comment by ProjektGopher** [comment]
@newtonjob yes this is not a bug. Replace your updating hook with this

```php
Product::updating(function ($product) {
    $product->update(['updated_by' => Auth::id()]);
})
```

Or leave it as-is, but call `$product->save();` before returning.

**Comment by newtonjob** [comment]
First, you should **never** execute another `->update(...)` during an `updating` event, as that'll end up in an endless dispatch of the `updating` event and eventually timeout.

Second, invoking `save()` after `increment()` doesn't make any difference since the `increment()` method already invokes `syncChanges()` internally before you even get a chance to call `save()`. 

So, by the time you call `save()`, the "fake" changes have already been synced, thus `save()` doesn't see any "dirty" attributes to actually save. 

Note that `syncChanges()` will sync all "dirty" attributes (even the ones that were never actually updated in db).

Moreso, doing a check with `$product->wasChanged('updated_by')` will return `true` when it actually never changed in db. 
You still don't think this is a bug?

**Comment by ProjektGopher** [comment]
Interesting - I'll have to keep digging into this. But I was under the impression that mass assignment through `->update()` doesn't trigger the `updating` and `updated` hooks
