### ISSUE TITLE
PHPRedis Cluster constants 

### ISSUE THREAD

**Issue by stemis** [laravel/framework#48361]
### Laravel Version

10.16.1

### PHP Version

8.1

### Description

The PHPRedis library removed `RedisCluster::` constants since `6.0.0`. Released on [pecl](https://pecl.php.net/package/redis) today 2023-09-11

However, these constants are still used:
https://github.com/laravel/framework/blob/9ae962af1d50b9b10e4779475513384c559adb39/src/Illuminate/Redis/Connectors/PhpRedisConnector.php#L191

My build started failing today now that version 6.0.0 is on pecl, and I didn't lock down the pecl version.

I'm using cluster mode and have a prefix and the code is failing with: 
```
Undefined constant RedisCluster::OPT_PREFIX
at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:191
```

The author of PHPREDIS recommends not using the constants of `RedisCluster` anymore but using the constants in `Redis` instead here: https://github.com/phpredis/phpredis/issues/2262#issuecomment-1327916568:
> We updated how we create these class constants which is when I noticed I was duplicating all the constants for both classes. I think we want to only define them for Redis in the next version (which will be a major version bump)
            
I believe they are also backwards compatible as they were duplicated in Redis.php already.

### Steps To Reproduce

1. Use phpredis 6.0.0 (by default installed via PECL since today)
2. Use cluster mode with a prefix

### Workaround:
Instead of using `pecl install redis`, use `pecl install redis-5.3.7`

**Comment by driesvints** [comment]
Thanks for the PR!

**Comment by ahmed-bhs** [comment]
@stemis what about if I'm using `sudo apt install php8.2-redis` in that case how to specify the 5.7.3 version of phpredis behind php8.2-redis ?

**Comment by ahmednabil2k** [comment]
@stemis Could you please provide me with your database.php configurations for phpredis cluster as I just keep getting an error `Couldn't map cluster keyspace using any provided seed`

**Comment by duycong2509** [comment]
@ahmednabil2k You should configure options in Redis like that
`'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX'),
            'password' => [env('REDIS_USERNAME'), env('REDIS_PASSWORD')],
        ],`
