### ISSUE TITLE
Add soft enum cast

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel/framework#48363]
### Laravel Version

9+

### PHP Version

8.1 +

### Database Driver & Version

-

### Description

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1182

replace to `tryFrom` return null if case exists

### Steps To Reproduce

Create error cast value enum

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
