### ISSUE TITLE
Separate `throttle:x,y` does not work like multiple RateLimiter's

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [laravel/framework#48374]
### Laravel Version

10.23.0

### PHP Version

8.2.4

### Database Driver & Version

latest

### Description

If we use
```php
// `.../routes/web.php`
Route::middleware('throttle:15,1')->group(function () {
    Route::get('/home', HomeController::class)->name('home');
});
Route::middleware('throttle:30,1')->group(function () {
    Route::get('/home2', Home2Controller::class)->name('home2');
});
```
we can no longer call `/home` after 15 `/home2` calls, but if we use
```php
// `...app/Providers/RouteServiceProvider.php`
RateLimiter::for('fifteen', function (Request $request) {
    return Limit::perMinute(15)->by($request->user()?->id ?: $request->ip());
});
RateLimiter::for('thirty', function (Request $request) {
    return Limit::perMinute(30)->by($request->user()?->id ?: $request->ip());
});

// `.../routes/web.php`
Route::middleware('throttle:fifteen')->group(function () {
    Route::get('/home', HomeController::class)->name('home');
});
Route::middleware('throttle:thirty')->group(function () {
    Route::get('/home2', Home2Controller::class)->name('home2');
});
```
we can.

Maybe I'm misunderstanding something about "Throttle" and "RateLimiter", but I think it shouldn't be like that.

### Steps To Reproduce

See `Description`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by gomzyakov** [comment]
@ghost Hello!

I have experienced similar behavior. Was it possible to obtain an answer from the mentioned sources?
