### ISSUE TITLE
`lazyById` doesn't check availability of id column in database response and silently ends up with endless loop 

### ISSUE THREAD

**Issue by decadence** [laravel/framework#48401]
### Laravel Version

10.22.0

### PHP Version

8.1.9

### Database Driver & Version

MySQL 5.7.39 (Windows 11)

### Description

If we use this code (we don't select `id` column):
```php
// select without id
$users = User::select("name")->lazyById(10);

foreach($users as $user) {
    // endless loop (generator) because lazyById will always return first element
}
```

So `foreach` will fall into endless loop and never ends if there are more than 1 page of results.

You can say that it's programmer's responsibility to include `id` in select but `chunkById` has this check and `lazyById` documentation doesn't say anything about `id` is required.

In the `chunkById` we have this code which verifies that response has `id` column.

```php
$lastId = data_get($results->last(), $alias);

if ($lastId === null) {
    throw new RuntimeException("The chunkById operation was aborted because the [{$alias}] column is not present in the query result.");
}
```

It seems logical to me to add such a check to `lazyById` as well.

### Steps To Reproduce
Create table with 100 records for example

```php
// select without id
$users = User::select("name")->lazyById(10);

foreach($users as $user) {
    // endless loop (generator) because lazyById will always return first element
}
```

**Comment by crynobone** [comment]
Seems like this is more a configuration issue rather that actual bug. The method name itself indicate the it would `cursor` by ID.

**Comment by decadence** [comment]
@crynobone What configuration do you mean? Did you read the issue? `chunkById` has this check, `lazyById` does not. This is inconsistent behaviour that leads to endless loop.
