### ISSUE TITLE
Model fields define accessors, and the accessor value is used to associate the model.

### ISSUE THREAD

**Issue by yde55188** [laravel/framework#48414]
### Laravel Version

9.33

### PHP Version

8.1

### Database Driver & Version

Mysql8.0

### Description

Model fields define accessors, and the accessor value is used to associate the model. For example, the accessor converts the middle 4 digits of the mobile phone number into ****. Then, when the association is made, it is associated according to the mobile phone number. When associated with (''), it is associated with the value of the accessor. How to solve it?

### Steps To Reproduce

User table defines mobile phone number field, defines mobile phone number field accessor, and uses mobile phone number to associate another table

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
