### ISSUE TITLE
FormRequest validation attribute problem

### ISSUE THREAD

**Issue by zsoltjanes** [laravel/framework#48417]
### Laravel Version

10.22

### PHP Version

8.1

### Description

I created a simple FormRequest in which I can validate multiple file mime-types. I wanted to give a custom name for them via Attribute but with wildcard not working. `The files.0 field must be a file of type: application/pdf, application/octet-stream.`

```
public function rules(): array
    {
        return [
            'files' => [
                'required',
                'array',
                'min:1',
                'max:3',
            ],
            'files.*' => [
                'required',
                File::types(['application/pdf', 'application/octet-stream'])
                    ->min('1kb')
                    ->max('10mb'),
            ],
        ];
    }
```

```
public function attributes(): array
    {
        return [
            'files.*' => 'file',
        ];
    }
```

It only works if I select the item from the array like this:

```
public function attributes(): array
    {
        return [
            'files.0' => 'file',
        ];
    }
```

### Steps To Reproduce

I pasted the code that I use.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by zsoltjanes** [comment]
@driesvints I don't want to tease you but it is a bug. Why do you think it's not an bug?
