### ISSUE TITLE
'mysqldump' is not recognized, windows 11, xampp or laragon

### ISSUE THREAD

**Issue by kakigorimochi** [laravel/framework#48444]
### Laravel Version

10.17.1

### PHP Version

8.1.10

### Database Driver & Version

MySQL 8.0.30 Winx64

### Description

I am currently having problems trying to export a database via blade.php on a windows environment, please see the images below. I have already tried possible fixes such as adding a `dump_binary_path` to `config/database.php` and the `path` to `windows path`.

I also ran `php artisan optimize` and `php artisan config:cache`

However, running the command in a prompt seems to be working just fine even without the possible fixes mentioned above.

![image](https://github.com/laravel/framework/assets/16938949/f9d90a59-0d70-42f5-9ce8-a033857bc451)

![image](https://github.com/laravel/framework/assets/16938949/b6550480-0e91-4bf9-b93e-7712df8edbd1)

![image](https://github.com/laravel/framework/assets/16938949/e8bb1b1f-43e1-4439-8354-3a1854cf4dfb)

![image](https://github.com/laravel/framework/assets/16938949/e3456844-dc04-4a85-bc84-34a5a1bae203)

### Steps To Reproduce

1. Create a simple blade with a button
![image](https://github.com/laravel/framework/assets/16938949/38b30cab-b84d-448b-8e29-45a8cc8e6ed5)
![image](https://github.com/laravel/framework/assets/16938949/3d12c928-1cc6-41ad-9136-d0cd2bc6df2c)

2. Write a code in a controller to execute `Artisan::call('schema:dump');`
![image](https://github.com/laravel/framework/assets/16938949/1887c5c8-0dc0-43b1-96d7-6059a9e73805)
![image](https://github.com/laravel/framework/assets/16938949/9904b9e9-c039-4447-a48a-9e10c066d4f7)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
