### ISSUE TITLE
Incorrect docblock for EnumeratesValues::ensure()

### ISSUE THREAD

**Issue by wimski** [laravel/framework#48443]
### Laravel Version

10.23.1

### PHP Version

8.2.3

### Description

The `@param` and `@return` declarations in the docblock of the `lluminate\Collections\Traits\EnumeratesValues::ensure()` method are incorrect.

https://github.com/laravel/framework/blob/ca546893cb98a633daf8be6fdd286faa05c9044d/src/Illuminate/Collections/Traits/EnumeratesValues.php#L315-L325

### Situation

The documentation says the following about the `$type` parameter:

> Primitive types such as `string`, `int`, `float`, `bool`, and `array` may also be specified:
>
> ```php
> return $collection->ensure('int');
> ```

https://laravel.com/docs/10.x/collections#method-ensure

### Issue

The usage with primitive type strings doesn't match the `class-string<TEnsureOfType>` type-hint and static analysis tools (like PHPStan) will complain about this (and rightly so).

### Solution

Since you can't type-hint _"a string representation of a primitive type"_ (so far at least), the only solution would be to create separate methods for all primitive types (`ensureInt`, `ensureBool`, etc.).

### Situation

The key type is hinted as `mixed`, although a template `TKey of array-key` is available.

### Issue

This makes a collection lose it's key type after applying the `ensure` method.

### Solution

```php
/*
 * @return static<TKey, TEnsureType>
 */
```

### Steps To Reproduce

1. Install Laravel
2. Install PHPStan
3. Create a file `app/Example.php` with the following code:
```php
<?php

declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Example
{
    /**
     * @param  Collection<array-key, mixed> $collection
     * @return void
     */
    public function paramIssue(Collection $collection): void
    {
        $collection->ensure('int');
    }

    /**
     * @param  array<int, Model> $array
     * @return Collection<int, Model>
     */
    public function returnIssue(array $array): Collection
    {
        return collect($array)->ensure(Model::class);
    }
}

```

Running static analysis will generate the following errors:
```
 ------ -----------------------------------------------------------------------------------------------------------------------------------
  Line   app/Example.php
 ------ -----------------------------------------------------------------------------------------------------------------------------------
  18     Parameter #1 $type of method Illuminate\Support\Collection<(int|string),mixed>::ensure() expects class-string<int>, string given.
  27     Method App\Example::returnIssue() should return
         Illuminate\Support\Collection<int, Illuminate\Database\Eloquent\Model> but returns
         Illuminate\Support\Collection<mixed, Illuminate\Database\Eloquent\Model>.
 ------ -----------------------------------------------------------------------------------------------------------------------------------
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by wimski** [comment]
> Instead, please submit a pull request [...]

Well, I'd like to propose the bug (and possible solutions) first before putting in the work. Otherwise I could spend quite some time on this, while it get's rejected in the end. That would be a waste.

**Comment by wimski** [comment]
@driesvints this is exactly why I open an issue first before putting in the work of a PR :disappointed: 

https://github.com/laravel/framework/pull/48460#issuecomment-1726636769

**Comment by driesvints** [comment]
I’m sorry you feel that way @wimski. But it’s better for us to look at a PR to see it’s impact and what it does.
