### ISSUE TITLE
Mismatched Attributes between Parent and Child Components in Laravel

### ISSUE THREAD

**Issue by PH7-Jack** [laravel/framework#48457]
### Laravel Version

10.24.0

### PHP Version

8.2

### Description

Hello,

**Description:**
While attempting to utilize attributes from a parent component within a child component, I've observed that the attribute values are not consistent. Notably, any attribute that matches a constructor parameter of the child component gets removed when rendering the slot.

-----

I hope this helps in understanding the issue. Let me know if you need any further clarification or examples.

### Steps To Reproduce

1. Create a laravel application
2. Create the **ComponentA**
    ```
    <?php
    
    namespace App\View\Components;
    
    use Illuminate\View\Component;
    
    class ComponentA extends Component
    {
        public function render()
        {
            return view('components.component-a');
        }
    }
    ```
    View
    ```
    <div>
         @json($attributes)
        
         <x-component-b>
             @json($attributes)
         </x-component-b>
    </div>
    ``` 
3. Create the **ComponentB**
    ```
    <?php
    
    namespace App\View\Components;
    
    use Illuminate\View\Component;
    
    class ComponentB extends Component
    {
        public function __construct(
            public $foo = null,
            public $xar = null,
        ) {
        }
    
        public function render()
        {
            return view('components.bomponent-b');
        }
    }
    ```
    
    View
    ```
    <div>
        {{ $slot }}
    </div>
    ```
4. Render the component A in some route 
`<x-component-a foo="bar" xar="baz" abc="1"  />`
You should see this
![image](https://github.com/laravel/framework/assets/38913462/11646eb0-a2d9-4175-a3dd-e711085e3f6b)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by PH7-Jack** [comment]
@crynobone Alright, see this [repository](https://github.com/PH7-Jack/laravel-bug-report-48457)

**Comment by crynobone** [comment]
Hey there,

From the reproducing code, this is to be the correct behavior. While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by PH7-Jack** [comment]
Hi, don't get me wrong, but why is it the correct behavior?

The $attributes rendered in the ComponentB slot are from the ComponentA.
The expected behavior is to render the correct attributes from the ComponentA in the ComponentB slot.

**Comment by PH7-Jack** [comment]
@crynobone Also, see this PR for more information. The attributes is reassigned with the nesting component attributes. Using a hash to differentiate the attributes can fix it 

https://github.com/laravel/framework/pull/48459
