### ISSUE TITLE
php artisan migrate --force error

### ISSUE THREAD

**Issue by jackkitley** [laravel/framework#48469]
### Laravel Version

10.24.0

### PHP Version

8.2.10

### Database Driver & Version

AWS Mysql Aurora

### Description

When building the docker image as we have been doing for 2 years it now fails on 

```
php artisan migrate --force

> [digital_dealer_php_uat 7/9] RUN php artisan migrate --force:
0.839
0.839    RuntimeException
0.839
0.839   Curl error (code 3): URL rejected: No host part in the URL
0.839
0.839   at vendor/monolog/monolog/src/Monolog/Handler/Curl/Util.php:54
0.840      50▕                     if ($closeAfterDone) {
0.840      51▕                         curl_close($ch);
0.840      52▕                     }
0.840      53▕
0.840   ➜  54▕                     throw new \RuntimeException(sprintf('Curl error (code %d): %s', $curlErrno, $curlError));
0.840      55▕                 }
0.840      56▕
0.840      57▕                 continue;
0.840      58▕             }
0.840
0.840       +12 vendor frames
0.840
0.840   13  artisan:35
0.840       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
0.841
```

### Steps To Reproduce

Ran the docker image which add laravel code to framework and runs a series of steps for build.

```
COPY --chown=${USERNAME}:${USERNAME} .env.uat $APP_HOME/.env
RUN php artisan optimize:clear
RUN php artisan storage:link
RUN npm ci && npm run build_uat
RUN php artisan migrate --force
RUN php artisan scribe:generate
```

Its failing on migration which is hasnt done in the past. Ive tested locally and on jenkins where it was initially  failing

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
