### ISSUE TITLE
DatabaseInspectionCommand ignoring --env option

### ISSUE THREAD

**Issue by naxvog** [laravel/framework#48462]
### Laravel Version

10.24.0

### PHP Version

8.2.10

### Description

It seems the db:* commands are ignoring the --env option displayed by the --help option.

### Steps To Reproduce

- create `.env.testing` and change `DB_*` variables
- run `php artisan db:show --env=testing` and the default `.env` file was used to instance the connection used

**Comment by crynobone** [comment]
![CleanShot 2023-09-20 at 08 17 15](https://github.com/laravel/framework/assets/172966/18c2250d-bf86-4943-8ee4-6a2f5c5677e6)

Unable to replicate the issue.

**Comment by naxvog** [comment]
Sorry my bad. Cannot reproduce in a new project either. Most likely it will be one of our dependencies rather than the framework itself.

Still, will investigate further.
Thank you for your time... and again: Sorry! Should have done my due diligence testing unmodified first.

**Comment by crynobone** [comment]
Feel free to open a new bug report if you able include complete reproducing steps.
