### ISSUE TITLE
The QueryBuilder upsert method is slow

### ISSUE THREAD

**Issue by keksum666** [laravel/framework#48461]
### Laravel Version

10.10

### PHP Version

8.2.10

### Database Driver & Version

MySql 8.1 For Linux

### Description

I'm using the upsert method to insert data into the database, but it's working very slowly. The actual database query itself executes quickly.

Telescope screenshot:
![image](https://github.com/laravel/framework/assets/47279073/0999c1d0-5313-4eaf-9b9b-c0b7456b6986)

Benchmark result:
![image](https://github.com/laravel/framework/assets/47279073/522e7815-d4f1-44a9-892c-52f7c5670f04)

### Steps To Reproduce

1. Create database
2. Fill 3000 items in array
3. Use upsert and Banchmark

Source code:
```
Benchmark::dd([
            'upsert' => fn () => DB::table('sellers')->upsert(
                array_values($sellers),
                [
                    'platform_id',
                    'external_id'
                ],
                [
                    'name',
                    'inn',
                    'ogrn',
                    'address'
                ]
            )
        ])
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
