### ISSUE TITLE
Bug when using Laravel directives in component attributes

### ISSUE THREAD

**Issue by joaopalopes24** [laravel/framework#48475]
### Laravel Version

10.24.0

### PHP Version

v8.2.10

### Description

When using Laravel components with Blade directives in component attributes, a bug has been identified in the rendering process. This bug results in incorrect HTML output, as the component attributes are not correctly interpreted, leading to undesired behavior.

### Steps To Reproduce

1. Create a Laravel component with the following structure:
```
<div {{ $attributes }}>
    {{ $slot }}
</div>
```

2. Render the component while passing an attribute that uses Laravel directives in a Blade view:
```
@php
    $bool = true;
@endphp
<x-test x-data="test({
    @if ($bool)
        test: 'test'
    @endif
})">
    Content
</x-test>
```

3. Observe the rendered HTML.

> **Current Behavior:**
>
> The rendered HTML includes unwanted attributes, resulting in unexpected output:
> ![image](https://github.com/laravel/framework/assets/45684782/8060c02a-9a23-4696-8bb2-efee4c0f9557)
> 
> **Expected Behavior:**
>
> The rendered HTML should correctly interpret and render the Laravel directives, resulting in the following expected output:
> ```
> <div x-data="test({
>     test: 'test'
> })">
> Content
> </div>
> ```

A repository demonstrating this bug can be found here: [repository](https://github.com/joaopalopes24/bug-component)

This issue affects the proper functioning of Laravel components when using directives within component attributes, causing incorrect HTML output.

**Comment by rafaeldevfem** [comment]
+1

**Comment by crynobone** [comment]
![CleanShot 2023-09-21 at 06 30 16](https://github.com/laravel/framework/assets/172966/57d3c9bc-8389-45b1-91bb-2437bb5a4d76)


The documentation already mentioned this is not supported. If free to submit a PR to add the feature.
