### ISSUE TITLE
Pagination and distinct in Postgres

### ISSUE THREAD

**Issue by zubosem** [laravel/framework#48478]
### Laravel Version

10.13.1

### PHP Version

8.2.8

### Database Driver & Version

PostgreSQL 14.2, compiled by Visual C++ build 1914, 64-bit

### Problem
In Postgres we have two ```DISTINCT``` statements. Simple ```DISTINCT``` and ```DISTINCT ON (column)```. It works differently. If first ```DISTINCT``` statement will remove repeated rows, the ```DISTINCT ON``` works like grouping and it requires grouping statements, ordering for distinct column and etc.

If we will going to laravel framework code we will see method [```runPaginationCountQuery```](https://github.com/laravel/framework/blob/22d4530c2fbe815223eba7fe1fc1005d1f4d6cce/src/Illuminate/Database/Query/Builder.php#L2883) used by query pagination. It need for calculating total rows in our query. But there are no distinct conditions or something. And if we add ```->paginate($perPage)``` to our query (see Steps To Reproduce) we will get 2 rows instead of 1. Because ```runPaginationCountQuery``` will remove our distinct for total row calculating.

```php
// src/Illuminate/Database/Query/Builder.php
...
// 2876 row
   /**
     * Run a pagination count query.
     *
     * @param  array  $columns
     * @return array
     */
    protected function runPaginationCountQuery($columns = ['*'])
    {
        if ($this->groups || $this->havings) {
            $clone = $this->cloneForPaginationCount();

            if (is_null($clone->columns) && ! empty($this->joins)) {
                $clone->select($this->from.'.*');
            }

            return $this->newQuery()
                ->from(new Expression('('.$clone->toSql().') as '.$this->grammar->wrap('aggregate_table')))
                ->mergeBindings($clone)
                ->setAggregate('count', $this->withoutSelectAliases($columns))
                ->get()->all();
        }

        $without = $this->unions ? ['orders', 'limit', 'offset'] : ['columns', 'orders', 'limit', 'offset'];

        return $this->cloneWithout($without)
                    ->cloneWithoutBindings($this->unions ? ['order'] : ['select', 'order'])
                    ->setAggregate('count', $this->withoutSelectAliases($columns))
                    ->get()->all();
    }
    
...

```

Adding ```$columns``` parameter for ```->paginate($perPage, $columns)``` method also did not worked because ```runPaginationCountQuery``` remove all columns statements and of course ```DISTINCT``` too.

But some recomedations tell us to add ```$columns``` parameter to ```->distinct($columns)``` like this:

```php

use App\Models\Organization;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class User extends Model
{
...

    public function getOrganizationsWithPermission($permission_id): BelongsToMany
    {
        return $this->belongsToMany(Organization::class, 'user_roles', 'user_id', 'organization_id')
            ->join('roles', 'roles.id', '=', 'user_roles.role_id')
            ->join('role_permissions', 'role_permissions.role_id', '=', 'roles.id')
            ->join('permissions', 'permissions.id', '=', 'role_permissions.permission_id')
            ->where('permissions.id', '=', $permission_id)
            // like this
            ->distinct('organization.id');
            // or like this
            // ->distinct(['organization.id']);
    }

...
```
In this case with Postgres we will get ```DISTINCT ON``` in Laravel and we can not using this query for example _dynamic sorting_ because we will need to add firstly ```ORDER BY organizations.id``` statement for our ```DISTINCT ON```. After that we will need to add grouping for columns and etc. Our construction will be badly working for continue querying.

But as we see in code [```runPaginationCountQuery```](https://github.com/laravel/framework/blob/22d4530c2fbe815223eba7fe1fc1005d1f4d6cce/src/Illuminate/Database/Query/Builder.php#L2885C39-L2885C39) we have condition with checking groups and havings. If we have query with grouping statement ```runPaginationCountQuery``` using our query as subquery without column changes. And it works!

### Conclusion
If we have total counting for our queries with groupping like wrapping as subquery, why we can not using it for simple ```DISTINCT```?
Thank you.

### Steps To Reproduce

1. Add 4 models in Laravel: **_User_**, **_Organzation_**, **_Role_**, **_Permission_**
2. **_User_**: id, name
3. **_Organization_**: id, name
4. **_Role_**: id, name
5. **_Permission_**: id, name
6. Add table for linking roles with permissions ```role_permissions```: role_id, permission_id with unique index (role_id, permission_id).
7. Add table for linking users with roles and organizations ```user_roles```: role_id, organization_id and user_id with unique index (role_id, organization_id, user_id).
8. Fill our tables:
```sql
INSERT INTO users (id, name) VALUES (1, 'user');
INSERT INTO organizations (id, name) VALUES (1, 'org');
INSERT INTO roles (id, name) VALUES (1, 'role1'), (2. 'role2');
INSERT INTO permissions (id, name) VALUES (1, 'permission');

-- add same permission to both roles
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 1), (2, 1);

-- now we have 2 roles with same permission
-- we need to add roles to users in organization
-- our user will have both roles
INSERT INTO user_roles (role_id, organization_id, user_id) VALUES (1, 1, 1), (2, 1, 1);

-- now we have 1 user who have 2 roles in 1 organization
```
In Laravel we can build ```BelongsToMany``` relation:
```php

use App\Models\Organization;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class User extends Model
{
...

    public function getOrganizationsWithPermission($permission_id): BelongsToMany
    {
        return $this->belongsToMany(Organization::class, 'user_roles', 'user_id', 'organization_id')
            ->join('roles', 'roles.id', '=', 'user_roles.role_id')
            ->join('role_permissions', 'role_permissions.role_id', '=', 'roles.id')
            ->join('permissions', 'permissions.id', '=', 'role_permissions.permission_id')
            ->where('permissions.id', '=', $permission_id)
            ->distinct();
    }

...
```
If we run this query we will get normal result. But If we need append pagination we will have problem with that (see Description).

**Comment by zubosem** [comment]
I need little review from you for decide it this good fix or maybe it will break logic in other databases?
For this fix we need to change just single line in code but I dont want that we will have problems with other databases or maybe problems with perfomance.  Need expert consultation.
Maybe this problem will be fix with another method.

**Comment by driesvints** [comment]
I realize a lengthy description was given here. However, we've had [many issues](https://github.com/laravel/framework/issues?q=distinct+pagination+is%3Aissue+is%3Aclosed) in the past about distinct and pagination all concluding it's not possible to combine these. If you want, feel free to send in a non-breaking PR that could add support. Thanks.
