### ISSUE TITLE
I have configured the APP in the. env configuration of the root directory of my project APP_ ENV=local, but when starting the project to access the xdebug debugging, it was found that the default. env. file was still loaded, but it was not the corresponding environment file for local. Why is this. I also included screenshots

### ISSUE THREAD

**Issue by jasonccs** [laravel/framework#48470]
### Laravel Version

10.23.1

### PHP Version

8.2.3

### Database Driver & Version

5.7

### Description

![image](https://github.com/laravel/framework/assets/17975766/9f75cadb-482b-4f7d-a6f9-018f17d0a0d6)
![73c455d2c2d3f9e2292b4f79595835a](https://github.com/laravel/framework/assets/17975766/abe2578b-365b-42bb-bc5a-6fd8bc45e4a8)

### Steps To Reproduce

Work environment windows+php8.2.3+larave10.23.1

I have configured the APP in the. env configuration of the root directory of my project_ ENV=local, but when starting the project to access the xdebug debugging, it was found that the default. env. file was still loaded, but it was not the corresponding environment file for local. Why is this. I also included screenshots

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by jasonccs** [comment]
https://laravel.io/forum/work-environment-windowsphp823larave10231-i-configure/edit  

  you see

**Comment by jasonccs** [comment]
能帮我解决吗，
