### ISSUE TITLE
DB::table() unexpected behavior when providing database enclosed with backtick

### ISSUE THREAD

**Issue by aabril07** [laravel/framework#48485]
### Laravel Version

10.4.1

### PHP Version

8.1.2

### Description

When providing database and table name inside query builder, it is expectedly adding many backticks enclosing the already enclosed database name.

### Steps To Reproduce

Example:
DB::table("\`transaction-service\`.transactions") the query build will provide "SELECT * FROM \`\`\`transactions-service\`\`\`.\`transactions\`", trying to enclose the already enclosed database name.

**Comment by driesvints** [comment]
This isn't supported sorry.

**Comment by aabril07** [comment]
Hi @driesvints, apologies you might have read my earlier report. This is my first time reporting bug here on github and didnt expect the output until i read it, i already clean up the my initial report. Please try reading it again. Thank you.

**Comment by driesvints** [comment]
You don't need to add backticks yourself.
