### ISSUE TITLE
Using '*' and '/' together in the Validator attribute path is not handled correctly

### ISSUE THREAD

**Issue by naotake51** [laravel/framework#48489]
### Laravel Version

10.24.0

### PHP Version

8.2.10

### Description

If you pass a path using `*` and `/` such as `*.email/id` to the second argument of `\Illuminate\Validation\Validator::make`, an error will occur at the following location.

https://github.com/laravel/framework/blob/v10.24.0/src/Illuminate/Validation/ValidationRuleParser.php#L152

```php
> Validator::make([['email/id' => '1']], ['*.email/id' => 'required|string'])->validate()

   WARNING  preg_match(): Unknown modifier 'd' in vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php on line 152.

= []

> Validator::make([['email|id' => '1']], ['*.email|id' => 'required|string'])->validate()
= [
    [
      "email|id" => "1",
    ],
  ]

> Validator::make(['email/id' => '1'], ['email/id' => 'required|string'])->validate()
= [
    "email/id" => "1",
  ]
```

In the following places, preg_quote is used to escape special characters, but / is not escaped.
https://github.com/laravel/framework/blob/v10.24.0/src/Illuminate/Validation/ValidationRuleParser.php#L147

https://www.php.net/manual/en/function.preg-quote.php
> Note that / is not a special regular expression character.

So I think '/' needs to be escaped individually.

```php
preg_match('/^'.$pattern.'\z/', $key)
```

```php
preg_match('/^'.preg_match('/^'.str_replace('/', '\/', $pattern).'\z/', $key)'\z/', $key)
```

### Steps To Reproduce

Run the following

```php
 Validator::make([['email/id' => '1']], ['*.email/id' => 'required|string'])->validate()
```

**Comment by driesvints** [comment]
This is not supported sorry. Please refrain from using characters like `/` in your validation keys.
