### ISSUE TITLE
reset(): Calling reset() on an object is deprecated in /var/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php on line 161

### ISSUE THREAD

**Issue by oktaykalfa** [laravel/framework#48548]
### Laravel Version

9.52.15

### PHP Version

8.1.23

### Description

Hello, 

This error is being generated continuously and it being written to "deprecation" log file. How can i resolve this? 

Thanks.

 production.WARNING: reset(): Calling reset() on an object is deprecated in /var/www/vendor/laravel/framework/src/Illuminate/Collections/helpers.php on line 161
![klogg_Ln1vf8qD8s](https://github.com/laravel/framework/assets/47442988/b7f6645c-e617-499d-bf5c-1551e70f16dc)

### Steps To Reproduce

I do not do anything to reproduce this. It has been generating by system.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
