### ISSUE TITLE
Why laravel don't escape '_' and '%' in like by default?

### ISSUE THREAD

**Issue by ErfanBahramali** [laravel/framework#48556]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

MySQL 8.0.34-0ubuntu0.22.04.1

### Description

I want to provide a search for the users section

If a letter is entered, it should be searched in the users in the database

But some inputs like '%' and '_' return all records

I don't want all user names to be returned

### Steps To Reproduce

Example:

`User::where('name','LIKE',"%{$search}%")->get();`

If the `$search` variable is equal to '`%`' or '`_`', all records will be returned

https://stackoverflow.com/questions/22749182/laravel-escape-like-clause

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
