### ISSUE TITLE
Invalid `incrementEach` method signature

### ISSUE THREAD

**Issue by TheAndrey** [laravel/framework#48551]
### Laravel Version

10.24.0

### PHP Version

8.1.21

### Description

Hello. I am trying to increase the values of two columns of the table using the following query.

```php
$affected = ModelClass::where('user_id', '=', $user->id)
    ->incrementEach(['total' => 1, 'total_monthly' => 1], ['updated_at' => Date::now()]);
dump($affected);
```

According to phpdoc, the method should return `int` (_the number of updated records_), but in reality I get the object `Illuminate\Database\Eloquent\Builder`. That's not what I need. At the same time, the values in the database are updated.

There is no such problem with the similar `increment()` method. It's magic 🧙‍♂️

### Steps To Reproduce

The code example is given above.

I have solved this problem so far by accessing the table by name, without using the model class.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by TheAndrey** [comment]
@driesvints 
I think that phpdoc is correct, but the operation of the method does not correspond to it. In theory, it should return the number of affected rows.

**Comment by driesvints** [comment]
Changing a behavior on a method can't be done on a minor/patch release. In this case most likely, the docbloc is incorrect.
