### ISSUE TITLE
`collect()->map(trim(...))` not working (First class callable syntax)

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#48572]
### Laravel Version

10*

### PHP Version

8.2

### Description

When you pass php functions as first-class callable into the map method, surprisingly, it doesn't work:

### Steps To Reproduce

```php
collect([' a  ', ' b '])->map(trim(...)); //not working ❌ 
```

But this working:

```php
array_map(trim(...), ['a ', ' b', ' c ']); //working ✅
```

Note that the first class callable also creates closure under the hood: https://www.php.net/manual/en/functions.first_class_callable_syntax.php

**Comment by mpyw** [comment]
You should do this:

```php
collect([' a  ', ' b '])->map(fn ($value) => trim($value));
```

Because `trim` has the following signature; optional second argument: `$characters`

```php
trim(string $string, string $characters = ' \n\r\t\v\x00')
```

**Comment by timacdonald** [comment]
@mpyw it correct - but I also hit this and was like "what the" ha!

**Comment by foremtehan** [comment]
Ah good catch, `$keys` is the problem

https://github.com/laravel/framework/blob/f402d3f235a6e93e6d1f70da8095b9eabc41c4b5/src/Illuminate/Collections/Arr.php#L558

**Comment by kdg-cwood** [comment]
This is a time bomb. I wasted several hours slowly tracking this down in a function that processes data in bulk. Can we maybe get a warning calling this out in the docs. I understand that we shouldn't necessary guarantee that Arr::map and collect()->map() work identically to array_map; but it's an easy mixup to make.

**Comment by kdg-cwood** [comment]
This is especially irritating because the second parameter to `trim` is a string and the second parameter to `map`'s callback is an int, at least according to Laravel docs.
