### ISSUE TITLE
incrementEach and decrementEach dont respect where query when used for eloquent model

### ISSUE THREAD

**Issue by hanicab** [laravel/framework#48595]
### Laravel Version

9.52.15

### PHP Version

8.1.19

### Database Driver & Version

MySQL 8.0.33 for macOS 13.4.1 on arm64 (Homebrew)

### Description

incrementEach() and decrementEach() dont respect where condition when used for eloquent model.

```
$user = User::where('shop_id', 1)->first();
$user->decrementEach(['counter' => 1, 'balance' => 100]);
```

All users in the table are decremented whatever 'shop_id' they have.

Please note that the problem is only if executed via eloquent model , but works correctly if executed via direct query as below 
```
User::where('shop_id', 1)->decrementEach(['counter' => 1, 'balance' => 100]); // works correctly
```

### Steps To Reproduce

incrementEach() and decrementEach() dont respect where condition when used for eloquent model.

```
$user = User::where('shop_id', 1)->first();
$user->decrementEach(['counter' => 1, 'balance' => 100]);
```

All users in the table are decremented whatever 'shop_id' they have.

Please note that the problem is only if executed via eloquent model , but works correctly if executed via direct query as below 
```
User::where('shop_id', 1)->decrementEach(['counter' => 1, 'balance' => 100]); // works correctly

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by thomasmokuaomweri2011** [comment]
Please show some love to the newly introduced fix PR https://github.com/laravel/framework/pull/57302
This could go into the major release as it has a BC
