### ISSUE TITLE
Http Facade Fake Does Not Override Correctly

### ISSUE THREAD

**Issue by mehradsadeghi** [laravel/framework#48596]
### Laravel Version

10.2.6

### PHP Version

8.2.3

### Description

There seem to be a problem (probably a bug) that prevents `Http` facade perform multiple fakes correctly. If you fake a path e.g. `/test` twice (or more), the first fake will be always the one that gets executed. 

Imagine a scenario where you have a general (global) fake for a third-party dependency in your `TestCase` (aka BaseTestCase) in order to prevent real http requests when running tests, and you need to override this global fake occasionally in some test cases, which seems to be impossible currently.

### Steps To Reproduce

This is a simple test faking the `/test` path multiple times and it always gets the first fake's http status code:

```php
class ExampleTest extends TestCase
{
    public function test_http_fake(): void
    {
        Http::fake(['test' => Http::response(['error' => 'server error'], 500)]);
        Http::fake(['test' => Http::response(['error' => 'unauthorized'], 401)]);

        echo Http::get('test')->status(); // 500

        Http::fake(['*' => Http::response(['message' => 'ok'], 200)]);

        echo Http::get('test')->status(); // 500
    }
}
```

**Comment by timacdonald** [comment]
@mehradsadeghi to prevent making real requests, you should call the `Http::preventStrayRequests` method in your testsuite's setup.

Having a global fake and overriding things isn't currently supported.

https://laravel.com/docs/10.x/http-client#preventing-stray-requests
