### ISSUE TITLE
Problem when one command calls another multiple times

### ISSUE THREAD

**Issue by Rattone** [laravel/framework#48608]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

When a command calls another command several times, with its signature, this is not reinitialized so the properties that are modified in the first call are found in the second

### Steps To Reproduce

Run these commands
`php artisan make:command Foo`
`php artisan make:command Bar`

in Foo command put:
```
protected $signature = 'foo';

public function handle()
{
    $this->call('bar');
    $this->call('bar');
    $this->call('bar');
    return 0;
}
```

in Bar command put:
```
protected $signature = 'bar';

protected array $numbers = [];

public function handle()
{
    $this->numbers[] = rand(0, 100);
    dump($this->numbers);
}
```
Then run: `php artisan foo`

**Comment by Rattone** [comment]
![image](https://github.com/laravel/framework/assets/7362607/fecc4a89-9126-49d0-b435-19e2445c56c5)

**Comment by Carnicero90** [comment]
@driesvints then I don't particularly get why Illuminate\Console\Command@resolveCommand actually creates a new instance if you call the command via class name and not via signature. Is there a practical reason for that?
