### ISSUE TITLE
Plagued by Semicolon

### ISSUE THREAD

**Issue by austingrove** [laravel/framework#48618]
### Laravel Version

10.22.0

### PHP Version

8.1

### Description

I'm having an issue where a semicolon is showing up on the top of all of my pages and even shows up at the beginning of outputs from my "php artisan" commands. 

![Screen Shot 2023-10-03 at 5 56 19 AM](https://github.com/laravel/framework/assets/44840323/a6986f24-6286-473b-bbca-195de9399e49)

One thing to note on my pages the content that should be in my head shows up in the body. I've put my layout below. I've removed everything in the layout page without success

% php artisan -v
;Laravel Framework 10.22.0

This also breaks my sessions so I'm currently unable to get past my login screen. 

I think it may have affected my laravel installer as well because I am unable to complete the "laravel new <project>" workflow

`<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}" />

        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
        />
    </head>
    <body class="h-100" style="background-color:#F8F9FA;">
        

        {{ $slot }}

        
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.10.377/build/pdf.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>

        
        
        <script src="/pdfselector.js"></script>
    </body>
</html>`

I'm fairly novice so if you request any outputs, I'd appreciate if you could provide the commands. 

### Steps To Reproduce

I honestly have no clue how this happened. It doesn't happen in the other Laravel projects on my computer.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
