### ISSUE TITLE
Cannot use pivot model's (intermediate table model for BelongsToMany) query scopes

### ISSUE THREAD

**Issue by Rike-cz** [laravel/framework#48617]
### Laravel Version

10.22

### PHP Version

8.1

### Description

It's legal to have intermediate table model for BelongsToMany relationship and it's legal to have query scopes within this model.
But, how can I make query using them when making relationship query? Missing implementation.
```
$someModel->belongsToManyRelationship()->wherePivot(fn ($query) => $query->isValid())->...
```

### Steps To Reproduce

```
class MyPivot extends Pivot
{
   public function scopeIsValid($query)
   { ... }
}
...

class SomeModel extends Model
{
    public function belongsToManyRelationship()
    {
        return $this->belongsToMany(AnotherModel::class)->using(MyPivot::class);
    }
}
...

$someModel->belongsToManyRelationship()->wherePivot(fn ($query) => $query->isValid())->...
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dmikam** [comment]
I have similar problem. Just leaving here links to the threads I created on [Stackoverflow](https://stackoverflow.com/questions/77301852/laravel-eloquent-belongstomany-and-globalscopes) and [Laracast](https://laracasts.com/discuss/channels/eloquent/belongstomany-and-globalscopes)
