### ISSUE TITLE
Double render 500 error if `APP_KEY` is empty

### ISSUE THREAD

**Issue by TENIOS** [laravel/framework#48627]
### Laravel Version

10.26.2

### PHP Version

8.2.10

### Description

If `.env` file have empty `APP_KEY` and `APP_DEBUG` set to `false` it render two 500 errors on one page.

![Double render 500 code page](https://github.com/laravel/framework/assets/40282681/6364b9e7-03e3-4e5e-9520-dd3a8dcda4ab)

![Page code](https://github.com/laravel/framework/assets/40282681/620e20a3-9cbe-4a94-a6b1-279533275c8f)

### Steps To Reproduce

* Create a new fresh Laravel app
* Copy `.env.example` and rename to `.env`
* Set `APP_DEBUG` to `false`
* Run `php artisan serve` and open `127.0.0.1:8000`

**Comment by driesvints** [comment]
APP_KEY can never be empty. I realize the double error isn't ideal nor helpful but every install method of installing Laravel will set this for you.
