### ISSUE TITLE
symfony/psr-http-message-bridge v2.3.1 loses the transformations of ConvertEmptyStringsToNull middleware

### ISSUE THREAD

**Issue by tspencer244** [laravel/framework#48626]
### Laravel Version

10.26.2

### PHP Version

8.1.24

### Description

Recreating JSON request bodies was changed in v2.3.1 of `symfony/psr-http-message-bridge`.

https://github.com/symfony/psr-http-message-bridge/commit/ef03b6dfb040da9615a11679306d707da7fee51f

The JSON request body is read using `$symfonyRequest->getContent()` instead of `$symfonyRequest->getPayload()->all()` in v2.3.0, and `$symfonyRequest->request->all()` in v2.2.0.

Because of this, the modifications made to a Laravel request object by the `ConvertEmptyStringsToNull` middleware gets lost, i.e. empty string values for JSON request keys are not converted to `null`, and remain as empty strings.

This only affects controller methods that have `$request` type hinted as `Psr\Http\Message\ServerRequestInterface`.

### Steps To Reproduce

I have created a test in a new repository to demonstrate the issue:

```shell
git clone https://github.com/HealthengineAU/laravel-bug-report
```

Tests should fail:

```shell
php artisan test
```

If we install the previous version:

```shell
composer require symfony/psr-http-message-bridge=2.3.0
```

We should see the tests pass:

```
php artisan test
```

**Comment by timacdonald** [comment]
I've created a PR to fix this. We can track it there: https://github.com/laravel/framework/pull/48696
