### ISSUE TITLE
Table default: Argument #3 ($subject) must be of type array|string, Illuminate\Database\Query\Expression given

### ISSUE THREAD

**Issue by muuvmuuv** [laravel/framework#48625]
### Laravel Version

10.x

### PHP Version

8.1

### Database Driver & Version

MariaDB 10 macos ARM

### Description

Previously I used the below expression to set a default on uuid tables but in the latest release this throws an expception.

```php
$table->char('uuid', 36)->default(DB::raw('UUID()'))->change();
```

Relevant part in code is: vendor/doctrine/dbal/src/Platforms/AbstractMySQLPlatform.php:1388

### Steps To Reproduce

```php
		Schema::table('app_logs', function (Blueprint $table) {
			$table->uuid()->default(DB::raw('(UUID())'))->change();

			$table->timestamp('created_at')->useCurrent();
			$table->timestamp('updated_at')->nullable()->useCurrentOnUpdate();
		});
```

**Comment by driesvints** [comment]
I don't think we ever documented this usage?

**Comment by muuvmuuv** [comment]
Thats partly true, default is documented and I cannot find any other API to set default as an expression. What would you suggest? IMO Laravel should by default set a default on stuff like above but this is another topic.

**Comment by hafezdivandari** [comment]
You may remove `doctrine/dbal` or call `Schema::useNativeSchemaOperationsIfPossible()` on your `AppServiceProvider`.
