### ISSUE TITLE
[10.x] array to string conversion in upsert

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel/framework#48638]
### Laravel Version

10+

### PHP Version

8.1+

### Database Driver & Version

*

### Description

```
$arrays = [
    [
        'url'  => 'https://laravel.com',
        'data' => [
            'version' => '10.26',
            'php'     => '8.2.7',
        ],
    ],
];

Model::upsert($arrays, ['url'], ['data']);
or 
Db::table('table')->upsert($arrays, ['url'], ['data'])
```

### Steps To Reproduce

```
$arrays = [
    [
        'url'  => 'https://laravel.com',
        'data' => [
            'version' => '10.26',
            'php'     => '8.2.7',
        ],
    ],
];

Model::upsert($arrays, ['url'], ['data']);
or 
Db::table('table')->upsert($arrays, ['url'], ['data'])
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by CrazyBoy49z** [comment]
This bags

**Comment by CrazyBoy49z** [comment]
[#48593](https://github.com/laravel/framework/pull/48593/files)
