### ISSUE TITLE
DatabaseUuidFailedJobProvider + mongoDB has error Attempt to read property "uuid" on array

### ISSUE THREAD

**Issue by zsinryu** [laravel/framework#48675]
### Laravel Version

10.x

### PHP Version

8.x

### Database Driver & Version

MongoDB 4.x

### Description

Hi team,

I found an issue when retry a failed job.
The failed job is setup with `mongodb`. 

```
'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
        'database' => env('QUEUE_FAILED_DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],
```
    
I noticed, the $record here return as `array` instead of `object`
```
if ($record = $this->getTable()->where('uuid', $id)->first()) {
            $record->id = $record->uuid;
            unset($record->uuid);
        }
```

Do I miss any setting?

Thanks

    

### Steps To Reproduce

1. Setup both `jobs` and `failed_jobs` to use mongodb
2. Add a failed job record
3. Retry that failed job with command `php artisan queue:retry [uuid]`

**Comment by driesvints** [comment]
We don't support MongoDB sorry
