### ISSUE TITLE
Str::password() does not always generate password with numbers

### ISSUE THREAD

**Issue by mcadet** [laravel/framework#48677]
### Laravel Version

10.22.0

### PHP Version

8.2.10

### Description

Actually, the helper Str::password() does not always generate password containing numbers.

### Steps To Reproduce

Simply use Pest as it allows to repeat a test, creating a password using Str::password() with default parameters:

```php
test('generate password', function () {
    $password = \Illuminate\Support\Str::password(
        length: 32,
        letters: true,
        numbers: true,
        symbols: true,
        spaces: false,
    );
    expect(
        str($password)->contains(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))
        ->toBeTrue();
}
)->repeat(100);
```

**Comment by rodrigopedra** [comment]
IMO, it is not a bug.

The parameters refer to allowed character's categories that MAY be on the generated password.

Nowhere in the documentation, it states those categories MUST be on the output.

note: MAY and MUST are in caps, like in RFC vocabulary, not like a rant

**Comment by crynobone** [comment]
While this may not be considered a bug, if we rely on `Str::password()` to generate a secure password and use the same logic for password validation, the provided password will fail if it's expected to contain symbols but doesn't have one because `Str::password()` **MAY** contain symbol instead of **MUST** contain symbol.

**Comment by daliendev** [comment]
A few months ago, I worked on something similar and submitted a PR. Maybe it can help.

https://github.com/laravel/framework/pull/48142
