### ISSUE TITLE
FormRequest side effects after introducing Laravel Precognition

### ISSUE THREAD

**Issue by lucaspanik** [laravel/framework#48685]
### Laravel Version

v10.27.0

### PHP Version

8.2.11

### Description

In version [9.32.0](https://github.com/laravel/framework/blob/v9.32.0/src/Illuminate/Foundation/Http/FormRequest.php#L112) and earlier, the validationData() method was called before the rules() method in the FormRequest, which provided the possibility of changing the data before being sent to rules().

https://github.com/laravel/framework/blob/aae3b59f82434176546c9dd10804adda16da5278/src/Illuminate/Foundation/Http/FormRequest.php#L110-L116

As can be seen in the print below.
![image](https://github.com/laravel/framework/assets/7035554/3a498f9f-0f56-4798-bd32-acbee952bf5a)

---

With the acceptance of PR [9.x] Introduce Laravel Precognition #44339, a "side effect" was introduced in the sequences in which methods are called.

From version [9.33.0](https://github.com/laravel/framework/blob/v9.33.0/src/Illuminate/Foundation/Http/FormRequest.php#L112) and later, the rules() method is being called before validationData(), not giving the possibility of making changes to the data before being sent to rules();

https://github.com/laravel/framework/blob/13665b7e15dbcbecb3651acc19ba8818da6fa0a9/src/Illuminate/Foundation/Http/FormRequest.php#L110-L122

As can be seen in the print below.
![image](https://github.com/laravel/framework/assets/7035554/79966a99-a269-415b-8778-94b4bc615fa5)

---

### I confirmed that the same code is in version 10 as well:
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Http/FormRequest.php#L119C96-L119C96
https://github.com/laravel/framework/blob/6bfd7550c94ef8666b3312cae577ddd30db03e03/src/Illuminate/Foundation/Http/FormRequest.php#L117-L133

### Steps To Reproduce

Use the code below to notice that there is a change in the sequence in which the methods are executed:

```php
// Route

Route::post('home', [HomeController::class, 'index']);

// Controller
class HomeController extends Controller
{
    public function index(HomeTestRequest $request)
    {
        dd('HomeController');        
    }
}

// Form Request
class HomeTestRequest extends FormRequest
{
    /**
     * Get data to be validated from the request.
     *
     * @return array
     */
    public function validationData()
    {
        dump('validationData');

        $this->merge([
            'foo' => 'bar',
        ]);

        return $this->all();
    }

    protected function rules()
    {
        dump('rules');

        dump($this->all());

        return [];
    }
}
```

**Comment by lucaspanik** [comment]
Possibility of change 1 (Arrow Functions):

```php
   /**
     * Create the default validator instance.
     *
     * @param  \Illuminate\Contracts\Validation\Factory  $factory
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function createDefaultValidator(ValidationFactory $factory)
    {
        $rules = fn () => method_exists($this, 'rules') ? $this->container->call([$this, 'rules']) : [];

        $validator = $factory->make(
            $this->validationData(), $rules(),
            $this->messages(), $this->attributes()
        )->stopOnFirstFailure($this->stopOnFirstFailure);

        if ($this->isPrecognitive()) {
            $validator->setRules(
                $this->filterPrecognitiveRules($validator->getRulesWithoutPlaceholders())
            );
        }

        return $validator;
    }
```
    
---
    
 Possibility of change 2 (remove variable):

```php
   /**
     * Create the default validator instance.
     *
     * @param  \Illuminate\Contracts\Validation\Factory  $factory
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function createDefaultValidator(ValidationFactory $factory)
    {
        $validator = $factory->make(
            $this->validationData(), 
            method_exists($this, 'rules') ? $this->container->call([$this, 'rules']) : [],
            $this->messages(), 
            $this->attributes()
        )->stopOnFirstFailure($this->stopOnFirstFailure);

        if ($this->isPrecognitive()) {
            $validator->setRules(
                $this->filterPrecognitiveRules($validator->getRulesWithoutPlaceholders())
            );
        }

        return $validator;
    }
```
---

Possibility of change 3 (create a variable for validationData):

```php
   /**
     * Create the default validator instance.
     *
     * @param  \Illuminate\Contracts\Validation\Factory  $factory
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function createDefaultValidator(ValidationFactory $factory)
    {
        $validationData = $this->validationData();
        $rules = method_exists($this, 'rules') ? $this->container->call([$this, 'rules']) : [];

        $validator = $factory->make(
            $validationData, $rules,
            $this->messages(), $this->attributes()
        )->stopOnFirstFailure($this->stopOnFirstFailure);

        if ($this->isPrecognitive()) {
            $validator->setRules(
                $this->filterPrecognitiveRules($validator->getRulesWithoutPlaceholders())
            );
        }

        return $validator;
    }
    ```

**Comment by timacdonald** [comment]
@lucaspanik although I can see the order of method execution has changed, I'm not really sure what we are trying to do here so I might need a bit more context so i can write a test for this.

> not giving the possibility of making changes to the data before being sent to rules();

The data is not sent to the `rules` method. I think this is what I'm tripping up on.

These two methods are rather independent, so I can only assume you are somehow creating a dependency between them with stored state?

If you could you provide a code snippet that shows how this is functionally impacting your app I can dig in and try and get this sorted for you.

Thanks.

**Comment by NickSdot** [comment]
@lucaspanik isn't for your scenario `prepareForValidation()` the better choice?

https://laravel.com/docs/10.x/validation#preparing-input-for-validation

**Comment by lucaspanik** [comment]
Hi @NickSdot, thanks for your interaction.

I actually used `validationData()` because it existed/was born before `prepareForValidation()`


Jun 17, 2016 - `validationData()`
https://github.com/laravel/framework/pull/13914

Nov 7, 2016 - `prepareForValidation()`
https://github.com/laravel/framework/commit/36b0f5009a07e3bff3d64f6a42435a3dec8d9fd7

But I evaluated my code and using `prepareForValidation()` it worked as expected.

and that brought me a question:

If the correct option would be to use `prepareForValidation()`, what purpose would the `validationData()` method be for?

**Comment by timacdonald** [comment]
@lucaspanik `prepareForValidation` is a hook to do any required "work" before validation where as `validationData` is intended to return the data to be validated.

Gonna close this as I agree that `prepareForValidation` should be used in this case and this ordering has been released for a while now.
