### ISSUE TITLE
$dateFormat is invalid for json_encode serial number model. You must define serializeDate to change it.

### ISSUE THREAD

**Issue by aogg** [laravel/framework#48697]
### Laravel Version

^8.83

### PHP Version

7.4

### Description

Invalid
    protected $dateFormat = 'U';

Should be changed to
```
    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date instanceof \DateTimeImmutable ?
            \Carbon\CarbonImmutable::instance($date)->__toString() :
            \Illuminate\Support\Carbon::instance($date)->__toString();
    }
```

### Steps To Reproduce

Should be changed to
```
    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date instanceof \DateTimeImmutable ?
            \Carbon\CarbonImmutable::instance($date)->__toString() :
            \Illuminate\Support\Carbon::instance($date)->__toString();
    }
```

**Comment by aogg** [comment]
https://github.com/briannesbitt/Carbon/issues/1870

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
