### ISSUE TITLE
compileDeleteWithJoins incorrect behaviour with MySQL and inner join

### ISSUE THREAD

**Issue by Glennmen** [laravel/framework#48690]
### Laravel Version

10.26.2

### PHP Version

8.1.23

### Database Driver & Version

MySQL 8.0.32-1.2.11-server

### Description

When using `getGrammar()->compileDelete()` on a query builder that has a join in it, in case of an inner join the compiled delete statement is incorrect.

According to [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/delete.html) it should contain both tables in order to delete rows in both tables.
The way it currently is implemented it will only delete data from the first table and not the joined data from the referenced table.

From tinker:
Current behaviour:
```
>>> $query->limit(1000)->getGrammar()->compileDelete($query->toBase())
=> "delete `commands` from `commands` inner join `statuses` on `commands`.`id` = `statuses`.`model_id` where `commands`.`created_at` < ? and `commands`.`action` in (?, ?, ?, ?, ?) and `statuses`.`model_type` = ? and `parent_uuid` is null"
```

Expected result:
```
>>> $query->limit(1000)->getGrammar()->compileDelete($query->toBase())
=> "delete `commands`, `statuses` from `commands` inner join `statuses` on `commands`.`id` = `statuses`.`model_id` where `commands`.`created_at` < ? and `commands`.`action` in (?, ?, ?, ?, ?) and `statuses`.`model_type` = ? and `parent_uuid` is null"
```

### Steps To Reproduce

I was using this Spatie package that parses queries this way: https://github.com/spatie/laravel-queued-db-cleanup

```php
CleanDatabaseJobFactory::new()
            ->query(DeviceCommand::join('statuses', 'commands.id', '=', 'statuses.model_id')
            ->where('commands.created_at', '<', Carbon::now()->subDays(5)->toDateTimeString())
                ->whereIn('commands.action', [CommandEnum::deviceAppList(), CommandEnum::deviceInfo(), CommandEnum::deviceAppStats(), CommandEnum::deviceAppStatus(), CommandEnum::deviceSensorData()])
                ->where('statuses.model_type', '=', DeviceCommand::class)
            )
            ->deleteChunkSize(1000)
            ->getBatch()
            ->onQueue('maintenance')
            ->dispatch();
```

**Comment by sebapastore** [comment]
As I see, this is an error, it's just how the method is implemented.

The description at `compileDeleteWithJoins()` method in `Illuminate\Database\Query\Grammars\Grammar` just says "Compile a delete statement with joins into SQL". So it's not very specific. At this point it is not clear if it will delete the records of all tables involved or if it will just delete records from the main table. But when you look at the method's code, it is clear that the intention is to delete only the records from the main table. At least that is the way I see it.

**Comment by tpetry** [comment]
I am against changing the current behaviour. The new wished one would only work for MySQL and not any other database as multiple-deletes are not part of the standard. Depending on the DB used, the Laravel code would now behave differently 😬

**Comment by driesvints** [comment]
Thanks all. This is indeed not something we're going to change soon as it involves a major breaking change. If anything is unclear we'd appreciate a PR to the docs 👍
