### ISSUE TITLE
Storage & FTP doesn't work to upload files into subdirectories

### ISSUE THREAD

**Issue by Bran72** [laravel/framework#48712]
### Laravel Version

9.52.15

### PHP Version

8.1.10

### Description

Hello,

After migrating my application from Laravel 8 to Laravel 9, my FTP upload is no longer functioning :/
It only works when I place a file in the root folder. Before, when using Laravel 8, I never encountered this problem.

For example, if I want to upload my file to /documents/document/<mynewfile>, it doesn't work.

Here's my code:

```php
$filepath = Storage::path($document->getRawOriginal('path'));
$hash = hash_hmac('md5', config('app.hash_ftp'), $id.$type);
$file = new File($filepath);

$path = 'documents/document/'.$hash;
$path_php = 'documents/document/'.$hash.'/test.jpg';

Storage::disk('ftp')->putFile($path, $file); // not functioning !
Storage::disk('ftp')->put($path, $file); // not functioning !
Storage::disk('ftp')->put($path, Storage::path($document->name)); // not functioning !

$conn_id = ftp_connect('ftp.oenodata.fr');
$login_result = ftp_login($conn_id, config('filesystems.disks.ftp.username'), config('filesystems.disks.ftp.password'));
ftp_pasv($conn_id, true);
$put = ftp_put($conn_id, $path_php, $filepath, FTP_ASCII); // Functioning !
ftp_close($conn_id);
```
As you can see, I attempted to use the native PHP function ftp_put, and it works without any issues!

### Steps To Reproduce

You can try the code below, with a working ftp connection:
```php
$filepath = Storage::path($document->getRawOriginal('path'));
$hash = hash_hmac('md5', config('app.hash_ftp'), $id.$type);
$file = new File($filepath);

Storage::disk('ftp')->putFile($path, $file); // not functioning !
Storage::disk('ftp')->put($path, $file); // not functioning !
Storage::disk('ftp')->put($path, Storage::path($document->name)); // not functioning !

$conn_id = ftp_connect('ftp.oenodata.fr');
$login_result = ftp_login($conn_id, config('filesystems.disks.ftp.username'), config('filesystems.disks.ftp.password'));
ftp_pasv($conn_id, true);
$put = ftp_put($conn_id, $path_php, $filepath, FTP_ASCII); // Functioning !
ftp_close($conn_id);
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
