### ISSUE TITLE
Model::preventLazyLoading doesn't do anything 

### ISSUE THREAD

**Issue by sektormediaofficial** [laravel/framework#48722]
### Laravel Version

10.28.0

### PHP Version

sail latest

### Database Driver & Version

sail latest

### Description

public function boot(): void
{
        Model::preventLazyLoading(true);
 }
 
 Turning this setting on doesn't do anything. The model is still "lazy loaded". Please fix it
 

### Steps To Reproduce

Add `Model::preventLazyLoading(true)` 

Try to lazy load anything and it won't throw the exception:
```
> Model::preventLazyLoading(true)
> Message::find(34)->sender
[!] Aliasing 'Message' to 'App\Models\Message' for this Tinker session.
= App\Models\User {#7749
    id: 25,
    ...
```

**Comment by sektormediaofficial** [comment]
Adding a line in `Concerns/HasAttributes.php:534` shows that this setting isn't respected:
```php
= App\Models\Message {#7744
    id: 34,
    ...
  }

> Message::find(34)->sender
false // vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:534
```php 
// inside Concerns/HasAttributes.php:534
dd($this->preventsLazyLoading);
        if ($this->preventsLazyLoading) {
            $this->handleLazyLoadingViolation($key);
        }
```

```

**Comment by sektormediaofficial** [comment]
Solved it in a temporary way by doing this:
```php
<?php
namespace App\Models\Base;

class Model extends \Illuminate\Database\Eloquent\Model
{
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->preventsLazyLoading = true;
    }
}

class MyModel extends Model {}
```

Then it works...
```php
> Message::find(34)->sender
   Illuminate\Database\LazyLoadingViolationException  Attempted to lazy load [sender] on model [App\Models\Message] but lazy loading is disabled.
```

I think the framework should handle this case though, as this setting is mentioned in the documentation.

**Comment by Rizky92** [comment]
I believe this behaviour is intended (or relaxed). If you have a singular relation that is lazy loaded, it won't throw `LazyLoadingViolationException` because no N+1 relation query is created.

It will only throw if the relation is more than one.

**Comment by driesvints** [comment]
See the above. Thanks @Rizky92
