### ISSUE TITLE
MailMessage Blockquote Markdown Doesn't Work

### ISSUE THREAD

**Issue by rileysiemens** [laravel/framework#48724]
### Laravel Version

10.17.1

### PHP Version

8.1.23

### Database Driver & Version

10.11.4

### Description

In a Notification, you can assemble a markdown email notification in the `toMail()` function.  All standard Markdown shortcuts work except for using `>` for blockquotes.  For example, this is the return statement in my test notification `toMail` function:
```php
return (new MailMessage)
    ->line('# Heading 1')
    ->line('## Heading 2')
    ->line('### Heading 3')
    ->line('**Bold Text**')
    ->line('*Italicized Text*')
    ->line('_More Italicized Text_')
    ->line('1. Ordered List')
    ->line('2. Second Item')
    ->line('- Unordered List')
    ->line('- Second Item')
    ->line('`this is a code line`')
    ->line('```')
    ->line('this is a code block')
    ->line('```')
    ->line('[A markdown link](https://laravel.com)')
    ->line('![Laravel Logo](https://laravel.com/img/logomark.min.svg)')
    ->line('---')   // horizontal rule
    ->line('> this blockquote does not work')
    ->line(\Illuminate\Mail\Markdown::parse('> This blockquote does work'));
```
And this is output:<br>
![image](https://github.com/laravel/framework/assets/23223158/33403661-e348-4397-a648-0a4675b6031e)

You'll notice a workaround I've found is to explicitly convert the blockquote to an HtmlString via `Markdown::parse()`.  But I think this is inconsistent behaviour.  Adding a `>` should be parsed as a blockquote to be consistent with other MD shortcuts.

### Steps To Reproduce

1. Create a new notification `php artisan make:notification TestNotification`
2. In `app/Notifications/TestNotification.php`, modify `public function toMail()`
   ```php
    public function toMail(object $notifiable = null): MailMessage
    {
        return (new MailMessage)
            ->line('# Heading 1')
            ->line('## Heading 2')
            ->line('### Heading 3')
            ->line('**Bold Text**')
            ->line('*Italicized Text*')
            ->line('_More Italicized Text_')
            ->line('1. Ordered List')
            ->line('2. Second Item')
            ->line('- Unordered List')
            ->line('- Second Item')
            ->line('`this is a code line`')
            ->line('```')
            ->line('this is a code block')
            ->line('```')
            ->line('[A markdown link](https://laravel.com)')
            ->line('![Laravel Logo](https://laravel.com/img/logomark.min.svg)')
            ->line('---')   // horizontal rule
            ->line('> this blockquote does not work')
            ->line(\Illuminate\Mail\Markdown::parse('> This blockquote does work'));
    }
   ```
3. Add a route to `routes/web.php`
    ```php
    Route::get('/notificationTest', fn() => (new TestNotification())->toMail());
   ```
4. Go to `http://localhost/notificationTest`
5. Notice the blockquote that doesn't work

**Comment by crynobone** [comment]
Lines are echo'ed using `{{ $line }}` and not `{!! $line !!}` which cause `> this blockquote does not work` to become `&gt; this blockquote does not work`

You can solve this by using 

```diff
- ->line('> this blockquote does not work')
+ ->line(new Illuminate\Support\HtmlString('> this blockquote does not work'))
```

**Comment by xtfer** [comment]
How is this not a bug?

**Comment by rileysiemens** [comment]
> How is this not a bug?

Yeah I'm not sure either. It's definitely unintuitive.  The fact that there's a workaround doesn't not mean this shouldn't be fixed.
