### ISSUE TITLE
delete() method not working on version 10 with MySQL database

### ISSUE THREAD

**Issue by Shaykhnazar** [laravel/framework#48738]
### Laravel Version

10.28

### PHP Version

8.1.9

### Database Driver & Version

8.0.30 - MySQL Community Server - GPL for Windows

### Description

`delete` is not working after installing the new Laravel version (`10.28`)!
before in the old version(9.x) no problem with this.
Do you know how I can fix it?
![image](https://github.com/laravel/framework/assets/49790448/40f590b6-7ac6-43f3-908a-ab9abd216e81)

### Steps To Reproduce

but the update() function is correctly working, also I have debugged the delete() method and it returned true but in the Database record not deleting

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
