### ISSUE TITLE
Add quickstart documentation

### ISSUE THREAD

**Issue by fulldecent** [laravel/framework#48743]
### Laravel Version

10

### PHP Version

8

### Description

The documentation at https://laravel.com/docs/10.x is missing a quick start section.

That was one of the appeals Lumen (since deprecated)... there is just less to read.

The quick start documentation should allow you to do all the following while drinking one cup of coffee, on a single page.

1. Install locally on your workstation (probably Mac)
2. Create a hello world app using a database (SQLite) and some functionality
3. Run the application
4. Allow the customer to imagine how this example aligns with their current business needs
5. Link to deeper reading only as needed, but not as to distract from the main flow

And this quickstart should be the first page of the documentation.

---

As current, the documentation is written for an audience of people that are full-time paid programmers and have significant time to invest in reading it. This improvement will expand the applicability of the documentation from hardcore people to all people.

### Steps To Reproduce

..

**Comment by driesvints** [comment]
please don't open issues for docs but send in a PR instead, thanks.

**Comment by driesvints** [comment]
Also see this: https://laravel.com/docs/10.x#meet-laravel

<img width="745" alt="Screenshot 2023-10-16 at 15 50 12" src="https://github.com/laravel/framework/assets/594614/d74ee08c-5fa7-4485-9484-2279769d1132">
