### ISSUE TITLE
attach method does not support array value in the attribute parameter

### ISSUE THREAD

**Issue by OmarNasab** [laravel/framework#48753]
### Laravel Version

10,26,2

### PHP Version

8.1

### Database Driver & Version

8.0

### Description

I am having an issue i have a many to many relationship between two models and in the pivot table I have a JSON field but when i try to fill this field using attach it shows me `array to string conversion error`

### Steps To Reproduce

1- model one is called BalanceScoreCard
2- model two is User
3- pivot table called BalanceScoreCardApproval
4- relationship inside the model 1 
`public function users(){
        return $this->belongsToMany(User::class,"balance_score_card_approvals")->withPivot("status","notes");
    }`
5- relationship inside model 2
`public function balanceScoreCard(){
        return $this->belongsToMany(BalanceScoreCard::class,"balance_score_card_approvals")->withPivot("status","notes");
    }`
6- pivot table migration
`public function up(): void
    {
        Schema::create('balance_score_card_approvals', function (Blueprint $table) {
            $table->id();
            $table->foreignId("user_id")->constrained();
            $table->foreignId("balance_score_card_id")->constrained();
            $table->string("status");
            $table->json("notes")->nullable();
            $table->timestamps();
        });
    }`
9- pivot table model
`protected $fillable=[
        "user_id",
        "balance_score_card_id",
        "status",
        "notes"
    ];

    protected $casts=[
        "notes" => "array",
        "status" => StatusEnum::class
    ];`
10- filling the pivot table 
`$this->balanceScoreCard->users()->attach(auth()->id(),["status"=>"approved","notes"=>[$this->remarks]]);`
remarks here is a string

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
