### ISSUE TITLE
Builder getCountForPagination ignores distinct

### ISSUE THREAD

**Issue by mblajek** [laravel/framework#48750]
### Laravel Version

10.28.0

### PHP Version

8.2.11

### Database Driver & Version

MariaDB 10.5.0

### Description

Method getCountForPagination of Illuminate\Database\Query\Builder ignores if query has `distinct` parameter

As a result, there is count of all rows, including duplicated values

As I see, solution for this problem is to change first line of runPaginationCountQuery from
```php
if ($this->groups || $this->havings) {
```
to
```php
if ($this->distinct || $this->groups || $this->havings) {
```
As workaround I have to use someting like this:
```php
DB::table($builder->cloneWithout(['orders', 'limit', 'offset'])->cloneWithoutBindings(['order']))->count();
```

### Steps To Reproduce

```sql
-- create and fill table:
create table test_distinct (v int)
insert into test_distinct values (1),(1),(2);
```
```php
// all rows
DB::table('test_distinct')->get()->pluck('v')->all()
= [1, 1, 2]

// distinct rows
> DB::table('test_distinct')->distinct()->get()->pluck('v')->all()
= [1, 2]

// count of distinct rows
> DB::table('test_distinct')->distinct()->getCountForPagination()
= 3 // should be 2
```

**Comment by driesvints** [comment]
Please see https://github.com/laravel/framework/issues/26935 and many issues before it

**Comment by mblajek** [comment]
Maybe documentation should contain notice, that laravel is bad choice, because it has bugs which will not be fixed
