### ISSUE TITLE
Resource routes and route caching are not playing nice together

### ISSUE THREAD

**Issue by Ham3D** [laravel/framework#48766]
### Laravel Version

10.4

### PHP Version

8.1

### Database Driver & Version

Mysql 8.0

### Description

we have two resource routes:
- Route::resource('case1/interface', 'Case1Controller');
- Route::resource('case2/interface', 'Case2Controller');

its working fine.

but, if you try to do a route:cache, the hammer will fall.

the problem is, those resource routes create the same name as follows:

**first** route:

> interface.index
> interface.show 
> ...

**second** route:

> interface.index
> interface.show 
> ...

as a result you cant cache routes because they have same names.

one solution would be to name those routes one by one.

is there a way to disable auto naming of resource routes?

### Steps To Reproduce

as described in description, this problem is probably well known.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
