### ISSUE TITLE
Resource Attribute Access Issue in Paginated ResourceCollections

### ISSUE THREAD

**Issue by pejeio** [laravel/framework#48762]
### Laravel Version

10.4.1

### PHP Version

8.2.10

### Description

In [this line](https://github.com/illuminate/http/blob/master/Resources/Json/PaginatedResourceResponse.php#L31%5B2%5D.), it appears that the `resource` attribute is being accessed directly from the model. This becomes problematic when the [preventAccessingMissingAttributes](https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L2197-L2200) method is invoked in the AppServiceProvider. This method is designed to restrict access to missing attributes on retrieved models.

I get this error when trying to use a paginated resource collection:
```
{
    "message": "The attribute [resource] either does not exist or was not retrieved for model [App\\Models\\Vehicle]."
    ...
}
```

### Steps To Reproduce

**AppServiceProvider.php**
```php
<?php

namespace App\Providers;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {

    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Model::preventAccessingMissingAttributes();
    }
}
```

DefaultCollection.php
```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;

class DefaultCollection extends ResourceCollection
{
     /**
     * The resource collection class to be used.
     *
     * @var string
     */
    protected $resourceClass;

    /**
     * Set the resource collection class.
     *
     * @param  string  $resourceClass
     * @return $this
     */
    public function setResourceClass(string $resourceClass)
    {
        $this->resourceClass = $resourceClass;

        return $this;
    }

    /**
     * Customize the pagination information for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  array $paginated
     * @param  array $default
     * @return array
     */
    public function paginationInformation($request, $paginated, $default)
    {
        $default['count'] = $default['meta']['total'];
        unset($default['meta']);

        return $default;
    }

    /**
     * Transform the resource collection into an array.
     *
     * @return array<int|string, mixed>
     */
    public function toArray(Request $request): array
    {
        $resourceClass = $this->resourceClass;

        return [
            'data' => $resourceClass::collection($this->collection),
        ];
    }
}
```

**VehicleController.php**
```php
/**
     * Display a listing of the resource.
     */
    public function index()
    {
        $vehicles = Vehicle::with(['manufacturer', 'colors'])
            ->latest()
            ->paginate(50);
        $collection = new DefaultCollection($vehicles);
        $collection->setResourceClass(VehicleResourceCompact::class);
        return $collection;
    }
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
