### ISSUE TITLE
Exception Handler can't work

### ISSUE THREAD

**Issue by KenHuangisGood** [laravel/framework#48774]
### Laravel Version

9.52.15

### PHP Version

8.2.5

### Database Driver & Version

5.7.39 - MySQL Community Server (GPL)

### Description

I created a RelatedDataException.php under the app\Exceptions directory. Here is my code:

```
<?php

namespace App\Exceptions;

use Exception;

class RelatedDataException extends Exception
{
    public function __construct($related_model = "", $code = 401, Exception $previous = null)
    {
        parent::__construct("can't delete, include model：" . $related_model, $code, $previous);
    }
}
```

Then I added it to the $dontReport property in the Handler.php file because I don't want it to be logged in my logs:

```
protected $dontReport = [
    RelatedDataException::class
];
```
However, I found that when I trigger the custom exception, it doesn't follow the dontReport configuration I set, and I have to add it to the dontReport property in Illuminate\Foundation\Exceptions\Handler for it to work as expected.

### Steps To Reproduce

1. Create a custom exception file, and write something.
2. Add into $dontReport(app/exceptions/Handler.php)
3. Trigger this exception.

**Comment by timacdonald** [comment]
Are you importing the class?

Can you try swapping the inline class with the FQCN `\App\Exceptions\RelatedDataException::class`

**Comment by KenHuangisGood** [comment]
> Are you importing the class?
> 
> Can you try swapping the inline class with the FQCN `\App\Exceptions\RelatedDataException::class`

Yes, you mentioned it like this:

```
/**
 * A list of the exception types that are not reported.
 *
 * @var array<int, class-string<\Throwable>>
 */
protected $dontReport = [
    \App\Exceptions\RelatedDataException::class
];

```

If that's the case and it's still not working as expected, then there might be some other issue causing the dontReport configuration not to work as intended. You should make sure that the RelatedDataException class is correctly imported, and there are no typos in the class name or namespace. Also, check if the Handler.php file is being correctly loaded by your application. Double-checking the code and namespace declarations is essential for it to work as intended.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by lk77** [comment]
You most likelely overrided the report function, in which case you need to call shouldntReport yourself
