### ISSUE TITLE
DB::transactionLevel() shows incorrect level, if DDL operation was done

### ISSUE THREAD

**Issue by mrckzgl** [laravel/framework#48776]
### Laravel Version

9.20.0

### PHP Version

8.2.1

### Database Driver & Version

10.10.2-MariaDB-1:10.10.2+maria~ubu2204

### Description

We encounter that DB::transactionLevel() shows an incorrect level after a DDL operation was done, which does commit implicitly. Consider this code snippet which is the current behaviour:
```
Log::debug(DB::transactionLevel()); // 0
DB::beginTransaction();
Log::debug(DB::transactionLevel()); // 1
DB::commit();
Log::debug(DB::transactionLevel()); // 0

DB::beginTransaction();
Log::debug(DB::transactionLevel()); // 1
// some DDL operation which closes the transaction
Log::debug(DB::transactionLevel()); // 1
```
This is problematic on different levels. First, getting the correct transaction level is important to be able to close all pending transactions. Second, due to a current change (see: https://github.com/laravel/framework/issues/35380), DB::commit() and DB::rollback() both throw an exception if no active transaction is present. That means after beginTransaction and a DDL statement, this code:
```
if (DB::transactionLevel() > 0) {
  DB::commit();
}
```
will fail.

### Steps To Reproduce
```
DB::beginTransaction();
// do some DDL statement
if (DB::transactionLevel() > 0) {
  DB::commit();
}
```

If necessary I could construct a minimal working example (but woudn't mind if it is not needed).

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by mrckzgl** [comment]
@driesvints I just confirmed this is happening in Laravel 10 too, see: https://github.com/laravel/framework/issues/48777
