### ISSUE TITLE
Sql query incorrect with getModel()->{relationship_name}

### ISSUE THREAD

**Issue by nonoodev** [laravel/framework#48780]
### Laravel Version

10.28.0

### PHP Version

8.2.7

### Description

When using a relationship after a getModel() on a Builder with a HasOne(), the generated SQL contains the following code :
```where `my_table`.`user_id` is null and `my_table`.`user_id` is not null```

After some tests, I could figure out that in the Illuminate\Database\Eloquent\Relations\HasOne query there is :
```
      +wheres: array:3 [▼
        0 => array:3 [▼
          "type" => "Null"
          "column" => "my_table.user_id"
          "boolean" => "and"
        ]
        1 => array:3 [▼
          "type" => "NotNull"
          "column" => "my_table.user_id"
          "boolean" => "and"
        ]
        2 => array:3 [▼
          "type" => "raw"
          "sql" => "´id´ =  ´users.id´"
          "boolean" => "and"
        ]
      ]
```
We can't then generate well formed queries from a getModel() method calling a relationship.
and all of the subqueries are affected as well.

### Steps To Reproduce

have 2 Models like that :
```
class User extends Authenticatable
{
    ...
    public function active_contract()
    {
        return $this->hasOne(UserContract::class, 'user_id', 'id')->ofMany(['arrival_date' => 'max']);
    }
```

```
class UserContract extends Model
{
    protected $fillable = [
        ...
        'arrival_date',
        'user_id',
    ];
   public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
```

and just call 
```
$contract = User::active()->getModel()->active_contract();
dd($contract, $contract->toSql());
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by nonoodev** [comment]
Hello, I already tried the discord some days ago.
I created a post in the forum called "Eloquent strange behavior with generated query" and continued since then to try to fix/understand what was the problem.
here is the thread ID : 1163804312724582600

Should I try another way too?

**Comment by driesvints** [comment]
Hi there. This does seem like a support question sorry. Please try laracasts or laravel.io as well.

**Comment by nonoodev** [comment]
Ok thank you, I'll try it too :)
