### ISSUE TITLE
DI recursion

### ISSUE THREAD

**Issue by psprokofiev** [laravel/framework#48787]
### Laravel Version

10.26.2

### PHP Version

8.2.11

### Description

It so happened that I created two classes that have mutual dependencies.
I can’t detect this in any way, so is there any way to catch such an error? 
The Docker container stops with status 255, 
and there are no logs - neither in the container nor in the framework's storage.

### Steps To Reproduce

Just create two classes like that
```
<?php
namespace App\Services;
class ClassOne
{
    public function __construct(
        protected ClassTwo $class,
    ) {
        //
    }
}
```
and another one
```
<?php
namespace App\Services;
class ClassTwo
{
    public function __construct(
        protected ClassOne $class,
    ) {
        //
    }
}
```

Then make command and bind the classes
```
<?php
namespace App\Console\Commands;

use App\Services\ClassOne;
use App\Services\ClassTwo;
use Illuminate\Console\Command;

class AnyCommand extends Command
{
    protected $signature = 'any:command';

    public function handle(ClassOne $one, ClassTwo $two)
    {
        //
    }
}
```
And run command:
`docker compose exec app php artisan any:command`
There nothing in console, just exit
Command `echo $?` returns 255

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
