### ISSUE TITLE
Add support for root models to Laravel Breeze

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [laravel/framework#48783]
### Laravel Version

10.28.0

### PHP Version

8.2.11

### Database Driver & Version

MySQL 8.0.32

### Description

Sorry, this is arguably a feature request, but let's see...

After the change in Laravel 8 to place models in `App/Models` by default, some of us have held onto the support for [storing models in the `App` folder](https://stackoverflow.com/questions/77046231/how-i-move-my-laravel-models-back-to-the-app-folder-root). 

Thankfully the framework supports this (so `php artisan make:model` knows where to put new models), but the default **Laravel Breeze** installation still doesn't...

Obviously the user can easily search and replace `App\Models\User` for `App\User`, but it would be great if they didn't have to.

There is one controller (`RegisteredUserController.php`) and one request (`ProfileUpdateRequest.php`), as well as several tests that Breeze adds, that reference the default location.

### Steps To Reproduce

1. Install a new Laravel project
2. Move User.php out of the `app/Models` folder to the `app/` folder
3. Delete the `app/Models` folder
4. Run `php artisan make:model Test` and ensure it is created in the right place
5. [Install Laravel Breeze](https://laravel.com/docs/10.x/starter-kits#laravel-breeze-installation) (`composer require laravel/breeze --dev` and `php artisan breeze:install`)
6. Try and register on the default app

You will get an error because `RegisteredUserController.php` is still referring to `app/Models` instead of `app/`.

I guess the solution would be for Breeze to detect the absence of the models folder?

**Comment by driesvints** [comment]
I’m sorry but we have no plans for this. Breeze is a scaffold tool and by default references the location of the place where the model is by default in the skeleton.

**Comment by JohnnyWalkerDigital** [comment]
Ok, but please don't remove this support from Artisan. Many of us still prefer the Laravel 7 folder structure! Thanks
