### ISSUE TITLE
Error in Spatie\Ray

### ISSUE THREAD

**Issue by mj4444ru** [laravel/framework#48804]
### Laravel Version

10.15.0

### PHP Version

8.1.23

### Description

I get the following error, which in itself doesn't tell me anything, which is very bad.
```
   InvalidArgumentException 

  Database connection [mysql] not configured.

  at vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:173
    169▕         // If the configuration doesn't exist, we'll throw an exception and bail.
    170▕         $connections = $this->app['config']['database.connections'];
    171▕ 
    172▕         if (is_null($config = Arr::get($connections, $name))) {
  ➜ 173▕             throw new InvalidArgumentException("Database connection [{$name}] not configured.");
    174▕         }
    175▕ 
    176▕         return (new ConfigurationUrlParser)
    177▕                     ->parseConfiguration($config);

      +16 vendor frames 

  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

As debugging showed, the error occurs due to this line of code:
https://github.com/spatie/laravel-ray/blob/0c0b2962665d14ca958feb7f213ac864a0fdda0c/src/Ray.php#L481

The reason for the error is that I don't have a connection to the database.

I don't connect laravel-ray and I don't want laravel-ray to handle errors in my laravel application. Moreover, I don’t want it to create additional errors that are difficult to identify due to the fact that laravel hides the real call stack.

I'm creating an Issue here because I don't connect laravel-ray and don't want to work with it.

### Steps To Reproduce

When executing the code `ConfigOption::query()->where('name', $name)->first();` I get an error which I can't get due to the above mentioned error. This happens because I do not have a connection to the default database, I only use different connections to external databases, none of which is the main one. This throws an error when handling my error in Spatie\LaravelRay.

**Comment by crynobone** [comment]
Please report the issue to Laravel Ray project.

**Comment by mj4444ru** [comment]
> Please report the issue to Laravel Ray project.

I did not install Laravel Ray to write to the Laravel Ray project. Thank you.

**Comment by crynobone** [comment]
> I did not install Laravel Ray to write to the Laravel Ray project. Thank you.

And Laravel Framework doesn't requires Laravel Ray.

You should check `composer why spatie/laravel-ray`

**Comment by mj4444ru** [comment]
> And Laravel Framework doesn't requires Laravel Ray.

I'm glad that Laravel Ray is no longer installed automatically with laravel.
