### ISSUE TITLE
SkipIfBatchCancelled with retries marks previously failed jobs as successful

### ISSUE THREAD

**Issue by bernardwiesner** [laravel/framework#48810]
### Laravel Version

10.4

### PHP Version

8.1

### Description

When using the SkipIfBatchCancelled middleware together with failed jobs retries, the jobs that previously failed are marked as successful when one job reaches the failed retry threshold.

### Steps To Reproduce

Actual:
1. Batch 10 jobs
2. Job 3 and 7 fail
3. Failed jobs are retried up to retry threshold
4. Job 3 meets threshold first, marks batch as cancelled
5. Job 7 is skipped, and marked as successful due to SkipIfBatchCancelled middleware

Expected
5. Job 7 had previously failed, so it should not be marked as successful, it should be marked as failed instead.

**Comment by crynobone** [comment]
https://github.com/laravel/framework/pull/45869

Based on the initial PR the current behavior seems expected, as it skipped handling the job without failing it. I believe you can create a new custom middleware to handle your requirements and fail the job.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
