### ISSUE TITLE
Queued Mailable Redis: SerializesAndRestoresModelIdentifiers: ModelNotFoundException

### ISSUE THREAD

**Issue by stuartcusackie** [laravel/framework#48816]
### Laravel Version

10.15.0

### PHP Version

8.2.5

### Database Driver & Version

MySQL 8

### Description

I know this is has been brought up a million times before but there seems to still be a bug in queued mailables. I've been on Laracasts and various other resources and I don't see that I'm doing anything wrong.
```
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\Item]
#0 /home/forge/testapp.com/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(108):
```

I use Laravel Forge with a Redis queue managed by Horizon. There is no other special configuration. It's a simple server with the default MySQL installed.

What I'm doing is very simple. The item has been created and persisted, as shown below, but when the queued mailable job runs it cannot find the item.

```
public function handleItemCreation(Request $request)
{ 
  $item = Item::create([
    'name' => request('name'),
    'email' => request('email'),
  ]);

  Mail::to(request('email'))->send(new TestMailable($item));
  ...
```

```
class TestMailable extends Mailable implements ShouldQueue
{
  use Queueable, SerializesModels;

  public $item;

  public function __construct($item)
  {
    $this->item = $item;
    $this->onQueue('notifications');
  }
```

Retrying the job manually does work.
This also happens in scheduled tasks that send queued mailables 15 minutes after the model has been persisted

Thanks.

### Steps To Reproduce

1. Set up a model (Item) and a queued mailable (TestMailable).
2. Send the mailable and pass the recently created Item
3. Deploy to server (forge)
4. Create requests and watch Horizon Failed Jobs.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by sonja-turo** [comment]
What's the name of the primary key of the model? "id" is the default, and is what the queueing system looks for when trying to load the model. If you're using a different primary key name , this would cause your problem.

**Comment by stuartcusackie** [comment]
> What's the name of the primary key of the model? "id" is the default, and is what the queueing system looks for when trying to load the model. If you're using a different primary key name , this would cause your problem.

I defined my table like so:

```
Schema::create('items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('place_id');
            $table->foreignId('team_id');
            $table->foreignId('person_id');
            ... other string / boolean / json columns ...
            $table->timestamps();
});
```

**Comment by stuartcusackie** [comment]
> Can you please create a repository with the command below, commit the code that reproduces the issue _as one separate commit_ on the main/master branch and share the repository here?

I hope this is correct:
https://github.com/stuartcusackie/laravel-bug-report-48816

I'm sorry but I'm having trouble getting Horizon Redis queues to run on my Windows machine, so I couldn't verify if the same errors are occurring.

**Comment by driesvints** [comment]
> I'm sorry but I'm having trouble getting Horizon Redis queues to run on my Windows machine

Horizon doesn't supports Windows unfortunately.

**Comment by stuartcusackie** [comment]
I have deployed my bug report repo to a Forge server and I cannot reproduce the error. I'm not sure what's difference there is in my real application. The model has relations, but that's the only difference I can see.

I will kill horizon and restart it and see if that helps.

**Comment by stuartcusackie** [comment]
**SOLUTION?** I assume these errors are actually being produced by my staging server. The job is being placed on the same queue as the production server and when staging tries to find the object, it does not exist in the database.
