### ISSUE TITLE
Ignored .env.testing

### ISSUE THREAD

**Issue by andreacivita** [laravel/framework#48811]
### Laravel Version

10.29.0

### PHP Version

8.2

### Description

Hi,

i have configured two different databases, with two separated .env files

```
// .env
DB_CONNECTION=pgsql
DB_HOST=pgsql
DB_PORT=5432
DB_DATABASE=database
DB_USERNAME=sail
DB_PASSWORD=password
```

```
// .env.testing
APP_ENV=testing
...
DB_CONNECTION=sqlite
DB_DATABASE=database/testing.sqlite
DB_FOREIGN_KEYS=true
```

I have migrated both db (local and testing), but if I run `php artisan migrate:reset --env=testing`, laravel ignores my test db and revert migrations in my local pgsql database.

### Steps To Reproduce

Create `.env` and `.env.testing` file, set different database for each env. 
Run `php artisan migrate --env=testing`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by andreacivita** [comment]
I'm sorry, this is not a question but a bug report.
As per the Laravel documentation (https://laravel.com/docs/10.x/testing#the-env-testing-environment-file), it is stated that:
```
In addition, you may create a .env.testing file in the root of your project. This file will be used instead of the .env file when running PHPUnit tests or executing Artisan commands with the --env=testing option.
```

However, it seems that when I run the `artisan migrate --env=testing` command, Laravel is still using the `.env` file instead of `.env.testing`, which is unexpected behavior. So, you should re-open my issue

**Comment by zaherg** [comment]
@andreacivita make sure that you don't have your config cached, for example try to run `php artisan optimize:clear` first then run `artisan migrate --env=testing` and see which table will be created.
