### ISSUE TITLE
TypeError in Illuminate\Routing\RoutingServiceProvider::registerPsrRequest

### ISSUE THREAD

**Issue by kpicaza** [laravel/framework#48822]
### Laravel Version

10.29.0

### PHP Version

8.2

### Description

`Illuminate\Routing\RoutingServiceProvider::registerPsrRequest` is passing a potentially null value to the `array_merge` function on merging requests' parsed body with the Illuminate request payload. It causes a `TypeError` exception. I'm already working on a PR fixing it

### Steps To Reproduce

1. Using PSR-7 Bridge
2. Make a request without parameters, at least with the "content-type" header. For instance:
```php
$client->get('/', [
    'content-type' => 'application/json'
])
```
3. ServerRequestInterface $request::getParsedBody will be null
4. array_merge expect value of type array
`TypeError: array_merge(): Argument #1 must be of type array, null given`

**Comment by timacdonald** [comment]
Will close this and we can track it in the PR. Thanks!
