### ISSUE TITLE
Issue with default Laravel 10 Setup Using NPM: The package "@esbuild/darwin-x64" could not be found, and is needed by esbuild

### ISSUE THREAD

**Issue by danielh-official** [laravel/framework#48839]
### Laravel Version

10.10

### PHP Version

8.1

### Description

When I run `npm run dev`, I get this in the terminal:

```
failed to load config from /{project-root}/vite.config.js
error when starting dev server:
Error: The package "@esbuild/darwin-x64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
```

Installing es-build via `npm install es-build` yields this instead:

```
Cannot start service: Host version "0.18.20" does not match binary version "0.19.5"
```

Using yarn works, however.
1. `yarn install`
2. `yarn dev`

### Steps To Reproduce

1. Run `composer create-project laravel/laravel example-app` in the path of your choice. You can use a name other than "example-app".
2. Open in PhpStorm or VS Code.
3. Run `npm i` in terminal.
4. Run `npm run dev` in the terminal.
5. Install via `npm install es-build` and check if you get the second issue in the description.

I'm using an Intel Mac (OS: Sonoma 14.0), so the problem might not exist on Windows or Linux.

**Comment by Rizky92** [comment]
This issue doesn't seem related to laravel, but the javascript package manager you're using. See https://github.com/evanw/esbuild/issues/1646 for details

**Comment by crynobone** [comment]
Thank you @Rizky92
