### ISSUE TITLE
Eloquent - PDO Named Parameter

### ISSUE THREAD

**Issue by SnowRunescape** [laravel/framework#48848]
### Laravel Version

*

### PHP Version

7.4.33

### Database Driver & Version

MySQL 8.0.31

### Description

The problem:

When testing the following query with the same named parameter used multiple times, it works normally. Here's an example of the query:

```
SELECT * FROM shops WHERE user_id = :user_id
UNION shops_subusers FROM shops_subusers WHERE user_id = :user_id
```

However, if I instantiate Eloquent, obtain the PDO from Eloquent to execute raw SQL, I encounter the following problem:

"Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number"

This warning occurs because the named parameter :user_id is used twice. If I change one of them to :user_id2, it works.

Please note that using different names for the parameters, such as :user_id and :user_id2, resolves the issue.

### Steps To Reproduce

```
$statement = Capsule::connection()->getPdo()->prepare("SELECT
    id
FROM
    shops
WHERE
    user_id = :user_id
UNION ALL SELECT
    shop_id
FROM
    shops_subusers
WHERE
    user_id = :user_id
");
$statement->execute([
    ":user_id" => $userId
]);
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
