### ISSUE TITLE
Input value "_method" contains a non-scalar value.

### ISSUE THREAD

**Issue by tobz-nz** [laravel/framework#48871]
### Laravel Version

10.29.0

### PHP Version

8.2.2

### Description

One of my sites has been getting attacked today and one of the things they did is posted `_method` as an array to a form endpoint. Which throws an error(stack trace removed for security): https://flareapp.io/share/DPyKdV65

This is the relevant line:

```php
// vendor/symfony/http-foundation/Request.php
1213     if (!$method && self::$httpMethodParameterOverride) {
1214            $method = $this->request->get('_method', $this->query->get('_method', 'POST'));
1215     }
```

### Steps To Reproduce

In a new Laravel install (with Pest) make a test like:

```php
it('validates _method', function () {
    $this->post('/', ['_method' => ['invalid']])
        ->assertInvalid('_method');
});
```

**Comment by crynobone** [comment]
It seems that the issue also exist in Symfony HTTP Foundation, might worth it to report the issue there.

**Comment by mbabker** [comment]
This is not a Symfony bug, but the API design decision.

`Symfony\Component\HttpFoundation\InputBag` was introduced for exactly this type of scenario (an array being stuffed into an input where a single value is expected), with its `get()` method only being allowed to return scalar values.  Symfony is behaving as intended and explicitly forbidding an array value for the `_method` field in the input, throwing a `Symfony\Component\HttpFoundation\Exception\BadRequestException` (which should give the client a 400 response).

**Comment by driesvints** [comment]
Thanks @mbabker. Seems things work as expected here then. We'd appreciate a PR to avoid logging this specific exception!

**Comment by driesvints** [comment]
We'd still appreciate a PR for this one, thanks.
