### ISSUE TITLE
Additional function problem in JsonResource Collection

### ISSUE THREAD

**Issue by mstfblci** [laravel/framework#48878]
### Laravel Version

10.29.0

### PHP Version

8.1.23

### Description

When I create a JsonResource and run a collection in it, I cannot get the data I added with the additional() function with $this->additional in the resource.

### Steps To Reproduce

`(new TestResource([]))->collection($collection)->additional($additional)`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
