### ISSUE TITLE
Nested validation rules broken for non-wildcard keys

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/framework#48880]
### Laravel Version

10.19.0

### PHP Version

8.1.9

### Description

Hey.

When trying to use `NestedRules` with a key that's doesn't have a wildcard in it, it throws an error.

```php
use Illuminate\Validation\NestedRules;
use Illuminate\Validation\Validator;

$data = [
	'items' => [
		['discounts' => [['id' => 1], ['id' => 1], ['id' => 2]]],
		['discounts' => [['id' => 1], ['id' => 2]]],
	],
];

$rules = [
	'item' => new NestedRules(function () {
		return ['discounts.*.id' => 'distinct'];
	}),
];

// ErrorException: Undefined array key "item"
//   /app/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:131
//   /app/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:94
//   /app/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:73
//   /app/vendor/laravel/framework/src/Illuminate/Validation/ValidationRuleParser.php:51
$v = new Validator(app('translator'), $data, $rules);

$v->passes();

dd($v->errors()->all());
```

The same exact example but with a wildcard key works:

```php
$rules = [
         // Notice the added ".*" to the "items" key
	'items.*' => new NestedRules(function () {
		return ['discounts.*.id' => 'distinct'];
	}),
];
```

This use case is not documented, but rule name `NestedRules` implies it should work for any kind of nested rules and any keys, when in fact it doesn't. It makes sense to be support this use case, given most of the code is already there and the benefit is the same as with wildcard keys - to be able to share validation rules across multiple places.

It looks like the fix should be relatively trivial - `ValidationRuleParser::explodeExplicitRule` should iterate over rules and "explode" `NestedRules` rules the same way `ValidationRuleParser::explodeWildcardRules` does. I can work on a fix if it has a chance to get merged.

### Steps To Reproduce

1. Have a clean setup of Laravel at least 10.19.0
2. Copy the first example provided and run it

**Comment by oddvalue** [comment]
@oprypkhantc I think you just need to add a wildcard to the items rule:

```php
$rules = [
	'items.*' => new NestedRules(function () {
		return ['discounts.*.id' => 'distinct'];
	}),
];
```

**Comment by oprypkhantc** [comment]
@oddvalue Well yeah, that's the documentation example that works. But in my case I just want to share the rules for a non-array value.

**Comment by sonja-turo** [comment]
Not sure if I'm missing something here, but isn't the cause of your issue in your sample code due to you having the key `items` in your data, but a rule checking `item`?

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
