### ISSUE TITLE
Artisan sh: 2: cannot open code: No such file

### ISSUE THREAD

**Issue by halimkun** [laravel/framework#48895]
### Laravel Version

8.83.27

### PHP Version

7.4.33

### Database Driver & Version

MariaDB 10.6.12

### Description

Every time I run any artisan command an error like this always appears
```
sh: 2: cannot open code: No such file
```

I forget when this started, it's just that this error really bothers me when interacting with artisans. However, the error did not affect the work of the application I created. and the command I ran also ran without any problems. It's just that before the command runs, the error appears first.

I did the following things before in the application I made.
- install several helper libraries such as
   - `"awobaz/compoships": "^2.2"`
   - `"itsgoingd/clockwork": "^5.1"`
   - `"kreait/firebase-php": "^6.0"`
   - `"tymon/jwt-auth": "^1"`
   - `"yajra/laravel-datatables": "^1.5"`
- created a helper and added it in composer.json
   ```json
   "autoload": {
        "files": [
            "app/api_response.php"
        ],
        "psr-4": {
            .... 
        }
    },
   ```
-

### Steps To Reproduce

I tried looking for it on the 
- **internet (by Google, chatGPT or looking for it on StackOverflow)**, 
- **asked the local community**, and 
- **tried searching for it myself** 

but the results were still not found. I hope to get the answer here.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
