### ISSUE TITLE
Missing Illuminate\Contracts\Auth\MustVerifyEmail interface from Illuminate\Foundation\Auth\User class

### ISSUE THREAD

**Issue by danielbozsoki** [laravel/framework#48912]
### Laravel Version

>= 9.52.16

### PHP Version

8.1.21

### Database Driver & Version

MySQL 8.0.33

### Description

After trying to implement **Illuminate\Auth\Listeners\SendEmailVerificationNotification listener** I noticed that 

```
if ($event->user instanceof MustVerifyEmail && ! $event->user->hasVerifiedEmail()) {
    $event->user->sendEmailVerificationNotification();
};
```
condition always return false as a result.

After examining the User model, I noticed that it extends the **Illuminate\Foundation\Auth\User model**, where the **Illuminate\Contracts\Auth\MustVerifyEmail interface** which is implemented by **Illuminate\Auth\MustVerifyEmail trait**, seems to be missing.

### Steps To Reproduce

Actual version that I'm using (9.52.16) but as I see this gap is in latest version also.

After adding the MustVerifyEmail interface the problem was solved:

Actual version:

```
<?php

namespace Illuminate\Foundation\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\MustVerifyEmail;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail;
}
```

Modified version:

```
<?php

namespace Illuminate\Foundation\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\MustVerifyEmail as MustVerifyEmailTrait;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract,
    MustVerifyEmail
{
    use Authenticatable, Authorizable, CanResetPassword, MustVerifyEmailTrait;
}
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by danielbozsoki** [comment]
Hi @crynobone ,

I looked in the latest version as well and I see that the error is still there.

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Auth/User.php

New issue: https://github.com/laravel/framework/issues/48913

Can you check it please?

Thank you!
