### ISSUE TITLE
Model->update() has no effect if model does not include ID

### ISSUE THREAD

**Issue by hktang** [laravel/framework#48916]
### Laravel Version

10.26.0

### PHP Version

8.1

### Description

* I retrieve a collection (of users) and took only the "email" and "name" fields. I just need these for an API operation.
* Afterwards, I wanted to update a third field using `$model->update([$field => $value])`. 
* The code ran without error, but the field never updated. I took me a while to notice it was caused by the absence of the `id` field.

I am not sure if this has been addressed/discussed before, but at least some error message will be useful. 

### Steps To Reproduce

1. Grab a collection:

```php
$users = User::where($someCondition)->get(["name", "email"]);
```

2. Do mass update:

```php
$users->each(fn($user) => $user->update(["processed" => true]));  // No effect, no warning.
```

3. Hours looking at the `$fillable` array, database migration, checking column names 😅

**Comment by hafezdivandari** [comment]
* #29194

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by hktang** [comment]
Thanks for your reply. 

I do feel this can be improve because this special case is not documented, unlike more common gotchas such as $fillable/$guarded. Perhaps it could be added to the documentation of `$model->get()` parameters.

**Comment by lk77** [comment]
The query that is executed if the id is missing is :

```
PDOStatement {#8482
  +queryString: "update `users` set `name` = ?, `users`.`updated_at` = ? where `id` is null"
}
```

**Comment by hktang** [comment]
Thank you @lk77 for your investigation. That's very useful to know.

Suppose we are using a Model that does not use ID (but UUID, for example) as the default primary key. Then at least running update on those instances will result in an error, won't it? 

So, I do feel an error should be thrown when updating Models without supplying the ID field. Or some documentation, like for the $fillable/$guarded property.

**Comment by lk77** [comment]
@hktang no because it will use whatever field you define as a primaryKey on the model

i think laravel should always select the primaryKey field
