### ISSUE TITLE
var_export does not handle circular references

### ISSUE THREAD

**Issue by prathna124** [laravel/framework#48932]
### Laravel Version

8

### PHP Version

8.1

### Description

We are facing an issue when caching the config with
PHP artisan config: cache. It is a circular references-related issue and we have also faced issue-related closure that occurs when using the callback function in config files as you have suggested here https://github.com/exodusanto/Laravel-Admin/blob/master/docs/fields.md#editable-option.

https://i.imgur.com/Fxcb7Pt.png
Error: var_export does not handle circular references

### Steps To Reproduce

We have tried this but not working:-

We have tried to handle the error using Handler.php but it is not working
Also we have tried to remove the closure function from config/adminer.php but we have faced the below error:
There are problems with your administrator.php config: The permission option must be a function
Please guide me on how to solve this error when configuring the cache.

Is it possible to ignore this error when config cache or any way to handle this so error should not be reported?
Please guide me how to solve this ?

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
Also, see https://github.com/exodusanto/Laravel-Admin/issues/46
