### ISSUE TITLE
Using a Http Client Fake sequence with Pool triggers a TypeError exception

### ISSUE THREAD

**Issue by mattkingshott** [laravel/framework#48938]
### Laravel Version

10.30.1

### PHP Version

8.2.11

### Description

Owing to how concurrent HTTP requests using the HTTP client are executed (using promises), an exception can be encountered due to a sometimes incorrect type hint. Specifically line 1010 within the `makePromise` method of `Illuminate/Http/Client/PendingRequest`.

In some situations, the exception that is thrown is not a `TransferException`, but an `OutOfBoundsException`. It may be preferable to remove the type hint.

### Steps To Reproduce

When using the Http Client to send concurrent requests e.g.

```php
Http::pool(fn (Pool $pool) => [
    $pool->get('http://localhost/first'),
    $pool->get('http://localhost/second'),
    $pool->get('http://localhost/third'),
]);
```

And writing a test that fakes a corresponding Http response sequence e.g.

```php
use Illuminate\Support\Facades\Http;

Http::fakeSequence()
    ->push(null, 401)
    ->push(null, 403) 
    ->push(null, 405);
```

The following exception is thrown:

```bash
TypeError: Illuminate\Http\Client\PendingRequest::Illuminate\Http\Client\{closure}(): Argument #1 ($e) must be of type GuzzleHttp\Exception\TransferException, OutOfBoundsException given, called in /vendor/guzzlehttp/promises/src/RejectedPromise.php on line 49
```

The error relates to the `TransferException` type hint within `Illuminate/Http/Client/PendingRequest` on line 1010. If the type hint is removed the test runs as expected.

This error is not present when sending requests separately (not concurrently) as promises are not used.

**Comment by driesvints** [comment]
Thanks @mattkingshott. Maybe a union type is in order here?

**Comment by mattkingshott** [comment]
That's the simplest option, for sure. I'll PR
