### ISSUE TITLE
Method 'then' not found in \Illuminate\Foundation\Bus\PendingChain 

### ISSUE THREAD

**Issue by kolibabchuk** [laravel/framework#48948]
### Laravel Version

v10.31.0

### PHP Version

8.2.10

### Description

Method 'then' not found in \Illuminate\Foundation\Bus\PendingChain as it's described in documentation: https://laravel.com/docs/10.x/queues#chains-and-batches

### Steps To Reproduce

```PHP
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Log;

Bus::chain([
  new FooJob($bar),
])->then(
  fn() => Log::info("No luck.")
)->dispatch();
```

Will throw an Error: `"Call to undefined method Illuminate\Foundation\Bus\PendingChain::then()"`

**Comment by kolibabchuk** [comment]
it looks like PendingChain.php didn't get update at all:
https://github.com/laravel/framework/blob/v10.31.0/src/Illuminate/Foundation/Bus/PendingChain.php

**Comment by driesvints** [comment]
PendingChain is a new class. The `then` method here is incorrect I believe and should be removed from the docs. 

cc @khepin

**Comment by driesvints** [comment]
https://github.com/laravel/docs/pull/9126

**Comment by commando1251** [comment]
Same for me

**Comment by driesvints** [comment]
@commando1251 please see my messages above.
