### ISSUE TITLE
Segmentation fault when calling hasOne or hasMany relationship

### ISSUE THREAD

**Issue by andreoneres** [laravel/framework#48959]
### Laravel Version

10.31.0

### PHP Version

8.1.25

### Database Driver & Version

PostgreSQL 13.11 for Debian 11 on amd64

### Description

When calling the user-related profile with hasOne, the PHP server breaks and returns a segmentation fault error. To test, I replaced hasOne with belongsTo and it stopped giving errors.

### Steps To Reproduce

**User Class:**

class User extends Model
{
    use HasUuids, HasFactory, Notifiable;

    /**
     * Desativa a criação automática de timestamps.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * Nome da tabela.
     *
     * @var string
     */
    protected $table = "usuario";

    /**
     * Atributos que devem ser ocultados na serialização.
     *
     * @var array<int, string>
     */
    protected $hidden = ["senha", "pivot", "uuid"];

    /**
     * Atributos que devem ser convertidos.
     *
     * @var array<string, string>
     */
    protected $casts = [
        "password" => "hashed",
    ];
    
    /**
     * Retorna as colunas que devem receber um identificador único.
     *
     * @return array
     */
    public function uniqueIds(): array
    {
        return ["uuid"];
    }

    /**
     * Retorna o crédito associado a este usuário.
     *
     * @return HasOne
     */
    public function credit(): HasOne
    {
        return $this->hasOne(Credit::class, "usuario");
    }
}

A request is made to search for a user and their credit and... error:
![image](https://github.com/laravel/framework/assets/61215522/867d07e8-cb30-41d4-a2c6-427c1d78975b)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
