### ISSUE TITLE
Mail Faker does not emit `MessageSending` or `MessageSent` events when testing mailables.

### ISSUE THREAD

**Issue by jimrubenstein** [laravel/framework#48952]
### Laravel Version

10.28

### PHP Version

8.1.4

### Database Driver & Version

N/A

### Description

When writing tests using the `MailFake` mailer to determine if Mailables are sent, and subsequent Message events are emitted (and the behavior of the associated Listeners is as-expected), the `MessageSending` and `MessageSent` events (described in [in the docs](https://laravel.com/docs/master/mail#events)) are not emitted.

### Steps To Reproduce

1. Create a mailable: `php artisan make:mail MyTestMail`
2. Create a listener: `php artisan make:listener MailSentListener`
```php
namespace App\Listeners;

use Illuminate\Mail\Events\MessageSent;

class MailSentListener
{
    public static $executed = false;

    public function handle(MessageSent $event): void
    {
        static::$executed = true;
    }
}
```
3. Add the event/listener configuration to the `EventServiceProvider.php`
```php
protected $listen = [
    Illuminate\Mail\Events\MessageSent::class => [
        App\Listeners\MailSentListener::class,
    ],
];
```

4. Create a test: `php artisan make:test MailTest --pest`
5. Write test:

```php
use App\Listeners\MailSentListener;

it('emits mail events', function() {
  Mail::fake();
  Mail::send(new MyTestMail());

  expect(MailSentListener::$executed)->toBe(true);
});
```  

6. Run your test, and see the failure `php artisan test`

**Comment by crynobone** [comment]
https://laravel.com/docs/10.x/mail#testing-mailable-content

Shouldn't you just use the available assertion. Mail::fake() doesn't actually send an email.
