### ISSUE TITLE
Multi-word blade component attributes aren't passed to child component

### ISSUE THREAD

**Issue by jacksleight** [laravel/framework#48956]
### Laravel Version

10.31.0

### PHP Version

8.2.11

### Description

When passing multi-word blade component attributes to a child component they don't make it to the child component. Probably best explained with an example:

### Steps To Reproduce

I have a blade component called `foo`:

```blade
@props([
    'one' => 'none',
    'twoWord' => 'none',
])
{{ $one }} {{ $twoWord }}
```

And I have another blade component called `bar` which simply wraps `foo` and passes everything down:

```blade
<x-foo :attributes="$attributes"></x-foo>
```

If I render these two components  like this:

```blade
<x-foo one="ok" two-word="ok"></x-foo>
<x-bar one="ok" two-word="ok"></x-bar>
```

I would expect this output:

```
ok ok
ok ok
```

However instead I get:

```
ok ok
ok none
```

In both instances if I dump the attribute bag inside `foo` it's empty, which I would expect.

The `two-word`/`$twoWord` value just seems to disappear when passed via `bar`, but the `one`/`$one` value works fine.

![Screenshot 2023-11-09 at 11 41 06](https://github.com/laravel/framework/assets/126740/5f3c26a8-eca8-45a4-a047-fca1632a22a1)

`foo` and `bar` are both anonymous components.

**Comment by guiassemany** [comment]
Hello!

I do not have a great amount of experience using Blade components, but I noticed something a while ago that made me realize I might not fully understand all the concepts about Blade components, and perhaps I was the one making mistakes.

Maybe it is a bug, but I'm not sure. I'd prefer to share this here and see if someone with more experience can figure it out.

Let's consider the scenario that @jacksleight mentioned above.

"foo" anonymous Blade component:

```blade
// resources/views/components/foo.blade.php
@props([
    'one' => 'none',
    'twoWord' => 'none',
])
<div>
    One: {{ $one }} <br>
    Two: {{ $twoWord }} <br>
</div>
```

And the "bar" anonymous blade component
```blade
// resources/views/components/bar.blade.php
<div>
  <x-foo :attributes="$attributes" />
</div>
```

If we use them like this on the welcome.blade.php file
```blade
foo
<x-foo one="ok" two-word="ok" />

bar (kebab-case):
<x-bar one="ok" two-word="ok" />

bar (camelCase):
<x-bar one="ok" twoWord="ok" />
```

For some reason, the `kebab-case` version of the bar component won't work as expected, but the camelCase version will.

This is the output:
![CleanShot 2023-11-09 at 14 01 01](https://github.com/laravel/framework/assets/793994/97f70bac-7030-44a8-8742-81cb646d34ed)

To make the kebab-case version work, I had to use @aware on the foo component and put the name of the prop. 

```blade
@props([
    'one' => 'none',
    'twoWord' => 'none',
])
@aware(['twoWord'])
<div>
    One: {{ $one }} <br>
    Two: {{ $twoWord }} <br>
</div>
``` 

![CleanShot 2023-11-09 at 14 35 44](https://github.com/laravel/framework/assets/793994/51327c95-50d3-4fc0-bebe-0be9ab22b002)


But I think this is not how it's supposed to work. Again, there is a good chance that I am misunderstanding something, but I just wanted to contribute this information.

**Comment by jacksleight** [comment]
Yeah my understanding is that you should always use kebab case in the tag and camel case in `@props()`.

And it does work as expected if you make `$twoWords` a prop in `foo`, but something is preventing that from working when the values are passed down to `bar`.

**Comment by taylorotwell** [comment]
If you know it is a prop you should declare it as such in your wrapped component and pass it as a propped to the final child component.
