### ISSUE TITLE
Eloquent raw query have different result and response with raw query into the database

### ISSUE THREAD

**Issue by alizaenazet** [laravel/framework#48963]
### Laravel Version

10.29.0

### PHP Version

8.3.0RC1

### Database Driver & Version

mysql  Ver 8.1.0 for macos13 on arm64 (MySQL Community Server - GPL)

### Description

I want to select into table `portfolios` with a column `date` type of 'date' 
<img width="580" alt="Screenshot 2023-11-10 at 13 35 14" src="https://github.com/laravel/framework/assets/96227680/59bbfbe2-a548-4690-8a95-b2d5344bba78">

I'm trying to select all of the `portfolios` rows within multiple values of 'years' like this: `select * from `portfolios` where YEAR(date) in (2021,2012,2015,2020)`
<img width="819" alt="Screenshot 2023-11-10 at 13 36 36" src="https://github.com/laravel/framework/assets/96227680/c7833763-0529-4c20-95c5-2c51811949d7">

The problem is if I run the query from database client that will work but did not eloquent with same query `select * from `portfolios` where YEAR(`date`) in (2021,2012,2015,2020)` ; 

[shared error page](https://flareapp.io/share/yPagNzE5#context-request-browser)

The conclusion : 
Query works when used in database client but not in eloquent 

### Steps To Reproduce

the code
 ``` php
$portfolioByYear = DB::table('portfolios')->whereRaw('YEAR(`date`) in ?', '(2021,2012,2015,2020)')->get();
                // $portfolioByYear = Portfolio::whereRaw('YEAR(`date`) in ?', '(2021,2012,2015,2020)')->get(); have same result
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by alizaenazet** [comment]
what??, thats not  bug??. eloquent showing query and then the query is can work in the database client but the eloquent get error.
