### ISSUE TITLE
Collection methods are unable to follow magic methods

### ISSUE THREAD

**Issue by nicolasvac** [laravel/framework#49001]
### Laravel Version

10.10

### PHP Version

8.1.4

### Description

When dealing with old code, it happens to find properties defined by magic methods (especially in ORMs).

Collections methods like pluck are unable to follow the magic method, even is no reflection is used.

I dont know if this affects other parts of the laravel framework, i only tested it on collections.

Also Eloquent uses the magic method __get() too so i do not understand why this is not working.

### Steps To Reproduce

Here is a reproducible example with a basic class in a controller:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PluckController extends Controller
{

    public function index()
    {
        $element = new PluckElement();

        dd(
            $element->testProperty,
            collect([$element])->pluck('testProperty')->all()
        );
    }
}

/**
 * @property bool testProperty
 */
class PluckElement
{
    public function get_testProperty(): bool
    {
        return true;
    }

    public function __get(string $name)
    {
        if (method_exists($this, "get_$name")) {
            $name = "get_$name";
            return $this->$name();
        }

        return false;
    }
}
```

Here is the outcome: 
![image](https://github.com/laravel/framework/assets/45635090/3c1950a3-3f38-44c6-894f-bf0fb7debbae)

I would expect the output of the array to contain the element.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rodrigopedra** [comment]
@nicolasvac 

`Collection@pluck()` will work with unknown properties of an object, as long as it implements the `ArrayAccess` interface.

That is why it works as expected for Eloquent models. Eloquent models implement that interface.

Under the hood, `Collection@pluck()` uses the `data_get()` helper.

https://github.com/laravel/framework/blob/35aa3dd44762ec4244fb5cd1d9d7156c9455f026/src/Illuminate/Collections/helpers.php#L77-L83

`Arr::accessible()` checks if the variable is an array, or if it is an object that implements `ArrayAccess`.

All other objects are checked on the next `elseif` condition, which checks if the property actually exists in that object. A magic getter fails on this.
