### ISSUE TITLE
incrementEach and decrementEach dont respect where query when used for eloquent model

### ISSUE THREAD

**Issue by royduin** [laravel/framework#49009]
### Laravel Version

10.32.1

### PHP Version

8.1.22

### Description

Related: https://github.com/laravel/framework/pull/45577 and https://github.com/laravel/framework/issues/48595, copied the description from that issue:

incrementEach() and decrementEach() dont respect where condition when used for eloquent model.

```
$user = User::where('shop_id', 1)->first();
$user->decrementEach(['counter' => 1, 'balance' => 100]);
```

All users in the table are decremented whatever 'shop_id' they have.

Please note that the problem is only if executed via eloquent model , but works correctly if executed via direct query as below

```
User::where('shop_id', 1)->decrementEach(['counter' => 1, 'balance' => 100]); // works correctly
```

### Steps To Reproduce

See description

**Comment by driesvints** [comment]
Yes that's expected and how these methods work. They're not scoped to the single instance of the model.

**Comment by federico-boncaldo** [comment]
Our team had a similar issue with `incrementEach` and noticed a behaviour difference between the `increment` method and `incrementEach`. 
If the `increment` is used on a single instance of the model, the query is applied only to a single row, while `incrementEach` applies the update to the whole table. 
The behaviour of the `increment` method on the model object seems more intuitive, and it would be great if you could apply the same behaviour to `incrementEach` and `decrementEach`.

**Comment by CasEbb** [comment]
+1

Ran into the same problem. The difference in behaviour between `increment` and `incrementEach` is currently confusing and potentially dangerous.

**Comment by Roardom** [comment]
This was completely unexpected. This made it into prod and I have to restore backups now.

**Comment by matthiasPOE** [comment]
@driesvints can you please reconsider opening this there is no way this cant be considered a bug without changing the name of the functions to be more obvious.

**Comment by SjorsO** [comment]
Opened another issue to hopefully get this fixed: https://github.com/laravel/framework/issues/57262

**Comment by thomasmokuaomweri2011** [comment]
Please show some love to the newly introduced fix PR https://github.com/laravel/framework/pull/57302
This could go into the major release as it has a BC
