### ISSUE TITLE
Performance Issue with Eloquent: Connection Timeout on Delivery::find($id)->first();

### ISSUE THREAD

**Issue by zee404** [laravel/framework#49018]
### Laravel Version

9.19

### PHP Version

8.028

### Database Driver & Version

Server version: 10.4.25-MariaDB

### Description

I'm encountering a significant performance discrepancy when making an API call to retrieve delivery data using Eloquent. The request gets stuck, leading to a connection timeout in Postman. However, when using the Query Builder (DB::table('deliveries')->where('id', $id)->first();), the response is returned within milliseconds.

I have commented all relationships and tried but nothing works.

**Note:**
I have tried the same query in the Query Builder (DB::table('deliveries')->where('id', $id)->first();) and experienced no issues.

Any guidance or insights into resolving this performance discrepancy would be highly appreciated.

### Steps To Reproduce

Make an API call using Eloquent: Delivery::find($id)->first();
Observe the connection timeout in Postman.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
