### ISSUE TITLE
Arr::map($array, 'trim') doesn't work, is this a bug?

### ISSUE THREAD

**Issue by pintend** [laravel/framework#49013]
### Laravel Version

10.4.1

### PHP Version

8.2.11

### Description

```php
// Sample of how I got here
str($string)
    ->explode("\n")
    ->filter(someFilterFunction(...))
    ->map('trim') // This has no affect
    ->first()
```

Why is happens:
```php
class Arr
...
public static function map(array $array, callable $callback)
{
    $keys = array_keys($array);

    try {
        $items = array_map($callback, $array, $keys);
    } catch (ArgumentCountError) {
        $items = array_map($callback, $array);
    }

    return array_combine($keys, $items);
}
```
in `Arr::map()` we first try to pass the keys to the callback and only if that fails do we fallback to one argument. The problem is trim takes a second argument `$characters` https://www.php.net/manual/en/function.trim.php which is the characters to trim off each end. So essentially `Arr::map($array, 'trim')` is trying to trim the `key` of each `item`

Is this considered a bug? does it make sense to assume functions require 1 argument and if that fails then pass the key (why would a function have an optional argument `$key`? `function ($value, $key = null) {}` feels wrong.

Or maybe we add a flag `Arr::map(array $array, callable $callback, bool $withKeys = true)` which we can then decide ourselves if we should use ignore the keys?

Proposed:
```php
class Arr 
...
public static function map(array $array, callable $callback, bool $withKeys = true)
{
    $keys = array_keys($array);

    try {
        if (!$withKeys) {
            throw new ArgumentCountError;
        }
        $items = array_map($callback, $array, $keys);
    } catch (ArgumentCountError) {
        $items = array_map($callback, $array);
    }

    return array_combine($keys, $items);
}



class Collection
...
public function map(callable $callback, bool $withKeys = true)
{
    return new static(Arr::map($this->items, $callback, $withKeys));
}
```
Which would then allow
```php
str($string)
    ->explode("\n")
    ->filter(someFilterFunction(...))
    ->map('trim', withKeys: false)
    ->first()
```

Does this make sense for a pull request or am i doing something wrong here?

### Steps To Reproduce

```php
/** php artisan tinker */
$array = ['  hello, world! '];

Arr::map($array, 'trim'); // Nothing changed
```

Current output
```
[
    "  hello, world! ",
]
```

Expected output
```
[
    "hello, world!",
]
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
