### ISSUE TITLE
Default Service Providers replace() method bug.

### ISSUE THREAD

**Issue by jonagoldman** [laravel/framework#49021]
### Laravel Version

10.32.1

### PHP Version

8.2.12

### Description

The `replace()` method in `Illuminate\Support\DefaultProviders` always omits the first item and doesn't replace it.

https://github.com/laravel/framework/blob/6e4ecc7e2e67ba36eca325ff49adc55e93a72eb7/src/Illuminate/Support/DefaultProviders.php#L66-L77

This is because `$key` is `0` when the matched item is the first one in the array.

```php
$key = $current->search($from); 
  
$current = $key ? $current->replace([$key => $to]) : $current; 
```

### Steps To Reproduce

The first array item returned by `defaultProviders()` is :
```php
[0 => \Illuminate\Auth\AuthServiceProvider::class]
```

Because `$key` is `0` it will not be replaced by my custom provider:

```php
use Illuminate\Support\ServiceProvider;

ServiceProvider::defaultProviders()->replace([
    \Illuminate\Auth\AuthServiceProvider::class => \App\Custom\AuthServiceProvider::class,
])->toArray();

**Comment by driesvints** [comment]
Thanks. Seems you provided a PR so let's see how it goes 👍
