### ISSUE TITLE
Method `getUser` on Auth Facade does not work correct when auth with Sanctum

### ISSUE THREAD

**Issue by MrShnaider** [laravel/framework#49028]
### Laravel Version

10.22.0

### PHP Version

8.1

### Description

Auth facade has 2 methods: `getUser` and `user`. And `getUser` does not work, when there is `auth:sanctum` on routes. But just `user` does. And if there is no `auth:sanctum`, both methods work correctly

### Steps To Reproduce

1. I installed Sanctum for SPA (with session based auth)
2. In web routes I set `auth:sanctum` middleware
3. In controller I called `Auth::getUser()` - and it didn't work
4. In same controller I called `Auth::user()` - and it worked

**Comment by rodrigopedra** [comment]
The Auth facade delegates the static method calls to the underlying guard.

`getUser()` is available in the `SessionGuard`, but not on other guards, and will return the user set on the Session object.

When using `auth:sanctum`, the Sanctum guard does not call `SessionGuard::setUser()` to tell the session which user is logged in, so `SessionGuard@getUser()` will return `null`, even for web routes, or if using sessions.

When using `auth:sanctum`, or any other authentication guard other than the `SessionGuard`, just use `Auth::user()`.

**Comment by crynobone** [comment]
Thanks @rodrigopedra

**Comment by MrShnaider** [comment]
Yes, that's what I assumed from the code. But doesn't that violate LSP? I use a stable interface where there is a `getUser` method, but I don't get user because there are additional conditions in another part of the program. Maybe just delegate the work of `getUser` to the `user` method? This will remove the confusion and won't break the existing code.

**Comment by rodrigopedra** [comment]
> I use a stable public interface where there is a `getUser` method

Which "stable public interface" are you referring to?

Docblocks on Façades were added to improve IDE support, they are not a "stable public interface".

Neither a code stability guarantee. They were mostly maintained by the community, until someone contributed a tool to add missing methods automatically. Even though, if a method signature changes, there are cases someone has to fix them manually.

On the other hand, all classes implementing the `Guard` interface should provide a `user()` method:

https://github.com/laravel/framework/blob/e72327a0ad074a2d9d56742e6c7ff9eab1042528/src/Illuminate/Contracts/Auth/Guard.php#L21-L26

From an LSP perspective, one should rely on a guard providing the `user()` method.

Maybe you can send a PR removing the docblock for it from the `Auth` façade, as it does not apply to all guards, and if you believe that could be confusing to users.

**Comment by MrShnaider** [comment]
You're right, I use ide-helper for hints. And when I use the global function `auth` - it shows me Guard. But when I use the facade, it shows that there is a `getUser` method on it, as it is written in the [official api documentation](https://laravel.com/api/10.x/Illuminate/Support/Facades/Auth.html#method_getUser). So helper does everything according to the documentation. It may be worth fixing the official api doc
