### ISSUE TITLE
A bug was detected when using the `prefix` method without `group` method

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/framework#49039]
### Laravel Version

10.32.1

### PHP Version

8.2.12

### Description

When using the `prefix` method on routes that are not groups, it incorrectly generates the destination URL.

It should be like this:

```
POST api/orders/some ..... orders.index › OrderController@index
POST api/webhook/some ............. webhook › WebhookController
```
But this option is displayed instead:
```
POST api/orders/some ..... orders.index › OrderController@index
POST webhook/api/some ............. webhook › WebhookController
```

### Steps To Reproduce

1. Create a controllers:
    ```bash
    php artisan make:controller OrderController
    php artisan make:controller WebhookController -i
    ```
2. Create routes:
    ```php
    use App\Http\Controllers\OrderController;
    use App\Http\Controllers\WebhookController;

    app('router')
        ->name('orders.')
        ->prefix('orders')
        ->controller(OrderController::class)
        ->group(static function () {
            app('router')->post('some', 'index')->name('index');
        });
    
    app('router')
        ->name('webhook')
        ->prefix('webhook')
        ->post('some', WebhookController::class);
    ```
3. Execute the console command:
    ```bash
    php artisan route:list
    ```

https://github.com/laravel/framework/assets/10347617/c9ad88ab-653a-4f32-94e3-b4ea6a0402da

**Comment by andrey-helldar** [comment]
Repository: https://github.com/andrey-helldar/laravel-issue-49039
Commit: https://github.com/andrey-helldar/laravel-issue-49039/commit/3f6a81c4063129cf324ae4338e0a03558ca61e49
Result:

```bash
Helldar@HellPC MINGW64 /d/domains/bug-report (main)
$ php artisan route:list

  POST       api/orders/some .................................................... orders.index › OrderController@index
  POST       webhook/api/some ............................................................ webhook › WebhookController
```

**Comment by nikopeikrishvili** [comment]
Hello, I have tested with the examples provider, and I have the same result as @andrey-helldar 
![Screenshot 2023-11-20 at 14 47 26](https://github.com/laravel/framework/assets/10278664/74ef950f-d1b1-47bb-a3d0-2efb938580cf)

**Comment by andrey-helldar** [comment]
I've also noticed that it doesn't matter what route and controller names are used. The only important thing is to call the `prefix` method without using a group:

```php
// incorrect
app('router')->prefix('some')->get('', SomeController::class);

// correct
app('router')->prefix('some')->group(
    fn () => app('router')->get('', SomeController::class);
);
```

**Comment by crynobone** [comment]
I would feel the current behavior is expected, since `prefix` is more useful for grouped routes. Feel free to submit PR if you want to improve the behavior
