### ISSUE TITLE
Validation - comparing numeric fields to array fields always fails

### ISSUE THREAD

**Issue by boring-leon** [laravel/framework#49058]
### Laravel Version

10.4.1

### PHP Version

8.2.3

### Description

Validation always fails when comparing array field to a given numeric value.
This should not be the case, as Laravel should be able to compare a given numeric value to an array using `size` rule conventions. (https://laravel.com/docs/10.x/validation#rule-size)

Applies to rules: `lt, gt, gte, lte`.

### Steps To Reproduce

1. Define input which contains of a **numeric** field and an **array** field:
```
$data = [
   'number' => 4,
   'list' => [1,1,1]
];
```
2. Define validation rules so that the array field **size** will be compared against a given numeric field:
```
$rules = [
    'list' => [
      'required',
      'array'
    ],
    'number' => [
      'required',
      'integer',
      'gt:list'
   ]
];
```
4. Run rules against given input: 
```
$validator = Validator::make($data, $rules)'
$validator->messages(); // ['number' => This field must be greater than 3.]
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
