### ISSUE TITLE
Calling env('APP_NAME') in a CLI command returns an unexpected value

### ISSUE THREAD

**Issue by feuzeu** [laravel/framework#49066]
### Laravel Version

10.2.9

### PHP Version

8.1.21

### Description

Hi,

Calling `env('APP_NAME')` in a CLI command always returns a value that is different from what is set in the `.env` file.
The issue is only when reading the `APP_NAME` var in a CLI command. All the other variables values are correct, and reading the  `APP_NAME`  var in a web app on the same server also returns the right value.

I don't know if it is relevant, but I'm running PHP and Laravel on Rocky Linux 8.8.

### Steps To Reproduce

I'm having the issue even on a fresh install of Laravel 10.

```bash
composer create-project laravel/laravel test 10.x
cd test
php artisan make:command TestCommand
```

Here's the `app/Console/Commands/TestCommand.php` file.

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class TestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test-command';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info("The config value is " . config('database.redis.options.prefix'));
        $this->info('The direct call is ' . Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_');
        $this->info('The env value is ' . env('APP_NAME'));
    }
}
```

Here's what I get
```
The config value is ben_database_
The direct call is ben_database_
The env value is ben
```
It seems to me that the returned value is the name part of the server hostname (ben.xxxxxx.xxx), since I've tested on 3 different hosts with the same result.
Changing the `APP_NAME` value in the `.env` file has no effect. The result is still the same.

**Expected result**
On a fresh Laravel install, I expected to have
```
The config value is laravel_database_
The direct call is laravel_database_
The env value is laravel
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
