### ISSUE TITLE
Laravel CSRF field uses 'autocomplete="off"' which MAY be a bug

### ISSUE THREAD

**Issue by archfrog** [laravel/framework#49061]
### Laravel Version

10.32.1

### PHP Version

8.2.10-2ubuntu1

### Description

Hi,

I use the [Validity](https://chromewebstore.google.com/detail/validity/bbicmjjbohdfglopkidebfccilipgeif?hl=en) Chrome extension with the Brave browser.  I routinely use Validity to check that my web pages (generated by Laravel v10.x) are valid HTML5.

When I validate a form I get this error:

```
An “input” element with a “type” attribute whose value is “hidden” must not have an “autocomplete” attribute whose value is “on” or “off”.
```

The offending source line looks like this:
```
<input type="hidden" name="_token" value="2EFM4qx0Bqnn4jcJW8lCHzh0rWWwWRUl5hPqdIU3" autocomplete="off">
```

I am only reporting this as an heads-up to you guys, as I personally don't know if it is truly a bug or not.

Please notice that Validity uses [Nu Validator](https://validator.w3.org/nu/) by default, so frequent updates of the extension itself is not needed, which is why it hasn't been updated since 2022.

Cheers and THANKS for Laravel :-)
Archfrog

### Steps To Reproduce

1. Launch Chrome, Brave, or any other Chromium-based web browser on Windows 10+.
2. Install the [Validity](https://chromewebstore.google.com/detail/validity/bbicmjjbohdfglopkidebfccilipgeif?hl=en) extension.
3. Open any Laravel form with a hidden CSRF field (create a new project or open a form from an existing project).
4. Click on the Validity button in the extension bar (typically upper-right corner).
5. Open the `Developer Tools` using `Ctrl-Shift-I`.
6. Notice that the error `1 validation error` is present in the `Console` tab of the developer tools.
7. Click on the small arrow just before `1 validation error` so it points down.
8. Read the full error message, which is also given above.

**Comment by crynobone** [comment]
See #48371

**Comment by archfrog** [comment]
Arguments FOR removing the superflous and tricky `autocomplete="off"` substring of the hidden Laravel v10.x CSRF field:

1. [Argument FOR #3](https://validator.w3.org/#validate_by_uri).  The W3 validator REJECTS the `autocomplete="off"` part.  Try it out before you ignore or disregard this issue.
2. [Argument FOR #1](https://www.drupal.org/project/drupal/issues/3320467).
3. [Argument FOR #2](https://rocketvalidator.com/html-validation/an-input-element-with-a-type-attribute-whose-value-is-hidden-must-not-have-an-autocomplete-attribute-whose-value-is-on-or-off).

Arguments against:
1. [Argument AGAINST #1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete)

Seems like you guys are not aware that Firefox has devolved into the new Internet Exploder of the 'net.

I am not talking about issues with login on Macs, I am simply talking about the fact that Laravel generates invalid HTML!

I have applied the "Blade::directive()" approach in my own project, but why waste people's time by asking them to add new directives because the built-in directives don't work?

**Comment by archfrog** [comment]
<img width="1165" alt="W3 Nu Checker result" src="https://github.com/laravel/framework/assets/1729893/93ec4a91-e06e-4f67-8c4e-c32c78df2d40">

The result of running Laravel's default, hidden CSRF field through the W3 Nu HTML Checker...
