### ISSUE TITLE
Multiple memcached does not work

### ISSUE THREAD

**Issue by devprofession** [laravel/framework#49079]
### Laravel Version

10.4.1

### PHP Version

8.2.1

### Description

I have 2 memcached servers configured. As it currently works, if one of the servers goes down, memcached doesn't work.
The correct solution would be if one server stops, the other one is still working.
This is unfortunately not the case at the moment.
Could you confirm if this is a problem or am I mistake something?

### Steps To Reproduce

File: src/Illuminate/Cache/MemcachedConnector.php

Current source:

```
public function connect(array $servers, $connectionId = null, array $options = [], array $credentials = [])
    {
        $memcached = $this->getMemcached(
            $connectionId, $credentials, $options
        );

        if (! $memcached->getServerList()) {
            // For each server in the array, we'll just extract the configuration and add
            // the server to the Memcached connection. Once we have added all of these
            // servers we'll verify the connection is successful and return it back.
            foreach ($servers as $server) {
                $memcached->addServer(
                    $server['host'], $server['port'], $server['weight']
                );
            }
        }

        return $memcached;
    }
```
	
	
Possible solution:

```
public function connect(array $servers, $connectionId = null, array $options = [], array $credentials = [])
    {
        $memcached = $this->getMemcached(
            $connectionId, $credentials, $options
        );

        if (! $memcached->getServerList()) {
            // For each server in the array, we'll just extract the configuration and add
            // the server to the Memcached connection. Once we have added all of these
            // servers we'll verify the connection is successful and return it back.
            **$serverlist = array();**
            foreach ($servers as $server) {

                $memcached->addServer(
                    $server['host'], $server['port'], $server['weight']
                );

                **if ($memcached->getVersion() !== false)
                {
                    $serverlist[] = [$server['host'], $server['port'], $server['weight']];
                }
                $memcached->resetServerList();**
            }
        }
        **$memcached->addServers($serverlist);**

        return $memcached;
    }
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
