### ISSUE TITLE
Clarify Collections' interaction with Traversible<object, mixed>, such as WeakMap

### ISSUE THREAD

**Issue by Vectorial1024** [laravel/framework#49089]
### Laravel Version

10.33

### PHP Version

8.1.5

### Database Driver & Version

N/A

### Description

Laravel has `collect()` to produce a Collection; currently, the Collection accepts many types, one of which is PHP's `Traversible`.

It looks fine, but a problem: `WeakMap` implements `Traversible`. From the constructor definition/hinting, `WeakMap` instances are valid Collection "items". But as soon as such Collections are instantiated, a fatal error is always thrown:

```
TypeError: Illegal offset type.
```

Clearly, the underlying data structure of the Collection is an array, which obviously cannot accept objects as keys.

This is quite undocumented in the official Laravel docs in the Laravel website. However, the existing Collection constructor did not really check against WeakMaps.

I do know a bit about the covariance-contravariance thing that makes it a bit difficult to specifically reject `WeakMap` instances during typehinting.

A clarification is very much appreciated:
- If Collections should not accept `WeakMap`, then perhaps the docs should be updated with this info; or, a more specific error message could be printed.
- If Collections are supposed to accept `WeakMap`, then perhaps the Collection class needs some refactoring.

---

One very jarring experience with Laravel, is that e.g. I can do `filter()` on "real array" Collections, but I cannot do `filter()` on `WeakMap` instances, even when in native PHP, both can be traversed with something like 

```php
function filter(array|WeakMap $original, callable|Closure $predicate)
{
    $results = is_array($original) ? [] : new WeakMap();
    foreach ($original as $key => $value) {
        if ($predicate($value)) {
            $results[$key] = $value;
        }
    }
    return $results;
}
```

### Steps To Reproduce

Using `php artisan tinker [file]`:

File contents:

```php
<?php

$testMap = new WeakMap();
$testInstance = new stdClass();
$testInstance->haha = 'yes';
$testMap[$testInstance] = 3;

// should the following line be allowed or rejected?
$testCollection = collect($testMap);
// TypeError: Illegal offset type

// unreachable code: unhandled exception thrown
$testCollection->each(fn($x) => var_dump($x));
```

**Comment by crynobone** [comment]
Submitted a PR to throw exception when trying to use `$testCollection = collect($testMap);`

**Comment by Vectorial1024** [comment]
Slow down! The problem is not that trivial.

I did some more research after submitting this, and realized `WeakMap` is not the only class affected by this clarification. For example, `SplObjectStorage` is also affected by this, because it `instanceof Traversible`, but obviously its keys are all objects, and then it cannot be sent into a Collection.

Basically, any class that is `Traversible` is a potential incompatible class of Collection. To throw more accurate exceptions, we will need to check whether the keys of `Traversible` is of the pseudotype `array-key` (basically `int|string`).

We will never know how many such incompatible classes out there that extends `Traversible` but have their keys in `object` type.

Therefore, the question remains:
- refactor Collections to allow object keys?
- improve detection of `Traversible<object, mixed>`?

**Comment by Vectorial1024** [comment]
I noticed this flag in [iterator_to_array](https://www.php.net/manual/en/function.iterator-to-array.php):

- preserve_keys

Will setting it to false help with the situation? I see mentions of doing so to give out items inside `SplObjectStorage` instances.

**Comment by crynobone** [comment]
You can't convert WeakMap to an array and we not planning to add support for WeakMap using Collection at the moment.
