### ISSUE TITLE
M$ SQL Server SQLSTATE[22007] on a Laravel Jetstream new installation

### ISSUE THREAD

**Issue by warptoy** [laravel/framework#49157]
### Laravel Version

10.33.0

### PHP Version

8.2.13

### Database Driver & Version

Microsoft SQL Server 15.00.2101 (2019)

### Description

I have recently started a Laravel + Jetstream test project, as I need to to use SQL Server.  At the first attempt to insert a Laravel user, it crashes with this error:
`SQLSTATE[22007]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]La conversione di un tipo di dati nvarchar in datetime ha generato un valore non compreso nell'intervallo dei valori consentiti. (Connection: sqlsrv, SQL: insert into [users] ([name], [email], [password], [email_verified_at], [updated_at], [created_at]) values (xyz, warptoy@libero.it, $2y$12$jUb48hHfU/yW8SZEy30hku5qKY.2.Sz3IQZUT2BvTl.SL8q.39kSa, 2023-11-28 11:45:35.951, 2023-11-28 11:45:36.393, 2023-11-28 11:45:36.393))`

I know the issue may seem like a duplicate of [#19406](https://github.com/laravel/framework/issues/19406) or [#18991](https://github.com/laravel/framework/issues/18991) but the problem has never been resolved as it reoccurs with a fresh installation of Laravel with all default parameters.

From what I understand, fields that hold DATE and TIME values created by Laravel are always of type **DATETIME**, with milliseconds expressed in **3 digits**. However, **Laravel sends 4 digits**, causing issues with the SQL server. To address this, you can either modify all models to use a 4-digit format, which enforces the creation of DATETIME2 fields in the database, or rewrite the fromDateTime() function within the models. 

_These are workarounds when it might be sufficient for Laravel to consistently use only 3 digits for milliseconds. Alternatively, parameterize the option in some way. In any case, 3 milliseconds provide more than sufficient precision for any type of transcription._

### Steps To Reproduce

Install a fresh Laravel + Jetstream using Microsoft SQL Server as DB, and the issue will arise on the first user insertion.

**Comment by driesvints** [comment]
You have control over this: https://laravel.com/docs/10.x/eloquent-mutators#date-casting

<img width="711" alt="Screenshot 2023-11-28 at 13 37 13" src="https://github.com/laravel/framework/assets/594614/e0f9d1d0-e2c9-4b36-ad6f-a1f5d60fb2b0">

Also please indeed see many issues about this in the tracker. If anything is unclear we appreciate a PR to the docs.

**Comment by fabton1963** [comment]
Hello, I'm experiencing the same issue. Additionally, I've noticed that the error log, as also highlighted by @warptoy, shows the dates formatted correctly as "2023-11-28 11:45:35.951, 2023-11-28 11:45:36.393, 2023-11-28 11:45:36.393". In fact, if you copy the query displayed in the log and feed it to SQL Server using PDO, it executes without problems. Hence, I suppose it's something at a lower level that uses microseconds when writing timestamps.
