### ISSUE TITLE
$request->user() or Auth::user run query each time if token doesn't exists

### ISSUE THREAD

**Issue by mnr73** [laravel/framework#49201]
### Laravel Version

10.34.2

### PHP Version

8.2.12

### Database Driver & Version

8.2.0

### Description

sanctum version : 3.3.2

Hi, I use Laravel with Sanctum, and I've noticed that the app runs a query each time I use request()->user()
![image](https://github.com/laravel/framework/assets/23061025/b8bc5c45-2520-44f3-9dce-f6b9c3c2d7b0)

I found that if the saved token is incorrect or doesn't exist in the database, the user resolver runs a query each time it is called, and this is not good for performance.

### Steps To Reproduce

you can run a fresh Laravel app with sanctum and set wrong token in Bearer token that not exist and use request()->user() for times.

I check app and query log with Clockwork browser extension.

**Comment by mpyw** [comment]
@taylorotwell decided to get along with this behavior on #49205, we won't wix

---

You should check through `Auth::hasUser()` after your first call for `Auth::user()` (available since 5.6)

- https://github.com/laravel/framework/pull/24518

**Comment by driesvints** [comment]
Thanks @mpyw 

@mnr73 please see the above.

**Comment by mnr73** [comment]
thanks. I handled this 🙏
