### ISSUE TITLE
Schedule command on last day of the month with a different timezone did not execute

### ISSUE THREAD

**Issue by pascalvgemert** [laravel/framework#49211]
### Laravel Version

10.30.1

### PHP Version

8.2.6

### Description

**Situation:**

We have a schedule:
```
$schedule->command(ExampleCommand::class)->lastDayOfMonth('23:30');
```

We also have set the timezone to for the kernel to CET:

```
'schedule_timezone' => 'Europe/Amsterdam',
```

The server itself runs in UTC.

The `lastDayOfMonth` uses `Carbon::now()`, but I believe it didn't take the timezone into account.

**Possible solution:**

Add timezone when getting the last day of the month, like in the `inTimeInterval` method :

```
// In src/Illuminate/Console/Scheduling/ManagesFrequencies.php:562
public function lastDayOfMonth($time = '0:0')
{
    $this->dailyAt($time);

    return $this->spliceIntoPosition(3, Carbon::now($this->timezone)->endOfMonth()->day);
}
```

### Steps To Reproduce

1. Add scheduled command: `$schedule->command(ExampleCommand::class)->lastDayOfMonth('23:30');`
2. Make sure the server runs in UTC
3. Make sure the commands are scheduled in CET via `config/app.php` => `'schedule_timezone' => 'Europe/Amsterdam',`
4. Somehow try to trigger this schedule naturally 
5. Assert that it did not execute

**Comment by tntsoft** [comment]
Created #49302 that implements the above, it requires a test though - I couldn't quite figure out how to mock the server timezone vs app config timezone bit in order to write it.

**Comment by pascalvgemert** [comment]
@tntsoft I was struggling with the same issue.

Maybe we can make it work with (found on SO):

```
public function testRunsAt930()
{
    Event::fake();
    $this->travelTo(now()->startOfWeek()->setHour(9)->setMinute(30));
    $this->artisan('schedule:run');
    
    Event::assertDispatched(ScheduledTaskFinished::class, function ($event) {
        return strpos($event->task->command, 'your-command-name') !== false;
    });
}
```

I will try this tomorrow!

**Comment by jbrooksuk** [comment]
Changing a server's timezone often requires restarting various services, `cron` being one of them. This would automatically resolve the issue you faced here.

**Comment by pascalvgemert** [comment]
**Update:** 
Still debugging, have created a test. The schedule did run so far as I can see now, but still at the wrong time. So I'm checking wether this is an issue in de code or server / env configuration.

**Comment by pascalvgemert** [comment]
I will close the PR as the command has ran at the correct time and it was a configuration issue. My excuses for the trouble, but better safe than sorry.
