### ISSUE TITLE
Docs state, that "whereJsonContains" method can be used in SQLite3.38 or higher, but "compileJsonContains" method is not implemented in Illuminate\Database\Query\Grammars\SQLiteGrammar.php

### ISSUE THREAD

**Issue by Sagmedjo** [laravel/framework#49217]
### Laravel Version

10.34.2

### PHP Version

8.2.3

### Database Driver & Version

3.39

### Description

When testing I am using sqlite.

When now trying to use the "whenJsonContains" method or any derived method, it throws the error message:
"This database engine does not support JSON contains operations."

In the docs on the other hand you can find this example:

`$users = DB::table('users')
                ->whereJsonContains('options->languages', 'en')
                ->get();`
Right above you can find this text: "You may use whereJsonContains to query JSON arrays. This feature is not supported by SQLite database versions less than 3.38.0:"
 
 SQLite still has no "json_contains" method. Another approach would be to use the json_each method as follows:
 
` SELECT {table}.* from {table}, json_each({table}.{column}, {path}) as {table}{column}Each WHERE {table}{column}Each.value = {value};`

It would still have the same restriction, that you can only search for a non array value but it should work

### Steps To Reproduce

[https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php)

**Comment by crynobone** [comment]
Do you have JSON1 extension enabled just as described in the documentation?

**Comment by Sagmedjo** [comment]
As stated in the [SQLite docs](https://www.sqlite.org/json1.html#overview). That is only necessary for SQLite versions prior to 3.38.
But that is not my point. If you would have read the [SQLiteGrammar.php](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php) file, you would have seen, that the method needed to compile the SQL is not even implemented for SQLite.

> 2. Compiling in JSON Support
> The JSON functions and operators are built into SQLite by default, as of SQLite version 3.38.0 (2022-02-22). They can be omitted by adding the -DSQLITE_OMIT_JSON compile-time option. Prior to version 3.38.0, the JSON functions were an extension that would only be included in builds if the -DSQLITE_ENABLE_JSON1 compile-time option was included. In other words, the JSON functions went from being opt-in with SQLite version 3.37.2 and earlier to opt-out with SQLite version 3.38.0 and later.

**Comment by peterthomson** [comment]
We shimmed the SQLite grammar to at least get tests passing but I'm sure there's a better way. 
`use Illuminate\Support\Facades\DB;
use Illuminate\Database\Query\Grammars\SQLiteGrammar;

class PatchedSQLiteGrammar extends SQLiteGrammar
{
    public function __construct()
    {
        DB::connection()->getPdo()->sqliteCreateFunction('JSON_CONTAINS', function ($json, $val, $path = null) {
            $array = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
            $val = trim($val, '"');

            if ($path) {
                return $array[$path] == $val;
            }

            return in_array($val, $array, true);
        });
    }

    protected function compileJsonContains($column, $value)
    {
        [$field, $path] = $this->wrapJsonFieldAndPath($column);

        return 'json_contains('.$field.', '.$value.$path.')';
    }
}`

**Comment by crynobone** [comment]
This has been merged and released in 10.38
