### ISSUE TITLE
PHPUnit's process isolation doesn't work due to Laravel's application bootstrapping

### ISSUE THREAD

**Issue by l-alexandrov** [laravel/framework#49237]
### Laravel Version

10.34.2

### PHP Version

8.3.0

### Database Driver & Version

MariaDB 10.4.32

### Description

PHPUnit's process isolation feature doesn't work starting from PHPUnit 10.2.0 on Laravel.

Tried to run a minimal test case with process isolation, extending the plain PHPUnit's `PHPUnit\Framework\TestCase` class and it runs fine. 

But, when I try to run it over the Laravel's Testing platform it fails with error `Test was run in child process and ended unexpectedly`

---
Related https://github.com/sebastianbergmann/phpunit/issues/5595

### Steps To Reproduce

1. Create a minimal test case with process isolation, extending the Laravel's `TestCase` class:
```
<?php

declare(strict_types=1);

namespace Tests\Unit\Casts;


use Tests\TestCase;

class MyTestCase extends TestCase
{
    /**
     * @test
     * @runInSeparateProcess
     */
    public function it_is_true(): void
    {
        $this->assertTrue(true);
    }

}
```
2. See the error

**Comment by arclw** [comment]
IMP `--parallel` flag is used to run the multiple tests concurrently to speed up the test running process; it has nothing to do with weather a test method should entirely isolated in its own space to avoid class loading conflicts. 
**Same tests:**
Working in Laravel base test class in PHP 8.2 but **NOT** in 8.3; while the annotation works fine in PHPUnit's test case class in PHP 8.3 as well.

**Comment by siketyan** [comment]
As a workaround, calling `restore_error_handler()` in `tearDown` works for me. It is caused by an error handler which is set in HandleExceptions bootstrapper. I don't know why this is caused in PHP 8.3 only.

**Comment by Boevsson** [comment]
You guys forgot to tearDown properly: 

You sohuld call the parent::tearDown()

```
	protected function tearDown(): void
	{
		parent::tearDown();

		Mockery::close();
	}
```

**Comment by maxxwv** [comment]
I don't see it mentioned here, but in 11.21.0 (possibly earlier) this looks like it's fixed by using the attributes:
```php
#[RunInSeparateProcess]
public function testDoTheTest(): void
{
    // assertions - I was working with Mockery::mock('overload:App\Path\To\Class');
}
```
Or
```php
#[RunTestsInSeparateProcesses]
class SomeThingTest extends Test Case {
    //
}
```
