### ISSUE TITLE
ComponentAttributeBag::class() crashes

### ISSUE THREAD

**Issue by JohanFredrikVaren** [laravel/framework#49248]
### Laravel Version

10.34.2

### PHP Version

8.2.8

### Description

According to the sub-chapter [Conditionally Merge Classes](https://laravel.com/docs/10.x/blade#conditionally-merge-classes) in the Laravel docs, it should be possible to conditionally set/merge CSS classes using the `ComponentAttributeBag::class()` method. However, if the attribute bag contains attribute values that can not be cast to strings, the call crashes.

The `ComponentAttributeBag::class()` method eventually calls `ComponentAttributeBag::merge()`, subsequently leading to the error being thrown in the `ComponentAttributeBag::__toString()` implementation.

### Steps To Reproduce

Given the two component templates `foo.blade.php` and `bar.blade.php`, rendering the `foo` component will cause a PHP `TypeError` to be thrown.

![image](https://github.com/laravel/framework/assets/8833556/d2904fd7-e714-4185-bb2e-5452d96fa74a)
![image](https://github.com/laravel/framework/assets/8833556/30cefdde-3e1a-467f-94c7-bb8d048e5002)

![image](https://github.com/laravel/framework/assets/8833556/98d9df88-1188-44f9-83bf-750f94f9e97b)

The same error is also thrown if one tries to utilize the `ComponentAttributeBag::merge()` method:

![image](https://github.com/laravel/framework/assets/8833556/024eb87b-b7a3-482b-9c91-171f5fd31b13)

**Comment by driesvints** [comment]
I'm not really sure what you expect here? This usage isn't supported, sorry.
