### ISSUE TITLE
Method Illuminate\\Support\\Number::toCurrency does not exist.

### ISSUE THREAD

**Issue by anice1** [laravel/framework#49253]
### Laravel Version

10.35.0

### PHP Version

8.1.0

### Description

I tried to use the Number Utility but ran into issues like **Undefined type 'Illuminate\Support\Number'.** even after upgrading. 
<img width="933" alt="Screen Shot 2023-12-06 at 3 44 42 am" src="https://github.com/laravel/framework/assets/30138845/e2c302d5-75ed-4383-b181-6d1793cda668">

### Steps To Reproduce

Simply import utility **use Illuminate\Support\Number;**

Number::toCurrency(1000, 'EUR');

**Comment by crynobone** [comment]
Can you display the output of the following command:

```bash
composer show 
```

**Comment by crynobone** [comment]
There's only `Number::currency()` and not `Number::toCurrency()`: https://laravel.com/docs/10.x/helpers#method-number-currency

**Comment by adampatterson** [comment]
> There's only `Number::currency()` and not `Number::toCurrency()`: https://laravel.com/docs/10.x/helpers#method-number-currency

Must have been from https://laravel-news.com/laravel-number-utility-class#content-currency-formatting Becsue I did the same thing 😂
