### ISSUE TITLE
Jobs in chains ignore `ShouldBeUnique`

### ISSUE THREAD

**Issue by tricki** [laravel/framework#49263]
### Laravel Version

10.34.2

### PHP Version

8.1.26

### Database Driver & Version

mariadb 10.5.8 (Laravel Sail)

### Description

When dispatching jobs as part of a chain (using `Bus::chain()`) the uniqueness is not guaranteed.

### Steps To Reproduce

1. Create a new job
2. Implement the `Illuminate\Contracts\Queue\ShouldBeUnique` interface
3. Dispatch the job as part of a chain multiple times
4. Check that job is in the queue multiple times instead of just once

Dispatch example:

```php
Bus::chain([
    new NewUniqueJob(),
])->dispatch();
```

- Taylor's comment in the PR that introduced `ShouldBeUnique`: https://github.com/laravel/framework/pull/35042#issuecomment-720626921
- Bug report about similar issue with batched jobs: https://github.com/laravel/framework/issues/48882
- Closed PR introducing unique chained jobs: https://github.com/laravel/framework/pull/37031

---

Some details about why I could use this right now (also in case someone can suggest a better way): I have an application that acts as a proxy between two other systems (A and B). System A sends an update request for one, multiple or all entities (e.g. entity 1 has been updated). The application then fetches those changes from System A and saves them to the database. Then the application sends a general "change" request to System B, which will then load and import all entities from the application.

Here's a simple sequence diagram:
<img width="882" alt="image" src="https://github.com/laravel/framework/assets/523154/601861e9-d200-4aea-b94a-b0fe58e61d37">

In the end I have three jobs that have to be run in sequence:
1. Load the new data from System A and save to database
2. Clean up database (e.g. removing entities which were deleted in System A)
3. Trigger import in System B.

Additional notes:
- The reason for this complex system is the rigidity of the other systems: Both their APIs are built using no-code tools and are therefore quite inflexible. Both in their data structure and extensibility.
- They're separate jobs because the first one could be scoped to one, multiple or all entities, whereas the third one is always the same.
- In the third job I'm actually using `ShouldBeUniqueUntilProcessing`, but since that interface extends `ShouldQueue` I assume that's not relevant here.
- Previously those steps were done synchronously, because response time wasn't a concern, since it's just APIs. The main reason I refactored to using Jobs is to take advantage of the uniqueness feature.

I'm hoping this will be implemented. If not, I suggest explicitly mentioning that in the docs.

**Comment by tntsoft** [comment]
I've opened a #49294 where I've created a test in order to replicate this, but apparently it works as expected.

What I've done is I've created a unique job through the `ShouldBeUnique` interface and dispatched it through a chain 4 times, but it comes out only 1 time.

@tricki If you have time to provide a clean repository replicating this issue, that would help a ton. Or maybe take a look at the PR (#49294) and let me know what I can do in order to replicate this.

**Comment by tricki** [comment]
Thanks for the response and writing the test! I'll definitely look into it again more closely and report back.

I have to say I never really used the queue before, so I'll have to familiarize myself with how they work, especially how the atomic locks work.

**Comment by driesvints** [comment]
Hi all, is this still being worked on? Seems the test proves this works so this can be closed?
