### ISSUE TITLE
Artisan `test` command's `--no-interaction` does not exist

### ISSUE THREAD

**Issue by azzazkhan** [laravel/framework#49290]
### Laravel Version

10.35.0

### PHP Version

8.1.25

### Description

The `artisan test --help` commands shows an available option `-n, --no-interaction` described as **Do not ask any interactive question** and I added that in my GitHub action workflow but the step crashed printing `Unknown option "--no-interaction".`. Please remove the option from `artisan test` command if it's not supported. Thanks. 

### Steps To Reproduce

Create a new Laravel project with `composer create-project laravel/laravel my-project` and run `php artisan test --no-interaction`.

**Comment by crynobone** [comment]
The command is provided by Collision package, please send the request to the correct repository.
