### ISSUE TITLE
Inconsistent behavior when using `DatabaseTruncation` with In-Memory Database

### ISSUE THREAD

**Issue by KentarouTakeda** [laravel/framework#49312]
### Laravel Version

10.35.0

### PHP Version

8.3.0

### Database Driver & Version

SQLite In Memory Database

### Description

When using `DatabaseTruncation` with an In-Memory Database, the behavior is inconsistent between initial testing and subsequent tests.

The first test in the test class will run `artisan('migrate:fresh')` and the database will be complete before the test begins.

However, subsequent tests start with an empty database with no migrations performed. (For other databases, it will start migrated)

In-Memory Database does not save the database state, so migration results cannot be carried over to the next test.
As a countermeasure for this, `RefreshDatabase` includes a process that migrates not only the first time but every time in the case of `DB_DATABASE=:memory:`.

It seems that the same process is required for `DatabaseTruncation`.

### Steps To Reproduce

1. Configure phpunit.xml as follows:
   ```xml
   <env name="DB_CONNECTION" value="sqlite"/>
   <env name="DB_DATABASE" value=":memory:"/>
   ```

2. Run the following tests.
   ````php
   use DatabaseTruncation;
   
   public function test_create_user_1(): void
   {
        User::factory()->create(); // This test passes
   }
   
   public function test_create_user_2(): void
   {
        User::factory()->create(); // This test will fail
   }
   ````

3. The result should look like this:
   ````
    FAIL Tests\Feature\ExampleTest
   ! create user 1 → This test did not perform any assertions 0.12s
   ⨯ create user 2 0.01s
   ────────────────────────────────
    FAILED Tests\Feature\ExampleTest > create user 2 QueryException
   SQLSTATE[HY000]: General error: 1 no such table: users (Connection: sqlite, SQL: /* Omittion */)
   ````

* For anything other than In Memory Database, pass as follows.
  ```
   WARN Tests\Feature\ExampleTest
  ! create user 1 → This test did not perform any assertions 0.14s
  ! create user 2 → This test did not perform any assertions 0.02s
  ```

**Comment by crynobone** [comment]
It's not possible to use `DatabaseTruncation` with in-memory database since the database will get reset between tests. Feel free to submit PR to the documentation if you feel there's a need to highlight this.
