### ISSUE TITLE
Http client getting status() in retries is broken

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/framework#49318]
### Laravel Version

10.35.0

### PHP Version

8.1.26

### Database Driver & Version

Mysql 5.7

### Description

When using the [retries](https://laravel.com/docs/10.x/http-client#retries) feature of the Http client, attempting to get the `status` from the response as per the docs throws an error and I'm unable to get the response status code.

### Steps To Reproduce

1. Make a get request anywhere to a domain that doesn't exist via the Http client
2. Implement the `retries` function like this:

```php
$client = $client->retry(3, 100, function (Exception $exception, PendingRequest $request) {
    Log::debug('foo');
    Log::debug($exception->response->status()); // <-- this line is erroring
    Log::debug('bar'); // <-- I never make it here

    return true;
});
```

Observe the error:

> Undefined property: Illuminate\Http\Client\ConnectionException::$response

Also, I see my **foo** log but never the **bar** log.

Either the docs is wrong, or getting the response is broken. The domain I used deliberately is one that hangs, which is intentional: sdfsd.com

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by sts-ryan-holton** [comment]
Sure thing, I've posted it here: https://stackoverflow.com/questions/77638876/http-client-getting-status-in-retries-is-broken but likely will get downvoted and pushed back here :)
