### ISSUE TITLE
Possible memory leak on middlewares tampering with the request 

### ISSUE THREAD

**Issue by pghiuzan** [laravel/framework#49333]
### Laravel Version

10.35

### PHP Version

8.3.0

### Description

The `Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class` and `Illuminate\Foundation\Http\Middleware\TrimStrings::class` middleware classes can lead to memory leaks for long-running processes by stacking large amounts of callbacks in the `$skipCallbacks` properties.

I initially ran into problems with a round of regular updates that introduced Livewire 3.2.6 which came with a [specific change](https://github.com/livewire/livewire/commit/24469dafbcb0eb12e6cd5dfec6f99ad4ffb59e44) that helped unearth this issue. Digging a bit deeper, I found the root cause and managed to [reproduce it on a clean Laravel installation](https://github.com/pghiuzan/laravel-10-reproduce-memory-leak-from-middlewares-tempering-request/pull/1).

This issue can take a different shape. When given enough memory, the process might experience significant slowness. For example, running `artisan test` on a project affected by this problem, the HTTP tests will have to execute constantly growing stacks of callbacks, thus significantly affecting the performance of the tests. I wonder if https://github.com/laravel/framework/issues/49243 is a result of this same problem.

### Steps To Reproduce

https://github.com/pghiuzan/laravel-10-reproduce-memory-leak-from-middlewares-tempering-request/pull/1

**Comment by driesvints** [comment]
It looks like Taylor doesn't wants to make changes here sorry.
