### ISSUE TITLE
Clearing user types wipes extension types

### ISSUE THREAD

**Issue by simon-tma** [laravel/framework#49349]
### Laravel Version

10.37.1

### PHP Version

8.3.0

### Database Driver & Version

Postgres 14 + Postgis

### Description

After the inclusion of 57ae89a, dropping types is now also trying to drop types added by extensions (e.g. `postgis`). This is causing the database reset step of tests to fail.

```
  SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop type spheroid because extension postgis requires it
```

### Steps To Reproduce

1. Add `    protected bool $dropTypes = true;` to a feature test with multiple tests
2. Configure the database to use Postgres and create the postgis extension
3. Run the tests

**Comment by hafezdivandari** [comment]
I sent PR #49358 for this.

**Comment by simon-tma** [comment]
Thanks, can confirm this has fixed the issue for me :)
