### ISSUE TITLE
 Warning: #1287 'VALUES function' is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by ErfanBahramali** [laravel/framework#49376]
### Laravel Version

10.37.3

### PHP Version

8.2.13

### Database Driver & Version

8.0.35

### Description

**Warning: `#1287` 'VALUES function' is deprecated and will be removed in a future release. Please use an alias (INSERT INTO ... VALUES (...) AS alias) and replace VALUES(col) in the ON DUPLICATE KEY UPDATE clause with alias.col instead**

The `upsert` function uses `VALUES function` and  `VALUES function` is deprecated 

### Steps To Reproduce

Laravel:
```php
Example::upsert(Example::find(1)->toArray(), ['id','created_at']);
```

MySql:
```sql
INSERT INTO `example` (`id`, `name`, `created_at`)
VALUES (1, "test", "2023-12-14")
ON DUPLICATE KEY UPDATE
   `id` = values(`id`),
   `name` = values(`name`),
   `created_at` = values(`created_at`)
```

change to:

```sql
INSERT INTO `example` (`id`, `name`, `created_at`)
VALUES values (1, "test", "2023-12-14") AS new_record
ON DUPLICATE KEY UPDATE
   `id` = new_record.`id`,
   `name` = new_record.`name`,
   `created_at` = new_record.`created_at`
```

**Comment by driesvints** [comment]
Heya, if you could send in a PR that fixes this in a backwards compatible way with MySQL 5.7 we could consider it, thanks.
