### ISSUE TITLE
Http fake method does not overwrite if another fake method is used in the same test case.

### ISSUE THREAD

**Issue by StSarc** [laravel/framework#49398]
### Laravel Version

10.17.0

### PHP Version

8.2

### Description

I need to fake HTTP response of one URL multiple times in a single test flow. These are faked with different data each time.

Calling the fake method second time in the test case does not work. It gives the response set by the first fake method. It does not overwrite the response with the new fake data. The first fake call is always taking the precedence.

This is happening because https://github.com/laravel/framework/pull/47915 has added HttpFactory as a singleton.
It solves the issue raised at https://github.com/laravel/framework/issues/47738

Singleton is refreshed for each request, so it works fine for production. But this breaks in testing.

Similar issue being faced by other folks at: https://laracasts.com/discuss/channels/laravel/overwrite-fake-response-in-http-client?page=1&replyId=762080

The solution suggested in the above forum (swap) - it used to work until this PR got merged. That solution broke with this PR.

### Steps To Reproduce

```php
<?php

use Illuminate\Support\Facades\Http;

Route::get('/', function (){
  Http::fake([
    'https://laravel.com' => Http::response('OK', 200)
  ]);

  dump(Http::get('https://laravel.com')->body());

  Http::fake([
    'https://laravel.com' => Http::response('Internal Server Error', 500)
  ]);

  dump(Http::get('https://laravel.com')->body());
});
```

Laravel Playground: https://laravelplayground.com/#/snippets/0f8268bf-57d5-4709-ac54-e24965ec4c22

**Comment by StSarc** [comment]
Tagging @timacdonald since the PR was raised by him. If possible, can we revert the merge for now, please? Unable to upgrade to the latest Laravel version because of this.

**Comment by timacdonald** [comment]
Hi @StSarc,

I've created the following test which I've run in a fresh Laravel application using the latest version and also `10.16.1`, which was the version that change was tagged in.

The last assertion fails in both applications.

```php
<?php

namespace Tests\Feature;

use Illuminate\Http\Client\Factory;
use Illuminate\Support\Facades\Facade;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_http_factory(): void
    {
        // Make sure the HTTP factory starts as a singleton, as expected...
        // This assertion passes on the latest, but fails in version `10.16.1`
        $this->assertSame($this->app[Factory::class], $this->app[Factory::class]);

        // Rebind the Http factory so that it is no longer a singleton...
        $this->app->bind(Factory::class, fn () => new Factory($this->app['events']));
        $this->assertNotSame($this->app[Factory::class], $this->app[Factory::class]);
        // Clear any resolved instances, to make sure the HTTP facade gets a fresh instance...
        Facade::clearResolvedInstances();

        Http::fake([
            'https://laravel.com' => Http::response('OK', 200)
        ]);
        $body = Http::get('https://laravel.com')->body();
        $this->assertSame('OK', $body);

        Http::fake([
            'https://laravel.com' => Http::response('Internal Server Error', 500)
        ]);
        $body = Http::get('https://laravel.com')->body();
        // This assertion fails on the latest and `10.16.1`
        $this->assertSame('Internal Server Error', $body);
    }
}
```

This is because of the way the HTTP client stores "fakes". It builds up a list and checks them one-by-one, meaning this behaviour is expected (even if not ideal).

Instead, I would recommend taking a look at the docs on how to handle a sequence of HTTP requests to the same URL: https://laravel.com/docs/10.x/http-client#faking-specific-urls

```php
<?php

namespace Tests\Feature;

use Illuminate\Http\Client\Factory;
use Illuminate\Support\Facades\Facade;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_http_factory(): void
    {
        Http::fake([
            'https://laravel.com' => Http::sequence()
                ->push('OK', 200)
                ->push('Internal Server Error', 500),
        ]);

        $body = Http::get('https://laravel.com')->body();
        $this->assertSame('OK', $body);

        $body = Http::get('https://laravel.com')->body();
        $this->assertSame('Internal Server Error', $body);
    }
}
```

**Comment by StSarc** [comment]
Hey @timacdonald, thanks for the quick response! Replying to the comments below. Please do have a look.

> I've created the following test which I've run in a fresh Laravel application using the latest version and also 10.16.1, which was the version that change was tagged in.
It's tagged in 10.17.0 and not in 10.16.1. Please refer to https://github.com/laravel/framework/releases/tag/v10.17.0
It works in 10.16.1. This is the version that we are using currently. I am able to swap out the facade successfully here with a new Http facade. The moment I switch to 10.17.0, it breaks.

> The last assertion fails in both applications.
If we swap out the Facade instance with a fresh one, it doesn't fail in 10.16.1. But, it fails in 10.17.0
Please run the following code on 10.16.1 and 10.17.0 to check the same

```php
<?php

namespace Tests\Feature;

use Illuminate\Http\Client\Factory;
use Illuminate\Support\Facades\Facade;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_the_http_factory(): void
    {
        // Make sure the HTTP factory starts as a singleton, as expected...
        // This assertion passes on the latest, but fails in version `10.16.1`
        // ST_SARC: Commenting this out because it'll fail in 10.16.1 (rightly so).
        // $this->assertSame($this->app[Factory::class], $this->app[Factory::class]);

        // Rebind the Http factory so that it is no longer a singleton...
        // ST_SARC: Commenting these out as well because no singleton in 10.16.1 and hence not required
        // $this->app->bind(Factory::class, fn () => new Factory($this->app['events']));
        // $this->assertNotSame($this->app[Factory::class], $this->app[Factory::class]);
        // Clear any resolved instances, to make sure the HTTP facade gets a fresh instance...
        // Facade::clearResolvedInstances();
        // ST_SARC: Adding this to get and store a fresh instance of Http
        $freshHttp = $this->app[Factory::class];

        Http::fake([
            'https://laravel.com' => Http::response('OK', 200)
        ]);
        $body = Http::get('https://laravel.com')->body();
        $this->assertSame('OK', $body);

        // ST_SARC: Swapping the facade with the fresh instance created earlier
        Http::swap($freshHttp);

        Http::fake([
            'https://laravel.com' => Http::response('Internal Server Error', 500)
        ]);
        $body = Http::get('https://laravel.com')->body();
        // This assertion fails on the latest and `10.16.1`
        // ST_SARC: This assertion does not fail now.
        $this->assertSame('Internal Server Error', $body);
    }
}
```


> Instead, I would recommend taking a look at the docs on how to handle a sequence of HTTP requests to the same URL
I have tried this and it doesn't work for my use case because:
1. I have a base test case faking the HTTP request X with Data A.
2. I have multiple other test cases which extend this base test case. These test cases also fake the HTTP request X but with different Data (B, C, D).
The reason I cannot use sequences is because this faking first happens in a base test case (that other multiple test cases use in their own test flows) and then in the subsequent various test cases.



Now, I can use
```php
$this->app->bind(Factory::class, fn () => new Factory($this->app['events']));
```
to ensure it's not longer a singleton in test cases. But, ideally would want to avoid having a hack like this in test cases. Is there anything that you can suggest for this? Singletons are very messy to deal with usually. I am assuming this was also the reason why there are no other singletons registered at all in FoundationServiceProvider except for Vite.

**Comment by timacdonald** [comment]
@StSarc because we have features built on top of this class being a singleton, I don't think we will revert the change. The only thing I could recommend is, after resolving the class, you could tell the container to forget the instance.

```php
$freshHttp = $this->app[Factory::class];
$this->app->forgetInstance(Factory::class);
```

Alternatively, reworking how you handle the sequence faking in your testsuite is also an option. I can't comment on the best approach there as it will depend on your setup.

**Comment by StSarc** [comment]
What if we could just add the following in `Illuminate\Http\Client\Factory`?

```php
public function refreshRequestData()
{
        $this->stubCallbacks = collect();
}
```

I can raise a PR for this. Do you think it might be okay? We would then not have to use any workarounds / hacks. After the first request, we can just call the `refreshRequestData` if needed and it would work seamlessly.

**Comment by timacdonald** [comment]
You could certainly try a PR for this.

Perhaps `Http::flushFakes()` or something like that?

**Comment by StSarc** [comment]
Hey @timacdonald! I raised a PR to add the `flushFakes` method at https://github.com/laravel/framework/pull/49463

I have added a test case too. It fails without the `flushFakes` method.

**Comment by StSarc** [comment]
Hey @timacdonald ! This got closed. Do you think there's anything I can add in the description so that it gets approved?

**Comment by timacdonald** [comment]
If you wanted to try again I would recommend adding some code snippets to illustrate the issue.
