### ISSUE TITLE
No event is being dispatched for Redis::pipeline commands

### ISSUE THREAD

**Issue by cyppe** [laravel/framework#49395]
### Laravel Version

10.35.0

### PHP Version

8.2.13

### Database Driver & Version

Mysql 8.0.31

### Description

I noticed that there is no event fired for Redis when I use pipeline to call get. 

This has the effect in tools like clockwork och laravel telescope, that those commands are not visible in debugging purpose.

### Steps To Reproduce

Simple artisan command to show the problem. 

```
 public function handle()
    {
        Redis::enableEvents();

        $this->info("Listening to all events...");

        \Illuminate\Support\Facades\Event::listen('*', function ($eventName, $data) {
            $this->info("Event Triggered: " . $eventName);
        });
    
        // Example to log a message
        \Log::info('Test log message');

        
        Redis::get('testing..');


        Redis::pipeline(function ($pipe) {
            for ($i = 0; $i < 10; $i++) {
                // Generate a random key name
                $key = 'key_' . rand(1,100);
                $pipe->get($key);
            }
        });
        
    
        // Keep the command running
        while (true) {
            sleep(1);
        }   
    }
```

Output: 
```
Listening to all events...
Event Triggered: Illuminate\Log\Events\MessageLogged
Event Triggered: Illuminate\Redis\Events\CommandExecuted

```
As you can see, it catches event for Log and simple Redis::get(). But not for 10 iterations of pipeline redis get.

**Comment by cyppe** [comment]
I am not skilled enough to do a PR, otherwise I wouldn't mind trying to fix it.

**Comment by gkmk** [comment]
@cyppe the `pipeline()` function executes the callback with the actual Redis client (not the Laravel implementation/Facade). This is in a way similar to the mass update inside Eloquent where you cant expect events to be fired for each model.
I dont think this is an issue its just the way Pipelines and Transactions work, mass operations.

**Comment by driesvints** [comment]
Thanks @gkmk
