### ISSUE TITLE
Laravel does not drop system versioned tables when running `artisan migrate:fresh` command.

### ISSUE THREAD

**Issue by fnzr** [laravel/framework#49400]
### Laravel Version

10.37.3

### PHP Version

8.2.12

### Database Driver & Version

MariaDB 10.7

### Description

MariaDB supports [System Versioned Tables](https://mariadb.com/kb/en/system-versioned-tables/), allowing operations on temporal data.

If a migration-managed table is system versioned, the artisan command `migrate:fresh` command does not drop the table, and subsequently bringing the migrations up fails, since the migration tries to create a table that already exists.

The issue occurs because a system versioned table type is `SYSTEM VERSIONED`, and not `BASE TABLE`. When collecting the tables to be dropped, the system versioned table is not selected. Selecting `SYSTEM VERSIONED` tables fixes the issue.

I am willing to provide a PR fixing the problem, but it seems like it might be a risky change, I don't know. Please advise.

### Steps To Reproduce

1. Create base laravel project: `composer create-project laravel/laravel example-app`
2. Setup MariaDB 10.7+(ish?) and configure `.env` to connect to the database.
3. Run the default migrations with `php artisan migrate`
4. Create a new migration `php artisan make:migration add_users_table_versioning`
5. Execute the add versioning statement in the migration file:
```php
public function up(): void
    {
        \Illuminate\Support\Facades\DB::statement("ALTER TABLE users ADD SYSTEM VERSIONING;");
    }
```
6. Run the migration. It works.
7. Run `php artisan migrate:fresh`
The command will fail with the message:
```shell
...
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists
...
```

8. Navigate to [MysqlGrammar:86](https://github.com/laravel/framework/blob/03dbd3ab494419d9c72b80e1d16c1663238c9be4/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L86).
9. Edit the query to
```php
"from information_schema.tables where table_schema = %s and table_type = 'BASE TABLE' or table_type = 'SYSTEM VERSIONED' "
```

10. Execute `php artisan migrate:fresh`

The command runs successfully.

**Comment by monish-khatri** [comment]
@fnzr @crynobone ,
Hey,
Please let me know. If I can assist you.
