### ISSUE TITLE
Vite adds trailing slash at the end of each link tags

### ISSUE THREAD

**Issue by RejownAhmed** [laravel/framework#49422]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

Look at the below image, the ``link`` tag has a trailing slash which is totally unnecessary. 
Someone please remove it.

![image](https://github.com/laravel/framework/assets/91016843/860d10f5-875d-46c2-852c-dddd28861e48)

Thank you

### Steps To Reproduce

Create a Laravel Vue Application and run the server.

Check the html generated it has the trailing slash with all vite generated link tags.

See the image in the ``description``

Here is the pb link: https://github.com/laravel/framework/blob/0de8734170de48926e5a65c44e898b7078a0da0e/src/Illuminate/Foundation/Vite.php#L537

**Comment by timacdonald** [comment]
It's fine. It's just a self-closing tag. Although it might not be required for HTML5 doctypes, it's required for other doctypes and is not harmful in anyway.

**Comment by cotiga** [comment]
WHY DID YOU CLOSED THIS ISSUE?
Laravel generates HTML 5 NO!
