### ISSUE TITLE
 Migration: Creating primary key fails with mysql.

### ISSUE THREAD

**Issue by vish404** [laravel/framework#49440]
### Laravel Version

10.38.0

### PHP Version

8.1.25

### Database Driver & Version

8.0.25 - MySQL Community Server - GPL

### Description

Migration fails when trying to add primary keys (on existing table).  

#### Not working query on v10.38.0 
```mysql
alter table `course_person` drop index if exists `PRIMARY`, add primary key (`course_id`, `person_id`, `role`, `start`)
```

#### Working on v10.37.2 
```mysql
alter table `course_person` add primary key (`course_id`, `person_id`, `role`, `start`) 
```

### Steps To Reproduce

Create migration to add primary key to a table.
```php
public function up()
    {
        Schema::table('course_person', function (Blueprint $table) {
            $table->primary(['course_id','person_id','role','start']);
        });
    }
```

```bash
php artisan migrate
```

**Comment by aromka** [comment]
Similar issue but when running similar code in older migrations that worked fine before latest update - `SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead`

**Comment by crynobone** [comment]
Hi there,

This seems to have been caused via #49392 and reverted in 10.38.1

**Comment by vish404** [comment]
> Hi there,
> 
> This seems to have been caused via #49392 and reverted in 10.38.1
Thank you @crynobone
