### ISSUE TITLE
DB_PREFIX, has unexpected behaviour if the $table variable has dot.

### ISSUE THREAD

**Issue by JexPY** [laravel/framework#49450]
### Laravel Version

10.30.0

### PHP Version

8.1.26

### Description

In `model` I have:
```php
...
protected $connection = 'cars-auth';
protected $table = 'cars.users';
...
```
I wanted to add `DB_PREFIX=tests__` for testing, and I was expecting Laravel to return
`cars.tests__users` but it returns `tests__tests__cars.users`.
Works as expected If I will remove the `cars.` prefix from `$table`, returns - `tests__users`

### Steps To Reproduce

in `.env.testing`:
```env
DB_CONNECTION=mysql
DB_PREFIX=tests__
```
in `database.php`:
```php
'cars-auth' => [
    'driver' => 'mysql',
    ...
    'prefix' => env('DB_PREFIX', ''),
],
```

In `model`:
```php
...
protected $connection = 'cars-auth';
protected $table = 'cars.users';
...
```
call for example
```php
User::whereNotNull('id')->toRawSql();
```
returns:
```php
"select * from `tests__tests__cars`.`users` where `id` is not null"
```

**Comment by MaquinaTech** [comment]
Why are you trying to access a table indicating the database name?  You should specify only the name of the table since the database is specified in .env and not in the models

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
