### ISSUE TITLE
[10.x] Illuminate\Filesystem\join_paths(): Argument #2 must be of type string, null given

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/framework#49466]
### Laravel Version

10.38.1

### PHP Version

8.2.12

### Description

I recently ran `composer update`, which pulled in the latest Laravel version. My tests started reported errors that didn't previously exist, which indicates a breaking change.

After some investigation, I discovered that it was caused by #49433, which no longer accepts `null` as a valid value for functions like `app_path`, `base_path`, `public_path`, etc.

While substituting an empty string instead of `null` fixes the issue, I wouldn't expect to have to update my project like this unless I was making a major Laravel upgrade (e.g. L11).

### Steps To Reproduce

Within `php artisan tinker`:

```php
base_path(null); // Works on Laravel 10.38.0; throws exception on Laravel 10.38.1
```

**Comment by driesvints** [comment]
Hi @tylernathanreed. These methods never accepted a `null` value as you can see from their docblocks. You should always have passed a string here.

**Comment by tylernathanreed** [comment]
@driesvints,

Yet despite that, the code worked. The `null` case comes up often when we had use cases like `config('foo.bar')`. I would prefer to keep this working. Otherwise, I'll have to audit the project to change scenarios like this to be `config('foo.bar', '')`.

Honestly, this is just failing because of the new type that formally introduced. Granted, as you said, the docblock stated that only a `string` was accepted. The underlying code works with both `null` and `string`.

I've created PR #49467, which shows that only the type hint needs to be changed.

**Comment by venux92** [comment]
I had exactly the same issue. I had to revert to `10.38.0` for now as I could not build my project anymore without auditing it.

**Comment by driesvints** [comment]
We did a new patch release which should resolve this.

**Comment by venux92** [comment]
@driesvints Perfect.. I just updated to `10.38.2` and it's working. Thank for pointing out the `null` value as well. Will take some time one day to update them all. 👍🏽 

@tylernathanreed Thanks for the PR 🚀
