### ISSUE TITLE
New function join_paths second argument typed while callers are different

### ISSUE THREAD

**Issue by hocrattot** [laravel/framework#49462]
### Laravel Version

10.38.1

### PHP Version

8.1.24

### Description

The introduction of the new function join_paths() in /Illuminate/Filesystem/functions.php has a second argument $path that is typed as a String but the method that calls it in Application.php accepts $path as an optional argument that is an empty string by default.

In one of our projects, in a very specific case, a call to the helper storage_path with a null argument threw an exception while it was not the case in 10.38.0

Our case is very specific the fact that the method joinPaths() has $path as an option argument and passes it directly to the function join_paths may cause some bugs.

### Steps To Reproduce

Example

`echo storage_path(env('CONSTANT_THAT_IS_NOT_DEFINED'))`

**Comment by driesvints** [comment]
I'm sorry but the `storage_path` docblock clearly says you can only pass a string. Please add a check around this function. We don't consider this a breaking change, sorry.
