### ISSUE TITLE
Got warning on updating model with casts using raw query

### ISSUE THREAD

**Issue by yaelahan** [laravel/framework#49471]
### Laravel Version

10.38.1

### PHP Version

8.2.12

### Database Driver & Version

MySQL 8.0.27 for macos 13.0 on arm64 (DBngin)

### Description

I want to perform an update (increase and decrease) multiple columns at the same time but got the error `Object of class Illuminate\Database\Query\Expression could not be converted to int in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 754.` when update model using raw query 

The models:
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'product_id',
        'branch_id',
        'stock',
        'booked_stock',
    ];

    protected $casts = [
        'stock' => 'integer',
        'booked_stock' => 'integer',
    ];
}
```

### Steps To Reproduce

Open laravel tinker (`php artisan tinker`) and run this command
```
Stock::find(74)->update(['stock' => DB::raw('stock - 1'), 'booked_stock'=> DB::raw('booked_stock + 4')])
```

The return I got is looks like this
<img width="1909" alt="image" src="https://github.com/laravel/framework/assets/35204891/f9eeb0ad-b71f-4b3e-89d5-04937996633e">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
