### ISSUE TITLE
[Spart 5.0][Cashier 15.0] Call to undefined method Spark\SparkManager::ignoreMigrations()

### ISSUE THREAD

**Issue by gotexx1** [laravel/framework#49477]
### Laravel Version

10.38.2

### PHP Version

8.2

### Description

I have just updated laravel/cashier to version 15.0.0 and laravel/spark-stripe to version 5.0.0.
After following the migration guide to the new version, I get an error concerning the ignoreMigrations method, which is not defined.
This method is still referenced in the Spark-stripe documentation: https://spark.laravel.com/docs/spark-stripe/customization.html#migrations
My SparkServiceProvider.php
```php
use App\Models\Organization;
use Illuminate\Http\Request;
use Illuminate\Support\ServiceProvider;
use Laravel\Cashier\Cashier;
use Spark\Spark;

class SparkServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        Spark::ignoreMigrations();
    }
````
_This error concerns the Spark library but I can't find any way of sending a bug report to the Spark team._

### Steps To Reproduce

Upgrade laravel/cashier to version 15.0.0 and laravel/spark-stripe to version 5.0.0

**Comment by driesvints** [comment]
Hey @gotexx1. That part is defined here: https://github.com/laravel/cashier-stripe/blob/15.x/UPGRADE.md#publishing-migrations. But might need an explicit reference about the `ignoreMigrations. I'll add that and also update the spark docs.

You'll need to publish the migrations from now on as stated in the docs.

> This error concerns the Spark library but I can't find any way of sending a bug report to the Spark team.

There's a helpdesk widget on the spark website when you're logged in.
