### ISSUE TITLE
Cron task for Laravel schedule with sub-minute repeating skip a next minute running

### ISSUE THREAD

**Issue by alexsmirnovdotcom** [laravel/framework#49488]
### Laravel Version

10.4.1

### PHP Version

8.2

### Description

In last versions of laravel 10 was added [sub-minute intervals][1]. 
But i have strange behavior of runnig of cron task.
All works in Docker with docker-compose.
Cron works in separate from Laravel container.
I have no any errors in logs. 

Crontab file:
```cron
* * * * * php /var/www/api/artisan schedule:run >> /var/www/api/storage/logs/cron.log 2>&1
```

\App\Console\Kernel.php:
```php
<?php

namespace App\Console;

use App\Jobs\OneC\SyncChangesFrom1C;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Illuminate\Support\Facades\Log;

class Kernel extends ConsoleKernel
{
    /**
     * Register the commands for the application.
     */
    protected function commands(): void
    {
        $this->load(__DIR__ . '/Commands');

        require base_path('routes/console.php');
    }

    /**
     * Define the application's command schedule.
     */
    protected function schedule(Schedule $schedule): void
    {
        Log::debug('SCHEDULE RUN');
        $schedule->job(new SyncChangesFrom1C)->everyTenSeconds();
    }
}

```

**SyncChangesFrom1C** is a queued job. 
```handle``` method is empty.

Logs of Laravel:
```
[2023-12-25 08:22:01] local.DEBUG: SCHEDULE RUN
[2023-12-25 08:24:00] local.DEBUG: SCHEDULE RUN
[2023-12-25 08:26:00] local.DEBUG: SCHEDULE RUN
[2023-12-25 08:28:00] local.DEBUG: SCHEDULE RUN
```

Logs of Cron:
```
2023-12-25 08:26:00 Running [App\Jobs\OneC\SyncChangesFrom1C] .... 14ms DONE
2023-12-25 08:26:10 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 6ms DONE
2023-12-25 08:26:20 Running [App\Jobs\OneC\SyncChangesFrom1C] .... 10ms DONE
2023-12-25 08:26:30 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 5ms DONE
2023-12-25 08:26:41 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 3ms DONE
2023-12-25 08:26:51 Running [App\Jobs\OneC\SyncChangesFrom1C] .... 15ms DONE

2023-12-25 08:28:00 Running [App\Jobs\OneC\SyncChangesFrom1C] .... 39ms DONE
2023-12-25 08:28:10 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 3ms DONE
2023-12-25 08:28:21 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 2ms DONE
2023-12-25 08:28:31 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 2ms DONE
2023-12-25 08:28:41 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 5ms DONE
2023-12-25 08:28:51 Running [App\Jobs\OneC\SyncChangesFrom1C] ..... 2ms DONE
```

If i`m change to everyMinute:
```php
    /**
     * Define the application's command schedule.
     */
    protected function schedule(Schedule $schedule): void
    {
        Log::debug('SCHEDULE RUN');
        $schedule->job(new SyncChangesFrom1C)->everyMinute();
    }
```

It work perfect, and run every minute.

Why it skip a minute before new run if used sub-minutes interval?

  [1]: https://laravel.com/docs/10.x/scheduling#sub-minute-scheduled-tasks

### Steps To Reproduce

-

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by alexsmirnovdotcom** [comment]
Hi!

I make repository to reproduce bug in one command.
https://github.com/alexsmirnovdotcom/laravel-cron-bug

### How to Start
* Clone this repository.
* Navigate to the project directory.
* Run `docker-compose build && docker-compose down --remove-orphans && docker-compose up -d`.

### Where to Find the Issue
After launching the Docker containers, the Laravel application will start, and a test queued job will be executed in the schedule.

All logs are located in the standard Laravel logs folder: 
* `{path_to_project}/laravel/storage/logs/laravel.log` (for Laravel logs).
* `{path_to_project}/laravel/storage/logs/cron.log` (for Cron logs).

A portion of these logs is also available in the repository for easy access without the need to run the application.


---



# Important  note
In `\Illuminate\Console\Scheduling\ScheduleRunCommand::repeatEvents()`
if i change condition of while loop from 
```php
Date::now()->lte($this->startedAt->endOfMinute())
```
to
```php
Date::now()->lte($this->startedAt->endOfMinute()->subSeconds(20))
```
**It works perfect...**

I was unable to identify why cron skips running the `php artisan schedule:run` command. 
It is possible that the execution of the previous command does not have time to complete before trying to start a new one. 
But as far as I know, cron does not check this and must run the command even if the previous one has not completed yet...

**Comment by driesvints** [comment]
Hi there. I was not able to reproduce this on a local Laravel app with the latest version. Why this isn't working for you in your Docker setup, I do not know. But this unfortunately is beyond the support we can offer here. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel) 

<img width="840" alt="Screenshot 2024-01-01 at 14 40 22" src="https://github.com/laravel/framework/assets/594614/7097f5ac-df6e-49db-b706-a555502987d5">
<img width="770" alt="Screenshot 2024-01-01 at 14 40 31" src="https://github.com/laravel/framework/assets/594614/0c35583f-c10d-4209-a687-31aa569426f0">

**Comment by realjay007** [comment]
@alexsmirnovdotcom I also had a similar issue where sub-minute tasks sometime gets skipped. I solved it by running a task to schedule the jobs to be run in the future. In your case, it would be something like:

```php
$schedule->call(function () {
    $now = now()->floorMinute()->toImmutable();
    for ($i = 0; $i < 6; ++$i) {
        $dispatchTime = $now->addSeconds($i * 10);
        dispatch(new SyncChangesFrom1C)->delay($dispatchTime);
    }
})->everyMinute()->name('ScheduleSyncChangesFrom1CJobs');
```

Hope this helps.

**Comment by lavluda** [comment]
this bug is still reproducible in version 10.48.29

**Comment by tn710617** [comment]
I have the same issue in Laravel 11.36

**Comment by harshp-fabninjas** [comment]
I’m experiencing this issue on Laravel 12 as well.

My setup:

Running Laravel inside Docker

Initially, using the BusyBox cron daemon

Later switched to Supercronic

In both cases, the problem persists — scheduled tasks skip a minute unexpectedly.

This seems like a core scheduling issue, especially for sub-minute cron jobs, so it probably needs to be checked at the Laravel framework level.

**Comment by tn710617** [comment]
For anyone who might still be seeking for a solution. I solved this issue with `schedule:work`, and ran Supervisor to guard this process. For some unaccountable reason, the `schedule:work` process run sub-minute task without any problems.

**Comment by harshp-fabninjas** [comment]
Hello Everyone !

I have added the new issue [issue-link](https://github.com/laravel/framework/issues/57070) with all the necessary details.

Please review it and let me know if anyone knows anything in the context of it.
