### ISSUE TITLE
When using Eloquent and a orderBy('date') I'm getting a memory allocation error even for just 10 rows

### ISSUE THREAD

**Issue by bit-pax** [laravel/framework#49493]
### Laravel Version

10.35.0

### PHP Version

8.2.13

### Database Driver & Version

MySQL 8.0.32

### Description

I'm getting the following error when running a query that looks like the following:

DataSets::orderBy('release_date')->take(10)->get();

SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size

The release_date in MySQL is in YYYY-MM-DD format ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format) which may have something to do with the bug? Not sure. The data type for release date is 'date' (not 'timestamp'). Other Eloquent queries using orderBy() where the data type is not 'date' are working fine.

### Steps To Reproduce

I'm running everything through Laravel Sail in a Docker development environment setup. It's a pretty bare bones Laravel setup. Just added some data to the database and was playing around with it.

**Comment by MasterAdmin2** [comment]
> ### Laravel Version
> 10.35.0
> 
> ### PHP Version
> 8.2.13
> 
> ### Database Driver & Version
> MySQL 8.0.32
> 
> ### Description
> I'm getting the following error when running a query that looks like the following:
> 
> DataSets::orderBy('release_date')->take(10)->get();
> 
> SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size
> 
> The release_date in MySQL is in YYYY-MM-DD format ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format) which may have something to do with the bug? Not sure. The data type for release date is 'date' (not 'timestamp'). Other Eloquent queries using orderBy() where the data type is not 'date' are working fine.
> 
> ### Steps To Reproduce
> I'm running everything through Laravel Sail in a Docker development environment setup. It's a pretty bare bones Laravel setup. Just added some data to the database and was playing around with it.

**### Optimize the Query:**
Instead of relying on MySQL to sort the results, you can try optimizing the query by indexing the release_date column. This can significantly improve the sorting performance.

```php
DataSets::orderByRaw('DATE(release_date)')->take(10)->get();
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bit-pax** [comment]
I was assuming it's a problem with the Laravel library itself? All other sortBy operations are working fine. I have 128 GB of memory and only 2000 rows in my table.

**Comment by RezaODB** [comment]
I'm having the exact same issue. Any update or solution on this?
