### ISSUE TITLE
Unexpected Parameter Issue in Laravel Route Resource

### ISSUE THREAD

**Issue by hasanablak** [laravel/framework#49513]
### Laravel Version

10.10

### PHP Version

8.2.14

### Database Driver & Version

Mysql 8.0.33

### Description

I am defining a group of routes using `Route::resource` in a Laravel project. However, when I use the `php artisan route:list` command, I observe an unexpected parameter structure in the URLs created for the resources. Specifically, instead of having a variable name inside curly braces in the pattern like `admin/mail/{variable}`, I see `{}` as an empty parameter.

Routes File Example(web.php):
--------------------

    Route::prefix('admin/mail')->name('admin.mail.')
      ->group(function () {
        Route::resource('/', MailController::class);
        Route::resource('/future', MailController::class);
        Route::resource('/draft', DraftMailController::class);
     });

Output Screenshot(php artisan route:list):
------------------

![Route List Output](https://i.imgur.com/VYnWSAe.png)

Problem Details:
----------------

*   In the output of the `php artisan route:list` command, I can see that the unexpected parameter name is `{}`.
*   Laravel version: 10

Troubleshooting Steps:
----------------------

1.  I have checked the route definitions in the `routes/web.php` file and ensured they are configured correctly.
2.  I cleared the Laravel cache using the `php artisan route:clear` command.
3.  I reloaded classes and files using the `composer dump-autoload` command.
4.  I verified the naming and namespace of the controller classes.
5. I tried parameters method on route but this is doesn't work

But If I Use Like This
----------------------
This time it is working

    Route::prefix('admin/mail')->name('admin.mail.')
      ->group(function () {
        //Route::resource('/', MailController::class);
        #-------HERE-------#
        Route::get('/create', [MailController::class,"create"])->name('create');
        Route::post('/', [MailController::class,"store"])->name('store');
        Route::get('/{mail}', [MailController::class,"show"])->name('show');
        #-------END-------#
        Route::resource('/future', MailController::class);
        Route::resource('/draft', DraftMailController::class);
     });

![Route List Output](https://i.imgur.com/qNTI3Rr.png)

### Steps To Reproduce

1.  Create a new Laravel project using the following command:

    laravel new bug-report --github="--public"

3.  Navigate to the project directory with the command:

    cd bug-report

5.  Add the following route definitions to the `routes/web.php` file:

    
        Route::prefix('admin/mail')->name('admin.mail.')->group(function () {
            Route::resource('/', MailController::class);
            Route::resource('/future', MailController::class);
            Route::resource('/draft', DraftMailController::class);
        });
        

6.  Run the `php artisan route:list` command to list the routes and share the output.
7.  Open one of the generated routes in a browser by performing a request through the URL. For example, visit a URL like `/admin/mail/1`.

**Comment by cosmastech** [comment]
Does it not work if you use `Route::resource('', MainController::class);`?

**Comment by hasanablak** [comment]
no sir, it shows the same behavior

When I visit this url admin/mail/5 this time it gives 404 not found error but I have a mail with id 5.
When I type dd in the show method on the controller and visit the url, it still gives a 404 not found error, it does not show the dd screen.

<img width="1208" alt="Untitled 2" src="https://github.com/laravel/framework/assets/20007699/3b86f017-c274-4adb-8854-a012da9aaf8c">
<img width="1435" alt="Untitled 6" src="https://github.com/laravel/framework/assets/20007699/9a9e0b77-f2a5-473b-8eae-80a3e66ff8a5">

**Comment by hasanablak** [comment]
Ok guys, I found a solution, but now I'm absolutely sure that this is a bug.

As you know, Laravel has a "parameters" method for the "Route class", for example we can write it like this;

		Route::resource('/', MailController::class)->parameters(["mail" => "hasan"]);
		
but for my problem when i write like this it doesn't work. 
I was wondering, how would it behave if I left it blank instead of "mail"?

and this time it is working

		Route::resource('/', MailController::class)->parameters(["" => "hasan"]);


<img width="1435" alt="Untitled 8" src="https://github.com/laravel/framework/assets/20007699/a8775c77-92aa-40fa-b0c5-97a43a00896c">

**Comment by driesvints** [comment]
Thanks. Please provide an actual repo with the commands you provided instead of asking us to create one.

**Comment by unseen703** [comment]
I don't find any anomaly here. Isn't it default behavior of the recourse to create the route according to the recourse name provided?
in this case you have provided empty string so it appears as blank parenthesis.

```
  Route::resource('/', MailController::class);
```
while here you overridden that empty string with "mail";
```
  Route::resource('/', MailController::class)->parameters(""=>"mail");
```

but I didn't see the problem here, can't we just create new resourse like this
```
Route::prefix('admin')->name('admin.mail.')->group(function () {
    Route::resource('mail', MailController::class)->parameters(["mail"=>"mail"]);
});
Route::prefix('admin/mail')->name('admin.mail.')->group(function () {
  
    Route::resource('future', MailController::class);
    Route::resource('draft', DraftMailController::class);
});
```

Also I am kind of new to this field and open-source, so please enlighten me if there are any issue with the above approach.

**Comment by hasanablak** [comment]
@unseen703 yes, you are right.
I just thought it was supposed to work like this I guess
