### ISSUE TITLE
Laravel sail with Octane (Swoole) and Breeze, and when I log out an error occurs.

### ISSUE THREAD

**Issue by DuilioFanton** [laravel/framework#49516]
### Laravel Version

10.39.0

### PHP Version

8.3.1

### Database Driver & Version

PostgreSQL 15

### Description

I'm using Laravel sail with Octane and Breeze, and when I log out an error occurs.

Illuminate\ Contracts\ Container\ BindingResolutionException
PHP 8.3.1
10.39.0
Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable while building [Illuminate\Routing\ViewController].

Error: https://flareapp.io/share/w5BRn2d5

### Steps To Reproduce

Error
Share with Flare APP: https://flareapp.io/share/w5BRn2d5

The solution I found (but I'm not sure if this has any negative impact):

LINK: https://github.com/livewire/livewire/discussions/6942

File: vendor/livewire/livewire/src/Mechanisms/PersistentMiddleware/PersistentMiddleware.php 

```php
    protected function getApplicablePersistentMiddleware($request)
    {
        $route = $this->getRouteFromRequest($request);

        if (! $route) return [];

        // ADD THIS:
        $route->setContainer(app());

        $middleware = app('router')->gatherRouteMiddleware($route);

        return $this->filterMiddlewareByPersistentMiddleware($middleware);
    }
```

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
