### ISSUE TITLE
TypeError: Illuminate\Database\QueryException::__construct(): Argument #3 ($bindings) must be of type array, ErrorException given

### ISSUE THREAD

**Issue by tosinibrahim96** [laravel/framework#49580]
### Laravel Version

10.39.0

### PHP Version

8.1.27

### Database Driver & Version

MySQL 8.0.35

### Description

We made an update from Laravel 9.X to Laravel 10 yesterday, but we noticed that some queries  that worked perfectly before the upgrade returns these errors

**First**

`TypeError: Illuminate\Database\QueryException::__construct(): Argument #3 ($bindings) must be of type array, ErrorException given, called in /home/forge/api.edenlife.ng/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 761 and defined in /home/forge/api.edenlife.ng/vendor/laravel/framework/src/Illuminate/Database/QueryException.php:41`

**Second**

`TypeError: Illuminate\Database\QueryException::__construct(): Argument #3 ($bindings) must be of type array, PDOException given, called in /home/forge/api.edenlife.ng/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 761 and defined in /home/forge/api.edenlife.ng/vendor/laravel/framework/src/Illuminate/Database/QueryException.php:41`

The QueryException in our case aren't thrown manually, so there was no need to take [this](https://laravel.com/docs/10.x/upgrade#query-exception-constructor) step  described in the upgrade guide.

Is there any extra change required that is not specified in the guide to make sure the code works perfectly like before?

### Steps To Reproduce

- Update an existing Laravel 9 codebase to Laravel 10 
- Dispatch a job to a execute a database query. 
- Here is what the query throwing an error looks like

```
User::where('id', $id)
            ->with(
                'subscription',
                'feedback'
            )->first();
```

**Comment by unicodeveloper** [comment]
I'm experiencing this as well. This throws an error when queries are executed from within jobs. I have searched everywhere for a possible solution but to no avail. This was working well before the upgrade.

**Comment by driesvints** [comment]
Your example query is incorrect. You can't use `with` with comma separated values like that. It needs to be an array

Also, your statement should start by `with` rather than `where`. Try

```php
User::with([
    'subscription',
    'feedback',
])->where('id', $id)->first();
```

**Comment by unicodeveloper** [comment]
According to the [documentation](https://laravel.com/docs/10.x/eloquent-relationships#eager-loading-specific-columns), there is an example here without the array.

```
$books = Book::with('author:id,name,book_id')->get();
```

And in the framework code, I can see it allows either. Are you saying Laravel 10 doesn't allow it and must be strictly an array using `with` for comma separated values? @driesvints

**Comment by driesvints** [comment]
@unicodeveloper that's a single string, not the same as the example above with multiple arguments.
