### ISSUE TITLE
Running feature tests in a separate process in PHP 8.3 fails

### ISSUE THREAD

**Issue by PHLAK** [laravel/framework#49593]
### Laravel Version

10.39.0

### PHP Version

8.3.1

### Description

Running a _feature_ test with the [`RunInSeparateProcess`](https://docs.phpunit.de/en/10.5/attributes.html#runinseparateprocess) attribute (or [`@runInSeparateProcess`](https://docs.phpunit.de/en/10.5/annotations.html#runinseparateprocess) annotation) on PHP 8.3 fails immediately.

### Steps To Reproduce

Create a _feature_ test that uses the [`RunInSeparateProcess`](https://docs.phpunit.de/en/10.5/attributes.html#runinseparateprocess) attribute (or [`@runInSeparateProcess`](https://docs.phpunit.de/en/10.5/annotations.html#runinseparateprocess) annotation).

```php
namespace Tests\Feature;

use PHPUnit\Framework\Attributes\RunInSeparateProcess;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    #[Test, RunInSeparateProcess]
    public function it_can_run_in_a_separate_process(): void
    {
        $this->assertTrue(true);
    }
}
```

Run the test.

```
$ artisan test tests/Feature/ExampleTest.php

   FAIL  Tests\Feature\ExampleTest
  ⨯ it can run in a separate process                                                                                                     3199.78s  
  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\Feature\ExampleTest > it can run in a separate process                                                     AssertionFailedError   
  Test was run in child process and ended unexpectedly

```

**NOTE:** The above does not fail on PHP 8.2 and the following _unit_ test _does not_ fail on PHP 8.3.

```php
namespace Tests\Unit;

use PHPUnit\Framework\Attributes\RunInSeparateProcess;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    #[Test, RunInSeparateProcess]
    public function it_can_run_in_a_separate_process(): void
    {
        $this->assertTrue(true);
    }
}
```

**Comment by SimplyCorey** [comment]
I'm having the same issues when moving my projects over to PHP 8.3.  

https://github.com/laravel/framework/issues/49237 seems like a duplicate but I think this should be revisited as it backwards breaking.

**Comment by websitevirtuoso** [comment]
I have the same problem. Temporary I had to disable flag 
processIsolation="false"
in phpunit config

**Comment by crynobone** [comment]
Laravel Framework never officially supports using this flag as mentioned in the other issue and instead suggest using `php artisan test --parallel` option.

**Comment by websitevirtuoso** [comment]
Then why does it work with php8.2? I never use flag --parallel

**Comment by crynobone** [comment]
> Then why does it work with php8.2?

When we say "it's not officially supported" that's mean that whether it is working or not it not something that we provide or guarantee support for, and any breaking to what we don't officially support are not consider as breaking changes.

**Comment by SimplyCorey** [comment]
Is this lack of support listed anywhere?  This feature has been working for years within Laravel and a recent update broke it.  Some repos, including mine have thousands of tests that will need rethinking which the `--parallel` flag doesn't provide equity for.

**Comment by arclw** [comment]
In the same boat!! Any solutions ?
