### ISSUE TITLE
Model::shouldBeStrict property doesn't work with updateOrCreate and other related methods

### ISSUE THREAD

**Issue by websitevirtuoso** [laravel/framework#49597]
### Laravel Version

10.39.0

### PHP Version

8.3.0

### Database Driver & Version

PGSQL v16

### Description

Code to upsert record.
It works fine without option preventSilentlyDiscardingAttributes
```
public function resolve(mixed $root, array $args) :Subscriber
    {
        return Subscriber::updateOrCreate(
            [
                'id' => Arr::get($args, 'id')
            ],
            [
                'first_name'       => Arr::get($args, 'first_name'),
                'last_name'        => Arr::get($args, 'last_name'),
                'email'            => $args['email'],
                'rejection_status' => Arr::get($args, 'rejection_status'),
                'rejection_note'   => Arr::get($args, 'rejection_note'),
            ]
        );
    }
```

My Subscriber class has code
```
protected $table = 'subscribers';
    protected $fillable = ['first_name', 'last_name', 'email', 'rejection_status', 'rejection_note'];
    protected $guarded = ['id'];
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
```

Getting error
Add fillable property [id] to allow mass assignment on [App\Modules\Subscription\Models\Subscriber].
I know that method updateOrCreate inside using method "fill" but I still think that it should work

### Steps To Reproduce

Activate Model::shouldBeStrict to "true" and try to use code
```
public function resolve(mixed $root, array $args) :Subscriber
    {
        return Subscriber::updateOrCreate(
            [
                'id' => Arr::get($args, 'id')
            ],
            [
                'first_name'       => Arr::get($args, 'first_name'),
                'last_name'        => Arr::get($args, 'last_name'),
                'email'            => $args['email'],
                'rejection_status' => Arr::get($args, 'rejection_status'),
                'rejection_note'   => Arr::get($args, 'rejection_note'),
            ]
        );
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
