### ISSUE TITLE
validation rule "in" accepting value with plus sign in front

### ISSUE THREAD

**Issue by martinhschei** [laravel/framework#49602]
### Laravel Version

10.10

### PHP Version

8.2.12

### Description

One of the endpoints in my API is storing a phone number with country code and i´m validating the country code against an array of numbers (none with +)

example:

```
'country_code' => ['required', Rule::in([47,48,49])],
```

this rule will accept the values: "+47", "+48" and "+49" and also without the plus sign but will fail for all other numbers both with and without plus sign.

to me this seems like a bug - or am i using the rule wrong?

### Steps To Reproduce

create a endpoint that accepts a json payload with a property that takes a number. validate that number against a fixed list of number none of which contains a leading plus sign, and post with postman to that route one of the valid numbers with a leading plus sign.

**Comment by sonja-turo** [comment]
I just ran some experiments against a series of different inputs, and I think this is a bug

Basic validator make command and output of result
`$v = Validator::make($data, $rules); dd($v->passes());`

Rule combinations tested
`['x' => 47], ['x' => Rule::in([47,48,49])]; // passes`
`['x' => 46], ['x' => Rule::in([47,48,49])]; // fails`
`['x' => '47'], ['x' => Rule::in([47,48,49])]; // passes`
`['x' => '47'], ['x' => Rule::in(['47','48','49'])]; // passes`
`['x' => 47], ['x' => Rule::in(['47','48','49'])]; // passes`
`['x' => +47], ['x' => Rule::in([47,48,49])]; // passes`
`['x' => '+47'], ['x' => Rule::in([47,48,49])]; // passes (I think it should fail)`
`['x' => '++47'], ['x' => Rule::in([47,48,49])]; // fails`
`['x' => '+47'], ['x' => Rule::in(['47','48','49'])]; // passes (I think it should fail)`
`['x' => +47], ['x' => Rule::in(['47','48','49'])]; // passes`

+47 is simply "positive 47" (as opposed to -47 being "negative 47"). So matching this when passed in as a integer kind of makes sense. However '+47' is technically a string, and when doing the string comparison it should fail.

I guess this comes down to how strings and numeric strings are treated in both the rules and the incoming request. Unfortunately, I can't see a way where the framework can understand the context of "positive 47" vs "+47" as a string.

**Comment by driesvints** [comment]
Hi there. +47 is a number in PHP and it loosely matches 47 with the "in" rule. We consider this expected behaviour. If anything is unclear we'd appreciate a PR to the docs, thanks.
