### ISSUE TITLE
Works using Notification::fake, but fails without it

### ISSUE THREAD

**Issue by a4smanjorg5** [laravel/framework#49616]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

No keyword:[`clone`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Notifications/NotificationSender.php#L94C21-L94C26) on [\Illuminate\Support\Testing\Fakes\NotificationFake sendNow](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L316)

Even though in [\Illuminate\Notifications\NotificationSender sendNow](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Notifications/NotificationSender.php#L90-L111) is there

### Steps To Reproduce

So I think it would be better if the keyword:`clone` is also in NotificationFake or removed from NotificationSender

**Comment by driesvints** [comment]
I don't see an immediate issue here sorry
