### ISSUE TITLE
created_at and updated_at timestamps timezone

### ISSUE THREAD

**Issue by Noraddeen** [laravel/framework#49613]
### Laravel Version

10.39

### PHP Version

8.2

### Database Driver & Version

postgresql 16

### Description

I've encountered a challenge related to timezones and serialization in Laravel Eloquent models. I've configured the timezone in config/app.php to 'Asia/Baghdad,' and the PostgreSQL database also uses the same timezone. When inserting and retrieving values from a timestamp column, everything works as expected.

However, I've noticed an issue specifically with the created_at and updated_at timestamps. While the values are stored correctly in the database according to the configured timezone, serialization to JSON or array format for frontend responses converts the datetime to UTC.

I've found two solutions that involve manually handling timezone conversion in each model:
first: 
```
protected function getCreatedAtAttribute($value)
	{
		return   Carbon::parse($value)->tz(config('app.timezone'))->toDateTimeString();
	}
	protected function getUpdatedAtAttribute($value)
	{
		return   Carbon::parse($value)->tz(config('app.timezone'))->toDateTimeString(); 
	}
```
second:
 ```
 protected function serializeDate(DateTimeInterface $date)
	  {
		  return $date->format('Y-m-d H:i:s');
	  }
```
My concern is why these solutions are necessary in the first place. Shouldn't Laravel automatically use the application-wide timezone specified in config/app.php for serialization across all models? It feels like there might be an improvement or clarification needed in Laravel's default behavior regarding this aspect.

If anyone has insights or suggestions on a more streamlined approach or if this is an expected behavior, I would appreciate the community's input.

### Steps To Reproduce

...

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ellermister** [comment]
In 2025, this problem still exists, which I think is very unreasonable.

**Comment by browner12** [comment]
The problem has been solved for years. Just use UTC

**Comment by ellermister** [comment]
> The problem has been solved for years. Just use UTC

But I'm not in UTC time zone 😒
