### ISSUE TITLE
orderBy returns Eloquent/Builder despite the return type being defined as Query/Builder

### ISSUE THREAD

**Issue by mubashirzamir** [laravel/framework#49646]
### Laravel Version

10.30.1

### PHP Version

8.2.10

### Description

For the purpose of demonstrating the issue, I created the following command:

![image](https://github.com/laravel/framework/assets/79789067/3523e136-3bee-4d96-8a24-c032f9be5b7d)

As per [Laravel's API documentation](https://laravel.com/api/10.x/Illuminate/Database/Query/Builder.html#method_orderBy) for the `orderBy` method, it is supposed to return `Illuminate\Database\Query\Builder`

However, on running this command, I get the following error:

`Return value must be of type Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder returned` 

### Steps To Reproduce

Steps have been mentioned in the description, attaching the command file.

1. Place the command file `watch.txt` in `App/Console/Commands` and change the name to `watch.php`
2. Replace the `Briefing` model with any model that is present in your project 
3. Run `php artisan watch`

Downloads: [watch.txt](https://github.com/laravel/framework/files/13898182/watch.txt)

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by mubashirzamir** [comment]
Investigated the issue and turns out the issue was related to the laravel-ide-helper package and not laravel. 

see: https://github.com/barryvdh/laravel-ide-helper/issues/1128 

Adding this comment in case anyone else stumbles into this issue in the future.
