### ISSUE TITLE
[PHP8.3] Requests to non-existing resources or routes hang up PHP if Xdebug is loaded

### ISSUE THREAD

**Issue by madman-81** [laravel/framework#49663]
### Laravel Version

10.3.0

### PHP Version

8.3.1

### Database Driver & Version

n/a

### Description

I'm not sure if this is a Laravel or Xdebug issue, but since I'm only able to recreate it with a Laravel project, I thought I start here.

Recently I upgraded my development PC to PHP8.3 and started testing my projects when I noticed high CPU loads of Apache. After some testing I found out that it was caused by some images that are not on my development PC and normally cause a 404 response. After a bit more testing I found out that if I would disable the Xdebug module in PHP, all was working fine. 

Since I can reproduce the issue in a clean Laravel project, I thought I start here to see if this is an issue of Laravel or perhaps Xdebug.

I'm using Windows 10, PHP8.3.1, Xdebug 3.3.1 and a clean Laravel 10.3.2 project where I change '/' of the default route in web.php to 'demo':

```php
Route::get('demo', function () {
    return view('welcome');
});
```

If you access the project via a browser, you'll get a 404 response. If you long press the F5 button, sending many requests, it results in a hanging Apache/PHP process.

Note: this doesn't happen with PHP8.2 or when the Xdebug extension isn't loaded
Note2: it doesn't matter if Xdebug is triggerd or not via either the browser or the xdebug.start_with_request setting, just loading the extension is enough 

Anyone else here who can reproduce this? Is this a Laravel or a Xdebug issue? 

### Steps To Reproduce

* Create a new Laravel project
* Access the project via the browser (the Welcome page should be displayed)
* Change the '/' of the default route to 'demo' (to cause a 404)
* Refresh in the browser: a 404 message should be shown
* Long press F5 (send many requests to the server): high CPU load of Apache indicating a hanging PHP process

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
