### ISSUE TITLE
Router does not handle calls to /index.php correctly

### ISSUE THREAD

**Issue by Jimbolino** [laravel/framework#49708]
### Laravel Version

10.40.0

### PHP Version

8.3

### Description

The laravel router does not handle calls to `/index.php` correctly. Also calls to `/index.phpsomething` are matched with a route named `something`. It seems like there is a special case for the `/index.php` calls, that results in it resolving to `/`

### Steps To Reproduce

web.php:
```
Route::get('/index.php', function () {
    return 'this is the /index.php route. REQUEST_URI:'.$_SERVER['REQUEST_URI'];
});

Route::get('/', function () {
    return 'this is the / route. REQUEST_URI:'.$_SERVER['REQUEST_URI'];
});

Route::get('{any?}', function ($any = null) {
    return 'this is the catch all route. REQUEST_URI:'.$_SERVER['REQUEST_URI'];
})->where('any', '.*');
```

| url | result |
| ----------- | ----------- |
| http://localhost/index.php | this is the / route. REQUEST_URI:/index.php |
| http://localhost/ | this is the / route. REQUEST_URI:/ |
| http://localhost/anything | this is the catch all route. REQUEST_URI:/anything |
| http://localhost/index.phpsomething | 404 NOT FOUND (src/Illuminate/Foundation/Exceptions/views/minimal.blade.php) |

I've tried to edit the `.htaccess` file, changed the `RewriteRule` to `FallbackResource`, but this did not change anything.

The behaviour is also the same in dev-master

**Comment by Jimbolino** [comment]
this is an actual bug....

**Comment by rojtjo** [comment]
As far as I know this depends on how your web server is configured. What are you trying to accomplish?

**Comment by Jimbolino** [comment]
Trying to make sure that calls to /index.php are routed to my 404 catch all route, but it seems this maybe a bug in the underlying symfony request code.
For some reason they do a string replace on `REQUEST_URI` with `SCRIPT_NAME`, and laravel consumes the result via `getPathInfo()`

**Comment by Jimbolino** [comment]
for future reference, i found a workaround:

```
unset($_SERVER['SCRIPT_FILENAME']);
```
before symfony request is created in index.php

This bypasses the [weird behaviour](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpFoundation/Request.php#L1724) of [preparePathInfo()](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpFoundation/Request.php#L1822C24-L1822C24) that removes the filename from that prevents the router from matching correctly
