### ISSUE TITLE
Validator.php validated() method is not throwing exception when the field under validation thats fails is an array of values

### ISSUE THREAD

**Issue by stamosargiris** [laravel/framework#49704]
### Laravel Version

10.33.0

### PHP Version

8.3.1

### Database Driver & Version

irrelevant

### Description

In a Form Request Validation file we have a rule that checks an array attribute and the values if they exist in a database:
```
public function rules(): array
{
  return [
      'arrayAttribute' => [
          'sometimes',
          'nullable',
          'array',
          new ArrayAttributeExists // this is a custom validation rule
      ],
      'stringAttribute' => [
        'required',
        'string',
        'regex:/^[-\w ]*$/',
        'min:1',
        'max:255'
      ]
  ];
}
```
When one or all of the values of the array attribute do not exist then the rule `new ArrayAttributeExists` should fail when we call requests `validated()` method but it does not.

### Steps To Reproduce

As in the description of the issue our Form Request Validation file is something like the following:
```
public function rules(): array
{
  return [
      'arrayAttribute' => [
          'sometimes',
          'nullable',
          'array',
          new ArrayAttributeExists // this is a custom validation rule
      ],
      'stringAttribute' => [
        'required',
        'string',
        'regex:/^[-\w ]*$/',
        'min:1',
        'max:255'
      ]
  ];
}
```
The provided payload is like the following:
```
{
  "stringAttribute":"stringAttributeTestValue",
  "arrayAttribute": [
    "notExistentArrayAttributeTestValue"
  ]
}
```

Now when an api call (irrelevant if its a POST/PUT/PATCH) is made and the only thing that fails is, lets say, the "new ArrayAttributeExists" custom validation rule, then vendor/laravel/framework/src/Illuminate/Validation/Validator.php validated() function is not throwing an exception as it should, catching the failing validation and this is because Validator.php invalid() function does not return the particular failed attribute.

This is due to the following line inside Validator.php invalid() function:
```
$failed = Arr::only(Arr::dot($invalid), array_keys($this->failed()));
```
So `Arr::dot($invalid)` gives:
```
[
  "arrayAttribute.0" => "notExistentArrayAttributeTestValue"
]
```
and `array_keys($this->failed())` gives:
```
[
  "arrayAttribute"
]
```
which means that invalid() method `Arr::only` usage will not return the particular error case thus the `validate()` will not throw an exception.

Instead of using `Arr::dot($invalid)` why not using the actual `$invalid` array as is?

thank you in advance.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
