### ISSUE TITLE
array_key_exists deprecated since PHP 7.4, and removed in PHP8.0

### ISSUE THREAD

**Issue by jduan00** [laravel/framework#49711]
### Laravel Version

10.0

### PHP Version

8.3.1

### Database Driver & Version

mariadb 10.11

### Description

Hi there,

The official Laravel supports PHP8.x. However, I found out that `array_key_exists` is deprecated, but it is still being used in Laravel extensively. 

https://www.php.net/manual/en/function.array-key-exists.php

```
...
./vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:            if (array_key_exists('compression', $config)) {
./vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:            if (array_key_exists('compression_level', $config)) {
./vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:            if (array_key_exists('serializer', $options)) {
./vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:            if (array_key_exists('compression', $options)) {
./vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:            if (array_key_exists('compression_level', $options)) {
./vendor/laravel/ui/src/Presets/Preset.php:            array_key_exists($configurationKey, $packages) ? $packages[$configurationKey] : [],
./vendor/laravel/sail/src/Console/Concerns/InteractsWithDockerComposeServices.php:        if (! array_key_exists('laravel.test', $compose['services'])) {
...
```
Is there a plan to follow PHP's suggestion to change the code base? Thanks!

1. For backward compatibility reasons, array_key_exists() will also return true if key is a property defined within an object given as array. This behaviour is deprecated as of PHP 7.4.0, and removed as of PHP 8.0.0.
2. To check whether a property exists in an object, [property_exists()](https://www.php.net/manual/en/function.property-exists.php) should be used.

### Steps To Reproduce

```
$ cd laravel_app/src
$ find . -name '*.php' | xargs grep array_key_exists
```

**Comment by rojtjo** [comment]
It's only deprecated when the second argument is an object. All the example you mention use an array as the second argument.

**Comment by timacdonald** [comment]
As @rojtjo mentioned, the function isn't deprecated.

If there are specific instances were we are using it in a deprecated manner it would be good to know.

Will close this as there does not seem to be an issue.

**Comment by jduan00** [comment]
Thanks @rojtjo @timacdonald for the prompt response. I stand corrected regarding the specific behavior that is being deprecated.
