### ISSUE TITLE
Validating numeric values when string validation is applied.

### ISSUE THREAD

**Issue by akshit-arora** [laravel/framework#49716]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

If a validation is applied as `string` and a numeric value is passed, the validation fails.

However this is managed in the case of `integer` validation. The validation passes even if the integer is passed as a string.

the validation must be consistent for both `string` and `integer` validation

### Steps To Reproduce

```php
use Illuminate\Support\Facades\Validator;

// When an integer is passed and validation is for string
$validator = Validator::make(['value' => 900], ['value' => "required|string"]);

$validator->fails() //returns true... 🤔
```

**Comment by driesvints** [comment]
This is the correct behaviour.
