### ISSUE TITLE
Using JsonResource with whenAggregated() and an aliassed aggregrate

### ISSUE THREAD

**Issue by Ken-vdE** [laravel/framework#49747]
### Laravel Version

10

### PHP Version

8.36

### Description

When using withSum with an alias on an eloquent query builder:
```php
->withSum('stocks as total_quantity', 'quantity')
```
You'd expect the whenAggregated on a JsonResource to respect the alias:
```php
$this->whenAggregated('stocks as total_quantity', 'quantity', 'sum'),
```
That's not the case, it tries to retrieve a wrong column: `stocks_as_total_quantity_sum_quantity` when it should try the column `total_quantity`.

### Steps To Reproduce

See description

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
