### ISSUE TITLE
Access subfolder

### ISSUE THREAD

**Issue by alissonrodrigo** [laravel/framework#49740]
### Laravel Version

10.4

### PHP Version

8.1

### Database Driver & Version

Mysql 8

### Description

I need to release a subfolder within the public (public/api) where there is another system (index.php) but Laravel does not allow access, giving a 405 error. How can I release access without going through Laravel? grateful

### Steps To Reproduce

release subfolder within public for free access without going through laravel routes

**Comment by crynobone** [comment]
Hi there,

Such usage is not supported by Laravel: https://laravel.com/docs/10.x/installation#directory-configuration
