### ISSUE TITLE
Postgres: Undefined function: 7 ERROR:  operator does not exist: json = unknown

### ISSUE THREAD

**Issue by foremtehan** [laravel/framework#49763]
### Laravel Version

9

### PHP Version

8.1

### Database Driver & Version

Postgres 15

### Description

When using `whereJsonContains` with `updateOrCreate`, the following exception is thrown:

```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: json = unknown

LINE 1: ...ull and ("tags")::jsonb @> $2 and ("tags" = $3) 
```

### Steps To Reproduce

```php
$this->user->posts()->whereJsonContains('tags', $tag)->updateOrCreate($data);
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
