### ISSUE TITLE
$deleteWhenMissingModels on Jobs is ignored when Models use SoftDeletes trait

### ISSUE THREAD

**Issue by olml89** [laravel/framework#49788]
### Laravel Version

9.45

### PHP Version

8.2

### Description

When using the SoftDeletes trait, deleted models are ignored in Jobs which are using the $deleteWhenMissingModels = true feature, and the Jobs are still processed when they should be discarded.

The reason is that SoftDeletes trait is only taken into account when using Eloquent, but Jobs use the DB query builder to retrieve the serialized Models from the database, without checking the possible deleted_at column:

https://github.com/laravel/framework/blob/d7616a176afc641e9693266920cb11e84c352241/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php#L119

https://github.com/laravel/framework/blob/d7616a176afc641e9693266920cb11e84c352241/src/Illuminate/Database/Eloquent/Model.php#L1555

### Possible fix

One possible way to solve it is to overwrite the newQueryForRestoration from Models on the SoftDeletes trait, making it check that the deleted_at column is null:

```php
    /**
     * Get a new query to restore one or more models by their queueable IDs.
     *
     * @param  array|int  $ids
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function newQueryForRestoration($ids): Builder
    {
        return $this
            ->newQueryWithoutScopes()
            ->whereKey($ids)
            ->whereNull($this->getDeletedAtColumn());
    }
```

### Steps To Reproduce

```php
    class ExampleModel extends \Illuminate\Database\Eloquent\Model
    {
    }

    final readonly class Job implements \Illuminate\Contracts\Queue\ShouldQueue
    {
        public bool $deleteWhenMissingModels = true;
    
        public function __construct(
            public ExampleModel $exampleModel,
        ) {
        }
    }
```

If we create a Job injecting an ExampleModel, and then we delete the model and dispatch job:

```php
    $model = new ExampleModel;
    $job = new Job($exampleModel);

    $model->delete();
    
    dispatch($job);
```

The job should be automatically discarded, but it is processed anyway.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by olml89** [comment]
I'll try to reproduce it on the latest version.
