### ISSUE TITLE
Unable to clear stale queue locks

### ISSUE THREAD

**Issue by ppisecky** [laravel/framework#49804]
### Laravel Version

9.2

### PHP Version

8.1.4

### Description

When using the redis cache driver and the unique job functionality a stale lock cannot get cleared by either `queue:clear` or `cache:clear`. The only way I was able to clear it was using `redis-cli` directly. There also isn't really a way to tell that a lock is stuck unless you notice something stopped running for a while. 

Since this happened to me multiple times I think adding `uniqueFor` attribute to jobs or maybe switching cache driver for the lock might help but I'm not sure.

### Steps To Reproduce

I am not exactly sure how the lock gets stuck / doesn't clear but I imagine it happens when you stop a job execution while it's being processed. Using sleep to time turning off the queue worker mid execution may be the right idea.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
