### ISSUE TITLE
Spaces in Blade broke database fetch

### ISSUE THREAD

**Issue by lahoje** [laravel/framework#49817]
### Laravel Version

10.39.0

### PHP Version

8.2.4

### Database Driver & Version

My SQL 5.7.39 through MAMP

### Description

# Background
I am learning Laravel at Larcast.com following the Laravel 8 From Scratch course. I am using  PHPSTORM version 2023.3.2. In section 5 we did some changes. Reformatting the code got the posts to stop showing as if the Collection wasn't passed to the Component.
## Spaces in the code caused the problem
```php
<x-layout>

    @include('_posts-header')

    <main class = "max-w-6xl mx-auto mt-6 lg:mt-20 space-y-6">
        @if($posts->count())
            <x-posts-grid :posts = "$posts"/> /* After reformatting the code the spaces between :posts = "$posts" caused the problem */
        @else
            <p class = "text-center">There is no posts yet. Please check back later.</p>
        @endif

    </main>
</x-layout>
```

### Steps To Reproduce

See Description above...

**Comment by driesvints** [comment]
This syntax isn't supported sorry. Please use `:posts="$posts"`

**Comment by lahoje** [comment]
Thanks for you fast reply, I understand 👍. I'll search for a solution in PhpStorm.
