### ISSUE TITLE
Migration Fails to Rollback on Unique Constraint Error

### ISSUE THREAD

**Issue by thearyanahmed** [laravel/framework#49826]
### Laravel Version

^10.10

### PHP Version

8.1.27

### Database Driver & Version

MySQL 8.0.27 for MacOS 14.1

### Description

Migration fails to rollback (delete the created table) when it faces an error while adding unique constraints. `$table->unique(['column_1', 'column_2'])`. Although the database table itself was created, the `migrations` table did not add row regarding the new table. So, when `php artisan migrate` is run, it gives an error saying table already exists. 

```txt
SQLSTATE[42S01]: Base table or view already exists: 1050 Table $tableName already exists
```

Expected behavior, 
Rollback the table that was created. 

### Steps To Reproduce

1. Create a new migration where `Schema::create($tableName)` 
2. Add `$table->unique(['column_1', 'column_2`]);` where either `column_1` or `column_2` is not present. 
3. Run `php artisan migrate`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
