### ISSUE TITLE
PDO::ATTR_CASE => PDO::CASE_LOWER (MYSQL) doesn't work when using (Model) :: create or update

### ISSUE THREAD

**Issue by QubeX2** [laravel/framework#49829]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

Mysql 8

### Description

I have set 'mysql' => 'options' => .... PDO::ATTR_CASE => PDO::CASE_LOWER. Everything works except creating and updating. If I fill the model with array like Model::create($data) and then dump the model, the attributes only contain those columns that also happens to be lower_case in the database table.

### Steps To Reproduce

1) Create at table with column with a mix of uppercase and lowercase
2) set PDO::ATTR_CASE to PDO::CASE_LOWER
3) try to use Model::create or Model::update

**Comment by QubeX2** [comment]
I created a temporary work-around that seems to work.
` public function pdoFill($data)
    {
        $columns = Schema::getColumnListing($this->table);
        $new_data = [];
        foreach($columns as $column) {
            $lc = strtolower($column);
            if(array_key_exists($lc, $data)) {
                $new_data[$column] = $data[$lc];
            }
        }
        $this->fill($new_data);
    }`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by QubeX2** [comment]
IMHO it's a bug it doesn't work to save to the database when using PDO::CASE_LOWER, data that doesn't have column_names that are lower_case doesn't get any values. How is that not a bug?

**Comment by QubeX2** [comment]
The problem is in this function that doesn't care for PDO::CASE_LOWER.

`    /**
     * Get the fillable attributes of a given array.
     *
     * @param  array  $attributes
     * @return array
     */
    protected function fillableFromArray(array $attributes)
    {
        if (count($this->getFillable()) > 0 && ! static::$unguarded) {
            return array_intersect_key($attributes, array_flip($this->getFillable()));
        }

        return $attributes;
    }`

I solved this by creating my own base class that inherits from Model with this constructor:
'public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        // fix PDO::ATTR_CASE => PDO::LOWER_CASE
        $columns = $this->getConnection()
            ->getSchemaBuilder()
            ->getColumnListing($this->getTable());
        $this->fillable = array_map('strtolower', array_slice($columns, 1));
    }'
