### ISSUE TITLE
validation message placeholder is not replaced

### ISSUE THREAD

**Issue by Treggats** [laravel/framework#49841]
### Laravel Version

10.42.0

### PHP Version

8.3

### Description

**Scenario**
Validate a password that fails the max rule.

Using the following password validation settings;

```php
Password::defaults(
    Password::min(8)
        ->max(100)
);
```

Which results in the following error message
> The password must not be greater than :max characters.

The `:max` placeholder is not replaced.

### Steps To Reproduce

Currently this test fails
```php
public function test_password_validation_message(): void
{
    $validationMessage = Validator::make(
        data: ['password' => str_repeat('o', 101)],
        rules: ['password' => Password::default()])
            ->messages()
            ->first();

    self::assertNotSame('The password must not be greater than :max characters.', $validationMessage);
}

```

Changing `\Illuminate\Validation\Rules\Password::max()` into this makes this test pass.
```php
    public function max($size)
    {
        $this->max = $size;

        $this->customRules = [
            ...$this->customRules,
            'max:'.$size,
        ];

        return $this;
    }
```

**Comment by crynobone** [comment]
PR #49861 has been merged.
