### ISSUE TITLE
Deprecation logging to a specific channel is a footgun

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#49846]
### Laravel Version

10.42.0

### PHP Version

8.2.15

### Description

So... After finally figuring out what was going on I assumed this was a bug, but after writing this issue I decided to check the documentation, and it turns out what I just spent 2 hours on is actually [a feature, not a bug](https://laravel.com/docs/10.x/logging#logging-deprecation-warnings). However, since almost anyone who decides to log their deprecations to a specific channel is going to run into this issue it seems worthwhile to still report it.

I want to log deprecations to a specific file, so logically I create a channel called "deprecations" for this. I don't want to log deprecations on production, because that generates a 40GB log file in 2 days. On production I set `LOG_DEPRECATIONS_CHANNEL` to `null`, however, this does nothing, because this is [ignored if a channel called "deprecations" exists](https://github.com/laravel/framework/blob/d293d99709d076c5667462a0b5f6e76ef52c65a4/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L133).

I think that anyone who decides to create a separate channel for their deprecations is going to call it "deprecations", I mean, what else would you call it? I don't think anyone would assume that this name is reserved and would causes your other config options to be ignored. Maybe this behavior can be changed in Laravel 11?

### Steps To Reproduce

In `config/logging.php`, configure a channel called "deprecations":

```php
'deprecations' => [
    'channel' => env('LOG_DEPRECATIONS_CHANNEL', 'null'),
    'trace' => false,
],

'channels' => [
    'deprecations' => [
        'driver' => 'single',
        'path' => storage_path('logs/deprecations.log'),
        'level' => 'debug',
    ],

    'null' => [
        'driver' => 'monolog',
        'handler' => NullHandler::class,
    ],
],
```

Then:
- Set `LOG_DEPRECATIONS_CHANNEL` to `null` 
- Cause a deprecation (for example:`trim(null)`)
- Note how it logs to `logs/deprecations.log` despite the channel being set to `null`

**Comment by driesvints** [comment]
Thanks for bringing this up @SjorsO. I do get your sentiment but since the docs are explicit about this I think we'll leave things be for now.
