### ISSUE TITLE
File validation message uses instanceof UploadedFile instead of File

### ISSUE THREAD

**Issue by tinyoverflow** [laravel/framework#49875]
### Laravel Version

10.34.2

### PHP Version

8.2.13

### Database Driver & Version

N/A

### Description

When using the validator with a manually passed `Illuminate\Http\File` object, the validation seems to work as expected. The `getSize` method checks for a Symfony file to determine on how to check that:

https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L2482-L2484

But the returned error message is wrong, as it uses the `string` message. This seems to be due to the fact that the message formatter does an instanceof `Illuminate\Http\UploadedFile`:

https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Validation/Concerns/FormatsMessages.php#L225-L227

I'd expect to both use the same condition to determine on how to validate and on what message to use.

### Steps To Reproduce

Example Snippet:

```php
$v = \Illuminate\Support\Facades\Validator::make(
    ['file' => new \Illuminate\Http\File('composer.json')],
    ['file' => 'max:1']
);

dd($v->passes(), $v->messages()->all());
```

**Comment by driesvints** [comment]
Thanks. A PR for this was sent in.
