### ISSUE TITLE
Unknown duration unit when using Sleep::for() with integers/floats

### ISSUE THREAD

**Issue by gabidj** [laravel/framework#49887]
### Laravel Version

10.40.0

### PHP Version

8.2

### Database Driver & Version

No DB, macOS 14.3 (23D56) with Herd 1.0.0

### Description

As per Sleep class in Laravel int and floats are accepted, but actually sending integers or floats will trigger an error.

Sleep::for();  accepts  \DateInterval|int|float  $duration // according to phpdoc
which calls the Sleep constructor, which also accepts int|float|\DateInterval  $duration  // according to phpdoc
which calls Sleep::duration(), which also accepts  \DateInterval|int|float  $duration // according to phpdoc

All functions will execute successfully however when Sleep::__destruct() is called the exception is thrown due to $this->pending not being a null value.

```
    public function __destruct()
    {
        if (! $this->shouldSleep) {
            return;
        }

        if ($this->pending !== null) {
            throw new RuntimeException('Unknown duration unit.');
        }
// ...
```

Is this an expected behaviour keeping possible concurrency in mind?
Am I missing something?

### Steps To Reproduce

Write a new unit test, and call Sleep::for($x). 
The variable $x must be integer or a float.

The following exception 
  • Tests\Feature\SleepTest > pretendSleep
   PHPUnit\Framework\ExceptionWrapper 

  Unknown duration unit.

The same can be achieved by running  the snippet below

```
use Illuminate\Support\Sleep;

Sleep::for($x);
```

In this case a \RuntimeException will be thrown with the same message "Unknown duration unit."

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue **as one separate commit** on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by timacdonald** [comment]
I am unable to reproduce this exception.

I created a fresh laravel application and added the following command to the `routes/console.php` file.

```php
Artisan::command('sleep', function () {
    \Illuminate\Support\Sleep::for(1.5)->seconds();
    \Illuminate\Support\Sleep::for(1.5)->milliseconds();
});
```

The artisan command runs as expected and no exception is not thrown. Will need a reproduction repository to dig into this further.

**Comment by gabidj** [comment]
Run it in an UnitTest
Tested on a fresh install with Laravel Framework 10.43.0

I figured there's no point in creating a repo for this so I made a compressed file (as .php extension is not allowed)

[ExampleTest.php.zip](https://github.com/laravel/framework/files/14137386/ExampleTest.php.zip)

Try the following within a UnitTest

File to be changed: `tests/Unit/ExampleTest.php`
Add the following snippet
```
test('that sleeping doesnt fail', function () {
    \Illuminate\Support\Sleep::sleep(1);
    \Illuminate\Support\Sleep::for(1);
});
```

**Comment by gabidj** [comment]
Thank you. You are right. I did not add the scalar, I thought if none is set a default one will be assumed (seconds or u-seconds).
This all makes sense now. Thank you.
