### ISSUE TITLE
Backticks inserted into wrong place when executing DB::raw() expressions alongside ->withSum(...)

### ISSUE THREAD

**Issue by morganarnel** [laravel/framework#49894]
### Laravel Version

10.42.0

### PHP Version

8.2.12

### Database Driver & Version

MySQL 8.2.0 on linux/arm64

### Description

Recently upgraded to Laravel 10 from 9 - have substituted our `DB::raw()` expressions with the new `(string) DB::raw(...)->getValue(DB::connection()->getQueryGrammar())` as directed in the [upgrade guide](https://laravel.com/docs/10.x/upgrade#database-expressions) because the `->withSum()` no longer accepts an expression (presumably down to the loss of string casting).

![image](https://github.com/laravel/framework/assets/84181964/60c34676-619e-45d5-b382-d50d7e474d4e)

As you can see from the above screenshot the expression has been grossly misinterpreted and the backticks have been placed in some pretty wacky places. Adding the backticks myself didn't work.

Here's a snippet of one of the offending withSum lines
```php
$query->withSum([
            'revenueEntryLineItems as actual_revenue_gross' => function ($query) {
                $query->leftJoin('tax_rates', 'revenue_entry_line_items.tax_rate_id', 'tax_rates.id');
             },
        ], (string) DB::raw('((revenue_entry_line_items.unit_price * revenue_entry_line_items.quantity) / 100) * (100 + COALESCE(tax_rates.rate, 0))')->getValue(DB::connection()->getQueryGrammar()));
```

### Steps To Reproduce

Try a funky expression in a withSum

**Comment by morganarnel** [comment]
Update: This also happens when avoiding DB::raw entirely and passing an expression as a string

![image](https://github.com/laravel/framework/assets/84181964/4d642ea0-4464-421a-8257-69e8b7bf83cb)
<img width="764" alt="image" src="https://github.com/laravel/framework/assets/84181964/d477f6de-41ed-464a-988a-8e8533dfe607">

**Comment by driesvints** [comment]
From the upgrade guide:

> Casting an expression to a string using (string) is no longer supported.

I'm sorry, but we no longer support casting to a string. Did you already try just using the DB::raw() call without the type cast?

**Comment by morganarnel** [comment]
@driesvints The string cast is just to make phpstan as happy as you are at hitting that close as completed button because the `->getValue(...)` returns a `string|int|float`, however in this scenario this is always going to be a string.

The issue here is that the wrapping is being performed incorrectly.

**Comment by driesvints** [comment]
> as happy as you are at hitting that close as completed button

I don't really appreciate the passive/aggressive tone here. Feel free to attempt a PR to the docs or the framework if you want.

**Comment by john-dent** [comment]
@driesvints 

I can see the issue here, the wrap function in Grammar.php does a check to see if the value is an expression, however the changes implemented in #44784 (removing the __toString() method) have broken the ability for this check to work (at least with the relation aggregate methods) as we can no longer pass an expression through to this.

**Comment by tpetry** [comment]
Its probably a missing expression handling somewhere in `withSum`. I'll look into it today and build a fix.

**Comment by driesvints** [comment]
Thanks @tpetry

**Comment by tpetry** [comment]
I've verified the issue and started working on a fix. The aggregate functions hadn't been documented to support expressions.

**Comment by john-dent** [comment]
Thank you both!

@tpetry, a quick question if you don't mind (this could be me missunderstanding):

This line https://github.com/laravel/framework/blob/af2a7caa70ebe2d50c3aff8c222222e30cd83d12/src/Illuminate/Database/Query/Expression.php#L34 (and in the associated interface) forcibly requires that an instance of `Grammar` be passed through yet I can see nowhere that it is actually used or required?  Without forcibly requiring this then we would be able to re-implement the `__toString()` method which would fully resolve this issue and _I believe_ would not break your original PR?

As my colleague @morganarnel has pointed out this morning, we believe this issue may extend further than just aggregate usages and in fact may impact any `DB::raw()` instance as we are forcing this to be a string, so the wrapping function will fail on any complex query.

**Comment by tpetry** [comment]
The `__toString` method can not be implemented again. The `Grammar` is passed to the expression. The standard expression does not use it but special expressions like [tpetry/laravel-query-expressions](https://github.com/tpetry/laravel-query-expressions) use it to generate database-specific output. That was the whole intention of the Grammar rewrite. So expressions can abstract the different syntax or functionality of databases into reusable components.

**Comment by john-dent** [comment]
@tpetry thank you!

I understand now, greatly appreciate you working on a fix for this! 🙂

**Comment by tpetry** [comment]
@morganarnel @john-dent PR #49912 will fix this issue
