### ISSUE TITLE
Serializing datetimes with custom format won't use the Carbon instance inner timezone.

### ISSUE THREAD

**Issue by Bajszi97** [laravel/framework#49899]
### Laravel Version

10.42

### PHP Version

8.3.2

### Description

I came along a behavior during datetime serialization, which I think contradict what is stated in the documentation. I was able to reproduce it in a blank Laravel app, as simple as the following.

### Steps To Reproduce

In the `config/app.php` file:

    'timezone' => 'Europe/Belgrade' // or any other TZ

In the `Models\User`:
```
protected $casts = [
    ...
    'created_at' => 'datetime:Y-m-d H:i:s',
];
```

After that I created a simple user in the Database, and retrieved it using Eloquent. If i get the `created_at` attribute, it will result the expected Carbon instance:
```
> $user->created_at
= Illuminate\Support\Carbon @1706542875 {#4988
    date: 2024-01-29 16:41:15.0 Europe/Belgrade (+01:00),
  }
```

When I cast it to an array, the custom format is applied, but the timezone of the Carbon instance is gone, and the result of the serialization is a string time in UTC:

```
> $user->toArray();
= [
    ...
    "created_at" => "2024-01-29 15:41:15",
  ]
```

If i interpret the documentation right, which states the following:

> If a custom format is applied to the date or datetime cast, such as datetime:Y-m-d H:i:s, the inner timezone of the Carbon instance will be used during date serialization. Typically, this will be the timezone specified in your application's timezone configuration option.

then, the resulting string should be:

     "created_at" => "2024-01-29 16:41:15",  // as it is in the Carbon instance and in the DB.

I would suggest the removal of this section from the documentation if my claims are indeed valid, and it should work as I expected.

**Comment by driesvints** [comment]
Heya. This is actually the expected behaviour. As explained in the docs right above that section: 

> By default, the date and datetime casts will serialize dates to a UTC ISO-8601 date string (YYYY-MM-DDTHH:MM:SS.uuuuuuZ), regardless of the timezone specified in your application's timezone configuration option.

This is always the case, even if a custom timezone is applied. The section you mention only tries to explain that your timezone will be applied, but the displayed time is always in UTC. I've sent in a PR to the docs to make this crystal clear: https://github.com/laravel/docs/pull/9287

**Comment by Bajszi97** [comment]
Thank you for the clarification. I had my suspicions that the

>  used during date serialization

does not mean the resulting string. The changes in [laravel/docs#9287](https://github.com/laravel/docs/pull/9287) will definitely make it more clear.
