### ISSUE TITLE
TypeError with HTTP Client 

### ISSUE THREAD

**Issue by NKozhuharov** [laravel/framework#49909]
### Laravel Version

10.42.0

### PHP Version

8.3

### Description

Looks like a similar issue existed before - https://github.com/laravel/framework/pull/37596.

Relevant stack trace:
```
TypeError: Illuminate\Http\Client\Events\ConnectionFailed::__construct(): Argument #1 ($request) must be of type Illuminate\Http\Client\Request, null given, called in /code/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php on line 1424
#67 /vendor/laravel/framework/src/Illuminate/Http/Client/Events/ConnectionFailed.php(22): Illuminate\Http\Client\Events\ConnectionFailed::__construct
#66 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1424): Illuminate\Http\Client\PendingRequest::dispatchConnectionFailedEvent
#65 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(924): Illuminate\Http\Client\PendingRequest::Illuminate\Http\Client\{closure}
#64 /vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): retry
#63 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(892): Illuminate\Http\Client\PendingRequest::send
#62 /vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(770): Illuminate\Http\Client\PendingRequest::get
```

### Steps To Reproduce

It happens sometimes, when calling

```php
public function get(string $endpoint, array $query = [], int $tries = 3, int $timeout = 60): Response {
    $headers = [
        'X-Shopify-Access-Token' => 'my-token',
        'Content-Type'           => 'application/json',
    ];
    $response = Http::setClient(Http::buildClient())->withHeaders($headers)->timeout(60)->get($this->url($endpoint, $query));
}
```

**Comment by driesvints** [comment]
Can you provide a full reproducible example with endpoint and query?

**Comment by NKozhuharov** [comment]
```php
$endpoint = 'https://waterdrop-nl.myshopify.com/admin/api/2023-10/products/42859018911930/variants.json';
$query = []; //no query
```
This is the last logged url, but it happens sometimes, so I can't guarantee that this URL will reproduce it. Since `ConnectionFailed` is involved, I guess the server didn't respond at that moment.

**Comment by driesvints** [comment]
How are you executing this? Within a CLI command? Or through a web request? Could you provide a complete step by step guide at what you're doing?

**Comment by NKozhuharov** [comment]
The service is deployed and running in the Google Cloud Platform.

A scheduled task, that is running every 5 minutes is creating jobs in the Google Cloud Tasks. We're using the `stackkit/laravel-google-cloud-tasks-queue` to create the jobs in Cloud Tasks. Then GCP is calling the `handle-task` route to execute the task. 

We're logging any errors via Sentry, there are 4 of this type today.

**Comment by NKozhuharov** [comment]
Perfect, thank you! :sunglasses:
