### ISSUE TITLE
Queue::fake() not work for artisan command

### ISSUE THREAD

**Issue by luca-rigutti** [laravel/framework#49919]
### Laravel Version

10.42.0

### PHP Version

8.3.2

### Description

Hi,

with a fresh intallation, I make a simple test that call a artisan command and dispatch an event.

The example is in the reproduce section.

I change test with some variant, like without `WithConsoleEvents`, using `Bus::fake()` but not work.

I see that work if I call the api and inside it it's called the `Job::dispatch(1)`, so it's like that the `Queue::fake()` is not involved when `$this->artisan("app:dispatch-job");` be called.

Is some setting to change?

### Steps To Reproduce

Creating a fresh installation inside a docker container

Creating those files:

DispatchJob.php
```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

use App\Jobs\Job;

class DispatchJob extends Command
{
    protected $signature = 'app:dispatch-job';

    protected $description = 'Command description';

    public function handle()
    {
        print("Before dispatch");
        Job::dispatch(1);
        print("After dispatch");
    }
}
```

Job.php
```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class Job implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(public int $id)
    {
        //
    }

    public function handle(): void
    {
        print("Test" . $this->id);
    }
}

```

And the test is this (and some variant): JobTest.php

```php
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;


use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Queue;
use Illuminate\Foundation\Testing\WithConsoleEvents;

use App\Jobs\Job;

class JobTest extends TestCase
{
    use WithConsoleEvents;

    public function test_example_Queue(): void
    {
        Queue::fake();
        $response = $this->artisan("app:dispatch-job");

        $response->assertExitCode(0);

        Queue::assertPushed(Job::class, 1);
    }

}
```

Run the test

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by luca-rigutti** [comment]
Hi @driesvints,

I wrote here because I thought it's relative to the facade Queue that is not working right with this type.

Am I wrong to think is relative of the implementation of Laravel framework itself?

Because if it doesn't catch the queue for artisan command, is not mocking in the right way?

**Comment by driesvints** [comment]
Please try a support channel. We currently do not handle support questions on this issue tracker.

**Comment by luca-rigutti** [comment]
Ok, I opened the issue in the discussion section at this link: [discussions/49926](https://github.com/laravel/framework/discussions/49926)

I hope is in the right place, thanks for the reply before
