### ISSUE TITLE
Issue with stderr logging

### ISSUE THREAD

**Issue by yongtheskill** [laravel/framework#49927]
### Laravel Version

10.43.0

### PHP Version

8.2.15

### Description

When logging to stderr, certain strings will cause issues.

In handleProcessOutput of ServeCommand.php, the output is matched against certain strings. If these strings are found, additional logic is performed.
[Here](https://github.com/laravel/framework/blob/d65ea42dbec9137b94c2793b5fe06e75e8998764/src/Illuminate/Foundation/Console/ServeCommand.php#L238C13-L288C23)

If strings that match the criteria are logged, it is possible that the strings are not what is expected, and will cause an exception (See steps to reproduce.)

### Steps To Reproduce

1. Create a new laravel project
2. In .env, change LOG_CHANNEL to stderr
3. Add the following code such that will be run: `Log::info(' Accepted:');`
4. An `Undefined array key 1` exception will be thrown.

This is because the process output contains ` Accepted`. This causes regex to be run to look for the port number after the colon. Since there is no port number, this fails and causes the exception. [This is where it happens](https://github.com/laravel/framework/blob/d65ea42dbec9137b94c2793b5fe06e75e8998764/src/Illuminate/Foundation/Console/ServeCommand.php#L326C5-L331C6)

**Comment by driesvints** [comment]
Looks like we're not going to take action here right now, sorry.
