### ISSUE TITLE
Using after commit for jobs in batch

### ISSUE THREAD

**Issue by mohamedgaber-intake40** [laravel/framework#49932]
### Laravel Version

10.39.0

### PHP Version

8.1

### Database Driver & Version

mysql

### Description

i'm trying to use job batch with after commit jobs 
but i can't figure out what is  wrong here and can't find such example in the docs or i'm missing something
this exception is thrown
serialization of 'Closure' is not allowed in vendor/laravel/framework/src/Illuminate/Queue/Queue.php line 159
```php
Bus::batch([
            app(StorePostMainImage::class, [
                'post' => $post,
                'tempImageId' => $dto->mainImageId,
            ])->afterCommit(),
            app(StorePostImages::class, [
                'post' => $post,
                'tempImagesIds' => $dto->imagesIds,
            ])->afterCommit(),
        ])->then(function (Batch $batch) use ($post) {
            event(new PostImageBusProcessed(
                postId: $post->id,
                batchId: $batch->id
            ));
        })->dispatch();
```

this is the StorePostMainImage  class
```php
public function __construct(
        protected StorePostMainImageAction $storePostMainImageAction,
        protected int $tempImageId,
        protected Post $post,
    ) {
    }

        public function handle(): void
    {
        $this->storePostMainImageAction->execute(
            post: $this->post,
            tempImageId: $this->tempImageId
        );
    }
```

this is the StorePostImages  class

```php
public function __construct(
        protected StorePostImagesAction $storePostImagesAction,
        protected Post $post,
        protected array $tempImageIds
    ) {
    }

    public function handle(): void
    {
        $this->storePostImagesAction->execute(
            post: $this->post,
            tempImageIds: $this->tempImageIds
        );
    }
```

### Steps To Reproduce

- create an action class with single public method accept any params
- create a job and import Batchable trait
- inject the action class in the job constructor with other action params
- in job handle method call the action class and pass the need params to the action public method
- create a bus batch and put the created job in the bus jobs array but make the container resolve and create the job instance
- dispatch the bus batch

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
