### ISSUE TITLE
Model casting when update the record

### ISSUE THREAD

**Issue by utsavsomaiya** [laravel/framework#49938]
### Laravel Version

10.41.0

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

Hello, and my apologies if I am mistaken. I want to bring up a point that might help clear up some confusion.

I am currently in the process of updating the model, specifically using the User model as an example.

```php
$user = User::first();

$user->update(['status' => ConsumerStatus::DEACTIVATED]);
```

The issue I've noticed is that I am not explicitly specifying the model to be cast. Instead of throwing an exception, the update operation accepts the value without any problems.

However, I am uncertain about whether this behavior is suitable for older projects that are in the process of converting static data to enums.

While debugging into the vendor files, I identified the method responsible for this behavior. The sequence of calls leading to this is as follows:

1. `Illuminate\Database\Eloquent\Model@update`
2. `Illuminate\Database\Eloquent\Model@save`
3. `Illuminate\Database\Eloquent\Model@performUpdate`
4. `Illuminate\Database\Eloquent\Builder@update`
5. `Illuminate\Database\Query\Builder@update`
6. `Illuminate\Database\Query\Builder@cleanBindings` // This method invokes the map to `castBinding`

Therefore, it seems like this method is responsible for the behavior. However, I'm not certain if my understanding is correct.

Could you please provide an update or suggest a better solution from your end? I want to ensure that I am on the right track or if there is a more suitable approach.

Thank you!

### Steps To Reproduce

The step to reproduce is mentioned the above.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by SagarNaliyapara** [comment]
@driesvints Does Laravel automatically convert a BackedEnum to a string internally, even without specifying a casting for that column in eloquent model?
