### ISSUE TITLE
Fix not extending the `$wrap` property when initiate `AnonymousResourceCollection`

### ISSUE THREAD

**Issue by Abdulmajeed-Jamaan** [laravel/framework#49934]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

When using `collection()` method in `JsonResource` class, if the resource is empty the newly initiated `AnonymousResourceCollection` does not extend the value of the property `$wrap` 

see example in PR: https://github.com/laravel/framework/pull/49903

### Steps To Reproduce

PR to fix: https://github.com/laravel/framework/pull/49903

> ### Use Case
> ```
> class SampleResource extends JsonResource
> {
>     public static $wrap = 'customValue';
> }
> 
> $emptyCollection = collect([])
> 
> return SampleResource::collection($emptyCollection)
> ```
> 
> Current http response:
> 
> ```
> {
>     "data": []
> }
> ```
> 
> Expected http response:
> 
> ```
> {
>     "customValue": []
> }
> ```

**Comment by driesvints** [comment]
Looks like we're not taking any action here right now, sorry.

**Comment by Abdulmajeed-Jamaan** [comment]
Any updates here ?
