### ISSUE TITLE
Artisan serve doesn't kill it's subprocess if killed with a signal instead of Ctrl + C

### ISSUE THREAD

**Issue by Tofandel** [laravel/framework#49941]
### Laravel Version

10.4.1

### PHP Version

8.3

### Description

When running `php artisan serve` it creates a subprocess for the server, but it seems to simply forward all it's input to the subprocess which is only listening for Ctrl + C on the keyboard to close, this is is not POSIX compliant

As such when we kill the `php artisan serve` command it doesn't do any cleanup itself and the subprocess keeps running

### Steps To Reproduce

1. Run `php artisan serve`
2. Open a second terminal
3. Run `ps aux` and get the pid of `php artisan serve`
![image](https://github.com/laravel/framework/assets/6115458/299af716-1e25-4abe-aa6e-3535257ca6e5)
4. Run `kill -SIGTINT $the_pid` which should be equivalent to a Ctrl + C signal
5. Check `ps aux` and notice that the main process is gone but the subprocess is still there
![image](https://github.com/laravel/framework/assets/6115458/e68bfdcb-e9ba-4850-8f4f-7ec36c094d0d)

This is a big problem when spawning `php artisan serve` from within another program, because programs should only use signals to kill their offsprings

**Comment by driesvints** [comment]
Thanks. You've sent in a PR (thanks for that!) so let's see how it goes.
