### ISSUE TITLE
[BUG] Nested after date validation is broken

### ISSUE THREAD

**Issue by BertvanHoekelen** [laravel/framework#49955]
### Laravel Version

10.43.0

### PHP Version

8.3.1

### Description

This [PR](https://github.com/laravel/framework/pull/49871) broke the nested date after validation which was working fine in 10.42.0.

### Steps To Reproduce

```php

use Illuminate\Support\Facades\Validator;

$validator = Validator::make(
    [
        "dates" => [
            [
                "starts_at" => "2024-02-02 12:00:00",
                "ends_at" => "2024-02-02 14:00:00"
            ]
        ]
    ],
    [
        "dates.*.starts_at" => ["date"],
        "dates.*.ends_at" => ["date", "after:starts_at"]
    ]
);

dd($validator->validate()); // This should just return the array of values but is now Illuminate\Validation\ValidationException: The dates.0.ends_at must be a date after starts at.
```

**Comment by AV-GregMayes** [comment]
We have been having issues with this on 10.43.0 with non-nested fields, too. The below example works in 10.42.0 but not in 10.43.0

```php
'from_date' => [
    'nullable',
    'date',
    'before_or_equal:to_date',
],
'to_date' => [
    'required',
    'date',
    'after_or_equal:from_date',
],
```

**Comment by MrPunyapal** [comment]
> We have been having issues with this on 10.43.0 with non-nested fields, too. The below example works in 10.42.0 but not in 10.43.0
> 
> ```
> 'from_date' => [
>     'nullable',
>     'date',
>     'before_or_equal:to_date',
> ],
> 'to_date' => [
>     'required',
>     'date',
>     'after_or_equal:from_date',
> ],
> ```

can you give me the case? 
because it works for me...

**Comment by driesvints** [comment]
We've reverted the original PR.
