### ISSUE TITLE
Markdown does not add line break bug

### ISSUE THREAD

**Issue by khanakia** [laravel/framework#49986]
### Laravel Version

10.43.0

### PHP Version

8.1.27

### Description

When converting markdown it does add the line break automatically. It should add the line break for each line

```php
echo Str::markdown(<<<Markdown
      id
      sem_id - integer
      ref - string
      Markdown);
```

## Generated Output
```html
<p>
  id
  sem_id - integer
  ref - string
</p>
```

## Expected Output

```html
<p>
  id<br>
  sem_id - integer<br>
  ref - string
</p>
```

### Steps To Reproduce

```php
echo Str::markdown(<<<Markdown
      id
      sem_id - integer
      ref - string
      Markdown);
```

**Comment by rojtjo** [comment]
As far as I know line breaks are only added in Markdown if a line ends with two or more spaces.
These seem to be missing in your example.

Please note that editors often automatically trim trailing whitespace, so you might have to change some settings to assure these remain.

**Comment by khanakia** [comment]
You can check other markdown editor even the current GitHub comment editor check I just added the items below without any spaces and they are still have linebreak

 id
sem_id - integer
ref - string

**Comment by rojtjo** [comment]
I don't think the GitHub comment section is a good example for this. They indeed do add additional line breaks, but looking at the spec of both Markdown and CommonMark it does state that a line needs to end in two or more spaces.

See:
https://daringfireball.net/projects/markdown/syntax#p
https://spec.commonmark.org/0.31.2/#hard-line-breaks
