### ISSUE TITLE
 infinite loop, the RAM becomes full 

### ISSUE THREAD

**Issue by samehdoush** [laravel/framework#49999]
### Laravel Version

10.43

### PHP Version

8.2.8

### Database Driver & Version

mysql 8.0 phpmyadmin with laragon

### Description

```
  "inertiajs/inertia-laravel": "0.6.11",
   "laravel/jetstream": "2.16.2",
   "laravel/sanctum": "3.3.2",
   ````
   When upgrading to 10.43.0
There becomes an infinite loop, the RAM becomes full, and eventually timeout appears
I trace the sequence back to Inertia::render and start the loop
The Issue only exists in: 10.43.0
   

### Steps To Reproduce

upgrade laravel/framework to 10.43.0 with inertia

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by samehdoush** [comment]
I opened my issue in the forums and no one answered me
Let me say that I created a completely new project and when I used addGlobalScope the problem starts and only in version: 10.43.0
Example of the code causing the problem: 
```
 // User.php :
  protected static function booted(): void
    {
        static::addGlobalScope(new SumTotalBalance);
    }
     public function callrecords()
    {
        return $this->hasMany(CallRecord::class);
    }
    
   // SumTotalBalance.php
    
  public function apply(Builder $builder, Model $model)
    {

        $builder->withCount(['callrecords as callrecords_followse'  => fn ($q) => $q->whereBetween('created_at', [now()->startOfDay(), now()->endOfDay()])]);
         
    }
```
The databases are empty and there are no records

The exact same code works perfectly on 10.42.0

Note: I am not asking about anything, but I am clarifying that there is a issue in version 10.43.0.

**Comment by driesvints** [comment]
We have no other reports of this right now. Here's the full list of changes: https://github.com/laravel/framework/releases/tag/v10.43.0
