### ISSUE TITLE
Spark Stripe 5.0.1 and Cashier 15 Card Last 4 Bug

### ISSUE THREAD

**Issue by JonErickson** [laravel/framework#50007]
### Laravel Version

10.43.0

### PHP Version

8.2

### Database Driver & Version

MySQL 8

### Description

I apologize if this is the wrong area - do not know where to submit Spark bug reports. 

When a customer pays with Link, no card data is available on the PaymentMethod object. Line 216 of FrontendState attempts to read the card data from all of the customer's payment methods. This results in an error when trying to read a property on a null object. I've attached a Sentry error screenshot as well as a PaymenthMethod object of a customer who paid with link demonstrating the lack of card data resulting in the error.

<img width="1904" alt="Screenshot 2024-02-07 at 9 20 47 PM" src="https://github.com/laravel/framework/assets/3356740/a46a5c3f-678f-4a22-8394-0495228a3845">

<img width="678" alt="Screenshot 2024-02-07 at 9 28 08 PM" src="https://github.com/laravel/framework/assets/3356740/c036c8e2-57c9-4ab7-812f-34e59ace8069">

### Steps To Reproduce

1. Install a fresh copy of Stripe Spark 5.0.1 with Laravel 10.
2. Make a purchase using Link.
3. Navigaqte to the Spark billing portal for the error to be thrown.

**Comment by BasHJPeters** [comment]
@driesvints I'm facing the same error when using iDEAL since v5.

**Comment by driesvints** [comment]
@BasHJPeters we only support card payments. Not iDEAL.
