### ISSUE TITLE
call to undefined method \\Symfony\\Component\\HttpFoundation\HeaderBag::all()

### ISSUE THREAD

**Issue by rorkyendo** [laravel/framework#50011]
### Laravel Version

10.28.0

### PHP Version

8.2.11

### Description

call to undefined method \\Symfony\\Component\\HttpFoundation\HeaderBag::all() in /var/www/html/webApps/vendor/symfonny/http-foundation/HeaderBag.php:115
![Screenshot 2024-02-08 171643](https://github.com/laravel/framework/assets/38852429/343c6f27-e7ca-478f-8886-b8024a3beb79)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
