### ISSUE TITLE
"Call to undefined method Closure::getClosure()" in bus batches in chain.

### ISSUE THREAD

**Issue by maxwellmezadre** [laravel/framework#50028]
### Laravel Version

10.43

### PHP Version

8.2

### Database Driver & Version

MySQL 5.6 in Ubuntu 20.04 and using Redis as the queue driver

### Description

When running a chain with some batch arrays I am receiving the following error:

**Call to undefined method Closure::getClosure()**

In: /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedClosure.php:107 (code 0)

This error almost always happens at the end of chain processing

### Steps To Reproduce

use Illuminate\Support\Facades\Bus;

$batches[] = Bus::batch([
    // Array of jobs 1
])

$batches[] = Bus::batch([
    // Array of jobs 2
])

$batches[] = Bus::batch([
    // Array of jobs 3
])

$batches[] = function () use ($condominium) {
      $this->functionToNotifyUser()
 };
  
 Bus::chain($batches)->dispatch();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
