### ISSUE TITLE
Undefined constant "Illuminate\Foundation\Console\SIGTERM"

### ISSUE THREAD

**Issue by austins** [laravel/framework#50022]
### Laravel Version

11.x-dev

### PHP Version

8.3.2

### Description

The changes in #49943 use PHP's pcntl extension. In [PHP's documentation](https://www.php.net/manual/en/pcntl.installation.php), it notes that `this module will not function on non-Unix platforms (Windows)`, so the extension isn't available on PHP run in Windows environments and would result in the following error.

```
[2024-02-09 06:00:37] local.ERROR: Undefined constant "Illuminate\Foundation\Console\SIGTERM" {"exception":"[object] (Error(code: 0): Undefined constant \"Illuminate\\Foundation\\Console\\SIGTERM\" at D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\ServeCommand.php:143)
[stacktrace]
#0 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\ServeCommand.php(90): Illuminate\\Foundation\\Console\\ServeCommand->startProcess(true)
#1 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Foundation\\Console\\ServeCommand->handle()
#2 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(212): Illuminate\\Container\\Container->call(Array)
#7 D:\\laravel\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(181): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 D:\\laravel\\vendor\\symfony\\console\\Application.php(1049): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 D:\\laravel\\vendor\\symfony\\console\\Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ServeCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 D:\\laravel\\vendor\\symfony\\console\\Application.php(169): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(196): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 D:\\laravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1180): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 D:\\laravel\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#15 {main}
"} 
```

Should the trap be wrapped in `if (!windows_os()) { ... }` or, if the issue was present on Windows, perhaps another solution to be investigated?

### Steps To Reproduce

Run `php artisan serve` on Windows on a Laravel version that includes the changes in #49943.

**Comment by driesvints** [comment]
Thanks. I've sent in a PR for this: https://github.com/laravel/framework/pull/50023

**Comment by kikky7** [comment]
I am also getting this error on Windows, installed it just now. Version in composer.lock file is dev-master. PHP 8.3.2

Error is this: `Undefined constant "Illuminate\Foundation\Console\SIGTERM"` at `vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:143`

**Comment by santiago2000-afk** [comment]
Yo estoy recibiendo este error, alguien conoce una solucion rápida: C:\Users\nuevo\desktop\main>php artisan serve

   Error 

  Undefined constant "Illuminate\Foundation\Console\SIGTERM"

  at C:\Users\nuevo\Desktop\main\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:143      
    139▕
    140▕             return in_array($key, static::$passthroughVariables) ? [$key => $value] : [$key => false];       
    141▕         })->all());
    142▕
  ➜ 143▕         $this->trap([SIGTERM, SIGINT, SIGHUP, SIGUSR1, SIGUSR2, SIGQUIT], function ($signal) use ($process) {
    144▕             if ($process->isRunning()) {
    145▕                 $process->stop(10, $signal);
    146▕             }
    147▕

  1   C:\Users\nuevo\Desktop\main\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:90
      Illuminate\Foundation\Console\ServeCommand::startProcess()

  2   C:\Users\nuevo\Desktop\main\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Illuminate\Foundation\Console\ServeCommand::handle()


C:\Users\nuevo\desktop\main>
