### ISSUE TITLE
Inconsistent HTTP status code for dd() and collect()->dd()

### ISSUE THREAD

**Issue by SolveSoul** [laravel/framework#50026]
### Laravel Version

10.41.0

### PHP Version

8.3

### Description

The returned HTTP status code for a [dd()](https://github.com/symfony/var-dumper/blob/7.0/Resources/functions/dump.php#L45) function call and [collect()->dd()](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Collections/Traits/EnumeratesValues.php#L208) call are not equal. The former returns 500 whilst the latter returns 200.

For the sake of consistency, I believe both should be 500.

It can be fixed by copying the code from dd that sets the headers to `EnumeratesValues.php#dd()` like this:

```
    public function dd(...$args)
    {
        if (!in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) && !headers_sent()) {
            header('HTTP/1.1 500 Internal Server Error');
        }

        $this->dump(...$args);

        exit(1);
    }
```

But I'm not sure if that is the cleanest solution

### Steps To Reproduce

Call collect()->dd() and see status code 200
Call dd() and see status code 500

**Comment by driesvints** [comment]
Don't think we're going to make any changes here sorry.
