### ISSUE TITLE
Cannot seed m2m relation as pivot table ids are not assigned.

### ISSUE THREAD

**Issue by IamSAB** [laravel/framework#50077]
### Laravel Version

10.43.1

### PHP Version

8.2.14

### Database Driver & Version

sqlite

### Description

I have a self referencing m2m relation on the Contact model

```php
class Contact extends User
{
    use HasFactory;

   [...]

    public function relations()
    {
        return $this->belongsToMany(Contact::class, 'relations', 'contact_id', 'related_id')->withPivot(['type', 'value']);
    }
}
```
with a pivot model
```php
class Relation extends Model
{
    use HasFactory;

    protected $fillable = [
        'type',
        'value'
    ];

    public function contact()
    {
        return $this->belongsTo(Contact::class);
    }

    public function related()
    {
        return $this->belongsTo(Contact::class);
    }
}
```
with following migrations
```php
Schema::create('contacts', function (Blueprint $table) {
            $table->uuid('id')->primary();
            [ ... ]
        });
Schema::create('relations', function (Blueprint $table) {
            $table->id();
            $table->foreignUuid('contact_id');
            $table->foreignUlid('related_id');
            $table->string('type');
            $table->string('value')->nullable();
            $table->timestamps();
        });
```
When I  use `hasAttached` as follows in a unit test
```php
$type = 'test';
        $related = Contact::factory(3)->create();
        $contact = Contact::factory()
            ->hasAttached(
                $related,
                compact('type'),
                'relations'
            )
            ->create();
```
it gives me the following error:
```
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: relations.contact_id (Connection: sqlite, SQL: insert into "relations" ("type", "updated_at", "created_at") values (test, 2024-02-13 18:04:39, 2024-02-13 18:04:39))
```
Eventually i did something wrong but I did everything as described in the [docs](https://laravel.com/docs/10.x/eloquent-factories#pivot-table-attributes).
It seems, it does not recognize the correct foreign keys and does not add them to the insert sql.

I provided as 3rd argument to `hasAttached` (what is not mentioned in the docs)  the `relations()` function as it otherwise would try to call the `contacts()` method.

### Steps To Reproduce

Add above classes and migrations to laravel and run the factory commands in a unit test.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
