### ISSUE TITLE
Scheduler buildBackgroundCommand appends the output for schedule:finish to $event->getDefaultOutput() on non windows

### ISSUE THREAD

**Issue by marius-mcp** [laravel/framework#50081]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Database Driver & Version

Mysql 8

### Description

Hi,

https://github.com/laravel/framework/blob/84e7f85769ea268ffec9acab30f7a826223b3d6f/src/Illuminate/Console/Scheduling/CommandBuilder.php#L54C8-L61C11

 
       if (windows_os()) {
            return 'start /b cmd /v:on /c "('.$event->command.' & '.$finished.' ^!ERRORLEVEL^!)'.$redirect.$output.' 2>&1"';
        }

        return $this->ensureCorrectUser($event,
            '('.$event->command.$redirect.$output.' 2>&1 ; '.$finished.' "$?") > '
            .ProcessUtils::escapeArgument($event->getDefaultOutput()).' 2>&1 &'
        );

should be

        if (windows_os()) {
            return 'start /b cmd /v:on /c "('.$event->command.' & '.$finished.' ^!ERRORLEVEL^!)'.$redirect.$output.' 2>&1"';
        }

        return $this->ensureCorrectUser($event,
            '('.$event->command.$redirect.$output.' 2>&1 ; '.$finished.' "$?") ' . $redirect . $output . ' 2>&1 &'
        );

### Steps To Reproduce

Run a background scheduled command defined like this:

->runInBackground()->sendOutputTo('/dev/stdout')

 and check the logs for 

Running scheduled command: ('/usr/local/bin/php' 'artisan' {command signature} > '/dev/stdout' 2>&1 ; '/usr/local/bin/php' 'artisan' schedule:finish "framework/schedule-{random}" "$?") > '/dev/null' 2>&1 &

If the log channel is set to stdout, the command will log nothing.

**Comment by driesvints** [comment]
Feel free to attempt a PR, thanks!

**Comment by marius-mcp** [comment]
@driesvints 
ERROR: Permission to laravel/framework.git denied to marius-mcp.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by marius-mcp** [comment]
@driesvints another issue

https://github.com/laravel/framework/discussions/50085#discussioncomment-8475718

The parenthesis are sending everithing to dev null...

**Comment by marius-mcp** [comment]
@driesvints FYI I managed to hack it with macros  and log via queue. 
So the above is not needed anyway.
https://github.com/laravel/framework/discussions/50085#discussioncomment-8495648
