### ISSUE TITLE
Disk [redis] does not have a configured drive

### ISSUE THREAD

**Issue by shabnam227** [laravel/framework#50092]
### Laravel Version

7.4

### PHP Version

7.4

### Description

Disk [redis] does not have a configured drive getting this error wile loading page ans other pages are working 

### Steps To Reproduce

Disk [redis] does not have a configured drive
<img width="1317" alt="Screenshot 2024-02-15 at 6 33 40 AM" src="https://github.com/laravel/framework/assets/71077212/9437c9da-4b91-4e71-9c6f-928c558cae93">

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
