### ISSUE TITLE
Schedule `between()` not working as expected

### ISSUE THREAD

**Issue by raveren** [laravel/framework#50120]
### Laravel Version

10.44

### PHP Version

8.1.5

### Description

I wanted to convert old style cron expressions into the more readable fluent method format, but noticed that the `between` method when scheduling commands seems to not be doing anything.

I use the example from the docs (https://laravel.com/docs/10.x/scheduling#between-time-constraints):

```php
        $schedule->command('emails:send')
            ->hourly()
            ->between('7:00', '22:00');
```

And launch `php artisan schedule:list`:

```
  0 * * * *    php artisan emails:send ......................... Next Due: in 8 Minutes
```

As you can see the configuration resolves itself to just `hourly`, is this a bug?

### Steps To Reproduce

add 
```php
        $schedule->command('emails:send')
            ->hourly()
            ->between('7:00', '22:00');
```

to `app\Console\Kernel.php` and launch `php artisan schedule:list`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by raveren** [comment]
Laracasts user s4muel reports the bug is actually in the `php artisan schedule:list` which Taylor refused to fix.

Should I file a bug for that? 

I manually converted my projects schedules into the fluent format from the hardly readable cron, and now I have no way to check if it's the same as it was.

**Comment by wanted80** [comment]
Hello,

I have the same bug and I'm using **Laravel 11.0.7** and **PHP 8.3.4**.

This is the output after launch `php artisan schedule:list`:

`*/5 * * * *  php artisan app:data:import ......................................Next Due: in 50 Seconds`

This is the part of code in the route console configuration `routes/console.php`:

```PHP
use App\Console\Commands\DataImport;
use Illuminate\Support\Facades\Schedule;

Schedule::command(DataImport::class)
    ->everyFiveMinutes()
    ->between('9:00', '23:59')
    ->withoutOverlapping()
    ->emailOutputOnFailure(config('site.default_notice_email'));
```

**Comment by raveren** [comment]
created explicit issue about the `schedule:list` https://github.com/laravel/framework/issues/50670
