### ISSUE TITLE
[10.x] Conditionable on a Belongs-To-Many query breaks it

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/framework#50123]
### Laravel Version

10.38.1

### PHP Version

8.3.2

### Database Driver & Version

SQLite

### Description

When using `when` on a Belongs to Many query, it breaks the query.

This made me nuts the whole fucking week until I had the brilliant idea to dump the query itself 😡

I assume this is because `when()` and `unless()` are applied over the Eloquent Query itself, instead of the Relation instance, because the latter acts as a proxy. A quick fix for this would be to add `Conditionable` to the Relation itself to avoid the Eloquent Query to assume the `wherePivot()` is equivalent to column name and value.

### Steps To Reproduce

```php
class Post extends Model
{
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

class Tag extends Pivot
{
    public function post()
    {
        return $this->belongsToMany(Post::class);
    }
}
```

```php
$tag->post()
     ->when(true)->wherePivot('is_hidden', false)
     ->get();
```

## Expected

```sql
"select * from "post" inner join "post_tag" on "post"."id" = "post_tag"."post_id" where "post_tag"."tag_id" = 1 and "post_tag"."is_hidden" = false
```

## Actual

```sql
"select * from "post" inner join "post_tag" on "post"."id" = "post_tag"."post_id" where "post_tag"."tag_id" = 1 and "pivot" = 'is_hidden'
```

**Comment by driesvints** [comment]
Thank you. Seems you already sent in a PR so let's see how that goes.

**Comment by DarkGhostHunter** [comment]
@driesvints can we reopen this since the issue still persist?

**Comment by driesvints** [comment]
@DarkGhostHunter since the fix broke other things I don't think we'll take any action here soon sorry.

**Comment by DarkGhostHunter** [comment]
I think I will try again for Laravel 12 once Laravel 11 launches.
