### ISSUE TITLE
`firstOrCreate` not working properly with casts

### ISSUE THREAD

**Issue by binaryfire** [laravel/framework#50143]
### Laravel Version

10.3.3

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0.31

### Description

I have the following enum:

```PHP
<?php

declare(strict_types=1);

namespace App\Settings\Enums;

use ArchTech\Enums\From;
use App\Settings\PostSettings;
use App\Settings\PaymentProvidersSetting;

enum SettingClass: string
{
    use From;

    case post = PostSettings::class;
    case payment_providers = PaymentProvidersSetting::class;
}
```

and this cast:

```PHP
<?php

declare(strict_types=1);

namespace Modules\Setting\Casts;

use BackedEnum;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

class SettingClassEnumCast implements CastsAttributes
{
    public function get($model, string $key, $value, array $attributes): ?BackedEnum
    {
        $settingClassEnum = config('modules.setting.setting_class_enum');

        return $settingClassEnum::tryFromName($value);
    }

    public function set($model, string $key, $value, array $attributes): string
    {
        return $value->name;
    }
}
```

I then use `firstOrCreate` in a command to seed settings like this:

```PHP
Setting::firstOrCreate(
    ['setting_class' => SettingClass::post],
    ['........ array of attributes ......`]
);
```

The entry is created successfully the first time the command is run, but I get a duplicate constraint violation the second time. The problem is that `firstOrCreate` is using the cast in one direction (when inserting), but not in the other direction (when performing the select to check for an existing record).

This basically prevents you from using `firstOrCreate` with custom casts.

### Steps To Reproduce

See above.

**Comment by driesvints** [comment]
Hi there. Right now this isn't possible with enums indeed. We'd appreciate a PR to make this possible, thanks.

**Comment by binaryfire** [comment]
Thanks for clarifying. Btw the problem isn't specific to enums. It occurs with any cast, since `firstOrCreate` bypasses the cast's `get()` method.

**Comment by binaryfire** [comment]
Thanks for clarifying. But this problem isn't specific to enums. It occurs with any cast, since firstOrCreate bypasses the cast's `get()` method. Doesn't that make this is a bigger problem than just a missing feature?

**Comment by binaryfire** [comment]
Just tested with some simple (non-Enum) casts and can confirm the same issue is present.

**Comment by mateusjunges** [comment]
@binaryfire can you give me a repo where I can reproduce this? This is working as expected on my local env. Also, I noticed a possible bug in your code. 

Here you return the enum `name` to be stored on the database, instead of the value. Then, when you get the record, you use the `tryFrom` method, which requires the enum value to create a new enum, instead of the name:

This code:
```php
public function set($model, string $key, $value, array $attributes): string
{
    return $value->name;
}
```

should be 

```php
public function set($model, string $key, $value, array $attributes): string
{
    return $value->value;
}
```

**Comment by binaryfire** [comment]
Hi @mateusjunges. Actually this cast is a bit different - I'm storing the enum's case (name) rather than the value in the db. That's why I'm using a custom cast rather than just casting the enum directly.

The `tryFromName` method is provided by the [archtechx/enums](https://github.com/archtechx/enums) package. This is different to the native `tryFrom` method. It tries from the case for backed enums rather than the value.
