### ISSUE TITLE
[11.x] Hidden or Missing .env variables 

### ISSUE THREAD

**Issue by JoeCianflone** [laravel/framework#50151]
### Laravel Version

11

### PHP Version

n/a

### Database Driver & Version

n/a

### Description

There seem to be some unlisted `.env` variables in 11. The two that I saw that made me write this were `AUTH_GUARD` and `AUTH_MODEL` I just created a new app using `--dev` and was playing around and wanted to change the auth model from `User` to `Customer` and nothing was documented saying how I'd do this, so after a bunch of time searching I realized I could  published the `auth` config and that's where I saw the the two vars.  Maybe the assumption is that someone new would be using Breeze or something and that's probably a good assumption, but I think if you have any env vars IN the code, they should be exposed in the env file

### Steps To Reproduce

go look at the `.env-example` file

**Comment by crynobone** [comment]
Laravel 11 is not been officially released yet. Feel free to PR changes

**Comment by driesvints** [comment]
Not all env variables are exposed in the example file btw. That would be just too much. Some are discoverable through the docs. If you really want an env variable to be available in the example file you can always try a PR 👍
