### ISSUE TITLE
Blade compilation issues with Tailwind container queries

### ISSUE THREAD

**Issue by agentphoenix** [laravel/framework#50171]
### Laravel Version

10.45.0

### PHP Version

8.3.1

### Description

When using Tailwind's container queries plugin with the `@class` directive, Blade either throws exceptions about unexpected endif or simply doesn't compile the classes correct. Using `Arr::toCssClasses` directly works as expected.

The following examples are in the reproduction repo. (Note: Tailwind isn't installed and configured, but it isn't necessary to show the issues with the Blade compiler.)

## Code that works

`/success` shows everything working as expected with the `Arr::toCssClasses`

<img width="999" alt="Screenshot 2024-02-20 at 9 16 08 PM" src="https://github.com/laravel/framework/assets/14422/ed88f450-b14c-4c70-8241-1cd656370907">

I suspect this is working due to Blade wrapping everything in `e()`.

Here's a snippet of the code that works (full example in the repo):

```blade
@if (filled($heading))
    <h1
        class="{{
            Illuminate\Support\Arr::toCssClasses([
                'font-bold tracking-tight text-gray-900 @xs:text-4xl @md:text-6xl',
                'mt-10' => filled($callout),
                '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout)
            ])
        }}"
    >
        {{ $heading }}
    </h1>
@endif

@if (filled($description))
    <div
        class="{{
            Illuminate\Support\Arr::toCssClasses([
                'text-lg/8 text-gray-600',
                'mt-6' => filled($heading),
                'mt-10' => filled($callout) && blank($heading),
                '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout) && blank($heading),
            ])
        }}"
    >
        {{ $description }}
    </div>
@endif
```

## Code that throws an exception

`/failure` shows the exception (though this may be compounded by wrapping the HTML in conditionals)

<img width="725" alt="Screenshot 2024-02-20 at 9 16 36 PM" src="https://github.com/laravel/framework/assets/14422/882a1b3f-3dbc-4491-8777-e57db7d0b032">

Here's a snippet of the code that throws an exception (full example in the repo):

```blade
@if (filled($heading))
    <h1
        @class([
            'font-bold tracking-tight text-gray-900 @xs:text-4xl @md:text-6xl',
            'mt-10' => filled($callout),
            '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout)
        ])
    >
        {{ $heading }}
    </h1>
@endif

@if (filled($description))
    <div
        @class([
            'text-lg/8 text-gray-600',
            'mt-6' => filled($heading),
            'mt-10' => filled($callout) && blank($heading),
            '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout) && blank($heading),
        ])
    >
        {{ $description }}
    </div>
@endif
```

## Code that compiles incorrectly

`/incorrect` is the same thing as `/failure` but without the conditionals (you can see that the content of the `@class` call is simply output on the page)

<img width="998" alt="Screenshot 2024-02-20 at 9 16 21 PM" src="https://github.com/laravel/framework/assets/14422/d8d91b63-e2cc-4679-b91d-6760c8024f01">

Here's a snippet of the code that compiles incorrectly (full example in the repo):

```blade
<h1
    @class([
        'font-bold tracking-tight text-gray-900 @xs:text-4xl @md:text-6xl',
        'mt-10' => filled($callout),
        '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout)
    ])
>
    {{ $heading }}
</h1>

<div
    @class([
        'text-lg/8 text-gray-600',
        'mt-6' => filled($heading),
        'mt-10' => filled($callout) && blank($heading),
        '@xs:mt-24 @md:mt-32 @xl:mt-16' => blank($callout) && blank($heading),
    ])
>
    {{ $description }}
</div>
```

### Steps To Reproduce

https://github.com/agentphoenix/class-directive-bug

**Comment by timacdonald** [comment]
I've hit a similar issue in the past where there was a directive defined in the Laravel app that matched one of Tailwinds `@` things, e.g, an `@container` blade directive interfering with Tailwind's `@container` CSS thing.

I had to use Blade's escaping mechanism `@@container` when referencing the Tailwind version.

Not sure what exactly is causing the issue here, though.

**Comment by agentphoenix** [comment]
@timacdonald thanks for the suggestion! I gave it a try and unfortunately no change. The compiled output still has the same issues.

I even tried changing the `compileClass` method to wrap everything in the `e` function (since that's what happens when echoing out the `Arr::toCssClasses` in the successful test) and it still breaks. I'm just not sure where the actual problem is coming from to even start working on a PR that fixes the issue.

**Comment by agentphoenix** [comment]
I've narrowed this down to the following regex in the `compileStatements` method of the `BladeCompiler`.

```php
preg_match_all('/\B@(@?\w+(?:::\w+)?)([ \t]*)(\( ( [\S\s]*? ) \))?/x', $template, $matches);
```

I've been trying to work on tweaking this regex to ignore anything that has a single colon, but retains the double colons. If anyone has any suggestions for ways to accomplish that, I'd love the input.

**Comment by aguingand** [comment]
It seems to be related to https://github.com/laravel/framework/pull/45490 and further updates of `BladeCompiler::compileStatements()`

**Comment by agentphoenix** [comment]
@aguingand thanks for the heads up on that one. Not sure that changes the fix that I have, but I'll give it another pass and see.

@altamisatmaja curious how the Tailwind CDN is addressing the issue for you?

**Comment by milkbottlelough** [comment]
@agentphoenix I tweaked the regex so that it ignores anything with a single colon but retains the double colons:

`preg_match_all('/\B@(@?\w+(?:[ \t]*::[ \t]*\w+)?)([ \t]*)(\( ( [\S\s]*? ) \))?/x', $template, $matches);
`

Not tested but might help?

**Comment by sebastiaodomingos** [comment]
I believe the regex is fine. I suspect the issue could be related to vite/tailwind installation because if you change the last @xl to @lg it works without errors. That's where I stopped for now.

**Comment by driesvints** [comment]
Hi all. Since there's no action on this issue any more we're closing this. We'd still appreciate a PR that could potentially fix this one. Thanks
