### ISSUE TITLE
[9.x] RateLimiter fails to work when RateLimiter::for uses path as the name instead of const string

### ISSUE THREAD

**Issue by qiulang** [laravel/framework#50174]
### Laravel Version

9

### PHP Version

8.1.4

### Database Driver & Version

MySQL 5.x

### Description

When I did not use const string for RateLimiter name but path, RateLimiter fails to work,

```
    protected function configureRateLimiting()
    {
        $path = request()->method() . request()->path();
        RateLimiter::for($path, function (Request $request) use (60) {
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
        });
    }

    public function boot()
    {
        $this->configureRateLimiting();
        $path = request()->method() . request()->path();
        $this->routes(function () {
            Route::middleware(''throttle:' . $path)
            ...
     }
```

### Steps To Reproduce

`RateLimiter::for($path .. )` uses path (`$path = request()->method().request()->path();`) instead of const string then RateLimiter fails to work.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
