### ISSUE TITLE
Migrations not respecting nullable on polygon or point types.

### ISSUE THREAD

**Issue by flatcapco** [laravel/framework#50201]
### Laravel Version

10.45

### PHP Version

8.3.3

### Database Driver & Version

Mysql 8.0.3.3

### Description

Nullable == false is not respected when running a new migration for the 2 column types "polygon" and "point" for a Mysql 8 table

$table->polygon('geom')->nullable(false);
$table->point('point')->nullable(false);

### Steps To Reproduce

Create a migration with 2 columns:

$table->polygon('geom')->nullable(false);
$table->point('point')->nullable(false);

The columns are not set to nullable in the database.

It works if you run a DB::statement after to alter the columns
DB::statement('ALTER TABLE polygons MODIFY COLUMN geom POLYGON SRID 4326 NOT NULL;');
DB::statement('ALTER TABLE locations MODIFY COLUMN point POINT SRID 4326 NOT NULL;');

which is needed if you want to restrict your point and polygon to use an SRID value for spatial indexing:        DB::Statement('CREATE SPATIAL INDEX idx_polygons_geom ON polygons(geom);');
DB::Statement('CREATE SPATIAL INDEX idx_locations_point ON locations(point);');

**Comment by driesvints** [comment]
I have a feeling this will be solved in Laravel v11. Am I correct @hafezdivandari?

**Comment by flatcapco** [comment]
Thanks but I think the nullable bug still exists in L10, what I'm seeing using the laravel 10 example:

If I follow the adding steps above it does correctly set point and polygon to "is_nullable NO" 

however if srid wasn't used then the bug for ->nullable(false) still exists as its not applied to the column correctly and since srid is optional that seems strange to me.

In my case I do want to use srid so I can use your adding lines and remove my second step to enforce the srid and nullable status.


Thanks

**Comment by flatcapco** [comment]
See above sorry I closed it by accident

**Comment by flatcapco** [comment]
> Just not add `->nullable(false)` like @hafezdivandari suggested? Why can't you do that?

adding $table->polygon('geom')->srid(4326) works. 

However, if you don't specify a srid then is_nullable can only be set to false with a raw statement.

**Comment by hafezdivandari** [comment]
It even works if you add `->nullable(false)` with/without using `srid`. I've tested again, everything works fine on Laravel 10. I couldn't reproduce your issue.

**Comment by flatcapco** [comment]
ok weirdly I can't replicate now either :/ consider it closed and me an idiot unless I can see whats changed

**Comment by eusonlito** [comment]
@flatcapco do you have upgraded to Laravel 11?

Laravel 11 does not support  `getDoctrineSchemaManager`, then I can not register a type `point` and my migrations fails with `Method Illuminate\Database\Schema\Blueprint::point does not exist.` when `$table->point('point', 4326)->nullable();` is defined.

```php
/**
 * @return void
 */
protected function defineTypePoint(): void
{
    if (Type::hasType('point') === false) {
        Type::addType('point', PointType::class);
    }

    DB::connection()
        ->getDoctrineSchemaManager()
        ->getDatabasePlatform()
        ->registerDoctrineTypeMapping('point', 'point');
}
```

@driesvints ideas about this?
