### ISSUE TITLE
Redis interactions silently fail if using the same connection as a currently subscribed client

### ISSUE THREAD

**Issue by ianzylstra** [laravel/framework#50217]
### Laravel Version

10.40

### PHP Version

8.2

### Description

Using the Redis facade's `subscribe` method, for example, as a means to engage in pub/sub communication with another service, any Redis interactions that are executed from within the supplied closure will fail if they use the same connection as the subscription command.

This is expected in a strict sense because the Redis protocol expects clients in subscription mode to issue only subscription related commands, but Laravel should at the very least surface the failed commands as errors.

Ideally, the framework could intelligently spawn a new client connection if it observes the intended connection is currently in subscription mode.

This issue can currently be worked around by de-conflicting connection configs between the "subscriber" and any other Redis interactions such as job queueing or cache calls, but I believe the current silent failures are a less than ideal experience.

### Steps To Reproduce

Execute the following code. If the Redis queue and database configurations are configured to use the same Redis connection, e.g. `default`, the job dispatch will fail silently.

```php
use Illuminate\Support\Facades\Redis;

Redis::subscribe(['channel_name'], function (string $message) {
    YourJob::dispatch();
}
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
