### ISSUE TITLE
Incorrect information in the comment block for the function Str::orderedUuid()

### ISSUE THREAD

**Issue by wq9578** [laravel/framework#50231]
### Laravel Version

10.44.0

### PHP Version

8.3.1

### Database Driver & Version

MySQL 8.2.0

### Description

In the [comment block](https://github.com/laravel/framework/blob/56250738b43f0ff3e20a3596ac2caa0b589a1aac/src/Illuminate/Support/Str.php#L1637) for the function `Str::orderedUuid()` it is incorrectly stated: 

> Generate a time-ordered UUID (version 4).

Correctly it should be written:

> Generate a time-ordered **_modification of_** UUID (version 4) **_containing a time stamp_**.

By [definition](https://uuid.ramsey.dev/en/stable/rfc4122/version4.html)

> Version 4 UUIDs [...] do not contain any information about the time they are created [...].

While this is not technically a bug breaking execution, this error in the statement (claiming to be version 4) might trap a developer into using this function by believing that the generated UUIDs do not contain any time information, leading to unintended leakage of (time) information.

Strictly speaking, `Str::orderedUuid()` doesn't produce UUIDs fully complying to [RFC 4122](https://uuid.ramsey.dev/en/stable/rfc4122.html), but just the customization "[Timestamp-first COMB Codec](https://uuid.ramsey.dev/en/stable/customize/timestamp-first-comb-codec.html#customize-timestamp-first-comb-codec)":

> In 2002, Jimmy Nilsson recognized this problem with random UUIDs and proposed a solution he called “COMBs” (see “[The Cost of GUIDs as Primary Keys](https://www.informit.com/articles/printerfriendly/25862)”).

Changing the function name would break implementations, but at least the comment should be updated.

### Steps To Reproduce

See description.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!
