### ISSUE TITLE
Max file size rule is lost if `types` used after

### ISSUE THREAD

**Issue by cy2-alex** [laravel/framework#50253]
### Laravel Version

10.41.0

### PHP Version

8.1.2

### Description

Encountered an issue that the file size wasn't being enforced by the validator, investigating I found that if you have a rule declared like this:

`Rule::file()->max("250kb")->types($formattedMimetypes)`

... the file size is lost after the types are set (note the `null` value for `maximumFileSize`:

```
Illuminate\Validation\Rules\File {#1747
  #allowedMimetypes: array:1 [
    0 => "application/doc,application/docx,application/msword,application/odt,application/odp,application/rtf,application/pdf,application/ppt,application/pptx,application/vnd-ms-excel,application/xml,application/x-yaml,image/*,text/css,text/html,text/plain,text/richtext,"
  ]
  #allowedExtensions: []
  #minimumFileSize: null
  #maximumFileSize: null
  #customRules: []
  #messages: []
  #data: null
  #validator: null
}
```

However if you use the fluent methods in the other order it works as expected:

`Rule::file()->types($formattedMimetypes)->max("250kb")`

...results in a file rule object that does have both the `allowedMimeTypes` and `maximumFileSize` configured as expected. I had a look at the documentation and couldn't find anything that indicated you must use a specific order in the fluent method calls.

```
Illuminate\Validation\Rules\File {#1747
  #allowedMimetypes: array:1 [
    0 => "application/doc,application/docx,application/msword,application/odt,application/odp,application/rtf,application/pdf,application/ppt,application/pptx,application/vnd-ms-excel,application/xml,application/x-yaml,image/*,text/css,text/html,text/plain,text/richtext,"
  ]
  #allowedExtensions: []
  #minimumFileSize: null
  #maximumFileSize: 256.0
  #customRules: []
  #messages: []
  #data: null
  #validator: null
}
```

### Steps To Reproduce

`Rule::file()->max("250kb")->types(['application/pdf'])`

Use a debugger or `dd` to observe the rule object's state, the max file size will have been lost but the MIME types set properly.

`Rule::file()->types(['application/pdf'])->max("250kb")`

Use a debugger or `dd` to observe the rule object's state, the MIME types are still set properly but now so is the `maximumFileSize` as would be expected in both cases.

**Comment by crynobone** [comment]
https://github.com/laravel/framework/blob/988206bcacf79829bda66af4a016778e4b4d762a/src/Illuminate/Validation/Rules/File.php#L128-L137

This seems to be expected behavior. You may attempt to submit a PR if you can without disabling following usage: `Rule::types(['application/pdf'])->max("250kb")`

**Comment by cy2-alex** [comment]
Bizarre. Why have a fluent API that cannot be called in variable order. Might as well just use functional programming, which would have the advantage of being a lot more predictable.
