### ISSUE TITLE
Null exception when sending a mail defining envelope without `from`

### ISSUE THREAD

**Issue by Sharptsa** [laravel/framework#50261]
### Laravel Version

10.45.1

### PHP Version

8.1.27

### Description

Sending a Mailable with an envelope without the `from` argument throws an error, even when a global `from` address is set in the config.
I seems that as long as an envelope is defined, Laravel tries to get the sender address from it without defaulting to the config sender.

```
Attempt to read property "address" on null

  at vendor/laravel/framework/src/Illuminate/Mail/Mailables/Envelope.php:272
    268▕      */
    269▕     public function isFrom(string $address, string $name = null)
    270▕     {
    271▕         if (is_null($name)) {
  ➜ 272▕             return $this->from->address === $address;
    273▕         }
    274▕ 
    275▕         return $this->from->address === $address &&
    276▕                $this->from->name === $name;
```

Explicitly setting the `from` argument to the config value fixes the issue but it would be better to rely on the implicit global configuration as stated in the documentation.

### Steps To Reproduce

Mailable:
```php
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class PasswordReset extends Mailable
{
    use Queueable;
    use SerializesModels;

    /**
     * Create a new message instance.
     */
    public function __construct(protected string $url)
    {
    }

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Password Reset',
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        return new Content(
            view: 'emails.resetPassword',
            with: [
                'url' => $this->url,
            ]
        );
    }
}
```

config/mail.php:
```php
'from' => [
    'address' => env('MAIL_SENDER', 'no-reply@sender.com'),
    'name' => 'Sender',
],
```

Method that sends the email:
```php
public function sendEmail(User $user, string $token): void
{
    $url = $this->generateUrl($token);
    $mail = new PasswordReset($url);
    Mail::to($user->email)->send($mail);
}

**Comment by arifszn** [comment]
I couldn't reproduce the issue. Is there any reproducible repository, @Sharptsa ?

**Comment by Sharptsa** [comment]
I was just looking into it and it's not actually  a bug with the mailer.

The error is coming from a test asserting that the sender is correct :

```php
Mail::assertSent(PasswordReset::class, static function (PasswordReset $mail) use ($user) {
    return $mail->hasTo($user->email) &&
        $mail->hasFrom('no-reply@sender.com');
});
```
The assertion is made on the Mailable instance and checks the `from` parameter on the envelope. Since the envelope has no `from` defined, it throws an error down the line.

It only affects tests, so definitely not a big deal. I'm not even sure this is a really bug. I guess it could be handled better and not throw an error but that's it.

Sorry for the initial misleading report.
