### ISSUE TITLE
Eloquent's `ArrayObject` breaks default behavior of json encoding

### ISSUE THREAD

**Issue by amir9480** [laravel/framework#50264]
### Laravel Version

10.54.1

### PHP Version

8.2

### Description

Eloquent uses an override of PHP's `ArrayObject `to handle the casting of model attributes using the `AsArrayObject`.
When I try to JSON serialize an empty array with `ArrayObject`, it serializes it as an empty array instead of an object.

```php
$var = ['array' => [], 'object' => new \ArrayObject()];
json_encode($var) // {"array":[],"object":{}}

$var = ['array' => [], 'object' => new \Illuminate\Database\Eloquent\Casts\ArrayObject()];
json_encode($var) // {"array":[],"object":[]}
```

### Steps To Reproduce

1. Make an empty array using the `Illuminate\Database\Eloquent\Casts\ArrayObject` class.
2. Serialize it as JSON.

**Comment by crynobone** [comment]
Looks like the PR was rejected and this seems an expected behavior for now.
