### ISSUE TITLE
eloquent created event fired too early

### ISSUE THREAD

**Issue by banachg** [laravel/framework#50262]
### Laravel Version

10.4

### PHP Version

8.2

### Database Driver & Version

n/a

### Description

Not sure if intended, but when creating new record using Eloquent:
Illuminate\Database\Eloquent\Model save() function fires created event  in performInsert() function before setting connection and executing finishSave() function.

As a result model received by 'created' event has:
- 'connection' attribute empty what results in some issues when using multiple dbs
- 'original' array empty what results in issue with updating this model in event/listener class as then save() method tries to save also id which is primary key here.

To handle those issue I need to refresh model received by event.

Is it intended for some reasons?

### Steps To Reproduce

attach event i model like this:

protected $dispatchesEvents = [
        'created' => RecordCreated::class,
    ];

then add event like this:

class RecordCreated
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public Ticket $record;

    /**
     * Create a new event instance.
     */
    public function __construct(Ticket $record)
    {
        $this->record= $record;

        //for example try to update here and this will throw error "Cannot update identity column 'id'."
        $this->record->name = 'test';
        $this->record->save();
    }
}

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
