### ISSUE TITLE
Docs Command can not be cancelled when offline

### ISSUE THREAD

**Issue by grafst** [laravel/framework#50277]
### Laravel Version

10.45.1

### PHP Version

8.3.3

### Description

The php artisan docs command cannot be interrupted using the CTRL+C key sequence when the system is offline. This issue prevents users from stopping the execution of the command in environments without an internet connection, leading to prolonged waits (>10sec) or the necessity to terminate the terminal session.

OS: macOS

### Steps To Reproduce

1. Ensure the system is offline or disconnect from the internet.
2. Open the terminal application.
3. Navigate to the Laravel project directory.
4. Run the command php artisan docs.
5. Attempt to cancel the operation using the CTRL+C key sequence.

**Comment by driesvints** [comment]
@timacdonald do you maybe know?

**Comment by timacdonald** [comment]
@grafst I'm not able to replicate the long connection wait time when disconnected.

If I turn my Wi-Fi off I get an error *instantly*.

We could reduce the connection timeout for the command, but any value feels kinda arbitrary to me.

**Comment by timacdonald** [comment]
I will try manually pointing the docs command at a HTTP tarpit and see if I can recreate this tomorrow.

We can potentially trap signals to fix this (h/t @crynobone )

**Comment by grafst** [comment]
@timacdonald you are right when I'm completely offline It's fine. The error seems to arise when there is some kind of network error/delay...
Never heard of the tarpit-technique, very interesting :)
I wouldn't necessarily shorten the timeout, maybe some people on very slow networks will be greatful for a long timeout.
Trapping the abort signal would be a good idea either way I think...

**Comment by timacdonald** [comment]
@grafst, I've just replaced the HTTP request with one that takes 10 seconds.

```diff
// vendor/laravel/framework/src/Illuminate/Foundation/Console/DocsCommand.php
    /**
     * Fetch the documentation index from the Laravel website.
     *
     * @return \Illuminate\Http\Client\Response
     */
    protected function fetchDocs()
    {
+       echo 'making the HTTP request';
+
+       return $this->http->get("https://httpbin.org/delay/10");
-       return $this->http->get("https://laravel.com/docs/{$this->version()}/index.json");
    }
```

Then I run the command. The request is send but takes 10 seconds to respond, i.e., we are held on the HTTP line. When I press `Ctrl-c` the command instantly quits.

<img width="417" alt="Screen Shot 2024-03-04 at 10 30 33 am" src="https://github.com/laravel/framework/assets/24803032/8d09a521-f4db-4fab-907c-4f0a5162e52f">

Do you have any ideas how I could replicate the issue further?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
