### ISSUE TITLE
New Observe Attribute work has broken my model

### ISSUE THREAD

**Issue by TheFrankman** [laravel/framework#50284]
### Laravel Version

10.45.1

### PHP Version

8.1.2

### Database Driver & Version

MariaDB 10.x

### Description

Latest update has broken models with custom constructs.

### Steps To Reproduce

```
 "class": "ArgumentCountError",
    "message": "Too few arguments to function App\\Models\\TimbrePlayer::__construct(), 0 passed in /var/www/timbre/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php on line 67 and at least 2 expected",
    "code": 0,
    "file": "/var/www/timbre/app/Models/TimbrePlayer.php:28",
    "trace": [
```

I have a model that that has a custom construct : 

```
   public function __construct(
        Customer $customer,
        string $assetUuid,
        string $type = 'item',
        ?string $mount = null,
        ?CustomEmbedTheme $defaultCustomerEmbedTheme = null
    ) {
        parent::__construct();
        $this->customer = $customer;
        $this->assetUuid = $assetUuid;
        $this->type = $type;
        $this->mount = $mount;
        $this->defaultEmbedTheme = $defaultCustomerEmbedTheme;
    }
```

I believe the new auto discovery work is at fault here. I haven't done a full investigation yet, i will update as I go but fairly confident it's related to this PR : https://github.com/laravel/framework/pull/49843

**Comment by driesvints** [comment]
> I have a model that that has a custom construct :

I'm sorry but we do not recommend or support usage of models with custom constructs and strongly advice against this.

**Comment by matin-kh73** [comment]
@TheFrankman
This may help you #50295

**Comment by Disservin** [comment]
> > I have a model that that has a custom construct :
> 
> I'm sorry but we do not recommend or support usage of models with custom constructs and strongly advice against this.

@driesvints Is this documented anywhere?

**Comment by driesvints** [comment]
@Disservin not sure. If it isn't, we welcome PRs.
