### ISSUE TITLE
whereHas, withWhereHas doesn't work properly with "withAvg.... " methods.

### ISSUE THREAD

**Issue by muratgorken** [laravel/framework#50285]
### Laravel Version

9.11

### PHP Version

8.1.0

### Database Driver & Version

MySQL 5.7.36

### Description

Normally, I expect the withAggregate function to work by including the "where" clauses within it. However, when I use one of the whereHas and withWhereHas methods and then use one of the withAggregate functions afterward, it doesn't include the closure part of the whereHas method.

This leads to the following problem:

For example, consider a relationship between an author and books.
```
$books = Author::whereHas('books', function ($query) {
    $query->where('type', 'drama');
})->withAvg('books as page_count_avg', 'page_count')->get();

```
In this query, we would expect the average page count to be calculated only for books of type "drama". However, the result we encounter is as follows:

```
SELECT `author`.*,
  (
    SELECT avg(`books`.`page_count`)
    FROM `books`
    WHERE `author`.`id` = `books`.`author_id`
  ) AS `page_count_avg`
FROM `author`
WHERE EXISTS (
    SELECT *
    FROM `books`
    WHERE `author`.`id` = `books`.`author_id`
      and `TYPE` = 'drama'
  )

```
To solve this, when examining the code, I noticed that the withAggregate method in QueriesRelationships.php normally parses the where clauses in the query. However, it doesn't parse the whereHas queries. To address this, I temporarily added a parameter called conditions:

`public function withAggregate($relations, $column, $function = null, $conditions = null)`

Then within the code:

```
if ($conditions) {
    $query->callScope($conditions);
}

$query = $query->mergeConstraintsFrom($relation->getQuery())->toBase();
```

I used it like this:

```
$books = Author::whereHas('books', function ($query) {
    $query->where('type', 'drama');
})->withAggregate('books as page_count_avg', 'page_count', 'avg', function($query) {
    $query->where('type', 'drama');
})->get();
```

The SQL output is now:

```
SELECT `author`.*,
  (
    SELECT avg(`books`.`page_count`)
    FROM `books`
    WHERE `author`.`id` = `books`.`author_id`
      and `TYPE` = 'drama'
  ) AS `page_count_avg`
FROM `author`
WHERE EXISTS (
    SELECT *
    FROM `books`
    WHERE `author`.`id` = `books`.`author_id`
      and `TYPE` = 'drama'
  )
```
I needed this because I had to sort the main table based on data from the related table. However, I noticed that when sorting the table filtered by withWhereHas, it was sorted based on the unfiltered entries.

I'm not sure if there's a better way to handle this, but there's definitely an issue here. I'm undecided about whether to open a pull request or not.

### Steps To Reproduce

Create new laravel project and make two model called author and books.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by muratgorken** [comment]
well, i tested now on Laravel v10.45.1 (PHP v8.1.0)
