### ISSUE TITLE
page expired when login 

### ISSUE THREAD

**Issue by Ensaia** [laravel/framework#50299]
### Laravel Version

10.46.0

### PHP Version

8.2.15

### Database Driver & Version

mysql  Ver 15.1 Distrib 10.6.16-MariaDB

### Description

page expired when login or logout and the user is logged out after refresh.
and sometimes the logout link not responding.

https://github.com/laravel/framework/assets/19869364/72f26049-48fa-43a0-a52d-ed5cf7d04bba

and sometimes when redirecting with value it's not working and returning null value.

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
