### ISSUE TITLE
[v11] Spark middleware does not exist

### ISSUE THREAD

**Issue by pxpm** [laravel/framework#50298]
### Laravel Version

11

### PHP Version

8.2

### Database Driver & Version

sqlite

### Description

```php
local.ERROR: Uncaught ReflectionException: Class "Spark\Http\Middleware\VerifyBillableIsSubscribed" does not exist in Command line code:1
Stack trace:
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ReflectionException: Class \"Spark\\Http\\Middleware\\VerifyBillableIsSubscribed\" does not exist in Command line code:1
"} 
```
The middleware is referenced here: https://github.com/laravel/framework/blob/7c680bb58dfb15923209045f99ed5cf46c31f45d/src/Illuminate/Foundation/Configuration/Middleware.php#L739

I am not sure about the fix, or if there is something to fix other than removing that alias.
If it were to fix, maybe checking if the class exists before pushing it to router in https://github.com/laravel/framework/blob/7c680bb58dfb15923209045f99ed5cf46c31f45d/src/Illuminate/Foundation/Http/Kernel.php#L456 ?  🤷 

Cheers

### Steps To Reproduce

just a fresh laravel instalation with: `composer create-project laravel/laravel:"dev-master" laravel11`

**Comment by jbrooksuk** [comment]
You need to install [Laravel Spark](https://spark.laravel.com) before you may use the middleware.

**Comment by pxpm** [comment]
@jbrooksuk maybe I am missing something, and sorry if that's the case. But is Spark now a Laravel dependency ? 

I just created a new Laravel application using the above mentioned command: `composer create-project laravel/laravel:"dev-master" laravel11`  

Care to re-open or please clarify? This spark alias came with the framework.  

Thanks in advance. 🙏

**Comment by crynobone** [comment]
![CleanShot 2024-02-29 at 08 39 21](https://github.com/laravel/framework/assets/172966/0af3a623-08cf-4072-a32a-38b39d16847c)

Unable to replicate the issue with just `composer create-project laravel/laravel:"dev-master" laravel11`
