### ISSUE TITLE
Incorrect behaviour "SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification."

### ISSUE THREAD

**Issue by Cryborg** [laravel/framework#50303]
### Laravel Version

10.46

### PHP Version

8.2

### Database Driver & Version

SQLite

### Description

In a migration, I have the following code that worked well a few days ago : 
```
    public function down(): void
    {
        Schema::table('answers', function(Blueprint $table) {
            $table->dropColumn('corrected_text');
            $table->dropColumn('options');
            $table->dropColumn('score');
        });
    }
```

Now, I have this message when I run the tests : "SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification."

The solution I found is this : 
```
    public function down(): void
    {
        Schema::table('answers', function (Blueprint $table) {
            $table->dropColumn('corrected_text');
        });
        Schema::table('answers', function (Blueprint $table) {
            $table->dropColumn('options');
        });
        Schema::table('answers', function (Blueprint $table) {
            $table->dropColumn('score');
        });
    }
```

But it seems hacky and looks like a regression to me. I updated to 10.46 and I was on 10.40 before.

### Steps To Reproduce

Use multiple dropColumns in a migration file, and run unit tests using SQLite DB.

**Comment by hafezdivandari** [comment]
You have added `doctrine/dbal`?

To fix this, you may call `Schema::useNativeSchemaOperationsIfPossible()` method within the boot method of your `App\Providers\AppServiceProvider` class. check #45258

PS: This won't happen on Laravel 11.x

**Comment by Cryborg** [comment]
> Schema::useNativeSchemaOperationsIfPossible()

It solved the problem, thanks!

Just for my knowledge, why do I have to do this now? doctrine/dbal has been installed for months on my project.

**Comment by hafezdivandari** [comment]
Nothing changed recently on this manner (dropping columns on 10.x), maybe you didn't run your migrations after installing doctrine/dbal?
