### ISSUE TITLE
Sessions table is created even though driver is set to redis

### ISSUE THREAD

**Issue by jameswagoner** [laravel/framework#50317]
### Laravel Version

11.x

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

Setting session env variables to use `redis` as a driver in an attempt to avoid sessions table being created while migrating fails. `sessions` table always gets created.

### Steps To Reproduce

1. Set `redis` for `SESSION_DRIVER`
```
SESSION_DRIVER=redis
```

2. Run migration
```bash
php artisan migrate
```

3. See `sessions` table in database

<img width="593" alt="image" src="https://github.com/laravel/framework/assets/3052854/66e81062-c725-42f4-acaf-8c19c732468c">

**Comment by Raza9798** [comment]
session table will be created only if you run the command `php artisan session:table`. what it does is generate a migration file for session. So whenever you do migrate it will be manipulated on database even you configure the `SESSION_DRIVER`

**Comment by jameswagoner** [comment]
I did not run `php artisan session:table` nor is there a migration file in `database/migrations`

**Comment by Raza9798** [comment]
can we check your repository?

**Comment by jameswagoner** [comment]
It's private but I will attempt a new one

**Comment by jameswagoner** [comment]
https://github.com/jameswagoner/laravel-11-sessions-table

**Comment by jameswagoner** [comment]
I guess an assumption got the best of me. L11 cleans up a lot of boilerplate but didn't think they combined migrations. Specially an opinionated one such as sessions.

Thanks for pointing that out.

**Comment by Raza9798** [comment]
> I guess an assumption got the best of me. L11 cleans up a lot of boilerplate but didn't think they combined migrations. Specially an opinionated one such as sessions.
> 
> Thanks for pointing that out.

You are welcome
