### ISSUE TITLE
The method throwUnless() does not exists in Http response class

### ISSUE THREAD

**Issue by akalongman** [laravel/framework#50345]
### Laravel Version

10.46.0

### PHP Version

8.2.15

### Description

The official documentation says we can use $response->throwUnless() method: https://laravel.com/docs/10.x/http-client#throwing-exceptions 
But the method `throwUnless()` does not exist in the `vendor/laravel/framework/src/Illuminate/Http/Client/Response.php` file.

### Steps To Reproduce

```php
<?php
use Illuminate\Http\Client\Response;
 
$response = Http::get('https://google.com');

$response->throwUnless(fn(Response $response) => $response->status() === 200);
```

**Comment by crynobone** [comment]
I cannot find any reference other than #45704 and #42556

It seems that the documentation was incorrect to refer `throwUnless()` to `Response` instead of the correct `PendingRequest`.

**Comment by driesvints** [comment]
We'd appreciate a PR to the docs for this one 👍
