### ISSUE TITLE
 Named parameter $api overwrites previous argument

### ISSUE THREAD

**Issue by parasshah438** [laravel/framework#50357]
### Laravel Version

11

### PHP Version

8.2

### Description

I publish the various route files in Laravel 11

php artisan install:api
php artisan install:broadcasting

its generate the 2 files inside routes folder (api.php and channels.php)

For testing purposes, I deleted that api.php and generated it again using php artisan install:api command 

then give that error on 

![pic1](https://github.com/laravel/framework/assets/47562591/fcfae867-e1d0-43b4-adbe-0025df3262d4)

![pic2](https://github.com/laravel/framework/assets/47562591/c0b13070-507f-485f-9e57-8bcc969ed0e8)

![pic3](https://github.com/laravel/framework/assets/47562591/5a89ea89-9136-4363-b362-052f6daae09d)

Error: Named parameter $api overwrites previous argument in C:\wamp64\www\lara11\bootstrap\app.php on line 11

### Steps To Reproduce

I also found solution for that

Open app.php and remove this line

api: __DIR__.'/../routes/api.php',

then working perfectly

**Comment by driesvints** [comment]
Seems like you ran the `install:api` command twice? That's not something that's expected and can work properly. You usually only run that once.

**Comment by parasshah438** [comment]
> Seems like you ran the `install:api` command twice? That's not something that's expected and can work properly. You usually only run that once.

@driesvints
Yes I know installed API command only has one-time execution but for testing purposes, i executed that command again.

**Comment by parasshah438** [comment]
> Seems like you ran the `install:api` command twice? That's not something that's expected and can work properly. You usually only run that once.

Yes I know installed API command only has one time execution but for testing purposes, i executed that command again.

**Comment by nunomaduro** [comment]
I was unable to reproduce it.
