### ISSUE TITLE
Better SQL server documentation

### ISSUE THREAD

**Issue by HenkPoley** [laravel/framework#50388]
### Laravel Version

9.32.16

### PHP Version

8.0.30

### Database Driver & Version

Microsoft SQL Server 2019 (RTM-CU24) - 15.0.43445.5

### Description

(Versions are unrelated, merely the ones I'm using.)

Just vouching for my Laravel documentation update here: https://github.com/laravel/docs/pull/9459

But in case you want me to move this additional documentation to \Illuminate\Database\Connectors\SqlServerConnector->getSqlSrvDsn() 👍 

https://github.com/laravel/framework/blob/c4e8cf5d7e0a4a5f5621e979a07c1ed9167a6e33/src/Illuminate/Database/Connectors/SqlServerConnector.php#L125..L192

Or maybe the `config/database.php` stub.

Now is the right time to mention that.

### Steps To Reproduce

Don't find MultiSubnetFailover documented in Laravel. So I failed to set it on my MS SQL Server connection.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
