### ISSUE TITLE
Sqs Job: VisibilityTimeout value is zero and type is string instead integer

### ISSUE THREAD

**Issue by nepos87** [laravel/framework#50397]
### Laravel Version

5.5

### PHP Version

7.4

### Description

Using Laravel 5.5 and processing a job with AWS Sqs, only if I have an error during processing, the queue returns the following error message:

**_ErrorException: The provided type for VisibilityTimeout value was string. The modeled type is integer. in C:\Users\Win\public_html\project\vendor\aws\aws-sdk-php\src\QueryCompatibleInputMiddleware.php:173_**

This happens without any changes to the source code compared to a couple of months ago when everything was working correctly.
In particular, within the Laravel SqsJob.php file, in the following function, the variable $delay is equal to 0 (i.e. it arrives with a value of zero and does not take the default one in brackets) but with a string data type instead of an integer:

```
public function release($delay = 0)
     {
         echo gettype($delay); // string instead integer

         parent::release($delay);

         $this->sqs->changeMessageVisibility([
             'QueueUrl' => $this->queue,
             'ReceiptHandle' => $this->job['ReceiptHandle'],
             'VisibilityTimeout' => $delay,
         ]);
     }
```
But within the aws control panel the queue is set to the default value of 30 seconds in Visibility Timeout. Despite this, the $delay parameter in function arrives with a value of zero and in string format instead of integer.

### Steps To Reproduce

1. Create a Job with Queue
2. Simulate an error inside the Job
3. The Job failed and return the error message (ErrorException: The provided type for VisibilityTimeout value was string. The modeled type is integer.)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
