### ISSUE TITLE
Better SQL server documentation

### ISSUE THREAD

**Issue by HenkPoley** [laravel/framework#50390]
### Laravel Version

10

### PHP Version

8.2

### Database Driver & Version

Microsoft SQL Server 2019 (RTM-CU24) - 15.0.43445.5

### Description

Just vouching for my Laravel documentation update here: https://github.com/laravel/docs/pull/9459

But in case you want me to move this additional documentation to \Illuminate\Database\Connectors\SqlServerConnector->getSqlSrvDsn() 👍 

https://github.com/laravel/framework/blob/c4e8cf5d7e0a4a5f5621e979a07c1ed9167a6e33/src/Illuminate/Database/Connectors/SqlServerConnector.php#L125..L192

Or maybe the `config/database.php` stub.

Now is the right time to mention that.

### Steps To Reproduce

Don't find MultiSubnetFailover documented in Laravel. So I failed to set it on my MS SQL Server connection.

**Comment by driesvints** [comment]
Please just add any info you want on the above PR.
