### ISSUE TITLE
when installing jetstream found illuminate/console[v10.17.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require

### ISSUE THREAD

**Issue by tamilventhan** [laravel/framework#50416]
### Laravel Version

11.x

### PHP Version

8.2

### Database Driver & Version

mysql, windows11

### Description

PS C:\laragon\www\chitmaster> composer require laravel/jetstream                        
Using version ^4.3 for laravel/jetstream
./composer.json has been updated
Running composer update laravel/jetstream
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/jetstream ^4.3 -> satisfiable by laravel/jetstream[v4.3.0, v4.3.1, 4.x-dev].
    - laravel/jetstream[v4.3.0, ..., 4.x-dev] require illuminate/console ^10.17 -> found illuminate/console[v10.17.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/jetstream:*" to figure out if any version is installable, or "composer require laravel/jetstream:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
PS C:\laragon\www\chitmaster> 

### Steps To Reproduce

try to install jetstream by composer require laravel/jetstream   
will get below error

  Problem 1
    - Root composer.json requires laravel/jetstream ^4.3 -> satisfiable by laravel/jetstream[v4.3.0, v4.3.1, 4.x-dev].
    - laravel/jetstream[v4.3.0, ..., 4.x-dev] require illuminate/console ^10.17 -> found illuminate/console[v10.17.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/jetstream:*" to figure out if any version is installable, or "composer require laravel/jetstream:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
PS C:\laragon\www\chitmaster>

**Comment by driesvints** [comment]
Jetstream will receive a new major release for Laravel v11. Right now you need to do `composer require laravel/jetstream:dev-master`
