### ISSUE TITLE
Php Attribute ObservedBy doesn't take in account observables added in Traits

### ISSUE THREAD

**Issue by comhon-project** [laravel/framework#50410]
### Laravel Version

10.47.0

### PHP Version

8.2

### Description

When using PHP Attribute `ObservedBy` to observe my model (instead of register the observer in the `EventServiceProvider`), "custom" observables added through the `initialize{Trait}` using `addObservableEvents` are not taken in account.

(when I use `EventServiceProvider` to register the observer, it works well).

my investigation : 
When using `ObservedBy`, "custom" observables are not registered because when entering in `HasEvents::observe` for the first time, the Model is booting (and already tagged as booted in `Model::$booted`). And the instanciated model in `HasEvents::observe` line 67 (`$instance = new static;`) will not boot the model because it is already booting.

Conversely when we register the observer in `EventServiceProvider` we directly call `HasEvents::observe` and the previously mentioned `$instance = new static;` boot the model and can register "custom" observables.

### Steps To Reproduce

create a model that use `ObservedBy`
```PHP
#[ObservedBy([MyObserver::class])]
class MyModel extends Model
{
    use MyTrait;
    
    ...
}
```

create a trait that use `addObservableEvents`
```PHP
trait MyTrait
{
    public function initializeMyTrait()
    {
        $this->addObservableEvents('canceling');
    }

    /**
     * to easily fire the event for debugging
     */
    public function fireCanceling()
    {
        $this->fireModelEvent('canceling');
    }
}
```
create the observer `MyObserver`
```PHP
class MyObserver
{
    public function canceling(MyModel $myModel)
    {
        var_dump('triggered canceling');
    }
}
```
finally call `fireCanceling`
```PHP
$myModel = new MyModel();

$myModel->fireCanceling(); // doesn't call MyObserver::canceling
```

**Comment by comhon-project** [comment]
maybe a solution would be to not make the trait `HasEvents` bootable by removing `bootHasEvents`.
and call `HasEvents::observe` at the very begining of `bootIfNotBooted` method. Something like :
```PHP
    // there is certainly a better name
    protected static $observed = [];

    protected function bootIfNotBooted()
    {
        if (!isset(static::$observed[static::class])) {
            static::$observed[static::class] = true;
            static::observe(static::resolveObserveAttributes());
        }
        if (!isset(static::$booted[static::class])) {
            static::$booted[static::class] = true;

            $this->fireModelEvent('booting', false);

            static::booting();
            static::boot();
            static::booted();

            $this->fireModelEvent('booted', false);
        }
    }
    
    public static function clearBootedModels()
    {
        static::$booted = [];
        static::$observed = [];
        static::$globalScopes = [];
    }
```
I'm not very satisfy by this method... 
maybe instantiate the model during it's own instantiation was just a bad idea ?

**Comment by comhon-project** [comment]
> `canceling` isn't a model event?

As far as i know it's not.
Events are listed here.
```PHP
           [
                'retrieved', 'creating', 'created', 'updating', 'updated',
                'saving', 'saved', 'restoring', 'restored', 'replicating',
                'deleting', 'deleted', 'forceDeleting', 'forceDeleted',
            ],
```
Anyway, `canceling` was Just an exemple, I could have put `foo`

**Comment by comhon-project** [comment]
Maybe I have another better solution. As I said in my first proposition, do not make the trait HasEvents bootable by removing bootHasEvents.
And just call `HasEvents::observe` at the very end of `boot` method or at the very end of `bootTraits` method.
This way all stuff that need to be initialized will be initialized before the model instantiation in the method `HasEvents::observe`

**Comment by ekmungai** [comment]
I have a similar but much simpler case to this. I'm using code copied directly from the docs
```
/**
     * The "booted" method of the model.
     */
    protected static function booted(): void
    {
        static::restoring(function (User $user) {
            dd($user);
        });
    }
```
But I'm getting this exception:

```
BadMethodCallException: Call to undefined method App\Models\User::restoring()

C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:67
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:36
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2334
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2346
C:\projects\hestia\app\Models\User.php:118
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:258
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:235
C:\projects\hestia\app\Models\User.php:78
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:770
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:417
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\GuardsAttributes.php:155
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:422
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:390
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:284
C:\projects\hestia\tests\Unit\UserTest.php:130
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestCase.php:61
```
So far as I can tell most of the other events are working properly except forceDeleting:

```
BadMethodCallException: Call to undefined method App\Models\User::forceDeleting()

C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:67
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:36
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2334
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2346
C:\projects\hestia\app\Models\User.php:118
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:258
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:235
C:\projects\hestia\app\Models\User.php:78
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:770
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:417
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\GuardsAttributes.php:155
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:422
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:390
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:284
C:\projects\hestia\tests\Unit\UserTest.php:130
C:\projects\hestia\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestCase.php:61
```
Could this be a bug?

**Comment by driesvints** [comment]
Looks like we're not going to undertake anything here, sorry.

**Comment by comhon-project** [comment]
@driesvints thank you for your reply.
I don't understand this choice, as I said in the issue description, when we register observer from `EventServiceProvider`, it works fine!
The two registration method (from PHP Attribute and form `EventServiceProvider`) should behave exactly the same (even with undocumented stuffs). 

The documentation says we can use both methods, implicitly that says it is the exact same behaviour.

IMHO either two methods must behave exactly the same, either the Php attribute method must be rollbacked.

**Comment by wlaskovic** [comment]
@comhon-project So if I'm getting it right, the ObservedBy attribute as it is, doesn't work, in laravel 10.x? Because I've run into this issue(v10.47), where the observable methods (deleted, updated, created, etc..) doesn't run.

**Comment by comhon-project** [comment]
@wlaskovic as far as I know it works for predifined events like created, deleted, etc... This issue concern "custom" observables defined through addObservable in Trait
