### ISSUE TITLE
Soft-deletion of Model does not trigger `deleted` event in Observer

### ISSUE THREAD

**Issue by hendurhance** [laravel/framework#50422]
### Laravel Version

10.0

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0.32 for macOS 14.3.1 on Apple Silicon (Homebrew)

### Description

When attempting to soft-delete a model that implements soft deletion (using Laravel's `SoftDeletes` trait), the `deleted` event defined in the model's observer does not fire as expected. This issue is encountered when using Laravel's built-in soft deletion functionality.

### Steps To Reproduce

1. Create a model with soft deletion enabled using Laravel's `SoftDeletes` trait.
2. Implement an observer for the model and define event handling methods (`deleted`, `restored`, etc.).
3. Soft-delete an instance of the model using the `delete()` method or a similar soft-deletion mechanism.
4. Observe that the deleted event defined in the model's observer does not fire.

**Comment by driesvints** [comment]
This event isn't fired when deleted. Instead `trashed` is fired.

**Comment by hendurhance** [comment]
The event `trashed` isn't fired either.

**Comment by hendurhance** [comment]
> This event isn't fired when deleted. Instead `trashed` is fired.

The event `trashed` isn't fired either.

**Comment by eozyo** [comment]
I am encountering the same issue, neither `delete`, `deleting`, `restore`, nor `restoring` are working, `update` and `updating` are, though.

### Laravel Version
11.9

### PHP Version
8.2.12

### Database Driver & Version
10.4.13-MariaDB on windows 10

**Comment by valerio-bozzolan** [comment]
> The event trashed isn't fired either.

I see that 5 persons are upvoting this problem. I can also reproduce this problem. Maybe useful to change the task title to "Cannot intercept trashing and trashed events for softdeletions" and reopen (?)
