### ISSUE TITLE
Illuminate\Validation\Rule::enum builder public methods do not expose methods except() and only()

### ISSUE THREAD

**Issue by thiagoszbarros** [laravel/framework#50438]
### Laravel Version

v10.44.0

### PHP Version

8.1

### Description

Illuminate\Validation\Rule::enum builder public methods do not expose methods except () and only().

While following https://laravel.com/docs/10.x/validation#rule-enum documentation to user Rule::enum to validate a input I think I found something wrong.

![image](https://github.com/laravel/framework/assets/88802518/561be2ad-0bd3-43bd-9871-afd39dc7f614)

As you can see in docs the sintax Rule::enum(Enum::class)->except([Enum:SOME_CASE]) or ->only([Enum:SOME_CASE]) is provided but when I try to use this, those methods just are not been exposed in public interface

![image](https://github.com/laravel/framework/assets/88802518/45f1ef4b-6b63-4c61-be8f-1db884b834cd)

### Steps To Reproduce

Create a new request class and add a Rule::enum(Enum::class)->except ([Enum:SOME_CASE]) or ->only([Enum:SOME_CASE]).

**Comment by seansch** [comment]
Looking at the commit those were added only 2 weeks ago to 10.46.0 I believe, you are on 10.44.0.

https://github.com/laravel/framework/commit/8d47be393e43ffeacd49556471110454f868da5f
