### ISSUE TITLE
Laravel mysql errors due to daylight savings?

### ISSUE THREAD

**Issue by amnah** [laravel/framework#50445]
### Laravel Version

^11.0

### PHP Version

PHP 8.3.3-1+ubuntu22.04.1+deb.sury.org+1 (cli) (built: Feb 15 2024 18:38:52) (NTS)

### Database Driver & Version

mysql  Ver 8.0.36-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

### Description

Hey,

I noticed this error in my logs last night. It seems like the queries failed because it was trying to update my table `updated_at` every minute from "2am-3am", which doesn't exist because time jumped instantly due to daylight savings. 

It happened on a command that runs every minute, which then publishes to a queue after finishing. So both the command and then subsequent queue job failed

is there any way to fix/prevent this?

Here are examples from my laravel.log:

---------
> [2024-03-10 02:00:06] production.ERROR: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:00:06' for column 'failed_at' at row 1 (Connection: mysql, SQL: insert into `failed_jobs` (`uuid`, `connection`, `queue`, `payload`, `exception`, `failed_at`) values (xxx)  PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:00:05' for column 'updated_at' at row 1 in /var/www/subreddit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:596

---------
> Next Illuminate\\Database\\QueryException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:58:05' for column 'updated_at' at row 1 (Connection: mysql, SQL: update `watcher` set `last_notification` = 1710039383, `watcher`.`updated_at` = 2024-03-10 02:58:05 where `user_id` = 1 and `page_id` in (1, 3)) in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:813

### Steps To Reproduce

I'm not sure how to reproduce, as daylight savings hour is over ... However, I can emulate it by typing it into artisan:

```$ php artisan tinker
Psy Shell v0.12.0 (PHP 8.3.3-1+ubuntu22.04.1+deb.sury.org+1 — cli) by Justin Hileman
> use App\Models\Watcher;
> $w = Watcher::first();
= App\Models\Watcher {#5235
    id: 1,
    user_id: 1,
    page_id: 1,
    search_term: "nvidia",
    active: 1,
    last_notification: 1710109696,
    created_at: "2024-03-03 16:40:02",
    updated_at: "2024-03-10 22:35:04",
  }

> $w->updated_at = "2024-03-10 02:10:00";
= "2024-03-10 02:10:00"

> $w->save();

   Illuminate\Database\QueryException  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:10:00' for column 'updated_at' at row 1 (Connection: mysql, SQL: update `watcher` set `watcher`.`updated_at` = 2024-03-10 02:10:00 where `id` = 1).```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by amnah** [comment]
I'm confused - this seems like an inherent laravel bug. My code is utilizing a basic laravel feature and failing due to an edge case (daylight savings).

This is my entire model file:

```
class Watcher extends Model
{
    use HasFactory;
    protected $fillable = [
        "user_id",
        "page_id",
        "search_term",
    ];
```
}

And the only thing I'm changing is:

```$watcher = Watcher::find();
$watcher->last_notification = $lastNotification;
$watcher->save();
```

And this fails because the built-in laravel timestamp feature is creating a value of `2024-03-10 02:00:05` which is invalid due to daylight savings.

This also happened to the other laravel built-in feature where it couldn't insert into the `failed_jobs` table. 

```[2024-03-10 02:00:06] production.ERROR: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:00:06' for column 'failed_at' at row 1 (Connection: mysql, SQL: insert into failed_jobs (uuid, connection, queue, payload, exception, failed_at) values (xxx) PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2024-03-10 02:00:05' for column 'updated_at' at row 1 in /var/www/subreddit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:596```

**Comment by amnah** [comment]
well for now, this seems to fix it

https://stackoverflow.com/questions/55084109/laravel-sqlstate22007-invalid-datetime-format-1292-incorrect-datetime-value/55084791#55084791

``` 
//config/database.php:

'mysql' => [
    // ...

    'timezone'  => '+00:00'
],
```
