### ISSUE TITLE
install:broadcasting always publishes Reverb Echo file

### ISSUE THREAD

**Issue by yoeriboven** [laravel/framework#50440]
### Laravel Version

11.x

### PHP Version

8.3

### Description

I'm using L11 with Pusher. 

When running `php artisan install:broadcasting` I opted out of installing Reverb. It still published `echo.js` with the Reverb configuration.

In [`Illuminate\Foundation\Console\BroadcastingInstallCommand`](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php) it doesn't seem to take this decision in account.

### Steps To Reproduce

Run `php artisan install:broadcasting` and don't install Reverb.

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/pull/50455#issuecomment-1989934688
