### ISSUE TITLE
Backward Compatibility Issue with SqlServerGrammar in Laravel 10.x for MS SQL Server 2016 and Earlier

### ISSUE THREAD

**Issue by bobonov** [laravel/framework#50457]
### Laravel Version

10.46.0

### PHP Version

8.3.3

### Database Driver & Version

MSSql 2016 via pdo/microsoft odbc 18 

### Description

The version of **lluminate\Database\Schema\Grammars\SqlServerGrammar** updated in Laravel 10.x introduces a backward compatibility issue with Microsoft SQL Server 2016 (version 13.0) and earlier versions. The problem arises due to the **compileIndexes()** and **compileForeignKeys()** methods now using the **STRING_AGG()** function, which is not available in Microsoft SQL Server versions prior to 2017. This change leads to "_is not a recognized built-in function name_" error.

### Steps To Reproduce

Create a schema on MSsql server 2016 or earlier and try to use on it **compileIndexes()** and **compileForeignKeys()**
or just simply try to run any query that contains STRING_AGG() in query console

**Comment by crynobone** [comment]
Thanks @staudenmeir
