### ISSUE TITLE
Inquiry Regarding Application Behavior After Deleting Config Folder

### ISSUE THREAD

**Issue by RealMrHex** [laravel/framework#50483]
### Laravel Version

11

### PHP Version

8.3

### Description

I am reaching out with a query related to the framework. I have noticed that when the "config" folder is deleted from an application, it results in a crash. I am curious to understand the technical reasons behind this behavior.

Additionally, I have observed that an empty "config" folder is necessary for the application to run smoothly, even when no configuration files are being overridden. I am interested in understanding the purpose of requiring an empty "config" folder in such cases.

If you could provide insights into these aspects, it would greatly assist in enhancing my understanding of the framework's inner workings.

Warm regards.

### Steps To Reproduce

1. create a new laravel project
2. delete config folder
3. crash happened.

**Comment by nunomaduro** [comment]
Hi! You should not delete the configuration files that come with a fresh Laravel application.

**Comment by RealMrHex** [comment]
@nunomaduro i knew it but why?

i changed the code in [`src/Illuminate/Foundation/Application.php`](https://github.com/laravel/framework/blob/ee0c5f315c9a4886f4d7ea475998890e75b0b63c/src/Illuminate/Foundation/Application.php#L484-L487)

from:
```php
    /**
     * Get the path to the application configuration files.
     *
     * @param  string  $path
     * @return string
     */
    public function configPath($path = '')
    {
        return $this->joinPaths($this->configPath ?: $this->basePath('config'), $path);
    }
```

to this:
```php
    /**
     * Get the path to the application configuration files.
     *
     * @param  string  $path
     * @return string
     */
    public function configPath($path = '')
    {
        $configPath = $this->joinPaths($this->configPath ?: $this->basePath('config'), $path);

        if (!is_dir($configPath))
            $configPath = __DIR__ . '/../../../config';

        return $configPath;
    }
```

and the problem solved, is there any technical reason behind of the empty config directory?
