### ISSUE TITLE
Laravel 11 can't get the UTC timestamp

### ISSUE THREAD

**Issue by jevantang** [laravel/framework#50490]
### Laravel Version

11.0.0

### PHP Version

8.2.16

### Database Driver & Version

MySQL 5.7.44 for Ubuntu 22

### Description

I've tried three methods and I can't get the UTC+0 timestamp.

The time value is correct until it is converted to a timestamp.

Laravel 10 was valid code, upgrading to 11 caused problems. No server environment has been changed.

### Steps To Reproduce

```php
$now = now('UTC');
$nowTimestamp = $now->getTimestamp();
```

```php
$nowTimestamp = time();
```

```php
$now = now('UTC');
$nowTimestamp = strtotime($now);
```

**Comment by driesvints** [comment]
@jevantang what Carbon version are you using?

**Comment by jevantang** [comment]
> @jevantang what Carbon version are you using?

name     : nesbot/carbon
versions : * 3.0.2
released : 2024-02-06, 1 month ago

**Comment by Muetze42** [comment]
`now()->timestamp`

**Comment by akr4m** [comment]
<img width="448" alt="image" src="https://github.com/laravel/framework/assets/17238742/42fc785a-5c68-41b4-85f1-9559841870bd">


<img width="245" alt="image" src="https://github.com/laravel/framework/assets/17238742/1ceac350-61c7-45ed-87cd-f1a6d6cc3a74">

@Muetze42

**Comment by driesvints** [comment]
You'll have to report this to the carbon repo as we don't control that code sorry.

**Comment by Muetze42** [comment]
The timestamp is correct, isn't it?

![image](https://github.com/laravel/framework/assets/26193232/b272881c-82fb-4c04-b730-db31c7e7675a)

**Comment by jevantang** [comment]
> The timestamp is correct, isn't it?
> 
> ![image](https://private-user-images.githubusercontent.com/26193232/312233954-b272881c-82fb-4c04-b730-db31c7e7675a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzY5NDEsIm5iZiI6MTcxMDI3NjY0MSwicGF0aCI6Ii8yNjE5MzIzMi8zMTIyMzM5NTQtYjI3Mjg4MWMtODJmYi00YzA0LWI3MzAtZGIzMWM3ZTc2NzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDIwNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNWY4YjgzNzFhNzQ1NmIzNmY0OTIwMDIwYjYwZWY0MDRkMzFiZTAyNmE1MjUyYjNkNzgwODE4NDRmZTVkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CTjUrasZEm-J2-5kXiypqf9m5yZ3CNA8NXAwsVoHfhs)

@Muetze42 

1710276559 -> `2024-03-13 04:49:19`
Current UTC+0 Time `2024-03-12 20:49:19`

**Comment by jyxjjj** [comment]
> 1710276559 ->`2024-03-13 04:49:19`

@jevantang How do you convert it?
1710276559 is equals to `20:49:19`.
Timestamp has no timezone it always `UTC+0000`. where is the `8`?

**Comment by kylekatarnls** [comment]
> You'll have to report this to the carbon repo as we don't control that code sorry.

For the record, this issue is not related to Carbon since `time()` is giving the same value.
