### ISSUE TITLE
Recent updates are incompatible with PHP 8.1.x due to some symfony/* 7.x dependencies

### ISSUE THREAD

**Issue by spasibych** [laravel/framework#50491]
### Laravel Version

10.48.2

### PHP Version

8.1.27

### Description

Composer generates fatal error in vendor/composer/platform_check.php script due to some symfony/* 7.x dependencies

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.27.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.27. in ~/laravel10/vendor/composer/platform_check.php on line 24
```

Example dependency from vendor/composer/installed.json

```
{
    "name": "symfony/css-selector",
    "version": "v7.0.3",
    ...
    "require": {
        "php": ">=8.2"
    },
    ...
},
```

### Steps To Reproduce

composer create-project laravel/laravel laravel10 10.*
cd laravel10
php8.1 artisan test

**Comment by driesvints** [comment]
Please do not start new projects on Laravel v10 any more.

**Comment by spasibych** [comment]
@driesvints needed to support existing projects on Laravel 10, above is just a simple demonstration of the problem.

**Comment by driesvints** [comment]
You’re having this issue on a Laravel 10 project? What’s your composer.json?

**Comment by spasibych** [comment]
@driesvints here are all the PHP dependencies of my composer.json

```
  "require": {
        "php": "^8.1",
        "bacon/bacon-qr-code": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/tinker": "^2.8",
        "pragmarx/google2fa-laravel": "^2.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
```
There is also a problem with updating the PHP version in production.

I understand well what to do if the problem is not solved. However, I am surprised by the violation of this rule of backward compatibility. It will also be difficult to explain to the project management ))

**Comment by crynobone** [comment]
Can you run `composer why symfony/css-selector` and share the full output.

**Comment by spasibych** [comment]
@crynobone all problematic symfony/* 7.x dependencies

composer why symfony/css-selector
```
tijsverkoyen/css-to-inline-styles v2.2.7 requires symfony/css-selector (^2.7 || ^3.0 || ^4.0 || ^5.0 || ^6.0 || ^7.0)
```

composer why symfony/event-dispatcher
```
symfony/console     v6.4.4 conflicts symfony/event-dispatcher (<5.4)
symfony/http-kernel v6.4.5 requires  symfony/event-dispatcher (^5.4|^6.0|^7.0)
symfony/mailer      v6.4.4 requires  symfony/event-dispatcher (^5.4|^6.0|^7.0)
```

composer why symfony/string
```
symfony/console v6.4.4 requires symfony/string (^5.4|^6.0|^7.0)
```

**Comment by crynobone** [comment]
Only `symfony/css-selector` get installed with v7, this can happened when composer uses PHP 8.2 and later you attempt to use it with PHP 8.1, If you have requirements to run composer project using different version than the default local PHP version you should consider locking the version using platform config: https://mikemadison.net/blog/2020/11/17/configuring-php-version-with-composer

**Comment by spasibych** [comment]
Thanks everyone, I realized my mistake, this is the first time I've come across this.

Ran everything from "php8.1 /usr/local/bin/composer ..." and all dependencies were installed compatible with PHP 8.1.x
