### ISSUE TITLE
Exception when try to create a Controller without the base abstract Controller

### ISSUE THREAD

**Issue by devajmeireles** [laravel/framework#50494]
### Laravel Version

11.0.3

### PHP Version

8.2.16

### Database Driver & Version

SQLite

### Description

Starting from the Laravel 11 we can delete the base abstract Controller and remove all extends, the application will continue work without any error, but when we do that we have an error when we try to create a new controller by using the Artisan. 

![CleanShot 2024-03-12 at 20 10 05](https://github.com/laravel/framework/assets/60591772/bd3c984d-90f5-41de-ba0b-ddfd6b3ecb55)

The question is: the base abstract Controller is mandatory or not? If the answer to this question is not, then this exception is wrong.

### Steps To Reproduce

1. Prepare a fresh Laravel 11 application
2. Delete the base abstract Controller
3. Try to create a new controller by using Artisan

**Comment by crynobone** [comment]
![CleanShot 2024-03-13 at 08 27 22](https://github.com/laravel/framework/assets/172966/f32f46cd-741d-419f-92aa-63c724f3a269)

Unable to recreate the issue.

**Comment by devajmeireles** [comment]
I created a fresh Laravel 11 and the same error happened.

![CleanShot 2024-03-12 at 22 52 00](https://github.com/laravel/framework/assets/60591772/d8550945-1095-4c94-9b4b-2eadd75c562b)

I was only able to create a new controller without the base abstract Controller when I ran:

```bash
composer dump-autoload
```

I think this is happening because Laravel 11 uses `class_exists` to check if the Controller file exists. I will suggest a PR that uses `file_exists`, because if this file is moved, the base abstract controller will not be used anyway since the code uses a hard-coded reference to this file: 

https://github.com/laravel/framework/blob/eac3418dd5ff5c11dbaefee25038a734582f283a/src/Illuminate/Routing/Console/ControllerMakeCommand.php#L130

**Comment by driesvints** [comment]
I was able to reproduce this. We should indeed do the `file_exists` check.

**Comment by devajmeireles** [comment]
> I was able to reproduce this. We should indeed do the `file_exists` check.

Thanks for the PR. I forgot to do that yesterday! 😅
