### ISSUE TITLE
RPC failed; curl 18 Transferred a partial file: Laravel 11.x install error

### ISSUE THREAD

**Issue by phantomD92** [laravel/framework#50499]
### Laravel Version

11

### PHP Version

8.2.12

### Description

everyone. When I am trying to new laravel project, I got error.

composer create-project laravel/laravel example-app

or

composer global require laravel/installer

laravel new example-app

error
Creating a "laravel/laravel" project at "./remote-job" Installing laravel/laravel (v11.0.1) Failed to download laravel/laravel from dist: The zip extension and unzip/7z commands are both missing, skipping. The php.ini used by your command-line PHP is: E:\Xampp\php\php.ini Now trying to download from source

Syncing laravel/laravel (v11.0.1) into cache
In Git.php line 472:

Failed to execute git clone --mirror -- https://ghp...RWI:x-oauth-basic@github.com/laravel/laravel.git "C:/Users/[user]/AppData/Local/Composer/vcs/https---github.com-laravel-laravel.git/"

Cloning into bare repository 'C:/Users/[user]/AppData/Local/Composer/vcs/https---github.com-laravel-laravel.g it'... error: RPC failed; curl 18 Transferred a partial file error: 3200 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [ [ []]]

So I tryed with git config --global http.postBuffer 524288000 but it is same.

https://gist.github.com/enqtran/10e33674701967edd12c3cf224c835f8 https://github.com/ndmitchell/neil/issues/28

How can I fix this?

### Steps To Reproduce

composer create-project laravel/laravel example-app

or

composer global require laravel/installer

laravel new example-app

**Comment by me-shaon** [comment]
This is not a Laravel specific issue. Seems like it happened due to slow internet connection. 
Please check out the answers here: https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

**Comment by crynobone** [comment]
Thanks @me-shaon
