### ISSUE TITLE
Incorrect accessor value in `Model::toArray()` when a Model contains an accessor with the same name as a column and accessor name is added to  `Model::$appends`

### ISSUE THREAD

**Issue by liquid207** [laravel/framework#50501]
### Laravel Version

v10.47.0

### PHP Version

8.3.2

### Description

Suppose there is a MySQL table `users`, has a column `name` in this table. User Model Class like below:
```
class User
{
    protected $appends = [
        'name'
    ];

    public function getNameAttribute($value)
    {
        return strtoupper($value);
    }
}
```

Now, has one record (`id`: 1, `name`: 'Foo') in `users`,  Consider the following code:

```
User::find(1)->toArray()
```

Actual result: 
```
[
    "id" => 1,
    "name" => "",
  ]
```

Excepted result:

```
[
    "id" => 1,
    "name" => "Foo",
  ]
```

### Steps To Reproduce

1. Create a User like mentioned in the description
2. Run `User::find(1)->toArray()` in tinker

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
