### ISSUE TITLE
CacheManager repository function has changed signature in L11

### ISSUE THREAD

**Issue by noefleury** [laravel/framework#50508]
### Laravel Version

11.0.3

### PHP Version

8.3

### Description

From Laravel 11, the `CacheManager` [repository](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Cache/CacheManager.php#L289) function has changed signature. This wasn't like that in[ Laravel 10](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Cache/CacheManager.php#L280).

As there is nothing about that in the [upgrade guide](https://laravel.com/docs/11.x/upgrade#cache), I think that we should add an empty array as default `config` attribute.

### Steps To Reproduce

Just call the `CacheManager` _repository_ function without the second argument.

**Comment by driesvints** [comment]
Seems you already sent in a PR so let's see how that goes. Thanks!
