### ISSUE TITLE
Breaking feature about command and Exception

### ISSUE THREAD

**Issue by jyxjjj** [laravel/framework#50500]
### Laravel Version

11.0.3

### PHP Version

8.3.2

### Description

In `upgrading from 10.x to 11.x`:

> However, we do not recommend that Laravel 10 applications upgrading to Laravel 11 attempt to migrate their application structure, as Laravel 11 has been carefully tuned to also support the Laravel 10 application structure.

I don't know if it is on purpose or accidentally.

### Steps To Reproduce

```
(new ApplicationBuilder(new Application(dirname(__DIR__))))
    ->withKernels()
    ->withEvents()
    ->withCommands()
    ->withProviders()
    ->withRouting(fn() => defineRoutes())
    ->withExceptions()
    ->create()
```

In `withCommands`, without `singleton`.
In `withExceptions`, with `singleton`.
`app/Console/Kernel.php` will not be loaded:
```
    protected function schedule(Schedule $schedule): void
    {
        dump('schedule');
```
then run `php artisan schedule:list`:
```
INFO  No scheduled tasks have been defined.  
```
without `"schedule" //xxx.php:xxx`.

**Comment by jyxjjj** [comment]
I don't know if i am right but:

```
    ->withSingletons(
        [Illuminate\Contracts\Console\Kernel::class => Kernel::class]
    )
```
useless too.

**Comment by jyxjjj** [comment]
@crynobone I don't understand your words... `Application::configure(dirname(__DIR__))` has the same appearance. Can you just explain?

**Comment by jyxjjj** [comment]
#50755
I don't know why my "issue" was rejected and you continue to do this.

**Comment by crynobone** [comment]
See https://laravel.com/docs/11.x/upgrade#application-structure
