### ISSUE TITLE
Migration command failed

### ISSUE THREAD

**Issue by Raza9798** [laravel/framework#50518]
### Laravel Version

11.0

### PHP Version

8.2.12

### Database Driver & Version

mysql  Ver 15.1 Distrib 10.4.32-MariaDB, for Win64 (AMD64)

### Description

Migration getting failed on Laravel version 11
composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "laravel/framework": "^11.0",
        "laravel/tinker": "^2.9"
    },
```

### Steps To Reproduce

I have created a project using composer command `composer create-project laravel/laravel example-app` and configured the .env file's database inorder to work with database default configuration has following variables
```
DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=laravel
# DB_USERNAME=root
# DB_PASSWORD=
```

I have configured as follows

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=ex11
DB_USERNAME=root
DB_PASSWORD=
```

when ever i run the migration command it ask to create the database when i input yes it throws an error as follows
![image](https://github.com/laravel/framework/assets/59387235/8a35f73a-50cb-44e0-90a6-cf07daee59aa)

If i manually create a database as `ex11` on mysql it shows following error
![image](https://github.com/laravel/framework/assets/59387235/0343c542-107c-47cb-86c9-5dd280a8c472)

**Comment by shengslogar** [comment]
This looks better suited to be a discussion question as it doesn't appear to be a framework bug. I've never used MariaDB with the MySQL driver before, although theoretically it should work. The last screenshot is telling you the issue. Have you tried changing the collation mode inside your `database.php` config?

**Comment by hafezdivandari** [comment]
You are trying to use MariaDB driver with `mysql` connection? have you tried `DB_CONNECTION=mariadb` instead?

**Comment by Raza9798** [comment]
changing driver to `DB_CONNECTION=mariadb` works
