### ISSUE TITLE
Installing broadcasting doesn't add routes to bootstrap/app.php if routes/channels.php file exists

### ISSUE THREAD

**Issue by colincameron** [laravel/framework#50513]
### Laravel Version

11

### PHP Version

8.3

### Description

After updating the application skeleton files to those included with Laravel 11, I ran `php artisan install:broadcasting` as instructed in https://laravel.com/docs/11.x/broadcasting#installation

However, the broadcast routes were not registered in bootstrap/app.php as I already had the routes/channels.php file.

The `install:broadcasting` command does not add the routes to bootstrap/app.php if the channels.php file already exists: https://github.com/laravel/framework/blob/eac3418dd5ff5c11dbaefee25038a734582f283a/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php#L53

I believe `$this->uncommentChannelsRoutesFile();` should be called regardless of whether the channels.php file exists or not, and a check added to `$this->uncommentChannelsRoutesFile();` to prevent duplication.

### Steps To Reproduce

- Have existing Laravel 10 app that uses broadcasting
- Upgrade application to Laravel 11 including new bootstrap/app.php file
- Run php artisan install:broadcasting to re-enable broadcasting
- The expected changes to bootstrap/app.php are not made

**Comment by nunomaduro** [comment]
Fixed https://github.com/laravel/framework/pull/50519.
