### ISSUE TITLE
Migration Unknown collation on mariadb driver

### ISSUE THREAD

**Issue by Raza9798** [laravel/framework#50526]
### Laravel Version

11.0

### PHP Version

8.2.12

### Database Driver & Version

mysql Ver 15.1 Distrib 10.4.32-MariaDB, for Win64 (AMD64)

### Description

composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "laravel/framework": "^11.0",
        "laravel/tinker": "^2.9"
    },
```

### Steps To Reproduce

env configuration `DB_CONNECTION` is set to `mariadb`
```
DB_CONNECTION=mariadb
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=ex11
DB_USERNAME=root
DB_PASSWORD=
```
when run the migration command `php artisan migrate` 
`Unknown collation on mariadb driver` following issue occuring
![image](https://github.com/laravel/framework/assets/59387235/cafaa039-a823-4657-a647-9d3ae1600bfd)

Table is not migrating

**Comment by driesvints** [comment]
We fixed this in latest version of skeleton: https://github.com/laravel/laravel/releases/tag/v11.0.2
