### ISSUE TITLE
Laravel 11 Can't create nor connect to MySQL on Install

### ISSUE THREAD

**Issue by AllTheUserNamesAreGone** [laravel/framework#50536]
### Laravel Version

11.0.2

### PHP Version

8.3.3

### Description

Trying to install the new Laravel 11 for the first time and can not get it to connect to mysql. Have tried to create the DB manually and it fails and running php artisan migrate, where it asks to create the DB Laravel_11 as it correctly says that it doen't exist and gives: 

SQLSTATE[HY000] [1049] Unknown database 'laravel_11' (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'laravel_11' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)

I have set the ENV variables which work fine for Laravel 10 and before. I have tried to create the DB manually and still doesn't work.
<img width="979" alt="Screenshot 2024-03-13 at 20 32 33" src="https://github.com/laravel/framework/assets/163350445/e31f18b9-947a-4343-8099-6c7bd1fbd560">

### Steps To Reproduce

Laravel install Laravel_11

Install Jetstream and Livewire
Add Email verification and Dark

No to run migrations

Pick mysql as DB

**Comment by MNhat0308** [comment]
same issue

**Comment by subhananam** [comment]
facing the same issue using PHP 8.2.12 and Laravel 11.0.2 , select breeze using react

**Comment by crynobone** [comment]
Can you try with the following configuration:

```ini
DB_COLLATION=(null)
```

**Comment by driesvints** [comment]
Please fill out your database driver and engine version and don't leave that field blank.

**Comment by AllTheUserNamesAreGone** [comment]
> Can you try with the following configuration:
> 
> ```ini
> DB_COLLATION=(null)
> ```

This fixed it for me. Thank you.

**Comment by moerphie** [comment]
Same issue, with a slightly different error log:
``` SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'laravel_db' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name) ```

**Comment by AllTheUserNamesAreGone** [comment]
> Please fill out your database driver and engine version and don't leave that field blank.



> Please fill out your database driver and engine version and don't leave that field blank.

Mysql - Ver 14.14 Distrib 5.7.39, for osx10.12 (x86_64)

**Comment by cyberfab007** [comment]
![Screenshot 2024-05-09 061534](https://github.com/laravel/framework/assets/10542398/110911f2-a929-44d8-bfa1-78d689916c8d)
Still getting this error, MySQL latest, Laravel 11 latest, going back to 10

**Comment by cyberfab007** [comment]
DB_COLLATION=utf8mb4_unicode_ci 
MYSQL_VERSION=latest
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=6033
DB_DATABASE=app_db
DB_USERNAME=root
DB_PASSWORD=my_secret_password

**Comment by driesvints** [comment]
That's not the installer? Try a support channel for your issue:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
