### ISSUE TITLE
create new laravel 11 project, still using phpunit, not pest

### ISSUE THREAD

**Issue by khannedy** [laravel/framework#50543]
### Laravel Version

^11.0

### PHP Version

8.3

### Description

Create laravel project using composer still using PHPUnit as default test framework, not using Pest

### Steps To Reproduce

`composer create-project laravel/laravel:^11.0 example-app`

![CleanShot 2024-03-14 at 13 08 57](https://github.com/laravel/framework/assets/70091/03eff9b8-0456-422b-a408-0b8ea6e55bc6)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by devajmeireles** [comment]
This isn't an issue, but the default tests are still in PhpUnit. Wouldn't it be correct to migrate the base tests to Pest since Taylor announced Pest as the standard testing framework, @crynobone ?

@khannedy Use the Pest drift plugin and migrate your tests to Pest when you creates a new Laravel project using Composer.

1. `composer require pestphp/pest-plugin-drift --dev`
2. `./vendor/bin/pest --drift`

**Comment by Jubeki** [comment]
If you use the Laravel Installer (`^5.6`) to install a fresh Laravel Application, you get Pest tests. Or are you talking about the `phpunit.xml` which still exists?

**Comment by devajmeireles** [comment]
> If you use the Laravel Installer (`^5.6`) to install a fresh Laravel Application, you get Pest tests. Or are you talking about the `phpunit.xml` which still exists?

In this case, we are talking about creating Laravel projects through Composer.

**Comment by Jubeki** [comment]
Well than that is to be expected, because the Laravel Installer is responsible for configuring everything correctl like Starter Kits, Database, Testing Framework, etc.

**Comment by desertbynight** [comment]
Yes I was surprised too not to find Pest since it should be "out of the box" (documentation). I installed Laravel using Laravel Sail.

**Comment by Psypher1** [comment]
Was this ever solved because I also have phpunit instead of pest
