### ISSUE TITLE
Reverted PR 50403 (#50482) is missing in Illuminate/view Package

### ISSUE THREAD

**Issue by Mathias-Witt** [laravel/framework#50576]
### Laravel Version

v10.48.2

### PHP Version

8.2.16

### Description

It looks like that the reverted PR 50403 (#50482) is missing in illuminate/view Package
https://github.com/illuminate/view/blob/v10.48.2/Compilers/ComponentTagCompiler.php#L261 

### Steps To Reproduce

if you require  ```composer require illuminate/view:v10.48.2``` you get the non reverted version.

**Comment by driesvints** [comment]
Heya. Investigating.

**Comment by driesvints** [comment]
I tried tagging v10.48.3 and that seems to have done the trick. Can you try again?

**Comment by Mathias-Witt** [comment]
@driesvints works fine now, thanks a lot! 🚀 
have a nice weekend ....
