### ISSUE TITLE
it doesn't log arabic request into log file

### ISSUE THREAD

**Issue by joukhar** [laravel/framework#50571]
### Laravel Version

v10.48.2

### PHP Version

PHP 8.2.16

### Description

i use a request logger to log errors
and the framework converts arabic characters into unicode 
example: 
```php
  "RESPONSE": "{\"success\":false,\"message\":\"\\u0627\\u0644\\u0628\\u064a\\u0627\\u0646\\u0627\\u062a \\u062e\\u0627\\u0637\\u0626\\u0629.\"}",
  "LOCALE": "ar"
```

### Steps To Reproduce

```php
        $response = response()->json(['message' => 'صباح الخير']);
        Log::error($response->getContent());
```

**Comment by Jurager** [comment]
Nothing unusual, JSON always uses the Unicode character set. See RFC 8259. Nothing wrong with this, use json_decode.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
