### ISSUE TITLE
Set integer queue config

### ISSUE THREAD

**Issue by ArtyshkoAndrey** [laravel/framework#50579]
### Laravel Version

11.0.6

### PHP Version

8.3.3

### Description

Pls set (int) by default config: queue.connection.redis.retry_after.
But set int number in env file, php env() getting string. After start queue:work call crash carbon.

'retry_after' => (int) env('REDIS_QUEUE_RETRY_AFTER', 90),

### Steps To Reproduce

Create new project. Set config. Set number 90. But Laravel get “90”

**Comment by driesvints** [comment]
Thanks. I've sent in PR's to fix this but that's only for new installs. You'll have to add the integer cast like you suggested.
