### ISSUE TITLE
Unknown character set

### ISSUE THREAD

**Issue by jeffdv** [laravel/framework#50577]
### Laravel Version

11.0.6

### PHP Version

8.3.4

### Database Driver & Version

MariaDB-1:11.3.2

### Description

I created a fresh new laravel project and I'm trying to run php artisan migrate.
This gives me the following error:

Syntax error or access violation: 1115 Unknown character set: 'utf8mb4¾' (Connection: mariadb, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'xxx' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)

This is in my ENV:
DB_CONNECTION=mariadb
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=database
DB_USERNAME=root
DB_PASSWORD=root

### Steps To Reproduce

Create a new project and run php artisan migrate

**Comment by driesvints** [comment]
Please provide very detailed steps to reproduce this. Exact commands and choices made when running install commands. Thanks!

**Comment by jeffdv** [comment]
I'm just an idiot. Has nothing to do with Laravel.
I had sqlite disabled in my php, this threw an error while running 

composer create-project laravel/laravel:^11.0 example-app

Enabled it and all the problems are gone
