### ISSUE TITLE
Does not install breeze with api when routes directory does not exist

### ISSUE THREAD

**Issue by MrShnaider** [laravel/framework#50586]
### Laravel Version

11.0.6

### PHP Version

8.3

### Description

I like to put my routes in a directory other than the default one. If you delete the `routes` directory and try to install breeze with the api, the installation is interrupted with an error.

I expect that when installing breeze, if the `routes` directory does not exist - it will simply be re-created and all the necessary files will fit into it. Then, in my case, I would further distribute them myself according to my architecture.

### Steps To Reproduce

1. Install laravel 11
2. Delete `/routes` directory
3. `composer require laravel/breeze --dev`
4. `php artisan breeze:install` with `api` option

Exception:
`copy(project-root/routes/api.php): Failed to open stream: No such file or directory`
`at vendor\laravel\framework\src\Illuminate\Foundation\Console\ApiInstallCommand.php:53`

**Comment by driesvints** [comment]
> I like to put my routes in a directory other than the default one. 

This is not something we support out of the box sorry. If you want, you can attempt a PR in a non breaking way.

**Comment by MrShnaider** [comment]
I made 2 PRs with fixes for this issue but they were closed. What could be the reason?
