### ISSUE TITLE
Route cache not generated correctly when using separated files

### ISSUE THREAD

**Issue by lucraraujo** [laravel/framework#50591]
### Laravel Version

10.48.3

### PHP Version

8.3.3

### Description

I like to separate my routes in multiple files and require_once all the files in, for example, web.php route file.
The problem is that the routes defined in files other them web do not cache when "artisan optimize" is called for the first time. The cache is generated correctly only if the command "artisan optimize" is executes for the second time.
The same behavior is observed when the command "artisan route:cache" is executed.

### Steps To Reproduce

Create a route file and write routes in it.
require_once the said file in web.php route file.
Run "php artisan optimize" for the first time.
Verify that the cache file generated DOES NOT contain the routes described in the separated file.
Run "php artisan optimize" for the second time.
Verify that the cache file generated DOES contain the routes described in the separated file.

**Comment by utqinadhif** [comment]
try to Route::group([], __DIR__.'/pages/auth/admin.php');

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
