### ISSUE TITLE
After installing Laravel version 11, database configuration no working properly as previous versions.

### ISSUE THREAD

**Issue by pabloripoll** [laravel/framework#50594]
### Laravel Version

11.0.6

### PHP Version

8.3.3

### Database Driver & Version

MariaDB 10.11

### Description

I'm using Makefile for the installation but it's the same. It executes:
```bash
$ composer create-project laravel/laravel:^11.0 .
```

![Screenshot from 2024-03-15 23-22-14](https://github.com/laravel/framework/assets/53290870/f6463cbe-22e2-484c-a8b2-7bf98b78b2bb)

![Screenshot from 2024-03-15 23-22-34](https://github.com/laravel/framework/assets/53290870/e5bce703-6e68-42a8-9d17-a4f2c56d9f59)

As you can see in the second screenshot, finishing installation runs migrations automatically.

Continuing to connect to the database I found a new order in the .env file regarding order of all of them. Also the app key is already set as usually doesn't.

![Screenshot from 2024-03-15 23-33-35](https://github.com/laravel/framework/assets/53290870/dea21a2f-925c-49c9-90cf-0bb834f917e0)

Without touching anything, it works showing welcome page.

But when changing .env database connection params, immediatly fails, just reloading home page with any controller set:

![Screenshot from 2024-03-15 23-36-21](https://github.com/laravel/framework/assets/53290870/514493cf-6417-48d6-8cb9-0de81784863b)

![Screenshot from 2024-03-15 23-35-40](https://github.com/laravel/framework/assets/53290870/80a0ee80-5216-420c-8307-b9d0924e8e6c)

After setting connection params correctly, it has another error. I think it's because of previous table migrations in SqlLite:

![Screenshot from 2024-03-15 23-43-44](https://github.com/laravel/framework/assets/53290870/e649fc5c-5874-44dc-8b05-b2021098aee9)

![Screenshot from 2024-03-15 23-44-14](https://github.com/laravel/framework/assets/53290870/23e2b616-4e97-4ff5-922b-f938e667764a)
 
Many directories, files and configurations are missing comparing with previous versions. Take a look:

![Screenshot from 2024-03-15 23-49-57](https://github.com/laravel/framework/assets/53290870/d5138008-8350-4a2f-aeee-5e65b1dd00ea)

### Steps To Reproduce

https://github.com/pabloripoll/docker-laravel-11-php-fpm-8

**Comment by devajmeireles** [comment]
> After setting connection params correctly, it has another error. I think it's because of previous table migrations in SqlLite:

That's obvious, isn't it? The first migration was performed in SQLite. If you change the database connection to a new connection, you must rerun the migrations on this new database:

```shell
php artisan migrate:fresh
```

> Many directories, files and configurations are missing comparing with previous versions. Take a look:

You probably don't know the new Laravel 11. I suggest you study it.

**Comment by dyriavin** [comment]
Hey 👋 

I don't think that problems that you've encountered related to Laravel. In your case, since you've changed `DB_CONNECTION` to be `mysql` from previous - mysql connection doesn't have any knowledge about the laravel project, since you haven't executed migrations with `php artisan migrate:fresh` 

I would highly recommend you checking out [these docs](https://laravel.com/docs/11.x/installation).

**Comment by pabloripoll** [comment]
Before anyone feeling to answer anything like the above two junior programmers comments, try installing previous Laravel versions.

I recorded Laravel 11 and 10 installation with composer to prove them the differences. Before version 11 the installation process have never run any migration automatically for obvious reasons that you don't have time even to set environment file.

[Screencast from 2024-03-17 14-18-27.webm](https://github.com/laravel/framework/assets/53290870/628ca3a2-0a71-423a-9d8f-f3f5c0145fa7)

**Comment by devajmeireles** [comment]
> Before anyone feeling to answer anything like the above two junior programmers comments, try installing previous Laravel versions.

I'm suspecting the junior here isn't us. Laravel 11 adopted SQLite as the default database, and because it is a simple file, Laravel 11 creates the file and performs the migrations. As I mentioned above, I say it again: study Laravel 11, as several changes are guiding the framework towards a new path with this new version.

> Many directories, files and configurations are missing comparing with previous versions.

This is proof that you are lost trying to find similarities between versions, without knowing the new Laravel 11.

**Comment by pabloripoll** [comment]
Ok, I see. Don't worry I'm not going to waste my time on downgraded releases. I'm just using this framework version for testing purposes as the market would request it - it won't.

With just saying "there's nothing wrong with the installation process - this is a new approach - read [this](https://laravel.com/docs/11.x/database#configuration)" would be enough.

Your childish manner shows your professional level - nothing more to say.

**Comment by devajmeireles** [comment]
> Ok, I see. Don't worry I'm not going to waste my time on downgraded releases. I'm just using this framework version for testing purposes as the market would request it - it won't.
> 
> With just saying "there's nothing wrong with the installation process - this is a new approach - read [this](https://laravel.com/docs/11.x/database#configuration)" would be enough.
> 
> Your childish manner shows your professional level - nothing more to say.

I'm glad to know that you understand that the error is on your side and not in the framework. You are free to judge me, but you cannot say that there is an error in something that you don't even understand.

**Comment by pabloripoll** [comment]
> > Ok, I see. Don't worry I'm not going to waste my time on downgraded releases. I'm just using this framework version for testing purposes as the market would request it - it won't.
> > With just saying "there's nothing wrong with the installation process - this is a new approach - read [this](https://laravel.com/docs/11.x/database#configuration)" would be enough.
> > Your childish manner shows your professional level - nothing more to say.
> 
> I'm glad to know that you understand that the error is on your side and not in the framework. You are free to judge me, but you cannot say that there is an error in something that you don't even understand.

I'm not judging you, I'm helping you. If you have comprehension problems is something you need to address:

Title says: "After installing Laravel version 11, database configuration no working properly as previous versions."

Issues I found (regarding the title):
- "But when changing .env database connection params, immediately fails, just reloading home page without* any controller set:"
This means that without setting any controller Laravel makes request to database. So on each loading request will consume connection resources - I couldn't image that Laravel team would decided to take this direction.

- "After setting connection params correctly, it has another error. I think it's because of previous table migrations in SqlLite:"
This means I know how to fix it.

I will continue answering to you until you answer respectfully. As I've already wrote:
With just saying "there's nothing wrong with the installation process - this is a new approach - read [this](https://laravel.com/docs/11.x/database#configuration)" would be enough.

**Comment by driesvints** [comment]
Please keep things civil in the future people.
