### ISSUE TITLE
docs for bootstrap directory needs update

### ISSUE THREAD

**Issue by ariaieboy** [laravel/framework#50593]
### Laravel Version

11

### PHP Version

8.3

### Description

the [bootstrap](https://laravel.com/docs/11.x/structure#the-bootstrap-directory) directory doc is outdated and need to get updated according to the new laravel 11 design. 
it says that `You should not typically need to modify any files within this directory.` but that's not true with laravel 11.

### Steps To Reproduce

-

**Comment by nunomaduro** [comment]
Fixed: https://github.com/laravel/docs/pull/9507.
