### ISSUE TITLE
Bus::batch()->dispatch always use DB_CONNECTION = sqlite

### ISSUE THREAD

**Issue by mnazmi23** [laravel/framework#50618]
### Laravel Version

11.0.7

### PHP Version

8.3.4

### Database Driver & Version

mysql/oracle

### Description

Hi, I have successfully upgraded my project to Laravel 11.

Everything went fine, until a user of mine trying to run a page that triggers a job batch(I have tested it, and it happens to all job batches.

This is the code,
`$batch = Bus::batch([
                    $main_jobs
                ])
                    ->name('timetable-batch-'.auth()->id().'-'.$request->faculty_filter)
                    ->dispatch();`

My database config, which has been working fine since Laravel 6.

> 'mysql' => [
>             'driver' => env('DATABASE_DRIVER', 'mysql'),
>             'url' => env('DATABASE_URL', ''),
>             'host' => env('DB_HOST', '127.0.0.1'),
>             'port' => env('DB_PORT', '3306'),
>             'database' => env('DB_DATABASE', 'forge'),
>             'username' => env('DB_USERNAME', 'forge'),
>             'password' => env('DB_PASSWORD', ''),
>             'unix_socket' => env('DB_SOCKET', ''),
>             'charset' => 'utf8mb4',
>             'collation' => 'utf8mb4_unicode_ci',
>             'prefix' => '',
>             'prefix_indexes' => true,
>             'strict' => true,
>             'engine' => null,
>             'options' => extension_loaded('pdo_mysql') ? array_filter([
>                 PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
>                 PDO::ATTR_CASE => PDO::CASE_LOWER,
>             ]) : [],
>         ]

> My env (I am using docker container)
> DB_CONNECTION=mysql
> DB_HOST_CMSADMIN=mysql
> DB_PORT_CMSADMIN=3306
> DB_DATABASE=cmsadmin
> DB_USERNAME=portal
> DB_PASSWORD=portal

All other operations are fine. So upon trigerring the code above,
I will get,
![image](https://github.com/laravel/framework/assets/15712325/88b41ebf-91d4-4e71-b233-62a54b06fafa)

Then I ran,` touch database/database.sqlite `
![image](https://github.com/laravel/framework/assets/15712325/fce5f335-db62-455c-a4f4-f652e3131e63)

So, I tried adding the key sqlite to my config('database.connections')

> 'sqlite' => [
>             'driver' => env('DATABASE_DRIVER', 'mysql'),
>             'url' => env('DATABASE_URL', ''),
>             'host' => env('DB_HOST', '127.0.0.1'),
>             'port' => env('DB_PORT', '3306'),
>             'database' => env('DB_DATABASE', 'forge'),
>             'username' => env('DB_USERNAME', 'forge'),
>             'password' => env('DB_PASSWORD', ''),
>             'unix_socket' => env('DB_SOCKET', ''),
>             'charset' => 'utf8mb4',
>             'collation' => 'utf8mb4_unicode_ci',
>             'prefix' => '',
>             'prefix_indexes' => true,
>             'strict' => true,
>             'engine' => null,
>             'options' => extension_loaded('pdo_mysql') ? array_filter([
>                 PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
>                 PDO::ATTR_CASE => PDO::CASE_LOWER,
>             ]) : [],
>         ]

Then it started working. This happens for both connection that I have tested, mysql(local) and oracle(production and staging server).

If you need more info just let me know.

### Steps To Reproduce

Run a `Bus::batch()->dispatch` with another db connection other than sqlite.

**Comment by mnazmi23** [comment]
Found the issue, this is inside the vendor queue config. 

> 
>     'batching' => [
>         'database' => env('DB_CONNECTION', 'sqlite'),
>         'table' => 'job_batches',
>     ],

my bad

**Comment by tom-on-the-internet** [comment]
This helped me a lot. Thank you.
If anyone else runs into this, please take a look at a new Laravel app. The `config.queue` will have a `batching` section. 
In your app, you need to define this, or Laravel will fallback to the default (sqlite).
