### ISSUE TITLE
$request->user() returns null when called from a middleware

### ISSUE THREAD

**Issue by tauseefsshah** [laravel/framework#50621]
### Laravel Version

11.0.7

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0

### Description

When trying to dump user information in the middleware after authenticating, `$request->user()` returns `null`

**ExampleMiddleware.php**
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ExampleMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Closure(\Illuminate\Http\Request): (\Symfony\Component\HttpFoundation\Response)  $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        dd($request->user()); // This should dump the user object but it's dumping null (the user is authenticated)

        return $next($request);
    }
}
```

### Steps To Reproduce

- Do a fresh install of laravel and jetstream
- Create a test middleware 
- Add `dd($request->user());` code to the middleware
- Register a user account and login
- Add middleware globally in the `bootstrap/app.php`
- Finally check the dump, returns `null`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tauseefsshah** [comment]
@crynobone It's a bug introduced in laravel 11, the same works fine in laravel 10. The expected output for the `$request->user()` is the user object but it's returning null in laravel 11

**Comment by rojtjo** [comment]
You mention that you register your middleware as a global middleware.
Since, by default, the `StartSession` middleware runs in the `web` middleware  group this means your custom global middleware will run before the sessions starts.

Register your middleware using the `appendToGroup` middleware instead:
```php
->withMiddleware(function (Middleware $middleware) {
    $middleware->appendToGroup('web', MyMiddleware::class);
})
```

**Comment by tauseefsshah** [comment]
@rojtjo `appendToGroup` works. Thank you so muchhhhhhhhhhh!!!!
