### ISSUE TITLE
Nullable validation passes for empty string

### ISSUE THREAD

**Issue by basarito** [laravel/framework#50626]
### Laravel Version

10.45.1

### PHP Version

8.3.3

### Description

Hey, I'm noticing a weird behaviour that doesn't really make sense.
I'm trying to validate a request using `FormRequest`, in particular a date input. This is the rule for it:
```
'valid_from' => 'nullable|date'
```

I've checked the [documentation](https://laravel.com/docs/10.x/validation#rule-nullable) and for `nullable` it says:
> The field under validation may be null.

So `null`, not an empty string. 

The `date` part should validate for a valid date.

But when you pass an empty string `''` it passes this validation and ends up trying to store an empty string as date.

More importantly, `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class` is commented out from `Kernel.php` so it's not implicitly converting it to `null`, but during `nullable` check _does_ get treated as `null`. 

Is this the intended behaviour? If yes, it's a very odd behaviour to have because `null` is not the same as empty string and the documentation explicitly states that `nullable` should check for `null` value only.

### Steps To Reproduce

- add `nullable` rule to `FormRequest`
- pass an empty string in request

**Comment by PaperTurtle** [comment]
@basarito This doesn't seem to be the case in version 11 anymore, maybe try upgrading to a higher/the latest version of Laravel 10, 10.48.3.

**Comment by driesvints** [comment]
```php
validator()->make(["foo" => ""], ["foo" => "nullable"])->passes();
```

The above is expected to return true because of how the validator works with empty values. If you always want a value to be present you need to add `required` as well.

**Comment by basarito** [comment]
@PaperTurtle thanks, I will check it after upgrading!

> If you always want a value to be present you need to add required as well.

@driesvints I don't need `required` in this case, because I want to allow `null` as well. But `nullable` should check if a value is `null` not an empty string (at least according to the docs). Or rather, if it passes, it should then be caught by the `date` validation. In any case it doesn't seem consistent.
