### ISSUE TITLE
APP_KEY not cached on first cache

### ISSUE THREAD

**Issue by thojo0** [laravel/framework#50654]
### Laravel Version

10.48.3

### PHP Version

8.2.7

### Description

If no cached config is present and you run `config:cache`, `APP_KEY` doesn't get cached.
### 

### Steps To Reproduce

1. Set `APP_KEY` in `.env`
2. Run `config:clear`
3. Run `config:cache`
4. Value is not set in `bootstrap/cache/config.php`
5. Run `config:cache` again
6. Value is will be set in `bootstrap/cache/config.php`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
