### ISSUE TITLE
Support for Models in App folder in Laravel 11?

### ISSUE THREAD

**Issue by JohnnyWalkerDigital** [laravel/framework#50651]
### Laravel Version

11.0.7

### PHP Version

8.2.16

### Description

I'm a old skool Laravel developer who wanted Models to remain in the App root and was always grateful that Laravel 8+ still supported this. I've just installed Laravel 11 with Laravel Breeze (Blade/Alpine) and this seems to work fine as before... **except when I run** `php artisan test`.

I haven't quite deduced what's going on, but 19 of the 25 tests fail with the same error:

> include(/Users/home/Eleven/vendor/composer/../../app/Models/User.php): Failed to open stream: No such file or directory
> 
>   at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:789
>     785▕             $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));
>     786▕ 
>     787▕             $appNamespace = static::appNamespace();
>     788▕ 
>   ➜ 789▕             return class_exists($appNamespace.'Models\\'.$namespacedFactoryBasename)
>     790▕                         ? $appNamespace.'Models\\'.$namespacedFactoryBasename
>     791▕                         : $appNamespace.$factoryBasename;
>     792▕         };

### Steps To Reproduce

1. Install new Laravel 11 application with Laravel Breeze (Blade/Alpine) and SQLite
2. Move User model to App root (follow these steps: https://stackoverflow.com/a/77046263/199700 )
3. Run `php artisan make:model Test` to ensure everything is working correctly
4. Run `php artisan test`

**Comment by JohnnyWalkerDigital** [comment]
Hi @driesvints, I don't think you read the report correctly. I know you're busy, but please take another look.

**Comment by driesvints** [comment]
@JohnnyWalkerDigital ah sorry I indeed misread that. 

What's going on is probably that your User factory doesn't points to your User any more. Try either updating the model property of your factory and/or add a dedicated `newFactory` method to your User model

https://github.com/laravel/laravel/blob/11.x/database/factories/UserFactory.php

**Comment by JohnnyWalkerDigital** [comment]
Yes, I thought it might be the UserFactory no pointing to the right folder, but alas it's not that:

```
<?php

namespace Database\Factories;

use App\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends Factory<User>
 */
class UserFactory extends Factory
```

Does this mean that Laravel 11 doesn't support the root folder anymore?

**Comment by driesvints** [comment]
It should. But since you moved it manually you'll need to figure out a bit what it takes on getting that test to pass. It's best to try a support channel for that:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by JohnnyWalkerDigital** [comment]
@driesvints Sorry, not sure I follow. If you could explain further I'd really appreciate it. As far as I know there is no other way than the manual editing of the `config/auth.php` to change the models folder. Is there another supported way?

I'd love to discover this is something I've done wrong, but I've used this technique on many projects through Laravel 8, 9 and 10. It's only with 11 that I'm getting this strange issue... but maybe I've made a misstep somewhere. I will keep prodding and probing to see if I can discover the root, but if there's anything else you could add, I would appreciate it.

Thanks.

Here's my config/auth.php:

 ```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => env('AUTH_MODEL', App\User::class),
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

**Comment by JohnnyWalkerDigital** [comment]
@driesvints Bah! It was fixed with `composer dump-autoload`. All is fine. Thanks for your time.

**Comment by driesvints** [comment]
@JohnnyWalkerDigital all good! Glad you figured that one out 👍
