### ISSUE TITLE
Laravel + React + Inertia not save session after Auth::attempt

### ISSUE THREAD

**Issue by stevan-iskandar** [laravel/framework#50666]
### Laravel Version

11.0.7

### PHP Version

8.3.3

### Database Driver & Version

Postgre SQL 13

### Description

I try to update my application to Laravel 11. For the front end I use React + Inertia.

### Steps To Reproduce

```php
public function login(Request $request): JsonResponse
{
    $request->validate([
        'username' => 'required',
        'password' => 'required',
    ]);

    if (!Auth::attempt([
        User::ATTR_CHAR_NAME        => $request->username,
        User::ATTR_CHAR_PASSWORD    => $request->password,
    ], true)) return response()->json([
        self::RES_MESSAGE => 'The provided credentials do not match our records.',
    ], 422);

    return response()->json([
        self::RES_MESSAGE   => 'Successfully login',
        self::RES_DATA      => Auth::user(),
    ]);
}
``` 

Auth::user() exists (success login), but the session not save my auth. For the session driver I use `database` and after I check my database, the user_id is null.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
