### ISSUE TITLE
`php artisan schedule:list` does not support fluent-style scheduling

### ISSUE THREAD

**Issue by raveren** [laravel/framework#50670]
### Laravel Version

11.0.7

### PHP Version

8.3.4

### Description

As found out in #50120 - the `php artisan schedule:list` is broken for fluent-style scheduling entries.

The scheduling still works as expected, but the list is displayed incorrectly.

Using the example from the docs (https://laravel.com/docs/11.x/scheduling#between-time-constraints):

```php
$schedule->command('emails:send')
      ->hourly()
      ->between('7:00', '22:00');
```

`php artisan schedule:list`:

```
  0 * * * *    php artisan emails:send ......................... Next Due: in 8 Minutes
```

As you can see the configuration is displayed as a seemingly random value, in this case just `hourly`.

Related Laracasts topic:

https://laracasts.com/discuss/channels/laravel/schedule-between-not-working-as-expected

### Steps To Reproduce

add 
```php
$schedule->command('emails:send')
      ->hourly()
      ->between('7:00', '22:00');
```

to `routes/console.php` and launch 
```
php artisan schedule:list
```

**Comment by crynobone** [comment]
Are you saying it doesn't run between 7:00 - 22:00 hourly every day. Or does the CLI output does not match your expectations but the schedule still executed correctly?

**Comment by raveren** [comment]
I did not test if it runs or not according to the schedule, but [people in the Laracasts](https://laracasts.com/discuss/channels/laravel/schedule-between-not-working-as-expected?page=1&replyId=925415) forum claim that:

> between() works fine, just the schedule:list command does not display it OK. the tasks are not translated to individual cron entries, so the cron representation is a bit misleading (and wrong in this case). the kernel is run every minute (via cron) and it checks the schedule internally and run respective tasks/commands. and since it is not translated to the cron syntax (edit: well, it might, but i am not going to dig into it:), i just think it would be pain to represent all of the contraints that laravel scheduler provides.

So this issue is about `php artisan schedule:list` producing wrong output.

**Comment by wanted80** [comment]
I tested it and I confirm that the `between()` method work fine but the `php artisan schedule:list` show the wrong output so it's only a visual matter.

**Comment by driesvints** [comment]
Sorry I closed your previous issue @raveren. Would love to get some help with this one.

**Comment by raveren** [comment]
No problem, totally understandable, however I think @JonPurvis, the author of https://github.com/laravel/framework/pull/47983 knows this stuff best, however his PR was denied by @taylorotwell for reasons I couldn't fully understand.

Anyway me personally, I am out of my depth here, I've never did anything in Laravel internals at this point I and am frankly out of motivation to take this one up, as I accidentally lost the huge real-life schedule file that took me all evening to convert from cron to fluent-calls. I couldn't verify I did no unintended changes and eventually lost the change :)

**Comment by JonPurvis** [comment]
I actually forgot I'd worked on that until I got the GitHub notification for the mention on this issue 😆 

https://github.com/laravel/framework/pull/47983 should fix this issue though. I could try tagging Taylor for a re-review of it and see what he says?

**Comment by nunomaduro** [comment]
@JonPurvis Ideally, we should try to fix this issue without touching on the generation of the cron expression.

**Comment by JonPurvis** [comment]
Yep of course, would be awesome to get this sorted somehow!

**Comment by taylorotwell** [comment]
@JonPurvis would you mind sending your PR to 11.x and we can take another look?

**Comment by ottoszika** [comment]
The `between` or `unlessBetween` method uses `when` or `skip`, which are filters applied after CRON expression. They can be very difficult to represent, because you can have complex expressions like this:
```php
$schedule->command('...')->when(fn () => Birthday::existsOnDate(today()));
```

**Comment by skywarth** [comment]
Coming from  #51107, can confirm that `->between()` also doesn't work with `->isDue()` and `->nextRunDate()` methods on schedule events. Therefore, making it really difficult to do assertions and tests. Any news on the issue? Is someone working on it? If not, I may attempt to mitigate the issue by slightly altering `->isDue()` and `->nextRunDate()`, as well as `php artisan schedule:list` in order to make them take `->between()` into account. I agree that changing `->between()` to CRON based solution would be dangerous, therefore we can do a workaround.

**Comment by akinoriakatsuka** [comment]
$eventsを吐かせてみて、中の情報がどうなっているか調べる

```
      ["expression"]=>
      string(9) "0 * * * *"

            ["startTime"]=>
            object(Illuminate\Support\Carbon)#462 (20) {

              ["date"]=>
              string(26) "2024-05-12 07:00:00.000000"

            ["endTime"]=>
            object(Illuminate\Support\Carbon)#466 (20) {

              ["date"]=>
              string(26) "2024-05-12 22:00:00.000000"
```

**Comment by akinoriakatsuka** [comment]
上記から、終了時間と開始時間は取れてるっぽいが、expressionの計算がうまく行ってないっぽい

**Comment by akinoriakatsuka** [comment]
issueで問題になっているbetweenメソッドについてはtestケースがない！

**Comment by akinoriakatsuka** [comment]
Eventのexpressionがどうやって計算されているかを確認する

**Comment by akinoriakatsuka** [comment]
$expressionを代入する部分ない。traitかな？

**Comment by akinoriakatsuka** [comment]
traiteビンゴ！
src/Illuminate/Console/Scheduling/ManagesFrequencies.php

**Comment by akinoriakatsuka** [comment]
以下の実装見る限り
 $event->cron($expression)
の形で外から与えられるっぽい。

```
    /**
     * The Cron expression representing the event's frequency.
     *
     * @param  string  $expression
     * @return $this
     */
    public function cron($expression)
    {
        $this->expression = $expression;

        return $this;
    }
```

ので、次は `->cron(` を探す。

**Comment by akinoriakatsuka** [comment]
twiceDailyはうまくcron出せてるので、この実装をまねしてみよう

**Comment by akinoriakatsuka** [comment]
メソッド追っかけ

```
    /**
     * Schedule the event to run twice daily.
     *
     * @param  int  $first
     * @param  int  $second
     * @return $this
     */
    public function twiceDaily($first = 1, $second = 13)
    {
        return $this->twiceDailyAt($first, $second, 0);
    }
```

```
    /**
     * Schedule the event to run twice daily at a given offset.
     *
     * @param  int  $first
     * @param  int  $second
     * @param  int  $offset
     * @return $this
     */
    public function twiceDailyAt($first = 1, $second = 13, $offset = 0)
    {
        $hours = $first.','.$second;

        return $this->hourBasedSchedule($offset, $hours);
    }
```

**Comment by driesvints** [comment]
@JonPurvis would you maybe be up for re-attempting your PR against master/12.x? Maybe we can make it happen on a next release.

**Comment by JonPurvis** [comment]
Hey @driesvints 

Certainly, I actually meant to do this when Taylor tagged me but it slipped my mind. I'll re-create this PR targeted to Laravel 12 this week so I don't forget! I believe it's still worth looking into.

**Comment by driesvints** [comment]
Going to close this one now as non-supported but happy to receive a new attempt at 12.x, thanks.

**Comment by raveren** [comment]
This is still a very real issue, and although @driesvints said he'll close it as "non-supported", it's marked as `completed` above.

Exactly this issue is also preventing me from reliably detecting cron jobs that are scheduled between 2:00 and 3:00 (see [why](https://www.endpointdev.com/blog/2013/04/avoid-200-and-300-am-cron-jobs/)) as the `nextRunDate()` is also reporting incorrectly:

<img width="1287" height="943" alt="Image" src="https://github.com/user-attachments/assets/45e02eae-f9c5-4fb4-9232-f0712a8f2f03" />

I can't even detect jobs with `setTestNow()` because by the time my test (which attempts to catch such jobs) runs - the scheduler has calculated, and the ManagesFrequencies creates a closure with `$now` instead of now()

<img width="559" height="303" alt="Image" src="https://github.com/user-attachments/assets/803b59f6-4c0a-49bc-b482-34bdfedc75dd" />
