### ISSUE TITLE
The authorizeResource method does not work with the new abstract base controller class

### ISSUE THREAD

**Issue by nathanpurcell** [laravel/framework#50673]
### Laravel Version

11.0.7

### PHP Version

8.3.4

### Description

When upgrading from 10 > 11 and applying the "AuthorizesRequests" trait as defined in the upgrade guide, I encountered a "Call to undefined method Path\To\MyController::middleware()" exception. 

I believe this is simply due to the now empty App\Http\Controllers\Controller class. 
The problem can be resolved by changing the "extends" to "\Illuminate\Routing\Controller" but this doesn't seem right. 

Is this intended? 

### Steps To Reproduce

**Install a new L11 project**

**Create a new controller:** 
`php artisan make:controller UserController --resource`

**Add `AuthorizesRequests` trait to `UserController`**

**Add a route to test**
```php

// routes/web.php
Route::get('/', [\App\Http\Controllers\UserController::class, 'index']);
```

**Receive Call to undefined method App\Http\Controllers\UserController::middleware() error**

Neither a policy or authenticated user should be required to validate this issue.

**Comment by driesvints** [comment]
> When upgrading from 10 > 11 and applying the "AuthorizesRequests" trait as defined in the upgrade guide

We don't say this in the upgrade guide? https://laravel.com/docs/11.x/upgrade

> The problem can be resolved by changing the "extends" to "\Illuminate\Routing\Controller" but this doesn't seem right.

This is the correct solution.

**Comment by justinmoh** [comment]
> > When upgrading from 10 > 11 and applying the "AuthorizesRequests" trait as defined in the upgrade guide
> 
> We don't say this in the upgrade guide? https://laravel.com/docs/11.x/upgrade
> 
> > The problem can be resolved by changing the "extends" to "\Illuminate\Routing\Controller" but this doesn't seem right.
> 
> This is the correct solution.

Sorry, couldn't find it in the latest doc, probably removed? 

Just want to know if it's deprecated and no longer recommend to use `AuthorizesRequest` in version 11; or the feature will still be maintained and we just need to manually add the correct `extends \Illuminate\Routing\Controller`, no additional side effects.

**Comment by driesvints** [comment]
You just need to extend the routing controller :thu

**Comment by nathanpurcell** [comment]
@justinmoh my solution (as I need both `ValidatesRequests` and `AuthorizesRequests` very frequently) was to create a BaseController that `uses` both traits and extends `Illuminate\Routing\Controller`. 
![Screenshot 2024-05-16 at 10 01 28](https://github.com/laravel/framework/assets/4105739/52a40f15-95c0-4aed-b84a-cf3a2d5946da)

As Dries states, the new L11 approach is to extend the slim base controller and add the traits as-and-when required: https://laravel.com/docs/11.x/releases#base-controller-class

I do agree that the docs around this are a bit lacking; understanding of course that 11 is meant to work with 10 without any wholesale changes, but considering the make:controller Artisan command is also slim and there's no mention of the requirement to add these traits anywhere except the release guide, you can see how it's confusing.

**Comment by driesvints** [comment]
We'd very much welcome PR's to make the docs more clear 👍  In general we don't recommend those specific traits any longer because there's other ways to do this like `$request->validate()` & `abort_if()` etc. Granted, these work a little bit different.

**Comment by nathanpurcell** [comment]
That's fair enough - I see the logic. 
What are the other ways to use `authorizeForUser` and `authorizeResource` that come with `AuthorizesRequests`?

Thanks, NP

**Comment by nickfls** [comment]
@nathanpurcell not unless you reimplement `\Illuminate\Routing\Controller::middleware()`.

But unless i read @driesvints [comment above](https://github.com/laravel/framework/issues/50673#issuecomment-2115027168)  wrong, this approach is now not recommended.

**Comment by driesvints** [comment]
I think `authorizeForUser` will still work fine with just `AuthorizesRequests` but there doesn't seems to be an alternative for `authorizeResource` at this time. You'll have to use an approach from https://laravel.com/docs/11.x/authorization for this.

Otherwise if you still want to use `authorizeResource` you can simply extend the base controller which still ships with Laravel.
