### ISSUE TITLE
Model returned even when debug is off

### ISSUE THREAD

**Issue by Lexian-droid** [laravel/framework#50729]
### Laravel Version

10.48.2

### PHP Version

8.3.3

### Database Driver & Version

MySQL 8.0.30

### Description

While programming your API, and you use findOrFail() on a model, it returns the model that failed in the json response, even when Debug mode is off.

Here is a code example:
```php
    public function index($id)
    {
        $users = Users::findOrFail($id);

        return response()->json($versions);
    }
```

which will return the following:
```json
{
  "message": "No query results for model [App\\Models\\User] 5"
}
```
whilst giving a 404 error.

Here is my .ENV file (where related)
```env
APP_NAME=Nuance
APP_ENV=production
APP_KEY=base64:O9+NlA1oydWV3PHSh1AB9NiYtrR2R/ztI9qJRsjAq8k=
APP_DEBUG=false
APP_URL=http://nuance.local
```

### Steps To Reproduce

- Create a new project or use an existing project
- In your .ENV set your ``APP_ENV`` to production.
- In your .ENV set your ``APP_DEBUG`` to false.
- In your API routes create a route leading to any path you want and write the following code:
```php
Route::get('user/{userid}', function ($userid) {
    $users = User::findOrFail($userid);
    return response()->json($users);
});
```
- Make a web request to the route you created using either an API testing tool or your browser.
- You'll see that the error message displayed mentions the model that you were using.
```json
{
  "message": "No query results for model [App\\Models\\User] 2"
}
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Lexian-droid** [comment]
> Hi there,
> 
> Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:
> 
>     * [Laracasts Forums](https://laracasts.com/discuss)
> 
>     * [Laravel.io Forums](https://laravel.io/forum)
> 
>     * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> 
>     * [Discord](https://discordapp.com/invite/KxwQuKb)
> 
>     * [Larachat](https://larachat.co/)
> 
>     * [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
> 
> 
> However, this issue will not be locked and everyone is still free to discuss solutions to your problem!
> 
> Thanks.

Are you sure about that? This seems like a Laravel issue, as it occurs with fresh projects as well.
