### ISSUE TITLE
session error

### ISSUE THREAD

**Issue by jevantang** [laravel/framework#50720]
### Laravel Version

11

### PHP Version

8.2

### Description

The default session driver uses the database.

However, if the initialisation is not installed, it is not connected to the database, so it cannot be used.

Or, if the product does not have a database, it will not work.

If the database is not connected, it cannot be used, and if it cannot be used, it cannot be used to configure the product visually, leading to a dead end.

I want to restore the default driver to the file

### Steps To Reproduce

The new framework allows the product to reduce profiles, but driver configurations such as Session or Queue are databases by default, so the reduced profiles will be restored.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
