### ISSUE TITLE
Connection to database id containing only integer

### ISSUE THREAD

**Issue by Ph0tonic** [laravel/framework#50750]
### Laravel Version

11.0.8

### PHP Version

8.2.12

### Database Driver & Version

Not applicable

### Description

Hi,
When defining a connection with a key containing only numbers, I am not able to run the command `php artisan migrate --database 11`. This used to work with laravel 10.

Example of config :
```php
// Ajout DB de base
$connections['11'] = [
    'driver' => 'mysql',
    'host' => env('DB_HOST', '127.0.0.1'),
    'port' => env('DB_PORT', '3306'),
    'database' => env('DB_DATABASE', 'demo'),
    'username' => env('DB_USERNAME', 'forge'),
    'password' => env('DB_PASSWORD', ''),
    'unix_socket' => env('DB_SOCKET', ''),
    'charset' => env('DB_CHARSET', 'utf8mb4'),
    'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
    'prefix' => '',
    'prefix_indexes' => true,
    'strict' => true,
    'engine' => null,
    'options' => extension_loaded('pdo_mysql') ? array_filter([
        PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
        PDO::ATTR_EMULATE_PREPARES => true,
    ]) : [],
];
```

If I use a key `11a` it's working again. I would expect the command to work as before.

### Steps To Reproduce

Replace the identifier of the default database with an integer like `55` and try to migrate specifying the database name using:

- `php artisan migrate --database 55`

**Comment by driesvints** [comment]
I'm not sure we actively support this or ever did. We suggest to always use a string based key and not a number as PHP tends to reset array keys in some situations.

**Comment by Ph0tonic** [comment]
Hum, I am indeed using a string-based key but when using artisan it parses my input as an integer instead of a string. So, I believe that I am using the right syntax.

**Comment by driesvints** [comment]
You're using integers as a string. These things can happen: https://3v4l.org/0Xe3e

**Comment by Ph0tonic** [comment]
Ok, sorry for the bother, I implemented a fix to avoid this situation.
Thanks :+1:
