### ISSUE TITLE
Broadcasting does not work

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#50754]
### Laravel Version

11.0.8

### PHP Version

8.3.3

### Description

I’m trying to install broadcasting but it does not seem to register the **/broadcasting/auth** route anywhere, so private channels are not getting authorised.

### Steps To Reproduce

1. Run `php artisan install:broadcasting`
2. Run `composer require pusher/pusher-php-server`
3. Add `ShouldBroadcast` interface to event, and define `broadcastOn` method
4. Events are dispatched to Pusher, as I can see them arrive in the debug console
5. Listening to channels does not work, as requests for `POST /broadcasting/auth` receive a `404 Not Found` response

The [Laravel broadcasting docs](https://laravel.com/docs/11.x/broadcasting#authorizing-channels) state:

> When broadcasting is enabled, Laravel automatically registers the `/broadcasting/auth` route to handle authorization requests.

But this does not seem to be happening in practice.

**Comment by crynobone** [comment]
/
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by martinbean** [comment]
> We'll need more info and/or code to debug this further.

@crynobone I outlined the steps in my initial post. I’m afraid I can’t use the Laravel Installer as I don’t have Composer installed on my machine, so can’t install global Composer packages. such as that.

It’s a relatively new Laravel 11 application. Installed Broadcasting. Broadcasting authorisation route (`/broadcasting/auth`) is not registered. Confirmed by running `php artisan route:list` and the authorisation route not being listed there.

**Comment by crynobone** [comment]
Can you share the contain of `bootstrap/app.php`?

**Comment by martinbean** [comment]
> Can you share the content of `bootstrap/app.php`?

Sure:

```php
<?php

use App\Http\Middleware\HandleRedirects;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

return Application::configure(basePath: dirname(__DIR__))
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })
    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->alias([
            'features' => \Laravel\Pennant\Middleware\EnsureFeaturesAreActive::class,
        ]);

        $middleware->append(HandleRedirects::class);

        $middleware->group('web.channel', [
            \App\Http\Middleware\SetChannelViewNamespace::class,
        ]);

        $middleware->group('web.channel.admin', [
            \App\Http\Middleware\HandleInertiaRequests::class,
        ]);

        $middleware->trustProxies(
            at: '*',
            headers: Request::HEADER_X_FORWARDED_AWS_ELB,
        );

        $middleware->validateCsrfTokens(except: [
            'mux/webhook',
            'stripe/*',
        ]);
    })
    ->withRouting(
        health: '/up',
        web: __DIR__ . '/../routes/web.php',
        then: function (): void {
            // Channel
            Route::middleware('web', 'web.channel', 'can:view,channel')
                ->name('channel.')
                ->prefix('channels/{channel:slug}')
                ->group(base_path('routes/web.channel.php'));

            // Channel Admin
            Route::middleware('web', 'auth', 'can:update,channel', 'web.channel.admin')
                ->name('channel.admin.')
                ->prefix('channels/{channel:slug}/admin')
                ->group(base_path('routes/web.channel.admin.php'));
        },
    )
    ->create();
```

**Comment by crynobone** [comment]
You're missing `channels` https://github.com/laravel/framework/blob/efa867e85b4abcaab8146f66bc676b7239507719/src/Illuminate/Foundation/Configuration/ApplicationBuilder.php#L163 which should be added via the install command. Missing that would prevent the default behaviour.

**Comment by martinbean** [comment]
> You're missing `channels`

That `channels` key doesn’t exist in the Laravel 11.x skeleton, though?

https://github.com/laravel/laravel/blob/441845d88dfc2a4fbf59f1e57d48889c8de664bb/bootstrap/app.php#L8-L11

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/blob/efa867e85b4abcaab8146f66bc676b7239507719/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php#L88

**Comment by martinbean** [comment]
@crynobone Yes, all of those conditions will evaluate as `false` in my case. I removed the `commands` file as I detest using a “routes” file to register Artisan command.

**Comment by crynobone** [comment]
In that case, you should either use `withBroadcasting()` method or register the route manually.

**Comment by thecyrilcril** [comment]
I am having the same issue. here is my `bootstrap/app.php` file
```
<?php

declare(strict_types=1);

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {})
    ->withExceptions(function (Exceptions $exceptions): void {})->create();
```

Manually adding `channels: __DIR__ . '/../routes/channels.php',` to the withRouting method seems to fix it but I think this might be a bug on Windows as  am always running into it

**Comment by martinbean** [comment]
@thecyrilcril I got around it by adding the broadcasting routes and channel definitions to my `AppServiceProvider` file:

```php
use Illuminate\Support\Facades\Broadcast;

class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Broadcast::routes();

        Broadcast::channel('orders.{order}', function (User $user, Order $order): bool {
            return $order->user()->is($user);
        }
    }
}
```

**Comment by razorext2** [comment]
> channels: __DIR__ . '/../routes/channels.php',

might be the solutions since laravel created routes/channels.php and there is nothing to define in bootstrap/app.php

so check ur app bootstrap file, and add it
