### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Named parameter $api overwrites previous argument

### ISSUE THREAD

**Issue by hossam20520** [laravel/framework#50769]
### Laravel Version

11

### PHP Version

8.2

### Description

The error is shown when you try to use 
php artisan serve 

PHP Fatal error:  Uncaught Error: Named parameter $api overwrites previous argument in D:\laravel_11\pos_system\bootstrap\app.php:11

Stack trace:
#0 D:\laravel_11\pos_system\artisan(12): require_once()
#1 {main}
  thrown in D:\laravel_11\pos_system\bootstrap\app.php on line 11
This error happens if you used  "php artisan install:api --passport "  multiple times 
To resolve this issues just go to bootstrap\app.php and remove duplicated line 
 api: __DIR__.'/../routes/api.php',

### Steps To Reproduce

The error is shown when you try to use 
php artisan serve 

PHP Fatal error:  Uncaught Error: Named parameter $api overwrites previous argument in D:\laravel_11\pos_system\bootstrap\app.php:11

Stack trace:
#0 D:\laravel_11\pos_system\artisan(12): require_once()
#1 {main}
  thrown in D:\laravel_11\pos_system\bootstrap\app.php on line 11
This error happens if you used  "php artisan install:api --passport "  multiple times 
To resolve this issues just go to bootstrap\app.php and remove duplicated line 
 api: __DIR__.'/../routes/api.php',

**Comment by adedejiibrahim7** [comment]
@hossam20520 I see you've closed this. How did you resolve this please

**Comment by hossam20520** [comment]
@adedejiibrahim7 
This error happens if you use "php artisan install:api --passport " multiple times
To resolve this issue just go to bootstrap\app.php and remove the duplicated line
api: DIR.'/../routes/api.php',

**Comment by Mustafa-Kadir** [comment]
> @adedejiibrahim7 This error happens if you use "php artisan install:api --passport " multiple times To resolve this issue just go to bootstrap\app.php and remove the duplicated line api: DIR.'/../routes/api.php',

Thank you.
