### ISSUE TITLE
Problem with breeze install

### ISSUE THREAD

**Issue by IgorMarqx** [laravel/framework#50773]
### Laravel Version

11.0.8

### PHP Version

8.2

### Database Driver & Version

Mysql 8.0

### Description

I recently tried to install Breeze in my project, but I ran into a problem

When installing Breeze I chose the TypeScript language, I continued the installation but when I checked it installed in JSX

During installation I noticed that the selected section was empty

My operating system is Mac Sonoma(14.2.1) M2 and my terminal used is warp

![image](https://github.com/laravel/framework/assets/100423634/00439133-942a-45a8-9c37-1ca2bed9d5a7)

![image](https://github.com/laravel/framework/assets/100423634/308a07f5-cfc5-49be-9d31-6f58823b2505)

### Steps To Reproduce

I have a personal project I used the blade, but I chose to change it to react with inertia

So the steps are
- composer required laravel/breeze
- php artisan breeze:install
- choose to react with inertia
- choose typescript
- choose PHPUnit
- lastly choose MySql

When choosing the options, TypeScript looks like the image sent

**Comment by driesvints** [comment]
Did you actually select it using your spacebar?
