### ISSUE TITLE
dd() on chrome not working

### ISSUE THREAD

**Issue by adityadees** [laravel/framework#50786]
### Laravel Version

9.52

### PHP Version

8.2.13

### Description

I frequently use Google Chrome as my browser, but I'm starting to feel a bit frustrated because the output from dd() function will be encoding characters. Interestingly, Firefox doesn't seem to have this issue; everything works smoothly without character encoding. Should this issue be addressed by @laravel or by  @googlechrome ?

### Steps To Reproduce

using ajax, and `dd()` inside controller

Firefox
<img width="479" alt="image" src="https://github.com/laravel/framework/assets/37553901/7181254a-39ee-4d56-9f92-0ef31a7cdd7e">

Chrome
<img width="290" alt="image" src="https://github.com/laravel/framework/assets/37553901/398617c3-7a17-4f50-ae3e-831af7bc5d3e">

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/discussions/50785#discussioncomment-8928392
