### ISSUE TITLE
Queue job $tries, $retryUntil, not taking effect for already queued jobs in redis

### ISSUE THREAD

**Issue by MohamedLamineAllal** [laravel/framework#50793]
### Laravel Version

10.10

### PHP Version

8.2

### Database Driver & Version

Postgres 16 docker

#### Issue
Already queued jobs (released back) aren't reflecting the changes of $tries and retryUntil (set on the job) after changing them and restarting the workers. (redis queue used).

#### Expect
I Expect the changes to reflect immediately.

### Steps To Reproduce

Using Redis as a queue

Have a job with

```php
public $tries = 0;

public function handle(): void
{
    $this->l('Job TestQueueBusChainWithThrottle run ....');
    
    $this->l('Job : tries: ' . $this->tries);
    
    // throw new \Error('hi just kidding');
    // Sleep::usleep(1 * 1000000);
    $this->release();
    
    
    $this->l('Job TestQueueBusChainWithThrottle Done!');
}
```

Run worker, dispatch
=> keep running infinitely as supposed to.

Now kill worker, change code to

```php
public $tries = 1;
```

Start worker again.

The worker resumes work, but even $tries of the job is 1 (printed) => The whole is running on $tries = 0, as it keeps going indefinitely.

Basically, if there is a queued jobs, and we change $tries or retryUntil => the change will not take effect for old already in the queue jobs, and something of infinite loop, or of long tries, will keep going for too long. 

All newly dispatched jobs, take correctly the new value.

Whole job class

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Support\Sleep;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\{InteractsWithQueue, SerializesModels};
use Illuminate\Contracts\Queue\{ShouldBeUnique, ShouldQueue};

class TestQueueBusChainWithThrottle implements ShouldQueue
{
	use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

	public $tries = 0;
	public $maxExceptions = 1;

	// public function tries()
	// {
	// 	return 2;
	// }

	// public function retryUntil(): \DateTime
	// {
	// 	return now()->addSeconds(1);
	// }

	/**
	 * Create a new job instance.
	 */
	public function __construct()
	{
		$this->l('Job : tries: ' . $this->tries);
	}

	/**
	 * Execute the job.
	 */
	public function handle(): void
	{
		$this->l('Job TestQueueBusChainWithThrottle run ....');

		$this->l('Job : tries: ' . $this->tries);

		// throw new \Error('hi just kidding');
		// Sleep::usleep(1 * 1000000);
		$this->release();


		$this->l('Job TestQueueBusChainWithThrottle Done!');
	}

	public function l(mixed $msg)
	{
		\Log::channel('console')->info($msg);
	}

	public function failed(\Throwable $exception)
	{
		$this->l($exception->getMessage());
	}
}
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MohamedLamineAllal** [comment]
@crynobone just for alignment, Is it normal when one changes the attempts settings of a job ($tries, ...), and the already queued ones remain working with their initiation settings, and so in such a case of settings updates, either it's ok for the old one to continue till finish (old settings) if no issue, or we remove and re-queue if necessary (infinite loop, or long duration).

And the behavior is as mentioned. And by design? I'm not wrong. I just want the confirmation of that.

I don't have a problem, I know how to work in both cases, but I got to notice the behavior. And wanted to confirm (which in one case can make the issue a bug, otherwise not an issue at all.)

Thank you very much. Much appreciated.
