### ISSUE TITLE
DB::usingConnection() doesn't respect read/write type

### ISSUE THREAD

**Issue by SajtiDH** [laravel/framework#50804]
### Laravel Version

10.48.4

### PHP Version

8.2

### Description

I wanted to use the mysql write connection by default for all DB operations including selects, to prevent issues caused by replication lag in a Job that is dispatched immediately after a write operation.

For this I used the following code:

```
        DB::usingConnection('mysql::write', function () {
            // my code
        });
```

During testing I realized that my Models and even queries executed by the DB facade still using the read connection for selects.

After did some debugging I found out it is because it works like this:

1. `DB::usingConnection()` replaces the default connection's name in the `DatabaseManager`
2. When `DatabaseManager::connection()` is used with default connection it doesn't get a `$name` param and it is resolved within a subsequent call to `DatabaseManager::parseConnectionName()` and then use only the first `$database` segment without the type to look for already created connection instance so the `::write` part won't take effect.

### Steps To Reproduce

Create any db connection config with both write and read type and try to directly connect to the write host using DB::usingConnection()

```
        DB::usingConnection('mysql::write', function () {
            AnyModel::first(); // This will use the read connection
        });
```

**Comment by driesvints** [comment]
Thanks. Seems you already sent in a PR so let's see how it goes.
