### ISSUE TITLE
Manually Registering Events Make Them To Double Up

### ISSUE THREAD

**Issue by vincenzoraco** [laravel/framework#50805]
### Laravel Version

11.1.0

### PHP Version

8.3.3

### Database Driver & Version

MySQL 8.0.33

### Description

The documentation doesn't mention how to turn off event discovery.

I've followed the steps in https://laravel.com/docs/11.x/events#manually-registering-events and the listeners are registered twice.

Previously in `10.x` we would register in the `EventServiceProvider::listen` property and add `shouldDiscoverEvents` to not do it automatically. I don't see any documentation or similar method available in `11.x`.
```php
public function shouldDiscoverEvents(): bool
{
    return false;
}
```

In addition, it wasn't allowed to have the same listener twice for the same event. Currently seems possible. I'm not sure if it's intentional now.

It's either a lack of documentation, lack of configuration or a bug.

Thank you for your amazing work!

### Steps To Reproduce

Create a new Event
```php
php artisan make:event UserCreatedEvent
```
Create a new Listener
```php
artisan make:listener SendSmsListener --event=UserCreatedEvent
```
Add the following inside the listener `handle` method; it will help to debug
```php
public function handle(UserCreatedEvent $event): void
{
    echo self::class . ' was called' . PHP_EOL;
}
```
Add the following to the `AppServiceProvider::boot` method
```php
public function boot(): void
{
    Event::listen(
        UserCreatedEvent::class,
        SendSmsListener::class,
    );
}
```
Dispatch `UserCreatedEvent` you will see that the `handle` method is called twice
```php
php artisan tinker
```
```
Psy Shell v0.12.2 (PHP 8.3.3 — cli) by Justin Hileman
> \App\Events\UserCreatedEvent::dispatch();
```
The result is
```
App\Listeners\SendSmsListener was called
App\Listeners\SendSmsListener was called
```

If we run `php artisan event:list` we will see the below
```
App\Events\UserCreatedEvent ..................
⇂ App\Listeners\SendSmsListener  
⇂ App\Listeners\SendSmsListener@handle
```

If we add another `Event::listen` in the `AppServiceProvider::boot` method with the same params, we will see it duplicated again.
```php
public function boot(): void
{
    Event::listen(
        UserCreatedEvent::class,
        SendSmsListener::class,
    );
    Event::listen(
        UserCreatedEvent::class,
        SendSmsListener::class,
    );
}
```
```
App\Events\UserCreatedEvent ..................
⇂ App\Listeners\SendSmsListener  
⇂ App\Listeners\SendSmsListener  
⇂ App\Listeners\SendSmsListener@handle
```

**Comment by driesvints** [comment]
You don't need to add the listener manually anymore if it's in your listeners directory. This is all done for you. There's no need to stop the automatically discovery.

**Comment by vincenzoraco** [comment]
@driesvints thanks for getting back to me. The documentation says that I can add them manually and I need to do that if I want to trigger the listeners in a specific order just like I could with the `EventServiceProvider`. So either the documentation is not accurate or we just can't turn this off or it's a bug which I'm happy to contribute with a PR if it's confirmed.

**Comment by driesvints** [comment]
Hi @vincenzoraco. Listeners aren't meant to be triggered in a specific order. Their nature is that they're asynchronous. If you want to execute code in a specific order then most likely that code needs to be inside the same listener. By default, if you just create listeners and not call `Event::listen(` to register a listener already in the `Listeners` directory, there can't go anything wrong.

Your solution works but like you said, is hacky at best. `shouldDiscoverEvents` is indeed still there and we may possible be open to a PR to make more easily use of it. But it would depend on how complicated this would get. Feel free to attempt a PR if you're up for it.

**Comment by sts-ryan-holton** [comment]
I found I needed to manually add `Event::listen()` for Laravel specific events to my listeners as they weren't showing up in `event:list` until I added them:

```php
Event::listen(Login::class, UpdateUserLoggedIn::class);
Event::listen(Verified::class, SendWelcomeNotification::class);
```

**Comment by vincenzoraco** [comment]
> I found I needed to manually add `Event::listen()` for Laravel specific events to my listeners as they weren't showing up in `event:list` until I added them:
> 
> ```
> Event::listen(Login::class, UpdateUserLoggedIn::class);
> Event::listen(Verified::class, SendWelcomeNotification::class);
> ```

@sts-ryan-holton can you explain a bit more? Where is `UpdateUserLoggedIn` located? Is the `$event` parameter typed with the `Login` event?

**Comment by sts-ryan-holton** [comment]
The following go in `AppServiceProvider`

```php
use Illuminate\Auth\Events\Login;
use Illuminate\Auth\Events\Verified;
use App\Listeners\UpdateUserLoggedIn;
use App\Listeners\SendWelcomeNotification;
```

`UpdateUserLoggedIn` and `SendWelcomeNotification are listeners I've made. They're in the Listeners directory.

Then the following goes in the `boot` method of `AppServiceProvider`

```php
Event::listen(Login::class, UpdateUserLoggedIn::class);
Event::listen(Verified::class, SendWelcomeNotification::class);
```

`SendWelcomeNotification` is not typed, it's contents is:

```php
<?php

namespace App\Listeners;

use App\Notifications\Onboarding\Welcome;
use Carbon\Carbon;
use Illuminate\Contracts\Queue\ShouldQueue;

class SendWelcomeNotification implements ShouldQueue
{
    /**
     * The name of the queue the job should be sent to.
     *
     * @var string|null
     */
    public $queue = 'listeners';

    /**
     * Handle the event.
     */
    public function handle($event): void
    {
        if ($event->user) {

            // send a welcome email to the customer after verifying
            $delay = Carbon::now()->addMinutes(10);
            $event->user->notify((new Welcome())->delay($delay));
        }
    }
}

```

**Comment by vincenzoraco** [comment]
@sts-ryan-holton that [is expected](https://laravel.com/docs/11.x/events#event-discovery:~:text=Laravel%20will%20register%20those%20methods%20as%20event%20listeners%20for%20the%20event%20that%20is%20type%2Dhinted%20in%20the%20method%27s%20signature). Your Listener `$event` parameter is not type-hinted.

It should be

```php
use Illuminate\Auth\Events\Verified;
...
public function handle(Verified $event): void
```

and do this for all the listeners that you want to have it auto-discovered. If you don't type hint, they will not be auto-discovered for a logical reason: there won't be a way to know what is the event for that Listener.
