### ISSUE TITLE
Health route not registering when using routing customization

### ISSUE THREAD

**Issue by miagg** [laravel/framework#50816]
### Laravel Version

11.1

### PHP Version

8.3.3

### Description

Laravel [documentation](https://laravel.com/docs/11.x/routing#routing-customization) states that you can have full control of routing registration using `using` parameter like this:
```php
return Application::configure(basePath: dirname(__DIR__))
    ->withProviders()
    ->withRouting(
        using: function () {
            Route::middleware('web')
                ->group(function (Router $router) {
                    $router->impersonate();
                });

            Route::middleware('web')
                ->domain(config('filament.panels.partners.domain'))
                ->group(base_path('routes/partners.php'));

            // More Registrations here...
        },
        // channels: __DIR__.'/../routes/channels.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
```

However the health route `/up` is not registering using this method. How can we manually register the route without publishing the view?

### Steps To Reproduce

As explained above

**Comment by crynobone** [comment]
I believe you should use the following instead:

```diff
return Application::configure(basePath: dirname(__DIR__))
    ->withProviders()
    ->withRouting(
-       using: function () {
+       then: function () {
            Route::middleware('web')
                ->group(function (Router $router) {
                    $router->impersonate();
                });

            Route::middleware('web')
                ->domain(config('filament.panels.partners.domain'))
                ->group(base_path('routes/partners.php'));

            // More Registrations here...
        },
        // channels: __DIR__.'/../routes/channels.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
```

**Comment by laserhybiz** [comment]
The [documentation](https://laravel.com/docs/11.x/routing#:~:text=When%20this%20argument%20is%20passed%2C%20no%20HTTP%20routes%20will%20be%20registered%20by%20the%20framework%20and%20you%20are%20responsible%20for%20manually%20registering%20all%20routes%3A) states that using the `using` parameter disables all http routes:

> When this argument is passed, no HTTP routes will be registered by the framework and you are responsible for manually registering all routes

**Comment by miagg** [comment]
Thanks. I've switched to `then` and it is now working.

**Comment by iamphonghg** [comment]
Thanks, I also encountered this today with Laravel 12.
