### ISSUE TITLE
"recreate-databases" is not working with "parallel" tests

### ISSUE THREAD

**Issue by AnourValar** [laravel/framework#50840]
### Laravel Version

11.1.1

### PHP Version

8.3

### Database Driver & Version

PostgreSQL 15.1

### Description

php artisan test ignores the option "--recreate-databases".

This code won't be called:
ParallelTesting::setUpTestDatabase(fn () => dd('foo'));

### Steps To Reproduce

Run tests with the command:
php artisan test --parallel --recreate-databases --processes=3

**Comment by driesvints** [comment]
This flag isn't supposed to be combined with parallel testing.

**Comment by AnourValar** [comment]
@driesvints ,

1. parallel & recreate-databases features worked together a few month ago
2. Official Laravel document says it should work: https://laravel.com/docs/11.x/testing#parallel-testing-and-databases
![image](https://github.com/laravel/framework/assets/54237693/cbea7eef-fb73-4ed6-a80f-ec0849e67c83)

**Comment by driesvints** [comment]
Hah, you got me there, sorry. In my mind it seemed out to recreate databases while parallel testing is already constantly recreating them.

I'll re-open this but would appreciate some help figuring this one out.

**Comment by nunomaduro** [comment]
Any of your tests uses the "RefreshDatabase" trait?
