### ISSUE TITLE
Can't make a master route for react/vue.js

### ISSUE THREAD

**Issue by Shivam-SV** [laravel/framework#50856]
### Laravel Version

11.1

### PHP Version

8.3

### Description

I created a project in laravel 11.1 and I try to setup the react js in the project for the frontend. I've add the following snippet in my web.php

`Route::get('/{all?} ', function(){
    return view('app');
})->where('all', '. *');`

But It doesn't work. Is still the way to configure routes. or something else.

### Steps To Reproduce

![image](https://github.com/laravel/framework/assets/96371459/2ce6741a-7c2a-4c11-a13b-de6574d6dee1)

**Comment by rojtjo** [comment]
Looks like there is a space in your where. Try changing `. *` to `.*`

**Comment by Shivam-SV** [comment]
Oh, you are right, it seems Iike I've added a space which prevents the route to be hit.
Thanks for you help
