### ISSUE TITLE
Crash when assign a String in redirectGuestsTo

### ISSUE THREAD

**Issue by MrJmpl3** [laravel/framework#50871]
### Laravel Version

11.1.1

### PHP Version

8.3

### Description

Crash when assign a String in redirectGuestsTo, but the app works when assign a function.

That is rare because in the line https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php#L523 is configure to support string and function

### Steps To Reproduce

I use Inertia and Redis, you only need assign a string in redirectGuestsTo

```
->withMiddleware(function (Middleware $middleware) {
        $middleware
            ->redirectGuestsTo(route('auth.login'))
            ->throttleWithRedis()
            ->web(append: [
                HandleInertiaRequests::class,
                AddLinkHeadersForPreloadedAssets::class,
            ]);
    })
```

**Comment by crynobone** [comment]
But this is valid, right? `->redirectGuestsTo(route('auth.login'))`

**Comment by MrJmpl3** [comment]
> But this is valid, right? `->redirectGuestsTo(route('auth.login'))`

I think is correct, because in the line https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Configuration/Middleware.php#L523, transform the string to function and the types of $guests are "callable|string"

**Comment by crynobone** [comment]
So what's the crash? and actual reproducing step?

**Comment by ahinkle** [comment]
The docs sound pretty clear to use a callback with using routes:

https://laravel.com/docs/11.x/authentication#redirecting-unauthenticated-users

The string is for hardcoded URLs. I believe it's not possible because the app hasn't fully booted yet (the reasoning for the required callback), but I am not entirely sure.

**Comment by driesvints** [comment]
This can only be a hardcoded path or a callback. Never a named route like in the example above because of the reasons @ahinkle listed.
