### ISSUE TITLE
Timeout with Artisan::call() on Laravel 10 + Google App Engine

### ISSUE THREAD

**Issue by sl0wik** [laravel/framework#50914]
### Laravel Version

10.20

### PHP Version

8.2

### Description

After upgrading to Laravel L10, I encountered timeout issues when using `Artisan::call()` within a Google App Engine environment. A simple invocation like `Artisan::call('inspire')` leads to a timeout.

So far attempts to debug or capture more detailed error information have been unsuccessful. It's possibly due to how the Symfony dispatcher works with background processes.

### Steps To Reproduce

1. Pull Firevel (Laravel base modified to work in the read-only App Engine environment)
```
composer create-project firevel/firevel
```

2. Add to `routes/web.php`:
```
Route::get('/inspire', function () {
    return Artisan::call('inspire');
});
````

3. Generate `app.yaml`:
```
php artisan firevel:generate app.yaml
```

4. Deploy app using:
```
gcloud app deploy
```

5. Open host/inspire.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
