### ISSUE TITLE
Queue worker not processing on the queued jobs

### ISSUE THREAD

**Issue by lalit-insnapsys** [laravel/framework#50913]
### Laravel Version

10.44

### PHP Version

8.2.15

### Database Driver & Version

MariaDB 11.3 on Oracle Linux 8.7

### Description

I am having problems on Oracle Linux 8.7 for processing the queued jobs. I am trying to dispatch jobs from UI and they dispatch correctly on the jobs table, since I am using QUEUE_CONNECTION=database in the environment file. 

The problem is when the entry is added to jobs table, attempts column is increment to a value of "1" from "0". My queue workers run from the supervisor setup and in my case I have stopped the supervisor.

Because the attempts count is incremented to 1 and a reserved at column has some timestamp now, I am not sure how does this gets set even after my supervisors are stopped and not running and none of the queue workers are running. Now, since I have set max attempts to 1 in my laravel job file, now even if I run the queue worker manually from the command line, it does not pickup the job from the queue, since attempts is already set to "1" somehow on this oracle linux system. I am not sure if the issue is with OS process or the issue is with MariaDB.

Can any one help me out here so that it will help in my project, since I am helpless from last 15 days and I thought I should give out a shout here for help.

### Steps To Reproduce

1 - Stop all the queue workers
2 - Dispatch job
3 - Run the queue worker to see if the job gets processed successfully.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
