### ISSUE TITLE
Unnecessary "web" guard is registered automatically after upgrading from Laravel v10 to Laravel v11

### ISSUE THREAD

**Issue by 77web** [laravel/framework#50934]
### Laravel Version

11.2.0

### PHP Version

8.3.4

### Database Driver & Version

PostgreSQL v15.0

### Description

It seems that "web" guard is registered automatically after upgrading Laravel from v10 to v11.

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L93-L103
https://github.com/laravel/framework/blob/11.x/config/auth.php#L39-L42

Our product only use custom guards, and we do not need "web" guard at all.
How to remove this "web" guard from `config('auth.guards')` entry?

Possible solution:
Change default guard config to empty.
https://github.com/laravel/framework/blob/11.x/config/auth.php#L39-L42

### Steps To Reproduce

1. Create new Laravel project.
2. edit config/auth.php like this:
```
    'defaults' => [
        'guard' => env('AUTH_GUARD', 'web2'),
        'passwords' => env('AUTH_PASSWORD_BROKER', 'users'),
    ],
    'guards' => [
        'web2' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
```

3. debug `config('auth.guards')` somewhere in the application
```
dd(config('auth.guards'));
// it will show 2 guards: "web", "web2"
```

**Comment by 77web** [comment]
## Temporary workaround for this

Define "web" guard in project's `config/auth.php` even if we do not need one.
```
    'defaults' => [
        'guard' => env('AUTH_GUARD', 'web2'),
        'passwords' => env('AUTH_PASSWORD_BROKER', 'users'),
    ],
    'guards' => [
        'web' => [ // it will not be used anywhere in my application
            'driver' => 'session',
            'provider' => 'users',
        ],
        'web2' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
```

**Comment by crynobone** [comment]
![CleanShot 2024-04-06 at 10 37 49](https://github.com/laravel/framework/assets/172966/875e617f-f9b5-4006-b175-55bccb82fb53)

https://laravel.com/docs/11.x/upgrade#application-structure This wouldn't been needed if the original configuration was kept during the upgrade.
