### ISSUE TITLE
A command like "command:something" is executed by just typing "command:"

### ISSUE THREAD

**Issue by danleal** [laravel/framework#50936]
### Laravel Version

11

### PHP Version

8.2

### Database Driver & Version

PostgreSQL 14

### Description

A command like "command:something" is executed by just typing "command:"

![bug-laravel](https://github.com/laravel/framework/assets/5360720/b06dc44c-d1c0-4c45-8339-df21302c7227)

Would this be a bug?

### Steps To Reproduce

- Create a command with a signature like "command:something"
- Run only "php artisan command:"

**Comment by plumthedev** [comment]
Do you have any other command which is registered with prefix `command:`?

**Comment by crynobone** [comment]
Thanks @plumthedev

**Comment by matiaslauriti** [comment]
Just to add a little bit more clarification for anyone reading this in the future, this is why explained by the Symfony docs: https://symfony.com/doc/current/components/console/usage.html#shortcut-syntax
