### ISSUE TITLE
Laravel 11 has issues with broadcasting.

### ISSUE THREAD

**Issue by zarate02** [laravel/framework#50939]
### Laravel Version

11

### PHP Version

8.3

### Description

When setting up and running broadcasting the same way in Laravel 11 as in Laravel 10, it doesn't work properly. I'm not aware of any changes regarding broadcasting in the official documentation. Could you please let me know if I'm mistaken?

### Steps To Reproduce

laravel new bug-report --github="--public"

**Comment by plumthedev** [comment]
Could you please provide more information and preferable prepare a public repo with broken broadcasting?
You can setup a repo using command: `laravel new bug-report --github="--public"`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by marcos-padilla** [comment]
Here the solution to your problem: [Queue Configuration](https://laravel.com/docs/11.x/broadcasting#queue-configuration). 
You have to setup the queue worker. In development mode is as easy as change de default driver to sync in **config/queue.php** file
