### ISSUE TITLE
Illuminate\Http\Client\Request 'object' function does not type-hint array as a possible type

### ISSUE THREAD

**Issue by SteAshGiga** [laravel/framework#50932]
### Laravel Version

10.33.0

### PHP Version

8.2.7

### Description

The `object` function is type-hinted to return `object|null`.
But in the case when the response body contains a JSON array, the type returned by `$response->object()` is `array`.
 
Ideally, we'd be using the `->object()` function to convert an array of JSON objects into an array of PHP objects, but due to this issue, we have to manually override our code analysis tools, which isn't ideal

I believe this function should return `object|array|null`

### Steps To Reproduce

The following can be input into any Laravel Tinker window. The result is `array`, which is not one of the types specified on the `object()` function
```
use Illuminate\Support\Facades\Http;
$response = Http::get('https://jsonplaceholder.typicode.com/posts')->object();
echo gettype($response);
```

**Comment by buismaarten** [comment]
Maybe you could submit a PR.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!
