### ISSUE TITLE
[11.2] Global Scopes can't be removed from BelongsToMany relations

### ISSUE THREAD

**Issue by ccharz** [laravel/framework#50945]
### Laravel Version

v11.2.0

### PHP Version

8.3

### Database Driver & Version

Sqlite

### Description

As stated in https://github.com/laravel/framework/pull/50849#issuecomment-2036993416 global scopes can currently not be removed from BelongsToMany relations, because the `getGrammar()` is unnecessarily forwarded to the query builders `toBase` method which directly applies the scopes.

### Steps To Reproduce

https://github.com/ccharz/laravel-belongs-to-many-without-scopes/commit/e737068e69cb5780eba74579b77c9b055e708bfd

**Comment by tpetry** [comment]
@plumthedev can you have a look at this? Seems to be triggered by your change.

**Comment by plumthedev** [comment]
Sure, I will take a look 👀

**Comment by plumthedev** [comment]
@ccharz Thanks for your eagle eye 👏 
I have fixed that - code is under review

**Comment by borovez** [comment]
Laravel v11.9.1

I still am unable to remove global scopes from my `belongsToMany` relationship.... I have tried it directly on the `Location` model which works, but if I attempt it on the relation, it doesn't get removed. Am I missing something?

```php
// Location model
protected static function booted(): void
{
   parent::boot();
   static::addGlobalScope(new BelongsToLoggedInUserScope());
}
```
```php
public function locations(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
{
    return $this->belongsToMany(Location::class, 'location_users', 'user_id', 'location_id')
        ->withoutGlobalScope(BelongsToLoggedInUserScope::class);
}
```
