### ISSUE TITLE
PhpUnit now throws warnings: Test code or tested code removed exception handlers other than its own

### ISSUE THREAD

**Issue by elb98rm** [laravel/framework#50951]
### Laravel Version

11.2.0

### PHP Version

8.3

### Database Driver & Version

MySql 8

### Description

As per issue: https://github.com/laravel/framework/issues/49502

When running tests, the vast majority produce the warning: "Test code or tested code removed exception handlers other than its own"

This seems to have been a short lived change in PhpUnit that was reverted... I think it's back now!

### Steps To Reproduce

.. use any repo with existing tests OR:
Install L11.
Run a test on a view using something like $response->assertStatus(200);

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by elb98rm** [comment]
I'm sorry - I don't have time. However, the previous post offered these commands. 

laravel new laravel
cd laravel
./vendor/bin/phpunit

**Comment by driesvints** [comment]
Just works for me:

<img width="930" alt="Screenshot 2024-04-08 at 10 23 58" src="https://github.com/laravel/framework/assets/594614/4e767706-1c91-4dc9-a48f-6727d359acae">

**Comment by elb98rm** [comment]
![image](https://github.com/laravel/framework/assets/2630101/45405b9e-9f09-4391-aff0-ae67c98c4c9c)

Doesn't for me. Unfortunately due to a work deadline, I can't spend time on the bug. Hopefully someone else will be able to help.
As I've mentioned, this is a duplicate that looks like it's been re-introduced by PHPUnit, and other people have also seen it. 

Hope it gets resolved.

**Comment by AdrienPoupa** [comment]
I am also getting this on a new Laravel 11 project

**Comment by pps1** [comment]
This also happens on Symfony 7.0.3 controller tests

**Comment by elb98rm** [comment]
@driesvints is this being looked at? It's not a closed issue.

**Comment by elb98rm** [comment]
Ok, Ill look at trying to make a suitble test later today.

**Comment by crishoj** [comment]
If `$this->createApplication()` is called in the test constructor, the warnings appear.

(The call to `createApplication()` is a workaround for `A facade root has not been set` when interacting with the framework in PHPUnit 11 static `@dataProvider`. I would be happy to learn about a better workaround.)

**Comment by crynobone** [comment]
@crishoj 

![CleanShot 2024-04-18 at 14 31 32](https://github.com/laravel/framework/assets/172966/cfb063d8-b69f-4be6-aa2c-64fd7658ae94)

Read the Caveat section from https://tighten.com/insights/tidying-up-your-phpunit-tests-with-data-providers/

**Comment by Twinber** [comment]
test code or tested code removed exception handlers other than its own

**Comment by qmb-kschuster** [comment]
I guess the error comes for me because I am using a custom bootstrap file for tests. My fix is to call `HandleExceptions::flushState();` after `$app->make(Kernel::class)->bootstrap();`

**Comment by WorthLMS** [comment]
> Using a fresh Laravel 12. I guess the error comes for me because I am using a custom bootstrap file for tests. My fix is to call `HandleExceptions::flushState();` after `$app->make(Kernel::class)->bootstrap();`
> 
> To make sure to be able to test Exceptions with `$this->expectException()` one must add `$this->withoutExceptionHandling();` at the beginning of the test method.

OMG Thank you!

**Comment by negoziator** [comment]
For those still struggling with this. As mentioned before - adding `HandleExceptions::flushState();` seems to do the trick.

Jus to be clear:

In `tests/TestsCase.php`

Override the `createApplication()` method and add `HandleExceptions::flushState();` before returning `$app`

```php
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require Application::inferBasePath().'/bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        HandleExceptions::flushState(); // <--- Add this line

        return $app;
    }
```

**Comment by andreshg112** [comment]
@negoziato , https://github.com/laravel/framework/issues/49502#issuecomment-2878157050

**Comment by Phabyd** [comment]
In my case Newrelic was adding "newrelic_exception_handler" to backupGlobalExceptionHandlers and it was causing error, nothing helped.

You can find what is causing problem in 
vendor/phpunit/phpunit/src/Framework/TestCase.php:restoreGlobalErrorExceptionHandlers()

`
dd([
            'activeExceptionHandlers' => $activeExceptionHandlers,
            'backupGlobalExceptionHandlers' => $this->backupGlobalExceptionHandlers]
        );
`

Fixed adding to newrelic.ini:

`newrelic.special = "no_exception_handler"`
