### ISSUE TITLE
SyncQueue invokes createPayload with parameter $queue as null while phpdoc declares it should be string

### ISSUE THREAD

**Issue by SyuTingSong** [laravel/framework#50993]
### Laravel Version

10.48.4

### PHP Version

8.3.4

### Description

I am writing a customized create payload hook closure via `Queue::createPayloadUsing`. The phpdoc indicates that the callback should be `callable(string, string, array): array`, so I passed a Closure with parameter & return typehint into it.
A TypeError occurred when I dispatch jobs  via sync queue.

I investigated this issue and found that the callback is invoked by `\Illuminate\Queue\Queue::withCreatePayloadHooks` and the parameter `$queue` was initially coming from `\Illuminate\Queue\SyncQueue::push`.
The function `\Illuminate\Queue\Queue::createPayload` called by `\Illuminate\Queue\SyncQueue::push` expects the second parameter `$queue` to be a string, but `null` given.

Either redeclaring the phpdoc type of parameter `$queue` to `string|null` for the functions `createPayload`, `createObjectPayload`, `createStringPayload`, `withCreatePayloadHooks` or declare a default string queue name for SyncQueue is acceptable.

### Steps To Reproduce

1. Declare create payload hook In `AppServiceProvider`:
```php
public function boot(): void
{
    Queue::createPayloadUsing(function(string $connection, string $queue, array $payload): array {
        return ['context_user_id' => $this->extractUserIdFromContext()];
    })
}
```

2. Dispatch a sync job in somewhere:

```php
public function update(User $user): JsonResponse {
    // Save changes.

    dispatch(new \App\Jobs\SendProfileUpdatedEmail($user))->afterResponse();

    return response($user);
}
```

**Comment by driesvints** [comment]
We don't type `callable(string, string, array)` anywhere?

**Comment by SyuTingSong** [comment]
Yes, you didn't type the callback function, that's why I am using *indicates* instead of declares.

The callback is invoked by `Queue::withCreatePayloadHooks` which has [phpdoc declaring the parameter `$queue` is a string](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/Queue.php#L300).

And the parameter `$queue` is passed in from [`Queue::createObjectPayload`](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/Queue.php#L142) or [`Queue::createStringPayload`](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/Queue.php#L267) which is also declared as string in phpdoc. And their upstream is [`Queue::createPayloadArray`](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/Queue.php#L126C24-L126C42) and [`Queue::createPayload`](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/Queue.php#L101). They are declared the parameter `$queue` as string, too.

However, unlike other Queue class, the [`SyncQueue::push`](https://github.com/laravel/framework/blob/7e0701bf59cb76a51f7c1f7bea51c0c0c29c0b72/src/Illuminate/Queue/SyncQueue.php#L38) passes `null` instead of a default string to createPayload.

**Comment by driesvints** [comment]
Hi @SyuTingSong. Thanks for clarifying that. It indeed seems `$queue` can be `null`. This indeed isn't indicated entirely through docblocks. I personally don't feel we really need to change to the docblocks anything but you can always attempt a PR if you like.
