### ISSUE TITLE
Blade Component Attributes: Passing boolean-style (without value) attributes

### ISSUE THREAD

**Issue by devajmeireles** [laravel/framework#50994]
### Laravel Version

11.3.0

### PHP Version

8.3.4

### Database Driver & Version

N/A

### Description

In some cases, we need to pass an attribute to a component using boolean style, i.e. without setting a value (such as empty), as is the case with things like `wire:poll`. A few days ago I noticed this:

Using like this:

```blade
<x-loading wire:poll />
```

Generates this HTML:

```blade
<div ... wire:poll="wire:poll">
```

Instead of:

```blade
<div ... wire:poll>
```

Therefore, using things like `wire:poll` ends up generating: `wire:poll="wire:poll"` which ends up becoming a problem, even if a small one. There must certainly be several other cases where we need to pass attributes in this way, I'm just not remembering it now (besides, of course, things like required and disabled, where the value is optional)

### Steps To Reproduce

1. Create a dummy component
2. Insert the `{{ $attributes }}` on this
3. Use the component passing a component attribute like `wire:poll`
4. Use your browser dev tools to check the final HTML generated: `wire:poll="wire:poll"`

**Comment by driesvints** [comment]
Yeah, I can reproduce this. Looks like this isn't supported at this time, sorry. I suggest you add a boolean check within the component itself to dynamically enable this. We'd appreciate a PR to maybe escape attributes like this so they're unaltered.
