### ISSUE TITLE
Connection Refused Redis Clusters

### ISSUE THREAD

**Issue by anabeto93** [laravel/framework#51011]
### Laravel Version

11.x

### PHP Version

8.3

### Database Driver & Version

sqlite

### Description

When you follow the official documentation here [https://laravel.com/docs/11.x/redis#clusters](https://laravel.com/docs/11.x/redis#clusters) on how to use redis clusters with Laravel, you'll mostly end up with a connection refused error. Even if you can confirm your credentials are correct and you're following all the steps described, your Laravel still fails to talk to the cluster.

### Steps To Reproduce

1. Setup a basic Laravel 11 or 10.x app
2. Run it with Laravel sail as described here [https://laravel.com/docs/11.x/sail](https://laravel.com/docs/11.x/sail) Or Run it how you are used to setting up an app
3. Setup your redis or keydb cluster and follow the instructions here to configure your app to talk to it [https://laravel.com/docs/11.x/redis#clusters](https://laravel.com/docs/11.x/redis#clusters)
    A sample valid laravel config that I have for `config('database.redis.clusters)` is below 
    ```php
     [
    "default" => [
        [
            "host" => "keydb1",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
        [
            "host" => "keydb2",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
        [
            "host" => "keydb3",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
    ],
    "cache" => [
        [
            "host" => "keydb1",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
        [
            "host" => "keydb2",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
        [
            "host" => "keydb3",
            "port" => "6379",
            "password" => null,
            "database" => "0",
        ],
    ],
    "options" => ["cluster" => "redis", "prefix" => "laravel_database_"],
    ]

 5. Ensure you have debugging enabled (`APP_DEBUG=true`) in your `.env` file and then modify your `routes/web.php` with this 
 
    ```php
    Route::get('/', function () {
        cache()->store('redis')->set(request()->ip(), 'Hello, World!', 60);
        return view('welcome');
    });
6. Try accessing the default route in your browser `/`

**Comment by driesvints** [comment]
Thanks but please just resend your PR with a clear description like Taylor asked.
