### ISSUE TITLE
Pivot events not fired when using `updateExistingPivot` with custom pivot class and `wherePivot` condition

### ISSUE THREAD

**Issue by maximepvrt** [laravel/framework#51019]
### Laravel Version

v10.48.7

### PHP Version

8.2.13

### Description

There seems to be an issue with Laravel where pivot events are not triggered when using the updateExistingPivot method alongside a custom pivot class and a wherePivot condition.

Here's a scenario highlighting the problem:
```
$user->groups()->attach([$group1->id => ['status' => GroupPivot::STATUS_PENDING]]);
> saving event fire
$user->groups()->updateExistingPivot($group1->id, ['status' => GroupPivot::STATUS_ACCEPTED]);
> saving event fire

$user->groups()->wherePivot('status', GroupPivot::STATUS_PENDING)->attach([$group2->id => ['status' => GroupPivot::STATUS_PENDING]]);
> saving event fire
$user->groups()->wherePivot('status', GroupPivot::STATUS_PENDING)->updateExistingPivot($group2->id, ['status' => GroupPivot::STATUS_ACCEPTED]);
```

In the provided code, the first set of operations (without the wherePivot condition) behaves as expected. However, the second set of operations fails to fire events when the relation utilizing updateExistingPivot alongside a wherePivot condition.

### Steps To Reproduce

- clone : https://github.com/maximepvrt/laravel-test-relation
- configure a database in .env
- run `php artisan migrate`
- run `php artisan app:test`

**Comment by maximepvrt** [comment]
I found it's because of this addition, the pivot class is not used if there are wherePivots https://github.com/laravel/framework/commit/cadea88cc2007cedb825b5d86a0fb184dcd76ab4

I'm not sure I understand why, I tried removing this add condition the unit tests still pass.

If you think we should exclude the use of custom pivot class in this case, perhaps this should throw an error if a wherePivot is present ?

@driesvints @staudenmeir

**Comment by driesvints** [comment]
@maximepvrt heya. That change is pretty old and given Taylor did that specifically I feel like it's intended. You can try a PR if you like and add a test?
