### ISSUE TITLE
Laravel 11 command choice test issue

### ISSUE THREAD

**Issue by gmaccario** [laravel/framework#51020]
### Laravel Version

11

### PHP Version

8.2

### Description

I am implementing a Laravel 11 command, with choice, and when I test it I receive this message:

Output "blablabla" was not printed.

I tried then the example on the Laravel 11 documentation https://laravel.com/docs/11.x/console-tests

```
$name = $this->ask('What is your name?');

$language = $this->choice('Which language do you prefer?', [
    'PHP',
    'Ruby',
    'Python',
]);

$this->line('Your name is '.$name.' and you prefer '.$language.'.');
```

```
$this->artisan('question')
     ->expectsQuestion('What is your name?', 'Taylor Otwell')
     ->expectsQuestion('Which language do you prefer?', 'PHP')
     ->expectsOutput('Your name is Taylor Otwell and you prefer PHP.')
     ->doesntExpectOutput('Your name is Taylor Otwell and you prefer Ruby.')
     ->expectsOutputToContain('Taylor Otwell')
     ->doesntExpectOutputToContain('you prefer Ruby')
     ->assertExitCode(0);
```

but I receive this message:

Output does not contain "Taylor Otwell".

How do I test a choice command using Laravel 11?

### Steps To Reproduce

Create a command and follow the instructions https://laravel.com/docs/11.x/console-tests
Create a Test for the Command
Run the test

**Comment by driesvints** [comment]
That's an odd one... I get the same thing. From what I can gather in the code I don't think it's possible to assert output after it's been asserted once.

**Comment by gmaccario** [comment]
Thank you @driesvints for your reply. Is there currently any workaround?

**Comment by driesvints** [comment]
No

**Comment by gmaccario** [comment]
OK thank you. So basically a command that contains a choice instruction is not testable right now?

**Comment by taylorotwell** [comment]
Seems that way? PRs welcome 🤘

**Comment by gcjbr** [comment]
I found the issue, but don't understand mockery enough to fix it.

Tried for a couple hours by failed :(


If anyone wants to give it a poke:

On PendingCommand we check for askQuestion types of commands and clean the expectedQuestions array as we go.

Same should be done for writeln type of commands. 

The gist of it is, at the end of the assertions, PendingCommand will call run() and fail if any of the arrays if things you wanna very is not empty. 

Verification is done previously by mockConsoleOutput(), as I meantioned.


Something like:


`        $mock = Mockery::mock(OutputStyle::class.'[askQuestion, writeln]', [
            new ArrayInput($this->parameters), $this->createABufferedOutputMock(),
        ]);


        foreach ($this->test->expectedOutputSubstrings as $substring) {
            $mock->shouldReceive('writeln')
                ->once()
                ->with(Mockery::type('string'), Mockery::type('int'))
                ->andReturnUsing(function ($text) {
                    return $text;
                });

        }`

If anyone try it they'll see where I got stuck with Mockery.

**Comment by yourchocomate** [comment]
@gmaccario Can you clarify what you are expecting or what should be th expected behaviour?

Cause the order you have provided can't be valid as,

you already expecting an exact output by clarifying expectsOutput('Your name is Taylor Otwell and you prefer PHP.')
again it would be unnecessary - also the assertion will not happen for doesntExpectOutput()

**Comment by gmaccario** [comment]
@yourchocomate I tried the example in the official documentation https://laravel.com/docs/11.x/console-tests

**Comment by yourchocomate** [comment]
> @yourchocomate I tried the example in the official documentation https://laravel.com/docs/11.x/console-tests

Okay! But asserting expectsOutputToContain() after expectsOutput('some text') will lead to fail in test as you're already expecting for a specific output rather than a portion

**Comment by gmaccario** [comment]
@yourchocomate As I said, I was trying the example on the official documentation, which currently looks different compared to a week ago. I leave you the old version here https://web.archive.org/web/20240312151913/https://laravel.com/docs/11.x/console-tests

**Comment by driesvints** [comment]
Just gonna close this one right now as not supported, sorry.
