### ISSUE TITLE
php artisan view:cache returns an error since laravel 11 : Unable to locate a class or view for component [mail::message]. 

### ISSUE THREAD

**Issue by Lukimer** [laravel/framework#51025]
### Laravel Version

11

### PHP Version

8.3.4

### Description

Since I run a composer update to get the latest laravel version (11), my deployment script crashes.

If I go back to laravel 10.48.7, the error does not occur anymore.

This bug just like the issues: https://github.com/laravel/framework/issues/44544

### Steps To Reproduce

Just run these commands:

composer dump-autoload
php artisan view:cache

**Comment by devajmeireles** [comment]
Not reproducible in fresh Laravel 11.

**Comment by driesvints** [comment]
Can't reproduce this sorry.

**Comment by Lukimer** [comment]
Hi, All

I found a issue, it is not related to laravel 11 upgrading, It was raised by jetstream upgrade to 5.X.
I solved by:
1. copying all views from jetstream/livewire/ to resources/views
2. removing all '-jet' in <x-jet-xxx> header in all components views
3. php artisan view:cache
4. no error now.

And Sorry for posted to wrong topic...

Thanks for help.
Best
