### ISSUE TITLE
onEachSide

### ISSUE THREAD

**Issue by ericthanhtung** [laravel/framework#51024]
### Laravel Version

10.10

### PHP Version

8.2.12

### Description

I'm having problems with onEachSide. Please help me
my code: 
![image](https://github.com/laravel/framework/assets/95896012/4f561225-9098-4a91-b7ac-d9e9576737d8)
![image](https://github.com/laravel/framework/assets/95896012/73022adf-8383-4d3a-a459-90023e52e22f)

![Screenshot from 2024-04-11 23-36-14](https://github.com/laravel/framework/assets/95896012/256c7417-2153-4485-9f82-c19cf31504d9)

### Steps To Reproduce

<?php

namespace App\Livewire;

use App\Models\Quiz;
use Livewire\Component;

class SearchQuestion extends Component
{
    public $key;

    protected $queryString = ['key'];

    public function render()
    {
        $quizzes = Quiz::where('title', 'like', '%' . $this->key . '%')->orWhere('id', $this->key)->paginate(5);
        return view('livewire.search-question', compact('quizzes'));
    }
}

<div class="flex-1 flex flex-col gap-8">
                    @foreach($quizzes as $quiz)
                        <div class="bg-[#394b59] rounded-xl pl-10 pr-4 pt-5 pb-10">
                            <livewire:question :qid="$quiz->id"/>
                        </div>
                    @endforeach
                    <div class="mt-6">
                        {{ $quizzes->onEachSide(6)->withQueryString()->links() }}
                    </div>
                </div>

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
