### ISSUE TITLE
[10.x] Illegal operator and value combination `whereRelation` with three parameters (where the value is `<`)

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/framework#51033]
### Laravel Version

10.48.7

### PHP Version

8.3.3

### Database Driver & Version

MySQL 8.0.32

### Description

I'm getting an error (Illegal operator and value combination) when use `whereRelation` with three parameters.

<img width="952" alt="image" src="https://github.com/laravel/framework/assets/7753600/5fe4442a-93f2-465f-8e6d-5aa5e3fcfdef">

The interesting thing here is the `$barcode` variable contains the `<` character as value for searching.

But by the documentation if we are omitting the `operator` then the `=` will be used by default.

### Steps To Reproduce

Call the method `whereRelation` with three parameters where value is `<`.

```
Product::query()->whereRelation('ingredients', 'barcode', '<')->get();
```

**Comment by driesvints** [comment]
I think you forgot to provide the value for the fourth parameter? https://laravel.com/docs/11.x/eloquent-relationships#inline-relationship-existence-queries

<img width="754" alt="Screenshot 2024-04-12 at 13 29 55" src="https://github.com/laravel/framework/assets/594614/624c0544-a070-41f0-a552-b84ac94ed947">

**Comment by siarheipashkevich** [comment]
<img width="738" alt="image" src="https://github.com/laravel/framework/assets/7753600/9d0bf8c3-12da-404f-962b-31463cc8c409">

But above we have the example where we may omit the operator.

**Comment by driesvints** [comment]
That's a boolean check, not a greater than comparison.

**Comment by siarheipashkevich** [comment]
@driesvints do you mean that the three parameters can be used only with boolean values? It's very strange!

What about this?

```
Product::query()->where('barcode', '<')->get();
```

**Comment by driesvints** [comment]
You're not comparing anything against. To what is it lower than? Can you please try passing the value you want to compare to?

**Comment by siarheipashkevich** [comment]
@driesvints my search value is `<` as I described above. 

`<` - is not the operator it's the value by which I want to find the product.

```
select * from products where barcode = '<';
```

Do you understand me?

**Comment by driesvints** [comment]
Ah I finally see what you mean. Yeah unfortunately you'll have to try something like this:

`Product::query()->whereRelation('ingredients', 'barcode', '=', '<')->get();`

Does that work?

**Comment by siarheipashkevich** [comment]
Yes I already fixed by this way, but it's not obvious. Maybe we need add some note to the documentation about this?

Do you think it's a problem or not?

**Comment by driesvints** [comment]
I personally think it's pretty obvious, sorry. But you can always attempt to PR the docs. Thanks.

**Comment by siarheipashkevich** [comment]
@driesvints thanks for you response.
