### ISSUE TITLE
SQS Job Driver - Visibility Timeout Mapped As String

### ISSUE THREAD

**Issue by andrew-belac** [laravel/framework#51045]
### Laravel Version

10.48.7

### PHP Version

8.2

### Description

See previous issue https://github.com/laravel/framework/issues/50397.  

Bug is present on Laravel 10 and possibly all currently supported versions.

When dispatching a job visibility timeout is passed in as a string.  The AWS PHP SDK works up to version aws/aws-sdk-php:3.285.0.  Version aws/aws-sdk-php:3.285.1 and above stop working with the following error message

_**The provided type for `Attributes -> ReceiveMessageWaitTimeSeconds` value was `integer`. The modeled type is `string`.**_

The error is raised at _**/vendor/aws/aws-sdk-php/src/QueryCompatibleInputMiddleware.php:161**_

![AWS PHP Laravel SQS Error](https://github.com/laravel/framework/assets/63802538/6306332b-1871-4927-bd02-e33b963b487d)

The error was encountered using Laravel Vapor.  But the previous issue raised suggests it is not Vapor specific.

### Steps To Reproduce

- Configure SQS as the job driver
- Dispatch a job
- Error is raised when the driver attempts to push the job to SQS

**Comment by crynobone** [comment]
I cannot find any references where release() method can be called using `string`.

**Comment by andrew-belac** [comment]
> I cannot find any references where release() method can be called using `string`.

I am referring to how Laravel sets some AWS QueueAttributes as integers instead of strings.  My understanding is the AWS documentation is incorrect in that it states integers when the API takes strings.  

If you look in the vendor folder of aws/aws-sdk-php:3.285.1 you will see under src/data/sqs/2012-11-05/api-2.json.php you will see the specification has all QueueAttributes being string.  Seems to be due to the migration from XML to JSON.

![Screenshot from 2024-04-15 07-50-47](https://github.com/laravel/framework/assets/63802538/d326fc02-28c7-436e-8f35-3565e0d75faf)

With this version and above I receieve the errors in the log.  But if I move revert to aws/aws-sdk-php:3.285.0 of the SDK then no errors are logged.

**Comment by andrew-belac** [comment]
@crynobone Apologies the problem was in one job we have using the SQSClient directly.  I also confused queue attributes being strings with message attributes it seems.

**Comment by andrew-belac** [comment]
Closing
