### ISSUE TITLE
Laravel UI

### ISSUE THREAD

**Issue by deyan-ardi** [laravel/framework#51064]
### Laravel Version

11.3.1

### PHP Version

8.3.2

### Description

Sorry, I have to report a bug in this repository because the Laravel UI repository does not open discussions for existing issues. I am experiencing a problem where I cannot install Laravel UI when I use PHP 8.3. The following is a problem that I experienced, I hope it can help me without having to downgrade the php version that I am using

![gambar](https://github.com/laravel/framework/assets/60816261/11f8215d-3635-484c-96bd-c38716d3cf4e)

### Steps To Reproduce

1. Install laravel 11
2. Choose php 8.3.xx
3. Run `composer require laravel/ui`
4. In my case, error like this
![gambar](https://github.com/laravel/framework/assets/60816261/b35e80e2-fc82-47f0-8ad5-af3fe469c5aa)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
