### ISSUE TITLE
Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/a/Downloads/b/server.php on line 8

### ISSUE THREAD

**Issue by phpmac** [laravel/framework#51096]
### Laravel Version

10

### PHP Version

8.2

### Description

http://127.0.0.1:8000//agent

<img width="1588" alt="截屏2024-04-17 17 40 34" src="https://github.com/laravel/framework/assets/86544347/246032cb-2b1a-441b-bd62-373acf7ae0b9">

<img width="1486" alt="截屏2024-04-17 17 40 52" src="https://github.com/laravel/framework/assets/86544347/2786f4af-c87a-45ce-bc2c-b89cc317a6a8">

### Steps To Reproduce

Is it a problem with my own routing configuration?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
