### ISSUE TITLE
Laravel 11 SQLite Migration Failure: Error Dropping Columns with RefreshDatabase in PHPUnit Tests

### ISSUE THREAD

**Issue by ashcrok** [laravel/framework#51116]
### Laravel Version

11.4.0

### PHP Version

8.2.3

### Database Driver & Version

Sqlite

### Description

In Laravel 11, running tests in memory using SQLite and the RefreshDatabase trait causes failures when migrations involve dropping columns.

### Error Encountered

```
SQLSTATE[HY000]: General error: 1 near "drop": syntax error (Connection: sqlite, SQL: alter table "users" drop column "test")
```

### Additional Information

- In previous Laravel versions (e.g., v10), this issue is not observed.
- The error appears to be related to changes in the handling of SQLite migrations in Laravel 11, which now attempts to drop columns—a feature supported in SQLite 3.35 but not in the 3.34.1 version bundled with PHP 8.2.x.

### Possible solutions

- A potential workaround could be to manually update the SQLite library to version 3.35 or newer. However, this needs confirmation for compatibility with PHP 8.2.x.
- Another approach might be to modify the migration strategy in Laravel when detecting an older SQLite version.
- Use PHP 8.3.x, which uses a higher version of sqlite which solves the issue mentioned above.

### Steps To Reproduce

1. Create a new Laravel project.
2. Setup PHPUnit for testing with the connection set to SQLite and the database set to :memory:.
3. Create multiple migrations that add and then remove columns.
4. Run the tests using the created setup.

**Comment by crynobone** [comment]
Laravel 11 requires SQLite 3.35+ https://laravel.com/docs/11.x/database#introduction

**Comment by driesvints** [comment]
thanks @crynobone

**Comment by evgpisarchik** [comment]
@crynobone Thanks! You saved my day
