### ISSUE TITLE
Nova on Laravel 11 crashes with 'Route [login] not defined'

### ISSUE THREAD

**Issue by cameronmurphy** [laravel/framework#51113]
### Laravel Version

11.0.6

### PHP Version

8.3.6

### Database Driver & Version

Postgres 15.6

### Description

Installing Nova into a fresh Laravel 11 project throws an error "Route [login] not defined". Navigating to `/nova/login` works, however, and `artisan route:list` does list `nova/login` as a route.

### Steps To Reproduce

```shell
composer create-project laravel/laravel laravel-nova
cd laravel-nova
composer config repositories.nova composer https://nova.laravel.com
composer require laravel/nova
php artisan sail:install # Choose pgsql
php artisan nova:install
vendor/bin/sail up
vendor/bin/sail artisan migrate
```

Open [http://localhost/nova](http://localhost/nova) in a browser. 

![image](https://github.com/laravel/framework/assets/1300032/e00c1b52-8cca-4248-bc8f-875c96cf3c5e)

**Comment by driesvints** [comment]
Please report this on the nova issue tracker.

**Comment by crynobone** [comment]
Laravel skeleton and Nova doesn't have `route('login')` available by default and cause this error.
