### ISSUE TITLE
Custom route binding for enums doesn't work anymore

### ISSUE THREAD

**Issue by larskoole** [laravel/framework#51114]
### Laravel Version

11.4.0

### PHP Version

8.3.4

### Description

We're using custom route binding to convert a fancy string to an int backed enum but it breaks with the new enum handling in routes.

For example `https://test.test/sales-orders/...` will translate `sales-orders` to `OrderType::SALES_ORDER`.
But with the new changes from https://github.com/laravel/framework/pull/51029 this doesn't work anymore.
It tries to convert `$parameterValue` to a `string` but it's already `OrderType::SALES_ORDER`.

web.php
```php
Route::get('/{orderType}');
```

AppServiceProvider.php
```php
Route::bind('orderType', function ($orderType) {
    return match ($orderType) {
        'sales-orders' => OrderType::SALES_ORDER,
        default => abort(404),
    };
});
```

We've fixed the issue by not returning the instantiated enum but just extracting the value out of it, aka returning an int.
Would be cool if `$parameterValue` could be checked to see if it's already an instantiated enum.

### Steps To Reproduce

Create an int backed enum
```php
<?php

namespace App\Enums;

enum OrderType: int
{
    case SALES_ORDER = 1;
}
```

Add a route to the web.php
```php
Route::get('/{orderType}');
```

Add model binding to the AppServiceProvider.php
```php
Route::bind('orderType', function ($orderType) {
    return match ($orderType) {
        'sales-orders' => OrderType::SALES_ORDER,
        default => abort(404),
    };
});
```

Navigate to `https://yourdomain.test/sales-orders`

**Comment by driesvints** [comment]
Thank you. I sent in a revert: https://github.com/laravel/framework/pull/51119
