### ISSUE TITLE
WithoutRelations Attribute is not respected by SerializesModels, when the attribute is on a parent class

### ISSUE THREAD

**Issue by JonathanGawrych** [laravel/framework#51125]
### Laravel Version

10.46.0

### PHP Version

8.3.3

### Description

We would like to use the `Illuminate\Queue\Attributes\WithoutRelations` attribute on an abstract event, that is extended by multiple events.

However, [SerializeModels::__serialize()](https://github.com/laravel/framework/blob/d18097473e1826b0e8f354ad2ea623b4d8293b08/src/Illuminate/Queue/SerializesModels.php#L27) uses [ReflectionClass::getAttributes()](https://www.php.net/manual/en/reflectionclass.getattributes.php) to see if `WithoutRelations` is used, which does not detect inheritance. This was confusing for us when we saw the relations were still serialized.

Could we make SerializeModels detected inheritance on classes? Maybe something like:
```php
$ancestorReflectionClass = $reflectionClass;
$classLevelWithoutRelations = false;
while (! $classLevelWithoutRelations && $ancestorReflectionClass) {
    $classLevelWithoutRelations = ! empty($ancestorReflectionClass->getAttributes(WithoutRelations::class));
    $ancestorReflectionClass = $ancestorReflectionClass->getParentClass();
}
```

### Steps To Reproduce

If you define events inheriting from a parent event

```php
#[WithoutRelations]
abstract class AbstractSubmissionEvent
{
    use Dispatchable, SerializesModels;

    public function __construct (public Submission $submission)
    {
    }
}

class SubmissionGradeDeleted extends AbstractSubmissionEvent
{
}

class SubmissionFeedbackPublished extends AbstractSubmissionEvent
{
}

// etc
```

Then serialize it (we are doing `::dispatch()` to put it into a queued listener, but you can see it easier by directly serializing it)
```php
$submission = Submission::with('comments')->first();
serialize(new SubmissionFeedbackPublished($submission));
// notice that the string will have "s:9:"relations";a:1:{i:0;s:8:"comments";}
// despite the WithoutRelations attribute on AbstractSubmissionEvent
```

**Comment by driesvints** [comment]
Heya, this indeed isn't supported at this time. Feel free to attempt a PR. Thanks!
