### ISSUE TITLE
Redis stores number as string

### ISSUE THREAD

**Issue by vatsake** [laravel/framework#51124]
### Laravel Version

11.4

### PHP Version

8.2

### Database Driver & Version

phpredis, redis

### Description

Storing numeric values in redis returns the values as strings.
I understand that redis cannot store numeric values ([redis data-types](https://redis.io/docs/latest/develop/data-types/)), so I don't know if this issue can be addressed...

### Steps To Reproduce

```
Cache::put('test', 1);
Cache::get('test'); // Returns "1"
```

**Comment by gcjbr** [comment]
This is just how Redis works:

https://redis.io/docs/latest/develop/data-types/#lists

**Comment by crynobone** [comment]
thanks @gcjbr
