### ISSUE TITLE
Issues with Testing and Routing After Upgrading to Laravel 11.0

### ISSUE THREAD

**Issue by Recrus** [laravel/framework#51145]
### Laravel Version

11.2.0

### PHP Version

8.2

### Description

Pre-story: After upgrading Laravel and implementing some changes, I ran php artisan config:clear before executing my tests. Surprisingly, about 90% of my tests failed, and I noticed that the database was being refreshed unexpectedly. Upon further investigation, I realized that the application was referencing the .env file instead of the .env.testing. This issue caused the application to interact with the actual MySQL database instead of using the intended in-memory SQLite database for testing (fortunately, I had a database dump available).

Initial Findings:
- The application was using settings from the .env file instead of .env.testing.
- Discovered that certain crucial lines in the .env.testing were commented out, particularly those setting the database connection to SQLite (but earlier everything worked fine).
- After uncommenting these lines and ensuring the database was set to SQLite, some tests still failed.

`phpunit.xml` before:

```
        <!-- <env name="DB_CONNECTION" value="sqlite"/> -->
        <!-- <env name="DB_DATABASE" value=":memory:"/> -->
 ```

Specific Issues with Routing:

- Tests associated with routes configured under the client_account domain consistently failed by returning a 404 error.

Configuration in api.php:

```php
Route::group(['domain' => $domains['system'], 'middleware' => ['authOneOf:api_token', 'authOneOf:api', 'api']], function () {
 //my routes
}

Route::group(['domain' => $domains['client_account'], 'prefix' => 'v1/client', 'middleware' => ['authOneOf:client', 'api']], function () {
 //my routes
}
```

- It appears the testing environment no longer recognizes or properly handles requests to the second client domain (with not full uri).

Temporary Solution:
- Had to adjust tests to use the full URL for the client_account routes instead of relative paths.
- Modified phpunit.xml to explicitly define the APP_URL and other environment variables:

`
<env name="APP_URL" value="http://system"/>
<env name="SYSTEM_API_DOMAIN" value="http://system"/>
<env name="CLIENT_ACCOUNT_API_DOMAIN" value="http://client_account"/>
`

Ongoing Issues:
- A newly created route in api.php works in tests but fails when called from the frontend application.
- After making certain changes and clearing the config (via `php artisan config:clear`), encountered new errors and the database configuration reverted to MySQL unexpectedly.

Questions:

- Could the version of PHPUnit (^10.1) be incompatible with Laravel 11's requirements for testing?
- What are the specific requirements or configurations needed to handle subdomain routing and database management in Laravel 11 for testing environments?

I am seeking guidance on how to stabilize the testing environment and ensure consistent handling of database and route configurations, especially concerning different subdomains.

### Steps To Reproduce

1. Upgraded Laravel from version 10.x to 11.0.
2. Ran php artisan config:clear before executing tests.
3. Noticed that ~90% of tests failed, and the application was unintentionally interacting with the production MySQL database instead of the intended SQLite database in memory.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
