### ISSUE TITLE
Passport issue in laravel 11

### ISSUE THREAD

**Issue by Dhairyapatel273** [laravel/framework#51144]
### Laravel Version

11.4

### PHP Version

8.2.12

### Database Driver & Version

MariaDB 10.4.32

### Description

passport is alreay installed in my project but when i execute "php artisan passport:install" command in my vscode terminal it generates new migrations everytime in the same project and asks me to run migration of the remaining tables remaining tables includes newly generated passport migration`s table
![Screenshot 2024-04-20 002303](https://github.com/laravel/framework/assets/75977630/aafe9b26-e396-4ed4-936e-c09bcc6a39ee)
this is issue is coming in my device for the second time 

### Steps To Reproduce

Step 1: create new laravel project with latest version
step 2: execte command "composer require passport"
Error: it throws error of denependenices and required package sodium 
Solution: execute command "composer require passport --ignore-platform-reqs" then it will work.
Step 3:after this everytime you run command "php artisan passport:install".
It showing the above bug.[https://github.com/Dhairyapatel273/Farm-Management.git](url)

**Comment by akr4m** [comment]
For Laravel 11, why are running this command `composer require passport`? 
Laravel <10 version used to run this command.
In latest L11 [documentation](https://laravel.com/docs/11.x/passport#installation), you don't have to run that command.
Run `php artisan install:api --passport` command.

This command will publish and run the database migrations necessary for creating the tables your application needs to store OAuth2 clients and access tokens. The command will also create the encryption keys required to generate secure access tokens.

**Comment by driesvints** [comment]
> passport is alreay installed in my project but when i execute "php artisan passport:install" command 

You don't need to re-run this command if you have passport already installed.

**Comment by Dhairyapatel273** [comment]
My personal access token and password grant client is not generating
successfully that's why I executed multiple times
