### ISSUE TITLE
Throttle middleware with unnamed limiters behave weirdly

### ISSUE THREAD

**Issue by timmylindh** [laravel/framework#51151]
### Laravel Version

11.2.0

### PHP Version

8.2

### Description

When using non-named throttle middleware, such as throttle:10,60 (10 requests / 60 min) on a route the limits seem to be random.

Everything works as expected when using *RateLimiter::for* and named limiters however.

### Steps To Reproduce

For instance I have the following route configuration in bootstrap/app.php, with *throttle:150,1*.
```php
  ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/healthy',
        then: function ($router) {
            Route::middleware(['api', 'auth:api', 'throttle:150,1'])
                ->prefix('api/v1')
                ->group(base_path('routes/api.php'));
 ```
 
 Then in my route file:
 
 ```php
     Route::prefix('/groups')->group(function () {
        Route::middleware('throttle:10,60')->post('/{group}/posts', [
            CommunityPostController::class,
            'store',
        ]);
    });
 ```
 
 After hitting the route *POST /groups/1/posts/* once, the second time I hit it I get a ThrottleRequestsException. I expect to have 9 tries left here.

When using a different value such as *throttle:50:60* on a similar route, the limit seems to randomly drop by 2 for some requests although I am once again only hitting the route once.

**Comment by percymamedy** [comment]
Define the RateLimit in your `AppServiceProvider`

```php
/**
 * Bootstrap any application services.
 */
protected function boot(): void
{
    RateLimiter::for('api', function (Request $request) {
        return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
    });
}
```

Then attach it to the Route middleware like so:

```php
Route::middleware('throttle:api')->post('/{group}/posts', [
    CommunityPostController::class,
    'store',
]);
```

**Comment by timmylindh** [comment]
> Define the RateLimit in your `AppServiceProvider`
> 
> 
> 
> ```php
> 
> /**
> 
>  * Bootstrap any application services.
> 
>  */
> 
> protected function boot(): void
> 
> {
> 
>     RateLimiter::for('api', function (Request $request) {
> 
>         return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
> 
>     });
> 
> }
> 
> ```
> 
> 
> 
> Then attach it to the Route middleware like so:
> 
> 
> 
> ```php
> 
> Route::middleware('throttle:api')->post('/{group}/posts', [
> 
>     CommunityPostController::class,
> 
>     'store',
> 
> ]);
> 
> ```

Thanks for your suggestion. However, like I mentioned in my post I am aware of named parameters but this is about getting non-named parameters to work. Has Laravel dropped support for them?

**Comment by gomzyakov** [comment]
@timmylindh Hello!

I have encountered similar situations. Have you been able to figure out why this is happening?

**Comment by timmylindh** [comment]
> @timmylindh Hello!
> 
> 
> 
> I have encountered similar situations. Have you been able to figure out why this is happening?
> 
> 

Sadly not, I just switched to named parameters since this issue was discarded. Would love to see a real solution though.
