### ISSUE TITLE
`Bus::dispatch()` cannot be used to queue closures

### ISSUE THREAD

**Issue by j3j5** [laravel/framework#51150]
### Laravel Version

11.2.0

### PHP Version

8.3.6

### Description

I am not 100% sure this is a bug, but it's an inconsistency I did not expect so I thought it'd be good to check. According to the docs, you can [queue a closure](https://laravel.com/docs/11.x/queues#queueing-closures) and it'll get converted into a job. Following the example from the docs, it works as expected. Now, if I try to do the same thing using `Bus::dispatch()`, the closure doesn't implement `ShouldQueue` so the closure gets dispatched synchronously (you actually get whatever the Closure is returning.

I was under the impression that using `dispatch()` or `Bus::dispatch()` was similar (just two differente approaches, Facade vs helper) but looking at the code for both that's obviously not true (although their behaviour is similar enough). My question is, is this a bug? Or is it expected behaviour that I somehow missed? I see the docs don't mention `Bus::dispatch()` anywhere (and I remember the legacy from the times of Laravel 5) but just wanted to double check if the inconsistency was on purpose or you'd be willing to get a PR making the two calls consistent.

### Steps To Reproduce

```php
<?php

dispatch(fn() => 'hello'); // Puts the closure on a queue by creating an instance of `PendingClosureDispatch`

Illuminate\Facades\Bus::dispatch(fn() => 'hello'); // Runs the closure and returns return value.
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
