### ISSUE TITLE
Default connection is being changed unreliably in testing

### ISSUE THREAD

**Issue by olieady** [laravel/framework#51163]
### Laravel Version

11.4

### PHP Version

8.2

### Database Driver & Version

Mysql 8.1

### Description

When providing a custom connection to the FreshCommand it is changing the application's default connection. 

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Console/Migrations/FreshCommand.php#L65-L67

This was introduced in 11.4 by this PR - https://github.com/laravel/framework/pull/51021

setConnection doesn't reset the default connection back to its original, unlike usingConnection. 

### Steps To Reproduce

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $this->artisan('migrate:fresh', [
            '--database' => 'non_default_connection',
        ]);

        dd(config('database.default'));
    }
}
```
Laravel 11.3 output - `"mysql" // tests/Feature/ExampleTest.php:18`
Laravel 11.4 output - `"non_default_connection" // tests/Feature/ExampleTest.php:18`

**Comment by driesvints** [comment]
Thanks for reporting! I've sent in a PR for this: https://github.com/laravel/framework/pull/51167
