### ISSUE TITLE
The `Paginator` interface does not implement `through` method

### ISSUE THREAD

**Issue by Bloemendaal** [laravel/framework#51165]
### Laravel Version

10.48.8

### PHP Version

8.3.4

### Database Driver & Version

mysql  Ver 8.3.0 for macos14.2 on arm64 (Homebrew)

### Description

The paginate() method of the `Illuminate\Database\Eloquent\Builder` returns the interface `LengthAwarePaginator`, which implements the `Paginator` interface (also on master):
https://github.com/laravel/framework/blob/master/src/Illuminate/Contracts/Pagination/Paginator.php#L5

This interface does not implement the through() method, even though this is a part of `AbstractPaginator`. This causes my IDE to place red lines:
```php
$pokemon = Pokemon::query()
      ->paginate(30)
      ->through(static fn (Pokemon $pokemon): PokemonData => PokemonData::fromModel($pokemon));
```

![image](https://github.com/laravel/framework/assets/1348606/89141089-6070-4aa6-9e7d-0842820fc5de)
> Undefined method 'through'.

Can we add this method to the `Paginator` interface to prevent these errors?

### Steps To Reproduce

Paginate any model and call the through() method. It should work fine, but the IDE will give an error.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!
