### ISSUE TITLE
Maria DB before 10.5.2 rename nullable column fails

### ISSUE THREAD

**Issue by dav245** [laravel/framework#51171]
### Laravel Version

11

### PHP Version

8.3

### Database Driver & Version

Maria before 10.5.2 (10.3.39 in our case)

### Description

While trying to rename nullable numeric column, migration fails. It tries to gather data from existing schema as seen in Illuminate\Database\Schema\Grammars@343 (function compileLegacyRenameColumn). On line 357 it checks if it has default timestamp, which in our case had not. So $column['default'] was used as is. But schema returned default value as 'NULL'. Since it is string it tried to set default value as 'NULL' for numeric column thus crashing. 

```php   
    protected function compileLegacyRenameColumn(Blueprint $blueprint, Fluent $command, Connection $connection)
    {
/*343*/ $column = collect($connection->getSchemaBuilder()->getColumns($blueprint->getTable()))
            ->firstWhere('name', $command->from);

        $modifiers = $this->addModifiers($column['type'], $blueprint, new ColumnDefinition([
            'change' => true,
            'type' => match ($column['type_name']) {
                'bigint' => 'bigInteger',
                'int' => 'integer',
                'mediumint' => 'mediumInteger',
                'smallint' => 'smallInteger',
                'tinyint' => 'tinyInteger',
                default => $column['type_name'],
            },
/*357*/     'nullable' => $column['nullable'],
            'default' => $column['default'] && str_starts_with(strtolower($column['default']), 'current_timestamp') 
                ? new Expression($column['default'])
                : $column['default'],
            'autoIncrement' => $column['auto_increment'],
            'collation' => $column['collation'],
            'comment' => $column['comment'],
            'virtualAs' => ! is_null($column['generation']) && $column['generation']['type'] === 'virtual'
                ? $column['generation']['expression'] : null,
            'storedAs' => ! is_null($column['generation']) && $column['generation']['type'] === 'stored'
                ? $column['generation']['expression'] : null,
        ]));

        return sprintf('alter table %s change %s %s %s',
            $this->wrapTable($blueprint),
            $this->wrap($command->from),
            $this->wrap($command->to),
            $modifiers
        );
    }
```

Our solution was to patch 
`'default' => $column['default'] && str_starts_with(strtolower($column['default']), 'current_timestamp')`
to
`'default' => (($column['default'] && str_starts_with(strtolower($column['default']), 'current_timestamp')) || ($column['default'] === 'NULL'))`

Afterwards migration succeeded.

I honestly don't know if the problem lies in schema or in unpatched check. So this is as much as i can do. 

### Steps To Reproduce

Rename numeric nullable column in maria before version 10.5.2

**Comment by driesvints** [comment]
Are you using the dedicated mariadb connection in Laravel v11? https://github.com/laravel/laravel/blob/11.x/config/database.php#L62

**Comment by driesvints** [comment]
@hafezdivandari do you reckon this could be an easy fix?

**Comment by hafezdivandari** [comment]
@driesvints sure, I'll send a PR.

**Comment by dav245** [comment]
Hats off. That was quick. Thank you all.
