### ISSUE TITLE
Container unable to resolve class in a Job class

### ISSUE THREAD

**Issue by sumityadav** [laravel/framework#51182]
### Laravel Version

11.4.0

### PHP Version

8.3.6

### Description

In a new Laravel application, a singleton class registered within the `AppServiceProvider` is not resolved inside the constructor of a Job class. While the singleton resolves successfully in web.php, it fails within the job class.

### Steps To Reproduce

Test class.
```php
public function __construct($config = array())
{
    $this->config = $config;
}
```

Registering as singleton in app/Providers/AppServiceProvider.php
```php
$this->app->singleton(Test::class, function () {
    return new Test(['foo' => 'bar']);
});
```

Testing the / route and it works in web.php.
```php
Route::get('/', function (Test $test) {
    dump($test);
});
```

Now instead of dump, I dispatch the job and it gives the following exception: 

Too few arguments to function App\Jobs\TestJob::__construct(), 0 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php on line 19 and exactly 1 expected

```php
Route::get('/', function () {
    \App\Jobs\TestJob::dispatch();
});
```

app/Jobs/TestJob.php

```php
public function __construct(Test $test)
{
    $this->test = $test;
}
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
