### ISSUE TITLE
/Support/Facades/Schedule.php failing pipeline

### ISSUE THREAD

**Issue by hubseven** [laravel/framework#51183]
### Laravel Version

11.x

### PHP Version

8.2.17

### Description

The following jobs have failed

https://github.com/laravel/framework/actions/runs/7024152610/job/19112249940
https://github.com/laravel/framework/actions/runs/7024152603/job/19112249769
https://github.com/laravel/framework/actions/runs/7024152603/job/19112250156
https://github.com/laravel/framework/actions/runs/7024152603/job/19112250793

The Schedule Facade is not installing as a result

### Steps To Reproduce

checkout laravel/framework
check file exists src/Illuminate/Support/Facades/Schedule.php

**Comment by driesvints** [comment]
Not sure what you mean but all tests currently pass.
