### ISSUE TITLE
fruitcake/php-cors v13 needed but not match

### ISSUE THREAD

**Issue by bzqadmin** [laravel/framework#51201]
### Laravel Version

11

### PHP Version

8.2.13

### Description

when I create a new project of laravel11(composer or laravel new),I get these error messages :` Problem 1
    - laravel/framework[v11.0.0, ..., v11.2.0] require fruitcake/php-cors ^1.3 -> found fruitcake/php-cors[dev-feat-setOptions, dev-master, dev-main, dev-test-8.2, v0.1.0, v0.1.1, v0.1.2, v1.0-alpha1, ..., 1.2.x-dev (alias of dev-master)] but it does not match the constraint.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.2.0].
`

### Steps To Reproduce

` Problem 1
    - laravel/framework[v11.0.0, ..., v11.2.0] require fruitcake/php-cors ^1.3 -> found fruitcake/php-cors[dev-feat-setOptions, dev-master, dev-main, dev-test-8.2, v0.1.0, v0.1.1, v0.1.2, v1.0-alpha1, ..., 1.2.x-dev (alias of dev-master)] but it does not match the constraint.
    - Root composer.json requires laravel/framework ^11.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.2.0].
`

**Comment by driesvints** [comment]
No steps to reproduce.

**Comment by laduniestu** [comment]
![Screenshot 2024-05-14 at 02 25 50](https://github.com/laravel/framework/assets/44757637/68dacc59-c11a-4c20-b123-143059e5d29d)

i just had this error when installing new laravel project

**Comment by onnoink** [comment]
It seems that you are using an unofficial packagelist source that hasn't synchronized the latest 1.3.0 tags yet. You can try replacing your packagelist source with the default official source (url: https://repo.packagist.org/).

**Comment by sugeng-sulistiyawan** [comment]
> composer config -g --unset repos.packagist

thanks, work for me
