### ISSUE TITLE
Php artisan test "Option --configuration cannot be used more than once"

### ISSUE THREAD

**Issue by oceanapplications** [laravel/framework#51207]
### Laravel Version

11.0

### PHP Version

8.3.1

### Description

The latest version of phpunit generates a warning if you have multiple of the same command line flag. 

### Steps To Reproduce

Adding a --configuration flag to php artisan test will cause the warning as php artisan test already has a configuration flag set.

**Comment by driesvints** [comment]
Sorry, mixed this one up with something else.

**Comment by nunomaduro** [comment]
Seems an issue at Collision level; do you mind of PR something to Collision that allows to override the --configuration option rather than append it?
