### ISSUE TITLE
Run laravel in subfolder

### ISSUE THREAD

**Issue by Lioxen** [laravel/framework#51210]
### Laravel Version

10.48.9

### PHP Version

8.3.6

### Database Driver & Version

MySQL

### Description

I linked the public folder of the laravel app as subfolder in the public webservers folder so the app should  be reached on https://www.example.com/subfolder. I also changed the APP_URL to this address. This works so far, but I get a lots of errors in the browsers console. The application tries to load everything from the root folder and also changes the browser url. E.g. if I access the login page, the app tries to load 
https://www.example.com/build/assets/Login-gnHTBOkw.js
https://www.example.com/build/assets/GuestLayout-BiZdak9V.js ...
and changes the URL to: https://www.example.com/subfolder/subfolder/login
The funny thing is, I see the login form and can log in, but the URL of the dashboard changes also to  https://www.example.com/subfolder/subfolder/dashboard, so if I reload the page I will get a 404 error.
So whats the point to set the APP_URL, if it would obvious ignored at all? Because I can set what I want there, it has no effect. 
How can I run my app in a subfolder without it changes the url and also loads all the parts correctly?

### Steps To Reproduce

Just link your laravel public folder as subdirectory to your webservers public folder. e.g. ln -s /folder/where/laravel/resides/public /var/www/html/myapp
After that you can reach your app in your browser with following address: http(s)://example.com/myapp

**Comment by rodrigopedra** [comment]
Serving from a subdirectory is not supported. 

From the docs:

> Laravel should always be served out of the root of the "web directory" configured for your web server. You should not attempt to serve a Laravel application out of a subdirectory of the "web directory". Attempting to do so could expose sensitive files present within your application.

Reference: https://laravel.com/docs/11.x#directory-configuration

The text is the same on the 10.x docs: https://laravel.com/docs/10.x#directory-configuration

Also check for numerous past issues around the matter.

**Comment by crynobone** [comment]
Thanks @rodrigopedra

**Comment by Lioxen** [comment]
Thanks @rodrigopedra for your information, but in my case there is no security issue, because only the public sub folder is reachable over the web. All other things are still outside of the public web folder. (But may I miss some thing, than it would be nice if someone can tell me, what the securety issue exactly is)

My question is still, why is there an APP_URL config variable? I can define what I want, it is always ignored. 
Why does the app generates an extra subfolder in the address bar?
Why will this subfolder not used to generate the right url for the assets. Additionally I defined a prefix in the routes/web.php, but this makes it even worse. Now the url is really https://www.example.com/subfolder/subfolder/dashboard to get the dashboard and in the addressbar it is https://www.example.com/subfolder/subfolder/subfolder/dashboard but the app still tries to load all the assets on the root folder. Now the app even knows where it reaches the specific route, why it still tries to load the assets with the wrong url?

May you should think about it, to allow laravel to run in a subfolder... in my case, there is no other way... also see the discusion there:
https://github.com/laravel/framework/pull/3918

**Comment by rodrigopedra** [comment]
`APP_URL` is used mainly to generate URLs when running CLI processes, like queue workers.

On HTTP requests, Laravel defers to the request's base URL.

Although I have a "contributor" label on my posts, that is for sending previous PRs. I am not a member of Laravel as an organization, nor a maintainer. So it is not up to me to decide over this.

Can't you configure a subdomain?

In the discussion you linked, Taylor says he'd accept a comprehensive PR on the matter. I guess no one could make a PR which convinced him to allow this use-case.

https://github.com/laravel/framework/pull/3918#issuecomment-154494401

**Comment by rodrigopedra** [comment]
Regarding your assets' base URL, you can define a custom base URL for assets using the `ASSET_URL` environment variable.

Reference: https://laravel.com/docs/10.x/vite#custom-base-urls

Giving the docs a good read might answer further questions on the matter.

**Comment by rodrigopedra** [comment]
@Lioxen 

I can't guarantee everything will work as expected, as this is an unsupported use-case.

But you can try adding this to your project's `AppServiceProvider@boot` method:

```php
$this->app['url']->forceRootUrl($this->app['config']->get('app.url'));
```

This will tell the `UrlGenerator` to use the value in your `.env` file's `APP_URL`, as the base part of the URL.

I didn't test, and again, this is an unsupported use-case. So things may break, and third-party packages that deal with routing might handle the base URL differently.
