### ISSUE TITLE
N^2 models created when using EloquentFactory::createMany in conjunction with a count

### ISSUE THREAD

**Issue by calebdw** [laravel/framework#51224]
### Laravel Version

10.x

### PHP Version

8.2.x

### Description

Hello!

I noticed a subtle bug in the EloquentFactory method when it's using in conjunction with a factory count. The `createMany` should return an EloquentCollection of models (i.e., a flat structure):
https://github.com/laravel/framework/blob/a43537522094a109c22d8852b6e1d510a55c9313/src/Illuminate/Database/Eloquent/Factories/Factory.php#L235-L241

However, when the factory has a count provided, a collection of collections is returned, and **n^2 models are created**:
```php
// expected a collection of 3 models
// returns a collection of 3 collections with 3 models each---9 records total
User::factory()->count(3)->createMany();
```

I have a PR ready to go to fix this, but I just need some clarification on the expected behaviour when there's both a count and an argument passed to `createMany`:
```php
User::factory()->count(2)->createMany(3); // ?
```
Should:
1. the `createMany` arg override the `count` (3 models returned)?
1. the `count` override the `createMany` arg (2 models returned)?
1. the counts be added together (5 models returned)?
1. the counts be multiplied together (6 models returned)?

Note that an iterable (states) could also be passed to `createMany` which would normally create that many records.
It may be more trouble than it's worth to try to bring the count into the mix, so it may be easiest just to have the `createMany` override the `count` (Option 1).

Example:
```php
User::factory()->count(2)->createMany([['foo' => 1], ['foo' => 2], ['foo' => 3]]);
```
Options:
1. Three records are created with the states passed to `createMany`
2. Two records are created, but do you just ignore the last state passed?
3. Five records are created, but which states are repeated?
4. Six records are created with the states being repeated twice

Thanks!

### Steps To Reproduce

See above

**Comment by driesvints** [comment]
Thank you. It seems you already sent in a PR so let's see how it goes.
