### ISSUE TITLE
Route::pattern not applied to custom model key

### ISSUE THREAD

**Issue by jonesy655321** [laravel/framework#51262]
### Laravel Version

11.6.0

### PHP Version

8.3.6

### Database Driver & Version

PostgreSQL 15.6

### Description

Route patterns are not applied to custom model keys.

In the example below:
- URL with valid UUID works as expected.
- URL with valid format UUID but not in database returns 404 as expected.
- URL with invalid format UUID returns a SQL exception - expected a 404.

I would rather not force resolveRouteBinding on the model.

### Steps To Reproduce

Create an orders table and model with a 'uuid' field.

```
class AppServiceProvider extends ServiceProvider
{

    public function boot(): void
    {
        // UUIDv4 regex
        Route::pattern( 'uuid', '^[0-9A-Fa-f]{8}-?[0-9A-Fa-f]{4}-?4[0-9A-Fa-f]{3}-?[89AaBb][0-9A-Fa-f]{3}-?[0-9A-Fa-f]{12}$' );
    }

}
```

Create a route with a custom model key:

`Route::get( '/{order:uuid}', ... )`

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
