### ISSUE TITLE
`php artisan test` returns exit code 1 if phpunit has warnings, doesn't display them

### ISSUE THREAD

**Issue by imaginedbyme** [laravel/framework#51272]
### Laravel Version

10.31.0

### PHP Version

8.2

### Description

If you use phpunit tests with Laravel, and run them using `php artisan test`, the tests can all pass and still return an exit code of 1 if phpunit has warnings artisan doesn't display. This makes GitHub actions testing Laravel projects fail with no warnings/errors if the run command is `php artisan test` and the current documentation doesn't say anything about it suppressing phpunit warnings.

### Steps To Reproduce

If you create a test file but comment any tests out, phpunit returns it as a warning but artisan doesn't, leading to an exit code of 1 with no visible reason why, only by running `./vendor/bin/phpunit` can you see the warnings.

**Comment by staudenmeir** [comment]
Hi @imaginedbyme,
The test command is provided by the `nunomaduro/collision` package which already has a ticket and a PR for this issue:
https://github.com/nunomaduro/collision/issues/293
https://github.com/nunomaduro/collision/pull/294

**Comment by imaginedbyme** [comment]
Ah I didn't see this was from a different package, my apologies I'll close this, thanks for the feedback @staudenmeir !

**Comment by khalidmaquilang** [comment]
![Screenshot 2024-11-27 at 9 26 58 PM](https://github.com/user-attachments/assets/46d9bd14-a5e1-4d0f-9edf-c02ac243636c)

currently encountering this issue

**Comment by AmrSamra** [comment]
![Screenshot 2024-12-05 at 6 29 22 PM](https://github.com/user-attachments/assets/373e0f97-07d6-45bf-b6d3-42d987437abc)
same issue

**Comment by AVegMor** [comment]
Same here 

![image](https://github.com/user-attachments/assets/bcf98e3b-4f09-45d7-ab8a-dbe38c62adc9)

**Comment by fazio91** [comment]
Same here

<img width="774" alt="Screenshot 2024-12-20 alle 14 54 08" src="https://github.com/user-attachments/assets/4a0c635f-4943-4972-9bf2-849f05676c94" />

**Comment by khalidmaquilang** [comment]
I managed to fix this.. there was a class that doesn't have any test case.. i deleted it and it worked so double check your test files

**Comment by fazio91** [comment]
> I managed to fix this.. there was a class that doesn't have any test case.. i deleted it and it worked so double check your test files

Thank you @khalidmaquilang I also had a class without a test inside; I removed it, and everything worked! Thanks!

**Comment by basheer-taplane** [comment]
It's generally easier to identify these issues by running `./vendor/bin/phpunit --configuration phpunit.xml`, which will display errors or warnings that Laravel often suppresses.

**Comment by JohnnyWalkerDigital** [comment]
I just stumbled across this. Was expecting Laravel to flag issues more visually. However good to understand what's going on
