### ISSUE TITLE
Some docummented options are not working for `php artisan test` 

### ISSUE THREAD

**Issue by tontonsb** [laravel/framework#51304]
### Laravel Version

11.6.0

### PHP Version

8.2.6

### Description

Options `-v`, `-vv`, `-vvv`, `--verbose`, `-n`, `--no-intercation` are documented (listed in `php artisan help test`) but not working for the `test` command. I verified that the other commands do work.

Related to: #49290, #45699, #45340, #44373 and maybe #41951, #38140.

### Steps To Reproduce

To reproduce call `php artisan test [option]` with any of the above options, e.g.

```sh
$ php artisan test -vv
PHPUnit 11.1.3 by Sebastian Bergmann and contributors.

Unknown option "-v"
```

**Comment by crynobone** [comment]
The test command is provided by the `nunomaduro/collision` package and any issue should be reported at https://github.com/nunomaduro/collision/issues
