### ISSUE TITLE
YYYY-MM-DDTHH:MM:SS.uuuuuuZ not default, miliseconds not stored in DB

### ISSUE THREAD

**Issue by misog** [laravel/framework#51317]
### Laravel Version

10.10 and 11

### PHP Version

8.2

### Database Driver & Version

Mysql

### Description

Hi, here it states that default datetime format for casting is `YYYY-MM-DDTHH:MM:SS.uuuuuuZ`.
https://laravel.com/docs/10.x/eloquent-mutators#date-casting-and-timezones

However here is different default format specified:
https://github.com/laravel/framework/blob/67fbbc49eec22bd80178e2de991d67aea29c6d06/src/Illuminate/Database/Grammar.php#L255

Here is the logic of getting the format:
https://github.com/laravel/framework/blob/67fbbc49eec22bd80178e2de991d67aea29c6d06/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1498

When testing, `$this->getConnection()->getQueryGrammar()->getDateFormat()` from Model returns `"Y-m-d H:i:s"`. This means that milliseconds are not stored by default. I have to specify in Model `protected $dateFormat = 'Y-m-d H:i:s.u';` to workaround it.

### Steps To Reproduce

1. Set timestamp('field', 6) or timestamps(6) in migrations
2. Add field to $casts array
3. Save model in database
4. Milliseconds are not stored

**Comment by NiroDeveloper** [comment]
This can also lead to a incorrect timezone ... very high bug potential.

**Comment by driesvints** [comment]
That's the docs for serialisation when retrieving timestamps, not storing.

**Comment by driesvints** [comment]
The date format for storing isn't the same as the cast for retrieving. They're different things. The date format by default uses the format set on your model like you indicated above. It doesn't saves timezones, that's not how things work. You should always convert to UTC and store datetimes as UTC.

**Comment by misog** [comment]
@driesvints I am storing UTC. The problem is that when I have default configuration and I do this:
```
$user->updated_at = now(); // timestamp(6)
$user->save();
```
then updated_at in DB has .000000 value after seconds.

How to make it store milliseconds?

**Comment by misog** [comment]
@driesvints I see the difference now. The docs says:
1. About casting formats 
2. About storing formats
3. About default casting format

Maybe 1 and 3 could be together.
