### ISSUE TITLE
MariaDB migration - cannot create uuid column

### ISSUE THREAD

**Issue by olivierbaudouin** [laravel/framework#51315]
### Laravel Version

11.6.0

### PHP Version

8.3.6

### Database Driver & Version

MariaDB 10.6

### Description

Get an SQL exception while creating an uuid column in a migration

### Steps To Reproduce

$table->uuid('file_uuid')->nullable();

 SQLSTATE[HY000]: General error: 4161 Unknown data type: 'uuid'

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by hafezdivandari** [comment]
The UUID data type was added in [MariaDB 10.7](https://mariadb.com/kb/en/uuid-data-type/#:~:text=The%20UUID%20data%20type%20was%20added%20in%20MariaDB%2010.7.). You may use `$table->char('uuid', 36)` or `$table->binary('uuid', 16, fixed: true)` instead depend on your use case.

**Comment by misog** [comment]
Or you can switch DB_CONNECTION to **mysql** (not **mariadb**). In Laravel 11 there is new MariaDB driver (DB_CONNECTION), see https://laravel.com/docs/11.x/upgrade#dedicated-mariadb-driver

The problem is that it assumes that MariaDB supports UUID (only from version 10.7).
