### ISSUE TITLE
@php and @endphp directives should indeed compile down to standard PHP <?php ?> but it is not happening with me 

### ISSUE THREAD

**Issue by hasibul-terabit** [laravel/framework#51313]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

@php and @endphp directives should indeed compile down to standard PHP <?php ?> but it is not happening with me .

my code is 

`@php 
$language = 'abcd';
@endphp
`

and after running it in browser it still showing the same. and  $language variable says undefined. 

When i change the cache file  into 
`<?php
$language = 'abcd';
?>
`
it works. 

So assuming that, while compiling the tags are not converting. 

how to solve this issue. 

### Steps To Reproduce

It was working fine since yesterday. I did not change anything. just cleared the view cache and start browsing and go variables undefined . So I started debugging and found the situation

**Comment by driesvints** [comment]
I'm sorry but we no longer recommend using inline PHP statements, just block like:

```blade
@php
$language = 'abcd';
@endphp
```

There's been too many issues with the Blade compiler in the past which lead us to remove this usage from the docs. Please use native opening and closing tags if you need this.
