### ISSUE TITLE
Sanctum api doesn't protect routes

### ISSUE THREAD

**Issue by inkomomutane** [laravel/framework#51323]
### Laravel Version

11.6.0

### PHP Version

8.3

### Database Driver & Version

pgsql on ubuntu

### Description

Sanctum doesn't protect routes if middleware is called after group function.   but works if called before. 

### Steps To Reproduce

```php 

# Doesn't work 
Route::prefix('v1')->group(static function () {
    Route::get('user', static function (Request $request) {
        return $request->user();
    });
})->middleware('auth:sanctum');


# Works
Route::middleware('auth:sanctum')->prefix('v1')->group(static function () {
    Route::get('user', static function (Request $request) {
        return $request->user();
    });
});

```

**Comment by driesvints** [comment]
For route groups. You need to apply the middleware as documented like in the example of you where it works: https://laravel.com/docs/11.x/routing#route-group-middleware

<img width="805" alt="Screenshot 2024-05-07 at 16 36 02" src="https://github.com/laravel/framework/assets/594614/c017c844-12bb-4ee2-aeab-042c015cbfc5">

**Comment by marlboro** [comment]
I don't see how this is an answer. If the **middleware** method doesn't work on a **group** then why is it declared/allowed for a **group**? This is a security hole after all, so it seems like a no-brainer to get rid of the method or make it actually work.

It also seems weird that you are instructed to apply middleware to a single route with this syntax...

```php
# This is allowed and blessed
Route::get(...)->middleware('auth:sanctum');
```

But, the same syntax is allowed, but will not work on a group of routes. 😲

```php
# This is allowed, but will not work
Route::group(...)->middleware('auth:sanctum');
```
