### ISSUE TITLE
Unserialize DATETIME from Database not working with Carbon 3.0

### ISSUE THREAD

**Issue by NiroDeveloper** [laravel/framework#51321]
### Laravel Version

11.6.0

### PHP Version

8.3.6

### Database Driver & Version

MariaDB 11.1.4

### Description

Laravel 11 with carbon 3.0 will unserialize a DATETIME from the database with an incorrect timezone.
With laravel 11 and carbon 2.0 it is working as expected.

You can use this unit test to check it:
```
/**
 * @test
 */
public function serializes_datetime_correctly()
{
    $myDatetime = Carbon::createFromTimestamp(1657996631);

    $model = MyModel::create(["my_datetime" => $myDatetime]);

    self::assertEquals($myDatetime, $model->my_datetime);
}
```

It will fail with this reason:
```
Failed asserting that two DateTime objects are equal.
Expected :2022-07-16T18:37:11.000000+0000
Actual   :2022-07-16T18:37:11.000000+0200
```

### Steps To Reproduce

1. Install Laravel 11 with Carbon 3.0
2. Create Model with DATETIME database column (and laravel cast to datetime)
3. The given unit test will fail

**Comment by driesvints** [comment]
This is a change in Carbon v3. Please see the docs here: https://carbon.nesbot.com/docs/#api-carbon-3

**Comment by driesvints** [comment]
> We also recommend to always call createFromTimestamp with 2 parameters (i.e. explicitly pass a timezone)

**Comment by NiroDeveloper** [comment]
Yes, this means that you can only give Carbon instances to laravel with the server-timezone, which is very confusing.
Instead laravel should regonize the different timezone and convert it into the configured server timezone.

@driesvints Assume that i have a REST API and the client sends his current timestamp as UTC. 
Now i want to save this timestamp into the database ... it is fully correct that the Carbon instance is in the UTC Timezone, but laravel ignores this.

**Comment by driesvints** [comment]
I don't know what you want us to do? We don't control this code, this is all Carbon.

**Comment by NiroDeveloper** [comment]
We could fix this by adding a if-statement to https://github.com/laravel/framework/blob/5710fdb8bf36df501405c705f7d2ea4720d2b9d3/src/Illuminate/Database/Query/Builder.php#L4065
 ```
public function castBinding($value)
{
    if ($value instanceof Carbon) {
        // The php date() function converts the timestamp into the server timezone.
        return date('Y-m-d H:i:s', $value->unix());
    }

    if ($value instanceof UnitEnum) {
        return $value instanceof BackedEnum ? $value->value : $value->name;
    }

    return $value;
}
```
Alternative we could read the app.timezone config or define a timezone in the database.connections config.
This will work for insert() only, for create() we have to also insert a "if" into HasAttribute->setAttribute()

**Comment by driesvints** [comment]
I don't think we should do anything like that sorry. You should set the proper timezone as instructed by the Carbon docs.

**Comment by kylekatarnls** [comment]
> Yes, this means that you can only give Carbon instances to laravel with the server-timezone, which is very confusing.

No it does not mean that, on the contrary the Carbon v2 behavior was actually using the server-timezone and you can get the Carbon v2 behavior by using:

```php
$myDatetime = Carbon::createFromTimestamp(1657996631, date_default_timezone_get());
```

So I'm actually puzzled how you could get a +0000 timezone previous when using Carbon 2.
