### ISSUE TITLE
Schedule gets registered with every artisan call

### ISSUE THREAD

**Issue by Plytas** [laravel/framework#51354]
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Description

When running any `artisan` command (just `php artisan` does the same), the code inside `console.php` route file and/or `->withSchedule()` bootstrap method gets executed. Usually this wouldn't be a big deal, because the code should only register cron events. However, sometimes dynamic scheduling might involve database queries which can inflict unwanted performance penalty or in worst case scenario fail in CI setup.

We noticed this in our CI while upgrading from Laravel 10 to Laravel 11 (with slimmed down app structure). Our scheduler needs to be dynamic and it makes a DB query for that reason. When CI is setting up the application it runs `composer install` which then runs `php artisan package:discover --ansi` as a composer `post-autoload-dump` script. This is standard in every Laravel project. Since `package:discover` is an artisan command it boots up the scheduler as well. At this stage in CI database is not yet available thus we get a `QueryException: SQLSTATE[HY000] [2002] Connection refused`.

I have checked and this wasn't the case with Laravel 10. I'm not sure if this is now intended or not, but I would expect scheduler code to only execute when calling `php artisan schedule:run` and `php artisan schedule:work`.

### Steps To Reproduce

* Set up new Laravel 11 project.
* Add `dd();` inside `console.php` route file or inside `->withSchedule()` app bootstrap method.
* Run `php artisan` and observe the command to fail.

**Comment by Plytas** [comment]
Thanks @crynobone for taking your time to look at this. Unfortunately your attempt unveiled another issue. I tried investigating this myself and here are my findings:

1. Artisan command is invoked.
2. Console [Kernel is bootstrapped](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/Kernel.php#L194).
3. [Commands are discovered](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/Kernel.php#L479)
4. `console.php` [route file is required](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/Kernel.php#L499).
   * If the file contains scheduled commands `\Illuminate\Console\Scheduling\Schedule` is resolved too.
5. [Console application is bootstrapped](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Console/Application.php#L77), [executing bootstrappers](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Console/Application.php#L130) registered with `Artisan::starting()`

---

Currently, `->withSchedule()` looks like this:
```php
Artisan::starting(fn () => $callback($this->app->make(Schedule::class)));
```

Meaning that the code inside `->withSchedule()` gets executed with every artisan command.
@crynobone suggested to change this to
```php
Artisan::starting(function () use ($callback) {
    $this->app->afterResolving(Schedule::class, fn ($schedule) => $callback($schedule));
});
```
Which unfortunately doesn't work if `console.php` route file contains scheduled commands, because `\Illuminate\Console\Scheduling\Schedule` gets [resolved immediately the second time](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Container/Container.php#L774), skipping both `$resolvingCallbacks` and `$afterResolvingCallbacks`.

---

At this point, for this to work we would need to either detect scheduled commands inside `console.php` and defer registering them after console application is bootsrapped (step 5), or execute `$afterResolvingCallbacks` even if items, that have already been resolved before, are returned from container directly.
Perhaps I don't see the full picture yet and am missing some other hook that can be used?

Of course, another option is to treat this "bug" as "working as expected" and perhaps document it. After all, all code inside `console.php` is already being executed with every artisan call, so maybe code inside `->withSchedule()` should be too.

**Comment by mohammadMghi** [comment]
Why you did not run 'schedule' inside a Artisan::command() function? like following:

`` Artisan::command('schedule:run', function () { //write schedulers here. });``

So when run `php artisan schedule:run` only code there get executed.

**Comment by Plytas** [comment]
Well... [`schedule:run`](https://laravel.com/docs/master/scheduling#running-the-scheduler) is already a command. Overriding that would mean re-implementing the whole cron logic myself.

Unless I'm missing something?

**Comment by flexchar** [comment]
How about having a dedicated `schedule.php` file? During migration to L11 I found this to be very confusing and I am experiencing my commands not being run besides them appearing in the CLI `list`. It may be a completely another issue but it feels worth a second thought.

**Comment by Plytas** [comment]
@flexchar You are able to do that using `->withSchedule()` method on app bootstrap and then importing/requiring `schedule.php` file.

**Comment by Plytas** [comment]
I would urge to consider @crynobone PR #51364 as a valid solution for this issue. It might be a breaking change for people using scheduled commands in both places, though I'm not sure how common that is. If you are using `->withSchedule()` then there's no reason to use scheduled commands in `console.php` file.

**Comment by Plytas** [comment]
@driesvints PR https://github.com/laravel/framework/pull/51364 is still open so maybe we can keep the issue open until then? 

There were 2 PRs for this so that's why you see a closed one here.

**Comment by Plytas** [comment]
Taylor closed the PR:
> I dunno, I'm not comfortable merging this without much more community feedback and input.

For now I suggest keeping your scheduler as light as possible. If anyone is experiencing issues, please do try out the changes in https://github.com/laravel/framework/pull/51364 and leave your feedback.

**Comment by chris-betterrx** [comment]
We just ran into this issue when trying to upgrade to Laravel 11.  Is there a work around for applications that use database queries for dynamic scheduling?

**Comment by ghost** [comment]
@chris-betterrx not sure if you still need a solution, but it was posted here https://github.com/laravel/framework/issues/58079#issuecomment-3652754700 by @crynobone , there is also my "old style" solution which i use on production at the moment.

**Comment by chris-betterrx** [comment]
> [@chris-betterrx](https://github.com/chris-betterrx) not sure if you still need a solution, but it was posted here [#58079 (comment)](https://github.com/laravel/framework/issues/58079#issuecomment-3652754700) by [@crynobone](https://github.com/crynobone) , there is also my "old style" solution which i use on production at the moment.

Thanks we just ended up checking for a successful DB connection in the schedule method and if there wasn't one return early.  Not ideal but that was the least intrusive way I could think of until they get this fixed.
