### ISSUE TITLE
Redis::pipeline type error

### ISSUE THREAD

**Issue by frankykubo** [laravel/framework#51353]
### Laravel Version

11.4.0

### PHP Version

8.3

### Description

I want to use redis pipeline to set few items within redis db with expiration time. If I provide types as in [Laravel docs](https://laravel.com/docs/11.x/redis#pipelining-commands), I get error:

```
TypeError: Argument #1 ($pipe) must be of type Illuminate\Support\Facades\Redis, Redis given
```

If I remove the typing, code snipped (provided below) works okay.

### Steps To Reproduce

1. Import Redis facade as `use Illuminate\Support\Facades\Redis;`

2. Use pipeline example code from docs with provided typings:
```
Redis::connection('stream_tokens')
            ->pipeline(function ($pipe) use ($generatedTokens, $segmentLifetime) {
                foreach ($generatedTokens as $tokenKey) {
                    $pipe->setex($tokenKey, (int) $segmentLifetime, 1);
                }
            });
```

3. This piece of code ends up with TypeError

**Comment by crynobone** [comment]
The doc shows there are two import and is likely the root cause of your issue.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
