### ISSUE TITLE
[Testing] Multiple connections in connectionsToTransact result in Model Observers with ShouldHandleEventsAfterCommit not being triggered

### ISSUE THREAD

**Issue by CodeWrap** [laravel/framework#51362]
### Laravel Version

10.44 and 11.7.0

### PHP Version

8.2

### Database Driver & Version

mysql 8

### Description

Since Laravel 10.44 my tests with a **Model Observer** and the interface **ShouldHandleEventsAfterCommit** fails. 
I have set up two connections within my Testcase and I am using the **LazilyRefreshDatabase** trait.
The second connection was also set up in the phpunit.xml.

All tests before 10.44 are green.

### Steps To Reproduce

Repo: [https://github.com/CodeWrap/ShouldHandleEventsAfterCommit](url)

Set up two mysql databases.

Testcase:
```
abstract class TestCase extends BaseTestCase
{
    use LazilyRefreshDatabase;

    protected $connectionsToTransact = ['mysql', 'mysql2'];
}

```

Test:

```
<?php

use App\Models\User;

test('example', function () {
    User::create([
        'name' => 'John Doe',
        'email' => fake()->unique()->safeEmail,
        'password' => bcrypt('password'),
    ]);
});
```

User:
```
#[ObservedBy(UserObserver::class)]
class User extends Authenticatable
{
    use HasFactory, Notifiable;
```

Observer:
```
class UserObserver implements ShouldHandleEventsAfterCommit
{
    /**
     * Handle the User "created" event.
     */
    public function created(User $user): void
    {
        dd('User created');
    }
}
```

The **dd** never gets called

Thanks for any help in advance

**Comment by crynobone** [comment]
Seem to work fine with the following:


```php
<?php

use App\Models\User;

test('example', function () {
    DB::transaction(function () {
        User::create([
            'name' => 'John Doe',
            'email' => fake()->unique()->safeEmail,
            'password' => bcrypt('password'),
        ]);
    });
});
```

`ShouldHandleEventsAfterCommit` that requires a transaction and the transaction added explicitly by `RefreshDatabase` doesn't count.
