### ISSUE TITLE
Artisan make:model only creates form requests when selecting resource controller as well

### ISSUE THREAD

**Issue by marventhieme** [laravel/framework#51366]
### Laravel Version

11.7.0

### PHP Version

8.2.18

### Database Driver & Version

MySQL 10.11.7

### Description

When running `php artisan make:model` and declare that I would like to have "Form Requests" generated, it does so ONLY when I also check "Resource Controller"

<img width="695" alt="image" src="https://github.com/laravel/framework/assets/53627227/fd82fb6c-12ff-42b8-9675-4edeb9efc75c">

Use case:
As I already had the controller created I would have liked to only create the model and form requests.

### Steps To Reproduce

1. php artisan make:model
2. check "Form Requests" without checking "Resource Controller"
3. -> No form requests are created

**Comment by driesvints** [comment]
This is on purpose as these are only tied in with resource controllers. Just selecting form requests won't do anything because you didn't need a resource controller in the first place. Might indeed be a little weird gotcha.

**Comment by marventhieme** [comment]
@driesvints Thanks for the explanation 😊 

The options would be more clear like:
- ...
- Resource Controller
- Resource Controller (with From Requests)
