### ISSUE TITLE
Unable access configuration in application bootstrap method withMiddleware

### ISSUE THREAD

**Issue by illambo** [laravel/framework#51367]
### Laravel Version

11.7.0

### PHP Version

8.2.1

### Description

It is not possible to access the configuration in application bootstrap ([Streamlined Application Structure](https://laravel.com/docs/11.x/releases#structure)) in the method `withMiddleware`, it throw `Fatal error: Uncaught ReflectionException: Class "config" does not exist ..`.

I have also verified that this problem is not encountered in the method `withSchedule`.

Access to the configuration is convenient for enhancing parametric situations such as [Trusted Proxies](https://laravel.com/docs/11.x/requests#configuring-trusted-proxies) or other. 

### Steps To Reproduce

```php
<?php

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        config('app.name'); // this throw Fatal error: Uncaught ReflectionException: Class "config" does not exist ..  
    })
    ->withSchedule(function (Schedule $schedule) {
        //config('app.name'); // it works here
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
```

**Comment by driesvints** [comment]
I think it's too early in the bootstrap process for this to be available. We currently do not document the usage of this sorry.

**Comment by driesvints** [comment]
Hey @illambo. It might be best to use a dedicated middleware in that case.
