### ISSUE TITLE
Inconsistent Job Execution Sequence in Bus::chain

### ISSUE THREAD

**Issue by mcolominas** [laravel/framework#51395]
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

MySQL 8.0.30

### Description

I am executing a long-term job, but for some reason, every 88s, the attempts increase, the job continues to execute and another job is executed. 

After running `PrepareCsvExport` 3 times, it throws the exception `App\Jobs\PrepareCsvExport has been attempted too many times.` and it starts to go crazy running `ExportCompletion` non-stop

What is expected is run `PrepareCsvExport`, run all `CsvExport` and finally run `ExportCompletion`.

The log shows what is being executed:
[laravel.log](https://github.com/laravel/framework/files/15294361/laravel.log)

### Steps To Reproduce

.env
```
QUEUE_CONNECTION=database
```

Run command (4 times): `php artisan queue:work --timeout=6000 --force --tries=3`

Code:

```php
Bus::chain([
    Bus::batch([
        new \App\Jobs\PrepareCsvExport(),
    ])->allowFailures(),
    new \App\Jobs\ExportCompletion(),
])->dispatch();
```

```php
namespace App\Jobs;

use Illuminate\Bus\Batchable;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class PrepareCsvExport implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Batchable;

    public function handle(): void
    {
        set_time_limit(6000);
        $time = time();
        logger("Start PrepareCsvExport: $time");
        for ($i=0; $i < 1000; $i++) { 
            $this->batch()->add(new CsvExport($time, $i));
            sleep(1);
        }
        logger("End PrepareCsvExport: $time");
    }
}
```

```php
namespace App\Jobs;

use Illuminate\Bus\Batchable;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class CsvExport implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Batchable;

    public function __construct(public $time, public $index)
    {
    }

    public function handle(): void
    {
        logger("Run CsvExport: $this->time - $this->index");
    }
}
```
```php
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ExportCompletion implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle(): void
    {
        logger('Run ExportCompletion');
    }
}
```

**Comment by mcolominas** [comment]
After several tests and through the discord conversation, the problem was that the retry_after needed to be increased.

I don't know how `Bus::chain` works internally, but after executing the `PrepareCsvExport` job for the third time and throw an error, as shown in the logs, `ExportCompletion` has been executed more than 100 times.

The problem comes from the fact that all the jobs are completed, the batch is marked as completed (run `ExportCompletion`) and `PrepareCsvExport`, which is still running, adds more jobs, all the jobs are finished again, marked as completed and it enters a loop, continually running `ExportCompletion`.

Should this be considered a bug? In my opinion, Laravel should throw an error if jobs are added to a bach that has been completed.

**Comment by driesvints** [comment]
Hi @mcolominas. I personally feel the docs are pretty clear on the `retry_after` option: https://laravel.com/docs/11.x/queues#job-expiration

If you believe this can be improved, we'd welcome a PR to the docs. Right now we don't consider this a bug, sorry.
