### ISSUE TITLE
During the Composer update process in the Laravel framework

### ISSUE THREAD

**Issue by krisztinzoltan** [laravel/framework#51406]
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

Mysql 8.3

### Description

During the Composer update process in the Laravel framework, an error occurred, resulting in the following error message:
Deprecated: Optional parameter $api declared before required parameter $then is implicitly treated as a required parameter in /Users/zoltankrisztin/PhpstormProjects/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Configuration/ApplicationBuilder.php on line 185

### Steps To Reproduce

composer update

**Comment by driesvints** [comment]
Thank you for reporting. I'm guessing you're using a dev version of framework? Because it's from https://github.com/laravel/framework/pull/51356 which hasn't been released yet so the above reported version is incorrect.

**Comment by krisztinzoltan** [comment]
> Köszönjük a bejelentést. Gondolom a keretrendszer fejlesztői verzióját használod? Mivel [az #51356-os](https://github.com/laravel/framework/pull/51356) számból származik, ami még nem adták ki, így a fent közölt verzió hibás.

Yes, I am using a developer version.

**Comment by driesvints** [comment]
Gotcha. Gonna close this one then since this isn't released yet.

**Comment by krisztinzoltan** [comment]
Thank you
