### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by laduniestu** [laravel/framework#51403]
![Screenshot 2024-05-14 at 16 43 00](https://github.com/laravel/framework/assets/44757637/b34ea43a-27a2-4d2c-b110-85b0dc7400e3)

i just had this error when installing new laravel project

_Originally posted by @laduniestu in https://github.com/laravel/framework/issues/51201#issuecomment-2108528045_

**Comment by laduniestu** [comment]
im using herd on ARM mac OS

**Comment by driesvints** [comment]
Sorry, I couldn't reproduce this with the latest installer version.

**Comment by laduniestu** [comment]
> Sorry, I couldn't reproduce this with the latest installer version.

what should i do to make a new laravel project then?

**Comment by onnoink** [comment]
It seems that you are using an unofficial packagelist source that hasn't synchronized the latest 1.3.0 tags yet. You can try replacing your packagelist source with the default official source (url: https://repo.packagist.org/).
