### ISSUE TITLE
DB schema breaking when using older MariaDB with Laravel 11.x

### ISSUE THREAD

**Issue by leomedeiros** [laravel/framework#51409]
### Laravel Version

11.x

### PHP Version

8.2.17

## Background
MariaDB only added the `generation_expression` column to the `information_schema.columns` table on version 10.2 (https://jira.mariadb.org/browse/MDEV-9255).

`Database\Schema\Grammars\MariaDbGrammar`  extends `Database\Schema\Grammars\MySqlGrammar`. 

Starting on version 11.x (https://github.com/laravel/framework/commit/6f3ddc3c145b66532d0450fb7c5fd145d78bfcaa) , `MySqlGrammar->compileColumns()` started to pull `generation_expression` from `information_schema.columns`. 

## Problem
If you are running Laravel 11.x on a MariaDB older than 10.2, it will break because the `information_schema.columns` table won't have the `generation_expression` column.
 

### Steps To Reproduce

Setup Laravel 11.x on a MariaDB server and try to run a `Schema.hasColumn()` command. It will break.

**Comment by Jubeki** [comment]
Laravel only supports Mariadb 10.3+ (See https://laravel.com/docs/11.x/database#introduction)

**Comment by driesvints** [comment]
I'm afraid we don't support this version, sorry.
