### ISSUE TITLE
Date comparison problem

### ISSUE THREAD

**Issue by isisureste** [laravel/framework#51414]
### Laravel Version

11

### PHP Version

8.2.12

### Description

Today I was working with Laravel 11 in the latest version, with a comparison of dates and I noticed that in this version my result that previous versions marked False now marks True, perform the tests in other versions of Laravel such as Laravel 9 and mark False, that is The answer is correct since it is False.

### Steps To Reproduce

  $createTime =  Carbon\Carbon::parse('2024-05-14T20:49:47.591Z', 'UTC')->tz('America/Merida');
  $startedAt  = Carbon\Carbon::parse('2024-04-14 14:49:15');
  $finishAt   = Carbon\Carbon::parse('2024-05-14 14:49:15');
  $createdTimeClosesToStarterAt = $createTime->diffInDays($startedAt) < $createTime->diffInDays($finishAt);

Returns True and is False in other versions prior to 11.

  $createTime =  Carbon\Carbon::parse('2024-05-14T22:20:22.847Z', 'UTC')->tz('America/Merida');
  $createTime =  strtotime($createTime);
  $startedAt = strtotime('2024-05-14 16:32:38');
  $finishAt = strtotime('2024-06-14 16:32:38');

  $diffToStartedAt = abs(($createTime - $startedAt) / (60 * 60 * 24));
  $diffToFinishAt = abs(($createTime - $finishAt) / (60 * 60 * 24));

  $createdTimeClosesToStarterAt = $diffToStartedAt < $diffToFinishAt;
  dd($createdTimeClosesToStarterAt);

**Comment by crynobone** [comment]
Please report any issue specific to `Carbon` to https://github.com/briannesbitt/carbon

**Comment by kylekatarnls** [comment]
Cross-posting: to get the absolute difference in days in Laravel 11 use `abs($createTime->diffInDays($startedAt))` this value is signed by default as documented since Carbon 3.
