### ISSUE TITLE
Schema::getColumnType expects given column name to be lowercase

### ISSUE THREAD

**Issue by DeffiDeffi** [laravel/framework#51429]
### Laravel Version

11.7.0

### PHP Version

8.3

### Description

When calling `Schema::getColumnType` on a column that does not follow conventions and contains capital letters, the function will fail with `There is no column with name X`. Instead, you'll have to pass the column name in lower letters.

Now, an easy fix is to run the column name through `strtolower` but the error message is not really descriptive and I had to dive into the `getColumnType` definition to find out why this was happening.

### Steps To Reproduce

- Create a table (e.g. `posts`) containing a column with any name (e.g. `id`).
- Call `Schema::getColumnType('posts', 'id')`. It will return the column type.
- Now call `Schema::getColumnType('posts', 'ID')`. It will throw an `InvalidArgumentException` with the message `There is no column with name 'ID' on table 'posts'`.

**Comment by driesvints** [comment]
What's your database driver and version?

**Comment by DeffiDeffi** [comment]
I'm using Laravel's `sqlsrv` driver with Microsoft's PHP extension v5.12.0.

I don't think this is a driver issue, though -- [in this line of the Schema builder](https://github.com/laravel/framework/blob/3d800c5bd251e2becce4742671ab51c5d88830a3/src/Illuminate/Database/Schema/Builder.php#L296) the given column name is identify checked against a lower-cased column name fetched from the database. Would a `strtolower` on the `$column` variable break something on other drivers?

**Comment by driesvints** [comment]
Someone sent in a PR for this one. Thanks!
