### ISSUE TITLE
user appears to be logged out when password is updated (fortify)

### ISSUE THREAD

**Issue by comhon-project** [laravel/framework#51426]
### Laravel Version

v11.7.0

### PHP Version

8.2

### Database Driver & Version

mariadb

### Description

in my single page application, after updating user password with fortify route ` PUT /user/password` user appears to be logged out when requesting server again.

My investigation : 
In my `App\Actions\Fortify\UpdateUserPassword`, if I remove the line `'password' => Hash::make($input['password']),`, the user still logged in and he can request server again as a logged user (but of course password is not updated).  
So I assume the password is "linked" to the user session and when we update it, the session is not valid anymore ?

(I tried to update config file hashing.php with `'rehash_on_login' => false,` but this does not solve the problem)

### Steps To Reproduce

using laravel fortify : 
* I log in a user
* I call route ` PUT /user/password`
* I call any other route that need to be logged in
  * I receive a 401 response

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
