### ISSUE TITLE
PROPOSAL: Handling default values within \Illuminate\Queue\SerializesModels

### ISSUE THREAD

**Issue by rafrgnrx** [laravel/framework#51438]
### Laravel Version

v10.48.10

### PHP Version

8.2.15

### Description

This is also an "issue" in the master branch

When working with objects that go on the queue, and the object's property list is changed between when it goes onto the queue and when it's ran from the queue: you get `typed property <CLASS>::$<PROPERTY> must not be accessed before initialization`, which is fair, but we can (sometimes) give properties default values, and then it just works... except in this "issue"

When the properties are given defaults in the constructor (or when using [promoted constructor parameters](https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.promotion.)), `\Illuminate\Queue\SerializesModels::__unserialize` doesn't try to handle it, and it is never initialized

So this becomes a question, should this be fixed, or should there be a warning added to the queue's documentation along the lines of: "you must either ensure it's a class property and has a default, an untyped property (then it's null) and an if around new code, or disable the InteractsWithQueue class and run until no jobs remain until deploying it"?

To be fair, updating a queue'd object's constructor is an edge case

RELATED (when using promoted constructor params): [PHP BUG 81386](https://bugs.php.net/bug.php?id=81386&edit=1)

### Steps To Reproduce

1. Create any InteractsWithQueue class with promoted constructor parameters instead of properties
2. Queue this class up on a queue_driver that is not `sync`
3. Add a new promoted parameter to the class constructor with a default, and use this parameter in run code
4. Run queue for the class

**Comment by driesvints** [comment]
Any code that's still on a queue should be handled before the code is changed.
