### ISSUE TITLE
Backward compatibility makes `lang:publish` command useless!

### ISSUE THREAD

**Issue by abedcodes** [laravel/framework#51432]
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

MySQL 8

### Description

Hi, some packages still publish translations to `/resources/lang` not new root `/lang` directory. when `/resources/lang` exists(even as an empty folder, which makes laravel read translations from framework files) laravel does not care about `/lang` so changing those translations does not reflect in the app. 
I run `$request->validate()` & translating validation error messages does not work.

I moved `/lang` subdirectories to `/resources/lang` so I'm fine now, but i think it is considered a bug. 

Thanks in advance 🙌

### Steps To Reproduce

1. run `lang:publish`
2. create an empty `lang` directory in `/resources`
3. change translations in `/lang`
4. change translations in `/lang` & check validation errors using `$request->validate()`

**Comment by driesvints** [comment]
You either use one or the other but not both at the same time.

**Comment by abedcodes** [comment]
Yes i don't, but some packages still publish translations to `resources/lang/vendor` directory, making `lang:publish` command a little confusing! shouldn't framework be immune to packages stuffs? not letting them make documentation not working?
