### ISSUE TITLE
Jobs in default queue not working

### ISSUE THREAD

**Issue by drjoju** [laravel/framework#51448]
### Laravel Version

10.48.10

### PHP Version

8.3.3 (also in 8.2)

### Database Driver & Version

MySQL 8.0.30

### Description

We are experiencing an issue with our Laravel job queue. When we run the queue worker with the default configuration or specify only the default queue, the jobs in the database are not processed. However, when we specify multiple queues, including the high priority queue or any other queue, the jobs are processed correctly. It seems that the jobs are only processed when multiple queues are specified, even if some of the additional queues are not used. Is this a bug?

### Steps To Reproduce

If we run 
`php artisan queue:work`

the jobs in the database are not processed.

If we run
`php artisan queue:work  --queue=default`
The jobs in the database are not processed. :(

BUT...

If we run 
`php artisan queue:work  --queue=high,default`
or
`php artisan queue:work  --queue=default,high`
or
`php artisan queue:work  --queue=high,XXXXX` where XXXX is whatever you want, the jobs are processed.

Is it a bug?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
