### ISSUE TITLE
Rules with numeric keys do not validate properly

### ISSUE THREAD

**Issue by Tofandel** [laravel/framework#51499]
### Laravel Version

10.48.10

### PHP Version

8.3

### Description

Numeric rules (Eg: `[4 => 'required', 8 => 'required']`) when added to a validator are not saved properly, they are transformed into`[0 => 'required', 1 => 'required']` in the constructor

I tracked it down to this line
https://github.com/laravel/framework/blob/bf7046f37a03ac006f60a811148f91393f305283/src/Illuminate/Validation/Validator.php#L1208-L1210

It seems the array merge recursive treats any numeric key differently and just appends it to the array instead of preserving the keys, this is explained in the php doc, but undesirable behavior in this case https://www.php.net/manual/en/function.array-merge-recursive.php

```php
array_merge_recursive([], ['foo' => 'required', 4 => 'required', 8 => 'required']);
= [
    "foo" => "required",
    0 => "required",
    1 => "required",
  ]
```

### Steps To Reproduce

Running the following in a tinker session is enough to reproduce
```php
Validator::validate(['foo' => 'baz', 4 => 'foo', 8 => 'baz'], ['foo' => 'required', 4 => 'required', 8 => 'required']);
```

Results in
```
   Illuminate\Validation\ValidationException  The 0 field is required. (and 1 more error).
```

A possible solution is a different implementation of the `array_merge_recursive` as seen here https://www.php.net/manual/en/function.array-merge-recursive.php#106985

Prior attempt at a fix https://github.com/laravel/framework/pull/39368

**Comment by crynobone** [comment]
Since this behavior has been present ever since the beginning I don't think we can change this. Should you want to propose this change I suggest you to attempt a PR to the master branch. Thanks

**Comment by Jacobs63** [comment]
What is the actual, valid, use-case for this?

This seems very unlikely to anyhow useful in a real use-case.

**Comment by Tofandel** [comment]
@crynobone thank you for this very insightful copy-paste

But this "behaviour" is a bug and it existing forever is not a valid reason to not want to improve the tool/framework we are working on for future use

**Comment by crynobone** [comment]
@Tofandel feel free to send a PR to `master` branch as suggested earlier.

**Comment by rodrigopedra** [comment]
As a workaround, you can wrap your fields' IDs into the same name key. 

Code will explain better:

```php
// routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

// from DB
$fields = [
    4 => ['label' => 'name', 'rule' => 'required'],
    8 => ['label' => 'surname', 'rule' => 'required'],
];

Route::get('/', fn () => view('form', ['fields' => $fields]));

Route::post('/', function (Request $request) use ($fields) {
    $rules = collect($fields)->mapWithKeys(fn ($field, $id) => [
        'field.' . $id => $field['rule'],
    ]);

    $attributes = collect($fields)->mapWithKeys(fn ($field, $id) => [
        'field.' . $id => $field['label'],
    ]);

    $request->validate($rules->all(), attributes: $attributes->all());

    return back();
});
```

```blade
{{-- resources/views/form.blade.php --}}
<div style="white-space: pre-wrap;">@json($errors->all(), JSON_PRETTY_PRINT)</div>

<form action="/" method="POST">
    @csrf

    @foreach($fields as $id => $field)
        <label for="field-{{ $id }}">{{ $field['label'] }}</label>
        <input type="text" id="field-{{ $id }}" name="field[{{ $id }}]">
        <br>
    @endforeach

    <button type="submit">send</button>
</form>
```

**Comment by Tofandel** [comment]
@rodrigopedra Thanks, that's what I did but then the problem is that the path of the field in the error bag doesn't match with the output I want which is yet another workaround needed

**Comment by driesvints** [comment]
Thanks. This has come up before quite a few times. We decided we won't be changing this behaviour because this could have quite an impact on existing apps, sorry for that. We could maybe make the docs more clear about this so feel free to attempt a PR to the docs.

**Comment by Tofandel** [comment]
@driesvints 
> quite an impact on existing app

I would like to see what exactly what that could be, because I don't see it at all. A validator works only on keyed arrays
