### ISSUE TITLE
about FormRequest bail 

### ISSUE THREAD

**Issue by cjango** [laravel/framework#51510]
### Laravel Version

10.48

### PHP Version

8.2

### Description

当password字段的验证，使用 `Password::min(8)->mixedCase()->numbers()` 的时候，即使增加了 bail 属性，验证信息的提示为，***密码 至少为 8 个字符。 (and 1 more error)***，如何让这个 ***and 1 more error*** 消失呢，我已经在`FormRequest`的类中增加了` protected $stopOnFirstFailure = true;` 这个属性

### Steps To Reproduce

```php
 public function rules(): array
    {
        return [
            'username' => [
                'required',
                'bail',
                new MobileRule(),
            ],
            'password' => [
                'required',
                'bail',
                config('user.STRONG_PASSWORD') ? Password::min(8)->mixedCase()->numbers() : Password::min(6),
            ],
        ];
    }
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
