### ISSUE TITLE
Unescaped Reserverd keyword on Postgres

### ISSUE THREAD

**Issue by thecyrilcril** [laravel/framework#51511]
### Laravel Version

 11.7.0

### PHP Version

8.3.0

### Database Driver & Version

postgres (PostgreSQL) 16.2 on Windows 10 Pro 22H2

### Description

Creating a generated column `signature` from a JSON column `authorization` fails with the following error `SQLSTATE[42601]: Syntax error: 7 ERROR: ...`

Consider 
```
    $table->json('authorization');
    $table->string('signature')->storedAs("authorization->>'signature'");
```

The `signature` column  is generated from the ``authorization``` column. 

### Steps To Reproduce

1. Create a migration
```
public function up(): void
{
  Schema::create('cards', function (Blueprint $table): void {
    $table->id();
    $table->json('authorization');
    $table->string('signature')->storedAs("authorization->>'signature'");
  });
}
...        
```
2. Runing the above migration fails with 
```
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "->>"
LINE 1: ...r(191) not null generated always as (authorization->>'signat...
```

3. Runing the migration with the `--pretend` flag results in 
```
create table "cards" (
  "id" bigserial not null primary key, 
  "authorization" json not null, 
  "signature" varchar(191) not null generated always as (authorization->>'signature') stored
)
```  
which shows the unescaped reserved keyword `authorization` @tpetry 

4. The escaped syntax should be:
```
create table "cards" (
  "id" bigserial not null primary key, 
  "authorization" json not null, 
  "signature" varchar(191) not null generated always as ("authorization"->>'signature') stored
)
```

**Comment by tpetry** [comment]
I've chatted with @thecyrilcril about this. This is not a bug in Laravel.

The expression will be passed directly to the database and therefore escaping reserved keywords (`authorization `) needs to be done manually.

The MySQL driver implements special logic (`->storedAs('authorization->signature')`) that would transform a JSON selector to the valid SQL expression and could automatically escape the column. But this is not implemented for PostgreSQL as `abc->xyz` is also a valid expression for PG (but not MySQL).

So the drivers will behave differently when passed a JSON selector which is not great... But the only way possible to not prevent some PG functionality.

**Comment by crynobone** [comment]
Thanks @tpetry
