### ISSUE TITLE
Bulk Update and Creation Report

### ISSUE THREAD

**Issue by caioSalchesttes** [laravel/framework#51528]
### Laravel Version

11

### PHP Version

8.3

### Database Driver & Version

pgsql

### Description

**Introduction**
In this report, we will discuss the process of performing bulk updates and creations in a Laravel application using the DatasetLabel::upsert method. This method allows us to handle multiple records simultaneously, either updating existing records or creating new ones based on specified conditions. However, certain issues arise when the id field is missing or null in the dataset. We will explore these issues and propose solutions to ensure the smooth execution of bulk operations.

**Problem Statement**
The DatasetLabel::upsert method is designed to update or insert multiple records in a database. The method requires a unique key to determine whether a record should be updated or inserted. In our case, the unique key is the id field. The following scenarios present challenges:

Missing id for Creation: When a record does not have an id, it is assumed that the record is intended for creation. However, the id field is required for identifying records uniquely. If an id is not provided, an error occurs.
Null id for Creation: If a record has a null id, it is unclear whether it is meant to be a new record or if the null value is an error. This ambiguity can cause issues during the upsert operation.
Missing id in Comparison: When performing the upsert, all records must have consistent keys for comparison. If an id is missing, the method cannot determine whether to update an existing record or insert a new one.
**Example Dataset**
Consider the following dataset:

```
DatasetLabel::upsert(
    [
        ['id' => 4, 'name' => 'A', 'tenant_id' => 1, 'dataset_id' => 1],
        ['name' => 'B', 'tenant_id' => 1, 'dataset_id' => 1]
    ],
    uniqueBy: ['id'],
    update: ['name']
);
```

**Analysis**
The first record has a valid id of 4 and will be updated if it exists.
The second record lacks an id, indicating that it is intended for creation. However, without an id, the upsert method cannot uniquely identify it.

### Steps To Reproduce

Set up new Laravel 11 project.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
