### ISSUE TITLE
Query building is failing if using '->having()' method

### ISSUE THREAD

**Issue by Indianos** [laravel/framework#51533]
### Laravel Version

10.48.11

### PHP Version

8.2.17

### Description

I am trying to migrate an old code to laravel and it's using SQL 'HAVING' clause. However if I try to compose via `Query/Builder::having(Clousure)` it throws an error:

> TypeError 
>
>  count(): Argument #1 ($value) must be of type Countable|array, null given
>
>  at vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2298
>    2294▕      * @return $this
>    2295▕      */
>    2296▕     public function addNestedHavingQuery($query, $boolean = 'and')
>    2297▕     {
>  ➜ 2298▕         if (count($query->havings)) {
>    2299▕             $type = 'Nested';
>    2300▕ 
>    2301▕             $this->havings[] = compact('type', 'query', 'boolean');
>    2302▕

### Steps To Reproduce

```php
\Illuminate\Support\Facades\DB::query()
    ->select()
    ->from('some_table')
    ->having(fn ($query) => $query->where('id', '>', 0));
```

**Comment by staudenmeir** [comment]
Hi @Indianos,
You need to call `having()` inside the closure:

```php
->having(fn ($query) => $query->having('id', '>', 0));
                                ^^^^^^
```

**Comment by crynobone** [comment]
Thanks @staudenmeir
