### ISSUE TITLE
Create method returns always first record with related internal model

### ISSUE THREAD

**Issue by mohammadMghi** [laravel/framework#51578]
### Laravel Version

10.48.8

### PHP Version

8.2.19

### Database Driver & Version

MYSQL

### Description

Consider this snip code . I want to create a record in DB after return stored the data along with `with()` method but it's always returns first record.

If i use `get()` instead of `first()` it's returns all stored data.

### Steps To Reproduce

`$result = Protest::create($fields);`   
 
`return $result->with('service')->first()->toArray();`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mohammadMghi** [comment]
Do you think if we can use with() after Create() method it's very clear and useful?
Thanks.
