### ISSUE TITLE
isRelation checks only if a method exists but not if a relation is returned

### ISSUE THREAD

**Issue by denny-bee** [laravel/framework#51592]
### Laravel Version

10

### PHP Version

8.2

### Database Driver & Version

MySql

### Description

HasAttributes.php has the method isRelation.

This method only checks if there is no mutator with the same name and if there is a method with this name.

But if you have some helper methods which are not accessors ("getXyzAttribute" or "xyz(): Attribute"), it will still say it is an relation, which is not correct.

In my oppinion there should be a check for the return type like it is used in "hasAttributeMutator":

```
$returnType = (new ReflectionMethod($this, $method))->getReturnType();

return static::$attributeMutatorCache[get_class($this)][$key] =
                    $returnType instanceof ReflectionNamedType &&
                    $returnType->getName() === Attribute::class;
```

If there are some helper methods which are not relations but return the same type, they could be defined in a property and excluded by this check to support third party packages and custom code.

"Illuminate\Database\Eloquent\Relations\Relation" could be the type instead of Attribute::class in this case.

But with is_a instead of a basic check to include classes which extend Relation::class.

Or is there any other reason why this was not implemented this way?

### Steps To Reproduce

1. Create an model
2. Add a helper method e.g. pizza() this model
3. isRelation('pizza') on a object of this model would result in true, but it is not an relation

**Comment by crynobone** [comment]
Can you create a failing test PR for this use case?

**Comment by staudenmeir** [comment]
This topic is quite complex, unfortunately. Resolving the method can have unintended consequences, e.g. when doing something like `$user->isRelation('delete')`.

We can use the approach from the `model:show` command that checks the method's actual code before resolving it:
https://github.com/laravel/framework/blob/8fde0eafc95d7d166594a248585f532755cab031/src/Illuminate/Database/Console/ShowModelCommand.php#L191

This is much safer. The only downside I know is that it doesn't detect third-party relations.

**Comment by driesvints** [comment]
@staudenmeir good call

**Comment by caseydwyer** [comment]
@driesvints could we possibly reopen this? Still an issue in 12.x and bit us recently on a Filament-based project (see link above for more context, if helpful). I did try a simple swap on that `isRelation` method (`&&` instead of `||` on `HasAttributes` line 588), but as you mentioned earlier, that breaks quite a few other/unrelated tests. Lmk if there's anything I can do to help, here!
