### ISSUE TITLE
Booted in a trait with trait name does not work

### ISSUE THREAD

**Issue by timboozle** [laravel/framework#51596]
### Laravel Version

11.8.0

### PHP Version

8.3.7

### Description

Trying to add a trait to a model that runs when booted.

```
trait CustomTrait
{
    protected static function bootedCustomTrait()
    {
        dd('Booted');
    }
}
```

Most other scenarios work:

- ✅ `booted()` on the model
- ✅ `booted()` on the trait
- ❌ `bootedCustomTrait()` on the trait
- ✅ `boot()` on the model
- ✅ `boot()` on the trait
- ✅ `bootCustomTrait()` on the trait

### Steps To Reproduce

Add `CustomTrait` from the example to any model.

**Comment by driesvints** [comment]
We don't support such usage?

**Comment by timboozle** [comment]
> We don't support such usage?

Wait, not at all? Or just not for `booted()`? Because the internet is full of examples of this usage.
