### ISSUE TITLE
Things break if you mix the @php(...) inline directive with @php and @endphp

### ISSUE THREAD

**Issue by tkoop** [laravel/framework#51591]
### Laravel Version

11.0.8

### PHP Version

8.2.19

### Description

By itself, the following blade content works fine:
```
<p>
  Five plus three equals
  @php($eight = 5 + 3)
  {{ $eight }}.
</p>
```

Also, by itself, the following blade content works fine:
```
<p>
  My favourite colour is
  @php
    $modifier = "light";
    $colour = "blue";
  @endphp
  {{ $modifier }} {{ $colour }}.
</p>
```

However, if you put them together, you get an error:
```
<p>
  Five plus three equals
  @php($eight = 5 + 3)
  {{ $eight }}.
</p>

<p>
  My favourite colour is
  @php
    $modifier = "light";
    $colour = "blue";
  @endphp
  {{ $modifier }} {{ $colour }}.
</p>
```

The error in this case is: `Spatie\LaravelIgnition\Exceptions\ViewException: Undefined variable $modifier in file my-cool-thing.blade.php on line 13`

The generated PHP code from this blade is this:
```
<p>
	Five plus three equals
	<?php($eight = 5 + 3)
	{{ $eight }}
</p>

<p>
	My favourite colour is
	@php
		$modifier = 'light';
		$colour = 'blue';
	?>
	<?php echo e($modifier); ?> <?php echo e($colour); ?>

</p>
```

### Steps To Reproduce

To reproduce, paste the example code into a blade file and view it.

**Comment by rodrigopedra** [comment]
Inline PHP statements, using blade, are no longer recommended:

https://github.com/laravel/framework/issues/51313#issuecomment-2095905952

And no longer documented:

https://laravel.com/docs/11.x/blade#raw-php

Note that the comment linked above is from an issue that reports the exact same thing.

**Comment by crynobone** [comment]
Thanks @rodrigopedra
