### ISSUE TITLE
Model::preventLazyLoading() not working

### ISSUE THREAD

**Issue by vascocarreira** [laravel/framework#51604]
### Laravel Version

10.48.12

### PHP Version

8.2.14

### Database Driver & Version

MySQL 8.0.30

### Description

When using Model::preventLazyLoading() in the boot method of AppServiceProvider, I'm still being able to lazy load relationships.

### Steps To Reproduce

- AppServiceProvider (Model::shouldBeStrict() calls Model::preventLazyLoading())
![Screenshot 2024-05-28 200812](https://github.com/laravel/framework/assets/28606926/35639525-66f7-4a0a-bc07-bacae528bf95)

- Model::find() without with()
![Screenshot 2024-05-28 201110](https://github.com/laravel/framework/assets/28606926/03094a8b-2afc-4901-95cf-494e69a8a077)

- View
![Screenshot 2024-05-28 201126](https://github.com/laravel/framework/assets/28606926/d9a43d0d-3834-4a7c-b14a-9320d6ae07d8)

- Result
![Screenshot 2024-05-28 201208](https://github.com/laravel/framework/assets/28606926/73f410c4-a5a1-4afb-b2a6-fc297438c63d)

**Comment by iBotPeaches** [comment]
You pulled 1 entity and requested the teachers relationship off of it. That seems like it would get loaded already at once whether eager or not. If you found many Departments, then I'd think you'd hit the lazy loading as you'd need all teachers in each department, which would cause the n+1 problem to appear.

**Comment by crynobone** [comment]
Thanks @iBotPeaches
