### ISSUE TITLE
Model retrieved event fires before eager loaded relationships are populated

### ISSUE THREAD

**Issue by brentkelly** [laravel/framework#51608]
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

sqlite 3.37.2
mysql 8.0.32 

#### The problem
When hooking into the `retrieved` event for a model, I would expect it to have been "fully retrieved". However, if you are eager loading relationships, the event fires before those relationships have been loaded.

#### Impact
If your `retrieved` hook then uses those relationships it will result in needless database accesses to lazy load the relationship data for each model - one at a time - i.e. the N+1 query problem that eager loading was designed to solve. 

This is certainly not what a developer using this functionality would expect having explicitly called `with` to eager load the relationship. Worse still - a causal read of the code looks like the relationship data will then (after the event has been dispatched) be "eager loaded" a 2nd time for matching models.

Is there any reason why you would want this to be the case? I can't think of any. And even if we did need an event that fired mid-way during the retrieving process, I'd have thought it would best (in line with other model events) be a separate event called `retrieving` rather than `retrieved` which implies the retrieval process has completed when the event fires.

Another side-effect (which initially got me investigating) is that calling `$model->toArray()` in the callback would usually output an array containing all loaded relationships. However because the relations are not loaded, they are not present in the resulting array. I need to access relationships after retrieving, yet I am currently checkmate with no way of achieving this without introducing an N+1 query problem.

#### Analysis
The "culprit" code is as follows:

1. The `retrieving` event fires from `Model::newFromBuilder` when models are being hydrated
2. `Illuminate\Database\Eloquent\Builder::get` - inside the call to `getModels`, it executes the query & hydrates the models (which triggers `retrieving` for each). After retrieving the models it **then** eager loads the relations:

```php
    public function get($columns = ['*'])
    {
        $builder = $this->applyScopes();

        // If we actually found models we will also eager load any relationships that
        // have been specified as needing to be eager loaded, which will solve the
        // n+1 query issue for the developers to avoid running a lot of queries.
        if (count($models = $builder->getModels($columns)) > 0) {
            $models = $builder->eagerLoadRelations($models);
        }

        return $this->applyAfterQueryCallbacks(
            $builder->getModel()->newCollection($models)
        );
    }
```

#### Possible solutions
I'm assuming to resolve this ideally `get` would loop over the models to explicitly fire the model `retrieved` event, or an `afterQuery` callback would be defined somewhere which achieved the same.

Alternatively `newFromBuilder` could accept eager loaded relation data & hydrate the new instance with relation data prior to calling the `retrieved` hook.

### Steps To Reproduce

Here is a standalone test to prove the issue: https://gist.github.com/brentkelly/8e7f4ecfe92e6c8e8c8e7aff6967e609

To manually reproduce:

1. Define a `retrieved` hook in your boot method

```php
class Posts
{
    protected static function boot()
    {
        parent::boot();

        static::retrieved(function (Model $model) {
            dd($this->relationLoaded('comments'));
        });
    }

    // ... etc
}
```

2. Retrieve models while eager loading the desired relation

```
$posts = Posts::with('comments')->all();
```

Expected result: `true`
Actual result: `false`

**Comment by brentkelly** [comment]
Here is a manual illustration that shows the `N+1` queries - including the additional eager load query to retrieve data already now populated on the models.

In my `Account` model:

```
// inside boot()
static::retrieved(function (Model $model) {
    $tickets = $model->assignedTickets->toArray();
    echo "retrieved " . count($tickets) . " tickets for $model->id<br />";
});
```

The route:
```php
Route::get('/test', function () {
    \App\Models\Account::with('assignedTickets')->get()->each(function ($account) {
        echo "Looked at $account->id ($account->name)<br />";
    });
});
```

Queries:
![image](https://github.com/laravel/framework/assets/2694025/0682bca3-68e3-432e-8885-d9aeecff8420)

**Comment by driesvints** [comment]
So, this is not exactly how things work right now (as you've demonstrated). The `retrieved` event is fired for the calling model alone, not the relationships it has loaded. I agree this is a bit counterintuitive and it would be useful if there was a similar event that was fired when the entire model and its relationships were loaded. If you want, you could attempt a PR for this? Thanks for your report.
