### ISSUE TITLE
Out of memory when sending large disk attachments

### ISSUE THREAD

**Issue by bytestream** [laravel/framework#51620]
### Laravel Version

10.48.12

### PHP Version

8.2.19

### Description

Sending a mailable with a large disk attachment results in an out of memory exception. This is because the whole file is loaded into memory at https://github.com/laravel/framework/blob/97238d27e271d6f8b36b64680756f788130f19c5/src/Illuminate/Mail/Mailable.php#L494

It should be sent to Symfony mailer as a stream, which is already supported https://github.com/laravel/framework/blob/97238d27e271d6f8b36b64680756f788130f19c5/src/Illuminate/Mail/Message.php#L320

### Steps To Reproduce

```php
/**
 * Get the attachments for the message.
 *
 * @return array<int, \Illuminate\Mail\Mailables\Attachment>
 */
public function attachments(): array
{
    return [
        Attachment::fromStorage('/path/to/large.pdf')
                ->as('large.pdf')
                ->withMime('application/pdf'),
    ];
}
```

https://laravel.com/docs/11.x/mail#attaching-files-from-disk

**Comment by driesvints** [comment]
Thanks. Right now this isn't possible. It's also a bit unclear to me what you mean with "large"? How large are we talking about?

**Comment by bytestream** [comment]
Thanks for getting back to me. 

> Right now this isn't possible.

It's possible to use streams rather than load the file into memory i.e. `$storage->get($attachment['path']),` becomes `$storage->readStream($attachment['path']),`. That ensures Symfony mailer reads the file in chunks rather than all at once.

> It's also a bit unclear to me what you mean with "large"? How large are we talking about?

The size of the file doesn't really matter if you alter PHP's memory_limit directive i.e. `php -d memory_limit=32M`. The simple fact is that `$storage->get($attachment['path'])` unnecessarily loads the whole file into memory when there are better alternatives available.

**Comment by driesvints** [comment]
I do believe size matters as I don't think it's reasonable to send too large attachments over mail. I think it's best that if you feel something can be improved here that you attempt to send in a PR. If it can be without BC breaks it can adjust the current functionality otherwise it should be a new method. Thanks.

**Comment by bytestream** [comment]
@driesvints I agree that one shouldn't be sending large files over mail, but the code should be memory efficient and not enforce such limitations in an ungraceful manner. I sent a PR but it was closed without explanation https://github.com/laravel/framework/pull/51601. Perhaps you can offer some insight given it doesn't break BC, and just improves the efficiency of the current functionality.

**Comment by driesvints** [comment]
Hey @bytestream. It seems Taylor doesn't want to make that change right now. Since we only received one report for this we're going to leave things be sorry. You could always try to overwrite the `buildDiskAttachments` method if you want.
