### ISSUE TITLE
Str::snake doesn't handle multibyte uppercase letters

### ISSUE THREAD

**Issue by zoryamba** [laravel/framework#51624]
### Laravel Version

All versions

### PHP Version

All versions

### Description

`Str::snake` still use `ucwords` which doesn't support multibyte strings.
It's the last use of `ucwords` in Str class. It vas removed previosly from `Str::studly`: [commit](https://github.com/laravel/framework/commit/3d50d374ab9f473ef2d2daf5008f146a60e7ce07)
I'll provide PR to fix this

### Steps To Reproduce

Actual behavior:
```php
Str::snake('ÖffentlicheÜberraschungen'); // öffentlicheüberraschungen
Str::snake('ŻółtaŁódka') // żółtałódka
```

Expected behavior:
```php
Str::snake('ÖffentlicheÜberraschungen'); // öffentliche_überraschungen
Str::snake('ŻółtaŁódka') // żółta_łódka
```

**Comment by driesvints** [comment]
Thank you for your report. You seem to have sent in a PR so let's see how it goes.
