### ISSUE TITLE
import.meta.env.VITE_APP_NAME and process.env.VITE_APP_NAME not working in vite.config.js

### ISSUE THREAD

**Issue by misog** [laravel/framework#51647]
### Laravel Version

11.9.2

### PHP Version

8.2.18

### Description

`import.meta.env.VITE_APP_NAME` is undefined in vite.config.js
`process.env.VITE_APP_NAME` is undefined in vite.config.js

Also other variables defined in .env as VITE_* are not working / are undefined in vite.config.js

See https://laravel.com/docs/11.x/vite#environment-variables

### Steps To Reproduce

1. Add `console.log(import.meta.env.VITE_APP_NAME);` to vite.config.js
2. Run `npm run dev`
2. Expect value set in Laravel .env file

### Workaround
```js
import { defineConfig, loadEnv } from 'vite'; // import loadEnv
import laravel from 'laravel-vite-plugin';

const env = loadEnv(process.env.NODE_ENV, process.cwd(), ''); // get env with loadEnv

console.log(env.VITE_APP_NAME); // VITE_APP_NAME is working

export default defineConfig({
    //
});
```

This is useful when docker/sail or vagrant/homestead is used and vite fails to load assets due to incorrect default host while running `vite --host`:
```js
import { defineConfig, loadEnv } from 'vite';
import laravel from 'laravel-vite-plugin';

const env = loadEnv(process.env.NODE_ENV, process.cwd(), '');

console.log(env.VITE_HMR_HOST);

export default defineConfig({
    server: {
        hmr: {
            host: env.VITE_HMR_HOST,
        },
    },
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});

```

**Comment by timacdonald** [comment]
`import.meta.env.ENV_NAME` is only supported in files that Vite builds, not Vite's config.

Instead you should use `loadEnv`.

Docs: https://vitejs.dev/config/#using-environment-variables-in-config
Example:

```js
import { defineConfig, loadEnv} from 'vite'
import laravel from 'laravel-vite-plugin'

const env = loadEnv('', '')

export default defineConfig({
  plugins: [
    laravel({
      input: 'resources/js/app.js',
      detectTls: env.VITE_DETECT_TLS === 'true',
    }),
  ],
})
```
