### ISSUE TITLE
Unexpected `value()` method behavior when querying Eloquent models.

### ISSUE THREAD

**Issue by plakhin** [laravel/framework#51659]
### Laravel Version

11.7.0

### PHP Version

8.3.7

### Database Driver & Version

SQLite

### Description

`User::find(1)->value('email')` generates 2 SQL queries and returns incorrect result while it is expected to work the same as `User::where('id', 1)->value('email')` that generates 1 query and returns correct result.

**Correct** query produced by `User::where('id', 1)->value('email')`:
```sql
SELECT
  `email`
FROM
  `users`
WHERE
  `id` = 1
LIMIT
  1
```

**Incorrect** 2 queries produced by `User::find(1)->value('email')`:
```sql
SELECT
  *
FROM
  `users`
WHERE
  `users`.`id` = 1
LIMIT
  1
```
```sql  
SELECT
  `email`
FROM
  `users`
LIMIT
  1
```

So the `value()` method in the second case returns the value of `email` column of the row returned by DB without filtering by `id` column.

### Steps To Reproduce

1. Get a fresh Laravel 11.7.0 (or 10.48.4) installation;
1. Create either MySQL or SQLite database
1. Run `php artisan migrate:fresh --seed`;
1. Run `App\Models\User::where('id', 1)->value('email')` then run `App\Models\User::find(1)->value('email')`;
1. Compare sql queries produced.

**Comment by driesvints** [comment]
That's intended. `find` is a direct search and retrieve method while `value` was intended to be used in combination with the query builder like you've demonstrated.
