### ISSUE TITLE
The Route::dispatch method cannot pass parameters to the called controller.

### ISSUE THREAD

**Issue by jinghewang** [laravel/framework#51656]
### Laravel Version

11.1.0

### PHP Version

8.2.6

### Database Driver & Version

mysql 5.7 for centos 7

### Description

The Route::dispatch method cannot pass parameters to the called controller.

FirstController  cannot pass parameters to the SecondController
`
use App\Http\Controllers\BaseController;
use App\Services\EtcdService;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

/**
 */
class SecondController extends BaseController
{

    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return Renderable
     */
    public function index(Request $request) {
        return __CLASS__;
    }

    public function hello(Request $request)
    {
        $data = $request->all();

        return response()->json(['message' => 'Data received', 'data' => $data]);
    }

}

use App\Http\Controllers\BaseController;
use App\Services\EtcdService;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Termwind\Components\Dd;

/**
 */
class FirstController extends BaseController
{

    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return Renderable
     */
    public function index(Request $request)
    {
        return __CLASS__;
    }

    /**
     * 
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function hello(Request $request)
    {
        $data = [
            'key1' => 'value1',
            'key2' => 'value2',
            'array_key' => ['item1', 'item2', 'item3']
        ];

        $secondRequest = Request::create('/test/second/hello', 'POST', $data);
        $response = Route::dispatch($secondRequest);
        $content = $response->getContent();

        return response()->json(['message' => 'First route called', 'second_route_response' => $content]);
    }`

### Steps To Reproduce

look up

**Comment by crynobone** [comment]
There's should only one Request instance per request lifecycle.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
