### ISSUE TITLE
once() usage with static methods

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#51672]
### Laravel Version

11.9.2

### PHP Version

8.3.0

### Description

Hi,

I'm upgrading from laravel 10 to laravel 11

In my project i'm using spatie/once

I have this static method, when using spatie once() when the static method is called my callback will be executed once.
But with laravel 11 once() it's executing the callback with each call to my static method.

```php

public static function getActiveByDateString(string $date): ?self
    {
        return once(function () use ($date) {
            return self::where('start_at', '<=', $date)->where('end_at', '>=', $date)->first();
        });
    }
```

Is this behavior intended ?
I tried to install spatie/once and use it but the `replace` in `laravel/framework` composer.json prevents me from doing that.
So in this case i think it's better to remove the `replace` from composer.json and allow the developer to make his decision.

Thanks

### Steps To Reproduce

Use once() within a static method of a class

**Comment by rodrigopedra** [comment]
> So in this case i think it's better to remove the replace from composer.json and allow the developer to make his decision.

I don't believe that is possible, as both Laravel and Spatie's package define this function in the global namespace.

To have both options, one party should have to either rename their function, or to namespace it.

It might be possible, as Laravel's version is wrapped into a `function_exists()` check. Although it would depend on the order packages are loaded (if Spatie's is loaded after Laravel's, PHP will trigger a function already exists error).

On the other hand, if Spatie's package is loaded first, and therefore the `function_exists()` guard will prevent Laravel's one to be defined, is if Laravel's `once()`'s version is used within the framework itself, and it expects it to behave as it is declared.

For example, Laravel's version uses both the `Illuminate\Support\Once` and the `Illuminate\Support\Onceable` classes under the hood. If some code relies on these classes being called (either now, or in the future, for example for octane cleanup between requests), it won't work as expected anymore, if you manage to have Spatie's version declared upfront.

So I guess you are out of luck here.

One option is to have a local copy from Spatie's one, as you prefer their behavior, and namespace it.

Another option, is to send a PR to propose Laravel's to behave the same way regarding this use case.

And a more convoluted option is to propose to either party to namespace their offering, so one can have both available.

**Comment by shadoWalker89** [comment]
The best thing that would happen is if laravel once() will actually work like spatie with static methods, but that is a breaking change.
For now, if any one is interested the only solution that worked for me is to copy spatie code locally and rename the spatie once() to spatieOnce()

using "repositories"_attribute in composer will not work because of the replace

copying spatie code locally as is and autoload it will not work either because composer always autoloads third party code before your own code (spatie code will be considered your own because it's not installed via composer but rather copied)

Another solution is in the public/index.php and artisan you can include spatie before the composer autoload file but you will have a problem when running phpunit tests, because phpunit always load the composer autoload first, you will find yourself creating a new phpunit file in order to solve that which is not good for me.

The cleanest and best solution i've got currently is the copy spatie locally and rename the function to spatieOnce()

I hope that laravel will consider maybe making laravel once() work with static functions in a future major release.

**Comment by shadoWalker89** [comment]
I'm not asking for support for third party package

I'm asking for laravel once() to work with static methods of a class

**Comment by driesvints** [comment]
@shadoWalker89 I'm sorry but right now we don't offer this feature. You can always attempt a PR.

**Comment by crynobone** [comment]
> I'm asking for laravel once() to work with static methods of a class

Added integration tests to verify this usage #51723 and everything seems to work fine with the existing code.

You should consider sending a PR with failing tests to replicate the issue but we're not looking more into this at the moment.
