### ISSUE TITLE
Hoisted variable in template

### ISSUE THREAD

**Issue by bagasjs** [laravel/framework#51675]
### Laravel Version

9.52.7

### PHP Version

8.2.4

### Description

I am working with my organization project and encounter an issue with the templating of Laravel. It's look like that Laravel Blade has no scopes in templates, all variable in template is hoisted/declared first in global context. 

In my case there's a template ./resources/views/admin/users/index.blade.php. This template basically shows all the users in the application via foreach($users in $user) loop. This template will be called by App\Http\Controllers\Admin\UserController. The template also extends the base layout in ./resources/views/dashboard/_utils/layout.blade.php that has navigation bar in it. The navigation bar in layout refer to $user which is actually not passed by the UserController, but it still render the navigation bar since $user is defined by the loop where I expect the application should throw error.

### Steps To Reproduce

```html
// $PROJECT/resources/views/dashboard/_utils/layout.blade.php

<div class="px-4 py-3" role="none">
<p class="text-sm text-gray-900 " role="none">
  {{ $user->name }} // the value of $user will be the last iteration of foreach($users as $user)
</p>
<p class="text-sm font-medium text-gray-900 truncate " role="none">
  {{ $user->email }}
</p>
</div>
```

// $PROJECT/resources/views/admin/users/index.blade.php
```html
@extends("dashboard/_utils/layout.blade.php")
...
            @foreach($users as $user) // $user is declared/hoisted first
            <tr class="search-target-item bg-white border-b">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap  ">
                    {{ $user->id }}
                </th>
                <td class="px-6 py-4">
                    {{ $user->name }}
                </td>
                <td class="px-6 py-4">
                    {{ $user->npm }}
                </td>
                <td class="px-6 py-4">
                    <a href="{{ route('users.edit', $user->id) }}" class="focus:outline-none px-5 py-2.5 mr-2 mb-2 border-2 border-yellow-400 font-medium rounded-lg text-sm hover:bg-gray-100">Edit</a>
                    <form action="{{ route('users.destroy', $user->id) }}" class="inline-block" method="post">
                        @csrf
                        @method("delete")
                        <button class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" onclick="return confirm('Are you sure???')">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
...

````

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
