### ISSUE TITLE
RefreshDatabaseTrait is not refreshing all database connections

### ISSUE THREAD

**Issue by Pr3d4dor** [laravel/framework#51674]
### Laravel Version

11.9.2

### PHP Version

8.3.7

### Description

The RefreshDatabaseTrait is not working as intended. Not all the database connections are being refreshed correctly.

In Laravel 10 it works fine.

It stopped working after the pull request #47912.

I configured a fresh Laravel app with two database connections. After that I created two migrations, one for database A and the other for database B.

There are two simple tests that are just verifying if the table 'persons' is empty in each database connection.

When each test is ran individually the problem does not occur.

### Steps To Reproduce

Clone the repository: https://github.com/pr3d4dor/bug-report

Execute the tests:
```
php artisan test
```

Error:
```
   PASS  Tests\Feature\ExampleOneTest
  ✓ it refreshes the databases                                                                                   1.84s

   FAIL  Tests\Feature\ExampleTwoTest
  ⨯ it refreshes the databases                                                                                   0.12s
  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   FAILED  Tests\Feature\ExampleTwoTest > it refreshes the databases                                   QueryException
  SQLSTATE[HY000]: General error: 1 no such table: persons (Connection: sqlite_test, SQL: select * from "persons" limit 1)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

      +11 vendor frames
  12  tests/Feature/ExampleTwoTest.php:16


  Tests:    1 failed, 1 passed (3 assertions)
  Duration: 2.51s
```

**Comment by driesvints** [comment]
Heya, could you please re-create your repo with the below command and commit ALL of your custom changes in one single commit please? Please keep these at a minimum. Thanks.

```bash
laravel new bug-report --github="--public"
```

**Comment by Pr3d4dor** [comment]
@driesvints Here is the repo as you instructed: https://github.com/pr3d4dor/bug-report

This is the commit: https://github.com/Pr3d4dor/bug-report/commit/0c70953e4ae772eb182bba86696a7e667bfd03b5

**Comment by crynobone** [comment]
This can be fixed by adding `$connectionsToTransact` property: 

```php
    use RefreshDatabase;

    protected $connectionsToTransact = [
        'sqlite',
        'sqlite_test',
    ];

```

**Comment by bimix** [comment]
> This can be fixed by adding `$connectionsToTransact` property:
> 
>     use RefreshDatabase;
> 
>     protected $connectionsToTransact = [
>         'sqlite',
>         'sqlite_test',
>     ];

  Database connection [testing] not configured.
