### ISSUE TITLE
Str::kebab Does Not Convert snake_case to kebab-case Correctly.

### ISSUE THREAD

**Issue by sediqzada94** [laravel/framework#51677]
### Laravel Version

11.0

### PHP Version

8.2

### Description

The Str::kebab method in Laravel is intended to convert strings to kebab-case. However, it does not correctly convert snake_case strings to kebab-case. for example, the conversion from hello_world to hello-world is not functioning as expected.

### Steps To Reproduce

1-Use the following code snippet in a Laravel application:
echo Str::kebab('hello_world');

2-Observe the output.
output: hello_world
Expected Behavior
The output should be: hello-world
Actual Behavior
The output is not as expected, indicating that the snake_case to kebab-case conversion is not functioning correctly.

**Comment by driesvints** [comment]
Special characters like `_` are ignored. Only string as in the documented example are manipulated: https://laravel.com/docs/11.x/strings#method-kebab-case. So this works as expected.

**Comment by xtay2** [comment]
> So this works as expected.

Just because this works as documented, it doesn't work as expected. The name suggests that this works.

**Comment by ssang** [comment]
Sorry for commenting on an old issue but I figured that's better than opening a new issue. Is the current behaviour up for discussion. I would understand if that was consistent for all string helpers but camel does convert underscores so wondering how that's different from kebab.
