### ISSUE TITLE
Collection->shift(0) shifts 2 items instead of 0

### ISSUE THREAD

**Issue by mjomble** [laravel/framework#51684]
### Laravel Version

11.x

### PHP Version

8.1.28

### Description

The method contains the following lines:

```
        foreach (range(1, min($count, $collectionCount)) as $item) {
            array_push($results, array_shift($this->items));
        }
```

Where `min($count, $collectionCount)` evaluates to 0 and then `range(1, 0)` evaluates to `[1, 0]`, which is an array with a length of 2, causing 2 items to be shifted instead of 0.

Passing in a negative argument makes it shift even more items, e.g. -1 shifts 3. Negative arguments should probably be disallowed and throw an InvalidArgumentException?

### Steps To Reproduce

In Tinker:
```
$c = collect([10, 20, 30, 40])
$c->shift(0) // returns [10, 20]
$c // [30, 40]
```

Expected behavior:
```
$c = collect([10, 20, 30, 40])
$c->shift(0) // returns []
$c // [10, 20, 30, 40]
```

**Comment by driesvints** [comment]
Thanks. A PR was made so let's see how it goes.
