### ISSUE TITLE
request() helper not working properly when Laravel is optimized

### ISSUE THREAD

**Issue by ayzerobug** [laravel/framework#51682]
### Laravel Version

11.7.0

### PHP Version

8.2.12

### Description

Laravel request() helper won't work when app is optimized. 

`public function resolveAuthMiddleware()
    {
        return strtolower(request()->header('Request-From')) == "portal"
            ? "auth:sanctum" : "api.auth";
}
`

I have a logic to check which middleware to use depending on a header `Request-From` value. This works perfectly when the app is not optimized. But when i run `php artisan optimize`, the ternary operator returns false giving me `api:auth`. Again when i run `php artisan optimize:clear` i have `auth:sanctum`. 

PS: The request header was available when checked with telescope

### Steps To Reproduce

1) Generate a method to conclude which middleware to use
`public function resolveAuthMiddleware()
    {
        return strtolower(request()->header('Request-From')) == "portal"
            ? "auth:sanctum" : "api.auth";
    }
`

2) Make an HTTP request with header `Request-From: Portal`
3) Compare the value when optimized and when not optimized

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
