### ISSUE TITLE
`Queue::bulk()` does not use the target queues of the supplied jobs

### ISSUE THREAD

**Issue by dylanbr** [laravel/framework#51715]
### Laravel Version

10.48.10

### PHP Version

8.3.7

### Database Driver & Version

PostgreSQL 14

### Description

When using `Queue::bulk()` without the `queue` parameter, a target queue set with `onQueue()` on a job within the `jobs` array is ignored.

My expectation is that the queue name to use would be decided with the following priority:

1. If the `Queue::bulk()` `queue` parameter is set, this should override any target queue set on the individual jobs.
2. If any job in the `jobs` array has the target queue set, this should be used.
3. Otherwise, use the default queue.

### Steps To Reproduce

```php
// Create a job instance and set the target queue.
$job = (new MyJob)->onQueue('custom');

// This will enqueue the job on the `default` queue and not the `custom` queue.
Queue::bulk([$job]);
```

**Comment by crynobone** [comment]
Hi there,

`Queue::bulk()` hasn't been a documented approach since Laravel Framework 5.1 but feel free to send in a community PR to support this as long as it doesn't create a breaking change.
