### ISSUE TITLE
Connection Variable not applied in migration down() method

### ISSUE THREAD

**Issue by salfel** [laravel/framework#51735]
### Laravel Version

10.10

### PHP Version

8.1.28

### Database Driver & Version

psql (PostgreSQL) 14.12 (Homebrew) on MacOS 

### Description

When applying a connection to migration using the $connection property it works as expected in the up() method. 
But within the down() method, the connection doesn't seem to apply, it just uses the default connection. 
I also tried to add the connection manually on the schema, but same result 
`Schema::connection('crm')->dropIfExists('imports')`
to avoid this problem, one is required to put the dropIfExists method in the up() method before the Schema::create 

### Steps To Reproduce

- Start a fresh new laravel project

- Add a new database connection to database config
```php       
 'crm' => [
            'driver' => 'pgsql',
            'host' => env('CRM_DB_HOST', '127.0.0.1'),
            'port' => env('CRM_DB_PORT', '5432'),
            'database' => env('CRM_DB_DATABASE', 'crm'),
            'username' => env('CRM_DB_USERNAME', 'crm'),
            'password' => env('CRM_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
],
```
- add the necessary env variables in your .env file

- create a new migration `imports`

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {

    protected $connection = 'crm';

    public function up(): void
    {
        Schema::create('imports', function (Blueprint $table) {
            $table->id();
            $table->dateTime('finished_at');
            $table->dateTime('undo_completed_at')->nullable();
            $table->string('organization_id');
            $table->softDeletes();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('imports');
    }
};
```

- run the migration using `php artisan migrate` and then `php artisan migrate:fresh` to trigger the down method

- the following error should now show up in the terminal
```
SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "imports" already exists (Connection: crm, SQL: create table "imports" ("id" bigserial not null primary key, "finished_at" timestamp(0) without time zone not null, "undo_completed_at" timestamp(0) without time zone null, "organization_id" varchar(255) not null, "deleted_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))
```

**Comment by crynobone** [comment]
Hi there,

Can you confirm the issue exists on the latest Laravel 10? Laravel `10.10` is pretty outdated at the moment.

**Comment by staudenmeir** [comment]
Hi @salfel,

> run the migration using php artisan migrate and then php artisan migrate:fresh to trigger the down method

`migrate:fresh` doesn't call the `down()` method, it just removes all tables from the database. Only `migrate:refresh` and `migrate:rollback` call the down() method.

If you want to keep using `migrate:fresh`, you need to wipe the other databases manually:
https://github.com/laravel/framework/issues/21009#issuecomment-698290615

**Comment by salfel** [comment]
Thanks very much @staudenmeir that solves the issue

**Comment by coolamit** [comment]
> `migrate:fresh` doesn't call the `down()` method, it just removes all tables from the database. Only `migrate:refresh` and `migrate:rollback` call the `down()` method.

@staudenmeir `migrate:fresh` does seem to call the `down()` method and all tables are indeed dropped before they are recreated. It just happens only in the default database though. If you have migrations specified to run using non-default connection then the `down()` method is not being called.

**Comment by staudenmeir** [comment]
> migrate:fresh does seem to call the down() method

It doesn't (unless you call it yourself from an `up()` method). Put `dd()` in a `down()` method and you'll see that it doesn't get executed.

> all tables are indeed dropped

Laravel gets the table names from the database's internal list and just drops all of them. Your migrations have no effect here.
