### ISSUE TITLE
Laravel 10: Blade render

### ISSUE THREAD

**Issue by nguyentranchung** [laravel/framework#51750]
### Laravel Version

10.48.12

### PHP Version

8.2.18

### Description

Blade, when rendering, deleted the character starting with #!

### Steps To Reproduce

just
```php
echo Blade::render("#!/bin/bash\nabc\n#!/bin/bash\nabc");
```

expect
```
#!/bin/bash
abc
#!/bin/bash
abc
```

actual
```
abc
#!/bin/bash
abc
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
