### ISSUE TITLE
AuthenticatedLayout issue with Laravel Breeze/React

### ISSUE THREAD

**Issue by Maaz0313** [laravel/framework#51763]
### Laravel Version

11.10.0

### PHP Version

8.3.7

### Description

When typing text between html tags inside `AuthenticatedLayout ` tags of breeze, it's suggesting them as VS Code emmet abbreviation(as they are html tags).

### Steps To Reproduce

1. Create a new laravel app with breeze/react.
2. Run all the migrations first.
3. Go to `resources/js/Pages` folder.
4. Create a new folder named 'Project'.
5. Create a new jsx file named `Test.jsx`.
6. Paste the following code

```
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head } from "@inertiajs/react";

export default function Show({ auth, project }) {
  return (
    <AuthenticatedLayout
      user={auth.user}
      header={
        <h2 className="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
          {`Project "${project.name}"`}
        </h2>
      }
    >
      <Head title={`Project "${project.name}"`} />
      <div className="py-12">
        <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
          <div className="overflow-hidden bg-white shadow-sm dark:bg-gray-800 sm:rounded-lg">
            <div className="p-6 text-gray-900 dark:text-gray-100">
              <div>
                <img
                  src={project.image_path}
                  alt=""
                  className="object-cover w-full h-64"
                />
              </div>
              <div className="grid grid-cols-2 gap-1">
                <div>
                  <div>
                    <label></label>
                  </div>
                </div>
                <div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AuthenticatedLayout>
  );
}
```

7. Now type anything between label tags. It will start suggesting your typed words as if they are html tags.
All words-typing adjacent to html tags are suggesting as html emmets
I disabled all vs code extensions and stopped all servers, but nothing changes.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
