### ISSUE TITLE
Handling spaces in slug generation

### ISSUE THREAD

**Issue by will3** [laravel/framework#5177]
Currently the **slug generator** in the Illuminate\Support\Str helper produces different output depending on whitepaces in the input string.

For example:
```PHP
Str::slug('foo/bar baz');      // outputs 'foobar-baz'
Str::slug('foo / bar baz');    // outputs 'foo-bar-baz'
```

The first line results in the removal of the slash while the second lines slash sorrounded with whitespaces results in a delimiter: `foobar-baz` vs `foo-bar-baz`.

My proposal is to treat slashes in slugs the same way as whitespaces: by replacing with the delimiter. That would result in:

```PHP
Str::slug('foo/bar baz');      // outputs 'foo-bar-baz'
Str::slug('foo / bar baz');    // outputs 'foo-bar-baz'
```
_Notice now how both lines produces the same output unlike before._

**Summary**: I would like the Illuminate\Support\Str helper to transform slashes into the delimiter and not remove them entirely to avoid confusion when extra whitespaces are present around the slash.

**Comment by GrahamCampbell** [comment]
We're open to pull requests if anyone has a proposal.
