### ISSUE TITLE
Bug: Blade render

### ISSUE THREAD

**Issue by nguyentranchung** [laravel/framework#51775]
### Laravel Version

10.48.12

### PHP Version

8.2.18

### Description

the first line starts with #! will disappear

### Steps To Reproduce

open tinker
```bash
php artisan tinker
```

```php
echo Blade::render("#!/bin/bash\nabc\n#!/bin/bash\nabc");
```

<img width="559" alt="Screenshot 2024-06-12 at 4 47 53" src="https://github.com/laravel/framework/assets/9611224/b2f4ee3c-2f30-40b9-a9e2-16a51e2b792b">

expect output
```
#!/bin/bash
abc
#!/bin/bash
abc
```

actual output
```
abc
#!/bin/bash
abc
```

**Comment by nguyentranchung** [comment]
<img width="745" alt="Screenshot 2024-06-12 at 4 49 28" src="https://github.com/laravel/framework/assets/9611224/679517ee-3b96-49c1-9814-2176e0f90cad">

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
