### ISSUE TITLE
From Address is not applied when mail is sent

### ISSUE THREAD

**Issue by lanh-nguyen-vs** [laravel/framework#51788]
### Laravel Version

11.9

### PHP Version

8.3.7

### Database Driver & Version

Mysql 8.0

### Description

`
public function envelope(): Envelope
    {

        return new Envelope(

            from: new Address(address: 'jeffrey@example.com', name: 'Jeffrey Way'),

        );

    }

`
From name is shown, but From Address is not shown when mail is sent, it just show address by use MAIL_USERNAME in env file . 

### Steps To Reproduce

I want to send mail from different address.  I changed in this code but it doesn't apply 
`
public function envelope(): Envelope

    {

        return new Envelope(

            from: new Address(address: 'jeffrey@example.com', name: 'Jeffrey Way'),

        );

    }

`

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
