### ISSUE TITLE
Pivot table name does not use a plural form

### ISSUE THREAD

**Issue by alecpl** [laravel/framework#51792]
### Laravel Version

10.48.12

### PHP Version

8.1.29

### Description

https://laravel.com/docs/10.x/eloquent#table-names says "By convention, the "snake case", plural name of the class will be used as the table name unless another name is explicitly specified. So, in this case, Eloquent will assume the Flight model stores records in the flights table, while an AirTrafficController model would store records in an air_traffic_controllers table"

It doesn't look like so for pivots:
```
class PackageSku extends \Illuminate\Database\Eloquent\Relations\Pivot
{
}

PackageSku::all();
```
Results in use of `package_sku` table, while it should be using `package_skus`.

### Steps To Reproduce

```
class PackageSku extends \Illuminate\Database\Eloquent\Relations\Pivot
{
}

PackageSku::all();
```

**Comment by alecpl** [comment]
I just found #30788. So, not a bug, but the documentation at https://laravel.com/docs/10.x/eloquent#table-names should probably mention that to limit confusion. This is unexpected behavior because Pivot extends Model.

**Comment by rodrigopedra** [comment]
Documentation refers to it, on the many-to-many section:

> To define this relationship, three database tables are needed: `users`, `roles`, and `role_user`. The `role_user` table is derived from the alphabetical order of the related model names and contains `user_id` and `role_id` columns. This table is used as an intermediate table linking the users and roles.

https://laravel.com/docs/10.x/eloquent-relationships#many-to-many-table-structure

**Comment by crynobone** [comment]
Thanks @rodrigopedra
