### ISSUE TITLE
php artisan doesn't like it when constants are in the destructor and you do Ctrl + D

### ISSUE THREAD

**Issue by terrafrost** [laravel/framework#51816]
### Laravel Version

10.48.12

### PHP Version

PHP 8.1.2-1ubuntu2.17

### Database Driver & Version

n/a

### Description

Say you have this class:

```php
<?php
namespace Terrafrost\Namespace;

class Demo
{
    public function __construct()
    {
        define('ZZZ', 999);
    }

    public function __destruct()
    {
        echo ZZZ . "\n";
    }
}
```
If I initialize that in `php artisan tinker` (eg. `$a = new Terrafrost\Namespace\Demo;`) and then do Ctrl + D, I get this exception:

```
PHP Fatal error:  Uncaught Error: Undefined constant "Terrafrost\Namespace\ZZZ" in /home/terrafrost/laravel/vendor/terrafrost/namespace/src/Demo.php:14
Stack trace:
#0 [internal function]: Terrafrost\Namespace\Demo->__destruct()
#1 {main}
  thrown in /home/terrafrost/laravel/vendor/terrafrost/namespace/src/Demo.php on line 14
```
If, however, I do `unset($a);` after initializing that class, and then do Ctrl + D, I get no such error. eg.

```
$a = new Terrafrost\Namespace\Demo;
unset($a);
(Ctrl + D)
```
The following code snippet shows that ZZZ is being defined in the root namespace:

```
$a = new Terrafrost\Namespace\Demo;
defined('ZZZ') ? 't' : 'f';
```

`print_r(get_defined_constants(true)['user']);` concurs. But if I then put `print_r(get_defined_constants(true)['user']);` into the `__destruct` method, before the `echo ZZZ . "\n";` and then do Ctrl + D, then, all of a sudden, `ZZZ` no longer shows up.

### Steps To Reproduce

```
composer require terrafrost/namespace:dev-main
php artisan tinker
$a = new Terrafrost\Namespace\Demo;
(Ctrl + D)
```

**Comment by NickSdot** [comment]
@terrafrost Not sure if this helps. Coincidentally, just last week someone smarter than me thaught me that coupling to the desctructor isn't a good idea because it potentially does weird stuff. Laravel Tinker is using [bobthecow/psysh](https://github.com/bobthecow/psysh) under the hood. Given how it works, this is maybe one of the situations where weird stuff happens.

I am not too sure about the inner workings of phpseclib. Must the disconnect happen on object destruction?
Or does it have time until the end of script execution? If the latter, you could consider switching to a shutdown function.

```php
final class Demo
{
    public function __construct()
    {
        register_shutdown_function($this->shutdown(...));
        define('ZZZ', 999);
    }

    public function shutdown()
    {
        echo ZZZ . "\n";
    }
}


```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
