### ISSUE TITLE
Unsupported mixin objects with dependencies

### ISSUE THREAD

**Issue by itsDavidSQ** [laravel/framework#51828]
### Laravel Version

11.4.0

### PHP Version

8.3.6

### Description

When creating a macro, we can pass any dependencies that we may need using the `use` keyword when defining the closure. For example, we could define the following macro in a Service Provider and it would work with no issues:
```php
$apiVersionResolver = $this->app->get(ApiVersionResolver::class);

Request::macro('apiVersion', function () use ($apiVersionResolver): string {
    return $apiVersionResolver->resolve($this);
});
```

However, there is no way to achieve the same result using a mixin. Trying to do so results in an exception:
```php
class RequestMixin
{
    public function __construct(
        private readonly ApiVersionResolver $apiVersionResolver
    ) {
    }

    public function apiVersion(): \Closure
    {
        $apiVersionResolver = $this->apiVersionResolver;

        return function () use ($apiVersionResolver): string {
            return $apiVersionResolver->resolve($this);
        };
    }
}

// In a Service Provider:
$apiVersionResolver = $this->app->get(ApiVersionResolver::class);
Request::mixin(new RequestMixin($apiVersionResolver));
```
Exception:
```
ArgumentCountError: Too few arguments to function App\Http\RequestMixin::__construct(), 0 passed and exactly 1 expected
```

The exception is thrown in [Illuminate\Support\Traits\Macroable:51](https://github.com/laravel/framework/blob/07e12d378ec0875cdcfe4272d120d56e2312f713/src/Illuminate/Macroable/Traits/Macroable.php#L51), when it invokes the `__constructor()` method.

I have tested and excluding `__constructor()` methods within `Macroable::mixin()` would solve the problem.

Please, correct me if I'm wrong, but I'm unable to think of a case where someone would want the constructor copied over. Even if defined in the mixin object, most macroable classes will define their own.

Happy to submit a PR if there is no opposition to it.

### Steps To Reproduce

Given a class:
```
class ApiVersionResolver {

    public function resolve(Request $request): string
    {
        return 'v2'; // Hard-coded for simplification.
    }
}
```

1. Define a mixin which depends on the above class:
```
class RequestMixin
{
    public function __construct(
        private readonly ApiVersionResolver $apiVersionResolver
    ) {
    }

    public function apiVersion(): \Closure
    {
        $apiVersionResolver = $this->apiVersionResolver;

        return function () use ($apiVersionResolver): string {
            return $apiVersionResolver->resolve($this);
        };
    }
}
```
2. Register the mixin in a Service Provider:
```
$apiVersionResolver = new ApiVersionResolver();
Illuminate\Http\Request::mixin(new RequestMixin($versionResolver));
```
3. Perform any action that loads the application, for example running an artisan command:
```
php artisan about
```

**Comment by driesvints** [comment]
Hi @itsDavidSQ. This atm seems more like a feature request to me than a bug. Feel free to attempt that PR to see if Taylor wants to accept it as a use case, thanks!
