### ISSUE TITLE
Misleading error message when using auth:sanctum middleware

### ISSUE THREAD

**Issue by Zefried** [laravel/framework#51834]
### Laravel Version

11

### PHP Version

8.2.4

### Description

When using the auth:sanctum middleware in Laravel, if a user tries to access a protected route without being authenticated, the middleware redirects to the login route instead of returning a clear error message indicating that the user is not authenticated.
Expected behavior:
When an unauthenticated user tries to access a protected route, the middleware should return a JSON response with a 401 status code and a clear error message, such as "Unauthenticated" or "Authentication required".
Requested fix:
Please update the auth:sanctum middleware to return a clear error message for unauthenticated users, rather than redirecting to the login route. This will make it easier for developers to handle authentication errors and provide a better user experience.

### Steps To Reproduce

Install a fresh instance of Laravel
Set up Sanctum for authentication
Define a protected route using the auth:sanctum middleware
Try to access the protected route without being authenticated
Do not create a login route (optional)
Use get method for api/test route without authenticated (optional)
Observe the error message and behavior

**Comment by driesvints** [comment]
We don't have plans to change this right now, sorry.

**Comment by Zefried** [comment]
> We don't have plans to change this right now, sorry.

that's strange but it's a small issue anyway, understandable.
