### ISSUE TITLE
The Laravel new command does not work when Herd is not installed

### ISSUE THREAD

**Issue by JangoCG** [laravel/framework#51857]
### Laravel Version

11

### PHP Version

8.3.8

### Description

I am on brand new Mac and I have installed PHP with Homebrew, Valet, Composer, and Xdebug, and they all work. I can even debug Laravel applications. However, I cannot generate new projects.

Running laravel new test fails with the following error:
```
In Process.php line 371:
                                                                       
  The command "'herd' 'tld' '-v'" failed.                              
                                                                       
  Working directory: /Users/cengiz                                     
                                                                       
  Error: proc_open(): posix_spawn() failed: No such file or directory 
```

When I install herd the laravel new command will work. But I dont want to install Herd, I prefer to use valet

Other people seem to have this issue too.See the following Thread on laracasts:
https://laracasts.com/discuss/channels/laravel/laravel-new-command-fails-with-the-command-herd-tld-v-failed?page=1&replyId=937665

### Steps To Reproduce

**Run the laravel new command without having herd installed on your machine**

**Comment by driesvints** [comment]
This has already been fixed in v5.8.2 of the installer: https://github.com/laravel/installer/releases/tag/v5.8.2

What version are you on? Also, you can always report installer issues to the installer repo directly.

**Comment by JangoCG** [comment]
@driesvints  Thank you. I was on 5.8.1. I upgraded to 5.8.3 and now it works!

And sorry about creating the issue in the wrong repo. I am new to Laravel and had no idea that the installer is a separate repository.

**Comment by driesvints** [comment]
@JangoCG don't worry about it 👍
