### ISSUE TITLE
Job gets stuck in pending when dependent model is deleted inside the handle method.

### ISSUE THREAD

**Issue by davemagro** [laravel/framework#51860]
### Laravel Version

11.0

### PHP Version

8.1

### Database Driver & Version

using mysql/mysql-server on docker

### Description

I am currently executing/dispatching the job on a controller method. 

Job is being executed by `php artisan queue:work` 

Works well when I try to manually load the model, so instead of having the job depend on the model, I instead pass the model ID to the job, and inside the job handler, I try to fetch the model using the given ID, then delete it, and the job dont get stuck in pending.

### Steps To Reproduce

```php

class DeleteSubUser implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     */
    public function __construct(
        private User $user
    ) {}
   public handle() {
      $this->user->delete();
      echo "Done";    // This still gets printed in the console where `php artisan queue:work` was executed. 
   }
}
```

**Comment by davemagro** [comment]
Ok, it seems like the issue is with telescope. It works fine when telescope is disabled.

telescope v5.0

**Comment by driesvints** [comment]
Gonna close this one then since it's related to Telescope. Thanks
