### ISSUE TITLE
SQLite queries generated by Eloquent with non existing columns in WHERE clause should generate an error/exception but don't

### ISSUE THREAD

**Issue by tasso85** [laravel/framework#51871]
### Laravel Version

11.11.1

### PHP Version

8.3.8

### Database Driver & Version

SQLite 3.37.2

### Description

When using SQLite as database for Laravel framework, queries are generated using double quotes for identifiers, which can have unexpected results when you query for non existing columns.

For example, an Eloquent query like this

```
Company::where("not_existing", "whatever");
```

gets converted to

```
select * from "companies" where "not_existing" = 'whatever';
```

The problem is that, as stated at [here](https://www.sqlite.org/quirks.html):

> [...] in an effort to be compatible with MySQL 3.x (which was one of the most widely used RDBMSes when SQLite was first being designed) **SQLite will also interpret a double-quotes string as string literal if it does not match any valid identifier**.

So, the above query, instead of generating an error as I would have expected, simply returns no result; similarly, a query like

```
select * from "companies" where "not_existing" = 'not_existing';
```

will return all rows from the table.

I do understand that this is not directly tied to Laravel framework itself, and that, from what I understand, it could be resolved by recompiling PHP with some specific flags; however, it seems that in the standard PHP versions you download from repository, those flags were not used.

Given the above, I think that the framework could/should give a mean to its users to work around this problem.

### Steps To Reproduce

1. Create a test table in a migration, for example

```
Schema::create("companies", function (Blueprint $table) {
	$table->id("id")->primary();
	$table->string("name");
	$table->timestamps();
});
```

2. Seed the database

```
DB::table('companies')->insert(['name' => 'test']);
```

3. Create the matching model

```
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model {
	...
}
```

4. Try this query in Artisan tinker

```
Company::where("not_existing", "whatever")->first();
```

It'll return `null` instead of generating an error/exception, whereas

```
Company::where("not_existing", "not_existing")->first();
```

will return the seeded record.

**Comment by driesvints** [comment]
Hi @tasso85. While I do emphasise with your issue I do believe this is more a feature/enhancement request than a bug. Like you indicated, this is standard SQLite behaviour and right now we don't have plans to deviate from that, sorry. You can always attempt a PR to change this behaviour but I think it's highly unlikely Taylor will merge that.
