### ISSUE TITLE
RequiredIf validator with multiple values fails validating 

### ISSUE THREAD

**Issue by alagoroChapela** [laravel/framework#51882]
### Laravel Version

11.11.1

### PHP Version

8.2.15

### Description

Hi!

I'm using livewire Rule attribute, but problem is with 'required_if' that is from laravel framework.

```
#[Rule(' required_if:isOldEnough,true| string | max:30')]
$property

```
$property is empty
When isOldEnough is false, required_if evaluates correctly to "not required" but the Rule validates false because of 'string'. The solution is `#[Rule('nullable | required_if:isOldEnough,true| string | max:30')]` but it should not be necessary saying it can be null if you say it isn't required ... 

Thanks.

### Steps To Reproduce

Rule for validation.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
