### ISSUE TITLE
`view()` is rendered when passed as component attribute

### ISSUE THREAD

**Issue by ju5t** [laravel/framework#51889]
### Laravel Version

v11.11.1

### PHP Version

8.2

### Description

The following does not pass the view as a View class, but renders it to HTML.

```blade
<x-test :content="view('content')" />
```

As it turns out, this only happens for `Renderable` [classes](https://github.com/laravel/framework/blob/11.x/src/Illuminate/View/View.php#L220). This has been in Laravel since the first commit.

This feels inconsistent as other 'renderable' classes are not converted, such as `Htmlable`'s. As it's part of the first commit I cannot find why this was added/necessary but making changes to will likely be breaking.

> Sidenote: this happened to me in Filament where you can't use slots.

### Steps To Reproduce

See: https://github.com/ju5t/view-prop
Commit: https://github.com/ju5t/view-prop/commit/a60d9de4646944306f4e462f51fed8a0fac3c11b

**Comment by driesvints** [comment]
Hi @ju5t. I want to thank you for the clear issue and repro repository. Since this has been something that's been in core for so long I don't think we can consider this a bug but working as intended. Please also note that Htmlable and Renderable are two very different interfaces.
