### ISSUE TITLE
Error with AJAX request

### ISSUE THREAD

**Issue by Leksizz** [laravel/framework#51898]
### Laravel Version

11

### PHP Version

8.2

### Description

! I submit the form via AJAX, the data is added to the database, after which the site breaks with errors:
![image](https://github.com/laravel/framework/assets/129582133/00939e06-13d6-4672-b340-b81772cb64fe)

html: 

@extends('layouts/main')
@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<script src="{{ asset('assets/js/form.js') }}"></script>
<div class="container my-5">
<pclass="text-center my-5">Новый пользователь:</h1>
<div class="mx-auto col-sm-9">
<form action="/api/v1/users/store" method="POST">
@csrf
<div class="row g-3">
<div class="col-md-12">
<label for="name" class="form-label"><strong>Имя:</strong></label>
<input type="text" class="form-control" id="name" name="name" placeholder="Имя" required>
</div>
<div class="col-md-12">
<label for="phone" class="form-label"><strong>Телефон:</strong></label>
<input type="text" class="form-control" id="phone" name="phone" placeholder="Телефон" required>
</div>
<div class="col-md-12">
<label for="email" class="form-label"><strong>Электронная почта:</strong></label>
<input type="email" class="form-control" id="email" name="email" placeholder="Электронная почта"
required>
</div>
</div>
<button type="submit" class="btn btn-secondary mt-3">Отправить</button>
<p class="text-danger text-center" id="error"></p>
</form>
</div>
</div>
@endsection

js

$(document).ready(function () {
$('form').submit(function (event) {
let json;
event.preventDefault();
$.ajax({
type: $(this).attr('method'),
url: $(this).attr('action'),
headers: {
'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
},
data: new FormData(this),
contentType: false,
cache: false,
processData: false,
success: function (result) {
json = jQuery.parseJSON(result);
console.log(json)
if (json.status === 'error') {
document.getElementById('error').innerText = json.message
}
if (json.href) {
window.location.href = '/' + json.href;
}
},
});
});
});

laravel   

public function store(UserRequest $request): UserResource
{
$validatedData = $request->validated();
$userDTO = UserDTO::from($validatedData);

$created_user = $this->userService->createUser($userDTO);
return new UserResource($created_user);
}

### Steps To Reproduce

https://github.com/Leksizz/issue

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
