### ISSUE TITLE
current transaction is aborted, commands ignored until end of transaction block on listener when implement ShoudlQueue

### ISSUE THREAD

**Issue by iqbalatma** [laravel/framework#51917]
### Laravel Version

11.12.0

### PHP Version

8.3.8

### Database Driver & Version

psql (PostgreSQL) 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

### Description

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block

### Steps To Reproduce

this is the controller
```
class IqbalController extends Controller
{
    public function index()
    {
        DB::beginTransaction();
        $user = User::query()->create([
            "name" => "Iqbal",
            "email" => fake()->safeEmail,
            "password" => Hash::make('iqbal123')
        ]);
        DB::commit();
        TestingEvent::dispatch($user);

        return response()->json(["status" => "success"]);
    }
}
```

this is the event
```
class TestingEvent implements ShouldDispatchAfterCommit
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     */
    public function __construct(public User $user)
    {
        //
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return array<int, \Illuminate\Broadcasting\Channel>
     */
    public function broadcastOn(): array
    {
        return [
            new PrivateChannel('channel-name'),
        ];
    }
}
```

this is the listener
```
class TestingListener implements ShouldQueue, ShouldHandleEventsAfterCommit
{
    /**
     * Create the event listener.
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     */
    public function handle(TestingEvent $event): void
    {
        DB::beginTransaction();
        Bill::query()->create([
            "total" => 10
        ]);
        DB::commit();
    }
}
```

when i set QUEUE_CONNECTION=sync
and implement ShouldQueue on listener, i got error current transaction is aborted, commands ignored until end of transaction block.
i expecting Not null violation error because when i create bill it required column number. 
when i remove ShouldQueue error show as i expected.
when i remove    public function __construct(public User $user) in Event error show as i expected.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by zackAJ** [comment]
@iqbalatma any luck with this ?
