### ISSUE TITLE
sebastian/comparator should be an explicit dependency

### ISSUE THREAD

**Issue by kennaar** [laravel/framework#51915]
### Laravel Version

9.52.16

### PHP Version

8.1.28

### Description

I'm running phpunit 9.6 using the PHAR build. When calliing `$response->assertJson()` I see the following error:
 ```
Tests\Feature\Api\Users\UserProfileControllerTest::invoke_withRequest_shouldReturnNewAuthorizedUserDetailsShouldReturnReferenceIdValue
Error: Class "SebastianBergmann\Comparator\ComparisonFailure" not found

/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/Constraints/ArraySubset.php:78
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/Assert.php:40
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/AssertableJsonString.php:295
/var/www/html/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:641
/var/www/html/tests/Feature/Api/Users/UserProfileControllerTest.php:110
```

The namespace for the class inside the phar is `PHPUnitPHAR\SebastianBergmann\Comparator\ComparisonFailure`. So yes the problem is obvious, namespace doesn't match. 

**Solution:**
`illuminate/testing` should not rely on transient dependencies. These dependencies should be required explicitly.

This issue seems to be related: https://github.com/laravel/framework/issues/36393

### Steps To Reproduce

- Run phpunit using the PHAR build
- Create a phpunit test case and run it
```php
<?php

class FooTest extends Illuminate\Foundation\Testing\TestCase
{
    public function testBar(): void
    {
        $response = $this->get('/');

        $response->assertJson([]);
    }
}
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
