### ISSUE TITLE
attempts() method does not exist on FakeJob

### ISSUE THREAD

**Issue by JamesFreeman** [laravel/framework#51929]
### Laravel Version

11.12.0

### PHP Version

8.2.20

### Database Driver & Version

N/A

### Description

I need to be able to test a job that will be put back onto the queue with different delays based on how many times it has not been completed - after x times, we will just run the job. I thought the best course of action would be to use the new `withFakeQueueInteractions` helper - but i'm getting the following error:

Error:
```bash
Error: Call to undefined method Illuminate\Queue\Jobs\FakeJob::attempts()
/Users/xxx/Sites/xxx/vendor/laravel/framework/src/Illuminate/Queue/InteractsWithQueue.php:32
```

### Steps To Reproduce

Job Code:
```php
public function handle(): void
{
    if ($this->payment->paymentRequest->tokenize_payment && is_null($this->payment->token_id) && $this->attempts() <= 3) {
        $this->release($this->delays[$this->attempts()]);

        return;
    }

    $this->send();
}
```

Test Code:
```php
public function test_that_it_will_release_job_back_onto_queue_if_is_token_payment_and_its_not_there()
{
    Bus::fake();

    $payment = $this->createPaymentWithPostback();

    $payment->update(['token_id' => null]);
    $payment->paymentRequest->update(['tokenize_payment' => true]);

    $job = (new PaymentVerified($payment))->withFakeQueueInteractions();

    $job->handle();

    $this->assertWebhookNotCreated();
    $job->assertReleased(1);
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
