### ISSUE TITLE
Incorrect responses in Str `after` methods.

### ISSUE THREAD

**Issue by wffranco** [laravel/framework#51954]
### Laravel Version

11.13.0

### PHP Version

8.3.7

### Description

The `after` functions are returning unexpected values.
If the searched string is not matched, they return the original string.
In my opinion, if we search after a string but is not found, we should receive an empty string.

### Steps To Reproduce

```php
\Str::after('api/v1/test', 'api/v1/'); // returns 'test' ✅
\Str::afterLast('api/v1/test', 'api/v1/'); // returns 'test' ✅
\Str::after('api/test', 'api/v1/'); // returns 'api/test' ❌
\Str::afterLast('api/test', 'api/v1/'); // returns 'api/test' ❌

// getting resource and key from a route
$path = \Str::of('api/v1/resource/key/whatever')->after('api/v1/'); // store 'resource/key/whatever' ✅
$resource = $path->before('/'); // store 'resource' ✅
$key = $path->after("$resource/")->before('/'); // store 'key' ✅

// getting resource and key from a malformed route
$base = \Str::of('api/resource/key/whatever')->after('api/v1/'); // store 'api/resource/key/whatever' ❌
$resource = $base->before('/'); // store 'api'  ❌
$key = $base->after("$resource/")->before('/'); // store 'resource'  ❌
// The right answer should be empty $resource and $key, because is not a valid route.
```

**Comment by calebdw** [comment]
> If the searched string is not matched, they return the original string.

I'm fairly certain this is intentional so you can continue to fluently chain method calls---I don't want to have to check if the string contains the needle before calling the `after` method

**Comment by driesvints** [comment]
Thanks @calebdw. This is indeed intentional.
