### ISSUE TITLE
Passing value to class castable attribute

### ISSUE THREAD

**Issue by BenjaminMINK** [laravel/framework#51950]
### Laravel Version

10.x

### PHP Version

8.3

### Description

Hello,

I would like to report that seems to me an issue when passing value to a class castable attribute.

Let's say a model has an Enum Collection attribute `countries`:

```php
$casts = ['countries' => AsEnumCollection::class.':'.Country::class];
```

After fetching the model, we can have something like : `countries: ['FRA', 'USA']`

But if we want to manually use the `castAttribute` method with a custom value the result will always be the same as fetched before:

```php
$value = ['FRA', 'USA', 'JPN'];
$result = $model->castAttribute('countries', $value);

// $result: ['FRA', 'USA']
```

Shouldn't we get our passing value as a result?

In the https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Casts/AsEnumCollection.php#L31, the `$value` argument is never used, shouldn't be used if passed to the method? Is it by design? 
The same thing can be observed on the other casting classes.

Thank you!

### Steps To Reproduce

Pass a custom value to model's method `castAttribute`, result will always be the data retrieved before:

```php
$value = ['FRA', 'USA', 'JPN'];
$result = $model->castAttribute('countries', $value);

// $result: ['FRA', 'USA']
```

**Comment by BenjaminMINK** [comment]
Sorry if I'm unclear, what I would expect by passing a custom value is that the castable class can return correct casting for any passed value

**Comment by driesvints** [comment]
Hi @BenjaminMINK. I don't think this works like in your example. `AsEnumCollection` is currently documented to work like follow: https://laravel.com/docs/11.x/eloquent-mutators#casting-arrays-of-enums

Can you try that and let me know if it works?

**Comment by BenjaminMINK** [comment]
Hello,

Thank you for your answer, but what I've showed in my example is for Laravel 10.x.

I've also tested with the new syntax in Laravel 11.x, the same "issue" happens, in fact, the casting classes haven't changed since 10.x, so the same thing happens.

**Comment by BenjaminMINK** [comment]
Based on AsEnumCollection class:

Now we have on the get method:

```php
$data = Json::decode($attributes[$key]);

if (! is_array($data)) {
    return;
}

$enumClass = $this->arguments[0];

return (new Collection($data))->map(function ($value) use ($enumClass) {
    return is_subclass_of($enumClass, BackedEnum::class)
        ? $enumClass::from($value)
        : constant($enumClass.'::'.$value);
});
```

We might be expect something like this when we pass the `$value` argument:

```php
$data = Json::decode($value ?? $attributes[$key]);

if (! is_array($data)) {
    return;
}

$enumClass = $this->arguments[0];

return (new Collection($data))->map(function ($value) use ($enumClass) {
    return is_subclass_of($enumClass, BackedEnum::class)
        ? $enumClass::from($value)
        : constant($enumClass.'::'.$value);
});
```

**Comment by Lakshan-Madushanka** [comment]
[castAttrbute() ](https://github.com/laravel/framework/blob/1225a2ff8c8eb85240ebd8b1eb5b7442eea335c5/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L790) is an internal method since its visibility is protected. However, I'm curious how you managed to call that method from outside without an exception being thrown.

**Comment by driesvints** [comment]
@Lakshan-Madushanka is correct. It doesn't seem we support this usage sorry.
