### ISSUE TITLE
Double counting issue in rate limiter middleware

### ISSUE THREAD

**Issue by marcovo** [laravel/framework#51967]
### Laravel Version

v11.13.0

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

When using multiple limits for one rate limiter by the same key, requests are double-counted.

### Steps To Reproduce

Define a rate limiter like so:
```
        RateLimiter::for('some_api_point', function (Request $request) {
            return [
                Limit::perMinute(5)->by($request->ip()),
                Limit::perDay(50)->by($request->ip()),
            ];
        });
```

The underlying cache counts the requests by the same key, causing the third request to already return a 429 response instead of the fifth response within a minute. Leaving out the `perDay` rule, the 429 response appears on the fifth response as expected.

Expected behaviour: The given rate limiter should return the 429 response at exactly the fifth (and 50th) request.

Possible workaround:
```
            return [
                Limit::perMinute(5)->by($request->ip() . '_perMinute'),
                Limit::perDay(50)->by($request->ip() . '_perDay'),
            ];
```

**Comment by driesvints** [comment]
Using the different name for each limit is the recommended workaround for this.
