### ISSUE TITLE
findMany unexpectedly deduplicates

### ISSUE THREAD

**Issue by Sjord** [laravel/framework#51973]
### Laravel Version

v11.8.0-57-g83e28d065b

### PHP Version

PHP 8.3.8 (cli)

### Description

`findMany([1, 1])` returns one object instead of two. This is not obvious from the [documentation](https://github.com/laravel/framework/blob/83e28d065b7bc53f3e53a5c188806844eee30161/src/Illuminate/Database/Eloquent/Builder.php#L460):

> Find multiple models by their primary keys.

`findMany([1, 1])` creates a query with 'WHERE id IN (1, 1)`, and that returns one row. I think the best solution is to change the documentation. Either by explicitly describing that it deduplicates, or implicitly, e.g. "Finds all models whose primary keys are contained in the given array."

### Steps To Reproduce

Use findMany to retrieve the same object multiple times:

```
var_dump(count(findMany([1, 1])));
```

**Comment by driesvints** [comment]
I'm not sure what you expect here? I feel like all of this is very obvious? You're of course free to attempt a PR to the docs 👍
