### ISSUE TITLE
Http::globalRequestMiddleware not reflected in RequestSending event

### ISSUE THREAD

**Issue by sky93** [laravel/framework#51980]
### Laravel Version

11.13.0

### PHP Version

8.3.6

### Description

Hello. I change user agent in `Http::globalRequestMiddleware` like below according to [this](https://laravel.com/docs/11.x/http-client#global-middleware) link:
```php
Http::globalRequestMiddleware(fn ($request) => $request->withHeader(
    'User-Agent', 'Example Application/1.0'
));
```

When I use `RequestSending` event like the example in [document](https://laravel.com/docs/11.x/http-client#events) I get another user agent:

```php
public function LogHttpClientRequests(RequestSending $event)
{
    Log::info('Request Sending Headers:', $event->request->headers());
}
```

I get `GuzzleHttp/7` in log file:
```
local.INFO: Request Sending Headers: {"User-Agent":["GuzzleHttp/7"]} 
```

The expected User-Agent is Example Application/1.0. This happens with any modifications in header. The request that is actually get sent has the correct User Agent but the log shows invalid output. How can I get this fixed?

### Steps To Reproduce

1- Create `app/Providers/HttpClientServiceProvider.php`:
```php
public function register(): void
{
}

public function boot(): void
{
    Http::globalRequestMiddleware(fn ($request) => $request->withHeader(
        'User-Agent',
        'Example Application/1.0'
    ));
}
```

2- Register event in `app/Providers/EventServiceProvider.php`:
```php
protected $listen = [
    RequestSending::class => [
        LogHttpClientRequests::class,
    ],
    ResponseReceived::class => [
        LogHttpClientRequests::class,
    ],
    ConnectionFailed::class => [
        LogHttpClientRequests::class,
    ],
];
```

3- Create `app/Listeners/LogHttpClientRequests.php`:
```php
public function LogHttpClientRequests(RequestSending $event): void
{
    Log::info('Request Sending Headers:', $event->request->headers());
}
```

4- Run `Http::get('https://example.com')` in tinker.

**Comment by driesvints** [comment]
I managed to reproduce this. Not sure what's going on but would appreciate any insights here.

**Comment by sethsandaru** [comment]
> I managed to reproduce this. Not sure what's going on but would appreciate any insights here.

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Http/Client/PendingRequest.php#L1260-L1264

So we dispatch `RequestSending` event before invoking the global middleware(s). That would be the reason why the custom user-agent wasn't presented in the `RequestSending` event

**Comment by driesvints** [comment]
I have a feeling this has come up before and that we labeled it as the expected behaviour. But unsure which issue that was. We might have to adjust the docs a little bit here.

**Comment by eduance** [comment]
@driesvints 

This is quite funny, we add the middleware to the Guzzle stack around June 24th, 2020. We then receive a first commit on Jan 25th, 2022 (63cb622) that solves a similar issue, the middleware is not being added before the request is started. This commit moves the `$stack->push($this->buildStubHandler()) underneath the middleware. 

The reason for this is that you first want your middleware to be on each subsequent request. We receive an exact similar commit last year (f03e652), this moves the `$stack->push($this->buildRecorderHandler()); underneath the middleware.

I'm now proud to announce, that after 3 years hereby I'll be moving the last line so whenever we send a request, we always have the middleware hooked. 😆

**Comment by eduance** [comment]
@driesvints This should be solved now.

**Comment by driesvints** [comment]
Thanks @eduance
