### ISSUE TITLE
Duplicate migrations files if we are publishing vendors

### ISSUE THREAD

**Issue by dimkiriakos** [laravel/framework#52008]
### Laravel Version

11

### PHP Version

8.2, 8.3

### Database Driver & Version

sqlite

### Description

If I'm installing the sanctum and I'm publishing the vendors in Laravel 11 it duplicates the personal access tokens file. 
here is a video recording comparing laravel 11 and laravel 10 for the same thing https://youtu.be/OkZvD2fjDU4

### Steps To Reproduce

php artisan vendor:publish

**Comment by driesvints** [comment]
You're publishing this twice. A new timestamp is generated for the migration when doing this hence why they appear twice. You don't need to publish these twice. L10 had this migration already in its skeleton but L11 has it removed and made it optional.

**Comment by dimkiriakos** [comment]
> You're publishing this twice. A new timestamp is generated for the migration when doing this hence why they appear twice. You don't need to publish these twice. L10 had this migration already in its skeleton but L11 has it removed and made it optional.

I see, it needs skills to fix this problem from the core. May you don't have it so you did well that you closed the issue..... In laravel 10 by lack, this issue didn't exist....
