### ISSUE TITLE
Laravel 10 - Symfony Mailer Issue - shouldSendMessage validation always returning false

### ISSUE THREAD

**Issue by ekocahyonugroho** [laravel/framework#52025]
### Laravel Version

10.x.x

### PHP Version

8.1.29

### Description

I have always failed to send verification emails using Symfony. I should change Mailer.php file to below code :

```
// if ($this->shouldSendMessage($symfonyMessage, $data)) { <== I should comment this validation
           
            $symfonySentMessage = $this->sendSymfonyMessage($symfonyMessage);

            if ($symfonySentMessage) {
                $sentMessage = new SentMessage($symfonySentMessage);

                $this->dispatchSentEvent($sentMessage, $data);

                return $sentMessage;
            }
        // }
```
        
It turns out shouldSendMessage() always returns a false condition.

### Steps To Reproduce

call this function sendEmailVerificationNotification();

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
