### ISSUE TITLE
wrong :value in validation rules 'gt', 'gte', 'lt', 'lte' for type numeric

### ISSUE THREAD

**Issue by azgooon** [laravel/framework#52036]
### Laravel Version

10.48.15

### PHP Version

8.3.4

### Description

I came across what I think is the bug and would appreciate it if someone could have a second opinion.

In the "steps to reproduce" I have included a snippet which when executed I would have expected to return 2 errors both referencing the `currency` field, stating that the `currency` field must be an array (this is just to demonstration purposes). Instead, there are 4 errors 2 about the array and 2 about the `amount` field informing that the `amount` field should be greater than 2. 

am I missing something or is it not desirable behavior?

Thanks,
Tom.

### Steps To Reproduce

        $data = [
            [
                'amount' => 10,
                'currency' => 'GBP',
            ],
            [
                'amount' => 20,
                'currency' => 'GBP',
            ],
        ];

        $rules = [
            '*.amount' => [
                'required',
                'numeric',
                'gt:0',
            ],
            '*.currency' => [
                'array',
            ],
        ];

        $validator = Validator::make($data, $rules);

        dd($validator->getMessageBag()->toArray());

**Comment by prateekgoyal261** [comment]
After further testing your issue, it appears that gt:0 is not treating 0 as a value but as a key of the array. For instance, if you add three items in the first row and two items in the second row, gt:0 will return items greater than 3, and gt:1 will return items greater than 2.

Similarly, if you add more array items, gt:3 will behave the same if the array has more than three rows.

Here is an example of the data:

$data = [
    [
        'amount' => 10,
        'currency' => 'GBP',
        'country' => 'UK',
    ],
    [
        'amount' => 20,
        'currency' => 'GBP',
    ],
];

**Comment by azgooon** [comment]
Is it how it should work? I am not at the laptop right now but if I remember correctly, if we replace gt:0 with gt:10 then an actual number is used so I still think that the behaviour is inconsistent, no?

**Comment by Lakshan-Madushanka** [comment]
@prateekgoyal261 No it doesn't treat is as a key it should behave accordingly [size rule](https://laravel.com/docs/11.x/validation#rule-size). Though this is interesting. The first picture that came to my mind was similar to @azgooon's, but I knew that the gt, gte, etc. rules behave according to the [size rule](https://laravel.com/docs/11.x/validation#rule-size). The size rule varies depending on the type. For an array, size corresponds to the count of the array. That rule has been applied to your amount field, treating it as an array type but in your case it should be treated as integer which is quite odd.

Make sure you pass the amount as integer perhaps you may have passed it as an array.

**Comment by azgooon** [comment]
@Lakshan-Madushanka as per example, the amount is definitely passed as int.

**Comment by driesvints** [comment]
So this is quite the gotcha but @prateekgoyal261. It's because you're using the wildcard as the root of the array causing the value of `gt` to reference the array key instead of representing a size. The gt, gte, size, etc rules **first** check for a key presence in the root array which will match the `0` or `1` keys of the given array with two data entries. **Then** it'll check for a size. The solution to this problem is to always use a root key instead of using `*` as the root of the array:

```php
$data = [
    "values" => [
        [
            "amount" => 10,
            "currency" => "GBP"
        ],
        [
            "amount" => 20,
            "currency" => "GBP"
        ]
    ]
];

$rules = [
    "values.*.amount" => ["required", "numeric", "gt:0"],
    "values.*.currency" => ["array"]
];

$validator = Validator::make($data, $rules);

dd($validator->getMessageBag()->toArray());
```

**Comment by azgooon** [comment]
Thanks @driesvints, that makes sense.
