### ISSUE TITLE
Fresh install Laravel, user name added ->collation('utf8mb4_bin') cause sqlite error

### ISSUE THREAD

**Issue by paul38467** [laravel/framework#52045]
### Laravel Version

11.14.0

### PHP Version

8.3.1

### Description

After fresh installed Laravel v11.14.0 via Laravel installer

Added `->collation('utf8mb4_bin')` to the `name` column in the users table

run `php artisan test` cause all default test sqlite error

### Steps To Reproduce

1. Fresh install via Laravel installer
```
Would you like to install a starter kit?
> Laravel Breeze

Which Breeze stack would you like to install?
> Livewire (Volt Class API) with Alpine

Would you like dark mode support?
> Yes

Which testing framework do you prefer?
> Pest

Would you like to initialize a Git repository?
> No

Which database will your application use?
> sqlite

Default database updated. Would you like to run the default database migrations?
> No
```

2. Run command
```
php artisan migrate
npm install
npm run dev
```

3. Modify files

database\migrations\0001_01_01_000000_create_users_table.php
```
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name')->collation('utf8mb4_bin')->unique();
```
database\factories\UserFactory.php
```
    public function definition(): array
    {
        return [
            'name' => fake()->unique()->name(),
```
resources\views\livewire\pages\auth\register.blade.php
```
    public function register(): void
    {
        $validated = $this->validate([
            'name' => ['required', 'string', 'max:255', 'unique:'.User::class],
```
phpunit.xml
```
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
```
4. Run test
```
php artisan test
```

5. All default Breeze Test fail with same error
```
   FAILED  Tests\Feature\Auth\AuthenticationTest > login screen can be rendered                                                       QueryException   
  SQLSTATE[HY000]: General error: 1 no such collation sequence: utf8mb4_bin (Connection: sqlite, SQL: create table "users" ("id" integer primary key autoincrement not null, "name" varchar not null collate 'utf8mb4_bin', "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:565
    561▕             if ($this->pretending()) {
    562▕                 return true;
    563▕             }
    564▕
  ➜ 565▕             $statement = $this->getPdo()->prepare($query);
    566▕
    567▕             $this->bindValues($statement, $this->prepareBindings($bindings));
    568▕
    569▕             $this->recordsHaveBeenModified();

      +8 vendor frames 
  9   database/migrations/0001_01_01_000000_create_users_table.php:14
```
6. Seed 1000 users with `->collation('utf8mb4_bin')->unique()` in MySql is working good without error

**Comment by crynobone** [comment]
> Added ->collation('utf8mb4_bin') to the name column in the users table

Did you manually add this or you claiming Laravel Installer add this to your migrations?

**Comment by paul38467** [comment]
@crynobone I'm manually added `->collation('utf8mb4_bin')` to the users.name column

running test use sqlite memory is no error in my other Laravel10 project with `->collation('utf8mb4_bin')`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by paul38467** [comment]
In my Homestead has Laravel 10 and Laravel 11 project

with use `$table->string('name')->collation('utf8mb4_bin')->unique();` on Sqlite
Laravel 10 no error
Laravel 11 has error

so i go to check the Laravel Doc
https://laravel.com/docs/10.x/database#introduction (use SQLite 3.8.8+)
https://laravel.com/docs/11.x/database#introduction (use SQLite 3.35.0+)

and then i go to check Sqlite release note, and there has this https://www.sqlite.org/datatype3.html#collation
i guess in old Sqlite version it will ignore all custom collation, but in new Sqlite version it will throw an error if the collation not in the list below
```
BINARY
NOCASE
RTRIM
```

may be Laravel use new Sqlite version also need to update core code?

i changed the migration in the Laravel 11 project, is no error now
```
            if (env('DB_CONNECTION') == 'mysql')
            {
                $table->string('name')->collation('utf8mb4_bin')->unique();
            }
            else if (env('DB_CONNECTION') == 'sqlite')
            {
                $table->binary('name')->unique();
            }
```
