### ISSUE TITLE
Weird Error Message When Internal Server Error.

### ISSUE THREAD

**Issue by ElsevarAsadov** [laravel/framework#52046]
### Laravel Version

11.9

### PHP Version

8.2

### Database Driver & Version

MariaDB

### Description

My app doesn't have .env file and ofc laravel complains but laravel returns two same message.

![Screenshot_2024-07-07_05-26-15](https://github.com/laravel/framework/assets/125838640/53ff9411-77ac-418a-8b8c-d2c7aeef7b85)

This is xdebug result

![Screenshot_2024-07-07_05-25-43](https://github.com/laravel/framework/assets/125838640/50789a8e-6951-420e-b350-72cfe6a9e163)

i changed **content** from response object and that content showed in key section of response.

I think first {"message" : "Server Error"} is key and other is value 

### Steps To Reproduce

just having no .env file you can reproduce I think

**Comment by driesvints** [comment]
You need a .env file to run a Laravel app.
