### ISSUE TITLE
RedirectIfAuthenticated::redirectUsing callback should get guard as a parameter

### ISSUE THREAD

**Issue by itxshakil** [laravel/framework#52049]
### Laravel Version

11.14.0

### PHP Version

8.3

### Database Driver & Version

sqlite

### Description

**RedirectIfAuthenticated::redirectUsing callback should get guard as a parameter so, we can redirect according to guard.**

Currently, It only gets $request as the parameter, but I think it should also get guard as a parameter, It would allow handling cases according to guard.

### Steps To Reproduce

- Install Laravel
- Add redirectUsing to AppServiceProvider boot method
```
public function boot(): void
   {
       RedirectIfAuthenticated::redirectUsing(function($request){
           // TODO: Redirect according to guard
       });
   }
```

**Comment by driesvints** [comment]
This seems like a feature request. Feel free to attempt a PR 👍

**Comment by faraweilyas** [comment]
You can get your guard using `Auth::guard()`
