### ISSUE TITLE
using php Named parameter in routes 

### ISSUE THREAD

**Issue by muhsenmaqsudi** [laravel/framework#52061]
### Laravel Version

11.6.0

### PHP Version

8.3.9

### Description

When using php 8 named parameters in Route facade in our routing the bug appears and our routing config is not working as expected.

### Steps To Reproduce

The first isssue is when your are using a middleware static method call on your Route facade

![Screenshot from 2024-07-09 10-28-29](https://github.com/laravel/framework/assets/15028457/8e2b6dee-e2ce-47eb-b44d-98da761174c5)

and this is the produced bug. 

![Screenshot from 2024-07-09 10-29-10](https://github.com/laravel/framework/assets/15028457/252802dd-0370-444c-a6eb-b13875664d3b)

second one is when you are using other static methods like prefix & also the chained method calls like as

![Screenshot from 2024-07-09 10-26-57](https://github.com/laravel/framework/assets/15028457/e2c441ec-6eee-4b8d-8d02-d8f498790026)

and this is the second produced bug. route prefix and naming is replaced by 1 instead of app and application

![Screenshot from 2024-07-09 10-28-42](https://github.com/laravel/framework/assets/15028457/3d26298a-c6bc-4cee-9e07-577e7a43bf51)

**Comment by driesvints** [comment]
Seems you sent in a PR so let's see how it goes. Thanks
