### ISSUE TITLE
Once function runs repeatedly if cached value is null

### ISSUE THREAD

**Issue by AEM5299** [laravel/framework#52060]
### Laravel Version

11.8.0

### PHP Version

8.2

### Description

The [once](https://laravel.com/docs/11.x/helpers#method-once) function does not use cached value when it's `null`. This is because of the use of `isset` [here](https://github.com/laravel/framework/blob/0e9053da9d709c544200260cc0be5e223ea8ff93/src/Illuminate/Support/Once.php#L60).

If you run the function provided below 2 times, the callback will run twice. I would expect it to only once. I can open a fix PR if you can confirm this is not intended behaviour.

### Steps To Reproduce

```php
public function calculate()
{
    return once(function () {
        echo 'once';

        return null;
    });
}
```

**Comment by rodrigopedra** [comment]
I added this sample console command to a newly created Laravel project:

```php
<?php // ./routes/console.php

use Illuminate\Support\Facades\Artisan;

Artisan::command('app:test', function () {
    $foo = new class {
        public function calculate()
        {
            return once(function () {
                echo 'once';

                return null;
            });
        }
    };

    $foo->calculate();
});
```

And ran these commands:

```bash
$ php artisan --version
Laravel Framework 11.14.0

$ php artisan cache:clear

   INFO  Application cache cleared successfully.  


$ php artisan app:test
once
```

Can you provide additional information on how to reproduce it?

On the linked source code, although I think using `array_key_exists()` instead of `isset()` would allow caching of `null` values, there is nowhere where the callback would be called twice?

As you are using Laravel 11.8.0 instead of 11.14.0, would you care to update your project and check if the issue persists?

**Comment by AEM5299** [comment]
```php
<?php // ./routes/console.php

use Illuminate\Support\Facades\Artisan;

Artisan::command('app:test', function () {
    $foo = new class {
        public function calculate()
        {
            return once(function () {
                echo 'once';

                return null;
            });
        }
    };

    $foo->calculate();
    $foo->calculate();
});
```

Running the above will echo 'once' twice, where it should have cached the result and not run the callback a second time.

Same bug still exists in Laravel v11.14.0

**Comment by rodrigopedra** [comment]
Ah ok, now I see it, thanks for clarifying =)

**Comment by rodrigopedra** [comment]
I guess it is safe to send a PR, this doesn't seem like intentional behavior by any means. Specially if a given callback runs a costly operation.

I have it working as expected with these changes, just in case:

```php
public function value(Onceable $onceable)
{
    if (! static::$enabled) {
        return call_user_func($onceable->callable);
    }

    $object = $onceable->object ?: $this;

    $hash = $onceable->hash;

    if (! isset($this->values[$object])) {
        $this->values[$object] = [];
    }

    if (array_key_exists($hash, $this->values[$object])) {
        return $this->values[$object][$hash];
    }

    return $this->values[$object][$hash] = call_user_func($onceable->callable);
}
```

**Comment by driesvints** [comment]
Thanks. I'm not 100% sure if the `null` value return was intended to be cached. Feel free to attempt that PR 👍
