### ISSUE TITLE
Passing $attributes to component slot does not work

### ISSUE THREAD

**Issue by KhizarWahabKhan** [laravel/framework#52082]
### Laravel Version

11

### PHP Version

8.3.1

### Database Driver & Version

Mysql

### Description

Component slots can accept attributes but throws the following error when when passed all attributes through $attribute variable:
Illuminate\View\ComponentSlot::withAttributes(): Argument #1 ($attributes) must be of type array, null given,

### Steps To Reproduce

This works when attributes are given manually the <x-title:slot>:
```
<x-alert {{ $attributes->twMerge('relative w-full rounded-lg border bg-white p-4 [&>svg]:absolute [&>svg]:text-foreground [&>svg]:left-4 [&>svg]:top-4 [&>svg+div]:translate-y-[-3px] [&:has(svg)]:pl-11 text-neutral-900') }}>
    @if ($title && !$title->isEmpty())
        <x-slot:title class="mb-1 font-medium leading-none tracking-tight">{{ $title }}</x-slot:title>
    @endif
</x-alert>
```

But this does not work, here the attribute bag is passed to the <x-slot:title> with default classes. It works on the main component x-alert but does not work on the slot:
```
<x-alert {{ $attributes->twMerge('relative w-full rounded-lg border bg-white p-4 [&>svg]:absolute [&>svg]:text-foreground [&>svg]:left-4 [&>svg]:top-4 [&>svg+div]:translate-y-[-3px] [&:has(svg)]:pl-11 text-neutral-900') }}>
    @if ($title && !$title->isEmpty())
        <x-slot:title {{ $title->attributes->twMerge('mb-1 font-medium leading-none tracking-tight') }}>{{ $title }}</x-slot:title>
    @endif
</x-alert>
```

**Comment by lmottasin** [comment]
Assalamu Alaikum Brother @KhizarWahabKhan,

I hope you're doing well. Could you please create a new Laravel project and reproduce the issue you're facing with some demo component slots? Once you have done this, kindly share the GitHub repository with us so we can focus on solving the error without needing to repeat these steps.

Thank you, and I look forward to your cooperation.

**Comment by lmottasin** [comment]
@KhizarWahabKhan see this issue there is a solution and why is it like this answer is https://github.com/laravel/framework/issues/34313#issuecomment-691551759

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by KhizarWahabKhan** [comment]
Ok i will check the links. Thanks @lmottasin and @crynobone.
