### ISSUE TITLE
LengthAwarePaginator returns the total provided regardless of the total actual count of the data

### ISSUE THREAD

**Issue by ismailnakkar** [laravel/framework#52090]
### Laravel Version

11.13

### PHP Version

8.3

### Description

Paginate should return the correct total (not the total provided by the user when providing one)

Currently the code in paginate is `$total = value($total) ?? $this->toBase()->getCountForPagination();`

But I believe it should be `$total = $total ? min(value($total), $this->toBase()->getCountForPagination()) : $this->toBase()->getCountForPagination();`

### Steps To Reproduce

Paginate any model, if you choose the total to be 10000, it will return 10000 even if there is less than that in the total count of the model

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/pull/46410

**Comment by crynobone** [comment]
The `$total` parameter was added to skip running the default aggregate count query, so this seems to be the expected behavior now.

**Comment by ismailnakkar** [comment]
Well let's assume that I'm using a total of 50 on a query that returns nothing, I'd calculated pages and a total of 50 on an empty collection. I don't believe that is the expected behavior..
