### ISSUE TITLE
Illuminate\Queue\Failed\FailedJobProviderInterface runs out of memory

### ISSUE THREAD

**Issue by godwin-loyaltek** [laravel/framework#52129]
### Laravel Version

8.0

### PHP Version

8.1

### Description

I will like to state the fact that the methods provided within the `FailedJobProvidedInterface` for queue management performs badly with multiple failed jobs (over 1,000 maybe). There is only the `all()` method to fetch `failed_jobs` and when it gets so much, PHP goes out of memory with the message below:
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes)`

Is it possible to get a fix on this to at least support some sort of paginated fetch or better?

### Steps To Reproduce

Steps to reproduce will be as stated below:
- Have a laravel project
- Create the `failed_jobs` table [`php artisan make:queue-failed-table`]
- Simulate some data into it (make sure to have as much as 10,000 or 20,000)
- Try to view the failed_jobs [**php artisan queue:failed**]

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by godwin-loyaltek** [comment]
Hi @crynobone,

Thanks for your response. Yes, I checked out the latest version of laravel (version 11) and it was still the same meaning the version isn't the problem I am having. Could you kindly take a look and see that I am right?

Regards.
