### ISSUE TITLE
Blade components do not render when conditional statements are used for attributes

### ISSUE THREAD

**Issue by gbalduzzi** [laravel/framework#52179]
@### Laravel Version

v10.48 and v11.15

### PHP Version

8.1

### Description

When using a custom blade component, conditional blade controls such as `@if`, `@required`, `@checked` used during attribute listing results in the blade component not rendering:

```html
<x-input type="password" name="password" @required(!isset($user)) />
```

Apparently the component is not recognized anymore, and this is the corresponding compiled view:

```html
<x-input type="password" name="password" <?php if(!isset($user)): echo 'required'; endif; ?> />
```

No error is raised, just the component is not rendered in the browser.

I find this fairly unexpected, because the syntax is common inside blade templates. At least an error would be very useful, pointing out the issue.

I can try to submit a PR if there is interest

### Steps To Reproduce

Use a blade component in a blade template with a blade control tag in the attribute list:

```html
<x-input type="password" name="password" @required(!isset($user)) />
<x-input type="password" name="password" @if(!isset($user)) required @endif />
<x-input type="password" name="password" {{ !isset($user) ? 'required' : '' }}  />
...
```

The resulting HTML will include the uncompiled component tag, thus not rendering:

```html
<x-input type="password" name="password"  />
<x-input type="password" name="password"  />
<x-input type="password" name="password"  />
...
```

**Comment by driesvints** [comment]
This isn't supported sorry. Please see https://laravel.com/docs/11.x/blade#component-attributes

<img width="769" alt="Screenshot 2024-07-22 at 16 05 10" src="https://github.com/user-attachments/assets/a3465627-5d81-4c5e-a961-4e880e76d2ca">
