### ISSUE TITLE
Mail template components button the formatting is off

### ISSUE THREAD

**Issue by marcoyan0814** [laravel/framework#52189]
### Laravel Version

11.10.0 or 10.48.4

### PHP Version

8.3.4

### Description

I use the default template components  
```
<x-mail::message>
    # Order Shipped

    Your order has been shipped!

    <x-mail::button :url="$url" color="success">
        View Order
    </x-mail::button>

    Thanks,<br>
    {{ config('app.name') }}
</x-mail::message>
```

![image](https://github.com/user-attachments/assets/821d40b8-6546-4d30-9b5e-c128e969d3e6)

### Steps To Reproduce

I tried to eliminate this problem and found that if I add a full blank to the first line of the template, the problem is solved.

```
resources/views/vendor/mail/html/button.blade.php
```
![image](https://github.com/user-attachments/assets/e9382a62-ad6a-4c50-871b-a660e8b7a4c4)

So I thought it might be a bug

**Comment by timacdonald** [comment]
You will need to remove the indentation. Mail does not work with indenting of Markdown.

```
<x-mail::message>
# Order Shipped

Your order has been shipped!

<x-mail::button :url="$url" color="success">
    View Order
</x-mail::button>

Thanks,<br>
{{ config('app.name') }}
</x-mail::message>
```
