### ISSUE TITLE
Incorrect URL Generation with Custom APP_URL

### ISSUE THREAD

**Issue by acecx** [laravel/framework#52191]
### Laravel Version

11.16.0

### PHP Version

8.3.9

### Description

Description:

When using the URL https://abcde-psdfxxx-8000.app.cloudstudio.work/ as the APP_URL, the default framework page generates incorrect URLs. For example, the {{ route('register') }} directive results in the path https://8000.app.cloudstudio.work/register. Similarly, all asset URLs are also generated with this incorrect host header.

### Steps To Reproduce

1、Set APP_URL in the .env file to https://abcde-psdfxxx-8000.app.cloudstudio.work/.
2、Start the Laravel development server using php artisan serve.
3、Access the application at https://abcde-psdfxxx-8000.app.cloudstudio.work/.
4、Check the generated URLs for routes and assets on the default framework page.

**Comment by driesvints** [comment]
Did you put the url between quotes? What happens if you try `APP_URL="https://abcde-psdfxxx-8000.app.cloudstudio.work"` (also notice no trailing slash)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
