### ISSUE TITLE
Eager Loading One-to-Many Relationship in Laravel Returns Empty Collection Despite Data Being Present

### ISSUE THREAD

**Issue by bridgeyuwa** [laravel/framework#52201]
### Laravel Version

11.14.0

### PHP Version

8.2.12

### Database Driver & Version

MySQL 8.0 on XAMPP

### Description

I'm facing an issue with eager loading in Laravel where a one-to-many relationship returns an empty collection, even though there is data present in the database. The same relationship works correctly when accessed using lazy loading.

I have two models, Institution and Social, where an Institution has many Socials. Despite there being related records in the socials table, eager loading of the socials relationship returns an empty collection. However, the same relationship returns data when accessed lazily.

The $institution->socials relationship works as expected when accessed using lazy loading (e.g., $institution->socials outside of load).
The issue occurs specifically with eager loading.

### Steps To Reproduce

**Social Model:**
```
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    use HasFactory;

    public function institution()
    {
        return $this->belongsTo(Institution::class);
    }
}

```

**Institution Model:**

```
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Institution extends Model
{
    use HasFactory;

    public function socials()
    {
        return $this->hasMany(Social::class);
    }
}

```

**Controller Code:**

```
public function show(Institution $institution)
{
    $allInstitutions = Institution::whereNotNull('rank')
                                  ->where('category_id', $institution->category->id)
                                  ->orderBy('rank')
                                  ->get();

    $institution->load([
        'schooltype',
        'category.institutions',
        'term',
        'catchments',
        'state.institutions',
        'state.region.institutions',
        'socials',
        'levels.programs' => function($query) use($institution) {
            $query->wherePivot('institution_id', $institution->id);
        }
    ]);

    dd($institution->socials); // Returns empty collection
}

```

**Database Schema**

```
--Institutions Table

CREATE TABLE institutions (
    id VARCHAR(255) PRIMARY KEY,
    -- other columns
);

--Socials Table

CREATE TABLE socials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    institution_id VARCHAR(255),
    -- other columns
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

```

**Query Log:** Verified that the SQL query for loading socials executes correctly, but the collection returned is empty. 
```
dd(DB::getQueryLog());
``` 

**Direct Query:** Manually querying the socials table shows that records with the correct institution_id are present. 
```
$socials = Social::where('institution_id', $institution->id)->get();
dd($socials);
```

**Cleared Caches:** Used php artisan cache:clear, php artisan config:clear, and other cache clearing commands.
Data Integrity: Checked that the foreign key relationship is set up correctly and that the data in the socials table matches the institution_id.

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear

```
**Testing in Isolation:** Tested the eager loading in isolation to see if other parts of the code are affecting the results: 
```
$institution = Institution::find($id);
$institution->load('socials');
dd($institution->socials);

```

Using 
Laravel 11,
XAMPP 8.2 (PHP 8.2, Mysql 8.0)

Thanks

**Comment by marius-mcp** [comment]
can you please listen to QueryExecuted event and print all the executed queries?

use


Log::info($queryExecuted->connection
            ->query()
            ->getGrammar()
            ->substituteBindingsIntoRawSql($queryExecuted->sql, $queryExecuted->connection->prepareBindings($this->bindings)));

Would be a good ideea if you would define all your relations with all params and not let laravel guess them for you.

**Comment by marius-mcp** [comment]
Also, instead of using load I would use ->with() on the query builder.

**Comment by marius-mcp** [comment]
Also

public function show(Institution $institution)
{
    $allInstitutions = Institution::whereNotNull('rank')
                                  ->where('category_id', $institution->category->id)
                                  ->orderBy('rank')
                                  ->get(); // collection here

    $institution->load([
        'schooltype',
        'category.institutions',
        'term',
        'catchments',
        'state.institutions',
        'state.region.institutions',
        'socials',
        'levels.programs' => function($query) use($institution) {
            $query->wherePivot('institution_id', $institution->id);
        }
    ]);

    dd($institution->first()?->socials);// try this

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by staudenmeir** [comment]
@bridgeyuwa Did you set the required properties for string primary keys?

```php
class Social extends Model
{
    public $incrementing = false;

    protected $keyType = 'string';
}

**Comment by marius-mcp** [comment]
> @bridgeyuwa Did you set the required properties for string primary keys?
> 
> ```
> class Social extends Model
> {
>     public $incrementing = false;
> 
>     protected $keyType = 'string';
> }
> ```

I remember this was an issue on another thread. I missed the fact that the id is a varchar. Great spotting.

**Comment by marius-mcp** [comment]
@bridgeyuwa I had this issue before with the primary key not being int and the relations would not load. See also this https://github.com/laravel/framework/discussions/51135#discussioncomment-9166143

Your institution id being string, if you put it int it will not load the relations. Anyway you confirmed this is not the case, so it must be something in laravel 11. I never had this issue in 8 9 10. If it works in 10 for example then it is clearly a l11 bug.

**Comment by marius-mcp** [comment]
I don't have laravel 11 locally. Until 12 is out, I'll not set 11 locally for stability reasons.

**Comment by ImSidow** [comment]
> n't have laravel 11 locally.

I understand your concerns about stability. However, being an early adopter of Laravel 11 can be quite beneficial. The codebase in Laravel 11 introduces some significant changes compared to previous versions. Getting familiar with these updates early on can help ease the transition to future versions, such as Laravel 12, and give you a head start in adapting your projects

**Comment by lrljoe** [comment]
You've given an example of loading this, which seems to have nested "institution" relations.

```
    $institution->load([
        'schooltype',
        'category.institutions',
        'term',
        'catchments',
        'state.institutions',
        'state.region.institutions',
        'socials',
        'levels.programs' => function($query) use($institution) {
            $query->wherePivot('institution_id', $institution->id);
        }
    ]);
```

What happens if you just load the "socials" relation, or preferably use the "with" approach when building your initial query?
Are you certain that the "id" you're passing in actually has a Social associated with it?

**Comment by lrljoe** [comment]
Maybe I'm misunderstanding you, but with() can absolutely be used on a single instance.

E.g.
```
User::where('email', 'joe@microsoft.com')->with('teams')->first()
```
Would return the User model "Joe", and any "Teams" relations.

I'm trying to replicate the issue you're presenting, and I've got a combination of UUID (Char 36), ULID, and BigInt primary keys, with a mixture of relations, but I haven't managed to break it in the same way that you're demonstrating.

**Comment by marius-mcp** [comment]
A question still remains, Why the lowercase cast?

**Comment by lrljoe** [comment]
@bridgeyuwa  - Interesting find!

I know that Laravel converts column names to lowercase, but wasn't aware it was also converting the values.  It makes sense given that some collations will throw a hissy fit.  And makes sense from a non-case-sensitive approach with indexing etc, but interesting to know.

I tend to use UUIDs/ULIDs for the most part, as a lot of the data is re-used across dozens of instances.

**Comment by wizzymore** [comment]
I can't reproduce this issue on a properly configured table, i replaced most of the query with CONFIDENTIAL but the bindings can still be seen.

The releation is self-referencing the same table, everything works like a charm, even with the format that we use in production: "ADV000000" it still searches as "ADV000000".

```php
> CONFIDENTIAL::with('test')->find('TESTING')
= null

> DB::getQueryLog()               
    [
      "query" => "select * from "CONFIDENTIAL" where "CONFIDENTIAL_id" = ? limit 1",
      "bindings" => [
        "TESTING",
      ],
      "time" => 1.49,
    ],
    [
      "query" => "select * from "CONFIDENTIAL" where "CONFIDENTIAL_id" in (?)",
      "bindings" => [
        "ADV1430468",
      ],
      "time" => 0.63,
    ],
```

This table is in production since Laravel was version 8 we went through all of the weekly updates and from version to version and never had an issue.

**Comment by wizzymore** [comment]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/74267b9c-8bfe-4abe-8d65-812f0870e303">
This is the output from your repo.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by marius-mcp** [comment]
For the record this is the answer https://github.com/laravel/framework/issues/52201#issuecomment-2291639293
