### ISSUE TITLE
Output from the artisan queue:listener is colorless

### ISSUE THREAD

**Issue by Disservin** [laravel/framework#52229]
### Laravel Version

11.9

### PHP Version

8.3.8

### Description

![image](https://github.com/user-attachments/assets/64aac96a-b595-47a4-bb77-3863180d153c)

Currently the console output of `php artisan queue:listen --tries=1 --timeout=1800` is colorless compared to the output of `php artisan queue:work`.

I believe that is because the process isn't set to be a tty process, when laravel starts it https://github.com/symfony/symfony/issues/23002.

A possible fix is described here although not very nice (relying on shell_exec):
https://github.com/laravel/framework/pull/52223

### Steps To Reproduce

1. Create a class which implements the ShouldQueue interface
2. Dispatch it into the queue, i.e.
```php
Route::get('/dispatch-job', function () {
    TestJob::dispatch('Hello, Queue!');
    return 'Job dispatched!';
});
```

```php
<?php
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $message;

    public function __construct($message)
    {
        $this->message = $message;
    }

    public function handle()
    {
        \Log::info('TestJob: ' . $this->message);
    }
}
```

**Comment by driesvints** [comment]
Thanks. It looks like this is a no-fix for now because Taylor closed the PR. If there's a cleaner solution we might reconsider.
