### ISSUE TITLE
Model create time out

### ISSUE THREAD

**Issue by OctavioVM** [laravel/framework#52235]
### Laravel Version

11

### PHP Version

8

### Description

I try to create a DetailOrder model record in my DB, but only for this model it doesn't work, in the end it stays loading and doesn't generate errors, I just have a time out.

### Steps To Reproduce

1. $detail = DetailOrder::create([
                        'order_id' => $order->id,
                        'quantity_packing' => $short,
                        'state_packing' => $stateShort,
                        'quantity_loading' => $short,
                        'state_loading' => $stateShort,
                        'quantity' => $product['quantity'],
                        'products_supplier_id' => $product['products_supplier_id'],
                        'ff_price' => $product['ff_price'] ?? null,
                        'price' => $product['price'],
                        'foc' => $product['foc'] === 1 ? 1 : 0,
                        'note' => isset($product['note']) ? $product['note'] : null,
                        'unit_cost' => $product['unit_cost'],
                        'value_profit' => $product['value_profit'],
                        'percentage_profit' => $product['percentage_profit']
                    ]);
2. get time out

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
