### ISSUE TITLE
Laravel 11 framework config auto-merging is a risky breaking change

### ISSUE THREAD

**Issue by NickSdot** [laravel/framework#52237]
### Laravel Version

11.16

### PHP Version

8.3

### Description

Hi. 👋 Unfortunaly, the auto-merging of config files broke our app after upgrading to L11.

In our app we are doing something like this, where **expected** connection data is used in `doStuff()`:

```php
protected function handleEvent($stage): void
{
    /** @var array<string, array<string, string>> $connections */
    $connections = $this->app['config']->get('database.connections');

    foreach ($connections as $connection) {
        $this->doStuff((object) $connection, $stage);
    }
}
```

Or something like this, where **expected** connection data is passed over to shell scripts via a command.

```php
$databaseConfig = Config::get('database');

// output connection credentials to be
// consumed by shell script.

foreach ($databaseConfig['connections'] as $connection) {
    echo "db_name={$connection['database']} ";
    echo "db_user={$connection['username']} ";
    echo "db_host={$connection['host']} ";
    echo "db_port={$connection['port']} ";
    echo "db_password={$connection['password']} ";
    echo PHP_EOL;
}
```

We keep our config files clean, and don't have any unused connections in there

```php
return [
    'connections' => [

        // e.g. no sqlite here 

        'core' => [
            // stuff
        ],
        'geo' => [
            // stuff
        ],
        'statistics' => [
            // stuff
        ],
];
```

Because of config merging by the framework `database.connections` is

```
1: array (size=8)
    sqlite => array (size=8)
    mysql => array (size=15)
    mariadb => array (size=15)
    pgsql => array (size=12)
    sqlsrv => array (size=10)
    core => array (size=16)
    geo => array (size=16)
    statistics => array (size=16)
```

instead of the following, where we deal with explicitly expected data

```
1: array (size=8)
    core => array (size=16)
    geo => array (size=16)
    statistics => array (size=16)
```

The issue with this is that e.g. `sqlite` does not have all keys we expect, which e.g results in:

```
Undefined property: stdClass::$xyz

// or

Undefined array key password
```

Before Laravel 11 our approach was perfectly fine, because we were in control what ends up in the final config and what not. Now, with the framework auto-merging in undesired config values, our apps end up to be blackboxes.

After understanding what is going on I learned about  the _undocumented_ 

```php
$app->dontMergeFrameworkConfiguration();
``` 

which solved the issue.

However, this let's me think: will we now, since we opted out, be at risk to run in similar issues in the future because the framework could have added new configs, which potentially are used by feature ABC or package XYZ?

Since there is no documented breaking change, I decided to submit this as a bug report to start a discussion.

Personally, and respectfully, I really think the new behaviour is dangerous. 
I don't see how either way, opting in **and** opting out from auto-merging can be safe.

**Proposed solutions for L12**

1) Go back to the previous L10 behaviour. Don't merge configs at all.
2) Don't merge if the config file exists in the app, and commit to not adding new config values in non-major versions.

I guess, at the very least, for now this should be documented as high impact breaking change.

Thanks in advance for your consideration. 🙏

### Steps To Reproduce

self-explaing?

**Comment by driesvints** [comment]
Hi @NickSdot, thanks for your thorough issue. Unfortunately there's no action to take on our side as this is simple the new way things work in Laravel v11. Deviating from it is a major change and something that'll severely impact any Laravel v11 app. We added `dontMergeFrameworkConfiguration` specifically for apps like yours to circumvent this. In general I would recommend discovering a different approach on your part so you don't have to rely on `dontMergeFrameworkConfiguration` and can just use v11 as intended. Right now we don't have any plans to move from the current way of merging configs sorry.

You're free to attempt a PR to the docs to document `dontMergeFrameworkConfiguration` if you want 👍

**Comment by NickSdot** [comment]
Thanks for your answer @driesvints. Surely, in this particular case, we could be explicit in what connections we want to select. Unfortunally, there is no different, universal approach to discover if the framework can merge in new stuff at any time.

Either we opt-out (in whatever way, or we don't.

I appreciate all your hard word, and am sorry to say it, but Laravel – with this – has built a ticking time bomb.

**Comment by driesvints** [comment]
@NickSdot can't you just create your own config file for this and extract everything from there?

**Comment by NickSdot** [comment]
Sure, I can duplicate the database config (plus whatever else unexpectedly explodes at some point) and maintain everything twice. 

I could also bind an additional full, unmerged "safe config" to the container, and add my own `SafeConfig` facade _to be save_, theoretically. This duplicates all the work the `LoadConfiguration` bootstrapper does. Just to have a second, safe, unmerged config.

But what good does that really do?
We end up with two configs, one safe and one unsafe.
Depending on which one you use, the problem still exists.
In the end it, unfortunally, still doesn't solve anything. 

It's the same as in opting out.

> I don't see how either way, opting in and opting out from auto-merging can be safe.

And fwiw, this is the case even if I would directly require specific config files (with the cost of losing caching, and with the cost of losing dot notation etc. pp.).

The problem here is that the issue is not limited to the above case. 
The concept itself is a risk and - IMHO - broken. 

My main concern is that we no longer know what is happening under the hood. Unexpected things could happen at any time, if there is not at least a committment to not introduce new config values in non-major versions. I saw it today - the hard way.

I don't mean to be disrespectful with the following. But is it really worth hiding a bunch of config files and risking breaking apps (ours just did) when there are classes that show me 176 methods in auto-completion?

This is how Laravel 10 looked like.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/886560bd-634a-4018-bf72-207aa379f92f">

This is how a typical root directory of an app looks like (hi laravel.io).

<img width="348" alt="image" src="https://github.com/user-attachments/assets/afe2a6b7-fe8a-4b69-98d5-bd58b152bb94">

It's config files, it's normal that they are there.

Should the framework really merge in a bunch of (in this case) unused database connections? **Is it really cleaner if e.g. Laravel IDEA is daily suggesting me unused, auto-merged config values I don't want and use?** I don't know how it is for you. Personally, I look more often at auto-completion than in the config folder.

Taylor said there are no breaking changes.

![image](https://github.com/user-attachments/assets/9ff21ad4-9cb1-4bdb-b085-1eaad637b1f9)

He, understandable, also cannot think of every potential problem in advance. But here we are. And I think with the new input from this issue, things could, and should, be at least re-considered.

By saying

> @NickSdot can't you just create your own config file for this and extract everything from there?

you are basically suggesting that we should stop embracing the framework. The config is one of the most core things of the framework I can think of. Should we all start duplicating our config handling to be sure nothing unexpected happens? Or opt-out to end up having the risk from the opposite direction?

I understand that decisions were taken. 
However, this issue proves that the new concept can and does break things.

Not sure if I am really the first one reporting such a case. But I would find it really unfortunate if there would be zero re-consideration after I did report it, @driesvints. 

Sorry for the long text. You see I am worried. Not sure if that is still the DX I have known and liked for the last 11 years.

I would appreciate if you at least could re-open this to allow some visibility to gather more opinions. 🙏

**Comment by driesvints** [comment]
I'm sorry you got caught with this @NickSdot but please hear me out. You're currently the only person who reported something like this. Plus it's from a very specific use case by you and you alone. Which brings me to the following:

![image](https://github.com/user-attachments/assets/bcb1a3e4-0528-4cc5-bd36-6973f05cf6c3)

I don't want to be dismissive by posting a comic but want to illustrate a point. We took careful consideration by moving into the direction we did for the config files of the framework. It could very well be that something specific broke for you for your specific use case. But in the vast overwhelming majority of Laravel apps everything is fine. 

Right now we're not considering reverting this direction we took. I also believe there are many creative ways you could do what you want to do without a lot of effort on your side. Again, we're sorry things broke for you. But I'm sure you'll find an easy solution to this.

**Comment by johanrosenson** [comment]
I want to add that i agree with @NickSdot (so that it doesn't look like he's the only one in the world to have this point of view).

In our team we have always cleaned/removed unused connections/stores from the config files (such as cache, database, filesystems and logging, did i forget any?), just because that since are not using those connections, we don't want any un-used/un-configured/non-working connections to even be available in the system, that has been our way of keeping our systems lean.

**Comment by pavloniym** [comment]
Same issue, but with `queue.connections`!
This auto-merge is breaking a lot of stuff in our project, because of this default unwanted connections from base Laravel configs. And this is hard to search and fix, because there is no any word in Upgrade Guide about it!
This is, definitely, not the correct behavior and not "no breaking changes"

**Comment by driesvints** [comment]
If someone would send in a PR to document `dontMergeFrameworkConfiguration` in the upgrade guide then that would be very much appreciated 👍

**Comment by dreadkopp** [comment]
We also just into this problem.

Yeah, we are a bit late to the whole update laravel 10->11 party.

In our usecase we have some kind of healthcheck that tests the accessibility of filesystems/caches/databases based on the configured values.

With the update to laravel 11 we could see that all our services would not update due to healthchecks failing and/or timing out.

Thanks to this issue we quickly found a solution/workaround.

However I also strongly suggest that this behavior should at least be documented.

**Comment by dreadkopp** [comment]
i made a small package as a workaround:

https://packagist.org/packages/dreadkopp/laravel-configured

use Configured - facade or configured() method
