### ISSUE TITLE
MariaDB uuid migration fieldType

### ISSUE THREAD

**Issue by Gioelinz** [laravel/framework#52243]
### Laravel Version

11.16.0

### PHP Version

8.2.0

### Database Driver & Version

MariaDB 10.6.17

### Description

When create a migration with fieldType 'uuid' it fail.

The field type uuid in mariadb is implemented from 10.10

### Steps To Reproduce

enviroment : DB_CONNECTION=mariadb
On migration
$table->uuid('uuid')

launch php artisan migrate

**Comment by driesvints** [comment]
Not sure what you're after here. You need 10.10 which you clearly aren't using?

**Comment by Gioelinz** [comment]
@driesvints in the Laravel 11 documentation the minimum version of mariadb is 10.3,
So I think this is a bug in MariaDbGrammar

**Comment by driesvints** [comment]
@Gioelinz but this is a MariaDB 10.10 feature. There's no way we can make it work in lower versions. There's really no action for us to take here.

**Comment by bmoex** [comment]
Well, the documentation says it supports 10.3 so if version is older than 10.7  (when added; https://mariadb.com/kb/en/uuid-data-type/) it should act like mysql driver 😟 
This took me ~2h to find that i should use `DB_CONNECTION=mysql` over `DB_CONNECTION=mariadb`.

I would suggest to add an helptext on the documentation page for the mariadb driver just like you have the sqllite section.
Mariadb >10.3 and < 10.7 seems to be supported perfectly if you use the mysql connection.

Just my 2 cents.
