### ISSUE TITLE
casts()-Method is not working

### ISSUE THREAD

**Issue by gala-matze** [laravel/framework#52273]
### Laravel Version

11.16.0

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

The Eloquent casts are not working like expected. The `HasAttributes`-Class has a method `initializeHasAttributes`. But that is never called. In the Model-Constructor it should be included to init the casts from the Method.

The Init-Method
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:191

`
    public function __construct(array $attributes = [])
    {
        $this->bootIfNotBooted();

        $this->initializeTraits();

        $this->syncOriginal();

        $this->fill($attributes);
    }
`

`initializeHasAttributes` is never called there.

### Steps To Reproduce

Set a cast only in the Method and not in the Property. In the Best case an Object-Cast.

**Comment by rodrigopedra** [comment]
It is called by `initializeTraits()`. 

It checks all traits included in a model and if it has a method named `initialize<TraitName>` it gets called.

**Comment by crynobone** [comment]
Thanks @rodrigopedra

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by charaldp** [comment]
Had the same issue and realized something was not correctly implemented in the Model that I tried to use the `casts()` method on.

You can check if you have overridden the `__construct(...)` method in your Model extending class or whether within your overriding constructor implementation you are using `parent::__construct(...);` at some point (you should use it).
