### ISSUE TITLE
[11.17] Laravel attempts to load attributes it didn't previously

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#52279]
### Laravel Version

11.17

### PHP Version

8.3.9

### Description

After upgrading from 11.16 to 11.17 I started getting errors in production: `Attribute class "Knuckles\Scribe\Attributes\Group" not found`.

I use [`scribe`](https://github.com/knuckleswtf/scribe) to generate API documentation. `scribe` is installed a a development dependency because the documentation is built during CI/CD.

Tests still passed because `scribe` is available during tests, but once this was in production it blew up.

Laravel 11.16 did not attempt to load these controller attributes, but now does.

This is a breaking change that unfortunately flew under the radar for me. Should this be expected behaviour going forward? (I can make `scribe` a regular dependency to get around this, but wanted to be sure).

Relevant PR: #52167

```php
use Knuckles\Scribe\Attributes\Group;


#[Group('Feeds', <<<'DESC'
Endpoints that return currently available listings that can be listed on other sites with permission.
DESC)]
class RoomController extends Controller
{
    //
}
```

### Steps To Reproduce

Add an attribute that doesn't exist/is not available to a controller.

```php
#[Laravel\InteractsWithLambo]
class PagesController extends Controller
{
    //
}
```

This will do nothing on Laravel 11.16, but blow up on Laravel 11.17.

**Comment by driesvints** [comment]
heya thanks. we reverted the causing PR.
