### ISSUE TITLE
Issue with declaring `bindings` and `singletons` properties

### ISSUE THREAD

**Issue by manavo** [laravel/framework#52286]
### Laravel Version

11.18.0

### PHP Version

8.3.7

### Description

The commit https://github.com/laravel/framework/commit/ed28a456f6b4799c33a59840fd68ea9f0922d463 seems to be creating an issue.

When they are magic properties, there is some wiggle-room for how they get defined. For example, in [SquirePHP](https://github.com/squirephp/repository/blob/3.x/src/RepositoryServiceProvider.php) it gets defined with the data-type of array: https://github.com/squirephp/repository/blob/3.x/src/RepositoryServiceProvider.php

So this accidentally becomes a backward incompatible change unfortunately.

### Steps To Reproduce

- `laravel new bug-report --github="--public"`
- `composer require squirephp/countries-en`

This results in the error:

```
PHP Fatal error:  Type of Squire\RepositoryServiceProvider::$singletons must not be defined (as in class Illuminate\Support\ServiceProvider) in /Users/manavo/Code/laravel-bug/bug-report/vendor/squirephp/repository/src/RepositoryServiceProvider.php on line 7

In RepositoryServiceProvider.php line 7:
                                                                                                                              
  Type of Squire\RepositoryServiceProvider::$singletons must not be defined (as in class Illuminate\Support\ServiceProvider) 
```

**Comment by driesvints** [comment]
I'm gonna revert this one. Thanks for reporting

**Comment by manavo** [comment]
Thanks @driesvints!
