### ISSUE TITLE
with function from eloquent builder does not work with callback and multiple relations

### ISSUE THREAD

**Issue by marius-mcp** [laravel/framework#52283]
### Laravel Version

11.x

### PHP Version

8.2

### Database Driver & Version

MySql 8

### Description

    /**
     * Set the relationships that should be eager loaded.
     *
     * @param  string|array  $relations
     * @param  string|\Closure|null  $callback
     * @return $this
     */
    public function with($relations, $callback = null)
    {
        if ($callback instanceof Closure) {
            $eagerLoad = $this->parseWithRelations([$relations => $callback]);
        } else {
            $eagerLoad = $this->parseWithRelations(is_string($relations) ? func_get_args() : $relations);
        }

        $this->eagerLoad = array_merge($this->eagerLoad, $eagerLoad);

        return $this;
    }

If $relations is array and $callback is instance of closure

=> Illegal offset type

### Steps To Reproduce

Call

 Model::newQuery()->with(['relation1', 'relation2'], function (Relation $relation): void {})->get();

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by marius-mcp** [comment]
I will not do that. Thank you.

**Comment by marius-mcp** [comment]
This is not a bug from the functionality intention point of view but it is from the code point of view. It should throw some exception in this situation not die with php error..

**Comment by macropay-solutions** [comment]
The right way of using this for multiple relations is:

```php
with(['rel' => function ($q): void {
    $q->where(...);
}]);
```
or calling in a loop
```php
with('rel', function ($q): void {
    $q->where(...);
});

```

Inspired by https://github.com/laravel/framework/discussions/52292#discussioncomment-13138292
