### ISSUE TITLE
Artisan about command error

### ISSUE THREAD

**Issue by KeldorDE** [laravel/framework#52291]
### Laravel Version

11.18.1

### PHP Version

8.3.9

### Description

The artisan about command raises the following error if no composer binary is available:
```
The command "'composer' '-V' '--no-ansi'" failed.

  Working directory: /var/www/httpdocs

  Error: proc_open(): posix_spawn() failed: No such file or directory
```

I am using a Docker container that contains all the framework files and is running PHP, but there is no composer binary available for execution.

What I've found is that the Illuminate/Support/Composer::findComposer() and Illuminate/Support/Composer::getVersion() methods do not check if the Composer binary is available for execution.

### Expected Behavior
The command should gracefully handle the absence of the Composer binary and provide a clear error message.

### Actual Behavior
The command fails with the following error message:
```
The command "'composer' '-V' '--no-ansi'" failed.

  Working directory: /var/www/httpdocs

  Error: proc_open(): posix_spawn() failed: No such file or directory
```

### Possible Solution
The `Illuminate/Support/Composer::findComposer()` and `Illuminate/Support/Composer::getVersion()` methods should check if the Composer binary is available before attempting to execute it.

### Steps To Reproduce

Run the `artisan about` command on a system where no composer binary is available.

**Comment by driesvints** [comment]
You need composer for this.
