### ISSUE TITLE
$this->attempts() function is not working after upgrade laravel 11

### ISSUE THREAD

**Issue by priteshqualitycode** [laravel/framework#52302]
### Laravel Version

11.18

### PHP Version

8.2.0

### Description

$this->attempts() function before I am using for count number of attempts and before working fine and I can know 1 for first attempt, 2 for second attempt, 3 for third attempts in log file but now the always return 1

$attempts = $this->attempts();
Log::error("No of attempt: ". $attempts);

### Steps To Reproduce

I updeade laravel 9 to 10 and 10 to 11 using laravelshift.com

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
