### ISSUE TITLE
Wrong type annotation for `request()` helper

### ISSUE THREAD

**Issue by sebj54** [laravel/framework#52312]
### Laravel Version

11.18.1

### PHP Version

8.2.17

### Description

There is a problem with the return type annotation for the `request` function. I think this problem is only revealed when using **PHPStan level 9**, because that's the only level raising issues with explicit mixed types.

Actual code from Laravel:

```php
/**
 * @return ($key is null ? \Illuminate\Http\Request : ($key is string ? mixed : array<string, mixed>))
 */
function request($key = null, $default = null) { /* … */ }
``` 

The problem is that, when you use this function without parameter, the result is evaluated as `array< string, mixed>`, you have to call the function with an explicit `null` value so it does not break.

![image](https://github.com/user-attachments/assets/8f92ea88-866d-4d94-a355-bb6fcfd5984c)

![image](https://github.com/user-attachments/assets/9c39f7ed-080c-4865-82cd-c3531ce9443e)

It seems that PHPStan does not pick the default value. If it is the expected behavior from PHPStan, then I think the return type annotation should be reversed:

```php
/**
 * @return ($key is string ? mixed : ($key is array ? array<string, mixed> : \Illuminate\Http\Request))
 */
``` 

What are your thoughts on this? I can submit a PR if needed.

### Steps To Reproduce

- Setup a new Laravel project
- Setup [Larastan](https://github.com/larastan/larastan)
- Change Larastan's level to 9
- In a new controller, paste this code:

```php
// Code with issue
$request = request();
$values = $request->all();

// Code without issue
$request = request(null);
$values = $request->all();
```

### EDIT

I just ran PHPStan with CLI and not from VSCode, I found out that the issues are not reported by PHPStan but by Intelephense. I don't know if it is relevant to keep the issue then 😐

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by sebj54** [comment]
Thanks for the heads-up! I'm used to other repos requiring an issue before a PR. 

Will definitely know for the future ;)
