### ISSUE TITLE
https://fonts.bunny.net/css?family=figtree:300,400,500,600

### ISSUE THREAD

**Issue by hooman-mirghasemi** [laravel/framework#52340]
### Laravel Version

11

### PHP Version

8.3.0

### Description

https://fonts.bunny.net/css?family=figtree:300,400,500,600

this url in first page of laravel and also in telescope and horizon panels load statiicly in html
It seems this site blocked Iran ips or some of internet providers ip ranges in iran. and page load will take a lot of time until status change to (failed)net::ERR_TIMED_OUT

### Steps To Reproduce

not needed

**Comment by driesvints** [comment]
Thanks. Would appreciate a PR that could resolve this.

**Comment by alexkart** [comment]
Have the same issue (not from Iran but from Ukraine for me), @driesvints can you reopen this issue? It looks like it is better to load fonts from somewhere other than `bunny.net`.

<img width="1302" height="246" alt="Image" src="https://github.com/user-attachments/assets/77abf077-a9db-4b05-89b2-97205fb6e513" />
