### ISSUE TITLE
trans_choice uses wrong pluralization rules for fallback

### ISSUE THREAD

**Issue by stefanvdlugt** [laravel/framework#52341]
### Laravel Version

11.8.0

### PHP Version

8.2.18

### Database Driver & Version

MySQL 8.0.32 for Linux on x86_64

### Description

The `trans_choice` translation function always uses the pluralization rules of the selected locale. If the provided key is not translated in this locale, it falls back to the fallback locale, but it still uses the pluralization rules of the preferred locale.

For example, Czech has [3 forms](https://en.wikipedia.org/wiki/Czech_declension#Plural_forms), while English has 2. If the translator must fall back to English, it should use the English pluralization rules.

### Steps To Reproduce

```php
app('translator')->setLocale('cs_CZ');
$fallback = app('translator')->getFallback();
app('translator')->addLines(['strings.apple' => ':count apple|:count apples'], $fallback);
trans_choice('strings.apple', 1); // 1 apple
trans_choice('strings.apple', 2); // 2 apples
trans_choice('strings.apple', 10); // 10 apple - WRONG
```

**Comment by driesvints** [comment]
Seems you sent in a PR so let's see how it goes 👍
