### ISSUE TITLE
"No application encryption key has been specified."

### ISSUE THREAD

**Issue by devajmeireles** [laravel/framework#52342]
### Laravel Version

11.19.0

### PHP Version

8.2.21

### Description

When the application does not have `APP_KEY` set and `SESSION_ENCRYPT` is true, even if you are only running commands through artisan, the `No application encryption key was specified.` is thrown. Since I don't know if this is expected to happen, I'm reporting it as a bug. Although APP_KEY` is necessary to encrypt session data, should this happen via terminal, where there is no session created?

![CleanShot 2024-07-31 at 10 43 30](https://github.com/user-attachments/assets/f0a6e1a3-087a-4a6c-95a0-ebbda76bd9a5)

### Steps To Reproduce

1. Create a fresh Laravel 11 application
2. Set the `APP_KEY` as blank
3. Set the `SESSION_ENCRYPT` as `true`
4. Try to run any Artisan command - even basic commands like: `php artisan --version` will throw the exception

**Comment by crynobone** [comment]
I believe this is expected.

1. Tests are executed using console, and HTTP requests tests would still require session.
2. Octane workers run from console.
