### ISSUE TITLE
Dynamodb for session storage uses the cache table instead of its own table

### ISSUE THREAD

**Issue by dshackley-pathful** [laravel/framework#52353]
### Laravel Version

10.48.18

### PHP Version

8.2.21

### Database Driver & Version

sql server latest

### Description

Hello, we were trying to get dynamodb to store our sessions and could not get it to work.

In the end, after looking at the source code, we discovered that dynamodb for sessions uses the cache table instead of it's own table.

session.php file
```php
return [
    'driver' => env('SESSION_DRIVER', 'database'),
    'lifetime' => env('SESSION_LIFETIME', 120),
    'expire_on_close' => false,
    'encrypt' => false,
    'files' => storage_path('framework/sessions'),
    'connection' => env('SESSION_CONNECTION', 'sqlsrv'),

    // For some reason, laravel uses the "cache" table instead of this table for sessions.
    // Seems like a bug and it isn't noted anywhere but we confirmed this was true.
    'table' => env('SESSION_TABLE', 'sessions'),
    'store' => env('SESSION_STORE', 'dynamodb'),
    'lottery' => [2, 100],
    'cookie' => env(
        'SESSION_COOKIE',
        Str::slug(env('APP_NAME', 'laravel'), '_') . '_session'
    ),
    'path' => '/',
    'domain' => env('SESSION_DOMAIN'),
    'secure' => env('SESSION_SECURE_COOKIE', false),
    'http_only' => true,
    'same_site' => 'lax',
    'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),

    'credentials' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
    ],
];
``` 

cache.php file
```php
'dynamodb' => [
            'driver' => 'dynamodb',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),

            // This table is being used for the sessions as well. Related comment in session.php
            'table' => env('DYNAMODB_CACHE_TABLE', 'cache'),
            'endpoint' => env('DYNAMODB_ENDPOINT'),
        ],
``` 

My question is, is this expected behavior? If so, why isn't it documented? If not, then it appears to be a bug.

### Steps To Reproduce

To reproduce, create a new dynamodb table with the name you put for the table in the sessions.php file, but make sure it is different than the name of the table for cache.php dynamodb.

Update your code to use that dynamodb for sessions.

You should get an error when you try to browse to a page because it can't create anything.

Now, create a new table in dynamodb that has the name for the dynamodb table in cache.php, and reload your site, no errors and items will appear in the table.

**Comment by crynobone** [comment]
https://github.com/laravel/laravel/blob/6ebd9fed8a1724464e9c1138d94c882d12dfd61b/config/session.php#L78-L89

It has explicitly documented that usage is for "database" driver.
