### ISSUE TITLE
Log::build doesn't take into account the value from the 'tap' parameter in the passed configuration

### ISSUE THREAD

**Issue by ktarasov** [laravel/framework#52354]
### Laravel Version

10.48.14

### PHP Version

8.1.2

### Description

When creating a logger using the build method, like this:
```
$logger = Log::build([
	'driver' => 'daily',
	'tap' => [ \App\Logging\CustomizeFormatter::class ],
	'path' => storage_path(sprintf('logs/%d/discounts-%s.log', $shop->id, $discount->id)),
	'level' => env('LOG_LEVEL', 'debug'),
	'replace_placeholders' => true,
	'days' => 14,
]);
```
classes that are specified in the 'tap' parameter are not called.

The reason is that in this case, the channel name for the log becomes `ondemand` and the method  `LogManager::configurationFor` tries to find this channel in the site configuration (through `$this->app['config']["logging.channels.ondemand"]`) and does not find it there. Although it would be logical to use the configuration passed to the method `Log Manager::build`.

### Steps To Reproduce

Create a class:
```
<?php

namespace App\Logging;

use Monolog\Formatter\LineFormatter;
use Illuminate\Log\Logger;

class CustomizeFormatter
{
    /**
     * @param  \Illuminate\Log\Logger  $logger
     * @return void
     */
    public function __invoke(Logger $logger): void
    {
        foreach ($logger->getHandlers() as $handler) {
            $handler->setFormatter(new LineFormatter(
                'TEST: [%datetime%] %channel%.%level_name%: %message% %context% %extra%' . PHP_EOL
            ));
        }
    }
}
```

Create a `logger` in any location that will be called, for example in `php artisan tinker`
```
$logger = Log::build([
	'driver' => 'single',
	'tap' => [ \App\Logging\CustomizeFormatter::class ],
	'path' => storage_path('logs/test.log'),
	'level' => env('LOG_LEVEL', 'debug'),
	'replace_placeholders' => true,
	'days' => 14,
]);
```

After that, call `$logger->info('Something here');`
In the `test.log` file, the string should start with 'TEST:', but this will not happen.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
