### ISSUE TITLE
Generate a custom rules using php artisan make:rule

### ISSUE THREAD

**Issue by Tiskiel** [laravel/framework#52366]
### Laravel Version

11.0

### PHP Version

8.2

### Description

Hi, 

Using the php artisan make:rule MyCustomRule, I see that the `use Illuminate\Contracts\Validation\Rule;` is deprecated.

It is normal that this command generate me a depracated stub ? 

Thank you in advance

### Steps To Reproduce

php artisan make:rule MyCustomRule

**Comment by crynobone** [comment]
Do you have `stubs/rule.stub` file in the project? If you publish the stub it would use what's has been publish regardless if Framework now has the updated code: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/stubs/rule.stub

**Comment by Tiskiel** [comment]
@crynobone Indeed, I've got the stubs published, but they're still from the previous version. The project has been updated but not the stubs. I update them directly. Sorry for this issue, it's a personal mistake !
