### ISSUE TITLE
Registering Event Subscribers processes the subscriber twice

### ISSUE THREAD

**Issue by mhmdomer** [laravel/framework#52404]
### Laravel Version

11.1.4

### PHP Version

8.3.9

### Description

The documentation on Event Subscribers says that we should register the event subscriber after creating it [https://laravel.com/docs/11.x/events#registering-event-subscribers](https://laravel.com/docs/11.x/events#registering-event-subscribers), however, when I do so, the event subscriber will double-process the event that it is subscribing to. After some debugging, I found that just ignoring the registration of the Event Subscriber class fixes the issue.

Is it meant to register the event subscriber automatically? if so, then I can create a PR to update the documentation to mention that the Event Subscribers will automatically be registered.

### Steps To Reproduce

- Create a new laravel project `laravel new event-subscriber`
- Create an event `php artisan make:event SampleEvent`
- Create an Event Subscriber class that listens to the previous event:
```php
<?php

namespace App\Listeners;

use App\Events\SampleEvent;
use Illuminate\Support\Facades\Log;

class SampleSubscriber
{
    /**
     * Handle the event.
     */
    public function handleSampleEvent(SampleEvent $event): void
    {
        Log::info('sample event processed.');
    }

    /**
     * Subscribe to the events for the subscriber.
     * 
     * @param \Illuminate\Events\Dispatcher $events
     */
    public function subscribe($events): void
    {
        $events->listen(
            SampleEvent::class,
            [SampleSubscriber::class, 'handleSampleEvent']
        );
    }
}
```
- In the `AppServiceProvider.php`, register the subscriber:
```php
public function boot(): void
{
    Event::subscribe(SampleSubscriber::class);
}
```
- Run `php artisan tinker` and trigger the SampleEvent `event(new \App\Events\SampleEvent())`
- Check out the `storage/logs/laravel.log` file, you will see that the message "sample event processed." is logged twice.
- Comment out the line where you register the subscriber on the `AppServiceProvider.php`
- Trigger event again, the message will only be logged once.

**Comment by andrewbroberg** [comment]
Could this be because of the auto discovery that Laravel does?

**Comment by mhmdomer** [comment]
> Could this be because of the auto discovery that Laravel does?

I believe so.

**Comment by taylorotwell** [comment]
Any public class in listeners directory with a method that starts with `handle` will be automatically registered as a listener.

**Comment by njpanderson** [comment]
Apologies for commenting on a closed issue but I've just been bitten by this as well — I think there's maybe an issue with the docs.

It mentions the above as Taylor quite rightly pointed out here:
https://laravel.com/docs/11.x/events#event-discovery

However the docs for making a subscriber (https://laravel.com/docs/11.x/events#event-subscribers) don't seem to take this into account and if you follow the guidance verbatim you will potentially end up with handlers being fired twice.

In my case it was literally the "handleUserLogin" method I had on a subscriber in an "App\Listeners\Subscribers" namespace.

Could the docs possibly be updated to reflect this in some way? If it is the intention to keep manual registration then perhaps a different example namespace could be used to avoid the methods being auto-registered?
