### ISSUE TITLE
Exceptions Renderer Listener causing memory leak

### ISSUE THREAD

**Issue by amcsi** [laravel/framework#52416]
### Laravel Version

11.20.0

### PHP Version

8.3.10

### Description

The linked file from the linked PR is causing a memory leak: https://github.com/laravel/framework/pull/51261/files#diff-dd48a4b628c66b2c2388be3d8f6c63911e5cef6b1bfb483fe8c36739087ce40f (#51261)

Why?
This listener class implicitly listens to query execution events, and then - despite me not opting into logging queries - this class stores executed queries in it, though limited to 100.

This is bad when doing many bulk updates in an (ETL) loop, because it stores large bulk insert SQL queries in memory, causing high memory usage.

OK, to be fair, this only happens if Debug mode is on. But I did spend a bunch of time debugging why memory usage was high while developing an ETL tool locally, because I didn't know there was a recent code change that kept query logs that I didn't opt into.

### Steps To Reproduce

```php
foreach ($lazyCollectionWith100000Values->chunk(1000) as $rows) {
  \DB::table('some_table')->insert($rows->toArray());
}
// 100 x 1000 rows worth of values are stuck in memory.
```

**Comment by hugoboss17** [comment]
As it's mention [here](https://github.com/laravel/framework/issues/27539#issuecomment-646112782)
you can disable the logging and enable it after the bulk insert.

this will result in reduced memory usage and not throw the exception.

**Comment by amcsi** [comment]
Yes, assuming you didn't create any event listeners that you did actually want to use

**Comment by hugoboss17** [comment]
If you still need to have event listeners on this exact queries you can do the setEventDispatcher referencing which event listeners to have.
Pretty much excluding the one you're getting the exception and including your desired one.


But I may be seeing this wrong :)

**Comment by driesvints** [comment]
Hi @amcsi. Since you mention this only happening with debug mode I don't consider this a huge issue. @hugoboss17 also gives a workaround (thanks!).

**Comment by amcsi** [comment]
The workaround isn't perfect, because maybe one would want to listen to events in a custom listener. But at least I wanted to make sure there was an Issue for this so that if in the future anyone would get confused about high memory usage locally or on a dev server, they would save time by finding this Issue by googling.

**Comment by amcsi** [comment]
So for projects where you don't need to listen to any DB events at all, this is the workaround in the `boot()` method of any service provider:

```php
\DB::connection()->setEventDispatcher(new \Illuminate\Events\Dispatcher());
```

This is better than `\DB::connection()->unsetEventDispatcher();`, because otherwise some Feature tests would fail.

---

In the event that you _do_ want to listen to other DB events, you can create a new override class for the high memory usage listener class:

```php
<?php

declare(strict_types=1);

namespace App\Exceptions;

use Illuminate\Database\Events\QueryExecuted;
use Illuminate\Foundation\Exceptions\Renderer\Listener;

/**
 * Override of Laravel's exceptions listener.
 */
class ExceptionsListenerOverride extends Listener
{
    public function onQueryExecuted(QueryExecuted $event)
    {
        // (...Or you could have a condition here to not return, but rather call the parent, if you do want the log-to-memory behavior for the exceptions HTML page.)
        
        return;
    }
}
```

...And then use that overridden class this way in any service provider's `register()` method:

```php
$this->app->bind(Listener::class, ExceptionsListenerOverride::class);
```

**Comment by CodyJHeiser** [comment]
> So for projects where you don't need to listen to any DB events at all, this is the workaround in the `boot()` method of any service provider:
> 
> \DB::connection()->setEventDispatcher(new \Illuminate\Events\Dispatcher());
> This is better than `\DB::connection()->unsetEventDispatcher();`, because otherwise some Feature tests would fail.
> 
> In the event that you _do_ want to listen to other DB events, you can create a new override class for the high memory usage listener class:
> 
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\Exceptions;
> 
> use Illuminate\Database\Events\QueryExecuted;
> use Illuminate\Foundation\Exceptions\Renderer\Listener;
> 
> /**
>  * Override of Laravel's exceptions listener.
>  */
> class ExceptionsListenerOverride extends Listener
> {
>     public function onQueryExecuted(QueryExecuted $event)
>     {
>         // (...Or you could have a condition here to not return, but rather call the parent, if you do want the log-to-memory behavior for the exceptions HTML page.)
>         
>         return;
>     }
> }
> ...And then use that overridden class this way in any service provider's `register()` method:
> 
> $this->app->bind(Listener::class, ExceptionsListenerOverride::class);

This was the only solution that worked for me in Laravel 12 as well. When I called my upsert method, the memory leak would happen. Thank you!!
