### ISSUE TITLE
Migration is not working as expected (as written in docs)

### ISSUE THREAD

**Issue by kvelaro** [laravel/framework#52427]
### Laravel Version

11.19.0

### PHP Version

8.3.9

### Database Driver & Version

Postgres 16.3 (pdo_pgsql, pg_sql)

### Description

We have multiple db conections

So we have created migration file as described in official docs
1. With protected property $connection set to alternative db 
2. With Schema::connection('<alternative_db>')->create() ... 
But these options seems to not work

If we run from command line migration set with database option --database=<alternative_db> migration is applied to alternative db (But this is not an option)

We debugged and it seems that migration command only accepts --database option or uses default connection

### Steps To Reproduce

php artisan migrate

**Comment by hafezdivandari** [comment]
We have many PostgreSQL specific integrations tests for `Schema::connection()` [here](https://github.com/laravel/framework/blob/e1a9c5dcabb8cd49838648ddc34c5e5272e1a52c/tests/Integration/Database/SchemaBuilderSchemaNameTest.php).

Also [these 2 tests](https://github.com/laravel/framework/blob/e1a9c5dcabb8cd49838648ddc34c5e5272e1a52c/tests/Database/DatabaseMigratorIntegrationTest.php#L114-L144) works for setting `$connection` property on `Migration` class using SQLite connection.

**Comment by kvelaro** [comment]
Sorry man, it just does not work or Im stupid, doing something wrong
Please have a look

https://www.dropbox.com/t/gFdSGIpjJoi58cKa

This thing 
https://laravel.com/docs/11.x/migrations#setting-the-migration-connection
is not working

$connection is being ignored by framework

Or what Im doing wrong?

**Comment by hafezdivandari** [comment]
What is the output of `php artisan db:show --database=caching`?

**Comment by kvelaro** [comment]
> php artisan db:show --database=caching
At first this command failed with following error
```
root@33ec01ea16a6:/IdeaProjects/graphql# php artisan db:show --database=caching
PDOException 
SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "caching" does not exist
```
Yeah, I know its a silly, but I created on my own
```

root@33ec01ea16a6:/IdeaProjects/graphql# su postgres -c '/opt/pgsql/bin/createdb caching'
root@33ec01ea16a6:/IdeaProjects/graphql# php artisan db:show --database=caching

  PostgreSQL .................................................................................................................................. 16.3  
  Connection .......................................................................................................................................  
  Database ................................................................................................................................. caching  
  Host ................................................................................................................................... 127.0.0.1  
  Port ........................................................................................................................................ 5432  
  Username ................................................................................................................................ postgres  
  URL ..............................................................................................................................................  
  Open Connections ............................................................................................................................... 6  
  Tables ......................................................................................................................................... 0  
```

Then issued next command
```
php artisan config:show database

  database .........................................................................................................................................  
  default .................................................................................................................................... pgsql  
  connections ⇁ caching ⇁ driver ............................................................................................................. pgsql  
  connections ⇁ caching ⇁ url ................................................................................................................. null  
  connections ⇁ caching ⇁ host ........................................................................................................... 127.0.0.1  
  connections ⇁ caching ⇁ port ................................................................................................................ 5432  
  connections ⇁ caching ⇁ database ......................................................................................................... caching  
  connections ⇁ caching ⇁ username ........................................................................................................ postgres  
  connections ⇁ caching ⇁ password ........................................................................................................ postgres  
  connections ⇁ caching ⇁ charset ............................................................................................................. utf8  
  connections ⇁ caching ⇁ prefix ...................................................................................................................  
  connections ⇁ caching ⇁ prefix_indexes ...................................................................................................... true  
  connections ⇁ caching ⇁ search_path ....................................................................................................... public  
  connections ⇁ caching ⇁ sslmode ........................................................................................................... prefer  

```

Tried to issue migration
```
root@33ec01ea16a6:/IdeaProjects/graphql# php artisan migrate

   Illuminate\Database\QueryException 

  SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: FATAL:  role "root" does not exist (Connection: pgsql, SQL: select c.relname as name, n.nspname as schema, pg_total_relation_size(c.oid) as size, obj_description(c.oid, 'pg_class') as comment from pg_class c, pg_namespace n where c.relkind in ('r', 'p') and n.oid = c.relnamespace and n.nspname not in ('pg_catalog', 'information_schema') order by c.relname)

```

Tried to set postgres's password to empty string, also without success

Note to mention again! `php migrate --database=caching` is doing its job, but Im not interested in this king of command

**Comment by kvelaro** [comment]
Suddenly, I realised problem

We are developing package https://laravel.com/docs/11.x/packages and currently do not need primary connection (because our package is aimed to work with alternative db). But as I understood, for framework its crucial to have alive primary db connection

To cut long story short, I see two options here:
1. To mention in official docs importance of primary db connection when creating alternative db connection
2. To fix in framework itself (seems, this is not a case, because `migrations` table is stored in main connection)

Waiting for your comment @hafezdivandari and I think we can close this issue
Thank you, for your help and time
