### ISSUE TITLE
limit() in relationship load extremely slow in Laravel 11

### ISSUE THREAD

**Issue by MeesterDev** [laravel/framework#52439]
### Laravel Version

11.20.0

### PHP Version

8.2.22

### Database Driver & Version

MySQL 8.0.33

### Description

Loading a relationship with a `limit()`, results in an extremely slow query.

Laravel 10 query:
```mysql
select * from `measurements` where `measurements`.`beaconMac` in (?) order by `measurementDate` desc limit 1
```

Laravel 11 query:
```mysql
select * from (select *, row_number() over (partition by `measurements`.`beaconMac` order by `measurementDate` desc) as `laravel_row` from `measurements` where `measurements`.`beaconMac` in ('somebinarystring')) as `laravel_table` where `laravel_row` <= 1 order by `laravel_row`
```

The latter takes several minutes, whereas the first is near instantaneous.

(The goal of loading this relationship is to get the most recent measurement)

------

For anyone stumbling upon this with the same problem, I worked around the issue by using:
```php
            $measurement = $beacon->measurements()
                ->orderByDesc('measurementDate')
                ->limit(1)
                ->get();
            $beacon->setRelation('measurements', $measurement);
```

### Steps To Reproduce

```php
            $beacon->load([
                'measurements' => function (HasMany $q) {
                    $q->orderByDesc('measurementDate');
                    $q->limit(1);
                }
            ]);
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by MeesterDev** [comment]
Thank you for the response, it's not worth that much trouble for me. I'm sorry.

I'm 99% sure it's a bug, if it's not, it's not. The workaround works for me.
