### ISSUE TITLE
DatabaseRule "unique" fails quietly when given an incorrect column

### ISSUE THREAD

**Issue by woganmay** [laravel/framework#52456]
### Laravel Version

11.20.0

### PHP Version

8.3.6

### Database Driver & Version

PostgreSQL 16

### Description

If I write a validation rule for a non-existent table, for eg:

```php
$validator = Validator::make(request()->all(), [
  'port' => 'required|integer|unique:nonexistent,port',
]);
```

The validator crashes with `SQLSTATE[HY000]: General error: 1 no such table: nonexistent` which is good enough. However, if I specify an existing table but a non-existent column, no errors or exceptions are thrown.

### Steps To Reproduce

To reproduce this bug:

- Create any table
- Create a validator that uses the unique: rule
- Specify a valid database name but an invalid column name

**Comment by Lakshan-Madushanka** [comment]
@woganmay, @crynobone  I have experience this issue several time and this can cause unexpected behavior and  issues. So I opened a pull request which I wanted to do a while ago.

**Comment by withgem** [comment]
I believe the expected behavior should be to throw an error when an invalid column is specified. I reviewed @Lakshan-Madushanka's pull request #52500, and it seems to address this issue effectively.

**Comment by driesvints** [comment]
I don't think there's any action for us to take here as it's expected you provide a correct column name.
