### ISSUE TITLE
firstOrNew on belongsToMany doesn't work as expected

### ISSUE THREAD

**Issue by zeyad82** [laravel/framework#52471]
### Laravel Version

9.52.16

### PHP Version

8.2

### Description

$user->roles()->firstOrNew();

In earlier versions, this was supposed to retrieve the first role attached to that user or a new model if that user has no roles. Now it's retrieving the first role of the roles regardless of the relationship with that user. So it's retrieving roles not attached to that user.

### Steps To Reproduce

Create a user and roles with relationship belongsToMany. This $user->roles()->firstOrNew();  could retrieve a role that not attached to the user.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by paulandroshchuk** [comment]
> Hey there,
> 
> Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!

This issue still exists in Laravel 11.

@crynobone

**Comment by mitchierichie** [comment]
Can you please reopen @crynobone ?

This still exists in Laravel 12.

**Comment by sahil-io** [comment]
I'm gonna go out on a limb here and predict that when Laravel 13 drops, this bug will still be there.
It's a bug with tenure

**Comment by crynobone** [comment]
Create a new issue with reproduction repository
