### ISSUE TITLE
Accessor date casting formatting as UTC when being serialized to JSON.

### ISSUE THREAD

**Issue by robertmylne** [laravel/framework#52478]
### Laravel Version

10.45

### PHP Version

8.3.1

### Database Driver & Version

MySql 8

### Description

```
class Appointment extends Model
{
    protected $casts = [
        'starts_at' => 'datetime',
    ];

    protected $appends = [
        'starts_at_local',
    ];

    public function startsAtLocal(): Attribute
    {
        return new Attribute(function ($value) {
            return $this->starts_at->setTimezone($this->location->timezone);
        });
    }
}
```

JSON serialized output (both in UTC):
```
starts_at: "2024-08-14T02:45:00.000000Z"
starts_at_local: "2024-08-14T02:45:00.000000Z"
```

I can solve this in the JSON output with:
```
return new Attribute(function ($value) {
    return $this->starts_at->setTimezone($this->location->timezone)->toIso8601String();
});


starts_at: "2024-08-14T02:45:00.000000Z"
starts_at_local: "2024-08-14T02:45:00+10:00"
```

However, I then run into the issue where I can't really work with the local time in code (for email templates for example) anymore:
```
<div>{{ $appointment->starts_at_local->format('F'); }}</div>
```

I could in the code just revert back to the other formatting then, but this stops me from having a single point of truth:
```
<div>{{ $appointment->starts_at_local->setTimezone($appointment->location->timezone)->format('F') }}</div>
```

I guess what would be nice would be to be able to override OR skip the part where Laravel serializes this date as UTC. I understand why this is a sensible default, but by not being able to override it, it creates issues.

### Steps To Reproduce

Create an accessor, format it in a timezone and then view the JSON output.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
