### ISSUE TITLE
Using Emergency logging channel throw an exception

### ISSUE THREAD

**Issue by 7snovic** [laravel/framework#52487]
### Laravel Version

11.22.0

### PHP Version

8.3.8

### Description

Setting the logging channel to be emergency regardless using it in `.env` as `LOG_CHANNEL` or by specifying it using `Log::channel('emergency')` within the code or by setting env variable within the cli `LOG_CHANNEL=emergency php artisan ...` keep throwing an `ErrorException`

```
[2024-08-14 19:43:12] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ErrorException(code: 0): Undefined array key \"driver\" at .../example-app/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:234)
```

### Steps To Reproduce

As mentioned, switch to emergency logging channel, it will throw the mentioned exception alongside the main exception

- Go to .env and update LOG_CHANNEL=emergency
- [OR] set the logging channel to be `Log::channel('emergency')->error("Some data")`
- [OR] throw the terminal, switch it to emergency channel `LOG_CHANNEL=emergency php artisan some-command`

**Comment by 7snovic** [comment]
I wrote this [PR](https://github.com/laravel/framework/pull/52488) as a hotfix, but now sure if this should go throw the `LogManager.php` or we need to explicitly define the driver in the `config/logging.php` file in laravel/laravel repo

**Comment by crynobone** [comment]
Looks like the PR was rejected.

**Comment by 7snovic** [comment]
@crynobone lol yeah, for unknown reason
