### ISSUE TITLE
Job runs longer than "retry_after" will re-run immediately once the "retry after" seconds  passed. 

### ISSUE THREAD

**Issue by videni** [laravel/framework#52493]
### Laravel Version

8-11

### PHP Version

8.1

### Description

I searched but found no answer.   Job runs longer than "retry_after" will re-run immediately once the "retry after" seconds  passed. 

### Steps To Reproduce

This issue exists for all Laravel versions.

1. set job timeout  to 80s
2. set retry after to  30
3. the time to run a job  is 60s,  you can let is sleep 60s.

Then, you will see even  the job does not timeout and is not ended, it will be reran once "retry after" seconds  passed.

So one solution is that  we can set "retry after" to the longest timeout to make sure job ends before next run. since the job is still runing, not timeout , why start next run?   if the attempts limit not reached,  we will have two runing  instances for the this job.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
