### ISSUE TITLE
Unexpected behaviour when chunking a query

### ISSUE THREAD

**Issue by philbates35** [laravel/framework#52495]
### Laravel Version

11.8

### PHP Version

8.2

### Description

When constructing a `Query`, calling `->chunk()` before calling `->get()` or `->delete()` alters the original `Query` object resulting in unexpected results when calling `->get()`.

I consider this unexpected because I expected `->chunk()` to be a read only operation i.e. it doesn't add any constraints to the underling query.

### Steps To Reproduce

Execute the query (no chunk before its executed):
```php
$query = \App\User::query()->where('created_at', '<=', \Carbon\CarbonImmutable::today()->subMonths(3));

$query->delete(); // 1742
```

Chunking the query before doing something with it:
```php
$query = \App\User::query()->where('created_at', '<=', \Carbon\CarbonImmutable::today()->subMonths(3));

$query->chunk(250, function ($users) {}); // Do something with the $users e.g. create a log entry for each user

$query->delete(); // 242
```

You can see that by calling `$query->chunk()` first, even with an empty closure, it resulted in ~1,500 users not being deleted

(For context: I used the combination of `->chunk()` and `->delete()` because I needed to do something per user that wasn't possible to do in a single operation before they were deleted, but I still wanted to run a single DELETE query instead of `n` DELETE queries inside the `->chunk()`)

**Comment by crynobone** [comment]
Chunk will modify the query and append take and limit to the generated SQL, you should be able to clone the instance for your use case.

```php
$query = \App\User::query()->where('created_at', '<=', \Carbon\CarbonImmutable::today()->subMonths(3));

$query->clone()->chunk(250, function ($users) {}); // Do something with the $users e.g. create a log entry for each user

$query->delete(); // 242
```

**Comment by crynobone** [comment]
Chunk will modify the query and append take and limit to the generated SQL, you should be able to clone the instance for your use case.

```php
$query = \App\User::query()->where('created_at', '<=', \Carbon\CarbonImmutable::today()->subMonths(3));

$query->clone()->chunk(250, function ($users) {}); // Do something with the $users e.g. create a log entry for each user

$query->delete(); // 242
```

**Comment by philbates35** [comment]
@crynobone thanks, yeah that's how I worked around the issue in the end, but I thought I'd report anyway as I found it unexpected and resulted in a bug getting deployed. My tests were passing so I was confident it was working but I obviously didn't have a test where I created > 250 users.

Do you think it maybe makes sense for `->chunk()` to do a clone internally before applying the take and limit so that in my example I wouldn't need to do the clone myself?

**Comment by crynobone** [comment]
> Do you think it maybe makes sense for ->chunk() to do a clone internally before applying the take and limit so that in my example I wouldn't need to do the clone myself?

Not really, chunking is documented under returning model results, and therefore is it expected that you are no longer working on pre-defined query builder at the state.
