### ISSUE TITLE
Database migrations in pretend mode doesn't display insert statements to migrations table

### ISSUE THREAD

**Issue by Sn0wCrack** [laravel/framework#52491]
### Laravel Version

10.48.19

### PHP Version

8.2

### Database Driver & Version

MariaDB / MySQL

### Description

When running the migrate command with the `--pretend` flag, I've noticed the insert statement that is run for adding a new entry into the migrations table is not output along with the `create table` and `alter table` commands.

I've noticed other insert commands that are executed within the migration, such as database seeders, are recorded in the output however.

### Steps To Reproduce

Run `php artisan migrate --pretend` with currently pending migrations, only create tables, alerts and inserts from seeders are displayed.

**Comment by Boorinio** [comment]
I opened a pr for this, lets see
https://github.com/laravel/framework/pull/52513

**Comment by driesvints** [comment]
Seems we're not going to take action here sorry.
