### ISSUE TITLE
MariaDB doesn't have json datatype, forces to use longText

### ISSUE THREAD

**Issue by bhattji** [laravel/framework#52529]
### Laravel Version

11.x

### PHP Version

8.3.x

### Database Driver & Version

MariaDB

### Description

MariaDB doesn't have json datatype, forces to use longText. Laravel needs to have a special driver for MariaDB (maybe, we can specify DB_CONNECTION=mariadb instead of DB_CONNECTION=mysql in .env file), which will recognise $table->json() and automatically convert to $table->longText()

### Steps To Reproduce

run any migration having a json data type (  $table->json()  ) when in .env the DB_CONNECTION=mysql

**Comment by driesvints** [comment]
I'm not sure what you want? MariaDB doesn't have this feature so just don't use it?

**Comment by bhattji** [comment]
What I mean is, MariaDB uses longText ($table->longText)) and MySql uses json ( $table->json() )

So whenever I install any plugin, which has migration having $table->json() , I have to manually rename it to $table->longText()

**Comment by hafezdivandari** [comment]
@bhattji MariaDB has `JSON` type as an alias for `LONGTEXT`: https://mariadb.com/kb/en/json-data-type/

**Comment by bhattji** [comment]
> @bhattji [MariaDB 10.2.7+](https://mariadb.com/kb/en/mariadb-1027-release-notes/#:~:text=The%20JSON%20data%20type%20(an%20alias%20for%20LONGTEXT)%20was%20introduced.) has `JSON` type as an alias for `LONGTEXT`: https://mariadb.com/kb/en/json-data-type/

Right, but one has to rename all the json to longText (that, precisely is the issue)
