### ISSUE TITLE
Event dispatch inconsistency

### ISSUE THREAD

**Issue by Pr3d4dor** [laravel/framework#52521]
### Laravel Version

11.20.0

### PHP Version

8.3.7

### Description

There is a inconsistency when dispatching events.

Given the classes:
```
class TestEvent
{
    public function __construct(
        public string $test
    ) {}
}
```

And
```
class TestListener
{
    public function handle(TestEvent $exampleEvent)
    {
        // Some code
    }
}
```

Those snippets dont produce the same behavior:

```
// Does not work, throws a error in the listener class (listener excepts the TestEvent class, but is given a string)
Event::dispatch(TestEvent::class, ['hello']);
```

```
// Works as expected
Event::dispatch(new TestEvent('hello'));
```

I dont know if this is the intended behavior or not.

Links to #owen-it/laravel-auditing#963

### Steps To Reproduce

The steps do reproduce are in the description above.

**Comment by driesvints** [comment]
I don't think we document the former?
