### ISSUE TITLE
Resource routing overlaping when they are devided

### ISSUE THREAD

**Issue by HichemTab-tech** [laravel/framework#52551]
### Laravel Version

11.9

### PHP Version

8.3

### Description

# **Problem: Route Overlapping in Resource Routes with `only` and `except` Clauses**

When dividing resource routes using the `only` and `except` clauses (e.g., separating the `index` and `show` routes under `auth` middleware and `create`, `store`, `edit`, `update`, and `destroy` routes under `auth:admin` middleware), an unexpected route overlapping issue occurs.

## Scenario

1. When defining routes like this:
   ```php
   Route::middleware('auth')->group(function () {
       Route::resource('/areas', AreaController::class)->only(['index', 'show']);
   });

   Route::middleware('auth:admin')->group(function () {
       Route::resource('/areas', AreaController::class)->except(['index', 'show']);
   });
   ```
   
2. The `create` route (`GET /areas/create`) overlaps with the `show` route (`GET /areas/{area}`). Laravel attempts to resolve the `create` string as an `{area}` parameter, leading to an SQL error when it tries to find a record with `id = 'create'`.

## Outcome

- Instead of resolving the correct route for `create`, Laravel interprets "create" as an `{area}` parameter and tries to find a record with that ID, causing an SQL error when it fails to find an `id` with the value "create".

## Solution Found

A workaround for this issue is to add a `whereNumber()` constraint to the `{area}` parameter in the routes to ensure that Laravel only considers numeric values as valid IDs for the `show`, `edit`, `update`, and `destroy` routes.

## Updated Route Definition
```php
Route::middleware('auth')->group(function () {
    Route::resource('/areas', AreaController::class)->only(['index', 'show'])->whereNumber('area');
});

Route::middleware('auth:admin')->group(function () {
    Route::resource('/areas', AreaController::class)->except(['index', 'show'])->whereNumber('area');
});
```

## Why This Works
- The `whereNumber()` constraint ensures that Laravel treats the `create` string as a separate route, preventing it from being mistaken as an `id` in the `show` route. This prevents the overlapping issue between `create` and `show`.

## **Expected Behavior:**

When defining resource routes with `only` and `except` clauses, routes should not overlap, and `create` should not be misinterpreted as a resource identifier for the `show` route.

# **Additional Notes:**

- This issue does not occur when the resource route is defined without `only` and `except` clauses (i.e., all routes are defined under a single route line) like this :

```php
   Route::resource('/areas', AreaController::class);
```

- It only occurs when routes are split across different middleware groups using `only` and `except`.

# **Proposed Fix or Improvement:**

Consider adding a note to the documentation or improving the route model binding mechanism to handle such cases more gracefully when splitting resource routes using `only` and `except`. Alternatively, suggesting the `whereNumber()` constraint as a best practice when dealing with this scenario could help other developers avoid this issue.

# Credit
- @YounesAmalou

### Steps To Reproduce

just try this : 
```php
Route::middleware('auth')->group(function () {
    Route::resource('/areas', AreaController::class)->only(['index', 'show'])->whereNumber('area');
});

Route::middleware('auth:admin')->group(function () {
    Route::resource('/areas', AreaController::class)->except(['index', 'show'])->whereNumber('area');
});
```
and the create route will not be accessible, insteade an sql error will occur saying that id = create is not allowed or something similar.

**Comment by driesvints** [comment]
This is actually the expected behaviour. The first defined route is the one that'll catch the incoming request. Just swap the route sequence for it to work:

```
Route::middleware('auth:admin')->group(function () {
    Route::resource('/areas', AreaController::class)->except(['index', 'show']);
});

Route::middleware('auth')->group(function () {
    Route::resource('/areas', AreaController::class)->only(['index', 'show']);
});
```

**Comment by HichemTab-tech** [comment]
Oh my bad :') Thanks ^.^
