### ISSUE TITLE
Query Builder Conditional Clauses not working as per documentation

### ISSUE THREAD

**Issue by robertmylne** [laravel/framework#52559]
### Laravel Version

10.x

### PHP Version

8.3.x

### Database Driver & Version

MySql 8

### From documentation

The documentation has the following example:

https://laravel.com/docs/10.x/queries#conditional-clauses
```
$role = $request->string('role');
 
$users = DB::table('users')
                ->when($role, function (Builder $query, string $role) {
                    $query->where('role_id', $role);
                })
                ->get();

So, in the example above, the closure given to the when method will only be invoked if the role field is present on the incoming request and evaluates to true.
```

This clearly states `present on the incoming request and evaluates to true`. 

### Tested example

However, when I simply visit my url `https://app.localhost/roles` in a browser url bar with `no` params, it triggers the `dd` function. Which is should not as `role` is not present in the request. 

```
$role = $request->string('role');
dump($role);
Role::query()
    ->when($role, function (Builder $query, string $role) {
        dd($role);
        $query->where('role_id', $role);
    })
```
Value of `dump($role)`:
```
Illuminate\Support\Stringable {
  #value: ""
}
```
Value of `dd($role)`:
```
""
```

### Steps To Reproduce

1. Create a Role model
2. Create a Role controller with method
3. Create a route, and join the route to the controller method
4. Paste the following into the route

```
$role = $request->string('role');
dump($role);
Role::query()
    ->when($role, function (Builder $query, string $role) {
        dd($role);
    })
```

5. Visit the route and see the output.

**Comment by timacdonald** [comment]
We need to update the docs. To fix your app use the following...

```diff
- $role = $request->string('role');
+ $role = $request->input('role');
```

**Comment by timacdonald** [comment]
Docs PR: https://github.com/laravel/docs/pull/9839
