### ISSUE TITLE
Illuminate/Testing/TestResponse.php not returning decoded response

### ISSUE THREAD

**Issue by dropweb** [laravel/framework#52563]
### Laravel Version

11.x

### PHP Version

8.1

### Description

decodeResponseJson() here: https://github.com/illuminate/testing/blob/600e3d55288fec5dd00ebe330ce3766952611556/TestResponse.php#L998

This method called decodeResponseJson and with the comment "Validate and *return the decoded response* JSON." Returns the $testJson (which is asserted as vaid JSON) and not the $decodedResponse, which would seem like the correct data to return.

Maybe the comment is wrong and the name spurious. Otherwise I think that this should return the decoded JSON as implied.

I notice that this behaviour changed since 10.x

### Steps To Reproduce

Run a test that requests decodeResponseJson() on a json output.

The returned data is the output of AssertableJsonString() and not the decoded response $decodedResponse, as stated.

**Comment by driesvints** [comment]
Seems like a copy paste mistake indeed from the method below it. Would welcome a PR to adjust the comment! Thanks
