### ISSUE TITLE
Cannot assert logs when using logging within a before middleware

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/framework#52565]
### Laravel Version

11.21.0

### PHP Version

8.3.0

### Description

I have a before middleware that i'm using to log a service payload using laravel Logging system
When used via the web it works.
When i try to Log::shouldReceive('info')->... i get an error 

`Error: Call to a member function runningUnitTests() on null`

https://github.com/laravel/framework/blob/500f3eb8970ed2a0bf6c31d6db2f02932b46cd12/src/Illuminate/Log/LogManager.php#L632

### Steps To Reproduce

Within bootstrap.php

```
$middleware->alias([
    'log-service-request' => \App\Http\Middleware\LogServiceRequestMiddleware::class,
]);
```

Handle method of the middleware
```
public function handle(Request $request, Closure $next, string $logChannel): Response
    {
        Log::channel($logChannel)->info(
            json_encode($request->all()),
            [
                'url' => $request->fullUrl(),
            ]
        );

        return $next($request);
    }
```

Assign the middleware to a route

Run this test

```
    public function test_it_logs_the_amazon_request()
    {
        $this->withoutExceptionHandling();

        Log::partialMock()->shouldReceive('info')->once()
        ->with('What you logged');

        $this->post('your route url', []);
    }
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by shadoWalker89** [comment]
This is framework code, where it's trying to access method on null which is the Application instance

This is clearly a bug
