### ISSUE TITLE
BadMethodCallException: Method Illuminate\Support\Collection::select does not exist.

### ISSUE THREAD

**Issue by Lreus** [laravel/framework#52585]
### Laravel Version

10.38.1

### PHP Version

8.2.11

### Description

BadMethodCallException: Method Illuminate\Support\Collection::select does not exist.

However this method is documented in both [10.X](https://laravel.com/docs/10.x/collections#method-select) and [11.X](https://laravel.com/docs/11.x/collections#method-select) documentation

### Steps To Reproduce

$users = collect([
    ['name' => 'Taylor Otwell', 'role' => 'Developer', 'status' => 'active'],
    ['name' => 'Victoria Faith', 'role' => 'Researcher', 'status' => 'active'],
]);
 
$users->select(['name', 'role']);

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
