### ISSUE TITLE
Reference on the error text is reversed when incorrect reference class is passed

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/framework#52605]
### Laravel Version

11.21.0

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

I incorrectly set the parameter of the `withSchedule` method on the `bootstrap/app.php` to `Illuminate\Support\Facades\Schedule` instead of `Illuminate\Console\Scheduling\Schedule` and when running `php artisan` on the terminal shows incorrect class.

```bash
Argument #1 ($schedule) must be of type Illuminate\Support\Facades\Schedule, Illuminate\Console\Scheduling\Schedule given,
```
but shouldn't it display the error as 
```
Argument #1 ($schedule) must be of type Illuminate\Console\Scheduling\Schedule, Illuminate\Support\Facades\Schedule given,
```
![CleanShot 2024-08-30 at 14 01 42](https://github.com/user-attachments/assets/1a45541e-652b-41f9-8145-1a88bea473b7)

### Steps To Reproduce

1. Goto `bootstrap/app.php`
2. Add the `withSchedule()` method and set the parameter on the callback to use `\Illuminate\Support\Facades\Schedule` as shown below

```php
->withSchedule(function (\Illuminate\Support\Facades\Schedule $schedule) {
       
 })
```
3. Run `php artisan` on the terminal

**Comment by driesvints** [comment]
No the error is correct. You provide the wrong typehint but the given class is still the correct one.
