### ISSUE TITLE
IDE autocomplete does not work for Storage::disk('someDisk')->url('...')

### ISSUE THREAD

**Issue by Wulfheart** [laravel/framework#52617]
### Laravel Version

v11.21.0

### PHP Version

8.3.10

### Description

When using `Storage::disk('local')->u` the `->url('...')` method is not displayed in IDE autocompletion because it doesn't exist in the return type of `Storage::disk()`.

![image](https://github.com/user-attachments/assets/cc8c24b8-fe6c-4ffc-b5f1-a567dac3b560)

### Steps To Reproduce

```php
Storage::disk('someDisk')->url('...')
``` 

 https://github.com/laravel/framework/blob/b9cf7d3217732e9a0fa4f00e996b3f9cc5bf7abd/src/Illuminate/Support/Facades/Storage.php#L9
According to the docblocks in `Illuminate\Support\Facades\Storage` the disk method returns an instance of `Illuminate\Filesystem\Filesystem`. However, in `php artisan tinker` `Storage::disk('local')` returns `Illuminate\Filesystem\FilesystemAdapter` which has the url method. Unfortunately this is not reflected in the IDE.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

If you notice improper DocBlock, PHPStan, or IDE warnings while using Laravel, do not create a GitHub issue. Instead, please submit a pull request to fix the problem. Also see [our contribution guide](https://laravel.com/docs/contributions#bug-reports).

Thanks!

**Comment by Wulfheart** [comment]
Hey Dries, 
I don’t know how to fix this.
