### ISSUE TITLE
Laravel 10 password reset blade fails

### ISSUE THREAD

**Issue by programmin1** [laravel/framework#52635]
### Laravel Version

v10.48.20

### PHP Version

8.2.23

### Database Driver & Version

Mysql Ver 8.0.39-0ubuntu0.22.04.1

### Description

Password reset screen fails on Laravel 10:
BadMethodCallException
Method Illuminate\View\ComponentAttributeBag::extractPropNames does not exist.
for

vendor / laravel / framework / src / Illuminate / Mail / resources / views / html / button.blade.php

### Steps To Reproduce

Try to submit the password reset after setting back to laravel 10 from 11.

POST request to password/email fails.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by timacdonald** [comment]
For anyone else stumbling across this issue, I was able to resolve it by clearing the view cache.
