### ISSUE TITLE
__('Validation') returns an array instead of a a string

### ISSUE THREAD

**Issue by rabol** [laravel/framework#52642]
### Laravel Version

11.22.0

### PHP Version

8.3.10

### Description

Translation of the word Validation does not work:

in tinker, try this:

```echo __('Validation');```

and you will get this result:

```
 WARNING  Array to string conversion.
```

### Steps To Reproduce

new clean laravel app, open artisan tinker and execute this command:

```echo __('Validation');```

**Comment by crynobone** [comment]
The limitations has been described in the documentation: https://laravel.com/docs/11.x/localization#using-translation-strings-as-keys

**Comment by driesvints** [comment]
Please see many previous issues about this.
