### ISSUE TITLE
Eloquent Refresh() Returns All Columns Instead of Predefined Columns

### ISSUE THREAD

**Issue by anabeto93** [laravel/framework#52640]
### Laravel Version

11.x

### PHP Version

8.3

### Database Driver & Version

Sqlite

### Description

When dealing with a table that has many columns and you are selecting a model from DB, you have the option of specifying a list of columns you wish to select only, let's say `['first_name', 'last_name']`, but the table has other columns such as `id, email, password, address` and for the purposes of performance you choose only these. If at some point in the future (in the code), you decide to call `->refresh()` on that model instance, it is rehydrated with all other columns you didn't previously select.

The expected behaviour is that the `refresh()` method should return only the previously specified columns on this model instance and all related models instead of rehydrating everything.

### Steps To Reproduce

1. On a new laravel app, modify the user schema to include the following columns

    ```php
    Schema::create('users', function (Blueprint $table) {
        $table->id();
        $table->string('first_name');
        $table->string('last_name');
        $table->string('email');
        $table->string('password');
        $table->string('address')->nullable();
        $table->timestamps();
    });
    ```

2. Run the migration `php artisan migrate`

3. Seed the users with some sample data `User::factory()->count(4)->create();`

4. In a controller or route, select a model specifying only columns that you need.

    ```php
    $user = User::select(['first_name', 'last_name'])->first();
    ```
5. Now call `->refresh()` on that model instance and take a look at the result.

    ```php
        $user = User::select(['first_name', 'last_name'])->first();

        // Verify that only selected columns are loaded
        dd($user->toArray()); // Should only show first_name and last_name, uncomment this line to move to the next line

        $user->refresh();

        // Check the model after refresh
        dd($user->toArray()); // Will show all columns, including id, email, password, address
    ```

### Notes

Now consider the case where you may have have additional relationships, and for each of these related models, you specified some specific columns when you were loading them using the `with()` method for instance. If these related models also have multiple columns, then there's a chance this could significantly affect performance.

I created a repository to further explain this problem found here [https://github.com/anabeto93/Laravel-11-Refresh-Issue](https://github.com/anabeto93/Laravel-11-Refresh-Issue)

This is what the code is and I hope it explains it much futher

```php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('refresh', function () {
    $userRequiredFields = ['id', 'first_name', 'last_name']; // excluding email, password, address, email_verified_at, remember_token
    $orderFields = ['id', 'user_id', 'status']; // ignoring total, payment_type,
    $productFields = ['id', 'name',]; // ignoring description, price, stock,

    // Fetch the first user, with orders and products using the required fields
    $relatedQuery = [
        'orders' => function ($query) use ($orderFields) {
            $query->select($orderFields);
        },
        'orders.products' => function ($query) use ($productFields) {
            $query->select($productFields);
        },
    ];

    $user = App\Models\User::with($relatedQuery)->first($userRequiredFields);

    // dd(json_encode([
    //     'efficient_query' => $user->toArray(), // comment this out if you want to see the difference
    // ]));

    // Sample Response from the above
    /**
     * {"efficient_query":{"id":1,"first_name":"Test","last_name":"User","orders":[{"id":1,"user_id":1,"status":"cancelled","products":[{"id":3,"name":"qui","pivot":{"order_id":1,"product_id":3,"quantity":1,"price":56,"created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}}]},{"id":2,"user_id":1,"status":"cancelled","products":[{"id":4,"name":"laboriosam","pivot":{"order_id":2,"product_id":4,"quantity":2,"price":20,"created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}},{"id":5,"name":"aspernatur","pivot":{"order_id":2,"product_id":5,"quantity":2,"price":20,"created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}}]},{"id":3,"user_id":1,"status":"completed","products":[{"id":1,"name":"similique","pivot":{"order_id":3,"product_id":1,"quantity":5,"price":23,"created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}},{"id":2,"name":"consectetur","pivot":{"order_id":3,"product_id":2,"quantity":5,"price":23,"created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}}]}]}}
     */

     // Please Ignore Trying to Use fresh()->load(), it is not the same as with()
     //Now call refresh on this and observe a difference
     dd([
        json_encode(['refreshed_query' => $user->refresh()->toArray()]),
     ]);

     // Sample Response from the above
     /**
      * {"refreshed_query":{"id":1,"first_name":"Test","last_name":"User","email":"test@example.com","email_verified_at":"2024-09-04T16:11:37.000000Z","address":"82450 Alejandrin Shoals\nHoppeburgh, OH 72654","created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z","orders":[{"id":1,"user_id":1,"status":"cancelled","total":1267.38,"payment_type":"bank_transfer","created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"},{"id":2,"user_id":1,"status":"cancelled","total":916.14,"payment_type":"paypal","created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"},{"id":3,"user_id":1,"status":"completed","total":1255.9,"payment_type":"bank_transfer","created_at":"2024-09-04T16:11:37.000000Z","updated_at":"2024-09-04T16:11:37.000000Z"}]}}
      */

      // The refreshed_query has all the fields in the user model, and the orders have all the fields in the order model, but the products are missing the fields in the product model
    return response()->json(['message' => 'Refreshed']);
});
```

#### Sample Responses Screenshots
1. Fetching User with Related Order and Products
    ![Screenshot from 2024-09-04 16-24-56](https://github.com/user-attachments/assets/44cc84d3-8229-4aaf-9d12-44c2ee596951)
2. When It Is Refreshed
    ![Screenshot from 2024-09-04 16-26-14](https://github.com/user-attachments/assets/32a96308-7daf-4741-bff6-89a83768be3a)

**Comment by Naimul007A** [comment]
Please read this Carefully
https://laravel.com/docs/11.x/eloquent#refreshing-models

**Comment by Naimul007A** [comment]
https://laravel.com/docs/11.x/eloquent#refreshing-models
"Maybe you will use 'fresh'."

**Comment by anabeto93** [comment]
After @Naimul007A comments, I decided that I should create repo to further explain this problem. This repository can be found here https://github.com/anabeto93/Laravel-11-Refresh-Issue

**Comment by driesvints** [comment]
This unfortunately isn't how `refresh` works. `refresh` will always load all attributes because of this `firstOrFail` call:

https://github.com/laravel/framework/blob/769f00ba71de3b3cbbb271e9f34a019b584982c9/src/Illuminate/Database/Eloquent/Model.php#L1730

You'll need to again run `User::select(['first_name', 'last_name'])->first();` in your case.
