### ISSUE TITLE
Cast "hashed" does not work in laravel tinker in updating operation

### ISSUE THREAD

**Issue by VitaliyGromov** [laravel/framework#52652]
### Laravel Version

11.0.8

### PHP Version

8.3.9

### Database Driver & Version

PostgreSQL 16.2

### Description

I have cast "hashed" for field password in User model.

![image](https://github.com/user-attachments/assets/c09ba808-f90c-418b-ba66-95e81a431ace)

    
When i create user in controller or in tinker, i have correct hashed value in database. 
    
![image](https://github.com/user-attachments/assets/a0a348b8-02bc-448e-89f2-28a3218ab886)
But when i use tinker for updating this password, i have unhashed value in database
![image](https://github.com/user-attachments/assets/b2485cd6-d7f4-4447-8bbd-e38089d9bc86)

### Steps To Reproduce

1) Add hashed cast for password field in the User model
2) Create user
3) Open tinker
4) Update password for user via tinker

**Comment by Jubeki** [comment]
What you are doing is a database query, which does not use the casts from Eloquent and also doesn't fire any model related events.

To have model casts and events active you would need to do, first query the data and then perform the update in PHP and not directly in the database:
```php
User::where('email', 'ivan@ivanov.com')->get()->update([
    'password' => 'anotherPassword'
])

// or 
User::where('email', 'ivan@ivanov.com')->get()->each->update([
    'password' => 'anotherPassword'
])

// or
User::where('email', 'ivan@ivanov.com')->first()->update([
    'password' => 'anotherPassword'
])
```

**Comment by VitaliyGromov** [comment]
Thanks
