### ISSUE TITLE
Issue with new chaperone feature when utilizing "pluck"

### ISSUE THREAD

**Issue by jrking4** [laravel/framework#52660]
### Laravel Version

11.22

### PHP Version

8.3

### Description
This relates to the new feature #51582 
There seems to be an issue when utilizing pluck on a model relationship. An error occurs on this line in

```php
protected function applyInverseRelationToCollection($models, ?Model $parent = null)
    {
        $parent ??= $this->getParent();

        foreach ($models as $model) { 
            $this->applyInverseRelationToModel($model, $parent);
        }

        return $models;
    }
``` 
src/Illuminate/Database/Eloquent/Relations/Concerns/SupportsInverseRelations.php

The model being passed to applyInverseRelationToModel is an integer and not the full model.

### Steps To Reproduce

in this case I am trying to query and get the "Comment" ids from a Post model
```php
$BlogCommentIDs = $Post->Comments()->pluck( 'id' )->all();
```

the relationship in the Post Model
```php
 /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function Comments() {
        return $this->hasMany( Comment::class, 'post_id' )->orderBy( 'comment_order', 'asc' )->chaperone('Post');
    }
```

the inverse relationship in the Comment Model
```php
/**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function Post() {
        return $this->belongsTo( Post::class, 'post_id' );
    }
```

in theory you can fix what im trying to do by changing the line to, but that shouldnt be necessary by the end-developer
```php
$BlogCommentIDs = $Post->Comments()->withoutChaperone()->pluck( 'id' )->all();
```

**Comment by AndrewMast** [comment]
I'm also running into an issue with `$this->hasMany(Child::class)->chaperone('parent')` and then having `$touches = ['parent']` on the `Child` class. It causes an infinite loop. I've commented out one or the other and it fixes the issue. I'm still trying to narrow it to exactly what is going wrong, but I thought I should add a comment here before I open an issue.

**Comment by driesvints** [comment]
@samlev could you maybe look into this one?

**Comment by samlev** [comment]
@driesvints sure thing.

The first issue is an easy fix - just skip hydration if the child isn't a model:

```php
foreach ($models as $model) { 
    $model instanceof Model && $this->applyInverseRelationToModel($model, $parent);
}
```

The second one should be relatively straightforward, too, depending on where `$touches` is referenced. If it's within the model class itself, then it's easy enough to wrap `$this->withoutRecursion()` around it like what happens in `->push()`. If it's in a trait that Model uses then we can still use it, we just have to be aware of breaking tests that expect the trait to be stand-alone. If it happens in another class entirely (like `Relation`), then the `PreventsCircularRecursion` trait itself is completely class agnostic - it can go into anything, and will still work just fine.

I'll see if I can get something up early next week, of if anyone else wants a crack at it, just ping me for review.

**Comment by samlev** [comment]
Because I can't help myself... It looks like `touchOwners()` in `HasRelationships` will be an easy place to wrap in `withoutRecursion()`, the time consuming part will just be writing tests for it.

**Comment by AndrewMast** [comment]
@samlev I can confirm that `withoutRecursion()` does solve my issues. Thanks for investigating this, I was at the end of my rope last night.

I wouldn't mind making a PR, but I have no idea where to put the tests. Surely not in `DatabaseEloquentInverseRelationTest.php`, right? I can't seem to find where the `touchOwners()` is tested.

**Comment by samlev** [comment]
@driesvints maybe it would actually be worth pulling `PreventsCircularRecursion` out of being a model trait and making is a standalone service/singleton so that it's more useful throughout the framework and in userland (similar to `once()`)

**Comment by samlev** [comment]
@AndrewMast / @driesvints I got some time, and got a PR together which resolves this (and some other things)
