### ISSUE TITLE
Extra attributes are added to html element

### ISSUE THREAD

**Issue by vascocarreira** [laravel/framework#52663]
### Laravel Version

11.22

### PHP Version

8.3.11

### Description

All attributes are added when attributes merge is invoked

### Steps To Reproduce

According to Laravel's documentation in https://laravel.com/docs/11.x/blade#default-merged-attributes, if the attributes in a blade component are set like this:
\<div {{ $attributes->merge(['class' => 'alert alert-'.$type]) }}>
    {{ $message }}
\</div>

And then we invoke the component like this:
\<x-alert type="error" :message="$message" class="mb-4"/>

The end result should be this:
\<div class="alert alert-error mb-4">
    \
\</div>

But... That's not what I'm getting.
All attributes passed in the blade component are being added to the html element where I'm calling the attributes merge.
Please, check the following screenshot.

![Screenshot from 2024-09-05 18-42-44](https://github.com/user-attachments/assets/6b1662bc-9dee-4cb0-8cf0-cede7f637fed)

Am I doing something wrong or missing something?
Or is this a real issue?

Thanks in advance.
Regards.

**Comment by calebdw** [comment]
This is the expected behaviour

**Comment by vascocarreira** [comment]
@calebdw , if this is the expected behavior, I kindly ask you to update the documentation since it does not reflect the true final rendered HTML of the component.

Regarding this issue, is there a more efficient way to merge just the classes than the following one?
class="alert alert-{{ $type }} {{ $class ?? '' }}"

**Comment by calebdw** [comment]
> I kindly ask you to update the documentation since it does not reflect the true final rendered HTML of the component.

You can submit a PR if you like, but perhaps there were no other attributes in the AttributeBag?

> Regarding this issue, is there a more efficient way to merge just the classes than the following one?

You can use the [`@class` directive](https://laravel.com/docs/11.x/blade#conditional-classes)

**Comment by claspina** [comment]
> This is the expected behaviour

According to documentation, this is not the expected behavior 

![doc](https://github.com/user-attachments/assets/63686668-ce48-4e94-bed3-5e783cda3b51)

**Comment by calebdw** [comment]
@claspina, your red box / arrow has nothing to do with the question at hand.

Dumping the AttributeBag in a blade template `<div {{ $attribute }}>` *dumps all the attributes in the bag onto the element* (including when using the merge: `<div {{ $attribute->merge(...) }}>`).

**Comment by calebdw** [comment]
I believe using `@props(['message'])` will take the `$message` out of the AttributeBag:

```html
@props(['message'])

<div {{ $attributes }}>
    {{ $message }}
</div>
```

**Comment by vascocarreira** [comment]
@calebdw , I think you did not understand what I asked.

I have this component:
<div class="alert alert-{{ $type }}" role="alert">

But I want to be able to add more classes if needed like, for example, mb-4.
<x-alert class="mb-4"/>

So, in order to be able to add that extra class, I'm doing it like this in the component:
<div class="alert alert-{{ $type }} {{ $class ?? '' }}" role="alert">

Is there a more efficient way to do this (merging classes)?
The @class directive does not seem to do the trick.

**Comment by calebdw** [comment]
> But I want to be able to add more classes if needed like, for example, mb-4.

There's nothing wrong with what you originally had:

```html
<div {{ $attributes->merge(['class' => 'alert alert-'.$type]) }}>
```


> To check for directives like "required" inside a blade component, I'm doing it like this.

Use `@required($required)`

**Comment by vascocarreira** [comment]
> There's nothing wrong with what you originally had:

Yes, but in order to not add the other attributes to the html component, I have to declare them as props in the component.
I get it, now.

I think this detail should be in the docs example, like so:

```
@props([
    'message',
    'type'
])

<div {{ $attributes->merge(['class' => 'alert alert-'.$type]) }}>
    {{ $message }}
</div>
```

Thank you very much for clearing up my doubts.
I'm closing this ticket now.
Regards.

**Comment by driesvints** [comment]
Thanks for helping out here @calebdw
