### ISSUE TITLE
Illuminate/Support package does not declare Laravel/SerializeClosure as a Dependency

### ISSUE THREAD

**Issue by craigrileyuk** [laravel/framework#52670]
### Laravel Version

11.22

### PHP Version

8.3

### Description

I use some Illuminate packages without the Laravel/Framework package in a project and I've started getting errors for "Error: Class &quot;Laravel\SerializableClosure\Support\ReflectionClosure&quot; not found in file /path/to/project/vendor/illuminate/support/Onceable.php on line 66"

Checking the dependency list for the Support package in `composer.json`, I can't see "laravel/serializable-closure" package listed there which is causing the error when it's not listed elsewhere (i.e. in the main laravel/framework package where it is listed).

### Steps To Reproduce

Install 'Illuminate/Support' by itself and use a function that calls the "Onceable" class.

**Comment by driesvints** [comment]
Thanks for reporting this. I sent in a PR to add this to the package's suggest list: https://github.com/laravel/framework/pull/52673

**Comment by winds1983** [comment]
I get same error:
`PHP Fatal error:  Uncaught Error: Class "Laravel\SerializableClosure\Support\ReflectionClosure" not found in vendor/illuminate/support/Onceable.php:66
`
How to fix this? @driesvints

**Comment by CoderJoeW** [comment]
I also am experiencing the same issue after upgrading to 11.33.2
