### ISSUE TITLE
Inconsistent Model checks on find() methods throughout the framework

### ISSUE THREAD

**Issue by Andyuu** [laravel/framework#52682]
### Laravel Version

11.22.0

### PHP Version

8.2

### Description

This commit: https://github.com/laravel/framework/commit/353442d80722e8862c3f140b7e34c27578e89f7d introduced a fix on BelongsToMany which allowed a Model to be passed as an ID, where the primary key would be pulled out for the query.

```
        if (! $id instanceof Model && (is_array($id) || $id instanceof Arrayable)) {
            return $this->findMany($id, $columns);
        }
```

However, this fix was not applied to the identical methods on the eloquent Builder or HasOneOrManyThrough classes, which caused a very messed up SQL query when passing a model to these methods.

```
        if (is_array($id) || $id instanceof Arrayable) {
            return $this->findMany($id, $columns);
        }
```

Because the model is Arrayable, it does some funky stuff along these lines

![image](https://github.com/user-attachments/assets/3680e902-35cc-4708-a1b6-75c8f7b5dee4)

There may be other places that are missing this check, but that's what I found from a brief search. There is no value in the current functionality and the lack consistency does not meet developer expectations, so I would not consider this a breaking change.

### Steps To Reproduce

User::find($user)

The use case of this is to refresh the model whilst keeping global scopes applied (to determine if the user is still accessible to the current user after some changes.)

**Comment by driesvints** [comment]
Heya, this change was made 4 years ago. If you want to send a follow up PR feel free to send one in 👍
