### ISSUE TITLE
__toString() method causes conversion error in Illuminate\Validation

### ISSUE THREAD

**Issue by FelipeMenezesDM** [laravel/framework#52700]
### Laravel Version

10.0

### PHP Version

8.1

### Database Driver & Version

MySQL

### Description

When using the following validation:

```
Rule::exists('permissions', 'uuid')->where(['disabled_at' => null, 'client_id' => $clientId])
```

A conversion error occurs when the value does not satisfy the rule, causing the system to return an error along with a stack trace.

This issue arises because the `formatWheres()` method in the Illuminate\Validation\Rules\DatabaseRule trait does not correctly process the `$this->wheres` attribute when multiple conditions are present.
![image](https://github.com/user-attachments/assets/48821d34-de2d-440b-b68b-2da797b5c8f1)

Sorry for my bad English 🫤

### Steps To Reproduce

To reproduce, simply execute the __toString() method on a Rule::exists() object that contains a where clause in array format:

```
$rule = Rule::exists('permissions', 'uuid')->where(['disabled_at' => null, 'client_id' => $clientId]);
$rule->__toString();
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
