### ISSUE TITLE
Conditional statements for extra fields in Auth::attempt

### ISSUE THREAD

**Issue by srph** [laravel/framework#5270]
```php
$auth = Auth::attempt(array(
    'email'     => $email,
    'password'  => $password,
    // This feature:
    'level'    => array('>', 99)
), $remember);
```
This could make code a little bit cleaner and remove unnecessary lines (to perform the conditions) in situations like:

When I'd like to check if there is an existing user with provided ```email``` and ```password``` with a ```level``` of higher than ```n```. Currently, I still have to perform an *extra* separate query just to check if a user with the given credential and given condition exists.

```php
try {
    $user = User::where('email', $email)->where('level', '>', 99)->firstOrFail();
} catch(...\ModelNotFoundException $e) {
    // Do something
}

if ( Auth::attempt(array('email' => $email, 'password' => $password) ) {
    // ...
}
```

* Note: I haven't checked if there has already been a solution to this problem or if an alternative exists.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by srph** [comment]
Alright :+1:
