### ISSUE TITLE
$this->replace() removes models injected to the request by custom middlewares

### ISSUE THREAD

**Issue by ISNewton** [laravel/framework#52711]
### Laravel Version

10.48.20

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0.37

### Description

Using $this->replace() to update a request property in `passedValidation` in Laravel form request:
```
    public function passedValidation()
    {
        if ($someCondition) {
            $this->replace(['count' => 1]);
        }
    }

```

The property is replaced as expected , but models injected to the request is deleted as well. Middleware example:
```
class MyCustomMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!$request->hasHeader('x-institution-id')) return apiError(api('x-institution-id header is required'));

        $institution = Institution::findOrFail($request->header('x-institution-id'));
        
        $request['institution'] = $institution;

        return $next($request);
    }
}

```

 The `$institution` property injected by `MyCustomMiddleware` is null when accessed in the controller. However , Everything it isn't when not using `$this->replace()` in Laravel form request.

### Steps To Reproduce

- Create custom middleware that injects models to the request body.
- Create a form request and replace a property within the `passedValidation` method.
- Access the injected property from a controller, It will be null.

**Comment by rodrigopedra** [comment]
Internally, `Illuminate\Http\Request` uses an `Symfony\Component\HttpFoundation\InputBag` to store properties set by array access, or with the `replace` and other methods.

Replace will "replace" all such modifications to an `InputBag`:

```php
https://github.com/symfony/http-foundation/blob/92ab8d3773167ac37acfc172e6bbc537a5a415ae/InputBag.php#L47-L51
```

It first resets the `$parameters` storage, and then adds the new values.

Change the `replace` usage with `merge`:

```php
public function passedValidation()
{
    if ($someCondition) {
        $this->merge(['count' => 1]);
    }
}
```

This will overwrite existing values, without clearing the storage beforehand.

**Comment by rodrigopedra** [comment]
Internally, `Illuminate\Http\Request` uses an `Symfony\Component\HttpFoundation\InputBag` to store properties set by array access, or with the `replace` and other methods.

Replace will "replace" all such modifications to an `InputBag`:

https://github.com/symfony/http-foundation/blob/92ab8d3773167ac37acfc172e6bbc537a5a415ae/InputBag.php#L47-L51


It first resets the `$parameters` storage, and then adds the new values.

Change the `replace` usage with `merge`:

```php
public function passedValidation()
{
    if ($someCondition) {
        $this->merge(['count' => 1]);
    }
}
```

This will overwrite existing values, without clearing the storage beforehand.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
