### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ynsbleng** [laravel/framework#52731]
### Laravel Version

11.22.0

### PHP Version

8.2.23

### Database Driver & Version

MySQL 8.0.39

### Description

If I do:

$author->books()->where("category", "Fantasy")->orWhere("price", "<=", "9.99");

I expect the query to return books related to the author, however it won't be the case as the resulted sql query will be something like:

`select * from books where books.author = ? and books.category = ? or books.price <= ?`

This seems odd, when using relationships eloquent builder must automatically add parenthesis without the need for the user to wrap their conditions inside a where clause:

`$author->books()->where(function($query){ return $query->where("category", "Fantasy")->orWhere("price", "<=", "9.99") });`

Also it happens to me just this morning that:

`$model->get()->each->delete();`

Was soft deleting all models, not just the model in question,  I had this along with many lines to force triggering observers and I accidentally made a bunch replace  where the model as well had that `->get->each->`, while it seems wrong to have this in the first place and `$model->delete()` was enough, but the behavior was really odd, and hopefully I was using soft deletes otherwise the issue could be much worse.

### Steps To Reproduce

`$author->books()->where("category", "Fantasy")->orWhere("price", "<=", "9.99");`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
