### ISSUE TITLE
Redirect `withErrors` cannot be tested with `assertSessionHasErrors`

### ISSUE THREAD

**Issue by tadhgboyle** [laravel/framework#52733]
### Laravel Version

11.22.0

### PHP Version

8.3.8

### Description

In a controller, I am redirecting the user back if an error occurred, using `redirect()->back()->withErrors('My error message');`.
In the controllers test, I want to assert that an error was raised. I went for `assertSessionHasErrors('My error message');` (given the naming of this seems to imply it would work seamlessly with `withErrors`) but this does not work and instead the assertion fails.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/5d0a07de-6d11-4cd2-b670-b9b044dbc1e5">

Dumping the `$errors` ([Laravel framework source](https://github.com/laravel/framework/blob/2f83567c1c2e650ee18a712d677f693bd7fc5fef/src/Illuminate/Testing/TestResponse.php#L1400)) shows that the expected error does indeed appear in the error bag:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/390a496b-9213-452e-9c7b-b984b3fd56eb">

### Steps To Reproduce

Controller:
```php
class ExampleController
{
	public function __invoke()
	{
		if ($someCondition) {
			return redirect()->back()->withErrors('That action is not allowed');
		}

		// ...
	}
}
```

Test:
```php
class ExampleControllerTest extends TestCase
{
	public function test_error_is_shown_if_some_condition_is_true()
	{
		$this->post(route('example_controller'))
			->assertRedirect()
			->assertSessionHasErrors('That action is not allowed');
	}
}
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tadhgboyle** [comment]
Thanks for the reply. 

Can you please elaborate as to how this isn't a bug?

If this is intentional behaviour, it's super unintuitive given the names of the methods involved.
