### ISSUE TITLE
Array offset error when using the Concurrency facade

### ISSUE THREAD

**Issue by heychazza** [laravel/framework#52752]
### Laravel Version

11.23.2

### PHP Version

8.3.11

### Database Driver & Version

SQLite

### Description

The `Concurrency` facade returns a "Trying to access array offset on null" error, when attempting to use the `run` method. This error seems to be at `$result['successful']` within the ProcessDriver class.

From some testing I've done myself it still seems that Laravel is unable to find the php binary from Herd, as `(new PhpExecutableFinder)->find(false)` returns `false`.

### Steps To Reproduce

Create a route like the following:

``` php
Route::get('/concurrency', function () {
    [$test] = Concurrency::run([
        fn () => DB::table('users')->get(),
    ]);

    return response()->json([
        'test' => $test,
    ]);
});
```

Laravel will error out at the Concurrency::run line.

**Comment by heychazza** [comment]
Hey @crynobone, seems the issue still exists when using Laravel Herd.

Latest Herd (just updated), Laravel 11.23.4, PHP 8.3.11

![CleanShot 2024-09-12 at 5  04 10@2x](https://github.com/user-attachments/assets/ffa340ca-1324-42d1-989f-4c93285a1126)

**Comment by brandonaaskov** [comment]
For future travelers, if you're using the latest version of Laravel, the issue isn't Herd. Trying using the fork driver as described here: https://laravel.com/docs/11.x/concurrency#how-it-works

**Comment by misodrobny** [comment]
> For future travelers, if you're using the latest version of Laravel, the issue isn't Herd. Trying using the fork driver as described here: https://laravel.com/docs/11.x/concurrency#how-it-works

The problem is fork is only supported in CLI. Do we have a solution without using fork?

**Comment by misodrobny** [comment]
> PR #52744 should fix this issue.

I still have this issue in Laravel 11.30.0

**Comment by crynobone** [comment]
@misodrobny please submit new bug report with reproducing code instead of commenting on closed issue.

**Comment by acid23m** [comment]
I still have this issue in Laravel 12. But there is no errors while debugging (xdebug 3).
