### ISSUE TITLE
proc_open(): posix_spawn() failed error with the Concurrency facade

### ISSUE THREAD

**Issue by heychazza** [laravel/framework#52767]
### Laravel Version

11.23.4

### PHP Version

8.3.11

### Database Driver & Version

N/A

### Description

When using the `Concurrency` facade, specifically the `run` method, the following error is triggered:
> `The command "'php' 'artisan' 'invoke-serialized-closure'" failed. Working directory: /Users/charlie/Development/Sites/example Error: proc_open(): posix_spawn() failed: No such file or directory`

For context, this **only** errors when going through Laravel Herd. If I run this through `php artisan serve` the code runs fine.

I have even tried a re-install of Herd and the same error.

Apologies for sending through another GitHub issue, but I know this is still in beta so I'd love to help where I can.

### Steps To Reproduce

Create an endpoint like the following:
``` php
Route::get('/concurrency', function () {
    [$first, $second] = Concurrency::run([
        fn () => 1+1,
        fn () => 2+2,
    ]);

    return response()->json([
        'first' => $first,
        'second' => $second,
    ]);
});
```

If you go to `<site>.test/concurrency` (running through Herd) you'll hit that error.

Now do `php artisan serve` and go to `127.0.0.1:8000/concurrency` and the code will run fine.

**Comment by heychazza** [comment]
Further investigation it seems like `PHP_BINARY` returns the fpm binary when running through Herd, while the artisan serve shows the normal binary.

Adding this code fixed it for me:
``` php
putenv('PHP_BINARY='.Str::replace('-fpm', '', PHP_BINARY));
```

**Comment by crynobone** [comment]
@heychazza Might be worth it to submit this issue to https://github.com/beyondcode/herd-community/issues

**Comment by heychazza** [comment]
> @heychazza Might be worth it to submit this issue to https://github.com/beyondcode/herd-community/issues

Ah my bad, I'll post it there

**Comment by mpociot** [comment]
I opened a [PR on the Symfony codebase](https://github.com/symfony/symfony/pull/58258) as the PhpExecutableFinder does not detect Herd's PHP binary properly.

**Comment by crynobone** [comment]
@mpociot Does this PR solved the issue? https://github.com/laravel/framework/pull/52791

**Comment by mpociot** [comment]
@crynobone I'm getting errors when trying to use that PR:

<img width="1469" alt="image" src="https://github.com/user-attachments/assets/e4d40b0d-848e-4c7d-ba3e-edc0ca39358c">

**Comment by crynobone** [comment]
What's a good way to replicate scenario where we need to depends on `HERD_HOME`?

![CleanShot 2024-09-17 at 16 01 36@2x](https://github.com/user-attachments/assets/50c04944-e9e6-4c84-946f-a0f78198c735)
![CleanShot 2024-09-17 at 16 01 56@2x](https://github.com/user-attachments/assets/383d03c7-61b8-417f-8bdd-8d9630bcf6b1)

I seems to be able to get the correct binary even without the changes

**Comment by crynobone** [comment]
@mpociot Should be fixed now. It might be best to solve this for now until the release of Symfony 7.2 in November 2024

**Comment by crynobone** [comment]
PR #52791 has been merged and pending release
