### ISSUE TITLE
Using @vite in a view that is rendered but a file response is sent back causes an exception

### ISSUE THREAD

**Issue by likeadeckofcards** [laravel/framework#52784]
### Laravel Version

11.22.0

### PHP Version

8.2.23

### Description

If you render a view in a request for building a file such as a pdf but return the pdf file you will trigger the following exception:

```
Call to undefined method Symfony\\Component\\HttpFoundation\\BinaryFileResponse::header() at /project/vendor/laravel/framework/src/Illuminate/Http/Middleware/AddLinkHeadersForPreloadedAssets.php:21)
```

The issue is that @vite compiles a list of urls to preload and the middleware will try to attach them to the response. It seems like the middleware should check what type of response it has before attempting to apply the header. I believe any of the ResponseFactory methods that return Symfony classes instead of Illuminate classes will also have this problem.

### Steps To Reproduce

1. Use either jetstream/breeze to setup a new project (confirm for the inertia stacks)
2. Add a route to the web routes that renders a view containing `@vite` but returns a BinaryFileResponse 
    `return response()->file();` or `return response()->file();`
3. Run `npm run build` (`npm run hot` does not compile the list of preloaded urls)
4. Try to download the file

**Comment by likeadeckofcards** [comment]
One immediate work around is to use `<link href="{{Vite::asset()}}"/>` in the view instead of `@vite()`

**Comment by timacdonald** [comment]
Got a PR up to address this one. Will close this and we can follow along in the PR: https://github.com/laravel/framework/pull/52789
