### ISSUE TITLE
Add whereRegexp on Query Builder

### ISSUE THREAD

**Issue by endel** [laravel/framework#5279]
It would be useful to have `whereRegexp` function on Query\Builder.

- [Postgres](http://www.postgresql.org/docs/9.0/static/functions-matching.html) supports it by `regexp_matches ` function.
- [MySQL](http://dev.mysql.com/doc/refman/5.1/en/regexp.html#operator_regexp) and [SQLite](http://www.sqlite.org/lang_expr.html) supports it by REGEXP operator.
- SqlServer doesn't support it, as of my searches.

The advantage of this abstraction are more portable queries.

**Comment by GrahamCampbell** [comment]
This appears to be implemented.
