### ISSUE TITLE
\Illuminate\Database\Eloquent\Concerns\PreventsCircularRecursion use \Illuminate\Support\Onceable who has a laravel dependency

### ISSUE THREAD

**Issue by alepieser** [laravel/framework#52828]
### Laravel Version

11.22.0

### PHP Version

8.3.0

### Description

Hello,

On different projects, we are using eloquent as standalone package. 
Everything was working well since the release v11.22.0.

In this release, a refactoring was done and introduce a new trait Eloquent/Concerns/PreventsCircularRecursion.php.
This trait is using the class Onceable from package Support

```php
$onceable = Onceable::tryFromTrace($trace, $callback);
```

The class Onceable is using use `\Laravel\SerializableClosure\Support\ReflectionClosure`.
As we don't have laravel as dependency, we cannot upgrade illuminate/database depdendency.

Do you think that there is a chance to solve this issue ?

Sorry if I didn't write at the right place to report this issue.

Thanks

### Steps To Reproduce

You can take look on line 6 file of Onceable.php

**Comment by crynobone** [comment]
Shouldn't you be able to just run `composer require "laravel/serializable-closure:^1.3"`?

**Comment by alepieser** [comment]
Thanks for your reply. I didn't know it was a standalone package. 
I just tested and it solved the issue.

However, what do you think about to update the requirement of illuminate/support to include it ?

**Comment by crynobone** [comment]
It is already suggested in `illuminate/support`: https://packagist.org/packages/illuminate/support

**Comment by alepieser** [comment]
Ah ok ! Sorry I didn't check that.

What about this time to add it in illuminate/database ? Because it's this package who is using the once function

**Comment by samlev** [comment]
I'm responsible for `PreventsCircularRecursion`, but I've _just now_ published a PR that deprecates it: #52865
