### ISSUE TITLE
Concurrency - can't set non-public fields in constructor

### ISSUE THREAD

**Issue by xHeaven** [laravel/framework#52829]
### Laravel Version

11.23.5

### PHP Version

8.3.10

### Database Driver & Version

-

### Description

Laravel's Concurrency facade throws a serialization exception if I want to set a non-public (private or protected) field in a class' constructor.
It does not have any issue with public properties though. See the steps to reproduce below.

Is this something that can be resolved, or are we required to implement alternative methods, such as assigning values from other methods rather than directly from the constructor?

### Steps To Reproduce

Create a class that like this:
```php
class Foo
{
    // Create a protected or private property
    private string $expensive;

    public function __construct()
    {
        // Try to set the value in the constructor
        $this->expensive = 'hello world';
    }

    public function bar(): string
    {
        return $this->expensive;
    }
}
```

Use the class:
```php
$foo = new Foo;

[$bar] = Concurrency::run([
    fn () => $foo->bar(),
]);
```

Instead of getting back the string `"hello world"` in `$bar`, you will get a serialization exception, something like this: `unserialize(): Error at offset 157 of 277 bytes`.

**Comment by crynobone** [comment]
You should implement `Serializable` the handle this: https://www.php.net/manual/en/class.serializable.php

**Comment by xHeaven** [comment]
Thanks!

If anyone else comes across this issue in the future, note that starting from PHP 8.1, the Serializable interface has been deprecated. It is recommended to implement the __serialize and __unserialize methods instead.
