### ISSUE TITLE
Cannot run Concurrency with session driver `dynamodb`

### ISSUE THREAD

**Issue by emiliopedrollo** [laravel/framework#52833]
### Laravel Version

11.23.5

### PHP Version

8.3.11

### Database Driver & Version

PostgreSQL 16.3 on alpine linux (docker)

### Description

Cannot execute `Concurrency::run()` while having session driver set as DynamoDB. 

Got the following `RuntimeException`: "Instances of Aws\DynamoDB\DynamoDbClient cannot be serialized. The exception is thrown on `Aws\AwsClient@__sleep()` which is called by `Laravel\SerializableClosure\Serializers\Signed@__serialize`:

```
#0 [internal function]: Aws\AwsClient->__sleep()
#1 /var/www/api/vendor/laravel/serializable-closure/src/Serializers/Signed.php(68): serialize(Object(Laravel\SerializableClosure\Serializers\Native))
#2 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__serialize()
#3 /var/www/api/vendor/laravel/framework/src/Illuminate/Concurrency/ProcessDriver.php(35): serialize(Object(Laravel\SerializableClosure\SerializableClosure))
#4 [internal function]: Illuminate\Concurrency\ProcessDriver->Illuminate\Concurrency\{closure}(Object(Illuminate\Process\Pool))
#5 /var/www/api/vendor/laravel/framework/src/Illuminate/Process/Pool.php(68): call_user_func(Object(Closure), Object(Illuminate\Process\Pool))
#6 /var/www/api/vendor/laravel/framework/src/Illuminate/Concurrency/ProcessDriver.php(42): Illuminate\Process\Pool->start()
#7 /var/www/api/vendor/laravel/framework/src/Illuminate/Support/MultipleInstanceManager.php(226): Illuminate\Concurrency\ProcessDriver->run(Array)
#8 /var/www/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(358): Illuminate\Support\MultipleInstanceManager->__call('run', Array)
#9 /var/www/api/app/Http/Controllers/v2/SearchController.php(264): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#10 /var/www/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\v2\FarmController->internalSearch(Object(App\Http\Searches\SearchRequest))
```

### Steps To Reproduce

1. Create a controller with a method containing some concurrency code like provided on the doc page:

```php
use Illuminate\Support\Facades\Concurrency;
use Illuminate\Support\Facades\DB;

public function __invoke() {
 
  [$userCount, $orderCount] = Concurrency::run([
      fn () => DB::table('users')->count(),
      fn () => DB::table('orders')->count(),
  ]);

  return ['users' => $userCount, 'orders' => $orderCount ];
}
```

2. Define a route to access the new controller.

3. Setup session driver for dynamodb on `config/session.php`:

```php

return [
    \\ ...
    'session' => 'dynamodb'
    \\ ...
]

```

4. Start server:

```shell
php artisan serve
```

5. Access the route.

**Comment by crynobone** [comment]
There nothing here that would indicate Concurrency need to serialize session data.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by emiliopedrollo** [comment]
While creating this repo I found out that the issue really is passing a request variable into a concurrent closure while using DyanmoDB. I'll close this issue and work on a new one with better description and more details.
