### ISSUE TITLE
Concurrency process crashes after 60 seconds

### ISSUE THREAD

**Issue by clementbirkle** [laravel/framework#52837]
### Laravel Version

11.23.5

### PHP Version

8.1

### Description

When a task takes more than 60 seconds, `Concurrency` throws this error: `The process "'/usr/local/bin/php' 'artisan' 'invoke-serialized-closure'" exceeded the timeout of 60 seconds.`

It seems the issue comes from this line:https://github.com/laravel/framework/blob/11.x/src/Illuminate/Process/PendingProcess.php#L44

I haven't found a solution to change this timeout, such as:

```php
$results = Concurrency::timeout(500)->run([
    function () {
        sleep(65);
        return 'done';
    }
]);
```

### Steps To Reproduce

Run

```php
use Illuminate\Support\Facades\Concurrency;

$results = Concurrency::run([
    function () {
        sleep(65);
        return 'done';
    }
]);
```

**Comment by crynobone** [comment]
Shouldn't you set idle timeout here since `sleep(65)` would cause the command to not print any output for 65 seconds?

**Comment by clementbirkle** [comment]
Thank you, @crynobone, for your reply. How can I set the idle timeout?

For instance, with the `Spatie Async` package, I can define a timeout like this: https://github.com/spatie/async?tab=readme-ov-file#pool-configuration

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by clementbirkle** [comment]
@crynobone, this is not a support request. Concurrency does not work with long-running processes (tasks), so it appears to be an issue.

Could you please reopen this issue?
