### ISSUE TITLE
Change MariaDB commandline name as per official documentation from MariaDB 10.5

### ISSUE THREAD

**Issue by aledelgo** [laravel/framework#52843]
### Laravel Version

11.x

### PHP Version

any

### Database Driver & Version

MariaDB

### Description

As per official documentation https://mariadb.com/kb/en/mysql-command-line-client/
from MariaDB 10.2 the commandline name of mariadb is not `mysql` anymore but `mariadb`
this make a lot of artisan command related to db pretty unusable when using mariadb 10.2+ (eg. with laradock) (except form manually symlinking obviously)

Here i suppose the code where to inject a new logic for commandline name generation
https://github.com/laravel/framework/blob/3e56cc4cd0700dbcb540a40f263e4180867549e1/src/Illuminate/Database/Console/DbCommand.php#L136C13-L136C34

### Steps To Reproduce

try to use any artisan db / migrate command on a docker with a clean MariaDB 10.2+

**Comment by staudenmeir** [comment]
Hi @aledelgo,
This will changed in Laravel 12: #51505

**Comment by crynobone** [comment]
Thanks @staudenmeir
