### ISSUE TITLE
Issue with using the new defer helper

### ISSUE THREAD

**Issue by MohamedElzoghby99** [laravel/framework#52861]
### Laravel Version

^11.9

### PHP Version

^8.2

### Database Driver & Version

MySQL 8.0.39 for Linux Debian 12

### Description

i installed a fresh laravel application 
i wanted to test the new helper **defer**
```
Route::get('/', function () {
    defer(function () {
        sleep(5);
        dump("Running defered code");
    });

    return response('success', 200);
});
```

for something reason when i visit:  http://localhost:8000, it does show the response but the browser is still loading until the code inside defer has executed.
![Screenshot from 2024-09-20 00-24-14](https://github.com/user-attachments/assets/8e8cb3b8-ccef-4b82-95f0-f189b41e71e4)

### Steps To Reproduce

just created a new laravel application

**added this code in routes.php file:**

```
Route::get('/', function () {
    defer(function () {
        sleep(5);
        dump("Running defered code");
    });

    return response('success', 200);
});
```

**then visited localhost:8000**

- OS: debian 12
- php: 8.2.23
- laravel: 11.9
- mysql:  8.0.39

**Comment by timacdonald** [comment]
It seems like your web server does not support the defer functionality.

The web server will need to be using PHP-FPM or Lightspeed.

If you are doing this via `php artisan server`, for example, the web server cannot hang up on the request until it has finished executing.

**Comment by rezahmady** [comment]
I use nginx on herd in Windows and I have the same problem

**Comment by Jas-n** [comment]
I've made a wrapper to detect if PHP's running with FPM, if not it'll just run the callback as-is:

```php
<?php

namespace App\Helpers;

class Laravel
{
    public static function defer(?callable $callback = null, ?string $name = null, bool $always = false)
    {
        if (function_exists('fpm_get_status')) {
            return defer($callback, $name, $always);
        }

        $callback();
    }
}
```

Then just call it:

```php
use App\Helpers\Laravel;

Laravel::defer(function () {
    sleep(5);
    dump("Running defered code");
});
```

**Comment by timacdonald** [comment]
If the required web server functions are not available the deferred functions will simply run after the response is sent to the client but before they are disconnected.

**Comment by kratos-digital** [comment]
I came here after it didn't work for me on local env, using `php artisan serve`. I think this should be highlighted in docs.

It works when using Laravel Herd and test domain.

Also, in docs it says to import the `defer` function `use function Illuminate\Support\defer;` but this throws an error "Call to undefined function Illuminate\Support\defer()"

**Comment by timacdonald** [comment]
@kratos-digital, please update to the latest version of Laravel and try again.

The function was namespaced, and documented that it is imported, to ensure there are no conflicts with other global `defer` functions.
