### ISSUE TITLE
Local Temporary Urls only work for the last defined disk

### ISSUE THREAD

**Issue by syntafin** [laravel/framework#52872]
### Laravel Version

11.23.5

### PHP Version

8.3.11

### Database Driver & Version

MySQL 8.0.39 for Linux on x86_64

### Description

I tried out the new ``temporaryUrl()`` for the Local Filesystem. 
After adding
```php
<?php
return [
    'disks' => [
        'files' => [
            'driver' => 'local',
            'root' => storage_path('app/files'),
            'throw' => false,
            'serve' => true,
        ],
    ],
];
```

to the ``filesystems.php`` it works fine with ``Storage::disk('files')->temporaryUrl('foobar.txt');``, but when I add another Disk below it, for example a disk called ``download``:

```php
<?php
return [
    'disks' => [
        'files' => [
            'driver' => 'local',
            'root' => storage_path('app/files'),
            'throw' => false,
            'serve' => true,
        ],
        'download' => [
            'driver' => 'local',
            'root' => storage_path('app/download'),
            'throw' => false,
            'serve' => true,
        ],
    ],
];
````

You can only generate Links for this disk, if I try it with the disk defined above, I get the error message ``Route [storage.files] not defined.``.

### Steps To Reproduce

* Create a Disk to serve Local files via Temporary Url.
* Create another
* Try to generate a Temporary Url for the first one.

**Comment by crynobone** [comment]
You need to add custom `url` configuration to avoid both disk to use `storage` path:

```diff
        'files' => [
            'driver' => 'local',
            'root' => storage_path('app/files'),
            'throw' => false,
            'serve' => true,
+           'url' => 'disk-storage',
        ],
        'download' => [
            'driver' => 'local',
            'root' => storage_path('app/download'),
            'throw' => false,
            'serve' => true,
+           'url' => 'download-storage',
        ],
```

![CleanShot 2024-09-23 at 12 51 23](https://github.com/user-attachments/assets/490349dd-219b-418a-bfd7-248e7c268df8)

We would appreciate a PR to the documentation to improve this.
