### ISSUE TITLE
Automatically created directories have incorrect permissions

### ISSUE THREAD

**Issue by miken32** [laravel/framework#52871]
### Laravel Version

11.23.5

### PHP Version

8.3.11

### Description

When creating a file containing a non-existent path, intermediate directories are created. The visibility of those directories should match the visibility specified in the file creation command.

### Steps To Reproduce

```php
Storage::disk('local')->put('foo/test.txt', 'asdf', 'public');
```
Assuming the directory `foo/` did not exist beforehand, it is created with 0700 permissions instead of 0755 as would be expected for a "public" file.

**Comment by crynobone** [comment]
Storage code is provided by Flysystem package.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by miken32** [comment]
I already worked around this in my code. It would take 30 seconds to verify this; if you’re not interested in doing that minimum amount of effort I’m not going to spend any more of my time on it. And yes Flysystem makes the directories, but you guys could ensure it makes them correctly. On Sep 22, 2024, at 5:31 AM, Mior Muhammad Zaki ***@***.***> wrote:﻿
Hey there,
While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

Laracasts Forums
Laravel.io Forums
StackOverflow
Discord
Larachat
IRC

Thanks!
