### ISSUE TITLE
Custom commands not being listed on php artisan

### ISSUE THREAD

**Issue by miguelfmromao** [laravel/framework#52907]
### Laravel Version

11.24.0

### PHP Version

8.3.11

### Description

My custom commands stoped working after the latest Laravel update and are not even being listed in `php artisan`.

I think the problem might be from the update that changed the `ApplicationBuilder.php` file on this pull request: https://github.com/laravel/framework/pull/52867

If I restore the `ApplicationBuilder.php` from before this update, the custom commands work again.

### Steps To Reproduce

On version 11.24.0 of Laravel create a custom command and check if it shows up with `php artisan`.

**Comment by elijahcruz12** [comment]
Can confirm, all custom commands in `App\Console\Commands` are not listed in `php artisan` and aren't able to be ran.

**Comment by miguelfmromao** [comment]
Thanks for the info @rodrigopedra! Didn't see that you already reported the issue.

**Comment by rodrigopedra** [comment]
No problem =)
