### ISSUE TITLE
Using saveMany() twice on the same model results in incorrect relation collection

### ISSUE THREAD

**Issue by driesrobeyns** [laravel/framework#52908]
### Laravel Version

11.23.5

### PHP Version

8.3

### Description

When calling saveMany() on the same model within the same function results in an incorrect relations collection inside the model which saveMany() was called on.

Consider the following code:
```
public function test()
{
	// Find order model
	$backorder = Order::find(1);

	// Array of related OrderProducts (only 1 for brevity)
	$orderItem[] = new OrderProduct([
		'product_id' => 1,
		'quantity' => 1,
		'price' => 2,
	]);

	// Save using saveMany
	$backorder->orderProducts()->saveMany($orderItem);

	// At this point the output will read "Product ID: 1" which is correct
	foreach ($backorder->orderProducts as $product) {
		echo 'Product ID:' . $product->product_id<br>';
	}

	// Do some more logic

	// Another array of related OrderProducts (only 1 for brevity)
	$orderItem[] = new OrderProduct([
		'product_id' => 2,
		'quantity' => 2,
		'price' => 4,
	]);

	// Save using saveMany again
	$backorder->orderProducts()->saveMany($orderItem);

	// Looping over the relation again at this point will only show the first OrderProduct that was saved, 
	the second one is not updated into the backorder model. However in the database 
	both OrderProducts are created correctly.
	// The code below will result in the output:
	//  "Product ID: 1" 
	// which is incorrect as it should output:
	// "Product ID: 1"
	// "Product ID: 2"
	foreach ($backorder->orderProducts as $product) {
		echo 'Product ID:' . $product->product_id<br>';
	}

	dd($backorder);
}
```
When doing dd() on the model it show only the models saved in the first saveMany() call, but not the models from the second saveMany(). In the database the model count is correct. So it has to be an issue with updating the model after the second save.

This can also be seen in the output:
![Screenshot 2024-09-24 194123](https://github.com/user-attachments/assets/e69beac0-bb01-473c-85d5-598c638fea19)

### Steps To Reproduce

1. Create a model with a hasMany() relation.
2. Create the second related model with a belongsTo() relation.
3. Populate the first model.
4. Use find().
5. Create an array of related models and use SaveMany() to save it.
6. Check the number of related models (should be correct)
7. Create another array of related models and use SaveMany() to save it.
8. Check the number of the related models (this should give you the same model count as in step 6 which is incorrect as the newly added models should be added from step 7.)

**Comment by claspina** [comment]
Can you share the definition of method `orderProducts()`

**Comment by driesrobeyns** [comment]
```
	public function orderProducts()
	{
		return $this->hasMany(OrderProduct::class, 'order_id', 'id');
	}
```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by staudenmeir** [comment]
Hi @driesrobeyns,
When you load the relationship with `$backorder->orderProducts`, the result is cached inside the model (as your screenshot shows). So when you then create more order products with `saveMany()` and loop over `$backorder->orderProducts` again, the cached result hasn't changed.

You need to either reload the relationship with `$backorder->load('orderProducts')` or fetch the relationship without caching it using `$backorder->orderProducts()->get()`.

`saveMany()` could unset or reload the relationship automatically, but that would be a breaking change and not necessarily a behavior that every user expects.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
