### ISSUE TITLE
Duplicate schedule command

### ISSUE THREAD

**Issue by fouteox** [laravel/framework#52929]
### Laravel Version

11.24.1

### PHP Version

8.3.11

### Database Driver & Version

MySQL 8.0.36 for macOS 15.0 on arm64 (Herd)

### Description

The command "php artisan schedule:work" executes duplicate commands

### Steps To Reproduce

Clone : 
https://github.com/fouteox/twice-command-laravel

Run :
`php artisan schedule:work`

Look the output.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by fouteox** [comment]
I added the repository in my first post.

I'm surprised so few people are impacted.

**Comment by BassemN** [comment]
I am facing the same issue. Everything was working well up to version 11.23.5. As a workaround, I downgraded the framework to 11.23.5 until the issue is resolved.

**Comment by sebastiaands** [comment]
Same issue here for commands that are scheduled using Forge.
In 11.24.0 none of the scheduled commands ran, in 11.24.1 all of them run twice.

**Comment by Smartoptics-jesper** [comment]
Same issue here, but I also did a fresh Laravel 11 install and directly run **php artisan schedule:list** and it shows twice so it seems like a generic bug and not related to any specific custom projects.

php artisan schedule:list

  0 * * * *  php artisan inspire ..................................................................................................................................................................................................................................................................................................................................... Next Due: 51 minutes from now  
  0 * * * *  php artisan inspire ..................................................................................................................................................................................................................................................................................................................................... Next Due: 51 minutes from now

**Comment by hettiger** [comment]
Same problem here. I also verified it actually executes twice. Thought, it might just be duplicate output or something. However, it really does execute twice:

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class TestCommand extends Command
{
    protected $signature = 'app:test';

    protected $description = 'Command description';

    public function handle()
    {
        logger()->info('did execute test command');
    }
}
```

```
// console.php

// …

\Illuminate\Support\Facades\Schedule::command('app:test')->everyMinute();
```

```
// laravel.log after `php artisan schedule:run` for ~2 seconds

[2024-09-26 07:58:39] local.INFO: did execute test command  
[2024-09-26 07:58:40] local.INFO: did execute test command  
```

**Comment by crynobone** [comment]
`v11.25.0` has been released with revert the breaking change PR.
