### ISSUE TITLE
[ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near 'offset'.

### ISSUE THREAD

**Issue by gsferro** [laravel/framework#52952]
### Laravel Version

11.23.5

### PHP Version

8.2.7

### Database Driver & Version

ODBC Driver 18 for SQL Server

### Description

|App|Version|
|--|--|
|Laravel|11.23.5|
|PHP|8.2.7|
|OS|Win 11|
|RGBD|Sqlsrv|

## When calling paginate, it is generating the error below using sqlsrv

```php
UsuariosAutorizados::paginate(2);
```

```sql
SQLSTATE[42000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near 'offset'. (Connection: sqlsrv, SQL: select * from [usuarios_autorizados] order by [id] asc offset 10 rows fetch next 10 rows only)
```

![image](https://github.com/user-attachments/assets/a2d3bab0-be2d-43f0-968c-ed9308cf62fc)

### Steps To Reproduce

```php

# model
Users::paginate(2);

# view
$users->links()

# url
.../users?page=2
```

![image](https://github.com/user-attachments/assets/45f96897-bcf5-46c5-9132-d662694fbf71)

**Comment by staudenmeir** [comment]
Hi @gsferro,
What version of SQL Server are you using? It looks like an older one. Laravel 11 [requires](https://laravel.com/docs/11.x/database#introduction) SQL Server 2017+.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
