### ISSUE TITLE
Check if attribute is empty for whereNotIn on QueryBuilder

### ISSUE THREAD

**Issue by chougron** [laravel/framework#5296]
I use the whereNotIn function with a "dynamic" array, and this array may be empty.
When the array is empty, SQL return a syntax error, because it is translated to a **not in ()**.

It would be great if the whereNotIn function could check the emptiness of the array passed, and not translate anything to SQL if it is the case.

Ex:
```
    $array = array();
    DB::table('users')->whereNotIn('users.id', $array);
```
This will become
```
   SELECT * FROM users WHERE users.id NOT IN ();
```
And this throws a SQL syntax error.

(Edited for ex.)

**Comment by barryvdh** [comment]
Does this need a PR or what is the status on this? I would like to see this added to the Eloquent ORM :)

**Comment by franzliedke** [comment]
I think it was rejected a few times, but there's obviously demand. ;)
I'd love to see this, too!

**Comment by GrahamCampbell** [comment]
Discussion can continue on the pull request if still required.
