### ISSUE TITLE
Component not working with double quotation 

### ISSUE THREAD

**Issue by abramie** [laravel/framework#53016]
### Laravel Version

11

### PHP Version

8.3

### Description

When using a custom component and passing to an attribute a value with {{}} containing the same quotation mark, the component is not recognized. 
For my component : 

Test.php
```
class Test extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct($value)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.test');
    }
}

```
with the following view : 
```
<div>
    Test
</div>
```
If I call it like that : 
`<x-test value="test" />` it work as expected
If instead, I use it that way : 
`<x-test value="{{"test"}}" />`
the constructor is not called, and my final page contain the full balise in the html: 
![image](https://github.com/user-attachments/assets/84cc33ea-c4ea-4702-bffb-951ce0e88aae)

(I noticed the problem while passing route to as custom form component ) 
I think it's a bug, there is no error triggering and it work correctly with standard html component. 

### Steps To Reproduce

Create component : `php artisan make:component Test`
Add an attribute to the component's construct method. 
Use the component in a view. 
When assigning the value for the attribute, use the same quotation twice like that : 
`<x-test value="{{"test"}}" />`
There is no problem with : 
`<x-test value="{{'test'}}" />`
of with
` <x-test value='{{"test"}}' />`

Inspect the resulting view, instead of the normal result (the component return the content of his associated view), the component will be as written in the view.

**Comment by browner12** [comment]
don't use `{{ }}` when passing data to components.

if you need to pass PHP, prefix the attribute with a colon:

```blade
<x-test :value="'test'">
```

the regex is quite complex, and probably isn't setup to handle the double quotes like that

**Comment by crynobone** [comment]
Thanks @browner12
