### ISSUE TITLE
Calls to $model->update() doesn't trigger the eloquent.updated event

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#53013]
### Laravel Version

11.25.0

### PHP Version

8.3.11

### Database Driver & Version

PostgreSQL 16

### Description

When calling the `update(...)` method on a Eloquent model, the framework is not dispatching the `eloquent.updating` and `eloquent.updated` events because it forwards the call to the Query\Builder here (and maybe on some other places):

```php
public function update(array $values)
{
    return $this->toBase()->update($this->addUpdatedAtColumn($values));
}
```

My first reaction to this is that we would need to do something like this:

```php
public function update(array $values)
{
    $this->fireModelEvent('updating');

    $result = $this->toBase()->update($this->addUpdatedAtColumn($values));

    $this->fireModelEvent('updated');

    return $result;
}
```

But the same behaviour is present on some other places, like the `upsert()` that may not be just a simple update event, and also `touch()` that is doing

```php
return $this->toBase()->update([$column => $time]);
```

While I believe it could call update on the model directly, to be backed by a future event dispatch:

```php
return $this->update([$column => $time]);
```

So this seems like a bug, as it's not doing what update on `save()` does, but I would like how do you feel about a PR on this.

### Steps To Reproduce

Add an event watcher on `*` to show then on the log file, and trigger a `$model->update()`, there are no eloquent.updated being fired.

**Comment by crynobone** [comment]
See https://laravel.com/docs/11.x/eloquent#mass-updates
