### ISSUE TITLE
[Docs] [Mail > Localizing Mailables] The code throws an exception: Method Illuminate\Mail\Mailer::locale does not exist.

### ISSUE THREAD

**Issue by jorgelloret** [laravel/framework#53023]
### Laravel Version

11

### PHP Version

8.2

### Description

The code in https://laravel.com/docs/11.x/mail#localizing-mailables, throws an exception: Method Illuminate\Mail\Mailer::locale does not exist.

### Steps To Reproduce

I generate a Mailable (ThanksMail in this case) and send the mail in a class with this code:

```
Mail::locale('es')->send(new ThanksMail());
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jorgelloret** [comment]
@crynobone thanks, but is not a question, it's a bug in the documentation, i.e. code that doesn't and won't work. There is only in this repository the option to create an issue, in the documentation repository you can only make pull requests.

**Comment by crynobone** [comment]
Your code isn't the same as documentation.

**Comment by jorgelloret** [comment]
Excuse me, sorry, I just realised that to() returns a PendingMail object which does have a locale method.

My confusion was because I put the recipient in the Mailable and I thought that removing the to() would work.
