### ISSUE TITLE
Error: Undefined array key "driver" with Multidimensional Config Values for Disks in Laravel ^11.23.0

### ISSUE THREAD

**Issue by jaapredeker** [laravel/framework#53032]
### Laravel Version

11.23.0

### PHP Version

8.3.11

### Description

When using Laravel version ^11.23.0, I encounter an error Undefined array key "driver" when I have multidimensional config values for disks.

### Steps To Reproduce

1. Define a multidimensional config value for disks in config/filesystems.php.
2. Attempt to use the filesystem configuration in the application.

**Expected Behavior:** The application should correctly handle multidimensional config values for disks without throwing an error.  

**Actual Behavior:** The application throws an error: `Undefined array key "driver"`.

**File that throws error:** 
[src/Illuminate/Filesystem/FilesystemServiceProvider.php:114](https://github.com/laravel/framework/blob/v11.23.0/src/Illuminate/Filesystem/FilesystemServiceProvider.php#L114)

**Example Configuration:**
```
'disks' => [
    'example' => [
        'driver' => 'local',
        'root' => storage_path('app/example'),
        'throw' => true,
    ],
    'nested' => [
        'level1' => [
            'driver' => 'local',
            'root' => storage_path('app/nested/level1'),
            'throw' => true,
        ],
    ],
],
```

**Comment by crynobone** [comment]
Can you share where in the documentation that allows multi-dimensjonal configuration?

**Comment by jaapredeker** [comment]
I assumed it was possible based on the documentation, which states:  
> The configuration values may be accessed using 'dot' syntax, which includes the name of the file and option you wish to access.

source: https://laravel.com/docs/11.x/configuration#accessing-configuration-values

This implies that nested values can also be accessed.

Is this an incorrect usage of the configuration?

**Comment by crynobone** [comment]
Nope, that's not the correct usage.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
