### ISSUE TITLE
cannot modify/merge eloquent relations.

### ISSUE THREAD

**Issue by asule90** [laravel/framework#53036]
### Laravel Version

10.10

### PHP Version

8.2.17

### Database Driver & Version

mariadb:10

### Description

wanted to merged eloquent relations collection, but keeps being reset to the original value.

```php
$entity->load('deliveries');
$deliveries = $entity->deliveries;

$deliveryNumbers = $deliveries->pluck('deliveryNumber');

$otherDels = $this->getOtherDeliveries($deliveryNumbers);

//bug : deliveries is always reset to the original value
$entity->deliveries = $deliveries->merge($otherDels); //even used ->toArray() is still the same

//but delivs is work as expected
$entity->delivs = $entity->deliveries;
```
$entity->deliveries contains 1 item, merge expected to contains 2 items

i debug it in the controller, it is still containing expected value.

but in the the resulted http response , `deliveries` keeps being reset to the original value (1 item).
also checked in the DiagnosticMiddleware (after middleware), it is already reset to the original.
```php
$response = $next($request);
dd($response->getContent()); (deliveries: 1 item)
```

but `delivs` works fine, contains 2 items.

middleware in the kernel

```
protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\HeadMiddleware::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\DiagnosticMiddleware::class,
        \App\Http\Middleware\PrometheusMetricsMiddleware::class
    ];
```

### Steps To Reproduce

- setup eloquent relations
```php
public function deliveries(): HasMany
    {
        return $this->hasMany(Delivery::class, 'docReference', 'orderNumber');
   }
```

- lazy eager load
- merge the relation collection
- return entity

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by asule90** [comment]
i thought it is a bug, because i couldn't find the solution. will try to ask in discord.
