### ISSUE TITLE
Laravel class files are distributed as executable files

### ISSUE THREAD

**Issue by szepeviktor** [laravel/framework#53045]
### Laravel Version

11.25.0

### PHP Version

8.2.17

### Database Driver & Version

n/a

### Description

Currently many class files are executable.
Executable files are security risks. 👈🏻 

Would you merge a PR removing those mode bits?

### Steps To Reproduce

```
find -type f -executable | wc -l
231
```

**Comment by crynobone** [comment]
251 files with 777 chmod or 755 chmod?

**Comment by szepeviktor** [comment]
git is not able to store all mode bit combinations, only 644 and 755.

So 755.

**Comment by crynobone** [comment]
`755` is fine, webserver normally access the file via group and therefore doesn't have executable access.

**Comment by szepeviktor** [comment]
I am sad that the framework remains dirty.
