### ISSUE TITLE
Deferred function helper execute the task before the HTTP response has been sent to the user

### ISSUE THREAD

**Issue by saychool** [laravel/framework#53055]
### Laravel Version

11.26

### PHP Version

8.3

### Database Driver & Version

Postgresql 16 self hosted on ubuntu 24

### Description

upgraded to laravel 11.x from 10.x and still has ``app/Http/Kernel.php`` file, adding ``InvokeDeferredCallbacks`` to my Kernel.php already like the documentation told ([here](https://laravel.com/docs/11.x/helpers#deferred-function-compatibility)), but i think the helper didn't work correctly

### Steps To Reproduce

```PHP
Route::get('/testingDefer', function () {
    defer(function () {
        sleep(10);
    });

    return true;
});
```

just a simple test, i did some complex code before but simple test are enough to reproduce

![{8710F3E8-B8EA-43CE-829C-DF59ABD69AAC}](https://github.com/user-attachments/assets/26c679fe-8297-43cc-bf4c-373c0b50e8e7)

**Comment by crynobone** [comment]
Can you provide the web server information?

**Comment by saychool** [comment]
> Can you provide the web server information?

NGINX using Laravel Herd on my local development, NGINX with Ubuntu 24 on my production / staging environment

**Comment by timacdonald** [comment]
The web server will need to be using `PHP-FPM` or `Lightspeed` for the defer function to run after the HTTP connection has disconnected.

If the required web server functions are not available the deferred functions will simply run after the response is sent to the client but before they are disconnected.
