### ISSUE TITLE
PATCH requests don't work with FormData

### ISSUE THREAD

**Issue by DIPANJAN01** [laravel/framework#53061]
### Laravel Version

11.26.0 

### PHP Version

8.3

### Description

When making a PATCH request, the request body is empty in the backend.
I have seen the old (now closed) issue on this and the workaround of using _method="PUT" works yes, but the main problem hasn't been fixed in a proper way and still persists to this day. 

### Steps To Reproduce

1. In frontend, you can do:

```
const patchData = async() => {
  const formData = new FormData();
  formData.append("my-file", file);
  try {
    const response = await axios.patch(
      `/api/endpoint`,
      formData,
      {
        headers: {
          "Content-Type": "multipart/form-data",
        },
      });
    } catch (err) {
    console.log(err.response.data);
  }
  };
```
  
  
  2. In laravel backend (api.php):
  
  ```
Route::patch('/endpoint', function (Request $request) {
  
  logger(json_encode($request->file('my-file')));		//output: null
  
  }
```

**Comment by DIPANJAN01** [comment]
uhh, okay I guess. I just thought this is a problem with the library itself, since Route::patch()'s behavior is inconsistent with other http method behaviors like Route::post. 
Ideally Route::patch() should work with client requests exactly like Route::post does.
But thanks anyways!

**Comment by hkiame** [comment]
I encountered the same issue with a `PUT` request when sending form data. After spending a lot of time troubleshooting, I resolved the problem by changing the request method to `POST` and adding `formData.append('_method', 'PUT');`
