### ISSUE TITLE
Incorrect version v46011 available on Packagist

### ISSUE THREAD

**Issue by jnoordsij** [laravel/framework#53065]
### Laravel Version

N/A (or v46011)

### PHP Version

N/A

### Description

When running `composer outdated`, a version 46011 was reported as available. This version can be found at https://packagist.org/packages/laravel/framework#v46011.

This seems to be an incorrectly listed release.

### Steps To Reproduce

Run `composer update` and then `composer outdated` on https://github.com/laravel/laravel

**Comment by n0099** [comment]
And it's published on `2023-02-13 16:54 UTC`

**Comment by Jimbolino** [comment]
```
$ composer outdated
Color legend:
- patch or minor release available - update recommended
- major release available - update possible

Direct dependencies required in composer.json:
laravel/framework 11.27.1 46011 The Laravel Framework.

Transitive dependencies not required in composer.json:
Everything up to date
```

**Comment by crynobone** [comment]
The version has been removed from Packagist, thanks all
