### ISSUE TITLE
Error in FileUpload not throwing an exception

### ISSUE THREAD

**Issue by murat-ertunc** [laravel/framework#53062]
### Laravel Version

9.52.16

### PHP Version

8.3.12

### Database Driver & Version

PostgreSql 16.4, MacOs 15.0.1, HomeBrew

### Description

When I run the code below, strangely, it returns immediately during updateOrCreate. When I tried to test it with dd right after updateOrCreate, it would return without hitting the dd. When I wrapped updateOrCreate in a try-catch block and caught the exception with dd, I got the following errors: first, that a string value cannot be inserted into the 'min' column, and second, that 'name' is an undefined array key. However, I was only able to get these error messages by using a try-catch block; I didn't receive any exception otherwise.

`
                RecruitmentCriteria::updateOrCreate([
                    'api_id' => $apiInterface->id,
                    'recr_id' => $rec->id
                ],[
                    'min' => isset($information['min']) ? $information['min'] : 0,
                    'max' => isset($information['max']) ? $information['max'] : 0,
                    'name' => $apiInterface['name'],
                ]);
`

### Steps To Reproduce

1- Send a POST request to a controller function.
2- In that function, send the request to a different private function within the same controller.
3- Try to save the sent request in the second function using updateOrCreate in an erroneous way (like an undefined array key).

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
Also, Laravel 9 was only design and tested for PHP 8.0, 8.1 and 8.2
