### ISSUE TITLE
Issues with latest phpredis breaking changes

### ISSUE THREAD

**Issue by scottasmith** [laravel/framework#53082]
### Laravel Version

10.48.22

### PHP Version

8.3.7

### Database Driver & Version

DB version N/a

### Description

OS: Docker / Linux
PHP: 8.3.7
Redis server: 7.4
phpredis: 6.1.0

The latest version of phpredis (6.1.0) has been changed to use an unsigned 64-bit cursor.
See https://github.com/phpredis/phpredis/pull/2458 and https://github.com/phpredis/phpredis/pull/2462.

There is a bug report here https://github.com/phpredis/phpredis/issues/2562, but this is intended behaviour going forward.

This means it breaks tagged caching on Laravel/Redis.

This is the line causing the issue with the latest version of the extension: https://github.com/laravel/framework/blob/5caf767f708aa6e8a3774104ecc7dd0471db805e/src/Illuminate/Cache/RedisStore.php#L298

### Steps To Reproduce

- Install latest version of Laravel 10.
- pecl install redis-6.1.0

Current way broken in new version of phpredis in Tinker
```
> $redis = new \Redis(['host' => 'redis', 'port' => 6379]);
> $redis->zAdd('laravel:tag:test', -1, 'value');
> $cursor='0'
> $redis->zScan('laravel:tag:test', $cursor, '*', 10);
```

Works with new version of phpredis in Tinker
```
> $redis = new \Redis(['host' => 'redis', 'port' => 6379]);
> $redis->zAdd('laravel:tag:test', -1, 'value');
> $cursor=null
> $redis->zScan('laravel:tag:test', $cursor, '*', 10);
```

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by scottasmith** [comment]
@crynobone It literally affects the very latest version as well!

https://github.com/laravel/framework/blob/v11.27.2/src/Illuminate/Cache/RedisStore.php

**Comment by mic2100** [comment]
@crynobone This needs fixing on the latest version Laravel 11 not just on the unsupported versions!
