### ISSUE TITLE
Route inside a prefix group gives 404 error

### ISSUE THREAD

**Issue by guarriellocristianmichele** [laravel/framework#53099]
### Laravel Version

11.27.2

### PHP Version

8.2

### Description

Some routes inside a prefix group gives a 404 error, but if i move the route outside the prefix group it works without errors.
If I also move the corrupted route on top the other routes inside the prefix group it works.

![image](https://github.com/user-attachments/assets/cddb3f51-f1c4-42d8-b4f1-2617a2d45baf)

The corrupted route is '/history' and 'thank-you'.

### Steps To Reproduce

[web.zip](https://github.com/user-attachments/files/17326699/web.zip)
This is my web.php file

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by Jubeki** [comment]
@guarriellocristianmichele I think this has something to do with you defining the `/{id}` before the other groups. This would capture the routes `thank-you` and `history` as well. if you place these before `/{id}` everything should work.
