### ISSUE TITLE
`SESSION_DOMAIN` changes the domain for all cokkies

### ISSUE THREAD

**Issue by troccoli** [laravel/framework#53112]
### Laravel Version

11.27.2

### PHP Version

8.3.12

### Database Driver & Version

SQLite 3.43.2

### Description

I'm trying to share the session between subdomains, and one of the step is to change `SESSION_DOMAIN`. This has also the effect to set the domain for the `XSRF-TOKEN` cookie too, which I think it's wrong.

### Steps To Reproduce

To replicate the issue follow these steps:
- create a brand new Laravel app with `laravel new example` and choose to add Breeze
- change `SESSION_DOMAIN=null` to `SESSION_DOMAIN=".test"` in your `.env` file (Im using Herd, which is why the domain is `.test`)
- add a new user
  - `php artisan tinker`
  - `User::factory()->create(['email' => 'test@example.com']);`
- go to `http://example.test/login` and enter the following credentials
  - Email: `test@example.com`
  - Password: `password`
- click on `Login`

If you inspect the request you will see that the response's headers contain a `Set-Cookie` instruction for the `XSRF-TOKEN` cookie with a domain of `.test`.

**Comment by valorin** [comment]
The CSRF token is tied to your session, so if you're sharing a session across subdomains, I'm pretty sure the same CSRF token will apply on both too.

Do you use the `XSRF-TOKEN` cookie? It might be an option to just disable that if you don't want it shared.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
