### ISSUE TITLE
Queue worker hangs on AWS database failover

### ISSUE THREAD

**Issue by mantas-done** [laravel/framework#53115]
### Laravel Version

v11.27.2

### PHP Version

8.3

### Database Driver & Version

8.0.mysql_aurora.3.05.2

### Description

Queues are managed though Laravel Forge.
Database on AWS, two servers: master/slave.

This issue was already reported in: https://github.com/laravel/framework/issues/48486 , but seems that the error number is different this time [error log.txt](https://github.com/user-attachments/files/17343477/error.log.txt) 

When MySQL fails over to the reader server, queue workers get a "read only error" and do not process new jobs. Restarting queue worker fixes the problem.

![image](https://github.com/user-attachments/assets/9fcac6c5-7916-4b00-a4d5-5e7da0693372)

![image](https://github.com/user-attachments/assets/a33679a3-23bd-4c52-879a-a4e6350b9135)

### Steps To Reproduce

Failover database on AWS.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
