### ISSUE TITLE
whereBelongsTo is not working on MorphRelations

### ISSUE THREAD

**Issue by mahdimirhendi** [laravel/framework#53124]
### Laravel Version

11.23.5

### PHP Version

8.3

### Database Driver & Version

MYSQL 

### Description

In the documentation, it is mentioned that we can find a relation owner using the following syntax:

```php
$query->whereBelongsTo($user, 'author');
```
 when attempting to use this method with morph relations, we are getting the following exception:

```
"message" => "Nested arrays may not be passed to whereIn method."
"exception" => "InvalidArgumentException"
```

### Steps To Reproduce

1. **Create a Morph Relationship**: Set up a polymorphic relationship between the `Post` model and the `Author` model. This relationship will allow the `Post` to reference different types of authors (e.g., users, admin, etc.).

2. **Define the Morph Relationship in Models**:
In the `Post` model, define a `morphTo` relationship for the `author`.
n the `Author` model, define a `morphMany` relationship for the posts.

3. **Query the Author of a Post**:
Use the following query to attempt to find the author of a specific post:
     ```php
     $query->whereBelongsTo($user, 'author');
     ```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
