### ISSUE TITLE
Model make command with folder path has incorrect class path

### ISSUE THREAD

**Issue by JeRabix** [laravel/framework#53141]
### Laravel Version

11.27.2

### PHP Version

8.3

### Description

If you run the command `php artisan make:model Product/ProductTag -f`

We will get the ProductTag.php file in the Models/Product folder

But the path for ProductFactory will not be correct

Example:
```php
/** @use HasFactory<\Database\Factories\Product/ProductTagFactory> */
use HasFactory;
```

### Steps To Reproduce

1. Install laravel
2. Run make:model command with factory flag and path to folder, example: Product/ProductTag
3. Open Models/Product/ProductTag.php file

**Comment by crynobone** [comment]
PR has been merged.
