### ISSUE TITLE
Cookie::queue(...) does not take `domain` into account

### ISSUE THREAD

**Issue by JonathanGawrych** [laravel/framework#53159]
### Laravel Version

11.24.0

### PHP Version

8.2.19

### Description

When setting two cookies using `Cookie::queue(...)`, with the same name and path, but different domains, the two cookies are _not_ sent to the client, but the latter one overwrites the prior. It works when calling `response()->cookie(...)` directly, just not when the cookie is queue.

It appears that Symphony's ResponseHeaderBag::setCookie() handles it by making one level of the cookie map, domain specific:
https://github.com/symfony/http-foundation/blob/3d7bbf071b25f802f7d55524d408bed414ea71e2/ResponseHeaderBag.php#L162

However, CookieJar doesn't, only caring about name and path:

https://github.com/laravel/framework/blob/231091c19945f058c576005907a5518fcc7a2bb1/src/Illuminate/Cookie/CookieJar.php#L153

You may be asking why we are setting cookies on two different domains? The answer is that we are transitioning from using CORS to an API server, to instead have each subdomain have separate logins. During this transition we need to set cookies on both the subdomain and domain, and some of our cookies are queued inside services, rather created directly in the controller next to the response. Thanks.

### Steps To Reproduce

Ensure the `AddQueuedCookiesToResponse` middleware is being used.

Add this code to any controller
```php
// Logout request made on www.example.com
Cookie::queue(Cookie::forget('auth_cookie')); // lost
Cookie::queue(Cookie::forget('auth_cookie', domain: '.example.com')); // sent
```

View the response and see there is only one cookie set.

**Comment by Sajid-al-islam** [comment]
created a PR but, but as queue and unqueue is part of the interface / contract it can't be changed on a patch release

**Comment by JonathanGawrych** [comment]
Yeah, I was working on it myself and found that.

Also I found that getPath() is not null, but domain _might_ be null, and null is a valid value for domain. Thus we can't use null to mean unqueue on "any domain". I'm currently looking into defaulting to `false`, so you can pass in `null` explicitly.

**Comment by crynobone** [comment]
Closing this as possible alternative is available: https://github.com/laravel/framework/pull/53202#issuecomment-2421089653
