### ISSUE TITLE
[11.28.0] `->orWhere()` behaviour changed with array input

### ISSUE THREAD

**Issue by Dmitrev** [laravel/framework#53184]
### Laravel Version

11.28.0

### PHP Version

8.2.24

### Description

I'm not sure if this was a bug and is now fixed, but either way it's a breaking change and thought it was worth creating an issue for.

The Query builder `->orWhere()` command by default now combines statements using the `OR` rather than `AND` keywords

I found an closed PR that is related to this:
https://github.com/laravel/framework/pull/53147

The following change broke the functionality:
https://github.com/laravel/framework/pull/53147/files#diff-2ed94a0ea151404a12f3c0d52ae9fb5742348578ec4a8ff79d079fa598ff145d

Perhaps this needed to be patch for Query builder as well? PR was only targeting Eloquent

I think the Query builder should probably have the same functionality of passing a `boolean` param to avoid having the functionality be inconsistent between the two.

There is a clear workaround in this case, which is to not use the array syntax and instead use the `orWhere` with a callback like this:

```php
$query->orWhere(function(Builder $query) {
    $query->where(...)->where(...);
});
```

### Steps To Reproduce

Run the following in tinker (should work on any clean install of Laravel):

```php
DB::table('users')->orWhere([['id', '=', 1], ['id', '=', 2]])->toRawSql();
```
output Laravel 11.28.0:

```
= "select * from `users` where (`id` = 1 or `id` = 2)"
```

output Laravel 11.23.5 (notice the `and` instead of `or`)
```
= "select * from `users` where (`id` = 1 and `id` = 2)"
```

**Comment by Dmitrev** [comment]
I was able to do some additional testing and narrowed the issue down to the commit that caused the issue.

Remove the boolean here, reverts back the behaviour.

**Comment by sivabalan02** [comment]
I also face the same issue

**Comment by hafezdivandari** [comment]
@timacdonald you may want to take a look at this.

**Comment by zero-to-prod** [comment]
The problem is that the elements in the array are `or` joined instead of `and` joined.

Take a look at the `$boolean` in the `where()` method.

**Comment by taylorotwell** [comment]
Hmm, this is a tough one. The inconsistent behavior that @timacdonald fixed makes this feel like a bugfix to me, but it is breaking since people have relied on the inconsistent behavior.

**Comment by zero-to-prod** [comment]
> ave relied on the inconsistent behavior.

Definitly feels like a [Hyrum's Law](https://www.hyrumslaw.com/) thing.

**Comment by hafezdivandari** [comment]
@taylorotwell It seem that the changes on the PR are invalid, the boolean applies to the outer constraint not the nested ones?

```php
User::where('active', true)->orWhere(['name' => 'Tim', 'verified' => true])->toRawSql();

// This one is wrong?
// select * from "users" where "active" = 1 or ("name" = 'Tim' or "verified" = 1)"

User::where('active', true)->orWhere([['name', 'Tim'], ['verified', true]])->toRawSql();

// This one was correct, but broken in the PR?

// Before the PR:
// select * from "users" where "active" = 1 or ("name" = 'Tim' and "verified" = 1)

// After the PR:
// select * from "users" where "active" = 1 or ("name" = 'Tim' or "verified" = 1)
```

**Comment by timacdonald** [comment]
Got a fix up for this. Unfortunately the array syntax results in inconsistent queries depending on which one you use.

Sorry for the troubles here, folks. I've added a heap of additional tests to hopefully ensure we don't hit this again.

https://github.com/laravel/framework/pull/53197

**Comment by Afrowson** [comment]
@taylorotwell We also relied on this "feature" since 2021... now we have to fix our code... that is OK. I can see why it was a "bug" but please... if you decide to not revert the breaking change, at least comment it on the Laravel11 Migration guide... I spent far to much time debugging the root issue of my failing tests...

**Comment by Tadaz** [comment]
I believe this should be mentioned in the docs. I noticed different results in my project after migrating from v.9 to v.11, and only with Gemini's help was I able to track down this topic.

**Comment by LarsDol** [comment]
Haha zelfde issue in WAP! Thanks Dmitri! 😎

**Comment by Luke-SF** [comment]
Is this behavior fixed again?
Composer.lock shows me

          "name": "laravel/framework",
            "version": "v11.41.3",

In "artisan tinker" I run:

    MyModelName::where([['column','value'], ['column2','value2']])->first();

and it appropriately finds null if they do not both match.
