### ISSUE TITLE
Wrong error view when exception comes from eval()'d code

### ISSUE THREAD

**Issue by jlabedo** [laravel/framework#53203]
### Laravel Version

11.28.1

### PHP Version

8.1.4

### Description

When an error is thrown from eval()'d code, I don't see the real error but this one:
<img width="1054" alt="Capture d’écran 2024-10-17 à 22 21 31" src="https://github.com/user-attachments/assets/aa30d82e-c694-4efe-a532-fab1b7a05375">

### Steps To Reproduce

In any part of the code, eval() some code that throws an exception:
```php
class AuthenticatedSessionController extends Controller
{
    /**
     * Display the login view.
     */
    public function create(): View
    {
        eval(<<<PHP
            namespace MyNamespace;
            
            class MyClass {
                public function myMethod(): void
                {
                    throw new \Exception('Hello, world!');
                }
            }
            PHP);

        $class = new \MyNamespace\MyClass();
        $class->myMethod();
        return view('auth.login');
    }
}
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
