### ISSUE TITLE
BadMethodCallException Method validate does not exist.

### ISSUE THREAD

**Issue by kamaldeen661** [laravel/framework#53208]
### Laravel Version

5.5.50

### PHP Version

7.0.0

### Description

hello, am new to laravel i been forcing this problem when i tried to signup but actual the project was not created by me below is the registercontroller.php

### Steps To Reproduce

`<?php

namespace App\Http\Controllers\Auth;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Support\Facades\Response;
class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        $validator = Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed|min:6',			
			'phoneNo'=>'required|min:12|numeric',
			'address'=>'required',
			'image'=>'required|image|mimes:jpg,png,jpeg',
			'check' => 'required',
        ]);
		if ($validator->fails())
		{
			return Response::json(['errors' => $validator->errors()]);
        }
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\User
     */
    protected function create(array $data)
    {

        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => md5($data['password']),
			'phone_no' => $data['phoneNo'],
			'address'=>$data['address'],
			'image'=>$data['image']->store('profile'),
        ]);
		Auth::login($user);
		return redirect('/')->with('success', 'Thanks for Registrating With us');
    }
}`

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
