### ISSUE TITLE
ajax killing session

### ISSUE THREAD

**Issue by faisal975232** [laravel/framework#53201]
### Laravel Version

10.4.1

### PHP Version

8.1.4

### Description

I have three different auth guards.. two are working fine with ajax .. but one guard is killing session on ajax .. 
I am using sessions with database .. It works well with sessions driver == file ..  I have spent three days on this ..tried everything .. also for this guard It is not saving user_id in sessions table .. Please help .. I have tried everything on internet..

### Steps To Reproduce

I have a guard named employee .. 
there are two other merchant and reseller .. 

but employee is killing session on ajax request

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
