### ISSUE TITLE
APP_BASE_PATH fails to be detected due to $_ENV usage

### ISSUE THREAD

**Issue by adaliszk** [laravel/framework#53219]
### Laravel Version

11.28.1

### PHP Version

8.3

### Problematic Behaviour

When the base path of the Laravel is different than the root folder of a repository/deployment then you have the option to use APP_BASE_PATH to adjust that. However, this does not work when you have a production-grade `php.ini` configuration, like the one shipped by default in popular distros as they all disable the access to the `$_ENV` super global by default.

The problematic code is this:
https://github.com/laravel/framework/blob/d2895c733d738200964c6209714e37c20f568789/src/Illuminate/Foundation/Application.php#L253-L259

Ideally, this should be rewritten to use `getenv` as that will be available even when the `$_ENV` super global is disabled due to security concerns of allowing anyone to scan through the environment variables without knowing them.

In my case, this become a problem because we use a monorepo where the vendor location is different from the actual project directories and thus the basename default points to the root of the monorepo and not the workspace itself.

### Steps To Reproduce

1. Use a production intended PHP.ini configuration that excludes the access to `$_ENV`:
    ```ini
   ; in the php.ini file, data handling section
    variables_order = "GPCS"
    ```
2. Move vendor into a separate folder and adjust the bootstrap and artisan files to use that folder
3. Try running tests in your application

### Expected Behaviour

The best would be if the default path resolution should automatically work even for tests using the bootstrap files as their anchor points, that way no overwrite would be necessary. However, fixing the `$_ENV` would already be enough and may be sufficient as it seems the non-standard repository root has not used widely enough to catch this issue.

**Comment by crynobone** [comment]
You can override the default path from `bootstrap/app.php`.

**Comment by adaliszk** [comment]
I merely change the base path, not the actual `bootstrap/app.php`, but very well, I see reporting genuine issues is not welcomed here.
