### ISSUE TITLE
Additional "this" keyword go to infinite loop & generating gateway timeout instead of wrong syntax or some meaningfull message

### ISSUE THREAD

**Issue by pakistanimoon** [laravel/framework#53216]
### Laravel Version

9.x

### PHP Version

8.2

### Description

I just came across a mistake which was leading request to Gateway time out Exception rather it should handle it gracefully and throw a meaning full exception.

`public function getPayableAttribute($value='')
{
    if($this->auction_id > 0){
        return $this->total_cost + $this->$this->admin_fee_price;
    }else{
                return $this->total_cost - $this->discount;
            }
        }`
        
this additional `$this->$this->` was leading to an infinite loop and generating Gateway Timeout Exception

### Steps To Reproduce

add $this->$this-> as i added inside model.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
