### ISSUE TITLE
Default connection is not assumed to use when loading relations between two connections.

### ISSUE THREAD

**Issue by malkhazidartsmelidze** [laravel/framework#53221]
### Laravel Version

10.0

### PHP Version

8.3.0

### Database Driver & Version

MySQL 8.0.31 for macOS 13.0 on arm64

### Description

I've just came accross this issue.

Let's say I have these two model:

**`Author`**
```php
class Author extends Model {
  // no connection specified, assumed that it should use default connection
}
```

**`Post`**
```php
class Post extends Model {
  public $connection = 'posts';

  public function author(){
    return $this->hasOne(Author::class, 'id', 'author_id');
  }
}
```

When I run following query I got the similar error:
**`Error: Base table or view not found: 1146 Table 'posts_database.authors'`**
```php
Post::query()->with('author')->get();
```

It was just unexpected behaviour and I solved it by adding `public $connection = 'author';` to `Author` model. In this example it's simple, but can get tricky in my project, where I've to specify `public $connection = 'mysql';` to 150+ models.

Similar unexpected error can happen when using filtering of relations such as `whereHas` method or any method that creates joins or sub queries for selecting/filtering data between multiple connections.

In this case the query will throw error:
```php
Post::query()->whereHas('author', function ($query) {
  $query->where('age', '>', 21);
})->count();
```

Generated query would be:
```sql
select * from `posts` where exists (select * from `authors` where `authors`.`id` = `posts`.`author_id` and `age` > 21);
```
Where it should be:
```sql
select * from `posts_db`.`posts` where exists (select * from `authors_db`.`authors` where `authors_db`.`authors`.`id` = `posts_db`.`posts`.`author_id` and `authors`.`age` > 21);
```

We can differentiate if the relation model has different connection or different databases names and then qualify full column name prefixed by database name.

I know this usecase is so uncommon, but whole relation thing becomes unusable when using multiple connections even when databases can see each others and theoretically is possible.

I can start working to solve that if it is real issue not only for me.

### Steps To Reproduce

I've just came accross this issue.

Let's say I have these two model:

**`Author`**
```php
class Author extends Model {
  // no connection specified, assumed that it should use default connection
}
```

**`Post`**
```php
class Post extends Model {
  public $connection = 'posts';

  public function author(){
    return $this->hasOne(Author::class, 'id', 'author_id');
  }
}
```

When I run following query I got the similar error:
**`Error: Base table or view not found: 1146 Table 'posts_database.authors'`**
```php
Post::query()->with('author')->get();
```

It was just unexpected behaviour and I solved it by adding `public $connection = 'author';` to `Author` model. In this example it's simple, but can get tricky in my project, where I've to specify `public $connection = 'mysql';` to 150+ models.

Similar unexpected error can happen when using filtering of relations such as `whereHas` method or any method that creates joins or sub queries for selecting/filtering data between multiple connections.

In this case the query will throw error:
```php
Post::query()->whereHas('author', function ($query) {
  $query->where('age', '>', 21);
})->count();
```

Generated query would be:
```sql
select * from `posts` where exists (select * from `authors` where `authors`.`id` = `posts`.`author_id` and `age` > 21);
```
Where it should be:
```sql
select * from `posts_db`.`posts` where exists (select * from `authors_db`.`authors` where `authors_db`.`authors`.`id` = `posts_db`.`posts`.`author_id` and `authors`.`age` > 21);
```

We can differentiate if the relation model has different connection or different databases names and then qualify full column name prefixed by database name.

I know this usecase is so uncommon, but whole relation thing becomes unusable when using multiple connections even when databases can see each others and theoretically is possible.

I can start working to solve that if it is real issue not only for me.

**Comment by NickSdot** [comment]
The same underlying issue is causing trouble and extra work in migrations. We now define the connection property on the migration, plus define the connection on every `Schema`/`DB` facade call.

First, it's a bit cumbersome. Second, the worst side effect, if not doing so, is that in some situations migrations were ran even when `--pretend` was passed to the migrate command.

So from me it's a "not only an issue for you". This definitely could use some love.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by NickSdot** [comment]
@malkhazidartsmelidze do you cosider re-submitting this for Laravel 11/12?
