### ISSUE TITLE
losing auth sessions on ajax

### ISSUE THREAD

**Issue by faisal975Hexolt** [laravel/framework#53227]
### Laravel Version

11.0

### PHP Version

8.2.12

### Database Driver & Version

mysql

### Description

losing auth guard on employee guard . other guards are working with ajax .  database.sql is in repo . using sessions with database . 

go to http://127.0.0.1:8000/manage/login

user: SPaymentAdmin
pass:Anand@123

otp:123456 

then it call an ajax to load dashboard data .here on this call it loses session .

### Steps To Reproduce

go to http://127.0.0.1:8000/manage/login

user: SPaymentAdmin
pass:Anand@123

otp:123456 

then it call an ajax to load dashboard data .here on this call it loses session .

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
