### ISSUE TITLE
Concurrency facade not binding properly

### ISSUE THREAD

**Issue by wizzymore** [laravel/framework#53265]
### Laravel Version

11.28.1

### PHP Version

8.3.12

### Description

The new Concurrency package does not work in a Laravel 9 application that was gradually updated to version 11.
We are not doing anything custom, we are binding only 3 interfaces to the container and the rest of the application is just controllers views and inertia.

We are getting the following error when trying to use Concurrency and also from the IDE Helper package:

Exception: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\MultipleInstanceManager

### Steps To Reproduce

I don't know how to reproduce this, in new laravel apps running laravel 11 it works perfectly, our project was upgraded through the years to the latest version so we still have the old structure and the kernel files.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by wizzymore** [comment]
In config/app.php I had to add `Illuminate\Concurrency\ConcurrencyServiceProvider::class` in the 'providers' key.

**Comment by johanmolen** [comment]
@wizzymore thanks!

**Comment by alignwebs** [comment]
@wizzymore Thanks!
