### ISSUE TITLE
Interference character | (Straight line) In trans_choice function

### ISSUE THREAD

**Issue by MohammadZarifiyan** [laravel/framework#53286]
### Laravel Version

9.24

### PHP Version

8.1

### Description

When I use `trans_choice` and use straight line symbol (**|**) in the parameters, it causes the sentence structure to be messed up. It seems that Laravel first places the parameters in the sentences and then selects the sentence based on the _number_ parameter in `trans_choice`. While the correct way is to first select the correct sentence in terms of _number_, then replace the parameters.

### Steps To Reproduce

`home.php` file:
```php
return [
   'greeting' => '{0} Hello :name|[1,*] Hello :name, you have :count unread messages'
];
```
Usage:
```php
trans_choice('home.greeting', 0, ['name' => 'Alex | Moi']);
```
Above code must result in `Hello Alex | Moi`, But it results to `Hello Alex`.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by crynobone** [comment]
However, feel free to send a fix to `11.x` branch if you are able to do so.

**Comment by MohammadZarifiyan** [comment]
> Hey there,
> 
> Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.
> 
> Thanks!

Hello I upgraded the Laravel version to `v11`. The problem still persists.
