### ISSUE TITLE
Interference character | (Straight line) In trans_choice function

### ISSUE THREAD

**Issue by MohammadZarifiyan** [laravel/framework#53289]
### Laravel Version

11.29

### PHP Version

8.1

### Description

When I use `trans_choice` and use straight line symbol (**|**) in the parameters, it causes the sentence structure to be messed up. It seems that Laravel first places the parameters in the sentences and then selects the sentence based on the _number_ parameter in `trans_choice`. While the correct way is to first select the correct sentence in terms of _number_, then replace the parameters.

### Steps To Reproduce

`home.php` file:
```php
return [
   'greeting' => '{0} Hello :name|[1,*] Hello :name, you have :count unread messages'
];
```
Usage:
```php
trans_choice('home.greeting', 0, ['name' => 'Alex | Moi']);
```
Above code must result in `Hello Alex | Moi`, But it results to `Hello Alex`.

**Comment by zakariaarrid** [comment]
@MohammadZarifiyan 
try using HTML encoding for the pipe for _**quick solution**_
`trans_choice('home.greeting', 0, ['name' => 'Alex &#124; Moi']);`

**Comment by ShowravBiswas** [comment]
**You can use a custom placeholder**

<p>{!! str_replace('__PIPE__', '|', trans_choice('home.greeting', 0, ['name' => 'Alex __PIPE__ Moi'])) !!}</p>

Above code return your desired result which is : **Hello Alex | Moi**

**Comment by AndrewMast** [comment]
Correct me if I’m wrong, but could this be fixed by changing `$replace` with `[]` on line 203 of [Translator.php](https://github.com/laravel/framework/blob/5527e72efe5d86cf83afe21944a47fe9a0bdc406/src/Illuminate/Translation/Translator.php#L203)? `makeReplacements()` gets called at the end of the method so we shouldn’t be missing anything. I’m currently abroad on my phone so I can’t check. Is there any purpose to the current double calling of `makeReplacements()` since `line()` already calls it?

**Comment by rudiedirkx** [comment]
I don't understand Laravel issues. More than a year ago the same bug was reported: #48127 and closed. I'm happy it's fixed, but I don't get it.

@reneroth Happy days

**Comment by reneroth** [comment]
> I don't understand Laravel issues.

It’s a unique approach. It does keep the issues section very slim — honestly most projects have more open issues than can be solved in a lifetime — but at the same time it means real bugs are being closed without being solved. :/

The important learning for me is that while issues get closed easily, PRs also get merged easily, so it might be worth it just putting in a PR for smaller things.
