### ISSUE TITLE
QueueBusy event dispatched when there's 0 active jobs, and 100 delayed jobs

### ISSUE THREAD

**Issue by benascbr** [laravel/framework#53345]
### Laravel Version

11.29

### PHP Version

8.3.12

### Database Driver & Version

mongodb (    "mongodb/laravel-mongodb": "^4.0",)

### Description

After dispatching 100jobs, with delay 1000

 \Illuminate\Queue\Events\QueueBusy::class is fired.
 
 IMO it should consider that job has delay, and it's not busy at all at this moment. Thoughts?

### Steps To Reproduce

for($i=0;$i<100;$i++){ EmptyJob::dispatch()->delay(1000); }

**Comment by ismaildasci** [comment]
Hey! 👋

Yep, QueueBusy gets triggered even with delayed jobs, since Laravel doesn’t check if they’re actually ready to run. It just counts them all as “busy.”
Quick Workaround with Example

You could make a custom listener to skip jobs with a delay. Here’s a rough example:

php

Event::listen(\Illuminate\Queue\Events\QueueBusy::class, function ($event) {
    $pendingJobs = Queue::getPendingJobs();

    // Filter out delayed jobs
    $nonDelayedJobs = $pendingJobs->filter(function ($job) {
        return $job->delay === 0; // Only count jobs with no delay
    });

    if ($nonDelayedJobs->count() > 0) {
        // Handle "busy" condition for non-delayed jobs
        \Log::info('Queue is actually busy with non-delayed jobs.');
    }
});

This way, QueueBusy only considers jobs without a delay as “busy.” Hope it helps! 😊

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by benascbr** [comment]
@ismaildasci thank you, I've tried but no such method "getPendingJobs" for me.

This is what I've ended up using. (use at own risk)
```
    public function busyCount(QueueBusy $event): int
    {
        if($event->queue != 'default'){
            Log::error('Unknown queue in QueueBusyListener: ' . $event->queue);
        }

        if($event->connection != 'redis'){
            Log::error('Unknown connection in QueueBusyListener: ' . $event->connection);
        }

        $default = $event->queue;
        $totalCount = Queue::size($default);
        $delayedCount = Queue::getRedis()
            ->connection(null)
            ->zcard('queues:'.$default.':delayed');

        return $totalCount - $delayedCount;
    }
    ```
