### ISSUE TITLE
Advanced Route Model Binding with Multiple Conditions Failing

### ISSUE THREAD

**Issue by testuser060601** [laravel/framework#53375]
### Laravel Version

10

### PHP Version

8.1

### Database Driver & Version

MYSQL 8.0

### Description

Hey everyone, I’m facing a problem with Laravel’s route model binding. I need to bind a Product model based on multiple conditions, not just a single column. Specifically, I want to retrieve the product based on both the sku and status fields, but it’s not working as expected.

I tried overriding the resolveRouteBinding method in the Product model like this:

php

public function resolveRouteBinding($value, $field = null)
{
    return $this->where('sku', $value)->where('status', 'active')->first();
}

However, I keep getting a 404 error when I access the route with an inactive product or if the sku doesn't match exactly. I need some help understanding why this might be happening and if there's a better way to set up custom route bindings with multiple conditions. Thanks in advance!

Steps To Reproduce:

    Define the resolveRouteBinding method in the Product model to bind using both sku and status fields.
    In the route definition, use {product} as a parameter to bind the Product model to an endpoint.
    Attempt to retrieve a product by sku with status set to active, and observe the 404 error when conditions aren’t met exactly.

### Steps To Reproduce

The route should successfully bind the Product model when both sku and status conditions are met.

**Comment by ismaildasci** [comment]
Hey! 👋 It sounds like you’re on the right track with using resolveRouteBinding, but there are a few things you might want to try to make it work more reliably:

    Verify Your Route Definition: Make sure you’re defining the route correctly with the model type hint. For example:

    php

Route::get('/product/{product}', [ProductController::class, 'show']);

Laravel should automatically use the resolveRouteBinding method based on your setup.

Debug the Binding Logic: Add a log inside resolveRouteBinding to verify what’s happening. Sometimes, conditions might not be met exactly as you expect:

php

public function resolveRouteBinding($value, $field = null)
{
    \Log::info('Binding product with SKU: ' . $value);
    return $this->where('sku', $value)->where('status', 'active')->first();
}

This can help you track if sku and status conditions are matched correctly.

Alternative Approach Using RouteServiceProvider: You can define custom bindings directly in RouteServiceProvider, which might give you more flexibility:

php

    public function boot()
    {
        parent::boot();

        Route::bind('product', function ($value) {
            return Product::where('sku', $value)->where('status', 'active')->first();
        });
    }

    This approach allows you to define multiple conditions more explicitly.

Let me know if this helps, and feel free to share more details if it’s still not working. 😊
