### ISSUE TITLE
Update binding parameters is not supported for drivers other than MySQL and MariaDB.

### ISSUE THREAD

**Issue by kts27366** [laravel/framework#53405]
### Laravel Version

11.30

### PHP Version

8.3.6

### Database Driver & Version

PostgreSQL 17

### Description

Binding parameters is not supported for drivers other than MySQL and MariaDB, because in prepareBindingsForUpdate(), only MySQL and MariaDB perform the action

$values = Arr::flatten(array_map(fn ($value) => value($value), $values));

Other drivers do not include this step

https://github.com/laravel/framework/pull/50030

### Steps To Reproduce

```
Order::whereIn('id', [1,2,3])->update([
    'status' => DB::query()->selectRaw("CASE `{$uniqueKey}` {$cases} ELSE `{$column}` END", $bindings)
])
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
