### ISSUE TITLE
Model table generated with invalid name

### ISSUE THREAD

**Issue by AhmedElTabarani** [laravel/framework#53410]
### Laravel Version

11.9

### PHP Version

8.3.13

### Description

When i run `php artisan make:model approval-notes -m`, note that the name of the model is `approval-notes`
it will generate the model with the same name without parsed it

```php
class approval-notes extends Model
{
    use HasFactory;
}
```

![image](https://github.com/user-attachments/assets/4aece9ad-ef0e-4a60-8ef4-f3fa9d4efb85)

same in the migration file `Schema::create('approval-notes', ...`

what i expected is that remove `-` in the model name so `approval-notes` will be `approvalNotes`
and converted `-` to `_` in migration file so `approval-notes` will be `approval_notes`

### Steps To Reproduce

Just run:

```bash
$ php artisan make:model approval-notes -m

   INFO  Model [app/Models/approval-notes.php] created successfully.  

   INFO  Migration [database/migrations/2024_11_05_084844_create_approval-notes_table.php] created successfully.  
```

**Comment by crynobone** [comment]
You should aupply the class name
