### ISSUE TITLE
Cannot create a cache for one second after upgrading to Laravel 11

### ISSUE THREAD

**Issue by GalahadXVI** [laravel/framework#53425]
### Laravel Version

11.30.0

### PHP Version

8.3.13

### Description

I recently upgraded from Laravel `10.48.22` to Laravel `11.30.0` and all implementations of 

`cache()->remember($key, $value, now()->addSecond())` have broke.

However, this works:
`cache()->remember($key, $value, 1)` 

Switching back to Laravel 10 fixed the issue. 

I'm not sure if this is intentional or not - but it's undocumented and it caused our app to break.

![image](https://github.com/user-attachments/assets/72743824-3751-45d7-bcb4-a8e4efbbe646)
![image](https://github.com/user-attachments/assets/51b2cae1-9f0d-4fcf-a8b9-ae03d8954f68)

Both tests for Laravel 10 + 11 using Carbon `2.72.5`. 

### Steps To Reproduce

Just run the following:
```php
return [
  cache()->put("test_1", true, now()->addSecond()), 
  cache()->put("test_1", true, 1), 
  cache()->put("test_2", true, now()->addSeconds(2))
];
```

And it will output:
```php
[
    false,
    true,
    true,
  ]
  ```
  
  Interestingly, if the order changes, then it will output as true for all values.
  
  ```php
  return [
  cache()->put("test_1", true, 1), 
  cache()->put("test_1", true, now()->addSecond()), 
  cache()->put("test_2", true, now()->addSeconds(2))
];
```

will output:
```php
[
    true,
    true,
    true,
  ]
  ```

**Comment by timacdonald** [comment]
This issue is caused by time progressing during the execution of the PHP script.

You pass through `now()->addSecond()`, but by the time we actually can extract the time into the future of that value, microseconds have passed.

This results in a value of ~`0.9999` seconds, which we cast to an `int` and it becomes zero.

I've got a fix that should mostly fix this which I'll PR shortly.

**Comment by timacdonald** [comment]
PR up: https://github.com/laravel/framework/pull/53431
