### ISSUE TITLE
Vite - Add required crossorigin attribute to modulepreload

### ISSUE THREAD

**Issue by indykoning** [laravel/framework#53424]
### Laravel Version

11.30.0

### PHP Version

8.3

### Description

CORS (the crossorigin parameter) is **required** when dealing with scripts of `type="module"` or `rel="modulepreload"`
https://github.com/whatwg/html/issues/1888

Thus adding these links as headers will prove ineffective both in Http/2 ServerPush and Http/3 Early Hints.
We might want to default the `crossorigin` parameter to `anonymous` to ensure preloading will always be effective.
https://github.com/laravel/framework/blob/ca0617aeee70d5e69d7ce7f299af4d1c945cc32c/src/Illuminate/Foundation/Vite.php#L698

### Steps To Reproduce

Set up your regular laravel project, run `yarn && yarn run build `
add the link elements to the link header.

In a clean Laravel installation update your web.php to reflect
```php
    return response(view('welcome'))->header('Link', '<http://laravel.test/build/assets/app-<your hash>.js>; as=script; rel=preload');
```

See the console warning in your browser claiming the preload has not been used due to incompatible crossorigin between your link headers and your script.
![image](https://github.com/user-attachments/assets/1d1a2fe1-ac96-4497-95c5-9f768d3d853b)

Also note in the network tab how the script is downloaded twice.
![image](https://github.com/user-attachments/assets/bea5fd46-dd7c-4173-b9f3-5a5cb8e56163)

First during the preload, but since that is thrown away. The second time because it finds the script in your html.

**Comment by timacdonald** [comment]
I'm unable to reproduce this issue.

Set up a fresh laravel breeze application with Link headers applied to the urls and do not have any issues.

Will need more comprehensive reproduction steps to dig into this further.

**Comment by indykoning** [comment]
I've updated the reproduction steps and added some screenshots.
My current fix is to force the `crossorigin="anonymous"` attribute in 
```php
Vite::useScriptTagAttributes([
    "crossorigin" => "anonymous"
]);
```
or when collecting link elements to place into the link header

**Comment by timacdonald** [comment]
@indykoning, I think this might be because you are using `rel=preload'` instead of `rel=modulepreload"`, which will cause the double download and why the browser is saying it is not used.

Either way, I'd recommend ditching any manual work and ensure that the `\Illuminate\Http\Middleware\AddLinkHeadersForPreloadedAssets::class` middleware is applied to your routes so this is all handled automatically.

**Comment by indykoning** [comment]
Awesome! I didn't know that middleware was built in! 

It will not fully utilise early hints CDNs offer as that only supports preconnect and preload 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103#browser_compatibility
But that's out of the scope of this issue, and honestly out of Laravels scope I reckon. 

I've fixed it in 
https://github.com/justbetter/laravel-http3earlyhints
where it is in scope.

> @indykoning, I think this might be because you are using rel=preload' instead of rel=modulepreload", which will cause the double download and why the browser is saying it is not used.

I can confirm this is not a problem luckily, using early hints with Cloudflare this way with crossorigin added, it luckily downloads and parses it once!

Thank you for looking into this!

**Comment by timacdonald** [comment]
Based on the documentation on the Cloudflare docs, the `modulepreload` tag is considered to automatically generate early hint headers.

Of note for this conversation, adding any other attribute, including `crossorigin`, will stop Cloudflares the automatic generate of early hints.

<img width="815" alt="Screenshot 2024-11-11 at 09 32 42" src="https://github.com/user-attachments/assets/109e3ffd-9fbc-4bdc-9671-f9343ec495df">

https://developers.cloudflare.com/pages/configuration/early-hints/

Glad you got it sorted!

**Comment by indykoning** [comment]
You're awesome looking into it this deep!

By the looks of this topic as well, it wasn't possible but it _should_ be now to use modulepreload!
https://community.cloudflare.com/t/support-rel-modulepreload-for-automatic-link-header-generation/550051

The documentation indeed says crossorigin is not supported, which i agree with the PS on the community topic, is an odd choice... Especially since fonts are [required to have a crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload#cors-enabled_fetches)
But they must have their reason.

Weirdly enough that conflicts with what my experience is during testing
![Screenshot 2024-11-11 at 09 41 35](https://github.com/user-attachments/assets/f693735b-190b-42cd-97fb-acb83946bdc6)
Or perhaps they mean that they will not cache the script on their CDN in that case?

Anyhow, i've got some more testing and checking to do for my package! By the looks of it

**Comment by timacdonald** [comment]
Love this. Thanks for sharing you findings on all this.
