### ISSUE TITLE
"php artisan install:api --passport" Doesn't work in Php 8.3

### ISSUE THREAD

**Issue by Rusbelito** [laravel/framework#53445]
### Laravel Version

v11.30.0

### PHP Version

8.3

### Description

I ran into an error when trying to implement Passport in php 8.3

### Steps To Reproduce

1 i Created a new project 
2 i try add api sistem with passport `php artisan install:api --passport`

Answer :

```
php artisan install:api --passport
./composer.json has been updated
Running composer update laravel/passport
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/passport[v12.0.0, ..., v12.3.0] require lcobucci/jwt ^4.3|^5.0 -> satisfiable by lcobucci/jwt[4.3.0, 5.0.0, ..., 5.4.2].
    - lcobucci/jwt[4.3.0, 5.1.0, ..., 5.4.2] require ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
    - lcobucci/jwt 5.0.0 requires php ~8.1.0 || ~8.2.0 -> your php version (8.3.12) does not satisfy that requirement.
    - Root composer.json requires laravel/passport ^12.0 -> satisfiable by laravel/passport[v12.0.0, ..., v12.3.0].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp_8_3_12\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-sodium` to temporarily ignore these required extensions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
   INFO  Published API routes file.

 Would you like to use UUIDs for all client IDs? (yes/no) [no]:
 > yes
```

**Comment by crynobone** [comment]
The error message is clear regarding missing PHP extension required by dependencies of Passport.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Rusbelito** [comment]
> The error message is clear regarding missing PHP extension required by dependencies of Passport.

Oh sorry, the first time I installed it I did it with other dependencies and since the error was similar I thought it was the same, I ignored the extension, my experience is not that advanced and now my mistake is very obvious, thanks .
