### ISSUE TITLE
inconsistent behavior in routes web.php file after php artisan optimize and before php artisan optimize.

### ISSUE THREAD

**Issue by rajatvermaiam** [laravel/framework#53591]
### Laravel Version

11.31.0

### PHP Version

8.3.13

### Description

inconsistent behavior in routes web.php file after php artisan optimize and before php artisan optimize. i am providing steps to reproduce same behavior, it will be easy to understand there.

### Steps To Reproduce

in web.php suppose we have these routes like below:
Route::permanentRedirect('/', '/en');   //1st route
Route::get('en', [HomeController::class, 'homepage']);  //2nd route
Route::post('/', [GetController::class, 'getMedia']);   //3rd route

1. Enter "php artisan optimize:clear" command.
2. And submit an HTML form by " form action="{{route('download')}}" method="post" from second route. The third route is getting control.
3. Enter "php artisan optimize" command.
4. And submit an HTML form by " form action="{{route('download')}}" method="post" from second route.. The first route is getting control.

This is inconsistent behavior after optimize command .

**Comment by rajatvermaiam** [comment]
This is repo link that have same bug that i have described above:
https://github.com/rajatvermaiam/bug-report

please follow above step to reproduce same bug in this repo.

**Comment by crynobone** [comment]
`Route::permanentRedirect()` uses `Route::any()` and therefore can create a clashing route. Feel free if you want to submit a PR to improve generated routes via `route:cache` but we don't classify this as a bug.
