### ISSUE TITLE
MorphTo relations are broken in some cases since v11.33.0

### ISSUE THREAD

**Issue by sebj54** [laravel/framework#53624]
### Laravel Version

11.33.0

### PHP Version

8.3.13

### Description

Since version 11.33.0 and more precisely this commit: https://github.com/laravel/framework/commit/8528d04598f99f7cfa0f0aab56c170f8fd583024, the constraints applied on `MorphTo` relations have changed.

For the example, let's say I have the example relation from the docs: https://laravel.com/docs/11.x/eloquent-relationships#one-to-one-polymorphic-model-structure. So I have an `Image` model with an `imageable` relation (`MorphTo`), pointing to a `Post`.

Before that commit, the foreign key constraint was correctly added to the relation query: it added a where like this: 

```
[
        "type" => "Basic"
        "column" => "posts.id"
        "operator" => "="
        "value" => 252
        "boolean" => "and"
]
```

Now with the latest version, the only where is:

```
[
        "type" => "Null"
        "column" => ""
        "boolean" => "and"
]
```

This bug breaks some packages like https://github.com/kirschbaum-development/eloquent-power-joins.

### Steps To Reproduce

- Create a `MorphTo` relation (for example `Image::imageable`)
- Call the relation: `$relation = (new Image)->imageable()`
- Dump the relation and watch the `wheres` of the query
- Change your Laravel version from `11.32.x` to `11.33.x`

Feel free to ask if you need a proper reproduction to work on this but I think you have some test projects already covering this feature.

Thanks for your help!

**Comment by crynobone** [comment]
After reviewing the reproduction code above I wasn't able to replicate the scenario as claimed above:

```diff
    public function test_empty_morph_to_relation_has_correct_where(): void
    {
        $relation = (new Image())->imageable();
        $wheres = $relation->getQuery()->getQuery()->wheres;

+       dd($wheres);

        $this->assertContains([
            'type' => 'Null',
            'column' => '',
            'boolean' => 'and',
        ], $wheres);
    }
```

### Before v11.33.0

![CleanShot 2024-11-26 at 17 47 49](https://github.com/user-attachments/assets/f2bb4ba9-273d-47ed-8092-212e20d57a88)

### Current

![CleanShot 2024-11-26 at 17 48 12](https://github.com/user-attachments/assets/514d62d5-3aab-4dea-b38e-7516249bb4e4)

**Comment by sebj54** [comment]
Oh right, I see. So there must be a hardcoded check in `eloquent-power-joins` so.

But what is the point of this constraint? If there is no column for the where clause, why even add it to the query then?

**Comment by crynobone** [comment]
> But what is the point of this constraint? If there is no column for the where clause, why even add it to the query then?

The best bet right now is to assume the current behavior. I can only look further into this if you can provide a "real-world" use case where it was previously a working SQL and now generates an incorrect SQL via Laravel Framework and not 3rd party package.

**Comment by sebj54** [comment]
Allright then, I'll follow up the issue with the extension developer. Thanks for checking that out!
