### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by farzadaqajani** [laravel/framework#53652]
### Laravel Version

11.31.0

### PHP Version

8.3.14

### Database Driver & Version

MariaDB 11.4 on Windows 11

### Description

From time to time this error occurs while running the project:

`
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Users\myuser\PhpstormProjects\myproject\vendor\symfony\finder\Iterator\SortableIterator.php on line 51
`

This error only occurs in the development environment and on Windows. When I run the same project on WSL or Standalone Ubuntu, there is no problem. Also, this problem does not occur in the server and production environment.

Sometimes this error does not occur, but the project execution speed is still slower than WSL and Ubuntu. The php.ini values ​​are the same in all three environments.

I did some searching and found similar errors related to iterators and it was said that changing the session driver would solve it. I also changed the SESSION_DRIVER and CACHE_STORE to Redis. But the problem still persists.

If it helps, I use Livewire and MaryUI.

### Steps To Reproduce

To be honest, I don't know exactly how to reproduce this error. The project is nothing special and is a simple store. It has nothing more than Laravel built-in authentication system and a few CRUD and checkout operations.

Is there a way to find out exactly which part of the code this error occurs during execution?

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
