### ISSUE TITLE
App starts on a new port when the .env file got updated.

### ISSUE THREAD

**Issue by CodeAddictx10** [laravel/framework#53669]
### Laravel Version

11.33.2

### PHP Version

8.3.6

### Database Driver & Version

SQLITE

### Description

I noticed the app starts on a new port anytime I update the env file.

Here is an image:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/40aaa026-2016-49d2-8335-4356fae312c8">

### Steps To Reproduce

1. Create a new Laravel project using the latest version
2. Seve the project using `php artisan serve` or `composer run dev`
3.  Update the .env file

**Comment by Zeno97** [comment]
> You should be able to use `--no-reload` option to avoid restarting the server when `.env` changes.

Hello, I tried and it works but it doesn't read the new changes on .env realtime, so I have to shut down and restart each time.
Why is this unresolved?
