### ISSUE TITLE
Filesystem configuration with nested disks config

### ISSUE THREAD

**Issue by userstas** [laravel/framework#53681]
### Laravel Version

10.34.1

### PHP Version

8.3.8

### Description

I have filesystem disks config like
`'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'throw' => false,
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
            'throw' => false,
        ],

        's3' => [
            'watermarks' => [
                'driver' => 's3',
                'key' => env('AWS_ACCESS_KEY_ID'),
                'secret' => env('AWS_SECRET_ACCESS_KEY'),
                'region' => env('AWS_DEFAULT_REGION'),
                'bucket' => env('AWS_WATERMARKS_BUCKET'),
                'url' => env('AWS_WATERMARKS_BUCKET_URL'),
                'endpoint' => env('AWS_ENDPOINT'),
                'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            ],
            'media-library' => [
                'driver' => 's3',
                'key' => env('AWS_ACCESS_KEY_ID'),
                'secret' => env('AWS_SECRET_ACCESS_KEY'),
                'region' => env('AWS_DEFAULT_REGION'),
                'bucket' => env('AWS_MEDIA_LIBRARY_BUCKET'),
                'url' => env('AWS_MEDIA_LIBRARY_BUCKET_URL'),
                'endpoint' => env('AWS_ENDPOINT'),
                'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            ],
            'attachments' => [
                'driver' => 's3',
                'key' => env('AWS_ACCESS_KEY_ID'),
                'secret' => env('AWS_SECRET_ACCESS_KEY'),
                'region' => env('AWS_DEFAULT_REGION'),
                'bucket' => env('AWS_ATTACHMENTS_BUCKET'),
                'url' => env('AWS_ATTACHMENTS_BUCKET_URL'),
                'endpoint' => env('AWS_ENDPOINT'),
                'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            ],
    ],
`
I use laravel/framework version 11.22.0 and all works fine.
But after change laravel/framework version 11.34.1 and run `composer upgrade` I got error
<img width="768" alt="image" src="https://github.com/user-attachments/assets/55c278fc-c80c-486f-b264-0b3c6dd12c85">

### Steps To Reproduce

Write filesystem disks nested config and
change laravel/framework version  from 11.22.0 or older to 11.34.1 and run `composer upgrade`
<img width="768" alt="image" src="https://github.com/user-attachments/assets/55c278fc-c80c-486f-b264-0b3c6dd12c85">

**Comment by crynobone** [comment]
Laravel Framework doesn't accept nested configuration as suggested above and was not designed to work with such configurations.

**Comment by userstas** [comment]
> Laravel Framework doesn't accept nested configuration as suggested above and was not designed to work with such configurations.

Thank you for response, but everything worked before, but after the update it stopped. I thought it was some kind of bug.

**Comment by crynobone** [comment]
> but everything worked before, but after the update it stopped. I thought it was some kind of bug.

If you are using 3rd party packages that accept nested configuration you need to report this issue to the correct repository as we don't consider changes to cause above error as a bug as we never support nested configuration.

**Comment by userstas** [comment]
@crynobone I use laravel/medialibrary v11.10.1 for work with files and code like below works file
`$file_768_path = Storage::disk('s3.banners')->put($filename . '_768', $request->file('file_768'));
  $img_link_768 = Storage::disk('s3.banners')->url($file_768_path);`
  
  I think it doesn't so matter, cause i got error when laravel parse config files. 
  For parsing config files I don't use 3rd party packages.
