### ISSUE TITLE
MailManager fails with UnsupportedSchemeException since Symfony Mailer 7.2.0

### ISSUE THREAD

**Issue by gabsource** [laravel/framework#53704]
### Laravel Version

11.34.2

### PHP Version

8.3

### Description

Symfony Mailer now throw an UnsupportedSchemeException when the specified scheme is not in the allowed list (smtps, smtp).

https://github.com/symfony/mailer/compare/v7.1.6...v7.2.0#diff-034fdf635bc919f1ba58fb3cac83ce59f111a73c1ee72d63055f752c4b3668dd

MailManager::createSmtpTransport should set a default scheme to `'smtp'` instead of `''` (empty string).

```
[2024-11-29 14:48:09] local.ERROR: Symfony\Component\Mailer\Exception\UnsupportedSchemeException: The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps". in /site/vendor/symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php:28
#0 /site/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(202): Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory->create(Object(Symfony\Component\Mailer\Transport\Dsn))
```

### Steps To Reproduce

- Update composer dependencies.
- Set `MAIL_ENCRYPTION=null` in `.env` (use default `config/mail.php` from the framework)
- Send a mail with smtp transport.

**Comment by LocalHeroPro** [comment]
Issue still exists: https://github.com/laravel/framework/issues/53718
