### ISSUE TITLE
Exception when passing closure to `Route::uses()`

### ISSUE THREAD

**Issue by bilogic** [laravel/framework#53700]
### Laravel Version

10.48.25

### PHP Version

8.2.26

### Description

Exception when calling `Route::uses(function(){ ... });`, see code, happy to file a PR.

### Steps To Reproduce

```PHP
// this works
Route::get('/example')
    ->uses([MyController::class, 'index']);

// but this throws an exception `trim(): Argument #1 ($string) must be of type string, Closure given`
Route::get('/example')
    ->uses(fn() => [MyController::class, 'index']);
```

**Comment by Jacobs63** [comment]
Hello,

nowhere in the documentation does it state that such use-case should be possible.

Neither does the documentation recommend to use the `uses` method in any way when defining a route.

The recommended way to define a route is:
```php
Route::get('/example', [MyController::class, 'index'])
```

**Comment by crynobone** [comment]
Thanks @Jacobs63

**Comment by bilogic** [comment]
https://github.com/laravel/framework/blob/8ffd13c6c66d431450a08d78005feac2c332c72b/src/Illuminate/Routing/Route.php#L925-L932

Well, `uses()` does accept a closure which leads straight an exception

**Comment by bilogic** [comment]
https://github.com/laravel/framework/commit/cf797d1477cc801bafee124579136e9a33d7e787#diff-efe2a07687b9b821bbd99ae38a9329253f032e6df04bdea02bba9303a2b2beadR801

and I wonder which "users" @phroggyy is referring to here
