### ISSUE TITLE
Empty SMTP setting scheme

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/framework#53718]
### Laravel Version

11.34.2

### PHP Version

8.3.4

### Description

Error: `The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps".`

Right now we can't use application, because of changes within that area: https://github.com/laravel/framework/pull/53585/files.
It looks like `scheme` for `SMTP` can't be issued, because of default setting of `Mailpit` port is `1025` and `Laravel` don't get `scheme` from `mail.mailers.smtp.transport`. So logic inside that scope is incorrect.

Quick fix for that is add `mail.mailers.smtp.scheme = mail.mailers.smtp.scheme.transport`. But it don't have any sense.

Please fix it.

### Steps To Reproduce

1. Download `11.34.2` version of `Laravel`
2. Add supported `Mailpit`, Docs: https://laravel.com/docs/11.x/mail#mailtrap
4. Run `composer install`.
5. Open browser and type app url
![image](https://github.com/user-attachments/assets/b4eab007-87ad-4f40-a1ad-68bea0d455cf)

Ad 2.
Default mail config: https://github.com/laravel/laravel/blob/11.x/config/mail.php#L38
Inside `.env`: 
```
MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=noreply@local.com
MAIL_FROM_NAME="${APP_NAME}"
```

**Comment by LocalHeroPro** [comment]
So it was't completed yet and workaround because of fix, is't proper fixing. Only workaround.

**Comment by 760524mkfa00** [comment]
Just updated to 11.35 still having the same issue
