### ISSUE TITLE
Release method for Illuminate\Queue\Jobs\SqsJob

### ISSUE THREAD

**Issue by clslrns** [laravel/framework#5373]
There is [no way](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Queue/Jobs/SqsJob.php#L84) to release job back to an SQS queue before [`Default Visibility Timeout`](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AboutVT.html) expires. I suggest to implement `release` method.

Consider SQS `ChangeMessageVisibility` [docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html). This is exactly what we need to release the job onto the queue.

Here is my implementation:
```php
public function release($delay = 0)
{
	$this->sqs->changeMessageVisibility(array(
		'QueueUrl'          => $this->queue,
		'ReceiptHandle'     => $this->job['ReceiptHandle'],
		'VisibilityTimeout' => $delay
	));
 }
```

I also wrote the [test](https://github.com/clslrns/framework/blob/ba232b4b421f32a98894729aa341323a355c325e/tests/Queue/QueueSqsJobTest.php#L81).

**Comment by GrahamCampbell** [comment]
We're open to pull requests.
