### ISSUE TITLE
Colon needed in prefix after migration

### ISSUE THREAD

**Issue by ben221199** [laravel/framework#53732]
### Laravel Version

11

### PHP Version

8.3

### Database Driver & Version

Redis

### Description

When I migrated my website from Laravel 10 to Laravel 11, suddenly my session system didn't behave like it did before. After hours of investigating the problem, I found the problem.

In Laravel 10, the cache store prefix (`config/cache.php`) and the session id got concatenated as `$storePrefix.":".$sessionId`, where the colon wasn't part of the prefix. In Laravel 11, the cache store prefix (`config/cache.php`) and the session id gets concatenated as `$storePrefix.$sessionId`, where the colon isn't automatically added anymore, so I have to add the colon to the prefix myself. I didn't find any migration information about this, but it seems like a breaking change.

### Steps To Reproduce

Create a project in Laravel 10, get the cache store working using Redis (`config/cache.php` and `config/database.php`), optionally with the session layer too (`config/session.php`). Then migrate to Laravel 11.

**Comment by haztakki** [comment]
https://laravel.com/docs/11.x/upgrade#cache

**Comment by crynobone** [comment]
Thanks @haztakki

**Comment by ben221199** [comment]
Thanks @haztakki, I somehow missed it then.
