### ISSUE TITLE
Validation rule required_if_declined is not working

### ISSUE THREAD

**Issue by projct1** [laravel/framework#53743]
### Laravel Version

11.34.1

### PHP Version

8.3.10

### Database Driver & Version

MySQL 8.0

### Description

According to the documentation:

> [required_if_declined:anotherfield,...](https://laravel.com/docs/11.x/validation#rule-required-if-declined)
> The field under validation must be present and not empty if the anotherfield field is equal to "no", "off", 0, "0", false, or "false".

But it is not working, example below.

### Steps To Reproduce

```php
$input = [
    'average_bill' => [
        'from' => 0,
        'to' => 0
    ]
];

$rules = [
    'average_bill.from' => ['required_if_declined:average_bill.to'],
    'average_bill.to' => ['required_if_declined:average_bill.from'],
];

validator($input, $rules)->validate(); //passes
```

So, i have to create new rule like this:
```php
class AverageBillRule implements ValidationRule
{
    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        if (empty($value['from']) && empty($value['to'])) {
            $fail($attribute, 'Average bill is empty.');
        }
    }
}
```

**Comment by iammursal** [comment]
@projct1 
The validation seems to be working as expected.
Both fields are valid, as both are **required**, and both have value **0**.
As stated in the [doc](https://laravel.com/docs/11.x/validation#rule-required:~:text=and%20not%20empty.-,A%20field%20is%20%22empty%22%20if%20it%20meets%20one%20of%20the%20following%20criteria%3A,-The%20value%20is), a field is "**empty**" if it meets one of the following criteria:
- The value is **null**.
- The value is an **empty string**.
- The value is an **empty array** or **empty Countable object**.
- The value is an uploaded **file with no path**.

**Comment by crynobone** [comment]
Thanks @iammursal

**Comment by projct1** [comment]
> @projct1 The validation seems to be working as expected. Both fields are valid, as both are **required**, and both have value **0**. As stated in the [doc](https://laravel.com/docs/11.x/validation#rule-required:~:text=and%20not%20empty.-,A%20field%20is%20%22empty%22%20if%20it%20meets%20one%20of%20the%20following%20criteria%3A,-The%20value%20is), a field is "**empty**" if it meets one of the following criteria:
> 
> * The value is **null**.
> * The value is an **empty string**.
> * The value is an **empty array** or **empty Countable object**.
> * The value is an uploaded **file with no path**.

No...
`average_bill.from` required if `average_bill.to` is declined (in my case 0)
same with `average_bill.to`, it required if `average_bill.from` is declined (in my case 0)

**Comment by projct1** [comment]
> @projct1 The validation seems to be working as expected. Both fields are valid, as both are **required**, and both have value **0**. As stated in the [doc](https://laravel.com/docs/11.x/validation#rule-required:~:text=and%20not%20empty.-,A%20field%20is%20%22empty%22%20if%20it%20meets%20one%20of%20the%20following%20criteria%3A,-The%20value%20is), a field is "**empty**" if it meets one of the following criteria:
> 
> * The value is **null**.
> * The value is an **empty string**.
> * The value is an **empty array** or **empty Countable object**.
> * The value is an uploaded **file with no path**.

No...
`average_bill.from` required if `average_bill.to` is declined (in my case 0)
same with `average_bill.to`, it required if `average_bill.from` is declined (in my case 0)
![image](https://github.com/user-attachments/assets/4f5499fa-4aeb-4a56-b260-71c6bdaa7945)

**Comment by iammursal** [comment]
@projct1 
If you want only one of the fields to be filled, try using the [required_without](https://laravel.com/docs/11.x/validation#rule-required-without) validation rule

**Comment by iammursal** [comment]
@projct1 
Also, if you want to also include **0** as **empty**, you can write a custom validation logic using [Rule::requiredIf](https://laravel.com/docs/11.x/validation#rule-required-if)

**Comment by projct1** [comment]
> @projct1 If you want only one of the fields to be filled, try using the [required_without](https://laravel.com/docs/11.x/validation#rule-required-without) validation rule

Not working too, validation passes =\
```php
$rules [
    'average_bill.from' => ['required_without:average_bill.to'],
    'average_bill.to' => ['required_without:average_bill.from']
];
```

**Comment by projct1** [comment]
`required_if_declined` must works, but not working...
Bug?

**Comment by iammursal** [comment]
@projct1 
@projct1 
I think this should do the trick. The validation below ensures that only one field is allowed at a time: either `date.to` or `date.from`.
```php
[             
  'date.to' => Rule::prohibitedIf($request->has('date.from')),
  'date.from' => Rule::prohibitedIf($request->has('date.to')),
]
```

**Comment by projct1** [comment]
Thanks for trying to help :)
But, apparently, none of the native rules suit me. I check the average bill of a restaurant, which can be, for example:
1) from $30, then TO can be empty;
2) up to $500, then FROM can be empty;
3) from $30 to $500.

But the average bill cannot be 0 when FROM and TO are zero.
Therefore, the average bill FROM is required ONLY if the average bill TO is not selected (equal to 0).
A similar situation is with the average bill TO, which must be greater than zero ONLY WHEN the average bill TO is not selected (equal to 0).
Therefore, the validation rules cannot skip values ​​from and to equal to zero.
Thus, in any case, one of these values ​​will be specified.
