### ISSUE TITLE
The exception renderer resource `dist` folder is missing in version 11.31, causing exception render to fail.

### ISSUE THREAD

**Issue by DonAlkens** [laravel/framework#53750]
### Laravel Version

11.31

### PHP Version

8.2

### Database Driver & Version

MYSQL 8.x

### Description

When Laravel is trying to render an exception page on development, the view renderer tries to load assets like stylesheets and others from the dist folder located inside the exceptions resources, but this file is missing in Laravel 11.31 which caused the app to resolve to a Symfony exception page stating that the resources file .../dist/style.css does not exist.

### Steps To Reproduce

Install a new Laravel app by specifying the version 11.31
Set up your environment variables and connect to Database.
Run the app and the exception will pop up showing a Symfony error page.

**Comment by crynobone** [comment]
Does the error exists on the latest version?

**Comment by crynobone** [comment]
Unable to replicate the issue on 11.31 or the latest version.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
