### ISSUE TITLE
RefreshDatabase not refreshing DB

### ISSUE THREAD

**Issue by katzda01** [laravel/framework#53758]
### Laravel Version

11.31

### PHP Version

8.3

### Database Driver & Version

:memory:

### Description

After upgrading to latest Laravel 11, my feature tests started to fail due to RefreshDatabase trait not refreshing the DB.

Adding `RefreshDatabaseState::$migrated = false;` to this function fixed the issue. I'm not sure what changed in the framework from last version but running each test individually passes but together they fail on "table does not exist" error.

```
    Illuminate\Foundation\Testing\RefreshDatabase.php

    protected function restoreInMemoryDatabase()
    {
        $database = $this->app->make('db');

        foreach ($this->connectionsToTransact() as $name) {
            if (isset(RefreshDatabaseState::$inMemoryConnections[$name])) {
                $database->connection($name)->setPdo(RefreshDatabaseState::$inMemoryConnections[$name]);
            }
        }
        RefreshDatabaseState::$migrated = false;
    }
```

Having this in the base tests/TestCase.php class fixes it as a workaround.

```
    public function setUp(): void
    {
        parent::setUp();

        RefreshDatabaseState::$migrated = false;
    }
```

### Steps To Reproduce

I think the problem arrizes when using multiple DB connections for different models. These models override default connection with 

protected $connection = 'mysql1';  // this is default
protected $connection = 'mysql2';  // this is used in User model

And so in the tests, we have to use these hardcoded connections, which is why for testing we override just what matters

phpunit.xml
```
<server name="DB_FIRST_DRIVER" value="sqlite"/>
<server name="DB_FIRST_DATABASE" value=":memory:" />
<server name="DB_SECOND_DRIVER" value="sqlite"/>
<server name="DB_SECOND_DATABASE" value=":memory:"/>
```

------
full example
------

.env
```
APP_NAME=ExampleApp
APP_KEY=<generate something>
APP_DEBUG=true
```

User model
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $connection = 'SECOND';
}
```

config/database.php
```
   'default' => env('DB_CONNECTION', 'FIRST'),

    'connections' => [
      'FIRST' => [
          'host' => env('DB_FIRST_WRITE_HOST', '127.0.0.1'),
          'port' => env('DB_FIRST_WRITE_PORT', '3306'),
          'username' => env('DB_FIRST_WRITE_USERNAME', ''),
          'password' => env('DB_FIRST_WRITE_PASSWORD', ''),
          'sticky' => env('DB_FIRST_STICKY', false),
          'driver' => env('DB_FIRST_DRIVER', 'mysql'),
          'database' => env('DB_FIRST_DATABASE', 'FIRST'),
          'unix_socket' => env('DB_FIRST_SOCKET', ''),
          'charset' => 'utf8mb4',
          'collation' => 'utf8mb4_unicode_ci',
          'prefix' => '',
          'prefix_indexes' => true,
          'strict' => true,
          'engine' => null,
          'options' => extension_loaded('pdo_mysql') ? array_filter([
              PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
          ]) : [],
      ],

      'SECOND' => [
          'host' => env('DB_SECOND_READ_HOST', '127.0.0.1'),
          'port' => env('DB_SECOND_READ_PORT', '3306'),
          'username' => env('DB_SECOND_READ_USERNAME', ''),
          'password' => env('DB_SECOND_READ_PASSWORD', ''),
          'sticky' => env('DB_SECOND_STICKY', false),
          'driver' => env('DB_SECOND_DRIVER', 'mysql'),
          'database' => env('DB_SECOND_DATABASE', 'SECOND'),
          'unix_socket' => env('DB_SECOND_SOCKET', ''),
          'charset' => 'utf8mb4',
          'collation' => 'utf8mb4_unicode_ci',
          'prefix' => '',
          'prefix_indexes' => true,
          'strict' => true,
          'engine' => null,
          'options' => extension_loaded('pdo_mysql') ? array_filter([
              PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
          ]) : [],
      ],
    ],
```

```
<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    public function setUp(): void
    {
        parent::setUp();

        $this->user = User::factory()->create([
          'id' => 1
        ]);
    }

    public function testUnauthenticated()
    {
        $this->assertTrue(true);
    }

    public function testUsersCannotShareReportIdViaCache()
    {
        $this->assertTrue(true);
    }
}
```

```
<?php

namespace Tests;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\RefreshDatabaseState;

abstract class TestCase extends BaseTestCase
{
  protected function setUp(): void
  {
      parent::setUp();
      // RefreshDatabaseState::$migrated = false;    //uncomment and all tests will pass!
  }
}
```

migration
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::connection('SECOND')->create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    public function down(): void
    {
    }
};
```

phpunit.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory>tests/Feature</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory>app</directory>
        </include>
    </source>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_STORE" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <server name="DB_FIRST_DRIVER" value="sqlite"/>
        <server name="DB_FIRST_DATABASE" value=":memory:" />
        <server name="DB_SECOND_DRIVER" value="sqlite"/>
        <server name="DB_SECOND_DATABASE" value=":memory:"/>
    </php>
</phpunit>

```

User factory
```
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}

```

**Comment by crynobone** [comment]
@stancl I believe your recent #53635 PR should be able to solve this.

@katzda01 can you check #53635 as well

**Comment by crynobone** [comment]
```xml
<server name="DB_FIRST_DRIVER" value="sqlite"/>
<server name="DB_FIRST_DATABASE" value="file:first?mode=memory" />
<server name="DB_SECOND_DRIVER" value="sqlite"/>
<server name="DB_SECOND_DATABASE" value="file:second?mode=memory"/>
```

Something like above.

**Comment by stancl** [comment]
Possibly, if the connection is being disconnected at some point.

FWIW the DSN string should possibly also include `&cache=shared`, not sure. The docs are a bit unclear on that.

It's an old feature for improved read performance (but potentially inconsistent writes?) that [isn't recommended anymore](https://www.sqlite.org/sharedcache.html) but every mention of [`mode=memory`](https://www.sqlite.org/inmemorydb.html) I saw also used `cache=shared`. So my understanding is that it's discouraged with actual files but since the docs examples for `mode=memory` used it, I do too.

**Comment by katzda01** [comment]
@crynobone
I checked out 11.x-dev branch into which #53635 was merged and 

First of all that did NOT resolve the issue.

I ran my unit tests with this flag and without. 
RefreshDatabaseState::$migrated = false;

With: ..E....E.FEEEE.E.. errors unrelated to this
Without: .EEEEEEEEEEEEEEEEE
All errors say "General error: 1 no such table: user...."

Not to mention I'm getting this error after composer update:

Could not scan for classes inside "/srv/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php" which does not appear to be a file nor a folder

In ClassMapGenerator.php line 131:
                                                                                                                                                                     
  Could not scan for classes inside "/srv/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php" which does not appear to be a file nor a folder

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by katzda01** [comment]
@crynobone In the "Steps to reproduce" I've shared full content of all the files to to changed to reproduce the issue. Can you first try to reproduce it with the information I provided? I did use the latest laravel installer. I would've submitted a PR straight away here but I don't have write access.

**Comment by stancl** [comment]
The PR is already part of latest Laravel, no need to change your composer dependencies. Just try what crynobone suggested.

**Comment by FurkiFor** [comment]
Temporary Solution for RefreshDatabase with Multiple In-Memory Connections
To resolve the issue with RefreshDatabase not resetting in-memory databases (:memory:) for multiple connections in Laravel 11, you can add the following to your base TestCase:
`namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\RefreshDatabaseState;

abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        // Reset migration state to ensure migrations run for each test
        RefreshDatabaseState::$migrated = false;
    }
}
`
RefreshDatabaseState::$migratedThe flag is set to true after the first migration run, even for in-memory databases that are reset between tests. By explicitly resetting this flag, migrations will rerun for each test, preventing "table does not exist" errors.

This is a quick and effective workaround until a more robust fix is implemented in the framework.

**Comment by joelbladt** [comment]
Your **phpunit.xml** file uses `<server>` tags to configure variables (e.g., **DB_FIRST_DRIVER**), but Laravel expects these settings to be defined as environment variables using `<env>` tags. This difference is important because Laravel retrieves its configuration from **.env** files or directly from `<env>` tags in the **phpunit.xml** file. The `<server>` tags are handled by PHP itself, but Laravel ignores them because it specifically looks for environment variables.

**Fix:** Replace the `<server>` tags with `<env>` tags so Laravel can recognize these variables as intended:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory>tests/Feature</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory>app</directory>
        </include>
    </source>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_STORE" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="DB_FIRST_DRIVER" value="sqlite"/>
        <env name="DB_FIRST_DATABASE" value=":memory:"/>
        <env name="DB_SECOND_DRIVER" value="sqlite"/>
        <env name="DB_SECOND_DATABASE" value=":memory:"/>
    </php>
</phpunit>
```

This ensures that Laravel correctly picks up the database configuration during testing.

**Comment by stancl** [comment]
That's a method on a class you control as my PR mentions. Try overriding it to return:
```php
protected function usingInMemoryDatabase()
{
    $default = config('database.default');
    $database = config("database.connections.$default.database");

    return $database === ':memory:' || str_contains($database, 'mode=memory');
}
```
The PR adding the feature in is slim and focused on core Laravel logic rather than helper traits that can be easily modified by the user. If such overrides work well and people use them often the change can be submitted in another PR.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
