### ISSUE TITLE
Calling `->index()` after `constrained()` sets foreign key name to `1`

### ISSUE THREAD

**Issue by carestad** [laravel/framework#53768]
### Laravel Version

11.34.2

### PHP Version

8.4.1

### Database Driver & Version

Postgres 16

### Description

In migrations, chaining `->index()` on a `foreignId()`, `foreignUlid()` or `foreignUuid()` column _after_  `->constrained()`, will lead to the foreign key being named `1` instead of `<table_name>_<column_name>_foreign` as expected.

### Steps To Reproduce

In a fresh application, if I add a migration that contains this:

```php
Schema::create('foos', function (Blueprint $table) {
    $table->ulid('id')->primary();
});

Schema::create('example', function (Blueprint $table) {
    $table->foreignUlid('foo_id')->nullable()->constrained('foos')->nullOnDelete()->index();
});
```

The foreign key is just named `1`.

If I change the migration and call `->index()` right after `foreignUlid()` instead, the foreign key is named `example_foo_id_foreign` instead. Example:

```php
Schema::create('foos', function (Blueprint $table) {
    $table->ulid('id')->primary();
});

Schema::create('example', function (Blueprint $table) {
    $table->foreignUlid('foo_id')->index()->nullable()->constrained('foos')->nullOnDelete();
});
```

I have only tested this with Postgres, not sure if it affects MySQL or other DB types.

**Comment by crynobone** [comment]
https://github.com/laravel/framework/blob/7db7ea950d3df663391718730f4490a4e189234a/src/Illuminate/Database/Schema/ForeignIdColumnDefinition.php#L53-L56


Wouldn't using `constrained()` already called `Blueprint::foreign()` and add indexing?

**Comment by carestad** [comment]
> https://github.com/laravel/framework/blob/7db7ea950d3df663391718730f4490a4e189234a/src/Illuminate/Database/Schema/ForeignIdColumnDefinition.php#L53-L56
> 
> Wouldn't using `constrained()` already called `Blueprint::foreign()` and add indexing?

It adds a foreign key, but in postgres, i don't think a foreign key is an index. In mysql and mariadb it also works as an index (or it adds an index as well when adding foreign keys). As per https://stackoverflow.com/a/970605/1223692 (although not particularly new that SO thread.)

Either way, it is the _naming_ of said index that has a weird behaviour here

**Comment by crynobone** [comment]
> Either way, it is the naming of said index that has a weird behaviour here

Yes it seems weird, but calling `constraints()` return `ForeignKeyDefinition` definition as no longer an instance of `ForeignIdColumnDefinition` when you run `$table->foreignUlid('foo_id')` therefore changing `index()` here cause it to call `index(true)` due it being 2 different class.

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\ForeignIdColumnDefinition;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('foos', function (Blueprint $table) {
            $table->ulid('id')->primary();
        });

        Schema::create('example', function (Blueprint $table) {
            tap($table->foreignUlid('foo_id')->nullable(), function (ForeignIdColumnDefinition $column) {
                $column->constrained('foos')->nullOnDelete();
            })->index();
        });
    }
}
```

![CleanShot 2024-12-06 at 17 44 33](https://github.com/user-attachments/assets/f0c2edb8-e1a7-4905-b03c-488b398db0d6)
