### ISSUE TITLE
firstWhere is requiring setting a $value parameter even it's null

### ISSUE THREAD

**Issue by avinmaster** [laravel/framework#53797]
### Laravel Version

10.48.25

### PHP Version

8.2

### Description

The `firstWhere` method in Laravel's Eloquent Builder class expects the `$value` parameter to be explicitly passed when the `$operator` is provided. If you remove null from the `firstWhere` call, it may cause a mismatch in the number of arguments, leading to a crash.  Here's the relevant part of the `firstWhere` method:
```php
public function firstWhere($column, $operator = null, $value = null, $boolean = 'and')
{
    return $this->where(...func_get_args())->first();
}
```

The method expects a specific number of arguments, and if the `$value` argument is omitted, it can cause a mismatch in the number of arguments, leading to a crash. To avoid this, we should always provide null for the `$value` argument if you don't need to specify it.

**We need to remove default value of $value.**

### Steps To Reproduce

```php
Book::firstWhere('price', '!=', null)
// I should be able to do so with default value, but it will not work:
Book::firstWhere('price', '!=')
```

**Comment by crynobone** [comment]
Thanks @macropay-solutions

**Comment by avinmaster** [comment]
@macropay-solutions I fully understand it, but when it's highlighted by IDE and by static analyzers, you start to think, that something here is wrong. I can't figure out what is for now (it seems like counting arguments logic is not quite right).
