### ISSUE TITLE
[5.0] Handle InnoDB Deadlocks By Re-Attempting Transactions

### ISSUE THREAD

**Issue by BlueHayes** [laravel/framework#5380]
I think Laravel should have built-in support for re-attempting transactions when they fail due to a deadlock. I noticed there was a recent update to re-attempt queries when the connection has "gone away" so I guess this is similar.

The exact error MySQL gives is:
````
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
````

The MySQL docs (http://dev.mysql.com/doc/refman/5.0/en/innodb-deadlocks.html) state:
> Normally, you must write your applications so that they are always prepared to re-issue a transaction if it gets rolled back because of a deadlock.

and

> Always be prepared to re-issue a transaction if it fails due to deadlock. Deadlocks are not dangerous. Just try again.

I think this would help make the framework more "stable" (or accommodating) than it is now, handling somewhat expected cases such as InnoDB locking.

Cheers

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by nakupanda** [comment]
How was it going? Did meet the same issue when setting transaction isolation level to 'SERIALIZABLE'.

**Comment by InstanceOfMichael** [comment]
Would this be possible as a middleware? Otherwise you should use the function provided by @mhayes14 it looks simple enough.

I think it would be insane (as in bad automagic) if Laravel automatically retried transactions by default.

**Comment by Modelizer** [comment]
@mhayes14 Idea is good, but we need to think. Can we implement queue system in transactions if 2 transactions are hitting same table at a time then they should be process one by one! In this way we can handle deadlocks, And also keeping your feature in mind we can make it more robust! 

@nakupanda as far as i know `SERIALIZABLE` will only work for ready statements. Correct me if i am wrong :)

**Comment by cgarnier** [comment]
Is there a way to disable this feature ? It make duplicate on my database.
