### ISSUE TITLE
Fillable not working properly

### ISSUE THREAD

**Issue by projct1** [laravel/framework#53820]
### Laravel Version

11.34.2

### PHP Version

8.3.10

### Database Driver & Version

MySQL 8.0

### Description

Docs https://laravel.com/docs/11.x/eloquent#mass-assignment-exceptions says:
> By default, attributes that are not included in the $fillable array are silently discarded when performing mass-assignment operations.

But i get an error when I try to insert a field that doesn't exist in the database and that is not in `$fillable`.

### Steps To Reproduce

```php
class Birthday extends Model
{
    protected $fillable = [
        'existing_field_1',
        'existing_field_2'
    ];
}

Birthday::create([
    'existing_field_1' => 'Some value',
    'non_existing_field' => 'Some value'
]);
```
Got error `Column not found: 1054 Unknown column 'non_existing_field' in 'field list'`.
That is field `non_existing_field` are not discarded.
I tried to use `Model::preventSilentlyDiscardingAttributes(true)` and `Model::preventSilentlyDiscardingAttributes(false)`, but nothing changes, mass assignment exception does not occur.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by projct1** [comment]
@crynobone Sry, my mistake, here is actual problem https://github.com/laravel/framework/issues/53830
