### ISSUE TITLE
PHP 8.4 Implicitly marking parameter $specificity as nullable is deprecated tijsverkoyen/css-to-inline-styles

### ISSUE THREAD

**Issue by mralston** [laravel/framework#53828]
### Laravel Version

11.34.2

### PHP Version

8.4.1

### Database Driver & Version

MySQL 8.0.31-google (Google-managed Cloud SQL)

### Description

Laravel requires tijsverkoyen/css-to-inline-styles. The latest version of this package throws deprecation warnings on PHP 8.4.
```
PHP Deprecated:  TijsVerkoyen\CssToInlineStyles\Css\Property\Processor::convertToObject(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead in vendor/tijsverkoyen/css-to-inline-styles/src/Css/Property/Processor.php on line 69
PHP Deprecated:  TijsVerkoyen\CssToInlineStyles\Css\Property\Processor::convertArrayToObjects(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead in vendor/tijsverkoyen/css-to-inline-styles/src/Css/Property/Processor.php on line 94
PHP Deprecated:  TijsVerkoyen\CssToInlineStyles\Css\Property\Property::__construct(): Implicitly marking parameter $specificity as nullable is deprecated, the explicit nullable type must be used instead in vendor/tijsverkoyen/css-to-inline-styles/src/Css/Property/Property.php on line 30
```
I realise this is an issue for the maintainer of that package to fix, but the last activity on the project was 5 months ago, so I'm not optimistic of a quick fix from them.

### Steps To Reproduce

1. Create a Laravel 11 application
2. Create a Markdown Mailable
3. Create a Console Command to send the mail
4. Run the Console Command

**Comment by Jubeki** [comment]
This problem was fixed 5 months ago, it just wasn't releases yet:
https://github.com/tijsverkoyen/CssToInlineStyles/commit/698d3de2eea82519c2acc9855718c4e87aaa2a9a

There is also an open issue which asks for the release:
- https://github.com/tijsverkoyen/CssToInlineStyles/issues/248

**Comment by mralston** [comment]
Yeah, I'd seen that issue. I guess it just became a bit more urgent...

**Comment by crynobone** [comment]
@mralston Can you share your `config/logging.php` file and `.env` related to logs (please remove any secret keys etc)

**Comment by crynobone** [comment]
Looks like this has been fixed upstream.
