### ISSUE TITLE
Json fillable not working properly

### ISSUE THREAD

**Issue by projct1** [laravel/framework#53830]
### Laravel Version

11.34.2

### PHP Version

8.3.10

### Database Driver & Version

MySQL 8

### Description

```php
protected $fillable = [
    'name',
    'email',
    'data',
    'password',
    'data->some_value'
];
```
No matter what keys I allow for the `data` field, they will be successfully added, ignoring `$fillable`.

### Steps To Reproduce

1) Clone repo https://github.com/projct1/laravel-json-casts
2) Change key (or add) in `$fillable` in User model from `data` to `data->allowed_field`
3) Run `php artisan migrate`
4) Run `php artisan serve`
5) Open link.

And you will see that the key which is not specified in `$fillable` will be added successfully.

**Comment by crynobone** [comment]
```php {4}
protected $fillable = [
    'data', // This means you can assign any value to `data`, including `custom_value`. 
    'data->some_value',
];
```

You should remove `data` from fillable if you want to be strict.

**Comment by projct1** [comment]
> ```
> protected $fillable = [
>     'data', // This means you can assign any value to `data`, including `custom_value`. 
>     'data->some_value',
> ];
> ```
> 
> You should remove `data` from fillable if you want to be strict.

In this case, the field is ignored completely, even when a specific key is allowed. Just try:
```php
protected $fillable = [
    'name',
    'email',
    'data->custom_value',
    'password',
];

App\Models\User::create([
    'name' => 'Test',
    'email' => 'test@test.com',
    'password' => Hash::make('password'),
    'data' => [
        'custom_value' => 1
    ]
]);
```
As result will be this, data ignored completely despite `$fillable` allowing `custom_value`:
```json
{
"name": "Test",
"email": "test@test.com",
"updated_at": "2024-12-11T12:13:35.000000Z",
"created_at": "2024-12-11T12:13:35.000000Z",
"id": 2
}
```

**Comment by projct1** [comment]
@crynobone Dude, can you check again plz? I commented above.
