### ISSUE TITLE
Symfony\Component\Mailer\Exception\TransportException after upgrading to 11.35.0

### ISSUE THREAD

**Issue by laserhybiz** [laravel/framework#53861]
### Laravel Version

11.35.0

### PHP Version

8.3.13

### Description

After upgrading to 11.35.0 in two projects I get these errors when trying to send a mail
```
Connection could not be established with host \"ssl://smtp.resend.com:587\": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:0A00010B:SSL routines::wrong version number
```

```
Connection could not be established with host \"ssl://smtp.gmail.com:587\": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

### Steps To Reproduce

Set .env mail variables to
```
MAIL_MAILER=smtp
MAIL_PORT=587
MAIL_ENCRYPTION=tls
```
and send a mail

**Comment by laserhybiz** [comment]
Looks like this is caused by https://github.com/laravel/framework/pull/53749

**Comment by crynobone** [comment]
Can you test it with `MAIL_ENCRYPTION=(null)`

Symfony Mailer has removed support for encryption in version 4.4 but we still have these options from `swiftmailer` era.

**Comment by laserhybiz** [comment]
@crynobone it does work fine when I set MAIL_ENCRYPTION to null.
I still think this should be considered as a BC since by just updating the minor version the current functionality breaks.

**Comment by laserhybiz** [comment]
and the encryption option [is still in the skeleton](https://github.com/laravel/laravel/blob/11.x/.env.example#L56)

**Comment by crynobone** [comment]
Either way, keeping `MAIL_ENCRYPTION=(null)` should solve your project right now.
