### ISSUE TITLE
Http requests being dropped when being executed on queues operated by Horizon

### ISSUE THREAD

**Issue by mahiarirani** [laravel/framework#53860]
### Laravel Version

11.34.1

### PHP Version

8.3.14

### Database Driver & Version

pgsql + redis

### Description

I am building an application using Laravel Sail, Octane, and FrankenPHP. My setup includes Horizon to run workers that process jobs in the queue. One of these jobs involves making an HTTP request to an external API, which takes approximately 3–4 minutes to respond.

Despite adjusting multiple timeout configurations, the HTTP request in the queued job fails silently when it exceeds 90 seconds. There are no exceptions, logs, or errors, even though the external API successfully responds within the expected timeframe. The job continues running until it hits its timeout and eventually fails.

### Steps To Reproduce

1. Create a queued job that makes an HTTP request to an external API taking ~3–4 minutes to respond.
2. Configure the following timeouts:
  - max_execution_time in php.ini (CLI): 0 (unlimited).
  - REDIS_QUEUE_RETRY_AFTER: 320.
  - Job $timeout: 300.
  - HTTP client request and connection timeouts: 300.
4. Dispatch the job.
5. Observe behavior when the request takes:
  - Less than 90 seconds: The job processes successfully.
  - More than 90 seconds: The HTTP request is abandoned, and no response is logged or handled.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
