### ISSUE TITLE
Json keys in $fillable and $casts are ignored

### ISSUE THREAD

**Issue by projct1** [laravel/framework#53878]
### Laravel Version

11.34.2

### PHP Version

8.3.10

### Database Driver & Version

MySQL 8.0

### Description

```php
class MyModel extends Model
{
    protected $fillable = [
        'name',
        'data->some_value'
    ];
}

$model = MyModel::create([
    'name' => 'Some name',
    'data' => ['some_value' => 1]
]);

//got `null` (`$fillable` ignored)
dd($model->data);
```
Same situation with `$casts`:
```php
class MyModel extends Model
{
    protected $fillable = [
        'name',
        'data'
        //'data->custom_value' (the presence or absence of this does not matter here)
    ];

    protected function casts(): array
    {
        return [
            //'data' => 'json', (the presence or absence of this does not matter here)
            'data->custom_value' => 'bool'
        ];
    }
}

$model = MyModel::create([
    'name' => 'Some name',
    'data' => ['custom_value' => 1]
]);

//got `1`, not `true` (`$casts` ignored)
dd($model->data->custom_value);
```

### Steps To Reproduce

1) Fresh install laravel;
2) Add `data` field as `json`;
3) Try to create any model.

**Comment by crynobone** [comment]
The above casts format is not supported by Laravel, please create custom Cast class if you need this: https://laravel.com/docs/11.x/eloquent-mutators#anonymous-cast-classes

**Comment by projct1** [comment]
> The above casts format is not supported by Laravel, please create custom Cast class if you need this: https://laravel.com/docs/11.x/eloquent-mutators#anonymous-cast-classes

What about fillable?

**Comment by crynobone** [comment]
>  What about fillable?

Not a bug. This is not the place to ask for support. Issue should be used only to send in confirmed bug.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by projct1** [comment]
> > What about fillable?
> 
> Not a bug. This is not the place to ask for support. Issue should be used only to send in confirmed bug.

Can you just try it without immediately autoclosing issue, plz?
Json keys in `$fillable` really ignoring...

**Comment by crynobone** [comment]
> Can you just try it without immediately autoclosing issue, plz?

Done the check the first time you send the issue, inspected the Laravel Framework code, looks at existing tests and everything are working as expected.

**Comment by projct1** [comment]
> > Can you just try it without immediately autoclosing issue, plz?
> 
> Done the check the first time you send the issue, inspected the Laravel Framework code, looks at existing tests and everything are working as expected.

How did you check?
Here i have fresh laravel install https://skrinshoter.ru/vTAZ6mmn8rX

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by projct1** [comment]
Even if i try to save json as string, `data` is not saving:
```php
$model = App\Models\User::create([
    'name' => 'Test',
    'email' => 'test@test.com',
    'password' => Hash::make('password'),
    'data' => '{"custom_value":1}'
]);

dd($model->data); //null
```

**Comment by marius-mcp** [comment]
@projct1 the above is called in 
\Illuminate\Database\Eloquent\Model::fill

```php
    /**
     * Fill the model with an array of attributes.
     *
     * @param  array  $attributes
     * @return $this
     *
     * @throws \Illuminate\Database\Eloquent\MassAssignmentException
     */
    public function fill(array $attributes)
    {
        $totallyGuarded = $this->totallyGuarded();

        $fillable = $this->fillableFromArray($attributes); /// here ------------------------------------------

        foreach ($fillable as $key => $value) {
            // The developers may choose to place some attributes in the "fillable" array
            // which means only those attributes may be set through mass assignment to
            // the model, and all others will just get ignored for security reasons.
            if ($this->isFillable($key)) {
                $this->setAttribute($key, $value);
            } elseif ($totallyGuarded || static::preventsSilentlyDiscardingAttributes()) {
                if (isset(static::$discardedAttributeViolationCallback)) {
                    call_user_func(static::$discardedAttributeViolationCallback, $this, [$key]);
                } else {
                    throw new MassAssignmentException(sprintf(
                        'Add [%s] to fillable property to allow mass assignment on [%s].',
                        $key, get_class($this)
                    ));
                }
            }
        }

        if (count($attributes) !== count($fillable) &&
            static::preventsSilentlyDiscardingAttributes()) {
            $keys = array_diff(array_keys($attributes), array_keys($fillable));

            if (isset(static::$discardedAttributeViolationCallback)) {
                call_user_func(static::$discardedAttributeViolationCallback, $this, $keys);
            } else {
                throw new MassAssignmentException(sprintf(
                    'Add fillable property [%s] to allow mass assignment on [%s].',
                    implode(', ', $keys),
                    get_class($this)
                ));
            }
        }

        return $this;
    }

```

**Comment by projct1** [comment]
> @projct1 You invented a fillable key structure that is not supported by laravel
> 
> \Illuminate\Database\Eloquent\Concerns\GuardsAttributes::fillableFromArray array_intersect_key is used so your key (data->some_value) is not valid.
> 
> ```
>     /**
>      * Get the fillable attributes of a given array.
>      *
>      * @param  array  $attributes
>      * @return array
>      */
>     protected function fillableFromArray(array $attributes)
>     {
>         if (count($this->getFillable()) > 0 && ! static::$unguarded) {
>             return array_intersect_key($attributes, array_flip($this->getFillable()));
>         }
> 
>         return $attributes;
>     }
> ```

Then how to understand the [documentation](https://laravel.com/docs/11.x/eloquent#mass-assignment-json-columns)?
Here is a clear example of how to specify:
```php
protected $fillable = [
    'options->enabled',
];
```

**Comment by projct1** [comment]
> @crynobone is that a documentation bug or?

He's unlikely to answer, unfortunately. Everything works as it should for him, as far as I understand :D

**Comment by crynobone** [comment]
@macropay-solutions Nope, tests verify the documentation is correct. 

https://github.com/laravel/framework/blob/cf7886bdee7017081263b14510c8d4753aa17a52/tests/Database/DatabaseEloquentModelTest.php#L1546-L1563

@projct1 I don't need to answer support, I need to verify and triage bugs.

**Comment by marius-mcp** [comment]
@crynobone This is mind blowing also for me. This means that the json can be mass assignable if it's column is in fillable also, resulting in full json replacement or only the keys from fillable. This should be stated clearly in the documentation with examples.

**Comment by projct1** [comment]
> @crynobone the documentation is lacking description then.
> 
> @projct1 you must use the key exactly the same in the fill array with "->"... totally not intuitive..
> 
> UPDATE
> 
> @projct1 Can the keys that contain arrow be used for creation? It would be strange to create a json by assigning only a key from it's json structure...

I didn't understand anything at all. I just want to allow certain json fields to be saved, so that garbage is filtered out and only those keys that correspond to the structure of my project are saved. How can I do this? Logically, everything is clear that you need to list the keys through the arrow ->. This is a standard way to access json fields in Laravel. That's what the documentation says. But it doesn't work.
