### ISSUE TITLE
Nested validation doesn't accept ClosureValidation

### ISSUE THREAD

**Issue by samuelhgf** [laravel/framework#53892]
### Laravel Version

10.48.25

### PHP Version

8.2

### Description

I have a request rules as this:

```php
public function rules(): array
    {
        return [
            'users.*.email' => ['nullable', 'email', Rule::forEach(fn ($value, $attribute) => [
                    new ClosureValidationRule(fn($att, $value, $fail) => $fail('test'))
                ])
            ],
        ];
    }
```

And i'm getting this error:

```
"message": "trim(): Argument #1 ($string) must be of type string, Illuminate\\Validation\\ClosureValidationRule given",
    "exception": "TypeError",
```

### Steps To Reproduce

Create a nested validation as in the description and try to validate as the rule key requests

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
