### ISSUE TITLE
HasManyThrough returns object with wrong primary key

### ISSUE THREAD

**Issue by Duffleman** [laravel/framework#5389]
In the case of 3 models:
Users, Keys, Characters: a User has many Keys, and a Key has many Characters.

You declare the relationship in the User Model, 

    function characters() {
        return $this->hasManyThrough('Character', 'Key');
    }

Later using $user->characters(); works as intended with correct fields. However, the Character object returned when using $user->characters()->first() is a working Character object, but the primary key, 'id', is not the id of the character, but rather, the primary key id of the Key object.

**Comment by Grimthorr** [comment]
This bug affects both Laravel 4 and 5.

To reiterate @jchamberlain - the best workaround is narrow down the columns in the select query (using `["grandchild.*"]` on the `find()` or `first()` methods for example). Although, a slight correction to the test examples is needed (missing parentheses):

```php
echo $parent->grandchildren()->get()->first()->id; // Correct: echoes id of the grandchild
echo $parent->grandchildren()->first()->id; // Wrong: echoes id of the child!!
echo $parent->grandchildren()->first(["grandchild.*"])->id; // Correct: echoes id of the grandchild
echo $parent->grandchildren()->find(15)->id; // Wrong: echoes id of the child, e.g., 4 instead of 15!!
echo $parent->grandchildren()->find(15, ["grandchild.*"])->id; // Correct: echoes id of the grandchild, 15
```

For this example, our parent model would need this relationship:
```php
public function grandchildren() {
    return $this->hasManyThrough('grandchild', 'child');
}
```

And the child model would need:
```php
public function fuels() {
    return $this->hasMany('child');
}

**Comment by drecken** [comment]
Just ran into this. Really annoying and hard to track. dd'ed both the returned model and the id I was looking for to finally realize its a bug.

**Comment by vinicarlos56** [comment]
I took a look and found a solution for this issue, I tested on @jchamberlain 's repository (Laravel 4.2), seems that it is still a problem on version 5, but I haven't tested it yet. I'll write some unit tests and submit a PR soon, should I work on version 4.2 or 5?

**Comment by GrahamCampbell** [comment]
Work on 5.0 please.

**Comment by vinicarlos56** [comment]
So, I tested on 5.0 and looks like everything is working fine. The solution for the 4.2 version was already provided on 5.0 (see [HasManyThrough] (https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L266)). I saw no test handling this issue specifically but [this one] (https://github.com/laravel/framework/blob/5.0/tests/Database/DatabaseEloquentHasManyThroughTest.php#L70) apparently cover the problem.

If someone that faced this on 4.2 confirm that 5.0 works well I believe that it is closed.
