### ISSUE TITLE
Cache does not flush by tag! Redis

### ISSUE THREAD

**Issue by AmirKhalifehSoltani** [laravel/framework#53896]
### Laravel Version

11.35.1

### PHP Version

8.2

### Database Driver & Version

Redis

### Description

`Cache::tags('tag_name')->flush();`
returns true but the cache does not flush actually.
but `Cache::flush();` works correctly.

- php 8.2
- laravel 11.35.1
- phpredis library 

### Steps To Reproduce

1. `Cache::tags('mytag')->put('name', 'Amir', 120);`
2. `Cache::tags('mytag')->get('name');`
3. `Cache::tags('mytag')->flush();`
4. `Cache::tags('mytag')->get('name');`

And after flush you can still get the name!

**Comment by AmirKhalifehSoltani** [comment]
<img width="401" alt="Screenshot 2024-12-14 at 4 09 19 PM" src="https://github.com/user-attachments/assets/a44f02c5-667c-48a6-806a-917d8b468189" />

**Comment by crynobone** [comment]
https://github.com/laravel/framework/pull/48078#issuecomment-1716332925

At the current state, we don't support or recommend using tagged cache other than `memcached`.
