### ISSUE TITLE
Broken relation hasOneThrough (using Many-to-Many Pivot) after update

### ISSUE THREAD

**Issue by MarekGogol** [laravel/framework#53915]
### Laravel Version

v11.31.0

### PHP Version

8.3.x

### Database Driver & Version

Mysql 8.0

### Description

Hello, just reopening #53557 with further info + repo + sql dump. It's not fixed yet in new releases.

Relation returns collection instead of eloquent after minor laravel update. 

This applies only when using methods `->through(xxx)->has(yyy)`, but not when using `->hasOneThrough`

<img width="488" alt="image" src="https://github.com/user-attachments/assets/6ead02bb-4759-407a-a133-54a819059f2a">

Correct response (v11.30.0):
<img width="1818" alt="image" src="https://github.com/user-attachments/assets/ede4c6c5-3762-4dcf-8fc7-69039c475b96">

Wrong response (v11.31.0):
<img width="1798" alt="image" src="https://github.com/user-attachments/assets/4b8be5d0-6ac7-4102-8a59-303b0b1dc4bd">

## My code

Student.php

``` php
class Student extends Model
{
    public function termine()
    {
        return $this->through('terminesPivot')
                    ->has('termine');
    }

    public function terminesPivot()
    {
        return $this->hasMany(StudentsTerminesPivot::class);
    }
```

StudentsTerminesPivot.php
``` php
class StudentsTerminesPivot extends Pivot
{
    public $table = 'termine_student_termines';

    public function termine()
    {
        return $this->hasOne(Termine::class, 'id', 'termine_id');
    }
}
```

Termine.php
``` php
class Termine extends Model
{

}
```

Route
``` php
Route::get('/test', function () {
    $student = Student::find(1);

    dd($student->termine);
});
```

### Steps To Reproduce

1. import
git clone https://github.com/MarekGogol/bug-report-001 bug-report
cd bug-report
cp .env.example .env
composer install

2. set mysql:
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=

SQL DUMP
[test.sql.zip](https://github.com/user-attachments/files/18149367/test.sql.zip)

3. Run
php artisan key:generate
php artisan serve
http://localhost:8000/test

5. Downgrade laravel to v11.30.0 from v11.31.0
run again http://localhost:8000/test and you will see different output.

**Comment by crynobone** [comment]
The bug that https://github.com/laravel/framework/issues/53557 solves unfortunately causes your code to fail. 

### Before 11.31

1. `HasOne` followed by `HasOne` => `HasOneThrough`
2. `HasOne` followed by `HasMany` => `HasManyThrough`
3. `HasMany` followed by `HasMany` => `HasManyThrough`
4. `HasMany` followed by `HasOne` => `HasOneThrough`

### After 11.31

1. `HasOne` followed by `HasOne` => `HasOneThrough`
2. `HasOne` followed by `HasMany` => `HasManyThrough`
3. `HasMany` followed by `HasMany` => `HasManyThrough`
4. `HasMany` followed by `HasOne` => `HasManyThrough`

------

However, after inspecting the logic of those changes. It seems wrong to expect `HasMany` followed by `HasOne` to resolve `HasOneThrough` as you would have expected. At the moment, we not going to revert this change and you should use the old syntax to handle this scenario.
