### ISSUE TITLE
[11.x] Handle SQLSTATE[HY000] [2002] Operation in progress in DetectsLostConnection trait 

### ISSUE THREAD

**Issue by holgerk** [laravel/framework#53965]
### Laravel Version

11.33.2

### PHP Version

8.3

### Database Driver & Version

'driver' => 'mysql', MariaDB 10.1.40

### Description

We see a the pdo exception: `PDOException: SQLSTATE[HY000] [2002] Operation in progress` sometimes.
Patching the `DetectsLostConnection` trait fixed the Problem for us.

### Steps To Reproduce

This is not easy to reproduce, happens randomly

**Comment by holgerk** [comment]
https://github.com/laravel/framework/pull/53966

**Comment by jeffdafoe** [comment]
The issue that causes this message is most likely fixed in the version of PHP that was released today. There was a bug in the core network connection establishment code where the EINPROGRESS return could "leak" out of the connect function as an error, in a very uncommon scenario.
