### ISSUE TITLE
Weird behavior of `->value()` on Eloquent Model

### ISSUE THREAD

**Issue by ISNewton** [laravel/framework#54030]
### Laravel Version

11.9

### PHP Version

8.3

### Database Driver & Version

MySQL 8.0

### Description

Calling `value()` on Eloquent Model causes a DB query . For example:
```
        $user = User::find(250);
        $b = $user->value('id');
        dd($b);
```
The `$b` value unexpectedly will be `1` instead of `250` as a result of the following query:
`select `id` from `users` limit 1`

### Steps To Reproduce

Run the below example code:
```
$user = User::find(250);
        $b = $user->value('id');
        dd($b);
```

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
