### ISSUE TITLE
Array validation does not work

### ISSUE THREAD

**Issue by Sanhiscio** [laravel/framework#54043]
### Laravel Version

11

### PHP Version

8.2.4

### Database Driver & Version

MySql

### Description

Good afternoon, I have PHP 8.2.4 and Laravel 10.
I want to perform validations on a form, specifically an input type text called numeros[] that can be repeated dynamically.
In my rules file I have the following:
```
public function rules(){
return [
"nombre" => ['required', 'min:3', 'max:100'],
"email" => ['required', 'string', 'lowercase', 'email', 'max:255'],
"numeros" => ['required', 'array', 'min:1', 'max:3'],
"numeros.*" => ['required', 'numeric', 'min:5']
];
}
```
But when sending the form with the empty field, it does not show the error of Required Field, it does not validate this field, the rest of the fields do it correctly.
Thanks.

### Steps To Reproduce

Request: ValidarRegistro
<?php
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ValidarRegistro extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool{
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(){
        return [
            'nombre' => ['required', 'min:3', 'max:100'],
            'email' => ['required', 'string', 'lowercase', 'email', 'max:255'],
            "numeros" => ['required', 'array', 'min:1', 'max:3'],
            "numeros.*" => ['required', 'numeric', 'min:5'],
        ];
    }

In my controller:
public function store(ValidarRegistro $request){
...
}

**Comment by bulletproof-coding** [comment]
Try with [size:value](https://laravel.com/docs/11.x/validation#rule-size) instead of min:1

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
