### ISSUE TITLE
BelongsToMany::attach() method does not refresh collection

### ISSUE THREAD

**Issue by moleculezz** [laravel/framework#5414]
Hi,

I've noticed that the `BelongsToMany::attach()` method does not update the collection.
I came across this issue when I introduced a new method on my Model that did an `attach()` and then fired a model event. The referenced model in the event handler of course did not represent the data correctly from the DB.

My solution was to force the collection to do a new query, I `unset` the property which seems to do a new query.

Is there a better way of doing this?

````php
class Foo extends Eloquent
{

  public function bars()
  {
    return $this->belongsToMany('Bar');
  }

  public functiion updateBar($bar)
  {
    $this->bars()->attach($bar);
    unset($this->bars);
    $this->fireModelEvent('bar_updated');
  }
}
````

**Comment by GrahamCampbell** [comment]
This is actually the indented behaviour, sorry.

**Comment by moleculezz** [comment]
@GrahamCampbell if this is intended behaviour. You mean that the odd solution I provided is how you solve the issue?

**Comment by GrahamCampbell** [comment]
No, you not meant to access things like that. You're meant to sync again.

**Comment by moleculezz** [comment]
Are you referring to the `sync` method?
I don't understand what you mean with:
>No, you not meant to access things like that

**Comment by GrahamCampbell** [comment]
Please could you ask on the forums.

**Comment by moleculezz** [comment]
http://laravel.io/forum/07-17-2015-belongstomanyattach-method-does-not-refresh-collection

**Comment by moleculezz** [comment]
@GrahamCampbell Would you be so kind as to take a look at the forum thread? No one seems to have an answer. You suggested a solution. I would love to understand this solution.

**Comment by vieirafagner** [comment]
@moleculezz  Did you solve the update?

**Comment by wmcmurray** [comment]
This worked for me :
https://stackoverflow.com/questions/23364276/how-do-i-reload-a-relation-collection-in-laravel

Instead of : 

```php
unset($this->bars);
```

Just do : 

```php
$this->load('bars');
```
