### ISSUE TITLE
Add and() and or() methods to Relations

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/framework#5466]
To generate joins like

```
inner join A on
B.id = A.column1
or
B.id = A.column2
```

and

```
inner join A on
B.id = A.column1
and
B.id != A.column2
```

or a `join()` method, so users can override Laravel's one.

**Comment by GrahamCampbell** [comment]
Has anyone got any interest in this? If not, it will eventually get closed. This has been open for about 8 months now.
