### ISSUE TITLE
Compound SQL using closure in FROM

### ISSUE THREAD

**Issue by loganfre** [laravel/framework#5545]
I created some code to allow from to accept a closure. This allows compound SQL to be created. An example of what currently can not be done:

SELECT * FROM (SELECT * FROM table1 where id = 1 UNION SELECT * FROM table2 where id = 1) as foo ORDER BY id LIMIT 15

This is necessary for using the built in paginate function. The closure allows paginate to work with any SQL. It currently chokes on unions and some joins.

I have example code to achieve this:

Illuminate\Database\Eloquent\Builder
```
	public function from($table, $name = 'foo')
	{
		if ($table instanceof Closure)
		{
			$query = $this->newQuery();
			$query = call_user_func($table, $query);
			$this->mergeBindings($query);
			$table = '( '.$query->toSql().' ) as '.$this->grammar->wrapTable($name);
		}
		else
		{
			$table = $this->grammar->wrapTable($table);
		}
		$this->from = $table;
		return $this;
	}
```
Illuminate\Database\Query\Grammars\Grammar
```
	protected function compileFrom(Builder $query, $table)
	{
		return 'from '.$table;
	}
```

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by ifeltsweet** [comment]
We need this, otherwise pagination doesn't work with unions.

**Comment by ifeltsweet** [comment]
I've modified original proposal to the following in order not to change `Grammar`.

```php
public function from($table, $name = '')
{
	if ($table instanceof Closure) {
		$query = $this->newQuery();
		call_user_func($table, $query);
		$this->mergeBindings($query);
		$table = $this->raw('( '.$query->toSql().' ) as' .  $this->grammar->wrapTable($name));
	}
	
	$this->from = $table;
	return $this;
}
```

I use a custom extended `Builder` in my projects, so this is not a problem for me, but for people who can't do that they may want to create a helper that can do the same. Something like:

```php
$query->from(QueryHelper::from($query, $name, function($q) { ... })->paginate();
```

But really, this should be implemented.
