### ISSUE TITLE
Fire events for artisan commands

### ISSUE THREAD

**Issue by freezy-sk** [laravel/framework#5621]
It would be fine when we can hook on some Artisan events when they are fired with corresponding command name. For example `call`, `execute`, `run` for `db:seed` should be `artisan.call.db.seed`, `artisan.execute.db.seed` etc.
It's all about adding few lines into `Illuminate\Console\Application` and `Illuminate\Console\Command`.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.
