### ISSUE TITLE
URL::route() producing inconsistant routes.

### ISSUE THREAD

**Issue by xylesoft** [laravel/framework#5630]
It appears that if you provide a route parameter which has a value of NULL (['sort'=>null]) or do not added the parameter key=>value at all, route generation will take the next available route parameter and use it's value as the {sort?} interpolation.

For example **['sort'=>null, 'url'=>'cat', 'page'=>2]** or **['url'=>'cat', 'page'=>2]** against route syntax **'/animals/{url}/{sort?}'** will become **'/animals/cat/2'** instead of **'/animals/cat/?page=2'**.

The following code snippet shows the weirdness of this behaviour:
http://laravel.io/bin/O9zaW

This appears to effect 4.1 and 4.2 that I know of.

**Comment by GrahamCampbell** [comment]
Is this still an issue? Can anyone send a pull request please.

**Comment by xylesoft** [comment]
@GrahamCampbell 

It's an issue based upon design of the routing system, allowing associative key and non-associative key arrays for route parameter matching is the real issue. I think the only reliably fix I can think of initially is to force associative arrays to match the key to token and value to parameter, any which are unmatched then apply the ?key=value parameter mechanism.

**Comment by GrahamCampbell** [comment]
Maybe a no-fix then. If you have a clean fix, please send a pull for Taylor to look at.
