### ISSUE TITLE
[FR] Allow query builder to build without a table

### ISSUE THREAD

**Issue by judgej** [laravel/framework#5843]
The query builder in 4.2.x has to start by specifying a table. However, queries (MySQL at least) do not need to select from a table.

For example, during a sync process, I needed to know the current clock time of a remote database by selecting NOW(). The following solved that specific case:

    $db_time = DB::connection('my_db')->selectOne('SELECT NOW() AS now')->now;

However, as a generic case, that does not allow me to build the query any further, since selectOne returns the results and not a query builder object to extend. Only `DB::table('name')` or `DB::connection('whatever')->table('name')` return a query builder object ready to go, and the name is mandatory.

So how about allowing the table name to be left empty/blank/null? Or maybe skip the table method and provide something like `DB::builder()` to return the builder without a table.

I suspect the SQL builder or grammar processor will need to be changed to account for there not necessarily being a table to select from.

From what I remember, Oracle got around this problem by providing a single-row table called DUAL, and that helped ensure there was always a table available, even when you were not selecting data from a table.

**Comment by GrahamCampbell** [comment]
Closing due to no interest.

**Comment by andonovn** [comment]
Now you can actually use `DB::query()` which will return you an instance of the builder. Just wanted to say that for anyone else that may come here in the future after googling (like me).

Not sure if that was possible back in 2014 where this issue was opened. And yeah, sorry for posting in outdated issue, just thought I may safe someone else's time

**Comment by judgej** [comment]
Awesome point @andonovn 

Whether this was possible or not in 2014, it was certainly never offered as a solution.

**Comment by binarweb** [comment]
In Laravel 8, you can do:

```php
$dbNow = collect(
    DB::select('SELECT NOW() AS _now')
)->first()->_now;

echo $dbNow;
```

**Comment by iamprageeth** [comment]
@andonovn , Thanks You saved my time ! We can create our advanced raw sql query and and convert it to a query builder object like this.

$query_advanced_join = ("a.column FROM  ({$this->getSql($query1)}) a JOIN ({$this->getSql($query2)}) b ON a.column = b.column");

//convert my raw query to query builder instance

            $my_builder = DB::query();
            $my_builder->select(DB::raw($query_advanced_join)); 

Then we can pass this query builder object to any DataTable Library to set pagination ,sorting etc.

////////////////////////////////////////////////////////////////////////////////////
    private  function getSql($builder)
    {
        $sql = $builder->toSql();

        foreach($builder->getBindings() as $binding)
        {
            $value = is_numeric($binding) ? $binding : "'".$binding."'";
            $sql = preg_replace('/\?/', $value, $sql, 1);
        }
        return $sql;
    }
