### ISSUE TITLE
[MySqlGrammar] - Invalid default value for timestamp if mysql server run in "strict mode"

### ISSUE THREAD

**Issue by villico85** [laravel/framework#5903]
Strict sql mode (default mode in mysql 5.6), don't allows to use 0 as timestamp value.
Step to reproduce:
1) On Mysql server run the following command to change the sql mode:
SET GLOBAL sql_mode = 'STRICT_ALL_TABLES';
2) Run a create table migration with a timestamp field.

**Comment by snipe** [comment]
Did this issue get resolved? I don't see a PR attached.

**Comment by zupolgec** [comment]
NO_ZERO_DATE is now enabled by default in Mysql 5.7.8
I'm having issues with `timestamps()` using homestead
