### ISSUE TITLE
[Request] Set relations on model property

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#5924]
You are able to request model relations off it's properties. For example, if a `Post` belongs to a `User` you can do the following:

    $user = $post->user;

I'd like to see the reverse made possible - setting relations on a model property. This would make it easier to set relations rather than using something like `$post->user()->associate(User::first())` or `$user()->posts()->attach(Post::first())` - where the API is different depending on the relationship type.

    // Single relations
    $post->user = User::first();

    // Plural relations
    $user->posts = [Post::find(1), Post::find(2)];

This would provide a more consistent (and more readable) way to set the relations of a model.

**Comment by GrahamCampbell** [comment]
Pull request please?
