### ISSUE TITLE
Route filter security issue or feature?

### ISSUE THREAD

**Issue by divdax** [laravel/framework#5967]
Hi,

IMHO laravels route filters has a security issue. This can be feature but should be documented.

Basic Example:
```
Route::group(['before'=>'auth'], function()
{
 Route::get('protect', function() {});
});
```
if i'm not logged in and hit ```/protect``` in the browser i should get redirected to ```/login``` because i've defined a before filter, right?
Now the Security Issue. If you use ```Route::when()``` like this: (in filters.php)
```
Route::when('protect*', 'check');
```
the before filter on the Route::group() is completely ignored.
But ```php artisan routes``` list my route with the Before Filters ```auth, check```.

Instead you have to put a "/" at the beginning so the auth filter is executed:
```
Route::when('/protect*', 'check');
```

What do you think? Feature or Security Issue? :)

**Comment by GrahamCampbell** [comment]
Can you send a pull request please.
