### ISSUE TITLE
Service providers providing deferred service providers

### ISSUE THREAD

**Issue by kirkbushell** [laravel/framework#6029]
Hit a little bit of a hiccup today whilst having a package service provider, wanting to provide another service provider that was meant to be deferred (whilst the parent package service provider was not).

No matter what I did, it was impossible to register a deferred service provider from within another service provider that is not deferred. To get around this, I had to do the following:

```php
class ValidationServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = true;

    public function register()
    {
        $closure = function() {
            $this->app['validator']->setPresenceVerifier(new DoctrinePresenceVerifier);
        };

        $closure->bindTo($this);

        $this->app['events']->listen('Illuminate\Validation\ValidationServiceProvider', $closure);
    }
}
```

Then in the parent:

```php
$this->app->register(ValidationServiceProvider::class);
```

Obviously register() is the wrong method to use, but I couldn't work out another method to use. registerDeferredProvider registers a provider that is already set to be deferred, which I could probably do also, but that seemed unnecessary (aka, forcing another deferred provider to be registered).

It works, but it's not particularly clean or nice. It would be great to be able to register a service provider and ensure that it's deferred.

**Comment by GrahamCampbell** [comment]
This is probably a no-fix then. If you ever find a good way to do this, a pull requests would be much appreciated. :)

**Comment by kirkbushell** [comment]
It's been resolved in L5 anyways :)

**Comment by GrahamCampbell** [comment]
Oh right. :)

**Comment by tabennett** [comment]
So is there now a way to load a deferred provider from within another provider in L5?  I'm facing pretty much the exact situation as you were (needing to load a deferred provider without manually adding it to config/app.php).

**Comment by kirkbushell** [comment]
@tabennett yup, just have your service provider work with the AggregateServiceProvider class.
