### ISSUE TITLE
[5.0] Blade relative paths

### ISSUE THREAD

**Issue by EloProf** [laravel/framework#6081]
I have searched for this quite a lot but either I am blind or nobody else proposed this before:

I would like to see blade support relative paths. For example i have the following folder structure in my views:
```
views
└── pages
        └── sub1
                 └── sub2
                          ├── _partial.blade.php
                          └── view.blade.php
```
If i want to use the `_partial` now in `view` i have to write a quite extensive statement:
```
@include('pages.sub1.sub2._partial')
```
And what if I later refactor and for example want to change the name of `sub2`? then i will have to scan every file in the subfolder(s) for usages of the name and change them.

There is a reason why the concept of relative paths was implemented in filesystems years ago =)
How about giving this flexibility to our template engine as well?

**Comment by GrahamCampbell** [comment]
Pull request please?

**Comment by EloProf** [comment]
Pull request for what? A new tag like `@includeUnix('/path/to')`? An optional parameter for `@include`? I could probably write something like that, but I mainly opened this issue to come to a conclusion what the best way to approach this would be. In regards to adding it to laravel 5.0 and perhabs a non bc breaking solution for laravel 4.2.

**Comment by GrahamCampbell** [comment]
5.0 or 5.1 please, not 4.2.

**Comment by judgej** [comment]
So did this make it into a release? I can't quite make it out.

**Comment by vedmant** [comment]
+1 for @rinclude() or something like this

**Comment by srph** [comment]
Taylor closed https://github.com/laravel/framework/pull/7218 so it didn't, most probably. Any update?

**Comment by maxflex** [comment]
Still no updates on this one?

**Comment by srph** [comment]
It probably belongs to userland.

**Comment by andreneto** [comment]
+1

**Comment by brnmonteiro** [comment]
+1?

**Comment by judgej** [comment]
@srph also remember that issues raised may be "testing the water", and are often closed if they do not get any interest. Maybe a "thumbs up" on the top comment would keep the noise down while providing an informal vote?

**Comment by tthdvd** [comment]
It is a must-have feature. Think about it, when you generate a controller as a resource, you have the generated methods like index, edit etc. It could be so nice have the file structure (when you have two user type, like admin and basic user) like :
```
- /layouts
--- default.blade.php
--- admin.blade.php
- /admin
--- /news
------ index.blade.php
------ show.blade.php
------ edit.blade.php
- /user
--- /orders
------ index.blade.php
------ show.blade.php
------ edit.blade.php
```
And now I just can't user my layouts  from admin.news.index :/

**Comment by lfukumori** [comment]
I made a package for it:
```
lfukumori/laravel-blade-include-relative
```
