### ISSUE TITLE
New environment detection system is not mutable by default

### ISSUE THREAD

**Issue by jlem** [laravel/framework#6096]
The new environment detection system is nice, but there is a kind of bug out of the box. By default, the `Dotenv` class is set to immutability for existing ENV values. This means that if an ENV value is already set, you cannot simply change what's in your .env file to something else.

What you need to do is call `Dotenv::makeMutable()` before the `Dotenv::load()` call in order to ensure that you can mutate existing environment variables.

This is not a bug per-se, but it's an unexpected out of the box behavior that requires you to dive into the source code to figure out. Might be good to throw the `Dotenv::makeMutable()` call in there by default so that environment mutation is possible out of the box.

**Comment by GrahamCampbell** [comment]
It's very easy for people to change this default as @kelvinj said.

**Comment by oprudkyi** [comment]
for 5.2 next code seems to work (used in command)
```php
    /**
     * loads env file (.env.something) based on environment set via --env=something
     *
     * @return void
     */
	public function reloadEnvironment()
	{
        $this->info("Reload environment");
		putenv('APP_ENV=' . \App::environment());
		$this->laravel->make('Illuminate\Foundation\Bootstrap\DetectEnvironment')->bootstrap($this->laravel);
		(new \Dotenv\Dotenv(\App::environmentPath(), \App::environmentFile()))->overload();
		$this->laravel->make('Illuminate\Foundation\Bootstrap\LoadConfiguration')->bootstrap($this->laravel);
	}
```

**Comment by ryancwalsh** [comment]
@oprudkyi Does this work in Laravel 6.0 for Dusk to solve [this problem](https://stackoverflow.com/questions/54407784/laravel-dusk-how-to-change-config-values-before-each-test-for-the-browser#comment103224655_54407784)? (Where can I put this function, and where does `$this->laravel` come from?)

@kelvinj Related to [your comment](https://github.com/laravel/framework/issues/6096#issuecomment-60737666), I'm wondering if you have any suggestions about changing env values in a Dusk pre-test setup?

Thank you both!

**Comment by oprudkyi** [comment]
@ryancwalsh for Laravel 6.0 and Dusk it might be different calls/classes . ```$this->laravel``` is the same as app() if I remember correctly (used as variable because in commands it was available, at least in 5.2)

**Comment by ryancwalsh** [comment]
@oprudkyi Thanks. Unfortunately I've been stuck on this. I even had the idea of making my own library that extends the Dusk command and then use _that_ as a dev requirement in my project (instead of Dusk), and override the [refreshEnvironment](https://github.com/laravel/dusk/blob/5.0/src/Console/DuskCommand.php#L219) function to make DotEnv mutable. But unfortunately it always seems to get clobbered by something later on.

**Comment by ryancwalsh** [comment]
Here is the answer for overriding certain Laravel Dusk env variables per test after the DotEnv upgrade of Laravel 5.8+: https://stackoverflow.com/a/58473993/470749
