### ISSUE TITLE
Table alias doesn't work on DB queries

### ISSUE THREAD

**Issue by toorta** [laravel/framework#6173]
I am having a problem with left joining to the same table on the following function. I am using table alias to join to the same table but I get column not found error. I am sure all tables and colums exist. The code works without this join. I have already written on stackoverflow and laravel but I couldn't get any help. Here is my fonction and error message including "toorta" which is my table prefix: 

Function:

```
public static function getPhrases($vals = array(), $limit = 20, $sortby, $sorttype) {
        
        $phrases = Toorta_DB::table('language_phrase')
                ->select('language_phrase.*', 'language.name AS language', 'lpo.text AS original')
                ->join('language', 'language_phrase.language_code', '=', 'language.code')
                ->leftJoin('language_phrase AS lpo', function($join)
                {
                    $join->on('language_phrase.variable', '=', 'lpo.variable');
                    $join->on('language_phrase.module_folder', '=', 'lpo.module_folder')
                            ->where('lpo.language_code', '=', 'en');
                })
                ->where(function($query) use ($vals) {
                    if(isset($vals['language']))
                        $query->where('language_phrase.language_code', $vals['language']);

                    if(isset($vals['module']))
                        $query->where('language_phrase.module_folder', $vals['module']);

                    if(isset($vals['search']))
                        $query->where('language_phrase.text', 'LIKE', '%' .  $vals['search'] . '%');
                })
                ->orderBy($sortby, $sorttype)
                ->orderBy('language_phrase.variable', 'ASC')
                ->paginate($limit);
        
            return $phrases;
    }
```

Error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'toorta_lpo.variable' in 'on clause' (SQL: select count(*) as aggregate from `toorta_language_phrase` inner join `toorta_language` on `toorta_language_phrase`.`language_code` = `toorta_language`.`code` left join `toorta_language_phrase` as `lpo` on `toorta_language_phrase`.`variable` = `toorta_lpo`.`variable` and `toorta_language_phrase`.`module_folder` = `toorta_lpo`.`module_folder` and `toorta_lpo`.`language_code` = en)

**Comment by psbharathy** [comment]
joelLarson , how to  wrapp my aliases in "new Expression" ?
Could you give sample query with join alias
