### ISSUE TITLE
Templates Documentation broken on Laravel website

### ISSUE THREAD

**Issue by BogdanBartis** [laravel/framework#6257]
The template inheritance docs on [http://laravel.com/docs/4.2/templates](http://laravel.com/docs/4.2/templates) have the word `@parent` missing throughout the **Using A Blade Layout** section. However on the same docs page on github [https://github.com/laravel/docs/blob/4.2/templates.md#using-a-blade-layout](https://github.com/laravel/docs/blob/4.2/templates.md#using-a-blade-layout) they seem to show just fine.

Markdown parsing problem on the website maybe?

**Comment by taylorotwell** [comment]
Yeah Jeffrey mentioned this to me the other day, need to look into it.

**Comment by GrahamCampbell** [comment]
Fixed in https://github.com/laravel/framework/commit/dfaca7cfc50e5dbde99e072e94eff01e78449de7.
