### ISSUE TITLE
Queue Events (Push, Before, After)

### ISSUE THREAD

**Issue by djtarazona** [laravel/framework#6282]
I'd like some way of executing code right before a job is pushed on the queue, before a worker fires a job and after a worker fires a job.  This will allow one to modify a job before it is pushed on the queue and set up / tear down when a job is fired.

My use case is "persisting" authentication.  For example, my job may call methods that depend on the user being authenticated.  Perhaps the job is accessing some data from the database and our method checks to see if the user is authenticated first.  Because queues are asynchronous, the job is executed later by the worker with a fresh boot of the framework — no user is authenticated.

Right now, I am passing the currently authenticated user ID in the job data on every `Queue::push`:
```php
Queue::push('SampleJob', ['authUserId' => $this->auth->user()->id])
```

Then logging the user in from the job's fire method:
```php
public function fire($job, $data)
{
	if (isset($data['authUserId']))
	{
		$userId = $data['authUserId'];

		if ($userId)
		{
			$this->auth->onceUsingId($userId);
		}
	}
```

It would be really nice to use events to handle this as I want it applied to every queued job.

```php
Event::listen('queue.push', function(&$job, &$data, &$queue)
{
	$data['authUserId'] = $this->auth->user()->id;
});

Event::listen('queue.job.before', function($job, &$data)
{
	if (isset($data['authUserId']))
	{
		$userId = $data['authUserId'];

		if ($userId)
		{
			$this->auth->onceUsingId($userId);
		}
		else
		{
			$this->auth->logout();
		}
	}
});

Event::listen('queue.job.after', function($job, $data)
{
	$this->auth->logout();
});
```

What do you guys think?  Is there a better way to handle this?

**Comment by GrahamCampbell** [comment]
We've got a whole new queue system in L5.
