### ISSUE TITLE
[5.0] [Bug?] Tests no longer use $client - but AssertionsTrait still require it

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#6373]
Not sure if this is a bug, or just still mid-implementation.

All the testing assertion traits no longer work. i.e.

`$this->assertRedirectedToRoute('admin.login')`

will fail - because the assertion looks for `$this->client` which is no longer defined in the tests.

Or this also fails (example straight from the 5.0 Dev Docs):

```
public function testMethod()
{
    $this->call('GET', '/');

    $this->assertResponseOk();
}
```

**Comment by TheShiftExchange** [comment]
@GrahamCampbell - FYI - its still broken.

```
$this->assertRedirectedToRoute('admin.login')
```

gives this error:

```
Failed asserting that Symfony\Component\HttpFoundation\Response Object (...) is an instance of class "Illuminate\Http\RedirectResponse".
```

I know L5 not finished etc - so its up to you if you reopen this so it doesnt get missed - or leave it closed.

**Comment by GrahamCampbell** [comment]
We want to do a beta release this week, so the the sting stuff will probably get looked at soon.

**Comment by dmi3000** [comment]
Any updates on this issue?

**Comment by mikefrancis** [comment]
Would love an update on this too.

**Comment by crynobone** [comment]
Is `$this->response` not working? <https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L21>

> L5 is live but this doesn't seem like it was addressed.

What's broken? A sample code could be useful.

**Comment by TheShiftExchange** [comment]
@crynobone Here is some broken code:

Straight from the L5 docs:

```
$this->assertRedirectedToRoute('route.name');
```

Gives error 

```
Failed asserting that Illuminate\Http\Response Object (...) is an instance of class "Illuminate\Http\RedirectResponse".
```

**Comment by TheShiftExchange** [comment]
I've done some testing - and this seems to be fixed now.

**Comment by shutchinson** [comment]
Are assertion traits, such as `assertRedirectedToRoute()` not intended to work in Laravel 5.6?

If so, should the [documentation](https://laravel.com/api/5.6/Illuminate/Foundation/Testing/AssertionsTrait.html#method_assertRedirectedToRoute) be updated?
