### ISSUE TITLE
$touches causes fatal error if no ManyToMany relations exist

### ISSUE THREAD

**Issue by joechilds** [laravel/framework#6386]
You can set up a pair of Eloquent models like this:

    class Product extends \Eloquent {
        public function assets() {
            return $this->belongsToMany('Asset');
        }
    }

    class Asset extends \Eloquent {
        protected $touches = [ 'products' ];

        public function products() {
            return $this->belongsToMany('Product');
        }
    }

By doing this, you can call

    Product::find( $validProductId )->assets()->attach( $validAssetId );

the `Asset` will go and update the `updated_at` field on every related `Product` to indicate that its relations have changed.

However, if you make a new `Asset`, or take an `Asset` which has no related `Product`s yet, you'll get a fatal error as the `Model::touchOwners` method only checks if `$this->relation` isn't null:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation)) // this is the problem
			{
				$this->$relation->touchOwners();
			}
		}
	}

I have a tentative fix in place locally (for now) by just adding in a check for `&& ! $this->$relation->isEmpty()`, but that may affect other relations, I'm not sure:

	public function touchOwners()
	{
		foreach ($this->touches as $relation)
		{
			$this->$relation()->touch();

			if ( ! is_null($this->$relation) && ! $this->$relation->isEmpty())
			{
				$this->$relation->touchOwners();
			}
		}
	}

**Comment by impleri** [comment]
Another example (from #6932):

```php
class Address extends Eloquent
{
    public $touches = ['people'];

    public function people()
    {
        return $this->morphedByMany('Person', 'addressable');
    }
}
```
```php
class Person extends Eloquent
{
    public function addresses()
    {
        return $this->morphToMany('Address', 'addressable');
    }
}
```
Saving an Address throws `'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::touchOwners()`. I'm guessing the model's touchOwners should be looping through the collection since I cannot seem to find a touchOwners() method anywhere but on the Model.

**Comment by GrahamCampbell** [comment]
Can someone please send a pull to fix this?

**Comment by commandantp** [comment]
Still an issue... isn't it? Have to stay at 4.2.6 to avoid that

**Comment by impleri** [comment]
Added PR for 4.2. Looks like it can apply to 5.0 pretty easily.

**Comment by GrahamCampbell** [comment]
@impleri Could you send a pull to 5.0 please?

**Comment by impleri** [comment]
Sure can. Patch applied cleanly from original PR and local testing still passes.

**Comment by GrahamCampbell** [comment]
Thanks guys. Further discussion can take place on the pull. :)
