### ISSUE TITLE
Throw error for nonexistent validation rules

### ISSUE THREAD

**Issue by BlueHayes** [laravel/framework#6430]
I have never understood why Laravel will ignore invalid validation rules. IMO it's very important that if a validation rule does not exist, an Exception is thrown. A small typo in a rule name can mean that a rule is not applied as expected. Likewise a rule which no longer exists may be expected, etc.

Of course testing should pick this up but I definitely think an error should be thrown still.

**Comment by GrahamCampbell** [comment]
We're open to pull requests. That might better display what you want.
