### ISSUE TITLE
[5.0] Add parameters back into middleware

### ISSUE THREAD

**Issue by GRAgmLauncher** [laravel/framework#6470]
EDIT: [See my comment for the resolution:](https://github.com/laravel/framework/issues/6470#issuecomment-75354611)

In 4.2, you could create a really elegant permission system by attaching filters to routes, without having to include anything in controllers:

    Route::post('/admin/users/{id}/ban', [
                'before' => 'can:ban.users', 
                'uses' => 'AdminUserController@ban' ]);

But the above is not possible using middleware - it is effectively impossible to use a permission class via  middleware because of it, unless you want to couple your permission key to a route name, which is not desirable (and not as flexible).

It would be enormously beneficial if middleware could accept parameters.

And if the answer is to continue using filters, then the filter service provider and folder for filters should be re-included by default, along with documentation for it. As of now, legacy filter support is a hidden feature which is also undesirable.

**Comment by GrahamCampbell** [comment]
We're open to pull requests. :)

**Comment by jmas** [comment]
What status of this task?

**Comment by GrahamCampbell** [comment]
Unsolved. Closed because nobody was interested in writing a solution.

**Comment by jmas** [comment]
I'm interested, but I have't match experience with Laravel for solving this task.
I think if filters is deprecated we should able to have same functionality. Now middleware is filters except passing parameters.

**Comment by nesl247** [comment]
So because no one has written a solution yet, you close the ticket out? Seems like an odd way to manage feature requests. Usually feature requests remain open until solved or decided it will never be added.

This is still a feature that has been asked for numerous times on IRC.

**Comment by GRAgmLauncher** [comment]
So apparently there is a solution to this that works perfectly fine. You can define any arbitrary array key => value in your route

```php
Route::get('/foo/bar', [
	'as'   => 'foo',
	'uses' => 'FooController@bar',
	'middleware' => 'authorize',
	'permission' => 'foo.bar'
]);
```

Then in the middleware's `handle()` method you can do:

```php
$request->route()->getAction()['permission']; //foo.bar
```

Or you can even pass in an array:

```php
Route::get('/foo/bar', [
	'as'   => 'foo',
	'uses' => 'FooController@bar',
	'middleware' => 'authorize',
	'permission' => ['array', 'of', 'many', 'permissions']
]);
```

Or a full object if you want:

```php
Route::get('/foo/bar', [
	'as'   => 'foo',
	'uses' => 'FooController@bar',
	'middleware' => 'authorize',
	'permission' => new Permission('foo.bar')
]);
```

So this behavior of route actions is actually BETTER than the old filter parameters by miles. Not sure why Taylor never really mentioned this when it's a fantastic solution.

**Comment by jmas** [comment]
@GRAgmLauncher Yep, but when I use middleware in Controller I do not able to set parameters.
```php
...
public function __construct() {
  $this->middleware('rolechecker', ['only'=>['index']]);
}
...
```
I can only set scope of actions where I can use this middleware, but can't set: what roles have access to this actions.

How I can pass parameters to middleware from controller?

**Comment by JosephSilber** [comment]
@GRAgmLauncher this might be OK for your own middleware. But if you develop middleware as part of a package, you can't just dictate to your users to use some random key in their route action - eventually it's bound to clash with someone else's middleware.

Unless you would advise them to use a package-specific naming convention, which is pretty ugly if you ask me - and there's nothing visually tying the two together.

It's a nice temporary workaround, but it's not a solution. At all.

**Comment by jmas** [comment]
I think we need same way to pass params as params in filters.
```php
class BirthdayFilter
{
    public function filter($route, $request, $first, $second, $third)
    {
        echo "{$first} - {$second} - {$third}";
    }
}
```

Filter called from Route:
```php
Route::get('/', array(
    'before'    => 'birthday:foo,bar,baz',
    function()
    {
       return View::make('hello');
    }
));
```
Filter called Controller:
```php
public function __construct() {
  $this->beforeFilter( 'birthday:foo,bar,baz');
}
```

How it maybe can look for Middleware.
```php
class Birthday {
	public function handle($request, Closure $next, $first, $second, $third)
	{
		echo "{$first} - {$second} - {$third}";
		return $next($request);
	}
}
```
Middleware called from Route:
```php
Route::get('/', array(
    'middleware' => ['birthday:foo,bar,baz'],
    function()
    {
       return View::make('hello');
    }
));
```
Middleware called Controller:
```php
public function __construct() {
  $this->middleware( 'birthday:foo,bar,baz');
}
```

**Comment by dominikveils** [comment]
Agree, it's a common feature that must be implemented. I'm really dont understand why Taylor need to remove awesome filters, and REPLACE it with Middleware. We NEED filters back, but not instead of middleware, but both.

**Comment by jmas** [comment]
I tried to implement middleware parameters like in filters, but common problem in algorithm that call middleware - Pipeline. I can't pass parameters to each middleware separately. Only can pass one params to all call's. Maybe someone can advice how to pass parameters through Pipeline for each middleware separately?

**Comment by bastiaan89** [comment]
@dominikveils Filters are still there actually, the documentation just doesn't really mention them.

**Comment by dominikveils** [comment]
@bastiaan89 filters are deprecated, so I can't rely on them for a long term. Next commit @taylorotwell will remove them, and what will I do?

**Comment by bastiaan89** [comment]
@dominikveils Oh right sorry, I didn't know about that. Actually I'm in the same boat then, I have converted a project to L5 but it relied on filters with parameters. To be honest I don't really get the point of middleware over filters anyway. The global middleware is fine, but the route ones don't make much sense to me.

**Comment by dominikveils** [comment]
@bastiaan89 yes, global middleware are perfect, but an idea to make route-middleware instead of - is crappy. Taylor need to return filters back... it's useless to use middleware for filters.

**Comment by jmas** [comment]
@dominikveils I only need parameters for middleware (for mw called from controllers and routers). I think filters and middleware is competing approaches. If filters are deprecated I do not think that it will be roll back in future.

**Comment by steve3d** [comment]
Well, I think the most guys want this because they just need a simple permission check. and put all permissions to a middleware is not so accurate. So I bring you this solution:

in every middleware, we can get a route's action name it's Controller@method kind of string. So we created a facade do this:
```
class RoutePermissions {

    /**
     * @var array of controller => [action => permission]
     */
    protected $actions = [];

    /**
     * add a controller's action permission
     *
     * @param \App\Http\Controllers\Controller $controller
     * @param array $permissions
     */
    public function addPermission(Controller $controller, $permissions)
    {
        $this->actions[get_class($controller)] = $permissions;
    }

    /**
     * get permission name according to the controller and action
     *
     * @param string $controller
     * @param string $action
     * @return null|string permission name or null
     */
    public function permission($controller, $action)
    {
        if(isset($this->actions[$controller]))
        {
            if(isset($this->actions[$controller][$action]))
                return $this->actions[$controller][$action];
        }

        return null;
    }
```
this class will store each route on each controller with action's permission, so with this, I can set permissions for each action. 

and in each controller who need some permissions:
```
        \RoutePermissions::addPermission($this,
            ['create' => 'announce.create']);
```
this means in this controller's `create` action, we need to check the `announce.create` permission, and all other actions don't need to check the permission.

after that,  in our middleware `handle` function:
```
                $action = explode('@', $request->route()->getActionName());
                $perm = \RoutePermissions::permission($action[0], $action[1]);
```
so with these codes, we can get permissions on each action in each controller, if some actions don't have permissions, `$perm` will be null.

I can say that no matter how large is your application, you won't have thousands of permissions, so the memory of course will be less than the compiled.php file, and string compare is also fast.

I think this is another simple solution to middleware permission check. 

and of course, say if you want to check `announce.system` permission in `create` action, that's because you will need to check different permission when user post different options. and that is also easy: custom validation rules.

**Comment by sambenne** [comment]
What I don't understand is that I can pass parameters when doing some like.
```
Route::group( [ 'middleware' => 'license.permissions', 'permissions' => ['document'] ], function () {
    ...
} );
```

This then gives me.
```
Array
(
    [middleware] => Array
        (
            [0] => auth
            [1] => license.permissions
        )

    [permissions] => Array
        (
            [0] => document
        )

    [as] => permissions
    [uses] => HRPulse\Http\Controllers\PermissionsController@getDisplay
    [controller] => HRPulse\Http\Controllers\PermissionsController@getDisplay
    [namespace] => HRPulse\Http\Controllers
    [prefix] => 
    [where] => Array
        (
        )

)
```
But when doing `$this->middleware()` there is no way to pass in that 'action'. There just needs to be a way to take in extra parameters. Maybe a new option in the middleware method that will put this in the actions of the request?

**Comment by jbrooksuk** [comment]
I may be looking at the wrong `middleware` definition here, but in `./framework/src/Illuminate/Routing/Controller.php` there is:

```php
/**
 * Register middleware on the controller.
 *
 * @param  string  $middleware
 * @param  array   $options
 * @return void
 */
public function middleware($middleware, array $options = array())
{
    $this->middleware[$middleware] = $options;
}
```

Which should be able to be passed an array?

**Comment by jmas** [comment]
But $options do not passed to middleware. $options only for internal
framework usage.

On 31 March 2015 at 23:18, James Brooks <notifications@github.com> wrote:

> I may be looking at the wrong middleware definition here, but in
> ./framework/src/Illuminate/Routing/Controller.php there is:
>
> /** * Register middleware on the controller. * * @param  string  $middleware * @param  array   $options * @return void */public function middleware($middleware, array $options = array()){    $this->middleware[$middleware] = $options;}
>
> Which should be able to be passed an array?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/6470#issuecomment-88231870>.
>



-- 
Mobile: +38 099 669 15 06

**Comment by taylorotwell** [comment]
Done in 5.1.

**Comment by GrahamCampbell** [comment]
:ship: :rocket: :ship: :tada: :trophy:

**Comment by jonathanpmartins** [comment]
:+1:

**Comment by jmas** [comment]
Great, thank you!

**Comment by GRAgmLauncher** [comment]
Awww yisss

**Comment by vinkla** [comment]
:+1:

**Comment by Burnett01** [comment]
Awesome @taylorotwell :+1:

**Comment by jonathanpmartins** [comment]
Trying it soon! :+1:

**Comment by Burnett01** [comment]
Works like a charm!
