### ISSUE TITLE
elixir issues and a request

### ISSUE THREAD

**Issue by leemason** [laravel/framework#6520]
posting here as cant find any info on where elixir issues should go (maybe the readme should detail this).

ok so loving the changes coming through, this is more of a request than an issue.

when running gulp --production it minifies js/css which is perfect.

however it would be great if when using the --production flag it made the filename .min.**

especially when building an app that is released for contribution as the .min files could be used for actual usage, but the standard compiled files could be kept expanded for developers to read.

so for example:

/resources/assets/scss/app.scss

would become

/public/assets/css/app.css
/public/assets/css/app.min.css

**Comment by GrahamCampbell** [comment]
We're open to pull requests. :)
