### ISSUE TITLE
A few points/ideas for Queue module.

### ISSUE THREAD

**Issue by d-ph** [laravel/framework#6534]
Hi,

Recently, I setup a Beanstalk Queue system for my Laravel application. After solving some issues with it, I decided to share a couple of points/ideas for making the Queue module easier for devs to implement in the future.

### 1. Queue module should allow devs to set a fallback queue driver (with an event being emitted in the application, when the application needed to use this fallback)
I found out, that when my Beanstalkd daemon is not running (e.g. it crashed), I will get `Connection refused` exceptions from the `pda/pheanstalk` library. This is not the behaviour I'd like to have in my application. What I ended up doing is, I wrote a very simple `beanstalk_with_sync_fallback` queue driver, and set it in the `queue.php` for Laravel to use instead of the plain `beanstalk` driver. Now, when there is "a disaster scenario" (beanstalkd daemon not running), my application falls back to the `sync` driver and sends me an email, that something wrong is happening.

And this is my point. It would be very beneficial and useful to have a `fallback_to_sync => true/false` configuration key in the `queue.php`, which would do this out of the box for any queue driver. This is needed, because very often, if not always, queuing jobs happens after some irreversible operations, which cannot be rerun, after we get an exception from the queue driver. In my case, I'm queuing some `rsync` jobs after I get a successful response from PayPal. I'd rather make it run synchronously, than having an exception thrown at this point.

### 2. Artisan command for checking, whether a daemonised worker/workers are currently running.
I use a daemonised queue worker to process my queued jobs. In order to make everything work without using the maintenance mode when I deploy my app, I came up with this solution:
```
// deploy script
1. Run `php artisan queue:restart`
2. Poll the application whether the queue worker has stopped in interval of 3 seconds.
3. When the queue worker is stopped, then proceed with the deploy.
4. When the deploy is done with success/failure, then rerun the worker.
```
The problem was, that there is no way to check, whether a queue worker is running or not. Because of that, I implemented an artisan command, which returns 1 (true) or 0 (false), when the daemonised worker's running or not. The actual check is implemented in a very similar way to how the `php artisan queue:restart` is implemented. Namely, it's implemented via the `cache` module. I listen on the first application event of `illuminate.queue.looping` (this is when I set a "flag" in my Cache, which says, that the queue daemon is working) and on the the event of `illuminate.queue.stopping` (this is when I set the flag back to `false`). My command simply checks for this flag, and returns 1/0 according to the flag's value. This solution is error prone (the flag is not cleared, when the daemon is closed in any other way than by the `queue:restart`; i.e. it's not cleared, when the daemon crashes), but it does its job and I am aware of the consequences. 

So, I think, that it'd be useful to have an artisan command to check, whether there are any queue workers running at the moment. And maybe a command, that will forcefully clear the cached flag/counter in case of queue worker's failure.

### 3. Emit `illuminate.queue.starting` event, when a new queue worker is started.
In my previous point I said, that I'm listening on the first occurrence of the `illuminate.queue.looping` event. But it'd be much better to actually listen to a `starting` event instead.

### 4. A separate log file for exceptions thrown from queued jobs.
I didn't find digging through the default `laravel.log` file for finding queued jobs' exceptions' stack traces very appealing. Instead, I'm listening on the first queue worker `looping` event, and I'm pushing a new Log handler, which writes all errors to a separate log file called `queue-worker.log`.

This is not an ideal solution, because now I'm writing the errors twice: to the `laravel.log` file and to the `queue-worker.log` file, but I couldn't find an easy and reliable solution to either unregister the `laravel.log` StreamHandler *only*, or to register the StreamHandler destination file conditionally in the `app/start/global.php`.

### 5. `Mail::queue()` should make it possible, to "rebuild" some arguments passed to the emails view template.
I often pass Doctrine entities to emails' views. I cannot do that, when I'm queuing an email via `Mail::queue`, because Doctrine entities are not easily serializable and the only way to pass view variables for the email's view template is by passing an array of view variables. What I do right now is: instead of passing in Doctrine's entities, I pass entities' ids, and then in the view I use the EntityManager to get the entities back from the database. I dislike this solution, because using the EntityManager in views is just plain wrong.

Ideally, instead of array of view variables, the `Mail::queue()` would accept a closure function, which returns an array of view variables. This would give me and other developers an opportunity to rebuild the objects, which are not easily serializable, for the email view template.

### 6. And that's it.
Apart from the above points, everything was a breeze to use. Let me know, if there are solutions to any of the above problems, but I failed to notice them. Otherwise, I hope these points will be helpful for making Laravel an even better framework to use in the future.

Cheers.

**Comment by GrahamCampbell** [comment]
2, 3 and 5 would make good pull requests (separately please). We'd be happy to review them if you were to send them.
