### ISSUE TITLE
Eloquent fields starting with an _underscore are not mass assignable

### ISSUE THREAD

**Issue by hpkns** [laravel/framework#6630]
As I was trying to get Eloquent to save a bunch of properties that start with `_` I realised that it could not be done unless I explicitly added each and every fields that start with `_` in `$fillable`. As I realised, it's because of the `starts_with` test @ [line 2124](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Model.php#L2124). 

I looked in the docs and I could not find the rationale behind this behaviour. I’m sure Taylor put it there for a good reason, but I could not find it anywhere.

**Comment by ebynum** [comment]
Presumably, this dates back to here: https://github.com/laravel/framework/issues/635.

**Comment by GrahamCampbell** [comment]
Thanks @ebynum. Yeh, this is actually the intended behaviour.

**Comment by devcircus** [comment]
for now, to work around it, just overwrite the isFillable method in your model (or a parent model if needed) and remove the last check for an '_' in the key name.
