### ISSUE TITLE
[5.0] Add The Ability To Use Non-Encrypted Cookies

### ISSUE THREAD

**Issue by davejamesmiller** [laravel/framework#6679]
This has been discussed a few times (#6421, #4134, #3440) without resolution. I'd like to offer to write the code for this, but I need to know what direction to take - i.e. would any of these actually make it into Laravel? Here are the options I can think of / find in other issues:

**1.** The simplest solution, which I [have already written code for](https://github.com/laravel/framework/issues/6421#issuecomment-65940223) is to differentiate the encrypted/plain cookies with a prefix before the name when getting/setting them, e.g.:

```php
// Write a cookie named "hello" with a value of "world" (unencrypted)
Cookie::queue('plain::hello', 'world');

// Reading unencrypted cookies
$hello = Cookie::get('plain::hello'); // world

// It won't allow unsigned cookies to be read without the prefix
Cookie::get('hello'); // null
```

The prefix is TBD - it could be `plain`, `raw`, `unsigned`, `unencrypted` or something else. Note that the prefix is not actually used in the cookie name that's sent to the browser, because one of the major uses of this is interoperability with non-Laravel applications where we can't choose the cookie name.

I chose `::` as the separator here because I think it's very rare for it to be used in cookie names, but technically it's allowed so the Symfony cookie class doesn't complain.

(Potentially there could be other prefixes, e.g. `signed::` for the Laravel 3 (or was it 4.0?) method of signing cookies rather than fully encrypting them - if there's any value to that. I'm not sure that there is, just an idea.)

A slight variation would be to use have a [suffix like `_signed`](https://github.com/laravel/framework/issues/3440#issuecomment-39604887) that's actually used in the cookie name for signed/encrypted cookies - and since only Laravel can decrypt them there should be no interoperability issues. But that would break backwards compatibility in a rather insecure & hard to detect way, since existing apps may assume that cookies are encrypted by default, so I don't think it's a good idea.

**2.** [Another option](https://github.com/laravel/framework/issues/3440#issuecomment-40107349) is to have a list of the cookies that shouldn't be encrypted/decrypted in the config:

```php
'unguarded_cookies' => ['legacy_session', 'js-token'],
```

The advantage is this is the simplest option to understand.

The downside is you can't tell just by looking at the code whether or not a cookie can be trusted. Also packages might need a way to add their own cookies to this list, and I'd suggest adding `XSRF-Token` to it automatically too.

**3.** A [third option](https://github.com/laravel/framework/issues/3440#issuecomment-37381659) is to have a separate facade for non-encrypted cookies:

```php
PlainCookie::queue('hello', 'world');
$hello = PlainCookie::get('hello'); // world
```

There is the added complication of `Request::cookie()` though, which would maybe need an equivalent `Request::plainCookie()`. My concern with this option is it could require a lot of changes and get a bit ugly - though I haven't actually tried writing any code yet so I may be wrong.

**4.** For setting the cookies, there could be a wrapper method that creates a different Cookie subclass, telling the middleware not to encrypt them:

```php
Cookie::queue(Cookie::plain('hello', 'world'));
```

However, I don't think this would work as I can't see any way to ensure that other cookies are still encrypted when reading them (`Cookie::get()`). The same would apply to adding another parameter to `Cookie::make()` - though it has a lot already so I wouldn't recommend that one.

---

If none of these would make it into core, and no-one has a better suggestion, I will probably implement option 1 (or maybe option 2) as a separate middleware package, replacing `EncryptCookies`.

But I personally think it should be in core because then the `XSRF-Token` cookie doesn't need to be encrypted unnecessarily, removing ~238 bytes from every request & response (pre-gzip) and saving [some confusion](https://github.com/laravel/framework/issues/6541).

**Comment by ceejayoz** [comment]
What about a chained approach, like `Cookie::plain()->get('something')` and `Cookie::plain()->queue('hello', 'world');`?

Of your four options, my preference is the third one.

**Comment by raulp** [comment]
i love most the idea of Cookie::plain()->get('something') and maybe by default leave Cookie functions without plain to be encrypted ...
Just to keep it simple ;)

**Comment by davejamesmiller** [comment]
I like that - it fits with the rest of the framework better.

**Comment by franzliedke** [comment]
I've wanted something like this for a long time, so I'm all for it.

I think having a separate cookie queue (basically proposal 3) would be the best way to go.

**Comment by davejamesmiller** [comment]
I'm currently thinking of something like this:

```php
// Plain method returns a driver object, as mentioned above
Cookie::plain()->get('something');

// The default driver would be called 'encrypted':
Cookie::get('something'); // Equivalent to:
Cookie::encrypted()->get('something');

// It would then be possible for users to add additional drivers:
// e.g. Signed but not encrypted, like in Laravel 4.0(?)
Cookie::register('signed', 'SignedCookieDriver');
Cookie::signed()->get('something');
```

I'm not sure if I got the terminology or method naming correct - just working from memory - but I think this is similar to other parts of Laravel.

I would then move the cookie encryption/decryption out of the middleware and have the 'encrypted' driver do it on the fly, putting cookies into the response already encrypted. (Not sure if that'll cause a problem for unit testing... Might need to add a getPlainValue() method to the cookie class for that - or getResponseValue() for the response to use - or something like that...)

The ability to add cookies that are signed but not encrypted is something I'd also like to see in core Laravel again, as they're smaller for non-sensitive data, but I think the ability to create custom drivers would be useful anyway - e.g. I have to set cookies to pass data to another application which are signed in a particular way. On the other hand I could continue to sign them in the app code as long as there was a way to set plain cookies.

Of course all of that depends on Taylor signing it off - I see little benefit to doing it this way in a package. If I have to go the package route, options 1 or 2 seem to be much easier to implement because of the way the middleware currently works.

**Comment by RomainLanz** [comment]
:+1:

**Comment by maclof** [comment]
+1 for this, I have wanted something like this in the past and I love the chained method idea, definitely fits with the rest of the framework.

**Comment by franzliedke** [comment]
@taylorotwell Can you tell us which direction you'd prefer? I don't want to put any work into this if I ultimately do something you won't like...

**Comment by RomainLanz** [comment]
Personally, I really like @davejamesmiller's way. https://github.com/laravel/framework/issues/6679#issuecomment-74554788

**Comment by maclof** [comment]
@RomainLanz +1 to that too, I love @davejamesmiller's propsal

**Comment by raulp** [comment]
:+1:

**Comment by mdesign83** [comment]
+1 for @davejamesmiller

**Comment by iJoyCode** [comment]
+1 for @davejamesmiller

**Comment by franzliedke** [comment]
For anybody interested in this, I've finally submitted a [pull request](https://github.com/laravel/framework/issues/9150), implementing a blacklist in the middleware.
