### ISSUE TITLE
[5.0] Ability To Iterate Over Cache Keys

### ISSUE THREAD

**Issue by fireproofsocks** [laravel/framework#6736]
Since issue #6681 was closed without comment, let me refine the request:

Needed is a way to iterate over cache keys.  The app should know which keys were stored and be able to return them on request.  Cache Tags do not support this.

**Comment by GrahamCampbell** [comment]
Has anyone got any input on this? If not I'll close this due to no interest.

**Comment by fireproofsocks** [comment]
How does a feature request equate to "no interest"?

**Comment by GrahamCampbell** [comment]
> How does a feature request equate to "no interest"?

A feature request normally requires someone from the community to implement it, however, if there is no-interest, it would be a waste of their time because it will not be accepted into the core.

**Comment by fireproofsocks** [comment]
That's exactly why I haven't forked this.   Judging from the "country club" mentality and pushback on other pull requests, I'm not about to spend hours on setting myself up for rejection here, but I'm very much interested in having this feature.  It's pretty primitive to work around not having the ability to iterate over existing keys or refresh only parts of the cache.

**Comment by GrahamCampbell** [comment]
> I'm not about to spend hours on setting myself up for rejection here, but I'm very much interested in having this feature.

Make a package then. If it's liked by people, then you can propose to have it merged into the core later.
