### ISSUE TITLE
Coding Style Proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#6836]
This has been floating around for a long time, so let's put this in writing here.

I propose Laravel does one of the 3 following things:

##### ~~3. Moves to PSR-2 with allman style braces.~~ *Rejected*

---

NB, I vote for number 1. NB, we could still do number 1 without yoda style comparisons if needed.

---

EDIT:

Reading through the comments, it's 100% certain that we should at least move to full PSR-2, and a lot of people seem to like the idea of moving to symfony in the interest of consistency, but without yoda comparisons. Moving without yoda conditions is the only way at the moment anyway since we currently have no automated way to enforce them.

**Comment by jwpage** [comment]
If Laravel moves to the Symfony standard, will this include the [naming conventions](http://symfony.com/doc/current/contributing/code/standards.html#naming-conventions) (such as Trait/Interface suffixes) as well, or does this issue only relate to code structure?

**Comment by GrahamCampbell** [comment]
No. Those suffixes don't make sense for laravel.

**Comment by nmabhinandan** [comment]
I think, unless Taylor makes a "Laravel Style Guide", PSR-2 is our best bet!

**Comment by RomainLanz** [comment]
I really don't like Allman Brace, but it's not the meaning of this issue.
I think move to PSR-2 and then PSR-5 is the best idea. I don't if using Symfony standard is really useful for Laravel.

**Comment by GrahamCampbell** [comment]
Symfony is psr2 and psr5 btw. It just adds some extra rules.

**Comment by GrahamCampbell** [comment]
Anyway, thanks for your input guys. I'll close this for now, and I'll have a chat with Taylor at some point.

**Comment by browner12** [comment]
@TomasVotruba https://laravel.com/docs/5.4/contributions#coding-style

**Comment by GrahamCampbell** [comment]
Laravel's code style is also documented at https://styleci.readme.io/docs/presets#section-laravel.

**Comment by TomasVotruba** [comment]
Anything automated and reusable for other repositories?

**Comment by GrahamCampbell** [comment]
> Anything automated and reusable for other repositories?

Yeh. Absolutely. You can pull in the Laravel preset on StyleCI. In fact, thousands of repos already do. :)

**Comment by browner12** [comment]
lots of IDEs will have presets for coding styles. I would start there.

**Comment by TomasVotruba** [comment]
That's not easy to replicate since locked to 1 personalized  program.

So there is nothing like:

```bash
vendor/bin/laravel-cs fix src
```

**Comment by barryvdh** [comment]
Just use PSR-2 for your coding style. That has presets everywhere.

**Comment by TomasVotruba** [comment]
I bet there are many extra rules than PSR-2 in Laravel, like in [`@Symfony` set](https://github.com/Symplify/Symplify/blob/master/packages/EasyCodingStandard/config/symfony-checkers.neon) in PHP-CS-Fixer. That's what I'm looking for.

I'm surprised nobody made such package yet.

**Comment by hannesvdvreken** [comment]
We tried but php-cs-fixer is not that extendible that you can define your own preset like `@something`.

**Comment by TomasVotruba** [comment]
@hannesvdvreken Have you tried config approach like in  `.php_cs` like in repo of PHP-CS-Fixer?
There you can specifiy [all the fixers you need](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/dc04c34f7f2725a55b84d4b075a7d05586abb495/.php_cs.dist#L13-L53).

Then call it in another package like this:

```bash
vendor/bin/php-cs-fixer fix --config vendor/laravel/coding-standard/.php_cs
```

**Comment by Anahkiasen** [comment]
No we went with a [wrapper package](https://github.com/madewithlove/php-cs-fixer-config) as we needed some extra logic

**Comment by valentinxxx** [comment]
I've created a PR with `@Laravel` rule set for PHP-CS-Fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2985
I understand the StyleCI does it's job, but I think it's essential to Laravel based projects which are not using StyleCI.
Feel free to contribute.

**Comment by GrahamCampbell** [comment]
Easier to just use StyleCI. Fixing as a service, and, more importantly, up to date rules as a service. :P

**Comment by valentinxxx** [comment]
@GrahamCampbell Why we can't just use both (optionally the PHP-CS-Fixer)?
(What about private repos?)
It think it's a good starting point for newbies (with IDE integration).

**Comment by GrahamCampbell** [comment]
> What about private repos?

StyleCI supports those too.

> Why we can't just use both (optionally the PHP-CS-Fixer)?

You can, but the config mapping from StyleCI to PHP-CS-Fixer is both proprietary, and actually, only partial. You can't just do a 1-1 map. I know of a GitHub project that attempts to do this, but it doesn't work well.

**Comment by TomasVotruba** [comment]
@valentinxxx I agree with you, mainly for usability and adaptability reasons.

I consider this much easier for entry:

```bash
composer require <tool>
vendor/bin/<tool> fix --rule=@Laravel 
``` 

No matter if it is public or private project.

**Comment by keradus** [comment]
StyleCI is basically a wrapper over PHP CS Fixer with few additions.
Asking ppl to rely on web-service and not running it locally is not nice, imagine same for tests - statement that one shall rely on Travis/CircleCI/AppVeyor/... and not run PHPUnit/Behat/... at all is extra sad

**Comment by TomasVotruba** [comment]
@keradus Well written, I share the view with you.

**Comment by GrahamCampbell** [comment]
That's fine. I'm just saying someone needs to take responsibility for updating the mapping. StyleCI's maintainers will not be doing that.

**Comment by GrahamCampbell** [comment]
> StyleCI is basically a wrapper over PHP CS Fixer with few additions.

Yeh, that's true. We're not claiming we don't do that for PHP code. :P

**Comment by GrahamCampbell** [comment]
In recent times, the difference between StyleCI and PHP-CS-Fixer is getting smaller and smaller. The main difference left at this point, is just config.

**Comment by keradus** [comment]
> Yeh, that's true. We're not claiming we don't do that for PHP code. :P

I remember originally StyleCI provides information it's built on top of PHP CS Fixer. I cannot find it now.

**Comment by GrahamCampbell** [comment]
We're not claiming that we don't.

**Comment by keradus** [comment]
You did say it explicitly one day. Now you don't. Sad for a service that's basically a big wrapper.
Even with every update you just take changelog of PHP CS Fixer.

**Comment by valentinxxx** [comment]
I see this is a very sensitive area for you guys, I just want to create a `@Laravel` ruleset for this great tool. As I stated before this is a very convinient way for using Laravel-like coding style on private stuff (e.g. projects without git 🙈)

(Btw. I think it's out of topic 😶 https://gjcampbell.co.uk: `...StyleCI is powered by PHP CS Fixer...`)

**Comment by CupOfTea696** [comment]
What I'm still wondering is why Laravel adopted string concatenation with no spaces (e.g. `'hello'.'world'`) instead of with spaces (e.g. `'hello' . 'world'`). I find the second one way more readable and I don't believe PSR-2 has rules for that?

**Comment by browner12** [comment]
because it's all made up, and the points don't matter!

**Comment by philsturgeon** [comment]
There's nothing about that in PSR-2. As a friendly word of warning, this thread would be a poor location to open up the can of worms that is raising (dis)agreements with arbitrary style choices made by Laravel on top of PSR-2.

Lots of mud and weeds to get stuck in down that road.
