### ISSUE TITLE
Allow multiple routes per controller action

### ISSUE THREAD

**Issue by JamShady** [laravel/framework#6852]
Presently, Laravel registers one URL per controller action, which is a little bit contradictory to the way resource routes are handled (in that, they accept multiple routes).

Consider the following:
````
class PetController extends ResourceController {} // implements common CRUD actions

abstract class Pet extends Illuminate\Database\Eloquent\Model {}
class Cat extends Pet {}
class Dog extends Pet {}


class AdoptionController extends BaseController {

	public function postAdopt(Pet $pet) {
		$pet->update([
			'isAdopted' => 1,
		]);
	}

}

Route::resource('cats', 'PetController'); // registers basic CRUD operations
Route::bind('cats', function($name, $route) { 
	return Cat::where('name', $name)->first(); 
});
Route::controller('cats/{cats}/adoption', 'AdoptionController');

// so far, so good...

Route::resource('dogs', 'PetController'); // registers basic CRUD operations
Route::bind('dogs', function($name, $route) { 
	return Dog::where('name', $name)->first(); 
});
Route::controller('dogs/{dogs}/adoption', 'AdoptionController'); // uh-oh...


print app('url')->action('AdoptionController@postAdopt', ['dogs' => 'fido']);
// outputs http://mydomain/cats/fido/adopt <-- broken route binding, no cat named Fido exists
````

The problem here is that there are technically two routes to AdoptionController@postAdopt, which are:

* /cats/{cats}/adopt, and
* /dogs/{dogs}/adopt

But there's no way of retrieving the second URL because in this case, only the first is recognised and used.

So, assuming there is no way to get around this (using the current implementation, i.e. without changing how the classes/controllers work), my proposal is to update the functionality in the following way:

1. Update RouteCollection to store an array of routes (as opposed to just one) on the relevant properties
 * $routes
 * $allRoutes
 * $actionList
2. Update Routing\UrlGenerator to choose best route based on the parameters supplied (i.e. first one where all parameters are resolved)
 * so in this case, when ['dogs' => 'fido'] is passed through, the {cats} parameter isn't resolved for the cat-version of the url, thus it's ignored, and the subsequent dog one will resolve and that'll be returned back

The main reason for posting this is just to ensure I'm going about this in the right way, because I would like to submit this back as a PR and it's going to be quite intrusive, so want to make sure I'm not doing something completely silly.

(btw, I realise the update steps are vague, am still working out how the whole thing fits together to find the most appropriate point to make the required changes - any clear direction would be much appreciated, but otherwise I'm using xdebug to trace my way through everything)

**Comment by TheShiftExchange** [comment]
I dont understand - seems like an edge case that can be easily solved by just explicitly listing the routes instead of using the `resource()` and `controller()` route functions?

Or am I missing something else?

**Comment by JamShady** [comment]
You're right, it's just in my particular example the routes generated are a little more complicated and involved, and the helper I wrote determines the end point (in this case, adoption) and passes in the supplied variables. Essential, I can do Url::adoption($pet) and it'll generate the right URL for me, except in this instance it'll break if $pet is a dog.

**Comment by JamShady** [comment]
Decided to close this as I implemented a different solution for my current project, so seeing as I'm not going to be implementing this one, no point keeping it open.
