### ISSUE TITLE
[5.0][Command bus][Proposal] SelfHandlingCommand and ShouldBeQueued as annotations

### ISSUE THREAD

**Issue by hannesvdvreken** [laravel/framework#6870]
Wouldn't it be useful to create annotations to replace the usage of the empty interfaces `SelfHandlingCommand` and `ShouldBeQueued`?

**Comment by franzliedke** [comment]
No. ;-)
Am 02.01.2015 09:51 schrieb "Hannes Van De Vreken" <notifications@github.com

**Comment by hannesvdvreken** [comment]
Ok :-) and why? To me it seems like a great use case.

**Comment by franzliedke** [comment]
Why implement something with annotations that is a perfectly valid use case for interfaces? Again, you get all the downsides of annotations for free, all the while you could just do it with plain PHP, too.

**Comment by hannesvdvreken** [comment]
I'm not familiar with downsides of annotations. Can you point me to an article or something?

**Comment by bigsinoos** [comment]
It is one of the exact use case of interfaces, why should it be replaced by annotations ?

**Comment by franzliedke** [comment]
I happen to have written one. ;)
http://www.develophp.org/2014/10/annotations-show-me-the-benefits/

Also, speed.

**Comment by hannesvdvreken** [comment]
@bigsinoos @franzliedke dunno, isn't `instanceof` and empty interfaces a code smell? Just proposing here :-)

**Comment by GrahamCampbell** [comment]
Laravel is never going to do that.
