### ISSUE TITLE
don't use contracts god namespace

### ISSUE THREAD

**Issue by bazo** [laravel/framework#6871]
why are all contracts for all components under one huge god namespace? they should be with the corresponding components. 

if i want to use one single component, all the contracts get installed too which makes no sense. 
especially annoying when the interface names popup on every autocompletion prompt

**Comment by bigsinoos** [comment]
Contracts should be decoupled from the concrete implmentation of them so they can be replaced with new implmentations without having previous(default) ones.

**Comment by Anahkiasen** [comment]
Also really useful to code packages without having to require half of Laravel.

**Comment by GrahamCampbell** [comment]
Yeh, that's the entire point.

**Comment by bazo** [comment]
ok, whatever. i just find it ridiculous to download gazillion interface files when i need only one. not everybody uses the whole laravel.

imho interfaces should be a part of the component/package/use case namespace, not separate. 

this is the first time i see such an approach. but laravel has always been special in the wrong way.

**Comment by GrahamCampbell** [comment]
Well downloading a load of interfaces is better than downloading the entire framework.

**Comment by bazo** [comment]
why would you download the entire framework? that's also wrong. if laravel so heavily builds on symfony, why doesn't it use the same approach to standalone components? if i want to use a single component from symfony, i don't have to download a bunch for interfaces for completely not related components that are not even present in my install.

**Comment by bigsinoos** [comment]
Why do you make it so complicated? Whats the matter with some files that may not be used but only exist in your project?

**Comment by GrahamCampbell** [comment]
The contracts make a lot of sense. I maintain a lot of packages, and it has definitely reduced my dependance on so many components of laravel. For example, I no-longer depend on laravel's config. As long as anyone gives my code any implementation, we're good.
