### ISSUE TITLE
[proposal] some kind of namespacing on globals

### ISSUE THREAD

**Issue by CarstenHoyer** [laravel/framework#6872]
I just installed Drupal and Drush in Homestead using Composer. I know Homestead is made for Laravel, but its just so good :)

When doing anything with Drush I would get:

>PHP Fatal error:  Cannot redeclare base_path() (previously declared in /home/vagrant/.composer/vendor/illuminate/support/Illuminate/Support/helpers.php:365) in /home/vagrant/Workspace/drupal/8/community/core/includes/common.inc on line 830

Drupal also has a base_path global function. I ended up renaming the Laravel base_path to laravel_base_path. Maybe not the prettiest solution, but it looks like it is working for now.

Please consider some solution (probably not mine) to this problem.

EDIT: Same goes for dd()

**Comment by GrahamCampbell** [comment]
That would go against the whole point of these functions, sorry. They need to be easy to use in views, like the `trans` function. We can't namespace them.

**Comment by rossedman** [comment]
@CarstenHoyer how did you work around this and change this variable when working in Drupal sites?

**Comment by CarstenHoyer** [comment]
@rossedman I didn´t. I started using Homestead for Laravel and [VDD][https://www.drupal.org/node/2008792] for Drupal. Much better solution.

**Comment by rossedman** [comment]
@CarstenHoyer Thats what I was considering. Thanks so much for responding.

**Comment by kenorb** [comment]
I've got the same problem with Drupal.

Follow-up:

- laravel/internals/issues/709
- laravel/framework/issues/20370
