### ISSUE TITLE
Postgres not honouring read/write host config

### ISSUE THREAD

**Issue by outrunthewolf** [laravel/framework#6880]
We're configuring our Postgres databases for read write like so:

```php
        'pgsql' => array(
            'driver'   => 'pgsql',
            'read' => array(
                'host'     => 'api-read.xxxx',
            ),
            'write' => array(
                'host'     => 'api-master.xxxx',
            ),
            
            'database' => 'api',
            'username' => 'xxxxx',
            'password' => 'xxxxx',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        )
```

We've outputted connection data all the way to the Laravel database connection files and as far as I can tell Laravel is always reading and writing to/from the master and ignoring the read replica. 

Has anyone had the same issue? Or am I misconfiguring the setup here?

If you'd like me to drill further for an explanation let me know, I'd love to get this sorted so any help would be much appreciated.

**Comment by outrunthewolf** [comment]
This may not be a Laravel issue from my further investigation. I'll close this issue for now.

**Comment by outrunthewolf** [comment]
Found the problem. Laravel always connects to the write host even if we're only running a read query.

If we're running a master DB in the EU, and several replicas in the US for example. Then we make a purely read query, Laravel wastes time connecting to the master DB when it doesn't need to. This causes lots of latency.

Main issue is:
createReadWriteConnection
illuminate/Database/Connectors/ConnectionFactory

Always opens a connection to the read DB.

Hopefully this makes sense.

**Comment by GrahamCampbell** [comment]
We're open to pull requests. :)

**Comment by outrunthewolf** [comment]
Yeah... I feared you might say that. I'll take a look at it.

**Comment by GrahamCampbell** [comment]
:beers:

**Comment by GrahamCampbell** [comment]
Ping @outrunthewolf.

**Comment by outrunthewolf** [comment]
@GrahamCampbell you're such a work nazi. ;P

I have a fixed fork, at some point i'll try and write the tests and p/r you. I don't believe its an issue for anyone else?

I have to admit though, not connecting to the database until the query is going to run has decreased our latency across regions by a factor of 10...

**Comment by GrahamCampbell** [comment]
:rocket:

**Comment by stevenmyhre** [comment]
Did this ever get created/merged? Looking for a solution as when my master goes down, it bring the entire app down (no reads available even)

**Comment by mayken** [comment]
Any news? Same problem with PostgreSQL

**Comment by icelake0** [comment]
@outrunthewolf
what's up with your fixed fork?
did you ever make the PR?
did it ever got merged?
Does anyone know a workaround for this?
cc @taylorotwell

**Comment by mayken** [comment]
> @outrunthewolf
> what's up with your fixed fork?
> did you ever make the PR?
> did it ever got merged?
> Does anyone know a workaround for this?
> cc @taylorotwell

You can use two connection as  'pgsql_read' => [config] and 'pgsql_write' => [config]
