### ISSUE TITLE
[5.0] Add toSentence() helper for Collection

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#6889]
I'd like to propose the addition of a `toSentence()` helper for the Collection class. This method would make it easy to fetch a number of items from a collection and then format them as a proper sentence. This is inspired by the [`to_sentence`](http://apidock.com/rails/Array/to_sentence) method in Rails.

    Illuminate\Support\Collection::make(['one'])->toSentence(); // one
    Illuminate\Support\Collection::make(['one', 'two'])->toSentence(); // one and two
    Illuminate\Support\Collection::make(['one', 'two', 'three'])->toSentence(); // one, two and three

It would also work with the database collection so that Eloquent models can be used.

    $george = User::create(['first_name' => 'George']);
    $jane = User::create(['first_name' => 'Jane']);

    Illuminate\Database\Eloquent\Collection::make([$george, $jane])->toSentence('first_name'); // George and Jane

The method would accept three parameters that allow control over the construction of the sentence.

    function toSentence($attribute, $wordsConnector = ', ', $lastWordConnector = ' and ');

I would imagine that when the default parameters are not provided the translations should come from a language file rather than being hard-coded

**Comment by bigsinoos** [comment]
It could be a pull request instead of an issue !!!

**Comment by dwightwatson** [comment]
It's a proposal, as per the contribution guidelines I'm checking to see if the feature would be considered before making a pull request so that it's not a wasted effort.

**Comment by GrahamCampbell** [comment]
Actually, our contribution guidelines are incorrect. If someting will take you less than 30 mins to implement, just send a pull. It's quicker for everyone.

**Comment by dwightwatson** [comment]
Cool, thanks for clarifying. Will create a PR tonight.

**Comment by CurosMJ** [comment]
:+1: Dont forget writing tests. :D
