### ISSUE TITLE
[5.0] when() on router doesn't run middleware.

### ISSUE THREAD

**Issue by Garbee** [laravel/framework#6890]
Currently the [when method of the router](https://github.com/laravel/framework/blob/master/src/Illuminate/Routing/Router.php#L846) only runs *filters* when used. However, when using the ```route:list``` command it shows the middlewares as registered on the routes just fine.

From the comment for the when method, I would assume the list generation is buggy since they shouldn't be registered. However, I would like to see if Router::when() could also work for middlewares to reduce duplication of definitions throughout routes.

Which is the bug and how should it be go about getting fixed?

**Comment by GrahamCampbell** [comment]
Thanks for reporting this.

**Comment by taylorotwell** [comment]
So you saying when the `when` method is used no middlewares are run at all?

**Comment by Garbee** [comment]
Yea, they never execute. Nor do they execute when using the group method. However, they appear in route:list as if they are attached for execution.

**Comment by taylorotwell** [comment]
Can't recreate. Submit a failing test if you feel the problem persists.
