### ISSUE TITLE
[5.0] Proper setting of mb_internal_encoding()

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#6891]
Following the removal of the call to [Patchwork\Utf8\Bootup::initMbstring()](https://github.com/laravel/laravel/commit/0e0fd73b435d22aebb2efd2c42bf9df23d197b99#diff-13) then the complete removal (#4521) of Patchwork UTF-8.

I found out I was relying on [its setting of mb_internal_encoding()](https://github.com/nicolas-grekas/Patchwork-UTF8/blob/62a1f7f777fb121e13c9ddbbd4718060d2fda08f/class/Patchwork/Utf8/Bootup.php#L55) to the excepted "UTF-8" value. The default appears to be "ISO-8859-1" even on PHP 5.4.

As it affects all the mb_* functions, and is something easily overlooked, I'm pretty sure many users will have trouble because of this.

So, I think this `mb_internal_encoding('UTF-8')` should be added somewhere in Laravel (5). Also, looking at all the stuff in initMbstring(), there may be other things worth adding.

**Comment by GrahamCampbell** [comment]
You've referenced https://github.com/laravel/laravel/commit/0e0fd73b435d22aebb2efd2c42bf9df23d197b99#diff-13, but that didn't actually remove it. It was just moved elsewhere.

**Comment by GrahamCampbell** [comment]
Hmmm. I disagree. We shouldn't be changing people's config at runtime. If they want utf8, they need to have setup php correctly.

**Comment by mikeritter** [comment]
Unfortunately, PHP the Right Way disagrees with Graham's assertion http://www.phptherightway.com/#php_and_utf8

**Comment by GrahamCampbell** [comment]
No it doesn't?

**Comment by GrahamCampbell** [comment]
Oh, yeh. Didn't read this correctly just then. Feel free to send a pull then.

**Comment by vlakoff** [comment]
I think we really should switch back to Patchwork UTF-8, for now. I've found so many things that make Stringy not a viable replacement in its current state.

And put back this:

    // btw add this, extracted from Patchwork\Utf8\Bootup::initAll()
    ini_set('default_charset', 'UTF-8');

    // restore this
    Patchwork\Utf8\Bootup::initMbstring();

Adding the `ini_set(...)` let us not rely on a [fix in Symfony Response](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Response.php#L284).

**Comment by GrahamCampbell** [comment]
> I think we really should switch back to Patchwork UTF-8, for now.

I totally disagree.

**Comment by mikeritter** [comment]
@GrahamCampbell I'm still learning so not able to contribute a meaningful pull, nor meaning to stir trouble, just thought this was worth noting as it popped up in my best practices research.

Maybe this just goes with the framework migrating toward a more mature developer audience.

**Comment by taylorotwell** [comment]
I made change to set mb_internal_encoding when configuration is loaded. Thanks.

**Comment by mikeritter** [comment]
cool

**Comment by vlakoff** [comment]
Refs https://github.com/laravel/laravel/commit/058eebfaf9124e9d475a7da966ca56a9e1c81718.

Now that PHP 5.6 is required, looks like it's not needed anymore.
Doc: http://php.net/manual/en/ini.core.php#ini.default-charset

In what branch shall I PR to remove it?
