### ISSUE TITLE
[5.0] Boilerplate controllers confusing names

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#6892]
Currently, Laravel 5 has two boilerplate controllers: `HomeController` and `WelcomeController`.

Each time I see them I think "oww which one it the frontend one ?". Then I open both files and spend a tiny bit of time to figure out... I can't stop mixing their names :disappointed_relieved:

Case in point, for quick debugging I just throw code in the homepage controller (it's `WelcomeController`).

How about naming the backend controller something like `DashboardController`? It would be so much clearer :grinning:

<br>
(BTW, the "home" view is currently missing, but I guess you're already aware)

**Comment by GrahamCampbell** [comment]
We're open to pull requests.
