### ISSUE TITLE
Add MySQL's SET column type to the Schema Builder

### ISSUE THREAD

**Issue by tgfisher** [laravel/framework#6899]
I noticed that there is no SET column type available for the Schema Builder.

http://dev.mysql.com/doc/refman/5.0/en/set.html

**Comment by GrahamCampbell** [comment]
Laravel supports custom schemas. If you thin the SET column would be useful to lots of people, then please send a pull request to add it.

**Comment by GrahamCampbell** [comment]
Ish...

https://coderwall.com/p/mo1gew/custom-datatype-in-laravel-schema-builder

**Comment by pierrocknroll** [comment]
https://github.com/laravel/framework/pull/24229
