### ISSUE TITLE
Cache language files

### ISSUE THREAD

**Issue by ibrasho** [laravel/framework#6907]
I really do like the caching of config files. It's an improvement over having to load each file separately.

Can we do the same for language files?

I started working on a PR to implement this, but the issue I'm facing is loading package files.

In 4.2, and so far in 5.0, there is no way to know which packages are used in the application, therefore you can't cache the files.

Any ideas on how to deal with this? Is this something needed?

**Comment by GrahamCampbell** [comment]
Not sure. Maybe. Ping @taylorotwell.

**Comment by joshhornby** [comment]
+1

**Comment by GrahamCampbell** [comment]
We're open to pull requests.
