### ISSUE TITLE
[4.2] Can't get the session ID stored in database

### ISSUE THREAD

**Issue by brazenvoid** [laravel/framework#6908]
I am trying to add extra info in the sessions table by making another model Sessions. 

    class Sessions extends BaseModel
    {
        protected $table = 'sessions';
        protected $fillable = array(
            'id', 
            'payload', 
            'last_activity', 
            'user_id', 
            'type', 
            'created_at');

        public static function getCurrent()
        {
            return Sessions::find(Session::getId());
        }
    } 

I am using laravel v4.2.16 with database based session management. The function Session::getId() doesn't return the id stored in the database thus I can't get the current session's modal through my Sessions::getCurrent() method.

The approach worked before v4.2.16.

**Comment by shehi** [comment]
I may be wrong, but shouldn't it be ```Sessions::getId()``` instead of ```Session::getId()```?

**Comment by GrahamCampbell** [comment]
Neither is named session. But `Session` is the name of a facade.

**Comment by RomainLanz** [comment]
Try to put your Session's class into a namespace.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
