### ISSUE TITLE
Deploy Laravel 4.2 behind proxy server

### ISSUE THREAD

**Issue by thanhson1085** [laravel/framework#6910]
My scenario as below:
- Public domain: example.com
- Private IP: 10.0.0.5
- Laravel is deployed to server addressed 10.0.0.5 behind proxy server addressed example.com
- URL::to('/') return 10.0.0.5. I expected that I am able to defined base url for Laravel when I set app.url = 'example.com'.

**Comment by GrahamCampbell** [comment]
app.url must be a valid url. That is not a valid url. `'https://example.com` is a valid url.

**Comment by thanhson1085** [comment]
@GrahamCampbell , thanks for your quick response.
I used a valid URL (http://example.com). But URL::to('/') return 10.0.0.5. How can I change it?

**Comment by ibrasho** [comment]
The `app.url` config is only used in the `route:list` artisan command.

I think your best bet is using `Url::forceRootUrl('http://example.com')`.
But I assume there is a better way...
