### ISSUE TITLE
Question: are workbench packages coming back in v5?

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#6911]
As the title: will workbench packages be coming back in Laravel 5 at all? As I couldn’t see an official roadmap. Also, apologies if this is the wrong place to ask this question.

I used workbench packages a lot to create private packages for my Laravel projects. It’d be great if this was brought back so I could create a package skeleton via Artisan. Or is the recommendation to now create our own framework-agnostic packages to load into Laravel via a Laravel-specific service provider?

**Comment by GrahamCampbell** [comment]
No. Workbenches are gone.

**Comment by martinbean** [comment]
@GrahamCampbell Good to know. Thanks for the speedy response.

**Comment by martinbean** [comment]
Question: if packages are no more, how does one go about running things like migrations that may be in a third-party library?

**Comment by GrahamCampbell** [comment]
You don't. You're meant to publish them to your own migrations folder in the same way the laravel failed queue command does it.

**Comment by martinbean** [comment]
@GrahamCampbell Is there an example of this in practice? I’m not sure how you’d “publish” migrations if Laravel 5 no longer knows about packages?

**Comment by GrahamCampbell** [comment]
Packages should register their own commands.

**Comment by martinbean** [comment]
@GrahamCampbell So if I create a say, `publish:migrations` command, what should that do? `mv` the migrations into the *database/migrations* directory in the “parent” Laravel application?

**Comment by GrahamCampbell** [comment]
No. You write your own command.

**Comment by GrahamCampbell** [comment]
You write your own version of this https://github.com/laravel/framework/blob/master/src/Illuminate/Queue/Console/TableCommand.php, specific to your package. Then your users use your command.

**Comment by martinbean** [comment]
@GrahamCampbell I think the above is similar to what I was trying to say. Only in my scenario, I’d actually have the migration classes ready in a directory in my package, and my command would move those classes to the outer Laravel installation’s **database/migrations** directory, instead of using “stub” text files with the migration classes’ content.

**Comment by GrahamCampbell** [comment]
Right, whatever you want. That's the point. :)

**Comment by martinbean** [comment]
@GrahamCampbell Cool. Thanks for the speedy response :)
