### ISSUE TITLE
[L5] Inject `Illuminate\Contracts\Config\Repository` when calling ServiceProvider::register

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#6914]
I'm not sure if it's available when the framework is registering `ServiceProviders`, but I'm wondering if it might be useful to inject Laravel's configuration repository to calls to `ServiceProvider::register`.

I'm basing this suggestion off of the following two tidbits of info:

https://twitter.com/taylorotwell/status/551911499266928640

https://twitter.com/taylorotwell/status/551925053089406976

Of course, as always if I've misunderstood something, I apologize.

**Comment by GrahamCampbell** [comment]
Nah, that would be pointless. You can access the config with `$this->app->config->...`.

**Comment by ibrasho** [comment]
`$this->app['config']` ; )

**Comment by atrauzzi** [comment]
I think using the array syntax implicitly makes use of the dependency injection system, which Taylor outlined was to be avoided.

Now, the fact that I'm calling `config` out of it and that it's most likely loaded at that time is certainly significant.  But to the reader, this would make it look like the container is ready when in fact it's not.

I think @GrahamCampbell's suggestion is good because it's strongly typed and so it indicates that we're still early in the game.
