### ISSUE TITLE
Auth::check() doesn't work

### ISSUE THREAD

**Issue by alexfedotov** [laravel/framework#6917]
Laravel's function Auth::attempt() returns true in the following code section (with unimportant parts deleted):

    public function doLogin()
    {
        $validator = [..]
    
        if ($validator->fails()) {
            [..]
        } else {
            $userdata = array(
                'username'  => Input::get('username'),
                'password'  => Input::get('password')
            );
    
            if (Auth::attempt($userdata, true)) {
                return Redirect::to('/');
            } else {        
                return Redirect::to('login');
            }
        }
    }
But when we are redirected, we try to check if an user is really logged in with Auth::check(), and it returns false somehow.

As a last resort, we even tried to print something in the Auth::attempt() method of Laravel in ./vendor/laravel/framework/src/Illuminate/Auth/Guard.php but we did not see anything of that, not even with print_r. We tried to find other attempt-functions in the complete codebase but none is found.

It could be that something about changing User to an translated form of it makes it broken, but then the function Auth::attempt() should also be broken, probably.

http://stackoverflow.com/questions/27780985/laravels-authattempt-returns-true-but-authcheck-returns-false?noredirect=1#comment43972421_27780985

**Comment by rscafi** [comment]
Is your session persisting? Try to set a key in one place and retrive it in another.
If it doesn't, thats your problem.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
