### ISSUE TITLE
[5.0] FormRequest sanitized input not being passed into commands with dispatchFrom

### ISSUE THREAD

**Issue by JosephSilber** [laravel/framework#6922]
The `FormRequest` object [now supports](https://github.com/laravel/framework/pull/5950) sanitizing the user's input.

To get the sanitized input, you have to call the `sanitized` method:

```php
$request->sanitized(); // returns [...], like Input::all();

// or...
$request->sanitized('foo'); // returns what Input::get('foo') would, sanitized.
```

However, when populating a command with `dispatchFrom`:

```php
$this->dispatchFrom(Command::class, $request);
```

...it'll just iterate over the `$request` object, which will return the raw unsanitized input.

To solve this problem, we *could* check for an instance of `FormRequest` in [the `marshal` method](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Bus/DispatchesCommands.php#L65) and call `$source->sanitized()`, but that's an ugly hack.

---

Even without this problem, it would make more sense to somehow replace the default input with the sanitized input, and instead have a `raw` method to get the unsanitized input. This is more secure by default, and would also help with this `dispatchFrom` problem.

Taylor told me a while ago that this is actually how he would prefer it, and that I should change it to default to the sanitized input. Alas, implementing this proved rather challenging. I've tried it a few times, but have always come up empty.

The input itself can come from many different sources (get data, post data, post json data etc.), and repopulating all those sources, respectively, is nigh impossible. They can also be accessed through a myriad of methods (get, input, all etc.). Overwriting all those methods isn't really feasible either.

Ideas?

**Comment by MartijnThomas** [comment]
Taylor removed the sanitization feature: https://github.com/laravel/framework/commit/924a7fcf21bbba4f4efc8e367f456cea5e4d25c1

**Comment by JosephSilber** [comment]
:cry:

**Comment by GrahamCampbell** [comment]
You should probably just implement your own solutions here. Perhaps a decorator for the request object would do it for you? It's not like we're removing a feature laravel ever actually had here. No tagged release contains this.

**Comment by joshhornby** [comment]
Does anyone have an example of this working with a decorator request object? The solutions posts at the bottom of this thread seem a little clunky https://github.com/laravel/framework/commit/924a7fcf21bbba4f4efc8e367f456cea5e4d25c1
