### ISSUE TITLE
keys() method on support collection

### ISSUE THREAD

**Issue by stygiansabyss** [laravel/framework#6928]
While the values() method sets the items array to the values and returns a new collection, keys() does not.  Is this intentional for some reason?

I would assume that keys would return a collection so it could then be further handled by the collection methods.

**Comment by ibrasho** [comment]
Actullay, the `Collection::values()` method:

> Reset the keys on the underlying array.

It doesn't return a new collection, it just set the current instance `$items` property to the result of `array_values()` and return the same instance.

**Comment by stygiansabyss** [comment]
Well, yes.  But that means you can still chain collection methods on it.  Keys() does not do this.

**Comment by ibrasho** [comment]
https://github.com/laravel/framework/pull/6930

**Comment by stygiansabyss** [comment]
:) Brilliant.  Thanks!

**Comment by GrahamCampbell** [comment]
Discussion can continue on the pull request. :)
