### ISSUE TITLE
What is the replacement for: Patchwork\Utf8\Bootup::initMbstring()

### ISSUE THREAD

**Issue by loduis** [laravel/framework#6931]
When I create a new artisan command that has to generate files that contain accents or other characters diferent to ASCII this is not creating the content of the file in utf8 format.

What is solucion in artisan commands for: Patchwork\Utf8\Bootup::initMbstring()

**Comment by GrahamCampbell** [comment]
You need to correctly configure your php setup.

**Comment by jombelanja** [comment]
how to correctly configure php setup?
