### ISSUE TITLE
Model $touches does not like many-to-many relationships

### ISSUE THREAD

**Issue by impleri** [laravel/framework#6932]
Example models:

````
class Address extends Eloquent
{
    public $touches = ['people'];

    public function people()
    {
        return $this->morphedByMany('Person', 'addressable');
    }
}
````

````
class Person extends Eloquent
{
    public function addresses()
    {
        return $this->morphToMany('Address', 'addressable');
    }
}
````

Saving an Address gets a `exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::touchOwners()`. I'm guessing the model's touchOwners should be looping through the collection since I cannot seem to find a touchOwners() method anywhere but on the Model.

May be a dupe of #6386 ?

**Comment by GrahamCampbell** [comment]
Yeh, please can you comment on the original issue, and include this example.
