### ISSUE TITLE
alpha,alpha_num,alpha_dash validation bug?

### ISSUE THREAD

**Issue by ycrao** [laravel/framework#6935]
When I using `alpha,alpha_num,alpha_dash` to validate form data, some Chinese string can still passed.
Is that bug?

here the test code
```
#temp test route
Route::get('/test', function()
{
	
	$data = array('username'=>'测试');  //passed
	//$data = array('username'=>'!@#67abcd');  //failed
	//$data = array('username'=>'abcd');  //passed
	//$data = array('username'=>'测试abcd');  //passed
	//$data = array('username'=>'测试^&abcd');  //failed
	//$data = array('username'=>'나이프');  //passed
	//$data = array('username'=>'にほんご');  //passed
	$messages = array(
		'username.required'   => '请填写用户名',
		'username.alpha_num'  => '用户名只能阿拉伯数字与英文字母组合',
	);
	$rules = array(
		'username'             => 'required|alpha_num',
	);
	$validator = Validator::make($data, $rules, $messages);
	if ($validator->passes()) {
		return 'username passed:'.$data['username'].'.';
	}
	else{
		return 'username failed:'.$data['username'].'.';
	}
});

```
$data = array('username'=>'测试'); passed
![qq 20150107131040](https://cloud.githubusercontent.com/assets/3280204/5641212/cc3ec6f2-966e-11e4-9ba5-eadece221c27.jpg)
$data = array('username'=>'!@#67abcd'); failed
![qq 20150107131132](https://cloud.githubusercontent.com/assets/3280204/5641240/901bc2d2-966f-11e4-89d9-d8ab9ff24776.jpg)

**Comment by ibrasho** [comment]
`alpha` validation returns the results of `preg_match('/^[\pL\pM]+$/u', $value)`

This matches any Unicode character that is a letter, or a combining mark in some languages.

Refer to: http://www.regular-expressions.info/unicode.html#prop for more info.

**Comment by ycrao** [comment]
@ibrasho thanks!

**Comment by tylerdong** [comment]
@ycrao 怎么解决这个问题的呢？
那个参考文章里面也没有看到解决方法

**Comment by ycrao** [comment]
@tylerdong 自己写扩展方法即可

**Comment by Jakobud** [comment]
Seems really weird to me that this is acceptable for the `alpha` validation. This is definitely not clear in the documentation: https://laravel.com/docs/5.5/validation#rule-alpha. Very misleading.

In my opinin `alpha` should just be a simple regex match for `[0-9a-zA-Z]` and maybe create a `unicode-letter` validation rule that does the above validation.

**Comment by lifeblood** [comment]
// app/Providers/AppServiceProvider.php
use Illuminate\Support\Facades\Validator;
public function boot()
    {
        // 添加验证规则,允许字母
        Validator::extend('alpha_new', function ($attribute, $value, $parameters, $validator) {
            return is_string($value) && preg_match('/^[a-z]+$/iu', $value);
        });
        // 添加验证规则,允许字母_-数字
        Validator::extend('alpha_dash_new', function ($attribute, $value, $parameters, $validator) {
            return is_string($value) && preg_match('/^[a-z_-]+$/iu', $value);
        });
        // 添加验证规则,允许字母数字
        Validator::extend('alpha_num_new', function ($attribute, $value, $parameters, $validator) {
            return is_string($value) && preg_match('/^[a-z0-9]+$/iu', $value);
        });
    }

**Comment by dong-sir** [comment]
## alpha_dash

> The field under validation **may have** alpha-numeric characters, as well as dashes and underscores.

Try this rule instead of `alpha_dash`


```
[
    'username' => ['regex:/^[0-9a-zA-Z_\-]*$/']
]
```
