### ISSUE TITLE
OpenSSL extension is required. 

### ISSUE THREAD

**Issue by Salon-sai** [laravel/framework#6936]
The picture shows the error message.I search the php.ini and sure openssl extension is ok.
In the first time,I load the index.php.Everything is fine.
However, load again the page.The problem comes.
If I clear the cookie in the browser,it is ok.
Please help me!!

![laravel-question](https://cloud.githubusercontent.com/assets/4996787/5641809/14f49b46-967a-11e4-9e7e-a932c9e122ac.png)

**Comment by ycrao** [comment]
restart your apache when you have changed your php.ini.

**Comment by Salon-sai** [comment]
The problem is solved.
The http.conf file that I forget to add this configure.

#php5 support
LoadModule php5_module "E:/php-5.6.1/php5apache2_4.dll"

AddType application/x-httpd-php .php
AddType application/x-httpd-php .html

# configure the path to php.ini
PHPIniDir "E:/php-5.6.1"

This is the stupid question I issue.

**Comment by ibrasho** [comment]
Close this please?
