### ISSUE TITLE
Routes display a blank page after set a resource with the same controller before

### ISSUE THREAD

**Issue by RomainLanz** [laravel/framework#6937]
Hi everyone,

According that we have a resource `users` in our routes file:
````php
Route::resource('users', 'UsersController');
````

If we set another routes related to the user resource and use same method on it like that:
````php
Route::get('users/edit', [
    'as' => 'users.self.edit',
    'uses' => 'UsersController@edit'
]);

Route::post('users/edit', [
    'as' => 'users.self.update',
    'uses' => 'UsersController@update'
]);
````

It's doen't work and display a blank page if these new routes is write after our resource.
But if I write these routes before all things work fine.

````php
Route::get('users/edit', [
    'as' => 'users.self.edit',
    'uses' => 'UsersController@edit'
]);

Route::post('users/edit', [
    'as' => 'users.self.update',
    'uses' => 'UsersController@update'
]);
    
Route::resource('users', 'UsersController');
````

**Comment by RomainLanz** [comment]
Why it would be the intended behaviour? Btw I can't sort properly my routes file.

**Comment by stevebauman** [comment]
I believe this is intended behavior as well. In my experience if I ever needed to add extra routes to the same controller attached to a `Route::resource`, I've had to register them before I've registered the `Route::resource`. Unfortunately I'm not sure why, but I can't dive into the code ATM

**Comment by vishalsirka** [comment]
Route::resource('/trainer','TrainerController');

i have same problem here.

**Comment by smarthashmi** [comment]
> Route::resource('/trainer','TrainerController');
> 
> i have same problem here.

did you solved the issue coz i am facing also the same issue
