### ISSUE TITLE
[Proposal] [5.0] Route group naming (as)

### ISSUE THREAD

**Issue by iWader** [laravel/framework#6939]
It would be good to be able to name groups of routes, similar to how the prefix works. Not sure if this is an existing thing in L4, but L5 seems to throw an error when attempting this currently.

I'm happy to create a PR either way, if it needs fixing or implementing (if the proposal is accepted).

```
Route::group(['as' => 'admin'], function() {
    Route::get('/home', ['as' => 'index']);

    Route::group(['as' => 'foo'], function()
    {
        Route::get('/test', ['as' => 'bar']);
    }
});
```

This would produce the /home route named admin.index and /test as admin.foo.bar

**Comment by crynobone** [comment]
Similar to #3000 proposal

**Comment by GrahamCampbell** [comment]
Closing this duplicate.
