### ISSUE TITLE
Auth::attempt() and Redirect::intended() has issues

### ISSUE THREAD

**Issue by tonglil** [laravel/framework#6942]
1. Starting on `/`
2. Go to `/login` to enter the form
3. Press submit

```
            if (Auth::attempt($credentials, $remember)) {
                Log::info('Is logged in.');
                return Redirect::intended('/');
            } else {
                return Redirect::to('/login');
            }
```

After successfully entering the credentials (log tells me so), `Redirect::intended()` thinks the user is not logged in and redirects them to `/logout` and logs them out.

If I start on any other page, then the log in works and the user gets redirected to the intended page.

I know this because when I insert a `Log::info($redirect)` [here](https://github.com/illuminate/routing/blob/4.2/Redirector.php#L186) it logs [this](https://gist.github.com/tonglil/3e33c2844fdb12158a6b).

I am trying to understand where it go the `logout` route from. I grepped my folder and only 2 instances of the text came inside the logout method in the routes, which when the route was disabled, I get a 404 during the redirection.

**Comment by tonglil** [comment]
Routes file (relevant routes):
```
// Auth
Route::group([
], function() {
    Route::get('/login', 'AuthController@show');
    Route::any('/logout', 'AuthController@logout'); // comment this out and get 404 in above redirection
    Route::get('/password/forgot', 'AuthController@forgot');
    Route::get('/password/reset/{token?}', 'AuthController@reset');

    Route::group([
        'before' => ['csrf'],
    ], function() {
        Route::post('/login', 'AuthController@login');
        Route::post('/password/forgot', 'AuthController@send');
        Route::post('/password/reset', 'AuthController@update');
    });
});
```

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by tonglil** [comment]
`Laravel Framework version 4.2.16`

**Comment by tonglil** [comment]
I figured out what is happening and I think it might be a bug with Laravel.

Relevant controller method:

    // Log out route
    public function logout()
    {
        Auth::logout();

        return Redirect::to('/');
    }

I think because going to `http://site.com/logout` redirects the user somewhere after logging them out, Laravel sets the session `url` key to: `array:1 [ "intended" => "https://site.com/logout" ]` because of the redirection. Now when the user tries to log in again, because the (falsely) "intended" route is saved as the logout url, it kicks them back out thanks to `return Redirect::intended('/');`

Current workaround is to manually forget the session 'url' key (which is not always desired): `Session::forget('url');`

**Comment by tonglil** [comment]
Actually the issue stems from the `Redirect::guest()` which preserves the intended url.

The solution is to use `Redirect::to()`.
