### ISSUE TITLE
Request::query() and Request::header() does not return string

### ISSUE THREAD

**Issue by ddeath** [laravel/framework#6943]
Request::query() and Request::header() does not return string as is written in documentation. Instead it return array or something...

confusing doc:
http://laravel.com/api/4.2/Illuminate/Http/Request.html#method_header
http://laravel.com/api/4.2/Illuminate/Http/Request.html#method_query

If I want to get strings I need to write:

    $headers = Request::instance()->headers;
    $query = Request::instance()->getQueryString();
    $request_content = Request::instance()->getContent();

from symphony:
http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Request.html

**Comment by ibrasho** [comment]
Could you please show us where does it say, in the docs, that the `Request::header()` and `Request::query()` functions return a string?

**Comment by ddeath** [comment]
Hi there,
sorry my fault, I forgot include link. Here it is:

http://laravel.com/api/4.2/Illuminate/Http/Request.html#method_header

**Comment by GrahamCampbell** [comment]
Yeh, we only return a string if you provide a key. Feel free to send a pull to update the docs.
