### ISSUE TITLE
Error with Redirect::back()->withInput() when using Form (Arrays?)

### ISSUE THREAD

**Issue by dnetix** [laravel/framework#6944]
I have a form that contains multiple inputs that resolves as an array when posted let's say:

&lt;input type="text" name="article[]" .../&gt;
&lt;input type="text" name="article[]" .../&gt;
&lt;input type="text" name="article[]" .../&gt;

I can use in the controller an Input::get("article") and it transforms to an array. But if there is a problem with the Validation I'm redirecting back withInput() but it throws the exception of the capture.

![errorlaravel](https://cloud.githubusercontent.com/assets/4644865/5659324/6a3402a4-96de-11e4-82d9-ed696c88014f.png)

**Comment by GrahamCampbell** [comment]
The form component is no longer maintained, or supported. Also, I recognise this issue. Perhaps try searching the closed issues - this has definitely come up before.
