### ISSUE TITLE
[4.2] Optimize command shouldn't optimize class loader in debug mode

### ISSUE THREAD

**Issue by mattzuba** [laravel/framework#6948]
This is more of a feature request than a bug.  It would be great if the optimize command did not run `$this->composer->dumpOptimized();` when in debug, favoring `$this->composer->dumpAutoloads();` when in debug mode OR option('psr') is present.

As it currently is, it can cause a false sense of proper PSR-4/0 and Namespaced classes because if the namespace and folder structure don't match as they should, the optimized classloader is forgiving.

Short case - I moved a class to a different folder but forgot to change the namespace.  I also happened to run a `composer update` before running my app again, which generated an optimized class loader and my mistake in forgetting to rename the namespace until I happen to notice it.

**Comment by ibrasho** [comment]
Most likely no BC-breaking changes will ever happen in the 4.2 branch.

**Comment by mattzuba** [comment]
Not sure I really see this as a breaking change or backwards incompatible change.  If namespaces and psr autoloading is probably used, you'd never notice a difference.  If you don't use them properly, then the problem isn't a Laravel, one, but a developer one.

**Comment by GrahamCampbell** [comment]
Please don't send a proposal for such a small change. Send a pull to **5.0**, and Taylor will review it. This can't go into 4.2, sorry.
