### ISSUE TITLE
[L5.0] Where have package migrations gone?

### ISSUE THREAD

**Issue by andrewmclagan** [laravel/framework#6949]
**How does one run migrations for a package in L5?**

If you look at `Illuminate\Database\Console\Migrations\MigrateCommand` and specifically the `getOptions()` method you will notice that both the **package** and **bench** commands have been removed in L5. Although there is still a class property for `$packagePath` that is not being used.

Im guessing there are plans afoot to change how this works, currently in progress? or am I missing something?

**Comment by GrahamCampbell** [comment]
They don't exist anymore. You must write your own custom commands now.

**Comment by RomainLanz** [comment]
So every developper need to write a command to publish configuration and migrations files?

**Comment by andrewmclagan** [comment]
...hardcore.

**Comment by RomainLanz** [comment]
We have a global command like php artisan publish:package [package-name] and we need to write the behaviour of that or nothing?

**Comment by andrewmclagan** [comment]
I get the feeling everyone is going to re-impliment `Illuminate\Database\Console\Migrations\MigrateCommand`

**Comment by ibrasho** [comment]
Someone should make this a package...

**Comment by GrahamCampbell** [comment]
The idea is you generate migration files for the user to include in their app and modify if they want. Ultimately, we now have maximum flexibility.

**Comment by andrewmclagan** [comment]
Hmm.... now that is really great. In the beggining I thought "great more code tying my "agnostic" packages into Laravel. The more I think about it, this lends itself to awesome agnostic abilities (alliteration?).
