### ISSUE TITLE
ErrorException in BelongsToMany.php line 177

### ISSUE THREAD

**Issue by AndrewOverlord** [laravel/framework#6951]
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::hydratePivotRelation() must be of the type array, object given, called in ...\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php on line 158 and defined.
until today everything was fine
class Product extends Model {
	//...
	public function children()
	{
		return $this->belongsToMany('App\Product', 'pivot_table', 'parent_id', 'product_id');
	}
}

**Comment by RomainLanz** [comment]
You think that without a piece of code we can know what is wrong?

**Comment by ibrasho** [comment]
I think one of the latest commits broke this.

**Comment by ibrasho** [comment]
https://github.com/laravel/framework/issues/6952
