### ISSUE TITLE
Add code coverage badge?

### ISSUE THREAD

**Issue by montogeek** [laravel/framework#6955]
It is possible to add a code coverage badge?
It is helpful to see and will allow to new commiters to add some tests or look what code does not have tests.

**Comment by GrahamCampbell** [comment]
This was alreasy rejected. Sorry.

**Comment by montogeek** [comment]
Ok

**Comment by harikt** [comment]
I was looking why and found answer by @taylorotwell  here #3406 . But I feel it is good to keep code coverage, so when a bug happens everyone will try and write a test rather than https://github.com/laravel/framework/issues/5300#issuecomment-68179950 .

**Comment by crynobone** [comment]
Having code coverage alone can't assure that problem like #5300 can be avoided. It only state that those part of the code is covered by a test case but might be not even related to #5300

**Comment by harikt** [comment]
@crynobone coverage badge gives people an awareness to write a test code. I am not thinking coverage is bad idea , and yes I do agree it is not fully correct. But still .. :-) .

Anyway if people don't like don't need. I said what I thought.

Thank you.

**Comment by GrahamCampbell** [comment]
People can run coverage checks on their own machine.
