### ISSUE TITLE
Better URL::route function

### ISSUE THREAD

**Issue by peterkinnaird** [laravel/framework#6959]
It would be really convenient to be able to pass an argument to get https back instead of http and others to add http authentication parameters for http basic/digest.

**Comment by GrahamCampbell** [comment]
:+1: We should use what's provided in the config rather than just overriding it IMO.

**Comment by peterkinnaird** [comment]
:+1: totally agreed, but a smaller change would probably be to simply include optional parameters.

**Comment by peterkinnaird** [comment]
I was also surprised that  `URL::secure` didn't generate a proper  secure URL when passed a named route.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.
