### ISSUE TITLE
Packages in laravel 5

### ISSUE THREAD

**Issue by iillexial** [laravel/framework#6965]
How and where to now create packages in Laravel 5? Workbench has been deleted. or creating packages now is not a good practice?

**Comment by joecohens** [comment]
Like @taylorotwell said on the Q&A the idea is to have a separate tool to help on package creation. It's not been developed at the moment.

**Comment by GrahamCampbell** [comment]
This is a duplicate issue. You can still register view namespaces in L5, and in terms of config, you're going to want to just manually set the config in your service provider.
