### ISSUE TITLE
HandleError Operator &?

### ISSUE THREAD

**Issue by EliuFlorez** [laravel/framework#6970]
it is an error or not. encounter the same error in 4.2 and L5
Illuminate\Exception\Handler.php - linea: 132

if (error_reporting() & $level)
{
	throw new ErrorException($message, 0, $level, $file, $line);
}

should probably be

if (error_reporting() && $level)
{
	throw new ErrorException($message, 0, $level, $file, $line);
}

**Comment by GrahamCampbell** [comment]
No, it shouldn't.
