### ISSUE TITLE
[4.0.10] Eloquent bug in querying float values

### ISSUE THREAD

**Issue by envision** [laravel/framework#6980]
Our provider upgraded to PHP 5.4.36 and this problem arrived: When eloquent fetches float numbers from MySQL for example 333.33, it returns 330 - all float values are rounded in tens!

This appeared with some early Laravel 4.0 but I just upgraded to 4.0.10 and problem persists.

**Comment by GrahamCampbell** [comment]
Only Laravel 4.2.16 is supported. All other versions are unsupported. Sorry.

**Comment by envision** [comment]
I just upgraded to 4.2.16 and the problem persists! How can I debug this?

**Comment by GrahamCampbell** [comment]
Probably ask on the forums. This doesn't look like a bug with laravel itself.

**Comment by envision** [comment]
I just verified that connecting MySQL and querying with plain PHP gets the floats right...

**Comment by envision** [comment]
Started a thread on this: http://laravel.io/forum/01-12-2015-eloquent-returns-floats-as-integers-rounded-in-tens

**Comment by envision** [comment]
@GrahamCampbell this must be an Eloquent issue! Or an compatibility issue with certain PHP + MySQL version combo, but with Eloquent still.

How else this can output 333.33 :

    $result = mysql_query("SELECT someval FROM sometable WHERE id = 8");
    WHILE ($row = mysql_fetch_array($result)) {
        echo $row{'someval'};
    }

...when this outputs 330 and gettype() returns "double":

    return Sometable::where('id', 8)->pluck('someval');

**Comment by shaggyz** [comment]
Described problem persist on 4.2.17. MySql 5.6.21 PHP 5.5.17.

**Comment by GrahamCampbell** [comment]
4.x is not supported

**Comment by JavierMartinz** [comment]
I had the same problem with PHP 5.6.1 and it's working now with 5.6.7

**Comment by aparticka** [comment]
This issue popped up for me when using Laravel 5.0.27. It has nothing to do with Laravel, but rather with how floating point values are stored in MySQL and how PDO returns the value. This is fixed by using a `DECIMAL` type instead.

**Comment by 0x1ad2** [comment]
@aparticka thanks for the explanation! I'm running  4.2.17 and have the same issue. Is there something we could do besides changing the type to fix this problem?
