### ISSUE TITLE
Eloquent Relation doesn't work well with object_get()

### ISSUE THREAD

**Issue by dbpolito** [laravel/framework#6988]
If i have HasOne relations and try to get it using object_get(), and the relations aren't being hydrated, it simply doesn't work:

User -> HasOne -> Person
Person -> HasOne -> Address

If i do this:

````php
$user = User::find(1);
echo object_get($user, 'user.person.address.street'); // doesn't work
echo $user->person->address->street; // work
echo object_get($user, 'user.person.address.street'); // now it work because the relations was hydrated by the model calls
````

This can be fixed by a few approaches:

1) Make Eloquent Model __isset look relations, we can make use of getAttribute instead of getAttributeValue at:

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Model.php#L3078

2) We can create a new helper function, that also does the magic call, this is what i'm using for now:

````php
if ( ! function_exists('eloquent_get'))
{
	/**
	 * Get an item from an object using "dot" notation.
	 *
	 * @param  object  $object
	 * @param  string  $key
	 * @param  mixed   $default
	 * @return mixed
	 */
	function eloquent_get($object, $key, $default = null)
	{
		if (is_null($key) || trim($key) == '') return $object;
		foreach (explode('.', $key) as $segment)
		{
			if ( ! is_object($object) || ! (isset($object->{$segment}) || $object->{$segment}))
			{
				return value($default);
			}
			$object = $object->{$segment};
		}
		return $object;
	}
}
````

Let me know your thoughts, i haven't opened a PR for this because i wanted to get feedback about the best approach, as soon as i get it, i will open a PR.

**Comment by ibrasho** [comment]
Interesting.

Another suggestion is update `data_get()` and `object_get()` to do this check we passed a class that extends `Eloquent\Model`.

**Comment by GrahamCampbell** [comment]
This has been proposed already and was rejected because it was too hacky.

**Comment by dbpolito** [comment]
I don't think the first approach isn't hacky at all, is it expected to have an relation and at isset() call of this property relation return false because of the eager loading?

````php
$user = User::find(1);
var_dump(isset($user->address));; // return FALSE
var_dump($user->address);; // return relation object
var_dump(isset($user->address));; // return TRUE
````

Is this expected?

The first approach is the appropriate fix or is there a reason for not use getAttribute there?

**Comment by GrahamCampbell** [comment]
I was referring to the changes to the object_get array_get functions.

**Comment by dbpolito** [comment]
Cool, the main purpose of my ticket is showing the issue and get feedback about the approach and see if someone else has any better approach, if this is still an issue, why this is closed?

**Comment by GrahamCampbell** [comment]
Because it's a duplicate.

**Comment by bigjoevtrj** [comment]
+1 this code can be hacky but works as expected...
