### ISSUE TITLE
Illuminate\Database\Eloquent\Builder::whereHas() malfunctioning inside a ScopeInterface

### ISSUE THREAD

**Issue by kfuchs** [laravel/framework#6997]
This is a very similar story to issue #6116 

If you try to create a `whereHas` query inside a global scope it will loop infinitely till eventually giving you an out of memory error.

```php
    public function apply(Builder $builder)
    {
        $builder->whereHas('flags', function($q) use ($user)
        {
            $q->whereReporterId($user->id);
        });
    }
...
```

Basically it will get to line 607 in the [Eloquent/Builder.php](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Builder.php#L607) and that will cause it continuously create new queries.

I do not have a fix yet, does anyone else? :)

**Comment by GrahamCampbell** [comment]
This has actually been fixed already.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/63383c3e2b07deec1b15e521ad0c80e09b1983a2

**Comment by GrahamCampbell** [comment]
It'll be available in 4.2.17 once it's tagged.

**Comment by kfuchs** [comment]
@GrahamCampbell That actually doesn't fix the issue for closures with `whereHas`. It only fixes it for closures using `where`.

**Comment by GrahamCampbell** [comment]
:(

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell, @maddes.

**Comment by kfuchs** [comment]
K tracked it down...

The loop starts to occur in the [Illuminate/Database/Eloquent/Relations/Relation::wrap()](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Relations/Relation.php#L269) method.

It calls `$this->parent->getQuery()` which is handled by the [Illuminate/Database/Eloquent/Model::__call()](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Model.php#L3107)  magic method which calls the `$this->newQuery()` method causing the query scope to again be applied, which leads back to the relation again which again creates the new query on the parent and applies the query scope, and so on and so forth...

Hope that makes sense.

**Comment by mtvs** [comment]
I have the same issue [here](http://stackoverflow.com/questions/28244218/laravel-global-query-scope-throws-max-function-nesting-level-reached)

**Comment by GrahamCampbell** [comment]
This sounds like something that's been fixed already.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/6551
https://github.com/laravel/framework/pull/6862
https://github.com/laravel/framework/pull/7079

**Comment by GrahamCampbell** [comment]
Yeh, #6862 already fixed this...

**Comment by maddes** [comment]
I'll try and give this a spin next Sunday…

**Comment by GrahamCampbell** [comment]
I think this is fixed in 4.2.17, and 5.0.4+

**Comment by maddes** [comment]
Awesome!

**Comment by GrahamCampbell** [comment]
It would be cool if you can confirm it's working @maddes. Let me know if it's not, and I'll re-open this. :)

**Comment by mtvs** [comment]
[In my case](http://stackoverflow.com/questions/28244218/laravel-global-query-scope-throws-max-function-nesting-level-reached) it works, thanks
