### ISSUE TITLE
[4.2] data_get issue with collections

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#7002]
## To replicate

```php
$fruits = ['apples', 'pears', 'strawberry'];
$fruitsCollection = new \Illuminate\Support\Collection($fruits);;
dd(data_get($fruitsCollection, '0'), data_get($fruits, '0'));
```

## Result

```
// Outputs:
null
string `apples` (length=6)
```

## Expected result:

```
string `apples` (length=6)
string `apples` (length=6)
```

**Comment by garygreen** [comment]
Interestingly enough this is fixed in Laravel 5 due to improvements for the `data_get` method to support collections by checking for an instanceof `ArrayAccess`.

**Comment by GrahamCampbell** [comment]
Sorry, no.

**Comment by garygreen** [comment]
@GrahamCampbell any reason in particular? Would it break anything or just improve support (imo)?

**Comment by GrahamCampbell** [comment]
It was a change in behaviour. Taylor already took the decision to put it into 5.0. 4.2 is actually feature locked now, or will be shortly.

**Comment by GrahamCampbell** [comment]
Once the PSR-2 stuff goes through into 5.0, laravel 4.2 will be locked for all but higher priority bug fixes.

**Comment by garygreen** [comment]
Fair enough, thanks for explanation. For those who stumble across this thread with the same issue -- you can override Laravel's `data_get` by:

1. Add the following to code towards the top of your `bootstrap/autoload.php` after `define('LARAVEL_START', microtime(true));`:

```php
+// Register helpers so we can override any Laravel ones if needs be.
 	6
+require __DIR__ .  '/helpers.php';
```
2. Create a `helpers.php` in the root of your app (or wherever you would prefer, just change the above)
3. Copy the `data_get` code from Laravel 5, found in: src/Illuminate/Support/helpers.php

Once your app boots up, your one will override the default one in 4.2. Another good reason to do this is once issue illuminate/html#16 gets pulled (hopefully) model form binding with collections will work. Yippeee! :-)
