### ISSUE TITLE
illuminate/console: Conflict with Composer requirements

### ISSUE THREAD

**Issue by marcovtwout** [laravel/framework#7004]
I have these two conflicting packages in my composer.json:

    "apigen/apigen": "~4.0",
    "anahkiasen/rocketeer": "~2.0"

Running `composer update` results in a conflict for requirement symfony/console:

    - apigen/apigen v4.0.0 requires symfony/console ~2.6 -> satisfiable by symfony/console[v2.6.3, v2.6.0, v2.6.1, v2.6.2].
    - Can only install one of: symfony/console[v2.6.0, v2.5.0].
    - Can only install one of: symfony/console[v2.6.1, v2.5.0].
    - illuminate/console v4.2.1 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].

How can I solve this problem? Could you update the release for`illuminate/console` to 2.6?
(also see https://github.com/rocketeers/rocketeer/issues/401#issuecomment-69936934)

**Comment by GrahamCampbell** [comment]
rocketeer is not designed to be installed with anything else. This doesn't work because rocketeer is asking for only symfony console 2.6 or 2.7, but laravel 4.2 only allows you to use 2.5.

**Comment by Anahkiasen** [comment]
No what happens is I'l requiring illuminate/console 4.2 which requires symfony/console 2.5, while apigen uses symfony/console 2.6

**Comment by GrahamCampbell** [comment]
@Anahkiasen Yeh, thats what I said.

**Comment by GrahamCampbell** [comment]
Ish. The dependency conflicts are the same.

**Comment by marcovtwout** [comment]
Doesn't Symfony follow symantic versioning? If it does, the requirement for `symfony/console` should read (at least) ~2.5, but not 2.5.*.

**Comment by barryvdh** [comment]
Agreed. In theory all Laravel components could use semver constraints, preferably with the actual constraint they need, not just what's the latest version..

**Comment by GrahamCampbell** [comment]
@marcovtwout, @barryvdh Yeh, I already talked to Taylor about doing this in L5, but he doesn't like the idea.

**Comment by marcovtwout** [comment]
Can you link to that discussion? Why doesn't he like it?

**Comment by GrahamCampbell** [comment]
> Can you link to that discussion?

Sorry, I can't. It was on skype...

> Why doesn't he like it?

Taylor likes the idea that each laravel version is locked to a symfony version so that people can reliably know that a certain symfony component. I also pointed out that symfony 2.7 is a bit of a mess at the moment with the depreciation warnings all over the place.

I also said on the racketeer issue:

> I agree this is a bit of a bummer. I want laravel 5 to use ~2.3 and ~2.5` for the various symfony components but Taylor doesn't agree with me. What do you two think about that change?

**Comment by barryvdh** [comment]
Okay I don't know about Symfony 2.7 deprecations, it seems the discussion is still going on about that.
But shouldn't the tests make sure that it works on all versions? http://symfony.com/blog/testing-minimal-versions-of-symfony-requirements

**Comment by Anahkiasen** [comment]
I made a PR a while back to add `--prefer-lowest` to the build matrix but I don't think it was ready yet

**Comment by barryvdh** [comment]
But with fixed Symfony versions, wouldn't help much ;)

I do understand the reasoning for the framework, but for components it's a bit harder to re-use between projects with these constraints..

**Comment by franzliedke** [comment]
How about specifying different constraints for the components vs. the framework then?

**Comment by GrahamCampbell** [comment]
> I do understand the reasoning for the framework, but for components it's a bit harder to re-use between projects with these constraints..

Yeh, I agree.
