### ISSUE TITLE
MIGRATION: $table->timestamp('when'); or $table->timestamps() fail when using sql_mode=TRADITIONL

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel/framework#7007]
when running either
$table->timestamps(); or
$table->timestamp('created_at');
on a migration, with sql_mode=TRADITIONAL I get a :

 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `subscriber` (`id` int unsigned not null auto_increment primary key, `email` varchar(255) not null, `weekly_digest` char(1) not null, `source` varchar(255) null, `created_at` timestamp default 0 not null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'

![screen shot 2015-01-14 at 20 59 21](https://cloud.githubusercontent.com/assets/450069/5747476/4410e98c-9c30-11e4-9d3a-2dc378ef88b4.png)
![screen shot 2015-01-14 at 20 59 05](https://cloud.githubusercontent.com/assets/450069/5747478/441988a8-9c30-11e4-9924-b9ad6564b782.png)
![screen shot 2015-01-14 at 20 58 52](https://cloud.githubusercontent.com/assets/450069/5747477/44185302-9c30-11e4-9e8e-cfaae0f1d57e.png)

**Comment by mathiasgrimm** [comment]
the magic happens on namespace 

Illuminate\Database\Schema\Grammars;
class MySqlGrammar extends Grammar {

![screen shot 2015-01-14 at 21 02 46](https://cloud.githubusercontent.com/assets/450069/5747549/b8cf41b0-9c30-11e4-8ef0-3b59618baff6.png)

**Comment by mathiasgrimm** [comment]
I don't understand why the not null timestamps are being defining with a default value 
'timestamp default 0'

if the column is not null, shouldn't have any default... the user (programmer) should provide the values or a default value only/when required. None of the other types have default value by default, just this 'typeTimestamp'

**Comment by mathiasgrimm** [comment]
created a patch for it, however, many tests fail. All of them related to generated sql...

diff --git a/src/Illuminate/Database/Schema/Blueprint.php b/src/Illuminate/Database/Schema/Blueprint.php
index cb3de29..a8da812 100755
--- a/src/Illuminate/Database/Schema/Blueprint.php
+++ b/src/Illuminate/Database/Schema/Blueprint.php
@@ -633,7 +633,7 @@ class Blueprint {
        {
                $this->timestamp('created_at');

-               $this->timestamp('updated_at');
+               $this->timestamp('updated_at')->nullable();
        }

        /**
diff --git a/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php b/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php
index 90210ab..2a0908e 100755
--- a/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php
+++ b/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php
@@ -479,7 +479,7 @@ class MySqlGrammar extends Grammar {
         */
        protected function typeTimestamp(Fluent $column)
        {
-               if ( ! $column->nullable) return 'timestamp default 0';
+//             if ( ! $column->nullable) return 'timestamp default 0';

                return 'timestamp';
        }


i think default 0 is not a good idea because it will introduce invalid dates like 0000-00-00 00:00:00 (which i particularly hate)
and there is no need for the column update_at be not null, in term of semantics, it makes no sense. If the row was first inserted is was never updated...

**Comment by creocoder** [comment]
Currently framework just unusable with MySQL. I did not know any man who work without TRADITIONAL sql mode. I wonder how such a **critical** error goes to Laravel 5 release.

**Comment by mathiasgrimm** [comment]
For now im using just raw statements for the migrations

DB::statement("...")

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

---
Disclaimer: this is not me accepting this idea. Only Taylor has the power to do this.

**Comment by Kaushik-19** [comment]
The best way i do to tackle this error of SQL is by adding this line "mysql => [ 'strict'    => true, ]"to my database.php

**Comment by sampablokuper** [comment]
Why was this issue closed? It doesn't appear to have been fixed.
