### ISSUE TITLE
Multidimensional custom validation attributes breaks artisan db:seed

### ISSUE THREAD

**Issue by ryanengland** [laravel/framework#7009]
By default the code block for Custom Validation Attributes in /app/lang/XX/validation.php is a blank array:

	/*
	|--------------------------------------------------------------------------
	| Custom Validation Attributes
	|--------------------------------------------------------------------------
	|
	| The following language lines are used to swap attribute place-holders
	| with something more reader friendly such as E-Mail Address instead
	| of "email". This simply helps us make messages a little cleaner.
	|
	*/
	
	'attributes' => array(),

Changing this to a single array works correctly, and allows the command "" to execute correctly:

	/*
	|--------------------------------------------------------------------------
	| Custom Validation Attributes
	|--------------------------------------------------------------------------
	|
	| The following language lines are used to swap attribute place-holders
	| with something more reader friendly such as E-Mail Address instead
	| of "email". This simply helps us make messages a little cleaner.
	|
	*/
	
	'attributes' => array(
		'company'		=> 'Company Name',
	),

However, changing this to a multidimensional array, in order to follow fields named such as name[title] or name[first] does not. Code such as below:

	/*
	|--------------------------------------------------------------------------
	| Custom Validation Attributes
	|--------------------------------------------------------------------------
	|
	| The following language lines are used to swap attribute place-holders
	| with something more reader friendly such as E-Mail Address instead
	| of "email". This simply helps us make messages a little cleaner.
	|
	*/
	
	'attributes' => array(
		'company'		=> 'Company Name',
		'name'			=> array(
			'title' => 'Title',
			'first' => 'First Name',
			'last' => 'Last Name',
		),
	),

This yields correct attribute names in validation - i.e "The First Name field is required". However the above code block subsequently breaks the command "php artisan db:seed --force" with error:

	[ErrorException]
	Array to string conversion 

Doing a further seed with the -vvv option yields the following:

php artisan db:seed -vvv
	                              
	  [ErrorException]            
	  Array to string conversion  

	Exception trace:
	 () at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1580
	 Illuminate\Exception\Handler->handleError() at n/a:n/a
	 str_replace() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1580
	 Illuminate\Validation\Validator->doReplacements() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:459
	 Illuminate\Validation\Validator->addError() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:442
	 Illuminate\Validation\Validator->addFailure() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:314
	 Illuminate\Validation\Validator->validate() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:273
	 Illuminate\Validation\Validator->passes() at /Site/laravel/vendor/laravelbook/ardent/src/LaravelBook/Ardent/Ardent.php:529
	 LaravelBook\Ardent\Ardent->validate() at /Site/laravel/vendor/laravelbook/ardent/src/LaravelBook/Ardent/Ardent.php:584
	 LaravelBook\Ardent\Ardent->internalSave() at /Site/laravel/vendor/laravelbook/ardent/src/LaravelBook/Ardent/Ardent.php:611
	 LaravelBook\Ardent\Ardent->save() at /Site/laravel/app/database/seeds/AccountsUsersSeeder.php:103
	 AccountsUsersSeeder->run() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:37
	 Illuminate\Database\Seeder->call() at /Site/laravel/app/database/seeds/DatabaseSeeder.php:17
	 DatabaseSeeder->run() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/SeedCommand.php:57
	 Illuminate\Database\Console\SeedCommand->fire() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:112
	 Illuminate\Console\Command->execute() at /Site/laravel/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
	 Symfony\Component\Console\Command\Command->run() at /Site/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
	 Illuminate\Console\Command->run() at /Site/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php:889
	 Symfony\Component\Console\Application->doRunCommand() at /Site/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php:193
	 Symfony\Component\Console\Application->doRun() at /Site/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php:124
	 Symfony\Component\Console\Application->run() at /Site/laravel/artisan:59

	db:seed [--class[="..."]] [--database[="..."]] [--force]

Thanks for any assistance.

**Comment by GrahamCampbell** [comment]
That's the expected behaviour.

**Comment by ryanengland** [comment]
Is there any way round this? How can custom attributes be set for name.title fields, for example?

Cheers!

**Comment by rained23** [comment]
I am looking for solution for this too.

**Comment by hermanbanken** [comment]
@GrahamCampbell How can this be expected behaviour? Just closing this is not really helpful. 

I'm having an "Array to string conversion" issue, but for me it's in [MessageBag.php](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/MessageBag.php#L183) where probably `$format` is an array. However, I'm completely clueless where this is coming from. Probably has something to do with the Custom Validation Language Lines, as that's where I'm having multi-dimensional array's. 

The weird thing is that I'm not able to reproduce this error a client is having, and the error only lists some Array, not it's contents. I can successfully get all those Custom Validation Language Lines on my screen...

**Comment by canfiax** [comment]
I would like to know more about this. I cannot seem to find a way to properly define custom validation messages for specific attributes, like company.name.

My current approach:


	/*
	|--------------------------------------------------------------------------
	| Custom Validation Attributes
	|--------------------------------------------------------------------------
	|
	| The following language lines are used to swap attribute place-holders
	| with something more reader friendly such as E-Mail Address instead
	| of "email". This simply helps us make messages a little cleaner.
	|
	*/

	'attributes' => [
		'meta.hourly_rate' => 'hourly rate'
	],

It does not work. In my validation, this is how I specify:

    public function rules(Guard $auth) {
        return [
            'firstname' => 'min:2|max:255',
            'lastname' => 'min:2|max:255',
            'meta.hourly_rate' => 'integer'
        ];
    }

**Comment by canfiax** [comment]
Whoops. Tried this, and it works:

	'attributes' => [
		'meta' => ['hourly_rate' => 'hourly rate']
	],
