### ISSUE TITLE
[Proposal] Add possibility to override dot separator symbol in Arr helper

### ISSUE THREAD

**Issue by velosipedist** [laravel/framework#7010]
For now, '.' is hardcoded as separator in flatten/get etc. helper methods.

I suppose to move dot into protected static member to unlock extending possibility like

```php
class MyArrImplementation{
  protected static $dotSeparator  = '/';
  // any extra functionality if needed, self::get('foo/bar') is already works
}
```

I don't see any serious performance impact. Only errors possible on inherited class if author will change static separator on-the-fly, but it would be just his own problem.

For now i cannot use Illuminate/Support to extending and have to add Underscore library just for only that purpose.

**Comment by RomainLanz** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I can't see this happening. I suggest just rolling your own solution if you want this.
