### ISSUE TITLE
AuthenticatesAndRegistersUsers trait uses a hard coded route for redirect

### ISSUE THREAD

**Issue by thaisonle** [laravel/framework#7011]
If a authentication attempt fails, this bit of code is run which references a hard coded route '/auth/login'. This should be refactored to allow custom routes similar to the redirectPath() implementation.

```
return redirect('/auth/login')
		->withInput($request->only('email'))
		->withErrors([
			'email' => 'These credentials do not match our records.',
		]);
```

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/commit/7132cf233204dda7f8dfa3635901e1d7c260768e
