### ISSUE TITLE
[5.0] Route Cache cannot find routes

### ISSUE THREAD

**Issue by 0xMatt** [laravel/framework#7013]
I'm unsure as to why my routes file isn't able to be cached. I'm able to generate a full list with `route:list` but when I try to cache them it says I don't have any routes to be cached. The routes file is indeed loaded in the map() method of the RouteServiceProvider which I load immediately after all the framework provider. 

Here is a SS ![Screenhot](http://i.imgur.com/Q4fzE7D.png)

Any ideas on what might be going on? I've dumped the autoloader, services.json and cleared what I've needed to.

**Comment by GrahamCampbell** [comment]
Where are you registering your routes?

**Comment by 0xMatt** [comment]
The issue is on my end. I was requiring my routes file with `require_once` and since the `route:cache` boots another console kernel instance the file was still flagged as included by the interpreter thus left out I'm presuming. Closed.

**Comment by GrahamCampbell** [comment]
Glad you sorted it. :)
