### ISSUE TITLE
[5.0] [Proposal] Use IoC in Eloquent relationships

### ISSUE THREAD

**Issue by neomerx** [laravel/framework#7023]
Reasons
1) More flexibility and all the benefits of IoC in relationship descriptions.
2) Models could be extended with new fields without necessity to change original model. New fields could be added in children classes with IoC binding overridden.

Required fix
Change statements like
~~~
$instance = new $related;
~~~
to IoC in Model::BelongsTo, Model::morphTo and etc.

Or make it easily to override with replacing to something like
~~~
protected function createInstance($inctanceClass)
{
    return new $inctanceClass;
}
~~~

**Comment by memtoko** [comment]
How it could be done? The eloquent model is abstract class. Do you want them injected as static? 
The current implementations is fine.

**Comment by neomerx** [comment]
@memtoko Within Eloquent relations concrete classes are created. The way it works now is 'new' operator hardcoded. For example in /Illuminate/Database/Eloquent/Model.php line 792.
I propose all such lines change with createInstance() and probably switch to IoC.

**Comment by ibrasho** [comment]
Benefits?

**Comment by Anahkiasen** [comment]
I think if your models have dependencies you went wrong somewhere in your app architecture

**Comment by neomerx** [comment]
@ibrasho @Anahkiasen That's not about model's dependencies the way you think.
Usage scenario is following. I have a set of models combined to package. As a user of such a package I'd like to change one of the models but (e.g. add new fields) but don't want to/cant change models directly. I'm inheriting the models and add new features. The problem is that other models from the package have relation to parent model but not mine. With IoC I can easily change this behavior and relations will create my new model.
Because 'new' operator hardcoded currently I have to override all relation methods which is 200+ lines duplicate code with Laravel. This only change will allow to override just single line of code.

**Comment by GrahamCampbell** [comment]
I think this has already been rejected before.

**Comment by neomerx** [comment]
@GrahamCampbell I tried to find similar issues before posting and it seems it's not duplicate.

**Comment by GrahamCampbell** [comment]
If it wasn't discussed on github, it was definitely discussed somewhere.

**Comment by JosephSilber** [comment]
Resolving it through IoC might be a little over the top, but `new`ing it up
in a separate method wouldn't be such a bad idea.

**Comment by neomerx** [comment]
@GrahamCampbell Anyway currently there are not much options to solve the problem without copypasting 200 lines of code. 
@JosephSilber That's why I'm proposing adding a method that could be overridden.

**Comment by GrahamCampbell** [comment]
I'll leave this open for Taylor to look at.

**Comment by neomerx** [comment]
@GrahamCampbell Have you forgotten about your promise to leave it for @taylorotwell? What is your recommended solution for substituting models in relations?

**Comment by GrahamCampbell** [comment]
We have a 2 week human timeout system.

**Comment by neomerx** [comment]
@GrahamCampbell  and as for the main question about models?

**Comment by GrahamCampbell** [comment]
Model's aren't meant to have dependencies. If you find yourself needing that, it's likely you're missing out on some design pattern.

**Comment by neomerx** [comment]
@GrahamCampbell you either don't understand the question or haven't checked Laravel documentation http://laravel.com/docs/5.0/eloquent#relationships

**Comment by GrahamCampbell** [comment]
I'm not quite sure what the question is. Maybe looking at some of my model relationships would help? https://github.com/StyleCI/StyleCI/tree/master/app/Models

**Comment by neomerx** [comment]
@GrahamCampbell In terms of the model you've proposed the question would be
 - If I inherit your User class (lets say it'd be MyUser) and add a field address : string
 - Repo::firstOrFail()->user how can I get MyUser instead of User?

if my original proposal was in place Repo class would use IoC to instantiate MyUser rather than hardcoded 'new' operator used inside Laravel relationships implementation.

**Comment by neomerx** [comment]
@GrahamCampbell I guess you're inside a paradigm that all models of the application are free to be changed which is not the case when application is using models from other packages.
Laravel gives brilliant tool called migrations to extend models on database level and PHP gives ability to extend model on source code level. However current implementation of relationships don't match these possibilities.

**Comment by GrahamCampbell** [comment]
Have a look at how sentry does it. They set static properties on the model at framework boot.

https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/Users/Eloquent/User.php

**Comment by GrahamCampbell** [comment]
https://github.com/cartalyst/sentry/blob/2.1/src/Cartalyst/Sentry/SentryServiceProvider.php#L126

**Comment by neomerx** [comment]
@GrahamCampbell Doing something similar to many classed might be an overkill :)
It would really nice to have simple way to modify how Laravel instantiate models in relations (e.g. overriding a method).

**Comment by GrahamCampbell** [comment]
That's never going to happen sorry. The current solutions are fine IMO.
