### ISSUE TITLE
[Proposal] Add functions toArrayAttributes() & toArrayRelations() to Collection class

### ISSUE THREAD

**Issue by mysteryos** [laravel/framework#7024]
**Model** class has both aforementioned functions `toArrayAttributes()` & `toArrayRelations()`, used in `toArray()`

My proposal is to add them in the **Collection** class, so that one can retrieve solely the attributes or relations of a model when needed.

It allows more control on what information, one can retrieve from a model in array format.

**Comment by cryode** [comment]
Those methods seem very specific to their use case. Putting them on the `Collection` class doesn't make sense, as collections are typically agnostic as to what they hold.

Do you have a particular example of where this would be useful?

**Comment by mysteryos** [comment]
Glad you asked.

I am currently using [the official PHP package for Elasticsearch](https://github.com/elasticsearch/elasticsearch-php), which only accepts source data in an array format. 

Therefore, my eloquent models are being converted to array using `toArray()` which are retrieving additional (unnecessary) information, before being saved through the elasticsearch API. Given that the elasticsearch settings are set to strict, any extra information, being absent on the schema, will throw an error.

This is one of the cases where `toArrayAttributes()` will be of much help.

So far, i've resolved the issue, by extending `\Illuminate\Database\Eloquent\Collection` and adding the functions, suggested above.

**Comment by cryode** [comment]
I can see how the extended Collection functionality would benefit your use case, but it doesn't seem like something that is worth putting into the framework. It is not a common scenario.

Restricting attributes that are loaded with `toArray()` can already be done on the Eloquent level, also. [More info here.](http://laravel.com/docs/5.0/eloquent#converting-to-arrays-or-json)

**Comment by mysteryos** [comment]
Indeed, i'll just go ahead and close this.
