### ISSUE TITLE
Eloquent virtual attribute is wrongly added to the update query. [L4]

### ISSUE THREAD

**Issue by otagi** [laravel/framework#7027]
I have an Eloquent / Ardent model with an 'opt-in' virtual attribute (a form checkbox that must be validated but not saved).

```
class Foobar extends \LaravelBook\Ardent\Ardent {
	protected $fillable = [..., 'optin'];
	protected $appends = ['optin'];
	public static $rules = ['optin'  => 'required'];
}
```

When the object is updated in the controller, MySQL complains that `optin` is not a column:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'optin' in 'field list' (SQL: update `foobar` set `updated_at` = 2015-01-16 16:03:46, `optin` = 1 where `id` = 14)
```

The virtual attribute, when declared in the `$appends` array, shouldn't be added to the query.

**Comment by dwightwatson** [comment]
Does the same issue occur when you extend Eloquent instead of Ardent? Could be an issue on their end.

**Comment by jarektkaczyk** [comment]
@otagi You got it wrong. `$appends` is not for virtual attributes literally. It's for appending mutated vaues to the `toArray`/`toJson` output of the model:
```
public function getOptinAttribute() { ... }
```

So it has nothing to do with not adding to the query, and it's on your head to handle it, with current Model setup.

**Comment by otagi** [comment]
You're both right. The issue is with Ardent rather than Eloquent. I should have tested it more thoroughly before posting. Sorry about the noise.

PS: In case someone reading this has the same problem: I fixed it by adding a 'purgeFilter' in the model's constructor.
