### ISSUE TITLE
Method [send] does not exist on view.

### ISSUE THREAD

**Issue by JordanDalton** [laravel/framework#7034]
Attempt to display error page using the following:

````return view('errors.404')````

This produced the following error:

````
BadMethodCallException in View.php line 390: Method [send] does not exist on view.

    in View.php line 390
    at View->__call('send', array()) in index.php line 55
    at View->send() in index.php line 55
````

**Comment by GrahamCampbell** [comment]
If this is in a middleware then you need to actually create a response.

**Comment by GrahamCampbell** [comment]
`return Response::make(view('errors.404'), 404);`

**Comment by GrahamCampbell** [comment]
NB, you should be doing that anyway, otherwise you'd be returning 200 OK for your error page, which isn't right.

**Comment by JordanDalton** [comment]
The following resolved it:

```response()->make(view('errors.404'), 404)```

**Comment by GrahamCampbell** [comment]
Yeh, that's basically the same code.

**Comment by jafaronly** [comment]
this is old, but still want to suggest >> 
 if ($exception instanceof NotFoundHttpException) {
            return parent::render(view('errors.404'), $exception);
        }

**Comment by tienthanhjlw** [comment]
@jafaronly  Thanks :)
