### ISSUE TITLE
[4.1][4.2][5.0] Differing visibilities on relationship method getQualifiedParentKeyName()

### ISSUE THREAD

**Issue by patrickcarlohickman** [laravel/framework#7035]
The `getQualifiedParentKeyName()` method exists on four relationship classes: `Illuminate/Database/Eloquent/Relations/Relation`, `Illuminate/Database/Eloquent/Relations/BelongsToMany`, `Illuminate/Database/Eloquent/Relations/HasManyThrough`, and `Illuminate/Database/Eloquent/Relations/HasOneOrMany`.  However, the method's visibility on the `HasOneOrMany` class is set to `public`, whereas the rest are set to `protected`.

I noticed this when I was using the method to build a SQL statement without having to hardcode table/field names.  It worked perfectly for my hasMany relations, but I got an exception when I tried it with a belongsToMany relation.

I think it would be useful if this method were public on all relationships.  I can submit a pull request if there is no issue with this.

**Comment by jarektkaczyk** [comment]
Definitely should be `public` on all of them.

**Comment by GrahamCampbell** [comment]
Please send a pull to 4.2.
