### ISSUE TITLE
[proposal] Make `queue:restart` restart `queue:listen`-workers as well 

### ISSUE THREAD

**Issue by halaei** [laravel/framework#7036]
It seems currently `artisan queue:restart` only affects on `artisan queue:work --daemon` processes. It will be nice to let them affect `artisan queue:listen`s as well. That, I guess holds for `artisan down/up` commands, too.

PS: or maybe the point is to never use `queue:listen`. Should it be deprecated, if there is no memory leaks? Maybe having a hybrid of those 2 can be safe: a listener that creates daemon processes in a loop, each of them handles, let say, only 100 jobs.

**Comment by bigsinoos** [comment]
It seems that the memory issue has been solved in daemon workers, but the approach for mixing the ```queue:listen``` and ```queue:work --daemon```  is really cool.
