### ISSUE TITLE
Eloquent builder not trigger model events like creating,updating,deleting

### ISSUE THREAD

**Issue by nadavvin** [laravel/framework#7038]
Eloquent builder not trigger model events like creating,updating,deleting

only the model trigger them therefor only (new Model($params))->delete() will trigger but not Model::where(...)->delete()

**Comment by JosephSilber** [comment]
This is not a bug. It is known and [documented](http://laravel.com/docs/4.2/eloquent#insert-update-delete) behavior.

![](http://i.imgur.com/Nj7xwgi.png)

**Comment by nadavvin** [comment]
Does global scope like SoftDeletingScope is affect on builder operations?

**Comment by aaronpeterson** [comment]
Still unclear.  Why give the reader the impression that events are fired for deleting?  This warning should be moved and clarified.
