### ISSUE TITLE
[5.0] Can't create a paginator instance manually

### ISSUE THREAD

**Issue by joseph887** [laravel/framework#7042]
When I try to get the paginator facade resolved by using ```Paginator::make()``` I get the error: ``` Class paginator does not exist ```.

And trying to access the paginator by constructor and method injection throws this error: ```Unresolvable dependency resolving [Parameter #0 [ <required> $items ]] in class Illuminate\Pagination\Paginator```

And it doesn't look like there is a contract bound to the paginator implementation in Application.php . Is there a way at the moment to manually create a paginator instance?

**Comment by joseph887** [comment]
Just had to new up the class and pass in the constructor dependencies Paginator was asking for. I guess the paginator is currently being worked on, or the way to use them is changing. It looks like creating pagination links might be changing a bit too

**Comment by GrahamCampbell** [comment]
We need to still address this. The Laravel 5 release is looming, and this is exactly the sort of thing that needs to be cleaned up before the release.

**Comment by GrahamCampbell** [comment]
Taylor's removed the facade now. Thanks for reporting.
