### ISSUE TITLE
findOrFail() works like find() when array provided

### ISSUE THREAD

**Issue by kokokurak** [laravel/framework#7043]
For some reason, `findOrFail()` method doesn't throw exceptions when array of IDs is provided. For example, if I have a `Animal` model:
```
id | name
-----------
1  | Dog
2  | Cat
3  | Turtle
```

Those are the results of various `find()` / `findOrFail()` combinations:
```php
// single existing
Animal::find(1);       //=> instance of Animal
Animal::findOrFail(1); //=> instance of Animal

// single missing
Animal::find(4);       //=> NULL
Animal::findOrFail(4); //=> ModelNotFoundException

// multiple existing
Animal::find([1, 3]);       //=> Illuminate\Database\Eloquent\Collection with 2 elements
Animal::findOrFail([1, 3]); //=> Illuminate\Database\Eloquent\Collection with 2 elements

// multiple mixed
Animal::find([1, 4]);       //=> Illuminate\Database\Eloquent\Collection with 1 element
Animal::findOrFail([1, 4]); //=> Illuminate\Database\Eloquent\Collection with 1 element

// multiple unexisting
Animal::find([4, 5]);       //=> Illuminate\Database\Eloquent\Collection with 0 elements
Animal::findOrFail([4, 5]); //=> Illuminate\Database\Eloquent\Collection with 0 elements
```

I believe it would be more intuitive, if `findOrFail()` threw `ModelNotFoundException` if **any** of requested ID in the array doesn't exist.

**Comment by JosephSilber** [comment]
@kokokurak now that #7048 has been merged, has this been fixed?

**Comment by olso** [comment]
Not working @4.2

**Comment by GrahamCampbell** [comment]
> Not working @4.2

4.2 is not supported. Upgrade to 5.x, and you'll find this is fixed. :)

**Comment by olso** [comment]
@GrahamCampbell thanks, good to know that :+1:

**Comment by kokokurak** [comment]
By the way, I have tested it after the merge and it works now. Sorry for not telling :)
