### ISSUE TITLE
[5.0] Config & multi-tenants database

### ISSUE THREAD

**Issue by Charkhan** [laravel/framework#7053]
Hi,

Link to the conversation : https://laracasts.com/discuss/channels/general-discussion/l5-multi-tenants-database

I'm trying to build a multi-tenants App with dynamic DB informations (only to change the DB name).

I need to build some command, which have to be "multi-tenants" compatible.

So I tried to build a simple one, just to test :

```php
<?php
namespace App\Console\Commands;

use DB;
use Illuminate\Console\Command;
use App\Repositories\Feeds\FeedsRepositoryInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;

class ParseFeedsContent extends Command {

	/**
	 * The console command name.
	 *
	 * @var string
	 */
	protected $name = 'app:parse-feeds-content';

	/**
	 * The console command description.
	 *
	 * @var string
	 */
	protected $description = '';
	/**
	 * @var FeedsRepositoryInterface
	 */
	private $feedsRepository;

	/**
	 * Create a new command instance.
	 *
	 * @param FeedsRepositoryInterface $feedsRepository
	 */
	public function __construct(FeedsRepositoryInterface $feedsRepository)
	{
		parent::__construct();
		$this->feedsRepository = $feedsRepository;
	}

	/**
	 * Execute the console command.
	 *
	 * @return mixed
	 */
	public function fire()
	{
		if ($tenant = $this->argument('tenant')) {
			return $this->parseFeedsForTenant($tenant);
		}

                //This line will make the code below NOT work.
		$tenants = DB::connection('mysql_tenants')->table('tenants')->lists('tenant_name');
                //If I replace the line above by this, DB calls will work only on the first tenant.
		//$tenants = ['local', 'limoges'];

		foreach ($tenants as $tenant) {
			$this->parseFeedsForTenant($tenant);
		}
	}

	/**
	 * @param $tenant
	 */
	protected function parseFeedsForTenant($tenant)
	{
		config(['database.connections.mysql.database' => 'app_'.$tenant]);
		//$this->laravel['config']['database.connections.mysql.database'] = 'app_' . $tenant;

		$this->feedsRepository->whereRaw('...')->get();

		return $this->info('Test');
	}

	/**
	 * Get the console command arguments.
	 *
	 * @return array
	 */
	protected function getArguments()
	{
		return [
			['tenant', InputArgument::OPTIONAL, 'The tenant name.'],
		];
	}

	/**
	 * Get the console command options.
	 *
	 * @return array
	 */
	protected function getOptions()
	{
		return [];
	}

}
```
I want to get all my tenants from a dedicated DB, and change DB name from another connection to alter each tenant DB data.

But when I do the DB call to get all my tenants, all the subsequent config modifications don't work.
If I comment the `$tenants = DB::connection('mysql_tenants')->table('tenants')->lists('tenant_name');` and replace it by an array : the script doesn't crash, but the DB keeps the 1st tenant db name info....

So, I'm assuming that the DB facade fetches all connections and kind of "cache" them, which will overrides any further conf modifications...

**Comment by GrahamCampbell** [comment]
Sorry, this isn't the place to ask. Laravel's issues are not a place for discussion and support, sorry. Please use the forums for that. Our issues are for discussing isolated bugs and suggesting new features in the form of pull requests,

**Comment by Charkhan** [comment]
I asked on forum, and found that the config modification wasn't properly handled by the framework, that's why I though it was an issue.

I was just explaining how to reproduce the behavior. Sorry if my point wasn't clear...

**Comment by juukie14** [comment]
Perhaps you could simplify the problem and use Laravel Liferaft for this?
