### ISSUE TITLE
[5.0] Inconsistency in use of backslash in namespaced contextual binding

### ISSUE THREAD

**Issue by vgallur** [laravel/framework#7055]
It seems that for namespaced controllers you need to start the parameter for the method `when` with a backslash, but in other dependencies you must start without it. This works:

```php
 $this->app->when('\Vgcms\Cms\Http\Controllers\PageBackController')
                  ->needs('Vgcms\Cms\Contracts\NodeRepository')
                  ->give('Vgcms\Cms\Repositories\PageRepository');

 $this->app->when('Vgcms\Cms\Repositories\PageRepository')
            ->needs('Illuminate\Database\Eloquent\Model')
            ->give('Vgcms\Cms\Models\Page');
```
But if you remove the backslash in the first case or add it in the second it doesn't resolve the dependency.

In `Container->make($abstract, , $parameters = [])` ,  `$abstract` is `'\Vgcms\Cms\Http\Controllers\PageBackController'` when is called, so it doesn't find after in `getContextualConcrete` if you omit the bakcslash.

**Comment by vgallur** [comment]
It only happens when you leave `$namespace` in `RouteServiceProvider` empty and then use absolute namespacing in your routing, instead of relative ones. When the provider includes the routes file in the `loadRoutesFrom` it always uses the `$router->group` namespacing function in the router even if it's empty

```php
protected function loadRoutesFrom($path)
{
	$router = $this->app['Illuminate\Routing\Router'];

	$router->group(['namespace' => $this->namespace], function($router) use ($path)
	{
		require $path;
	});
}
```

Perhaps if `$this->namespace` is empty it could `require $path` without the `$router->group`.

It's really a minor thing but, if you want to load controllers from different namespaces and not to use just one prefix 'App\Http\Controllers' or other, you can face this issue.

**Comment by GrahamCampbell** [comment]
You should never use the leading slashes. The class name is defined without it.

**Comment by vgallur** [comment]
Yes, this is how it should work. But now if you leave an empty $namespace in your RouteServiceProvider it doesn't resolve unless you prefix it with a backslash in your when method, which should not be needed.
