### ISSUE TITLE
Patchwork update 1.2 ?!

### ISSUE THREAD

**Issue by n3m3s7s** [laravel/framework#7057]
Hi!
Patchwork/utf8 1.2 is out and it is used (and required) by some useful packages such as anahkiasen/underscore-php;
is it possibile to update the composer.json file for laravel/framework to use patchwork 1.2 ?!
in your opinion, the update could break a working instance of a laravel 4.2 project ?!

Thank You for any help!!

**Comment by GrahamCampbell** [comment]
Our current version constraint already allows that. It's `~1.1`.

**Comment by GrahamCampbell** [comment]
EDIT: It seems we only changed that on laravel 5, then we removed the dependency al together. I'll get this updated on L5 for you...

**Comment by GrahamCampbell** [comment]
I've left #7063 for Taylor to review. :)
