### ISSUE TITLE
[5.0] Flysystem no longer compatible

### ISSUE THREAD

**Issue by ben-joostens** [laravel/framework#7070]
Flysystem needs to be pinned to the 0.5.12 release because the 1.0.0-alpha1 released 3 days ago breaks compatibility and is installed automatically.

https://github.com/thephpleague/flysystem/releases

Trying to use it, "out of the box", throws this error:

```Class 'League\Flysystem\Adapter\AwsS3' not found in /vendor/laravel/framework/src/Illuminate\Filesystem\FilesystemManager.php on line 133```

It seems flysystem has separated the adapters from its main package.

**Comment by crynobone** [comment]
https://github.com/laravel/framework/commit/beb0a182178c953a295e3b566e0983c1fbc8ca99

has been fixed?

**Comment by ben-joostens** [comment]
Oh wow. I ran into it yesterday and didn't think anyone had noticed. Thanks, that was quick.

**Comment by thiduzz** [comment]
Just ran into it just now. It seems that the AWS3 changed - The League of Extraordinary Packages released some days ago this new package and the adapters are not in the main package last time i checked: 
https://github.com/thephpleague/flysystem-aws-s3-v2

**Comment by ben-joostens** [comment]
@thiduzz Yep, you'll notice flysystem suggests installing them if you use composer.

**Comment by thiduzz** [comment]
Yeap. I didnt get any suggestion when running composer but checking out their composer.json i found it.

Still, even after Taylor change I am getting 

Undefined property: Illuminate\Filesystem\FilesystemManager::$filesystem

when I run $this->filesystem->disk('s3')->exists($folder) on my FilesRepository, but the strange thing is that I am actually using $filesystem as a \Illuminate\Contracts\Filesystem\Factory not a FilesystemManager.

**Comment by thiduzz** [comment]
Fixed!
