### ISSUE TITLE
[4.2] route filters not fired when using Postman / Curl

### ISSUE THREAD

**Issue by yajra** [laravel/framework#7073]
Does Laravel does not fire route filters when using Postman / Curl?

I just stumbled on this today and noticed that route filters do not fire when using these tools. However, when using the browser for normal request, filters do work.

**Using Chrome:**
POST: http://laravel.app/blog -> filters work

**Using Postman:**
POST: http://laravel.app/blog -> filters do not work

**Using Curl:**
POST: curl -X POST http://laravel.app/blog -> filters do not work

**Comment by sorora** [comment]
Just did a test on posting to a route that requires the user to be authenticated (using before filter "auth") and it does apply the filter when using Postman.

**Comment by yajra** [comment]
Weird.. well maybe it's due to I migrated from 4.1 to 4.2 and been encountering some issues that were not occurring on fresh install of 4.2 like the instance of Crypt not working.

**Comment by yajra** [comment]
Ooops my bad! It was an environment issue... sorry!
