### ISSUE TITLE
[4.2] Eloquent bug in querying and outputting double/float values

### ISSUE THREAD

**Issue by envision** [laravel/framework#7075]
Our hosting provider runs Cpanel with Httpd (Apache2), PHP 5.4.36 and MySQL 5.5.40 on CentOS 5.11

After they upgraded from PHP 5.3 to PHP 5.4.36 (and probably their MySQL also) Eloquent started to output values that are on database (when queried with SSH or with plain PHP) for example 333.33 – as 330, with type double! So it's outputting all those floats with two decimal precision as rounded in full tens...

We had older Laravel 4.0 then but upgrading to newest 4.2.16 had no effect. I have also tried updating dependencies with minimum-stability dev with or without prefer stable, and it had no effect.

Database schema for those fields are with:

    $table->float('somefield')->default(0.00);

Update: I have created a Vagrant box with CentOS 6.5 with same software versions although there remains differences in Apache configuration – I haven't been able to replicate this issue locally.

**Comment by envision** [comment]
Even though this might not be an outright bug, it certainly seems an incompatibility with certain Cpanel configuration which is an issue for Eloquent users. Cpanel is very often used with web hosting although Laravel web applications most likely are not so often hosted with Cpanel.

I must highlight that when I connected MySQL with plain PHP it outputted the right values like 333.33

**Comment by GrahamCampbell** [comment]
This is a duplicate.
