### ISSUE TITLE
[5.0] CSRF tokens not working

### ISSUE THREAD

**Issue by ThePoet444** [laravel/framework#7078]
I can't be positive but I think commit: [12158fe](https://github.com/laravel/framework/commit/1215f8e317a74cbd4043dab1b8e01bd7c1bcdf05) broke the CSRF tokens from working properly. Every time I try to use a login I get token mismatch. I've cleared the sessions and cookies but it doesn't help.

**Comment by lzhang43** [comment]
+1

**Comment by rscafi** [comment]
Commit 40eadb90ad2e4013e581fc499908286679cbe382 should fix it.

**Comment by ThePoet444** [comment]
it seems to be fixed. Cool. Thanks :)
