### ISSUE TITLE
Namespace/subdir support when generating commands and events

### ISSUE THREAD

**Issue by mrterryh** [laravel/framework#7086]
To generate a command with L5, we can use the artisan `make:command` command, and a command will be created in the `/app/Commands` directory. However, for larger apps, I'd like to be able to organise these commands into separate subdirectories instead of having 200 commands in one folder. The same goes for handlers and events.

Could we get support for this?

**Comment by filipac** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I'd suggest using Jerry's generator package.

**Comment by mrterryh** [comment]
@GrahamCampbell I don't know what you're referring to. Link to repo?

**Comment by Aistina** [comment]
It sounds like this would be simple enough to integrate. Maybe something along the lines of `php artisan make:command SubDirectory.FooCommand`.

Are you open for PRs?

**Comment by mrterryh** [comment]
@Aistina That's what I was hoping for. Sure we can pull in a package, but I'd rather have it in the framework core and not have to worry about adding another dependency to every project.

**Comment by GrahamCampbell** [comment]
https://github.com/JeffreyWay/Laravel-4-Generators

**Comment by Anahkiasen** [comment]
> I'd suggest using Jerry's generator package.

Jerry Frway ?

**Comment by GrahamCampbell** [comment]
lol - I'm using a terrible keyboard.

**Comment by mrterryh** [comment]
That package doesn't have support for commands and events yet. But even when it does, I'd still rather see this functionality in the Laravel core.

**Comment by GrahamCampbell** [comment]
> That package doesn't have support for commands and events yet.

Then send a pull request. :)

**Comment by Aistina** [comment]
I've found out you can already do this, the syntax is just slightly different.

`php artisan make:command Foo\\BarCommand` will create app/Commands/Foo/BarCommand.php, namespace `App\Commands\Foo`, class name `FooCommand`.

I'm not sure if you'll have to type a double backslash on each platform or not. This was on OS X.
