### ISSUE TITLE
Mailgun Issue

### ISSUE THREAD

**Issue by TechKat** [laravel/framework#7087]
I'm using Mailgun to send my emails. Unfortunately, I seem to be running into a problem. This is the error I get.

Client error response [url] https://api.mailgun.net/v2/https://api.mailgun.net/v2/sandboxde2ccd631106433f9069b43856977dfb.mailgun.org/messages.mime [status code] 404 [reason phrase] NOT FOUND

Is this something vendor-related or me?

**Comment by crynobone** [comment]
Why is your url `https://api.mailgun.net/v2/https://api.mailgun.net/v2`.

**Comment by TechKat** [comment]
@crynobone This is what I don't get. The only changes I made for Mail is adding the username and password in the mail.php config file.

**Comment by rscafi** [comment]
Your `host` at mail config should be: `sandboxde2ccd631106433f9069b43856977dfb.mailgun.org`

Refer to [MailgunTransport](https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/Transport/MailgunTransport.php#L163)

**Comment by TechKat** [comment]
@rscafi Done that, still the same problem.
