### ISSUE TITLE
Laravel 4 - Model save() won't work with chunk() function.

### ISSUE THREAD

**Issue by priyankadevgaonkar** [laravel/framework#7089]
I know I should be doing the hashing of password while creating a new user, that is exactly what I am doing but I need to hash the previously present passwords which were in a pure PHP written system and are now converted to Laravel. 

My code looks like this,

    $users = User::where('password','!=','0')->select(array('password'))->chunk(50,function($users){
        foreach ($users as $user) {
            $user->password = Hash::make($user->password);
            $user->save();
        }
     });

I tried using `try catch` around `save()` and also tried `transaction` nothing helped. Any idea? Also, if I try to `var_dump` `$user` right after `save()` it shows the updated value of password but the DB will still be unaltered. Also, I don't have `$guarded` on password. Mass update works when I do it without `chunk()` but I don't want to deal with time out issue.

**Comment by priyankadevgaonkar** [comment]
In case anybody is really looking for an answer to this problem, then here you go, `chunk()` won't work with custom `select`. I was selecting only password for the obvious reasons. But turns out it doesn't like that. So I had to `get()` everything in order to make it work. Can this be thought of as an improvement for the function?

**Comment by MaartenStaa** [comment]
It makes sense if you think about it. If you `select` only `password`, that means it won't have the id of the users, so it doesn't know what to save.

**Comment by xroot** [comment]
could you dd($user) inside the loop and share with us dumped object?

**Comment by priyankadevgaonkar** [comment]
yeah correct @MaartenStaa, I was doing it wrong way, when I tried selecting id with passwords, I could save the model. genius :) closing the issue.
