### ISSUE TITLE
[Laravel 5] Installation troubles

### ISSUE THREAD

**Issue by iillexial** [laravel/framework#7091]
Hello. I'm install my l5 project from git and get this error:
`
Whoops\Exception\ErrorException thrown with message "Undefined index: path"
`
On this line in  /var/www/html/board/storage/framework/compiled.php:
`
return (new CookieJar())->setDefaultPathAndDomain($config['path'], $config['domain']);
`
Why? And when i run:
`php artisan cache:clear` 
i get 
` 'InvalidArgumentException' with message 'Cache store [] is not defined.'`
What is it?

**Comment by GrahamCampbell** [comment]
You need to update your app with all the changes from laravel/laravel develop.

**Comment by iillexial** [comment]
I ran. What else can I do?

**Comment by GrahamCampbell** [comment]
. I ran.

I didn't mean `composer update`. I meant physically make all the changes to your app yourself that have changed since you downloaded it on laravel/laravel. This is what you must do when you're using a version of laravel that wasn't ready for the public yet.
