### ISSUE TITLE
Corrupt services.json

### ISSUE THREAD

**Issue by troyharvey** [laravel/framework#7092]
This [issue has been open for 5 months on the Laracasts forum](https://laracasts.com/discuss/channels/general-discussion/getting-weird-error-in-laravel), so I'm hoping to spark some new conversation around it here.

Our `services.json` file is "corrupted" at seemingly random times. Here's an example of the messed up portion of the file. Any ideas on how to avoid this are welcome!

```
        "Indatus\\Facades\\ServiceProvider": [],
        "Indatus\\Services\\RoleManagement\\RoleManagementServiceProvider": []
    }
}er": [

        ],
        "Indatus\\Services\\CallMonitor\\CallMonitorServiceProvider": [

        ],
        "Indatus\\Dispatcher\\ServiceProvider": [
```

**Comment by GrahamCampbell** [comment]
No idea what's causing this. Looks like a php bug perhapse.
