### ISSUE TITLE
File::directories('files') sorted by name

### ISSUE THREAD

**Issue by andregeges** [laravel/framework#7098]
Hello, i used method File::directories('files') to get all my folder name, it is working fine in my local MAMP server i get all list directory with sorted name from A-Z

but when i uploaded to my server in sharehosting it still working but the list not sorted by name

how to fixed that? or there is any method to sorted by name ?

**Comment by JosephSilber** [comment]
The result returned is a simple array you can sort yourself:

```php
$directories = array_sort(File::directories('files'), function($file)
{
    return $file->getFilename();
});
```

**Comment by andregeges** [comment]
Hi, when i dd(File::directories('files'));
i got this output

```
array (size=3) 
  0 => string 'files/BOSS' (length=10)
  1 => string 'files/CULVER' (length=12)
  2 => string 'files/DAP' (length=9) 

```

but when i tried your suggestion 
```
$directories = array_sort(File::directories('files'), function($file)
	{
	    return $file->getFilename();
	});
```

and i tried this 
```
return $file->getName();
```
and i got same error
