### ISSUE TITLE
Requests not extending properly?

### ISSUE THREAD

**Issue by greenleafmedia** [laravel/framework#7106]
I have an issue where Requests don't seem to be extending properly and as far as I can tell I'm not doing anything odd.  I have 4 files
ParentController.php

**Comment by GrahamCampbell** [comment]
I have no idea what you mean. Please elaborate.

**Comment by greenleafmedia** [comment]
Sorry, I initially hit return accidentally. :)  Here's the full question:


I have an issue where Requests don't seem to be extending properly and as far as I can tell I'm not doing anything odd.  I have 4 files
ParentController extends Controller
ChildController extends ParentController
ParentRequest extends FormRequest
ChildRequest extends ParentRequest

In my ParentController store method, I'm looking for the parent request: `public function store(ParentRequest $request)`

In my ChildController store method, I'm looking for the child request: `public function store(ChildRequest $request)`

When I try to run the ChildController I get:
Declaration of App\Http\Controllers\ChildController::store() should be compatible with App\Http\Controllers\ParentController::store(App\Http\Requests\ParentRequest $request)

This same pattern is followed for the constructor with Repo injection.  Shouldn't my ParentController realize that ChildRequest is extended from ParentRequest and match the signatures?

**Comment by GrahamCampbell** [comment]
Yeh, this is a limitation with php. You can't change the method signature of a method present in the parent class.

**Comment by greenleafmedia** [comment]
Cool.

Out of curiosity, why does it work for the constructor repos?  Do PHP constructors have a different set of rules than for defined methods?

**Comment by GrahamCampbell** [comment]
Yeh, it does. http://3v4l.org/LFfpD http://3v4l.org/Yk7bH

**Comment by franzliedke** [comment]
Constructors have nothing to do with polymorphism, because you always bind yourself to a certain class when using a constructor (because you're instantiating it). Therefore, the overwriting rules don't apply here.

**Comment by greenleafmedia** [comment]
Ah, there you have it.  Good to know, good to know.  There's always something new to learn.  Thanks for helping me.
