### ISSUE TITLE
hey bro i have a problem with session

### ISSUE THREAD

**Issue by volabook** [laravel/framework#7118]
hey i have a problem my session file standard in session.php 
is work perfectly in my localhost but before upload my project on my hosting is trouble not working 
my version is 4.2.16 please if you have idea about this 
my session is writable in   storage path session but before attempt logged in and intended not work 
what the same issue ?
please i want your help :( thank you

**Comment by RomainLanz** [comment]
You need to post this on the forum and not on Github

**Comment by volabook** [comment]
please bro help me

**Comment by juukie14** [comment]
Try the laracasts forum or laravel.io forum.
