### ISSUE TITLE
[5.0] Resource routing for PATCH request does not give a route name

### ISSUE THREAD

**Issue by TimeToogo** [laravel/framework#7127]
```php
$router->resource('resource', 'ResourceController');
```

When registering a resource like above, it registers the standard restful routes. They are all named except for the PATCH request which in the [docs](http://laravel.com/docs/master/controllers#restful-resource-controllers) is said to have a route name of `resource.update` but when attempting to get the current route name in the controller or even running `php artisan route:list` the route name is not being set.

**Comment by GrahamCampbell** [comment]
This is intentional. PUT gets the name.
