### ISSUE TITLE
HTTP inputs should be copied by reference while constructing Request objects

### ISSUE THREAD

**Issue by halaei** [laravel/framework#7129]
First make a TestRequest with `artisan make:request TestRequest`. Then put this code in your routes.php file:

```PHP
$router->get('/test', function()
{
  /** @var \Illuminate\Http\Request $request */
  $request = App::make('request');
  $request->merge(['request' => 'works']);
  /** @var \App\Http\Requests\TestRequest $testRequest */
  $testRequest = App::make(\App\Http\Requests\TestRequest::class);
  $testRequest->merge(['testRequest' => 'does not work']);
  dd(Input::all());
});
``` 
Hitting localhost/test?q=1, the response is not what I was expecting at first:

array:2 [
  "q" => "1"
  "request" => "works"
]

Is it a bug?

My expectation was that all objects inherited from Request are holding reference to the same 'singleton' data buffer, so by changing this buffer through $one->merge(), $others also observe the same change. But this expectation seems to be not met.

**Comment by franzliedke** [comment]
When you use the `Input` facade, you're always resolving the `request` service from the IoC container. Since `$testRequest` is another instance, these results make sense.

**Comment by halaei** [comment]
I know. It sounds like in the current implementation every request object has its own 'copy' of all the http inputs. But why it is not the case that every instance has 'reference' to those?

I was thinking of using both laravel 5 resquests and [laracasts/commander CommanderTrait](https://github.com/laracasts/Commander/blob/master/src/Laracasts/Commander/CommanderTrait.php) together, but then this merge() behavior makes calling execute() with default params not to do what I first thought it should do.
