### ISSUE TITLE
Route-Model-Binding with nested resources

### ISSUE THREAD

**Issue by EloProf** [laravel/framework#7132]
Currently it is not easily possible to differentiate nested resources for route model bindings:
```php
Route::model('a', 'AModel');
Route::resource('a', 'AController');

Route::model('b', 'BModel');
Route::resource('b', 'BController');
```
Both of these resources have a nested resource called `action` with the following routes:
```php
Route::resource('a.action', 'AActionController');
Route::resource('b.action', 'BActionController');
``` 
If I now want to route model bind their respective action models I can't differentiate them by name, because in both cases the Route will just look for a binding with the name `action`. The only possible  workaround is to do something like this:
```php
Route::bind('action', function($value, \Illuminate\Routing\Route $route) {
	if ($a = $route->getParameter('a')) {
		return $a->actions()->findOrFail($value);
	} elseif ($b = $route->getParameter('b')) {
		return $b->actions()->findOrFail($value);
	}

	throw new NotFoundHttpException;
});
```
In my opinion this is very inconvenient and heavily obfuscates that there are actually two bindings going on instead of the expected one.

I would propose the following solution:
Name nested resource route parameters by their full name, for example the nested resource of
```php
Route::resource('post.comment');
```
would result in routes with the following scheme:
```
.../post/{post}/comment/{post.comment}
```
With this you could directly bind to the complete identifiers `a.action` and `b.action` from my example

**Comment by dwightwatson** [comment]
This is a problem I've run into as well, and this is quite an interesting solution.

I usually end up dropping model binding on the second parameter and performing the `findOrFail()` on the relationship in the controller action instead of the binding callback. I could see it getting really messy if you had the second model nested under a number of other models.

**Comment by EloProf** [comment]
In my case it is actually even messier than you can imagine. My structure is something like this:
```
A->B->method->instance
A->C->action->instance
A->D->E->action->instance
```
You don't want to see the code i have to use in my `Route::bind('instance', function () {...})` to sort out what instance I am currently getting =(

**Comment by EloProf** [comment]
I dug around in source a bit and I found an issue that would most likely prevent the usage of the `post.commment` notation:

Laravel uses Symfony to compile its routes parameters into regular expressions. To do so it looks for the following regex on the route pattern `#\{\w+\}#`. Since `\w` in a regex is equivalent to `[a-zA-Z_0-9]` this won't recognize names that include `.`. That is also the reason why `-` in route parameters are converted to `_` under hood.

A possible workaround would be to just replace `.` with `_` in the name, but this would mean losing some clarity for example when wanting to bind `foo-bar.comment`, because it would result in `foo_bar_comment` which can't be distinguished from `foo.bar-comment`.

**Comment by GrahamCampbell** [comment]
Seems to have rejected a while ago.
