### ISSUE TITLE
[Proposal] Assets linking

### ISSUE THREAD

**Issue by kokokurak** [laravel/framework#7136]
Hello,

I just thought how would it be if publishing (duplicating) assets from packages wasn't necessary? If Laravel had built-in routes to assets from packages instead of copying them to `/public` folder with `asset:publish` command? Same for views and configs. Are there any reasons why it's required to do it manually this way?

**Comment by barryvdh** [comment]
Routing all assets through routes isn't very efficient. Perhaps you could symlink the assets to their vendor folder instead.

**Comment by barryvdh** [comment]
Similar to the `vendor:publish` command, a `vendor:assets` command would be nice, which would overwrite existing assets (instead of skipping them, which is more logical for config etc). And if possible, just create a symlink between directories.

**Comment by barryvdh** [comment]
No explanation?

**Comment by GrahamCampbell** [comment]
You said:

> Routing all assets through routes isn't very efficient. Perhaps you could symlink the assets to their vendor folder instead.

I assumed that meant this was a bad idea?

**Comment by barryvdh** [comment]
Yeah just the part about routing it through Laravel, not the whole 'asset linking' part.

**Comment by GrahamCampbell** [comment]
Sorry, I skipped past this very quickly. Thanks for catching this.

**Comment by kokokurak** [comment]
I'm not sure if assets routing is that inefficient nowadays. Is it really that much of an overhead?

My idea was to simplify packages installation process. I believe that the assets could stay where they are and be linked to by specific URL containing package name, maybe even with dedicated method, like:
```
package_asset('images/cow.png', 'johnthefarmer/myfarm')
```

We are now deep in XXI century now and calculating every microsecond of performance is not such of the case now. This one small operation per asset won't kill anyone and it will make projects more robust, with no manual "publishing".

**Comment by dwightwatson** [comment]
Yeah, asset routing is still incredibly inefficient. We're not talking microseconds, generally you'd be looking at hundreds of milliseconds and that all adds up very quickly.

**Comment by franzliedke** [comment]
@kokokurak Yes, booting the entire framework for serving an already static file is highly inefficient.

**Comment by kokokurak** [comment]
Maybe then the framework should provide assets service without booting itself? Keeping assets in /public folder is not enough for most projects. Assets pipelines etc. are nice, but sometimes I'd like to just use assets from packages. I will defend my idea here, because I find assets publishing really unnecessary and wrong.

**Comment by barryvdh** [comment]
http://symfony.com/blog/new-in-symfony-2-6-smarter-assets-install-command

    # make a hard copy of the assets in web/
    $ php app/console assets:install

    # if possible, make absolute symlinks in web/ if not, make a hard copy
    $ php app/console assets:install --symlink

    # if possible, make relative symlinks in web/ if not, make a hard copy
    $ php app/console assets:install --symlink --relative

I think this would be an okay method.

Each package provider could register it's paths, similar to the publishes config.

`$this->assets($sourceDir, $targetDir);`

Running `php artisan vendor:assets` would delete the existing folders and overwrite with the new assets. `php artisan vendor:assets --symlink` would try to create a symlink (on linux systems) between the vendor folder and the public folder.
You would just run that 1 command on composer install/update.

**Comment by barryvdh** [comment]
And the hard part for that is already done here: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php

**Comment by kokokurak** [comment]
I'm still NO for additional commands and/or copying/symlinks or any kind of data duplication.

**Comment by Anahkiasen** [comment]
I don't get it, how would you want it to work otherwise?

**Comment by barryvdh** [comment]
Symlinking is not data duplication? Just run some benchmakers, load a simple image/css file through Laravel or directly with apache. That's a real difference.. Not much for a few files but a lot of vendor files exist of small icons, multiple scripts etc.

**Comment by kokokurak** [comment]
As I said, I'd like to get **dynamic** access to assets. They would resist in package folder and have nothing to do with /public. Then, the framework would route it. There's no need to boot the whole framework for this operation. Just simple route evaluation. I'm always against all kinds of desynchronisation and symlinking is that. I want to be sure that deleting package folder doesn't leave any garbage. This is actually what the idea of **module** is.

**Comment by barryvdh** [comment]
There is not 'simple route evaluation' without booting the framework (currently). You could look into things like Assetic, but I think they recommend dumping the assets to files anyways, for performance: http://stackoverflow.com/questions/22873164/difference-between-asseticdump-and-assetsinstall

You could just write your own php/htaccess file that outputs the vendor files, but you'd have to know the folders, which you can't with either using the same folder for each package, or having them set in the ServiceProvider, which needs them booted (or you'd cache the result to file).

But I still don't really see the problem with copying/symlinking. If you keep the package folder just for vendor packages, you could delete the package folder and republish the active packages, so everything is clean again, right?

**Comment by barryvdh** [comment]
And packages could still route them off course, like I did here: https://github.com/barryvdh/laravel-debugbar/blob/master/src/Controllers/AssetController.php
But that's for development. it really is noticably slower..

**Comment by kokokurak** [comment]
This is proposal, idea to improve our workflows. Of course, running one more command is not a problem. And if one is no a problem, why not running two? etc. Laravel makes developer's life easier and I'm having ideas to make it even better, that's it. I believe the number of manual steps should be kept to minimum.

After our discussion, I find this assets publishing to /public even weirder than before :smile:

**Comment by barryvdh** [comment]
Okay I don't share your opinion, so I've created a proposal for copying the assets ;)
https://github.com/laravel/framework/issues/7147

**Comment by kokokurak** [comment]
Just curious, if assets are published because routing them is heavy, why are views and configs published as well? This is beyond me, why can't views and configs just stay in a package folder?

**Comment by franzliedke** [comment]
Because upgrading the package could break your config. The config should be local to your application.

**Comment by barryvdh** [comment]
They can. You just publish them if you want to override them. You can't change files in the vendor folder.
And they aren't 'routed', they are just read in the same request.

**Comment by GrahamCampbell** [comment]
This is probably something to be implemented in a package for laravel. If anyone has a good solution for this, they can propose it to Taylor to go into the 5.1 core.
