### ISSUE TITLE
Remember me cookie cannot be configured as HTTPs only

### ISSUE THREAD

**Issue by mfjordvald** [laravel/framework#7142]
Laravel allows setting the session cookie as HTTPs only, however there is no such setting for the remember me cookie and the guard class does not allow for it.

https://github.com/laravel/laravel/blob/master/app/config/session.php#L138
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Guard.php#L508

I propose that the Guard class is modified to read a settings from the auth.php config file in similar style as the session cookie.

If there is interest in this I can submit a pull request to integrate this into either 4.2 or 5.0.

**Comment by franzliedke** [comment]
Would it make sense to use the same setting here?

That said, the config value should simply be passed to the Guard class, it shouldn't be coupled to the config component.

**Comment by mfjordvald** [comment]
I would not personally be opposed to using the same configuration variable but it's also not something that strikes me as immediately intuitive.

The way it's handled for the session cookie is that the Session Middleware asks the SessionManager for the session config array and then simply checks if secure is set or not.

There is an AuthManager which interacts with the auth configuration section, however it is not being used by the Guard class which sets the remember me cookie.

There are essentially two ways to implement this.

The login method can be modified to take a secure flag: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Auth/Guard.php#L420 which can then be passed all the way down to the method which sets the cookie.

The benefit is that this is fairly clean and self-explanatory when reading the code.

The down side is that it would be some time before abstraction layers would integrate this into their own libraries. For instance anyone using Confide will call Confide::logAttempt instead of directly accessing Auth::login() and will thus have to wait for Confide to update.

See: https://github.com/Zizaco/confide/blob/master/src/Confide/Confide.php#L122

The other way would be to pass in the AuthManager to the Guard class and implement a method to check if a configuration setting is set. This is a lot more involved but would allow everyone to easily set whether to use a secure cookie or not around their authentication abstraction layer.

I'm not sure what the preferred Laravel way is.

**Comment by GrahamCampbell** [comment]
We're open to pull requests. :)

**Comment by anlutro** [comment]
You could also create a `useSecureCookies(bool toggle)` method, or pass a `useSecureCookies` argument to the Guard constructor. Either one would set a property that would be passed on to the `CookieJar->forever` method call. Once implemented, you could call `Auth::useSecureCookies(true)` somewhere early in your app's lifecycle.

What's up with all this closing of issues that are clearly unresolved?

**Comment by chrispassas** [comment]
I ran into the same issue. I had to create my own Auth Driver and also extend the Guard class. In my extended guard class I did the following


class CustomGuard extends Guard {

	/**
	 * Create a remember me cookie for a given ID.
	 *
	 * @param  string  $value
	 * @return \Symfony\Component\HttpFoundation\Cookie
	 */
	protected function createRecaller($value)
	{
		$secure = Config::get('auth.secure',false);
		return $this->getCookieJar()->forever($this->getRecallerName(), $value, null, null, $secure);
	}

}


This isn't how I would propose the framework handle this but it did solve my problem.
