### ISSUE TITLE
Illuminate\Validation\Validator::each() doesn't support string rules (though documented)

### ISSUE THREAD

**Issue by FractalizeR** [laravel/framework#7145]
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Validation/Validator.php#L222

```php
	/**
	 * Define a set of rules that apply to each element in an array attribute.
	 *
	 * @param  string  $attribute
	 * @param  string|array  $rules
	 * @return void
	 *
	 * @throws \InvalidArgumentException
	 */
	public function each($attribute, $rules)
	{
		$data = array_get($this->data, $attribute);
		if ( ! is_array($data))
		{
			if ($this->hasRule($attribute, 'Array')) return;
			throw new \InvalidArgumentException('Attribute for each() must be an array.');
		}
		foreach ($data as $dataKey => $dataValue)
		{
			foreach ($rules as $ruleValue)
			{
				$this->mergeRules("$attribute.$dataKey", $ruleValue);
			}
		}
	}
```

Here ```$rules``` can be either string or an array. But if it is string, you must first run something like \Illuminate\Validation\Validator::explodeRules() on it.

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by FractalizeR** [comment]
4.2.16: https://github.com/laravel/framework/blob/v4.2.16/src/Illuminate/Validation/Validator.php#L221

**Comment by GrahamCampbell** [comment]
I think this is working on the latest 5.0.x tag.

**Comment by FractalizeR** [comment]
You mean this is not going to be fixed in 4.x branch? Why?

**Comment by GrahamCampbell** [comment]
> You mean this is not going to be fixed in 4.x branch? Why?

Laravel 4 is not maintained anymore for more trivial issues like this one.

**Comment by FractalizeR** [comment]
I see. Thanks.
