### ISSUE TITLE
[5.0] Command Bus Automapping from a request object

### ISSUE THREAD

**Issue by darryldecode** [laravel/framework#7146]
If we dispatch a command using ```dispatchFrom( "Some\Command", $requestObject );```
and the ```$requestObject``` does not contain a key that is a constructor argument in the ```"Some\Command"``` and has set a default value of ```array()```, the default value in the constructor is not assigned, instead, it will have a value of ```null```

From the code below:
https://github.com/laravel/framework/blob/master/src/Illuminate/Bus/Dispatcher.php#L131

```php
	protected function getParameterValueForCommand($command, ArrayAccess $source,
                                                   ReflectionParameter $parameter, array $extras = array())
	{
		$value = $this->extractValueFromExtras($parameter, $extras);
		
		if (is_null($value))
		{
			$value = $this->extractValueFromSource($source, $parameter);
		}
		elseif (is_null($value) && $parameter->isDefaultValueAvailable())
		{
			$value = $parameter->getDefaultValue();
		}
		elseif (is_null($value))
		{
			MarshalException::whileMapping($command, $parameter);
		}
		return $value;
	}
```

**this method:** ```$value = $this->extractValueFromSource($source, $parameter);```

will return ```null``` when a key is not set in ```$source``` and therefore ```null``` will be set to it, which I think if ```null``` is returned from this method, it should again check if there is a default value on Command constructor, so the code will look like below:

```php
	protected function getParameterValueForCommand($command, ArrayAccess $source,
                                                   ReflectionParameter $parameter, array $extras = array())
	{
		$value = $this->extractValueFromExtras($parameter, $extras);
		
		if (is_null($value))
		{
			if( is_null( $this->extractValueFromSource($source, $parameter)) && $parameter->isDefaultValueAvailable() )
			{
				$value = $parameter->getDefaultValue();
			}
			else
			{
				$value = $this->extractValueFromSource($source, $parameter);
			}
		}
		elseif (is_null($value) && $parameter->isDefaultValueAvailable())
		{
			$value = $parameter->getDefaultValue();
		}
		elseif (is_null($value))
		{
			MarshalException::whileMapping($command, $parameter);
		}
		return $value;
	}
```

**Comment by GrahamCampbell** [comment]
This is known. Please comment on my pull.
