### ISSUE TITLE
[5.0] Proposal: Vendor Assets publish command

### ISSUE THREAD

**Issue by barryvdh** [laravel/framework#7147]
For config/views etc, we have the `publishes()` method and the `php artisan vendor:publish` command. This works fine for files that should be published once and then modified by the developer, so they aren't overwritten by updates.
Package assets work differently, because they usually need to be re-published after updates.

I suggest the create a `vendor:assets` (or similar) command to copy all public assets from packages to the user public folder. This could work similar in the ServiceProvider:
`$this->assets([$sourceDir => $targetDir]);`

On publishing, the targetDir would be removed/emptied and the contents of the $sourceDir would be copied.

Considerations:
- Restrict to a certain folder in the public, to prevent wrong overwriting? Eg. `public/vendor` or `public/packages` folder. (And to force best practice)
- Symlink option to symlink the folders, instead of copying them. Could be even the default option, if possible?
- Add a `vendor_assets()` folder, to provide easy access in views to the package files?

The command could be heavily based on the [Symfony AssetsInstallCommand](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php), except that it uses the registered asset paths.

**Comment by BeingTomGreen** [comment]
:+1:

**Comment by TerrePorter** [comment]
Something similar is already in artisan. See https://github.com/laravel/docs/blob/master/packages.md#publishing-views

**Comment by barryvdh** [comment]
Yes, that is what I said in the first sentence, this is different ;)

**Comment by TerrePorter** [comment]
My apologizes, that's what I get for getting interrupted when reading something.

**Comment by willrowe** [comment]
I think why it was set up this way, was so that you could literally publish any files/folders anywhere in the project, which gets away from having specific folders where things go. I agree that there should be a way to re-publish certain files when updates happen though. I was thinking that perhaps the `publishes()` function and artisan command should be changed to work like so:
```php
// Service Provider
$this->publishes([
    'public' => [
        'path/to/source' => 'path/to/destination'
    ]
]);
```
So there could be keyed sets of assets for publishing which could then be targeted by the artisan command with an overwrite option to force deletion of any existing files:
`php artisan vendor:publish public --overwrite`
Running it without any arguments would still publish all files/folders that have been set.

**Comment by barryvdh** [comment]
Yes but that is kind of the same thing. 1 array with subgroups or 2 arrays.

**Comment by willrowe** [comment]
I'm not sure I follow what you mean...

**Comment by pilot911** [comment]
so now there are no way to publish assets from package ?

**Comment by barryvdh** [comment]
Well, you could publish them once, but updates don't get pushed ;) So people would have to write a custom publisher..
But if there is interest, I'll see if I can create a PR for this.

**Comment by pilot911** [comment]
yes, we really need it

**Comment by willrowe** [comment]
Wouldn't a generalized approach be more useful for everyone though? Not all packages publish assets to the public folder but they might still need this functionality to publish to other files/folders.

**Comment by barryvdh** [comment]
For what? The point of the public assets is that apache/nginx can't access them if they aren't in the public folder. Just reading/loading files from the vendor folder isn't a problem otherwise.
Files that could be modified shouldn't be overwritten, so could just use the existing `vendor:publish` command, right?

**Comment by willrowe** [comment]
I understand why you want to be able to overwrite files in the public folder, and I agree that there should be a way to do it. I'd just like the ability to do it with more than just a specific location in the public folder. It could be very useful if, for instance, someone wanted to revert to the original config file or get the newest changes after an update.

**Comment by barryvdh** [comment]
I agree, but that would mean you would need a --overwrite flag on the publish command AND have a way to specifiy what files you want to overwrite, which is currently not possible. So that would require changes to the `vendor:publish` command but doesn't have much to do with this proposal.

**Comment by willrowe** [comment]
Ok, yeah I know it's not what you were proposing, it just seemed like we could come up with a solution that would solve both problems at once.

**Comment by GrahamCampbell** [comment]
I'm a bit confused why this is needed. Perhaps sending a pull request would be better.

**Comment by barryvdh** [comment]
Why are you confused? This was already L4: http://laravel.com/docs/4.2/packages#package-assets
What I propose just makes it a bit simpler/in line with the resource publisher.
I'm okay with creating a PR but I don't really like creating PRs just to be shot down then, that's why I create a proposal first..

**Comment by GrahamCampbell** [comment]
> I'm okay with creating a PR but I don't really like creating PRs just to be shot down then, that's why I create a proposal first.

Our current policy is supposed to be only create proposals for things that take a serious amount of time to write. Something that takes between 5 mins and 2 hours isn't meant to require a proposal issue first.

**Comment by barryvdh** [comment]
Yeah but it's not just about wasting 2 hours but also trying to determine the need, best approach, things to consider etc instead of just writing something based on just my thoughts.

**Comment by barryvdh** [comment]
Added a PR in #7168
