### ISSUE TITLE
List of parameters for route filter doesn't work

### ISSUE THREAD

**Issue by andreyst** [laravel/framework#7149]
I am trying to implement a filter that accepts multiple parameters, like this:
```
'before' => 'auth|role:admin,lp_admin,lp_main_tech,lp_tech',
```

But in my filter function I receive only the first value:
```
Route::filter('role', function($route, $request, $value) {
  var_dump($value);
});
```
> string(5) "admin"

This is because in callRouteFilter (src/Illuminate/Routing/Router.php:1462 for v4.2) parameters, which are correctly explode into an array before by ',', get flattened with everything else by array_merge:
```
$data = array_merge(array($route, $request, $response), $parameters);
```
The resulting array is later being passed as parameters array into call_user_func, which results in all my original parameters passed as separate params to route filter function (..., $value, $value2, $value3...). Judging by the parameters handling code this is not a desired behavior. 

I am working around this by using something like this:
```
Route::filter('role', function($route, $request, $value) {
  $roles = $value;
  if (func_num_args() > 3 && !is_array($value)) {
    $roles = array_slice(func_get_args(), 2);
  }
  if (!is_array($roles)) {
    $roles = [ $roles ];
  }
});
```
But this is way to brittle. Simple change in source also worked for me:
```
$data = [ $route, $request, $response, $parameters ];
```
But this could easily interfere with something somewhere I do not yet know where, so I'm reluctant to fix it this way. Also patching sources is tedious.

As far as I can see in git log, this was the original way it was written by @taylorotwell:
> commit a4d8d950e49dc7d0de153513994a23e9343cfd4e
> Author: Taylor Otwell
> Date:   Fri Aug 23 00:44:33 2013 -0500

Maybe Aug 2013 is not that far away and he could remember and fix it? :)

**Comment by GrahamCampbell** [comment]
I thought we were just passing the second param as a 4th param rather than as an array to the 3rd param?

**Comment by andreyst** [comment]
Well, this is how it works now. But wouldn't it make much more sense to send it as an array?

Or this is an artefact now and we have to live with that? 

Let me know and I'll add an example in docs.

**Comment by crynobone** [comment]
<https://github.com/laravel/framework/commit/9902e7d5960c6f3a2ad9a187c142ab6dbb384ed1>

It should be the expected approach since taylor specifically code the tests that way.

**Comment by andreyst** [comment]
@crynobone I still don't believe that covering inconsistent and unexpected behaviour with tests makes it more consistent and unexpected.

Anyway, since I cannot provide a pull request yet, I'll add an example of current usage to docs.
