### ISSUE TITLE
[5.0] [Proposal] Make model command to add table name

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#7150]
It would be good if the make model command also set the snake-cased, pluralized table name, i.e.

```
<?php namespace {{namespace}};

use Illuminate\Database\Eloquent\Model;

class {{class}} extends Model {

	protected $table = '{{table}}';

}
```

**Comment by GrahamCampbell** [comment]
Probably not useful by default. If you want to send a pull for Taylor to review feel free. Sorry our contribution guidelines are still incorrect for proposals like this.
