### ISSUE TITLE
models support Russian doll caching?

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#7154]
Will the upcoming Laravel Framework support Russian Doll caching? I saw a old issues thread that had been closed from a year or so ago, I wanted to know if this is going to be pushed into Laravel 5, as it's very effective in Rails.

**Comment by GrahamCampbell** [comment]
This is probably something for you to implement in your own app. Repositories can be very good for this sort of thing. You can wrap your eloquent repository in a caching repository.
