### ISSUE TITLE
Database name with dot in it leads to pdo exception when using unix_socket

### ISSUE THREAD

**Issue by ivacuum** [laravel/framework#7155]
Usually I name site database with associated domain name, but such naming convention leads to exception in Laravel when I specify unix_socket in the app config and have database name like `example.com`.
> exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.com' at line 1' in ~/vendor/laravel/framework/src/Illuminate/Database/Connectors/[MySqlConnector.php:24](https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Connectors/MySqlConnector.php#L24)

The problem line.
```php
$connection->exec("use {$config['database']};");
```

Wrapping database name in backticks fixes the bug.
```php
$connection->exec("use `{$config['database']}`;");
```

**Comment by nickescobedo** [comment]
I assume this is because the database name has a period in it. Without quotes it probably confuses the database because of the period.

**Comment by GrahamCampbell** [comment]
You can't use database names containing a fullstop. Sorry.

**Comment by ivacuum** [comment]
But it does work without specifying unix_socket in config. That's confusing.

**Comment by franzliedke** [comment]
Interesting. As far as I can see, [MySQL does not allow full stops in database or table names](http://dev.mysql.com/doc/refman/5.0/en/identifiers.html).

**Comment by ivacuum** [comment]
It could since 5.1.6
http://dev.mysql.com/doc/refman/5.1/en/identifiers.html
> Before MySQL 5.1.6, database and table names cannot contain “/”, “\”, “.”, or characters that are not permitted in file names.

5.1.6 was released the way back in [2006](http://dev.mysql.com/doc/relnotes/mysql/5.1/en/news-5-1-6.html).

**Comment by franzliedke** [comment]
Ah, my bad.

**Comment by barryvdh** [comment]
Why the close? This doesn't seem like a very difficult fix?

**Comment by GrahamCampbell** [comment]
We're open to pull requests. If the fix is so trivial, there's no point in this issue. I find things are more manageable this way. :)

**Comment by barryvdh** [comment]
So why don't you say that ;) How are people supposed to guess that?

**Comment by GrahamCampbell** [comment]
> So why don't you say that ;) How are people supposed to guess that?

I still haven't got around to fixing the contribution guide. It will detail things like this.

**Comment by ivacuum** [comment]
I was low on time and had difficulties with cloning laravel/framework and installing its dependencies, so I decided to open the issue first. Whatever. I'll try to make pull request then. Thanks.
