### ISSUE TITLE
[5.0] Default Laravel Hello Page Fetches Lato Font insecurely

### ISSUE THREAD

**Issue by DavidLemayian** [laravel/framework#7159]
Perhaps small, but when I load the default laravel hello page at https://example.com/, Chrome throws the following error:

```js
Mixed Content: The page at 'https://example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Lato:100'. This request has been blocked; the content must be served over HTTPS.
```

This of course messes with the intended styling of the page.

**Comment by GrahamCampbell** [comment]
We're open to pull requests to the develop branch of laravel/laravel. :)

**Comment by DavidLemayian** [comment]
@GrahamCampbell Excellent! Thought because of the contribution guidelines I would report here. Will definitely open a pull request there. :+1:
