### ISSUE TITLE
[5.0] Environment based configs not working correctly

### ISSUE THREAD

**Issue by Kussie** [laravel/framework#7161]
I have three different services.php structured like this for example:
http://laravel.io/bin/32eD4

According to my .env file my environment is set to 'local', `php artisan env` returns 'local'.  Accessing the app via the web my environment is returned as 'local'.

However `Config::get('services.someitem')` returns 'Staging' instead of the expected value of 'Local'.

If i create a new environment folder called 'zebra' and change the value in zebra/services.php to 'Zebra' it returns 'Zebra' instead of the expected value of 'Local'.

It looks as though L5 is loading the config from the files of whatever the last folder inside of the 'config' directory is regardless of environment.

This is on revison: f219ab878c4781ffcd1915b2e276a302f8ec935b of laravel/framework

**Comment by GrahamCampbell** [comment]
Our config system doesn't work like that anymore. No more subfolders.

**Comment by tylercrompton** [comment]
I see that this is documented [here] but what I don't see is where to set the test configuration variables. Do you mind pointing me in the right direction for that? Perhaps I've overlooked something.

**Comment by GrahamCampbell** [comment]
> I don't see is where to set the test configuration variables. 

Look in the phpunit configuration file. :)
