### ISSUE TITLE
Update Superclosure

### ISSUE THREAD

**Issue by Anahkiasen** [laravel/framework#7163]
Just wanted to ask if there was any reason `illuminate/support` was still requiring superclosure 1.0 instead of 2.0, since we don't need the 5.3 support anyway on 4.2? This is causing conflicts on a project which require Psysh, the latter causing a conflict with it

**Comment by Anahkiasen** [comment]
(Conflict being that Superclosure 1 requires php-parser 0.9 while Psysh and Superclosure 2 use 1.0)

**Comment by GrahamCampbell** [comment]
> Just wanted to ask if there was any reason illuminate/support was still requiring superclosure 0.9 instead of 1.0

It's not. We're requiring `~1.0.1` in Laravel 4.2.

**Comment by Anahkiasen** [comment]
Yes made a typo, edited my post

**Comment by GrahamCampbell** [comment]
And `~2.0` in 5.0. This is disused on my L5 pulls. :)

**Comment by Anahkiasen** [comment]
Yes I know L5 uses 2.0 but I'm talking about 4.2

**Comment by GrahamCampbell** [comment]
@Anahkiasen We NEVER update dependencies my major versions in patch releases. That will screw someone over who's relying on the old version.

**Comment by Anahkiasen** [comment]
Oh well, ok

**Comment by GrahamCampbell** [comment]
We've done this same thing with a few other dependencies too. Like phpeanstalk and predis.

**Comment by Anahkiasen** [comment]
No yeah thought I'd ask since it's more of an internal dependency and the functionality doesn't change, just the API – since it's all uniformized through the SerializableClosure class. Was worth a shot.

**Comment by GrahamCampbell** [comment]
Closures serialized with 1.0.x won't be correctly unserialized with 2.0. So that's another reason we can't do it in a patch release because people's queued jobs may start failing.
