### ISSUE TITLE
No 'whereNotNull' in JoinClause

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#7165]
Was trying to use whereNotNull as part of an advanced join.

whereNull exists as part of JoinClause, but whereNotNull doesn't.

Any reason for this omission?

**Comment by danilobrinu** [comment]
I find an alternative solution:

```PHP
->orWhere(function ($query) { 
    $query->whereNull('field');
});
```

**Comment by mattmcdonald-uk** [comment]
@danilobrinu Yes - but much neater when method exists

**Comment by danilobrinu** [comment]
Yes but is useful when not have the last version (5.0)
