### ISSUE TITLE
[5.0] Confusion about exception thrown by ValidateRequests

### ISSUE THREAD

**Issue by vlakoff** [laravel/framework#7178]
The [documentation](http://laravel.com/docs/master/validation#controller-validation) says [ValidateRequests](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Validation/ValidatesRequests.php) throws an `Illuminate\Contracts\Validation\ValidationException`, whereas it actually throws an `Illuminate\Http\Exception\HttpResponseException`.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by vlakoff** [comment]
I was unsure how to fix it, otherwise I would have submitted a PR, whereas I'm confident Taylor could quite easily fix it.

**Comment by GrahamCampbell** [comment]
The docs just need updating. It's too late to move the class about now.

**Comment by vlakoff** [comment]
For the record,

* Documentation since 5.1 simply doesn't detail the type of exception
* Laravel 5.2 will actually throw ValidationException

**Comment by garygreen** [comment]
This just caught me out as well. It seems inconsistent that `ValidatesRequests` throws a `ValidatorException` and `FormRequest` throws a `HttpResponseException`

Shouldn't `HttpResponseException` be added to the `dontReport` at least ?
