### ISSUE TITLE
Artisan CLI: Change Controller Path

### ISSUE THREAD

**Issue by virtualstep** [laravel/framework#7188]
Good evening,

within the Artisan CLI I can make a controller via "controller:make" command.

In L4 I could change the path via "--path" parameter.

How can I do this in L5 ?

Sorry for bad english -> I'm German ;)

**Comment by tjbenator** [comment]
There doesn't appear to be a `--path` flag anymore in the new `make:controller` command unfortunately 

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Routing/Console/ControllerMakeCommand.php

**Comment by GrahamCampbell** [comment]
Perhaps send a pull request to add it to both the controller and middleware commands.
