### ISSUE TITLE
havingRaw is not working 

### ISSUE THREAD

**Issue by baao** [laravel/framework#7191]
I have a very strange issue with a query in laravel 5.

This part:

    ->havingRaw('MIN(pr.landed_price) > (pro.price + pro.shipping)')

throws an error saying

    column not found

This is strange because

- the column definitely exists
- the query is running with laravel 4 without a problem
- I have checked both raw query outputs (L4 & L5) with ->toSql(); and they are completely identical.
- Running the query without laravel works, too.

Is there a known bug, anything else I don't see - and how can I solve this?

**Comment by gil0mendes** [comment]
Give me the version of L4 you tested.
Generated SQL: select `price` from `pro` having MIN(pr.landed_price) > (pro.price + pro.shipping)

The `pr` table isn't included on `FROM` clausure
