### ISSUE TITLE
artisan app:name bugs depending on param input?

### ISSUE THREAD

**Issue by JerseyMilker** [laravel/framework#7192]
If you rename using artisan app:name from default 'App' to a completely different word like 'Jersey', everything seems to work as expected.

However if you rename using artisan app:name default 'App' to 'TestApp' (notice word 'App' carrying over into new app:name), it gives this error: http://puu.sh/fcHC3/d00ca744a7.png and my Http\Kernel.php file shows this as new namespace http://puu.sh/fcHPn/a0cf018335.png

Could there be a regex/replace issue here when the original app:name is contained within the new app:name?  Maybe app:name is doing a double replace for word 'App', so 'TestApp' becomes 'TestTestApp'?

**Comment by JerseyMilker** [comment]
Fixed?

**Comment by RomainLanz** [comment]
@JerseyMilker  As you can see a PR has been created to fix your problem. :)

**Comment by JerseyMilker** [comment]
@RomainLanz Okay thanks :)  Sorry, new to PR
