### ISSUE TITLE
Laravel installation got faulty [4.2]

### ISSUE THREAD

**Issue by rusma** [laravel/framework#7194]
http://stackoverflow.com/questions/28224467/artisan-migrate-broken-undefined-property

**Comment by rusma** [comment]
Fixed by rolling a back the vendor folder from an earlier copy. Might still be a bug. WIll post my laravel.log in the stackoverflow question

**Comment by GrahamCampbell** [comment]
Can you give us more information about the dependency versions please? Perhaps the lock file before and after?

**Comment by GrahamCampbell** [comment]
Closing due to human timeout.
