### ISSUE TITLE
Will there be RabbitMQ built in support for Laravel 5?

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#7195]
Will there be RabbitMQ support built into Laravel 5? If not, what's the best way to go about using RabbitMQ with Laravel 5?

**Comment by GrahamCampbell** [comment]
It's not planned, sorry. https://github.com/fintech-fab/laravel-queue-rabbitmq works on 4.2 atm. If it's useful to you, you could contribute to that repo and get them working on L5.

**Comment by michaeljs1990** [comment]
@GrahamCampbell is rabbitmq support purely a time issue or are other things at play here? I would be happy to contribute this component if it's purely a lack of developer time that is keeping it from being built out.
