### ISSUE TITLE
Model timestamps bug -- Laravel 4.2 

### ISSUE THREAD

**Issue by Aner-Git** [laravel/framework#7196]
class Model in  Illuminate\Database\Eloquent has a timestamps bug. 

create a model and set:
 
public $timestamps = false;

Insert a new record to the db. 
Pull the record via created model, eg:

$m = MyModel::find(1);

$m->touch() ;   <<< this fails with Unknown column 'updated_at' 

work around: overload touch method in your model to return nothing.

**Comment by JosephSilber** [comment]
How is that a bug? If you're not using timestamps, what are you doing calling `touch()` to begin with?

**Comment by Aner-Git** [comment]
1. Its a bug because  when you have an object of any Class, one should be able to call any method on it! Basic OO design. 
2. touch should be a no Op if not timestamps = false.
3. I'm not calling touch, but Im passing it to a 3 partly library which does call touch on it.  The 3rd party library IS thinking OO, and assume it can call any method on a Model.

**Comment by JosephSilber** [comment]
Yeah. Makes sense.

I create [a PR](https://github.com/laravel/framework/pull/7205) for it.

**Comment by GrahamCampbell** [comment]
Thanks @JosephSilber. @Aner-Git This is fixed in 5.0.0 which will be released early next week.
