### ISSUE TITLE
[Request]Run Migrations Separately

### ISSUE THREAD

**Issue by vahidstar** [laravel/framework#7201]
first of all  if there is a way to run migrations Separately  please leave a comment . 
if there is not  please read this  use case :

this feature becomes more important when it comes to production mode . consider the situation that you run your migration in production then after 1 month e.g. you wish to add new table to your application , so you cant just refresh the migration because of loss of data. so you have to install some packages such as phpmyadmin ... to add it manually and i dont believe this is a proper way to do such a thing. guys if you have any suggestions please share .

**Comment by gabrielkoerich** [comment]
Not sure if I understand, but if you need to create a new table, just create a new migration. Actually, that's what migrations are for.
