### ISSUE TITLE
Illuminate\Contracts\Cache\Repository - missing forever() method.

### ISSUE THREAD

**Issue by euantorano** [laravel/framework#7203]
The `Illuminate\Contracts\Cache\Repository` contract appears to be missing the `forever` method to store items indefinitely. This method is available in the class `Illuminate\Cache\Repository`.

Additionally, the comment for the `storeForever` method is a duplicate of the comment for the `sear` comment, which is likely incorrect:

```php
	/**
	 * Get an item from the cache, or store the default value forever.
	 *
	 * @param  string   $key
	 * @param  \Closure  $callback
	 * @return mixed
	 */
	public function rememberForever($key, Closure $callback);
```

**Comment by GrahamCampbell** [comment]
Add it in a pull then.

**Comment by euantorano** [comment]
@GrahamCampbell like the one referenced in this issue? https://github.com/laravel/framework/pull/7204

**Comment by euantorano** [comment]
Also, I'm not sure what the rememberForever() method does, so cannot possibly update the PHPDoc comment for it. Every class with that method has the same incorrect (as far as I can tell) comment.
