### ISSUE TITLE
orWhereHas not working correctly with nested relationships

### ISSUE THREAD

**Issue by flyingL123** [laravel/framework#7207]
There seems to be a bug with how the `orWhereHas` method works with nested relations. I believe that the `or` statement is being placed incorrectly in the generated sql.  Here's my StackOverflow link explaining the issue in detail:

http://stackoverflow.com/questions/28241584/laravel-orwherehas-not-working-as-expected

**Comment by GrahamCampbell** [comment]
What Laravel version please?

**Comment by flyingL123** [comment]
`Laravel Framework version 4.2.16`

But I'm using `4.2.*@dev` in my project.

**Comment by jarektkaczyk** [comment]
Done

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by flyingL123** [comment]
Does this mean the fix is now in the main 4.2 branch? Or not yet? Sorry, I'm pretty new to this process.

**Comment by GrahamCampbell** [comment]
I've closed the issue to help me keep track of what's been addressed. Further discussion can continue on the pull request.

**Comment by flyingL123** [comment]
Thanks. Is there any way for me to know when this gets merged in, or do I have to just come back and check?
