### ISSUE TITLE
Can’t use email queue in an event handler

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#7224]
When I try to queue an email in an event handler, the following exception is thrown:

> Maximum function nesting level of '100' reached, aborting!

Here is the offending class’s code:

```php
<?php namespace App\Handlers\Events;

use App\Events\OrderCreated;
use Illuminate\Contracts\Mail\Mailer;
use Illuminate\Contracts\Queue\ShouldBeQueued;
use Illuminate\Queue\InteractsWithQueue;

class SendOrderConfirmationEmail {

	/**
	 * Create the event handler.
	 *
	 * @param  Mailer  $mailer
	 */
	public function __construct(Mailer $mailer)
	{
		$this->mailer = $mailer;
	}

	/**
	 * Handle the event.
	 *
	 * @param  OrderCreated  $event
	 * @return void
	 */
	public function handle(OrderCreated $event)
	{
		$order = $event->order;

		$this->mailer->queue('emails.order.confirmation', compact('order'), function($message) use ($order)
		{
			$message->to($order->customer->getEmail(), $order->customer->getName());
			$message->subject('Your order confirmation');
		});
	}

}
```

Is this something to do with the `ShouldBeQueued` or `InteractsWithQueue` functionality, that it’s causing an infinite loop?

**Comment by GrahamCampbell** [comment]
Are you sure it's a loop, and not just that you actually have that many nested calls?

**Comment by martinbean** [comment]
@GrahamCampbell It’s an event raised from a command (`CreateOrder`). So the execution flow is:

* Dispatch queued command from controller action
* Command handler raises event
* Event listener *should* queue email, as above

It works if I `send` the email instead.

**Comment by GrahamCampbell** [comment]
You seem to be doing this wrong. I assume the issue is that you can't serialize the order variable. You should be queuing the entire event handler here, not queuing the mail sending.

**Comment by martinbean** [comment]
@GrahamCampbell I was trying to separate my order handling logic so that everything wasn’t stuffed in my create order command. I thought this was recommended best practice—how should I be doing it instead?

**Comment by GrahamCampbell** [comment]
I think you can have the event handlers themselves be async.

**Comment by martinbean** [comment]
@GrahamCampbell So are you saying I should be sending the message in my `SendOrderConfirmationEmail` event handler synchronously (with `send()`) because the handler itself is asynchronous and will be handled by the queue when it can?

**Comment by GrahamCampbell** [comment]
I'm saying if you implement the queuable interface and pull in the queuable entities trait you shouldn't have any issues.

**Comment by martinbean** [comment]
@GrahamCampbell I’ve created a queued event handler, and it’s now giving me the above exception message regardless whether I use `$mailer->queue()` or `$mailer->send()`.

**Comment by GrahamCampbell** [comment]
Yeh, you probably need to increase the max nesting level. In the next version of xdebug it's been set to 250 by default.

**Comment by martinbean** [comment]
@GrahamCampbell OK. How would I do that in the meantime?

**Comment by GrahamCampbell** [comment]
You can set the max function level in your php config.

**Comment by franzliedke** [comment]
@martinbean Can you show us the stack trace just before the error?

**Comment by martinbean** [comment]
@franzliedke I don’t really get that much of a helpful stack trace to be honest:

![screen shot 2015-01-31 at 20 26 39](https://cloud.githubusercontent.com/assets/167312/5989687/83f0c180-a987-11e4-8bed-d9026974f7ad.png)

**Comment by franzliedke** [comment]
Can you generate one using `debug_backtrace()`?

If this can happen easily with a standard Laravel install, we might have a problem...

**Comment by martinbean** [comment]
@franzliedke I’m not sure where I would put `debug_backtrace()` to get a relevant trace?

**Comment by franzliedke** [comment]
Right before the error usually happens?

**Comment by martinbean** [comment]
@franzliedke It’s the queued handler itself.

**Comment by martinbean** [comment]
Found someone else having the exact same issue (queuing email in an event handler): https://laracasts.com/index.php/discuss/channels/general-discussion/xdebug-max-nesting-level-reached

**Comment by askmatey** [comment]
I have the same issue as described above.

**Comment by askmatey** [comment]
@GrahamCampbell 

Regarding your https://github.com/laravel/framework/issues/7224#issuecomment-72331050

> You should be queuing the entire event handler here, not queuing the mail sending.

That's interesting. Can you provide a small example, how to enqueue the event handler?

**Comment by askmatey** [comment]
see issue: 8392

**Comment by askmatey** [comment]
#Num: #8392

**Comment by CreativityKills** [comment]
Im still  having this issue. If I implement the ShouldQueue interface and use the InteractsWithQueue trait, I get a unable to serialise closure error. This is strange.
