### ISSUE TITLE
Auth::attempt() only works with lowercase password field. 

### ISSUE THREAD

**Issue by ralph3991** [laravel/framework#7231]
`Attempt();` will not work if you have named the password field in your DB 'Password'.  It must be password.

**Comment by GrahamCampbell** [comment]
This is not a bug. You must use a lowercase p.

**Comment by ralph3991** [comment]
Can someone please include this in the laravel docs.  I beat my head up over this for hours ;(  I would hate for someone else go through the same exp.  Thank you for the quick reply, all is working now.

**Comment by joostvandermeijden** [comment]
I think it is not common to start the name of a database table with a capital so in my opinion it should not be added to the Laravel docs.
