### ISSUE TITLE
PHPUnit - Selenium Testing with Filters Disabled

### ISSUE THREAD

**Issue by mistakevin** [laravel/framework#7233]
I have a test that launches all of my selenium tests using Selenium Server and Selenium RC
```
<?php

class SeleneseTest extends PHPUnit_Extensions_SeleniumTestCase
{
    public static $seleneseDirectory = 'app/tests/selenium';

    protected function setUp()
    {
        $this->setBrowser('*googlechrome');
        $this->setBrowserUrl('http://localhost:8888/');
    }
}

?>
```
but since it is running in my `testing` environment, the filters are disabled in _Illuminate\Routing\RoutingServiceProvider_
```
protected function registerRouter()
{
	$this->app['router'] = $this->app->share(function($app)
	{
		$router = new Router($app['events'], $app);

		// If the current application environment is "testing", we will disable the
		// routing filters, since they can be tested independently of the routes
		// and just get in the way of our typical controller testing concerns.
		if ($app['env'] == 'testing')
		{
			$router->disableFilters();
		}

		return $router;
	});
}
```
Calling `Route::enableFilters();` or `$this->app['router']->enableFilters();` does not seem to work here. Can anyone think of a solution? Possibly extending _Illuminate\Routing\RoutingServiceProvider_ to disable the feature altogether or to permanently enable the filters somewhere else?

**Comment by GrahamCampbell** [comment]
Yeh, this was removed in L5. Please see https://github.com/laravel/framework/pull/6114.
