### ISSUE TITLE
Cashier not passing through tax_percent to Stripe

### ISSUE THREAD

**Issue by shealan** [laravel/framework#7235]
This call isn't passing through tax percent (although no error is thrown).

```
$this->user->subscription($input['plan'])->create($input['card'], [
    'email' => $this->user->email,
    'tax_percent' => 20
]);
```

However this raw Stripe call does pass it through successfully.

```
$customer = Stripe_Customer::create(array(
    'card' => $input['card'],
    'email' => $this->user->email,
));

$customer->subscriptions->create(array(
    'plan' => $input['plan'],
    'tax_percent' => 20
));
```

**Comment by lstables** [comment]
Did you manage to sort this? am having the same problem?

**Comment by shealan** [comment]
I was misunderstanding the process. When you set up a customer with a no card up front trial you don't pass their info to Stripe - you only do that when the trial finishes and they pay.

**Comment by lstables** [comment]
I pass a card up front then in stripe set it to have a 14 day trial, then after these 14 days they need to be billed X amount plus tax

**Comment by shealan** [comment]
Oh sorry I misread the question. No, the answer is that I didn't get an answer to this bug. It seems looking at the internal code of the Cashier function it isn't supported. I ended up having to use raw Stripe calls rather than Cashier. Would love someone to pull request and add the feature. It's a bit beyond me.

**Comment by lstables** [comment]
Yeah it's beyond me too, just on the Stripe IRC, looking for help, I'd submit a PR but can;t get to grips with Liferaft

**Comment by raphjutras** [comment]
I think this is a stripe documentation mistake... I am not able to set a tax_percent on a Customer object and automatically apply it to a new subscription... I wrote an email to stripe about that... Although, there is no returned error from the API when trying to set that value directly on customer..
