### ISSUE TITLE
[L5] \Config::set('session.driver', 'array') throw exception 

### ISSUE THREAD

**Issue by chareice** [laravel/framework#7250]
i just set `\Config::set('session.driver', 'array') ` then an error follow reponse

![q20150203-1 2x](https://cloud.githubusercontent.com/assets/1624785/6016929/58e75ae2-abc3-11e4-9056-719809f3c77a.png)

Anyone same with me?

**Comment by GrahamCampbell** [comment]
You probably need to set the config at an earlier point. Why do you need to change it on the fly anyway?

**Comment by chareice** [comment]
I want disable Set-Cookie header from laravel reponse, according to this issues https://github.com/laravel/framework/issues/726

**Comment by chareice** [comment]
taylorotwell said that

**Comment by GrahamCampbell** [comment]
Taylor didn't mean do that. Set it in your config file.
