### ISSUE TITLE
[Proposals] [5.1] Add Artisan Command 'db:setup', 'db:create' & 'db:drop'

### ISSUE THREAD

**Issue by RomainLanz** [laravel/framework#7256]
Hi everyone,

* `db:create` Create the database for the current environment.
* `db:drop` Drop the database for the current environment.
* `db:setup` Run a batch of other artisan commands: db:create, migrate, db:seed

Why not add these commands to the core of Laravel ?
You can see here a package made by @phurni who handle these : https://github.com/phurni/mortimer-db-setup

**Comment by GrahamCampbell** [comment]
I also maintain a package "Laravel-Core". I don't see this making it into the framework.
