### ISSUE TITLE
[5.0] cacheTags and remember of the Query\Builder

### ISSUE THREAD

**Issue by dakiesse** [laravel/framework#7259]
Where missing the methods cacheTags() and remember() from the Query\Builder?

**Comment by JosephSilber** [comment]
They were officially removed. You now have to cache them yourself using the cache class.

**Comment by dakiesse** [comment]
Why was this done?

**Comment by GrahamCampbell** [comment]
They were buggy with more advanced queries. Caching works better in repository decorators, or other patterns.
