### ISSUE TITLE
A bug in php artisan event:generate

### ISSUE THREAD

**Issue by lzhang43** [laravel/framework#7264]
I added the following event binding in `App\Providers\EventServiceProvider.php`

```
	protected $listen = [
		'App\Events\ThreadWasAdded' => [
			'App\Handlers\Events\GenerateNotification@handle'
		],
```

When I ran `php artisan event:generate`, here's what I got:

```
#	app/Events/ReplyWasAdded.php
#	app/Handlers/Events/GenerateNotification@handle.php
```

I'm not 100% sure, but it looks like the event handler file should be named `GenerateNotification`, and `@handle` indicates the method to be called. However, Laravel is currently generating a file called `GenerateNotification@handle.php`.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by EwanValentine** [comment]
+1

**Comment by Arrilot** [comment]
Why were both the issue and the PR closed?

It is a clear bug - we copypasty the example from official doc
http://laravel.com/docs/5.0/events

1)
```php
protected $listen = [
    'App\Events\PodcastWasPurchased' => [
        'App\Handlers\Events\EmailPurchaseConfirmation@handle',
    ],
];
```

2) php artisan event:generate
and it's broken

Even if you treat this as a documentation bug it should be fixed before closing this issue imho

**Comment by GrahamCampbell** [comment]
Not sure. Taylor's closed the pull.

**Comment by Arrilot** [comment]
I think that he probably closed the PR because you had closed the issue few days before

**Comment by GrahamCampbell** [comment]
@Arrilot Not correct at all. I close issues when a pull is available. This means we only have one thing open, to manage, at once.

**Comment by Kyslik** [comment]
Its still not fixed or am I missing something.

**Comment by Arrilot** [comment]
@Kyslik the doc was changed so it looks like event generator is not meant to be compatible with `@method`. Use only class names.

**Comment by Kyslik** [comment]
I added this for test:

    'App\Events\UserLoggedIn' => [
            'App\Handlers\Events\UpdateLastLogIn',
        ],

Ran the command `$ php artisan event:generate` but only Events/UserLoggedIn was created.

**Comment by ferry77** [comment]
Same issue, I follow http://laravel.com/docs/5.0/events
put this in EventServiceProvider.php

	protected $listen = [
		'App\Events\PodcastWasPurchased' => [
			'App\Handlers\Events\EmailPurchaseConfirmation',
		],
	];

then run 

	$ php artisan event:generate
	Events and handlers generated successfully!

But no event/handler file generated, any one can help on this?

Thanks!

**Comment by gothick** [comment]
@ferry77 Had you previously manually created a PodcastWasPurchased event? I had that problem, and finally figured out that I needed to `php artisan clear-compiled` before I ran `php artisan event:generate` to get it to work—I assume it was still seeing the previously-generated events classes that I'd deleted.

**Comment by chonla** [comment]
@gothick Thanks. I had the same problem with @ferry77 and your advice solved the issue.

**Comment by ferry77** [comment]
@gothick thanks for your clue mate.. :)
