### ISSUE TITLE
[5.0] Docs on the website link to 'master' version

### ISSUE THREAD

**Issue by thasmo** [laravel/framework#7265]
When selecting `5.0` from the Docs menu, all sub-sections on the left side link to the `master` version.

**Comment by filipac** [comment]
This is not really a framework issue, it is a docs one. And also it has been fixed: https://github.com/laravel/docs/commit/4deba2bfca6636d5cdcede3f2068eff3b59c15ce

**Comment by thasmo** [comment]
Yeah, sorry - docs has no issue tracker.
