### ISSUE TITLE
Proposal: Guidelines for translating docs

### ISSUE THREAD

**Issue by rscafi** [laravel/framework#7266]
Now that Laravel 5 is out and the docs are pretty much updated/stable, it would be awesome if an official form of translating docs and website were created.
By doing it, we, developers from all around the world, could help Laravel spread even more. I'm sure that are many many people that could help. 

I propose this so we can know that our work would be incorporated into official documentation.
I found [this project](https://crowdin.com/project/laravel-documentation) that started translating docs, but, even it is still active, it lacks people for helping out.

## A few thoughts:
- It would be nice to have a plataform to manage translations (Like [Transifex](https://www.transifex.com/) or [Crowdin](https://crowdin.com/) - both are free for open source projects!), because I think that translating with forks would make it hard for people to contribute and manage.
- Some well-known folks at the community from another countries could monitor the translations, to make sure that docs' quality matches the main translation.
- A channel at larachat could be created to centralize translators and information in general

For reference: [PHP Manual Contribution Guide](http://doc.php.net/tutorial/)

Is it a valid proposal? If it isn't, please let's work on it to make it happen. Any thoughts?

**Comment by vluzrmos** [comment]
+1

**Comment by VitorArjol** [comment]
+1

**Comment by devfake** [comment]
+1

**Comment by zecsystem** [comment]
+1

**Comment by johnathanmdell** [comment]
+1

**Comment by rscafi** [comment]
For reference: [PHP Manual Contribution Guide](http://doc.php.net/tutorial/)

**Comment by aFreshMelon** [comment]
I am German and can provide a German translation.

**Comment by gilvaju** [comment]
+1

**Comment by webkr** [comment]
+1

**Comment by andreoav** [comment]
:+1:

**Comment by johnidm** [comment]
+1

**Comment by ianrodrigues** [comment]
+1

**Comment by marcelofabiano** [comment]
+1

**Comment by sputinyk** [comment]
+1

**Comment by eduardostuart** [comment]
+1

**Comment by rbadillap** [comment]
+1

**Comment by joaoeduardo** [comment]
+1

**Comment by brendomaciel** [comment]
+1

**Comment by Fuhrmann** [comment]
+1

**Comment by caiocutrim** [comment]
+1

**Comment by flavianohonorato** [comment]
+1

**Comment by helfreire** [comment]
+1

**Comment by t-vieira** [comment]
+1

**Comment by SOSTheBlack** [comment]
+1

**Comment by overtrue** [comment]
+1

**Comment by xiaobeicn** [comment]
+1

**Comment by angusty** [comment]
+1

**Comment by daids** [comment]
:+1:

**Comment by LeandroNascimento** [comment]
+1

**Comment by Baraldi** [comment]
+1

**Comment by elton869** [comment]
+1

**Comment by raphapaulino** [comment]
+1

**Comment by luciano-jr** [comment]
+1

**Comment by williamoliveira** [comment]
+1

**Comment by RomainLanz** [comment]
https://readthedocs.org/ Can be a good start.

**Comment by vvinhas** [comment]
+1

**Comment by SOSTheBlack** [comment]
+1

*Jean Cesar Garcia*
Desenvolvedor Web

jeancesargarcia@gmail.com
Call: 55 - 16 - 9-9280-8021


2015-02-20 15:47 GMT-02:00 Vinicius Vinhas <notifications@github.com>:

**Comment by kiaking** [comment]
:+1: 

I really want to help this out. I mean how will this thread work? Are we waiting for Taylor's response?

**Comment by minkbear** [comment]
+1

**Comment by Pyton** [comment]
+1

**Comment by montogeek** [comment]
I am currently translating the Laravel docs to Spanish [docs](https://github.com/montogeek/laravel-docs-es), [reader](https://github.com/montogeek/laravel-docs-reader).

**Comment by jaschweder** [comment]
+1

**Comment by sebastianbarfurth** [comment]
I created [a fork](https://github.com/sebastianbarfurth/laravel-docs-de) for a German translation if anyone wants to help with that. I'll be contributing to it occasionally.

**Comment by taylorotwell** [comment]
The community can organize this as needed. I don't plan to personally take any official action, but welcome any community initiatives to translate the documentation.

**Comment by vluzrmos** [comment]
:-1:

**Comment by lemesdaniel** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44e.png)

**Comment by montogeek** [comment]
@taylorotwell I understand your position. Just keep the hard work on Laravel :)
