### ISSUE TITLE
Response::download doesn't work with file created with tmpfile()

### ISSUE THREAD

**Issue by flyingL123** [laravel/framework#7267]
After creating a file using `tmpfile()`, I am unable to force a download response using `Response::download()`.  Doing so leads to an `AccessDeniedExpection`.

Is this a bug or am I misunderstanding how the download response is supposed to work?  Here's my StackOverflow question with the code details:

http://stackoverflow.com/questions/28332313/laravel-access-denied-exception-with-file-download-response

I'm using `Laravel Framework version 4.2.16`.

**Comment by GrahamCampbell** [comment]
Symfony is handling this for us. Any questions about usage belong on the forums. Sorry, but there'd be simply far to many to process on github.
