### ISSUE TITLE
[L5] ->paginate() API is still too complicated

### ISSUE THREAD

**Issue by daftspunk** [laravel/framework#7272]
I understand there have been some improvements to the paginate() API and internals, yet I think there has been an oversight. What if someone has two or more paginations on a single page?

I'm not sure why the current `resolveCurrentPage()` and `currentPageResolver()` needs to be so complicated, but neither of these things are useful when a person simply wants to explicitly define what the current page is...

Can I propose we make it stupidly easy to set the current page number by passing a 2nd argument?

```
// Take 25 records, we are on page 3
$model->paginate(25, 3);
```

Columns can still be plucked as either the 2nd or 3rd argument, so long as 2nd arg is an array, see prototyped code:

    public function paginate($perPage = 15, $currentPage = null, $columns = ['*'])
    {
        if (is_array($currentPage)) {
            $columns = $currentPage;
            $currentPage = null;
        }

        if (!$currentPage) {
            $currentPage = Paginator::resolveCurrentPage();
        }

        if (!$perPage) {
            $perPage = $this->model->getPerPage();
        }

        $total = $this->query->getCountForPagination();
        $this->query->forPage($currentPage, $perPage);

        return new LengthAwarePaginator($this->get($columns)->all(), $total, $perPage, $currentPage, [
            'path' => Paginator::resolveCurrentPath()
        ]);
    }

Let me know if you want a PR

**Comment by juukie14** [comment]
I see it as a negative thing if I have to specify the current page every time.

**Comment by daftspunk** [comment]
Negative or not, it is crazy difficult to do without jumping through many hoops. This proposal suggests it is optional to supply one, not a requirement.

**Comment by daftspunk** [comment]
I  should note it was possible to do this in Laravel 4 with the following:

```
App::make('paginator')->setCurrentPage($page);
$model->paginate($perPage);
```

In Laravel 5 we are locked out, and I can only think of a really dirty solution:

```
$_POST['page'] = $page;
$model->paginate($perPage);
```

**Comment by GrahamCampbell** [comment]
Why not `$model->paginate(Input::get('page'));` or something?

**Comment by GrahamCampbell** [comment]
> In Laravel 5 we are locked out

It was redesigned to remove coupling with the other components.

**Comment by daftspunk** [comment]
> Why not $model->paginate(Input::get('page')); or something?

There is a distinction between "results per page" and "the current page we are on", I would be very happy with this of course:

```
$model->paginate(25, Input::get('page')); 
```

> It was redesigned to remove coupling with the other components.

I see why it was redesigned and I fully support the direction, of course! Since we've moved away from a singleton / container based object, it has essentially locked us out from the paginate object used by Eloquent's paginate() method, since it is fully implemented by the internals.

**Comment by daftspunk** [comment]
Alternatively, what about something like this?

```
// Take 25 records, we are on page 3
$model->pageinate([25, 3]);
```

That way we don't have to get all magical with the method arguments.

**Comment by GrahamCampbell** [comment]
I'm not opposed to these changes particularly. Perhaps send a proposal implementation to 5.1 to allow Taylor to see. :)
