### ISSUE TITLE
[website] api docs

### ISSUE THREAD

**Issue by pk-informatics** [laravel/framework#7274]
hi,

The Website api link links to the L 4.2 api and the L 5.0 stable api docs are not available.

Kind regards,

**Comment by bart** [comment]
It's available under http://laravel.com/api/master/index.html I think

**Comment by pk-informatics** [comment]
Of course, but its not clear if it is linked against the github master or L5 tag

**Comment by GrahamCampbell** [comment]
Yeh, we know. Taylor will be generating them soon. We discussed this yesterday actually. :)

Thanks anyway.
