### ISSUE TITLE
Auth: Basic auth not working and no solutions are working

### ISSUE THREAD

**Issue by smaxwellstewart** [laravel/framework#7279]
Hi,

I am running using Laravel 4.2 in Homestead enviroment.

I tried to test an API endpoint that is protected with the standard `auth.basic` filter:

```php
Route::filter('auth.basic', function()
{
	return Auth::basic();
});
```

I discovered this was a common issue and so tried adding the two lines suggested by the 4.2 docs, to `public/.htaccess`:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Fix basic auth
    RewriteCond %{HTTP:Authorization} ^(.+)$
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

</IfModule>
```

This does not fix the issue, i just get the basic auth prompt forever. Please help!

**Comment by dangreaves** [comment]
Your credentials are probably failing. Work your way down from [Illuminate\Auth\Guard.php#L285](https://github.com/illuminate/auth/blob/master/Guard.php#L285). If attemptBasic() is returning false, the likelihood is that Guard cannot validate your credentials.

**Comment by smaxwellstewart** [comment]
Do you mean i am getting my username/password wrong?

My credentials work perfectly for the ordinary auth filter. I validate this by logging in to my application using ordinary auth. Everything works I get my cookie and I can view the protected API endpoint. 

But if I logout and try and validate on the API route directly it does not work.

**Comment by smaxwellstewart** [comment]
I am extremely confident this is not a case of invalid credentials. I checked like 20 times!

**Comment by dangreaves** [comment]
Do you use a `username` or an `email` column for your auth? By default the basic filter will look for an `email` column unless something different is specified as the first parameter to `Auth::basic()`.

**Comment by smaxwellstewart** [comment]
AHa! This fixes it.

Is there a way to use username?

**Comment by kreitje** [comment]
Change

```
Route::filter('auth.basic', function()
{
    return Auth::basic();
});
```

To
```
Route::filter('auth.basic', function()
{
    return Auth::basic('username');
});
```

**Comment by dangreaves** [comment]
If you mean telling Guard to look at your `username` column, it's just:

    return Auth::basic('username');

**Comment by smaxwellstewart** [comment]
Thank you!
