### ISSUE TITLE
Eager loading nested relationships 

### ISSUE THREAD

**Issue by greenleafmedia** [laravel/framework#7283]
Hi -

I'm trying to eager load some nested relationships.  When I go two deep like the example in the docs: `Book::with('author.contacts')->get();` everything works as expected.  When I try to go one more level deep `Book::with('author.contacts.company')->get();` the first two levels are eager loaded, but my company model is back to being loaded as normal.

Am I supposed to be able to eager load nested relationships many levels deep or does it only work for two levels deep?  I can't tell if this is something I'm doing wrong or the normal functionality of Laravel.

**Comment by GrahamCampbell** [comment]
I don't think we support this.

**Comment by greenleafmedia** [comment]
Sounds good.  Thanks for the clarification.

**Comment by MaartenStaa** [comment]
Reading through the Eloquent query builder code on 4.2, it seems like this should work? Is this documented somewhere?
