### ISSUE TITLE
[L5] DecryptException in Encrypter.php line 142: Invalid data.

### ISSUE THREAD

**Issue by FabioAntunes** [laravel/framework#7287]
When passing the token through the header for AJAX requests eg:
```javascript
headers: {
  'X-XSRF-TOKEN': '{{ csrf_token() }}
 }
```

Since we are using the same principle as the hidden form input, decrypting the token in ```VerifyCsrfToken``` makes no sense at all, eg:
```php
protected function tokensMatch($request)
{
	$token = $request->session()->token();

	$header = $request->header('X-XSRF-TOKEN');

	return StringUtils::equals($token, $request->input('_token')) ||
	       ($header && StringUtils::equals($token, $this->encrypter->decrypt($header)));
}
```

In fact it throws an exception:
```DecryptException in Encrypter.php line 142: Invalid data```

**Comment by gokigoks** [comment]
How do I work around this? same problem here

**Comment by lukasgeiter** [comment]
I think this has been fixed with [this PR](https://github.com/laravel/framework/pull/7528). Is your Laravel installation up to date?
