### ISSUE TITLE
[L5] Don't hardcode the public path

### ISSUE THREAD

**Issue by phanan** [laravel/framework#7292]
The `public` path for the app is being hardcoded in Laravel 5, as shown in [Application.php#L266](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L266). This makes certain setups fail, for example mine:

```
app
bootstrap
...
.htaccess
index.php
```

(Notice that I've moved the `public` content up to the root).

I've been using this setup from L4 due to it being runnable on shared hosting envs -- of course certain `.htaccess` rules need to be added to secure the framework files and folders. With this change in L5, `artisan serve` fails:

```bash
~/w/deploy5 $ ./artisan serve 
Laravel development server started on http://localhost:8000
Directory /Users/an/www/deploy5/public does not exist.
```

If I start the PHP server manually with `php -S localhost:8000`, it works, but I'm not sure if certain calls to the public path will succeed.

Question: Is this something we can fix/work around in the next minor version of Laravel? Or it's just me missing something here?

**Comment by barryvdh** [comment]
See #7108 and http://mattstauffer.co/blog/extending-laravels-application

**Comment by phanan** [comment]
That's fast, thanks!

**Comment by overtrue** [comment]
This approach is really hard to understand, but also dangerous behavior.

**Comment by phanan** [comment]
How is it dangerous?

**Comment by overtrue** [comment]
If your web server permissions did not control well, then the hacker will be able to directly access http://youdomain.com/another.php, on the contrary, the $ document_root control more easily controlled in the public directory.
