### ISSUE TITLE
[L5] ->remember() alternative broken (possible PEBCAK)

### ISSUE THREAD

**Issue by daftspunk** [laravel/framework#7293]
```
// Worked in L4
$post = Post::remember(1440, 'test')->find(1);

// Alternative L5 throws error
Cache::remember('test', 1440, function(){
    return Post::find(1);
});
```

Error: **Serialization of 'Closure' is not allowed**

Trace:

```
1 in FileStore.php line 104
2 at serialize(object(Post)) in FileStore.php line 104
3 at FileStore->put('test', object(Post), '1440') in Repository.php line 141
4 at Repository->put('test', object(Post), '1440') in Repository.php line 197
5 at Repository->remember('test', '1440', object(Closure))
6 at call_user_func_array(array(object(Repository), 'remember'), array('test', '1440', object(Closure))) in CacheManager.php line 312
7 at CacheManager->__call('remember', array('test', '1440', object(Closure))) in Facade.php line 216
8 at CacheManager->remember('test', '1440', object(Closure)) in Facade.php line 216
9 at Facade::__callStatic('remember', array('test', '1440', object(Closure))) in index.htm line 13
10  at Cache::remember('test', '1440', object(Closure)) in index.htm line 13
[...]
```

**Comment by GrahamCampbell** [comment]
Yeh, this is a known issue, and there's not much we can really do. I'd suggest just caching your model attributes rather than the entire model.

**Comment by JoostK** [comment]
How does the model reference a Closure? Perhaps implementing `__sleep` can prevent it from being serialized, however that may get you an incomplete model after deserialization.

**Comment by daftspunk** [comment]
For anyone who stumbles across this, @GrahamCampbell is suggesting something like

```
$post = new Post(Cache::remember('test', 1440, function(){
    return Post::find(1)->toArray();
}));
```

I'm curious to know how the previous implementation worked? I can't seem to find out the magic ingredient. Was it simply caching the DB results then populating the Model as we are doing above?

**Comment by GrahamCampbell** [comment]
> I'm curious to know how the previous implementation worked?

The issue was it never worked properly, lol.

**Comment by GrahamCampbell** [comment]
> How does the model reference a Closure?

It doesn't. When you try to serialize it, php will basically try to serialise the entire container. That's where the issue is.

**Comment by JoostK** [comment]
So, then it does, through the container.

**Comment by GrahamCampbell** [comment]
> So, then it does, through the container.

?

**Comment by GrahamCampbell** [comment]
The container obviously contains objects with closures in it, like the file cache repository.

**Comment by JoostK** [comment]
I asked how a model has a reference to a closure. You answered it doesn't, but that can't be as we actually serialize a closure somewhere. I sure understand that the container contains loads of closures, so then the answer would have been that a model has a reference to the container and through that also references closures.

**Comment by daftspunk** [comment]
Sad to see this stuff go, ideally it would be awesome to cache the query results and not the model object (highly inefficient). Caching the DB query result can only *really* be done at the Connector level, I'm sorta scratching my head on how else this can be done.

I think I will just mourn the loss of a really cool feature and move on! =)

**Comment by GrahamCampbell** [comment]
@JoostK The model class has a static dispatcher property that contains the event dispatcher instance. That event dispatcher has a property containing a container instance. That's where the problem lies. Hope I explained this better this time. :0

**Comment by GrahamCampbell** [comment]
* :)
