### ISSUE TITLE
[L5] Adding global middleware with service providers.

### ISSUE THREAD

**Issue by Beanow** [laravel/framework#7294]
While `Route::middleware($name, $class)` can be used to add route middleware, I don't see a good way of adding global middleware through service providers.

Currently it seems that modifying `Kernel`'s `$middleware` attribute in a project is the only way.

This adds more steps to the installation instructions for my package than I would like.

**Comment by barryvdh** [comment]
Yes, would like that too.

I think the argument against that was that it would be difficult to manage the order of the middleware.

**Comment by Beanow** [comment]
Ah whoops, I see this is a duplicate of #6211.
