### ISSUE TITLE
Cannot share view variables that depend on session

### ISSUE THREAD

**Issue by lazychaser** [laravel/framework#7297]
Session is started using middlewares _after_ every service provider is booted, so if I try to access currently authenticated user in `boot` method to share it between views, the session isn't started yet so user is inaccessible.

To handle this I create wildcard view creator:

```php
View::creator('*', function ()
{
  static $shared = false;

  if ($shared) return;

  // share view vars...

  $shared = true;
});
```

Is there a better way?

**Comment by GrahamCampbell** [comment]
Yeh, don't use a closure, but an object bound as a singleton.

**Comment by lazychaser** [comment]
You're not following me. Try adding such code to `AppServiceProvider::boot`:

```php
$this->app['view']->share('user', $this->app['auth']->user());
```

You'll always get null even if the user successfully logged in. That happens because session is started in SessionStart middleware that is executed **after** the application is booted.

My only solution is to add a wildcard view creator and use static variable to make sure that required variables are shared only once.

**Comment by GrahamCampbell** [comment]
I can't replicate. It's working fine for me https://github.com/StyleCI/StyleCI/blob/master/app/Composers/LoggedUserComposer.php.

**Comment by lazychaser** [comment]
It works fine with view composers, of course, but I need global view variables that will be available for every view (`$currentUser`, `$signedIn`, etc). This is done by using shared variables.

**Comment by GrahamCampbell** [comment]
Maybe share a closure?

**Comment by lazychaser** [comment]
I could use helper functions instead =) The problem is that you can't access session data in `boot` method, not view variables, it's just a case.

**Comment by ibrasho** [comment]
Use `Illuminate\View\Factory::compose('*', ComposerClassHere)`.

This will be called on all views. You can share all the variables you want there.
