### ISSUE TITLE
Laravel 5 fails after install and using app:name or clear compile 

### ISSUE THREAD

**Issue by vincej** [laravel/framework#7302]
Just spent a day and half trying to install L5. 

A clean install gives you the L5 welcome screen. However as soon as you try to do a php artisan app:name the welcome screen disappears. The new name spaces all line up with new psr-4 name. Tried composer dumpautoload. 

So more clean installs. This time, I just run clear-compile and again the same failure. 

Ok - so I am advised to manually delete framework/storage files -> no benefit. 

I'm using Ubuntu 14.4 LTS / Apache / MySql

View the whole laracasts discussion here: https://laracasts.com/discuss/channels/general-discussion/upgrading-to-l5-and-getting-class-not-found-on-composer-update?page=1

**Comment by GrahamCampbell** [comment]
There are a few similar issues here. This is probably still better to the discussed on the forums.

**Comment by vincej** [comment]
This issue goes beyond the skills of the forums. The very best developers on the forums ( ie bashy bestmomo nolros ) are not able to remedy it. There is a track record of problems in this area.  Unfortunate that you do not recognise there is flaw in the s/w which needs to be fixed.

**Comment by vincej** [comment]
May I add that in it's current form Laravel 5 is unusable as a commercial product amongst corporate users.

**Comment by GrahamCampbell** [comment]
This is not an issue with laravel, but just you using it wrongly. To be totally honest, I'd never recommend people to use the app:name command due to how it works, and the clear-compiled command will of course fail if the compiled file is dodgy. That's been an issue since 4.0.

**Comment by vincej** [comment]
Graham - Thank you for your rapid reply. Look, you are young, and naive. Let me help you: 

For starters, never blame the user. After all you are the architect of the product, and it is *your* responsibility to foresee how users intend to make use of it. For a something to be called a "working commercial product" it needs: 

1) To work out of the box. Laravel 5 does not work out of the box. 
2) The documentation needs to reflect the functionality of the product - Laravel 5 docs do not come even close meeting that criteria. 
3) It needs to have been thoroughly tested with advertised features. app:name is one of those features. Disagree ?? You had better tell Jeffrey Way, for he is teaching everyone on it's use. More over if it does not reliably work why is in the product ? Same point with clear-compile. 
4) It needs to be reliable. My clients runs user populations in the 1,000's ... Laravel 5 will not even reliably install on a Ubuntu platform. 

A this stage I can not advise any of my customers to use L5. It is not a product ready for prime time. It appears to have been released too early. A point over which you appear to be in denial.  I would suggest that you get involved in the forums to experience the current frustration of real commercial developers working with L5.  It would give you valuable experience of what is really going on. If a reasonably educated user can not deploy a software "product" without issues, it is never the fault of the user - it is always bad design, bad code, bad documents and bad testing. But do not ever blame the user. 

Cheers !

**Comment by GrahamCampbell** [comment]
> To work out of the box. Laravel 5 does not work out of the box. 

It works fine for me, and most other people it seems, so that statement isn't really true.

> The documentation needs to reflect the functionality of the product - Laravel 5 docs do not come even close meeting that criteria. 

Not quite sure what you mean. Could you point out some areas please.

> It needs to have been thoroughly tested with advertised features

app:name is rubbish by design imo. Tests wouldn't help there.

> It needs to be reliable. My clients runs user populations in the 1,000's ... Laravel 5 will not even reliably install on a Ubuntu platform.

We're open for pull requests if there are specific things you want fixing.

**Comment by vincej** [comment]
Graham - 

Look, "working fine for me" is not an excuse. Get on the forums, and experience what is going on. Some of the very best devs. on the forums who have decades of knowledge can not resolve the install problem that I refer to and a multitude of other problems. The forums should be empty. Do you have any real interest at all in the user base ? To just dismiss their experiences out of hand is arrogant and naive. You know, I forgive you for being an A level student. But if this is not an A level exercise. Real companies with real cost over heads are relying on this to work *without having to jumps through hoops of fire* 

Documentation: Try using the 4.2 > L5 upgrade docs. Use them verbatim ... not what you think they say, or what you hope they say .. but use them for what *do* say. 

App:name : well if it is rubbish, then why is it there ? take it out immediately and have Taylor make an announcement not to use it. Same with clear-compile. Whilst we are at it .. what else is rubbish in L5 ? 

Pull requests: 
1) Get L5 to install without errors - all the time, every time, not just in your time.
2)  Get l5 to accept L4.2 code without errors. 
3) Get your docs cleaned up. 

Lastly - Never blame the user. If it's your product, YOU make it work. 

Cheers !

**Comment by kaidesu** [comment]
Hi @vincej,

There's a few issues I find with the approach you're taking on this matter.

1) You say many people are unable to install Laravel 5 and get it working, but you only linked to a thread you created about this very same (Github) issue. As someone who is not part of the core dev team behind Laravel, I've had no issues getting L5 working from a fresh install (and I've been using it both personally and professionally within a company without issues).

2) The official development environment for Laravel is Homestead. The fact that you're using your local installation of Apache and PHP on your machine leaves a lot of questions and unknowns about your local set up that we (and I mean "we" in the sense of anyone trying to help you out) can't work within.

3) Your "Get L5 to accept L4.2 code without errors" point doesn't really make since. There's a reason why this is called Laravel **5** and not Laravel *4.3*. There are breaking changes you must overcome to upgrade existing projects - there's no other way around this.

---

@GrahamCampbell, saying `app:name` is rubbish and telling people not to use it is certainly not a response you should be throwing out being a part of the core team behind Laravel.

---

I hope you both can take this as professional criticism and not as an attack on either of you.

With that, I do believe this is better discussed on the forum. If you experience this issue with a clean install of L5 while using Homestead, then I believe it is a viable issue to be reported here.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell, saying app:name is rubbish and telling people not to use it is certainly not a response you should be throwing out being a part of the core team behind Laravel.

I'm telling you my honest opinion. I wouldn't use it.

**Comment by vincej** [comment]
Hi @kaidesu Thank you very much for your comment. I can  not agree in any manner. I will take your points one by one: 

1) Congratulations on getting it to work.  As I said on Graham, "it works for me" is not an excuse. Certainly not if Taylor expect this to be a real commercial product. The proper response to a problem is "I will look into that for your" or "let me help you". Not .. "you are to blame"., and by association the best devs on the forum. Get involved on the forums - find out the frustration. Find out the problems. _Add value._  

2) This point is total absurd non sense. Are you seriously telling me that come deployment, I have to have Homestead underneath it ? Get serious.  L5 has certain requirements. They are published. If my platform meets those requirements and yet L5 is will not run, then again it is a flawed product. 

3) Have you actually read these posts, or the forum link ?? I don't think you have.  Let me repeat: the *upgrade* docs 4.2 > 5 are flawed. They do not work.

**Comment by brunogaspar** [comment]
@vincej The frustration of not getting something to work as we would expect is understandable, and i do understand you, been there, but your behavior of coming here shooting bullets and calling someone arrogant and naive is not the way to go my friend. 

Not judging you, but relax, we're here to help :)

@GrahamCampbell behavior could be better when handling issues and not close them giving that kind of replies, but hopefully he learned something new today.

Anyway, i've read the whole thread on Laracasts and seems that no one could figure out your issue.

If you want i can personally help you to debug your issue, just let me know.

**Comment by vincej** [comment]
@brunogaspar thanks for your comment... fyi ... Garham is 17. 

I have been in IT for 30 years ... I think I know what I am talking about.

**Comment by brunogaspar** [comment]
I'm aware of his age @vincej and i don't believe anyone said you don't know what you're talking about, but, we all make mistakes :)

Let's just focus on figuring out why you're having that issue and leave the rest behind, we don't get any benefit on following the dark.

**Comment by vincej** [comment]
@brunogaspar  Thank you for your offer of help . Very professional. 

I wish I could say that I have made a mistake.  When you have Bashy and Bestomo and Nolros  - 3 of the best devs on the forum *also* reporting problems and also unable to cure my problem, I think that the sensible thing for Graham et al to say, is "gosh ... we have a problem here".

Many thanks for your offer ! Cheers !  Maybe see you on the forums.

**Comment by brunogaspar** [comment]
Don't worry about it :)

**Comment by overtrue** [comment]
> I have been in IT for 30 years ... I think I know what I am talking about.

Age does not mean the ability.

**Comment by vincej** [comment]
Disagree - age does not determine intellectual horsepower, but age determines judgement. Good judgement leads to better decision making.

**Comment by overtrue** [comment]
Facts have proved that only you and some of the novice user with these problems, especially those who have not carefully read the document.

**Comment by jacobmarshall** [comment]
I'd say that this discussion is best had on the forums (and this issue locked), not here, before it ends up being a mass of conflicting opinions. This sort of dramatic negativity is so unprofessional, regardless of age or experience.

**Comment by vincej** [comment]
@overtrue excuse me  ...are  you saying that bashy is a "novice" or bestmomo. Do you know who you are talking about ? You are talking about people who have the same level of knowledge as Jeffrey Way. 

@jacobmarshall I agree 100% - All I wanted when I reported this issue today, was to be taken seriously and not taken as a "novice". Many thanks !

**Comment by vincej** [comment]
@overtrue  do you really believe that bashy and bestomo are novices ? These are people with the same level of knowledge as Jeffrey Way. 

@jacobmarshall - Agreed. All I wanted when this was originally posted to be taken seriously and not dismissed as a novice. Many thanks !

**Comment by overtrue** [comment]
@vincej ok, I just think your issue is very strange for me, I use it for two years, I have tried many kinds of usage, why do none of these Issue?

**Comment by vincej** [comment]
Sure - I have been using L4.2 for 6 months and it works very well. L5 was released only 2 days ago. It is L5 which has the problems.
