### ISSUE TITLE
Model::whereHas not working

### ISSUE THREAD

**Issue by onefasteuro** [laravel/framework#7309]
I have a morph relationship set up, it's working totally fine when accessing it directly. though where I try to run whereHas to restrict the result, it comes back as 
Column not found: 1054 Unknown column 'bpi_athletes.' in 'where clause' (SQL: select * from `bpi_athletes` where (select count(*) from `bpi_athletes` where `bpi_athletes`.`article_id` = `bpi_athletes`.`` and `active` = 1) >= 1)

The query on my end is:
App\Models\Eloquent\Athlete::whereHas(
					'article', function($q)
					{
						$q->where('active','=',1);
					})->get() );

**Comment by JeroenVanOort** [comment]
Could you please post your definition of the relationship? That makes it easer for anyone to reproduce your problem.

**Comment by GrahamCampbell** [comment]
There were fixes to this stuff in the `4.2.*@dev` version. Try that, or `5.0.*` and if it's still a problem, get back to me. Also, try looking at all the previous issues related to this. There are quite a few.
