### ISSUE TITLE
FatalErrorException when calling action() with a non-existing route results is vacuous

### ISSUE THREAD

**Issue by dhardtke** [laravel/framework#7310]
In Laravel 4 you could easily see where in your code (template i.e.) you have called URL::action() and with what Controller and Method as parameter you called it, so you could easily find that and fix it...

now in Laravel 5, all you get is:
> Call to a member function domain() on null

and the stack trace isn't helping either.

**Comment by GrahamCampbell** [comment]
Looks like you're using it wrong. Ask on the forums.

**Comment by dhardtke** [comment]
I don't think so, but thank you for closing the issue without asking for more details.

Anyway:
If I write this in my code:
```php
action("DummyController@nonExisting");
```
I expect to get an exception that tells me where I called action() and with what parameters I called it *and most importantly* telling me, that it cannot find that route.
But I get
> Call to a member function domain() on null

**Comment by GrahamCampbell** [comment]
> but thank you for closing the issue without asking for more details.

I shouldn't need to ask. I should have just straight closed this without comment due to insufficient info.

**Comment by dhardtke** [comment]
Now you have the info.
In L4 we got a precise Exception, and now we get this rubbish...

**Comment by GrahamCampbell** [comment]
Your info means you are indeed using this wrong. That message you provided is the expected behaviour. Sorry.

**Comment by dhardtke** [comment]
http://laravel.com/docs/5.0/helpers#urls
```php
action('HomeController@getIndex', []);
```
I am not using "action()" wrongly...

**Comment by siavash13** [comment]
I am suffering from the same issue as well, I have this `{{ action('MyController@methodName') }}`
which used to work in Laravel 4.2 but it doesn't work anymore in Laravel 5 and I get the following error
`Call to a member function domain() on null`

**Comment by siavash13** [comment]
mine issue is solved now this error comes up when there is some namespace issue, for some reason I had to change the namespace in the `action` method the one which used to work for laravel 4 doesn't work here

**Comment by mikerogne** [comment]
What OP is saying is that in L4 if you specified a route and it did not exist, it would throw an exception that the route does not exist. Whereas now, it fails in a much less-obvious way.

Can we please not close stuff without more than .02 seconds of thought? These are real issues that affect the community, and seriously a LOT of the folks are starting to feel shut out because of this type of behavior.

**Comment by dhardtke** [comment]
Alright, at least now theres #7424 going on
