### ISSUE TITLE
No way to use a custom template with the Paginator anymore

### ISSUE THREAD

**Issue by dhardtke** [laravel/framework#7311]
In Laravel 4 we could easily use a custom template for the Paginator and customize the resulting markup by that.
Now, in Laravel 5 we can't (at least not that easy).

In Laravel 4 we could configure the "pagination" array item in "app/config/view.php" or use the "links()" method with a parameter leading to a template.

Now, in Laravel 5, all I see is that we'd have to implement a custom Presenter for the Pagination.

Also, it's not saying that in the upgrade guide that this was changed.

**Comment by GrahamCampbell** [comment]
The render method accepts 0 or 1 params. You can pass a presenter into that and do your custom view stuff with that. :)

**Comment by GrahamCampbell** [comment]
It must implement this interface: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Contracts/Pagination/Presenter.php.

You can of course extend any of the presenters in https://github.com/laravel/framework/tree/5.0/src/Illuminate/Pagination.

**Comment by GrahamCampbell** [comment]
> Also, it's not saying that in the upgrade guide that this was changed.

We'd be grateful for a pull request to the docs. :)
