### ISSUE TITLE
The new path method like (configPath, databasePath, publicPath ...), make it difficult settings custom path

### ISSUE THREAD

**Issue by loduis** [laravel/framework#7312]
For the example in the rackspace cloud site the public path is content.

How I change the public path in Laravel 5?

**Comment by daids** [comment]
see #7108 or http://mattstauffer.co/blog/extending-laravels-application

**Comment by loduis** [comment]
Not a great solution but it works,

For now I have to load an extra file just to change the public path

The big problem methods (configPath, publicPath, ...) is the static part they have, what makes it difficult to change, without extending the application

If this methods instead of ...

```php
	/**
	 * Get the path to the public / web directory.
	 *
	 * @return string
	 */
	public function publicPath()
	{
		return $this->basePath.'/public';
	}
```

They were something like ...

```php
	/**
	 * Get the path to the public / web directory.
	 *
	 * @return string
	 */
	public function publicPath()
	{
		return $this['path.public'];
	}
```

Would be much easier to adjust
