### ISSUE TITLE
php artisan issue and workaround - problem in services.json

### ISSUE THREAD

**Issue by nolros** [laravel/framework#7314]
L5 Issue:

running php artisan optimize or subset of commands is creating a problem with services.json

So I can kind of replicate the problem. It is definitely a compile problem, but cannot pickup exactly where. It boils down to the following
- php artisan is creating a problem services.json file
- whereas the app services,json fixes the problem. If you get the app code to touch or write the service.json file your app will work. Example, below

**if I do the following:**
run php artisan optimize 

**it creates the following problem:**
regens services.json but loads certain Service Providers in problem sequence. The ServiceProvider are failing silently.

**workaround solution:**
1. get the app code vs. php artisan code to touch services.json 

Example:
1. create ServiceProvider 
2. create a boot() method that loads a view composer, example, below.
3. if I then load or the view the app will create the proper services.json and the app will work fine.
3.1 you might need to do a composer dumpautoload 
3.2 do not run run php artisan optimize or clear-compile as it will again corrupt the services.json file 

*If I compare a service.json file php artisan vs. app I can see that the php artisan command line is building the file incorrectly. Too much too put into this message but it is not eager loading certain ServiceProviders, but moving them to deferred which is a problem. So when you touch the file through app code it builds it the right way. In my case it loading the decorator into defer and removing the translator class so the decorator becomes the root class.*

*In my case it is taking my ServiceProviders and placing them in deferred and overwriting some root ServiceProvider like translator. Once the app touches the file, it moves the ServiceProvider back to eager load and then insert the root translator class again. Also, with the above change it is adding in a when condition that means certain ServiceProviders will fail silently. Again the app touch fixes the seqeunce*

Example of my basic view composer boot. Don't try register() as it will fail.
```
 // I can then remove all of this after the touch
  public function boot()
    {
        View::composer('auth.register', TranslatorComposer::class);
    }
```

**Comment by crynobone** [comment]
Could it be because you're running the app code (web) as different user/group (nginx/apache) as you would while running `php artisan`?

**Comment by nolros** [comment]
crynobone, unfortunately not, as I'm running exactly the same. In fact I can replicate it on MAMP, on the same host with full permissions. What leads me to believe this is a potential bug is that if I let the application i.e. I setup a basic ServiceProvider with a simple boot() ... example below ... to bind a view composer and then reload the browser all of my code will work fine. The reason I'm creating the ServiceProvider is to get the app to update the services.json from its own boot sequence vs artisan command line. is  I then comment out that one line and everything is back to normal. I can see when why when I do a file comparison. In my case I have a translator decorator that I can trace to see where it is writing pre and post a artisan optimize. In my case optimize is replacing Laravel's core translator with my translator decorator in the delayed loading section and then inserting a related when line which causes my decorator to fail silently. 

Versus when the app writes out the services.json file i.e. vs  artisan, it places the translator core back in delayed, moves my decorator to eager and removes the when clause so the app runs fine again. 

```
use Illuminate\Translation\TranslationServiceProvider as ServiceProvider;

class TranslatorServiceProvider extends ServiceProvider {

//    this is the code that I insert to get it to touch the services.json file and then
//    comment out the register 
//    public function boot()
//    {
//        View::composer('auth.register.start', TranslatorComposer::class);
//    }

    /**
     * Registers the decorated translator
     *
     * @return void
     */
    public function register()
    {
        $this->registerLang();
        $this->registerComposer();
    }

    /**
     * Register views to composer
     */
    private function registerComposer()
    {
        $this->app->make('view')->composer('auth.register.start', TranslatorComposer::class );
        $this->app->make('view')->composer('auth.login', TranslatorComposer::class );
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    private function registerLang()
    {

        $this->registerLoader();

        $this->app->singleton('translator', function($app)
        {
            $loader = $app['translation.loader'];

            $locale = $app['config']['app.locale'];

            $trans = new Translator($loader, $locale);

            $trans->setFallback($app['config']['app.fallback_locale']);

            // TranslatorDecorator implements the translator interface and the usual i.e. implements the contract methods and has some translation and locale methods
            return new TranslatorDecorator($trans, $app['config'], $this->app );

        });
        
    }
   // removed the rest for brevity
```

**Comment by crynobone** [comment]
So you're saying you have both `Illuminate\Translation\TranslationServiceProvider` and `App\Providers\TranslationServiceProvider` in `app.providers` when `App\Providers\TranslationServiceProvider` already extending `Illuminate\Translation\TranslationServiceProvider`?

**Comment by nolros** [comment]
If I run artisan optimize this is what it writes to services.json. This fails silently so that my translator decorator and view composer are not bound to the IoC

```
"deferred": {
...
        // note this is my own SP that extends the Laravel Translator SP
	"translator": "App\\Administrate\\Providers\\TranslatorServiceProvider",
	"translation.loader": "App\\Administrate\\Providers\\TranslatorServiceProvider",
...
}
  
"when": {
	...
        // 
	"App\\Administrate\\Providers\\TranslatorServiceProvider": [],  
	...
}
```

However, if I let the provider touch the services.json this is how it writes it.  This works and the app runs fine. As you cane see it is now eager loading my SP and deferred the Laravel SP that I'm extending. 
```
"eager"{
	...
	"App\\Administrate\\Providers\\TranslatorServiceProvider",
	...
}

"deferred": {
...
    // notice these are the Laravel Translators. 
    "translator": "Illuminate\\Translation\\TranslationServiceProvider",
    "translation.loader": "Illuminate\\Translation\\TranslationServiceProvider",
...
}
```
I am extending the Laravel TranslationServiceProvider in my own TranslatorServiceProvider. That might be an issue.

**Comment by nolros** [comment]
@crynobone  fwiw, another person have the same issue https://laracasts.com/discuss/channels/general-discussion/l5-with-psr-4-package?page=1#reply-31474

**Comment by crynobone** [comment]
> I am extending the Laravel TranslationServiceProvider in my own TranslatorServiceProvider. That might be an issue.

Yes, which you should remove `Illuminate\Translation\TranslationServiceProvider` since your replacement service provider already include the same feature.

> This fails silently so that my translator decorator and view composer are not bound to the IoC

Fail? `"translator": "App\\Administrate\\Providers\\TranslatorServiceProvider",` clearly shown that it is registered as deferred (which is the expected behaviour).

**Comment by nolros** [comment]
@crynobone for some reason 5.0.16 fixed this issue for me. Many thanks for you help.
