### ISSUE TITLE
[5.0]route:cache with  Closure  problem

### ISSUE THREAD

**Issue by stevenyangecho** [laravel/framework#7319]
command artisan route:cache

when met closure route:

    Route::get('/', function()
    {
        return 'Hello World';
    });

it will fail with 

    exception 'LogicException' with message 'Unable to prepare route [/] for serialization. Uses Closure.'

**Comment by GrahamCampbell** [comment]
Yep, that's the expected behaviour.

**Comment by GrahamCampbell** [comment]
Laravel's source code:

```php
	/**
	 * Prepare the route instance for serialization.
	 *
	 * @return void
	 *
	 * @throws LogicException
	 */
	public function prepareForSerialization()
	{
		if ($this->action['uses'] instanceof Closure)
		{
			throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
		}

		unset($this->container);

		unset($this->compiled);
	}
```

**Comment by stevenyangecho** [comment]
but ,when the  app has some closure route,it means cant route cache?
has solution ?
change the app code to not use closure route,or do  some others like skip cache for closure  route but cache for normals?

**Comment by GrahamCampbell** [comment]
Basically, you cannot use route caching at all if you have closures in your routes. Selective caching would defeat the object.

**Comment by stevenyangecho** [comment]
ok,thanks,so I will change code to not use closure  route at all

**Comment by rogue780** [comment]
It is possible, with a little creativity, to serialize a Closure. The code should be modified to allow this. I might have to submit a PR for it

**Comment by crynobone** [comment]
AFAIK, taylor tried it before and found out that having to serialize and unserialize closure reduce the performance that you could possibly gain from using route caching.

**Comment by codemdpro** [comment]
If you're not using any api func. , you can comment 
/*
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
*/
in routes/api.php

**Comment by devcircus** [comment]
Old thread but those are just sample routes. Delete them. This is covered in the docs.
