### ISSUE TITLE
File Cache Driver Bug

### ISSUE THREAD

**Issue by omarabid** [laravel/framework#7321]
I'm using caching with the File driver. I have many thousands items to cache. I get the following error

```
file_put_contents(/psys/app/app/storage/cache/3c/cb/3ccba2a8ec9370c97d0aeb6e142bce39): failed to open stream: No such file or directory 
```

The error disappears if I use less items. I'm wondering if I'm just reaching the limits of the File Cache driver?

**Comment by GrahamCampbell** [comment]
> I'm wondering if I'm just reaching the limits of the File Cache driver?

Yeh, the file drivers are only meant for low traffic sites and local development. :)
