### ISSUE TITLE
Socialite: Store config in .env instead

### ISSUE THREAD

**Issue by phanan** [laravel/framework#7322]
So L5 has replaced the cascading config system with PHP dotenv. TBH I'm not a fan of this move and find it really lack of flexibility, but guess I'll have learn to live with it. 

Now, I find it weird that socialite's config stills stays in `config/services`. Doesn't this defeat the whole purpose of having `.env` from the start? From PHP dotenv's readme:

> You should never store sensitive credentials in your code.

Aren't those Google, Mandrill, and Facebook secret keys all under that "sensitive credentials" category? If no, why not? If yes, shouldn't we follow then same rule and store them into `.env` instead?

**Comment by GrahamCampbell** [comment]
You can anything you want into that file.

**Comment by phanan** [comment]
What file are you talking about @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
You can load config into config/services.php from your .env file. We're not stopping you doing that.

**Comment by phanan** [comment]
Right, so we need a config file to load a config file. I know this is how it goes with current app and database config though. Thanks for answering.

**Comment by shehi** [comment]
@phanan No. You need to put something like:
```'facebook' => ['client_secret' => env('CLIENT_SECRET')]``` into services.php etc.
