### ISSUE TITLE
Session store not set on request.

### ISSUE THREAD

**Issue by duxet** [laravel/framework#7328]
https://github.com/laracasts/Behat-Laravel-Extension/issues/15 - i think this might be Laravel bug, since session attribute of request is working correctly, until it gets dispatched into router. I tried with other session drivers, but that doesn't change anything.

**Comment by GrahamCampbell** [comment]
This is definitely a bug in that behat extension.

**Comment by duxet** [comment]
@GrahamCampbell Could you give me any hint how to find what's wrong with it? I can't understand why session is being lost during request processing.
