### ISSUE TITLE
[Proposal] Pass object instances to Eloquent relationships in addition to strings

### ISSUE THREAD

**Issue by john052** [laravel/framework#7332]
Currently according to the documentation to define an Eloquent relationship you have to pass the model as a string. 
```php
class User extends Model {
    public function phone()
    {
        return $this->hasOne('App\Phone');
    }
}
```
With namespaced models this can become  a bit of a hassle, especially if you change the model namespace since all the model strings would have to be manually updated (Instead of just modifying the "use" statement at the top of the file)

My proposal is to be able to pass actual model instances to the relationship functions
```php
use App\Phone;

class User extends Model {
    public function phone()
    {
        return $this->hasOne(new Phone);
    }
}
```
Note, the relationship functions already create a model instance behind the scenes 
````php
public function hasOne($related, $foreignKey = null, $localKey = null)
{
	$foreignKey = $foreignKey ?: $this->getForeignKey();
	$instance = new $related;
	$localKey = $localKey ?: $this->getKeyName();
	return new HasOne($instance->newQuery(), $this, $instance->getTable().'.'.$foreignKey, $localKey);
}
```
So what I'm proposing is basically just a documentation update. Then for a (slight?) optimization, a simple check can be done so new objects aren't created unnecessarily
```php
$instance = is_string($related) ? new $related : $related;
```

**Comment by JosephSilber** [comment]
Use PHP 5.5's `class` static property:

```php
use App\Models\Phone;

class User extends Model {

    public function phone()
    {
        return $this->hasOne(Phone::class);
    }
}
```

**Comment by GrahamCampbell** [comment]
Yeh, I use ::class in all my code. :)

**Comment by john052** [comment]
Thanks. That's actually more what I was looking for but I'm still on PHP 5.4 :(

**Comment by pavankumar0440** [comment]
Thank You @JosephSilber

**Comment by baltun** [comment]
Is it possible to pass to relation not a class name or class but an instance of this class?
I need it to make model dynamically (in runtime) depending on request and then use it in relation that is created dynamically too

**Comment by baltun** [comment]
/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php  on the line 282 
it would be better if here will be a check, if $related is object - don't create it, create only if it is class or class name
