### ISSUE TITLE
[5.0] Methods not defined in the Application Contract used by Kernal's bootstrap Method.

### ISSUE THREAD

**Issue by codbox** [laravel/framework#7344]
**hasBeenBootstrapped** and **bootstrapWith** method is missing in the [Application contract](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Contracts/Foundation/Application.php).

It's used in [Illuminate\Foundation\Http\Kernal](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Http/Kernel.php) bootstrap method.

```php
/**
* Bootstrap the application for HTTP requests.
*
* @return void
*/
public function bootstrap()
{
    if (!$this->app->hasBeenBootstrapped()) {
        $this->app->bootstrapWith($this->bootstrappers());
    }
}
```
The two methods (hasBeenBootstrapped and bootstrapWith) are NOT present in the Application interface.

I tried to add those methods in the interface, but my [pull request](https://github.com/laravel/framework/pull/7180) is failing build test.

**Comment by GrahamCampbell** [comment]
Duplicate,

**Comment by GrahamCampbell** [comment]
We cannot add new methods to the contract now. It's fixed. Modifying it will break any other implementations.

**Comment by franzliedke** [comment]
There's no open duplicate of this as far as I can see.

This was [originally brought up](https://github.com/laravel/framework/pull/7180) before the 5.0 release, but you closed it

**Comment by robsoncombr** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  robson.com.br@gmail.com
    Domain robson.com.br has exceeded the max emails per hour (209/200 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:32771 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by paris.serverbr15.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YKqcl-001rgn-SK
	for robson@robson.com.br; Mon, 09 Feb 2015 13:51:48 -0200
Date: Mon, 09 Feb 2015 07:51:46 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1423497106;
	bh=YGRcfooW5qc4I7mKLwwroElbXlU6IDvvuF3NHHuS2mo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LDozVDK6WKPqVd0mNzId1hAUOmeIrJRegl5RP0XPAsoEqIMWy2tek5eoU0Tbxl690
	 dc6vsPCW6G1TLPIFgHPaMTDoIQ3LHtkwkPKG8NcmIwUmXQbZ+WEx9h66LeadBiCUmy
	 JPUZOpZ5ENE3Nssd95rPDzEyB5ln9/PM87M24HNs=

**Comment by codbox** [comment]
Why are you closing this? 

i don't see any duplicate issue.

Your interface might be fixed, but you are implementing it incorrectly.

**Comment by GrahamCampbell** [comment]
> There's no open duplicate of this as far as I can see.

There is. I've closed 3 of them.

**Comment by GrahamCampbell** [comment]
> This was originally brought up before the 5.0 release, but you closed it

That's because it was an incorrect solution that was causing fatal errors.

**Comment by codbox** [comment]
i have checked the issues and pull request, there doesn't seem to be another issue open. 

I don't think it's correct to close this issue unless there is another **OPEN**  issue. 

The fatal error was caused by incorrect implementation of the Application contract. 

In my view, you should keep this issue open untill it is addressed. 

If you think there is another duplicate issue, please provide the link to it.

**Comment by GrahamCampbell** [comment]
> I don't think it's correct to close this issue unless there is another OPEN issue.

It's not an issue. They've been closed.
