### ISSUE TITLE
[Proposal] Polymorphic relationships and namespaced models

### ISSUE THREAD

**Issue by john052** [laravel/framework#7347]
When using namespaced models and polymorphic relationships, the full namespaced model is stored in the database as the type. 

When changing the namespace or app name, all of the type strings for polymorphic relationships have to be updated in the database.

I'm proposing creating something like a model provider that register models under unique names. Then when using polymorphic relationships the model instance is created by looking at the registered name and returning corresponding model.

So if you change your namespace or app name, you simply have to update your "model registrations" and the correct model instances will be returned without having to update the polymorphic types in the database.

**Comment by crynobone** [comment]
Check `$morphClass` property inside your Model?

**Comment by john052** [comment]
@crynobone Thank you. That seems to be what I'm looking for. :)
I checked the documentation but it's not documented.

**Comment by john052** [comment]
I think `$morphClass` only solves half the problem.
It works for `morphMany()` but not for `morphTo()`

For example if I have a comment model that morphs to it's content
```php
return $this->morphTo('content', 'content_type', 'content_id');
```
Unless the full class is saved in content_type or the comment model instantiates each model to find it's $morphClass, there is no way for the comment model to know which content is being morphed to.

**Comment by vgallur** [comment]
You could make an alias so it can be instantiated even when the short name is stored in the database:

``AliasLoader::getInstance()->alias('YourModel', 'Your\Namespaced\YourModel');``

**Comment by GrahamCampbell** [comment]
> You could make an alias so it can be instantiated even when the short name is stored in the database:

Probably a bad idea.

**Comment by vgallur** [comment]
Why?, I'm using this in one case and haven't found any issue.

**Comment by robsoncombr** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  robson.com.br@gmail.com
    Domain robson.com.br has exceeded the max emails per hour (216/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46818 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by paris.serverbr15.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YKqfY-001sq5-VH
	for robson@robson.com.br; Mon, 09 Feb 2015 13:54:41 -0200
Date: Mon, 09 Feb 2015 07:54:40 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1423497280;
	bh=n9N/Lw9F7xuMBXLw5/83cFfycHKQ6KJ3qnIsjc7e/TM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FCfY4jOUYS8jVhL30RUOiXucBxu0CnndCO5RW0hlfOQ67n+VyOivto04hBgwKM3RX
	 YcooMFrLcEQ18cOl/AmVMWdNJ97pt8gH6omcbFsaovyMKfWIBpKFbXcRr5CKmS+nVP
	 pv3qXiLc2En09zFFht3jTJAC3iyq5A/9/jbcitX8=

**Comment by john052** [comment]
@vgallur Yes, that's what I was thinking. Simply mapping model short names to full model class names but haven't looked at AliasLoader.
