### ISSUE TITLE
Blade extension createMatcher pattern captures parenthesis

### ISSUE THREAD

**Issue by john052** [laravel/framework#7349]
The blade extend example in the documentation causes an error because the createMatcher pattern captures the parenthesis with the variable giving `($var)` instead of `$var`

When trying to access properties on the var you get the error
```
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
```
The current pattern produced by createMatcher is 
```php
/(?<!\w)(\s*)@datetime(\s*\(.*\))/
```
Where it should be
```php
/(?<!\w)(\s*)@datetime\s*\((.*)\)/
```
Moving the second capture group to capture everything inside the parenthesis and not include the parenthesis

**Comment by GrahamCampbell** [comment]
This is the intended behaviour.

**Comment by MaartenStaa** [comment]
Compiling a Blade view into a file that has a syntax error is intended behaviour??

**Comment by GrahamCampbell** [comment]
Provide the sample code please.

**Comment by john052** [comment]
Using the example from
http://laravel.com/docs/5.0/templates

```php
Blade::extend(function($view, $compiler)
{
	$pattern = $compiler->createMatcher('datetime');
	return preg_replace($pattern, '$1<?php echo $2->format(\'m/d/Y H:i\'); ?>', $view);
});
```
gives
```
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
```

I've narrowed it down to the createMatcher  pattern being created capturing the parenthesis with the variable.
So with a blade view like this
```php
@datetime($date)
```
will result in code that looks like this
```php
<?php echo ($date)->format(\'m/d/Y H:i\'); ?>
```
Which causes the error

**Comment by robsoncombr** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  robson.com.br@gmail.com
    Domain robson.com.br has exceeded the max emails per hour (210/200 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:28721)
	by paris.serverbr15.com with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-e0fb-robson=robson.com.br@sgmail.github.com>)
	id 1YKqdS-001rzE-Rr
	for robson@robson.com.br; Mon, 09 Feb 2015 13:52:31 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=SDRWZ+qto/pwaTD49sbtSX5YWQo=; b=E+yv/md1ab++PFJW
	X3lavJfL2Tg4+g1ToJDayFFu+APVq2cJcvK3sLsvWxIFvgFMnD5J/EJgnl3qXqrI
	6R9YdWxiSE3xFEIWrdO9Tv4+YkbolOoJumS6uGuon6v/Jtev32rfeM6va46sZhuj
	EIwnBVP0NOxmQ343F/zS1QTXixw=
Received: by filter0269p1mdw1.sendgrid.net with SMTP id filter0269p1mdw1.22999.54D8D7B77
        2015-02-09 15:52:23.542095219 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd-007 (SG) with ESMTP id 14b6f0aa4bc.b73.15f3c2
	for <robson@robson.com.br>; Mon, 09 Feb 2015 15:52:23 +0000 (UTC)
Date: Mon, 09 Feb 2015 07:52:23 -0800

**Comment by benallfree** [comment]
Can anyone explain why this was closed? I have observed the same problem.

**Comment by john052** [comment]
If you look at the 5.1 documentation (http://laravel.com/docs/5.1/blade), using the `with` function gets around this.

**Comment by sebastiaanluca** [comment]
So it's necessary to always strip the parentheses of the text you're getting when using the extend method on Blade?

For instance in the following example and used with `@block(randomidhere)`:
```php
Blade::directive('block', function ($id) {
    return view('partials.block', compact('id'))->render();
});
```
`$id` always returns `(randomidhere)` with parentheses, which is kind of weird since it's part of the blade directive? What's the though process here?
