### ISSUE TITLE
Getting rid of Public Directory

### ISSUE THREAD

**Issue by ghazanfarmir** [laravel/framework#7352]
This might not be the correct place to ask, but I didn't have any other option to ask directly here in the issue section as I haven't answers in the forums for this.

I need to deploy my Laravel5 site to Amazon Elastic Beanstalk so my application is accessible directly at root level and not under the public folder.

I tried following various methods like moving public to root directory and other files in a folder at root level and making changes in files for correct referencing. However, it did work to the point to display the homepage only. When I tried to access /home route it broke the page and showed error page. Similarly, artisan command and other migration command were not accessible.

Could someone please explain viable solution for getting rid of public folder?

Note: I don't want to use vhosts method or .htaccess.

**Comment by JeroenVanOort** [comment]
According to Amazon's docs, you can configure the document root: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP_console.html

And I guess these kind of questions are more appropriate on laravel.io or laracasts.com/discuss

**Comment by ghazanfarmir** [comment]
Thanks @JeroenVanOort.
