### ISSUE TITLE
.env issue with PHP thread-safe

### ISSUE THREAD

**Issue by bioteck** [laravel/framework#7354]
I noticed a problem with functions putenv() and getenv() when PHP is thread-safe: if a URL is called before another is completed, its environment variables will be reset when the first script is finished. It's problematic with ajax requests, or simply if a user opens several links too quickly in new tabs (for example).

You can reproduce this bug by using WampServer, or any other server with PHP thread-safe, and creating two routes in "app/Http/routes.php":

```php
Route::get('test1', function()
{
    sleep(5);
    
    return 'APP_ENV: '.env('APP_ENV');
});

Route::get('test2', function()
{
    sleep(5);
    
    return 'APP_ENV: '.env('APP_ENV');
});
```

Then call "test1", and while it's sleeping, call "test2".
"test1" will display "APP_ENV: local", but "test2" will display "APP_ENV: "

![env_var_issue](https://cloud.githubusercontent.com/assets/5863239/6111824/e6999e50-b08b-11e4-9085-96041a2e89c2.PNG)

This problem occurred with getenv(), but $_ENV and $_SERVER are not affected. So it can be resolved by using Dotenv::findEnvironmentVariable(), which uses $_ENV in priority, instead of getenv() in helper env():

```php
$value = Dotenv::findEnvironmentVariable($key);

if ($value === null) return value($default);
```

The call of Dotenv::makeMutable() is also needed in bootstrapper "DetectEnvironment.php":

```php
try
{
    Dotenv::makeMutable();
    Dotenv::load($app['path.base'], $app->environmentFile());
}
catch (InvalidArgumentException $e)
{
    //
}
```

**Comment by GrahamCampbell** [comment]
Please open an issue on the phpdotenv repo.

**Comment by bioteck** [comment]
But it's not a phpdotenv issue! It's a PHP issue. However, I open an issue on Laravel because it can be solved in the way I explained.

**Comment by GrahamCampbell** [comment]
There's nothing we can realistically do about it.

**Comment by GrahamCampbell** [comment]
Wait, what? If you've got a solution, then feel free to send a pull. That would be awesome! :)

Issues aren't very helpful to us.

**Comment by neomerx** [comment]
@bioteck Have you noticed? You should choose where to post issues depending on whether you have solution. :+1:

**Comment by crynobone** [comment]
> There's nothing we can realistically do about it.

Change `env()` to use `Dotenv::findEnvironmentVariable($key)` instead of `getenv()`?

**Comment by GrahamCampbell** [comment]
@crynobone I actually already privately discussed this via email, and it's clear that I was too hastily to dismiss this, but we're very much happy to receive pull requests to address this :)

**Comment by fkomaralp** [comment]
Code from vlucas/phpdotenv repository
`
$dotenv = new \Dotenv\Dotenv("/var/www/html/", '.env');
$dotenv->load();
`
If I load my local .env file with this method my code is worked.
IfI remove this line my code is getting an error, because env function is not working.

**Comment by JustinShift** [comment]
If anyone is interested this issues only started happening to us when we set `clear_env = yes` in the PHP-FPM pool config. We still testing to confirm but thought I would post it here in case it helps somebody else.
