### ISSUE TITLE
Domain wildcard group in routes and url generation for named routes

### ISSUE THREAD

**Issue by Jan-J** [laravel/framework#7366]
I have route group with domain wildcard. Something like this:
```php
Route::group(
    [
        'domain' => '{subdomain}.domain.com',
    ],
    function ($router) {
        Route::get(
            '/',
            [
                'uses' => function ($subdomain) {
                    return route('subhome');
                },
                'as' => 'subhome'
            ]
        );
    }
);
```

Route is working well, catching only subdomain request. But there is a problem in url generation for named route. Above code will produce:
```
http://%7Bsubdomain%7D.domain.com
```

{subdomain} wildcard is not converted to current subdomain, and named routes are not usable. I found dirty solution to this:
```php
Route::group(
    [
        'domain' => '{subdomain}.domain.com',
    ],
    function ($router) {
        Route::get(
            '/',
            [
                'uses' => function ($subdomain) use ($router) {
                    $route = $router->getCurrentRoute();
                    $action = $route->getAction();
                    $action['domain'] = $subdomain . '.domain.com';
                    $route->setAction($action);

                    return route('subhome');
                },
                'as' => 'subhome'
            ]
        );
    }
);
```
It is now outputting correct route url:
```
http://subdomain1.domain.com
```
This solution works, but it is a dirty one. It can be probably taken out from there and made into its own middleware or event handler class, but I'm wondering if there is, or should be any better solution?

###### EDIT

My solution is not quite right. Because you need to update __all__ routes actions with correct subdomains. This probably can be done through RouteCollection class, but this is not optimal in case of performance. And ugly as well.

**Comment by mackiecarr** [comment]
Maybe the UrlGenerator route(...) method could be changed as such:

~~~
public function route($name, $parameters = array(), $absolute = true)
{
    if ( ! is_null($route = $this->routes->getByName($name)))
    {
        if (count($parameters)) {
            return $this->toRoute($route, $parameters, $absolute);
        } else {
            //If no parameters are specified grab them from the current request...
            $parameters = $route->bind($this->getRequest())->parameters();
            return $this->toRoute($route, $parameters, $absolute);
        }
    }
    throw new InvalidArgumentException("Route [{$name}] not defined.");
}
~~~

If this works for you then maybe make a pull request...

**Comment by GrahamCampbell** [comment]
We're open to pulls. If it's a change in behaviour send to the master, otherwise, to 5.0 please. :)
