### ISSUE TITLE
Consecutive requests in unit tests have the same input

### ISSUE THREAD

**Issue by carlosafonso** [laravel/framework#7367]
Hi,

I have set up a very simple controller in a fresh installation of L5. Here's the code:

```php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DummyController extends Controller {
	public function index() {
		var_dump(Request::all());
	}
}
```

I also have a test which performs two consecutive requests to this controller. The first one provides some parameters through the query string, whereas the second one does not:

```php
class DummyTest extends TestCase {
	public function testDummy() {
		$response = $this->call('GET', 'dummy?foo=bar&baz=quux');
		$response = $this->call('GET', 'dummy');
	}
}
```

Here's the route:

```php
Route::resource('dummy', 'DummyController', ['only' => 'index']);
```

When I run the test, I'm expecting the second `var_dump()` to be empty, however this is the output that I get:

```
$ vendor/bin/phpunit --filter DummyTest
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

.array(2) {
  ["foo"]=>
  string(3) "bar"
  ["baz"]=>
  string(4) "quux"
}
array(2) {
  ["foo"]=>
  string(3) "bar"
  ["baz"]=>
  string(4) "quux"
}


Time: 73 ms, Memory: 10.50Mb
```

I also came across this issue in L4, but I managed to solve it by restarting the client between requests:

```php
$response = $this->call('GET', 'dummy?foo=bar&baz=quux');
$this->client->restart();
$response = $this->call('GET', 'dummy');
```

However this no longer works in L5 since `$client` does not exist anymore.

I have been tracking the request throughout the call stack and everything seems to be OK right until the controller is actually called, so to me it looks like it has something to do with the Request object itself. It's like it is caching previous input for some reason. Also, `$this->refreshApplication()` works but it also deletes any in-memory database that I might be using.

Is this behavior correct?

**Comment by carlosafonso** [comment]
Now that was fast.

**Comment by GrahamCampbell** [comment]
Thanks guys. Further discussion can continue on that pull request. :)
