### ISSUE TITLE
addition relations on the fly

### ISSUE THREAD

**Issue by greabock** [laravel/framework#7381]
I would like to see syntax like:
```php
SomeModel::addRelation('relation_name', function($model){
    return $model->hasMany(OtherModel::class);
});

SomeModel::with('relation_name')->get();
```
then we could do full-DDD structure for our application and get absolutely independent modules by just adding relations on the fly in own ServiceProviders of modlules or packages.

**Comment by rkgrep** [comment]
+1

**Comment by kaidesu** [comment]
This is what polymorphic relationships are.

**Comment by rkgrep** [comment]
Actually, no. Polymorpich relations cannot be created on the fly either.

**Comment by laravel-blog** [comment]
+1

**Comment by greabock** [comment]
@kaidesu @rkgrep  Actually, its possible. But has too much overhead. In example: we has User-dоmain (area of responsibility, not http-domain, of course)  and another Article-domain. User can have relations with article like: author, corrector, publisher, subscriber.  All of this relations uses user_id field. And what about polymorphic? We need: `authored_id`, `authored_type`, `corrected_id`, `corrected_type`, `edited_id`, `edited_type`, `published_id`, `published_type`... 
nope, thanks =)

Polymorphic relations convenient uses for cross-functional models like Comment, Image, Like etc.

**Comment by GrahamCampbell** [comment]
This looks like something that would be better implemented by a package first. Taylor doesn't want much more stuff being let into eloquent.

**Comment by greabock** [comment]
I’ll just leave this here
https://github.com/greabock/tentacles

**Comment by laravel-blog** [comment]
@greabock thx!
