### ISSUE TITLE
command db:seed strange behaviour

### ISSUE THREAD

**Issue by jmaibach** [laravel/framework#7383]
I recognized some strange behaviour in Laravel 4.2, and I don't know how this is possible...

# I'm seeding the database like this:

```php
class CitySeeder extends Seeder
{

....
public function run()
{
...
$city = \Bla\Models\Germany\City::create( [
    'ger_states_id' => $state->id,
    'name' => $row['name'],
    'name_seo' => Url::seoUrl($row['name']),
    'name_en' => $row['name_en'],
    'name_en_seo' => Url::seoUrl($row['name_en']),
    'url_seo' => Url::seoUrl($row['name'])
]);
...
}
}
```

The class Url looks like this, I'm creating seo-links out of the names:

```php
class Url {

    //  Umlaute äöüß durch ae, oe, ue, ss ersetzen
    private static function replaceUmlauts($string) {

        $such_array  = array ('ä', 'ö', 'ü', 'ß');
        $ersetzen_array = array ('ae', 'oe', 'ue', 'ss');

        $neuer_text  = str_replace($such_array, $ersetzen_array, $string);
        //  bla
        return $neuer_text;
    }

    public static function seoUrl($string) {

        //Lower case everything
        $string = strtolower($string);

        $string = static::replaceUmlauts($string);

        //Make alphanumeric (removes all other characters)
        $string = preg_replace("/[^a-z0-9_\s-]/", "", $string);
        //Clean up multiple dashes or whitespaces
        $string = preg_replace("/[\s-]+/", " ", $string);
        //Convert whitespaces and underscore to dash
        $string = preg_replace("/[\s_]/", "-", $string);

        return $string;
    }
}
```

So for example if the name of a city is `Düsseldorf` it gets converted to `duesseldorf`.

Now I run:
```php
php artisan db:seed
```

But the string gets stored in the database like this: `dsseldorf` without the `ue`.

So you'd probably think this is because of some bad setup of charsets, but:

(1) everything is utf-8 (files, mysql etc..)
(2) the umlaut `ü` gets converted to `ue` before it gets stored in the database

# So this was kinda strange so i setup a route to seed the database

So I set up a route `/seed` and a Controller `SeedController` with a function `seed()`

```php
Route::get('/seed', '\Bla\Controllers\SeedController@seed');
```

```php
class SeedController {

public function seed()
{
...
$city = \Bla\Models\Germany\City::create( [
    'ger_states_id' => $state->id,
    'name' => $row['name'],
    'name_seo' => Url::seoUrl($row['name']),
    'name_en' => $row['name_en'],
    'name_en_seo' => Url::seoUrl($row['name_en']),
    'url_seo' => Url::seoUrl($row['name'])
]);
...
}
}
```

So I copied the exact same code from above into the function `seed()`, really the exact same code.

Now I'm hitting the route `/seed` in my browser.

But this time the database gets seeded correctly with `duesseldorf`

# Custom Command

So I set up a custom command `seeddb` which calls the funciton `seed()` in the `SeedController`, which works fine like I said. So I run:

```php
php artisan seeddb
```

Guess what: The string doesn't get stored correctly. It gets stored like `dsseldorf`

# How is this even possible? What is going wrong there?

I swear to you everything is set up to use utf-8, even all the files are utf-8. As I said everything works fine when i hit the route `/seed` to fill the database.

**Comment by Arrilot** [comment]
That's most likely because of php settings, not Laravel.
Check your php.ini for CLI

**Comment by jmaibach** [comment]
Hi Arrilot,

thanks for your answer.
I thought about your answer and came to the conclusion that you have to be right. This must be because of some misconfiguration in CLI.

I changed the charset in my /etc/php5/cli/php.ini to UTF-8 but it still doesnt work (the charset in /etc/php5/fpm/php.ini is fine as well).

Btw: I'm running nginx + ubuntu.

What I forgot to mention is that the seeds run fine in my homestead environment. The problem only exists on my vServer.

Also, just to be safe, I copied the .ini files from my homestead environment to my vServer but it doesnt work. No I didn't forget to restart the services, I restarted my whole vServer after these changes but the problem still exists.

What to do? I'm appreciative of all help.

**Comment by GrahamCampbell** [comment]
Closing due to human timeout.
