### ISSUE TITLE
[L5] Allow publishing the same file multiple times.

### ISSUE THREAD

**Issue by Beanow** [laravel/framework#7387]
Using `$this->publishes()` from the `ServiceProvider` a file/directory can only be published once, because the source is the array key. Currently I need to use a weird workaround for publishing multiple times: adding several `/.` paths in between just so the key is unique.

An example use-case for doing this is: If I want to use an empty config file and publish it to several locations that users of my package are *very likely* to want to use. Saving them the effort of having to make multiple directories and this file.

A much better way to do this would be to allow the target to be an array.

```php
$this->publishes([
  __DIR__.'/config/.empty-config.php' => [
    base_path('resources/lang/packages/en/somepackage/namespace.php'),
    base_path('resources/lang/packages/fr/somepackage/namespace.php'),
  ]
]);
```

**Comment by GrahamCampbell** [comment]
> a file/directory can only be published once, 

Yes. That's correct.

**Comment by Beanow** [comment]
@GrahamCampbell if by "correct" you meant: by design. I've already noticed this reading the Laravel code. I would appreciate it if you would not dismiss my issue so lightly.

Maybe I'm mistaken due to the lack of documentation for package development, but I'm seeing a problem with this design of "publishing a file/dir only once", if you consider the L5 changes to how configuration files work.

A package developer is now forced to choose between several methods of providing configuration options. Mainly `publishes()` and `mergeConfigFrom()`. This means you can also create your own combinations of this, mixing and matching these. And I've found that the above use case is very helpful in how the configuration works for my package. Saving many steps in the configuration process for projects using my package.
