### ISSUE TITLE
 Class 'Predis\Client' not found during Mail:send. Mail::send now uses queue?

### ISSUE THREAD

**Issue by vitalniko** [laravel/framework#7388]
Hi i was using Laravel 5 (master branch, quite old, probably from december ) Now  i  switched to 5.0
And during mail send  i get 
-------------------
PHP Fatal error:  Class 'Predis\Client' not found in /home/seo/sites/seo/vendor/laravel/framework/src/Illuminate/Redis/Database.php on line 58
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Predis\Client' not found' in /home/seo/sites/seo/vendor/laravel/framework/src/Illuminate/Redis/Database.php:58
Stack trace:
#0 /home/seo/sites/seo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
----

I had defauilt set to redis in config/queue.php. That's the only redis mention i found
When i set the value  to 'default' => env('QUEUE_DRIVER', null)
I get no exception and no mail.

**Comment by vitalniko** [comment]
Switched queue  value to 
'default' => env('QUEUE_DRIVER', 'sync'),
And mail is working now. Weird...

**Comment by overtrue** [comment]
http://laravel.com/docs/5.0/redis
> Before using Redis with Laravel, you will need to install the predis/predis package (~1.0) via Composer.

**Comment by crynobone** [comment]
@overtrue The issue is why was "Redis" required when just using `Mail::send()`, it would be understandable if he was trying to use `Mail::queue()`.

**Comment by vitalniko** [comment]
@crynobone Correct, i wasn't using any ::queue or ::later
The code is pretty much simple -  the report is generated and sent via Mail::send()

**Comment by GrahamCampbell** [comment]
Caused by this: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Mail/MailServiceProvider.php#L72.

You must have your queue driver set to use redis. You need to require predis to use redis.
