### ISSUE TITLE
DB select returns bad output

### ISSUE THREAD

**Issue by Martodox** [laravel/framework#7389]
There is an issue with sqlsrv and possibly the rest of them too.

If I make a select query on a table and one of the resulting rows has a field containing right single quotation mark (hex: 0x2019) and I make a dd() on it, I get this

"question": b"Don’t I have a right to a refund after..."

That 'b' shound't be there

This causes Response::json to fail.

**Comment by Arrilot** [comment]
`b` appears in dd() output because symfony var-dumper treats your not UTF-8 string as binary string and indicates this fact during output with `b` char. That's fine for me

Can you provide the code where you get the data and then cast it to json?

**Comment by Martodox** [comment]
```php
$var = DB::table('sometable')->get();
return \Response::json($var);
```

and sometable contains row with a field type nvarchar containing this:

```
Don’t I have a right to a refund after ....?
```

I dug up how dd checks against binary and came up with a function that fixes it but it requires looping over every query before json decode.

```php
        if (isset($text[0]) && !preg_match('//u', $text)) {
            $text = iconv('Windows-1250', 'ASCII//TRANSLIT', $text);
        }
```

So there are 3 solutions:
    1. Forget about this issue and leave ppl writing their own functions solving this case
    2. Add an ability to listen to all incoming queries and allow for some parsing before the get() returns an object
    3. patch json encode function to check against this kind of error and encode the data appropriately.

The best approach would be no.2 as it allows for most flexibility. Similar functionality can be found on [Restangular](https://github.com/mgonto/restangular) for angularjs

**Comment by GrahamCampbell** [comment]
We're open to pulls if you want something changing.
