### ISSUE TITLE
Specify the queue / pipe for a handler

### ISSUE THREAD

**Issue by morrislaptop** [laravel/framework#7391]
How do we specify what queue / pipe the handler should go in? 

I was thinking something simple like? 

```
<?php namespace Locality\Handlers\Events;

use Locality\Events\LocationWasSaved;

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldBeQueued;

class GeocodeLocation implements ShouldBeQueued {

	use InteractsWithQueue;

        var $queue = 'geocode';

	/**
	 * Create the event handler.
	 */
	public function __construct()
	{
		//
	}

	/**
	 * Handle the event.
	 *
	 * @param  LocationWasSaved  $event
	 * @return void
	 */
	public function handle(LocationWasSaved $event)
	{
		//
	}

}
```

**Comment by GrahamCampbell** [comment]
Has anyone got anything to say about this? If not, it will eventually get closed.

**Comment by morrislaptop** [comment]
Well can it be implemented????

**Comment by GrahamCampbell** [comment]
We're open to PRs, but I'm not able to accept proposals. Taylor is in charge.

**Comment by morrislaptop** [comment]
Looking through the code it looks like that if you have a queue() method on your handler you can control how the job is added to the queue? I couldn't find any documentation for this, do you know anything about it?

**Comment by onbjerg** [comment]
Well, can't you just do Queue::pushOn($pipe, $handler)?

**Comment by GrahamCampbell** [comment]
@onbjerg That's not use if you're not dealing with the queue manually, say for example, async events.
