### ISSUE TITLE
Install Yii 2 advanced template via composer

### ISSUE THREAD

**Issue by Bnomercy** [laravel/framework#7399]
Hi sir,

When I use this command "composer create-project --prefer-dist yiisoft/yii2-app-advanced" it has the message:

Could not fetch https://api.github.com/repos/RobinHerbots/jquery.inputmask/contents/bower.json?ref=1d2a93fd4890ec65056b84136326ec8d7f484ca8, enter your GitHub credentials to go over the API rate limit
A token will be created and stored in "C:/Users/Nomercy/AppData/Roaming/Composer/auth.json", your password will never be stored
To revoke access to this token you can visit https://github.com/settings/applications
Username:

How to solve this?

**Comment by crynobone** [comment]
Welcome to `laravel/framework` github issue. You probably need to send this to <https://github.com/yiisoft/yii2/issues>

**Comment by overtrue** [comment]
:alien:

**Comment by wangqiqi21** [comment]
nice joke :)

**Comment by lichunqiang** [comment]
:boat:

**Comment by SuperPuppet** [comment]
lol

**Comment by qiansen1386** [comment]
Nice one, why don't you just close it.

**Comment by Anahkiasen** [comment]
To be fair this isn't an issue with Yii either, you just need to do what Composer tells you to do in that message: create a token and give it to him
