### ISSUE TITLE
After inner join model's attributes are overriden

### ISSUE THREAD

**Issue by alexsoft** [laravel/framework#7404]
When using belongsToMany method, after inner join it turns out that model's attributes are overridden by the attributes with the same names from pivot table. Exactly id, created_at, updated_at attributes are affected.

I'm afraid it's a bug. If not, could you please help and tell me how I can handle this.

**Comment by alexsoft** [comment]
I can remove id attribute from pivot table. But the issue still takes place with created_at and updated_at attributes. Need your help.

**Comment by riev** [comment]
The issue is because the BelongsToMany class is missing its paginate function to set the alias for the pivot table.. I put in a pull request to fix it https://github.com/laravel/framework/pull/7476

**Comment by taylorotwell** [comment]
You need to use a select. Also the PR fixes some issues.
