### ISSUE TITLE
Converting model to array 

### ISSUE THREAD

**Issue by daverdalas** [laravel/framework#7405]
Hey,
take for example this model:

    $client = Client::with['posts']->find(1);

Now, when I assign a new value to object, for example:

    $client->posts = $some_new_posts;

then invoke the toArray() function.

    $array = $client->toArray();

Let us refer now to posts $array['posts']. In response, we will get the old values and not the newly assigned. I think we should get new values but maybe I'm wrong :)

**Comment by neomerx** [comment]
Assuming $client->posts() is a relationship to Posts model (e.g. hasMany) you have to understand that $client->posts is not a regular property but could be considered as a short form for $client->posts()->get()

Shortly, you use it wrongly :)

**Comment by df-jablan** [comment]
@neomerx heh...
