### ISSUE TITLE
Controller method not found on brand new controller.

### ISSUE THREAD

**Issue by 0147500** [laravel/framework#7408]
Hello,
I just did a brand new install on laravel5 and got the following error after generating a controller with make:controller and adding the Route::recource('admin','AdminController');
```
Whoops, looks like something went wrong.

1/1
BadMethodCallException in Macroable.php line 87:
Method recource does not exist.
```
Is this a bug or did i shrew something up?

Regards,

Robert

**Comment by 0147500** [comment]
okay typo happed. nvm then

**Comment by ramagomamd** [comment]
Really now
