### ISSUE TITLE
[5.0] Confusing logic in vendor:publish with --provider and --tag

### ISSUE THREAD

**Issue by simonhampel** [laravel/framework#7412]
If I've understood the source code correctly, the behaviour of the vendor:publish command when specified using both the --provider and --tag options is to first try and publish all files for the tag if the tag exists, otherwise publish all files for the provider if the tag does not exist.

This potentially gives wildly different and unexpected results - especially in the case of a typo on the command line in the tag name.

Before I read the source, I expected the command to let me publish only the files tagged a specific way for a specific service provider, by specifying both options - but it doesn't work this way.

That's okay if you understand that - and looking at the code, it might be a little cumbersome to add this level of flexibility, although calculating the intersection between the two arrays would probably do the trick.

Either way - to prevent unintended side effects, I think it would be better to fail with a meaningful error in the case of the tag being specified not existing rather than just continuing on and ignoring the tag specified on the command line.

If you specify a tag, you expect only files marked with that tag to be published - but if you also specify a provider and accidentally mis-type the name of the tag, you'll end up publishing all files for that provider, regardless of tag - which is very likely not what was intended.

Even disregarding specifying both options - just specifying a non-existent tag name (eg due to a typo) does not fail with an error as you might expect - it just silently completes saying "Publishing Complete!", which is misleading.

**Comment by GrahamCampbell** [comment]
Has anyone got anything to say about this? If not, it will eventually get closed.

**Comment by franzliedke** [comment]
@simonhampel As far as I can see, `ServiceProvider::pathsToPublish()` returns an empty array when an invalid provider or tag is passed.

It will only return all paths from all providers if no parameter is passed.
