### ISSUE TITLE
Syntax error on Illuminate/Bus/Dispatcher.php:223 on PHP 5.4

### ISSUE THREAD

**Issue by fish131** [laravel/framework#7416]
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in /home/users/liviu/public_html/laravel2/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:223

Illuminate/Bus/Dispatcher.php:223
```php
return (new ReflectionClass($this->getHandlerClass($command)))->implementsInterface(
            'Illuminate\Contracts\Queue\ShouldBeQueued'
        );
```
Adding with in front will fix the problem:
```php
return with(new ReflectionClass($this->getHandlerClass($command)))->implementsInterface(
            'Illuminate\Contracts\Queue\ShouldBeQueued'
        );
```

**Comment by JoostK** [comment]
What PHP version are you using? As of L4.2 we require PHP 5.4 on which `with` is not required anymore.

**Comment by fish131** [comment]
I have 5.4 installed.

**Comment by fish131** [comment]
@JoostK , that feature has been added in 5.5
http://php.net/manual/en/migration54.new-features.php

**Comment by fish131** [comment]
@JoostK I know that `with` is not required anymore, but maybe it's a bug from PHP, because the reflection is internal and who knows?

**Comment by JoostK** [comment]
Please verify that the php binary you invoke from the terminal is the same as the one the Apache/Nginx server uses. Simply create a page `<?php phpinfo();` and see its results. It is a bit weird that you have other installations there that supposedly work fine, however there must be something wrong somewhere.

**Comment by fish131** [comment]
The output is from the cli.
```bash
liviu@ns2:~/public_html/laravel2$ php -v
PHP 5.4.37-1+deb.sury.org~precise+1 (cli) (built: Jan 26 2015 11:45:18) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend Debugger v5.3, Copyright (c) 1999-2010, by Zend Technologies

liviu@ns2:~/public_html/laravel2$ php artisan
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in /home/users/liviu/public_html/laravel2/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:223
Stack trace:
#0 /home/users/liviu/public_html/laravel2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
liviu@ns2:~/public_html/laravel2$ 

```

**Comment by GrahamCampbell** [comment]
Are you using a different php version in the cli?

**Comment by JoostK** [comment]
Well according to that output it is indeed 5.4. Weird thing is that the file in which the syntax error occurs also contains `[]` as empty array notation, which parses just fine, so must indeed be 5.4.

**Comment by fish131** [comment]
@GrahamCampbell , read the output from my previous comment. The error is in CLI, when  I try to run the artisan command.

I say it's a PHP bug, but I'm not filling a report, that form is horrible.

**Comment by fish131** [comment]
I should have made myself clear:
Ubuntu server 12.04 LTS x64
PHP 5.4 (PHP 5.4.37-1+deb.sury.org~precise+1)
This problem occurs on Laravel 5.
I have other Laravel 4.2 installations that work fine, however, laravel 4.2 doesn't have that file and it works differently.

Sorry if bad english, not native.

**Comment by fish131** [comment]
So I've made a **small** test case (on the same machine):

```php
<?php

interface MyInterface {
	
}

class MyClass implements MyInterface {

}

function bug(){
	$obj = new MyClass();
	return (new ReflectionClass($obj))->implementsInterface('MyInterface');
}

var_dump(bug()); // this doesn't throw exceptions and dumps bool(true) 
```

**Comment by fish131** [comment]
The problem was from the Facebook XHP extension that was running on the server and should have been compatible with  PHP 5.4.

Some close this "issue".
