### ISSUE TITLE
Password and PasswordBroker - different constant name

### ISSUE THREAD

**Issue by arnisritins** [laravel/framework#7417]
_Password_ Facade and _PasswordBroker_ Contract has different constant names.

So, the `Illuminate/Contracts/Auth/PasswordBroker.php` has **RESET_LINK_SENT**:
```
/**
 * Constant representing a successfully sent reminder.
 *
 * @var int
 */
const RESET_LINK_SENT = 'passwords.sent';
```

However, the `Illuminate/Support/Facades/Password.php` has **REMINDER_SENT**:
```
/**
 * Constant representing a successfully sent reminder.
 *
 * @var int
 */
const REMINDER_SENT = 'passwords.sent';
```

Why do they differ?

**Comment by taylorotwell** [comment]
Fixed.
