### ISSUE TITLE
IronMQ's package just had a backwards-incompatible change

### ISSUE THREAD

**Issue by janhartigan** [laravel/framework#7421]
See here: https://github.com/iron-io/iron_mq_php/releases

The only real change seems to be that they're now using namespaces and PSR-4 autoloading. The naive fix for this would probably just be referencing the new `IronMQ\IronMQ` and taking out the old `IronMQ`. I started putting together a PR to do this, but then realized that it may not be ideal, especially for people who don't want to upgrade their Iron packages.

So I'm opening this issue so that we can decide on a common approach if it's decided that one is needed. In any case, we'll need to change the [section of the docs that defines the Iron dependency](http://laravel.com/docs/5.0/queues#configuration).

**Comment by GrahamCampbell** [comment]
We'll be updating in L5.1.

**Comment by GrahamCampbell** [comment]
We only support `~1.5` in L4.2 and L5.0. See https://github.com/laravel/framework/blob/5.0/composer.json#L99.

**Comment by janhartigan** [comment]
Cheers, thanks @GrahamCampbell
