### ISSUE TITLE
No pivot alias when using paginate on a chained query in L5

### ISSUE THREAD

**Issue by riev** [laravel/framework#7423]
```
Auth::user()->conversations()->paginate(20)
```
Queries like the one above are not using a pivot alias when using paginate (works fine with get() and also paginate() in Laravel 4).

When used in conjunction with ->with(), it uses the conversation_user pivot table ids to eager load instead of the conversations id.

So a query like this below is selecting the messages by the id of pivot table instead of the conversation id
```
Auth::user()->conversations()
            ->with(array('messages' => function($query) {
                $query->orderBy('created_at', 'desc');
             }))
             ->paginate(20);
```

When using get() my queries are as
```
select * from `users` where `users`.`id` = '3' limit 1
select `conversations`.*, `conversation_user`.`user_id` as `pivot_user_id`, `conversation_user`.`conversation_id` as `pivot_conversation_id` from `conversations` inner join `conversation_user` on `conversations`.`id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = '3'
select * from `messages` where `messages`.`conversation_id` in ('1', '2', '3', '4', '5', '6', '7', '8') order by `created_at` desc
```
Which use the correct ids of ('1', '2', '3', '4', '5', '6', '7', '8')

When using paginate() in Laravel 5 they are as
```
select * from `users` where `users`.`id` = '3' limit 1
select count(*) as aggregate from `conversations` inner join `conversation_user` on `conversations`.`id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = '3'
select * from `conversations` inner join `conversation_user` on `conversations`.`id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = '3' limit 20 offset 0
select * from `messages` where `messages`.`conversation_id` in ('1', '3', '5', '7', '9', '11', '13', '15') order by `created_at` desc
```
Which use the user_conversation pivot table ids of ('1', '3', '5', '7', '9', '11', '13', '15')

**Comment by riev** [comment]
I just tried to get past it by using withPivot() to select everything but the ids of the pivot table, but it is not having any effect when using paginate() like the alias problem above. withPivot() works fine when I use get() instead of paginate() though.

In my model I have written
```
public function conversations() {
        return $this->belongsToMany('App\Conversation')->withPivot(['user_id', 'conversation_id', 'is_deleted', 'is_unread']);
}
```

Using paginate() gives me this query which doesn't alias the pivot table or even select my pivot columns I asked for.
```
select * from `conversations` inner join `conversation_user` on `conversations`.`id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = '3' limit 20 offset 0
```

Using get() gives me the alias and the columns I asked for.
```
select `conversations`.*, `conversation_user`.`user_id` as `pivot_user_id`, `conversation_user`.`conversation_id` as `pivot_conversation_id`, `conversation_user`.`is_deleted` as `pivot_is_deleted`, `conversation_user`.`is_unread` as `pivot_is_unread` from `conversations` inner join `conversation_user` on `conversations`.`id` = `conversation_user`.`conversation_id` where `conversation_user`.`user_id` = '3'
```

**Comment by alexsoft** [comment]
I've got the same issue. But I've just described it a bit differently in #7404

**Comment by riev** [comment]
Sorry I didn't see that you had written about this previously, or I would have added to yours.

**Comment by GrahamCampbell** [comment]
Could you comment on the original please to keep this in one place.
