### ISSUE TITLE
After creating a new project with laravel tool, none of the scripts in vendor/bin are executable

### ISSUE THREAD

**Issue by martynbiz** [laravel/framework#7434]
I don't know if this is supposed to be setup out of the box or not, but when I create  new Laravel (5) project:

```
$ laravel new myproject
$ cd myproject
```

..if I then try to run:

```
$ ./vendor/bin/phpunit ...
```

..it tells me I don't have permission. I either have to manually set scripts as executable, or remove the folder and run composer install (upon which the scripts are setup to go). Is this supposed to be like this? Not that it's a huge deal, just nice to have everything working ready to go.

By the way, excellent job on testing out the box! First time to use a PHP framework where this is the case and I don't have to create a bootstrap file, and TestCase methods.

**Comment by GrahamCampbell** [comment]
That's and issue that's outside our scope. Composer should probably deal with that.

**Comment by franzliedke** [comment]
It's totally in scope. Composer does this, however the installer does not use Composer, it simply downloads a pre-installed archive.

So, +1 for this.

@martynbiz If you can, you should probably send a PR to the laravel/installer repository. That's where that code lives...
