### ISSUE TITLE
Dumping Error

### ISSUE THREAD

**Issue by drtzack** [laravel/framework#7442]
WebSocket transport receive [8,48,4138138477789184,{},"com.app.fetchUser.error",["Undefined offset: 8"],{"xdebug_message":"\nErrorException: Undefined offset: 8 in D:\\Repo\\project\\vendor\\symfony\\var-dumper\\Symfony\\Component\\VarDumper\\Cloner\\VarCloner.php on line 73\n\nCall Stack:\n    0.0000     127184   1. {main}() D:\\Repo\\project\\artisan:0\n    0.0330    1941968   2. Illuminate\\Foundation\\Console\\Kernel->handle() D:\\Repo\\project\\artisan:36\n    0.2650    7749312   3. Symfony\\Component\\Console\\Application->run() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php:91\n    0.2650    7749816   4. Symfony\\Component\\Console\\Application->doRun() D:\\Repo\\project\\vendor\\symfony\\console\\Symfony\\Component\\Console\\Application.php:126\n    0.2660    7750256   5. Symfony\\Component\\Console\\Application->doRunCommand() D:\\Repo\\project\\vendor\\symfony\\console\\Symfony\\Component\\Console\\Application.php:195\n    0.2660    7750312   6. Illuminate\\Console\\Command->run() D:\\Repo\\project\\vendor\\symfony\\console\\Symfony\\Component\\Console\\Application.php:874\n    0.2660    7750432   7. Symfony\\Component\\Console\\Command\\Command->run() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php:101\n    0.2660    7752120   8. Illuminate\\Console\\Command->execute() D:\\Repo\\project\\vendor\\symfony\\console\\Symfony\\Component\\Console\\Command\\Command.php:253\n    0.2660    7752384   9. Illuminate\\Container\\Container->call() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php:115\n    0.2670    7752608  10. call_user_func_array:{D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:523}() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:523\n    0.2670    7752736  11. project\\Console\\Commands\\ServeSocketServer->fire() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:523\n    0.2670    7753720  12. project\\Services\\SocketServer->listen() D:\\Repo\\project\\app\\Console\\Commands\\ServeSocketServer.php:45\n    0.2910    8451832  13. Thruway\\Peer\\Router->start() D:\\Repo\\project\\app\\Services\\SocketServer.php:62\n    0.3490    9836312  14. React\\EventLoop\\StreamSelectLoop->run() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Peer\\Router.php:182\n    1.4321   12407480  15. React\\EventLoop\\StreamSelectLoop->waitForStreamActivity() D:\\Repo\\project\\vendor\\react\\event-loop\\StreamSelectLoop.php:201\n    1.6471   12407792  16. call_user_func:{D:\\Repo\\project\\vendor\\react\\event-loop\\StreamSelectLoop.php:227}() D:\\Repo\\project\\vendor\\react\\event-loop\\StreamSelectLoop.php:227\n    1.6471   12407808  17. React\\Socket\\Connection->handleData() D:\\Repo\\project\\vendor\\react\\event-loop\\StreamSelectLoop.php:227\n    1.6481   12412216  18. Evenement\\EventEmitter->emit() D:\\Repo\\project\\vendor\\react\\socket\\src\\Connection.php:15\n    1.6481   12412248  19. call_user_func_array:{D:\\Repo\\project\\vendor\\evenement\\evenement\\src\\Evenement\\EventEmitterTrait.php:64}() D:\\Repo\\project\\vendor\\evenement\\evenement\\src\\Evenement\\EventEmitterTrait.php:64\n    1.6481   12412480  20. Ratchet\\Server\\IoServer->handleData() D:\\Repo\\project\\vendor\\evenement\\evenement\\src\\Evenement\\EventEmitterTrait.php:64\n    1.6481   12412480  21. Ratchet\\Http\\HttpServer->onMessage() D:\\Repo\\project\\vendor\\cboden\\ratchet\\src\\Ratchet\\Server\\IoServer.php:113\n    1.6481   12412480  22. Ratchet\\WebSocket\\WsServer->onMessage() D:\\Repo\\project\\vendor\\cboden\\ratchet\\src\\Ratchet\\Http\\HttpServer.php:53\n    1.6481   12412512  23. Ratchet\\WebSocket\\Version\\RFC6455->onMessage() D:\\Repo\\project\\vendor\\cboden\\ratchet\\src\\Ratchet\\WebSocket\\WsServer.php:96\n    1.6581   12416096  24. Thruway\\Transport\\RatchetTransportProvider->onMessage() D:\\Repo\\project\\vendor\\cboden\\ratchet\\src\\Ratchet\\WebSocket\\Version\\RFC6455.php:202\n    1.6581   12423192  25. Thruway\\Peer\\Router->onMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Transport\\RatchetTransportProvider.php:174\n    1.6581   12423224  26. Thruway\\Realm->onMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Peer\\Router.php:141\n    1.6581   12423224  27. Thruway\\Realm->processAuthenticated() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Realm.php:114\n    1.6581   12423256  28. Thruway\\Role\\Dealer->onMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Realm.php:160\n    1.6581   12423256  29. Thruway\\Role\\Dealer->processCall() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Role\\Dealer.php:92\n    1.6581   12423632  30. Thruway\\Procedure->processCall() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Role\\Dealer.php:202\n    1.6581   12423632  31. Thruway\\Registration->processCall() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Procedure.php:245\n    1.6591   12424200  32. Thruway\\Session->sendMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Registration.php:193\n    1.6591   12424200  33. Thruway\\Transport\\InternalClientTransport->sendMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Session.php:86\n    1.6591   12424200  34. Thruway\\Peer\\Client->onMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Transport\\InternalClientTransport.php:69\n    1.6591   12424200  35. Thruway\\Peer\\Client->processOther() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Peer\\Client.php:342\n    1.6591   12424200  36. Thruway\\Role\\Callee->onMessage() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Peer\\Client.php:423\n    1.6591   12424200  37. Thruway\\Role\\Callee->processInvocation() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Role\\Callee.php:73\n    1.6591   12424272  38. project\\Services\\InternalClient->fetchUser() D:\\Repo\\project\\vendor\\voryx\\thruway\\src\\Thruway\\Role\\Callee.php:151\n    1.6591   12424288  39. dd() D:\\Repo\\project\\app\\Services\\InternalClient.php:50\n    1.6591   12424872  40. array_map() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php:439\n    1.6591   12425040  41. {closure:D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php:439-439}() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php:439\n    1.6591   12428544  42. Illuminate\\Support\\Debug\\Dumper->dump() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php:439\n    1.6651   12670264  43. Symfony\\Component\\VarDumper\\Cloner\\AbstractCloner->cloneVar() D:\\Repo\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Debug\\Dumper.php:18\n"}]

**Comment by RomainLanz** [comment]
??

**Comment by drtzack** [comment]
I am using voryx/Thruway package and I am sending session data from the browser.

connection.onopen = function (session, details) {
session.call('com.app.fetchUser', [session]).then(
function (result) {
}
);

When I try to dump it with dd function it just fails with error. But it is okay with print_r.

**Comment by GrahamCampbell** [comment]
This is a symfony bug.
