### ISSUE TITLE
Laravel 5.0.5 IronMq Class Error

### ISSUE THREAD

**Issue by barisbora** [laravel/framework#7448]
Updated Laravel framework from 5.0.2 to 5.0.5 getting iron-io/iron_mq class IronMQ not found error.

I also try IronMQ different version on Laravel 5.0.5

"iron-io/iron_mq": "dev-master"
"iron-io/iron_mq": "3.*@dev"
"iron-io/iron_mq": "3.0.1" 
"iron-io/iron_mq": "2.0.0"

When i back to 5.0.2, error resolved

**Comment by GrahamCampbell** [comment]
As clearly stated, only iron_mq ~1.5 is supported: https://github.com/laravel/framework/blob/5.0/composer.json#L99.
