### ISSUE TITLE
Trailing Slashes doesn't works properly when in subdirectory

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#7450]
This rule:

```
# Redirect Trailing Slashes...
RewriteRule ^(.*)/$ /$1 [L,R=301]
```

Is awesome! Except if you are working in a subdirectory. 

For instance, when I am developing I do work on `{root}/{project}/{public}`.
So my URL seems like: `http://localhost/{project}/{public}/{route}`.

If I put a slash after this, it changes to: `http://localhost/{route}`, only.

I think perhaps the Laravel want not work this way. However, it should be considered that, in development, some rules can be broken by methodological issues.

@ Laravel 5.0.5

**Comment by rentalhost** [comment]
This rule works perfectly for me:

```
# Redirect Trailing Slashes...
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L,R=301]
```

@ http://stackoverflow.com/a/27264788/755393

**Comment by rentalhost** [comment]
You can check if it can be applied to Laravel, or why not?
Thanks!

**Comment by GrahamCampbell** [comment]
If you want it changed, send a pull and see what taylor thinks.

**Comment by rentalhost** [comment]
Yeah... I'll do that.
Thanks!
