### ISSUE TITLE
[L5] App::setLocale vs Trans::setLocale

### ISSUE THREAD

**Issue by Beanow** [laravel/framework#7455]
There are some differences in implementation in these locale switching functions.
`App::setLocale` seems to have the largest impact, setting the value on config, the translator and firing an event. Where the translator only updates it's protected attribute.

Are there different use cases for using one vs the other, or is the Translator's method only public so the Application can use it?

**Comment by GrahamCampbell** [comment]
This is a question, thus belongs on the forums.
