### ISSUE TITLE
Request::isXmlHttpRequest() is missing in Laravel 5

### ISSUE THREAD

**Issue by zegl** [laravel/framework#7457]
`Request::ajax()` is using `Request::isXmlHttpRequest()`, although it seems to be missing in Laravel 5.

See here, https://github.com/laravel/framework/blob/8865d2276be94f0a3497ba3bd26c906ae9e91e1c/src/Illuminate/Http/Request.php#L176

**Comment by KennedyTedesco** [comment]
https://github.com/symfony/HttpFoundation/blob/master/Request.php#L1732
