### ISSUE TITLE
php artisan key:generate reports success erroneously when .env file missing (on windows)

### ISSUE THREAD

**Issue by lvpro** [laravel/framework#7459]
If one uses the laravel installer to create a new project via "laravel new test", only a .env.example is provided (whereas a default .env is provided via composer create-project).

If one then issues "php artisan key:generate", he is told an application key was set successfully.   However, still no .env file exists.

If one manually copies .env.example to .env first, artisan key:generate DOES work successfully.

Recommend testing for presence of .env and produce error accordingly, or create .env on the fly at this point.

**Comment by Arrilot** [comment]
There is a PR for this already https://github.com/laravel/framework/pull/7357
