### ISSUE TITLE
[L5] Auth::check() performs multiple DB calls

### ISSUE THREAD

**Issue by Rockroxx** [laravel/framework#7460]
In a view, I called Auth::check() multiple times and for each time the DB is hit.
Using the Guard contract and passing it to the view as a variable will stop the multiple DB call behaviour.

**Comment by GrahamCampbell** [comment]
I wouldn't recommend calling such things in your views. Maybe checkout view composers.

Example: https://github.com/StyleCI/StyleCI/blob/master/app/Composers/CurrentUserComposer.php.
