### ISSUE TITLE
Auth::user() return null in routes.php  (but not in view blade file) ? Thanks

### ISSUE THREAD

**Issue by samiboukadida** [laravel/framework#7463]

**Comment by crynobone** [comment]
Laravel 5? Session now load from within middleware, which is much later in the request lifecycle than `routes.php`

**Comment by GrahamCampbell** [comment]
Yeh, you can't access the user in the routing layer, because that stuff happens earlier in the request lifecycle.

**Comment by franzliedke** [comment]
This problem only occurs if you use `Auth::user()` outside of any closure in routes.php, right?
