### ISSUE TITLE
php artisan generate no output at all [L4]

### ISSUE THREAD

**Issue by hadifarnoud** [laravel/framework#7464]
none of php artisan commands work, even `php artisan --version` prints no output.

I have mcrypt installed. php error log is turned on. and I see no error to find out what is wrong with it. I have created another project from scratch on the same machine and php artisan works fine with that project. So, the issue is within my project.

I did composer update as well. made no difference.
Laravel Framework version 4.2.17

how can I find out what's wrong?

**Comment by GrahamCampbell** [comment]
We can't process support requests here, sorry. Also, 4.2 technically isn't supported anymore.

**Comment by hadifarnoud** [comment]
I don't get why I'm not getting any error though. I was not able to even debug the issue and it seems like the common issue with artisan. folks have been asking the same question over and over again in this repo as well.

I asked in IRC, Stackoverflow and other places. Didn't think anywhere else I could get an answer.

**Comment by hadifarnoud** [comment]
I don't get why I'm not getting any error though. I was not able to even debug the issue and it seems like the common issue with artisan. folks have been asking the same question over and over again in this repo as well.

I asked in IRC, Stackoverflow and other places. Didn't think anywhere else I could get an answer.

**Comment by mikerogne** [comment]
@GrahamCampbell Is this official? From @taylorotwell? That 4.2 is not supported at all?

**Comment by GrahamCampbell** [comment]
@mikerogne Only the current stable is supported. That has always been the case. 4.2 will of course receive fixes for large bugs and security issues, but will receive no support beyond that. It is not an LTS release. Laravel doesn't have any LTS releases, and there aren't any planned.

**Comment by mikerogne** [comment]
I guess I'm a little fuzzy still. Is there a certain timeframe for which 4.2 will continue to receive security updates & bug fixes? IE: "If you're on 4.2, you should consider upgrading to 5 within 6 months, 12 months, ..."?

**Comment by hadifarnoud** [comment]
anyway, can I get a tip or something? what should I do?

**Comment by mikerogne** [comment]
Well since this isn't a support forum, I would hit up the laracasts forums, laravel.io forums, and/or IRC again.
