### ISSUE TITLE
Timezone setting not applied for Response::setExpires()

### ISSUE THREAD

**Issue by verdure-tietz** [laravel/framework#7465]
Laravel version: 5.0

The Responses (e.g. JSON) won't accept time zone settings for \Symfony\Component\HttpFoundation\Response::setExpires() as the time zone will be overwritten with UTC in that file on line 731. That's fatal when it comes to client-side caching issues.

I don't know whether that's an issue for laravel or symfony as the time zone config is set for laravel (in app.php) and is only applied in the bootstrap LoadConfiguration.php, line 40 for date_default_timezone_set().

Best regards

**Comment by lucasmichot** [comment]
This should better be reported upstram
