### ISSUE TITLE
Exception: Class log does not exist when using trans() in config.

### ISSUE THREAD

**Issue by rawcreative** [laravel/framework#7467]
On a fresh L5 install, when attempting to use localization in a config file (in this instance a published package config), the following exception is thrown:
`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in .../laravel/framework/src/Illuminate/Container/Container.php:776`

I initially thought this was due to the package itself and it's loading/handling of the translation files, but the error is also thrown when attempting to use translations in the project (resources/lang).

**Comment by GrahamCampbell** [comment]
Don't use trans() at such an early point in the framework. You're using it before the logger is even initialized.

**Comment by ralf57** [comment]
I disagree here and it should be the other way around, with the Logger already available.
It's pretty common to have translations in config files.

**Comment by GrahamCampbell** [comment]
> It's pretty common to have translations in config files.

You should not be doing that. We do not support or recommend doing that. Config files should not be generated based on environmental changes. Doing so would mean that config caching would be unreliable.

**Comment by ralf57** [comment]
I see your point but as I see it the config files should not contain any dynamic value then.

**Comment by GrahamCampbell** [comment]
> I see your point but as I see it the config files should not contain any dynamic value then.

Correct.

**Comment by GrahamCampbell** [comment]
Excluding getting environment variables. :)

**Comment by ralf57** [comment]
Sure, otherwise it would be pointless
