### ISSUE TITLE
Cannot chnage Route Cache bootstrap directory

### ISSUE THREAD

**Issue by LukeMauldin** [laravel/framework#7472]
Using laravel 5 Route caching command, the bootstrap directory cannot be set.  RouteCacheCommand:78 is hard-coded to look at 'bootstrap/app.php'.  I have changed the bootstrap directory to 'laravel-bootstrap' but there is no way to make RouteCacheCommand look in that directory.

**Comment by Arrilot** [comment]
In fact the bootstrap dir is hardcoded in a number of places in both `laravel/framework` and `laravel/laravel` repos so it is not configurable at the moment and i don't think this fact can be changed without hurting BC.

Can this be considered as a decent proposal for 5.1?

**Comment by taylorotwell** [comment]
The bootstrap directory isn't meant to be configurable at the moment.
