### ISSUE TITLE
Query with orWhere ignoring soft deletion

### ISSUE THREAD

**Issue by henrikromby** [laravel/framework#7482]
Hello!

I have this model:

```
class Delivery extends Model {
    use SoftDeletingTrait;
}
```

When I have the following two deliveries in my database (the 5th column is hour and the last column is deleted_at):

```
1	5	monthly	1	9	2015-02-18 09:55:24	2015-02-18 09:55:35	NULL
2	5	monthly	1	10	2015-02-18 09:57:21	2015-02-18 09:57:21	2015-02-18 09:55:35
```

-- and I run the following in the terminal, I get this output:

```
[6] > foreach(Delivery::where(function($query) { $query->where('hour', 9); })->orWhere(function($query) { $query->where('hour', 10); })->get() as $delivery) { var_dump([$delivery->id, $delivery->deleted_at]); }
array(2) {
  [0] =>
  int(1)
  [1] =>
  NULL
}
array(2) {
  [0] =>
  int(2)
  [1] =>
  string(19) "2015-02-18 09:55:35"
}
```

Laravel seems to be picking up soft deleted models when using orWhere

**Comment by GrahamCampbell** [comment]
Yeh, because you're saying where is not soft deleted, or where something else. See what I mean?

**Comment by henrikromby** [comment]
So, when using orWhere multiple times, I should manually do the soft deletion check every time?

**Comment by MaartenStaa** [comment]
That's what the generated query is saying, but not what @henrikromby's code is saying, which just specifies: give me deliveries where hour equals 9 or 10.

Laravel could theoretically handle this by wrapping all user defined wheres in braces so that the query would become:

```sql
select * from deliveries where deleted_at is null and (hour = 9 or hour = 10);
```

**Comment by GrahamCampbell** [comment]
> Laravel could theoretically handle this by wrapping

That's exactly what I was suggesting. Laravel does support this.

**Comment by henrikromby** [comment]
I just assumed that when using soft deletes, I would never require the soft deleted models except when explicitly asking for them. I know that I can work around it by doing what you suggest, but it just seems a little counter-intuitive to me :-)
