### ISSUE TITLE
[Database] [PgSQL] [MySQL] MediumInteger field as Primary key in Schema Builder

### ISSUE THREAD

**Issue by shehi** [laravel/framework#7484]
Following Schema Builder code line, written for primarily MySQL:

```$table->mediumInteger('id', true, true);```

doesn't behave as expected when Db-driver is changed to PgSQL. Instead of creating a Not-Nullable PRIMARY INTEGER column, it just creates simple Not-Nullable INTEGER column which is *not* PRIMARY. Could this bug be fixed in upcoming dev-master release?

**Comment by shehi** [comment]
Ok, I want to write unit-tests and possibly a solution/patch for this problem. However, after 
```composer install```

when I run 
```vendor/bin/phpunit```

following exception is thrown:
```PDOException: could not find driver```

I tried to look into the source code, but couldn't find any database configurations anywhere. I guess some PHPUnit Db Mockup was used in there.

Any ideas which could accelerate this for me, so that I could write unit-tests etc? Thanks in advance!

**Comment by shehi** [comment]
Okkkk... Apparently ```php5-sqlite``` is required for tests to run. I will be adding it as ext-dependency to ```require-dev``` in ```composer.json``` file inside my pull-request.

**Comment by GrahamCampbell** [comment]
Could you send a pull to add it to the suggests list of our database and main composer.jsons please.

**Comment by MaartenStaa** [comment]
Maybe as suggests would be better, since not everyone will use it.

**Comment by shehi** [comment]
True. But what good is it if unit-tests don't run without it?! :) Don't you agree?

**Comment by shehi** [comment]
@GrahamCampbell : please re-open this issue. I haven't solved it yet as the original problem is outstanding. I will close it *myself* thank you very much!

**Comment by GrahamCampbell** [comment]
Our policy is to close issues where we have a related pull request.
