### ISSUE TITLE
Lang::choice doesn't work with fallback_locale

### ISSUE THREAD

**Issue by Jellyfrog** [laravel/framework#7490]
If an app doesn't have a locale set and only use "fallback_locale" the `Lang::choice` won't work properly,  it will simply pick the first option:

```
'day' => 'day|days'

Lang::choice('test.day', 2) // day
```

The problem is this line:
```
$line = $this->get($key, $replace, $locale = $locale ?: $this->locale);
```
https://github.com/laravel/framework/blob/3359de6d6cd322e8a1b251c2f8d9dd42a3e4e232/src/Illuminate/Translation/Translator.php#L165

A quick and dirty fix is to replace the line with:
```
$line = $this->get($key, $replace, $locale = $locale ?: $this->locale ?: $this->fallback);
```
But double ternary is bad, and I'm sure there is a cleaner way.
For example `get()` uses `parseLocale()` which takes cares of fallback_locale.

Ive tested this on 4.2 but 5.0 seems to have the same problem also.

**Comment by GrahamCampbell** [comment]
Could you send a PR to fix please?
