### ISSUE TITLE
attach() throws error with empty array

### ISSUE THREAD

**Issue by kokokurak** [laravel/framework#7493]
Hi guys,

I think that `attach()` method could just do nothing with empty array provided, instead of throwing an error. Example:
```
$ids = [];
User::find(4)->movies()->attach($ids);
```
This piece of code will throw following SQL error:
```
"SQLSTATE[23000]: Integrity constraint violation:
1452 Cannot add or update a child row: a foreign key constraint fails (`app`.`movie_user`,
CONSTRAINT `movie_user_user_id_foreign`
FOREIGN KEY (`user_id`)
REFERENCES `users` (`id`))
(SQL: insert into `movie_user` () values ())"
```
I'd like to be able to use `attach()` without checking whether my array is empty or not. Similar improvement has been done with `whereIn()` and `whereNotIn()`, time for `attach()`. :)

**Comment by franzose** [comment]
As of me, I think that it's pretty common behaviour of `attach()`, this method reattaches relations every time you call it. However, it's strange that it throws an exception.

**Comment by franzose** [comment]
Oops, I mixed it up with `sync` method, sorry)

**Comment by franzose** [comment]
In similar issue, there's a suggestion to use `sync` instead.

**Comment by kokokurak** [comment]
I don't understand your point, @franzose. We all want the framework to be as expressive and flexible as possible. This case is a no brainer, empty array with `attach` method **makes sense**. It's about being able to, for example, collect elements of the array dynamically and then attach collected IDs to the model. Sometimes this array can be empty in result, but this is fine, I don't see why `attach()` with empty array provided should throw an error.

It doesn't throw an exception, it throws SQL error, the one that I gave before.

What is your point with using `sync`? This method has totally different purpose. I'm not talking about deleting anything, but about adding relationships.

**Comment by lilybelle** [comment]
I ran into this exact same issue. Yes, sync works, but I think @kokokurak has a point.

**Comment by kokokurak** [comment]
I completely don't get it why is `sync()` even mentioned in this discussion.

**Comment by kokokurak** [comment]
Why closed?

**Comment by GrahamCampbell** [comment]
Not a bug. You shouldn't be passing an empty array to it. If you want this changing, please send a pull request for taylor to review, otherwise this issue is a waste of time.

**Comment by kokokurak** [comment]
It's a proposal. What's wrong about it?

**Comment by GrahamCampbell** [comment]
We don't want proposals for trivial things. Just send a pull.

**Comment by kokokurak** [comment]
It's not trivial. I will send pull request.

**Comment by GrahamCampbell** [comment]
> It's not trivial.

We consider anything trivial that takes less than an hour to implement. We'd like proposal issues if you want a large new feature, not some trivial technicality changing.

**Comment by kokokurak** [comment]
OK, got it.
