### ISSUE TITLE
detach() is dangerous with empty array

### ISSUE THREAD

**Issue by kokokurak** [laravel/framework#7494]
Hi guys,

surprisingly, `detach()` method has the same behavior with no arguments and with empty array. Example:
```
User::find(4)->movies()->detach();
```
That code will remove all related movies from user with id=4. I'm not sure if this is good, because it's easy to forget to pass the argument. I think `detachAll()` would be better, but this is not what I'm talking about here.

This is scary:
```
$ids = [];
User::find(4)->movies()->detach($ids);
```
This will also remove all related movies. Instead, I believe it should do nothing.

**Comment by Landish** [comment]
What about sync method?

**Comment by kokokurak** [comment]
@Landish How does it answer my request? Behavior of `sync()` is different.

**Comment by Landish** [comment]
I saw your other issue with `attach()` method and now this, that's why asked about `sync()` method. 
I wondered, if you came up with the same issue for the `sync()` method too?

**Comment by kokokurak** [comment]
No, `sync()` method works as expected. It throws error when called without parameter or with non-array parameter. When called with empty array, it removes all associations, which is understandable and correct.

**Comment by ibrasho** [comment]
Send a PR?

**Comment by wesleychang** [comment]
I had the same issue, it took me a while to work it out.  I understand that 'sync empty array' will remove all related records? But should 'detach empty array' behave differently?
