### ISSUE TITLE
Polymorphic m2m not populated on attach()

### ISSUE THREAD

**Issue by cviebrock** [laravel/framework#7496]
Here's the basic code:

```php
class Post extends Illuminate\Database\Eloquent\Model {
    public function tags() {
        return $this->morphToMany('Tag')->withTimestamps();
    }
}

class Tag extends Illuminate\Database\Eloquent\Model {
    public function taggable() {
        return $this->morphTo();
    }
}
```

Now take the following code:

```php
// assume that both of these work (i.e. the models exist)
$post = Post::find(1);
$tag = Tag::find(1);

$post->tags()->attach($tag);
```

So far so good. The relationship is being created in the `taggables` pivot table. However, if I immediately do:

```php
dd($post->tags);
```

It returns an empty collection.  `attach()` seems to create the relationship in the database but not in the current instance of the model.

This can be checked by loading the model again, or just loading the relationship:

```php
$post = Post::find(1);
// or 
$post->load('tags');

dd($post->tags);
```

And now the relationship is hydrated.

I'm not sure this worked in Laravel 4.2 either -- i.e. the relationship wasn't updated immediately after `attach()`.  I'm just looking for confirmation that this is expected behaviour.  If not, then I guess it's a bug.

**Comment by GrahamCampbell** [comment]
Probably a question for the forums. We can't process support requests here, sorry.
