### ISSUE TITLE
Morphmany query not working due to namespace backslashes

### ISSUE THREAD

**Issue by IAmJulianAcosta** [laravel/framework#7500]
I'm trying to generate a morphMany relationship:
```
namespace App\Persons\;

class Worker extends Model {
    public function personEvents () {
        return $this->morphMany('App\PersonEvent', 'sortable');
    }
}
```
and the query that is generated is this:
```
select * from `person_events` where `person_events`.`sortable_id` = 1 and `person_events`.`sortable_type` = App\Persons\Worker
```
If I run the SQL query it returns an empty result, but if I run this query (With double backslash):
```
select * from `person_events` where `person_events`.`sortable_id` = 1 and `person_events`.`sortable_type` = App\\Persons\\Worker
```

**Comment by vdotgood** [comment]
Did you solve this dude? Having the same issue.

**Comment by IAmJulianAcosta** [comment]
@vdotgood I don't remember well, but I think that double quote (") fixed it. Please let me know if that worked for you, or I will check better that issue.
