### ISSUE TITLE
Laravel forge

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#7505]
I am investigating using laravel forge.

What configurations does laravel forge do to the servers to make them as secure as possible (for the price paid)?

Also how can I delete out features that i don't need like mysql and Postgres to get maximum performance from my servers?

**Comment by rossedman** [comment]
@pjebs This isn't a conversation for the framework issues. There is information [here](https://forge.besnappy.com/laravel-forge) about what is included on the server. These are just Digital Ocean servers (or Linode) that are provisioned through automated scripts. If you want something more custom maybe look into just provisioning with those. However, I have run Wordpress installs and other types of apps through Forge and it works great.
