### ISSUE TITLE
Eloquent caches database connection configuration

### ISSUE THREAD

**Issue by uxweb** [laravel/framework#7511]
Hi, i am having some trouble trying to change a connection's database key on the fly to let a model extract information from a list of different databases, my code is as next:

```
    $users = new Illuminate\Support\Collection();
    
    // Iterate over each database name
    foreach ($databases as $db)
    {
        // Change the database name of the connection to let eloquent be in context of
        // other database
        $this->config->set('database.connections.mysql.database', $db->name);
        
        // Here i fetch all the users using the User model
        // But for the second and next databases, the model keeps connecting
        // to the first database, that gives me the same records for all the databases
        foreach(User::all() as $user)
        {
             $users->push($user);
        }
    }
```

I think that the first time i do User::all() it caches the connection, and for next uses it just pull it out from cache, but that is not the behavior i think i will have, if i tell it to change de database config, the it must change it and make the query to other database.

Is this a bug?, if is not a bug, how can this be achieved?

I pull the databases name from a sqlite database using a model that has its connection just to the sqlite database, and pointed the User model to the MySQL connection cause i only intend to change the database name of the connection.

Thank you!

**Comment by GrahamCampbell** [comment]
This is the intended behaviour. Any questions belong on the forums please.

**Comment by uxweb** [comment]
Where can i find the forums?

**Comment by GrahamCampbell** [comment]
http://lmgtfy.com/?q=laravel+forums

**Comment by uxweb** [comment]
Thank you!
