### ISSUE TITLE
Blade bug: exception in some cases when the word "or" is in a comment

### ISSUE THREAD

**Issue by tremby** [laravel/framework#7518]
I hit a strange bug earlier and have boiled it down to a failing template.

With a fresh Laravel 5 project, if I replace welcome.blade.php with this:

```php
<?php
class Foo {
	public function bar($callback) {
		return $callback();
	}
}
$foo = new Foo();
?>
{{ $foo->bar(function() {
	// Comments are okay here but if one contains the following word we get an exception.

	// or

	return "baz";
}) }}
```

An exception is thrown.

```
FatalErrorException in e05da09885ea068f3fec7a1a33d8fad4 line 16: Cannot use isset() on the result of a function call (you can use "null !== func()" instead)
```

On inspecting the compiled template we have

```php
<?php
class Foo {
	public function bar($callback) {
		return $callback();
	}
}
$foo = new Foo();
?>
<?php echo e(isset($foo->bar(function() {
	// Comments are okay here but if one contains the following word we get an exception.

	//) ? $foo->bar(function() {
	// Comments are okay here but if one contains the following word we get an exception.

	// : return "baz";
})); ?>
```

Looks like something is going quite wrong in the Blade compiler.

If you remove the comment `// or`, the file runs properly and we get output of "baz". In that case it compiles to

```php
<?php
class Foo {
	public function bar($callback) {
		return $callback();
	}
}
$foo = new Foo();
?>
<?php echo e($foo->bar(function() {
	// Comments are okay here but if one contains the following word we get an exception.

	return "baz";
})); ?>
```

The bug also exists in Laravel 4, which is where I found it, and also when the comment is the `# or` style or the `/* or */` style.

(I know it is unwise to put logic like this in a Blade template, but it's a bug all the same.)

**Comment by GrahamCampbell** [comment]
This is known I'm afraid. The or syntax is very limited. Sorry.

**Comment by tremby** [comment]
@GrahamCampbell, I'm not trying to use "or" syntax. I don't even know what "or" syntax you're referring to. My code breaks if the word "or" is in a comment -- that might happen for any number of reasons. Which ticket does this duplicate? Or if there is no duplicate, why have you closed it?

**Comment by franzliedke** [comment]
I agree with Graham, actually. You should not use PHP comments inside the output tags (`{{ ... }}`). You can use [Blade comments](http://laravel.com/docs/5.0/templates#blade-templating).

**Comment by tremby** [comment]
What exactly are you agreeing with?

Is it documented that I should not use PHP comments inside output tags?

How can I use Blade comments inside output tags?

**Comment by franzliedke** [comment]
You can't, just don't add any comments inside the output tags.

**Comment by tremby** [comment]
Is that documented anywhere?

Why not? What if I want to? Do you disagree that this is a bug?

**Comment by franzliedke** [comment]
Technically it isn't documented, but there are also no examples encouraging anything like this. You abused the fact that these tags are compiled to raw PHP, where this would be possible.

Yes, I don't think this is a bug.

**Comment by GrahamCampbell** [comment]
Not a bug, just a limitation.
