### ISSUE TITLE
route:cache does not work as expected when using nested route files.

### ISSUE THREAD

**Issue by rogue780** [laravel/framework#7522]
I organize my routes in a folder structure. For example, my app/Http/routes.php file is such:

    Route::group(['prefix' => 'api'], function() {
        require_once(app_path('Http/Routes/Api/routes.php'));
    });

then my Http/Routes/Api/routes.php file is as such:

    Route::group(['prefix' => 'v1'], function() {
        require_once(app_path('Http/Routes/Api/V1/routes.php'));
    });

Then finally my Http/Routes/Api/V1/routes.php is

    //Files
    Route::resource('file', 'Api\V1\FileController');
    //Packages
    Route::resource('package', 'Api\V1\PackageController');

When I run

    php artisan route:list

I get a complete list of these routes

    |        | GET|HEAD                       | api/v1/file                                           | api.v1.file.index      | App\Http\Controllers\Api\V1\FileController@index           |            |
    |        | GET|HEAD                       | api/v1/file/create                                    | api.v1.file.create     | App\Http\Controllers\Api\V1\FileController@create          |            |
    |        | POST                           | api/v1/file                                           | api.v1.file.store      | App\Http\Controllers\Api\V1\FileController@store           |            |
    |        | GET|HEAD                       | api/v1/file/{file}                                    | api.v1.file.show       | App\Http\Controllers\Api\V1\FileController@show            |            |
    |        | GET|HEAD                       | api/v1/file/{file}/edit                               | api.v1.file.edit       | App\Http\Controllers\Api\V1\FileController@edit            |            |
    |        | PUT                            | api/v1/file/{file}                                    | api.v1.file.update     | App\Http\Controllers\Api\V1\FileController@update          |            |
    |        | PATCH                          | api/v1/file/{file}                                    |                        | App\Http\Controllers\Api\V1\FileController@update          |            |
    |        | DELETE                         | api/v1/file/{file}                                    | api.v1.file.destroy    | App\Http\Controllers\Api\V1\FileController@destroy         |            |
    |        | GET|HEAD                       | api/v1/package                                        | api.v1.package.index   | App\Http\Controllers\Api\V1\PackageController@index        |            |
    |        | GET|HEAD                       | api/v1/package/create                                 | api.v1.package.create  | App\Http\Controllers\Api\V1\PackageController@create       |            |
    |        | POST                           | api/v1/package                                        | api.v1.package.store   | App\Http\Controllers\Api\V1\PackageController@store        |            |
    |        | GET|HEAD                       | api/v1/package/{package}                              | api.v1.package.show    | App\Http\Controllers\Api\V1\PackageController@show         |            |
    |        | GET|HEAD                       | api/v1/package/{package}/edit                         | api.v1.package.edit    | App\Http\Controllers\Api\V1\PackageController@edit         |            |
    |        | PUT                            | api/v1/package/{package}                              | api.v1.package.update  | App\Http\Controllers\Api\V1\PackageController@update       |            |
    |        | PATCH                          | api/v1/package/{package}                              |                        | App\Http\Controllers\Api\V1\PackageController@update       |            |
    |        | DELETE                         | api/v1/package/{package}                              | api.v1.package.destroy | App\Http\Controllers\Api\V1\PackageController@destroy      |            |
|

When I run 

    php artisan route:cache

however, none of the routes from these nested files are included.

I've found that if I modify \Illuminate\Foundation\Console\RouteCacheCommand so that an instance of \Illuminate\Routing\Router is injected into the constructor in the same manner as \Illuminate\Foundation\Console\RouteListCommand and then change \Illuminate\Foundation\Console\RouteCacheCommand::getFreshApplicationRoutes to just return $this->routes (I know this is not the ideal solution, but I just was trying to see if it would work), then all the routes from the nested controllers are included.

**Comment by crynobone** [comment]
It would be more useful if you include the exact code (whole class) on how you actually use this.

**Comment by rogue780** [comment]
whole class as in my routes? or as in the RouteCacheCommand?

**Comment by rogue780** [comment]
I've created a PR to demonstrate a working fix.

**Comment by crynobone** [comment]
Your `App\Providers\RouteServiceProvider`, or the exactly how did you use above code.

**Comment by rogue780** [comment]
I've uploaded an example app here: [https://github.com/rogue780/route-cache-problem](https://github.com/rogue780/route-cache-problem).

Here are the commands I ran:

    $ ./artisan route:list
    +--------+----------+-------------+------+----------------------------------------------+------------+
    | Domain | Method   | URI         | Name | Action                                       | Middleware |
    +--------+----------+-------------+------+----------------------------------------------+------------+
    |        | GET|HEAD | api/v1/test |      | App\Http\Controllers\WelcomeController@index |            |
    +--------+----------+-------------+------+----------------------------------------------+------------+
    $ ./artisan route:cache
    Route cache cleared!
    Your application doesn't have any routes.

**Comment by crynobone** [comment]
That's because you're using `require_once`.

1. Run `php artisan route:cache`
2. I would load your service providers, including `App\Providers\RouteServiceProvider`.
3. routes are loaded using `require_once`.
4. When artisan try to generate routes from a fresh application (using the same php request), it's ignore your routes file since it has been loaded before.

**Comment by rogue780** [comment]
That explanation makes no sense. route:cache shouldn't get different results than route:list

**Comment by jaychow** [comment]
what would be the proper way to implement this then? use `require` instead of `require_once`?

**Comment by brunogaspar** [comment]
@jaychow  require is the proper way.

**Comment by shiruken1** [comment]
I'm having a similar issue, but changing it from require_once to require didn't fix it for me.

Here's my RouteServiceProvider:
```
    public function map(Router $router)
    {        
        $router->group(['namespace' => $this->namespace], function ($router) {
            require_once app_path('Http/routes.php');
            require_once app_path('Http/Routes/user.php');
            require_once app_path('Http/Routes/admin.php');
            require_once app_path('Http/Routes/issues.php');
            require_once app_path('Http/Routes/dashboard.php');

            // Catch all undefined routes. Stays at the bottom since order of routes matters.
            require_once app_path('Http/Routes/404.php');
        });
```

Yet interestingly, only the user.php's routes fail to load. All the other files work just fine. 

Here are the contents of user.php:

```
Route::post('/api/user/login', 'UserController@login');
Route::get('/api/user/login', 'UserController@login');
Route::get('/api/user', 'UserController@login');
Route::get('/api/user/getByToken', 'UserController@getByToken');

// Getting RESTful
Route::resource('/api/user', 'UserController', [ 'only' => [ 'store', 'show' ]]);
```
An the main part that brought me here: even if I uncomment all of the required routes and do route:clear... it still shows up in the compiled file:

```
$ grep -nisIR "admin.php"
bootstrap/cache/compiled.php:17522:            require_once app_path('Http/Routes/admin.php');
app/Providers/RouteServiceProvider.php:42:            // require app_path('Http/Routes/admin.php');
```
This does not happen on my desktop, however, and both my desktop and laptop are current on the git branch.

Any tips would be greatly appreciated.

**Comment by GrahamCampbell** [comment]
Route cache will never work with closures.

**Comment by shiruken1** [comment]
What does that mean?

**Comment by shiruken1** [comment]
I figured out what you mean, but that's only saying "it's not the caching system".

True, but it doesn't help me get it to work on my laptop.

**Comment by shiruken1** [comment]
Well... I don't know how true your statement was, especially considering I found the route serialized in a storage/framework/sessions file.

In any case, if anyone comes across this in the future, I got it to work by creating a new folder, pulling my project from git and installing all dependencies. Something -HAD- to do with the caching...

**Comment by webmastjustin** [comment]
I didn't like having to register every route file I had, so I use this in my app/Providers/RouteSerfviceProvider.php 

`  protected function mapWebRoutes(){
        Route::group([
            'middleware' => 'web',
            'namespace' => $this->namespace,
        ], function ($router) {
            require app_path('Http/routes.php');
            foreach (\File::allFiles(app_path('Http/routes')) as $partial) {
                require $partial->getPathName();

            }
        });`

I have a folder  App\Http\routes which I break out all my routes into  i.e. login_routes.php
