### ISSUE TITLE
[5.0] Add parameters for Middleware called from Controllers

### ISSUE THREAD

**Issue by jmas** [laravel/framework#7546]
When I use Middleware in Controller I can't pass parameters to Middleware.
```php
...
public function __construct() {
  $this->middleware('rolechecker', ['only'=>['getIndex']]);
}
...
```
I can only set scope of actions where I can use this Middleware, but can't set: what roles have access for this actions.

How I can pass parameters from Controller to Middleware? I think we need more elegance and clear way to pass parameters from Routes and Controllers to Middleware.

I can describe why I need this. My Routes looks like:
```php
Route::controllers([
	'auth'=>'Auth\AuthController',
	'password'=>'Auth\PasswordController',
	'page'=>'PageController',
	'user'=>'UserController',
]);
```
Here I can add Route::group where I can pass parameter like 'permissions'. But this 'permissions' is using for all routes in Route::group. So I need to add different permissions for different Actions. Ok. I need to create separate routes for each Action. So my routes.php file will be huge only because I can't pass Middleware parameters from Controller.

I think way where we pass Middleware parameters through routes have low flexibility.

This issue is related to https://github.com/laravel/framework/issues/6470, it marked as RESOLVED and have status Closed, but I do not think so.

**Comment by GrahamCampbell** [comment]
Duplicate. Continue on the original issue.

**Comment by raumatbel** [comment]
What is solution to this problem? I have the same problem.

**Comment by Burnett01** [comment]
+Sup - same problem

Also something like http://blog.elliothesp.co.uk/coding/passing-parameters-middleware-laravel-5/ doesn't work in a Route::group

**Comment by pedrofeijo1** [comment]
just replace this:
$this->middleware('rolechecker', ['only'=>['getIndex']]);
to:
$this->middleware('rolechecker', ['only'=>'getIndex']);
