### ISSUE TITLE
getDates() does not return instance Carbon\Carbon when date is UNIX timestamp

### ISSUE THREAD

**Issue by pbrzoski** [laravel/framework#7547]
PROBLEM:
getDates() should returns instance of Carbon\Carbon from date. But if we store date as UNIX timestamp and value of timestamp is 0(January 1 1970 00:00:00 ) getDates() do not returns Carbon\Carbon instance.

Get look on test

https://github.com/laravel/framework/blob/5.0/tests/Database/DatabaseEloquentModelTest.php#L332

if we add new assert, like this

```php
$model = new EloquentDateModelStub;
$model->created_at = 0; 
$this->assertInstanceOf('Carbon\Carbon', $model->created_at);
```

test will fail.

So were is problem?
I think the problem is in this line:
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php#L2598

```php
if ($value) return $this->asDateTime($value);
```

SOLUTION:
I thnik, we should change this line to

```php
if (!is_null($value)) return $this->asDateTime($value);
```

**Comment by GrahamCampbell** [comment]
Thanks.
