### ISSUE TITLE
[Proposal] Queue::retry and Queue::listFailed()

### ISSUE THREAD

**Issue by alexw23** [laravel/framework#7553]
I'm wondering why the queue:retry logic was hard coded into the command and hasn't been put into a service so it can be called from the queue facade.

I'd like the ability to fire a job from our admin panel. Also the ability to get a list of failed jobs without having to query the DB would be good.

Therefore I propose

    Queue::retry($job_id);

    and

    Queue::retry([$job_id, $job_id]);

This will allow you to retry a job by passing the failed `$job_id`, it should also support passing of multiple `$job_id` for when you want to trigger multiple jobs. This mimics the functionality of the `queue:retry` command.

And:

    $jobs = Queue::listFailed();

This will return a collection of failed jobs which could then be outputted to a table etc. This mimics the functionality of the `queue:failed` command.

We could even have a Queue::retryAll() which would retry multiple jobs.

In creating these methods we could also refactor the queue:failed and queue:retry commands to utilise the new methods.

Please help on deciding on a naming convention for these.

**Comment by GrahamCampbell** [comment]
No need to send a proposal issue. Just send a pull.
