### ISSUE TITLE
Migrations table under a schema not found using SQLServer Grammar 

### ISSUE THREAD

**Issue by uxweb** [laravel/framework#7556]
Hi, i'm having trouble running migrations on a SQL Server database.

SQL Server supports "schemas" which are like database namespaces for the database objects (tables, views, stored proc).

I have 2 schemas in this database to separate 2 apps working in the same database with different tables each.

That is why i can't just have 1 migrations table.

To solve this i set the migrations config key to 'AppOne.migrations' in one app, and in the other to 'AppTwo.migrations'.

Then in my migrations using the Schema::create method i set the name of the table as 'AppOne.table_name' for all my migrations on AppOne, that is how i specify the schema a table belongs to.

NOTE: this has worked well when i just have one migrations table in the default schema "dbo".

Now, because i need to separate migrations of both apps, after doing my database configuration, i run the php artisan:install and it does create the table within the schema "AppOne.migrations".

But, here comes the weird part, when i run "php artisan migrate" it should not give me an error if the migrations table already exists, but it gives me an error because it tries to create it again.

That's when i looked at the source code and found that the Illuminate\Database\Schema\Grammars\SqlServerGrammar class is generating the next query to check if a table exists on the database:

select * from sysobjects where type = 'U' and name = 'AppOne.migrations'

When the Illuminte\Schema\Builder's hasTable() method is called using this SqlServerGrammar class it founds 0 records using the above query and then a create statement of a table already exists is executed and it fails.

Then i wrote another query to solve this problem, no matter if a schema is specified or not, it will find the right table:

select * from sys.objects inner join sys.schemas on objects.schema_id = schemas.schema_id where objects.type = 'U' and schemas.name + '.' + objects.name = 'AppOne.migrations'

Look how i am using another system table called "schemas" that has a record for each schema on the database, even the "dbo" default schema SQL Server uses when no schema is specified is registered there.

The 'AppOne.migrations' part is where the whole table name is passed to the grammar.

That query will work on any version of SQL Server from 2005 and above.

What do you think?, can this be changed?

Thank you!

**Comment by uxweb** [comment]
Hi, i found the method who generates this query is in the class:

Illuminate\Database\Schema\Grammars\SqlServerGrammar

        /**
	 * Compile the query to determine if a table exists.
	 *
	 * @return string
	 */
	public function compileTableExists()
	{
		return "select * from sysobjects where type = 'U' and name = ?";
	}

Hope this can help improve this.

**Comment by GrahamCampbell** [comment]
Are you saying this is working on new versions of SQLServer, but not on old versions?

**Comment by uxweb** [comment]
Hi Graham, yes, the query i wrote will only work on new versions of sql server from 2005 because of the new system tables added and the schemas feature added in 2005.

With version 7 and 2000 of SQL Server the query i wrote won't work.

Today i realize that even my query won't work if schemas are not used, so, think that is not the right solution, a combination of  both conditional sentences would work, if the table has specified a schema it will find it with the condition i have made in the query, but if a schema was not specified, then the actual condition will find it.

Then the query could be this:

    /**
 * Compile the query to determine if a table exists.
 *
 * @return string
 */
public function compileTableExists()
{
    return "select * from sys.objects inner join sys.schemas on objects.schema_id = schemas.schema_id     where objects.type = 'U' and ( schemas.name + '.' + objects.name = ? or name = ? )";
}

Here i'm using both conditions, in case a table was created with this name:

'AppOne.migrations'

Or if a table was created with this name:

'migrations'

In both cases the query will find the right table.

The actual solution for this scenario was to set the migrations table name like AppOne_migrations and for the other app will be AppTwo_migrations, both tables are going to be created in the default "dbo" schema and the current query will find them.

Why this does not happen when running the migrations to create my app tables?, because artisan does not checks if the table exists, it only checks if a migration is already applied, this is only a issue when the Builder's hasTable() method is called which right now it only happens when creating the migrations table in a schema.

Let me know what you think.

Thank you!

**Comment by GrahamCampbell** [comment]
We only support newer version of SQLServer. 08+ is all we officially support.

**Comment by uxweb** [comment]
Yep, then, the last query i added will work for the new versions, i'm not saying you have to support old versions.
