### ISSUE TITLE
Add phpdoc @method to Eloquent\Model Eloquent\Builder with Query\Builder methods

### ISSUE THREAD

**Issue by MalikinSergey** [laravel/framework#7558]
Hello,
Idea: add class-level phpdoc to Eloquent\Builder with some @method definitions. It's methods from Query\Builder, which called in eloquent builder and model, using __call()

If you think, that is good idea, I can wrote this phpdocs and create pull.

More about:

It will help IDE type hint, autocomplete and inspections:

```
class SomeModel extends Eloquent {...}
SomeModel::whereIn('id', [1,2]); // IDE (phpStorm, for example) says, that method whereIn not found in  class SomeModel
```

```
$builder = SomeModel::query(); // get eloquent builder
$builder->whereIn(); // same, IDE say method not found`
```

Example of proposed fix:
```php
<?php namespace Illuminate\Database\Eloquent;

use ...

/**
 * Class Builder
 * @method \Illuminate\Database\Query\Builder whereIn(string $column, mixed $values, string $boolean, bool $not)
 */

class Builder ...
```

Refs:
http://phpdoc.org/docs/latest/references/phpdoc/tags/method.html
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Builder.php#L920
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php#L3314

**Comment by GrahamCampbell** [comment]
I don't think this is ever going to happen. it defeats the object of using php's dynamic __call stuff if we're going round adding static stuff.

**Comment by franzliedke** [comment]
This is aimed at IDEs and working around the limitations of `__call()` etc. when it comes to code analysis, right?

What are you referring to by "static"?

**Comment by GrahamCampbell** [comment]
> What are you referring to by "static"?

I was just meaning no need to define all the methods all over again.

**Comment by GrahamCampbell** [comment]
It makes it hard to maintain because I'm 100% certain people will send pulls modifing code or adding new methods, and not update all the method docblocks. They are inherently unmaintainable.

**Comment by franzliedke** [comment]
That's the price we pay for beautiful code. ;)

And thanks, that's what I thought.

**Comment by halaei** [comment]
:+1: 
I really need this.

**Comment by opilo** [comment]
:+1:

**Comment by miladr** [comment]
I couldn't agree more :+1:

**Comment by barryvdh** [comment]
For phpStorm there is also the `@mixin` tag, which 'fake-extends' the entire class.
See https://github.com/phpDocumentor/fig-standards/issues/35

**Comment by Anahkiasen** [comment]
> For phpStorm there is also the @mixin tag, which 'fake-extends' the entire class.

This. This is the most appropriate phpdoc for decorator classes like this one

**Comment by barryvdh** [comment]
Yes but it's just (partially) implemented by phpStorm and isn't in the new phpdoc/FIG spec, so perhaps people should provide support in the linked issue ;)

**Comment by halaei** [comment]
:+1:  for barryvdh and `@mixin` :)

**Comment by shehi** [comment]
+1 Need this as well. We need to sort this out, otherwise its hard to do proper code inspection with IDE. And IMHO the solution shouldn't be for one-specific-IDE only!

**Comment by GrahamCampbell** [comment]
phpdoc is for people, not for ides.
