### ISSUE TITLE
current working directory is different if you are running artisan serv or forge

### ISSUE THREAD

**Issue by thecotne** [laravel/framework#7561]
issue is that if you uploaded file and then use move method on UploadedFile object
you are getting different results
as example if you move to `uploaded/file.txt`
when using `artisan serv` you will have file.txt at `project-folder/uploaded/file.txt`
and when using forge file will be in `project-folder/public/uploaded/file.txt`

i guess because when using forge framework starts from public/index.php
and when using `artisan serv` it starts from artisan file

i have win 10 and php 5.6.2

 also i tested and printed current working directory (with getcwd)
on `artisan serv` it returns project directory
on forge it is `project directory/public`

**Comment by suwardany** [comment]
#7222 should fix that issue.
