### ISSUE TITLE
Application::setProvider

### ISSUE THREAD

**Issue by mertkabadayi** [laravel/framework#7564]
I think you can add a new service provider, type of the application class. Thus, the application method of recording was able to solve the case. I would like to share a simple code to do this.

https://gist.github.com/mertkabadayi/546fc2d83c4811a9389a

I apologize for the English.

**Comment by crynobone** [comment]
Wouldn't this already do it?

```php
$this->app->afterResolving('Foo\Bar\Support\ServiceProvider', function ($provider) use ($widget, $provider) {
    $provider->setWidget($widget);
    $provider->setComponent($component);
});
```

**Comment by mertkabadayi** [comment]
This is very good. Thank you very much for the information.
