### ISSUE TITLE
[Proposal] Custom attribute names by form requests

### ISSUE THREAD

**Issue by MrAtiebatie** [laravel/framework#7569]
I needed custom attribute names by form requests. Actually the same thing as the messages function only for attribute names. I've tried to make a pull request but I'm pretty new to GIT and haven't had much time to get into it for now. Changes are made to Illuminate\Foundation\Http\FormRequest.php

    <?php namespace Illuminate\Foundation\Http;

	use Illuminate\Http\Request;
	use Illuminate\Http\Response;
	use Illuminate\Http\JsonResponse;
	use Illuminate\Routing\Redirector;
	use Illuminate\Container\Container;
	use Illuminate\Validation\Validator;
	use Illuminate\Http\Exception\HttpResponseException;
	use Illuminate\Validation\ValidatesWhenResolvedTrait;
	use Illuminate\Contracts\Validation\ValidatesWhenResolved;

	class FormRequest extends Request implements ValidatesWhenResolved {

		use ValidatesWhenResolvedTrait;

		/**
		 * The container instance.
		 *
		 * @var \Illuminate\Container\Container
		 */
		protected $container;

		/**
		 * The redirector instance.
		 *
		 * @var \Illuminate\Routing\Redirector
		 */
		protected $redirector;

		/**
		 * The URI to redirect to if validation fails.
		 *
		 * @var string
		 */
		protected $redirect;

		/**
		 * The route to redirect to if validation fails.
		 *
		 * @var string
		 */
		protected $redirectRoute;

		/**
		 * The controller action to redirect to if validation fails.
		 *
		 * @var string
		 */
		protected $redirectAction;

		/**
		 * The key to be used for the view error bag.
		 *
		 * @var string
		 */
		protected $errorBag = 'default';

		/**
		 * The input keys that should not be flashed on redirect.
		 *
		 * @var array
		 */
		protected $dontFlash = ['password', 'password_confirmation'];

		/**
		 * Get the validator instance for the request.
		 *
		 * @return \Illuminate\Validation\Validator
		 */
		protected function getValidatorInstance()
		{
			$factory = $this->container->make('Illuminate\Validation\Factory');

			if (method_exists($this, 'validator'))
			{
				return $this->container->call([$this, 'validator'], compact('factory'));
			}

			return $factory->make(
				$this->all(), $this->container->call([$this, 'rules']), $this->messages(), $this->attributes()
			);
		}

		/**
		 * Handle a failed validation attempt.
		 *
		 * @param  \Illuminate\Validation\Validator  $validator
		 * @return mixed
		 */
		protected function failedValidation(Validator $validator)
		{
			throw new HttpResponseException($this->response(
				$this->formatErrors($validator)
			));
		}

		/**
		 * Determine if the request passes the authorization check.
		 *
		 * @return bool
		 */
		protected function passesAuthorization()
		{
			if (method_exists($this, 'authorize'))
			{
				return $this->container->call([$this, 'authorize']);
			}

			return false;
		}

		/**
		 * Handle a failed authorization attempt.
		 *
		 * @return mixed
		 */
		protected function failedAuthorization()
		{
			throw new HttpResponseException($this->forbiddenResponse());
		}

		/**
		 * Get the proper failed validation response for the request.
		 *
		 * @param  array  $errors
		 * @return \Symfony\Component\HttpFoundation\Response
		 */
		public function response(array $errors)
		{
			if ($this->ajax() || $this->wantsJson())
			{
				return new JsonResponse($errors, 422);
			}

			return $this->redirector->to($this->getRedirectUrl())
	                                        ->withInput($this->except($this->dontFlash))
	                                        ->withErrors($errors, $this->errorBag);
		}

		/**
		 * Get the response for a forbidden operation.
		 *
		 * @return \Illuminate\Http\Response
		 */
		public function forbiddenResponse()
		{
			return new Response('Forbidden', 403);
		}

		/**
		 * Format the errors from the given Validator instance.
		 *
		 * @param  \Illuminate\Validation\Validator  $validator
		 * @return array
		 */
		protected function formatErrors(Validator $validator)
		{
			return $validator->errors()->getMessages();
		}

		/**
		 * Get the URL to redirect to on a validation error.
		 *
		 * @return string
		 */
		protected function getRedirectUrl()
		{
			$url = $this->redirector->getUrlGenerator();

			if ($this->redirect)
			{
				return $url->to($this->redirect);
			}
			elseif ($this->redirectRoute)
			{
				return $url->route($this->redirectRoute);
			}
			elseif ($this->redirectAction)
			{
				return $url->action($this->redirectAction);
			}

			return $url->previous();
		}

		/**
		 * Set the Redirector instance.
		 *
		 * @param  \Illuminate\Routing\Redirector  $redirector
		 * @return \Illuminate\Foundation\Http\FormRequest
		 */
		public function setRedirector(Redirector $redirector)
		{
			$this->redirector = $redirector;

			return $this;
		}

		/**
		 * Set the container implementation.
		 *
		 * @param  \Illuminate\Container\Container  $container
		 * @return $this
		 */
		public function setContainer(Container $container)
		{
			$this->container = $container;

			return $this;
		}

		/**
		 * Set custom messages for validator errors.
		 *
		 * @return array
		 */
		public function messages()
		{
			return [];
		}

		/**
		 * Set custom attribute names for validator errors.
		 *
		 * @return array
		 */
		public function attributes()
		{
			return [];
		}

	}

**Comment by tomschlick** [comment]
Sorry but this isnt helpful unless its via pull request. Too hard to tell what has changed. You can make it easy on yourself if you browse to the current file on github (https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Http/FormRequest.php) and click the little pencil icon. 

That will fork the repo and allow you to make your own changes via your browser. Then at the bottom you add a commit message about what you changed and it will automatically create a pull request for you.

**Comment by MrAtiebatie** [comment]
You're totally right, it's kinda a bad proposal, my bad. I've created a pull request the way you explained (didn't knew it was that easy...). Thanks!

**Comment by tomschlick** [comment]
Awesome! You'll probably want to close this issue so that all future conversation happens in the new pull request instead. You can do so with the Close button below the comment box.
