### ISSUE TITLE
Schema bug when adding autoincrement and FK in PK

### ISSUE THREAD

**Issue by fish131** [laravel/framework#7570]
I have this situation where I want to make an identifying relationship (the FK is in the PK) and the Schema doesn't allow me. It seems that it builds the SQL wrong...

```php
	public function up()
	{
        Schema::create('my_first_table', function(Blueprint $table){
            $table->increments('id');
        });
        Schema::create('my_second_table', function(Blueprint $table){
            $table->increments('id');
            $table->unsignedInteger('my_first_table_id');
            $table->foreign('my_first_table_id')->references('id')->on('my_first_table');
            $table->primary(['id', 'my_first_table_id']);
        });
	}
```

I've tried `$table->primary(['my_first_table_id']);` and also some variations on the `$table->increments('id')`, but with no success.

And I get the following exception:
```
[Illuminate\Database\QueryException]                                  
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `my_second_table` add primary key my_second_table_id_my_first_table_id_primary(`id`, `my_first_table_id`))
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined
```

This bug was already posted here, but it wasn't a test case and it wasn't readable and Taylor closed it. I can't find it...

**Comment by rkgrep** [comment]
It's not a bug.
1. Autoincrement actually supposed to be unique across the table, so it is enough to have only one field as primary key. If you need additional indexing, add another unique index or make your own incrementing procedures.
2. Supposed schema is not compatible with SQLite (and maybe with some other SQL syntaxes), so this change will cause incompatibility issues.

Anyway, you can use Schema::alter to drop the primary key and create a new one. This should work if you are sure that SQLite will not be used in your app.

**Comment by fish131** [comment]
1. MySQL workbench generates FK columns in PK, and so does SQLYog or any other software.. and you can do this in the CLI, too. Correct me if I'm wrong, but I think that FK's in PK are the fastest, not that it matters 95% of the times.

2. The `Schema` should tell the difference between RDBMS and throw an error if the feature is not supported. There are a lot of things incompatible between SQL dialects, RDBMS', engines, etc., and a there are a lot of multi-purpose SQL GUI software that tell the difference. It's not the syntax, it's the library.

I know the workaround... that's not the purpose of the of this issue. A lot of bugs in a lot of software have workarounds, this is a bad argument, rkgrep!
