### ISSUE TITLE
Undefined index: timezone

### ISSUE THREAD

**Issue by zjhzxhz** [laravel/framework#7588]
In `/vendor/laravel/framework/src/Illuminate/Foundation/start.php`:

```
date_default_timezone_set($config['timezone']);
```

I've tried add following lines to `/app/config/app.php`:
```
'timezone' => 'UTC';
```
But this doesn't work;

Laravel 4.2 with PHP 5.6.5(HHVM 3.5.1 also not working).

**Comment by GrahamCampbell** [comment]
I can't replicate. Also, 4.2 is non-longer supported ex security and larger issues that are reproducible.

If you can't fix this, try asking on the forums.
