### ISSUE TITLE
Setting app:name with a beginning backslash breaks the change

### ISSUE THREAD

**Issue by tpavlek** [laravel/framework#7591]
If you set app namespace via

```
php artisan app:name '\Some\Namespace\MyApp'
```

will incorrectly set the namespace (to exactly what you passed it). But afterwards app:name throws ReflectionExceptions and fails, meaning if you don't have a git history this is a very intensive problem to fix.

Since this is a common way to represent namespaces, the app:name command should strip preceding backslashes if they are present.

**Comment by GrahamCampbell** [comment]
You must not use a leading slash.

**Comment by GrahamCampbell** [comment]
> Since this is a common way to represent namespaces

It is incorrect. Classes are defined without a leading slash. Using one is incorrect.
