### ISSUE TITLE
[5.0] Eloquent collection throws error on $collection->contains('key', 'value')

### ISSUE THREAD

**Issue by MLinek** [laravel/framework#7596]
Simple call (User is a model):

    User::all()->contains('username', 'test')

It will always fail for any Eloquent collection. The reason is  [this](https://github.com/laravel/framework/blob/bf9838ebe2a15e894503cfdca16e5c51bb53c1b2/src/Illuminate/Support/Collection.php#L86-L89). It will call "contains" method of [Eloquent Collection](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Collection.php#L68-L76) which does not support closure and results in an error.

Am I missing something or is it clearly a bug?

**Comment by ibrasho** [comment]
This should be closed now?
