### ISSUE TITLE
[5.0] Validator each() not build nested rules correctly

### ISSUE THREAD

**Issue by erickubenka** [laravel/framework#7598]
Hi guys,

during validation of arrays with `Validator->each()`I encountered a little bug during the build nested keys routine. 
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Validation/Validator.php#L266 

**My input**
````
'pairs' => [
    ['foo' => 'startOfLine', 'value' => '']
]
````

**My validate each method:**
```php
$v = \Validator::make($input, ['pairs' => 'required|array']);

$v->each('pairs', [
    'keyword' => 'required',
    'value' => 'required'
]);
```

**Generated rules are:**
```php
[
    'pairs' => ['required', 'array'],
    'pairs.0' => ['required', 'required']
]
```

**In my opinion generated rules should are:**
```php
[
    'pairs' => ['required', 'array'],
    'pairs.0.keyword' => ['required']
    'pairs.0.value' => ['required']
]
```

**My fix for this would be to use this:**
```php
foreach ($rules as $ruleKey => $ruleValue)
{
    $this->mergeRules("$attribute.$dataKey.$ruleKey", $ruleValue);
}
```

**instead of this:**
```php
foreach ($rules as $ruleValue)
{
    $this->mergeRules("$attribute.$dataKey", $ruleValue);
}
```

If I should provide further information, add a failing test, or create a pull request, please let me know.

Best regards,
Eric

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by taylorotwell** [comment]
Wouldn't that break the first example?

**Comment by erickubenka** [comment]
Yea. The PR breaks a test. Sorry for that. Didn't thought about that before.
But in conclusion both behaviors seems strange to me. 
I will have a further look tomorrow.
