### ISSUE TITLE
Laravel 5.0 : Auth::check() return false inside Serviceprovider->boot() ?!! Thanks 

### ISSUE THREAD

**Issue by samiboukadida** [laravel/framework#7600]

**Comment by crynobone** [comment]
Yes it suppose to return null because booting service providers is done much earlier then loading session (middleware).

**Comment by shemusok** [comment]
@crynobone, it's strange, cause i'm using Auth inside event handler closure, which is executed
after auth middleware. Notice: $user arg to this closure is ok.

**Comment by crynobone** [comment]
That because the event is fired before setting the user. <https://github.com/laravel/framework/blob/5.0/src/Illuminate/Auth/Guard.php#L442-L444>

I don't see why you should still need to use `Auth::user()` when `$user` provide the same expected value.

**Comment by shemusok** [comment]
Because it's supposed to work, at least - according to documentation. 
Nothing said about 'facades are ok, except cases of event handling'.

**Comment by GrahamCampbell** [comment]
> Nothing said about 'facades are ok, except cases of event handling'.

This has nothing to do with facades.
