### ISSUE TITLE
[Bug] Eloquent classes are case insensitive on windows systems

### ISSUE THREAD

**Issue by prady00** [laravel/framework#7602]
If there are two models 'X' and 'Y', with Many2Many relationships defined as below -

<todo insert code here, I will edit this in sometime>

The relationships were working good on windows system but when I made it live on linux system,
class not found error occured.

<todo insert windows system details, I will edit this in sometime>
<todo insert linux system details, I will edit this in sometime>

So, This is feature or bug for windows user?

**Comment by deefour** [comment]
Case sensitivity for PHP is OS-specific. Windows is case-insensitive.

**Comment by prady00** [comment]
Thanks. I didn't knew this. Can we somehow make it uniform for the Laravel relationships?

**Comment by GrahamCampbell** [comment]
Not a bug. Php is case insensitive when resolving classes, however, your autoloader may not be depending on the os.
