### ISSUE TITLE
Auth::user returns null inside auth.login event handler

### ISSUE THREAD

**Issue by shemusok** [laravel/framework#7605]
**Auth::user** returns **null** inside **auth.login** event handler.
However, $user arg of event handler is filled with correct value.
**app/Providers/EventServiceProvider.php**:
```php     
// ...
public function boot(DispatcherContract $events) {
    parent::boot($events);
    Event::listen('auth.login', function($user) {
       // next will log 'null' and 'ok'
        Log::debug(isset(Auth::user()) ? "ok" : "null");
        Log::debug(isset($user) ? "ok" : "null");
    });
}
// ...
```
*May be not always, but somehow during standart password reset logic*

**Comment by crynobone** [comment]
<https://github.com/laravel/framework/issues/7600#issuecomment-75882934>
