### ISSUE TITLE
[Question\Proposal] Qualified column names

### ISSUE THREAD

**Issue by Flightfreak** [laravel/framework#7607]
```php
User::find(1)->roles()->join('floors', function($on){
    $on->where('floors.id','=','roles.floor_id');
    $on->where('floors.active',1);
})->update(['foo'=>'bar']);
```
If both the Roles and Floors model have timestamping active (`public $timestamps = true;`), this query will return a Integrity constraint violation because the table names are not set per default on the colum names in the resulting update query.

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Builder.php#L331

Redefining the timestamp constants to qualified column names (read: including table name), or reseting the timestamp property solves this particular case, but what is the reason for not using qualified column names in general as is already done in the softdeleting trait?

**Comment by GrahamCampbell** [comment]
We don't process proposal issues, sorry.
