### ISSUE TITLE
firstOrNew on relations aren't assigning the attributes searched for to the new instance

### ISSUE THREAD

**Issue by phaza** [laravel/framework#7614]
Hi,

I really tried to fix this, but unfortunately I wasn't sure how to write a test for this.
When you run firstOrNew on a relation, it isn't assigning the attributes searched for to the new object (if first() returns null)

[BelongsToMany.php#L560](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L560)
[HasOneOrMany.php#L214](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L214)
[MorphOneOrMany.php#L128](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Relations/MorphOneOrMany.php#L128)

I assume newInstance should really be newInstance($attributes)

Compared to how it works on normal models:
[Eloquent/Model.php#L595](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php#L595)

I was able to write a test that tested firstOrNew worked as expected on a normal Model, but when it got to relations it got too complicated to me, so I gave up :/

**Comment by Flightfreak** [comment]
I'll push a fix for it with tests asap.

**Comment by GrahamCampbell** [comment]
I think this is fixed now.
