### ISSUE TITLE
Service Provider makes invalid assumptions about Application class

### ISSUE THREAD

**Issue by PatrickRose** [laravel/framework#7615]
I'm currently unit testing a service provider so I can support Laravel 4 and Laravel 5 with more confidence, but I'm unable to mock out an instance of the Application to test that the correct fields are added to the container because the base ServiceProvider uses `$app['config']` in several places.

Since the Application interface doesn't implement the ArrayAccess, that is invalid in my test. Is there a reason that any instances could not be replaced with `$app->make()`? It makes the code messier but makes unit testing that things are bound correctly much easier.

**Comment by ibrasho** [comment]
Shouldn't your Application extend the Container class?

**Comment by PatrickRose** [comment]
I've not got a dependency on the container module (I'm working on a library).

**Comment by crynobone** [comment]
```php
$app->shouldReceive('offsetGet')->with('config')->andReturn($config = m::mock('\Illuminate\Contracts\Config\Repository'));
```

**Comment by PatrickRose** [comment]
I'm fairly certain that won't work? The Mockery double won't implement
ArrayAccess and so will fall over.

On 26 February 2015 at 09:24, Mior Muhammad Zaki <notifications@github.com>
wrote:

> $app->shouldReceive('offsetGet')->with('config')->andReturn($config = m::mock('\Illuminate\Contracts\Config\Repository'));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/7615#issuecomment-76146302>.
>



-- 
Regards

Patrick Rose

**Comment by ibrasho** [comment]
Much work is needed to ensure that Laravel components actually use contracts-defined methods only.

You will find this issue in a lot of places, since the transition was made from concrete classes to interfaces, we might be type hinting contracts but we are using methods not defined in the contract.

**Comment by crynobone** [comment]
> I'm fairly certain that won't work? The Mockery double won't implement
ArrayAccess and so will fall over.

Have you even tried it?

**Comment by crynobone** [comment]
`m::mock('\Illuminate\Contracts\Foundation\Application', '\ArrayAccess');`

https://github.com/orchestral/kernel/blob/master/tests/Http/RouteManagerTest.php#L21 as an example.

**Comment by PatrickRose** [comment]
That doesn't fix the problem as far as I'm concerned, all it does is just avoid the problem (and also what if someone wants to use Prophecy? etc)

If the ServiceProvider is expecting an instance of `\Illuminate\Contracts\Foundation\Application` and then uses it like `$this->app['config']` then we're making an assumption that isn't always going to be true. Since one could just run `sed -i 's|app\[(.+)\]|app->make($1)|'` (or whatever the sed syntax is for groups) why shouldn't that be done? I'll happily submit a PR to do so.
