### ISSUE TITLE
Make command handler reflection more flexible

### ISSUE THREAD

**Issue by SharpNoiZy** [laravel/framework#7619]
Hi

I want to write a small event souring framework based on the laravel 5 command and event system.
For that framework I want to have Aggregate classes, which handle multiple commands and events for their type, for example UserAggregate should have:
public handle(RegisterUser $command);
public handle(SignUserIn $command);

But the reflection to search the command handler searches for a "[command name]Handler" class.
And there is no way to change this, correct? (Nothing found in the documentation)

Kind regards

**Comment by GrahamCampbell** [comment]
Unfortunately we cannot process support requests here, thought is is definitely configurable. Take a look at the internals of Dispatcher::simpleMapping and just replicate that to suit what you need.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Bus/Dispatcher.php#L371

**Comment by SharpNoiZy** [comment]
Thanks, this would be a great hint for the docs.
