### ISSUE TITLE
Session + Third Party Packages

### ISSUE THREAD

**Issue by chadtomkiss** [laravel/framework#7620]
Hi,

The fact that Session data isn't written until after the request has returned means that it does not get saved when using some third party libraries such as:

https://github.com/thephpleague/oauth1-client

This is due to the way they redirect to Twitter etc:

    header('Location: '.$url);
    exit;

I'm currently calling Session::save() before the library redirects which fixes the issue but thought I would give a heads up.

**Comment by GrahamCampbell** [comment]
```
header('Location: '.$url);
exit;
```

That's going to screw up everything.

Sorry we can't process support requests here. Try the forums.
