### ISSUE TITLE
Route model binding not fetching datas

### ISSUE THREAD

**Issue by acaron** [laravel/framework#7633]
I'm having the exact same problem as stated here:
http://stackoverflow.com/questions/28446494/laravel-5-documenation-route-model-binding

It was working a few days ago and now it won't fetch the datas. The model is retrieve but empty. 

When I do $user->role, this:

**Is not working anymore:**
```
public function boot(Router $router)
{
	parent::boot($router);

	$router->model('user', 'App\User');
}
```

**Is working:**
```
Route::bind('user', function($value)
{
    return App\User::find($value);
});
```

**Comment by JoostK** [comment]
Well, if you look at how `$router->model` just delegates to `$router->bind` with a closure much like your working example, this should just be working. Also I don't recall a change recently that may have caused this.

Can you perhaps dive into the closure in `$router->model` and `dd` to find out what is going on. I am suspecting something else is going on.

**Comment by acaron** [comment]
If I use `$router->model`, I get this from `$user`:

```
User {#232 ▼
  #dates: array:1 [▼
    0 => "deleted_at"
  ]
  #fillable: array:5 [▼
    0 => "first_name"
    1 => "last_name"
    2 => "email"
    3 => "password"
    4 => "role_id"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: null
  #table: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: []
  #original: []
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▼
    0 => "*"
  ]
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: false
  #forceDeleting: false
}
```

If I use `$router->bind`, I get this from `$user`:
```
User {#192 ▼
  #dates: array:1 [▼
    0 => "deleted_at"
  ]
  #fillable: array:5 [▼
    0 => "first_name"
    1 => "last_name"
    2 => "email"
    3 => "password"
    4 => "role_id"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: null
  #table: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:10 [▼
    "id" => 3
    "created_at" => "2015-02-19 17:40:03"
    "updated_at" => "2015-02-19 17:40:03"
    "deleted_at" => null
    "role_id" => 3
    "first_name" => "Foo"
    "last_name" => "Bar"
    "email" => "string"
    "password" => "string"
    "remember_token" => null
  ]
  #original: array:10 [▼
    "id" => 3
    "created_at" => "2015-02-19 17:40:03"
    "updated_at" => "2015-02-19 17:40:03"
    "deleted_at" => null
    "role_id" => 3
    "first_name" => "Foo"
    "last_name" => "Bar"
    "email" => "string"
    "password" => "string"
    "remember_token" => null
  ]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▼
    0 => "*"
  ]
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  #forceDeleting: false
}
```

Hope that part help, I will dig further into it. Thank you!

**Comment by janhenkgerritsen** [comment]
Can you provide the code of your model classes? I just did a clean install of Laravel with the default User model without associations and everything works as expected in that case.

**Comment by acaron** [comment]
I don't know what I did (except doing a composer update) but it is working again. I don't know what was causing it so my browser, Behat and two other peoples on StackOverflow had the same problem. I will watch closely if it happen again.

Here is my `User` model:
```
<?php namespace App\Models\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword, ACLTrait, SoftDeletes;

    /**
	 * @var array
	 */
    protected $dates = ['deleted_at'];

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['first_name', 'last_name', 'email', 'password', 'role_id'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	/**
	 * role() one-to-one relationship method
	 *
	 * @return QueryBuilder
	 */
	public function role()
	{
		return $this->belongsTo('App\Models\Auth\Role');
	}

	/**
	 * @return string
	 */
	public function getName()
	{
		return $this->first_name . ' ' . $this->last_name;
	}

}
```

**Comment by GrahamCampbell** [comment]
This belongs on the forums please. Only submit issues here if you have an isolated issue to report.

**Comment by piyushpatil027** [comment]
hi ,

I'm having the exact same problem and my case $router->bind also not working.

 I get this :

Register {#198 ▼
  #table: "tbl_registration"
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: []
  #original: []
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: false
}

**Comment by msieprawski** [comment]
@piyushpatil027 and @acaron - I've got the same problem but only on my public server. It was caused by wrong PHP version. I had 5.4.29 on server but on local env I had 5.6.9. After changing PHP version and running composer dump-autoload, composer update, artisan clear-compiled and artisan optimize everything works as expected.
