### ISSUE TITLE
Unclear behavior for query scope returning null/empty/false things

### ISSUE THREAD

**Issue by alexandre-butynski** [laravel/framework#7643]
I want to write a query scope that return an array of things (id => name) and not the query builder. To simplify, it's like if I want to overwrite the `lists` method. The issue come when I return an empty array (and also occur when I return, `false`, `0` or `""`).

That's because the `callScope` method return the query builder itself when the method return something falsy :

```PHP
protected function callScope($scope, $parameters)
{
	array_unshift($parameters, $this);

	return call_user_func_array(array($this->model, $scope), $parameters) ?: $this;
}
```

First, I thought it was a bug and want to propose a PR but the stub class in the current test case confused me. It shows that we can use a query scope and returning nothing. This is an undocumented possibility  :

```PHP
class EloquentBuilderTestScopeStub extends Illuminate\Database\Eloquent\Model {
	public function scopeApproved($query)
	{
		$query->where('foo', 'bar');
	}
}
```

Then... is that an heresy to return something else than a query builder ? Can we build something more robust ? Am I missed an other way to do something like that ?

I think that it could be really great to build query scopes that act more or less like `find`, `count`, `exists` or `lists` methods.

**Comment by MaartenStaa** [comment]
I guess the query scopes weren't really designed for what you're trying to do, but changing that ternary operator to do a strict check for null would, I suppose, do the trick here.
