### ISSUE TITLE
Router accepts anything before `/index.php/`

### ISSUE THREAD

**Issue by lud** [laravel/framework#7644]
Hi, 

I've found that, even if I use URL rewriting, I can still access the site using `domain/index.php/my/route/url`.

Is there a way to disable this ? I think if I want to put an HTTP cache in front of my site, It would store two cache items for one single page. And it leads to duplicate content issues.

I also found that in this case, anyone can create many URLs for a single page. See  http://laravel.com/HELLO-I-AM-THERE/index.php/docs/5.0

Is that a possible bug, or do you have some strategies to avoid this ?

Thank you

**Comment by GrahamCampbell** [comment]
This belongs on the foums please, not the bug tracker
