### ISSUE TITLE
Elixir version not copying .map-files

### ISSUE THREAD

**Issue by tholu** [laravel/framework#7650]
When using mix.version(), the .map files are not copied and thus result in a 404-error.

**Comment by hownowbrowncow** [comment]
Map files paths are set in the js/css file they are for. IE: `/*# sourceMappingURL=style.css.map */` is in the bottom of style.css. So even if they where included in the versioning process the correct file will not be included unless to map path was updated in the associated css/js file.

Easy solution; Use the `.copy()` elixir ingredient to move the file manually so the path in the css/js file is correct. IE `.copy('./path/to/style.css.map', './public/build/css/style.css.map`)`. 

Also elixir has it's own repository so any real issues should be submitted there. https://github.com/laravel/elixir

**Comment by tholu** [comment]
There was a comment by 'Nick' here (I got notified via email), but it seems to be deleted.

```
Map files paths are set in the js/css file they are for. IE: /*# sourceMappingURL=style.css.map */ is in the bottom of style.css. So even if they where included in the versioning process the correct file will not be included unless to map path was updated in the associated css/js file.

Easy solution; Use the .copy() elixir ingredient to move the file manually so the path in the css/js file is correct. IE .copy('./path/to/style.css.map', './public/build/css/style.css.map)`.

Also elixir has it's own repository so any real issues should be submitted there. https://github.com/laravel/elixir
```

I tried mix.copy() but somehow it did not work (how can I debug this?). And if I use .version, it really should automatically copy the .map-files. Also I would happily submit issues for elixir in its own repository, but issue submission seems to be disabled there (like in all other laravel repos).

**Comment by hownowbrowncow** [comment]
Sorry i didn't realize sourcemap support just got added to elixir! my answer is probably no a valid response.

**Comment by tholu** [comment]
No problem, I tried the .copy() workaround, but somehow it did not work (see http://stackoverflow.com/questions/28767628/how-to-debug-laravel5-elixir-gulpfile-js).

**Comment by xewl** [comment]
+1
.map files aren't copied over/duplicated to the build folder when using elixir's mix.version()
Resulting in a NotFoundHttpException with code 500 Response (? - prolly something I can fix),
which of course ends up in the clients console in Chrome etc.

If the /build version is loaded as the link's source, why isn't the .map taken in consideration when copying over the build?

I also upvoted tholu's StackOverflow question as there's no solution yet (as of ~2h ago).

**Comment by thelfensdrfer** [comment]
+1

**Comment by Ostendorf** [comment]
Broken path to sourcemap brought me here, but the copy 'hack' fixed it for me.
I did notice an error however in the code that was specified above. There was a missing '.
This works for me:

```
elixir(function (mix) {
	mix.less(['theme.less'], 'public/css/')
		.version(["css/theme.css"])
		.copy('public/css/theme.css.map', 'public/build/css/theme.css.map');
});
```

I do however would like to see this fixed in Elixer version function.

**Comment by JeffreyWay** [comment]
Elixir issues should be submitted to the laravel/elixir repo, not here.

This does seem to be a bug, though. We can fix that. Are people liking the sourcemaps support?

**Comment by tholu** [comment]
@JeffreyWay Have you read my posts? Please reopen.

>  Also I would happily submit issues for elixir in its own repository, but issue submission seems to be disabled there (like in all other laravel repos).

**Comment by taiyaei** [comment]
+1.

Either laravel/elixir should enable issue submissions or this should be re-opened, probably the former in my opinion.

**Comment by JeffreyWay** [comment]
Someone can submit a PR to laravel/elixir. 

Otherwise, I'll fix it myself this week.

**Comment by tholu** [comment]
@JeffreyWay Can you reopen this issue until it is fixed then? Or enable issue submissions on laravel/elixir?

**Comment by JeffreyWay** [comment]
No. I'm going to push a commit to fix this today.

**Comment by tholu** [comment]
@JeffreyWay That's great! However, in my opinion issues should be closed after a fix was committed to prevent them from being forgotten.
