### ISSUE TITLE
View not sharable from middleware

### ISSUE THREAD

**Issue by nonamez** [laravel/framework#7656]
So, actually I do not know whether it is a bug or simply this feature is not implemented... For example I want to share my locale variable in the all views so I create middleware called Locale and register it Kernel globally for all routes. The I tried to share it via View::share and View\Factory and every time I get *Trying to get property of non-object*

```php
<?php namespace App\Http\Middleware;

use App;
use View;
use Config;
use Closure;

use Illuminate\View\Factory as ViewFactory;

class Locale {

	public function __construct(ViewFactory $view_factory)
	{
		$this->view_factory = $view_factory;
	}

	public function handle($request, Closure $next)
	{
		$locale = $request->segment(1);
		
		if (in_array($locale, config()->get('app.locales')))
			app()->setLocale($locale);
		else
			app()->setLocale(config()->get('app.fallback_locale'));

		$this->view_factory->share('locale', app()->getLocale());
		View::share('locale', app()->getLocale());

		return $next($request);
	}

}```

**Comment by GrahamCampbell** [comment]
I don't know what you're doing here? You've dependency injected the view factory, then you've used the facade to the view factory too?

**Comment by GrahamCampbell** [comment]
You should avoid using those aliases too. You should import `Illuminate\Support\Facades\View`, not just `View`.

**Comment by nonamez** [comment]
I just tried two things. None of them worked...

**Comment by GrahamCampbell** [comment]
Maybe view composers are what you are looking for?
