### ISSUE TITLE
No contract for session

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#7659]
There's no session contract interface in https://github.com/laravel/framework/tree/5.0/src/Illuminate/Contracts but only the SessionInterface in https://github.com/laravel/framework/blob/5.0/src/Illuminate/Session/SessionInterface.php.

For consistency, there should be also a Illuminate\Contracts\Session\Store interface.

**Comment by GrahamCampbell** [comment]
Duplicate, sorry.
