### ISSUE TITLE
dotenv DB_PASSWORD=null

### ISSUE THREAD

**Issue by a-komarev** [laravel/framework#7660]
I'm using a DB_PASSWORD=null on a test server, and dotenv thinking that my password shouldn't be sent, but it is wrong. My password is a 4 letters word: `null`.
I've tried to escape it: `'null' "null" \null (null)` but no luck. In most cases it's telling me in MySQL connection: `USING PASSWORD: NO`

https://github.com/vlucas/phpdotenv/issues/71

**Comment by GrahamCampbell** [comment]
Try `""`.

**Comment by a-komarev** [comment]
It's same: `Access denied for user 'root'@'localhost' (using password: NO)`. My password is 4 letters string: `null`, but it's impossible to assign - framework thinking it's empty.

**Comment by GrahamCampbell** [comment]
Oh, just miss out the environment variable. That should do it...

**Comment by a-komarev** [comment]
For example what i've got now:
`'username' => 'root', 'password' => null,`
And what I waited:
`'username' => 'root', 'password' => 'null',`

**Comment by GrahamCampbell** [comment]
This isn't an issue. You are using it wrong. Please continue this on the forums. I can make this work fine for me.
