### ISSUE TITLE
Schema Facade accessor returns object instead of string - why?

### ISSUE THREAD

**Issue by alfaguru** [laravel/framework#7661]
The contract for the Schema getFacadeAccessor() method is that it returns a string, yet the Schema implementation returns an instance of \Illuminate\Database\Schema\Builder. This means for one thing it is impossible to mock a Schema as a PHP exception is thrown by the isMock() method.

Is there a good reason for this or is it an oversight? If I want to mock Schema in a phpunit test, is there a better way?

**Comment by GrahamCampbell** [comment]
Not sure what you're talking about contracts for?

**Comment by alfaguru** [comment]
I just mean that the doc comment says it returns a string, and that's what isMock() expects.

**Comment by EdwardNelson** [comment]
I am also trying to mock the Schema facade. Is there any word on this?
