### ISSUE TITLE
[5.0] Unable to use migrate:rollback

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#7667]
Anyone else having issues with `migrate:rollback`?

I can use `migrate` and `migrate:refresh` with no issues - but if I try to just rollback my last migration (if I did a single migration) - I get `Class 'CreateResourceTable' not found`. The class is there, because I did the initial migration with it in the first place...

I thought it was just me - but someone else has posted the same issue on StackOverflow: http://stackoverflow.com/q/28710792/1317935

This is occurring on Homestead, with latest L5 build

**Comment by GrahamCampbell** [comment]
Looks like you've forgotten to autoload your migrations.

**Comment by TheShiftExchange** [comment]
@GrahamCampbell - but all other migration commands work for that class. I can migrate the `CreateResourceTable` using both `migrate` and then rollback it back using using `migrate:refresh`.

So why does `migrate:rollback` rely on something different? It makes no sense?

**Comment by GrahamCampbell** [comment]
Yes, they're different.

**Comment by TheShiftExchange** [comment]
so how to you auto load it? And the L5 docs make no mention of having to specifically auto load it - so I'll do a PR for the docs?

**Comment by GrahamCampbell** [comment]
The default app structure should autoload the migrations.

**Comment by TheShiftExchange** [comment]
Yes - exactly. But it *doesnt*...

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/master/composer.json#L15

**Comment by GrahamCampbell** [comment]
> But it doesnt...

Yes it does. I can't replicate this issue.

**Comment by TheShiftExchange** [comment]
Ok - let me work out a replication... (I have that composer.json setup)

**Comment by crynobone** [comment]
> Anyone else having issues with migrate:rollback?

Nope

> So why does migrate:rollback rely on something different? It makes no sense?

Why the process is different, the underlying code is the same.

`artisan migrate:refresh` is just `artisan migrate:reset && artisan migrate`.

<https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Console/Migrations/ResetCommand.php#L59-L71>

<https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Console/Migrations/RollbackCommand.php#L59-L67>

**Comment by TheShiftExchange** [comment]
@crynobone but migrate:rollback is not that command? It is a different underlying code....
