### ISSUE TITLE
required_with_all validation not populating :values in error message

### ISSUE THREAD

**Issue by Quagh** [laravel/framework#7832]
Seems like someone just forgot to add the `replaceRequiredWithAll` method in `Illuminate\Validation\Validator`. The `:values` was not getting populated`

Problem:
```
The height field is required when :values is present.
```

Desired result:
```
The height field is required when field1 / field2 / field3 is present.
```

Solution:
```php
/**
 * Replace all place-holders for the required_with_all rule.
 *
 * @param  string  $message
 * @param  string  $attribute
 * @param  string  $rule
 * @param  array   $parameters
 * @return string
 */
protected function replaceRequiredWithAll($message, $attribute, $rule, $parameters)
{
    return $this->replaceRequiredWith($message, $attribute, $rule, $parameters);
}
```

Using Laravel 4.2 btw. Creating a PR for this in a few minutes.

**Comment by GrahamCampbell** [comment]
> Using Laravel 4.2 btw.

We don't support L4.2 for minor bugs, sorry.

**Comment by Quagh** [comment]
Aww :disappointed: I'll use my fork then and merge all my personal fixes into its master branch, should work too.
