### ISSUE TITLE
Laravel queue worker sleep affecting new relic apdex score

### ISSUE THREAD

**Issue by nbransby** [laravel/framework#7860]
https://discuss.newrelic.com/t/laravel-queue-worker-sleep-affecting-apdex-score/16423

Will everyone who uses laravel and new relic together be experiencing this? If new relics PHP agent claims to support laravel I would guess that would be the best place to ensure the sleep doesn't get included in the metrics but they don't seem to think so.

Wondering if anything can be done this end.

**Comment by crynobone** [comment]
> Wondering if anything can be done this end.

Do you have any suggestion? Disable apdex when running queue with sleep?

> If new relics PHP agent claims to support laravel

`sleep()` is a PHP function not just Laravel, doesn't NewRelic support PHP?

**Comment by nbransby** [comment]
There no point me implementing it locally if it affects everyone, agreed this seem to be more NewRelic's issue and the fix feels like it belongs in their plugin but they don't seem to see it the same way

**Comment by nbransby** [comment]
Assuming this has been closed as a won't fix - will push back on NewRelic

**Comment by victorNewRelic** [comment]
New Relic added out-of-the-box instrumentation support for Laravel Queues as an experimental feature in version 6.6.0. Check if your agent version is at least 6.6.0 and then add this property to your `newrelic.ini`:
`newrelic.feature_flag=laravel_queue`

For more info, check out the [release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-660169)
