### ISSUE TITLE
(L5) Custom Route Bindings not working on production (but working in homestead)

### ISSUE THREAD

**Issue by Someguy123** [laravel/framework#7865]
I've ran into a very strange issue, I've written custom bindings for resolving users and images, which works great on my homestead setup, i.e. `/users/someguy123`, but on my production system, that same URL doesn't work, instead it appears to fallback to something that acts like `Route::model`, `/users/1` will work, but `/users/someguy123` will not.

**The code**

routes.php

    // use a function which simply does dd($user);
    Route::get('/users/{user}', 'ProfileController@show');
    Route::bind('user', function($value)
    {
	    return \App\User::where('username', $value)->firstOrFail();
    });

RouteServiceProvider.php

    public function boot(Router $router)
	{
		parent::boot($router);
		$router->model('user', 'App\User');
	}

**The systems**

It **works on my Laravel Homestead** vagrant box running on my Macbook. I can access `/users/someguy123` and it will show that user in the database.

    vagrant@homestead:~$ php -v
    PHP 5.6.3-1+deb.sury.org~trusty+1 (cli) (built: Nov 19 2014 19:38:33)
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
        with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

    vagrant@homestead:~$ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

It **does NOT work** on my DigitalOcean Ubuntu box, accessing `/users/someguy123` causes a 404 error, where-as `/users/1` works fine (assuming 1 exists in the DB). I have used `php artisan clear-compiled`, I've manually destroyed the `/storage` folder multiple times, I've ran `composer dump-autoload`, all of my composer packages are up to date.

    root@x:~# php -v
    PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11)
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

    root@x:~# cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

I've inspected the router within tinker and can confirm the bindings are definitely getting registered in the router, but I can't figure much else out other than that

    => <Illuminate\Routing\Router #00000000323694840000000010af4aae> {
       binders: [
           "user"  => function ($value) use ($class, $callback) { ... },
           "images" => function ($value) use ($class, $callback) { ... }
       ],
       verbs: [
           "GET",
           "HEAD",
           "POST",
           "PUT",
           "PATCH",
           "DELETE",
           "OPTIONS"
       ]
     }

Any help on this would be appreciated.

**Comment by Someguy123** [comment]
**UPDATE:** I can confirm this issue affects even a free ubuntu VM from Koding.com

I set up the code on their Apache2 with PHP, and `/users/someguy123` also does not work, but works fine on my local homestead.

    someguy123: ~ $ php -v
    PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
     someguy123: ~ $ cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
    someguy123: ~ $

**Comment by Someguy123** [comment]
**UPDATE**: I discovered that if I remove `$router->model('user', 'App\User');` from RouteServiceProvider, the bindings suddenly function again.

It appears on PHP 5.5.9, that the bindings are ignored if you have model classes in the RouteServiceProvider, however on 5.6 (homestead), the bindings run instead.

Not sure if this is a bug or not, but it's very strange behaviour that has cost me hours of debugging.

**Comment by GrahamCampbell** [comment]
Looks like a php bug.

**Comment by Someguy123** [comment]
@GrahamCampbell and a documentation clarity issue. I was somehow inclined to believe I needed to put it in the RouteServiceProvider even if i used a custom binding (maybe a "if you're using a custom binding then you don't need to put it in the the service provider" would be nice)

**Comment by GrahamCampbell** [comment]
I can't replicate this issue anyway. Have you forgotten to clear you compiled file?

**Comment by Someguy123** [comment]
@GrahamCampbell possibly, I've long since lost that environment as I removed the model from RouteServiceProvider and it just worked everywhere. Seemed to update without me clearing the compiled file so I'm not sure if that could've been why I saw it functioning fine in homestead.

**Comment by franzliedke** [comment]
@Someguy123 Did you get any further with this issue?

**Comment by newtonianb** [comment]
We just encountered the exact same issue! 
The bind works in homestead but doesn't work in production (amazon ec2 ubuntu). 
@GrahamCampbell @Someguy123 

What's the bottom line on how to fix this? 

Route::bind(
    'encodedToRaw',
    function ($value, $route) {
        return EncodeLibrary::decode($value);
    }
);

        Route::get('obj/{encodedToRaw}', [
                'uses' => '\MyApp\Http\Controllers\MyController@show'
            ]
        );

**Comment by amosmos** [comment]
Happened to me too.

@Someguy123, It's not an issue of the duplication of binding. I had it ONLY on the service provider and it worked fine on dev but failed on production.

I removed it from the service provider and added it to routes and it worked on production too.

It's definitely something that needs to be cleared on the documentation, and probably also here: https://laracasts.com/series/laravel-5-fundamentals/episodes/18 :-)

Thanks,
Amos

**Comment by iateadonut** [comment]
This worked for us:

`php artisan clear-compiled`
