### ISSUE TITLE
Rolling back a transaction will still increment the primary key

### ISSUE THREAD

**Issue by Richard-A** [laravel/framework#7866]
When using `DB::beginTransaction()`, then trying to insert something and then rolling back will not insert into the database as expected, but will increase the auto_increment by 1.

**Comment by crynobone** [comment]
Does it work differently when just using straight PDO?

**Comment by MaartenStaa** [comment]
I think this is expected behaviour from the database.

**Comment by ibrasho** [comment]
This is the expected behaviour of MySQL.
http://stackoverflow.com/questions/449346/mysql-auto-increment-does-not-rollback
