### ISSUE TITLE
Raising a custom Exception within a template is forcably wrapped in ErrorException

### ISSUE THREAD

**Issue by dcbarans** [laravel/framework#7879]
When i run a function in my view like `{{ $myObj->doSomething() }} ` and it raises a custom exception I'm listening for on the ExceptionHandler I don't see it because it's forceably wrapped in a ErrorException.

The work around is currently calling `$e->getPrevious()->getPrevious()` to drill down into the base exception.

Is it possible to only wrap the exception if it's a vanilla exception?

https://github.com/laravel/framework/blob/5.0/src/Illuminate/View/Engines/CompilerEngine.php#L75

**Comment by ibrasho** [comment]
First of all, you shouldn't `doSomething()` in a view. View are used to present content. All logic should be moved elsewhere if you care about the architecture of your code.

The reason the exception is wrapped in an ErrorException (I think this should be changed to ViewException or something else) in the `handleViewException()` is to provide you with the path of the view file to ease debugging.

You can always extend the CompilerEngine and bind your implementation:

```php
class MyCompilerEngine extends CompilerEngine
{
    protected function handleViewException($e, $obLevel)
    {
        if ($e instanceof MyException) {
            throw $e;
        }

        parent::handleViewException($e, $obLevel);
    }
}
```

```php
$this->app->make('view.engine.resolver')->register('blade', function() use ($app) {
    return new MyCompilerEngine($app['blade.compiler'], $app['files']);
});
```

**Comment by dcbarans** [comment]
Side note after using Laravel for a couple of months now (old ticket but.. data none the less) Laravel uses objects all the time in their templates. Perfect example is their withErrors() response function which allows for:

    <input type="text" class="form-control" name="alias" value="{{ old('alias') }}">
    @if($errors->has('alias'))
        <p class="help-block">{{ $errors->first('alias') }}</p>
    @endif

It's understood these functions are simple but you cannot guarantee the coders behavior here I believe.  Therefore, handling exceptions in a better manner wouldn't hurt.
