### ISSUE TITLE
Possible bug/limitation in dynamic where

### ISSUE THREAD

**Issue by phanan** [laravel/framework#7886]
Because of [the way it's currently written](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Query/Builder.php#L975), `dynamicWhere` method from Query Builder may have a hard time dealing with weird column names--those with `or_` or `and_`. For instance, if I have a column name like `or_id`, a "dynamic where" call might be `$model->whereOrId()` and fails in a similar fashion like that of #694:

``` php
$finder = substr($method, 5);
// => where
$segments = preg_split('/(And|Or)(?=[A-Z])/', $finder, -1, PREG_SPLIT_DELIM_CAPTURE);
/**
array(3) {
  [0]=>
  string(0) ""
  [1]=>
  string(2) "Or"
  [2]=>
  string(2) "Id"
}
**/

foreach ($segments as $segment) 
{
  // we can imagine what happens
}
```

Now does this happen in reality? Rarely, but I'd say yes, taking into account of different (spoken) languages.
Is it a bug? I'm not sure, but certainly it's a limitation.
How do we fix/improve this? I don't know, hence issue, not PR.

**Comment by JoostK** [comment]
Don't use dynamic where calls for such "ambiguous" columns. Just use multiple `where` calls where the column is specified as first argument, then this is avoided.
