### ISSUE TITLE
Requiring Borisrepl\Boris in the  composer make laravel uninstallable [4.2]

### ISSUE THREAD

**Issue by paulrblakey** [laravel/framework#7895]
Requiring Borisrepl\Boris in the  composer make laravel uninstallable[4.2]
At some point in the last week or so Borisrepl\boris has moved to requiring certain php extensions. Can we move borisrepl\boris to the suggests section of the composer file for this package. 

related : https://github.com/borisrepl/boris/issues/97

**Comment by paulrblakey** [comment]
Errrm its still there this refers to Laravel\Framework version 4.2

**Comment by GrahamCampbell** [comment]
> Errrm its still there this refers to Laravel\Framework version 4.2

4.2 is not supported. 5.0 fixes this issue, which is out of our control anyway.

**Comment by GrahamCampbell** [comment]
I've been aware of this issue for months.

**Comment by paulrblakey** [comment]
So thats a no then. We weren't really ready to have to update all our laravel apps to version 5.0 yet.

**Comment by GrahamCampbell** [comment]
> We weren't really ready to have to update all our laravel apps to version 5.0 yet.

Not our fault the boris team broke it. Go complain to them.
