### ISSUE TITLE
Laravel 4.2.x - Sessions & Cache in Redis, Conflicting Connection

### ISSUE THREAD

**Issue by SmurfWorks** [laravel/framework#7896]
Hey there! I'm currently working on a project in the 4.2.x release and have come across something that I'm not sure this is a bug or a new feature, but seems a little odd to me. Maybe someone can clarify what's going on?

1. I've set the Cache driver to Redis and defined a connection named 'default' within my databases configuration, under 'redis'. The cache is able to push to Redis with my given connection/port/database number. (database number is set to 0)

2. I now move my Sessions driver to Redis and defined another connection named 'sessions' within my databases configuration, under 'redis'. The sessions are pushed to Redis with my given connection/port/database number. (database number is set to 1)

3. Upon inspecting Redis via the command line, I see all of my cache values are put into the database number defined in my 'sessions' connection, which led me to look through the code and came across this in the SessionManager class:

```php
	/**
	 * Create an instance of the Redis session driver.
	 *
	 * @return \Illuminate\Session\Store
	 */
	protected function createRedisDriver()
	{
		$handler = $this->createCacheHandler('redis');

		$handler->getCache()->getStore()->setConnection($this->app['config']['session.connection']);

		return $this->buildSession($handler);
	}
```

From what I gather, the Redis Driver for sessions is building a Redis Cache instance, then setting the store's connection to the configured session connection. This is where my Cache is no longer pushing to it's configured connection. The difference is the database number, yet both Cache and Session data can be found in Redis Database number 1.

I understand why it'd create a new cache handler, it makes sense to use the Redis Cache to move data to and from Redis. However, why does each cache handler create and share the same store and connection as other cache handlers? This means my cache and sessions cannot be stored on different hosts, ports or databases. 

As a side note you can only select the "default" Redis connection for the Redis Cache driver. The connection parameter in the cache configuration is passed for the Database driver, but not the Redis Driver so it'd be good to be able to pass this through too.

After talking to a colleague about this, it's worth noting that there's a similar use case for having queues on their own Redis connection details (such as a different host or database number(

Does anyone have any thoughts/explanations about this? Thanks a bunch.

**Comment by GrahamCampbell** [comment]
4.2 is not supported.

**Comment by GrahamCampbell** [comment]
Also, this is not a forum. Please post on there if you'd like a discussion.

**Comment by ifduyue** [comment]
I've encounter this bug, too

**Comment by GrahamCampbell** [comment]
It's not a bug I'm afraid. It's the expected behaviour.

**Comment by ifduyue** [comment]
@GrahamCampbell  `Session::`methods are configured to not to use the `default` connection, but it pollutes the cache connection and `Cache::`methods are using the same connection to `Session::`methods.

 In my opinion this is a bug, because you cannot separate cache and sessions into different redis dbs/servers.

**Comment by GrahamCampbell** [comment]
You can separate then.

**Comment by GrahamCampbell** [comment]
Maybe not in 4.2, but you can in later versions.

**Comment by ifduyue** [comment]
OK, got that, thanks. If a later version support it, I will upgrade.

**Comment by ifduyue** [comment]
5.1.1 released 20 minutes ago, this problem still exists. 

https://github.com/laravel/framework/blob/3a44db7e70146dc1282b39887b5faa67c8583015/src/Illuminate/Session/SessionManager.php#L126-L133
