### ISSUE TITLE
Password Hidden Error

### ISSUE THREAD

**Issue by EliuFlorez** [laravel/framework#7900]
The password and remember_token still reflected in the data of Auth::user()->password

![password-hidden](https://cloud.githubusercontent.com/assets/784787/6519683/04cb77ca-c38a-11e4-9dcc-b6dbdf789169.png)

**Comment by overtrue** [comment]
![image](https://cloud.githubusercontent.com/assets/1472352/6520618/1fb0ea46-c404-11e4-83a7-41a098588473.png)

try :

```php
dd($user->toArray()); // or ->toJson();
```

>  Sometimes you may wish to limit the attributes that are included in your model's array or JSON form, such as passwords. To do so, add a hidden property definition to your model

"your model's array or JSON"

http://laravel.com/docs/5.0/eloquent

**Comment by EliuFlorez** [comment]
ok. protected $hidden = ['password'] and still the error still allows reading the password when it should be hidden from
