### ISSUE TITLE
L4 Blade comments can potentially cause a CONNECTION_RESET error

### ISSUE THREAD

**Issue by CausaMortis** [laravel/framework#7905]
Some of my view files were not loading correctly and causing the connection to be reset, resulting in an internal server error (500). After debugging it turned out that this was due to blade comments present in the file. Removing them solved the problem.

Turned out that someone else recently ran into the same problem and posted this SO question:
http://stackoverflow.com/questions/28782420/laravel-blade-comment-causes-connection-reset

Not quite sure if it is relevant but this happened since I moved development to a local windows environment using WAMP (2). Had no problems on my ubuntu box.

**Comment by GrahamCampbell** [comment]
This isn't really any use without a test case.

**Comment by CausaMortis** [comment]
As you can see in the linked SO question it is something that can happen in the simplest of view files. I will be sure to check if I can recreate the problem in a different manner (by trying different web servers for example).

Is there anything in particular that I haven't thought of that could help you in identifying the issue?

**Comment by HarmvZ** [comment]
I am also having trouble with this issue. When searching online it turns out that a lot of people using Xampp/Wampp on windows run into this problem. Just a few results:

http://demoscripts.info/28174162/blade-comments-in-laravel-are-crashing-apache.html
http://askproblem.com/question/blade-comments-in-laravel-are-crashing-apache/
http://www.tagwith.com/question_112799_laravel-blade-comments-blade-rendering-causing-page-to-crash
http://stackoverflow.com/questions/28174162/blade-comments-in-laravel-are-crashing-apache
http://stackoverflow.com/questions/27830200/laravel-blade-comments-blade-rendering-causing-page-to-crash
http://laravel.io/forum/07-28-2014-laravel-on-windows-7-wamp-env-doesnt-support-the-comment-tag-comment

The easy fix is to remove all blade comments from your files or making sure there is no blade/php code in your blade comments. But this solution is not ideal. 
Can this issue be reopened?

**Comment by jurosh** [comment]
happens for me too, no php code inside only scripts and links from header...
this is really sad for blade, because comments are then not usable for most use cases

**Comment by brazenvoid** [comment]
A test case is easy to build for this. Just make a view, put php code in blade syntax, then comment it out with blade, load the page and voila! 

For example, put this in any view and it will crash, at least all of my views do. 
(all variables and arguments must be valid)
```php
{{--@foreach($array as $element)--}}
    {{-- @include('someView')--}}
{{--@endforeach--}}
```

I just wasted two hours, figuring the problem when a page started showing 'connection was reset' error.

**Comment by geocine** [comment]
This still happens on Laravel 5.0 on windows

**Comment by CausaMortis** [comment]
@GrahamCampbell, It would appear that it is worth reopening this issue and taking a closer look. I'm no expert but I believe this has something to do with the way comments are being parsed by the templating engine.

Please elaborate as to what additional information you consider required. I will do my best to delve into it and save you some time.

**Comment by borys-p** [comment]
I just got bitten by this one and decided to dive into BladeCompiler.

Problem is probably somewhere deeply in PHP's regex parser. So I just simplified the expression and used modifiers to match multiline comments:

`$pattern = sprintf('/%s--(.*)--%s/Ums', $this->contentTags[0], $this->contentTags[1]);`

There should be probably more testing, but looks like it works.

**Comment by johnSheard** [comment]
@brazenvoid thank you so much. I've been trying to fix this for 3 days, and this is the thing that finally worked!

**Comment by isometriq** [comment]
I'm trying to comment a big chunk of code with blade comments and after 8200+ chars, I get an internal error 500.

The problem did not appear in local env (with php artisan serve).
I'm on laravel 5.1

Apache error log shows: End of script output before headers: index.php

I'm not sure if blade comments are designed to handle multiline content... but I guess something is still wrong

**Comment by isometriq** [comment]
note that i can always use this
<?php /* ... */ ?>

but the problem is that it surprised me during deployment.
blade comments limitations should be indicated in the documentation!

**Comment by rhofma** [comment]
issue is still there

**Comment by borys-p** [comment]
@rhofma [the fix is also there](https://github.com/laravel/framework/issues/9588), but it seems nobody cares

**Comment by GrahamCampbell** [comment]
This is a php bug rather than a laravel bug. Upgrade php.

**Comment by rhofma** [comment]
my app runs on php7

**Comment by borys-p** [comment]
@GrahamCampbell: this bug is somehow related to the Windows' implementation of regular expressions. If you change the regex from recursion to multiline flags, then it works.

**Comment by GrahamCampbell** [comment]
A bug when built with old libraries on Windows only.

**Comment by rhofma** [comment]
my app runs on ubuntu server 14.04.. but got the same issue

**Comment by GrahamCampbell** [comment]
Ok then, old libraries, fullstop.

**Comment by whatda** [comment]
So Ubuntu 14.04 isn't supported? Since it's a LTS this would seem a bit strange to me... A hint to supported OSes would be appreciated, thanks.

**Comment by borys-p** [comment]
Why are you so reluctant to changing this one regex?

**Comment by GrahamCampbell** [comment]
I'm not. Nobody has actually sent a PR to fix it though

**Comment by CausaMortis** [comment]
@borys-p care to submit that PR including a test?

**Comment by g-van-vreckem** [comment]
The same Issue is also present on homestead with php 7 and laravel 5.1
So it's not a Windows only issue or an old regex library bug

**Comment by GuillaumeUnice** [comment]
I have the same issue since I migrate my old project on my new laptot with Laravel 5.0 and php 5.5.12 on Win 10.

**Comment by mukundindianic** [comment]
Try to add following code into your root htaccess and issue will be fixed for now:
php_flag xcache.cacher Off 
php_flag xcache.size 0 
php_flag xcache.stat Off

**Comment by tmuks** [comment]
I ran into same situation. I am using Ubuntu 14.04 and site suddenly started giving "Connection was reset" and "No data received" error. I was facing issue in whole site. 

After digging the issue, I came to following solution:
Add following code into your root htaccess and issue will be fixed for now
php_flag xcache.cacher Off 
php_flag xcache.size 0 
php_flag xcache.stat Off

**Comment by whatda** [comment]
Why is this still closed? There are obviously several people encountering this bug.

**Comment by GuillaumeUnice** [comment]
Used Laragon instead of wamp and enjoy :D

**Comment by wapnen** [comment]
@tmuks tried that but i get the following error 
"invalid command php_flag  perhaps misspelled or defined by a module not included in the server configuration" im running on heroku

**Comment by HieuNM47** [comment]
hehe
