### ISSUE TITLE
Session data in service providers

### ISSUE THREAD

**Issue by swiggles** [laravel/framework#7906]
Hi,

In relation to this https://laracasts.com/discuss/channels/general-discussion/laravel-5-session-data-is-not-accessible-in-the-app-boot-process?page=1.

I am having the same problem, would firing a 'sessionstarted' event in the start session middleware be an option?

Thanks
Sam

**Comment by GrahamCampbell** [comment]
We cannot process support requests here. It looks like you're using it wrong.

**Comment by Arrilot** [comment]
@swiggles i think you should make a PR for your proposal. 
Issues for such small things are not really useful

**Comment by franzliedke** [comment]
@GrahamCampbell I'd say the issue is that things like this were possible in 4.x, and aren't anymore. There have been a lot of issues about this stuff, I think we shouldn't dismiss them this easily. I'll try to find out what we can do to improve the situation...

**Comment by swiggles** [comment]
@GrahamCampbell - The issue is that i need to access data in the session container from within the service provider.

I have a package that adds items to a navigation container so all i have to do is call the service provider for that package.

I can't retrieve the currently logged in user, because the session has not been started. This is because the session is started later than the service provider's boot method, in middleware

The proposal is to fire an event \Event::fire('session.started'); in the session middleware so that we can listen for this event in a packages service provider or anywhere in the app that we need to.

It would be more constructive for you to explain how you came to the conclusion that it looks like i'm using it wrong, rather than just dismissing the issue outright.

Thank you

**Comment by devinfd** [comment]
I concur with @swiggles and @franzliedke. This is a true bug and it would be nice if it wasn't so quickly dismissed.

@swiggles will you issue a PR to have this resolved?

**Comment by n0impossible** [comment]
use redis instead of native session

**Comment by vedmant** [comment]
I have the same problem here, I forced to use Middleware instead of ServiceProvider, though to use ServiceProvider is more logical for dynamically configuring menu items for example.

**Comment by mouhsinelonly** [comment]
+100000

**Comment by SirCumz** [comment]
Yeah i agree! Sessions are only available within controllers and middleware. But the service provider boot method claims i could BOOTSTRAP application stuff, but without the session i can't bootstrap my application as it should, the middleware is great solution but this is only for HTTP, but what about bootstrapping when running in console? the middleware is not executed then. I need to bootstrap modules and plugins in both HTTP and console, and it requires a session. I hope this is going to be fixed so that sessions are available in Boot methods or at least in the App::booted callback.
