### ISSUE TITLE
Route handled with get* instead of post*

### ISSUE THREAD

**Issue by brazorf** [laravel/framework#7917]
My route
```php
Route::controller('my/route/{args?}', 'My\Controller');
```

My controller
```php
class Controller extends Controller {
    function getIndex($args = null) {
      return "get";
    }

    function postIndex($args = null) {
      return "post";
    }
}
```

GET "my/route" returns "get"
GET "my/route/1" returns "get"
POST "my/route/1" returns "post"
POST "my/route" returns "get"

As you see there's a weird behaviour when there are no arguments to the post route. Is this by design?

**Comment by GrahamCampbell** [comment]
Looks like a bug to me.

**Comment by JosephSilber** [comment]
Why do you have that optional `args` their? The `controller` method takes care of the optional parameter binding.

Just use this:

    Route::controller('my/route', 'My\Controller');

**Comment by brazorf** [comment]
I think that the Controller should handle these arguments without messing with them, and route any request to its proper http verb. The optional argument declaration in the route is expected to be there by design from my understanding.

Furthermore, when trying your suggestion

```php
Route::controller('my/route', 'My\Controller');
```

i get the `Controller method not found` exception on route `GET my/route/1`, because it's trying to access the get1 method.

**Comment by rapliandras** [comment]
`class Controller extends Controller`
did you purposely use this controller name for the issue?

**Comment by GrahamCampbell** [comment]
> did you purposely use this controller name for the issue?

That looks like an oversight in the simplified example, that's all.

**Comment by brazorf** [comment]
I've ran some blackbox test, here's the result.
Each test contains the route declaration, the Controller methods and 4 results.

```php
// No args
Route::controller('test', 'My\Controller');
function getIndex() { return "index"; }
function getLocation() { return "location"; }
Results:
get 'test'			ok
get 'test/1'		ok (not found)
get 'test/location'		ok
get 'test/location/1'	ok
----------------------
```

```php
// Mandatory arg
Route::controller('test/{args}', 'My\Controller');
function getIndex($arg) { return "index"; }
function getLocation($arg) { return "location"; }
Results:
get 'test'				ok (not found)
get 'test/1'			ok
get 'test/location'		ok (not found)
get 'test/location/1'	ERR (NotFoundHttpException)
----------------------
```

```php
// Mandatory arg - no args on controller methods
Route::controller('test/{args}', 'My\Controller');
function getIndex() { return "index"; }
function getLocation() { return "location"; }
Results:
get 'test'				ok  (not found)
get 'test/1'			?   (returns "index" even though $arg is not declared)
get 'test/location'		ERR (returns "index")
get 'test/location/1'	ERR (NotFoundHttpException)
----------------------
```

```php
// Optional args
Route::controller('test/{args?}', 'My\Controller');
function getIndex($arg = null) { return "index"; }
function getLocation($arg = null) { return "location"; }
Results:
get 'test'				ok
get 'test/1'			ok
get 'test/location'		ERR (returns "index")
get 'test/location/1'	ERR (NotFoundHttpException)
----------------------
```

```php
// Optional args - no args on controller methods
Route::controller('test/{args?}', 'My\Controller');
function getIndex() { return "index"; }
function getLocation() { return "location"; }
Results:
get 'test'				ok
get 'test/1'			ok
get 'test/location'		ERR (returns "index")
get 'test/location/1'	ERR (NotFoundHttpException)
```

I can see that mostly the 'location' errors are triggered because 'location' is interpreted as an argument. However, i'm pretty sure that this behaviour was different in 4.x branch.

**Comment by brazorf** [comment]
Look at this trivial example:

```php
Route::get('a/{args}', function($args){return "get";});
Route::post('a', function(){return "post";});
```

- `GET a/1` returns "get"
- `POST a` returns "post"
- `GET a` returns MethodNotAllowedHttpException

The latter suggest that the resolver didn't found a matching route for `GET a`, so it fell back to the only matching pattern - that is configured to only allow the POST method.

I fear i'm losing something important, because this seems to be way too much of a routing issue.

**Comment by thomasruiz** [comment]
There is no bug in your last code snippet.
The route `/a` is only responding to POST requests, hence the MethodNotAllowed.

If you set the parameter to optional for the GET route, you won't have any error.

**Comment by brazorf** [comment]
You are right, but i didn't say that's a bug. 
My point is that for some reason, while in a GET request context, the resolver parsed a POST route. It's just an heads up since the original issue i submitted was exactly related to this behaviour, but may turn out that is not related.

**Comment by GrahamCampbell** [comment]
Closing due to human timeout (2 weeks or more with no response).
