### ISSUE TITLE
Distinguishing Laravel release versions in packages

### ISSUE THREAD

**Issue by lookitsatravis** [laravel/framework#7924]
I've got a package that I'd like to update to be compatible with 5.0. There are small differences with the way packages are registered, but beyond registration, my package will remain unchanged. I suppose I could just make a breaking change and bump the minor version, but my guess is that people will hang on L4 for a while longer, and it'd be cumbersome to maintain two versions where the only difference is package registration.

So, I thought about how to solve it. Parsing composer files is nasty, but Illuminate\Foundation\Application has a VERSION constant. Yay! Except, Illuminate\Foundation is no longer a separate composer package that I can list as a dependency. Boo! (I think it was back in L3 days, but no longer). My next thought is that the application version would get into Illuminate\Support\ServiceProvider since every package would use this class. This requires an extra release step, but then any package could know if it's running in 5.0 or not.

Anyway, I wanted to see if we could get a conversation going around ways that packages can find out which version of Laravel they are running in. It seems like a small, but potentially very useful way to maintain packages without having to explicitly support two releases.

**Comment by brunogaspar** [comment]
Just bump your major version, example, version 1 is for Laravel 4 and version 2 is for Laravel 5, simple.

**Comment by lookitsatravis** [comment]
One of the reasons I mentioned above for bringing this up is to not have to maintain two releases when the only thing that's different is the package registration or perhaps one or two other small changes (like location of the migrations directory). If I knew the Laravel version in my package, then I can make the small forks in logic required.

**Comment by brunogaspar** [comment]
While it's simple, the recommended way is to have 2 separate versions, one for each major Laravel version.

If you don't want multiple versions, then you'll need to check the Laravel version on your Service Provider and apply the changes accordingly.

---

To get the version of Laravel on your Service Provider, do something like:

```php
$app = $this->app;

$version = $app::VERSION;
```

or 

```php
$version = \Illuminate\Foundation\Application::VERSION;
```

**Comment by lookitsatravis** [comment]
As I mentioned above, doing so requires that my package requires laravel/framework as a dependency since `\Illuminate\Foundation\Application` is not available otherwise. It seems like overkill when normally a package only requires illuminate/support. It's not that I can't do it in the ways you've mentioned, it's that I'm trying to convey that these two choices -- either maintaining multiple, simultaneous releases or including the entire framework as a dependency of a package -- don't seem like they should be the only choices. Including the version in illuminate/support somewhere would be pretty simple and would give the benefit to the community of package makers of not necessarily having to maintain multiple versions of packages.

The reason this seems like an issue to me is because package registration changed with L5, but not necessarily other things about packages. Many package internals are the same, it's just the registration that has to be updated. This could be an easy solution.

If the answer is "yo, if you want the Laravel version, depend on laravel/framework, otherwise get ready to maintain multiple releases" then so be it. But I thought it was at least worth some discussion of alternatives.

**Comment by barryvdh** [comment]
You have to make your own decision. It depends on the package. If it's just the `package` method, perhaps you can live with that. But most packages also use config (which have changed), depend on interfaces (which are now different contracts), have blade views (new escaping behavior), publish resources (different commands/setup) etc.

I would say, start supporting 5.0 for new features. Keep the old version for bugs/security-fixes. Taylor also suggested to bump the major version (https://twitter.com/taylorotwell/status/512050601115414528)

But this isn't the place for a discussion, better use the forums/IRC
