### ISSUE TITLE
Mail::send() to accept string.

### ISSUE THREAD

**Issue by huglester** [laravel/framework#7925]
Hello everyone,

I think it would be good, if Mail::send() to accept strings (not only the view file).
Of course it would need to support parsing of variables, like blade templates does.

Because for now, keeping emails in the database, requires you to store them in file, before sending.
So on Mail::send(), we grab the template from DB, save it to file, and pass this temporary view file to the mailer.

Thank you!

**Comment by barryvdh** [comment]
You can use the `raw` method to send plain text.

http://laravel.com/docs/5.0/mail

> If you just need to e-mail a simple string instead of an entire view, use the raw method:

    Mail::raw('Text to e-mail', function($message)
    {
        $message->from('us@example.com', 'Laravel');

        $message->to('foo@example.com')->cc('bar@example.com');
    });

**Comment by GrahamCampbell** [comment]
> You can use the raw method to send plain text.

You can also pass an array of views to send both html an plain text.

**Comment by shahidkarimi** [comment]
THis is not working please help
```
 foreach($customers as $customer) {
           $body = "test body";

           Mail::raw($customer, function ($message) {
               $message->to($customer['email']) // $customer is undefined? why
                   ->subject('')
                   ->from($from_email)
                   ->setBody($body);
           });
}
```

**Comment by rs-sliske** [comment]
@shahidkarimi 

you need to pass variables into the anonymous method by adding "use"
eg

`foreach($customers as $customer) {
           $body = "test body";

           Mail::raw($customer, function ($message) use ($customer) {
               $message->to($customer['email']) 
                   ->subject('')
                   ->from($from_email)
                   ->setBody($body);
           });
}`
