### ISSUE TITLE
Illuminate\Foundation\Http\FormRequest not returning Custom Messages

### ISSUE THREAD

**Issue by granitibrahimi** [laravel/framework#7926]
When I override method public function messages() from FormRequest, it does not take in consideration array of messages returned.

Problem might be at formatError method, it takes only errors returned by Validator.

    protected function formatErrors(Validator $validator)
    {
        return $validator->errors()->getMessages();
    }

Actually I`m using 

    protected function formatErrors(Validator $validator)
    {
        return array_merge_recursive($validator->errors()->getMessages(), $validator->getCustomMessages());
    }

Sorry if I missed something.

**Comment by JeroenVanOort** [comment]
Could you please post the overriding `messages()` function? Without it, it is very hard to debug this.

**Comment by granitibrahimi** [comment]
public function messages()
    {
        $messages = [
             'acreage'  => 'Acreage field must be greater then 0.'
        ];

        return $messages;
    }
