### ISSUE TITLE
Artisan dump autoload is not working with the call method

### ISSUE THREAD

**Issue by tommthierry** [laravel/framework#7928]
I tried to run this command (Artisan::call('dump-autoload');) in one of my route but this is not working.

Behavior:
I create a new Model/Class using php code and tried to get access to it without having to run "php artisan dump-autoload" in command line in my server so I tried to use Artisan::call method but for this specific call it looks like it's not working.

For other one like Artisan::call('migrate'); it's working fine.

Any idea? 

Thanks

PS: i use laravel 4.2

**Comment by GrahamCampbell** [comment]
4.2 is not supported, sorry.
