### ISSUE TITLE
[L5] Schedule 'dailyAt' is not 24h-clock

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#7935]
The following Command in the Scheduler runs at 01:00AM and 01:00PM. 

```$schedule->command('foo:bar')->dailyAt('01:00'); ```

Docs say, it should be a 24H input:
![schermafdruk 2015-03-10 13 04 50](https://cloud.githubusercontent.com/assets/4254854/6574520/24340aec-c726-11e4-9855-65bdb1ef3d3d.png)

**Comment by jbrooksuk** [comment]
I believe that it's [this](https://github.com/laravel/framework/blob/55ad95a24261644a374d3e972519a15de8381dc0/src/Illuminate/Console/Scheduling/Event.php#L297-303) which is causing the issue.

**Comment by jbrooksuk** [comment]
Actually, it's the `spliceIntoPosition` method which looks to be parsing the timestamp incorrectly?

**Comment by taylorotwell** [comment]
When I use getExpression() on that kind of command I get `0 15 * * * *` which looks right to me?

**Comment by Jaspur** [comment]
Oh, then I should give it the time like: ```dailyAt('1:00');```, without a leading ```0```? I'll try.

**Comment by Jaspur** [comment]
It's 13:00 now, 1PM CET. Cronjob did still run.

**Comment by KennedyTedesco** [comment]
I believe that we don't have bug here.

@Jaspur to run at 13:00 you need to set up `dailyAt('13:00')`

13:00 -> `0 13 * * * *`
01:00 -> `0 1 * * * *`

**Comment by taiyaei** [comment]
@KennedyTedesco The task is supposed to run at 1am (01:00), not 1pm (13:00). `dailyAt('01:00')` is, according to OP, running at both 1am and 1pm, should only be 1am (from what I can tell).

I did a `getExpression()` on `dailyAt('01:00')` and `dailyAt('1:00')` and got `0 1 * * * *` which is right. What 5.x version is this on, @Jaspur?

**Comment by Jaspur** [comment]
@taiyaei; v5.0.17

**Comment by holmesjtg** [comment]
I tried a dailyAt('00:01') last night and it didn't work. Also tried dailyAt('11:21') just before that time this morning and it didn't work either. My cron job is set to run scheduler every minute. When I set the schedule for everyFiveMinutes(), that does work. Is there a bug with dailyAt?

**Comment by Jaspur** [comment]
@holmesjtg different issue. create new one. this is just for the 24h clock.

**Comment by holmesjtg** [comment]
Okay, although I thought it might be related to that spliceIntoPosition function as well.

**Comment by holmesjtg** [comment]
Found out that my particular problem was because I didn't realize the dailyAt needed to be UTC time. so I set it around 11pm Boston time to run at 12:01. This converts to 20:01 (UTC-4) so of course it had already passed. The page discussing Scheduler (https://laravel-news.com/2014/11/laravel-5-scheduler/) didn't mention the UTC aspect.

**Comment by taylorotwell** [comment]
Could it be a time zone issue?

**Comment by holmesjtg** [comment]
Yeah, thanks! I meant 00:01 in my post above (just after midnight).
