### ISSUE TITLE
[L5] Elixir tasks cannot be run asynchronously

### ISSUE THREAD

**Issue by bhatt40** [laravel/framework#7940]
## Intro

I have a found a few forum posts referencing this, but there doesn't appear to be a central location for tracking this issue.  According to the [gulp documentation](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support), gulp tasks are run with maximum concurrency.  To run tasks in a particular order, you must specify this using the methods outlined in their documentation.
I've been attempting to run some of my Elixir tasks asynchronously by wrapping them in gulp.task definitions and using the documented methods. While I've found that these methods work when I'm using other gulp tasks (src, dest, concat, etc.), they don't work when I'm using Elixir tasks.

## Example

I created a simple example to demonstrate the issue.  In this case, I'm concatenating two JavaScript files into an intermediate file, then concatenating this file with two more JavaScript files to create my final `app.js` file.  The second concatenation task is dependent on the completion of the first concatenation task.

### Using Gulp Tasks

Here's the gulpfile using `src`, `dest`, and `concat` tasks:

    var gulp = require('gulp'),
        concat = require('gulp-concat');
    
    gulp.task('default', ['second']);
    
    gulp.task('second', ['first'], function() {
        gulp.src(['resources/assets/js/intermediate.js', 'resources/assets/js/file3.js', 'resources/assets/js/file4.js'])
          .pipe(concat('app.js'))
          .pipe(gulp.dest('public/js'));
    });
    
    gulp.task('first', function() {
        return gulp.src(['resources/assets/js/file1.js', 'resources/assets/js/file2.js'])
          .pipe(concat('intermediate.js'))
          .pipe(gulp.dest('resources/assets/js'));
    });

Calling `gulp` from the command line results in the following output:

    [10:59:55] Using gulpfile ~/Sites/laravel_5/gulpfile.js
    [10:59:55] Starting 'first'...
    [10:59:55] Finished 'first' after 45 ms
    [10:59:55] Starting 'second'...
    [10:59:55] Finished 'second' after 5.18 ms
    [10:59:55] Starting 'default'...
    [10:59:55] Finished 'default' after 12 μs

The resulting `app.js` includes the code from all four files:

    var file1;
    var file2;
    var file3;
    var file4;

## Using Elixir Tasks

Here's the gulpfile using Elixir tasks:

    var elixir = require('laravel-elixir');
    var gulp = require('gulp');
    
    gulp.task('default', ['second'], function() {});
    
    gulp.task('first', function() {
        return elixir(function (mix) {
            return mix.scripts([
                "file1.js",
                "file2.js"
            ], "resources/assets/js/intermediate.js", "resources/assets/js");
    
        });
    });
    
    gulp.task('second', ['first'], function() {
        elixir(function(mix) {
            mix.scripts([
                "file3.js",
                "file4.js",
                "intermediate.js"
            ], "public/js/app.js", "resources/assets/js");
        })
    });

Calling `gulp` from the command line results in the following output:

    [11:11:03] Using gulpfile ~/Sites/laravel_5/gulpfile.js
    [11:11:03] Starting 'first'...
    [11:11:03] Finished 'first' after 303 ms
    [11:11:03] Starting 'second'...
    [11:11:03] Finished 'second' after 1.09 ms
    [11:11:03] Starting 'default'...
    [11:11:03] Starting 'scripts'...
    [11:11:03] Finished 'default' after 72 ms
    [11:11:03] Finished 'scripts' after 103 ms

 Here's the resulting `app.js` file:

    var file3;
    var file4;

It's missing the code that was concatenated into the intermediate file.  I've also tried the other methods from the documentation (accepting a callback and returning a promise), but neither of these worked.  From digging into the Elixir source code, I think this may have to do with Elixir's usage of the run-sequence package, but I'm not sure.

**Comment by chaseconey** [comment]
:+1:

**Comment by jdgriffith** [comment]
:+1:

**Comment by IsraelOrtuno** [comment]
:+1: 
I think this should be posted in the elixir repo https://github.com/laravel/elixir/issues

**Comment by bhatt40** [comment]
@IsraelOrtuno At the time of posting this, that repo didn't have an issues section. I'll try moving this to that repo or closing this and opening a new one there.  Thanks.

**Comment by bhatt40** [comment]
This issue was moved to laravel/elixir#73
