### ISSUE TITLE
compiled.php moved from "/storage/framework" to "/vendor"?

### ISSUE THREAD

**Issue by df-jablan** [laravel/framework#7944]
What's up with the compilation file? It's raising hell with my IDE, that's for sure! ;)  

Seriously though, why? Is `/storage/framework` being phased out?

**Comment by taiyaei** [comment]
The relevant commit: https://github.com/laravel/framework/commit/cfa7fcb60fd60b3870606c910559e67186a7a8a8

I'm not entirely sure though.

**Comment by drekinov** [comment]
Well, i am not sure this change is OK or at least in 5.0 branch as it could be breaking change for most applications.

If your application is deployed  then deployment procedure should change permissions for /vendor/services.json & compiled.php files only for that two files, as other /vendor/* should not be writable by web server or .. deployment user should regenerate them with correct env so they could be only readable by web server.
Of course Illuminate/Foundation/Application@registerConfiguredProviders could be overridden for now :) (ClearCompiledCommand too)

**Comment by GrahamCampbell** [comment]
> Seriously though, why? Is /storage/framework being phased out?

It's not. Just the compiled file is being moved.

**Comment by df-jablan** [comment]
Ok, totally cool. Seems to be gone now, and replaced by `services.json`? I like that.

**Comment by GrahamCampbell** [comment]
> and replaced by services.json

What? We haven't replaced anything. We've just moved files about. services.json as always existed,
