### ISSUE TITLE
Model::getDateFormat() incorrect for Date columns in MySQL

### ISSUE THREAD

**Issue by benfreke** [laravel/framework#7948]
For every column type, getDateFormat always returns the Schema's timestamp format (`'Y-m-d h:m:s'`). For a Date column within that schema, it should return just 'Y-m-d'.

In my use case, I'm converting data from an old LMS into proper objects, and the start and end dates of a Semester don't need a time, so I've created those columns as date's, not datetime's. And without using custom mutators, getDirty() believes attributes have changed even though the saved value will be the same.

It's an easy fix to use a mutator on the Model to handle this, but ideally this should be handled by the eloquent model automatically.

**Comment by GrahamCampbell** [comment]
Could you send a pull with tests please?
