### ISSUE TITLE
Clearer documentation for Blade templating

### ISSUE THREAD

**Issue by d4nyll** [laravel/framework#7950]
A clearer documentation on how to use Blade would be nice, with brief explanations of things like `@forelse`, or `@show`, and a little bit more details on `@yield`. I would be happy to knock something up and submit a PR. This issue is clearly [echo'd by many] (http://stackoverflow.com/q/17792180/3966682), and I don't think the documentation has expanded much since then.

**Comment by ralf57** [comment]
Please send a PR to https://github.com/laravel/docs
