### ISSUE TITLE
echo() or print() in custom artisan command disables terminal echo 

### ISSUE THREAD

**Issue by eagle-r** [laravel/framework#7952]
If you implement a custom Artisan command and use echo() or print() to send info to the console, terminal echo is disabled (on Mac running Yosemite and iTerm at least).

Example code,

```
<?php namespace App\Console\Commands;

use Illuminate\Console\Command;

class ExampleCommand extends Command {

  protected $name = 'example:command';
  protected $description = '';

  public function __construct() {
    parent::__construct();
  }

  public function fire() {
    echo "Hello world";
  }

  protected function getArguments() {
    return [];
  }

  protected function getOptions() {
    return [];
  }
}
```

**Comment by pavankumarkatakam** [comment]
You can use $this->info("What ever the message") in CustomCommand@fire function.

**Comment by GrahamCampbell** [comment]
You should ever use echo or print in there.

**Comment by eagle-r** [comment]
I would agree and I don't. The problem occurs when I'm using a third party package not designed for Laravel and it uses echo or print. I just used the above code as the simplest example.
