### ISSUE TITLE
Elixir gulp-notify runs a lot of times

### ISSUE THREAD

**Issue by cve** [laravel/framework#7956]
Hi,

I'm working with your excellent package called Elixir. The problem is when I run a gulp watch (or without watch) in the console the gulp-notify shows me about 25 same notifications, and after each file change again it shows about 25 system popups...

I'm working on Debian Wheezy 7.7 (64bit)

**Comment by rkgrep** [comment]
+1 It's quite annoying

**Comment by pavankumarkatakam** [comment]
Which editor are you using?

**Comment by cve** [comment]
It was resolved in this pull request and merged by iakio https://github.com/laravel/elixir/pull/56
