### ISSUE TITLE
Elixir: Unable to specify paths for mixing scripts.

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#7964]
I'm trying to combine my scripts after they're generated with dependencies loaded in via NPM.  This means that I have to reference `node_modules` at the root of my project:

	mix.scripts(
		[
			'node_modules/jquery/dist/jquery.js',
			'public/js/login.js'
		], 
		'public/js/login.dist.js', 
		'/'
	);

When I try and run the above however, elixir doesn't seem to perform any operation at all?

**Comment by JeffreyWay** [comment]
Elixir-specific questions may be added here now:

https://github.com/laravel/elixir/issues

But, to answer your question, you just need a period at the beginning of your output path:

```
mix.scripts(
    [
        'node_modules/jquery/dist/jquery.js',
        'public/js/login.js'
    ], 
    'public/js/login.dist.js', 
    './'
);
```

**Comment by atrauzzi** [comment]
Worked perfectly, thanks @JeffreyWay! :)
