### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by darkweb2015** [laravel/framework#7968]
Due to constraints on the server I am working on (still stuck with PHP5.3), I am trying to modernise some aspects of an existing application.  As such, I have integrated certain components from Laravel 4.1  to use.

Everything is working extremely well.  I do have a small issue with the pagination however.  While the links are displayed at first (i.e when you dont go to another page), the moment you get to another page, the name numbers in the url end up staying the same.

```
<ul class="pagination">
	<li><a href="index.php?page=3&amp;test=1">«</a></li>
        <li><a href="index.php?page=3&amp;test=1">1</a></li>
        <li><a href="index.php?page=3&amp;test=1">2</a></li>
        <li class="active"><span>3</span></li>
        <li><a href="index.php?page=3&amp;test=1">4</a></li>
        <li><a href="index.php?page=3&amp;test=1">5</a></li>
        <li><a href="index.php?page=3&amp;test=1">6</a></li>
        <li><a href="index.php?page=3&amp;test=1">7</a></li>
        <li><a href="index.php?page=3&amp;test=1">8</a></li>
        <li><a href="index.php?page=3&amp;test=1">»</a></li>	
</ul>
```

Does anyone have an idea of why this is the case?  I dont have the option of upgrade the PHP version on the server.  Any solutions for this would be of great help.

Thanks

**Comment by GrahamCampbell** [comment]
We don't support php 5.3, sorry.
