### ISSUE TITLE
dd() in ajax response

### ISSUE THREAD

**Issue by pilot911** [laravel/framework#7972]
Why i get for dd($var) in ajax this terrible html ?
What should i change and where to get normal aka var_dump() debug output in ajax response ?
```
<script> Sfdump = window.Sfdump || (function (doc) { var refStyle = doc.createElement('style'), rxEsc = /([.*+?^${}()|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/; doc.documentElement.firstChild.appendChild(refStyle); function toggle(a) { var s = a.nextSibling || {}; if ('sf-dump-compact' == s.className) { a.lastChild.innerHTML = '&#9660;'; s.className = 'sf-dump-expanded'; } else if ('sf-dump-expanded'
```

**Comment by taiyaei** [comment]
You'd have to be much more specific.  What Laravel version are you using, what is the expected output, what is the input?

As it stands, it can be anything.  Doing a dd() as your AJAX response is not a great idea anyway, you should be properly returning a response.

If this isn't a bug that you're reporting, you should consult a forum such as laravel.io for future cases of where you need help.

**Comment by pilot911** [comment]
I want to know about the questionable decisions from the developers of the framework

**Comment by crynobone** [comment]
I question your motive for not using `var_dump` in the first place.

The new dd() is powered by symfony's VarDump componwnt which show more result (for lengthy object/array) and properly collapse it on page load.

**Comment by pilot911** [comment]
i dont want to see thousands rows of array via symfony's VarDump in HTML after ajax request. I just want to get json with the same array. As it was in 4.2.

**Comment by pilot911** [comment]
i develop https://github.com/telenok/telenok 2 years and see some disadvantages.

**Comment by taiyaei** [comment]
So it sounds like you're using Laravel 5.0.  Things change in major releases.  dd() is purposely supposed to tell you as much info about what you're giving it as possible, that's kind of the point of even performing a dd().  It's used solely for quick debugging.

> I just want to get json with the same array

Use something like json_encode()?  This isn't an issue in any case, if you need help like this you should use a forum or something of the like.

**Comment by pilot911** [comment]
well, okey, thanks

**Comment by cweiske** [comment]
When using `dd()` for quick debugging when developing a JSON API, I currently see only the HTML tags in swagger UI and have a hard time deciphering the actual contents.

So I think that to serve the purpose of "quick debugging", `dd` should honor the application/json content type.

**Comment by devcircus** [comment]
dd() is provided by Symfony. Laravel is unable to change its functionality.

**Comment by cweiske** [comment]
No. `dd()` is defined in `laravel/framework/src/Illuminate/Support/helpers.php` and calls `Illuminate\Support\Debug\Dumper`, which itself decides which of the symfony dumpers (CliDumper, HtmlDumper) it uses.
So it could also decide to use `json_encode`.

**Comment by devcircus** [comment]
In older, unsupported versions, yes. It is no longer in the framework.

**Comment by ma7ko** [comment]
I also tried to debug like this. In order to debug correctly try to access the json data you send via the ajax request. Example:

```
$.ajax({
url: '/some/url',
type: 'POST',
data: {
par1: 'val1'
},
success: function(resp, status_code, _) {
console.log(resp);
}
});
```

and in the php controller just return $request['par1'] it should have the value val1.

**Comment by carocat87342** [comment]
I still got the above same error.

Could anyone give me the clue to solve it?

Thanks in advance.
