### ISSUE TITLE
Multiple Logs

### ISSUE THREAD

**Issue by willrowe** [laravel/framework#7984]
On several sites I've had the need to log to a separate file from the app log at `storage/logs/laravel.log`. For example, I might be using a payment gateway and want to log all payment attempts and their result, or recently I needed to keep a log of a task that was run once an hour. While I could have these log directly into the app log, it makes it difficult to find if I'm logging other information as well, especially if I have a verbose mode enabled while debugging. There is no way to do this easily right now since it only allows configuration for one log location, so I was wondering if setting up logging similarly to how cache stores are currently configured would be something that would fit in Laravel. Something like the following in the config:
```php
'log' => [
    'default' => 'app',
    'loggers' => [
        'app' => [
            'path' => $app->storagePath().'/logs/laravel.log',
            'type' => 'daily'
        ],
        'payment' => [
            'path' => $app->storagePath().'/logs/payment.log',
            'type' => 'single'
        ]
    ]
]
```
The facade would work the same, but a method like `logger` could be called to specify which log to use, if none specified it would use the default:
```php
// Would use the default log `app`
Log::warning('Something could be going wrong');

// Would use the `payment` log
Log::logger('payment')->warning('Payment could not be processed.');
```
What do you think?

**Comment by franzliedke** [comment]
Can't you inject a logger instance to wherever you need it and just make sure (e.g. via the container) that you're getting another instance there? That way we don't have to add any complexity to the facade...

**Comment by willrowe** [comment]
Yes, I have used other methods to get additional logs, but they are not accessible directly through the `Log` facade. It would not add complexity to the facade, only a single method, and it would function exactly as it does currently out of the box.

**Comment by franzliedke** [comment]
What I'm saying is that the facade is not meant to help you with such a use case. And I'm not sure it should be...

**Comment by willrowe** [comment]
Why not? This is how the `Cache` facade works, so it's not without precedent. This would make it more robust and allow for more logs if needed, otherwise you don't even need to worry about it. Most people might only use a single cache store, but there's still the ability to have more and easily access them if needed. I don't see this as much different than that.

**Comment by franzliedke** [comment]
Feature creep, I guess. I suppose the use case is probably more common for cache than for logs. We'll see what others have to say.

**Comment by willrowe** [comment]
Ok, I understand that. That's why I made this, to see if it would be worth putting in. If it's not something that anyone would ever use then there wouldn't really be any point.
Forgot to mention, I've already worked out what would need to be done so I can create a pull request if it's wanted.

**Comment by franzliedke** [comment]
Cool. =)

**Comment by willrowe** [comment]
@taylorotwell any thoughts on this?
