### ISSUE TITLE
Could not set application name properly, instead of DatingApp - DatingDatingApp

### ISSUE THREAD

**Issue by micahaza** [laravel/framework#7985]
pezo@pezo-ThinkPad-T530:~/tmp/blog$ laravel --version
Laravel Installer version 1.2.0
pezo@pezo-ThinkPad-T530:~/tmp$ laravel new blog
Crafting application...
Generating optimized class loader
Compiling common classes
Compiling views
Application key [MMYFKfrN2d3xEUcwldW7RnJLXKtUBYn1] set successfully.
Application ready! Build something amazing.
pezo@pezo-ThinkPad-T530:~/tmp$ cd blog/
pezo@pezo-ThinkPad-T530:~/tmp/blog$ php artisan app:name DatingApp
Application namespace set!

The applicaton name is now DatingDatingApp instead of DatingApp :
  
pezo@pezo-ThinkPad-T530:~/tmp/blog$ grep Dating app/Http/Controllers/HomeController.php 
<?php namespace DatingDatingApp\Http\Controllers;
pezo@pezo-ThinkPad-T530:~/tmp/blog$

**Comment by GrahamCampbell** [comment]
This is fixed in the current release. It will take a few hours for the installer to be updated to ship the latest release.

**Comment by micahaza** [comment]
Thank you very much.

2015-03-12 23:49 GMT+01:00 Graham Campbell <notifications@github.com>:

> This is fixed in the current release. It will take a few hours for the
> installer to be updated to ship the latest release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/7985#issuecomment-78671951>.
>



-- 
Pető Zoltán
