### ISSUE TITLE
[L5] Incorrect item range generated by firstItem() in \Illuminate\Pagination\AbstractPaginator 

### ISSUE THREAD

**Issue by CarterZhou** [laravel/framework#7986]
If I do not misunderstand the purpose of firstItem() and lastItem(), I can use them in the view to show item range of a specific page, for example, **"showing item 21 to 28"**.

The code in the controller could be
```php
$users = App\User::select('id')->paginate(10);
$begin =  $users->firstItem();
$end = $users->lastItem();

return view('users/index')->with('begin',$begin)->with('end',$end);
```
And in the view
```html
<p>showing item {{$begin}} to {{$end}}</p>
```

The information is correct when there is at least one item in the data set. But if there is no data retrieved, the information is wrong: **showing item 1 to 0**.

The reason is in the current firstItem() defined in \Illuminate\Pagination\AbstractPaginator class, it does not check for empty data set.

```php
     /**
	 * Get the number of the first item in the slice.
	 *
	 * @return int
	 */
	public function firstItem()
	{
		return ($this->currentPage - 1) * $this->perPage + 1;
	}
```

To rectify the issue, it could be modified as follows:
```php
/**
	 * Get the number of the first item in the slice.
	 *
	 * @return int
	 */
	public function firstItem()
	{
		return $this->count() == 0 ? $this->count() : ($this->currentPage - 1) * $this->perPage + 1;
	}
```
Given that current lastItem() is defined upon firstItem() and the new version firstItem() may return 0 when data set is empty, lastItem() may return -1 as a result. Thus I propose change the definition of lastItem() from
```php
       /**
	 * Get the number of the last item in the slice.
	 *
	 * @return int
	 */
	public function lastItem()
	{
		return $this->firstItem() + $this->count() - 1;
	}
```
to
```php
/**
	 * Get the number of the last item in the slice.
	 *
	 * @return int
	 */
	public function lastItem()
	{
		return ($this->currentPage - 1) * $this->perPage + $this->count();
	}
```

**Comment by JosephSilber** [comment]
Any reason this isn't a pull request?

**Comment by CarterZhou** [comment]
1) Not that condifident to make a good pull request and the time when I raised the issue.
And 2) was busy with the work at hand yesterday.

Would take some time to make a pull request today.

**Comment by rkgrep** [comment]
I think issue should be closed because related PR was not accepted
