### ISSUE TITLE
Use form request manually

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#7995]
The documented way to do form requests is by dependency injecting in your controller. I would like to call methods on my FormRequest before validating, so need to instantiate manually. The only way I've found of doing this is like below calling `setContainer` -- seems long winded, is there a better way?

**dependency inject**

```php
/**
 * Send message
 * @return Redirect
 */
public function send(ContactUsRequest $request)
{

}
```

**manual ?**

```php
/**
 * Send message
 * @return Redirect
 */
public function send()
{
	$request = new ContactUsRequest;
	// [.... custom functions to call on request here ....]
	$request->setContainer(app());
	$request->validate();
}
```

**Comment by crynobone** [comment]
Why not add a contract to `ContactUsRequest` and resolve it via IoC.

```php
class ContractUsRequest ... implements FooInterface {

}
```

In `AppServiceProvider`

```php
public function boo()
{
    $this->app->resolving(function (FooInterface $request, $app) {
        // [.... custom functions to call on request here ....]
    });
}
```

**Comment by crynobone** [comment]
Or even just `App::make('ContractUsRequest');` could simplify some of this stuff.

**Comment by garygreen** [comment]
Well take for instance with model route binding. What if I need to get some values from the model in order to help validate? So the nicest way I can think of is it just create an instance of the form request manually, and send through the model via a custom function like `setUser()`.

```php
/**
 * Update user
 * @return Redirect
 */
public function update(User $user)
{
    $request = new UpdateUserRequest;
    $request->setUser($user);
    $request->setContainer(app());
    $request->validate();
}
```

**Comment by iWader** [comment]
You should already be able to do this?

Routes.php
```php
Route::post('/example/{model}', 'ExampleController@postStore');
```

Request Class
```php

use Illuminate\Routing\Router;

class TestRequest extends Request {

    public function rules(Router $router)
    {
        $model = $router->input('model'); // Router inputs are the url parameters.

        $unique = sprintf('unique:%s,%s,%s,%s', $model->getTable(), 'email', $model->getKeyName(), $model->getKey());

        return [
            'email' => 'required|email|' . $unique,
        ];
    }

}
```

Controller
```php
class ExampleController extends Controller {

    public function postExample(TestRequest $request)
    {
        // Do stuff as normal. Validation has passed.
    }

}
```

**Comment by garygreen** [comment]
Why closed @GrahamCampbell ? Is it possible to use FormRequest manually *without* dependency injection in the controller?

**Comment by garygreen** [comment]
@GrahamCampbell any news? Not sure why you would close this without an explanation. It's so tricky at the moment to manually instantiate a FormRequest and validate. If there is a solution, please let me know otherwise this issue should be re-opened.

**Comment by phanan** [comment]
@garygreen There solution is right there, though as you said, long-winded. IMHO, `FormRequest` isn't meant to be used that way, making your case kind of particular/personal and not applicable for framework-level support, hence the closure.

**Comment by garygreen** [comment]
@phanan FormRequest should not be this tightly integrated into controllers where you can ONLY use them easily when you dependency inject them into your controller functions. That seems like a crude design and breaks the principle of [separation-of-concerns](http://en.wikipedia.org/wiki/Separation_of_concerns).

**Comment by garygreen** [comment]
Also forgot to mention -- my method above doesn't actually work. If you look at the way the FormRequest is bootstrapped, it sets all the input/request data [in this protected function](https://github.com/laravel/framework/blob/8865d2276be94f0a3497ba3bd26c906ae9e91e1c/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L51).

**Comment by phanan** [comment]
This works:

``` php
		$request = new ContactUsRequest;
		$request->setContainer(app());
		$request->setRedirector(app('Illuminate\Routing\Redirector'));
		$current = app('request');
		$request->initialize(
			$current->query->all(), $current->request->all(), $current->attributes->all(),
			$current->cookies->all(), $current->files->all(), $current->server->all(), $current->getContent()
		);

		$request->validate();
```

so in theory, the current design doesn't break said principle. But I agree, this looks clumsy. Let's hear from @GrahamCampbell.

**Comment by garygreen** [comment]
Actually I just tried resolving the form request through the IOC and it actually seems to work fine. Maybe this should be documented?

```php
$request = app('App\Http\Requests\ProfileSaveRequest'); // FormRequest
$request->validate();
```

**Comment by phanan** [comment]
Well, Laravel Docs is on Github, too... Just saying.

**Comment by jorenvanhee** [comment]
@garygreen Thanks! I just tried it and it works. Second line was not necessary though.

```
public function store(Request $request)
{
	// Modify the request
	$request['attending'] = true;

	// Execute validation manually
	app('App\Http\Requests\InviteeStoreRequest');
}
```

**Comment by tjphippen** [comment]
OMG thank you so much @garygreen !! Seriously like 2 straight days of BS is over thanks for that :)

**Comment by prograhammer** [comment]
A good valid reason for manual invoking the validation/redirect behavior is:

I like to have my form field definition and validation together in one class. Say you have a CRUD create or edit page. When first arriving on that page (READ), I have my controller get the injected form class, call some behavior, and send to view. If I have my validation there in that form class then the validation runs (finds that required fields are blank) and the page redirects (in an infinite loop actually). What I want is to manually call the validation from the routes where the form is submitted. Otherwise, I had been doing something similar to what Graham Campbell suggested.

**Comment by garygreen** [comment]
@prograhammer You could have just put that `isMethod` in your rules and if `get` request return empty set of rules. No need to overwrite `getValidatorInstance`

**Comment by prograhammer** [comment]
Ahh right. Although I also have more validation I do in an after validation hook so I would have to put this check for `get` there as well. And I lose the ability to add rules from another array I have where I've defined server side data for each form field. Now you've got me thinking though.

**Comment by modestguy** [comment]
@garygreen thank you so much!

**Comment by itroteam** [comment]
@garygreen thank you so much! you have healed my headache!

**Comment by booni3** [comment]
@garygreen thanks for your input on this. 

With this I was able to abstract the validation process for both my API requests and form submissions. The final way that a user can submit a form on my site is via a CSV upload (for a bulk submission). Each line of the CSV is effectively a new form submission. To get around this, I first convert the CSV into an array and then push this through the validator as follows:

```
foreach ($csvArray as $row){
    try{
        $request->replace($row);
        $request = app(OrderStoreRequest::class);
    } catch(ValidationException $e) {
        if($e->validator->fails()) {
            // validation has failed on this row
        }
    }
}
```

I realise that this is a bit hacky (replacing the request for each row) but it is doing the job. Maybe someone will have some feedback on a better way to do this, or it may just help someone else out!

**Comment by jartaud** [comment]
@booni3 what about array validation?

**Comment by booni3** [comment]
@jartaud  - Array validation will work just the same as you normally would from the request.

**Comment by realtebo** [comment]
I add my 2 cents

In a situation i'd like to use a different formRequest to validate the data based on some external conditions that must be checked at runtime only

so, based on esit of external check, I need to use the formRequest A or the formRequest B.

I ended to doing some weird and ugly code to achieve this, sorry because I cannot simply manually use formRequests.

**Comment by cacpmw** [comment]
This worked for me:

```PHP
            $yourFormRequest = new YourFormRequest();
            $yourFormRequest->setContainer(app());
            $yourFormRequest->initialize([
                'field1' => $data['field1'],
                'field2' => $data['field2'],
                'field3' => $data['field3']
            ]);
            $rules = [
                'rule1' => 'some rule',
                'rule2' => 'some rule',
                'rule3' => 'some rule',
             ];
            $yourFormRequest->setValidator(Validator::make($yourFormRequest->all(), $rules));
            $validData = yourFormRequest->validated();

```

**Comment by alighorbani1381** [comment]
What's up guys 😉

Your ways are very good but I need to use two important methods in form request called prepareForValidation & passedValidation

And I Can Handle This Option with a add trait into my form request

With This Option I can mutate and validate my data 

just added this trait and call runFormRequest static method

```php
<?php

namespace App\Console\Commands\DataPort\Validation;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

trait RuntimeFormRequest
{
    public static function runFormRequest($value)
    {
        $value = self::getMockedRequestByParameters($value);

        $validator = self::createFrom($value, new self());

        $validator->setContainer(app());

        $validator->prepareForValidation();

        $validator->setValidator(Validator::make($validator->all(), $validator->rules()));

        $instance = $validator->getValidatorInstance();

        if ($instance->fails()) {
            return $instance->errors();
        }

        $validator->passedValidation();

        return $validator->all();
    }


    protected static function getMockedRequestByParameters($paramters)
    {
        $mockRequest = Request::create('', 'POST');

        $mockRequest->merge($paramters);

        return $mockRequest;
    }
}

```

```php
<?php

//Usage

$values = ['name' => 'ali', 'age' => 18];

$validator = YourFormRequestName::runFormRequest($values);
```

This Code is Working Good But if you need to called custom behave when validation is fails or when passed you can rewrite the trait code

I hope useful for U

**Comment by Loafer19** [comment]
try this)
`$request->validate(
     (new ClientStoreUpdateRequest)->rules()
 )`

**Comment by gssj85** [comment]
On Laravel 9 I just changed the visibility to public and it actually works for manual validation and for the controller IOC way.

   ```
// it was protected before
 public function prepareForValidation(): void
    {
        $this->prepareDefaultValues();
    }

    private function prepareDefaultValues(): void
    {
        $this->merge([
            'DESCONTO' => $this->float('DISCOUNT'),
            'PRECO_UNIT' => $this->float('PRICE')
        ]);
    }
```

This is to make sure DISCOUNT and PRICE will be 0.0 if they are passed as null or not passed at all (we have a very specific case...)

**Comment by Nao-30** [comment]
> Actually I just tried resolving the form request through the IOC and it actually seems to work fine. Maybe this should be documented?
> 
> $request = app('App\Http\Requests\ProfileSaveRequest'); // FormRequest

gosh, Thank you so much tho @garygreen !!! 3 hours straight of following methods around to finally come up with a solution that I am not even sure if it breaks something, initiating everything or not, it solved my use case and was suitable enough i guess...

the reason i am telling you this tho is because i did already come up here and in other issues around >< and i stopped scrolling lost hope to find some answers right above ur comment, once i finished and i was satisfied, the moment i finished i scrolled a bit just to see a single line answer that my mind told me thousands of time to try but nope i didn't... ugh sometimes it's just like my logic just stops logicing....

here is this piece of ...code i won't use anymore
```php
<?php

namespace App\Http\Requests\Base;

use Illuminate\Foundation\Http\FormRequest as HttpFormRequest;
use Illuminate\Http\Request;

class FormRequest extends HttpFormRequest
{
    public static function createFrom(Request $from, $to = null)
    {

        $request = parent::createFrom($from);
        $request->setContainer(app());
        $request->getValidatorInstance();

        return $request;
    }
}
```
