### ISSUE TITLE
Problem with custom pageName for Pagination

### ISSUE THREAD

**Issue by limonte** [laravel/framework#8000]
When using custom $pageName for pagination (``$items->setPageName('custom_page_parameter')``) links are not working, more details here: 
http://stackoverflow.com/questions/29035006/laravel-5-pagination-wont-move-through-pages-with-custom-page-name/29035577

Bug is here: https://github.com/illuminate/pagination/blob/master/PaginationServiceProvider.php#L21 ``"page"`` is hardcoded so for now it's impossible to use custom ``$pageName``.

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by dmsilver2** [comment]
I just updated my laravel project to latest version and am having this issue too

**Comment by SgtGrumbles** [comment]
Why was this bug closed?  We see you're open to pull requests, and that's great, but that doesn't magically fix this issue.  Until it's fixed -- externally or internally -- shouldn't this remain open so we can comment and track this still-problematic bug?

**Comment by ounos** [comment]
This issue has been fixed on v5.0, but it seems unchanged on v5.1.
Will it be merged eventually ? Thank you.
