### ISSUE TITLE
php artisan migrate fails because of file name ordering on foreign keys

### ISSUE THREAD

**Issue by tlacaelelrl** [laravel/framework#8002]
The issue is present only when there are foreign key constrains

Let's see the following case

File name 2015_03_13_195049_create_testtable2_table

	class CreateTesttable2Table extends Migration {

		/**
		 * Run the migrations.
		 *
		 * @return void
		 */
		public function up()
		{
			Schema::create('testtable2', function(Blueprint $table)
			{
				$table->increments('id');
				$table->integer('parent')->unsigned();

				$table->foreign('parent')
					->references('id')
					->on('testtable');
			});
		}

		/**
		 * Reverse the migrations.
		 *
		 * @return void
		 */
		public function down()
		{
			Schema::drop('testtable2');
			//
		}

	}

File name 2015_03_13_195050_create_testtable_table

	class CreateTesttableTable extends Migration {

		/**
		 * Run the migrations.
		 *
		 * @return void
		 */
		public function up()
		{
			Schema::create('testtable', function(Blueprint $table)
			{
				$table->increments('id');
			});
		}

		/**
		 * Reverse the migrations.
		 *
		 * @return void
		 */
		public function down()
		{
			Schema::drop('testtable');
			//
		}

	}

Running php artisan migrate will fail with

	[Illuminate\Database\QueryException]
	SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL
	: alter table `testtable2` add constraint testtable_parent_foreign foreign key (`parent`) references `testtable` (`id`))

	[PDOException]
	SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

Why do we have the problem?, because of the file list order by name ascending

    2015_03_13_195049_create_testtable2_table
    2015_03_13_195050_create_testtable_table

How can we overcome the problem

Rename file 

    2015_03_13_195050_create_testtable_table

to

    2015_03_13_195048_create_testtable_table

so the ordering is

    2015_03_13_195048_create_testtable_table
    2015_03_13_195049_create_testtable2_table

This is a hassle because we need to alter the time-stamp or choose filenames alphabetically while keeping track of all names, I think artisan should check for foreign keys before running a migration so the correct execution is done, or maybe a new method can be added so there are three methods?

    up();
    down();
    foreign();

That way the tables will exists when running the migrations and the migration will not fail because of a filename since all schema will be built before adding the foreign key constrains.

I understand this would not happen if I run the table names to be created based on foreign key relations but I don't get why this needs to be done like that.

**Comment by iWader** [comment]
Migrations are sequential, its fundamentally how migrations and the database work.

For example, if I created a table, then later down the line wanted to drop a column from that table. If Laravel was reordering my migrations to work out the foreign keys then it could potentially move my migration to drop the column before I've even created the table, causing bigger issues.

**Comment by tlacaelelrl** [comment]
@iWader I understand what you mean however I think there should be at least a mention of how the migration is executed, I was trying to figure out why the query was failing because no specific error is displayed, checking my table declaration over and over, if at least a list of tables that have already been inserted was displayed on the console it would be easier to track down the issue.

I am new to laravel so I can't know how it works if it is not documented.

**Comment by jovelluna12** [comment]
Commenting in 2024. I personally don't agree as to this issue being closed.

while I kinda understand @iWader 's comment of migrations being sequential, I believe there should at least be an option that lets migrations work around the foreign keys. something like a ` --foreign-key` flag that can be added on top of the refresh or reset command.
