### ISSUE TITLE
Injecting FormRequest into Controller Constructor

### ISSUE THREAD

**Issue by zgosalvez** [laravel/framework#8004]
I decided to inject my `UserRequest` an extension of `App\Http\Requests\Request`, into my controller's constructor, instead of injecting it in all of the methods. The reason for this is to run `authorize()`on all of the requests on that controller.

It does work. However, `php artisan route:list` doesn't work, throwing the following error:

```
PHP Fatal error:  Call to a member function make() on null in /home/vagrant/Code/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php on line 73
```

Apparently, the container wasn't set for some unknown reason, and was being accessed on [line 73](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Http/FormRequest.php#L73).

**Comment by garygreen** [comment]
I really dislike the way form request is constructed, with the container. It makes it so difficult to instantiate and use manually, without dependency injection. This could be related to issue #7995 (which was closed, without any reason!).

**Comment by GrahamCampbell** [comment]
Closed because it was a support request. We cannot process them on github.

**Comment by zgosalvez** [comment]
@GrahamCampbell I may have been misled by the docs, could you point out where exactly we can file issues/bug reports?

**Comment by taiyaei** [comment]
At first I was going to say this wasn't how requests were intended to be used anyway, but [they are](http://laravel.com/docs/5.0/requests#obtaining-a-request-instance).

> To obtain an instance of the current HTTP request via dependency injection, you should type-hint the class on your controller constructor or method

I think this does actually need to be re-opened @GrahamCampbell.

**Comment by nicobrinkkemper** [comment]
I get the same error when I try to do this in a controller method:
```
$request2 = StoreFromSearchRequest::createFromBase($request1);
if ($request2->validate()) {
	$this->callAction('storeFromSearch', [$request2]);
}
```

It may not be a conventional aproach, but I believe it's still a bug.
