### ISSUE TITLE
Input value is absent/present - illogical behavior

### ISSUE THREAD

**Issue by arcadas** [laravel/framework#8006]
I think, that the following code behavior is illogical:
```php
// requested url: {host}/example?id
echo \Request::has('id') ? 'has' : 'has not';
// output: has not
echo \Request::input('id', '999');
// output: empty string
```
The logical output will be the '999' instead of empty string.

What do you think?

**Comment by GrahamCampbell** [comment]
No. That only happens if id is actually not defined. In your example, id is `""`.

**Comment by arcadas** [comment]
Ok. But If the "id" is defined, the `\Request::has('id')` have to return with 'true', now return with 'false'.

So the id defined, but the request has not "id" input?

**Comment by GrahamCampbell** [comment]
Looks like a bug, though, in symfony.

**Comment by GrahamCampbell** [comment]
Hmmmm, that looks like what I'd expect.

**Comment by GrahamCampbell** [comment]
Given that way this works: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Http/Request.php#L245, https://github.com/laravel/framework/blob/5.0/src/Illuminate/Http/Request.php#L287.

**Comment by arcadas** [comment]
If the empty string is a valid input value, that the 'has' method not correct.

In `isEmptyString` method:
Not correct: `trim((string) $this->input($key)) === '';`
Correct: `is_null($this->input($key));`

But, if the `has` method comment is correct: 
`Determine if the request contains a non-empty value for an input item.`

In `isEmptyString` method:
Not correct: `trim((string) $this->input($key)) === '';`
Correct: `empty($this->input($key));`

So, I think the``trim((string) $this->input($key)) === '';` code is wrong, or the has method is misleading.

**Comment by arcadas** [comment]
?
