### ISSUE TITLE
ValidatesRequests with custom messages

### ISSUE THREAD

**Issue by CodeSkills** [laravel/framework#8009]
Hello,

I would like you to think about extending ValidatesRequests with custom $messages, so we would be able set them. I know that this is mainly used for small validation checks but even there, in multi-lang app it's nice to have it there.

Thanks!

**Comment by agentphoenix** [comment]
:+1:

**Comment by phanan** [comment]
Correct me if I'm wrong, but looking at [this](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Validation/ValidatesRequests.php#L18), looks like you can already use custom messages.

**Comment by CodeSkills** [comment]
You are right, I didn't updated the framework last 10 days. Closing.
