### ISSUE TITLE
gitignore maintenance file

### ISSUE THREAD

**Issue by moleculezz** [laravel/framework#8012]
I've noticed that when I set a Laravel 5 site in maintenance mode. The file `storage/framework/down` gets created. But it's not ignored by the `.gitignore` file in that directory. Is this intended behaviour?

Seems to me that it should be ignored.

**Comment by GrahamCampbell** [comment]
Send a pull if you want something changing please. No need to discuss with an issue first.

**Comment by moleculezz** [comment]
Seems like a waste of time to make changes without knowing if it's needed. In this case it's not a big change, but what if it was.

In any case. I will make a PR then.
