### ISSUE TITLE
Service Provider/Container: Abstract Factory

### ISSUE THREAD

**Issue by DaHaiz** [laravel/framework#8016]
hey guys,

i'm coming from zf2. Beside a huge more complexity there was one feature i really liked: Abstract factories. It was possible to define a factory class which can decide if it is able to build up an instance of the requested class. For example you could define an interface and every class that implements that interface the factory can build. I think for laravel it would be too much overhead to have this within a separate class, but we could for instance bind a closure to a service key that is an interface (and maybe add a flag to App::bind, so that we do not have to check every binding. or even new App::bindInterface method). Now if someone tries to fetch an instance of a class that is not registered explicitly the service container checks if it implements the forementioned bound interface and then use that bound closure.
One example - and the one because of that i come up with this - are doctrine repositories. You would only have to define one binding instead of as many repositories i have.

i'm curious about your opinions.

simon

**Comment by GrahamCampbell** [comment]
Sorry to close this, but the forums are for discussions like this.
