### ISSUE TITLE
[5.0.15] Parsing/syntax errors are being hijacked and not displayed - white screen of death

### ISSUE THREAD

**Issue by jlem** [laravel/framework#8024]
If I have a parse/syntax error in say, routes.php, I get a white screen of death - it's not showing me the normal PHP / Xdebug error message.

I have verified it's not my environment by creating a plain PHP script in another directory, with a syntax error, and I can see the error just fine.

However, if I replace everything in routes.php with the same syntax error and run it, I get a white screen. Debug is enabled and is working for runtime errors (missing method, bad request, not found etc), but not for normal parse errors.

Further, if I comment out

```
$app->singleton(
     'Illuminate\Contracts\Debug\ExceptionHandler',
     'App\Exceptions\Handler'
);
```

in `/bootstrap/app.php`, the syntax error is displayed as normal. Something is happening in App\Exceptions\Handler (or there is a poorly chosen default config) that is white screening parse errors in debug mode on me.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. We can't do anything about this for some kinds of php errors.

**Comment by MaartenStaa** [comment]
Well that's not true, it's perfectly possible to add an exception handler for fatal errors, including parse errors.

**Comment by jlem** [comment]
> This is the expected behaviour

I can most assuredly tell you that this is not expected behavior. If it was, I would not have posted this issue.
