### ISSUE TITLE
Tag a new release of illuminate/support

### ISSUE THREAD

**Issue by tpavlek** [laravel/framework#8026]
The subtree split illuminate/support had its last tag at 5.0.4.

It still unfortunately typehints `\Closure` on the map function of `Collection` so I can't use perfectly valid callables with it. 

https://github.com/illuminate/support/blob/v5.0.4/Collection.php#L381

This seems to be fixed in the current version of the framework, so I'd appreciate a new tagged release :)

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/Collection.php#L386

**Comment by GrahamCampbell** [comment]
Will be done soon.
