### ISSUE TITLE
Input::only() inconsistent with array_only()

### ISSUE THREAD

**Issue by JamShady** [laravel/framework#8030]
array_only works as you'd expect, returning ony the keys that actually exist, ala
````
$results = array_only(['foo' => 'bar', 'bip' => 'bap'], ['foo', 'missing']);
// $results = ['foo' => 'bar'];
````

You'd expect Input::only() to be identical, ala
````
Input::only($keys) === array_only(Input::all(), $keys)
````

But it's not.

Using the above example:
````
// input = ['foo' => 'bar', 'bip' => 'bap']
$results = Input::only(['foo', 'missing']);
// $results = ['foo' => 'bar', 'missing' => null]
````

That's a disastrous situation because it means I'll be saving fields back to the database that weren't intended to be saved (because they're were missing from the original input values in the first instance).

I did change the code to:
````
foreach ($keys as $key)
{
	if (array_has($input, $key))
	{
		array_set($results, $key, array_get($input, $key));
	}
}
````
But in looking through the tests, it appears that this was intended behaviour:
````
$request = Request::create('/', 'GET', array('developer' => array('name' => 'Taylor', 'age' => 25)));
$this->assertEquals(array('developer' => array('name' => 'Taylor'), 'test' => null), $request->only('developer.name', 'test'));
````

In my opinion this is nonsensical, inconsistent, and very easily allows buggy code to be created by allowing developers to fall into the trap of assuming that it'll also filter out those values which weren't passed back for whatever reason (in my case, the form field is disabled to prevent it being updated - which doesn't help then when it gets saved back as an empty value)

**Comment by haampie** [comment]
In my opinion this behaviour makes perfect sense. Especially when mapping input to a command for example, you want to make sure all fields specified in Input::only(...) are passed through.

**Comment by JamShady** [comment]
@haampie Even if they weren't supplied as input values??

I'd say something like Input::every($keys) would make sense in that case... every $key would be returned, regardless of whether it was supplied as input or not

**Comment by GrahamCampbell** [comment]
We;re open to pull requests with tests to the master.
