### ISSUE TITLE
psy/psysh v0.4.2 breaks dynamic static method calls in command line interface

### ISSUE THREAD

**Issue by GMiLL5** [laravel/framework#8031]
The latest release adds some checks to ensure a static method exists (See https://github.com/bobthecow/psysh/commit/37f846fa4abef983b50ccc7a8706d45723c792ee) before calling it, which doesn't work with `__callStatic`.

**Comment by barryvdh** [comment]
ping @bobthecow

**Comment by bobthecow** [comment]
Ooh. Good catch. This would have been a great issue to open on the psysh repo ;)

**Comment by bobthecow** [comment]
This is fixed in v0.4.3. Thanks for reporting it!
