### ISSUE TITLE
Redis PCEL extension

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#8032]
How can I use the Redis PCEL extension instead of Predis.

I renamed the `Redis` alias in `app/config` and added a custom `RedisServiceProdiver` and `RedisDatabase`.

Now I'm getting:

    Argument 1 passed to Illuminate\Cache\RedisStore::__construct() must be an instance of
    Illuminate\Redis\Database, instance of App\Services\RedisDatabase given, called in 
    /vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php on line 206 and defined

**Comment by kreitje** [comment]
In your custom RedisDatabase class, make sure you extend Illuminate\Redis\Database

**Comment by tillkruss** [comment]
That simple, eh? Thanks!

**Comment by tillkruss** [comment]
https://gist.github.com/tillkruss/27eda66e77280f1ba727
