### ISSUE TITLE
POST route don't get registed

### ISSUE THREAD

**Issue by cafunfa** [laravel/framework#8035]
When in my routes file I try:
Route::post('something', 'someController@method');
That route isn't registered! (however i can register Route::get.... etc)

But if I do:
Route::any('something', 'someController@method');
I get GET|HEAD|POST|PUT|PATCH|DELETE and the POST work!

And to register a Post only route i need to make this way:
Route::match(['post'],'something', 'someController@method');

Beside "out-of-the-box" Laravel install I add the following repositories to my composer.json:
"barryvdh/laravel-ide-helper": "~2.0",
"laravelcollective/html": "~5.0",
"doctrine/dbal": "~2.3",
"bican/roles": "1.5.*"

I'm new to Laravel and this is probably my fault... but i can't find where!

**Comment by Edgpaez** [comment]
How do you *know* the POST route doesn't register?
Try `php artisan route:clear` if you ran `php artisan route:cache`.
And also check what you get in `php artisan route:list` which shows all the routes. 
Maybe the route is correctly being created but you're calling it wrong (?)

**Comment by phanan** [comment]
Sorry if it sounds rude but doesn't this kind of questions belong to StackOverflow?

**Comment by RomainLanz** [comment]
@phanan Yes, this is not an issue, please ask these types of question on the forum.
