### ISSUE TITLE
hasMany with select() returns no results

### ISSUE THREAD

**Issue by andreikun** [laravel/framework#8044]
For $this->hasMany('Model', 'foreign_key') -> indeed Eloquent is returning correct entities but if you try to apply a select condition it does not return anything.

Let's have an example:
1.I have an album model
2.I have an picture model
3.An album can have multiple pictures and each picture have a name, size, extension and other info

When you try to get an album like http://domain.com/api/album/{album} -> you want also all pictures from that album like :

    "id":"123", 
    "name":"My Album", 
    "pictures":[{
        "id":"1", 
        "name":"Pic1", 
        "size":"1000"
      },{
        "id":"2",
         "name":"Pic2",
         "size":"2000"
      }]

Above is the response when using:
    
     $this->hasMany('App\Pictures', 'album_id');

But in this case i don't want size to be in the response and i don't want to fetch it as array and do extra work to remove my size.

For belongsTo condition we can use ->select('column1', 'columns2') option but when comes using it with hasMany, it simply does not work and as a result, the returning data looks like this

    "id":"123", 
    "name":"My Album", 
    "pictures":[]

Above is the response when using:

    $this->hasMany('App\Pictures', 'album_id')->select('id', 'name');

Instead of :

    "id":"123", 
    "name":"My Album", 
    "pictures":[{
        "id":"1", 
        "name":"Pic1"
     },{
        "id":"2",
         "name":"Pic2"
     }]

**Comment by crissi** [comment]
You need to add the foreign_key to the select statement

**Comment by andreikun** [comment]
What exactly do you mean by adding foreign_key to select statements ? I already added the foreign keys for hasMany and belongsTo relationships.

**Comment by crissi** [comment]
try this:
$this->hasMany('App\Pictures', 'album_id')->select('id', 'name', 'album_id');

**Comment by andreikun** [comment]
Hmm, interesting. I never thought that if you do not include the id, it won't fetch you any data. It seems that the same thing happens when you do not include "id" column in belongsTo relation. 

There i had $this->belongsTo('App\Album')->select('id', 'name'), but i included it because i needed it. When getting Pictures from Albums is supposed that i already know about album_id.

Weird though. They should put some more documentation on the website, or somewhere to be able to read about this.
