### ISSUE TITLE
[Database] [Proposal] Allow database connections to be specified within migrations

### ISSUE THREAD

**Issue by tomcastleman** [laravel/framework#8049]
It would often be useful to be able to create and alter tables within multiple databases from one migration. The current `artisan migrate --database=foo` option doesn't facilitate this - for example if you needed to make certain changes to one database but not another, it would not be appropriate to run `artisan migrate` once for each database without some hacky logic in there to check the database option. It would be good if running `artisan migrate` once handled everything and the migrations themselves could optionally define which database connection to use for each action.

I'm pretty sure @JeffreyWay mentioned this kind of feature to @taylorotwell in a podcast around Christmas.

The migration method `CreateUsersTable::up()`currently looks like this:

```
		Schema::create('users', function(Blueprint $table)
		{
			$table->increments('id');
			...
			$table->timestamps();
		});
```

What I propose is that we would add the ability to specify the connection, much like with the `DB` fascade:

```
		Schema::connection('foo')->create('users', function(Blueprint $table)
		{
			$table->increments('id');
			...
			$table->timestamps();
		});
```

The migration table itself would remain in the default database.

I could start work on this but it would be useful to get some feedback first.

Thanks

**Comment by crynobone** [comment]
You should be able to do it already.

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/Facades/Schema.php#L14

**Comment by tomcastleman** [comment]
Hmm.. thanks @crynobone.. so it would appear! Should have noticed that.
