### ISSUE TITLE
[L5] Subsequent routes not found in unit tests

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#8050]
As long as only one test method is part of a test class, $this->action() works as expected but in the second and subsequent test method it fails, e.g.
~~~
public function testCountAction()
{
    $this->action('GET', '\Aimeos\Shop\Controller\CatalogController@countAction');
    $this->assertResponseOk();
}

public function testListAction()
{
    $this->action('GET', '\Aimeos\Shop\Controller\CatalogController@listAction');
    $this->assertResponseOk();
}
~~~

The $this->action in testListAction() fails with InvalidArgumentException: Action Aimeos\Shop\Controller\CatalogController@listAction not defined. .../laravel5.0/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:540

But this works:
~~~
public function testCountAction()
{
    $this->action('GET', '\Aimeos\Shop\Controller\CatalogController@countAction');
    $this->assertResponseOk();

    $this->action('GET', '\Aimeos\Shop\Controller\CatalogController@listAction');
    $this->assertResponseOk();
}
~~~

This does also apply to $this->call(), $this->route(), etc. More examples are available in https://laracasts.com/discuss/channels/testing/phpunit-says-route-not-defined

**Comment by GrahamCampbell** [comment]
Thank you, but this is a duplicate. Please see the other issues for the solution.

**Comment by aimeos** [comment]
Which ones? Could you share the issue numbers?

**Comment by jrm2k6** [comment]
+1 
Would be nice to share the issue links!
