### ISSUE TITLE
Unable to listen queue when fetch mode is set to ASSOC

### ISSUE THREAD

**Issue by andrewNestorenko** [laravel/framework#8052]
I created command that implements ShouldBeQueued interface
After launching artisan queue:listen I got error

exception 'ErrorException' with message 'Trying to get property of non-object' in /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php:151

If change fetch_assoc to OBJ -> everithing is fine

**Comment by GrahamCampbell** [comment]
Could you provide an isolated case we can try, or submit a failing test please. Also, provide the laravel version.

**Comment by andrewNestorenko** [comment]
Laravel v5.0.5
Steps to reproduce:
1) Setup framework, configure db access
2) Change db settings 'fetch' to PDO::FETCH_ASSOC
3) Create command that implements interface ShouldBeQueued
4) Up migrations
5) run artisan queue:listen
6) handle command 


Result 
Error has happened.  
exception 'ErrorException' with message 'Trying to get property of non-object' in /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php:151

Expect 
Command should be successfully processed
