### ISSUE TITLE
dont escape accent

### ISSUE THREAD

**Issue by erickmonteiro** [laravel/framework#8056]
Hi guys, i have a problem,

// my var
$teste = "<b>Página</b> inicial";

{{ $teste }}
print:
&lt;b&gt;P&aacute;gina&lt;/b&gt; inicial

but i need don't escape accent, like this:
&lt;b&gt;Página&lt;/b&gt; inicial

any suggestions for not escape accent?

thanks in advance

**Comment by taiyaei** [comment]
{!! $teste !!} ?  If you absolutely trust the variable you're outputting.


On a side note, a forum is a better place to put a question like this.

**Comment by erickmonteiro** [comment]
Thanks for the reply, but I need to continue escaping html.

any suggestions?

**Comment by erickmonteiro** [comment]
My first question did not show up correctly:

{{ $teste }}
print:
&lt; b& gt;P&aac ute;gina&lt;/b &g t; inicial

but i need don't escape accent, like this:
& lt;b &gt;Página&lt;/b & gt; inicial

**Comment by RomainLanz** [comment]
This is not an issue about Laravel. Please ask these types of question on the forum.

**Comment by erickmonteiro** [comment]
Thanks, I'll ask the question in the forum.
