### ISSUE TITLE
BusServiceProvider

### ISSUE THREAD

**Issue by apps4u** [laravel/framework#8061]
HI I wanted to submit a issue on the BusServiceProvider its setup default to map command Handlers out of the box to the App/Handlers/Commands namespace so If a package tries to create commands and handlers you need to edit the ServiceProvider so I wanted to submit a more generic way of resolving the handler class in the BusServiceProvider boot method this is just a quick example but if it worked like this out of the box then packages can take advantage of the command bus with out having to dig into the dispatch class ..

        // map namespace for Command Handlers
		$dispatcher->mapUsing(function($command)
		{
            // The default command handler would on map to the app/Handlers/Commands namespace
            // so this dynamically maps the handler namespace based on the command class namespace.
            $name = get_class($command);
            $commandNamespace = substr($name, 0, strrpos($name, '\\'));
            $handlerNamespace = str_replace('Commands', 'Handlers\\Commands', $commandNamespace);

            return Dispatcher::simpleMapping(
                $command, $commandNamespace, $handlerNamespace
            );
		});

**Comment by apps4u** [comment]
Just to be clear I mean the app/Providers/BusServiceProvider not the class in the framework.

**Comment by apps4u** [comment]
<?php namespace App\Providers;

use Illuminate\Bus\Dispatcher;
use Illuminate\Support\ServiceProvider;
use ReflectionClass;

class BusServiceProvider extends ServiceProvider
{

    /**
     * Bootstrap any application services.
     *
     * @param  \Illuminate\Bus\Dispatcher $dispatcher
     * @return void
     */
    public function boot(Dispatcher $dispatcher)
    {
        // map namespace for Command Handlers
        $dispatcher->mapUsing(function ($command) {
            list($commandNamespace, $handlerNamespace) = $this->resolveHandlerNamespace($command);

            return Dispatcher::simpleMapping(
                $command, $commandNamespace, $handlerNamespace
            );
        });
    }

    /**
     *  Dynamically resolve handler class using command namespace.
     * @param $command
     * @return array
     */
    private function resolveHandlerNamespace($command)
    {
        $reflection = new ReflectionClass($command);
        $commandNamespace = $reflection->getNamespaceName();
        $handlerNamespace = str_replace('Commands', 'Handlers\\Commands', $commandNamespace);

        return array($commandNamespace, $handlerNamespace);
    }


    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

}

**Comment by GrahamCampbell** [comment]
Thanks, but this probably belongs on the forums.
