### ISSUE TITLE
[Blade] Curly braces to put PHP code without echoing

### ISSUE THREAD

**Issue by vpratfr** [laravel/framework#8062]
I am successfully and happily using Blade for WordPress development (!) and I have a pretty common use case for that:

Lots of functions in WordPress are echoing directly their output. For example:

```
function the_content() { 
  do_something();
  echo get_something_else();
}
```

Now in my blade templates I currently have the choice of doing that:

- `<?php the_content(); ?>` which does what I need but is ugly
- `{{ the_content(); }}` which in facts compiles to echo something that should not be echoed because it already is (`echo the_content();`)
- `@{{ the_content(); }}` which does not do what I need (simply prints the function name)

So I came up with an extension to blade to simply write the PHP code in between my special brackets:

`#{{ the_content() }}` which gets compiled to `<?php the_content(); ?>`

Here is the extension if a merge on your side is possible and desirable.

```
$compiler->extend(
        /**
         * @param string        $view The view currently being rendered
         * @param BladeCompiler $comp The compiler currently used
         *
         * @return string The compiled view
         */
            function ($view, $comp)
            {
                return preg_replace('/#\{\{\s*(.+?)\s*\}\}/s', '<?php $1; ?>', $view);
            });
```

**Comment by phanan** [comment]
Actually, logic should be kept out of the view.

**Comment by vpratfr** [comment]
Well. As I said I am using Blade for WordPress development and unfortunately WP is poorly structured. That said, I think that could be useful to have this in the language to cover such use cases.

**Comment by taiyaei** [comment]
I think this is an edge case, I don't hear a lot about people using Blade for Wordpress.  In my opinion adding this would encourage poor programming and lead people new to Laravel to do this all the time, which is not good, and may even cause some people to "do this once or twice" as a shortcut and then eventually do it all the time.

While this may be good for using Blade for Wordpress, it's not something that should be in Blade imo.  Could be wrong, we'll see what everyone else thinks.

**Comment by rotichbryant** [comment]
Is this doable? I am very much liking how one can implement this.

**Comment by vpratfr** [comment]
This has been added since then.

```
{{-- single line --}}
@php($var = 123)

{{-- multiple lines --}}
@php
$var1 = 123;
$var2 = 456;
@endphp
```

**Comment by browner12** [comment]
most (all?) Wordpress functions have another function that also only returns the data.

```php
the_content();
```

*echoes* the content

```php
get_the_content();
```

*returns* the content.

Wordpress is stupid, and I would agree, we should not encourage creating functions that echo output directly.

**Comment by vpratfr** [comment]
@browner12 except that in that case, they do not execute the same code (some filters get applied with `the_content()` and not with `echo get_the_content()`) :) 

Anyway, I have since then stopped WP development almost completly, I cannot agree more on your last sentence.

I have had a few cases when I had to use `@php` in my Laravel projects though. (less cases with the multi-line version though).
