### ISSUE TITLE
Form::textarea loses wrapping line breaks

### ISSUE THREAD

**Issue by derekhamilton** [laravel/framework#8063]
Not sure if this is the right place, since Illuminate\html is read-only, but is no longer included by default.  Anyway,

Consider the value

```
$text = "\nthis is some text";
```

This renders to
```
<textarea>
this is some text</textarea>
```

Which is interpreted as having no leading linebreak.  For one line break, it needs to be
```
<textarea>

this is some text
</textarea>
```

Rendering as
```
<textarea>
{{text here}}
</textarea>
```

Would render in a way that more accurately reflects user expectations.

**Comment by GrahamCampbell** [comment]
We don't maintain this component anymore.
