### ISSUE TITLE
【BUG】Illuminate\View

### ISSUE THREAD

**Issue by wutong** [laravel/framework#8070]
When I change my server from linux to windows,
there is an error said can't find the view.
I'm sure everything is correct.
finally I find problem is windows filename encoding.
I use Chineses so filename encoded as 'gbk',
and the Illuminate\View find the file use 'utf-8'.
so I change the file `\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php`,
at line 132
```php
+    $file = iconv('utf-8', 'gbk', $file);
```

wish u guys fix it for Chinese developers :smile: 
by the way, I used laravel 4.1

**Comment by overtrue** [comment]
@wutong 文件名中文的？还是啥？

**Comment by GrahamCampbell** [comment]
4.1 is no longer supported.

**Comment by overtrue** [comment]
@GrahamCampbell :smile:

**Comment by wutong** [comment]
@overtrue 文件名是中文～

**Comment by wutong** [comment]
@GrahamCampbell It's also happend in L5

**Comment by GrahamCampbell** [comment]
You need to configure php to use that encoding then. Otherwise, we don't support those filenames, and you'll need to use English file names.

**Comment by wutong** [comment]
@GrahamCampbell
Could you please tell me how to configure that for php.ini ?

**Comment by GrahamCampbell** [comment]
http://lmgtfy.com/?q=php+encoding+config
