### ISSUE TITLE
[Typo?] problem with the contains() method

### ISSUE THREAD

**Issue by Mathius17** [laravel/framework#8074]
I have a Many to Many relation between User and Role. For some strange reason when I do `User::find(1)->roles->contains(2)` it just won't work, always throws `false` (I've checked in the db and indeed user with id 1 has role with id 2).

I'm using it just as the Laravel docs: [http://laravel.com/docs/5.0/eloquent#collections](http://laravel.com/docs/5.0/eloquent#collections)

I dug the `contains()` method and found it in `Illuminate\Database\Eloquent\Collecion.php`, here it is:
```php
    /**
	 * Determine if a key exists in the collection.
	 *
	 * @param  mixed  $key
	 * @param  mixed  $value
	 * @return bool
	 */
	public function contains($key, $value = null)
	{
		if (func_num_args() == 1 && ! $key instanceof Closure)
		{
			$key = $key instanceof Model ? $key->getKey() : $key;

			return $this->filter(function($m) use ($key)
			{
				return $m->getKey() === $key;

			})->count() > 0;
		}
		elseif (func_num_args() == 2)
		{
			return $this->where($key, $value)->count() > 0;
		}

		return parent::contains($key);
	}
```
Right in the middle of the method, if I change `return $m->getKey() === $key;` for `==` it suddenly works. Is this a typo? Should I report it in the repository or make a pull request?

P.S. It will never enter the `parent::contains()`, or at least in my case.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. :)
