### ISSUE TITLE
After update 5.0.17 not created compiled.php

### ISSUE THREAD

**Issue by 2byte** [laravel/framework#8076]
`php artisan optimize` command execute from super user, but file /vendor/compiled.php not created.
Error log is empty
PHP error log is empty

**Comment by GrahamCampbell** [comment]
I can't replicate. We're not a support forum I'm afraid. Our issue are only for reproducible bugs, not for support, sorry.

**Comment by 2byte** [comment]
Not created compiled.php not a bug?

**Comment by GrahamCampbell** [comment]
No - I can't replicate it. Perhaps you have an issue with file permissions, or opcache?

**Comment by 2byte** [comment]
Set chmod 777 /vendor and execute artisan command from sudo
