### ISSUE TITLE
Odd Relationship Behaviours

### ISSUE THREAD

**Issue by ConnorVG** [laravel/framework#8085]
I truely cannot tell if this is expected or not - the documentation is grey in this area but the code in `Relation` seems to have a `initRelations` method though it doesn't seem to actually get set on the Model (for example `$this->relations` would be empty). Though I feel this should not be how this behaves. I could be misunderstanding something here or just not be going about it correctly in which case please correct.

Take the following simple scenario:
* Parent (id, name)
* Parent hasMany Child
  * Child (id, name, parent_id)

```php
$parent = Parent::with('children')->first();
$children = $parent->children;

foreach ($children as $child)
{
    // this fires another query
    $other = $child->parent;
    
    // this outputs false
    var_dump(spl_object_hash($other) === spl_object_hash($parent));
}
```

Obviously in a real situation you wouldn't call a child's parent like that, with parent already in scope, but thinking about the possibilities of parent no longer being in scope but it's reference needed (ie, through child) gives cause for concern with the amount of queries that can end up being executed. 

Another scenario could be where the child has a mutator or something of that sort that needs to reference it's parent, this would mean the original `$parent` would be out of scope:
* Job (id, name)
* Job hasMany Employees
  * Child (id, name, job_id, salary_id)
* Job hasMany Salaries
  * Salary (id, job_id, salary)

```php
class Job extends \Illuminate\Eloquent\Model {

    public function getSalary($id)
    {
        return $this->salaries->first(function ($salary) use ($id)
        {
            return $salary->id === $id;
        });
    }
    
    public function salaries()
    {
        return $this->hasMany(Salary::class);
    }
    
    public function employees()
    {
        return $this->hasMany(Employee::class);
    }

}

class Employee extends \Illuminate\Eloquent\Model {

    public function getSalary()
    {
        return $this->job->getSalary($this->salary_id);
    }
    
    public function job()
    {
        return $this->belongsTo(Job::class);
    }

}
```

This issue can be elieviated straight after the query simply by doing (*which feels weird to do*):
```php
foreach ($children as $child)
{
    $child->setRelations([
        'parent' => $parent
    ]);
}
```

**Comment by GrahamCampbell** [comment]
Fix proposal was rejected a while back.

**Comment by nickma42** [comment]
@GrahamCampbell was there any further detail on why the fix was rejected? Looks like it was just closed without comment - does that indicate it was just a poor PR or not a problem that needs fixing? I'm running into the same issue and this behavior seems to be the difference between running 4 queries and over 100 for my particular circumstance. Just wondering whether I should try my luck with an improved PR or refactor my code to work around this. Thanks!

**Comment by ConnorVG** [comment]
I would love this to be implemented still, I recently found myself needing it again and had to do a few manual `setRelation` calls to remedy it... It needs to work on `setRelation` also, the only issue I see is lingering relations (when detached) and I'm not sure how that can be observed.
