### ISSUE TITLE
Storing Cookie with a dot in name doesn't work.

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#8093]
This works:

Cookie::queue('temp', 'sdagsadgassdg', 0);

This does not work:
Cookie::queue('temp.region', 'sdagsadgassdg', 0);

**Comment by GrahamCampbell** [comment]
Yeh, you can't use dots.

**Comment by pjebs** [comment]
It should be documented

**Comment by GrahamCampbell** [comment]
We're open to pulls.

**Comment by franzliedke** [comment]
Apparently this is [a very old PHP limitation](http://harrybailey.com/2009/04/dots-arent-allowed-in-php-cookie-names/) that goes back to `register_globals`. Wow.

@pjebs Did you try setting the cookie with `$_COOKIE`? And what exactly didn't work? Did the cookie not show up in the HTTP response (when inspecting them with your browser's dev tools)? Or were you unable to access it with `Cookie::get()` (if so, try accessing the cookie named "temp_region")?

**Comment by pjebs** [comment]
You can store but can't retrieve using Cookie::get()

**Comment by GrahamCampbell** [comment]
> You can store but can't retrieve using Cookie::get()

Yeh, as @franzliedke said, that's a php limitation.
