### ISSUE TITLE
Laravel5 FATAL 'provider not found' error when adding pkg from github repo

### ISSUE THREAD

**Issue by pgnd** [laravel/framework#8097]
I'm attempting to add a github repo to a new L% install's composer.json,

Following/adapting L4 instruction -- haven't found L5-specific -- when adding the repor, on update, I receive a FATAL error that the ...Provider is not found.

Here's the detail.

Adding

```
vi composer.json
	{
		"name": "laravel/laravel",
		"description": "The Laravel Framework.",
		"keywords": ["framework", "laravel"],
		"license": "MIT",
		"type": "project",
+		"repositories": [
+			{
+				"type": "git",
+				"url": "https://github.com/pgnd/LaravelVarnishSessions"
+			}
+		],
		"require": {
			"laravel/framework": "5.0.*",
+			"pgnd/laravel-varnish-sessions": "dev-master"
		},
		"require-dev": {
			"phpunit/phpunit": "~4.0",
			"phpspec/phpspec": "~2.1"
		},
		"autoload": {
			"classmap": [
				"database"
			],
			"psr-4": {
				"App\\": "app/"
			}
		},
		"autoload-dev": {
			"classmap": [
				"tests/TestCase.php"
			]
		},
		"scripts": {
			"post-install-cmd": [
				"php artisan clear-compiled",
				"php artisan optimize"
			],
			"post-update-cmd": [
				"php artisan clear-compiled",
				"php artisan optimize"
			],
			"post-create-project-cmd": [
				"php -r \"copy('.env.example', '.env');\"",
				"php artisan key:generate"
			]
		},
		"config": {
			"preferred-install": "dist"
		},
+		"minimum-stability": "dev",
+		"prefer-stable": true
	}
```

where the package's composer.json @ github

```
vi composer.json
	{
		"name": "pgnd/laravel-varnish-sessions",
		"homepage": "https://www.github.com/pgnd/LaravelVarnishSessions",
		"authors": [ {
			"name": "pgnd",
			"homepage": "https://github.com/pgnd"
		} ],
		"type": "library",
		"description": "Laravel5 + Varnish4 session management",
		"keywords": ["Laravel", "Varnish", "Sessions"],
		"license": "LGPL-2.1",

		"require": {
			"illuminate/support": "5.0.*",
			"php": ">=5.6.0"
		},
		"autoload": {
			"classmap": [
				"src/migrations"
			],
			"psr-4": {
				"pgnd\\LaravelVarnishSessions\\": "src/pgnd/LaravelVarnishSessions/"
			}
		},
		"minimum-stability": "dev"
	}
```

with these changes in place when I attempt a composer update, I get the following FatalError

```
composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)                  
	  - Updating pgnd/laravel-varnish-sessions dev-master (66f028d => 802d395)
	    Checking out 802d395b7dbfdf746c3f49ae97a56dd75724d6e0

	Writing lock file
	Generating autoload files


	                                                                                       
	  [Symfony\Component\Debug\Exception\FatalErrorException]                              
	  Class 'pgnd\LaravelVarnishSessions\LaravelVarnishSessionsServiceProvider' not found  
	                                                                                       


	Script php artisan clear-compiled handling the post-update-cmd event returned with an error


	                      
	  [RuntimeException]  
	  Error Output:       
	                      
```

**Comment by GrahamCampbell** [comment]
You need to add the service provider AFTER running composer.

**Comment by pgnd** [comment]
That's completely unclear to me, but I'll figure it out. Thx for the pointer.

b4 I get started on that, might as well ask the causal question -- does/will L5 provide _natively_ the session/cookie mgmt required for use with Varnish? or will that be left to 3rd party pkgs?

**Comment by phanan** [comment]
> does/will L5 provide natively the session/cookie mgmt required for use with Varnish? or will that be left to 3rd party pkgs?

Why don't you try to find out yourself, before asking?

**Comment by pgnd** [comment]
Gosh, THAT's helpful; thanks for going out of your way.

What makes you think I didn't try already?  Both by looking at it and asking ...

**Comment by phanan** [comment]
Dude, no need of sarcasm. First of all, this place is not supposed to be a support forum. Second, you added another off-topic question on a closed issue. Now to directly answer your last question (what made I think you didn't try) -- it's because you used "does/will," which implies that you're not sure, which in turn implies that you haven't tried. If I'm wrong, my apologies. Again, this issue is closed anyway, there's no point of discussing here.

**Comment by pgnd** [comment]
Dude?  You're wrong on both assumptions ... the sarcasm and the implications.   Not to worry --  Won't be discussed further here, or elsewhere.
