### ISSUE TITLE
FK on different database no longer works (Schema Builder)

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#8101]
This use to work on L4 but no longer works in L5:

$table->integer('country')->unsigned();
$table->foreign('country')->references('id')->on( new Illuminate\Database\Query\Expression('regions' . '.' . 'countries') )->onDelete('cascade');

Now when I check the relations on "Sequel Pro", it thinks the reference should be to regions.id instead of regions.countries.id (where regions is a different database)

**Comment by pjebs** [comment]
Actually I'm no longer sure if this is abug with laravel or sequel pro

**Comment by GrahamCampbell** [comment]
Could you provide us with something we can replicate please.

**Comment by pjebs** [comment]
Safe to keep closed -> bug is with Sequel Pro

**Comment by GrahamCampbell** [comment]
thanks
