### ISSUE TITLE
'/vendor/compiled.php' not being generated

### ISSUE THREAD

**Issue by ctoma** [laravel/framework#8104]
Windows machine, laravel v5.0.16.

bootstrap/autoload.php

    $compiledPath = __DIR__ . '/../vendor/compiled.php';

Illuminate/Foundation/Console/ClearCompiledCommand

    if (file_exists($path = $this->laravel->basePath().'/vendor/compiled.php'))
		    {
		        	@unlink($path);
		    }

Illuminate/Foundation/Console/OptimizeCommand

    $outputPath = $this->laravel['path.base'].'/vendor/compiled.php';

If I generate a dummy compiled.php it is successfully removed by running the "php artisan optimize" command, but a new compiled.php is never generated.

As this is a windows machine I don't think it's a permission issue, but I also tried it on a CentOS machine with 777 for testing and still no luck.

**Comment by crynobone** [comment]
Do you have `app.debug` set to `true`?

**Comment by ctoma** [comment]
Yes, debug is set to true.

**Comment by crynobone** [comment]
> Yes, debug is set to true.

There you go. `compiled.php` is not generated in that mode.
