### ISSUE TITLE
[5.0] Pagination with groupBy causes wrong counting of the pages

### ISSUE THREAD

**Issue by codelight89** [laravel/framework#8105]
`Post::paginate(2);` returns the paginator with 
- total: 4
- lastPage: 2

`Post::groupBy('id')->paginate(2);` returns the paginator with 
- total: 1
- lastPage: 1

`Post::groupBy('id')->get();` returns collection with 4 items

Edit:
As I see in Laravel 4 there were [different functions for grouped and ungrouped paginate] (https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/Builder.php#L235)

**Comment by GrahamCampbell** [comment]
#8310 should fix this for you. :)
