### ISSUE TITLE
Wrong language file used

### ISSUE THREAD

**Issue by faisalmirza** [laravel/framework#8106]
When i use trans('someword') it works fine for locale 'nl', but when my locale is set on 'en' it uses nl/default.php instead of en/default.php. I am using L4.2. What is it that i am doing wrong?

![image](https://cloud.githubusercontent.com/assets/1070807/6779255/82461484-d15a-11e4-9e44-127df5891226.png)

**Comment by phanan** [comment]
I don't think 4.x is still supported.

**Comment by GrahamCampbell** [comment]
You should probably ask on the forums. I'm sure someone can help you there.
