### ISSUE TITLE
Highlight in the docs that environments named "testing" have filters disabled

### ISSUE THREAD

**Issue by MarkVaughn** [laravel/framework#8116]
This ruined my whole day. We had to dig through the source to find out why filters were being ignored on our pre-production site where the QA team does testing.
It is commented in the code here: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Routing/RoutingServiceProvider.php#L32

http://stackoverflow.com/questions/29220618/laravel-auth-filter-not-working-on-one-server/29221547

**Comment by taiyaei** [comment]
If you submit a PR making a note of this to [laravel/docs](https://github.com/laravel/docs) on the `4.2` branch then it should be merged in.

**Comment by MarkVaughn** [comment]
Appreciate it, TIL not to use the pre-generated testing folder for a real environment
