### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::getCachedCompilePath()

### ISSUE THREAD

**Issue by gravitano** [laravel/framework#8124]
Hi There,

I recently updated my project to `laravel/framework` version 5.0.20. But, after the package is installed there is error as follows.

```
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::getCachedCompilePath() in [project]/vendor/laravel/framework/src/Illuminate/Foundation/Console/ClearCompiledCommand.php on line 28
```

After I checked, this error appear when the composer run `php artisan clear-compiled` command.

Thank you.

**Comment by crynobone** [comment]
This would happen normally if you don't run `php artisan clear-compiled` before running composer update. When you run `php artisan optimize` it would use `Application` from compiled instead of vendor since the file still exist. But your artisan command need to use `getCachedCompiledPath()`

**Comment by gravitano** [comment]
Oh, okay. Thanks for the reply. Also, turns out I missed something on version 5.0.16. Thank you for helping me fix this problem. I think now this problem has been solved.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/9678.
