### ISSUE TITLE
Pretty URL doesn't work, because REDIRECT_URL is being ignored

### ISSUE THREAD

**Issue by gently69** [laravel/framework#8129]
Hello,

I have a problem with the pretty URL.

My Development Environment:
- Windows 7
- XAMPP 1.8.3-4 (Apache 2.4.9, PHP 5.5.11)
- Laravel 5.0.14

Productive System:
- Ubuntu 14.04.2 LTS
- Apache 2.4.7
- PHP Version 5.5.9
- Laravel 5.0.14

In both environments I can see the following problem. 

Here is what I did:

- I installed Laravel using composer. 
- I didn't modify: c:/xampp/laravel-rocks/public/.htaccess
- I created c:/xampp/laravel-rocks/.htaccess as follows:
	```
		<IfModule mod_rewrite.c>
			RewriteEngine On
			RewriteRule  ^$ public/    [L]
			RewriteRule  (.*) public/$1 [L]
		</IfModule>
	```
	
- I inserted the following route into app/Htpp/routes.php:
```
Route::get('/hello', function () {
    return 'Hello!';
});
```
	
Symptom:
	http://localhost/laravel-rocks/public/hello works fine.
	http://localhost/laravel-rocks/hello fires a NotFoundHttpException in RouteCollection.php line 145.

mod_rewrite works, because public/index.php is being called. REQUEST_URI and REDIRECT_URL have the following values:
```
	$_SERVER['REQUEST_URI'] = "/laravel-rocks/hello"
	$_SERVER['REDIRECT_URL'] = "/laravel-rocks/public/hello"
```
	
Unfortunately Laravel ignores REDIRECT_URL!

I've written the following lines in public/index.php as a workaround:
```
if (isset($_SERVER['REDIRECT_URL'])) {
    $_SERVER['REQUEST_URI'] = $_SERVER['REDIRECT_URL'];
}
```
Now everything is working as I had hoped. But I think, prepareRequestUri() should be modified to read REDIRECT_URL if it exists.

What you think? Is it right?

**Comment by GrahamCampbell** [comment]
This is a duplicate,

**Comment by r-springmann** [comment]
Where is the duplicate entry? having the same problem.

**Comment by geoffreyhale** [comment]
Where is the duplicate please?
