### ISSUE TITLE
[L4.2] boris  requires ext-readline

### ISSUE THREAD

**Issue by Jaspur** [laravel/framework#8136]
I'm on Forge, so it shouldn't be a problem :p 
```
Updating d02c1a6..25a3f84
Fast-forward
 composer.lock | 111 ++++++++++++++++++++++++++++++----------------------------
 1 file changed, 58 insertions(+), 53 deletions(-)
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for d11wtq/boris v1.0.10 -> satisfiable by d11wtq/boris[v1.0.10].
    - d11wtq/boris v1.0.10 requires ext-readline * -> the requested PHP extension readline is missing from your system.
  Problem 2
    - d11wtq/boris v1.0.10 requires ext-readline * -> the requested PHP extension readline is missing from your system.
    - laravel/framework v4.2.17 requires d11wtq/boris ~1.0 -> satisfiable by d11wtq/boris[v1.0.10].
    - Installation request for laravel/framework v4.2.17 -> satisfiable by laravel/framework[v4.2.17].
```

**Comment by GrahamCampbell** [comment]
Duplicate. Your options are as follows:
* Install the required extensions (best option)
* Run composer with the `--ignore-platform-reqs` flag (very hacky)
* Upgrade to Laravel 5 (we no longer user boris for the tinker command)

**Comment by barryvdh** [comment]
Or require boris v1.0.8 manually

**Comment by barryvdh** [comment]
I know L4.2 isn't supported anymore, but imho it would be an easy fix to change the composer.json for L4.2 to require `"d11wtq/boris": "1.0.8",` as that was the release at the time, and Boris apparently doesn't use SemVer.

**Comment by Jaspur** [comment]
@barryvdh perfect :-) 
@GrahamCampbell Lots of people still using 4.2 for projects, and have no need/time/money for upgrading to L5.

**Comment by GrahamCampbell** [comment]
> and Boris apparently doesn't use SemVer.

Though, actually, boris has always needed this extension, they just forgot to put it in their composer.json, so from the perspective of the code, it wasn't a breaking change.

> Lots of people still using 4.2 for projects, and have no need/time/money for upgrading to L5. 

Right, but 4.2 is not maintained by us anymore. We'll only put security fixes into 4.x.

> Or require boris v1.0.8 manually

Thanks @barryvdh, that's also a good solution, if not the best solution. :)

**Comment by nguyentienlong** [comment]
I had the same issue with php7 ( build from php7 source). Need to add `--with-readline` to enable php readline extension.
this is my configure command to generate `Makefile`
```
./configure --with-pdo-pgsql --with-zlib-dir --with-freetype-dir --enable-mbstring --with-libxml-dir=/usr --enable-soap --enable-calendar --with-curl --with-mcrypt --with-zlib --with-gd --with-pgsql --disable-rpath --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-sysvsem --enable-sysvshm --enable-pcntl --enable-mbregex --with-readline --enable-exif --enable-bcmath --with-mhash --enable-zip --with-pcre-regex --with-mysqli --with-pdo-mysql --with-mysqli --with-jpeg-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-openssl --with-fpm-user=www-data --with-fpm-group=www-data --with-libdir=/lib/x86_64-linux-gnu --enable-ftp --with-kerberos --with-gettext --with-xmlrpc --with-xsl --enable-opcache --enable-fpm
```
Hope this will have someone have same issue like me ;)

**Comment by GrahamCampbell** [comment]
ONLY Laravel 5.1+ supports PHP 7.
