### ISSUE TITLE
Can't access file in $request from dispatchFrom

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#8137]
If you have a Request object which includes files, and you call dispatchFrom using that Request object, the files are stripped out.

I think the problem lies in Illuminate/Bus/Dispatcher.php in function getParameterValueForCommand. It looks for the value in the $request array, but files aren't available from the $request array.

**Comment by taylorotwell** [comment]
I would pass the file via the "extra" params.

**Comment by mattmcdonald-uk** [comment]
But doesn't that defeat the purpose of sending a Request to dispatchFrom? I send the Request so that if I add new inputs (including file inputs) to my form, I don't have re-visit the controller and remember to pass those new inputs along.

So anytime I add a file input I have to remember to add the new file to the extras array?

**Comment by taylorotwell** [comment]
I'm simply considering that better than the somewhat hacky solution of
seeing if the array access object has a files property. Would be better IMO
to modify array access request logic to look at files.

**Comment by GrahamCampbell** [comment]
@taylorotwell You're up early, lol.

**Comment by mattmcdonald-uk** [comment]
@taylorotwell Yes - it did seem a bit hacky! Had another go... any better?
