### ISSUE TITLE
BladeCompiler createMatcher error if using various blade expressions in the same line

### ISSUE THREAD

**Issue by aescarcha** [laravel/framework#8138]
Hi,

I'm extending blade in order to push some static config which will never be changed to the compiled blade templates, I'm doing it this way

    Blade::extend(function($view, $compiler)
    {
	$pattern = $compiler->createMatcher('hardcodeConfig');
	$matches = [];
	preg_match_all($pattern, $view, $matches);
	foreach($matches[2] as $index => $key){
		$key = str_replace([ "('", "')" ], '', $key);
		$configValue = \Config::get( $key );
		$view = str_ireplace($matches[0][$index], $configValue, $view);
	}
	return $view;
    });

It works fine, but it crashes if I use several @hardcodeConfig in the same line, like this:

Expandiendo el conocimiento de @hardcodeConfig('package::strings.siteTopic') de @hardcodeConfig('package::strings.site') al español.

This is due to the createMatcher pattern being greedy, it will match ('package::strings.siteTopic') de @hardcodeConfig('package::strings.site')` in the same element.

Is this a bug? Is there a built-in functionality to do this? I've fixed it by placing an U for ungreedy in the pattern.

Thanks.

**Comment by GrahamCampbell** [comment]
Unfortunately we cannot process support requests here due to the volume of issues we'd have if we did. Feel free to ask on the forums though. I'm sure someone can help you there. :)

**Comment by franzliedke** [comment]
@aescarcha You should probably not use `createMatcher()` in that case (allowing multiple tags on one line). Those methods aren't really used (and thus maintained) anymore, so you'll have to come up with your own regex.

I'll try to improve this soon.
