### ISSUE TITLE
[5.0] BUG  sending mail with sendmail - endless loop and unsent mail

### ISSUE THREAD

**Issue by YammYcoding** [laravel/framework#8147]
using: windows - wamp - sendmail - laravel 5
problem happens when place 'sendmail' in config/mail.php

On a laravel 5 clean install, when I go to auth password reset /password/email form, and try sending the reset email, it get's stuck forever loading, the email is not sent. And when I restart the apache, the following error happens in sendmail debug:

15/03/21 19:55:08 ** --- MESSAGE BEGIN --- 15/03/21 19:55:08 ** --- MESSAGE END --- 15/03/21 19:55:08 ** Message is missing sender's address

Although, on the same machine, on a laravel 4.2, using 'sendmail' in mail.config is working fine.

All I can think it's that in lara 5 they forgot to pass the sendmail path from config into swiftmailer transport instance, or they forgot to place a 'From: ' in the email header. Or it's something else.

**Comment by GrahamCampbell** [comment]
Can't replicate.

**Comment by decadence** [comment]
Maybe same here with Laravel 5.4 and Windows 10. It just hangs with `sendmail` driver and I can't get any log messages.
PHP `mail()` works.
