### ISSUE TITLE
Fully Support PDO Fetch Modes

### ISSUE THREAD

**Issue by jchamberlain** [laravel/framework#8149]
Following up on #3512 and #8107, I've dug through the v5.0.16 release and found the following places that SELECT from the database outside of Eloquent, and therefore may be affected by PDO's fetch mode. (Eloquent itself is entirely agnostic to the fetch mode.) As you can see, there's nothing major going on, but there is a little bit of inconsistency. We can either fix the two broken spots by typecasting, or come up with a more general solution. If the former, we just have to remember that types can never be assumed for Laravel's internal queries.

#### Broken:
* `Illuminate\Cache\DatabaseStore::get()`
        Uses result as object: `return $this->encrypter->decrypt($cache->value);` does NOT cast to object.

* `Illuminate\Queue\Console\RetryCommand::fire()`
        Calls `Illuminate\Queue\Failed\DatabaseFailedJobProvider::find()`, and uses as object; does NOT cast to object.

#### Works, Maybe Slightly Hacky
* `Illuminate\Auth\Passwords\DatabaseTokenRepository::exists()`
        Casts to array

* `Illuminate\Database\Migrations\Migrator::rollback()`
        Calls `DatabaseMigrationRepository::getLast()`; casts to object

* `Illuminate\Queue\DatabaseQueue::getNextAvailableJob()`
        Casts to object

* ` Illuminate\Queue\Console\ListFailedCommand::fire()`
        Calls `Illuminate\Queue\Failed\DatabaseFailedJobProvider::all()`; casts to array.

* `Illuminate\Session\DatabaseSessionHandler::read()`
      Casts to object

#### Works, Not Hacky:
* `Illuminate\Auth\DatabaseUserProvider`
        `retrieveById()`, `retrieveByToken()`, and `retrieveByCredentials()` all perform SELECTs, but all pass results to `getGenericUser()`, which casts as array for passing into `GenericUser` constructor as required by type hint.

* `Illuminate\Database\Builder::lists()`
        Relies on `array_pluck()` which relies on `data_get()`, which handles both arrays and objects.

* `Illuminate\Database\Builder::aggregate()` ( includes `max()`, `count()`, etc.)
        Casts to array so that it can call `array_change_key_case()`.

* `Illuminate\Database\Builder::pluck()`
        Casts to array so that it can grab the first value.

/ping @franzliedke

**Comment by franzliedke** [comment]
Thanks for digging through all of this. =)

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by franzliedke** [comment]
Who are you pinging? This should be pretty clear...

**Comment by GrahamCampbell** [comment]
Pinging for someone to actually do this.

**Comment by jchamberlain** [comment]
Hey guys. I'll go ahead and do this--I should have a long time ago. All my evenings are booked right now, but I'll try to get a PR up sometime next week.

**Comment by franzliedke** [comment]
@jchamberlain Mind if I do it tonight then? :)

**Comment by jchamberlain** [comment]
@franzliedke yeah, if you don't mind doing it, go right ahead. Thanks!

**Comment by franzliedke** [comment]
@jchamberlain In fact, the two places marked as "Broken" in your summary are already fixed.

**Comment by jchamberlain** [comment]
Awesome!
