### ISSUE TITLE
[5.0] suggestion: Form to reset password after token link is clicked - with email

### ISSUE THREAD

**Issue by YammYcoding** [laravel/framework#8153]
If I try any other email, the error just claims as 'invalid token' - this could be more clear, like 'email do not match token'.

Also, the token link comes from the actual email and when I click the link, it goes to an empty form asking for email and password.
This said, that email could come already filled in the reset form, and maybe let the field as read only. That'd be nice to have from the perspective of the user.

[]s

**Comment by GrahamCampbell** [comment]
We're open to pull requests. Also the Form class is not maintained anymore.
