### ISSUE TITLE
Str::slug convert "&" to "and"?

### ISSUE THREAD

**Issue by fungku** [laravel/framework#8155]
I think it would be handy to convert `&` to `and` while making a slug.

for example `Friends & Family` could be `friends-and-family` instead of `friends-family`

**Comment by RomainLanz** [comment]
You can create a PR to do that.

**Comment by GrahamCampbell** [comment]
Send to 5.1 please.

**Comment by juukie** [comment]
Would be nice if it was easy to adjust for other languages.

**Comment by fungku** [comment]
@juukie check pull request #8157

**Comment by phanan** [comment]
This is closed, but I'd suggest -1. "And" is a stop word, when slug is (correct me if I'm wrong) mainly for permalinks.

**Comment by fungku** [comment]
There is an open PR. Feel free to voice your opinion there.

However, keywords in url don't really effect ranking so why not make them more readable for your users?

![ranking](http://www.searchmetrics.com/wp-content/uploads/us-ranking-factors-2013.png)

**Comment by fungku** [comment]
@phanan There is an open PR. Feel free to voice your opinion there.

However, keywords in url barely correlate with ranking so why not make them more readable for your users?

![ranking](http://www.searchmetrics.com/wp-content/uploads/us-ranking-factors-2013.png)

There are other things you should be way more concerned with...

If social stuff has the vast majority of correlation to raning, then improving your content and making things less confusing for your users should be your main priority, and a small part of that could be making your urls readable.

If you are concerned about stop words then you should try to reduce the use of them in your titles (and then they won't be in your slugs either) instead of strippign them out of slugs and making nonsensical urls. If you need to use a stopword in your title then why not keep it in your url too to keep it more easily readable?

P.S. I think even Google agrees. They use "and" in their urls: http://googlewebmastercentral.blogspot.ca/2015/03/safe-browsing-and-google-analytics.html

![and that's all i have to say about that](http://cdn.meme.am/instances/500x/55121519.jpg)

**Comment by phanan** [comment]
@fungku Whoops. Nice read, thanks! Sorry if my opinion offended you in any way.

**Comment by fungku** [comment]
@phanan It takes a lot more than that to offend me ;)
