### ISSUE TITLE
Handle method on queued commands only fires when using sync queue driver

### ISSUE THREAD

**Issue by kidshenlong** [laravel/framework#8161]
If I generate a queue command using `php artisan make:command RandomCommand --queued`

	class RandomCommand extends Command implements ShouldBeQueued, SelfHandling {

	    use InteractsWithQueue, SerializesModels;

		public function __construct()
		{
	        Log::info('Construct Queue Message');
		}

		public function handle()
		{
	        Log::info('Handle Queue Message');
		}

	}

Database/SQS Queue Driver running  `php artisan queue:listen`
`[2015-03-26 01:40:50] development.INFO: Construct Queue Message`  
Sync Queue Driver  output
`[2015-03-26 01:41:39] development.INFO: Construct Queue Message`
`[2015-03-26 01:41:39] development.INFO: Handle Queue Message`

Handle method isn't being called for asynchronous queues.

**Comment by GrahamCampbell** [comment]
Hmmm. Thanks for the report. I'll let Taylor know about this one.

**Comment by TheShiftExchange** [comment]
I cant replicate using Redis queue. Works for me.

**Comment by TheShiftExchange** [comment]
I also cant replicate using Database queue on Homestead - also works for me (using the exact Command code above).

The issue must be in your application elsewhere...?

**Comment by taylorotwell** [comment]
I can't recreate either using SQS.

**Comment by kidshenlong** [comment]
Hmmm. Issue still persists on clean installs of the code on live servers(Digital Ocean Server) but it doesn't happen on Homestead VMs. Willing to close as I think this is just a weird issue specific to something I'm doing.

**Comment by TheShiftExchange** [comment]
@kidshenlong - does it happen with a clean install of a new L5 code base? Or is it your already built application?

**Comment by taylorotwell** [comment]
Pretty much all of my live apps use commands so I would really be screwed
if this is broken. :) ... Still haven't been able to recreate.

**Comment by TheShiftExchange** [comment]
@taylorotwell - yeah - same.

And I was thinking this is one of the 'flagship' features of L5 - so it must be in heavy use out there and we'd have more bug reports by now if there was an overall issue.

**Comment by kidshenlong** [comment]
Tbf it was happening on a built application, so I should've known better. Definitely looks like something I've broken! Anyway thanks for confirming that it was just my installation :) much appreciated.
