### ISSUE TITLE
User::where('id','=',1)->first(); should return exact one object from table, but is returning useless data also

### ISSUE THREAD

**Issue by tayyabhussain** [laravel/framework#8163]

**Comment by tayyabhussain** [comment]
// below is result of $user= User::whereCode($code)->first(); dd($user);
object(User)#171 (20) {
  ["table":protected]=>
  string(5) "users"
  ["guarded":protected]=>
  array(1) {
    [0]=>
    string(2) "id"
  }
  ["connection":protected]=>
  NULL
  ["primaryKey":protected]=>
  string(2) "id"
  ["perPage":protected]=>
  int(15)
  ["incrementing"]=>
  bool(true)
  ["timestamps"]=>
  bool(true)
  ["attributes":protected]=>
  array(10) {
    ["id"]=>
    string(1) "7"
    ["name"]=>
    string(6) "asdasd"
    ["dp"]=>
    string(23) "IMG_20140801_145322.jpg"
    ["email"]=>
    string(29) "amir.javed@coeus-solutions.de"
    ["password"]=>
    string(60) "$2y$10$seobeiSfxsPWps8KdGtcUOEi8oj6Ylk5ntu1c5tbhphItFf6IZNdq"
    ["password_temp"]=>
    string(0) ""
    ["code"]=>
    string(60) "rrhuMm52WIMLxysIY2QgmSn08tCwDlDGCM6eYZs10TgP6zsVZnG66o8CtHce"
    ["active"]=>
    string(1) "0"
    ["created_at"]=>
    string(19) "2015-03-25 11:29:45"
    ["updated_at"]=>
    string(19) "2015-03-25 11:46:11"
  }
  ["original":protected]=>
  array(10) {
    ["id"]=>
    string(1) "7"
    ["name"]=>
    string(6) "asdasd"
    ["dp"]=>
    string(23) "IMG_20140801_145322.jpg"
    ["email"]=>
    string(29) "amir.javed@coeus-solutions.de"
    ["password"]=>
    string(60) "$2y$10$seobeiSfxsPWps8KdGtcUOEi8oj6Ylk5ntu1c5tbhphItFf6IZNdq"
    ["password_temp"]=>
    string(0) ""
    ["code"]=>
    string(60) "rrhuMm52WIMLxysIY2QgmSn08tCwDlDGCM6eYZs10TgP6zsVZnG66o8CtHce"
    ["active"]=>
    string(1) "0"
    ["created_at"]=>
    string(19) "2015-03-25 11:29:45"
    ["updated_at"]=>
    string(19) "2015-03-25 11:46:11"
  }
  ["relations":protected]=>
  array(0) {
  }
  ["hidden":protected]=>
  array(0) {
  }
  ["visible":protected]=>
  array(0) {
  }
  ["appends":protected]=>
  array(0) {
  }
  ["fillable":protected]=>
  array(0) {
  }
  ["dates":protected]=>
  array(0) {
  }
  ["touches":protected]=>
  array(0) {
  }
  ["observables":protected]=>
  array(0) {
  }
  ["with":protected]=>
  array(0) {
  }
  ["morphClass":protected]=>
  NULL
  ["exists"]=>
  bool(true)
}

**Comment by crynobone** [comment]
Do you know about `toArray()`?

**Comment by tayyabhussain** [comment]
no i didn't :) , thanks by the way

**Comment by tayyabhussain** [comment]
@crynobone but now, i'll be unable to use laravel Eloquent's method,
according to $user = User::whereCode($code)->first()->toArray();
// i will not be able to user $user->save(); after setting some properties of user

**Comment by taiyaei** [comment]
Yes, that's because it'd no longer be an object after `toArray()`. Really though you shouldn't need to worry about the "useless data", is there a reason you need to avoid it?
