### ISSUE TITLE
[Blade] Cannot overwrite twice same block

### ISSUE THREAD

**Issue by appcia** [laravel/framework#8181]
I have a following view structure:

A.blade.php
```
@section('example')
Hello!
@show
```

B.blade.php
```
@extends("a")

@section('example')
@parent
Hi!
@stop
```

C.blade.php
```
@extends("b")
@section('example')
@parent
Bonjour!
@stop
```

Expected result:
```
Hello!
Hi!
Bonjour!
```
Actual result (second @overwrite does nothing)
```
Hello!
Hi!
```

I think it is a same problem as described here: http://stackoverflow.com/questions/18417130/laravel-4-extending-a-section-declared-in-a-master-template-more-than-once

**Comment by GrahamCampbell** [comment]
This is unfortunately a limitation of our system. If you can figure out a better way, that would be really awesome. :)

**Comment by franzliedke** [comment]
Is this even a limitation? It seems to work for me (though I'm not doing the duplicate "extends" thing.)

@appcia Have you tried using `@append` instead of `@stop` (that way you also don't need the `@parent`)?
