### ISSUE TITLE
Use queue for PasswordBroker sendResetLink

### ISSUE THREAD

**Issue by miagg** [laravel/framework#8186]
It would be awesome if the `emailResetLink()` in `Illuminate\Auth\Passwords\PasswordBroker` uses the queue for sending the password reset link.

	public function emailResetLink(CanResetPasswordContract $user, $token, Closure $callback = null)
	{
		// We will use the reminder view that was given to the broker to display the
		// password reminder e-mail. We'll pass a "token" variable into the views
		// so that it may be displayed for an user to click for password reset.
		$view = $this->emailView;

		return $this->mailer->send($view, compact('token', 'user'), function($m) use ($user, $token, $callback)
		{
			$m->to($user->getEmailForPasswordReset());

			if ( ! is_null($callback)) call_user_func($callback, $m, $user, $token);
		});
	}

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by WongLeslie** [comment]
I would like to ask how to choose queue for password reset? Simpler way is there? If not I'll have to rewrite sendResetLinkEmail

**Comment by crynobone** [comment]
In Laravel 5.3 (via the new notification), it would be possible to send reset password email via queue. Don't think it going to be back-ported to older release.

**Comment by WongLeslie** [comment]
Thank you, I will be watching with 5.3.

**Comment by WongLeslie** [comment]
In Laravel 5.2 . 
What is correct through the queue to send password reset method?
