### ISSUE TITLE
URL Facade and helpers broken by commit eb0da7a48258682163be3c77bd8173209db67bcb

### ISSUE THREAD

**Issue by istvanszimon** [laravel/framework#8188]
src/Illuminate/Routing/UrlGenerator.php, line 302 change caused 
* url::action()
* link_to_:route
 to incorrectly generate urls:

Basically any method using *replaceRouteParameters()* can misbehave

Example:
Having this controller route: Route::controller('foo', 'FooController');
 {!! URL::action('FooController@getBar', 3)  !!}
Generates: /foo/bar?3
Instead of /foo/bar/3

---
eb0da7a48258682163be3c77bd8173209db67bcb

**Comment by magnetas** [comment]
Is this solved yet? Everything that's action related simply stopped working...

**Comment by istvanszimon** [comment]
You can fix it temporary by changing the given line back, as you see in the
commit diff. Solution is untested

MaGnetas <notifications@github.com> ezt írta (2015. március 27., péntek):

> Is this solved yet? Everything that's action related simply stopped
> working...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/8188#issuecomment-86869743>.
>


-- 
Szimon István
istvan.szimon@ebolaplay.com

**Comment by magnetas** [comment]
Yes. That's exactly what I did. Thank you.

**Comment by m-behr** [comment]
The link_to_route helper method seems also affected
```php
{!! link_to_route('somewhere.edit','edit',['id' => $a->id]) !!}
```
results in :
somewhere//edit?id=1

**Comment by istvanszimon** [comment]
Thank you, i'll update the issue description

**Comment by JoostK** [comment]
Taylor will never merge regex replacements ever again :disappointed:

**Comment by Anahkiasen** [comment]
Although you can always thank these PRs for pointing out missing tests

**Comment by Anahkiasen** [comment]
Although you can always thank these PRs for pointing out missing tests

**Comment by Alifamri** [comment]
reverted back :+1: 
https://github.com/laravel/framework/pull/7892#issuecomment-86962691

**Comment by aimeos** [comment]
Generating URLs is broken for some cases that are expected to work. Tried to add tests for all cases that produce wrong results: #8198

Please suggest further tests that are expected to work but not yet tested
