### ISSUE TITLE
Validation rule required_if doesn't work for boolean values

### ISSUE THREAD

**Issue by pdcmoreira** [laravel/framework#8194]
This fails:

```php
Validator::make([
    'whole_day' => true,
    'time' => ''
], [
    'time' => 'required_if:whole_day,false'
]);
```

**Comment by pdcmoreira** [comment]
Hey @GrahamCampbell can you please provide some information on the issue? Is it somehow an intended behavior?

**Comment by GrahamCampbell** [comment]
Not sure. Have you tried with `1` or `"true"`?

**Comment by pdcmoreira** [comment]
It seems to work with `'required_if:whole_day,0'`.

**Comment by GrahamCampbell** [comment]
:)

**Comment by devboxr** [comment]
Just had exactly the same problem, still not documented. Should definitely be either fix for documented.

**Comment by SaifurRahmanMohsin** [comment]
+1 Thanks @pdcmoreira
It should be documented

**Comment by dattz** [comment]
Perhaps we can have such that required_if looks for "casts" to booleans and then checks for true/false instead of just 1/0?
`protected $casts = ['whole_day' => 'boolean'];`
`required_if:whole_day,true`

**Comment by molerat619** [comment]
any news?

**Comment by vedmant** [comment]
It also just doesn't work if incoming value type is actual boolean.

**Comment by bdjunayed** [comment]
> It also just doesn't work if incoming value type is actual boolean.

My hack is, to refactor this line,
```php
'citizen'           => 'required|boolean',
```
to
```php
'citizen'           => 'required',
```

So, now, it will be available 
```php
            'passport_number'   => 'required_if:citizen,true',
            'visa_type'         => 'required_if:citizen,false',
```

**Comment by planetchili** [comment]
Why is this closed? Either the implementation should be fixed, or the documentation should reflect this surprising (in an unwelcome sense) behavior.

**Comment by driesvints** [comment]
Anyone's free to send in prs to the docs.
