### ISSUE TITLE
Add conversion into Ascii inside str_slug()

### ISSUE THREAD

**Issue by mkwsra** [laravel/framework#8197]
Hello there,
when I use the helper function `str_slug` with characters other than ascii, in my case Arabic characters, the return value in English characters which is super cool if I didn't need the support of SEO or the readable URLs.

Is there any way to add a conversion from utf-8 into ascii so it will return url friendly value ?

For me now I'm using function that I wrote which is doing the trick, I'm posting this as feature maybe!

**Comment by mkwsra** [comment]
@GrahamCampbell anything to help me with ?

**Comment by GrahamCampbell** [comment]
If there is a popular package with transformation for these characters, perhaps we could use this, otherwise, this is probably out side the scope of the framework core.

**Comment by mkwsra** [comment]
@GrahamCampbell Okay, thanks a lot, and amazing work btw

**Comment by GrahamCampbell** [comment]
:heart:
