### ISSUE TITLE
vendor:publish doesn't handle files that are named ..ext (e.g. ..png in KCFinder) properly.

### ISSUE THREAD

**Issue by BenWoodford** [laravel/framework#8199]
So this is a very... 'niche' thing but occasionally things such as KCFinder will include an oddly named file such as '..png', read as dot.png.

When you do a vendor:publish from a package that includes KCFinder (for instance), it'll look for img/filespng instead of img/files/big/..png due to the rather peculiar naming scheme for that file. At least, that's what I've gathered. It'll then throw this error:

```
$ php artisan vendor:publish      
                                                      
  [League\Flysystem\FileNotFoundException]                      
  File not found at path: js/kcfinder/themes/dark/img/filespng
```

If you want a test case, my [fork](https://github.com/BenWoodford/Laravel-Administrator/tree/KCFinder) of Frozennode Admin has it under the kcfinder branch.

**Comment by GrahamCampbell** [comment]
Could you provide us with an isolated example please.

**Comment by BenWoodford** [comment]
Start up a new project, tack this in the composer.json:

```
	"repositories": [
	{
		"type": "vcs",
		"url": "https://github.com/BenWoodford/Laravel-Administrator.git"
	}
	],
```

and:

`"frozennode/administrator": "dev-KCFinder",`

`composer update`
`php artisan vendor:publish`

**Comment by GrahamCampbell** [comment]
That's not isolated.

**Comment by bflydesign** [comment]
Any solution to this problem?
