### ISSUE TITLE
Opcache issue in a Apache2 with fcgi environment.   

### ISSUE THREAD

**Issue by Dominic108** [laravel/framework#8201]
I used the latest version of PHP running as cgi-fcgi with suexec.   I simply installed Laravel with the commands  `cd /var/www` and `sudo composer create-project laravel/laravel test_laravel  --prefer-dist`  .  I created a site `laravel.ca` with document root `/var/www/test_laravel/public`. To test this new site, I created a  file `/var/www/test_laravel/public/test.php` with simple content `echo "Hello World";`.  I added `<myip> laravel.ca` in my host file, so that the domain laravel.ca is resolved on my server.  The URL `http://laravel.ca/test.php` works fine on my server.  However,  when I visit `http://laravel.ca/` I get an  Internal Server Error . In /var/log/syslog, I have the error message ` ... kernel: php5-cgi[6741]: segfault at 0 ip 00000000006fe0d1 sp 00007fff28397df0 error 4 in php5-cgi[400000+7ee000 `.  However, if I comment out `zend_extension=opcache.so` in the file `\etc\php5\apache2\conf.d\05-opcache.ini` , the same URL works fine : I get the Laravel welcome page. If I uncomment it (enable opcache), I get the same error message again.  So, there seems to have an issue with opcache. I don't have this issue with other applications, only with Laravel. Laravel  works fine in other environments, but if it is reproducible with php, fcgi and suexec, then it qualifies as a bug.  I used the latest version of Ubuntu with a recent update of all packages.  Note that I have no issue when I use PHP on the command line to access `/var/www/test_laravel/public/index.php`. The issue occurs only on the web - the php config must be different : perhaps opcache is disabled on the cli.

**Comment by Dominic108** [comment]
I make the perhaps wrong assumption that those who support Laravel code consider this issue as an installation support request, not as a bug report that requires their attention.  The line that separates bug reports from support requests and feature requests is not very well defined.  It could very well be that the current issue entirely qualifies as an installation support request. This would be the case if the issue is due to something in my environment that is very special, but fcgi and suexec are not in themselves very special.  If the problem is reproducible in this very common environment, then it qualifies as a bug.  This is why I ask, if any one has succeeded to install the most recent version of Lavarel with fcgi and suexec with no special configuration.

**Comment by Dominic108** [comment]
The issue is with the caching of /vendor/compiled.php.  Since the file is large (more than 500k), simply adding the php option `opcache.max_file_size= 500000` in php.ini was sufficient to prevent this file from being cached and this made the issue disappear.  However, I don't understand why it could not be cached.  Perhaps there are conflicting configuration setting with my implementation of fcgi on Ubuntu.  So, my question remains. Did someone succeed to  install Laravel with fcgi and suexec, with no extra special configuration?

**Comment by Dominic108** [comment]
Here is better solution. Cd to your Laravel root and execute : 
    php artisan down
    php artisan clear-compiled
    composer update --no-dev
    php artisan optimize
    php artisan up

**Comment by GrahamCampbell** [comment]
If you're getting segfaults, it's definitely a php bug, so we can't fix it here.

**Comment by GrahamCampbell** [comment]
I've just had a look at that thread. The easy fix is to manually delete the compiled file. You don't need to reclone the project!

**Comment by Dominic108** [comment]
Non sense to say that it is not a bug here because it is a PHP bug. If Laravel pushes PHP to its limits and brings out bugs in it that we don't see otherwise, then it is also a Laravel bugs.   It is the responsibility of a developer to respect the limit of the tools that it decides to use, which are never perfect.  The end users want something that works... If you use a tool that is not perfect, then use it in a way that works. So, yeah, it is a bug ... exactly what I call a bug.

**Comment by phanan** [comment]
> If Laravel pushes PHP to its limits and brings out bugs in it that we don't see otherwise, then it is also a Laravel bugs

I wouldn't say so. We developers need to configure our system to fit different needs. For example, my Drupal sites always have `memory_limit` set to at least 256M. Or, think about the default 2MB max upload file size set in `php.ini`. If your PHP script fail to upload a 2.5MB image, do you blame it? I don't think so. You'll go and change the `upload_max_filesize` value. This doesn't look like a Laravel bug to me.

> You can document it and propose the correct way to install Laravel so that this PHP limitation is avoided.

I'd agree, thought it sounds a bit overkill. Then again, [Laravel Docs](https://github.com/laravel/docs) is open source as well.

**Comment by Dominic108** [comment]
There are no PHP bug at all in the example you provided, because it is all about documented limits. I believe that, in this case, GrahamCampbell was referring to a PHP bug, ie., a non documented limit in PHP.  If Laravel brings out such a limit without documenting it either, it becomes a bug in Laravel too, In fact, even if it was documented in PHP, Laravel must do its part by documenting this limit in its system requirements. The current issue is mainly about documentation, but it does not mean that it is not a bug.  On the contrary, because it is a non documented limit, it becomes a bug.  Sure, your argument that the documentation is open source is valid. I totally agree. I cannot take a tone where I blame others, but I can still say that it is a bug.  Now, is this the correct place to chat like we do?

**Comment by phanan** [comment]
> Dominic108 changed the title from Opcache issue in a Apache2 with fcgi environment. to Waste of time 11 hours ago

> @Dominic108Dominic108 changed the title from Bug in some PHP environment with compiled.php: what is better, not use it or not cache it? to Waste of time 11 hours ago

Wow... just... wow...

**Comment by GrahamCampbell** [comment]
@Dominic108 Now it's a waste of time. You deleting this issue means that anyone else wondering the same thing as you can't see this anymore.
