### ISSUE TITLE
[Proposal] Correctly catch large post errors instead of CSRF error

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#8202]
So I was doing some AJAX file uploading, and kept getting random `TokenMismatchException` errors. After much debugging - I realised the issue related to `post_max_size`.

If the file I was attempted to upload was greater than my `post_max_size` - PHP clears the super globals of `$_POST` and `$_FILE` - **but** still sends the server the POST request (which is now empty).

The problem is that the empty post hits Laravel, and when doing CSRF detection there is no `_token` - so you'll get a `TokenMismatchException`, leading you on wild goose chases as to why your forms are not sending correct tokens.

It also means that the user will be shown an incorrect error. Rather than be told they are uploading a file that is *way* to large - it just throws a 500 error with the wrong message.

I did some investigating - and there is a way to detect this situation. I propose we include this in the CSRF detection, to ensure we are throwing the correct message. It doesnt change the behavior of the CSRF rules (it still stops access) - but at least we can correctly identify *why*:

Some very rough code (can be refactored):

```
    public function handle($request, Closure $next)
    {
        if ($this->isReading($request) || $this->tokensMatch($request)) {
            return $this->addCookieToResponse($request, $next($request));
        }

        if ($_SERVER['CONTENT_LENGTH'] > ini_get('post_max_size')) {
              Throw new PostTooLargeException;
         }
         
         Throw new TokenMismatchException;
    }
```

*Note* - this is significantly different to when the file upload is greater than `max_file_upload` but less than `post_max_size` - PHP keeps the globals, it just gives a file error which Laravel already handles.

**Comment by TheShiftExchange** [comment]
Actually - thinking outloud - maybe this should be extracted to its own global HTTP middleware? Rather than part of the CSRF check?

Can be called just before the CSRF check...

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by TheShiftExchange** [comment]
@GrahamCampbell to 5.0 or 5.1?

**Comment by GrahamCampbell** [comment]
Hmmm. Not sure. Just do what you think, and Taylor will tell you if he wants it moving.
