### ISSUE TITLE
Error send mail 

### ISSUE THREAD

**Issue by it9xpro** [laravel/framework#8204]
use Illuminate\Contracts\Mail\Mailer as Mail;

FatalErrorException in WelcomeController.php line 35: Non-static method Illuminate\Contracts\Mail\Mailer::send() cannot be called statically, assuming $this from incompatible context

why ? help me

**Comment by TheShiftExchange** [comment]
This is not a bug - it is a support issue.

You need to post for help in the http://laravel.io/forum - not here

**Comment by it9xpro** [comment]
thank ! TheShiftExchange
