### ISSUE TITLE
FilesystemManager not bound in IoC by type.

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#8207]
Is there any reason why `FilesystemManager` can't be injected?  It seems to only be bound to the IoC by a string name.

**Comment by GrahamCampbell** [comment]
We're open to pulls to alias it.

**Comment by franzliedke** [comment]
It is bound to the factory contract:
https://github.com/laravel/framework/blob/f868261433cb06b3f8cdddd4a6263a63bd38d727/src/Illuminate/Foundation/Application.php#L999

**Comment by GrahamCampbell** [comment]
@franzliedke Both should be bound, surely?

**Comment by franzliedke** [comment]
Good point, I sent a PR.
