### ISSUE TITLE
Possible Bug with Blade Templating Comments

### ISSUE THREAD

**Issue by AdenFraser** [laravel/framework#8212]
When commenting out multiple blade control blocks together there appears to be an issue with subsequent blade output on a page.

Given the following example:

```php
<p>
    {{ $key }} : {{ $value }} 
</p>
<a href="{{ url('/link/'.$value) }}">
    Link Title
</a>
```

If you then comment out the whole 2nd line like so:
```php
<p>
    {{-- $key }} : {{ $value --}}
</p>
````

The expected behaviour would be that this would be the result when rendered and cached in the /storage/views folder:
```php
<p>
    <?php /* echo e($key); ?> : <?php echo e($value); */ ?>
</p>
<a href="http://localhost/link/value">
    Link Title
</a>
````

However the actual output ends up being:
```php
<p>
    <?php /* $key }} : <?php echo e($value */ ?>
</p>
<a href="{{ url('/link/.$value)); ?>">
    Link Title
</a>
````

With the attempt of echoing the url failing.

Assuming this is a valid bug request I'm willing to look into it further and put together a pull request :)

Aden

**Comment by GrahamCampbell** [comment]
Not a bug. Our comments are just very limited, though, if you can implement a fix, that would be really cool.
