### ISSUE TITLE
Bug in some PHP environment with compiled.php: what is better, not use it or not cache it?    

### ISSUE THREAD

**Issue by Dominic108** [laravel/framework#8214]
In a closed bug https://github.com/laravel/framework/issues/8201, which occurs in some common PHP environments (fcgi),  the proposed solution was to not use the compiled file.  This compiled file is documented in this way :   
```
To dramatically increase your application's performance, you may use a
compiled class file which contains all of the classes commonly used
by a request. The Artisan "optimize" is used to create this file.
```
Another possibility is to use this file, but  not cache it using the option `opcache.max_file_size= 500000` in php.ini.  The file being larger than 500k bytes, it will not be cached. This could be  a better solution because most files will be cached and we will still use this compiled file. So, what is the best option?    Perhaps the bug here is in the documentation : the paragraph above might not apply anymore in new optimized Laravel.

**Comment by GrahamCampbell** [comment]
That;s not for us to decide. You do what's fastest on your server. Feel free to discuss on the forums though, but not here.

**Comment by GrahamCampbell** [comment]
@Dominic108 How rude.

**Comment by Dominic108** [comment]
If you feel that you gave some thing valuable to a person and the person tells you that it is not useful to him, you want to take it back.  That's exactly the way I felt when you clearly said the issue should have been raised elsewhere, with the PHP team.  If you felt that it was useful to raise this issue at Laravel, then you shouldn't have said that it should have been raised elsewhere.  You should instead have expressed some appreciation for the issue raised.  You did not show any appreciation at all.   Very honestly, I am telling you, very honestly, I thought you would have considered logical  that I erased my contribution.  I innocently thought  that you and others would have continued the process to delete this issue. I even had the thought that perhaps you will have been grateful that I start this deletion process, because, after all, you did say that it was not at the right place at Laravel.   I was surprised that I was blamed to start deleting this issue.
