### ISSUE TITLE
Is the "forgetPushed()" method needed on Illuminate\Contracts\Events\Dispatcher?

### ISSUE THREAD

**Issue by dankobiaka** [laravel/framework#8216]
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Contracts/Events/Dispatcher.php#L62

What is the purpose of the `forgetPushed()` method on the event dispatcher contract?

There is no other reference to "pushed" events in the contract.

I can see how it's being used in the concrete implementation (Illuminate\Events\Dispatcher), however I don't see how `forgetPushed()` is useful without the corresponding `push($event, $payload = array())` method.

**Comment by GrahamCampbell** [comment]
Maybe, yeh. We're open to pulls, though adding methods to an interface is a breaking change, so must go to the master.

---
Disclaimer: this is not me accepting this idea. Only Taylor has the power to do this.
