### ISSUE TITLE
Laravel Socialite - twitter email support

### ISSUE THREAD

**Issue by mitchobrian** [laravel/framework#8218]
Socialite is supporting google+, facebook, github and twitter. But the overall public fields id, nickname, name, email and avatar aren't filled out by every provider. For facebook and google+ there is email provided, for github I have a fix but for twitter there seems to be no way to get the users email address for own purposes?!

http://stackoverflow.com/questions/3599621/is-there-a-way-to-get-an-users-email-id-after-verifying-their-twitter-identity

The question, is there any idea about a workaround to get the users email information by twitter or from an oAuth partner to complete the oAuth profile?

**Comment by crynobone** [comment]
Based on above link http://stackoverflow.com/a/3627563/1458318 (one of the answer)

> The user's email address can not be retrieved via the API. This is a deliberate design decision by the API team.

If Twitter purposely disallow retrieving e-mail address do you have an alternative suggestion?
