### ISSUE TITLE
Migrate Rollback has no paths option

### ISSUE THREAD

**Issue by sorora** [laravel/framework#8220]
When migrating, there is a path option that can be supplied to migrate files from a different directory. When rolling back migrations, there's no path option, so trying to rollback migrations from a custom path is impossible from what I can see.

Request: Add paths option to migrate:rollback command.

**Comment by phanan** [comment]
The `rollback` action uses the data from `migrations` table, so I guess there's no need of a `path`, right?

**Comment by GrahamCampbell** [comment]
Yeh, this has been brought up before. Feel free to look through recently closed issues/pulls.

**Comment by sorora** [comment]
@phanan the migrations table doesn't specify where those migrations came from, so it looks in the normal migrations folder.

@GrahamCampbell I have looked through quite a few of the previous requests already - most of these revolve around packages (which is not what I'm trying to achieve). None of them had an obvious solution to the issue that I could see, however I've found that `composer dump` fixes the issue... so that resolves that!
