### ISSUE TITLE
Blade extend pattern: useless left parenthesis in match $2

### ISSUE THREAD

**Issue by ArtemFitiskin** [laravel/framework#8224]
**any.blade.php**:
```html
<div>
  @int($total)
</div>
```

**BladeServiceProvider.php**:
```php
Blade::extend(function($view, $compiler)
{
  $pattern = $compiler->createOpenMatcher('int');

  return preg_replace($pattern, '$2', $view);
});
```

**Result:**

```html
<div>($total
</div>
```

Laravel 5.

**Comment by ArtemFitiskin** [comment]
Maybe I used it wrong?

**Comment by Arrilot** [comment]
I had a similar issue. 
The documentation http://laravel.com/docs/5.0/templates#extending-blade is kinda weird because `createMatcher` and `createPlainMatcher` are discussed and when it comes to an example `createOpenMatcher` is used.

Anyway, use `createMatcher` in this case and you should be ok

**Comment by GrahamCampbell** [comment]
We're open to pull requests to update the docs. :)
