### ISSUE TITLE
Redirect Trailing Slashes Querystring Encoding Issue

### ISSUE THREAD

**Issue by vcmattp** [laravel/framework#8227]
The following line within the standard htaccess causes problems when using certain characters:

 # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

For instance the url '/application/?keyword=Ñ' gets rewritten as: '/application?keyword=%25C3%2591', which is wrong. This problem is especially apparent when using the paginate control.

To get around the problem I modifed this line to the following, which fixes the problem (by not encoding querystrings):

 # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301,NE]

**Comment by GrahamCampbell** [comment]
Thank you, but this is a duplicate. Feel free to flick through the original, and the other duplicates.

**Comment by franzliedke** [comment]
I couldn't find any duplicates. Can you link to one?
