### ISSUE TITLE
Illuminate\Foundation\Console\ClearCompiledCommand uses methods not defined in contract

### ISSUE THREAD

**Issue by dankobiaka** [laravel/framework#8229]
See https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/ClearCompiledCommand.php#L28

`Illuminate\Foundation\Console\ClearCompiledCommand::fire()` uses two methods that are actually not part of the Illuminate\Contracts\Foundation\Application interface:

`$compiledPath = $this->laravel->getCachedCompilePath(); $servicesPath = $this->laravel->getCachedServicesPath();`

As the command objects depend on the Application contract / interface only (https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/Command.php#L382), not the Illuminate\Foundation\Application implementation, **should any commands rely on methods not available in the interface**?

The `ClearCompiledCommand::fire()` seems to be tightly-coupled to the implementation class, not the interface.

**Comment by GrahamCampbell** [comment]
Adding methods to interfaces is a breaking change and could result in fatal errors. We'd accept a pull to 5.1 though.

**Comment by guiwoda** [comment]
This should not be closed. Having the command depend on the interface means right now this breaks on any scenario where the `Application` object is not the default Laravel one, but does adhere to `Illuminate\Contracts\Foundation\Application`. Not fixing this is as problematic as accepting the fix, as both BC change and bug are edge use cases.

**Comment by GrahamCampbell** [comment]
It was closed because I'd requested a pull request to go to 5.1.
