### ISSUE TITLE
[L5] Paginator links broken on apache when app installed in non-base path

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#8231]
This affects both the standard ['simple'](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Pagination/Paginator.php#L39) and [length aware paginator](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Pagination/LengthAwarePaginator.php#L49).

```php
$this->path = $this->path != '/' ? rtrim($this->path, '/').'/' : $this->path;
```

Notice the trailing slash which generates urls like:

> http://localhost/my-app/public/users/?page=1

In the htaccess trailing slashes are redirected back to base url:

```
# Redirect Trailing Slashes...
RewriteRule ^(.*)/$ /$1 [L,R=301]
```

So when you navigate, you get redirected to simply `http://localhost/users/?page=1` essentially breaking pagination when you use apache.

**Comment by sureshbala** [comment]
For now, this can be manged via setPath method
`$results->setPath('url')`

**Comment by garygreen** [comment]
@GrahamCampbell maybe this can be re-opened for Taylor to respond? It's a bug and an issue for those that use apache, like me :-)

> This has been discussed before. Not why we didn't do anything. Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
@garygreen Taylor doesn't normally read the issues, though, I can re-open it you want, for the community to look at.

**Comment by garygreen** [comment]
Cheers buddy!

**Comment by Believedecision** [comment]
I have the same issue.

**Comment by eusonlito** [comment]
I have the same problem and is not a solution to add `RewriteBase` to `.htaccess` (problems with different develop environments).

Also, all pages are redirected from /? to ? with a 301 redirection.

`$list->setPath('')->render()` can be a fast fix, or a `str_replace('/?', '?', $list->render())` but I think that must be fixed on core.

**Comment by ifaniqbal** [comment]
+1

**Comment by sameernyaupane** [comment]
+1 . Same issue here.

**Comment by GrahamCampbell** [comment]
+1ing issues doesn't mean they get fixed. Issues are here for the community to fix.

**Comment by sameernyaupane** [comment]
@GrahamCampbell  sorry, I am new to contributing to open source. I would surely love to do so, but I doubt I could do much currently. I know you guys are busy enough, but would be nice to get it fixed when you have time.

**Comment by garygreen** [comment]
@GrahamCampbell Whilst issues/PRs are open your always going to get people contributing their thoughts and +1 is a perfectly acceptable way to do so. As said before, it helps gauge number of people affected by the issue, and useful on PRs to see interest. A issue with lots of +1s is more likely to get interest from a member of the community in fixing/providing a PR rather than a stale one without any interest shown.

**Comment by crynobone** [comment]
> I know you guys are busy enough, but would be nice to get it fixed when you have time.

It not that simple, Taylor has said in many of previous discussion that Laravel was meant to be instead only in base path. So asking him to fixed something that he never has attention to support in the first place is just contradicting. So when @GrahamCampbell said is for the community to fix, he really means it.

**Comment by garygreen** [comment]
Ok then, screw everyone installing Laravel in a non-base path. Nice view. Sigh

**Comment by sameernyaupane** [comment]
@crynobone , thanks for the explanation. Didn't know that. As said by @garygreen , this is really inconvenient. Anything that makes you go the extra mile to get things working, is not a RAD. And I guess our philosophy as Laravel is to make the work as painless as possible for developers. And if this is not possible to be fixed, it should be stated clearly on the pagination section on the Laravel doc. And of course, the community can do a PR for that.

**Comment by crynobone** [comment]
> Ok then, screw everyone installing Laravel in a non-base path. Nice view. Sigh

Take it in a positive way, you can either:

1. try to make taylor changes his mind.
2. have someone in the community to create a PR fix without breaking anything else (this give better argument for taylor to accept such PR). 

My point with this is that, sure you +1. But don't +1 hoping that Laravel Contributor is going to do anything about it, or argue in future why the team never done anything to fix this 1, 2, 3 years down the road despite getting hundreds of +1.

**Comment by garygreen** [comment]
@crynobone Any chance of seeing in the documentation (maybe installation instructions) that Laravel it should NOT be installed in a non-base path? Because under your's/Taylors view Laravel does not support it, therefore it is a installation prerequisite and should be documented.

Will it be? Probably not, because it's ludicrous to think a framework doesn't support installing in a non-base path. I risk to say you do it too.

I'm not having a go at you, just really think this should be left open for Taylor to see and decide if it's something he wants to support/fix (it would be a simple case of removing that redirect in the htaccess file). At minimum, this should be documented.

**Comment by crynobone** [comment]
> Because under your's/Taylors view Laravel does not support it, therefore it is a installation prerequisite and should be documented.

It not my view, as I said before 

*"Taylor has said in many of previous discussion that Laravel was meant to be instead only in base path."* 

This can be referred in some of previously closed PR such as 

https://github.com/laravel/laravel/pull/3263#issuecomment-75479437
https://github.com/laravel/laravel/pull/3145#issuecomment-76609803 (closed with same reason).
https://github.com/laravel/laravel/pull/3163#issuecomment-65732049
and many more (even with Lumen).

**Comment by taylorotwell** [comment]
If someone submits a really high-quality PR that fixes these things, then
we will review it. Symfony has an .htaccess file you can look at. I'm sure
something similar would work fine for Laravel.

**Comment by msonowal** [comment]
I am still getting the issue on Laravel 5.0.33

**Comment by aliwaqassi** [comment]
{{$stories->appends($_GET)->links() }}
