### ISSUE TITLE
Getting Config variables from subfolders broken in 5.0.23

### ISSUE THREAD

**Issue by mistakevin** [laravel/framework#8234]
My config is structured as

```
config/
    subfolder/
        my_file.php
```
and none of the ways I've read to grab the value works
```
Config::get('my_file.value')
Config::get('subfolder/my_file.value')
Config::get('subfolder.my_file.value')
config('my_file.value')
config('subfolder/my_file.value')
config('subfolder.my_file.value')
```
neither does adding it `ConfigServiceProvider.php`
```
public function register()
{
	config([
		'config/subfolder/my_file.php'
	]);
}
```
`Config::get('my_file.value')` still works in Laravel 5.0.0.

Anybody else seeing this behavior?

**Comment by GrahamCampbell** [comment]
Config was changed in a later L5 version after people complained that subfolders were broken. If you want to use the 5.0.0 code, then don't put the config in a subfolder, and everything will work again.

**Comment by crynobone** [comment]
> Config was changed in a later L5 version after people complained that subfolders were broken.

I would think that this is a valid issue as he mention (in the title) *Getting Config variables from subfolders broken in 5.0.23* even with `config('subfolder.my_file.value')`.

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L87 still contain nested setup

**Comment by phanan** [comment]
Echoing @crynobone. Subfolder config was added back by @antonioribeiro on [Feb 15](https://github.com/laravel/framework/commit/fee982004a795058ab6a66e1600c11aac6748acf).
