### ISSUE TITLE
[L5] Blueprint - enable jsonb column type

### ISSUE THREAD

**Issue by modmanx** [laravel/framework#8240]
It would be nice to be able to add jsonb type column for PostgreSql.

**Comment by olso** [comment]
+1

**Comment by GrahamCampbell** [comment]
We can't support columns that are not supported by all databases. You can manually specify column types anyway though.

**Comment by modmanx** [comment]
Did I miss something in documentation - how can I manually specify column type? method addColumn is protected therefore not accessible from migration.

**Comment by GrahamCampbell** [comment]
I'll leave this open for discussion then.

**Comment by Arrilot** [comment]
Another example - mssql doesn't really support `enum` or `json`, so `nvarchar` is used for those methods instead. https://github.com/laravel/framework/blob/8865d2276be94f0a3497ba3bd26c906ae9e91e1c/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L392

So i guess there is nothing wrong in adding `jsonb` support. Just make a PR against master(?) branch

**Comment by modmanx** [comment]
OK, I'll try. Thank you.

**Comment by neomerx** [comment]
I would try to discover the following possibility
* inherit from ```Illuminate\Database\Schema\Blueprint``` and add jsonb column support
* update migrate up
```php
        Schema::blueprintResolver(function($table, $callback) {
            return new YourBlueprint($table, $callback);
        });
        Schema::create(Model::TABLE_NAME, function (Blueprint $table) {
	
			/** @var YourBlueprint $table */
			table->jsonb(...);

        });
```

**Comment by Arrilot** [comment]
This can be closed
