### ISSUE TITLE
Cannot access camelCase relationship as a property

### ISSUE THREAD

**Issue by thril** [laravel/framework#8241]
I am unable to access a relationship as a property if the method name has multiple words camelCased. E.g., the following **does not** work:

```php
// Project
public function superTalents()
{
    return $this->belongsToMany('My\Domain\Talent', 'project_talents', 'project_id', 'talent_id');
}

// in Tinker or via web app
$project = \My\Domain\Project::find(1);
$project->superTalents->toArray();
```

Doing the above produces the following fatal:

```
PHP Fatal error:  Call to a member function toArray() on a non-object in /Users/thril/Projects/Whatev/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code on line 1
```

And if I access the above as a method call, I get the following:

```php
>>> $project->superTalents();
=> <Illuminate\Database\Eloquent\Relations\BelongsToMany #000000004b7de3e5000000005cd99e3d> {}
```

However, the following method names **do** work:

```php
// Project
public function super_talents() {...}
// or
public function talents() {...}

// in Tinker or via web app
$project = \My\Domain\Project::find(1);
$project->super_talents->toArray(); // good to go
// or
$project->talents->toArray(); // good to go
```

I'm on laravel 5.0.23. This appears to be a bug. Please let me know if I'm missing something.

**Comment by GrahamCampbell** [comment]
You need to access it as `->superTalents`, not `->superTalents()`.

**Comment by GrahamCampbell** [comment]
The property access actually is the result of the query, rather than a relationship object.

**Comment by thril** [comment]
@GrahamCampbell, I don't believe you actually read the problem. As indicated in my description, I got a fatal error when doing...

```php
$project->superTalents->toArray()
```

because `superTalents` is not a proper collection like `super_talents` or just `talents` would be. The issue still stands. By just changing the relationship name to use camelCasing, it fails. That sounds like a bug to me. Please reopen this issue.
