### ISSUE TITLE
Composer update error : Call to undefined method Illuminate\Foundation\Application::getCacheCompilePath

### ISSUE THREAD

**Issue by congkhuong** [laravel/framework#8249]
I use laravel 5 and  just update my laravel app by composer update and get error:
Call to undefined method Illuminate\Foundation\Application::getCacheCompilePath

Please check here for more detail: http://screencast.com/t/TnhFpm1az

**Comment by crynobone** [comment]
Duplicate of #8127

**Comment by congkhuong** [comment]
Sorry, will close it now
