### ISSUE TITLE
Migrations failing 

### ISSUE THREAD

**Issue by maltex** [laravel/framework#8250]
When using an the auto generated migration files, I'm now getting a failure every time:

{"error":{"type":"ErrorException","message":"iconv(): Wrong charset, conversion
from `ascii' to `utf8\/\/IGNORE' is not allowed","file":"C:\\wamp\\www\\my_app\\vendor\\patchwork\\utf8\\class\\Patchwork\\PHP\\Shim\\Mbstring.php","lin
e":103}}

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported anymore.

**Comment by hyperized** [comment]
This is a little crude response since the migration steps from 4.2 to 5.0 are pretty steep and 5.0 has some serious issues with external libs and integration. Enough reason for us to not to migrate to 5.0 any time soon for existing sites. We too are running into this issue when patching database via migrations on existing sites.

**Comment by AdamWillden** [comment]
In case someone else lands here I hit the same error for a different reason. Ensure you have the mbstring php extension enabled.

**Comment by GrahamCampbell** [comment]
Laravel physically won't install unless you have it enabled.

**Comment by AdamWillden** [comment]
Regardless, a suggested fix that might help someone is better than nothing at all!! Also I assume that depends on how you 'install' too as I'd not run into the problem before relatively recently.

**Comment by sibinx7** [comment]
I have similar experience. I had install MAMP and XAMP, I gave MAMP's PHP path in System variable. I change php path to XAMP's php directory. It working now... Please check your PHP path and check curresponding php.ini file. Enable mbstring and restart apache server.
