### ISSUE TITLE
[Proposal] [5.0] Auth component - PasswordBroker - Hashing - password_hash() function usage

### ISSUE THREAD

**Issue by shehi** [laravel/framework#8256]
As we know PHP has got ```password_hash()``` function starting v5.5.0. I am currently writing Auth for my Laravel based open-source project, and I noticed we are just ```bcrypt()``` ing passwords in Laravel 5 auth component (which is default crypt algo in current PHP). To make things forward-ready (forward-compatible?) PHP recommends having 255-char-long field instead of 60-char-long field (which is Bcrypt's length) for password hashes.

I would like to create and implement a certain Hashing interface/contract which would enable usage of both regular ```bcrypt()``` for PHP < 5.5 and ```password_hash()``` wrapper for beyond 5.5. Do you think such implementation would be welcomed in this project? Of course I will include all necessary function/version checks and unit-tests (if applicable). Thanks!

**Comment by GrahamCampbell** [comment]
Not going to happen I don't think, sorry. Laravel 5.2 will be php 5.5+, so I don't think there are any plans to add extra php 5.4 work around at this point.

Also, laravel already requires a library that makes the password_hash available on php 5.4.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.0/composer.json#L25 :)

**Comment by GrahamCampbell** [comment]
Though, you have raised a good issue regarding bycrypt. That probably needs changing. Ping @taylorotwell.

**Comment by shehi** [comment]
@GrahamCampbell but that requirement contradicts with this line:
https://github.com/laravel/framework/blob/5.0/composer.json#L18

Its actually an awesome news. So, it means that basic ```bcrypt()``` usage will be replaced with ```password_hash()```, right? Let me find the line.

**Comment by shehi** [comment]
@GrahamCampbell , @taylorotwell : Line I mentioned:
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Auth/ResetsPasswords.php#L105
