### ISSUE TITLE
Calling migrate:reset --pretend wil cause Infinite Loop

### ISSUE THREAD

**Issue by chainlist** [laravel/framework#8262]
Hi !

I discovered a weird issue today, not sure if it's from me or Laravel but
when i'm calling 

```
$> php artisan migrate:reset --pretend
```

That causes an infinite loop.

Please get back to me if you have more infos !

PS: Sorry for my english, not my native language.

EDIT: I tried from a fresh install with the two default migrations (users and reset_password), infinite loop too.

**Comment by willrowe** [comment]
I can confirm this behavior. As can be seen [here](https://github.com/laravel/framework/blob/3f223fba974bf56551d576618109ec50429fe0b2/src/Illuminate/Database/Console/Migrations/ResetCommand.php#L59-L72) there is a while loop that depends on the `migrator` actually rolling back the migration, but since it's pretending it will go into an infinite loop.

**Comment by onbjerg** [comment]
Yes, somehow we have to decrement the number of pending migrations, without actually doing that. Hmm.

**Comment by onbjerg** [comment]
Maybe we could set count to ``count($this->migrator->getRepository()->getLatest())`` (if we're pretending), on line 61 of ResetCommand.php and decrement it each time we loop. It just feels like a hack.

**Comment by willrowe** [comment]
That won't work since it will only get the latest migration and not all of them.

**Comment by onbjerg** [comment]
Yes. I just realized. We will have to add a $pretend flag to the delete method on MigrationRepositoryInterface.

**Comment by onbjerg** [comment]
Yes, I just realized.

**Comment by chainlist** [comment]
Why not wrap the while around ab DB::transaction and rollback the transaction at the end of function ?

**Comment by GrahamCampbell** [comment]
We're open to pull requests.

**Comment by onbjerg** [comment]
We could also move the migration temporarily in order to fake us deleting it, and then move it all back afterwards. But that seems weird, also. And it's not really up to the repository to pretend to be deleting the migration.

**Comment by willrowe** [comment]
I can work up a PR for this unless someone else is eager to.

**Comment by onbjerg** [comment]
I'd love to, but I think it's too big of a task for a first PR :grin: Go for it!

**Comment by chainlist** [comment]
Yup, same go for it =)

**Comment by willrowe** [comment]
Alright, I'll get on it.
