### ISSUE TITLE
I Wrong Or That's Bug

### ISSUE THREAD

**Issue by bylinggha** [laravel/framework#8267]
I try laravel 5 and i use 
Hello, {!! $name !!}.
like the tutorial in http://laravel.com/docs/master/templates
but the $name show and not hide..

maybe i wrong or that's bug.

Thanks.

**Comment by onbjerg** [comment]
I am not sure what you are asking.

When you use {!! $var !!} the output is not escaped, that is, HTML and so forth is going to be printed, if the variable contains it.

It has nothing to do with hiding or showing something.

**Comment by bylinggha** [comment]
ok thanks guys
