### ISSUE TITLE
forceCreate no longer works

### ISSUE THREAD

**Issue by stevenmyhre** [laravel/framework#8268]
See pull request #8213 for the bug description

```
User::forceCreate(array(
    'name' => 'Steven'
    'email' => 'steven@example.org'
));
```

Error is: Cannot instantiate abstract class Model

**Comment by GrahamCampbell** [comment]
Your provided code just doesn't work anyway? https://i.starbs.net/RRPL

**Comment by GrahamCampbell** [comment]
https://i.starbs.net/KRrG

**Comment by GrahamCampbell** [comment]
I can't replicate this.

**Comment by stevenmyhre** [comment]
Sorry, forgot to include a column, I wasn't intending anyone to run exactly my sample code.  I'm using a different entity that no one else would have, so I tried to create a psuedo-example with the User type.  Try this:

```
App\PERS\User::forceCreate(array(
            'name' => 'Steven',
            'email' => 'steven@example.org',
            'password' => 'test'
        ));
```
http://i.imgbox.com/jgYVNUG3.png

**Comment by GrahamCampbell** [comment]
That example works fine for me.

**Comment by GrahamCampbell** [comment]
Maybe this is a bug in php. Upgrade to the latest 5.5.x version.

**Comment by stevenmyhre** [comment]
I'm running off of PHP version `5.5.11` and laravel/framework `5.0.26`

**Comment by GrahamCampbell** [comment]
Yeh, 5.5.11 is way out of date.

**Comment by GrahamCampbell** [comment]
5.5.23 and 5.6.7 are currently the two recommended versions of php.

**Comment by stevenmyhre** [comment]
Okay, so laravel isn't supporting anything less than that? The docs say >= 5.4

**Comment by GrahamCampbell** [comment]
We're supporting newer versions of 5.4.x, 5.5.x, and 5.6.x. We can't help it if you're hitting a bug in php itself.

**Comment by stevenmyhre** [comment]
Good call, thanks for the feedback/help.  Now to talk everyone into upgrading all our servers...
