### ISSUE TITLE
@ (at sign) breaks causes errors in strings

### ISSUE THREAD

**Issue by merlinpatt** [laravel/framework#8274]
I have the below code in my app. The problem is the @ (at sign). When it's there, I get syntax highlighting and errors as if the string doesn't end. When remove it, the page works fine (minus the action not existing). I've tried escaping the @ and that doesn't work. I've also tried double quotes, but that doesn't work either. How can I escape @?

I could use the route function and avoid the @ entirely but I feel that the action function is far more clear in terms of what it's doing so I'd rather not use route.

    @extends('layouts.default') <?php
    $url = URL::action('UsersController@index'); ?>
    
    @section('header')
        @include('partials.components.searchHeader', array('title' => "Users", 'results' => $users->getTotal(), 'total' => $total, 'url' => URL::route( 'users.index' ), 'type' => 'user'))
    @stop
    
    <?php
    if(Auth::user()->isAdmin()) $publishedFellows = Fellow::published()->get();
    if(!Auth::user()->isFellow()) $publishedOpportunities = Opportunity::select('opportunities.*')->published()->sortedByCompany()->get(); ?>
    
    @section('content')
        @if(Auth::user()->isAdmin())
            @include('partials.components.add-button', array('url' => '/users/create', 'name' => 'Add User'))
        @endif
        <?php $partialsList = [
            'listItems' => $users,
            'search' => $search,
            'url' => URL::route('users.index'),
            'pills' => $pills,
            'indexView' => 'users.single',
            'type' => 'user',
            'total' => $total,
        ]; ?>
        @include('partials.list')
    @stop

**Comment by TheShiftExchange** [comment]
You've already asked this question on Stackoverflow: http://stackoverflow.com/q/29450708/1317935

I posted an answer there.

Please dont post support questions here.
