### ISSUE TITLE
How do I use phpiredis with Laravel?

### ISSUE THREAD

**Issue by dhardtke** [laravel/framework#8276]
Hey,

found nothing in the Docs, but I want to use https://github.com/nrk/phpiredis to increase the Performance of phpredis.

I know that https://github.com/nrk/predis/blob/master/src/Connection/PhpiredisSocketConnection.php exists, but I don't know how and where Laravel initializes its Predis connection.

Thanks.

**Comment by GrahamCampbell** [comment]
Ask on the forums.

**Comment by dhardtke** [comment]
Alright, here we go again - you closing issues quite fast.
No PR from me regarding the Docs then.

**Comment by GrahamCampbell** [comment]
That's fine. This question belongs on the forums. Either I close it now, or I close it in 2 week's time after it has exactly 0 comments on it.
