### ISSUE TITLE
New IDEA: Automation of adding service providers to app.php

### ISSUE THREAD

**Issue by vignesh0025** [laravel/framework#8280]
Hello, Right now when a composer package is added, we have to look at its `documentation` and add the corresponding ``ServiceProvider`` and ``Facets`` in ``app.php``. 

Why can't it be `automated` by using an `another command` , which will be executed right after we run `composer update` . I have experience in laravel, still then i am new in PHP. Otherwise i would have implemented and give a pull request.

The command will just read the laravel.json file (for eg.), belonging to each and every package and add the data into app.php if it does'nt exist.

**Comment by GrahamCampbell** [comment]
There is already a package that does this. This was discussed then, and it's not getting into the laravel core.

**Comment by vignesh0025** [comment]
Someone came into my dream and stole my idea. :-) Thanks. Whats the name of the package anyway?
