### ISSUE TITLE
cron job on laravel homestead

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#8281]
It appears that cron jobs aren't automatically configured on homestead.

I created an artisan command that is meant to run every 5 minutes but it doesn't do anything.
When I call the command in the terminal, it works.

**Comment by pjebs** [comment]
How can I make it work?

**Comment by pjebs** [comment]
I had to manually edit crontab:

1) crontab -e
2)Then add * * * * * php /path/to/artisan schedule:run

This made it work.

Why is it not automatically configured???

**Comment by crynobone** [comment]
Does homestead documentation said anything about automatically configuring cron jobs?

**Comment by pjebs** [comment]
No - but it's implied because the standard laravel setup has everything set up to run a cron job:
a) The Kernal file has the inspire artisan command set up to run every hour.

Homestead should honour what laravel has automatically set up. I don't even see a downside for Homestead not automatically having the cron job set up. Laravel 'boasts' how cron jobs can be all configured internally from within the framework: http://laravel.com/docs/master/artisan#scheduling-artisan-commands

Plus it is super easy for homestead to have it automatically configured.

Besides the possibly of Taylor making a mistake in his reasoning OR not thinking about the issue at all, I can only think of one rational reason why Taylor has not done this.

He wants Homestead to mirror Forge. In Forge, you have to manually configure the cron job.
In Forge, they don't necessarily encourage  you to run "schedule:run" and let the framework take care of all the cron jobs internally. The documentation and Laracast videos highlight that you can bypass "schedule:run" and manually decide which artisan command jobs you want done from outside the framework.

**Comment by crynobone** [comment]
> He wants Homestead to mirror Forge. In Forge, you have to manually configure the cron job.

In Forge, you still have to manually configure it, since Forge and Homestead is not ONLY for Laravel 5, Laravel 4 does not have `schedule:run` by default and for sure non Laravel app doesn't have `artisan` command to begin with.

> Plus it is super easy for homestead to have it automatically configured.

Both https://github.com/laravel/homestead and https://github.com/laravel/settler are open source. It would be super easy to submit Pull Request to add this feature.

**Comment by pjebs** [comment]
I'm not talking about Forge automatically having the cron job set up, for the reasons you state. I'm only talking about Homestead having it set up - at least if it detects L5.

I'll look into doing a pull-request once I learn how to understand what is going on in those scripts.

**Comment by TheShiftExchange** [comment]
Can I ask - why are you even running cron jobs on homestead? Its designed for development?

**Comment by taiyaei** [comment]
If you're doing development then it'd be reasonable to mimic production as much as possible, not an unreasonable want imo.

**Comment by TheShiftExchange** [comment]
But why run "crons"?

You just run the commands individually to test them - no need to *schedule* them to run at certain times.

It doesnt make sense in a development environment.

**Comment by taiyaei** [comment]
I personally would do that, yes, but I think that giving people options is also good, e.g. multiple ways to set up your routes, validate requests, setup your middleware, etc.

In any case, not worth arguing about, issue should probably be closed and if someone wants to PR it over at laravel/homestead or laravel/settler (not sure which this would go under honestly, haven't looked into either of them much, hopefully someone can help there) then they can

**Comment by GrahamCampbell** [comment]
This belongs on the forums.

**Comment by dbashyal** [comment]
As a brand new homestead user, I would love to see this feature included. It would be awesome if I can define in Homestead.yaml.

FYI this issue comes on top of google search for this feature.

**Comment by haoxi911** [comment]
Adding to Homestead.yaml might be the best option. I feel this feature should be off by default but can be easily enabled via an additional option in Homestead.yaml.

However.. having Homestead managing crontab may lead to other issues, since developers might use crontab for other requirements as well, it should make sure that the changes won't override those customized fields.

**Comment by matthias-influry** [comment]
Just for others coming from Google:
I had to add `schedule: true`  within `sites` of `Homestead.yaml` (see https://laravel.com/docs/5.7/homestead#configuring-cron-schedules) 
Then, after `vagrant halt` and `vagrant up --provision` it went into effect.
