### ISSUE TITLE
setPasswordAttribute conflicts with password reset process

### ISSUE THREAD

**Issue by olimorris** [laravel/framework#8287]
I've noticed that specifying the setPasswordAttribute in my App\User model prevents me from using the password reset feature that comes with L5. I set the attribute like so:

```
public function setPasswordAttribute($password)
{
    $this->attributes['password'] = Hash::make($password);
}
```

I believe that in the reset process it hashes the hashed password. In terms of why I bother with the attribute, well it's quite useful in my PHPUnit integration tests and also means I don't have to think about hashing as it's automatically taken care of in the model.

For information, I'm largely using the standard user eloquent model except for a few custom relationships.

**Comment by JosephSilber** [comment]
Yeah. I also use this, and have run in to the same issue.

Before Laravel 5 was released, I wanted to change.

Taylor didn't like it for some reason :cry: 

For reference: #7211 and laravel/laravel#3236

**Comment by olimorris** [comment]
I'm surprised because it's a genuine issue which had me stumped for a while. There's probably a lot of users out there who are blissfully unaware their password reset function in L5 doesn't work. At the least I hope this is documented behaviour.

**Comment by alexsoft** [comment]
@JosephSilber @olimorris You can override postReset method in PasswordController and while reseting password do it without hashing.
But I think we need to extract this callback to another method so we can override only callback function.

**Comment by alexsoft** [comment]
@JosephSilber @olimorris My PR #8664 with extraction that callback to a method was merged into master branch. Will be in 5.1
