### ISSUE TITLE
Console Kernel is booting twice

### ISSUE THREAD

**Issue by daftspunk** [laravel/framework#8289]
Please refer to my comments here: https://github.com/laravel/framework/commit/6a9aa29278e13274549d8205f2b21a2d2cb70e98

- Requires a second opinion / peer confirmation
- Unsure if this is an intended outcome

I should also note, the load order is the following:

1. Bootstrap Kernel
1. Load providers
1. Bootstrap Kernel

So if the Kernel loads something in to IoC and a provider wants to change the instance, it gets wiped out on the second Kernel load.

**Comment by GrahamCampbell** [comment]
Thank you for reporting. We'll look into this soon.

**Comment by petercoles** [comment]
I'm also seeing an odd behaviour that might be related to this. Commands that access the databases other than the default and which run perfectly from the command line, seem to lose the database credentials when executed by the Artisan scheduler.

A simple use case would be a command containing nothing other than a handler that does nothing other than \DB::connection('non-default conn');

This throws a PDO exception, namely:
PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'apache'@'xxxxxx.com' (using password: NO)' in /home/www/xxxxxx.com/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47

**Comment by GrahamCampbell** [comment]
Can anyone send a pull to fix this please?

**Comment by daftspunk** [comment]
My pull would be to revert this breaking change. I have tried to find the answer but am unsure why it occurs. I'm also unsure why the change was needed in the first place so can't figure out an alternative solution. Can anyone shed some light on why we need to define the schedule after booting app? I think the answer exists in the mind of @taylorotwell

**Comment by taylorotwell** [comment]
Otherwise you can't pull something from the database to define the schedule
etc.

**Comment by taylorotwell** [comment]
But I can see why it boots twice. In foundation application bootstrapWith
the bootstrapped indicator is set after bootstrapping instead of before.

**Comment by daftspunk** [comment]
Fixed by 125809bc364159773c09e5f480cff7f29a89fdea

Thank-you Mr O! =)
