### ISSUE TITLE
artisan route:list no longer works without a database connection

### ISSUE THREAD

**Issue by jmakenney** [laravel/framework#8297]
Since 7233adaf20dde806db8cc4691a46a6312d2010c5 `artisan route:list` requires a database connection if any controller's constructor requires a database connection for any reason (e.g. dependency injection of PasswordBroker in the default PasswordController).

In many applications, especially those which introduce multi-tenancy, having a default database set either does not make sense or is not desirable.

Is it possible for there to be either an option to disable controller instantiation on `route:list`, or a graceful failure with a list of controllers that were unable to be instantiated?

**Comment by amt925** [comment]
This is an issue for a project I am working on with multi-tenancy. We have the default DB connection config value to null and set it in a service provider. 

As @jmakenney suggested a soft fail/warning would be nice.

**Comment by GrahamCampbell** [comment]
This is not a bug, but the expected result. On a default laravel application, this is caused by loading dependencies for middleware I assume.
