### ISSUE TITLE
hasManyThrough Related question?

### ISSUE THREAD

**Issue by Talean-dev** [laravel/framework#8298]
Exist method class:
```
class Users extends Model
{
    protected $table = 't_users';

    public function metas()
    {
        return $this->hasManyThrough('App\Models\UsersMeta', 'App\Models\DUsersMeta', 'id_user', 'id_meta');
    }
}
```

App\Models\UsersMeta - Table: t_users_meta
App\Models\DUsersMeta - Table: d_users_meta

DataBase Structure:
![vderkgc](https://cloud.githubusercontent.com/assets/8143119/7005973/f5be2236-dc85-11e4-9e36-15e89097124f.png)

Users::meta->toSql() generate sql:
select * from `t_users_meta` inner join `d_users_meta` on `d_users_meta`.`id` = `t_users_meta`.`id_meta` where `d_users_meta`.`id_user` = ?

???  `d_users_meta`.`id_user` = ?
maybe it should be?
`t_users_meta`.`id_user` ?

**Comment by taiyaei** [comment]
Please post on the forums with more information. Laravel issues is not for support tickets

**Comment by Talean-dev** [comment]
ok. sorry!

**Comment by Talean-dev** [comment]
just wanted to ask casually is not a mistake ?? if the error is possible to consider as Bug

**Comment by GrahamCampbell** [comment]
@taiyaei If this is a bug, then it's fine here. Please do not tell people where to post. Taylor and I do that.

**Comment by jarektkaczyk** [comment]
It's `belongsToMany` not `hasManyThrough` relation, that's all. `hasManyThrough` won't work for `hasMany - belongsTo` chain.

**Comment by Talean-dev** [comment]
Thanks. Sorry!
