### ISSUE TITLE
Translation override issues

### ISSUE THREAD

**Issue by sixfootsixdesigns** [laravel/framework#8302]
In `Illuminate\Translation\FileLoader` the method `loadNamespaceOverrides` is setting an incorrect file path. 

For packages, I setup my language folder structure the same as the main laravel app does ie: 
```
- package
    - src
        - resources
            - lang
                - en
                    buttons.php
                - fr
                    buttons.php
```
When I publish my package, the file path defined in the `loadNamespaceOverrides` method doesn't find the language files.

If the path is changed to the following everything works as expected and is also similar to how package views are overriden.:
```
$file = "{$this->path}/vendor/{$namespace}/{$locale}/{$group}.php";
```

In my package Service Provider I have my publish command for languages as follows:
```
$this->publishes([__DIR__ . '/resources/lang/' => base_path('resources/lang/vendor/myPackage')], 'lang');
```
I'm also calling the `loadTranslationsFrom` method in my package Service Provider as follows:
```
$this->loadTranslationsFrom(__DIR__.'/resources/lang', 'myPackage');
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting. We're open to pull requests if you have any time. :)
