### ISSUE TITLE
Issue with L4 & L5 apps hosted on the same server

### ISSUE THREAD

**Issue by sureshbala** [laravel/framework#8303]
I have two Laravel 4.2 apps and three Laravel 5.0 apps on DigitalOcean droplet(Ubuntu 14.04). Everything was going quite good since the last one year. After a recent server upgrade, both the Laravel 4.2 apps started throwing the below mentioned error while all the three Laravel 5 apps continue to work as usual. 

'Class Illuminate\Contracts\Debug\ExceptionHandler does not exist'

![Error Image]
(http://i.imgur.com/6Itwoe6.png)

Also, upon refreshing the page quite a number of times it works but then the success rate is hardly 10%. 

And strangely all the Laravel 4.2 apps works quite well in the local server.

I have already done the following but the problem persists.

1. Removed all the third party plugins
2. Cleared the Cache
3. Removed the vendor folder and have run composer update

**Comment by BoXHocK** [comment]
I have the same issue. Here's my forum thread with all the things I've tried to fix it.
http://laravel.io/forum/04-06-2015-laravel-suddenly-stops-working

**Comment by GrahamCampbell** [comment]
Can't replicate. Ask on the forums.

**Comment by BoXHocK** [comment]
Forums told to open issue. Where's our god now

**Comment by GrahamCampbell** [comment]
It's not for them to decide.

**Comment by sureshbala** [comment]
That's ok. But, we are now orphaned :worried:

**Comment by RemiCollin** [comment]
Suggested to open issue to have a larger visibility as there may been more user involved. We don't know what's the origin of this bug may be. Production application are involved. Can you please keep this open for informational purpose as more users may be experiencing this issue?

**Comment by sureshbala** [comment]
I side with RemiCollin. For sure, this is an issue with Production environment and something that crept in quite recently. Please keep this open at least for the time being.

**Comment by RemiCollin** [comment]
Just quoting laravel contribution guidelines :

'Remember, bug reports are created in the hope that others with the same problem will be able to collaborate with you on solving it. Do not expect that the bug report will automatically see any activity or that others will jump to fix it. Creating a bug report serves to help yourself and others start on the path of fixing the problem.'

If we can't use the github issue as a collaborative way of helping each other, please state it more clearly.

Regards.

**Comment by sureshbala** [comment]
GrahamCampbell, please keep this open :cry:

**Comment by BoXHocK** [comment]
Yes, please. Recently, several people are having the same issue. All of them get the same error when using L4 and L5 apps on same server.

**Comment by jjrdev** [comment]
Also having this issue with L4 sites breaking when L4 and L5 sites are hosted on the same server. moving the L5 site to another server is the only solution that worked for me

**Comment by jedkirby** [comment]
I'm also having this issue, but only whilst having the `New Relic PHP Agent Installation` installed on my droplet. Do any of you have this agent installed also?

**Comment by BoXHocK** [comment]
Yes I actually do. Haven't tried disabling that. Have you?

**Comment by jedkirby** [comment]
Yep @BoXHocK, disabling it and restarting php fixes the issue for me at least.

**Comment by BoXHocK** [comment]
Thank you so much @jedkirby, you made my day! Works perfectly now. I will update my thread on the forum now.

**Comment by jedkirby** [comment]
No probs @BoXHocK. I'm opening a ticket with New Relic as we speak, i'll keep this post updated.

**Comment by jjrdev** [comment]
Ahh yes i also have the new relic php agent! - well done that man!

**Comment by sureshbala** [comment]
Same here. Got rid of New Relic and everything work fine. Thanks @jedkirby & @BoXHocK

**Comment by jcalonso** [comment]
I'm having the same issue, waiting to hear back from NewRelic

**Comment by mabasic** [comment]
Omg, this saved me a lot of time figuring it out.

**Comment by barryvdh** [comment]
Perhaps because of the 4.20.x release, which supports Laravel 5? https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes

**Comment by rvanderwal-newrelic** [comment]
Thanks for the input! The New Relic PHP Agent team is currently addressing this issue. If you're running both Laravel 4 and Laravel 5 on the same host, our support team is recommending that you roll back to the 4.19 version of the agent for now. Also, file a support ticket with New Relic to make sure you're notified when we publish the fix.

**Comment by rvanderwal-newrelic** [comment]
I'm pleased to announce that the New Relic PHP Agent Team has just released a new version of the agent that contains a fix for this issue. Thanks for your patience, and let us know if you have any other feedback.

**Comment by jcalonso** [comment]
Thanks, it works now!

**Comment by jedkirby** [comment]
Thanks @rvanderwal-newrelic, works perfectly.

**Comment by jcalonso** [comment]
The error is still present for me, it worked for some minutes, probably because php-fpm was restarted, but now is happening again, anyone experiencing the same?

**Comment by barryvdh** [comment]
Just to be clear, you did update the newrelic php agent to 4.20.2.95?

**Comment by jcalonso** [comment]
Yes:

```
jcalonso@digitalocean:~$ dpkg -s newrelic-php5
Package: newrelic-php5
Status: install ok installed
Priority: optional
Section: non-free
Installed-Size: 10328
Maintainer: New Relic <support@newrelic.com>
Architecture: amd64
Version: 4.20.2.95
Depends: libc6 (>= 2.3.2), debconf (>= 0.5) | debconf-2.0, coreutils, debconf, python
Pre-Depends: newrelic-php5-common (= 4.20.2.95), newrelic-daemon (= 4.20.2.95)
Description: The New Relic agent for PHP
 The actual New Relic PHP agent. This depends on the newrelic-php5-common
 package for its installation script and support files.
Homepage: http://www.newrelic.com/
```

**Comment by jcalonso** [comment]
I restarted php-fpm again now everything seems good, probably was my mistake, thanks!

**Comment by tallcoder** [comment]
I'm having the same problem. I have to restart php5-fpm about every 45 minutes to fix this. I have L5 projects and L4 projects on same DigitalOcean box. Is there any progress with this yet???
