### ISSUE TITLE
Eloquent Collections causing FatalErrorException when using fetch() & unique() together

### ISSUE THREAD

**Issue by alibo** [laravel/framework#8327]
Hi,

I have a problem with using `fetch()` & `unique()` together.
That's because `\Illuminate\Database\Eloquent\Collection::unique()` overrides `\Illuminate\Support\Collection::unique()` with different implementation.

~~~php
$user = User::find(1);
$posts = $user->posts;

$uniqueTitles = $posts->fetch('title')->unique();
~~~

It causes a `FatalErrorException`:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to a member function getKey() on string
```
```
…/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Collection.php:237
```

Is that an issue?

Thanks :)

**Comment by JosephSilber** [comment]
`fetch` serializes the model into an array. If you then want to run `unique` on them, you should use the base collection:

```php
$uniqueTitles = $posts->fetch('title')->toBase()->unique();
```

**Comment by alibo** [comment]
Thanks:)
