### ISSUE TITLE
Misleading function of App::resolved() callback

### ISSUE THREAD

**Issue by neon64** [laravel/framework#8332]
While working on a Laravel application, I noticed that one of my callbacks set up using `App::resolving()` was never being called. It turns out, that because the service was already resolved, the callback never fired.

I easily fixed the issue with a bit of extra hackery:

        $function = function($entities) {
            // do something
        };
        if($this->app->resolved('My\Service')) {
            $function($this->app['My\Service']);
        } else {
            $this->app->resolving('My\Service', $function);
        }

But I was wondering whether this is really the intended behaviour.

I would propose a simple check at the start of the `Container::resolving` method that calls the callback immediately if it has already been resolved:

    if($this->resolved($abstract)) {
        $callback($this[$abstract]);
    }

I'm using Laravel 4 at the moment, but through looking the 5's source code I can see that this hasn't changed.

PS:

Just a background on my use of `App::resolved`. I was injecting a Validation listener into Doctrine's events system (yes sorry I'm not a loyal Eloquent fan) only after Doctrine was resolved. However due to this bug my validation system was never injected and thus all requests went unvalidated (horror!).

**Comment by GrahamCampbell** [comment]
I think this is intended. I assume the class was originally resolved before you registered the listener?
