### ISSUE TITLE
Handling missing routes in Laravel 

### ISSUE THREAD

**Issue by kishanj918** [laravel/framework#8337]
I have added the following code in my Handler.php file to handle missing routes.
```
	public function render($request, Exception $e)
	{
		if($e instanceof \Symfony\Component\HttpKernel\Exception\NotFoundHttpException)
                   {
                       return Response::make(view('index'));
                   }
           return parent::render($request, $e);
	}
```
But it's giving me an error .. I have attached a screen shot.. any guesses?
![screenshot 10](https://cloud.githubusercontent.com/assets/3994657/7042014/1ba7f8d8-ddfc-11e4-93c5-a171fd1e8bd5.png)

**Comment by phanan** [comment]
Or you can just add a `resources/views/errors/404.blade.php` file...?

**Comment by GrahamCampbell** [comment]
Ask on the forums please.

**Comment by kishanj918** [comment]
I want to redirect all the missing routes to index view so that further angular'll handle the routing.

**Comment by kishanj918** [comment]
@GrahamCampbell  okay.
