### ISSUE TITLE
[Redis] `Cache:has()` always returns `true`, even if key doesn't exist.

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#8340]
`RedisStore` needs it's own `has()` method. The inherited `has()` method is checking if the returned cache key is `null`, but Predis and PECL Redis return `false` if the key does't exist, not `null`

**Comment by CurosMJ** [comment]
Aren't there any unit tests for this?

**Comment by GrahamCampbell** [comment]
Don't think there are. I think we have some for array cache only.

**Comment by tillkruss** [comment]
Homestead PECL get returns null, but on Heroku PECL returns false.

**Comment by CurosMJ** [comment]
Strange, but I am using `Predis` and it works fine. @tillkruss

**Comment by tillkruss** [comment]
I'm using the PECL extensions and it works fine on Homestead, but not on Heroku, because for some reasons `Cache::get()` returns false if the keys doesn't exist.

**Comment by CurosMJ** [comment]
I've seen the `Illuminate\Cache\Repository`. It depends on the `$store->get()` method to find out if key exists or not. If `$store->get()` equals `null`, then only the `Cache::has()` method will return false.

PECL Redis documentation says that the value will either be a string or a boolean:
https://github.com/phpredis/phpredis#get

Homestead and Heroku must be using something different.

**Comment by FractalizeR** [comment]
But Laravel uses https://github.com/nrk/predis internally, which returns null for inexisting keys. Or not?

**Comment by tillkruss** [comment]
https://gist.github.com/tillkruss/27eda66e77280f1ba727
