### ISSUE TITLE
[5.0] Wrong bindings order with 'having' inside whereHas

### ISSUE THREAD

**Issue by silwerclaw** [laravel/framework#8341]
```php
$res = \SomeModel::where('param1', 'value1')
->whereHas('table2', function($query) {
            $query->having('subParam1', '>', 'subValue');
        })
->where('param2', 'value2')->get();
```
And Laravel creates 

```mysql
select * from `table1` where `param1` = 'value1' and (select count(*) from `table2` where `table2`.`table2_id` = `table1`.`id` and `table2`.`deleted_at` is null having `subParam` > 'value2') >= 1 and `param2` = 'subValue'
```

So in general it took WHERE bindings and set second WHERE binding to HAVING inside subquery. And HAVING binding goes last, where param2 must be. As I digg inside the code it always make `array_flatten` for bindings and HAVING bindings always go after WHERE bindings, but not in that case where HAVING is inside relation subquery. So my bindings are just mixed in wrong order that is not very expected behaviour.

**Comment by GrahamCampbell** [comment]
What laravel version.

**Comment by silwerclaw** [comment]
4.2.17

**Comment by GrahamCampbell** [comment]
4.2 is not supported

**Comment by silwerclaw** [comment]
I've installed latest version (5.0.27)

The same issue reproduces - bindings are also inserted in the wrong order into query with relation subquery

**Comment by GrahamCampbell** [comment]
Is this still present on 5.1 and 5.2?

**Comment by GrahamCampbell** [comment]
Ping @silwerclaw.

**Comment by silwerclaw** [comment]
Yes, this issue is still present in laravel 5.1.7. Generated query:

```
select * from `table1` where `id` = 'param1' and (select count(*) from `relation_table` where `relation_table`.`id` = `table1`.`id` having `id` > 'param3') >= 1 and `id` = 'param2'
		
```

**Comment by GrahamCampbell** [comment]
What about the latest 5.1.x version?

**Comment by GrahamCampbell** [comment]
Or the latest 5.2.x?

**Comment by acasar** [comment]
@silwerclaw Try with the latest 5.1. This was already fixed a while ago: https://github.com/laravel/framework/pull/10548
