### ISSUE TITLE
[4.2] Blade: @foreach($things as $thing) giving "Undefined variable: $thing"

### ISSUE THREAD

**Issue by dandart** [laravel/framework#8344]
Hi,

The following code breaks based on $thing not being defined:

$things = Thing::all(); // an eloquent model

        Mail::send(
            [
                'emails.emailhtml',
                'emails.emailtext'
            ],
            [
                'things' => $things
            ],
            function($message) {
                $message->to('me@me.com','Me')
                        ->subject('All of your things')
                        ->from('me@me.com', 'Me');
            }
        );

Contents of view:

@foreach($things as $thing)
{{{ $thing->data }}}
@endforeach

Anyone know what might be up with that? I think it's a bug. On the other hand I could be being a pillock.

Cheers

**Comment by GrahamCampbell** [comment]
4.2 isn't supported, though you are very free to ask on the forums.

**Comment by dandart** [comment]
Aha! I missed the release of 5... fair enough!
