### ISSUE TITLE
Random TokenMismatchExceptions

### ISSUE THREAD

**Issue by Naxiz** [laravel/framework#8345]
I get random TokenMismatchExceptions. I'm using laravel/framework v5.0.27.

The code needed to reproduce this is very minimal, I've created a test case here (steps to reproduce: just keep clicking `Submit`, I get the exception almost instantly the first 2 times I tried):
Naxiz/L5-CSRF-TestCase@74d8222551cd0383c5887b108967b634c7af3b15

I've no idea what's causing this. The `$request->session()->token()` randomly changes to another string on validation, but is set back to the original string on the next request.

The same token is always sent to the server, so when the exception is thrown, simply hitting F5 and resubmitting the form data usually passes the CSRF validation the second time.

I get this problem using `php artisan serve` on my local machine, but also on my server using nginx and PHP 5.6.7.

**Comment by GrahamCampbell** [comment]
Dupe of https://github.com/laravel/framework/issues/8172.
