### ISSUE TITLE
Specify current page for Paginator when Model::paginate

### ISSUE THREAD

**Issue by elpd** [laravel/framework#8347]
Is there a way to specify for a Paginator the currrent page requested specificaly ?
Something like:

    $users = User::paginate($rowsPerPage, $currentPageNum);

I have found that the Eloquent\Builder take the page number from the "global" function the PaginationServiceProvider is setting. 

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Builder.php#L246
```
public function paginate($perPage = null, $columns = ['*'])
	{
		$total = $this->query->getCountForPagination();

		$this->query->forPage(
			$page = Paginator::resolveCurrentPage(),
			$perPage = $perPage ?: $this->model->getPerPage()
		);

		return new LengthAwarePaginator($this->get($columns), $total, $perPage, $page, [
			'path' => Paginator::resolveCurrentPath()
		]);
	}
```

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Pagination/PaginationServiceProvider.php
```
public function register()
	{
		Paginator::currentPathResolver(function()
		{
			return $this->app['request']->url();
		});

		Paginator::currentPageResolver(function()
		{
			return $this->app['request']->input('page');
		});
	}
```

Is there something less global I can set ?

**Comment by GrahamCampbell** [comment]
Unfortunately not, sorry.

**Comment by Sladewill** [comment]
He could do it a hacky way and override the input Input::merge then change the page that way.
