### ISSUE TITLE
301 Form L5

### ISSUE THREAD

**Issue by sciasfreelancer** [laravel/framework#8352]
Hello.

Am getting some strange things in laravel like redirecting. No Idea why..
http://prntscr.com/6rk3re
I open form like this:
{!! Form::open(array('action'=>'Home@indexPost')) !!}
... my content ...
{!! Form::close() !!}

But it's giving me 301 redirect.

Routes.php

Route::get('/', 'Home@index');
Route::post('/', 'Home@indexPost');

If I make like this:

Route::get('/', 'Home@index');
Route::post('/post', 'Home@indexPost');

it works, but why does it not work o same slash ?

**Comment by GrahamCampbell** [comment]
You can't have a slash before post.

**Comment by GrahamCampbell** [comment]
Also, L5 doesn't have a form component anymore.
