### ISSUE TITLE
Configure the nginx server of homestead to dynamically match host names to folders

### ISSUE THREAD

**Issue by Evertt** [laravel/framework#8359]
So one of the many things that still costs me time, unnecessarily, is adding hosts when I begin a new project. First I need to add the host to my hosts files and then reconfigure homestead / vagrant to map the host name to the right folder. It's always a bit of a hassle.

Now with the help of dnsmasq I'm redirecting every url that ends in `.dev` to homestead. And now after some trial and error with configuring nginx I was able to also dynamically match every host to a folder with the same name. So when I now go to `http://foo.dev` in my browser, it will redirect to homestead which will try to use `~/Server/foo/public/` as my documents root and if that doesn't exist then it will try `~/Server/foo/` as my documents root. Awesome for me, but it still took me a bit of time and energy to get this to work.

Wouldn't it be cool if we could configure this in our homestead.yaml file with a simple bit of regex? Like so:

    sites:
        - map: (.+)\.dev
          to: /home/vagrant/Server/$1
        - map: (.+)\.laradev
          to: /home/vagrant/Server/$1/public

Of course it's hard to make this super powerful, but just this simple configuration (in combination with dnsmasq) could save developers a lot of time. What do you guys think?

**edit** and of course then while we're at it, it would be very helpful to write a little article on setting up dnsmasq in the laravel documentation.

**Comment by franzliedke** [comment]
Great idea. This would make Homestead even more awesome.
Am 09.04.2015 18:39 schrieb "Evertt" <notifications@github.com>:

**Comment by TheShiftExchange** [comment]
p.s. you shouldnt be using `.dev` for your virtual TLD extensions. `.dev` is now a valid TLD - so you risk causing some issues.

Personally I use `.vm` which will never become a valid TLD (unless a new country is formed).

**Comment by yajra** [comment]
@Evertt  You can use [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) to update your host. Just loop on the sites and add the host. P.S. credits to original author (forgot where I got the snippet)

on `Vagrantfile` update this line to:
```ruby
Homestead.configure(config, YAML::load(File.read(homesteadYamlPath)), Vagrant.has_plugin?('vagrant-hostsupdater'))
```

On `homestead.rb`:
```ruby
class Homestead
  def Homestead.configure(config, settings, hostsupdater)
  
.....

    # Add the aliases to the host machine
    if hostsupdater
      aliases = Array.new
      settings["sites"].each do |site|
        aliases.push(site["map"])
      end
      config.hostsupdater.aliases = aliases
    end
```
