### ISSUE TITLE
response()->download() FatalErrorException

### ISSUE THREAD

**Issue by angelomaragna** [laravel/framework#8363]
after this commit: https://github.com/laravel/framework/commit/21283ca25f70e0aac39d30f13dd0d349a363ebd3#diff-d0cc9b4968f529aa95cffc7ec370273f

I think a problem raised.
When using response()->download($someFileName)
response() can return \Symfony\Component\HttpFoundation\Response that does not have withCookies method.

I discovered it becasue after composer update in my application raised

FatalErrorException in AddQueuedCookiesToResponse.php line 38:

Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::withCookies()

**Comment by taylorotwell** [comment]
Reverted.
