### ISSUE TITLE
[L5] feature request: a version of eloquent using the Data Mapper pattern

### ISSUE THREAD

**Issue by Evertt** [laravel/framework#8369]
I love eloquent and how intuitive it is. I love how I can access attributes using `$person->name` without ever having to configure or define that and the same for relations of models. What I don't like as much about Eloquent is that it uses the Active Record pattern. This encourages to mix all kinds of different logic together into the model, like business logic and persistence logic, which eventually makes everybody's code messier.

Of course one can choose to use the Repository pattern to tackle this, which I'm doing right now, but wouldn't it be nicer if the laravel framework encouraged separation of those different kinds of logic out of the box? I also know Doctrine 2 is an option, but the argument still stands. And besides, Doctrine 2 isn't as beautifully simple as Eloquent, so I trust that if you guys would want to do this, you'd be able to make something beautiful.

I'd love to hear what everybody thinks about this.

**Comment by jarektkaczyk** [comment]
https://github.com/analogueorm/analogue

**Comment by GrahamCampbell** [comment]
I think this has come up before. Note, just because I've closed this issue, it absolutely doesn't mean people can't continue to comment on it. :)
