### ISSUE TITLE
Wrong expected return value from Illuminate\Contracts\Auth\Registrar::create

### ISSUE THREAD

**Issue by fungku** [laravel/framework#8370]
The expected [return value](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Contracts/Auth/Registrar.php#L17) is currently `Illuminate\Contracts\Auth\User`, which doesn't exist.

e.g.

https://scrutinizer-ci.com/g/SevenShores/Kraken/issues/master/files/app/Services/Registrar.php?orderField=path&order=asc

**Comment by GrahamCampbell** [comment]
Nice catch. It's meant to be `Illuminate\Contracts\Auth\Authenticatable`. I'll get this sorted.
