### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by brendler** [laravel/framework#8379]
In an attempt to perform a fresh installation I'm having the problem below.
When I try to remove I get the same error. Trying to use "laravel new *" results in the same problem.

$ composer create-project laravel/laravel test-laravel-5-project --prefer-dist 
Installing laravel/laravel (v5.0.22)
  - Installing laravel/laravel (v5.0.22)
    Loading from cache

Created project in test-laravel-5-project
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing jakub-onderka/php-console-color (0.1)
    Loading from cache

  - Installing vlucas/phpdotenv (v1.1.0)
    Loading from cache

  - Installing symfony/var-dumper (v2.6.4)
    Loading from cache

  - Installing symfony/translation (v2.6.4)
    Loading from cache

  - Installing symfony/security-core (v2.6.4)
    Loading from cache

  - Installing symfony/routing (v2.6.4)
    Loading from cache

  - Installing symfony/process (v2.6.4)
    Loading from cache

  - Installing symfony/http-foundation (v2.6.4)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.4)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/debug (v2.6.4)
    Loading from cache

  - Installing symfony/http-kernel (v2.6.4)
    Loading from cache

  - Installing symfony/finder (v2.6.4)
    Loading from cache

  - Installing symfony/console (v2.6.4)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.3.1)
    Loading from cache

  - Installing nikic/php-parser (v1.1.0)
    Loading from cache

  - Installing jakub-onderka/php-console-highlighter (v0.3.1)
    Loading from cache

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Loading from cache

  - Installing psy/psysh (v0.4.1)
    Loading from cache

  - Installing nesbot/carbon (1.17.0)
    Loading from cache

  - Installing mtdowling/cron-expression (v1.0.4)
    Loading from cache

  - Installing monolog/monolog (1.13.1)
    Loading from cache

  - Installing league/flysystem (1.0.2)
    Loading from cache

  - Installing jeremeamia/superclosure (2.1.0)
    Loading from cache

  - Installing ircmaxell/password-compat (v1.0.4)
    Loading from cache

  - Installing doctrine/inflector (v1.0.1)
    Loading from cache

  - Installing danielstjules/stringy (1.9.0)
    Loading from cache

  - Installing symfony/filesystem (v2.6.4)
    Loading from cache

  - Installing classpreloader/classpreloader (1.2.0)
    Loading from cache

  - Installing laravel/framework (v5.0.16)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing symfony/yaml (v2.6.4)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.0)
    Loading from cache

  - Installing sebastian/exporter (1.2.0)
    Loading from cache

  - Installing doctrine/instantiator (1.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.3.1)
    Loading from cache

  - Installing phpspec/php-diff (v1.0.2)
    Loading from cache

  - Installing phpspec/phpspec (2.1.1)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.0)
    Loading from cache

  - Installing sebastian/version (1.0.4)
    Loading from cache

  - Installing sebastian/global-state (1.0.0)
    Loading from cache

  - Installing sebastian/environment (1.2.1)
    Loading from cache

  - Installing sebastian/diff (1.2.0)
    Loading from cache

  - Installing sebastian/comparator (1.1.1)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.0)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.0)
    Loading from cache

  - Installing phpunit/php-timer (1.0.5)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.3.4)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.0.15)
    Loading from cache

  - Installing phpunit/phpunit (4.5.0)
    Loading from cache

symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/translation suggests installing symfony/config ()
symfony/security-core suggests installing symfony/expression-language (For using the expression voter)
symfony/security-core suggests installing symfony/validator (For using the user password constraint)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing predis/predis (Allows you to use Predis for caching)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver (~2.4).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.4).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers (~5.0).)
laravel/framework suggests installing iron-io/iron_mq (Required to use the iron queue driver (~1.5).)
laravel/framework suggests installing league/flysystem-aws-s3-v2 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 – Adds Nyan formatters)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
                                                                 
  [ErrorException]                                                
  Undefined property: Illuminate\Queue\QueueManager::$connectors  

Script php artisan clear-compiled handling the post-install-cmd event returned with an error
           
  [RuntimeException]  
  Error Output:       

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

**Comment by GrahamCampbell** [comment]
Why are the dependencies so old? When did you run this?

**Comment by brendler** [comment]
Today, actually. I self updated composer and ran it. Would a composer update fix this?

**Comment by GrahamCampbell** [comment]
And a `composer clear-cache` too.

**Comment by brendler** [comment]
Thanks Graham, it worked flawlessly.

**Comment by GrahamCampbell** [comment]
Great. :)
