### ISSUE TITLE
Artisan: clear-compiled command fails due to unknown method

### ISSUE THREAD

**Issue by Mythos** [laravel/framework#8380]
After running composer update I get this error when artisan tries to run the "clear-compiled" command:
```
[Symfony\Component\Debug\Exception\FatalErrorException]                             
Call to undefined method Illuminate\Foundation\Application::getCachedCompilePath()  
```

**Comment by GrahamCampbell** [comment]
Yes, you need to manually delete the compiled file.

**Comment by GrahamCampbell** [comment]
Or, clear it BEFORE you break it. :)

**Comment by Mythos** [comment]
Ah thanks, deleting ```storage/framework/compiled.php``` fixed that problem. ;-)

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/9678.
