### ISSUE TITLE
bug in ORM relations?

### ISSUE THREAD

**Issue by fragale** [laravel/framework#8382]
Hi Taylor,
how are you?

In Laravel 5.0, I have 2 models, one called 'Employee' and another called 'Family'

both are related as follows:

at 'Employee.php':

	// an Employee can have many families
	public function families()
	{
		return $this->hasMany('Family');
	}

at 'Family.php':

	// a family record belongs to an employee
	public function employee()
	{
		return $this->belongsTo('Employee');
	}

if I run this statement:

$result = Employee::find(27)->families()
            ->where('first_name','LIKE','%A%')
            ->orderBy('id', 'desc')
            ->paginate(100);

Laravel returns all records from the table `familes` where employee_id = 27 and first_name LIKE '%A%', no troubles here.
I put a debug in the database and the ORM is running this sentence in DB:

select * from `families` where `families`.`employee_id` = '27' and `families`.`employee_id` is not null and `first_name` LIKE '%A%' order by `id` desc limit 100

the problem occurs when I run this statement:

$result = Employee::find(27)->families()
            ->where('first_name','LIKE','%A%')
            ->orwhere('last_name','LIKE','%A%') 
            ->orderBy('id', 'desc')
            ->paginate(100);

then the ORM is running this sentence in DB:

select * from `families` where `families`.`employee_id` = '27' and `families`.`employee_id` is not null and `first_name` LIKE '%A%' or `last_name` LIKE '%A%' order by `id` desc limit 100

Laravel then returns a wrong result because it seeks all records in `families` table where employee_id = 27 and first_name LIKE '%A%' or last_name LIKE '%A%'

the last operator OR is in the problem because it makes the first 2 conditions are met "OR" the last condition is true, then it brings all the employee_id including those that are different from 27

what should execute the ORM in the base is:

select * from `families` where `families`.`employee_id` = '27' and `families`.`employee_id` is not null and (`first_name` LIKE '%A%' or `last_name` LIKE '%A%') order by `id` desc limit 100

i.e. using parentheses.

I thik thath it is a bug
your you think?

Regards
MF

**Comment by stuartmccord** [comment]
This is to do with operator precedence in SQL, if you have a where clause:
```
where foo or bar and baz
```
it will produce the same result as 
```
where foo or (bar and baz)
```
what you are wanting to do is this
```
where (foo or bar) and baz
```

If you take a look at the documentation for queries at http://laravel.com/docs/5.0/queries, specifically the section on advanced wheres you should be able to achieve what you need.  It should look something like:

```
$result = Employee::find(27)->families()
->where(function($query) {
    $query->where('first_name','LIKE','%A%')
          ->orwhere('last_name','LIKE','%A%');
})
->orderBy('id', 'desc')
->paginate(100);
```

**Comment by nonDeath** [comment]
Sorry but is ```->orWhere(...``` inside the closure.

**Comment by fragale** [comment]
Stuart,
it work great,
thanks a lot!!!
MF

**Comment by nonDeath** [comment]
¬¬ you don't believe me XD

**Comment by stuartmccord** [comment]
@nonDeath yes, the closure groups whatever is inside it together and puts it into brackets, so it will generate
```
and (first_name LIKE '%A%' or last_name LIKE '%A%') 
```

@fragale no problem, glad I could help
