### ISSUE TITLE
Cannot run npm install, get cache error

### ISSUE THREAD

**Issue by jlem** [laravel/framework#8383]
$ npm install
/
> node-sass@2.1.1 install c:\Websites\Test\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

> node-sass@2.1.1 postinstall c:\Websites\Test\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

`win32-x64-node-0.10` exists; testing
Binary is fine; exiting
npm ERR! EEXIST, open 'C:\Users\Jon\AppData\Roaming\npm-cache\e22f82f0-adable-stream-1-0-33-package-tgz.lock'
File exists: C:\Users\Jon\AppData\Roaming\npm-cache\e22f82f0-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Websites\Credlr
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\Jon\AppData\Roaming\npm-cache\e22f82f0-adable-stream-1-0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0

I get the same error running natively in Windows, as well as trying the same thing in Homestead.

The .lock file that it claims is there, is not actually there.

**Comment by GrahamCampbell** [comment]
Looks like a bug with npm.

**Comment by Ingramz** [comment]
Just got the same error as well with a fresh homestead install. The issue seems to disappear after updating npm to something more recent.
