### ISSUE TITLE
Prefix in RouteServiceProvider is not working ?

### ISSUE THREAD

**Issue by Vocal** [laravel/framework#8393]
HI all. I try add prefix into RouteServiceProvider but it not working. This is in my RouteServiceProvider.php file :

public function map(Router $router) { $router->group(['namespace' => $this->namespace, 'prefix' => 'admin'], function($router) { 
    require app_path('Http/routes.php'); }); 
}
This is in Http\routes.php file :

Route::controllers(['auth' => 'Auth\AuthController', 'password' => 'Auth\PasswordController', ]);
When i access to url : http://cms.dev/admin/auth/login then i get error :

NotFoundHttpException in compiled.php line 7755.
What could possibly cause this error ? 
but if i add directly prefix into routes.php file :

Route::group([ 'prefix' => 'admin'], function() { 
    Route::controllers(['auth' => 'Auth\AuthController', 'password' => 'Auth\PasswordController', ]); 
});
then it working fine. 
i using laravel 5.0.27 
sorry for my english :)

**Comment by crynobone** [comment]
Did you run `php artisan optimize` after adding the prefix?

**Comment by Vocal** [comment]
@crynobone i did run  **php artisan optimize** and it working, thank you very much :)
