### ISSUE TITLE
I want to add the command bus pipes.

### ISSUE THREAD

**Issue by sasakure-kei** [laravel/framework#8405]
I have a question on how to use the Command Bus of Laravel.
ex) register the transaction processing to the pipeline in case of a write operation to the DB.
I want to pipeThrough so as not to affect the subsequent dispatch.
Is there any other way?

**Comment by GrahamCampbell** [comment]
Please ask questions on the forums. :)

**Comment by sasakure-kei** [comment]
Thanks!
