### ISSUE TITLE
Class cache does not exist

### ISSUE THREAD

**Issue by msimkunas** [laravel/framework#8408]
When I try to do something like
```
$cache = $this->app['cache'];
```
in a service provider's `register` method in L4.2, I get the 'Class cache does not exist' ReflectionException.

However, `new \Illuminate\Cache\CacheManager($app)` works. What's the issue here?

**Comment by GrahamCampbell** [comment]
You're going about this wrong. You should not create a new instance manually like you're doing here. You MUST move the code that needs the cache either inside a closure, or into the boot method.

**Comment by msimkunas** [comment]
I *am* doing this inside a closure.

I'm trying to bind a repository class to its implementation and I need to pass the CacheManager to the repo's decorator.

**Comment by GrahamCampbell** [comment]
Looks like you're trying to instantiate this class before laravel has even registered the binding for our cache manager though.

**Comment by GrahamCampbell** [comment]
That is not possible.

**Comment by GrahamCampbell** [comment]
Hence why you're getting this error.

**Comment by msimkunas** [comment]
Why is the cache not yet registered? I put my service provider at the very end of the providers array.

I suppose this means that any code that tries to resolve bindings from the container should be put into the boot method, right?

**Comment by GrahamCampbell** [comment]
Yes. :)

**Comment by msimkunas** [comment]
Thank you for clarifying this.

**Comment by msimkunas** [comment]
My current implementation looks something like this:

```
public function register()
{
  $this->app->bind(
    'Foo\Bar\UserInterface',
    function($app)
    {
        $repo = $app->make('Foo\Bar\Repositories\Eloquent\UserRepository');
        return new UserDecorator(
          new LaravelCache(new \Illuminate\Cache\CacheManager($app));
        );
    }
  );
}
```

As you've said, we should only instantiate the `CacheManager` manually inside a closure or a boot  method. The example above utilises the closure method. Is this what you had in mind?

**Comment by GrahamCampbell** [comment]
> As you've said, we should only instantiate the CacheManager manually inside a closure or a boot method. Is this what you had in mind?

No, never manually make a new instance of our cache manager. Use our container to resolve the instance we provide.

**Comment by msimkunas** [comment]
I've tried moving my code to the boot method, but Laravel complains that the UserRepository interface is not instantiate. What should I do? When exactly are the individual boot methods called?

**Comment by GrahamCampbell** [comment]
I can't replicate this error. You should really continue this on the forums. Here's an example of something similar: https://github.com/StyleCI/StyleCI/blob/master/app/Providers/GitHubServiceProvider.php#L135. Note that I'm not injecting the cache manager itself, I'm just injecting a cache repository. Laravel will get me the default one here. Injecting the cache manager is not "wrong", but it does introduce coupling, but that might not be something you're concerned about. As far as I'm concerned, my code shouldn't care about the internals of selecting the cache driver to use, it just wants a cache repository, and then it's good to go.

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/blob/master/app/GitHub/Repos.php#L49

**Comment by msimkunas** [comment]
When I try to do `$app['cache.store']`, I get 'Class cache.store does not exist'. Suppose I have service providers A, B and C, each with a `register` and `boot` method. When are the boot methods called exactly? After all of the register methods have been called or are those boot methods called separately, after the corresponding register method call?

**Comment by msimkunas** [comment]
Also, why is it wrong to manually instantiate objects like in the above example?
