### ISSUE TITLE
Homestead v2.0.15+ failing with "unknown mount option `actimeo=1'"

### ISSUE THREAD

**Issue by Zirro** [laravel/framework#8410]
Homestead v2.0.15 (and v2.0.16) is failing to complete a boot up of a virtual machine with NFS shared folders on the host I am currently using. The host OS is Windows and it is using a fresh installation of Homestead. The complete error message is:

"Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,actimeo=1 home_vagrant_Code /home/vagrant/Code
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant`,actimeo=1 home_vagrant_Code /home/vagrant/Code

The error output from the last command was:

unknown mount option `actimeo=1'
valid options:
  rw         mount read write (default)
  ro         mount read only
  uid       =<arg> default file owner user id
  gid       =<arg> default file owner group id
  ttl       =<arg> time to live for dentry
  iocharset =<arg> i/o charset (default utf8)
  convertcp =<arg> convert share name from given charset to utf8
  dmode     =<arg> mode of all directories
  fmode     =<arg> mode of all regular files
  umask     =<arg> umask of directories and regular files
  dmask     =<arg> umask of directories
  fmask     =<arg> umask of regular files"

There is some delay before it appears after the message "Mounting shared folders..." and the listing of folders has been shown.

Given the error of "unknown mount option `actimeo=1'", the following commit would seem to be the cause:

https://github.com/laravel/homestead/commit/977ca46b7b7c2fe5893db6b57d56176a5443bc8f

I have reverted my installation to v2.0.14 and confirmed that it is still working as expected.

**Comment by coolhome** [comment]
I can confirm using Windows 8.

**Comment by gpkfr** [comment]
Perhaps you can try using another Solution like https://github.com/gpkfr/GenericVM.
hope this help !

**Comment by HagarKassem** [comment]
Thanks @coolhome, removing  type: "nfs" from Homestead.yaml file solved this issue with me.

**Comment by joelfrens** [comment]
Thanks @coolhome Removing type: "nfs" line completely worked for me. (thumbsup)

**Comment by Pton** [comment]
Another solution for WIndows users running wanting to use nfs in vagrant is installing the [vagrant-winnfsd plugin](https://github.com/winnfsd/vagrant-winnfsd). I've posted my issue and the solution a found in [this stackoverflow post](https://stackoverflow.com/a/54900979/7528944).
