### ISSUE TITLE
Complex where query in a custom Validator using Presence Verifier

### ISSUE THREAD

**Issue by cabloo** [laravel/framework#8418]
I'm writing a validator that verifies that an IP is unique. The complexity is that these are IP ranges, so no IP range can overlap with another. For this I've extended the `Illuminate\Validation\Validator` class and added my `validateUniqueIp` function which is very similar to the `validateUnique` function built into `Validator`.

I'm thinking the key lies in the `$extra` variable, but it seems to only allow `=` relations, not `>`, `<`, etc. After skimming the code I noticed I could use a closure for a subquery here but I don't think I need a subquery, just a simple way of adding my own `->where(...)` to the `$query` object. Obviously I could extend the `PresenceVerifier` but that doesn't sound like the right solution. Ideally, I'd be able to pass a closure to the `getCount` function which receives `$query` and can add extra logic to it.

What would be the recommended solution to this? Thanks in advance.

**Comment by GrahamCampbell** [comment]
Please ask on the forums. We cannot process support requests here.
