### ISSUE TITLE
[L5] Problem with 'Auth' Middleware used in routes after upgrading to 5.0.27

### ISSUE THREAD

**Issue by sureshbala** [laravel/framework#8419]
After an upgrade to 5.0.27, the following error is thrown with all the routes using 'Auth' Middleware. Strangely routes with custom middlewares do not seem to have any issues. 

ErrorException in Route.php line 194:
Undefined offset: 1

![Error Image]
(http://i.imgur.com/n7GOW7o.png)

Couple of users already mentioned the same in laracasts forum.
https://laracasts.com/discuss/channels/general-discussion/laravel-5-middleware-with-route-error-errorexception-in-routephp-undefined-offset-1?page=1

**Comment by crynobone** [comment]
Can you reproduce the bug with a fresh Laravel 5 installation?

**Comment by sureshbala** [comment]
Fresh installs do not have this issue because couple of hours back I have done a fresh install for another project. The problem is only with the upgraded projects. I have upgraded from 5.0.6 to 5.0.27

**Comment by crynobone** [comment]
> The problem is only with the upgraded projects. I have upgraded from 5.0.6 to 5.0.27

Then I don't think it would be easy for anyone to replicate your bug, unless we can replicate your code (which is why it common to ask if it's reproducible on a fresh installation).

**Comment by GrahamCampbell** [comment]
Please ask on the forums. We cannot process support requests here.

**Comment by fkomaralp** [comment]
Bullshet.

**Comment by fkomaralp** [comment]
Use;
`..... ['middleware' => 'auth', 'uses' => 'HomeController@dashboard']);`

**Comment by davidsielert** [comment]
I have this too ! although the documents clearly show (http://laravel.com/docs/5.0/middleware)  closures with middleware it doesn't look like it works

**Comment by taylorotwell** [comment]
@sureshbala can you paste your route declaration that is causing the problem?

**Comment by sureshbala** [comment]
@taylorotwell Here it is 

    Route::get('update-snap', ['middleware'=>'auth', 'as'=>'UpdateSnap', function(){
	  $userSnap = Auth::user()->snap;
	  $data = [
		  'pageTitle'	=>	'Update Snap',
		  'page'		=>	'update-snap',
		  'snap'		=>	$userSnap ? $userSnap : 'user.png'
	  ];
	  return view('update-snap',$data); 
    }]);

**Comment by taylorotwell** [comment]
I can't recreate this on a Laravel installation.

**Comment by sureshbala** [comment]
@taylorotwell Ok. In case if this helps you...I have created a custom middleware ('LoggedIn') by taking the code from the Authenticate Class and when the above route is used with it everything works fine.
