### ISSUE TITLE
Laravel sqlsrv works in tinker mode but not in browser

### ISSUE THREAD

**Issue by sandyandi** [laravel/framework#8426]
I have a Laravel 5 project (on a CentOS 7 machine) that connects to an external MSSQL database.

I followed the setup outlined [here](http://laravel.io/forum/02-08-2014-laravel-linux-to-sql-server-windows?page=1) using FreeTDS.

When I hit the page using a browser I get the error: `SQLSTATE[HY000] Unable to connect: Adaptive Server is unavailable or does not exist (severity 9)`.

But when I use `php artisan tinker` and do something like `App\MyModel::get();`, it returns an `Illuminate\Database\Eloquent\Collection` instance with the records/models just fine.

Anyone knows what's wrong with this?

**Comment by baspeters** [comment]
Did you check the TDS version in the FreeTDS configuration file?

In ```/etc/freetds.conf``` under the ```[global]``` section, there is a setting called ```tds version```. If you haven't already, set it to ```7.0``` or ```8.0```. For some reason the stock FreeTDS version configuration defaults with an archaically low version number.

Also don't forget to restart the webserver, or the dblib connection might not pick up on the updated settings.

**Comment by sandyandi** [comment]
It's not a FreeTDS problem. I checked all in command line. It's a SELinux problem. I managed to fix it by disabling SELinux. Please see [here](http://stackoverflow.com/questions/29640092/laravel-sqlsrv-works-in-tinker-mode-but-not-in-browser).

**Comment by baspeters** [comment]
Ah, the dreaded beast SELinux :)

Anyways, the solution for your problem is to give the webserver permissions to make outgoing connections to the database:

```setsebool -P httpd_can_network_connect_db 1```

The ```-P``` flag makes the rule persistent, otherwise the rule is lost after a reboot.

**Comment by sandyandi** [comment]
Thanks @baspeters! Your solution worked. I enabled SELinux again and ran your command. The site loaded in browser perfectly.

**Comment by QSoto** [comment]
Im experiencing the same issue but on Ubutu Server 17.10 Using Laravel 5.5, Posted solution does not worked with me. Im getting "could not find driver (SQL:  SELECT .....)", it works on Tinker and CLI but not in "browser mode"
**setsebool** is not installed on my server or even avaliable on repositories

Any Solution?

**Comment by fonini** [comment]
@QSoto Check if your web server loaded the database extension too.
