### ISSUE TITLE
timestamp field forcing system timezone without conversion

### ISSUE THREAD

**Issue by jessehon** [laravel/framework#8427]
When default timezone is set to America/Los_Angeles, assigning for example with
```php
$instance->created_at = Carbon("2015-01-01 10:00", "America/New_York");
```
will somehow result in

```php
date=>"2015-01-01 10:00:00.000000",
timezone=>"America/Los_Angeles"
```

where timezone has changed but time not been properly adjusted

**Comment by GrahamCampbell** [comment]
Bug with carbon or php
