### ISSUE TITLE
[Bug] Laravel dblib simple query fatals without exception

### ISSUE THREAD

**Issue by baspeters** [laravel/framework#8429]
When executing simple table-less queries with the DB facade on a properly configured SQL Server connection, the script fatals with a white screen (error 500) without the ability to catch the error.

```php
try {
    $results = DB::select("select 1");
} catch (\Exception $e) {
    // this statement is never reached
    dd($e);
}

// this statement isn't reached either
dd($results);
```

__*Expectation:*__
```php
array:1 [▼
  0 => { ▼
    +0: "1"
  }
]
```

The database connection is configured as type ```sqlsrv``` and is set up using the FreeTDS library as a ``dblib`` PDO connection.

Currently unable to debug further due to time constraints, just reporting it to get it out there. When I find the time I might be able to cook up a merge request. I suspect it might have something to do with the query parser which doesn't understand that a table component is missing.

__*Tested on:*__
Laravel 5.0.27
Lumen 5.0.0

__*Environment:*__
Centos 6.6 / PHP 5.4 / FreeTDS 1.12 / SQL Server 2012

**Comment by stuartmccord** [comment]
I've just ran this in homestead against a postgres DB and got
```
array:1 [▼
  0 => {#204 ▼
    +"?column?": 1
  }
]
```
and a mysql DB
```
array:1 [▼
  0 => {#204 ▼
    +"1": 1
  }
]
```

I think DB::select() just executes the statements passed in without parsing them.  It could be an issue with the SQL Server driver or something like that.

**Comment by GrahamCampbell** [comment]
We're open to PRs.
