### ISSUE TITLE
Guzzle not listed as requirement for artisan schedule

### ISSUE THREAD

**Issue by laurentvd** [laravel/framework#8433]
Laravel suggests requiring Guzzle for Mandrill or Mailgun, but in fact, is is also used in the `php artisan schedule:run` command. See `https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/Scheduling/Event.php`. 

Maybe this should be mentioned in the docs and or added to the composer.json suggestion?

**Comment by GrahamCampbell** [comment]
We're open to pulls.

**Comment by laurentvd** [comment]
There you go. Hope these additions save others some debugging time.

**Comment by GrahamCampbell** [comment]
Taylor as closed it. I assume he's objecting to the vaugness. Make it really clear what bit actually needs it. You also need to update BOTH composer.json files.
