### ISSUE TITLE
Eloquent queries break with having clauses

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#8436]
I’ve come across an issue with Eloquent queries that make use of `having()`.

I’m implementing the [haversine formula](http://en.wikipedia.org/wiki/Haversine_formula) to search a database table containing gyms. Each gym belongs to a venue, which is where I store the latitude and longitude values.

I’m adding a `scopeFilterByLocationAndDistance()` scope to my `Gym` model. I’ve implemented it as thus:

```php
public function scopeFilterByLocationAndDistance(Builder $query, $latitude, $longitude, $distance)
{
	$latitude = (double) $latitude;
	$longitude = (double) $longitude;

	return $query
		->addSelect(app('db')->raw("(3959 * acos(cos(radians($latitude)) * cos(radians(venues.latitude)) * cos(radians(venues.longitude) - radians($longitude)) + sin(radians($latitude)) * sin(radians(venues.latitude)))) AS distance"))
		->join('venues', 'gyms.venue_id', '=', 'venues.id')
		->orderBy('distance', 'asc')
		->having('distance', '<', $distance);
}
```

But this fails with the following error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause' (SQL: select count(*) as aggregate from \`gyms\` inner join \`venues\` on \`gyms\`.\`venue_id\` = \`venues\`.\`id\` having \`distance\` < 10)

But if I remove the `having()` call, the error disappears.

Looking at the SQL statement in the error above, it seems that when adding the `having()` call, it completely disregards my previously-set raw `SELECT` statement.

**Comment by morilog** [comment]
did you use pagination on this query results?

**Comment by martinbean** [comment]
@morilog Yes.

**Comment by morilog** [comment]
try ->get() instead of ->paginate(). maybe it works.

**Comment by martinbean** [comment]
@morilog I want to paginate the results. I don’t want to be fetching 50,000 venues if that’s how many match.

**Comment by morilog** [comment]
you can use Paginator class and separately and paginate your results

**Comment by martinbean** [comment]
@morilog This may be a workaround, but it still doesn’t address that this is a bug in Eloquent.

**Comment by jarektkaczyk** [comment]
@martinbean It's not eloquent bug. You just can't call `select count(*) from ... having ...` becaue `having` is applied after the result has been fetched.

That said, your query is not the best way to do this anyway.

But first, here's what you could do and would work:
```
$query->filterBy...()->simplePaginate() // simple Paginator
```

this will be simple `Paginator` (not `LengthAwarePaginator`), so it will not try to call `count` first.

And here's what you should use instead:
```
public function scopeFilterByLocationAndDistance(Builder $query, $latitude, $longitude, $distance)
{
    $latitude = (double) $latitude;
    $longitude = (double) $longitude;

    $haversine = "(3959 * acos(cos(radians($latitude)) * cos(radians(venues.latitude)) * cos(radians(venues.longitude) - radians($longitude)) + sin(radians($latitude)) * sin(radians(venues.latitude))))";

    return $query
        ->selectRaw("{$haversine} AS distance"))
        ->join('venues', 'gyms.venue_id', '=', 'venues.id')
        ->orderBy('distance', 'asc')
        ->whereRaw("{$haversine} < ?", [$distance]);
}
```

Now it's better in terms of performance, and `$query->paginate()` will work as well.

**Comment by martinbean** [comment]
@jarektkaczyk How is it better in terms of performance? Surely it can’t be better performing the intensive trigonometry calculations _twice_ in the same query?

**Comment by jarektkaczyk** [comment]
@martinbean here in MySQL with ~0.5mil rows it's almost 2 x faster, so I suppose it can.

Remember that `having` filters after you got **all the rows**.

Test it with you data, I might be wrong in the end :)

**Comment by anik786** [comment]
@martinbean In addition to what @jarektkaczyk  said, it may also be because the calculation isn't actually done twice. Remember MySQL does optimisations to queries before executing them.

**Comment by mnabialek** [comment]
@martinbean That's true - `whereRaw` will be faster than `having`. I was testing it a few days ago in some app and it was 50% difference in my case.
