### ISSUE TITLE
Routes bug

### ISSUE THREAD

**Issue by montogeek** [laravel/framework#8441]
Somebody in the https://larachat.slack.com team sent a [message](https://larachat.slack.com/archives/laravel5/p1429164523001948) about a strange behavior regarding Laravel routes in the Laravel docs website

> http://laravel.com/docs/5.0 - actual url
> http://laravel.com/aaa - a nice 404 page
> http://laravel.com/aaa/index.php/docs/5.0 - Laravel documentation page again, same as the first one.

It should return a 404 page. I test it with Laravel 4.1 getting the same results.

**Comment by ehkasper** [comment]
It happens in L5 as well

**Comment by montogeek** [comment]
Yep, Laravel docs site runs with Laravel v5

**Comment by TheShiftExchange** [comment]
Actually - it is not a laravel website bug - seems to be a bug in the Laravel 5 router itself:

Here are some sites that work on Laravel 5:

    https://forge.laravel.com/blah/blah/index.php/auth/login
    https://laracasts.com/blah/blah/index.php/login

Those links all work (but shouldnt).

So looks like any route containing `index.php` is stripped from that point backwards.

**Comment by montogeek** [comment]
Maybe a server config, something related with Apache or Nginx

**Comment by lukasgeiter** [comment]
It's because of how the [Symfony Request class tries to find a base URL](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L1792-L1851). For your example the base URL would be `/aaa/index.php` which is then removed from the actual request URL in `preparePathInfo()`.

**Comment by GrahamCampbell** [comment]
Thanks for reporting. Discussion can continue on the pull request. :)
