### ISSUE TITLE
Composer Update & Laravel Socialite

### ISSUE THREAD

**Issue by shehi** [laravel/framework#8446]
After adding the package to composer.json and into conf/app.php, ```composer update``` command yields following output:
```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Exception: Target [Laravel\Socialite\Contracts\Factory] is not instantiable.
Skipping \Laravel\Socialite\Facades\Socialite.
A new helper file was written to _ide_helper.php
Generating optimized class loader
```
I haven't set any parameters specific to any social login platform in conf.services.php. Any ideas why this error happens?

**Comment by GrahamCampbell** [comment]
Not related to us. Ask the maintainers of the ide helper thing.

**Comment by shehi** [comment]
@GrahamCampbell : You saying its ide-helper related issue? Hmm, ok then.
