### ISSUE TITLE
Logout a user by their ID - not necessarilly the one currently logged in.

### ISSUE THREAD

**Issue by kdoichinov** [laravel/framework#8448]
Hi everyone,

I have a couple of Users defined in my app, one with id = 1 and one with id = 9.
Scenario:
1. Login as user ID **1**
2. Visit "/test" - the route below
Result: **I** get logged out
What I was expecting: I should still be logged in, but the user with ID **9** should be logged out

The "echo" below shows me the details of user 9, not 1 as which I'm logged in, so it appears that up to this point, everything is functioning normally. 

    Route::get('test', function () {
        Auth::setUser(\App\User::findOrFail(9));
        echo Auth::getUser();
        Auth::logout();
    });

By looking at Illuminate\Auth\Guard, I think this should actually function as expected, but for some reason it doesn't. How would I get Auth to respect the user I've set it to when calling `logout()`? Many thanks in advance!

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
