### ISSUE TITLE
[5.0] setUpBeforeClass() not working - Facades not available

### ISSUE THREAD

**Issue by shehi** [laravel/framework#8459]
A code similar to this one:

```php
public static function setUpBeforeClass() {
    Artisan::call('migrate');
}
```
within any unit-test doesn't work. Thrown error is ```class Artisan not found```. This is generally true for all Facades. What to do, as I need to do a task once for each test-class at this stage? Usage of ```setUp()``` method is not viable. Thanks.

**Comment by crynobone** [comment]
If you looking for such customisation, you need to write on your own.

**Comment by shehi** [comment]
Why would we need to?! Its out-of-box feature that comes with PHPUnit. Question is, what could solve the problem, if we wanted quick fix? Why this default feature of PHPUnit doesn't work in Laravel's extended version?

**Comment by crynobone** [comment]
> Your architecture must support testing units (i.e., classes or very small groups of classes) independently, not all chained together. Otherwise, you have lots of overlap between tests, so changes to one unit can cascade outwards and cause failures everywhere. <http://blog.stevensanderson.com/2009/08/24/writing-great-unit-tests-best-and-worst-practises/>

Having it set at `setUpBeforeClass()` would only load `$app` once from every test file/class, and that would lets above scenario to happen. 

This is not the expected default behaviour for everyone else, and would without a doubt break everyone's else test case.

**Comment by shehi** [comment]
No official comment?

**Comment by GrahamCampbell** [comment]
We do not process support requests here. Ask on the forums.
