### ISSUE TITLE
How to enableQueryLog() when I have multiple connections?

### ISSUE THREAD

**Issue by varunsahu** [laravel/framework#8460]
First of all, thanks for the amazing framework! :-)

I have been using enableQueryLog() which seems to work only on my default database connection.  I have two other connections in my database.php which I am using for other models. How can I enable the logging of other connections?

Any help is appreciated.

**Comment by RomainLanz** [comment]
Issues on Github are for bug in the code of Laravel.

Please, ask this question on the forum.
