### ISSUE TITLE
[Eloquent][Proposal] Change cacheMutatedAttributes to loop through attributes rather than looping through class methods.

### ISSUE THREAD

**Issue by IanCaunce** [laravel/framework#8461]
The method cacheMutatedAttributes currently loops through the class methods and runs a preg_match on each method, the result of which may lead to the attribute being cached in the mutatorCache property in either camel case or snake case.

Would it be more reliable to loop through the models attributes, and run hasGetMutator to determine if it has a mutator and cache the result of that.

The reason why I am suggesting this, as at the moment it seems that at the moment the current implementation only seems to support snake and camel case. 

If I am supporting a legacy database which I am unable to change the schema of and it has a column in a table called "SomeValue", if I write a mutator "getSomeValueAttribute" and access that property the value is successfully mutated. However, if I was to run toArray or toJson on that model, the value remains unmutated as the mutatorCache will contain either "some_value" or "someValue" neither of which pass the check in the attributesToArray method.

**Comment by GrahamCampbell** [comment]
Closing due to lack of interest.
