### ISSUE TITLE
Dynamo session driver for Laravel 5

### ISSUE THREAD

**Issue by Wendtly** [laravel/framework#8464]
For those of you not satisfied with these previous issues:
https://github.com/aws/aws-sdk-php-laravel/issues/16
https://github.com/laravel/framework/issues/4209

Here's my version:

    <?php namespace App\Providers;

    use Illuminate\Support\ServiceProvider;
    use Aws\DynamoDb\DynamoDbClient;
    use Aws\DynamoDb\Session\SessionHandler;
    use Session;

    class DynamoSessionServiceProvider extends ServiceProvider {
        const DEFAULT_REGION = 'us-east-1';
    
        // Make sure that this service provider always boots
        protected $defer = false;
    
        /**
         * Register the service provider.
         *
         * @return void
         */
        public function register() {
           Session::extend('dynamo', function ($app) {
                // Get a shortcut to config data            
                $cfg = $app['config']->get('session');
            
                // Do the real work of hooking up Dynamo as session handler
                $dynamoDb = DynamoDbClient::factory([
                    'region' => (isset($cfg['region']) ? $cfg['region'] : self::DEFAULT_REGION),
                ]);
            
                $sessionHandler = $dynamoDb->registerSessionHandler([
                    'table_name'               => $cfg['table'],
                    'hash_key'                 => 'id',
                    'session_lifetime'         => $cfg['lifetime'],
                    'consistent_read'          => true,
                    'locking_strategy'         => null,
                    'automatic_gc'             => true,
                    'gc_batch_size'            => 25,
                    'max_lock_wait_time'       => 10,
                    'min_lock_retry_microtime' => 10000,
                    'max_lock_retry_microtime' => 50000
                ]);
            
                // Set the start of the session id to the cookie name - optional
                $sessionHandler->open('', $cfg['cookie']);
            
                return $sessionHandler;
            });
        }
    }
    ?>

To use, set the following in /config/session.php:
    'driver' => 'dynamo'
 
Additionally, the following session options also impact this class:
    'table' => 'name-of-Dynamo-table'
    'lifetime' => number-of-minutes-to-live
    'cookie' => 'start-of-session-id' - in addition to being the cookie name - optional (see code)
    'region' => 'aws-region' (must add option to file manually, or defaults to self::DEFAULT_REGION)
 
Other options like 'secure', 'expire_on_close', 'domain' and 'encrypt', while not used directly by this class, still affect Laravel's session management.

**Comment by GrahamCampbell** [comment]
Would make a good package.

**Comment by Wendtly** [comment]
Better: should be baked into Laravel core, like the AWS SES mail transport was for L5. ('driver'  => 'ses' now in /config/mail.php. Speaking of which, 'ses' needs to be added to the "Supported:" section in the comments of that file)

**Comment by vineetgarg90** [comment]
Thanks @Wendtly, really helpful.
I have also created a tutorial for the same.
http://www.techigniter.in/tutorials/dynamodb-session-driver-for-laravel-5/

**Comment by inxilpro** [comment]
For those who found this thread via search, I've got a PR out for adding support to the official AWS Laravel package: 

https://github.com/aws/aws-sdk-php-laravel/pull/114

**Comment by Mozammil** [comment]
You could also use this package: https://github.com/oryxcloud/laravel-dynamodb-session-driver
