### ISSUE TITLE
Laravel Packagist

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#8466]
https://packagist.org/packages/laravel/laravel

See here the latest version is v5.0.22 which is out of sync which is causing a lot of issues when using create-project as it gets the buggy compiled code then updates to 5.0.27 which has the fixed, it looks like to needs to skip straight to 5.0.27 as that is the currently stable version.

**Comment by riotCode** [comment]
That is not for this repo. This is
https://packagist.org/packages/laravel/framework

5.0.22 of laravel/laravel is the project repo for versions 5.0.22+, from it's composer.json it will install laravel/framework 5.0.*  (which resolves to 5.0.27)

**Comment by Sladewill** [comment]
Firstly there's no issue tracker on laravel/laravel and it is not resolving to 5.0.27 which why so many people are moaning about the clear compiled problems when installing fresh laravel.
