### ISSUE TITLE
Methods in API documentation not ordered alphabetically.

### ISSUE THREAD

**Issue by phaza** [laravel/framework#8468]
When you read documentation for classes or interfaces on http://laravel.com/api/5.0/ the methods should be listed alphabetically to make it easier to find what you're looking for.

Currently you have to do search within the frame, which is a bitch itself.

**Comment by tomzx** [comment]
First, I assume you are aware that this uses [Sami](https://github.com/FriendsOfPHP/Sami) to generate the documentation.

Second, I don't think Sami has any setting to make it display like you'd like to. So it would probably make the most sense to open a ticket there and ask for such feature.

Lastly, I'm curious as to why you'd refer to the API online. You most likely have a copy lying on your computer and it is generally much faster to browse code through a code editor/IDE than through a website.
