### ISSUE TITLE
Retrieving route parameters as query argument not possible

### ISSUE THREAD

**Issue by uikid** [laravel/framework#8476]
When setting up route like

```php
Route::get('test', 'TestController@test');
```

it is not possible to access query parameters when the route is being accessed like this:

```
/test?foo=bar&id=3&framework=laravel
```

The controller method

```php
public function test(Request $request)
    {
        var_dump($request->input('foo'));
    }
```

(also tested with $request->get('foo'))

doesn't work.

The only option is to make a route like

```php
Route::get('test/{foo}/{id}/{framework}' , 'TestController@test');
```

but that would make it impossible for optional parameters because all parameters have to be included, even if the questionmark is used, the only option would be to make the last one optional with {framework?}.

A long query argument where a lot of query parameters are optional was easily possible in Laravel 4 like

```
/search?user=lara&country=usa&car=truck&city=washington
```

(It is even possible to change the order of all parameters, that wouldn't be possible with the slashes version)

Where you could check and get all the parameter values with

```php
Input::get('user')
```

But every method mentioned in this issue ticket returns null in Laravel 5.

**Comment by GrahamCampbell** [comment]
Can't replicate. Ask on the forums.

**Comment by shakir1443** [comment]
I have also the same problem.
