### ISSUE TITLE
[BUG] [Lumen] Logging facade is broken

### ISSUE THREAD

**Issue by Someguy123** [laravel/framework#8486]
Doesn't seem to be an issue tracker on either of the Lumen repo's so I'm posting it here.

When using functions such as `Log::info()` or `Log::error()` with **facades turned on**, you get the following PHP error:

    Call to undefined method Illuminate\\Support\\Facades\\Log::info()

There appears to be an issue with the `Log` facade in Lumen and I can't figure out why.

**Comment by GrahamCampbell** [comment]
Dupe.

**Comment by Someguy123** [comment]
@GrahamCampbell duplicate of what issue exactly?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/lumen-framework/pull/39

**Comment by iyaozhen** [comment]
But, It looks like not friendly for IDE(PHPStorm).
![image](https://cloud.githubusercontent.com/assets/4395553/13276176/94e09bf8-daf7-11e5-99f6-b25a18e3a9bc.png)

**Comment by Someguy123** [comment]
@iyaozhen Use this to fix that: https://github.com/barryvdh/laravel-ide-helper

**Comment by iyaozhen** [comment]
@Someguy123 Thx, this 'ide-helper' work well.
