### ISSUE TITLE
Pagination render stdClass undefined method

### ISSUE THREAD

**Issue by gokigoks** [laravel/framework#8489]
I did a simple query plus pagination and it works fine without the render()
but when I add the {!! $articles->render()  !!} it reports 
Undefined property: Illuminate\Pagination\LengthAwarePaginator::$id (View: D:\PHP\laravel\resources\views\Article\article.blade.php) 

I managed to work around this by placed the $articles render at the top before my loop iterating through the $articles. I have not much deeper knowledge with laravel source and I hope you guys can find the issue.

**Comment by gokigoks** [comment]
at first I used a 
@foreach($article as $article)

@endforeach

$article->render

and it gives me a StdClass render undefined method.

It works when I place the render before the foreach loop though. hmmm mind checking if its because of the latest PR with collections?

**Comment by GrahamCampbell** [comment]
Please discuss on the forums.
