### ISSUE TITLE
Mail::queue return problem

### ISSUE THREAD

**Issue by djalmaoliveira** [laravel/framework#8500]
Hi, I'm using laravel 5.0.18, and I have different return behavior between Mail::send() and Mail::queue() methods.

In config/mail.php:

'driver' => env('MAIL_DRIVER', 'mail'),

In config/queue.php:

'default' => env('QUEUE_DRIVER', 'sync'),

My problem is:

if ( Mail::send(....) )  {  } // return true and mail is sent as expected;

if ( Mail::queue(....) )  {  } // return false, but mail is sent too, here is my problem

thanks!

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
