### ISSUE TITLE
Laravel Blade passing variable with string through @include causes error

### ISSUE THREAD

**Issue by Pyloid** [laravel/framework#8502]
In blade, when including a template and passing a variable with a string containg a "(" or ")" an error is generated. Below are steps to reproduce.

In Laravel 5.0.27 I am including a view with with a variable using the following code:

    @include('layouts.article', [
			'mainTitle' => "404, page not found",
			'mainContent' => "sorry, but the requested page does not exist :("
		])

which generates the following error...

 
> FatalErrorException syntax ... error, unexpected ','

I've narrowed down the error to just the "(" in the "mainContent" variable string. When I remove the "(" the error disappears and everything runs as expected. I tested this on a fresh install of laravel (5.0.16) and it still had the issue. 

Thanks!

**Comment by Arrilot** [comment]
Blade works on regular expressions, so syntax is limited there.

Just make a variable and path it to include like that `@include('layouts.article', $var)` and you should be fine

**Comment by rscafi** [comment]
The problem is using multi-line. You can only use a single line to do this.
Try the code below and you should be good to go:
```php
@include('layouts.article', ['mainTitle' => "404, page not found", 'mainContent' => "sorry, but the requested page does not exist :("])
```

**Comment by Pyloid** [comment]
Thanks for the information, sorry for my misunderstanding!

**Comment by joeyfb** [comment]
In Laravel 5.6 is a multiline include now valid, so the below would work?

```
@include('layouts.article', [
        'mainTitle' => "404, page not found",
        'mainContent' => "sorry, but the requested page does not exist :("
    ])
```

**Comment by doubleprincez** [comment]
Not working In Laravel 5.6 that i'm trying to update! I'm trying to upgrade an old app and noticed its still not working
