### ISSUE TITLE
Using Laravel compressed in a phar file

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#8503]
How can one go about compressing Laravel into a single Phar file? I'd like to compress everything except the configuraiton directory and artisan file

**Comment by GrahamCampbell** [comment]
You could compress the framework repo in this way, though, not the laravel/laravel repo. This would break out views system.

**Comment by GrahamCampbell** [comment]
And our config.

**Comment by GrahamCampbell** [comment]
I suspect you could probably get Laravel partially working though. Feel free to discuss on the forums. :)
