### ISSUE TITLE
Tinker must be restarted for code to take effect.

### ISSUE THREAD

**Issue by kadimi** [laravel/framework#8504]
Hello

I've started studying the Laravel framework on @JeffreyWay's Laracasts for a few hours and I noticed this:

### Bug:
When using `tinker`, I receive the mass-assignment error even if the columns are whitelisted with `$fillable`. The error is:  `Illuminate\Database\Eloquent\MassAssignmentException with message 'title'`)

### How to reproduce:
1. Create a Model with a title column
1. Start tinker **now**
1. Whitelist the title for mass assignment
1. Try to add a new row and notice the error eg. 

    `>>> App\Article::create(['title'=>'1st Article']);`
1. Restart tinker
1. Repeat (4), this now it works

### So...
Is there a way to avoid restarting tinker?

**Comment by Anahkiasen** [comment]
I think you mean `tinker` cause tinkster is *way* something else :D

**Comment by kadimi** [comment]
@Anahkiasen Yep, thanks.

**Comment by JosephSilber** [comment]
This is not a bug. It is how `tinker` works.

**Comment by kadimi** [comment]
@JosephSilber I see, thanks.

**Comment by tnorthcutt** [comment]
@kadimi you might want to check out this repo: https://github.com/ajthinking/tinx

**Comment by GrahamCampbell** [comment]
We've love contributions back to the original repo. We were discussing the possibility of restarts only recently.

**Comment by szekeresa** [comment]
@kadimi Here a simple bash command: 

`while true; do php artisan tinker; done`

CTRL+D = reload   
CTRL+C = exit   

or

.profile file:

`alias pat="php artisan tinker"`
`alias patt="while true; do php artisan tinker; done"`

after type "pat" to normal tinker, and "patt" to continous tinker.

**Comment by ryancwalsh** [comment]
@GrahamCampbell Any more recent thoughts about how not to be required to restart Tinker after editing code?

I see "Laravel Tinx was archived on 12th December 2019 and is no longer maintained." but also that it seems to be just a suggestion like https://github.com/laravel/framework/issues/8504#issuecomment-478248339 

@szekeresa It seems to work for me so far (+1), but would you mind explaining what that is doing and what the downsides are of running Tinker that way? 

Thanks!

**Comment by MrWeb** [comment]
> @szekeresa It seems to work for me so far (+1), but would you mind explaining what that is doing and what the downsides are of running Tinker that way?
> 
> Thanks!

This command `while true; do php artisan tinker; done` runs a loop with tinker, and every time you close it by Cmd+D or exit it the loop starts over again, so it reloads the classes and all the lot. Cmd+C closes it.

**Comment by onlime** [comment]
If anyone has run into the new [PsySH v0.12.13](https://github.com/bobthecow/psysh/releases/tag/v0.12.13) SIGINT handling "regression" (fixes https://github.com/bobthecow/psysh/issues/154) and can no longer exit the `php artisan tinker` loop with Ctrl-C, try this:

```bash
alias patt='trap "kill 0" SIGINT; while true; do php artisan tinker || break; done; trap - SIGINT'
```

instead of the good old (before PsySH v0.12.13):

```bash
alias patt="while true; do php artisan tinker; done"
```
