### ISSUE TITLE
View is not rendered in controller specified middleware.

### ISSUE THREAD

**Issue by RyanThompson** [laravel/framework#8510]
During middleware that is specified from a controller - the response is still a View object. Seems like it should be a Response like it is in the middleware defined in Kernel.php

**Comment by GrahamCampbell** [comment]
Yeh, this was mentioned a while ago. Can't remember what we did about it. Ping @taylorotwell.

**Comment by taylorotwell** [comment]
This is fixed for 5.1.

**Comment by RyanThompson** [comment]
Excellent. Thanks!
