### ISSUE TITLE
[Cache] [Proposal] Introduce Cache Dependency

### ISSUE THREAD

**Issue by miraage** [laravel/framework#8517]
It is very powerful and flexible feature.

IMHO, not hard to implement next cache dependencies:
- file cache dependency (file contents, modification time)
- expression dependence (raw value)
- db cache dependency (result of specified SQL statement)

Let me show example from Yii1
```php
$sql = 'SELECT * FROM tbl_post LIMIT 20';
$dependency = new CDbCacheDependency('SELECT MAX(update_time) FROM tbl_post');
$rows = Yii::app()->db->cache(1000, $dependency)->createCommand($sql)->queryAll();
```

Your minds?

**Comment by GrahamCampbell** [comment]
Query caching was removed in Laravel 5.0. It it now up to people to implement their own caching. A common case I think will be the repository pattern with a caching repository decorator.

**Comment by miraage** [comment]
Looks like I should create own bundle?

**Comment by GrahamCampbell** [comment]
This isn't something I think would work as a package either. It is something that people can very easily write within their applications.

**Comment by miraage** [comment]
Maybe, but I want use this feature in all projects I develop with Laravel/Lumen. :)

**Comment by GrahamCampbell** [comment]
Yes, that's fine. The stuff we're talking about it totally framework agnostic.

**Comment by GrahamCampbell** [comment]
Example of this design pattern in Cachet: https://github.com/cachethq/Cachet/tree/L5/app/Segment. Note that this isn't wrapping eloquent or anything, but it's the same idea.

**Comment by miraage** [comment]
Very thanks you for clarification.
