### ISSUE TITLE
Cache Tags with remember() - flush fails (Redis)

### ISSUE THREAD

**Issue by subdesign** [laravel/framework#8519]
Problem: can't flush tagged cache if I use remember(). Example:
```
$result = Cache::tags('feeds')->remember($tagname, Setting::get('xml.cache')['value'], function() use ($file) {
...
}
```
after that
```
Cache::tags('feeds')->flush();
```
doesn't do anything. How I know? I use phpredmin (https://github.com/sasanrose/phpredmin) to monitor the Redis status.
In my other part of code where I don't need timing, rememberForever() can be flushed:
```
$page = Cache::tags('pages')->rememberForever('page_'.$slug, function() use ($slug) {
...
}
Cache::tags('pages')->flush(); // works!
```
Am I using wrong maybe tagging with remember, or it should be a bug?
Simply adding and forgetting data from Redis also works well.

Laravel 4.2.16
Redis 2.8.4

Thanks

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported, though I suspect that L5.0 will behave in exactly the same way.

**Comment by subdesign** [comment]
Hmm, thanks.
