### ISSUE TITLE
Request methods saying return string.

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#8521]
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Http/Request.php#L503

The method above 

```php
/**
 * Retrieve a parameter item from a given source.
 *
 * @param  string  $source
 * @param  string  $key
 * @param  mixed   $default
 * @return string
*/
```

Supposed to return a string, but it could return an array.

Subsequently anything using that method also has it wrong as well i.e.

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Http/Request.php#L340

```php
/**
 * Retrieve a query string item from the request.
 *
 * @param  string  $key
 * @param  mixed   $default
 * @return string
*/
```

**Comment by GrahamCampbell** [comment]
We're open to pull requests. :)
