### ISSUE TITLE
Cannot place `migrations` table into any schema other than default on Postgres and MS SQL Server

### ISSUE THREAD

**Issue by FractalizeR** [laravel/framework#8523]
If you try to do something like this
```php
    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'public.migrations',
```

Laravel will try to recreate migrations table each time and, eventually, will fail since it already exists.

The attempt to recreate a table comes from this:
\Illuminate\Database\Schema\Grammars\PostgresGrammar:
```php
	/**
	 * Compile the query to determine if a table exists.
	 *
	 * @return string
	 */
	public function compileTableExists()
	{
		return 'select * from information_schema.tables where table_name = ?';
	}
```

`table_name` in `information_schema.tables` does not contain schema name. So, if you execute this query against `'public.migrations'` as a parameter, you will get no result even if this table really exists.

With this implementation it is impossible to verify the existence of any fully qualified table name.

This bug relates to #7556, #4063, #2043

It will affect people, who, like me has several schemas per project and want to put migrations into `public` schema.

My current solution to the case is to leave migration table unqualified, but set 'schema' database connection parameter to the following value:

```php
            'schema' => 'public","storage',
```

I am using something like SQL injection to set PostgresSQL search_path to a list of schemas, putting `public` first.

Can something be done about that?

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by glaucomorais** [comment]
In my scenario, I was trying to keep a test schema in the same database that the application run, but the same database runs all applications from the company.

In my case, have an application that need to repeat some tables, like users, the migrations won't work for this specific app.
