### ISSUE TITLE
Allow using not defined class name as type hint to set injection

### ISSUE THREAD

**Issue by binaryoung** [laravel/framework#8531]
Laravel container use these code to  get the type hint
```
	/**
	 * Get the type hint for this closure's first argument.
	 *
	 * @param  \Closure  $callback
	 * @return mixed
	 */
	protected function getFunctionHint(Closure $callback)
	{
		$function = new ReflectionFunction($callback);
		if ($function->getNumberOfParameters() == 0)
		{
			return;
		}
		$expected = $function->getParameters()[0];
		if ( ! $expected->getClass())
		{
			return;
		}
		return $expected->getClass()->name;
	}
```
But it will cause a fatal error if the class required by the  type hint is not defined. Sometimes,i just want to bind some simple name with my services to service container and use type hint to setter injection .But i can't do that.Can you provide some background on the need for this code?Maybe you can use these code that post on http://php.net/manual/en/reflectionparameter.getclass.php to get type hint.
```
function getClassName(ReflectionParameter $param) {
    preg_match('/\[\s\<\w+?>\s([\w]+)/s', $param->__toString(), $matches);
    return isset($matches[1]) ? $matches[1] : null;
}
```
Any ideas?

**Comment by franzliedke** [comment]
I'm pretty sure that's a PHP limitation. The class or interface in the typehint needs to be defined.

**Comment by JosephSilber** [comment]
@franzliedke It can be done by registering an alias on the fly, but Taylor has rejected it - and for good reason.
