### ISSUE TITLE
[L5] Stateless Authentication in PHPUNIT Tests

### ISSUE THREAD

**Issue by smaxwellstewart** [laravel/framework#8538]
Hey Guys,

So I am building an API, so of course changed my authentication to be stateless. Everything works great except that the following does not work anymore in my tests:

```php
$user = new User(['email' => 'someone@example.com']);
$this->be($user);
```

I could live with this if I could find a way to manually set an authorization header in my tests but I am unclear how to do that either.

Any help would be massively appreciated.

Simon

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by smaxwellstewart** [comment]
Is it not a bug that the $this->be($user) is not working?
