### ISSUE TITLE
[proposal] update sync method of belongsToMany.php to ignore null

### ISSUE THREAD

**Issue by matthewmalone** [laravel/framework#8544]
Update the sync method to accept non-arrays and ignore the request if the input is "null". This way, when multiple select forms are sync'ed with no value, you do not need to use the ternary operator like the example below.

	$tags = $request->input('tag_list');
	$company->tags()->sync($tags <> null ? $tags : []);

**Comment by lukasgeiter** [comment]
I'm not saying this proposal is a bad idea, but you could use the default value to make your code a bit cleaner:

    $tags = $request->input('tag_list', []);
    $company->tags()->sync($tags);
