### ISSUE TITLE
Eloquent primaryKey integer by default

### ISSUE THREAD

**Issue by ibruque** [laravel/framework#8545]
I have created a migration for a model where the primary key is defined as follow:
$table->string('idproduct', 5)->primary();

I have created an Eloquent model where I have set up the attribute $primaryKey as follows:
protected $primaryKey = "idproduct";

I have created a seeder with the next code:
$product = Product::create([
                'idproduct' => "ASDFG"
]);

If I try to watch the 'idproduct' value for de Product created, I get that this attribute is an integer and its value is 0:
var_dump($product->idproduct); -> int(0)

But if I find the element created I get the correct result:
var_dump(Product::find('ASDFG')->idproduct); -> string(5) "ASDFG"

I takes the same effect if you separate the create process in two steps (fill() and save()).

So, I understand in some place of the code, a primary key is considered an integer by default when you construct a new model and this is great problem.

For example, if you want to immediately attach() the element created to a pivot table, you will get an error!

**Comment by lukasgeiter** [comment]
Did you set `incrementing` to false?

    class Product extends Model {
        public $incrementing = false;
    }

**Comment by ibruque** [comment]
Ups! No. I've set it now and it works now! Sorry!
