### ISSUE TITLE
[Bug]: Middleware declared in controller construct is validated after other construct methods

### ISSUE THREAD

**Issue by zerojargon** [laravel/framework#8558]
As mentioned in the title, middleware declared in the construct method of a controller appears to be validated after any other methods in the construct.

Code example below, but summary is:

* middleware should trigger an abort(404)
* abort(500) is called after the middleware is declared
* the abort(500) will always run first, even though it is called after the middleware.

**Route:**

	Route::get('foo', 'ApiController@foo');

**Controller:**

	class ApiController extends Controller {

		public function __construct()
		{
			$this->middleware('baz');
			abort(500);
		}
		public function foo()
		{
			return 'bar';
		}

**Middleware:**

	class baz extends BaseMiddleware {

		public function handle($request, Closure $next)
		{
			if($request->input('test') == 1) {
            			abort(404);
        		}
        		return $next($request);
		}
	}

visiting *url.com/foo* or *url.com/foo?test=1* both returns the 500 error.

removing the abort 500 from after the middleware declaration and visiting *url.com/foo?test=1* returns a 404 as expected.

Whilst this example is oversimplified, running a method which depends on the success of the middleware, after the middleware will fail. My case being getting the user from a token, where the middleware ensures the token is valid.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. I have no idea why you would expect anything else?

**Comment by zerojargon** [comment]
Forgive me, was more the difference in when the middleware is run when declared in the construct, as opposed to when declared in the routes. When the middleware is called in the route, this happens before the construct is run, it would seem.

**Comment by heisian** [comment]
is there a way to have functions run in __construct() but after any included middleware??

**Comment by kduszczy** [comment]
@heisian I know I'm late but maybe someone will see this. You can override callAction method like this:
```php
public function callAction($method, $parameters)
{
    //your code to run after middleware and before action
    return parent::callAction($method, $parameters);
}
```
It's not in construct but will be run in more less correct time. Unless you want to run something between middlewares.
