### ISSUE TITLE
Builder with a groupBy results in empty pagination->render()

### ISSUE THREAD

**Issue by simonfranz** [laravel/framework#8559]
HI there, 

I think i have found a bug witht he pagination-component while using a group-by statement.

My sample model is quite simple 
```
Song
     id
     name
     artist_id
Artist
     id
     name
```
In my Controller do can do this query:
```
 $songs = Song::select('songs.*')
            ->join('artists', 'songs.artist_id', '=', 'artists.id')
            ->groupBy('songs.id')
```
which results into this sql statement.
```
select count(*),`songs`.* from `songs` inner join `artists` on `songs`.`artist_id` = `artists`.`id` group by `songs`.`id`
```

By now this is all correct, but if i want to use $songs->paginate(25); the result is a LengthAwarePaginator, which looks like this:
```
LengthAwarePaginator {#28786 ▼
  #total: 1
  #lastPage: 1
  #items: Collection {#28759 ▶}
  #perPage: 25
  #currentPage: 1
  #path: "myurl"
  #query: []
  #fragment: null
  #pageName: "page"
}
```

Maybe you can already see, that the "total"- value is wrong. I think it's the problem, is that to get the total value its Illuminate\Database\Pagination\Builder::getCountForPagination() is called. To get the total row-count a count(*) is added in front of the query, But through the group by in every row the first value is 1, to the result for getCountForPagination() is set to one and no pagination links are rendered, because there seems to be only 1 page. 

Is this behaviour by purpose? Is there a workaround for this?

In my application i do multiple joins over multiple tables to create a large query over multiple tables, so i have to call a group-by to get the get the grouped songs.

**Comment by GrahamCampbell** [comment]
What Laravel version?

**Comment by GrahamCampbell** [comment]
Does https://github.com/laravel/framework/pull/8310 fix this for you>

**Comment by simonfranz** [comment]
thanks for the quick repsonse
I'm on version 5.0.28
#8310 does fix the problem, yes

thanks

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by simonfranz** [comment]
hopefully it's get merged soon ;-)
