### ISSUE TITLE
2 PATCH method route for same controller

### ISSUE THREAD

**Issue by gokigoks** [laravel/framework#8560]
I noticed this when I was sending an ajax request and I always get the methodNotAllowed exception.
I worked around this by specifying the type of my request to a patch but adding a _method : 'Delete' in the data.

![prntscreen](https://cloud.githubusercontent.com/assets/10005383/7334840/5f45ecce-ebd2-11e4-8d73-58cb92593ba9.png)

**Comment by GrahamCampbell** [comment]
It you want to delete something, you need to use the DELETE verb, or the _method hack we allow.

**Comment by gokigoks** [comment]
I tried DELETE and the post with a _method :'delete' , BUT those did'nt work. only worked when I specified the type of my request to a PATCH. WIERD :D
