### ISSUE TITLE
Bug with Self relations, inside Eloquent\Builder has() closure  v 5.0.28

### ISSUE THREAD

**Issue by imranomari** [laravel/framework#8563]
Before the version  5.0.28 of illuminate/database there have been a small bug in has() method of Eloquent\Builder, when the relationship references the same model, as described in issues #6190 .

We were going around this problem as follows:

```
// Inside Message model
function replies()
{
  return $this->hasMany('App\Models\Message', 'parent_id', 'id');
}

public function scopeHasNewReplies($query, $user)
{
  return $query->has('replies', '>', 0, 'and', function ($query) use ($user)
  {
    $query->from('message as replies')->orWhere(function ($query) use ($user)
    {
      $query
        ->whereRaw('`replies`.`parent_id` = `message`.`id`')
        ->where('replies.receiver_id', $user->id)
        ->where('replies.is_seen', 0);
    });
  });
}
````

The code above results an sql query with the right alias `replies` and additional OR in the  where clause to avoid the useless generated  ` select count(*) from  message where message.id = message.id` clause.

The [merged pull request that intended to fix this issue](https://github.com/laravel/framework/commit/499495) made it impossible to use where conditions that reference the relation (replies in the example above), because the table name in the `from` clause that represents the child in the relation is aliased using a [generated hash](https://github.com/laravel/framework/commit/499495#diff-c8675355c360b9bd4ef485c30ff5e025R86) that can't be accessed in the closure, and changes in each call to the method [getRelationCountHash](https://github.com/laravel/framework/commit/499495#diff-ec2d0253053e44a86e87a99c6b65a3cbR124)

As a result, this scope:
````
public function scopeHasNewReplies($query, $user)
{
  return $query->has('replies', '>', 0, 'and', function ($query) use ($user)
  {
      $query
        ->where('replies.receiver_id', $user->id)
        ->where('replies.is_seen', 0);
  });
}
````

Generates an sql query that looks like this:
````
select
	*
from
	`message`
where
	`parent_id` is null
    and (`receiver_id` = 1 or `sender_id` = 1)
    and ((select 
				count(*)
			from
				`message` as `self_63635fc4a0a4dc4135631e1e45c8bb24`
			where
				`self_63635fc4a0a4dc4135631e1e45c8bb24`.`parent_id` = `message`.`id` 
                and `replies`.`receiver_id` = 1 
                and `replies`.`is_seen` = 0
			) > 0
		or (`receiver_id` = 1 and `is_seen` = 0))
````

So If I'm not missing something, I think `has()` method should pass the name of the relation or a custom alias to getRelationCountQuery() and getRelationCountQueryForSelfRelation() to use it instead of the generated hash, that way it can be used also in the conditions inside the closure.

Any thoughts on what's the best approach to solve this?

**Comment by GrahamCampbell** [comment]
We're open to PRs.
