### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#8564]
why does php artisan migrate:refresh NOT work unless you have done a prior "php artisan migrate"?

Is this intended or a bug?

**Comment by sukonovs** [comment]
Refresh is combination of reset/migrate commands. Most likely it does not work because you have no migrations table in db what is needed for restet part of command.

**Comment by pjebs** [comment]
yes. so why cant it automatically do a migrate if that is the case.

Right now, it's 2 steps.
