### ISSUE TITLE
[Proposal][Lumen] Add tinker command

### ISSUE THREAD

**Issue by Someguy123** [laravel/framework#8566]
I've been running into a lot of strange problems with Lumen lately, and the lack of tinker makes these issues even more irritating because they're harder to debug.

Can we please get Tinker in Lumen? It's extremely important in debugging applications, even if this is a micro-framework.

**Comment by GrahamCampbell** [comment]
That would add a lot of dependencies.

**Comment by GrahamCampbell** [comment]
It would make a good lumen package though. :)

**Comment by gerrywastaken** [comment]
damn
