### ISSUE TITLE
ErrorException in BladeCompiler.php line 261: preg_replace_callback(): Compilation failed

### ISSUE THREAD

**Issue by ethali** [laravel/framework#8567]
Hi.

I just installed a fresh install of Laravel 5.*. I can't display the welcome view ;-(

Here's the error I get:
ErrorException in BladeCompiler.php line 261: preg_replace_callback(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 47

I'm running PHP 5.5.13, PCRE 8.34 2013-12-15.

I can't figure out what the issue is.

Thanks for the help.

**Comment by GrahamCampbell** [comment]
Looks like a php bug. We can't really do anything about this, sorry.

**Comment by odin88** [comment]
I face the same problem.

Using PHP 5.4.7

So the only solution is to upgrade my PHP version ?

ErrorException in BladeCompiler.php line 261:
preg_replace_callback(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 47

![2015-05-23_4-13-17](https://cloud.githubusercontent.com/assets/680300/7778867/0d8e1f92-0102-11e5-9693-33f32b6bd460.png)

**Comment by GrahamCampbell** [comment]
Had reports of this being an issue in php 5.5.23 too. :?

**Comment by spinn** [comment]
Happens with PHP 5.6.9/PCRE 8.37 as well (running Debian with PHP from Dotdeb).

**Comment by odin88** [comment]
Guys .. after some researching I think it is because of the PCRE version is not match with your PHP version.

https://github.com/swiftmailer/swiftmailer/issues/259

List of PCRE and PHP version - http://php.net/manual/en/pcre.installation.php

**Comment by marcamon2013** [comment]
Change your vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler with is one.

https://raw.githubusercontent.com/laravel/framework/a1c5dd80aa6a13e0f8cf1f0e0e1700ff65c11f2c/src/Illuminate/View/Compilers/BladeCompiler.php

**Comment by GrahamCampbell** [comment]
Looks like this is a bug in your php environment, not laravel.

**Comment by hecpalomares** [comment]
I upgraded my php to 5.6 8 in my DO server (I'm using 5.5.12 locally) keep getting the same error.

**Comment by GrahamCampbell** [comment]
Yeh, as I said, it's a problem with your php environment. Take it up with the people who compile your php.
