### ISSUE TITLE
[Proposal] Update multiple records at once - Query Builder / Eloquent.

### ISSUE THREAD

**Issue by IonutBajescu** [laravel/framework#8570]
I've seen that a common use case of update is not allowed by the Laravel Query Builder and therefore Eloquent.

The single use case of multiple update currently covered by the Query Builder is updating multipe rows using a static value, not a dinamic one - which can be different for each one of the records based on the other columns.

Usually a multiple update is done using CASE ... WHEN instructions https://dev.mysql.com/doc/refman/5.0/en/case.html

One of the eloquent strongest assets is that is making complex problems (like the eager loading) painless and without inserting boilerplate code. Well, a multiple update is one of those cases where boilerplate code is required and the final code looks really ugly.

------------------------------------------

Okay, is someone finding that usefull? I've encountered it sometimes. 
I don't think that the implementation really matters in the current state of this issue.

**Comment by Flightfreak** [comment]
+1

**Comment by GrahamCampbell** [comment]
This looks outside the scope of our system.
