### ISSUE TITLE
Laravel round pdo mysql float field

### ISSUE THREAD

**Issue by nadavvin** [laravel/framework#8573]
PHP 5.6.5
Laravel 4.2

if I run:
DB::getPdo()->query("select float_field from some_table")->fetchAll();

It will round the result. so 155.02 become 155.

However if I run:
$pdo = new PDO('mysql:dbname....');
$pdo->->query("select float_field from some_table")->fetchAll();

It will be the same as in the database.

**Comment by taiyaei** [comment]
@nadavvin Here's a relevant issue if you want one rather than nothing being said: #6980.
