### ISSUE TITLE
[L5] Route middleware not processed before bindings are resolved

### ISSUE THREAD

**Issue by egeriis** [laravel/framework#8578]
I am experiencing an issue with `get`, `put` and `delete` requests, where Laravel attempts to resolve controller method bindings before route middleware has been executed.

This is concerning especially when Laravel are automatically passing model instances to controller method, e.g. when using `Route::resource`. This creates an interesting security issue, because Laravel will actually fetch the model from database before the request has been authenticated.

In my case, I am using an auth middleware which sets a configuration directive which defines a context for the current session. This context is the base for all database requests and ensures that my multi-tenant setup doesn't leak data from a wrong tenant.

It's simple to test this bug.

**Routes**

```php
Route::group(['middleware' => App\Http\Middleware\Test::class], function () {
    Route::resource('users', 'UsersController');
});
```

Create **App/Http/Middleware/Test.php**

```php
<?php namespace App\Http\Middleware;

use Closure;

class Test
{
	public function handle($request, Closure $next)
	{
		dd('test middleware');
		return $next($request);
	}

}
```

Create **App/Http/Controllers/UsersController.php**

```php
<?php namespace App\Http\Controllers;

class UsersController extends Controller
{
    public function index()
    {
        dd('index');
    }

    public function store()
    {
        dd('store');
    }

    public function update()
    {
        dd('update');
    }

    public function destroy()
    {
        dd('destroy');
    }
}
```

A `GET` request to `/users` will trigger the middleware and output `test middleware`, while a `GET` request to `/users/1`—or any other request that references a single entity, i.e. `PUT /users/1`, `DELETE /users/1`, etc.—will attempt to connect to a database to fetch that entity. This may result in an Exception if you have not set up a database for this demo.

This logic might be by design, but to me it looks more like wrong order of execution and a bug.

**Comment by PhilMarkham** [comment]
I also came across this issue today. I was hoping to verify an API signature in a middleware, then if it's successful setting a global scope that limits the data that API request can fetch. 

Unfortunately, because the model has already been booted by the route/model binding - I'm unable to set the global scope with a value determined in the middleware.

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by egeriis** [comment]
I would like to present an argument for this being a bug.

Since middleware is documented as being a place to do authentication, I consider it a security issue in multi-tenant applications that database queries can be executed before this middleware.

I would love to do a PR, but I have too little experience in reading the Laravel codebase to figure out how to solve this. But I would be really disappointed if this issue is just left closed.
