### ISSUE TITLE
Using multiple middlewares in routes group

### ISSUE THREAD

**Issue by 3x14159265** [laravel/framework#8579]
according to the docs, it's possible to use multiple middlewares on a route group

```
Route::group(['middleware' => 'foo|bar'], function()
{
    Route::get('/', function()
    {
        // Has Foo And Bar Middleware
    });
});
```

but in fact, if I try that (with middlewares: ``` 'cors|auth' ```), I get following error:

```[2015-04-27 19:37:10] local.ERROR: exception 'ReflectionException' with message 'Class cors|auth does not exist' in /home/vagrant/Code/oratio-phoenix/vendor/laravel/framework/src/Illuminate/Container/Container.php:776```

The middleware itself works, since I tested it without ```|auth```. Please have a look into it or fix the docs.

**Comment by lukasgeiter** [comment]
The correct way is to pass it as array:

    Route::group(['middleware' => ['foo','bar']], function()

I'll send a PR to change the docs...
