### ISSUE TITLE
[L5] Mailgun API Url

### ISSUE THREAD

**Issue by mikeshawdev** [laravel/framework#8585]
Mailgun is now using v3 of their API, however you can't change the API URL without changing the Laravel source. The new API base URL appears to be 'https://api.mailgun.net/v3/{domain}'

Anyone trying to use the API with new Mailgun setups will get a 404 response

Could we, maybe, introduce a way to change the API from `config/services.json` so it can be updated as users need? Maybe something like:

```php
return [
    'mailgun' => [
        'base_url' => 'https://api.mailgun.net/v3/{domain}',
        'domain' => env('MAIL_HOST'),
        'secret' => env('MAIL_SECRET')
    ]
];
```

Where `{domain}` is a placeholder which would offer flexibility for other URL structures (like the v2 base URL)

**Comment by GrahamCampbell** [comment]
Laravel 5.1 already uses the new URL.

**Comment by GrahamCampbell** [comment]
We haven't changed it on 5.0 to keep BC.

**Comment by mikeshawdev** [comment]
Ahh right, cheers Graham! Sorry, didn't realise!

**Comment by mikeshawdev** [comment]
I know this is closed now, but what did you think of the idea of using a URL with a placeholder for flexibility?
