### ISSUE TITLE
AuthenticatesAndRegistersUsers hardcoded error message

### ISSUE THREAD

**Issue by IsraelOrtuno** [laravel/framework#8592]
The trait `AuthenticatesAndRegistersUsers` helps a lot. However, the function that provides the error message when a user authentication attempt has failed is hardcoded:

```
protected function getFailedLoginMessage()
{
	return 'These credentials do not match our records.';
}
```
[See here](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Auth/AuthenticatesAndRegistersUsers.php#L96-L99)

This makes difficult to replace it in another language. 

An option would be an extra default language file and I am not sure how right is that for you guys.

I've also thought about registering a new language item straight from there. This way it could be easily replaced from language files but I am not sure if this is possible at all.

**Comment by GrahamCampbell** [comment]
You can easily override this method if you want.

**Comment by vermaboys** [comment]
I have solved this issue. Click https://github.com/vermaboys/change-error-message-of-login-laravel5.4
