### ISSUE TITLE
Container singleton doesn't respect arguments

### ISSUE THREAD

**Issue by ecstasis** [laravel/framework#8593]
Registering a singleton with arguments results in having the same singleton for different arguments
```php
App::singleton('logger', function ($container, $type = 'default') { return new Logger($type); });
App::make('logger', 'default'); // creates a new instance
App::make('logger', 'default'); // returns the same singleton - OK
App::make('logger', 'another'); // returns the same singleton - confusing?
```
Obviously if I call a function with a different argument, I expect a different result. 
I this case I would expect a different singleton for each set of arguments.

**Comment by franzliedke** [comment]
`App::bind()` should not create singletons at all!?

**Comment by ecstasis** [comment]
Apologies, I meant singleton(). Code above edited.
Thanks, @franzliedke

**Comment by lukasgeiter** [comment]
I think by definition, singletons shouldn't even receive constructor arguments...
Do you really need a shared object?

**Comment by GrahamCampbell** [comment]
You can't bind classes with arguments to the closure like that. That makes no sense?

**Comment by ecstasis** [comment]
I can.
It does make sense for me.
This functionality probably is there for a reason?
