### ISSUE TITLE
Blade compilation error with 'or' present in function parameters

### ISSUE THREAD

**Issue by dolbex** [laravel/framework#8595]
Take into account the following scenario:

```
$blog('durka or foo')
```

Which will compile down to:

```
<?php echo e(isset($blog('durka) ? $blog('durka : foo')); ?>
```

We tried to change up the compileEchoDefaults method in BladeCompiler.php line 332 but just couldn't quite figure out the RegEx. Something to consider though: I'm not quite sure we want to search exclusively for 'or's only when a variable is present. What about a constant? Maybe you can remove that portion all together? I think as long as the 'or' doesn't appear within double or single quotes it will achieve what we are looking for.

http://regexr.com/3atjr

**Comment by GrahamCampbell** [comment]
This issue was raised before but was marked as "nofix". If you can come up with a clean solution, I'm sure Taylor would be interested though. :)
