### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by Displee** [laravel/framework#8600]
Is it an idea to let the database format the dates when the framework retrieves all date/datetime columns for a model, database date formatting is going way faster than server sided formatting. This would really help me.

For example:
In the Eloquent class set a variable with a default date/datetime format.
Then we can override that variable in the actual model.

**Comment by Sladewill** [comment]
In doing so though this would remove the timezone functionality which carbon provides. Another way of doing it that doesn't break everything people currently have would be possible though.

**Comment by mondss** [comment]
Why would it help you? Would moving any logic from the framework to the data access layer really improve speeds? 

If you want to change the timezone that is stored you can just change it in config/app.php.

**Comment by Displee** [comment]
Changing the timezone wont affect any date's/datetime's from it's format, at least not for stored dates/datetime's in the database. At this moment I am having 20+ stored dates in my database, and I have to format them all via PHP to get the output I want. These 20 dates are being used on a lot of places, It would be much easier to let the database format it. So yes, I think this would improve the speed. Why would I use a whole library if the database can do it. I know this is possible without messing up other people's work, so please, think about it.

**Comment by lukasgeiter** [comment]
@Displee You should be able to do that with a few custom scopes and `select()`.
