### ISSUE TITLE
homestead and laravel

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#8613]
I'm only posting these issues here because you cannot open issues on homestead, but I can imagine it's common for laravel users.

I'm writing multiple microservices, and I want each service (running on laravel) to come up online, and each image to have a specific provisioning configuraiton.

For example, I want my first homestead environment to have rabbitmq installed on it, but not the second one.

I can see there is a ~./homestead/after.sh, where you can run your own addition commands to install and whatever you want to do. But this global to all images, I want to be specific to one image.

How do I achieve that? In homestead.

**Comment by Sladewill** [comment]
I think you'd be better off asking on the forums http://laravel.io/forum
