### ISSUE TITLE
Type hinting optional parameters goes to wrong parameter

### ISSUE THREAD

**Issue by claar** [laravel/framework#8617]
If you type-hint only the 2nd parameter of a controller method having two optional parameters, Laravel sends the type-hinted object to the first parameter instead.

## To Reproduce
* In a fresh 5.0/5.1 install, create a WelcomeController@index method like:
```php
public function index($foo=null, \App\User $user=null)
{
    dd(['foo' => $foo, 'user' => $user]);
}
```
* Visit your fresh L5 website.

## Expected result
$foo is null, $user is an \App\User object

## Actual result
$foo is an \App\User object, $user is null

**Comment by TheShiftExchange** [comment]
That is expected behaviour in routes. You cant "skip" an optional parameter.

How does Laravel know that if you have `domain.com/index/1` you are saying `1` is the User? It is logical that is assigns it to `foo`.

**Comment by claar** [comment]
@TheShiftExchange I guess I wasn't clear. I didn't visit domain.com/index/1, I visited domain.com/index

I didn't skip a parameter. I gave zero parameters, and Laravel "helpfully" assigned a User object to $foo. 

@GrahamCampbell Could you please reopen this ticket until someone at least comments on the actual problem?

**Comment by brunogaspar** [comment]
From the docs http://laravel.com/docs/5.0/controllers#dependency-injection-and-controllers

> If your controller method is also expecting input from a route parameter, simply list your route arguments after your other dependencies

So AFAIK, there's no bug here, you just need to make sure you define the arguments in the correct order as kinda stated on the documentation.

**Comment by claar** [comment]
@brunogaspar Yeah, I agree with your interpretation.

Where this bit me was upgrading from Laravel 4 to 5 in an application that heavily used Route Model Binding. I had a bunch of routes like:

```php
Route::model('projectId', Project::class);
Route::get('dashboard/{which?}/project/{projectId?}', ['uses' => 'ProjectController@dashboard']);
// in ProjectController:
function dashboard($which=null, Project $projectId=null) {}
```

After upgrading to Laravel 5, all such routes broke if the parameters were omitted, because `$which` would unexpectedly be a `Project` object. Simply removing the typehinting fixed it, but it was certainly confusing behavior.

**Comment by herzcthu** [comment]
Kind of a hack for this issue.

`    public function index($project_id, $samplable = null, SurveyResultDataTable $resultDataTable = null) {
            $project = $this->projectRepository->findWithoutFail($project_id);
            $resultDataTable = ($resultDataTable)?$resultDataTable:($samplable instanceof SurveyResultDataTable)?$samplable:null;
            return $resultDataTable->render('projects.index');
    }`

**Comment by patrikniebur** [comment]
I'm having the same problem, anyone cad advise if it's a bug or intended behavior? Thanks

**Comment by claar** [comment]
@patrikniebur Intended behavior. The Laravel 5 type hinting is used for constructor injection. You have to update (in my case, remove) the type hinting on your affected controllers to fix.
