### ISSUE TITLE
[Proposal] Allow belongsTo association by primary ID

### ISSUE THREAD

**Issue by ghunti** [laravel/framework#8618]
Currently to create an association between two models in a (one-to-many) relationship we need to create an instance of the "one side" model and pass it to the ```associate()``` method:
```
$comment = new Comment();
$post = Post::find($id);
//do validations
$comment->post()->associate($post);
```
On the other hand, when creation associations of a "many-to-many" relations we need to pass the ids instead of concrete instances of the models:
```
$user = new User();
$user->roles()->attach(1);
//or
$user->roles()->sync(array(1, 2, 3));
```

My proposal is to create an ```associateById()``` method to pass the id directly instead of a concrete model.
If we look at the post/comments example, if we were to have on the validations:
```
return array(
            'post' => array(
                'exists:posts,id',
            ),
        );
```
at the Controller we would fetch the post to create a concrete Model and pass it to the ```associate()``` method and we would also check if the Post exists on the database.
If we don't need to instantiate the Model then only one query would be performed.

I haven't provided a patch, because ```Illuminate\Database\Eloquent\Relations\BelongsTo::associate()``` sets the relation on the parent model and I'm not sure where this "relations" can be used (besides the ```push()``` method that only makes sense when all the models don't exist yet on the database).

Thanks

**Comment by dwightwatson** [comment]
Surely `associate()` could just determine whether the parameter passed to it is an integer or an Eloquent object and go from there?

**Comment by Sladewill** [comment]
I agree with the idea of making a new function or making it so it can detect the type, as currently the way to do this is rather tedious, so you would set the models id.

```php
<?php
$model = new Model;
$model->associated_id = 1;
$model->save();
?>
```

Or you have to unguard the column to make it changeable via ->update.

The majority of use cases of setting a relation to another model is via a select which would have the other models ID so it would certainly make it easier.

**Comment by GrahamCampbell** [comment]
Closing as the PR was merged. :)

**Comment by gqueiros** [comment]
Nice, thanks :-)

**Comment by ghunti** [comment]
Nice, thanks :-)
