### ISSUE TITLE
Request::flash() should not be called statically

### ISSUE THREAD

**Issue by syphernl** [laravel/framework#8626]
The [documentation of Requests](http://laravel.com/docs/5.0/requests#old-input) contains a method:
```
Request::flash();
```

But if you call this from a controller in L5 it results in an exception being thrown:
```
Non-static method Illuminate\Http\Request::flash() should not be called statically, assuming $this from incompatible context 
```

**Comment by lukasgeiter** [comment]
You are using the wrong `Request` class. Instead of importing `Illuminate\Http\Request` you should add either:

    use Request; // global alias

Or

    use Illuminate\Support\Facades\Request;

**Comment by GrahamCampbell** [comment]
Or, you can dependency inject `Illuminate\Http\Request`, and call that method on the object. :)
