### ISSUE TITLE
[4.2]relation query error when the table name is `user` with PostgreSQL

### ISSUE THREAD

**Issue by Gwill** [laravel/framework#8631]
`user` is a reserved word in Postgres, and when the Eloquent generate the SQL codes include `user` named table, there is no quotation mark. so the query make error.

**Comment by lukasgeiter** [comment]
Usually the query builder escapes everything so this doesn't happen. Can you please add your code and the resulting SQL query?

**Comment by GrahamCampbell** [comment]
4.2 not supported
