### ISSUE TITLE
Eloquent: rounded float values

### ISSUE THREAD

**Issue by PhillippOhlandt** [laravel/framework#8636]
Hey,

I have an existing database with float fields at some tables. When I return Model::first() the float values were rounded. 2.95 -> 3.
Casting it to float or float(10,2) with the $casts attribute within the model doesn't solve the problem.

**Comment by lukasgeiter** [comment]
What kind of database are you using? MySQL, PostgreSQL, etc ?

**Comment by PhillippOhlandt** [comment]
MySQL with utf8_general_ci

**Comment by lukasgeiter** [comment]
I couldn't reproduce this bug. It might be a driver problem or something like that...

**Comment by PhillippOhlandt** [comment]
I use the lokal php development server on php 5.6.3 and mysql from one of the latest xampp releases. I'll check that on the production server.
