### ISSUE TITLE
artisan optimize & composer vendor-dir

### ISSUE THREAD

**Issue by Broutard** [laravel/framework#8637]
Hi,

We have more than 100 websites in my company, so we don't want to duplicate the vendor directory each time.
So composer.json use a config like that : 
```
"config": {
   "vendor-dir": "../library/vendor"
}
```

The "vendor" directory is out of the websites structure.

But when I try to execute "php artisan optimize", it failed with this error : 
```
 [InvalidArgumentException]
  Configuration file "/home/seb/www/site1/,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,/home/seb/www/site1/app/Providers/AppServiceProvider.php,/home/seb/www/site1/app/Providers/BusServiceProvider.php,/home/seb/www/site1/app/Providers/ConfigServicePr
  ovider.php,/home/seb/www/site1/app/Providers/EventServiceProvider.php,/home/seb/www/site1/app/Providers/RouteServiceProvider.php" does not exist.
```

In fact, the optimize command use a config file (config.php) in which the vendor dir is inevitably under the website basePath :
```
$basePath = $app['path.base'];

return array_map('realpath', array(
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Container/Container.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Container/ContextualBindingBuilder.php',
    $basePath.'/vendor/laravel/framework/src/Illuminate/Contracts/Foundation/Application.php',
[...]
```

**Comment by lukasgeiter** [comment]
Just so you know, the most important thing that `artisan optimize` does, creating optimized autoload files, can be achieved with composer itself:

    composer dump-autoload -o

**Comment by Anahkiasen** [comment]
> Just so you know, the most important thing that artisan optimize does, creating optimized autoload files, can be achieved with composer itself:

That's already [what it does](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/OptimizeCommand.php#L59)

**Comment by Broutard** [comment]
```artisan optimize``` also generate a complied.php file with the entire framework.

**Comment by lukasgeiter** [comment]
It's not the entire framework, just often used classes. I didn't say this was the solution to your problem. Just wanted to make sure you are aware of this and might want to use it as "workaround"...

**Comment by Broutard** [comment]
Thanks but I also want to compil common classes.

**Comment by nuhh** [comment]
You should ```artisan optimize --force``` to create complied file

**Comment by Broutard** [comment]
I already use --force ! But is not the issue.

```vendor``` folder is still nested into $app['path.base']

**Comment by AaronJan** [comment]
I had this problem too.

We have a lots applications,we only want to have one common `vendor` directory like you do.

Like you said, the `config.php` had the `path` written pretty solid, the `basePath` is absolutely unchangeable.

I don't want to change the framework code, it will causing problems when I run update, `ln -s` may confuse `composer` I think, and it's ugly.

I figure rewrite a compile console command is a way. Any good thought?
