### ISSUE TITLE
Support/Collection constructor misbehave?

### ISSUE THREAD

**Issue by andizzle** [laravel/framework#8638]
Current Collection constructor https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/Collection.php#L28 converts the input to an array.

    $a = new Model;
    $c = new Collection($a);
    // now what's in $c is an array instead of a model instance

Is this intended this way? If it is then `$c->push($a)` and `$c->prepend($a)` should produce the same result.

Additionally, I don't quite get why `getArrayableItems()` has to convert none Collection items to an Array.

**Comment by Sladewill** [comment]
That seems intentional if you want to keep it in the model format push it like

```php
<?php
$a = new Model;
$c = new Collection(['model' => $a]);
?>
```

**Comment by andizzle** [comment]
@Sladewill Thanks, make sense.
