### ISSUE TITLE
Redirect all traffic to http://www.domain.com and not to http://domain.com

### ISSUE THREAD

**Issue by Advil-Robin** [laravel/framework#8640]
Hi,

I want to set all my traffic to www. So, I have the domain name http://www.rallypodium.tk/ but, when someone enters my site like http://rallypodium.tk they can't do much, and I want to have all the traffic over the www. So I don't want a 'naked' domain. How can I do this?

**Comment by brunogaspar** [comment]
Since this is not related to the framework, why don't you use [Google](http://lmgtfy.com/?q=htaccess+redirect+to+www+domain) to figure it out?
