### ISSUE TITLE
Correct way to dispatch a new request inside the application and dealing with Request injection afterward

### ISSUE THREAD

**Issue by elpd** [laravel/framework#8641]
Hello. 
I am dealing with a restful api. Each controller deals with one type of object. Now the wish is to update children of main object also. Currently I can't separate that call on the front side to several api calls on the children controllers so I decided to do it on the server side. 

After a while I ended up with creating a new request based on the original request with modifications. 

```php
$server = $request->server();
$server['REQUEST_URI'] = $child_route_url;

$childRequest = $request->duplicate(null, $child_input, null, null, null, $server);
$childRequest->initialize(        
            [], //query           
            $child_input,  // request            
            [], // attributes           
            $request->cookie(),  // cookies           
            [],  // files           
            $server,  // server           
            null  // content
);

\Route::dispatch($child_request);
```

This worked fine util we get to the child controller. The child controller is injected with the request in the update method by the injector. Instead of injecting the new child request, the original request was injected. 

To solve this, I manually set the injector instance for the 'request' before dispatching. 

```php
$app->instance('request', $child_request);
\Route::dispatch($child_request);
````

I was wondering if there was a more proper way to deal with this and also maybe this is suppose to happen in the dispatch method of the framework and I am missing something.

**Comment by GrahamCampbell** [comment]
Please ask on the forums. We can't process questions like this here, sorry.
