### ISSUE TITLE
[proposal] dd should exit with status 1

### ISSUE THREAD

**Issue by mrgrain** [laravel/framework#8646]
Hi community,

I stumbled a about an issue with the `dd` helper function today. Short version: A script depending on phpunit got stuck in the wrong state, because phpunit terminated with success due to a forgotten `dd`, which exits with status code 0.

Obviously the mistake was made somewhere else, and there are numerous ways to prevent `dd` from being committed to a VCS at all. But it made me thinking about the current implementation of `dd`:

__Should we regard an early abortion as a successful execution of the program or rather not?__

On the one hand, the termination is intended by the developer and will exactly result in what is expected. But on the other hand, `dd` is only supposed to be used in debugging. It will interrupt the current execution and might even break the HTML of the response. Especially viewing at it on a programmatic level, I reckon a `dd` would not be regarded as successful execution in 99.9% of the cases.

I'm very keen to hear your opinions about this. From my current point of view, I would suggest changing `dd`'s exit code to 1.

__Update:__ (2015-05-11) Thank you for the feedback so far. It seems, this would be a welcome change. I updated the title to a more 'demanding' one and I'll also advance this issue by creating a pull request and some test examples.

**Comment by franzliedke** [comment]
Sounds sensible.

**Comment by rizqidjamaluddin** [comment]
I'm inclined to support this purely from a practical standpoint; an errant `dd()` is usually a mistake, and should be detected by CI or other automated processes.

**Comment by dwightwatson** [comment]
Yeah, we actually had a `dd()` in sitting in our tests which was cancelling our test suite about half way through. Our CI never had an issue with it, wasn't until one of us actually looked up the output and saw the mistake.

I'd be in favour of this change.

**Comment by mrgrain** [comment]
Thank you for the feedback so far. It seems, this would be a welcome change. I updated the title to a more 'demanding' one and I'll also advance this issue by creating a pull request and some test examples.
