### ISSUE TITLE
Log not correct write

### ISSUE THREAD

**Issue by 2byte** [laravel/framework#8649]
Run
```
Log::info('Line1');
```
Result is ok
```
[2015-05-07 11:23:34] local.INFO: Line1  
```
Run 2
```
Log::info('Line2');
```
Result https://yadi.sk/i/Tw-tFufggUar5
Run 3
```
Log::info('Line3');
```
Result https://yadi.sk/i/866DBtf9gUatd

and so on

**Comment by GrahamCampbell** [comment]
Looks like an issue with monolog. Ask them. :)
