### ISSUE TITLE
[ 5.0 ] [ LengthAwarePaginator ] Do not limit the results

### ISSUE THREAD

**Issue by ChristianGiupponi** [laravel/framework#8651]
I have an eloquent scope that need to use `sortBy` so, as the doc says, I have created a new instance of `LengthAwarePaginator` to paginate the result:

Image.php
~~~
public function voti()
    {
        return $this->hasMany( 'App\Vote' );
    }

 public function scopePiuVotate( $query )
    {
        return $query->with( 'voti' )->get()->sortBy( function ( $sort )
        {
            return $sort->voti->count();
        }, 0, true );
    }
~~~

Controller:
~~~
$images = \App\Image::piuVotate();
$items = new \Illuminate\Pagination\LengthAwarePaginator($images, $images->count(), 5);
~~~

View:
~~~
@foreach( $items as $item )
        {{ $item->name }}<br>
@endforeach

{!! $items->render() !!}
~~~

The problem is that the pagination works but the `$items` contains always all the images and not the subset of 5 setted in the `LengthAwarePaginator`.

Can anyone try to replicate the issue?

**Comment by RDelorier** [comment]
I  don't think scope are intended to actually call get(), at that point you already have all the records and your sorting the result set.

try removing the get and changing the sortBy to and orderBy, then you can do 
\App\Image::piuVotate()->paginate(5)

take a look at the Illuminate\Database\Eloquent\Builder paginate function. it tells the query which page to use which your scope is not doing

**Comment by GrahamCampbell** [comment]
Ask on the forums please.

**Comment by ChristianGiupponi** [comment]
@GrahamCampbell mine was not a request about how to fix my code but just to understand if this is the correct behaviour of `LengthAwarePaginator`. 
The code was just an example to show what I did to get that result.

**Comment by ilikourou** [comment]
Hello.

I have the same question as @ChristianGiupponi 

In class **LengthAwarePaginator**, `$items` contains all the items of the collection, whereas in Class **Paginator**, `$items` contains only the items of the specific page.

Having a look at the constructor of class Paginator, method **checkForMorePages()** is called at the end, and this method sets the limit to the `$items` var:

```
protected function checkForMorePages()
{
    $this->hasMore = count($this->items) > ($this->perPage);
    $this->items = $this->items->slice(0, $this->perPage);
}
```

So, my question is, isn't it the way **LengthAwarePaginator** should also behave?

**Comment by skfahad** [comment]
@ChristianGiupponi  and @ilikourou  even I'm wondering why **LengthAwarePaginator** doesn't slice the data itself but looks like we have to take the burden of slicing the data to get limited number of items per page.

[kindly check this answer](https://stackoverflow.com/a/66318882/4494813  )
