### ISSUE TITLE
laravel 5 artisan tinker namespace issue

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#8655]
I have a class called SendEmail as a command bus. Following this example here

http://laravel.com/docs/5.0/queues#configuration

When I go into artisan tinker and I try to instantiate the SendEmail, it's not found.

```sh
Psy Shell v0.4.4 (PHP 5.4.36 — cli) by Justin Hileman
>>> use App\Commands;
=> false
>>> $email = new SendEmail();
PHP Fatal error:  Class 'SendEmail' not found in eval()'d code on line 1
```

pourquoi?

**Comment by GrahamCampbell** [comment]
you need `use App\Commands\SendEmail`

**Comment by BardiaAfshin** [comment]
fixed

**Comment by saiful912** [comment]
yes, thanks bro..

**Comment by renggamaulana** [comment]
> you need `use App\Commands\SendEmail`

so, we also use this when make using create method in tinker? => 'use App\Commands\SendEmail::create([])' ?
bcs i got same error when using create mehod just using the class name.
