### ISSUE TITLE
Wildcard on contextual binding?

### ISSUE THREAD

**Issue by gabriellimo** [laravel/framework#8660]
Im trying to learn and build something with laravel. In my app I use multiple interchangeable third-party APIs to get some data. I have some interfaces that the classes from my app implements. At the moment Im doing like this:

    $this->app->when('App\DataSources\Youtube\YoutubeRequester')
            ->needs('App\DataSources\Contracts\ApiManagerInterface')
            ->give('App\DataSources\Youtube\YoutubeApiManager');
I was wondering, it would be nice if I could do something like this:

    $this->app->when('App\DataSources\{ApiName}\{ApiName}Requester')
            ->needs('App\DataSources\Contracts\ApiManagerInterface')
            ->give('App\DataSources\{ApiName}\{ApiName}ApiManager');
It would prevent me from violate DRY principle. Is there any way of doing such a thing?

**Comment by lukasgeiter** [comment]
You could just create the bindings inside a loop...
(I know that's not exactly what you wanted, but it cleans it up a bit)

Like:

    $apis = ['Youtube', 'Foo', 'Bar'];

    foreach($apis as $api){
        $this->app->when('App\DataSources\'.$api.'\'.$api.'Requester')
                         ->needs('App\DataSources\Contracts\ApiManagerInterface')
                         ->give('App\DataSources\'.$api.'\'.$api.'ApiManager');
    }
