### ISSUE TITLE
[L4.2] Lock down boris dependency

### ISSUE THREAD

**Issue by spescina** [laravel/framework#8663]
Please lock down the boris dependency. Since v1.0.9 boris requires some php extensions that are not present in some hosting (webfaction). I can install laravel 4.2.* using composer install --ignore-platform-reqs but I think you could lock the dedpendency down.
Thanks.

**Comment by GrahamCampbell** [comment]
Duplicate. Locking it down is a bad idea. That's just meaning we're forcing people onto an old version with bugs in. it's a bug that you're able to install it without the extensions. That's why we ditched it in L5.
