### ISSUE TITLE
Automatically cast dates will always turn up dirty in an Eloquent model

### ISSUE THREAD

**Issue by Flightfreak** [laravel/framework#8666]
Consider an existing model which has the eloquent dates attribute filled.
Set an identical date value (Ex. 'Y-m-d') on such a date field, the field will turn-up dirty.
This happens because the ```setAttribute``` method will create a Carbon object from this set date, which will return a grammar defined date format (Ex. 'Y-m-d H:i:s').

The ```getDiry``` method requires an ```originalIsNumericallyEquivalent``` equivalent for dates to handle this correctly.

**Comment by GrahamCampbell** [comment]
Hmmm, thanks for reporting.

**Comment by Flightfreak** [comment]
I can create a push and fix with tests for it but time is somewhat of an issue for the moment so it will probably take a while.

**Comment by GrahamCampbell** [comment]
Just fix on 5.0 please. We're not interested in putting bug fixes into L5.

**Comment by Flightfreak** [comment]
Ok, will reference this in the pull request.
