### ISSUE TITLE
laravel and bootstrap modal

### ISSUE THREAD

**Issue by hadiab** [laravel/framework#8668]
how i can delete or update in laravel with bootstrap modal 

this is my code

       @include('admin.partials.modal.delete-category-modal', ['record' => $category ])
       @foreach($categories as $category)
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">

                    {!! Form::open([ 'method' => 'DELETE', 'route' => ['category.destroy', 'id' => $category->id] ]) !!}
                        <div class="form-group">
                            {!! Form::button('&times;', ['type' => 'submit', 'class' => 'close pull-left', 'data-tagret' => '']) !!}
                        </div>
                    {!! Form::close() !!}

                    {{ $category->name }}
                    <small class="pull-right">#{{ $category->id }}</small>
                    <a id="-btn-space" class="btn btn-primary btn-xs pull-left" data-id="{{ $category->name }}" data-toggle="modal" data-target="#show-form{{ $record->id }}">edit</a>
                    <div class="clearfix"></div>
                </h4>
            </div>
        </div>
       @endforeach

**Comment by GrahamCampbell** [comment]
Ask on the forums or something.

**Comment by xeaneax** [comment]
hello what is &times; means btw?
