### ISSUE TITLE
belongsTo with different foreign key column not work after update to 5.0.30

### ISSUE THREAD

**Issue by yeknava** [laravel/framework#8671]
after update my project to 5.0.29 (and 5.0.30 also) my model with belongsTo relationship wont work and return error when associating.

my belongsTo method:

public function owner() {
	return $this->belongsTo('App\User', 'owner', 'id');
}

error say can not define $owner but even after i add public $owner; to Model its wont work also;

**Comment by taylorotwell** [comment]
Can you show us the exact query you are running. We need more code.

**Comment by yeknava** [comment]
after adding public $owner; to model its worked but still i think its a bug;

code:
```php
        $user = Auth::user();
		$project = new Project($request->all());
                $user->project()->save($project);
        $project = $project->owner()->associate($user);  //Error occured here
        if($project->save()) {
            $projectMember = $projectMember->user()->associate($user);
            $projectMember = $projectMember->project()->associate($project);
            if($projectMember->save()) {
                return 'success';
            }
        }
```

**Comment by taylorotwell** [comment]
I'm having trouble seeing how this would ever have worked. Your column and relation ship are sharing the same name "owner"... I would have never expected that to be supported at all. Because when you access $model->owner what is it supposed to return? The column value or the relationship?

**Comment by taylorotwell** [comment]
You need to not name your columns the same name as your relationship.

**Comment by yeknava** [comment]
i supposed column value, i named both same because when loading with eager loading i wanted some thing like this :
```
id: "11",
owner: {id:"1", username:"usertest"},
title: "test",
description: null,
avatar: null,
status: "0",
public: "1",
plan: "1",
expire_date: "0000-00-00 00:00:00",
created_at: "2015-05-08 21:06:10",
updated_at: "2015-05-08 21:06:10",
```
not this 
```
id: "11",
owner: null,
title: "2test2222",
description: null,
avatar: null,
status: "0",
public: "1",
plan: "1",
expire_date: "0000-00-00 00:00:00",
created_at: "2015-05-08 21:06:10",
updated_at: "2015-05-08 21:06:10",
user:{id:"1", username:"usertest"}
```

**Comment by RDelorier** [comment]
if you renamed owner column to owner_id with owner relationship as owner() and eager load like this:

$project = Project::with(['owner' => function($q){
    $q->addSelect(['id','username']);
}])->get();

i think you should see the results your looking for

**Comment by yeknava** [comment]
@RDelorier thanks i changed it in my code, i just report this because its worked before update.
