### ISSUE TITLE
PHPDoc autocomplete for Fluent while creating a migration

### ISSUE THREAD

**Issue by JorisDebonnet** [laravel/framework#8675]
Pull request #8506 was not approved because that solution only works for migrations, while Fluent is not only used for that. 

But how then can we avoid IDE warnings in migration files? Things like `$table->string('email')->unique();` throw them because the IDE (at least PhpStorm) can't find that `unique` method. It can be worked around by splitting it into two lines (as explained [here](http://stackoverflow.com/questions/29004347/phpstorm-9-eap-method-unique-not-found-in-class-illuminate-support-fluent#answer-29118215)), but that's just less than ideal. 

Perhaps it can be solved by creating a few minor class extensions, especially for migrations? After all, chained methods like `->unique()` and `->unsigned()` in migrations are so useful, it would be a shame if they don't show up in the IDE.

**Comment by JorisDebonnet** [comment]
Any comment as to why this was closed so quickly?... I'm just trying to open the discussion about how we can fix this issue, if not by that original pull request.

**Comment by sammarks** [comment]
I started a thread on the Laracasts forum about the PR you mention in your original post: https://laracasts.com/discuss/channels/laravel/phpdoc-autocomplete-for-fluent-creating-a-migration

One of the maintainers replied to the thread with an explanation as to why this isn't easily achievable.
