### ISSUE TITLE
$request->secure() returns false by handle in middleware

### ISSUE THREAD

**Issue by huoy** [laravel/framework#8680]
Basically identical issue as this one:

http://laravel.io/forum/06-22-2014-requestsecure-return-false-no-ssl-but-ssl-certificate-is-applied?page=1

I'm running nginx with fastcgi

**Comment by GrahamCampbell** [comment]
Never use `'HTTP_X_FORWARDED_PROTO'`. That's a crap idea.

You need to correctly set your trusted proxies, and symfony will automatically setup the request class correctly.

**Comment by huoy** [comment]
Actually ended up being a problem with nginx/fastcgi. Fastcgi doesn't/wasn't identifying itself so setting trusted proxy wouldn't work. Ended up with this solution: http://laravel.io/forum/05-09-2015-https-not-being-detected
