### ISSUE TITLE
Add support for PubNub event broadcast

### ISSUE THREAD

**Issue by cwt137** [laravel/framework#8684]
PubNub is a real-time, cloud based event system like Pusher. http://pubnub.com. It would be nice if Laravel supported this system as well

**Comment by cwt137** [comment]
I made some changes. Please reconsider.

**Comment by GrahamCampbell** [comment]
I've closed it because we don't need two issues. I've not rejected it. ;)

**Comment by cwt137** [comment]
I see, a pull request is an issue too, correct?
