### ISSUE TITLE
[4.2] How to observe Many to Many relation attach()/sync() action?

### ISSUE THREAD

**Issue by Gwill** [laravel/framework#8690]
How to observe Many to Many relation attach()/sync() action?

For this:
I have Tag model and Post model, their raletion is Many to Many. I want to $tag->count += 1 when Post attach() with a Tag.

How to do that?

**Comment by GrahamCampbell** [comment]
1. 4.2 is not supported anymore.
2. We don't process support requests here - ask on the forums.
