### ISSUE TITLE
Auth middleware broken in closure 

### ISSUE THREAD

**Issue by Thatplayer** [laravel/framework#8693]
A closure route with auth middleware gives an error 

```[2015-05-11 09:40:11] local.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in /home/vagrant/Code/Laravel/vendor/compiled.php:7315````

Seems to be broken from this commit 46203676c748ac3cdb4849e75e711ca9cb1ca118

**Comment by GrahamCampbell** [comment]
That commit has nothing to do with middelware.

**Comment by Thatplayer** [comment]
I think the name might be conflicting with the middleware. Reverting to 5.0.23 before that commit or removing that code the error for me, and I get the exact same error as #8419 in a fresh install of Laravel 5

```
Route::get('test', ["middleware" => "auth", function() {
    return "test";
}]);
```

**Comment by GrahamCampbell** [comment]
> I think the name might be conflicting with the middleware.

Nope, it's not.

**Comment by Thatplayer** [comment]
Okay, it is not the middleware, instead 

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Routing/Route.php#L607 is finding this auth function before it reaches the closure and attempts to use the Guard instead of the closure.

**Comment by GrahamCampbell** [comment]
Again, this has nothing to do with "auth" "function".

**Comment by Thatplayer** [comment]
Should I make a new issue then? 
```
Route::get('test', ["middleware" => "auth", function() {
    return "test";
}]);
```
or even the sample from the documentation
```
Route::get('admin/profile', ['middleware' => 'auth', function()
{
    //
}]);
```
Still doesn't work.

**Comment by GrahamCampbell** [comment]
I simply can't replicate this?

**Comment by Thatplayer** [comment]
I was able to replicate it in a fresh laravel install from the packagist once I ran composer update to use the latest framework.

**Comment by GrahamCampbell** [comment]
Could you give Taylor instructions for exactly how to replicate please?

**Comment by morganhein** [comment]
I am receiving the same exact error. Steps to reproduce:
* Create a new l5 project
* Set up auth (in my case against a DB, but doesn't matter)
* Create a route protected by auth that returns a closure
* Fail to profit
The issue lies on line 200 of Route.php. Specifically `runWithCustomDispatcher`, as it tries to unpack using:
```list($class, $method) = explode('@', $this->action['uses']);```
and since the closure has no @ symbol, it fails. I'm not sure if the actual bug is before this in the chain, and it's supposed to just execute the closure instead, but this is what's happening.

**Comment by Thatplayer** [comment]
The bug is that ```findCallable``` in Routes.php which finds the first callable in the values finds that ```"middleware" => "auth"``` is callable as ```is_callable("auth")``` is true and attempts to use that.

So there's a workaround by putting the closure before the middleware option.

**Comment by lukasgeiter** [comment]
I think checking if the key is numeric should fix this. Will send a PR soon...

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Comment by morganhein** [comment]
https://github.com/laravel/framework/pull/8700

This fixes it.

**Comment by GrahamCampbell** [comment]
Thanks.
