### ISSUE TITLE
License for Laravel

### ISSUE THREAD

**Issue by neomerx** [laravel/framework#8697]
How Laravel is licensed? I mean not framework which is licensed under MIT but default application laravel/laravel.

Same for Lumen.

**Comment by brunogaspar** [comment]
It's on the README.md (at the bottom).

**Comment by neomerx** [comment]
The readme is about framework not the default app.

**Comment by GrahamCampbell** [comment]
Both are MIT.

**Comment by neomerx** [comment]
@GrahamCampbell Where is it stated? Please reopen.
@taylorotwell  Can you please clarify how default Laravel/Lumen app are licensed? If it's MIT please add such statement to the project.
