### ISSUE TITLE
Laravel trying to repeat previous db record creation when I misstype a column name on a event listener

### ISSUE THREAD

**Issue by gabriellimo** [laravel/framework#8698]
Im still learning laravel. Right now, Im trying to use events. I have a route which does that:
```
Source::create(['name' => 'source1']);

        $id = Source::first()->id;
        Media::create([
            //array with data
        ]);

        $tags = [
                'php',
                'tag1',
                'dummytag'
        ];

        $media = Media::first();

        Event::fire(new MediaWasCreated($media, $tags));
```
In one of the listeners I inject a class that is responsible for creating posts with the given media. This is the method that the listener is calling:
```
    public function create(Media $media = null)
    {

        if (!($media === null))
            $this->setMedia($media);

        $this->throwsIfHasErrors();

        $parsedArray = $this->parseArray();

        return $this->db->table('posts')->insert($parsedArray);
    }
```
The last line is giving me an error.

I made a misstake on ```parseArray``` and it was returning a ```statu``` key, when it should be ```status``` (when I fix it, it works just fine). The problem is that I was not taking a ```column not found``` error. Instead, apparently, laravel was trying to create another instance of Source with the same name that I created earlier. I got this error:
```
Integrity constraint violation: 1062 Duplicate entry 'source1' for key 'sources_name_unique' (SQL: insert into `sources` (`name`) values (source1))
```
I removed the unique() constraint from the migration and then I got 2 rows with the same name. What am I doing wrong?

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
