### ISSUE TITLE
[Support] Missing dependency on Symfony Var Dumper component

### ISSUE THREAD

**Issue by brendo** [laravel/framework#8707]
I'm attempting to utilise `illuminate/database` outside of a traditional environment with a bit of guidance from [this Laracasts](https://laracasts.com/lessons/how-to-use-eloquent-outside-of-laravel#) episode. As part of the episode, @JeffreyWay talks about how the `dd()` function can be used because of `illuminate/support` component.

I actually found that as `illuminate/support` does not include the `symfony/var-dumper` dependency in the [composer file](https://github.com/illuminate/support/blob/master/composer.json#L17-L21), `dd` does not work.

To fix, I included the `symfony/var-dumper` component in my project's composer and everything worked smoothly once again.

Perhaps this should be added to the `illuminate/support` composer as well, either as a dependency or a suggestion?

**Comment by lukasgeiter** [comment]
Already rejected: #8632

**Comment by GrahamCampbell** [comment]
@brendo Please actually read the list of suggested packages gives to you on install...

**Comment by GrahamCampbell** [comment]
Turns out we screwed up - it was missing from the suggest block. So sorry about thus guys!
