### ISSUE TITLE
make:seeder command

### ISSUE THREAD

**Issue by wayneashleyberry** [laravel/framework#8709]
Is there any reason you can pretty much `php artisan make` anything except a seeder?

**Comment by GrahamCampbell** [comment]
I guess because you only have one database seeder.

**Comment by JeffreyWay** [comment]
Well you can have as many seeder classes as you require... 

It would make sense to have one. It's one of the few Laravel-specific classes that I manually create each time.

**Comment by lukasgeiter** [comment]
@GrahamCampbell You usually have one seeder that calls the specific seeders for each table.

**Comment by agentphoenix** [comment]
:+1: for a `make:seed` command

**Comment by BrianDillingham** [comment]
+1 I think "why no make:seed" almost every time I make seeders.
