### ISSUE TITLE
Artisan db:seed --class doesn't add all data for models with fillable / guarded columns

### ISSUE THREAD

**Issue by davestewart** [laravel/framework#8714]
The simple simple solution would be to add Model::unguard() somewhere in the calling code, so just calling a specific database seeded works without having to add Model::unguard to each seeder

**Comment by dwightwatson** [comment]
The default master seeder file called `Model::unguard()` before you call any of your seeders: [DatabaseSeeder.php](https://github.com/laravel/laravel/blob/master/database/seeds/DatabaseSeeder.php). You must have removed it from your seeder.

**Comment by lukasgeiter** [comment]
@dwightwatson The question is about calling the command with the `--class` option. So `DatabaseSeeder` is never even called.

The problem I see with unguarding somewhere in the command is that the developer then can't really control if he wants to unguard or not (unless by calling `Model::reguard()`).
I think you should be able to create your custom Seeder base class and call `Model::unguard()` in the constructor to solve this issue for you.

**Comment by davestewart** [comment]
Just seems a bit pointless though, as Seeding a database:

 - it's *far* more likely that you would want to unguard your model than guard it
 - the code is your own, so no security risks
 - if you want to populate a column, you put that in the code, if you don't, you don't

Having to explicitly add in ungaurd to a class, just in case you want to run it again, seems a bit odd

Perhaps another command line switch ?

**Comment by GrahamCampbell** [comment]
Our current implementation makes perfect sense and there are no plans to change it. Sorry.

**Comment by davestewart** [comment]
Fair enough. FYI you spelled "yong developer of the year award" wrong
