### ISSUE TITLE
Get redirect loop when pass custom form request class into action

### ISSUE THREAD

**Issue by NovikovViktor** [laravel/framework#8716]
Hello, I try to display and handle my form using single action, so I allow GET and POST verbs to this action, and then pass custom request to the action, like `public function add(PostFormRequest $request)`, and I get redirect loop. When I remove PostFormRequest  from arguments all work fine, but not work validation, or when I remove GET verb I get `MethodNotAllowedHttpException`. So the question is how I can handle this? I need to create two separate actions for display and handling, or try to use `Validator` class?

**Comment by Rubemlrm** [comment]
can you share your current code ? maybe its easier and we can help =)

**Comment by lukasgeiter** [comment]
This is not the place for such questions or to get support for your problems. Github Issues are for Bug reports and feature requests. Please ask on the [forum](http://laravel.io/forum) or on other pages like StackOverflow.

**Comment by NovikovViktor** [comment]
@lukasgeiter,  [here](http://stackoverflow.com/questions/30198491/getting-redirect-loop-when-pass-custom-request-type-into-action-laravel-5) question on StackOverflow, there is no answer. And in my humble opinion, if I cant handle and render form using single action, usign custom FormRequest, it something wrong goes inside framework. But if using two actions for display and handle form ([here](http://stackoverflow.com/questions/30298336/handle-form-submission-laravel-5/30298913#30298913)  on StackOverflow) is Laravel way I have nothing against... but it need to be better discribed in the docs.
