### ISSUE TITLE
HasOne Through as an Eloquent relationship

### ISSUE THREAD

**Issue by dwightwatson** [laravel/framework#8721]
I'd like to suggest that we add `hasOneThrough()` as an additional Eloquent relationship. I'll use the example of the [hasManyThrough()](http://laravel.com/docs/5.0/eloquent#has-many-through) relationship to explain the use case. You can use the `hasManyThrough()` relationship to get the posts of a country. A `hasOneThrough()` relationship would allow you to get the country of a post.

    class Post extends Model
    {
        public function country()
        {
            return $this->hasOneThrough('App\Country', 'App\User');
        }
    }

This effectively allows inverse transversal of the relationship between the chain of models. This relationship exists in Rails, and I've supplied the SQL statement used by ActiveRecord to fetch the country from a post model.

    SELECT  "countries".* FROM "countries" INNER JOIN "users" ON "countries"."id" = "users"."country_id" WHERE "users"."id" = ? LIMIT 1

**Comment by ChangePlaces** [comment]
Maybe I'm misunderstanding - why not use a ```getCountryAttribute``` and ```return $this->user->country```?

**Comment by dwightwatson** [comment]
Because that's abusing attributes to work like relations. You can't eager load it, you can't query it and you can't assign it.

**Comment by keevitaja** [comment]
+1

**Comment by IVIR3zaM** [comment]
+1

**Comment by djtarazona** [comment]
+1

I could definitely use this.

**Comment by samuel-cloete** [comment]
+1

**Comment by EricWVGG** [comment]
+1

**Comment by ovp87** [comment]
+1

**Comment by Sirlazer2** [comment]
+1

**Comment by brandfocus** [comment]
+1

**Comment by GrahamCampbell** [comment]
Please don't :+1: issues. It doesn't really help anyone. Sending a PR would help, adding a +1 does not.

**Comment by GrahamCampbell** [comment]
Thanks for the report, but we don't process feature requests. We are, however, open to PRs.

**Comment by nejtr0n** [comment]
+1

**Comment by Barbery** [comment]
+1
