### ISSUE TITLE
A possible bug in Cookie with domain

### ISSUE THREAD

**Issue by littlewish** [laravel/framework#8723]
HI:

For example,There is a website,domain is "test.ab.com".

The Cookie like this:
{"key":"test1",“value”:"test1","domain":".ab.com"}
{"key":"test2",“value”:"test2","domain":"test.ab.com"}

when I use "$request->cookie()",get this:
["test1"=>NULL,"test2"=>"test2"]

But,when I use "$_COOKIE" , get this:
["test1"=>"test1","test2"=>"test2"]
It's right

Is there anything wrong?

If it is not a problem,how should i configure?

Thanks

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
