### ISSUE TITLE
add method Event::ignore($listener);

### ISSUE THREAD

**Issue by leemason** [laravel/framework#8725]
the event system is great, however there is no way to dynamically remove a listners from an event on the dispatcher.

this leads to any dynamic application needing to either fire another event within an event to determine if it should continue, or using db based settings and doing an if true check.

for example say i have a RegisterNewUser command, which then fires a UserWasRegistered event.

my application has email verification/activation implemented, so i have a SendActivationEmail event handler which sets the activation code on the user and sends the activation email.

for reference the email contains the code and a url the user can visit to then activate by the token.

nice and simple really.

HOWEVER.

say im building an admin area for this app now, and i want to be able to manually register users, AND check a box to NOT send an activation email (as i know there email is correct).

currently the only way i can do it is store a true/false value in persistent storage to determine if the activation email should be fire.

for example:

"update settings set value 'false' where 'key' = 'activation_email';"//disable email
$this->dispatch(new RegisterNewUser($data));
//user registered event gets fired in the background - checking for true/false value in the db or other persistent storage
"update settings set value 'true' where 'key' = 'activation_email';"//re-enable email

it would be much more fluent to have something like this:

Event::ignore('UserWasRegistered', 'SendActivationEmail');
$this->dispatch(new RegisterNewUser($data));
Event::listen('UserWasRegistered', 'SendActivationEmail');

the benefits are no true/false checks, no persistance data needed, and it allows other listeners attached to the event to continue without disabling the event all together by returning false.

Might not be the best example but im sure this would make the event system so much more flexible.

**Comment by GrahamCampbell** [comment]
Hmmm, I think this is intended in the design, as event handlers don't have to be classes, they can be closures too.

**Comment by ahmadmughal0312** [comment]
Please add this feature i really need it i am search from 2 days to solve this kid of problem
