### ISSUE TITLE
Database Schema Builder - onDelete when using MySQL

### ISSUE THREAD

**Issue by florx** [laravel/framework#8730]
When using the MySQL driver, the `onDelete('cascade')` function take effect unless we use:

    $table->engine = 'InnoDB' 

For reference I have tested this using the latest version of HomeStead and Laravel 5.

Please see: http://stackoverflow.com/questions/24897300/laravel-foreign-key-ondeletecascade-not-working

**Comment by yasinkocak** [comment]
How do you have your scheme ?

This how u use foreign keys: http://laravel.com/docs/5.0/schema#foreign-keys
This how u set your db engines: http://laravel.com/docs/5.0/schema#storage-engines

**Comment by jtraub** [comment]
This is not a bug. 

MyISAM is a default storage engine in MySQL 5.5.4 or older unless you change it in `my.cnf` or using a special command-line option during server startup. The engine doesn't support foreign keys, thus it won't perform cascading deletes.

So you need to either use newer version of MySQL or edit your MySQL setting or clearly indicate in a migration, that you want to use `InnoDB` as a storage engine.

**Comment by florx** [comment]
Shouldn't the framework automatically set the engine to InnoDB if you're trying to use a feature that's not in the engine that's default for your MySQL instance? Unless you've specifically asked it for a different engine, in which case an exception?
