### ISSUE TITLE
Eloquent push not saving related models

### ISSUE THREAD

**Issue by skyzer** [laravel/framework#8731]
Laravel Framework version 4.2.17

At some point my model->push() stopped updating relations and now my DB is messed up because of this.

Here is what I have:

```
class UserAccount extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

// $table, $fillable, $hidden

    public function address()
    {
        return $this->hasOne('UserAddress');
    }

}
```

```
class UserAddress extends Eloquent
{
 // $table, $fillable
    public function userAccount()
    {
        return $this->belongsTo( 'UserAccount' );
    }
}
```

How I'm saving in my controller:

```
    public function postUpdate() {

...
        $user = $this->user; // injection in constructor

	    $location_id = Input::get('location_id');

	    $user->address->location_id     = e(Input::get('location_id'));

	    $user->push();
        return Redirect::to( 'settings' )->with( 'flash_success', 'Your profile has been updated successfully' );
    }
```

I don't know at which point in time it stopped working, but now the relation UserAddress is not saved when i change anything. View in debugger $this->user has relations attribute with `address` as `UserAcccount` type. Why is this happening?

**Comment by Sladewill** [comment]
laravel 4.2 isnt supported anymore, try the forums.

**Comment by goethewins** [comment]
I am having the same problem and no one has any idea.
Plenty of folks still on 4.2 and will be for sometime. we REALLY REALLY need some help here.

**Comment by Lidbetter** [comment]
Does anyone have an example of how to reproduce this bug?

**Comment by Sladewill** [comment]
```php
$address = $user->address;
$address->location_id = e(Input::get('location_id'));;
$address->save();
```
