### ISSUE TITLE
RouteCollection match() doesn't handle directories so throws a 404 instead of 403

### ISSUE THREAD

**Issue by georgeescott** [laravel/framework#8732]
I'm currently working on an application where i want to have a custom 403 error page when a user tries to access a directory (such as `/css/`).

In homestead the current implementation is to show the default nginx 403 page and laravel doesn't do anything. I've added the `error_page 403 /;` directive to my `.conf` file in `/etc/nginx/sites-enabled` and laravel is returning the 404 error page instead of the 403 error view i created, however it returns an HTTP status code of 403.

In `/src/Illuminate/Routing/RouteCollection.php` the `match()` function only handles routes and not directories so I modified the match() function to include this at the top:
```
if (is_dir($request->path()))
{
    throw new AccessDeniedHttpException;
}
```

then obviously importing the AccessDeniedHttpException class `use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;`

which now handles the directory correctly and shows the 403 view and still returns the HTTP 403. I'm sure there's a better way of doing this, but i'm just testing the functionality behind using the 403 error pages.

I'm wondering if this is deliberate to mimic hiding directory's existence, or if you'd consider adding this if i create a PR? I'm happy to provide further information/code if requested.

**Comment by jaschweder** [comment]
I thing this is more application specific propose that the current framework not ?

**Comment by GrahamCampbell** [comment]
Yeh, just implement whatever you want in your application. Everyone wants different things.
