### ISSUE TITLE
Blade multiline comment bug?

### ISSUE THREAD

**Issue by lozitskiys** [laravel/framework#8738]
Here is the template:

>    {{-- HTML::style('css/bootstrap.css') }}
>   {{ HTML::style('css/main.css') --}}
>{{public_path()}}
>{{public_path()}}

Here is output i got:

>{{public_path()); ?>
>/var/www/dev/stas/myproject/public

Compiled file content:
>  <?php /* HTML::style('css/bootstrap.css') }}
>   <?php echo e(HTML::style('css/main.css') */ ?>
>{{public_path()); ?>
><?php echo e(public_path()); ?>

BTW: with single line comment everything is OK.

Laravel version: 5.0

**Comment by GrahamCampbell** [comment]
Sorry, our comments in blade a very limited. If you have a fix, we'd accept a PR but I doubt we'll fixing it otherwise. Sorry I couldn't bring better news.

**Comment by lozitskiys** [comment]
BladeCompiler wraps commented text with php-comments. I would suggest to strip commented text (instead of wrapping it) to prevent further parsing that strings:
><?php /* HTML::style('css/bootstrap.css') }}
>    {{HTML::style('css/bootstrap.css') }}
>    {{HTML::style('css/bootstrap.css') }}
>    {{ HTML::style('css/bootstrap.css') */ ?>

Not sure if it is OK for debugging, so let it be as is.

**Comment by lukasgeiter** [comment]
@lozitskiys I like the idea of directly removing the comments instead of compiling them to PHP comments. @taylorotwell What's your opinion on this?
