### ISSUE TITLE
blade {{ }} echo escape behavior

### ISSUE THREAD

**Issue by TerrePorter** [laravel/framework#8743]
I decided to do a composer update today and ran in to a odd issue. I'm wanting to see if this is suppose to be this way or if it is a unexpected result of a code change.

I am using the setContentTags to remove the "auto escape content tags" that was introduced some time ago.

The function is setContentTags($openTag, $closeTag, $escaped = false)

I was doing this 
```
Blade::setContentTags('{{', '}}', false);
```

However, after digging in to the code I found a change at, https://github.com/laravel/framework/commit/deb0a3259d34e0246703ff48871b7993c224e325 which added in the setEchoFormat function.

In order to disable the auto escape I have to change
```
Blade::setEchoFormat('%s');
```
The third option, $escape, in the setContentTags appears to be ignored completely.

**Comment by GrahamCampbell** [comment]
Not an issue, we changed the tags that do the escaping.

**Comment by TerrePorter** [comment]
@GrahamCampbell Are you referring to the change of the {{ }} being escaped by default or something other tags that do escaping?  

When I look at the code behind the function Blade::setContentTags('{{', '}}'). I see the third option as $escape  = FALSE, I read that as if it is false then do not escape the variable contents. Unless you are planing to change the meaning of false, the code needs to be adjusted. That doesn't even touch the usage of the setEchoFormat('%s') vs the default of e(%s). 

Care to elaborate on your reply, instead of what feels like a brush off ?

**Comment by Sladewill** [comment]
{{ }} - html entities applied
{!! !}} - raw output.

If you want to change that look at the Blade Compiler on which ones to override.
