### ISSUE TITLE
re: blade {{ }} echo escape behaviour

### ISSUE THREAD

**Issue by TerrePorter** [laravel/framework#8747]
In reference to #8743

@taylorotwell, @GrahamCampbell Your an ass GrahamCampbell - collaboration is the key to successful open source development. The disrespect of being locked out of the issue without any conversation is completely 100% rude. Your one line reply didn't event touch a tiny bit of the what I posted in relation to the code changes. 

I took the time out of my busy work day to post a possible issue, that looked to me like a bug or at least something that might need looked at, and instead of getting the the basic amount of respect. I get the feeling of "I bothered the great and almighty GrahamCampbell".

So you pull out your GOD power and lock the issue, no discussion, GrahamCampbell has spoken. You win GrahamCampbell. You won't be bothered with any trivial issues from me ever again.

I might not be a really active contributor but I was trying to help where I could to make this framework be better. 

This is my last issue post.

**Comment by GrahamCampbell** [comment]
This was closed for good reason. We're not reverting the change to blade. If you want a discussion, please use the forums. GitHub is reserved for bugs.
