### ISSUE TITLE
[Envoy] runing npm on normal ssh sessions works, but with envoy task returns npm command not found

### ISSUE THREAD

**Issue by cve** [laravel/framework#8753]
Hi,

when I login to my VPS with SSH and run command:

    npm -v

it gives me 

    1.4.28

but when I run my Envoy.blade.php:

    @servers(['testing' => 'user@host'])

    @task('deploy')
        cd some/folder
        npm -v
    @endtask

with envoy run deploy it gives me bash: line 3: npm: command not found

**Comment by GrahamCampbell** [comment]
Doesn't look like a bug in envoyer, more that envoyer's not running as the same user as the one you ran that first command from, likely the "nmp" alias isn't registered. Any further questions belong on the forums please.
