### ISSUE TITLE
Eloquent accessor throws error when comparing integer values during a toJson() call

### ISSUE THREAD

**Issue by Harrisonbro** [laravel/framework#8755]
I have code in my app which calls `toJson()` (via Jeffery Way's [PHP-Vars-To-Javascript](https://github.com/JeffreyWay/PHP-Vars-To-Js-Transformer) package) on a `Project` model which itself has a collection of other `Budget` models. The `Budget` model has an attribute accessor which casts an integer value to a currency object, like so:

```
public function getMaxAmountAttribute($value)
{
    // If max amount is less than target amount, set it to be equal target value
    if ($value < $this->target_amount->getAmount())
    {
        $value = $this->target_amount->getAmount();
    }

    return new \Acme\Currencies\UsdAmount($value);
}
```

However, when the `Project::toJson` method runs and tries to work through the collection of `Budgets` it throws an exception: `Failed calling Illuminate\Database\Eloquent\Collection::jsonSerialize()` (see screenshot below). 

Furthermore, even just attempting to cast `$value` to an integer throws the same issue:

```
public function getMaxAmountAttribute($value)
{
    return (int)$value; // Does exactly the same if I use intval($value)
}
```

The only way I've found to prevent this is to cast `$value` in my accessor method to a string and back to an integer again:

```
public function getMaxAmountAttribute($value)
{
    $value = intval(strval($value));
    
    // If max amount is less than target amount, set it to be equal target value
    if ($value < $this->target_amount->getAmount())
    {
        $value = $this->target_amount->getAmount();
    }

    return new \Acme\Currencies\UsdAmount($value);
}
```

I've no idea why this would be the case! Any help is much appreciated.

![screen shot 2015-05-15 at 10 50 31](https://cloud.githubusercontent.com/assets/377366/7650665/93c90044-faf0-11e4-8879-82b57ce6f406.png)

**Comment by GrahamCampbell** [comment]
We do not support Laravel 4.2.
