### ISSUE TITLE
Dynamic where clause uses snake case and destroys field names

### ISSUE THREAD

**Issue by dot0x** [laravel/framework#8765]
Hi,

the addDynamic function (Query/Builder.php) snake case's every segment. This Result in a wrong field name by using fields named like "UserID" or "LicenseID".

Any suggestions to fix this? Or how to workaround? I don't want to permanently edit the vendor folder

**Comment by lukasgeiter** [comment]
Instead of something like `->whereUserID(1)`, just use `->where('UserID`, 1)`

**Comment by GrahamCampbell** [comment]
Thanks @lukasgeiter.
