### ISSUE TITLE
Concurrency issue in database session driver

### ISSUE THREAD

**Issue by ibrasho** [laravel/framework#8778]
I've been seeing the "Integrity constraint violation: 1062 Duplicate entry ..." message once or twice daily in a small app using the database driver.

Are we open to improvements on dealing with concurrency, e.g. what [Symfony PdoSessionHandler](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L660) is doing? [Specifically check this PR](https://github.com/symfony/symfony/commit/e58d7cf6c6da343b3e9259425ad8f11c9e05ca51).

**Comment by Stichoza** [comment]
Maybe related to #8172 ?
