### ISSUE TITLE
artisan queue:listen not working with custom php extension

### ISSUE THREAD

**Issue by ddeath** [laravel/framework#8779]
Hi there,
I am using Laravel queues with beanstalkd. I would like to run function solve_simplex() which is my custom function intalled to php as extension. 

If I use it in Laravel framework in controller it works. But if I use it in queue job it does not.
It says undefined function solve_simplex()

It is caused because Queue jobs in laravel are executed in "CLI enviroment" so the extensions are not loaded.

However I can pass -dextension parameter to PHP with name of my extension so it know I need to use it:

    php -dextension=solveSimples.so artisan queue:work 

so it works. But if I try to run queue:listen

    php -dextension=solveSimples.so artisan queue:listen

**Solution:**
it does not because [queue:listen execute own command](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Queue/Listener.php#L59) where -dextension option is not passed.

Would be possible to add an option to the queue:listen command, which would take params for php command?

Thanks

**Comment by GrahamCampbell** [comment]
I'd recommend just enabling that extension in your cli environment.
