### ISSUE TITLE
Model::toJson should use jsonSerialize()

### ISSUE THREAD

**Issue by borys-p** [laravel/framework#8783]
\Illuminate\Database\Eloquent\Model::toJson() uses toArray() method to creted JSON data, although there's jsonSerialize() next to it, which does exactly the same, but can be overridden to modify output data (e.g. base64-encode binary strings).

**Comment by barryvdh** [comment]
I would say that using jsonSerialize would make more sense when extending, although in most cases it probably wouldn't change much.

    public function toJson($options = 0)
    {
        return json_encode($this->jsonSerialize(), $options);
    }

**Comment by borys-p** [comment]
Yes, I exactly thought about extending jsonSerialize(), sorry for the long sentence :)

By the way the same problem is in Illuminate\Routing\ResponseFactory::json(). Perhaps there should be another check, e.g.:

```
if ($data instanceof Model)
{
     $data = $data->jsonSerialize();
}
elseif ($data instanceof Arrayable) 
{
    $data = $data->toArray(); 
}
```

**Comment by barryvdh** [comment]
That could probably be the JsonSerializable interface from PHP itself. http://php.net/manual/en/class.jsonserializable.php

You can just make a PR if you want. The first issue is already fixed in the PR mentioned above :)

**Comment by lukasgeiter** [comment]
@borys-p Well spotted! As Barry mentions, checking for `JsonSerializable` is better though :wink:

**Comment by borys-p** [comment]
Of course you're right with `JsonSerializable`. My only excuse is that it's my fourth day with both Laravel and PHP 5.4 ;)

**Comment by GrahamCampbell** [comment]
Closing. Discussion can continue on the PR.
