### ISSUE TITLE
Manual pagination broken in L5

### ISSUE THREAD

**Issue by clapas** [laravel/framework#8790]
Both Paginator and LengthAwarePaginator seem broken.

Paginator would show the same items no matter what page.

LengthAwarePaginator would show all the items like there was no pagination.

I have tried 5.0.28 and 5.0.31 with same results.

**Comment by GrahamCampbell** [comment]
You need to provide the already paginated items yourself.

**Comment by GrahamCampbell** [comment]
There would be no point in a paginator if we fed it all the data.

**Comment by clapas** [comment]
Thank you for your answer.

In the API docs, there is a method `items(): Get the slice of items being paginated.`

Sorry if I interpret it the wrong way, but that leads to think on a "whole" the slice is taken from, therefore suggesting you must pass the whole to the constructor.

Cheers
