### ISSUE TITLE
WhereHas adds the table prefix twice in the from clause.

### ISSUE THREAD

**Issue by Speedrockracer** [laravel/framework#8795]
Hey Guys,

I just migrated to laravel 5.0 and ran into this issue.
the following code:
```php
$query->whereHas('following', function($q) {
	var_dump($q->toSql());
});
```
Gives this query as a result:
```sql
select count(*) from "sq_user_follower" as "sq_sq_self_0f2062d385331e7c99512b0421ca6f81" where "sq_self_0f2062d385331e7c99512b0421ca6f81"."user_id" = "sq_users"."id"
```
Adding the table prefix twice in the "as" part of the from clause. This causes and error in the where clause where the prefix is added only once. This code used to work fine in laravel 4.

Regards,
Django

**Comment by GrahamCampbell** [comment]
Discussion can continue on the PR.
