### ISSUE TITLE
Proposal: sort imports alphabetically

### ISSUE THREAD

**Issue by lowerends** [laravel/framework#8800]
I'd like to hear your opinions for sorting the imports (with ```use``` statements) alphabetically in ascending order. This would make it easier to detect imports that are included twice and is also easier to read/reference. It's not part of any PSR (yet) but the increased readability and consistency would make the code a bit cleaner.

Thoughts?

**Comment by Anahkiasen** [comment]
I'd like that, I know the current sort order looks nicer but it's kind of counter productive.

**Comment by Arjan96s** [comment]
I think this doesn't make sense. A lot of IDE's have a option to optimize imports. Furthermore if you import something twice the length should be the same. Therefore I see no benefits in this besides it is easier to find you're import if you've a lot of them.

**Comment by lowerends** [comment]
@Arjan96s A lot of IDE's indeed have that functionality, but that shouldn't be used for the vendor's code of course. Also, importing something twice will indeed have the same length, but if there are multiple imports with the same length, the double import will not necessarily be listed one after another. This will not happen when listed alphabetically.

**Comment by Arjan96s** [comment]
That's true. But how often are there so much imports with the same length? If there are a lot of imports with the same length we can probably sort imports of the same length alphabetically!

**Comment by Anahkiasen** [comment]
@Arjan96s More importantly what is your argument for sorting by line length? Apart from being nicer visually it offers literally no benefit whereas sorting them alphabetically has all sorts of benefits

**Comment by Arjan96s** [comment]
@Anahkiasen My only argument is a nice visual represention of imports. I think we don't NEED a change in this. Therefore I think we can best keep it as is.

**Comment by GrahamCampbell** [comment]
This isn't going to happen. It's of no gain.

**Comment by franzliedke** [comment]
Why no gain? Please at least consider the arguments.

@Anahkiasen put it best:
> @Arjan96s More importantly what is your argument for sorting by line length? Apart from being nicer visually it offers literally no benefit whereas sorting them alphabetically has all sorts of benefits

**Comment by GrahamCampbell** [comment]
I can ask Taylor, though I think I know what that answer will be. :)

**Comment by franzliedke** [comment]
That would be great. =)

**Comment by taylorotwell** [comment]
I prefer them sorted by length. Thanks though.
