### ISSUE TITLE
Magic method in view make is not working of a camel case variable

### ISSUE THREAD

**Issue by gowthamSelvaraj** [laravel/framework#8803]
when a magic method is used to access a variable in view its is not working for a camel cased variable.

eg

// Using Magic Methods
$view = View::make('greeting')->withName('steve');

I am able to access the data in the variable $name, But when I use

// Using Magic Methods
$view = View::make('greeting')->withFullName('steve Harry');

I am not able to get the data by using the variable $fullName, it shows 

Undefined variable: fullName

**Comment by lukasgeiter** [comment]
The name is converted to *snake_case*. So the variable will be: `$full_name`.

**Comment by gowthamSelvaraj** [comment]
so i can't use a came cased variable ?

**Comment by lukasgeiter** [comment]
Just use `->with('fullName', '...')` if you want full control over the variable name
