### ISSUE TITLE
Dissociate strange behavior on One to Many Polymorph relation

### ISSUE THREAD

**Issue by iget-master** [laravel/framework#8806]
Suppose a two models App:
`User ('id', 'tag_type' nullable, 'tag_id' nullable)`
`Tag ('id', 'name')`

Having this relations:
```
// At User
public function tag() {
    $this->morphTo();
}

// At Tag
public function users() {
    $this->morphMany('App\User');
} 
```

I've found an strange behavior on `$model->relation()->dissociate()`.

When I do 

```
$user = User::first();
$tag = Tag::create([ 'name' => 'foo' ]);
$user->tag()->associate($tag)->save();
```

My $user dump will be:
```
[
    'id' = 1,
    'tag_type' = 'App\Tag',
    'tag_id' = 1
]
```

Everything right here, ok?
But, if I run this:

```
$user->tag()->dissociate()
```

My $user dump will be:
```
[
    'id' = 1,
    'tag_type' = 'App\Tag',
    'tag_id' = null
]
```

It does not empty the `type` field, when it should do it.
I've a database with thousands of records with unecessary column data, since that only a model name does not means anything. It's just trash.

**Comment by GrahamCampbell** [comment]
Thank you, but I thing you'd get a better response from people if you posted on the forums, since our GitHub is strictly for isolated bug reports.

**Comment by iget-master** [comment]
Isn't this an bug?!

I don't want a answer, this is clearly an bug!

**Comment by GrahamCampbell** [comment]
Hmm, ok. Thanks for reporting.
