### ISSUE TITLE
Eloquent executes queries to load null relations

### ISSUE THREAD

**Issue by Flightfreak** [laravel/framework#8819]
Consider a user model with a nullable country relation, keyed with country_id that has a value null. 
When loading the relation, a query ```select * from `countries` where `countries`.`deleted_at` is null and `countries`.`id` in (0)``` is executed. Is there a specific reason for this? Would a pull request to avoid queries for null relations be accepted?

**Comment by lukasgeiter** [comment]
I already created a PR that would fix such cases: #8737
