### ISSUE TITLE
Laravel Dependency Injection of Request issue with Inheritance [bug]

### ISSUE THREAD

**Issue by newtonianb** [laravel/framework#8821]
There seems to be some kind of bugs when using **Method Injection** and **Basic PHP Inheritance** in the parameters.

Below I have a ``BaseController`` that defines a function with a parameter of type Request.
I then create my new controller ``MyController`` with ``MyRequest`` (which extends from ``Request``) and should work but it's throwing an error:

**The exception I get**

    ErrorException in MyController.php line 11:
    Declaration of app\Http\Controllers\MyController::index() should be compatible with app\Http\Controllers\BaseController::index(app\Http\Requests\Request $request)

**app\routes.php**
    Route::get('/', 'MyController@index');

**app\Requests\MyRequest.php**

    class MyRequest extends Request {
      
    }

**app\Http\Controllers\BaseController.php**

    class BaseController extends Controller {
      
      public function index(Request $request)
      {
    
      }
    }

**app\Http\Controllers\MyController.php**

    class MyController extends BaseController {
      
      public function index(MyRequest $request)
      {
    
      }
    }

**Comment by GrahamCampbell** [comment]
`app\Http\Requests\Request` is wrong.

**Comment by newtonianb** [comment]
Hi @GrahamCampbell we've been trying many things, this error was the last try where we fiddled with the Request we used but we also tried using the Request from Illuminate, the problem is still there.

```
Declaration of App\Http\Controllers\MyController::index() should be compatible with App\Http\Controllers\BaseController::index(Illuminate\Http\Request $request)
```

**Comment by newtonianb** [comment]
Also, we tried the same example outside of the Laravel framework and it works, it's just when Laravel tries to do dependency injection on the parameters, this concept fails.

```
MyParameterClassType extends BaseParameterClassType {}
```

```
    class BaseClass {
      
      public function index(BaseParameterClassType $input)
      {
    
      }
    }
```

**app\Http\Controllers\MyController.php**
```
    class MyClass extends BaseClass {
      
      public function index(MyParameterClassType $input)
      {
    
      }
    }
```

**Comment by franzliedke** [comment]
You cannot overwrite a method with a conflicting signature. Why does your
BaseController even have that index method when it is just a (abstract?)
base controller?
Am 20.05.2015 18:36 schrieb "newtonianb" <notifications@github.com>:

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by newtonianb** [comment]
k thanks just did 
http://stackoverflow.com/questions/30355435/laravel-dependency-injection-of-request-issue-with-inheritance

**Comment by GrahamCampbell** [comment]
"the forums" -> http://laravel.io/forum :)

**Comment by newtonianb** [comment]
ay was not aware of it, thanks just did too
http://laravel.io/forum/05-20-2015-laravel-dependency-injection-of-request-issue-with-inheritance

**Comment by newtonianb** [comment]
USER ERROR :( sorry all it actually does not even work in raw php after all, we just did a sanity check outside of php and confirmed we get the same error. We were so convinced it should work, we either confused with another language or actually remember it working in previous versions of PHP, in any case it doesn't work in php 5.6, whether it should or not is for a different chat.

**Comment by franzliedke** [comment]
For reference: this is a feature, not a bug, and due to proper OO.

Your `BaseController` promises to the outside world a certain interface, and that includes that it will accept any `Request` instance as parameter to the `index()` method. Since `MyRequest` is a subclass of `Request`, it violates that contract: the `MyController` will not accept *any* `Request` object.

I hope that makes sense. =)

**Comment by newtonianb** [comment]
@franzliedke thank you @franzliedke! Makes sense but the confusion sinks in when you define an interface you can actually be lax about this and it does allow the interface definition to be a parent class.

**Comment by franzliedke** [comment]
That still makes sense, because by accepting a parent interface, a subclass can still accept anything its parent class accepts, but also more - that is okay from an OO standpoint.

**Comment by newtonianb** [comment]
Thanks!
