### ISSUE TITLE
On production server: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureHandler()

### ISSUE THREAD

**Issue by vargvinter** [laravel/framework#8829]
Hello,

First of all, version 5.0.31 works OK locally on Vagrant/Homestead. There are problems when I have uploaded a project to the production server. I see a blank page and in php log I have:
`Notice: date_default_timezone_set(): Timezone ID '' is invalid in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 41`
`Fatal error: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureHandler() in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php on line 54`

I've var_dumped() some data and:
- in file `/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php` on line 41 `$config['app.timezone']` is NULL,
- in file `/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php` on line 52 `$app['config']['app.log']` is NULL.

...and I have no idea why... 
Is my production server missing some modules/functionality?

PHP on production server is 5.5.13. 
PHP on Homestead is 5.5.17.

Cheers.

PS. Version 5.0.7 works OK locally and on production server as well.

**Comment by GrahamCampbell** [comment]
You need to delete your compiled file.

**Comment by vargvinter** [comment]
I've done this. There is no compiled.php in /vendor. Page still doesn't work on production server. Locally is OK.
I suppose that there is problem with dot notations...

**Comment by omnilord** [comment]
Experiences the same issues with a completely vanilla install of Laravel 5.1.1, PHP 5.5.9.

We've spent some time digging around, and discovered, at least for the notice, a "solution" that indicates a change in the way config/app.php is loaded into $config.

On this line: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L41

     date_default_timezone_set($config['app.timezone']);

should be

    date_default_timezone_set($config['config.app.timezone']);

Not sure if this is a problem with the $config object's array access implementation, the way the data is loaded into $config, or if we've just missed something in our instance's configuration, but 'app.timezone' does not access the timezone as configured in config/app.php, 'config.app.timezone' does.

The following error is completely preventing us from even getting started with our first Laravel project:

    Fatal error: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureHandler() in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php on line 66

**Comment by tekkenking** [comment]
I just experience this error today after updating on laravel 5.1..

To solve the error you'll have to go to Illuminate\Foundation\Bootstrap\LoadConfiguration

Go to line 72 i think.

And change

$files[$nesting.basename($file->getRealPath(), '.php')] = $file->getRealPath();

To

$files[basename($file->getRealPath(), '.php')] = $file->getRealPath();

Works for me..

**Comment by lbeauvisage** [comment]
I experience this error today.
as @tekkenking removing $nesting in Illuminate\Foundation\Bootstrap\LoadConfiguration solve the problem. 
`$nesting` is provided by getConfigurationNesting method, where, in my case , `config_path()` return a string ended by a `/` , whereas $directory return a string that does not finish by a `/` , so `str_replace` does not work as needed and `$tree` return a full PATH (include project root directory).

Finaly I found a conflict with the `config_path()` helper from  `laravel/framework/src/Illuminate/Foundation/helpers.php` and another from https://github.com/appkr/fractal package witch return the string ended by a `/` if `$path` is empty. 
I make a pull request here : https://github.com/appkr/fractal/pull/6

**Comment by appkr** [comment]
@vargvinter Reproduce the problem on your dev machine and try this:

```
$ rm composer.lock
$ rm -rf vendor
$ composer install
```

@lbeauvisage This issue has nothing to do with `appkr/fractal`

**Comment by drupalik** [comment]
very dirt fint
Bootstrap/ConfigureLogging.php on line 66
try "monolog/monolog":"master"
очень грязный рабочий трюк))

    protected function configureHandlers(Application $app, Writer $log)
    {
        if(ucfirst($app['config']['app.log'])) $method = 'configure'.ucfirst($app['config']['app.log']).'Handler';
else $method='configureSingleHandler';//return;
        $this->{$method}($app, $log);
    }

**Comment by Santoshge-Reddy** [comment]
please help me out my app is working fine in local but it is throwing errors on the production.
![public](https://user-images.githubusercontent.com/25544735/40587244-318cfea8-61ea-11e8-91a1-1e085d7b5619.png)

**Comment by luispabon** [comment]
To anybody coming across this problem, it's due to lack of the config entry `app.log`.
