### ISSUE TITLE
allow null return value on relationships

### ISSUE THREAD

**Issue by browner12** [laravel/framework#8830]
when defining relationships it would be nice to allow a null return value if the relationship does not exist.

imagine a game with a `Home Team` and `Away Team`. The relevant fields are `home_id` and `away_id`. `belongsTo()` relationships are defined for both of them.  Once the game is done I have a home team score and away team score. We can have a winner and a loser, or it can be a tie. I would like to create a relationship called `winningTeam()` that performs some logic and returns the winning team to me.

```php
public function winningTeam()
{
    //home team won
    if ( $homeTeamWon )
    {
        return $this->belongsTo('App\Team', 'home_id');
    }
    elseif ( $awayTeamWon )
    {
        return $this->belongsTo('App\Team', 'away_id');
    }

    //game resulted in a tie
    return null;
}
```

if I then used the relationship in my code

```php
$game->winningTeam->id
```

and the game was a tie, it would throw a `LogicException` telling me a relationship method must return a `Relation` object.

I would propose allowing the `getRelationshipFromMethod()` method to return a null value;

```php
protected function getRelationshipFromMethod($method)
{
    $relations = $this->$method();

    if ( is_null($relations) )
    {
        return $this->relations[$method] = null;
    }

    if ( ! $relations instanceof Relation)
    {
        throw new LogicException('Relationship method must return an object of type '
            . 'Illuminate\Database\Eloquent\Relations\Relation');
    }
    return $this->relations[$method] = $relations->getResults();
}
```

this would allow me to 

```php
echo ($game->winningTeam) ? $game->winningTeam->name : 'No winner';
```

or something similar to that.

there are definitely other ways I can attack this problem, but I wanted to throw this out there and get other people's thoughts on it. maybe another solution to this would be some kind of null `Relation`.

*Thanks*

**Comment by jaschweder** [comment]
I don't know if this is the best propose, but you can map the collumns names in the $fillable array in the model for this, but I think this is a good propose and is a better alternative :+1:

**Comment by GrahamCampbell** [comment]
There is no point in `return null;`. You can just miss out that code and still get the same result.

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by browner12** [comment]
is this a BC break? in other words, which branch should I send the PR to?

**Comment by GrahamCampbell** [comment]
5.1, or 5.2. If it doesn't go through into 5.1 by the weekend, it'll need retargeting to 5.2 basically.
