### ISSUE TITLE
SQLite using ilike breaks query builder

### ISSUE THREAD

**Issue by loganfre** [laravel/framework#8837]
When using 'ilike' as an operator and a SQLite database throws a sql exeception.

Example:
User::where('username','ilike',"%$search%")->get();

Result:
[Illuminate\Database\QueryException] SQLSTATE[HY000]: General error: 1 near "ilike": syntax error (SQL: select * from "users" where "username" ilike %something%)

The above code works fine in Postgres. It seems that SQLite does not support the 'ilike' operator, but the 'like' operator is case insensitive. My suggestion would be to change 'ilike' to 'like' in the SQLite grammar or processor class.
The alternative is to remove 'ilike' from the list of operators for SQLite, but that makes the query builder a bit less universal.

**Comment by jtraub** [comment]
`LIKE` operator in MySQL is case-insensitive too unless one of the operands is a binary string. 

`ILIKE` operator is a non-standard PostgreSQL extension. Therefore I am not sure if Laravel should emulate the operator and include it in available clause operators by default.
