### ISSUE TITLE
Seeds, weeds and migrations :)

### ISSUE THREAD

**Issue by rafis** [laravel/framework#8839]
Hi, I was smoking a weeds and an brilliant idea came to my mind at that time (kidding of course!). What If we could drop seeds system and leave only migrations? Seeds are particular case of migrations. I was noticed that my seeds have up and down methods, for example, `class NodeSeederUp extends Seeder` and `class NodeSeederDown extends Seeder` and I call them from my migrations's `up()` and `down()` methods, for example, `Artisan::call('db:seed', ['--class' => 'NodeSeederUp ']);`.

So we have following statements of abstraction:

1. Common migrations are migrations on structure
2. Seeds are migrations on data:
    * Enumerator/directory seeds, for example, Currencies
    * Data seeds, for example, New products
    * Seeds for testing - those will leave at current seeds directory, but would extend Migration class

That would be cool to see this in Laravel 6, what do you think?

**Comment by GrahamCampbell** [comment]
> That would be cool to see this in Laravel 6, what do you think?

Laravel 6 is a LONG way off yet.

**Comment by ChangePlaces** [comment]
No, I disagree. Migrations are for database schema, not content. I should be able to use the same migration whether dev, testing or production. I want to be able to choose what seeds I want to import (if any at all) manually. Just because I'm working on a testing dev may not necessarily mean that I want testing data in automatically.

**Comment by sebastiaanluca** [comment]
I'm working on a structure for a project that does something similar.

1. Migrations: database structure
2. Application seeders: data necessary to run the application (OAuth2 applications, superadmin, …)
3. Development seeders: optionally-run seeders to provide development test data
4. Test seeders: data specifically for test purposes
5. Etc…

I wouldn't merge migrations and seeders though lol.

**Comment by jbrooksuk** [comment]
:-1: from me on this.

1. Migrations are table structure.
2. Seeds are table content.
