### ISSUE TITLE
Request include a Backslash first element 

### ISSUE THREAD

**Issue by jwatkins0101** [laravel/framework#8841]
Request include a Backslash first element 
uri

http://localhost.app/dashboard/data?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=name&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=email&columns%5B2%5D%5Bname%5D=email&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=created_at&columns%5B3%5D%5Bname%5D=created_at&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=updated_at&columns%5B4%5D%5Bname%5D=updated_at&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1432233768891
![screen shot 2015-05-21 at 3 20 07 pm](https://cloud.githubusercontent.com/assets/6437647/7756982/e69c60f0-ffcc-11e4-89e1-0e67bd2c2e65.png)

**Comment by fluffypony** [comment]
If anyone comes across this in future, it's because some of the Laravel + nginx guides (such as [this one](https://asked.io/how-to-install-php-7-x--nginx-1-9-x---laravel-5-x), at time of this comment) escape ```$``` symbols in the nginx config, which is entirely wrong. Instead of:

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

it should be:

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

**Comment by gcphost** [comment]
My guide has you write the config using a heredoc and it requires escaping the $, if you copied the config by itself then you would need to remove the escapes.
