### ISSUE TITLE
Artisan doesn't use --env during migration process.

### ISSUE THREAD

**Issue by itsash--** [laravel/framework#8844]
I'm having a problem with migrating my tables within a package under the `testing` environment.

The problem is when I run a migration using `--env=testing` with `--path=/vendor/...`.  Essentially two things have happened, first I run the migration as part of my unit test like so:

```php
    public function setUp()
    {
        parent::setUp();
        $this->artisan('migrate', ['--env' => 'testing', '--path' => __DIR__.'/../database/migration']);
    }
```

It creates the `migration` table on the test database, it doesn't migrate the tables though.  Every migrate thereafter says 'Nothing to migrate.'.  I have got `<env>` settings in `phpunit.xml`.

Secondly if I run the migration myself on the CLI I get the same result.  In fact on the CLI I can confirm even with `--env=testing` migrations are run on the default connection details.

```
$ php artisan migrate --env=testing --path=/vendor/example/package/database/migrations
```

I'm not sure if it's a bug or if I have not configured something currently, so I will continue to look into this/PR if I can find a problem.  But If anyone else has any ideas or can assist from that would be cool.

**Comment by GrahamCampbell** [comment]
Looks like a bug. We're open to PRs. :)

**Comment by itsash--** [comment]
I've had a look into the an it's not actually a bug.  The environment is maintained as testing which is expected, also further investigation turns out that the `--path` must be relative from the application base_path:

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L64-L67
