### ISSUE TITLE
[Feature Request] Eloquent, Order By related model

### ISSUE THREAD

**Issue by sn0opr** [laravel/framework#8845]
Let say that we have Article model with Comment as it's related model.
I want to get the 10 last commented articles:

```php
$lastCommentedArticles = Article::with(['comments.author', 'author'])
->orderBy('comments.date', 'DESC') //order by comments.date
->limit(10)->get();
```
This way, I don't have to use the join method etc...

**Comment by Sladewill** [comment]
```php
$lastCommentedArticles = Article::with(['comments' => function($query)
{
    $query->orderBy('date', 'DESC')
          ->with('author');
}), 'author'])
->take(10)
->get();
```

Just note, these kind of things should be asked on the forum as its not an issue.

**Comment by sn0opr** [comment]
@Sladewill this is not what I'm asking for, your query will just order the comments of each Article and not **Order the articles by its own comment date**

**Comment by stuartmccord** [comment]
I'm nearly certain you can't do this in Eloquent using a with as it will run 2 queries, one for each table.  You can definetely get the result you want using a join.

**Comment by fico7489** [comment]
It is not that simple as may it looks like, for more info why take a look at this package  https://github.com/fico7489/laravel-eloquent-join
