### ISSUE TITLE
Error templates ?

### ISSUE THREAD

**Issue by mickaelandrieu** [laravel/framework#8851]
Hi,

I saw in ``resources\error`` folder from ``laravel/laravel`` a 503 error template. Did you plan to provide a custom template for others ? Is it already the case ?

**Comment by GrahamCampbell** [comment]
Doubt it. There's probably some sample resources out there somewhere. Otherwise, we'd expect people to implement this as they want.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions might be of use to you?

**Comment by mickaelandrieu** [comment]
Thank you for your answer and your library sounds very well :)

but not realy, I'm not a huge fan of WhoopsBundle (I did an implementation for Symfony but I think Symfony Webdebug application is far more performant and complete).

Does the error templating system works like in Symfony's one ? Listening on kernel exception event and then returns a view ?

**Comment by GrahamCampbell** [comment]
> but not realy, I'm not a huge fan of WhoopsBundle (I did an implementation for Symfony but I think Symfony Webdebug application is far more performant and complete).

It's not just a whoops bundle. It provides a framework for massive customisation and easy setup for your errors.

**Comment by GrahamCampbell** [comment]
You can register your own "displayers" that know how to deal with different content types in different situations.

**Comment by GrahamCampbell** [comment]
This is what prod error pages for html look like out of the box: https://styleci.io/123.

**Comment by mickaelandrieu** [comment]
@GrahamCampbell wow ! Ok, this is clearly far from a simple implementation.
And I think this doesn't need to much work to be used in Symfony world too :)

Thank you, I think I will try to create a Symfony port (for fun). Good night
