### ISSUE TITLE
Make a method to set faker local on FactoryBuilder

### ISSUE THREAD

**Issue by jatubio** [laravel/framework#8865]
Now can't setup local on Faker, similar to `$faker = Faker\Factory::create('es_ES'); // create a Spanish faker`

I'm using this temporary solution:

```
$factory->define('App\User', function ($faker) {
     $faker=Faker::create('es_ES');
     return [
        'name' => $faker->name,
        'email' => $faker->email,
        'password' => str_random(10),
        'remember_token' => str_random(10),
    ];
});
```

**Comment by crynobone** [comment]
Can't you do it during TestCase before/setup.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by jatubio** [comment]
@crynobone, i can't do because i have not access to faker instance from outside.   

Faker instance on FactoryBuilder is protected, and how you can see here: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/FactoryBuilder.php#L55 it's created in constructor. The problem is that Faker have not public method to set locale. You can change locale only making a new Faker instance.

New factory system of Laravel 5.1 is based or similar to TestDummy package. And I have seen this implementation on them: (https://github.com/laracasts/TestDummy/blob/master/src/FakerAdapter.php#L42)

```
    /**
     * Set the locale of the generator
     *
     * @param string $locale
     */
    public function locale($locale)
    {
        $this->generator = Faker::create($locale);
    }
```

This way, you can setup Faker locale from outside through one adapter.  Thus, I'm talking about if it's posible to implements similar method directly on Factory or FactoryBuilder :)

**Comment by mohamedsharaf** [comment]
`$factory->define(\App\User::class, function (Faker\Generator $faker) {
    $faker = \Faker\Factory::create('ar_SA');
    return [
        'name' => $faker->name,
           ];
});`

hope this help
