### ISSUE TITLE
MIME validation rule checks extensions, not MIME types.

### ISSUE THREAD

**Issue by timgws** [laravel/framework#8866]
As per the documentation, http://laravel.com/docs/5.0/validation#rule-mimes

> The file under validation must have a MIME type corresponding to one of the listed extensions.

The problem with the MIME validation type is that it does not actually validate against the MIME type, but rather the extension of the file that is assumed from the mime type.

[validateMimes in Illuminate\Validation\Validator][2]

What I suggest is adding to the validation rule a simple check to find if any of the provided rule values match a file content type as described in [RFC 2045][1]

ie, if there is a parameter to the MIME validator that contains a slash, as well as (... or instead of, depending on the provided parameters) calling `guessExtension` on Symfony\Component\HttpFoundation\File\File (which the `UploadedFile` that Laravel uses from Symfony extends) we will also/instead call [`getMimeType`][3]

See also: https://github.com/laravel/framework/pull/1828

[1]: https://tools.ietf.org/html/rfc2045#section-5.1
[2]: https://github.com/laravel/framework/blob/aa5cb848670a5aa9bd35e151eb566e359221da5a/src/Illuminate/Validation/Validator.php#L1244
[3]: https://github.com/symfony/symfony/blob/d5ed6ecdf61f7d520aa5528d21aa68911373eee5/src/Symfony/Component/HttpFoundation/File/File.php#L83-L88

**Comment by GrahamCampbell** [comment]
We're open to PRs.
