### ISSUE TITLE
FilesystemManager public drive method, not on Factory interface

### ISSUE THREAD

**Issue by hendore** [laravel/framework#8867]
Not sure if this is intentional, I noticed the Filesystem factory interface has a single method

```php
public function disk($name = null);
```

However, when looking at the FilesystemManager factory implementation, theres also a public method which acts as an alias to the disk method.

```php
public function drive($name = null)
{
	return $this->disk($name);
}
```

I searched the repository for anywhere using the drive method but couldn't find anywhere making use of it?

https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=drive

Should this be removed from the FilesystemManager?

**Comment by GrahamCampbell** [comment]
This is intentional I think. Our other manager classes are simelar.
