### ISSUE TITLE
[Request] Blade Localization modifiers

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#8885]
Wouldn't it be useful to add an extra parameter to the blade @lang and @choice Control Structures to allow some simple String modifications? Like so:

```php
   @lang('subscriptions', 2, 'ucfirst') // Subscriptions
   @lang('routes.feed', 'str_slug')     // your-subscription-feed
   @lang('routes.feed', 'str_slug:_')   // your_subscription_feed
```

**Comment by lukasgeiter** [comment]
I think this is rather unnecessary. You could just do this:

    {{ ucfirst(trans('subscriptions', 2)) }}
    {{ str_slug(trans('routes.feed')) }}
    {{ str_slug(trans('routes.feed'), '_') }}

**Comment by taiyaei** [comment]
:-1:  Agreed with Lukas, logic such as this in a localization function sounds off.
