### ISSUE TITLE
Very short Forbidden message by Laravel when using custom Authentication

### ISSUE THREAD

**Issue by prakharsingh95** [laravel/framework#8887]
When I wrote a custom `AuthController` with `postLogin(LoginRequest $request)`, `postRegister(RegisterRequest $request)`, etc (where `RegisterRequest` and `LoginRequest` are custom classes extending `App\Http\Requests\Request`), Laravel 5 simply outputs a **Forbidden** (401), no logs. 

It took me a while, but the problem was that I had not set `Authorize()` in `LoginRequest` (or `RegisterRequest` to return `true`. *Hence the forbidden*.

There is no bug when the code is logically correct, but I believe that more extensive logging should be present for the buggy case, as this can be frustrating to hunt down.

**Comment by lukasgeiter** [comment]
What kind of logging would you expect? Keep in mind that this is an error (similar to 404) that might occur quite a few times on a production application.

**Comment by prakharsingh95** [comment]
I meant that when a forbidden error (or some similar error, like authentication error)  is issued, it's hard to track which middleware caused it. A nice feature would be to determine where exactly the request was denied.
