### ISSUE TITLE
Faster Request

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#8889]
Currently Request class relies on Symfony Request - which is not bad while you use something like `$request->query->get('foo')`, but it is much slower when you use `$request->input('foo')` because it goes through at least 4 conditions and one cycle even before `array_get` which makes this handy method much slower (the benchmark is rough but it shows the difference).

![4](https://cloud.githubusercontent.com/assets/2423048/7805305/9115aa10-0391-11e5-929a-4744a6b4800c.PNG)

My proposal is to make an ImmutableRequest which cannot be modified after construction and stores all data as simple arrays or internal properties.

It could be used in most applications as far as they don't need to change Request properties in runtime.

````php
class ImmutableRequest implements RequestContract
{
//...
protected $input;

public function input($key = null, $default = null)
{
    return array_get($this->input, $key, $default);
}
//...
}

// ...

public function postFoo(ImmutableRequest $request)
{
    $request->input('foo');
}

public function postBar(Request $request)
{
    $request->request->set('bar', 1);
    //...
    $request->input('bar')
}
````

I can open a PR if you agree that this will help to improve performance

**Comment by GrahamCampbell** [comment]
This would be breaking for people, sorry.

**Comment by franzliedke** [comment]
How is introducing a new class breaking?
(This is also similar to what PSR-7 suggests. Might be relevant if moving in that direction is considered in the future.)

**Comment by GrahamCampbell** [comment]
> This is also similar to what PSR-7 suggests.

Taylor and I already discussed PSR-7. We have no plans to care about it's existence atm.

**Comment by franzliedke** [comment]
Fine. It's still not breaking.

**Comment by rkgrep** [comment]
How do you think it will break compatibilities if the new class can only be used by direct method injection where it is needed? The old Request class will still be available and used by default

**Comment by Arrilot** [comment]
:-1:  
You will need to make an anormous number of $request->input('foo') calls in a single controller action to feel any difference. 
It's pretty confusing to have another request class too.
Just not worth it imho.

It's possible to have it as a package, isn't it?

**Comment by GrahamCampbell** [comment]
:-1: too

**Comment by barryvdh** [comment]
Or just use `$request->query->get()` and `$request->request->get()`?

**Comment by rkgrep** [comment]
@barryvdh I would like to, but mostly in controllers I have probability of both plain and json requests - that is where `$request->input()` is very useful.

Well - it's just a proposal to provide a simplified faster variant of Request class.

Anyway - what about implementing a Request and Response contracts? E.g. to implement one in [`Application::handle()`](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L734)

**Comment by yadakhov** [comment]
I think going to spend some time to see if array_get() which calls Arr->get() can be optimize.

**Comment by yadakhov** [comment]
Reading this issue led me to try to improve Arr::get() and I got about 25% faster.  https://github.com/laravel/framework/pull/8902

**Comment by stevestock** [comment]
@rkgrep What benchmark tool / website is that?

**Comment by rkgrep** [comment]
@stevestock Here it is: https://github.com/nicmart/Benchmark
