### ISSUE TITLE
Poor Internal Documentation

### ISSUE THREAD

**Issue by jjanusch** [laravel/framework#8909]
I'm using Laravel for the first time and I'm noticing the documentation within the code itself is rather poor in most instances. I've noticed this quite a bit while trying to figure out how Eloquent relations are defined and work (since the site docs aren't overly clear about it, which will hopefully be improved in 5.1).

A few examples:

[MorphTo#212](https://github.com/laravel/framework/blob/7fb8c6735bcfba46a87b6713cdb4468bd053a825/src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L212)
```
	/**
	 * Create a new model instance by type.
	 *
	 * @param  string  $type
	 * @return \Illuminate\Database\Eloquent\Model
	 */
	public function createModelByType($type)
```

The documentation for that method is the method name in sentence form. It's a simple method, but it doesn't say what Model `$type` is, whether it be an instance of the polymorphic model (i.e. "Comment") or the associated model (i.e. "Posts")

[MorphTo#238](https://github.com/laravel/framework/blob/7fb8c6735bcfba46a87b6713cdb4468bd053a825/src/Illuminate/Database/Eloquent/Relations/MorphTo.php#L238)
```
	/**
	 * Get the dictionary used by the relationship.
	 *
	 * @return array
	 */
	public function getDictionary()
```
Just a few lines lower, you see this. The doc, again, says the function name with the added "by the relationship", which isn't overly helpful since the class itself extends `Relation`.

Those two docs add nothing at all of value to the method and just reword the method name. They're both fairly pointless to have and should either be expanded on or removed.

[Model#941](https://github.com/laravel/framework/blob/7fb8c6735bcfba46a87b6713cdb4468bd053a825/src/Illuminate/Database/Eloquent/Model.php#L941)
```
	/**
	 * Define a many-to-many relationship.
	 *
	 * @param  string  $related
	 * @param  string  $table
	 * @param  string  $foreignKey
	 * @param  string  $otherKey
	 * @param  string  $relation
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function belongsToMany($related, $table = null, $foreignKey = null, $otherKey = null, $relation = null)
```
This one is a little more excusable since there is a bunch of comments within the code itself, but the comments do not show up in the API documentation ([see here](http://laravel.com/api/5.0/Illuminate/Database/Eloquent/Model.html#method_belongsToMany)) making the actual technical docs for that method completely useless.

[Query\Builder#432](https://github.com/laravel/framework/blob/7fb8c6735bcfba46a87b6713cdb4468bd053a825/src/Illuminate/Database/Query/Builder.php#L432)
```
	/**
	 * Add a basic where clause to the query.
	 *
	 * @param  string|array|\Closure  $column
	 * @param  string  $operator
	 * @param  mixed   $value
	 * @param  string  $boolean
	 * @return $this
	 *
	 * @throws \InvalidArgumentException
	 */
	public function where($column, $operator = null, $value = null, $boolean = 'and')
```

One of the most frustrating things about using Laravel so far has been the lack of argument documentation, as seen in above and in the `belongsToMany()` example. You can figure out what `$boolean` is, but it's a poor name with no documentation whatsoever. I had to spend 10 minutes explaining to a colleague that `$boolean = 'or'` is the same as Doctrine's `->orWhere()`. It just didn't click and, according to him, the lack of documentation about it was confusing for him. If you look back at `belongsToMany()`, which key is `$foreignKey` and which is `$otherKey`? I managed to figure it out after digging through the source a bit and running some tests, but why is it not clearly stated with the argument declaration in the docs? Why are really generic variable names like `$otherKey` and `$boolean` being used?

----

I really like Laravel. Once I figure something out, it is much, much faster than the work I was previously doing in Silex. But the problem is I have to sit there reading through code and testing it for 45 minutes to figure out how to properly define a one-to-many polymorphic relationship both ways. The site docs aren't very complete, and I know they are being worked on for 5.1, but it would be somewhat forgivable if things within the code were adequately documented.

**Comment by franzliedke** [comment]
Yeah, I agree that most descriptions could be improved. That is a lot of work, though. =)

**Comment by jjanusch** [comment]
For sure it is. It's definitely not something I expect to be improved for next release or anything. Just voicing concerns and pointing out areas that I've noticed are lacking is all.

**Comment by amitailanciano** [comment]
This would also require a lot of initial work and future maintenance, but It would be awesome if all the magic `__call`'ed methods all over Laravel were doc blocked with `@method`. It's frustrating enough having to use 3rd party tools like ide-helper at all, and yet *still* not having code completion for things like `ModelName::findOrFail`, and the methods available on `..Query/Builder` that are still callable from `...Eloquent/Builder`

**Comment by ChangePlaces** [comment]
People can always add comments to the code themselves and submit pull requests instead of wishing.

**Comment by FractalizeR** [comment]
@GrahamCampbell Will phpdoc documentation improvements be accepted as PRs? I just thought that may be they are left out because of maintainability costs. I really miss them and I would make PR or two with phpdoc improvements, if it desired.

**Comment by GrahamCampbell** [comment]
> Will phpdoc documentation improvements be accepted as PRs

Probably yeh. Please send to the 5.1 branch. :)

**Comment by franzliedke** [comment]
@FractalizeR How about a coordinated PhpDoc improvement effort some time in the coming weeks?

**Comment by GrahamCampbell** [comment]
Sounds good. Please don't send 100s of PRs though. 2 or 3 PRs would be really awesome. :)

We really appreciate your contributions. :)

**Comment by franzliedke** [comment]
Well, Taylor also doesn't like huge PRs... what do you guys want? ;)

**Comment by FractalizeR** [comment]
@franzliedke Yep, why not? We can create an organization for that and fork laravel repo there for shared use. I guess there should be a PR per each Laravel subsystem unless it is too big.

**Comment by GrahamCampbell** [comment]
> Well, Taylor also doesn't like huge PRs... what do you guys want? ;)

PRs that are not massive and atomic, but not loads of them.

For example, dealing with the database component separately might be a good idea.

Ping @taylorotwell. Only Taylor can decide what he wants. :)

**Comment by ibrasho** [comment]
I would suggest a WIP PR, so people could give feedback gradually.

I vouch for what @GrahamCampbell said, start will one component, to establish the rules and figure out what Taylor wants, before trying to improve the whole framework.

**Comment by kodeine** [comment]
Maybe we should all start sending pull requests.

**Comment by nanaya1** [comment]
is possible to at least provide link to source file (at github)? That would help speed up figuring what a method does (at least from web browser)

**Comment by FractalizeR** [comment]
@nanaya1 I don't think this is related to improving phpdoc comments.

**Comment by nanaya1** [comment]
@FractalizeR at least it'll help changing the current api on web from "quite useless" to "less useless"...

**Comment by ArjanSchouten** [comment]
I agree that the phpdocs and comments in the code can be improved. However it can be hard to maintain and slow down development when you've to maintain large phpdocs. I know that it can be hard because of backwards compatibility but descriptive names are quite better.
