### ISSUE TITLE
different view data when using mail::queue over mail::send

### ISSUE THREAD

**Issue by leoncottell** [laravel/framework#8915]
Using Laravel 4.2.9

Swapped mail::send for mail::queue, leaving everything else the same and started getting errors in my views.

Turns out any objects in the data passed to the view get turned into an arrays when you call ::queue so you need to change the view to reference arrays instead of objects.

e.g.

$model = Invoice::find($id)
Mail::send('ViewName', ['model'=>$model], function($message) use ($filename, $model, $to, $from, $title)
	        {
	            $message->from($from, '---');
	            $message->subject($title);
	            $message->to($to);
	            $message->attach($filename);
	        }); 

Then in the view I used : 

{{ $model->supplier->company }}

Works fine for Mail::send, but after swapping that out for Mail::queue the objects in the view data are converted to arrays, so 

{{ $model->supplier->company }}

would need to be

{{ $model['supplier']['company'] }}

I think this is probably by design, but not mentioned in the docs anywhere and took me quite a while to figure out what was going on - maybe just need to add a note to the docs.

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported.

**Comment by phaza** [comment]
This applies to 5.1 too.

**Comment by GrahamCampbell** [comment]
You can't serialise models.

**Comment by phaza** [comment]
Isn't that the whole point of this class? https://github.com/laravel/framework/blob/5.1/src/Illuminate/Queue/SerializesModels.php

**Comment by wunc** [comment]
I can confirm that this behavior also occurs in 5.1. Mail::send works perfectly, but Mail::queue with the exact same parameters fails with "Trying to get property of non-object".

**Comment by Sladewill** [comment]
If I'm not mistaken Mail::queue didnt work in 4.2/4.1 and untried on 5.0/5.1 but you could always just use a normal queue and do Mail::send from that.

**Comment by GrahamCampbell** [comment]
> Isn't that the whole point of this class? https://github.com/laravel/framework/blob/5.1/src/Illuminate/Queue/SerializesModels.php

No. That class DOES NOT serialize models as such. That class is used for things going through the command bus only, and it provides a way to avoid serializing models.

**Comment by GrahamCampbell** [comment]
You can't use that trait with mail unless you were to make yourself a mail "job" that calls the "send" method.

**Comment by phaza** [comment]
According to the [documentation](http://laravel.com/docs/5.1/queues#writing-job-classes):
> In this example, note that we were able to pass an Eloquent model directly into the queued job's constructor. Because of the SerializesModels trait that the job is using, Eloquent models will be gracefully serialized and unserialized when the job is processing. If your queued job accepts an Eloquent model in its constructor, only the identifier for the model will be serialized onto the queue. When the job is actually handled, the queue system will automatically re-retrieve the full model instance from the database. It's all totally transparent to your application and prevents issues that can arise from serializing full Eloquent model instances.

There's no reason why Mail::queue shouldn't use the same idea: Serialize models by key, and load them when rendering the message.
