### ISSUE TITLE
Dynamic Route Based Middleware

### ISSUE THREAD

**Issue by mreschke** [laravel/framework#8917]
According to this issue https://github.com/laravel/framework/issues/6211 you guys did give us the ability to add dynamic global middlware via the new kernel functions pushMiddleware() and prependMiddleware() which is great!

But we still need the ability to add dynamic route based middleware too.  Without this feature, packages cannot define their own middleware and we are forced to resort to Laravel 4 style Filters instead.

**Comment by GrahamCampbell** [comment]
Those kernel methods are public, and packages can call them.

**Comment by GrahamCampbell** [comment]
If there's something specific we're not doing, we're open to PRs.

**Comment by mreschke** [comment]
I know, I use them all the time to define "global" middlware.  But how to add non global, route based (ie with a key...basically appending to the protected $routeMiddleware) dynamically.   ??

**Comment by crynobone** [comment]
You could just add it in your package service provider (boot method).

```php
public function boot(\Illuminate\Routing\Router $router)
{
    $router->middleware('name', 'MiddlewareClass');
}
```

**Comment by mreschke** [comment]
Great! I was not aware you could register them dynamically.  The docs say nothing about it.  Would be an easy doc update in http://laravel.com/docs/5.0/middleware#registering-middleware

**Comment by mreschke** [comment]
Course the docs say nothing about pushMiddlware and prependMiddleware either.  Guess taylor doesn't want that level of detail in the docs.  Generally he mentions multiple ways to "register" something, either from the easy standard method, or some dynamic alternative.  I would imagine at least a mention of $router->middleware and push/prepend registers in the more advanced http://laravel.com/docs/5.0/packages at least.  I will PR the docs and see what he thinks.

**Comment by mreschke** [comment]
PR https://github.com/laravel/docs/pull/1479
