### ISSUE TITLE
middleware options not getting through

### ISSUE THREAD

**Issue by sebastiansipos90** [laravel/framework#8928]
Hello,

I have a problem using parameters on middleware on laravel 5.1@dev
I've created a test scenario: composer create-project laravel/laravel --prefer-dist
Upgraded to 5.1 following the instructions from here: http://laravel.com/docs/master/upgrade (only the two steps)
```bash
$ pa
Laravel Framework version 5.1-dev
...
```

On App\Http\Controllers\WelcomeController:
```php
/*...*/
class WelcomeController extends Controller {
/*...*/
	public function __construct()
	{
		$this->middleware('guest', ['test', 'test2']);
	}
/*...*/
```

On App\Http\Middleware\RedirectIfNotAuthenticated:
```php
/*...*/
class RedirectIfAuthenticated {
/*...*/
	public function handle($request, Closure $next, $params)
	{
		print_r($params);
                /*
		if ($this->auth->check())
		{
			return new RedirectResponse(url('/home'));
		}

		return $next($request);
                */
	}
/*...*/
```

And I get:
`Missing argument 3 for App\Http\Middleware\RedirectIfAuthenticated::handle(), called in /home/sebi/workspace/5.1test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php on line 125 and defined`

According to this: 
http://laravel.com/api/master/Illuminate/Routing/Controller.html#method_middleware , I should get the parameters there. What does the "options" parameter mean?

However, if I try the way specified here: http://laravel.com/docs/master/middleware#middleware-parameters , it all works. The problem is that I need that parameter to be in the constructor of the controller.

I tried to implement this for users permissions, like in the example.

I've tried to fix it myself, but there are multiple closures there and I don't have the time to debug.

**Comment by GrahamCampbell** [comment]
That's not how middleware params work?

**Comment by sebastiansipos90** [comment]
that was helful, thanks.

**Comment by rspenc29** [comment]
I had the same issue so I dug into the `ControllerDispatcher` and it looks like the options that you can pass into `Controller::middleware()` are only used to filter out the request action by passing `except` or `only` with an array of action names. So it seems at this time you cannot pass additional parameters to route middleware by adding the middleware from the controller. I guess we have to stick to filters for that.

**Comment by sebastiansipos90** [comment]
Hello,

Thanks for the feedback. I've dug through it, too, and have noticed that. I
think it's pretty useless for that param not to get through. I managed to
get my data through to the middleware using the Config class.. pretty lame
but I didn't have the time for anything else. Oh well...
