### ISSUE TITLE
Problems with UTF-8 encoding in Eloquent

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#8935]
Hi, I'm trying to output my Model as Json, but it doesn't work for certain results from the Database. The JSON error I get is `Malformed UTF-8 characters, possibly incorrectly encoded`. 

The character that's probably causing this problem is `►`.

**Comment by GrahamCampbell** [comment]
This is a "no fix" I'm afraid due to the nature of json.

**Comment by CupOfTea696** [comment]
Is there any way to prevent this? Maybe a string function to replace any dangerous characters?

**Comment by GrahamCampbell** [comment]
Yeh, there is. Ask on the forums please and someone can help you there.
