### ISSUE TITLE
HasManyThrough on a many-to-many relation feature (code included)

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#8938]
I needed a hasManyThrough relationship where what I wanted to key on was a many-to-many relationship. Of course this wasn't possible using the current hasManyThrough, so I made a new relation class called HasManyThroughPivot which implements this feature. For reference, my use case was for model ```piece```, which was used in a bom in ```component``` and several ```components``` made up a ```product```. From ```piece``` I wanted to see all the ```products``` it was used in, hence the hasManyThroughPivot. 

https://gist.github.com/ChangePlaces/8231b4e1d4d76562c337

Not gonna lie, the class is a mess as I copied it from the HasManyThrough, and is only half done (go take a look at all those dies), but for the most basic of use, it works. Maybe someone more knowledgeable can finish it off. I've only been using Laravel for a week or so and wanted to at least put something out there that could be the start.

The first method lives in a base model class (I think it's good practice for all models to extend a base model class of your own, even if it's empty, and I put the HasManyThroughPivot class inside the app dir. I'm sure someone can suggest a better setup!

I think Laravel could benefit from such a relation!

**Comment by cryode** [comment]
My company has a use case for this as well. We putzed around with creating a similar relation class, but it started to take a lot of time, so we forewent it for a round-about solution in order to push our product.

Would be cool to see at least how this could be properly implemented. Even as a third party package, this would be useful to at least some developers. :)

**Comment by Fl0ux** [comment]
I need this too !

**Comment by drawmyattention** [comment]
Can't you achieve this using the existing relationship definitions? See the sample (none complete) code below:

    class Piece extends Model {
      public function components() {
          return $this->belongsToMany('Component');
      }
    }

    class Component extends Model {
        public function pieces() {
            return $this->hasMany('Piece');
        }
        public function products() {
            return $this->hasMany('Product');
        }
    }

    class Product extends Model {
        public function components() {
            return $this->hasMany('Component');
        }
    }

    // Get all products with their components and pieces
    $products = Product::with('components.pieces')->get();

    // Get all pieces with their components and products
    $pieces = Piece::with('components.products')->get();

Or alternatively. to get all products which have a piece name of 'piecename':

    $products = Product::whereHas('components.pieces', function($q) {
        $q->where('pieces.name', 'piecename');
    })->get();

**Comment by cryode** [comment]
@drawmyattention Sure, you can use that to retrieve the necessary rows, but at the expense of:

1. Queries. You don't *need* the middle man in this case, so why require the overhead of fetching and mapping all of those entities?

2. Usability. A `hasManyThrough` relationship gives you the ability to say "My Product has many Components, which has many Pieces. I want to get all the Pieces for a product by using the `$product->pieces` syntax." Using existing solutions forces you to loop through every Product's Components, retrieve their pieces, then merge them into a collection, ensuring that you prevent duplicates and the like.

**Comment by mattmcdonald-uk** [comment]
Would also find this useful. Currently working around it with a less clean solution.

**Comment by GrahamCampbell** [comment]
Thanks for the report, but we don't process feature requests. We are, however, open to PRs.
