### ISSUE TITLE
Add feature to Session::forget() so you can forget specific value in session array

### ISSUE THREAD

**Issue by Oleander2911** [laravel/framework#8940]
There is this feature `Session::push('user.teams', 'developers');` which adds some value to a session array, the problem is that you are only able to remove the whole array with Session::forget() and not just a single value inside the array.

So what im seeking is a feature that does the same as 
`unset($_SESSION['thesessionarray']['keyofarray'])`

And that would remove or unset the value inside the session array with that specific key.

**Comment by cryode** [comment]
I don't know if this could be implemented without leaving potential edge cases for developers. For example, how would you know what the resulting key is after `Session::push('user.teams', 'developers');`? What if you have more than one identical array value - which one do you remove? Do you remove all of them?

**Comment by GrahamCampbell** [comment]
Yeh, this is probably a no-fix.
