### ISSUE TITLE
Laravel 4.2 App::finish doesn't run after response is returned.

### ISSUE THREAD

**Issue by yantolee** [laravel/framework#8946]
I was trying to do some lengthy processing on the backend after a response is returned to the client using App::finish but apparently what happened is that it actually wait for the processing to finish and then the response only get sent to the client.

Tried to put a dd('test) inside the App::finish, and in fact I received the response followed by the "test" string.

The laravel 4.2 docs say "The finish event is called after the response from your application has been sent back to the client"

Hope someone can shed some light regarding this. Thanks

**Comment by GrahamCampbell** [comment]
4.2 isn't supported anymore. The forums might be a good place to ask though. :)

**Comment by yantolee** [comment]
Sorry about that. Will head over to the forum for this matter. Thanks
