### ISSUE TITLE
[5.x][Suggestion] Change to ::class keyword for name resolution

### ISSUE THREAD

**Issue by xeno010** [laravel/framework#8954]
[5.x][Suggestion] Change to ::class keyword for name resolution.

Hello,

PHP 5.5 is required now ( #https://github.com/laravel/framework/commit/8349040e7381d083868fa40bd7dcaf301f0347e3 ). PHP >= 5.5 has a ::class keyword  for name resolution.

I suggest that we should use it (by default).

E.g.

```php
// 1. Model relations
public function category() 
{
        return $this->belongsTo('Intranet\Models\Category');
}

// 2. Middleware
protected $routeMiddleware = [
	'auth' => 'Intranet\Http\Middleware\Authenticate',
	'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
	'guest' => 'Intranet\Http\Middleware\RedirectIfAuthenticated',
];

// 3.
$this->app->singleton('Illuminate\Contracts\Queue\EntityResolver', function()
{
      return new QueueEntityResolver;
});
```

Change to:

```php
// 1. Modal relations
public function category() 
{
        return $this->belongsTo(Category::class);
}

// 2. Middleware
protected $routeMiddleware = [
	'auth' => Authenticate::class,
	'auth.basic' => AuthenticateWithBasicAuth::class,
	'guest' => RedirectIfAuthenticated::class,
];

// 3.  'Illuminate\Contracts\Queue\EntityResolver'
$this->app->singleton(EntityResolver::class, function()
{
      return new QueueEntityResolver;
});
```

Pro:
- easy to write (IDE autocomplete)
- good for refactoring
- good for "Go To Declaration"
- good for "Find used"
- and and and

Negativ:
- ???

**What do you thing?**

**Comment by lukasgeiter** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Sounds good to me to have this changed on laravel/laravel. I doubt we'd be wanting to make these changes within laravel/framework though. :)

**Comment by lukasgeiter** [comment]
@GrahamCampbell why not in the core as well? What disadvantages or problems do you see in that?

**Comment by GrahamCampbell** [comment]
Because we don't accept mass changes that don't actually fix things.
