### ISSUE TITLE
Inconsistent date handling in an Eloquent model when a accessor exists.

### ISSUE THREAD

**Issue by Flightfreak** [laravel/framework#8958]
When a field is configured as a date, it will be cast as a Carbon date when calling up on the property, and be returned as a storeable string when the model is being converted to an array.

However, when you create a accessor for this property, Eloquent ignores the dates configuration and always returns the return value of the accessor. This is inconsistent behavior. When I don't want it to be cast, I should not have the field in the dates property.

The current Eloquent logic makes it impossible to use dates and accesors on date fields in a consistent way.

The [```mutateAttributeForArray```](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php#L2679) function could do an additional dates check and cast if required to solve this.

Any thoughts on this?

**Comment by cryode** [comment]
I don't know if I'd call it inconsistent, but I can certainly see a use case for wanting to return a different value from an accessor during a `toArray()` transformation.

One change that would support your use case would be to flip the dates and mutated attributes compiling within [`attributesToArray()`](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/Model.php#L2389). That would be a backwards compatibility issue, though, and it would also require you to have accessors *and* modify the `$dates` array, which just seems unnecessary.

A new feature that would encompass both your use case and anyone who wished to modify their accessors for `toArray()

**Comment by Flightfreak** [comment]
Aye, that is the underlying issue, to distinguish between array mutation and regular accessing.
However, imho in this particular case, one should not have the property in the dates array, if it should not  be handled as a date like laravel does, irrespective of an existing accessor.

**Comment by franzliedke** [comment]
I'm not one hundred percent sure whether I understand your issue.

If I read the code correctly, the [`attributesToArray()` method](https://github.com/laravel/framework/blob/42b3f4ce73a58ebb29399a40aa9f381fd77b45f1/src/Illuminate/Database/Eloquent/Model.php#L2384-2439) first checks whether the requested attribute is a date and then passes that to the accessor.

In constrast, the [`getAttributeValue()` method](https://github.com/laravel/framework/blob/42b3f4ce73a58ebb29399a40aa9f381fd77b45f1/src/Illuminate/Database/Eloquent/Model.php#L2577-2612) returns `DateTime` objects immediately without passing them to any accessor...

Is that the problem? Or am I misreading something here?

**Comment by Flightfreak** [comment]
The problem is the hard string cast of the Carbon object in the attributesToArray() function. The accessor, being called after, has no idea the model is working towards an array, and will just return a Carbon instead of a string.

**Comment by witsu** [comment]
Why did you close this issue? I would consider it as a bug.
