### ISSUE TITLE
Task Scheduling and output

### ISSUE THREAD

**Issue by raulp** [laravel/framework#8961]
Hey guys

While playing with the scheduler from Laravel, i found out that sendOutputTo($file) creates the file if it does not exists, however, if it does exists, truncates it.
I could see why this is happening, especially when combined with emailOutputTo($email), so that way you get the latest cron output.

Does anyone thinks we should have a new function, like appendOutputTo($file) or logOutputTo($file) for people that just wanna store cron logs ?

**Comment by GrahamCampbell** [comment]
We don't process proposal issues, sorry. If something's small, just PR it. If it's large, contact Taylor directly to ask for advice.
