### ISSUE TITLE
[5.1] Proposal: migration transactions

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#8966]
Currently migrations provide `--pretend` option to dump sql queries, but it is hard to check if migrations properly run on different databases.

I propose to add `--transaction` option to wrap migration into transaction - so it can't ruin the database in case of error during testing.

**Comment by FractalizeR** [comment]
Remember, that not all database statements can be executed in transaction. There are many restrictions on this in MySQL. Even Postgres has some unexpected ones like inability to execute `ALTER TYPE ... ADD VALUE` in transaction.

**Comment by GrahamCampbell** [comment]
@FractalizeR's pretty much floored this idea.
