### ISSUE TITLE
Return data from queued event handlers

### ISSUE THREAD

**Issue by SnehalAmbab** [laravel/framework#8969]
Hello,

I have code like this

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldBeQueued;

class DataHandler {

	public function handle(DataEvents $dataEvent)
	{
		$event = $dataEvent->event;
		$data = $dataEvent->data;

		if($event == 'dataHandler2') {
		} else if($event == 'dataHandler') {
			$data_vals = $data['data_vals'];
			$id = $data['id'];
			return $this->dataHandler($data_vals, $id);

		}
	}
	private function dataHandler($data_vals, $id) {
		//something...
               return array('data1' => 'test1');
        }
}

Above code works perfectly and return the respective data.

But when I implements "ShouldBeQueued", the handler doesnt returns any data.

Anyone please help me.

Thank you

**Comment by GrahamCampbell** [comment]
Yes, of course nothing is returned. It hasn't been executed yet.

**Comment by SnehalAmbab** [comment]
How do we execute the same?

**Comment by GrahamCampbell** [comment]
> How do we execute the same?

I have no idea what you mean?

**Comment by SnehalAmbab** [comment]
I want to return the respective data when the specific event gets fired.

**Comment by GrahamCampbell** [comment]
> I want to return the respective data when the specific event gets fired.

You can't if it's been queued.

**Comment by GrahamCampbell** [comment]
Also, returning the data is a bad anyway if you want to more closely follow ddd.

**Comment by SnehalAmbab** [comment]
Suppose I want to save the data in database, return the respective inserted data and email the user.

In such case what should I do ?
Please guide me for this

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
