### ISSUE TITLE
Unable to mock Config::get()

### ISSUE THREAD

**Issue by ctrlaltdylan** [laravel/framework#8979]
Unable to successfully mock `Config::shouldReceive('get')->with('my_testing_param_here');` because it asks for database configurations from `Config::offsetGet('database.default');` and then `Config::offsetGet('database.connections');`. These shouldn't be asked for when unit testing.

**Comment by GrahamCampbell** [comment]
Ask on the forums pleas.

**Comment by ctrlaltdylan** [comment]
@GrahamCampbell sorry about that, but it's not a problem with my specific implementation that's why I'm reporting it here.

I created a forum post with a little more detail but basically the gist of it is that you cannot mock `Config::get()` in isolation:

http://laravel.io/forum/06-01-2015-unable-to-mock-configgetmy-config-param

**Comment by crynobone** [comment]
What wrong with simple Config::set()
