### ISSUE TITLE
Input:file wrong counting

### ISSUE THREAD

**Issue by djchrispurple** [laravel/framework#8986]
//      get all the files to upload in an array
        $files=Input::file('images');
//      count the number of files to upload
        $files_count = count($files)

The problem I face is that even if I don't select any file to upload I still got the array $files created.
when I do dd($files) and I don;t select any file in the form I got
array:1 [▼
  0 => null
]
So I found a way to overcome this issue but I would like to know if there is a simpler way:
//      count the files to upload check if the first element is null
        if(count($files)==1 and $files[0]==null){$files_count=0;}else{$files_count=count($files);}
Thanks for your help.

**Comment by Sladewill** [comment]
You might want to ask this on the laravel forums http://laravel.io/forum

**Comment by djchrispurple** [comment]
ok thanks
