### ISSUE TITLE
Custom Blade directive stopped working

### ISSUE THREAD

**Issue by talyssonoc** [laravel/framework#8990]
I developed a Laravel package for allowing serverside rendering with React, called [react-rails](https://github.com/talyssonoc/react-laravel), and it was working well.

But then, last week, I've done a `composer update`, so Laravel was upaded too (I use `5.0.*` Laravel version at my project) and it stopped working. It did't broke the app, but the directive `@react_component` just doesn't get replaced by what I programmed it to be in the `Blade::extend`.

Did Laravel had some change recently that would make it happen ? I noticed that `Extending Blade` is not present in the 5.0 docs, just in the 4.0 and master.

**Comment by GrahamCampbell** [comment]
You're going to have to tell us which version it was working on, and which version it's not working on.

**Comment by GrahamCampbell** [comment]
And we're going to need detail. We need the exact version change, not a large jump. We can't debug that.

**Comment by Arrilot** [comment]
You have probably updated to Laravel 5.1.

Blade extending has been reworked in 5.1.
Unfortunately it's a big BC break if you use it in your package =(

You can check this PR https://github.com/laravel/framework/pull/8482 and the workaround I've found instead of maintaining two different git branches for Laravel 5.0 and 5.1 https://github.com/Arrilot/laravel-widgets/blob/master/src/ServiceProvider.php#L119

**Comment by GrahamCampbell** [comment]
> You have probably updated to Laravel 5.1.

Apparently not:

> (I use 5.0.* Laravel version at my project) and it stopped working

**Comment by GrahamCampbell** [comment]
You have the wrong version constraint in your package. `~5.0` would assume laravel follows semver, which it does not.

**Comment by talyssonoc** [comment]
Yeah, I know, but I think it is not a reason to close the issue, more users may be having this problem with their directives stopping working.

Should I change the dependency to `5.0.*` then ?

**Comment by GrahamCampbell** [comment]
Yes, but it's a bit late now, because composer will just install an old version of your package because you marked it as compatible with all 5.x releases.

**Comment by talyssonoc** [comment]
@GrahamCampbell, I've created a new dev version and installed it, and my test app uses `"laravel/framework": "5.0.*"` and it still does not work, so I guess it is not the cause ?

**Comment by talyssonoc** [comment]
@GrahamCampbell @Arrilot I'm trying to use the Laravel 5.1 syntax (in a Laravel 5.1 project) in this branch: https://github.com/talyssonoc/react-laravel/tree/laravel_5_1, but it does not work either (it just doesn't render, it just gets `@react_component(<parameters>)`  rendered on the view. What can be the cause ?

**Comment by younes0** [comment]
@talyssonoc @Arrilot has a clean workaround: https://github.com/Arrilot/laravel-widgets/blob/master/src/ServiceProvider.php#L119

I bet this issue will be locked soon ;)

**Comment by talyssonoc** [comment]
Thanks, @younes0, that worked !
