### ISSUE TITLE
[5.1] Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#8993]
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L2268

Illuminate/Database/Eloquent/Model.php 2268

```php
/**
 * Determine if the model is totally guarded.
 *
 * @return bool
 */
public function totallyGuarded()
{
    return count($this->fillable) == 0 && $this->guarded == ['*'];
}
```
When you call create on a Eloquent model which should be forwarded to the query builder the error `Maximum function nesting level of '100' reached, aborting!` occurs.

Data is just an array of data and model is just an eloquent model that gets injected into the construct.

```php
// create product
$product = $this->model->create($data);
```

**Comment by GrahamCampbell** [comment]
Are you sure you haven't just used that many function calls?

**Comment by franzliedke** [comment]
That limit (from XDebug, it can be configured) is pretty easy to hit when using a bunch of middlewares...

**Comment by Sladewill** [comment]
Trying to debug where this is happening now, but its only since testing on 5.1 as of 5.0 it was fine.

**Comment by GrahamCampbell** [comment]
Right, but you might have been using 99 calls in laravel 5.0, and the upgrade to 5.1 tipped you over the limit you've configured.

**Comment by Sladewill** [comment]
Yeah its entirely xdebug.

**Comment by franzliedke** [comment]
It's the default limit, though (or it was until recently), so we may see a bunch of these reports in the next days.

**Comment by prewk** [comment]
Same issue here. Circumvented by raising the limit.
