### ISSUE TITLE
[5.1] Console generator commands don’t use correct namespace

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#8997]
I’ve created a Laravel 5.1 application to check out the new version. I appreciate it’s still in development, but I’m noticed an issue with the `make:` console commands: they don’t insert the correct (full) namespace into new files.

I set my application namespace to `YourFightSite\OnDemand` using `app:name`. I then used `make:model` to create a model, but instead of using the full namespace, it’s instead just inserting `YourFightSite` (and omitting the `OnDemand` portion).

I haven’t observed this behavior in any of my up-to-date 5.0.x Laravel applications, so can safely say this is a 5.1-specific issue.

Are there any gotchas I should know of when using nested namespaces? Or is this a bug?

**Comment by Arrilot** [comment]
App namespace detection was re-factored in 5.1 to get rid of nasty and slow parsing of `composer.json` file. I can potentially make a PR addding nesting namespace support, no problem here. The question is - Is it really needed?

@taylorotwell Were nested application namespaces ever meant to be supported?

@martinbean Do you have any particular reasons to use nested namespace?  I can't make up any and it all seems kind of illogical to me

**Comment by martinbean** [comment]
@Arrilot Yes: I have multiple projects under the `YourFightSite` namespace. `YourFightSite` is the vendor name, `OnDemand` is the application name.

This isn’t a new thing; other projects have adopted the vendor–project namespace approach, so not “illogical” at all.

As I say, this works is 5.0.x, so I would expect nested namespaces to still work in 5.1.

**Comment by Arrilot** [comment]
Should be closed now.
