### ISSUE TITLE
[Feature Request] Translate Carbon by default

### ISSUE THREAD

**Issue by morloderex** [laravel/framework#9017]
Hello 

We already have both a great translate component and a great time/date package, but as of my knowledge we haven't yet translated the Carbon instances created by for instance the model, could this be done by laravel automatically when we for instance say App()->setLocale() or somewhere else in the application life cycle?

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by franzliedke** [comment]
Can we establish first whether such a pull request would have a chance of being accepted?

**Comment by GrahamCampbell** [comment]
> pull request would have a chance of being accepted?

Not a clue, sorry. You'll have to ask taylor directly. Don't create proposal issues, because Taylor doesn't read the issues anymore.

**Comment by franzliedke** [comment]
Well, I don't have the time to write pull requests without even knowing whether they get accepted. I'm sure I'm not the only one...

**Comment by GrahamCampbell** [comment]
As I said, ask them...

**Comment by GrahamCampbell** [comment]
As I said, ask then...
