### ISSUE TITLE
Schema migration generates two files

### ISSUE THREAD

**Issue by msonowal** [laravel/framework#9018]
after i have updated my framework
now whenever I generate a migration it generates two files  i.e. two migration for the same command

for e.g:
php artisan make:migration:schema create_editions_table
after that it created first

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEditionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('editions', function(Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('editions');
    }
}

then again
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEditionsTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('editions', function(Blueprint $table)
		{
			$table->increments('id');
			$table->timestamps();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('editions');
	}

}

both are exactly same but the starting bracket " { " at the same line as of the class name on the second file.

**Comment by lukasgeiter** [comment]
What exact version of the framework are you using?

**Comment by msonowal** [comment]
in my composer.json its
"laravel/framework": "5.0.*",
which i have updated to latest through composer update
I think it's a huge bug

**Comment by willrowe** [comment]
I have not been able to reproduce this. What is the exact version number (run `php artisan --version`)?

**Comment by msonowal** [comment]
php artisan --version
Laravel Framework version 5.0.32

**Comment by Arrilot** [comment]
There is no 'make:migration:schema' command in Laravel framework, so this is a package issue.

**Comment by msonowal** [comment]
what you are talking about it is there
 make:migration:schema create_editions_table

**Comment by RomainLanz** [comment]
@msonowal  `make:migration:schema` is added with this package : https://github.com/laracasts/Laravel-5-Generators-Extended
