### ISSUE TITLE
Please consider dropping requirement on MCrypt.

### ISSUE THREAD

**Issue by remicollet** [laravel/framework#9020]
lilbmcrypt is a dead project, unmainted for ~7years.
Some Enterprise Distribution simply don't provide it (e.g. RHEL)

Relying  on a dead cow for cryptography just sounds terrible.

Please consider switching to openssl encryption which is much more common and wel maintained.

**Comment by GrahamCampbell** [comment]
We are using both openssl and mcrypt. Taylor would probably accept a PR to 5.1 to remove the need for mcrypt, though I can't speak for him.

**Comment by GrahamCampbell** [comment]
5.1 will be our next LTS release btw, and will ship on Tuesday next week.

**Comment by GrahamCampbell** [comment]
It's also php 5.5.9+ only. :)

**Comment by remicollet** [comment]
> It's also php 5.5.9+ only. :)

Which is fine ;)  RHEL (with RHSCL 2.0) provides 5.5.21 and 5.6.5 ;)
But not mcrypt

**Comment by GrahamCampbell** [comment]
> Which is fine

Great. I'd quite like to see us dropping mcrypt too. :)

**Comment by jbrooksuk** [comment]
Dropping mcrypt would be a great change! :)

**Comment by GrahamCampbell** [comment]
I'll talk to Taylor about this later today and see what he thinks. :)

**Comment by override-chaos** [comment]
:+1:

**Comment by taylorotwell** [comment]
If it can be done in a backwards compatible way, sure.

**Comment by ibrasho** [comment]
If I remove mcrypt dependency completely but end up with compatible encoding, is that fine?

**Comment by taylorotwell** [comment]
As long as it can decrypt stuff that was encrypted using the old mcrypt way.

On Wed, Jun 3, 2015 at 1:16 PM, Ibrahim AshShohail <notifications@github.com

**Comment by ibrasho** [comment]
`Encrypter::setCipher()` and `Encrypter::setMode()` will not be BC-compatible.

Is this acceptable?

**Comment by taylorotwell** [comment]
I'm fine with that.

**Comment by ibrasho** [comment]
Done #9041
