### ISSUE TITLE
[5.1] Namespaces don’t get updated in database factories

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#9027]
I’ve noticed that when I run the `app:name` command in Laravel 5.1, the namespace doesn’t get updated in files in **database/factories** (i.e. `App\User` stays as such).

If I were to fix this, which branch should I open a Pull Request against? [5.1][1] or [master][2]?

[1]: https://github.com/laravel/framework/tree/5.1/
[2]: https://github.com/laravel/framework/tree/master/

**Comment by GrahamCampbell** [comment]
5.1 please. :)
