### ISSUE TITLE
laravel 5 and aws

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#9042]
is there a preconfigured public image with laravel 5 and aws ami that comes recommended?

Searching for laravel on aws console, I can see the following image, with image description:
Webuzo 2.2.9 Laravel 4.2.9 Application Manager on LAMP Stack centos 6.5 x86_-ade7a751-6903-41c1-a39e-0dfd721eb002-ami-8e64d5e6.2

**Comment by GrahamCampbell** [comment]
Not that I'm aware of. Feel free to ask on the forums. :)
