### ISSUE TITLE
ServiceProvider contains harcoded view path, so config/view.php paths not working as expected

### ISSUE THREAD

**Issue by andrewdworn** [laravel/framework#9048]
In https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/ServiceProvider.php in line 76 <code>loadViewsFrom</code> function contains a hardcoded <code>'/resources/views/vendor/'</code> path for default package view path.

It caused me a headache since I changed the view path in <code>config/view.php</code> form <code>'resources/views'</code> to <code>'blades'</code>, and I wanted to override a package's view file. If this path is hardcoded like now, I have to recreate <code>'resources/views/vendor'</code> folder, and copy the view holder folder there to override the view in <code>'/vendor/../views'</code>.

The mentioned function is:
<pre><code>
/**
 * Register a view file namespace.
 *
 * @param  string  $path
 * @param  string  $namespace
 * @return void
 */
protected function loadViewsFrom($path, $namespace)
{
	if (is_dir($appPath = $this->app->basePath().'/resources/views/vendor/'.$namespace))
	{
		$this->app['view']->addNamespace($namespace, $appPath);
	}
	$this->app['view']->addNamespace($namespace, $path);
}
</code></pre>

Because <code>config/view.php</code> <code>paths</code> field is an array, and can hold many view folder paths, checking every one of them for vendor folder might not be a good idea. 

How about dedicating the first item of <code>paths</code> array for this purpose?

Something like this:
<pre><code>
protected function loadViewsFrom($path, $namespace)
{
	$viewpaths = $this->app['config']->get('view.paths', $this->app->basePath() . '/resources/views');
	if (is_array($viewpaths))
	{
		$viewpath = array_values($viewpaths)[0];
	}

	if (is_dir($appPath = $viewpath.'/vendor/'.$namespace))
	{
		$this->app['view']->addNamespace($namespace, $appPath);
	}

	$this->app['view']->addNamespace($namespace, $path);
}
</code></pre>

**Comment by GrahamCampbell** [comment]
This is intended. If you want to change it, override the service provider.
