### ISSUE TITLE
[5.1] Testing/CrawlerTrait submitForm() method sends wrong multi-dimensional fields.

### ISSUE THREAD

**Issue by Stolz** [laravel/framework#9052]
The method `submitForm()` from the trait `Illuminate\Foundation\Testing\CrawlerTrait.php` submits inconsistent multi-dimensional fields.

i.e:  if you use this code in one of your tests

    $this->visit('resource.create')->submitForm('send', ['options' => [0 => 1, 1 => 2]]);

your controller will get this input

	[
		"options[0]" => 1,
		"options[1]" => 2
	]

instead of the expected one

	['options' => [
		0 => 1,
		1 => 2
	]]

If instead of submitForm() other functions such `post()` or `put()` are used the sent input is correct.

# How to reproduce

Edit `app/Http/Kernel.php` and remove `'App\Http\Middleware\VerifyCsrfToken',` to disable CSRF middleware.

Add a route for a resource controller into `app/Http/routes.php`

	Route::resource('resource', 'ResourceController');

Create a resource controller

	php artisan make:controller ResourceController

Edit the created file `app/Http/Controllers/ResourceController.php`

		public function create()
		{
			return <<<'HTML'
	<!DOCTYPE html>
	<html>
		<body>
			<form method="POST" action="/resource">
				<input id="options1" name="options[]" type="checkbox" value="1" /> Option 1
				<input id="options2" name="options[]" type="checkbox" value="2" /> Option 2
				<input type="submit" value="send">
			</form>
		</body>
	</html>
	HTML;
		}

		public function store()
		{
			dd(\Input::all());
		}

Start server

	php artisan server

Visit <http://localhost:8000/resource>, check both checkboxes and submit form. You'll get

	['options' => [
		0 => 1,
		1 => 2
	]]

Edit file `test/TestCase.php` and set

	protected $baseUrl = 'http://localhost:8000';

Edit file `test/testBasicExample.php` and set

    public function testBasicExample()
    {
		$input = ['options' => [0 => 1, 1 => 2]];

		$this
		->visit('resource.create')
		->submitForm('send', $input);
    }

Run PHPUnit

	./vendor/bin/phpunit

You'll get

	[
		"options[0]" => 1,
		"options[1]" => 2
	]

instead of the expected

	['options' => [
		0 => 1,
		1 => 2
	]

Submitting the same form with the same data should  send consistent data in both testing and non-testing environment

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by Stolz** [comment]
Fixed by #9058
