### ISSUE TITLE
mediumInteger autoIncrement in sqlite fails

### ISSUE THREAD

**Issue by jildertmiedema** [laravel/framework#9057]
This functions does not work for sqlite (in memory)
```public function mediumInteger($column, $autoIncrement = false, $unsigned = false)```

The second argument is ```$autoIncrement``` but setting it to ```true``` will result in an error during insert.

I have created a gist to show the error:
https://gist.github.com/jildertmiedema/22a87b98b7078b141fc0

**Comment by rkgrep** [comment]
Fixed and merged to 5.1 #9113
