### ISSUE TITLE
[5.1-dev] openssl_cipher_iv_length(): Unknown cipher algorithm

### ISSUE THREAD

**Issue by Kryptonit3** [laravel/framework#9059]
did a composer update recently. now when trying to access site i get that error.

~~~
ErrorException in Encrypter.php line 45:
openssl_cipher_iv_length(): Unknown cipher algorithm
in Encrypter.php line 45
at HandleExceptions->handleError('2', 'openssl_cipher_iv_length(): Unknown cipher algorithm', '/home/vagrant/Projects/cw5/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php', '45', array('key' => 'sCyy0nXoipGeI5YLfKSSRs0l3taVBYRQ', 'cipher' => 'rijndael-128'))
at openssl_cipher_iv_length('rijndael-128') in Encrypter.php line 45
at Encrypter->__construct('sCyy0nXoipGeI5YLfKSSRs0l3taVBYRQ', 'rijndael-128') in EncryptionServiceProvider.php line 17
~~~

more details https://laracasts.com/discuss/channels/laravel/openssl-cipher-iv-length-unknown-cipher-algorithm

**Comment by GrahamCampbell** [comment]
You need t update your config.

**Comment by GrahamCampbell** [comment]
'rijndael-128' was the mcrypt name

**Comment by Kryptonit3** [comment]
@GrahamCampbell wonder why it just now became an issue? I saw that this was mentioned in a L4 upgrade.

http://laravel.com/docs/master/upgrade#upgrade-4.2

**Comment by Kryptonit3** [comment]
@GrahamCampbell  and my config says

~~~
	'cipher' => MCRYPT_RIJNDAEL_128,
~~~

**Comment by Francismori7** [comment]
I have the same issue - and my config also has this:

```php
'cipher'          => MCRYPT_RIJNDAEL_128,
```

**Comment by Kryptonit3** [comment]
issue resolved. - https://laracasts.com/discuss/channels/laravel/openssl-cipher-iv-length-unknown-cipher-algorithm

comment out or delete 
```
'cipher'          => MCRYPT_RIJNDAEL_128,
```

**Comment by GrahamCampbell** [comment]
> comment out or delete

**Comment by GrahamCampbell** [comment]
> comment out or delete

no, don't do that!

**Comment by Sladewill** [comment]
```php
'cipher' => 'aes-128-cbc',
```

If you want it to be fixed.

**Comment by GrahamCampbell** [comment]
>     'cipher' => MCRYPT_RIJNDAEL_128,

That config is wrong.

**Comment by GrahamCampbell** [comment]
> 'cipher' => 'aes-128-cbc',

^^^^ this is correct

**Comment by Kryptonit3** [comment]
@GrahamCampbell  you say `no don't do that!` to commenting it out or deleting it from `config/app.php` but if you look, [here](https://github.com/laravel/laravel/blob/develop/config/app.php#L70-L82) it doesn't exist there anymore. I guess Taylor moved it to the core code so it could be changed easier in the future?

**Comment by GrahamCampbell** [comment]
Please see https://github.com/laravel/laravel/commit/4c291abfe8bf6261692e1644ad26e22c406c3948.

**Comment by Kryptonit3** [comment]
Damn. that was quick. :)

**Comment by ibrasho** [comment]
Should not the encrypter use 'AES-128-CBC' if `app.config` is null?

**Comment by GrahamCampbell** [comment]
> Should not the encrypter use 'AES-128-CBC' if app.config is null?

Not anymore, no.

**Comment by GrahamCampbell** [comment]
> Not anymore

Not in any tagged releases, and not in the upcoming 5.1.0 release either.

**Comment by GrahamCampbell** [comment]
Only was for a short time in 5.1-dev.
