### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 46

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#9071]
I have the following route.php
```php
Route::resource('/api/v1/message', 'MessagingController',
                ['only' => ['store']]);
```

with the following snippet from my resource controller
```php
	public function store($messageID)
	{
        return 'creating '.$messageID;
    }
```

When I attempt to POST to http://localhost:8000/api/v1/message I get the following exception

```html
TokenMismatchException in VerifyCsrfToken.php line 46:
```

This issue is discussed here
https://laracasts.com/discuss/channels/general-discussion/csrf-form-token-doesnt-match-session-token

however, that discussion is using forms to post data. I'm building an API that will receive POST data.

**Comment by GrahamCampbell** [comment]
Ask on the forums only please.
