### ISSUE TITLE
add a queue:stop command

### ISSUE THREAD

**Issue by Grummfy** [laravel/framework#9083]
Hi,
It could be usefull to add a queue:stop command.

## Today
Now we have a queue:restart that restart a queue (or stop a queue:work --daemon) but nothing to stop it. We can launch a listener or a worker, and it's easy.
When we want to stop it we need to search the process id and kill it. The queue is stopped but not in a clean way and can break the current process.

## Why stopping it?
We need to stop it because we have redeployed our code (if we use a deployer that use symlink restart is not enough).
Because we want to stop for any reason.

## Extra
Having the possibility to kill only queue on some connection or that are related to a specific queue name.
It should stop gracefully the queue

**Comment by rkgrep** [comment]
+1

**Comment by GrahamCampbell** [comment]
`php artisan down` `php artisan queue:restart`

**Comment by GrahamCampbell** [comment]
We already have issues with the restart command. A PR to fix this would be cool.

Note that this is not me accepting this idea. I can't do that.

**Comment by nicktc** [comment]
I agree that it should be possible to stop a queue. Doing a 'php artisan down' makes the application shortly unavailable, which is not what I would like. Especially with Envoyer being a zero-downtime deployment tool.
