### ISSUE TITLE
Collection shuffle not working, array_shuffle() is not a function

### ISSUE THREAD

**Issue by jeffwalsh** [laravel/framework#9084]
Hey y'all. 
The Collection's shuffle method is broken right now, unless you change

    public function shuffle()
       {
          $items = $this->items;

        array_shuffle($items);

        return new static($items);
       }

to

    public function shuffle()
      {
        $items = $this->items;

        shuffle($items);

        return new static($items);
       }

**Comment by GrahamCampbell** [comment]
We're open to PRs. :)

**Comment by jeffwalsh** [comment]
I've actually never done a pull request before. Also, I was in error, as the completed fix is:  
   
    
    
    /**
     * Shuffle the items in the collection.
     *
     * @return static
     */
    public function shuffle()
    {
        shuffle($this->items);

        return $this;
    }

if you return a new static, it loops endlessly and the Collection times out after 30 seconds.
I'm going to figure out how to submit this as a pull request and do so now!

**Comment by GrahamCampbell** [comment]
Don't sorry. I can make the change for you. :)

**Comment by GrahamCampbell** [comment]
```php
/**
 * Shuffle the items in the collection.
 *
 * @return static
 */
public function shuffle()
{
    shuffle($this->items);

    return $this;
}
```

That's not correct.

**Comment by GrahamCampbell** [comment]
We want the collection class to be immutable.

**Comment by GrahamCampbell** [comment]
See #9085. :)

**Comment by jeffwalsh** [comment]
Sorry, I'm not exactly a wiz programmer, hehe - I just made it work enough so that I could keep developing! :P Is this what you're looking for?
  
    public function shuffle()
    {
        shuffle($this->items);

        return new static($this);
    }

**Comment by GrahamCampbell** [comment]
We still can't do `shuffle($this->items);` has that would modify the array in place.

**Comment by jeffwalsh** [comment]
Ah, I see. So my original fix was the correct one.
The timeout I was experiencing was due to Vagrant after all. I put the original back in and it works.
Thanks much, Graham!

**Comment by GrahamCampbell** [comment]
As I said, please see https://github.com/laravel/framework/pull/9085.
