### ISSUE TITLE
Elixir copy

### ISSUE THREAD

**Issue by antonybudianto** [laravel/framework#9086]
Hello,

Does anyone have successfully using elixir copy function to copy files to "public/build/..." ?
Because I need to copy fonts folder to the newly generated folder "public/build" after versioning process, the console log said success but the files or folder is not copied. The fonts folder needed to be read by font-awesome.
Any solution besides manually copying the folder to public/build?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
