### ISSUE TITLE
who did this?

### ISSUE THREAD

**Issue by imbubble** [laravel/framework#9089]
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L389

```php
$table->float('fk'); // the field is double in the table.
```

why did this ?? so weird...

**Comment by GrahamCampbell** [comment]
Not sure what you mean? It's just an alias function?

**Comment by imbubble** [comment]
4.2 vs 5.0

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L389
```php
protected function typeFloat(Fluent $column)
{
	return "float({$column->total}, {$column->places})";
}
```

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L389
```php
protected function typeFloat(Fluent $column)
{
	return $this->typeDouble($column);
}
```

it is the 'double' type in the table when im trying to add one column use '$table->float('field_name')' in the migration file.
v4.2 is normal...

**Comment by imbubble** [comment]
here is my migration file:
```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UserAlter extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('user', function(Blueprint $table)
        {
            $table->float('asdf')->after('tt')->unsigned()->index();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('user', function(Blueprint $table)
        {
            $table->dropColumn('asdf');
        });
    }

}
```

**Comment by imbubble** [comment]
@GrahamCampbell plz open this issue.
