### ISSUE TITLE
[bug] migration 'float' function generated a 'double' type.

### ISSUE THREAD

**Issue by imbubble** [laravel/framework#9103]
im trying to add a type of 'float' field to a user table using 'float()' functoin.
but i got a type of 'double' field instead of 'float' after 'php artisan migrate' command.

here is my migration file:
```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UserAlter extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('user', function(Blueprint $table)
        {
            $table->float('asdf')->after('tt')->unsigned()->index();
            //the 'asdf' field should be 'float' type, but it is double... so weird
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('user', function(Blueprint $table)
        {
            $table->dropColumn('asdf');
        });
    }

}
```

v4.2 is normal...

4.2 vs 5.0

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L389
```php
protected function typeFloat(Fluent $column)
{
	return "float({$column->total}, {$column->places})";
}
```

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L389
```php
protected function typeFloat(Fluent $column)
{
	return $this->typeDouble($column);
}
```

is it a bug? plz fix it...

**Comment by GrahamCampbell** [comment]
Not a bug. This is correct. See https://github.com/laravel/framework/commit/0c0a717052d8326e7e032e5181019b91926b76a8.

**Comment by imbubble** [comment]
@GrahamCampbell okay, then how could i get a type of 'float' field? plz help, thanks.

**Comment by GrahamCampbell** [comment]
Ask on the forums please. It's definitely possible though, given the method has a first parameter where you can set the size of the data.

**Comment by imbubble** [comment]
@GrahamCampbell i tried, not work. 
could u open this issue? i think it's a bug. 
the alias function, 'typeFloat',  will always return the 'typeDouble' function. 

but the problem is 'typeDouble' function always return a 'double' type. 
u could check the source code. 

and plz open this issue... thanks.

**Comment by GrahamCampbell** [comment]
A double IS a float if you tell the database how many bytes you want there to be.

**Comment by imbubble** [comment]
i tried $table->float('asdf', 4), still got a double.
do u mean that i should config the mysql server? if not, plz just give me some code... thanks

**Comment by GrahamCampbell** [comment]
Ask on the forums.
