### ISSUE TITLE
Blueprint does not throw an exception if an unknown method is called

### ISSUE THREAD

**Issue by stefanmajoor** [laravel/framework#9105]
When you call an not existing method on the blueprint, it simply ignores it. It would be better if an exception is thrown. This makes debugging easier

e.g.
```
		\DB::transaction(function () {
			\Schema::table('users', function (Blueprint $table) {
				$table->removeColumn('username');
			});
		});
```

This migrations should fail, and throw an exception that the method 'removeColumn' can not be found. At this time this migration will pass. This results in an unexpected state of the database, and a mismatch between the status of the tables and the executed migrations - i.e. the migration has been run, but the column is still present in the table.

**Comment by GrahamCampbell** [comment]
What laravel version please.

**Comment by lukasgeiter** [comment]
But `removeColumn` does exist!!

**Comment by stefanmajoor** [comment]
> But removeColumn does exist!!"

That is exactly the problem. It does not exists. Yet it does not say so, and pretends that the migration finished correctly.

It should throw an exception or so indicating that it does not exist.

Laravel version is 5.0

**Comment by GrahamCampbell** [comment]
So you're saying the column you're removing doesn't exist?

**Comment by lukasgeiter** [comment]
The *method* does exist. [Proof](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Schema/Blueprint.php#L825-L839)

**Comment by stefanmajoor** [comment]
Hm, is there any reason for it being public? It happened to me more than once that I accidentally called that method instead of dropColumn, which results in the column not being dropped.

**Comment by GrahamCampbell** [comment]
> Hm, is there any reason for it being public? 

Yes. So you can call it...
