### ISSUE TITLE
[5.0] Subdomain redirects cause redirect loop

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#9108]
When I redirect to a route from my subdomain, it causes a redirect loop. The Admin Middleware does a `redirect()->route('home');` when the user is not an admin, but instead of redirecting to example.com it redirects to /admin.example.com

Excerpt from my routes.php:

```php
Route::group(['domain' => 'admin.' . config('app.domain'), 'middleware' => ['admin']], function() {
    
    get('/', ['uses' => 'AdminController@index', 'as' => 'admin.index']);
    
});

get('/', ['uses' => 'HomeController@index', 'as' => 'home']);
```

**Comment by rkgrep** [comment]
This is not a bug.
Routes defined without domains are applied to any domain connected to your app.

E.g. `get('/foo', ...);` will work on both `http://domain/foo` and `http://admin.domain/foo`

When you try to resolve URL to such route, the system cannot determine which domain to use and uses current one.

You should define base domain group.

````php
Route::group(['domain' => config('app.domain')], function() {

    get('/', ['uses' => 'HomeController@index', 'as' => 'home']);

});
````

**Comment by CupOfTea696** [comment]
I didn't know that, thanks for the help!
