### ISSUE TITLE
Error in Response::make for png file

### ISSUE THREAD

**Issue by kummerer94** [laravel/framework#9116]
Hey everyone,

I'm trying to output a png image via Laravel (I'm doing something for every page view this image gets) and ran into this strange behaviour:

This is my code for the Response in the controller:

```php
$response = Response::make(File::get(public_path() . '/img/myfile.png'), 200);
return $response->header('Content-Type', 'image/png');
```
The file is there and has no errors (as I can easily view it through my local filesystem).

When I'm trying to view the page in the browser it says: image can't be shown due to an error. The same happens for me when I'm trying to download the image via

```php
return Response::download(public_path() . '/myfile.png');
```

When trying the whole thing with PDF files, everything works for me. There is no error nor any problem downloading the file.

I tried outputting a .txt file via the browser and checked if there is any whitespace added (therefore messing up the image): nothing.

Are there any more sources where this could come from?

I'm using Laravel 4.2 with this composer require config:
"laravel/framework": "4.1.\*",
"laravelbook/ardent": "2.\*",
"barryvdh/laravel-debugbar": "1.\*",
"ezyang/htmlpurifier": "4.6.\*",
"mews/purifier": "dev-master",
"jyggen/curl": "dev-master"

**Comment by erayaydin** [comment]
You cannot create image with Laravel. For this you need GD extension of PHP. I think there is some Laravel-GD packages on packalyst. Also [Intervention/image](https://github.com/Intervention/image) package will also work.

**Comment by kummerer94** [comment]
When trying the following I get the same error:

```php
$response = Response::make(new Imagick(public_path() . '/img/stipnetz.png'), 200);
```

**Comment by Sladewill** [comment]
Firstly laravel 4.2 isnt support anymore, secondly ask on http://laravel.io/forum
