### ISSUE TITLE
Eloquent save() not working after switching from MyISAM to InnoDB

### ISSUE THREAD

**Issue by khurramIlyas** [laravel/framework#9125]
I'm using Laravel 4.2. I have just converted all tables of `MySQL` database from `MyISAM` to `InnoDB` by issuing following command:
    `ALTER TABLE month_fees ENGINE=InnoDB;`
Following code was working fine before converting table engine to InnoDB:
```
    $m = MonthFee::where('id', Input::get('h_mf_id'))->first();
    $m->deposit_date = $data['depositDate'];
    $m->deposit_amount += $data['depositAmount'];
    $m->relaxation += $data['relaxation'];
    if($m->save()){
        Log::info('saved'.$m->deposit_date.'amount='.$m->deposit_amount);
    }
```
But now, it is not updating table in database. Apparently, Eloquent/Laravel gives no error. As you can see on success of `save()` I logged some variables, Even these values are logged in Log file.

When I only changes table engine back to `MyISAM`, everything starts working fine.

Eloquent is extracting data from db absolutely fine but can't insert, update or delete any record & surprisingly not throwing any error. I even logged query to see if Eloquent is issuing update command & I found that Eloquent is issuing update command too.

What's wrong here? I tried a lot of things but no luck.

**Comment by GrahamCampbell** [comment]
4.2 is not supported.

**Comment by khurramIlyas** [comment]
Can you please explain a little bit. What do you mean by "4.2 not supported", are you suggesting me to move on to Laravel 5 or do you mean that Laravel 4.2 is no more supported in this forum?

**Comment by lukasgeiter** [comment]
This is no forum. Github issues are for bug reports and feature proposals.
4.2 is not supported anymore, only security fixes will be backported. You might get help on the "real" [forum](http://laravel.io/forum) or on StackOverflow etc
