### ISSUE TITLE
Missing method Illuminate\Contracts\Routing\Registrar::controller[s]

### ISSUE THREAD

**Issue by guiwoda** [laravel/framework#9129]
Method `Illuminate\Contracts\Routing\Registrar::controllers()` is used through the `Route` Facade but not declared in the interface, only in the implementation (`Illuminate\Routing\Router`).

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by guiwoda** [comment]
Would you mind leaving a link to the original?

**Comment by GrahamCampbell** [comment]
You've already posted a comment on the original.

**Comment by GrahamCampbell** [comment]
Oh right, my bad. If you'd like to propose we add a method to a contract, please send a PR to 5.1 or 5.2 as always. Please don't create issues about it.

**Comment by GrahamCampbell** [comment]
Issues are to report bugs for the community to fix only as documented in the contribution guide lines.

**Comment by guiwoda** [comment]
:+1: I'll do that

**Comment by guiwoda** [comment]
Pull request: https://github.com/laravel/framework/pull/9131
