### ISSUE TITLE
[BUG] DB::table()->get()

### ISSUE THREAD

**Issue by sciasfreelancer** [laravel/framework#9130]
Whenever trying to get 160,000 rows, PHP-FPM throws 500 internal and crashes.
Column count: > 10
However using a simple query from bare php does not crash.
Also selecting 1 column also does not crash on both.
Selecting > 1 columns => crash

Machine: Windows 8.1
PHP: php for windows from php.net 5.6.9

**Comment by lukasgeiter** [comment]
Maybe try using [chunk](http://laravel.com/docs/5.0/queries#selects).

**Comment by sciasfreelancer** [comment]
I need to get all rows, not specific amount of them.
The idea is to get all rows and print it on image that displays a minimap afterwards

**Comment by lukasgeiter** [comment]
With `chunk()` you can process *all* records in.. well... chunks :wink:
