### ISSUE TITLE
[5.0] Using findOrFail on belongsToMany relations doesn't return pivot

### ISSUE THREAD

**Issue by stevebauman** [laravel/framework#9138]
For example:

    $role = $users->roles()->findOrFail(1);

    dd($role->pivot); // Returns null

However:

    $role = $users->roles()->find(1);

    dd($role->pivot); // Returns Pivot

Is this intended?

**Comment by lukasgeiter** [comment]
The reason for this is that the `BelongsToMany` relationship has a special `find` method, but no `findOrFail`. I'll fix that with a PR later...

**Comment by GrahamCampbell** [comment]
Thanks. :)

**Comment by stevebauman** [comment]
Cool thanks!

**Comment by stevebauman** [comment]
Shouldn't this be left open though since it hasn't been fixed yet? Maybe a tag indicating that it's in progress?

**Comment by lukasgeiter** [comment]
>Shouldn't this be left open though since it hasn't been fixed yet?

Just pushed the PR :wink:  #9143

**Comment by stevebauman** [comment]
That was quick! Nice! :+1:

**Comment by GrahamCampbell** [comment]
> Shouldn't this be left open though since it hasn't been fixed yet?

No, because we'd only forget about it, and it's common for contributors to not use the correct "Closes" syntax in their commit messages.

**Comment by lukasgeiter** [comment]
@GrahamCampbell Also `Closes` (or `Fixes`, etc) only work when the PR is merged into the default branch...

**Comment by GrahamCampbell** [comment]
I know. But this PR is to 5.1 which is not the default branch, and as I said, people often miss out "closes", "fixes". Also, I don't think it works when you put it in italics.

**Comment by lukasgeiter** [comment]
It would be a shame if it wouldn't work when put in italics. I surely expect a bit more from github :)

**Comment by bryannielsen** [comment]
I'm not sure if this is related, but using  `findOrFail()` off of a belongsToMany relationship is returning results for me, however it's throwing all the pivot data into the found model's attributes, including the pivot id.  

I'm on 5.1, for now I'm just dropping back to regular find(), I can raise a different issue if this is unrelated.

**Comment by stevebauman** [comment]
@bryannielsen Yup this is occurring to me as well. This should definitely be fixed as it has unintended results, and querying through relations is [advertised](http://laravel.com/docs/5.1/eloquent-relationships#querying-relations):

> Note that you are able to use any of the query builder on the relationship!

@GrahamCampbell Any intentions on fixing this any time soon?

**Comment by stevebauman** [comment]
A workaround for the time being is not using an ID key the same as your ID key in your pivot tables so your pivot data doesn't take over your main model attributes. In my opinion though, this should definitely be fixed.
