### ISSUE TITLE
[Bug] Always extending

### ISSUE THREAD

**Issue by sciasfreelancer** [laravel/framework#9142]
Using @extends() will always extend the template, even though I wrote to extend only if a value is true.

http://i.imgur.com/behC8Ne.png

```
@if($header)
    @extends('Templates.Layouts.SecureGame')
    @section('content')
        <div class="contentTitle">
            <a id="closeContentButton" class="contentTitleButton" href="dorf1.php">&nbsp;</a>
            <a id="answersButton" class="contentTitleButton" href="http://t4.answers.travian.com/index.php?aid=285#go2answer" target="_blank">&nbsp;</a>
        </div>
        <div class="contentContainer">
            <div id="content" class="positionDetails">
@endif
@section('header')
    <h1 {{$header ? 'class=titleInHeader' : ''}}>
        @if($info['is_oasis'])
            @if($info['player_id'] > 0)
                Occupied oasis
            @else
                Unoccupied oasis
            @endif
        @elseif($info['player_id'] > 0)
            {{$info['village_name']}}
        @else
            Abandoned valley
        @endif
        <span class="coordinates coordinatesWrapper">
            <span class="coordinateX">({{$info['rel_x']}}</span>
            <span class="coordinatePipe">|</span>
            <span class="coordinateY">{{$info['rel_y']}})</span>
        </span>
        <span class="mainVillage">@if($info['is_capital']) (capital) @endif</span>
        <span class="clear">&nbsp;</span>
    </h1>
@stop

@if($header)
    @yield('header')
@endif
@if($info['is_oasis'])
    <div id="tileDetails" class="oasis oasis-{{$info['image_num']}}">
@else
    <div id="tileDetails" class="village village-{{$info['field_maps_id']}}">
@endif
    @if(!$header)
        @yield('header')
    @endif

.....
Crappy code goes here
.....


@if($header)
    <div class="clear"></div>
    </div></div>
    <div class="contentFooter"></div>
    @stop
@endif
```

**Comment by sciasfreelancer** [comment]
Although, putting @extends() into separate blade view does the trick, but unfortunately makes more files to make and changes the logic inside controller.

Hopefully someone will fix this issue.

**Comment by willishq** [comment]
I think this issue is related to an issue I have encountered where if you comment out an `@extends` it still extends the page:

app.blade.php

```html
    <h1>Foo</h1>
```

'home.blade.php'

```html
{{--

@extends('app')

--}}

<h1>Bar</h1>

```

renders 

```html

<h1>Bar</h1>
<h1>Foo</h1>

```

as opposed to just rendering `<h1>Bar</h1>` as expected.

**Comment by fhferreira** [comment]
I remember the @extends need to be the first declaration in the blade file.

**Comment by fhferreira** [comment]
i use some like this:

@extends((( Request::ajax()) ? 'layouts.ajax' : 'layouts.default' ))

**Comment by GrahamCampbell** [comment]
You don't need so many brackets btw. :)

**Comment by sciasfreelancer** [comment]
So the bug remains unsolved. Great. 

@fhferria I don't use layout for ajax requests, because layout is provided after request by main layout witch this request was called from.

**Comment by fhferreira** [comment]
@sciasfreelancer the sample it's only for you see how i make when i use empty layout or extends the completly layout with yields + sections.

because i remember in the old versions of blade the @extends command need to be the first command in the blade file.
