### ISSUE TITLE
[proposal] Collection::min and Collection::max

### ISSUE THREAD

**Issue by tonglil** [laravel/framework#9144]
@taylorotwell closed https://github.com/laravel/framework/issues/2155 after saying they'll be added to `4.*`, however they are not present currently in `5.*` either.

To clarify, this is [`Support\Collection`](https://github.com/illuminate/support/blob/master/Collection.php), not [`Eloquent\Collection`](https://github.com/illuminate/database/blob/master/Eloquent/Collection.php#L92) (which does have the max/min methods).

My proposal: shift the current max-min methods to `Support\Collection` as `Eloquent\Collection` extends from the support collection.

The reason being, sometimes I create collections without querying the DB.

**Comment by tonglil** [comment]
If given the go-ahead, I can submit a PR.

**Comment by willrowe** [comment]
You probably won't get a go ahead. I'd just go ahead and submit a PR.
