### ISSUE TITLE
Error creating the source Testin

### ISSUE THREAD

**Issue by EliuFlorez** [laravel/framework#9146]
Creating Testin the origin of the route is always http: // localhost although set in config / app.php url => 'http: // localhost / laravel-app / public'

$this->response->original
![url](https://cloud.githubusercontent.com/assets/784787/8046969/774336fc-0e09-11e5-8886-56253d6fb39f.jpg)

![error-origen](https://cloud.githubusercontent.com/assets/784787/8046953/46330ee8-0e09-11e5-9194-228fb8fd3e81.jpg)

**Comment by GrahamCampbell** [comment]
You need to set the base url in the test case.

**Comment by EliuFlorez** [comment]
@GrahamCampbell ok. in case it is as you would? where I specify the url base. Sorry you do not find where it is. Greetings.
