### ISSUE TITLE
Read Write Connections cant fail anyone

### ISSUE THREAD

**Issue by ericcire** [laravel/framework#9151]
if the read write connections are set up, refer to http://laravel.com/docs/5.0/database#read-write-connections

When anyone of the connections failed, even the action is not related to the failed connection, like if the write connection failed, but only performs select statement to database, laravel will throw exception of PDO.

In other words, each request need to verify all the database connections, which may cause some network overhead.
And the application will fail, if one of the connections fail.

**Comment by dopesong** [comment]
Any news @taylorotwell ? Also what about multiple read slaves. Reconnection to other server if one failed and so on?

**Comment by GrahamCampbell** [comment]
Fixed.

**Comment by stevenmyhre** [comment]
Can you reference the changes made?  I am trying to test scenarios for when the write host is down - I should still be able to perform reads on the slave, right?  Not currently working on 5.1.  If the write host is down, it fails regardless of the query type being performed (read vs. write).  Can we defer the connecting until a query is performed?
