### ISSUE TITLE
Get Route Action

### ISSUE THREAD

**Issue by robjbrain** [laravel/framework#9153]
In Illuminate/Routing/Route there is a getAction() method which returns all actions but no way to get a specific action, besides the specific methods like getName() which gets the name of the route.

I propose that getAction() be rewritten and the original functionality replicated in a new getActions() method.

```php
public function getAction($key)
{
    return isset($this->action[$key]) ? $this->action[$key] : null;
}
public function getActions()
{
    return $this->action;
}
```

One benefit of this is that it would make it easier to use custom actions in the router. For instance someone might wish to add custom breadcrumb functionality like so:

```php
//Set the Route
Route::get('forums/category/{category}/{title}', array('as' => 'forums_category', 'uses' => 'ForumsController@getCategory', 'breadcrumbs'=>'category'));

//Get the breadcrumb action
$breadcrumbs = Route::current()->getAction('breadcrumbs')
```

This is of course one such example, i'm not suggesting that Laravel adds breadcrumb functionality. Only that it makes it easier to use and extend the current Routing functionality. 

Note on backwards compatibility: Just incase there was a problem with renaming the methods from getAction() to getActions() it would be simple enough to return getActions() should a $key not be set.

**Comment by lukasgeiter** [comment]
I suggest adding an optional parameter to `getAction()`. If something is passed, it will search for the action, otherwise all actions are returned.

**Comment by robjbrain** [comment]
@lukasgeiter yeah that works better actually. Good point.

**Comment by ibrasho** [comment]
Won't this be better?

```php
public function getAction($parameter = null)
{
    return array_get($this->action, $parameter);
}
```

**Comment by sciasfreelancer** [comment]
~~~Route::getCurrentRoute()->getAction();
Route::currentRouteAction();
Route::currentRouteName();~~~

**Comment by GrahamCampbell** [comment]
We're open to PRs.
