### ISSUE TITLE
Undefined offset: 1 on Route

### ISSUE THREAD

**Issue by blackburn1911** [laravel/framework#9154]
Hey,

This route returns Undefined offset: 1 on the line 200 from Illuminate/Routing/Route.php
```php
Route::get('/', [
        'as'   => 'home',
        'uses' => 'HomeController'
]);
```
Will be good a throw Exception instead a Notice and checking if @ exists on the uses key.

**Comment by lukasgeiter** [comment]
@GrahamCampbell I wouldn't say this is a bug. It's a proposal/request to improve the handling of a wrong `uses` option.

**Comment by GrahamCampbell** [comment]
Closing as a PR has been sent. Thank you everyone. :)
