### ISSUE TITLE
[5.1] Unit-tests started giving property $baseUrl missing error - after upgrade

### ISSUE THREAD

**Issue by shehi** [laravel/framework#9156]
Hey good folks,

After I upgraded my project (http://github.com/AudithSoftworks/Basis) from L5.0 to L5.1, I started getting errors similar to:

```
ErrorException: Undefined property: UsersControllerTest::$baseUrl

/home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:680
/home/shehi/Projects/Basis/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:598
/home/shehi/Projects/Basis/tests/UsersControllerTest.php:70
```

I did quick googling and following topic in Laracasts (not sure if related by solution helped me) at:
https://laracasts.com/discuss/channels/testing/undefined-property-testspathtomytestclasebaseurl

Adding ```protected $baseUrl = '';``` to my ```TestCase``` class solved the issue. I believe this problem needs addressing?

**Comment by johnwheal** [comment]
I also have this problem.

**Comment by GrahamCampbell** [comment]
Not a bug. You need to define that property from 5.1+.

**Comment by shehi** [comment]
@GrahamCampbell : Upgrade guide doesn't say so. Or did I miss something?

**Comment by GrahamCampbell** [comment]
The upgrading guide isn't comprehensive. There's a fair bit missed out. Taylor only wants the major stuff in there. I'm pretty sure it is mentioned on our docs somewhere though. :)

**Comment by GrahamCampbell** [comment]
> Upgrade guide doesn't say so. Or did I miss something?

You're meant to read the commits on laravel/laravel btw. That's the best way of staying up to date with changes that affect the default app.

**Comment by shehi** [comment]
@GrahamCampbell : Totally agreed. Though you very well know what I meant :D Thanks!

**Comment by basementjack** [comment]
Just a note that this is now included in the 5.0->5.1 upgrade documentation.
If anyone needs to know exactly what needs to be done, the documentation now clearly spells it out.
http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0 (do a find on "test" in your browser)

**Comment by todstoychev** [comment]
By the way I have the same problem with 5.1.32 as @shehi. I think that the ```$baseUrl``` MUST be taken from the ```config/app.php```.  There is an ```url``` key in the config array there.

**Comment by crynobone** [comment]
> I think that the `$baseUrl` MUST be taken from the `config/app.php`

Not 100%, I have tests that work 100% fine with `$baseUrl` set to `http://localhost` and `APP_URL` set to something else for VM (Vagrant).

**Comment by shehi** [comment]
@todstoychev Update your base TestCase file with the latest from laravel/laravel repo. It has new property with that name.

**Comment by rcadhikari** [comment]
just define the following line inside your TestCase Class
 `protected $baseUrl = 'your_application_url_here'`;
