### ISSUE TITLE
Redis session changes cache connection

### ISSUE THREAD

**Issue by ifduyue** [laravel/framework#9157]
Like described in #7896, if both session and cache are configured to use redis, but different redis dbs or different redis instances, all `Cache::` operations go througth the connection used by `Session::`. This makes Cache configuration meaningless. 

If you think this is a problem and should be fixed, I will send a pull-request.

**Comment by GrahamCampbell** [comment]
Looks like a bug to me. :)

**Comment by crynobone** [comment]
> Looks like a bug to me

Closed by mistake?

**Comment by GrahamCampbell** [comment]
> Closed by mistake?

Nope. Closed because a PR was offered. If I don't close it now, it risks being forgotten about and adds to the pile of issues we're not actually going to look at because there's too many.

**Comment by crynobone** [comment]
A tag with `"proceed with pr"` or something would be nice, and clearer.

**Comment by GrahamCampbell** [comment]
@crynobone I can't say that though, because I don't have permission to authorise PRs. I don't want to give the wrong impression otherwise people get annoyed when Taylor rejects PRs.

**Comment by lukasgeiter** [comment]
The problem with closing not fixed bugs is that people who are willing to fix them, won't easily find the issues. If I have some free time, I'll often browse all open issues to see if I find something to contribute.

**Comment by ifduyue** [comment]
@GrahamCampbell My PR was rejected, please reopen this issue so that someone else can fix it.

Thanks.
