### ISSUE TITLE
Middleware deprecated?

### ISSUE THREAD

**Issue by rookian1337** [laravel/framework#9158]
Why is there a `@deprecated` annotation in the `Middleware` interface?

I assume you mean that Filters are deprecated.

**Comment by GrahamCampbell** [comment]
Nope, those contracts are deprecated.

You don't need to implement the Middleware contract as of 5.0. It is marked as deprecated in 5.1, and will be removed in 5.2.

You don't need to implement the TerminableMiddleware contract as of 5.1. It is marked as deprecated in 5.1, and will be removed in 5.2.

**Comment by GrahamCampbell** [comment]
Middleware are very much staying for the future.

Filters were undocumented in 5.0, officially deprecated in 5.1, and have been removed for 5.2.

**Comment by rookian1337** [comment]
Ah, i see. Thanks!
