### ISSUE TITLE
[L5.1 LTS] Fresh-Command

### ISSUE THREAD

**Issue by netconception** [laravel/framework#9159]
Hello!

I've installed laravel in version 5.1.

After installation I can't execute "php artisan fresh" because the command is not found.

Is that command outdated ?

Greetings from Germany!

**Comment by jbrooksuk** [comment]
The command is still available... https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Console/FreshCommand.php

**Comment by jbrooksuk** [comment]
Looks like the command isn't registered in `ArtisanServiceProvider` - fixing and making a PR now :)
