### ISSUE TITLE
Illuminate/Contracts is missing a 5.1.* tag, causing composer errors

### ISSUE THREAD

**Issue by emitkowski** [laravel/framework#9165]
Looks like illuminate/contacts doesn't yet have a 5.1 release tag. I noticed this while trying to require an illuminate package independently of the framework. Anything with a dependency "illuminate/contracts" : "5.1.*" throws a composer error. Put an example below.

  Problem 1
    - Installation request for illuminate/mail 5.1.* -> satisfiable by illuminate/mail[v5.1.1].
    - illuminate/mail v5.1.1 requires illuminate/contracts 5.1.* -> no matching package found.
  Problem 2
    - Installation request for illuminate/log 5.1.* -> satisfiable by illuminate/log[v5.1.1].
    - illuminate/log v5.1.1 requires illuminate/contracts 5.1.* -> no matching package found.

**Comment by GrahamCampbell** [comment]
Yeh, you need to give us time to actually get this stuffed tagged up.The package tags are done manually by Taylor...

**Comment by emitkowski** [comment]
No problem. Not trying to rush you guys. I just wanted to give you a heads up if it just got missed. Thanks for the hard work.

**Comment by GrahamCampbell** [comment]
No worries. :)
