### ISSUE TITLE
Something is wrong with laravel compiled or with me

### ISSUE THREAD

**Issue by blackburn1911** [laravel/framework#9168]
Step 1. Use DB::table() in service provider, it works.
Step  2. php artisan clear-compiled. Refresh website. The website returns "Call to undefined method Illuminate\Support\Facades\DB::table()"
Step  3. Comment the code with DB::table() and refresh website. It works

**Comment by taylorotwell** [comment]
We would need more real code to diagnose anything.

**Comment by blackburn1911** [comment]
I use the **Core** class in the **enabledExtensions** method from **ExtensionsServiceProvider**. The **enabledExtensions** method is called in **register** method.

The problem is when I want to run "php artisan clear-compiled". Laravel returns me an error "Call to undefined method Illuminate\Support\Facades\DB::table()". Because Laravel can't create a new compiled.php file because there is an error, it's needed to comment the config method from Core class for generate a new compiled.php file.

Code: http://laravel.io/bin/1yyG6

**Comment by rkgrep** [comment]
You are probably trying to access database before it's connection is loaded.
Make sure you have your provider loaded after DatabaseServiceProvider and try to use `app('db')->table()`

**Comment by blackburn1911** [comment]
I solved the problem. I used DB::table in the service provider constructor. Now I use in the boot method and it works. Thanks and sorry for the mistake.
