### ISSUE TITLE
'cipher' => AES-256-CBC,

### ISSUE THREAD

**Issue by BlazeNikhilesh** [laravel/framework#9169]
<pre>
PHP Notice: Use of undefined constant AES - assumed 'AES' in /Applications/XAMPP/xamppfiles/htdocs/levigo/config/app.php on line 83
</pre>

Getting this error when updated to 5.1 .

How this is to be fixed??

**Comment by GrahamCampbell** [comment]
You forgot the quotes around the string. :)
