### ISSUE TITLE
All routes giving 500 server error - 5.1

### ISSUE THREAD

**Issue by BlazeNikhilesh** [laravel/framework#9170]
I upgraded to Laravel 5.1 and followed steps as provided in the upgrade documentation. All my routes have stopped working. All of them are giving 500 Server Error. 

What could be the problem??

**Comment by stuartmccord** [comment]
Check the log files, in 5.0 they were given a date stamped file name such as storage/logs/laravel-2015-06-09.log, I'm assuming they haven't changed.

FYI, you really should be asking this in the forums, you can log it here once you're fairly certain its a Laravel issue

**Comment by GrahamCampbell** [comment]
Also, you'll need to clear out your compiled routes file between upgrades.
