### ISSUE TITLE
InvalidArgumentException: Given expression is not a regex

### ISSUE THREAD

**Issue by sebastiaanluca** [laravel/framework#9173]
See https://github.com/laravel/framework/issues/7545

Could this still be an issue? Just did a fresh Laravel 5.1 installation and after copying over some files from another project, I get this error mixed in with my output.

The provided fix resolves the issue btw, but of course I don't know the rest of the story.
```php
foreach (Finder::create()->files()->name('/\.php$/')->in($app->configPath()) as $file)
```

**Comment by Icedroid** [comment]
I did a fresh install Laravel 5.1, when I visit http://loaclhost, I got this errror log.
And I don't know how to solve it ? Do I need to edit symfony vendor code?

**Comment by GrahamCampbell** [comment]
Can't replicate. Not enough information.

**Comment by swayok** [comment]
Got this issue after enabing xDebug
Here is trace
![image](https://cloud.githubusercontent.com/assets/629675/8576235/45cc6ba4-25a9-11e5-848a-420881ca4876.png)
Problem is in "*.php" expression

**Comment by GrahamCampbell** [comment]
What php version?

**Comment by swayok** [comment]
PHP 5.6 x86, xDebug 2.3.3

**Comment by GrahamCampbell** [comment]
> PHP 5.6

What patch version...

**Comment by swayok** [comment]
5.6.3

**Comment by GrahamCampbell** [comment]
Upgrade to 5.6.10 and tell me if it's still broken.

**Comment by swayok** [comment]
Updated to 5.6.10. Problem fixed.

**Comment by mikebronner** [comment]
I'm having this issue on php 5.6.10 as well. The regex fix above fixes the issue for me. Here is my PHP version: `PHP 5.6.10-1+deb.sury.org~trusty+1 (cli)`

**Comment by mikebronner** [comment]
This seems to conflict with the minimum requirement listed in composer.son as being PHP 5.5.9. Perhaps that needs to be updated, or this issue revisited? Are there any drawbacks to implementing the solution mentioned by the OP? Thanks :)

**Comment by GrahamCampbell** [comment]
> This seems to conflict with the minimum requirement listed in composer.son as being PHP 5.5.9. 

What? 5.5.10 is clearly newer than 5.5.9.

**Comment by mikebronner** [comment]
Exactly:  we can't run it on 5.5.9 without experiencing the exception. We should be able to, though.

**Comment by GrahamCampbell** [comment]
The composer.json just gives the minimum version needed to run MOST of the framework, in the same way we have suggested dependencies to get some stuff to work.

We always "suggest" you use the very latest version of php.

**Comment by mikebronner** [comment]
Understood :) Only meant to bring that to your attention if it needed to be addressed.

However, I am still having the original issue outlined above, that my process monitor still shows the exception as being thrown (but it doesn't abort the request). Obviously I would rather not trigger exceptions, if possible. :)

**Comment by sebastiaanluca** [comment]
I'm still having this issue during clean Laravel installs. Anything I can provide to help debug it?

**Comment by GrahamCampbell** [comment]
> I'm still having this issue during clean Laravel installs. Anything I can provide to help debug it?

Upgrade to the very latest php 5.6 release. I can be sure that you will not have an issues then.

**Comment by GrahamCampbell** [comment]
Or the latest 5.5 would be fine too. :)

**Comment by sebastiaanluca** [comment]
It's even worse now lol :D Now I'm seeing the exception trace in my views too.

    PHP 5.6.11-1+deb.sury.org~utopic+1 (cli)

**Comment by GrahamCampbell** [comment]
What about 5.6.13?

**Comment by sebastiaanluca** [comment]
php5 (5.6.11+dfsg-1+deb.sury.org~utopic+1 PPA for PHP 5.6:14.10/utopic [all])

Is the latest version using the custom Ubuntu repository, I find.

**Comment by sebastiaanluca** [comment]
Clean Homestead VM with `PHP 5.6.10-1+deb.sury.org~trusty+1 (cli)` and no more errors. I'm lost… :)

**Comment by sebastiaanluca** [comment]
@GrahamCampbell Do you have any thoughts on why I keep running into this issue? New VM (not Homestead) with PHP `5.6.14-1+deb.sury.org~trusty+1 (cli)`.

**Comment by mornone** [comment]
i got the same error,
php version above:
PHP 5.6.26 (cli) (built: Sep 17 2016 13:45:08)
could i solve the error without update PHP?
tkx!

**Comment by mornone** [comment]
i found i had opened xdebug in php.ini
i annotated it,laravel run ok,i opened it ,laravel run error

**Comment by efrenhz2016** [comment]
When xdegub is enabled, the config file must be match to workspace.
I'm using VsCode, this is my config in file launch.json 

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log":true,
            "pathMappings": {
                
               // "serverSourceRoot": "/var/www/html",
                //"localSourceRoot": "${workspaceRoot}"
                "/var/www/html":"/Users/{myuser}/{mysitefolder}"
                
            },
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}`
