### ISSUE TITLE
Upgrade to Laravel 5.1 - Method [validator] does not exist

### ISSUE THREAD

**Issue by BlazeNikhilesh** [laravel/framework#9177]
Last night, I upgraded my application from 5.0 to 5.1 . 

Everything seems to be working fine, except the registration. 

On entering the information, and registering, I get this error: 

    BadMethodCallException in Controller.php line 282:
    Method [validator] does not exist.

Not able to figure out where do I have to fix this.

**RegistersUsers.php**

        namespace Illuminate\Foundation\Auth;
        
        use Illuminate\Http\Request;
        use Illuminate\Support\Facades\Auth;
        
        
        trait RegistersUsers
        {
            use RedirectsUsers;
        
        public function postRegister(Request $request)
            {
                $validator = $this->validator($request->all());
        
                if ($validator->fails()) {
                    $this->throwValidationException(
                        $request, $validator
                    );
                }
        
                Auth::login($this->create($request->all()));
        
                return redirect($this->redirectPath());
            }
    }

**Controllers.php**

    public function __call($method, $parameters)
        {
            throw new BadMethodCallException("Method [$method] does not exist.");
        }

**Comment by RomainLanz** [comment]
Did you read the upgrade guide?

http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0
