### ISSUE TITLE
Defining package validators & problems concerning unit testing

### ISSUE THREAD

**Issue by Propaganistas** [laravel/framework#9178]
Duplicate of [this post](http://stackoverflow.com/questions/30750303/best-practice-for-defining-a-validator-in-a-package) on Stackoverflow, but I think that immediate contact with some high-level devs is justified.

----

Currently Laravel has three ways to add additional validator methods:

 1. Extend the validator using a closure:

    ```php
    Validator::extend('foo', function($attribute, $value, $parameters) {
        return $value == 'foo';
    });
    ```

 2. Extend the validator using a separate class:

    ```php
    Validator::extend('foo', 'FooValidator@validate');
    ```

    ```php
    class FooValidator {
        public function validate($attribute, $value, $parameters, $validator) {
            return $value == 'foo';
        }
    }
    ```

 3. Define a custom validator resolver:

    ```php
    Validator::resolver(function($translator,$data,$rules,$messages) {
        return new CustomValidator($translator,$data,$rules,$messages);
    });
    ```

    ```php
    class CustomValidator extends \Illuminate\Validation\Validator {
        public function validateFoo($attribute, $value, $parameters) {
            return $value == 'foo';
        }
    }
    ```

Thinking about defining a validator in a package, here's the catch:

 - option 1 (extend using a closure): if you need complex validation handling which most certainly should be split into several sub-methods, this options seems rather unusable to me.

 - option 2 (extend using a class): at first sight this seems to be the way to go. Note that the class should **not** extend `Illuminate\Validation\Validator` as it will throw errors concerning construction of the base `Validator` class. However this also throws a problem when implementing unit testing: for what I have found, the only way to test custom validator packages is by extension of the original `Validator` class with custom methods added to it.

 - option 3 (defining a resolver): this shouldn't be used in my opinion as it *replaces* the validator instead of *extending* it. Two packages defining their own resolver will simply override eachother rendering one of them unusable.

I'm the author of the [Laravel-Phone](https://packagist.org/packages/propaganistas/laravel-phone) package, and for now I went with option 2. As a workaround for the unit testing problem, I have defined all validation logic in a trait and created stub classes for production use and unit testing. It works perfectly, but it's rather unclean.

Hence my question: Am I overlooking something? What's the way to go to define validators in packages while still allowing other validator packages to work properly? Is there a cleaner way to solve the unit testing problem in option 2?

**Comment by Sladewill** [comment]
This is a question more suited for the laravel forums http://laravel.io/forum. But as a heads up unit testing packages like this may require the whole framework to install things such as the translations, validation, and the symphony components. If you do use the whole framework you have the ability to use Facade faking http://laravel.com/docs/5.1/testing#mocking-facades so you will only need to validate your own code and not have the tests relating to anything else.

**Comment by Propaganistas** [comment]
Thanks for your reply. I was using functionality of the framework itself (`$validator->passes()`) in the tests, but as you suggested it is better to directly call the class & method with some mocks.

This also allows to remove the previously created stubs I was talking about since the `passes()` call isn't necessary anymore.

Thanks.
