### ISSUE TITLE
Artisan app:name fails with fresh install of laravel

### ISSUE THREAD

**Issue by austinkregel** [laravel/framework#9183]
# Description 
When trying to change the application's namespace the command (`php artisan app:name <name>`) failed. It seems like it changed the namespaces of some or most of the files, I just wanted to make sure the bug was known.

# Recreation
Easiest way to recreate this is install a fresh version of laravel 5.1 then run `php artisan app:name somebackend` and the command will fail. I have tried this multiple times and I have updated composer, laravel, and the laravel installer just to make sure I'm not going nuts. 

## PHP error message
For anyone whose curious this is the error below
```php
PHP Fatal error:  Cannot redeclare class backend\Exceptions\Handler in /home/austin/public_html/app/Exceptions/Handler.php on line 43
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class App\Exceptions\Handler does not exist' in /home/austin/public_html/bootstrap/cache/compiled.php:1059
Stack trace:
#0 /home/austin/public_html/bootstrap/cache/compiled.php(1059): ReflectionClass->__construct('App\Exceptions\...')
#1 /home/austin/public_html/bootstrap/cache/compiled.php(1010): Illuminate\Container\Container->build('App\Exceptions\...', Array)
#2 /home/austin/public_html/bootstrap/cache/compiled.php(1536): Illuminate\Container\Container->make('App\Exceptions\...', Array)
#3 /home/austin/public_html/bootstrap/cache/compiled.php(833): Illuminate\Foundation\Application->make('App\Exceptions\...', Array)
#4 /home/austin/public_html/bootstrap/cache/compiled.php(1057): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application in /home/austin/public_html/bootstrap/cache/compiled.php on line 1059
```

**Comment by GrahamCampbell** [comment]
That error isn't very useful to us. That error is an issue with reporting the real error...

**Comment by austinkregel** [comment]
Okay so how can I give you something you can actually use?

**Comment by GrahamCampbell** [comment]
You're going to have to rename the exception handler and all references to it first, then try out the command.

**Comment by austinkregel** [comment]
Okay so that fixed the first error about redeclaring the class; however, there is now an issue about not being able to find "Class backend\Console\Kernel" which exists and I'm staring at right now. The namespace on the file is " backend\Console" and the class name is "Kernel".

**Comment by tkuijer** [comment]
Did you try 
````
composer dump-autoload
````
after renaming your application?

**Comment by austinkregel** [comment]
Yes nothing seemed to help which is the only reason I came to github.
