### ISSUE TITLE
Bug Report About Auth 

### ISSUE THREAD

**Issue by caolixiang** [laravel/framework#9184]
I have defined a redirectTo variable in AuthController beside use AuthenticatesAndRegistersUsers. But when I logged in(successfully), it still redirect to '/home' url.

As the document said

>
When a user is successfully authenticated, they will be redirected to the /home URI, which you will need to register a route to handle. You can customize the post-authentication redirect location by defining a redirectTo property on the AuthController.
>

I run my program in homestead latest, and my Laravel version is 5.1(Updated on 6.9)

Here's my code or AuthController:

```php

<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;

class AuthController extends Controller
{
   
    use AuthenticatesAndRegistersUsers;

    protected $redirectTo = '/';

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'getLogout']);
    }

    
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }

    protected function create(array $data)
    {
        return User::create([
            'real_name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
}

```

**Comment by caolixiang** [comment]
I've tried.
When I defined $redirectTo variable to '/', it always redirect me to '/home', but when I define it to something else, it effects.

```php

use AuthenticatesAndRegistersUsers;

protected $redirectTo = '/test2';

```

```php

Route::get('/test2',function(){
    return "Ok Ok";
});

```

My route file is like this:


```php

Route::get('/', 'WelcomeController@index');

Route::get('/home', 'HomeController@index');

```

**So** I think the bug is
When I define $redirectTo to '/', it doesn't effect and still redirect to '/home' as the trait expect.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
