### ISSUE TITLE
S3Exception in WrappedHttpHandler.php line 162 when using Storage::put();

### ISSUE THREAD

**Issue by EwanValentine** [laravel/framework#9185]
Hi folks,

Great work on v5.1! I'm just having a snag with the Storage facade when using S3. 

I have the following code in a controller:

```
        $file = $request->file('file');

        $extension = $file->getClientOriginalExtension();
            
        $filename = date('d-m-Y').'_'.$request->get('author').'.'.$extension;
        Storage::put($filename, $file);

```

However I get the following error when this code's his:

S3Exception in WrappedHttpHandler.php line 162:
Error executing "HeadObject" on "https://s3-eu-west-1.amazonaws.com/[REDACTED]/10-06-2015_my%20file.jpg"; AWS HTTP error: Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS'

Cheers in advance!

**Comment by GrahamCampbell** [comment]
Please take this up with flysystem.

**Comment by EwanValentine** [comment]
Apologies, for future reference for anyone else maybe struggling with this: curl setopt's are unsupported by HHVM 3.7, upgrading to nightly builds (3.8.0-dev) resolved this for the time being.
