### ISSUE TITLE
fresh command removed?

### ISSUE THREAD

**Issue by lorvent** [laravel/framework#9187]
in 5.1 `php artisan fresh` removed?

if so how can i remove all scaffolded files manually?
can anyone list all file names?

thanks.

**Comment by GrahamCampbell** [comment]
Yes, it's been removed, because there's very little to remove anymore from the default app.

**Comment by lorvent** [comment]
can you pls list what are the files to be removed?

**Comment by GrahamCampbell** [comment]
That's up to you.
