### ISSUE TITLE
BladeCompiler#compileStatements is never called

### ISSUE THREAD

**Issue by talyssonoc** [laravel/framework#9190]
I have a package that extends Blade with a directive, but it is not replacing it when the view is rendered.

I've checked the source code and noticed that it is done by the method [BladeCompiler#compileStatements](https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/View/Compilers/BladeCompiler.php#L263).

But when I [search for this method](https://github.com/laravel/framework/search?utf8=%E2%9C%93&q=compileStatements) in the source code, I noticed that it never gets called, is it right ?

**Comment by talyssonoc** [comment]
Never mind, just saw how it gets called.

**Comment by yulianovdey** [comment]
In case anyone else stumbles upon this, make sure to clear your cached views when trying to test your custom directive.
