### ISSUE TITLE
compiled.php is not portable between deployment targets

### ISSUE THREAD

**Issue by dzuelke** [laravel/framework#9195]
It uses `PreCompileCommand` without the `--skip_dir_file` option, so applications built in one environment to be deployed in another environment contain hard"coded" paths from the environment where the build occurred.

Example:

```
static::translator()->addResource('array', require '/tmp/build_dd40f31f287e50a947b28cc04088e5dc/vendor/nesbot/carbon/src/Carbon' . '/Lang/' . $locale . '.php', $locale);
```

This affects Heroku, Dokku, CloudFoundry, anyone building on a CI server for deployment elsewhere, ...

Suggested fix is to invoke `compile` with the `--skip_dir_file` option.

**Comment by lukasgeiter** [comment]
Already put to discussion: #8776

**Comment by franzliedke** [comment]
Why close this again? You'll get this request over and over again, it's a very valid use case.

@taylorotwell didn't seem to be entirely against this idea in #8776.

**Comment by dzuelke** [comment]
A build should be portable. If you want this optimization out of the box, please figure out a way to do it at app startup time.

I don't see what the problem is with using that flag when invoking. It's a micro-optimization that breaks entirely reasonable use cases and workflows.

**Comment by franzliedke** [comment]
@dzuelke We'll have to open a new issue then.

Civil disobedience FTW. :)

**Comment by dzuelke** [comment]
All hail @ibrasho ! :)
