### ISSUE TITLE
ModelNotFoundException thrown when unserializing an unsaved eloquent instance

### ISSUE THREAD

**Issue by sebdesign** [laravel/framework#9196]
When `SerializesModels` unserializes an eloquent instance which does **not exist** in storage, a `ModelNotFoundException` is thrown.

```php
$user = new User;
$user->email = 'info@example.com';

$this->dispatch(new SendReminderEmail($user));
```

```
[Illuminate\Database\Eloquent\ModelNotFoundException]
No query results for model [App\User].
```

Maybe during the `__sleep` process we should check if the `QueueableEntity` instance exists (has an identifier), e.g. by checking the `exists` property of the eloquent model instance before creating a new `ModelIdentifier`.

**Comment by GrahamCampbell** [comment]
Yes, this is the expected behaviour. If you've deleted the model in the db you can't access it again.

**Comment by sebdesign** [comment]
When you delete a model, the exists property is set to false, but the
identifier is still set. In that case this behavior makes sense.

It's not the same as an instance that has not been saved yet. There is no
id so it shouldn't try to find it in the db.
