### ISSUE TITLE
Models fields property to specify attributes that should be saved

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#9197]
I was thinking that it might be nice to have a `$fields` property on Models that defines the fields in the Database table, and then when the model saves, it only inserts / updates the attributes that are in the fields array. 

This can be done by either modifying the save method, or internally adding and extra property (e.g. metadata) that would contain all data of attributes that don't need to be saved (basically splitting up the attributes property into attributes and metadata)

I can create a PR if interested.

**Comment by lukasgeiter** [comment]
For metadata you can just add a public property to your model. Since then it won't be set in the `attributes` array it won't be saved to the database.

    class FooBar extends Model {
        public $meta;
    }

    $foobar = new FooBar;
    $foobar->meta = 'Lorem ipsum';
    $foobar->stored = 'Lorem ipsum dolor sit amet';
    $foobar->save();

`stored` will be saved, `meta` won't.

**Comment by CupOfTea696** [comment]
True, but it'd still be useful in situations where you don't know all the properties that'll be set (e.g. dynamic properties)

**Comment by GrahamCampbell** [comment]
Sorry, there doesn't seem to be much interest. Perhpase making this into a package might be an option?
