### ISSUE TITLE
Issue with new install of Laravel 5.1.1

### ISSUE THREAD

**Issue by omnilord** [laravel/framework#9199]
Previously documented here: https://github.com/laravel/framework/issues/8829

There is no compiled.php file in our file system at the moment.  These errors come out of a fresh install on a new system when following the instructions provided here http://laravel.com/docs/5.1#installation

    Notice: date_default_timezone_set(): Timezone ID '' is invalid in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 41

    Fatal error: Call to undefined method Illuminate\Foundation\Bootstrap\ConfigureLogging::configureHandler() in /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/ConfigureLogging.php on line 66

All I know from doing some debugging is that if you change this line: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L41

from
     date_default_timezone_set($config['app.timezone']);

to
    date_default_timezone_set($config['config.app.timezone']);

It fixes the Timezone notice.

As for the fatal error, can someone explain what my entire team missed during install?  We each had a go at installing, and we each got the same error on our own servers.

Thanks!

**Comment by rkgrep** [comment]
I have launched both installations: via laravel/installer and composer create-project.
No errors occured.

Config cannot contain `config` key - `$config['app.timezone']` is proper.

Try to dump `$this->getConfigurationFiles($app)` before https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php#L55
It should look like
````
array:12 [▼
  "app" => "E:\Work\Code\test-l51\config\app.php"
  "auth" => "E:\Work\Code\test-l51\config\auth.php"
  "broadcasting" => "E:\Work\Code\test-l51\config\broadcasting.php"
  "cache" => "E:\Work\Code\test-l51\config\cache.php"
  "compile" => "E:\Work\Code\test-l51\config\compile.php"
  "database" => "E:\Work\Code\test-l51\config\database.php"
  "filesystems" => "E:\Work\Code\test-l51\config\filesystems.php"
  "mail" => "E:\Work\Code\test-l51\config\mail.php"
  "queue" => "E:\Work\Code\test-l51\config\queue.php"
  "services" => "E:\Work\Code\test-l51\config\services.php"
  "session" => "E:\Work\Code\test-l51\config\session.php"
  "view" => "E:\Work\Code\test-l51\config\view.php"
]
````

**Comment by omnilord** [comment]
Here is what I get when I place `var_export($this->getConfigurationFiles($app));` before line 55:

    array (
      'config.database' => '/config/database.php',
      'config.compile' => '/config/compile.php',
      'config.view' => '/config/view.php',
      'config.services' => '/config/services.php',
      'config.session' => '/config/session.php',
      'config.queue' => '/config/queue.php',
      'config.app' => '/config/app.php',
      'config.filesystems' => '/config/filesystems.php',
      'config.broadcasting' => '/config/broadcasting.php',
      'config.auth' => '/config/auth.php',
      'config.cache' => '/config/cache.php',
      'config.mail' => '/config/mail.php',
    )

**Comment by rkgrep** [comment]
Here it is.
Do you have any symlinks?

**Comment by GrahamCampbell** [comment]
Can't replicate. Ask on the forums please.

**Comment by omnilord** [comment]
Yes, php-fpm was chrooted to the laravel directory.

**Comment by rkgrep** [comment]
I'll try to replicate and fix this.

**Comment by rkgrep** [comment]
@omnilord Fixed and merged

**Comment by GrahamCampbell** [comment]
Ish. Though your fix was incorrect, so Taylor changed it after merging.

**Comment by rkgrep** [comment]
I found the reason and the solution while my technical mistake was not so critical.
Most of such errors happen because tests don't cover big parts of code.
