### ISSUE TITLE
Homestead Port Forwarding

### ISSUE THREAD

**Issue by pjebs** [laravel/framework#9200]
http://laravel.com/docs/5.1/homestead
The documentation states that port forwarding should be in this format in Homestead.yaml file:

ports:
    - send: 93000
      to: 9300

This is incorrect.

It has to be in this format to work:

ports:
    - host: 93000
      guest: 9300

That is because in homestead.rb file the code is this:

    # Add Custom Ports From Configuration
    if settings.has_key?("ports")
      settings["ports"].each do |port|
        config.vm.network "forwarded_port", guest: port["guest"], host: port["host"], protocol: port["protocol"] ||= "tcp"
      end
    end

**Comment by GrahamCampbell** [comment]
Please send a PR then.
