### ISSUE TITLE
Retrieving all input data using $request->all()

### ISSUE THREAD

**Issue by rjchauhan** [laravel/framework#9205]
I have one middleware, which merges `customerId` to each incoming request.

    if ( ! $request->has('customerId')) {
        $request->merge(['customerId' => auth()->user()->userId]);
    }

When I'm fetching all input data using `$request->all()`, It's just works fine.
> If `$request` is of type `Illuminate\Http\Request`.

But if `$request` is of type `App\Http\Requests` then I can't get `customerId` while fetching all data using `$request->all()`.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
