### ISSUE TITLE
Undefined property in Illuminate\Foundation\Testing\CrawlerTrait.php

### ISSUE THREAD

**Issue by gmoschitta** [laravel/framework#9212]
After update to framework 5.1, i got this error in my test:

ErrorException: Undefined property: GestcommControllerTest::$baseUrl

...vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:680

**Comment by GrahamCampbell** [comment]
You need to define that property.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/master/tests/TestCase.php#L10

**Comment by gmoschitta** [comment]
Sorry, i updated to framework 5.1 but, of course, my tests/TestCase.php did not update.

I apologize
