### ISSUE TITLE
[L5] Empty JSON array not recognized in Validator

### ISSUE THREAD

**Issue by 3x14159265** [laravel/framework#9213]
when sending an empty JSON array, the Validator doesn't recognize it as array.

This is my request payload:
```{interests: []}```

My rules array:
```
private $rules = array(
		'interests' => 'required|array'
	);
```

The validator returns following errors message:
```interests: ["The interests field is required."]```

This is in fact a very strange behaviour. The interests field exists in the request and payload and is of type array, it's just empty. The Validator shouldn't return an error it this case.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour. Empty is the same as non-existent.

**Comment by 3x14159265** [comment]
This makes no sense at all. Anyway, will find a workaround for myself.

**Comment by GrahamCampbell** [comment]
The way we deal with requests, we can't tell the different between not set, because ->input('foo') will return the same if set or not.
