### ISSUE TITLE
queue:listen does not hand off artisan path to queue:work

### ISSUE THREAD

**Issue by russmatney** [laravel/framework#9216]
Ran into this today – not sure it's worth fixing, but I thought I'd bring it up.

I was having a hard time debugging my app – jobs were being queued, but my listener wasn't consuming anything. I'm running on elastic beanstalk and using Supervisor to keep it running, and all of that is fine. The issue was thus:

I was running queue:listen like this:

```
php /var/app/current/artisan queue:listen --tries=3 --env production
```

And that was firing workers with this command:

```
/usr/bin/php-5.6 artisan queue:work --delay=0 --memory=128 --sleep=3 --tries=3 --env=production
```

The workers were dying instantly and quite silently b/c artisan couldn't be found. 

I don't have much php experience, but thought this could potentially be solved with a PATH fix, and I looked briefly into php.ini stuff before deciding that we should really be running queue:work directly in production (as opposed to relying on queue:listen).

**Comment by GrahamCampbell** [comment]
We're open to PRs.
