### ISSUE TITLE
Unnescessary illuminate support dependencies

### ISSUE THREAD

**Issue by rkgrep** [laravel/framework#9220]
Most of illuminate packages require support only because of service providers inside, while service providers are used rarely in non-Laravel apps.
In the same time support pulls 2 additional packages.

I propose to remove this dependency so service providers will become unusable though users could manually require support package on their need

**Comment by GrahamCampbell** [comment]
These dependencies are often for the array helpers too.

**Comment by GrahamCampbell** [comment]
Also, illuminate/support is pretty small. The contracts repo is larger.
