### ISSUE TITLE
Test - Form type('password', 'password') failure

### ISSUE THREAD

**Issue by BenGriffiths** [laravel/framework#9221]
Laravel 5.1.

I have a problem when trying to test filling in a form with a username and password.

If I call:
```
$this->visit('/auth/login')
    ->type('some@email.com', 'email')
    ->type('password', 'password')
    ->press('Login')
    ->seePageIs('/dashboard');
```
I get the following error when testing (Which I realise at this point i useless):
```
1) AuthTest::testLoggingIn
ErrorException: Undefined property: Symfony\Component\HttpFoundation\Response::$exception
```

However, if I try changing the password to something else, it works fine:
```
$this->visit('/auth/login')
    ->type('some@email.com', 'email')
    ->type('something_else', 'password')
    ->press('Login')
    ->seePageIs('/dashboard');
```
This doesn't appear to be an issue for other fields where the input matches the name, just on passwords.

**Comment by bmitch** [comment]
I tried duplicating this but wasn't able to. Can you provide the code for your view?

**Comment by BenGriffiths** [comment]
I'm using an updated version since this and it seems to be working fine now - guess somethings fixed it in a previous update.
