### ISSUE TITLE
moving default directories around

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#9223]
I'm moving the database directory, and I get this error

```log
  [RuntimeException]
  Could not scan for classes inside "database" which does not appear to be a file nor a folder
```

Is there a laravel framework configuration that can be edited so these directories can be easily moved?

**Comment by override-chaos** [comment]
You will need to change the autoload classmap in the composer.json file.

https://github.com/laravel/laravel/blob/master/composer.json#L19
