### ISSUE TITLE
Status of commands in 5.1?

### ISSUE THREAD

**Issue by martinbean** [laravel/framework#9225]
What are the status of command classes in Laravel 5.1? I see the Artisan command to generate a command class still exists (`$ php artisan make:command`). I’ve just used it to create a command class, but the class stub it creates extends a non-existing abstract `Command` class.

I see “jobs” have been introduced in 5.1 but they seem self-handling only, i.e. there’s no option to create a corresponding handler class. Are commands deprecated in favour of jobs? In which case the Artisan command to create new command classes should be removed. Or should the abstract command class be re-introduced that existed in Laravel 5.0.x?

**Comment by GrahamCampbell** [comment]
Commands are still exactly the same. They are just called jobs by default now, and are self handling by default. You don't have to make them self handling...

**Comment by martinbean** [comment]
@GrahamCampbell Still doesn’t really answer the question. If commands are jobs now, should the `make:command` Artisan command be removed? Because if not, there’s a bug in that the command class stub it creates extends a non-existent abstract class.

**Comment by GrahamCampbell** [comment]
You can still have commands in the same place. I do. I don't call them jos.

**Comment by martinbean** [comment]
@GrahamCampbell Well as I say, there’s a bug: the abstract command class doesn’t exist, but the command stub tries extends it.

**Comment by GrahamCampbell** [comment]
It does exist for some people.

**Comment by martinbean** [comment]
@GrahamCampbell There’s no file at **app/Commands/Command.php** in the Laravel repo: https://github.com/laravel/laravel/tree/master/app

**Comment by GrahamCampbell** [comment]
Yes, but it DOES exist for laravel 5.0 users that upgraded.

**Comment by GrahamCampbell** [comment]
That command is for them.

**Comment by martinbean** [comment]
@GrahamCampbell I think some warning should be in place in that case then. As otherwise, people creating a fresh 5.1 application are going to have this command that creates classes extending non-existing classes.

**Comment by trashofmasters** [comment]
@martinbean do you perhaps need `artisan make:console` to create a console command, as opposed to a command bus command?

**Comment by martinbean** [comment]
@trashofmasters No. I knew the difference between a console command, and a command bus command.

**Comment by judgej** [comment]
Just came across this too. If I understand this correctly, the `make:command` artisan command does the same in 5.1 as it did in 5.0, but is actually invalid in a fresh install of 5.1 - the command it produces is suitable only for 5.0 without some additional work to bring in some 5.0 legacy stuff.

Instead, for a fresh install of 5.1 we should be using `make:job` instead.

Is this the right conclusion?

**Comment by martinbean** [comment]
@judgej Indeed. This is a bug if creating a brand new 5.1 Laravel application and then trying to run `php artisan make:command`.

**Comment by judgej** [comment]
On top of that, the switching to 5.1 in the docs after finding the command pipeline takes you to a 404. A redirect to the "jobs" page as the new way of doing things would be handy. I was totally in the dark about the change until I hit this problem and found this closed issue.

**Comment by JesseObrien** [comment]
This needs to be re-opened. It is a bug in a fresh install of 5.1 currently. The `php artisan make:command` class will stub out a new command which will make use of `App\Commands\Command` which does not exist by default. Either that class needs to exist or the stub needs to change.

**Comment by martinbean** [comment]
@JesseObrien Totally agree. It’s the reason I created this issue and disappointing it was flippantly closed when this _is_ a bug for new users of 5.1.

**Comment by coldfuzion** [comment]
@martinbean  Yes, i just experienced this problem. it should be removed, or addressed when trying to add via artisan. - notify me, well now i know.

**Comment by AdenFraser** [comment]
Could we not just have a simple check to determine if the Command abstract (App\Commands\Command) exists and throw an exception if it is unavailable.

Ran into this issue this morning and upon researching one of the first things I've ended up at is this issue, not a major one by any means, but we can't be the only ones.
