### ISSUE TITLE
vendor:publish - migrations using stubs

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel/framework#9232]
So when you run `php artisan vendor:publish` the migrations will get copied and have their names changed according to the date('Y_m_d_His') current migration pattern;

Had this problem in the lucadegasperi/oauth2-server-laravel package https://github.com/lucadegasperi/oauth2-server-laravel/pull/423

The src name could be a stub, opposed to being a real migration name, ending up with something like:
`m001_alter_table_user_add_myfield1.php`
`m002_alter_table_user_add_myfield2.php`
`m003_alter_table_user_add_myfield3.php`

and then when publishing they would get prepended by the migration pattern (date('Y_m_d_His'))

so Illuminate\Foundation\Console\VendorPublishCommand could include a publishMigration method that would handle that. Still the ServiceProvider would need to be amended as well.

the m001 is because the class name has to start with a letter and 001 to keep the alphabetical order sane, considering nobody would have more than 999 migrations, but could be m0001 or m00001 as well.

Everything else would still work while giving the developer possibility to offer more flexibility/consistence.

**Comment by vinkla** [comment]
This would be a great feature :+1:

**Comment by mathiasgrimm** [comment]
I see one problem, which can be overcome. 
There would be needed to do a validation to not re-publish the migrations as they are dynamic.
On the referred PR I use this technique but actually checking for the main configuration file existence.

**Comment by mathiasgrimm** [comment]
the stub name string could be searched instead of the full name.

So if the package contain migrations that have names like m001_alter_table_user_add_myfield1.stub
then we search for migrations that match this name, otherwise do the regular search matching the full name.

**Comment by GrahamCampbell** [comment]
I guess we're open to PRs if you can think of a good solution.
