### ISSUE TITLE
Relationships in factory builders

### ISSUE THREAD

**Issue by devinfd** [laravel/framework#9245]
Given:
```
$factory->define(App\Post::class, function ($faker) {
    return [
        'title' => $faker->sentence,
        'body' => $faker->sentence
    ];
});
$factory->define(App\Comment::class, function ($faker) {
    return [
        'post_id' => factory(App\Post::class)->create()->id,
        'body' => $faker->sentence,
    ];
});
```
with TestDummy it was safe to do
```
Factory::create(App\Comment::class, [
    'post_id' => $someGivenPostId
]);
```
and the `App\Comment::class` factory would not create a post because the post_id key was set in the creating array. However L5.1 does not have the same behavior. It creates the entire factory (including a new post) and then merges the defined attributes into the created factory and overrides the post_id. This is troublesome because it takes longer to create many factories and also floods the database with unused data. Basically its not efficient. (see `Illuminate\Database\Eloquent\FactoryBuilder@makeInstance`)

The documentation says to define the relationships as if the factories were normal modals. This is problematic because if you had many modals all related to each other, then each time you needed a factory your left to be responsible for remembering and creating all of the relations. For example, having to relate a comment to a post to a user to a role (and so on if needed) is kind of a pain.

I'm not sure if this is a bug or just a behavior/coding change that I need to make. Are you open to PR's to change this so that Laravel can handle the relationships?

**EDIT**
One solution that I see is to pass the user defined attributes through to the factory definition as a second argument. Then allowing the definition to decide what to do about it.

```
// Illuminate\Database\Eloquent\FactoryBuilder @ line 129
$definition = call_user_func($this->definitions[$this->class][$this->name], $this->faker, $attributes);
```

```
$factory->define(App\User::class, function ($faker, $attributes) {
    
    $accountId = isset($attributes['account_id']) ? $attributes['account_id']: factory(App\Account::class)->create()->id;

    return [
        'account_id' => $accountId,
        'email' => $faker->email,
        'password' => 'secret',
        'name' => $faker->name
    ];
});
```

**Comment by dennisoderwald** [comment]
+1

**Comment by dennisoderwald** [comment]
I tried to use your workaround @devinfd:

```
Missing argument 2 for Illuminate\Database\Eloquent\Factory::{closure}()
```

**Comment by devinfd** [comment]
I don't know what to tell you. All I did was change line 129 to
```
$definition = call_user_func($this->definitions[$this->class][$this->name], $this->faker, $attributes);
```
If you have done a composer update then this change will no longer exist as you/we are changing code in the framework and this change has not been accepted into it for real yet.

**Comment by dennisoderwald** [comment]
Why uncommented closed?

**Comment by dwightwatson** [comment]
Yeah I'd like to know too. I think relationships are an important part of a model factory (like factory_girl in Rails generates the "belongs to" of models) so an official word on this would be good.

**Comment by devinfd** [comment]
@GrahamCampbell Uh excuse me? Why was this closed without comment? There are a number of people having this issue judging by the discussions on Laracassts.

**Comment by GrahamCampbell** [comment]
Taylor already rejected this.

**Comment by devinfd** [comment]
He rejected a different implementation of fixing this issue. What I am proposing doesn't change Laravels methodology and also fixes this bug

**Comment by GrahamCampbell** [comment]
Well, if you have a good implementation please send a PR. We don't process proposal issues unless they are for something really large.

**Comment by devinfd** [comment]
I'll gladly send a PR for this. Thanks!

**Comment by devinfd** [comment]
Which branch should the PR be for?

**Comment by dennisoderwald** [comment]
thanks @devinfd!

**Comment by mabasic** [comment]
Still having this issue: https://github.com/laravel/framework/pull/9387#issuecomment-118499838

**Comment by cerw** [comment]
IS this fixed? How can I access the attribute in Factory?

**Comment by bretramin** [comment]
@cerw The pull request for this proposed solution _has_ been merged and the solution _is_ still working (as of 5.4).  Just add $attributes to the function parameters and, if the key is set in your $attributes array, use that value instead of calling the next factory.  Take a look at the last chunk of code in the very first comment for an example.

**Comment by Chekote** [comment]
Thank you @devinfd! I was running into this exact problem and the fix you implemented was not documented anywhere. You saved me a bunch of headache. 🥇

**Comment by cerw** [comment]
@bretramin thank you for the reply yes it did work for me with $attributes.
