### ISSUE TITLE
Ability to define index key length while creating schema

### ISSUE THREAD

**Issue by eidng8** [laravel/framework#9256]
I've just tried out v5.1, and got the infamous ERR1071 while doing a `artisan migrate`, right after `laravel new`. I can't find out a good solution to it, yet. Because table charset is utf8mb4, and the email column is varchar(255), creating a unique on it will definitely cause error. I can't find out a way to specify the key length while calling
```php
$table->string('email')->unique();
```
from the `2014_10_12_000000_create_users_table.php` file.

After a little digging, it seems that we'll have to modify several index related functions in the `Illuminate\Database\Schema\Blueprint` class, and eventually (maybe not), the `Illuminate\Support\Fluent`.

Any hint?

**Comment by GrahamCampbell** [comment]
Yeh, it's possible. Pass a second param to string with the length.

**Comment by GrahamCampbell** [comment]
```
$table->string('email', 128)->unique();
```

**Comment by eidng8** [comment]
Sorry, that's not the case. Passing in the length to string() changes the length of the column, but not the key length. The email column does need to be long enough to hold the data. The key length is specifically MySQL, which makes a partial index with only the given length in bytes.
