### ISSUE TITLE
5.1 phpunit test method "attach" setting incorrect mimetype

### ISSUE THREAD

**Issue by ArthurGuy** [laravel/framework#9262]
When using the attach method the file gets passed through with the mimetype application/octet-stream even if it's an image.
This then fails Laravel's image validation check.

Presumably this should be detected or an option provided for it to be set manually.

**Comment by iZaL** [comment]
+1

**Comment by ibrasho** [comment]
I think is related to [symfony/DomCrawler](https://github.com/symfony/DomCrawler), since it's what's handling the form submission.
