### ISSUE TITLE
fluent naming for response macros

### ISSUE THREAD

**Issue by lukaserat** [laravel/framework#9267]
I just noticed that laravel is not yet automatically detecting for fluent matching of macros' names.

Example:

```
$factory->macro('resourceForbidden', function ($value=[]) use ($factory) {
    $data = array_replace([
....
    return $factory->json($data, 403);
});
```

It is better I think if the name can be written ``resource-forbidden``. Currently it will issue a ``BadMethodCallException``

**Comment by GrahamCampbell** [comment]
`resource-forbidden` would be a crap method name imo.
