### ISSUE TITLE
[5.1] action() generates wrong link for Controller@getIndex 

### ISSUE THREAD

**Issue by zitniak** [laravel/framework#9268]
Please try example:
```php
class TestController extends Controller {

    public function getIndex($id)
    {
        dd($id);
    }

    public function getIndex2($id)
    {
        dd($id);
    }
}

Route::controller('test', 'TestController');
Route::get('/', function(){

    dd ([
        action('TestController@getIndex', 1),
        action('TestController@getIndex2', 1)
    ]);

});
```
action generates links:

  0 => "http://laravel5.localhost/test?1"
  1 => "http://laravel5.localhost/test/index2/1"

First generated link http://laravel5.localhost/test?1 is wrong, when you paste to the browser you get ErrorException in TestController.php Missing argument 1 

Correct link should be http://laravel5.localhost/test/index/1

In Laravel 4 it works correctly

**Comment by GrahamCampbell** [comment]
Is this the same in 5.1. 5.0 isn't supported anymore.

**Comment by zitniak** [comment]
Yes same issue is in 5.1

**Comment by GrahamCampbell** [comment]
I need to see your routes.

**Comment by zitniak** [comment]
It's clean installation for demonstration, there is nothing more in routes.php, only this:

Route::controller('test', 'TestController');

Route::get('/', function(){
    dd ([
        action('TestController@getIndex', 1),
        action('TestController@getIndex2', 1)
    ]);
});

**Comment by GrahamCampbell** [comment]
Oh, right. You're not using coed blocks. I'll update your posts...

**Comment by lukasgeiter** [comment]
I can confirm this bug. The problem is that Laravel adds two different routes for all index methods.

    /test
    /test/index/{one?}/{two?}/{three?}/{four?}/{five?}

**Comment by ArjanSchouten** [comment]
Don't think this is wrong behavior. A method ```getIndex($id)``` is not valid. The ```getIndex()``` method may not have parameters. If I try to pass ```1``` as parameter I get the error that the method ```1``` does not exists. That's in my opinion the desired behavior. It's strange to do it this way.

**Comment by zitniak** [comment]
Please look on more real example. I have OrdersController and I would like to display list of all orders and list of all orders by user id

So I am doing it like this:

```php
<?php namespace App\Http\Controllers;

class OrdersController extends Controller {

    public function getIndex($userId = null)
    {
        dd($userId);
    }

}

?>

<?php
Route::controller('orders', 'OrdersController');

Route::get('/', function(){
    dd ([
        action('OrdersController@getIndex'),
        action('OrdersController@getIndex', 1),
    ]);
});

```

Second link it is not working, it generated links:

http://laravel51.localhost/orders
http://laravel51.localhost/orders?1

I am forced to rename getIndex to anything different like getList and then it works. But then it's not resourcefull (BTW when OrdersControllers I define like resourcefull Route::resource('orders', 'OrdersController'); that is not working either). 
If index cannot have parameters but other methods can then I think it's inconsistent and should be mentioned in documentation that index cannot have parameters, but why shouldn't have? 

Interestingly this link http://laravel51.localhost/orders/index/1 works and I think action helper should generate it when I specify parameter (like it was in L4). 

Now how to generate this link via action helper? I am forced to use hardcoded links in templates.

Please what is correct way to do it?

**Comment by mkhuramj** [comment]
I'm making a link of a controller's function resides in a directory named 'Admin' in Controller directory. When I make a link in the menu bar using 
```
{!! HTML::link('/admin', 'Admin') !!}  // www.property.com/admin
```
it doesn't work, but if I prefix '/admin' with 'index.php/admin' like this:
```
{!! HTML::link('index.php/admin', 'Admin') !!}  // www.property.com/index.php/admin
```
 it works fine. What is the problem? How can I get rid off adding 'index.php' before each of my link like 'admini'?
**Note** I'm using virtual host named 'www.property.com' on Ubuntu 15.04.
here is my AdminController
```
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('admin.index');
    }
```

Here is my route file
```
Route::resource('/', 'HomeController');

Route::resource('/admin', 'Admin\AdminController');
```
