### ISSUE TITLE
Improving mutator cache in Eloquent

### ISSUE THREAD

**Issue by reshadman** [laravel/framework#9276]
Currently the eloquent model class contains a cache strategy for getters which first fetches all class methods and runs a loop on them filtering them by a regular expression.  
This occurs [only once](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L3207) per unique eloquent final object.  
The getter cache container is only filled up with the [processed snake case attribute key](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L3238).

Each time a new model class is created for first time a loop with 50 to 100 iterations with processing a regular expression is run. 

Wouldn't it be cool to have something like ```php artisan eloquent:cache``` for this ?

Also the method name can be saved in the mutator cache container, which prevents further string processing (for fetching method name from a given attribute) as both *attribute* name and the *getter method name* exist in the cache array.

```php
$mutatedAttributes[$method] = lcfirst($matches[1]);
```

**Comment by GrahamCampbell** [comment]
The performance difference would be minimal and this would be a pain to implement.

**Comment by reshadman** [comment]
It does not have bold impact but it is not minimal, usually for me eloquent models contain more than 50 (without parents).

at least, I think storing the method name in the cache array wouldn't be a pain, as it will prevent calling extra ```snake_case``` calls.

**Comment by GrahamCampbell** [comment]
Well if you can implement this I'm sure it would be considered.

**Comment by reshadman** [comment]
@GrahamCampbell  I also made a package for the caching strategy : [eloquent-faster](https://github.com/reshadman/eloquent-faster).   
If the strategy is O.K, I will make a feature pull request on master branch based on that.
