### ISSUE TITLE
Queue docs/reality

### ISSUE THREAD

**Issue by ash-rain** [laravel/framework#9279]
I'm on L5.1 and have recently started talking to myself.
I'm reading the docs on queues, made a Job and try to ->dispatch() it from a controller.
However, there are vast differences between what's in the docs and what's in the codebase. For instance, the Job contract requires a fire($job, $data) method instead of handle().
Can someone tell me what's going on?

**Comment by GrahamCampbell** [comment]
Ask on the forums please. Note that a job doesn't dispatch itself.

**Comment by ash-rain** [comment]
Why would I ask on the forums? Something is wrong with either the code or the docs!

**Comment by GrahamCampbell** [comment]
The code and the docs are just fine.

**Comment by ash-rain** [comment]
Did I not describe the issue appropriately? Or do you get paid per closed issue?

**Comment by GrahamCampbell** [comment]
I'm not paid, and I'm telling you this is not an issue. Ask on the forums and someone will help you out.

**Comment by ash-rain** [comment]
It was a joke but this is serious. I'll obviously have to try somewhere else, so I'll just leave this here:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Contracts/Queue/Job.php#L12
http://laravel.com/docs/master/queues#writing-job-classes

**Comment by GrahamCampbell** [comment]
You're not meant to be calling the fire method to queue up a job...

**Comment by GrahamCampbell** [comment]
You're basically looking at the wrong code. You want to check out https://github.com/laravel/framework/blob/5.1/src/Illuminate/Contracts/Queue/Queue.php.

**Comment by ash-rain** [comment]
No I'm not trying to queue the job using the fire method. I'm showing you there's a difference for Jobs between the docs/code. The method name itself is different, not to mention the whole queue process doesn't work according to the docs.

**Comment by ash-rain** [comment]
So, conclusion: The Laravel 4.2 docs on queues are currently the actual ones. Weird stuff.

**Comment by GrahamCampbell** [comment]
I think you're a bit confused. Both the 4.2 docs and 5.1 docs document the same thing though 5.1 has some new stuff that's probably causing the confusion.

**Comment by GrahamCampbell** [comment]
The 4.2 way of using the queue is kind of deprecated if you will.

**Comment by GrahamCampbell** [comment]
In 5.1, the idea is you "dispatch" a job and have the command bus decide what to do with it.

**Comment by ash-rain** [comment]
Yeah I get it but the thing is the examples in the 5.1 docs don't work at all. And I'm not really keen on doing it "the 4.2 way" but I don't really have a choice.

**Comment by djtarazona** [comment]
What example in particular?  You shouldn't be using a contract.  What contract are you trying to use?

All your jobs need to work with the dispatcher is a `handle()` method.  The [5.1 `App/Jobs/Job`](https://github.com/laravel/laravel/blob/master/app/Jobs/Job.php) class is just an abstract class that doesn't implement any contracts, nor does it required a `fire()` method to be implemented.

> Job classes are very simple, normally containing only a handle method which is called when the job is processed by the queue.

**Comment by ash-rain** [comment]
I use the Queue facade to dispatch jobs but the old docs apply. To repeat once more - I have to use a fire() method that accepts $job and $data arguments instead of a handle() method. The `handle` doesn't get called at all.

**Comment by GrahamCampbell** [comment]
That method of using the queue facade is the old way of doing it basically. You can continue using it if you want though. :)

**Comment by ash-rain** [comment]
That's how it works. If I use the controller dispatch() method from the trait it breaks (as I mentioned earlier).

**Comment by djtarazona** [comment]
How does it break?  What is the error?  It would really help if you posted example code so that we can attempt to reproduce your situation.

**Comment by GrahamCampbell** [comment]
As I said, forums please.
