### ISSUE TITLE
Paginator links have trailing slash

### ISSUE THREAD

**Issue by pfazzino** [laravel/framework#9288]
https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/Pagination/LengthAwarePaginator.php

Given trailing slashes cause a redirect due to out of the box htaccess rule, any link generation should be consistent with this policy.

A suggestion is that the links generated go via the UrlGenerator, that way if I want to inject a custom instance (for instance I might prefer trailing slashes on all routes generated for legacy reasons) then only one class needs to be replaced where. Currently LengthAwarePaginator is hardcoded in Builder.php and therefore this behaviour can't easily be modified afaics.

**Comment by Sladewill** [comment]
Duplicate #8231

**Comment by pfazzino** [comment]
Is this really a dupe? I saw the item above and that's related to non base path installations. My issue is that regardless of installation path, the framework shouldn't be generating trailing slash url's when it goes so far out of it's way to remove them just about everywhere (which is another huge pain but a separate discussion)

**Comment by Sladewill** [comment]
Well yeah it should have been fixed but no one sent a pull request for it. Yeah it effects all installations. But it is kinda related the whole trailing slash isn't specific to non base path installations, its just the paginator in general.

**Comment by kohenkatz** [comment]
I have another example for this issue.

One of my apps allows the user to specify the returned content type by changing the file extension.  For example, `/categories/1.html` returns a category with a list of items as a regular HTML page, while `/categories/1.json` returns the data in JSON format, and `/categories/1.rss` returns an RSS feed of updates in the category.

The current behavior of the paginator is that it creates page URLs as `/categories/1.html/?page=2`, etc, and that's just not right.

I know that I can override the URL manually, but I really don't see why the trailing slash is there in the first place.

(I don't have the `.htaccess` redirect problem though; I'm using nginx.)

**Comment by phroggyy** [comment]
@GrahamCampbell this one's resolved now, in #10217 :)

**Comment by GrahamCampbell** [comment]
Thanks. :)
