### ISSUE TITLE
Multiple handlers do not work correctly when calling Monolog through Log Facade

### ISSUE THREAD

**Issue by kidshenlong** [laravel/framework#9290]
If I call monolog statically twice, whichever handler I call first will take precedence.
```
$monolog = Log::getMonolog($context);
$monolog->pushHandler($redisHandler);
$monolog->addInfo('Access Log', [
    'data' => 'test-data'
]);

$other_monolog = Log::getMonolog($other_context);
$other_monolog->pushHandler($customHandler);
$other_monolog->addInfo('Access Log', [
    'data' => 'test-data-2'
]);
```
If I run this code while watching a redis monitor both log writes would be to redis.

This isn't an issue if I don't call Monolog through the Log facade and actually instantiate a new instance. `new \Monolog\Logger($context);` works. I imagine this is happening because of how laravel wraps things statically in facades, so in a way it's almost expected behaviour. I was just curious if there was a way round this while still using facades.

I can recreate on fresh install. Tried with Redis and a custom Handler I've written. It would be nice to see if others can recreate this.

**Comment by GrahamCampbell** [comment]
This is not a bug. This is the expected behaviour. Our log class is a singleton. Nothing to do with facades.

**Comment by kidshenlong** [comment]
Thanks!

**Comment by GrahamCampbell** [comment]
If you want a separate monolog istance "clone" it. :)
