### ISSUE TITLE
Advanced seeInDatabase query

### ISSUE THREAD

**Issue by brayniverse** [laravel/framework#9292]
At the moment it doesn't seem possible to check whether a value `!=` something.

If you change the `$data` parameter, [on this line](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L216), to allow for either an `array` or `callable` value it becomes possible to provide a more complex query.

## Proposed change
```php
/**
 * Assert that a given where condition exists in the database.
 * 
 * @param  string  $table
 * @param  array|callable  $data
 * @param  string  $connection
 * @return $this
 */
protected function seeInDatabase($table, $data, $connection = null)
{
    // ...
}
```

This will also need to be reflected on lines [239](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L239) and [252](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L252).

## Example use case
```php
$this->seeInDatabase('vehicles', function($query) use ($vehicle)
{
    $query->where('id', $vehicle->id)
        ->whereNotNull('discontinued_at');
});
```

Would this be beneficial to anybody, are there any circumstance where it could break?

**Comment by fadillzzz** [comment]
Don't we have `missingFromDatabase` and `notSeeInDatabase` for that?
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L239
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L252

**Comment by brayniverse** [comment]
`missingFromDatabase` and `notSeeInDatabase` check whether the data does not exist in the database, which could be used to check whether the following **doesn't** exist.

```php
[
    'id' => 1,
    'deleted_at' => '2015-19-06'
]
```

```php
$this->missingFromDatabase('vehicles', ['deleted_at' => null]);
```

However, this doesn't necessarily mean that this **does** exists in the database.

With the proposed change we can check whether a row exists where `deleted_at` does not equal `null`.

**Comment by brayniverse** [comment]
@GrahamCampbell did you close this because nothing has happened in 4 days or because it's a bad idea?

**Comment by ibrasho** [comment]
Send a PR with a suggested implementation.
Issues are for bug reports.
Suggestions should be made with PRs.

**Comment by EspadaV8** [comment]
Did anything happen with this? Currently trying to test a soft deleted row exists and can't find a way to do `WHERE deleted_at IS NOT NULL`.

**Comment by acorncom** [comment]
I'd love to see this added to the system as well ...

**Comment by mehdisbys** [comment]
In the meantime for those in search of a solution, you can still do the following to get the latest version of your model after your submit request or whatever you did to change it :

```
 $model = Model::find($id) 
 //or 
$model = Model::orderBy('id', 'desc')->first() //Gets the latest record in table - if you don't have the id
```

And then : 

`$this->assertNotNull($model->discontinued_at)`

Hope that helps someone.
