### ISSUE TITLE
Request::all() and Request::input() cause HHVM to fatal

### ISSUE THREAD

**Issue by BobLoco** [laravel/framework#9301]
I've encountered an unusual error in Lumen when attempting to access the request details with Request::all(). The logs show the following:

```
Fatal error: $this is null in /website/no36/releases/dev/vendor/illuminate/http/Request.php on line 272
```

As far as I can tell, this appears to be related to [this issue](https://github.com/facebook/hhvm/issues/2594) for HHVM, which is actually a bug with Zend rather than HHVM to do with PHP conflating $this and statics.

If that's the case, then the solution is to declare all() and input() as static in Illuminate\Http\Request, and use Request::capture() to get the instance. I'm happy to submit a pull request for this, but thought a change like this might benefit from discussion as an issue as well

One solution is to replace $this with $request and add the following to methods which can be called statically:

```
$request = !empty($this) ? $this : self::capture();
```

This has the advantage of making a minimal change, but may not be the cleanest solution

**Comment by BobLoco** [comment]
Apologies - it looks like this issue isn't reproducible on Laravel 5.1, and instead only happens on Lumen, for which the solution is to inject the Request object into the controller method.

**Comment by GrahamCampbell** [comment]
yeh, `$request = !empty($this) ? $this : self::capture();` is wrong.

**Comment by GrahamCampbell** [comment]
We lazy create the request object on purpose to save on performance in lumen.

**Comment by GrahamCampbell** [comment]
If we can complete a request response cycle without creating a request object, then we do.
