### ISSUE TITLE
Renaming column and changing it at same migration causes error.

### ISSUE THREAD

**Issue by iget-esoares** [laravel/framework#9305]
Hi, I've found something that may probably be a bug:

If I do this schema changing:

```
Schema::table('table', function(Blueprint $table)
{
     $table->renameColumn('old_column', 'new_column');

     $table->string('new_column')->nullable()->change();
});
```

I'll get this error:

```
[Doctrine\DBAL\Schema\SchemaException]                                  
  There is no column with name 'new_column' on table 'table'.
```

Since the queries are executed in same order that they are write at Schema Builder,

At the moment that the query to change the colum type runs, my column will already be named `new_column`.

So I think that I found a inconsistence here.

Thanks,

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by iget-esoares** [comment]
Sorry, I didn't found any issues like this. Could you link it for me?

**Comment by brunogaspar** [comment]
There's this PR https://github.com/laravel/framework/pull/9198 which is now merged so the issue should be fixed and there's a few issues mentioned (at the bottom).
