### ISSUE TITLE
SqsConnector always creates 'key' and 'secret' array key configurations.

### ISSUE THREAD

**Issue by jakeengrade** [laravel/framework#9309]
SqsConnector.php

Version 5.1.2
```
    public function connect(array $config)
    {
        $config += [
            'version' => 'latest',
            'credentials' => [
                'key'    => $config['key'],
                'secret' => $config['secret'],
            ],
        ];

        unset($config['key'], $config['secret']);

        return new SqsQueue(new SqsClient($config), $config['queue']);
    }
```
Version 5.0.*
```
	public function connect(array $config)
	{
		$sqs = SqsClient::factory($config);

		return new SqsQueue($sqs, $config['queue']);
	}
```
AWS SQS does not require key and secret keys to be set. In prior versions the SqsConnector worked with an IAM role on an EC2 instance simply by not setting a key and secret, with v5.1.2 this isn't the case. It always complains about a missing key and secret.

It's been a long day, I might be missing something. Can anyone with queue experience comment on this difference?

Thanks

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia. :)

**Comment by jakeengrade** [comment]
Thanks Graham, I will.

**Comment by GrahamCampbell** [comment]
@jakeengrade No, that litterally was me pinging him, lol.

**Comment by jakeengrade** [comment]
Oh I see. Oops I did not realize that alerted the user. I hope I did not annoy him by sending an email...

Anyway thanks :)

**Comment by jeremeamia** [comment]
You're right, that is a problem. `'key'` and `'secret'` should be conditionally applied if they are present in the `$config`. I'll have to submit a PR to fix that. As a workaround, make sure to remove `'key'` and `'secret'` from your config and set `'credentials' => null`. That should make it fall through to IAM role credentials, but let me know if there is still a problem with that approach.

**Comment by jakeengrade** [comment]
Thanks for taking care of that, Jeremy. Yes, that temporary work-around works. It generates undefined indexes but the code runs through anyway.

**Comment by jeremeamia** [comment]
> It generates undefined indexes but the code runs through anyway.

Oh, well, then I guess you don't actually have to remove `'key'` and `'secret'`, just set them to null. Setting `'credentials'` should be enough.

**Comment by jeremeamia** [comment]
Note to self: Any changes applied to the way config is handled in the Queue component should be applied to Mail and Filesystem, as appropriate.

**Comment by jakeengrade** [comment]
Thank you.

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia.

**Comment by jeremeamia** [comment]
Thanks for the ping. I'll prep a PR this week.

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Comment by jeremeamia** [comment]
OK, I meant this week. Today.

**Comment by jakeengrade** [comment]
Thank you! Much appreciated.
