### ISSUE TITLE
[Request] EncryptCookies $except property should be method instead

### ISSUE THREAD

**Issue by jlem** [laravel/framework#9312]
If you have a legacy system with legacy authorization cookies, you will want to add those to the $except array of the EncryptCookies middleware so you can retrieve them without going through the decryption process.

However, some legacy apps (like Invision Power Board) let you define the cookie prefix, which could vary from one environment to the next, as such you need a way to dynamically define those cookie strings.

    protected $except = [
        getenv('COOKIE_PREFIX').'session_id',
        getenv('COOKIE_PREFIX').'pass_hash'
    ];

is not allowed, as you can't have function calls in class properties.

As such, it would be better to have the array returned via a method rather than defined as a property so that you can dynamically build the cookie names to exclude.

For the time being, the parent's `handle()` method will have to be overridden, which is not quite as elegant.

**Comment by lukasgeiter** [comment]
Sounds like a good idea to me :+1:

**Comment by GrahamCampbell** [comment]
Please don't create issues regarding small proposals. PRs are better. :)

**Comment by jlem** [comment]
Graham, I am not going to put in work that might be summarily rejected. I don't have the time to play pull request roulette. 

I'll do a PR if I get confirmation that the proposal is a good idea.

**Comment by franzliedke** [comment]
:+1: both for the proposal and for waiting for a confirmation ;)

**Comment by dptole** [comment]
Sorry for being so late but...

Just so that if other people click on this issue through google, as I did, and don't find any code that might solve their problem, here is a simple work around:

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;
use Illuminate\Contracts\Encryption\Encrypter;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array
     */
    protected $except = [];

    public function __construct(Encrypter $encrypter)
    {
        parent::__construct($encrypter);

        $this->except = [
          getenv('COOKIE_PREFIX').'session_id',
          getenv('COOKIE_PREFIX').'pass_hash',
        ];
    }
}
```

Hope it helps!

**Comment by vtl-pol** [comment]
If everyone stumbles on this issue from google search - Here's another solution:
I had a similar issue, but in my case, I had to disable encryption for cookies that match a specific pattern. I found that you can customize the `isDisabled`-method, which checks if a cookie should be encrypted or not. Here's what I came up with:
```php
<?php

namespace App\Http\Middleware;

use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array
     */
    protected $except = [
        'subscribed-to-newsletter',
        'gdpr-notified',
    ];

    /**
     * Determine whether encryption has been disabled for the given cookie.
     *
     * @param  string $name
     * @return bool
     */
    public function isDisabled($name)
    {
        if (preg_match('/ebook-\d+-page/', $name)) {
            return true;
        }
        return in_array($name, $this->except);
    }
}

```
