### ISSUE TITLE
Backport commit to 5.0 branch.

### ISSUE THREAD

**Issue by dalabarge** [laravel/framework#9313]
Can we get this commit backported to 5.0? It fixes a bug with groups being overset when they should have been merged: https://github.com/laravel/framework/commit/2925e486b4c498555782edfb506a727dd5707726 and corresponding CS fix: https://github.com/laravel/framework/commit/e3d3043c90dead1fdeb95401c7dc65af38d4f7ad

**Comment by GrahamCampbell** [comment]
No, sorry.
