### ISSUE TITLE
Session Expire on Close OR after lifetime

### ISSUE THREAD

**Issue by caycek** [laravel/framework#9321]
I am attempting to set up a session timeout consisting of 3 levels. This has been requested of me. The 3rd level has nothing to do with laravel so will not be discussed in this issue. However, the first two levels are directly involved.

If:
```
     'lifetime' => '1',
     'expire_on_close' => true
```

`lifetime` is ignored. `expire_on_close` works.

If:
```
     'lifetime' => '1',
     'expire_on_close' => false
```

'lifetime' works. 'expire_on_close'... well still technically works :+1: 

This structure doesn't make sense. To what I understand directly from the `config\session.php`

>	| Here you may specify the number of minutes that you wish the session
	| to be allowed to remain idle before it expires. If you want them
	| to immediately expire on the browser closing, set that option.

Unless I'm incorrectly reading this I understand it as:

>    Set the lifetime in minutes to allow for an indication of inactive time in which the session will
      expire. If you want the sessions to expire when the browser closes as well just set that option.

[Stack](http://stackoverflow.com/questions/24424607/laravel-4-session-doesnt-expire-after-lifetime-limit) has an example of a question that directly replicates this issue in Laravel 4. I am using 5. I have also not been able to find any instances of answers stating that it is possible to set both.

I'm currently thinking this is because setting the value to 0 is supposed to be the expire on browser close, but there are no responses that I have found supporting this.

Are there others that are interested in having this resolved / capability? Is there something that I can do to make this happen or is this absurd?

**Comment by caycek** [comment]
Aside thought... I'm not currently 100% positively knowledgeable in the matter of how sessions are done, but I think it would make sense to have 2 different session variables when doing something like this. Thoughts? Questions? Concerns? :smile:

**Comment by ibrasho** [comment]
It's not possible.

Sessions rely on cookies, and cookies can either be `session cookies` or `persistent cookies`.
Session cookies expire when the user-agent session is closed (browser is closed), while persistent cookies are kept alive until the the expires date is reached.

You cannot have both behaviours using the same cookie.

So the correct understanding should be:
> Set the lifetime in minutes to allow for an indication of inactive time in which the session will
expire. If you want the sessions to expire when the browser closes instead ~~as well~~ just set that option.

**Comment by caycek** [comment]
Just a mention, but I did state that it would probably need 2 variables. Other than complexity is there a real reason to avoid this?

**Comment by mpmurph** [comment]
@caycek I just ran into [this issue](https://laracasts.com/discuss/channels/laravel/understanding-session-better-setting-lifetime-avoiding-data-transference-between-users-and-how-file-deletion-works?page=1#reply-130356) too - it caused me no end of confusion for several hours. I would really like to be able to ensure both too - that the user is logged out after X amount of idle time - and also when they close the browser.

**Comment by caycek** [comment]
Your best bet is to set a reasonable timeout.. Sadly there isn't enough support to figure a serious way to handle this. The reasonable timeout works ok for most situations.. I wish I could help more.

**Comment by mpmurph** [comment]
@caycek Noted - thanks for the response!

**Comment by ibrasho** [comment]
This is not related to Laravel. It's how HTTP cookies work. 

https://tools.ietf.org/html/rfc6265#section-4.1.2.2

**Comment by ibrasho** [comment]
You can however implement some work arounds if necessary.
Store the current timestamp in the session on every page request and implement a middleware that checks if that period since that timestamp is larger that the allowed period, then do whatever you wanted.

This way you get both both rules.

**Comment by mpmurph** [comment]
@ibrasho Thanks for the link and the middleware suggestion - I think I might try to implement something along those lines.
