### ISSUE TITLE
Collection prepend break array with key values

### ISSUE THREAD

**Issue by Spir** [laravel/framework#9327]
When using prepend method on a collection with a key/value array, we loose all keys since the current use of array_unshift function is not made for array key/value.

**Comment by ibrasho** [comment]
What should happen when the collection contains a key `0`? Should the prepended element be keyed with -1?

**Comment by ibrasho** [comment]
```php
$c = new Collection([
    0 => 'element 0',
    1 => 'element 1',
]);

// What should the new key be?
$c->prepend('element ?');
```

**Comment by GrahamCampbell** [comment]
The current implementation is good imo.
