### ISSUE TITLE
testing different request received in controller and in service provider

### ISSUE THREAD

**Issue by tzookb** [laravel/framework#9329]
keep it simple I have a controller method:
 
    public function whatever(Request $request) {
          //dontcar
    }

and I use "tymondesigns/jwt-auth" package and inside the service provider it has

     app('request')

in general they both should be the same...
but when I dump both of them, the one in the service provider points to "/" and the one in controller points to the right path.

This is called by the simple test:

    public function testPostCreate()
    {
        $server = [
            'HTTP_Authorization' => 'Bearer '.$token
        ];
        $res = $this->put('/api/posts', [], $server);
    }

any ideas why? or maybe a bug?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by GrahamCampbell** [comment]
`$this->put('/api/posts', [], $server);` should be `$this->put('/api/posts', $server);` btw

**Comment by tzookb** [comment]
$server is for headers not data....
and I browsed forums, thought its a bug
