### ISSUE TITLE
Feature request - unpublishes method at ServiceProvider

### ISSUE THREAD

**Issue by appkr** [laravel/framework#9330]
I hope there be `unpublishes()` method and corresponding artisan command in `ServiceProvider`. I think, Laravel package developers may want to withdraw published assets sometimes.

**Comment by GrahamCampbell** [comment]
:-1: from me.

**Comment by appkr** [comment]
I know user can delete them manually. But my thought was it would be great if users can conveniently delete published assets by issuing just a command like `php artisan vendor:unpublish --provider=Abc\Def`. Of course user touched config or something important should not be deleted, but examples or integration test just for quick evaluation purpose can be safely removed by doing so. I think the package developer can pass the list as  arguments.

**Comment by Sladewill** [comment]
It could cause unwanted files to get deleted easily by making a single mistake.
