### ISSUE TITLE
Case sensitivity inconsistent between Route registration and Middleware assignment

### ISSUE THREAD

**Issue by NickAtSchool** [laravel/framework#9335]
*The following issue was discovered using Laravel 5.0 and  has not been tested with any other version of the framework*

**Expected behavior:** Middleware and Routes use the same case-sensitivity when referencing controller actions. Case sensitive is probably the ideal solution

**Current behavior:** Controller actions in middleware registration are case sensitive, while Controller actions in Route registration are not.

**Reproducibility:** In the following example, users may access the routes as normal despite the controller action being lower-case. However, they will encounter the `auth` middleware which should not have been applied due to the `except` clause during middleware registration.
Given the following example, one would expect either of the following:
1. Controller action not found exception when visiting `milestone/{id}`
2. Middleware `auth` is not applied to the `ShowMilestone` action

```php
//routes.php:
//note that "show" is not capitalized. When registering routes, case sensitivity does not mater
Route::get('milestone/{id}', "DatasourceController@showMilestone");
Route::resource('datasources', 'DatasourceController'); //DatasourceController manages a resource. I've omitted the usual CRUD methods for brevity, however

//DatasourceController.php
class DatasourceController extends Controller{
    public function __construct()
    {
        //note that "show" is not capitalized. When registering middleware, case sensitivity matters.
        //As a result, the auth middleware is applied to showMilestone when it appears the coder omitted it
        $this->middleware('auth',['except' => ['showMilestone']]);
    }

    public function ShowMilestone($id)
    {
        //code here
    }
}
```

As you can imagine, this gotcha caused a fair bit of pain/time waste, and I was not able to find any reference to it in the documentation (but of course, I could be mistaken).

**Comment by NickAtSchool** [comment]
My apologies, I just realized that the 5.1 branch. Is there any way I can move this to the appropriate branch, or do I need to recreate it? (is it even necessary to do so?)

**Comment by jhdxr** [comment]
http://php.net/manual/en/functions.user-defined.php says: 
>     Note: Function names are case-insensitive, though it is usually good form to call functions as they appear in their declaration.

**Comment by NickAtSchool** [comment]
If that's the case then, shouldn't middleware assignments follow the same convention as route actions do?

**Comment by GrahamCampbell** [comment]
We ARE case sensitive.
