### ISSUE TITLE
Laravel 5.1 throws ReflectionException after upgrade from 5.0

### ISSUE THREAD

**Issue by siannone** [laravel/framework#9338]
I have recently upgraded Laravel to version 5.1 from 5.0, but whenever I send an API response to the server, it throws an exception like the following:

    ReflectionException in RouteDependencyResolverTrait.php line 57: Class App\Http\Requests\User\GetRequest does not exist

Before upgrading everything was working fine.

This is the `autoload` section of my *composer.json* file:

    "autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/",
		  	"Bloom\\" : "library/Bloom"
		}
	}

Could it be that I did something went wrong during the upgrade procedure?

This is how the `GetRequest` class is declared:

    <?php namespace App\Http\Requests\User;
    
    use App\User;
    use App\Http\Requests\Request;
    use Illuminate\Support\Facades\Auth;
    
    /**
     * Class GetRequest
     * @package App\Http\Requests\User
     */
    class GetRequest extends Request {

**Update**: I just reinstalled Laravel 5.1 and moved all the old files to the new installation but I still receive the same error.

**Update 2**: After running `php composer dump-autoload -o` I can notice that the file *vendor/composer/autoload_classmap.php* contains the class that Laravel is unable to find:

     'App\\Http\\Requests\\User\\GetRequest' => $baseDir . '/app/Http/Requests/User/GetRequest.php',

**Comment by GrahamCampbell** [comment]
Please ask on the forums. This is unrelated to laravel.
