### ISSUE TITLE
Default Resource route names don't use route Group name but prefix instead.

### ISSUE THREAD

**Issue by koenvdheuvel** [laravel/framework#9344]
It seems that a resource routes don't apply the proper route group names but the prefixes of that group instead. for example:

```php
Route::group([
    'prefix' => 'foo',
    'as' => 'bar.'
], function () {
    Route::resource('user', 'UserController');
});
```
The expected route name here would be `bar.resource.method` but instead it is `foo.resource.method`

looking at the code myself I consolidated the method I think is responsible for this behavior : https://github.com/laravel/framework/blob/master/src/Illuminate/Routing/ResourceRegistrar.php#L202-L219

**Comment by GrahamCampbell** [comment]
This is already fixed. Just not available in a tagged release yet.

**Comment by koenvdheuvel** [comment]
I looked to see if this in my eyes problem is fixed in the latest untagged release. But now this code:

```php
Route::group([
    'prefix' => 'backoffice',
    'as' => 'admin.'
], function () {
    Route::resource('region', 'Admin\RegionController');
});
```
Results in `admin.backoffice.region.*` for the route names for the `region` resource. Which coresspondes to `groupname.groupprefix.resource.action` which in my eyes seems very unlogical. Where I would expect it to be `admin.region.*` which is `groupname.resource.action`. 

@taylorotwell what are your thoughts on this design?
