### ISSUE TITLE
Model record not deleting due to global query scope

### ISSUE THREAD

**Issue by Kryptonit3** [laravel/framework#9349]
This explains everything - http://stackoverflow.com/questions/27113205/laravel-cannot-soft-delete-model-using-other-trait

When I find the record with the method appended to disable the global scope it finds the record, but I cannot delete it because the delete method re-adds global scope thus hiding record.

Records not affected by global scope delete fine. And as that post suggests, finding the model with the method to disable the global scope, and then applying the method again to the second call with `delete()` deletes ALL records for that model.

This post kind of goes over what the issue is as well. - https://laracasts.com/discuss/channels/general-discussion/deleting-a-model-wich-has-a-global-scope-excluding-it

The only way I can think of to be sure to delete the record is to do it manually with query builder (bypassing eloquent). But then I would assume soft deletes would not work. :\

The only SURE way to get around this without any issues is to manually assign a `deleted_at` timestamp.

~~~
        $job = Job::withAll()->find($request->input('id'));

        $job->deleted_at = Carbon::now();
        $job->save();
~~~

`withAll()` is [what I use](https://laracasts.com/discuss/channels/eloquent/need-help-writing-remove-for-global-query-scope) to disable the global query scope just so the record can be found (which works).

**Comment by JavoByte** [comment]
I ran into this issue. Solved it by making my trait provide the same funcionality as the soft deleting trait. However, I don't think it's a nice solution. I think the framework should handle this.
+1

**Comment by GrahamCampbell** [comment]
We're open to PRs then. :)

**Comment by Kryptonit3** [comment]
I really hope this can get figured out. Hate to see it closed so quickly. Are global scopes not supported? Don't see them in documentation for 5.1.

**Comment by GrahamCampbell** [comment]
@JavoByte Said he had a solution?

**Comment by PhiloNL** [comment]
I have the same issue, did anyone have a solution for this? Thanks!

**Comment by Kryptonit3** [comment]
@PhiloNL i just decided to use regular query scopes as constraints on the relationship. An example can be found here, look at my response in the comments - https://larabin.com/Jk

**Comment by Anahkiasen** [comment]
Think this is related to the issue I described on #9479

**Comment by olsgreen** [comment]
I've just run into the same issue, to get around it I've changed:

    protected function performDeleteOnModel()
    {
        $this->setKeysForSaveQuery($this->newQuery())->delete();
    }

to:

    protected function performDeleteOnModel()
    {
        $this->setKeysForSaveQuery($this->newQueryWithoutScopes())->delete();
    }

Can anyone see any problems with this? Scopes are used for querying models, the constraints are not needed for creations / updates / deletions.

Created pull request #10369
