### ISSUE TITLE
Add support for alternate hosts to the elixir method

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#9350]
Call me crazy, but I'm wondering if it would be nice to have a config option that represented a host for URIs generated by `elixir`.  Somewhere around here:

https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/Foundation/helpers.php#L678

Some types of CDNs support on-pull assets, which means all it takes to CDN-enable a site is a different host name.  Elixir is already taking care of the cache busting, which could make this a really handy feature!

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. This would be something useful for me too. Also for the `asset` function.

**Comment by atrauzzi** [comment]
Something like this: https://github.com/atrauzzi/bryophyte/blob/master/bootstrap/app.php#L44

**Comment by GrahamCampbell** [comment]
Yeh, only with the correct logic for `secure` The logic there looks wrong.

**Comment by GrahamCampbell** [comment]
Laravel should return https links even if secure is false if the current request was secure.

**Comment by atrauzzi** [comment]
Thanks for the catch :)

**Comment by GrahamCampbell** [comment]
I think the only correct way to do this would be to rebind the url class.

**Comment by GrahamCampbell** [comment]
Messing with helper functions would be the wrong way imo.

**Comment by GrahamCampbell** [comment]
This is something you can do in your own app, and is probably not something for most laravel users.
