### ISSUE TITLE
[Eloquent] BelongsToMany::detach() does not update count

### ISSUE THREAD

**Issue by JellePetersHAN** [laravel/framework#9351]
To reproduce:
```php
$oldCount = $model->models->count();

$model->models()->detach($id);

// Statement below should result in true, but instead gives false since the count hasn't changed
var_dump($model->models->count() !== $oldCount);
```

Is this intentionally or is this a bug?

**Comment by lukasgeiter** [comment]
That's intentionally. The collection is cached in `$model->models` it won't change unless you reload it. You can do that with:

    $model->load('models');

Or just use a query instead of the collection to do the count (if you only need the count that's better anyways)

    $model->models()->count();

**Comment by JellePetersHAN** [comment]
But shouldn't it reload if you detach models, since it makes no sense to keep the connection?

**Comment by lukasgeiter** [comment]
That's easier said then done. With the current implementation this behavior is totally expected.
