### ISSUE TITLE
[5.1.2] Unable to delete Migrations

### ISSUE THREAD

**Issue by johannes-z** [laravel/framework#9356]
In my Application, when I run ```php artisan migrate:make create_location_user_table```, then delete the generated file (doesn't matter if I ex- or include the line created in ```vendor/composer/autoload_classmap.php```, the ```php artisan migrate:refresh``` command throws an error:
```php
include(<path_to_project>/database/migrations/2015_06_21_105357_create_location_user_table.php): failed to open stream: No such file or directory
```

After running commands to get rid of the faulty autoload entry, I get an exception. The commands I tried are: ```composer update```, ```composer dump-autoload```, ```php artisan clear-compiled```, ```php artisan optimize```.

```php
PHP Fatal error:  Class 'CreateLocationUserTable' not found in <path_to_project>\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php on line 323

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'CreateLocationUserTable' not found

```

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
