### ISSUE TITLE
[5.1] Terminable Middleware not called during integration tests

### ISSUE THREAD

**Issue by felixkiss** [laravel/framework#9357]
Given the following Middleware:
```php
<?php namespace App\Http\Middleware;

use Closure;
use Log;

class Test
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        Log::debug('Test#handle() called');
        return $next($request);
    }

    /**
     * Store request/response in log.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Response $response
     */
    public function terminate($request, $response)
    {
        Log::debug('Test#terminate() called');
    }
}
```

`laravel.log` after `GET /` (in browser):
```
[2015-06-21 12:26:26] local.DEBUG: Test#handle() called  
[2015-06-21 12:26:26] local.DEBUG: Test#terminate() called  
```

`laravel.log` after `phpunit` (runs `tests/ExampleTest.php`):
```
[2015-06-21 12:27:30] testing.DEBUG: Test#handle() called  
```

The test does not use `WithoutMiddleware`.

Is this intended behavior or a bug?

**Comment by crynobone** [comment]
Most likely `$app->terminate()` was never called during the test runtime.

**Comment by rafaelbeckel** [comment]
I'm having the same issue here. Is there any way to test a terminatable middleware?

**Comment by felixkiss** [comment]
@crynobone I tried to include `App::terminate()` into my test, but `$this->terminatingCallbacks` are empty (`[]`) in the test environment.

```php
    /**
     * Terminate the application.
     *
     * @return void
     */
    public function terminate()
    {
        foreach ($this->terminatingCallbacks as $terminating) {
            $this->call($terminating);
        }
    }
```

@GrahamCampbell Issue is not resolved. Please reopen.

**Comment by GrahamCampbell** [comment]
Sorry, but this is not a forum. We do have a forum, so please ask there. I'm sure there will be lots of people who can help you there. :)

**Comment by felixkiss** [comment]
So, bug reporting should be handled in the forums?

I consider it a bug, because the existence of `WithoutMiddleware` implies middleware will be executed if this trait is not included.

Terminable middleware is not executed correctly when doing things like `$this->post('foo')`. This is either a bug or unexpected behavior (since other middleware is executed just fine).

It can be fixed by contributing to this repository (by code or by clarifying the non-obvious behavior in the docs).

I reported it, @rafaelbeckel has the same _issue_ (so having an _issue_ on a GitHub repo to me seems like the exact right place to discuss this until it is resolved).

Why in your opinion shouldn't it be discussed/resolved here? I am not asking for a tutorial to write integration tests ...

I am confused.

**Comment by GrahamCampbell** [comment]
You're going to have to provide more information then. Where are you declaring this middleware?

**Comment by GrahamCampbell** [comment]
Middleware inside controllers for example DO NOT terminate. It's simply not supported.

**Comment by felixkiss** [comment]
The middleware is `App\Http\Middleware\Test`, so it is in `app/Http/Middleware/Test.php`.

I use it in the Kernel (`app\Http\Kernel.php`) like so:

```php
<?php namespace App\Http;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Cookie\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,

        /**
         * Application specific middleware...
         */
        Middleware\Test::class,
    ];
```

Pretty standard and right out of the docs.

**Comment by GrahamCampbell** [comment]
Hmmm, ok. Thanks for providing that.

**Comment by felixkiss** [comment]
Thanks. Let me know if I can help any further to resolve this.

**Comment by rafaelbeckel** [comment]
The $response object is an instance of Symfony\Component\HttpFoundation\Response, which current implementation of send() method is:

    public function send()
    {
        $this->sendHeaders();
        $this->sendContent();
    
        if (function_exists('fastcgi_finish_request')) {
            fastcgi_finish_request();
        } elseif ('cli' !== PHP_SAPI) {
            static::closeOutputBuffers(0, true);
        }
    
        return $this;
    }

I've not investigated what closeOutputBuffers() do, but that may probably have something to do with that. $response->send() is called just before terminate() in index.

**Comment by GrahamCampbell** [comment]
We never call the send method when testing.

**Comment by rafaelbeckel** [comment]
Isn't a call to $this->visit('/') a normal http request to the index.php file?

**Comment by GrahamCampbell** [comment]
> Isn't a call to $this->visit('/') a normal http request to the index.php file?

No?

**Comment by felixkiss** [comment]
@rafaelbeckel No. Instead of an actual HTTP request, the instance of `Symfony\HttpFoundation\Request` gets dispatched to the router directly, because it is substantially faster.

**Comment by rafaelbeckel** [comment]
OK. I just read the call() implementation now. Sorry for the dumb question. Should have read it before posting. ;)

**Comment by rafaelbeckel** [comment]
This should solve this issue: https://github.com/laravel/framework/compare/5.1...rafaelbeckel:patch-1

**Comment by GrahamCampbell** [comment]
Further discussion can continue on the PR if required. Thank you everyone. :)
