### ISSUE TITLE
[5.1] Using pattern for domain routing does not get resolved correctly using route() helper

### ISSUE THREAD

**Issue by pixelpeter** [laravel/framework#9359]
I don't know if this is wanted functionality, but if you have this code in `routes.php`

```php
Route::pattern('domain', 'www.laravel51.app|laravel51.app');

Route::group(['domain' => '{domain}'], function() {

  Route::get('test', ['as' => 'testRouteName', function($id) {

    print route('testRouteName') ;

  }]);    
});
```

You'll get this printed
```
http://%7Bdomain%7D/test
```
while the wanted result is:
```
http://laravel51.app/test
```

I could fix this in `Illuminate/Routing/UrlGenerator.php` 

#### OLD
```
    protected function getRouteDomain($route, &$parameters)
    {
        return $route->domain() ? $this->formatDomain($route, $parameters) : null;
    }
```
#### NEW
```
    protected function getRouteDomain($route, &$parameters)
    {
        return $route->domain ? $this->formatDomain($route, $parameters) : null;
    }
```

#### OLD
```
    protected function getDomainAndScheme($route)
    {
        return $this->getRouteScheme($route).$route->domain();
    }
```
#### NEW
```
    protected function getDomainAndScheme($route)
    {
        return $this->getRouteScheme($route).$route->domain;
    }
```

I couldn't find the place where the function `domain()` was defined so I assumed the calls to `$route->domain()` are the problem.

After this fix I get the expected output:
```
http://laravel51.app/test
```

If this is confirmed as an issue I will/could create a pull request

**Comment by Steingate** [comment]
Same problem here in laravel 5.0 !

**Comment by ArjanSchouten** [comment]
The domain method is located in [```Illuminate\Routing\Route```](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Route.php#L860).

The output is completely expected in my opinion. Through the ```route()``` function you want to generate a url for a route. As second argument you can pass the bindings for patterns of the route. You've not passed the second parameter so you get a urlencoded string.

(Furthermore it looks like you're solution only works when you call the function inside the matched route as you do now. I've not tested that thoroughly!)

**Comment by canfiax** [comment]
Have same issue here, laravel 5

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by liveNetworks** [comment]
I have need of following scenario:
{lang}.domain.com and
{username}.domain.com

I'm trying to apply "where" method to Route::domain

`Route::domain('{lang}.domain.com', ['where' => ['lang' => '[a-zA-Z]{2}']])`

and 
`['where' => ['username' => '[a-zA-Z0-9\-]{3,}']`

but it doesn't work as expected.
