### ISSUE TITLE
[5.1] Hydrating a model assumes it exists already?

### ISSUE THREAD

**Issue by cabloo** [laravel/framework#9360]
I stumbled upon this issue while writing a Seeder. The code should be fairly self-explanatory. When I run this, nothing shows up in the database.

```php
list($hdds, $other) = PartType::hydrate([
	['name' => 'Hard Drives'],
	['name' => 'Other'],
])->each(function($item) {
	$item->save();
});

$hdd_parts = Part::hydrate([
	[
		'name' => 'HDD 1',
		'billing_id' => 'HDD-1',
	], [
		'name' => 'HDD 2',
		'billing_id' => 'HDD-2',
	],
]);

$hdds->parts()->saveMany($hdd_parts->all());
```

After some digging through the `Model` source code, I found that the `hydrate` function ends up creating a new `Model` instance and sets the `exists` property to `true`. Then, when calling the save function, nothing is added to the database because it is assumed to exist there already.

As a temporary fix for my use case, I added this to my base `Model`. With this code added, everything shows up in the database as expected.

```php
    public static function hydrate(array $items, $connection = null)
    {
        return parent::hydrate($items, $connection)->each(function($item) {
            $item->exists = false;
        });
    }
```

However, I think the correct solution would be to create each new `Model` instance without assuming it exists already.

**Comment by lukasgeiter** [comment]
That's intentional and totally how hydrate should work.
It's specifically to hydrate the data from the db into a model.

**Comment by cabloo** [comment]
Ah, I understood it as turning raw arrays into models so that they could be
stored in the database.

So I should just create a second function like hydrate that does this
specifically for seeding, using the logic from my overridden hydrate
function?

**Comment by franzliedke** [comment]
These sections of the docs should help you:
- http://laravel.com/docs/5.1/eloquent#inserting-and-updating-models
- http://laravel.com/docs/5.1/eloquent-relationships#inserting-related-models

I think this ticket can be closed. :)

**Comment by cabloo** [comment]
Yes, thanks for your help.
