### ISSUE TITLE
phpunit 'select' function doesn't support empty square brackets for the name

### ISSUE THREAD

**Issue by ArthurGuy** [laravel/framework#9361]
Probably the same issue as #9090 but if you use a field selector with empty square brackets phpunit fails.

I have a multiselect dropdown as follows

`<select multiple="multiple" name="skills[]">`

And I am trying to fill it in

`->select(['skill1', 'skill2'], 'skills[]')`

but it ends up throwing the following exception

`Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <delimiter "]" at 9> found.`

**Comment by ArthurGuy** [comment]
Why was this closed?

**Comment by GrahamCampbell** [comment]
As you said, it's a duplicate. It's already fixed in 5.1.x

**Comment by mikerice** [comment]
I don't believe this particular error is a duplicate. The previous issue was throwing a different exception and appears to work if the square brackets aren't empty.

If the brackets are empty for a multiselect, it's still failing. 

This multi-select:
```php
<div class="form-group">
    {!! Form::label('industries[]', 'Areas of Interest:') !!}
    {!! Form::select('industries[]', $industries, null, ['class' => 'form-control', 'multiple']) !!}
</div>

With this test:
```php
$this->select(4, 'industries[]')
```

Results in:
```
Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <delimiter "]" at 13> found.
```

**Comment by GrahamCampbell** [comment]
Are you using the bleeding edge `5.1.*`? I already know the latest tag doesn't contain this fix.

**Comment by mikerice** [comment]
I am indeed using ```"laravel/framework": "5.1.*"```.

**Comment by GrahamCampbell** [comment]
And what version is that actually installing? Is loading 5.1.2 or 5.1.x-dev?

**Comment by mikerice** [comment]
It's installing 5.1.2.

I also attempted it with 5.1.x-dev and I'm getting the same error, fwiw.

**Comment by GrahamCampbell** [comment]
> I also attempted it with 5.1.x-dev

You should use `5.1.*@dev` to get that btw.

**Comment by bingvanmoorsel** [comment]
Im currently on laravel 5.1.17 and im having the same problemen with the checkbox

`->check('example_checkbox[]')`

results in

`Symfony\Component\CssSelector\Exception\SyntaxErrorException: Expected identifier or "*", but <delimiter "]" at 19> found.`

Stil presists ?
