### ISSUE TITLE
Unable to validate date string/Unable to escape special characters in a validation string

### ISSUE THREAD

**Issue by andkrup** [laravel/framework#9363]
I am trying to validate a date string that contains a comma.

We're using the following composer/bower libraries that may be directly relevant to the problem:
jenssegers/date (3.*), pickadate (~3.5.6)

The date string is specced to look like:
"d F, Y"
, which could translate to: "22 June, 2015"

The validation rules array looks like:
['date' => 'required|date_format:d F, Y']

The comma character in the validation rule-string seems to have a significance in the process that takes place before validation, maybe while creating the validation tokens that later will be used when doing the actual validating (could be some un-intelligent explode-by-comma-after-a-colon use).

Trying to escape the comma with a backslash in the validation string does not seem to work as intended: the validation seems to consider the backslash as part of the string to validate, because the validation continues to displaying errors like this:
"The publish at date does not match the format d F\.".

The problem disappears completely when we remove commas from the date-string value. This is not acceptable because of the date-string has to be localised.

**Comment by lukasgeiter** [comment]
Yes the parameters are exploded by comma, with `str_getcsv` [here](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Validation/Validator.php#L2087).
You should be able to avoid that by using array format instead of a single string:

    [
        'date' => ['required', 'date_format:d F, Y']
    ]

**Comment by daniel-centore** [comment]
This was driving me crazy before I realized that @lukasgeiter 's answer does not work because the comma is being parsed as providing 2 params to the date_format. The answer should look more like this:

`'date' => ['date_format:"d F, Y"'],`
