### ISSUE TITLE
Automatically retry beginTransaction() when hit connection "gone away" issue

### ISSUE THREAD

**Issue by sookteng** [laravel/framework#9367]
Noticed there is auto retry on database queries when connection lost, but not in [beginTransaction()](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Connection.php#L487). Any reason for this discrepancy?

I am getting `PDO::beginTransaction(): MySQL server has gone away` error frequently in my application, so I wish it has the auto retry too.

Please advice if it is possible. Thanks.

**Comment by GrahamCampbell** [comment]
This should already be happening in L5.1.

**Comment by sookteng** [comment]
Can the fixes apply to L4.2 too? I am using L4.2. Thanks.

**Comment by lukasgeiter** [comment]
@sookteng No, 4.2 is not supported anymore.

**Comment by sookteng** [comment]
Noted. Thanks to all the prompt replies.

**Comment by sookteng** [comment]
I have tried in L5.1 with few lines of code below:

```
DB::connection('db');
sleep(20);  //MySQL idle timeout after 10s
DB::connection('db')->beginTransaction();
```

It still throw the same error like L4.2:

`ERROR: exception 'ErrorException' with message 'PDO::beginTransaction(): MySQL server has gone away' in ...\vendor\laravel\framework\src\Illuminate\Database\Connection.php:491`

Please advice. Thanks.
