### ISSUE TITLE
Tests that visit multiple pages in a single test get stale data from the IOC

### ISSUE THREAD

**Issue by rikh42** [laravel/framework#9369]
If you create a test that visits multiple pages, like the example below, on the second request many objects in the IOC are still hanging around from when they were created on the first page. This can have side effects.

Example unit test:

```php
// visit a page (first request)
$this->visit('/example');

// do something that results in a second page request
$this->submitForm('Do Something', ['email' => 'bad email address]);

// check I'm back on example page, but I can see errors on the form
$this->onPage('/example');
$this->see('Some error message about bad email address');
```

In my case I had a form builder class. It's constructor was passed the request, which it used to access the flashed errors in the session. On the second page request, my form builder from the first page request was still in the ioc and was returned. This referenced 'out of date' session error data, resulting in the tests failing (no error messages were displayed, as there were no form errors in the first request).

I think everything in the ioc would need to be cleared out when the test framework attempts to start a new page request to ensure there are no dependencies on the original request or session in existence.

**Comment by GrahamCampbell** [comment]
You need to refresh the application.

**Comment by ibrasho** [comment]
I think this is a valid issue.

Before following each redirect, the app instance should be refreshed by default.

**Comment by GrahamCampbell** [comment]
I don't agree. That could kill performance. We don't want to refresh twice.

**Comment by ibrasho** [comment]
Then your test is not reflecting normal behaviour.

In a normal user-agent, you will get a fresh application for each request.

**Comment by ibrasho** [comment]
This of course will break other aspects of the tests, like sessions.

But I believe we should think of a way to mitigate this.

**Comment by pablorsk** [comment]
(1) **For very specific tests**, you can use:

```
$this->refreshApplication();
```
This resets the application state between each request, ensuring that no data or headers persist across calls.

(2) However, if possible, **it’s better to split the requests into separate focused tests**. This approach keeps your test suite cleaner and more maintainable.
