### ISSUE TITLE
FormRequest object get() method returning null for file input

### ISSUE THREAD

**Issue by sn0opr** [laravel/framework#9372]
the ```get('paramName')``` of the class Illuminate\Foundation\Http\FormRequest is returning null for file input

but when I ```dd($request->all());``` I got the file object ```UploadedFile``` like expected

Laravel version :Laravel 5.0

**Comment by tshafer** [comment]
Hi,
You need to use $request->file('fieldName').

**Comment by sn0opr** [comment]
@tshafer thank you
