### ISSUE TITLE
[Eloquent] SQLiteGrammar should use different date format

### ISSUE THREAD

**Issue by staudenmeir** [laravel/framework#9374]
When using `$query->whereDate('column', '=', '2015-06-22')` with a SQLite database the SQLiteGrammar converts the constraint to `where strftime('date', "column") = ?` which is equivalent to `where strftime('%Y-%m-%d %H:%M:%S', "column") = ?`.

I think it should use `'%Y-%m-%d'` because that's the expected behavior.

**Comment by GrahamCampbell** [comment]
Closing due to lack of interest.
