### ISSUE TITLE
Upgrade from 5.0.33 to 5.1 produces undefined method exception for Illuminate\View\Compilers\BladeCompiler::createOpenMatcher()

### ISSUE THREAD

**Issue by joelsaxton** [laravel/framework#9379]
FatalErrorException in BladeServiceProvider.php line 16: Call to undefined method Illuminate\View\Compilers\BladeCompiler::createOpenMatcher()

    in BladeServiceProvider.php line 16

**Comment by lukasgeiter** [comment]
Extending Blade is done differently in 5.1. [Read the docs](http://laravel.com/docs/5.1/blade#extending-blade)
