### ISSUE TITLE
[5.1] $router->model missing in the docs

### ISSUE THREAD

**Issue by JavoByte** [laravel/framework#9381]
I developed in Laravel since 4.2 and I was in love with "Route model binding". Now, in 5.1, I realized that it still works like in Laravel 5.0 but this section is missing in the docs. Is this now discouraged or something like that?? Or it's just missing from the docs??

**Comment by ArjanSchouten** [comment]
Taylor Otwell deleted it from the docs: https://github.com/laravel/docs/commit/00be759cea21d6b4d59c6ce3814042599e5223f4. As you can read Graham Cambell promised it will come back.

**Comment by JavoByte** [comment]
Ohh I didn't see it. I think new features will come if docs are gonna change. Let's wait for it.

**Comment by GrahamCampbell** [comment]
> As you can read Graham Cambell promised it will come back.

I assumed it would. It's not up to me. I'll ask Taylor now...

**Comment by martindilling** [comment]
Still no news? :/
