### ISSUE TITLE
laravel 5:  can we only send cookie if user is log in ? 

### ISSUE THREAD

**Issue by ssgaur** [laravel/framework#9382]
I do not know this question is right or wrong but it is happening. When i am logged in than everything works fine but if i am not log in than cookie i am sending  with response is not setting. 

Here is code

```
$newCookieCount = Cookie::get('pageviewcount'); 
if(empty($newCookieCount))  $newCookieCount = 1;
else $newCookieCount ++;
$data['pageviewcount'] = Helpers::getMinPageCount() -  $newCookieCount;  // non logged in users
return response()->view('MainSite.schoolhomePage',$data)->withCookie( cookie('pageviewcount', $newCookieCount, 30*24*60) );
```

**Comment by GrahamCampbell** [comment]
> can we only send cookie if user is log in

If I were you, I'd deal with this in your middleware, not in your controller.

**Comment by ssgaur** [comment]
If you can explain little that would be very helpful.
