### ISSUE TITLE
Artisan, parse error

### ISSUE THREAD

**Issue by StephanMeijer** [laravel/framework#9384]
```
Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/dir/Documents/websites/dir/artisan on line 31
```

```
PHP 5.4.38 (cli) (built: Mar 19 2015 14:49:15) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

Laravel, go fix your stuff.

**Comment by GrahamCampbell** [comment]
We don't support php 5.4.

**Comment by StephanMeijer** [comment]
Come on! PHP 5.4 is a wide-used PHP version, and I think you **SHOULD** support PHP 5.4.
Please, go back to your boss and tell him to support wide-used PHP versions.

**Comment by GrahamCampbell** [comment]
PHP 5.4 doesn't receive security fixes from the core team very soon. It's not up for negotiation. Laravel doesn't supported it anymore.

**Comment by StephanMeijer** [comment]
I don't 'believe' in people not supporting widely used technology. However, your message is clear to me, and I think it's time to close this issue :).

Thanks for your time!

**Comment by GrahamCampbell** [comment]
> widely used technology

It's not widely used if you look at the actual composer stats. Way over half use 5.5+.

**Comment by franzliedke** [comment]
Though, to be fair, Composer stats have little to do with actual PHP usage.

**Comment by GrahamCampbell** [comment]
> Composer stats have little to do with actual PHP usage.

We don't care about people not using composer though. It makes no different to us if those people are using php 3. People using composer represents the set of people we care about.
