### ISSUE TITLE
[Blade] Supporting custom footers

### ISSUE THREAD

**Issue by srph** [laravel/framework#9386]
## What
- I'd like to have custom footers, for example, making something similar to `@extend`.
- Custom directives seem to be parsed at the same line.
- My directive needs to be placed at the bottom of the file when compiled (because it is similar to `@extend`).
- I don't really want to put a directive similar to `@extend` to be written on the last line of the blade file.

## Case
Currently, I have a directive that functions like `@extend`, however, I am writing it to view file (`my-view.blade.php`) at the last line 

```blade
@section('body')
@base
```

Why? Because custom directives are simply parsed in the same line. The following example:

```php
@base
@section('body')
```

Becomes:

```php
<?php echo $__env->make('themes/_blank/pages/base', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

<?php $__env->startSection('title'); ?><?php echo e($store->message); ?><?php $__env->stopSection(); ?>
```

But this is what I want to achieve:

```php
<?php $__env->startSection('title'); ?><?php echo e($store->message); ?><?php $__env->stopSection(); ?>

<?php echo $__env->make('themes/_blank/pages/base', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
```

I'd like the `->render()` fn to be called in the bottom like what `@extend` does.

Without making it a `footer`, I happen to be forced to write the code like this:

```php
@section('body')
@base
```

Just so it would work :disappointed:.

=====

I can see if I can send a PR if this is an okay proposal.

**Comment by GrahamCampbell** [comment]
I don't think we really need this. This can already be achieved using the current directives. Thank you though. :)

**Comment by srph** [comment]
Ahh, I see. Mind elaborating? Thanks :smile:
