### ISSUE TITLE
PHP 5.6.0 mbstring.internal_encoding is deprecated

### ISSUE THREAD

**Issue by grvweb** [laravel/framework#9392]
mbstring.internal_encoding is deprecated for php version 5.6.0.
Please address this error:
undefined function Illuminate\Foundation\Bootstrap\mb_internal_encoding() 
Illuminate\Foundation\Bootstrap\LoadConfiguration.php on line 43

**Comment by jonursenbach** [comment]
Why was this issue closed?

**Comment by grvweb** [comment]
Issue which was raised by me was invalid.
mbstring.internal_encoding is deprecated for php version 5.6.0 but, mbstring.internal_encoding is not mb_internal_encoding() and mb_internal_encoding() was not deprecated.
mbstring.internal_encoding doc http://php.net/manual/en/mbstring.configuration.php
and
mb_internal_encoding() doc http://php.net/manual/en/function.mb-internal-encoding.php
so, I closed this issue.

**Comment by NitroBAY** [comment]
Same problem here

**Comment by GrahamCampbell** [comment]
What Laravel version?

**Comment by NitroBAY** [comment]
when I supress mb_internal_enconding on line 43 I can get version with artisan and it's Laravel Framework version 5.1.19 (LTS) 
Besides I tried to update once I supressed mb_internal_enconding I can composer update but it said - laravel/framework v5.1.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
thus I php --ini and it said that "php.ini Path: C:\WINDOWS" tough I set in path C:\UwAmp\bin\php\php-5.6.14

**Comment by GrahamCampbell** [comment]
You need to install that extension on your server.

**Comment by NitroBAY** [comment]
I use uwamp and on phpinfo() mbstring seems activated
If you're talking about internal_enconding() tough I read doc I don't understand HOW install extensions?

**Comment by GrahamCampbell** [comment]
> the requested PHP extension mbstring is missing from your system.

**Comment by GrahamCampbell** [comment]
You can't use Laravel without that installed.

**Comment by GrahamCampbell** [comment]
Is your cli version of php different to the one your using for your websever?

**Comment by NitroBAY** [comment]
I use Uwamp not webserver what is clui?

**Comment by haleksandre** [comment]
@NitroBAY The CLI is the php you use in your cmd prompt (terminal) and not necessarily the same version that uWamp uses. The mbstring extension might be enabled for your php cli but not for your uWamp.

Check that the version uWamp uses located in uwamp/bin/php has the mbstring extension enabled.

**Comment by NitroBAY** [comment]
in bin/php/phpX.X.X 
And I've enabled mbstring in them
![phpini](https://cloud.githubusercontent.com/assets/9869317/10594186/c56ea7e2-76ca-11e5-98ba-c9491b2fe004.PNG)

**Comment by haleksandre** [comment]
@NitroBAY 

A simple way to troubleshoot webserver's php is to add the `phpinfo()` method inside the index.php.

```php
<?php
    phpinfo();
?>
```

When refreshing the index.php page you should have the information you are looking for like which `php.ini` the uWamp webserver uses.

**Comment by NitroBAY** [comment]
Okay it's done

**Comment by NitroBAY** [comment]
A question that there is nothing to deal with the question but IDK where ask for and google don't want to tell me, thus in a web project should I start by back-end (php/mysql) or front (html/design) ?

**Comment by NitroBAY** [comment]
Even in C:\UwAmp\bin\apache\php.ini the line mb_string don't have ;

**Comment by GrahamCampbell** [comment]
Please discuss on the forums. This is not a bug.

**Comment by DanDvoracek** [comment]
As this is one of the first result in Google, I thought I would post my solution here.

Simply ssh your vagrant box and run

`$ sudo apt-get install php5.6-mbstring`
`$ sudo apt-get install php5.6-curl` 

then `$ composer update`. Simply make sure mbstring and php versions are the same and it should do the trick.. it did for me!
