### ISSUE TITLE
Middleware Parameters

### ISSUE THREAD

**Issue by tratotui** [laravel/framework#9394]
Good day.
In Laravel 5.1 an opportunity to pass parameters to middleware, but what if I want to transfer more than one parameter? In this case, I have no way to do it.
For example:
```php
// ...
get('/admin-terms', 
    ['middleware' => 'role:admin;requireAll:true', ...]
);
```
Now there is no possibility to achieve this result.

**Comment by ArjanSchouten** [comment]
https://mattstauffer.co/blog/passing-parameters-to-middleware-in-laravel-5.1 As far as I know you can. Separated by comma.

**Comment by EwanValentine** [comment]
Use a variadic parameter in your middleware. 

```
Route::group(['middleware' => 'role:admin,editor,user'] function(){});
```

Then in your middleware

```
public function __construct(...$roles) 
{
    dd($roles);
}
```

You should have an array of your roles
