### ISSUE TITLE
[5.12] Logging in with "Remember me" causes TokenMismatchException on form submit

### ISSUE THREAD

**Issue by OskarD** [laravel/framework#9395]
This started happening a few days ago, about 30 hours into development. Reverting with version control to a moment before the bug was discovered does not fix the error.

Laravel 5.1
Windows 8.1
Google Chrome Version 43.0.2357.124 m
PHP Version 5.6.8

* Only happens on my Chrome browser (Tested latest IE and latest FF)
* Happens in incognito mode as well
* Occurs more often than not (About 90% of the time I submit a form)
* Does not appear to have anything to do with the frequency of form submissions
* Happens in both prod and local APP_ENV

![image](https://cloud.githubusercontent.com/assets/6658382/8326691/1b03a4e2-1a63-11e5-9e32-b2ec793641ec.png)

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by OskarD** [comment]
I opened [a thread on the forums](https://laracasts.com/discuss/channels/laravel/512-logging-in-with-remember-me-causes-tokenmismatchexception-on-form-submit) like you asked, but nobody has been able to come up with a solution or explanation. Someone else also has this problem and posted in my thread. What should I do?

**Comment by OskarD** [comment]
@GrahamCampbell I opened [a thread on the forums](https://laracasts.com/discuss/channels/laravel/512-logging-in-with-remember-me-causes-tokenmismatchexception-on-form-submit) like you asked, but nobody has been able to come up with a solution or explanation. Someone else also has this problem and posted in my thread. What should I do?

**Comment by OskarD** [comment]
ping  @GrahamCampbell

**Comment by OskarD** [comment]
ping @GrahamCampbell
