### ISSUE TITLE
5.1 Documentation: Example of non-queued Job (or command bus-style Jobs)

### ISSUE THREAD

**Issue by bgetsug** [laravel/framework#9400]
For those of us with large/complex domains, the command bus pattern which separates command DTOs from handling classes is commonly used. So, I've found transitioning to Laravel 5.1 a bit confusing in this area. While there is clear documentation on how to use the new `Job` classes with queues, it is unclear how they should be used as command bus-style commands. (I believe @taylorotwell mentioned continued support for this in a recent tweet.) Additionally, it would be nice to know what is required to use Jobs without the `SelfHandling` interface. If I have a `MyJob` class, would I simply create a `MyJobHandler` class in the same namespace? Should I refer to the 5.0 documentation? Or should I use a package like Laracasts Commander? It would seem redundant to use a package like Commander, if the same functionality is bundled with the framework.

Please advise, thank you :)

**Comment by GrahamCampbell** [comment]
> For those of us with large/complex domains, the command bus pattern which separates command DTOs from handling classes is commonly used. So, I've found transitioning to Laravel 5.1 a bit confusing in this area.

You don't need to change anything or name things jobs. Take a look at my code here: https://github.com/StyleCI/StyleCI.

**Comment by bgetsug** [comment]
So are you saying I'm bound to the directory structure of Laravel out of the box? What if I want to keep my commands and handlers in the same namespace?

**Comment by Anahkiasen** [comment]
No you can configure the namespaces in the `BusServiceProvider`, doesn't affect the `make:command` command though, just where Laravel looks

**Comment by GrahamCampbell** [comment]
> So are you saying I'm bound to the directory structure of Laravel out of the box? 

No, not at all. The exact opposite. :) That's why I gave you a link to my project which doesn't use the Jobs structure that I don't like.

**Comment by bgetsug** [comment]
@GrahamCampbell, is this what you expected me to find?

```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Boot the service provider.
     *
     * @param \Illuminate\Bus\Dispatcher $dispatcher
     *
     * @return void
     */
    public function boot(Dispatcher $dispatcher)
    {
        $dispatcher->mapUsing(function ($command) {
            return Dispatcher::simpleMapping($command, 'StyleCI\StyleCI', 'StyleCI\StyleCI\Handlers');
        });
        $dispatcher->pipeThrough([ValidatingMiddleware::class]);
//...
```

**Comment by GrahamCampbell** [comment]
That just says that something named `StyleCI\StyleCI\Commands\FooCommand` will get handled by `StyleCI\StyleCI\Handlers\Commands\FooCommandHandler`.

**Comment by GrahamCampbell** [comment]
You don't need to worry about that pipe through bit - that basically just runs my validation middleware on the commands before executing them.

**Comment by GrahamCampbell** [comment]
> is this what you expected me to find?

That, and my entire app structure.

**Comment by bgetsug** [comment]
@GrahamCampbell, actually I would prefer being able to have some sort of validation middleware. At the moment I'm using FormRequests for validation, since the validation bus decorator was removed from Laracasts Commander. Perhaps I'll have to dig into pipes further, referring to the 5.0 documentation. 

I'm sure your project structure is appropriate for your domain. My domain has over 230 entities, so throwing all of those into one Models directory would be a bit unwieldy, as would storing all repositories in a single directory, etc.  (Yes, 200+ entities smells of needing to break up a monolith...I didn't write them...it's all "legacy" code...we're working on it.) So what I try to do is create modules, each within its own namespace, where I keep related classes together. For example:
```
app/
    Products/
        Http/
        Commands/
        Entities/
        Repositories/
        ProductsServiceProvider.php
    Users/
        Http/
            Middleware/
        Commands/
...
```
So, I'll end up having multiple Commands directories.  Looking at `Illuminate\Bus\Dispatcher`, I'm not yet clear on whether multiple mappings are supported...maybe I have to implement my own `HandlerResolver`?

(@Anahkiasen, I don't have a `BusServiceProvider` in my project (app/.../Providers). I also checked here: https://github.com/laravel/laravel/tree/master/app/Providers. A `BusServiceProvider` does exist in the `Illuminate\Bus` namespace. Feels like something must have changed in 5.1...?)

**Comment by GrahamCampbell** [comment]
>  I don't have a BusServiceProvider in my project (app/.../Providers).

That doesn't matter. The boot method of my app provider is basically the same as if i were to ave put it into a bus service provider - I just didn't see the point at the time.

> actually I would prefer being able to have some sort of validation middleware.

Sure. That middleware is available in https://github.com/AltThree/Validator. We provide a model observer that validates on save too if you're interested in that. They both throw the same exception on validation error.

**Comment by bgetsug** [comment]
Well it looks like multiple mappings are supported via `Illuminate\Bus\Dispatcher::maps()`...I'll give that a shot.
