### ISSUE TITLE
Testing Jobs

### ISSUE THREAD

**Issue by viraj-khatavkar** [laravel/framework#9401]
$this->expectsJobs() doesn't work for the $this->dispatchFrom() method

**Comment by GrahamCampbell** [comment]
We need way more info than that.

**Comment by viraj-khatavkar** [comment]
Hi Graham,

While unit testing, if I use **$this->expectsJobs()**, it works totally fine for testing **$this->dispacth()** method .

But, if I use **$this->dispatchFrom()** method to dispatch jobs, then **$this->expectsJobs()** doesn't work while running tests

**Comment by GrahamCampbell** [comment]
Yeh, that's the expected behaviour.

**Comment by viraj-khatavkar** [comment]
But, need to have some abstraction to test *$this->dispatchFrom()* as well..

**Comment by viraj-khatavkar** [comment]
@GrahamCampbell So we are not going to implement this ? I just want to know a valid reason for not having a helper method to test this case ?
