### ISSUE TITLE
5.1 Documentation: Route Model Binding has disappeared

### ISSUE THREAD

**Issue by barryp** [laravel/framework#9403]
Route Model Binding, documented in 5.0 here: 

http://laravel.com/docs/5.0/routing#route-model-binding 

doesn't seem to appear anywhere in the 5.1 documentation.

I hope it's not deprecated (not listed as such) - I use that feature quite a bit.

**Comment by tomzx** [comment]
See https://github.com/laravel/docs/commit/00be759cea21d6b4d59c6ce3814042599e5223f4#diff-ce107015c43d323e34bbf68cbc83e623.

**Comment by ArjanSchouten** [comment]
It's exactly the same as an already opened issue: #9381.

**Comment by franzliedke** [comment]
Doesn't seem to be fixed, @GrahamCampbell. The other issue is closed.

**Comment by TheShiftExchange** [comment]
@GrahamCampbell - both issues are closed - with neither having a resolution. 

Can we please have a formal answer on the status of this function? If it is going to be depreciated - can we know for sure?

**Comment by ryanmortier** [comment]
+1

@GrahamCampbell is this feature still supported or is it something that will be depreciated?

**Comment by paslandau** [comment]
+1 ...

**Comment by webkenny** [comment]
FWIW, this actually affected me in a project recently. I didn't include this in an API that could have seriously used it. I wasn't sure if it was deprecated so I didn't use it. +1

**Comment by ArjanSchouten** [comment]
Probably someone can ask it in the slack channel?

**Comment by vvinhas** [comment]
+1

**Comment by GrahamCampbell** [comment]
No point in +1 closed issues. Taylor doesn't read the issues anyway. If you want something, you must contact him directly.
