### ISSUE TITLE
[5.1] Can't use .php extension in POST route

### ISSUE THREAD

**Issue by mirzabusatlic** [laravel/framework#9405]
It doesn't seem possible to use a .php extension (or possible other extensions) with POST. This always throws a 405 error:

```
# cURL request
curl -X POST -d 'id=5' http://foo.local:8000/some_file.php
```

```php
Route::post('some_file.php', 'SomeController@someMethod');
```

However, GET does work, but I can't access any data within the controller method.
```php
Route::get('some_file.php', 'SomeController@someMethod');

# Within SomeController@someMethod
$request->all() // Always empty...
```

**Comment by GrahamCampbell** [comment]
This is to do with your routing before you even reach laravel.
