### ISSUE TITLE
Model::fresh should reload relations specified in $with?

### ISSUE THREAD

**Issue by theatrain** [laravel/framework#9406]
As the comment above the protected $with variable says "The relations to eager load on every query.", shouldn't this be included?

**Comment by GrahamCampbell** [comment]
Probably yeh. We're open to PRs.

**Comment by dwightwatson** [comment]
It already does this, `fresh()` fires off a fresh query which includes the default eager loads.

**Comment by GrahamCampbell** [comment]
Thank you @dwightwatson.
