### ISSUE TITLE
Eager loading polymorphic relations in different namespaces

### ISSUE THREAD

**Issue by phroggyy** [laravel/framework#9407]
Currently, eager loading polymorphic relations works perfectly fine if the associated models are all in the same namespace. For those that aren't familiar with how polymorphic relations work under the hood, it's basically just an extension of `BelongsTo`. What happens is that, since your database is structured with a related type and id, let's call them `source_type` and `source_id` respectively, we establish a `BelongsTo` relationship with the model called `source_type`, which has `id = source_id`. The actual name prepended to type and id, in this case `source`, is by default determined by the name of the caller function, so in its very simplest form, we could have

~~~
class MorphMe {

    public function source() {
         return $this->morphTo();
    }
}
~~~

and that would be all we need. However, down the line, our morph has to build up the related model. The only data it has to do that is our `type` and `id`. Let's create a scenario for demonstration purposes:

## Scenario

We have an instance of `MorphMe` above, call it `$model`. Our `related type` column is `source_type` and our `related id` column is `source_id`.  
Now, let's say

~~~
$type = $model->source_type;
$id = $model->source_id;
~~~

Even though it works in a slightly more complicated way, the easiest way to think about it is that our `morphTo()` will create a new `MorphTo` instance, which will call `$type::find($id)` in order to find our related model (it doesn't work exactly like this, but it is the end result), and will then attach it. However, if $type ends up not being in the same namespace, $type cannot be instantiated (because that's what's actually done, the model is instantiated and then hydrated) because our application can't locate the class. This is no surprise; if we have

`Acme\Modules\First\MorphMe` and `Acme\Modules\Second\Example`, it's quite obvious that calling
~~~
new Example();
~~~
from `MorphMe` will result in the class not being found.

Well, we can solve this issue by mapping the name in our table to the actual class, right? let's just add a protected `$types` array and we're set, right?

~~~
class MorphMe {

    protected $types = [
        'example' => 'Acme\Modules\Second\Example'
    ]

    public function source() {
         return $this->morphTo();
    }
}
~~~

Well, we need a way to actually make sure we return the fully qualified class name when we attempt to access the `source_type` attribute, so let's write an accessor, as suggested by Taylor in #3090, and exemplified on [StackOverflow](http://stackoverflow.com/questions/27866020/laravel-returning-the-namespaced-owner-of-a-polymorphic-relation#answer-27993113):

~~~
class MorphMe {

    protected $types = [
        'example' => 'Acme\Modules\Second\Example'
    ]

    public function source()
    {
         return $this->morphTo();
    }

    public function getSourceTypeAttribute($type)
    {
        // transform to lower case

        $type = strtolower($type);

        // to make sure this returns value from the array
        return array_get($this->types, $type, $type);

        // which is always safe, because new 'class'
        // will work just the same as new 'Class'
    }
}
~~~

Well, we have a couple issues now... If we have a hydrated instance of the model, and attempt to access the source type, we'll **always** get the fully qualified class name back, which may or may not be desired (for my application, I need both the class name and the original value separately). We could of course surpass this with another method and that's solved.

**This works**. We can now do something like
~~~
$morphMe = MorphMe::find(1);
$parent = $morphMe->source;
~~~
and it will correctly return the related model.

## The issue

However, what we can't do is something like
~~~
AnotherModel::with('morph.source')->get();
~~~
where `AnotherModel` is some model related to `MorphMe` through a `morph` method which contains a simple relationship (`belongsTo` or `hasOne` for example).

If we run this, we hit a wall:

~~~
FatalErrorException in Model.php line 836:
Class '' not found
~~~

## So what happened?

Well, in short, Laravel didn't hydrate the model before we attempted to get our `source_type`, so the field was empty. Our accessor hence received null, and `strtolower(null) == ''`. So we attempted to instantiate a model that doesn't exist...

## How do we solve this?

I propose adding a protected attribute on the model along the lines of `$types`, or for less ambiguity `$morphMap`, `$morphClassMap` or similar. This attribute could then be accessed by our `MorphTo` instance to check if we have a mapping for the given type, and then use that instead (in essence doing the same as the accessor, but in a more general way and in the relation class itself instead).

Most likely, I'll do a PR since this is a relatively quick fix, unless someone else is faster.

## A temporary solution

After a bit of thinking, the quickfix is just overwriting the `morphTo` method and adding a new method to retrieve the fully qualified class name:

~~~
class MorphMe extends Model {

    protected $types = [
        'resource' => 'Snowfire\Domain\Resources\Resource'
    ];

    public function source()
    {
        return $this->morphTo();
    }

    public function morphTo($name = null, $type = null, $id = null)
    {
        // If no name is provided, we will use the backtrace to get the function name
        // since that is most likely the name of the polymorphic interface. We can
        // use that to get both the class and foreign key that will be utilized.
        if (is_null($name)) {
            list(, $caller) = debug_backtrace(false, 2);

            $name = snake_case($caller['function']);
        }


        list($type, $id) = $this->getMorphs($name, $type, $id);

        // If the type value is null it is probably safe to assume we're eager loading
        // the relationship. When that is the case we will pass in a dummy query as
        // there are multiple types in the morph and we can't use single queries.

        $type = $this->getMorphClassName($type);

        if (is_null($class = $this->$type)) {
            return new MorphTo(
                $this->newQuery(), $this, $id, null, $type, $name
            );
        }

        // If we are not eager loading the relationship we will essentially treat this
        // as a belongs-to style relationship since morph-to extends that class and
        // we will pass in the appropriate values so that it behaves as expected.
        else {
            $instance = new $class;
            return new MorphTo(
                $instance->newQuery(), $this, $id, $instance->getKeyName(), $type, $name
            );
        }
    }

    private function getMorphClassName($reference)
    {
        // transform to lower case

        $type = strtolower($reference);

        // to make sure this returns value from the array
        return array_get($this->types, $reference, $reference);

        // which is always safe, because new 'class'
        // will work just the same as new 'Class'
    }
}
~~~

Please note that this still does not solve the issue of eager loading, but rather only of manual loading if we still want to be able to access the attribute.

**Comment by GrahamCampbell** [comment]
Further discussion can continue on the open PR. :)
