### ISSUE TITLE
[Feature Request] event:generate could take EventListener subscribed events into account

### ISSUE THREAD

**Issue by younes0** [laravel/framework#9410]
`artisan event:generate` could generate events defined in `EventListener`s which are, as you know, defined in `EventServiceProvider`

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by younes0** [comment]
Sorry was more like a feature *proposal *;) I assume it's not a bid idea
then, I will take a look into it then
ᐧ

2015-06-25 14:51 GMT+02:00 Graham Campbell <notifications@github.com>:

> We're open to PRs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/framework/issues/9410#issuecomment-115241680>.
>



-- 
EL BIACHE Younès
Gérant chez YebSoft
Création de sites, applications Web et Android
07 82 13 34 50
http://www.yebsoft.com

**Comment by GrahamCampbell** [comment]
We don't process feature proposal issues. Issues, as documented in the contributing guidelines are only there for the community to report bugs and for the community to fix bugs.

**Comment by younes0** [comment]
Okay got it, thanks for the info
