### ISSUE TITLE
Route model binding interfaces

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#9411]
If you register a model interface

```php
app()->bind('App\Users\UserModelInterface', 'App\Users\User');
```

Then route bind it, laravel won't find the class.

```php
app('router')->model('users', 'App\Users\UserModelInterface');
```

This is because the [class is not resolved through the IOC](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L943), only when you use `bind` [does it resolve](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/Router.php#L992) -- but that's a headache to use with Eloquent models.

@taylorotwell would you consider a PR to resolve through IOC for `::model()` calls?

**Comment by GrahamCampbell** [comment]
:-1: We already have ditched the middleware interface.

**Comment by Sladewill** [comment]
Sorry but what does middleware interfaces have to do with route model binding?

**Comment by GrahamCampbell** [comment]
> Sorry but what does middleware interfaces have to do with route model binding?

I'm saying that we're moving away from adding interfaces we don't need. Middleware was an example of that.

**Comment by GrahamCampbell** [comment]
Sorry, the issue title was misleading. I agree with this proposal.

**Comment by GrahamCampbell** [comment]
Please don't create proposal issues for small changes though.

**Comment by garygreen** [comment]
@GrahamCampbell Shall I create a PR and target it at master?
