### ISSUE TITLE
Illuminate\Support\Arr::get has inconsistent behavior?

### ISSUE THREAD

**Issue by enriquemorenotent** [laravel/framework#9415]
I was looking at the `\Illuminate\Support\Arr` class, more exactly to the [get method](https://github.com/illuminate/support/blob/master/Arr.php#L200) and I noticed some inconsistent behavior.

	\Illuminate\Support\Arr::get(["a" => 1], false, "default"); // => "default"

	\Illuminate\Support\Arr::get(["a" => 1], null, "default"); // => ["a" => 1]

What is the reason for this inconsistency? Is it on purpose?

**Comment by ArjanSchouten** [comment]
Yes it is inconsistent behavior. This comes from this commit: https://github.com/illuminate/support/commit/a370a739fac41929acdf8165a2bee7ec30a0423d. Before this commit the array_get function was not ready for mixed input types. Hope we can fix this.

**Comment by enriquemorenotent** [comment]
I'd be happy to fork it, if I knew what it the proper behavior. Should we return the array for invalid keys? Or just the default value?

**Comment by ArjanSchouten** [comment]
However it is a bit uncommon to pass null as the key but it can happen that null is passed. Probably we can look at the [```first()```](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Arr.php#L150) method which has also a 3th parameter which is the default value.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by briedis** [comment]
Yeah, this was a wtf moment, when I came across it.

Simple use case:
```
$key = Input::get('key');
$value = array_get($arr, $key);
if($value){
    // User gave a valid key
}
```
If no input is given, null is returned - array_get returns all of the array.

This behavior does not make any sense to me.

**Comment by taylorotwell** [comment]
`Null` has always just returned the entire array. `False` probably should too.
