### ISSUE TITLE
theme support in views

### ISSUE THREAD

**Issue by HuaTiMeiTian** [laravel/framework#9420]
a cms has many themes, it not convenient now

**Comment by GrahamCampbell** [comment]
Ask on the forums.

**Comment by HuaTiMeiTian** [comment]
i'm asking ?

**Comment by GrahamCampbell** [comment]
This isn;t a forum.

**Comment by HuaTiMeiTian** [comment]
i mean you should make theme change easier,this is a suggestion, i know how to set theme now , but it is not convenient

**Comment by HuaTiMeiTian** [comment]
This is a suggestion for user experience

**Comment by GrahamCampbell** [comment]
There is no such concept as "themes" in laravel's core.

**Comment by HuaTiMeiTian** [comment]
so consider to add it in next version ,users do not care about your concept first; UX first；

please do not reply me, this is just a suggestion ,that's all

**Comment by GrahamCampbell** [comment]
It would make no sense at all to add this to the core. We already have easy ways to achieve what you want.
