### ISSUE TITLE
Allow indexes to be created in timestamps method

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#9424]
As this is just a helper function to create two timestamp columns, it'd be nice if we could pass two args to the ```Blueprint timestamps``` function to automatically create an index for each column, e.g.

```$table->timestamps(true, true)``` where each value is whether to create an index for the created_at and updated_at columns respectively. Default value could be false of course.

**Comment by GrahamCampbell** [comment]
We don't process proposal issues. Sorry. Please review our contribution guidelines.
