### ISSUE TITLE
add a $defaults property to Eloquent?

### ISSUE THREAD

**Issue by ChangePlaces** [laravel/framework#9425]
This is how I understand one can define default values for models:

```
public function __construct()
{
    $defaults = ['some_property' => 'asdf', 'another_property' => 'qwerty'];
    parent::__construct($defaults);
}
```
This is a bit fiddly. So, in keeping with using properties to define useful features, such as $fillable etc, how about using a ```$defaults``` property so in the Model constructor any attributes passed to the constructor can be merged into the defaults array defined in the model class?

**Comment by GrahamCampbell** [comment]
Proposed before and rejected.

**Comment by ChangePlaces** [comment]
link please, and why?

**Comment by GrahamCampbell** [comment]
> link please

You're going to have to find it yourself. I have no idea where it is.

**Comment by ChangePlaces** [comment]
Well search doesn't provide any answer, so maybe it hasn't been proposed before
