### ISSUE TITLE
message crypt() no salt parameters specified.you must use a randomly generated salt and strong hash function to a produce secure hash 

### ISSUE THREAD

**Issue by MarkVaughn** [laravel/framework#9428]
This issue was opened on HHVM https://github.com/facebook/hhvm/issues/5021
The opinion seems to be this is a Laravel issue.
Basically our bugnsag on hhvm is catching an Exception from a warning 
````
ErrorException crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.
:0handleError
[internal]:0crypt
[internal]:0password_verify
vendor/laravel/framework/src/Illuminate/Hashing/BcryptHasher.php:45check
vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:108validateCredentials
vendor/laravel/framework/src/Illuminate/Auth/Guard.php:378hasValidCredentials
vendor/laravel/framework/src/Illuminate/Auth/Guard.php:359attempt
vendor/laravel/framework/src/Illuminate/Auth/Guard.php:263validate
[internal]:0call_user_func_array
vendor/laravel/framework/src/Illuminate/Support/Manager.php:138__call
src/SellerLabs/Snagshout/Auth/Authenticator.php:141run
src/SellerLabs/Snagshout/Auth/Controllers/AuthController.php:139postLogin
````
Why does this warning get raised to Exception? Is laravel not using the hash function with salt?

**Comment by GrahamCampbell** [comment]
This appears to only be an issue with php 7.0 which is why laravel doesn't support it yet. HHVM seems to be implementing bits and pieces from php 7 which is why we observe this error.

**Comment by arunpoudel** [comment]
To be more precise, this happens only when the password on your db is empty. This can be reproduced in hhvm using:

`password_verify('hello', '')`

**Comment by GrahamCampbell** [comment]
Thanks guys. I'll get this sorted.

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/pull/9651.
