### ISSUE TITLE
[L5.1] Database encoding problem

### ISSUE THREAD

**Issue by monsterdream** [laravel/framework#9437]
Hi,
I'm not so avanced user to fix the problem, so I hope somebody will take care of that in the future. 

The problem occuring when I want to seed MySQL database with for example Swedish, Polish letters, below example compering this same enviorments, settings etc with Laravel 5.0 (working on right properly, and Laravel 5.1.3 on the left). Settings for utf8 and utf8_unicode_ci.

![1](https://cloud.githubusercontent.com/assets/9707557/8393725/0a624d8e-1d1d-11e5-9e6e-e856538b454e.jpg)

**Comment by RomainLanz** [comment]
Please, ask these kinds of questions in the forum.
