### ISSUE TITLE
[Proposal] Auth Middleware

### ISSUE THREAD

**Issue by sniper7kills** [laravel/framework#9448]
Currently when logging a user in two events are fired. `auth.attempt` and `auth.login`.

These events allow us to hook into the auth process and make changes to the user, or update settings for the user. But they don't allow us send information back or stop the authentication process.

A trivial example:
My user table has a `status` column. I only allow users to login who have a `status` of `active`. 
The current way I handle this across my application is by having all logins (api & website) use the same `LoginRequest` that forces `status` to be `active` when looking up a user.

While this is a trivial example, I feel that it would be a much simpler solution in the long run to introduce Auth Middleware. This would allow us to do our simple check and pass off the authentication to the next middleware.

An advance example:
Two Factor Authentication. Right now (as far as I can tell) the main methods of implementation are by using route middleware to check if the user requires two-factor and if they have supplied it for this login; or by updating their auth controller to first `Auth::validate`, preform two factor, then `Auth::attempt`.

I feel these are both bad solutions as 
1) the route middleware continues to run even after the authentication process has already been finished
2) updating the controller means that you have to duplicate that code anywhere else a user logs in.
3) Both solutions allow for holes that allow the user to be logged in regardless of any extra checks that need to take place

As such I would like to propose Auth Middleware to easily allow developers to add additional authentication checks before they are logged into the application.

Middleware should be able to:
1) pass the request to the next middleware
I.E. User has passed this check
2) stop the request
I.E. User's `status` is not `active`
3) pause the request and redirect to gather additional information
I.E. If a user needs to enter a code, they should **not** be logged in, but directed to another login page to enter that code and upon submitting it they should be able to continue without having to re-enter their username/password.

Hopefully I submitted this in the correct place. If not I apologize, Please let me know and I'll move it.

**Comment by GrahamCampbell** [comment]
Sorry, we don't process proposal issues. Please see the contributing guidelines.

**Comment by sniper7kills** [comment]
@GrahamCampbell Sorry about that. I'll try to jump on the IRC today and propose it there.
