### ISSUE TITLE
[Lumen] Documentation doesn't have text search

### ISSUE THREAD

**Issue by doctorallen** [laravel/framework#9454]
I wasn't sure where to put this, as the lumen repo doesn't allow issues. When 5.1 was released, all documentation was updated with full text search, however the Lumen documentation was not. It might be good to update the site with that as well to keep it consistent throughout.

**Comment by GrahamCampbell** [comment]
Lumen's docs are small enough you can easily find things though?

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.
