### ISSUE TITLE
Unable to use Amazon SES when using IAM Roles for EC2 instances

### ISSUE THREAD

**Issue by cenob8** [laravel/framework#9458]
If you set up your EC2 instance to use an IAM role then you don't have to provide a key and secret to use certain AWS services such as SES. This will automatically be fetched by AWS using a meta data server.
However to use this method you should NOT provide the key and secret when instantiating the SesClient Object. In the Illuminate/Mail/TransportManager class the key and secret are always supplied, even if you leave them blank or set to null in config/services.php.
Now AWS returns an error "InvalidClientTokenId" if you leave the key & secret blank.

A check should be made below to only set the credentials array if it is supplied in the config

```
    /**
     * Create an instance of the Amazon SES Swift Transport driver.
     *
     * @return \Swift_SendmailTransport
     */
    protected function createSesDriver()
    {
        $config = $this->app['config']->get('services.ses', []);

        $config += [
            'version' => 'latest',
            'service' => 'email',
            'credentials' => [
                'key'    => $config['key'],
                'secret' => $config['secret'],
            ],
        ];

        unset($config['key'], $config['secret']);

        return new SesTransport(new SesClient($config));
    }

```

**Comment by cenob8** [comment]
Just noticed this is related to : https://github.com/laravel/framework/issues/9309

**Comment by aaronkaz** [comment]
in v5.1.19
the block is:
```
/**
     * Create an instance of the Amazon SES Swift Transport driver.
     *
     * @return \Swift_SendmailTransport
     */
    protected function createSesDriver()
    {
        $config = $this->app['config']->get('services.ses', []);

        $config += [
            'version' => 'latest', 'service' => 'email',
        ];

        if ($config['key'] && $config['secret']) {
            $config['credentials'] = Arr::only($config, ['key', 'secret']);
        }

        return new SesTransport(new SesClient($config));
    }
```
If a key and secret are not provided, an `'Undefined index: key'` exception is thrown.

**Comment by sebas-nicholls** [comment]
on v5.5.7

If key and secret are not provided an `Undefined index: key` Exception is thrown.

In TransportManager at line 93:

`
/**
     * Add the SES credentials to the configuration array.
     *
     * @param  array  $config
     * @return array
     */
    protected function addSesCredentials(array $config)
    {
        if ($config['key'] && $config['secret']) {
            $config['credentials'] = Arr::only($config, ['key', 'secret']);
        }

        return $config;
    }
`
