### ISSUE TITLE
phpunit not reading database config from .env.testing

### ISSUE THREAD

**Issue by jonjonw** [laravel/framework#9463]
When running unit tests, the .env.testing file is ignored and .env is read instead. It would be nice to be able to specify a different testing database in .env.testing. I believe this might be related to https://github.com/laravel/framework/issues/6096.

**Comment by crynobone** [comment]
You could use `phpunit.xml` php env configuration to add those config, such as https://github.com/laravel/laravel/blob/master/phpunit.xml#L22-L27

**Comment by jonjonw** [comment]
@crynobone Thanks for the work-around.

Still, shouldn't setting `APP_ENV` to `testing` in `phpunit.xml` be sufficient to make it read the database config from `.env.testing`?
https://github.com/laravel/laravel/blob/master/phpunit.xml#L23

**Comment by Sladewill** [comment]
It's not intended to use any other file than the .env setting it up via the phpunit.xml is the correct way.

**Comment by agostlg** [comment]
Hello, I'm having quite the same issue even using phpunit.xml to overwrite the env keys.

My phpunit.xml has this:

```
<php>
  <env name="DB_CONNECTION" value="test_mysql"/>
  <env name="APP_ENV" value="testing"/>
</php>
```

but when I execute phpunit explicitly passing the configuration file (or not) and print the env keys on my test class I get:
```
root@75de758b1491:/var/www/html# vendor/bin/phpunit --configuration phpunit.xml
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

<pre>/var/www/html/tests/Feature/BatchTest.php:16:
string(5) "mysql"
<pre>/var/www/html/tests/Feature/BatchTest.php:17:
string(5) "local"
```
mysql and local values are the ones set during build.

I'm running this inside a docker container.

**Comment by agostlg** [comment]
Ah, almost forgot DB_CONNECTION=test_mysql is pointing to this connection set on config/database.php

```
'connections' => [
        'test_mysql' => [
            'driver' => 'mysql',
            'host' => env('TEST_DB_HOST', 'db'),
            'database' => env('TEST_DB_DATABASE', 'test_sourcing'),
            'username' => env('TEST_DB_USERNAME', 'root'),
            'password' => env('TEST_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'db'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'sourcing'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
    ],
```

Thanks for the support in advance.
