### ISSUE TITLE
Laravel Installer

### ISSUE THREAD

**Issue by vluzrmos** [laravel/framework#9466]
Laravel installer is crafting the dev-master version instead of the latest stable published release (5.1.3).

**Comment by crynobone** [comment]
You're only getting the `dev-master` app skeleton, all the dependencies should resolved to stable 5.1.x released.

**Comment by vluzrmos** [comment]
I know about the dependencies...

**Comment by vluzrmos** [comment]
But I think it should be the stable version to the app skeleton.

**Comment by crynobone** [comment]
There no breaking changes in `dev-master` (because if anything it would be tagged as `5.1.x`, e.g `5.1.4` as next patch release), `5.2` changes goes to `develop` branch. 

Don't you want to get the latest code for 5.1, for example https://github.com/laravel/laravel/compare/v5.1.3...master

**Comment by vluzrmos** [comment]
Ok,
thanks for the explanation.
