### ISSUE TITLE
morphOne, polymorphism with namespace

### ISSUE THREAD

**Issue by rafgugi** [laravel/framework#9468]
I created two models: User and Student
```
User
  id 				# 1
  personable_id 	# 1
  personable_type 	# 'student'
  public function personable() {
    return $this->morphTo('personable');
  }
  public function getPersonableTypeAttribute($type) {
    $type = strtolower($type);
    return 'App\\'. str_replace(' ', '', ucwords($type));
  }

Student
  id 				# 1
  name 				# 'Mathew Jones'
  public function user() {
    return $this->morphOne('App\User', 'personable');
  }
```

I can get student from user by ``$user->personable``. But I ``$student->user`` returns null.. what I did wrong? what personable_type in user should filled by? I fill by 'App\Student'

**Comment by dwightwatson** [comment]
The `Student` doesn't morph to a `User`, it just belongs to one. The polymorphic relationship is one-way.

    public function user()
    {
        return $this->belongsTo('App\User');
    }

**Comment by rafgugi** [comment]
because i have another personable type like lecturer, staff, dll

**Comment by rafgugi** [comment]
I found the solution. simply add `protected $morphClass = "student"` in Student model. This fix the problem. but why?
