### ISSUE TITLE
[5.1] vendor:publish doesn't work without tag option

### ISSUE THREAD

**Issue by golonix** [laravel/framework#9469]
As in title, `vendor:publish` command doesn't work when you don't pass `--tag` option. However it is working when you just pass option, but no option value, i.e. `vendor:publish --tag`. 
I believe this is not how it should work. I understand tag option purpose, but command should not require from the user to give even an empty option just to publish all package configurations or assets, etc.

`fire()` method in `VendorPublishCommand` looks like this:
```
public function fire()
{
    foreach ($this->option('tag') as $tag) {
        $this->publishTag($tag);
    }
}
```

When no tag option is passed to the command, `$this->option('tag')` returns empty array. However, when tag option without any value is given, `$this->option('tag')` returns array with one element, where key is 0 and value is NULL.
This bug was introduced in d21ab3787709154dd65a34ffd9ea093fcd0d3c3e

**Comment by GrahamCampbell** [comment]
Works fine for me.

**Comment by GrahamCampbell** [comment]
Oh right. Err.

**Comment by GrahamCampbell** [comment]
Ping @lucasmichot, @taylorotwell.

**Comment by lucasmichot** [comment]
Indeed we cannot force the default value we want in the `$signature`.
https://github.com/laravel/framework/issues/9475 fixes that.
