### ISSUE TITLE
Negation of a validation rule

### ISSUE THREAD

**Issue by ghost** [laravel/framework#9471]
This follows a [previous proposal](https://github.com/laravel/framework/issues/3111).

Being able to negate validation rules would be helpful. For example, there is no rule for date "after or equal". Both `after` and `before` are strict and don't allow such validation.

Also, being able to specify parameters for the `after` or `before` rules for specifying accuracy (second, minute, day, month, or year level) would be nice.

**Comment by GrahamCampbell** [comment]
Closing since the user appears to have deleted their github account.
