### ISSUE TITLE
[Blade] Render single section from partial view

### ISSUE THREAD

**Issue by soee** [laravel/framework#9472]
Hi,

if we want to render some part of a partial view in a parent template, we can use condition by passing some variable from parent to partial or using @yield:

```Blade
@include('_partials.foo')
@yield('bar')
```

 Would it be possible to make it little simpler and just define what section from a parial view we want to include after partial path? Something like:

partial.blade.php:
```Blade
@section('foo')
    fancy content 1
@endsection

@section('bar')
    fancy content 1
@endsection
```

Than in main template.blade.php:

```Blade
@include('_partials/partial:@foo')
```

or

```Blade
@include('_partials/partial:bar')
```

This way we know directly to what partial our section refers.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.

**Comment by lukasgeiter** [comment]
Just create multiple blade files. One for each partial/section.

**Comment by soee** [comment]
Hi @lukasgeiter,
The main reason i proposed this solution was to avoid multiple blade files for small, and related part of code (for example where i only need different wrappers).
