### ISSUE TITLE
SoftDeletes::performDeleteOnModel doesn't take into account additional scopes

### ISSUE THREAD

**Issue by Anahkiasen** [laravel/framework#9479]
In the SoftDeletes trait the `performDeleteOnModel` method is overwrote to include trashed models:

```php
if ($this->forceDeleting) {
	return $this->withTrashed()->where($this->getKeyName(), $this->getKey())->forceDelete();
}
```

However this means any additional scopes are ignored and prevents the model from being truly deleted. Take the case of a `DraftScope` per example, for an Article model that is still unpublished, and which behaves the same as soft deletes (`withDrafts()` `onlyDrafts()` etc).

If I have an article that is still in draft, and call `->forceDelete()` on it, it won't actually delete anything as drafts won't be included in the new query used to perform the deletion.

Now I'm not sure as to whether this was done on purpose or not, one possible fix would be to replace `$this->withTrashed()` by `$this->newQueryWithoutScopes()` but I'm not sure if that was intended behavior or not so, thought I'd open an issue to discuss this.

**Comment by taijuten** [comment]
Also just ran into this bug. +1

**Comment by taylorotwell** [comment]
Can you make a PR with your suggested fix so we can review it?

**Comment by AadilC** [comment]
@taylorotwell I am currently overriding two methods directly on my model, The changes are included in this PR https://github.com/laravel/framework/pull/10086

It seems to work and be in-line with the expected behaviour, the tests might be somewhat lacking though. Perhaps you can review it and reopen the PR if it's correct.

**Comment by tcfw** [comment]
+1 after writing a global scope similar to the softDeletes. PR #10086 worked for me

**Comment by GrahamCampbell** [comment]
Fixed.
