### ISSUE TITLE
ErrorException when try to serialize a model with Illuminate\Queue\SerializesModels trait

### ISSUE THREAD

**Issue by AaronJan** [laravel/framework#9483]
Hi, all. 

I'm using `Laravel 5.1` on `PHP 5.6.7`.

I got `excepiton` like this: 

```
serialize(): &quot;snakeAttributes&quot; returned as member variable from __sleep() but does not exist
```

When I try to cache result of `User::all()` like this:

```php
$users = User::all();
dd(serialize($users));
```

Here is my `User` model:

```php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Queue\SerializesModels;

class User extends Model {

    use SerializesModels;

	protected $table = 'user';

    protected $fillable = ['name'];

    public $timestamps = false;

}

```

And migration:

```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

class CreateUserTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('user', function(Blueprint $table)
		{
            $table->increments('id');
            $table->string('name');
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
        Schema::drop('user');
	}

}

```

Am doing it wrong?

If I remove the `SerializesModels Trait`, it'll be OK.

**Comment by GrahamCampbell** [comment]
You can'y actually call "serialize". That won't work.

**Comment by GrahamCampbell** [comment]
The trait means laravel doesn't actually serialise your data on queue, but does something more clever.

**Comment by AaronJan** [comment]
Thanks for your reply!

So if I want to cache results, and this model hapends to use `SerializesModels` trait, what should I do?

**Comment by GrahamCampbell** [comment]
Ahh, you can't cache results like that. That won't work.You'd need to call toArray and then stick that into the cache. Also, don't call serialize before caching, laravel deals with all of that. This does mean you can't work with eloquent models at the other end though. Any futher questions, please ask on the forums.

**Comment by AaronJan** [comment]
Thank you very much @GrahamCampbell ! That's very helpful !

I'll be asking questions on the forums next time.

Cheers.
