### ISSUE TITLE
using Laravel version 5.0, Session not working as expected HELP!

### ISSUE THREAD

**Issue by msonowal** [laravel/framework#9484]
I have previously developed using laravel 4.2 then it was working fine.
but now this always gives or adds new value to the session variable
i.e. Session::has() always returns false.
Is it a bug if not please tell me how to use this in 5.0.

if(Session::has('ro_no')){
 return "there is data";
}else{
Session::put('ro_no', 12);
return "new data has been added";
}

//framework version updated to the latest 5.0
//using file driver in session config
//please help me I am in a middle of a risk

**Comment by msonowal** [comment]
sorry my mistale
I was calling var_dump() then exit(0)
so it was not calling those termantion middleware
now working on actual code

**Comment by lukasgeiter** [comment]
Then please close the issue, thanks.
