### ISSUE TITLE
Laravel installer isuue.

### ISSUE THREAD

**Issue by syokunin** [laravel/framework#9491]
When I used the laravel installer, I got a "phpunit: Permission denied".

### Via Laravel Installer

    $ laravel new project_by_installer
    $ cd project_by_installer
    $ phpunit
    -bash: ./vendor/bin/phpunit: Permission denied

    $ ls -l ./vendor/bin
    total 24
    -rw-r--r--  1 who  staff   750  7  1 23:48 phpspec
    -rw-r--r--  1 who  staff   930  7  1 23:48 phpunit
    -rw-r--r--  1 who  staff  3296  7  1 23:48 psysh

### Via Composer Create-Project

    $ composer create-project laravel/laravel --prefer-dist project_by_composer
    $ cd project_by_composer
    $ phpunit
    PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

    .

    Time: 198 ms, Memory: 13.75Mb

    OK (1 test, 2 assertions)

    $ ls -l ./vendor/bin
    total 24
    lrwxr-xr-x  1 who  staff  30  7  1 23:50 phpspec -> ../phpspec/phpspec/bin/phpspec
    lrwxr-xr-x  1 who  staff  26  7  1 23:50 phpunit -> ../phpunit/phpunit/phpunit
    lrwxr-xr-x  1 who  staff  22  7  1 23:50 psysh -> ../psy/psysh/bin/psysh

### Issue

latest.zip is incorrect.
http://cabinet.laravel.com/latest.zip

Maybe compression method is incorrect.
phpunit should be a symbolic link.

    // NG
    zip -r latest.zip latest_project

    // keep symbolic link
    zip -ry latest.zip latest_project
    tar zcvf latest.tar.zip latest_project

**Comment by willrowe** [comment]
I already reported this in issue #9051, but there was denial that it was even a bug, even though it clearly is.

**Comment by syokunin** [comment]
Installer will affect very many users. Contributors should take this issue more seriously.

**Comment by GrahamCampbell** [comment]
As documented in the contribution guidelines, it's up to the community to fix reported bugs.

**Comment by syokunin** [comment]
Why do you say that?
I don't understand.

This bug is not in the source code.
I can't pull request.
How can I fix this?

People who have the responsibility to archive file, should be re-released it.

**Comment by GrahamCampbell** [comment]
The installer is a public repo.

**Comment by syokunin** [comment]
What is public repo?
Where can I report this issue?

You are community too.
You have a power, knowledge and connections.
I need your help.

Regardless of whether public or private, Why don't you do that you can do now?
Because Installer will affect very many users, we need rapid response.
We need your help.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/installer

**Comment by GrahamCampbell** [comment]
All issues are to be reported on the framework repo though. Issues else where are disabled.

**Comment by franzliedke** [comment]
@syokunin Somebody sent [a fix](https://github.com/laravel/installer/commit/9297bff47777b77fd6afa4f48827890efb658fa3) for this kind of issue a while ago. Is this still a problem? May not be deployed yet...

**Comment by franzliedke** [comment]
Ah, it didn't seem to have the intended effect. Please comment on [this pull request](https://github.com/laravel/installer/pull/26).

**Comment by syokunin** [comment]
@franzliedke Thanks.
[This is it.](https://github.com/laravel/installer/pull/26)
