### ISSUE TITLE
Incorrect Route::resource generation

### ISSUE THREAD

**Issue by tobikris** [laravel/framework#9494]
As you can see in the following screenshot, there is one route name of a resource generated differently from the rest:
![Screenshot of artisan route:list](http://puu.sh/iJS15/a6b2c2d945.png)

The PATCH members/{members} route has a name of "dashboard2." - which is the "as" index of the route group the resource call is in.

I tried to create a PR myself, but couldn't understand the process of generating the routes.

**Comment by tobikris** [comment]
I guess that the problem was solved as I took another look through the files and routes.
The PUT and PATCH routes do the same and therefore just one needs to have a name...

**Comment by tobikris** [comment]
Except the thing, that the empty PATCH route name shouldn't be "prefixed" maybe?

**Comment by GrahamCampbell** [comment]
Nope. :)

**Comment by tobikris** [comment]
I can't extract, what you want to tell me :P Could you elaborate a bit?
