### ISSUE TITLE
Model@update() method updating all rows of table when is new record.

### ISSUE THREAD

**Issue by gokure** [laravel/framework#9495]
To sorry my poor English.

I using Laravel framework in my project and once change the new record
```
$product = new Product();
$product->fill($attributes)->save();
```
to 
```
$product = new Product();
$product->update($attributes);
```
and a big problem did.

**All rows of products table updated.**

This is my wrong way to make the problem, but the [Model@update()](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L1399) to updating all table when new record is dangerous.

**Comment by gokure** [comment]
I think Model@update() non-exists record should goes create or raise exceptions better.

**Comment by lukasgeiter** [comment]
I'm pretty sure the current behavior won't be changed...

The method specifically checks if the model does not exist and then runs the update of the whole table. So it is definitely intended:

    public function update(array $attributes = array())
	{
		if ( ! $this->exists)
		{
			return $this->newQuery()->update($attributes);
		}

		return $this->fill($attributes)->save();
	}

You are also able to call any query builder method on a model and it will run against the respective table.

**Comment by gokure** [comment]
That so sad, I knew the Rails `update()` method just alias of assign attributes and save (that would be create if record not exists).

The `update()` method keep literal means, but you made the hidden problem in Laravel.

I'll just notice my team *don't use `update()` method directly*.

**Comment by lukasgeiter** [comment]
Feel free to override the `update` method in a base model in your project.

**Comment by gokure** [comment]
Yes, I can override it, but it is hack, my point is implicit result of `update` method in Laravel framework.

**Comment by lukasgeiter** [comment]
It's not a hack. It's just a way to change the behavior of the method for your project(s) because I'm pretty sure that this won't be changed in the framework itself...

**Comment by gokure** [comment]
OK, what's the purpose of `update` method to updating all table? To punch the gay if he make mistake?

**Comment by overtrue** [comment]
我觉得，`update` 本身就意味着 “更新” 而不是 “如果不存在则创建”，如果写错就创建，那数据库里得多少垃圾信息（而我的目的只是更新）

试想，我现在的目的是：**给所有用户状态更新为某个值**，在5里我们的写法：

```php
function updateIntegration(User $user) {   // 框架会 new User()
    $user->update(['status' => xxx]);
}
```

但如果按您的意思改掉ORM后这句就插入新的记录或者抛异常？当然上面的这种需求可能举例不是太合适，但从代码角度来讲就应该是更新全表的意思，而不是“插入新的记录或者抛异常”。

**Comment by gokure** [comment]
The `update` is the Model level method, if you wants to update all records, you needs find and update them, or make `DB::table('users')->update(['status' => xxx])` instead.

I think the `update` method make two different things is bad, 

* To call method in the instance object should trigger callback.
* To call method in the static/class just delegate to Query Builder, should not trigger callback.

If we need this feature, we need implement some like `updateColumn` method (Ralis way) to do it.

**Comment by karona3it** [comment]
# Problem : Update and Insert multi record using laravel 5.4
