### ISSUE TITLE
\Request::ip() returns load balancer's IP

### ISSUE THREAD

**Issue by Binternet** [laravel/framework#9501]
When Laravel sits behind a load balancer, the `Request::ip()` returns the IP of the load balancer instead the IP of the client.

The Client IP should also return 'HTTP_X_FORWARDED_FOR'

**Comment by GrahamCampbell** [comment]
This is known and is intended.

**Comment by GrahamCampbell** [comment]
> The Client IP should also return 'HTTP_X_FORWARDED_FOR'

No it shouldn't. We can't trust that information.

**Comment by GrahamCampbell** [comment]
Check out https://github.com/fideloper/TrustedProxy.

**Comment by franzliedke** [comment]
Also, this: http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html

**Comment by Page-Carbajal** [comment]
@GrahamCampbell and @franzliedke thank you both for the links. I am running into the same snafu here and both links will solve my problems.

**Comment by badcom** [comment]
Did you guys manage to sort this out? I'm having a hard time getting this to work on Heroku.

I've configured the trustedproxy.php file, but no luck so far =/.

I can get the IP via $_SERVER['HTTP_X_FORWARDED_FOR'], but I obviously want to use Request::ip();

**Comment by badcom** [comment]
Nevermind. I've figured this out now.

**Comment by saeedvaziry** [comment]
@badcom How you solved this problem?

**Comment by Kyslik** [comment]
@saeedvaziry 

> Check out https://github.com/fideloper/TrustedProxy.
