### ISSUE TITLE
L5 "php artisan migrate --env=testing" not work as expected.

### ISSUE THREAD

**Issue by lokielse** [laravel/framework#9503]
When I run command `php artisan migrate --env=testing`, it shows `Nothing to migrate.`.

//The content of  file `.env` 
```
APP_ENV=local
APP_DEBUG=true
APP_KEY=1daerm3gPSoRJoQaDDRWeVwSRBaww0Ze

DB_HOST=localhost
DB_DATABASE=db_local
DB_USERNAME=my_user
DB_PASSWORD=my_password
```

Should I change `DB_DATABASE` value `db_local` to `db_testing` ... each time before I run the command `php artisan migrate --env=testing`? 

Is there any feature about L5's env config I don't know? 

What's the best practice to do with it?

**Comment by GrahamCampbell** [comment]
The env file does not define the environment to use.

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
