### ISSUE TITLE
Bug in Cache\FileStore will expire arbitrary Records

### ISSUE THREAD

**Issue by superdummy** [laravel/framework#9508]
Hello

in Illuminate\Cache\FileStore is mostlikely a Bug:

1.) If a Value is Put with Cache:forever the expiry Timestamp will internally be set to: 
if ($minutes === 0) return 9999999999;

2.) Now I Am Doing a Cache::increment!
 This internally will call put() with an incremented value that does set the new Timeout as follows:
$value = $this->expiration($minutes).serialize($value);
Minutes is the old value from above 99999999

3.)The $this->expiration($minutes)
 is defined as: return time() + ($minutes * 60);
 And will lead to a time that "rolls over! (like 9999999999*60 + Current Timestamp= will be something like 100000xxxxx
 
4.) BUG: When the Key is accessed in getPayload()
	$expire = substr($contents = $this->files->get($path), 0, 10);
	if (time() >= $expire)
	a Substring of 10(!! Bug?) Characters is cutted that then will be always be smaller than the current timestamp as of the current date: http://www.timestampgenerator.com/1435909496/
	(So this cutting leads to a 10 digit Timestamp like 10000xxxxxxx but misses the 11th or more digit that got constructed due to the default value of 9999999999...) Will always expire the cache.
	
=>Bug leads to arbitrary Deletion of Cached Data that should _not_ be expired! 

I have Laravel Version 5.0.33 installed

**Comment by shssoichiro** [comment]
I was unable to replicate this issue on 5.1.6. I've submitted a PR with a test for the issue (which passes on my machine).

**Comment by t2t2** [comment]
The test case ignores checking the file output (and even causes the bug to be ignored by feeding the correct file). Reproduced the bug: (Lumen 5.1.3, Illuminate/cache 5.1.8)

``` php
$app->get('/test', function (\Illuminate\Contracts\Cache\Factory $factory) {
	$cache = $factory->store('file');
	$cache->forever('test', 2);
	// Stored file: 9999999999i:2;
	$cache->increment('test');
	// Stored file: 10000000001i:3;
	// (actual value depends on the time)
	$value = $cache->get('test');
	// Stored file is deleted (expired)
	dump($value); // null
});
```

Did some extra testing using the formulas in filestore:

``` php
$expire = time() + 99; // okay, okay, officially only minutes are allowed
$time = ceil(($expire - time()) / 60); // $filestore->getPayload()['time']; used on get
$newexpires = time() + ($time * 60); // $filestore->expiration($time)); used on set
dump($expire, $time, $newexpires);
// 1440200665, 2.0, 1440200686.0
```

So every time FileStore->increments is used the expire time is reset so it lives 0 ~ 59 seconds longer, which for forever means:

``` php
$expire = 9999999999;
// same code as above, output:
// 9999999999 142663319.0 10000000019.0
```

@GrahamCampbell reopen?
