### ISSUE TITLE
pagging() not working since v 5.1.3

### ISSUE THREAD

**Issue by LPMadness** [laravel/framework#9509]
The pagging() functionality no longer works when called with 2nd parameter being an array of columns

```
return $this->model->paginate(25, ['id', 'body']);
```

This results in MySQL error

```
select count(`id`, `body`) as aggregate from `questions` where `questions`.`deleted_at` is null
```

The problem is located it Bulder.php class. and is caused by the runSelect() method call in which the toSQL() function returns the columns in the count section instead of count(*).

**Comment by GrahamCampbell** [comment]
Will be fixed in the next tag.
