### ISSUE TITLE
Big bug in throttling process

### ISSUE THREAD

**Issue by damiencriado** [laravel/framework#9512]
Hi,

I think I have found a bug in the throttling process. (I use REDIS for cache)
(trigger after 3 fails `if ($attempts > 3) {`)

#### 1st Attempt
*Time Elapsed : 0s*
**KEY :** login:attempts:xxx
**VALUE :** 1
**TTL :** 1min
#### 2nd Attempt
*Time Elapsed : 10s*
**KEY :** login:attempts:xxx
**VALUE :** 2
**TTL :** 50s
#### 3rd Attempt
*Time Elapsed : 20s*
**KEY :** login:attempts:xxx
**VALUE :** 3
**TTL :** 40s
#### 4th Attempt
*Time Elapsed : 30s*
**:no_entry: I’M IN JAIL Message say to try again in 1min because login:expiration TTL=60**
**KEY :** login:attempts:xxx
**VALUE :** 4
**TTL :** 30s

**KEY :** login:expiration:xxx
**TTL :** 1min
#### 5th Attempt
*Time Elapsed : 40s*
**:no_entry: I’M IN JAIL Message say to try again in 50s because login:expiration TTL=50**
**KEY :** login:attempts:xxx
**VALUE :** 4
**TTL :** 20s

**KEY :** login:expiration:xxx
**TTL :** 50s
#### 6th Attempt
*Time Elapsed : 50s*
**:no_entry: I’M IN JAIL Message say to try again in 40s because login:expiration TTL=40**
**KEY :** login:attempts:xxx
**VALUE :** 4
**TTL :** 10s

**KEY :** login:expiration:xxx
**TTL :** 40s
#### 7th Attempt
*Time Elapsed : 60s*
**:warning: NOT IN JAIL**
**KEY :** login:attempts:xxx
**VALUE :** 1
**TTL :** EXPIRED SO -> 1min

**KEY :** login:expiration:xxx
**TTL :** 30s
#### 8th Attempt
*Time Elapsed : 1m10s*
**:warning: NOT IN JAIL**
**KEY :** login:attempts:xxx
**VALUE :** 2
**TTL :** 50s

**KEY :** login:expiration:xxx
**TTL :** 20s

The expiration need to start when I'm in jail and not when the first attempt occured.
In `incrementLoginAttempts` a login:attempts:xxx key is created if no key exist on cache. Next the key is only incremented and the TTL has started to decrement after the first request.

**Comment by taylorotwell** [comment]
Fixed.
