### ISSUE TITLE
Event model serialization exclude relations from output

### ISSUE THREAD

**Issue by TeroBlaZe** [laravel/framework#9520]
I have noticed odd behavior around it.

When you fire an event and pass the model instance to it, eg:
$comment = Comment::with('user')->first();
event(new \App\Event\CommentCreated($comment));

if the event class uses SerializesModels trait, the output would be without relations, but if do not use trait it is ok. One more workaround I found is using lazy eager loading inside broadcastWith function of event class
    public function broadcastWith() {
        $this->comment->load('user');
        return ['comment' => $this->comment];
    }
Another more clean way is just to convert a model with relations to an array and pass it to event instead of model instance.

Is it a bug or "feature"? :)

**Comment by GrahamCampbell** [comment]
Intended.
