### ISSUE TITLE
Command and Handler issue

### ISSUE THREAD

**Issue by pandian05** [laravel/framework#9521]
I have created handler for the command but still it shows no handler registered issue. Please help me

I am using laravel 5.1.x

http://stackoverflow.com/questions/31208519/laravel-5-command-and-handler-issue

**Comment by GrahamCampbell** [comment]
You need to register the mappings. Take a look at the 5.0 branch of laravel/laravel. There is a bus service provider with some mapping code you can copy and paste out. :)
