### ISSUE TITLE
Non persistance Session

### ISSUE THREAD

**Issue by iLeoDo** [laravel/framework#9522]
I use file drive for session, but each new request will generate a new session file.

**Comment by ArjanSchouten** [comment]
Haven't seen this before. Probably you're nginx is configured the wrong way. Can you give more information? Is this on a fresh install? Is this on homestead? Is this in production?

**Comment by iLeoDo** [comment]
Problem solved.
caused by `@endsection` in the blade template,solved by changing to `@stop`.
maybe this should be mentioned in document.

**Comment by Hades1996** [comment]
It works like a charm, thanks

**Comment by fahmilatib** [comment]
@ileodo thanks, but mind to explain the logic behind that?

**Comment by ileodo** [comment]
@fahmilatib It seems like the @endsection is only a close tag of @section in terms of template but not the rendering stuff.

**Comment by jzhang917** [comment]
This works for me. But I still don't understand why. Could anyone please explain? Appreciate!

**Comment by devcircus** [comment]
Both tags compile identically, something else must be happening. 

![935EE41F-67D7-4F31-8B4F-9BE92BDB8238](https://user-images.githubusercontent.com/18542852/54844388-cbdb3880-4ca4-11e9-8f40-0986cea85a0f.jpeg)
