### ISSUE TITLE
How to change the laravel directories structure

### ISSUE THREAD

**Issue by foxmedo** [laravel/framework#9526]
hello all,

i want to use my own folders structure and i want also to use plugins system like october CMS how can we do this and what is the best packages for this

Structure Example

-core*** ====> new folder that regroup all below
--app
--bootstrap
--database
--composer.json
-config
-modules*** ====> folder that contait ( frontend / backend)
-plugins*** ====> folder that containt plugins
-storage
-themes
-vendor
-index.php
-.htaccess

waiting for your help

best regards

**Comment by GrahamCampbell** [comment]
Ask on the forums please.
