### ISSUE TITLE
Optional mapping of integers in the DB to class names for polymorphic relations

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#9530]
I'm working on a project that is likely to have its DB accessed outside of Laravel and PHP contexts.

For the sake of keeping the schema "clean", it might be nice if I could keep a mapping of integers to class names in Laravel instead of putting whole class names in the DB when doing polymorphic relations.

This also would have the added benefit of cutting down the amount of space needed to store rows that contain the references.

(FTR: In pure Laravel projects, this never bothers me much, but it would be nice to have the option.)

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
This is already achievable by overriding the morph class.

**Comment by atrauzzi** [comment]
:+1:
