### ISSUE TITLE
laravel csrf token mismatch exception after session timeout

### ISSUE THREAD

**Issue by shangsunset** [laravel/framework#9531]
in our laravel 5 app, the login is through ajax. if user logout and log back in before session expires, everything is fine. but if user logout and stay idle on that page until session is expired, user will get a `csrfTokenMismatch` exception if they attempt to log back in.

i know in `verifyCsrfToken` middleware, laravel checks if session matches with the csrf token. also in `Guard.php logout()` method, session will be cleared on logout. Ive been searching around but havent found a solution.

so my questions are:

is session really flushed on logout, if so how come user can still log back in before the session i set expires?

what happens to csrf token when session is expired?

and lastly, how is this issue usually handled in an elegant way?

Thanks in advance!

**Comment by TheShiftExchange** [comment]
The session is not "flushed" on logout - only the authenticated section of it.

This should really be asked on the forums.
