### ISSUE TITLE
[Proposal] Include MailHog in Homestead

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#9533]
I've recently switched away from MailCatcher (due to multiple issues with Ruby + Gems) - and found MailHog - https://github.com/mailhog/MailHog

Mailhog is an alternative for Mailcatcher that doesnt require any special dependencies like Ruby, so installation dead simple. Here is a quick article I found on it: http://iankent.uk/2014/04/20/introducing-go-mailhog/

Here is an example of bash installation script that would cover everything needed to include in Homestead: https://gist.github.com/varghesejacob/68caf7aeee53305a1ffa#file-mailhog-bash-script

MailHog includes hooks (like Mailcatcher) to use in PHPUnit Tests so you can 'test' your emails are been sent etc etc: https://gist.github.com/varghesejacob/6113ac971a00611015c5#file-mailhog-test-helper.

Obviously people could install this themselves - but it would seem to be a natural synergy with Homestead - providing everything 'out of the box'. Taylor has previously tweeted that perhaps MailCatcher should be in Homestead by default: https://twitter.com/taylorotwell/status/536923096213516288 - and it was highly "+1" from many replied tweets (including @JeffreyWay) - so this would potentially be a better 'drop in' replacement.

Obviously there is also MailTraip.io - but this is a local service - so is much faster/reliable etc etc.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by TheShiftExchange** [comment]
ping @taylorotwell 

Perhaps this could be considered for the next Homestead release (which I am assuming there will be a new one when PHP7 is released)?

**Comment by oidnus** [comment]
ping @taylorotwell +1

**Comment by GrahamCampbell** [comment]
Sorry, but we don't process proposal issues. Feel free to discuss on slack or whatever though.
