### ISSUE TITLE
Configuration folder overriding

### ISSUE THREAD

**Issue by Jamesking56** [laravel/framework#9536]
Hello,

Configuration folder overriding (a feature from Laravel 4) seems to have stopped working in Laravel 5.

I set `APP_ENV` to `pagoda` and created a directory in `config` directory called `pagoda` and added 2 config files `app.php` and `database.php`.

Even with `php artisan env` returning `pagoda`, my configuration overrides were ignored (still using configs from `config/app.php`).

Any ideas why this feature has stopped working in Laravel 5.1?

**Comment by GrahamCampbell** [comment]
It's not supported out of the box. Please ask on the forums.

**Comment by GrahamCampbell** [comment]
Oh, you mean config folder for environments? We don't support that, no. You're meant to be using the environment file.
