### ISSUE TITLE
[5.1.6] migration can not add a column to table

### ISSUE THREAD

**Issue by index-panayotov** [laravel/framework#9550]
Hello,
 I have tones of migrations, one of all is 

upgrade : 
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UpdateCandidateAwardTable extends Migration
{
    protected static $table = 'candidate_award';
    
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table(self::$table, function (Blueprint $table) {
            $table->string('key', 32)->after('year');
        });
    }
	
	public function down(){
		
	}
}

and mail migration is 

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCandidateAwardTable extends Migration
{
    protected static $table = 'candidate_award';
    
    /**
     * Run the migrations.
     *
     * @return void
     */
    
    public function up()
    {
        Schema::create(self::$table, function (Blueprint $table) 
        {
            $table->increments('id');
            $table->integer('profile_id')
                    ->unsigned();
            $table->foreign('profile_id')
                    ->references('id')
                    ->on('candidate_profile');
            $table->string('title');
            $table->string('organization');
            $table->text('description')
                    ->nullable();
            $table->string('year');
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    
    public function down()
    {
        Schema::drop(self::$table);
    }
}

And I'm getting this error 
![screenshot_1](https://cloud.githubusercontent.com/assets/5002951/8545697/aec0bef8-24b9-11e5-8f4f-14bdc7ef68f3.png)

**Comment by GrahamCampbell** [comment]
Ask on the forums please.

**Comment by index-panayotov** [comment]
Hello, GrahamCampbell, 
I really don't think this is for the forum :
1) It's releated with artisan migrate
2) I can add column from everywhere but not from migration.
3) my college has  same problem. 


But Okay, I will ask in the forum too :)

**Comment by GrahamCampbell** [comment]
This is definitely an issue with your code. The column must already exist.

**Comment by GrahamCampbell** [comment]
You're calling the table method twice, thus creating it twice...

**Comment by GrahamCampbell** [comment]
You need to `create` the first time then `table` the next.

**Comment by index-panayotov** [comment]
its first `create`, after that is `table`!  I just paste my code in wrong possition. YES ! This is my bad.

**Comment by brunogaspar** [comment]
The error states that a table already exists not a column.

**Comment by index-panayotov** [comment]
In laravel documentation ( http://laravel.com/docs/5.1/migrations#creating-columns )
I think i must have a table , before edit it ? Am I wrong?

**Comment by brunogaspar** [comment]
> I think i must have a table , before edit it ? Am I wrong?

No, you're not wrong, but the error you pasted, doesn't state anything like that!

The error you have on that screenshot states this:

> General error: 1 table "candidate_profile" already exists

Which means you're creating the table `candidate_profile`, twice, therefore you receive that error, which is expected.

This is not a bug of Laravel, it's a bug on your own migrations.

**Comment by index-panayotov** [comment]
Okay :) Thanks :)
