### ISSUE TITLE
Regex validator throws exception if input isn't scalar

### ISSUE THREAD

**Issue by curtisdf** [laravel/framework#9554]
The `regex` validator (and probably others) throws an exception if the input is not scalar.  Preceding the `regex` validation with a validation on the primitive data type (e.g. `string`) does not help since Laravel's validator runs all validations on a given field even if previous ones have failed. 
This is with Laravel 5.1.1.  Example:

```
$data = ['foo' => ['La la la']];
$rules = ['foo' => 'string|regex:/.*/'];
$validator = Validator::make($data, $rules);
$failed = $validator->fails();
```

Rather than returning a boolean, $validator->fails() throws an exception in this case:

```
ErrorException: preg_match() expects parameter 2 to be string, array given in 
{redacted}/vendor/illuminate/validation/Validator.php on line 1310
```

I would submit a pull request as the docs suggest, but I don't know what behavior is desired here.  Should the regex validator first check if the input is a string, and return false if not?  Personally, I would like to see the validator stop executing any subsequent validations on a field as soon as one of them fails, or at least for this to be a configurable option.  But it appears to be a firm design decision to run all validations no matter what.

Also, what about the other validators? I have not tested them, but I presume others are in a similar boat.

**Comment by Anahkiasen** [comment]
I think thats desired behavior, if your input fails multiple rules you want to know all of them at once instead of having to resubmit the form again and again until you get to the last validation rule

**Comment by curtisdf** [comment]
Ok.  So are you saying that the proper solution to avoid throwing those exceptions would be to make all validators gracefully fail if they are expecting scalar input but are given an array instead?

**Comment by Arrilot** [comment]
All kinds of `regex` validators should probably return `false` for non-string input instead of throwing random php exceptions.

**Comment by Arrilot** [comment]
Okay. In fact the validation for 
`$data = ['foo' => ['La la la']];`
`$rules = ['foo' => 'string|regex:/.*/'];` 
goes well except the fact that `preg_match` raises an uncatchable warning in addition to returning false. With some php settings that can be annoying.

@GrahamCampbell Do you think this warning needs to be suppressed or should we leave it as it is?

**Comment by GrahamCampbell** [comment]
Not sure. Ping @taylorotwell.

**Comment by curtisdf** [comment]
@Arrilot  - I'm getting unhandled exceptions, not just warnings.  Regex validation is unusable for me in this state, so it definitely can't be left as-is.  I don't know which PHP settings you're referring to, but I've got a very out-of-the-box Laravel 5.1 deployment on a very out-of-the-box OSX/Homebrew PHP 5.6 setup.  In Production, this codebase will run on a very out-of-the-box modern Ubuntu or CentOS rig.

Validators should never throw unhandled exceptions.  The whole point of validation is taking whatever crazy input the user might come up with and gracefully spitting out a boolean indicating whether or not the input passed the test.

**Comment by Arrilot** [comment]
@curtisdf I'll do a PR soon. Not a big deal

**Comment by GrahamCampbell** [comment]
Thank you @curtisdf. :)

**Comment by curtisdf** [comment]
Thanks everyone! :+1:

**Comment by Arrilot** [comment]
@GrahamCampbell This can be closed
