### ISSUE TITLE
if use default queue listener always throw exceptions

### ISSUE THREAD

**Issue by jason-chang** [laravel/framework#9555]
commnd: 
      php artisan queue:listen

exception:

       [ErrorException]
       Undefined index: job

    [2015-07-08 00:01:17] local.ERROR: exception 'ErrorException' with message 'Undefined index: job' in /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:125
Stack trace:
    #0 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(125): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/mnt/hgfs/web/i...', 125, Array)
    #1 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
    #2 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(202): Illuminate\Queue\Jobs\RedisJob->fire()
    #3 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '0', '0')
    #4 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop(NULL, 'default', '0', '3', '0')
    #5 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'default', '0', '128', false)
    #6 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
    #7 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
    #8 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Console/Command.php(149): Illuminate\Container\Container->call(Array)
    #9 /mnt/hgfs/web/icd/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #10 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Console/Command.php(135): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #11 /mnt/hgfs/web/icd/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #12 /mnt/hgfs/web/icd/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 /mnt/hgfs/web/icd/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #14 /mnt/hgfs/web/icd/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(98): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #15 /mnt/hgfs/web/icd/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #16 {main}

**Comment by GrahamCampbell** [comment]
Probably due to a conflict with your cache.

**Comment by GrahamCampbell** [comment]
You need to connect to a different redis database.

**Comment by jason-chang** [comment]
redis-cli 
127.0.0.1:6379> KEYS *
1) "queues:default:delayed"
127.0.0.1:6379> 

and Mailer:queue() can send a email

sorry my english is so bad.

**Comment by GrahamCampbell** [comment]
You're probably best asking on the forums.

**Comment by jason-chang** [comment]
GrahamCampbell  thank you.

i'll ask this on StackOverflow.
and is there a better forum? what is it.

and if i try to debug this how do i start? xdebug?

thanks

**Comment by cabloo** [comment]
For other people who come across this problem: I had the same issue after I forgot to add the 'Illuminate\Queue\SerializesModels' to a Job/Command class. Earlier in the Job/Command pipeline, the `json_encode` function doesn't know how to serialize Jobs that have models without that function, so `json_encode` on the array containing the job returns false.

**Comment by slothentic** [comment]
If you have a job class that does not use `implements ShouldQueue` it will return this error
