### ISSUE TITLE
Inconsistent relation dynamic properties

### ISSUE THREAD

**Issue by meetraz** [laravel/framework#9559]
On the model, __isset() returns false for dynamic properties before they are accessed.  For example:

```php
isset($book->author);  // false
$author = $book->author;
isset($book->author);  // now true
```

This is internally inconsistent, since the Model __isset() returns true for properties that do not exist, but have a GetMutator.  It should also return true for properties that do not exist "yet" but have a matching relationship accessor.

This is currently a big problem for us, since Twig will error on statements like ` {{ book.author.name }} ` because it checks if "author" is a property before accessing it, and it's not.   This pretty much makes Twig unusable with Laravel unless you fill up your controllers with dummy statements to vivify any relationship properties your view might need.

**Comment by lukasgeiter** [comment]
As a workaround you could eager load your relationships. Like: `$book = Book::with('author')->find(1);`
