### ISSUE TITLE
SqsJob can be more flexable.

### ISSUE THREAD

**Issue by andizzle** [laravel/framework#9560]
AWS has worker instances that runs sqsd, which listen to the queue and POST the job to laravel route.

In the payload there's no Receipt Handle, so we can't really create the SqsJob and fire it, since the Events\CallQueuedHandler tries to delete the job after call it, and delete a SqsJob relies on Receipt Handle.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Queue/Jobs/SqsJob.php#L74

Should we double check if the job has ReceiptHandle then call the deleteMessage()?

Thanks.

**Comment by GrahamCampbell** [comment]
We're open to PRs. ;)
