### ISSUE TITLE
[5.3] Closure vs callable

### ISSUE THREAD

**Issue by shehi** [laravel/framework#9565]
Hey good folks,

I have a question, related to a design problem I stumbled upon today while developing some nice code with Laravel:

Why don't we use ```callable``` type-hint instead of ```\Closure``` wherever applicable? The former covers the latter, whereas the other way around isn't valid. Example code:

```
Router::group($someOptionsHere, [$this, 'myCallbackMethod']);
```

won't work with Laravel's current signatures. However if one changed these sigs, let's say for the ```group()``` method above FROM 

```public function group(array $attributes, \Closure $callback)``` 

TO

 ```public function group(array $attributes, callable $callback)```

everything would be honkie dorie. We could use both Closures and regular callables. Additionally, let me note that ```callable``` type-hinting has been introduced in PHP 5.4, so we are covered. As you can see there are no BC implications involved as well.

Thoughts?

CC: @taylorotwell , @GrahamCampbell

**Comment by shehi** [comment]
If "the Gods of Copybook Headings" are interested, I can start working on this one by the way :)

**Comment by Anahkiasen** [comment]
:+1: for this, bumped into this so many times

**Comment by lukasgeiter** [comment]
There is definitely a BC break, since the signature of an overriding method has to match exactly.

**Comment by shehi** [comment]
Of course, but its a framework method, both the interface and its implementation lie inside framework. Do you mean someone would be bold enough to override, let's say, Router class and rewrite it from scratch? :) If not, we can limit these changes to such implementations and their respective interfaces.

**Comment by franzliedke** [comment]
:+1: We definitely talked about this back when we created `Closure` typehints all over the place.

Backwards compatibility definitely is an issue, though.

**Comment by Anahkiasen** [comment]
Related issue is the fake callables in Laravel, ie. `Foo@bar` instead of PHP's standard callable notation which is `Foo::bar`

**Comment by shehi** [comment]
Can you elaborate @Anahkiasen : how can one pass anything fake that isn't a ```\Closure``` instance?

**Comment by lukasgeiter** [comment]
I'm pretty sure there are people that have overridden parts of the framework, created packages that implement framework contracts/interfaces etc.
In the end it doesn't really matter if someone actually did do so, but just the fact that there's a possibility of breaking someones code. I don't see this as huge issue though. The changes would just have to be targeted at 5.2.

**Comment by shehi** [comment]
@franzliedke : I am finding files like https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Arr.php with ```callable``` in their signatures and PRs related to them. Can you point me in right direction when ```\Closure``` hints were added please?

**Comment by shehi** [comment]
@lukasgeiter : Yea, I had the same initial idea, to make these changes for the next release.

**Comment by franzliedke** [comment]
@shehi Long ago, in the beginning times of Laravel 4.

**Comment by Anahkiasen** [comment]
@shehi What I meant is in a lot of places Laravel expects this notation `Foo@bar` (routes, view composers, etc.) which means you can't pass an actual callable like ù Foo::bar` or `[$foo, 'bar']` etc

**Comment by shehi** [comment]
@Anahkiasen : I know, but you don't have to. ```callable``` hint allows passing a ```\Closure``` instance. I said above, its compatible one way, not the other way around.

**Comment by shehi** [comment]
If at least we could do this for handful of methods, like Router implementation here - code looks so ugly when I wrap existing class method with a lambda function just to satisfy hint requirement. :(

**Comment by GrahamCampbell** [comment]
I think 5.2 is a good place to do this if we do given 5.1 is LTS and that 5.2 will be using symfony 3.0.

**Comment by GrahamCampbell** [comment]
We've already broken a few things in 5.2 already.

**Comment by GrahamCampbell** [comment]
I say broken - "removed". :)

**Comment by shehi** [comment]
Glad to hear this @GrahamCampbell . If @taylorotwell gives a go as well, I could start small PR and we could move bit by bit, carefully :)

**Comment by GrahamCampbell** [comment]
Yeh, it really is totally up to @taylorotwell. It ultimately doesn't matter what I say, lol.

**Comment by shehi** [comment]
Pinging @taylorotwell

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
I'm fine with moving non-breaking things to callable where possible.

**Comment by GrahamCampbell** [comment]
Would be good to get this sorted in 5.3.

**Comment by laravel-internals** [comment]
Sorry, we don't process requests/proposals here. Please see https://github.com/laravel/internals/issues.

**Comment by shehi** [comment]
Moved to laravel/internals#25, let's continue there.
