### ISSUE TITLE
.env files make it hard to set value to "true", "false", "empty" or "null" string

### ISSUE THREAD

**Issue by powelski** [laravel/framework#9566]
.env files are automatically processed in the way, where this kind of assignment is automatically casted to appropriate value type:
~~~
MY_VAR=true
~~~
In this case, `MY_VAR` will be intrepreted by `env()` function as boolean `true`. In the same way, `false` will become boolean `false`, `empty` will become empty string and `null` will become `null`.

Additionally, surrounding single and double quotes are being stripped, so `'cat'` becomes `cat`. This feature could be used to provide one of those special values as regular string, so for example 4-letters string `true`.

Currently, this will become boolean true:
~~~
MY_VAR='true'
~~~

The only way I found to make a value be `true` string is:
~~~
MY_VAR='"true"'
~~~

That is: single quote, double-quote, true, double quote, single quote. Not very convenient.

**Comment by ArjanSchouten** [comment]
To me it seems a bit strange to pass ```true``` as a string. Why should you use that? .env files only contains some basic, environment dependent configuration! Don't think you've to use this and it's probably not the problem of Laravel.

**Comment by powelski** [comment]
I don't want to pass `true` as a string, but somebody may want to call anything `true`, `false`, `empty` or `null`. I think that behavior of single and double quotes is not intuitive, they should always end up as a string.

**Comment by GrahamCampbell** [comment]
Things have changed in the 2.0 release of phpdotenv. We will eventually be upgrading to it I hope. Nothing else we can really do here, sorry.
