### ISSUE TITLE
Laravel TestCase not sending Authorization headers

### ISSUE THREAD

**Issue by gvhuyssteen** [laravel/framework#9570]
Duplicate of issue on StackOverflow.

http://stackoverflow.com/questions/31309098/laravel-testcase-not-sending-authorization-headers-jwt-token

**Summary**

We are writing unit tests to test the creation and invalidation of JWT tokens and receiving a "The token could not be parsed from the request" error back from a JWTException every time we try to JWTAuth::invalidate the token.

**Description**

Inside our controller, to create a user token, we are passing through the user email address and then returning the JWT token.

Afterwards, we are destroying the token by invalidating it using invalidateToken method and passing through the token by sending an Authorization header.

```
public function invalidateToken()
{
    try {
        JWTAuth::invalidate(JWTAuth::getToken());
        return Response::json(['status' => 'success'], 200);
    } catch (JWTException $e) {
        return Response::json(['status' => 'error', 'message' => $e->getMessage()], 401);
    }
}
```
This works perfectly by using Postman as well as PHPStorms Restful client.

When we try to write a test for this method, we are faced with an error response and a "The token could not be parsed from the request" error message.

Our test is as follow:

```
public function testInvalidateToken()
{
    $createUserToken = $this->call('POST', '/token/create', ['email' => 'test@test.com']);
    $user = $this->parseJson($createUserToken);

    $response = $this->call('POST', '/token/invalidate',
        [/* params */], [/* cookies */], [/* files */], ['HTTP_Authorization' => 'Bearer '.$user->token]);

    // var_dump($user->token);
    // die();

    $data = $this->parseJson($response);
    $this->assertEquals($data->status, 'success');
    $this->assertEquals($data->status, '200');
}
```
We are using Laravel 5.1 (which has the cookies as a parameter before the server parameter)

PHP version 5.6.10

PHPUnit 3.7.28

**Comment by GrahamCampbell** [comment]
Only phpunit 4.7+ is supported. Also, please ask on the forums.

**Comment by gvhuyssteen** [comment]
Hi Graham.

I have updated to PHPUnit 4.7.6 

The test is still failing with 'The token could not be parsed from the request'

I do not believe this is a phpunit version fault.

$this->call()  is not sending the Authorization header through when overwriting the $server parameter.

**Comment by GrahamCampbell** [comment]
is that because you're running with middlewares turned off?

**Comment by GrahamCampbell** [comment]
Which version of 5.1? We recently made a fix related to this.

**Comment by gvhuyssteen** [comment]
Middleware is not turned off.

There is middleware running though: 
```
$this->middleware('jwt.auth', ['only' => ['invalidate']]);
``

I'm running the following version:
VERSION = '5.1.6 (LTS)'

**Comment by GrahamCampbell** [comment]
You're still best asking on the fourms, sorry.

**Comment by gvhuyssteen** [comment]
Alright. Thank you.

**Comment by gvhuyssteen** [comment]
HI Graham,

I'm not receiving any responses from Laracast Discussion Board nor StackOverflow.

Are you sure this is not a Laravel Framework issue?

I see that between Laravel 4 and Laravel 5, there have been changes to the TestCase call method.

**Comment by ghprod** [comment]
@gvhuyssteen try this.. its works for me ... 

https://github.com/dingo/api/issues/476#issuecomment-116172393
