### ISSUE TITLE
./artisan make:listener generate listener with "use Footgoll\Events\;"

### ISSUE THREAD

**Issue by nardev** [laravel/framework#9576]
I tried to generate only a Listener and in header of file there was

namespace App\Listeners;

use Footgoll\Events\;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

Obviously there is a mistake: use Footgoll\Events\;

p.s. i needed a listener in order to make "Event Subscriber" to listen few events and trigger only one listener.

**Comment by Arrilot** [comment]
Please provide the full artisan command and Laravel version

**Comment by nardev** [comment]
Laravel 5.1.6

usual ./artisan make:listener ClassName

**Comment by GrahamCampbell** [comment]
Closing this as discussion can continue on the PR. Thanks guys. :)
