### ISSUE TITLE
Unused param $domain in translation helpers/methods

### ISSUE THREAD

**Issue by kamui545** [laravel/framework#9584]
Hey guys,

The $domain param in the following functions/methods is not used:

Illuminate/Foundation/helpers.php
- [trans($id = null, $parameters = [], $domain = 'messages', $locale = null)] (https://github.com/laravel/framework/blob/v5.1.6/src/Illuminate/Foundation/helpers.php#L546,L562)
- [trans_choice($id, $number, array $parameters = [], $domain = 'messages', $locale = null)] (https://github.com/laravel/framework/blob/v5.1.6/src/Illuminate/Foundation/helpers.php#L566,L579)

Illuminate/Translation/Translator.php
- [trans($id, array $parameters = [], $domain = 'messages', $locale = null)] (https://github.com/laravel/framework/blob/v5.1.6/src/Illuminate/Translation/Translator.php#L173,L185)
- [transChoice($id, $number, array $parameters = [], $domain = 'messages', $locale = null)] (https://github.com/laravel/framework/blob/v5.1.6/src/Illuminate/Translation/Translator.php#L187,L200)

As per the doc, domains are declared in the key name like this `trans('domain.message_key')`

In Translator@trans() we can clearly see this param is not used

```php
public function trans($id, array $parameters = [], $domain = 'messages', $locale = null)
{
    return $this->get($id, $parameters, $locale);
}
```

Now, the thing is, this param is needed in the Translator class because it implements the `Symfony\Component\Translation\TranslatorInterface`.

Maybe we could at least modify the trans() and trans_choice() helpers like this:

```php
function trans($id = null, $parameters = [], $locale = null)
{
    if (is_null($id)) {
        return app('translator');
    }

    return app('translator')->trans($id, $parameters, null, $locale);
}

function trans_choice($id, $number, array $parameters = [], $locale = null)
{
    return app('translator')->transChoice($id, $number, $parameters, $locale);
}
```
but it would still be confusing for people dealing with the translator class directly.

Any thoughts?

**Comment by GrahamCampbell** [comment]
We can't remove that param as that would be a breaking chanage, sorry.

**Comment by kamui545** [comment]
Yep I know, but isn't it possible to do this change for 5.2?

**Comment by GrahamCampbell** [comment]
Please send a PR then. Proposal issues aren't much use to us, sorry.
