### ISSUE TITLE
Console Commands called from code with array argument/option cause error

### ISSUE THREAD

**Issue by CupOfTea696** [laravel/framework#9586]
Hi,

I just noticed that Console Commands with arguments or options that need an Array as input cause an error when you give a string as argument. I think the option --tag on the VendorPublishCommand used to be a string so that's how I noticed this. 

However, I would expect that somewhere along the line arguments or options that require an array would cast strings to arrays, or at least validate the input and show an error accordingly. This currently does not happen, and just passes the argument/option as a string to the command, which, in case of the VendorPublishCommand, causes a string to be used in the foreach loop rather than an Array.

It took me a while to figure out why this error was happening so I thought I'd point it out (the command below used to work in 5.0).

My code:
```php
$this->call('vendor:publish', ['--provider' => TwoStreamServiceProvider::class, '--tag' => 'required']);
```

Log:
```log
[2015-07-10 18:23:44] local.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /home/vagrant/projects/Stribe/vendor/laravel/framework/src/Illuminate/Foundation/Console/VendorPublishCommand.php:61
```

**Comment by yoramdelangen** [comment]
Your problem could be solved easily when using the call method. 

```
$this->call('vendor:publish', ['--tag', => ['resources', 'public']]);
```

But i created an easy fix for the command-line to do `--tag=required,public,resources`

**Comment by CupOfTea696** [comment]
@yoramdelangen I know that, it's just that if you don't do that the error should be better handled or avoided. Also, the fix you created only fixes this for that specific command, and it should be fixed for all ArrayInput.

**Comment by CupOfTea696** [comment]
@taylorotwell @GrahamCampbell I'm not sure why this issue has been closed already. I wasn't trying to point out my individual issue, but rather a larger issue with all commands using either `InputArgument::IS_ARRAY` or `InputOption::VALUE_IS_ARRAY`.

If those Commands are called from PHP code rather than CLI, and the array parameter is a string (similar to how in the CLI you would do `--tag=config`) you get an error on the Command's foreachloop because it is passed to the Command as a string, rather than an Array. 

If you guys don't plan on casting those strings to Arrays in the Command class, there should at least be a validation that checks if the input was indeed an array, that throws an Exception if that isn't the case. 

I hope I am more clear now, and that you consider re-opening this issue.

**Comment by GrahamCampbell** [comment]
Wasn't this fixed with a PR already?

**Comment by CupOfTea696** [comment]
Not that I can see, unless it's not on the 5.1 branch?

**Comment by yoramdelangen** [comment]
@CupOfTea696 you proved my point, didnt made my self clear i guess. I created a fix for it perhaps it is solved but not merged yet?

**Comment by CupOfTea696** [comment]
@yoramdelangen your fix only fixes the specific VendorPublishCommand, whilst this is a problem that should be solved within the general Command classes. A Command expecting an array shouldn't receive a string.
