### ISSUE TITLE
Collection where and HHVM

### ISSUE THREAD

**Issue by justutiz** [laravel/framework#9587]
when running on hhvm $collection->where('id', '2') works, but without hhvm $collection->where('id', '2') returns zero results.

when running without hhvm $collection->where('id', '2') returns zero results and $collection->where('id', 2) works fine. 

It's very dificult to work, when you have homestead with hhvm in your development and have porduction server without hhvm.

**Comment by GrahamCampbell** [comment]
Please contact HHVM.

**Comment by justutiz** [comment]
This is Laravel isue. Laravel didnt recognize integer vs string when filtering collection.

**Comment by GrahamCampbell** [comment]
It's a bug in HHVM if this works on PHP but not on HHVM.
