### ISSUE TITLE
Variable output in Blade comment causes connection_reset on Windows [fix]

### ISSUE THREAD

**Issue by borys-p** [laravel/framework#9588]
Hi,

You probably don't track closed tickets and my comment to #7905 got lost.

There's probably a bug in regex parser on Windows. But in this case we can use modifiers to get the same result with much simpler expression:

```
// Illuminate/View/Compilers/BladeCompiler.php:199
$pattern = sprintf('/%s--(.*)--%s/Ums', $this->contentTags[0], $this->contentTags[1]);
```

**Comment by ptsilva** [comment]
I think  is not a bug, but your ini_get('pcre.recursion_limit') is a low value. Then ``preg_replace()`` return ``null``. Causing output break.

**Comment by borys-p** [comment]
@ptsilva: I have it set at 100000, so it's not this case.
@GrahamCampbell: it's not yet resolved.

**Comment by ptsilva** [comment]
try change your ```pcre.backtrack_limit``` also

**Comment by GrahamCampbell** [comment]
I've closed in order to take it of our todo list. You're of course free to continue the discussion on a closed issue.

**Comment by GrahamCampbell** [comment]
> There's probably a bug in regex parser on Windows.

I use windows and everything works fine for me, so it is likely to be a configuration issue.

**Comment by borys-p** [comment]
@ptsilva: pcre.backtrack_limit	= 1000000

@GrahamCampbell: oh, OK :)
Could you please paste somewhere your phpinfo()? I'll try to compare with mine for any suspicious values.

**Comment by borys-p** [comment]
More info about my config:
PCRE Library Version 	8.36 2014-09-26 
PHP Version 5.6.10
Build Date 	Jun 10 2015 15:53:40
Compiler 	MSVC11 (Visual C++ 2012)
Architecture 	x86

**Comment by ptsilva** [comment]
Here also occured this issue, i fix changing those  ```pcre``` config.

**Comment by borys-p** [comment]
@ptsilva: and what are your current values? I think 1000000 and 100000 is quite a lot...

**Comment by ptsilva** [comment]
Try ```preg_last_error``` to find the error.. I opened a issue #9252, check  commit and test if solve..

**Comment by ptsilva** [comment]
Ops.. PR.

**Comment by GrahamCampbell** [comment]
Looks like it was closed because you messed with all of the phpdoc.

**Comment by borys-p** [comment]
@ptsilva: PHP crashes on preg_replace(), I can't put anything after it.

But I kept digging. And I think that I've found the root cause: Apache MPM module on WinNT. With the default settings it can crash when PHP allocates a lot of stack.

The fix:

```
<IfModule mpm_winnt_module>
ThreadStackSize 8000000
</IfModule>
```

But I have never encountered this error before Laravel and Blade. Why not change the regexp to keep the stack size lower? I believe using the pattern modifiers does exactly that.

**Comment by borys-p** [comment]
Nope, there it is back again on my second computer with Win7 64-bit and PHP 5.5.17. Changing ThreadStackSize in Apache 2.4 doesn't help. PCRE settings are also 1000000 and 100000. httpd.exe crashes because of php5ts.dll, no other module is messing with the stack.

@GrahamCampbell: why you don't want to change this regular expression? Do you want a pull request and passed tests?

**Comment by GrahamCampbell** [comment]
@borys-p Not up to me. Ask @taylorotwell please.

**Comment by borys-p** [comment]
@GrahamCampbell: sure, thanks!

@taylorotwell: could you please take a look at this?

**Comment by themightystephen** [comment]
I've encountered this same issue today using WAMP on my Windows machine with a Laravel 4 set up (though from reading https://github.com/laravel/framework/issues/7905 it looks like it affects L5 too). It seems to affect Blade comments which are quite long, whether or not they are single or multi-line.

I tried @borys-p fix suggested at the top of this issue and can confirm his fix has resolved the issue for me as well. (The other workaround is to remove long comments, which isn't ideal).

I tried @ptsilva suggestion to increase the pcre.backtrack_limit and pcre.recursion_limit PHP config vars but even when set very high I didn't have any success with these (both set to 4000000).

NOTE: when (informally) testing this issue you have to be careful that a previously cached/pre-compiled version of the page isn't being loaded up, making you think it's working when it may actually not be.

**Comment by isometriq** [comment]
I'm trying to comment a big chunk of code with blade comments and after 8200+ chars, I get an internal error 500.

The problem did not appear in local env (with php artisan serve).
I'm on laravel 5.1

Apache error log shows: "End of script output before headers: index.php"

I'm not sure if blade comments are designed to handle multiline content... but I guess something is still wrong. According to previous comments, maybe it's related to preg limits being different on the my production server.

note that i can always use reliably this:
<?php /* ... */ ?>

but the problem is that it surprised me during deployment.
blade comments limitations should be indicated in the documentation!

**Comment by isometriq** [comment]
Darn, again having this problem.. is there any way to show some exception or error message, at least?
A blank page with "connection reset" error is irrelevant
