### ISSUE TITLE
Homestead does not work on VirtualBox 5

### ISSUE THREAD

**Issue by taai** [laravel/framework#9594]
Recently a *VirtualBox 5* was released. I installed it. I had to use newest *Vagrant 1.7.3*, because version 1.7.2 did told me that it will not work with any other *VirtualBox* versions except 4.x... By the way, I'm using Windows 8.1. When I was provisioning (```homestead up```) the *Homestead*, there was an error with something like this : "chmod ... ... /vagrant : not a directory ...". I did try many things, including trying to use older version of *Homestead* - 0.2.6 - instead of 0.2.7. Nothing worked, error was shown anyway. So I downgraded to *VirtualBox 4.3.30* and *Homestead* worked again.

**Comment by danwall** [comment]
Looks like this is to do with Vagrant / Virtualbox rather than Homestead.

https://github.com/mitchellh/vagrant/issues/5933
