### ISSUE TITLE
Illuminate\Support\Collection::contains() is always false when 2 parameters passed

### ISSUE THREAD

**Issue by powelski** [laravel/framework#9596]
Example:
```
$collection = collect([
    'a' => 1,
    'b' => 2,
    'c' => 3
]);

var_dump($collection->contains('a', 1)); // Outputs boolean false
```

This is where the problem origins: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Collection.php#L76-L78

**Comment by GrahamCampbell** [comment]
That the expected behaviour, because we are only searching the values, not the keys,

**Comment by GrahamCampbell** [comment]
This for example will be true:
```
var_dump($collection->contains(2, 1))
```

**Comment by powelski** [comment]
Then I guess the API is wrong: http://laravel.com/api/5.1/Illuminate/Support/Collection.html#method_contains

**Comment by powelski** [comment]
Plus, your example returns `false` as well.

**Comment by powelski** [comment]
Seems like contains was supposed to work as I thought.

**Comment by GrahamCampbell** [comment]
Oh, right, you;re calling it wrong...

**Comment by GrahamCampbell** [comment]
You can't pass multiple paramaters like that, as show in the link you posted.

**Comment by GrahamCampbell** [comment]
Look at https://github.com/laravel/framework/blob/5.1/tests/Support/SupportCollectionTest.php#L599 for usage examples.

**Comment by powelski** [comment]
@GrahamCampbell Those examples are really helpful, thanks!

**Comment by powelski** [comment]
So it looks for the key => value pair, but within collection elements, not within the collection itself.

**Comment by GrahamCampbell** [comment]
Yeh, sorry, you confused me too. :)
