### ISSUE TITLE
AuthManager must make use of Guard interface.

### ISSUE THREAD

**Issue by ifeltsweet** [laravel/framework#9597]
I am making my own guard that implements `Illuminate\Contracts\Auth\Guard` interface just like the original `Illuminate\Auth\Guard` does. I'm doing it without extending the original due to strong reasons.

The problem occurs when `AuthManager` calls `callCustomCreator()` inside which it does:

    if ($custom instanceof Guard) {
        return $custom;
    }

Since I did not extend original `Guard`, this will fail. So instead, `instanceof` should be done to `Illuminate\Contracts\Auth\Guard` to make sure my `$custom` is an instance implementing `Guard` interface.

**Comment by ibrasho** [comment]
Send a PR? :smile:
