### ISSUE TITLE
Query Builder where clause for enum

### ISSUE THREAD

**Issue by MrOutput** [laravel/framework#9599]
When querying an enum column in mysql, I have to query by string value instead of it's index integer value. I can run queries in my database searching for the index just fine. But it looks like laravel is looking only for its string value. Please add support for searching by an int in an enum column. 

`SELECT * FROM theshopper.advertisement where type = 2;`

`type` is enum...this returns results as expected.

`Advertisement::whereType(2);`

The latter does not return results.

Instead I have to do `Advertisement::whereType('STRING');`

**Comment by MrShibby** [comment]
The only way to use the enum index in a query is by using raw mysql.
[More informations here](http://stackoverflow.com/questions/3625569/pdo-cannot-compare-mysql-enum-using-integers-in-prepared-statements)

If you need this behaviour, you can use the whereRaw method:
whereRaw('type = 2')

Using simple where() will create bindings and won't work with enum indexes.
