### ISSUE TITLE
Query exists() method is inefficient

### ISSUE THREAD

**Issue by meetraz** [laravel/framework#9607]
If you attempt to check for a record's existence like this:

```php
$bool = MyModel::where('field','=','somevalue')->exists();
```

Laravel will execute a query like this:

```sql
select count(*) as aggregate from "my_models" where "my_models"."field" = 'somevalue' limit 1
```

On MySQL and Postgresql, the "limit 1" here is doing nothing, since a count is always returned as a single row.  The count(*) however is scanning the entire table and returning the true count of matching rows.  

Instead, the query executed should be something like this:

```sql
select 1 as exists from "my_models" where "my_models"."field" = 'somevalue' limit 1
```

This allows the database respect the "limit 1", stop searching and return immediately after the very first record is found, without actually counting all matching rows.  This is much, much faster than the query laravel uses.

**Comment by fonini** [comment]
+1
