### ISSUE TITLE
Add INSERT IGNORE support to Query Builder

### ISSUE THREAD

**Issue by gephaest** [laravel/framework#9612]
It would be very useful to have ability to use IGNORE statement like this
`DB::connection('foo')->table('bar')->insert($rows)->ignore();`

For additional details check MySQL docs: http://dev.mysql.com/doc/refman/5.6/en/insert.html

**Comment by ArjanSchouten** [comment]
Yes but is it supported by mssql, postgresql and sqlite?

**Comment by dtaub** [comment]
A quick google shows that [SQLite supports a somewhat similar construct](https://www.sqlite.org/lang_conflict.html) but for the other DBMS's you would need to either use `WHERE NOT EXISTS` or some form of exception catching. `WHERE NOT EXISTS ` would probably be the most cross-compatible way to go about it.

**Comment by gephaest** [comment]
`ignore()` can be alias to `WHERE NOT EXISTS`. Ignore looks clear and understandable.

**Comment by dtaub** [comment]
Also, you can't chain onto `insert()` since that method actually runs the statement, so it would have to be something more like:

`DB::connection('foo')->table('bar')->insertIgnore($rows);`

**Comment by GrahamCampbell** [comment]
You probably just want to use a raw query here.

**Comment by jfoliveira** [comment]
Using raw query is fine for inserting a single row/array.

However, as the `insert` function supports an array of multiple rows to be inserted at a time - `insert($multipleRows)` - it would be very convenient to have `INSERT IGNORE INTO` implemented in the `QueryBulider`.

**Comment by jfoliveira** [comment]
A good soul has published a package that can add this capability to a model: https://github.com/jdavidbakr/replaceable-model

**Comment by jbruni** [comment]
Here is what worked for me: https://stackoverflow.com/a/45151709/370290

**Comment by phpguru** [comment]
Because this very old issue is the #1 hit on google for _insert ignore query builder_... what works best for us is [firstOrCreate](https://laravel.com/docs/5.6/eloquent#other-creation-methods).

**Comment by mtrajano** [comment]
`firstOrCreate` is great if you only need to insert one row, but like someone else said the great thing about insert is that it lets you pass multiple rows at once, I still think a `insertIgnore` would be a good addition

**Comment by gpressutto5** [comment]
@phpguru `firstOrCreate` is for Eloquent. Query builder isn't the same as Eloquent.

**Comment by dunhamjared** [comment]
@GrahamCampbell Could we re-open this? Is there anyway we could vote on this feature? Judging from the responses on this issue, this feature would be very useful for many people who use databases that allow insert ignore.

**Comment by dunhamjared** [comment]
Found this great Laravel extension that adds support for INSERT & UPDATE (UPSERT) and INSERT IGNORE to the query builder and Eloquent: **[staudenmeir/laravel-upsert](https://github.com/staudenmeir/laravel-upsert)**

**Comment by dunhamjared** [comment]
For you Googlers, Laravel's Query Builder now has `insertOrIgnore` in version v5.8.33 and up:

```php
<?php
DB::table('users')->insertOrIgnore([
    ['id' => 1, 'email' => 'taylor@example.com'],
    ['id' => 2, 'email' => 'dayle@example.com']
]);
```

Read more here: https://laravel.com/docs/5.8/queries#inserts

**Comment by iwasherefirst2** [comment]
@dunhamjared thank you! Exactly what I was looking for.
