### ISSUE TITLE
[Proposal] Add functions to use onQueue() delay() in Event Listeners

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/framework#9615]
Laravel makes it really easy to push an event listener/handler onto a queue, but it is missing an easy way within that listener to specify what queue it should be pushed onto.

```php
<?php

namespace App\Listeners;

use App\Events\PodcastWasPurchased;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class EmailPurchaseConfirmation implements ShouldQueue
{
    // add methods to set onQueue and delay()
}

```

**Comment by ibrasho** [comment]
You don't push listeners to the queue, you push the event itself.

Can't you use classes for events and just implement `Illuminate\Bus\Queueable` ?

**Comment by BrandonSurowiec** [comment]
I'm firing off an event, but then I have several listeners responding to the same event. Some of those listeners are done right away, and others are queued using the auto-queue method above. But I don't want each listener to go on the same `queue`.  

Using the DB driver there is a `queue` column which has the value of `default`, but I want those separate listeners to have different values for that column so I can process them differently. I don't know of an easy way of doing it yet .

Maybe I'm doing it wrong, but I'm desiring `ShouldBroadcast`'s ease of use. :)

**Comment by GrahamCampbell** [comment]
I don't think this needs changing.

**Comment by glockops** [comment]
I've been googling for a while to figure out how to do this.  At least now I know it's not supported.  @BrandonSurowiec the approach I'm now taking is to have an event listener that isn't queued which triggers a job on the queue that I specify.  It's an extra step, but it will provide the required functionality.

**Comment by BrandonSurowiec** [comment]
@glockops Thanks so much for the tip! Care to share some sample code?

**Comment by BrandonSurowiec** [comment]
I found an elegant solution that worked for my listener.

```php
// 5.1
use Illuminate\Contracts\Queue\ShouldQueue

class MyExampleListener implements ShouldQueue {

    /**
     * Push a new job onto the queue.
     *
     * @param  string  $queue
     * @param  string  $job
     * @param  mixed   $data
     * @return mixed
     */
    public function queue($queue, $command, $data)
    {
    	dd($data);

        $queue->pushOn('facebook.agent', $command, $data);
        return $queue->pushOn('facebook.company', $command, $data);
    }
}
```

**Comment by johnpaulmedina** [comment]
Just to confirm? I think you have a queued job that runs when the delay of the original job should happen then you just pushOn at that point in time when that delay should be effective?

I bump the fact that Queue::later should have the option to specify the tube

**Comment by yurik94** [comment]
@BrandonSurowiec  Cool, still working perfectly on L5.7
My events, even though with redis on a dedicated i9, were slow by a one second delay, now they are so fast
