### ISSUE TITLE
WSOD due to breaking change in Exception Handler

### ISSUE THREAD

**Issue by tampadesign** [laravel/framework#9616]
A recent commit (526fbe0d3b1831488c427a50a1ef75afe2eb1dce) breaks the default exception handler that ships with Laravel (https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php). It causes a WSOD and also stops Laravel/Monolog error logging.

The problem is that the \Exception typehint was removed from the report() method in Illuminate\Foundation\Exceptions\Handler. Because of this, the contract is broken by the default Handler (App\Exceptions\Handler) that ships with Laravel since it still typehints \Exception in report().

A simple fix (remove the typehint in the child class) but will cause anyone who updates or freshly installs to run into a WSOD when an exception occurs.

**Comment by ArjanSchouten** [comment]
So if you remove the ```Exception``` typehint [here](https://github.com/laravel/laravel/blob/7e303014b6ab627e18dcdc5ee976e7fe545a3092/app/Exceptions/Handler.php#L28-L40) it will be fixed?

**Comment by tampadesign** [comment]
@ArjanSchouten Yes, that's all that needs to be done to comply with the changes in the parent class.

**Comment by GrahamCampbell** [comment]
Not breaking. That change was only made on laravel 5.2.

**Comment by ArjanSchouten** [comment]
Yeh it's on Master I know. Although nice work from @tampadesign

**Comment by tampadesign** [comment]
Ok, yea -- my composer.json has "laravel/framework": "~5.0", so I got the 5.2 changes.

Thanks @ArjanSchouten and @GrahamCampbell

**Comment by ArjanSchouten** [comment]
You know laravel 5.1 is stable and 5.2 dev?

**Comment by GrahamCampbell** [comment]
Nobody should be using 5.2.

**Comment by GrahamCampbell** [comment]
> Ok, yea -- my composer.json has "laravel/framework": "~5.0"

VERY bad idea. Laravel does NOT follow semver.

**Comment by GrahamCampbell** [comment]
`5.1.*` is what you want.

**Comment by tampadesign** [comment]
Gotcha, thanks!

**Comment by ArjanSchouten** [comment]
This way you'll get feedback :smile:
