### ISSUE TITLE
Wrong query generation

### ISSUE THREAD

**Issue by KevinM86** [laravel/framework#9622]
It seems that the following generates a wrong query when using eager loading.

```
class Category extends \Illuminate\Database\Eloquent\Model
{
	protected $table = 'categories';
	public $timestamps = false;

	public function __construct() {
		
	}
	
	public function i18ns() {
		$regionid = \Auth::user()->properties->selectedRegion;
		return $this->hasMany("\App\CategoryI18N", "categoryId")->where('regionId', '=', $regionId);
	}
}
```

### Not eager loaded - ok
If I call i18ns relation without eager loading, the $regionId is indeed the selectedRegion from the userproperties.
```
\App\Category::where('id', '=', 1)->with('i18ns')->first()->i18ns;
```
Query: 
```
select * from `userproperties` where `userproperties`.`userId` = '2' and `userproperties`.`userId` is not null limit 1
```

### Eager loaded - not ok
However, if I eager load the i18ns relation, $regionId is the selectedRegion from the first userproperty record in my table.
```
\App\Category::where('id', '=', 1)->with('i18ns')->first()->i18ns;
```
Query: 
```
select * from `userproperties` limit 1
```

Anyone that can explain this? Or is it a bug?

I also posted this on laracasts:
https://laracasts.com/discuss/channels/eloquent/wrong-query-generation

Kind regards,
Kevin

**Comment by GrahamCampbell** [comment]
The response on the forums was very good. Glad this was sorted. :)

**Comment by KevinM86** [comment]
The problem still occurs, I only have a workaround now.

I guess this code should work.

```
class Foo extends Model
{
    public function bars()
    {
        echo User::find(2)->property->selectedRegion; // Wrong value here!
        return $this->hasMany(Bar::class);
    }
}
```
