### ISSUE TITLE
Dispatching jobs from requests uses default values over request values

### ISSUE THREAD

**Issue by adamtomat** [laravel/framework#9631]
## Bug

As per the [documentation](http://laravel.com/docs/5.1/queues#dispatching-jobs-from-requests), when dispatching jobs via `dispatchFrom` the method takes a third argument:

> You may also pass an array as the third argument to the dispatchFrom method. This array will be used to fill any constructor parameters that are not available on the request:

This implies that anything in this array will act as a fallback if it cannot fill the constructor parameters via the request. However, the current implementation behaves differently.

From my understanding (and testing), what is actually happening is any values passed in via the `dispatchFrom()` third parameter take precedence over request variables.

Here's the method in question: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Bus/Dispatcher.php#L152

```php
protected function getParameterValueForCommand($command, ArrayAccess $source,
        ReflectionParameter $parameter, array $extras = [])
    {
        if (array_key_exists($parameter->name, $extras)) {
            return $extras[$parameter->name];
        }
        if (isset($source[$parameter->name])) {
            return $source[$parameter->name];
        }
        if ($parameter->isDefaultValueAvailable()) {
            return $parameter->getDefaultValue();
        }
        MarshalException::whileMapping($command, $parameter);
    }
```

The first if statement will return any value it finds from `$extras` before it checks for it in the request, which contradicts the documentation. I am unsure which is the intended behaviour, but it appears the **documentation is incorrect** and the above block of code is correct.

It seems that the third parameter for `dispatchFrom` is not a default value, but indeed a way to force a value regardless of the request. Instead, to provide a fallback you can just set one in the constructor of the job:

`public function __construct($example = 'default')`

## Replicating

Assuming `$request->input('example');` yields `from-request`...

In a controller that uses the trait `DispatchesJobs` from `Illuminate\Foundation\Bus\DispatchesJobs`:

```php
// Controller 1 - No third parameter
public function index(\Illuminate\Http\Request $request)
{
    $this->dispatchFrom(\App\Jobs\ExampleJob::class, $request);
}

// Controller 2 - With a third parameter
public function index(\Illuminate\Http\Request $request)
{
    $this->dispatchFrom(\App\Jobs\ExampleJob::class, $request, [
        'example' => 'from-controller'
    ]);
}
```

And in the Job's constructor:

```php
// Job 1 - No default value
public function __construct($example)
{
    dd($example);
}

// Job 2 - Default value
public function __construct($example = 'from-constructor')
{
    dd($example);
}
```

**Controller 1 & Job 1** yields: `from-request` - throws exception when request doesn't contain `example`

**Controller 1 & Job 2** yields: `from-request` - defaults to `from-constructor` when request doesn't contain `example`

**Controller 2 & Job 1** yields: `from-controller`.

**Controller 2 & Job 2** yields: `from-controller`.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.
