### ISSUE TITLE
[L5] getenv() doesn't return .env values on FreeBSD

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#9633]
We've seen the problem that getenv() used in the env() helper function doesn't return the values from the .env file even if the are available via $_ENV. We noticed that on a FreeBSD machine.

Solution in Illuminate/Foundation/helpers.php:628
- $value = getenv($key);
+ $value = $_ENV[$key];

An "isset($_ENV[$key]) check should be done before.

**Comment by GrahamCampbell** [comment]
Could you please take this up with dotenv since that's who we're using under the hood. Thank you. :)

**Comment by aimeos** [comment]
Nope, the fix was for the Laravel code

**Comment by GrahamCampbell** [comment]
No, I'm saying this needs fixing at the source. Some hack on top isn't good enough.

**Comment by aimeos** [comment]
getenv() is an internal PHP function that calls the getenv() C function from stdlib. If the FreeBSD stdlib implementation has additional checks to prevent overriding what getenv() returns, the dotenv project will not be able to fix anything.

The only way to make this work is by using the $_ENV superglobal.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell. Not my call on what to do.

**Comment by shehi** [comment]
@aimeos : it never worked on any Linux - at least I tried on Ubuntu and Fedora. I believe ENV vars get placed inside ```$_SERVER``` instead of ```$_ENV``` in some environments - but I managed to get mine using PHP-FPM's config and typing everything inside like:

```
[senisecti]
listen = /var/run/php5-fpm-senisecti.sock
listen.owner = senisecti
listen.group = www-data
listen.mode = 0660
user = senisecti
group = www-data
pm = ondemand
pm.max_children = 50
...
php_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[max_file_uploads] = 20
php_admin_value[memory_limit] = 128M
...
env[APP_ENV]=staging
... goes on and on ...
```
