### ISSUE TITLE
L5.1 RedirectPath no effect

### ISSUE THREAD

**Issue by sciasfreelancer** [laravel/framework#9634]
```
	protected $redirectPath = '/dashboard';
```
This code described in http://laravel.com/docs/5.1/authentication has no effect.
I put it in AuthController class and it still redirects to /home

**Comment by GrahamCampbell** [comment]
Just had a look at our code, and this looks as if it works fine.

**Comment by GrahamCampbell** [comment]
Perhaps you need to reload php fpm?

**Comment by sciasfreelancer** [comment]
Sorry. I just checked, appearently when you redirect authenitcated user to /auth/login it will always redirect you back to /home no matter what.

**Comment by GrahamCampbell** [comment]
You probably need to flush HHVMs cache in a equivalent way then.

**Comment by sciasfreelancer** [comment]
I already did. No matter what user is being redirected to /home.

Try it for yourself. From a "auth" middleware redirect /home to /auth/login and he will ALWAYS be redirected to /home EVEN if it's set to /dashboard

**Comment by sciasfreelancer** [comment]
Example:
```
Route::group(['as' => 'admin::', 'middleware' => 'auth'], function () {
	Route::match(['get', 'post'], '/home', function(){return redirect()->intended('/auth/login'); });
// some other routes
}
```

**Comment by lukasgeiter** [comment]
The redirect if you're logged in and visit the login page is handled at a completely different place. Take a look at `App\Http\Middleware\RedirectIfAuthenticated`

**Comment by sciasfreelancer** [comment]
@lukasgeiter oh damn. Didn't see that one. This should be notified in docs though.

Thanks.

**Comment by jturmel** [comment]
We just ran into this and had to track it down, the docs clearly say to set $redirectPath but the middleware is hard coded to /home.

Reference: http://laravel.com/docs/5.1/authentication#included-authenticating
