### ISSUE TITLE
New session is created on each request

### ISSUE THREAD

**Issue by rpg999** [laravel/framework#9635]
Recently I started working on a new project. There was a problem with logging in. I and my teammate, we both made a fresh checkout from a repository but his app works fine, while my copy always tries to create new session on each request, in result i could not authorize to the app (new session file is created in storage/sessions every time) . Here is the code, i know it its not very clear because this is our first project on Laravel: 

```
Route::post('/login', function()
	{
		Asset::add('jquery', URL::to('media/backend/js/jquery.min.js'));
		Asset::add('backendjs', URL::to('media/backend/js/backend.js'));
		$user = array(
			'email' => Input::get('email'),
			'password' => Input::get('password')
		);

		if (Auth::attempt($user))
		{
/ ***** IF I CALL  Auth::user() HERE I WILL GET A USER OBJECT **/
            return Redirect::intended('/');
		}
		$view= View::make('backend.login')->with('error','Wrong login or pass');
		return $view;
	});


	Route::group(array('before'=>'admin-auth'),function()
	{
/*********** BUT  IF I CALL Auth::user()  I GET NOTHING ************/
		Route::controller('users', 'BackendUserController');
		Route::controller('user_type', 'UserTypeController');
		Route::controller('document', 'DocumentController');

		Route::get('/', function()
		{
			return App::make('DocumentController')->getAll();
		});
	});
```

function auth admin just check if the user is logged in

``` 
Route::filter('auth-admin', function()
{
/*********** Auth::user()  GIVES ME NOTHING HERE TOO************/
	if (Auth::guest()) return Redirect::guest('login');
});
```

I have checked the table, the primary key of User object as it was mentioned here 
[https://github.com/laravel/framework/issues/161], but it does not help at all. I have no idea how to fix it. 
Please help :(

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
