### ISSUE TITLE
route not found?

### ISSUE THREAD

**Issue by BardiaAfshin** [laravel/framework#9637]
Okay, I'm building out a service on ec2 (ubuntu 64 bit 14.04LTS) on a application that I've built locally on my mac that works just fine.

The problem is that route:list doesn't find one specific route, and if I comment out the route to that controller, it works just fine. Help?

``bash
ubuntu@ip-192-168-3-183:/var/www/email-microservice$ ./artisan route:list

                                                            
  [ReflectionException]                                     
  Class App\Http\Controllers\OrgunitService does not exist  
                                                            

ubuntu@ip-192-168-3-183:/var/www/email-microservice$ find -name routes.php
./app/Http/routes.php
ubuntu@ip-192-168-3-183:/var/www/email-microservice$ find -name routes.php^C
ubuntu@ip-192-168-3-183:/var/www/email-microservice$ php --version
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
ubuntu@ip-192-168-3-183:/var/www/email-microservice$ ./artisan |head -n 5
Laravel Framework version 5.0.33

Usage:
 command [options] [arguments]

```

EDIT: local php version is 5.5.24 and ec2 instance of php version 5.5.9

**Comment by BardiaAfshin** [comment]
here's a copy of the routes.php

```php
cat ./app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/authenticate', 'AuthenticationService@create');
Route::get('/send', 'SendEmail@create');
Route::get('/xouid', 'OrgunitService@create');
Route::get('/create', 'EmailController@create');

Route::resource('/api/v1/message.', 'MessagingController',
                ['only' => ['store']]);
```

**Comment by Luceos** [comment]
class not exists mostly indicate a composer issue, use `composer dumpautoload` and see if that changes anything. Can you post the `App\Http\Controllers\OrgunitService`?

**Comment by BardiaAfshin** [comment]
tried it, problem persists

```bash
composer dump && ./artisan route:list
Generating autoload files


                                                            
  [ReflectionException]                                     
  Class App\Http\Controllers\OrgunitService does not exist  
                                                            
```

**Comment by Luceos** [comment]
> Can you post the App\Http\Controllers\OrgunitService?

**Comment by fureszpeter** [comment]
Yes, post your `OrgunitService` content and from the project root, please
copy past the output of this command

`ls -l ls app/Http/Controllers/OrgunitService.php`



Sincerely / Üdvözlettel
Peter Furesz

**Comment by GrahamCampbell** [comment]
Could you please continue this on the forums. :)

**Comment by joshaxelman** [comment]
Why was this closed? I am having the same problem.

**Comment by BardiaAfshin** [comment]
So for anybody else out there getting this exception. I had developed this on a local mac os x.

That exception was happening on Ubuntu.

The problem is that Mac does not throw exception for not having exact casing on the letters. 

In my routes I was referencing 'OrgunitService' with a lower case letter 'u', where the actual class is defined as 'OrgUnitService'. 

So the exception is correct, what was hard to find is the fact that mac is not treating that class as case sensitive and Ubuntu 14.04 LTS is.
