### ISSUE TITLE
Localization bug (outputs arbitrary "1" 's)

### ISSUE THREAD

**Issue by digixweb** [laravel/framework#9645]
I have a lang file called "forms.php" and noticed it would print out a "1" next to the translated key.

In some cases I solved it to rename the lang file. However not always, if I do this:
$insertion = trans("elems.".$value->insertion['default']);
It still does this weird output of "1"

It also makes a difference in what function I call this. For instance when I executed a mysql query with an ID given by a function call.  So for instance: print(userId); And I would send it with a string in stead of an integer, it also outputs this weird 1. So bug would appear around a translation in this case where I would send it as: print("1"), but if I would send it as print(1) the bug does not show up.

So not sure what is going on, but it looks something is off here. Hope this makes sense.

**Comment by GrahamCampbell** [comment]
I don't quite understand your issue. Could you provide a really short code example please with the actual results vs the results you'd expect.

**Comment by digixweb** [comment]
Sure!

Like I said there are different setups leading to this bug. 

I can give you one scenario right now:

For instance. I have a model setup like this:

public function getPresetAttribute($value)
 {
		$langPaymentmethod = "elems";
		$value = trans($langPaymentmethod.'.Preset'.$value);

		return $value;
  }


So in this case I want to retrieve a translated string: elems.Preset0

In my view I use this by calling: <td>{{{ $studentInvoice->preset }}}</td>

Well now, in case there is no "Preset0" translation present in the elems.php file I get this:

1 elems.Preset0 
  
in stead of just

elems.Preset0

I also tried with {!! escaping, same result. Hope this helps.

**Comment by shehi** [comment]
Are you sure there is no condition checks in your code (something like ```$var = \Lang::getLocale() != \Config::get('app.locale')``` which in turn gets type casted to ```1``` when ```$var``` becomes ```true```? I had such scenario in mine, in recent past and it is sometimes hard to detect.

**Comment by vlakoff** [comment]
@digixweb maybe you have solved it since?
