### ISSUE TITLE
Artisan Console bug

### ISSUE THREAD

**Issue by heoquay99** [laravel/framework#9646]
$name = $this->choice('What is your name?', ['Taylor', 'Dayle'], false);
get error messages [ERROR] Undefined index: Dayle

**Comment by GrahamCampbell** [comment]
Yeh, you need to provide a key value pair, otherwise, `1` would be the index for Dayle.

**Comment by heoquay99** [comment]
no bro, in past my code run already. But when i run composer update it's has problem and it's has problem.

**Comment by GrahamCampbell** [comment]
What version from and to?

**Comment by GrahamCampbell** [comment]
Both laravel version, and symfony console version please.

**Comment by heoquay99** [comment]
Laravel Framework version 5.1.6 (LTS) to 5.1.7 and symfony/console v2.7.1 to v2.7.2

**Comment by GrahamCampbell** [comment]
Looks like a regression in symfony then. We haven't changed our console component at all.

**Comment by heoquay99** [comment]
please review that's thank you :D
