### ISSUE TITLE
findOrFail missing for many relations leading to dropped pivot data

### ISSUE THREAD

**Issue by jochenmanz** [laravel/framework#9647]
Hallo,

i have the following Models and Relations (Pseudocode)

User > belongsToMany > Groups
Groups > belongsToMany > User

I tried to get some data from the pivot table, for this example the pivot timestamps. The relationship was set with -> withTimestamps().

```
// get user by group id
$group = Group::findOrFail($gid);

$group->users()->findOrFail($uid); <- this will find the correct user, but no pivot data is present
$group->users()->find($uid) <- works correctly, pivot data is present.
```

I found out that the findOrFail function is missing from the following relations, c&p them from the Builder made the above example work.

- BelongsToMany
- HasManyThrough
- HasOneOrMany
- MorphOneOrMany

I am unsure how to solve this properly, c&p the functions into the relations can be done. A advice to fix it properly is appreciated.

Best regards,
Jochen

**Comment by GrahamCampbell** [comment]
Hi @jochenmanz. I'm afraid I can't really answer this since only Taylor can decide what PRs are accepted. Ping @taylorotwell.
