### ISSUE TITLE
forceDeleting event?

### ISSUE THREAD

**Issue by newtonianb** [laravel/framework#9653]
Is there a way to listen to forceDeleting events? We naturally have model with relations to other models and we need a way to cascade the delete. We hooked on to the deleting event and call delete through each relation this way.

However when you force delete we have the same problem, we need to cascade this down but there are no events.

How is this usually done it seems like a common scenario?

**Comment by GrahamCampbell** [comment]
No, but you can of course just override the force delete method and fire your own event. :)
