### ISSUE TITLE
Isn't this a security issue?

### ISSUE THREAD

**Issue by hcancelik** [laravel/framework#9658]
ResetsPasswords trait returns INVALID_USER when the user doesn't match with the sent email address. Does this open a hole where you can simple check if an email address exists in users table?

~~~
 /**
     * Send a reset link to the given user.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function postEmail(Request $request)
    {
        $this->validate($request, ['email' => 'required|email']);

        $response = Password::sendResetLink($request->only('email'), function (Message $message) {
            $message->subject($this->getEmailSubject());
        });

        switch ($response) {
            case Password::RESET_LINK_SENT:
                return redirect()->back()->with('status', trans($response));

            case Password::INVALID_USER:
                return redirect()->back()->withErrors(['email' => trans($response)]);
        }
    }
~~~

**Comment by lukasgeiter** [comment]
Please report security issues directly to Taylor as described here: http://laravel.com/docs/5.1/contributions#security-vulnerabilities

**Comment by hcancelik** [comment]
thanks @lukasgeiter. Just sent him an email.

**Comment by NFarrington** [comment]
This really isn't considered a security issue in this day and age, particularly with public registration systems.
What are you going to do if someone tries to register with an email address or username that already exists? You're going to tell them it's not available, and to choose a different one - it would be a very confusing sign-up process for a user if you tried to protect against this.
Most sites with public sign-ups even display user's usernames and/or emails publicly.

**Comment by hcancelik** [comment]
@NFarrington huh?

**Comment by NFarrington** [comment]
'huh?' doesn't really explain your confusion - what part of my response are you having difficulty with?

TL;DR being able to check if an email address exists in a users table is perfectly normal.

**Comment by hcancelik** [comment]
@NFarrington all of it.

**Comment by RickLancee** [comment]
@hcancelik Why —in your opinion— is checking if a email exists in the database a security issue? When in a sign-up form it's common practice to let the user know when an given email is already taken.

**Comment by Shkeats** [comment]
@hcancelik The point that @NFarrington is making is pretty clear to me. It's necessary that a new user be told that an email or username can't be registered during the registration process if it's already in use. Otherwise they wouldn't be able to understand why they can't complete registration with that username or email. Therefore this 'vulnerability' already exists in any public facing user and registration process. The username and email is not a secret, the password is.

**Comment by GrahamCampbell** [comment]
Nah, it's not a security issue, but if you don't want people to know if the user exists, you're free to change this behaviour. Thank you for your concern though. :)

**Comment by hcancelik** [comment]
Thank you guys for the reply. I forgot about the public user registration part where you can also run into the same scenario. 

I guess it's more of a privacy issue rather than a security for my case. I'm working on a private website where there is no public registration. The current "forget password" opens a hole where anyone can check if an email is signed up to site.

Well I guess changing the error message for throttle will fix my issue for now. Thanks again.

**Comment by EliasZ** [comment]
Can we reconsider this issue? It is kind of a weird default implementation to allow email address pinging (enumeration). For example, OWASP (for what it's worth) [states the following](https://www.owasp.org/index.php/OWASP_Periodic_Table_of_Vulnerabilities_-_Insufficient_Password_Recovery):

>The reset form should not expose an account enumeration vulnerability

An answer over at Security SE explains the potential attack vector: "[hypothetical yet very plausible scenario](http://security.stackexchange.com/a/42873)".

On a related note, it is also odd that in the reset process, when filling in a reset (`reset` method), it is expected that the request should contain the email address of which the password is being changed. With solely the token - which could very well be unique - the email address can be retrieved from the database. It feels kinda redundant when you receive such a token in your email inbox, you still have to fill in your email address.

Yes, from a security standpoint, without email confirmation, you could *potentially* brute force a 32 character random token to find active "password resets" and hijack said account without knowing the email address associated. And yes, I am aware the implementation can be changed at application level.

**Comment by EliasZ** [comment]
The boilerplate is also very specific. You cannot change the behavior of `reset` without checking the response returned or completely duplicating all of the code and hand tailoring it.

For example, if you wish to modify what happens after `reset`, you currently have two options:

- call `reset`, store the controller action its response and then verify what to do based on which session data is set (`status`, which is already a translated string or whether the session has errors)
- copy all the code of `reset` over and write your own implementation

For example, in an application, wanting to modify the `ResetsPasswords` trait its behavior, we had to do this:

    use ResetsPasswords;

    public function postEmail(Request $request, Store $session)
    {
        $response = $this->sendResetLinkEmail($request);

        if ($session->has('status')) {
            $this->notification->info(PasswordBroker::RESET_LINK_SENT);
        }

        return $response;
    }

    public function postReset(Request $request, Store $session)
    {
        $response = $this->reset($request);

        if ($session->has('status')) {
            $this->notification->info(PasswordBroker::PASSWORD_RESET);
        }

        return $response;
    }

Wouldn't it make more sense if the action (like `reset` and `sendResetLinkEmail`) would return the result of the `PasswordBroker` and the actual controller action would form the response based on that? So it is easier to customize the behavior.

This also affects #11335
