### ISSUE TITLE
.env not being loaded when using phpunit for testing in L5.1

### ISSUE THREAD

**Issue by activatedgeek** [laravel/framework#9663]
I recently upgraded to L5.1, and had the following setup. My tests folder has a base class which has the standard Laravel setup as

```
<?php namespace Testing;

class TestCase extends \Illuminate\Foundation\Testing\TestCase {

	/**
	 * Creates the application.
	 *
	 * @return \Illuminate\Foundation\Application
	 */
	public function createApplication()
	{
		$app = require __DIR__.'/../bootstrap/app.php';

		$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

		return $app;
	}
}
```

Now when I run `phpunit`, in the previous version it used to load all environment variables from my `.env` file. After a recent upgrade to `L5.1`, it is not loading the `.env` file, hence my test cases are throwing exceptions due to the environment variable not found. Though, it is loading the environment variables I set in the `phpunit.xml` file. Is this the expected behavior?

**Comment by GrahamCampbell** [comment]
> Is this the expected behavior?

Yeh, this is the expected behaviour. :)

**Comment by activatedgeek** [comment]
@GrahamCampbell How can I replicate the old behavior?

**Comment by GrahamCampbell** [comment]
Not sure off the top of my head. If you ask on the forums, I'm sure someone can help you out there. :)

**Comment by activatedgeek** [comment]
Thank you! :)

**Comment by activatedgeek** [comment]
Thank you! :)
