### ISSUE TITLE
[Eloquent][Proposal] BelongsToManySymmetrical

### ISSUE THREAD

**Issue by rulrok** [laravel/framework#9666]
The motivating problem can be found at issue #2673 .
I've made a long comment there. Since the comment got bigger and bigger, and because the topic is very old, I felt motivated to open a new issue better describing my ideas here.
On that new issue I summarize what a described there.

## Motivation 

Add/remove friends/followers in an eloquent manner from both ways (either as the follower or as the followed).

## Description of problem

For those situations, we have a many-to-many relationship similar to this:

user_id | friend_id
------ | -------
1 | 2
1 | 3
2 | 3
2 | 5

The following methods would be reasonable.

```php
 public function friends(){
   return $this->belongsToMany('App\User', 'user_friend', 'user_id', 'friend_id');
 }

 public function add_friend(User $user) {
   $this->friends()->attach($user);
   return $this;
 }

 public function remove_friend(User $user) {
   $this->friends()->detach($user);
   return $this;
 }

```

When *user 1* wants to add a friend, we could have

```php
 $user1->add_friend($user2);
```

The problem comes when *user 2* wants to remove that person.

```php
 $user2->remove_friend($user1)
```

The above code would not work for laravel would look up the user_friends table looking for __user_id__ as __2__ and __friend_id__ as __1__. That does not exist, but the reverse exists, i.e, __user_id__ as __1__ and __friend_id__ as __2__.

Long story short, __belongsToMany__ would see *user 1* as friend with *user 2*, but not that *user 2* is friend with *user_1* based on the database table below.

user_id | friend_id
------ | -------
1 | 2
1 | 3
2 | 3
2 | 5

## Tried solution

I have tried doing something like the following

```php
/**
* @return App\User[]
*/
public function friends(){
  $query_1 = $this->belongsToMany('App\User', 'user_friend', 'user_id', 'friend_id')->getBaseQuery();
  $query_2 = $this->belongsToMany('App\User', 'user_friend', 'friend_id', 'user_id')->getBaseQuery();

 return $query_1->union($query_2)->get();
}
```

The problem is that I lose the convenience of function such as `add_friend($user)` and `remove_friend($user)` described before.

The query union will generate the following SQL
```sql
 (select * from `user` inner join `user_friend` on `user`.`id` = `user_friend`.`friend_id` where `user_friend`.`user_id` = ?) 
union
 (select * from `user` inner join `user_friend` on `user`.`id` = `user_friend`.`user_id` where `user_friend`.`friend_id` = ?)
 union
 (select * from `user` inner join `user_friend` on `user`.`id` = `user_friend`.`user_id` where `user_friend`.`friend_id` = ?)
```

## Suggestion

For select the related models, what about generating a SQL something like the following?

```sql
select user.id from `user` where `user`.`user_id` IN 
(
 select * from (
  (select friend_id from user_friend WHERE user_id = 1)
  union
  (select user_id from user_friend WHERE friend_id = 1)
 ) AS subquery -- it is important that this query has a name
)
```

As eloquent method, something like that:

```php
 public function friends(){
   return $this->belongsToManySymmetrical('App\User', 'user_friends', 'user_id', 'friend_id');
 }

 public function add_friend(User $user) {
   $this->friends()->attach($user); //Would look up for both user_id and friend_id columns to operate
   return $this;
 }

 public function remove_friend(User $user) {
   $this->friends()->detach($user); //Would look up for both user_id and friend_id columns to operate
   return $this;
 }
```

**Comment by CMDann** [comment]
:+1:

**Comment by shehi** [comment]
This kinda scenarios make me regret using frameworks :) There are so many of them, and they are such brain drainers.

+1

**Comment by jufy** [comment]
+1

**Comment by prohalexey** [comment]
I think you should not mix meaning of relation. It's a 2 kind of tables(friends_requests, friends_list).
Table friends_requests (id, user_from, user_to, approved_at, declined_at, created_at, updated_at, deleted_at)
I JAST WANT to be a friend of someone.
->myfriendrequest() //SELECT * FROM friends_requests WHERE user_from = {my.user_id}
Someone JUST WANT to be my friends
->wanttobemyfriends() //SELECT * FROM friends_requests WHERE user_to = {my.user_id}

And on Approved_at you must have observer(trigger in DB or ORM observer), when getDirty['approved_at'] == STATUS_APPROVED in saving, insert in friend_list new row, on deleting friend, delete friend_request rows and delete row from friends_list.

Table friends_list(id, user_id, friend_id)
->friends() // SELECT * FROM friends_list WHERE user_id = {my.user_id}

**Comment by fetch404** [comment]
+1 :+1:

**Comment by syaiful6** [comment]
I dont like this idea,

**Comment by daniel-gomes** [comment]
+1 had to find ways around to implement this precise situation on my project

**Comment by codefocus** [comment]
So `$user1` calls `$user2` a friend, but `$user2` does not call `$user1` a friend?

It would make sense that `$user2->remove_friend($user1)` does not do anything in that case, since `$user2` cannot change who `$user1` calls "friend". This seems more like the "follower" model that Twitter uses.

If the relationship goes both ways, imo that should be reflected in the database:

user_id | friend_id
--------|--------
1|2
2|1

**Comment by rulrok** [comment]
@codefocus If `$user2` can or cannot break this relationship will be up to your business logic.
In some situations, like mine, whenever one breaks the friendship, this will be broken in both directions.

**Comment by GrahamCampbell** [comment]
Thanks for the report, but we don't process feature requests. We are, however, open to PRs.

**Comment by brian2694** [comment]
Did you found any solution for this scenario? @rulrok

**Comment by rulrok** [comment]
@brian2694 Back then, to simplify matters for our project, we had decided that the friendship concept wouldn't exist. Rather, users could follow and be followed by other users.

https://github.com/PanoPla/panopla/blob/develop/app/User.php

I know, it doesn't fix the problem, but it simplifies the project. =p

**Comment by brian2694** [comment]
I'll analyze it. Thank you.

And I've found this.
https://github.com/AbdullahGhanem/friendship
