### ISSUE TITLE
laravel session can not auto save only when window's machine make the request.

### ISSUE THREAD

**Issue by xkong63** [laravel/framework#9669]
when use window machine whatever browser, some times the laravel doesn't call the terminate function, some times works well.

**Comment by GrahamCampbell** [comment]
Not sure what you mean. I assume you mean when someone uses internet explorer?

**Comment by GrahamCampbell** [comment]
Please ask on the forums, or look through the previous issues as this is well documented. Try using the redis session driver as the file one is pretty crap.
