### ISSUE TITLE
Symfony update causes Artisan 'choice' function to fail

### ISSUE THREAD

**Issue by SimonSonar** [laravel/framework#9677]
I don't know if this is really a bug in Laravel or an issue with Symfony, but after updating to the latest revision of Laravel, the following line in symfony/console/Question/ChoiceQuestion.php was changed:

array_push($multiselectChoices, (string) $result);

It was changed to:

$multiselectChoices[] = $choices[(string) $result];

This change causes any artisan command using the 'choice' method to fail, as it now appears to try to access the array of choices by the value rather than the key. For example:

$choices = [ "Choice 1", "Choice 2", "Choice 3"]
$this->choice("Select a choice, $choices)

When executing the artisan command, it will prompt you to select 0, 1 or 2 as a selection with the names 'Choice 1', 'Choice 2' or 'Choice 3', but if you enter '0' it will error, stating that Choice 1 is not a value index for the array.

Reverting the aforementioned line in the Symfony component resolves this issue.

**Comment by GrahamCampbell** [comment]
Please bring this up with symfony. They need to fix this breaking change.
