### ISSUE TITLE
Middleware class must be registered as singleton if it has terminate method

### ISSUE THREAD

**Issue by ifeltsweet** [laravel/framework#9683]
If middleware is not registered as singleton within container and it has `terminate` method, `HttpKernel` will create a new instance of your middleware and call `terminate` on that instance, losing your previous instance properties.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Http/Kernel.php#L143

Have not tested this on Laravel, only on Lumen, but pretty sure it's the same.

To fix, either make a note about this in documentation so users can take care of this by themselves or register all passed middleware as singletons for users during bootstrap.

**Comment by GrahamCampbell** [comment]
Not sure how we can actually fix this?

**Comment by GrahamCampbell** [comment]
> register all passed middleware as singletons for users during bootstrap.

That would be a bad idea, as it could destroy existing registrations.

**Comment by GrahamCampbell** [comment]
It's up to users to deal with the correct bindings them selves.

**Comment by ifeltsweet** [comment]
Yes I agree with you. But can we at least update the documentation to let users know that if they want `terminate` to work correctly not to forget to bind the middleware as singleton. Not everyone has knowledge and time to dig through source code to figure out why on Earth it's not working.

If you give me thumbs up for this I'll send PR to laravel/docs.

**Comment by GrahamCampbell** [comment]
> If you give me thumbs up for this I'll send PR to laravel/docs.

Not really up to me, though I don't think anything needs changing on the docs.

**Comment by chrisbjr** [comment]
Argh.. this is a big problem for me. Thanks for pointing it out in the docs. Googled that exact line in the docs, took me to stackoverflow, then took me here.

Looking at the `Kernel.php`.. there doesn't seem to be an easy way to fix this.
