### ISSUE TITLE
[User] Auth configuration

### ISSUE THREAD

**Issue by EmixFrench** [laravel/framework#9684]
Hello guys,
mmh, i configured the file auth.php, key "model" but it does not work.
My User Model he's on namespace "App\Models"...
auth.php =>
```php
 'model' => App\Models\User::class,
```
Why i have this error ? "Class 'App\User' not found"?

But when I change the namespace in AuthController.php
```php
use App\User;
// to
use App\Models\User;
```
it work..

Sorry for my bad english :-)

**Comment by GrahamCampbell** [comment]
Because that's the correct location of your class?

**Comment by EmixFrench** [comment]
Yes, but the configuration "model" it's used for..?

**Comment by CupOfTea696** [comment]
It probably needs to be

```php
 'model' => \App\Models\User::class,
```

**Comment by GrahamCampbell** [comment]
That's used internally. It's got nothing to do with any code you write. It's not magic. :)

**Comment by malhal** [comment]
Any particular reason why the \App\User model isn't \App\Models\User by default? Seems strange to have to handle this special case when using model classes.
