### ISSUE TITLE
Before validator dosn't work with DateTime objets

### ISSUE THREAD

**Issue by halfik** [laravel/framework#9687]
When field value is a DateTime object, before validator returns error exception

[ErrorException]                                            
  strtotime() expects parameter 1 to be string, object given

**Comment by halfik** [comment]
/**
	 * Validate the date is before a given date.
	 *
	 * @param  string  $attribute
	 * @param  mixed   $value
	 * @param  array   $parameters
	 * @return bool
	 */
	protected function validateBefore($attribute, $value, $parameters)
	{
		$this->requireParameterCount(1, $parameters, 'before');

        if ($value instanceof DateTime){
            $value = $value->format('Y-m-d');
        }

		if ($format = $this->getDateFormat($attribute))
		{
			return $this->validateBeforeWithFormat($format, $value, $parameters);
		}

		if ( ! ($date = strtotime($parameters[0])))
		{
            $toDate = $this->getValue($parameters[0]);
            if ($toDate instanceof DateTime){
                $toDate = $toDate->format('Y-m-d');
            }

			return strtotime($value) < strtotime($toDate);
		}

		return strtotime($value) < $date;
	}

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported.
