### ISSUE TITLE
Problem with mcrypt_create_iv() in virtual server

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#9688]
We had today a massive problem with our Laravel application that wasn't responding any more. The problem was that the virtual server wasn't able to provide enough random data via /dev/urandom:
```
production.ERROR: exception 'ErrorException' with message 'mcrypt_create_iv(): Could not gather sufficient random data' in .../laravel.demo.aimeos.org/vendor/laravel/framework/src/Illuminate/Encryption/McryptEncrypter.php:69
```
As workaround we changed the getRandomizer() method to return the constant for MCRYPT_RAND instead, which solves the problem for the moment. What's a good solution for the future? Make the random data source configurable?

**Comment by GrahamCampbell** [comment]
We only support running on systems where a sufficiently random source is available, sorry.

**Comment by GrahamCampbell** [comment]
If you need this to work on other systems, you're going to just modify our code, but we're not supporting this otherwise since we simply can't recommend people actually do this, sorry.
