### ISSUE TITLE
Automatic Model datatypes and validation based on migration schema

### ISSUE THREAD

**Issue by kingIZZZY** [laravel/framework#9689]
Instead of coding a schema definition in a migration complete with datatypes, lengths, etc. And then re-defining them all over again in the corresponding Model with mutators and validation;

Let the Model compute default datatype mutations and some basic validation based off the schema definition.

###### Examples
* If a $table->dateTime('foo') column has been set in a schema, its corresponding Model should automatically recognize and validate it as a Carbon object.
* A $table->string('bar',100) column should make the corresponding Model validate string lengths appropriately.

Perhaps flags can be set to turn this default datatype-detection and basic validation off for specific columns, but otherwise this seems to make sense that the framework should behave this way / offer this automatic feature.

**Comment by lukasgeiter** [comment]
Sounds like this should be a package and not in the framework core to me...

**Comment by GrahamCampbell** [comment]
Yeh, this should be a package.

**Comment by GrahamCampbell** [comment]
I'd recommend having a trait that you can put on your models that registers a validation observer.

**Comment by GrahamCampbell** [comment]
Something like I've done here: https://github.com/AltThree/Validator.

**Comment by kingIZZZY** [comment]
Hm really? If laravel is trying to make things smooth & streamlined, eliminate repetitive stuff etc. I'd think this would almost be expected from such a framework... but meh what do I know
