### ISSUE TITLE
Cache:: methods should operate with seconds under the hood

### ISSUE THREAD

**Issue by NoNameProvided** [laravel/framework#9691]
Lets say I have a code snippet like this:

```php
if (Cache::has('rateCount')) {
    Cache::increment('rateCount');
} else {
    Cache::put('rateCount', 0, 1);
}
```

When this code called repeatedly less than a minute, then because of the round up in the Illuminate\Cache\FileStore::getPayload method (which is used by the Cache::increment method) the minute will be rounded back to 1 minute even if only 10 seconds remaining, so the cache entry wont expire which is not the expected behaviour. (At least from me)

**Comment by GrahamCampbell** [comment]
Working in seconds would be a MASSIVE break and would destroy everyones apps.
