### ISSUE TITLE
Allow setting timeout for ThrottlesLogin Trait

### ISSUE THREAD

**Issue by kohenkatz** [laravel/framework#9694]
Right now, the `ThrottlesLogin` trait has the timeout [hardcoded at 60 seconds](https://github.com/laravel/framework/blob/0aee92c61b7f322669814e91b4f57a09eed8113c/src/Illuminate/Foundation/Auth/ThrottlesLogins.php#L25).

This means that in order to change the timeout (we want 5 minutes for one of our sites), it is necessary to fully re-implement `hasTooManyLoginAttempts`, in effect just copying that function out of the Trait and changing the one number.

Instead, maybe the Trait should check for a `config('auth.throttle_timeout')` setting or call a function `getTimeoutSeconds` that the login controller can override.

**Comment by arrilot** [comment]
This was already discussed many many times. Morever Taylor has already merged one of PRs.
https://github.com/laravel/framework/pull/9661

**Comment by kohenkatz** [comment]
@arrilot Thanks. I did a search in all issues/PRs for `"ThrottlesLogin"` but it did not return that PR.
