### ISSUE TITLE
Appended Carbon date attribute is not transformed to a datetime string

### ISSUE THREAD

**Issue by ArturKp** [laravel/framework#9700]
I'm not entirely sure if it is a bug or intended behaviour although I would have expected the appended attribute to behave like other model dates.

**Example code:**

	<?php namespace App\Models;

	use Carbon\Carbon;
	use Illuminate\Database\Eloquent\Model;

	class Bar extends Model {

		protected $dates = array('foo');

		protected $appends = array('foo');

		public function getFooAttribute()
		{
			return new Carbon();
		}
		
	}

**Expected output:**

	{
	    "foo": "2015-07-21 08:43:24"
	}

**Current output:**

	"foo": {
		"date": "2015-07-21 08:43:24",
		"timezone_type": 3,
		"timezone": "UTC"
	}

**Comment by GrahamCampbell** [comment]
This is expected. We don't case it to a string to get the json representation.
