### ISSUE TITLE
Artisan make:model -m specify table

### ISSUE THREAD

**Issue by RoM4iK** [laravel/framework#9701]
When artisan making model with migration, it add this line to migration
`Schema::create('table_name', function (Blueprint $table)`
but not adding this line to model
`protected $table = 'table_name';`

Anyway we have predefined table name, so why we must copy it to model?

IMHO, it can be good practice.

**Comment by lukasgeiter** [comment]
When following Eloquents table naming conventions (which the autmatically generated name does) there's no need to specify it in the model.

**Comment by GrahamCampbell** [comment]
This is probably an edge case, so I don't think our out of the box generators need updating.
