### ISSUE TITLE
Custom Validation Attributes not working for attributes.as.array

### ISSUE THREAD

**Issue by eneskaya** [laravel/framework#9705]
In the `validation.php` you can set pretty names for custom validation attributes. For example, you could have a filed in your form with the name 'email' and have it replaced with 'E-Mail Address' simply by putting it in the array. However, if you use arrays in forms the name of the attribute gets not replaced.

e.g. if you have following input field...

``` html
.
.
<input type='text' name='quiz[type]' value='...'>
.
.
```
... you can access the field value through quiz.type. But the name replacement does not work.

**Comment by lukasgeiter** [comment]
How about this? (just guessing though)

    'quiz' => [
        'type' => 'Quiz type'
    ]

**Comment by eneskaya** [comment]
Oh, that really did the trick. Thank you! :smiley:
