### ISSUE TITLE
[Feature Request] Setting Default Faker Localization

### ISSUE THREAD

**Issue by vinkla** [laravel/framework#9706]
Faker supports setting the default localization when initializing the FakerFactory like this:

```php
$faker = Faker\Factory::create('fr_FR'); // Create a French faker.
```

https://github.com/fzaninotto/Faker#localization

What about adding this to either the configuration or to the environment files?

**Comment by GrahamCampbell** [comment]
I think if users want to do this themselves they can, otherwise, it's fine for them to set it in their code.

**Comment by vinkla** [comment]
Of course they can. The reason is that it isn't pretty and it would make it a whole lot easier to setup.

**Comment by GrahamCampbell** [comment]
Tests shouldn't be configured like that.

**Comment by vinkla** [comment]
No? What about adding an environment variable to the `phpunit.xml`?

**Comment by GrahamCampbell** [comment]
I still don't like the idea. For example, the base url is configured through a property in a test case. You should do the same here.

**Comment by vinkla** [comment]
Though, this is different. The factory is already registered and the generator is returned to us with the default localization. Currently we have to do something like this: 

```php
$factory->define(App\User::class, function ($faker) {

    $newFaker = Faker\Factory::create('fr_FR');

    return [
        'city' => $newFaker->city,
    ];
});
```

**Comment by vinkla** [comment]
I've opened an issue https://github.com/fzaninotto/Faker/issues/647
