### ISSUE TITLE
Database - Support for Upsert

### ISSUE THREAD

**Issue by JTallis** [laravel/framework#9713]
I'd like to see support for Upsert. Similar to Model::updateOrCreate but it does not return a Model therefore it only requires one query.

I've created a sample `Model::upsert()` however `onDuplicateKeyUpdate()` needs to be created. This sample contains `Model::upsert()`, example usage, and the resulting query. There may be better ways of handling it but as of now, this is the best I got.

    abstract class Model implements ...
    {
        public $timestamps = true;
        
        public static function upsert(array $attributes, array $values = [])
        {
            $model = static::class;
            $model = new $model;

            $update_values = $values;
            $insert_values = $attributes + $update_values;

            if ($model->timestamps == true) {
                $raw => DB::raw('NOW()');

                $update_values += ['updated_at' => $raw];
                $insert_values += ['created_at' => $raw, 'updated_at' => $raw];
            }

            static::insert($insert_values)
                ->onDuplicateKeyUpdate($update_values);
        }
    }

    class Foobar extends Model { }

    Foobar::upsert(['foo' => 75], ['bar' => 'baz']);

    // Generated query result
    INSERT INTO Foobars ('foo', 'bar', 'created_at', 'updated_at')
    VALUES (75, 'baz', NOW(), NOW())
        ON DUPLICATE KEY UPDATE bar = 'baz', 'updated_at' = NOW();

Is there ever a chance something like this would come? Seems a shame to run two queries even if you don't want to have the model returned.

**Comment by mkoterle** [comment]
Even if it doesn't get implemented you can still just extend the Model class and all of your Models can just extend the new class...

**Comment by brunogaspar** [comment]
A quick search returned this https://github.com/laravel/framework/search?q=upsert&type=Issues&utf8=%E2%9C%93 so i believe this was already requested.

**Comment by staudenmeir** [comment]
I've created an UPSERT package for all databases: https://github.com/staudenmeir/laravel-upsert
