### ISSUE TITLE
[Helpers][Proposal] asset() function should auto-detect a secure request

### ISSUE THREAD

**Issue by Binternet** [laravel/framework#9716]
I really think the helper function [asset](http://laravel.com/api/5.0/Illuminate/Contracts/Routing/UrlGenerator.html#method_asset) should have $secure = 'auto' by default. when the request is secure, it will simply alias to `secure_asset`. what do you think?

**Comment by GrahamCampbell** [comment]
It does auto-detect.

**Comment by GrahamCampbell** [comment]
Provided you've setup any trusted proxies correctly, `asset` will match the current connection type.
