### ISSUE TITLE
update the join tables, become ambiguous

### ISSUE THREAD

**Issue by zhukangfeng** [laravel/framework#9721]
php code:
DB::table('file')->join('file_owner', 'file.ower_id', '=', 'file_owner.id')-where('file_owner.id', '5')->delete()

sql：
update `file` inner join `file_owner` on `file`.`owner_id` = `file_owner`.`id` set `file`.`deleted_at`=' 2015-07-23 9:47:09`, `updated_at` = ' 2015-07-23 9:47:09' where `file_owner.owner_id` = 5

The 'updated_at' is both in table file and file_owner, and it will become ambiguous. So how can I let 'updated_at' change to 'file.updated_at'.

**Comment by zhukangfeng** [comment]
@taylorotwell Could you help me, Thank you.

**Comment by GrahamCampbell** [comment]
Issues that don't provide the laravel version will be closed.

**Comment by kdoonboli** [comment]
I have this issue. Verison 5.1
