### ISSUE TITLE
Register Logger in somewhere more logical

### ISSUE THREAD

**Issue by joshbrw** [laravel/framework#9725]
With the recent 5.1 update there's a lot more pressure to use Service Providers, so it would make sense if all the Logging was moved to a `LoggingServiceProvider` rather than `ConfigureLogging.php` where it is now

**Comment by GrahamCampbell** [comment]
> With the recent 5.1 update there's a lot more pressure to use Service Providers

I don't really agree.

**Comment by joshbrw** [comment]
@grahamcampbell I respect your opinion but I spent a long time searching for where the logger was bound.

**Comment by willrowe** [comment]
I spent awhile looking at this as well and came to the conclusion that it's better to register the logger as early as possible, which means that it can't be registered at the same time as the other service providers since that would be too late.
