### ISSUE TITLE
whereHas with belongsToMany relationship not working properly

### ISSUE THREAD

**Issue by GarryOne** [laravel/framework#9726]
I have table a "tasks" with self referencing. I need to use whereHas method from Eloquent. First, I used just parent_id column in the same table, but I was getting empty model. I have read that this is a issue and was fixed just in Laravel 5. In this case, I created I pivot table, "task_dependency", with two columns: "task_id" and "parent_id". These are the realtionships in the Task Model

```
public function parent()
{
 return $this->belongsToMany('Task', 'task_dependency', 'task_id', 'parent_id');
}

public function children()
{
 return $this->belongsToMany('Task', 'task_dependency', 'parent_id', 'task_id');
}
```
But I didn't get rid of all problems. This code:
```
Task::whereHas('parent', function($q) {
    $q->where('status', 4);
})
```
generates the below query: 
```
select * from `tasks` where `tasks`.`deleted_at` is null and 
(select count(*) from `task_dependency` as 
`self_25523d38deca8ac023c5241dc6c5de6e` where 
`self_25523d38deca8ac023c5241dc6c5de6e`.`task_id` = `tasks`.`id` and 
`status` = '4' and `tasks`.`deleted_at` is null) >= 1
```
Which doesn't return the corect results. It returns no rows, even if the parent task has status 4. How can I rezolve this problem? Thank you.

**Comment by GrahamCampbell** [comment]
Issues that don't provide the laravel version will be closed.

**Comment by GarryOne** [comment]
"I have read that this is a issue and was fixed just in Laravel 5"
It's not enough to understand about which version it's talking about? And what is your purpose, to get rid of problems as many as possible, with this approach?

**Comment by GrahamCampbell** [comment]
You need to say "5.1.8". "5" is no use to use.

**Comment by GarryOne** [comment]
Ok, it's 4.2.17
Now I have to open another topic or you can reopen current topic?

**Comment by GrahamCampbell** [comment]
> Ok, it's 4.2.17

Only 5.1.8 is supported. Don't open another issue. Sorry.
