### ISSUE TITLE
$table->bigInteger Adds AUTO_INCREMENT

### ISSUE THREAD

**Issue by mikebronner** [laravel/framework#9727]
When running the following:

```php
        Schema::table('table_name', function ($table) {
            $table->bigInteger('field_name', 15)->nullable()->change();
        });
```

It generates this SQL command:

```sql
ALTER TABLE table_name C  
  HANGE field_name field_name BIGINT AUTO_INCREMENT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT 'field_name';
```

It probably should not be adding the AUTO_INCREMENT.

**Comment by GrahamCampbell** [comment]
Does it? Are you sure that's not the output from bigIncrements?

**Comment by mikebronner** [comment]
That's why I did a double take as well. :) I'm guessing its to do with the change() method, as there appear to be other issues with it as well.

Here's the console output:

```
[Illuminate\Database\QueryException]                                                                                                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (SQL: ALTER TABLE table_name C  
  HANGE field_name field_name BIGINT AUTO_INCREMENT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT field_name)                                                                              
                                                                                                                                                         
  [PDOException]                                                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key  
```

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
There is no "length" parameter for bigInteger, or any other integer field for that matter. Integer fields have a fixed size set by the database.

**Comment by taylorotwell** [comment]
The second parameter to the method is a booelan for autoIncrement, which you are passing > 0.

**Comment by mikebronner** [comment]
That makes sense. Is there a way to set display width of a BIGINT or INT in Schema Builder? Not hugely important, just curious.

**Comment by taylorotwell** [comment]
No I don't think there is a way to set that currently.

**Comment by linmufeng326** [comment]
in vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php  line564:
  `return $this->addColumn('bigInteger', $column, compact('autoIncrement', 'unsigned'));`
Modified into
  `return $this->addColumn('bigInteger', $column, compact($autoIncrement, $unsigned));`
it's ok,but this is the wrong it?
