### ISSUE TITLE
Mocking Cache Facade Throws Protected Function Error

### ISSUE THREAD

**Issue by loren138** [laravel/framework#9729]
I'm using the code from http://laravel.com/docs/5.1/testing#mocking-facades

IE 

        Cache::shouldReceive('get')
            ->once()
            ->with('key')
            ->andReturn('value');`

However, when I run this through PHPUnit I get the following error:

    1) App\Models\GoogleAnalyticsTest::testCacheMohlerPopularUris
    InvalidArgumentException: get() cannot be mocked as it a protected method and mocking
    protected methods is not allowed for this mock

    /Users/../Sites/resources/vendor/mockery/mockery/library/Mockery.php:670
    /Users/../Sites/resources/vendor/mockery/mockery/library/Mockery.php:678
    /Users/../Sites/resources/vendor/mockery/mockery/library/Mockery.php:629
    /Users/../Sites/resources/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:54
    /Users/../Sites/resources/tests/Api/GoogleAnalyticsTest.php:22

The error makes perfect readable sense to me, but the problem is I need to mock the cache get function which happens to be exactly documented and it doesn't work...

I've also tried a trick that worked in 4.2 with using swap to place a Mocked class into a facade that doesn't work.  (The original cache class still gets called rather than the mock that I'm swapping in.)  That code is:

    public function testCacheMohlerPopularUris()
    {
        $original = \Cache::getFacadeRoot();
        $cache = \Mockery::mock('\Illuminate\Cache\Repository');
        \Cache::swap($cache);
        $ga = \Mockery::mock('App\Models\GoogleAnalytics[mohlerPopularUris]');
        
        $cache->shouldReceive('get')->withArgs(['mohlerPopularUris', 'miss'])->once()->andReturn('miss2');
        $ga->shouldReceive('mohlerPopularUris')->once()->withNoArgs()->andReturn([1]);
        $cache->shouldReceive('put')->withArgs(['mohlerPopularUris', [1], 30])->once();

        \Cache::swap($original);
        $this->assertSame([1], $ga->cacheMohlerPopularUris());
    }

**Comment by GrahamCampbell** [comment]
You can't mock a manager class like that I'm affraid. The get call there is a __callStatic followed by a __call.

**Comment by loren138** [comment]
Once again, let me point out that this call is copied EXACTLY from the documentation on mocking a facade: http://laravel.com/docs/5.1/testing#mocking-facades and is the entire point of mocking them.  I shouldn't need to argue that this should work since Taylor in the docs says consider that you want to do this. Just to make this easier for you I'm copying the docs to here.

Mocking Facades (http://laravel.com/docs/5.1/testing#mocking-facades)

When testing, you may often want to mock a call to a Laravel facade. For example, consider the following controller action:

	<?php

	namespace App\Http\Controllers;

	use Cache;
	use Illuminate\Routing\Controller;

	class UserController extends Controller
	{
		/**
		 * Show a list of all users of the application.
		 *
		 * @return Response
		 */
		public function index()
		{
			$value = Cache::get('key');

			//
		}
	}

We can mock the call to the Cache facade by using the shouldReceive method, which will return an instance of a Mockery mock. Since facades are actually resolved and managed by the Laravel service container, they have much more testability than a typical static class. For example, let's mock our call to the Cache facade:

	<?php

	class FooTest extends TestCase
	{
		public function testGetIndex()
		{
			Cache::shouldReceive('get')
						->once()
						->with('key')
						->andReturn('value');

			$this->visit('/users')->see('value');
		}
	}

**Comment by tillkruss** [comment]
@taylorotwell This should be removed from the docs.

**Comment by ctrlaltdylan** [comment]
Why is this issue closed when there hasn't been a viable solution yet?

**Comment by abrahamgreyson** [comment]
Issue moved to [laravel/echo #1](https://github.com/laravel/echo/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by kirkbushell** [comment]
Because the underlying instance of the facade has a protected get method - which you cannot mock. Why was it moved to echo, btw? It doesn't belong there.

**Comment by loren138** [comment]
No, idea, I was really confused with my emails this morning.

The documentation for mocking facades still includes this method which doesn't work....
https://laravel.com/docs/master/testing#mocking-facades

Should someone make a new task to fix the docs or is that purposely being left as is?
(Also, it would be great to be able to test methods that are supposed to cache things/use cached things without actually caching or deleting caches to make them follow a particular route.)

**Comment by tillkruss** [comment]
Did you see this commit? https://github.com/laravel/framework/commit/8a2a2d5d9102ecab0cd4a69ffc073f09f03760e1

**Comment by loren138** [comment]
No I didn't.  I just assumed from https://github.com/laravel/framework/issues/9729#issuecomment-182513083
Just tested it though and it works now!  Thanks! :)
For others, this is fixed on v5.2.31+ and v5.1.24+
