### ISSUE TITLE
Bug: Migration unique error

### ISSUE THREAD

**Issue by ziming** [laravel/framework#9730]
Hi,

I'm not exactly sure why but after running composer update today, I realised that I can no longer seed seed data if my field has something like

```
$table->string('username')->unique();
```

I need to remove unique() from my migration files in order for my seeding to work. My seeder file should be unique as it has not been updated for many days and previous seedings before today has been working too.

**Comment by blacklizard** [comment]
@ziming you should clear your table first before seeding again since username field is unique

**Comment by ziming** [comment]
I did clear them, even re-run migrations then seed again.

**Comment by ziming** [comment]
The other issue noticed was that if I seed just that class Alone (delete all rows of that table before doing so), seeding works for that table works.

**Comment by ziming** [comment]
Hi just to update, turns out it's caused by another laravel package. Apologies.
