### ISSUE TITLE
factory() method persists random number of entities

### ISSUE THREAD

**Issue by kfirba** [laravel/framework#9734]
EDIT:
====

The issue was not caused by laravel but by a 3rd package that I was using. Sorry for that.

**Comment by lukasgeiter** [comment]
Then just close the issue :)

**Comment by kfirba** [comment]
@lukasgeiter I'm not sure how to do so :hushed:

**Comment by lukasgeiter** [comment]
I believe at the bottom besides the comment button there should be one to close it.

**Comment by kfirba** [comment]
@lukasgeiter oh lol how come I didn't see it :joy: Thanks.
