### ISSUE TITLE
Testing: seeJsonContains is not aware of variables types

### ISSUE THREAD

**Issue by kfirba** [laravel/framework#9735]
Hello.

I've noticed that some of my tests which contains `seeJson()` or `seeJsonContains()` are failing because they are not aware of variable types. For example, when I authenticate a user I return a token with the user id. So in my test I do something like:

```php
$user = $this->createPredictableRegularUser();

$this->post('authenticate', [
            'email' => 'john@example.com',
            'password' => 'password'
        ])
            ->seeStatusCode(200)
            ->seeJson(['user_id' => $user->id]);
```

the `$user->id` is an integer but when it's trying to match it with the response, it's trying to match the right form of the value which is what I requested in the `seeJson()` method:

```
"user_id": 71
```

with the wrong value where the ID has became a string:

```
"user_id": "71"
```

and since it uses a `str_contains` method it simply fails because of the double-quotes.

I've tested the response of my application with both Postman and Curl and they both return the ID as an integer which means that the test has somewhere converted it to string.

**Comment by fire015** [comment]
That's correct behaviour, not a bug. The whole point of tests are to check everything matches, including data type!

**Comment by kfirba** [comment]
@fire015 Exactly.. it is not aware of the data type... If I check the response from postman or curl I can clearly see that the ID is a number but when it's trying to assert in tests it somehow converts to string...

**Comment by devsalman** [comment]
hmm.. are you sure? i have tested it myself. i have json response like this:

```javascript
{"status_msg":"OK","timestamp":1437810483,"data":{"subactivity_id":1,"new_status":"done","new_progress":"done"}}
```
and then i try to assert it using `seeJson()` like this:

```php
$this->post('sub_activity/change_progress', $requestData)
            ->seeStatusCode(HTTPCode::STATUS_OK)
            ->seeJson(['subactivity_id' => 1]);
```
the test is pass

but, when i add quote in subactivity_id like this:

```php
$this->post('sub_activity/change_progress', $requestData)
            ->seeStatusCode(HTTPCode::STATUS_OK)
            ->seeJson(['subactivity_id' => '1']);
```
the test is failed. so, its aware of the data type.

**Comment by kfirba** [comment]
@devsalman I'm not sure what to say then... It's a proven fact that my tests returns the ID as string and Postman/Curl return it as integer
