### ISSUE TITLE
CSRF Protection: inconsistency between frameworks

### ISSUE THREAD

**Issue by tortuetorche** [laravel/framework#9737]
The [CSRF Protection](http://laravel.com/docs/5.1/routing#csrf-protection) of Laravel appears to be inspired by the [Ruby on Rails one](http://guides.rubyonrails.org/v4.2.3/security.html#csrf-countermeasures).

But [this code](https://github.com/laravel/framework/blob/v5.1.8/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L81) doesn't reflect the CSRF protection [behaviour](https://github.com/rails/rails/blob/v4.2.3/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L254) of Ruby on Rails.

We should compare `$request->session()->token()` with `$request->input('_token') ` **and** if it doesn't match, we should compare the `$request->session()->token()` with `$request->header('X-CSRF-TOKEN')`.

For a real world use cases: If on your page you have a `<form>` cached with an outdated `csrf_token()`.
When you submit the form, the CSRF protection will check matching tokens with the outdated CSRF token then it will thrown an `TokenMismatchException`.
But the HTTP header `X-CSRF-TOKEN` sent to the server is good, so we should check matching tokens with it before throwing an exception.

PS: I know my explanations are a bit confusing, just tell me if you want more clarifications.

**Comment by spencerdeinum** [comment]
I'm trying to think of when you would have a an invalid `_token` from the form but a valid `X-CSRF-TOKEN`.

I see that the rails one will fall through `||` to check both but I'm not really sure if I understand the use case.

**Comment by GrahamCampbell** [comment]
I don't think we need to change anything, and anything we did change would be breaking.
