### ISSUE TITLE
Improvement/Correction: Replace count() functions with empty() in some if-statements

### ISSUE THREAD

**Issue by DanielStuttgart** [laravel/framework#9738]
Since Taylor rejected my PR #9672 because it "only" improves code, makes use of the correct functions and was too big for him to see the simple changes that were made I will create an issue for the improvement here.

If Taylor is so passionate about the DocBlocks in Laravel, why not with the functions too?

However, my issue here requests the replacement of count() functions in if-statements. It's a bit stupid to count items if you don't even care how many there are and just want to know if anything is given.

The correct function for that is: empty()

Even if this change only results in < 1ms performance boost at the end of the day (it could be a bigger improvement, no benchmarks were made), it still is the correct and logic way to code!

Change it please, elsewise you got nice DocBlocks and crappy code. And we want both the be nice, right? :)

**Comment by phanan** [comment]
Just curious, why do we need `empty()` or even `count()` for most of these cases? A simple `if ($array)` would do just fine, and is even faster according to the mentioned benchmark.

**Comment by DanielStuttgart** [comment]
You're right! count() is retarded, empty() is a bit less retarded and the most direct way to check it would be your solution. Damn I didn't see the wood for the trees :D
