### ISSUE TITLE
Migration tries to set first integer as primary key

### ISSUE THREAD

**Issue by rimace** [laravel/framework#9739]
Hi guys!

I have a really strange behavoir in with my migrations. First this is my code (very simple):
```php
Schema::create('activities', function(Blueprint $table) {
	$table->string('id')->primary();
	$table->integer('supplier_id')->nullable();
});
```
What happens is that the primary key is set to the first integer field, supplier_id in this case. After that it tries to alter the table and set the primary key to the id field with (of course) the following error:
```
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (SQL: alter table `activities` add primary key activities_id_primary(`id`))
```
I am using the current version 5.1.8. Can anyone approve this behavior?

**Comment by GrahamCampbell** [comment]
The error here is from a different migration.
