### ISSUE TITLE
Optional route prefix parameters or RegEx

### ISSUE THREAD

**Issue by vedmant** [laravel/framework#9741]
Hello!
I encountered quite noticeable inconvenience with optional routes prefixes. For example when URI can be "/auth/register" for default language (English) and "/de/auth/register" for German. I need to use language prefix, but it's optional and needs to be captured only if it's one from allowed languages list.

I have moved from Kohana framework, and it's quite simple implemented there:

    Route::set('default', '(<lang>/)(<controller>(/<action>(/<id>)))', array('lang' => $allowed_langs))
        ->defaults(array(
            'lang'       => $default_lang,
            'controller' => 'landing',
            'action'     => 'index',
        ));

But with Laravel I have to do this workaround to make it work:

    $lang = Request::segment(1);
    if (in_array($lang, ['de','zh'])) {
        App::setLocale($lang);
    } else {
        $lang = null;
    }

    Route::group(['prefix' => $lang], function () {

    });

It would be great if prefix can take parameters:

    Route::group(['prefix' => '{lang?}' =>, 'middleware' => 'locale'], function () {

    })->where(['lang' =>  ['de', 'zh']]);

So it captures prefix only if one of parameters match. Or if it matches Regex pattern:

    Route::group(['prefix' => '{lang?}', 'middleware' => 'locale'], function () {

    })->where(['lang' =>  'de|zh']);

If it doesn't capture prefix it passes URI to the group as it is.

I think it's not hard to implement, but it can save our souls when we have to work with optional prefixes.

Thank you!

**Comment by GrahamCampbell** [comment]
Closing due to lack of interest.

**Comment by dmdnkv** [comment]
I wonder whether you've found more elegant solution for catching the lang from route prefix than this workaround or not?

**Comment by vedmant** [comment]
Something like this:

    Route::group(['prefix' => Translation::getRoutePrefix(), 'middleware' => ['locale']], function() {
    
    });

Where Translation::getRoutePrefix() checks if prefix matches one of locales, or if no, returns null. I use helper from stevebauman/translation package.

**Comment by AidasK** [comment]
@vedmant This solution is not working with route cache. Is there any other options?

**Comment by vedmant** [comment]
@AidasK For routes caching I think you will need to generate every possible route for all languages in a loop. Something like this

    foreach ($languages => $lang) {
        Route::group(['prefix' => $lang, 'middleware' => ['locale']], function() {

        });
    }

I'm not sure if it's going to work though.
