### ISSUE TITLE
 [BadMethodCallException] Call to undefined method Illuminate\Database\Query\Builder::posts() 

### ISSUE THREAD

**Issue by connorjburton** [laravel/framework#9742]
Not sure if this intended, however when we are seeding our Users table with the factory method. See the gist here that throws the error:

https://gist.github.com/connorjburton/cd8e914b89a8b11900ad

The function that throws the error is in Database/Query/Builder.php

     __call($method, $parameters)

Which seems to always throw an error?

Cant find anything on Google regarding this so wondering if it's a known issue or not an issue at all and we are just missing something.

**Comment by GrahamCampbell** [comment]
Looks like you haven't set up a posts relation.

**Comment by GrahamCampbell** [comment]
Please ask on the forums if you need any help, and I'm sure someone can help you there. :)
