### ISSUE TITLE
[5.1.8] Testing redirections, never asserted because of followRedirects()

### ISSUE THREAD

**Issue by mjpvandenberg** [laravel/framework#9743]
If someone visits my root URL unauthenticated, he will be redirected to a login page. The following test passes successfully:

```php
$response = $this->call('GET', '/');
$this->assertEquals(302, $response->getStatusCode());
$this->assertInstanceOf('Illuminate\Http\RedirectResponse', $response);
$this->assertEquals($this->baseUrl . '/auth/login', $response->getTargetUrl());
```

But now this (which I would expect to be semantically the same) fails:

```php
$this->visit('/')
     ->assertRedirectedTo($this->baseUrl . '/auth/login');
```

with the following message: `Failed asserting that Illuminate\Http\Response Object (...) is an instance of class "Illuminate\Http\RedirectResponse".`

That's because `CrawlerTrait::makeRequest` calling `followRedirects` makes sure in the test case we always end up with the final response after redirection. 

I assume this automatic redirection-following of `makeRequest` is intentional behavior, and in most cases appropriate, although an easy way to disable it would be nice. But I wonder, is this intentional behavior of `TestCase::assertRedirectedTo`? Does it ever pass, if calling it is only possible after all redirection is done?

**Comment by GrahamCampbell** [comment]
This intended.

**Comment by GrahamCampbell** [comment]
What you want is something like this: https://github.com/BootstrapCMS/CMS/blob/master/tests/BasicTest.php#L33.

**Comment by GrahamCampbell** [comment]
That tests that when i hit the root url, i get redirected to another page.

**Comment by davo3** [comment]
@GrahamCampbell , what is the reason that this is an intended behavior ?
