### ISSUE TITLE
Typehint \StdClass in DatabaseQueue constructor

### ISSUE THREAD

**Issue by jakeengrade** [laravel/framework#9744]
Hi,

Just stumbled across this:

https://github.com/laravel/framework/blob/a423a55ed6601daebcbb75817de6d06b4d670a70/src/Illuminate/Queue/Jobs/DatabaseJob.php#L34

$job is treated as an object immediately but not typehinted as such.

Thanks.

**Comment by GrahamCampbell** [comment]
Type hinting standard class would be totally wrong.

**Comment by GrahamCampbell** [comment]
PHP has no way to typehint to say you want any object.

**Comment by jakeengrade** [comment]
My mistake, sorry, I thought that this constructor should only accept that type.

Is there any way you can wrap it in an is_object()? There are cases when an array gets passed to this constructor (for instance DatabaseQueue::getNextAvailableJob() can return an array or an stdClass depending on whether PDO's fetch mode is set to PDO::FETCH_OBJ or not).
