### ISSUE TITLE
During insert, set a flag on the model

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#9745]
When doing a `firstOrCreate`, it comes up frequently that I'd like to return a 201 when the action resulted in an insert.  It would be nice if a flag existed on model subclasses that allowed me to infer if a model with  `exists == true` was *also* created during the current request.

**Comment by rickywiens** [comment]
+1

**Comment by bmartel** [comment]
+1

**Comment by GrahamCampbell** [comment]
Further discussion can take place on the PR if required.
