### ISSUE TITLE
Extend QueryBuilder discussion

### ISSUE THREAD

**Issue by ash-rain** [laravel/framework#9749]
Is there some way to hook in the query execution flow? I can't seem to find a way to properly extend the QueryBuilder class and what I really want is to put a condition on all `insert`/`update` queries.
Also, I want to post-process `select` results but I managed to do that in a clean way with a `Processor`.
I start to wonder if I am the first to want to make something like this :)) I'm getting desperate, I don't want to override the whole database manager.

**Comment by ash-rain** [comment]
I ended up using my own DatabaseManager and Connection(s).
I had a weird moment when I tried to use it from the facade but DB::clearResolvedInstances() did the trick.
Thanks for a great discussion. You're welcome.

**Comment by pilot911** [comment]
Can you explain how to extend query builder

**Comment by ash-rain** [comment]
@pilot911 Check out this implementation for reference. Start with "multilang.php"
https://github.com/microweber/microweber/tree/multilanguage/userfiles/modules/multilang/Laravel

**Comment by pilot911** [comment]
Thanks. I extended via replacing

```
    public function registerDBConnection()
    {
        foreach([
                'mysql' => 'MySql',
                'pgsql' => 'Postgres',
                'sqlite' => 'SQLite',
                'sqlsrv' => 'SqlServer',
            ] as $key => $driver)
        {           
            $this->app->singleton('db.connection.' . $key, function ($app, $parameters) use ($driver)
            {
                list($connection, $database, $prefix, $config) = $parameters;

                $class = '\App\Telenok\Core\Interfaces\Database\Connection\\' . $driver . 'Connection';

                return new $class($connection, $database, $prefix, $config);
            });
        }
    }
```
