### ISSUE TITLE
Broadcast Events do not have option to select queue name.

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/framework#9750]
I'm currently using the broadcast events feature of 5.1 with Socket.io. It's working well...BUT

As per the docs with broadcast events:

> [Queue Prerequisites](http://laravel.com/docs/5.1/events#broadcast-configuration)
>Before broadcasting events, you will also need to configure and run a queue listener. All event broadcasting is done via queued jobs so that the response time of your application is not seriously affected.

This of course means we have to use a queue. The default queue name will be set in `config/queue.php`.

With a normal job (i.e. not a broadcast event) that gets pushed to the queue with the `ShouldQueue` trait, there is an option of assigning what queue name you would like to push to:

>[Specifying The Queue For A Job](http://laravel.com/docs/5.1/queues#pushing-jobs-onto-the-queue)
>You may also specify the queue a job should be sent to.
>[snip]To specify the queue, use the onQueue method on the job instance. The onQueue method is provided by the base App\Jobs\Job class included with Laravel:

Code example:
```php
 $job = (new SendReminderEmail($user))->onQueue('emails');
```

As I am not completely "at one" with intricacies of the Laravel, I had a look at the source code and this is what I could determine.

The `Illuminate\Bus\Dispatcher.php` class has a check when running its `dispatchToQueue` method to see if there's been a specified queue-name. If there is, it gets used otherwise it gets set to the default.

```php
    public function dispatchToQueue($command)
    {
        $queue = call_user_func($this->queueResolver);

        if (!$queue instanceof Queue) {
            throw new RuntimeException('Queue resolver did not return a Queue implementation.');
        }

        if (method_exists($command, 'queue')) {
            $command->queue($queue, $command);
        } else {
            $this->pushCommandToQueue($queue, $command);
        }
    }
```

However in the `Illuminate\Events\Dispatcher.php`, there is NO check for any custom queue name when the Broadcast Event is being sent to the queue:
```php
    protected function broadcastEvent($event)
    {
        if ($this->queueResolver) {
            $connection = $event instanceof ShouldBroadcastNow ? 'sync' : null;

            
            $this->resolveQueue()->connection($connection)->push('Illuminate\Broadcasting\BroadcastEvent', [
                'event' => serialize($event),
            ]);
        }
    }
```

Finally to my points:

Say I have 100 jobs in my default queue and as they start processing they each generate a Broadcast event to update the user on how things are going.

It was my plan to send these Broadcast events to their OWN queue so that they could be processed quickly and not get "caught-up" by being placed at the end of the default queue with the other jobs being processed ahead. I can't do this at the moment because I can't set the queue name for the broadcast events to be sent to.

I could change the queue name for the original jobs, but then I have to remember everytime I want to queue something else (mail etc), not to use the default queue name as there could be broadcast events in there I want to process first.

Questions:
1) Have I understood all this correctly?

2) Is it sensible to suggest a similar check in the `broadcastEvent` method that looks to see if a queue name has been set on an event and use that instead of the default?

3) I don't know how to do unit testing, so I'm fearful of sending a PR in because I can't back it up with proof it works. (Yes I know I need to learn but I haven't so far.) I've written my own check here locally and it all seems to work well, but see the beginning of point 3 again :)

Thanks for sticking with the long post.

**Comment by GrahamCampbell** [comment]
Perhapse a PR?

**Comment by jonnywilliamson** [comment]
Sure if you could answer question 2 at the bottom of my post?

**Comment by GrahamCampbell** [comment]
Maybe yeh. Details can be discussed on the PR though.

**Comment by jonnywilliamson** [comment]
@kinologik - Thanks for the verification of the issue.

Good news is that I have a 2 line PR about to be sent that allows us the ability to send the event job to a named queue.

I should have it done tomorrow.

**Comment by kinologik** [comment]
@jonnywilliamson - Fantastic. I'll keep monitoring my queue with Beanstalk-Console while I go forward with my project, and wait for this update for a proper way to include the Broadcasting Events in it. Very much appreciated. I will have a last try, this time using the DispatchesJobs trait when I call the Event from my Job script. Might worth having a look...

**Comment by jonnywilliamson** [comment]
@kinologik PR has been sent. This would allow you to send all broadcasts to a specific queue and then you could use a dedicated worker to process just those jobs.

Also don't forget about the `ShouldBroadcastNow` interface instead of `ShouldBroadcast`. Might work for you.

**Comment by kinologik** [comment]
@jonnywilliamson - I tried the updated broadcastEvent function using the following code:

    $myEvent = (new MyBroadcastingEvent($param))->onQueue('anotherQueue');
    Event::fire($myEvent);

But kept receiving the following error:

    Missing argument 1 for App\Events\MyBroadcastingEvent::onQueue()
        defined in /w3/test/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php:27
        called in /w3/test/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 257

I thought I missed something and tried different variations to fire up the Event, but I kept getting the same error.

I finally looked back at the PR, and noticed that you were using the `onQueue()` method to retrieve the queue name. The problem is `onQueue()` is a setter:

http://laravel.com/api/5.1/Illuminate/Bus/Queueable.html#method_onQueue

And calling this method without an argument will return the error I mentioned above.

I changed line 257 in `src/Illuminate/Events/Dispatcher.php` from:

    $queue = method_exists($event, 'onQueue') ? $event->onQueue() : null;

to this:

    $queue = method_exists($event, 'onQueue') ? $event->queue : null;

Et voilà! Now, everything works as advertised! :D 

Thank you for pointing me in the right direction. I would have never figured it out by myself. Have an awesome weekend.

**Comment by jonnywilliamson** [comment]
@kinologik. MMmm no, something isn't right with the way you've written some of your code (I think).

If you follows the docs, or create a brand new event `artisan make:event demo` You'll get this file:

```php
<?php

namespace App\Events;

use App\Events\Event;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class demo extends Event
{
    use SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the channels the event should be broadcast on.
     *
     * @return array
     */
    public function broadcastOn()
    {
        return [];
    }
}

```

All you are requested to do is to implement the `ShouldBroadCast` interface:

```php
class demo extends Event implements ShouldBroadcast
{
```


After Taylor's  [request](https://github.com/laravel/framework/pull/9869#issuecomment-128693273), I changed the method name to `onQueue()`.


Only the `Queueable` trait has that method name (`onQueue`) already in use and that trait is not used in the event class (see above code).


All you should have to do is add the following code/method to your event class and you're set.

```php
    /**
     * Get the name of the queue the event should be placed on.
     * 
     * @return string
     */
    public function onQueue()
    {
        return 'broadcastqueue';
    }

```

The reason you DON'T want the `onQueue()` method to be a setter is that if there is a public property in the class, that will be sent as DATA when the event is fired. This is probably not a good idea. ([see docs](http://laravel.com/docs/5.1/events#broadcast-data))


=====
So whilst inside the `Queueable` trait, the method `onQueue` SETS a public property called `$queue`, the `onQueue()` method inside an event does not.

Wither this is a good idea or not I do not know. But I think you might have accidentally added a `uses Queueable` in your event class by mistake.

Hopefully that's as clear as mud.

**Comment by kinologik** [comment]
@jonnywilliamson - I guess you are right. I tried so many thing to get my queues to work independently in the last 10 days or so that my code is all over the place. It works, but it might not be as legit as it should.

I'll try again this weekend from a fresh install and see how it goes. Thanks again for your reply. It is most helpful.

**Comment by PoTHuYJoHN** [comment]
My solution about this issue:
https://medium.com/@ivankolodiy/how-to-prioritize-queues-in-laravel-5-3-events-149001dec2c7#.jphvg7uvo

Can be helpful for someone

**Comment by brnmonteiro** [comment]
Look a simple solution here: [stackoverflow](http://stackoverflow.com/a/43347790/2140095) 👌🏼
