### ISSUE TITLE
[5.1]Extending Mail Transport

### ISSUE THREAD

**Issue by stevenyangecho** [laravel/framework#9751]
trying adding some other Mail Transport.
guess can be done by app['swift.transport']->extend();

but in the /laravel/framework/src/Illuminate/Mail/MailServiceProvider.php
shows  the 'swift.transport' only been registed after 'mailer' registed.
but the 'mailer' register will instant the 'swift.transport'  via
return new Swift_Mailer($app['swift.transport']->driver());

so seems cant extending mail transport?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by stevenyangecho** [comment]
oh,its the logic problem  of code
