### ISSUE TITLE
[docs] authentication.md authenticate() method missing Request parameter

### ISSUE THREAD

**Issue by milosivanovic** [laravel/framework#9752]
There is an error in the documentation (authentication.md to be exact), in the section that describes custom authentication methods.

The following snippet:

	public function authenticate()
	{
		if (Auth::attempt(['email' => $email, 'password' => $password])) {
			// Authentication passed...
			return redirect()->intended('dashboard');
		}
	}

should be

	public function authenticate(Request $request)
	{
		if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
			// Authentication passed...
			return redirect()->intended('dashboard');
		}
	}

along with the addition of `use Illuminate\Http\Request;` otherwise the variables `$email` and `$password` are not set and result in "undefined variable" errors.

**Comment by Sladewill** [comment]
https://github.com/laravel/docs/blob/5.1/authentication.md

You could submit a pull request to there to get it fixed.
