### ISSUE TITLE
"Class name must be a valid object or a string" php configuration ?

### ISSUE THREAD

**Issue by isbkch** [laravel/framework#9754]
I'm getting this error on my prod server when I call a method that uses belongsToMany():

```
FatalErrorException in Model.php line 936:
Class name must be a valid object or a string
in Model.php line 936
```

What I find strange is that the same code, shows no error on my local dev vagrant (both run on Debian, uses Laravel 5.1 and the same LAMP stack)

Is this could be related to some kind of php conf directive ?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
