### ISSUE TITLE
Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by JamborJan** [laravel/framework#9755]
## Preconditions
I am packaging an app called [Paperwork](https://github.com/twostairs/paperwork) which has been created with the Laravel Framework for a platform called [Sandstorm](https://github.com/sandstorm-io/sandstorm). I first have build the package with Docker and now switched to Vagrant for that. I have a problem migrating old instances of the package which have been created with Docker to the new version.

## Issue related to the Laravel Framework
At one point an error from the Laravel Framework is shown which indicates an issue with the MySQL connection or the database elsewhere but instead of showing a helpful SQL error a "Class not found" error is shown.

## How to reproduce the issue
Take an existing app with database and rename a random used table to something else.

## Expected behavior
The raised error should show a message like "table xyz not found" or something else helpful should be shown, like "advertised" in the code:
```
// If an exception occurs when attempting to run a query, we'll format the error
// message to include the bindings with SQL, which will make this exception a
// lot more helpful to the developer instead of just the database's errors.
```

## Current behavior
The following message appears which doesn't help to track down the root cause:

```
 /opt/app/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php 
```
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class 'Illuminate\Database\QueryException' not found
```
```
		}
 
		// If an exception occurs when attempting to run a query, we'll format the error
		// message to include the bindings with SQL, which will make this exception a
		// lot more helpful to the developer instead of just the database's errors.
		catch (\Exception $e)
		{
			throw new QueryException(
				$query, $this->prepareBindings($bindings), $e
			);
```

I guess that the class ```QueryException``` is a component of the Laravel Framework which has been changed or doesn't work as expected.

Can you please help me with that? Am I guessing right or is the cause of the not so good fatal error exception not based in the Laravel Framework?

FYI: a screen shot of the error message:
![bildschirmfoto 2015-07-26 um 16 18 09](https://cloud.githubusercontent.com/assets/7508960/8894318/357cbc62-33a1-11e5-81f8-811329c9af07.png)

**Comment by GrahamCampbell** [comment]
Laravel 4.2 is not supported, sorry.

**Comment by JamborJan** [comment]
It would be nice to have at least a useful hint like "upgrade to the latest framework". A "We are not helping" response is pretty lame.

**Comment by JamborJan** [comment]
FYI, if anybody else has an older version of the framwork and gets an issue:

Add in ```/Volumes/2rockRAID5/Eigene/Development/paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connection.php``` this line at the beginning:

``` 
use Illuminate\Database\QueryException;
```

![bildschirmfoto 2015-07-28 um 13 44 03](https://cloud.githubusercontent.com/assets/7508960/8930487/bbcdf78e-352e-11e5-85e5-aafb291ef4c6.png)

After having done that you get a proper error message and can start debugging.

**Comment by itsyahyaa** [comment]
// try this Way


<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserTable extends Migration
{

    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('role_id')->unsigned();
            $table->string('name');
            $table->string('email',50)->unique();
            $table->string('username');
            $table->string('password');
            $table->boolean('active');
            $table->rememberToken();
            $table->timestamps();

        });
    }

    public function down()
    {
        Schema::dropIfExists('users');
    }
}

**Comment by lk77** [comment]
this is a very old issue that was closed nearly 6 years ago

**Comment by Temur23112003** [comment]
Zo'r gap yo'q malades bosing endi
