### ISSUE TITLE
Can't redirect from RouteServiceProvider

### ISSUE THREAD

**Issue by Merujan99** [laravel/framework#9757]
I want to redirect from RouteServiceProvider, if user not authenticated. But redirect function doesn't work. fix it

![screenshot from 2015-07-26 23 28 09](https://cloud.githubusercontent.com/assets/4623322/8895491/a287252e-33e5-11e5-901d-ab7fc2519df7.png)

**Comment by GrahamCampbell** [comment]
You should NEVER call the `header` function.

**Comment by GrahamCampbell** [comment]
Please ask for support on the forums.

**Comment by Merujan99** [comment]
it doesn't matter, Issue is opened, for redirect function

**Comment by GrahamCampbell** [comment]
The redirect stuff works fine, sorry. Please ask for support on the forums.

**Comment by Merujan99** [comment]
Dear Friend. redirect stuff will work fine, if I redirect example from Controllers. but in this provider, I'm binding to post value {slug}, and checking for auth. and I want to redirect. it doesn't work.

**Comment by lukasgeiter** [comment]
This is not supposed to work that way. You can't just return a response from a model binding. It is expected that you return the model itself. To handle errors you should throw an exception and handle that globally.
