### ISSUE TITLE
Illuminate\Session\Store method 'migrate' parameter 'lifetime' doesn't have any effect

### ISSUE THREAD

**Issue by HolgerW1** [laravel/framework#9758]
The *lifetime* parameter of Illuminate\Session\Store::migrate currently doesn't have any effect and is not used at all:

```
    public function migrate($destroy = false, $lifetime = null)
    {
        if ($destroy) {
            $this->handler->destroy($this->getId());
        }

        $this->setExists(false);

        $this->id = $this->generateSessionId();

        return true;
    }
```

It should actually either have the documented effect as defined by the Symfony *SessionInterface* (see below) or the documentation for this method should be changed and not inherited.
> Sets the cookie lifetime for the session cookie. A null value
> will leave the system settings unchanged, 0 sets the cookie
> to expire with browser session. Time is in seconds, and is
> not a Unix timestamp.

**Comment by GrahamCampbell** [comment]
We deal with lifetime through the handlers. We can't really change that, sorry.
