### ISSUE TITLE
Validation rule "exists" does not work with custom database connection

### ISSUE THREAD

**Issue by Pr00f** [laravel/framework#9759]
Validation rule "exists" does not work with custom database connection

My rules:
```
public function rules()
{
	return [
		'name' => 'required|alpha_dash|min:3|max:32|exists:db2.users',
	];
}
```

When I submit form, I get this error:
> local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db2.users' doesn't exist' in \vendor\laravel\framework\src\Illuminate\Database\Connection.php:309

I checked `getExistCount()` function in \vendor\laravel\framework\src\Illuminate\Validation\Validator.php, and there is no `$verifier->setConnection($connection)` method, like in `validateUnique()`.

**Comment by GrahamCampbell** [comment]
db2 doesn't set the connection, it sets the database name

**Comment by Pr00f** [comment]
I want use custom connection in "exists" rule, as well as in "unique" rule.
So, why "unique" work with custom connection, when i type connection name and "exists" does not work?
