### ISSUE TITLE
elixir versioning does not respect subfolders

### ISSUE THREAD

**Issue by kerbylav** [laravel/framework#9760]
When laravel app is in subfolder of domain and assets are versioned via elixir's .version() worker then elixir helper doesn't respect subfolder. It just returns plain /build/ path:

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L691

**Comment by shssoichiro** [comment]
Unfortunately this was already brought up here https://github.com/laravel/framework/issues/8565 and the response was basically that you shouldn't install Laravel in a subdirectory.

I also think `elixir()` should generate a path relative to the app root for consistency with Laravel's other helpers e.g. `asset()`, but it's not my decision.

**Comment by lukasgeiter** [comment]
FYI it was changed for Laravel 5.2 to use the `asset()` helper: #9552
(This can't be changed for 5.1 since it's a breaking change)

For a workaround until then, just add your own `elixir()` helper function that uses `asset()`

**Comment by jdrda** [comment]
I have just made a workaround - nest the elixir helper into asset in Blade this way:
{{ asset(elixir('css/style.css')) }}
It works for me
