### ISSUE TITLE
No method to observe pivot

### ISSUE THREAD

**Issue by prohalexey** [laravel/framework#9761]
Sometimes I need to observe the additional data changing in pivot table like this.
Table 1: product
Table 2: client
Table 3: client_product(client_id, product_id, quantity)
I need to have observer which looking for quantity changing. But i can't do this, because this ability is absent. So i need write some ugly code like this in a base model 
```php
public function newPivot(Model $parent, array $attributes, $table, $exists){
        switch(true){
            case $parent instanceof Client:
                $pivot_model = new ClientProductPivot($parent, $attributes, $table, $exists);
                $this->overridePivotObserve($pivot_model, new ClientProductPivotObserver);
                return $pivot_model;
```
```php
    public function overridePivotObserve($pivot_class, $observer_class, $priority = 0){
        $className = is_string($observer_class) ? $observer_class : get_class($observer_class);
        foreach ($pivot_class->getObservableEvents() as $event) {
            if (method_exists($observer_class, $event)) {
                $pivot_class->registerModelEvent($event, $className.'@'.$event, $priority);
            }
        }
    }
```
it's because of original observe method in Model.php, it make a new static instance, but __constructor of pivot class must have 4 parameters for instantiate.

I think the method "observe" of model must look and choose what we want to observe Model or Pivot.
Or we need to have some method like ObservePivot.

What do you think?

**Comment by GrahamCampbell** [comment]
This is probably not something fit for laravel's core, sorry.
