### ISSUE TITLE
[5.1] Artisan commands are not destroyed between calls?

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/framework#9762]
I dont know what the right terminology is - but is this a bug?

If I have a command inside Command A:

```
public function fire()
{
          $this->call('worker:count`);
          $this->call('worker:count`);
          $this->call('worker:count`);
}
```

Then in my `worker:count` looks like this:

```
protected $count = 0;

public function fire()
{
     $this->count = $this->count+1;
     echo $count;
}
```

I would have thought the output would be:

```
1
1
1
```

But I get

```
1
2
3
```

That doesnt seem right? It is not documented anywhere that you are re-calling the original class. It should re-initizile all variables - because you wouldnt normally be expecting them to be persistent between calls would you?

**Comment by GrahamCampbell** [comment]
This is the expected behaviour, yeh. The call function there is creating a new console kernel each time.

**Comment by TheShiftExchange** [comment]
If it is creating a new console kernel - why is the class persisting?
