### ISSUE TITLE
Elixir undefined method "registerWatcher"

### ISSUE THREAD

**Issue by Daveawb** [laravel/framework#9771]
## Elixir 3.0.5

I don't know whether Elixir ~3 is going to maintain BC with ~2 so I write this on the proviso that it is.

When registering any extension that registers watchers:

````js
var elixir = require('laravel-elixir');

elixir.extend('myExtension', function(src, options) {

    // Extension logic

    this.registerWatcher('myExtension', src);

    return this.queueTask('myExtension');
});
````
### When using Node 0.12
````
this.registerWatcher('myExtension', src);
         ^
TypeError: undefined is not a function
````

### When using Node 0.10
````
TypeError: Object function (recipe) {
    // We'll start by loading all of the available tasks.
    require('require-dir')('./tasks');

    // The user may then choose which tasks they want.
    recipe(Elixir.mixins);

    // Now that the user has requested their desired tasks
    // from the Gulpfile, we'll initialize everything!
    createGulpTasks.call(Elixir);
} has no method 'registerWatcher'
````

I will be using ^2.0.0 for the foreseeable future as a result, and may well be the conclusive answer to this issue however I thought it is worth noting here as I've seen a few people post up issues elsewhere.

**Comment by GrahamCampbell** [comment]
Please report issues with elixir on the elixir repo.

**Comment by JeffreyWay** [comment]
Dave - read the release notes for Elixir 3.

https://github.com/laravel/elixir/releases
