### ISSUE TITLE
Allow pass a ::class to second parameter of Model::belongsToMany

### ISSUE THREAD

**Issue by rentalhost** [laravel/framework#9773]
Currently, I can only pass the class name to first parameter. To second parameter, I need use `with(new UserPermission)->getTable()` (to avoid code the table name). I just think that it is a workaround. I solved this problem in my code, but I think that Laravel can do it natively.

So I thinked in two possibilities. One is accept a class name as argument (`::class`) or accept a new instance (what I think that is a workaround too, on really). So we have some cons and pros:

**Current method**: accept only the table name.

 * Parameter: use `with(new SomeModel)->getTable()`
 * Pro: anyone?
 * Cons: to verbose and is clearly a workaround.

**First possibility**: accept a class name.

 * Parameter: use `SomeModel::class`.
 * Pros: very beautiful; Laravel will fill table name based on `Model::$table` property.
 * Cons: Laravel will do it by use `class_exists()`. But only if table is specified. In falsy cases will cost more than normal.

**Second possibility**: accept a class instance.

 * Parameter: use `new SomeModel`
 * Pros: Laravel will not use `class_exists()`, just check if is `instanceof Model`
 * Cons: not too clear and not default.

```php
// File:   Illuminate\Database\Eloquent\Model.php
// Method: Model::belongsToMany

// Appended to:
if (is_null($table)) {
    /* ... */
} 

// First possibility:
else if(class_exists($table)) {
    $table = with(new $table)->getTable();
}

// Second possibility:
else if($table instanceof self) {
    $table = $table->getTable();
}
```

I suggest create a Model static method to do it on other possible places on `Model` -- where we could accept the class name instead of table name.

**Comment by lukasgeiter** [comment]
You realize that Laravel already determines the table automatically if you don't pass anything?

**Comment by rentalhost** [comment]
Yes. But in my case, I have: `users`, `permissions` and `user_permissions`. And:

```php
public function permissions()
{
    return $this->belongsToMany(Permission::class);
}
```

Laravel will try `permission_user` table instead of `users_permissions`. Maybe some setting can tweak it? 

Thanks.

**Comment by lukasgeiter** [comment]
I see... However I don't think this is a very common use case. I personally think you should just pass the table name `$this->belongsToMany(Permission::class, 'users_permissions');`

**Comment by bobbybouwmann** [comment]
Laravel is using a convention for this, in order to avoid these kind of problems. That is the reason we love framework, because these kind of problems are solved by someone else who already had this problem ;)
