### ISSUE TITLE
Routing - REQUEST_URI vs REDIRECT_URL?

### ISSUE THREAD

**Issue by mvodanovic** [laravel/framework#9776]
Apache + Laravel 5.1, this is in .htaccess:

    Options -Indexes
    ErrorDocument 403 /error-403

The error document statement is pointing to a Laravel-defined route.

I also have a `js/` directory in `public/`. When I try to access it, I should get a 403 Forbidden response. But instead I get Laravel's 404 error page. Why? Well, I've been doing a little bit of digging. When this happens, these are some of the active server variables:

    "REDIRECT_REDIRECT_REQUEST_METHOD" => "GET"
    "REDIRECT_REDIRECT_STATUS" => "403"
    "REDIRECT_STATUS" => "403"
    "REDIRECT_URL" => "/error-403"
    "REQUEST_METHOD" => "GET"
    "REQUEST_URI" => "/js/"

Note the `REDIRECT_URL` and `REQUEST_URI` here. What happens is that Laravel picks up the `REQUEST_URI` value, when it should in fact pick up `REDIRECT_URL`. Since `js/` isn't defined as a Laravel route, a 404 page is returned.

As I see this, if `REDIRECT_STATUS` is >= 400 (which is an indication of an error and not a 3xx redirect), `REDIRECT_URI` should be used, otherwise there is no way to set it up so that Apache's error document points to a Laravel route. Or?

The code responsible for this is a part of Symfony it seems, so I'm not sure this should be reported here. The code is in `Symfony\Component\HttpFoundation\Request::prepareRequestUri()`.

I've also asked a question related to this on StackOverflow, although I did it before digging into Laravel/Symfony code. This is the original question:
http://stackoverflow.com/questions/31700806/routing-apache-errordocument-to-a-laravel-route

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
