### ISSUE TITLE
Refresh resolved instances in facade

### ISSUE THREAD

**Issue by mtils** [laravel/framework#9784]
If you replace an instance (singleton) in laravels application, the previous instance of this object is hold inside Facade::$resolvedInstance and will not be updated. If you use facades inside ServiceProviders the Facade::$resolvedInstance will be set and if then for example a middleware replaces the request, the wrong instance will be hold inside the facades.
Ok, using Facades in ServiceProviders is bad practice but it shouldnt lead to errors...

Normally I would just suggest something like this:

```php
abstract class Facade {
    //...
    protected static function resolveFacadeInstance($name)
    {
        if (is_object($name)) return $name;
        
        if (isset(static::$resolvedInstance[$name])) {
            return static::$resolvedInstance[$name];
        }
        static::$resolvedInstance[$name] = static::$app[$name];

        static::$app->rebinding($name, function($app, $resolvedInstance){
            static::$resolvedInstance[$name] = $resolvedInstance;
        });
    }
    //...
}
```
...but normally the Facade::swap() method is used to swap the instance and this would lead to endless recursion because swap will rebound the instance inside the container.
So what would be the solution? If someones interested I can write a patch (test and fix).

**Comment by GrahamCampbell** [comment]
Sorry, this is the expected behaviour and not a bug.
