### ISSUE TITLE
random logouts & TokenMismatch using memcached cluster on AWS

### ISSUE THREAD

**Issue by mattyglover** [laravel/framework#9787]
Production site is kicking users back to login seemingly randomly - almost always correlating to a TokenMismatch.

I have added logging to track the URI being requested and the user requesting. Interestingly I can see that for some unknown reason the user transitions to "Guest" ie !Auth::user() just prior to hitting a protected route.

Does NOT occur using the file driver. But this is no use to me with two active front end servers.

Laravel 5.1 - two EC2 instances in parallel
memcached (AWS cluster)
php 5.5.25
centos/whm

I have config:cache's and session domain set.

Typical flow is page GET, with an AJAX call to check for new messages on a getstream.io queue, with EACH page refresh. Each page refresh also subscribes to push notifications from getstream.io

At this stage we have to shut down our second front end EC2 instance and run in production on only one server using the file driver.

What am I doing wrong?

**Comment by GrahamCampbell** [comment]
Which driver are you using?

**Comment by GrahamCampbell** [comment]
This issue has come up many times before.

A good work around in my experience is to use the redis driver for sessions, and actually save the session data before sending the response rather than after sending the response like Laravel does out of the box.

**Comment by GrahamCampbell** [comment]
You'll need to extend laravel's start session middleware to do that.

**Comment by mattyglover** [comment]
ok, will look to it

**Comment by mattyglover** [comment]
thanks

**Comment by mattyglover** [comment]
I'm ok with switching to Redis from memcached- in your experience is it ok to use Redis for both sessions and cache or do I need to split these?

**Comment by GrahamCampbell** [comment]
It's fine. You can actually have multiple redis databases on one redis instance. Just add another redis connection in your database config and get the sessions to use database 1 instead of database 0.

**Comment by GrahamCampbell** [comment]
Then make sure you set the database key in the session config to use the name you gave this new connection in your database config,

**Comment by mattyglover** [comment]
Thanks again graham :)

**Comment by TheShiftExchange** [comment]
@GrahamCampbell 

`
A good work around in my experience is to use the redis driver for sessions, and actually save the session data before sending the response rather than after sending the response like Laravel does out of the box.
`

So can we make this the default behaviour in Laravel then? We know there are many many other people with this issue?

Or at least put this on the Docs as an alternative way - so it is documented for all to see?

**Comment by raydric** [comment]
I'm having similar issues after I started using the redis session driver. I don't get any TokenMismatch but a random logout. 

Not 100% reproducible but most of the time: login in two browsers/computers with the same user, make an ajax POST request, refresh both and one of them gets logged out

**Comment by andres-lorenzatti-olx** [comment]
Hi there, we have same issue on AWS EC2 PHP 5.5.9-1ubuntu4.16 and AWS elastic cache cluster with sessions expiring in randomly very very often (1-2 of 5 requests).
Does it means that laravel does not support AWS elastic-cache memcache cluster?
Is there another approach than moving from memcache to redis?

Thanks
