### ISSUE TITLE
Adding a 'silence' rule

### ISSUE THREAD

**Issue by cjaoude** [laravel/framework#9801]
I'll just throw this out there... a 'silence' rule may be handy for hidden inputs or other shenanigans you want to validate but wish to hide from the user.

`'token' => 'required | silence'`

Should the condition fail, the message would be silenced. Or emitted to a log or exception.

Or `silent`.

**Comment by GrahamCampbell** [comment]
You need to implement this when you look at the errors. It would be wrong for us to implement it at this level.
