### ISSUE TITLE
Config::set() sets connection to unwanted setting

### ISSUE THREAD

**Issue by baao** [laravel/framework#9804]
I'm working with a message queue with 40 listening daemon workers. The queue will always have messages in it, so the workers work continuously. There are messages for different customers in the queue and I have to set the database according to the xml data contained in the queue's payload.

When using Config::set() to set the database during runtime, the data gets inserted into various databases, in the correct tables - but in the wrong database. There are many equal databases.

I'm trying to set the database with

    Config::set('database.connections.usertable.database',$database);

directly before the connection is made. I also tried Config::set() directly before each (and also only some or one) $table->create() statements, without success.

According to the documentation, Config::set() should be valid for this request only, but it seems like it is confusing the settings when there are multiple connections that set configuration values at the exact same time.

Though I have now solved above issue by extending Model by setConnection() and getConnection() and a different configuration, I'm curious why this happens.

Shouldn't the Config only be set for the exact request it is set in?

**Comment by GrahamCampbell** [comment]
Everything is persisted when you have daemon workers. They are NOT requests.

**Comment by baao** [comment]
Wow, thank you!
