### ISSUE TITLE
findOrFail() & firstOrFail() 

### ISSUE THREAD

**Issue by lukebro** [laravel/framework#9808]
In the documentation for Eloquent, specifically [retrieving single/model aggregates section](http://laravel.com/docs/5.1/eloquent#retrieving-single-models) it notes that when you call firstOrFail() or findOrFail() and no results are found,  a ModelNotFoundException is thrown.  

That part is correct, however it continues to note that `If the exception is not caught, a 404 HTTP response is automatically sent back to the user, so it is not necessary to write explicit checks to return 404 responses when using these methods`.

If you don't catch the exception a 500 response is automatically sent rather than a 404.  To send the 404 you have to catch it and respond yourself.

I could be missing something, but to recreate this just create a route with a closure and return the Model using one of these methods.

**Comment by spencerdeinum** [comment]
Did you only test in debug mode? I believe if you test in production it should be a 404 but I'm not 100% sure.

**Comment by lukebro** [comment]
@spencerdeinum tested in production as well

**Comment by neomerx** [comment]
Guys why not look into the code? When `ModelNotFoundException` exception is thrown (as all others) it goes to [exception handler](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php). `ModelNotFoundException` is not on [the list of exceptions that won't be reported](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L16) thus it will be [reported](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L30) ([logged by default](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Exceptions/Handler.php#L46)) and [rendered](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L42) to user ([well known error screen](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Exceptions/Handler.php#L88)).

**Comment by GrahamCampbell** [comment]
If you don't catch a model not found exception, expect an error 500.

**Comment by GrahamCampbell** [comment]
404 would be wrong - the context for a 404 is very specific.

**Comment by patrickcarlohickman** [comment]
@GrahamCampbell In this case, it is the documentation that is wrong, not the code. The documentation states that a 404 will be returned, but it is not. Is this the correct place to report documentation errors, or is there another place for that?

**Comment by lukebro** [comment]
I feel like the documentation is right and maybe it was taken out by accident between iterations.   When will you ever not catch the ModelNotFoundException and respond with a 404?  Should be the default action in my opinion if not caught.

**Comment by neomerx** [comment]
@lukebro you should start learning how it works these days :trollface: 

![it used to be different...](http://img11.deviantart.net/52e3/i/2006/070/f/c/please_listen_by_balling.jpg)

**Comment by mounsif-chr** [comment]
If the exception is not caught a 404 HTTP response will be sent back to the user

**Comment by jeff-h** [comment]
Something to bear in mind here is that both Eloquent queries *and* collections have a `firstOrFail` method, but they throw different exceptions.

* Illuminate\Database\Eloquent\ModelNotFoundException [documentation](https://laravel.com/docs/11.x/eloquent#not-found-exceptions)
* Illuminate\Support\ItemNotFoundException [documentation](https://laravel.com/docs/11.x/collections#method-first-or-fail)

The docs are correct I believe (as of 2024), but it's not always obvious that you have a collection, and in my case at least the collection's `firstOrFail` resulted in a `500` code to the client, whilst a `ModelNotFoundException` results in a `404`.

**Comment by plumthedev** [comment]
We can implement HttpExceptionInterface from Symfony but it will be a BC for all people who are not catching the exception from collection
