### ISSUE TITLE
its a bug or not?

### ISSUE THREAD

**Issue by dkeepersun** [laravel/framework#9812]
console i run all the time :  php artisan queue:work --daemon --sleep=1 --tries=5 --queue=task 

after some times i get error :
 ```product.ERROR: exception 'RuntimeException' with message 'Can't swap PDO instance while within transaction.' in /data/lightning5/vendor/laravel/framework/src/Illuminate/Database/Connection.php:854```

if i restart the queues :  php artisan queue:restart  ,  it work fine.  after some minutes, its occur again.....

before i guess ,maybe i use two connection of mysql(1, read ,2 write), but its not . 
i check all my codes, i always use transaction like this: 
```
        \DB::beginTransaction();
        try {
        } catch (\Exception $e) {
            \DB::rollback();
            \Log::error($e);
        }
        \DB::commit();
```

what happened to me ?  
thank you.

**Comment by GrahamCampbell** [comment]
Not a bug.

**Comment by GrahamCampbell** [comment]
Please ask on the forums for help regarding use of transactions.

**Comment by dkeepersun** [comment]
so what's that ? wrong way to use transactions?
