### ISSUE TITLE
Paginator fails if parameter page is not a string

### ISSUE THREAD

**Issue by ifduyue** [laravel/framework#9813]
For example, `?page[]=1`.

I find laravel will not fail if parameter page is string, although it's not a valid number. Better to make an array work like this, too.

**Comment by GrahamCampbell** [comment]
This is the expected behaviour.

**Comment by ifduyue** [comment]
> This is the expected behaviour.

I think it's better to validate page parameter, rather than throws an exception.
Laravel already makes a string but not a valid number (e.g. `?page=xxx`) survive, why not a step further?

**Comment by GrahamCampbell** [comment]
> I think it's better to validate page parameter, rather than throws an exception.

Throwing an exception IS validating the parameter.

**Comment by ifduyue** [comment]
> Throwing an exception IS validating the parameter.

So one has to try & catch in every place where paginator is used.
Just feel a little painful.

**Comment by ifduyue** [comment]
> Throwing an exception IS validating the parameter.

After catching such an exception, is there anyway to fallback it to page 1?

**Comment by GrahamCampbell** [comment]
You need to implement that logic.

**Comment by ifduyue** [comment]
> You need to implement that logic.

Yes, but I can't find an easy way to implement it.
Neither try&catch `->paginate()` and then `Paginator::setCurrentPage(1)`, nor `Paginator::currentPageResolver(func)` is a simple and clean way.


IMHO, laravel, as a framework, provides paginator feature, and it would be better to make sure that an invalid parameter in querystring doesn't cause 500.

@GrahamCampbell anyway, thanks.

**Comment by GrahamCampbell** [comment]
I'd recommend catching it at the exception handler level, and then making the exception a bad request exception. I have a package that makes this sort of thing easy. https://github.com/GrahamCampbell/Laravel-Exceptions. Then you're going to want to make a transformer for that pagination exception, something like this: https://github.com/StyleCI/StyleCI/blob/master/app/Exceptions/Transformers/ValidationTransformer.php.

**Comment by ifduyue** [comment]
@GrahamCampbell Thanks, I'll give it a try.

**Comment by ifduyue** [comment]
It's addressed in 5d750330b6c366c89d192646433d3731037fe000

**Comment by GrahamCampbell** [comment]
You'll need 5.2.x then. ;)

**Comment by ifduyue** [comment]
> You'll need 5.2.x then. ;)

Any chance to get this backported to 5.1.*?

**Comment by GrahamCampbell** [comment]
It was considered breaking so didn't make it into 5.1.

**Comment by ifduyue** [comment]
@GrahamCampbell It seems branch 5.1 did the same thing, but in another commit 83ad23c.

**Comment by GrahamCampbell** [comment]
We must have changed our mind, and backported it. ;)

**Comment by ifduyue** [comment]
:+1: :100:
