### ISSUE TITLE
public_path() returning hostname in path?

### ISSUE THREAD

**Issue by MikkyX** [laravel/framework#9817]
I'm working on a Laravel 5.1 project on my Mac. I'm also using CodeKit's server functionality for auto-reloading and device testing.

The project is hosted in the following folder:

    /Users/MikkyX/Sites/uncovered5/

"uncovered5" is also the name of my development host. However, CodeKit requires you to connect to a different port in order to access the auto-reload functionality, so I'm currently accessing my project via http://localhost:5757/

I've just used the public_path() function in my project and I've noticed it's returning this path:

    /Users/MikkyX/Sites/localhost:5757/public/

If I access the script in question via my usual http://uncovered5/ host, I get the expected and correct path:

    /Users/MikkyX/Sites/uncovered5/public/

It looks like it's dropping the HTTP_HOST into the path somehow?

**Comment by MikkyX** [comment]
I've been testing this further and it looks like a problem with realpath()

I have a controller set up to do just this:

    class ConvertController extends Controller
    {
        public function test()
        {
            return realpath(__DIR__);
        }
    }

When I call this controller function from a route, it outputs:

    /Users/MikkyX/Sites/localhost:5757/app/Http/Controllers

I'm using MAMP PRO running PHP 5.6.10.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
