### ISSUE TITLE
Input hidden _method is not accepted with GET method

### ISSUE THREAD

**Issue by jdrda** [laravel/framework#9819]
If using **CRUD** controller with **Resource route**, it is possible to add hidden field **_method** to specify the real method of HTTP we want to achieve (PUT/PATCH/DELETE, ...).

However this works with form `method="post"` only, if you change `method="get"`, the **_method** field is not detected. So I suppose, the `$_POST` array is used insead of `$_REQUEST` in this case.

In real development, there is not always necessary to use submitting form for actions like DESTROY (delete), A links are used like:
```html
<a href="http://domain.com/article/26?_method=DELETE">Delete article</a>
```

**Comment by arrilot** [comment]
`_method` is intentionally applied only to `POST` forms.
You should never delete anything with `GET` request because it leads to many problems.

**Comment by GrahamCampbell** [comment]
Using GET for perform non-read operations is asking for trouble, and violates the http spec. HEAD and GET are so called "safe" verbs.

**Comment by barryvdh** [comment]
You shouldn't use GET requests to delete stuff, but if you want to delete something with 1 click, just create a form submit button for the delete button, or use Javascript to handle the link. https://github.com/rails/jquery-ujs does that for example, see http://barryvdh.nl/laravel/jquery/2015/04/11/unobtrusive-javascript-with-jquery-ujs-and-laravel/

**Comment by jdrda** [comment]
:arrilot What problems do you mean?
:GrahamCampbell Well, in general POST method is not for deleting something, so if there is a solution for POST, I do not know, why it is problem for GET.
:barryvdh Thanks, I know how to work arround, but GET is much mor simplier, mainly in admin templatess

As I read, I really do not know, what makes this "problem". If you have good methods associated with _destroy, it is the same as if you call from POST. 

But I let this judge by community, but from the posts above, I do not see any good explanation, why to not use it - in comparation with GET.

**Comment by barryvdh** [comment]
It's because GET should be `safe`. Browser follow this convention. They will warn if you submit a POST request again, but not for GET requests. They can be cached, tracked by google, even preloaded etc.

https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Safe_methods
>Some of the methods (for example, HEAD, GET, OPTIONS and TRACE) are, by convention, defined as safe, which means they are intended only for information retrieval and should not change the state of the server. In other words, they should not have side effects, beyond relatively harmless effects such as logging, caching, the serving of banner advertisements or incrementing a web counter. Making arbitrary GET requests without regard to the context of the application's state should therefore be considered safe.
> [..]
>  Despite the prescribed safety of GET requests, in practice their handling by the server is not technically limited in any way. Therefore, careless or deliberate programming can cause non-trivial changes on the server. This is discouraged, because it can cause problems for web caching, search engines and other automated agents, which can make unintended changes on the server.

If you look at jquery-ujs, you can see that it's hardly more difficult, other then setting it up once.

```
<a href="article/26" data-method="delete" rel="nofollow">Delete this entry</a>
```
