### ISSUE TITLE
random whoops page even when debug is true 

### ISSUE THREAD

**Issue by astroanu** [laravel/framework#9824]
I've been having this problem since L5. Sometimes i get directed to this screen even when the debug is true. I dont think it's suppose to do this. There's nothing on the error logs, not in the php error log or the apache error log. If there's any error shouldn't it always be showing up when in development mode? And the most irritating thing is this happens randomly. If i refresh the page it works but next time it does not.

![Image of Yaktocat](http://i62.tinypic.com/152ccy9.png)

**Comment by GrahamCampbell** [comment]
You likely didn't clear the config cache.

**Comment by astroanu** [comment]
but i'm not caching my config files.

**Comment by GrahamCampbell** [comment]
Well, you must be.

**Comment by GrahamCampbell** [comment]
Go and delete the cached config file.

**Comment by astroanu** [comment]
no i'm not. i think the cache files are stored in \vendor ? i'm using file cache driver and there is no config.php there. will caching the config files get rid of this error ?

**Comment by GrahamCampbell** [comment]
Cache files are not stored in vendor, they're stored in bootstrap/cache.

**Comment by GrahamCampbell** [comment]
> i'm using file cache driver

That's not the cache I mean...

**Comment by astroanu** [comment]
hmm that's weird because if i run config:cache it does make a config.php on the vendor folder. it doesn't make anything on the bootstrap/cache. i don't even have a cache folder in bootstrap :O 

so cache setting doesnt have anything to do with caching config files .. :octopus:

**Comment by GrahamCampbell** [comment]
Are you using L5.0 and not 5.1?

**Comment by GrahamCampbell** [comment]
Likely your file permissions are wrong.

**Comment by astroanu** [comment]
i cant update one of my projects to laravel to 5.1 because of the packages i'm using, but others are using 5.1. i even ran an update to make sure it is. the problem persists on both 5 and 5.1
yes  file permissions are setup correctly.

**Comment by GrahamCampbell** [comment]
We don't support 5.0, sorry.

**Comment by GrahamCampbell** [comment]
This isn't a bug in the framework anyway I'm afraid. Please ask on the forums and I'm sure someone can help you out. :)

**Comment by astroanu** [comment]
thanks. i think it HAS something to do with config files. there maybe a latency in reading the .env files and it's causing this.. i'm just guessing. for now i'll just cache the config files. it did improve the loading time a little bit. let's see if that weird bug goes away.
