### ISSUE TITLE
Offer localized number formatter

### ISSUE THREAD

**Issue by ameenross** [laravel/framework#9827]
Instead of having to do this:

```php
NumberFormatter::create(App::getLocale(), NumberFormatter::DECIMAL)->format($this->weight);
```

Laravel could offer a few API functions that deal with creating a number formatter based on the currently used locale, saving code for the developer and potentially offering better performance as well. You could store the number formatter on the `Lang` object for example, until `App::setLocale()` is called, invalidating the formatter.

**Comment by GrahamCampbell** [comment]
Feel free to make a package.
