### ISSUE TITLE
route() and to() in URL generator behave differently

### ISSUE THREAD

**Issue by aimeos** [laravel/framework#9829]
@CyberiaResurrection found an issue in the URL generator. It generates different URLs when calling ```route()``` vs. calling ```to()``` for the same thing. The difference is that ```to()``` adds the subdirectory the application is located at while ```route()``` does not, e.g.

- route('list'): /list
- to('/list'): /myapp/list

```/myapp/``` is the subdirectory the application is located at. This leads to URLs generated by ```route()``` that point to invalid locations.

**Comment by GrahamCampbell** [comment]
Looks like you haven't configured your base url correctly.

**Comment by aimeos** [comment]
Nope, changing the ```url``` setting in ```config/app.php``` doesn't have any effect as it seem to be only used by artisan CLI.

**Comment by GrahamCampbell** [comment]
Did you remember to clear you config cache?

**Comment by aimeos** [comment]
Jep, but none worked:
- artisan cache:clear
- artisan config:clear
- artisan route:clear

I think the problem is in the ```toRoute()``` method of the URL generator. It simply doesn't care about subdirectories.

**Comment by GrahamCampbell** [comment]
Hmm, well apps running under subdirectories aren't recommended by laravel I'm afraid, and aren't fully supported.

**Comment by aimeos** [comment]
One further note: Creating absolute URLs does work, only in relative ones the subdirectories are missing.

**Comment by garygreen** [comment]
`->route` fully supports base urls and `app.url` has nothing to do with the base url (it's only used in console / environments where there isn't a 'Request' to determine output urls). It's actually Symphony that get's the base url -- you've probably not configured your environment quite right or got some weird htaccess/nginx rewrite that's causing Symphony to have trouble working out your base path.

**Comment by aimeos** [comment]
@garygreen This has nothing to do with the Symfony components or a wired web server environment as it happens with the integrated PHP web server as well. The ```toRoute()``` and it's used methods in the URLGenerator class simply don't care about subdirectories when creating relative paths.

**Comment by garygreen** [comment]
@aimeos What does `Request::root()` return for you? Is nothing calling `forceRootUrl()`? What environment are you trying this under (Browser or Console command?)
