### ISSUE TITLE
Empty currentRouteName() on patch/update request

### ISSUE THREAD

**Issue by sineld** [laravel/framework#9831]
I use Route::currentRouteName() to get route name on request but it returns null on patch/update requests.

**Comment by shssoichiro** [comment]
Unable to confirm in 5.1. See PR #9833 for test case.

Ensure that you have a name set for that route in your routes file (using `as => 'foo'`).

**Comment by sineld** [comment]
I have updated my form views and replaced every "patch" with "put" and now everything works as expected.
Thanks.
