### ISSUE TITLE
Why do the native User is not included in the laravel/framework component?

### ISSUE THREAD

**Issue by brazorf** [laravel/framework#9832]
I mean: i can write my own package that relies on ```illuminate/auth```. 
However, if i call for example ```Auth::attempt('foo', 'bar') ``` that will not work and i'll get a 

```Class '\App\User' not found in Illuminate/Auth/EloquentUserProvider.php on line 126```

since the ```App\User``` lives outside the ```laravel/framework``` package, and ```illuminate/support``` has not the proper dependency. 

Obviously, adding the whole ```laravel/laravel``` package as a dependency sounds way too much redundant.

Why did you take this design path? How should we deal with packages that want to reuse the User and the Auth implementations?

**Comment by GrahamCampbell** [comment]
`App\User` is meant to be a class defined in your own application.

**Comment by GrahamCampbell** [comment]
> Obviously, adding the whole laravel/laravel package as a dependency sounds way too much redundant.

That's not a package and should never be added to your composer.json. laravel/laravel is just a boiler plate laravel application.
