### ISSUE TITLE
Model::fresh() does not fail when the record is deleted from database

### ISSUE THREAD

**Issue by budhajeewa** [laravel/framework#9835]
Following does fail, as expected.

```
$ned = \App\Person::findOrFail(1);
$ned->delete();

$nedsGhost = \App\Person::findOrFail($ned -> id); //Fails as expected.
```

However, following does not:

```
$ned = \App\Person::findOrFail(1);
$ned->delete();

$ned->fresh(); //Does not fail as expected. 
```

If the `Person` is deleted from the database, and `Illuminate\Database\Eloquent\Model::fresh()` "Reload[s] a fresh model instance from the database.", how can it not throw a `\Illuminate\Database\Eloquent\ModelNotFoundException`?

If above is the expected behaviour, i.e. return existing instance if the record is deleted database, I suggest considering including a `Illuminate\Database\Eloquent\Model::freshOrFail()`.

**Comment by willrowe** [comment]
I'm pretty sure that's expected.

**Comment by budhajeewa** [comment]
So the method's description is misleading. It does not completely "Reload a fresh model instance from the database." as advertised.

I am not experienced enough in Laravel's inner workings to submit a PR for a `Illuminate\Database\Eloquent\Model::freshOrFail()`, but I guess someone could do it, if above is the expected behaviour of `...::fresh()`.

**Comment by willrowe** [comment]
What does it it return? null?

**Comment by budhajeewa** [comment]
Yep.

**Comment by willrowe** [comment]
Can you give a specific use case for `freshOrFail`?

**Comment by budhajeewa** [comment]
While testing a model, I need to verify whether it's related models are deleted as well. To do that, I could simply do following:

```
public function testDelete_deletesComments()
{
  $this -> setExpectedException ( '\Illuminate\Database\Eloquent\ModelNotFoundException' ) ;

  $post = \App\Post::
    with(['comments'])
    ->findOrFail();

  $post -> delete();
  
  $post -> comments -> first() -> fresh();
}
```

I am currently using `\App\Comment::findOrFail($post -> comments -> first() -> id)` in place of `$post -> comments -> first() -> fresh()`.

**Comment by willrowe** [comment]
There are several ways that you can do that like:
```php
$this->assertNull($post->comments->first()->fresh());
```
The way I think about `fresh`, it would only be used on a record you'd assume exists. `freshOrFail` doesn't make sense to me.

**Comment by budhajeewa** [comment]
That's true. However, I think it won't hurt to have a `freshOrFail` given that we already have a `findOrFail`.

**Comment by bobbybouwmann** [comment]
Create the PR and hope that will be merged ;)

**Comment by budhajeewa** [comment]
@bobbybouwmann Sadly I have not dwelt in the inner working of Laravel enough to do that. :disappointed:
