### ISSUE TITLE
 CrawlerTrait assertPageLoaded prevents negative route testing

### ISSUE THREAD

**Issue by rickpelletier** [laravel/framework#9841]
I have a RESTful Lumen API, and I'm writing "functional" tests using Lumen's handy [TestCase][1].  For positive tests, ie anything intended to return an http 200, this works great - the test assertions can access both the original content and the serialized string output.

However, I'm trying to write a "negative" test - ie. request a resource that does not exist.  In my code, this is supposed to return an http status code of 404 as well as a small json object with a more descriptive error message.

Unfortunately I can't see to get my test to pass, because [this line of code][2] in the Lumen CrawlerTrait ends up throwing an exception before any of my test code can execute.

Does Lumen assume that every request should result in a 200 OK?  

Is it possible to code a test against a route which asserts that the correct non-200 status code is sent?

  [1]: https://github.com/laravel/lumen/blob/master/tests/TestCase.php
  [2]: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/CrawlerTrait.php#L254

**Comment by GrahamCampbell** [comment]
Please report lumen bugs on the lumen repo.

**Comment by rickpelletier** [comment]
Sorry!  Will move over there.

**Comment by GrahamCampbell** [comment]
Don't worry about it. :)

**Comment by rickpelletier** [comment]
Actually, I don't see the Lumen github repo having issue reporting turned on - do you happen to know where I can report issues with Lumen?

**Comment by GrahamCampbell** [comment]
You're probably looking at the wrong repo. The "lumen" repo is just a boiler plate lumen app, the same deal as the "laravel" repo. The real deal is at https://github.com/laravel/lumen-framework.

**Comment by rickpelletier** [comment]
Aha, thanks!
