### ISSUE TITLE
[5.1.8]Migrating lots of rows crashes the process silently

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [laravel/framework#9842]
When migrating lots of rows for one table (around 45.000 rows), the process ends without any output to the console. Only the log file catch the exception. The console just finish the process looking like everything went just fine.

The migration scope:

```
DB::table('my_big_table')->insert([
    ['column' => 'data', 'other-column' => 'other-data'],
    ['column' => 'data', 'other-column' => 'other-data'],
    ...
    + 45.000 rows like that
    ...
]);
```

And what the log caught:

```
[2015-08-04 23:00:07] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]:
General error: 1390 Prepared statement contains too many placeholders' in
D:\my_app\vendor\laravel\framework\src\Illuminate\Database\Connection.php:381
```

And following that error is a "Next exception", which contains a mega string with all the inserts concatened in one line.

I think that local.ERROR should show up in the console as well.

**Comment by garygreen** [comment]
That's a lot of data to insert in one go. You should chunk / split it up. Not an issue with Laravel

**Comment by rafael-renan-pacheco** [comment]
This issue isn't about the lots of data to insert. Of course I had to use some other way to insert those 45k lines.

The main reason I opened this topic is to show that the console doesn't always catch errors, which may, or may not, lead the developer to a false positive regarding the operation being executed.

@GrahamCampbell 
Reopen this issue if you find valid this argument.

**Comment by Sladewill** [comment]
Its a php exception because you haven't coded it correctly, laravel can't really help with bad programming.

**Comment by rafael-renan-pacheco** [comment]
@Sladewill are you serious?

As I said, this topic isn't about DB::table handle tons of lines. It's about the "php artisan" not catching the exception during the php execution.

> you haven't coded it correctly
Yes I did. The exception isn't about typos in my php code.

> laravel can't really help with bad programming
Can you point where is this bad programming? Can you link the doc which says how many inserts my migration may have?

The only thing bad here is your "contribution" to this post.

**Comment by lukasgeiter** [comment]
I think the OP has got a point. If there was an exception, you should see something indicating that it failed. At the minimum something like: `An error occurred. Check the logs for more information`

**Comment by Sladewill** [comment]
I'm mearly stating if you are going to throw that many rows through php and whichever database you will always expect that to fail, its guaranteed so you know your code is going to fail. The only logical way to proceed is to just chunk it, its not laravels duty.

Also if you read the docs it advises you to do this with chunk. http://laravel.com/docs/5.1/queries#retrieving-results see Chunking Results From A Table. So once again you know your code will not work because your adviced not to do this.

**Comment by rafael-renan-pacheco** [comment]
Now that is a good answer. Chunk seems to solve the problem for selecting rows, but the docs don't say about inserting.

But, as said before, this topic is about the console catching and displaying some errors to the developer. I just used the insert sample to justify this topic. I can't just open an issue and say "sometimes the console doesn't display errors, bye bye".

Best regards.
