### ISSUE TITLE
Multi-dimensional cookies breaks request with exception

### ISSUE THREAD

**Issue by garygreen** [laravel/framework#9843]
Currently the `Illuminate\Cookie\Middleware` only supports [only one level deep cookies](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L109), if there is 2 levels or more, it won't properly encrypt and throws an exception when it comes to decrypting.

Example of cookie causing this exception:

> **Cookie:** myrsol[History][token]=2fb17f8adabc33014ef7eded6b6f601c;

**Comment by GrahamCampbell** [comment]
This might be intended. Not sure if we ever wanted to support that. Ping @taylorotwell.

**Comment by garygreen** [comment]
Well if that's the case it's still a problem as "malicious" user input from a request shouldn't cause a base64 decode exception within the core. If anything it should throw a `CookieNestingTooDeep` exception or something. That way it's at least it's catchable so I can tell my app to not log those exceptions...

**Comment by GrahamCampbell** [comment]
@garygreen Could you send a PR please. As you pointed out, malicious user input can crash the web server.
