### ISSUE TITLE
Testing - DatabaseMigrations trait to seed database

### ISSUE THREAD

**Issue by Va1** [laravel/framework#9845]
Hey!

The issue is pretty minor, but here it is:

Currently, `\Illuminate\Foundation\Testing\DatabaseMigrations` trait does not seed the database. It is easy to copy this trait and add `--seed` to the command on [this line](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/DatabaseMigrations.php#L12) or just add another line with `$this->artisan('db:seed');`, but I suggest having such trait in the framework and call it like (for example) `DatabaseMigrationsSeed` would be cool.

That's all. Looking forward to any thoughts on this. If it sounds good, I would like to add this tiny feature.

**Comment by GrahamCampbell** [comment]
Please send a PR. We don't normally process proposal issues.
