### ISSUE TITLE
CSS doesn't work when use gulp

### ISSUE THREAD

**Issue by derah04** [laravel/framework#9855]
the class of bootstrap css or custom css doesn't work in my laravel 5.1 web project, i use gulp to manage css assets  ...
so whats wrong ?? 
please help me master ..
![jumbotton](https://cloud.githubusercontent.com/assets/12068181/9108525/65019958-3c61-11e5-9e5e-21f60e0f2775.PNG)
![page source](https://cloud.githubusercontent.com/assets/12068181/9108526/650eca60-3c61-11e5-8abd-bae63c98ef34.PNG)

**Comment by ghprod** [comment]
Whats the content of your build css?

**Comment by jbrooksuk** [comment]
This isn't a Laravel issue.

It looks more to me that you've not setup your `gulpfile.js` properly.

**Comment by derah04** [comment]
this is my gulpfile.js

var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.sass('app.scss');

    mix.version('public/css/app.css');
});

**Comment by jbrooksuk** [comment]
I don't think you need to prefix the `public/` path, it's defaulted to be I believe.

**Comment by derah04** [comment]
still not work :(

**Comment by jbrooksuk** [comment]
Just check that `public/css/app.css` does actually have some content.
