### ISSUE TITLE
$status should be automatically bound to view

### ISSUE THREAD

**Issue by rootman** [laravel/framework#9856]
As validation errors are automatically bound to the view, it would make sense to do the same with the status.

This behavior would make it simpler in scenarios like the password reminder. When the email has been sent, the user is redirected back with a status.

    return redirect()->back()->with('status', trans($response));

To use the status, one would now need to override:

    public function getEmail()
    {
        return view('auth.password'); // add status here
    }

So the status could either be added to the trait to be available in the password.blade.php or be globally bound to the view like validation errors, which would make sense in my opinion.

What do you guys think?

**Comment by GrahamCampbell** [comment]
You can implement this yourself in your app, or in a package, or whatever.
