### ISSUE TITLE
find/firstOrFail 404 issue

### ISSUE THREAD

**Issue by somuraijoe** [laravel/framework#9857]
Hello,

findOrFail and firstOrFail methods doesn't work as intended. If the exception "Illuminate\Database\Eloquent\ModelNotFoundException" isn't caught then a 404 error should be displayed on the screen,
however this is not happening.

Reference: https://github.com/laravel/docs/pull/1728

**Comment by shssoichiro** [comment]
I can confirm this on 5.1. Instead of returning a 404 response, a ModelNotFoundException is thrown and the user receives the Whoops error screen with response code 500.

**Comment by somuraijoe** [comment]
fixed here: https://github.com/laravel/framework/commit/71b61eafa444537d74ca767f724bd7bff3130b30
