### ISSUE TITLE
Query binding giving incorrect results

### ISSUE THREAD

**Issue by BakerCo** [laravel/framework#9860]
Shouldn't these two statements be equal?

This one returns 5 records which is accurate
$buildings = DB::select('select * from buildings where square_footage < 10000');

This one returns an empty array
$buildings = DB::select('select * from buildings where square_footage < ?', [10000]);

I am rather new so forgive my ignorance in posting this. Something just seems broken.

**Comment by bobbybouwmann** [comment]
Well `DB::select` accepts an array with column names to return: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L225

So in your case you need to use the `selectRaw` function in which you can specify the parameters: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Query/Builder.php#L239

**Comment by lukasgeiter** [comment]
@bobbybouwmann That's a different `select()`. `DB::select` refers to a [function in `Connection`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Connection.php#L300)

**Comment by BakerCo** [comment]
Ok well let me come at it from this angle I have a query scope setup like this

```php
public function scopeBySize($query) {
     return $query->where('sqaure_footage', '<', 10000);
}
```

The above gives me an empty array... yet if I query the database I have 5 records that are < 10000

I can concede to being ignorant when it comes to laravel but please help me understand how this is supposed to give me a different result from a straight SQL query.

Thank you both for your responses earlier this did open my eyes to some things I was unaware of.

`JB

**Comment by bobbybouwmann** [comment]
I would say post your question on a forum (Laracasts), so we can keep this issue closed. Also if you post on a forum, explain what you have tried and what is not working and your code of course ;)
