### ISSUE TITLE
Nested resources 404'ing when 3 deep using MySQL.

### ISSUE THREAD

**Issue by r3oath** [laravel/framework#9865]
So, strange issue I’m having with nested resources in 5.1, I have a route defined as `groups.feeds.images` with route model binding for groups, feeds and images. Now locally, using sqlite and the built in artisan serve, if I hit `{url}/groups/1/feeds/1/images/1` I get the resource I am after, but on our production server running ngix and mysql, we get a resource not found. Now this only seems to happen with nested resources that are more than 2 deep, `{url}/groups/1/feeds/1` works fine, so does `{url}/groups/1/feeds/1/images/`.

Both the local and the remote databases share the same data and the id's being used exist in the relative tables.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
