### ISSUE TITLE
Laravel 5.1 comes without default auth views

### ISSUE THREAD

**Issue by llnk** [laravel/framework#9868]
I just found out that Laravel 5.1 removed the default auth views (and a skeleton of app.blade.php). For me this is a major issue. The prebaked auth view/route allowed to very quick prototype/internal tool development.

Even taylor said that one of the reason he developed Laravel was to have authentication already set-up in the system. Is there any chance to rollback this decision?

In fact to have that back, I copied the view/auth folder from laravel 5.0 repo inside my 5.1 repo

**Comment by GrahamCampbell** [comment]
No, sorry.

**Comment by bobbybouwmann** [comment]
@llnk Here is a package that will do the same thing for you: https://github.com/bestmomo/scafold

**Comment by llnk** [comment]
Interesting! Although I suggest you to expand a little more the readme, I couldn't underatand that your package was for this
