### ISSUE TITLE
[Clarification] About multilevel transactions behaviour

### ISSUE THREAD

**Issue by prady00** [laravel/framework#9871]
When I do:

    DB::beginTransaction(); //T1
    Device::insert(array("submit_hash" => "trial"));
    DB::beginTransaction(); //T2
    Device::insert(array("submit_hash" => "trial2"));
    DB::rollBack();
    DB::commit();

then both the queries are getting inserted into Device table. This is a feature or bug?
Essentially I have cancelled the T2.

According to specs of MySQL, multilevel transactions are support.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
