### ISSUE TITLE
[5.1] Mandrill maildriver sends CC'ed and BCC'ed emails separately

### ISSUE THREAD

**Issue by devinfd** [laravel/framework#9875]
The subject says it. `\Illuminate\Mail\Transport\MandrillTransport@getToAddresses` combines the emails in a single TO array and sends them all separately. I consider this to be a huge bug or at the very least deceitful code. If I write `$message->cc('foo@example.com')` then I expect it to be CCed. I discovered this bug because I have a requirement to CC an address in every sent email. The recipient of that CC is not able to see who the email was sent to and therefore can not reply all.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by KennedyTedesco** [comment]
I can guarantee you that this is not a Laravel bug. The problem is on the Mandrill `send-raw` API.

I have tested here with these services:

- Mandrill (API)
- SES (API)

Results:

- **Mandrill**: The same problem describred by you.
- **SES**: Worked fine.

**Comment by devinfd** [comment]
Strange that the SES implementation works because the SesTransport class also combines the To, CC and BCC arrays into one.

Devin Dombrowski
dddesigns3@gmail.com

**Comment by GrahamCampbell** [comment]
See https://github.com/laravel/framework/issues/7276.

**Comment by devinfd** [comment]
Wow, even stranger that mandrill doesn't respect CCs normal behavior by default. Thanks Graham. Sorry for the red alert.
