### ISSUE TITLE
Route Group as appending to routes without an as.

### ISSUE THREAD

**Issue by Sladewill** [laravel/framework#9876]
If you define a route i.e a Post route without an as and you wrap it in a Route::group if you use as it appends the as to that as well, shouldn't it ignore those?

```php
Route::group(['as' => 'test.']) {
    Route::get('test', ['as' => 'index', 'uses' => 'Controller@method']);
    Route::post('test', 'Controller@postMethod');
}
```
Now it will output test.index and test. for the second.

**Comment by GrahamCampbell** [comment]
This has come up multiple times before, and this is the expected behaviour.
