### ISSUE TITLE
Pagination custom page name

### ISSUE THREAD

**Issue by ounos** [laravel/framework#9884]
https://github.com/laravel/framework/issues/8000

This issue still exists on v5.1. Will it be merged eventually ?

**Comment by GrahamCampbell** [comment]
This was merged into 5.0 thus is included in 5.1.

**Comment by GrahamCampbell** [comment]
Oh wait, this was actually only merged to 5.1.

**Comment by GrahamCampbell** [comment]
As you can see in my commit message: https://github.com/laravel/framework/commit/79f15d98809a48274a281dfae7fa69d66bf734d7.

**Comment by GrahamCampbell** [comment]
Either way, this feature has been available in EVERY 5.1 tag in existence.
