### ISSUE TITLE
AJAX is keeping the session alive on logout.

### ISSUE THREAD

**Issue by lazos99** [laravel/framework#9890]
I have an AJAX script that checks if the Forum is active or not. See the code below.
It's waiting a response from a CURL for 5seconds and if in those 5seconds do not get a reply I get false.

public function forumStatus() {
        if (!Request::ajax()) {
            return Response::make('Unauthorized', 401);
        }
        if(Forum::isAvailable(5)) {
            return Response::json(true);
        } else {
            return Response::json(false);
        }
    }

If during those 5 seconds do not get a reply and I logout if I click back and then access the admin page again the session will validate and the user will login even he clicked logout. I think the reason is because the AJAX script somehow refreshes the session after the logout.

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by lazos99** [comment]
I am wondering if this is a bug or not?
