### ISSUE TITLE
URL::forceSchema('https') doesn't affect paginator render() function

### ISSUE THREAD

**Issue by 2tunnels** [laravel/framework#9894]
So I used URL::forceSchema('https') to force https in url generation.
Everything works fine except `render` function from paginator.

```php
route('login'); // HTTPS
asset('css/app.css'); // HTTPS
$users->render(); // HTTP
```

**Comment by GrahamCampbell** [comment]
Thanks for reporting. Let me know if #10007 fixes your issue.

Please comment on the PR though rather than here again since I don't read comments on closed issues. :)

**Comment by Nandakumar-d** [comment]
Not working.

**Comment by webappbuilder** [comment]
+1
forceSchema('https') doesn't affect pagination urls.

**Comment by Kwaadpepper** [comment]
The issue is still present on laravel 7 and 8

**Comment by marty0678** [comment]
> The issue is still present on laravel 7 and 8

Can confirm on Laravel 8 it doesn't work, but the older, less ideal way `$this->app['request']->server->set('HTTPS', true);` does.
