### ISSUE TITLE
Ids cannot be written using facades

### ISSUE THREAD

**Issue by amonger** [laravel/framework#9895]
In Laravel 5.1 using a facade to write an id field fills the field with an empty string.

So in
```PHP
Item::create(['id'=>123]);
```
The id in an item row would be empty.

However

```PHP
$item = new Item;
$item->id = 123;
$item->save()
```
Works fine.

**Comment by GrahamCampbell** [comment]
That's not a facade.

**Comment by GrahamCampbell** [comment]
You probably need to set the incrementing property to false.

**Comment by GrahamCampbell** [comment]
Maybe check that mass assignment is allowed for the id column too.

**Comment by GrahamCampbell** [comment]
Otherwise, please ask on the forums.
