### ISSUE TITLE
DispatchesJobs cannot queue to a different connection in Laravel 5.1 

### ISSUE THREAD

**Issue by halaei** [laravel/framework#9896]
According to [Laravel queue documentation](http://laravel.com/docs/5.1/queues#pushing-jobs-onto-the-queue): 
> **Specifying The Queue For A Job**
...
> By pushing jobs to different queues, you may "categorize" your queued jobs, and even prioritize how many workers you assign to various queues. This **does not push jobs to different queue "connections"** as defined by your queue configuration file, but only to specific queues within a single connection.
...

**Question 1)** Is there any workaround to dynamically change the connection while dispatching jobs using `DispatchesJobs` trait? I want to be able to dispatch 2 jobs to 2 different queues (supposedly with different drivers and on different machines) during the lifetime of a single process of my Laravel application.

**Question 2)** Is it better to add this feature to DispatchesJobs trait?

 **Question 3)** Why queue connection and queue *name* are 2 separate concepts? I am really confused about it. Is it a real requirement for someone to push to multiple queues on the same connection? Can't he/she just push to multiple connections, each have a unique queue name?

`config/queues.php`:
```php
...
'connections' => [
        ...
        'redis' => [
            'driver' => 'redis',
            'connection' => 'confuses_me',
            'queue'  => 'who_really_needs_this',
            'expire' => 60,
        ],
       ....
]
```

**Comment by tampadesign** [comment]
Also interested in this. Can we get an update, please?

**Comment by pulkitjalan** [comment]
A possible workaround could be to add a `queue` method to your job. The dispatcher calls the `queue` method if one exists with the `queue` instance and the `job` instance as the parameters. https://github.com/laravel/framework/blob/5.1/src/Illuminate/Bus/Dispatcher.php#L241

Then in here you can maybe use the Facade to change the connection and push to the queue of your choice. However this means that any time this job is dispatched it will be push into this queue only.

This is not an ideal solution but does work...

```php
public function queue($queue, $job)
{
    return \Queue::connection('redis')->push($job);
}
```

**Comment by halaei** [comment]
Thanks @pulkitjalan 
I did not see that in code. Maybe we should request for update in documentation.

**Comment by halaei** [comment]
As @pulkitjalan mentioned, maybe it is not a very clear solution!

**Comment by halaei** [comment]
What is good about using dispatcher versus doing `Queue::connection('foo')->push(new Job)` is that the client code says "just do the job, I don't know how or when, and I don't care about dependency injection either".

I see 3 parts here:

1. What should be done (calling some handle() function). This is the responsibility of job and handler objects.
2. Queuing configuration (Should the job be queued?, on which queue? For how long should it be delayed?). This is currently  partially done via setting special properties (`queue` and `delay`) in the job object.
3. The act of executing itself: queuing and dequeuing (if necessary), dependency injection for handler and finally calling it. This is the responsibility of the dispatcher. But is partially handled via $job->queue() function, if exists.

To clear things I have a proposal:

1. getting rid of $job->queue() special function.
2. adding another special property to job that identify the connection, namely `queueConnection`.

This way, the part 1 and 2 will completely be done by job object and part 3 by dispatcher. Not a mix anymore.

But still there is a problem: job has 2 responsibility, and the number of special properties can go high. In order to fix that, we may put all the configurations into its own class, namely `QueueConfigurations` and then having only one special property inside the job of that type.

Shall I give it a try?
