### ISSUE TITLE
Display migration file when a migration fails

### ISSUE THREAD

**Issue by mathiasgrimm** [laravel/framework#9900]
Would be good to have such feature. Maybe there is a way to increase the verbosity of the output but I could not find it.

One way would be creating a MigrationException that would wrap the original exception and have an additional attribute and method that would contain the file name (including folder).

So in the MigrateCommand would try and catch that exception and print the file name along with the original error.

Something like this:
<pre>
try {
    $this->migrator->run($path, $pretend);
} catch (MigrationException $e) {
    $this->output->writeln("< error >Exception thrown in: {$e->getFileNameWithPath()}< / error >");
    throw $e;
}
</pre>

**Comment by mathiasgrimm** [comment]
Doest it make any sense?
I could submit the PR it that makes sense

**Comment by mathiasgrimm** [comment]
Another thing, maybe as an alternative, would be to have the ability to the make:migration specify a base migration class, and also specify in a config file what the default base migration class is. But that is further down the road.

**Comment by jadjoubran** [comment]
Increasing the verbosity level hasn't worked for you? 
-v
-vv
-vvv

These are the verbosity levels

**Comment by spiritix** [comment]
This should be moved into config:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Migrations/MigrationCreator.php#L169
