### ISSUE TITLE
Get arguments in Blade directive

### ISSUE THREAD

**Issue by zorx** [laravel/framework#9905]
Something is going wrong with args in blade directive, I'm using Laravel 5.1 (upgraded from 5.0), I was trying to create my own blade directive, but I discovered that argument is followed by (' and ')

Example : 
-----------

##### Template :
```php
`@mydirective('argument')`
```
##### Service Provider :

```php
Blade::directive('mydirective', function($argv) {
	dd($argv); // print ('argument') instead of argument
}
```

Actually, I can use a regex to retrieve my argument, but is it normal ?

**Comment by GrahamCampbell** [comment]
Works fine for me. Please review the docs and/or ask on the forums, and I'm sure someone can help out.
