### ISSUE TITLE
[5.1] Weird thing about Eloquent Collection

### ISSUE THREAD

**Issue by AaronJan** [laravel/framework#9910]
Replay:

```php
$users = \App\Models\User::all();  // Any eloquent model could do the trick
$users = $users->reject(function () { return true; });

dd(empty($users), $users->isEmpty());
```

My results are:
```
false

true
```

I'm using `Laravel 5.1.9`, `PHP 5.6.9`, don't know why, I'm panicked.

**Comment by lukasgeiter** [comment]
Well the collection itself is still an object and definitely not empty in the way `empty()` checks for it. You could call `->all()` to get the actual array of items that the collection holds:

    empty($users->all())

**Comment by AaronJan** [comment]
Sorry for my idiotic issue, I thought it's a thing that `Collection` implemented.

I'm so sorry.

And thank you @lukasgeiter .
