### ISSUE TITLE
Config file is read from vendor

### ISSUE THREAD

**Issue by MrAudioGuy** [laravel/framework#9912]
Hi,

I have come across an issue in Laravel 4.2 that I can't quietly point the source of it. I have developed a wrapper around oracle OCI, It can be found [here](http://github.com/MrAudioGuy/oci-classes). 

While in use in my other projects, It works fine in development environment but due to restricted access to the internet in production environment, I copy the whole project and paste in the desired destination in production and it starts reading config files for the package from the `vendor/package/src/config` directory instead of the `app/config/package/vendor/package`.

Since I can't have access to the production server abundantly, I can't debug step by step through it. I would try to do so on a replica if I could and told you what's going on. Sorry for that.

My dev environment:

     OS: Windows 8.1
     HTTPServer: Apache2
     PHP: 5.6.4, Zend Engine 2.6.0 w/ xDebug 2.2.5

My production environment:

     OS: CentOS 6
     HTTPServer: nginx
     PHP: php-fpm 5.5

**Comment by GrahamCampbell** [comment]
Please ask on the forums.
