### ISSUE TITLE
Coverage?

### ISSUE THREAD

**Issue by Lewiscowles1986** [laravel/framework#9913]
Hi, do you plan to show coverage for the framework at any point?

**Comment by GrahamCampbell** [comment]
No, sorry.

**Comment by GrahamCampbell** [comment]
Coverage is a bit of a lie about the truth of the test coverage anyway.

**Comment by Lewiscowles1986** [comment]
Well it only shows lines covered, rather than situations covered I agree, but it also scores those lines for the number of tests that cover those lines, so while I accept your answer and your viewpoint, it is incomplete and could warrant some further reading / understanding of the tools :wink: 

Thanks anyway for the swift response
