### ISSUE TITLE
Max in Validator does not handle numbers

### ISSUE THREAD

**Issue by blrobin2** [laravel/framework#9919]
When I try to validate that a number is no larger than a given max, the validator does not count it as a failure. [The documentation states that max is meant for numerics, strings and files](http://laravel.com/docs/5.1/validation#rule-max), so I the following should fire a failure.

[Screenshot](http://i.imgur.com/g2YPZ9j.png)

**Comment by GrahamCampbell** [comment]
That's the expected behaviour. The length is 3 so is less than 200.

**Comment by GrahamCampbell** [comment]
You'll need to cast to an int to get numeric comparisons.

**Comment by blrobin2** [comment]
Can that be stated somewhere in the documentation then, instead of insinuating that I can pass the request in as is, like the examples show? Why should I assume that I need to recast the values of my incoming request, especially when PHP's dynamic typing is usually pretty tolerant of such behavior?

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by GrahamCampbell** [comment]
This has to be an error on your end. Our unit tests prove this isn't a bug: https://github.com/laravel/framework/blob/5.1/tests/Validation/ValidationValidatorTest.php#L753.

**Comment by taylorotwell** [comment]
You just need to add the `numeric` rule in addition to your `max` rule so Laravel knows to treat it as a number.

**Comment by blrobin2** [comment]
Hey Taylor, below is an example where I try that as well...

[Screenshot](http://i.imgur.com/P0EnG1R.png)
