### ISSUE TITLE
Possible bug in Middleware After

### ISSUE THREAD

**Issue by ryrobbo** [laravel/framework#9920]
So I have a middleware class that is invoked by a controller via $this->middleware();

    public function handle($request, Closure $next)
    {
        $response = $next($request);
        
        die('yeah');

        return $response;
    }

The above code doesn't kill the script and echo 'yeah'.

However, this code does:

    public function handle($request, Closure $next)
    {
        die('yeah');
        
        $response = $next($request);
        
        return $response;
    }

This can't be an issue related to how my middleware is configured as it does run the method when you insert the die() before $response = $next($request);

I have had the "after middleware" feature working fine but now it just doesn't want to work. I'm on version 5.1.0.

**Comment by GrahamCampbell** [comment]
Only 5.1.10 is supported.

**Comment by GrahamCampbell** [comment]
Closing this as I can't replicate.

**Comment by GrahamCampbell** [comment]
Feel free to ask for help on the forums though. ;)

**Comment by ryrobbo** [comment]
I apologise for wasting your time but I found out why the code wasn't executing. I wasn't returning a response in the controller action therefore, there was no response object to process in the stack.

Maybe this could have been avoided by throwing an exception if there isn't a valid Response object to process?
