### ISSUE TITLE
Default users table migration creates table with field username as name

### ISSUE THREAD

**Issue by funyug** [laravel/framework#9926]
The default users table migration generates users table with field 'name' instead of 'username' which breaks the use of the property $username in authcontroller

**Comment by arcdigital** [comment]
Could you provide some more information? The email field is supposed to be used as the "username" and out of the box everything works fine.

**Comment by funyug** [comment]
Found out in laravel 5's documentation introduced a new property that allows to change the default username with the use of a property in the auth controller. It wasnt mentioned in the laravel 5.1 docs.
