### ISSUE TITLE
Laravel 5.1 - test database with SQLite gives 'no such index' error on migration down()

### ISSUE THREAD

**Issue by rephiscorth** [laravel/framework#9933]
The following schema builder code works **perfectly** when running `php artisan migrate` and `php artisan migrate:rollback` on **local** and **staging** (production-like) environment. This will run an `alter table` statement to modify an existing table.

*Note: since rows are empty, there is no need to set `nullable` or `default value` to the `category_id`:*

    // up
    $table->integer('category_id')->unsigned()->index();
	$table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');

    // down
    $table->dropForeign('stores_category_id_foreign');
    $table->dropColumn('category_id');

I'm running my functional tests with **SQLite** using `:memory:` configuration, and I'm getting the following error when the database rolls back (thanks to the `DatabaseMigrations` trait)

    General error: 1 no such index: stores_category_id_index (SQL: DROP INDEX stores_category_id_index)

Why is this happening, is there something I have to configure on SQLite that I don't know of?

**Comment by Feijs** [comment]
It's more of a workaround, but I've found that doing each drop operation in a separate Schema builder works for SQLite

**Comment by GrahamCampbell** [comment]
Oh yeh, that's what you're meant to do. That's why migrations are meant to be "drop column x" rather than drop multiple columns. :)

**Comment by peterpan666** [comment]
This solved the issue I was having, if it makes sens, you can keep dropping multiple columns and indices in one migration but you must separate them like so

```php
Schema::table('your_table', function (Blueprint $table) {
    $table->dropForeign('stores_category_id_foreign');
});

Schema::table('your_table', function (Blueprint $table) {
    $table->dropColumn('category_id');
});
```
