### ISSUE TITLE
array_forget removes wrong keys

### ISSUE THREAD

**Issue by lazos99** [laravel/framework#9937]
I am using Laravel 4.2

If I have an array similar to the following... 

array('shop' => array('cart' => array(150 => 0)))

Then if I use array_forget('shop.final.cart') will delete what is above which is wrong.
The above should be only removed if I call array_forget('shop.cart').

**Comment by overtrue** [comment]
...

**Comment by lazos99** [comment]
...?

**Comment by shssoichiro** [comment]
At first I had the same "..." thought (because Laravel 4.2) but I was able to reproduce this in 5.1 with a test case. I assume this is not the intended behavior.

I'll see if I can put together a patch.

**Comment by shssoichiro** [comment]
Actually I'm curious if this is the intended behavior. It seems that it should be, but I'd like to confirm.

ping @taylorotwell

**Comment by GrahamCampbell** [comment]
Only Laravel 5.1.10 is supported.

**Comment by GrahamCampbell** [comment]
> but I was able to reproduce this in 5.1

Ok, right. Ping @taylorotwell.

**Comment by lazos99** [comment]
Well if this is not the intended behavior then maybe we need to update the documentation because I think is misleading.

"The array_forget method will remove a given key / value pair from a deeply nested array using "dot" notation."

For me the above sentence is telling be give me any kind of keys with the dot notation and If I find this nested keys I will remove the value.

Also guys is it ok to post issues for 4.2 here or not? If not where then?

**Comment by bmitch** [comment]
Pretty sure there is an issue with this function. The helper function array_forget uses Illuminate\Support\Arr::forget. I wrote a few tests to ensure it works as expected:


```
        $array = ['products' => ['desk' => ['price' => 100]]];
        Arr::forget($array, 'products.desk');
        $this->assertEquals(['products' => []], $array);

        $array = ['products' => ['desk' => ['price' => 100]]];
        Arr::forget($array, 'products.desk.price');
        $this->assertEquals(['products' => ['desk' => []]], $array);

        $array = ['products' => ['desk' => ['price' => 100]]];
        Arr::forget($array, 'products.final.price');
        $this->assertEquals(['products' => ['desk' => ['price' => 100]]], $array);

        // Fails
        $array = ['shop' => ['cart' => [150 => 0]]];
        Arr::forget($array, 'shop.final.cart');
        $this->assertEquals(['shop' => ['cart' => [150 => 0]]], $array);

        // The last test leaves:
        // array:1 [
        //   "shop" => []
        // ]

```

So it seems if the second array element in the dot notation doesn't exist but the following one does, it will erase that following one.
