### ISSUE TITLE
Global scopes are applied in whereHas callback when they shouldn't

### ISSUE THREAD

**Issue by phaza** [laravel/framework#9940]
```PHP
// Basic has call - 'deleted_at is null' applied by default
>>> User::has('posts')->toSql()
=> "select * from `users` where (select count(*) from `posts` where `posts`.`user_id` = `users`.`id` and `posts`.`deleted_at` is null) >= 1"

// Now let's remove the 'deleted_at is null' constraint in the callback
>>> User::whereHas('posts', function ($q) { $q->withTrashed(); })->toSql()
=> "select * from `users` where (select count(*) from `posts` where `posts`.`user_id` = `users`.`id` 

and `posts`.`deleted_at` is null // SOFT DELETE CONSTRAINT SHOULDN'T BE HERE ANYMORE

) >= 1"
>>> 
```

All information is here: https://github.com/laravel/framework/pull/9696

I think it's very disconcerting that Taylor simply closes a bug, because the original bug reporter didn't fix it. The bug is still there, the test case is still valid. Why on earth would you close down a bug, with a test case, without fixing it?

This ruins the use for global scopes, but luckily we can live without them.

**Comment by Feijs** [comment]
@Max13 Could you provide (a link to) the implementation of your `onlyUnofficial` scope as referenced in: https://github.com/laravel/framework/pull/9696 ? Specifically the `remove` method.

I'd like to reproduce the error you found.
