### ISSUE TITLE
[Socialite] Eliminate dependency on old version of guzzle

### ISSUE THREAD

**Issue by atrauzzi** [laravel/framework#9951]
Right now it looks like for Oauth1 operations, [Socialite is using](https://github.com/laravel/socialite/blob/2.0/composer.json#L18) [an outdated version of Guzzle](https://github.com/thephpleague/oauth1-client/blob/master/composer.json#L7) which will not be receiving updates soon.

Reason being, I'm currently troubleshooting some cURL related issues on Google App Engine and in some situations, I'm required to fall back to stream wrappers.  Guzzle 3 unfortunately requires cURL and does not support any underlying alternative implementations.

**Comment by GrahamCampbell** [comment]
Could you send PR to that repo to get it updated then?

**Comment by GrahamCampbell** [comment]
Otherwise, I'm not sure what else we can do?

**Comment by atrauzzi** [comment]
Maybe, I have [created a ticket](https://github.com/thephpleague/oauth1-client/issues/31) until it's a little more imminent for me.

We should monitor that issue in case we end up at guzzle's EOL and the work still hasn't been done.

**Comment by GrahamCampbell** [comment]
Not sure guzzle's EOL is a massive issue though tbh. If it works, then it works. It only becomes an issue if security issues arise, though I'm sure Michael would patch them in guzzle 3 if such issues were discovered.

**Comment by atrauzzi** [comment]
The problem is that socialite is using two guzzle libraries. The older one doesn't support falling back to streams.  This poses an issue on Google app engine that I'm already encountering currently.

**Comment by GrahamCampbell** [comment]
Ping @taylorotwell.

**Comment by taylorotwell** [comment]
Not much we can do about this until League releases a new tag that supports
Guzzle 6. ping @bencorlett

**Comment by bencorlett** [comment]
It's [on the way](https://github.com/thephpleague/oauth1-client/pull/35). :)
