### ISSUE TITLE
Pagination fails when items number is less than zero

### ISSUE THREAD

**Issue by phpawy** [laravel/framework#9960]
In pagination , If you tried to provide a number of items < 0

for example:
Model::paginate(-5);

leads to executing a query with wrong syntax like this:
Select * from `model` offset 0
which will result in a not descriptive error message

I suggest throwing an error telling the user that limit provided was incorrect?

**Comment by GrahamCampbell** [comment]
We're open to PRs.

**Comment by phpawy** [comment]
@GrahamCampbell 
sorry for the question , but what you mean by PRs?
Im newbie here :)

**Comment by GrahamCampbell** [comment]
As in, please send a PR. :)

**Comment by phpawy** [comment]
ok, Ill do
