### ISSUE TITLE
TestCase call() with HTTP headers not working as it is expected

### ISSUE THREAD

**Issue by vaske** [laravel/framework#9966]
I'm trying to add unit test for file upload, I followed up procedure what has been suggested on several points over the laravel websites, here is my current code

```
$uploadedFile = new Symfony\Component\HttpFoundation\File\UploadedFile(
            storage_path() . '/uploads/sample.mp4', 
            'sample.mp4');        
$this->be($this->user);
$response = $this->call('POST', 
                        '/api/v1/uploads', 
                        array('key' => 'test'),
                        [], // cookies
                        array('file' => [$uploadedFile]), // file(s) 
                        [], // server
                        array('CONTENT_TYPE' => 'multipart/form-data'));
```

Seems like invalid header has been set, when I add `$_SERVER['CONTENT_TYPE'] = 'multipart/form-data';` server variable is visible, but keep getting file not found error, seems like call() do not fully simulate regular usage, thoughts?

**Comment by GrahamCampbell** [comment]
You should never be using that super global variable.

**Comment by vaske** [comment]
@GrahamCampbell I know otherwise call() do not set it properly, and in my upload class I do not see it.
