### ISSUE TITLE
[5.1] Request with 'CONTENT_TYPE'='application/json' behaves incorrectly with unit tests

### ISSUE THREAD

**Issue by samlev** [laravel/framework#9970]
Possibly related to an update in the Symphony framework.

### How to reproduce:

`app/Http/routes.php`:

```php
Route::post('test', 'TestController@postTest');
```

`app/Exceptions/Handler.php`

```php
class Handler extends ExceptionHandler
{
    public function render($request, Exception $e)
    {
        /**
         * Solution found from http://stackoverflow.com/a/28947051/1172464
         */
        // If the request wants JSON (AJAX doesn't always want JSON)
        if ($request->wantsJson()) {
            // Define the response
            $response = [
                'errors' => 'Sorry, something went wrong.'
            ];

            // If the app is in debug mode
            if (config('app.debug')) {
                // Add the exception class name, message and stack trace to response
                $response['exception'] = get_class($e); // Reflection might be better here
                $response['message'] = $e->getMessage();
                $response['trace'] = $e->getTrace();
            }

            // Default response of 400
            $status = 400;

            // If this exception is an instance of HttpException
            if ($this->isHttpException($e)) {
                // Grab the HTTP status code from the Exception
                $status = $e->getStatusCode();
            }

            // Return a JSON response with the response array and status code
            return response()->json($response, $status);
        }

        // Default to the parent class' implementation of handler
        return parent::render($request, $e);
    }
}
```

`app/Http/Controllers/TestController.php`:

```php
class TestController extends Controller
{
    public function postTest(Request $request) {
        $req = ['json' => (array) $request->json(), 'get' => $request->get('foo')];
        $this->validate($request, ['foo' => 'required']);
        return ['success' => true, 'request' => $req];
    }
}
```

`tests/JsonTest.php`:

```php
class JsonTest extends TestCase
{
    use WithoutMiddleware;

    public function testPostJson()
    {
        $headers = [];
        $headers['CONTENT_TYPE'] = 'application/json';
        $headers['Accept'] = 'application/json';

        $this->post('/test', ['foo' => 'bar'], $headers)->seeJson(['success' => true, 'get' => 'bar']);
    }

    public function testCallJson()
    {
        $headers = [];
        $headers['CONTENT_TYPE'] = 'application/json';
        $headers['Accept'] = 'application/json';

        $server = $this->transformHeadersToServerVars($headers);

        $this->call('POST', '/test', ['foo' => 'bar'], [], [], $server);

        $this->seeJson(['success' => true, 'get' => 'bar']);
    }

    public function testCallJsonBody() {
        $headers = [];
        $headers['CONTENT_TYPE'] = 'application/json';
        $headers['Accept'] = 'application/json';

        $server = $this->transformHeadersToServerVars($headers);

        $this->call('POST', '/test', [], [], [], $server, json_encode(['foo' => 'bar']));

        $this->seeJson(['success' => true, 'get' => 'bar']);
    }

    public function testCallJsonBoth() {
        $headers = [];
        $headers['CONTENT_TYPE'] = 'application/json';
        $headers['Accept'] = 'application/json';

        $server = $this->transformHeadersToServerVars($headers);

        $this->call('POST', '/test', ['foo' => 'bar'], [], [], $server, json_encode(['foo' => 'bar']));

        $this->seeJson(['success' => true, 'get' => 'bar']);
    }
}
```

### Expected

4 successes

### Actual

```
$ phpunit 
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

FFF.

Time: 216 ms, Memory: 21.50Mb

There were 3 failures:

1) JsonTest::testPostJson
Unable to find JSON fragment ["get":"bar"] within [{"foo":["The foo field is required."]}].
Failed asserting that false is true.

/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:420
/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:399
/var/www/vhosts/laravel/testbed/tests/JsonTest.php:15

2) JsonTest::testCallJson
Unable to find JSON fragment ["get":"bar"] within [{"foo":["The foo field is required."]}].
Failed asserting that false is true.

/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:420
/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:399
/var/www/vhosts/laravel/testbed/tests/JsonTest.php:28

3) JsonTest::testCallJsonBody
Unable to find JSON fragment ["get":"bar"] within [{"request":{"get":null,"json":{"":{"foo":"bar"}}},"success":true}].
Failed asserting that false is true.

/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:420
/var/www/vhosts/laravel/testbed/vendor/laravel/framework/src/Illuminate/Foundation/Testing/CrawlerTrait.php:399
/var/www/vhosts/laravel/testbed/tests/JsonTest.php:40

FAILURES!
Tests: 4, Assertions: 5, Failures: 3.
```

### Analysis:

* If data is passed as request parameters, then it fails to validate
* If data is passed as body content, validate works, but 'get' fails
* If data is passed as both body content and parameters, then validate works and 'get' works

~~If data is passed as body content, then the 'json' available to the request is wrapped in a keyless array:~~

~~`{"json":{"":{"foo":"bar"}}}`~~

Just realised that this is because `json()` returns a `ParameterBag` and not an array.

### Notes:

This doesn't affect regular http POST requests where the content is attached as body content (as in from angularjs). This only requests posts within unit tests.

**Comment by GrahamCampbell** [comment]
The content type of the request has NOTHING to do with the acceptable response type.

**Comment by samlev** [comment]
I think you're missing the point.

`$request->get()` should retrieve data from the same place as  `$this->validate($request)` uses.

i.e. if the validator passes, you should be able to retrieve content from `get()`.

**Comment by kidshenlong** [comment]
I'm not sure why this was closed. As it currently stands the test post(and put, patch and delete for that matter) method does not allow you to post raw JSON essentially ignoring the `'HTTP_CONTENT_TYPE' => 'application/json'` header.

**Comment by GrahamCampbell** [comment]
You can't be using it right. Works fine for me.

**Comment by kidshenlong** [comment]
Could post an example of your usage in a test and how your controller handles the JSON?

**Comment by samlev** [comment]
I gave you some files to test/replicate the issue.

Remember to run composer update first (I think it may be a change to how the symfony interface works which has affected how the Laravel interface works)

**Comment by GrahamCampbell** [comment]
Using wants json like that is wrong too.

**Comment by GrahamCampbell** [comment]
You should check if it accepts json, otherwise you might return the wrong content type.

**Comment by samlev** [comment]
Ok, I feel that you're focusing on the wrong aspect.

The problem isn't with the response. It's with the Request. When you set `CONTENT_TYPE=application/json` on a request:

* `$request->get()` doesn't look for data that was passed as json body content. It looks for POST parameters only.
* `$this->validate()` doesn't look at POST parameters, it uses body content only.

`validate` is working correctly for a `CONTENT_TYPE=application/json` request, `get` is not.

**Comment by samlev** [comment]
The only way to get it to work correctly in a unit test is to post the data as both body content *and* as POST parameters.

**Comment by samlev** [comment]
Ignore the exception handler part entirely. That's only there to make testing easier when the validator (inevitably) fails.

**Comment by samlev** [comment]
Added pull request #9971 to solve this issue.

**Comment by kidshenlong** [comment]
Hmmm I thought the issue was more closely related to Laravel's HTTP test method that its request method?

As json requests needed to be passed as the content parameter of the call method rather than the parameter method like in your code above.

**Comment by samlev** [comment]
I'm not entirely sure why it responds differently to actual requests than it does to testing requests. My best guess is either the server does some form of translation, or the browser claims to send one but actually sends both.

Either way, this is a definite bug in the `Request` class.

**Comment by andrewmclagan** [comment]
Agreed, how could one simulate a `application/xml` request when testing otherwise?
