### ISSUE TITLE
queue:work - No timeout option 

### ISSUE THREAD

**Issue by TheTechnoMan** [laravel/framework#9975]
Hey,

sadly there is there no timeout option for queue:work but for queue:listen. Not sure if that has been missed, I do however see no reason to not add it. I would have submit a pull request, sadly I am not to familar with what's going on behind the scenes in Laravel.

Thank you!

**Comment by GrahamCampbell** [comment]
It's not really possible, sorry, a bit like the deamon worker can't have a timeout.
