### ISSUE TITLE
whereHas() not working with MorphTo()

### ISSUE THREAD

**Issue by marcusmota** [laravel/framework#9976]
Hi, i'm trying to make this query with mophto() relationships 

return Os::orderBy('id', 'DESC')
            ->with('user')->whereHas('user', function ($query) {
                $query->where('name', 'like', '%marcus%');
                })
            ->paginate(10);

My relationship is fine, i wrote like the docs, when i try return Os::with('user')->first(); my json return the os with user data (so my relationships is working fine) but when i try make some query relationships i always have a exception 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'where clause' (SQL: select count(*) as aggregate from `os` where (select count(*) from `os` as `self_29901d9db2fdef10c1199ad16cd17df0` where `self_29901d9db2fdef10c1199ad16cd17df0`.`id` = `os`.`user_id` and `name` like %marcus%) >= 1)

there's another issue with the same problem https://github.com/laravel/framework/issues/5429

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by GrahamCampbell** [comment]
That other issue was marked as no-fix anyway, sorry.
