### ISSUE TITLE
Application Testing: selectors with square brackets in their name only work if `id` and `name` match

### ISSUE THREAD

**Issue by smallhadroncollider** [laravel/framework#9978]
When doing application testing if a form field has `[]` in its name (e.g. to denote a multiple select).

It is sometimes desirable to have a different `id` - say on a page with multiple forms.

---

#### Doesn't work when `id` and `name` are different

```
<select name="name[]" id="some-id" multiple>
    <option value="1">Item 1</option>
    <option value="2">Item 2</option>
</select>
```

**Running `$this->visit("/form")->select(1, 'name')`:**
Error: `Nothing matched the filter [name] CSS query`

**Running `$this->visit("/form")->select(1, '#some-id')`:**
Error: `Unreachable field "some-id"`

---

#### Works when `id` and `name` match

```
<select name="name[]" id="name" multiple>
    <option value="1">Item 1</option>
    <option value="2">Item 2</option>
</select>
```

**Running `$this->visit("/form")->select(1, 'name')`:**
Works

**Running `$this->visit("/form")->select(1, '#name')`:**
Works

**Comment by bmitch** [comment]
I tried duplicating using your HTML and PHP code.

```
$this->visit("/form")->select(1, 'name');
```
Produced the same error you received.

```
$this->visit("/form")->select(1, '#some-id');
```
Didn't produce any error for me.

The element is being selected using the Symfony Dom Crawler. So I'm not sure if it's an issue with attributes that contain '[]' in the selector being passed to the Dom Crawler or in the Dom Crawler itself.
