### ISSUE TITLE
SQLite forceDelete via hasManyThrough doesn't work as expected

### ISSUE THREAD

**Issue by stokic** [laravel/framework#9979]
Say you have a model User with something like:

```
static::deleted(function (\User $user) {
    $user->transactions()->forceDelete();
});
```

and relationship defined as:

```
public function transactions()
{
    return $this->hasManyThrough('Transaction', 'Account');
}
```

When deleting the user "cascaded" delete will fail, the reason is the Grammar for mysql and sqlite are different, sqlite Grammar builds delete like this:

```
    /**
     * Compile a delete statement into SQL.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return string
     */
    public function compileDelete(Builder $query)
    {
        $table = $this->wrapTable($query->from);


        $where = is_array($query->wheres) ? $this->compileWheres($query) : '';

        return trim("delete from $table ".$where);
    }

```

ie. not taking into account joins, limits etc...

While I understand that sqlite doesn't allow inner joins on delete, which mysql does, I still think that either:

- it should work differently in sql ( subquery in WHERE comes to mind? )
- it should be documented that the above situation will cause an issue (which I've learned the hard way ;) )

**Comment by GrahamCampbell** [comment]
Is this still an issue in the latest 5.1 or 5.2?

**Comment by stokic** [comment]
Haven't tested, I'll try to catch some time today to check if it's still present in 5.1
