### ISSUE TITLE
Validating input arrays bug if unique:tablename rule is used

### ISSUE THREAD

**Issue by DarioCorno** [laravel/framework#9980]
I'm using Eric Barnes approach at validating form input arrays, If I create a rule function like this ina a custom Request : 

```
foreach($forminputs as $idx=>$input) {
    ....
    $rules['username.'.$idx] = 'required|unique:users';
    ....
}
```

The Connection gives me an error of Column not found: 1054 Unknown column 'username.4'  (as an example).  It looks like when using arrays the index part is not removed before creating the validation query.

Am I doing something wrong or is this a bug?

**Comment by lukasgeiter** [comment]
Just specify the column name:

    'unique:users,username'

**Comment by arrilot** [comment]
Yes, you need to specify the column name if it doesn't fully match the key you have.
Nothing wrong here.
