### ISSUE TITLE
[Request] Get another attribute's displayable name inside Illuminate\Validation\Factory::replacer callback

### ISSUE THREAD

**Issue by vincekovacs** [laravel/framework#9982]
I wrote validation rule something like `different`. The validation rule checks another field value. When it fails then output message like `The :attribute and :other must be different.`. Here `:other` is another field attribute, so I want output this attribute’s displayable name. If `Illuminate\Validation\Validator::getAttribute` method would be public that will be solve this problem.

**Comment by prady00** [comment]
Making it public? 
May you please explain on it a little more?

**Comment by vincekovacs** [comment]
I show what I want to accomplish:

I writted a rule `empty_if` that check if field under validation is empty if another field is present in input array (like required_if, just working in reversed way). 

Rule code is:

```php
$this->app->make('Illuminate\Validation\Factory')
                  ->extend('empty_if', function ($attribute, $value, $parameters) {
                      return !$this->app->make('Illuminate\Http\Request')->has($parameters[0]) || $value === '';
                  });
```

I added message to `resources/lang/{locale}/validation.php` file:
```php
// ...
'empty_if' => 'The :attribute field have to be empty when :other field is present.',
// ...
```

Usage:

I have form with two input fields. I want that if one field is filled than another field remain empty.

Html Code

```html
<!-- some form -->
<input name="field_first" />
<input name="field_second" />
```

Form Request:

```php
class SampleFormRequest extends FormRequest
{
    public function rules()
    {
        return [
            'field_first'  => 'empty_if:field_second',
            'field_second' => 'empty_if:field_first',
        ];
    }

    public function attributes()
    {
        return [
            'field_first'  => 'First',
            'field_second' => 'Second',
        ];
    }
}
```

When I filled both fields, I got following error messages:

* `The First value field have to be empty when :other is present.`
* `The Second value field have to be empty when :other is present.`

But I want that :other attribute will be translated to correct attribute display name.

* `The First field have to be empty when Second field is present.`
* `The Second field have to be empty when First field is present.`

Or there is another way to reach this functionality?

**Comment by rkgrep** [comment]
Use `replacer` method
````php
$this->app->make('Illuminate\Validation\Factory')->replacer('empty_if', function ($message, $attribute, $rule, $parameters) {
    return str_replace(':other', $YOUR_REPLACEMENT, $message);
});
````

**Comment by Decadence** [comment]
He wants to get nice name for field which name is used as parameters, not just replace it by param value.
It could be reached by using $validator->getAttribute($name) like it does replaceRequiredIf method for example.
Two problems are here: You can't get current validator in replacer and getAttribute method is protected.
Now I don't see the way to do it without extending Validator like here: [http://stackoverflow.com/questions/37856943/laravel-validator-get-attribute-names-in-replacer](url)
So I have not much understanding why this is closed because `replacer` is not solution.
