### ISSUE TITLE
Can't mock "Storage::get()" and "File::get()".

### ISSUE THREAD

**Issue by budhajeewa** [laravel/framework#9985]
Neither `Storage::get()` nor `File::get()` can be mocked in Mockery. It returns the `get() cannot be mocked as it a protected method and mocking protected methods is not allowed for this mock`.

Mockery seems to allow mocking protected methods now using `shouldAllowMockingProtectedMethods`, it'll be great,

1. if Laravel supported mocking protected methods in facades,
1. or making above methods public.

**Comment by Sladewill** [comment]
This isn't a Laravel thing, its entirely mockery and its an option so google on Mockery how to use protected methods.

**Comment by budhajeewa** [comment]
@Sladewill As I mentioned in my original post, what you say is possible in Mockery's `shouldAllowMockingProtectedMethods` method. However, Laravel's facade mocking feature seems not to have incorporated that.

**Comment by budhajeewa** [comment]
Found a workaround.

Do not refer to facade method like following:

```
$fileContent = \Storage::get ( $path );
```
Instead use absolute class path

```
$fileContent = app ( Illuminate\Contracts\Filesystem\Factory::class ) -> get ( $path );
```

or use the _Service Container Binding Key_ (My choice.).

```
$fileContent = app ( 'filesystem' ) -> get ( $path );
```

Still, I'd love to see a fix for this.

**Comment by budhajeewa** [comment]
@GrahamCampbell Why?

**Comment by budhajeewa** [comment]
@taylorotwell Shouldn't I bother submitting ideas in the future if they get dismissed without even a slightest explanation why?
