### ISSUE TITLE
Send route param to middleware as argument

### ISSUE THREAD

**Issue by ventaquil** [laravel/framework#9986]
Can I sent to middleware parameter from router as argument?

For simple:

```php
    Route::get('test/{param}',['middleware'=>['testing:{param}'],'uses'=>'TestController@method']);
```

Is there in Laravel isset method like this? I know about `Route::current()->parameters()` but I want to find better method.

**Comment by GrahamCampbell** [comment]
No, sorry.

**Comment by GrahamCampbell** [comment]
Also, `$request->route()` is probably better.

**Comment by ventaquil** [comment]
I hope you will add something like that in future. Thank you.
