### ISSUE TITLE
Explicitly define permissions for Local driver 

### ISSUE THREAD

**Issue by bcat-eu** [laravel/framework#9987]
When this change goes out, it would be nice to set the `$permissions` array in filesystems config

https://github.com/thephpleague/flysystem/pull/542

The reason: At the moment we have 755 hardcoded which makes console and http parts working under different Linux users unable to change each others files.

**Comment by prady00** [comment]
Can you please explain on it a little more?

**Comment by bcat-eu** [comment]
@prady00 at the moment "public" flysystem permission is defined here

https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Local.php#L37

so any directories will be 755 unless local driver is extended to change this number. flysystem guys are aware of that, see these issue
https://github.com/thephpleague/flysystem/issues/541
and earlier this commit
https://github.com/thephpleague/flysystem/pull/525

so they'll make the permissions variable configurable via constructor. After they're done it would make sense to add the permissions array to laravels config, otherwise it will still be 755 as per default

**Comment by meriial** [comment]
Along a similar vein, it configuring file permissions for FlySystem becomes a reality, it would make sense to be able to explicitly set the file permissions of the log files. Right now, if I want to set them to something other than 644, I have to add the following:

```
$app->configureMonologUsing(function($monolog) use ($app) {
	$path = $app->storagePath().'/logs/laravel.log';
	$days = $app->make('config')->get('app.log_max_files', 5);
	$level = MonologLogger::DEBUG;
	$handler = new RotatingFileHandler($path, $days, $level, true, 0664);
    $monolog->pushHandler($handler);
});
```

Monolog provides the capacity to do this, Laravel doesn't use it.
