### ISSUE TITLE
[Proposal] Validation rule for hexadecimal values 

### ISSUE THREAD

**Issue by prady00** [laravel/framework#9988]
This will be useful for checking hexadecimal values, for instance the color hex like #000000 (black) and #ffffff (white)

**Comment by bmitch** [comment]
@prady00  Are you thinking about submitting a pull request? If not I can give it a go.

**Comment by lukasgeiter** [comment]
Couldn't this easily be accomplished using the `regex` validation rule?

**Comment by bmitch** [comment]
Yeah that's a good point @lukasgeiter

**Comment by prady00** [comment]
@bmitch : I've already coded it for one of my current project, just need to move it to Validator.php and do a simple PR.

**Comment by prady00** [comment]
@lukasgeiter using regex all types of validations can be performed. IP, alpha, numbers, URLs etc.

We include easy subsystem for something fast and non-time consuming in terms of development.

**Comment by lukasgeiter** [comment]
@prady00 Maybe not all types, but in most cases that's true. I just wanted to point out the possibility of using the `regex` validation rule, in case someone didn't know about it. I'm not particularly against it.

Just send the PR and we'll see if Taylor is up for it.
