### ISSUE TITLE
Collection every() method is missing

### ISSUE THREAD

**Issue by thkthebest** [laravel/framework#9991]
Weird issue. In the Illuminate/Support/Collection.php, the ```every()``` method is missing. Running a fresh installation of Laravel doesn't seem to help as the method is still missing.

I see the method here:
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Support/Collection.php

But in the subtree split of the Illuminate Support component, it doesn't exist:
https://github.com/illuminate/support/blob/master/Collection.php

**Comment by GrahamCampbell** [comment]
It'll be available soon.
