### ISSUE TITLE
[5.1] Support for "application/vnd.api+json" as valid content type, in Illuminate\Http\Request

### ISSUE THREAD

**Issue by aedart** [laravel/framework#9997]
If some kind of a client is sending json data, specified as `application/vnd.api+json`, then the `Illuminate\Http\Request` class doesn't appear accept this, as a valid json request, via the `isJson()` method. Upon further review of the core code, I see that `application/json` is specified in a few locations...

The main reason why supporting the specified content type would be nice, is due to the [Json API standard](http://jsonapi.org/format/#content-negotiation). However, I'm not really sure if there is a quick work-around for this?

Currently I have only tested this manually via the [Postman](https://www.getpostman.com/) application, by sending a simple json request, using the mentioned content-type, and dumping the following

```php
    public function store(Request $request)
    {
        //dd(getallheaders());
        dd($request->isJson()); // Returns false, expected it to be true
        //dd($request->acceptsJson());
        //dd($request->headers);
    }
```

**Comment by GrahamCampbell** [comment]
You're getting mixed up with the accept header.

**Comment by GrahamCampbell** [comment]
isJson is telling you about the content type of the request, NOT the if json an acceptable content type for the response.

**Comment by aedart** [comment]
Hi mate - once again, thank for your quick reply.
I'll look further into it the accept headers vs. isJson method...
